Round stats
TauCetiStation/TauCetiClassic pull request #10015
Opened 2022-09-08 11:55 UTC by notkripton

## Описание изменений

https://user-images.githubusercontent.com/75007994/189112058-1ecb3e96-2d0e-495a-afad-dd18e31a0a60.mp4

Титры раунда теперь можно открывать через ссылку, которая появится в чате или через кнопку Show Last Scoreboard во вкладке оок. Нажатие кнопки в раунде покажет титры последнего завершенного раунда.

Добавлен преф, позволяющий отключить автооткрытие титров и воутов.

Также сообщение в чате за сколько секунд была сохранена статистика будет показываться только педалям, а не всему серверу.
## Почему и что этот ПР улучшит
Титры и воуты не будут выскакивать в лицо и мешать тру робасту. Титры можно будет посмотреть в красивой форме прямо в игре.
## Авторство

## Чеинжлог
:cl:
 - add: Добавлена кнопка Show Last Scoreboard для просмотра титров последнего раунда.
 - add: Добавлен преференс Toggle Votes Autoopening, запрещающий интерфейсам воутов и титр выскакивать автоматически.

2022-09-08 11:55 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2022-09-08 12:35 UTC, Tap0r commented
> Титры раунда теперь можно открывать через ссылку, которая появится в чате или через кнопку Show Last Scoreboard во вкладке оок.

Наконец-то!!!!!!

2022-09-09 18:51 UTC, notkripton commented on code/game/gamemodes/scoreboard.dm
> +	text2file(completions, "data/last_score.txt")
Сделал.

2022-09-09 18:57 UTC, notkripton commented on code/game/gamemodes/scoreboard.dm
> +/datum/stat_collector/proc/generate_scoreboard()
В последнем коммите сделал немного код импрувмента. Обьединил генерацию титров в один прок и перенес его в юрисдикцию SSStatistics.

2022-09-30 03:57 UTC, notkripton commented
Поставьте пру тег чтобы бот не приставал

2022-10-07 05:32 UTC, notkripton commented on code/game/gamemodes/scoreboard.dm
> +	usr?.client?.show_scoreboard()
Потому что человек может нажать эту ссылку из другого раунда и это могло бы привести к тому, что игра бы попыталась открыть титры уже идущего раунда

2022-10-14 06:16 UTC, volas requested changes

2022-10-14 06:16 UTC, volas commented on code/modules/client/preferences.dm
> +	var/votes_autoopening = TRUE
если это еще попап статистики, то нужно какое-то другое название.

И лучше это делать отдельным ПР-ом, потому что тебе нужно еще обновлять сейв/лоад префов.

2022-10-14 06:16 UTC, volas commented on code/__HELPERS/logging.dm
> +/proc/get_last_proper_ended_round_id()
стоит добавить кэширование. Просто глобальный вар по типу round_id, который будет инициализироваться тут при первом запросе.

2022-10-14 06:16 UTC, volas commented on code/game/gamemodes/scoreboard.dm
> +		roundid = global.get_last_proper_ended_round_id()
не проверяешь, вернул ли get_last_proper_ended_round_id вообще что нибудь

2022-10-14 06:16 UTC, volas commented on code/game/gamemodes/scoreboard.dm
> +		return
return и отправку картинок стоит поменять местами. И проверку на roundid ниже тоже стоит поднять до browse_rsc

2022-10-14 06:16 UTC, volas commented on code/game/gamemodes/scoreboard.dm
> +/client/proc/show_scoreboard(roundid)
будь на открытие текущего/произвольного раунда две разных функции - было бы проще и удобнее делать кэширование и выставлять ограничения.

Никто конечно не умрет, если мы на каждого из допустим 100 игроков будем делать отдельный запрос в БД за датой, отдельный запрос на диск за файлом, отдельный json_decode, но как-то не очень.

Без кулдауна json_decode какого-нибудь произвольного тяжелого раунда вообще может задосить сервер.

2022-11-04 12:58 UTC, closed without merging

2022-11-06 06:11 UTC, Tap0r commented
Неееет!!!!!