Перевод ТОЛЬКО интерфейса ПДА
TauCetiStation/TauCetiClassic pull request #10096
Opened 2022-09-19 19:31 UTC by DarthSidiousPalpatine

## Описание изменений
Перевод интерфейса ПДА и только его:
![image](https://user-images.githubusercontent.com/21008918/191099173-8533d9f8-a4fc-40d1-a195-e0b15a3b78a9.png)
![image](https://user-images.githubusercontent.com/21008918/191099199-1624a3ab-90c6-49e9-9218-3dd9fad73d7b.png)
![image](https://user-images.githubusercontent.com/21008918/191099260-a4b18adb-3a94-4ce7-a3f1-52f89f9c7a92.png)
![image](https://user-images.githubusercontent.com/21008918/191099302-74a569fd-98d8-4790-b002-fe04765734df.png)
![image](https://user-images.githubusercontent.com/21008918/191099335-89425d21-4623-44b5-ada5-5df09c122e5a.png)
![image](https://user-images.githubusercontent.com/21008918/191099381-0e0f5a34-8fef-4778-a563-dbe0e825b230.png)
![image](https://user-images.githubusercontent.com/21008918/191099397-e6c9235e-17e1-4a86-b9ba-a7549ba7d7cf.png)
![image](https://user-images.githubusercontent.com/21008918/191099446-a31720c2-88c0-4803-9d73-c68f0299db47.png)
![image](https://user-images.githubusercontent.com/21008918/191099475-d6f3ad50-9f08-4734-a66b-284f3171d2a9.png)
![image](https://user-images.githubusercontent.com/21008918/191099560-1405e4d1-cbba-4986-af4e-690a1b04f7db.png)
![image](https://user-images.githubusercontent.com/21008918/191099615-7b990723-8983-4de8-837d-90d797a5c95f.png)
![image](https://user-images.githubusercontent.com/21008918/191099644-81abf2b2-8656-4591-801f-6a6e07d42ebb.png)
![image](https://user-images.githubusercontent.com/21008918/191099664-2e1ef60a-285a-4d9e-a4d1-1948aebe6544.png)
![image](https://user-images.githubusercontent.com/21008918/191099692-bda6192c-7e91-4eff-8e00-2c487b36931c.png)
![image](https://user-images.githubusercontent.com/21008918/191099722-62c78dd0-39cd-4ab0-9ca4-4e5fd1f7c26e.png)
![image](https://user-images.githubusercontent.com/21008918/191099776-a6cda325-4007-4898-b09a-e9f19ba44164.png)

## Почему и что этот ПР улучшит
Переведём интерфейс ПДА и только его, на данный момент.

## Авторство
Darth_Sidious

## Чеинжлог
 :cl:
- localization: Перевод интерфейса ПДА и только его.

2022-09-19 19:31 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2022-09-19 20:00 UTC, KIBORG04 commented on code/game/objects/items/devices/PDA/PDA.dm
> +			var/t = sanitize(input(U, "Выберите новый рингтон", name, input_default(ttone)) as text, 20)
Я не выбираю, а ввожу

2022-09-19 20:02 UTC, KIBORG04 commented on code/game/objects/items/devices/PDA/PDA.dm
> +		tgui_alert(usr, "ОШИБКА! Аккаунт не сохранён в КПК, пожалуйста вставьте свою карту и перезагрузите устройство.")
```suggestion
		tgui_alert(usr, "ОШИБКА! Аккаунт не сохранён в КПК, пожалуйста, вставьте свою карту и перезагрузите устройство.")
```

2022-09-19 20:05 UTC, DarthSidiousPalpatine commented on code/game/objects/items/devices/PDA/PDA.dm
> +			var/t = sanitize(input(U, "Выберите новый рингтон", name, input_default(ttone)) as text, 20)
Что странно, Как можно ввести рингтон?

2022-09-19 20:07 UTC, KIBORG04 commented on code/game/objects/items/devices/PDA/PDA.dm
> +			var/t = sanitize(input(U, "Выберите новый рингтон", name, input_default(ttone)) as text, 20)
Синтез речи в 2222 году, дружек.

2022-09-20 12:10 UTC, AirBlack commented
сделай баблы за место квадратов, а еще сделай чтобы лайки можно было ставить, еще сделай стантиндер где можно по флаффам свайпать

2022-09-20 12:13 UTC, DarthSidiousPalpatine commented
> сделай баблы за место квадратов, а еще сделай чтобы лайки можно было ставить, еще сделай стантиндер где можно по флаффам свайпать

Нет. Только перевод и всё что для перевода требуется. Доп. функции уйдут в новый ПР.

2022-09-20 13:18 UTC, AirBlack commented
ну сделай в другом ПРе, ток сделай

2022-09-20 14:27 UTC, volas commented
\> Перевод интерфейса ПДА и только его.
\> Меняет верстку страниц

2022-09-20 15:45 UTC, KIBORG04 requested changes
Шанс на мёрж перевода + вёрстки равен 0

2022-09-20 15:46 UTC, DarthSidiousPalpatine commented
Вааат, ясно. Ладно, сейчас удалю к чертям вёрстку и тогда быстромерж?

2022-09-20 15:47 UTC, KIBORG04 commented
Лол, нет, будешь ждать ревью ТОЛЬКО перевода. Можешь паралельно сделать вёрстку и там уже мб и будет быстро мёрж, хотя без закруглённых краёв я хз...

2022-09-20 15:57 UTC, KIBORG04 commented on nano/templates/pda.tmpl
> +				{{:helper.link('Кошелёк', 'suitcase', {'choice' : "Finance"}, null, 'fixedLeftWide')}}
Тут скорее финансы, сбережения, банк, чем кошелёк. Кошелёк не способен платить и делать переводы

2022-09-20 15:58 UTC, DarthSidiousPalpatine commented on nano/templates/pda.tmpl
> +				{{:helper.link('Кошелёк', 'suitcase', {'choice' : "Finance"}, null, 'fixedLeftWide')}}
Это твой онлайн-кошелёк. Сбербанк, можно сказать. Банковское приложение.

2022-09-20 16:06 UTC, KIBORG04 commented on nano/templates/pda.tmpl
> +                                <span class="message_left"><left><small><span class="average">{{:value.reciever}}</span></small></left><br>{{:value.message}}</span><br>
Ты теги Left и small не закрываешь.

2022-09-20 16:06 UTC, DarthSidiousPalpatine commented on nano/templates/pda.tmpl
> +                                <span class="message_left"><left><small><span class="average">{{:value.reciever}}</span></small></left><br>{{:value.message}}</span><br>
Всмысле. Вон же смалл и лефт закрытие

2022-09-20 16:08 UTC, KIBORG04 commented on nano/templates/pda.tmpl
> +                                <span class="message_left"><left><small><span class="average">{{:value.reciever}}</span></small></left><br>{{:value.message}}</span><br>
А, оно реально есть, дейтсвительно.

2022-09-20 16:09 UTC, DarthSidiousPalpatine commented on nano/templates/pda.tmpl
> +                                <span class="message_left"><left><small><span class="average">{{:value.reciever}}</span></small></left><br>{{:value.message}}</span><br>
Одна ошибка и ты ошибся

2022-09-20 16:31 UTC, DarthSidiousPalpatine commented
Вырвал с корнем вёрстку мессенджера.... Больно, блин

2022-09-21 15:20 UTC, Fenriros commented
> Вырвал с корнем вёрстку мессенджера.... Больно, блин

Сейчас проверим, и замержат и будет хорошо.

2022-09-21 19:04 UTC, Fenriros commented on nano/templates/pda.tmpl
> +                    <b>Доп. Устройства</b>:
А чего Ты картридж, как "доп. устройтва" перевёл?

2022-09-21 19:04 UTC, Fenriros commented on nano/templates/pda.tmpl
> +				{{:helper.link('Кошелёк', 'suitcase', {'choice' : "Finance"}, null, 'fixedLeftWide')}}
Можно перевести просто как "Финансы"

2022-09-21 19:27 UTC, Fenriros commented on nano/templates/pda.tmpl
> +                    {{:helper.link('Извлечь', 'eject', {'choice' : "pai", 'option' : "2"}, null, 'fixedLeft')}}
А почему не "Извлечь пИИ" ?

2022-09-22 03:50 UTC, DarthSidiousPalpatine commented on nano/templates/pda.tmpl
> +                    {{:helper.link('Извлечь', 'eject', {'choice' : "pai", 'option' : "2"}, null, 'fixedLeft')}}
Потому что это в графе Управление ПИИ

2022-09-22 03:50 UTC, DarthSidiousPalpatine commented on nano/templates/pda.tmpl
> +                    <b>Доп. Устройства</b>:
Потому что картридж ассоциируется с принтерами.
Я хотел написать аксессуары или что-то такое, ну, знаешь, что можно докупить к планшету чтобы там к нему геймпад приделать или ещё что-то.

2022-09-22 03:52 UTC, DarthSidiousPalpatine commented on nano/templates/pda.tmpl
> +				{{:helper.link('Кошелёк', 'suitcase', {'choice' : "Finance"}, null, 'fixedLeftWide')}}
Не знаю, почему не кошелёк? Эта кнопка - доступ в твой кошелёк где есть твои счета, можно переводить деньги на другие кошельки и можно посмотреть лог транзакций.

2022-09-26 15:49 UTC, Udokun commented
Даже гугл лучше переводит, что это за №%;:!?

2022-09-26 19:32 UTC, Sakuya-Izayoi commented on nano/templates/pda.tmpl
> +                    <b>Доп. Устройства</b>:
Картридж бля ассоциируется с денди и игровым пацаном.

2022-09-26 20:36 UTC, BesumniiChebureck commented
Наверное только моя шиза, но "Чат" я бы заменил на "Диалог", глаз режет

2022-09-30 03:29 UTC, volas commented on code/game/objects/items/devices/PDA/PDA.dm
> +	var/note = "Спасибо за покупку КПК 9 от ООО Тинктроник!" //Current note in the notepad function
Thinktronic 5230

2022-09-30 03:31 UTC, volas commented on nano/templates/pda.tmpl
> +                    <b>Доп. Устройства</b>:
модули/плагины

2022-09-30 12:44 UTC, Fenriros commented on code/game/objects/items/devices/PDA/PDA.dm
> +	var/note = "Спасибо за покупку КПК 9 от ООО Тинктроник!" //Current note in the notepad function
```suggestion
	var/note = "Поздравляем, Для станции была выбрана модель карманного персонального компьютера Thinktronic 5230 " //Current note in the notepad function
```

2022-09-30 12:47 UTC, Fenriros commented on code/game/objects/items/devices/PDA/PDA.dm
> +	var/note = "Спасибо за покупку КПК 9 от ООО Тинктроник!" //Current note in the notepad function
```suggestion
	var/note = “Поздравляем, ваша станция выбрала КПК серии Thinktronic 5230” //Current note in the notepad function
```

2022-09-30 12:50 UTC, Fenriros commented
Ещё бы я перевёл описание самого PDA (7я строчка кода)
`	desc = ""Портативный микрокомпьютер от Thinktronic Systems, LTD. Набор функций зависит от вставленного картриджа."`

2022-09-30 12:57 UTC, Fenriros reviewed
99-101

> 			to_chat(user, "Время на станции [worldtime2text()] и ожидаемое время прибытия Шаттла [shuttleeta2text()] отображаются в углу экрана.")
> 		else
> 			to_chat(user, "Время на станции [worldtime2text()] отображается в углу экрана.")

2022-09-30 15:47 UTC, DarthSidiousPalpatine commented on nano/templates/pda.tmpl
> +                    <b>Доп. Устройства</b>:
Плагин это что-то цифровое, нематериальное. Модуль - норм. Но и устройства тоже норм. Туда можно вставить как картридж, так и пИИ, что подпадает под устройства.

2022-09-30 15:48 UTC, DarthSidiousPalpatine commented on nano/templates/pda.tmpl
> +				{{:helper.link('Кошелёк', 'suitcase', {'choice' : "Finance"}, null, 'fixedLeftWide')}}
Ни один из предложенных не нравится. Финансы, Сбережения - хрень.

Банк - ну такое, хотя лучшее из предложенных. Может, банк лучше.

2022-09-30 15:49 UTC, DarthSidiousPalpatine commented on code/game/objects/items/devices/PDA/PDA.dm
> +	var/note = "Спасибо за покупку КПК 9 от ООО Тинктроник!" //Current note in the notepad function
> Thinktronic 5230 и должно остаться. И перевод можно ближе к оригиналу.

Не должен, что за бред вообще, почему кпк могут закупить только станции? Нет уж. Стандартное сообщение в кпк должно быть именно "Спасибо за покупку <modelname>".

2022-09-30 15:51 UTC, DarthSidiousPalpatine commented
> Ещё бы я перевёл описание самого PDA (7я строчка кода) ` desc = ""Портативный микрокомпьютер от Thinktronic Systems, LTD. Набор функций зависит от вставленного картриджа."`

2022-09-30 15:51 UTC, DarthSidiousPalpatine commented
Ять, случайно закрыл

2022-10-02 17:22 UTC, DarthSidiousPalpatine commented
И терпим терпим

2022-10-09 12:01 UTC, DarthSidiousPalpatine commented
Терпим терпим

2022-10-22 08:37 UTC, DarthSidiousPalpatine commented
Атлант потерял дар речи

2022-10-26 10:36 UTC, Fenriros commented
Кого ждём?

2022-10-26 10:37 UTC, DarthSidiousPalpatine commented
Да мне уже пофиг, я ПДА переделываю на тгуи :dovolen:

2022-11-09 11:44 UTC, DarthSidiousPalpatine commented
нет стой

2022-11-09 14:36 UTC, BasiaBelov commented
Так и переведём всю игру, по частям)

2022-11-15 22:10 UTC, DarthSidiousPalpatine commented
Так это, не понял, а что тут не так?

2022-11-15 22:48 UTC, DarthSidiousPalpatine commented
Перевод пофикшен, жду мерж кароч.

2022-11-28 15:52 UTC, DarthSidiousPalpatine commented
Чтобы не закрылось

2022-12-02 17:37 UTC, DarthSidiousPalpatine commented
Конфликт резолвнул. Ну, а в чём проблема мержа-то?

2022-12-17 03:10 UTC, DarthSidiousPalpatine commented
Сук да покуда?

2022-12-20 13:25 UTC, KIBORG04 commented
> Новое правило переводов: одновременно может быть открыто не больше 1 одновременных PR с переводами. 

Гены были открыты раньше на 1 день. В твоих интересах привести к их мержу/закрытию. Пока лишь я ВРЕМЕННО закрываю ПР.

2022-12-20 13:25 UTC, closed without merging

2022-12-20 14:08 UTC, DarthSidiousPalpatine commented
Есть привести их к закрытию!

2023-01-22 19:04 UTC, DarthSidiousPalpatine commented
Пацаны, я тут узнал, а этот ПР - единственный.