Sprites combat borg
TauCetiStation/TauCetiClassic pull request #10100
Opened 2022-09-20 16:51 UTC by Deahaka

## Описание изменений
после https://github.com/TauCetiStation/TauCetiClassic/pull/9957 нужно было обновить https://github.com/TauCetiStation/TauCetiClassic/pull/9946 , но я что-то наклацал и всё пропало.
Коротко: портировал с ВГ и Эриса спрайты для комбат борга. В этом ПРе ещё удалил скин паука для выбора комбат модулю, так как для него нет ничего нигде (щит и ролл).
Удав просил разницу, так что:
| Пример | Было | Стало |
|:-------------: |:---------------:| :-------------:|
| Дройдека в ролле | ![XXXXXXa](https://user-images.githubusercontent.com/96499407/191316200-f1f42c57-7ae3-4869-ac4d-9191988a10ca.png) |  ![XXXXXC](https://user-images.githubusercontent.com/96499407/191316485-385219b1-6af1-4de0-b5c2-e036910678e7.png) |
| Кодиак глаза | ![ZZZZZ](https://user-images.githubusercontent.com/96499407/191316744-6d52cdc5-b64e-4e5c-bdb3-6aa3ae9b655c.png) |  ![ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ](https://user-images.githubusercontent.com/96499407/191316836-455c38a3-de49-4bc2-9e5f-51535a91bd0d.png) |
| Ищейка глаза | ![ZXXXX](https://user-images.githubusercontent.com/96499407/191317108-9b030efe-9b52-42c3-b600-9e92c94da36e.png) | ![ZZZZZZZZZZZZZX](https://user-images.githubusercontent.com/96499407/191317152-afa5ccba-1d7b-4a89-90c5-f7272a976825.png) |
| Ищейка глаза сбоку | ![ZZZXXX](https://user-images.githubusercontent.com/96499407/191317595-991fe175-7bb3-41ea-9768-c3398b1bc6f2.png) | ![ZZZZXXX](https://user-images.githubusercontent.com/96499407/191317601-8545ab74-a45c-410a-8df7-e20247418291.png) |

## Почему и что этот ПР улучшит
Спрайты комбат боргов ура!
## Авторство
VG Station, CEV Eris
## Чеинжлог

2022-09-20 16:51 UTC, TauKitty commented
###### Changelog status: :radio_button: No changelog

2022-09-22 09:22 UTC, UDaV73rus commented
Ровном счетом ничего не поменялось

2022-09-22 09:28 UTC, Deahaka commented
Уберу слово "круче", апрув?

2022-10-20 15:37 UTC, Deahaka commented
Терпим терпим

2022-10-20 15:40 UTC, UDaV73rus requested changes
говно.

2022-11-10 18:31 UTC, closed without merging