Таяра-повар теперь реальность
TauCetiStation/TauCetiClassic pull request #10113
Opened 2022-09-22 07:37 UTC by Deahaka

## Описание изменений
Таяры теперь будут вкладывать немного шерсти в результаты готовки. Это будет влиять на потребителей. После этого ПРа собираюсь убрать tajaran рестрикт на повара. Для напитков пока этого нет, так что таяр-бармен пока останется запрещённым.
## Почему и что этот ПР улучшит
Геймплей
## Авторство

## Чеинжлог
:cl: Deahaka
-add: Таяры при готовке еды оставляют в ней шерсть.

2022-09-22 07:37 UTC, TauKitty commented
###### Changelog status: :x: Empty changelog (check markdown correctness)

2022-09-22 07:46 UTC, KIBORG04 commented
Знаешь ли, у людей тоже много шерсти, тем более с ближнего востока, но еду от него спасают перчатки, маска, одежда и колпак от волос на голову. У тебя же я в коде не увидел таких условий.

2022-09-22 07:49 UTC, Deahaka commented
Я думал об этом. У нас это всё не навешивает никаких дебафов и можно хоть в риге бегать всю смену. Думаю сначала нужно разобраться с этой проблемой, а потом уже вшивать проверку на риги/перчатки/биокостюм и тд.

2022-09-22 07:50 UTC, KIBORG04 commented
Ну так, в жизни тоже одежда повара не навешивает дебаффов. А биокостюм и риг замедляют. Ну если у тебя таяра в риге и повар, то ржака жеж

2022-09-22 07:51 UTC, Deahaka commented
Дополню, а то расплывчато написал: в чём смысл этого механа, если его можно нивелировать просто нацепив чё угодно навсегда? Будут таяры в перчатках, в маске и в шапке повара ну и что это интересного даст? Абсолютно ничего.

2022-09-22 07:53 UTC, KIBORG04 commented
А какой интерес даст функция блевать с шансом 25%? Ты делаешь механ, который изначально мешает жить игрокам, и который вообще никак не обозначается и не указан. Это же хорошо, что подготовленный чел не будет делать блевать, в отличие от нуба

2022-09-22 07:57 UTC, Deahaka commented
На желание подготовленных челов манчить мне пох, все в равных условиях будут пока что

2022-09-22 07:58 UTC, KIBORG04 commented
Эта фича мешает не повару, а клиентам. А добавить проверку всегда можно, ты же добавление трейта сделал от расы

2022-09-22 08:29 UTC, Deahaka commented
Киборг предложил норм варик, пусть будет проверка на био защиту, чисто чтобы поржать.

2022-09-22 09:31 UTC, Sakuya-Izayoi commented
а смысл разрешать таярам повара ???

2022-09-22 09:32 UTC, Deahaka commented
Смысл этого не делать?

2022-09-22 15:07 UTC, Deahaka commented
Ладно, если лордепа или кто там заведует вики не хватает чтобы придумать пару строк почему что-то работает, то пусть остаются рестрикты. ПР все равно про другое

2022-09-24 12:13 UTC, KIBORG04 commented on code/game/machinery/kitchen/kitchen_machines.dm
> +		if(ishuman(user))
Чет тут хуйня, почему при ГОТОВКЕ в микроволновке еда вдруг получает шерсть? Сделай лучше, что при подбирание еды таярской расой. Смотри в сторону pickup(). А еще думаю, можно добавить сообщение о шерсти в examine

2022-09-24 12:16 UTC, Deahaka commented on code/game/machinery/kitchen/kitchen_machines.dm
> +		if(ishuman(user))
Так ничего не мешает пулить объекты и не вызывать пикап, так работать будет на всё, кроме мейкшифт хотдогов и бургеров. Что делать с этим?

2022-09-24 12:19 UTC, KIBORG04 commented on code/game/machinery/kitchen/kitchen_machines.dm
> +		if(ishuman(user))
Не, ну можно добавить и при пулле тоже. У нас точно нету  какого-то прока on_touch

2022-09-24 16:27 UTC, Deahaka commented
Ну вроде работает. Получилось немного говно конечно, пока нет идей как сделать по-другому. Сигнал не создавал новый, но может стоило бы, вместо того что я сделал.
Таярам уменьшил шанс на рыготню, я ж не ради ухудшения жизни таярам делал это.

2022-09-25 05:09 UTC, WatlerJe commented
> Таярам уменьшил шанс на рыготню, я ж не ради ухудшения жизни таярам делал это.

Явно и не для улучшения. От осознания того, что игровая кукла теперь может отравить еду тупо коснувшись ее, жизнь у от этого только станет лучше.

> После этого ПРа собираюсь убрать tajaran рестрикт на повара. Но если не надо то не надо.

Можешь не убирать и ПР этот закрыть, ибо тебе как гению сегрегационной мысли в игре про 2Д космонавтов, не понять, что есть такое понятием как геймплей, кстати о нем.

>**Почему и что этот ПР улучшит**
Геймплей

Что _геймплей_, кто _геймплей_, почему _геймплей_? Где описание того как улучшится быт игроков на данной расе или кого либо еще. Если раньше это еще выглядело, с натяжкой, как боланс фича где раса теперь может в профу, но вот вам штраф за это (лол). Сейчас же это просто намеренное ухудшение геймплея, так как создаются сложности которых раньше не было, которые при этом не как не компенсируются.
 
Почему же тогда у людей такого нету? Они тоже сыпяться и еще как, отшелушенная кожа, волосы из разных участков тела. Давай добавляй и им такое или это другое? Или дело в том, что ты как последователь секты ролеплея и свидетель релизма, хочешь чтобы та раса за которую ты не играешь была максимально кастрирована, а игрокам на ней было мучительно больно играть, ведь на этом ты не остановишься.

2022-09-25 05:18 UTC, Deahaka commented
Написать столько, основываясь только на придуманных у себя в голове утверждениях, может только вальтер (на самом деле каждый мой хейтер).

2022-09-25 09:57 UTC, Deahaka commented
Понял как сделать без сигнала, теперь всё красиво

2022-09-25 11:57 UTC, KIBORG04 commented on code/modules/mob/mob.dm
> +		if(SEND_SIGNAL(AM, COMSIG_ATOM_START_PULL, src, AM) & COMPONENT_PREVENT_PULL)
```suggestion
		if(SEND_SIGNAL(AM, COMSIG_ATOM_START_PULL, src) & COMPONENT_PREVENT_PULL)
```

2022-09-25 12:05 UTC, KIBORG04 commented on code/modules/mob/living/carbon/human/human.dm
> +/mob/living/carbon/human/start_pulling(atom/movable/AM)
Я подумал про прок on_touch, который бы определял всё, до чего бы докоснулся чел. И я даже нашёл некую альтернативу - `add_fingerprint`, который уже стоит везде! Можно туда это пихнуть крч.

(Всё, что ниже идёт как мега крутая идея)
Это значит, что можно добавить в расы новый флаг, типо волосяного покрова, там же с волосами падает частичка дна и обозначение расы. Ну и крч это всё развить в некую фичу детектива с микрофичей отравления.

2022-09-25 12:06 UTC, KIBORG04 commented on code/modules/reagents/reagent_containers/food.dm
> +/obj/item/weapon/reagent_containers/food/proc/tajaran_effect(mob/M)
Нормально назови прок без привязки к расе и с глаголом.

2022-09-25 12:07 UTC, KIBORG04 commented on code/modules/reagents/reagent_containers/food.dm
> +	REMOVE_TRAIT(src, TRAIT_TAJARAN_HAIR, GENERIC_TRAIT)
Не имеет смысла

2022-09-28 19:04 UTC, Deahaka commented
переделал на трейт на любой атом. Хз надо ли где-то делать удаление трейтов? Наверное нет.

>Это значит, что можно добавить в расы новый флаг, типо волосяного покрова, там же с волосами падает частичка дна и обозначение расы. Ну и крч это всё развить в некую фичу детектива с микрофичей отравления.

Так как я сейчас сделал не передать информацию независимо. Нет хранения ДНК или имени автора трейта. Возможно, что-то да можно сделать для дека, например проверить этот трейт и увеличить процент расшифровки этого отпечатка. Или же не влиять на расшифровку и давать отдельной инфой в комп, мол "найдены частички шерсти", чтобы дать подсказку деку, но не указывать конкретно автора. Немного не логично, ведь шерсть содержит ДНК, других минусов в таком нету.

2022-10-01 21:03 UTC, Deahaka commented
Сделал механ через фиберс, потому что я манал разбираться в ассоциативных листах в том компе детективском. При оставлении отпечатков атом проверяет био protecc у хумана и наличие шерстяного покрова. Если не защищён - оставляет на атоме "частички шерсти [имя расы]" подсказку для детектива. Опять же, из-за асоциативной файвхед механики скинуть деку ДНК хз как, не через кровь же.

2022-10-01 21:04 UTC, Deahaka commented
Завтра наверное попробую сразу впилить механ для операций. Больше идей не было, но неплохо если б добавились.

2022-10-02 07:26 UTC, Deahaka commented
Шерсть накидывает столько же микробов, сколько и кровь на инструменте. Добавил удаление трейта с объектов через стерилизин, добавил особенности действия стерилизина на еду (чтобы не пшикали)

2022-10-04 14:48 UTC, Haggerd commented
Ощущение, будто таяры линяют ядерными комьями шерсти, что выдаёт 25% шанс сблевнуть.
В чём смысл? Фича ради фичи? 

Фича с детективом, к слову, норм.

2022-10-04 14:58 UTC, Deahaka commented
>В чём смысл? Фича ради фичи?

Фича ради свободы отыгрыша и РП

2022-10-18 12:46 UTC, Deahaka commented
Поменял концепцию. Еда больше не вызывает рвоту ни у кого. Теперь всё работает как флафф.
Причина для изменений: идея использовать в таком частом явлении, как приём пищи, механ рвоты, с каким-либо шансом, не сможет влиять на игроков в большей мере положительно, чем отрицательно. Какая-то логика "накопления" не выстраивается в голове, поэтому лучше просто удалить, заменив на настроение.

Если и делать рвоту, то, например, при поедании сырой мыши, когда её можно будет кушать.

2022-10-20 19:15 UTC, KIBORG04 commented on code/modules/detectivework/detective_work.dm
> +		fibertext = "Small particles of [M.species.name] fur."
```suggestion
		fibertext += " Small particles of [M.species.name] fur."
```
Иначе инфа о фибрах одежды пропадет

2022-10-20 19:17 UTC, KIBORG04 commented on code/modules/detectivework/detective_work.dm
> +		var/check_cloth = 100 - M.getarmor(null, "bio")
```suggestion
		var/bio_armor = 100 - M.getarmor(null, "bio")
```
лучше нормально назови, как-то так. Ну или же че-то про био-защиту-ткани, но не ПРОВЕРКА_ТКАНЬ

2022-10-20 19:20 UTC, KIBORG04 commented on code/modules/reagents/reagent_containers/food/snacks.dm
> +				chance = 0
```suggestion
		var/mob/living/carbon/human/H = M
		if(istype(H) && !H.species.flags[FUR])
```
Лайфхаки

2022-10-20 19:20 UTC, KIBORG04 commented on code/modules/reagents/reagent_containers/food/snacks.dm
> +				chance = 0
Ну и зачем там шанс, кстати?

2022-10-20 19:20 UTC, KIBORG04 commented on code/modules/reagents/reagent_containers/food/snacks.dm
> +				to_chat(H, "<span class='warning'>You feel like something enveloping in your throat...</span>")
Муд_ивент же кидает в чат сообщалку, зачем еще писать

2022-10-20 19:22 UTC, KIBORG04 commented on code/modules/reagents/reagent_types/Chemistry-Medicine.dm
> +		F.reagents.add_reagent("ethanol", 1)
Почему это так? Можно же стерилизину добавить /on_general_digest

2022-10-20 19:23 UTC, KIBORG04 requested changes
написал

2022-10-20 19:25 UTC, Deahaka commented on code/modules/reagents/reagent_containers/food/snacks.dm
> +				to_chat(H, "<span class='warning'>You feel like something enveloping in your throat...</span>")
Разве кидает? Оно вроде только в экзамайне муда.

2022-10-20 19:26 UTC, Deahaka commented on code/modules/reagents/reagent_types/Chemistry-Medicine.dm
> +		F.reagents.add_reagent("ethanol", 1)
Так пшик не передаёт реагент в контейнер. Только чистит.

2022-10-20 19:28 UTC, KIBORG04 commented on code/modules/reagents/reagent_containers/food/snacks.dm
> +				to_chat(H, "<span class='warning'>You feel like something enveloping in your throat...</span>")
эээ

2022-10-20 19:30 UTC, Deahaka commented on code/modules/detectivework/detective_work.dm
> +		fibertext = "Small particles of [M.species.name] fur."
Это вроде не для такого. fibertext это переменная, чтобы вставить туда текст и проверить в собственно suit_fibers, фибрах одежды. Если дублируется - то ничего, а если нету - добавить след.

2022-10-20 19:34 UTC, KIBORG04 commented on code/modules/detectivework/detective_work.dm
> +		fibertext = "Small particles of [M.species.name] fur."
а, fibertext вообще не нужен в этом проке впринципе 🤣

2022-10-20 19:43 UTC, Deahaka commented on code/modules/reagents/reagent_containers/food/snacks.dm
> +				chance = 0
Просто подумал что так будет лучше.
Таяра приготовила бургер > каждый кто укусит бургер получит расстройство от шерсти > 3 раза прокнул ивент
Таяра приготовила бургер > с половинным шансом укус бургера будет с шерстью > 0-3 раза прокнул ивент, то есть кому-то повезло "не заметить".
Логичнее, да и нормально будет, если шерсти там не вагон, а немножко.

2022-10-20 19:46 UTC, KIBORG04 commented on code/modules/reagents/reagent_containers/food/snacks.dm
> +				chance = 0
Ну шанс ок, но лайфхак все еще в силе

2022-10-20 19:52 UTC, Deahaka commented
☑

2022-11-01 21:21 UTC, merged