Улучшения камер и обновление иконки
TauCetiStation/TauCetiClassic pull request #10156
Opened 2022-09-28 14:19 UTC by Deahaka

## Описание изменений
Выделенная отдельно часть https://github.com/TauCetiStation/TauCetiClassic/pull/9853 , потому что полная разрушаемость взяла дело в свои руки. Ещё мне лень фиксить баги, которые нашлись, по-этому пусть останется как было всё.

Попытался вывести апгрейды в асоциативный список. Починил обновление иконки, чтобы иксрей-камеры использовали свою иконку, вместе с этим сделал отображение сломанной и поражённой ЭМИ камерой. Добавил к апгрейдам улучшение пласталью, что защитит камеру от взрывов.
## Почему и что этот ПР улучшит
Красота и геймплей
## Авторство

## Чеинжлог
- add: Добавлена возможность улучшать камеры.
- del: Добавлено улучшение  защиты от взрывов камере с помощью пластали.
- fix: Иконка камер теперь имеет не только 2 состояния, иксрей камеры теперь выглядят немного иначе.

2022-09-28 14:49 UTC, kalazus commented on code/game/machinery/camera/camera.dm
> +		icon_state = "[camera_base]emp"
Всегда лучше использовать if else, а не переустанавливать переменную.

2022-09-28 14:49 UTC, kalazus commented on code/game/machinery/camera/camera.dm
> +	return FALSE
Максимально странные конструкции, учитывая что в camera_updates находятся (элементы) не листы, и они всегда определённого типа.
2) лучше наверное имена не по предметам, а по типам улучшения брать.
P.s. проверка должна быть типа !!camera_updates[name] (вместо !! можно, и наверное лучше использовать !is null(...)

2022-09-28 14:49 UTC, kalazus commented on code/game/machinery/camera/presets.dm
> +	upgradeExplosiveImmune()
Устанавливаем null в updates?

2022-09-28 14:49 UTC, kalazus commented on code/game/machinery/camera/camera.dm
> +	update_icon()
Наверное во всех улучшения нужно перемещать объект в камеру чтобы при уничтожении выпадал (если выпадает), иначе нет смысла хранить именно объекты, а не True/False т.к. достать нельзя.

2022-09-28 15:55 UTC, Deahaka commented on code/game/machinery/camera/camera.dm
> +	return FALSE
Что такое "типы улучшения"?

2022-09-28 16:26 UTC, Deahaka commented
Поменял всё кроме проверок. Там проверять L.len или что? Я не понял что за isnull и куда его вставить

2022-09-28 16:28 UTC, kalazus commented on code/game/machinery/camera/camera.dm
> +	return FALSE
Вместо phorone, emp/emp_proof

2022-09-28 16:34 UTC, kalazus commented on code/game/machinery/camera/camera.dm
> +			S.forceMove(src)
Это лучше в саму функцию апдейта, но и так сойдёт.

2022-09-28 16:34 UTC, kalazus commented on code/game/machinery/camera/camera.dm
> +	var/list/L = camera_upgrades["phoron"]
У тебя по названием предметы, а не списки предметов.

2022-09-28 17:35 UTC, Deahaka commented
Получилось.

2022-09-28 19:09 UTC, notkripton commented
> del: Добавлено улучшение защиты от взрывов камере с помощью пластали.

Лол

2022-09-28 19:48 UTC, kalazus commented on code/game/machinery/camera/camera.dm
> +	return FALSE
Либо if camera..., либо return !isnull(camera...). Первая наверное быстрее

2022-09-29 15:42 UTC, Shootnik01 commented
Дайте народу возможность ломать камеры петушителем!

2022-09-29 20:09 UTC, kalazus commented on code/game/machinery/camera/camera.dm
> +	return FALSE
Либо if camera..., либо return !isnull(camera...). Первая наверное быстрее. Ну или camera... ? TRUE : FALSE. У нас точно для этого нету дефайна?

2022-09-29 20:10 UTC, kalazus commented on code/game/machinery/camera/camera.dm
> +		I.forceMove(src)
Лучше всё-же не как я сказал, а к attackby т.к. там куча других способов перемещения объекта.

2022-09-29 20:12 UTC, kalazus commented on code/game/machinery/camera/camera.dm
> +		I = newitem
Не обязательно, но лучше наверное просто new type(src), а не создание переменной и моментальное убирание.

2022-10-09 12:03 UTC, KIBORG04 commented on code/game/machinery/camera/camera.dm
> +	update_icon()
Объекты и так перемещаются в камеру, но зачем это хранить в листе я не понимаю тоже.

2022-10-09 12:04 UTC, KIBORG04 requested changes
Согласен с калазусом. Можно было бы ещё `drop_from_inventory` переместить в `upgrade-`проки

2022-10-09 12:04 UTC, Deahaka commented on code/game/machinery/camera/camera.dm
> +	update_icon()
Так а что мне сделать переменные? Я думал намного лучше без них кодить

2022-10-09 12:14 UTC, KIBORG04 commented on code/game/machinery/camera/camera.dm
> +	update_icon()
Зачем? Можно в листе просто хранить стринги, ну или же стринг = флаг, для быстрого доступа.

2022-10-10 20:30 UTC, Deahaka commented
через contents не получается никак, оставил как есть, допилил остальное по ревью

2022-10-10 20:31 UTC, Deahaka commented
Ой стоп, так в аттакбай собрать все дропинвентарь и форсмув или в апгрейд проки?

2022-10-10 20:58 UTC, kalazus commented
> Согласен с калазусом. Можно было бы ещё `drop_from_inventory` переместить в `upgrade-`проки

Так я наоборот написал, что лучше в update не кидать проки перемещения т.к. они различаются, и для некоторых нужен юзер.

2022-11-04 16:14 UTC, Deahaka commented
Пусть вобщем не меняется ничего.

2022-11-04 16:14 UTC, closed without merging