asteroid_update (part 3: "Инструменты") (splitting #9557)
TauCetiStation/TauCetiClassic pull request #10154
Opened 2022-09-28 08:37 UTC by BiQndy

Добавлены новые улучшения для кинетика, изменён механ резонатора, подредактированы цены на некоторые предметы в шахт-о-мате.

Демонстрация работы резонатора и спрайты улучшений кинетика находятся в **конце** описания ПР'а.

## Описание изменений

1. **Кинетикам добавлены новые улучшения.** 
Теперь их четыре вида и вот таблица их эффектов:

| Тип улучшения         | Значение БЕЗ улучшений | Эффект за одно улучшение  | Лимит | Цена в шахт-о-мате | 
| :-----------------------:| :----------------------------: | :-------------------------------: | :-------:  | :--------------------:  | 
| Скорострельность    |  2.1 сек.                              |  -0.35 сек.                                | 1.4 сек.  |   2250                       |
| Урон                          |  10                                      |  +1.5                                         |  13         |   2000                      |    
| Ресурсы                     | 100%                                  |  +25%                                      |  150%    |   1750                       |
| Дальность                 |    3                                      |  1                                              |  4           |   2500                       |

Так же стоит упомянуть, что теперь снаряды кинетиков прилетают в цель моментально, без задержки.

2. **Изменена механика работы резонатора**. 
Теперь он с каждым выстрелом начинает перезаряжаться всё быстрее и быстрее. Его стандартная перезарядка 2.3 сек, с каждым выстрелом ускоряется, есть лимит скорострельности. Но учтите, что со временем он будет возвращаться к стандартной перезарядке в случае, если его не использовать какое то время. Так же напомню, что его эффективность добычи ресурсов = 125%, поэтому это теперь неплохой вариант для быстрой партии ресурсов в начале игры. И да, у него новый звук стрельбы.

3. Теперь разные инструменты добывают **разное** количество руды с пород.

4. Изменены режимы работы у буров.
На замену старым режимам пришли обычный и эффективный режимы!

| Режим             | Кол-во ресурсов | Скорость добычи | Трата энергии |
| :----------------:| :------------------:  | :------------------:  | :--------------:  | 
| Обычный        |  100%                    | 100%                     | 100%                |
| Эффективный |  125%                    | 75%                       | 200%                |

Так же теперь в бурах со старта батарейка на 10к, а не 1к, но и тратят энергии они теперь больше, чем было ранее. (35 траты энергии в обычном режиме = ~285 вскопанных тайлов)

5. Немного увеличил цены на некоторые предметы в шахт-о-мате в связи с увеличением добываемых ресурсов, из чего следует бОльшее количество поинтов. Так же шахт-о-мат теперь издаёт звук как и обычный вендомат при выдаче предмета.

<details> 
  <summary>Видео</summary>

https://user-images.githubusercontent.com/43725089/192729432-a12be4ce-cbfc-4b6f-b410-356faef43eca.mp4

</details>

## Почему и что этот ПР улучшит
Резонатор будут брать не раз в 1000 раундов и то, что было мисскликом. Да и хоть чё то интересненькое в сухую шахту добавить хочеца
## Авторство
Звук выстрела резонатора был сделан из этих двух:
https://freesound.org/people/Invisible_inks/sounds/517058/
https://freesound.org/people/TheGeekRanger/sounds/273497/
## Чеинжлог

2022-09-28 08:37 UTC, TauKitty commented
###### Changelog status: :radio_button: No changelog

2022-09-29 03:33 UTC, F0xiq commented
Было бы круто ещё добавить рекалибратор в вендомат или возможно даже сразу выдавать рекалибратор при покупке геологических мезонок. А то тратишь 10000 очков и потом ещё приходится терпеть выедающий глаза фильтр.

2022-09-29 06:06 UTC, Chip11-n commented
О, кинетик автоматом может перезаряжаться теперь? А ещё, улучшения неснимаемые что ли?

2022-09-29 06:30 UTC, BiQndy commented
> Улучшения неснимаемые что ли?

Вообще да, но можно сделать их вытаскиваемыми

2022-09-29 06:33 UTC, BiQndy commented
> Было бы круто ещё добавить рекалибратор в вендомат или возможно даже сразу выдавать рекалибратор при покупке геологических мезонок. А то тратишь 10000 очков и потом ещё приходится терпеть выедающий глаза фильтр.

Что за рекалибратор?

2022-09-29 06:34 UTC, Chip11-n commented
А фиксы фильтров не коснулись геологии что ли? Может в целом им тогда фильтры ослабить?

2022-09-29 06:35 UTC, kreeperHLC commented
> > Улучшения неснимаемые что ли?
> 
> Вообще да, но можно сделать их вытаскиваемыми

Да вроде на всех остальных билдах можно было снимать улучшения отвёрткой

2022-09-29 06:36 UTC, KIBORG04 commented
Напиши ченджлог

2022-09-29 06:42 UTC, F0xiq commented
> > Было бы круто ещё добавить рекалибратор в вендомат или возможно даже сразу выдавать рекалибратор при покупке геологических мезонок. А то тратишь 10000 очков и потом ещё приходится терпеть выедающий глаза фильтр.
> 
> Что за рекалибратор?

Рекалибратор дисплея, делается в РнД, убирает мерзкий фильтр с мезонок, термалов и т.п.

> А фиксы фильтров не коснулись геологии что ли? Может в целом им тогда фильтры ослабить?
Не коснулось.

2022-09-29 06:50 UTC, kreeperHLC reviewed
Изменения конечно мизерные, но может кому-то пригодятся.

2022-09-29 06:50 UTC, kreeperHLC commented on code/modules/mining/mine_items.dm
> +/obj/item/kinetic_upgrade/range
```suggestion
	return ..()

/obj/item/kinetic_upgrade/range
```

2022-09-29 06:50 UTC, kreeperHLC commented on code/modules/mining/mine_items.dm
> +	var/upgrade_success = FALSE
Мда уж, лучше уж ретёрнить после неудачной попытки, чем вот так вот. Свитч по названию улучшения тоже смущает конечно, но не настолько.

2022-09-29 06:50 UTC, kreeperHLC commented on code/modules/mining/mine_items.dm
> +	var/cell_type = /obj/item/weapon/stock_parts/cell/high
А замена батареи на более улучшенную то не указано.

2022-09-29 06:50 UTC, kreeperHLC commented on code/modules/mining/mine_items.dm
> -		sleep(1)
Это что и почему выпиливается?

2022-09-29 06:51 UTC, BiQndy commented on code/modules/mining/mine_items.dm
> +	var/cell_type = /obj/item/weapon/stock_parts/cell/high
а что тогда написано под второй таблицей?

2022-09-29 06:52 UTC, BiQndy commented on code/modules/mining/mine_items.dm
> -		sleep(1)
это я и добавлял, когда 2 года назад кувалду закодил, что бы оно крутило при ударе, но понял, что это выглядит нелепо, вот и выпилил

2022-09-29 06:53 UTC, Chip11-n commented on code/modules/mining/mine_items.dm
> +	var/cell_type = /obj/item/weapon/stock_parts/cell/high
Ну кстати, в чейнжлог может быть и стоит сунуть. Или просто линк на пр добавь

2022-09-29 06:53 UTC, kreeperHLC commented on code/modules/mining/mine_items.dm
> +	var/cell_type = /obj/item/weapon/stock_parts/cell/high
Тьфу, я в чейнджлоге смотрел

2022-09-29 06:55 UTC, kreeperHLC commented on code/modules/mining/mine_items.dm
> -		sleep(1)
Оке, но в чейнджлог бы это наверное стоит прописать

2022-09-29 07:01 UTC, BiQndy commented
В общем есть много идей, как поступить с этими улучшениями. Я думал сделать сначала некоторый лимит вставляемых апргрейдов, ну по типу 3 штуки вставил а дальше нельзя. Щас закодено так, что можно все характеристики до лимита проапгрейдить. Стоит вернуться к начальной идее, что думаете?

2022-09-29 07:06 UTC, kreeperHLC commented
> В общем есть много идей, как поступить с этими улучшениями. Я думал сделать сначала некоторый лимит вставляемых апргрейдов, ну по типу 3 штуки вставил а дальше нельзя. Щас закодено так, что можно все характеристики до лимита проапгрейдить. Стоит вернуться к начальной идее, что думаете?

Мне нравится идея с размером апгрейдов. В любом случае некоторые хар-ки будут важнее чем другие. И уже пусть человек решает, как ему удобно заапать свой КА. Хочет быстрый и производительный, но при этом без дальности? Да пожалуйста!

2022-09-29 07:07 UTC, Chip11-n commented
Определённо стоит. Я не шахтёр, но приходилось пользоваться кинетиком, и в вакууме, даже когда не хочешь, ты ломаешь с первого попадания грудак человеку, а если дать капы действующие только в 1-й характеристике, то может выйти слишком жёстко. 

На ТГ эта система прошла через множество улучшений, в идеале украсть бы оттуда. Однако где-то там есть бекдур.

2022-09-29 15:20 UTC, KIBORG04 commented on code/modules/mining/equipment_locker.dm
> +		addtimer(CALLBACK(src, .proc/increase_recharge_time), 50 SECOND)
Можешь знаешь как сделать, не чтобы каждую тычку делался таймер, а чтобы обновлялся постоянно один и тот же. Насколько помню, нужно просто дописать тут `TIMER_UNIQUE|TIMER_OVERRIDE` флаги и теперь будет всегда 1 таймер, который будет при каждой тычке пересоздаваться

2022-09-29 15:21 UTC, KIBORG04 commented on code/modules/mining/equipment_locker.dm
> +		QDEL_IN(src, 0.4 SECOND)
откуда 0,4?

2022-09-29 15:25 UTC, KIBORG04 commented on code/modules/mining/mine_items.dm
>  	if(istype(I, /obj/item/kinetic_upgrade/speed))
Можно это нормально сделать? Каждому `obj/item/kinetic_upgrade` дать какой-то прок, который будет вызывать КА. В этих проках каждый апгрейд сам будет решать как апгрейдить КА, а не как тут щас

2022-09-29 15:26 UTC, KIBORG04 commented on code/modules/mining/mine_items.dm
> +				to_chat(user, "<span class='warning'>Достигнут лимит скорострельности!</span>")
Это к комменту про нормальную реализацию. В ней ты убираешь нафиг этот свитч и этот прок, эти характеристики пусть апгрейд меняет, а не КА

2022-10-01 19:34 UTC, BiQndy commented
Обновление. Переписал код улучшений для кинетика, и теперь их можно вытаскивать при помощи отвёртки: высвечивается радиальное меню с выбором. Так же теперь в кинетик можно вставить 3 улучшения. Улучшить ОДНУ характеристику можно максимум два раза. В игру добавлен расширитель для кинетика: он позволяет вставить четвёртое улучшение. Изменена логика "остывания" перезарядки резонатора: теперь если не стрелять 5 секунд, то перезарядка сбросится до дефолтной. Изменён звук при "лопании" шарика от резонатора.

2022-10-03 09:09 UTC, BiQndy commented on code/modules/mining/mine_items.dm
>  	if(istype(I, /obj/item/kinetic_upgrade/speed))
✔ done.

2022-10-03 17:08 UTC, Sakuya-Izayoi commented on code/modules/mining/minerals.dm
> +	var/name			// Tag for use in overlay generation/list population
табы вместо пробелов, и так везде

2022-10-03 17:26 UTC, BiQndy commented on code/modules/mining/minerals.dm
> +	var/name			// Tag for use in overlay generation/list population
ну это конечно ни на что не влияет, но есть ли какой то стандарт для комментариев?

2022-10-04 14:46 UTC, arygal commented
А можно добавить улучшение для кинетика которое позволит ему наносить урон в атмосфере? Получение - емаг на раздатчик.

2022-10-04 14:47 UTC, BiQndy commented
> А можно добавить улучшение для кинетика которое позволит ему наносить урон в атмосфере? Получение - емаг на раздатчик.

интересная идея. Но хз насколько балансная

2022-10-04 16:57 UTC, arygal commented
> > А можно добавить улучшение для кинетика которое позволит ему наносить урон в атмосфере? Получение - емаг на раздатчик.
> 
> интересная идея. Но хз насколько балансная

На ТГ есть. На парадизах есть почему бы и нам не завести?

2022-10-21 10:04 UTC, Deahaka commented
Я вот сейчас посмотрел. На ониксе кирку делают отличной от бура тем, что копает без задержки. Учитывая, что у нас уже есть молоток, который работает также, может кирку проапгрейдить в плане удобства? (а добывать она например будет меньше ресурса/будет оставлять rock debris чаще.

2022-10-31 07:57 UTC, BiQndy commented
Был бы рад хотя бы поверхностному ревью этого пр'а

2022-10-31 20:34 UTC, Sakuya-Izayoi commented on code/modules/mining/minerals.dm
> +	var/name			// Tag for use in overlay generation/list population
табы для отступов вначале строки, пробелы для всего остального

2022-11-01 21:58 UTC, KIBORG04 commented
Вот бы конфликты решали

2022-11-01 22:03 UTC, KIBORG04 commented on code/modules/mining/mine_items.dm
> -		sleep(1)
Все еще нет информации о удаление фичи.

2022-11-01 22:05 UTC, BiQndy commented on code/modules/mining/mine_items.dm
> -		sleep(1)
она не нужная и не интересная, больше даже нелепая

2022-11-01 22:07 UTC, KIBORG04 commented on code/modules/mining/mine_items.dm
> +		if(max_upgrades >= 4)
Мб стоит сделать отдельную переменную, которая и будет отвечать за количество вставленных экспандеров? Тогда код опять же будет легче расширяться и уменьшатся магические числа.

2022-11-01 22:09 UTC, KIBORG04 commented on code/modules/mining/mine_items.dm
> +			possible_removals[upg] = image(icon = upg.icon, icon_state = upg.icon_state)
Зачем нужен choices, если ты как ключ уже вставляешь объект? То есть, у тебя `removal_choice` и так содержит нужный апргейд

2022-11-01 22:10 UTC, KIBORG04 commented on code/modules/mining/mine_items.dm
> +		UPG.install(src)
Я лично не вижу причин не поместить вызов upgrade_kinetic() в install(). Тоже самое и про downgrade_kinetic(user, src) remove()

2022-11-01 22:11 UTC, KIBORG04 commented on code/modules/mining/mine_items.dm
> +	if(istype(I, /obj/item/kinetic_upgrade))
Добавь в конец каждой ифки return, либо добавь else. У тебя лишний код будет работать иначе.

2022-11-01 22:14 UTC, KIBORG04 commented on code/modules/mining/mine_items.dm
> +	desc += "Ускоряет <span class='notice'><B>перезарядку</B></span> на <span class='notice'><B>[cooldown_reduction / 10]</B></span> секунд."
```suggestion
	desc += "Ускоряет <span class='notice'><B>перезарядку</B></span> на <span class='notice'><B>[cooldown_reduction / 10]</B></span> секунды."
```
0,35 секунды

2022-11-01 22:15 UTC, KIBORG04 requested changes
Вроде всё

2022-11-05 15:29 UTC, arygal commented
Стимпак сейчас говно.
`list_reagents = list("inaprovaline" = 5, "coffee" = 13, "tricordrazine" = 2)`
Баффни его - он и за текущую цену не оправдан, а тут ещё и надбавка.

2022-11-26 23:09 UTC, Shootnik01 commented
![Ef2iFIMWsAAz7Pw.jpg](https://user-images.githubusercontent.com/75479005/204112084-6ce40ee7-e932-4044-90ce-dc76c743c8b6.jpg)

2022-12-03 09:28 UTC, BiQndy commented
я ожил, откройте ПР пожалуйста @TauCetiStation/maintainers

2022-12-03 10:37 UTC, BiQndy commented
Пофиксил конфликты, прошелся по ревью Киборга

2022-12-08 22:06 UTC, KIBORG04 commented on code/modules/mining/mine_items.dm
> +	KA.mineral_multiply_coefficient += additional_coefficient
У нас есть `/datum/modval` штука, которая позволяет удобнее с такими значениями и модификаторами работать. Но это так, на будущее, когда будет дота с 10 бафами и 10 дебаффами. Щас не заставляю

2022-12-08 22:06 UTC, KIBORG04 approved these changes
да вроде чётко

2022-12-10 20:06 UTC, merged