Фикс звука тряпки и ведра при поднятии установке их на стол
TauCetiStation/TauCetiClassic pull request #10282
Opened 2022-10-24 01:31 UTC by FelixRuin

## Описание изменений
Я по звукам не секу впринципе, но теперь ведро и тряпочка не шумят стекло при поднимании и поставлении их на стол
Ну а ещё общая переменная для звука поднятия и опускания штук айтемам (да знаю всёравно попросили-бы)
## Почему и что этот ПР улучшит
Теперь нежные уши игроков не будут сталкиваться со звуком стекла у тканевой тряпки
close https://github.com/TauCetiStation/TauCetiClassic/issues/10031
## Авторство
Winter Schock - Felicia Ruin
## Чеинжлог
:cl: Winter Schock
- bugfix: ведро и тряпка не издают звуки стекла при поднятии и опускании вещей

2022-10-24 01:31 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2022-10-24 12:11 UTC, Sakuya-Izayoi approved these changes

2022-10-24 19:31 UTC, Sakuya-Izayoi commented on code/game/objects/items.dm
> +	playsound(user, dropped_sound, VOL_EFFECTS_MASTER)
```
if(isturf(loc) && (user.loc != loc))
```

потерялась эта проверка

2022-10-24 19:44 UTC, FelixRuin commented on code/game/objects/items.dm
> +	playsound(user, dropped_sound, VOL_EFFECTS_MASTER)
а смысл в ней? На мой вкус очень даже прикольно звучит когда вытаскиваешь вещи из коробки и такой тук-тук-тук-тук

2022-10-24 20:16 UTC, Sakuya-Izayoi commented on code/modules/reagents/reagent_containers/glass.dm
> +		playsound(user, dropped_sound, VOL_EFFECTS_MASTER)
тут два раза вроде звук играется

2022-10-24 20:34 UTC, FelixRuin commented on code/modules/reagents/reagent_containers/glass.dm
> +		playsound(user, dropped_sound, VOL_EFFECTS_MASTER)
готово

2022-10-25 18:38 UTC, KIBORG04 commented on code/game/objects/items.dm
>  	SHOULD_CALL_PARENT(TRUE)
Перемести свои плейсауды под `SHOULD_CALL_PARENT(TRUE)` дефайн.

2022-10-25 18:39 UTC, KIBORG04 commented on code/game/objects/items.dm
> +	playsound(user, dropped_sound, VOL_EFFECTS_MASTER)
Ни одного слова про это в ПРе с фиксом бага

2022-10-25 20:17 UTC, Sakuya-Izayoi requested changes
ревью выше

2022-10-25 20:45 UTC, FelixRuin commented on code/game/objects/items.dm
> +	playsound(user, dropped_sound, VOL_EFFECTS_MASTER)
готово

2022-10-25 20:45 UTC, FelixRuin commented on code/game/objects/items.dm
>  	SHOULD_CALL_PARENT(TRUE)
готово

2022-10-25 20:56 UTC, FelixRuin commented on code/game/objects/items.dm
> +	playsound(user, dropped_sound, VOL_EFFECTS_MASTER)
готово

2022-10-25 21:05 UTC, Sakuya-Izayoi commented on code/game/objects/items.dm
> +	if(isturf(loc) && (user.loc != loc))
при пикапе изначально не было этого чека

2022-10-25 21:06 UTC, FelixRuin commented on code/game/objects/items.dm
> +	if(isturf(loc) && (user.loc != loc))
готово

2022-10-25 22:47 UTC, KIBORG04 commented on code/game/objects/items.dm
> +	if(isturf(loc) && (user.loc != loc))
Насколько я помню, дроппед может спокойно вызываться без юзера и тут будут рантаймы для ифки и плейсаунда. А вот пикап вроде всегда с юзером.

Ну и я сразу нашел вызов без юзера
https://github.com/TauCetiStation/TauCetiClassic/blob/494bce228ce94fa2b7fb8a5cea78bc4aaed0e9a5/code/modules/mob/inventory.dm#L253

2022-10-25 22:51 UTC, FelixRuin commented on code/game/objects/items.dm
> +	if(isturf(loc) && (user.loc != loc))
```suggestion
	if(user && isturf(loc) && (user.loc != loc))
```
типо такого, да?

2022-10-25 22:53 UTC, KIBORG04 commented on code/game/objects/items.dm
> +	if(isturf(loc) && (user.loc != loc))
```suggestion
	if(isturf(loc) && (user?.loc != loc))
```
можно так

2022-10-25 23:35 UTC, FelixRuin commented on code/game/objects/items.dm
> +	if(isturf(loc) && (user.loc != loc))
хорофо

2022-10-26 07:11 UTC, KIBORG04 commented on code/game/objects/items.dm
> +	if(user?.loc != loc && isturf(loc))
```suggestion
	if(user && user.loc != loc && isturf(loc))
```
Блин, тут же сравнение, извиняюсь за вброс

2022-10-26 17:53 UTC, FelixRuin commented on code/game/objects/items.dm
> +	if(user?.loc != loc && isturf(loc))
жабка

2022-10-27 17:37 UTC, Sakuya-Izayoi commented on code/game/objects/items.dm
> +	playsound(user, pickup_sound, VOL_EFFECTS_MASTER)
перемести после ретерн фолс

2022-10-27 18:12 UTC, FelixRuin commented on code/game/objects/items.dm
>  		return FALSE
```suggestion
	if(SEND_SIGNAL(src, COMSIG_ITEM_PICKUP, user) & COMPONENT_ITEM_NO_PICKUP)
		playsound(user, pickup_sound, VOL_EFFECTS_MASTER)
		return FALSE
```

2022-10-27 18:13 UTC, FelixRuin commented on code/game/objects/items.dm
> +	playsound(user, pickup_sound, VOL_EFFECTS_MASTER)
готово

2022-11-01 21:24 UTC, KIBORG04 commented on code/game/objects/items.dm
>  	return TRUE
```suggestion
	if(SEND_SIGNAL(src, COMSIG_ITEM_PICKUP, user) & COMPONENT_ITEM_NO_PICKUP)
		return FALSE
	playsound(user, pickup_sound, VOL_EFFECTS_MASTER)
	return TRUE
```
Ты блин сугома. Ифка буквально запрещает делать пикап

2022-11-01 21:26 UTC, KIBORG04 requested changes
давайте мерж после коммит саггешена

2022-11-02 15:59 UTC, FelixRuin commented
> давайте мерж после коммит саггешена

🐢 ну типо да...

2022-11-02 16:21 UTC, merged