Магбутсы выключаются после снятия рига
TauCetiStation/TauCetiClassic pull request #10307
Opened 2022-10-31 12:15 UTC by simb11

## Описание изменений
Магбутсы выключатся после снятия рига
## Почему и что этот ПР улучшит
При снятии рига магбутсы оставались включены и продолжали работать, но замедление было такое, будто они были выключены.
## Авторство

## Чеинжлог

2022-10-31 12:15 UTC, TauKitty commented
###### Changelog status: :radio_button: No changelog

2022-10-31 18:43 UTC, Sakuya-Izayoi commented
посмотри ишьюсы вроде там чето было такое

2022-10-31 18:43 UTC, Sakuya-Izayoi commented on code/modules/clothing/spacesuits/rig/rig.dm
> +		magpulse = 0 //disables magboots when dropped
```suggestion
		magpulse = FALSE //disables magboots when dropped
```

2022-10-31 19:08 UTC, simb11 commented
ничего связанного с этим в ишшуйсах не нашёл

2022-10-31 19:41 UTC, Sakuya-Izayoi approved these changes
было бы неплохо в принципе отрефакторить вот этот механизм накидывания слоу, магбутов и так далее, в идеале чтобы не нужно было вырубать магбуты при снятии хардсьюита, а чтобы слоудаун сохранялся. если киборг будет проходить мимо и его устроит текущее решение то пускай мержит, но на мой взгляд это не более чем заплатка.

2022-11-03 19:47 UTC, Sakuya-Izayoi requested changes
ревью выше

2022-11-04 10:58 UTC, simb11 commented
переделал вроде как

2022-11-04 11:37 UTC, KIBORG04 commented on code/modules/clothing/spacesuits/rig/rig.dm
> +			if(magpulse == TRUE)
```suggestion
			if(magpulse)
```
а ещё вроде как, здесь ничего не нужно добавлять. Я пока не понял смысл вообще этого.

2022-11-04 11:37 UTC, KIBORG04 commented on code/modules/clothing/spacesuits/rig/rig.dm
> +		if(!offline)// so rigs without cell are slow
```suggestion
		if(!offline) // so rigs without cell are slow
```

2022-11-04 11:37 UTC, KIBORG04 commented on code/modules/clothing/spacesuits/rig/rig.dm
> +/obj/item/clothing/suit/space/rig/proc/toggle_magpulse()
передавай сюда user'а, не используй usr

2022-11-04 11:38 UTC, KIBORG04 commented on code/modules/clothing/spacesuits/rig/rig.dm
> +		src.slowdown = boots.slowdown_off
```suggestion
		slowdown = boots.slowdown_off
```

2022-11-04 11:38 UTC, KIBORG04 commented on code/modules/clothing/spacesuits/rig/rig.dm
> +		to_chat(usr, "You disable \the [src] the mag-pulse traction system.")
передавай сюда user'а, не используй usr

2022-11-04 11:38 UTC, KIBORG04 commented on code/modules/clothing/spacesuits/rig/rig.dm
> +		src.slowdown = initial(slowdown)
```suggestion
		slowdown = initial(slowdown)
```

2022-11-04 12:05 UTC, simb11 commented
вроде всё

2022-11-04 12:09 UTC, KIBORG04 commented on code/modules/clothing/spacesuits/rig/rig.dm
> +/obj/item/clothing/suit/space/rig/proc/toggle_magpulse()
не все, но закрыл конвершен..

2022-11-04 12:09 UTC, KIBORG04 commented on code/modules/clothing/spacesuits/rig/rig.dm
> +		to_chat(usr, "You disable \the [src] the mag-pulse traction system.")
не все, но закрыл конвершен..

2022-11-04 12:21 UTC, simb11 commented on code/modules/clothing/spacesuits/rig/rig.dm
> +		to_chat(usr, "You disable \the [src] the mag-pulse traction system.")
типа такого?

2022-11-04 12:22 UTC, KIBORG04 commented on code/modules/clothing/spacesuits/rig/rig.dm
> +/obj/item/clothing/suit/space/rig/proc/toggle_magpulse(user)
```suggestion
/obj/item/clothing/suit/space/rig/proc/toggle_magpulse(mob/user)
```

2022-11-04 12:22 UTC, KIBORG04 commented on code/modules/clothing/spacesuits/rig/rig.dm
> +		user.slowdown = boots.slowdown_off
```suggestion
		slowdown = boots.slowdown_off
```
Бля...

2022-11-04 12:23 UTC, KIBORG04 commented on code/modules/clothing/spacesuits/rig/rig.dm
> +		user.slowdown = initial(slowdown)
```suggestion
		slowdown = initial(slowdown)
```

2022-11-04 12:23 UTC, KIBORG04 commented on code/modules/clothing/spacesuits/rig/rig.dm
> +		to_chat(usr, "You disable \the [src] the mag-pulse traction system.")
```suggestion
		to_chat(user, "You disable \the [src] the mag-pulse traction system.")
```

2022-11-04 12:23 UTC, KIBORG04 commented on code/modules/clothing/spacesuits/rig/rig.dm
> +		to_chat(usr, "You disable \the [src] the mag-pulse traction system.")
```suggestion
		to_chat(user, "You disable \the [src] the mag-pulse traction system.")
```

2022-11-04 12:35 UTC, KIBORG04 commented on code/modules/clothing/spacesuits/rig/rig.dm
> +		disable_magpulse()
```suggestion
		disable_magpulse(H)
```

2022-11-04 12:36 UTC, KIBORG04 commented on code/modules/clothing/spacesuits/rig/rig.dm
> +		toggle_magpulse()
```suggestion
		toggle_magpulse(H)
```

2022-11-04 12:36 UTC, KIBORG04 commented on code/modules/clothing/spacesuits/rig/rig.dm
> +
А где вызов disable_magpulse при снятие рига то?))

2022-11-04 12:58 UTC, simb11 commented
всё???

2022-11-04 13:00 UTC, KIBORG04 commented on code/modules/clothing/spacesuits/rig/rig.dm
> +			if(magpulse)
В какой ситуации макбутсы будут включены, при надевание рига?

2022-11-04 13:01 UTC, simb11 commented on code/modules/clothing/spacesuits/rig/rig.dm
> +			if(magpulse)
ни в какой???????

2022-11-04 13:01 UTC, KIBORG04 commented on code/modules/clothing/spacesuits/rig/rig.dm
> +			if(magpulse)
Я то хз, значит ифка не нужна?

2022-11-04 13:16 UTC, simb11 commented on code/modules/clothing/spacesuits/rig/rig.dm
> +			if(magpulse)
убрал иф

2022-11-10 14:43 UTC, LudwigVonChesterfield commented on code/modules/clothing/spacesuits/rig/rig.dm
> +/obj/item/clothing/suit/space/rig/proc/toggle_magpulse(mob/user)
мне кажется супер странным что риг отдельно хендлит логику бутсов..... но так уже было поэтому не могу докопаться до этого ПР-а

2022-11-10 14:43 UTC, LudwigVonChesterfield approved these changes
хороший багфикс

2022-11-13 20:20 UTC, ZVee commented on code/modules/clothing/spacesuits/rig/rig.dm
> +/obj/item/clothing/suit/space/rig/proc/toggle_magpulse(mob/user)
> докопаться до этого ПР-а

Я бы toggle на enable поменял, т.к toggle всетаки подразумевает переключение состояний, а не выставление конкретного.

2022-11-13 20:28 UTC, LudwigVonChesterfield commented on code/modules/clothing/spacesuits/rig/rig.dm
> +/obj/item/clothing/suit/space/rig/proc/toggle_magpulse(mob/user)
```suggestion
/obj/item/clothing/suit/space/rig/proc/enable_magpulse(mob/user)
```

2022-11-13 20:29 UTC, LudwigVonChesterfield commented on code/modules/clothing/spacesuits/rig/rig.dm
> +		toggle_magpulse(H)
```suggestion
		enable_magpulse(H)
```

2022-11-14 15:08 UTC, merged