Удаление кифоторина
TauCetiStation/TauCetiClassic pull request #10333
Opened 2022-11-08 11:28 UTC by simb11

## Описание изменений
Удаляет кифоторин.
Теперь меднаноботы могут лечить кости и отращивать конечности.
Лечение костей и отращивание конечностей больше не сопровождается высасыванием крови и нутриментов.
## Почему и что этот ПР улучшит
Не вижу смысла в существовании кифоторина, ведь оно ОЧЕНЬ сложно в создании, использовании и я вообще плохо понимаю, зачем оно существует. 
Про создание понятно, как мне кажется, очень сложно и всё такое.
Про использование - это лекарство, как лично я думаю, нужно для излечения переломов и оторванных конечностей без помощи медиков, однако, во первых - редко бывает так, чтобы на станции не оставалось живых медиков, во вторых - без помощи этих самых медиков его нельзя использовать, ведь человеку наносится обычный урон и целая куча болеурона, плюс ко всему, из человека высасывается огромное количество крови (полтора процента каждый тик) и просто нутриментов, из-за чего бедному пациенту приходится лежать под капельницей с сахаром и кровью примерно минут 5. 
Не много ли геморроя для излечения косточек или отращивания конечностей, не кажется? Да и стоит учесть, что кифоторин делается сто лет из кучи других лекарств.
Потому реагент, который существует только для лечения костей и утраченных конечностей и который варится достаточно долгое количество времени, мне кажется слишком уж ненужным, пусть уж меднаноботы это делают.
## Авторство

## Чеинжлог
:cl: Simbaka
- del: Удалён кифоторин.
- tweak: Медицинские наноботы теперь отращивают конечности и лечат кости.
- balance: Отращивание конечностей с помощью лекарств больше не тратит кровь.

2022-11-08 11:28 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2022-11-08 11:33 UTC, Chip11-n commented
Может быть и логично. Я не помню, когда в последний раз видел кифоторин, и уж тем более, когда его применяли. В теории, смысла от него практически нет, ведь тот же хирург сделает это с большим интересом, быстрее и менее нудно. А так, варишь сложное лекарство, лечиться которым ты будешь исключительно в меде, дольше и потом ещё и будешь голодным. Оно совершенно не стоит своих затрат. Хоть по времени, хоть по ресурсам. 
Наноботы же я хоть и редко, но вижу. И то, их ведь не варят в банках по 30 унций, так что вряд ли выйдет большая проблема. Можно по идее уменьшить порог обращения нанитами, дабы их было более опасно использовать

2022-11-08 11:35 UTC, maleyvich commented
> Может быть и логично. Я не помню, когда в последний раз видел кифоторин, и уж тем более, когда его применяли. В теории, смысла от него практически нет, ведь тот же хирург сделает это с большим интересом, быстрее и менее нудно. А так, варишь сложное лекарство, лечиться которым ты будешь исключительно в меде, дольше и потом ещё и будешь голодным. Оно совершенно не стоит своих затрат. Хоть по времени, хоть по ресурсам. Наноботы же я хоть и редко, но вижу. И то, их ведь не варят в банках по 30 унций, так что вряд ли выйдет большая проблема. Можно по идее уменьшить порог обращения нанитами, дабы их было более опасно использовать

когда все станут ими пользоваться то сто проц понерфят а так зачем заранее делать эпидемию нанохорроров?

2022-11-08 15:41 UTC, simb11 commented
> Так он не лечит переломы.

лечит

2022-11-08 21:33 UTC, arygal commented
> > Так он не лечит переломы.
> 
> лечит

Сейчас проверил: лечит перелом у куклы обколотой нутринтами - я был неправ. Без обколки нутриентами - нихрена не лечит(что и 2 раза было со мной в раунде).

2022-11-09 23:19 UTC, Lafrien commented
Сварить Кифоторин это как сделать Токомак при рабочей Синге.
Просто делается от балды лишь потому, что это есть в коде, а по факту никому не нужно и слишком запутанно.
Перенос механики Кифа на Меднаноботов вполне хорошая идея. Уж его-то более легче варить, а контролировать дозировку можно и научиться. Плюс без помощи РнД и Бармена всё-равно не обойтись, но хотя бы не нужно ждать шахтёров.

2022-11-14 15:05 UTC, LudwigVonChesterfield requested changes
Кифоторин не вредит никому как реагент, почему бы не оставить его вместе с изменением меднаноботов?

В лучшем случае - дать ему новое использование, в худшем - просто оставить на тот редкий случай когда кто-то захочет похвастаться что таки смог сварить кифоторин...

2022-11-14 15:30 UTC, simb11 commented
вернул

2022-11-14 16:02 UTC, LudwigVonChesterfield commented
ну теперь нужен ребрендинг названия и описания ПР-а

2022-11-14 20:10 UTC, simb11 commented
поменял название и чейнджлог, описание не вижу смысла менять

2022-11-18 14:58 UTC, LudwigVonChesterfield commented on code/modules/reagents/reagent_containers/glass/bottle.dm
> +/obj/item/weapon/reagent_containers/glass/bottle/nanobots
если бутылка нигде не юзалась почему она вообще существует

2022-11-18 15:00 UTC, LudwigVonChesterfield commented on code/modules/reagents/reagent_types/Chemistry-Miscellaneous.dm
> +				if(H.regenerating_bodypart)
может я очень много прошу, но сейчас есть рантайм связанный с регенерацией конечностей

испытывают его только дионы на данный момент, потому-что только их конечности кьюделитают

суть рантайма: regenerating_bodypart - ссылка на орган, нигде не подчищается. если удалить конечность (зажаркой, к примеру) - а потом отрастить новую на её месте произойдёт рантайм

#8974

2022-11-20 13:12 UTC, simb11 commented on code/modules/reagents/reagent_containers/glass/bottle.dm
> +/obj/item/weapon/reagent_containers/glass/bottle/nanobots
Без понятия. Её удалить?

2022-11-23 14:03 UTC, LudwigVonChesterfield commented on code/modules/mob/living/carbon/human/human.dm
> -			if(use_cost)
скрытнобаф дион на бесплатный реген конечностей :)

2022-11-23 14:04 UTC, LudwigVonChesterfield commented on code/modules/mob/living/carbon/human/human.dm
> -		if(remove_blood_amount)
скрытнобафф Кифоторина на отсутствие потери крови

2022-12-04 19:02 UTC, pro100kotah commented
Слушай, а кифоторин из слаймов звучит реально отлично. Как реагент он будет хуже чем меднаноботы, отсюда и заебка с нутриментами и кровью. Но, если хочешь нормальное действенное лекарство, будь добр умоляй химиков наделать наноботов.

2022-12-07 15:49 UTC, simb11 commented on code/modules/mob/living/carbon/human/human.dm
> -			if(use_cost)
сделал платным исключительно для дион.

2022-12-07 15:54 UTC, simb11 commented on code/modules/mob/living/carbon/human/human.dm
> -		if(remove_blood_amount)
написал про это в чейнджлоге

2023-01-10 21:57 UTC, closed without merging