Ремап медбея, техов медбея, библиотеки бокса
TauCetiStation/TauCetiClassic pull request #10374
Opened 2022-11-15 14:57 UTC by DarthSidiousPalpatine

## Описание изменений
### **Здрасьте, с вами снова Гисев и это снова попытка ремапнуть медбей.**

### **Огромная красивая картинка без проводов, труб и пр:**
![image](https://user-images.githubusercontent.com/21008918/201929675-efe00485-f9a4-4cfc-be06-57f1442ba02c.png)
### **Огромная красивая картинка с проводами, трубами и пр:**
![image](https://user-images.githubusercontent.com/21008918/201929546-e23e8157-4de4-441c-ba6d-38d2ed67761b.png)

## Почему и что этот ПР улучшит
### Изменения:
**Ресепшн стал угловым, вход в коридор медбея стал свободным:**
![image](https://user-images.githubusercontent.com/21008918/201930367-59641dce-182a-4429-9716-e69b391dcb93.png)
**Комната персонала перекочевала в коридор, выделенный только для персонала и связывающий ресепшн, коридор меда, химию, склад и лечебную комнату:**
![image](https://user-images.githubusercontent.com/21008918/201930620-6755ba46-170a-4a30-9099-24af02f02a97.png)
**Химия переехала к техам, заимела дверь в техи, которая также закрываться на створки может. Заимела свою аптеку, в которую химик может положить что угодно и любой со станции сможет прийти и взять себе это:**
![image](https://user-images.githubusercontent.com/21008918/201930909-e4f84c35-c250-4da5-9aa9-cf35951508f0.png)
**Склад медбея заимел кресло-каталку, склад каталок, бак и охладитель крио переехали сюда, как для быстрой настройки в начале смены, так и для возможности саботажа, через техи. Замена бака на другой, отключение охладителя и т.п.:**
![image](https://user-images.githubusercontent.com/21008918/201931289-94b8a137-b929-47e1-a058-d07d1315c936.png)
**Основной коридор медбея стал открытым для всех, по левую и правую сторону у него скамьи и двери в Крио, Лечебную комнату, Кабинет психолога, Кабинет терапевта, Морг, Общественный туалет, Кабинет Главврача:**
![image](https://user-images.githubusercontent.com/21008918/201940597-d92e32c8-8a0f-4d5e-92a8-7cdf5cb10017.png)
**Крио перекочевало к ресепшну, расширилось и стало первой комнатой в медбее, что позволит скорее скидывать трупы на реанимацию туда. Также оно получило третью колбу и прямой выход в клонилку:**
![image](https://user-images.githubusercontent.com/21008918/201942319-7171a80e-6328-4a18-8973-3ddd20e05bc9.png)
**Лечебная комната сузилась, потому как перестала быть проходной, по факту полезной площади где можно стоять и нормально лечить кого-то - стало больше. Из этой комнаты выход в коридор персонала, в хирургическую и в дневной стационар:**
![image](https://user-images.githubusercontent.com/21008918/201944266-b494f9e1-92b7-4cb7-8b90-4f10fa83956a.png)
**Генетика сузилась, заимела открытый сад с окнами к психологу и в общий коридор, вместо прохода до морга теперь мусорка в морг, как у роботеха, чтобы утилизировать генетические трупики. Из клонилки теперь прямой выход в Крио:**
![image](https://user-images.githubusercontent.com/21008918/201943263-0c97aaae-a2f9-4832-9e41-2e464416486c.png)
**Хирургическая, вместо каталок на полу они лежат на стойке в размере 4-х штук. Две хирургии сузились, но полезного пространство стало не на много меньше. Вокруг стола есть место как для пары хирургов, так и для трёх машин:**
![image](https://user-images.githubusercontent.com/21008918/201945247-29319eba-fafb-4aae-bafc-7e00b7629550.png)
**Комната психолога сузилась, но заимела как выход в открытый коридор, так и окно в сад с животными:**
![image](https://user-images.githubusercontent.com/21008918/201945644-46b520fc-f64c-47ec-a1c6-8bbbe34a8b0a.png)
**Кабинет терапевта. По приколу, РП-кабинет с плакатом проверки зрения, с весами, что показывают рост и весь вставшего на них по examain-у, кабинет, где может сидеть интерн и выписывать ЛСД кловну или какой-нибудь антаг, что будет прятать трупы/лут в тайле раздевалки, который скрыт для всех ширмой и непрозрачным стеклом. Ведь никто не зайдёт сюда проверить что там у терапевта :dovolen: :**
![image](https://user-images.githubusercontent.com/21008918/201945994-5bdc2bc5-630b-4659-b218-c980256a7ccd.png)
**Морг. Ну, морг:**
![image](https://user-images.githubusercontent.com/21008918/201946349-91a66b03-0d39-4878-9c70-376858e44b5b.png)
**Туалет:**
![image](https://user-images.githubusercontent.com/21008918/201946479-79f8eea4-1343-42af-9ff5-f31cf85f464b.png)
**Кабинет СМО в конце коридора ~~у параши~~ находится через одну стенку от техов с пары сторон, теперь это не самый защищённый кабинет глав, имеет кнопку открытия двери, а также кнопку карантина, что закрывает практически все входы и выходы из медбея:**
![image](https://user-images.githubusercontent.com/21008918/201946912-d9775472-8af1-4aef-b572-7b83324f8129.png)
**Дневной стационар, три индивидуальные палаты, два криослипера, столик, коврики, капельницы для процедур, уголок дежурного интерна :hugs: :**
![image](https://user-images.githubusercontent.com/21008918/201947247-0dda59dc-5b0e-48c4-a678-69a479ebe99a.png)
**Вирусология не изменилась:**
![image](https://user-images.githubusercontent.com/21008918/201947426-c77b3031-6301-44c9-8ab6-ae433e4d6ed6.png)
**Библиотека заимела зеркальный церкви вход, чуть расширилась, сохранила нижнюю комнату без изменений, верхняя комната уже не вместилась и была пересобрана:**
![image](https://user-images.githubusercontent.com/21008918/201947925-775458bb-7fa3-4c68-879e-5da4aee4b12e.png)
**Техи атмосферки, стали прямыми, но избавились от однотайловых кишок, получили курилку, по приколу 🚬 :**
![image](https://user-images.githubusercontent.com/21008918/201948333-8daa54da-f967-48a4-8d3f-ecea65cc43a5.png)
**Странная мини-пожарная комната оформилась, получила пол, получила больше ящиков, плюс секретный пожарный топор (который на деле не пожарный топор, никакой резни):**
![image](https://user-images.githubusercontent.com/21008918/201948738-2052c653-1fc3-4e4d-be72-2fc12b201a8c.png)
**Техи медбея и библиотеки значительно расширились, больше не имеют однотайловых коридоров, все коридоры в два тайла, множество разветвлений, ответвлений, гетто бомжатня по центру, курилка у юго-восточных соляр, гетто-ботаника на юге со стеклом в космос, всякие мелкие комнатки и пр.:**
![image](https://user-images.githubusercontent.com/21008918/201949665-6b7bf82d-e911-4ef1-94c9-561cb6addf3e.png)
Небольшой аппендикс, который не влез на картинку:
![image](https://user-images.githubusercontent.com/21008918/201949794-b301898c-6abc-41e2-88ee-3e5b3a72ae6e.png)

Повсюду теперь 100500 цветочков, таблетки парацетамола, маленькие лампочки в огромном масштабе.

## Авторство
AndreyGysev и все все все, кто помогал в дискорде

## Чеинжлог
:cl:
 - map: Ремап медбея, библиотеки и техов на Boxstation
 - rscadd: Добавлены весы, измеряющие рост и вес, плакат проверки зрения, фейк-пожарный-топор,  значки морга, аптеки.

2022-11-15 15:01 UTC, TauKitty commented
Этот запрос на слияние был упомянут в **Tau Ceti Station Forum**. Там могут быть соответствующие подробности:

https://forum.taucetistation.org/t/suzhenie-meda/36384/79

2022-11-15 15:03 UTC, Tap0r approved these changes

2022-11-15 15:09 UTC, AndroBetel requested changes
когда новая карта

2022-11-15 15:14 UTC, Tap0r commented
так стоп а где
![image](https://user-images.githubusercontent.com/88531962/201955303-1471e8ad-51ea-4527-91c4-bd3bca6aed6d.png)

2022-11-15 15:16 UTC, DarthSidiousPalpatine commented
> так стоп а где ![image](https://user-images.githubusercontent.com/88531962/201955303-1471e8ad-51ea-4527-91c4-bd3bca6aed6d.png)

Кто, что, где

2022-11-15 15:18 UTC, Tap0r commented
а все отбой у меня почему-то не всю твою ветку подгрузило

2022-11-15 16:52 UTC, Tap0r commented
Такое не принято делать. Опусти аварийки на тайл ниже. Если вдруг челикам придется выбираться с ресепшена ломая окно, то они за одной аварийкой сразу еще обнаружат, ну не оч короче такое.
![image](https://user-images.githubusercontent.com/88531962/201956472-35704ae6-5c0f-4b24-87e0-29f7a3ac1372.png)

Стремная мусорка в проходе. Куча говна накиданная на 1 стол не пойми как с просто ебейшими смещениями аж на другой тайл залазит. Мониторчик камер сползает со стола. Кусок ноута откушен стеклом. Проводка проведена под стеклом и консолью. Аж 2 камеры в лампе. Ни одного интеркома на такую большую площадь. Это непонятное стекло разделитель которое только мешать будет сохранено. Ну и чето не до конца понятное с плиткой.

![image](https://user-images.githubusercontent.com/88531962/201961162-ee98e702-50fd-4970-9a20-5f2c117fabc5.png)

Крутые смещения, снова. С книжкой и т.п пох, а вот зарядник могут открутить в блоба например, и таскать по коридору зарядник с таким смещением это кринглс. Интеркома нема.

![image](https://user-images.githubusercontent.com/88531962/201961877-717ec7a5-f907-4534-abf4-4bf1314cc175.png)

Снова пиздец на столах. Ну добавь еще стол, туда часть переложи, зачем пытаться по 5+ предметов уложить на один стол, если это не склад даже. Ну и великолепные абсолютно рандомные и сикясь накись сделанные смещения настенной машинерии. 
![image](https://user-images.githubusercontent.com/88531962/201962390-c27701c7-3bcf-43d1-b262-f8a7b1ed9963.png)
![image](https://user-images.githubusercontent.com/88531962/201963032-77d2beec-7fe4-4217-a9e9-b7a572496501.png)
только пизданите после этого :arrow_up:  чето про не нужность стандартизации.

Я не припомню, чтобы у нас где-то приваси шаттерсы ставились в шлюз, да и сама по себе такая оверзащищенность химиков имхо лишняя. Ну тут опять попытки выставить на столе все что только можно, и колокольчик и бумагу и ручку. Коробка с банками пилюль лежит в шкафу кодом, зачем вторая, если и первой редко пользуются? Банок инопровалина стало на 1 меньше, это очень, пиздец как плохо. Эти банки с пилюлями позволяют прошареным химозам не хило экономить заряд диспенсеров, который не сказать что резиновый. Мне не нравится что сайнс гласесы ушли в шкаф. Щас их хотя бы малогеи могут одеть, а так мне кажется их вообще забудут. Спейс клинер на тайл верхний залазит, если сверху пробегать, он тебе под ноги уйдет, поэтому кринж. И где интеркомы????????? Я ни одного пока что не увидел. Гусев хочет сбросить иго ИИшной прослушки?
![image](https://user-images.githubusercontent.com/88531962/201964463-e215d43e-1d9f-4fe5-95c1-9ae0161c68a2.png)
Ну и вот возьми перекинь корзинку бумажек на столик рядом, но нет.
![image](https://user-images.githubusercontent.com/88531962/201965830-a5cba3c8-65c0-49b3-8d67-112e1f367e67.png)

На складе в шкафы к медикам, которых стало в 2 раза больше (зачем если там ничего кроме одежды нет?), положил медицинские пояса, которые уже там лежат раундстартом кодом. Лучше убрать 2 шкафа и поставить полки/столы куда и выложить эти доп пояса. Кринжевые смещения аптечек, которые вылазят на верхний тайл и будут уходить под ноги. Кринжево накиданное говно на полку. И... тулбокс? Надувные стены? И гусев, а где интеркомы то? Ну а еще я не уверен что 3 крио капсулы, находящиеся на расстоянии километра от охладителя, будут реально работать всего на 1 канистре кислорода.
![image](https://user-images.githubusercontent.com/88531962/201968202-40922925-0cc4-4e9c-b1c1-15f3f4d848c8.png)

Это... Ну наверное очень удобно и совсем не тесно
![image](https://user-images.githubusercontent.com/88531962/201968696-6b2a7770-bcf6-44ae-9706-b080d483932d.png)

Я не знаю как это комментировать, это пиздец какой-то. Огромное, кривое пространство, которое скорее всего никогда и никак использоваться не будет. Тут ещё и смещения выключателей света в палатах просто улетные. Передоз ступеньками, при чем кривыми. Ну есть же нормальный спрайт с такой типо кромкой на краю, но нет мы суем миддл_стэйрс. Еще хочу выделить очень щирокие техи хирургии. И... *барабанная дробь*... ни одного интеркома до сих пор!
![image](https://user-images.githubusercontent.com/88531962/201969303-a1c5a998-4eb7-4d17-95ae-2eb943b8aae6.png)

В вирусологии этот шлюз дебильно кривой так и не исправлен.
![image](https://user-images.githubusercontent.com/88531962/201970351-758eadfd-4f58-4d47-b5d9-64d17c8a7025.png)

Хирургии я не буду трогать, ну их нахуй. Скажу только что на окнах висят шаттерсы, а кнопок под них нет, как и интеркомов.
![image](https://user-images.githubusercontent.com/88531962/201970836-4da70daf-aab1-4f38-9554-0dc332ce4bdd.png)

Непонятные разобранные каталки наложенные пирамидкой или что это. Я бы ближайшие к хирургическим шкафы убрал и поставил стульчики для созерцателей.
![image](https://user-images.githubusercontent.com/88531962/201971207-06b427e6-e3d3-44ea-b904-fff4da269228.png)
где интеркомы, гусевски?

Итак, крио. Ну 3 крио это мощно конечно, но я бы оставил лучше 2, а остальные по желанию достраивать хз вообще. Расположены вроде прикольно, расстояния между ними вполне нормально и хватает на первый взгляд. Но меня тут пугает не само крио, а труба к нему.
![image](https://user-images.githubusercontent.com/88531962/201971749-ea1459a4-aac7-46b4-9041-db12ebab36bd.png)
Вот эта труба:
![image](https://user-images.githubusercontent.com/88531962/201972272-29de5ed2-7eaa-46d7-a0b8-3f1d60341cfc.png)
Она идет под окнами раз. Она пробегает через весь мед два. Не ну в игре конечно пох как-то труба не труба, но выглядит согласитесь ультра странно и откровенно плохо. А еще я опять скажу, что скорее всего оно не будет так работать...

Генетика это пиздец и он неисправим. Очень клаустрофобно маленькая клонилка, ну наверное можно смириться, а вот с чем мириться я не хочу, так это с размером генетики. Это пиздец. Сжал аж до слез, шакал ты ебучий. В итоге имеем перегруженные говном столы, смешные мусорки в морг, которые доступнее мусорки, которая ведет в карго и в следствии этого как мне кажется, весь мусор из генетики будет идти в морг, а не в карго. Далее у нас в садике появилась 1 безымянная бебезяна и еще целых 2 дополнительных с именем стенли, юху, целых 3 Стенли. И я бы огородил садик не стеклянными створками, а стенами и шлюзом без стекла, чтоб бедный психолог не имел вида на дна модифиер и не мог слышать че там орут куклы под турретом брейндамагом и прочими веселостями. Настенная машинерия просто отпад жопы. Лампочка на стекле. Аварийки перпендикулярно окну. 
![image](https://user-images.githubusercontent.com/88531962/201973717-c12ce404-2798-4e6c-9e6c-8b480f4ef099.png)

А еще я заметил вдруг ужасное
![image](https://user-images.githubusercontent.com/88531962/201974942-802b448d-5d91-4bd0-81c6-242ab78dbe70.png)
Гусев, я понимаю что ты там типо транс деп, но давай здесь без этого кринжа, его итак тут предостаточно?

Морг вродь норм, но я бы верхний вход левее сместил и зачем тут на полу разметка как будто тут чето опасное. Не лезь тут генокрад? А еще где здесь аир алярм? А интерком? Где интеркомы то блять?
![image](https://user-images.githubusercontent.com/88531962/201976295-c846e831-84da-4d99-885d-af02e814971a.png)

Бля в пизду у меня уже мозг нахуй плавится, но еще чуть-чуть.
В кабинете смо оч смешной папер бин, оч крутая камера в лампе. Просто опиздиневшие смещения кнопок и выключателя света (гусев, тебе места на стенках мало? Зачем ты их лепишь по 3 на стену?) И ты самое важное тут забыл - рекуест консоль на стенку, с которой смо оповещения дает. 
![image](https://user-images.githubusercontent.com/88531962/201976622-00669f8d-ebf7-4fde-987b-c23a36d06484.png)

Огромный коридор без единой пожарной створки. Чуть что разгерма и всем пиздец, и врачам и пациентам.
![image](https://user-images.githubusercontent.com/88531962/201978930-be21ac63-2adc-42d0-a675-4e361f7548cd.png)

Библиотеку и техи я щас оценивать не буду, но на первый взгляд техи выглядят очень широкими и очень пустыми. В техах должны быть проходы 2 тайла шириной, но они должны быть заполнены чем-то, тут же нет литералл [...]

2022-11-15 16:56 UTC, Tap0r commented
Ну и общая логика и компановка это я не знаю бля что. Лучше возьми это все и на другую карту занеси, я так погляжу всяким шизотерическим мазохистам вроде неонбибли такое реально заходит.

2022-11-15 17:04 UTC, DarthSidiousPalpatine commented
Ну кароч примерно с половиной претензий согласен, со второй половиной не согласен, ещё пару-тройку не понял вообще о чём :dovolen:

2022-11-15 17:09 UTC, Tap0r commented
Как апрув снять я передумал

2022-11-15 18:20 UTC, DarthSidiousPalpatine commented
Обновил
![image](https://user-images.githubusercontent.com/21008918/201996120-f914eae6-7861-4984-9e00-ce2f5fe01056.png)

2022-11-18 22:28 UTC, DarthSidiousPalpatine commented
А, да, все твои требования сделал кроме перестановки предметов на столах некоторых.

2022-11-20 12:28 UTC, DarthSidiousPalpatine commented
Давайте в ТМ уже, я же всё пофиксил и всё теперь идеально.

2022-11-23 14:37 UTC, LudwigVonChesterfield commented
ставлю на второй, #10363 на первый

если на втором вдруг окажется больше людей вы знаете что делать

2022-11-23 18:53 UTC, DarthSidiousPalpatine commented
Пофиксил пустую комнатку у сада, неработающий холодильник аптеки, не те мониторы оповещения в медбее, плохое имя весам, убрал возможность крутить весы, добавил банку с дексалином.

2022-11-23 19:04 UTC, DarthSidiousPalpatine commented
Наполнил пустую комнату у библиотекаря.

2022-11-28 15:53 UTC, DarthSidiousPalpatine commented
Смешно, мой ремап оказался единственным
https://www.youtube.com/watch?v=sv3-9QXUtuY

2022-12-02 17:50 UTC, DarthSidiousPalpatine commented
Пофиксил конфликты, обновил до актуалочки с таггерами из грузторга.

Можно снова ТестМерж, Дефора-то больше нет :pepe:

2022-12-25 16:54 UTC, DarthSidiousPalpatine commented
Отставить

2023-01-12 16:11 UTC, DarthSidiousPalpatine commented
На это тоже всем похуй.

2023-01-12 16:11 UTC, closed without merging