Nuke toy emag
TauCetiStation/TauCetiClassic pull request #10459
Opened 2022-12-01 14:04 UTC by Chip11-n

## Описание изменений
Мелкофича. Можно емагнуть игрушку-нюку, что бы она взрывалась в руках как ПДА
## Почему и что этот ПР улучшит
Просто забавно будет дать кому-то в руки взрывающуюся игрушку.
## Авторство

## Чеинжлог

2022-12-01 14:04 UTC, TauKitty commented
###### Changelog status: :radio_button: No changelog

2022-12-01 15:56 UTC, Chip11-n commented
![image](https://user-images.githubusercontent.com/50750952/205099364-20cfba03-a59f-42b0-a8ea-6f06b8ba8acf.png)

2022-12-02 06:00 UTC, LudwigVonChesterfield commented on code/game/objects/items/toys.dm
> +	if (emagged && cooldown < world.time)
можно без лесенки елс ифов
```
/attack_self()
    if (emagged && cooldown < ...)
        ...
        return
        
     if(cooldown < ...)
         return
 
    ...
    ```

2022-12-02 12:38 UTC, Chip11-n commented on code/game/objects/items/toys.dm
> +	if (emagged && cooldown < world.time)
Попробуем так

2022-12-02 16:11 UTC, LudwigVonChesterfield commented on code/game/objects/items/toys.dm
> +	if(cooldown > world.time)
очень хорошо сделал даже лучше чем я предлагал, спасибо

2022-12-02 16:11 UTC, LudwigVonChesterfield commented on code/game/objects/items/toys.dm
> +	spawn(5) //gia said so
если переделаешь слипы и спавны на колбеки вообще цены тебе не будет но я в принципе готов замержить и без рефактора

2022-12-02 16:12 UTC, LudwigVonChesterfield requested changes
поспрашивай в #how-to-code как вместо слипов сделать колбеки

2022-12-02 18:53 UTC, Chip11-n commented on code/game/objects/items/toys.dm
> +	spawn(5) //gia said so
Сделано.
Пол секунды не стал убирать, ибо без этого звук кажется обрезанным

2022-12-02 18:55 UTC, LudwigVonChesterfield approved these changes
норм ПР

2022-12-04 16:54 UTC, merged