Тгуификация GPS, впиндюривание DarkWater'овского GPS трекера в игру.
TauCetiStation/TauCetiClassic pull request #10493
Opened 2022-12-09 19:58 UTC by DarthSidiousPalpatine

## Описание изменений
![image](https://user-images.githubusercontent.com/21008918/206785873-052c7d85-791d-49c7-994d-39d0042b734e.png)
![GIF 09 12 2022 23-27-07](https://user-images.githubusercontent.com/21008918/206785882-a1714820-6e8b-4504-9ea1-bfa0db0b6d65.gif)
(Цвета берутся для каждого вида трекера)

ЖПС. Имеет доп. функции:
1) Показ координат курсора.
2) Запись пути на один из трёх слотов, в каждом по 150 точек. Удаление его.
3) Сохранение текущей позиции на один из трёх слотов. Удаление её.
4) Листание z-координаты.
5) Возможность выключить трекинг, оставив карту с сохранённой точкой на экране.

## Почему и что этот ПР улучшит
ИмМеРсИвНыЙ интерфейс.

## Авторство
AndreyGysev и DarkWater и все все все, кто помогал в дискорде.
## Чеинжлог
 :cl: 
- image: Переделан интерфейс и функционал GPS трекера.

2022-12-09 19:58 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2022-12-10 00:29 UTC, KIBORG04 commented on tgui/packages/tgui/styles/interfaces/GPS.scss
> +.GPS_Monitor {
у scss есть наследование этих классов. УБЕРИ СТОЛЬКО КОПИПАСТЫ ПОЖАЛУЙСТА

2022-12-10 00:29 UTC, KIBORG04 commented on tgui/packages/tgui/styles/interfaces/GPS.scss
> +.GPS_Monitor {
scss так же позволяет переменные делать, всякие динамические фичи, юзай их, чтобы убрать весь ужас

2022-12-10 01:46 UTC, Dominig12 commented
Хочу поинтересоваться, а я не вижу просто чтобы можно было отображать треки других GPS-ов, или я просто чего то не понимаю?

2022-12-10 01:49 UTC, Dominig12 requested changes
Пока такие вот замечания, возможно я не прав но тогда поясни где именно окей?

2022-12-10 01:49 UTC, Dominig12 commented on code/modules/telesci/gps.dm
> +	var/list/track = list(list(), list(), list())
Стоит я думаю сделать функцию по добавлению и удалению трека, чтобы не нужно было вот так хардкодить листы, или функцию по инициализации по количеству треков списка

2022-12-10 01:49 UTC, Dominig12 commented on code/modules/telesci/gps.dm
> +			if(selected_track > 3)
здесь так же хардкот количества треков, как по мне неправильно, лучше вынести в отдельную переменную а потом все инициализировать в отдельной функции

2022-12-10 01:49 UTC, Dominig12 commented on code/modules/telesci/gps.dm
> +	var/list/saved_locations[3]
так же лучше инициализировать с помощью отдельной функции и вынести количество в отдельную переменную

2022-12-10 01:49 UTC, Dominig12 commented on code/modules/telesci/gps.dm
> +			if(selected_track > 3)
либо сделать по количеству треков в списке

2022-12-10 01:54 UTC, Ro2tCrab commented
По поводу дизайна. 
Основной задачей GPS можно считать определение своих координат, верно?
Будет ли проблема определения координат при наличии толпы игроков на одном месте?
Будет ли человеку удобно искать свою метку среди толпы этих точек? А других?

2022-12-10 05:02 UTC, DarthSidiousPalpatine commented
> 

Ну твои координаты зелёные и выше всех других координат. Вроде, заметно когда на одном месте.

2022-12-10 05:15 UTC, DarthSidiousPalpatine commented
> Хочу поинтересоваться, а я не вижу просто чтобы можно было отображать треки других GPS-ов, или я просто чего то не понимаю?

Да, видно только твой трек.

2022-12-10 05:30 UTC, DarthSidiousPalpatine commented
> По поводу дизайна. Основной задачей GPS можно считать определение своих координат, верно? Будет ли проблема определения координат при наличии толпы игроков на одном месте? Будет ли человеку удобно искать свою метку среди толпы этих точек? А других?

![image](https://user-images.githubusercontent.com/21008918/206830950-6c099a1e-63fb-44f6-b229-29310b65bb0d.png)
![image](https://user-images.githubusercontent.com/21008918/206830963-b52e1e79-f744-4f44-adf8-0a5f13eca6b5.png)
![image](https://user-images.githubusercontent.com/21008918/206830984-259c3dd8-2353-46bd-9980-5bd9295a027f.png)
Литералли чем больше на фоне других гпсов тем лучше видно твой)

2022-12-10 06:01 UTC, DarthSidiousPalpatine commented on tgui/packages/tgui/styles/interfaces/GPS.scss
> +.GPS_Monitor {
Исправлено

2022-12-10 07:25 UTC, TauKitty commented
Этот запрос на слияние был упомянут в **Tau Ceti Station Forum**. Там могут быть соответствующие подробности:

https://forum.taucetistation.org/t/gpstracker-otsledite-svoj-put-po-gps/33402/17

2022-12-10 18:17 UTC, KIBORG04 commented on tgui/packages/tgui/styles/interfaces/GPS.scss
> +.GPS_SCI_Main, .GPS_ENG_Main, .GPS_MIN_Main, .GPS_MED_Main, .GPS_COM_Main {
заюзай пж scss фичи:

https://sass-scss.ru/guide/
![image](https://user-images.githubusercontent.com/26389417/206869588-771447b7-277d-4a8d-aebc-d53abbb6a5ba.png)

2022-12-10 18:18 UTC, DarthSidiousPalpatine commented on tgui/packages/tgui/styles/interfaces/GPS.scss
> +.GPS_SCI_Main, .GPS_ENG_Main, .GPS_MIN_Main, .GPS_MED_Main, .GPS_COM_Main {
ВАУ, оки-доки

2022-12-10 18:22 UTC, KIBORG04 commented on tgui/packages/tgui/interfaces/GPS.js
> +            </Box>
Можно цикл???

2022-12-10 18:23 UTC, KIBORG04 commented on tgui/packages/tgui/interfaces/GPS.js
> +              content={<Box className="GPS_Button-Content"><Icon name="arrow-up" color="#cccccc" size="1" /></Box>} />
Баттонов же вроде есть параметр иконки

2022-12-10 18:47 UTC, DarthSidiousPalpatine commented on tgui/packages/tgui/interfaces/GPS.js
> +            </Box>
как

2022-12-10 18:49 UTC, KIBORG04 commented on tgui/packages/tgui/interfaces/GPS.js
> +            </Box>
Сам придумывай, это легко...

2022-12-10 21:02 UTC, DarthSidiousPalpatine commented on tgui/packages/tgui/interfaces/GPS.js
> +            </Box>
хрень какая-то, я хз.

2022-12-11 01:08 UTC, Dominig12 commented on tgui/packages/tgui/interfaces/GPS.js
> +            </Box>
у тебя прослеживается цикл из трех и один лишний последний элемент который ты ставишь вручную
1. цикл из трех (в нем меняются значения top) (0 35 70)
2. Внутри него цикл из трех (в нем меняются значения left) (0 45 90)
Итого 3*3 = 9 значений то есть 9 первых кнопок + 1 кнопка вручную

2022-12-11 07:18 UTC, DarthSidiousPalpatine commented on tgui/packages/tgui/interfaces/GPS.js
> +            </Box>
Ладно, я сделяль

2022-12-13 20:03 UTC, LudwigVonChesterfield commented
я бы всё таки отдельно где-то писал в интерфейсе координаты твоего ГПС-а...

2022-12-14 11:49 UTC, KIBORG04 commented on code/modules/telesci/gps.dm
> +				return
Мб я не прав, но пытаться понять этот капец на листах я не хочу

2022-12-14 11:50 UTC, DarthSidiousPalpatine commented on code/modules/telesci/gps.dm
> +				return
А смысл, мне надо всё передавать во фронтенд где я строю линии.

2022-12-14 11:55 UTC, DarthSidiousPalpatine commented
> я бы всё таки отдельно где-то писал в интерфейсе координаты твоего ГПС-а...

Ну хз, его видно поверх всех других в любых ситуациаях. И он отличается от всех других тем что он зелёный. Вполне легко увидеть.

2022-12-14 11:59 UTC, KIBORG04 commented on code/modules/telesci/gps.dm
> +	if( ((Second["x"]-First["x"]) * (Third["y"] - First["y"])) - ((Second["y"]-First["y"]) * (Third["x"]-First["x"])) == 0)
Сделай без рандомных пробелов и с рандомным их отсутствием пж

2022-12-14 12:04 UTC, KIBORG04 commented on tgui/packages/tgui/interfaces/GPS.js
> +  { id: 1, x: 0, y: 0 },
я не так хотел, но да ладно.. Можно же было просто цикл от 1 до 3 и цикл от 1 до 3. 
```
for i = 1 to 3
    x = 0
    y = 0
    for i = 1 to 3
        <button x={x} y = {y}>
         x+=45
    y+=35
```

2022-12-14 12:05 UTC, KIBORG04 commented on tgui/packages/tgui/interfaces/GPS.js
> +                            <line x1={1.4*track[index-1].x+1} x2={1.4*dot.x+1} y1={1.4*track[index-1].y-19} y2={1.4*dot.y-19} stroke="rgba(255, 255, 255, .5)" />
почему 1,4 и почему отнимает от y 19, а x добавляем 1

2022-12-14 12:06 UTC, KIBORG04 commented on tgui/packages/tgui/interfaces/GPS.js
> +                            <line x1={1.4*track[index-1].x+1} x2={1.4*dot.x+1} y1={1.4*track[index-1].y-19} y2={1.4*dot.y-19} stroke="rgba(255, 255, 255, .5)" />
Стоит вынести 1,4 в виде переменной и заменить все вхождения

2022-12-14 12:07 UTC, DarthSidiousPalpatine commented on tgui/packages/tgui/interfaces/GPS.js
> +                            <line x1={1.4*track[index-1].x+1} x2={1.4*dot.x+1} y1={1.4*track[index-1].y-19} y2={1.4*dot.y-19} stroke="rgba(255, 255, 255, .5)" />
Потому что 1.4 это 357/255

Да, вынесу

2022-12-14 12:07 UTC, DarthSidiousPalpatine commented on tgui/packages/tgui/interfaces/GPS.js
> +                            <line x1={1.4*track[index-1].x+1} x2={1.4*dot.x+1} y1={1.4*track[index-1].y-19} y2={1.4*dot.y-19} stroke="rgba(255, 255, 255, .5)" />
ПРо добавление х и у - это просто подгонка. Я хз почему именно, но не ровно ставятся точки и пр. Потому я подгоняю все под бокс монитора.

2022-12-14 12:08 UTC, KIBORG04 commented on tgui/packages/tgui/interfaces/GPS.js
> +                            <line x1={1.4*track[index-1].x+1} x2={1.4*dot.x+1} y1={1.4*track[index-1].y-19} y2={1.4*dot.y-19} stroke="rgba(255, 255, 255, .5)" />
а что такое 327

2022-12-14 12:11 UTC, KIBORG04 commented on tgui/packages/tgui/interfaces/GPS.js
> +                            <line x1={1.4*track[index-1].x+1} x2={1.4*dot.x+1} y1={1.4*track[index-1].y-19} y2={1.4*dot.y-19} stroke="rgba(255, 255, 255, .5)" />
А смещение мб потому что у тебя здесь элемент GPS_TrackLine имеет `position: absolute;`, что как бы координаты самого жипиеса, а не релятивные тут

2022-12-14 12:13 UTC, DarthSidiousPalpatine commented on tgui/packages/tgui/styles/interfaces/GPS.scss
> +	position: absolute;
абсолютная относительно Monitor бокса экрана. Это норм.

Относительно мне не надо потому что тогда они будут скапливаться и друг друга двигать.

2022-12-14 12:15 UTC, KIBORG04 commented on tgui/packages/tgui/styles/interfaces/GPS.scss
> +	position: absolute;
Скилл максимальный скилл ишуй.

2022-12-14 12:16 UTC, DarthSidiousPalpatine commented on tgui/packages/tgui/interfaces/GPS.js
> +                            <line x1={1.4*track[index-1].x+1} x2={1.4*dot.x+1} y1={1.4*track[index-1].y-19} y2={1.4*dot.y-19} stroke="rgba(255, 255, 255, .5)" />
нет, это координаты бокса, пчел.

2022-12-14 12:18 UTC, KIBORG04 commented on tgui/packages/tgui/interfaces/GPS.js
> +                            <line x1={1.4*track[index-1].x+1} x2={1.4*dot.x+1} y1={1.4*track[index-1].y-19} y2={1.4*dot.y-19} stroke="rgba(255, 255, 255, .5)" />
это свг

2022-12-28 14:55 UTC, DarthSidiousPalpatine commented
Прощай и ты

2023-07-24 05:21 UTC, closed without merging