Убирает возможность скрелла брать синдром туретта
TauCetiStation/TauCetiClassic pull request #10513
Opened 2022-12-15 11:30 UTC by Mercurialaste

## Описание изменений
Скреллы больше не смогут брать синдром туретта в лодауте.
## Почему и что этот ПР улучшит
Скреллы не будут материться из-за механа.
## Авторство
я
## Чеинжлог
:cl:
- tweak: Скреллы больше не могут брать синдром туретта как особенность.

2022-12-15 11:30 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2022-12-15 12:30 UTC, Enerty commented
Имеет место быть, я не вижу причин брать синдром туретта на скреллов, кроме как ради высмеивания, провокации и тому подобного

2022-12-15 12:31 UTC, KIBORG04 commented on code/datums/traits/negative.dm
> +	incompatible_species = list(SKRELL)
а типа че, только скреллы не матерятся?

2022-12-15 13:45 UTC, Mercurialaste commented on code/datums/traits/negative.dm
> +	incompatible_species = list(SKRELL)
Ну, настолько критично — да. 
В остальном, даже таяры/спу/унатхи/дионы/воксы могут использовать маты. На сколько я знаю, воксы на своем языке только не матерятся. А у тех же дион, частично их личность может зависеть от того, какой кровью поили их головную нимфу.
Унатхи и таяры — на сколько я знаю, матерятся без особых ограничений.

2022-12-21 16:19 UTC, Mercurialaste commented
а нет, херня.

2022-12-29 20:28 UTC, Mercurialaste commented
?

2022-12-29 20:57 UTC, KIBORG04 commented on code/modules/mob/living/carbon/human/life.dm
> +var/global/list/tourette_bad_words = list("ГОВНО","ЖОПА","ЕБАЛ","БЛЯДИНА","ХУЕСОС","СУКА","ЗАЛУПА",
сделай через ассоциативные листы где ключ это раса, а набор слов это лист

2022-12-29 20:58 UTC, KIBORG04 requested changes
жду

2022-12-30 06:50 UTC, Mercurialaste commented
> жду

Вродь все.

2022-12-30 12:33 UTC, KIBORG04 commented on code/modules/mob/mob_helpers.dm
> +		message_list[insertpos] = pick(tourette_bad_words[species])
Будет рантам, если расы не будет в tourette_bad_words. Сделай минимальную валидацию

2022-12-30 12:34 UTC, KIBORG04 commented on code/modules/mob/living/carbon/human/life.dm
> +						say(pick(tourette_bad_words[get_species()]))
Будет рантам, если расы не будет в tourette_bad_words. Сделай минимальную валидацию

2022-12-30 12:34 UTC, KIBORG04 commented on code/modules/mob/mob_helpers.dm
> +		message_list[insertpos] = pick(tourette_bad_words[species])
Рантайм будет у pick *

2022-12-30 15:40 UTC, Mercurialaste commented
Сделал

2022-12-30 16:37 UTC, KIBORG04 commented on code/modules/mob/mob_helpers.dm
> +		return message
> оно теперь просто удаляет сообщение, а не выводит его.

Все норм должно быть

2022-12-30 16:39 UTC, Mercurialaste commented on code/modules/mob/mob_helpers.dm
> +		return message
Да, я там просто пустой ретурн по началу прост сделал.

2022-12-30 16:39 UTC, KIBORG04 approved these changes

2023-01-01 22:26 UTC, Mercurialaste commented
?

2023-01-04 18:28 UTC, merged