Возможный фикс иконок имплантов у скелета
TauCetiStation/TauCetiClassic pull request #10550
Opened 2022-12-23 22:42 UTC by Mercurialaste

## Описание изменений
Багфикс?
Не могу проверить тк все способы обращения в скелета требуют двух игроков.
## Почему и что этот ПР улучшит
closes https://github.com/TauCetiStation/TauCetiClassic/issues/10515https://github.com/TauCetiStation/TauCetiClassic/issues/10515
## Авторство
я
## Чеинжлог
- bugfix: Теперь при скелетофикации, у человека пропадает худ имплантов.

2022-12-23 22:42 UTC, TauKitty commented
###### Changelog status: :radio_button: No changelog

2022-12-23 23:11 UTC, Mercurialaste commented
Осталось понять, что от меня гит хочет...

2022-12-24 18:28 UTC, KIBORG04 requested changes
послушай реминд ми и не делай так ка сейчас

2022-12-24 19:46 UTC, Mercurialaste commented
> 

Я уже проверил через VV, удаляя из contetns имплант и обновляя иконки через regenerate_icons().

2022-12-24 19:46 UTC, Mercurialaste commented
> послушай реминд ми и не делай так ка сейчас

?

2022-12-24 19:48 UTC, KIBORG04 commented
> Я уже проверил через VV, удаляя из contetns имплант и обновляя иконки через regenerate_icons().

> Теперь при скелетофикации, у человека пропадает худ имплантов.

Это две РАЗНЫЕ штуки. У тебя из-за говно-способа даже тесты не проходят. Ты должен вызывать обновление худ-иконки там, где код убирает имплант

2022-12-25 01:37 UTC, Mercurialaste commented
На сколько я понял, просматривая код, у скелетов через ритуал ничего не снимается, перепроверю, когда разберусь с тем, как зайти через акаунт гостя на локальный сервер.

2022-12-28 19:21 UTC, KIBORG04 commented
должно работать

2022-12-28 19:21 UTC, merged