большие вещи в руках снова замедляют
TauCetiStation/TauCetiClassic pull request #10568
Opened 2022-12-30 09:48 UTC by simb11

## Описание изменений
большие вещи в руках замедляют как раньше 
## Почему и что этот ПР улучшит
эксперимент оказался очевидно неудачным
перестрелки превратились в какую-то аркаду, где персы не прячутся от пуль в укрытиях, а удивительно уворачиваются от них в открытом поле. и вообще всякие черти что спокойно бегают с пулемётами, огромными щитами и противотанковыми ружьями портят баланс и ломают погружение
## Авторство

## Чеинжлог
:cl: Simbaka
- add: Большие предметы в руках замедляют персонажей.

2022-12-30 09:48 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2022-12-30 10:02 UTC, Deahaka commented
Будет смешно, если следующий ПР добавит аналог гипера, который это замедление будет убирать.

2022-12-30 10:18 UTC, volas commented on code/modules/mob/living/carbon/human/human_movement.dm
> +				tally += 0.25 * (I.w_class - 2) // (3 = 0.25) || (4 = 0.5) || (5 = 0.75)
Напомню, в pull_debuff всё еще нету штрафов для большинства вещей. И есть еще сумки и прочее.

Для простоты системы я бы предложил замедлять за предметы от SIZE_NORMAL, эти предметы не влезут в сумки и так можно будет обойти проблему с разным механом.

В pull_debuff добавить такое же замедление для предметов, как и тут, но раза в два больше.

Останется абуз с пуллом ящиков и шкафов, можно тоже что нибудь решить или забить, так как не сильно удобный.

2022-12-30 14:21 UTC, simb11 commented on code/modules/mob/living/carbon/human/human_movement.dm
> +				tally += 0.25 * (I.w_class - 2) // (3 = 0.25) || (4 = 0.5) || (5 = 0.75)
сделал

2022-12-30 15:49 UTC, Fluffy-510 commented
А световой и двойной световой меч будут замедлять?
Они ведь по сути не меняют свой вес, как предмет, а получают световое(плазменное?) удлинение .
А вообще в фильмах джедаи бегали с мечами быстро, теперь все с мечами будут медленными?

2022-12-30 15:56 UTC, simb11 commented
да будут замедлять

2022-12-30 16:08 UTC, TheLone1y commented
Норм хорошая затея нерфать всегда балансно, а световые мечи вы можете быстро включать-выключать.

2022-12-30 16:38 UTC, KIBORG04 commented
В чем различие с ситуаций ДО твоего выпила замедлений?

2022-12-30 17:08 UTC, simb11 commented
разница заключается в том что можно спокойно бегать с большими вещами в руках, это выливается в то что игроки могут одновременно стрейфить и стрелять не теряя мобильность. это очень сильно влияет на перестрелки.

2022-12-30 17:16 UTC, KIBORG04 commented
Я про другое. Ты сам выпиливал замедления и сам сделал такую ситуацию. И я спрашиваю, сильные ли различия ДО эксперимента и в этом ПРе ПОСЛЕ?

2022-12-30 17:20 UTC, simb11 commented
написал же эксперимент хуйня и не удался, единственное что изменилось это мои взгляды на билд и сейчас я вижу что отсутствие замедления это ненужное ускорение геймплея которое превращает более-менее реалистичные перестрелки в херню квейкоподобную

2022-12-30 17:24 UTC, KIBORG04 commented
То есть реверт без каких-либо изменений?

2022-12-30 17:26 UTC, simb11 commented
ага, только ещё добавил замедление от пулла по просьбе Уолеса

2022-12-30 17:41 UTC, Tap0r commented
Замедление от пулла имхо не надо. Это и логично, т.к по полу волочить легче, чем в руках нести, и вполне балансно, т.к оно не может быть мгновенно использовано, поднять ее кто угодно другой может, в принципе потерять так шмотку куда проще.

2022-12-30 18:35 UTC, volas commented on code/modules/mob/living/carbon/human/human_movement.dm
> +				tally += 0.25 * (I.w_class - 2) // (3 = 0.25) || (4 = 0.5) || (5 = 0.75)
Всё еще ``w_class >= SIZE_SMALL``.

Я думаю, ``SIZE_NORMAL`` будет логичнее. SIZE_SMALL в любой момент можно запихать в сумку, где они тут же перестанут влиять на ускорение. Для максималистов это может закончится лишними телодвижениями запихал-достал.

``SIZE_NORMAL`` и выше это как раз указанные тобой вещи типо щитов и пулеметов, которые не лезут в сумку, и за мобильность с которыми игрокам нужно торговаться слотом спины. Им замедление напрашивается, в отличии от ``SIZE_SMALL``.

2022-12-30 18:37 UTC, volas commented
> Замедление от пулла имхо не надо.

пулл это как неожиданная независимая третья рука или хвост, уже само по себе не слишком логично.

2022-12-30 18:38 UTC, Deahaka commented on code/modules/mob/living/carbon/human/human_movement.dm
> +				tally += 0.25 * (I.w_class - 2) // (3 = 0.25) || (4 = 0.5) || (5 = 0.75)
Ну не слотом спины, а слотом в броне или пояса. Еденицы носят пушки на спине, потому что остальные вещи, которые пригодятся вне боя некуда запихать.

2022-12-30 18:53 UTC, MrWestnow commented
Да да да и ещё раз да

2022-12-30 19:33 UTC, simb11 commented on code/modules/mob/living/carbon/human/human_movement.dm
> +				tally += 0.25 * (I.w_class - 2) // (3 = 0.25) || (4 = 0.5) || (5 = 0.75)
сделал сайз нормал

2022-12-30 20:00 UTC, volas approved these changes

2022-12-31 16:10 UTC, LoTaRk-FroG commented
Я бы ввёл отдельную переменную на вес. Очевидно, что пулемёт ПИЛА будет тяжелее деревянного топора, но занимать сколько же места. А так милишники станут намного слабее любого стрелка. С мечами вообще кринж, поверфист станет намного более лучшим вариантом. А, ну ещё складные объекты в сложенном и разложенном состоянии по весу не отличаются.

2023-01-01 16:04 UTC, TryXAH commented
> *выпиливаем гиперцин, аргументируя убиранием замедления*
> *возвращаем замедление обратно*
> yoba.png
![изображение](https://user-images.githubusercontent.com/104844287/210177234-073070bc-ffe6-4800-a707-5bd4976ecfea.png)

2023-01-02 04:46 UTC, WatlerJe commented
Bruh. Снова ящуры станут неиграбльными, благодаря расовому дебафу на скорость.

2023-01-02 09:05 UTC, Ro2tCrab commented
Хоть кто то подумал о ВеСеЛьЕ и удовольствии самих игроков? Не?
Лично я не вижу баланса, но вижу пачку бесполезных изменений.

2023-01-02 09:36 UTC, simb11 commented
я здесь вообще ничего не писал про баланс
а если игрокам не нравятся изменения это не значит что они плохие

2023-01-02 09:41 UTC, TheLone1y commented
УРА ДА ЕБАНИ ЕГО ТОПОРОМ НА ЗАМЕДЛЕНИИ 0.1 ДАВАЙ СУКА ФАН ДАААА УРАААА ВЕСЕЛУХА УРА ЭТО НЕ ПРО БАЛАНС НАХУЙ УРА ВЕСЕЛЬЕ ФАН ВЕСЕЛЬЕ ФАН КСКА ВЕСЕЛИМСЯ МИЛИ ТЫК-ТЫК-ТЫК ХАХАХА ЗАТЫКАЛ МИНУС ТРИ ИЗИ БОЖЖЖ У ТЕБЯ ММР МЕНЬШЕ ЧЕМ У МЕНЯ +1СМ ХУЯ АХАХХАХАХАА СОСНИ АНРОБАСТИЩЕ ВПЕРЕД ВЕСЕЛИТСЯ.

2023-01-02 10:08 UTC, Ro2tCrab commented
> я здесь вообще ничего не писал про баланс а если игрокам не нравятся изменения это не значит что они плохие
Так же ты.
> эксперимент оказался очевидно неудачным
перестрелки превратились в какую-то аркаду, где персы не прячутся от пуль в укрытиях, а удивительно уворачиваются от них в открытом поле. и вообще всякие черти что спокойно бегают с пулемётами, огромными щитами и противотанковыми ружьями портят *баланс* и ломают погружение

2023-01-02 10:09 UTC, Ro2tCrab commented
> УРА ДА ЕБАНИ ЕГО ТОПОРОМ НА ЗАМЕДЛЕНИИ 0.1 ДАВАЙ СУКА ФАН ДАААА УРАААА ВЕСЕЛУХА УРА ЭТО НЕ ПРО БАЛАНС НАХУЙ УРА ВЕСЕЛЬЕ ФАН ВЕСЕЛЬЕ ФАН КСКА ВЕСЕЛИМСЯ МИЛИ ТЫК-ТЫК-ТЫК ХАХАХА ЗАТЫКАЛ МИНУС ТРИ ИЗИ БОЖЖЖ У ТЕБЯ ММР МЕНЬШЕ ЧЕМ У МЕНЯ +1СМ ХУЯ АХАХХАХАХАА СОСНИ АНРОБАСТИЩЕ ВПЕРЕД ВЕСЕЛИТСЯ.

Cringe

2023-01-02 12:24 UTC, simb11 commented
световые мечи и щиты теперь не замедляют
двойной меч немного замедляет потому что без замедления он был бы слишком уж мощным

2023-01-02 16:13 UTC, Ro2tCrab commented
> световые мечи и щиты теперь не замедляют двойной меч немного замедляет потому что без замедления он был бы слишком уж мощным

А теперь скажи нам..
Почему снаряжение за 14 ТК не может быть сильным?

2023-01-02 16:24 UTC, simb11 commented
потому что потому, оно и сейчас является невероятно мощным, а ты представь что будет, когда почти всё оружие будет замедлять персонажа, а этот ножик с 70 урона и шансом блока в 60% нет

2023-01-03 11:37 UTC, Ro2tCrab commented
> потому что потому, оно и сейчас является невероятно мощным, а ты представь что будет, когда почти всё оружие будет замедлять персонажа, а этот ножик с 70 урона и шансом блока в 60% нет

Вот только смысла в данном нерфе нет для этого меча. Что эио поменяет? Врят ли это сделает Нюккера под Аддреналим медленным или тритору запретит убивать одним тыком. 
У последнего все ещё есть микролазеры, боевой гипоспрей и поверфист. 

Всё это реально имеет смысл на фоне **всего этого?**

2023-01-03 13:40 UTC, TheLone1y commented
Ну перестань ты из мелочей доить конфликт, поверфист понерфили, остальное стантувин и чем ты этого хочешь добится? Не трогать даблесворд пока не потрогают остальное? Мы так с мертвой точки не сдвинемся…

2023-01-03 16:23 UTC, volas commented on code/__DEFINES/flags.dm
> +#define HEAR_TA_SAY            (1<<23)   // temp for talking_atoms
лучше не двигай флаги, если не хочешь заняться #10023

можешь его разместить во flags_2, эти флаги под комментарием
> /* Secondary atom flags, for the flags_2 var, denoted with a _2 */

ниже.

2023-01-03 16:28 UTC, volas requested changes

2023-01-03 16:28 UTC, volas commented on code/game/objects/items/weapons/swords_axes_etc.dm
> +	w_class = SIZE_SMALL
можно не менять вовсе

2023-01-03 16:28 UTC, volas commented on code/game/objects/items/weapons/swords_axes_etc.dm
> +	flags = NOBLOODY | CANT_BE_INSERTED
стоит переключать отдельный флаг, а не обновлять всю переменную, посмотри в бинарные операции бьенда

2023-01-03 16:28 UTC, volas commented on code/game/objects/items/weapons/storage/storage.dm
> +			to_chat(usr, "<span class='notice'>[src] cannot hold [W].</span>")
название довольно абстрактное, в случае с мечем наверно лучше было бы его просто автоматом выключать в сумке. И юзерфрендли, и понятно

2023-01-03 16:29 UTC, volas commented
> световые мечи и щиты теперь не замедляют

я понимаю мечи, но щиты? если щиты не будут замедлять, то кто и какой в этом смысл вообще

2023-01-03 16:39 UTC, TryXAH commented
> если щиты не будут замедлять, то кто и какой в этом смысл вообще

Энергетические щиты и не состоят толком из ничего, кроме как основания ручки. Они должны быть легкими по своей сути, это же громадные металлические оборонительные щиты, а легкие наступательные

2023-01-03 17:29 UTC, Ro2tCrab commented
> Ну перестань ты из мелочей доить конфликт, поверфист понерфили, остальное стантувин и чем ты этого хочешь добится? Не трогать даблесворд пока не потрогают остальное? Мы так с мертвой точки не сдвинемся…

Вот только мы уже прыгаем между двумя мёртвыми точками и считаем это "балансом".
Ревёрт изменений и их обратный мёрж - самая стандартная ситуация в нашем ГитХабе.

2023-01-03 17:49 UTC, TheLone1y commented
Удалили гипер, удалили замедление, вернули замедление, а где мой гипер...
Да и пусть в целом, мержил Симбака, понял что сделал неправильно, откатывает с небольшими правками.
P.S. Я балансдеп мне виднее

2023-01-05 20:12 UTC, simb11 commented on code/game/objects/items/weapons/storage/storage.dm
> +			to_chat(usr, "<span class='notice'>[src] cannot hold [W].</span>")
я без понятия как это сделать, и через аттак бай пытался, и через код сумки - никак не получается. :pensive:

2023-01-11 20:10 UTC, AndroBetel commented
где мерж-то

2023-01-12 19:39 UTC, KIBORG04 commented on code/game/objects/items/weapons/swords_axes_etc.dm
> +        attack_self(usr)
Пробелы

2023-01-12 19:39 UTC, KIBORG04 commented on code/game/objects/items/weapons/shields.dm
> +        attack_self(usr)
Пробелы

2023-01-19 08:13 UTC, Pimap3 commented
Баланс говна

2023-01-25 23:00 UTC, AndroBetel commented
надо надо мерж

2023-01-26 06:37 UTC, Ro2tCrab commented
> Удалили гипер, удалили замедление, вернули замедление, а где мой гипер...
> Да и пусть в целом, мержил Симбака, понял что сделал неправильно, откатывает с небольшими правками.
> P.S. Я балансдеп мне виднее

И ни слова мнения или аргументов против.
Т.к нормальных аргументов за мёрж нет и соотношение голосов близко к 5:5...

То и мёржить это хорошим назвать нельзя.

Половина игроков все ещё игроки.
Если и делать изменения, то только по конкретным темам.

Чаще всего жалобы на двойной меч.
Просто подправьте урон.
Серьёзно.
Скиллы мили дают буст в 40% урона (?).
Хотя.. Вот за **ЭТО** игроки точно начнут кидать в меня палки.

...но меч и так был хорош со своми 45 урона. 70 урона уже **Cringe**

2023-01-26 07:35 UTC, simb11 commented
Не мержьте пж пока что, мне ещё надо подправить размеры некоторых милишек

2023-02-07 20:31 UTC, LudwigVonChesterfield commented
Волас одобрил го ТМ если люди не заметят замержим

2023-02-12 19:42 UTC, KIBORG04 commented
даже я не заметил, что это попало в тм

2023-02-15 08:39 UTC, volas commented on code/__DEFINES/flags.dm
>  /* Secondary atom flags, for the flags_2 var, denoted with a _2 */
тебе нужно использовать flags_2 вместо flags

система та же, просто другой набор флагов что бы они не пересекались

2023-02-18 13:04 UTC, volas commented on code/game/objects/items/weapons/twohanded.dm
> +	TCB.on_unwield = CALLBACK(src, .proc/on_unwield)
я не понимаю, для чего это? Как и у копья.

2023-02-18 17:36 UTC, simb11 commented on code/game/objects/items/weapons/twohanded.dm
> +	TCB.on_unwield = CALLBACK(src, .proc/on_unwield)
Чтобы размер предмета менялся при взятии его в 2 руки. Сделал именно таким образом, потому что также само была реализована смена размера у двойного есворда.

2023-02-18 21:58 UTC, Sakuya-Izayoi commented on code/game/objects/items/weapons/twohanded.dm
> +	TCB.on_unwield = CALLBACK(src, .proc/on_unwield)
ну, даблесворд увеличивается в размерах по факту, а копье нет

2023-02-18 22:21 UTC, LudwigVonChesterfield commented on code/game/objects/items/weapons/twohanded.dm
> +	TCB.on_unwield = CALLBACK(src, .proc/on_unwield)
ну это же повышает скилл использования вещи, теперь надо подбегать в одной руке - хватать в две - и потом обратно в одну, прикольно же.

2023-02-19 20:51 UTC, Deahaka commented
Вот сейчас почувствовал. Что угодно потащишь, особенно лежачего чела - замедло внушительное. Вроде пока не помешало что-либо сделать, но будем смотреть

2023-02-20 20:47 UTC, LudwigVonChesterfield approved these changes
натестились думаю

2023-02-22 07:03 UTC, volas commented on code/game/objects/items/weapons/twohanded.dm
> +	TCB.on_unwield = CALLBACK(src, .proc/on_unwield)
> Чтобы размер предмета менялся при взятии его в 2 руки.

это как-то костыльно и не понятно, ты скорее всего можешь в самом count_pull_debuff проверять, держишь ли ты предмет в двух руках.

2023-02-22 12:48 UTC, simb11 commented on code/game/objects/items/weapons/twohanded.dm
> +	TCB.on_unwield = CALLBACK(src, .proc/on_unwield)
перенёс

2023-02-22 15:20 UTC, volas commented on code/modules/mob/living/carbon/human/human_movement.dm
> +				tally += 0.25
```suggestion
			if(I && !(I.flags & ABSTRACT) && I.w_class >= SIZE_NORMAL)
				tally += 0.25 * (I.w_class - 2) // (3 = 0.25) || (4 = 0.5) || (5 = 0.75)
				if(HAS_TRAIT(I, TRAIT_DOUBLE_WIELDED))
					tally += 0.25
```

2023-02-22 15:34 UTC, simb11 commented on code/modules/mob/living/carbon/human/human_movement.dm
> +				tally += 0.25
оно не будет работать ибо у всех 2хенд вещей маленький размер

2023-02-22 15:40 UTC, volas commented on code/modules/mob/living/carbon/human/human_movement.dm
> +				tally += 0.25
тогда
```suggestion
			if(I && !(I.flags & ABSTRACT))
				if(I.w_class >= SIZE_NORMAL)
					tally += 0.25 * (I.w_class - 2) // (3 = 0.25) || (4 = 0.5) || (5 = 0.75)
				if(HAS_TRAIT(I, TRAIT_DOUBLE_WIELDED))
					tally += 0.25
```

2023-02-23 07:21 UTC, volas commented on code/game/objects/items/weapons/twohanded.dm
> +
```suggestion
```

2023-02-23 07:27 UTC, volas commented on code/game/objects/items/weapons/shields.dm
> +
```suggestion
```

2023-02-23 07:30 UTC, volas commented
Баланс, замечания учтены, баги поправлены, так что мержу. 

Идея замедления ок, конкретные значения еще открыты для обсуждения в будущем.

2023-02-23 07:30 UTC, merged