Стена щитов. Нереальный баф командной работы
TauCetiStation/TauCetiClassic pull request #10564
Opened 2022-12-29 15:55 UTC by Deahaka

## Описание изменений
Адаптация механики описанной на вики ЛайфВеба. Держа щит в руке (если он раскладной - активируйте), кликните по нему альт-кликом и войдите в защитную стойку. Ваша скорость понижается, однако, если рядом с вами кто-то также встанет в стойку - сработает эффект "Стена Щитов". За каждого, находящегося рядом человека, держащего щит в том же направлении, что и вы, увеличивается шанс заблокировать удар. Чем больше людей - тем выше шанс, ограничения нет и по идее быть не должно. Отключено для щита генокрада и культа потому что они итак имба, куда ещё бафать. Круто должно сочетаться с самодельными щитами у революционеров и противо-бунтовыми щитами СБ.
## Почему и что этот ПР улучшит
Увеличение пользы командной работы перед одиночными побегушками. Люди, собравшись вместе, набрав щитов, теперь с меньшей вероятностью пососут. Нерф всех антагов, особенно завязанных на "выстрелил, попал, победил".
## Авторство

## Чеинжлог
:cl: Deahaka
- add[link]: Щитам добавлена возможность увеличивать свою эффективность за счёт построения линии обороны. Активация бонуса на Alt + Click.

2022-12-29 15:55 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2022-12-29 16:01 UTC, Mercurialaste commented
Мммм... Гробики...

2022-12-29 16:03 UTC, DarthSidiousPalpatine commented
Афигенная стена щитов когда щиты позади тебя, кста. А по-другому и не сделать, кста, так что мда, кста.

2022-12-29 16:05 UTC, Deahaka commented
> Афигенная стена щитов когда щиты позади тебя, например, стоят, кста. А по-другому кроме проверки по-кругу и не сделать, кста, так что мда, кста.

Ты чё про римскую фалангу не читал, неуч?

2022-12-29 16:06 UTC, DarthSidiousPalpatine commented
> > Афигенная стена щитов когда щиты позади тебя, например, стоят, кста. А по-другому кроме проверки по-кругу и не сделать, кста, так что мда, кста.
> 
> Ты чё про римскую фалангу не читал, неуч?

Долбоёб? Ты стоишь спереди один и держишь щит. Позади тебя 3 челика стоят стенкой и держат щиты.
Каким хуем они тебе помогут, блять, долбоёб.

2022-12-29 16:08 UTC, Mercurialaste commented
> > > Афигенная стена щитов когда щиты позади тебя, например, стоят, кста. А по-другому кроме проверки по-кругу и не сделать, кста, так что мда, кста.
> > 
> > 
> > Ты чё про римскую фалангу не читал, неуч?
> 
> Каким хуем они тебе помогут, блять, долбоёб.

Морально

2022-12-29 17:50 UTC, KIBORG04 commented on code/game/atoms.dm
> +		SEND_SIGNAL(src, COMSIG_ATOM_CHANGE_DIR, dir, src)
ГЕНИАЛЬНО

2022-12-29 17:50 UTC, KIBORG04 commented on code/game/atoms_movable.dm
> +		SEND_SIGNAL(src, COMSIG_ATOM_CHANGE_DIR, dir, src)
ГЕНИАЛЬНО

2022-12-29 17:50 UTC, KIBORG04 commented on code/game/atoms.dm
> +		SEND_SIGNAL(src, COMSIG_ATOM_CHANGE_DIR, dir, src)
зачем ты вообще его добавил я не вижу причин

2022-12-29 17:51 UTC, KIBORG04 commented on code/game/gamemodes/modes_gameplays/changeling/powers/mutations.dm
> +	return
не нужный ретурн

2022-12-29 17:51 UTC, KIBORG04 commented on code/game/gamemodes/modes_gameplays/cult/cult_items.dm
> +	return
не нужный ретурн

2022-12-29 17:51 UTC, KIBORG04 commented on code/game/objects/items/weapons/shields.dm
> +/obj/item/weapon/shield/proc/user_moved(dir, user)
че то мне подсказывает ты это не тестил

2022-12-29 17:53 UTC, KIBORG04 commented on code/game/objects/items/weapons/shields.dm
> +	*/
че за дебильный коммент

2022-12-29 17:55 UTC, KIBORG04 commented on code/game/objects/items.dm
> +/obj/item/proc/Get_shield_chance(mob/user = null)
зачем ты везде пишешь = null, оно не имеет смысла??

2022-12-29 17:56 UTC, KIBORG04 commented on code/game/objects/items/weapons/shields.dm
> +			continue
Кринж, что оно проверяет только поворот, а не расположение в пространстве. Гисев базу написал.

2022-12-29 19:09 UTC, LudwigVonChesterfield commented
чтобы эта фича была крутой надо ещё добавить возможность лочить направление при ходьбе аки стрейфить

2022-12-29 19:12 UTC, AndroBetel commented
> А по-другому кроме проверки по-кругу и не сделать, кста, так что мда, кста.

можно же от дира гет степами проверить

2022-12-30 04:20 UTC, DarthSidiousPalpatine commented
> чтобы эта фича была крутой надо ещё добавить возможность лочить направление при ходьбе аки стрейфить

Эта фича будет крутой если пиксель мувмент, чтобы при ходьбе главного все вокруг видели что он начал двигаться и следовали за ним, сохраняя своё положение в примерно одном блоке, чтобы сохранить стену щитов.

2022-12-30 04:21 UTC, DarthSidiousPalpatine commented
> > А по-другому кроме проверки по-кругу и не сделать, кста, так что мда, кста.
> 
> можно же от дира гет степами проверить

Если проверять слева-справа, то стена щитов будет крутой когда вы стоите. Один шаг и стена ломается. Смысл стены щитов ИРЛ, допустим - в том чтобы давить, медленно продвигаясь, всяких челиксов, протестующих, допустим. А у нас будет смысл в том чтобы стоять :/

2022-12-30 04:39 UTC, Deahaka commented
Пофиксил всё о чём написали.

2022-12-30 12:25 UTC, KIBORG04 commented on code/game/objects/items/weapons/shields.dm
> +/obj/item/weapon/shield/proc/user_moved(dir, user)
все еще не тестил. У тебя тут dir будет не диром, а ссылкой на юзера

2022-12-30 12:29 UTC, KIBORG04 commented on code/game/objects/items/weapons/shields.dm
> +		var/turf/no_perpendicular_back = get_step(user_turf, turn(saved_dir, 180))
Я не уверен что нужно считать людей, которые стоят по диагонали. Ты можешь весь цикл убрать и просто сделать два гет_степа.

get_step(turf, turn(saved_dir, 90))
get_step(turf, turn(saved_dir, -90))

Типа так. И имея хотя бы одного чела, там шанс на блок уже почти 100

2022-12-30 13:13 UTC, Ro2tCrab commented
Звучит круто.
На практике круто.
Одна проблема - увидеть эффект от этого **глазами** невозможно. Даже начертить одну красную черту перед СБ было бы достаточно что-бы **понять реальное наличие стены щита.**

2022-12-30 14:27 UTC, Deahaka commented on code/game/objects/items/weapons/shields.dm
> +		var/turf/no_perpendicular_back = get_step(user_turf, turn(saved_dir, 180))
Не, не, смысл в том, чтобы они могли наступать медленно же. Гисев базу написал, что если считать только челов в перпендикуляре, то это получится говно, где ты должен стоять.

2022-12-30 14:37 UTC, KIBORG04 commented on code/game/objects/items/weapons/shields.dm
> +		var/turf/no_perpendicular_back = get_step(user_turf, turn(saved_dir, 180))
я тоже самое написал, тебе никто не запрещает идти медленно и одновременно..

2022-12-30 14:41 UTC, Deahaka commented on code/game/objects/items/weapons/shields.dm
> +		var/turf/no_perpendicular_back = get_step(user_turf, turn(saved_dir, 180))
Запрещает. Считается в момент нанесения урона турфы. Рядом с тобой челы нажали чуть раньше чем ты - у тебя 0 бафа = сосать

2022-12-30 14:44 UTC, KIBORG04 commented on code/game/objects/items/weapons/shields.dm
> +		var/turf/no_perpendicular_back = get_step(user_turf, turn(saved_dir, 180))
Будут идти медленно шагами, не будут лишаться баффа

2022-12-30 14:48 UTC, Deahaka commented on code/game/objects/items/weapons/shields.dm
> +		var/turf/no_perpendicular_back = get_step(user_turf, turn(saved_dir, 180))
XD Будут. Блин киборг чё ты в залупу лезешь, было и без этих гетстепов нормально и по механу и по логике. Ты хочешь сделать из фичи хуйню никому не нужную

2022-12-30 14:48 UTC, Deahaka commented on code/game/objects/items/weapons/shields.dm
> +/obj/item/weapon/shield/proc/user_moved(dir, user)
я делал ту чат, там всё нормально было... ну щас ещё раз потесчу...

2022-12-30 14:49 UTC, KIBORG04 commented on code/game/objects/items/weapons/shields.dm
> +		var/turf/no_perpendicular_back = get_step(user_turf, turn(saved_dir, 180))
фича и так `хуйню никому не нужную`

2022-12-30 14:50 UTC, Deahaka commented on code/game/objects/items/weapons/shields.dm
> +		var/turf/no_perpendicular_back = get_step(user_turf, turn(saved_dir, 180))
Если что-то даёт имба-баф, то всем нужна, не придумывай. А щиты сейчас носят вообще все.

2022-12-30 14:53 UTC, KIBORG04 commented on code/game/objects/items/weapons/shields.dm
> +		var/turf/no_perpendicular_back = get_step(user_turf, turn(saved_dir, 180))
> Если что-то даёт имба-баф, то всем нужна, не придумывай

Нет. Без визуальных обозначений про это забудут и никогда не вспомнят, тем более заставить еще 2х челиков тебе поверить.

А больше я не хочу тебе писать, почему это хуйня, которая на тау не юзабельна

2022-12-30 14:58 UTC, Deahaka commented on code/game/objects/items/weapons/shields.dm
> +		var/turf/no_perpendicular_back = get_step(user_turf, turn(saved_dir, 180))
Так и напиши что не хочешь добавлять и всё,  я закрою ПР. А то тут 10 комментов как будто ты об этом ещё подумывал.

2022-12-30 22:14 UTC, Deahaka commented
Чуть-чуть поменял рабочее, чтобы оно дир передавало. Не смог сделать эти оверлеи для щита и моба одновременно. хз пока идея только get_standing_overlay() юзать но это нигде не юзается вообще в билде и все оверлеи завязаны на смене icon_state, что значит надо на каждый щит вручную вставлять оверлей, а это говно.

2022-12-30 22:16 UTC, KIBORG04 commented
get_standing_overlay лол нет

2023-02-21 09:02 UTC, Deahaka commented
Нарисовал аутлайн для ин-хендов с включённым бонусом. Наложил фильтер на итем при активировании щитов. Убрал нюковский ещилд из-за того что он багованный какой-то да и нюка думаю не нуждается в замедлении для +15 блокировки по причине что они убер-сильные и быстрые.

2023-02-21 09:04 UTC, AndroBetel commented
скинь картинку как выглядит

2023-02-21 09:06 UTC, Deahaka commented
![000000000000000000000000000000000000007](https://user-images.githubusercontent.com/96499407/220299009-a1af4a96-3214-4ab3-bebf-23f59a721e51.png)
![0000000000000000000000000000000000](https://user-images.githubusercontent.com/96499407/220299021-d6b4f8f2-2cfe-4a24-9bc4-0cdb80cf6c72.png)

2023-02-22 07:38 UTC, volas requested changes

2023-02-22 07:38 UTC, volas commented on code/game/objects/items/weapons/shields.dm
> +	//Using when shield on back, when
странный комментарий, и вообще не обязателен, условие ниже объясняет само себя

2023-02-22 07:38 UTC, volas commented on code/game/objects/items/weapons/shields.dm
> +		return block_chance
изменение поведения функции в зависимости от того, передали сюда юзера или нет - не очевидное. И из 4-х вызовов Get_shield_chance ты добавил параметр только к 2, т.е. это поведение еще и как-то используется.

Я бы предложил просто сразу тут и искать носильщика.

2023-02-22 07:38 UTC, volas commented on code/modules/mob/living/carbon/human/human_movement.dm
> +		SEND_SIGNAL(I, COMSIG_ATOM_CHANGE_DIR, src, dir)
У меня ощущение, что сигналы тут используются не верно, и прослойка не нужна.

Скорее всего можно просто в enable_wallshield подписываться на событие COMSIG_ATOM_CHANGE_DIR носильщика щита

2023-02-23 08:45 UTC, Deahaka commented
Сигнал теперь регистрируется от юзера напрямую, удалил лишнее описание, поставил в гет шилд поиск юзера вместо передачи его непонятно когда

2023-02-23 09:16 UTC, volas commented on code/modules/mob/living/carbon/human/human.dm
> +	RegisterSignal(src, list(COMSIG_ATOM_CHANGE_DIR), .proc/inform_items_about_changing_dir)
прок и сигнал теперь не нужны

2023-02-23 09:31 UTC, Deahaka commented
Удаляю неиспользуемые проки но не мержить надо щас ещё под возвращение замедления предметов симбаки перекинуть и потестить код

2023-02-23 09:49 UTC, Deahaka commented
Ну вроде всё работает

2023-02-23 10:19 UTC, volas commented on code/modules/mob/living/carbon/human/human_movement.dm
> +				if(shield && shield.wall_of_shield_on)
```suggestion
				if(istype(shield) && shield && shield.wall_of_shield_on)
```

еще замедление в 3 может быть будет слишком, учитывая что мы обычное от вещей вернули

2023-02-23 13:44 UTC, Deahaka commented on code/modules/mob/living/carbon/human/human_movement.dm
> +				if(shield && shield.wall_of_shield_on)
Уменьшил на одиничку. 0,5 за щит + 2 от активированной стойки ~= 3 изначально задуманное.

2023-02-23 16:07 UTC, volas approved these changes

2023-02-23 16:07 UTC, merged