Небольшой ребаланс репульса
TauCetiStation/TauCetiClassic pull request #10580
Opened 2023-01-04 14:41 UTC by Mercurialaste

## Описание изменений
Теперь включенные магбутсы защищают от отталкивания репульсом.
## Почему и что этот ПР улучшит
Геймплей, добавляет хоть какую-то защиту от репульса.
## Авторство
Я
## Чеинжлог
:cl:
- balance: Магбутсы теперь защищают от отталкивания репульса.

2023-01-04 14:41 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2023-01-04 14:53 UTC, KIBORG04 commented
надо бал деп и менторов

2023-01-12 20:05 UTC, KIBORG04 commented
где бал деп и где коммит от реминд ми

2023-01-12 20:09 UTC, Mercurialaste commented
> где бал деп и где коммит от реминд ми

В дискорде
![image](https://user-images.githubusercontent.com/90282587/212170303-bd73f08c-72ab-4e71-9825-2e273e947620.png)

2023-01-12 20:12 UTC, KIBORG04 commented
где коммит от реминд ми

2023-01-12 20:14 UTC, Mercurialaste commented
> где коммит от реминд ми

?

2023-01-12 20:14 UTC, KIBORG04 commented
![image](https://user-images.githubusercontent.com/26389417/212171241-7b6f8ad3-e685-46ca-9a55-1b3a20c793e9.png)

2023-01-12 20:18 UTC, Mercurialaste commented
🤨

2023-01-12 20:34 UTC, Mercurialaste commented
> ![image](https://user-images.githubusercontent.com/26389417/212171241-7b6f8ad3-e685-46ca-9a55-1b3a20c793e9.png)

Ты уверен, что это нужно было коммитить?
Я думал, что он это для более удобной проверки сделал.

2023-01-19 03:59 UTC, pro100kotah commented
Ну шо, когда уже там

2023-01-24 12:06 UTC, Mercurialaste commented
Ничего не понятно, покажите что Ремайнд ми имел в виду, я попробовал и так: 
```
		if(AM == user || AM.anchored || (ishuman(H) && (
			(istype(H.shoes, /obj/item/clothing/shoes/magboots) && (H.shoes.flags & NOSLIP)) ||
			(istype(H.wear_suit, /obj/item/clothing/suit/space/rig) && (H.wear_suit.flags & NOSLIP)))
				)
			)
```
Но все равно ошибка.

2023-01-24 12:13 UTC, KIBORG04 commented
прочти ошибку, расставь `\` при переносах, подумай

2023-01-27 16:21 UTC, KIBORG04 commented on code/datums/spells/repulse.dm
> +		)
```suggestion
		if(AM == user || AM.anchored || \
			(ishuman(H) && ( \
				(istype(H.shoes, /obj/item/clothing/shoes/magboots) && (H.shoes.flags & NOSLIP)) \
					|| \
				(istype(H.wear_suit, /obj/item/clothing/suit/space/rig) && (H.wear_suit.flags & NOSLIP)) \
				)
			)
		)
```
а вообще да, можно не такой хуйней маяться  с переносами, а сделать отдельный прок. И наверное я настою над этим. Пихнешь прок куда-то ко всем /clothing'ам. Воот. А че я выше подредачил можешь игнрировать и просто посмотреть как это сделать красивее

2023-01-27 16:23 UTC, KIBORG04 commented on code/datums/spells/repulse.dm
> +		)
ну или пихнуть не в моба а в хумана, хз

2023-01-27 20:31 UTC, Mercurialaste commented on code/datums/spells/repulse.dm
> +		)
> /clothing'ам

mob`ам может имел в виду?

2023-01-28 08:55 UTC, Mercurialaste commented
vse

2023-02-07 20:29 UTC, LudwigVonChesterfield commented on code/modules/mob/living/carbon/human/human.dm
> +/atom/movable/proc/can_be_trow(human)
если это функция исключительно для репульса я бы предпочёл чтобы этот код был в репульсе?

2023-02-07 20:30 UTC, LudwigVonChesterfield commented on code/modules/mob/living/carbon/human/human.dm
> +/atom/movable/proc/can_be_trow(human)
а, Киборг хотел отдельнй прок...

2023-02-07 20:30 UTC, LudwigVonChesterfield commented on code/datums/spells/repulse.dm
> +		if(AM == user || AM.anchored || can_be_trow(AM))
учитывая что репульс это объект почему бы функцию кен би тровн не дать репульсу

2023-02-09 19:37 UTC, Deahaka commented on code/modules/mob/living/carbon/human/human.dm
> +		(istype(H.wear_suit, /obj/item/clothing/suit/space/rig) && (H.wear_suit.flags & NOSLIP)) \
flags & NOSLIP неактуально, обновляй?

2023-02-12 20:24 UTC, Mercurialaste commented on code/modules/mob/living/carbon/human/human.dm
> +		(istype(H.wear_suit, /obj/item/clothing/suit/space/rig) && (H.wear_suit.flags & NOSLIP)) \
ауэа... Что сейчас актуально?

2023-02-16 15:39 UTC, LudwigVonChesterfield requested changes
если can_be_thrown перенесут в спелл/repulse вместо /atom/movable я буду готов апрувнуть

2023-02-28 05:23 UTC, Deahaka commented
1. Можно ли IC понять что тебе нужно надевать магбутсы чтобы тебя не откинуло?
2. Почему что-то такое распространённое как магбутсы нивелирует то, на что потрачены очки в спеллбуке? Какой смысл покупать репульс из категории "Защита" если он не защитит тебя после первых одного-двух использований?

2023-02-28 05:24 UTC, LudwigVonChesterfield commented
> Почему что-то такое распространённое как магбутсы нивелирует то, на что потрачены очки в спеллбуке? Какой смысл покупать репульс из категории "Защита" если он не защитит тебя после первых одного-двух использований?

Но ведь они должны быть активны, что замедляет игрока. Ты трейдишь скорость на то чтобы законтрить откидывание

2023-02-28 05:33 UTC, Deahaka commented
> Ну они защищают от откидывания ветром, если репульс тоже пихает ветром то почему бы и нет!

Но пишет ли репульс, что жертва откидывается сильным дуновением ветра... Нет, не пишет. Может тогда стоит это добавить!

> Но ведь они должны быть активны, что замедляет игрока. Ты трейдишь скорость на то чтобы законтрить откидывание.

Вроде бы да, но это не равноценный обмен совсем. Маг умирает на том моменте, когда его заклинания перестают работать. Например, он промахнётся ними. Потому что кроме них у него никакой защиты от любых средств охраны/экипажа нету абсолютно.
+ Стоит учесть что у нас не редки раунды (иногда кажется что буквально каждый второй) когда на станции, конкретно у охраны, появляется щитспавн вещь или вещь антагониста, на которую никто не может расчитывать (ксеноархеология, мусорщики, рандом спавн шмота в карго, дереликт). С половиненным слоудауном от синди магбутов вообще обмена скорости на protecc нет и близко.

2023-03-21 10:15 UTC, closed without merging