Перевод описания Емага, ИД карт и дисков.
TauCetiStation/TauCetiClassic pull request #10602
Opened 2023-01-10 21:00 UTC by Fluffy-510

## Описание изменений
 Переводит описание ИД карт всех сотрудников, Емага, а также дисков с различными данными.
## Почему и что этот ПР улучшит
 Погружение. Приятнее играть в игру в которой тебе не надо включать внутреннего переводчика или гугл переводчика чтобы перевести заинтересовавшее тебя описание предмета посередине какого-либо игрового движа.
## Авторство

## Чеинжлог
:cl:
 - ru: Перевод описания Емага, ИД карт и дисков.

2023-01-10 21:00 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2023-01-10 21:10 UTC, Deahaka commented
Сори, но волас сказал что не больше 1-го ПРа переводов открытых должно быть. Исключение видимо для анонсов сделали, так как там звуковые файлы только трогаются

2023-01-11 08:25 UTC, Fluffy-510 commented
И что теперь делать? Закрыть этот ПР и ждать или идти помогать с мержем другого перевода?

2023-01-11 09:49 UTC, KIBORG04 commented
Лучше конечно помочь, там капец

2023-01-11 12:48 UTC, maleyvich commented on code/game/objects/items/weapons/cards_ids.dm
> +	desc = "Карта, используемая для индификации личности, должности и станционого доступа."
индификация???

2023-01-11 12:49 UTC, maleyvich commented on code/game/objects/items/weapons/cards_ids.dm
> +	desc = "Карта, пренадлежащая сотруднику гражданского персонала."
пренадлежащая?

2023-01-11 12:49 UTC, maleyvich commented
10 пренадлежит из 10

2023-01-11 12:55 UTC, BasiaBelov commented
> Исключение видимо для анонсов сделали, так как там звуковые файлы только трогаются
Ничерта подобного. Текст и код тоже трогаю.

2023-01-11 13:12 UTC, Fenriros requested changes
Поправить надо это, может ещё что.

2023-01-11 13:12 UTC, Fenriros commented on code/game/objects/items/weapons/cards_ids.dm
> +	desc = "Карта, пренадлежащая сотруднику гражданского персонала."
```suggestion
	desc = "Карта, выдаваемая обычным сотрудникам."
```
```suggestion
	desc = "Карта, выдаваемая гражданским сотрудникам."
```

2023-01-11 14:26 UTC, Fluffy-510 commented
Как редактировать изменения в ПРе?

2023-01-11 14:32 UTC, Chip11-n commented
Просто создаешь ещё один коммит и пушишь его. Он сам появится в пре

2023-01-11 18:39 UTC, Fluffy-510 reviewed
Пре/При + описание карты КМ

2023-01-11 18:39 UTC, Fluffy-510 commented on code/game/objects/items/weapons/cards_ids.dm
> +	desc = "Карта, пренадлежащая сотруднику службы безопасности."
```suggestion
	desc = "Карта, принадлежащая сотруднику службы безопасности."
```

2023-01-11 18:39 UTC, Fluffy-510 commented on code/game/objects/items/weapons/cards_ids.dm
> +	desc = "Карта, пренадлежащая агенту внутренних дел."
```suggestion
	desc = "Карта, принадлежащая агенту внутренних дел."
```

2023-01-11 18:39 UTC, Fluffy-510 commented on code/game/objects/items/weapons/cards_ids.dm
> +	desc = "Карта, пренадлежащая сотруднику инженерного отдела."
```suggestion
	desc = "Карта, принадлежащая сотруднику инженерного отдела."
```

2023-01-11 18:39 UTC, Fluffy-510 commented on code/game/objects/items/weapons/cards_ids.dm
> +	desc = "Карта, пренадлежащая сотруднику медицинского отдела."
```suggestion
	desc = "Карта, принадлежащая сотруднику медицинского отдела."
```

2023-01-11 18:39 UTC, Fluffy-510 commented on code/game/objects/items/weapons/cards_ids.dm
> +	desc = "Карта, пренадлежащая сотруднику научного отдела."
```suggestion
	desc = "Карта, принадлежащая сотруднику научного отдела."
```

2023-01-11 18:39 UTC, Fluffy-510 commented on code/game/objects/items/weapons/cards_ids.dm
> +	desc = "Карта, пренадлежащая сотруднику отдела снабжения."
```suggestion
	desc = "Карта, принадлежащая сотруднику отдела снабжения."
```

2023-01-11 18:39 UTC, Fluffy-510 commented on code/game/objects/items/weapons/cards_ids.dm
> +	desc = "Карта начальника, представляющая возможность планирования и материальную обеспеченость владельца."
```suggestion
	desc = "Карта начальника, представляющая способность планирования и материальную обеспеченность владельца."
```

2023-01-14 21:03 UTC, Fluffy-510 commented on code/game/objects/items/weapons/cards_ids.dm
> +<<<<<<< HEAD
```suggestion
```

2023-01-14 21:03 UTC, Fluffy-510 commented on code/game/objects/items/weapons/cards_ids.dm
> +=======
```suggestion
```

2023-01-14 21:03 UTC, Fluffy-510 commented on code/game/objects/items/weapons/cards_ids.dm
> +>>>>>>> parent of 40d471868c (Перевод описания Емага, ИД карт и дисков.)
```suggestion
```

2023-01-14 21:06 UTC, Fluffy-510 commented on code/game/objects/items/weapons/cards_ids.dm
>  	desc = "A card used to provide ID and determine access across the station."
```suggestion
```

2023-01-15 20:23 UTC, Fluffy-510 commented on code/game/objects/items/weapons/cards_ids.dm
> +	access = get_all_accesses()
```suggestion
```

2023-01-15 20:49 UTC, Fluffy-510 commented
Ура, больше не ругается

2023-01-31 02:18 UTC, BasiaBelov commented
Ребят, вы там решите уже что с этим делать. А то оно уже недели две лежит без разбору.

2023-01-31 02:29 UTC, Fluffy-510 commented
Есть пожелания/замечания? Нужно ли что-то подправить или всё всех устраивает?

2023-01-31 02:30 UTC, BasiaBelov commented
Смотрю...

2023-01-31 02:34 UTC, BasiaBelov commented
Ну, по буквам пробежался, вроде всё хорошо выглядит. 
Не знаю почему людям вечно не так кажется...

2023-01-31 05:11 UTC, BasiaBelov commented
Помнится, Волас или кто-то из наших переводчиков говорил, мол "ID желательно так и оставить, как ID. Практически во всех проектах с руссификацией ID остаётся неизменным" 
Но в нашем случае, думаю я, это опционально и не совсем обязательно.
_Всего лишь моё жалкое мнение._

2023-02-01 08:39 UTC, BasiaBelov commented
Ну что там?

2023-02-01 08:48 UTC, AndroBetel commented on code/game/objects/items/weapons/cards_ids.dm
> +	desc = "Это карта с магнитной полосой, прикрепленной к какой-то схеме. Выглядит слишком разбитой, чтобы её можно было использовать для чего-либо, кроме утилизации."
а чем ее разбивали

2023-02-01 08:48 UTC, AndroBetel commented on code/game/objects/items/weapons/cards_ids.dm
> +	desc = "Радужная карта, которая олицетворяет смех и несгибаемость владельца."
надо бы уже какойто гайдлайн по переводу робуста

2023-02-01 08:48 UTC, AndroBetel commented on code/game/objects/items/weapons/cards_ids.dm
> +	desc = "Запасное удостоверение личности самого Верховного лорда."
скорее повелителя а не лорда

2023-02-01 08:51 UTC, Fluffy-510 commented on code/game/objects/items/weapons/cards_ids.dm
> +	desc = "Запасное удостоверение личности самого Верховного лорда."
хорошо

2023-02-01 08:52 UTC, Fluffy-510 commented on code/game/objects/items/weapons/cards_ids.dm
> +	desc = "Запасное удостоверение личности самого Верховного лорда."
А вариант с владыкой норм?

2023-02-02 03:38 UTC, BasiaBelov commented
@KIBORG04 думаю, уже можно мержать.
Не вижу, чтобы можно было к чему-то ещё придраться.

2023-02-02 06:56 UTC, KIBORG04 commented
Бля, кроме того что где-то точки в конце проебаны, так тут ещё и какие-то ДИСКЕТЫ вместо дисков и карт, причём где-то карта ДИСКЕТА, а где-то карта карта. Я пролистал 2 секунды и мне хватило кринжа

2023-02-02 07:25 UTC, BasiaBelov commented
Я просто не особо понимаю про что говорится, когда в описании идёт речь о "дискетах*
Думал это норма...

2023-02-02 07:28 UTC, BasiaBelov commented
@Fluffy-510 вот и дела подошли...

2023-02-02 07:44 UTC, Fluffy-510 commented
> 

Не знаю, я думаю что дискета больше подходит на эту роль, да и вообще она очень похожа на неё:
![image](https://user-images.githubusercontent.com/109436132/216262186-89409b7f-5113-401c-920f-751c20abc5ff.png)

2023-02-02 07:53 UTC, BasiaBelov commented
Надо попробовать самому перевести с нуля, чтобы предложить некоторые изменения нормально...

2023-02-02 07:55 UTC, KIBORG04 commented
Ладно, в месте где card стало ДИСКЕТОЙ это уместно,  я не прав. Но это само слово довольно архаическое

2023-02-02 12:14 UTC, BasiaBelov commented
Ну тута немного это...
Не дискеты, кажется.
```
desc = "Используется в дискетных делах."
icon = 'icons/obj/card.dmi'
```
![image](https://user-images.githubusercontent.com/115452414/216321886-2dee4ed1-542f-4260-a1ee-120f153d3687.png)

2023-02-02 14:48 UTC, Fluffy-510 commented
> Ну тута немного это... Не дискеты, кажется.
> 
> ```
> desc = "Используется в дискетных делах."
> icon = 'icons/obj/card.dmi'
> ```
> 

ой
Это получается пустые карты, которые в коробочках у ГП?
Что это за карты и где они используются?

2023-02-02 15:04 UTC, KIBORG04 commented on code/game/objects/items/weapons/cards_ids.dm
> +	desc = "ID карта прямиком от Центрального Командования."
```suggestion
	desc = "ID карта прямиком с Центрального Командования."
```
цк все же это место, а не иерархия

2023-02-02 15:07 UTC, KIBORG04 commented on code/game/objects/items/weapons/cards_ids.dm
> +	desc = "Запасная ID карта самого Верховного лорда."
"lord" не всегда означает лорд

2023-02-02 15:07 UTC, KIBORG04 commented on code/game/objects/items/weapons/cards_ids.dm
> +	desc = "ID карта личности прямиком от Синдиката."
какой личности, шизы?

2023-02-02 15:08 UTC, KIBORG04 commented on code/game/objects/items/weapons/cards_ids.dm
> +	desc = "ID карта начальника, представляющая способность планирования и материальную обеспеченность владельца."
Че ориганал кринж, че перевод больштй кринж

2023-02-02 15:10 UTC, KIBORG04 commented on code/game/objects/items/weapons/cards_ids.dm
> +	desc = "Белоснежная золотая ID карта, символизирующая слезы и молчаливость владельца."
```suggestion
	desc = "Белоснежно-золотая ID карта, символизирующая слезы и молчаливость владельца."
```

Плюс непонятно откуда впринципе пошло "белоСНЕЖНАЯ", а не просто белая

2023-02-02 15:14 UTC, KIBORG04 commented on code/game/objects/items/weapons/cards_ids.dm
> +	desc = "Радужная золотая ID карта, которая символизирует смех и несгибаемость владельца."
Если поставить два конфликтующих прилагательных рядом, то лучше не станет..  Какая нафиг `Радужная золотая ID карта`

2023-02-02 15:15 UTC, KIBORG04 commented on code/game/objects/items/weapons/cards_ids.dm
> +	desc = "Радужная ID карта, которая олицетворяет смех и несгибаемость владельца."
robust потерял всю свою мощь после этого перевода

2023-02-02 15:16 UTC, KIBORG04 commented on code/game/objects/items/weapons/cards_ids.dm
> +	desc = "ID карта начальника, олицетворяющая заботу и сострадание к раненым и больным у владельца."
:cry: 

Че они у владельца забыли

2023-02-02 15:19 UTC, KIBORG04 commented on code/game/objects/items/weapons/cards_ids.dm
> +	desc = "ID карта начальника, которая олицетворяет доблесть владельца и его покровительство беззащитных."
:cry:

2023-02-02 15:20 UTC, KIBORG04 commented on code/game/objects/items/weapons/cards_ids.dm
> +	desc = "ID карта, выдаваемая гражданским сотрудникам."
а ученые типа не гражданские?

2023-02-02 15:22 UTC, KIBORG04 commented on code/game/objects/items/weapons/cards_ids.dm
> +	desc = "ID карта, используемая для определения личности, должности и станционого доступа."
```suggestion
	desc = "ID карта, используемая для определения личности, должности и станционного доступа."
```
![image](https://user-images.githubusercontent.com/26389417/216365711-b99b40cc-a5ec-4cfd-a544-9a2aab61ceda.png)
даже гитхаб ошибку подсвечивает

2023-02-04 08:17 UTC, BasiaBelov commented
Опять встали. Да что ты будешь делать...

2023-02-08 13:13 UTC, Fluffy-510 commented
> Ну тута немного это... Не дискеты, кажется.
> 
> ```
> desc = "Используется в дискетных делах."
> icon = 'icons/obj/card.dmi'
> ```
> 
> ![image](https://user-images.githubusercontent.com/115452414/216321886-2dee4ed1-542f-4260-a1ee-120f153d3687.png)

/obj/item/weapon/card
![2023-02-08_15-48-34](https://user-images.githubusercontent.com/109436132/217539146-8b09e11b-29b4-4d47-a37d-8d7497732a2d.png)
этот предмет никак не используется в игре, у него даже нету спрайта
и вообще он не дискета

2023-02-12 19:26 UTC, Fluffy-510 commented
транслейт деп?
какие замечания остались?

2023-02-13 17:04 UTC, Deahaka approved these changes

2023-02-20 19:24 UTC, Fluffy-510 commented
Получается всё ок?

2023-03-08 08:04 UTC, volas commented on code/game/objects/items/weapons/cards_ids.dm
> +	desc = "Запасная ID карта самого Верховного властелина."
```suggestion
	desc = "Запасная ID карта самого Верховного Властелина."
```

2023-03-08 08:06 UTC, volas commented on code/game/objects/items/weapons/cards_ids.dm
> -/obj/item/weapon/card/data
с переводами и так всё сложно, лучше не делать лишних перестановок, на будущее

2023-03-08 08:06 UTC, volas commented on code/game/objects/items/weapons/cards_ids.dm
> +	desc = "ID карта сотрудников Велосити."
просьба дополнить словарь в https://wiki.taucetistation.org/%D0%9F%D0%B5%D1%80%D0%B5%D0%B2%D0%BE%D0%B4

2023-03-08 08:07 UTC, merged