сват шлем респрайт
TauCetiStation/TauCetiClassic pull request #10610
Opened 2023-01-14 11:37 UTC by simb11

## Описание изменений
![image](https://user-images.githubusercontent.com/84613249/212469633-b762c720-4e2b-4358-94f2-f9dbd06a9960.png)
а ещё он теперь защищает от вспышек и прячет лицо
## Почему и что этот ПР улучшит
билд станет чуточку красивее
## Авторство
CEV Eris
## Чеинжлог
:cl: Simbaka, CEV Eris
- image: Респрайт шлема SWAT.

2023-01-14 11:37 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2023-01-14 11:48 UTC, AndroBetel commented
подними эту банку

2023-01-14 11:49 UTC, AndroBetel commented on code/modules/mob/living/carbon/human/human.dm
> +	if(!istype(head, /obj/item/clothing/head/helmet/space/sk) && istype(head, /obj/item/clothing/head/helmet/space) || istype(head, /obj/item/clothing/head/helmet/syndiassault) || istype(head, /obj/item
сделай это уж переменной какойто я хз

2023-01-14 12:01 UTC, Chip11-n commented on code/modules/mob/living/carbon/human/human.dm
> +	if(!istype(head, /obj/item/clothing/head/helmet/space/sk) && istype(head, /obj/item/clothing/head/helmet/space) || istype(head, /obj/item/clothing/head/helmet/syndiassault) || istype(head, /obj/item
#10111

2023-01-14 13:43 UTC, KIBORG04 commented
а где спрайт дифф втф

2023-01-15 20:31 UTC, KIBORG04 commented
А почему на превью только маска? Где броня?

2023-01-15 20:41 UTC, simb11 commented
вот фотка шлема с броней
![image](https://user-images.githubusercontent.com/84613249/212566050-10d610a1-9164-440f-b8bd-9707529803c5.png)

2023-01-15 20:53 UTC, KIBORG04 commented
Как по мне, оно в соло не сочитается со всей одеждой капитана. Надо стайл деп сюда

2023-01-15 21:39 UTC, UDaV73rus requested changes
Нос фронтальный и боковой разного цвета

2023-01-15 21:54 UTC, simb11 commented
поправил нос
![image](https://user-images.githubusercontent.com/84613249/212569244-20b8f87f-19c9-4bf4-80eb-aae4961e2974.png)

2023-01-15 22:05 UTC, UDaV73rus approved these changes
Про не состыковку дизайна со старым, это ок. Новый сложный спрайт обусловлен сумасшедшими статами этой шляпки

... осталось выпилить

2023-01-18 19:32 UTC, Riverz1 commented
Через сват шлем можно пить, щас судя по спрайту такой функции не должно быть.

2023-01-18 19:57 UTC, Deahaka commented
> Через сват шлем можно пить, щас судя по спрайту такой функции не должно быть.

Оно прячет лицо, так что пить не должно мочь больше

2023-01-19 04:10 UTC, pro100kotah commented
Неплохо. Если все еще будут докапываться до того, что теперь шлем не сочетается с броней, можешь мне скинуть я попробую поменять цвет слегка. Либо закинуть в спрайт деп. Хотя исходя из того, что этот спрайт кто-то сделал, самим поменять тона будет не так уж и сложно.

2023-01-28 14:13 UTC, LudwigVonChesterfield approved these changes

2023-01-30 00:17 UTC, merged