треллов теперь можно деконвертить не снося им бошки
TauCetiStation/TauCetiClassic pull request #10620
Opened 2023-01-22 18:53 UTC by AndroBetel

## Описание изменений
через хирургию из головы можно вытащить опухоль, которую шедоу вкладывает в трелла при конверте
## Почему и что этот ПР улучшит
убийство теперь не единственный способ взаимодействия с треллом, а возможность их деконверта без особого насилия может их подстегнуть к действиям и сопротивлению СБ
## Авторство
я, спрайт опухоли с ТГ
## Чеинжлог
- rscadd: Треллов теперь можно деконвертить путем вырезания опухоли из башки.

2023-01-22 18:54 UTC, TauKitty commented
###### Changelog status: :radio_button: No changelog

2023-01-22 19:53 UTC, simb11 commented
Без меты на шадоффлингоф фигня какая то
будет такая же клоунада, как и с ченжлингами до введения меты на них. Под клоунадой я имею ввиду ситуации из разряда "Мне кажется подозрительным то, что какой то панк бегает рядом с ксеносом, надо его арестовать и отправить медикам" и админы будут ломать се мозги, нарушение ли это правил или нет

2023-01-22 19:54 UTC, KIBORG04 commented
хуйня пр да

2023-01-22 19:56 UTC, TryXAH commented
Просто сразу же после этого мета на шадоу

2023-01-22 19:58 UTC, AndroBetel commented
у нас кроме того что шедоулинг может треллить нет никакой на него метаинфы, даже флаера понерфили, а так как трелльство типа должно быть основной частью всего режима (чего часто не бывает из-за того что шедоу достаточно силен всоло) дать на него хоть какую-то мету в принципе будет норм

2023-01-22 19:59 UTC, KIBORG04 commented
лучше режим измени а не дебаффай метой

2023-01-22 20:01 UTC, AndroBetel commented
it's as good as it is, ещё бы запретить станить глейром челов с майндщилдом и ваще идеальный будет

2023-01-22 20:03 UTC, KIBORG04 commented
нет, режим однокалиточный и скучный для всех, кроме 2х чуваков

2023-01-22 20:04 UTC, AndroBetel commented
не однокалиточный а одноклеточный, и не режим а игроки, у треллов есть вся мотивация на войну с сб

2023-01-22 20:05 UTC, KIBORG04 commented
По приказу мастера*, не имея никаких баффов. Реверы даж сильнеее будут

2023-01-22 20:06 UTC, AndroBetel commented
не буду с тобой на гитхабе это обсуждать ты нуб

2023-01-22 21:20 UTC, Riverz1 commented
Странно, почему ребята не жалуются тогда на культ со святощей, кст лучше бы ты святощу интегрировал в этот режим, чем вырезание чего-то там

2023-01-25 17:05 UTC, Ro2tCrab commented
Ничего зазорного в деконверте не вижу.

Что бы было легче ставить мету, то тогда уж лучше сразу сделать отображение данного состояния на HUD'ах Мед-Персонала и сканнеров.

Это вполне даст причину проверить состояние человека на наличие сомнительной ерунды.

2023-01-25 17:09 UTC, Ro2tCrab commented
> Ничего зазорного в деконверте не вижу.
> 
> Что бы было легче ставить мету, то тогда уж лучше сразу сделать отображение данного состояния на HUD'ах Мед-Персонала и сканнеров.
> 
> Это вполне даст причину проверить состояние человека на наличие сомнительной ерунды.

-----

Если у кого-то есть сомнения на счёт баланса тенелингов.
**Вспомните тот факт, который чётко указывает на способность тенелинга в одиночку убить всё СБ. ** Для это достаточно взять любое хорошее оружие ближнего боя.

Я уже не говорю о возможности носить Абялятивную броню.

2023-01-26 14:59 UTC, F0xiq commented
Было бы круто не святошу тут привлекать (непонятно какое отношение священник к лингам вообще имеет), а психиатра, сейчас у него вроде как никакого механа нет, а так будет. Дал он таблеточку от лечения светобоязни или от того, что кто-то слышит голос мастера в голове, опухоль проявилась на худах или что-то такое.

2023-01-26 15:09 UTC, Riverz1 commented
> Было бы круто не святошу тут привлекать (непонятно какое отношение священник к лингам вообще имеет), а психиатра, сейчас у него вроде как никакого механа нет, а так будет. Дал он таблеточку от лечения светобоязни или от того, что кто-то слышит голос мастера в голове, опухоль проявилась на худах или что-то такое.

Тоже самое что и с культом, ударил палкой -деконверт

2023-01-27 18:24 UTC, pro100kotah commented
> По приказу мастера*, не имея никаких баффов. Реверы даж сильнеее будут

Треллы под лингом и его абилками запинывают весь отдел СБ. Один трелл врывается в бриг и собирает весь отдел на себя, врывается линг на шреньк или глейр с заморозкой кровью и все. Дальше треллы пиздят их стандубинками, станподами, палками. Хуялками. Поджигают их. 
Они по силе равны реверам, если даже не сильнее из-за своего черного мастера в размере двух штук.

2023-02-09 19:44 UTC, Deahaka commented
Может смешнее было бы чтобы надо вырезать глаза? А сами глаза чтобы светились как у шедоу.

2023-02-12 07:12 UTC, Deahaka commented
Может быть если законвертили то появляется худ как будто внутри человека борер? Потому что действительно предпосылок что-то вырезать человеку по нулям.

2023-02-16 15:47 UTC, LudwigVonChesterfield approved these changes
если пофиксить фейлящиеся тесты я за

2023-02-16 15:50 UTC, AndroBetel commented
а как это фиксить

2023-02-16 17:43 UTC, AndroBetel commented
добавил свечение глаз и ночное зрение по кнопке трелла @LudwigVonChesterfield

2023-02-16 17:46 UTC, KIBORG04 commented on code/game/gamemodes/modes_gameplays/shadowling/shadowling_abilities.dm
> +		user.thrall_sight = FALSE
1. Вручную вызывай update_sight()
2. Почему через оверлеи? А если кот, то глаза же не совпадут

2023-02-16 17:47 UTC, KIBORG04 commented on code/game/gamemodes/roles/shadowling.dm
> +	var/obj/effect/proc_holder/spell/targeted/thrall_sight/spell2 = locate(/obj/effect/proc_holder/spell/targeted/shadowling_hivemind) in antag.current.spell_list
```suggestion
	var/obj/effect/proc_holder/spell/targeted/thrall_sight/spell2 = locate() in antag.current.spell_list
```
Еще и с ошибкой написал.....

2023-02-16 17:47 UTC, KIBORG04 commented on code/game/gamemodes/roles/shadowling.dm
> +	var/obj/effect/proc_holder/spell/targeted/shadowling_hivemind/spell = locate(/obj/effect/proc_holder/spell/targeted/shadowling_hivemind) in antag.current.spell_list
```suggestion
	var/obj/effect/proc_holder/spell/targeted/shadowling_hivemind/spell = locate() in antag.current.spell_list
```

2023-02-16 17:49 UTC, AndroBetel commented on code/game/gamemodes/modes_gameplays/shadowling/shadowling_abilities.dm
> +		user.thrall_sight = FALSE
![image](https://user-images.githubusercontent.com/44546836/219447006-803ecfc6-1135-4422-b294-4ac853757c22.png)
да вроде норм

2023-02-16 17:55 UTC, KIBORG04 commented on code/game/gamemodes/modes_gameplays/shadowling/shadowling_abilities.dm
> +		user.thrall_sight = FALSE
вот бы мир, если бы ты сделал через https://github.com/TauCetiStation/TauCetiClassic/blob/d6767016aa6d4abd9ad53799346f91a38760fcc9/code/datums/components/cult_eyes.dm#L6

2023-02-16 18:04 UTC, KIBORG04 commented
В таком варианте более-менее согласен, но ждите БХ за метаебство от сб

2023-02-18 13:59 UTC, Lexakr commented
Да, чет стремновато будет, надо или мету или на ХУДы медикам как с лярвами. В только втором варианте тоже наверняка будут дебилы, которые "случайно" заведут трелла в медбей по пути в бриг. Ну конечно вариант, где чуловек был затреллен и пошел сам в медбей только педалями можно будет законтрить

2023-02-18 17:20 UTC, Udokun commented
Введение меты лишь развяжет руки людям, режим так и останется ужасным. ХУДы как при инфестейшон тоже не решение проблемы. Как костыль действительно хорошим решением будет добавить палево опухоли в боди сканер. А ещё треллам накинуть какие-нибудь дебаффы, чтобы не было много желающих бегать на гипнозы.

2023-02-23 16:11 UTC, volas requested changes
У многих опасения по завязке фичи на мета-знания, нужно как-то по другому делать.

2023-03-10 04:13 UTC, LudwigVonChesterfield commented
норм ПР не приставай ты тут только административные неувязки

2023-03-15 22:49 UTC, closed without merging