стрельба очередями
TauCetiStation/TauCetiClassic pull request #10634
Opened 2023-01-23 11:02 UTC by simb11

## Описание изменений
добавляет режим стрельбы очередями некоторым видам оружия
## Почему и что этот ПР улучшит
всякие автоматы перестанут быть респрайтами пистолета, а станут реально почти автоматическим оружием.
## Авторство

## Чеинжлог
:cl: Simbaka
- add: Добавлена стрельба очередями.

2023-01-23 11:02 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2023-01-23 11:07 UTC, AndroBetel commented
я их раню не даю аптечку очереди как за гречкой

2023-01-23 11:07 UTC, Mercurialaste commented
покажи на видео

2023-01-23 11:11 UTC, TryXAH commented
Давай давай ура ура

2023-01-23 12:26 UTC, IlinMihail commented
когда фулл авто?

2023-01-23 13:06 UTC, KIBORG04 commented on code/game/gamemodes/modes_gameplays/families/outfit.dm
> +		/obj/item/weapon/gun/projectile/colt1911
```suggestion
		/obj/item/weapon/gun/projectile/colt1911 = 1,
```

2023-01-23 13:07 UTC, KIBORG04 commented on code/modules/jungle/jungle_temple.dm
> +/obj/item/weapon/gun/projectile/pistol, \
```suggestion
		/obj/item/weapon/gun/projectile/pistol, \
```

2023-01-23 13:08 UTC, KIBORG04 commented on code/game/objects/random/random_guns.dm
> -						prob(2);/obj/item/weapon/gun/projectile/glock,\
за че глок

2023-01-23 13:22 UTC, AndroBetel commented
дай глоку gen3 стрельбу очередями тож

2023-01-24 19:01 UTC, Chip11-n commented on code/modules/projectiles/guns/projectile/pistol.dm
> -	return
А что не так с алярмом?

2023-01-24 22:07 UTC, arygal commented
А можно на пулик для меха такое?

2023-01-24 22:31 UTC, KIBORG04 requested changes
не очень

2023-01-24 22:31 UTC, KIBORG04 commented on code/modules/projectiles/guns/projectile/automatic.dm
> +	if(!select)
зачем селект, если в данном случае можно все эти ифки заменить на проверку burst_mode

2023-01-24 22:31 UTC, KIBORG04 commented on code/modules/projectiles/guns/projectile/automatic.dm
> +	fire_delay = 0
0 лучше не ставить

2023-01-24 22:31 UTC, KIBORG04 commented on code/modules/projectiles/gun.dm
> +		shake_camera(user, recoil + 1, recoil)
```suggestion
	if(ignore_skills)
		shake_camera(user, recoil + 1, recoil)
	else if(skill_recoil)
		shake_camera(user, skill_recoil + 1, skill_recoil)
```
мне кажется так по лучше

2023-01-24 22:31 UTC, KIBORG04 commented on code/modules/projectiles/gun.dm
> +			user.update_inv_r_hand()
1. Очевидно, что мне не нравится копи паста. Убрать.
2. Обилие каких-то неиспользуемых параметров функции
3. Весь алгоритм странный. Почему вызывается только код самого выстрела, а не непосредственно сам `/Fire(` burst_size раз? Наверное, чтобы реализовать нормально придется по-рефакторить. Но сейчас, я предлагаю просто сделать какую-то обертку над Fire (он вроде не часто вызывается), сделать нормальный `can_fire` с выносом останавливающего выстрел кода туда и уже там впендюрить `while(can_fire() && fired==burst_size)`. Воот. 

Щас же один из очевидных багов - клоун может выдать очередь 3 выстрела, если на первом выстреле не прокнул взыв. Еще, вроде как, можно в начале выстрелов дропнуть оружку и оно продолжит стрелять, а еще там ДЕБИЛЬНЕЙШИЙ слип, который кроме своей кринжовости еще и может вызвать настакивание.

2023-01-24 22:31 UTC, KIBORG04 commented on code/modules/projectiles/gun.dm
> +		shake_camera(user, recoil + 1, recoil)
а еще я принципе не понял прикола с ignore_skills

2023-01-27 09:37 UTC, simb11 commented on code/modules/projectiles/gun.dm
> +		shake_camera(user, recoil + 1, recoil)
прикол в том чтобы выстрелить очередью в одно и то же место было немного сложнее.

2023-02-09 21:54 UTC, simb11 commented
у меня нет желания этим заниматься
да и незачем 
стрельба очередями это не то что подойдет билду на котором у персонажей в броне ломаются ребра после попадания в пузо двух пистолетных пуль

2023-02-09 21:54 UTC, closed without merging