удаляет случайные нокдауны при ударе оружием ближнего боя
TauCetiStation/TauCetiClassic pull request #10644
Opened 2023-01-24 18:08 UTC by AndroBetel

## Описание изменений
тайтл
## Почему и что этот ПР улучшит
боевка станет менее рандомной, позволит баффнуть урон оружию бб не боясь того что оно станет слишком имбовым
## Авторство
я
## Чеинжлог
:cl:
- balance: Оружием ближнего боя больше нельзя сбить человека с ног.

2023-01-24 18:09 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2023-01-24 18:20 UTC, LudwigVonChesterfield approved these changes
крутой пи эр но разве это не очуметь какой бафф мейкшифт батонов

2023-01-24 18:21 UTC, AndroBetel commented
они и так мегакрутые до этого пра оружие worth using кроме станпалок это буквально либо трейтерские пушки либо топор/золотой огнетуш

2023-01-24 18:27 UTC, LudwigVonChesterfield commented
после етого пр-а ещё менее worth using :pensive: 

может кого-нибудь забаффать ещё типо мечей или ножов...

2023-01-24 18:28 UTC, AndroBetel commented
в этом же пре?

2023-01-24 18:29 UTC, KIBORG04 commented
мм людук пришел и на херовый пр сразу аппрув кидает. Этот пр убьет все мили оружие нахер. Именно благодаря этим станам есворды, мечи культа и тд

2023-01-24 18:31 UTC, AndroBetel commented
слишком хорошо работали станя с первой тычки любого чувака

2023-01-24 18:38 UTC, KIBORG04 requested changes
Хз, в таком виде ПР убивает смысл носить мили вообще

2023-01-25 17:54 UTC, AirBlack commented
\>device says it removes RANDOM knockdowns
\>look inside
\>no knockdowns at all
![image](https://user-images.githubusercontent.com/5171605/214643645-85b795b1-7548-43dc-aa0e-a2d7f6b66117.png)

2023-01-25 17:57 UTC, AndroBetel commented
если все нокдауны рандомные значит все и удаляца... (на самом деле нет, есть ещё захардкоженные приколы у тех же скалок и чумоданов)

2023-01-28 13:52 UTC, LudwigVonChesterfield requested changes
ето троллинг

2023-02-06 17:25 UTC, KIBORG04 commented
тролленг..

2023-02-06 17:25 UTC, closed without merging