Blueshield RETURNS!!!!!
TauCetiStation/TauCetiClassic pull request #10653
Opened 2023-01-27 02:11 UTC by AndroBetel

## Описание изменений
доделывает блющилда из пра #7822 but with a twist

![image](https://user-images.githubusercontent.com/44546836/214994689-c86cf9d3-28c6-447e-b8c3-77d1abfc9b88.png)

1) выпилен до лучших времен тайный сейф - его я доделаю, но потом.
2) удалены какие-то непонятные мегасообщения и выдача дополнительных тк трейторам с задачами на глав. слишком замудрено, а блющилд, на самом-то деле, не такая уж и неприступная стена, чтобы вознаграждать триторов доптк
3) блющилд стал немного красивше с доспехами, чуть лучшими, чем у офицеров
4) всякие упоминания его недоработанности тоже выпилены
и главное, наверное:
5) каждые десять минут блющилду нужно экзаминить любого главу или АВД, чтобы не грустить, таким образом зависимость от своей задачи у него будет не только админская (время можно сделать рандомным или уменьшить)
## Почему и что этот ПР улучшит
блющилда много кто хочет, его лоббировал волас, но не вышло... а теперь вышло!
## Авторство
изначально делал первертгениус, доделал я, спрайты с эриса
## Чеинжлог
:cl: PervertGenius, AndroBetel
- rscadd[link]: Синий щит прибывает на станцию.

2023-01-27 02:11 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2023-01-27 08:01 UTC, Riverz1 commented
Жесть, почему пда так по цвету отличается.....

2023-01-27 08:14 UTC, UDaV73rus commented
На станции не хватает ролькохантеров? Какая нужда в блющилде что его ВсЕ так хотят

2023-01-27 08:24 UTC, Deahaka commented on code/modules/mob/living/carbon/human/examine.dm
> +		if(H.mind.assigned_role == "Blueshield Officer" && mind && mind.assigned_role in to_look_at)
Скобки для `in` проверки?

2023-01-27 11:34 UTC, AndroBetel commented
> Жесть, почему пда так по цвету отличается с другим спрайтами блющилда.....

интересный факт - чтобы не париться я брал спрайты трусов с гаммы и чуть-чуть редактировал, ведь профессиональные рисовальщики прошлого подобрали цветовую гамму лучше перверта. пда почему-то там был такой вот...

> На станции не хватает ролькохантеров? Какая нужда в блющилде что его ВсЕ так хотят

охрана у нас в настоящее время пососная если всеми силами не пытается в повергейм. ещё один чел с сомнительным эквипом и конкретным заданием погоды не сделает.

2023-01-27 11:55 UTC, KIBORG04 commented on code/modules/mob/living/carbon/human/examine.dm
> +		var/list/to_look_at = list("Captain", "Head of Personnel", "Head of Security", "Chief Engineer", "Research Director", "Chief Medical Officer", "Internal Affairs Agent")
кринж

2023-01-27 11:56 UTC, AndroBetel commented on code/modules/mob/living/carbon/human/examine.dm
> +		var/list/to_look_at = list("Captain", "Head of Personnel", "Head of Security", "Chief Engineer", "Research Director", "Chief Medical Officer", "Internal Affairs Agent")
а че сделать

2023-01-27 11:57 UTC, KIBORG04 commented on code/modules/mob/living/carbon/human/examine.dm
> +				addtimer(CALLBACK(mood2, /datum/component/mood.proc/add_event, null, "blueshield", /datum/mood_event/blueshield), 10 MINUTES)
кринж, лучше сделай прок, который сигнал будет слать

2023-01-27 11:58 UTC, KIBORG04 commented on code/game/jobs/jobs.dm
> +	"Blueshield Officer"
в чем он комманд позишон, он где-то в сб должен быть наверн

2023-01-27 11:59 UTC, AndroBetel commented on code/game/jobs/jobs.dm
> +	"Blueshield Officer"
у перверта он метался между секьюрити и комманд, для секьюрити он слишком синий, пусть тут будет

2023-01-27 11:59 UTC, KIBORG04 commented on code/modules/mob/living/carbon/human/examine.dm
> +		var/list/to_look_at = list("Captain", "Head of Personnel", "Head of Security", "Chief Engineer", "Research Director", "Chief Medical Officer", "Internal Affairs Agent")
var/static/list/to look at = heads_positions + "Internal Affairs Agent"

2023-01-27 12:00 UTC, KIBORG04 commented on code/game/jobs/jobs.dm
> +	"Blueshield Officer"
но нужен ли он сверху в пда??

2023-01-27 12:01 UTC, KIBORG04 commented on code/game/jobs/jobs.dm
> +	"Blueshield Officer"
ну хзхз

2023-01-27 12:42 UTC, PersyFOX commented
А РИГа отдельного для БЩ не будет?

2023-01-27 13:48 UTC, PersyFOX commented
Доступа к главам нема. Хотя вроде должен быть. Нет?

2023-01-27 15:52 UTC, WatlerJe commented
>каждые десять минут блющилду нужно экзаминить любого главу или АВД, чтобы не грустить, таким образом зависимость от своей задачи у него будет не только админская (время можно сделать рандомным или уменьшить)

А если главы/АВД нету на станции?

2023-01-27 15:52 UTC, NeOchenLord commented
А как будет выглядеть офис? Так же как прежде, но без сейфа?

2023-01-27 16:15 UTC, AndroBetel commented
> А если главы/АВД нету на станции?

блющилд гасит боль от своей бесполезности выпивкой и тяжелыми наркотиками

> А как будет выглядеть офис? Так же как прежде, но без сейфа?

не, у нас поменялись реалии и блющилд теперь уживается в конурах поменьше

бокс
![image](https://user-images.githubusercontent.com/44546836/215135967-59a6f975-74a6-43c8-88b4-60c904480048.png)
гамма
![image](https://user-images.githubusercontent.com/44546836/215136094-65fd99dd-6348-4768-a395-954f2d7d82fd.png)
прометей
![image](https://user-images.githubusercontent.com/44546836/215136182-ef263a66-2992-41c7-a982-7e98a1e1b433.png)

2023-01-27 16:54 UTC, AndroBetel commented
@volas

2023-01-27 17:20 UTC, volas commented
я когда нибудь потом вернусь и отпишусь, нужно вспоминать всё что обсуждалось в прошлый раз и все проблемы что были...

> каждые десять минут блющилду нужно экзаминить любого главу или АВД, чтобы не грустить, таким образом зависимость от своей задачи у него будет не только админская (время можно сделать рандомным или уменьшить)

но вот это выглядит странно, это разные механики для разных целей, привязывать настроение к профе как-то хз. Сама идея с экзамайном мне нравится, но была бы только реализованна как-то по другому.

2023-01-27 18:19 UTC, pro100kotah commented
> > но вот это выглядит странно, это разные механики для разных целей, привязывать настроение к профе как-то хз. Сама идея с экзамайном мне нравится, но была бы только реализованна как-то по другому.
> 
> даже не знаю, что, кроме настроения, может побудить блющилда держаться рядом с главами... разве что часовая бомба в голове, хз

Смерть глав = смерть БЩ, не? Я просто не знаю как это можно реализовать, но со смертью всех глав тебя подрывает. Или механ как у голема сделать. Если мастер голема рип = рип и голем. Как-то перенести механ на глав или только кэпа? В общем, если это не кажется абсурдом, то может как-то обсудить эту затею.

Это побудит всяких БЩ не играть в офиков и держаться постоянно рядом с главами, охраняя их. В частности рядом с кэпом и ГП.

Муд также можно закрепить на смерти глав, а не экзаймине. Механ как у треллов, если мастер-линг умер, все линги в депрессии. Если главы померли БЩ в депрессии, потому что на ЦК ему оторвут жопу, ибо он не справился со своей задачей.

2023-01-27 18:26 UTC, AndroBetel commented
понимаешь, то, что предлагаешь ты наказывает блющилда пост-фактум - главы могут и не умереть без его контроля, поэтому и находится с ними постоянно как-то не так притягательно. моя же реализация буквально подталкивает к бытию рядом с главами, и чем меньше поставить таймер, тем больше придется бщ быть под попой у какого-нибудь главы

2023-01-27 20:40 UTC, Tap0r commented
Кабинетики мне не нравятся

2023-01-27 21:01 UTC, AndroBetel commented
давай ты после мержа красиво сделаешь

2023-01-28 04:55 UTC, Ro2tCrab commented
> даже не знаю, что, кроме настроения, может побудить блющилда держаться рядом с главами... разве что часовая бомба в голове, хз

Мы и не должны.
Никто же при создании ГП не держал его в офисе клепать доступы.

На первое время хватит и банальной Цепи Командования.
Станция не сгорит от парочки приказов для БШ от глав или возможности просиживать штаны в баре.

2023-01-28 04:58 UTC, Tap0r commented
> давай ты после мержа красиво сделаешь

Может сразу лучше? Могу себе эту ветку притянуть и в дисе тебе скинуть результат.

2023-01-28 04:58 UTC, Ro2tCrab commented
> понимаешь, то, что предлагаешь ты наказывает блющилда пост-фактум - главы могут и не умереть без его контроля, поэтому и находится с ними постоянно как-то не так притягательно. моя же реализация буквально подталкивает к бытию рядом с главами, и чем меньше поставить таймер, тем больше придется бщ быть под попой у какого-нибудь главы

Ограничивать игрока конкретным стилем игры - плохая идея.

2023-01-28 10:21 UTC, WatlerJe commented
То есть сама профа позиционируется как незначительное усиление охранки и скорее как эрзац СБшник для глав. Но в тоже время, в отличии от любой другой профы, даже тех же самых глав, у него есть механика с привязкой к своей задаче. Почему тогда не ввести такое же других пров? Я понимаю, что метод кнута это самый практикуемый на Тау, так как на другое ума не хватает, но мне не кажется, что это не будет работать как задумано и скорее будет мешать.

Тащемта как аналоговое решение я могу предложить задачи для экипажа. По сути обычному члену экипажа дается задачи соответствующие его профе, условному повару например надо приготовить N число моднейших блюд и т.п.
Соответственно у Блу Щитера будет задача на сохранение жизней глав. 
Как это заставит игрока выполнять свою РАБоту?  - Никак. Так же как и привязка к настроению, это никак не заставит игрока играть по профе, зато даст мотивацию. Ведь когда игроку дропается ролька, то никто не заставляет его ее выполнять, да и наградой за ее выполнение служит только зеленый текст _САКСЭЗЗ_.

2023-01-28 13:20 UTC, AndroBetel commented
> Ограничивать игрока конкретным стилем игры - плохая идея.

пиздуй читать пр перверта, обсуждение пра на форуме и смотреть баны на блющилда за 21 год

> Тащемта как аналоговое решение я могу предложить задачи для экипажа. 

задачи во первых конкретно в этом пре вводить не получится банально из-за объема мозгоштурма на придумывание всех задач, а во вторых задачи кроме как наградой после раунда(если награды сделать, условный плюсик на очки в лодаут) будут влиять на персонажа только условно, а подталкивать к слежке за главами точно так же, как и настроение - строчкой где-то там в менюшке. но если задача никак на тебя во время раунда не влияет, то настроение в свою очередь делает кукле и игроку неприятно

не знаю насколько это хорошая идея, но волесу вроде понравилась, посмотрим что ещë скажет - удолить будет нетрудно

2023-01-28 14:10 UTC, WatlerJe commented
Ну а что делать если глава ливнул в крио через 10 минут после старта, а других нету? - Тупить с низким мудом. Данная фича не учитывает того, что в игре возможен сценарий когда нету глав на сервере.

2023-01-28 14:11 UTC, LudwigVonChesterfield commented
существование роли единственная цель которой защищать главу не предусматривает отсутствие главы ето правда

2023-01-28 14:14 UTC, AndroBetel commented
волас забраковал старт раунда только если есть кэп-се-авд, щито поделать...

2023-01-28 20:11 UTC, AndroBetel commented
![image](https://user-images.githubusercontent.com/44546836/215288739-f33986f9-b760-4883-8749-1c39588e5d6f.png)
![image](https://user-images.githubusercontent.com/44546836/215288742-2c1710f5-b5eb-44d4-a187-677f6bf159a8.png)
![image](https://user-images.githubusercontent.com/44546836/215288745-10e3a812-abf3-4b49-84b4-31a33c25969f.png)
дефор помог с конурой

2023-01-29 05:35 UTC, BongoPunch commented
Всё ниже описанное - субъективно
1) 10 минут, кажется, много. Думаю БЩ ролькохантер раз в десять минут будет видеть главу мельком, так что это его не остановит. Можно уменьшить, если одобрят
2) Если будешь доделывать сейф со временем, было бы неплохо на столе оставить листик с инструкцией к его открытию. В прошлый раз его никто толком не открывал из-за незнания.


> волас забраковал старт раунда только если есть кэп-се-авд, щито поделать...

не совсем уловил суть в силу своей безграмотности. БЩ не стартанет при отсутствии данных лиц?

2023-01-29 10:38 UTC, Ro2tCrab commented
> > Ограничивать игрока конкретным стилем игры - плохая идея.
> 
> пиздуй читать пр перверта, обсуждение пра на форуме и смотреть баны на блющилда за 21 год

Зашёл, прочитал и вопросов возникло ещё больше.

*И это без вопросов на счёт того, что большинство БХ на людей с неплохой историей банов*

Но для начала..
-----

Вот привязали вы игрока к Муду...
**А что если Глава тупо пропадёт без вести по своей же глупости?**
** Что будет с БШ после ухода так нужного ему Главы в крио?**
** А если из глав остался лишь мастер воронок и дереликтов РД?**

Я понимаю задумку BS - Телохронитель.

Но опять же.
**На Блюшмлде играет игрок и ад, резня и бойня может просто.. и не быть**
**Главы же могут быть заняты своими делами, 24/7 ходя от работы к работке, тупо делать ничего**
**И если Офицеры СБ все еще могут побегать за злобным клоуном, выпить этанола или побежать собирать хлам для смеха..

## ***Блю Шилд же теперь станет Самым-Самым частым гостем крио.***

----

Что я предлагаю? Дать доступ к снаряжению через глав, но не через ГСБ.

Через доступ ID или код от сейфа снаряжения.
Половина кода главам, половина только для БШ.

Блюшилд бегает всю смену по техам, забывает о главах и требует код от сейфа после всего этого? Бум! Ходи без снаряжения, ибо главам твои похождения к чёрту.

Побежал к ГСБ? У того нет кода.
Арсенал? **Посмей, ибо доступа у тебя туда нет.**
**Вошёл? Получай дубиной от ГСБ или Вардена без особого шанса на успех в самозащите.**

Это все еще делает зависимым БШ от глав, но это более  гибкий для разных ситуаций вариант.

2023-01-29 11:27 UTC, AndroBetel commented
> Если будешь доделывать сейф со временем, было бы неплохо на столе оставить листик с инструкцией к его открытию. В прошлый раз его никто толком не открывал из-за незнания

его никто не открывыл из-за того что он пустой был...

2023-01-29 11:52 UTC, Ro2tCrab commented
> > Если будешь доделывать сейф со временем, было бы неплохо на столе оставить листик с инструкцией к его открытию. В прошлый раз его никто толком не открывал из-за незнания
> 
> его никто не открывыл из-за того что он пустой был... 

Если. Будешь. Доделывать.

2023-01-29 14:45 UTC, AndroBetel commented
![image](https://user-images.githubusercontent.com/44546836/215334130-7b87789b-7ba7-4d4a-9473-1aafbbda1aef.png)
респрайт блющилда от вальтухи
теперь он должен тебе пиво

2023-01-29 14:49 UTC, AndroBetel commented
![image](https://user-images.githubusercontent.com/44546836/215334368-d1656af4-7a48-473c-95fd-c6549af72807.png)
а ещё во

2023-01-29 15:42 UTC, Deahaka commented
Капец кепка козырная

2023-01-29 17:04 UTC, NeOchenLord commented
Прикольная отсылка, но вообще  новые спрайты meh

2023-01-31 19:52 UTC, AndroBetel commented
теперь если глав нет блющилд не грустит

2023-01-31 19:55 UTC, LudwigVonChesterfield commented
а чем он занимается когда нет глав

2023-01-31 20:05 UTC, Mercurialaste commented
бухает до посинения, от грусти. Он должен грустить.

2023-01-31 20:13 UTC, AndroBetel commented
волоса убедите в том что он грустить должен

2023-02-01 10:52 UTC, TauKitty commented
Этот запрос на слияние был упомянут в **Tau Ceti Station Forum**. Там могут быть соответствующие подробности:

https://forum.taucetistation.org/t/wip-blueshield-officer-i-ego-sudba/27761/448

2023-02-05 14:35 UTC, BongoPunch commented
No merge?🧐

2023-02-07 20:07 UTC, AndroBetel commented
@volas ну камон

2023-02-07 20:26 UTC, LudwigVonChesterfield commented
хочу оставить это в истории но я против только потому-что коморка не на мостике.

2023-02-09 19:55 UTC, Deahaka commented on code/datums/components/mood.dm
> +/proc/add_mood_event(mob/living/carbon/human/H, source, datum/mood_event/E)
```suggestion
/proc/add_mood_event(mob/living/H, source, datum/mood_event/E)
```
Если это только для хумана, то почему бы это не засунуть в хумана? А если не только, то зачем там принимается H человек

2023-02-09 19:55 UTC, Deahaka commented on code/modules/clothing/suits/armor.dm
> +	armor = list(melee = 60, bullet = 55, laser = 50, energy = 35, bomb = 35, bio = 0, rad = 0)
Не интереснее было бы выдать броню только от одной-двух видов оружия? Конкретно только от пуль и мили, а остальное заговнить в 25 или меньше? Чёто не очень понимаю зачем ему брони как хосу. Получается будет в игре два пальтишка хайпаверед...

2023-02-09 19:55 UTC, Deahaka commented on code/modules/clothing/under/jobs/security.dm
> +	armor = list(melee = 10, bullet = 0, laser = 0,energy = 0, bomb = 0, bio = 0, rad = 0)
Ну и ожидаемо ещё его форма больше танчит. Куда ж без этого))

2023-02-09 19:59 UTC, KIBORG04 commented on code/datums/components/mood.dm
> +/proc/add_mood_event(mob/living/carbon/human/H, source, datum/mood_event/E)
это костыль, чтобы делать addtimer(SEND_SIGNAL)

2023-02-09 20:00 UTC, KIBORG04 commented on code/datums/components/mood.dm
> +/proc/add_mood_event(mob/living/carbon/human/H, source, datum/mood_event/E)
это костыль, чтобы делать addtimer(CALLBACK(null, .proc/add_mood_event, H, "blueshield", /datum/mood_event/blueshield), 10 MINUTES), потому что addtimer(SEND_SIGNAL) нельзя

2023-02-09 20:06 UTC, AndroBetel commented on code/modules/clothing/suits/armor.dm
> +	armor = list(melee = 60, bullet = 55, laser = 50, energy = 35, bomb = 35, bio = 0, rad = 0)
так у хоса мощность пальта в том что оно закрывает все части тела, доспех бщ же только сундук

2023-02-14 07:02 UTC, volas requested changes
Пробежался по старым обсуждениям, что-то вспомнил, увы многое осталось в дискорде и там искать сложно.

Одной из проблем было описание области применения профы, так как это спавн человека с леталом, который не имеет отношения к СБ или главам (и ограничений СБ и глав правилами и IC), и вытекающие из этого проблемы. 

Должна была быть сопровождающая статья на вики и соответствующие правки в иерархию и процедуры, их лучше вытащить и актуализировать перед ТМ-ом.

В остальном, гуд, то что должен был сделать еще перверт - выкинуть всё не нужное и не переусложнять со старта.

2023-02-14 10:14 UTC, AndroBetel commented on code/game/jobs/job/captain.dm
> +	addtimer(CALLBACK(null, .proc/add_mood_event, H, "blueshield", /datum/mood_event/blueshield), 10 MINUTES)
ну я не против просто выпилить и чтобы все на совести игроков и админов было, потому что ничего другого мы так и не выдумали

2023-02-14 10:14 UTC, AndroBetel commented on code/game/objects/structures/crates_lockers/closets/secure/security.dm
> +	new /obj/item/weapon/melee/baton(src)
у него места на все дубинки хватает

2023-02-14 10:19 UTC, AndroBetel commented on code/modules/mob/dead/new_player/new_player.dm
> +			addtimer(CALLBACK(null, .proc/add_mood_event, blueshield, "blueshield", /datum/mood_event/blueshield), 10 MINUTES)
> вроде таймер вешается после каждой главы
не страшно, потому что вряд ли главы зайдут кучей за две минуты

2023-02-14 11:11 UTC, Deahaka commented on code/game/objects/structures/crates_lockers/closets/secure/security.dm
> +	new /obj/item/weapon/melee/baton(src)
Раньше вроде не было станбатона у него. Зачем он теперь? Неужели нечего больше положить?

2023-02-14 11:12 UTC, AndroBetel commented on code/game/objects/structures/crates_lockers/closets/secure/security.dm
> +	new /obj/item/weapon/melee/baton(src)
потом что-нить другое положим, если придумаем

2023-02-16 15:37 UTC, LudwigVonChesterfield commented on code/game/jobs/job/captain.dm
> +	addtimer(CALLBACK(null, .proc/add_mood_event, H, "blueshield", /datum/mood_event/blueshield), 10 MINUTES)
а как же имплант

2023-02-16 16:24 UTC, AndroBetel commented
переделал на имплант весь цимес с настроением блющилда
конечно не думаю что это хорошо но что сказали сделать то сделал...

2023-02-17 13:44 UTC, LudwigVonChesterfield commented
почему у блющилда нет форсщилда которого он навешивает на глав :cry:
и почему нет такл механа чтобы PRESIDENT, GET DOWN :cry:

2023-02-17 13:45 UTC, LudwigVonChesterfield commented on code/datums/components/mood.dm
> +/proc/add_mood_event(mob/living/carbon/human/H, source, datum/mood_event/E)
чем эта функция красивее `SEND_SIGNAL(H, COMSIG_ADD_MOOD_EVENT, source, E)`

2023-02-17 18:27 UTC, volas commented
мап конфликты с другими тмами

2023-02-18 17:17 UTC, LudwigVonChesterfield commented on code/datums/mood_events/needs_events.dm
> +		description = "<span class='notice'>А где главы?</span>"
можно ли не добавлять эффект если нет глав?

2023-02-18 17:19 UTC, AndroBetel commented on code/datums/mood_events/needs_events.dm
> +		description = "<span class='notice'>А где главы?</span>"
там из-за непонятной системы цдоления муда я не смог и сделал так

2023-02-22 08:49 UTC, AndroBetel commented
конфликты пофикшены

2023-02-22 16:27 UTC, Deahaka commented on code/game/objects/structures/crates_lockers/closets/secure/security.dm
> +	new /obj/item/weapon/melee/baton(src)
```suggestion
	new /obj/item/weapon/melee/telebaton(src)
```
![image](https://user-images.githubusercontent.com/96499407/220691197-e55bf824-cbe5-4560-ba4d-646825f4d532.png)

2023-02-22 16:29 UTC, AndroBetel commented on code/game/objects/structures/crates_lockers/closets/secure/security.dm
> +	new /obj/item/weapon/melee/baton(src)
надо голосование на форуме

2023-02-22 17:25 UTC, Deahaka commented on code/game/objects/structures/crates_lockers/closets/secure/security.dm
> +	new /obj/item/weapon/melee/baton(src)
А на боевые патроны не надо?)))

2023-02-23 07:52 UTC, volas requested changes

2023-02-23 07:52 UTC, volas commented on code/game/gamemodes/modes_gameplays/nuclear/pinpointer.dm
> +	icon_state = "pinoff"
стоит добавить отдельный метод для выключения, но так и было и проблема пинпоинтеров не твоя в рамках пр-а

2023-02-23 07:52 UTC, volas commented on code/game/jobs/job/captain.dm
> +	addtimer(CALLBACK(null, .proc/add_mood_event, H, "blueshield", /datum/mood_event/blueshield), 10 MINUTES)
Зачем резолвать и не комментировать замечания? Людук прав - имплант сам сейчас обрабатывает ситуацию и мусорить в эквипе нет необходимости.

2023-02-23 07:52 UTC, volas commented on code/game/objects/items/weapons/implants/implant.dm
> +/obj/item/weapon/implant/blueshield
Будет логичнее и чище убрать все addtimer(CALLBACK)) с мудом, которые тригерятся в рандомное время, иногда друг за другом, по независимым от бщ обстоятельствам, и вынести это в process импланта.

Ты можешь сохранять время последнего экзамайна главы в импланте, и если оно > 10 минут - накидывать тут муд (сразу сигналом без прослойки add_mood_event).

2023-02-23 10:45 UTC, NeOchenLord commented
В данный момент таймер грусти сбрасывается только если ты уже грустишь. Я осмотрел главу и через 10 секунд словил дебафф. И таймер слишком маленький, весь чат этими экземинами засирается. Можно еще добавить чтобы этот таймер сбрасывали объятья, чтобы чат почище стал.

2023-02-23 14:35 UTC, AndroBetel commented on code/game/objects/items/weapons/implants/implant.dm
> +/obj/item/weapon/implant/blueshield
сделал

2023-02-23 14:35 UTC, AndroBetel commented on code/game/jobs/job/captain.dm
> +	addtimer(CALLBACK(null, .proc/add_mood_event, H, "blueshield", /datum/mood_event/blueshield), 10 MINUTES)
удолил

2023-02-23 14:36 UTC, AndroBetel commented
сделал все что волас просил в ревью, теперь не обязательно экзаминить главу РОВНО через 10 минут, можно и пораньше

2023-02-23 15:59 UTC, volas commented on code/modules/client/preferences_savefile.dm
> -#define SAVEFILE_VERSION_SPECIES_JOBS 30 // job preferences after breaking changes to any /datum/job/
SAVEFILE_VERSION_MAX тоже надо бампнуть. И то и другое должны быть максимальной версии после обновления

2023-02-23 16:04 UTC, volas approved these changes

2023-02-23 16:05 UTC, merged

2023-02-24 01:58 UTC, AzzyDreemurr13 commented
Проблема со кепки, проверьте что там пошло с ней так
![image](https://user-images.githubusercontent.com/74739991/221073362-2fa6a262-6e34-43d3-bc85-1bf27d981552.png)