Частичный порт кода рыгания с ТГ
TauCetiStation/TauCetiClassic pull request #10673
Opened 2023-02-01 10:24 UTC by Deahaka

## Описание изменений
Зашёл на ТГ а там прикольный код рыгания, думаю дай ка сворую.
## Почему и что этот ПР улучшит
Больше возможных настроек рыганий в будущем, улучшения кода
## Авторство

## Чеинжлог

2023-02-01 10:24 UTC, TauKitty commented
###### Changelog status: :radio_button: No changelog

2023-02-01 10:44 UTC, KIBORG04 approved these changes

2023-02-02 10:19 UTC, Sakuya-Izayoi commented on code/modules/mob/living/carbon/human/human.dm
> +/mob/living/carbon/human/vomit(punched = FALSE, masked = FALSE, vomit_type = DEFAULT_VOMIT, blood = FALSE, stun = TRUE, force = FALSE)
если вомит с blood исключает обычный и токсичные вомиты, почему бы его не сделать vomit_type?

2023-02-03 11:30 UTC, KIBORG04 commented on code/modules/mob/living/carbon/human/human.dm
> +	return ..(punched, mask_, vomit_type, blood, stun, force)
у родителя параметра блада нет

2023-02-03 11:30 UTC, KIBORG04 commented on code/modules/mob/living/carbon/carbon.dm
> +	. = ..(punched, mask_, vomit_type, blood, stun, force)
у родителя параметра блада нет

2023-02-03 11:30 UTC, KIBORG04 commented on code/modules/mob/living/carbon/carbon.dm
> +/mob/living/carbon/vomit(punched = FALSE, masked = FALSE, vomit_type = DEFAULT_VOMIT, blood = FALSE, stun = TRUE, force = FALSE)
у родителя параметра блада нет

2023-02-03 11:31 UTC, KIBORG04 commented on code/modules/mob/living/carbon/human/human.dm
> +/mob/living/carbon/human/vomit(punched = FALSE, masked = FALSE, vomit_type = DEFAULT_VOMIT, blood = FALSE, stun = TRUE, force = FALSE)
у родителя параметра блада нет

2023-02-03 11:38 UTC, KIBORG04 requested changes
1

2023-02-06 17:26 UTC, merged