HoS corp uniform resprite
TauCetiStation/TauCetiClassic pull request #10684
Opened 2023-02-02 19:36 UTC by Deahaka

## Описание изменений
Порт с ТГ: https://github.com/tgstation/tgstation/pull/66355
Но там это типо костюм Синдиката. Немного поправил чтобы сидел на кукле как другая одежда. В билде в данный момент не используется.
## Почему и что этот ПР улучшит
# Было
![bilo](https://user-images.githubusercontent.com/96499407/216431197-47b925a1-de47-45c8-9004-aef4655eefbe.png)
# Стало
![stalo](https://user-images.githubusercontent.com/96499407/216431203-1a6b4849-d8d4-4ace-a59d-3c9574d058ff.png)
## Авторство
[Imaginos16](https://github.com/Imaginos16) aka Positive Entropy or Mr. Entropy
## Чеинжлог
:cl: Imaginos16
- image: Респрайт костюма корпората ГСБ

2023-02-02 19:36 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2023-02-03 11:32 UTC, KIBORG04 commented
было же красивее

2023-02-04 13:44 UTC, UDaV73rus commented
Ето же пальто-суит, а не униформа...

2023-02-05 16:55 UTC, UDaV73rus requested changes
хз, униформа пальто это дико

2023-02-05 17:23 UTC, Deahaka commented
Ладно, это действительно не подходит под "униформу".

2023-02-05 17:23 UTC, closed without merging