Magboots resprite
TauCetiStation/TauCetiClassic pull request #10683
Opened 2023-02-02 17:49 UTC by Deahaka

## Описание изменений
Порт с ТГ: https://github.com/tgstation/tgstation/pull/69134
Новый спрайт магнитным ботинкам, слегка подкрашенный в нашу палитру

## Почему и что этот ПР улучшит
![Pica](https://user-images.githubusercontent.com/96499407/216401589-43ef5d2b-8277-49bd-94a5-74a86463bb3b.png)
![Piuca](https://user-images.githubusercontent.com/96499407/216401614-7ed32da5-4e51-4c5a-9685-fe5109dd39b5.png)
![PICAW](https://user-images.githubusercontent.com/96499407/216401623-d23110c9-4baf-46f8-a152-0d449011492b.png)
А ещё они перестали выпирать по краям с ригов, ну это если вы замечали такое как и я.
## Авторство
[Imaginos16](https://github.com/Imaginos16) aka Positive Entropy or Mr. Entropy
## Чеинжлог
:cl: Imaginos16
- image: Респрайт магнитных ботинок

2023-02-02 17:49 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2023-02-02 18:40 UTC, Ro2tCrab commented
Тееерь это не MagBoots.
Знакомьтесь - DripBoots

2023-02-02 18:46 UTC, UDaV73rus commented
кринж

2023-02-02 18:49 UTC, TryXAH commented
антикринж

2023-02-02 19:11 UTC, KIBORG04 commented
> кринж

это аппрув?

2023-02-05 16:50 UTC, UDaV73rus requested changes
Синди не контрастная блеклость, СЕ не белый. Ну и в целом не особо интересно смотрится

2023-02-05 21:11 UTC, Deahaka commented
Ладно, может действительно могло быть лучше. Может быть найдут/нарисуют когда-нибудь в 3/4 (ну только не как на эрисе).

2023-02-05 21:11 UTC, closed without merging