Spacecash burning! Буржуи ликуют!
TauCetiStation/TauCetiClassic pull request #10692
Opened 2023-02-03 11:57 UTC by Deahaka

## Описание изменений
Теперь можно делать вот так!
![image](https://user-images.githubusercontent.com/96499407/216597445-7a2b0619-5017-4aae-bc12-92ac83249529.png)

## Почему и что этот ПР улучшит
Преставили лицо революционеров?
## Авторство

## Чеинжлог
:cl: Deahaka
- image: Добавлен спрайт горения бумажным  деньгам.
- add: Теперь можно поджигать бумажные деньги и подкуривать ними сигары.

2023-02-03 11:57 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2023-02-03 13:31 UTC, Ro2tCrab commented
Pog

2023-02-03 13:32 UTC, Ro2tCrab commented
Представьте себе священника.

2023-02-03 15:09 UTC, KIBORG04 commented on code/modules/economy/cash.dm
> +		var/mutable_appearance/I = mutable_appearance(icon, "on_fire_cash")
зачем здесть мутейбл аппиранс?

2023-02-03 20:35 UTC, LudwigVonChesterfield commented on code/modules/economy/cash.dm
> +/obj/item/weapon/spacecash/process()
а почему деньги горят вечно и не тушатся ничем

2023-02-03 20:36 UTC, Deahaka commented on code/modules/economy/cash.dm
> +/obj/item/weapon/spacecash/process()
Дешёвая бумага

2023-02-04 02:39 UTC, LudwigVonChesterfield commented on code/modules/economy/cash.dm
> +/obj/item/weapon/spacecash/process()
будешь ли ты делать чтобы деньги можно было потушить, и они сгорали со временем

2023-02-04 17:34 UTC, Deahaka commented on code/modules/economy/cash.dm
> +/obj/item/weapon/spacecash/process()
Попытаюсь всё же сделать тушение...

2023-02-05 19:49 UTC, Deahaka commented
Теперь тушится

2023-02-06 17:23 UTC, KIBORG04 commented on code/modules/economy/cash.dm
> +	if(!timer?.spent)
ЭммЭЭэээммммм, зачем

2023-02-06 17:25 UTC, KIBORG04 requested changes
п

2023-02-06 17:25 UTC, Deahaka commented on code/modules/economy/cash.dm
> +	if(!timer?.spent)
Копипаст откуда-то, если не надо то удалю

2023-02-06 17:29 UTC, KIBORG04 commented on code/modules/economy/cash.dm
> +	if(!timer?.spent)
нахуя ты копипастишь и даже не пытаешься в этом разобраться

2023-02-06 23:18 UTC, Deahaka commented on code/modules/economy/cash.dm
> +	if(!timer?.spent)
Я не нашёл прока который бы удалял таймер, но нашёл места где он удаляется, насколько я вижу, по результату на локалке. Поэтому я беру рабочий код и вставляю.
Щас пересмотрел, в билде буквально только два таких места: в удалении датума и в твоей мафии. Если достаточно просто проверить timer && !timer.spent то сделаю.

2023-02-06 23:21 UTC, KIBORG04 commented on code/modules/economy/cash.dm
> +	if(!timer?.spent)
хм, может таймер удалякт прок deltimer?

2023-02-07 17:20 UTC, Deahaka commented
Теперь deltimer удаляет таймер

2023-02-15 14:45 UTC, merged