cone
TauCetiStation/TauCetiClassic pull request #10707
Opened 2023-02-04 16:26 UTC by Deahaka

## Описание изменений
Порт с ТГ: https://github.com/tgstation/tgstation/pull/50318
Такие есть на Гамме
## Почему и что этот ПР улучшит
![0000000000000000000000000000000000](https://user-images.githubusercontent.com/96499407/216778373-2956c653-1a93-45cc-ba30-dcb9fcfd2627.png)

## Авторство
[Krysonism](https://github.com/Krysonism)
## Чеинжлог
:cl: Krysonism
- image: Респрайт предупреждающего конуса на Гамме.

2023-02-04 16:26 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2023-02-05 16:44 UTC, UDaV73rus requested changes
внизу у обводки оранжевого, странная жеванность.
Наверно сделай чтоб затененная обводка была тамже где и тень на самом конусе

2023-02-05 19:16 UTC, Deahaka commented
Подредактировано
![abob](https://user-images.githubusercontent.com/96499407/216840033-ac39d3fc-6fd2-4205-82d1-5193f2c509dd.png)

2023-02-05 19:55 UTC, Deahaka commented
Точно реди

2023-02-06 17:47 UTC, UDaV73rus approved these changes

2023-02-06 17:49 UTC, merged