респрайт АНИМЕ
TauCetiStation/TauCetiClassic pull request #10713
Opened 2023-02-05 17:21 UTC by Deahaka

## Описание изменений
Источник: https://github.com/BeeStation/BeeStation-Hornet/pull/3941
![image](https://user-images.githubusercontent.com/96499407/216834212-ed334a5b-41dc-45c4-bf4d-4cbbec80bf86.png)

## Почему и что этот ПР улучшит
![0000000000000000000000000000000000](https://user-images.githubusercontent.com/96499407/216834227-0952d0cb-c736-4702-a9d7-175f5a35e612.png)

## Авторство
[Naevii](https://github.com/Naevii)
## Чеинжлог

2023-02-05 17:21 UTC, TauKitty commented
###### Changelog status: :radio_button: No changelog

2023-02-05 17:41 UTC, arygal commented
так кнопка на аниме поломана ещё вроде

2023-02-05 17:46 UTC, Deahaka commented
На локалке работает

2023-02-06 15:46 UTC, Sakuya-Izayoi commented
пр сомнительного качества. я против всяких улучшений грифозных кнопок. спрайты мб норм, но в игре их получить нельзя никак (кто-то может поспорить что это к лучшему...).

2023-02-06 16:00 UTC, Sakuya-Izayoi commented
> вроде синее платье можно получить из ящика в театре

ну это одно, а тут три новых

2023-02-06 17:44 UTC, UDaV73rus requested changes
стремные токсичные не контрастные цвета

2023-02-08 15:32 UTC, Deahaka commented
Аниме не пройдёт! 
![image](https://user-images.githubusercontent.com/96499407/217575556-a090d12c-e5d8-417b-853e-d3c7fa3d56b4.png)

2023-02-08 15:32 UTC, closed without merging