[WiP] Gay ger counter. Счётчик Гейгера.
TauCetiStation/TauCetiClassic pull request #10722
Opened 2023-02-07 16:54 UTC by Deahaka

## Описание изменений
![000000000000141](https://user-images.githubusercontent.com/96499407/217308328-53bf96d8-edec-4c9e-a4da-2f652965d22a.png)
# Включайте звук
https://user-images.githubusercontent.com/96499407/217307600-cab83489-5a61-4b8b-b18a-ba2f22f7084e.mp4

Концепт-арт (может что-то из этого подойдёт больше?)
![011111111111111111111111111111](https://user-images.githubusercontent.com/96499407/217308891-00e11172-5ca8-47e4-9f6a-c250aafb7d49.png)

Почему WiP? Сделал только для антиматерии, а надо ещё для много чего. Но возможно подскажете идею как дописать где-то в одном месте, чтобы оно работало.
Также нужно прийти к решению какой спрайт был бы лучше.
## Почему и что этот ПР улучшит
![0000000000000000000000000000000000](https://user-images.githubusercontent.com/96499407/217307924-ae22c0db-20d3-440c-8f6b-7aa7a7787632.png)

## Авторство
Спрайты, звуки, идея
[DarkFurrSss](https://forum.taucetistation.org/u/DarkFurrSss)
Источники звуков: 
https://freesound.org/people/Benboncan/sounds/66922/
https://freesound.org/people/leonelmail/sounds/328381/
## Чеинжлог
:cl: DarkFurrSss
- add: Добавлен счётчик Гейгера

2023-02-07 16:54 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2023-02-07 16:57 UTC, TauKitty commented
Этот запрос на слияние был упомянут в **Tau Ceti Station Forum**. Там могут быть соответствующие подробности:

https://forum.taucetistation.org/t/fludilka-chast-2/28659/19350

2023-02-07 16:59 UTC, TauKitty commented
Этот запрос на слияние был упомянут в **Tau Ceti Station Forum**. Там могут быть соответствующие подробности:

https://forum.taucetistation.org/t/a-nu-navalili-fidbeka-lajki-dizlajki/37801/1

2023-02-07 17:41 UTC, TryXAH commented
ультрамегасуперхарош

2023-02-07 20:16 UTC, LudwigVonChesterfield commented
пирометр 2.0

2023-02-08 08:18 UTC, Sakuya-Izayoi commented
спрайты чето какие-то... палитра короче так себе...

2023-02-08 08:22 UTC, Deahaka commented
Если будет стоять вопрос, попробую покрасить чтобы больше было похоже на рацию

2023-02-08 19:56 UTC, Naroke commented
mine и V5 хороши, как по мне.

2023-02-10 16:07 UTC, Deahaka commented
Сделал один прок для радиации по области. Из минусов: 
* объекты не фонят, если не постоянно наносят радиацию, то есть Гейгер пиликнет один раз по максимуму и замолчит;
* я боюсь переделывать range(src, 200) с эффектами кроме радиации на этот прок + второй рейндж 200 чтобы нанести остальные эффекты. Пока оставляю там отдельно луп для гейгера (СМ при взрыве и ещё какой-то механ уничтожения артефакта)

Из плюсов: теперь большую часть накладываний радиации можно отслеживать Гейгером.

2023-02-12 06:17 UTC, WatlerJe commented
Как мне кажется, счетчик гейгера можно интегрировать в анализатор атмосферы. Это не будет плодить лишних девайсов с моно задачей и увеличивает функционал у текущих.

2023-02-24 13:01 UTC, Deahaka commented
Обновил описание и название ПРа. Теперь это, как по комментарию выше, интегрировано в анализатор атмосферы. Поменял спрайт газовому анализатору на другой.

2023-02-24 18:03 UTC, LudwigVonChesterfield commented on code/datums/weather/weather_types.dm
> +		irradiate_in_dist(get_turf(L), rand(40,70), 0)
Трумэн шоу какое-то выходит что радиация только там где есть игроки...

С другой стороны если никто не видит счетчик то есть ли но вообще..

2023-02-24 18:03 UTC, LudwigVonChesterfield commented on code/datums/weather/weather_types.dm
> +		irradiate_in_dist(get_turf(L), rand(40,70), 0)
а ещё насколько тупо выходит что если 5 человек лежат на одном турфе то они получат в 5 раз выше дозу радиации?

2023-02-24 18:05 UTC, LudwigVonChesterfield commented on code/game/machinery/teleporter.dm
> +						irradiate_in_dist(get_turf(human), rand(120 - accurate * 40, 180 - accurate * 60), 0)
опять же, почему-то то что облучился один человек телепортацией облучает всех кто был на тайле с ним..

2023-02-24 18:05 UTC, LudwigVonChesterfield commented on code/game/mecha/equipment/tools/tools.dm
> +		irradiate_in_dist(get_turf(chassis), rad_per_cycle * 3, 7)
у нас есть `world.view` вместо 7-ки можно поставить

(возможно world.view это 15, не помню)

2023-02-24 18:07 UTC, LudwigVonChesterfield commented on code/game/objects/items/devices/scanners/gas.dm
> +			analyze_gases(user.loc, user, advanced_mode)
как-то не очень интуитивно что чтобы анализатор газов (а ето было его основная задача) проанализировал газы надо:
1. включить
2. выключить нажав кнопку "Да" вместо "Нет"

2023-02-24 18:08 UTC, LudwigVonChesterfield commented
крутой ПР но то что радиация стакается на всех мобов на тайле мне не нрав

2023-03-09 22:04 UTC, volas requested changes

2023-03-09 22:04 UTC, volas commented on code/modules/supermatter/supermatter.dm
>  			l.show_message("<span class=\"warning\">You hear an uneartly ringing and notice your skin is covered in fresh radiation burns.</span>", SHOWMSG_AUDIO)
типо > 300 - волна тепла, > 500 - эти сообщения о ожогах. Будет общий для всех механ и тут лишний цикл по мобам в радиусе уберешь.

2023-03-09 22:04 UTC, volas commented on code/game/atoms_movable.dm
> +			counter.recieve_rad_signal(rad_power, distance_rad_signal)
Я не думаю, что счетчику гейгера должно быть какое-то дело до дистанции. 

+ сейчас получается, что ты учитываешь дистанцию дважды - сначала тут, сответствующе корректируя rad_power, потом еще раз в самом счетчике.

2023-03-10 21:47 UTC, Deahaka commented on code/game/atoms_movable.dm
> +			counter.recieve_rad_signal(rad_power, distance_rad_signal)
Без разницы в звуке узнать источник радиации наверное невозможно.

2023-03-13 18:49 UTC, volas commented on code/game/atoms_movable.dm
> +			counter.recieve_rad_signal(rad_power, distance_rad_signal)
разница в звуке и так будет, звук зависит от силы а сила от дистанции. И дистанция на силу влияет дважды - тут, высчитывая первый раз rad_power от дистанции, и в самом счетчике уже для звука.

2023-03-13 18:57 UTC, Deahaka commented on code/game/atoms_movable.dm
> +			counter.recieve_rad_signal(rad_power, distance_rad_signal)
Я понял что выразился немного не точно, но подумал может итак поймут. В чём загвоздка: почти все источники радиации будут выдавать максимальную частоту пиликанья у гейгометра, так как, кроме пула сингулярности, они все очень опасны. Получится так, что стояющую в техах суперматерию, которая фонит, будет невозможно обнаружить, ведь всё будет гудеть одинаково на любом расстоянии. Так как нам нужно, исходя из идеи на скрине, чтобы гейгер помогал находить источники радиации, мы добавляем ему интуитивно понятный механ разницы в громкости в зависимости не от силы радиации, а от дистанции.

Но зачем мы тогда высчитываем из рад дозы кусочек в зависимости от дистанции? Это скорее для того, чтобы игрок понимал насколько сильная доза его ждёт на каком расстоянии. Шифтклик выдаёт последнюю сохранёный сигнал.

2023-03-13 19:00 UTC, Deahaka commented on code/game/atoms_movable.dm
> +			counter.recieve_rad_signal(rad_power, distance_rad_signal)
Хотя я уже спустя столько времени не уверен что оно будет выдавать высокую частоту пиликанья, но так было когда я только начинал делать. Щас потесчу на локалке наверное

2023-03-13 19:01 UTC, volas approved these changes

2023-03-13 19:33 UTC, Deahaka commented on code/game/atoms_movable.dm
> +			counter.recieve_rad_signal(rad_power, distance_rad_signal)
Потестил щас. Вроде есть разница в ощущениях из-за звука, а вроде бы и нет. Когда сила радиации не пропорциональна дистанции, то как будто с звуком понятно что оно не прямо перед тобой находится. Но когда сила стабильно фонит "средненько", то на средней дистанции разницу громкости не ощущаешь, а как только приблизишься почти вплотную, то по ушам даст эффектно. То есть разница громкости ситуативно работает по назначению, варьирование волюма не всегда даёт нужный эффект, только когда у тебя сильный источник радиации. Но зато он даёт супер алярм когда вблизи громко трещит. Возможно стоило бы сделать градацию не по 99, 98, 95 и тд, а сразу по 10-ткам. Вблизи 100, на небольшой дистанции 80-90 и на остальных 60-70, но не знаю как это будет работать с очень сильными источниками радиации. Они будут фонить тихо, но очень интенсивно? Думаю оставлю как есть.

2023-03-14 14:07 UTC, merged

2026-08-28 04:52 UTC, volas commented on code/game/atoms_movable.dm
> +			counter.recieve_rad_signal(rad_power, distance_rad_signal)
хочу тебя всё же догнать и сказать что это та еще поебень в итоге