добавляет дереликт выживач
TauCetiStation/TauCetiClassic pull request #10739
Opened 2023-02-09 11:56 UTC by simb11

## Описание изменений
![2023 02 09-13 12 18](https://user-images.githubusercontent.com/84613249/217796796-de8f5163-c4fa-44dd-bda0-7d3216faeca5.png)
Добавляет огромную заброшенную станцию, которая состоит из 3 частей
Левая часть почти полностью уничтожена метеороидами и не только. Особой опасности там нет, как и лута. Из врагов там только карпы. Ранее там находился инженерный отсек, атмосферный, медпункт и кафетерий.

Центральная часть в меньшей степени пострадала от метеороф, в отличии вот левой, турели вокруг этой части станции не были уничтожены и вполне себе функционируют. На этой станции расположен мостик, бриг, гидропоника, кухня, дормы и крио. Здесь чуть больше полезного лута, но и проникнуть на эту часть станции намного сложнее

Правая часть почти полностью уцелела, но на ней расположился улей ксеноморфов. Эта часть состоит из РнД, оружейной, склада невероятно секретных, опасных и важных предметов. Как можно было догадаться, полезных вещей здесь предостаточно, но и врагов здесь очень много.

Спутник, особо ничего интересного, он полностью захвачен ксеноморфами, здесь же умер капитан этой станции, от него осталась лишь шляпка да карта с доступом к складку особо важных предметов, что находится в рнд. 

Немного про выживших
Появляются они в крио, их двое, старший медик и инженер, что у одного, что у второго предостаточно полезных вещей и навыков. Им не надо лезть на спутник для получения доступа ко всяким системам станции, у них изначально есть карточки с полным доступом ко всей заброшенной станции.

Ещё добавляет новый крутой еган спешл фор зис дереликт, отличается от обычного большей скорострельностью и батарейкой.
## Почему и что этот ПР улучшит
Больше разнообразного геймплея призракам и теленаучникам.
## Авторство
Ну эм это ремейк олд стейшона с билда ТГ
Спрайты егана взяты с Эриса.
## Чеинжлог
🆑 Simbaka
- add: Добавлен новый большой дереликт.

2023-02-09 11:56 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2023-02-09 12:50 UTC, Tap0r commented
Выглядит как говно, но идея супер крутая.

2023-02-09 13:07 UTC, Chip11-n commented
Стеклянный переход выглядит ну слишком плохо. Первый попавший моб туда устроит разгерму.

2023-02-09 13:08 UTC, NikMaestro commented
Трахнул бы.
Турели лютые только, даже для дереликта.

2023-02-09 13:13 UTC, Mercurialaste commented
А в чем рофл спавнить карпов вне диреликта, ставя на обшивке диреликта турели?

2023-02-09 13:18 UTC, simb11 commented
> А в чем рофл спавнить карпов вне диреликта, ставя на обшивке диреликта турели?

живые карпы есть только у левой станции, где нет турелей, рядом с остальными лежат мёртвые, типа предупреждение, чтобы любители полетать по космосу сразу понимали, что дальше турели или что-то типа того.

2023-02-09 16:11 UTC, simb11 commented
попытался сделать всё чуть более красивым, в основном покрасил плитку в многих местах и понадобавлял всякой мелочи.

2023-02-09 17:45 UTC, IlinMihail commented on code/modules/projectiles/guns/energy/nuclear.dm
> +	desc = "The latest model of energy weapons. In addition to the new design, the pistol has a new cooling system that allows you to shoot much faster, as well as a new internal battery."
new, new, new... тавтология. скажи лучше 'new, cutting edge design features improved cooling system and internal battery'

2023-02-09 17:46 UTC, IlinMihail commented on code/datums/spawners_menu/spawners.dm
> +	to_chat(H, "<B>Вы - <span class='boldwarning'>были работником передовой Космической Научной Станции Нанотразен LCR</span>, что уже как год считается уничтоженной.</B>")
а год не мало?

2023-02-09 17:47 UTC, IlinMihail commented
оч жалко что нет трагичной записочки шахтёра как в оригинальном дереликте на тг, а так классно

2023-02-09 18:04 UTC, simb11 commented on code/datums/spawners_menu/spawners.dm
> +	to_chat(H, "<B>Вы - <span class='boldwarning'>были работником передовой Космической Научной Станции Нанотразен LCR</span>, что уже как год считается уничтоженной.</B>")
мэх, не хочу делать очень старую станцию, как это сделано на тг.

2023-02-09 19:25 UTC, Deahaka commented on code/modules/skills/skillsets/roles.dm
> +/datum/skillset/survivalist_medic
Почему просто не дать макс-скилы и не париться? Или добавить скилсет нужной профы при спавне.

2023-02-09 19:25 UTC, Deahaka commented on code/datums/spawners_menu/spawners.dm
> +	desc = "Вы просыпаетесь на заброшенной станции. Адаптируйтесь, выживайте и всё такое."
Может сделать описание больше похожее на ситуацию персонажей из: [этого фильма](https://ru.wikipedia.org/wiki/Пандорум)? Вы не можете вспомнить "вашу миссию/ваше имя/ничего"? Хотя может я слишком многого хочу от этой задумки.

2023-02-09 19:38 UTC, IlinMihail commented on code/modules/projectiles/guns/energy/nuclear.dm
> +	desc = "The latest model of energy weapons. In addition to the new design, the pistol has a new cooling system that allows you to shoot much faster, as well as a new internal battery."
In addition to здесь тоже не нужен, просто 'каттинг едж дезигн феатурес бла бла бла'

2023-02-10 07:48 UTC, NikMaestro commented on code/datums/spawners_menu/spawners.dm
> +	to_chat(H, "<B>Вы - <span class='boldwarning'>были работником передовой Космической Научной Станции Нанотразен LCR</span>, что уже как год считается уничтоженной.</B>")
"Нанотразен"...

2023-02-10 12:01 UTC, simb11 commented on code/datums/spawners_menu/spawners.dm
> +	desc = "Вы просыпаетесь на заброшенной станции. Адаптируйтесь, выживайте и всё такое."
да нах
эта гост роль задумывается как простое развлечения для гостов, которые хотят постреляться с мобами/позаниматься строительством/пострадать фигней на заброшенной станции или ещё чем-то
так что вся эта фигня с провалами в памяти лишней будет

2023-02-10 12:06 UTC, simb11 commented on code/modules/skills/skillsets/roles.dm
> +/datum/skillset/survivalist_medic
Не хочу выдавать макс скиллы по причине того что эти выжившие могут полететь на исход и там уже максимальные скиллы будут выглядеть не очень красиво.
Выдавать скиллсеты сразу нескольких профессий мне кажется тож не очень красивым решением, пусть будут отдельные скиллсеты для них

2023-02-11 14:25 UTC, NikMaestro commented
А если, как защиту от грифа, поставить им лояльность? Чтобы не прилетели по приколу на станцию и не начали грифонить экипаж своим мощным...вооружением.

2023-02-14 17:51 UTC, Ro2tCrab commented
> А если, как защиту от грифа, поставить им лояльность? Чтобы не прилетели по приколу на станцию и не начали грифонить экипаж своим мощным...вооружением.

С тем же успехом любой Ассистен может грохнуть кого то с копьём.

2023-02-25 15:18 UTC, simb11 commented
всё что надо было пофиксил можно мержить

2023-03-08 08:29 UTC, volas requested changes
слишком много мобов и машинерии на дереликт, нужно очень сильно резать

даже если мобы дохлые - нужно иметь в виду, что они всё равно будут висеть в процессинге (пока мы это как-то может системно не исправим)

2023-03-08 08:29 UTC, volas commented on code/datums/spawners_menu/spawners.dm
> +	return ..()
у нас же уже где-то была подобная ролька на дереликтах? может стоит объединить под общим предком

2023-03-08 08:29 UTC, volas commented on code/game/objects/items/weapons/cards_ids.dm
> +	desc = "The old ID card, belongs to the captain of a very unlucky station named 'LCR'."
можешь переводить, тк https://github.com/TauCetiStation/TauCetiClassic/pull/10602

2023-03-08 10:45 UTC, simb11 commented on code/datums/spawners_menu/spawners.dm
> +	return ..()
та роль появляется только после того как кто-то откроет слипер-спавнер и, кроме этого, она абсолютно не привязана к новой системе спавнеров

2023-03-08 10:48 UTC, simb11 commented
> машинерии на дереликт

нужно ли удалять "пустые" нерабочие консоли и машинфреймы?

2023-03-08 11:19 UTC, simb11 commented
позаменял большинство машинерии на пустые консольки и машин фреймы, удалил часть мобов



> даже если мобы дохлые - нужно иметь в виду, что они всё равно будут висеть в процессинге (пока мы это как-то может системно не исправим)

мёртвые карпы являются айтемами
/obj/item/fish_carp, если точнее

2023-03-08 11:51 UTC, volas commented
всё равно больше 10 для потенциально не используемой за весь раунд локации имхо слишком много. Я был бы ок с максимум 2-3, может быть спавнером мобов на триггер (zone/entered, например).

2023-03-08 12:30 UTC, LudwigVonChesterfield commented
Ещё хочу напомнить что у нас есть система динамического спавна мобов в зоне которая юзается на астероиде!

2023-03-08 20:19 UTC, simb11 commented
поудалял раундстартовых живых карпов и прикрутил систему динамичного спавна

2023-03-08 20:25 UTC, LudwigVonChesterfield commented on code/game/area/space_structures_areas.dm
> +	InitSpawnArea()
не думаю что есть смысл выносить в отдельную функцию, но так красивее.

2023-03-09 05:47 UTC, volas commented
* Всё еще с десяток алиенов на карте
* По поводу машинерии - могу предложить еще изначально выключить смес-ы. Нет света - меньше процессинга. А сталкеры потом вернут.
* из-за объема возможно карта несбалансированно более вкусная для сталкеров с блюспейс телепортом, чем другие дереликты. Много компонент, некоторые продвинутые, и прочего инструмента. Я не вникал, но кому нибудь стоит посмотреть.

2023-03-09 08:27 UTC, simb11 commented
урезал количество алиенов до ровно десяти штук
батареек в АПЦ хватает только на пару минут
СМЕС теперь изначально отключен

2023-03-10 20:19 UTC, simb11 commented
ксеносы теперь появляются только после того как кто-то зайдёт на территорию дереликта

2023-03-13 18:53 UTC, volas approved these changes
Спавнеры можно потом еще доработать (они к пр-у относятся косвенно), абузы с теленаукой не критично и если всплывут - поправим.

2023-03-13 18:55 UTC, KIBORG04 commented on code/datums/spawners_menu/spawners.dm
> +	return ..()
Волес наверное про синдикатовского шпеона со станции прослушки в астеройде

2023-03-15 22:37 UTC, simb11 commented
пофиксил конфликты

2023-03-16 03:50 UTC, merged