Недотрога
TauCetiStation/TauCetiClassic pull request #10747
Opened 2023-02-11 07:43 UTC by LoTaRk-FroG

## Описание изменений
Добавлен квирк "Недотрога" за -1 очков. Если вас грабают или обнимают то ваше настроение понижается. 
## Почему и что этот ПР улучшит
#10537 
## Авторство

## Чеинжлог
:cl:
- feature: _Новый_ квирк "Недотрога"

2023-02-11 07:43 UTC, TauKitty commented
###### Changelog status: :x: Invalid changelog classes (feature)

2023-02-11 11:19 UTC, Sakuya-Izayoi commented on code/__DEFINES/traits.dm
> +#define TRAIT_HARDTOGET           "hard_to_get"
touchy

2023-02-11 11:19 UTC, Sakuya-Izayoi commented on code/datums/mood_events/generic_negative_events.dm
> +	description = "<span class='warning'>I don't like when peoples touch me!</span>"
```suggestion
	description = "<span class='warning'>I don't like it when people touch me!</span>"
```

2023-02-11 11:19 UTC, Sakuya-Izayoi commented on code/datums/mood_events/generic_negative_events.dm
> +	description = "<span class='warning'>Somebody touch me. Gross!</span>"
```suggestion
	description = "<span class='warning'>Somebody have touched me. Gross!</span>"
```

2023-02-11 11:19 UTC, Sakuya-Izayoi commented on code/modules/mob/mob_grab.dm
> +					if(mood.mood_level < MOOD_LEVEL_NEUTRAL)
тут можно тернарным оператором

2023-02-11 11:19 UTC, Sakuya-Izayoi commented on code/modules/mob/living/carbon/carbon.dm
> +						if(mood.mood_level < MOOD_LEVEL_NEUTRAL)
тут так же, вообще копипаста

2023-02-11 11:21 UTC, Sakuya-Izayoi commented
иконка спорная какая-то, по ней непонятно что она значит... можно перевернутое черное сердечко или как в аниме крестик

2023-02-11 11:55 UTC, LoTaRk-FroG commented
> иконка спорная какая-то, по ней непонятно что она значит... можно перевернутое черное сердечко или как в аниме крестик

На тг вроде такая же, либо что-то похожее.

2023-02-11 12:24 UTC, LoTaRk-FroG commented on code/modules/mob/mob_grab.dm
> +					if(mood.mood_level < MOOD_LEVEL_NEUTRAL)
`(mood.mood_level < MOOD_LEVEL_NEUTRAL) ? SEND_SIGNAL(src, COMSIG_ADD_MOOD_EVENT, "bad_hug", /datum/mood_event/very_bad_hug) : SEND_SIGNAL(src, COMSIG_ADD_MOOD_EVENT, "bad_hug", /datum/mood_event/bad_hug)` ???

2023-02-13 13:30 UTC, LudwigVonChesterfield commented on code/modules/mob/mob_grab.dm
> +					if(mood.mood_level < MOOD_LEVEL_NEUTRAL)
я думаю скорее
```
SEND_SIGNAL(src, COMSIG_ADD_MOOD_EVENT, "bad_hug", mood.mood_level < MOOD_LEVEL_NEUTRAL ? /datum/mood_event/very_bad_hug : /datum/mood_event/bad_hug)
```
(но зачем?)

2023-02-13 13:30 UTC, LudwigVonChesterfield commented on code/modules/mob/living/carbon/carbon.dm
> +						if(mood.mood_level < MOOD_LEVEL_NEUTRAL)
а куда вынести подобного рода функцию?

2023-02-14 11:16 UTC, LoTaRk-FroG commented
Теперь носитель квирка  "Дружелюбный" не будет давать бафф носителю квирка "Недотрога" как и обычные хаги. Носитель квирка "Дружелюбный" все еще будет получать бафф и сердце будет показываться вместе с ромбом.

2023-03-09 06:05 UTC, volas requested changes

2023-03-09 06:05 UTC, volas commented on code/modules/mob/living/carbon/carbon.dm
> +				if(HAS_TRAIT(src, TRAIT_HARDTOGET))
если у M есть friendly, а у src hardtoget, то мы где-то тут можем вроде лишние сигналы продублировать.

Вообще какая-то сложная цепочка, наверно можно привести в более читабельный вид и может стоит вынести в отдельную функцию.

2023-03-30 07:24 UTC, closed without merging