добавляет крутые шоковые перчатки
TauCetiStation/TauCetiClassic pull request #10744
Opened 2023-02-10 18:45 UTC by simb11

## Описание изменений
![image](https://user-images.githubusercontent.com/84613249/218159708-48adc9d8-a387-4e2e-a0bf-4771c0d33891.png)
будучи выключенными выглядят как перчатки марина 
![image](https://user-images.githubusercontent.com/84613249/218161649-6eef743e-e320-486f-9e46-393ff3754c2e.png)

добавляет в аплинк нюки и предателей шоковые перчатки, стоят они 4 телекамня, питаются от батареек и работают в двух (трёх) режимах

Будучи выключенными они просто защищают от ударов тока.

В режиме УБИТЬ они работают как боксерские перчатки, повышают урон с удара кулаком в два с половиной раза, плюсом к этому, удары наносят 15 бёрн и 10 боле урона. каждый удар тратит 500 единиц энергии. С шансом 50% удар создаст искры. Защита от тока частично теряется.

В режиме ОГЛУШИТЬ они работают как стангловсы, только в два раза мощнее. Тратится 5000 энергии за один клик. Защита от ударов тока почти полностью пропадает.

Ещё они были добавлены в набор медика, как средство защиты от всяких ассистентов без брони, и в набор за 20 ТК    "ГАДЖЕТЫ".    Вместе с перчатками там идёт батарейка на 30 тысяч единиц энергии.
## Почему и что этот ПР улучшит
Этот предмет разнообразит арсенал ядерных оперативников и предателей, что создаст большую вариативность при игре за них.
## Авторство
вдохновлялся паувер гловсами с эриса
## Чеинжлог
🆑 Simbaka
- add[link]: В аплинк предателей и ядерных оперативников были добавлены шоковые перчатки.

2023-02-10 18:45 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2023-02-10 18:47 UTC, AndroBetel commented
не нрав

2023-02-11 21:33 UTC, flying-george commented
Круто

2023-02-13 17:09 UTC, LudwigVonChesterfield commented
ураааа станы

2023-02-13 19:16 UTC, simb11 commented
> станы одним кликом

Одним кликом можно только человечков без брони оглушить, для людей в броне надо 2 или 3 нажатия.

2023-02-13 22:21 UTC, Sakuya-Izayoi requested changes

2023-02-13 22:21 UTC, Sakuya-Izayoi commented on code/modules/clothing/gloves/power_gloves.dm
> +					L.apply_effects(0,0,0,0,2,0,0,calc_power)
apply_effect(STUN, ...)

2023-02-13 22:21 UTC, Sakuya-Izayoi commented on code/modules/clothing/gloves/power_gloves.dm
> +			if(cell.charge >= cell_use)
в одну ифку?

2023-02-13 22:21 UTC, Sakuya-Izayoi commented on code/modules/clothing/gloves/power_gloves.dm
> +			cell.forceMove(get_turf(loc))
дать в руки или дропнуть

2023-02-13 22:21 UTC, Sakuya-Izayoi commented on code/modules/clothing/gloves/power_gloves.dm
> +	to_chat(user, "<span class='warning'>Not enough energy, gloves off!</span>")
```suggestion
	to_chat(user, "<span class='warning'>Not enough energy, gloves turn off!</span>")
```

2023-02-13 22:21 UTC, Sakuya-Izayoi commented on code/modules/clothing/gloves/power_gloves.dm
> +/obj/item/clothing/gloves/power/proc/turn_off_the_gloves(mob/user)
```suggestion
/obj/item/clothing/gloves/power/proc/turn_off(mob/user)
```
тут и ниже

2023-02-13 22:21 UTC, Sakuya-Izayoi commented on code/modules/clothing/gloves/power_gloves.dm
> +		to_chat(user, "Cell charge: [cell.charge].")
аджасенси чек чтобы нельзя было за три пизды увидеть заряд

2023-02-13 22:21 UTC, Sakuya-Izayoi commented on code/modules/clothing/gloves/power_gloves.dm
> +		to_chat(user, "<span class='notice'>You change the regime in power gloves. Current mode:</span> <span class='danger'>[selected_mode]</span>.")
```suggestion
		to_chat(user, "<span class='notice'>You change the power gloves mode to</span> <span class='danger'>[selected_mode]</span>.")
```

2023-02-13 22:21 UTC, Sakuya-Izayoi commented on code/modules/clothing/gloves/power_gloves.dm
> +					L.log_combat(attacker, "stungloved witht [name]")
```suggestion
					L.log_combat(attacker, "stungloved with [name]")
```

2023-02-13 22:21 UTC, Sakuya-Izayoi commented on code/modules/clothing/gloves/power_gloves.dm
> +					cell.use(cell_use)
целл.юз возвращает сколько было юзнуто энергии, тоже в ифку. + можно сделать фичу что с батарейкой где не хватает энергии на полный удар перчатка бьет слабее

2023-02-13 22:21 UTC, Sakuya-Izayoi commented on code/modules/clothing/gloves/power_gloves.dm
> +					H.apply_damage(10, HALLOSS, BP, armor_block)
здесь случай противоположный, почему бы не apply_damages(...)

2023-02-13 22:21 UTC, Sakuya-Izayoi commented on code/datums/uplinks_items.dm
> +	uplink_types = list("nuclear", "traitor")
у нюки где-то есть батарейки чтобы она могла купить перчатки без набора? ну и вообще можно хоть даже 5 тк за такой итем, но с уже всунутой батарейкой на 30к энергии

2023-02-14 13:32 UTC, simb11 commented
поправил всё что нужно было

2023-02-14 16:33 UTC, Sakuya-Izayoi commented
ну вон еще неразезолвленный конверсейшен

2023-02-14 16:35 UTC, Sakuya-Izayoi commented on code/modules/clothing/gloves/power_gloves.dm
> +	if((cell) && (cell.charge))
```suggestion
	if(cell?.charge)
```

2023-02-14 16:35 UTC, Sakuya-Izayoi commented on code/modules/clothing/gloves/power_gloves.dm
> +		if((cell) && (cell.charge >= cell_use) && (cell.use(cell_use)))
```suggestion
		if(cell && cell.charge >= cell_use && cell.use(cell_use))
```

2023-02-14 18:02 UTC, Sakuya-Izayoi approved these changes

2023-02-15 21:12 UTC, KIBORG04 commented on code/modules/clothing/gloves/power_gloves.dm
> +	return FALSE
заюзай здесь прием, как ранний возврат.

2023-02-15 21:15 UTC, Sakuya-Izayoi commented on code/modules/clothing/gloves/power_gloves.dm
> +				H.apply_damages(damage, 15, 0, 0, 0, 10, BP, armor_block)
> В режиме УБИТЬ они работают как боксерские перчатки, повышают урон с удара кулаком в два с половиной раза, плюсом к этому, удары наносят 15 бёрн и 10 боле урона. 

тут брут потерялся

2023-02-15 21:15 UTC, Sakuya-Izayoi commented on code/modules/clothing/gloves/power_gloves.dm
> +				L.apply_damage(calc_power, HALLOSS)
тут потерялся стан

2023-02-16 14:37 UTC, simb11 commented on code/modules/clothing/gloves/power_gloves.dm
> +				L.apply_damage(calc_power, HALLOSS)
оно не станит, только голоурон наносит

2023-02-16 16:16 UTC, simb11 commented on code/modules/clothing/gloves/power_gloves.dm
> +	return FALSE
вроде сделал

2023-02-16 19:20 UTC, Sakuya-Izayoi commented on code/modules/clothing/gloves/power_gloves.dm
> +		return TRUE
это ор

2023-02-16 19:20 UTC, Sakuya-Izayoi commented on code/modules/clothing/gloves/power_gloves.dm
> +		to_chat(user,"<span class='warning'>Not enough energy!</span>")
тут тоже ранний возврат. + учитывая что перчатки должны вырубаться когда не хватает на целл юз, имеет смысл не переключать режим если на него не хватает энергии

2023-02-16 19:20 UTC, Sakuya-Izayoi commented on code/modules/clothing/gloves/power_gloves.dm
> +	return TRUE
что-то из этого лишнее, + у тебя везде выше тру возвращается

2023-02-16 20:51 UTC, simb11 commented on code/modules/clothing/gloves/power_gloves.dm
> +		return TRUE
эээ я не знаю как объединить эти две проверки, когда я пытаюсь сделать что-то по типу 
if(!cell && cell.charge < cell_use) или
if((!cell) && (cell.charge < cell_use)) 
всё ломается и перчатки перестаются отключаться при отсутствии заряда в батарейке

2023-02-16 20:55 UTC, Deahaka commented on code/modules/clothing/gloves/power_gloves.dm
> +		return TRUE
Так сделай `||`

2023-02-16 21:03 UTC, Sakuya-Izayoi commented on code/modules/clothing/gloves/power_gloves.dm
> +		return TRUE
Это or стоило написать

2023-03-03 15:00 UTC, simb11 commented
можно мержить сей пр, всё готово и отлично работает

2023-03-04 22:30 UTC, KIBORG04 commented on code/modules/clothing/gloves/power_gloves.dm
> +		return
```suggestion
	if(!isliving(A))
		return FALSE
	var/mob/living/L = A
	attacker.do_attack_animation(L)
	if(!cell || cell.charge < cell_use)
		turn_off()
		return FALSE
```

2023-03-04 22:31 UTC, KIBORG04 commented on code/modules/clothing/gloves/power_gloves.dm
> +	if(selected_mode == GLOVES_MODE_KILL)
```suggestion
	else if(selected_mode == GLOVES_MODE_KILL)
```
аптимизция

2023-03-04 22:34 UTC, merged