Модуль реактора на риг теперь немного расист
TauCetiStation/TauCetiClassic pull request #10755
Opened 2023-02-12 11:59 UTC by Deahaka

## Описание изменений
Только избавились от манчера рига Осокакавима, так теперь заходит Бебен и тоже решает побегать в риге потому что он самозаряжающийся, оправдывая это тем что СПУ все равно на то что риг не для постоянного ношения.
![00000000000000000000000000000000000000](https://user-images.githubusercontent.com/96499407/218309342-9283aca8-8536-46cc-afde-ea64194f6681.png)
Что ж игроки не понимают по-хорошему, ксеновизорам насрать (я жаловался не раз на одного такого Уэйсона Болта, админам тоже насрать, давайте начнём балансировать механом.
## Почему и что этот ПР улучшит
Убирает главную причину нарушать правила (манчить) для рига Старшего Инженера и любых других, чтобы не переставляли в обычный и бегали в обход этого.
## Авторство

## Чеинжлог
:cl: Deahaka
- add: Модуль ядерного реактора для рига теперь коротит от конструкции Самоходных Позитронных Установок.

2023-02-12 11:59 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2023-02-12 12:00 UTC, TauKitty commented
Этот запрос на слияние был упомянут в **Tau Ceti Station Forum**. Там могут быть соответствующие подробности:

https://forum.taucetistation.org/t/fludilka-chast-2/28659/19583

2023-02-12 12:03 UTC, AndroBetel commented
сделай чтобы когда спу в риге они разряжались в пять раз быстрее (спу в смысле)

2023-02-12 12:19 UTC, UDaV73rus commented
> Что ж игроки не понимают по-хорошему,

в голосину

2023-02-12 13:04 UTC, Mercurialaste commented
> * Модуль ядерного реактора для рига теперь коротит от конструкции Самоходных Позитронных Установок.

XDDDDDDDDDDDDD

2023-02-12 13:07 UTC, TryXAH commented
Система, когда какой то отдельный модуль просто не работает от определенных лиц, на самом деле хуита
Гораздо лучше было бы, если реактор накидывал постоянно какой нибудь берн мелкий
Таким образом, и пользоваться вроде можно, а с другой, и как то уже и не хочется

2023-02-12 19:09 UTC, Motzord commented
if ckey=manchkin
>qdel(src)

Всепроблема решена

2023-02-12 19:16 UTC, KIBORG04 requested changes
текущая реалиализация кринж

2023-02-13 09:06 UTC, Deahaka commented
Обновлено. Теперь СПУ будут по 2% за тик разряжаться от действий электро-магнитного поля реактора.

2023-02-13 18:30 UTC, Pimap3 commented
Чекайте как смешные СПУ триторы разряжают всю станцию через одно АПЦ

2023-02-14 05:10 UTC, Deahaka commented
Ноль кринжа, даже изначальный вариант был полностью оправдан и необходим тау ките. Текущий конечно повлияет на ситуацию намного слабее, но мейнтейнерам виднее.

2023-02-15 21:06 UTC, Deahaka commented
Закрыт по причине не актуально в данный момент

2023-02-15 21:06 UTC, closed without merging