Фотки во флаффе
TauCetiStation/TauCetiClassic pull request #10751
Opened 2023-02-11 16:26 UTC by DarthSidiousPalpatine

## Описание изменений
Добавлена возможность добавлять фотографии во флафф слот.

Можно добавить иконку до 128х128 пикселей размером.
![image](https://user-images.githubusercontent.com/21008918/218269184-c0978d7a-ae3d-492e-a9e5-7d6b0da0a8cb.png)
![image](https://user-images.githubusercontent.com/21008918/218269189-97711178-6695-4891-b1ed-3350b590dbfd.png)

Из мелкого изменения - пофиксил размер окна фотографий на 12 пикселей высоты. Теперь фотография открывается без скролбара. (Когда делали фотки вообще ни о чём не думали? Это литералли изменить одно число, лол, вот это низкие стандарты раньше были, писец.)

## Почему и что этот ПР улучшит
Больше возможностей, теперь не будет кринж-медальонов на фуллтайл с лицом Трисс.

## Авторство
AndreyGysev и все все все, кто помогал в дискорде.

## Чеинжлог
 :cl:
 - rscadd: Добавлена возможность сделать флафф-фотографию.

2023-02-11 16:26 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2023-02-11 16:28 UTC, TauKitty commented
Этот запрос на слияние был упомянут в **Tau Ceti Station Forum**. Там могут быть соответствующие подробности:

https://forum.taucetistation.org/t/fludilka-chast-2/28659/19534

2023-02-11 16:28 UTC, DarthSidiousPalpatine commented
Если позволят можно расширить фотку со 128х128 до 512х512.
Но нежелательно, думаю.

2023-02-11 20:47 UTC, KIBORG04 commented on code/modules/fluff/customitems.dm
> +			item.item_state = custom_item_info.icon_state
?

2023-02-11 20:47 UTC, KIBORG04 commented on code/modules/fluff/fluffmenu.dm
> +		I.Scale(32, 32)
зачем эти скейлы?

2023-02-11 20:48 UTC, KIBORG04 commented on code/modules/fluff/customitems.dm
> +				pc.Blend(tiny_img,ICON_OVERLAY, 12, 19)
```suggestion
				ic.Blend(small_img, ICON_OVERLAY, 13, 13)
				pc.Blend(tiny_img, ICON_OVERLAY, 12, 19)
```

2023-02-12 04:28 UTC, DarthSidiousPalpatine commented on code/modules/fluff/customitems.dm
> +			item.item_state = custom_item_info.icon_state
Чтобы если ты ранее эти параметры уже установил, то они не устанавливались бы ещё раз и не сбивали всё.

2023-02-12 04:29 UTC, DarthSidiousPalpatine commented on code/modules/fluff/fluffmenu.dm
> +		I.Scale(32, 32)
Чтобы впихивать картинки больше чем 32х32 в окошко 32х32

2023-02-12 05:49 UTC, volas commented on code/modules/fluff/customitems.dm
> +			item.item_state = custom_item_info.icon_state
у шаблонных итемов могут быть дефолтные параметры, может сломаться другой флафф

2023-02-12 05:49 UTC, volas commented on code/modules/fluff/fluffmenu.dm
> +		I.Scale(32, 32)
скейл не нужен, и админам нужна возможность ревьювить оригинальное изображение

2023-02-12 05:50 UTC, volas commented on code/modules/fluff/fluffmenu.dm
> +		if(editing_item.item_type == "photo")
итем тайп можно изменить уже после заливки иконки

2023-02-12 05:51 UTC, volas commented on code/modules/fluff/fluffmenu.dm
> +		if(editing_item.item_type == "photo")
еще нужно проверять анимацию

2023-02-12 05:51 UTC, DarthSidiousPalpatine commented on code/modules/fluff/customitems.dm
> +			item.item_state = custom_item_info.icon_state
Ничего не сломается. Если у шаблонного итема есть ДЕФОЛТНЫЙ параметр, то !item.parameter не будет прокать.

2023-02-12 05:53 UTC, DarthSidiousPalpatine commented on code/modules/fluff/fluffmenu.dm
> +		I.Scale(32, 32)
А у них нет возможности скачать изображение чтоль?

2023-02-12 05:55 UTC, DarthSidiousPalpatine commented on code/modules/fluff/fluffmenu.dm
> +		if(editing_item.item_type == "photo")
Значит надо удалять иконку при изменении тайпа.

2023-02-12 06:57 UTC, DarthSidiousPalpatine commented
Починил всё что можно было починить

2023-02-12 09:48 UTC, pro100kotah commented
> Починил всё что можно было починить

Лучший. Мое уважение тебе.

2023-02-16 14:55 UTC, LudwigVonChesterfield commented on code/game/machinery/camera/camera.dm
> +	else if(istype(W, /obj/item/weapon/photo))
а почему копипастой пахнет

2023-02-16 15:09 UTC, DarthSidiousPalpatine commented on code/game/machinery/camera/camera.dm
> +	else if(istype(W, /obj/item/weapon/photo))
Потому что она и есть, но, к сожалению, одним не сделать в любом случае и придётся копипастить в любом случае, так что...

2023-02-16 15:40 UTC, LudwigVonChesterfield commented on code/game/machinery/camera/camera.dm
> +	else if(istype(W, /obj/item/weapon/photo))
определенно можно без копипаста

2023-02-18 15:40 UTC, pro100kotah commented
Когда...

2023-02-19 17:34 UTC, DarthSidiousPalpatine commented on code/game/machinery/camera/camera.dm
> +	else if(istype(W, /obj/item/weapon/photo))
Удалил это вообще, достойно отдельного ПРа.

2023-02-19 17:55 UTC, LudwigVonChesterfield commented
@volas думаю ревью на тебе потому-что помню ты выражал резкое негативное отношение к этой идее.

2023-02-22 12:03 UTC, pro100kotah commented
Ждем всем сервером добавление...

2023-02-22 12:27 UTC, KIBORG04 commented on code/modules/fluff/fluffmenu.dm
> +		I.Scale(32, 32)
есть, но они ленивые жопы

2023-02-22 12:33 UTC, DarthSidiousPalpatine commented on code/modules/fluff/fluffmenu.dm
> +		I.Scale(32, 32)
Ну и что что ленивые. Пусть качают, лол.

2023-02-23 16:28 UTC, volas commented on code/modules/fluff/fluffmenu.dm
> +		if(editing_item.item_type == "photo")
Анимацию оставишь как фичу?

2023-02-23 16:29 UTC, DarthSidiousPalpatine commented on code/modules/fluff/fluffmenu.dm
> +		if(editing_item.item_type == "photo")
Да

2023-02-23 16:29 UTC, volas commented on code/modules/fluff/fluffmenu.dm
> +		I.Scale(32, 32)
Как минимум убери скейлы, и сделай для фоток отдельное превью

2023-02-23 16:30 UTC, DarthSidiousPalpatine commented on code/modules/fluff/fluffmenu.dm
> +		I.Scale(32, 32)
писец

2023-02-23 16:33 UTC, DarthSidiousPalpatine commented on code/modules/fluff/fluffmenu.dm
> +			if(I.Width() > 128 || I.Height() > 128)
эмм, нет. Фотки могут быть любого размера от 1х1 пиксель до 128х128 пикселей.

2023-02-23 16:37 UTC, volas commented on code/modules/fluff/fluffmenu.dm
> +		if(editing_item.item_type == "photo")
Оно кажется всё равно не будет работать, а если будет - давать возможность грузить ту гифку со шреком кажется сомнительной фичей. У меня и так сомнения по поводу модерации контента фоток.

2023-02-23 16:40 UTC, DarthSidiousPalpatine commented on code/modules/fluff/fluffmenu.dm
> +		if(editing_item.item_type == "photo")
С чего бы ему не работать, боже. Оно работать будет даже если туда 4к картинку пихнуть.

2023-02-23 16:57 UTC, volas commented on code/modules/fluff/fluffmenu.dm
> +		if(editing_item.item_type == "photo")
Я не знаю, будет оно или нет, зависит от того как Byond конвертнит эту хрень, и от того, как потом IE отобразит её в браузере, будучи переименованной в png. Я не полезу проверять, как оно будет работать в этих специфичных условиях. Это не важно.

Если оно не работает - мы будем хранить лишние кадры на сервере. Если работает - игроки будут грузить фильм шрека и всем радостно показывать крутую "фотку".

2023-03-09 06:08 UTC, volas requested changes
Обсуждалось в дискорде, нужно
* желательно впилить какое-то своё рабочее превью для фоток, тк обычного флаффа не подходит (и избавиться от всех этих понатыканных ресайзов)
* лимит на вес (раз мы не можем контролировать анимацию)

2023-03-09 07:12 UTC, DarthSidiousPalpatine commented
> Обсуждалось в дискорде, нужно
> 
> * желательно впилить какое-то своё рабочее превью для фоток, тк обычного флаффа не подходит (и избавиться от всех этих понатыканных ресайзов)
> * лимит на вес (раз мы не можем контролировать анимацию)

Каким образом лимит на вес, мы не можем делать ни то ни другое.

2023-03-09 07:14 UTC, volas commented
https://www.byond.com/docs/ref/info.html#/proc/length

2023-03-09 07:17 UTC, DarthSidiousPalpatine commented
> https://www.byond.com/docs/ref/info.html#/proc/length

и в чём же оно измеряется.

2023-03-10 14:13 UTC, volas commented
в байтах

2023-03-29 14:47 UTC, DarthSidiousPalpatine commented
живи

2023-04-04 18:11 UTC, pro100kotah commented
> живи

Папаша, когда?

2023-04-05 15:22 UTC, closed without merging