Statistics research output
TauCetiStation/TauCetiClassic pull request #10778
Opened 2023-02-14 21:43 UTC by LudwigVonChesterfield

## Описание изменений

Записывает информацию обо всём произведённом на протолате в статистику.

Вы вот знаете что на них производят?! Никто не знает!!! Ну то есть все знают о пушках, секхудах, рюкзаках и апгрейдиках, но в протолате же столько вещей!!!

## Почему и что этот ПР улучшит

Поддержка https://stats.dushess.net/

2023-02-14 21:43 UTC, TauKitty commented
###### Changelog status: :radio_button: No changelog

2023-02-14 21:46 UTC, KIBORG04 commented on code/modules/research/circuitprinter.dm
> +	var/datum/rnd_queue_design/RNDD = new /datum/rnd_queue_design(D, 1, producer.name)
```suggestion
	var/datum/rnd_queue_design/RNDD = new /datum/rnd_queue_design(D, 1, producer.mind.real_name)
```
Скорее так, иначе ункновн попадет. То же и с автолатом

2023-02-14 21:46 UTC, LudwigVonChesterfield commented on code/modules/research/circuitprinter.dm
> +	var/datum/rnd_queue_design/RNDD = new /datum/rnd_queue_design(D, 1, producer.name)
а то что будет майнд гарантируется??

может producer.real_name?

2023-02-14 21:47 UTC, KIBORG04 commented on code/modules/research/circuitprinter.dm
> +	var/datum/rnd_queue_design/RNDD = new /datum/rnd_queue_design(D, 1, producer.name)
Майнд, наверное, не очень, но я просто не помню где там реал_нейм есть

2023-02-14 21:49 UTC, KIBORG04 commented on code/modules/research/protolathe.dm
> +	var/datum/rnd_queue_design/RNDD = new /datum/rnd_queue_design(D, amount, producer.name)
тоже реал_нейм

2023-02-14 21:49 UTC, KIBORG04 commented on code/modules/statistic/stat_dto.dm
> +	// float, [0.0...]
```suggestion
```

2023-02-14 21:51 UTC, LudwigVonChesterfield commented on code/modules/research/circuitprinter.dm
> +	var/datum/rnd_queue_design/RNDD = new /datum/rnd_queue_design(D, 1, producer.name)
```suggestion
	var/datum/rnd_queue_design/RNDD = new /datum/rnd_queue_design(D, 1, producer.real_name)
```

2023-02-14 21:51 UTC, LudwigVonChesterfield commented on code/modules/research/protolathe.dm
> +	var/datum/rnd_queue_design/RNDD = new /datum/rnd_queue_design(D, amount, producer.name)
```suggestion
	var/datum/rnd_queue_design/RNDD = new /datum/rnd_queue_design(D, amount, producer.real_name)
```

2023-02-14 21:51 UTC, KIBORG04 approved these changes

2023-02-15 02:08 UTC, volas requested changes
блок пр-а для обсуждения

2023-03-01 03:17 UTC, LudwigVonChesterfield commented
не пр ещё норм

2023-03-09 06:25 UTC, volas commented
Как и с #10774, считаю для раунда не актуальным и не хочу хранить этот флуд в стате раунда. В качестве глобальной статистики и отслеживания трендов фидбек лучше подойдет по моему мнению.

2023-03-09 12:56 UTC, closed without merging