предмет последнего взора в статистике
TauCetiStation/TauCetiClassic pull request #10775
Opened 2023-02-14 21:01 UTC by LudwigVonChesterfield

## Описание изменений

на что же смотрела кукла перед смертью!!!

ещё обязательно надо будет чтобы скреллы с телепатией могли эту инфу видеть тоже.

## Почему и что этот ПР улучшит

Поддержка https://stats.dushess.net/

2023-02-14 21:01 UTC, TauKitty commented
###### Changelog status: :radio_button: No changelog

2023-02-14 21:53 UTC, KIBORG04 approved these changes

2023-02-15 02:08 UTC, volas requested changes
блок пр-а для обсуждения

2023-02-15 14:31 UTC, KIBORG04 commented
ну это то можно замержить..

2023-03-01 15:03 UTC, LudwigVonChesterfield commented
Хороший ПР, смешной

2023-03-09 06:18 UTC, volas commented on code/modules/mob/mob.dm
> +	last_examined = A.name
я вижу тут вверху проверку на stat == UNCONSCIOUS, значит ли это, что дохлые всё еще могут экзамайнить?

2023-03-09 06:20 UTC, volas commented
Раз последняя фраза уже есть, последний экзамайн более-менее логичен и может быть будет интересен для статы киборга, так что я не против.

2023-03-10 04:38 UTC, LudwigVonChesterfield commented
@KIBORG04 го?

2023-03-10 14:15 UTC, volas commented on code/modules/mob/mob.dm
> +	if(stat == CONSCIOUS)
проблема с мертвыми экзамайнами касается не только твоего пр-а а возможно общая, там и сигналы отправляются и face_atom вызывается и сообщение пытается показать. И поправить возможно нужно глобально.

2023-03-10 20:36 UTC, LudwigVonChesterfield commented on code/modules/mob/mob.dm
> +	if(stat == CONSCIOUS)
предпочту чтобы статистика была корректной, а пофиксят глобально когда пофиксят... это и через год может быть и через два. :)

2023-03-11 09:53 UTC, KIBORG04 commented
Морж

2023-03-11 09:53 UTC, merged