digestion dynamics
TauCetiStation/TauCetiClassic pull request #10785
Opened 2023-02-14 23:06 UTC by LudwigVonChesterfield

## Описание изменений

Статистика о количестве потребленных реагентов куклой на момент конца раунда. См. проблему #10784 

## Почему и что этот ПР улучшит

Мы узнаем кто обжирается гиперцин и забаним мухаахахахах!

2023-02-14 23:06 UTC, TauKitty commented
###### Changelog status: :radio_button: No changelog

2023-02-14 23:36 UTC, KIBORG04 commented on code/modules/mob/mob_defines.dm
> +	var/digested
```suggestion
	var/list/digested
```

2023-02-15 02:07 UTC, volas requested changes
блок пр-а для обсуждения

2023-02-20 22:43 UTC, LudwigVonChesterfield commented
Это есть в Фидбеке и Волас обязательно когда-нибудь мне к нему даст доступ.

2023-02-20 22:43 UTC, closed without merging