emp statistics, explosion time
TauCetiStation/TauCetiClassic pull request #10786
Opened 2023-02-14 23:30 UTC by LudwigVonChesterfield

## Описание изменений

Мы узнаем про ЭМИ!!! А ещё времена взрывов.

2023-02-14 23:30 UTC, TauKitty commented
###### Changelog status: :radio_button: No changelog

2023-02-15 02:08 UTC, volas requested changes
блок пр-а для обсуждения

2023-03-01 03:17 UTC, LudwigVonChesterfield commented
не пр ещё норм

2023-03-10 14:20 UTC, volas commented on code/modules/statistic/statistics_helpers.dm
> +	stat.light_range = light_range
```suggestion
	stat.heavy_impact_range = high_range
	stat.light_impact_range = light_range
```

для совместимости, или зачем разное форматирование для эми и взрывов. Можно вообще их в одном поле хранить, просто добавить флаг тип взрыва.

2023-03-10 14:21 UTC, volas commented
взрывы уже есть, так что ок

2023-03-10 20:37 UTC, LudwigVonChesterfield commented on code/modules/statistic/statistics_helpers.dm
> +	stat.light_range = light_range
Могу хранить в таблице взрывов если попросят.

А имена полей совпадают с именами аргументов функции ЭМИ.

(Не думаю что корректно будет хранить их в одной таблице, у ЭМИ половина этих переменных даже не юзается кстати...)

2023-03-11 10:01 UTC, KIBORG04 commented on code/modules/statistic/stat_dto.dm
> +	var/occured_time
```suggestion
	var/occurred_time
```

Гугл переводчик говорит что две r
![image](https://user-images.githubusercontent.com/26389417/224478007-12b62999-b4cc-44b8-b784-bbf4fd4dc3f3.png)

2023-03-11 10:01 UTC, KIBORG04 commented on code/modules/statistic/stat_dto.dm
> +	var/occured_time
вроде две r

2023-03-11 12:25 UTC, LudwigVonChesterfield commented on code/modules/statistic/stat_dto.dm
> +	var/occured_time
```suggestion
	var/occurred_time
```

2023-03-11 12:25 UTC, LudwigVonChesterfield commented on code/modules/statistic/statistics_helpers.dm
> +	stat.occured_time = roundduration2text()
```suggestion
	stat.occurred_time = roundduration2text()
```

2023-03-11 12:25 UTC, LudwigVonChesterfield commented on code/modules/statistic/statistics_helpers.dm
> +	stat.occured_time = roundduration2text()
```suggestion
	stat.occurred_time = roundduration2text()
```

2023-03-18 23:33 UTC, LudwigVonChesterfield commented
@KIBORG04 @volas 

*нужно* ли что-то тут сделать чтобы мержить?

2023-03-19 00:12 UTC, KIBORG04 commented
Да вроде остальные стат-ПРы забракованы.. Ну и как бы, че бы и не замержить..

2023-03-19 00:24 UTC, volas commented
где-то было еще 2 пр-а, один я нашел уже замержили. Надо лейблы ставить на них

2023-03-19 15:52 UTC, KIBORG04 commented
Лан, щас морж будет, добавлю ток к себе в код приколы

2023-03-19 16:07 UTC, merged