reagent reactions!!!
TauCetiStation/TauCetiClassic pull request #10781
Opened 2023-02-14 22:05 UTC by LudwigVonChesterfield

## Описание изменений

Позволит узнать кто варит кого варят и сколько варят.

## Почему и что этот ПР улучшит

Поддержка https://stats.dushess.net/

2023-02-14 22:05 UTC, TauKitty commented
###### Changelog status: :radio_button: No changelog

2023-02-14 22:06 UTC, LudwigVonChesterfield commented on code/modules/statistic/stat_dto.dm
> +	var/seen_by
очень страшная фигня на самом деле.

2023-02-14 22:06 UTC, LudwigVonChesterfield commented on code/modules/statistic/stat_dto.dm
> +	var/seen_by
если будет очень очень страшно я буду брать только самого ближайшего видящего и будем считать что он и виновник.

2023-02-14 22:20 UTC, KIBORG04 commented on code/modules/statistic/stat_dto.dm
> +	var/seen_by
смешное же

2023-02-14 22:38 UTC, KIBORG04 commented on code/modules/statistic/stat_dto.dm
> +	var/seen_by
блин, убъет ли нас волес, если жисонки будут весить под 10 мб

2023-02-14 22:40 UTC, LudwigVonChesterfield commented on code/modules/statistic/stat_dto.dm
> +	var/seen_by
@volas убьёшь?

2023-02-14 22:40 UTC, KIBORG04 commented on code/modules/statistic/stat_dto.dm
> +	var/seen_by
пока весят в ~20кб, алиенты ~100кб

2023-02-15 02:08 UTC, volas requested changes
блок пр-а для обсуждения

2023-02-20 22:44 UTC, LudwigVonChesterfield commented
Половина этого есть в фидбеке к которому мне обязательно дадут доступ.

Та половина которой нету ну это надо ещё одну бдшку поднимать а это непосильно трудно мб если вдруг реально понадобится то обсудим ещё раз.

2023-02-20 22:44 UTC, closed without merging