Фикс бага с заказом одного и того же предмета в грузторге.
TauCetiStation/TauCetiClassic pull request #10816
Opened 2023-02-19 17:22 UTC by DarthSidiousPalpatine

## Описание изменений
Один и тот же предмет в грузторге теперь не заказать.

## Почему и что этот ПР улучшит
Фикс бага, стало лучше, урааа.

## Авторство
AndreyGysev и все все все, кто помогал в дискорде.

## Чеинжлог
 :cl:
 - bugfix: Баг с покупкой одного и того же предмета в грузторге двумя людьми пофикшен.

2023-02-19 17:22 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2023-02-19 17:24 UTC, LudwigVonChesterfield commented on code/game/objects/items/devices/PDA/PDA.dm
> +								if(NewLot && !NewLot.sold)
а что если цена лота будет выше?

2023-02-19 17:25 UTC, DarthSidiousPalpatine commented on code/game/objects/items/devices/PDA/PDA.dm
> +								if(NewLot && !NewLot.sold)
Она не будет выше, оно же по хешу берёт.

Хеш это когда цена, имя, описание и продавец - один и тот же.

2023-02-19 17:26 UTC, LudwigVonChesterfield commented on code/game/objects/items/devices/PDA/PDA.dm
> +								if(NewLot && !NewLot.sold)
Я принимаю этот ответ, но никому не мешает в будущем сделать чтобы хеш имел разную цену... Я к примеру предпочёл бы чтобы слоты группировались по типу... Как в нормальных аукционах нажимаешь "купить яблоко" и тебе показывает список яблока = цена, продавец, описание...

Короче в принципе апрувабельно, но если будет идея как элегантно решить проблему другой цену - я  разрешаю в этот ПР. условно если столько же или дешевле чем ожидалось - то можно

2023-02-19 17:26 UTC, LudwigVonChesterfield approved these changes

2023-02-19 17:27 UTC, DarthSidiousPalpatine commented on code/game/objects/items/devices/PDA/PDA.dm
> +								if(NewLot && !NewLot.sold)
В будущем когда хеш будет иметь разную цену - весь ПДА будет переписан к херам.

Компы я уже сделал у себя, они работают просто ОТЛИЧНО, осталось лишь довести их до ума и набить контентом программ-консолек и можно пда на ТГУИ компы переводить. Так что это не за горами, летом, думаю.

2023-02-19 17:54 UTC, LudwigVonChesterfield requested changes
сделай проверку на цену потому-что потом забудем.

рекомендую функцию
```
/get_lot_price
```
```
/get_lot_prepayment
```
и т.д., вероятно лоту, чтобы не копипастить логику с скидками налогами и прочим.

читая этот код не очевидно что игрок никогда не сможет купить дороже чем надо, и это потому-что это не совсем правда.

2023-02-19 17:59 UTC, DarthSidiousPalpatine commented
Окей, Окей, переделал

2023-02-19 18:19 UTC, LudwigVonChesterfield commented on code/modules/cargo/shop.dm
> +	return round((1 - global.online_shop_discount) * src.price)
```suggestion
	return round((1 - global.online_shop_discount) * price)
```

и я бы предложил функцию переименовать в get_discounted_price

2023-02-19 18:20 UTC, DarthSidiousPalpatine commented on code/modules/cargo/shop.dm
> +	return round((1 - global.online_shop_discount) * src.price)
я думаю не стоит.

2023-02-19 18:47 UTC, LudwigVonChesterfield commented on code/modules/cargo/shop.dm
> +	return round((1 - global.online_shop_discount) * src.price)
@Sakuya-Izayoi подскажи стоит ли переименовать функцию на то что она делает

2023-02-19 19:44 UTC, Sakuya-Izayoi commented on code/modules/cargo/shop.dm
> +	return round((1 - global.online_shop_discount) * src.price)
очевидно стоит

2023-02-21 16:27 UTC, LudwigVonChesterfield commented on code/modules/cargo/shop.dm
> +/datum/shop_lot/proc/get_price()
```suggestion
/datum/shop_lot/proc/get_discounted_price()
```

2023-02-21 16:28 UTC, LudwigVonChesterfield commented on code/game/objects/items/devices/PDA/PDA.dm
> +								if(NewLot && !NewLot.sold && (Lot.get_price() <= NewLot.get_price()))
```suggestion
								if(NewLot && !NewLot.sold && (Lot.get_discounted_price() <= NewLot.get_discounted_price()))
```

2023-02-21 16:28 UTC, LudwigVonChesterfield commented on code/game/objects/items/devices/PDA/PDA.dm
> +	var/discount_price = Lot.get_price()
```suggestion
	var/discount_price = Lot.get_discounted_price()
```

2023-02-21 16:28 UTC, LudwigVonChesterfield approved these changes

2023-02-22 12:26 UTC, merged