добавляет methamphetamine
TauCetiStation/TauCetiClassic pull request #10822
Opened 2023-02-20 18:41 UTC by simb11

## Описание изменений
метамфетамин является очень мощным психостимулятором-наркотиком, который сильно уменьшает время оглушения, но при неосторожном использовании может сильно уменьшить продолжительность жизни наркомана.

Имеет такой рецепт:
30 единиц синаптизина, 30 наркотиков и 30 аммиака плюс 5 форона, как катализатора, при смешивании всего этого создаётся 1 осколок мета 
![image](https://user-images.githubusercontent.com/84613249/220176224-2207e3f6-2675-4248-954f-b8115d302cfe.png)

этот осколок можно прямо в руках измелить в пыль и вдохнуть, в таком случае, в организм попадёт 15 единиц метамфетамина
кроме этого, этот осколок можно измелить в гриндере и получить 20 единиц жидкого мета.

передоз:
20 или больше юнитов

про эффекты:
Сам по себе он лишь уменьшает сонливость и время оглушения, но чем больше метамфетамина в организме, тем сильнее он действует.

## Почему и что этот ПР улучшит
То же самое, что и в прошлом ПРе.
Увеличит спрос на наркотики, что увеличит взаимодействие между химиками и прочим экипажем, ну и просто немного разнообразит игру на химике.

## Авторство

## Чеинжлог
:cl: Simbaka
- add[link]: Добавлен метамфетамин.

2023-02-20 18:41 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2023-02-20 18:44 UTC, LudwigVonChesterfield commented
Синаптизин 2.0?

2023-02-20 18:45 UTC, simb11 commented
почти

2023-02-20 18:45 UTC, LudwigVonChesterfield commented on code/modules/reagents/reagent_types/Chemistry-Toxic.dm
> +/datum/reagent/methamphetamine/on_general_digest(mob/living/M)
жаль столько наркоты и никаких визуальных эффектов интересных

2023-02-20 18:45 UTC, AndroBetel commented on code/game/objects/items/contraband.dm
> +	name = "Methamphetamine shard"
с маленькой буквы

2023-02-20 18:45 UTC, AndroBetel commented on code/modules/reagents/Chemistry-Recipes.dm
> +	name = "methamphetamine crystall"
одна L

2023-02-20 18:45 UTC, LudwigVonChesterfield commented on code/modules/reagents/reagent_types/Chemistry-Toxic.dm
> +	if(volume >= overdose)
в жидком виде не овердозиться очень легко, какие у реагента минусы?

2023-02-20 18:46 UTC, LudwigVonChesterfield requested changes
нереальная имбища без каких-либо недостатков:

дробишь в дробилке, делаешь таблетки на 10 юнитов. закидываешься только когда предыдущая кончилась

2023-02-20 18:46 UTC, simb11 commented on code/modules/reagents/reagent_types/Chemistry-Toxic.dm
> +	if(volume >= overdose)
сложный рецепт и шанс остановки сердца при 15+ юнитах

2023-02-20 18:54 UTC, simb11 commented
немного потыкал цифорки, терь оно по идее не должно быть уберштукой.

2023-02-20 18:56 UTC, TryXAH commented
Ура контрим стантувин

2023-02-20 18:59 UTC, volas commented
как минимум переименуйте, а то нас роскомнадзор закроет

2023-02-20 19:02 UTC, LudwigVonChesterfield commented on code/modules/reagents/reagent_types/Chemistry-Toxic.dm
> +	if(volume >= overdose)
можно не есть 15+ юнитов

сори, с гиперцином уже плавали - знаем

2023-02-20 19:14 UTC, Mercurialaste commented
1+

2023-02-20 19:14 UTC, LudwigVonChesterfield commented
не могу поставить апрув потому-что мне всё ещё не нравится

но считаем что "реквест ченжес я снял"

2023-02-20 19:18 UTC, Mercurialaste commented on code/modules/reagents/reagent_types/Chemistry-Toxic.dm
> +	if(volume >= overdose)
Симбака, ты же ведь и сам понимаешь, что это не сложный рецепт...

2023-02-20 19:30 UTC, Chip11-n commented on code/modules/reagents/reagent_types/Chemistry-Toxic.dm
> +	if(volume >= overdose)
Предлагаю это сделать таблеткой последнего шанса. Чем дольше в организме находится - тем сильнее побочки нарастают. И в идеале невозможность вывести без диализа. 

Или вовсе сделать зависимости. Если надо, могу подсказать на каких билдах уже реализовано оно, что бы с нуля не делать.

2023-02-20 19:36 UTC, Pivo24 commented
джессе, пора варить кристаллефрин джессе

2023-02-20 21:14 UTC, Sakuya-Izayoi reviewed
меня больше прикалывает то что сбшники за кристаллэфрин не будут сажать химиков потому что он лучше чем легальные аналоги

2023-02-20 21:44 UTC, simb11 commented
переделал, теперь эффект зависит от того, насколько долго кристаллоефрин находится в организме

2023-02-20 21:45 UTC, simb11 commented on code/modules/reagents/reagent_types/Chemistry-Toxic.dm
> +/datum/reagent/methamphetamine/on_general_digest(mob/living/M)
добавил нереальную тряску экрана, сойдёт за визуальный эффект?

2023-02-20 21:48 UTC, LudwigVonChesterfield commented on code/modules/reagents/reagent_types/Chemistry-Toxic.dm
> +	data["ticks"]++
снова стало хуже. ты же в курсе что как только реагент выводится из тела - тики сбрасываются?

ну так вот, мы вернулись к стадии где если иметь таблеточку на определенное количество единиц (надо посчитать) - ею можно без опаски закидываться и снимать себе станы.

2023-02-20 22:04 UTC, Sakuya-Izayoi commented on code/modules/reagents/reagent_types/Chemistry-Toxic.dm
> +	data["ticks"]++
ну ты до абсурда сводишь. если сделать таблетку там ну на 3 юнита, на 5, на сколько? в стане ты ее не съешь, выйдешь из стана -- она отработает и ты опять упадешь. то есть польза нивелируется таким образом

2023-02-20 22:05 UTC, Sakuya-Izayoi commented on code/modules/reagents/reagent_types/Chemistry-Toxic.dm
> +	data["ticks"]++
как вариант для баланса -- очень быстрый метаболизм, чтобы нельзя было быть забаффаным ну тупо всегда, а только перед комбатом и желательно не до его конца

2023-02-20 22:08 UTC, LudwigVonChesterfield commented on code/modules/reagents/reagent_types/Chemistry-Toxic.dm
> +	data["ticks"]++
> история балансинга гиперцина

2023-02-20 22:09 UTC, LudwigVonChesterfield commented on code/modules/reagents/reagent_types/Chemistry-Toxic.dm
> +	data["ticks"]++
и да,

> ты доводишь до абсурда

тут сейчас надо 400 тиков (13 минут) чтобы хоть какой-то негативный эффект появился.

2023-02-20 22:13 UTC, Sakuya-Izayoi commented on code/modules/reagents/reagent_types/Chemistry-Toxic.dm
> +	data["ticks"]++
я вижу 230 лайфтиков (две минуты без хвостика)

2023-02-20 22:18 UTC, simb11 commented on code/modules/reagents/reagent_types/Chemistry-Toxic.dm
> +	data["ticks"]++
уменьшил количество в тиков в два раза

2023-02-21 12:47 UTC, simb11 commented
хорошенько обдумал всё это и сам начал видеть то что я сделал второй синаптизин у которого нет побочек (если всё рассчитать и сделать таблетку с выверенным кол-вом кристаллефрина).
можно конечно абсолютно полностью переделать действие реагента, вместе с дебаффами и прочим, но тогда это будет абсолютно другой реагент

2023-02-21 12:47 UTC, closed without merging