Фиксы багов, связанных с последним изменением вендоматов, которые я не заметил когда делал ПРы.
TauCetiStation/TauCetiClassic pull request #10837
Opened 2023-02-23 09:43 UTC by DarthSidiousPalpatine

## Описание изменений
1.Вендоматы становятся полупустыми только если их возможно пополнить...
2.Вендоматы дропают рефил канистру только если она существует, если нет то дропают как раньше все предметы...
3.Для лоу попа 20% шанс у пустых ячеек на то чтобы стать не пустыми.

## Почему и что этот ПР улучшит
Фиксы багов и недоработок.

## Авторство
AndreyGysev и все все все, кто помогал в дискорде.

## Чеинжлог
 :cl:
  - bugfix: Вендоматы становятся полупустыми только если их возможно пополнить.
  - bugfix: Вендоматы дропают рефил канистру только если она существует, если нет то дропают как раньше все предметы.
  - bugfix: Для лоу попа 20% шанс у пустых ячеек на то чтобы стать не пустыми.

2023-02-23 09:43 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2023-02-23 09:43 UTC, DarthSidiousPalpatine commented
Ладно, я чёт подумал и сразу сделал.

2023-02-23 14:47 UTC, LudwigVonChesterfield commented on code/game/machinery/vending.dm
> +	else //If no canister - drop everything
мне кажется это плохая идея

какие это вендоматы теперь можно ломать ради халявы?

2023-02-23 14:47 UTC, LudwigVonChesterfield commented on code/game/machinery/vending.dm
> +				if(!amount && prob(20)) //20% that empty slot will be not empty. For very low-pop rounds.
возможно 1 предмет поставить как минимум для лоупопа, и не делать шансы

2023-02-23 14:48 UTC, DarthSidiousPalpatine commented on code/game/machinery/vending.dm
> +	else //If no canister - drop everything
Которые не имеют рефилла. Например вендоматы вирусолога там или вендомат офицеров или вендомат клоуна

2023-02-23 14:51 UTC, DarthSidiousPalpatine commented on code/game/machinery/vending.dm
> +				if(!amount && prob(20)) //20% that empty slot will be not empty. For very low-pop rounds.
с шансами достаточно, имхо, например, гидропоник выращивать сможет не все семки, если не закажет у карго.

2023-02-23 15:01 UTC, LudwigVonChesterfield requested changes
нужно добавить переменную вида
`public_facing` для вендоматов которые находятся в коридорах всяких к которым у всех есть доступ

рандомить количество вещей только у `public_facing` вендоматов (ну и учитывать рефиллы очевидно)

2023-02-23 15:25 UTC, DarthSidiousPalpatine commented
Наверное, что-то забыл и что-то не так, так что можно не ревувать.

2023-02-23 15:51 UTC, LudwigVonChesterfield commented on code/game/machinery/vending.dm
> +	var/private = FALSE
я думаю по дефолут лучше private=TRUE

потому-что я не предвижу чтобы добавляли новые вендоматы с едой, а новые вендоматы с экипировкой может быть..

2023-02-23 15:51 UTC, LudwigVonChesterfield commented on code/game/machinery/vending.dm
> +	var/private = FALSE
(мне кстати название `public_facing` больше нравилось, оно как мне кажется лучше расскрывает о чем переменная чем `private`)

Ну и стоит оставить комментарий вида
`// Whether the vending machine is privately operated, and thus must not start with a deficit of goods.`

@Sakuya-Izayoi

2023-02-23 16:32 UTC, LudwigVonChesterfield approved these changes

2023-02-24 10:16 UTC, Sakuya-Izayoi commented on code/game/machinery/vending.dm
> +	var/private = FALSE
паблик фейсинг лучше чем прайват, но я так понял что речь идет вообще о вендоматах специализированных для проф и вендоматах типо с едой и так далее. в таком случае лучше назвать соответствующе (я что байкшеддинг департмент теперь?)

2023-02-24 16:57 UTC, merged