minor_fixes fax&mine ore proccesor
TauCetiStation/TauCetiClassic pull request #10849
Opened 2023-02-24 10:42 UTC by Mercurialaste

## Описание изменений
Теперь, если нет возможности отдать карточку/бумагу в руку взаимодействующего, бумага/карточка выпадет на месте машины.
## Почему и что этот ПР улучшит
фиксит возможность кражи карт через переработчик руды шахтеров.
Изменяет фикс вороства листов бумаги от ИИ так, чтобы ИИ и борги могли доставать бумагу из факса.
## Авторство
я
## Чеинжлог
:cl:
- bugfix: ИИ и Борги больше не смогут воровать карты из шахтерского переработчика руды.
- tweak: Бумага из факса выпадает на факс если никого нет рядом или взаимодействие производится удаленно.

2023-02-24 10:42 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2023-02-24 11:07 UTC, Sakuya-Izayoi commented on code/modules/mining/machine_processing.dm
> +				inserted_id.loc = loc
```suggestion
				inserted_id.forceMove(loc)
```

2023-02-24 11:07 UTC, Sakuya-Izayoi commented on code/game/machinery/fax.dm
> +				tofax.loc = loc
```suggestion
				tofax.forceMove(loc)
```

2023-02-24 11:15 UTC, Sakuya-Izayoi commented on code/game/machinery/fax.dm
> +			if(isAI(usr) || isrobot(usr))
```suggestion
			if(issilicon(usr))
```

2023-02-24 11:15 UTC, Sakuya-Izayoi commented on code/modules/mining/machine_processing.dm
> +			if(isAI(usr) || isrobot(usr))
```suggestion
			if(issilicon(usr))
```

2023-02-24 11:15 UTC, Sakuya-Izayoi commented on code/game/machinery/fax.dm
> +			if(isAI(usr) || isrobot(usr))
наверное имеет смысл еще добавить else if !human then return тут и ниже

2023-02-24 11:17 UTC, Mercurialaste commented on code/game/machinery/fax.dm
> +			if(isAI(usr) || isrobot(usr))
на сколько я знаю, большинство мобов не могут открыть интерфейс в принципе, просто атакуя.
*(конструкты, блобернауты, слаймы и тд.)*

2023-02-24 11:18 UTC, Mercurialaste commented
br*h

2023-03-01 20:04 UTC, Deahaka requested changes
Не понятно зачем ты сделал так, чтобы борги могли воровать карточки и выкидывать бумажки с факса [Сарказм, я всё понял]. Лучше оставить как было, починив только съедание карточки проком put_in_hands()

2023-03-01 20:04 UTC, Deahaka commented on code/modules/mining/machine_processing.dm
> +				inserted_id.forceMove(loc)
```suggestion
				to_chat(usr, "<span class='warning'>You can't do it.</span>")
```

2023-03-01 20:04 UTC, Deahaka commented on code/game/machinery/fax.dm
> +				tofax.forceMove(loc)
```suggestion
				to_chat(usr, "<span class='warning'>You can't do it.</span>")
```

2023-03-01 22:32 UTC, Mercurialaste commented
текущий вариант и так решает эту проблему, без you can`t

2023-03-02 06:39 UTC, Deahaka commented
Проблем с факсом нет, там никаких багов. Проблемы с плавителем руд есть, но и они могут решаться через you can't на силикона. Зачем боргу возможность доставать чужие карточки с машины?

2023-03-02 10:04 UTC, Mercurialaste commented
> Проблем с факсом нет, там никаких багов.

Коммит Воласа 8-9 летнеей давности говорит об обратном.


> Зачем боргу возможность доставать чужие карточки с машины?

Почему бы и нет? И да, обсуждение в рнд. Когда меня размутит. :^)

2023-03-02 10:18 UTC, Deahaka commented
> Коммит Воласа 8-9 летнеей давности говорит об обратном

АХАХАХАХАХАХ. Боже если б ты не сказал я б и не увидил что волас СПЕЦИАЛЬНО ПОСТАВИЛ ЗАПРЕТ ИИ ТРОГАТЬ ФАКС. 
![00000000000000000000000000000000003](https://user-images.githubusercontent.com/96499407/222399518-f7518938-15d1-45ca-b53d-82122e726280.png)
![0000000000000000000000000000000000](https://user-images.githubusercontent.com/96499407/222400152-160386ca-78f5-4692-befe-200f9eefdb0e.png)


> Почему бы и нет?

Потому что это не делает игру лучше, а даёт возможности мудакам мудачить.

2023-03-09 01:07 UTC, LudwigVonChesterfield commented on code/modules/mining/machine_processing.dm
> +			if(issilicon(usr))
было бы круто это интегрировать с is_in_interaction_vicinity чтобы была поддержка будущих Тихеон и телекинетиков в целом

2023-03-20 09:33 UTC, volas commented
Я не против дать роботам, но ИИ в прошлом обычно использовал для троллинга. Учитывая, что он всё равно не может прийти в отдел и поднять эту бумажку, ему это явно не требуется.

2023-04-10 13:42 UTC, closed without merging