Добавлен рюкзак и куртка каргонца
TauCetiStation/TauCetiClassic pull request #10856
Opened 2023-02-25 09:07 UTC by DarthSidiousPalpatine

## Описание изменений
![image](https://user-images.githubusercontent.com/21008918/221348592-e9c098d3-3cbc-4b7e-92d7-a2c82672bfca.png)![image](https://user-images.githubusercontent.com/21008918/221348594-180fd300-d766-4f9c-91fc-fadbce6f267c.png)![image](https://user-images.githubusercontent.com/21008918/221348595-7b2b0e67-4727-4649-a8f3-149ce472aa5d.png)![image](https://user-images.githubusercontent.com/21008918/221348603-fdfa6ac0-4b32-4ab3-ae10-8691cd307d0b.png)![image](https://user-images.githubusercontent.com/21008918/221348611-1cca5d6d-5a3f-4aa7-9a48-a658cc96edb1.png)![image](https://user-images.githubusercontent.com/21008918/221348617-44918c5f-a794-4119-a792-5cc41f28593e.png)![image](https://user-images.githubusercontent.com/21008918/221348619-95797b66-2a35-49b6-b15a-1900bfab37b4.png)![image](https://user-images.githubusercontent.com/21008918/221348629-d165256a-07ea-4e9a-bc80-4e77d1b3ed35.png)![image](https://user-images.githubusercontent.com/21008918/221348637-b1ac3a45-d6e7-4beb-8655-1cfe4c78dd99.png)![image](https://user-images.githubusercontent.com/21008918/221348699-b7c7428a-82b6-49dc-afed-b7d321600438.png)

## Почему и что этот ПР улучшит
Брендовая куртка с капюшоном для доставщиков Грузторг-Еды
Удобный рюкзак для ношения 10-и посылок.

## Авторство
AndreyGysev и все все все, кто помогал в дискорде.

## Чеинжлог
 :cl: 
  - rscadd: Добавлена куртка с капюшоном и рюкзак доставщика в шкафы грузчиков.

2023-02-25 09:07 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2023-02-26 01:12 UTC, LudwigVonChesterfield commented on code/game/objects/items/weapons/storage/backpack.dm
> +	can_hold = list(/obj/item/smallDelivery, /obj/item/weapon/storage/box)
> /obj/item/weapon/storage/box

Эээ?

Если сюда кладутся посылки ГрузТорга, то это можно абузить следующим образом:
Ставишь посылке цену 0
Кладёшь сюда, покупаешь
Достаёшь - подтверждаешь доставку

Таким образом имеешь рюкзак на 14 любых вещей в билде.

Можно запретить продавать вещи в ГрузТорге за бесплатно.

2023-02-26 01:13 UTC, LudwigVonChesterfield commented on code/modules/clothing/head/jobs.dm
> +/obj/item/clothing/head/cargo_hood
капюшон без функционала очень грустно

2023-02-26 07:24 UTC, DarthSidiousPalpatine commented on code/modules/clothing/head/jobs.dm
> +/obj/item/clothing/head/cargo_hood
а какой должен быть функционал?

2023-02-26 07:26 UTC, DarthSidiousPalpatine commented on code/game/objects/items/weapons/storage/backpack.dm
> +	can_hold = list(/obj/item/smallDelivery, /obj/item/weapon/storage/box)
Сюда кладутся вообще любые посылки.
И коробки.

Я вообще хотел максимум слотов 10, но интерфейс у storage - говно, так что там только кратное 7 ставить можно.
А просто 7 слотов это как-то мало, наверн, хз...

2023-02-26 12:38 UTC, Sakuya-Izayoi commented on code/game/objects/items/weapons/storage/backpack.dm
> +	desc = "A bag capable of holding 10 parcels for delivery."
```suggestion
	desc = "A bag capable of holding 14 parcels for delivery."
```

2023-03-09 07:28 UTC, DarthSidiousPalpatine commented
Пофиксил конфликт иконок.

2023-03-10 04:41 UTC, LudwigVonChesterfield commented
если убрать плащ не надо будет его респрайтить когда спрайтдеп скажет что плохо

2023-03-10 04:41 UTC, LudwigVonChesterfield commented on code/modules/clothing/head/jobs.dm
> +/obj/item/clothing/head/cargo_hood
очевидно чтобы плащ ускорял тебя если на тебе рюкзак доставщика. пепега

2023-03-10 04:42 UTC, LudwigVonChesterfield commented on code/game/objects/items/weapons/storage/backpack.dm
> +	can_hold = list(/obj/item/smallDelivery, /obj/item/weapon/storage/box)
в данный момент крайне абузабельно

2023-03-10 04:49 UTC, LudwigVonChesterfield commented on code/modules/clothing/head/jobs.dm
> +/obj/item/clothing/head/cargo_hood
можно попробовать выдумать какие-то интеграции с ГрузТоргом ещё...

2023-03-10 07:51 UTC, UDaV73rus requested changes
куртка пцц, сумку как кодерспрайт можно стерпеть

2023-03-29 14:46 UTC, DarthSidiousPalpatine commented
живи

2023-04-01 01:41 UTC, LudwigVonChesterfield commented
пожалуйста не некропость пр который не доделал... тебе уже сказали что с курткой ето мержить не будут пока её не перерисуешь, и у тебя два решения:
- убрать куртку
- перерисовать куртку

2023-04-05 14:43 UTC, closed without merging