[DNM] Replicators
TauCetiStation/TauCetiClassic pull request #10868
Opened 2023-02-26 01:01 UTC by LudwigVonChesterfield

## Описание изменений

Режим Репликаторы. Уже играбелен, и даже со спрайтами, но можно лучше!

Суть: Помесь алиена и блобов, рой роботов-коммунистов переоборудывает станцию на более эффективный манер! Лишь чтобы отожраться и улететь в глубокий космос...

**УПРАВЛЕНИЕ**

Ctrl-клик по другому дрону - переключитья на управление им.

Граб клик - режим "авторазборки", разбирает всё "не критическое" на тайле.
Клик любым другим режимом - попытаться разобрать вещь, даже если это сделает тебе хуже (поломка АПЦ, труб).
Хелп клик по голо-стене в режиме постройки подпространственных коридоров - строит коридор поверх неё, так же можно в неё просто врезаться.

Харм - боевой режим. Клик вдаль стреляет слабеньким лазером который проходит через других дронов. Если встать на тайл с дроном, он переключится в боевой режим. Дроны в боевом режиме повторяют ваше движение и атаки.

Может лазить по вентам.
Может смываться в мусорку как мейнтененс дрон. Если мусорки нет - достаточно стоять над trunk-ом.

*help в чат - позвать роботов вокруг помогать делать действие.

**КНОПКИ**

Replicate - делает ещё одного репликатора. Максимальное количество репликаторов в Рое ограничено "Пропускной способностью"(Bandwidth). Пропускная способность повышается отправляя ресурсы "домой" порталами - "Bluespace Transponder"

Construct barricade - Ставит ломаемую барикаду через которую могут ходить дроны, но не кто-либо ещё.

Spawn trap - Ставит станящую-шокирующую мину.

Emit - строит портал(Bluespace Transponder), отправляющий ресурсы Роя "домой". Набрав определенную сумму Рой повысит максимальное количество репликаторов. Порталы жрут очень много электричества! Строить можно каждых 10 тайлов.

Construct Generator - собирает генератор, к примеру для запитки портала. Ставить нужно поверх проводов.

Toggle Web Construction - включает режим постройки подпространственных коридоров. В коридоры можно зайти из любого портала. Если коридор проложен поверх стены - будучи в коридоре можно через неё пройти.

Idle transfer - Вселяет в любого неактивного дрона.

Area transfer - Вселяет в дрона без игрока в выбранной вами зоне.

**МЕХАНИКИ**

Генераторы можно строить только на активированных узлах.

Активировать узлы можно пройдясь по ним находясь в блюспейс туннеле.

Если зайти в неактивный (чёрный) портал - вы будете жертвовать собой чтобы поддерживать его временно открытым.

**ПРОТИВОДЕЙСТВИЕ**

Форсфилд полы и Стабилизационные поля разбирать отвёрткой (не спрашивайте)
Поверх форсфилд пола можно ставить плитку.

Разбирая тайл с узлом - уничтожаете узел.

Темка на форуме:
https://forum.taucetistation.org/t/rezhim-replikatory/38118

## Почему и что этот ПР улучшит

Новый режим игры урааа!!!

## Авторство

Кодер, дизайнер, идея - Luduk
Спрайты - взяты с Swarmers с /tg/station (сами свормеры там уже выпилены)
Спрайт финальной заставки - Artbsd, AndroBetel
Музыка: Буран - Воскрешение (https://soundcloud.com/buran_sw/nqf4tpcdcs4i)

## Чеинжлог
:cl: Luduk
- rscadd[link]: Новый режим: "Репликаторы"!

2023-02-26 01:01 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2023-02-26 01:03 UTC, LudwigVonChesterfield commented on code/_onclick/click.dm
> +		if(dx > 0)	src.set_dir(EAST)
здесь фикс того что репликатор без игрока при вызове face_atom рантаймит

2023-02-26 01:03 UTC, LudwigVonChesterfield commented on code/_onclick/click.dm
> +		LE.Fire(A, src, params)
здесь фикс того чтоглаза стреляют в одну точку

2023-02-26 01:04 UTC, LudwigVonChesterfield commented on code/datums/keybinding/carbon.dm
> -/datum/keybinding/carbon/select_help_intent
здесь фикс того что у симплмобов есть интенты но нет хоткеев

2023-02-26 01:04 UTC, LudwigVonChesterfield commented on code/datums/wires/airlock.dm
> +					if(usr)
здесь фикс того что если сломать шлюз без юзера будет рантайм

2023-02-26 01:05 UTC, LudwigVonChesterfield commented on code/game/machinery/cell_charger.dm
> +/obj/machinery/cell_charger/deconstruct(disassembled = TRUE)
здесь фикс того что если по имени передавать именной аргумент то возникнет рантайм

2023-02-26 01:06 UTC, LudwigVonChesterfield commented on code/game/objects/effects/anomalies.dm
> +	var/freq = rand(1200, 1599)
здесь фикс бага о котором уже и позабыли...

суть: в atom_init /signaler-а есть таймер на установку частоты, он устанавливает её на значение frequency сигналера в момент его создания

в итоге все аномалии всегда имели частоту 145.7

2023-02-26 01:06 UTC, LudwigVonChesterfield commented on code/game/objects/effects/decals/Cleanable/robots.dm
> +	base_icon = 'icons/mob/robots.dmi'
здесь фикс супер старого бага который уже даже стал лором

гибсы роботов юзали человеческие спрайты потому-что в update_icon `icon = base_icon`

правда с этим фиксом робогибсы полностью черные, потому-что "цвет" "крови" выбирали так чтобы скрыть оплошность того что кишки юзаются человеческие)

2023-02-26 01:09 UTC, LudwigVonChesterfield commented
ПР в драфте потому-что я ещё хочу дотестить режим, допилить недопиленное, запилить другие спрайты.

Но если есть какие-то большие дизайн-проблемы с кодом, я бы предпочёл их знать заранее, чтобы эмоционально подготовиться и пофиксить!

2023-02-26 12:56 UTC, KIBORG04 commented on code/game/gamemodes/factions/replicators.dm
> +	// Win condition is launching 10 replicators.
```suggestion
	// Win condition is launching 20 replicators.
```

2023-02-26 12:59 UTC, KIBORG04 commented on code/game/gamemodes/roles/replicator.dm
> +/datum/role/replicator/printplayerwithicon(datum/mind/M)
Обычно для таких целей переопределяется GetScoreboard

2023-02-26 23:04 UTC, volas commented on code/modules/client/preferences_savefile.dm
> +#define SAVEFILE_VERSION_SPECIAL_ROLES 41 // if you change any values in global.special_roles_ignore_question
изменения любой из 3-х переменных подразумевает, что ты и SAVEFILE_VERSION_MAX бампнешь

2023-02-27 00:22 UTC, LudwigVonChesterfield commented on code/datums/elements/bluespace_move.dm
> +	src.prev_see_invisible = prev_see_invisible
Сейчас есть супер мерзкий баг с очками ночного зрения который сбрасывает эту переменную.

У меня 0 идей как без глобального рефактора решить эту проблему...

2023-02-27 05:09 UTC, LudwigVonChesterfield commented on code/modules/replicators/replicators.dm
> +		qdel(old_mind_idk_anymore)
@KIBORG04 

Мне нужна помощь я не знаю что происходит.

Когда гостаешься - у тебя новый майнд, который не содержит антага. Мне надо чтобы 1 роль = 1 сикей = 1 майнд.

2023-02-27 05:10 UTC, LudwigVonChesterfield commented on code/modules/replicators/replicators.dm
> +		qdel(old_mind_idk_anymore)
Если не будет нормальных идей как это сделать, я вернусь к старой идее хранить ассоциации с сикеями у Фракции, но может вынесу все данные в отдельный датум.

Потому-что то что тут происходит сейчас клоунада какая-то, особенно в купе с `get_member_by_ckey`

2023-02-28 04:53 UTC, LudwigVonChesterfield commented on code/modules/client/preferences_savefile.dm
> +#define SAVEFILE_VERSION_MAX 42
Внимание!

Если этот ПР ТМ-ить но не принимать, нужно что-то думать с преференсами.

@volas говорил что в случае если ПР не примется нужно будет как-то дебампать версию у игроков.

2023-02-28 04:53 UTC, LudwigVonChesterfield commented on code/modules/mob/living/simple_animal/simple_animal.dm
> +	else
Здесь вторая половина того что симпл мобы засыпают но не просыпаются

2023-02-28 13:50 UTC, Sakuya-Izayoi commented on code/__DEFINES/gamemodes.dm
> +#define F_REPLICATORS           "Replicators"
```suggestion
#define F_ZOMBIES            "Zobmies"
#define F_REPLICATORS        "Replicators"
```

2023-02-28 13:50 UTC, Sakuya-Izayoi commented on code/__DEFINES/status_effects.dm
> +#define STATUS_EFFECT_SWARMS_GIFT /datum/status_effect/swarm_gift
```suggestion
#define STATUS_EFFECT_SWARMS_GIFT /datum/status_effect/swarm_gift
```

2023-02-28 13:50 UTC, Sakuya-Izayoi commented on code/datums/elements/bluespace_move.dm
> +	src.prev_see_invisible = prev_see_invisible
как вариант -- повесить трейт, и где-то в update_sight его чекать?

2023-02-28 13:50 UTC, Sakuya-Izayoi commented on code/datums/elements/bluespace_move.dm
> +		return COMPONENT_CLIENTMOB_BLOCK_MOVE
насколько сложно таким же способом запретить двигаться при постройке коридора туда куда нельзя поставить коридор?

2023-02-28 14:08 UTC, kalazus commented on code/datums/elements/bluespace_move.dm
> +		return COMPONENT_CLIENTMOB_BLOCK_MOVE
А чем не угодило COMSIG_MOVABLE_PRE_MOVE? Типо, диагональный дир пропускать, остальные проверять. Максимум может быть проблема в отсутвии / слишком большом кол-ве сообщений.

2023-02-28 14:47 UTC, LudwigVonChesterfield commented on code/datums/elements/bluespace_move.dm
> +	src.prev_see_invisible = prev_see_invisible
если я пофикшу один баг такого рода то меня заставят фиксить тысячи их!

стелс костюмы воксов, ночное видение, абилки генок... !!!

2023-02-28 14:48 UTC, LudwigVonChesterfield commented on code/datums/elements/bluespace_move.dm
> +		return COMPONENT_CLIENTMOB_BLOCK_MOVE
На Волке уже запрещает

2023-02-28 14:49 UTC, LudwigVonChesterfield commented on code/datums/elements/bluespace_move.dm
> +		return COMPONENT_CLIENTMOB_BLOCK_MOVE
PRE_MOVE сделал бы что нельзя выпихнуть из коридора, из коридора нельзя добровольно выйти, но можно быть выпихнутым.

2023-02-28 18:41 UTC, KIBORG04 commented on code/game/gamemodes/roles/replicator.dm
> +	antag_hud_name = "hudalien"
Стоит сделать хотя бы свои дефайны и названия для худа

2023-02-28 18:51 UTC, KIBORG04 commented on code/modules/replicators/replicator_disintegration.dm
> +/mob/living/simple_animal/replicator/proc/is_disintegratable(atom/A, alert=FALSE)
Как-то странно, что это функция репликатора, где от репликатора особо ничего и нет. Мб переименовать в какой-то can_disintegreate .

2023-02-28 18:53 UTC, KIBORG04 commented on code/modules/replicators/replicator_disintegration.dm
> +/mob/living/simple_animal/replicator/proc/is_auto_disintegratable(atom/A)
тут тоже can же лучше звучит, чем Is

2023-02-28 19:04 UTC, KIBORG04 commented on code/modules/replicators/replicators.dm
> +		var/datum/faction/replicators/FR = get_or_create_replicators_faction()
У рольки (или у фракции) есть своя функция, чтобы срать в Stat(). Мб туда этот код положить

2023-02-28 19:06 UTC, KIBORG04 commented on code/modules/replicators/replicators.dm
> +	var/list/pos_replicators = list() + global.alive_replicators
```suggestion
	var/list/pos_replicators = global.alive_replicators.Copy()
```
Хз че быстрее, но так базированнее

2023-02-28 19:06 UTC, LudwigVonChesterfield commented on code/modules/replicators/replicators.dm
> +		var/datum/faction/replicators/FR = get_or_create_replicators_faction()
есть ли принципиальная разница куда класть?

типо если будет у рольки то мобы без игрока не будут рефрешить себе статус?

2023-02-28 19:08 UTC, KIBORG04 commented on code/modules/replicators/replicators.dm
> +		var/datum/faction/replicators/FR = get_or_create_replicators_faction()
мобы без игрока и так не должны, но теперь можно будет дать рольку репликатора таяре и таяра будет видить цифорки!

2023-02-28 19:09 UTC, KIBORG04 commented on code/modules/replicators/replicators_spawners.dm
> +	// TO-DO: check if guy is banned from Replicators.
Это чекается не здесь, а в специальном листе у /spawner . Вроде `ranks` называется

2023-02-28 19:09 UTC, KIBORG04 reviewed
Ладно посмотрел

2023-03-01 02:18 UTC, LudwigVonChesterfield commented on code/modules/client/preferences_savefile.dm
> +#define SAVEFILE_VERSION_MAX 42
Disregard this comment

Киборч подсказал что не надо бампать версию сейвфайла вовсе!

2023-03-02 18:22 UTC, Chip11-n commented on code/game/gamemodes/factions/replicators.dm
> +	for(var/mob/M in player_list)
```suggestion
	for(var/mob/M as anything in global.player_list)
```
Плееры разве могут быть не-мобами?

2023-03-02 18:23 UTC, Chip11-n commented on code/game/gamemodes/factions/replicators.dm
> +	for(var/mob/M in player_list)
```suggestion
	for(var/mob/M as anything in global.player_list)
```

2023-03-02 18:24 UTC, Chip11-n commented on code/game/gamemodes/factions/replicators.dm
> +	for(var/turf/other as anything in RANGE_TURFS(80, center))
Просто хочу привлечь внимание. Выглядит очень страшно с ренжой 80 и слипами.

2023-03-02 18:40 UTC, LudwigVonChesterfield commented on code/game/gamemodes/factions/replicators.dm
> +	for(var/turf/other as anything in RANGE_TURFS(80, center))
нормально работает, тем более это конец раунда, и это происходит пока игроки смотрят титры.

2023-03-02 18:40 UTC, LudwigVonChesterfield commented on code/game/gamemodes/factions/replicators.dm
> +	for(var/mob/M in player_list)
могут быть ещё нуллом если мне память не изменяет )

@KIBORG04

2023-03-02 19:12 UTC, Ro2tCrab commented
> Ставлю на второй для тестов.

Чистым рандомом падать будет?

2023-03-02 20:54 UTC, Deahaka commented on code/game/gamemodes/modesbundle.dm
> +	black_types = subtypesof(/datum/game_mode/mix) + list(/datum/game_mode/extended, /datum/game_mode/malfunction) - list(/datum/game_mode/replicators)
```suggestion
	black_types = subtypesof(/datum/game_mode/mix) + list(/datum/game_mode/extended, /datum/game_mode/malfunction, /datum/game_mode/replicators)
```
Тебе ж выключить надо, да?

2023-03-02 22:24 UTC, KIBORG04 commented on code/game/gamemodes/modesbundle.dm
> +		// /datum/game_mode/replicators,
Поставил бы просто probability = 0

2023-03-02 23:17 UTC, LudwigVonChesterfield commented on code/game/gamemodes/modesbundle.dm
> +		// /datum/game_mode/replicators,
не вижу разницы если потом все равно расскоментим

2023-03-03 11:57 UTC, Sakuya-Izayoi commented on code/modules/replicators/replicator_regeneration.dm
> +	return O.max_integrity - O.atom_integrity
```suggestion
	return O.max_integrity - O.get_integrity()
```

2023-03-03 12:02 UTC, Sakuya-Izayoi commented on code/modules/replicators/replicator_regeneration.dm
> +	return O.max_integrity - O.atom_integrity
это коммитнуть и обновить ТМ на сервере, там люди страдают от бага который парой коммитов выше пофикшен по идее

2023-03-13 21:19 UTC, LudwigVonChesterfield commented
ладно, можно ревьювить и мержить, я устал уже это кодить... режим играбелен и даже вроде не в одни ворота.

2023-03-17 07:23 UTC, volas requested changes
я не разбираюсь в репликантах, просто пробежался по коду

2023-03-17 07:23 UTC, volas commented on code/modules/replicators/replicator_infrastructure.dm
> +	// to-do: sound
такие туду лучше дописать, что именно требуется, или вовсе убрать перед мержем

2023-03-17 07:23 UTC, volas commented on code/modules/replicators/replicators.dm
> +	while(length(pos_replicators))
это тоже можно было бы просто на for in заменить

2023-03-17 07:26 UTC, volas commented on code/modules/admin/topic.dm
> +		jobs += "</tr><tr align='center'>" //Breaking it up so it fits nicer on the screen every 5 entries
хотя не, всё ок должно быть, отбой

2023-03-17 15:59 UTC, volas commented on code/modules/replicators/replicator_communication.dm
> +		"ебл" = "реплик",
типо еб[ауоиеыёнл] = 

ниже с ху[йиеё...] примерно так же

коверканья слов вроде "дибил" я бы вообще не включал в замену - ты их все не поймаешь

2023-03-17 17:08 UTC, LudwigVonChesterfield commented on code/game/gamemodes/game_mode.dm
> -		if (F.members.len > 0)
Как мне хендлить что у репликаторов роль удаляется когда ты умираешь из репликатора, но фракция должна остаться до конца игры?

2023-03-17 17:11 UTC, volas commented on code/game/gamemodes/game_mode.dm
> -		if (F.members.len > 0)
у других антагов ведь роль остается, даже если тело уничтожено, может и тут так сделать?

Если нет - сделай флаг фракции "выводить всегда".

2023-03-17 17:13 UTC, LudwigVonChesterfield commented on code/modules/replicators/replicator_disintegration.dm
> +		return FALSE
Перестал проверять этот флаг, вернул мехам флаг

2023-03-17 17:14 UTC, LudwigVonChesterfield commented on code/modules/replicators/replicator_infrastructure.dm
> +	// to-do: sound
это я себе расставлял что мне тут нужен другой звук крутой какой-то.

дописать точно не выйдет, я думаю потенциал нашего билда иссяк в плане реюзания звуков... а у я уже устал топтаться с этим режимом и искать что-то ещё для него.

я бы предпочёл оставить для будущих поколений метку что там нужен какой-то уникальный звук. мне переписать комментарий на что-то типо`// to-do: add a sound here. something fsssshwoooyhyhyhyhy like`

2023-03-17 17:15 UTC, LudwigVonChesterfield commented on code/modules/replicators/replicators.dm
> +	while(length(pos_replicators))
тогда тебя бы телепортировало бы в первого существующего репликатора вместо случайного существующего

2023-03-17 17:15 UTC, volas commented on code/modules/replicators/replicator_infrastructure.dm
> +	// to-do: sound
да, было бы ок

2023-03-17 17:17 UTC, LudwigVonChesterfield commented on code/modules/replicators/replicator_disintegration.dm
> +	while(!is_busy() && do_after(src, 1, target=src, progress=FALSE))
цикл по contents точно не подойдёт

смысл граб-клика разбирать на тайле пока хоть что-то разбирается, хоть что-то может появиться в результате предыдущего разбора

если убрать эут фичу (заменив на "in contents") то играть будет очень-очень не приятно.

в теории можно как-то заменить на какую-то обработку в Life.

как компромисс я могу поставить лимит в 100 разборов на тайл чтобы ты не переживал, сойдет?

2023-03-17 17:19 UTC, LudwigVonChesterfield commented on code/modules/replicators/replicators.dm
> +			to_chat(R, "<span class='warning'>Negative: Unit is affected by another Presence.</span>")
:woozy_face: 

честно не хочу думать что замена не client может сломать. как к примеру обрабатывать то что логаутнутый зайдёт в игре когда кто-то  законтроллил реплика логаутнутого? а так и законтроллить не сможешь, только пихнуть в космос/разобрать смешными методами...

2023-03-17 17:22 UTC, LudwigVonChesterfield commented on code/modules/mob/mob_movement.dm
> +			return
мне опять же лень думать почему когда я лепил сигнал сюда я поступил с `moving` именно так как поступил. эта функция дублирует поведение сигнала - после всех возможных клиентских проверок на движение, спросить у моба или он позволяет двигаться клиенту. в этом по-крайней мере задумка прока

2023-03-17 17:24 UTC, volas commented on code/modules/replicators/replicator_disintegration.dm
> +	while(!is_busy() && do_after(src, 1, target=src, progress=FALSE))
мне кажется, бьенд хандлит изменения листа в for(in contents), т.е. пикает из него пока он не опустеет. По крайней мере, я не помню каких-то проблем.

2023-03-17 17:30 UTC, volas commented on code/modules/mob/mob_movement.dm
> +			return
сигналом тогда было бы понятнее

2023-03-17 18:44 UTC, LudwigVonChesterfield commented on code/modules/replicators/replicator_communication.dm
> +			message_close_tags = "</b>[message_close_tags]"
Можно, но разве то что ты написал читаемей чем то что сейчас?

2023-03-17 18:56 UTC, volas commented on code/modules/replicators/replicator_communication.dm
> +			message_close_tags = "</b>[message_close_tags]"
как минимум без лишних тегов/переменных, опционально можешь разбить
```
var/msg_class = "message replicator"
if(announcer && get_dist(announcer, M) < 7))
	msg_class = " bold"
msg = "<span class='[msg_class]' style='font-size: [font_size]'>"
...
```

2023-03-17 21:05 UTC, volas commented on code/modules/mob/mob_movement.dm
> +			// Someone please investigate why we can't do moving = TRUE *after* this check. ~Luduk
я думал, мы друг друга поняли, а теперь еще непонятнее. Сигнал связанный с проком переехал из этого прока в какую-то странную функцию.

Почему не оставить тут сигнал как и было, и не подписать моба на него с ``can_intentionally_move``?

2023-03-17 21:17 UTC, volas commented on code/modules/replicators/replicator_communication.dm
> +			"<font size='[font_size]'>[speaker_name] [channel] announces, <span class='[message_span_class]'>\"[message]\"</span>[jump_button]</font>",
>  refactor that imho looks worse but I don't really wanna argue with Volas 

это можно было еще прихорошить, я предлагал форматировать сообщение до send_to_chat например. Но я тиран и ничего не понимаю, ладно.

2023-03-17 21:40 UTC, LudwigVonChesterfield commented on code/modules/replicators/replicator_communication.dm
> +			"<font size='[font_size]'>[speaker_name] [channel] announces, <span class='[message_span_class]'>\"[message]\"</span>[jump_button]</font>",
это бы имело смысл если бы у нас не было кастомизаций в зависимости от типа наблюдателя? там же кнопочки добавляются для гостов, репликов, в зависимости от дистанции класс меняетс

2023-03-17 21:54 UTC, volas approved these changes

2023-03-18 10:02 UTC, merged