Переделка денег часть 1.
TauCetiStation/TauCetiClassic pull request #10873
Opened 2023-02-26 12:27 UTC by DarthSidiousPalpatine

## Описание изменений
И снова седая ночь и только деньги переделываю я.
Для начала респрайт купюр в единичные купюры.
![image](https://user-images.githubusercontent.com/21008918/221410295-c3d754d2-04bf-4482-89a7-4066f6c03dcf.png)
Теперь купюры есть: 1, 5, 10, 20, 50, 100, 200 и 500 кредитов. Купюра в 1000 кредитов удалена за ненадобностью.
На купюрах изображён знак Кредита и профессия. 1 - ассистент, 5 - уборщик, 10 - учёный, 20 - медик, 50 - инженер, 100 - гп, 200 - гсб, 500 - капитан.

**Следующие ПРы:**
1. Совмещение купюр в пачки купюр.
2. Респрайт кошелька.
3. Преф на начальные деньги в рюкзаке вместо счёта.
4. Оплата покупок в вендомате наличкой.
5. Переработка цен заказа в карго и многого другого.

## Почему и что этот ПР улучшит
Начали переделывать кеш. Продолжим переработкой всех денег.

## Авторство
AndreyGysev и все все все, кто помогал в дискорде.

## Чеинжлог
 :cl:
  - image: Респрайт купюр.

2023-02-26 12:27 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2023-02-26 12:29 UTC, KIBORG04 commented
скрытонерф капеллана

2023-02-26 12:30 UTC, DarthSidiousPalpatine commented
> скрытонерф капеллана

Теперь открытонерф

2023-02-26 12:31 UTC, KIBORG04 commented on code/modules/reagents/reagent_containers/food/snacks/grown.dm
> +			new/obj/item/weapon/spacecash/c1(loc)
это было смешно, когда спавнило деньги номиналом 0

2023-02-26 12:31 UTC, DarthSidiousPalpatine commented on code/modules/reagents/reagent_containers/food/snacks/grown.dm
> +			new/obj/item/weapon/spacecash/c1(loc)
Я думаю это был баг.

2023-02-26 12:32 UTC, KIBORG04 commented on code/modules/reagents/reagent_containers/food/snacks/grown.dm
> +			new/obj/item/weapon/spacecash/c1(loc)
хз баг ли, но спрайт с 0 то был

2023-02-26 12:32 UTC, DarthSidiousPalpatine commented on code/modules/reagents/reagent_containers/food/snacks/grown.dm
> +			new/obj/item/weapon/spacecash/c1(loc)
Не был, использовался тот же спрайт что для с1

2023-02-26 12:33 UTC, DarthSidiousPalpatine commented on code/modules/reagents/reagent_containers/food/snacks/grown.dm
> +			new/obj/item/weapon/spacecash/c1(loc)
точнее был баг, не существовало спрайта для spacecash1, а сам кеш1 существовал в коде. Видимо. Ну судя по икондиффу.

2023-02-26 12:33 UTC, KIBORG04 commented on code/modules/reagents/reagent_containers/food/snacks/grown.dm
> +			new/obj/item/weapon/spacecash/c1(loc)
а, ты прав, но тут очевидно не 1 написано, а скорее 10????
![image](https://user-images.githubusercontent.com/26389417/221410720-4249540e-6e06-4746-ba69-4fae32cff236.png)

2023-02-26 12:35 UTC, KIBORG04 commented on code/modules/economy/cash.dm
> +	icon_state = "spacecash1"
Нет желания сделать разные иконки для мира и для рук, как это щас с монетками?

2023-02-26 12:36 UTC, DarthSidiousPalpatine commented on code/modules/economy/cash.dm
> +	icon_state = "spacecash1"
Нет, потому что тогда придётся для пачки денег тоже делать разные спрайты, а это писец тбф.
Тем более мелкие деньги очень плохо видны если ими расплачиваться. Монетки никому не нужны, ими не расплатиться нигде, а деньги я хочу ввести в оборот, чтобы хотя бы в вендоматах и прочих структурах можно было платить ими.

2023-02-26 12:37 UTC, KIBORG04 commented on code/modules/reagents/reagent_containers/food/snacks/grown.dm
> +			new/obj/item/weapon/spacecash/c1(loc)
Проверь тогда на всякий случай, можно ли в билде легально получить 0 кредитов

2023-02-26 12:37 UTC, Sakuya-Izayoi commented
наличные деньги удобно сделаны на эрисе, там они стакаются

но у них есть обоснование для уделения внимания бумажным деньгам -- у них у бродяг нет банковских счетов. хз насколько к нам такое применимо...

2023-02-26 12:38 UTC, KIBORG04 submitted a review, later dismissed
Да вроде только к спрайтам вопрос

2023-02-26 12:38 UTC, DarthSidiousPalpatine commented
> наличные деньги удобно сделаны на эрисе, там они стакаются
> 
> но у них есть обоснование для уделения внимания бумажным деньгам -- у них у бродяг нет банковских счетов. хз насколько к нам такое применимо...

У меня в следующем ПРе будут стакаться.

2023-02-26 12:40 UTC, DarthSidiousPalpatine commented on code/modules/reagents/reagent_containers/food/snacks/grown.dm
> +			new/obj/item/weapon/spacecash/c1(loc)
Проверил, в вендомате каком-то у капеллана спавнился кеш, теперь 50 кредитов спавниться будет.

2023-02-26 12:44 UTC, volas commented
> На купюрах изображён знак Кредита и профессия. 1 - ассистент, 5 - уборщик, 10 - учёный, 20 - медик, 50 - инженер, 100 - гп, 200 - гсб, 500 - капитан.

как тебе такое вообще пришло в голову

2023-02-26 12:45 UTC, DarthSidiousPalpatine commented
> > На купюрах изображён знак Кредита и профессия. 1 - ассистент, 5 - уборщик, 10 - учёный, 20 - медик, 50 - инженер, 100 - гп, 200 - гсб, 500 - капитан.
> 
> как тебе такое вообще пришло в голову

Потому что это забавно, говорить о деньгах, произнося не номинал, а то, что на них нарисовано.
Типа как с вашингтоном делают в фильмах. А у нас "Плачу тебе капитанами" :dovolen:

2023-02-26 14:07 UTC, LudwigVonChesterfield commented
> как тебе такое вообще пришло в голову

а что плохого особенно учитывая что почти реально отражают зарплаты проф...

2023-03-09 14:04 UTC, TauKitty commented
Этот запрос на слияние был упомянут в **Tau Ceti Station Forum**. Там могут быть соответствующие подробности:

https://forum.taucetistation.org/t/peredelka-deneg-chast-1/38387/1

2023-03-12 22:12 UTC, LudwigVonChesterfield commented
Нужно скооперироваться с спрайт отделом по поводу цветов купюр, кажется

2023-03-20 10:36 UTC, UDaV73rus requested changes
Лица - ну тут и так понятно ультра калыч. Даже то как нарисованы
Цвета в целом ок, но поправь разную "силу" цветов, чоб все одинаково смотрелись. Хз как по нормальному назвать, типо насыщенность и темность-светлость. Мб если посмотреть в чб, будет понятнее к чему стремится

2023-04-05 14:42 UTC, closed without merging