Реорганизация резисткода
TauCetiStation/TauCetiClassic pull request #10875
Opened 2023-02-26 14:02 UTC by Sakuya-Izayoi

## Описание изменений
Реорганизация резист кода, основная цель рефактора -- избавление от истайпов
Продвижение в сторону реворка бореров
В некоторых местах не стал трогать очевидные моменты типа спаунов потому что мне лень с этим разбираться

## Почему и что этот ПР улучшит
Код стал чище

## Авторство

## Чеинжлог

2023-02-26 14:02 UTC, TauKitty commented
###### Changelog status: :radio_button: No changelog

2023-03-04 13:30 UTC, kalazus reviewed
Вроде норм, но слишком много старого кода, который желательно заменить. По типу, next_move = world.time + 100, заменить время на секунды/минуты. Но если это просто "немного улучшить код резиста", то вроде норм.

2023-03-04 13:30 UTC, kalazus commented on code/modules/mob/living/living.dm
> +		if(!iscarbon(src)) // carbon unbuckling is done in carbon's /resist, i don't know how to make it better
Добавить прок для resist_buckle? Типо, у живых это buckled.user_unbuckle_mob(src). У карбонов будет с проверкой на handcuffs.

2023-03-10 04:27 UTC, LudwigVonChesterfield approved these changes
всё что сказал Калазус

вроде ничего не потерялось, всё поразбивалось на функции, но внутри функций страшно...

надеюсь в будущем это тоже пофиксят.

2023-03-13 07:11 UTC, Sakuya-Izayoi commented on code/modules/mob/living/living.dm
> +		if(!iscarbon(src)) // carbon unbuckling is done in carbon's /resist, i don't know how to make it better
да это хорошее решение

2023-03-13 11:38 UTC, kalazus commented
Так, нету же коммитов после последнего замечания...

2023-03-17 04:50 UTC, volas requested changes
реквест выше, с которым автор вроде согласился

2023-03-23 20:13 UTC, LudwigVonChesterfield commented
ПР так-то ничего не ломал, а если вы не будете мержить потому-что "а порефактори ещё больше" и в итоге ПР умрёт конечно смешно получится.

2023-03-24 01:27 UTC, volas commented
Гетап бы мог попросить и сам смержить, сейчас это просто выглядело что он хочет доделать по предложениям

2023-04-09 17:02 UTC, volas commented
*смешно получилось*

2023-04-24 00:29 UTC, LudwigVonChesterfield commented
хахахахахаха а теперь тут ещё и конфликты :). найс пр доделали

2023-05-15 02:23 UTC, closed without merging