Удобный ефтпос.
TauCetiStation/TauCetiClassic pull request #10884
Opened 2023-02-27 13:42 UTC by DarthSidiousPalpatine

## Описание изменений
![image](https://user-images.githubusercontent.com/21008918/221577484-328441a3-9cd9-4016-841d-c443616ef79e.png)
Добавлен девайс, который прикручивается к столу, которым легко пользоваться как продавцу так и пользователю.
### Для настройки требуется:
1) Откручиваем девайс от стола ключом.
2) Берём девайс в руки и тыкает по нему картой.
3) Продавец ставит девайс назад и прикручивает ключом.

### Как пользоваться продавцу:
1) Открываешь интерфейс когда девайс лежит на столе и прикручен.
2) Нажимаем циферки.
3) Нажимаем зелёную кнопку с кружочком.
(ОПЦИОНАЛЬНО) Если хочешь чтобы цена не сбросилась после покупки, а осталась такой же, чтобы тебе не вводить снова эту же цену (допустим. донаты собираем, ввели 5$ и любой желающий просто подходит и может сколько угодно раз заплатить тебе 5$), - нажми на кнопку "Сбрасывать?", чтобы она перестала быть зелёной.

### Как пользоваться покупателю:
1) Увидеть высветившуюся голограмму цены.
2) Тыкнуть картой по девайсу.

## Почему и что этот ПР улучшит
Удобнее чем ефтпос.

## Авторство
AndreyGysev и все все все, кто помогал в дискорде.

## Чеинжлог
 :cl:
  - rscadd: Добавлен терминал оплаты который придёт на замену EFTPOS.

2023-02-27 13:42 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2023-02-27 13:44 UTC, TheLone1y commented
Юхууу емать Гисев рвееет!!!

2023-02-27 13:46 UTC, DarthSidiousPalpatine commented
Ебать у меня сломался русский язык.

2023-02-27 13:53 UTC, TauKitty commented
Этот запрос на слияние был упомянут в **Tau Ceti Station Forum**. Там могут быть соответствующие подробности:

https://forum.taucetistation.org/t/fludilka-chast-2/28659/20448

2023-02-27 13:57 UTC, Pivo24 commented
А если хочу подключить к EFTPOS карго-аккаунт?

2023-02-27 13:58 UTC, DarthSidiousPalpatine commented
> А если хочу подключить к EFTPOS карго-аккаунт?

бля....

2023-02-27 13:59 UTC, DarthSidiousPalpatine commented
> 

выйдет и не будет видно. Так что не ставь два терминала рядом :dovolen:

2023-02-27 14:02 UTC, DarthSidiousPalpatine commented
так, немного надо переделать кое-что, резонные требования. Не мержить.

2023-02-27 16:04 UTC, DarthSidiousPalpatine commented
Что я сделал. Что-то закодил, оно работает. Даааа....
Собственно, да.

2023-02-27 16:12 UTC, volas commented on tgui/packages/tgui/interfaces/CardPay.js
> +    buttons.push(<br />);
сделай классы, или в tgui наверняка уже есть какой-нибудь grid. br вообще не нужны.

2023-02-27 16:14 UTC, volas commented on tgui/packages/tgui/interfaces/CardPay.js
> +          mb={0.5}
аналогично тут и ниже, хардкодить значения в сам шаблон плохо

2023-02-27 16:16 UTC, DarthSidiousPalpatine commented on code/modules/economy/cardpay.dm
> +	desc = "���������� ������� ������� ��������� �����."
Так уже пофиксил же бля

2023-02-27 16:52 UTC, liteyzz commented
крутой ПР, меня только голограмма цены смутила как то выбивается сильно из общего вида

2023-03-01 13:43 UTC, DarthSidiousPalpatine commented
Ну кароч готово

2023-03-01 20:24 UTC, Sakuya-Izayoi requested changes
нельзя ввести комментарий к переводу как в оригинальном ефтпосе, даунгрейд

2023-03-02 02:43 UTC, DarthSidiousPalpatine commented
> нельзя ввести комментарий к переводу как в оригинальном ефтпосе, даунгрейд

его блять и не должно быть, ефтопс это терминал оплаты блять а комменты иди вводи в кпк или атм

2023-03-09 07:04 UTC, DarthSidiousPalpatine commented
Исправил конфликт иконок.

Гетуп, иди нафиг, если из-за твоей необоснованной претензии меня не замержат, то я ничего не сделаю, но буду очень расстроен.

2023-03-10 04:51 UTC, LudwigVonChesterfield commented
можно ли циферки сделать полупрозрачными? на фотке кринжовенько выглядит

2023-03-10 04:52 UTC, LudwigVonChesterfield commented on code/modules/economy/cardpay.dm
> +		. = ..()
```suggestion
		return ..()
```

2023-03-10 04:53 UTC, LudwigVonChesterfield commented on code/modules/economy/cardpay.dm
> +	set_dir(turn(dir,-90))
не знал что в руках дир есть

2023-03-10 04:53 UTC, DarthSidiousPalpatine commented on code/modules/economy/cardpay.dm
> +	set_dir(turn(dir,-90))
Есть

2023-03-10 04:53 UTC, LudwigVonChesterfield commented on code/modules/economy/cardpay.dm
> +				update_holoprice(TRUE)
аргумент надо поименно передавать а то очень не понятно

2023-03-10 04:54 UTC, LudwigVonChesterfield commented on code/modules/economy/cardpay.dm
> +				linked_account = D
суть мемов была в том чтобы не хранить ссылки на эти аккаунты, от этого рантаймы и проблемы. пожалуйста храни номер счёта и подтягивай его когда надо

2023-03-10 04:54 UTC, DarthSidiousPalpatine commented on code/modules/economy/cardpay.dm
> +				linked_account = D
Так он не хранится же. Он сразу юзается.

2023-03-10 04:55 UTC, LudwigVonChesterfield commented on code/modules/economy/cardpay.dm
> +			attempt_pin = input("Введите ПИН-код", "Терминал оплаты") as num
за время ввода пин кода можно поменять pay amount, и отвязать аккаунт

2023-03-10 04:55 UTC, LudwigVonChesterfield commented on code/modules/economy/cardpay.dm
> +		addtimer(CALLBACK(src, .proc/make_transaction, D, pay_amount), 3 SECONDS)
за время таймера на транзакцию можно поменять pay amount и отвязать аккаунт

2023-03-10 04:56 UTC, LudwigVonChesterfield commented on code/modules/economy/cardpay.dm
> +	var/datum/money_account/linked_account
"он не хранится же он сразу юзается"

2023-03-10 04:56 UTC, DarthSidiousPalpatine commented on code/modules/economy/cardpay.dm
> +		addtimer(CALLBACK(src, .proc/make_transaction, D, pay_amount), 3 SECONDS)
И что? Тут конкретно и что? Оно же возьмёт payamount во время постановки таймера.

2023-03-10 04:56 UTC, DarthSidiousPalpatine commented on code/modules/economy/cardpay.dm
> +	var/datum/money_account/linked_account
черт

2023-03-10 04:57 UTC, LudwigVonChesterfield commented on code/modules/economy/cardpay.dm
> +	var/pay_amount = 0
pay amount определенно переменная объекта а не функции а значит будет браться не в момент установки таймера

2023-03-10 10:17 UTC, DarthSidiousPalpatine commented
отлично, это было просто и быстро, исправил всякое.

2023-03-10 13:33 UTC, LudwigVonChesterfield commented on code/modules/economy/cardpay.dm
> +		addtimer(CALLBACK(src, .proc/make_transaction, D, pay_holder), 3 SECONDS)
зачем задержка в три секунды

2023-03-10 13:34 UTC, DarthSidiousPalpatine commented on code/modules/economy/cardpay.dm
> +		addtimer(CALLBACK(src, .proc/make_transaction, D, pay_holder), 3 SECONDS)
Потому что прикольно, типа связь с сервером устанавливает. И анима ещё что там крутится кружок. Круто, че)

2023-03-10 13:34 UTC, LudwigVonChesterfield commented on code/modules/economy/cardpay.dm
> +			attempt_pin = input("Введите ПИН-код", "Терминал оплаты") as num
нужно как-то проверять что человек не ввёл пин код убежав на другой конец карты через пол часа
(надо чтобы от момента начала транзакции прошло не больше условно минуты)

2023-03-10 13:37 UTC, DarthSidiousPalpatine commented on code/modules/economy/cardpay.dm
> +		visible_message("[bicon(src)]<span class='warning'>Недостаточно средств!</span>")
Да норм вроде выглядит. В чате иконка терминала и недостаточно средств

2023-03-10 20:35 UTC, LudwigVonChesterfield commented on code/modules/economy/cardpay.dm
> +		addtimer(CALLBACK(src, .proc/make_transaction, D, pay_holder), 3 SECONDS)
не круто потому-что не валидируется  существование аккаунта, ефтпоса, платильщика после трёх секунд

2023-03-11 14:04 UTC, DarthSidiousPalpatine commented
Добавил оплату по КПК, добавил проверку пинкода и ретурн.

2023-03-11 14:04 UTC, DarthSidiousPalpatine commented on code/modules/economy/cardpay.dm
> +			attempt_pin = input("Введите ПИН-код", "Терминал оплаты") as num
Мне кажется это не проблема

2023-03-11 14:04 UTC, DarthSidiousPalpatine commented on code/modules/economy/cardpay.dm
> +		addtimer(CALLBACK(src, .proc/make_transaction, D, pay_holder), 3 SECONDS)
Мне кажется и не должно, оно эти 3 секунды отправляет сообщение куда-то и ждёт ответ. Ну и норм. Зачем валидировать существование терминала после 3-х секунд?

2023-03-11 14:06 UTC, DarthSidiousPalpatine commented
Пофиксил конфликт с тгуи

2023-03-11 14:23 UTC, LudwigVonChesterfield commented on code/modules/economy/cardpay.dm
> +		addtimer(CALLBACK(src, .proc/make_transaction, D, pay_holder), 3 SECONDS)
Потому-что за 3 секунды его можно взорвать и вызвать этим потом рантаймы

2023-03-11 14:23 UTC, LudwigVonChesterfield commented on code/modules/economy/cardpay.dm
> +			attempt_pin = input("Введите ПИН-код", "Терминал оплаты") as num
Мне кажется это проблема.

2023-03-26 04:42 UTC, LudwigVonChesterfield requested changes
нужно пофиксить все мои незакрытые комменты

2023-03-29 14:46 UTC, DarthSidiousPalpatine commented
живи

2023-04-15 20:25 UTC, DarthSidiousPalpatine commented
Оооуееее, кароч пофиксил всё что ты говорил, людук, про пинкод там и проверки всякие. ТЕперь проверяется.

2023-04-22 03:32 UTC, LudwigVonChesterfield commented on code/modules/economy/cardpay.dm
> +/obj/item/device/cardpay/attackby(obj/item/I, mob/user, params)
challenge: реорганизовать код так чтобы использовать как можно меньше else-ов.

 лесенку else if-оф для определения чем атаковали можно оставить.

2023-04-22 03:33 UTC, LudwigVonChesterfield commented on code/modules/economy/cardpay.dm
> +			if(user.is_busy())
это кажется надо проверять ДО use_tool. если вообще надо

2023-04-22 03:34 UTC, LudwigVonChesterfield commented on code/modules/economy/cardpay.dm
> +			attempt_pin = input("Введите ПИН-код", "Терминал оплаты") as num
никак не пофикшено

2023-04-22 03:34 UTC, LudwigVonChesterfield commented on code/modules/economy/cardpay.dm
> +			attempt_pin = input("Введите ПИН-код", "Терминал оплаты") as num
никак не пофикшено

2023-04-22 03:34 UTC, LudwigVonChesterfield commented on code/modules/economy/cardpay.dm
> +		visible_message("[bicon(src)]<span class='warning'>Недостаточно средств!</span>")
у нас обычно вендоматы таки юзают такой же формат как и люди.

2023-04-22 03:35 UTC, LudwigVonChesterfield commented on code/modules/economy/cardpay.dm
> +	if(!isturf(src.loc))
```suggestion
	if(!isturf(loc))
```

2023-04-22 03:36 UTC, LudwigVonChesterfield commented on code/modules/economy/cardpay.dm
> +				display_price *= 10
можно ли это всё сделать проще?

почему бы к примеру не хранить введённый num строкой где-нибдь...

2023-04-22 03:36 UTC, LudwigVonChesterfield commented on code/modules/economy/cardpay.dm
> +						var/datum/money_account/D = get_account(display_price)
почему переменная с названием "отобрази цену" на самом деле отвечает за номер счёта

2023-04-22 03:37 UTC, LudwigVonChesterfield commented on code/modules/economy/cardpay.dm
> +/obj/item/device/cardpay/proc/check_direction(mob/user)
мне кажется функцию надо более говоряще переименовать в что-то типо "get operator direction" или "get client direction" в зависимости от того что именно она делает.

2023-04-22 03:52 UTC, DarthSidiousPalpatine commented on code/modules/economy/cardpay.dm
> +						var/datum/money_account/D = get_account(display_price)
потому что она отвечает за цифры на мониторе

2023-04-22 03:53 UTC, DarthSidiousPalpatine commented on code/modules/economy/cardpay.dm
> +				display_price *= 10
нет нельзя

2023-04-22 03:53 UTC, DarthSidiousPalpatine commented on code/modules/economy/cardpay.dm
> +			if(user.is_busy())
похуй сделал

2023-04-22 03:53 UTC, DarthSidiousPalpatine commented on code/modules/economy/cardpay.dm
> +		visible_message("[bicon(src)]<span class='warning'>Недостаточно средств!</span>")
похуй сделал

2023-04-22 03:54 UTC, DarthSidiousPalpatine commented on code/modules/economy/cardpay.dm
> +/obj/item/device/cardpay/proc/check_direction(mob/user)
она не ГЕТАЕТ ничего, она ПРОВЕРЯЕТ ДИРЕКШН, потому названа ЧЕК ДИРЕКШН чтобы был НУЖНЫЙ.

2023-04-22 03:54 UTC, volas commented on code/modules/economy/cardpay.dm
> +			if(user.is_busy())
не нужно, use_tool более высокоранговый метод и делает всё сам

2023-04-22 03:56 UTC, volas commented on code/modules/economy/cardpay.dm
> +/obj/item/device/cardpay/proc/check_direction(mob/user)
зачем она вообще нужна, is_the_opposite_dir сам по себе говорящий

2023-04-22 03:58 UTC, DarthSidiousPalpatine commented on code/modules/economy/cardpay.dm
> +/obj/item/device/cardpay/attackby(obj/item/I, mob/user, params)
Похуй сделал

2023-04-22 03:59 UTC, DarthSidiousPalpatine commented on code/modules/economy/cardpay.dm
> +			attempt_pin = input("Введите ПИН-код", "Терминал оплаты") as num
похуй сделал

2023-04-22 03:59 UTC, DarthSidiousPalpatine commented on code/modules/economy/cardpay.dm
> +	if(!isturf(src.loc))
о боже мне нельзя резолвнуть, как быть, ну вот, такое сильное изменение

2023-04-22 04:00 UTC, DarthSidiousPalpatine commented on code/modules/economy/cardpay.dm
> +/obj/item/device/cardpay/proc/check_direction(mob/user)
Похуй удалил

2023-04-22 04:01 UTC, DarthSidiousPalpatine commented on code/modules/economy/cardpay.dm
> +			if(user.is_busy())
Похуй удалил

2023-04-22 13:56 UTC, LudwigVonChesterfield commented on code/modules/economy/cardpay.dm
> +						var/datum/money_account/D = get_account(display_price)
но это номер счёта, а не цена. может `display_account_number`?

2023-04-22 13:57 UTC, LudwigVonChesterfield commented on code/modules/economy/cardpay.dm
> +				return
нужен вывод в чатик о том что произошла ошибка связанная с чем-нибудь. если для каждого вида ошибки будет свой вывод будет ещё лучше

2023-04-22 13:57 UTC, LudwigVonChesterfield commented on code/modules/economy/cardpay.dm
> +	else
challenge: убрать else

2023-04-22 13:58 UTC, DarthSidiousPalpatine commented on code/modules/economy/cardpay.dm
> +						var/datum/money_account/D = get_account(display_price)
Там дисплеится и номер счёта который ты вводишь и цена предмета которую вводишь. Это полуфронтенд переменная чисто.
Может, я херню сделал и проще переписать, хз. Может нет.


Кстати, такой вопрос, а зачем проверять не изменился ли аккаунт у штуки для оплаты за время воода пинкода?
Ну ты начал вводить пинкод - программа взяла все параметры у терминала и всё, пусть хоть 10 раз меняется. главное проверить что терминал ещё существует....

2023-04-22 14:00 UTC, LudwigVonChesterfield commented on code/modules/economy/cardpay.dm
> +						var/datum/money_account/D = get_account(display_price)
ты либо обманываешь того кто платит либо того кому платят

предпочтительно не обманывать никого

2023-04-22 14:01 UTC, DarthSidiousPalpatine commented on code/modules/economy/cardpay.dm
> +						var/datum/money_account/D = get_account(display_price)
Я не понимаю как ты обманываешь если во время начала транзакции записывается тот акк который стоял на терминале, а не тот который потом сменится. Тот который сменится повлияет только на следующую транзакцию. А тот который был на момент начала транзакции - так и передастся в оплату.

2023-04-30 04:02 UTC, DarthSidiousPalpatine commented
нет

2023-04-30 14:58 UTC, DarthSidiousPalpatine commented
С другой стороны да, Лижард прав.

2023-05-20 16:29 UTC, DarthSidiousPalpatine commented
Возрождаем челика, раз два три...

2023-05-21 06:54 UTC, DarthSidiousPalpatine commented
Так, убрал лишний else, добавил сообщения об ошибках.

Я, думаю, усё? Можно... тестмержить...?

2023-05-21 16:16 UTC, LudwigVonChesterfield commented
можно ли циферкам голограмме сделать обводку черную?

2023-05-21 16:16 UTC, DarthSidiousPalpatine commented
> можно ли циферкам голограмме сделать обводку черную?

Ну это же маптекст, надо чекнуть, ща.

2023-05-26 12:37 UTC, DarthSidiousPalpatine commented
Нет, нельзя. Остальное, вроде, решил. Там либо нерешаемо, либо не нужно?
Кароч, можно уже ТМ там или хз. Хочется поиграть с ефтпосом и собрать фидбек игроков как это было с прилавками или квалити оф лайф карго.

2023-05-26 17:05 UTC, LudwigVonChesterfield commented on code/modules/economy/cardpay.dm
> +				display_price *= 10
@KIBORG04 нужно мнение о том можно ли сделать проще

2023-05-26 17:06 UTC, LudwigVonChesterfield commented on code/modules/economy/cardpay.dm
> +						var/datum/money_account/D = get_account(display_price)
переменную надо переименовать

2023-05-26 17:38 UTC, KIBORG04 commented on code/modules/economy/cardpay.dm
> +				display_price *= 10
С num проще нельзя, валидация типа все дела, а с display_price можно. Но вроде и так понятно все

2023-05-26 20:16 UTC, DarthSidiousPalpatine commented
Сделал обводку, заменил шрифт на SMALL FONTS юзаемый и так в билде для всякого говнища.
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/21008918/eac18e30-6952-4af3-93e9-f3c207d60231)

2023-05-26 20:18 UTC, DarthSidiousPalpatine commented on code/modules/economy/cardpay.dm
> +						var/datum/money_account/D = get_account(display_price)
Жду предложений. У меня нет фантазии.

2023-05-26 20:39 UTC, LudwigVonChesterfield commented on code/modules/economy/cardpay.dm
> +						var/datum/money_account/D = get_account(display_price)
выше в этой дискуссии `display_account_number`

2023-05-26 20:40 UTC, DarthSidiousPalpatine commented on code/modules/economy/cardpay.dm
> +						var/datum/money_account/D = get_account(display_price)
Но оно не только аккаунт намбер же дисплеет. Оно дисплеет и аккаунт намбер и прайс.

2023-05-26 20:40 UTC, LudwigVonChesterfield submitted a review, later dismissed
если переименновать переменную аккаунта можно мержить, пока-что одобряю на ТМ

2023-05-26 20:41 UTC, LudwigVonChesterfield commented
если мержить старый ефтпос надо будет убрать думаю.

2023-05-26 20:44 UTC, LudwigVonChesterfield commented on code/modules/economy/cardpay.dm
> +						var/datum/money_account/D = get_account(display_price)
попроубй `display_numbers`

2023-05-26 20:44 UTC, DarthSidiousPalpatine commented
Переименовал в display_numbers

2023-05-26 20:45 UTC, DarthSidiousPalpatine commented
> если мержить старый ефтпос надо будет убрать думаю.

Старый уберу когда вмержится этот. Надо собрать будет фидбек всё ли устраивает и удобнее ли старого :dovolen:

2023-05-26 22:40 UTC, LudwigVonChesterfield commented
Я бы предпочёл выпилить кнопку "РЕЖИМ ДОНАТОВ" и ввести режим донатов как дефолтное поведение.
(если не выпиливать то как минимум нужно уведомление игроку в чат о том что кнопка делает, "ВЫ ВКЛЮЧИЛИ РЕЖИМ ПОЖЕРТВОВАНИЙ, В НЁМ ЦЕНА НЕ БУДЕТ СБРАСЫВАТЬСЯ ПОСЛЕ ПОКУПКИ)

Было бы круто если бы ЕФТПОС подтягивал при возможности из памяти игрока номер аккаунта при первом поднятии что-ли.

Нужно сообщение о том что вы в режиме ввода номера счёта когда он включается

2023-05-26 22:41 UTC, LudwigVonChesterfield commented
а) надо сбрасывать картинку по переключении режима
б) надо пинкод из мема

2023-05-26 22:52 UTC, LudwigVonChesterfield commented
имхо идеальный ЕФТПОС бы работал бы так - 

1. начинает в режиме "НЕПРИВЯЗАН". если открыть интерфейс тебе это пишет ЕФТПОС НЕПРИВЯЗАН, ВВЕДИТЕ НОМЕР СЧЁТА ИЛИ ПРОВЕДИТЕ КАРТОЙ

если проводишь картой - вводит номер счёта с неё, альтернативно можно ввести ручками

2. в интерфейсе есть кнопка "СБРОСИТЬ НОМЕР СЧЁТА", требующая пин кода от текущего аккаунта(можно чтобы она выглядела как и сейчас, она переводит в состояние 1)

3. если счёт введён, то только челик с картой на которую подвязан этот счёт может выставлять цену, независимо от того где он находится относительно ефтпоса. можно ещё какую-то защиту от отго чтобы другие люди не спиздили ефтпос, но нужно как-то максимально тупо

4. клик по ефтпосу с выставленной ценой картой, пда, или чипом с деньгами проводит транзакцию. после чего штучка пиликает и говорит ТРАНЗАКЦИЯ УСПЕШНА. но цена не сбрасывается

я думаю такой ЕФТПОС был бы явно лучше старого во всех возможных аспектах
инструкция к использованию была бы встроена в сам мегадевайс, нельзя протупить и ввести что-то не так, максимально расширяем в плане использований
при этом требует кроме панельки ввода циферок всего 1 лишнюю кнопку и одну панель для информирования пользователя.

2023-05-26 22:55 UTC, LudwigVonChesterfield commented
Кстати не знаю или кто-то будет скучать по этой фиче, но в старом ЕФТПОС-е можно было оплачивать зная реквизиты, а в новом нет.

2023-05-26 23:02 UTC, LudwigVonChesterfield commented
Ещё пара вещей которые делают этот ЕФТПОС даунгрейдом:
- требование стоять с той или иной стороны. Гисев кодил это параллельно с прилавками, и не подумал что прилавки затыкают уже нишу прилавочного магазина. А поставить ЕФТПОС посреди зала и получать донаты с текущей реализацией невозможно.
- невозможно оплачивать по реквизитам, почему-то обязательна карта и является единственным способом оплатить.
- нет поддержки чипов для оплаты, которые по сути электронные счета

Не уверен что понимаю почему нельзя позволять оплачивающему иметь доступ к интерфейсу, позволило к примеру сделать оплату по реквизитам, при этом не мешая платить карточкой... Цена ведь и так высвечивается голограммой

2023-05-26 23:07 UTC, DarthSidiousPalpatine commented
Сделал ресет по изменении режима.

Сделал подписи по смене режимов.

Сделал пинкод из мема.

2023-05-26 23:09 UTC, DarthSidiousPalpatine commented
Жаль это не обновят ещё долго и на сервере будет версия с пином.

2023-05-26 23:30 UTC, DarthSidiousPalpatine commented
а) Добавил оплату по чипу оплаты.
б) Добавил возможность привязать к терминалу чип оплаты и кидать деньги на него.
в) Доп. сообщение если нет аккаунта у терминала.

2023-05-26 23:31 UTC, DarthSidiousPalpatine commented
Кароч надеюсь за эту неделю (или хотяб выхи), протестить ефтпос по всем пунктам, собрать фидбек лично и если уж надо сделать твои фичи, Людук.

2023-05-27 03:23 UTC, LudwigVonChesterfield commented on code/modules/economy/cardpay.dm
> +/obj/item/device/cardpay/proc/scan_charge_card(datum/money_account/D)
мне кажется функцию надо переименовать в check_money_account

2023-05-27 03:25 UTC, LudwigVonChesterfield commented
пускай повисит неделю в ТМ-е, если сделаны будут фичи что я описал ("обратная" совместимость со старым ЕФТПОС-ом, в том плане что как минимум все фичи старого + отсутствие требования направления взаимодействия) то лично я точно замержу, а так посмотрим на фидбек.

2023-05-27 20:42 UTC, LudwigVonChesterfield commented
на экзамайн стоит ещё писать номер счёта введённый, и имя счёта получателя думаю.

2023-05-27 21:29 UTC, LudwigVonChesterfield approved these changes

2023-05-27 23:09 UTC, LudwigVonChesterfield commented
не работает подключение счёта по реквизитам

ввожу номер счёта (будь то с карточки, или с чипа), нажимаю зелененькое, и нет сообщения "Аккаунт подключён" но введённое стирается.

2023-05-27 23:09 UTC, LudwigVonChesterfield commented
обычно у нас номер счёта начинается с # а не №

2023-05-27 23:10 UTC, LudwigVonChesterfield commented
Если на терминале ввести цену, к примеру 5 кредитов

После его открутить, и прикрутить снова

Голограммы цены не будет, но если прикласть карточку то спишется 5 кредитов.

2023-05-27 23:21 UTC, LudwigVonChesterfield commented
можно прикрутить к столу, открутить стол, и тогда ЕФТПОС будет прикручен к полу.

2023-05-27 23:22 UTC, LudwigVonChesterfield commented
когда вводишь номер счёта в интерфейсе пишет "0" до того как ты что-то введёшь, немного путает.

2023-05-27 23:34 UTC, LudwigVonChesterfield commented
пока обрабатывается одна транзакция можно приложить КПК ещё раз и будет параллельно обрабатываться две транзакции что сломает анимацию

2023-05-27 23:49 UTC, LudwigVonChesterfield commented
когда оплачиваешь вместо того чтобы писать кому ты заплатил пишет Терминал оплаты account number

2023-05-27 23:55 UTC, DarthSidiousPalpatine commented
Добавил сообщение и выключение режима счёта при удачном переключении счёта.
Добавил стирание цены при откручивании.
Добавил откручивание при ломании стола.
Теперь нельзя подряд несколько транзакций проводить.
Теперь пишет имя и номер аккаунта терминала в логах.

2023-05-30 14:30 UTC, LudwigVonChesterfield commented
- когда вводишь номер счёта в интерфейсе пишет "0" до того как ты что-то введёшь, немного путает.
- обычно у нас номер счёта начинается с # а не №

Насколько сложно эти две вещи пофиксить?

2023-05-30 21:06 UTC, LudwigVonChesterfield commented
35 Runtime in cardpay.dm:132 : Cannot read null.security_level

2023-06-01 17:48 UTC, LudwigVonChesterfield commented
Баг это вот этот рантайм? `35 Runtime in cardpay.dm:132 : Cannot read null.security_level`

2023-06-01 17:49 UTC, LudwigVonChesterfield commented on code/modules/economy/cardpay.dm
> +				if(!check_pincode(get_account(linked_account)))
что если get_account(linked_account) - нулл?

2023-06-01 17:49 UTC, LudwigVonChesterfield commented on code/modules/economy/cardpay.dm
> +	if(D)
можно сделать ранним возвратом
```
if(!D)
    return

код
```

2023-06-01 17:49 UTC, LudwigVonChesterfield commented on code/modules/economy/cardpay.dm
> +		if(check_pincode(D))
можно тоже сделать ранним возвратом

2023-06-01 20:21 UTC, LudwigVonChesterfield commented
Если поменять № на # (потому-что номера счёта везде в игре именно так обозначаются, а не потому-что я хочу подавить твою креативность, я не против если ты потом сделаешь отдельный ПР где все упоминания номера счёта поменяешь на этот символ)

И если пофиксить рантайм (написал под конкретной строкой в чем думаю проблема)

то думаю что ПР готов к мержу.

2023-06-01 21:51 UTC, LudwigVonChesterfield commented
обнаружили прикол что на терминал оплаты нет КД на клики и можно спаммить звуками к примеру если кликать карточкой по не настроенному терминалу

2023-06-02 04:21 UTC, DarthSidiousPalpatine commented
Ну итак, я заменил #, я добавил проверку get_account(linked_account), сделал кд на клики, сделал ранние возвраты.

2023-06-02 04:22 UTC, DarthSidiousPalpatine commented
Думаю, это всё, пойду форкнусь от этой ветки и сделаю интерфейс в другом пре...

2023-06-03 00:42 UTC, LudwigVonChesterfield commented
как только тут решат конфликт, и удалят старый ЕФТПОС - смержу ПР.

2023-06-03 07:54 UTC, DarthSidiousPalpatine commented
> как только тут решат конфликт, поправят(или уберут) спрайт голограммы и удалят старый ЕФТПОС - смержу ПР.

ГоТоВо

2023-06-03 07:54 UTC, DarthSidiousPalpatine commented
![GIF 03 06 2023 11-41-40](https://github.com/TauCetiStation/TauCetiClassic/assets/21008918/d9e57bd9-8ed4-4746-a14c-9a3f2c8b6a40)

2023-06-03 14:21 UTC, DarthSidiousPalpatine commented
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/21008918/8e38691f-436f-4485-bc37-50a3498fcd87)
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/21008918/4d6bca1f-573f-4798-afa2-f043c8573219)
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/21008918/b3e512d0-9610-48af-a313-faa81a5b15a0)

Переделал на три штуки крч.

2023-06-04 02:12 UTC, merged