Простите, это фикс.
TauCetiStation/TauCetiClassic pull request #10918
Opened 2023-03-04 13:28 UTC by DarthSidiousPalpatine

## Описание изменений
Пофиксил неправильно устанавливаемое количество максимально возможных предмето в вендомате.
Пофиксил отсутствие расчёта количества игроков на сервере для вендомата.

## Почему и что этот ПР улучшит
Блин, простите, вот фикс...

## Авторство
AndreyGysev и все все все, кто помогал в дискорде.

## Чеинжлог
 :cl: 
 - bugfix: Фикс бага с невозможностью пополнить вендомат на полную.
 - bugfix: Фикс бага с отсутствием расчёта количества игроков для загрузки вендомата.

2023-03-04 13:28 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2023-03-04 13:29 UTC, DarthSidiousPalpatine commented
😢

2023-03-04 13:47 UTC, kalazus commented on code/game/machinery/vending.dm
> +				var/players_coefficient = global.player_list.len / 75 //75 players = max load, 0 players = min load
Вроде не поможет. У нас атои иниты происходят до того как игроки успеют зайти (как минимум большинство).

2023-03-04 13:48 UTC, DarthSidiousPalpatine commented on code/game/machinery/vending.dm
> +				var/players_coefficient = global.player_list.len / 75 //75 players = max load, 0 players = min load
Да вродь нет, они довольно поздно проходят.

2023-03-04 17:25 UTC, DarthSidiousPalpatine commented on code/game/machinery/vending.dm
> +				var/players_coefficient = global.player_list.len / 75 //75 players = max load, 0 players = min load
Ну готово

2023-03-04 17:33 UTC, kalazus commented on code/game/machinery/vending.dm
> +				var/players_coefficient = global.player_list.len / 75 //75 players = max load, 0 players = min load
А теперь не будут работать мидраунд т.к. у них нету датумов. Рандомизацию лучше сделать вообще в отдельном проке (не где создаются датумы).

2023-03-04 17:35 UTC, DarthSidiousPalpatine commented on code/game/machinery/vending.dm
> +				var/players_coefficient = global.player_list.len / 75 //75 players = max load, 0 players = min load
Всм не будет работать мидраунд, почему это.

2023-03-04 19:17 UTC, KIBORG04 commented on code/game/machinery/vending.dm
> +		load_products(FALSE)
Зачем этот иф?...

2023-03-04 19:18 UTC, KIBORG04 commented on code/controllers/subsystem/ticker.dm
> +		Vendomat.load_products(TRUE)
Оберни это в функцию(чтобы было понятно че за код и нах) и помести куда-то к 255 строчкам.

2023-03-04 19:36 UTC, volas commented
Это днем вроде обсуждалось в дискорде, на момент загрузки сервера количество игроков не лучшая метрика. Часто это будет какой-то рандом, когда не все успели залететь по тем или иным причинам до начала инициализации.

Брать раундстартом было бы лучше, но тоже не всегда ок. Если сервер, допустим, поднимается после падения, он может и с 5 человеками стартовать в прайм тайм, а остальные потом подтягиваются.

Да и штатно у нас бывают большие колебания онлайна в раунде. Если стартовали где-то в час в будний день - будет нормой иметь 20-30 игроков в начале раунда, и в два раза больше к концу.

2023-03-04 19:39 UTC, volas commented
Можно подумать о какой-нибудь простой зависимости от максимального лимита игроков + nightshift (или что-то подобное)

2023-03-05 05:20 UTC, DarthSidiousPalpatine commented on code/game/machinery/vending.dm
> +		load_products(FALSE)
Чтобы при маплоаде не пыталось впиндюрить предметы.

2023-03-05 05:21 UTC, DarthSidiousPalpatine commented on code/controllers/subsystem/ticker.dm
> +		Vendomat.load_products(TRUE)
Нигде не обёрнуто в функцию ничего.

2023-03-05 05:23 UTC, DarthSidiousPalpatine commented
> Это днем вроде обсуждалось в дискорде, на момент загрузки сервера количество игроков не лучшая метрика. Часто это будет какой-то рандом, когда не все успели залететь по тем или иным причинам до начала инициализации.
> 
> Брать раундстартом было бы лучше, но тоже не всегда ок. Если сервер, допустим, поднимается после падения, он может и с 5 человеками стартовать в прайм тайм, а остальные потом подтягиваются.
> 
> Да и штатно у нас бывают большие колебания онлайна в раунде. Если стартовали где-то в час в будний день - будет нормой иметь 20-30 игроков в начале раунда, и в два раза больше к концу.

В редких случаях это и будет считаться ивентом "Пусто". Надо будет - каргонцы всегда пополнят. Главное что в большинстве случаев наполненность будет 60-100%

2023-03-05 08:45 UTC, DarthSidiousPalpatine commented on code/game/machinery/vending.dm
>  				var/players_coefficient = num_players() / 75 //75 players = max load, 0 players = min load
Если бы я знал где оно хранится, кап сервера.

2023-03-05 09:08 UTC, DarthSidiousPalpatine commented
как-то так

2023-03-05 09:48 UTC, KIBORG04 commented on code/game/machinery/vending.dm
> +		Vendomat.load_products(TRUE)
Не глобальным прок сделай, пусть в неймспейсе тикера будет

2023-03-05 09:48 UTC, KIBORG04 commented on code/game/machinery/vending.dm
> +		load_products(FALSE)
Ты знаешь че такое маплоад?

2023-03-05 10:14 UTC, KIBORG04 commented on code/game/machinery/vending.dm
> +/obj/machinery/vending/proc/load_products(mapload = FALSE)
параметр ничего не делает

2023-03-05 12:50 UTC, DarthSidiousPalpatine commented
Ну, как бы, готово.

2023-03-05 12:57 UTC, KIBORG04 commented on code/game/machinery/vending.dm
> +/obj/machinery/vending/proc/load_products(mapload = FALSE)
![image](https://user-images.githubusercontent.com/26389417/222961725-b2284571-5421-4e88-a749-1f19197f9b8d.png)

и где исправление

2023-03-05 12:58 UTC, DarthSidiousPalpatine commented on code/game/machinery/vending.dm
> +/obj/machinery/vending/proc/load_products(mapload = FALSE)
А, этот зря резолвнул, да.

Ну кароч параметр ничего не делает но нагляднее и читаемее.

2023-03-05 13:35 UTC, LudwigVonChesterfield commented on code/controllers/subsystem/ticker.dm
> +/datum/controller/subsystem/ticker/proc/fill_all_vending_machines()
Более крутой версии этой имплентации было бы где-то тут отправлять сигнал "ИГРА_НАЧИНАЕТСЯ" на который вендоматы зарегестрированы

2023-03-05 13:36 UTC, LudwigVonChesterfield commented on code/game/machinery/vending.dm
>  /obj/machinery/vending/proc/build_inventory(list/productlist, mapload, hidden = 0, req_coin = 0 , req_emag = 0)
учитывая что оно больше не подвязано к маплоаду, я бы переименовал.

2023-03-05 13:42 UTC, DarthSidiousPalpatine commented on code/game/machinery/vending.dm
>  /obj/machinery/vending/proc/build_inventory(list/productlist, mapload, hidden = 0, req_coin = 0 , req_emag = 0)
Окей готово.

2023-03-05 17:01 UTC, volas commented on code/controllers/subsystem/ticker.dm
> +/datum/controller/subsystem/ticker/proc/fill_all_vending_machines()
Можно перенести https://github.com/tgstation/tgstation/blob/master/code/__DEFINES/dcs/signals/signals_subsystem.dm

2023-03-06 19:15 UTC, KIBORG04 commented on code/game/machinery/vending.dm
> +				var/jobs_number = 0
тут какие-то цифорки пошли, зову других ментейнеров @LudwigVonChesterfield

2023-03-06 19:17 UTC, KIBORG04 commented on code/game/machinery/vending.dm
> +	if(!mapload)
Возможно мой вопрос прозвучит глупо, но что если я в начале раунда подойду к вендомату, разберу его, соберу, то все твои формулы сбросятся и эмаут станет больше?

2023-03-06 19:21 UTC, KIBORG04 commented on code/game/machinery/vending.dm
> +	if(!mapload)
всем похуй мы на бьонде кодим

2023-03-06 19:51 UTC, LudwigVonChesterfield commented on code/game/machinery/vending.dm
> +				var/jobs_number = 0
мне не нрав это решение, если его и делатьто пожалуйста отдельно от фикса

2023-03-06 19:51 UTC, LudwigVonChesterfield commented on code/game/machinery/vending.dm
> +	if(!mapload)
тут всё нормально потому-что функция кроме основного механа ещё другие вещи делает??

2023-03-06 19:52 UTC, LudwigVonChesterfield requested changes
заменить

find_all_vending_machines -> сигнал

убрать формулу про работы, мне лень сейчас думать как это правильно сделать (к примеру точно не брать число 8, потому-что на разных картах разное количество проф)

2023-03-09 12:50 UTC, LudwigVonChesterfield requested changes
Ещё нужно будет убрать коэффициенты от работ, если захочешь их добавить - то лучше отдельным ПР-ом.

2023-03-10 15:27 UTC, DarthSidiousPalpatine commented
Слыш работай. Удалил то что требовал удалить Людук. Добавил сигнал, пофиксил тупость свою.

2023-03-10 15:34 UTC, volas reviewed
всё еще немного говнокод, потом добью

2023-03-10 15:34 UTC, volas commented on code/game/machinery/vending.dm
> +		RegisterSignal(SSticker, COMSIG_TICKER_ROUND_STARTING, .proc/load_products, roundstart = TRUE)
```suggestion
	if(SSticker.current_state == GAME_STATE_PLAYING)
		load_products(FALSE)
	else
		RegisterSignal(SSticker, COMSIG_TICKER_ROUND_STARTING, .proc/load_products)
```

2023-03-10 15:34 UTC, volas commented on code/game/machinery/vending.dm
> +/obj/machinery/vending/proc/load_products(roundstart)
```suggestion
/obj/machinery/vending/proc/load_products(roundstart = TRUE)
```

2023-03-11 10:23 UTC, KIBORG04 commented
Этот ПР ломает в вендоматах картинки предметов!!!

https://github.com/TauCetiStation/TauCetiClassic/issues/10976

2023-03-11 10:26 UTC, KIBORG04 commented
Видимо баг в том, что штука пытается зарегестрировать ассеты когда-то на моменте инициализаций, а так как вендоматы пустые, то и нет предметов для картинок.
https://github.com/TauCetiStation/TauCetiClassic/blob/daf82fd26daf53b7d0b2b3045a550f77663caae0/code/modules/asset_cache/asset_list_items.dm#L145

2023-03-17 04:40 UTC, volas commented
#гусевживи

или помогите ему кто нибудь. Или откатите предыдущий пр с вендоматами (на время?).

2023-03-23 18:25 UTC, LudwigVonChesterfield commented on code/game/machinery/vending.dm
> +/obj/machinery/vending/proc/load_products(roundstart = TRUE)
все приёмники сигналов имеют как первый аргумент datum/source, а дальше уже нужные им аргументы.

2023-03-23 18:26 UTC, LudwigVonChesterfield commented on code/game/machinery/vending.dm
> +/obj/machinery/vending/proc/load_products(roundstart = TRUE)
рекомендую сделать что-то типо

```
RegisterSignal(SSticker, COMSIG_TICKER_ROUND_STARTING, .proc/on_round_start)

/vending/proc/on_round_start(datum/source)
    load_products(roundstart=TRUE)
```

2023-03-26 12:39 UTC, DarthSidiousPalpatine commented
Я сделяль.

2023-03-26 12:50 UTC, DarthSidiousPalpatine commented
Афигеть, реально работает. О_О

2023-03-26 13:48 UTC, LudwigVonChesterfield commented on code/game/machinery/vending.dm
> +	build_menue()
build_menu тут и везде

2023-03-26 13:49 UTC, LudwigVonChesterfield commented on code/game/machinery/vending.dm
> +			var/list/needed_records = records[menues.Find(menue)]
если они оба идут в одном порядке, почему нельзя

```
for(var/i in 1 to length(menues))
    var/list/menue = menues[i]
    var/list/needed_records = records[i]
    ...
```

2023-03-26 13:50 UTC, LudwigVonChesterfield commented on code/game/machinery/vending.dm
> +				var/players_coefficient = num_players() / 50 //100 players = double load, 50 players = max load, 0 players = min load
Гисев но коммент ремайндми был не о том чтобы сломать наши гениальные рассчёты поменяв циферку с 75 на 50, а о том что даже если players_coefficient будет 4.0 при 200-а людях, то потом ниже в final_coefficient он клампнется до 1.0.

2023-03-26 14:01 UTC, DarthSidiousPalpatine commented on code/game/machinery/vending.dm
> +			var/list/needed_records = records[menues.Find(menue)]
Обычно работает. Find выдаёт порядковый номер. Но да, решение Людука элегантнее ибо не нужно лишнего прока.

2023-03-26 14:09 UTC, DarthSidiousPalpatine commented on code/game/machinery/vending.dm
> +				var/players_coefficient = num_players() / 50 //100 players = double load, 50 players = max load, 0 players = min load
Да и потому я убрал кламп до 1.0 и сделал кламп до 2.0

2023-03-26 14:09 UTC, DarthSidiousPalpatine commented on code/game/machinery/vending.dm
> +		for(var/typepath in menue)
зачем нужно as anything и указание на atom если в оригинале этого не было.

2023-03-26 14:11 UTC, DarthSidiousPalpatine commented on code/game/machinery/vending.dm
> +	build_menue()
я немец кста

2023-03-26 14:12 UTC, LudwigVonChesterfield commented on code/game/machinery/vending.dm
> +				var/players_coefficient = num_players() / 50 //100 players = double load, 50 players = max load, 0 players = min load
верни 75... мы же считали что для 75-и будет премного достаточно еды при 1.0, а значит для 50-и будет премного достаточно * 1.5

2023-03-26 14:12 UTC, DarthSidiousPalpatine commented on code/game/machinery/vending.dm
> +				var/players_coefficient = num_players() / 50 //100 players = double load, 50 players = max load, 0 players = min load
Люди голодны, милорд.

2023-03-26 16:33 UTC, DarthSidiousPalpatine commented
Сделал всё что хотел и пофиксил всё что хотел.

2023-03-26 16:34 UTC, LudwigVonChesterfield commented on code/game/machinery/vending.dm
> +			records[menus.Find(menue)] += R
почему не сделал как я предлагал с ```for(var/i in 1 to length(menu))```?

2023-03-26 16:48 UTC, DarthSidiousPalpatine commented on code/game/machinery/vending.dm
> +			records[menus.Find(menue)] += R
потому что так проще

2023-03-27 02:36 UTC, LudwigVonChesterfield commented on code/game/machinery/vending.dm
> +			records[menus.Find(menue)] += R
нет не проще, сделай

2023-03-27 02:37 UTC, LudwigVonChesterfield commented on code/game/machinery/vending.dm
> +/obj/machinery/vending/proc/build_inventory(list/productlist, roundstart = FALSE, hidden = 0, req_coin = 0 , req_emag = 0)
почему закрыт коммент без ответа на него

2023-03-27 02:37 UTC, LudwigVonChesterfield commented on code/game/machinery/vending.dm
> +			records[menus.Find(menu)] += R
мне не нравится цикл в цикле в цикле когда можно так не делать. пожалуйста переделай так чтобы не юзать menus.Find, спс

2023-03-27 02:52 UTC, DarthSidiousPalpatine commented on code/game/machinery/vending.dm
> +/obj/machinery/vending/proc/build_inventory(list/productlist, roundstart = FALSE, hidden = 0, req_coin = 0 , req_emag = 0)
ответ: Б

2023-03-27 04:08 UTC, DarthSidiousPalpatine commented on code/game/machinery/vending.dm
> +			var/list/needed_records = records[menues.Find(menue)]
Сделал

2023-03-27 04:08 UTC, DarthSidiousPalpatine commented on code/game/machinery/vending.dm
> +			records[menus.Find(menu)] += R
Окей, сделал

2023-03-27 04:08 UTC, DarthSidiousPalpatine commented on code/game/machinery/vending.dm
> +			records[menus.Find(menue)] += R
Как ты просил так и сделал.

2023-03-27 04:51 UTC, DarthSidiousPalpatine commented on code/game/machinery/vending.dm
> +	if(SSticker.current_state == GAME_STATE_PLAYING)
зачем

2023-03-27 04:52 UTC, DarthSidiousPalpatine commented on code/game/machinery/vending.dm
> +	if(SSticker.current_state == GAME_STATE_PLAYING)
оно не нужно тут проверять

2023-03-27 04:53 UTC, kalazus commented on code/game/machinery/vending.dm
> +	if(SSticker.current_state == GAME_STATE_PLAYING)
Чтобы не делать кучу одинаковых проверок дальше и регистрировать меньше сигналлов

2023-03-27 04:56 UTC, DarthSidiousPalpatine commented on code/game/machinery/vending.dm
> +	if(SSticker.current_state == GAME_STATE_PLAYING)
Тут - не надо проверки. Проверки нужны далее. Если тут сделать то всё сломается.

2023-03-27 04:57 UTC, DarthSidiousPalpatine commented on code/game/machinery/vending.dm
> +	if(SSticker.current_state == GAME_STATE_PLAYING)
а, блен, ладно, может, и не сломается.

2023-03-27 05:00 UTC, DarthSidiousPalpatine commented on code/game/machinery/vending.dm
> +	if(SSticker.current_state == GAME_STATE_PLAYING)
Окей, сделал.

2023-03-27 18:14 UTC, KIBORG04 commented
Почему пр с хот фиксом критического бага уже лежит 4ю неделю?

2023-03-27 22:06 UTC, LudwigVonChesterfield commented on code/game/machinery/vending.dm
> +/obj/machinery/vending/proc/build_inventory(list/productlist, roundstart = FALSE, hidden = 0, req_coin = 0 , req_emag = 0)
почему бы не 
build_menu переименовать в build_inventory
а build_inventory в load_inventory

2023-03-31 12:50 UTC, DarthSidiousPalpatine commented
готово кароч

2023-03-31 13:41 UTC, LudwigVonChesterfield commented on code/game/machinery/vending.dm
> +	if((SSticker.current_state == GAME_STATE_PLAYING) || !is_station_level(z) || private)
из-за ис стейшон левел вендоматы Велосити и шахты всегда полны. задумано?

2023-03-31 13:42 UTC, DarthSidiousPalpatine commented on code/game/machinery/vending.dm
> +	if((SSticker.current_state == GAME_STATE_PLAYING) || !is_station_level(z) || private)
Ну, да. Кроме шахты, блин....

2023-03-31 13:42 UTC, DarthSidiousPalpatine commented on code/game/machinery/vending.dm
> +	if((SSticker.current_state == GAME_STATE_PLAYING) || !is_station_level(z) || private)
Но можно уже на это глаза закрыть?

2023-03-31 13:43 UTC, LudwigVonChesterfield commented on code/game/machinery/vending.dm
> +		load_products(FALSE)
```suggestion
		load_products(roundstart=FALSE)
```

2023-03-31 13:43 UTC, LudwigVonChesterfield approved these changes
looks good to me

2023-03-31 13:45 UTC, DarthSidiousPalpatine commented on code/game/machinery/vending.dm
> +		load_products(FALSE)
Сейчас верну придёт Киборг снова скажет удалить 🤡

2023-03-31 13:47 UTC, LudwigVonChesterfield commented on code/game/machinery/vending.dm
> +		load_products(FALSE)
@KIBORG04 зачем удалять если так красивее..

2023-03-31 13:47 UTC, LudwigVonChesterfield commented on code/game/machinery/vending.dm
>  	return
если он не нужен почему он тут...

2023-03-31 13:48 UTC, DarthSidiousPalpatine commented on code/game/machinery/vending.dm
>  	return
я думал он ретурн требует выше типа в ифке

2023-04-01 01:38 UTC, LudwigVonChesterfield requested changes
ждём фикса полных вендоматов на шахте и Велосити..

2023-04-05 14:43 UTC, closed without merging