Suit jackets resprites + starting accessories
TauCetiStation/TauCetiClassic pull request #10920
Opened 2023-03-04 17:29 UTC by AndroBetel

## Описание изменений
![image](https://user-images.githubusercontent.com/44546836/222920231-ef99373f-4c3f-4925-9d42-193165724df0.png)
удалил парочку некрасивых или повторяющихся костюмов
сделал возможность спавна одежды сразу с налепленными аксессуарами
## Почему и что этот ПР улучшит
я
## Авторство
эрис+я
## Чеинжлог
:cl:
- image: Респрайт деловых костюмов.

2023-03-04 17:29 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2023-03-04 17:40 UTC, Tap0r commented
Сразу с галстуком спавн???????

2023-03-04 17:45 UTC, AndroBetel commented
yess

2023-03-04 17:58 UTC, NikMaestro commented
На тонкотропов будет??

2023-03-04 18:21 UTC, AndroBetel commented
есть

2023-03-04 21:50 UTC, Mercurialaste commented
аксессуары с флафф слота?

2023-03-04 22:24 UTC, KIBORG04 commented on code/modules/clothing/clothing.dm
> +		LAZYADD(accessories, T)
А зачем этот LAZYADD ? Почему он_аттачед это не делает

2023-03-05 05:44 UTC, UDaV73rus requested changes
Не нравятся цвета галстуков

![image](https://user-images.githubusercontent.com/33157992/222943659-dc23dcb2-5947-4c27-a0ce-146d796951b5.png)
пиджак зад зажевал?????? В общем проблема со светом дикая, нужно более осмысленно к этому подойти.

2023-03-05 05:47 UTC, AndroBetel commented
женские спрайты ето пиздец

2023-03-10 04:24 UTC, LudwigVonChesterfield commented
Походу нужно колаборироваться с спрайт депом и менять цвета галстуков.

2023-04-10 11:49 UTC, closed without merging