Карты из текущего раунда не будет в списке votemap
TauCetiStation/TauCetiClassic pull request #10929
Opened 2023-03-05 17:57 UTC by KandreyKandrey

## Описание изменений
Карты из текущего раунда не будет в списке votemap
## Почему и что этот ПР улучшит
Прометей и Гамма станут более частыми гостями
## Авторство
-
## Чеинжлог
:cl:
 -tweak: Карты из только что прошедшего раунда не будет на голосовании

2023-03-05 17:57 UTC, TauKitty commented
###### Changelog status: :x: Empty changelog (check markdown correctness)

2023-03-05 17:59 UTC, Deahaka commented
![image](https://user-images.githubusercontent.com/96499407/222977499-a7640008-88d5-4069-b831-1b4f7df2d5a5.png)
my honest reaction

2023-03-05 18:00 UTC, DarkFurrSss commented
Пипец, вроде и банальная, но гениальная идея

2023-03-05 18:19 UTC, TryXAH commented
Этой идей столько же лет, сколько уже воуты замерженны. Вообще, было бы неплохо как то сделать модификаторы голоса за мапу, и чем больше она подряд стоит, тем меньше у нее модификатор, но это в идеале

2023-03-05 18:33 UTC, NikMaestro commented
Уберите боксодрочеров от экрана, остальных поздравляю!!

2023-03-05 19:26 UTC, KIBORG04 commented
> Прометей и Гамма станут более частыми гостями

И почему это хорошо

2023-03-05 20:02 UTC, KandreyKandrey commented
Более быстрый поиск багов/недочётов

2023-03-05 20:13 UTC, Sakuya-Izayoi commented
> Более быстрый поиск багов/недочётов

ну хорошо, баги мы найдем, а фиксить кто будет? если кандрей будет поддерживать гамму и прометей то я конечно за, но скорее всего получится что мы будем заставлять игроков играть на попросту плохих картах.

2023-03-05 20:14 UTC, Sakuya-Izayoi requested changes

2023-03-05 20:14 UTC, Sakuya-Izayoi commented on code/controllers/subsystem/voting/poll_types.dm
> +		if(vc.mapname != SSmapping.config.map_name)
эту ифку выше. зачем создавать вотчойс если мы не будем добавлять его никуда

2023-03-05 20:32 UTC, KandreyKandrey commented
Попросту плохую карту никто бы не стал мержить.
Плюс, недочёты сначала надо найти, а потом уже искать маппера.

2023-03-05 22:42 UTC, Sakuya-Izayoi commented
> Попросту плохую карту никто бы не стал мержить. Плюс, недочёты сначала надо найти, а потом уже искать маппера.

у нас там список недочетов на десять лет вперед, почитай ишьюсы и мап канал. как пофиксишь - можно мержить

2023-03-06 18:21 UTC, closed without merging

2023-03-06 18:21 UTC, AndroBetel commented
открой обратно все карты играбельны а все недочеты это фичи