[DNM] Gamma Map Edit. Dormitories and some tunnels
TauCetiStation/TauCetiClassic pull request #10947
Opened 2023-03-07 17:39 UTC by Deahaka

## Описание изменений
Обновление недотроги Гаммы в соответствии с [планом](https://discord.com/channels/401030271417188353/405006856134852608/1073878917527633960)
## Почему и что этот ПР улучшит
![000000000000000000000000000000000000007 - копия](https://user-images.githubusercontent.com/96499407/223503604-d9aa714e-2362-42af-80cb-acaf57b7be52.png)
![000000000000000000000000000000000000007](https://user-images.githubusercontent.com/96499407/223503631-ea840a31-97c1-44b9-a03e-825f6b6126ff.png)
![0000000000000000000000000000000000](https://user-images.githubusercontent.com/96499407/223503644-16e3db1b-1c8d-40a5-adac-4eb28165936e.png)
![00000000000000000000000000000000003](https://user-images.githubusercontent.com/96499407/223503658-3706809e-c46b-4ef4-9eca-d3825ebb91be.png)

## Авторство

## Чеинжлог
:cl: Deahaka
- map: Дормитории и ближайшие технические тоннели на NSS Gamma получили немного косметических изменений.

2023-03-07 17:39 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2023-03-07 18:49 UTC, Deahaka commented
Я так понимаю, там был баг, что конвеер в офисе мусорщиков двигался не в ту сторону, повернул его в нужном направлении и подвинул, чтобы не выбрасывал за пластиковые флапертрапы

2023-03-07 19:06 UTC, Tap0r commented
Вместо кучки непонятных ингейм скринов маленьких куда лучше кидать сразу один большой скрин всего. Чтобы можно было оценивать изменения в целом, а не кусками разрозненными. 

Что касается ремапа. Хоть это и гамма, свои пять копеек касательно общих ошибок всуну.

Проблемы с плиткой. На входе у барбера она желтая, ведь раньше там майтенс шлюз был. Вдоль стены почему-то обрывается, видать там раньше тоже какой-то шлюз был.
В церкви ступеньки странные диры имеют. В качалке старые плохо выглядящие ступеньки, к тому же на них фаердуры, что еще плюс к уродству дает. Я бы либо ступеньки убрал, либо фаердуры. Вместе им быть не надо.

Касательно техов, видно расширение, но кишка за северной комнатой дорм все еще имеется, раз уж начал расширять, ее бы тоже убрать.

Также раз уж решил трогать дормы, то глянь у переработчиков зону шлюза, там аж 2 стенки четверные. Я бы это тоже пофиксил.

Назвал тут только общие ошибки какие на глаза попались, касательно структуры пусть лучше энерти пишет.

![IMG_20230307_225213.jpg](https://user-images.githubusercontent.com/88531962/223523935-24d8a9d5-8774-46a7-a300-f6349ed77b94.jpg)
![IMG_20230307_225257.jpg](https://user-images.githubusercontent.com/88531962/223524399-fba566ec-6328-49e6-a823-c8026f7c86d8.jpg)
![IMG_20230307_225401.jpg](https://user-images.githubusercontent.com/88531962/223524426-1249f659-f220-4913-b6b1-0705dfc502ed.jpg)
![IMG_20230307_225505.jpg](https://user-images.githubusercontent.com/88531962/223524981-d5e919d1-4dd3-4b62-9a0e-2ca29e4ab09a.jpg)
![IMG_20230307_225549.jpg](https://user-images.githubusercontent.com/88531962/223525000-9ddcc101-5477-4456-9077-2e262bee6c78.jpg)
![IMG_20230307_225704.jpg](https://user-images.githubusercontent.com/88531962/223525013-d0865ab0-e377-41cf-9ed7-9fb44e9a9039.jpg)

2023-03-07 19:27 UTC, Deahaka commented
Спасибо! Пофиксил и залил фоточку большую одну.
Кишку не убирал, очевидно что её там никак хорошо не расширить если оставлять ту дорму.
Ступеньки в качалке и у ринга не трогаю так как хз как к этому относится Энерти.

2023-03-08 05:33 UTC, Enerty requested changes
Мне не нравится и я все сделаю сам, еще в дискорде я писал что конкретно с этим "Планом" не так. Более того, ремапы до фиксов смысла не имеют.

2023-03-08 06:32 UTC, Deahaka commented
Ждём пока будут "реальные" изменения, а потом уже делаем карту лучше.

2023-03-08 06:32 UTC, closed without merging