Нерф взрывного диализа
TauCetiStation/TauCetiClassic pull request #10994
Opened 2023-03-13 12:55 UTC by ssbugman

## Описание изменений
Взрыв и ЕМП больше не удаляют из холдера все прочие реагенты.

## Почему и что этот ПР улучшит
Удаление 100 кубиков химикатов при реакции 1 кубика калия абсурдно и по сути является читерским абузом. 

## Авторство

## Чеинжлог
:cl:
- bugfix: Взрывы калия и нитроглицерина а также ЕМП больше не удаляют все остальные реагенты.

2023-03-13 12:55 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2023-03-13 14:20 UTC, ssbugman commented
> предлагаю сделать что количество реагентов которое убрано зависит от количества калие и воды и тд.

Вообще нет смысла в этом. Взрыв в венах должен вызывать артериалку а не диализ.

2023-03-13 14:21 UTC, kiVts commented
> > предлагаю сделать что количество реагентов которое убрано зависит от количества калие и воды и тд.
> 
> Вообще нет смысла в этом. Взрыв в венах должен вызывать артериалку а не диализ.

Ну так сделай артериалку и диализ

2023-03-13 14:37 UTC, ssbugman commented
> Ну так сделай артериалку и диализ

Диализ вообще никаким боком тут не может быть. Химикатам некуда деться.

2023-03-13 16:15 UTC, LudwigVonChesterfield commented on code/modules/reagents/Chemistry-Recipes.dm
> +	holder.del_reagent(id)
мне кажется даже это не нужно, вещества при реакции ведь и так удаляются в нужном объёме.

2023-03-13 16:16 UTC, LudwigVonChesterfield approved these changes
жаль конечно что убивают такой старый интересный медицинский абуз, но думаю медики переживут и это...

по поводу имплементации - мне кажется реагенты вовсе удалять не надо, это должно хендлиться системой реакций и так

2023-03-13 16:16 UTC, LudwigVonChesterfield commented on code/modules/reagents/Chemistry-Recipes.dm
> +	holder.del_reagent(id)
тем более в текущей имплементации оно пытается удалять реагент с айди реакции ("explosion_potassium"), которого и вовсе не существует :)

2023-03-15 15:20 UTC, LudwigVonChesterfield commented
Слушай, сейчас думал и вспомнил как часто быстрый диализ таки очень нужен... Есть ли вариант добавить какой-то другой рецепт который легетимизирует фичу с диализом?

2023-03-16 09:07 UTC, arygal commented
У нас кукла может держать в себе огромное количество реагентов(Кега пива на 1000 юнитов). Пчелу всю кровь высосем пока диалез будет.

2023-03-16 09:09 UTC, Mercurialaste commented
> У нас кукла может держать в себе огромное количество реагентов(Кега пива на 1000 юнитов). Пчелу всю кровь высосем пока диалез будет.

Тк, подобные реагенты вполне легко выводить с помощью даже простых пальцев себе же в рот. Пиво насыщает, из-за чего кукла может блевать, ну мы и блюеем, пока все пиво не выйдет.

2023-03-18 08:07 UTC, Sakuya-Izayoi commented
> Вспомнил о паре кейсов где нужна возможность быстро выкачать все реагенты из куклы, прошу добавить реакцию на замену взрывному диализу.

Тут стоит придумать че-то как в случае с анти-токсином (который выводит все токсины) или как с этилредоксрацином (который выводит подтипы алкоголя). Ну и тебе стоит расписать что это за кейсы где нужно быстро выкачать все реагенты из куклы, может это их надо фиксить, а не мгновенный диализ. Пока что это выглядит так будто медбей трапы у тебя заказали блок на пр 🙂 

Ну и мгновенный диализ это одна из причин почему смешные фичи типо ядов не работают, так что пока ты не объяснишься я скорее против.

2023-03-18 22:36 UTC, LudwigVonChesterfield requested changes
del_reagent который везде натыкан в данный момент ничего не делает, его можо просто убрать.

2023-03-20 14:14 UTC, LudwigVonChesterfield commented on code/modules/reagents/Chemistry-Recipes.dm
> +	holder.del_reagent(id)
```suggestion
	holder.del_reagent(result)
```

2023-03-20 14:14 UTC, LudwigVonChesterfield commented on code/modules/reagents/Chemistry-Recipes.dm
> +	holder.del_reagent(id)
```suggestion
```

2023-03-20 14:15 UTC, LudwigVonChesterfield commented on code/modules/reagents/Chemistry-Recipes.dm
> +	holder.del_reagent(id)
(в чем смысл создавать реагент а потом его удалять?)

2023-03-26 04:34 UTC, LudwigVonChesterfield approved these changes
ладно пох подтолкнёт фиксить то что в кукле может быть 1000 реагентов

2023-03-28 00:58 UTC, merged