Изменение формулы сбоя конечности
TauCetiStation/TauCetiClassic pull request #11005
Opened 2023-03-13 21:01 UTC by Dominig12

## Описание изменений
Изменена формула по которой каждый тик моба конечности с определенным шансом роняли предметы или персонаж падал. Это коснулось всех киборгизированных конечностей.
Ранее шанс считался по формуле БЕРН+БРУТ = шанс
prob(brute_dam + burn_dam)

Сейчас идет подсчет по БЕРН + БРУТ, но максимальный шанс 25%
prob(min(brute_dam + burn_dam, 25))

Причина почему я решил поставить 25%, это во первых то, что при уроне в 25 единиц на каждой конечности, какая то из них точно будет сдавать позиции. Если повреждены обе ноги 50% шанс что человек будет падать каждый тик моба. Если повреждена рука, то 25% шанс что он выронит из рук что либо.
Учитывая добавление задержки нанопасты в 10 тиков, то 25% ее уронить выглядит не как что то слишком сильно ломающее желание жить.

По старой формуле, если у тебя накопится 100 урона, то это 100% шанс уронить или упасть, а это значит ты физически ничего использовать не успеешь. Возможно максимальное значение шанса можно подкорректировать, но локальные тесты показали что 25% это хорошее значение

## Почему и что этот ПР улучшит
Подгонка механики поврежденных конечностей под изменение использования нанопасты = Нормальный игровой экспириенс

## Авторство
1DarkWater1
## Чеинжлог
🆑 1DarkWater1
- balance: Изменена формула расчета шанса отказа механической конечности при повреждениях ( при сильных повреждениях будет шанс пошевелится )

2023-03-13 21:01 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2023-03-13 21:07 UTC, TauKitty commented
Этот запрос на слияние был упомянут в **Tau Ceti Station Forum**. Там могут быть соответствующие подробности:

https://forum.taucetistation.org/t/spu-hotyat-nerfanut-v-govno-a-ya-ne-hochu/38469/59

2023-03-13 21:12 UTC, LudwigVonChesterfield commented
Если у тебя 100 урона на руке почему ты ещё не умер...

2023-03-13 21:21 UTC, Dominig12 commented
https://youtu.be/PhADMN-jI64

2023-03-13 21:24 UTC, Mercurialaste commented
Не ведитесь, там фишинг

2023-03-13 21:28 UTC, pro100kotah commented
Перешел по ссылке и с моего счета списали все деньги

2023-03-14 04:24 UTC, Dominig12 commented
> Если у тебя 100 урона на руке почему ты ещё не умер...

Урон на протезы не создает боли, хуман с протезом может получить туда 100 урона но он не упадет в крит от боли

2023-03-14 04:32 UTC, Dominig12 commented
> https://youtu.be/PhADMN-jI64

Тут кстати как сейчас, то есть при каждом тике жизни ты роняешь предмет, если будут поломана нога, то так же каждый тик падать

2023-03-26 04:37 UTC, LudwigVonChesterfield requested changes
Абсолютно незаслуженный бафф протезов.

У хуманов руки ломаются примерно после 30-и урона по ним и 100% дроппают предмет в руке каждых две секунды

У протезов же по-твоему почему-то должен быть 25% шанс дропа при том же уроне что и у хуманов. Это при том что протезы ещё и не дают боль, и могут чиниться подручными инструментами.

2023-04-16 11:06 UTC, closed without merging