станпрод апдейт
TauCetiStation/TauCetiClassic pull request #11016
Opened 2023-03-15 08:31 UTC by simb11

## Описание изменений
станпрод теперь не помещается в рюкзаки, пояса и держатели для дубинок, ДОБАВЛЕН ТОЛЬКО ФЛАГ, размер я не менял
станпроды можно таскать в слоте рюкзака, а ещё теперь бросок станпалки с некоторым шансом нанесёт болеурон врагу.
## Почему и что этот ПР улучшит
очень странно что САМОДЕЛЬНАЯ дубинка по почти всем параметрам превосходит обычную, из плюсов у самоделки:
не требует умений
может бить через тайл
возможность перезаряжать прод с помощью батареек, из этого вытекает возможность вставить батарейку на 40 тыщ энергии, которая даст владельцу дубинки сделать до 20 ударов без перезарядки

у самодельной дубинки всего два спорных минуса:
она не наносит болеурон при броске (кто вообще бросает дубинку с целью застанить кого-то????????)
батарейки можно зарядить только в селл речарджерах (зачем перезаряжать если можно носить 3-4 батарейки в рюкзаке?)

короче, на мой личный взгляд станпрод не должен быть намного лучше обычной дубинки

если кто-то думает, что станпроды перестанут использовать - посмотрите на тг, там они уже шесть лет живут с большими станпродами и, о удивительно, там их не перестали использовать.
## Авторство
спрайты взял с тг
## Чеинжлог
:cl: Simbaka
- balance: Самодельная дубинка не помещается в рюкзаки, пояса и ТД.

2023-03-15 08:31 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2023-03-15 08:39 UTC, TryXAH commented
какой же ты ужасный человек который нерфит всё и вся и не дает игрокам играть нормально в игру

2023-03-15 08:48 UTC, AndroBetel commented
нафиг ты сам себе дизлюкантропа поставмл

2023-03-15 08:49 UTC, AndroBetel commented
я бы на поясе разрешил его таскать

2023-03-15 08:49 UTC, simb11 commented
я напомню что я добавил только ФЛАГ, скорость передвижения никак не изменится

2023-03-15 08:50 UTC, Chip11-n commented
Ты в руках его не будешь носить. И на спину не закинешь, ибо рюкзак в руках хуже.

2023-03-15 08:51 UTC, simb11 commented
бегайте без рюкзака в руках
существует стопяццот способов переносить айтемы не в рюкзаке (пояс, разгрузка, кармашки)

2023-03-15 08:52 UTC, AndroBetel commented
у реверов еще будут станперчатки, лут шкафчиков офицеров, лут карго, лут рнд, лут из аплинка главреверов, обездоленными не останутся

2023-03-15 08:56 UTC, KIBORG04 commented
Весь твой пр абузится через оберточную бумагу

2023-03-15 09:10 UTC, TheLone1y commented
Аааа дурак оберточную бумагу понерфь, а так норм аппруваю

2023-03-15 09:15 UTC, Deahaka commented
То что самодельная дубинка превосходит обычную это последствие введения "скилов" на сбшную палку, что ты её ни включить ни выключить без 5-секундного ду-афтера не можешь. Без этого они будут практически равны по балансу:
одна имеет кучу ударов, урон даже выключенной, не требует усилий для перезарядки, не требует лишнего места в рюкзаке, при кидании наносит болеурон столько же сколько и при ударе со 100% шансом, а другая всё это не имеет, но зато можно попытаться через Ctrl+Click кого-то побить.

"короче, на мой личный взгляд станпрод не должен быть намного лучше обычной дубинки" - это изменение по факту не трогает ничего вышеперечисленное, а только не даёт юзать дубинку из стелс-мода. 
Хз зачем тут продвигается что это сделает станпрод значительно хуже чем СБшную, если это просто нерф шадоу и культа, так как у них это единственное оружие которое есть для борьбы и конверта, а во всех остальных режимах ничего по части "станпрод хуже дубинки" не изменится так как есть другие инструменты подаренные режимом или угрозу не надо маскировать из-за открытого противостояния.

2023-03-15 10:42 UTC, NikMaestro commented
another one. Нёрф, который никто не просил.
Факт того, что её нужно нёрфить - имеет место быть. Но не так, точно не так.

2023-03-15 10:56 UTC, Deahaka commented
Никто не говорил что её нужно нерфить. Nobody

2023-03-15 10:57 UTC, simb11 commented
если никто не говорит про проблему это не значит что её нет

2023-03-15 10:57 UTC, AndroBetel commented
все молча терпели
![image](https://user-images.githubusercontent.com/44546836/225289083-8b1be555-d6d1-46a0-964b-9e6e247b8c90.png)

2023-03-18 08:21 UTC, Sakuya-Izayoi commented
Что за красные линии на мобспрайтах?

2023-03-18 08:39 UTC, simb11 commented
Лямка типа
![image](https://user-images.githubusercontent.com/84613249/226094985-fab9a38d-1c1f-4e6a-8226-a5aaa65f680b.png)

2023-03-20 10:57 UTC, UDaV73rus requested changes
Лямка выглядит кринжово по превью дифбота, удали её совсем или докажи нормальными превьюшками что без неё хуже.

Анимация включенной странная, это же вилка между которыми искры скачат, а на спине это аура какяа-та во все стороны

Спрайт с батареей и без - не отличается

2023-03-22 04:43 UTC, UDaV73rus approved these changes

2023-03-22 14:00 UTC, TauKitty commented
Этот запрос на слияние был упомянут в **Tau Ceti Station Forum**. Там могут быть соответствующие подробности:

https://forum.taucetistation.org/t/udalenie-simbaki/38617/1

2023-03-26 04:06 UTC, LudwigVonChesterfield commented on code/game/objects/items/weapons/makeshift.dm
> +	if (prob(50))
Сделай пожалуйста ранний возврат
```
. = ..()
if(!prob(50))
    return
if(!ishuman(hit_atom))
    return

2023-03-26 04:06 UTC, LudwigVonChesterfield commented on code/game/objects/items/weapons/makeshift.dm
> +			var/mob/living/carbon/human/H = hit_atom
сверху проверка на ливинг, но здесь уже хуман

2023-03-26 04:06 UTC, LudwigVonChesterfield commented on code/game/objects/items/weapons/makeshift.dm
> +				for(var/mob/M in player_list) if(M.key == src.fingerprintslast)
у throwingdatum есть .thrower для этого

2023-03-26 04:07 UTC, LudwigVonChesterfield commented on code/modules/recycling/sortingmachinery.dm
> +	if(O.flags_2 & CANT_BE_INSERTED)
это разве не сломает вещи кроме рюкзака?... не знаю там дестрактив анализатор или что-то такое

2023-03-26 04:07 UTC, LudwigVonChesterfield approved these changes
не вижу причин не мержить, тем более после бафа бол

копья же не помещаются в рюкзак почему станпрод должен...

2023-03-27 02:36 UTC, LudwigVonChesterfield commented on code/game/objects/items/weapons/makeshift.dm
> +		for(var/mob/M in player_list) if(M.key == src.fingerprintslast)
нужно вместо этого костыля юзать throwingdatum.thrower

2023-03-27 02:36 UTC, LudwigVonChesterfield requested changes
коммент про thrower

2023-03-27 09:21 UTC, ssbugman commented
Бессмысленное разоружение антагов. Без стелс мода станпрод бесполезен, на него мгновенно заагрится вся СБ.
То что у антагов есть скиллы на станбатон это бред - у антагов нет станбатона.
Кто-то как я виду разучился смотреть на баланс в целом и не понимает что антаги живут по сути ровно до момента пока о них узнает СБ, то есть важно чтобы у тритора-шедоу-прочих была возможность положить офицера прежде чем тот начнет мансить жопой и выкрикивать что Жамес Морган - трейтор.

2023-03-27 09:54 UTC, simb11 commented on code/game/objects/items/weapons/makeshift.dm
> +		for(var/mob/M in player_list) if(M.key == src.fingerprintslast)
сделал

2023-03-27 22:12 UTC, LudwigVonChesterfield commented on code/game/objects/items/weapons/makeshift.dm
> +		H.visible_message("<span class='danger'>[src], thrown by [T.name], strikes [H]!</span>")
нет проверки на то что T - нулл.

thrown by null, strikes H!

2023-03-28 11:35 UTC, simb11 commented on code/game/objects/items/weapons/makeshift.dm
> +		H.visible_message("<span class='danger'>[src], thrown by [T.name], strikes [H]!</span>")
вроде сделал проверку

2023-03-28 22:51 UTC, LudwigVonChesterfield commented on code/game/objects/items/weapons/makeshift.dm
> +		if(isnull(T.name))
```suggestion
		if(!T)
```

2023-03-28 22:52 UTC, LudwigVonChesterfield approved these changes

2023-03-31 13:48 UTC, merged