Cyborg + Zurek = Kerfus! New borg sprite
TauCetiStation/TauCetiClassic pull request #11025
Opened 2023-03-15 22:32 UTC by Deahaka

## Описание изменений
![000000000000000000000000000000000000007](https://user-images.githubusercontent.com/96499407/225458001-d99e3c07-73ce-43db-ae94-c1ab53b89f95.png)

## Почему и что этот ПР улучшит
Новый спрайты ура. А ещё этого пока нет на других билдах, а достопочтенный автор разрешил использовать его работу для ПРа.
## Авторство
[PigeonVerde aka PestoVerde or PestoVerde322](https://github.com/PestoVerde322)
но некоторые вещи я натыкал уже своими руками, так что если что-то не так, то скорее всего это Я сделал.
## Чеинжлог
:cl: PestoVerde322
- image: Добавлены новые спрайты боргов для модуля "Миротворец".

2023-03-15 22:32 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2023-03-15 22:33 UTC, AndroBetel commented
я ненавижу пшеков

2023-03-16 00:29 UTC, arygal commented
Выглядят как боты для доставки заказов с грузторга.

2023-03-16 01:00 UTC, girdas commented
эахахахахэхахвхазах

2023-03-16 04:05 UTC, PestoVerde322 commented
Dear god it's real.

2023-03-16 04:06 UTC, LudwigVonChesterfield commented
Жёлтый выглядит как инжеборг спрайт... Мейдочка выглядит как сервисборг спрайт...

2023-03-16 05:31 UTC, Tsar-Salat commented
> Dear god it's real.

My god... you actually did it...

2023-03-16 11:13 UTC, Pivo24 commented
Это лучшая хуйня которую я когда-либо видел

Вот они слева направо:

синто-няшка
флашед
мейдочка
ерп-полисман

2023-03-16 11:25 UTC, Sakuya-Izayoi commented
почему это не сервис борг непонятно... почему это вообще два разных борга сервис и миротворец непонятно

2023-03-16 11:29 UTC, Deahaka commented
Потому что спрайтик милый и безобидный, а пискипер как раз милый и безобидный по концепции. Когда спрайтдеп заревувает, посмотрю у каких боргов есть свободные места и может перенесу мейдочку в уборщика либо в сервис борга. Вроде там арсенала нет чтобы делать плохие дела.

2023-03-18 12:14 UTC, Deahaka commented
Распределил спрайты по модулям как Людук откоментил.

2023-03-18 22:38 UTC, LudwigVonChesterfield approved these changes
с кодом норм ждём аппрув Коискина

2023-03-19 13:19 UTC, UsadoSmokk approved these changes

2023-03-19 13:35 UTC, Deahaka commented
Обновлено описание ПРа. Обновлён вид четвёртой вариации керфуса, спасибо Коисцину за участие!

2023-03-19 15:39 UTC, KIBORG04 reviewed
Я лично отказываюсь это мержить, потому что мне не нравятся спрайты и то что на них нарисовано.

2023-03-20 10:43 UTC, UDaV73rus requested changes
МАЛО ТОГО ЧТО ФУРРИ КАЛ, ТАК ЕЩЁ И НЕ СМОГЛИ СДЕЛАТЬ КРАСИВО

https://user-images.githubusercontent.com/33157992/226316488-075fb108-873a-494a-84c4-25da0ffafdb2.mp4

2023-03-24 17:21 UTC, LudwigVonChesterfield commented
Я думаю учитывая что игроки и так могут просить педалей им всякие ерп спрайты @Mercurialaste на тебя смотрю, ставить на боргов то на фуррикаловость пох...

Киборчу не нравится что это отсылка на тупой ирл мем...

2023-03-24 17:29 UTC, BasiaBelov commented
УХАХАААААААААААА!!
Мне нравится это чудо!

2023-03-24 17:31 UTC, merged

2023-03-24 17:48 UTC, BasiaBelov commented
Так, стоп...