Респрайт и добавление новых знаков для Гусьбоксика.
TauCetiStation/TauCetiClassic pull request #11113
Opened 2023-03-23 18:00 UTC by DarthSidiousPalpatine

## Описание изменений
![image](https://user-images.githubusercontent.com/21008918/227302713-81522ab3-81c9-44d7-947f-59d2166172dc.png)

Новые знаки есть только в коде, на карте не расставлял ибо каждый сам решит надо ему или не надо и куда ставить.
Я вот на Гусьбоксике расставил всякое.

## Почему и что этот ПР улучшит
Расово верные, православные знаки, более контрастные, менее броские, унифицированные.

## Авторство
AndreyGysev и все все все, кто помогал в дискорде.

## Чеинжлог
 :cl:
  - image: Респрайт и добавление знаков опасности, отделов и пр.

2023-03-23 18:00 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2023-03-23 18:37 UTC, KIBORG04 commented
Чел, ты бот.

А вообще. АВД же, а не АДВ :rofl:
![image](https://user-images.githubusercontent.com/26389417/227314734-f9581bbc-4b75-4501-9f71-c2ccc62670a0.png)

2023-03-23 18:37 UTC, DarthSidiousPalpatine commented
> Чел, ты бот.
> 
> А вообще. АВД же, а не АДВ 🤣 ![image](https://user-images.githubusercontent.com/26389417/227314734-f9581bbc-4b75-4501-9f71-c2ccc62670a0.png)

это не авд, а Lawyer, который на деле коворкинг.

2023-03-23 18:38 UTC, KIBORG04 commented
Ааа, это АДВокат, ок.

2023-03-23 18:42 UTC, UsadoSmokk commented
отвратительно

2023-03-24 05:40 UTC, UDaV73rus requested changes
круглые выглядят грязно на контуре
![image](https://user-images.githubusercontent.com/33157992/227430596-231d8ee6-fe05-4cda-993a-5262956516a0.png)

здесь плюсик не нужен, центрируй
![image](https://user-images.githubusercontent.com/33157992/227430489-bf5567a7-c7ba-4030-af8e-334a72362ca7.png)

2023-03-24 20:14 UTC, NuxeLSadew commented
Даёшь русификацию, ееее

2023-03-26 13:05 UTC, DarthSidiousPalpatine commented
> круглые выглядят грязно на контуре ![image](https://user-images.githubusercontent.com/33157992/227430596-231d8ee6-fe05-4cda-993a-5262956516a0.png)
> 
> здесь плюсик не нужен, центрируй ![image](https://user-images.githubusercontent.com/33157992/227430489-bf5567a7-c7ba-4030-af8e-334a72362ca7.png)

Не имеет смысла центрировать. Да и плюсик убирать, в данный момент знак общеизвестный именно в таком виде.
Про грязность кругов попробую что-то сделать.

2023-05-09 13:35 UTC, DarthSidiousPalpatine commented
Окей, второй шанс.

2023-05-09 13:36 UTC, DarthSidiousPalpatine commented
@UDaV73rus смотри, эти знаки больницы не используются в билде и нужны только для гусьбоксика. Они такие потому что нужны для моей карты. Можно ты закроешь глаза на знаки больницы и пропустишь это в мерж?

2023-05-11 00:02 UTC, LudwigVonChesterfield commented
не думаю что есть смысл мержить вне Гусьбоксика

2023-05-11 02:41 UTC, TryXAH commented
Гусев просто залей только желтые знаки сначала, они всем нравятся и нормально пройдут. Как все привыкнут после мержа, выкатывай остальные

2023-05-11 02:51 UTC, DarthSidiousPalpatine commented
> Гусев просто залей только желтые знаки сначала, они всем нравятся и нормально пройдут. Как все привыкнут после мержа, выкатывай остальные

Нет, синие тоже нужны и знаки с одеждой тоже нужны.

2023-05-11 03:11 UTC, TryXAH commented
> Нет, синие тоже нужны и знаки с одеждой тоже нужны.

Ну так залей отдельным пром, а так ни себе, ни людям

2023-05-26 18:25 UTC, LudwigVonChesterfield commented
ждём сам Гусьбоксик, без него знаки не нужны. если какие-то знаки респрайтятся вне контекста Гусьбоксика - делай отдельный ПР где говоришь про это.

2023-05-26 18:25 UTC, closed without merging