Зарплаты
TauCetiStation/TauCetiClassic pull request #11135
Opened 2023-03-26 16:28 UTC by DarthSidiousPalpatine

## Описание изменений
Все каргонцы перестали иметь зарплату. Шахтёр если не имеет дивидендов - зарабатывает на шахте рудой и так.

Бармен и повар имеют зарплату 5 кредитов, в качестве поддержки малого бизнеса.

## Почему и что этот ПР улучшит
Логику зарплат

## Авторство
AndreyGysev и все все все, кто помогал в дискорде

## Чеинжлог
 :cl:
  - tweak: Переделка некоторых зарплат цивилиан проф.

2023-03-26 16:28 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2023-03-26 16:32 UTC, Chip11-n commented
Мне совсем не нравится тенденция делать экономику обязательной, а не прикольной фишкой, для всё большего количества людей.

2023-03-26 16:36 UTC, LudwigVonChesterfield commented on code/game/jobs/job/civilian.dm
> +	salary = 5
почему бы не поставить 0?

люди думают что бармен у нас НТ-шный и оборудование у него НТ-шное и что он обязан бесплатно разливать

если зарплата будет 0 то так думать не будут...

2023-03-26 16:51 UTC, DarthSidiousPalpatine commented on code/game/jobs/job/civilian.dm
> +	salary = 5
Хз, мне кажется смешно если к ним сделать отношение как к ИП. Это забавно.

Ещё бы это как-то показывалось кроме низкой ЗП, которая запланирована как поддержка малого бизнеса....

2023-03-26 17:25 UTC, D3kr0s commented
Удаляйте ЗП всем, но главам сделайте под 500-1000. Главы будут лично в руки давать конверты с деньгами в соответствии с проделанной работой. Ну а фиг ли, мы же в логическую игру зарплат играем x)

2023-03-27 16:54 UTC, DedYarick commented
т.е теперь ты обязан быть жадной блядью и продавать все что мешаешь/готовишь/выращиваешь чтоб хоть как-то мочь себя прокормить >:(

2023-04-14 06:03 UTC, DarthSidiousPalpatine commented
Тут тоже, изменения минимальны. Это не замержат потому что мейнтейнеры против?

2023-04-15 18:43 UTC, DarthSidiousPalpatine commented
Раньше пр не мержили потому что слишком противоречиво.

ПОтому что сделал ещё противоречивее. Теперь повар, ботаник и бармен не имеют зарплаты вообще. Теперь они платят 5 кредитов раз в 15 минут за аренду своих отсеков. Урааааа.

2023-04-16 17:41 UTC, DarthSidiousPalpatine commented on code/game/jobs/job/civilian.dm
> +	salary = 5
Теперь я им -5 поставил. Пусть аренду платят за свои отсеки.

2023-04-18 13:34 UTC, LudwigVonChesterfield commented on code/game/jobs/job/civilian.dm
> +	salary = -5
в чем смысл если у нас нельзя уйти в долг и получить тюрьма

2023-04-18 13:37 UTC, volas commented on code/game/jobs/job/civilian.dm
> +	salary = -5
я бы этот момент выносил на форум на обсуждение еще, экономика ок но не когда она наказывает игрока просто потому что.

2023-04-18 14:29 UTC, DarthSidiousPalpatine commented on code/game/jobs/job/civilian.dm
> +	salary = -5
> в чем смысл если у нас нельзя уйти в долг и получить тюрьма

Пока лёгкий наказ на продажу вещей. Без продажи повар, бармен, ботаник не смогут ничего нигде купить, еды там, хз. Пусть работают и тогда уже могут что-то покупать.
Потом уже можно будет наказание делать какое-то. Пока что я тут наказания не вижу. Экономика это всё ещё флафф, в реалиях Тау Киты, Волас.

2023-04-21 02:50 UTC, TauKitty commented
Этот запрос на слияние был упомянут в **Tau Ceti Station Forum**. Там могут быть соответствующие подробности:

https://forum.taucetistation.org/t/nebolshaya-peredelka-zarplat-kargo-i-obslugi/39108/1

2023-04-30 04:02 UTC, DarthSidiousPalpatine commented
нет

2023-04-30 14:58 UTC, DarthSidiousPalpatine commented
С другой стороны да, Лижард прав.

2023-05-15 17:30 UTC, DarthSidiousPalpatine commented
Ну что, какие могут быть требования для мержа?
1) Убрать убирание зп повару/ботанику/бармену
2) Сделать им ЗП нулевое, вместо отрицательного

2023-05-15 17:37 UTC, LudwigVonChesterfield requested changes
я думаю как минимум нужно сделать зарплаты не отрицательными.

я уверен что сделать зарплату 0 Карго всем зайдет, а вот с цепью питания тяжелее.

на форуме люди выразили недовольство неудобством закупки по одной вещи поваром, лору того кем являются повар ботаник бармен на станции (частным предпринимателем, или прислугой)

я бы предложил отделить повара, ботаника, и бармена в отдельный ПР в котором сразу решатся проблемы лора (в описании расскажешь какие нужны правки), и проблемы кооперации (возможно добавишь те самые деревянные ящики против которых я так рьяно воевал, или добавишь в гайд на вики что можно продавать сумки с овощами...)

2023-05-15 17:41 UTC, DarthSidiousPalpatine commented
Окей, я удалил отсюда всех поваров ботаников барменов. Мерж.

2023-05-15 17:43 UTC, LudwigVonChesterfield approved these changes
думаю каргонцы абсолютно не почувствуют но это имеет какой-то смысл.

возможно создаст ситуации где шахтёры не будут бежать заносить ресурсы ученым потому-что денег хочется...

2023-05-19 03:10 UTC, merged

2023-05-19 11:21 UTC, volas commented
чеинжлог бы исправить (в репе чеинжлогов), сейчас что он есть, что его нету - ни о чем не говорит