Shards world/inventory icons
TauCetiStation/TauCetiClassic pull request #11147
Opened 2023-03-28 06:26 UTC by volas

## Описание изменений

Коммит с функциональными изменениями -> https://github.com/TauCetiStation/TauCetiClassic/commit/1699d97c55e6edbc2f3afae750d9ef3873b157ed

## Почему и что этот ПР улучшит

## Авторство

## Чеинжлог

:cl: WalterJe
 - image: Новые иконки осколков стекла с различным размером для инвентаря и мира

2023-03-28 06:26 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2023-03-28 06:54 UTC, volas commented
Вальтер продолжает рисовать свои world иконки для предметов, но их вставка в игру иногда требует небольших тивиков кода предметов, если у предмета есть хоть какая-то своя логика работы с иконкой. Вариации, оверлеи, анимации, изменения icon_state по каким-то условиям. Часто не большие, но не то, что было бы легко сделать человеку без опыта с кодом.

Нужен кто нибудь, кто-то согласился бы помочь с подобными реквестами. Я если что проконсультирую, и может по необходимости сделаю небольшую инструкцию про world иконки.

2023-03-28 07:23 UTC, AirBlack reviewed
Можно же как-нибудь обойтись без хаков

2023-03-28 07:23 UTC, AirBlack commented on code/defines/obj/weapon.dm
> +	if(icon_state == "large") // little hack so we don't overwrite our childs phoron and shrapnel icons
🤮

2023-03-28 07:31 UTC, AirBlack commented
> 

нажми details у IconDiffBot2

<details><summary>скрин но не все влезло сам нажми дурак блин</summary>
<p>

![image](https://user-images.githubusercontent.com/5171605/228161573-b123dd7d-cbc5-4e02-92d4-ecdc8fcbdd9a.png)


</p>
</details>

2023-03-28 07:50 UTC, AirBlack commented on code/defines/obj/weapon.dm
> +	if(icon_state == "large") // little hack so we don't overwrite our childs phoron and shrapnel icons
😢

2023-03-28 07:51 UTC, AirBlack commented
> в игре клоун

👺

2023-04-02 21:18 UTC, LudwigVonChesterfield commented
#11203 мы когда-нибудь обязательно это адрессуем..

2023-04-02 21:19 UTC, LudwigVonChesterfield commented on code/defines/obj/weapon.dm
> +/obj/item/weapon/shard/Bump()
как бампнуться об не-dense объект?

2023-04-02 21:25 UTC, volas commented on code/defines/obj/weapon.dm
> +/obj/item/weapon/shard/Bump()
может, если его бросили

2023-04-02 22:30 UTC, KIBORG04 commented on code/defines/obj/weapon.dm
> +/obj/item/weapon/shard/Bump()
Мб это тогда в какой-то after_throw ?

2023-04-08 12:31 UTC, UDaV73rus requested changes
Шрапнель же кроме как от выстрелов в тушу никак не получить??? Чего оно не пули, а листы металла

2023-04-08 12:33 UTC, volas commented
Подозреваю, что бы спрайт был виден и не было пиксельханта

2023-04-08 12:41 UTC, UDaV73rus approved these changes
ну лан, шрапнель действительно во всем себя ведет как осколки стекла, пусть будет. Надо будет как-нить сделать пульки

Добавь в мусор её!!!

2023-04-09 17:18 UTC, merged