Более удобное взаимодействие с полом репликаторов
TauCetiStation/TauCetiClassic pull request #11149
Opened 2023-03-28 09:00 UTC by Slavik2001

## Описание изменений
Были случаи когда хотели убрать руну над полом репликов, но нажимали на сам пол из-за чего открывался космос. Разгерма, все дела.
## Почему и что этот ПР улучшит
Да бы такого не повторялось, этот ПР будет проверять есть ли над полом руну и при наличии будет убираться руна, а не пол.
## Авторство
Людук
## Чеинжлог

2023-03-28 09:00 UTC, TauKitty commented
###### Changelog status: :radio_button: No changelog

2023-03-28 12:52 UTC, LudwigVonChesterfield approved these changes

2023-03-28 18:00 UTC, LudwigVonChesterfield commented on taucetistation.dme
> +#include "code\game\objects\items\weapons\syndie.dm"
вот тут что-то непонятное.

2023-03-28 21:14 UTC, Slavik2001 commented on taucetistation.dme
> +#include "code\game\objects\items\weapons\syndie.dm"
Это у меня после замерженого ПРа появилось. Прожал рефреш и поставил галочки

2023-03-28 22:45 UTC, LudwigVonChesterfield commented on code/modules/replicators/replicator_infrastructure.dm
> +	user.visible_message("<span class='notice'>[user] starts disarm [src].</span>", "<span class='notice'>You start disarm [src].</span>")
надо сделать так же как сдеалл для турфа
```
if(ispulsing && !user.is_busy()
    visible_message
    if(do_skilled
        visible message

2023-03-28 22:46 UTC, LudwigVonChesterfield requested changes
надо ещё доделать

2023-03-28 22:46 UTC, LudwigVonChesterfield commented on code/modules/replicators/replicators_forcefields.dm
> +		var/turf/simulated/floor/plating/airless/catwalk/forcefield/RB = locate()
```suggestion
		var/turf/simulated/floor/plating/airless/catwalk/forcefield/RB = loc
```

2023-03-29 19:53 UTC, LudwigVonChesterfield commented on code/modules/replicators/replicator_infrastructure.dm
> +		user.visible_message("<span class='notice'>[user] starts disarm [src].</span>", "<span class='notice'>You start disarm [src].</span>")
```suggestion
		user.visible_message("<span class='notice'>[user] starts disarming [src].</span>", "<span class='notice'>You start disarm [src].</span>")
```

2023-03-29 19:54 UTC, LudwigVonChesterfield commented on code/modules/replicators/replicators_forcefields.dm
> +		user.visible_message("<span class='notice'>[user] starts replace [src].</span>", "<span class='notice'>You start replace [src].</span>")
```suggestion
		user.visible_message("<span class='notice'>[user] begins replacing [src].</span>", "<span class='notice'>You begin replacing [src].</span>")
```

2023-03-29 19:55 UTC, LudwigVonChesterfield commented on code/modules/replicators/replicators_forcefields.dm
> +	var/obj/structure/bluespace_corridor/BR = locate() in src
мне кажется это нужно внести под if(ispulsing()):
```
if(ispulsing(C) && !user.is_busy())
    var/obj/structure/bluespace_corridor/BR = locate() in src
    if(BR)
       ...
       return
    visible_message( start destroying)
    if(do_skilled)```

сейчас наличие руны на турфе перекрывает любой клик по турфе чем-либо кроме плитки пола, а должен перекрывать только мультитул клик

2023-03-29 19:56 UTC, LudwigVonChesterfield commented on taucetistation.dme
> +#include "code\game\objects\items\weapons\syndie.dm"
(можешь попробовать у себя убрать галочку и тогда должно пропасть)

2023-04-01 21:28 UTC, merged