Перезарядка плазменного резака фороном.
TauCetiStation/TauCetiClassic pull request #11160
Opened 2023-03-29 07:37 UTC by F0xiq

## Описание изменений
Плазменный резак теперь можно заряжать фороном (листовым и рудой),что позволит полноценно шахтерам им копать (сейчас это не особо возможно из-за крайне быстрой разрядки).
## Почему и что этот ПР улучшит
Плазменный резак шахтер сможет на месте быстро заряжать фороном, не придется таскать с собой кучу резаков или как-то ещё извращаться.
## Авторство
  Код перезарядки плазменного резака взят с билда парадизов и переработан под реалии Тау.
## Чеинжлог
:cl:
 - add: Плазменный резак перезаряжается фороном (листовым и рудой)

2023-03-29 15:23 UTC, simb11 commented
сделай дуафтер небольшой, ибо перезарядка без кд это такое се, особенно если резак емагнут и будут использовать для убийства кого нибудь.

2023-03-30 04:21 UTC, F0xiq commented
На что дуафтер, на засовывание форона или перезарядку выстрела?

2023-03-30 07:24 UTC, simb11 commented
на вставку форона

2023-04-05 09:39 UTC, F0xiq commented
Добавлен do_after + перезарядка фороном из сумки шахтера

2023-04-07 07:48 UTC, volas requested changes

2023-04-07 07:48 UTC, volas commented on code/modules/mining/mine_items.dm
> +		S.use(1)
``use_tool`` включает в себя и use, и do_after, и проверяет необходимые условия за тебя (что юзер занят и т.п.)

2023-04-08 09:59 UTC, F0xiq commented on code/modules/mining/mine_items.dm
> +		S.use(1)
Можно и use_tool использовать.

2023-04-08 10:41 UTC, volas commented on code/modules/mining/mine_items.dm
> +		S.use(1)
там ниже у тебя еще другие do_after+use, их тоже можно заменить

2023-04-09 17:37 UTC, volas approved these changes

2023-04-09 17:39 UTC, volas commented
не уверен по поводу баланса, может оно так специально было а вовсе не случайно, посмотрим.

2023-04-09 17:39 UTC, merged