New/old families objectives
TauCetiStation/TauCetiClassic pull request #11218
Opened 2023-04-04 08:46 UTC by KandreyKandrey

## Описание изменений
Есть 20 лоуриск предметов, находящихся на станции в единственном экземпляре. Каждый раунд из этих 20 случайным образом выбираются 3 предмета(выбор может совпадать). Каждой банде из этих 3 выдаётся 1 (у банд цели могут совпасть)
## Почему и что этот ПР улучшит
больше столкновений банд между собой и с офицерами/главами
## Авторство

## Чеинжлог
:cl: Kandrey
- add: В режим families добавлены цели на лоуриск предметы, находящиеся на станции в единственном экземпляре

2023-04-04 08:50 UTC, KIBORG04 commented
Имхо, должно быть не просто "выбор может совпадать", а "выбор всегда совпадает", хотя бы у двух банд

2023-04-04 09:02 UTC, Chip11-n commented
Лоу риск а-ля ядерный диск, карта кэпа, дермал хоса 🙂 Или капский и Сб пульт. 

P. S. А в остальном, я уже хочу увидеть то, как банда устраивается горничными у кэпа, что бы украсть его плюшевую игрушку

2023-04-04 09:04 UTC, KandreyKandrey commented
Но ни один из этих предметов не выпадает триторам

P. S. по поводу горничной у кэпа - курс на рп!

2023-04-04 09:28 UTC, liteyzz commented
Согл с киборгом. И это . . . фезку можно за 1 поинт в лодауте взять . . .

2023-04-04 10:33 UTC, KandreyKandrey commented
> Имхо, должно быть не просто "выбор может совпадать", а "выбор всегда совпадает", хотя бы у двух банд

банд вроде всегда 3

если гарантированно делать совпадение целей, то как распределять?

может получиться, что две банды дерутся за один предмет, а третья сама по себе

2023-04-04 10:39 UTC, KIBORG04 commented
Можно попробовать выдавать задачу по  прилете дилеров. Там примерно ясно какие 2 банды сильные, а какая аутсайдер, вот и аутсайдерам можно дать задачу

2023-04-04 10:45 UTC, TheLone1y commented
И причем тут баланс

2023-04-04 10:50 UTC, TheLone1y commented
Всё ок

2023-04-04 12:23 UTC, TauKitty commented
Этот запрос на слияние был упомянут в **Tau Ceti Station Forum**. Там могут быть соответствующие подробности:

https://forum.taucetistation.org/t/novye-starye-czeli-bandam/38615/11

2023-04-04 16:27 UTC, simb11 commented
снабжающий пульт ДУ 🤮

2023-04-07 22:47 UTC, KIBORG04 commented on code/game/gamemodes/factions/families.dm
> +var/global/datum/objective/gang/steal_lowrisk/all/A = new
Что это за глобальная переменная с названием `A` ? Почему это так сделано...

2023-04-07 22:51 UTC, KIBORG04 commented on code/game/gamemodes/objectives/families/steal_lowrisk.dm
> +	return S
Не существует причин делать это подпитом от этого же обжектива. Этот же механ может быть у самих генгов. Выдача обжективов происходит уже после спавна всех банд и у тебя к ним есть доступ

2023-04-07 22:53 UTC, KIBORG04 commented on code/game/gamemodes/objectives/families/steal_lowrisk.dm
> +	return S
Ну или еще лучше, задача при спавне может сама делать это всё и сама себе выбирать задачу, текст ставить и тд, а не кем-то

2023-04-07 22:53 UTC, KIBORG04 commented on code/game/gamemodes/factions/families.dm
> +	AppendObjective(A.get_steal_objective())
То, что AppendObjective может принимать не только тип, но и объект, является скорее костылем, который сейчас уже не актуален и может быть спокойно удален.

2023-04-07 22:54 UTC, KIBORG04 commented on code/game/gamemodes/objectives/families/steal_lowrisk.dm
> +	var/static/todays_steal_objectives=list(pick(items_to_steal),pick(items_to_steal),pick(items_to_steal))
а еще жду форматирования, где будут пробелы до и после `=`, после `,` и тд

2023-04-14 20:27 UTC, KandreyKandrey commented
Целей теперь 1-2 (т.е совпадение у банд точно будет)

2023-04-14 20:29 UTC, KIBORG04 commented on code/game/objects/items/weapons/fulton.dm
> +	if(isitem(AM))
Это стоит перенести в дилерский фултон, а то тут это неуместно

2023-04-14 20:29 UTC, KIBORG04 commented on code/game/objects/items/weapons/fulton.dm
> +			if(possible_lowrisk_items_to_steal[objective] != AM.type)
```suggestion
		for(var/objective in global.possible_lowrisk_items_to_steal)
			if(global.possible_lowrisk_items_to_steal[objective] != AM.type)
```
just qol

2023-04-14 20:34 UTC, KIBORG04 commented on code/game/gamemodes/objectives/families/steal_lowrisk.dm
> +		objective = pick(items_to_steal)
Кринге.
Можно же так и все, лист статический и для всех инстансов оно должно быть убрано
```suggestion
	var/objective = pick(items_to_steal)
	items_to_steal -= objective
```

2023-04-14 20:34 UTC, KIBORG04 commented on code/game/gamemodes/objectives/families/steal_lowrisk.dm
> +	global.possible_lowrisk_items_to_steal[objective] = items_to_steal[objective]
Кринге.
Можно же так и все, лист статический и для всех инстансов оно должно быть убрано
```suggestion
	var/objective = pick(items_to_steal)
	global.possible_lowrisk_items_to_steal[objective] = items_to_steal[objective]
	items_to_steal -= objective 
```

2023-04-14 21:10 UTC, KandreyKandrey commented on code/game/objects/items/weapons/fulton.dm
> +	if(isitem(AM))
Уведомление об отказе стоит красным сделать? или синий сойдёт?

2023-04-14 21:13 UTC, KIBORG04 commented on code/game/objects/items/weapons/fulton.dm
> +	if(isitem(AM))
ну warning, красный

2023-04-28 21:33 UTC, KIBORG04 approved these changes
Ну, типа, вроде по коду мержабельно, но хз насчёт идеи как таковой

2023-05-01 15:19 UTC, volas commented on code/game/objects/items/weapons/fulton.dm
> +			return FALSE
хм

2023-05-01 15:20 UTC, volas commented on code/game/gamemodes/objectives/families/steal_lowrisk.dm
> +	global.possible_lowrisk_items_to_steal[objective] = items_to_steal[objective]
глобальный список не должен заполняться в столь специфичном месте

2023-05-01 15:21 UTC, volas commented on code/game/gamemodes/objectives/families/steal_lowrisk.dm
> +    var/static/items_to_steal = list("запасная карта капитана" = /obj/item/weapon/card/id/captains_spare,
было бы ок использовать английский и избавиться от специфичного хардкода названий

2023-05-01 15:21 UTC, volas requested changes
^

2023-05-04 03:06 UTC, LudwigVonChesterfield commented on code/game/gamemodes/objectives/families/steal_lowrisk.dm
> +	global.possible_lowrisk_items_to_steal[objective] = items_to_steal[objective]
(перенести в populate_lists или как его там где все датумлисты заполняются)

2023-05-04 03:07 UTC, LudwigVonChesterfield commented on code/game/gamemodes/objectives/families/steal_lowrisk.dm
> +	global.possible_lowrisk_items_to_steal[objective] = items_to_steal[objective]
это не глобальный список, а кеш. я думаю тут всё норм

2023-05-04 03:07 UTC, LudwigVonChesterfield commented on code/game/objects/items/weapons/fulton.dm
> +			return FALSE
что не так?

2023-05-04 03:08 UTC, LudwigVonChesterfield commented on code/game/objects/items/weapons/fulton.dm
> +			if(global.possible_lowrisk_items_to_steal[objective] != target.type)
```suggestion
			if(i!stype(target, global.possible_lowrisk_items_to_steal[objective]))
```

если по задумке нужно проверять на тип и подтип - то вот так

если почему-то на конкретный тип и так везде для этих лоу риск предметов - то как сейчас...

2023-05-04 03:08 UTC, LudwigVonChesterfield approved these changes
мне нрав идея как только зарезолвятся комменты Воласа готов мержить

2023-05-04 03:09 UTC, LudwigVonChesterfield commented on code/game/gamemodes/objectives/families/steal_lowrisk.dm
> +									 "феска ГП" = /obj/item/clothing/head/fez
её в лоадауте получить можно

2023-05-04 07:36 UTC, KandreyKandrey commented on code/game/objects/items/weapons/fulton.dm
> +			return FALSE
?
это чтобы контрабандист не продал искомые предметы

2023-05-04 07:45 UTC, KandreyKandrey commented on code/game/objects/items/weapons/fulton.dm
> +			if(global.possible_lowrisk_items_to_steal[objective] != target.type)
тут не без разницы? (у предметов в том списке же нет подтипов)

2023-05-04 09:38 UTC, KandreyKandrey commented on code/game/gamemodes/objectives/families/steal_lowrisk.dm
> +	global.possible_lowrisk_items_to_steal[objective] = items_to_steal[objective]
перенести заполнение в New ?

2023-05-04 09:40 UTC, KandreyKandrey commented on code/game/gamemodes/objectives/families/steal_lowrisk.dm
> +									 "феска ГП" = /obj/item/clothing/head/fez
убрал из списка (с другой стороны, кто-то будет из раунда в раунд брать феску, надеясь именно на эту цель?)

2023-05-04 09:41 UTC, KandreyKandrey commented on code/game/gamemodes/objectives/families/steal_lowrisk.dm
> +    var/static/items_to_steal = list("запасная карта капитана" = /obj/item/weapon/card/id/captains_spare,
заменил на английские названия

2023-05-04 09:47 UTC, KIBORG04 commented on code/game/gamemodes/objectives/families/steal_lowrisk.dm
> +	explanation_text = "Следующей целью будет [target]."
Странно звучит. Мб проще: "Украсть [нейм]"? Потому что странно видеть в списке задач "следующая цель" без описания че сделать и почему следующая

2023-05-04 09:48 UTC, KIBORG04 commented on code/game/gamemodes/objectives/families/steal_lowrisk.dm
> +	explanation_text = "Следующей целью будет [target]."
Ну и можно не на русском написать, ведь теперь предметы на инглише. Можешь взять текст с задачи тритора на воровство

2023-05-04 17:22 UTC, volas commented on code/game/gamemodes/objectives/families/steal_lowrisk.dm
> +    var/static/items_to_steal = list("captain's spare ID" = /obj/item/weapon/card/id/captains_spare,
я не достаточно хорошо написал комментарий в прошлый раз. Имел в виду, что хардкод названий тебе вообще не нужен, ни на русском, ни на английском (тем более, это вредно, если мы вдруг переименуем предметы) - ты можешь оперировать сразу типами, а если нужно имя - взять initial(type.name)

2023-05-04 17:23 UTC, volas commented on code/game/gamemodes/objectives/families/steal_lowrisk.dm
> +    var/static/items_to_steal = list("captain's spare ID" = /obj/item/weapon/card/id/captains_spare,
если нужно, я подробнее могу в дискорде расписать, только слапни

2023-05-04 17:30 UTC, volas commented on code/game/objects/items/weapons/fulton.dm
> +			return FALSE
мне показалось забавным хардкод проверки на предметы банды в коде фултона, но сейчас я вижу, что это именно фултон режима банд (нам катастрофически не хватает комментариев).

Другой момент - потеря предмета из раунда возможна многими способами, есть фритюр и карго шаттл и другие способы уничтожения, критично или нет не знаю.

2023-05-04 17:33 UTC, LudwigVonChesterfield commented on code/game/gamemodes/objectives/families/steal_lowrisk.dm
> +	global.possible_lowrisk_items_to_steal[objective] = items_to_steal[objective]
(две цели на воровство которые должны быть общие у банд чтобы был конфликт)

2023-05-04 17:34 UTC, KandreyKandrey commented on code/game/gamemodes/objectives/families/steal_lowrisk.dm
> +	global.possible_lowrisk_items_to_steal[objective] = items_to_steal[objective]
нам нужно гарантированное совпадение целей хотя бы у 2 банд.
банд всегда спавнится 3 -> делаем максимум 2 цели

2023-05-05 01:09 UTC, KandreyKandrey commented on code/game/gamemodes/objectives/families/steal_lowrisk.dm
> +    var/static/items_to_steal = list("captain's spare ID" = /obj/item/weapon/card/id/captains_spare,
думаю понял

переделал

2023-05-05 01:15 UTC, KandreyKandrey commented on code/game/objects/items/weapons/fulton.dm
> +			return FALSE
фритюр/каргошаттл так-то и нюке могут проблем создать (диск испортив)

фултоном просто уменьшаем кол-во способов уничтожения предмета на 1

думаю здесь проблема не особо критичная (банды изначально не знают, что ищет конкурент + мотивация быстрее искать)

~~они же не станут абсолютно все предметы искать и уничожать~~

2023-05-05 17:51 UTC, LudwigVonChesterfield commented on code/game/objects/items/weapons/fulton.dm
> +			return FALSE
эх вот бы была какая-то компонента "неразрушаемый" которая бы мимикрировала текущий функционал диска ядерного который телепортируется в рандомное место в техах при удалении.

2023-05-05 18:27 UTC, KIBORG04 commented on code/game/gamemodes/objectives/families/steal_lowrisk.dm
> +var/global/list/lowrisk_objectives_cache = list()
Сделай небольшую оптимизацию. Генг у нас довольно редкий режим, а этот лист будет создаваться и занимать память каждый раунд. Сделай для листа ленивую инициализацию, пж.

2023-05-05 20:52 UTC, KandreyKandrey commented on code/game/gamemodes/objectives/families/steal_lowrisk.dm
> +var/global/list/lowrisk_objectives_cache = list()
сделал

2023-05-08 17:54 UTC, volas approved these changes
по коду ок, в будущем я думаю имело бы смысл сделать задачу не только генгу/вынести low risk итемы в глобальные списки.

2023-05-08 17:54 UTC, merged