Перевод сообщений ЦК во время революции
TauCetiStation/TauCetiClassic pull request #11214
Opened 2023-04-03 14:10 UTC by BasiaBelov

## Описание изменений
Были переведены сообщения от ЦК главам в режим революции.
## Почему и что этот ПР улучшит
Сразу будет видно что конкретно просит ЦК.
Главы-новички не будут сконфужены тем, как этот текст перевёл их гугл переводчик.
## Авторство
## Чеинжлог
:cl: Basia
- ru: Переведены сообщения от ЦК главам во время революции

2023-04-03 14:10 UTC, TauKitty commented
###### Changelog status: :x: Empty changelog (check markdown correctness)

2023-04-03 14:12 UTC, KIBORG04 commented
Changelog status: ❌ Empty changelog (check markdown correctness)

2023-04-03 14:15 UTC, BasiaBelov commented
Проклятая точка.
Надеюсь, не нужно из-за этого переделывать весь ПР полностью.

2023-04-03 14:18 UTC, BasiaBelov commented
Спасибо большое, Киборг.

2023-04-03 18:23 UTC, LudwigVonChesterfield commented
мне не нравится что фикс в одном пакете с новыми переводами

из-за этого фикс замержат года через полтора, пожалуйста вынеси эту одну строчку в отдельный пр.

2023-04-04 05:17 UTC, BasiaBelov commented
> ...фикс замержат года через полтора...

Да ты не бойся. Не долго будет висеть, _я надеюсь..._

2023-04-05 12:52 UTC, BasiaBelov commented
Я вот что заметил... Если тупо сидеть и ждать, пока это проверят, пролетит года два.
Нужно вечно напоминаться, что среди других ПРов есть этот ПР.

2023-04-05 14:38 UTC, BasiaBelov commented
Естественно, ПР с переводами не может быть больше одного, в отличии от остальных.

2023-04-05 14:54 UTC, BasiaBelov commented
И ведь не соврал.
Как я мог сломать это?

2023-04-05 15:02 UTC, BasiaBelov commented
А как отменить? Я думал, что удалю изменения, а удалил _целый файл..._

2023-04-05 15:23 UTC, KIBORG04 commented
> А как отменить? Я думал, что удалю изменения, а удалил _целый файл..._

В гитхаб десктопе жми пкм по комиту и там выбери реверт. Коммить реверт. Готово

2023-04-07 22:41 UTC, KIBORG04 commented on code/game/gamemodes/factions/revolution.dm
> +		command_report("Согласно статистическим данным, свободное время и связанные с ним деятельности могут быть причиной неудовлетворительной работы нескольких наших станций. Поэтому рекомендуется закрыт
я думаю, тут под `vendors` имелись введу вендоматы, а не какие-то поставщики

2023-04-07 22:43 UTC, KIBORG04 commented on code/game/gamemodes/factions/revolution.dm
> +		command_report("Мы начали подозревать, что руководители персонала могут быть нелояльными к Нанотразен. Мы просим вас и других руководителей ввести имплант лояльности, если вы еще не вводили его в с
https://github.com/search?q=repo%3ATauCetiStation%2FTauCetiClassic+Нанотрейзен&type=code
```suggestion
		command_report("Мы начали подозревать, что руководители персонала могут быть нелояльными к НаноТрейзен. Мы просим Вас и других руководителей ввести имплант лояльности, если вы еще не вводили его в себя. Руководители, которые не хотят вводить имплант, должны быть арестованы за неисполнение приказов Центрального Командования до конца смены.")
```
Ну и бля, лучше бы переформулировал, а не дословно переводил, особенно кринжово звучит `Мы просим Вас и других руководителей ввести имплант лояльности, если вы еще не вводили его в себя.`

2023-04-07 22:45 UTC, KIBORG04 commented on code/game/gamemodes/factions/revolution.dm
> +		command_report("Сообщается, что простое закрытие развлекательных учреждений не дало результатов. Вы и ваши руководители должны обеспечить максимальную эффектиность всего экипажа и не допустить пуст
Крч нужно обсуждение по поводу перевода `Heads` и `Heads of Staff`, как `Руководители`.

2023-04-10 09:43 UTC, BasiaBelov commented on code/game/gamemodes/factions/revolution.dm
> +		command_report("Сообщается, что простое закрытие развлекательных учреждений не дало результатов. Вы и ваши руководители должны обеспечить максимальную эффектиность всего экипажа и не допустить пуст
Ну... Если брать из анонсов, то тут Главы.

>Тревога! Код Дельта!
Активирован механизм самоуничтожения или ситуация вышла полностью из под контроля! Все приказы глав станции должны выполняться беспрекословно, любое неповиновение карается смертью! Всему персоналу перевести датчики костюмов в третий режим! Это не учебная тревога!

2023-04-10 09:44 UTC, BasiaBelov commented on code/game/gamemodes/factions/revolution.dm
> +		command_report("Согласно статистическим данным, свободное время и связанные с ним деятельности могут быть причиной неудовлетворительной работы нескольких наших станций. Поэтому рекомендуется закрыт
А я думал карго...

2023-04-10 10:07 UTC, BasiaBelov commented on code/game/gamemodes/factions/revolution.dm
> +		command_report("Мы начали подозревать, что руководители персонала могут быть нелояльными к Нанотразен. Мы просим вас и других руководителей ввести имплант лояльности, если вы еще не вводили его в с
И как бы ты хотел поменять?

2023-04-21 19:00 UTC, BasiaBelov commented
Совсем забыли...

2023-04-22 12:01 UTC, DarthSidiousPalpatine requested changes
Чел, ты

2023-04-22 12:01 UTC, DarthSidiousPalpatine commented on code/game/gamemodes/factions/revolution.dm
> +		command_report("Сообщается, что простое закрытие развлекательных учреждений не дало результатов. Все главы станции должны обеспечить максимальную эффектиность всего экипажа и не допустить пустой тр
убери слово простое
вместо эффективность экипажа - эффективность персонала
вместо не допустить - не допускать
вместо "на отдыхе" - "отдыхающим"
вместо своей главы - своего главы
должна быть предупреждена? член предупреждена? Брух чел перечитай что ты пишешь. Должен быть предупреждён
дефис не нужен
тюрьма? У нас есть тюрьма? У нас, вроде, бриг
трансферный шаттл? Бруууух.
учреждение? станция это учреждение? брууух. Напиши просто: доставит их туда, где они будут полезнее.
более полезный это пиздец.

2023-04-22 14:44 UTC, BasiaBelov reviewed
Так...

2023-04-23 13:24 UTC, BasiaBelov commented
Если что, всё готово. Чуть не застрелился.

2023-04-25 20:51 UTC, IlinMihail commented on code/game/gamemodes/factions/revolution.dm
> +		command_report("Согласно статистическим данным, отдых и связанные с ним активности могут быть причиной неудовлетворительной работы нескольких наших станций. Поэтому рекомендуется закрыть следующие
в оригинале про многие станции + раз речь про статистику то выборка явно не из 'нескольких наших станций'. тогда уж лучше вообще не уточнять про их количество. мб стоит также убрать 'могут' и заменить на более уверенный ответ как в оригинале

алсо кринж с 'Питание через'. послушай 'Питание рабочих может производится через столовую'. напиши как в оригинале 'Пища доступна на кухне и в торговых автоматах'

2023-05-01 15:02 UTC, merged