респрайт столов
TauCetiStation/TauCetiClassic pull request #11235
Opened 2023-04-06 16:36 UTC by AndroBetel

## Описание изменений
![image](https://user-images.githubusercontent.com/44546836/230441565-d17263c1-52e3-4784-a184-c729220bd08f.png)

## Почему и что этот ПР улучшит
красиво
## Авторство
лижард
## Чеинжлог
:cl:LiJard
- image: респрайт столов

2023-04-06 16:36 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2023-04-06 16:45 UTC, AndroBetel commented
![image](https://user-images.githubusercontent.com/44546836/230443324-a503bf6b-02e8-4ae3-9e01-15ab7f6229f0.png)
баг диффбота

2023-04-07 08:17 UTC, Lexakr commented
Почему у всех 4 ношки а у стеклянного 2....

2023-04-08 12:23 UTC, UDaV73rus requested changes
Сломанный тайлинг нынешнего стеклянного стола так и остался :pensive:
- Магазинный стол пофикшен?

- Укреп стол быстрым взглядом сложно отличить от обычного
![image](https://user-images.githubusercontent.com/33157992/230719942-077be52d-3f40-404b-8efc-e57128bc45af.png)

- Ножки стола как-то топорно, без идеи разложены. А место от их жирных аутлайнов между ними, можно было потратить на красивый свет и объем
![image](https://user-images.githubusercontent.com/33157992/230719976-119a8a14-7658-4c9e-b8b3-8dc7f90edaa2.png)

- Блик стеклянного стола стал насыщенным цветом, прошлый блеклый варик выглядел чуть стекляннее. Но не важно
![image](https://user-images.githubusercontent.com/33157992/230719896-4115b777-64c6-48c7-a9ab-cef0460517aa.png)

2023-04-29 16:25 UTC, closed without merging