Автосоляры
TauCetiStation/TauCetiClassic pull request #11244
Opened 2023-04-07 20:13 UTC by DarthSidiousPalpatine

## Описание изменений
Раундстартом солнечные панели настроены и отдают станции 50кВт каждая

## Почему и что этот ПР улучшит
В раунд без инженеров станция не умирает. Но инженерам всё ещё желательно построить двигло чтобы станция не нуждалась в энергии.

Впоследствии можно увеличить потребление энергии тем или иным машинкам, а, также, от улучшения этих самых машинок с помощью РнД компонентов, тем самым, усилив нужду в настройке двигателя в мидл-лейт гейме.

## Авторство
AndreyGysev и все все все, кто помогал в дискорде.

## Чеинжлог
 :cl:
  - tweak: Солнечные массивы настроены по умолчанию.

2023-04-07 20:13 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2023-04-07 20:15 UTC, LudwigVonChesterfield commented
я против потому-что "пошли настроим соляры" это ответка не-инженеров на любые проблемы с инженерами, хорошо учит новичков тому как работает игра, даёт им повод выйти в космос.

2023-04-07 20:16 UTC, DarthSidiousPalpatine commented
Я за, потому что инженерам и неинженерам можно настраивать двигло, что интереснее и пригодится.

2023-04-07 20:17 UTC, DarthSidiousPalpatine commented
И учит новичков тому как работает игра и даёт им повод выйти в космос.

2023-04-07 23:02 UTC, DarkFurrSss commented
Может поставить некоторый шанс на каждую соляру быть готовой/нет? Хоть электрик проверит их

2023-04-08 03:47 UTC, Tap0r commented
Солярам нужно рандомить панельки. Чтобы некоторые из них раундстартом ломались. И инженерам для идеальной выработки с них приходилось бы брать ящик с этими панельками из двигательной и восстанавливать их. Или стекло менять на них и тд. А это брейндед какой-то

2023-04-08 04:29 UTC, DarthSidiousPalpatine commented
> 

я бы лучше сделал чаще метеоры там, или сделал мелкие метеоры без ивента, которые не могут стену пробить но всё остальное - пожалуйста

2023-04-09 17:59 UTC, volas commented
протирать шваброй раз в n минут...

я еще не очень с идеей делать работу за инженеров заранее. Может, будь это лишь 1-2 панели, с возможностью станции самим остальные запустить, было бы лучше.

Еще мап дифф странный, там окна.

2023-04-09 18:08 UTC, DarthSidiousPalpatine commented
Окна в мап. дифе потому что тапоровский антигусев фикс замержили мб?
Чекну что не так.

А про сам смысл ПРа, ну я уже говорил про то, что особый смысл это заимеет если замержить ПР с увеличением энергопотребления улучшенной машинерии.
В таком случае раундстартом у станции будет +- достаточно энергии чтобы выжить, инженеры тогда смогут ПОФАНТАЗИРОВАТЬ СПОКОЙНО и поставить теслу/сингу как хотят, чем хотят, где хотят. Будет больше скринов смешных тесл, можно будет дождаться платок от рнд и поставить сразу крутую теслу в поле двойном и т.д. и т.п.

Задача инженеров будет обновить энерговыработку станции к тому моменту когда РнД изучат крутые компоненты и начнут улучшать всех подряд.
Также задачей инженеров станет апгрейд батареек АПЦ в комнатах с улучшенной машинерией. Допустим, в рнд, кухне, химии самые такие.

Имхо, одни плюсы. Потом можно будет добавить мини-метеоры которые соляры бьют и пр. вещи на постоянку. Типа раз в rand(0.5, 5) MINUTES посылается рандомный мини-метеор под 90 градусов к солнцу от границы карты и он может попасть на соляру там, на окно, на грилль и сломать их. Задачей инженеров в таком случае будет армирование соляр и двигла гриллями там, починка окон разбитых, обход соляр для их починки если вдруг что и т.п.

Альтернативно можно сделать соляры целью для космокарпов :dovolen: Типа соляры блестят и те такие о, червячок, хз.

2023-04-09 18:21 UTC, BlankCringe commented
ааа, лично моё кринжовое мнение как просто тау плеера а не кодера.
автосоляры было бы круто в лоупоп раунды без инженерки, всё

2023-04-14 06:01 UTC, DarthSidiousPalpatine commented
Неделя уже прошла, мдамс. Изменение минимальное, не мержат потому что не замержат, потому что, все против?

2023-04-23 11:03 UTC, AzzyDreemurr13 commented
Здесь скорее это необходимо для Фалкона, чтобы хотя бы 1 из 3 была уже в работе, что немного дольше даст станции протянуть до полной потери энергии. 

Ибо зачастую если нет инженера, то Фалкон без света 100% и начинаются тупо попытки вызвать шаттл эвакуации и выбрать бокс или другую карту. 

А если для остальных карт, то вроде у больших карт по 4 солнечных панелей, то можно или 1/4 или 2/4 уже настроены, а остальные самим.

Но выше уже говорили поэтому поводу, а надо ли? Тип, когда вообще настраивали солнечные панели лл? Если не в счёт Фалкон.
Обычно туда идут или новички или если инженеру совсем не фиг в Раунде делать и по приколу хочется погулять по космосу и идёт в настройку панелей.

2023-04-23 11:04 UTC, DarthSidiousPalpatine commented
Я уже описывал зачем нужна настройка соляр автоматом.
Затем, чтобы базово станция не умирала полностью, а для продвинутой её работы всё равно требовалось бы двигло.

2023-04-23 11:06 UTC, AzzyDreemurr13 commented
Это я понял, но не знаю, тут двоякое мнение, типо иногда людям вообще хочется тупо без света по быть на станции, иногда не хочется.

Наверное.. попробуй голосование на форуме, я честно даже как-то сам хз ┐⁠(⁠´⁠ー⁠｀⁠)⁠┌

2023-04-23 11:17 UTC, Deahaka commented
Я сейчас задумался и этот ПР по идее фиксит большую проблему важную, которую по-другому возможно и нельзя решить.

2023-04-23 11:22 UTC, volas commented
Проблема решается силами имеющегося экипажа, даже просто тест сабжектов. Им и правила это позволяют за отсутствием инженеров, и скиллы позволяют разбираться группой со сложностями. На фалконе же у всех еще скиллы бафнуты.

Отсутствие инженеров никогда вроде не было серьезным препятствием. ПР стоит рассматривать только в совокупности с https://github.com/TauCetiStation/TauCetiClassic/pull/11245

2023-04-23 11:47 UTC, Deahaka commented
Аргументация такая как будто хотят удалить вендоматы и чтобы в отсутствии поваров и ботаников любой всё равно бы занимался их работой, чтобы остальные и сами они не "помирали" от голода...

2023-04-30 04:02 UTC, DarthSidiousPalpatine commented
нет

2023-04-30 05:40 UTC, Deahaka commented
Если б убрать ещё камеры на всех солнечных панелях, то, при условии, что они работают раундстартом и инженеры не крафтят двигло всю смену, это получается хороший концепт для амогуса, ведь нет одной точки, за которой кто-то может следить, чтобы препятствовать рольке саботировать энергию на станции. Но в остальных случаях это конечно так не работает))

2023-04-30 14:58 UTC, DarthSidiousPalpatine commented
С другой стороны да, Лижард прав.

2023-05-15 17:27 UTC, DarthSidiousPalpatine commented
А че, кстати, Дехака теперь со мной согласен что автосоляры нужны :dovolen:

Тбф я уже полторы или две недели играю почти каждый день, из-за болезни, и из личной статистики это действительно острая проблема. Лучше уж автосоляры чтобы можно было выжить хоть немного.

2023-05-15 17:32 UTC, LudwigVonChesterfield requested changes
я против.

у игроков есть все возможности самим настроить соляры в экстренных ситуациях (раунд без инженеров, саботаж), и в этом собственно и их смысл.

если соляры настраивать не нужно то почему-бы просто не поставить волшебный генератор делающий энергию изничего, будет выполнять ту же функцию абсолютно.

соляры же учат игроков выходам в космос, прокладке проводов.

вторая причина по которой этот ПР что-то улучшает это гипотетическая ситуация которой сейчас нет, если такая ситуация будет - можно будет думать о мержинге ПР-а.

2023-05-15 17:34 UTC, DarthSidiousPalpatine commented
Две недели играю. Ноль раз игроки "сами настраивали двигатель".
Да всем похуй, нет инженеров? Нет ГП? Воут рестарт. Очень интересная херобора выходит.

2023-05-30 05:05 UTC, LudwigVonChesterfield commented
Никто из мейнтейнеров не заинтерисовался. Волас предположил что если не все панели будут настроены, а лишь их часть то это имеет возможность жить.

Я правда думаю что тут двусторонняя палка:
- либо этих "не всех" панелей будет достаточно чтобы запитать станцию, и выходит что никому ничего не надо настраивать
- либо этих панелей не хватает и не до конца понятно зачем это было...

2023-05-30 05:05 UTC, closed without merging