Предметы не выпадают из рук когда лежишь попытка вторая
TauCetiStation/TauCetiClassic pull request #11272
Opened 2023-04-10 16:12 UTC by simb11

## Описание изменений
#11186 , но с некоторыми отличиями
При стрельбе лёжа скорострельность у оружия резко уменьшается
Если человек поскальзывается (получает статус эффект weaken)- вещи из его рук выпадают, но он может тут же их поднять.
Если человек оглушен (это касается и оглушения от болеурона) или спит - вещи из его рук выпадают и их нельзя поднять, пока не пройдёт оглушение или пока он не проснётся.

Реализовывать урон по всем мобам в тайле я не решился, это слишком сложно, да и может сломать несколько других механик.
## Почему и что этот ПР улучшит
resolves#11240
## Авторство

## Чеинжлог
:cl: Luduk, Simbaka
- rscadd: Предметы можно держать даже когда падаешь на пол.

2023-04-10 16:16 UTC, SiveanBen commented
Ты сделал так чтобы лежаший на одном тайле с трупом человек был выше трупа?

2023-04-10 16:51 UTC, simb11 commented
не, оно работает случайным непонятным образом.

2023-04-10 16:53 UTC, AndroBetel commented
if(stat == DEAD)
   layer -= 0.1

2023-04-10 22:42 UTC, volas commented on code/modules/mob/living/carbon/human/death.dm
> +		layer -= 0.1
переживи несколько клинических смертей и получи суперспособность

2023-04-14 15:35 UTC, LudwigVonChesterfield commented
Всё ещё можно абузить столы

2023-04-14 15:36 UTC, LudwigVonChesterfield commented on code/datums/status_effects/debuffs.dm
> +	if(owner.get_inactive_hand())
почему бы не

owner.drop_from_inventory(l_hand)
owner.drop_from_inventory(r_hand)

2023-04-14 15:38 UTC, LudwigVonChesterfield commented
Мне не очень нрав подход с трупом... потому-что найдут обязательно под чем ещё можно прятаться и что выстрелы будет впитывать поэтому решение не полноценное ._. , и создаёт эффект белки в колесе где регулярно надо выкатывать и выдумывать новые решения постоянно генерирующихся проблем

2023-04-15 14:56 UTC, simb11 commented on code/_onclick/click.dm
> +	if(HAS_TRAIT(usr, TRAIT_IMMOBILIZED))
там ниже идёт проверка на restrained

2023-04-20 21:27 UTC, simb11 commented
@LudwigVonChesterfield урон терь всему живым на тайле наносится, но при этом живой щит не теряет свою полезность и поглощает проджектайлы.
ну и удалил пару лишних моментов, по типу изменения леера при умерщвлении моба.

2023-04-20 21:45 UTC, Mercurialaste commented
> @LudwigVonChesterfield урон терь всем живым на тайле наносится, но при этом живой щит не теряет свою полезность и поглощает проджектайлы. ну и удалил пару лишних моментов, по типу изменения леера при умерщвлении моба.

все ещё можно держать человека лежа в третьем грабе?

2023-04-20 21:50 UTC, LudwigVonChesterfield commented
Го попробуем, вроде самые крупные проблемы пофикшены.

Дальше только думать о том:
- Операции на себе же лёжа (фича, если под обезболом. если можно без обезбола надо фиксить...)
- Привношение себя же в жертву (думаю фича)

2023-04-20 21:50 UTC, LudwigVonChesterfield commented
Не забудь темку на форум, и попросить форум модераторов удалять нерелевантные комментарии.

2023-04-20 21:56 UTC, LudwigVonChesterfield commented on code/modules/projectiles/projectile.dm
> +			if(check_living_shield(mob) == M)
нет учёта перевернутого стола, кажется.

2023-04-20 22:07 UTC, simb11 commented on code/modules/projectiles/projectile.dm
> +			if(check_living_shield(mob) == M)
проверка на защиту стола от пуль находится, собственно, в коде стола, так что всё работает

2023-04-21 22:01 UTC, TauKitty commented
Этот запрос на слияние был упомянут в **Tau Ceti Station Forum**. Там могут быть соответствующие подробности:

https://forum.taucetistation.org/t/predmety-ne-vypadayut-iz-ruk-kogda-lezhish-2/39118/1

2023-04-22 15:12 UTC, LudwigVonChesterfield commented
предметы не выпадают из рук даже когда умер. так ещё и стрелять из них можно.

2023-04-22 15:12 UTC, LudwigVonChesterfield commented on code/_onclick/click.dm
> +	if(HAS_TRAIT(usr, TRAIT_IMMOBILIZED))
ну вот всё таки боком это вылезло.

тут проверка на смерть, параличи, и т.д.

зачем ты её убрал, кому она мешала?..

2023-04-25 16:35 UTC, muWander commented
по-моему из-за
>Если человек оглушен (это касается и оглушения от болеурона) или спит - вещи из его рук выпадают и их нельзя поднять, пока не пройдёт оглушение или пока он не проснётся. 
у лярв алиенов вырастающих в человеке "выпадает из руки" абилка выгрызться из носителя и им очень грустно потому что они не могут выгрызться из носителя на волю пофикси пж

2023-04-25 16:41 UTC, muWander commented
> * Привношение себя же в жертву (думаю фича)

(https://github.com/TauCetiStation/TauCetiClassic/pull/8047)

2023-05-03 17:35 UTC, AndroBetel commented
предметы из рук не выпадают даже когда в крите без сознания

2023-05-08 15:10 UTC, LudwigVonChesterfield commented on code/datums/status_effects/debuffs.dm
> +	owner.drop_from_inventory(owner.l_hand)
мне кажется что если каким-то образом умереть не заснув то предметы останутся в руках.

2023-05-08 16:38 UTC, volas commented on code/modules/projectiles/projectile.dm
> +				mob.bullet_act(src,def_zone)
хотя нет, оно уже так и было, так что ладно

2023-05-08 16:46 UTC, volas commented on code/modules/projectiles/projectile.dm
> +				mob.bullet_act(src,def_zone)
нет, правда, какого фига оно работало так... булетакт по мобу, но on_impact вызывали на турф.

И оно уже было плохо, но теперь еще хуже, с этим циклом по мобам какой-то рнг получится. Это сейчас проблемное место. Я бы предложил какой-то другой вариант, но это опять по новой разбираться в запутанном коде прожектайлов.

2023-05-08 17:21 UTC, Mercurialaste commented
Заметил баг. Если во время того, как кукла впадет в слип, условно от лицехвата, кукла возьмет кого-то на прицел, то она все равно выстрелит, несмотря на то что лежит ничком и лицехватом на лице.

2023-05-18 20:28 UTC, LudwigVonChesterfield requested changes
нужно пофиксить то что Мерк говорит про прицельную стрельбу

(а может всё таки её выпилим?..)

2023-05-19 15:52 UTC, simb11 commented
Так персонаж же роняет вещь на пол когда засыпает и соответственно перестаёт прицеливаться

2023-05-20 00:42 UTC, LudwigVonChesterfield commented
@Mercurialaste @simb11 скооперируйтесь по поводу бага пж

2023-05-20 16:46 UTC, simb11 commented
Мерк не может повторить баг, ещё у игроков и менторов на сервере поспрашивал - пишут, что не видели ничего подобного.

2023-05-20 20:03 UTC, LudwigVonChesterfield commented
окей мержим буду надеяться что что-либо такое починят.

2023-05-20 20:03 UTC, LudwigVonChesterfield approved these changes

2023-05-20 20:06 UTC, LudwigVonChesterfield commented on code/modules/projectiles/projectile.dm
> +	if(ismob(A))
@volas я не уверен что понимаю в чем тут проблема, попробуй объясниться

2023-05-20 20:07 UTC, LudwigVonChesterfield requested changes
попросили не мержить из-за репликаторов

2023-05-20 23:04 UTC, volas commented on code/modules/projectiles/projectile.dm
> +				mob.bullet_act(src,def_zone)
> @volas я не уверен что понимаю в чем тут проблема, попробуй объясниться

@LudwigVonChesterfield 

Я не могу сходу сказать, какие тут могут быть проблемы, это нужно лучше в коде разбираться и сейчас я только интуитивно представляю. Bump это конечный в цепочке прок столкновения с объектом, т.е. прожектайл столкнулся с определенной преградой, и мы обрабатываем это. Либо мы промазали и возвращаем FALSE, прожектайл идет бампаться дальше, либо мы попали и обрабатываем наше попадение, именно по объекту, с которым мы столкнулись. И у нас вся обработка в проке, каллбеки, on_impact ниже - к этому попадению на конкретный объект, с которым столкнулись.

Потом когда-то добавили костыль-делегацию попадания с турфа на мобов 
```
if(istype(A,/turf))
		for(var/mob/Mob in A)
			Mob.bullet_act(src, def_zone)
```

Видимо для стрельбы по лежачим - я даже не уверен, что оно работало (турф не density, по нему не должен сработать bump по идее, но это нужно разбираться в коде и рефах), но даже если работало - это уже немного криво. Потому что попадание у нас всё еще по объекту(турфу), но сам выстрел без разбора делегируем всем мобам в турфе. Забыв про каллбек, забыл про всю обработку с forcedodge и silenced и прочими сообщениями выше, наплевав на всё это и форся буллетакт напрямую на всех мобов.

А теперь этот костыль с одного тайла, который вообще мог не работать сейчас, расширяется на всех мобов в тайле. Столкновения с мобами точно будут работать, они density. Учитывая, что Bump проходится по каждому объекту по очереди, и мобов на тайле может быть больше чем тайлов, тут и могут возникнуть баги с двойным уроном и другие проблемы. Если например в тайле два плотных моба, но один на свой Bump сделал forcedodge, а другой не смог и получил попадание, а потом передал его всем мобам в тайле, в т.ч. обратно первому...

Короче я бы смотрел в код прожектайлов до Bump-а и где нибудь там бы решал это всё. Может потребуется переписать прожектайлы с бампов или еще какой-то рефакторинг.

2023-05-20 23:48 UTC, LudwigVonChesterfield commented
мне кажется сейчас если целиться в репликатора то попадёшь только в него

а если целиться в тайл на котором несколько репликаторов то все получат урон

2023-05-20 23:49 UTC, LudwigVonChesterfield commented on code/modules/projectiles/projectile.dm
> +				mob.bullet_act(src,def_zone)
мне кажется я всё ещё не понимаю почему это должно обрабатываться не в проке результирующего попадания...

ну а насчёт того что один доджнул а второй нет - справедливое замечание, но теперь такая механика... если один получает урон - все получают.

2023-05-21 16:15 UTC, LudwigVonChesterfield commented
Дехака жалуется на лежачие перестрелки в космосе

2023-05-27 03:26 UTC, LudwigVonChesterfield commented on code/modules/projectiles/gun.dm
> +				if(isspaceturf(user.loc) && user.lying)
я не уверен что это хорошая идея и не видел это когда ТМ-ил.

будем считать что это временный кодер ивент

но мне кажется очевидно надо не пушку взрывать, а решать любую из причин того почему стрельба лёжа в космосе имба

(мне кажется что возможно дело в скорости перемещения лёжа, но я не уверен)

2023-05-27 11:50 UTC, ZVee commented on code/modules/projectiles/projectile.dm
> -	if(istype(A,/turf))
Я тут мимо прохожу снова, видел вы что-то там обсуждали на эту тему в комментах но я особо не влезал осмысленно, однако мельком код проглядел и вроде не нашел переиначивания этого момента в другом месте тут где либо.

Если не ошибаюсь весь этот иф служил для закрытия абуза людей которые залезли каким-то образом на стену и могли безнаказанно там сидеть при этом постреливая со стен без проблем.

Но могу ошибаться и оно тут для другого сидело, но вряд ли это было для пола или каких-то еще других турфов кроме стен. Однако это легко проверить должно быть для этого этот код был или нет.

2023-05-27 18:28 UTC, ZVee commented on code/modules/projectiles/projectile.dm
> +				mob.bullet_act(src,def_zone)
Еще чу-чуть почитал.
По поводу on_impact - его основное предназначение это типа "спец эффекты" вроде отрисовывания вспышек или проигрывании звука удара при столкновении с объектом в бампе (в проке бампа) или на последнем турфе (в проке процесса) если прожектайл прошел максимально разрешенную дальность по процессу - ибо в этом случае иначе прожектайл вообще просто исчезнет ибо мы минуем бамп и всю его логику завершения. Поэтому по значимости это не какой-то очень важный прок который выполняет что-то важное.
И второстепенная задача это какие-то особые действия совершить с объектом в который влетели, но по поиску это видимо добралось только для стаффа анимации - т.к прок без подводных камней как если взять что-то более низкоуровневое из доступного и начать возиться со всей логикой родителей или прочего..

Тут наверно неудачное название. Хотя не совсем представляю как иначе его можно было бы назвать, наверно on_impact_effect какой-нибудь.
Возможно для тех кто незнаком такое название сходу путает и наводит непонимание почему оно так, или может где коммент лежит на эту тему путающий в коде - это уже не знаю.
Чу-чуть по старой памяти помню еще некоторые моменты т.к сам и портировал эти новые эффекты тогда, только уже не помню откуда это тянулось тогда с ТГ или бея, но как-то где-то там так оно и было названо и реализовано на тот момент.

2023-05-28 18:05 UTC, simb11 commented on code/modules/projectiles/gun.dm
> +				if(isspaceturf(user.loc) && user.lying)
поменял на медленное передвижение ползком в космосе

2023-05-29 01:27 UTC, LudwigVonChesterfield commented on code/modules/projectiles/projectile.dm
> -	if(istype(A,/turf))
насколько знаю вся суть ПР-а была прикрыть в том числе этот абуз, с тем что можн острелять из стен/шлюзов /холодильников/шкафов/прочих объектов впитывающих выстрелы

@simb11 я что-то упустил? мы вроде обсуждали надобность мочь попасть по мобу в чём бы он не прятался

2023-05-29 08:06 UTC, volas commented on code/modules/projectiles/projectile.dm
> +				mob.bullet_act(src,def_zone)
Я проглядел и разобрался в прожектайлах еще раз, и короче это не годиться. Глушитель и логи можно убрать дальше в bullet_act (хз, что они тут делают), on_impact выпилить в пользу on_hit (я даже когда-то комментарий оставлял в коде), и тогда бамп просто будет ищущим проком для прожектайла.

Но всё упирается в то, что прожектайл - один, и попадания работают с ним. У прожектайла могут изменяться параметры, его может рефлектить, он может удалиться, архитектурно не подразумевалось использование одного прожектайла на несколько попаданий. Разве что создавать каждому мобу на тайле по своей копии прожектайла, но и там будут проблемы, не говоря про как это криво. Без переписывания кода это не сделать нормально.

Я бы откатился до изначальной проблемы и искал другие решения. Если это про тела в density объектах, то решается предотвращением подобного, так вообще не должно быть, и это будет проще, чем выставлять всюду костыли (на стрельбу, на удары, на бросания, на абилки, и прочее). Если это про лежачих в одном тайле, прикрывающихся трупами - можно было бы рандомно пикать одного из них в этом месте, но обрабатывать только одно попадание.

2023-06-06 15:17 UTC, volas commented on code/modules/projectiles/projectile.dm
> +	on_hit(A)
не совсем это имел в виду. on_hit() обычно и так вызывается дальше после булетактов, нужно было бы тут просто убрать вызов и смержить саму функцию on_impact в on_hit, сам on_impact истребить

2023-06-08 21:05 UTC, simb11 commented
Теперь урон получает случайный моб в тайле, плюс вернул попадания по существам в стенах.

2023-06-13 06:41 UTC, volas reviewed
мне уже гораздо больше нравится код без on_impact

2023-06-13 06:41 UTC, volas commented on code/game/objects/obj_defense.dm
> +		Mob.bullet_act(P, P.def_zone)
Это тоже нужно переделывать. И вообще может оно и не нужно вовсе? Выглядит странно. Если пуля попала по тонкому стеклу, на границе тайла, то странно её потом мобам еще передавать.

2023-06-13 06:41 UTC, volas commented on code/modules/mob/inventory.dm
> +			return FALSE
```suggestion
	if(HAS_TRAIT(src, TRAIT_IMMOBILIZED) && !(W.flags & ABSTRACT))
		return FALSE
```

2023-06-13 06:41 UTC, volas commented on code/modules/mob/living/living_defense.dm
> +	if(P.firer)
куда-то потерялся ``old_firer``, возможно регресс https://github.com/TauCetiStation/TauCetiClassic/pull/2752

я по коду схожу не вижу, где проблема с тазерами, но рефлекты точно могут изменять firer-а.

2023-06-13 06:41 UTC, volas commented on code/modules/projectiles/projectile.dm
> +			forcedodge = A.bullet_act(src, def_zone) // searches for return value
я не понимаю, почему ``check_living_shield`` переехал вниз, и зачем в проке две копипасты с обходом мобов (они теперь опять двойной урон получают?)

2023-06-13 06:41 UTC, volas commented on code/modules/projectiles/projectile.dm
> +			on_hit(src.loc) //for any final impact behaviours
``on_hit`` не нужно, это про гарантированный хит, и он вызывается с буллетакта. А тут просто растворяется прожектайл из-за прошедшего расстояния.

Если заменять - это должен быть ``bullet_act()``. Пуля потеряла ускорение и попала в пол и т.п.

2023-06-13 06:44 UTC, volas commented on code/modules/mob/living/living_defense.dm
> +	if(P.firer)
Если ``old_firer`` вернуть, то его можно было бы задавать не в bump-е (где это уже может быть поздно), а при создании прожектайла. И переименовать как-то, original_firer может

2023-06-13 06:53 UTC, simb11 commented on code/game/objects/obj_defense.dm
> +		Mob.bullet_act(P, P.def_zone)
гении игры без этой штуки будут строить кучу столов и воевать лёжа под ними, без возможности получить урон

2023-06-13 06:55 UTC, simb11 commented on code/modules/mob/inventory.dm
> +			return FALSE
тут вроде нужна конкретно последовательная проверка, потому как без неё будут появляться баги, например, вот этот #11363

2023-06-13 07:03 UTC, volas commented on code/game/objects/obj_defense.dm
> +		Mob.bullet_act(P, P.def_zone)
можно тогда костыль на сам стол нацепить, а не на все объекты. И цикл заменить на пик.

По хорошему, если без полумер и прожектайлов пролетающих над столом и дамажащих людей под ним - можно добавить им "уровень". Если стрельба из лежачего состояния - прожектайлу нижний уровень (или флаг) и пусть летит под столом и бампается в лежачих... но это отдельный сложный вопрос.

2023-06-13 07:07 UTC, volas commented on code/modules/mob/inventory.dm
> +			return FALSE
я просто склеил два условия для читаемости, суть не меняется - как был return false для условий IMMOBILIZED & не абстрактный - так и осталось.

2023-06-15 14:55 UTC, simb11 commented
всё что надо было сделать сделал @volas

2023-06-15 15:30 UTC, volas commented on code/game/objects/structures/tables_racks.dm
> +		mob.bullet_act(P, P.def_zone)
```suggestion
		. = mob.bullet_act(P, P.def_zone)
```

2023-06-15 15:55 UTC, volas commented on code/modules/mob/living/living_defense.dm
> +	if(P.firer)
анрезолв, так как еще актуально. Смотреть код в мастере:

https://github.com/TauCetiStation/TauCetiClassic/blob/ee6c4370393a1f9f7d66eb651a3da27ce4f07d3e/code/modules/projectiles/projectile.dm#L214

2023-06-15 16:02 UTC, volas commented on code/modules/projectiles/projectile.dm
> +			on_hit(src.loc) //for any final impact behaviours
Это тоже анрезолвну, bullet_act был бы предпочтительным. Там всякие плетки есть еще, может для них это важно.

2023-07-01 12:07 UTC, volas approved these changes
В последний момент немного хайджектнул ради косметических изменений, сломаться ничего не должно.

Прожектайлы нужно будет еще перетрясти глобально, но это уже отдельная тема.

2023-07-01 12:26 UTC, simb11 commented
@volas проджектайл будет дважды наносить урон если его не удалять

2023-07-01 12:31 UTC, volas commented
не должен, я не замечал. Но он мог наносить из-за какого-то кода (лишние моб.буллет_акт в бампе) до последних изменений. Если воспроизведешь - я еще посмотрю

2023-07-02 09:34 UTC, volas commented on code/datums/status_effects/debuffs.dm
> +	owner.drop_from_inventory(owner.l_hand)
вроде реалистично

2023-07-02 09:36 UTC, merged