Эмоуты видны в рунчате
TauCetiStation/TauCetiClassic pull request #11292
Opened 2023-04-14 18:26 UTC by NinjaPikachuska

## Описание изменений
Эмоуты теперь отображаются в рунчате
![image](https://user-images.githubusercontent.com/89906909/232121469-242fd477-fded-4380-80da-b1a308021ccb.png)
Язык жестов тоже
![image](https://user-images.githubusercontent.com/89906909/232121991-c4725811-470e-4f6b-bdb8-cc2c1b57a913.png)
![image](https://user-images.githubusercontent.com/89906909/232122047-82a14fa7-6a87-4f2f-b40b-1dd2a53df7fd.png)
Помимо этого, у нас оказывается гендеры все время были сломаны в эмоутах. Починил заодно.
## Почему и что этот ПР улучшит
Красиво, удобно
## Авторство
Я
## Чеинжлог
:cl:
 - tweak: Эмоуты видны в рунчате

2023-04-14 18:26 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2023-04-14 18:36 UTC, KIBORG04 commented on code/modules/mob/hear_say.dm
> +	if(!(sdisabilities & DEAF || ear_deaf))
ну такое, делать не быстрые операции вхолостую (copytext_char)

2023-04-14 18:42 UTC, KIBORG04 commented on code/modules/replicators/replicator_communication.dm
> -	if(speaker && target.client && target.client.prefs.show_runechat)
не везде вернул

2023-04-14 19:05 UTC, LudwigVonChesterfield commented on code/modules/replicators/replicators.dm
> -	if(!client.prefs.show_runechat)
эээ? а где теперь эта проверка

2023-04-14 20:43 UTC, Tobyyyan commented
Mime gaming, наконец то. Только облачка не хватает в процессе ввода.

2023-04-18 13:22 UTC, LudwigVonChesterfield approved these changes

2023-04-20 19:38 UTC, volas requested changes
Мне кажется, стоило бы в таком случае рунчат сообщение перенести как дополнительных опциональный параметр в ``proc/visible_message`` и ``proc/audible_message``. Они уже делают более правильный цикл по юзерам, и показывают юзеру то сообщение, которое он должен увидеть (визуальное, или аудио если он глухой, и т.д.)

Опционально, если не хочешь заниматься - я согласен просто на todo комментарий.

2023-04-25 10:37 UTC, volas approved these changes

2023-05-01 14:55 UTC, merged

2026-07-23 16:46 UTC, volas commented on code/modules/mob/mob.dm
> +		if((!(M.sdisabilities & BLIND) && !M.blinded && !M.paralysis) && runechat_msg)
@NinjaPikachuska не помнишь, почему тут проверка на ``paralysis``?