Добавлены заборчики
TauCetiStation/TauCetiClassic pull request #11329
Opened 2023-04-23 18:04 UTC by DarthSidiousPalpatine

## Описание изменений
Добавлен металлический, деревянный и стеклянный заборы. Первые два делаются из металла и дерева, стеклянный не делается ни из чего.
![image](https://user-images.githubusercontent.com/21008918/233856919-ecd74d86-3f3f-48f0-b3ea-38f1ab5219cd.png)
![image](https://user-images.githubusercontent.com/21008918/233856928-917449fc-13fc-4505-8450-fbfc169f3b19.png)
![image](https://user-images.githubusercontent.com/21008918/233856937-90c3d4ef-978e-4ceb-a860-edaaa4338307.png)
![image](https://user-images.githubusercontent.com/21008918/233856952-cd2108fc-af7d-4d44-8db7-298604cf27db.png)

## Почему и что этот ПР улучшит
Заборы для мапперов, заборы для сбух, заборы для ботаников.

## Авторство
AndreyGysev и все все все, кто помогал в дискорде.

## Чеинжлог
 :cl:
  - rscadd: Добавлены заборы.

2023-04-23 18:04 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2023-04-23 20:43 UTC, volas commented on code/game/objects/structures/fence.dm
> +/obj/structure/fence/CanAStarPass(obj/item/weapon/card/id/ID, to_dir, caller)
посмотри ``/turf/proc/LinkBlockedWithAccess``, там путаница с параметрами

2023-04-23 20:43 UTC, volas commented on code/game/objects/structures/fence.dm
> +	add_overlay(Rail)
если делаешь оверлеем, то блендить не нужно, можешь просто ``.color`` поставить. Так будет быстрее.

2023-04-23 20:44 UTC, volas commented
Мне всё же больше нравится тг-шный спрайт, они выглядят хорошо и понятны для боковых направлений. Но можно будет потом добавить.

2023-04-24 03:35 UTC, DarthSidiousPalpatine commented on code/game/objects/structures/fence.dm
> +	add_overlay(Rail)
Ты вкурсе что у icon не .color?

2023-04-24 06:13 UTC, volas commented on code/game/objects/structures/fence.dm
> +	add_overlay(Rail)
сделай не icon а image

2023-04-30 15:00 UTC, DarthSidiousPalpatine commented
Лижард всегда прав. И Лексакр, несите сюда Вальтеровские заборы, если так уж хотите.

2023-05-10 14:05 UTC, DarthSidiousPalpatine commented
Мда, чёрт его знает что не так.

2023-05-16 17:19 UTC, AgRevol commented
Я никто и я апрувлю этот ПР. 🤠 
На карте всё адекватно, проблем быть не должно, критичные заборчики убрали. 

Непривычно местами? Да. Можно ли это убрать если по факту станет хуже? Абсолютли.

Стоит ли дать волю новому и непривычному чтобы потенциально улучшить стейшон? Я считаю, что да.
Спасибо за внимание

2023-05-16 18:04 UTC, Deahaka commented
Всмысле критичные заборчики убрали? Всё осталось на своих местах с тех пор как ПР появился. Или это мапдиф глючит?

2023-05-16 19:32 UTC, AgRevol commented
> Всмысле критичные заборчики убрали? Всё осталось на своих местах с тех пор как ПР появился. Или это мапдиф глючит?

Их было больше, те которые правда были лишними уже убрали. Остальные, - эксперимент

2023-05-19 03:49 UTC, LudwigVonChesterfield commented on code/game/objects/structures/fence.dm
> +	desc = "Спрячь за высоким забором таяру - выкраду вместе с забором!"
рифмы не хватает

2023-05-19 03:49 UTC, LudwigVonChesterfield commented on code/game/objects/structures/fence.dm
> +	name = "Fence"
```suggestion
	name = "fence"
```

2023-05-19 03:49 UTC, LudwigVonChesterfield commented on code/game/objects/structures/fence.dm
> +	name = "Metal Fence"
```suggestion
	name = "railings"
```

2023-05-19 03:50 UTC, LudwigVonChesterfield commented on code/game/objects/structures/fence.dm
> +	name = "Metal Fence"
какой-то из заборов которые на картинке должен называться railings, но railings в коде не вижу.

2023-05-19 05:33 UTC, DarthSidiousPalpatine commented on code/game/objects/structures/fence.dm
> +	desc = "Спрячь за высоким забором таяру - выкраду вместе с забором!"
Там нет рифмы и в оригинале.

"Спрячь за высоким забором девчонку - выкраду вместе с забором" - песня Яшки ЦЫгана из неуловимых мстителей.

2023-05-19 11:22 UTC, volas commented on code/game/objects/structures/fence.dm
> +	add_overlay(Rail)
всё еще актуально

2023-05-21 04:53 UTC, DarthSidiousPalpatine commented
Сделал твои семантические предложения.

2023-05-21 16:39 UTC, LudwigVonChesterfield commented on code/game/objects/structures/fence.dm
> +/obj/structure/fence/attackby(obj/item/W, mob/user)
мне кажется надо мочь их крутить как стекла

2023-05-21 16:39 UTC, LudwigVonChesterfield commented
мне кажется нужен способ их перелезать

2023-05-21 16:40 UTC, LudwigVonChesterfield commented on code/game/objects/structures/fence.dm
> +				if(!user.is_busy() && do_mob(user, src, 1 SECONDS))
мне кажется в мувмент коде нельзя слипать

@volas может ты подскажешь

2023-05-21 18:37 UTC, TryXAH commented
Если все еще в роботике и в токсинной стеклянные заборчики вместо стекол то это кринге

2023-05-21 22:35 UTC, DarthSidiousPalpatine commented on code/game/objects/structures/fence.dm
> +/obj/structure/fence/attackby(obj/item/W, mob/user)
Сделал

2023-05-21 22:36 UTC, DarthSidiousPalpatine commented
Сделал возможность крутить забор. Также если забор откручен то при его перелезании челика кинет вперёд. Как достать соседа момент.

2023-05-22 03:17 UTC, volas commented on code/game/objects/structures/fence.dm
> +				if(!user.is_busy() && do_mob(user, src, 1 SECONDS))
да, нельзя, это бьендовские вербы и тормозит сервер (или стакаются вызовы на каждое нажатие стрелки, я не помню). Но у нас линтер должен ругаться на это, может Enter() не критичен или у нас линтер на него не настроен...

Можно как со столами сделать переползание по дрананддропу, либо задержку через переменную замедления в коде движения.

Еще стоит держать в уме абузивность, люди уже спамили стекла против нюки - тут еще один предмет с потенциалом получается.

2023-05-22 03:21 UTC, volas commented on code/game/objects/structures/fence.dm
> +				if(!user.is_busy() && do_mob(user, src, 1 SECONDS))
Можно еще в код тг заборов посмотреть и что нибудь оттуда перенять или подтвердить валидность текущего варианта. ~~Но мы же гордые и не зависимые, обязательно должны сами собрать все грабли и потратить своё время на такие мелочи.~~

2023-05-22 07:39 UTC, AgRevol commented on code/game/objects/structures/fence.dm
> +				if(!user.is_busy() && do_mob(user, src, 1 SECONDS))
> Еще стоит держать в уме абузивность, люди уже спамили стекла против нюки - тут еще один предмет с потенциалом получается.

Не согласен с этим т.к. в билде уже есть перевернутые столы которые по сути делают то же самое, но через которые ещё и стрелять сложнее/перелезать не так удобно. Перевернутый стол будет лучше чем заборчики.
Так же в отличии от стёкол обе стороны могут стрелять над заборами.

Вообще, считаю что можно пойти даже дальше и сделать ограды "мешки с песком" для войнушек

2023-05-22 07:41 UTC, TryXAH commented
> сделать ограды "мешки с песком" для войнушек

гусев жду через день пр на мешки с песком на космической станции, которые заказываются в карго и защищают от обстрела лучше чем перевернутые столы

2023-05-26 18:32 UTC, LudwigVonChesterfield requested changes
нужно каким-либо образом убрать sleep() (который внутри do_mob) из кода ходьбы.

так как у нас уже есть фича с залезанием на стол, предлагаю сделать на её подобие. перетаскивание себя на заборчик инициализирует перелезание. думаю так будет и интуитивней, и не надо будет слипать в ходьбе.

2023-10-03 14:30 UTC, DarthSidiousPalpatine commented
ГоТоВо

2023-10-06 11:38 UTC, volas commented on code/game/objects/structures/fence.dm
> +	open = TRUE
мне кажется, или у ворот с поворотом на запад/восток будет проблема с порядком слоев и мобом?

2023-10-10 15:01 UTC, DarthSidiousPalpatine commented on code/game/objects/structures/fence.dm
> +	open = TRUE
Да, да, когда-нибудь сделаю оверлеем, лень разбираться, пока что.

2023-10-13 23:55 UTC, KIBORG04 commented on code/game/objects/structures/fence.dm
> +		return TRUE
У нас же есть специальные pass_flags

2023-10-13 23:56 UTC, KIBORG04 commented on code/game/objects/structures/fence.dm
> +		return TRUE
Тоже странно ТУТ видеть пули

2023-10-13 23:56 UTC, KIBORG04 commented on code/game/objects/structures/fence.dm
> +	return
в конце какой-то пустой ретурн, а выше ретурн зачем-то 0 возвращает

2023-10-13 23:58 UTC, KIBORG04 commented on code/game/objects/structures/fence.dm
> +	add_overlay(Rail)
всё еще актуально (color должен быть у image)

2023-10-13 23:58 UTC, KIBORG04 commented on code/game/objects/structures/fence.dm
> +	throwpass = 1
```suggestion
	throwpass = TRUE
```

2023-10-14 00:00 UTC, KIBORG04 commented on code/game/objects/structures/fence.dm
> +		return TRUE
pass_flag = PASSTABLE

тейбл кажись норм подходит или PASSGRILLE, хз

2023-10-14 00:01 UTC, KIBORG04 commented on code/game/objects/structures/fence.dm
> +		return TRUE
pass_flag = PASSTABLE

2023-10-26 01:44 UTC, volas commented on maps/templates/holodeck/theatre.dmm
> +/obj/structure/fence/glass,
спасибо, что убрал с карт, но на голодеке тут будет возможно проблема с дюпом ресурсов (если разбор есть)

2024-01-17 06:49 UTC, DarthSidiousPalpatine commented
Прошу переоткрыть

2024-01-17 06:58 UTC, DarthSidiousPalpatine commented
Спасибо, ща допилю

2024-01-17 07:10 UTC, DarthSidiousPalpatine commented on code/game/objects/structures/fence.dm
> +		return TRUE
У столов они и в чек экзите и в чек энтере, так что...

2024-01-17 08:02 UTC, DarthSidiousPalpatine commented
Итак, @KIBORG04 исправил твои замечания про экзит и ентер проки, сделал как у столов.
Переделал перекрас перил на image вместо icon.

@volas исправил отображение гейтов на боковых спрайтах, добавив оверлей ниже моба. Работает отлично, хотя и отстаёт на 1-2 тика от основного спрайта((( Но это мелочи.
Также, убрал с голокарт штуки. Сейчас обновляю ветку до мастера, фикшу конфликты и ГОТОВО.

2024-01-17 08:04 UTC, DarthSidiousPalpatine commented
ОГО, Никаких конфликтов не появилось за СТОЛЬКО ВРЕМЕНИ. Хотя я скорее новые файлы добавлял чем старые менял. Отлично крч. ГОТОВО!

2024-01-22 17:25 UTC, volas commented on code/game/objects/structures/fence.dm
> +			return FALSE
use_tool уже сам проверяет is_busy, отдельно нет смысла вызывать

2024-01-22 17:28 UTC, volas commented on code/game/objects/structures/fence.dm
> +		return TRUE
было несколько ПР-ов с рефакторингом прохода прожектайлов, в чекэкзит в столах этого больше нет, надо обновить соответствующе

2024-01-22 17:36 UTC, volas commented on code/game/objects/structures/fence.dm
> +	var/screwed = TRUE
мне кажется, эти два флага про одно и то же, и можно оставить один anchored

2024-01-22 17:39 UTC, volas commented on code/game/objects/structures/fence.dm
> +	for(var/atom/A in T)
```suggestion
	for(var/atom/A as anything in T)
```

так как мы знаем, что в контентсах могут быть только атомы, мы можем пропустить тайпчек в массиве

2024-01-22 17:43 UTC, volas commented on code/game/objects/structures/fence.dm
> +/obj/structure/fence
у него нет дестроя, обычный ``/fence`` просто как мастер-класс, который не используется в игре? Если да, то можно где-то в названии или описании подчеркнуть, чтоб маперы не использовали.

2024-01-22 17:44 UTC, volas commented on code/game/objects/structures/fence.dm
> +	..()
следует добавить проверку на NODECONSTRUCT, и не дропать ничего, если на заборе висит этот флаг. В билде можешь поискать примеры по имени флага

2024-01-22 17:47 UTC, volas commented on code/game/objects/structures/fence.dm
> +	Rail = image(icon, "[icon_state]_color")
стоит использовать mutable_appearance - это как image, только не отправляется клиенту пока ты с ним работаешь. Чуть оптимальней, и с ними как-то меньше багов если использовать оверлеем

2024-01-22 17:49 UTC, volas commented on code/game/objects/structures/fence.dm
> +	new /obj/item/stack/sheet/metal(loc, 2)
NODECONSTRUCT

2024-01-22 17:49 UTC, volas commented on code/game/objects/structures/fence.dm
> +	new /obj/item/stack/sheet/glass(loc, 2)
NODECONSTRUCT

2024-01-22 17:50 UTC, volas commented on code/game/objects/structures/fence.dm
> +	var/image/under_sprite
аналогично с mutable_appearance

2024-01-22 17:51 UTC, volas commented on code/game/objects/structures/fence.dm
> +		return TRUE
аналогично как выше про прожектайлы

2024-01-22 18:02 UTC, LudwigVonChesterfield commented on code/game/objects/structures/fence.dm
> +	if(isobserver(usr)) //to stop ghosts from rotating
incapacitated() вероятно

2024-01-22 18:20 UTC, DarthSidiousPalpatine commented on code/game/objects/structures/fence.dm
> +	var/screwed = TRUE
Не про одно и то же. Анчоред - прикручен к полу. Скревед - прикручен к полу но чуть иначе :dovolen:
Подкручен, можно сказать. Подкрученные заборы можно крутить и если попытаться через них перелезть то ты упадёшь смешно :P

2024-01-22 18:21 UTC, DarthSidiousPalpatine commented on code/game/objects/structures/fence.dm
> +/obj/structure/fence
Это забор для мапперов. Неразрушимый и бетонный :dovolen:

2024-02-21 16:47 UTC, closed without merging

2024-02-22 11:28 UTC, DarthSidiousPalpatine commented
Спасибо воласу за счастливое детство.