Комоды заимели диры, Комоды стали прозрачны для вытсрелов и на них можно залезть.
TauCetiStation/TauCetiClassic pull request #11326
Opened 2023-04-23 10:18 UTC by DarthSidiousPalpatine

## Описание изменений
Комоды заимели диры.
Комоды стали прозрачны для кидания вещей и выстрелов.
На комоды можно залезть.

## Почему и что этот ПР улучшит
Комоды перестали быть супермега структурой которая блокирует угловое взаимодействие.
Теперь можно строить удобные кабинеты.

## Авторство
AndreyGysev и все все все, кто помогал в дискорде.

## Чеинжлог
 :cl:
 - tweak: Комод получил диры, на комод можно залезть, через комод можно кидать предметы.

2023-04-23 10:18 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2023-04-23 11:26 UTC, UDaV73rus commented
гисев ты...
![image](https://user-images.githubusercontent.com/33157992/233837096-23bee1f9-582e-4e3f-b7e4-32e9b738c6c0.png)

2023-04-23 16:52 UTC, Tap0r commented
Вот би сборку разборку.

2023-04-24 04:25 UTC, DarthSidiousPalpatine commented
> Вот би сборку разборку.

Всё для тебя, Тапор. Сделал возможность сборки/разборки.

2023-04-24 04:28 UTC, DarthSidiousPalpatine commented
> гисев ты... ![image](https://user-images.githubusercontent.com/33157992/233837096-23bee1f9-582e-4e3f-b7e4-32e9b738c6c0.png)

А тебе добавил сзади вент. щели, чтобы документы внутри не прели :smile: и чтобы разбавить спрайт пустой стены, хз.

2023-04-27 13:35 UTC, UDaV73rus requested changes
не нужно

боковые если только МОЩНО как-то обоснуешь со скриншотами как круто всё смотрится с ними, и как плохо без них

2023-04-30 14:59 UTC, DarthSidiousPalpatine commented
Лижард всегда прав.

2023-05-04 02:56 UTC, LudwigVonChesterfield commented
Тебе эти спрайты для чего-то конкретного нужны?

Если нет, можно вытащить все спрайтоизменения в отдельный ПР а тут оставить только механики?

2023-05-04 03:06 UTC, DarthSidiousPalpatine commented
> Тебе эти спрайты для чего-то конкретного нужны?
> 
> Если нет, можно вытащить все спрайтоизменения в отдельный ПР а тут оставить только механики?

блин да, спрайты нужны для диров.

Диры + остальная фигня нужны вкупе для того чтобы сделать кабинетики не гробами фуллтайл блокирующими всё подряд, а удобной фигнёй которая позволит удобно делать кабинеты.


НО окей, приду разрежу на три ПРа.

2023-05-08 16:36 UTC, UDaV73rus approved these changes
Коисцину понравились боковые, у меня негатив к такому был из-за планов Гисева на повороты всякой машинерии на стенах и всего такого. Северный убрать нужно в любом случае

2023-05-08 16:51 UTC, KIBORG04 commented
конфликтс

2023-05-08 16:54 UTC, DarthSidiousPalpatine commented
> конфликтс

исправил

2023-05-08 19:15 UTC, DarthSidiousPalpatine commented
> Коисцину понравились боковые, у меня негатив к такому был из-за планов Гисева на повороты всякой машинерии на стенах и всего такого. Северный убрать нужно в любом случае

В городе бузина, а в Киеве дядька.
Каким образом поворот настенной машинерии относится к повороту напольной мебели - остаётся для меня загадкой.
Хорошо хоть Coiscin подействовал как-то.

2023-05-10 23:28 UTC, LudwigVonChesterfield commented
залейте кто-нибудь превьюшку апрув спрайтдепа вроде уже есть

2023-05-11 02:50 UTC, DarthSidiousPalpatine commented
> залейте кто-нибудь превьюшку как выглядит в игре апрув спрайтдепа вроде уже есть

готово

2023-05-12 20:59 UTC, LudwigVonChesterfield commented
когда комод смотрит на север очень грустно что пропадает анимация но раз уже апрувнули надо мержить..

2023-05-12 20:59 UTC, LudwigVonChesterfield submitted a review, later dismissed

2023-05-12 20:59 UTC, LudwigVonChesterfield commented on code/game/objects/items/stacks/sheets/sheet_types.dm
> +	new/datum/stack_recipe_list("Мебель", list(
... почему тут переводы?..

2023-05-12 20:59 UTC, LudwigVonChesterfield commented on code/modules/paperwork/filingcabinet.dm
> +	throwpass = 1	//You can throw objects over this, despite it's density.")
TRUE?

2023-05-12 21:00 UTC, LudwigVonChesterfield commented on code/modules/paperwork/filingcabinet.dm
> +	throwpass = 1	//You can throw objects over this, despite it's density.")
разве он не должен тогда ещё пропускать летающих существ?

2023-05-12 21:00 UTC, LudwigVonChesterfield commented on code/modules/paperwork/filingcabinet.dm
> -		to_chat(user, "<span class='notice'>You can't put [P] in [src]!</span>")
почему убрал довольно хорошее сообщение игроку

2023-05-12 21:01 UTC, LudwigVonChesterfield commented on code/modules/paperwork/filingcabinet.dm
> +			flick("[initial(icon_state)]-open", src)
что произойдёт если откротю пока проигрывается анимация

2023-05-13 05:18 UTC, DarthSidiousPalpatine commented on code/modules/paperwork/filingcabinet.dm
> +	throwpass = 1	//You can throw objects over this, despite it's density.")
А он не пропускает летающих существ?

А у нас есть летающие существа?

2023-05-13 05:19 UTC, DarthSidiousPalpatine commented on code/modules/paperwork/filingcabinet.dm
> +			flick("[initial(icon_state)]-open", src)
О что должно произойти? Ну открыл и открыл, че такого?

2023-05-13 05:19 UTC, DarthSidiousPalpatine commented on code/modules/paperwork/filingcabinet.dm
> -		to_chat(user, "<span class='notice'>You can't put [P] in [src]!</span>")
Окей, добавлю.

2023-05-13 05:25 UTC, KIBORG04 commented on code/modules/paperwork/filingcabinet.dm
> +	throwpass = 1	//You can throw objects over this, despite it's density.")
Есть летающие

2023-05-15 18:08 UTC, LudwigVonChesterfield commented on code/modules/paperwork/filingcabinet.dm
> +			flick("[initial(icon_state)]-open", src)
у тебя анимация проигрывается дважды, я не знаю как это будет работать. ты походу не затестил.

2023-05-15 18:08 UTC, LudwigVonChesterfield commented on code/modules/paperwork/filingcabinet.dm
> +	throwpass = 1	//You can throw objects over this, despite it's density.")
> А он не пропускает летающих существ?

а он пропускает?

2023-05-15 18:56 UTC, DarthSidiousPalpatine commented on code/modules/paperwork/filingcabinet.dm
> +			flick("[initial(icon_state)]-open", src)
Ну проигрывается и проигрывается?

2023-05-27 03:30 UTC, LudwigVonChesterfield requested changes
переводы лишние,
не понятно пропускает ли летучих существ,
пропало сообщение о том что нельзя класть вещи,
не понятно что происходит если дважды проиграть анимацию открытия одновременно и не сломается ли ничего

2023-09-24 12:30 UTC, DarthSidiousPalpatine commented
Так, крч, убрал лишние переводы, добавил утерянное сообщение, проверил ломается ли картинка при двойной активации ящика - не ломается. Пролетают ли мобы - пролетают потому что они чекают тхровпасс. Кароч, всё чётко.

2023-09-25 11:17 UTC, WatlerJe approved these changes

2023-10-01 09:56 UTC, DarthSidiousPalpatine commented
Обновил конфликт. Вальтер апрувнул комоды. Так что хз, можете мержить.

2023-10-10 15:01 UTC, DarthSidiousPalpatine commented
А это Вальтер апрувнул, а остальное я вырезал. Чисто спрайты тут.

2023-10-11 20:37 UTC, KIBORG04 commented
> @KIBORG04 прив как дела?

@DarthSidiousPalpatine Устал

2023-10-11 21:56 UTC, KIBORG04 commented on code/modules/paperwork/filingcabinet.dm
> +	throwpass = 1	//You can throw objects over this, despite it's density.")
```suggestion
	throwpass = TRUE//You can throw objects over this, despite it's density.")
```

2023-10-11 21:57 UTC, KIBORG04 commented on code/modules/paperwork/filingcabinet.dm
> +	else if(isscrewing(P))
в ПРе же 0 слов, что с помощью отвертки оно разбирается

2023-10-11 21:58 UTC, KIBORG04 commented on code/modules/paperwork/filingcabinet.dm
> +			flick("[initial(icon_state)]-open", src)
> у тебя анимация проигрывается дважды, я не знаю как это будет работать. ты походу не затестил.

Затестил?

2023-10-11 22:46 UTC, KIBORG04 approved these changes
Ээээ, ну вроде и нечево еще сказать хз

2023-10-12 03:32 UTC, DarthSidiousPalpatine commented on code/modules/paperwork/filingcabinet.dm
> +	else if(isscrewing(P))
написал

2023-10-13 23:36 UTC, merged