Обновлены файлы локализации
TauCetiStation/TauCetiClassic pull request #11339
Opened 2023-04-26 14:20 UTC by BasiaBelov

## Описание изменений
Волас давно просил, но сделал я это только сейчас...
Исправил вещи под `name = ...` на русском, так как они сильно выбивались из текста игры.
И [этот чудо-ишуй](https://github.com/TauCetiStation/TauCetiClassic/issues/10072).
## Почему и что этот ПР улучшит
Как пример, исправит это: 
![image](https://user-images.githubusercontent.com/115452414/234604353-ecd60bc3-28c7-4571-a9c1-512fd4544d62.png)
## Авторство
Я и комментарии @Lexakr 
## Чеинжлог
:cl: Basia
- bugfix: Обновлены файлы локализации

2023-04-26 14:20 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2023-05-01 14:49 UTC, volas commented
Я в дискорде писал, нужно что бы книга осталась на русском. Сейчас там в
``/datum/spellbook_entry/proc/GetInfo()``
берется именно название заклинания из ``/obj/effect/proc_holder/spell``. Вариант решения я писал в самом ишью. 

Может быть можно было бы использовать не имя спелла в Getinfo, а имя враппера ``/datum/spellbook_entry``, и тогда твой вариант с переводом только у spellbook_entry был бы ок.

2023-05-01 14:50 UTC, volas requested changes
^

2023-05-16 22:03 UTC, AzzyDreemurr13 commented
@BasiaBelov , тебе тут Волас запросил изменения, а ты не реагируешь

2023-05-17 00:45 UTC, BasiaBelov commented
Реагирую, но с задержкой в три недели.

2023-06-03 13:10 UTC, KIBORG04 commented
Не среагировал, попроси открыть, если будет готово

2023-06-03 13:10 UTC, closed without merging