Shadowling and lights
TauCetiStation/TauCetiClassic pull request #11396
Opened 2023-05-08 11:12 UTC by Chip11-n

## Описание изменений
Когда шедоулинг использует веил (спелл гасящий свет), он вырубает лампы, двери и фонарики у людей, но вот остальное не трогает. Теперь слинг гасит ещё и:
- Компьютеры (свет от них)
- Вендоматы
- Обезьян и всех живых

А также убрана двойная проверка списка для дверей и ламп.
## Почему и что этот ПР улучшит

## Авторство

## Чеинжлог
:cl: 
- bugfix: Тенелинги научились гасить свет компьютеров, вендоматов и обезьян

2023-05-08 11:12 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2023-05-08 11:15 UTC, Deahaka commented on code/game/gamemodes/modes_gameplays/shadowling/shadowling_abilities.dm
> +				L.on = 0
Могу ошибаться, но может быть тут надо `FALSE`

2023-05-08 14:59 UTC, LudwigVonChesterfield commented on code/game/gamemodes/modes_gameplays/shadowling/shadowling_abilities.dm
> +		for(var/obj/machinery/M in T.contents)
какие подводные проходиться по всему вокруг вообще и делать set_light(0)

2023-05-08 15:03 UTC, Chip11-n commented on code/game/gamemodes/modes_gameplays/shadowling/shadowling_abilities.dm
> +		for(var/obj/machinery/M in T.contents)
К примеру, не хочу делать тёмные и горящие костры. Да и ведь смешно видеть все новые абузы

2023-05-08 17:00 UTC, volas commented on code/game/gamemodes/modes_gameplays/shadowling/shadowling_abilities.dm
> +		for(var/obj/machinery/M in T.contents)
set_light очень низкоуровневый метод, что бы дергать отсюда. Может как сломать что-то до конца раунда, так и сломать только до ближайшего обновления с апц. Могу предложить два варианта:
1. Добавить источникам света свой метод для отключения света, и всё обрабатывать на стороне предмета, как это уже так работает для предметов выше. Например добавить машинерии какой-нибудь флаг nolight, который бы сбрасывался только после её переразбора. Или выключать вовсе как с nopower, потому что будет странно, если экран всё еще горит - а свет от него не идет.
2. Добавить порог для шедоулинга, что бы минимальное атмосферное освещение его не трогало.

2023-05-16 16:50 UTC, Chip11-n commented on code/game/gamemodes/modes_gameplays/shadowling/shadowling_abilities.dm
> +		for(var/obj/machinery/M in T.contents)
Сделано. Через `set_light()` мы выполняем функции выключения и включения.

2023-05-18 20:26 UTC, LudwigVonChesterfield commented on code/game/objects/items/devices/flashlight.dm
> +	if(l_range == 0)
интересный подход конечно...

@volas думаю ты не про это думал, правда?

2023-05-18 20:50 UTC, Chip11-n commented on code/game/objects/items/devices/flashlight.dm
> +	if(l_range == 0)
Это универсальный прок, который всегда юзается при выключении света. Если создавать ещё один прок, то будет и путаница, и переусложнение и дополнительные диффы. Но с переменной да, идей лучше не было

2023-05-18 21:46 UTC, volas commented on code/game/objects/items/devices/flashlight.dm
> +	if(l_range == 0)
да, это совсем не торт, еще и флаги где-то стали перегружаться у машинерии

2023-05-18 21:50 UTC, volas commented on code/game/gamemodes/modes_gameplays/shadowling/shadowling_abilities.dm
> +		for(var/obj/machinery/M in T.contents)
``set_light`` это прок сабсистемы освещения, он низкоуровневый и его задача - только дергать свет. Использовать его таким образом не стоит.

2023-05-19 03:05 UTC, LudwigVonChesterfield commented on code/game/gamemodes/modes_gameplays/shadowling/shadowling_abilities.dm
> +		for(var/obj/machinery/M in T.contents)
рекомендую сделать новую функцию что-то типо "toggle_lights" или "turn_light_off" и юзать её у всего на что должен влиять шедоулинг...

(кстати почему бы не shadowling_act)

2023-05-27 03:34 UTC, LudwigVonChesterfield requested changes
нужно:

всем вещам которые может отключать шедоулинг дать ИЛИ

/proc/shadowling_act

ИЛИ

/proc/turn_off

в котором обрабатывать всю логику выключения вещи корректно, чтобы ничего не сломалось.

тогда спелл линга будет проходиться по всем вещам и вызывать у них этот shadowling_act или turn_off

2023-05-29 21:20 UTC, Chip11-n commented
Перевёл действо на отдельную проку.

2023-05-29 21:52 UTC, LudwigVonChesterfield commented on code/game/gamemodes/modes_gameplays/shadowling/shadowling_abilities.dm
> +			if(istype(M,/obj/machinery/light))
почему бы эту лесенку ифов тоже не вынести в turn_light_off()

2023-05-29 21:53 UTC, LudwigVonChesterfield commented on code/game/gamemodes/modes_gameplays/shadowling/shadowling_abilities.dm
> +			if(istype(M,/obj/machinery/light))
можно было бы

```
for(var/obj/O in T.contents)
    O.turn_light_off()
    
 for(var/mob/living/L in T.contents)
     L.turn_light_off() // выключение всех предметов на мобе внутри этой функции
```

2023-05-29 21:57 UTC, volas commented on code/game/objects/items/devices/flashlight.dm
> +	. = ..()
в таких местах не обязательно вызывать родителя, на уровне предмета оно само уже должно нормально обрабатываться. А так, выглядит гораздо лучше :+1:

2023-05-29 22:02 UTC, volas commented on code/game/machinery/computer/computer.dm
> +	update_icon()
у машинерии NOPOWER будет работать только до первого вызова обновления с АПЦ. Может BROKEN или какой-то новый флаг лучше подойдет.

+ для обновления статуса нужен не апдейт иконки, а какой-то прок машинерии.

2023-06-04 10:32 UTC, Chip11-n commented on code/game/machinery/computer/computer.dm
> +	update_icon()
Я не хотел бы делать вейл ультимативным, ломающим вендоматы, компьютеры и так далее. Чинят их в большинстве своём инженеры, которые цель №1 для шедоу. 

Так, любой желающий может просто "перезагрузить" необходимую ему машинерию, собственно, как и происходит с лампами (вытащить и всунуть).

`power_change` исполняет одновременно и проверку., а потому просто перенёс её часть в проку.

2023-06-04 10:33 UTC, Chip11-n commented on code/game/objects/items/devices/flashlight.dm
> +	. = ..()
Там ещё у фонарика своё поведение. Стоит всё перенести в 1 место, без `. = ..()`?

2023-06-04 10:34 UTC, Chip11-n commented on code/game/gamemodes/modes_gameplays/shadowling/shadowling_abilities.dm
> +			if(istype(M,/obj/machinery/light))
В общем, как раньше писали, переделал на атом. Но за права костров буду драться.

2023-06-04 10:40 UTC, Chip11-n commented
По какой-то причине слайм лампочки были невидимые. В файлах нашёл только спрайт `floor` (`floor1` был)

2023-06-13 19:28 UTC, volas approved these changes

2023-06-13 19:30 UTC, volas commented on code/game/objects/items/devices/flashlight.dm
> +	. = ..()
я к тому, что ``turn_off`` флейра уже делает всю работу по "выключению" флейра - можно было бы только его и оставить, без вызова ..()

2023-06-13 19:32 UTC, volas commented
> По какой-то причине слайм лампочки были невидимые. В файлах нашёл только спрайт floor (floor1 был)

мой косяк, я думал это напольные которые не используются, а они оказывается тут были

2023-06-13 19:34 UTC, volas commented on code/game/machinery/computer/computer.dm
> +	update_icon()
если так, то без кд какой-нибудь ИИ через апц сможет быстро возвращать их обратно

2023-06-13 19:57 UTC, LudwigVonChesterfield commented on code/game/machinery/computer/computer.dm
> +	update_icon()
прикольно, социалочка, надо кого-то втягивать чтобы быстро включать.

но лучше реально сделать чтобы от света экранчиков наша древняя НЕХ из открытого космоса не умирала

2023-06-13 20:09 UTC, volas commented on code/game/machinery/computer/computer.dm
> +	update_icon()
я соглашусь, где-то там был дефайн с люммами. Но это можно и отдельным ПР-ом

2023-06-20 11:54 UTC, merged