Чемоданчик
TauCetiStation/TauCetiClassic pull request #11398
Opened 2023-05-08 12:26 UTC by DarthSidiousPalpatine

## Описание изменений
![pri-ugroze-terroristicheskogo-akta_1610977617926912112](https://user-images.githubusercontent.com/21008918/236823348-e6ee339a-0bc6-4e3b-88ed-a966e9220646.jpg)

## Почему и что этот ПР улучшит
Отучит разминировать лицом сумки, а также вообще лезть в бесхозные сумки.

## Авторство
AndreyGysev и все все все, кто помогал в дискорде.

## Чеинжлог
 :cl:
  - rscadd: Добавлен рандомраундстартивент на появление сумки в случайном месте станции. В сумке может быть мина или обычные предметы.

2023-05-08 12:26 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2023-05-08 12:29 UTC, TauKitty commented
Этот запрос на слияние был упомянут в **Tau Ceti Station Forum**. Там могут быть соответствующие подробности:

https://forum.taucetistation.org/t/fludilka-chast-2/28659/23153

2023-05-08 14:53 UTC, LudwigVonChesterfield commented on code/game/objects/items/weapons/grenades/chem_grenade.dm
> +	B1.reagents.add_reagent("potassium", 50)
может ли устроить разгерму? если да - плохо

2023-05-08 14:54 UTC, LudwigVonChesterfield commented on code/game/objects/random/random_misc.dm
> +	var/obj/item/weapon/storage/Bag = ..()
что тут происходит

2023-05-08 14:55 UTC, DarthSidiousPalpatine commented on code/game/objects/random/random_misc.dm
> +	var/obj/item/weapon/storage/Bag = ..()
Подвязываюсь к родительскому проку рандомов - спавн рандомпредмета из списка.

Когда предмет спавнится я его подтягиваю в потомка сюда и определяю его сумкой, которая заспавнилась. В сумку уже кладу что мне надо.

2023-05-08 14:55 UTC, LudwigVonChesterfield commented on code/game/objects/random/random_misc.dm
> +			if(istype(Bag, /obj/item/weapon/storage/box) || istype(Bag, /obj/item/weapon/storage/pouch/medium_generic))
мне кажется лучше было бы иметь

random/box
random/pouch

а потом

/obj/item/random/filled_storage
   spawn_list = list(
       random/box = шанс,
       random/pouch = шанс,
 
 
чем спагетти которое происходит сейчас

2023-05-08 14:55 UTC, DarthSidiousPalpatine commented on code/game/objects/items/weapons/grenades/chem_grenade.dm
> +	B1.reagents.add_reagent("potassium", 50)
не может

2023-05-08 14:56 UTC, DarthSidiousPalpatine commented on code/game/objects/random/random_misc.dm
> +			if(istype(Bag, /obj/item/weapon/storage/box) || istype(Bag, /obj/item/weapon/storage/pouch/medium_generic))
Круто, канеш, но тогда надо иметь 5-6 random/box/mine random/pouch/mine и пр. внутри которых 5-6 раз определять atom_init и т.д. и т.п.

2023-05-08 14:56 UTC, DarthSidiousPalpatine commented on code/game/objects/random/random_misc.dm
> +			if(istype(Bag, /obj/item/weapon/storage/box) || istype(Bag, /obj/item/weapon/storage/pouch/medium_generic))
Единственное как я мог бы сейчас улучшить это сунуть общие предметы в один лист. И сумкам добавлять прост дополнительные.

2023-05-09 16:19 UTC, DarthSidiousPalpatine commented on code/game/objects/random/random_misc.dm
> +			if(istype(Bag, /obj/item/weapon/storage/box) || istype(Bag, /obj/item/weapon/storage/pouch/medium_generic))
А, нет, не могу, бьёнд не работает так.

2023-05-10 17:52 UTC, LudwigVonChesterfield commented on code/game/objects/items/weapons/grenades/chem_grenade.dm
> +	B1.reagents.add_reagent("potassium", 50)
возможно стоит сделать гранату которая литерали никогда никак не сможет делать разгерму вместо юзать механ который может поменяться...

2023-05-10 17:54 UTC, DarthSidiousPalpatine commented on code/game/objects/items/weapons/grenades/chem_grenade.dm
> +	B1.reagents.add_reagent("potassium", 50)
Какую, например, и как?

2023-05-15 17:57 UTC, LudwigVonChesterfield requested changes
мне не нрав как реализован рандомизатор

я бы предпочёл рандом/кошелёк, рандом/сумочка, и потом рандом/сторедж

почти везде у нас иерархия именно так и работает

2023-05-15 19:21 UTC, DarthSidiousPalpatine commented
Сделал.

2023-05-18 17:10 UTC, LudwigVonChesterfield commented on code/game/objects/items/weapons/grenades/chem_grenade.dm
> +	B1.reagents.add_reagent("potassium", 50)
найти какая сила ex_act-а не уничтожает полностью тайл, сделать новую реакцию (или просто сделать гранату которая волшебным образом вызывает именно такой силы ex_act у тайлов вокруг)

потому-что если эта штука сейчас или когда-либо в будущем будет делать разгермы будет грустно.

2023-05-30 05:05 UTC, DarthSidiousPalpatine commented
Вот тут из требований - ты хочешь особую гранату.

2023-05-30 05:07 UTC, LudwigVonChesterfield commented on code/game/objects/random/random_misc.dm
> +/obj/random/misc/mine
выглядит будто это рандомная мина а не коробка с миной

2023-05-30 05:08 UTC, DarthSidiousPalpatine commented on code/game/objects/random/random_misc.dm
> +/obj/random/misc/mine
так на картинке с ней будет сумка. так что явно будет понятно что это рандомная коробка с миной

2023-05-30 05:09 UTC, LudwigVonChesterfield commented on code/game/objects/random/random_misc.dm
> +		new /obj/item/weapon/grenade/chem_grenade/mine(Bag)
в чем прикол больше одной гранаты

2023-05-30 05:10 UTC, DarthSidiousPalpatine commented on code/game/objects/random/random_misc.dm
> +		new /obj/item/weapon/grenade/chem_grenade/mine(Bag)
5 гранат по 30 ломают человека но не ломают тайлы.

2023-05-30 05:10 UTC, LudwigVonChesterfield commented on code/game/objects/random/random_misc.dm
> +	if(prob(30))
тут и везде переписать на вид

```
if(prob(30))
    ...
    return

for ...
    ...
```
(т.н. "ранний возврат")

2023-05-30 05:10 UTC, LudwigVonChesterfield commented on code/modules/assembly/holder.dm
> +/obj/item/device/assembly_holder/mousetrap_igniter
можно ли его скрафтить или только щитспавн?

2023-05-30 05:11 UTC, LudwigVonChesterfield commented on code/game/objects/random/random_misc.dm
> +/obj/random/misc/mine
названия важны. в названии написано что это мина а не сумка с миной. напиши что это сумка с миной

2023-05-30 05:12 UTC, LudwigVonChesterfield commented on code/game/objects/random/random_misc.dm
> +		new /obj/item/weapon/grenade/chem_grenade/mine(Bag)
а 1 граната не ломает?

2023-05-30 05:12 UTC, DarthSidiousPalpatine commented on code/modules/assembly/holder.dm
> +/obj/item/device/assembly_holder/mousetrap_igniter
вроде также как с обычным ассембли холдером с таймером - это щитспавн для пресетов гранат.

Так-то в обычную гранату можно сунуть мышеловку с игнайтером. Оно не будет конкретным холдером.
Конкретный холдер как и таймер холдер, нужен для пресета.

2023-05-30 05:13 UTC, LudwigVonChesterfield commented on code/game/objects/random/random_misc.dm
> +		new /obj/item/weapon/grenade/chem_grenade/mine(Bag)
ну и в любом случае заменить на
```
for(var/i in 1 to количество)
    new граната
```

2023-08-16 14:45 UTC, DarthSidiousPalpatine commented
Как бы я хотел это вернуть и довести до мержа, Людук приди.

2023-08-16 14:45 UTC, DarthSidiousPalpatine commented
Так, ща тогда проверю сделал ли я то о чём ты тут написал и не скрыл и спрошу что дальше.

2023-08-17 07:41 UTC, DarthSidiousPalpatine commented
Спасибо воласу.

2023-08-17 07:41 UTC, closed without merging

2023-08-17 07:57 UTC, DarthSidiousPalpatine commented
Волас поменял взрывы и теперь какой бы бомбу и в скольких количествах не делал не добиться гиба руки при сохранении тайла под челом

Волас поменял полностью код рандом предметов и теперь я не могу подтягиваться внутрь прока после спавна предмета и пихать в сумку лут или гранаты

Волас требует написать, блять, свой, параллельный тип рандомных, блять, предметов, просто потому что его тип не возвращает предмет что он спавнит. Ахуенно.

Да нахуй это всё, блять, заебись фича была, немного доп. работки сбухам, разминирование, всё такое. Замержили бы раньше - Волас бы со всем этим ебался, ну или удалил бы фичу. А я не буду.

2023-08-17 08:27 UTC, volas commented
1. Нечего браться за десяток ПРов и не доводить их до мержа, ждать конфлитков.
2. Нужно читать и слушать, что я пишу, я всё объяснил и даже накидал вариант и предложил помощь.
3. По взрывам есть ишью и обсуждения на форуме, я открыт для фидбека.
4. Я бы даже мог из принципа доделать всё сам за тебя, что бы показать, насколько ты тормоз, но мне не нравится фича и других профитов нет.

2023-08-17 08:29 UTC, DarthSidiousPalpatine commented
Даа дааа, конечно.