ГП квоты на профы.
TauCetiStation/TauCetiClassic pull request #11416
Opened 2023-05-13 22:25 UTC by DarthSidiousPalpatine

## Описание изменений
ГП может поставить акцент на выбранную профу и этот акцент увидят заходящие на сервер, дескать, станции нужна эта профа.
Акцентов в списке сохраняется всего три, можно все три в одну профу и игрок увидит три !!!, или 2 в одну 1 в другую или по одному в разные и т.п., в зависимости от того что надо ГП. Каждый следующий выбор перезаписывает старый.
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/21008918/e247627e-adae-4a76-a468-2c3185f51118)
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/21008918/fc50ab79-ed6b-41d3-bf17-97acab4bc950)

## Почему и что этот ПР улучшит
Удобно всяким заходящим далеко после старта раунда.

## Авторство
AndreyGysev и все все все, кто помогал в дискорде.

## Чеинжлог
 :cl:
  - rscadd: Появилась возможность выставить акцент на профессию, который увидят заходящие на сервер.

2023-05-13 22:25 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2023-05-13 22:25 UTC, DarthSidiousPalpatine commented
Симпле солюшн ту евридей проблем.

2023-05-13 22:57 UTC, KIBORG04 commented on code/modules/mob/dead/new_player/new_player.dm
> +				var/job_quota = "<B><FONT COLOR=red>"
FONT устаревший тег, пожалуйста, не используйте его

2023-05-14 06:03 UTC, DarthSidiousPalpatine commented on code/modules/mob/dead/new_player/new_player.dm
> +				var/job_quota = "<B><FONT COLOR=red>"
ок, как можно покрасить в красный не устаревшим тегом?

2023-05-14 06:47 UTC, DarthSidiousPalpatine commented on code/modules/mob/dead/new_player/new_player.dm
> +				var/job_quota = "<B><FONT COLOR=red>"
Переделал на нормальный

2023-05-15 17:45 UTC, LudwigVonChesterfield commented on code/game/machinery/computer/card.dm
> +	var/list/jobs_quotas = list()
прошу сделай какой-то файлик где это будет абстрагировано в функции

add_job_quota
remove_job_quota
init_job_quota_list

сейчас очень страшный код смешан с относительно нормальным высокоуровневым кодом

2023-05-15 17:47 UTC, LudwigVonChesterfield commented on nano/templates/identification_computer.tmpl
> +        Quotted jobs:
это точно так не называется...

Quota Jobs возможно

2023-05-15 17:47 UTC, LudwigVonChesterfield commented on nano/templates/identification_computer.tmpl
> +      {{for data.quotted_jobs}}
как-то грустно будет что вместо тройная важность ГСБ, будет три раза ГСБ. можно ли это исправить?

2023-05-15 17:47 UTC, LudwigVonChesterfield approved these changes
прикольный ПР

2023-05-15 17:48 UTC, LudwigVonChesterfield commented
можно ли интегрировать ещё как-то с газетой? чтобы в газете писалось какие квоты.

2023-05-15 18:52 UTC, DarthSidiousPalpatine commented
Сделал всё что надо.

2023-05-15 18:53 UTC, DarthSidiousPalpatine commented
Кроме того что не убрал автоснятие квоты, не сделал чтобы в консоли отображались х2 х3 вместо повторения и не сделал ньюскастер фичу.

первое потому что слишком много проблем, ты сам описал в дисе.
второе потому что не получилось, наноуи такой кал половинчатый.
третье потому что ну такое.

2023-05-15 18:53 UTC, DarthSidiousPalpatine commented
Но в целом, переименовал штуки, вынес проки и пр.

2023-05-15 19:42 UTC, LudwigVonChesterfield commented on code/game/machinery/computer/card.dm
> +/obj/machinery/computer/card/proc/setup_quotas()
тут кажется get_quotas?

2023-05-15 19:43 UTC, LudwigVonChesterfield commented on code/game/machinery/computer/card.dm
> +		if ("add_job_to_quotas")
сейчас нет возможности удалить квоты?

2023-05-16 11:01 UTC, DarthSidiousPalpatine commented on code/game/machinery/computer/card.dm
> +		if ("add_job_to_quotas")
Удаляются сами, угу.

2023-05-16 17:44 UTC, volas commented
То, что давно требовалось :+1: 

> Квоты удаляются каждый раз когда приходит зарплатка, т.е. раз в 15 минут.

Лучше сделать удаление по заполнению, хоп-у бегать каждые 15 минут к консоли не круто будет

2023-05-16 17:47 UTC, volas commented on code/controllers/subsystem/economy.dm
> +	global.station_jobs_quotas = list(null, null, null)
Я знаю, ты не любишь учиться по чужому опыту, но прошу посмотреть как на тг и других серверах сделали ``prioritized_job``. Оперировать датумами будет лучше, чем названиями, и сам список вместо глобала заполняемого в сабсистеме экономики лучше вынести в сабсистему SSjob

2023-05-18 20:23 UTC, LudwigVonChesterfield commented
> Лучше сделать удаление по заполнению, хоп-у бегать каждые 15 минут к консоли не круто будет

что должно произойти если тройной приоритет поставили на ГСБ (которых может быть только 1)

что должно произойти если ГП назначил роль внутри игры...

2023-05-21 00:12 UTC, LudwigVonChesterfield commented on code/controllers/subsystem/economy.dm
> +	global.station_jobs_quotas = list(null, null, null)
https://github.com/tgstation/tgstation/blob/05535c94123e9a5c6b3327ec0c845a0f1fb83af7/code/modules/modular_computers/file_system/programs/jobmanagement.dm#L107

но ведь литерали так же, просто в другом месте.

2023-05-21 00:13 UTC, LudwigVonChesterfield requested changes
Волас хочет чтобы station_jobs_quotas было переименовано в priotized_jobs, и перенесено в SSjob контроллер

я ещё прошу всё таки сделать чтобы если кто-то зашёл за профу (или кого-то назначил ГП) то оно удалялось из списка один раз.

если профа достигла своего лимита то чтобы удалялись все квоты на эту профу.

2023-06-05 10:38 UTC, Naroke commented
чё по квотам?

2023-06-06 01:19 UTC, LudwigVonChesterfield commented
Очень хороший ПР который обязательно надо доделать, но автор получил травму, ПР обрёл конфликты, в общем откроем как будет желание допилить.

2023-06-06 01:19 UTC, closed without merging