Kentucky Fried Vox
TauCetiStation/TauCetiClassic pull request #11410
Opened 2023-05-11 20:03 UTC by Deahaka

## Описание изменений
Жарим воксов в фритюре и получаем неимоверные крылышки
![00000000000000000000000000000000000000](https://github.com/TauCetiStation/TauCetiClassic/assets/96499407/84e16b99-990e-4541-8a91-ce59cce5d2be)
## Почему и что этот ПР улучшит
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/96499407/bf11037e-906c-4aa6-a45d-becfb1649504)
## Авторство
Порт с Парадизов (англ): https://github.com/ParadiseSS13/Paradise/pull/13114
## Чеинжлог
:cl: Ty-Omaha, Farie82, Ionward
- add: Теперь можно жарить части тела воксов в фритюре повара.

2023-05-11 20:03 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2023-05-11 21:05 UTC, KIBORG04 requested changes
Че за бред

2023-05-11 21:30 UTC, AndroBetel commented
на парадизах код лучше

2023-05-11 23:31 UTC, LudwigVonChesterfield commented
почему Киборч дизлайкнул не понимаю, забавное же...

2023-05-12 08:11 UTC, Deahaka commented
> на парадизах код лучше

Надо становится их форком. Как раз новые расы и снятие ограничений на профы подтянем

2023-05-16 22:14 UTC, AzzyDreemurr13 commented
Бля, это что ПР который забыли на первое апреля?🤣🤣🤣

2023-05-22 10:54 UTC, closed without merging