Hydro resprite
TauCetiStation/TauCetiClassic pull request #11439
Opened 2023-05-21 10:46 UTC by Tap0r

## Описание изменений
* Респрайт одежды ботаников.
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/88531962/5ee85073-3863-4db7-8cf4-3cd4e86fc698)
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/88531962/1ea5621b-1e22-4e47-a4e4-48acfe7d7ee3)
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/88531962/23263f05-6ff0-4cb8-8e50-09093018e559)
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/88531962/340cfe54-a092-4de5-b1c8-e185079b808f)
* Добавлен спрайт спущенной формы для жирничей 
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/88531962/f8ce2e25-d8b7-406a-a08b-51f727a016ba)
* hydroponics_f заменён на hydroponics_lite. Потому что раньше, до тонкотрапов, гидро_ф служил фем версией одежды ботаников. Но сейчас вообще мем, фем версия есть и у обычного джампсюита (hydroponics_fem), и у его бывшей фем версии (hydroponics_f_fem). А lite из себя представляет просто облегчённую форму ботаников.
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/88531962/24164d87-88e1-4261-968a-8880942a77f5)

## Почему и что этот ПР улучшит
красивое
## Авторство

## Чеинжлог
:cl: 
 - image[link]: Обновлены спрайты одежды ботаников.

2023-05-21 10:46 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2023-05-21 12:37 UTC, UDaV73rus requested changes
- hydroponics_f_fem забыл допереименовать в lite

- В этих местах спина, а не рука, нужно закрыть
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/33157992/1c5c0fa6-722b-4d81-8d3d-8f28199540dd)

- Воротник с несколькими оттенками выглдяит слишком размазанно
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/33157992/e04131a8-6414-487c-b03c-f302c5c2bf20)

- В паху лишние тени, у баб вообще втф
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/33157992/cc413204-2cbc-44f7-95cb-8be7ee92326e) ![image](https://github.com/TauCetiStation/TauCetiClassic/assets/33157992/e47c525a-d0a3-44ff-bb55-8b99e9524e4c)



- У толстых нужно осветлить висящий живот. 
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/33157992/b7751a05-db83-4d5d-b6a9-ee735093e710)

2023-05-21 12:41 UTC, UDaV73rus commented
здесь линия тени неизвестно почему. Это же просто тряпка сложанная по диагонали. Внутри тени странные, нужно вдумчивее их наложить, а не рандомно

![image](https://github.com/TauCetiStation/TauCetiClassic/assets/33157992/5b454943-459e-4f8d-b00d-8177f0268f91)

2023-05-28 23:07 UTC, KIBORG04 commented
Автор, думаю ты сам позовешь спройтеров для аппрува

2023-06-22 01:02 UTC, LudwigVonChesterfield commented
Тут было какое-то обсуждение с спрайтдепом как человек доделает уверен можно будет открыть тем более тут уже всё обросло конфликтами.

2023-06-22 01:02 UTC, closed without merging