текущая карта не будет в списке для воута на следующую карту
TauCetiStation/TauCetiClassic pull request #11438
Opened 2023-05-21 10:01 UTC by AndroBetel

## Описание изменений
тайтл
## Почему и что этот ПР улучшит
игра станет разнообразнее! карты будут развиваться, потому что на них будут играть игроки! сами игроки будут развиваться, ведь познание нового стимулирует мозговую деятельность!
## Авторство
я
## Чеинжлог
:cl:
- experimental: В воуте больше не будет карты, на которой прошёл раунд.

2023-05-21 10:01 UTC, TauKitty commented
###### Changelog status: :x: Invalid changelog classes (experimental)

2023-05-21 10:10 UTC, AgRevol commented
Гамма лобби поддерживает этот ПР

2023-05-21 10:52 UTC, Deahaka commented
![00000000000000000000000000000000000000](https://github.com/TauCetiStation/TauCetiClassic/assets/96499407/9fd87e79-e3e4-4aaa-9e8c-7b75a0d35e3f)

https://github.com/TauCetiStation/TauCetiClassic/pull/10929

2023-05-21 10:55 UTC, SiveanBen commented
Бетель ты гений, теперь я буду поддерживать тебя во всех начинаниях

2023-05-21 10:57 UTC, TryXAH commented
Очень перспективный ПР, который решает несколько проблем и имеет минимум негативных последствий.

Смена привычной обстановки так или иначе даст игрокам другие взгляды на МЕТУ, которая будет отличаться от карты к карте. Вместо застоялого болота одних и тех же тактик игрокам придется адаптироваться к новым тактикам и изменять свои привычные раундстартвые действия. Манчеры по типу морклеба будут неудобно себя чувствовать, не имея за собой стандартный набор утащенных предметов с разных концов бокса.

Такое решение так же вдохнет жизнь в уже заскучавших игроков, которые "прошли" игру. Многие игроки с десятками тысяч минуток так и не видели других карт, и попытка разобраться в новом месте вернет им те радостные ощущения от познания и открытия нового, как будто снова научились садиться на стул в свои первые 100 минуток.

С другой стороны, постоянное нахождение на других картах даст толчок к развитию этих самых карт. Без должного тестирования и игроков новые/старые карты не могут обновляться и следовать тенденциям, когда как бокс тестировался непрерывно и менялся под новые нужды постоянно. ПР же даст необходимое количество игроков, и в следствии, остальные карты получат необходимую поддержку и станут лучше.  

Разные карты будут вдохновлять игроков заниматься маперством и создавать свои новые станции. В данный момент плееры никак не заинтересованы в мапперстве, так как никому не нужно ничего, кроме бокса, и их творение обречено на провал. А так как бокс сам по себе отполирован с годами, отсутствие ошибок или неровностей на карте не дает стимула научиться мапить, чтобы изменить и поправить любимый отдел или отсек. С данным ПРом же будет нужда в таких изменениях, и люди будут предлагать свои решения и изменения к другим станциям.

Единственный же минус, который можно так или иначе подвязать ко всему этому - привычки игрокови их нежелание что либо менять. И если взглянуть в прошлое, эти самые привычки игнорировались как при мерже спрайтов, так и при мерже ребалансов. Данное же перспективное решение, приведет только к положительным ситуациям, и не несет прямого негативного подтекста (мнение людей без личной жизни с сотнями тысяч минуток в расчет можно не брать, они уже просто по другому не умеют играть).

2023-05-21 11:03 UTC, DarthSidiousPalpatine commented
ПР отличный, если появится больше карт-альтернатив Боксу. Сейчас это будет выглядеть как ротация Бокс-Бокс(снег)-Прометей.
Думаю, можно замержить с перспективой допиливания Гаммы Агреволем и Енерти, они уже скоро закончат.

2023-05-21 11:07 UTC, DarkFurrSss commented
Будут играть в основном Бокс-Прометей.
Может лучше бы сильно понижать цену воута на несколько раундов?

2023-05-21 16:33 UTC, LudwigVonChesterfield commented
когда ГрузТорг на Гамме

а ещё мне тоже больше нравится идея с понижением веса а не полный запрет

2023-05-22 12:26 UTC, SkLepP commented
А зачем ограничивать людей в выборе только потому что кому-то захотелось, чтобы происходила ротация? Игрокам предоставляется выбор и если по результатам голосования будет другая карта, значит будет другая карта. Может быть стоит подумать почему не выбирают другие карты, а не заставлять игроков играть на других?

2023-05-22 12:29 UTC, AndroBetel commented
сто тыщ раз уже думали, почему игрокам другие карты не нравятся, ответ прост - они привыкли к боксу и не хотят заново учить другие мапы

2023-05-22 13:11 UTC, TryXAH commented
> "карты будут развиваться, потому что на них будут играть игроки" - перевожу: "Играйте на говне и быть может когда-то говно станет не говном".

Не ну а как ты себе это представляешь то. Чисто в голову всем двум с половиной маперам входит мысль такая "бляха муха а че мы хуево то делали, надо же хорошо делать" и меняют карты к лучшему, все начинают их выбирать и живут все долго и счастливо.


> Может быть стоит подумать почему не выбирают другие карты

За года стабильного бокса просто никто не хочет ничего менять

2023-05-22 16:06 UTC, TryXAH commented
> решение дать шанс познакомиться с картами, а не форсить плохие карты на игрока постоянно.

в воуте присутствует снежный бокс
то есть даже если прям никто не хочет остальное, можно продавливать его с модификатором 0,7
почти как фича с понижением веса
 
> для ознакомления несколько раундов подряд на одной карте было бы проще для игроков, чем менять каждый раунд на новую

Для такого нужен администратор, который за это возьмется.

2023-05-23 23:31 UTC, ViDLiathan commented
Опять нёрф Морклеба

А если серьёзно, то можно на текущую карту ставить множитель меньше. А то хочется на снежной побегать не только зимой.

2023-05-26 18:29 UTC, LudwigVonChesterfield requested changes
Предлагаю следующий вариант переделки который учтёт большую часть пожеланий:
1. карты надо сгруппировать, и вес менять не только карте, но и группе. чтобы люди не обходили низкий вес бокса голосованием за зимний бокс. то есть если текущая карта бокс, в голосовании вес понизится и на бокс и на зимний бокс
2. понижение веса надо стакать. условно если два раза бокс подряд - -10% к весу, если три - 20% и так далее, до какого-то порога. Порог нужен чтобы ПОДАВЛЯЮЩИМ большинством (условно 90% проголосовавших) все равно можно было ставить текущую карту.

Думаю в таком варианте возражений ни у кого быть не может, и если так сделать то можно будет замержить на постоянку как вариант приследующий подталкивание игроков пробовать другие карты.

2023-05-26 18:56 UTC, volas commented
1 - вместо группы можно по названию dmm определять

2023-05-26 18:58 UTC, volas commented
но группы хз, если с боксом наказывать снежный бокс с уже и так низким весом - его будет сложно пикнуть

2023-05-26 19:18 UTC, Tap0r commented
Разделить голосование за карту и энвиронмент

2023-05-27 11:59 UTC, AndroBetel commented
кто-то готовый ебаться с базами данных пусть делает это

2023-05-27 11:59 UTC, closed without merging

2023-08-05 16:30 UTC, TauKitty commented
Этот запрос на слияние был упомянут в **Tau Ceti Station Forum**. Там могут быть соответствующие подробности:

https://forum.taucetistation.org/t/boxstation/40389/4