теперь можно подглядеть пин-код во время пользования АТМ
TauCetiStation/TauCetiClassic pull request #11430
Opened 2023-05-19 15:29 UTC by AndroBetel

## Описание изменений
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/44546836/89320f16-8b96-4c9e-91cd-1bdf907fe4d1)

## Почему и что этот ПР улучшит
рпшка
## Авторство
я
## Чеинжлог
:cl:
- rscadd: Когда работаете с банкоматом, убедитесь, что вокруг нет мошенников - они могут подсмотреть ваш пин-код!

2023-05-19 15:29 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2023-05-20 00:55 UTC, LudwigVonChesterfield approved these changes

2023-05-20 23:59 UTC, LudwigVonChesterfield commented on code/modules/economy/ATM.dm
> +								to_chat(L, "Вам удаётся подглядеть пин-код: <span class='notice'>[tried_pin]</span>.")
я сейчас подумал и мне не нравится реализация

я думал надо стоять рядом с человеком и экзамайнить (чтобы он тоже знал что ты стараешься подсмотреть).

тебе больше нравится текущая реализация чем экзамайн чем-то?

2023-05-21 09:02 UTC, AndroBetel commented on code/modules/economy/ATM.dm
> +								to_chat(L, "Вам удаётся подглядеть пин-код: <span class='notice'>[tried_pin]</span>.")
не уверен, в какой момент конкретно нужно экзаминить? когда карта вставлена, но не залогинена?

2023-05-21 16:18 UTC, LudwigVonChesterfield commented on code/modules/economy/ATM.dm
> +								to_chat(L, "Вам удаётся подглядеть пин-код: <span class='notice'>[tried_pin]</span>.")
можно и так наверное

2023-05-24 16:17 UTC, LudwigVonChesterfield commented
сошлись на следующей реализации фичи:

1. когда кто-то логинится в банкомат, он пиликает давая всем знать что можно посмотреть
2. если кто-то стоит впритык к этому же банкомату, и осматривает его в пределах 2-ух секунд после пилика, у него есть шанс подсмотреть код.

2023-05-26 18:05 UTC, LudwigVonChesterfield requested changes
ждём пофиксинга

2023-05-27 09:32 UTC, AndroBetel commented
сделал как надо

2023-05-27 14:33 UTC, LudwigVonChesterfield commented on code/modules/economy/ATM.dm
> +						pin_visible_until = world.time
по задумке в переменной должно храниться как долго видно пин код.

то есть тут
```
pin_visible_until = world.time + 2 SECONDS
```

2023-05-27 14:34 UTC, LudwigVonChesterfield commented on code/modules/economy/ATM.dm
> +	pin_visible_until = world.time + 2 SECONDS
а вот тут `pin_visible_until = 0`

2023-05-29 12:21 UTC, AndroBetel commented on code/modules/economy/ATM.dm
> +	pin_visible_until = world.time + 2 SECONDS
пофиксил

2023-05-29 13:53 UTC, LudwigVonChesterfield commented on code/modules/economy/ATM.dm
> +	if(!(src in view(1, user)))
```suggestion
	if(!in_range(src, user))
```

2023-05-29 13:54 UTC, LudwigVonChesterfield commented on code/modules/economy/ATM.dm
> +	if(held_card && world.time < pin_visible_until && prob(50))
```suggestion
	if(held_card && prob(50))
```

2023-05-29 13:54 UTC, LudwigVonChesterfield approved these changes

2023-06-01 17:52 UTC, merged