Небольшой перевод animals
TauCetiStation/TauCetiClassic pull request #11440
Opened 2023-05-21 11:32 UTC by BasiaBelov

## Описание изменений
Перевод речи и описания животных.
Можете спорить много, но мышь не "сквикает", а пищит.
Слаймы, питомцы, животные, халки и разные твари теперь говорят по-русски.
## Почему и что этот ПР улучшит
Понимание. Особенно слаймов.
## Авторство
Me
## Чеинжлог
:cl: Basia
- ru: Переведены описания и речи животных и других некоторых существ.

2023-05-21 11:32 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2023-05-21 11:34 UTC, TryXAH commented
бася вперед

2023-05-21 11:41 UTC, KandreyKandrey commented on code/modules/mob/living/carbon/ian/ian.dm
> +	var/list/emote_see = list("виляет хвостом", "облизываетася")
облизываетася?

2023-05-21 11:42 UTC, BasiaBelov commented on code/modules/mob/living/carbon/ian/ian.dm
> +	var/list/emote_see = list("виляет хвостом", "облизываетася")
Пошло дело...

2023-05-21 11:47 UTC, AndroBetel requested changes

2023-05-21 11:47 UTC, AndroBetel commented on code/modules/mob/living/carbon/metroid/examine.dm
> +				msg += "Слабо мерцает.\n"
почему тут и ниже безличные предложения а выше личные

2023-05-21 11:47 UTC, AndroBetel commented on code/modules/mob/living/simple_animal/bees.dm
> +					to_chat(M, "<span class='warning'>Они жалятся!</span>")
кто жалится? смысл предложения другой без перевода

2023-05-21 11:47 UTC, AndroBetel commented on code/modules/mob/living/simple_animal/constructs.dm
> +	desc = "Хитроумный доспех с клинками, управляемый связанным духом."
wicked это злой, злодейский, а не хитроумный

2023-05-21 11:47 UTC, AndroBetel commented on code/modules/mob/living/simple_animal/constructs.dm
> +	desc = "Луковичная конструкция, предназначенная для создания и поддержания армий Культа Нар-Си."
нормальный перевод bulbous сделать для русского тяжело будет, как-то адаптировать надо

2023-05-21 11:47 UTC, AndroBetel commented on code/modules/mob/living/simple_animal/friendly/cat.dm
> +	desc = "Пушистый кот. Имеет тенденцию умилять экипаж."
adopt crewmembers это, скорее всего, шутка про то, что это не ты кота приручаешь, а кот приручает тебя.

2023-05-21 11:47 UTC, AndroBetel commented on code/modules/mob/living/simple_animal/friendly/cat.dm
> +	desc = "Его шерсть настолько мягкая, что даже появляется сильное желание погладить его."
плохо

2023-05-21 11:47 UTC, AndroBetel commented on code/modules/mob/living/simple_animal/friendly/farm_animals.dm
> +	desc = "Не славятся своим приятным нравом."
приветливый? дружелюбный? козлы в игре типа единственные животные которые тебя могут побить

2023-05-21 11:47 UTC, AndroBetel commented on code/modules/mob/living/simple_animal/friendly/farm_animals.dm
> +			to_chat(user, "<span class='warning'>Вымя сухое. Нужно немного подождать...</span>")
пустое всё-таки будет понятнее.....

2023-05-21 11:47 UTC, AndroBetel commented on code/modules/mob/living/simple_animal/friendly/farm_animals.dm
> +		visible_message("[src] [pick("отклазывает яйца.","садится и напевает.","поднимает шумиху.","начинает хрипло кудахтать.")]")
что напевает нафиг и опечатка

2023-05-21 11:47 UTC, AndroBetel commented on code/modules/mob/living/simple_animal/friendly/farm_animals.dm
> +	desc = "Я гусь, никого не боюсь."
вот бы все описания были адаптированными а не переведенными

2023-05-21 11:47 UTC, AndroBetel commented on code/modules/mob/living/simple_animal/friendly/farm_animals.dm
> +	speak = list("Кря?","Кря","КРЯ!")
реквестирую гагага а не кряканье

2023-05-21 11:47 UTC, AndroBetel commented on code/modules/mob/living/simple_animal/friendly/mouse.dm
> +	desc = "Коту Джерри не нравится он..."
что с построением предложения

2023-05-21 11:47 UTC, AndroBetel commented on code/modules/mob/living/simple_animal/friendly/spiderbot.dm
> +	desc = "Ходячий друг-робот!"
skitter - глагол, употребляющийся к тому, как пауки перемещаются. ползучий мб?

2023-05-21 11:47 UTC, AndroBetel commented on code/modules/mob/living/simple_animal/hostile/bots.dm
> +	desc = "Маленький робот-охранник. Не выглядит таким уж опасным..."
looks less than thrilled - не впечатлен, ему вообще пофиг на всех он закон

2023-05-21 11:47 UTC, AndroBetel commented on code/modules/mob/living/simple_animal/hostile/carp.dm
> +	desc = "Свирепое, обладающее клыками существо, напоминающее рыбу."
клыкастое, зубастое

2023-05-21 11:47 UTC, AndroBetel commented on code/modules/mob/living/simple_animal/hostile/cyber_horror.dm
> +	desc = "Что-то, что было человеком, когда-то..."
"Что-то, что когда-то было человеком"

2023-05-21 11:47 UTC, AndroBetel commented on code/modules/mob/living/simple_animal/hostile/giant_spider.dm
> +	desc = "Э ДЖАЕНТ ЭНЭМИ СПАЙДЭР!"
😔

2023-05-21 11:47 UTC, AndroBetel commented on code/modules/mob/living/simple_animal/hostile/hivebot.dm
> +	desc = "Кажется, оно хочет кого-то убить..."
все мне дальше лень ревьювить

2023-05-21 11:48 UTC, KandreyKandrey commented on code/modules/mob/living/carbon/xenomorph/special/facehugger/facehugger_playable.dm
> +	desc = "На конце хвоста есть какая-то трубочка.."
зачем вторая точка

2023-05-21 11:51 UTC, BasiaBelov commented on code/modules/mob/living/simple_animal/hostile/giant_spider.dm
> +	desc = "Э ДЖАЕНТ ЭНЭМИ СПАЙДЭР!"
А ой, забыл нормально сделать

2023-05-21 11:51 UTC, KandreyKandrey commented on code/modules/mob/living/simple_animal/borer.dm
> +	speak_emote = list("щипит")
"щипит", "пищит", или "шипит" ?

2023-05-21 11:53 UTC, BasiaBelov commented on code/modules/mob/living/simple_animal/bees.dm
> +					to_chat(M, "<span class='warning'>Они жалятся!</span>")
Даже перефразировать нельзя, да?

2023-05-21 11:58 UTC, BasiaBelov commented on code/modules/mob/living/simple_animal/borer.dm
> +	speak_emote = list("щипит")
Балин, ненавижу Щ и Ш. Они верно рядом и отличаются мало...

2023-05-21 11:59 UTC, KandreyKandrey commented on code/modules/mob/living/simple_animal/friendly/corgi.dm
> +	emote_see = list("виляет хвостом", "облизываетася")
облизываетася

2023-05-21 12:00 UTC, BasiaBelov commented on code/modules/mob/living/simple_animal/friendly/corgi.dm
> +	emote_see = list("виляет хвостом", "облизываетася")
Я тот отметил решёным, потому что исправил это у себя.

2023-05-21 12:02 UTC, KandreyKandrey commented on code/modules/mob/living/simple_animal/friendly/corgi.dm
> +	emote_see = list("виляет хвостом", "облизываетася")
это другой файл уже

2023-05-21 12:05 UTC, BasiaBelov commented on code/modules/mob/living/simple_animal/hostile/hivebot.dm
> +	desc = "Кажется, оно хочет кого-то убить..."
Ну что тута не так?
Адаптировал.
Оно точно хочет убить тебя. Не выглядит оно добрым.

2023-05-21 12:07 UTC, BasiaBelov commented on code/modules/mob/living/simple_animal/hostile/bots.dm
> +	desc = "Маленький робот-охранник. Не выглядит таким уж опасным..."
Так уж и быть...
Давай идти строго по пути буква в букву, это же так важно.

2023-05-21 12:09 UTC, KandreyKandrey commented on code/modules/mob/living/simple_animal/friendly/farm_animals.dm
> +	speak_emote = list("курлыкает")
"курлыкает" или "курлычет"  ?

2023-05-21 12:11 UTC, BasiaBelov commented on code/modules/mob/living/simple_animal/friendly/farm_animals.dm
> +	desc = "Я гусь, никого не боюсь."
Ладно.

2023-05-21 12:17 UTC, KandreyKandrey commented on code/modules/mob/living/simple_animal/friendly/mouse.dm
> +	desc = "Это маленький, пораженный болезнями грызун."
где "ё"

2023-05-21 12:19 UTC, KandreyKandrey commented on code/modules/mob/living/simple_animal/friendly/pug.dm
> +	emote_see = list("виляет хвостом", "облизываетася")
облизываетася (или ты уже везде поправил?)

2023-05-21 12:19 UTC, BasiaBelov commented on code/modules/mob/living/simple_animal/friendly/pug.dm
> +	emote_see = list("виляет хвостом", "облизываетася")
Поправил

2023-05-21 12:29 UTC, BasiaBelov commented on code/modules/mob/living/simple_animal/friendly/cat.dm
> +	desc = "Пушистый кот. Имеет тенденцию умилять экипаж."
Одомашненный кот. Имеет тенденцию приручать экипаж.

2023-05-21 12:31 UTC, KandreyKandrey commented on code/modules/mob/living/simple_animal/hostile/faithless.dm
> +	desc = "Воплощенная вера Исполнителя желаний, воплоти."
что "воплоти"  ?

2023-05-21 12:33 UTC, KandreyKandrey commented on code/modules/mob/living/simple_animal/hostile/hivebot.dm
> +	desc = "Какая-то странная штука с мачком."
мб "маячком" ?

2023-05-21 12:34 UTC, BasiaBelov commented on code/modules/mob/living/simple_animal/hostile/hivebot.dm
> +	desc = "Кажется, оно хочет кого-то убить..."
А ещё, оно не выглядит маленьким роботом.

2023-05-21 12:37 UTC, KandreyKandrey commented on code/modules/mob/living/simple_animal/vox.dm
> +	desc = "Одноглазое, пернатое существо. Полумашина, легко достигающее девяти футов от хвоста до клюва!"
"легко достигающая" ?

2023-05-21 12:49 UTC, BasiaBelov commented
Тыак... И стаётся лишь первые три адаптировать...

2023-05-21 12:54 UTC, KandreyKandrey commented on code/modules/mob/living/simple_animal/friendly/farm_animals.dm
> +		visible_message("[src] [pick("отклазывает яйца.","поднимает шумиху.","начинает хрипло кудахтать.")]")
"отклазывает"

2023-05-21 12:55 UTC, KandreyKandrey commented on code/modules/mob/living/simple_animal/friendly/farm_animals.dm
> +		visible_message("[src] [pick("отклазывает яйца.","поднимает шумиху.","начинает хрипло кудахтать.")]")
и "яйца" или "яйцо" ?

2023-05-23 04:58 UTC, BasiaBelov commented on code/modules/mob/living/simple_animal/constructs.dm
> +	desc = "Луковичная конструкция, предназначенная для создания и поддержания армий Культа Нар-Си."
Круглая структура, предназначенная для создания и поддержания армий Культа Нар-Си. (?)

2023-05-23 10:07 UTC, KIBORG04 commented on code/modules/mob/living/simple_animal/constructs.dm
> +	desc = "Луковичная конструкция, предназначенная для создания и поддержания армий Культа Нар-Си."
Луковичная структура ??????? Ну можно че-то свое придумать, эти описания мало кто читает и помнит

2023-05-23 16:29 UTC, LudwigVonChesterfield commented on code/modules/mob/living/carbon/metroid/life.dm
> +		if ((findtext(phrase, num2text(number)) || findtext(phrase, "slime") || findtext(phrase, "слайм") || findtext(phrase, "легион") || findtext(phrase, "слаймы"))) // Talking to us
предлагаю удалить английские версии фраз,

не рекомендую добвалять вариации потому-что сейчас каждый слайм проходится по каждому сообщению в чат с поиском каждого слова что ты тут добавишь. оставь просто "слайм"

2023-05-23 19:47 UTC, KIBORG04 commented on code/modules/mob/living/carbon/metroid/examine.dm
> +				msg += "<B>У него серьезные проколы и разрывы в его теле.</B>"
```suggestion
				msg += "<B>У него серьезные проколы и разрывы в теле.</B>"
```

2023-05-23 19:49 UTC, KIBORG04 commented on code/modules/mob/living/carbon/metroid/life.dm
> +								to_say = pick("Я уничтожу [last_pointed]...", "Убить...", "Убить [last_pointed]...", "Злодей...", "Есть...", "Да...")
Мне кажется, варианты без написанного названия цели полная хрень. Игрок не получит конкретного фидбека, что слаймы поняли кого убить

2023-05-23 19:53 UTC, KIBORG04 commented on code/modules/mob/living/simple_animal/bees.dm
> +			visible_message("<span class='notice'>[pick("Жжжжжжжжжж.","Жжжжжжжж.","Жжжжжжжжж.")]</span>")
Жжжжжжж

2023-05-23 19:53 UTC, KIBORG04 commented on code/modules/mob/living/simple_animal/constructs.dm
> +	desc = "Какой-то странный робот."
Я не понимаю почему игроки называют конструктов боргами, но они же нихрена не из метелла сделаны, скорее из камня. Я против роботов крч

2023-05-23 19:57 UTC, KIBORG04 commented on code/modules/mob/living/simple_animal/constructs.dm
> +	desc = "Летающий кристалл, излучающий неземную энергию."
```suggestion
	desc = "Летающий кристалл, излучающий таинственную энергию."
```
неземную как-то странно звучит в контексте, что земля по лору является помойкой

2023-05-23 20:01 UTC, KIBORG04 commented on code/modules/mob/living/simple_animal/friendly/farm_animals.dm
> +	speak = list("Кулюк?","Кулюк","КУЛЮК")
Кулюк? Они же вроде курлык-курлык

2023-05-23 20:02 UTC, KIBORG04 commented on code/modules/mob/living/simple_animal/friendly/fox.dm
> +	desc = "Это лиса. Интересно, что она говорит?"
> I wonder what it says?

Это откуда-то из английского фольклёра?

2023-05-23 20:04 UTC, KIBORG04 commented on code/modules/mob/living/simple_animal/friendly/mouse.dm
> +	desc = "Это маленький грызун, которого часто можно увидеть прячущимся в техтоннелях."
```suggestion
	desc = "Это маленький грызун, которого часто можно увидеть, прячущимся в тех. туннелях."
```

2023-05-23 20:10 UTC, KIBORG04 commented on code/modules/mob/living/simple_animal/hostile/carp.dm
> +	desc = "Свирепое, клыкастое существо, напоминающее акулу. Кажется, оно ещё опасней..."
```suggestion
	desc = "Свирепое и клыкастое существо, напоминающее акулу. Кажется, оно очень опасное..."
```
Так вроде легче читается и "ещё" непонятно к чему отсылает

2023-05-23 20:11 UTC, KIBORG04 commented on code/modules/mob/living/simple_animal/hostile/carp.dm
> +	desc = "Свирепое, клыкастое существо, напоминающее рыбу. Выглядит довольно странно."
```suggestion
	desc = "Свирепое и клыкастое существо, напоминающее рыбу. Выглядит довольно странно."
```
Так вроде легче читается

2023-05-23 20:13 UTC, KIBORG04 commented on code/modules/mob/living/simple_animal/hostile/mimic.dm
> +	desc = "Абсолютно не клювовидный и безвредный. Держать подальше от трупов."
Какой клювовидный

2023-05-23 20:13 UTC, KIBORG04 commented on code/modules/mob/living/simple_animal/hostile/mimic.dm
> +	desc = "Абсолютно не клювовидный и безвредный. Держать подальше от трупов."
Начало какое-то странное

2023-05-23 20:13 UTC, KIBORG04 commented on code/modules/mob/living/simple_animal/hostile/syndicate.dm
> +	desc = "Небольшая машина с двумя лезвиями, способная наносить очень смертельные раны."
Очень смертельные. Это как?

2023-05-23 20:15 UTC, KIBORG04 commented on code/modules/mob/living/simple_animal/hulk_powers.dm
> +	desc = "МЕГАШУТНИК!"
```suggestion
	desc = "МЕГАШУТКА!"
```
Это не моб, а спелл

2023-05-23 20:15 UTC, KIBORG04 commented on code/modules/mob/living/simple_animal/parrot.dm
> +	desc = "Обречён кричать на землю."
В чем шутка

2023-05-24 04:19 UTC, BasiaBelov commented on code/modules/mob/living/simple_animal/hulk_powers.dm
> +	desc = "МЕГАШУТНИК!"
А ой, тогда вообще надо убрать

2023-05-24 04:21 UTC, BasiaBelov commented on code/modules/mob/living/simple_animal/hostile/syndicate.dm
> +	desc = "Небольшая машина с двумя лезвиями, способная наносить очень смертельные раны."
Ну типа знаешь, веры перерезать - это не очень смертельные раны, а вот проткнуть голову - это очень.

*Ладно, исправлю...*

2023-05-24 04:23 UTC, BasiaBelov commented on code/modules/mob/living/carbon/metroid/life.dm
> +		if ((findtext(phrase, num2text(number)) || findtext(phrase, "slime") || findtext(phrase, "слайм") || findtext(phrase, "легион") || findtext(phrase, "слаймы"))) // Talking to us
Я проверил, они и так будут отзываться на **слайм**ы

2023-05-24 05:08 UTC, BasiaBelov commented on code/modules/mob/living/simple_animal/friendly/fox.dm
> +	desc = "Это лиса. Интересно, что она говорит?"
Песенка мемная была.
What the fox say?

2023-05-25 19:05 UTC, Fenriros commented on code/modules/mob/living/carbon/metroid/examine.dm
> +		msg += "<span class='deadsay'>Он вялый и не реагирует.</span>\n"
может
```suggestion
		msg += "<span class='deadsay'>Он размяк и не реагирует.</span>\n"
```

2023-05-25 23:34 UTC, Fenriros commented on code/modules/mob/living/simple_animal/hostile/bots.dm
> +	desc = "Маленький робот-охранник. Не впечатлен, ему вообще пофиг на всех, он закон."
а зачем здесь не впечатлён?

2023-05-25 23:34 UTC, Fenriros commented on code/modules/mob/living/simple_animal/hostile/carp.dm
> +	name = "Мега карп!"
а зачем здесь восклицательный знак?

2023-05-25 23:34 UTC, Fenriros commented on code/modules/mob/living/simple_animal/friendly/tomato.dm
> +	desc = "Ужасающе огромный помидор!"
```suggestion
	desc = "Ужасающе огромный помидор, ты точно найдёшь в нём бычье сердце!"
```
[Это такой большой томат](https://ru.wikipedia.org/wiki/%D0%91%D1%8B%D1%87%D1%8C%D0%B5_%D1%81%D0%B5%D1%80%D0%B4%D1%86%D0%B5_(%D1%82%D0%BE%D0%BC%D0%B0%D1%82))

2023-05-25 23:34 UTC, Fenriros commented on code/modules/mob/living/simple_animal/hostile/hostile.dm
> +		to_chat(user, "<span class='warning'>Похоже, немного побит.</span>")
wounded это больше про ранения
Кажется, он сильно ранен и тп.
но думаю это не критично

2023-05-25 23:34 UTC, Fenriros commented on code/modules/mob/living/simple_animal/hostile/tree.dm
> +	desc = "Бешеная деревяшка. Странное существо..."
```suggestion
	desc = "Бешеная деревяшка. Похоже ему надоели новогодние праздники..."
```

2023-05-25 23:34 UTC, Fenriros commented on code/modules/mob/living/simple_animal/hulk.dm
> +	emote_hear = list("кричит")
roar - рёв, рык
даже в фильмах он орёт и рычит
```suggestion
	speak_emote = list("рычит")
	emote_hear = list("рычит")
```

2023-05-25 23:34 UTC, Fenriros commented on code/modules/mob/living/simple_animal/hulk.dm
> +	to_chat(src, "<span class='notice'>Вы можете есть конечности (Левый кнопка мыши).</span>")
```suggestion
	to_chat(src, "<span class='notice'>Вы можете есть конечности (Левой кнопкой мыши).</span>")
```
```suggestion
	to_chat(src, "<span class='notice'>Вы можете есть конечности (Левая кнопка мыши).</span>")
```

2023-05-25 23:34 UTC, Fenriros commented on code/modules/mob/living/simple_animal/hulk.dm
>  		"<span class='userdanger'>You feel some weird vibration!</span>")
а почему это не перевёл?

2023-05-26 06:03 UTC, BasiaBelov commented on code/modules/mob/living/simple_animal/hulk.dm
>  		"<span class='userdanger'>You feel some weird vibration!</span>")
Моей целью был перевод описаний, речи и эмоутов.
"МЕГАШУТКА" я перевёл по ошибке, но пускай останется.

2023-05-26 06:08 UTC, BasiaBelov commented on code/modules/mob/living/simple_animal/hostile/bots.dm
> +	desc = "Маленький робот-охранник. Не впечатлен, ему вообще пофиг на всех, он закон."
Мой первый вариант с переводом
`Маленький робот-охранник. Выглядит не очень опасным.`
Бетель сказал переделать на это, потому что... потому что что?
Мне сказали - я исправил.

2023-05-26 06:11 UTC, BasiaBelov commented on code/modules/mob/living/simple_animal/friendly/cat.dm
> +	desc = "Его шерсть на вид и ощупь напоминает бархат."
`...а хвост немного подрагивает.`
Посчитал, что звучит такое предложение, как минимум, странно...

2023-05-26 06:13 UTC, BasiaBelov commented on code/modules/mob/living/simple_animal/hostile/carp.dm
> +	name = "Мега карп!"
Это вообще лишнее.
Надо вернуть как было...

2023-05-26 18:51 UTC, BasiaBelov commented
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/115452414/5e3a681a-47fa-498b-a7b3-19024a33d522)
Каво...

2023-05-27 03:28 UTC, LudwigVonChesterfield commented
и ты и кто-то другой меняли один и тот же файлик на одних и тех же строках и произошёл конфликт изменений.

спроси в #how-to-code Дискорда как решить, тебе помогут.

2023-05-27 08:52 UTC, BasiaBelov commented
Балин, не вышло...

2023-05-30 13:35 UTC, BasiaBelov commented
Аёу... Да?

2023-06-02 09:26 UTC, BartNixon requested changes
Не утверждаю что прям всё нужно исправить, но стоит максимально избежать "кальки" с английского при переводе. Многие описания имеют контекстное или культурное значение, которое также нужно соответственным образом интерпретировать, и местами осознанно менять под структуры речи русского языка.

2023-06-02 09:26 UTC, BartNixon commented on code/modules/mob/living/simple_animal/friendly/farm_animals.dm
> +	desc = "Известны своим молоком. Только не роняйте их."
Могу понять фразу "повалить" или "свалить" корову, а вот "уронить" корову возможно пожалуй с вертолёта, или из разряда древней байки о Петровиче и Михалыче которые в деревушке Приморского края украли корову, запихнув её в АН-2 "Кукурузник" перед вылетом на Сахалин, а корова в панике спрыгнула с километровой высоты над морем и упала прямиком на японскую рыболовецкую лодку после чего чудом выживших японских рыбаков арестовали офигевшие пограничники.

2023-06-02 09:26 UTC, BartNixon commented on code/modules/mob/living/simple_animal/friendly/mouse.dm
> +	desc = "Это маленький, поражённый болезнями грызун."
Это маленький грызун - переносчик опасных заболеваний.

2023-06-02 09:26 UTC, BartNixon commented on code/modules/mob/living/simple_animal/friendly/mouse.dm
> +	desc = "Это маленький, поражённый болезнями грызун."
Это маленький грызун - переносчик опасных заболеваний.

2023-06-02 09:26 UTC, BartNixon commented on code/modules/mob/living/simple_animal/hostile/creature.dm
> +	desc = "Разрушающее здравомыслие... что-то."
Разрушающее здравомыслие... Нечто.

2023-06-02 09:26 UTC, BartNixon commented on code/modules/mob/living/simple_animal/hostile/mimic.dm
> +	desc = "Абсолютно не безобидный и не без клюва. Держать подальше от трупов."
Абсолютно не безобидный и скорее всего очень кусючий. Держать подальше от трупов.

2023-06-02 09:26 UTC, BartNixon commented on code/modules/mob/living/simple_animal/hostile/mimic.dm
> +	desc = "Абсолютно не безобидный и не без клюва. Держать подальше от трупов."
"Absolutely not de-beaked or harmless." это отсылка на диалог Доктора Кляйнера из Half-Life 2 про ручного хедкраба.
https://www.youtube.com/watch?v=SXm0wTZrbNE

В переводе эта отсылка целиком теряется, так что лучше придумать другую шутку на тему.
Может вспомнится что-то из старых или новых мультиков или других известных игр с русской озвучкой?

2023-06-02 09:26 UTC, BartNixon commented on code/modules/mob/living/simple_animal/hostile/tree.dm
> +	desc = "Бешеная деревяшка. Похоже ему надоели новогодние праздники..."
Взбешённая, древоподобная инопланетная сущность. Новогодние праздники явно не пошли на пользу её сородичам...

2023-06-02 09:26 UTC, BartNixon commented on code/modules/mob/living/simple_animal/special/scp.dm
> +	desc = "Какая-то скульптура размером с человека, похожая на куклу, со странными пятнами на некоторых частях. Выглядит вполне солидно."
Какая-то скульптура в человеческий рост, похожая на куклу, со странными пятнами на некоторых частях. Выглядит нерушимо и безмятежно.

2023-06-02 09:26 UTC, BartNixon commented on code/modules/mob/living/simple_animal/special/scp.dm
> +	desc = "Какая-то скульптура размером с человека, похожая на куклу, со странными пятнами на некоторых частях. Выглядит вполне солидно."
Тут речь была не о том что скульптура "солдиная" а solid в значении "твёрдый как бетон", "монолитный", "неподивжный как статуя".

2023-06-02 09:28 UTC, BartNixon commented on code/modules/mob/living/simple_animal/hostile/creature.dm
> +	desc = "Разрушающее здравомыслие... что-то."
или

Нечто, разрушающее рассудок.

2023-06-02 21:34 UTC, Fenriros commented on code/modules/mob/living/simple_animal/hostile/bots.dm
> +	desc = "Маленький робот-охранник. Не впечатлен, ему вообще пофиг на всех, он закон."
А что если
```suggestion
	desc = "Маленький робот-охранник. Похоже, он не в восторге увидев вас."
```

2023-06-05 07:50 UTC, BasiaBelov commented on code/modules/mob/living/simple_animal/friendly/mouse.dm
> +	desc = "Это маленький, поражённый болезнями грызун."
Нет. Дефис тут точно лишний.

2023-06-05 07:58 UTC, BasiaBelov commented
Ура ура ура ура! Всё, оно сделано! Ура ура ура ура!

2023-06-13 19:00 UTC, merged