удаляет дереликт выживач
TauCetiStation/TauCetiClassic pull request #11452
Opened 2023-05-24 22:46 UTC by AndroBetel

## Описание изменений
![doc_2023-05-25_01-42-08](https://github.com/TauCetiStation/TauCetiClassic/assets/44546836/3fa8eb63-6931-4012-9ce2-5b0165e54f22)

заявленного выживача на станции нет, алиены вырезаются за 5 минут, потом ебало в доспехах и с арсеналом оружия летит на станцию и в раунде появляется рандомный чел с пушками, к которому непонятно как относиться и с админской стороны, и с игровой

поэтому я считаю что до полного реворка лучше выпилить. выпиливаю полностью, если надо - могу удалить из шаблонов дереликтов

## Почему и что этот ПР улучшит
качество жизни африканских детей на тау кита
## Авторство

## Чеинжлог
:cl:
- rscdel: Удаляет дереликт выживач.

2023-05-24 22:46 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2023-05-25 02:45 UTC, LudwigVonChesterfield commented
предлагаю вместо выпила контента выпилить админов

остальные проблемы (рандомный чел с пушками) думаю меньшие чем тот контент что привносит дереликт-выживач

2023-05-25 19:44 UTC, ViDLiathan commented
Вставьте импланты лояльности выжившим

2023-05-26 17:25 UTC, LudwigVonChesterfield requested changes
я против выпила.

простых но костыльных фиксов достаточно чтобы быстренько пофиксить а не выпилить:
- убрать все риги, дать скафандры космические
- сделать какую-то огорожу которую надо отключать
- влепить импланты лояльности (лол почему лояльны НТ если другая корпорация но да ладно)

2023-05-27 11:59 UTC, AndroBetel commented
лан похуй

2023-05-27 11:59 UTC, closed without merging