негативная особка
TauCetiStation/TauCetiClassic pull request #11453
Opened 2023-05-25 10:56 UTC by AndroBetel

## Описание изменений
недавно вон кравл стал инструментом в арсенале робастера...
## Почему и что этот ПР улучшит

## Авторство

## Чеинжлог

2023-05-25 10:56 UTC, TauKitty commented
###### Changelog status: :radio_button: No changelog

2023-05-25 11:02 UTC, KIBORG04 commented
Запрет впринципе лежать?

2023-05-25 11:04 UTC, AndroBetel commented
кравл прожать нельзя, а толкнуть-то тебя на пол могут...

2023-05-25 11:05 UTC, KIBORG04 commented
Ну, добровольно нельзя лечь

2023-05-25 11:06 UTC, AndroBetel commented
да!

2023-05-25 13:38 UTC, LudwigVonChesterfield commented on code/modules/mob/living/living.dm
> +		to_chat(usr, "<span class='warning'>Нет! ПОЛ ГРЯЗНЫЙ!</span>")
а если хочется встать..

2023-05-26 17:26 UTC, LudwigVonChesterfield requested changes
мне кажется если по какой-либо причине упасть то потом не встанешь с текущей реализацией.

пока это не проверят мержить низя..

2023-05-26 17:47 UTC, AndroBetel commented
совершил пофиксинг

2023-05-26 17:58 UTC, LudwigVonChesterfield approved these changes

2023-05-27 16:34 UTC, merged