Космонавты вновь грустят от одиночества
TauCetiStation/TauCetiClassic pull request #11464
Opened 2023-05-26 18:16 UTC by NinjaPikachuska

## Описание изменений
fixes #11463
## Почему и что этот ПР улучшит

## Авторство

## Чеинжлог
:cl:
 - bugfix: Грусть от одиночества вернулась.

2023-05-26 18:16 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2023-05-26 18:17 UTC, LudwigVonChesterfield approved these changes
могут вылезти проблемы при смене расы/навешивании мута, но я их пока не обнаружил.

2023-05-26 18:43 UTC, TryXAH commented
А давайте не надо
Как минимум, пока ксенобиологу не засчитывается разговор с слаймами, а вирусологу с мартышками

2023-05-26 18:46 UTC, Deahaka commented
> А давайте не надо Как минимум, пока ксенобиологу не засчитывается разговор с слаймами, а вирусологу с мартышками

Как же он в неведении

2023-05-27 10:43 UTC, arygal commented
Опять. Снова. Надоело.
Была уже эта хрень - людям не понравилось, но всё равно ушло в [мердж](https://github.com/TauCetiStation/TauCetiClassic/pull/8605). 
Последнее время с учётом таких классных ПРов на некоторых профах играть стало уныло. Тот же шахтёр - на ЦК не покормили и ни с кем не поговорить - наслаждайся замедлением и фильтром цвета мочи в глазах.
И это касается не только шахтёров - химики, инженегры, учёные и атмосферники. Любая профа которая должна выполнить работу в начале смены и как можно быстрее - внерфлена кодерами.
Вместо того чтобы давать позитивный фидбек от действий куклы - у нас в основном негатив.

2023-05-27 10:56 UTC, AndroBetel commented
> людям не понравилось, но всё равно ушло в https://github.com/TauCetiStation/TauCetiClassic/pull/8605.
> 6 лайков 8 дизлайков

ебало автора смски представили?

2023-05-27 11:02 UTC, Deahaka commented
> Тот же шахтёр - на ЦК не покормили и ни с кем не поговорить - наслаждайся замедлением и фильтром цвета мочи в глазах. И это касается не только шахтёров - химики, инженегры, учёные и атмосферники.

Лучше б аппелировал к лоупопу, но на онлайне где есть хотя бы один напарник это штрафует за анти-социальность. Может "увы", но это цель существования системы настроения и если ты хочешь убрать подобные механики то надо топить за полное удаление муда.

2023-05-27 11:11 UTC, arygal commented
> Лучше б аппелировал к лоупопу, но на онлайне где есть хотя бы один напарник это штрафует за анти-социальность. Может "увы", но это цель существования системы настроения и если ты хочешь убрать подобные механики то надо топить за полное удаление муда.

Там были бафы муда за разговоры - до того как было пропихнуто это... Опциональный бафф муда не равен дебаффу который хотят протолкнуть.

2023-05-27 12:05 UTC, Deahaka commented
Пока никто не ставил рамок в которых надо держаться при создании системы мотивирования к тому для чего муд нужен. Ну и обсуждать багфикс, если только это не рекурсивные взрывы, бессмысленно

2023-05-27 14:16 UTC, LudwigVonChesterfield commented
кстати говорить не обязательно с хуманами, достаточно чтобы в мобе был клиент(игрок).

я изначально хотел чтобы можно было говорить и с животинками типо Яна, даже если игрока нет, но меня попросили почему-то так не делать, а теперь тут жалобы что говорить не с кем в игре на 70 онлайна... хз.

2023-05-27 18:50 UTC, LudwigVonChesterfield commented
а они не проверяются на TRAIT_MUTE?

2023-05-27 23:52 UTC, LudwigVonChesterfield commented
https://github.com/TauCetiStation/TauCetiClassic/pull/11464/files#diff-b505dab1cf5c88d56ff1a2772ebbe0c5c0ac7096ee0ff3a07cd499a8429e5c8eR62

мне кажется тут что-то напутано.

сейчас если ты поговорил 4 минуты назад, и поговоришь ещё раз, то через 1 минуту ты все равно загрустишь, потому-что таймер не сбросится, хотя должен был бы.

2023-05-28 14:12 UTC, LudwigVonChesterfield commented on code/modules/mob/emote.dm
> +	if(!ishuman(src))
так, проблема один, это можно сделать по-другому

```
/mob/living/carbon/human/me_emote(
    . = ..()
    if(!miming && !HAS_TRAIT())
       блаблабла
```

проблема два, я понимаю что это сделано чтобы к примеру крик не сбрасывал одиночество... но как-то странно что всякие *laugh *nod не работают... хз, может я не прав и пох.

2023-05-28 14:14 UTC, LudwigVonChesterfield commented on code/modules/mob/emote.dm
> +		H.handle_socialization(M)
вместо того чтобы это обрабатывать тут сделай функцию типо

```
/mob/proc/hear_emote(mob/source, emote)
    if(!client)
        return
    if(ishuman(source))
        var/mob/living/carbon/human/H = source
        H.handle_socialization(src)
        return
    to_chat(src, emote)
```

2023-05-28 14:14 UTC, LudwigVonChesterfield commented on code/modules/mob/hear_say.dm
> +		H.handle_socialization(src)
сейчас проебался проверка на потерю сознания, и на наличие клиента

2023-05-28 14:15 UTC, LudwigVonChesterfield commented on code/modules/mob/hear_say.dm
> +		H.handle_socialization(src)
(и в чем кстати смысл переноса? раньше красивее выглядело имхо...)

2023-05-28 14:16 UTC, LudwigVonChesterfield commented on code/modules/mob/living/carbon/human/say.dm
> +	if(!ishuman(hearer))
вот эта проверка не нужна. по задумке с осознанными животными (условно Ян с игроком) можно разговаривать...

2023-05-28 14:18 UTC, LudwigVonChesterfield commented
Тесты показали что таймер глубокого одиночества стоит увеличить чтобы оно набрасывалось через минут 20 без собеседника.

Ещё в связи с появлением некоторых поодиноких ролей, к примеру лон опса, или чувака на аванпосте прослушки думаю надо добавить какой-то TRAIT_LONER который тоже блокирует этот механ и выдавать его им.

2023-05-28 14:31 UTC, LudwigVonChesterfield commented
По поводу шахтёров я бы предложил или тоже дать им TRAIT_LONER, или дать им особый механ что они могут довольствоваться разговорами по радио.

( к примеру специальный наушник который такое позволяет )

2023-05-28 15:07 UTC, LudwigVonChesterfield commented on code/modules/mob/emote.dm
> +	for(var/mob/M in (viewers(get_turf(src), world.view)))
С одной стороны, я бы предпочёл иметь меньше циклов по всем мобам вокруг.

С другой стороны уже литерали точно так же сделано для рунчата...

2023-05-28 16:05 UTC, LudwigVonChesterfield requested changes
нужно доделать:
- выдавать TRAIT_LONER лонопсу, оператору прослушки
- сделать особые развлекательные наушники у шахтеров (взять спрайт наушника БЩ) по которым когда говоришь то считается будто говоришь с кем-то рядом
- эмоуты которые изрыгивает игрок осознанно типо *laugh если он немой должны считаться за социализацию на уровне с *me
- нужно упразднить viewers() в цикле раздачи социализации от эмоута. я в Дискорде расписывал как это можно сделать

2023-05-29 17:32 UTC, pro100kotah commented
Блять, обсуждали же раньше. Зачем вы пытаетесь воткнуть игроку обоссанный экран в качестве наказания за соло игру без коммуникации. Существует не только метод кнута. но и пряника.
Куда проще давать бафф муда, как раз за общение. Чтобы он был мизерным, все еще являлся приятным. Мытье в душе, хождение в толкан и т.д. Все это дает бафф и люди этим пользуются.
Эффект и полезность ПРа будет куда больше, если вместо наказания игроки будут получать пощрение за исполнение требуемых действий.

2023-05-29 18:32 UTC, LudwigVonChesterfield commented
Реализовать награду за общение не получилось, было очень тупо что за поливание друг друга матом люди радовались, и могли общаться с абдукторами.

2023-05-29 21:19 UTC, arygal commented
> Реализовать награду за общение не получилось, было очень тупо что за поливание друг друга матом люди радовались, и могли общаться с абдукторами.

Ну может тогда вырезать, а не навязывать свой геймплей другим игрокам? Оно вообще не нужно.

2023-05-30 12:14 UTC, SkLepP commented
Согласен. Кому-то интереснее играть стало от мочевого фильтра и замедления? Когда кому-то грустно вдруг моментально должны отказывать мышцы, что он сразу становится медленнее? Это более бредово, чем получать хорошее настроение от ругательств. Тем более это субъективно. Кому-то это даже будет смешно.

2023-06-04 08:53 UTC, Tolerantboy commented
Если такое и делать, то в виде квирка, типа «Экстраверт», который имеет этот самый дебаф если долго ни с кем не говорить. Для остальных это не нужно

2023-06-07 20:12 UTC, LudwigVonChesterfield approved these changes
мне реально нравится пр

2023-06-07 22:07 UTC, NikMaestro commented
Отличный пример того, что некоторым багам лучше навсегда остаться фичей.

Почему вообще специально обученные люди, что были готовы встретиться лицом к лицу с бескрайним и одиноким космосом ноют, что им не хватает общения??? Я не понимаю

2023-06-08 15:07 UTC, Ro2tCrab commented
> мне реально нравится пр

А как показывает форум - остальным данный ПР не понравился.

Ни один воут не в пользу ПР'а.

2023-06-08 15:53 UTC, Ro2tCrab commented
> Я и не ожидал что игрокам будет нравиться дополнительное ограничение.

Ты не понял.
Все *настолько* все плохо.
Один игрок уже собирают конфу против ПР'а.
А я вот думаю сразу же кинуть в Пулл ревёрт на основе голосования.

2023-06-08 15:56 UTC, Mercurialaste commented
блин, сообщество против фикса багов...

2023-06-08 18:38 UTC, LudwigVonChesterfield commented
Интересно можно ли сделать чтобы пока без сознания/спишь время не считалось...

2023-06-08 18:58 UTC, Tolerantboy commented
> блин, сообщество против фикса багов...

Потому, что фича, которая хуже бага.

2023-06-08 20:38 UTC, LudwigVonChesterfield commented
@NinjaPikachuska спрайт наушника некрасивый откровенно

заюзай пожалуйста тот который у БЩ, а БЩ дай дефолтный как у всех

2023-06-15 16:28 UTC, Ro2tCrab commented
Если мне не показалось, то онлайн Тау Киты резко так упал после этого ПР'а где-то на 30%

И это немного.. много.

2023-06-16 20:37 UTC, LudwigVonChesterfield commented
> Интересно можно ли сделать чтобы пока без сознания/спишь время не считалось...

Если это реализовать то можно мержить.

Сейчас если ты на условной операции или отошёл от игры - потом прилетаешь а у тебя красный экран незаслужено.

2023-06-17 17:22 UTC, LudwigVonChesterfield commented on code/modules/mob/living/carbon/human/say.dm
> +	if(stat == UNCONSCIOUS && timer)
лучше не так, а то посмретно будет одиноко...

надо заменить на stat != CONSCIOUS

2023-06-17 17:23 UTC, LudwigVonChesterfield commented on code/modules/mob/living/carbon/human/say.dm
> +	var/datum/timedevent/timer = SStimer.timer_id_dict["timerid[conversation_timer]"]
это точно надо так делать? это точно работает если игроков несколько?...

я конечно запущу на сервак посмотрим или что-то сломается но выглядит не очень

2023-06-17 17:48 UTC, LudwigVonChesterfield commented
Можно добавить требование к количеству символов перед снятием мудлета? Типо надо написать 10 символов (не за минуту, не за раз) а суммарно чтобы забрать

2023-06-17 21:27 UTC, LudwigVonChesterfield commented on code/modules/mob/living/carbon/human/say.dm
> +	var/datum/timedevent/timer = SStimer.timer_id_dict["timerid[conversation_timer]"]
очень низкоуровневый код среди высокоуровневого. точно нет какого-то get_timer() или что-то такое?

2023-06-19 13:22 UTC, volas requested changes
дизлайки бесполезны, так как формально это фикс неработающей механики, а не что-то новое. Но можете воспользоваться фидбеком в рамках отдельного ПР-а.

2023-06-19 13:22 UTC, volas commented on code/modules/mob/emote.dm
> +	var/viewers = message_type & SHOWMSG_VISUAL ? viewers(get_turf(src), world.view) : hearers(get_turf(src), world.view)
можно было бы просто сделать мимов и немых иммунными к одиночеству. Не будет лишнего опроса окрестных мобов, да и visible_message/audible_message работают сложнее и точнее, чем просто viewers/hearers.

Или можно обновить show_message, добавить поддержку трейтов сообщения кроме типов отдельным битфилдом (можно наверно использовать последний нечетный аргумент, это проклято но как минимум останется обратная совместимость и простота прока), и добавить сообщениям битфлаг "сбрасывает одиночество"... или переделать уже сообщения на датумы.

2023-06-19 13:22 UTC, volas commented on code/modules/mob/living/carbon/human/say.dm
> +				10 MINUTES,
10 минут по меркам игры мало, хотя бы 15 было бы более реалистично имхо и + нужно иметь в виду, что 10 реальных минут не всегда равно 10 игровым минутам.

2023-06-19 13:26 UTC, volas commented on code/modules/mob/living/carbon/human/say.dm
> +	var/datum/timedevent/timer = SStimer.timer_id_dict["timerid[conversation_timer]"]
на тг есть луп-таймеры и updatetimedelay, но это отдельным ПРом тащить. Может вариант просто сбрасывать одиночество при бессознательном состоянии и пропускать тик таймера

2023-06-19 16:25 UTC, volas commented
Оно еще не замерженно, и я против того выпила. Возможно рано закрывать, но как хочешь.

2023-06-20 01:03 UTC, LudwigVonChesterfield commented on code/modules/mob/living/carbon/human/say.dm
> +				10 MINUTES,
перекинуться раз в 20 минут фразой с коллегой это "не реалистично"?...

2023-06-20 20:46 UTC, LudwigVonChesterfield commented
я бы предложил смержить так как эффектов от муда пока-что нет а в новой системе конкретно этот мудлет я бы хотел видеть.

2023-06-22 04:00 UTC, LudwigVonChesterfield commented on code/modules/mob/emote.dm
> +	var/viewers = message_type & SHOWMSG_VISUAL ? viewers(get_turf(src), world.view) : hearers(get_turf(src), world.view)
https://github.com/TauCetiStation/TauCetiClassic/pull/11464/files#diff-68a53a959e831e50243e16bcc7f57c5a5a756babfdeafbf8294b9b84c1ab30b6R90

господи что тут происходит

Для каждого обзервера заново рассчитываем всех смотрящих за тем кто говорит!

Тем временем: "о нет +1 viewers() обход"

2023-06-22 04:00 UTC, LudwigVonChesterfield commented on code/modules/mob/living/carbon/human/say.dm
> +	var/datum/timedevent/timer = SStimer.timer_id_dict["timerid[conversation_timer]"]
так как сейчас есть похоже нормально, ждём в будущем луптаймеров.

2023-06-22 08:24 UTC, volas commented on code/modules/mob/emote.dm
> +	var/viewers = message_type & SHOWMSG_VISUAL ? viewers(get_turf(src), world.view) : hearers(get_turf(src), world.view)
первая часть - просто предложение поступить проще. Касательно viewers/hearers/view/range/что-там-еще, у бьенда есть ряд не очевидных оптимизаций и способов выстрелить себе в ногу, но тут я еще раз пригляделся и вроде ок. Но

> и visible_message/audible_message работают сложнее и точнее, чем просто viewers/hearers.

про более конкретную проблему. Там где-то и рекурсивные обходы, и другой способ обхода. Может получится так, что сообщения юзер не увидит, но социализация прокнет. Или наоборот, увидит, но не прокнет.

2023-06-22 08:45 UTC, volas commented on code/modules/mob/living/carbon/human/say.dm
> +				10 MINUTES,
Но ведь не за 20, сейчас за 10 минут уже накидывается довольно высокий штраф в -6, сравнимый с болью (это, кстати, еще момент для обсуждения - почему штрафы такие высокие). Как только прокнул - человеку нужно за оставшиеся 10 минут заметить проблему и пойти найти, с кем поговорить, иначе впадет в еще большую депрессию.

И 10 минут по темпу игры имхо мало. У любого космонавта есть шансы оказаться на астеройде, застрять в космосе, или быть в ситуации, где отвлечься и пойти социализироваться крайне нежелательно (новичек первый раз запускает сингу/сидит читает вики за генетика, щитсек сидит в засаде). А есть еще афк. А есть еще ночные раунды, где банально может не найтись с кем поговорить.

2023-06-22 08:56 UTC, volas commented on code/modules/mob/living/carbon/human/say.dm
> +				10 MINUTES,
Космос вообще злой, тут какой-то кумулятивный эффект окажись ты в спессе, без еды, и не дай бог еще и с какой-то болью.

2023-07-01 12:56 UTC, volas commented on code/modules/mob/emote.dm
> +	var/viewers = message_type & SHOWMSG_VISUAL ? viewers(get_turf(src), world.view) : hearers(get_turf(src), world.view)
другой комментарий обсудили, это пока еще нет

2023-07-02 21:34 UTC, LudwigVonChesterfield commented on code/modules/mob/emote.dm
> +	var/viewers = message_type & SHOWMSG_VISUAL ? viewers(get_turf(src), world.view) : hearers(get_turf(src), world.view)
походу придётся делать больше аргументов у show_message, visible_message, audible_message!

иначе никак не можем.

2023-07-05 16:20 UTC, volas commented
https://github.com/NinjaPikachuska/TauCetiClassic/pull/1

хотелось бы перенести еще рунчат в конец и за флаг, но там свои сообщения. Видимо до рефакторинга.

2023-07-27 08:50 UTC, closed without merging