респрайт столов
TauCetiStation/TauCetiClassic pull request #11461
Opened 2023-05-26 10:36 UTC by DarthSidiousPalpatine

## Описание изменений
**Респрайтнул все столики и стойку:**
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/21008918/c77c4fcd-18e5-47e5-9aa7-96935e257108)
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/21008918/4764eb30-8c58-4902-9aab-095be01497bd)
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/21008918/6eefa355-d218-42a2-bfa4-f6b1e4d404da)![image](https://github.com/TauCetiStation/TauCetiClassic/assets/21008918/035a5279-2165-444a-9b42-0381b6768b1b)
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/21008918/9c94bf6a-0e66-40ba-b7c9-61ac7cce29ea)

Как это выглядит в мире вообще, примеры:
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/21008918/35038879-b163-464f-bb22-41167e27e7b9)
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/21008918/e239a02d-ef9c-4697-aa25-a0c037a26f42)
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/21008918/ea38b0b0-03ce-4255-86a1-40e698a8c01e)
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/21008918/f0b98294-48a1-4f8d-808e-191ba8247192)
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/21008918/fc2203d3-9a53-4181-9099-9ba2ac124f77)
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/21008918/6f5243fa-3aa8-4574-9e47-dc267a24be13)
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/21008918/24a56d43-f621-4791-bdac-2c8a2d1a1877)
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/21008918/67d9ed77-0736-4c76-9d15-27f8e9c8df71)
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/21008918/c196c293-d1bc-4091-9cb7-64cc2eebdb48)
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/21008918/866550aa-4f27-4cd6-9d78-1757fb0370e5)
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/21008918/680928ad-79c6-45ce-a53a-83ecb9b9ff2f)
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/21008918/762ab347-2107-4b72-b411-6ee480150e74)
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/21008918/55fac92a-0609-45ba-bd14-e8163f058ff3)
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/21008918/b620bbd9-daab-4489-8259-9c91c0924d56)
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/21008918/bf7a32de-74f3-46e1-ae68-89231393f644)

## Почему и что этот ПР улучшит
Хз, старый спрайт столов be gone?

## Авторство
AndreyGysev и все все все, кто помогал в дискорде.

## Чеинжлог
 :cl:
  - image: Столы и стойка заимели новые спрайты.

2023-05-26 10:36 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2023-05-26 12:57 UTC, DarthSidiousPalpatine commented
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/21008918/95f348ac-f860-49af-8daa-e1d512304555)
Могу у деревянных ножек меньше сделать

2023-05-27 03:33 UTC, LudwigVonChesterfield commented
Почему и что этот ПР улучшит

Хз

2023-05-28 16:11 UTC, Naroke commented
У столов слишком много ножек, а так нормально

2023-05-29 17:28 UTC, pro100kotah commented
Укрепленные столы выглядят просто ахуенно. Гусев вперед!

2023-05-30 04:59 UTC, DarthSidiousPalpatine commented
поддержу актив

2023-06-06 02:28 UTC, UDaV73rus requested changes
:|

2023-06-27 14:21 UTC, closed without merging