изменения ивента на спавн мобов в техах
TauCetiStation/TauCetiClassic pull request #11471
Opened 2023-05-27 21:04 UTC by AndroBetel

## Описание изменений
в техах больше не спавнятся слизни, пилоны и хайвботы
вместо них спавнятся другие мобы - шейды, осьминоги и киберхорроры
почему именно они:
шейды - исключительно из-за элемента пугачки. одиноких лутеров техов вполне можно будет страшненько взять за жопу полуневидимый моб, ослепляющий и выключающий свет
осьминоги - много хп, кидаются какашками. не слишком опасный, но посмеяться можно будет
киберхорроры - тоже не слишком опасный, но если повезет, может превратить чела в киберхорора или киборга
## Почему и что этот ПР улучшит
ивент интереснее
## Авторство

## Чеинжлог
:cl:
- rscadd: В тоннелях будут появляться монстры поинтереснее.

2023-05-27 21:04 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2023-05-28 02:46 UTC, maleyvich commented
обьявляется неделя киберхорроров на тауцети

2023-05-28 02:56 UTC, LudwigVonChesterfield commented
вроде прикол пилонов сделать вид что хаха культ ржака попался офицерик

2023-05-28 08:48 UTC, AndroBetel commented
> вроде прикол пилонов сделать вид что хаха культ ржака попался офицерик

они выглядят out of place и ломаются решительным челом с горелкой, хз...

2023-05-28 11:35 UTC, SiveanBen commented
> вроде прикол пилонов сделать вид что хаха культ ржака попался офицерик

Всё офицеры метаеберы и при виде пилонов в техах в начале раунда просто игнорят их. Даже ксеноморфы челов чуть больше пугают

2023-05-28 11:46 UTC, KIBORG04 commented on code/modules/mob/living/simple_animal/hostile/maintenance.dm
> +/mob/living/simple_animal/hostile/forgotten/AttackingTarget()
forgotten? Ты же shade кодишь

2023-05-28 16:17 UTC, LudwigVonChesterfield commented on code/modules/mob/living/simple_animal/hostile/maintenance.dm
> +/mob/living/simple_animal/hostile/forgotten/AttackingTarget()
произошла копипаста

2023-05-28 16:20 UTC, AndroBetel commented on code/modules/mob/living/simple_animal/hostile/maintenance.dm
> +/mob/living/simple_animal/hostile/forgotten/AttackingTarget()
не копипаста я просто думал изменить имя но потом передумал

2023-05-28 23:00 UTC, KIBORG04 requested changes
Ну в общем, ждем выпил копипасты

2023-05-29 22:08 UTC, merged