[WiP] Дополнение кода ролей антагонистов
TauCetiStation/TauCetiClassic pull request #11470
Opened 2023-05-27 18:49 UTC by Deahaka

## Описание изменений
Добавлены трейты, которые выдаются ролями при присоеденении разума. Переделана большая часть проверок на роли из истайпов на проверку трейтов. Попробовал сразу создать все комбинации доступные без щитспавна в игре в виде кучи трейтов. Не все из них используются, но в идеале как-то должны.

Почему WiP?
Щитспавном всё работает. Но раундстартовые антагонисты почему-то не получают трейты. Потыкал и увидел что AssignToRole работают корректно во всех случаях, но по какой-то причине трейты не навешиваются. HELP WANTED!
## Почему и что этот ПР улучшит
Код. Конкретный юз предполагает что можно будет выдать разные трейты одним и тем же ролям, а после на этом построить их особенности геймплея. Также возможен юз выдачей таких трейтов мобам без роли, чтобы те могли проходить проверки на роли и пользоваться некоторыми шмотками антагов не требуя выдачи роли.
## Авторство
Luduk
## Чеинжлог

2023-05-27 18:49 UTC, TauKitty commented
###### Changelog status: :radio_button: No changelog

2023-05-27 18:52 UTC, LudwigVonChesterfield commented on code/game/gamemodes/roles/cultist.dm
> +	ADD_TRAIT(M.current, TRAIT_CULTIST_MEMBER, GAMEMODE_TRAIT)
а рантаймов никаких нет? какой шанс что M.current эток  примеру не та кукла которой должны выдаваться трейты...

2023-05-27 18:59 UTC, Deahaka commented on code/game/gamemodes/roles/cultist.dm
> +	ADD_TRAIT(M.current, TRAIT_CULTIST_MEMBER, GAMEMODE_TRAIT)
Никто кроме абдукторов у меня не запустился. По ним сужу, может только там не работает, но беглым осмотром не нашёл мест где бы куклы поменялись или типо того

2023-05-27 19:26 UTC, KIBORG04 commented on code/game/gamemodes/roles/abductor.dm
> +/datum/role/abductor/AssignToRole(datum/mind/M, override = FALSE, msg_admins = TRUE, laterole = TRUE)
> Щитспавном всё работает. Но раундстартовые антагонисты почему-то не получают трейты. Потыкал и увидел что AssignToRole работают корректно во всех случаях, но по какой-то причине трейты не навешиваются. HELP WANTED!

Насколько я помню, раундстартом в AssignToRole попадают еще госты. Тебе бы юзать OnPostSetup, там всегда кукла игрока.

2023-05-27 19:32 UTC, KIBORG04 commented on code/__DEFINES/is_helpers.dm
>  #define isgangsterlead(H) isrole(GANGSTER_LEADER, H)
А че лидаку и дилеру не сделал?

2023-05-28 05:41 UTC, Deahaka commented on code/__DEFINES/is_helpers.dm
>  #define isgangsterlead(H) isrole(GANGSTER_LEADER, H)
Это используется не как "истайп" а как "получить ссылку на роль"

2023-05-28 08:17 UTC, Deahaka commented
Действительно в `AssignToRole()` был майнд госта. Переписал на `OnPostSetup()`

2023-05-28 14:41 UTC, LudwigVonChesterfield commented on code/__DEFINES/is_helpers.dm
>  #define isgangsterlead(H) isrole(GANGSTER_LEADER, H)
возможно стоит сделать какую-то конвенцию чтобы истайп и ссылка на роль назывались по-разному

2023-05-28 14:42 UTC, LudwigVonChesterfield commented
Хочу заметить что относительно элегантно фиксит проблемы вида:

https://github.com/TauCetiStation/TauCetiClassic/pull/11413

2023-05-28 23:04 UTC, KIBORG04 commented on code/__DEFINES/is_helpers.dm
>  #define isgangsterlead(H) isrole(GANGSTER_LEADER, H)
> Это используется не как "истайп" а как "получить ссылку на роль"

Сделай пж, чтобы они использовались только как "истайп"

2023-06-03 13:13 UTC, KIBORG04 approved these changes
да вроде ок

2023-06-13 19:47 UTC, volas requested changes

2023-06-13 19:47 UTC, volas commented on code/game/gamemodes/roles/abductor.dm
> +
можно было бы список выдаваемых трейторов прописывать параметром в определении роли, и выдавать их в родительском AssignToRole/RemoveFromRole. OnPostSetup тут немного не в тему, и будет меньше копипасты

2023-06-13 19:49 UTC, volas commented
Я не против идеи, но я всё еще чувствую что это какое-то дублирование уже имеющихся ролей в майнде непонятно зачем. И проблема, что трейты вешается на моба, когда роли (и их хуки) работают с майндом. А если вешать трейты на майнд - то тогда какая разница, если там уже есть ``antag_roles`` списком.

2023-06-22 08:16 UTC, Deahaka commented
Хз не знаю, пофиг?

2023-06-22 08:16 UTC, closed without merging