тест сабжекты стартую со случайными скиллами
TauCetiStation/TauCetiClassic pull request #11489
Opened 2023-05-29 09:01 UTC by simb11

## Описание изменений
тест сабжектс (и подпрофессии) стартуют со случайными скиллами
## Почему и что этот ПР улучшит
Сделает профессию уникальней и чуть более интересной.
## Авторство

## Чеинжлог
🆑 Simbaka
- tweak: Случайный набор умений у профессии "Подопытный".

2023-05-29 09:01 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2023-05-29 13:52 UTC, LudwigVonChesterfield commented on code/game/jobs/job/assistant.dm
> +		H.mind.skills.randomize()
Думаю randomize должна быть функцией скиллсета который добавляют

2023-05-29 14:30 UTC, LudwigVonChesterfield commented
изменение идёт вразрез с тем что по задумке скиллы должны заменять педальное правило на отнимание работы

сейчас при должном расскладе карт абсолютно безответственный тест сабжект/официант сможет в теории заменить хоть кого...

мне нравится идея но я не уверен как себя об этом чувствую.

2023-05-29 14:49 UTC, TryXAH commented
> сможет в теории заменить хоть кого

только при определенном раскладе, и опять же, в отсутствии того, кто эту работу сделать сможет
никто не даст тестовику варить что-то в химии при самом химике
но если его нет, то дадут ему эту должность, если он захочет, даже без смены скиллов

2023-05-29 15:28 UTC, LudwigVonChesterfield commented
> никто не даст тестовику

кто именно не даст, если педали - то я против ПР-а.

2023-05-29 20:11 UTC, simb11 commented
> изменение идёт вразрез с тем что по задумке скиллы должны заменять педальное правило на отнимание работы

ну не знаю, не думаю что кто-то будет за подопытного целенаправленно красть у кого-то работку, типа заниматься хирургией, химией, взламывать шлюзы. 
если кто-то захочет таким заниматься - он зайдёт за нужную профессию (например, ассистента какого-нибудь отдела, который тоже не обладает грузом ответственности) и гарантированно получит нужные навыки.

но если очень страшно, могу убрать разброс и сделать чтоб всегда был первый уровень у случайных навыков..

2023-05-30 04:52 UTC, LudwigVonChesterfield commented on code/modules/skills/skillset.dm
> +	skills = list(
мне кажется две проблемы.

1. у разных скиллов раньше был разный "ренж". не знаю или это актуально сейчас, но 1-ичка в melee когда-то была "очень хорошо" потому-что по дефолту было -1
2. мне кажется вместо "нарандомить все скиллы а потом удалять лишнее" проще было бы сделать что-то типо такого:

```
/datum/skillset/random/New()
    var/static/list/possible_skills = list(
        /datum/skill/police,
        /datum/skill/firearms,
        // 1. такого списка точно нигде нет?
        // 2. нужно ли взвешивать шанс выпадения скиллов? Чтобы условно пилотирование мехом было редким.
    )
    
    for(var/i in 1 to 5)
        var/skill_improvement = pick(possible_skills)
        skills[skill_improvement] += 1
        if(skills[skill_improvement] > max)
            possible_skills -= skill_improvement
```

2023-05-30 04:53 UTC, LudwigVonChesterfield commented on code/game/jobs/job/assistant.dm
> +			s.randomize()
предлагаю вместо этого сделать /datum/skillset/random, где внутри New скиллсета рандомились бы скиллы.

2023-05-30 04:53 UTC, LudwigVonChesterfield commented on code/game/jobs/job/assistant.dm
> +		H.add_moveset(new moveset(), MOVESET_JOB)
кажется мувсет выдаётся дважды. один раз тут, и ещё раз в родителе.

2023-05-30 04:53 UTC, LudwigVonChesterfield commented on code/game/jobs/job/assistant.dm
> +	var/outfit_type = get_outfit(H, alt_title)
кажется одежда выдаётся дважды.

2023-05-30 04:54 UTC, LudwigVonChesterfield commented on code/game/jobs/job/assistant.dm
> -		"Lawyer"         = /datum/skillset/test_subject/lawyer,
если будешь идти в сторону взвешенных рандомных скиллов, можно сделать чтобы "веса" скиллов зависели от подпрофы.

2023-06-04 21:03 UTC, simb11 commented
всё переделал

2023-06-05 17:34 UTC, LudwigVonChesterfield commented on code/game/jobs/job/assistant.dm
> +	skillsets = list("Test Subject"   = /datum/skillset/random)
```suggestion
	skillsets = list("Test Subject" = /datum/skillset/random)
```

2023-06-05 17:34 UTC, LudwigVonChesterfield commented on code/game/jobs/job/assistant.dm
> +	skillsets = list("Test Subject"   = /datum/skillset/random)
а остальным подпрофам тоже даёт скиллсет рандом или нет?

2023-06-05 17:35 UTC, LudwigVonChesterfield commented on code/modules/skills/skillsets/misc.dm
> +		if(skills[skill_improvement] > skill_max)
```suggestion
		if(skills[skill_improvement] >= skill_max)
```

2023-06-05 17:35 UTC, LudwigVonChesterfield commented on code/modules/skills/skillsets/misc.dm
> +	var/skill_max = 2
```suggestion
	var/skill_max = 3
```

2023-06-05 17:44 UTC, simb11 commented on code/game/jobs/job/assistant.dm
> +	skillsets = list("Test Subject"   = /datum/skillset/random)
у них случайный да

2023-06-05 22:08 UTC, LudwigVonChesterfield commented on code/game/jobs/job/job.dm
> +		for(var/datum/skillset/random/s as anything in H.mind.skills.available_skillsets)
надобность этого решения связана с тем что скиллсеты сейчас синглтоны, но ничего не мешает "индивидуализировано" добавлять их.

предлагаю реализовать фичу так:
- добавить новую функцию, позволяющую добавлять инстанс скиллсета вместо типа
datums/skills.dm
```
/datum/skills/proc/add_unique_available_skillset(datum/skillset/S)
    LAZYADD(available_skillsets, S)
    update_available()
```

кроме этого можно поменять
skills.dm
```
/datum/skills/proc/add_available_skillset(skillset_type)
    add_unique_available_skillset(global.skillsets[skillset_type])
```

имея эту функцию, убрать skillsets у job/test_subject, потому-что для них мы создаём индивидуализированный набор навыков, и нам не подойдет юзать общую систему.

соответственно
job/assistant.dm
```
/datum/job/assistant/equip()
    . = ..()
    if(!.)
        return
 
    if(!H.mind)
        return

    H.mind.skills.add_unique_available_skillset(new /datum/skillset/random())
    H.mind.skills.maximize_active_skills()
```

2023-06-05 22:08 UTC, LudwigVonChesterfield requested changes
думаю нужно исправить то как сейчас работает добавление рандомизированного скиллсета. смотри комментарий в ПР-е

2023-06-12 07:23 UTC, simb11 commented on code/game/jobs/job/job.dm
> +		for(var/datum/skillset/random/s as anything in H.mind.skills.available_skillsets)
не работает что-то твой вариант с удалением скиллсета...
[09:14:32] Runtime in job.dm:187 : bad index
  proc name: get skillset (/datum/job/proc/get_skillset)
  src: /datum/job/assistant (/datum/job/assistant)
Runtime in skillset.dm:16 : Cannot execute null.get value().
  proc name: merge (/datum/skillset/proc/merge)
Runtime in skills.dm:19 : Cannot execute null.merge().
  proc name: update available (/datum/skills/proc/update_available)

2023-06-14 13:55 UTC, LudwigVonChesterfield commented on code/game/jobs/job/job.dm
> +		for(var/datum/skillset/random/s as anything in H.mind.skills.available_skillsets)
не уверен что понимаю, это с моим предложением которое сейчас в ПР-е такая ошибка?

2023-06-14 13:56 UTC, LudwigVonChesterfield commented on code/game/jobs/job/job.dm
> +		for(var/datum/skillset/random/s as anything in H.mind.skills.available_skillsets)
увидел, проблема в том что /datum/job/proc/get_skillset почему-то не учитывает что скиллсета может не быть

нужно поменять код везде на то чтобы учитывать что скиллсета у профы может не быть

2023-07-01 13:18 UTC, closed without merging