Удаление секьюрити модуля у боргов (и небольшой бафф пискипера)
TauCetiStation/TauCetiClassic pull request #11490
Opened 2023-05-29 10:34 UTC by maleyvich

## Описание изменений
Полное удаление секьюрити борга из кода игры, для выбора модуля "Peacekeeper" теперь не требуется никаких улучшений.
## Почему и что этот ПР улучшит
Удаление довольно грифозного и ненужного борга, "раб не должен карать своего хозяина". На его более легкую и негрифозную замену полностью приходит модуль пискипера.
## Авторство
maleyvich
## Чеинжлог
:cl:
- del: Охранный модуль боргов был полностью удален, вместе с необходимой для него платой.
- tweak: Для выбора модуля "Peacekeeper" теперь не требуется улучшение.

2023-05-29 10:34 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2023-05-29 10:37 UTC, AndroBetel requested changes

2023-05-29 10:37 UTC, AndroBetel commented on code/game/objects/items/robot/robot_upgrades.dm
> +	if(!istype(R.module, /obj/item/weapon/robot_module/peacekeeper))
у пискипера же нет тазера, зачем тогда этот тазеркулер нужен (он и до этого был бесполезный, тоже выпилить???)

2023-05-29 10:37 UTC, AndroBetel commented on code/game/objects/items/robot/robot_upgrades.dm
> -	if(R.can_be_security)
не увидел удаления этой переменной

2023-05-29 10:39 UTC, Deahaka approved these changes
У нас не было контента чтобы РнД могло исследовать плату СБ борга? Надо её тогда тоже удалить и исследования РнД проверить, ибо оно выдавать ошибку не будет при компиляции.

2023-05-29 10:39 UTC, Deahaka commented on code/game/objects/items/robot/robot_upgrades.dm
> +	if(!istype(R.module, /obj/item/weapon/robot_module/peacekeeper))
Лишнее

2023-05-29 10:41 UTC, maleyvich commented
> У нас не было контента чтобы РнД могло исследовать плату СБ борга? Надо её тогда тоже удалить и исследования РнД проверить, ибо оно выдавать ошибку не будет при компиляции.

вроде бы все методы получения сесюрити платы выпилили, кроме кабинета рд

2023-05-29 11:09 UTC, TauKitty commented
Этот запрос на слияние был упомянут в **Tau Ceti Station Forum**. Там могут быть соответствующие подробности:

https://forum.taucetistation.org/t/golosovanie-udalenie-sb-modulya-borgu/39540/1

2023-05-29 11:30 UTC, maleyvich commented
переменная удалена, все ошибки пофикшены.

2023-05-30 22:39 UTC, pro100kotah commented
Ахахха, вы только подумайте. Малевич потратил столько времени, чтобы сделать мем для форумчан. Ахахаххаха.

2023-06-03 13:21 UTC, Fenriros commented
Сесурити мод может помочь когда нет сб, или когда они все откинулись. А что может противопоставить пискипер против культа, генокрада?

2023-06-06 10:59 UTC, maleyvich commented
> Сесурити мод может помочь (чем-то) когда нет сб, или когда они все откинулись. А что может противопоставить пискипер против культа, генокрада?

найди мне как минимум три причины почему раб должен быть надзирателем для своего хозяина

2023-06-07 20:50 UTC, Fenriros commented
> > Сесурити мод может помочь (чем-то) когда нет сб, или когда они все откинулись. А что может противопоставить пискипер против культа, генокрада?
> 
> найди мне как минимум три причины почему раб должен быть надзирателем для своего хозяина

Зачем мне тебе что искать, когда есть википедия?
Если я тебя правильно понял, то как и другие борги у них есть законы, которые они должны соблюдать.
За боргов играют люди, а если они их не соблюдают, тогда проблема в людях а не в боргах.

2023-06-13 20:06 UTC, volas commented
> Полное удаление секьюрити борга из кода игры

можно было бы удалить из выбора в модуле, сам борг еще где-то может пригодится. Сделать что-то как уже с дройдеками.

2023-06-14 08:45 UTC, maleyvich commented
> > Полное удаление секьюрити борга из кода игры
> 
> можно было бы удалить из выбора в модуле, сам борг еще где-то может пригодится. Сделать что-то как уже с дройдеками.

лучше полностью ограничить доступ к секборгам - у меня попросту нет идей где эта машина для ролькоханта может пригодиться. у нее нет никакой другой цели, в отличии от любого другого модуля боргов. а боевой модуль боргов вообще щас щитспавнят? если нет, то и смысла делать сб модуль таким же нет

у меня такое мнение, и всё-же если вы настаиваете то я могу сделать его  щитспавным.

2023-06-16 04:22 UTC, LudwigVonChesterfield commented
если хочешь быстрого мержа определенно стоит попробовать сделать щитспавным

2023-06-16 04:40 UTC, maleyvich commented
> если хочешь быстрого мержа определенно стоит попробовать сделать щитспавным

окей, сделаем.

2023-06-16 05:38 UTC, maleyvich commented
ПР был серьезно обновлён, попрошу ознакомиться с изменениями!

2023-06-16 06:12 UTC, Deahaka commented on code/modules/mob/living/silicon/robot/robot.dm
> +	if(crisis) //Leaving this in until it's balanced appropriately.
```suggestion
```
Это не надо, сверху точно такая же проверка устраивает.

2023-06-16 06:14 UTC, Deahaka commented on code/modules/mob/living/silicon/robot/robot.dm
> +		to_chat(src, "<span class='warning'>Crisis mode active. Security available.</span>")
в `Crisis mode active. Combat available` добавь секурити или переформулируй. Отдельный тучат не нужен, пусть будет один, говорящий что доступно и Секурити и Комбат. Может назвать ПРОТОКОЛЫ ПОДАВЛЕНИЯ или Нейтрализации угроз.

2023-06-16 06:15 UTC, Deahaka commented on code/modules/mob/living/silicon/robot/robot.dm
> -	if(opened && (icon_state == "mechoid-Standard" || icon_state == "mechoid-Service" || icon_state == "mechoid-Science" || icon_state == "mechoid-Miner" || icon_state == "mechoid-Medical" || icon_state
тут сделай ревёрт, так как это касается отображения спрайтов

2023-06-16 06:16 UTC, Deahaka commented on code/datums/emotes/robot/audible.dm
> -		EMOTE_STATE(has_robot_module, /obj/item/weapon/robot_module/security),
это наверное тоже можно вернуть, так как остаётся он в игре же.

2023-06-16 07:34 UTC, TEXH4Pb commented
Наебал в названии ПРа, это всё ещё выпил СБ борга

2023-06-16 07:44 UTC, Rumpiturs commented
Жёсткий нерф боргов.

2023-06-18 18:27 UTC, maleyvich commented
все требования были выполнены и выходит что пр готов к просмотру?

2023-06-20 12:10 UTC, volas requested changes

2023-06-20 12:10 UTC, volas commented on code/datums/emotes/robot/audible.dm
> -		EMOTE_STATE(has_robot_module, /obj/item/weapon/robot_module/security),
ты тут открыл эмоуты сек боргов для всех остальных. Это не надо было трогать

2023-06-20 12:10 UTC, volas commented on code/datums/emotes/robot/audible.dm
> +		EMOTE_STATE(is_stat, CONSCIOUS)
аналогично

2023-06-20 12:10 UTC, volas commented on code/modules/mob/living/silicon/robot/robot.dm
> +	if(opened && (icon_state == "mechoid-Standard" || icon_state == "mechoid-Service" || icon_state == "mechoid-Security" ||  icon_state == "mechoid-Science" || icon_state == "mechoid-Miner" || icon_sta
тут дехака тоже прав, к выбору модуля не относится и не стоит изменять

2023-06-20 12:10 UTC, volas commented on code/game/objects/items/robot/robot_upgrades.dm
> -	require_module = 1
это будет потерянным апдейтом, но его все равно пришлось бы выпиливать из фабрикатора, так что имхо ок и не страшно.

2023-06-20 12:10 UTC, volas commented on code/modules/mob/living/silicon/robot/robot.dm
> -	var/can_be_security = FALSE
саму переменную верни

2023-06-20 12:10 UTC, volas commented on code/modules/mob/living/silicon/robot/robot.dm
> +		choose_module["Security"] = image(icon = 'icons/mob/robots.dmi', icon_state = "security")
```suggestion
	if(can_be_security)
		choose_module["Security"] = image(icon = 'icons/mob/robots.dmi', icon_state = "security")
```

и тут сделай так. Будет отдельный флаг для включения кризиса, и отдельный для секьюрити.

Бонусные поинты, если еще ``var/crisis`` переименуешь в ``var/can_be_crisis`` для консистентности

2023-06-20 12:33 UTC, maleyvich commented on code/modules/mob/living/silicon/robot/robot.dm
> +		choose_module["Security"] = image(icon = 'icons/mob/robots.dmi', icon_state = "security")
всё сделано, думаю насчёт проверки на красный код, но вероятно нет

2023-06-20 13:23 UTC, volas approved these changes
По коду - ок, по идее - спорный фидбек. Но я понимаю, откуда и в чем задумка, и можно попробовать смержить и посмотреть на дистанции в может пару месяцев, как оно будет.

По пискиперу ничего не знаю, но это вроде в чате обсуждалось.

2023-06-28 07:43 UTC, maleyvich commented
Несмотря на проведенное голосование, которое означало что сб модуль нужно оставить - я не согласен с его результатами. Хоть и гитхаб не является платформой для обсуждения таких вещей, но я думаю нужно внести свою небольшую лепту. Со стороны тех, кто голосовал против действий с сб боргом выступал аргумент, что эти изменения повлекут за собой ПОНИЖЕНИЕ УРОВНЯ РП НА СЕРВЕРЕ, что является неправдой и  вероятно даже наоборот. Иных аргументов, кроме как "выпиливание контента" не было - однако, со стороны тех, кто голосовал за изменения - было достаточно много аргументов, например то что этот модуль направлен на ролькохант и никакие взаимодействия по РП с ним невозможны, у него нет инструментов для этого. Не хочется говорить, но даже на других билдах уже нет этого модуля, однако люди всё еще защищают этот инструмент ролькоханта (даже администрация!). Вероятно, нужно будет проводить второе голосование - но ПР не будет закрыт.

2023-07-01 15:35 UTC, Fenriros commented
> Несмотря на проведенное голосование, которое означало что сб модуль нужно оставить - я не согласен с его результатами. Хоть и гитхаб не является платформой для обсуждения таких вещей, но я думаю нужно внести свою небольшую лепту. Со стороны тех, кто голосовал против действий с сб боргом выступал аргумент, что эти изменения повлекут за собой ПОНИЖЕНИЕ УРОВНЯ РП НА СЕРВЕРЕ, что является неправдой и вероятно даже наоборот. Иных аргументов, кроме как "выпиливание контента" не было - однако, со стороны тех, кто голосовал за изменения - было достаточно много аргументов, например то что этот модуль направлен на ролькохант и никакие взаимодействия по РП с ним невозможны, у него нет инструментов для этого. Не хочется говорить, но даже на других билдах уже нет этого модуля, однако люди всё еще защищают этот инструмент ролькоханта (даже администрация!). Вероятно, нужно будет проводить второе голосование - но ПР не будет закрыт.

Так значит дело не в модуле, а в людях

2023-07-16 05:28 UTC, maleyvich commented
никак нет, пр все ещё актуален.

2023-07-30 06:11 UTC, maleyvich commented
пр все актуален (я не сдамся)

2023-08-05 18:09 UTC, maleyvich commented
пр все ещё актуален и он нужен серверу

2023-08-19 21:21 UTC, Kiromaka commented
пр не актуален, малевич сдавайся

2023-08-20 18:23 UTC, maleyvich commented
пр ещё актуален и я готов поддерживать его состояние

2023-09-04 07:05 UTC, maleyvich commented
проблема сб боргов осталась, но закрываю в связи с новыми прами гусева, всем удачи.

2023-09-04 07:05 UTC, closed without merging