Личная мини-аптечка почти бесполезного говна релейтед ту профессия вместо коробки.
TauCetiStation/TauCetiClassic pull request #11500
Opened 2023-05-30 18:53 UTC by DarthSidiousPalpatine

## Описание изменений
Потом заполню, драфт пр.

## Почему и что этот ПР улучшит
Ну камон, ребят, коробка в рюкзаке это кек.

## Авторство
Andrey Gysev и все все все, кто помогал в дискорде. Особенно Волас, если поможет с этим багом.

## Чеинжлог
 :cl:
  - rscadd: добавлены мини-аптечки вместо коробок в рюкзаках.

2023-05-30 18:53 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2023-05-30 18:55 UTC, TryXAH commented
гусев давай гусев вперед

2023-05-30 19:10 UTC, LudwigVonChesterfield commented
баллон в аптечке это кек

2023-05-30 19:10 UTC, LudwigVonChesterfield commented on code/datums/outfits/jobs/cargo.dm
> +	survival_kit_items = list(/obj/item/weapon/storage/pill_bottle/citalopram
тут и везде

```
survival_kit_items = list(
    /obj/1,
    /obj/2,
)
```

в таком стиле красивее

2023-05-30 19:13 UTC, LudwigVonChesterfield commented
https://github.com/TauCetiStation/TauCetiClassic/pull/4382

https://github.com/TauCetiStation/TauCetiClassic/pull/5285

Предлагаю к ознакомлению прошлые подобные инициативы, и их рейтинг аппрувала.

2023-05-30 20:17 UTC, DarthSidiousPalpatine commented
Во, расписал всё.

2023-05-30 20:38 UTC, DarthSidiousPalpatine commented
> #4382
> 
> #5285
> 
> Предлагаю к ознакомлению прошлые подобные инициативы, и их рейтинг аппрувала.

По пунктам:
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/21008918/19c50e62-e814-4392-a7e0-f70576fd1a55)
А тут у меня не у всех есть бинтики, и "бинтик" на 1 использование, а не на 5 как в обычном.
Плюс я спецом изменил и вид и смысл "коробки" с защиты от разгермы на карманную аптечку.

Что смешно, во втором ПРе добавили АЖ СТАЗИС, МАЗЬ, СКАНЕР ЗДОРОВЬЯ И БИНТ офицерикам. А реакция была уже:
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/21008918/46c6e3c4-2cbc-4f59-ba9d-d943145b59c4)
Ну, я пытался, надеюсь, моих спрайтов достаточно.

2023-05-30 20:39 UTC, TauKitty commented
Этот запрос на слияние был упомянут в **Tau Ceti Station Forum**. Там могут быть соответствующие подробности:

https://forum.taucetistation.org/t/fludilka-chast-2/28659/23981

2023-05-30 20:48 UTC, DarthSidiousPalpatine commented
> баллон в аптечке это кек

![image](https://github.com/TauCetiStation/TauCetiClassic/assets/21008918/8d811860-a4bc-4ef6-9d98-75f69ce003bb)
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/21008918/ede59383-f7b0-4ea4-b5f1-589fbcd27ce2)
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/21008918/194e4f5f-2f7d-4670-98f0-819ceb07b2d7)

Ну типа.. ножницы, свистки, фонарики, бутылки в аптечке... кеееек?
Очевидно баллон потому что мы в космосе. Были бы в арктике там бы была сапёрная лопатка, сухой лёд и спички. Были бы в джунглях там бы были всякие противооспалительные и пр. фигня.

2023-05-31 03:02 UTC, Tap0r commented
Может просто в лоадаут такую мини аптечку добавить? За 1-2 поинта, кому надо те возьмут.

Просто меня лично пугает этот огромный список введений непонятных. 

Витамины каждому каргонцу и главе втф зачем. 

Инженерам таблетки от радиации это ну лишнее явно. Сколько помню в меде играл, регулярно инженеры иногда после настройки двигателя приходили от радиации лечиться и ниче, нормально всё было, никаких проблем, даже наоборот социалочка.

Таблетки от заражения переработчику тоже не пойми зачем, у него скафандр, перчатки, лопата, мех, он в принципе не может заразиться, а даже если и словит токсинов, пусть в мед идет.

Ученым таблы от гиперактивности это прикол или просто положить нечего было?

У ксенобиолога всё есть на его рабочем месте, тоже очень сомнительно.
У психолога тоже всё в его кабинете в шкафу есть.

Бутылочка с водкой офицерам смешно.

Короче сомнительно очень.

2023-05-31 04:57 UTC, Lexakr commented
Это очень странно видеть, вспоминая разговоры и разработочку всяких штук типа страховки. А тут на тебе антирадин. Выглядит как флафф/лоадаут, но как замена коробки чет ваще нет. В чем вообще проблема коробочки? Это как сумка в сумке, а тут придется с той же целью использовать твою аптечку и хранить мелочи не в коробке а в аптечке

2023-05-31 04:59 UTC, DarthSidiousPalpatine commented
> Это очень странно видеть, вспоминая разговоры и разработочку всяких штук типа страховки. А тут на тебе антирадин. Выглядит как флафф/лоадаут, но как замена коробки чет ваще нет. В чем вообще проблема коробочки? Это как сумка в сумке, а тут придется с той же целью использовать твою аптечку и хранить мелочи не в коробке а в аптечке

Действительно самое небезобидное из всего списка это антирадин. Потому я убрал его у инженеров и оставил у СЕ ток.
МБ и у СЕ стоит убрать, тут хз.

2023-05-31 17:46 UTC, Fx43t2nm commented
андрей а как быть с нутриментовыми инъекторами и азотобаллоном у воксов, а еще охладителем и нанопастой спу

это все в их коробках

2023-05-31 17:47 UTC, DarthSidiousPalpatine commented
> андрей а как быть с нутриментовыми инъекторами и азотобаллоном у воксов, а еще охладителем и нанопастой спу
> 
> это все в их коробках

Оно не удалено из них. Я просто буквально добавил новых предметов.

2023-06-20 14:59 UTC, Naroke commented
Гусев, что с аптечкой?

2023-07-04 15:32 UTC, Venngedi commented
Мержа не будет?

2023-07-15 05:45 UTC, volas requested changes
Идея сделать сурвайвл кит аптечкой вместо дефолтной коробки мне нравится, нужен апрув спрайтеров.

Обновление контента сурвайвал кита - спорно, и тут слишком много всего что бы обсуждать, лучше отдельными PR-ами.

2023-07-15 05:45 UTC, volas commented on code/game/objects/items/weapons/storage/firstaid.dm
> +	update_world_icon()
это обсуждали, сейчас не очень. Если хочется использовать таким образом - я бы мог добавить аргументы в ``update_world_icon``, или помочь переделать.

2023-07-22 12:11 UTC, DarthSidiousPalpatine commented
Удав сказал нет, всем удачи.

2023-07-22 12:11 UTC, closed without merging