Changeling Implant Managment
TauCetiStation/TauCetiClassic pull request #11515
Opened 2023-06-02 19:20 UTC by Deahaka

## Описание изменений
Альтернатива https://github.com/TauCetiStation/TauCetiClassic/pull/11497 предложенная мной. Генокрад получает свободный доступ к мимикрированию под все импланты, которые светятся на худе. Мимикрия работает точно также как и обычный имплант, но для лояльности я отключил пользование цепью коммандования, чтобы плётка не стала хайриск итемом. В сканере мимикрированные импланты отображаться не будут.
![000000000000000000000000000000000000007 - копия](https://github.com/TauCetiStation/TauCetiClassic/assets/96499407/0b704521-077e-4f65-935a-baab83d443d4)

## Почему и что этот ПР улучшит
Разнообразие игровых ситуаций. Путём удаления упоминания обиденс импланта, удаляет мету в сторону генокрадов (генокрад никогда не мог получить обиденс имплант). Даёт генокраду-притворщику хороший баф, что должно увеличить колличество не шрик-армблейд страток.
## Авторство

## Чеинжлог
:cl: Deahaka
- add: Все генокрады получили новую способность бесплатно подражать имплантам на охранном hud-интерфейсе.

2023-06-02 19:20 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2023-06-02 22:36 UTC, LudwigVonChesterfield commented on code/datums/atom_huds/atom_hud_data.dm
> +	if(isimplantedchem())
мне кажется как раз эта функция должна называться как-то типо "has_chemimplandhud" потому-что по факту у генокрада импланта нет, только картинка.

2023-06-02 22:36 UTC, LudwigVonChesterfield commented on code/game/gamemodes/modes_gameplays/wizard/artefact.dm
> +	if(H.ismindprotect(TRUE))
я бы предпочёл вместо этого иметь две функции:

- одна про визуальную составляющую
- одна про физическую сущность наличия импланта

2023-06-02 22:37 UTC, LudwigVonChesterfield commented
я бы все равно добавил импланты и в экзамайн честно говоря... чисто исходя из удобства и размышлений о новичках.

2023-06-03 07:11 UTC, Deahaka commented
Убрал подчинение генокрадов цепи, добавил идею людука отрывать руки если кто-то кликнет цепью не по назначению. Остаётся абуз особковых големов, так как на их оторванные руки может быть насрать капитану/хосу, но пока видимо его не покрываем и оставляю вот так.

2023-06-03 12:56 UTC, KIBORG04 commented on code/game/gamemodes/modes_gameplays/changeling/implant_menu.dm
> +	if(HAS_TRAIT_FROM(H, TRAIT_MINDSHIELD, FAKE_IMPLANT_TRAIT))
Жесть тут всё в копипасте. Сделай тут, наверное, функцию, которая будет выдавать нужную строку в зависимости от переданных аргументов

2023-06-03 12:57 UTC, KIBORG04 commented on code/game/gamemodes/modes_gameplays/changeling/implant_menu.dm
> +	if(href_list["remove"])
Жесть тут всё в копипасте. Сделай наверн лист, где будет `implant_* = TRAIT_*`. Ну а дальше `trait_to_remove = list[href_list["remove"]]`. `trait_to_add = list[href_list["remove"]]`

2023-06-03 12:59 UTC, KIBORG04 commented on code/game/objects/items/weapons/implants/implant.dm
> +		REMOVE_TRAIT(host, TRAIT_TRACK_IMPLANTED, IMPLANT_TRAIT)
Жесть тут копипасты. Не легче ли сделать переменную `implant_trait`, поместить код добавление и удаления трейтов в самый родительский класс и всё?

2023-06-03 13:00 UTC, KIBORG04 commented on code/modules/surgery/implant.dm
> +					imp.implant_removal(target)
Если я не ошибаюсь, там еще есть способы вынуть имплант. Посмотри еще раз, на всякий случай.

2023-06-03 13:01 UTC, KIBORG04 commented on code/game/objects/items/weapons/implants/mindshield.dm
> +		ADD_TRAIT(C, TRAIT_LOYAL, IMPLANT_TRAIT)
Почему эта функция не рядом с его братом-implant_removal?

2023-06-03 13:03 UTC, KIBORG04 commented on code/__DEFINES/traits.dm
> +#define TRAIT_TRACK_IMPLANTED     "track_implanted"
Если они отвечают только за визуальные худы, мб так и назвать?

2023-06-03 16:53 UTC, Deahaka commented on code/game/objects/items/weapons/implants/implant.dm
> +		REMOVE_TRAIT(host, TRAIT_TRACK_IMPLANTED, IMPLANT_TRAIT)
Не знаю, я думал что трейты должны так всегда прописываться конкретно, чтобы было легко найти и менять всё это.

2023-06-03 16:54 UTC, LudwigVonChesterfield commented on code/__DEFINES/traits.dm
> +#define TRAIT_TRACK_IMPLANTED     "track_implanted"
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/17705613/a0abebee-d0c6-45ae-a68f-d7806e71da1b)


Дехака непонятно зачем резолвнул мои комментарии литерали об этом.

2023-06-03 16:54 UTC, Deahaka commented on code/modules/surgery/implant.dm
> +					imp.implant_removal(target)
я вроде все просмотрел взаимодействия с тайпом импланта. остальные где for(var/object in mob) я врядли найду.

2023-06-03 16:55 UTC, LudwigVonChesterfield commented on code/datums/atom_huds/atom_hud_data.dm
> +	if(ishaveloyalhud())
ishave идентично к has

2023-06-03 16:58 UTC, Deahaka commented on code/__DEFINES/traits.dm
> +#define TRAIT_TRACK_IMPLANTED     "track_implanted"
не знаю, надо назвать правильно "TRAIT_VISUAL_MINDSHIELD"?

2023-06-03 16:58 UTC, KIBORG04 commented on code/game/objects/items/weapons/implants/implant.dm
> +		REMOVE_TRAIT(host, TRAIT_TRACK_IMPLANTED, IMPLANT_TRAIT)
Так сам трейт явно будет лежать в переменной, а дальше много ума не надо найти, где переменная используется

2023-06-05 22:39 UTC, pro100kotah commented
> Убрал подчинение генокрадов цепи, добавил идею людука отрывать руки если кто-то кликнет цепью не по назначению. Остаётся абуз особковых големов, так как на их оторванные руки может быть насрать капитану/хосу, но пока видимо его не покрываем и оставляю вот так.

Чет про отрывание и проверку не понял

2023-06-06 01:39 UTC, LudwigVonChesterfield commented on code/game/gamemodes/modes_gameplays/changeling/implant_menu.dm
> +		ADD_TRAIT(M, topics_trait_keys[href_list["add"]], FAKE_IMPLANT_TRAIT)
сейчас трейт можно добавлять несколько раз за счёт того что не валидируется инпут от юзера.

надо проверять или трейт уже есть, юзер может выполнять кастомные команды (я забыл синтаксис, но короче ты можешь не кликать а по кнопочке а ввести в строку бьёнда что-то типо byond://implants/[0xqw8dqw8eas8d]/add=implant_m и оно выполнит)

2023-06-06 01:41 UTC, LudwigVonChesterfield commented on code/game/objects/items/weapons/implants/implant.dm
> +	if(implant_trait)
эту проверку можно объединить с проверкой на след. строке в implant_Trait && istype(host)

2023-06-06 01:41 UTC, LudwigVonChesterfield commented on code/game/objects/items/weapons/melee/misc.dm
> +		to_chat(target, "<span class='userdanger'>THEY KNOWS ABOUT US!!!</span>")
```suggestion
		to_chat(target, "<span class='userdanger'>COVER BLOWN!!! THEY KNOW ABOUT US!!!</span>")
```

2023-06-06 01:42 UTC, LudwigVonChesterfield commented on code/modules/mob/mob_helpers.dm
> +	if(HAS_TRAIT(src, TRAIT_VISUAL_MINDSHIELD))
можно три строчки заменить на `return HAS_TRAIT(src, TRAIT_VISUAL_MINDSHIELD)` заставляет задуматься нужна ли такая функция вообще...

точно так же для остальных. @KIBORG04

2023-06-06 01:42 UTC, LudwigVonChesterfield commented on code/modules/mob/mob_helpers.dm
> +	if(HAS_TRAIT(src, TRAIT_VISUAL_MINDSHIELD) || HAS_TRAIT(src, TRAIT_VISUAL_LOYAL))
не уверен что понимаю вот эту часть. а почему имплант лояльности отображается как майндшилд

2023-06-06 05:10 UTC, Deahaka commented on code/modules/mob/mob_helpers.dm
> +	if(HAS_TRAIT(src, TRAIT_VISUAL_MINDSHIELD) || HAS_TRAIT(src, TRAIT_VISUAL_LOYAL))
Это не для отображения, а только для проверок при конвертах онли, насколько я помню.

2023-06-06 18:00 UTC, LudwigVonChesterfield commented on code/modules/mob/mob_helpers.dm
> +	if(HAS_TRAIT(src, TRAIT_VISUAL_MINDSHIELD) || HAS_TRAIT(src, TRAIT_VISUAL_LOYAL))
тогда "имеет худ майнд протекта" делает не только "имеет худ" а ещё и "имеет имплант в плане проверок и конверта" что все равно не корректно

2023-06-06 20:13 UTC, Deahaka commented on code/modules/mob/mob_helpers.dm
> +	if(HAS_TRAIT(src, TRAIT_VISUAL_MINDSHIELD))
убрал все такие функции и заменил на местный хес-треит

2023-06-06 20:16 UTC, Deahaka commented on code/modules/mob/mob_helpers.dm
> +	if(HAS_TRAIT(src, TRAIT_VISUAL_MINDSHIELD) || HAS_TRAIT(src, TRAIT_VISUAL_LOYAL))
убрал это функцию и заменил всё на местный хес-трейт. Момент про скилы, где проверяется наличие импланта для сгорания скилов. Это закрывает потенциал спалить по мете через принятия скил-чипа в имплантированного протектмаендом генку.

2023-06-07 20:35 UTC, LudwigVonChesterfield commented on code/modules/mob/mob_helpers.dm
> +	if(HAS_TRAIT(src, TRAIT_VISUAL_MINDSHIELD) || HAS_TRAIT(src, TRAIT_VISUAL_LOYAL))
функция ещё тут...

2023-06-07 20:41 UTC, ViDLiathan commented on code/modules/mob/mob_helpers.dm
> +	if(HAS_TRAIT(src, TRAIT_VISUAL_MINDSHIELD) || HAS_TRAIT(src, TRAIT_VISUAL_LOYAL))
Это же мимикрия под импланты, а не наделение их реальными свойствами. Обманка ведь только для худов, как я понимаю, а вот специализированное оборудование не должно их детектить или как то реагировать.

2023-06-13 20:26 UTC, volas commented on code/game/gamemodes/modes_gameplays/changeling/implant_menu.dm
> +	var/mob/M = usr
..() тут не нужен?

2023-06-13 20:37 UTC, volas requested changes

2023-06-13 20:37 UTC, volas commented on code/game/gamemodes/modes_gameplays/changeling/implant_menu.dm
> +		REMOVE_TRAIT(M, topics_trait_keys[href_list["remove"]], FAKE_IMPLANT_TRAIT)
нужно валидировать, какие трейты себе юзер пытается удалить и добавить

2023-06-13 20:37 UTC, volas commented on code/game/gamemodes/modes_gameplays/changeling/implant_menu.dm
> +	text += get_implant_text(enabled_mindshield, enabled_loyal, enabled_obey, enabled_chem, enabled_track)
я думаю, было бы читаймей, вынеси ты просто контент get_implant_text сюда. Что так копипаста, что так.

а setup_mimicry_active_text и setup_mimicry_unactive_text лучше сделать дефайн-макросами

2023-06-14 06:52 UTC, Deahaka commented on code/game/gamemodes/modes_gameplays/changeling/implant_menu.dm
> +		REMOVE_TRAIT(M, topics_trait_keys[href_list["remove"]], FAKE_IMPLANT_TRAIT)
На добавление трейта валидирование уже сделал, чтобы нельзя было добавить дважды один и тот же (если это возможно?). А на удаление вроде все проверки внутри дефайна сработают и в случае каких-то неувязиц просто ничего не предпримут.

2023-06-17 04:11 UTC, LudwigVonChesterfield commented on code/game/gamemodes/modes_gameplays/changeling/implant_menu.dm
> +		REMOVE_TRAIT(M, topics_trait_keys[href_list["remove"]], FAKE_IMPLANT_TRAIT)
просто добавь валидацию чтобы показать будущим поколениям что надо валидировать ВСЕГДА

2023-06-17 06:21 UTC, Deahaka commented on code/game/gamemodes/modes_gameplays/changeling/implant_menu.dm
> +		REMOVE_TRAIT(M, topics_trait_keys[href_list["remove"]], FAKE_IMPLANT_TRAIT)
добавил валидацию всегда

2023-06-18 21:28 UTC, KIBORG04 commented on code/game/objects/items/weapons/implants/implant.dm
> +	var/implant_trait = ""
```suggestion
	var/implant_trait
```

2023-06-18 21:32 UTC, merged