Добавляет предателям новую цель
TauCetiStation/TauCetiClassic pull request #11529
Opened 2023-06-05 10:50 UTC by simb11

## Описание изменений
Добавляет трейтору цель на саботирование рнд
Предатель должен проникнуть в серверную и взломать консоль управления серверами (нажать альтклик), после чего из базы данных серверов случайным образом удалятся 3 исследования, плюс к этому, все консоли исследований взорвутся взрывом.
Ещё удалил возможность создавать сервера рнд, потому что новая цель будет ломаться.
## Почему и что этот ПР улучшит
Больше интересных и, самое главное, влияющих на жизнь экипажа заданий у предателя.
## Авторство

## Чеинжлог
🆑 Simbaka
- add[link]: У предателей появилась новая цель.

2023-06-05 10:50 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2023-06-05 11:04 UTC, AndroBetel commented
наверное надо его сделать неразрушимым а то будет обидненько в раундах с ксеноморфами или репликаторами...

2023-06-05 11:33 UTC, Mercurialaste commented
Больше не создаваемых вещей богу не создаваемых вещей.

2023-06-05 13:39 UTC, ViDLiathan commented
Идея отличная, реализация немного странная.
Зачем взрывать, когда можно сделать синий экран смерти?
А вместо простого альт клика, можно дать тритору бесплатный предмет в виде флоппи диска с вирусом, который нужно сунуть в консоль. Может выглядеть как обычный диск, которые повсюду валяются в техах, но детектится, если поместить его в деконструктор. 
Ну и превращение консоли в уберпостройку тоже выглядит странно. Мне кажется это лишнее.

2023-06-05 13:55 UTC, simb11 commented
> Идея отличная, реализация немного странная. Зачем взрывать, когда можно сделать синий экран смерти?

Учёный может легко и быстро пересобрать консоль, а вот после взрыва нужно во первых звать инженеров, а во вторых починка отсека будет длиться достаточно долго.


> А вместо простого альт клика, можно дать тритору бесплатный предмет в виде флоппи диска с вирусом, который нужно сунуть в консоль. Может выглядеть как обычный диск, которые повсюду валяются в техах, но детектится, если поместить его в деконструктор.

Это тоже неплохой вариант, если многие захотят именно диск - сделаю его.

2023-06-05 15:05 UTC, TryXAH commented
новая целька круто гудмод постройке не круто

2023-06-15 02:39 UTC, LudwigVonChesterfield commented on code/game/gamemodes/roles/traitor.dm
> +							SR.already_completed = TRUE
можно ли это сделать как-нибудь иначе?

желательно:
а) не выдавать эту цель вообще если кто-то уже саботировал
б) при выдаче цели проверить саботированность и дернуть этот флаг

2023-06-15 02:39 UTC, LudwigVonChesterfield commented on code/modules/research/server.dm
> +/obj/machinery/computer/rdservercontrol/AltClick(mob/user)
можно ли это делать не альткликом?

2023-06-15 02:40 UTC, LudwigVonChesterfield commented on code/modules/research/server.dm
> +/obj/machinery/computer/rdservercontrol/AltClick(mob/user)
некоторые цели выдают предметы нужные для них, может стоит что-то выдать?

2023-06-15 07:32 UTC, simb11 commented on code/modules/research/server.dm
> +/obj/machinery/computer/rdservercontrol/AltClick(mob/user)
а что делать с этим предметом если кто-то другой уже выполнил цель?

2023-06-15 09:20 UTC, KIBORG04 commented on code/game/gamemodes/roles/traitor.dm
> +							SR.already_completed = TRUE
У нас, вроде, есть глобальный лист all_objectives (или подобное). Можно в нем проверять, заспавнена ли задача и если да, то выдавать другую

2023-06-16 04:21 UTC, LudwigVonChesterfield commented on code/modules/research/server.dm
> +/obj/machinery/computer/rdservercontrol/AltClick(mob/user)
не вижу никаких проблем. предмет есть предмет. ничего с ним делать не нужно?

если второй человек предметом кликает ему просто сообщение что упсики уже взломано, надо избавиться от улик

2023-06-29 20:08 UTC, simb11 commented
@LudwigVonChesterfield заменил альт клик на диск и ещё эта цель может выпасть только одному предателю.

2023-07-01 12:38 UTC, Oz1Es commented
интересная целька, но у меня вопрос, пропадёт типо одно исследование из ветки? Или прям целая ветка?

2023-07-02 21:34 UTC, LudwigVonChesterfield commented on code/datums/components/gamemodes/syndicate.dm
> +	for(O in R.objectives.GetObjectives())
что тут происходит

почему это работает

2023-07-05 16:35 UTC, KIBORG04 commented on code/game/gamemodes/objectives/objectives.dm
> +	required_equipment = new required_equipment(H.loc)
Я дума, так не стоит переопределять переменную, пусть всегда лучше будет тайп тут, а не ссылки

2023-07-05 16:37 UTC, KIBORG04 commented on code/game/gamemodes/objectives/sabotage_research.dm
> +	required_equipment = /obj/item/weapon/disk/data/syndi
Чисто для красоты

2023-07-05 16:38 UTC, KIBORG04 commented on code/game/gamemodes/objectives/sabotage_research.dm
> +	..()
```suggestion
```
Не нада

2023-07-05 16:47 UTC, KIBORG04 commented on code/game/gamemodes/roles/traitor.dm
> +					AppendObjective(/datum/objective/research_sabotage, TRUE)
Наверное, стоит добавить глобальную переменную. ЛИБО, почему только 1 задача, почему бы не выдавать просто рандомно и пусть выполняют челики/конкурируют? Этот код странный и, если повезет, является бесконечной рекурсией.

2023-07-05 16:47 UTC, KIBORG04 commented on code/modules/research/server.dm
> +		sabotage(user, S)
```suggestion
		sabotage(user, D)
```
Не нужно

2023-07-05 16:53 UTC, KIBORG04 commented on code/modules/research/server.dm
> +					return //in order to avoid that the antagonist will constantly do this.
Мейби, добавить в тот диск какую-то переменную, которая бы обозначала одноразовость, а не такой ужас?

2023-07-05 16:54 UTC, KIBORG04 commented on code/modules/research/server.dm
> +					return //in order to avoid that the antagonist will constantly do this.
а, диск удаляется, хайп тогда, зачем нужен этот код?

2023-07-05 16:54 UTC, KIBORG04 commented on code/modules/research/server.dm
> +/obj/machinery/computer/rdservercontrol/proc/sabotage(mob/user, obj/item/weapon/disk/data/syndi/d)
```suggestion
/obj/machinery/computer/rdservercontrol/proc/sabotage(mob/user, obj/item/weapon/disk/data/syndi/D)
```
Маленькая буква лошпедская какая-то

2023-07-05 16:56 UTC, KIBORG04 approved these changes
Ну я написал че думаю, так то все ок, но моменты с поиском обжектива страшные.

2023-07-15 06:29 UTC, volas requested changes

2023-07-15 06:29 UTC, volas commented on code/game/gamemodes/objectives/sabotage_research.dm
> +		to_chat(user, "<span class='warning'>This disk contains a computer virus to sabotage the station's systems!</span>")
зависимость идентификации антаг итемов от скилов глобальный вопрос, который бы лучше решать отдельно. Не хотелось бы создавать прецедент без обсуждения, потому предлагаю пока убрать.

 @Lexakr занимался этим, можно еще с ним обсудить.

2023-07-15 06:29 UTC, volas commented on code/modules/research/server.dm
> +					return //in order to avoid that the antagonist will constantly do this.
```suggestion
```

Этот кусок лишний и ничего сейчас не делает, насколько понимаю. Диск есть в аплинке для всех, так что проверять наличие и статус задачи саботажа лишнее.

2023-07-15 06:29 UTC, volas commented on code/modules/research/server.dm
> +	to_chat(user, "<span class='warning'>Так-с, эта процедура займёт [sabotage_time / 10] секунд.</span>")
```suggestion
	to_chat(user, "<span class='warning'>Эта процедура займёт некоторое время...</span>")
```

do_after может зависеть от скиллов/настроения/лагов, так что точное время сложно прогнозировать. И мы обычно нигде так не делаем. По прогресс бару будет сразу примерно понятно.

2023-07-15 06:29 UTC, volas commented on code/modules/research/server.dm
> +		explosion(c.loc, 3, 2, 1)
может, это будет как-то палевно. Просто мысли.

2023-07-15 06:29 UTC, volas commented on code/modules/research/server.dm
> +			s.files.forget_random_technology()
интересный момент - для постоянного забытия технологии *раз в тик* достаточно перегреть сервер. И это не требует постоянного личного присутствия. И вроде не предупреждает ученых о проблема...

На фоне этого механа дроп 3 рандомных технологий со спецэффектами (ниже) и при требуемом личном присутствии выглядит как-то слабо.

Стоило бы либо перегрев понерфить (отдельным Пром), либо всё таки диск бафнуть (я думаю, не критично, если даже все технологии будут дропнуты - у них есть диски для бэкапов, и сами исследования не столь тяжелы).

2023-07-15 06:29 UTC, volas commented on code/modules/research/server.dm
> +			rs.already_completed = TRUE
Я бы предложил выполнять саботаж для всех антагов, а не только для конкретного. Как уже происходит (происходило) с задачами на травмы или заключение - не важно кто это сделал, важен сам факт. Что задача на диверсию, а кто сделает не столь важно. Так будет например еще возможность делегировать диверсию кому-то другому.

2023-07-15 06:29 UTC, volas commented on code/game/gamemodes/objectives/sabotage_research.dm
> +/obj/item/weapon/disk/data/syndi
Дефолтный ``/obj/item/weapon/disk/data`` называется "Cloning Data Disk" и имеет соответствующую иконку, нужно переопределить. Или может быть ты хотел унаследовать его от ``/obj/item/weapon/disk/research_points``, но они для консолей а не сервера.

Можешь посмотреть еще в сторону https://github.com/TauCetiStation/TauCetiClassic/issues/11321, если есть желание.

2023-07-15 06:58 UTC, AndroBetel commented on code/game/gamemodes/objectives/objectives.dm
> +		to_chat(H, "You have been given some equipment for the mission, check your backpack or hands.")
я там недавно добавил особку на оружие, которое достается из любой мусорки, мб что-то такое сделать? это не будет захламлять инвентарь и в случае отсутствия одежды позволит выполнить задачу

2023-07-15 07:06 UTC, volas commented on code/game/gamemodes/objectives/objectives.dm
> +		to_chat(H, "You have been given some equipment for the mission, check your backpack or hands.")
мог ссылкой приложить, но вообще - и канистры для голов, и этот диск, всё еще можно заказать в аплинке. Это не смертельно, и ситуация со спавном безрукого и без рюкзака далека от реальности.

2023-07-29 00:20 UTC, volas commented on code/game/gamemodes/objectives/sabotage_research.dm
> +		to_chat(user, "<span class='warning'>This disk contains a computer virus to sabotage the station's systems!</span>")
это тоже конечно прецедент, такие вещи лучше отдельно делать. Ну ладно.

2023-07-29 00:25 UTC, volas commented on code/game/gamemodes/objectives/sabotage_research.dm
> +/obj/item/weapon/disk/data/syndi
у нас нету механики маскировки предметов под другие и соответствующего детекта. В таком виде этот диск будет слишком беспалевный, и даже будет работать в качестве диска генетики без каких-то проблем.

2023-07-29 00:29 UTC, volas commented on code/game/gamemodes/objectives/sabotage_research.dm
> +/obj/item/weapon/disk/data/syndi
хотя я таки вижу, что такие предметы уже существуют, ладно

2023-07-29 00:31 UTC, volas commented on code/game/gamemodes/objectives/sabotage_research.dm
> +		to_chat(user, "<span class='warning'>This disk contains a computer virus to sabotage the station's systems!</span>")
предлагаю тогда вообще убрать. Если диск не отличается, то это какой-то слишком OOC комментарий

2023-08-03 03:14 UTC, volas commented on code/game/gamemodes/objectives/sabotage_research.dm
> +		to_chat(user, "<span class='warning'>This disk contains a computer virus to sabotage the station's systems!</span>")
```suggestion
```

и я мержу

2023-08-03 18:12 UTC, volas approved these changes

2023-08-03 18:12 UTC, merged