Altar corruption
TauCetiStation/TauCetiClassic pull request #11699
Opened 2023-07-10 16:32 UTC by Chip11-n

## Описание изменений
Алтарь священника можно будет с серьёзным выражением моськи красть, получать аспекты, и не бояться бвоинька.
Культисту надо подойти, ударить книгой по алтарю, подтвердить выбор, и тогда у священника будет 15 секунд, что бы защитить алтарь и не дать забрать свою собственность. Вокруг еретика появляется фильтр красный, так что промахнуться сложно.

В связи с этим, алтари чужой религии больше нельзя красть в физическом плане на пару с ключом. Да, священники и ассистухи, хватит гадить под коврик.
## Почему и что этот ПР улучшит
Можно будет на официальный основаниях заявить, что **Это не баг, а фича!**
_А ещё, что бы я мог это абузить, когда бан пройдёт_
## Авторство

## Чеинжлог
:cl:
- tweak: Немного изменена кража алтаря священника.

2023-07-10 16:32 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2023-07-10 19:36 UTC, Chip11-n commented
Оповещение религии уже есть. И по факту это просто обмен информации о режиме на бафф режиму. И за 15 секунд сделаны чисто что бы не крали алтарь прямо из под носа священника. В общем, посмотрим ещё со временем.

2023-07-10 19:49 UTC, AzzyDreemurr13 commented
> . И 15 секунд сделаны что бы не крали алтарь прямо из под носа священника. В общем, посмотрим ещё со временем.

Сильно ты надеешься на сознательность игроков, лучше действительно 30 секунд - 1 минуту, иначе будут заставлять вокруге стенками и смотреть на капелана с такой рожей:  :peka: :peka: :peka:

2023-07-10 20:00 UTC, Chip11-n commented
> > . И 15 секунд сделаны что бы не крали алтарь прямо из под носа священника. В общем, посмотрим ещё со временем.
> 
> Сильно ты надеешься на сознательность игроков, лучше действительно 30 секунд - 1 минуту, иначе будут заставлять вокруге стенками и смотреть на капелана с такой рожей: :peka: :peka: :peka:

Ты-то написал всё правильно, но не учёл, что палка о двух концах. Если слишком повысить время, будет ещё и разгерметизация. Ну и ещё повод ставить алтарь у всех на виду, а не в коморке.

2023-07-12 07:09 UTC, Chip11-n commented
Я всех обманул. Там было 25 секунд. Ну, значит 25, что уж.

2023-07-12 08:32 UTC, AzzyDreemurr13 commented
Ну так тем более

2023-07-12 20:45 UTC, KIBORG04 commented on code/modules/religion/altar_types/altar_of_gods.dm
> +		to_chat(user, "<span class='notice'>Это алтарь иной религии</span>")
Это мы все вынести в отдельную функцию, а не в can_interact!!!!

2023-07-12 20:46 UTC, KIBORG04 commented on code/modules/religion/altar_types/altar_of_gods.dm
> +	var/chaplain_altar = TRUE
Мне не нравится эта переменная. Думаю, надо сделать `/obj/structure/altar_of_gods/chaplain` и решить задачу полиморфизмом

2023-08-18 14:05 UTC, Chip11-n commented
Понятия не имею, почему в диффах карты меняются местами переменные, но в целом, оно готово.

2023-08-27 21:44 UTC, volas approved these changes
Я **ничего** не знаю про культ и священника, по коду роде ок.

25 секунд по меркам станции мало, по меркам do_after много, посмотрим как на деле будет.

Надо поправить мерж конфликт (перестановки - либо от отсутствия dmm хуков, либо в какой-то версии SDMM была проблема, я не помню)

2023-09-04 07:12 UTC, Deahaka commented
Хороший ПР, поскорее бы мерж

2023-09-04 13:46 UTC, Chip11-n commented
В общем, я не знаю, что делать с этими конфликтами. Что-то при мап мержере пошло не так. Наверное, придётся уже пересоздавать ПР.

2023-09-04 13:55 UTC, Deahaka commented
А ты везде ставил 2 (Remote) в выборе предложенных изменений?

2023-09-04 14:01 UTC, Deahaka commented
Попробуй ещё раз ревертнуть `second_try`, обновить ветку с мастером (на локалке чтоб была актуальная) и внести эту замену тайпов. Может даже можно через Ctrl+F просто /obj/structure/altar => /obj/structure/church/altar или как там у тебя

2023-09-04 14:15 UTC, Chip11-n commented
В этом и дело, что оба способа уже попробовал

2023-09-05 15:26 UTC, KIBORG04 commented
Вроде ок дифф же

2023-09-05 15:31 UTC, KIBORG04 commented on code/modules/religion/altar_types/altar_of_gods.dm
> +		piety = "and <span class=' [religion.style_text]'>[round(religion.piety)] piety</span>"
```suggestion
		piety = "and <span class='[religion.style_text]'>[round(religion.piety)] piety</span>"
```
Что-то странное.

2023-09-05 15:32 UTC, KIBORG04 commented on code/modules/religion/altar_types/altar_of_gods.dm
> +	msg += "<span class='notice'>The religion currently has [round(religion.favor)] favor[piety] with [pick(religion.deity_names)].\n</span>"
```suggestion
	msg += "<span class='notice'>The religion currently has [round(religion.favor)] favor [piety] piety with [pick(religion.deity_names)].\n</span>"
```
Что-то странное.

2023-09-05 15:32 UTC, KIBORG04 commented on code/modules/religion/altar_types/altar_of_gods.dm
> +	msg += "<span class='notice'>The religion currently has [round(religion.favor)] favor[piety] with [pick(religion.deity_names)].\n</span>"
А, я понял

2023-09-05 15:34 UTC, KIBORG04 commented on code/modules/religion/altar_types/altar_of_gods.dm
> +		to_chat(user, "<span class='warning'>Не знаю что с этим делать.</span>")
Возможно стоит вообще эту строчку удалить. Тип, атмосфернее, когда как раз ничего не пишется, ты ведь не знаешь как это юзать!

2023-09-05 15:36 UTC, KIBORG04 commented on code/modules/religion/altar_types/altar_of_gods.dm
> +		to_chat(user, "<span class='warning'>Получить силу чужих алтарей можно только осквернив уже действующий алтарь!</span>")
```suggestion
		to_chat(user, "<span class='warning'>Получить силу чужих алтарей можно только, осквернив уже действующий алтарь!</span>")
```
Вроде дееприч. оборот.

2023-09-05 15:37 UTC, KIBORG04 commented on code/modules/religion/altar_types/altar_of_gods.dm
> +		to_chat(user, "<span class='warning'>Получить силу чужих алтарей можно только осквернив уже действующий алтарь!</span>")
Хотя звучит как хрень.

2023-09-05 15:39 UTC, KIBORG04 commented on code/modules/religion/altar_types/altar_of_gods.dm
> +		to_chat(user, "<span class='warning'>Получить силу чужих алтарей можно только осквернив уже действующий алтарь!</span>")
Но сообщение всё равно странное. Акцент как-то не на том, а нужно на "действующем".  Сам подумай крч

```suggestion
		to_chat(user, "<span class='warning'>Алтарь должен быть действующим, чтобы его можно было осквернить.</span>")
```

2023-09-05 15:40 UTC, KIBORG04 commented on code/modules/religion/altar_types/altar_of_gods.dm
> +		var/answer = tgui_alert(user, "Мы можем оквернить этот алтарь, и заполучить его силу! Однако, это займёт время, а еретики обязательно узнают об этом!", "Осквернение алтаря", list("Deus Vult!","Не с
```suggestion
		var/answer = tgui_alert(user, "Мы можем осквернить этот алтарь и заполучить его силу! Однако, это займёт время, а еретики обязательно узнают об этом!", "Осквернение алтаря", list("Deus Vult!","Не стоит"))
```
Мы можем осквернить и заполучить. Запятая не нужна.

2023-09-05 15:41 UTC, KIBORG04 commented on code/modules/religion/altar_types/altar_of_gods.dm
> +			religion.send_message_to_members("Еретики пытаются осквернить священный алтарь! НА ЗАЩИТУ!", user)
Эм, зачем ты юзера передаешь?
https://github.com/TauCetiStation/TauCetiClassic/blob/7311c553bb652f2d261fb30d8064a118193fe347/code/modules/religion/religion.dm#L657-L657

2023-09-05 15:48 UTC, KIBORG04 approved these changes
Попробуй хард ресетнуться до мержа мастера к себе в ветку. Затем опять запулль, но укажи мерж стратегию theirs. Ну и потом просто замени все алтари неподходящие. То что я предлагаю, вроде, быстрее чем твои изменения в новую ветку черри пикать и тд

`git pull upstream master -s theirs`

https://git-scm.com/docs/merge-strategies#Documentation/merge-strategies.txt-theirs

2023-09-05 15:48 UTC, KIBORG04 requested changes
Ой, не аппрув.

2023-09-23 20:01 UTC, Deahaka commented
капец так быстро время летит.

2023-09-23 22:16 UTC, KIBORG04 commented
Позови, откроем, а то мне глаза мазолит)

2026-04-18 15:47 UTC, closed without merging