Стоимость руки-молота повышена до 3
TauCetiStation/TauCetiClassic pull request #11722
Opened 2023-07-13 17:23 UTC by Leprekeoner

## Описание изменений
Пока кто незанерфит лучше, молот будет стоить 3 очка.
## Почему и что этот ПР улучшит
Молот стоит как меч, а профита больше. Неправильно.
## Авторство

## Чеинжлог
:cl:
-balance: Стоимость руки-молота повышена с 2 до 3 очков

2023-07-13 17:23 UTC, TauKitty commented
###### Changelog status: :x: Empty changelog (check markdown correctness)

2023-07-13 17:28 UTC, maleyvich commented
мухахаха убиваем генокрадов ещё сильнее!!! (фулл меты игрокам таусери не хватает)

а ещё у тебя в чеинжлоге не хватает пробела, исправь пожалуйста

2023-07-13 19:41 UTC, Deahaka commented
Рукомеч покупают в большем количестве чем рукомолот. Если бы мета сместилась так, что различия влияли бы на игроков массово, можно было бы утверждать что молот сильнее армблейда. Но по цифрам он слабее и сегодня я видел как генокрад с молотом умер от двух офицеров также как умер бы человек с армблейдом. Не вижу смысла нерфить, пусть может кто выскажется за изменения другими аргументами.

По задумке генокрадские отростки должны стоить одинаково и быть по-своему полезны, а не мешать собирать билды которые можно собрать только с другими вариантами.

2023-07-13 20:54 UTC, Mercurialaste commented
Зачем нерфить что-то, если можно бафнуть альтернативу?

2023-07-14 08:05 UTC, Oz1Es commented
Бед пр, лучше бы добавил турелей шаттлу нюки

2023-07-14 08:58 UTC, Rumpiturs commented
Жесть! Геннадии так слабые в плохих руках так ещё повышаешь цену на нормально оружие которое нужно чисто для стенок туц туц.

2023-07-15 09:23 UTC, BlankCringe commented
молот контрится нудизмом

2023-07-15 13:40 UTC, KIBORG04 requested changes
> По задумке генокрадские отростки должны стоить одинаково и быть по-своему полезны, а не мешать собирать билды которые можно собрать только с другими вариантами.

Лучше думать в сторону бафа других рук, чем эту нерфить

2023-07-24 20:43 UTC, KIBORG04 commented
В общем, баффай руки в других ПРах

2023-07-24 20:43 UTC, closed without merging