СПУ теперь можно перекрасить баллончиком краски.
TauCetiStation/TauCetiClassic pull request #11720
Opened 2023-07-13 15:12 UTC by Ro2tCrab

## Описание изменений
 Тайтл
## Почему и что этот ПР улучшит
 Лучше спросить у MIDI или Ксеновизора.
## Авторство
 Рукожопый - Я
Идея от MMDI
## Чеинжлог
:cl:
 - tweak: СПУ может быть перекрашен баллончиком краски в Disarm взаимодействии.

2023-07-13 15:12 UTC, TauKitty commented
###### Changelog status: :x: Empty changelog (check markdown correctness)

2023-07-15 14:03 UTC, KIBORG04 commented on code/game/objects/items/crayons.dm
> +		}
Я напомню, мы все еще кодим на бъонде, где `{` и `}` не нужны. Так же было бы круто, если бы ты не делал такие объемные и вложенные ифки, разбил бы на функции хз

2023-07-15 14:04 UTC, KIBORG04 commented on code/game/objects/items/crayons.dm
> +				var/new_skin = input(user, "Select IPC body color", "IPC body color") as null|color
почему мы должны тут что-то селектить, если цвет уже есть в самом баллончике????

2023-07-17 07:44 UTC, Ro2tCrab commented on code/game/objects/items/crayons.dm
> +				var/new_skin = input(user, "Select IPC body color", "IPC body color") as null|color
Можешь назвать это "защитой от дурака".

Я сделал все что смог что бы человек окончательно про*бался в попытке покрасить СПУ в розовый на ходу.

btw, я могу убрать это по необходимости.

2023-07-17 08:03 UTC, Deahaka commented on code/game/objects/items/crayons.dm
> +				var/new_skin = input(user, "Select IPC body color", "IPC body color") as null|color
Да, убрать необходимо

2023-07-17 08:03 UTC, KIBORG04 commented on code/game/objects/items/crayons.dm
> +				var/new_skin = input(user, "Select IPC body color", "IPC body color") as null|color
Чтобы на ходу не красили, то добавь do_after. Это же убери, так как мне не нравится и это не логично

2023-07-17 08:05 UTC, Deahaka commented on code/game/objects/items/crayons.dm
> +				var/new_skin = input(user, "Select IPC body color", "IPC body color") as null|color
может do_mob()?

2023-07-17 08:05 UTC, KIBORG04 commented on code/game/objects/items/crayons.dm
> +				var/new_skin = input(user, "Select IPC body color", "IPC body color") as null|color
Может, я не помню разницы

2023-07-22 12:11 UTC, Ro2tCrab commented on code/game/objects/items/crayons.dm
> +				var/new_skin = input(user, "Select IPC body color", "IPC body color") as null|color
> Чтобы на ходу не красили, то добавь do_after. Это же убери, так как мне не нравится и это не логично

Do_after уже есть

2023-07-22 12:11 UTC, Ro2tCrab commented on code/game/objects/items/crayons.dm
> +		}
> Я напомню, мы все еще кодим на бъонде, где `{` и `}` не нужны. Так же было бы круто, если бы ты не делал такие объемные и вложенные ифки, разбил бы на функции хз

*ужасные флешбеки*
Мне уже ничего не поможет с этим.

2023-07-24 20:41 UTC, KIBORG04 requested changes
`С` синтаксис еще не ушел, ждем.

2023-07-24 20:41 UTC, KIBORG04 commented on code/game/objects/items/crayons.dm
> +	to_chat(user, "<span class='notice'>- Can be used to repaint IPC in the Disarm intent.</span>")
Дизарма не существует

2023-07-24 20:41 UTC, KIBORG04 commented on code/game/objects/items/crayons.dm
> +			if(user.a_intent == INTENT_PUSH && H.get_species() == IPC){
Все еще `C`шные скобки

2023-07-25 16:19 UTC, Ro2tCrab commented on code/game/objects/items/crayons.dm
> +	to_chat(user, "<span class='notice'>- Can be used to repaint IPC in the Disarm intent.</span>")
Он у нас в дифайнах, вики, форумах обозначен как Disarm. Я продолжаю это для интуитивности.

2023-07-25 16:22 UTC, KIBORG04 commented on code/game/objects/items/crayons.dm
> +	to_chat(user, "<span class='notice'>- Can be used to repaint IPC in the Disarm intent.</span>")
А в игре это пуш. Вики не авторитет, форум не авторитет, код игрок не видит

2023-07-30 15:19 UTC, Ro2tCrab commented
> `С` синтаксис еще не ушел, ждем.

Ушел же.

2023-08-03 04:27 UTC, volas requested changes

2023-08-03 04:27 UTC, volas commented on code/game/objects/items/crayons.dm
>  	if(iscarbon(target) && uses - 10 >= 0)
предыдущая хардкод проверка, что uses > 10, но использовать может теперь 15 и мы можем выйти в минус.

По хорошему нужно переделать на ``use_tool``, но для быстроты я бы предложил оставить использование 10 юнитов для всего, как было. Это не критично, и сохранит время на рефакторинге старого кода, если ты к этому не готов.

2023-08-03 04:27 UTC, volas commented on code/game/objects/items/crayons.dm
> +			if(user.a_intent == INTENT_PUSH && H.get_species() == IPC)
проверка на интент не очевидна, это слишком скрытая фича получится, на которую попадут разве что случайно. Я бы оставил только на species

2023-08-03 04:27 UTC, volas commented on code/game/objects/items/crayons.dm
> +			C.eye_blind = max(C.eye_blind, 1)
лучше не делать лесенок с if-ами, а использовать концепт раннего возврата. Типо где-то в начале

```
if(!ishuman(C))
	uses -= 10
	C.blurEyes(3)
	C.eye_blind = max(C.eye_blind, 1)
	return

var/mob/living/carbon/human/H = C
...и дальше поведение работы с хьюманом, но уже без всяких лесенок...

```

На твоё усмотрение, переделывать или нет, тут остальной код такой же, так что не горит

2023-08-24 07:03 UTC, closed without merging