Imposters without uplink
TauCetiStation/TauCetiClassic pull request #11745
Opened 2023-07-18 07:14 UTC by Deahaka

## Описание изменений
Одна фракция триторов отсюда https://github.com/TauCetiStation/TauCetiClassic/pull/11741 в один режим. Лейтспавн включён, ограничений на профессии никаких
## Почему и что этот ПР улучшит
всё расписано в https://github.com/TauCetiStation/TauCetiClassic/pull/11741, правда не вся информация теперь актуальна и амбиции поменьше. Но главная идея запутать не меняется.
## Авторство

## Чеинжлог
:cl: Deahaka
- experiment: Добавлена вариация режима Traitor в Secret

2023-07-18 07:14 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2023-07-18 12:49 UTC, Deahaka commented
А ты что думал капитан в списках подозреваемых из раундстартовой бумажки это баг?

2023-07-18 13:15 UTC, Chip11-n commented
А роль можно снять имплантом? Если да, то теперь будет нормальной практикой ставить второй имплант капитану и хосу?

2023-07-18 17:20 UTC, liteyzz commented
> А роль можно снять имплантом? Если да, то теперь будет нормальной практикой ставить второй имплант капитану и хосу?

не, оправдать это психическим отторжением импланта, хоть 10 вколи отображаться отображаются а так не действуют

2023-07-18 21:29 UTC, LudwigVonChesterfield approved these changes
я бы хотел как минимум посмотреть какие будут результаты такого эксперимента

аплинк разменян на возможность быть кем-то реально важным, в идеале конечно можно было бы как-то отслеживать что условно говоря единственный офицер не импостор, но пока пускай будет так.

с капитаном и гсб-предателями возникает проблема с плёткой и её воздействием на офицеров, безусловный пермастан это не очень красиво но думаю это тривиально можно было бы пофиксить

пока-что ТМ посмотрим какие ещё "тупые" ситуации возникнут, если слишком много признаю что идея проклятая и не буду пушить её дальше.

2023-07-18 22:31 UTC, KIBORG04 commented on code/game/gamemodes/factions/traitors.dm
> +	max_roles = ..()
```suggestion
	..()
```
то же самое будет

2023-07-18 22:31 UTC, KIBORG04 commented on code/game/gamemodes/factions/traitors.dm
> +	log_debug("IMPOSTERS: [src] faction has [max_roles] limit of roundstart roles")
Зач в log_debug? Есть log_mode, лучше в него все это писать, думаю

2023-07-18 22:32 UTC, KIBORG04 commented on code/game/gamemodes/factions/traitors.dm
> +	log_debug("IMPOSTERS: Members ([members.len]) has enough people for current players amount ([player_list.len])")
Зач в log_debug? Есть log_mode, лучше в него все это писать, думаю

2023-07-21 18:01 UTC, Deahaka commented
Первый фидбек: очень мало импостеров. Зря я уменьшил в три раза надеясь что лейтджоином наберёт больше, надо подумать как сохранить фичу лейтспавна и при этом не делать мало импостеров если лейтспавнеров не будет.

2023-07-22 12:08 UTC, AndroBetel commented
стоит подкрутить шансы выпадения импостера кэпу сбшникам итд. ИМХО, так оно веселее будет и задумка ярче проявляться

2023-07-22 17:32 UTC, Deahaka commented
Обновил по первому фидбеку колличество трейторов. Теперь как автотрейторы доспавнятся в течении раунда. Подкрутил шанс на профы которые заспавнятся импостерами (в начале раунда).

Обновил по второму фидбеку шансы на задания. С ~90% шанса на стелсо-задачи стало ~70%

2023-07-22 18:27 UTC, Deahaka commented
Переписал импостеров на подтип автотрейторов, так как суть теперь у них крайне похожа, но только раундстартом появляются ещё.

2023-07-23 02:03 UTC, F0xiq commented
Нужна настройка в преференсах, чтобы можно было быть трейтором, но не быть импостером.

2023-07-23 03:26 UTC, Oz1Es commented
Дехака, лучше бы сделал разновидности агентов, а не компостеров

2023-07-23 05:38 UTC, Deahaka commented
> Нужна настройка в преференсах, чтобы можно было быть трейтором, но не быть импостером.

Это или после ПРа или в самый последний момент, так как затрагивает префы клиентов

2023-07-24 01:07 UTC, volas commented
> всё расписано в https://github.com/TauCetiStation/TauCetiClassic/pull/11741, правда не вся информация теперь актуальна и амбиции поменьше. Но главная идея запутать не меняется.

там какой-то длиннотекст, что проще и быстрее код читать. Просьба делать какой-то tl;dr, у тебя многим ПР-ам не хватает.

2023-07-24 09:50 UTC, MrWestnow commented
Дехака как обычно поел чего-то того

И думает что стелсотриторы выручат ситуацию с паТАУ.
Так ещё убиваешь доверие к импланту, который как раз таки давал OOC гарантию от много пула антагов

2023-07-24 10:04 UTC, Deahaka commented
Стелсотриторство конечно не то, что надо теперь в новом ПРе, но в любом случае не плохо. Второе это смысл ПРа, нах не нужна гарантия никакая, нужно никаких гарантий

2023-07-24 11:01 UTC, Mercurialaste commented
Дааа... Мб просто добавить отдельным режимом все триторы?

2023-07-25 21:18 UTC, Deahaka commented
Фидбек номер три: добавление роли тритора выдает импостора по схожему айди. 

Не вникал влияет ли айди наследника роли на префы желаемых ролей игроку, но возможно достаточно будет немного поменять трейтор панель, убрав перезаписывание для трейторов.

2023-07-25 21:19 UTC, Deahaka commented
Фидбек номер 4: банка биогеля не сравнится при выдаче импостера.

Связано с тем, что выдача банки лежит в компоненте аплинка, а не в самой роли, куда это можно было бы перенести. Что я и сделаю.

2023-07-26 13:11 UTC, Deahaka commented on code/game/gamemodes/factions/autotraitors.dm
> +		if(player.mind.assigned_role in unusual_position_list)
>2 Runtime in autotraitors.dm:115 : Cannot read null.assigned_role

Надо было вспомнить что не все хуманы это плееры

2023-07-27 08:50 UTC, Sourse101 commented on code/game/gamemodes/factions/autotraitors.dm
> +		if(player.mind.assigned_role in unusual_position_list)
Почему это говно не было обсуждено с педалями? Как это администрировать? Нахрена нужен капитан с лояльность, который может одной плеткой заробастить СБ, что за бред сумасшедшего?

2023-07-27 08:50 UTC, Sourse101 commented
Почему это говно не было обсуждено с педалями? Как это администрировать? Нахрена нужен капитан с лояльность, который может одной плеткой заробастить СБ, что за бред сумасшедшего?

2023-07-27 14:51 UTC, Deahaka commented
Цепь отключена, биогель выдаётся, щитспавн трейтор теперь получает всё как обычно.

2023-07-28 04:59 UTC, volas commented
Неделю в ТМ-е повисело, должно быть достаточно для обсуждения. Админы уже не очень рады были.

2023-07-28 15:57 UTC, Deahaka commented
Отключил автотрейторов в режим импостеров, так как конфликтуют айди фракций у них, а также фактически удваиваются антагонисты в числе. Достаточно будет увеличивать на ~3 каждый час. Добавил идентификацию лояльным импостерам по давней идее людука, путём создания фейк-импланта имитирующего худ лояльности, но не делая лояльным НТ субъекта. Убрал для глав-импостеров задачи на воровство предметов глав, так как хорошие шансы есть на выпадения совсем не конфликтующих со станцией задач (капитан с целью на собственный джетпак и капитанский пин-поинтер немного не cool). Обсудить с администрацией, которая была недовольна, проблемы и методы решения режима не удалось, пойду как-то накидаю идей на форум а там хз чё в итоге будет, центком доступен только админам.

2023-07-28 16:45 UTC, TauKitty commented
Этот запрос на слияние был упомянут в **Tau Ceti Station Forum**. Там могут быть соответствующие подробности:

https://forum.taucetistation.org/t/obsuzhdenie-pra-imposters-impostery-samozvanczy/40237/1

2023-08-11 17:14 UTC, Deahaka commented
Странно, я не нажимал ничего связанного с реквестом ревью. Ну ничего.

Понизил пробабилити до задуманных значений (если чаще чем пару раундов в неделю на первом будет, то стоит понизить до 50-60, на будущее. Добавил преф на импостера игрокам.

2023-08-11 17:23 UTC, LudwigVonChesterfield commented
ревью реквестнуло из-за системы кодовнеров файла. ты вероятно конфиги трогаешь

2023-08-26 12:33 UTC, Deahaka commented
Интересно соскучились ли игроки по ТМу режима?)

2023-09-04 07:16 UTC, Deahaka commented
Согласно последнему голосованию за режимы, не хуже ревы, культа и генокрадов. Спасибо!

2023-09-09 17:48 UTC, volas requested changes
админы вроде не сопротивляются, дело идет к мержу

2023-09-09 17:48 UTC, volas commented on code/game/gamemodes/factions/autotraitors.dm
> +	var/static/list/unusual_position_list = list("Cyborg", "Captain", "Blueshield Officer") + security_positions
аналогично, опять хардкод проф, было бы круто будь у datub/jobs просто флаги

2023-09-09 17:49 UTC, volas commented
и обнови описание нормально уже, типо офицер не мог быть трейтором а теперь может, ничего не понятно же сейчас что изменяется

2023-09-14 04:18 UTC, volas commented on code/__DEFINES/flags.dm
> +#define BRIG 1
лучше использовать более уникальные дефайны, типо JOB_FLAG_SECURITY - уже точно не пересечется ни с чем.

2023-09-21 05:32 UTC, volas approved these changes

2023-09-21 05:32 UTC, merged

2023-09-23 10:07 UTC, TgT4 commented
попрактиковался в целях на защиту которые падают киборгам.

и не понял в чём задумка? следовать как собака за кем-то постоянно? уговаривать врубить датчики?

постояннно типы ливают в крио, и цели постоянно меняются (особенно заметно в моменты падения онлайна ближе к ночи, один раз 6 целей сменилось на защиту)


может лучше законы вроде ионных-синдизлобных накидывать? вроде "помогай освободиться заключённым" или "всячески препятствуй работе сб"? или банально покалечить кого-нибудь?

2023-09-23 10:26 UTC, Deahaka commented
Тебе ж падал хиджак на борга, я видел по статистике. Просто 90% что силикон будет в конфликте с самими импостерами

2023-09-23 10:43 UTC, TgT4 commented
> Тебе ж падал хиджак на борга, я видел по статистике. Просто 90% что силикон будет в конфликте с самими импостерами

хиджак подразумевает действие по прилёту корыта. до этого момента как-бы делать нечего

2023-09-23 11:47 UTC, Deahaka commented
Ну если ты так и выполнял хиджак обджектив до этого, то я только могу развести руки. У меня получилось лишь один раз с истреблением всей станции где всё держалось на одном волоске от фейла.

2023-09-24 10:58 UTC, TgT4 commented
но вообще-то мне интересно было, в чем задумка цели на защиту. и как это в теории должно выглядеть

2023-10-03 20:14 UTC, TauKitty commented
Этот запрос на слияние был упомянут в **Tau Ceti Station Forum**. Там могут быть соответствующие подробности:

https://forum.taucetistation.org/t/golosovanie-fidbek-imposterov/40934/1

2023-10-11 17:01 UTC, TauKitty commented
Этот запрос на слияние был упомянут в **Tau Ceti Station Forum**. Там могут быть соответствующие подробности:

https://forum.taucetistation.org/t/ishod-imposterov/40975/1