Перевод, дополнение и добавление помощи при получении антага
TauCetiStation/TauCetiClassic pull request #11756
Opened 2023-07-21 06:33 UTC by Slavik2001

## Описание изменений
https://forum.taucetistation.org/t/minutki-na-roli/39490/32
По обсуждению решил перевести(?), дополнить и добавить больше информации при получении роли, да бы новые игроки могли по лучше понять что им нужно делать(возможно).
P.S.: Мои руки таки дотянулись до этого.
## Почему и что этот ПР улучшит
Новые игроки всегда есть и будут, но конечно же они не знаю и не понимают что им нужно делать при получении своей первой роли. Этот ПР даст больше информации для новичков что будет если тыкнуть красную кнопку
## Авторство
Я
## Чеинжлог
Переведено, дополнено и добавлен текст при получении роли

2023-07-21 06:33 UTC, TauKitty commented
###### Changelog status: :radio_button: No changelog

2023-07-21 06:35 UTC, Slavik2001 commented
Я так и не понял почему у культяпок Greetа нет, а у возвышенного зато он перекрывает пол чата(теперь и культяпок так же XD)

2023-07-21 06:46 UTC, TRISAGI0N commented on code/datums/components/gamemodes/syndicate.dm
> +		var/code_phrase = "<b>Кодовая фраза</b>: [codewords2string(global.syndicate_code_phrase)]"
Во первых, не фразы, а кодовые слова. Во вторых, слов несколько.

2023-07-21 06:47 UTC, TRISAGI0N commented on code/datums/components/gamemodes/syndicate.dm
> +			to_chat(traitor_mob, "Воспользуйтесь кодовыми сломавами в полученом вами порядке для индентификации других агентов в обычном разговоре. Будьте бдительны, все вокруг вас потенциальные враги.")
Тут очепятка в слове "сломавами"

2023-07-21 06:48 UTC, TRISAGI0N commented on code/datums/components/gamemodes/syndicate.dm
> +			to_chat(traitor_mob, "Воспользуйтесь кодовыми сломавами в полученом вами порядке для индентификации других агентов в обычном разговоре. Будьте бдительны, все вокруг вас потенциальные враги.")
Тут тоже очепятка!

2023-07-21 06:49 UTC, TRISAGI0N commented on code/datums/components/gamemodes/syndicate.dm
> +			to_chat(traitor_mob, "Синдикат к несчастью не может предоставить вам банку с биогелем для хранения голов.")
Запятые?

2023-07-21 06:49 UTC, maleyvich requested changes
какие-то ошибки мог упустить

2023-07-21 06:49 UTC, maleyvich commented on code/datums/components/gamemodes/syndicate.dm
> +			to_chat(traitor_mob, "Воспользуйтесь кодовыми сломавами в полученом вами порядке для индентификации других агентов в обычном разговоре. Будьте бдительны, все вокруг вас потенциальные враги.")
исправь ошибку в слове "словами" пожалуйста

2023-07-21 06:49 UTC, maleyvich commented on code/datums/components/gamemodes/syndicate.dm
> +			to_chat(traitor_mob, "Воспользуйтесь кодовыми сломавами в полученом вами порядке для индентификации других агентов в обычном разговоре. Будьте бдительны, все вокруг вас потенциальные враги.")
ну и тут аналогично

2023-07-21 06:49 UTC, maleyvich commented on code/datums/components/gamemodes/syndicate.dm
> +			to_chat(traitor_mob, "Синдикат к несчастью не может предоставить вам банку с биогелем для хранения голов.")
Синдикат, к несчастью, не может предложить вам банку с биогелем для хранения необходимой головы.

2023-07-21 06:49 UTC, maleyvich commented on code/game/gamemodes/roles/blob.dm
> +	to_chat(antag.current, "<span class='warning'>Если вы покините сектор станции, или улетите в космос, тогда вы умрете; убедитесь в том что ваше место имеет достаточно земли/пола чтобы закрепится на с
исправь покините на покинете

2023-07-21 06:49 UTC, maleyvich commented on code/game/gamemodes/roles/changeling.dm
> +	to_chat(antag.current, "<span class='danger'>Воспользуйтесь \":g message\" для комуникации с остальными Генокрадами. Помните: вы поглощаете все образцы ДНКа которые поглатила ваша жертва-генокрад.</
коммуникации, поглотила

2023-07-21 06:49 UTC, maleyvich commented on code/game/gamemodes/roles/changeling.dm
> +	to_chat(antag.current, "<span class='notice'>Мы Генокрад, существо из далеких уголков космоса. У нас есть задачи на эту станцию которые нужно выполнить используя свою сообразительность и при необход
Генокрад - существо из далёких уголков космоса. У нас есть задачи на эту станцию, которые нужно выполнить, используя свою сообразительность и при необходимости свои генетические возможности (возле вкладки Status  в право-верхней части экрана,  у вас должна появиться новая вкладка - Changeling, в которой можно приобрести новые мутации.

2023-07-21 06:49 UTC, maleyvich commented on code/game/gamemodes/roles/changeling.dm
> +		to_chat(antag.current, "Вы развились за пределы своей клоунской природы, что позволит вам пользоватся боевым вооружением без вреда для вас.")
вам что делать? пользоватЬся.

2023-07-21 06:49 UTC, maleyvich commented on code/game/gamemodes/roles/changeling.dm
> +		to_chat(changeling, "<span class='warning'>Поглощая так много заставило нас осознать что мы на полпути до перевоплощения в большую угрозу для всех - даже для самих себя. Мы должны быть более осторо
Поглощение многих генов, заставило нас осознать, что мы на полпути до перевоплощения в Абоминацию - большую угрозу для всех, даже для нас. Мы должны быть более осторожны в этом деле.

2023-07-21 06:49 UTC, maleyvich commented on code/game/gamemodes/roles/changeling.dm
> +		to_chat(changeling, "<span class='warning'>Мы ощущаем грань за которой находится еще более жестокое и нечеловеческое обличие - <B>и это необратимо</B>.</span>")
Мы ощущаем грань, за которой находится еще более жестокое и бесчеловечное обличие - и это необратимо.

2023-07-21 06:49 UTC, maleyvich commented on code/game/gamemodes/roles/changeling.dm
> +		to_chat(changeling, "<span class='danger'>Ощущение мутации по всему нашему телу, разрывание всего от прошлой оболочки, дополнительные конечности вырывающиеся из грудной клетки обножая на своих конц
Мы ощущаем глобальную мутацию нашего тела, мы забываем всё. Из грудной клетки просачиваются новые конечности, на их концах - смертоносные когти. Мы преобразились. Мы - АБОМИНАЦИЯ. Конец близится.

2023-07-21 06:49 UTC, maleyvich commented on code/game/gamemodes/roles/cultist.dm
> +	to_chat(antag.current, "<span class='cult'>Вы Культист поклоняющийся древнему злому богу Нар-Си. Вам была дарована потустороняя сила для достижения поставленых целей. Если вы их не выполните...</spa
Вы культист, поклоняющийся древнему богу Нар-Си. Вам была дарована потусторонняя  сила для достижения поставленных целей. Если вы их не выполните, то вас ждёт СТРАШНАЯ КАРА...

2023-07-21 06:49 UTC, maleyvich commented on code/game/gamemodes/roles/cultist.dm
> +	to_chat(antag.current, "<span class='cult'>Вам был дарован Том древних писаний культа. Открыв Том вы сможете начертить руны которые позволят вам телепортироватся, отправлять предметы или же себя в Р
Вам был дарован том древних писаний культа Нар-Си. Открыв том, вы сможете начертить различные руны, которые позволят вам: телепортироваться, отправляя различные предметы или себя в Рай, захватывать зоны станции, призывать невидимые барьеры и активировать древние кристаллы - пилоны, для быстрого уничтожения неверных.

2023-07-21 06:49 UTC, maleyvich commented on code/game/gamemodes/roles/revolution.dm
> +		to_chat(src, "<span class='warning'>Рядом с вами нет никого кто мог бы присоединиться к Революции.</span>")
Рядом с вами нет никого, кто захотел бы поддержать пламя Революции!

2023-07-21 06:49 UTC, maleyvich commented on code/game/gamemodes/roles/replicator.dm
> +	to_chat(antag.current, {"<span class='notice'><b>Вы Репликатор, часть Роя. Вы должны поглощать материалы, возводить свою инфраструктуру или использовать станционую для постройки Bluespace Catapult,
для постройки Блюспейс катапульты, которая распространит Рой дальше по галактике через трещину.

2023-07-21 06:49 UTC, maleyvich commented on code/game/gamemodes/roles/replicator.dm
> +	to_chat(antag.current, {"<span class='notice'><b>Вы Репликатор, часть Роя. Вы должны поглощать материалы, возводить свою инфраструктуру или использовать станционую для постройки Bluespace Catapult,
плюсом, ошибку в слове "станционную надо исправить)

2023-07-21 06:49 UTC, maleyvich commented on code/game/gamemodes/roles/shadowling.dm
> +	to_chat(antag.current, "<b>Другие Шедоулинги являются вашими братьями и союзниками. Вы должны помогать им, как и они вам, для достижения общей цели.</b>")
общатЬся с себе подобными братьями и рабами

2023-07-21 06:49 UTC, maleyvich commented on code/game/gamemodes/roles/wizard.dm
> +	to_chat(antag.current, "<B>Космическая Федерайия Магов отправила вас выполнить определенные цели:</B>")
Космическая Федерация Магов

2023-07-21 06:49 UTC, maleyvich commented on code/game/gamemodes/roles/wizard.dm
> +	var/newname = sanitize_safe(input(wizard_mob, "Вы Космический Волшебник. Желаете ли вы изменить свое имя?", "Name change", randomname) as null|text, MAX_NAME_LEN)
мне кажется, что лучше использовать прижившиеся на сервере слове МАГ

2023-07-21 06:49 UTC, maleyvich commented on code/game/gamemodes/roles/zombie.dm
> +	to_chat(antag.current, "Вы реанимированый, безмозглый, разлагающийся труп с чуством голода на человеческие мозги. Избегайте растений. Благодаря вашему голоду вы чуеете живые мозги")
чуете.

2023-07-21 06:51 UTC, TRISAGI0N commented
пиздец

2023-07-21 06:52 UTC, TRISAGI0N commented on code/game/gamemodes/roles/zombie.dm
> +	to_chat(antag.current, "Вы реанимированый, безмозглый, разлагающийся труп с чуством голода на человеческие мозги. Избегайте растений. Благодаря вашему голоду вы чуеете живые мозги")
и точку в конце!

2023-07-21 06:53 UTC, TRISAGI0N commented on code/game/gamemodes/roles/wizard.dm
> +	to_chat(antag.current, "<B>Космическая Федерайия Магов отправила вас выполнить определенные цели:</B>")
А может вообще Федерация Космо-Волшебников/Магов? :pekahmm:

2023-07-21 06:54 UTC, TRISAGI0N commented on code/game/gamemodes/roles/revolution.dm
> +		to_chat(src, "<span class='warning'>Рядом с вами нет никого кто мог бы присоединиться к Революции.</span>")
Ну тут малевич отсебятины навалил. Это не ошибка!

2023-07-21 06:56 UTC, Slavik2001 commented on code/datums/components/gamemodes/syndicate.dm
> +			to_chat(traitor_mob, "Воспользуйтесь кодовыми сломавами в полученом вами порядке для индентификации других агентов в обычном разговоре. Будьте бдительны, все вокруг вас потенциальные враги.")
Окей

2023-07-21 06:56 UTC, Slavik2001 commented on code/datums/components/gamemodes/syndicate.dm
> +			to_chat(traitor_mob, "Синдикат к несчастью не может предоставить вам банку с биогелем для хранения голов.")
Чего не предоставить?

2023-07-21 06:57 UTC, TRISAGI0N commented on code/game/gamemodes/roles/changeling.dm
> +		to_chat(changeling, "<span class='danger'>Ощущение мутации по всему нашему телу, разрывание всего от прошлой оболочки, дополнительные конечности вырывающиеся из грудной клетки обножая на своих конц
Вообще та не абоминация, а мерзость. 🤓

2023-07-21 06:58 UTC, TRISAGI0N commented on code/game/gamemodes/roles/changeling.dm
> +		to_chat(changeling, "<span class='warning'>Поглощая так много заставило нас осознать что мы на полпути до перевоплощения в большую угрозу для всех - даже для самих себя. Мы должны быть более осторо
Всё так же, не абоминация, а мерзость. 🤓

2023-07-21 06:59 UTC, AndroBetel commented on code/game/gamemodes/roles/zombie.dm
> +	to_chat(antag.current, "Вы реанимированый, безмозглый, разлагающийся труп с чуством голода на человеческие мозги. Избегайте растений. Благодаря вашему голоду вы чуеете живые мозги")
надмозг реанимированный мб просто оживший?

с чувством голода на человеческие мозги? это на аутсорс индусам перевод отдали? 

про растения непонятно вообще при чем тут, но это не с переводом связано

2023-07-21 07:00 UTC, AndroBetel commented on code/game/gamemodes/roles/wizard.dm
> +	var/newname = sanitize_safe(input(wizard_mob, "Вы Космический Волшебник. Желаете ли вы изменить свое имя?", "Name change", randomname) as null|text, MAX_NAME_LEN)
на вики действительно маг, поменять надо

2023-07-21 07:00 UTC, AndroBetel commented on code/game/gamemodes/roles/shadowling.dm
> +	to_chat(antag.current, "<b>Другие Шедоулинги являются вашими братьями и союзниками. Вы должны помогать им, как и они вам, для достижения общей цели.</b>")
продрочить всё что тут в ворде блядь, очень плохо!

2023-07-21 07:01 UTC, AndroBetel commented on code/game/gamemodes/roles/replicator.dm
> +	to_chat(antag.current, {"<span class='notice'><b>Вы Репликатор, часть Роя. Вы должны поглощать материалы, возводить свою инфраструктуру или использовать станционую для постройки Bluespace Catapult,
"трещену" в жопи

2023-07-21 07:01 UTC, AndroBetel commented on code/game/gamemodes/roles/cultist.dm
> +	to_chat(antag.current, "<span class='cult'>Вам был дарован Том древних писаний культа. Открыв Том вы сможете начертить руны которые позволят вам телепортироватся, отправлять предметы или же себя в Р
не знаю зачем тут перечисление половины рун, но дабы пишется слитно

2023-07-21 07:02 UTC, AndroBetel commented on code/game/gamemodes/roles/changeling.dm
> +		to_chat(changeling, "<span class='danger'>Ощущение мутации по всему нашему телу, разрывание всего от прошлой оболочки, дополнительные конечности вырывающиеся из грудной клетки обножая на своих конц
какие-то непонятки с повествованием в начале. малевич норм предложил

2023-07-21 07:03 UTC, Slavik2001 commented on code/game/gamemodes/roles/wizard.dm
> +	to_chat(antag.current, "<B>Космическая Федерайия Магов отправила вас выполнить определенные цели:</B>")
Можно.

2023-07-21 07:03 UTC, AndroBetel commented on code/game/gamemodes/roles/changeling.dm
> +		to_chat(antag.current, "Вы развились за пределы своей клоунской природы, что позволит вам пользоватся боевым вооружением без вреда для вас.")
боевое вооружение олсо новн эз маслянное масло

2023-07-21 07:03 UTC, Slavik2001 commented
Да

2023-07-21 07:04 UTC, AndroBetel commented on code/datums/components/gamemodes/syndicate.dm
> +			to_chat(traitor_mob, "Синдикат к несчастью не может предоставить вам банку с биогелем для хранения голов.")
тут реально предоставить лучше подходит, но запятые нужны

2023-07-21 07:04 UTC, AndroBetel commented
украинцы саботируют перевод

2023-07-21 07:07 UTC, Slavik2001 commented
Основная цель была дать больше информации новичкам что тыкать на рольке. Как пример культяпки. У них вообще не было ничего

2023-07-21 07:10 UTC, TRISAGI0N commented
Поменяй ченджлог на такой формат

🆑 

- localization: Переведён, дополнен и добавлен текст при получении роли.

2023-07-21 07:24 UTC, KandreyKandrey commented on code/datums/components/gamemodes/syndicate.dm
> +			to_chat(traitor_mob, "К сожалению, неудалось установить портативное телепортационное реле AntagCorp ни в Гарнитуру, ни в ПДА.")
'не удалось'

2023-07-21 07:25 UTC, KandreyKandrey commented on code/datums/components/gamemodes/syndicate.dm
> +			to_chat(traitor_mob, "К сожалению, неудалось установить портативное телепортационное реле AntagCorp ни в Гарнитуру, ни в ПДА.")
'не удалось'

2023-07-21 07:25 UTC, KandreyKandrey commented on code/datums/components/gamemodes/syndicate.dm
> +			to_chat(traitor_mob, "Не обнаружено подходящего Интеркома внутреней связи станции, установка портативного телепортационного реле AntagCorp в Гарнитуру!")
'внутренней'

2023-07-21 07:25 UTC, KandreyKandrey commented on code/datums/components/gamemodes/syndicate.dm
> +			to_chat(traitor_mob, "К сожалению, неудалось установить портативное телепортационное реле AntagCorp ни в Гарнитуру, ни в ПДА.")
'не удалось'

2023-07-21 07:27 UTC, TRISAGI0N commented
@Slavik2001 вот это прочитай: https://github.com/TauCetiStation/TauCetiClassic/blob/master/.github/wiki/STYLING_OF_PR.md

2023-07-21 07:27 UTC, KandreyKandrey commented on code/datums/components/gamemodes/syndicate.dm
> +			to_chat(traitor_mob, "К сожалению, неудалось установить портативное телепортационное реле AntagCorp ни в Гарнитуру, ни в ПДА.")
'не удалось'

2023-07-21 07:28 UTC, KandreyKandrey commented on code/datums/components/gamemodes/syndicate.dm
> +			to_chat(traitor_mob, "Портативное телепортационное реле, сокращёно - Аплинк, было установлено в [R.name] внутреней связи станции в районе [get_area(R)]. Просто переключитесь на нужную частоту [for
'сокращённо'
'внутренней'

2023-07-21 07:28 UTC, KandreyKandrey commented on code/datums/components/gamemodes/syndicate.dm
> +			traitor_mob.mind.store_memory("<B>Радио частота:</B> [format_frequency(freq)] ([R.name] [get_area(R)].")
'радиочастота' вроде слитно пишется

2023-07-21 07:30 UTC, KandreyKandrey commented on code/datums/components/gamemodes/syndicate.dm
> +			to_chat(traitor_mob, "Портативное телепортационное реле, сокращёно - Аплинк, было установлено в ваш [R.name] [loc]. Просто переключитесь на нужную частоту [format_frequency(freq)] для получения до
'сокращённо'

2023-07-21 07:32 UTC, KandreyKandrey commented on code/datums/components/gamemodes/syndicate.dm
> +			to_chat(traitor_mob, "Воспользуйтесь кодовыми словами в полученом вами порядке для индентификации других агентов в обычном разговоре. Будьте бдительны, все вокруг вас потенциальные враги.")
'полученном'

2023-07-21 07:33 UTC, KandreyKandrey commented on code/datums/components/gamemodes/syndicate.dm
> +			to_chat(traitor_mob, "Воспользуйтесь кодовыми словами в полученом вами порядке для индентификации других агентов в обычном разговоре. Будьте бдительны, все вокруг вас потенциальные враги.")
'полученном'

2023-07-21 07:34 UTC, KandreyKandrey commented on code/game/gamemodes/roles/blob.dm
> +	to_chat(antag.current, "<span class='warning'>Найдите хорошее место для создания ядра после чего взять контроль и захлестнуть станцию!</span>")
что-то тут не то

2023-07-21 07:35 UTC, Slavik2001 commented on code/game/gamemodes/roles/blob.dm
> +	to_chat(antag.current, "<span class='warning'>Найдите хорошее место для создания ядра после чего взять контроль и захлестнуть станцию!</span>")
Теряется смысл текста?

2023-07-21 07:43 UTC, BlankCringe commented on code/game/gamemodes/roles/shadowling.dm
> +	to_chat(antag.current, "<b>Другие Шедоулинги являются вашими братьями и союзниками. Вы должны помогать им, как и они вам, для достижения общей цели.</b>")
где запятая?

2023-07-21 07:44 UTC, KandreyKandrey commented on code/game/gamemodes/roles/blob.dm
> +	to_chat(antag.current, "<span class='warning'>Найдите хорошее место для создания ядра после чего взять контроль и захлестнуть станцию!</span>")
я не про смысл
'найдите хорошее место, после чего возьмите контроль'
'найти хорошее место, после чего взять контроль'

или обращение к игроку, или без обращения

а тут перемешивается

2023-07-21 07:46 UTC, KandreyKandrey commented on code/game/gamemodes/roles/blob.dm
> +	to_chat(antag.current, "<span class='warning'>Если вы покинете сектор станции, или улетите в космос, тогда вы умрете; убедитесь в том что ваше место имеет достаточно земли/пола чтобы закрепится на с
'убедитесь в том, что ваше место имеет достаточно земли, чтобы закрепиться'  (запятые)

2023-07-21 07:51 UTC, Slavik2001 commented on code/game/gamemodes/roles/blob.dm
> +	to_chat(antag.current, "<span class='warning'>Если вы покинете сектор станции, или улетите в космос, тогда вы умрете; убедитесь в том что ваше место имеет достаточно земли/пола чтобы закрепится на с
Может тогда вместо земли "Твердой поверхности"?

2023-07-21 07:55 UTC, KandreyKandrey commented on code/game/gamemodes/roles/blob.dm
> +	to_chat(antag.current, "<span class='warning'>Если вы покинете сектор станции, или улетите в космос, тогда вы умрете; убедитесь в том что ваше место имеет достаточно земли/пола чтобы закрепится на с
земля только в саду вроде, во всех остальных местах плитка

2023-07-21 07:56 UTC, KandreyKandrey commented on code/datums/components/gamemodes/syndicate.dm
> +			to_chat(traitor_mob, "К сожалению, не удалось установить портативное телепортационное реле AntagCorp ни в Гарнитуру, ни в ПДА.")
почему 'гарнитура' с большой буквы посередь предложения?

2023-07-21 08:01 UTC, Slavik2001 commented on code/datums/components/gamemodes/syndicate.dm
> +			to_chat(traitor_mob, "К сожалению, не удалось установить портативное телепортационное реле AntagCorp ни в Гарнитуру, ни в ПДА.")
В моей голове, на то время, это было как акцентирование внимания

2023-07-21 08:03 UTC, KandreyKandrey commented on code/datums/components/gamemodes/syndicate.dm
> +			to_chat(traitor_mob, "К сожалению, не удалось установить портативное телепортационное реле AntagCorp ни в Гарнитуру, ни в ПДА.")
акцентирование - ладно
правила русского языка такого вроде не допускают

2023-07-21 08:04 UTC, KandreyKandrey commented on code/game/gamemodes/roles/zombie.dm
> +	to_chat(antag.current, "Вы реанимированый, безмозглый, разлагающийся труп с чуством голода на человеческие мозги. Избегайте растений. Благодаря вашему голоду вы чуете живые мозги.")
'чувством'

2023-07-21 08:05 UTC, KandreyKandrey commented on code/game/gamemodes/roles/wizard.dm
> +	to_chat(wizard_mob, "<span class='info'>У вас в карманах вы сможете найти Свиток Телепортации, который телепортирует вас в указаное место под покровом дыма. Используйте его при надобности.</span>")
'указанное'

2023-07-22 22:20 UTC, Naroke commented on code/game/gamemodes/roles/revolution.dm
> +		to_chat(src, "<span class='warning'>Рядом с вами нет никого кто мог бы присоединиться к Революции.</span>")
Так, как написал малевич, звучит даже лучше

2023-07-29 13:57 UTC, Slavik2001 commented
Вроде решил вопросы с нетом, снова перепроверил всё и вроде ничего не пропустил. Если есть дополнения к подсказкам, то прошу писать здесь.

2023-08-04 10:44 UTC, Ambassadoing commented on code/datums/components/gamemodes/syndicate.dm
> +			to_chat(traitor_mob, "Гарнитура не обнаружена, установка портативного телепортационного реле AntagCorp в ПДА!")
В КПК, мать вашу, в КПК!

2023-08-04 11:22 UTC, Ambassadoing commented on code/datums/components/gamemodes/syndicate.dm
> +			to_chat(traitor_mob, "К сожалению, не удалось установить портативное телепортационное реле AntagCorp ни в гарнитуру, ни в ПДА.")
Опять эти ваши ПДА.

2023-08-04 16:05 UTC, Slavik2001 commented on code/datums/components/gamemodes/syndicate.dm
> +			to_chat(traitor_mob, "К сожалению, не удалось установить портативное телепортационное реле AntagCorp ни в гарнитуру, ни в ПДА.")
А чем ПДА хуже КПК? Смысл же 1.
Мне лично прижилось "ПДА" еще с Сталкера в детстве

2023-08-09 06:34 UTC, Slavik2001 commented on code/datums/components/gamemodes/syndicate.dm
> +			to_chat(traitor_mob, "К сожалению, не удалось установить портативное телепортационное реле AntagCorp ни в гарнитуру, ни в ПДА.")
А

2023-08-17 07:12 UTC, Slavik2001 commented on code/game/gamemodes/roles/blob.dm
> +	to_chat(antag.current, "<span class='warning'>Найдите хорошее место для создания ядра, после чего возьмите контроль и захлестните станцию!</span>")
Заразите станцию?
Разраститесь по всей станции?
Мне просто не нравится использовать "Захватите", так как блоб это огромный организм который не может передвигаться обычным образом(как хуманы). Но если брать что данный Гриит обращается к самому игроку...

2023-08-17 08:31 UTC, closed without merging