добавляет играбельную расу вульпканин
TauCetiStation/TauCetiClassic pull request #11753
Opened 2023-07-19 21:26 UTC by Fx43t2nm

## Описание изменений
![vulp](https://github.com/TauCetiStation/TauCetiClassic/assets/109123932/3d66f1bc-35b1-4f61-9fd3-f91d6d36f06a)

**_добавляет играбельную расу вульп_**

фишки:
• модификатор берна 1.5
• открыты все профессии
• найтвижн
• когти
• может поедать симплмобов
## Почему и что этот ПР улучшит
долгожданная раса повысит онлайн на сервере
## Авторство
порт с fluffy frontier
## Чеинжлог
:cl: WetSkrell
rscadd: Добавлена новая раса антропоморфных лис.

2023-07-19 21:26 UTC, TauKitty commented
###### Changelog status: :x: Empty changelog (check markdown correctness)

2023-07-19 21:40 UTC, Mercurialaste commented
https://www.youtube.com/watch?v=oX4QN2am6G8

2023-07-19 22:14 UTC, liteyzz commented
дизлайк

2023-07-19 22:38 UTC, AndroBetel commented
а хвост где

2023-07-19 22:43 UTC, AndroBetel requested changes
без хвоста нельзя

2023-07-19 22:44 UTC, ViDLiathan commented
Кидан хотя бы в лоре есть. А это кто и откуда? Капитаном можно будет?????

2023-07-19 22:47 UTC, AndroBetel requested changes

2023-07-19 22:47 UTC, AndroBetel commented on code/modules/mob/living/carbon/species.dm
> -	siemens_coefficient = 1.3 // Because they are wet and slimy.
куда

2023-07-19 22:47 UTC, AndroBetel commented on code/modules/mob/living/carbon/species.dm
> +		O_LUNGS   = /obj/item/organ/internal/lungs/skrell,
почмеу скрелл

2023-07-19 22:58 UTC, KIBORG04 requested changes
Ставлю прифаером крестик, я не думаю, что нужно добавлять на тау больше рас

2023-07-19 23:06 UTC, Fx43t2nm commented
> без хвоста нельзя

после мержа будет сопутствующий контент в виде батплагов

2023-07-19 23:21 UTC, Snailcat commented
Добавьте расу "мне похуй" пожалуйста.

2023-07-20 05:21 UTC, DarkFurrSss commented
Спрайт фиговый

2023-07-20 05:47 UTC, Fx43t2nm commented
просьба не дизлайкать пр скоро будет добавлена новая фишка расы отсутствие вайтлиста чтобы взорвать онлайн

2023-07-20 06:06 UTC, Rumpiturs commented
Что за фигня? Это сговор или что? Почему за два дня так много Пров с ксеносами То им даём больше свободы выбора для профессий, то добавляем новые рассы, которые нафиг нам не нужны! У нас есть таяры, которые на этих "Вульп" похожи и лучше смотрятся. Какой ксенос укусил кодеров, что они дают больше послаблений для чёртовых ксеносов.

2023-07-20 08:26 UTC, Polotos commented
Где верёвка и мало в локаута?

2023-07-20 08:41 UTC, TauKitty commented
Этот запрос на слияние был упомянут в **Tau Ceti Station Forum**. Там могут быть соответствующие подробности:

https://forum.taucetistation.org/t/dobavlenie-v-proekt-vulpy-na-tauceti/24712/35

2023-07-20 11:17 UTC, Ro2tCrab commented
Ебейший стыд

2023-07-20 13:19 UTC, pro100kotah commented
Что это за крыса

2023-07-20 16:01 UTC, AzzyDreemurr13 commented
Спрайт хрень, давай по новой

2023-07-20 18:31 UTC, Fx43t2nm commented
когда другие кодеры делают вброс их мержат но вот когда я

2023-07-20 18:31 UTC, closed without merging

2023-07-20 19:40 UTC, arygal commented
они просто не поняли что это шутка, даже после:
• открыты все профессии

2024-01-28 11:26 UTC, TauKitty commented
Этот запрос на слияние был упомянут в **Tau Ceti Station Forum**. Там могут быть соответствующие подробности:

https://forum.taucetistation.org/t/fludilka-chast-2/28659/31002