Респрайт клинботов
TauCetiStation/TauCetiClassic pull request #11766
Opened 2023-07-24 05:25 UTC by TRISAGI0N

## Описание изменений
Перерисовал клинботов и привёл к палитре:
![изображение](https://github.com/TauCetiStation/TauCetiClassic/assets/127397187/2f18c60c-7521-46bf-9638-3cdef1cc92c2)

## Почему и что этот ПР улучшит
Красиво
## Авторство
Я
## Чеинжлог
🆑 

- image: Клинботы теперь в палитре.

2023-07-24 05:25 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2023-07-24 05:45 UTC, UDaV73rus commented
накидать блеска на старый спрайт, врятли имеет смысл

2023-07-24 05:57 UTC, TRISAGI0N commented
Какого блеска, ты старый спрайт видел то?
![изображение](https://github.com/TauCetiStation/TauCetiClassic/assets/127397187/db688681-e1d5-4103-a19b-7be64b8d11f5)

2023-07-24 05:59 UTC, DarthSidiousPalpatine commented
Рил начистил до блеска.

2023-07-24 06:01 UTC, TRISAGI0N commented
Да какой блин начистил, он несильно ярче же стал, яркие части там же, тёмные там же!

2023-07-24 09:37 UTC, Naroke commented
Ну, выглядит конечно странно, хотя это скорее всего из-за того, что видим мы этот спрайт первый раз. В любом случае альтернативы нет, а старые спрайты оставлять лучше не надо

2023-07-24 14:27 UTC, TRISAGI0N commented
Ей богу, лучше бы чем искали параллели с гандонами и советскими горшками, сами респрайтили бы что то. :pekaface:

2023-08-04 10:44 UTC, WatlerJe commented
Спрайт получился слабый, не сильно далеко ушел от оригинала, даже зачем-то приобрел аутлайн.

К тому же если это респрайт клинбота который делается из ведра, то где респрайт ведра? Пролистай интернеты на наличие референсов и изучи их. Такой спрайт я пропустить не могу.

2023-08-04 10:46 UTC, WatlerJe requested changes
Слабо выполненный спрайт, присутствует аутлайн. Так же требуется респрайт ведра из которого бот собственно и делается. 

Автору следует пролистать интернеты на наличие референсов и изучить их (Пинтрест в помощь). Такой спрайт я пропустить не могу.

2023-08-06 23:51 UTC, closed without merging