Добавление инструкции и списка песен к джукбоксу
TauCetiStation/TauCetiClassic pull request #11802
Opened 2023-07-30 10:57 UTC by KatoMarika

## Описание изменений
Добавляет гайд\ссылку на вики ингейм на https://wiki.taucetistation.org/Jukebox
## Почему и что этот ПР улучшит
Гайд содержит в себе базовое описание джука и что важнее: список песен в плейлистах. Избавит менторов\админов от вопросов А ГДИЕ СПЕЙСАСХОЛЕ
## Авторство
Yastark
## Чеинжлог
:cl: Добавлен гайд по джукбоксу

2023-07-30 10:57 UTC, TauKitty commented
###### Changelog status: :x: Empty changelog (check markdown correctness)

2023-07-31 12:51 UTC, simb11 commented
а чего только на бокстейшн добавил мануал?

2023-07-31 13:56 UTC, KatoMarika commented
> а чего только на бокстейшн добавил мануал?
Действительно, исправил. 
На гамму не стал по причине скорого реворка.

2023-08-03 05:22 UTC, volas requested changes
нужно исправить maps/delta/delta.dmm, по диффу слишком много изменений. Вероятно косяк с мержем или что-то еще.

2023-08-03 05:58 UTC, KatoMarika commented
> нужно исправить maps/delta/delta.dmm, по диффу слишком много изменений. Вероятно косяк с мержем или что-то еще.

Там было изменение зоны бара для работы джука, ибо барная зона проходила только для бармена, т.е. зона с посетителями относилась к фудкорду, а бармен с джуком стояли в зоне бара. И перенос апц в подсобку бара для работы подсобки следовательно и шатание проводов. Или с учетом этого тоже есть проблемы?

2023-08-03 05:59 UTC, volas commented
https://affectedarc07.blob.core.windows.net/mdb2/images/55870442/15486764255/m/maps_delta_delta/0-diff.png

тут видно, что это не только бар задело

2023-08-03 06:15 UTC, KatoMarika commented
> тут видно, что это не только бар задело
Из-за #11723 может конфликтовать?

2023-08-03 06:27 UTC, volas commented
тут не конфликт, а скорее неправильно резолвнутый конфликт, но да - может оно.

2023-08-03 18:09 UTC, volas approved these changes

2023-08-03 18:09 UTC, merged