Респрайт формы адвоката
TauCetiStation/TauCetiClassic pull request #11820
Opened 2023-08-03 13:44 UTC by TRISAGI0N

## Описание изменений
До:
![изображение](https://github.com/TauCetiStation/TauCetiClassic/assets/127397187/0a46dc9a-5aa1-40dd-a7ac-ec24c7d753ac)
![изображение](https://github.com/TauCetiStation/TauCetiClassic/assets/127397187/a5e1ef42-bed5-49f6-8a79-dcc38b90ff6b)

После:
![изображение](https://github.com/TauCetiStation/TauCetiClassic/assets/127397187/d22652a3-faf9-4297-9197-44a214b51330)
![изображение](https://github.com/TauCetiStation/TauCetiClassic/assets/127397187/910284ce-b597-42fc-bad9-1a75966e7f20)

## Почему и что этот ПР улучшит
Красиво
## Авторство
Maleyvich нарисовал
Я подкорректировал
## Чеинжлог
:cl:

- image: Обновлённые спрайты формы адвоката

2023-08-03 13:47 UTC, TRISAGI0N commented
Главное достоинство респрайта:
![изображение](https://github.com/TauCetiStation/TauCetiClassic/assets/127397187/ccee1e2d-f293-4912-b6cc-cae9d00ca144)
![изображение](https://github.com/TauCetiStation/TauCetiClassic/assets/127397187/dd3f8f40-113a-45e4-a21d-82321cba630e)

2023-08-03 14:07 UTC, Tobyyyan commented
вы как биба и боба, ей богу

2023-08-03 14:08 UTC, UDaV73rus commented
Пиджак типо в задницу зажевало?

2023-08-03 14:08 UTC, TRISAGI0N commented
Да.

2023-08-04 15:38 UTC, WatlerJe requested changes
Начинайте привыкать к палитрам Splendor и Aurora, цветов и оттенков в них более чем достаточно. Подбери цвета по палитрам и будет ок.

2023-08-06 23:51 UTC, closed without merging

2023-08-06 23:55 UTC, TRISAGI0N commented
суууука