Респрайт мусорно-почтовой системы
TauCetiStation/TauCetiClassic pull request #11848
Opened 2023-08-05 20:39 UTC by BartNixon

## Описание изменений

**Было:**
![0986](https://github.com/TauCetiStation/TauCetiClassic/assets/9289619/a9da744e-846f-4aad-9896-76477b8e2de9)

**Стало:**
![0987](https://github.com/TauCetiStation/TauCetiClassic/assets/9289619/27296380-4f7b-4300-8b34-9ef9f505c40d)

## Почему и что этот ПР улучшит

Приводит в один стиль все три устройства соединённых с трубами: мусорку, впускной и выпускной механизмы.

Более яркие стрелки на самих трубах

Позволяет мапперам и игрокам в самой игре ставить трубы с надписью trash или логотипом нанотрасен (просто поверните прямую секцию трубы нужном направлении и при появлении надписи - приварите к полу)

Исправляет артефакты оригинала, которые были вызваны ресайзом (лишние полутона, невидимые цвета):
![bad](https://github.com/TauCetiStation/TauCetiClassic/assets/9289619/b65c6b0c-beb5-491b-a060-6bce407f60c6)

Сокращает палитру с 200+ цветов до 20, при том что перекрасу и респрайтингу подданы 30 спрайтов.
![compare-1](https://github.com/TauCetiStation/TauCetiClassic/assets/9289619/4cea674b-26a2-48d7-bf9d-9b35aaedb68b)

Палитры труб полностью соответствуют актуальным стандартам:
![Palette-Aurora](https://github.com/TauCetiStation/TauCetiClassic/assets/9289619/b6ad7663-3be8-41bf-8f87-847d9b98a7a8)
![Palette-Splendor](https://github.com/TauCetiStation/TauCetiClassic/assets/9289619/33f3536a-9475-47cd-9bce-dd4341ef4b3b)

## Авторство

BartNixon

## Чеинжлог
🆑

- image: Новые спрайты мусорных труб и сопутствующего оборудования.

2023-08-05 20:39 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2023-08-05 20:44 UTC, Chip11-n commented
Трубы явно стали лучше, но вот остальное какое-то блеклое, незаметное, много деталей, но тем не менее не могу с уверенностью сказать, что стало лучше. Хотя я не спрайтер, так что...

2023-08-06 07:08 UTC, DarkFurrSss commented
Лучше стало однозначно, но если и переделывать, то надо сразу все![Screenshot_2023-08-06-10-06-54-886_com.opera.gx-edit.jpg](https://github.com/TauCetiStation/TauCetiClassic/assets/92409383/e1912827-532a-4cce-9a27-5f6f6dec0925)

2023-08-06 10:37 UTC, BartNixon commented
> Лучше стало однозначно, но если и переделывать, то надо сразу все![Screenshot_2023-08-06-10-06-54-886_com.opera.gx-edit.jpg](https://user-images.githubusercontent.com/92409383/258626697-e1912827-532a-4cce-9a27-5f6f6dec0925.jpg)

Разумное замечание.
Я только-что полностью обновил картинки превью чтобы было понятней что к чему.

До меня дошло что я не добавил на превью иконки труб взятых из раздатчика (которые ещё не приварены к полу) и технические модули которые на карте встречаются в единичном экземпляре которые игрок не может построить, так как у них более сложные опции на уровне переменных которые возможно изменить только через редактор (автоматический маркировщик посылок - одинарного или двойного прохода) или нельзя ставить на карту больше одного такого объекта (труба-сканнер грузторга). На сегодняшних превьюшках стиль очевидней.

Чтобы технические сортировочные модули отличались от обычных не-сортирующих труб, у них осталась подложка под стрелку или символ, как это было на старых трубах.

На следующем этапе, после обновления спрайтов планируется расширить код самой системы - чтобы можно было дотягивать почтовую систему куда угодно без необходимости делать полный круг из труб по всей Станции для альтернативных карт или той-же шахтёрки, или например достигать удалённых отсеков посредством вот такой штуки:
![new](https://github.com/TauCetiStation/TauCetiClassic/assets/9289619/4bb114b0-f2d2-4b59-ac00-91c97c7188e6)

_До расширения функционала в коде правда дожить бы ещё._

Кто внимательно сравнивает то что было до и после, заметит что формы самих труб не изменились вовсе, поменялся только тип распределения цветов чтобы палитру сократить и исправить ошибки 10+ летней давности, даже устройства практически не изменились, все прошлые дизайнерские решения сохранились и может слегка дополнились где направление спиной.

Я увы не профессиональный спрайтер, и мне ещё очень много практиковаться чтобы достичь уровня Вальтера или Удава, но всякая практика полезна.

Помню еще оригинальные мусорки, они были такими-же ярко белыми с бирюзовым отливом как и раздатчики, думаю их еще можно увидеть на каком-нибудь ТГ или на видео десятилетней давности.
Мусорку перерисовал Вальтер где-то в 2017 году если не ошибаюсь, теперь под неё подтянулись все остальные спрайты.

Забавно что я уже второй раз трубы перерисовываю, первый раз был ради мемов:
https://youtu.be/0nYGnGHHrRU?t=33

На радость щитспавнерам, иконки из видео сохранились:
https://drive.google.com/file/d/1bW84jSGYwRa2OQJIfs469qg8XM7rBJtW/view?usp=drive_link

2023-08-10 11:25 UTC, WatlerJe requested changes
Требуется респрайт под новые полы и стены (когда они будут готовы).

2023-08-27 21:51 UTC, volas commented
респрайт готов, но Барта видимо опять ИРЛ засосало

2023-09-18 02:02 UTC, closed without merging

2023-09-21 17:50 UTC, volas commented
К сожалению так получилось, что Вальтер параллельно тоже работал над трубами, и их смержили вперед в #12097

Эти тоже в чем-то хороши на мой взгляд, но если открывать - нужно будет пересматривать вопрос заново.