кртм пдлгнртр н клк н нг
TauCetiStation/TauCetiClassic pull request #11913
Opened 2023-08-16 10:10 UTC by DarthSidiousPalpatine

## Описание изменений
Крутим педальген не кликая на него.

## Почему и что этот ПР улучшит
Спасите наши мышки.

## Авторство
AndreyGysev и никто не помогал мне в дискорде.

## Чеинжлог
 :cl:
  - tweak: Педальген крутится от движения как было задумано.

2023-08-16 10:10 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2023-08-16 13:40 UTC, juighty commented
делай нормальные названия пожалуйста

2023-08-16 13:44 UTC, TRISAGI0N commented
Норм название

2023-08-16 14:03 UTC, Tap0r commented
нрм нзвн :+1:

2023-08-16 14:20 UTC, LudwigVonChesterfield commented on code/modules/sports/PedalGen.dm
> +			buckled_mob.nutrition -= 0.5
а почему не хуманы не должны от етого голодать

2023-08-16 14:21 UTC, DarthSidiousPalpatine commented on code/modules/sports/PedalGen.dm
> +			buckled_mob.nutrition -= 0.5
А они могут голодать разве?

2023-09-06 15:27 UTC, DarthSidiousPalpatine commented
@volas когда мерж?

2023-09-06 15:28 UTC, volas requested changes
длнм фыол павлдн

2023-09-09 17:56 UTC, volas commented
я не буду разбираться в твоих шифровках, кто нибудь может пересоздать с нормальным оформлением если это что-то важное

2023-09-09 17:56 UTC, closed without merging