грузторг консоли в отделы
TauCetiStation/TauCetiClassic pull request #11926
Opened 2023-08-17 21:43 UTC by DarthSidiousPalpatine

## Описание изменений
Грузторг консоли. Расставил их по ресепшнам, складам, кабинетам глав и всяким таким местам где сидят челы в отделах.
Консоли подключены мапперской магией ко счетам конкретных отделов. Они имеют одну корзину отдела и всякое такое.
Пока что реквест консоли не удалены.

Скрины всякие:
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/21008918/d630cbe8-9024-4933-8b0c-b7edf7877574)
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/21008918/c5ea5297-5378-46a5-95bc-2733eeb1aa8d)
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/21008918/b0f6b1dc-8ebc-4d58-829a-4716de4f1aaa)

P.s. Интерфейс наноуи, потому что делать отдельный тгуи интерфейс для грузторга когда в кпк наноуи - кринж. Обновлю до тгуи, когда кпк станет тгуи.
## Почему и что этот ПР улучшит
Интегрируем грузторг ещё сильнее в жизнь и работу станции.

## Авторство
AndreyGysev и никто не помогал мне в дискорде. Кроме Людука.

## Чеинжлог
 :cl:
  - rscadd: Добавлена консоль грузторга в отделах.

2023-08-17 21:43 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2023-08-17 21:55 UTC, KandreyKandrey commented on code/game/machinery/computer/shop.dm
> +	var/mob/user = usr
в чем разница между 'user' и 'U' ?

2023-08-17 21:56 UTC, DarthSidiousPalpatine commented on code/game/machinery/computer/shop.dm
> +	var/mob/user = usr
Один ливинг, один просто моб. Я написал что я не рефакторил особо наноуи код КПК. Это, по сути, полная копия интерфейса грузторга в КПК.

Я всё ещё не сел нормально за полной переделкой КПК на ТГУИ. Надеюсь, закончить когда-нибудь.

2023-08-17 21:58 UTC, DarthSidiousPalpatine commented
Оно всё, возможно, немного костыльно, я когда проснусь пройдусь посмотрю что можно сделать лучше. Но я бы очень не хотел сильно трогать наноуи интерфейс потому как если это говно мамонта работает - лучше не трогать.

2023-08-18 02:45 UTC, LudwigVonChesterfield commented on nano/templates/shop.tmpl
> +	<div class="item">
Мы точно не можем каким-то образом иметь один интерфейс для обоих?

2023-08-18 02:46 UTC, LudwigVonChesterfield commented on code/game/machinery/computer/shop.dm
> +/obj/machinery/computer/shop/proc/add_order_and_offer(Text)
Возможно это стоит сделать глобальной функцией? Дублирует код у ПДА такой же

2023-08-18 02:47 UTC, LudwigVonChesterfield commented on code/game/machinery/computer/shop.dm
> +/obj/machinery/computer/shop/proc/check_pda_server()
Я не знаю или в рамках этого ПР-а.

Но я бы наверное сделал чтобы система ГрузТорга работала до тех пор пока на станции есть карго консоль, а не сервера ПДА

почему? потому-что сейчас можно сломать консоль карго и грузторг дальше будет работать но никто заказы не будет видеть)

2023-08-18 02:47 UTC, LudwigVonChesterfield commented on code/game/machinery/computer/shop.dm
> +/obj/machinery/computer/shop/Topic(href, href_list)
Было бы круто каким-то образом не копипастить всё это.

Пока нет идей кроме как сделать ГрузТорг отдельным датумом что-ли которому дать все эти функции...

Или возможно чтобы счёт это обрабатывал?

2023-08-18 02:49 UTC, LudwigVonChesterfield requested changes
из больших изменений - думаю надо как-то трекать *кто* заказал через консоль.

если кто-то и будет абузить счёт надо иметь возможность его отследить и наказать я думаю.

2023-08-18 06:20 UTC, DarthSidiousPalpatine commented on code/game/machinery/computer/shop.dm
> +/obj/machinery/computer/shop/Topic(href, href_list)
Когда я ПДА на тгуи допилю - все "программы" будут, как раз, отдельными датумами.

2023-08-18 06:31 UTC, DarthSidiousPalpatine commented
Так, что сделал:
1) Убрал лишний U, оставил user
2) Переделал грузторг на требование наличия консоли карго и сделал это глобальным проком
3) Написал в комментарий к заказу через консоль имя человека
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/21008918/18f48088-7a18-4298-bde8-c46d5ef1840d)

2023-08-18 06:37 UTC, DarthSidiousPalpatine commented on nano/templates/shop.tmpl
> +	<div class="item">
Точно нет. Пока это наноуи - нет. Когда я уже тгуи кпк допилю будет всё заебись, там, наверное, вообще не надо будет умирать.

2023-08-18 08:06 UTC, DarthSidiousPalpatine commented
Мне не понравилось как это пишется в комменте к заказу и понял что я могу просто в поле "заказавший" в скобках написать кто. так лучше будет.

2023-08-18 08:12 UTC, DarthSidiousPalpatine commented
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/21008918/76fbc928-a389-4062-98c5-1e2feac5f5ed)

2023-08-18 09:25 UTC, DarthSidiousPalpatine commented
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/21008918/c06739dd-66f2-43f9-9f87-3d027daa12bc)
Изменил спрайт.

2023-08-18 16:41 UTC, BlankCringe commented
можно сделать так чтобы через эту консоль кроме всего просто так в карго заказы закидывать?

2023-08-18 21:04 UTC, LudwigVonChesterfield commented on code/game/machinery/computer/shop.dm
> +/obj/machinery/computer/shop/ui_interact(mob/user, ui_key = "main", datum/nanoui/ui = null, force_open = 1)
@volas Может ты подскажешь

Есть какой-то способ наноуи реюзать? Потому-что сейчас тут копипаста из ПДА, но в ПДА оно всё так тесно связано с остальным ПДА фичами что я и не знаю как можно...

Типо я уже обсуждал с Гисевым что можно было бы ГрузТорг в отдельном окне открывать и с ПДА и с этого компьютера, но мы пришли к выводу что это как-то муторно для ПДА тогда получается что у тебя два окошка.

Если нет какого-то лёгкого фикса для такого то ну лично я бы закрыл глаза на копипасту но хочу ещё услышать твой совет.

2023-08-18 21:15 UTC, LudwigVonChesterfield commented on code/game/machinery/computer/shop.dm
> +/obj/machinery/computer/shop/ui_interact(mob/user, ui_key = "main", datum/nanoui/ui = null, force_open = 1)
```
/datum/browser/shop/proc/get_page(state)
  return в зависимости от состояния ГрузТорга страница

/datum/browser/shop/proc/handle_topic(href, href_list)

/obj/pda
  /datum/browser/shop/shop

/obj/pda/Topic()
  if(state == shop)
    shop.handle_topic()

/obj/computer/shop
  /datum/browser/shop

/obj/computer/shop/Topic()
  shop.handle_topic()
```

я к примеру что-то такого рода думаю

2023-08-27 22:49 UTC, volas commented on code/game/machinery/computer/shop.dm
> +/obj/machinery/computer/shop/ui_interact(mob/user, ui_key = "main", datum/nanoui/ui = null, force_open = 1)
в том же окне вряд ли, разве что оформить компонентой и переиспользовать

2023-09-13 13:44 UTC, DarthSidiousPalpatine commented
Жестко доделываем фичи

2023-09-14 03:32 UTC, TauKitty commented
Этот запрос на слияние был упомянут в **Tau Ceti Station Forum**. Там могут быть соответствующие подробности:

https://forum.taucetistation.org/t/tau-ceti-build-obsuzhdenie/37327/73

2023-10-01 17:59 UTC, LudwigVonChesterfield approved these changes
Я бы хотел когда-нибудь увидеть это в игре,

Из замечаний тут всё ещё адская дупликация кода, вопреки предложению как это исправить... Лично я готов на такого рода тех борг учитывая что ПДА вероятно никогда и не перепилят чтобы сделать "хорошо"

Лично я не понимаю зачем оставлять эти консоли рядом с старыми реквест консолями, но если это смягчит переход готов на такой компромисс, пока-что.

2023-10-08 14:26 UTC, volas commented on code/game/machinery/computer/shop.dm
> +			category = href_list["categ"]
в топике кажется не хватает валидации полученных с клиента данных

2023-10-08 14:26 UTC, volas commented on code/game/objects/items/devices/PDA/PDA.dm
>  			var/id = href_list["order_item"]
в функциях грузторга в пда, кстати, тоже

2023-10-08 14:26 UTC, volas commented on nano/templates/shop.tmpl
> +	<div class="item">
наноюи это то, от чего я бы хотел избавиться в первую очередь в пользу тгюи, и добавлять новые наноюи интерфейсы отдаляет и усложняет эту цель. Будет на твоей совести.

2023-10-08 14:27 UTC, volas commented
Если ты еще жив, я могу потом попробовать в ТМ закинуть.

2023-10-08 14:43 UTC, DarthSidiousPalpatine commented
> Если ты еще жив, я могу потом попробовать в ТМ закинуть.

Ожидаю

2023-10-08 15:03 UTC, DarthSidiousPalpatine commented on code/game/objects/items/devices/PDA/PDA.dm
>  			var/id = href_list["order_item"]
Это ерунда, там дальше по id ищется нужный лист и проверяется существует ли он. Это не валидация?

2023-10-08 15:09 UTC, volas commented on code/game/objects/items/devices/PDA/PDA.dm
>  			var/id = href_list["order_item"]
я как клиент могу тут спровоцировать рантайм на сервере с обращением к несуществующему элементу массива

2023-10-08 15:16 UTC, DarthSidiousPalpatine commented on code/game/objects/items/devices/PDA/PDA.dm
>  			var/id = href_list["order_item"]
Ладно, удачи, д****а какая-то странная, учитывая что у нас половина билда тогда рантаймы шлёт с несуществующими элементами массивов...

2023-10-08 15:17 UTC, DarthSidiousPalpatine commented
Приду когда-нибудь когда.

2023-10-09 16:06 UTC, LudwigVonChesterfield commented on code/game/objects/items/devices/PDA/PDA.dm
>  			var/id = href_list["order_item"]
> я как клиент могу тут спровоцировать рантайм на сервере с обращением к несуществующему элементу массива

мне кстати кажется что не получится потому-что передаётся как строка и не конвертится в цифру значит обращение будет по ключу а если ключа нет в словаре то дальше просто не выполнится код

2023-10-09 16:22 UTC, volas commented on code/game/objects/items/devices/PDA/PDA.dm
>  			var/id = href_list["order_item"]
скорее всего, я вчера это с очень тяжёлой головой смотрел. Но категория выше всё еще под вопросом, и в дургих местах возможно тоже надо посмотреть

2023-10-09 16:27 UTC, LudwigVonChesterfield commented on code/game/objects/items/devices/PDA/PDA.dm
>  			var/id = href_list["order_item"]
с категорией точно обосрамс, он не приводил бы к рантаймом, но можно было бы инжектить туда гадости всякие крашащие к примеру потому-что никакой валидации вообще нет

2023-10-09 16:37 UTC, LudwigVonChesterfield requested changes
не хватает как минимум валидации категории в топике ПДА и новой консольки

стоит пройтись вообще по всем веткам топика и глянуть где тоже можно натыкать валидацию

2023-10-09 17:23 UTC, DarthSidiousPalpatine commented
Всё, сделал

2023-10-09 17:34 UTC, LudwigVonChesterfield commented on code/game/machinery/computer/shop.dm
> +			mode = 11
как же круто если бы для этого были дефайны...

2023-10-09 17:34 UTC, LudwigVonChesterfield commented on code/game/machinery/computer/shop.dm
> +				category_shop_per_page = number
нужен максимум-минимум валидация тут

2023-10-09 17:35 UTC, LudwigVonChesterfield commented on code/game/machinery/computer/shop.dm
> +				category_shop_per_page = number
(кстати было бы круто если бы ещё в КПК с ГрузТоргом это фиксил бы заодно)

2023-10-09 17:37 UTC, LudwigVonChesterfield commented on code/game/machinery/computer/shop.dm
> +			var/datum/shop_lot/Lot = global.online_shop_lots[id]
я думаю Воласа тригернуло что оно не мгновенно выходит из функции если Лот не обнаружен а продолжает что-то выполнять.

мне кажется тут нет возможности вызвать рантайм и всё валидировано но как вариант было бы вот тут сделать
```
if(!Lot || !owner_account)
    return
if(Lot.sold)
     и т.д. и т.д.
```

2023-10-09 17:37 UTC, LudwigVonChesterfield commented on code/game/machinery/computer/shop.dm
> +					if(Lot.sold)
мне кажется или можно присвоить себе чужой лот?

2023-10-09 17:38 UTC, LudwigVonChesterfield commented on code/game/machinery/computer/shop.dm
> +					if(Lot.sold)
таки кажется, не обращай внимания

2023-10-09 17:39 UTC, LudwigVonChesterfield commented on code/game/machinery/computer/shop.dm
> +/proc/check_cargo_consoles_link(object)
мб кстати check_cargo_consoles_operational

2023-10-09 18:12 UTC, DarthSidiousPalpatine commented on code/game/machinery/computer/shop.dm
> +					if(Lot.sold)
Не обратил внимания как и было приказано

2023-10-09 18:12 UTC, DarthSidiousPalpatine commented on code/game/machinery/computer/shop.dm
> +			var/datum/shop_lot/Lot = global.online_shop_lots[id]
Зачем

2023-10-09 18:12 UTC, DarthSidiousPalpatine commented on code/game/machinery/computer/shop.dm
> +			mode = 11
И что делать

2023-10-09 18:14 UTC, DarthSidiousPalpatine commented
Сделал крч х2

2023-10-09 18:18 UTC, DarthSidiousPalpatine commented on code/game/objects/items/devices/PDA/PDA.dm
>  			var/id = href_list["order_item"]
Сделал

2023-10-09 18:18 UTC, DarthSidiousPalpatine commented on code/game/machinery/computer/shop.dm
> +			category = href_list["categ"]
Сделал

2023-10-09 18:22 UTC, DarthSidiousPalpatine commented
Ееей, все чеки прошло, конфликтов нет, на всё ответил, всё сделал. Збс.

2023-10-09 20:25 UTC, LudwigVonChesterfield commented on code/game/machinery/computer/shop.dm
> +			mode = 11
ну просто это копипаста из ПДА но мы с ней скорее всего будем долго жить

и возможно было бы лучше если бы вместо mode = 1, 9, 11

у нас были бы SHOP_PAGE_LANDING, SHOP_PAGE_LOTS, SHOP_PAGE_ORDERED_LOTS

2023-10-10 03:34 UTC, DarthSidiousPalpatine commented on code/game/machinery/computer/shop.dm
> +			mode = 11
та зачем, это литералли бесполезно учитывая что темплейты у них разные.

2023-10-10 15:01 UTC, DarthSidiousPalpatine commented
Так это, надое ещё что-то делать?

2023-10-10 15:19 UTC, LudwigVonChesterfield commented on code/game/machinery/computer/shop.dm
> +				mode = round(mode/10)
вот это вообще, может тоже mode = 1? и тогда снести всю эту проверку?

2023-10-10 15:39 UTC, DarthSidiousPalpatine commented on code/game/machinery/computer/shop.dm
> +				mode = round(mode/10)
не пон

2023-10-10 15:40 UTC, LudwigVonChesterfield commented on code/game/machinery/computer/shop.dm
> +				mode = round(mode/10)
Это копипаста из ПДА, в ПДА все 21-29 моды при нажатии ретурн возвращаются к моду 2

Но у нас тут нет такого функционала. Если бы mode поменяли на дефайны и прошлись бы тут то это было бы очевидней

2023-10-10 15:40 UTC, DarthSidiousPalpatine commented on code/game/machinery/computer/shop.dm
> +				mode = round(mode/10)
пон

2023-10-10 18:02 UTC, DarthSidiousPalpatine commented
еее, боииииии, аппрувнуто

2023-10-15 20:05 UTC, LudwigVonChesterfield commented
есть места на карте которые нужно поправить

@Lexakr , прочие доброжелатели, скидывайте пожалуйста любые места где консоль нелепо висит

2023-10-18 01:19 UTC, volas commented
гусев, не забудь про консоли. Я сниму с ТМ-а, если до конца недели не будет прогресса

2023-10-21 21:31 UTC, DarthSidiousPalpatine commented
Ну всё, как бы, я поправил кринжовые места.

2023-10-22 03:33 UTC, LudwigVonChesterfield commented
Всё ещё проблемное место с ресепшенем брига

![image](https://github.com/TauCetiStation/TauCetiClassic/assets/17705613/5a91d484-2230-4197-a875-618932e36945)

Я бы предложил её перенести или в раздевалку или ещё куда-то...

2023-10-22 04:15 UTC, DarthSidiousPalpatine commented
> Всё ещё проблемное место с ресепшенем брига
> 
> ![image](https://user-images.githubusercontent.com/17705613/277143931-5a91d484-2230-4197-a875-618932e36945.png)
> 
> Я бы предложил её перенести или в раздевалку или ещё куда-то...

Консоль должна быть на ресепшне.

2023-10-22 14:50 UTC, DarthSidiousPalpatine commented
Исправил консоль на ресепшне брига и, теперь, вообще все замечания по расположению исправлены.

2023-10-26 02:01 UTC, LudwigVonChesterfield approved these changes
LGTM

2023-10-26 02:04 UTC, merged