[Часть 1]Перевод описания всего лазерного/огнестрельного оружия
TauCetiStation/TauCetiClassic pull request #11923
Opened 2023-08-17 14:35 UTC by AzzyDreemurr13

## Описание изменений
По мотивам старого ПРа от Симбаки #8662
Выполнение одной из задач нашей команды переводчиков. 
Переведено все что находилось в \code\modules\projectiles\guns до pistol.dm + от гусеева sniper.dm , silencer.dm и pneumatic.dm

P.s Буду еще после курсов вечером дополнять перевод.

## Почему и что этот ПР улучшит
Более понятное описание на русском языке с сохранением различных приколов и отсылок которые были в английском
## Авторство
Подвального транслейта возглавляемый Лиджардом. А также 3 переведенных файла @DarthSidiousPalpatine. Спасибо также за моральную помощь в #Build-Translation
## Чеинжлог
:cl: Azzy.Dreemurr
- localization: Первая часть перевода описания лазерного/огнестрельного оружия

2023-08-17 14:35 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2023-08-17 14:47 UTC, simb11 commented on code/modules/projectiles/guns/energy/nuclear.dm
> +	desc = "Основной энергетический пистолет с двумя настройками: оглушить или убить."
мне кажется тут лучше подойдет "стандартный энергетический пистолет", а не основной

2023-08-17 15:10 UTC, maleyvich requested changes

2023-08-17 15:18 UTC, maleyvich commented on code/modules/projectiles/guns/energy/pulse.dm
> +	desc = "Дело не в размере оружия, а в размере дыры, которую оно проделывает в людях."
Эта штука была проверена временем, и никак не может потерять актуальность! Попробуй и узнай её мощь!

составил за 5 минут, но раз щитспавн то можно так и оставить

2023-08-17 15:31 UTC, volas commented on code/modules/projectiles/guns/energy/laser.dm
> +	desc = "Это антикварный лазерный пистолет. Все детали высочайшего качества. В отделке есть элементы из хрома, стали и ассистента? Предмет излучает энергетику и власть. На нем выгравирована космическ
описание отчасти пересекается с гравюрой гунов в прибытии

2023-08-17 15:59 UTC, TRISAGI0N commented on code/modules/projectiles/guns/energy/laser.dm
> +	desc = "Это антикварный лазерный пистолет. Все детали высочайшего качества. В отделке есть элементы из хрома, стали и ассистента? Предмет излучает энергетику и власть. На нем выгравирована космическ
не из ассистента, а из кои ассистента

2023-08-17 16:00 UTC, AndroBetel commented on code/modules/projectiles/guns/energy/special.dm
> +	desc = "Инструмент, используемый для быстрого измерения температуры без опасения причинить вред при непосредственном физическом контакте. Поставляется со встроенным многоцветным лазерным указателем.
можно ещё эти два предложения соединить в одно, типа "Поставляется со встроенным многоцветным лазерным указателем и способен работать во всех возможных режимах!"

2023-08-17 16:03 UTC, TRISAGI0N commented on code/modules/projectiles/guns/energy/laser.dm
> +	desc = "Это антикварный лазерный пистолет. Все детали высочайшего качества. В отделке есть элементы из хрома, стали и ассистента? Предмет излучает энергетику и власть. На нем выгравирована космическ
ахуенный подход

2023-08-17 18:41 UTC, TRISAGI0N commented on code/modules/projectiles/guns/energy/special.dm
> +	desc = "Прототип лечебной пушки, которая медленно возвращает органические вещества в прежнее состояние, исцеляя их. Не проходите через луч!"
Скрещивать струи это ж можно отсылку на гостбастеров сделать, вроде там так было

2023-08-18 09:02 UTC, muWander commented on code/modules/projectiles/guns/energy/special.dm
> +	desc = "Прототип лечебной пушки, которая медленно возвращает органические вещества в прежнее состояние, исцеляя их. Не проходите через луч!"
На тг с которого скопировали описание если на пути луча окажется другой луч произойдёт бум, так что это про два луча предупреждение

2023-09-01 11:43 UTC, Kiromaka commented
так, я как то хуево ревью делаю 
![ыфвфывфы](https://github.com/TauCetiStation/TauCetiClassic/assets/74469991/d3264c43-ed6e-45f6-8697-a8175df12eab)

2023-09-01 11:47 UTC, Kiromaka requested changes

2023-09-01 11:47 UTC, Kiromaka commented on code/modules/projectiles/guns/energy/special.dm
> +	desc = "Инструмент, используемый для быстрого измерения температуры без опасения причинения вреда в результате прямого физического контакта с пользователем."
снизу еще 5 штук таких же

2023-09-01 11:47 UTC, Kiromaka commented on code/modules/projectiles/guns/energy/special.dm
> +	desc = "Инструмент, используемый для быстрого измерения температуры без опасения причинения вреда в результате прямого физического контакта с пользователем."
получается что при контакте с объектом измерения, пользователь наносит вред самому объекту, а не обратное.

2023-09-01 18:05 UTC, Kiromaka requested changes

2023-09-01 18:05 UTC, Kiromaka commented on code/modules/projectiles/guns/plasma/plasma.dm
> +		to_chat(user, "<span class='notice'>Внутри [src] нет обоймы.</span>")
Может просто "в" ? Обойма обычно внутри процентов на 10%.

2023-09-01 18:05 UTC, Kiromaka commented on code/modules/projectiles/guns/plasma/plasma.dm
> +			to_chat(user, "<span class='notice'>Внутри [src] уже установлена обойма.</span>")
Может просто "в" ? Обойма обычно внутри процентов на 10%.

2023-09-01 18:05 UTC, Kiromaka commented on code/modules/projectiles/guns/plasma/plasma.dm
> +	desc = "Стандартный плазменный карабин типа буллпап с высокой скорострельностью."
```suggestion
	desc = "Стандартный плазменный карабин типа булл-пап с высокой скорострельностью."
```

2023-09-01 18:05 UTC, Kiromaka commented on code/modules/projectiles/guns/energy/special.dm
> +			to_chat(user, "<span class='warning'>Проектор червоточины неисправен, оно телепортирует прочь!</span>")
```suggestion
			to_chat(user, "<span class='warning'>Проектор червоточины неисправен, оно телепортируется прочь!</span>")
```

2023-09-01 18:10 UTC, Kiromaka commented
Не пропусти свернутые реквесты

2023-09-01 18:44 UTC, Kiromaka commented on code/modules/projectiles/guns/projectile/sniper.dm
> +	desc = "Бронебойное ружьё. Предназначалось для поражения бронированных мехов. С лёгкостью пробивает стёкло пулей калибра 14.5мм."
> аммм, а в чем разница? Все тоже самое - резовл

е != ё

2023-09-01 18:47 UTC, Kiromaka commented on code/modules/projectiles/guns/projectile/bow.dm
> +	desc = "Не плачь по мне, Орифина."
и != е, чтобы не сказал, что тоже самое

2023-09-01 18:51 UTC, Kiromaka commented on code/modules/projectiles/guns/energy/special.dm
> +			to_chat(user, "<span class='warning'>Проектор червоточины неисправен, оно телепортирует прочь!</span>")
если тут по отношению к проектору - то вместо оно, ОН

2023-09-01 19:37 UTC, Kiromaka requested changes

2023-09-01 19:37 UTC, Kiromaka commented on code/modules/projectiles/guns/projectile/bow.dm
> +		to_chat(user, "[src] при попадании из арбалета разлетается на россыпь осколков из перенапряженного металла.")
Уже писал при выстреле/выпуске (вместо "при попадании). Ты родом стреляешь и искры летят от трения об арбалет, в ориге так-же

2023-09-01 19:39 UTC, Kiromaka commented on code/modules/projectiles/guns/projectile/bow.dm
> +		to_chat(user, "[src] при попадании из арбалета разлетается на россыпь осколков из перенапряженного металла.")
щас
не совсем понимаю, перейди в дс

2023-09-01 19:43 UTC, Kiromaka commented on code/modules/projectiles/guns/projectile/bow.dm
> +		to_chat(user, "[src] при попадании из арбалета разлетается на россыпь осколков из перенапряженного металла.")
![Uploading фывфывфы.PNG…]()

2023-09-01 19:43 UTC, Kiromaka commented on code/modules/projectiles/guns/projectile/bow.dm
> +		to_chat(user, "[src] при попадании из арбалета разлетается на россыпь осколков из перенапряженного металла.")
![фывфывфы](https://github.com/TauCetiStation/TauCetiClassic/assets/74469991/4b50447b-f4c5-44f9-8a42-68d4e2062ad1)

2023-09-01 19:47 UTC, Kiromaka commented on code/modules/projectiles/guns/projectile/bow.dm
> +		to_chat(user, "[src] при попадании из арбалета разлетается на россыпь осколков из перенапряженного металла.")
```suggestion
		to_chat(user, "[src] при выпуске из арбалета разлетается на россыпь осколков из перенапряженного металла.")
```

2023-09-01 19:47 UTC, Kiromaka commented on code/modules/projectiles/guns/projectile/bow.dm
> +		to_chat(user, "[src] при попадании из арбалета разлетается на россыпь осколков из перенапряженного металла.")
если лиджард скажет что перенапряжённый херово звучит, можно заменить на перегретый

2023-09-01 19:59 UTC, Kiromaka commented
> Тэкккс, ну вроде все что по первому взгляду Киромаки я все отредачил

не все, 

- [ ] 

> Тэкккс, ну вроде все что по первому взгляду Киромаки я все отредачил

Пролистай те на которых нету плашки outdated, там провода не переведены, булл-пап, и заварите вместо заварить. Хотя все остальное в повелительном

2023-09-04 22:13 UTC, Fenriros commented on code/modules/projectiles/guns/energy/special.dm
> +	desc = "Эта ручка могущественнее, чем меч."
The pen is mightier than the sword
Перевод: перо сильнее меча.
Значение: правильные слова убедительнее физической силы; словами можно больно ранить.
Аналог в русском языке: не ножа бойся — языка.
Это точная цитата из пьесы Эдварда Бульвера-Литтона «Ришелье, или Заговор», написанной в 1839 году. Однако в других формулировках эта мысль звучала ранее у Джорджа Ветстоуна и Уильяма Шекспира.

2023-09-04 23:03 UTC, Fenriros commented on code/modules/projectiles/guns/projectile/automatic.dm
> +	desc = "Сильно модифицированный легкий пулемет с тактической пластиковой рамкой, опирающейся на довольно традиционную баллистику. На ствольной коробке выгравировано 'Оружейная мастерская Aussec - 25
может 
```suggestion
	desc = "Сильно модифицированный легкий пулемет с тактической рамкой из пластали, опирающейся на довольно традиционную баллистику. На ствольной коробке выгравировано 'Оружейная мастерская Aussec - 2531', кроме того используются патроны '7.62x51мм' ."
```

2023-09-04 23:04 UTC, Fenriros commented on code/modules/projectiles/guns/projectile/automatic.dm
> +		to_chat(user, "<span class='notice'>[src] крышка открыта! Закройте ее перед стрельбой!</span>")
```suggestion
		to_chat(user, "<span class='notice'>Крышка [src] открыта! Закройте ее перед стрельбой!</span>")
```

2023-09-04 23:06 UTC, Fenriros commented on code/modules/projectiles/guns/projectile/automatic.dm
> +		to_chat(user, "<span class='notice'>[src] крышка закрыта! Вы не можете вставить новую обойму!</span>")
```suggestion
		to_chat(user, "<span class='notice'> Крышка [src] закрыта! Вы не можете вставить новую обойму!</span>")
```

2023-09-04 23:12 UTC, Fenriros commented on code/modules/projectiles/guns/projectile/automatic.dm
> +	desc = "Малогабаритный самозарядный полуавтоматический дробовик для ведения огня в узких коридорах."
А чего не добавил " требуются специальные патроны" ?

2023-09-04 23:12 UTC, Fenriros commented on code/modules/projectiles/guns/projectile/automatic.dm
> +		"<span class='warning'>Вы активирует ваш [gl].</span>",\
```suggestion
		"<span class='warning'>Вы активируете ваш [gl].</span>",\
```

2023-09-05 06:39 UTC, Fenriros commented on code/modules/projectiles/guns/projectile/bow.dm
> +	desc = "В нем есть подсказка для вас - уловили суть?"
тут шутка, но хз как на русский перевести.
Мне пришло в голову ток это  "У меня есть подсказка для тебя - найди цель"

2023-09-05 06:46 UTC, Fenriros commented on code/modules/projectiles/guns/projectile/bow.dm
> +	desc = "Не плачь по мне, Орифена."
Аргентина*

2023-09-05 06:53 UTC, Fenriros commented on code/modules/projectiles/guns/projectile/bow.dm
> +			user.visible_message("[user] ослабляет натяжение тетевы [src]'и вытаскивает [arrow].","Вы ослабляете натяжение тетевы [src] и вытаскиваете [arrow].")
```suggestion
			user.visible_message("[user] ослабляет натяжение тетевы [src] и вытаскивает [arrow].","Вы ослабляете натяжение тетевы [src] и вытаскиваете [arrow].")
```

2023-09-05 06:58 UTC, Fenriros commented on code/modules/projectiles/guns/projectile/bow.dm
> +	user.visible_message("<span class='danger'>[user] стреляет из [src] и [arrow] летит в направлении [target]!</span>","<span class='danger'>Вы отпускаете [src] и отправляется в полет [arrow] несущуюся
```suggestion
	user.visible_message("<span class='danger'>[user] стреляет из [src] и [arrow] летит в направлении [target]!</span>","<span class='danger'>Вы отпускаете [src] и отправляете в полет [arrow] несущуюся навстречу [target]!</span>")
```

2023-09-05 07:04 UTC, Fenriros commented on code/modules/projectiles/guns/projectile/launcher.dm
> +	desc = "Это маленькая крошечная пусковая установка. Вы не должны этого видеть."
```suggestion
	desc = "Это маленькая крошечная пусковая установка. Вам не следовало этого видеть."
```
```suggestion
	desc = "Это маленькая крошечная пусковая установка. Вам не стоило этого видеть."
```
```suggestion
	desc = "Это маленькая крошечная пусковая установка. Вы не должны были это увидеть."
```

2023-09-05 07:42 UTC, Fenriros commented on code/modules/projectiles/guns/projectile/pneumatic.dm
> +	desc = "Для завершения сборки: проварите трубу; добавьте и приварите 5 листов металла; прикрутите вентиль и заварите швы."
Тут же не указана труба `To finish you need: weld it all;`

2023-09-05 10:26 UTC, Kiromaka commented on code/modules/projectiles/guns/projectile/bow.dm
> +	desc = "Не плачь по мне, Орифена."
Тут две отсылки, на Dont cry for me argentina, и персонажа Орифена из новелы Anathem, так что Орифена правильно

2023-09-05 12:11 UTC, Fenriros commented on code/modules/projectiles/guns/projectile/launcher.dm
> +	desc = "Это маленькая крошечная пусковая установка. Вы не должны этого видеть."
```suggestion
	desc = "Это маленькая крошечная пусковая установка. Вам не следовало этого видеть."
```
> Чаще всего модальный глагол should употребляется в предложениях, где говорящий человек дает совет. Запомните, именно совет, а не строгие указания. Совет – это просто рекомендация, которой можно пренебречь. При таком использовании should будет иметь перевод "следует сделать что-то":

2023-09-05 12:14 UTC, Fenriros commented on code/modules/projectiles/guns/projectile/pneumatic.dm
> +	desc = "Для завершения сборки: проварите трубу; добавьте и приварите 5 листов металла; прикрутите вентиль и заварите швы."
```suggestion
	desc = "Для завершения сборки: приварите трубу; добавьте и приварите 5 листов металла; прикрутите вентиль и заварите швы."
```

2023-09-21 05:58 UTC, merged