Перевод молитв
TauCetiStation/TauCetiClassic pull request #11933
Opened 2023-08-19 02:33 UTC by Kiromaka

## Описание изменений
Перевод молитв( не переведены еще 4-5, посчю для фидбека а пока пойду спать). 
Перевод с запроса КИБОРГА, молитвы с источником переведены на церковный манер 
( как их читают в церкви и как они написаны в большинстве книг), 
молитвы без  источника переведены прямо,
( максимально старался придумать более " церковные" слова но в 5 утра мозг не вывозит).

Прошу писать любой фидбек, в 9 вечера встану посмотрю и допишу молитвы

## Почему и что этот ПР улучшит
Молитвы будут переведены) запрос от основы трисагона
## Авторство
Я и молитвослов у икон
## Чеинжлог
🆑 
 - localization: Переведены молитвы священника

2023-08-19 02:33 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2023-08-19 03:02 UTC, maleyvich commented on code/modules/religion/rites/standing/consent.dm
>  	consent_msg = "Are you ready to sacrifice your body to turn into a cyborg?"
а это не перевёл блин

2023-08-19 05:07 UTC, DarkFurrSss commented
Ошибка в ошибке, умноженная на ошибку, в скобках возведённая на ошибку. Всунул в переводчик и без смысла переписал что увидел? Хоть не скопировал, суда по "Гопсади"

2023-08-19 05:09 UTC, DarkFurrSss commented
Даже отче наш переведен каверно...

2023-08-19 05:16 UTC, maleyvich requested changes

2023-08-19 05:16 UTC, maleyvich commented on code/modules/religion/rites/standing/consent.dm
> +	ritual_invocations = list("Благодоря внутренним механизмам бога нашего...", //если есть перевод лучше предлогайте
чё это за комментарий

2023-08-19 05:16 UTC, maleyvich commented on code/modules/religion/rites/standing/consent.dm
> +								"...да прииидет царствие твое...",
знаешь "прииидет" звучит немного идиотски

2023-08-19 05:16 UTC, maleyvich commented on code/modules/religion/rites/standing/consent.dm
> +								"...Хлеб насущный даждь нам днесь и остави нам долги наши...",
даждь

2023-08-19 05:16 UTC, maleyvich commented on code/modules/religion/rites/standing/consent.dm
> +								"...якожи и мы остовляем должником нашим...",
остовляем

2023-08-19 05:16 UTC, maleyvich commented on code/modules/religion/rites/standing/consent.dm
> +						"...до преждевременныя и внезапныя смерти без покаяния....",
преждевременная и внезапная

2023-08-19 05:16 UTC, maleyvich commented on code/modules/religion/rites/standing/consent.dm
> +						"...А дом наш и всех нас, живущих в нем, сохрани от огненнаго запаления, воровскаго нападения...",
огненного, воровского

2023-08-19 05:16 UTC, maleyvich commented on code/modules/religion/rites/standing/consent.dm
> +						"...всякаго злаго обстояния, разнаго страхования и диавольскаго наваждения....",
без комментариев

2023-08-19 05:16 UTC, maleyvich commented on code/modules/religion/rites/standing/consent.dm
> +						"...Да и мы купно и раздульно, явно и сокровунно будем прославлять имя Твоу Святое....",)
тоже без комментариев... ошибок действительно много. зачем пытаться в старославянский (если это он вообще)

2023-08-19 09:11 UTC, AndroBetel commented on code/modules/religion/rites/standing/consent.dm
> +						"..От нашей матери к нашим ушам мы получили в дар рога...",
не рога а гудки же епта клаксоны

2023-08-19 09:20 UTC, Kiromaka commented
Так я проснулся, ладно половина не выкупила что отче наш, утренние и молитва о защите переведены на древне русский, как в молитвослове. Людям не зашел древне русский, Меняем на другой перевод.
(насчет небольших ошибок  в текста пофикшу)

2023-08-19 09:21 UTC, Kiromaka commented on code/modules/religion/rites/standing/consent.dm
> +						"...не допусти никого из семьи́ моей до разлуки и тяжкаго расставания...",
копипаст из молитволосва, забыл удалить

2023-08-19 09:21 UTC, Kiromaka commented on code/modules/religion/rites/standing/consent.dm
> +	ritual_invocations = list("Владычице Преблагословенная, возьми под Свой покроов семью мою...",
тут тоже молитвослов

2023-08-19 09:22 UTC, Kiromaka commented on code/modules/religion/rites/standing/consent.dm
> +	invoke_msg = "...И в качестве подарка от наших матерей мы даруем вам HONK!!"
сделаем

2023-08-19 09:30 UTC, Kiromaka commented on code/modules/religion/rites/standing/misc.dm
> +							  "...Они наделяли анимацию человеческими страстями и чувствами...",
вроде внутриигровой термин,  - гомункул, голем )

2023-08-19 09:31 UTC, Kiromaka commented on code/modules/religion/rites/standing/misc.dm
> +							  "...ибо я нарушаю ваш покой не только из любопытства...")
я хуй знает, я на ты менял когда понял че написал, видимо я не все изменения закомпилил

2023-08-19 09:32 UTC, Kiromaka commented on code/modules/religion/rites/standing/misc.dm
> +							  "...Вы должны отравить все целиком, выгнать хвосты из тела животного...",
тут походу устоявшееся, которое я не выкупил

2023-08-19 09:49 UTC, Kiromaka commented
> Короче плохо. Мало того, что миллион ошибок, неустановленных смыслов и логических несоответствий, так ещё и не сильно пахнет какой-то творческой деятельностью. А хотелось бы, потому что в молитвах важно не только донести смысл, но и завернуть это все в подобающую форму. Работать и работать тут.

да работу еще дохуя знаю, щас займусь переводом с старо-славянского на русский, думал что старо славянский колорита добавит. Людям не зашло. Потом исправлю и поищу еще ошибок на здоровую выспавшеюся голову.

2023-08-19 10:16 UTC, Kiromaka commented
Все пофикшено, нашел еще пару ошибок и тупых применений слов. 
Анимация - надо заменять термин, все что подходит, это голем, но голем у нас занят, так что надо придумывать что-то новое

2023-08-19 10:48 UTC, Kiromaka commented
Переведены молитвы со спавном, учел ваши замечания, вроде эти перевел лучше.

2023-08-19 14:30 UTC, Kiromaka commented
Все перевел, нужно мнение насчет первой молитвы в swap.

2023-08-19 14:35 UTC, Kiromaka commented
ПР доделан, ожидает проверки от депа, и мержа от воласа

2023-08-19 14:57 UTC, KIBORG04 commented on code/modules/religion/rites/standing/consent.dm
> +						"...Вы взываем к тебе, перед лицом напасти...",
Мы

2023-08-20 01:03 UTC, Kiromaka commented on code/modules/religion/rites/standing/misc.dm
> +							  "...Они наделяли анимацию человеческими страстями и чувствами...",
мне на ум замена не приходит.

2023-08-20 11:19 UTC, Kiromaka commented on code/modules/religion/rites/standing/misc.dm
> +							  "...Вы должны вытравить все целиком, отогнать заразу из тела животного...",
я не понял к кому тут обращение, поставил ВЫ, исправлю на ты

2023-08-20 11:23 UTC, Kiromaka commented on code/modules/religion/rites/standing/misc.dm
> +							  "...данные из света, данные мудростью возвратившихся богов...",
не понял, надо сделать - свет дарованный мудростью возвратившихся ?

2023-08-20 11:37 UTC, Kiromaka commented
Damn, ошибок я конечно много допустил, еще и церковнославянский лишний.

2023-08-20 11:56 UTC, KIBORG04 commented on code/modules/religion/rites/standing/consent.dm
> +	ritual_invocations = list("Отче наш, сущий на небесах......",
А почему у "добровольного жертвоприношения" молитва "отче наш" ??????? Че-то я думаю оно не смотрится здесь

2023-08-20 11:57 UTC, KIBORG04 commented on code/modules/religion/rites/standing/consent.dm
> +	invoke_msg = "... И от Матери нашей, да заполучишь ты силу ГУДКА!!"
```suggestion
	invoke_msg = "... И от Матери нашей, да заполучишь ты силу ХОНКА!!"
```

2023-08-20 11:58 UTC, KIBORG04 commented on code/modules/religion/rites/standing/consent.dm
> +						"...Чтобы завершить нас, искоренить нежелаемое...")
Определись, где-то ты продолжаешь молитвы с большой буквы (как тут), где-то продолжаются с маленькой, держи одну стилистику

2023-08-20 11:59 UTC, maleyvich commented on code/modules/religion/rites/standing/consent.dm
> +	invoke_msg = "... И от Матери нашей, да заполучишь ты силу ГУДКА!!"
это лизард предлагал вроде бы.

2023-08-20 12:01 UTC, Kiromaka commented on code/modules/religion/rites/standing/consent.dm
> +	invoke_msg = "... И от Матери нашей, да заполучишь ты силу ГУДКА!!"
хонк запретили лизард

2023-08-20 12:02 UTC, Kiromaka commented on code/modules/religion/rites/standing/consent.dm
> +						"...Чтобы завершить нас, искоренить нежелаемое...")
если херни не сделал, маленькие буквы потому, что это одно предложение.

2023-08-20 12:02 UTC, KIBORG04 commented on code/modules/religion/rites/standing/consent.dm
> +	invoke_msg = "... И от Матери нашей, да заполучишь ты силу ГУДКА!!"
Втф, хонк вне закона??? 💀 💀 💀 💀 💀 💀 💀 💀 💀 💀 💀 💀 💀 💀 💀 💀 💀

2023-08-20 12:02 UTC, Kiromaka commented on code/modules/religion/rites/standing/consent.dm
> +	ritual_invocations = list("Отче наш, сущий на небесах......",
это ты ее вставил

2023-08-20 12:02 UTC, Kiromaka commented on code/modules/religion/rites/standing/consent.dm
> +	invoke_msg = "... И от Матери нашей, да заполучишь ты силу ГУДКА!!"
расизм против клоунов

2023-08-20 12:03 UTC, KIBORG04 commented on code/modules/religion/rites/standing/misc.dm
> +							  "...(замена анимации в RU, голем занят големом), пришедшая из Нового Царства, радуйся свету!...",)
Не пихай такие приколы со скобками, это можно легко упустить, а челы в игре могут заметить и поржать. Хз че не так с Анимацией, так ритуал назван, хз

2023-08-20 12:03 UTC, Kiromaka commented on code/modules/religion/rites/standing/misc.dm
> +							  "...(замена анимации в RU, голем занят големом), пришедшая из Нового Царства, радуйся свету!...",)
тоже к лизарду. Я оставил до момента нахождения замены, если анимация тоже норм вставлю ее

2023-08-20 12:04 UTC, KIBORG04 commented on code/modules/religion/rites/standing/consent.dm
> +	ritual_invocations = list("Отче наш, сущий на небесах......",
Я не узнал. лаааадно

2023-08-20 12:05 UTC, KIBORG04 commented on code/modules/religion/rites/standing/swap.dm
> +							  "... Так этот предмет всегда будет лучше...",)
```suggestion
							  "...Она наделила эти вещи своей силой...",
							  "...Как луна и земля никогда не расстаются...",
							  "...Так этот предмет всегда будет лучше...",)
```

2023-08-20 12:06 UTC, KIBORG04 commented on code/modules/religion/rites/standing/swap.dm
> +							  "...всё есть твоё ! Иди - бери!...",
```suggestion
							  "...всё есть твоё! Иди - бери!...",
```

2023-08-20 12:07 UTC, KIBORG04 commented on code/modules/religion/rites/standing/swap.dm
> +							  "...для всех - несметные богатства,...",
```suggestion
							  "...богатств достигнут и высот,...",
							  "...и Ангелов душой коснутся...",
							  "...Что приготовили дары...",
							  "...для всех - несметные богатства...",
```
Я думаю можно упустить запятые, так как они странно выглядят рядом с троеточием таким

2023-08-20 12:08 UTC, KIBORG04 commented on code/modules/religion/rites/standing/consent.dm
> +						"...Чтобы завершить нас, искоренить нежелаемое...")
А здесь как раз одно

2023-08-20 12:08 UTC, Kiromaka commented on code/modules/religion/rites/standing/consent.dm
> +						"...Чтобы завершить нас, искоренить нежелаемое...")
я щас фикшу
дай минутку

2023-08-20 12:30 UTC, Kiromaka commented
Чет галочки решили немного поругаться

2023-08-21 11:07 UTC, Kiromaka commented
Вроде больше ошибок нету, говно-перевод готов к мерджу.

2023-08-28 20:15 UTC, KIBORG04 commented on code/modules/religion/rites/standing/consent.dm
> +	invoke_msg = "... И от Матери нашей, да заполучишь ты силу ГУДКА!!"
```suggestion
	ritual_invocations = list("Земля от нашей Матери заполучила бананы...",
						"...Уши от нашей Матери заполучили клаксоны...",
						"...Стопы от нашей Матери заполучили длинную обувь...")
	invoke_msg = "...И от Матери нашей, да заполучишь ты силу ГУДКА!!"
```
Мдааа, а сам бы пролистал ПР и нашел бы

2023-08-28 20:15 UTC, KIBORG04 commented on code/modules/religion/rites/standing/consent.dm
> +						"...всякого злого обстояния,  страха и дьявольского навождения...",
```suggestion
						"...всякого злого обстояния, страха и дьявольского навождения...",
```
😢

2023-08-28 20:27 UTC, KIBORG04 commented on code/modules/religion/rites/standing/swap.dm
> +	invoke_msg = "...Я взываю ко всему сущему!"
```suggestion
	ritual_invocations = list("Родилась луна...",
							  "...Родилась сила...",
							  "...Она наделила эти вещи своей силой...",
							  "...Как луна и земля никогда не расстаются...",
							  "...так этот предмет всегда будет лучше...",)
	invoke_msg = "...Я взываю ко всему сущему!"
```

2023-08-28 20:37 UTC, Kiromaka commented
Лижард, если больше нету вопросов ставь галочку.

2023-08-28 22:49 UTC, Kiromaka commented on code/modules/religion/rites/standing/consent.dm
>  	desc = "Превращает <i>homosapiens</i> в (превосходящего) Андройда."
заменил на машину

2023-08-29 14:50 UTC, volas commented
мне не очень нравится флавор некоторых, я предлагаю кому-нибудь потом свои молитвы сочинить на замену

2023-08-29 14:51 UTC, merged