Обновление UI здоровья ксеноморфов и небольшие перестановки.
TauCetiStation/TauCetiClassic pull request #11939
Opened 2023-08-21 08:52 UTC by maleyvich

## Описание изменений
Небольшое изменение в UI ксеноморфов, а именно отображение здоровья
## Почему и что этот ПР улучшит
красивее выглядит
## Авторство
https://github.com/Cosmic-Overlord/TerraGov-Marine-Corps/pull/241 - спрайты взяты с этого ПР-а, автор не против их использования.
## Чеинжлог
🆑 Fe_ed
- image: Обновление UI-панели здоровья у ксеноморфов.

2023-08-21 08:52 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2023-08-21 08:52 UTC, maleyvich commented
забыл скинуть как это выглядит внутри игры... сейчас

2023-08-21 08:59 UTC, maleyvich commented
Это не все отображения, лишь два состояния из остальных.
 ---------------------------------------------------------------------
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/104298869/4f5d206f-1715-415f-9c15-ee745c3faa8d) - 100% хп
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/104298869/c9052591-6238-4f57-afbf-2b00d4a241a9) - 50% хп

2023-08-21 11:55 UTC, maleyvich commented
а в чем смысл сего действия...

2023-08-22 03:18 UTC, maleyvich commented
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/104298869/1b134da2-beee-46f1-826f-ff442bfd60bd)
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/104298869/4eed30d1-576f-409d-a42c-dd9a1333e213)
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/104298869/a66d497c-46e1-4d20-bba3-d1700c035e2d)


вот, те самые скриншоты.

2023-08-22 04:00 UTC, AndroBetel commented
слабо счетчик плазмы сделать?

2023-08-22 04:12 UTC, maleyvich commented
> слабо счетчик плазмы сделать?

потом

2023-08-22 13:07 UTC, pro100kotah commented
Забавно, только вчера это вышло в мерж на маринах и уже сегодня он у нас на гите. Ты уи плазмы забыл. Он идет вместе с хп.

2023-08-22 13:13 UTC, maleyvich commented
> Забавно, только позавчера это вышло в мерж на маринах и уже сегодня он у нас на гите. Ты уи плазмы забыл. Он идет вместе с хп.

уи плазмы будет позже, ибо там придется поработать.

2023-08-27 22:58 UTC, volas commented
для новых иконок стоит создать отдельный новый dmi с большими размерами

2023-08-27 23:01 UTC, volas commented
спрайтдеп дергать не буду, думаю тут по отзывам игроков решим. Можешь еще превью было/стало добавить

2023-09-06 16:33 UTC, TauKitty commented
Этот запрос на слияние был упомянут в **Tau Ceti Station Forum**. Там могут быть соответствующие подробности:

https://forum.taucetistation.org/t/obsuzhdenie-novaya-poloska-zdorovya-ksenomorfoa/40698/1

2023-09-09 17:34 UTC, volas requested changes
для новых иконок стоит создать отдельный новый dmi с большими размерами (x2)

старые просто в стандартном у нас формате 32px, их трогать не нужно

2023-09-10 05:19 UTC, maleyvich commented
> для новых иконок стоит создать отдельный новый dmi с большими размерами (x2)
> 
> старые просто в стандартном у нас формате 32px, их трогать не нужно

создал новый файл в формате 32х64 (что и порекомендовало выставить), судя по диффботу старые иконки вернулись на своё место.

2023-09-13 15:54 UTC, maleyvich commented
@volas э... ну новый файл под отдельные иконки создан, все работает.

2023-09-14 04:22 UTC, volas approved these changes

2023-09-14 04:24 UTC, volas requested changes
мм, нет, почему у тебя всё еще старые иконки изменяются в 32x64

2023-09-14 04:38 UTC, maleyvich commented
чего-то я совсем ничего не понимаю.  вероятно я сделал что-то не так, просто поменяв разрешение на 32х32, однако в икондифф боте как-то всё слишком смешно выглядит.

2023-09-21 06:02 UTC, volas commented
уменьшение возможно не возможно в dmi редакторе автоматическими средствами. Просто скачай dmi файл с мастера, удали в нем лишние иконки, и залей, и в будущем помни этот опыт при попытках подергать размеры иконок.

2023-09-27 15:11 UTC, maleyvich commented
> уменьшение возможно не возможно в dmi редакторе автоматическими средствами. Просто скачай dmi файл с мастера, удали в нем лишние иконки, и залей, и в будущем помни этот опыт при попытках подергать размеры иконок.

оригинальный файл залит с удалением старых иконок здоровья, теперь точно всё готово.

2023-10-03 05:50 UTC, merged