paint the station red
TauCetiStation/TauCetiClassic pull request #11945
Opened 2023-08-22 06:01 UTC by AndroBetel

## Описание изменений
при дельта-коде лампы будут светиться красным 
пока выглядит так: 
![Screenshot_5](https://github.com/TauCetiStation/TauCetiClassic/assets/44546836/efd86aac-d146-4b65-8630-55dab2a02dbc)
![Screenshot_6](https://github.com/TauCetiStation/TauCetiClassic/assets/44546836/72dba7ef-2769-40af-824d-965007a5ea31)
![Screenshot_8](https://github.com/TauCetiStation/TauCetiClassic/assets/44546836/926c4177-89e6-4fb2-8c6f-0e92989b9e96)
но если кто-то хочет предложить другой цвет - милости прошу!
## Почему и что этот ПР улучшит
рп иммерсивность.....
## Авторство
я
## Чеинжлог
:cl:
- rscadd: При дельта-коде станция будет светиться красным.

2023-08-22 06:01 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2023-08-22 06:21 UTC, Deahaka commented
Возможно было бы лучше, если как на сс14 сделать лампочкам или хз чему анимацию конуса красного света
По памяти вот так изобразил
![1 1](https://github.com/TauCetiStation/TauCetiClassic/assets/96499407/5555f77a-c1ce-4d34-881c-5855c0e88e1b)

2023-08-22 07:21 UTC, volas commented
У нас раньше были отдельные аварийные лампочки, но куда-то пропали, кажется только иконка осталась. Они ставились посреди пола.
И на тг есть еще обычный outdor вариант, который внешнюю обшивку станции подсвечивает, это тоже интересная идея достойная стыринга.

2023-08-22 07:22 UTC, volas commented
И с оверлеями гусева можно будет действительно анимацию сделать

2023-08-22 20:54 UTC, Pivo24 commented
Блять я 7 часов играл в JRPG и в темноте ночью зашёл на гитхаб (белый цвет) и заглянул на этот ПР и увидел скриншоты и теперь у меня глазницы вытекли и я paint the мой дом red нахуй ЫАААААААААААА

2023-08-22 23:39 UTC, kiVts commented
Как насчет сделать сделать цвет немного более прозрачным и что-бы он скажем через две минуты после начала дельты  был еще более прозрачным ну или цвет менял на менее красный, и то и другое тоже самое, я просто хз если можно алфу менять в этом случае

2023-08-24 02:16 UTC, volas commented
Отложено до мержа других светоПРов. Там, кстати, красный круто выглядит.

2023-08-27 15:31 UTC, volas commented on code/modules/security_levels/security_levels.dm
> +				SSsmartlight.update_mode(/datum/light_mode/default/bulb/emergency, TRUE)
лучше добавить новый мод, этот от круглой лампочки в оружейке. По параметрам можешь скопипастить, ну или подбери что-то

2023-08-27 23:02 UTC, volas requested changes
требуется свой световой мод и обновить превью, так идея хорошая

2023-09-18 02:02 UTC, closed without merging