добавляет возможность крафта брони из ксеноморфов
TauCetiStation/TauCetiClassic pull request #11944
Opened 2023-08-22 05:25 UTC by AndroBetel

## Описание изменений
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/44546836/020bbab3-11b7-4343-a520-33ec17f9d43b)
добавляет возможность скрафтить шлем и доспех ксеноморфа (спрайты идентичны костюму из клоунской). 5 хитина и 15 проводов для шлема и 10 хитина и 30 проводов для костюма. неплохо защищает от мили и био, хуже - от пуль и совсем плохо от лазеров. 
из алиенов теперь выпадает хитин. из симпл мобов - три штуки, из обычных - пять штук, из квины - пятнадцать.
## Почему и что этот ПР улучшит
больше контента и прикольного взаимодействия с телами алиенов
## Авторство
я
## Чеинжлог
:cl:
- rscadd: Из разделанных ксеноморфов можно делать доспехи.

2023-08-22 05:26 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2023-08-24 02:25 UTC, volas requested changes

2023-08-24 02:25 UTC, volas commented on code/modules/clothing/suits/miscellaneous.dm
> +	armor = list(melee = 60, bullet = 30, laser = 25,energy = 0, bomb = 0, bio = 75, rad = 0)
для собранной на коленке брони ты слишком перекрутил значения. Особенно с сюитом, который покрывает всё тело.

И я бы вообще задумался, а нужна ли броня, у самих алиенов её ведь нет. А то выйдет, что чел в костюме самопальном алиена защищен лучше, чем сам алиен.

2023-08-25 17:25 UTC, kiVts commented on code/modules/clothing/suits/miscellaneous.dm
> +	armor = list(melee = 60, bullet = 30, laser = 25,energy = 0, bomb = 0, bio = 75, rad = 0)
Оставить значение но давать носителю берн урон по кд :peka:

2023-08-25 17:29 UTC, maleyvich commented on code/modules/clothing/suits/miscellaneous.dm
> +	armor = list(melee = 60, bullet = 30, laser = 25,energy = 0, bomb = 0, bio = 75, rad = 0)
зачем берн? гораздо логичнее по природе ксеносов токсикдемедж давать, они же кислоту выделяют

2023-08-25 17:35 UTC, ArthurPhilipDent42 commented on code/modules/clothing/suits/miscellaneous.dm
> +	armor = list(melee = 60, bullet = 30, laser = 25,energy = 0, bomb = 0, bio = 75, rad = 0)
Это нейротоксин токсик накладывает, а кислота жжет, от чего и бёрн. На маринах не играл, чтоль?

2023-08-25 17:43 UTC, Chip11-n commented on code/modules/clothing/suits/miscellaneous.dm
> +	armor = list(melee = 60, bullet = 30, laser = 25,energy = 0, bomb = 0, bio = 75, rad = 0)
Увы и ах, но Малевич в этом случае прав, к сожалению. Алиены плюются токсинами, как бы то ни было странно.

2023-09-09 12:47 UTC, AndroBetel commented
пофиг

2023-09-09 12:47 UTC, closed without merging