улучшение ролплея ии
TauCetiStation/TauCetiClassic pull request #11967
Opened 2023-08-25 04:31 UTC by AndroBetel

## Описание изменений

https://github.com/TauCetiStation/TauCetiClassic/assets/44546836/b8ea7da9-52d9-4957-8251-88048390b1f2

<details>
  <summary>кхм</summary>
   у админов в вв ии в выпадающей менюшке есть возможность дать ему "ноги", тем самым разрешая перемещаться
</details>

## Почему и что этот ПР улучшит
рп за ии
## Авторство
звук с тг
## Чеинжлог

2023-08-25 04:31 UTC, TauKitty commented
###### Changelog status: :radio_button: No changelog

2023-08-25 05:43 UTC, Slavik2001 commented
Мы с Аззи буквально недавно в шутку это сказали и угарали. Шутка вышла из под контроля

2023-08-25 06:48 UTC, DarkFurrSss commented
Буквально роллплей

2023-08-25 14:05 UTC, AirBlack commented
ass blast usa

2023-08-25 16:03 UTC, muWander commented
<details><summary></summary>
<p>
![IMG_20230825_190055_808](https://github.com/TauCetiStation/TauCetiClassic/assets/39914744/3a88432c-dc08-4df2-bac0-56555880643a)
</p>
</details>

2023-08-27 17:30 UTC, Oz1Es commented
я весёлый таракан я бегу бегу

2023-08-27 23:12 UTC, volas requested changes

2023-08-27 23:12 UTC, volas commented on code/datums/datumvars.dm
> +			return
allow_walking тебе скорее всего еще нужно запускать - для удаление верба у игрока

2023-08-27 23:12 UTC, volas commented on code/modules/mob/living/silicon/ai/ai.dm
> +		to_chat(src, "M.O.V.E. protocol has been disabled.")
нужно выключать само хождение у ИИ и убирать все оверлеи, мб просто запускать toggle_walking() если он в режиме хождения

2023-08-29 21:05 UTC, DarkFurrSss commented
> Беталь до сих пор не представляю как тебе идея пришла в голову, но это ахуенно :D

Оно что, получает дамаг будто отклбчено от сети?

2023-08-30 16:07 UTC, AndroBetel commented on code/datums/datumvars.dm
> +			return
сделал

2023-08-30 16:07 UTC, AndroBetel commented on code/modules/mob/living/silicon/ai/ai.dm
> +		to_chat(src, "M.O.V.E. protocol has been disabled.")
сделал

2023-08-30 16:07 UTC, AndroBetel commented
сделал по ревью все

2023-09-09 17:36 UTC, volas approved these changes

2023-09-09 17:36 UTC, merged