[WIP] Suit modifiser
TauCetiStation/TauCetiClassic pull request #12017
Opened 2023-09-03 00:06 UTC by Mercurialaste

## Описание изменений
Добавлена станция для модификации РИГов.

На текущий момент, может изменять рассовые требования к РИГам.

Из того, что нужно сделать на данный момент:
- [ ] Сделать проверку на наличиие спрайтов для ригов, не предназначеных для ксеносов или добавить спрайты для таковых
- [ ] Добавить возможность покупки модулей на РИГ и установку покупленных модулей, в случае, если лимит модулей забит, предлагать модуль из РИГа на извлечение.
- [ ] Нарастить механа для интересных взаимодействий по типу емага и обычных, по типу открытия станции ломом, в случае её отключения и тд.

По окончанию [WIP] опишу все в пре без ^
## Почему и что этот ПР улучшит
Удобство
## Авторство
Я, спрайты с Эриса, те, кто помогал или будет помогать в дискорде
## Чеинжлог
:cl:
- tweak[link]: Добавлена станция для модификации РИГов.

2023-09-03 00:06 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2023-09-03 08:03 UTC, AndroBetel commented
картинки интерфейса

2023-09-03 09:23 UTC, Mercurialaste commented
> 

Там радиалка, а не интерфейс.

2023-09-04 18:07 UTC, Mercurialaste commented
> Как мне кажется было бы лучше заменить в интерфейсе спрайты скафандров, на лица/тела/название текстом той или иной расы. Отличия в спрайтах скафандров на самом деле незначительные и плохо читаются.

Будут спрайты, будут изменения. Я не помню чтобы в билде был какой-либо спрайт принадлижавший конкретной расе, максимум, что могу вспомнить, это сделанные Сосискин в лор дискусе, но это также нигде не используется.
*(Если что, при наведении мыши на каждый вариант модификации, есть конкретная надпись для какой расы этот вариант, по типу, если навестись на спрайт рига предназначенного на вокса, будет написано "Vox" и тд.)*
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/90282587/9729fba5-75b2-4904-92e4-4d15d517d3a1)

2023-09-04 18:17 UTC, Mercurialaste commented
Я могу нарезать то, что сделал Сосискин, если это будет приемлемо.

2023-09-04 22:09 UTC, Mercurialaste commented
Добавил возможность емага и установки 2 модулей синдиката. В них входят:

Улучшенный модуль защиты от ЭМИ
Лазерная установка
Гранатомет с флешками, ЭМИ и дымом
Модуль для коммуникации с синдикатом

2023-09-05 07:35 UTC, Mercurialaste commented
Изменил работу ригов. Теперь они спавняться с уже вставленными шлемом и магбутсами. Шлем теперь нельзя открепить от РИГа. Есть встроенный баллон который можно использовать для дыхания. Пока что, нет только возможности его пополнять.

2023-09-05 07:47 UTC, Mercurialaste commented
Думаю добавить ещё в РИГи перчатки, которые будут надеваться на человека, если на том не надеты другие.
*(Изоляционки для инженеров и etc)*

2023-09-06 22:09 UTC, AgRevol reviewed
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/29666964/82f18939-4020-4b74-84a8-db0c259925f1)
Стол в углу невозможно достать не двигая шкафчик. Тут возможно стоило бы немного изменить комнатку чтобы всё впихнуть.
Аптечки в шкафчики мне не нравятся лично, потому что их часто лутают шахтеры, но это мое мнение скорее

2023-09-06 22:45 UTC, AgRevol requested changes
Астероид:
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/29666964/82f18939-4020-4b74-84a8-db0c259925f1)
Стол в углу невозможно достать не двигая шкафчик. Тут возможно стоило бы немного изменить комнатку чтобы всё впихнуть.
Аптечки в шкафчики мне не нравятся лично, потому что их часто лутают шахтеры, но это мое мнение скорее

Бокс:
Рекуклеры не изменены, так и задумано?
Перенос вещей парамедиков из закрытых ячеек плохо потому что они будут 100% украдены, стоит посмотреть альтернативные решения. Ну и если переносить камеру то может стоит её перенести в морг, как я сделал на гамме.
В ЕВА есть одна штука в центре, что в ней?

Гамма:
Гамму забыли :(

Центком:
Апрув

Дельта: та же проблема с парамедиками. В остальном апрув

Фалкон:
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/29666964/4a069e59-fd6f-46ed-8d54-1e7c61ab5507)
Стол в углу, беда
Остальное апрув

Прометей:
Та же проблема с парамедиками. В остальном - гуд

Астероид прометея:
Апрув

Строечка: апрув

2023-09-07 04:41 UTC, Mercurialaste commented
> В ЕВА есть одна штука в центре, что в ней?

обычный скафандр. Пришлось немного перенести его из-за того, что 2 спейс сьюта скреллов и сьют унатхов не помещались.

Остальное исправлю.

Насчет аптечек в шкафы -- шахтерам придется ради каждой аптечки или тырить целый шкаф, или просить. Можно если что просто  им добавить +2 аптечки.

> Рекуклеры не изменены, так и задумано?

Да, их сьюты в шкафах, в которых же напихано снаряжение, которое я или не могу запихнуть в сьют сторейдж и etc. если под них там будет место, мб добавлю.



> Перенос вещей парамедиков из закрытых ячеек плохо потому что они будут 100% украдены, стоит посмотреть альтернативные решения. Ну и если переносить камеру то может стоит её перенести в морг, как я сделал на гамме.

Мб верну камеру чисто для этих вещей, хотя по своей сути, среди "вещей парамедиков" уже нет ничего, что нельзя было бы достать в меде.

2023-09-07 11:02 UTC, Mercurialaste commented
> Гамма:
> Гамму забыли :(

ой

2023-09-07 11:36 UTC, AgRevol commented
> > Перенос вещей парамедиков из закрытых ячеек плохо потому что они будут 100% украдены, стоит посмотреть альтернативные решения. Ну и если переносить камеру то может стоит её перенести в морг, как я сделал на гамме.
> 
> Мб верну камеру чисто для этих вещей, хотя по своей сути, среди "вещей парамедиков" уже нет ничего, что нельзя было бы достать в меде.

И да и нет. Достать - можно. Но лучше всего когда они у парамедика и их не приходится искать у каждого интерна, который мог себе захоботить

2023-09-07 11:38 UTC, Kiromaka commented
Мб, сделать рекалор для разных отделов, но им еще тогда idшники добавлять и на карту заново ставить - спрайт я могу перекрасить, а остальное к тебе. Если захочешь конечно

2023-09-07 11:40 UTC, Mercurialaste commented
> Мб, сделать рекалор для разных отделов, но им еще тогда idшники добавлять и на карту заново ставить - спрайт я могу перекрасить, а остальное к тебе. Если захочешь конечно

если будет спрайт, сделаю.

2023-09-07 11:41 UTC, Mercurialaste commented
> > > Перенос вещей парамедиков из закрытых ячеек плохо потому что они будут 100% украдены, стоит посмотреть альтернативные решения. Ну и если переносить камеру то может стоит её перенести в морг, как я сделал на гамме.
> > 
> > 
> > Мб верну камеру чисто для этих вещей, хотя по своей сути, среди "вещей парамедиков" уже нет ничего, что нельзя было бы достать в меде.
> 
> И да и нет. Достать - можно. Но лучше всего когда они у парамедика и их не приходится искать у каждого интерна, который мог себе захоботить

Мб мне их просто выдать парамедику как профе?
Из того что я прикидываю, GPS будет в риге, только ручной монитор могут стырить по итогу, но его можно выдавать по факту взятия профы.

2023-09-07 11:45 UTC, AgRevol commented
> > > > Перенос вещей парамедиков из закрытых ячеек плохо потому что они будут 100% украдены, стоит посмотреть альтернативные решения. Ну и если переносить камеру то может стоит её перенести в морг, как я сделал на гамме.
> > > 
> > > 
> > > Мб верну камеру чисто для этих вещей, хотя по своей сути, среди "вещей парамедиков" уже нет ничего, что нельзя было бы достать в меде.
> > 
> > 
> > И да и нет. Достать - можно. Но лучше всего когда они у парамедика и их не приходится искать у каждого интерна, который мог себе захоботить
> 
> Мб мне их просто выдать парамедику как профе? Из того что я прикидываю, GPS будет в риге, только ручной монитор могут стырить по итогу, но его можно выдавать по факту взятия профы.

Хз мне как человеку который сидит в меде постоянно кажется это net negative.
Получается, что нельзя при желании украсть из закрытой ячейки мониторчик. Это делается редко но иногда надо

2023-09-07 11:47 UTC, Mercurialaste commented
> > > > > Перенос вещей парамедиков из закрытых ячеек плохо потому что они будут 100% украдены, стоит посмотреть альтернативные решения. Ну и если переносить камеру то может стоит её перенести в морг, как я сделал на гамме.
> > > > 
> > > > 
> > > > Мб верну камеру чисто для этих вещей, хотя по своей сути, среди "вещей парамедиков" уже нет ничего, что нельзя было бы достать в меде.
> > > 
> > > 
> > > И да и нет. Достать - можно. Но лучше всего когда они у парамедика и их не приходится искать у каждого интерна, который мог себе захоботить
> > 
> > 
> > Мб мне их просто выдать парамедику как профе? Из того что я прикидываю, GPS будет в риге, только ручной монитор могут стырить по итогу, но его можно выдавать по факту взятия профы.
> 
> Хз мне как человеку который сидит в меде постоянно кажется это net negative. Получается, что нельзя при желании украсть из закрытой ячейки мониторчик. Это делается редко но иногда надо

Мониторчики есть, по сути на халяву в мед вендоматах, монетки в техах и тд.
Ну, суть, хотим ли мы, чтобы мониторчики были доступны всем, но парамедики могли их не получить или даем их только парамедикам, надеясь на то, что если их не будет, смогут взять из вендомата.

2023-09-07 11:55 UTC, Deahaka commented
Положите в меинтенс лут этот хендлед монитор и не е6іть соби мозги с тем чтобы выдать парамеду в руки

2023-09-07 11:58 UTC, Kiromaka commented
> > Мб, сделать рекалор для разных отделов, но им еще тогда idшники добавлять и на карту заново ставить - спрайт я могу перекрасить, а остальное к тебе. Если захочешь конечно
> 
> если будет спрайт, сделаю.
в дс кину, гит не хочет (

2023-09-07 15:31 UTC, AgRevol approved these changes
Map dep approves

2023-09-22 00:13 UTC, Mercurialaste commented
ты - злобный робот

2023-09-24 10:25 UTC, TauKitty commented
Этот запрос на слияние был упомянут в **Tau Ceti Station Forum**. Там могут быть соответствующие подробности:

https://forum.taucetistation.org/t/shkaf-rigov-so-vsyakoj-vsyachenoj/40851/1

2023-10-15 05:53 UTC, volas commented
переоткрой, когда закончишь. Надеюсь на твой успех.

2023-10-15 05:53 UTC, closed without merging