Бесплатная Свалка на эксту
TauCetiStation/TauCetiClassic pull request #12028
Opened 2023-09-04 13:08 UTC by Deahaka

## Описание изменений
В набор Extended добавлен гейммод Junkyard, который является той же Экстой, но с включённой [свалкой ](https://github.com/TauCetiStation/TauCetiClassic/pull/1723) для гостов. Для появления такого варианта требуется не менее 30 игроков на сервере и не менее 15 нажатых Ready у игроков (то есть половина должна быть согласна отправится на станцию, а половина может начать играть в свалочку). Вероятность выпадения Свалки вместо Эксты, при выборе набора режимов "Extended" ~ 1:2 в пользу Эксты.

Из замеченного: т.к. используются уже существующие методы загрузки Свалки, загрузка раунда происходит на 5-10 секунд позже (хост с моего компа) из-за задачи контроллеру приостанавливать загрузку на 1-2 секунды при появлении задержек.

**Почему 30 человек должно быть на сервере?** На Фальконе, нашей министанции, нет Гейтвея вообще, а доступен на выбор только при онлайне <= 25 человек. Возможно буферных 5 человек будет недостаточно, тогда нужно увеличить требование к онлайну до 35.
## Почему и что этот ПР улучшит
Свалка не может быть полноценным режимом для Secret или Team Based из-за того, что она не имеет в себе никаких "антагонистов" и является PvE большую часть раунда (а если ещё бомжи не смогли пройти в Гейтвей, то вообще весь раунд), где практически нет никаких событий влияющих на экипаж. В таком случае добавление возможности поиграть в неё требует "желания" игроков сыграть без антагонистов, то есть пика набора режимов Extended. Но даже так, имея желание поиграть в свалку, игроки не имею возможности как-либо её запускать, ведь кнопка на это находится у администраторов. Теперь же всё можно через демократический воут.
## Авторство

## Чеинжлог
:cl: Deahaka
- add: Игроки иногда могут запустить Свалку, путём выбора Extended в голосовании за режимы.

2023-09-04 13:08 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2023-09-04 17:16 UTC, Kiromaka commented
> > еще бы свалка не создавала лаги для играющих на станции 😔
> 
> Ну мы ж знаем что это не существующая проблема, ведь об этом нет ни одного ишуя.

Проблемы не существует), но свалку надо фиксить прежде чем в ротацию вводить, без педалей она нормально не работает.

2023-09-04 18:04 UTC, Pirsnya commented
Как минимум придумай что-то с пауками и их коконами, ибо они заставляют сервер позже дико лагать

2023-09-04 18:05 UTC, Pirsnya commented
> > еще бы свалка не создавала лаги для играющих на станции 😔
> 
> Ну мы ж знаем что это не существующая проблема, ведь об этом нет ни одного ишуя.

Если об этом нет ишуя - не значит, что нет проблемы. Мы просто в ручную делаем массдел павуков и коконов если начинаются лаги(почти всегда)

2023-09-04 18:18 UTC, Deahaka commented
Гигантские инопланетные пауки - это вам не шутки

2023-09-04 18:41 UTC, Fenriros commented
> > > еще бы свалка не создавала лаги для играющих на станции 😔
> > 
> > Ну мы ж знаем что это не существующая проблема, ведь об этом нет ни одного ишуя.
> 
> Если об этом нет ишуя - не значит, что нет проблемы. Мы просто в ручную делаем массдел павуков и коконов если начинаются лаги(почти всегда)

Давайте удалим пауков они мешают игрокам похлеще чем сб борги

2023-09-04 20:22 UTC, Deahaka commented
Станция зачищена от пауков

2023-09-04 20:23 UTC, AndroBetel commented
а спавн бомжей пофикшен?

2023-09-04 22:08 UTC, volas commented on code/__DEFINES/mob.dm
> +#define MAX_SPIDERS_SPAWN 75
Пауков можно кастрировать и на спавнер переделать, как с мобами астеройда. Центральной области свой тип и свой спавнер. Если в области никого - они не спавнятся.

Вообще пауки имбалансны с их скоростью и ядом, можно заменить на каких-нибудь тараканов с эриса, и тогда спавнить не только в центре.

2023-09-05 04:43 UTC, Deahaka commented on code/__DEFINES/mob.dm
> +#define MAX_SPIDERS_SPAWN 75
Надо тестить, го в тест мерж

2023-09-05 16:07 UTC, Pirsnya commented
> а спавн бомжей пофикшен?
 #11980

2023-09-06 06:04 UTC, BlankCringe commented
Делай платно через кидание денег на карту воласу, и сразу мерж.

2023-09-06 17:15 UTC, Kiromaka commented
Дахака, добавь к пру -  closes #12029

2023-09-06 17:21 UTC, Deahaka commented
> Дахака, добавь к пру - closes #12029

походу не будет свалки

2023-09-06 18:42 UTC, Deahaka commented
AndroBetel подсказал альтернативу уничтожения пауков

2023-09-14 04:34 UTC, volas commented on code/game/objects/random/random_mob.dm
>  						/mob/living/simple_animal/hostile/giant_spider\
даже без nurse, сколько примерно там таким образом спавнится мобов?

2023-09-14 06:07 UTC, Deahaka commented on code/game/objects/random/random_mob.dm
>  						/mob/living/simple_animal/hostile/giant_spider\
Ну как и обычных мобов, всего в карте где-то в районе 30

2023-09-14 13:57 UTC, volas commented on code/game/objects/random/random_mob.dm
>  						/mob/living/simple_animal/hostile/giant_spider\
всё еще много. У нас есть постепенный спавнер людука на зону, есть спавнер симбаки по тригеру, лучше что-то из них использовать, чем оставлять 30 (всё еще говнокоженых) мобов бегать по зоне, в которую может никто и не заглянет.

2023-09-14 15:59 UTC, Deahaka commented on code/game/objects/random/random_mob.dm
>  						/mob/living/simple_animal/hostile/giant_spider\
Ну, посмотрел что там, переписал на компоненту Людука.

2023-09-21 06:33 UTC, volas requested changes

2023-09-21 06:33 UTC, volas commented on code/game/area/awaymission_areas.dm
> +/area/awaymission/junkyard/proc/InitSpawnArea()
это, кстати, лишнее, хз зачем людук у себя добавил

2023-09-21 06:33 UTC, volas commented on code/game/area/awaymission_areas.dm
> +	var/static/list/mob_spawn_list = list(
когда я предлагал спавнер, я подразумевал, что только для центральной зоны, которую нужно было бы разметить. Зачем на остальной части пауки и голиафы? Там если и делать, то что-то безобидное.

2023-09-21 06:39 UTC, Fenriros commented on code/game/area/awaymission_areas.dm
> +	var/static/list/mob_spawn_list = list(
Он хочет зрелищ

2023-09-25 05:35 UTC, volas commented on code/game/area/awaymission_areas.dm
> +		/mob/living/simple_animal/hostile/giant_spider/nurse = 1,
```suggestion
```

2023-09-25 05:40 UTC, volas commented
Если интересно - у Багесто где-то был еще ту-ду с доработками свалки, можно поискать

2023-09-25 05:40 UTC, volas approved these changes

2023-09-25 05:44 UTC, volas commented on code/game/gamemodes/modesbundle.dm
> +	possible_gamemodes = list(/datum/game_mode/extended, /datum/game_mode/junkyard)
это мне кажется еще лучше потом изменить, игроки ради свалки могут голосовать за обычную эксту вопреки режимам, а потом из-за рандома аутировать в обычном экстендет.

2023-09-25 05:44 UTC, merged

2023-09-25 06:19 UTC, Deahaka commented on code/game/gamemodes/modesbundle.dm
> +	possible_gamemodes = list(/datum/game_mode/extended, /datum/game_mode/junkyard)
Игрокам совсем не обязательно иметь возможность выбирать в какой вид экстендеда им играть