Добавил множество декоративных и не очень предметов.
TauCetiStation/TauCetiClassic pull request #12152
Opened 2023-09-23 20:59 UTC by DarthSidiousPalpatine

## Описание изменений
Добавил:
Настольные часы, настенные часы, настольную лампу, маятник ньютона, глобус марса, держатель для ручки, органайзер для ручек, органайзер для папок, календарь, шбмнк плакат, портрет нтшника, портрет капитана.
Респрайтнул бумагу, папки, корзину для бумаг.
Добавил пак для пополнения корзины для бумаг, заказываемую в карго.

## Почему и что этот ПР улучшит
Збс декор, украшательство, респрайт старья.

## Авторство
AndreyGysev и все все все, кто помогал в дискорде.

## Чеинжлог
 :cl:
  - rscadd: Добавлены настольные и настенные декоративные мелочи.
  - image: Респрайтнуты папки для бумаг, корзина для бумаг, бумаги.

2023-09-23 20:59 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2023-09-24 08:09 UTC, WatlerJe approved these changes

2023-09-24 16:40 UTC, volas requested changes

2023-09-24 16:40 UTC, volas commented on code/controllers/subsystem/ticker.dm
> +	update_station_head_portraits()
стоит использовать сигнал COMSIG_TICKER_ROUND_STARTING

2023-09-24 16:40 UTC, volas commented on code/game/objects/items/decorations.dm
> +/obj/item/table_deco
вводится новый лишний мета-класс, который ничего не делает, лучше избавиться

2023-09-24 16:40 UTC, volas commented on code/game/objects/items/decorations.dm
> +/obj/item/wall_deco
как и это, они лишние в структуре объектов и только делают вещи сложнее

2023-09-24 17:20 UTC, volas commented on code/game/objects/items/decorations.dm
> +		sleep(5)
слипы в процессе не стоит делать, зачем он тут?

2023-09-24 17:25 UTC, DarthSidiousPalpatine commented
обновил, получается

2023-09-24 17:26 UTC, DarthSidiousPalpatine commented on code/game/objects/items/decorations.dm
> +		sleep(5)
декоративный эффект придавали, можно без них, ща удалю

2023-09-24 17:28 UTC, DarthSidiousPalpatine commented
Теперь точно всё окей.

2023-09-25 06:11 UTC, volas commented on code/game/objects/items/decorations.dm
> +			desc = "Константин Карпатенко - ранее  адмирал ракетного флота, ныне духовный лидер флота НаноТрейзен."
```suggestion
			desc = "Константин Карпатенко - ранее адмирал ракетного флота, ныне духовный лидер флота НаноТрейзен."
```

2023-09-25 06:16 UTC, volas approved these changes

2023-09-25 06:18 UTC, volas commented on html/custom-fonts/custom-fonts.css
> +  src: url(TINIESTONE.ttf) format("truetype"), url(TINIESTONE.eof) format("embedded-opentype"), url(TINIESTONE.woff) format("woff");
я кстати думаю, что это не имеет смысла, тк шрифты используются не в вебе а маптекстом. Но пусть будет

2023-09-25 06:18 UTC, merged