Перевод Body Scanner(a)
TauCetiStation/TauCetiClassic pull request #12174
Opened 2023-09-26 10:30 UTC by AzzyDreemurr13

## Описание изменений
Перевел интерфейс body scanner(a).
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/74739991/fd7bd58d-fdad-416a-b9c7-684e5bbd2890)
## Почему и что этот ПР улучшит
Помогаем новеньким так и стареньким лучше понимать, какое переломанное тело привезли ему после мясорубки у мостика. Делаем полезные переводы для всех.
## Авторство
Перевел сам, за идею спасибо @Deahaka , и за помощь Киборгу, Пикачухе с некоторыми моментами в коде. Особое спасибо Airblack(у) и DarkFurrSss с корректировками перевода. (А также тем кто находил какие-то кривые мелочи в переводе)
## Чеинжлог
🆑 Azzy.Dreemurr
- ru: Перевод интерфейса body scanner(а) на русский язык

2023-09-26 10:34 UTC, DarkFurrSss commented on code/game/machinery/adv_med.dm
> +		dat = "<font color='blue'><B>Информация об пациенте:</B></FONT><BR>" //Blah obvious
Скорее всего будет уместнее "Информация о пациенте"

2023-09-26 10:36 UTC, DarkFurrSss commented on code/game/machinery/adv_med.dm
> +				dat += "<font color='red'>Это устройство может сканировать только человекоподобный персонал.</font>"
Лучше "Гуманоидный", более подобающий термин

2023-09-26 10:37 UTC, DarkFurrSss commented on code/game/machinery/adv_med.dm
> +				dat += text("<font color='[]'>\t-Физический урон %: []</font><BR>", (occupant.getBruteLoss() < 60 ? "blue" : "red"), occupant.getBruteLoss())
Везде "Урон от...", а тут "Физический урон". Сделал бы одинаковыми

2023-09-26 10:38 UTC, DarkFurrSss commented on code/game/machinery/adv_med.dm
> +					dat += text("<font color='red'>В кровотоке обнаружен вирусный возбудитель.</font><BR>")
Мб я глупое скажу, но попробуй "Вирусный патоген". В рус. медицине такой термин имеется

2023-09-26 10:40 UTC, DarkFurrSss commented on code/game/machinery/adv_med.dm
> +					dat += "В лобной доле обнаружено большое образование, возможно, раковое. Рекомендуется хирургическое вмешательство.<BR/>"
"В лобной доле обнаружено злокачественное новообразование, есть шанс развития рака/возможно, раковое..."

2023-09-26 10:42 UTC, DarkFurrSss commented on code/game/machinery/adv_med.dm
> +						imp += "Неизвестный в теле предмет:"
Тут так себе выглядит, мб подойдет "Обнаружен инородный предмет:"

2023-09-26 10:44 UTC, DarkFurrSss commented on code/game/machinery/adv_med.dm
> +			t1 += "Status: <B>Безсознания</B>"
Раздельно

2023-09-26 10:44 UTC, DarkFurrSss commented on code/game/machinery/adv_med.dm
> +			t1 += "Status: <B>В Сознание</B>"
"В сознании"

2023-09-26 10:45 UTC, DarkFurrSss commented
Можешь скинуть скрин как это выглядит на деле?

2023-09-26 11:04 UTC, maleyvich commented on code/game/machinery/adv_med.dm
> +	P.name = "Отчет о сканирование [occupant.name]"
пожалуйста исправь

2023-09-26 11:09 UTC, maleyvich commented on code/game/machinery/adv_med.dm
> +	P.name = "Отчет о сканирование [occupant.name]"
не ё а е, да.

2023-09-26 11:14 UTC, DarkFurrSss commented on code/game/machinery/adv_med.dm
> +	P.name = "Отчет о сканирование [occupant.name]"
Отчет (О ком/О чем?) - о Сканировании. На конце должно быть И

2023-09-26 11:14 UTC, DarkFurrSss commented on code/game/machinery/adv_med.dm
> +	P.name = "Отчет о сканирование [occupant.name]"
А лучше "Результаты сканирования"

2023-09-26 22:04 UTC, DarkFurrSss commented
А так выглядит классно

2023-09-27 06:19 UTC, AirBlack commented on code/game/machinery/adv_med.dm
> +							organ_status = "Сердечная недостаточность:"
недостаточность != failure, мб остановка сердца?

2023-09-27 06:21 UTC, AirBlack commented on code/game/machinery/adv_med.dm
> +			to_chat(usr, "<span class='notice'>Распечатка... Пожалуйста подождите.</span>")
```suggestion
			to_chat(usr, "<span class='notice'>Распечатка... Пожалуйста, подождите.</span>")
```

2023-09-27 06:22 UTC, Deahaka commented on code/game/machinery/adv_med.dm
> +			to_chat(usr, "<span class='notice'>Распечатка... Пожалуйста подождите.</span>")
Лучше "идёт печать..." наверное..?

2023-09-27 06:58 UTC, AirBlack commented on code/game/machinery/adv_med.dm
> +							organ_status = "Сердечная недостаточность:"
недостаточность это не только остановка вроде но и когда сердце слабенькое в целом

2023-09-27 06:59 UTC, AirBlack commented on code/game/machinery/adv_med.dm
> +						open = "Открытое:"
когда часть тела вскрытая, то есть когда провели первые три шага любой операции которые скальпель зажим ретрактор

2023-09-27 08:11 UTC, DarkFurrSss commented on code/game/machinery/adv_med.dm
> +							organ_status = "Сердечная недостаточность:"
Можно вписать фибриляцию, это более-менее похоже

2023-09-28 02:13 UTC, AirBlack commented on code/game/machinery/adv_med.dm
> +					var/mech = "Родные органы:"
мб не "Родные" а "Органические"? еслиб у нас можно было пересаживать органы, то технически не обязательно родные были бы

2023-09-28 02:30 UTC, AirBlack commented on code/game/machinery/adv_med.dm
> +						AN = "Не обнаружено:"
Ты че ахуел чтоли? Я это предложил потому что "Не обнаружено" уебански выглядит как говнище, none это хотя бы 4 буквы, а у тебя в переводе лютый кластерфак этими "Не обнаружено", я просто предложил хоть чуть чуть сократить

2023-09-28 02:31 UTC, AirBlack commented
Скрин в стандартном разрешении окна сделай, а не развернутого

2023-09-28 02:54 UTC, AirBlack commented on code/game/machinery/adv_med.dm
> +				storedinfo += "<th>Другие ранения</th>"
```suggestion
				storedinfo += "<th>Часть тела</th>"
				storedinfo += "<th>Ожоги</th>"
				storedinfo += "<th>Травмы</th>"
				storedinfo += "<th>Другое</th>"
```

чтоб сократить названия столбцов чтоб влезали, ну или сократить типа там Физ. Урон и тд и тп

2023-09-28 08:07 UTC, AirBlack commented
про названия то же самое с "не обнаружено", сократи как нить, я предложил пару вариантов

2023-09-28 14:08 UTC, AirBlack commented on code/game/machinery/adv_med.dm
> +						mech = "Механические:"
если у органических органов(лол) есть приписка органы, то почему у механических нет? и почему множественное число?

2023-09-28 14:08 UTC, AirBlack commented
скрины не показывают последние изменения

2023-09-28 17:23 UTC, Kiromaka requested changes

2023-09-28 17:23 UTC, Kiromaka commented on code/game/machinery/adv_med.dm
> +					dat += "В лобной доле обнаружено злокачественное новообразование, есть шанс развития рака. Рекомендуется хирургическое вмешательство.<BR/>"
Лиджард путь то добрый - но это что. 
```suggestion
					dat += "В лобной доле обнаружено новообразование, возможно злокачественное. Рекомендуется хирургическое вмешательство.<BR/>"
```
Тут раком и не пахнет - cancerous буквально злокачественное.

2023-09-28 17:24 UTC, Kiromaka commented on code/game/machinery/adv_med.dm
> +					dat += "В лобной доле обнаружено злокачественное новообразование, есть шанс развития рака. Рекомендуется хирургическое вмешательство.<BR/>"
хоть рак и злокачественная опухоль, не каждая злокачественная опухоль рак

2023-09-28 17:29 UTC, Kiromaka commented on code/game/machinery/adv_med.dm
> +					dat += "В лобной доле обнаружено злокачественное новообразование, есть шанс развития рака. Рекомендуется хирургическое вмешательство.<BR/>"
хотя в рф злокачественные раком называют. Я бы поменял, но если так подумать твой вариант тоже нормас.

2023-09-28 17:34 UTC, Kiromaka commented on code/game/machinery/adv_med.dm
> +					dat += "В лобной доле обнаружено злокачественное новообразование, есть шанс развития рака. Рекомендуется хирургическое вмешательство.<BR/>"
короче я хуйню несу. Рак - простонародный термин, не каждый вид рака это опухоль, ссылка на злокачественную опухоль как рак, может привести к недопониманию, тем более учитывая что это сканер а не человек.

2023-09-28 20:14 UTC, Kiromaka approved these changes
Лиджард уже апрувал. 👍

2023-09-29 03:50 UTC, AirBlack approved these changes
хз норм вроде только автор боргоплеер

2023-09-30 10:02 UTC, volas reviewed
Для имен органов можешь воспользоваться склонениями, не трогая оригинальный name, из https://github.com/TauCetiStation/TauCetiClassic/pull/11686/files

1. Прописать объектам органов склонения ``cases``
2. В шаблоне вместо ``BP.name`` использовать дефайн ``CASE(BP, ACCUSATIVE_CASE)``

лучше в другом ПР-е, а этот потом зависимым сделать.

2023-09-30 19:26 UTC, volas commented
я имел в виду, ты можешь сделать отдельный ПР с переводами органов, и этот будет зависим от него и после мержа органов можно к этому вернуться.

Если хочешь, можешь так и оставить, пусть спрайтдеп тогда одобряет.

2023-10-06 11:13 UTC, volas commented
Я чуть не потерял этот ПР без лейбла

2023-10-06 11:14 UTC, merged