Fabricator recycling
TauCetiStation/TauCetiClassic pull request #12191
Opened 2023-09-28 14:59 UTC by AirBlack

## Описание изменений
Добавляет переработку фабрикаторами изученных предметов. Разбирает на ресурсы, требуемые для производства такого же предмета, но умноженное на 0.8. В зависимости от размера предмета разное время разбора. 

Есть пара вопросов-недочетов, которые хотелось бы решить, но мержить можно и так. Нужен тест мерж так как что-то может пойти не так, не тестил все возможные для печати в фабрикаторах предметы.

Темы обсуждения:

1. Больше легальных способов выводить боргоплееров из игры или хотя бы настолько сильно портить им игру, чтоб они гостались и больше не заходили на наш сервер.

Если фича зайдет, могу подобную запилить и на протолат, чтобы разбирать нерабочие прототипы на ресурсы без получения очков исследования(деструктив анализатор дает только стекло и металл)

## Почему и что этот ПР улучшит
Можно вернуть часть ресурсов при разборе всяких робо штук. Учитывая постоянную нехватку ресурсов в робототехнике, мне кажется, что данная фича даст больше геймплея робототехникам.

Ну и шахтеры могут разбирать всякое говно по типу ригов.

Так же можно полностью разобрать невключающихся боргов на ресурсы, т.к. по ресурсам они довольно жирные.
## Авторство
AirBlack - код и идея
## Чеинжлог
:cl: AirBlack
 - rscadd: Возможность перерабатывать предметы в фабрикаторе.

2023-09-28 14:59 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2023-09-28 15:04 UTC, AirBlack commented
так стоп, какого хера в mining_fabricator другой код? причем я смотрю и он выглядит сука так же, тупасть, скоро поправлю

2023-09-28 15:06 UTC, AirBlack commented
увидел, там добавлен только пластик, ща уберу тупасть

2023-09-28 15:23 UTC, AirBlack commented
Все, шахтерский фабрикатор тоже теперь разбирает предметы. Можно ради ресурсов разобрать все кирки по приколу шахтерам, геймплееей.

2023-09-30 17:21 UTC, AirBlack commented
бля ну ответили бы хотя бы че нить по вопросам

2023-09-30 18:45 UTC, AirBlack commented
бля я в первом же раунде нашел арбуз, один фабрикатор улучшаем, второй нет, все из первого во второй, бесконечные ресурсы. че делать не знаю

2023-09-30 20:23 UTC, AirBlack commented
нельзя разобрать форон генератор и активированый мозг

2023-10-01 11:07 UTC, AirBlack commented
бля а ревьювить то кто-нить будет нет?

2023-10-02 06:05 UTC, Fenriros commented
Я тебе делаю глубокий поклон за это.

2023-10-02 06:51 UTC, AirBlack commented
да бля я это написал не чтобы робототехникам помочь на самом деле, а чтобы железных пидарасов разбирать безнаказанно, предлагайте че еще добавить и че пофиксить и тестите там хз там может добавить разборку всех мехов хз

2023-10-02 10:41 UTC, AirBlack commented
@volas по коду то нормально? плюс там вопросики в описании, если можешь хоть ты на них хотя бы на часть ответь.
В планах добавить переработку мехов, но это оставить на отдельный ПР так как надо будет еще у самих мехов добавить механ разборки

2023-10-02 11:51 UTC, volas commented on code/game/mecha/mech_fabricator.dm
> +	if(I.use_tool(src, user, I.w_class * FABRICATOR_ITEM_RECYCLE_SIZE_TO_TIME_MODIFIER, required_skills_override = list()))
юзтул у нас для всяких расходников, думаю его тут не стоит использовать. Иначе какая-нибудь горелка будет пытаться разварить фабрикатор, а краска покрасить. Можно сделать дуафтер, и после него отдельно проверять положение предмета и что он еще существует

2023-10-02 11:57 UTC, AirBlack commented on code/game/mecha/mech_fabricator.dm
> +	if(I.use_tool(src, user, I.w_class * FABRICATOR_ITEM_RECYCLE_SIZE_TO_TIME_MODIFIER, required_skills_override = list()))
ну технически в момент того как кладешь в фабрикатор предмет превращается в расходник, если в дуафтер можно сделать проверку не ПОСЛЕ а ВО ВРЕМЯ, чтобы прогрессбар сбрасывался сразу если че-то с итемом произошло, то тогда поменяю, иначе ну слишком коряво будет выглядеть хз и уж лучше потерпеть горелочку(учитывая то что подобные предметы скорее всего до юз тула не доберутся) чем терпеть кривоту

2023-10-02 11:58 UTC, volas commented on code/game/mecha/mech_fabricator.dm
> +	if(I.use_tool(src, user, I.w_class * FABRICATOR_ITEM_RECYCLE_SIZE_TO_TIME_MODIFIER, required_skills_override = list()))
в дуафтер можно добавить каллбек с проверкой

2023-10-02 12:46 UTC, AirBlack commented on code/game/mecha/mech_fabricator.dm
> +	if(I.use_tool(src, user, I.w_class * FABRICATOR_ITEM_RECYCLE_SIZE_TO_TIME_MODIFIER, required_skills_override = list()))
который в процессе будет работать? если да то переделаю

2023-10-03 10:04 UTC, AirBlack commented
э а че тм убрали норм же

2023-10-10 12:16 UTC, AirBlack commented
а че не так то

2023-10-11 06:47 UTC, volas commented
могу вернуть в тм, мне просто показалось оно еще ворк ин прогресс

2023-10-13 19:11 UTC, AirBlack commented
ща попробую в ду афтер и добавлю списочек с тем что можно разбирать даже с contents, в который потом можно будет добавлять чего да.

2023-10-26 02:10 UTC, volas commented
do it

2023-10-30 17:07 UTC, AirBlack commented
а я забыл совсем ща поковыряюсь

2023-10-30 17:45 UTC, AirBlack commented
на do_after переделал, ща добавлю исключения по contents и нашел баг с рецуклингом мехов, то что считается только chasis по ресурсам

2023-10-30 20:11 UTC, AirBlack commented
Вроде я проверил ВООБЩЕ ВСЕ ПЕЧАТАЕМЫЕ ПРЕДМЕТЫ В ФАБРИКАТОРЕ И ШАХТЕРСКОМ И РОБОТОТЕХНИЧЕСКОМ и вроде все ок, спецом проверил че будет с мобом в позитронке(гостанется прост, все ок), починил рантайм при рецукле кабле лауера, мне лень очень было делать норм переработку мехов и меха врекадже так что только по отдельности части можно, но их с шасси не снять если поставил, мне лень делать снятие и похуй короче на них, может потом когда-нибудь сделаю разборку полную мехов

2023-10-30 20:13 UTC, AirBlack commented
да ты ахуел линтер ебаный я тебя в рот ебал тварь

2023-10-30 20:19 UTC, AirBlack commented
ну сейчас то что сука

2023-10-30 20:53 UTC, AirBlack commented on code/game/mecha/mech_fabricator.dm
> +	var/global/list/allowed_recycling_assembled_types = list(
а почему ему быть не глобальным? он никак не меняется и статичен для всех инстансов всех фабрикаторов всех видов, хотя можно и убрать, разницы мало

2023-10-30 20:53 UTC, AirBlack commented on code/game/mecha/mech_fabricator.dm
> +	var/global/list/disallowed_types = list(
не ругается

2023-10-30 20:56 UTC, AirBlack commented on code/game/mecha/mech_fabricator.dm
> +	var/global/list/allowed_recycling_assembled_types = list(
логичнее на статик поменять, а вообще уберу, нафиг с этим заморачиваться еще

2023-10-31 14:57 UTC, volas commented on code/game/mecha/mech_fabricator.dm
> +	if(!recycling_check_contents_empty(I)) // Needs review. Check to prevent recycling whole rigs/assembled borg endoskeletons.
~~тут какое-то всё сложное, странное, и сам код мех фабрикатора непонятное древнее говно без комментариев, и я не понимаю зачем ему деконструкцию надо добавлять, когда уже есть автолат, и зачем я это ревьюваю, ведь сейчас ты уже лучше меня разбираешься в фабрикаторе.~~

Почему-то черный список определяется здесь, белый список allowed_recycling_assembled_types где-то там, проверка на контентс непонятная зачем и как, то применяется, то нет, и какие вообще типы принимаются для деконструкта (спойлер: ограничено дизайном, но об этом мы узнаем позже а не сразу). Всё как-то слишком разбросано.

То что мы имеем дизайн - можно было бы проверять сразу где-то тут, находить и сохранять его для возможного дальнейшего применения. И саму валидацию получше сгруппировать.

2023-10-31 14:57 UTC, volas commented on code/game/mecha/mech_fabricator.dm
> +	return list()
тут я понимаю, что ищется дизайн, пытается по нему узнать ресурсы, но каким образом - черт ногу сломит. ``get_resource_cost_w_coeff`` не откомменчен, вроде считает какие-то свои ресурсы с какими-то коэффициентами, но для производства, а здесь еще сверху какой-то коэффициент бросается.

И полностью игнорируются m_amt и g_amt, которые уже использует автолат, стоящий рядом. Разные способы деконструкта - разные возможные дюпы. Я бы предложил в произведенные фабрикатором вещи записывать их m_amt и g_amt, и дописать прочие материалы в сам предмет. Потом при разборе брать ресурсы с параметров предмета.

Еще может отрефакторить этот момент в отдельный модуль машинерии, который бы был общим у автолата и фабрикатора, дабы не копипастить.

2023-10-31 15:20 UTC, AirBlack commented on code/game/mecha/mech_fabricator.dm
> +	if(!recycling_check_contents_empty(I)) // Needs review. Check to prevent recycling whole rigs/assembled borg endoskeletons.
Разборку в фабрикатор я добавлял только для того, чтоб потом в раундах разбирать боргов так как боргоплееры лохи, но потом так подумал слегонца, и этой фичи реально РнД не хватает как в автолате, так и в фабрикаторе, чтобы бракованые детали разбирать на ресурсы. Автолат разбирает только на стекло и металл, фабрикатор же начнет разбирать на все виды ресурсов.

Черный список объявляется тут чтобы дальше не падать в другие проверки. Белый список далее - отдельный белый список на именно проверку contents, так как проверено что в этих именно типах белого списка изнутри contents не вытащить. Вообще проверка на contents нужна, чтобы по случайности не разобрать допустим дрель или риг не высунув модули/батарейки.

Спецом убрал нахождение дизайна в отдельный прок для возможности разборки вещей без дизайна, либо вообще переделать алгоритм получения ресурсов. были мысли о добавлении полного разбора mecha wreckage(которых в дизайне нет но логично что можно было бы переработать), но реализовывать было лень. Это по поводу того что дизайн в отдельном проке.

2023-10-31 15:26 UTC, AirBlack commented on code/game/mecha/mech_fabricator.dm
> +	return list()
m_amt и g_amt это только два вида ресурсов, в значения их я не смотрел, но считаю нужным получать именно нужные для производства ресурсы, т.к. они содержат не только стекло и железо, но и форон/пластик/уран/серебро и тд и тп. Было бы хорошо хранить затраченые ресурсы в предметах, но тогда уже в другом ПРе когда прикручу переработку и протолатам, да и хранить эти хреновы листы ну такое себе конечно. Все рефакторы и выносы именно из фабрикатора думаю стоит делать в отдельном ПРе в котором уже можно будет это все нормализовать и стандартизировать. Пока только так, но если есть идеи, как можно сделать быстро и хорошо, то можно попробовать

2023-11-01 08:20 UTC, AirBlack commented
Я к чему веду, рефактор и стандартизация разбора предметов и упразднение m_amt и g_amt должны делаться в отдельном ПРе по моему мнению. Эта же фича изолирована и можно смержить так, даже если рефактора не будет...

2023-11-20 14:14 UTC, Deahaka approved these changes
Думаю надо тестить. Хуже все равно не будет!

2023-11-21 11:23 UTC, AirBlack commented
волес просит кое что сделать сексуально тематическое требует реFUCKторнуть всю систему сборки и упразднить m_amt и g_amt объединив все реальные данные о сборке в какой нить cockstruction как на тг, а мне этим пиздец лень заниматься

2023-11-21 14:56 UTC, volas commented
это необходимо, иначе честную сборку/разборку не сделать. Как альтернатива, если этот ПР вперед - тут можно использовать уже значения стекла и металла из объектов, вместо листания дизайнов, и прочие материалы пока будут отсутствовать, пока кто-то не добавит их предметам тоже.

2023-11-22 08:01 UTC, AirBlack commented
хоть этот ПР и создавался только в целях разбора боргоплееров и вывода их из игры, однако разборка именно на разные материалы - главная фишка данного ПРа и принятие полумер по типу чисто разборки на m_amt и g_amt ну такое себе, пусть лежит до дальних времен когда появится время у мисье аирблека на ковыряние трупа хуем

2023-11-26 15:49 UTC, AirBlack commented
guess what

2023-11-26 15:54 UTC, AirBlack commented
менял регекспами, то что крашится все ок не может же все сразу работать

2023-11-26 16:07 UTC, AirBlack commented
Почему у /obj/item есть var/list/materials? Я не вижу где он используется вообще

2023-11-26 19:10 UTC, AirBlack commented
можете ревувать это говно

2023-11-28 15:55 UTC, AirBlack commented
review when?

2023-11-29 08:37 UTC, Deahaka reviewed
Извини, не вникал в то что там за вопросы с дизайнами рнд, просто глянул на общий вид.

2023-11-29 08:37 UTC, Deahaka commented on code/game/mecha/mech_fabricator.dm
> +			update_icon()
Не до конца уверен, но вроде как иконка должна меняться через аргументы дефолт деконстракшена.

2023-11-29 08:37 UTC, Deahaka commented on code/game/mecha/mech_fabricator.dm
> +		for(var/material as anything in materials_to_add)
```suggestion
		for(var/material in materials_to_add)
```
Тут тоже скорее всего лишнее

2023-11-29 08:37 UTC, Deahaka commented on code/game/mecha/mech_fabricator.dm
> +	// TODO: Maybe add mecha wreckage and mecha chassis recycling
```suggestion
	// TODO: Maybe add mecha wreckage and mecha chassis recycling
```
`Maybe add mecha wreckage recycling` — Nonono
Разве не круто что его по частям разбирают сейчас, лучше пусть так.

2023-11-29 08:37 UTC, Deahaka commented on code/game/mecha/mech_fabricator.dm
> +	for(var/material as anything in resources)
```suggestion
	for(var/material in resources)
```
/me shakes head

2023-11-29 08:37 UTC, Deahaka commented on code/game/objects/items/stacks/tiles/plasteel.dm
> +	construction = MAT_METAL+"=937.5"
Кто эти цифры сюда поставил)))

2023-11-29 11:44 UTC, AirBlack commented on code/__HELPERS/_lists.dm
> +	for(var/key as anything in params_list)
я по привычке ебанул, надо бы убрать да спасибо

2023-11-29 11:45 UTC, AirBlack commented on code/game/machinery/doors/airlock.dm
> +			if (params2numberlist(i.construction)[MAT_METAL])
были мысли просто геттер/сеттер в прок отдельный выделить, но тогда было уже 3 ночи перед понедельником и я не хотел умереть на работе, тут вполне приемлемо

2023-11-29 11:45 UTC, AirBlack commented on code/game/mecha/mech_fabricator.dm
> +			update_icon()
я тут табуляцию менял, код старый

2023-11-29 11:47 UTC, AirBlack commented on code/game/mecha/mech_fabricator.dm
> +	// TODO: Maybe add mecha wreckage and mecha chassis recycling
меху вообще ре разобрать, коммент относится к принимаемому типу, меха врекаджи не obj/item, а просто obj, у меха врекадже нету данных о ресурсах(хотя можно было бы, сейчас это изи добавить, коммент писался тогда когда кол-во ресурсов из дизайна бралось)

2023-11-29 11:48 UTC, AirBlack commented on code/game/objects/items/stacks/tiles/plasteel.dm
> +	construction = MAT_METAL+"=937.5"
не моя проблема, я тоже офигел

2023-11-29 12:23 UTC, AirBlack commented on code/game/mecha/mech_fabricator.dm
> +	// TODO: Maybe add mecha wreckage and mecha chassis recycling
и в плане mecha wreckage я имел в виду саму груду, по частям ты разобрал и в итоге больше ничего не вытащить а груда осталась, можно было бы пихнуть в фабрикатор

2023-12-01 13:44 UTC, AirBlack commented
я сначала обиделся что меня опять педали гондоны запермамьютили везде и в дискорде и в дедчате но потом вспомнил что цель ПРа поднасрать игрокам и кодерам поэтому переоткрываю

2023-12-02 14:03 UTC, AirBlack commented
и про мут ахелпа и оока, но они были и раньше, а недавно меня еще и в дискорде и снова в дедчате замутили

2023-12-06 16:00 UTC, LudwigVonChesterfield commented on code/defines/obj/hydro.dm
> +	construction = MAT_METAL+"=200;"+MAT_GLASS+"=50"
почему не списком? construction = list(MAT_METAL = 200, MAT_GLASS = 50)

2023-12-06 16:00 UTC, LudwigVonChesterfield commented on code/__HELPERS/_lists.dm
> +/proc/numberlist2params(list/number_list)
если construction сделать ассоциативным списком можно без этих функций

2023-12-06 16:10 UTC, AirBlack commented on code/defines/obj/hydro.dm
> +	construction = MAT_METAL+"=200;"+MAT_GLASS+"=50"
потому что почитай коммиты. листы - объекты, через initial() не получить, а автолаты через construction берут ресурсы нужные для производства без создавания объектов чисто через типы, короче вот да, изначально через лист красиво было но автолат сказал "иди нахуй говно"

2023-12-06 16:12 UTC, AirBlack commented on code/__HELPERS/_lists.dm
> +/proc/numberlist2params(list/number_list)
у меня мут в дискорде так бы я в рнд ответил я щас вот тебя читаю че ты там калякаешь

2023-12-06 16:19 UTC, LudwigVonChesterfield commented on code/__HELPERS/_lists.dm
> +/proc/numberlist2params(list/number_list)
выходит что из-за каки там появляется кака тут :pensive:

2023-12-07 18:45 UTC, AirBlack commented on code/defines/obj/hydro.dm
> +	construction = MAT_METAL+"=200;"+MAT_GLASS+"=50"
ладно я могу вернуть листы если ментейнеры дадут добро на создание каждого предмета в автолате при генерации рецептов, и кто одобрит того имя я помещу в коммент под кодом чтобы все знали кто ответственен за каку

2023-12-08 09:34 UTC, AirBlack commented
идея с таким подходом кстати не моя, я ее спиздил из дизайнов где писались уровни исследования, они так же записаны но без убогих плюсов так как там нету дефайнов

2023-12-11 12:50 UTC, AirBlack commented
зацените мой диагноз

F32.10 – Депрессивный эпизод средней степени без соматических симптомов

2023-12-11 13:32 UTC, AndroBetel commented
педовка ты

2023-12-12 07:44 UTC, AirBlack commented
плевать что пиздят крысы за спиной у кисы, теперь я на антидепрессантах и мне похуй ваще или не похуй хуй знает седня первый день

2023-12-14 08:14 UTC, volas commented
Макрос тут хороший не сделать, так как мы не можем запихать динамический код в объявлении переменной и всё пришлось бы делать на уровне препроцессора. А итерация силами препроцессора даже просто по динамическому набору параметров уже какое-то извращение, в определенном формате вообще не возможно.

Так что я бы просто предложил изменить
> ``construction = MAT_METAL+"=200;"+MAT_GLASS+"=50"``

на
> ``construction = "[MAT_METAL]=200;[MAT_GLASS]=50"``

2023-12-14 15:04 UTC, AirBlack commented
Я сначала так попробовал, но интерполяция строк через [penis] не работает в статике даже если внутри статические константы. Ошибка компиляции, ругается на то что динамическое чето там. Только через плюс

2023-12-15 03:09 UTC, volas commented
пипец. Можно тогда деградировать еще дальше, и вместо MAT_METAL писать сразу "metal", прям как в техах. Оно тут нужно было бы только лишь очепятки предотвратить, но можно было бы это сделать отдельной регуляркой в CI

2023-12-17 17:24 UTC, AirBlack commented
Ну CI это не моя проблема, и все-таки лучше мне кажется дефайны использовать

2023-12-19 08:16 UTC, volas requested changes
> Ну CI это не моя проблема, и все-таки лучше мне кажется дефайны использовать

можешь оставить как есть, но мне кажется так было бы читаймей и красивее. Тест я сам потом могу написать, в любом случае это не помешало бы и технологиям, и стоило бы в целом проверять валидность формата params и что кодер не опечатался с каким-нибудь лишним ``;``. Регулярку будет проще написать, если оно в одном формате.

2023-12-19 08:16 UTC, volas commented on code/game/mecha/mech_fabricator.dm
> +	var/resource_coeff_recycle = 0.6
эти всё коэффициенты что-то сложное и не очевидное, одна опечатка или неосторожный патч и космонавт сможет дюпать ресурсы. Особенно с учетом других разборщиков типо автолата, где свои алгоритмы.

Но можно оставить уже на потом.

2023-12-19 08:16 UTC, volas commented on code/game/objects/items/devices/flashlight.dm
> +	construction = MAT_METAL+"=0;"+MAT_GLASS+"=0"
```suggestion
	construction = null
```

2023-12-19 08:16 UTC, volas commented on code/game/objects/items/devices/flashlight.dm
> +	construction = MAT_METAL+"=0;"+MAT_GLASS+"=0"
```suggestion
	construction = null
```

2023-12-19 08:16 UTC, volas commented on code/game/objects/items/devices/radio/headset.dm
> +	construction = MAT_METAL+"=75;"+MAT_GLASS+"=0"
```suggestion
	construction = MAT_METAL+"=75"
```

2023-12-19 08:16 UTC, volas commented on code/game/objects/items/stacks/sheets/glass.dm
> +	construction = MAT_GLASS+"=0"
```suggestion
	construction = null
```

2023-12-19 08:16 UTC, volas commented on code/game/objects/items/stacks/sheets/glass.dm
> +	construction = MAT_METAL+"=0;"+MAT_GLASS+"=0"
```suggestion
	construction = null
```

2023-12-19 08:16 UTC, volas commented on code/game/objects/items/stacks/sheets/sheet_types.dm
> +	construction = MAT_METAL+"=0"
```suggestion
	construction = null
```

2023-12-21 03:00 UTC, AirBlack commented on code/game/objects/objs.dm
> +	var/construction = "" // Resources used for construction
да я это видел но не понял нахера оно нужно, там где-то в комментах я отписывал

2023-12-21 03:02 UTC, AirBlack commented on code/game/objects/objs.dm
> +	return contents.len == 0
я же убрал disallowed_types. так написал чтобы кучу логики в рецукле не срать с проверкой на contents, делать рекурсивный разбор слишком муторно, делать разбор уничтожая все внутри нечестно

2023-12-21 03:03 UTC, AirBlack commented on code/game/objects/items/weapons/tools.dm
> +	construction = MAT_GLASS+"=30"
менял регекспом, видимо пропустил

2023-12-21 03:04 UTC, AirBlack commented on code/game/mecha/mech_fabricator.dm
> +	var/resource_coeff_recycle = 0.6
я там в итоге все равно делаю min(1, coeff)

2024-01-19 01:59 UTC, AirBlack commented
@TauCetiStation/maintainers переоткройте я на выхах поковыряю

2024-01-23 23:55 UTC, LudwigVonChesterfield commented on code/defines/obj/hydro.dm
> +	construction = MAT_METAL+"=2550"
@volas Точно не лучше было бы иметь отдельный список `var/list/construction_materials` и `var/list/materials` которые *сейчас* есть в штучке?

2024-01-24 02:27 UTC, volas commented on code/defines/obj/hydro.dm
> +	construction = MAT_METAL+"=2550"
у атомов он должен быть выпилен в пользу этого общего формата, эти списки непонятно как в билд занесло и они нигде не используются.

И текстовый формат лучше в том плане, что мы можем через init() его достать (ну и меньше памяти занимает). Он выглядит жутко, но лучше это хоть убейся сейчас не оформить.

2024-01-24 10:51 UTC, AirBlack commented on code/defines/obj/hydro.dm
> +	construction = MAT_METAL+"=2550"
докажи

2024-01-24 12:51 UTC, volas commented on code/defines/obj/hydro.dm
> +	construction = MAT_METAL+"=2550"
:: просто шорткат для init, он не поможет. Списки инициализируются вместе с объектом, на своём скрытом шаге инициализации (типо New), и до инициализации объекта не доступны.

Хорошие новости - Люммокс согласен, что это проблема, и рассматривает варианты как это можно решить https://www.byond.com/forum/post/2904278#comment26636169

2024-01-26 10:44 UTC, AirBlack commented on code/defines/obj/hydro.dm
> +	construction = MAT_METAL+"=2550"
пикачушка же в рнд присылал что через :: можено получать листы и оно работает

2024-01-29 03:19 UTC, volas commented on code/defines/obj/hydro.dm
> +	construction = MAT_METAL+"=2550"
это позже случилось, я видел. Лучше на листы тогда переделать. 

Но нужно будет еще замерить встроенным профайлером память до и после чисто из интереса.

2024-01-30 12:03 UTC, AirBlack commented on code/defines/obj/hydro.dm
> +	construction = MAT_METAL+"=2550"
тогда ПР ждет 515? если да отметьте там чтоб пр не закрывался там хз

2024-01-30 19:35 UTC, LudwigVonChesterfield commented
@AirBlack Закрепил ПР, в ожидании 515.

Я бы предложил заранее выкатить ПР с списком, теперь когда всё будет на списках думаю могу взять ревью на себя.

2024-01-30 19:46 UTC, volas commented on code/defines/obj/hydro.dm
> +	construction = MAT_METAL+"=2550"
мы уже на 515, делай

2024-01-31 15:03 UTC, AirBlack commented on code/defines/obj/hydro.dm
> +	construction = MAT_METAL+"=2550"
skill issue

2024-01-31 20:27 UTC, LudwigVonChesterfield commented
меня обманули со списками.

2024-02-01 05:33 UTC, AirBlack commented
У меня есть идея как оставить списки и воспольщоватьсся :: в генерации автолатов, я попробую, если не получится, то хуйова

2024-02-05 08:00 UTC, AirBlack commented
немного занят был на днях простите

2024-02-21 20:34 UTC, AirBlack commented
меня разбанили друзья

2024-02-28 09:14 UTC, AirBlack commented
ладно мне лень и посрать как-то и я перестал играть, если вернусь, может закончу, хз

2026-05-17 07:18 UTC, AirBlack commented on code/modules/research/designs.dm
> +(??)
это убрал, это я не разобрался с mend тулзой, простите

2026-05-17 11:02 UTC, AirBlack commented on code/defines/obj/hydro.dm
> +	construction = MAT_METAL+"=2550"
upd 2026: Я еще раз попытался как-нибудь сделать списком. Оператор :: не помог вообще, статические переменные нельзя переобъявлять. Попытался через #define MATERIALS(args...) #args чтобы он в строку все аргументы перевел с названиями, но он тогда реально просто в строку делает и не заменяет уже текущие препроцессоры. т.е. MATERIALS(MAT_METAL=50) превратится в "MAT_METAL=50" а не в ""metal"=50". Если есть идеи - готов выслушать. А пока если все-таки вводить фичу, то только с конкатенацией строк через плюсы...

2026-05-17 11:39 UTC, AirBlack commented on code/game/objects/objs.dm
> +	var/construction = "" // Resources used for construction
нигде не использовалось, заменил на строковый мой формат.

2026-05-17 11:41 UTC, AirBlack commented on code/game/objects/objs.dm
> +	return contents.len == 0
открыто к обсуждению. рекурсивный разбор не вариант т.к. для разбора определенных предметов может присутствовать своя логика.

2026-05-17 11:47 UTC, AirBlack commented on code/game/objects/items/stacks/tiles/plasteel.dm
> +	construction = MAT_METAL+"=937.5"
Округлил до тысячи

2026-05-17 11:56 UTC, AirBlack commented on code/game/machinery/doors/airlock.dm
> +			if (params2numberlist(i.construction)[MAT_METAL])
Проверяется у atom/movable/mover, а не у двери. Может иметь неактуальные данные и конфликтнуть с изменением materials после инита(допустим когда в автолате напечатали, там заменяется materials чтобы не дюпать материалы). Пока что убрал проверку раз такое в canpass не стоит делать, будет искрить при любом бампе с любым мувером.

2026-05-17 12:05 UTC, AirBlack commented on code/game/machinery/doors/airlock.dm
> +			if (params2numberlist(i.construction)[MAT_METAL])
Добавил за место проверки материалов проверку на флаг CONDUCT

2026-05-17 12:18 UTC, AirBlack commented
Кто придумает нормальное решение как в автолате получить от сырого типа список материалов не через строку а через list и все это без создания объекта а чисто по типу, скину 200 рублей на карту.

2026-05-17 14:27 UTC, AirBlack commented
пока кушал идейка пришла в голову, а че если мы цену за производтство в автолате всунем в датум дизайна и просто на все предметы наделаем дизайнов типа как в консоли рнд? там же датумы, их можно спокойно инициализировать не боясь сайд эффектов. а переменную materials у итемов оставим чисто под разборку и сделаем ее листом красивым

2026-05-20 02:03 UTC, LudwigVonChesterfield commented on code/game/mecha/mech_fabricator.dm
> +#define FABRICATOR_ITEM_RECYCLE_SIZE_TO_TIME_MODIFIER 5 // Item.size * modifier is the time required to recycle an item.
```suggestion
#define FABRICATOR_ITEM_RECYCLE_SIZE_TO_TIME_MODIFIER (0.5 SECONDS) // Item.size * modifier is the time required to recycle an item.
```

2026-05-20 02:04 UTC, LudwigVonChesterfield commented on code/game/mecha/mech_fabricator.dm
> +			return materials_to_add
а почему нельзя деталям прописывать при производстве их материалы

2026-05-20 02:05 UTC, LudwigVonChesterfield commented on code/game/mecha/mech_fabricator.dm
> +	return user.Adjacent(src) && item.Adjacent(src) && user.Adjacent(user)
user.Adjacent(user) ?

2026-05-20 02:06 UTC, LudwigVonChesterfield commented on code/game/objects/items.dm
> +	var/chance = w_class / (qual_prying * (params2numberlist(materials)[MAT_METAL] || 0) + 1)
увидел это и как-то захотелось чтобы когда ломиком ломаешь вещи тоже есть небольшой шанс как-то реклеймнуть материалы...

2026-05-20 02:08 UTC, LudwigVonChesterfield commented on code/modules/research/destructive_analyzer.dm
> +			for(var/material as anything in loaded_item_materials)
хмммммммм. я почему-то думал что только фабрикатор роботов будет разбирать. надо будет перечитать ПР...

2026-05-20 02:09 UTC, LudwigVonChesterfield commented
@AirBlack вроде хайповый ПР мне всё нравится только я не понял а зачем теперь деструктив аналайзер даёт ученым рерусы с разбираемых вещей.

я думал что задумка типо чтобы роботехи стали помойщиками делающими из говна и палок роботов.

2026-05-20 04:20 UTC, volas commented
> Если есть идеи - готов выслушать.

Этот вопрос списков актуальный и для переводов/падежей, я с этим тоже долго сидел. 

Моя лучшая идея была с макросом, который бы формировал текстовое представление списка, совместимое с [params2list](https://cdn.taucetistation.org/byond/ref/#/proc/params2list)/[list2params](https://cdn.taucetistation.org/byond/ref/#/proc/list2params), и где надо мы бы просто делали list2params от строки (ну или в другом формате, хоть json, не обязательно params). Но всё упиралось либо в девятиэтажные по вложенности макросы, либо в очередные ограничения [бьенда](https://www.byond.com/forum/post/2904067), я не ушел далеко. И всё равно оверхед с доступом не очень был бы.

> пока кушал идейка пришла в голову, а че если мы цену за производтство в автолате всунем в датум дизайна и просто на все предметы наделаем дизайнов типа как в консоли рнд? 

Датум-синглтон к каждому атому прописывать уныло, может быть если бы это автоматизировалось, возможно это уже будет похоже на SSmaterials с тг. Но этот вариант меня немного тоже коробит - вот у нас уже есть прототип объекта, идеально для задачи, но из-за бьенда нельзя, делайте свои обертки...

2026-05-20 04:40 UTC, volas commented
Пока писал, появилась еще мысль. Может забыть про списки/единую переменную материалов. Можно попробовать варианты макроса, который бы разворачивался в набор сетапов для переменной (т.е. как сейчас, просто обернуть в макрос который бы еще занулял переменные по умолчанию). 

Условно что-то вроде

```
#define MATERIALS(METAL, GLASS, ...) {
 m_amt = METAL
 g_amt = GLASS
}

/atom
   var/m_amt = 0
   var/g_amt = 0

/atom/thing
   MATERIALS(100, 0)
   
```

Плюсы: это не список, переменные всегда доступны, в т.ч. с initial(). Память тоже не теряем - насколько помню, бьенд использует var прототипа, если атому свой экземпляр не требуется. И можно без проблем переопределить материалы конкретного объекта в рантайме, если надо.

Но надо исследовать, у макросов нет named-аргументов, надо посмотреть можно ли это как-то лучше и читабельно оформить, или будет та же засада, что и со списками. Если получится адекватно и без большой вложенности макросов, то может быть вариант.

2026-05-20 05:44 UTC, AirBlack commented
> аналайзер даёт ученым рерусы с разбираемых вещей.

зачем ученых от мусорного геймплея обрезать? ну и вроде я до сих пор зануляю материалы на созданых из протолата прототипах, т.е. ученые не смогут дефектив прототипы разобрать, а вот всякую шелупонь по станции насобирать на ресурсы смогут

2026-05-20 06:02 UTC, AirBlack commented on code/game/mecha/mech_fabricator.dm
> +	return user.Adjacent(src) && item.Adjacent(src) && user.Adjacent(user)
дело было давно и неправдой... да надо убрать

2026-05-20 06:07 UTC, AirBlack commented on code/game/mecha/mech_fabricator.dm
> +			return materials_to_add
мне наверн было западло дефолтные материалы дублировать из датумов дизайна в сами итемы(чтоб реально из мусора разбирать вещи на редкие ресурсы а не на сталь и стекло), но щас мб не лень будет и да так лучше будет.

2026-06-19 06:25 UTC, closed without merging

2026-07-17 22:46 UTC, volas commented
По датуму-синглтону, есть такой вариант https://github.com/DaedalusDock/daedalusdock/pull/1356/ и мне он нравится, даже навайбкоденный скрипт в комплекте для автоматизации.