Imposters code refactor + small feature
TauCetiStation/TauCetiClassic pull request #12200
Opened 2023-10-01 07:22 UTC by Deahaka

## Описание изменений
Переписал проверки профессий в коде импостеров, убрав инициализацию сабтайпов и мелкий хардкод листа.

Немного изменил процесс набора людей в фракции, чтобы фракции с нулём максимума ролей на старте не набирали никого и просто скипались. Сделал появление импостеров не в начале раунда, а со временем.
Мотивировано тем, что обдумывая методы препятствию раундстарт попыток резать кого-либо с оружием профессий (конкретно лазерное оружие у глав), было сформулировано требование хотя бы подождать пока жертвы эквипнут что-то или разбегутся по своим делам, что сделает такую тактику в разы менее успешной, а следовательно больше шанс на какой-то амогус.
## Почему и что этот ПР улучшит
сделал код лучше, сделал режимчик продуманнее.
## Авторство

## Чеинжлог

2023-10-01 07:22 UTC, TauKitty commented
###### Changelog status: :radio_button: No changelog

2023-10-01 21:06 UTC, LudwigVonChesterfield commented on code/game/gamemodes/factions/autotraitors.dm
> +	// No imposters on roundstart
на самом деле прикольное наказывание ролеплееров которые заходят после раундстарта чтобы гарантировать что им не выпадет роль.

2023-10-01 22:10 UTC, AgRevol commented on code/game/gamemodes/factions/autotraitors.dm
> +	// No imposters on roundstart
Префы: существуют

2023-10-04 15:10 UTC, LudwigVonChesterfield commented on code/game/gamemodes/factions/autotraitors.dm
> +	// No imposters on roundstart
ах да ещё надо будет как-нибудь наказывать тех кто заходят после раундстарта чтобы на НИХ не выпала целька...

2023-10-06 11:21 UTC, volas commented
Там многие жаловались, что импостеры игнорируют префы персонажей, это поправлено?

2023-10-06 11:24 UTC, Deahaka commented
Ну когда тот фикс с `player_list` залили, полагаю что да.

2023-10-08 15:43 UTC, volas commented on code/game/gamemodes/roles/traitor.dm
> +		var/count = 1
count нигде не инкрементируется, и в декларе они все под 1 номером. отсутствующий win/loss мб тоже с этим связан, не знаю

2023-10-08 16:26 UTC, volas commented on code/game/gamemodes/roles/traitor.dm
> +/datum/role/traitor/imposter/Declare()
считаю, что убирать деклеры win/loss вне скоупа пр-а и стоит обсуждать отдельно. У меня не укладывается в голове, зачем тогда им таски нужны, и если так надо - можно просто рассмотреть старый бэйский "делай что хочешь".

2023-10-14 00:18 UTC, KIBORG04 commented on code/game/gamemodes/game_mode.dm
> +				log_mode("[F] max_roles <= 0.")
```suggestion
			if(F.max_roles <= 0)
				log_mode("[F] max_roles <= 0.")
```
Но хз.. Если ты хочешь запретить заполнять фракцию по дефолту, думаю лучше придумать новую переменную, а не max_roles <= 0. Это не очень очевидно

2023-10-14 00:19 UTC, KIBORG04 commented on code/game/gamemodes/game_mode.dm
> +				log_mode("[F] max_roles <= 0.")
Ну и если сейчас написать `-1`, то ифка ниже цикл прервёт

2023-10-14 00:19 UTC, KIBORG04 commented on code/game/gamemodes/game_mode.dm
>  			if(F.max_roles && F.members.len >= F.max_roles)
```suggestion
			if(F.max_roles != 0 && F.members.len >= F.max_roles)
```

2023-10-14 00:24 UTC, KIBORG04 commented on code/game/gamemodes/roles/traitor.dm
> +			text += "<B>Objective #[count]</B>: [objective.explanation_text]"
Лучше не копипастить Declare, а либо:
1. Сделать функцию /role/proc/GetObjectiveDescription(datum/objective/objective)
2. Сделать переменную show_victory и в оригинальном деклере от переменной выводить победу.

Полная копипаста кода с 1 изменением не стоят того.

2023-10-14 00:26 UTC, KIBORG04 commented on code/game/gamemodes/roles/traitor.dm
> +			text += "<B>Objective #[count]</B>: [objective.explanation_text]"
А так же хочу обратить внимание, что в статистику киборга задача высрется с настоящим состоянием выполненности задачи. Можешь придумать новое состояние задачи, которые как бы будет тут присваиваться и называться, условно OBJECTIVE_HIDE_RESULT

2023-10-18 01:23 UTC, volas requested changes
смотреть комменты киборга

2023-10-26 02:12 UTC, merged