Фикс еще одной временной ошибки (до нового лора...)
TauCetiStation/TauCetiClassic pull request #12247
Opened 2023-10-10 12:56 UTC by maleyvich

## Описание изменений
тайтл
## Почему и что этот ПР улучшит
минус еще одна несостыковка
## Авторство
maleyvich
## Чеинжлог
- bugfix: В описании душа была указана дата из старого лора.

2023-10-10 13:24 UTC, LudwigVonChesterfield approved these changes

2023-10-10 13:32 UTC, KIBORG04 approved these changes

2023-10-10 13:40 UTC, Mercurialaste requested changes
Пцц тут целые две строчки вайткода в котором боргов удаляют в нулину.

2023-10-10 13:43 UTC, volas requested changes

2023-10-10 13:43 UTC, volas commented on code/game/objects/structures/watercloset.dm
> +	desc = "The HS-451. Installed in the 2210s by the Nanotrasen Hygiene Division."
Я буду комбо-брейкером. Мы не хардкодим год, у нас где-то была отдельная переменная или дефайн, от которой можно отталкиваться

2023-10-10 13:48 UTC, KIBORG04 reviewed
Убираю свой аппрув.

2023-10-10 14:04 UTC, maleyvich commented
короче сами чините я не понял ничего

2023-10-10 14:23 UTC, Mercurialaste commented
Слабый

2023-10-10 15:02 UTC, maleyvich commented
людук обьяснил мне как сделать (спасибо ему) поэтому пр снова жив

@volas ужаснейшая проблема решена (наверное)

2023-10-10 18:32 UTC, LudwigVonChesterfield commented on code/game/objects/structures/watercloset.dm
> +  	desc = "The HS-451. Installed in the [global.gamestory_start_year] by the Nanotrasen Hygiene Division."
можно сделать `[round(global.gamestory_start_year, 10)]s` чтобы было типо 2120s вместо 2123

2023-10-10 18:32 UTC, LudwigVonChesterfield commented on code/game/objects/structures/watercloset.dm
> +  	desc = "The HS-451. Installed in the [global.gamestory_start_year] by the Nanotrasen Hygiene Division."
```suggestion
  	desc = "The HS-451. Installed in the [round(global.gamestory_start_year, 10)]s by the Nanotrasen Hygiene Division."
```

2023-10-11 07:25 UTC, TheLone1y commented
Рушило атмосферу спс за фикс

2023-10-11 08:03 UTC, merged