Добавил усиление гранат порохом из патронов. Добавил шрапнель крафтящимся гранатам.
TauCetiStation/TauCetiClassic pull request #12254
Opened 2023-10-12 18:58 UTC by DarthSidiousPalpatine

## Описание изменений
Порох можно получить извлекая его из патронов в колбу. Порох усиливает реакцию нитроглицерина и калия-воды, если содержится в результирующей колбе в отношении 1 порох к 10 нитроглицерина или калия-воды.

Крафтящиеся гранаты заимели шрапнель. У мелкой гранаты 5-7 кусочков вылетает, у крупной - 12-17 кусочков.

## Почему и что этот ПР улучшит
Хз, разнообразие. Плюс шрапнель гранатам, почему бы и нет.

## Авторство
AndreyGysev.

## Чеинжлог
 :cl:
  - rscadd: Крафтящиеся гранаты получили шрапнель.
  - rscadd: Добавлен реагент порох, получаемый из патронов. Порох усиливает реакции взрыва.

2023-10-12 18:58 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2023-10-12 19:07 UTC, Mercurialaste commented
https://www.youtube.com/watch?v=0PFvFLUv-lw
☠️

2023-10-13 12:18 UTC, DarthSidiousPalpatine commented
Был пр на 3 файлика 10 строк, а стал пр на 28 файлов 178 строк.

2023-10-13 12:24 UTC, TauKitty commented
Этот запрос на слияние был упомянут в **Tau Ceti Station Forum**. Там могут быть соответствующие подробности:

https://forum.taucetistation.org/t/fludilka-chast-2/28659/27745

2023-10-13 14:23 UTC, DarthSidiousPalpatine commented
Всё хорошо, но учитывая размер, пр теперь точно ещё не скоро рассмотрят, не то что замержат :dovolen:

2023-10-13 14:39 UTC, LudwigVonChesterfield commented on code/game/objects/items/stacks/sheets/sheet_types.dm
> +	else
можно сделать чуточку красивее
```
if()
   ...
  return
  
return ..()
```

2023-10-13 16:26 UTC, LudwigVonChesterfield commented on code/controllers/subsystem/explosions.dm
> +		SSexplosions.throwturf += list(list(explode, epicenter, severity))
странно ли что отброс не зависит от силы взрыва?

2023-10-13 16:26 UTC, DarthSidiousPalpatine commented on code/controllers/subsystem/explosions.dm
> +		SSexplosions.throwturf += list(list(explode, epicenter, severity))
Зависит. Сила взрыва это северити.
Разброс зависит от северити разрушения турфа, всё ок.

2023-10-13 16:31 UTC, LudwigVonChesterfield commented on code/controllers/subsystem/explosions.dm
> +		SSexplosions.throwturf += list(list(explode, epicenter, severity))
меня немного воротит от того что эпицент хранится для кучи разных турфов при том что он всего один. почему нельзя откидывать предметы в ex_act?

2023-10-13 18:06 UTC, DarthSidiousPalpatine commented on code/defines/obj/weapon.dm
> +	force = 10
А у форонового осколка 8 брута было, потому у металлического поднял.

2023-10-13 18:07 UTC, DarthSidiousPalpatine commented on code/defines/obj/weapon.dm
> +	force = 10
А разве нельзя просто фороновое стекло разбить?

2023-10-13 18:10 UTC, DarthSidiousPalpatine commented on code/defines/obj/weapon.dm
> +	force = 10
окей, с руки будет как у обычного осколка.

2023-10-14 02:54 UTC, Mercurialaste commented on code/defines/obj/weapon.dm
> +	throwforce = 20
Добавить бы ещё херню, при которой после удара шрапнели об что-то - она удалялась и вынести мб в отдельную шрапнель от гранат. Эту шрапнель же по сути можно получить с дроби и подобного, после чего кидаться ей по 20 урона за бросок.

2023-10-14 02:54 UTC, Mercurialaste commented on code/game/objects/items/stacks/stack.dm
> +	var/shrapnel_type = /obj/item/weapon/shard/shrapnel
Мб лучше здесь указать `null`,  а в местах, где есть шрапнель, указать нужный тип шрапнели?

2023-10-14 04:32 UTC, DarthSidiousPalpatine commented on code/defines/obj/weapon.dm
> +	throwforce = 20
Нет, я просто сделаю так что ты не можешь кидать осколки и шрапнель далеко. Потому что они маленькие и потому что они тоненькие. Летят как листы металла/стёклышки и теряют скорость в воздухе. А от взрывов они будут посылаться до третьей космической всё также.

2023-10-14 04:32 UTC, DarthSidiousPalpatine commented on code/modules/reagents/reagent_containers/glass.dm
> +	else if(istype(I, /obj/item/ammo_casing) && !istype(I, /obj/item/ammo_casing/energy) && !istype(I, /obj/item/ammo_casing/magic) && !istype(I, /obj/item/ammo_casing/plasma) && !istype(I, /obj/item/am
на всякий случай перестраховался.

2023-10-14 04:33 UTC, DarthSidiousPalpatine commented on code/game/objects/items/stacks/stack.dm
> +	var/shrapnel_type = /obj/item/weapon/shard/shrapnel
нет, потому что оказалось что мест где не нужна шрапнель - меньше чем мест где нужна.

2023-10-14 11:21 UTC, arygal commented
Мб стингеры сбухам с rubber bullet вместо шрапнели?

2023-10-14 14:51 UTC, DarthSidiousPalpatine commented
В 4 раза уменьшил порох добываемый с патронов, потому что патронов полно.

2023-10-14 14:51 UTC, DarthSidiousPalpatine commented
> Мб стингеры сбухам с rubber bullet вместо шрапнели?

Это интересно, но я хз если кинуть руббер буллет то она застанит?)))

2023-10-14 15:49 UTC, DarthSidiousPalpatine commented
> Мб стингеры сбухам с rubber bullet вместо шрапнели?

Добавил гранату с боласами :dovolen:
Оказалось, только они у нас кидаются и станят. Хз.

2023-10-15 05:08 UTC, volas requested changes

2023-10-15 05:08 UTC, volas commented on code/controllers/subsystem/explosions.dm
> +							break
это интересная идея, но место плохое - стоит сразу где-то в части самого взрыва ``propagate_blastwave`` смотреть, чем в более абстратном контроллере, который просто последствия процессит.

2023-10-15 05:14 UTC, DarthSidiousPalpatine commented on code/defines/obj/weapon.dm
> +	throwforce = 20
При дальности прокида 1 это не поабузить нормально, хз

2023-10-15 05:16 UTC, DarthSidiousPalpatine commented on code/controllers/subsystem/explosions.dm
> +		SSexplosions.throwturf += list(list(explode, epicenter, severity))
У них там кринж, я сделаю лучше. Сейчас сделаю учитывание нескольких взрывов. И оно будет круче!
:)

2023-10-15 05:18 UTC, DarthSidiousPalpatine commented on code/game/objects/items/stacks/stack.dm
> +			new shrapnel_type(loc)
Я могу с шансом прост их спавнить, хз. Шанс 20% на спавн с листа одной шрапнельки.

2023-10-15 05:19 UTC, DarthSidiousPalpatine commented on code/game/objects/items/stacks/sheets/glass.dm
> +	shrapnel_type = /obj/item/weapon/shard
Тут не понял. Мне нужен был один механ для всех видов стаков. Чтобы и стекло и фороновое стекло и усиленное стекло и металл и слитки и пласталь и провода и роды и плитки пола и стеклянные плитки пола - давали осколки.

2023-10-15 05:35 UTC, volas commented on code/defines/obj/weapon.dm
> +	throwforce = 20
дальность прокида может изменяться в зависимости от обстоятельств: гравитация, разгермы, какие-нибудь гравипушки, мусоропровод и все что угодно, вызывающее throw_at() с кастомными скоростью и расстоянием. throwforce это единственный параметр, связанный с самим объектом, так сказать базовый дамаг.

2023-10-15 05:39 UTC, DarthSidiousPalpatine commented on code/defines/obj/weapon.dm
> +	throwforce = 20
Ну тогда мне придётся изменить систему нанесения урона вещью.
Пусть количество урона будет скаллироваться от скорости, видимо.

2023-10-15 05:45 UTC, volas commented on code/defines/obj/weapon.dm
> +	throwforce = 20
оно уже так и делает, как минимум для мобов. Броски у нас ок, но само попадание нуждается в рефакторинге и сейчас может работать по разному для разных объектов, надо проводить ревизию ``hitby``

2023-10-15 05:57 UTC, DarthSidiousPalpatine commented on code/defines/obj/weapon.dm
> +	throwforce = 20
Не, я посмотрел - для мобов тоже не делает. Я теперь крч считаю throwmomentum из w_class и скорости * файнтюн_дефайн

2023-10-15 06:00 UTC, volas commented on code/defines/obj/weapon.dm
> +	throwforce = 20
```
/mob/living/hitby()
	var/throw_damage = O.throwforce * (AM.fly_speed / 5)
```
fly_speed тут идет из датума, где считается как раз из скорости и расстояния

2023-10-15 06:01 UTC, volas commented on code/defines/obj/weapon.dm
> +	throwforce = 20
w_class не надо включать, throwforce это оно и есть отчасти.

2023-10-15 06:25 UTC, DarthSidiousPalpatine commented
Не мержим крч, ща сделаю пр с проставлением всем объектам в билде их массы :dovolen:

2023-11-16 10:13 UTC, closed without merging