Погребок
TauCetiStation/TauCetiClassic pull request #12282
Opened 2023-10-18 07:46 UTC by DarthSidiousPalpatine

## Описание изменений
Добавлены объекты что переносят еду и напитки между раундами.
Бочка - переносит напитки и позволяет крафтить алкоголь и неготовый сыр между раундами.
Стол - переносит еду и позволяет донастаивать неготовый сыр между раундами.
Корзина - переносит овощи и фрукты.

Стоят они только на боксе и гамме, между картами предметы тоже переносятся, так что всё ок. На прометее и дельте некуда ставить, а на фальконе не нужно, имхо.
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/21008918/4c364ba6-91df-45a7-b3c8-6a9aacf2f5c6)

## Почему и что этот ПР улучшит
СтРаТеГиЯ игры на поваре между раундами. Хороший тон положить овощей в корзину, да поставить готовиться сыр чтобы следующему повару было приятно :dovolen:

## Авторство
AndreyGysev и все все все, кто помогал в дискорде.

## Чеинжлог
 :cl:
  - rscadd: Добавлены бочка, стол и корзина для заготавливания еды и напитков между раундами.

2023-10-18 07:46 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2023-10-18 07:52 UTC, TauKitty commented
Этот запрос на слияние был упомянут в **Tau Ceti Station Forum**. Там могут быть соответствующие подробности:

https://forum.taucetistation.org/t/fludilka-chast-2/28659/27824

2023-10-18 07:55 UTC, DarkFurrSss commented
Тогда нужно жесткое ограничение в количестве (Мб и есть, в коде не мастер), дабы не перенести по сотне каждого овоща на следующий раунд + работа ботаника в раунде

2023-10-18 07:56 UTC, DarthSidiousPalpatine commented
> Тогда нужно жесткое ограничение в количестве (Мб и есть, в коде не мастер), дабы не перенести по сотне каждого овоща на следующий раунд + работа ботаника в раунде

в бочку помещается 200 реагента
в корзину помещается 10 овощей
на стол помещается 4 еды

2023-10-18 08:03 UTC, SergalCute commented
Что будет с теми предметами что были в еде?

2023-10-18 08:07 UTC, BiQndy commented
> Что будет с теми предметами что были в еде?

хорошее уточнение, надо сделать так что бы можно было класть только пустые продукты

2023-10-18 08:08 UTC, DarthSidiousPalpatine commented
> Что будет с теми предметами что были в еде?

Удалятся кнш. Оно просто переносит типы предметов что лежат в нём и в новом раунде создаёт с нуля предмет.
Получается что если там овощ с кастомными характеристиками, супер potency и пр. - в новом раунде будет овощ со стандартными характеристиками.

Так и если в нём сыр а в сыре нож, то в следующем раунде на полке появится только сыр. Пустой.

2023-10-18 08:48 UTC, WatlerJe approved these changes

2023-10-18 10:44 UTC, DarthSidiousPalpatine commented on code/game/machinery/kitchen/preservation.dm
> +			continue finding_recipe
Да нет, всё работает именно так как я и думаю. Я же протестировал и сделал сыр и водку.

2023-10-18 10:49 UTC, DarthSidiousPalpatine commented on code/game/machinery/kitchen/preservation.dm
> +	var/selection = show_radial_menu(user, src, liquids, require_near = TRUE, tooltips = TRUE)
эм, буквально ниже на строчку?

2023-10-18 10:52 UTC, DarthSidiousPalpatine commented on code/game/machinery/kitchen/preservation.dm
> +			continue finding_recipe
Ты очень плохо рассказываешь. На самом деле проблема не в том что оно не так работает, а в том что continue там и не нужно вовсе. Брух

2023-10-18 10:52 UTC, DarthSidiousPalpatine commented on code/game/machinery/kitchen/preservation.dm
> +	var/selection = show_radial_menu(user, src, liquids, require_near = TRUE, tooltips = TRUE)
Нужна, а что?

2023-10-18 10:56 UTC, DarthSidiousPalpatine commented on code/game/machinery/kitchen/preservation.dm
> +			continue finding_recipe
Не, я хотел сделать прогон по рецептам снова после того как какой-нибудь из них скрафтится, но это и без континуе можно.

2023-10-18 10:56 UTC, DarthSidiousPalpatine commented on code/game/machinery/kitchen/preservation.dm
> +			continue finding_recipe
а вообще хз что я хотел, кто знает

2023-10-18 10:58 UTC, DarthSidiousPalpatine commented on code/game/machinery/kitchen/preservation.dm
> +			continue finding_recipe
Убрал лишний континуе

2023-10-18 10:58 UTC, DarthSidiousPalpatine commented on code/game/machinery/kitchen/preservation.dm
> +	else
Сделал ранние возвраты в таких местах

2023-10-18 11:00 UTC, DarthSidiousPalpatine commented on code/game/machinery/kitchen/preservation.dm
> +	var/selection = show_radial_menu(user, src, liquids, require_near = TRUE, tooltips = TRUE)
Ну так а я что сделал? Создаю радиалку из реагентов внутри бочки плюс опции "налить".

А потом позволяю игроку выбрать реагент который игрок хочет набрать и набираю его.

2023-10-18 11:05 UTC, DarthSidiousPalpatine commented on code/game/machinery/kitchen/preservation.dm
> +	var/selection = show_radial_menu(user, src, liquids, require_near = TRUE, tooltips = TRUE)
Теперь точно набираю **его**

2023-10-18 11:05 UTC, DarthSidiousPalpatine commented on code/game/machinery/kitchen/preservation.dm
> +	var/savefile/S = new /savefile("data/obj_saves/PresBarrel.sav")
Да, и что?

2023-10-18 11:06 UTC, DarthSidiousPalpatine commented on code/game/machinery/kitchen/preservation.dm
> +	S["liquidslist_[save_id]"] << "Nothing"
На всякий случай сделал нафинг чтобы при считывании нафинга был нафинг

2023-10-18 11:09 UTC, DarthSidiousPalpatine commented on code/datums/components/roundstart_roundend.dm
> +/datum/component/roundstart_roundend
Ну потому что это нужно аж для четырёх объектов (полли можно на это перевести вместо вечной проверки в лайфе) и тип удобно наложить компоненту чем везде писать это.

2023-10-18 11:10 UTC, DarthSidiousPalpatine commented on code/datums/components/roundstart_roundend.dm
> +/datum/component/roundstart_roundend
Потому что компонента ещё и хендлит удаление подписок на сигналы :dovolen:

2023-10-18 11:17 UTC, DarthSidiousPalpatine commented on code/game/machinery/kitchen/preservation.dm
> +	var/selection = show_radial_menu(user, src, liquids, require_near = TRUE, tooltips = TRUE)
С точки зрения ирл у разных материалов разная плотность и в бочке они долго стоят и расслаиваются :dovolen:

С точки зрения геймдизайна, делать 200мл контейнер который легко можно загадить навсегда без возможности его поднять и потому извлечь из него N говна - кринж и неудобство ради неудобства. Пусть заготовка и крафт предметов будет удобным, он и так долгий - аж целый раунд займёт :)

2023-10-18 11:18 UTC, DarthSidiousPalpatine commented on code/game/machinery/kitchen/preservation.dm
> +	var/datum/reagents/R = new/datum/reagents(0)
остатки древней попытки на обычную систему рецептов еды перевести. Попытка была провальная как и попытка переписать систему рецептов.

2023-10-18 11:19 UTC, DarthSidiousPalpatine commented on code/game/machinery/kitchen/preservation.dm
> +	var/selection = show_radial_menu(user, src, liquids, require_near = TRUE, tooltips = TRUE)
Буквально в 2-х тайлах стоит химмастер повара. На который не нужны скиллы и особый доступ.

2023-10-18 11:24 UTC, DarthSidiousPalpatine commented on code/game/machinery/kitchen/preservation.dm
> +	var/selection = show_radial_menu(user, src, liquids, require_near = TRUE, tooltips = TRUE)
Как ты отфильтруешь стационарную бочку в которую попало 5мл кринжа с помощью химмастера повара?

2023-10-18 11:26 UTC, DarthSidiousPalpatine commented on code/game/machinery/kitchen/preservation.dm
> +	var/selection = show_radial_menu(user, src, liquids, require_near = TRUE, tooltips = TRUE)
С точки зрения геймдизайна я хочу фильтровать стационарную бочку в которую попало 5мл кринжа стаканом и я это делаю.

2023-10-18 11:27 UTC, DarthSidiousPalpatine commented on code/modules/food/recipes_preservation.dm
> +/datum/barrelrecipe
Нет

2023-10-18 11:27 UTC, DarthSidiousPalpatine commented on code/game/machinery/kitchen/preservation.dm
> +	var/selection = show_radial_menu(user, src, liquids, require_near = TRUE, tooltips = TRUE)
Он аппрувнул спрайт -_-

2023-10-18 11:28 UTC, DarthSidiousPalpatine commented on code/game/machinery/kitchen/preservation.dm
> +	var/selection = show_radial_menu(user, src, liquids, require_near = TRUE, tooltips = TRUE)
а нахуй тогда пишешь какой-то кринж, рофлан

2023-10-18 14:05 UTC, LudwigVonChesterfield commented
Я заранее напишу пару мыслей даже до формального ревью,

Но если все смешные вещи которые хотелось бы передавать между раундами - нельзя, то эта фича не намного лучше рандомной генерации вещей в этих бочках... Может даже хуже.

Если смешные вещи можно переносить то хотелось бы где-то иметь список вещей табличкой которые запрещены, почему запрещены, и какие смешные вещи были разрешены и почему.

2023-10-18 14:06 UTC, LudwigVonChesterfield commented on code/datums/components/roundstart_roundend.dm
> +/datum/component/roundstart_roundend/Initialize(datum/callback/roundstart_callback, datum/callback/roundend_callback, datum/callback/destroyed_callback)
вот бы SSPersistence

2023-10-18 14:08 UTC, DarthSidiousPalpatine commented on code/datums/components/roundstart_roundend.dm
> +/datum/component/roundstart_roundend/Initialize(datum/callback/roundstart_callback, datum/callback/roundend_callback, datum/callback/destroyed_callback)
Я думал о том чтобы сделать подсистему целиком для сохранения межраундового, но не смог вообразить её цельно в голове.

2023-10-18 14:44 UTC, LudwigVonChesterfield requested changes
Пожалуйста, не изобретай ещё одну систему крафтов когда их уже насчитывается как минимум 3 в билде.

В дискорде обсуждали как можно переделать на "крафт" реакциями химическими.

2023-10-18 14:51 UTC, DarthSidiousPalpatine commented
Хех, я думал, кнш, будет больше описания требований, но окей...

Описание таково:
а) рецепты для бочки это рецепты реагентов но требуют особый реагент "старений", который является катализатором и добавляется в начале и в конце раунда.
б) рецепты для стола попробовать всё же сделать как кухонные рецепты. Снова.
в) добавить удаление семечек из овощей что пролежали раунд

2023-10-18 15:50 UTC, Oz1Es commented
оооо я буду раундстартом делать жёское говно на ботанике, а потом овощи и фрукты пихать в корзинку и раундстартом получать сильнейшие овощи и фруктики и грифонить статион

2023-10-18 20:08 UTC, LudwigVonChesterfield commented on code/datums/components/roundstart_roundend.dm
> +		roundstart_callback.Invoke(parent)
эм а зачем эта компонента, почему нельзя объекту подписываться?

2023-10-18 20:31 UTC, LudwigVonChesterfield commented on code/game/atoms.dm
> +			if(istype(src, /obj/structure/reagent_dispensers) || istype(src, /obj/structure/preservation_barrel)) //watertanks, fueltanks, fermenting barrel
не знаю или мне нравится что вот так волшебный образом можно увидеть что в бочке..

2023-10-18 20:32 UTC, LudwigVonChesterfield commented on code/game/machinery/kitchen/preservation.dm
> +	for(var/datum/reagent/consumable/ethanol/R in reagents)
это не работает надо reagents.reagent_list

2023-10-18 20:33 UTC, LudwigVonChesterfield commented on code/game/machinery/kitchen/preservation.dm
> +	reagents.maximum_volume++
а я бы сделал чтобы бочка не работала если её доверху набили...

2023-10-18 20:33 UTC, LudwigVonChesterfield commented on code/game/machinery/kitchen/preservation.dm
> +	reagents.maximum_volume++
ну или убирался 1 куб жидкости рандомно, но точно не так

2023-10-18 20:33 UTC, LudwigVonChesterfield commented on code/game/machinery/kitchen/preservation.dm
> +/obj/structure/preservation_barrel/proc/check_reagents_for_recipe(list/checkreagents)
это всё ещё надо?

2023-10-18 20:34 UTC, LudwigVonChesterfield commented on code/game/machinery/kitchen/preservation.dm
> +	var/obj/item/selection = show_radial_menu(user, src, foods, require_near = TRUE, tooltips = TRUE)
замени на инвентарь у бочки пожалуйста, как у мусорных куч к примеру

2023-10-18 20:35 UTC, LudwigVonChesterfield commented on code/game/machinery/kitchen/preservation.dm
> +		if("Слить")
я бы вот этот тогл убрал

кликаешь пустым - набираешь
кликаешь полным - выливаешь

2023-10-18 20:35 UTC, LudwigVonChesterfield commented on code/game/machinery/kitchen/preservation.dm
> +	var/savefile/S = new /savefile("data/obj_saves/PresBarrel.sav")
бочки переставили между сменами, не вижу проблемы.

2023-10-18 20:37 UTC, LudwigVonChesterfield commented on code/game/machinery/kitchen/preservation.dm
> +	S["liquidslist_[save_id]"] << list2params(allliquids)
мне супер не нравится что бочка должна знать как работать с файлами

можно мы сделаем систему которая будет опрашивать нужные объекты что они хотят записать куда, и сама решать как записывать?

2023-10-18 20:38 UTC, LudwigVonChesterfield commented on code/game/machinery/kitchen/preservation.dm
> +	save_id = global.preservation_tables.Find(src)
мне не очень нравится этот подход. как минимум можно брать длину списка

но я бы предложил переиначить то как бочки работают, напиши в личку помогу

В кратце чтобы у бочек был уникальный "пул" айди в который они сохраняют списком вещества, а потом из этого пула по одной вытягивают

Это нужно чтобы поддерживать разные карты и бочки в разных зонах.

2023-10-18 20:39 UTC, LudwigVonChesterfield commented on code/game/machinery/kitchen/preservation.dm
> +		for(var/RecType in subtypesof(/datum/preservation_recipe))
Мы можем без этого теперь?

2023-10-18 20:39 UTC, LudwigVonChesterfield commented on code/game/machinery/kitchen/preservation.dm
> +/obj/structure/preservation_table/proc/read_data()
мне опять же не нравится что у нас три объекта копипастят этот код, так ещё и знают про записывание в файлы

Очень нужно сделать отдельную сабсистему для этого. объекты бы говорили что хотят сохранить, а не как

2023-10-19 03:54 UTC, DarthSidiousPalpatine commented on code/game/machinery/kitchen/preservation.dm
> +	var/obj/item/selection = show_radial_menu(user, src, foods, require_near = TRUE, tooltips = TRUE)
У бочки нет инвентаря. А у стола инвентарь на 4 слота что не позволяют наши инвентари. У корзины инвентарь на 10 слотов что ТОЖЕ НЕ ПОЗВОЛЯЮТ НАШИ ИНВЕНТАРИ

2023-10-19 13:34 UTC, Naroke commented
> Абсолютно ужасная фича не имеющая ничего общего с концептом игры и реальным миром. Создает огромную дыру в правилах и лоре подразумевая, что станция находится не во временной петле и все раунды реально случались, раз между ними есть связь. Абсолютно против и встретив бы гусева в реальной жизни я бы его ударил за такое. Эта фича не стоит вообще добавления учитывая какие дыры она приносит. Слишком мало дает взамен на отмену такого концепта на котором станция и держится.

Эм... Ну петля она петлёй так и останется. Что мешает представлять это как добродушность повара прошлой смены?

2023-10-19 13:42 UTC, BiQndy commented
> Абсолютно ужасная фича не имеющая ничего общего с концептом игры и реальным миром. Создает огромную дыру в правилах и лоре подразумевая, что станция находится не во временной петле и все раунды реально случались, раз между ними есть связь. Абсолютно против и встретив бы гусева в реальной жизни я бы его ударил за такое. Эта фича не стоит вообще добавления учитывая какие дыры она приносит. Слишком мало дает взамен на отмену такого концепта на котором станция и держится.

lore moment

2023-10-19 13:47 UTC, AirBlack commented
> Эм... Ну петля она петлёй так и останется. Что мешает представлять это как добродушность повара прошлой смены?

никанон, добрых людей в лоре сс13 не существует и попытка оставить там овощи должна расцениваться нарушением правила о реалистичных персонажах и строго наказываться админами

2023-10-21 15:51 UTC, DarthSidiousPalpatine commented on code/game/machinery/kitchen/preservation.dm
> +/obj/structure/preservation_table/proc/read_data()
Сделал

2023-10-21 15:51 UTC, DarthSidiousPalpatine commented on code/game/machinery/kitchen/preservation.dm
> +	save_id = global.preservation_tables.Find(src)
Так и сделал

2023-10-21 15:51 UTC, DarthSidiousPalpatine commented on code/game/machinery/kitchen/preservation.dm
> +	S["liquidslist_[save_id]"] << list2params(allliquids)
Сделал

2023-10-21 15:52 UTC, DarthSidiousPalpatine commented on code/datums/components/roundstart_roundend.dm
> +		roundstart_callback.Invoke(parent)
Теперь не надо никому подписываться

2023-10-21 17:36 UTC, DarthSidiousPalpatine commented
Крч это, если и мержить, то можно сначала ТМ? Я как бы протестил всё, ок да, но я не уверен до конца и хотелось бы прям в игре протестить будет на станции.

А на вики я напишу обо всех рецептах, кнш.

2023-10-21 21:54 UTC, LudwigVonChesterfield commented on code/_globalvars/mapping.dm
> +var/global/list/maintenance_barrels = list()
мб maintenance_barrel_landmarks?

2023-10-21 22:22 UTC, LudwigVonChesterfield commented on code/controllers/subsystem/continuity.dm
> +	var/savefile/S = new /savefile("data/obj_saves/Preservations.sav")
Мне не очень нравится что к файлу обращается в каждом проке. Может назвать файлы obj_saves/continuity и передавать в функцию хендлер к файлу?

2023-10-21 22:23 UTC, LudwigVonChesterfield commented on code/controllers/subsystem/ticker.dm
> +				SEND_SIGNAL(src, COMSIG_TICKER_ROUND_ENDING)
Кажется не юзается нигде?

2023-10-21 22:23 UTC, LudwigVonChesterfield commented on code/game/atoms.dm
> +			if(istype(src, /obj/structure/reagent_dispensers)) //watertanks, fueltanks, fermenting barrel
комментарий больше не актуален?

2023-10-21 22:24 UTC, LudwigVonChesterfield commented on code/game/atoms.dm
> +/atom/proc/continuity_read(list/arguments)
Сейчас система полностью хендлит всё:
1. точно ли нужна эта функция
2. точно ли она нужна *всем* атмомам?

2023-10-21 22:25 UTC, LudwigVonChesterfield commented on code/game/machinery/kitchen/preservation.dm
> +	reagents.add_reagent("agium", 1)
Мне всё ещё кажется смешным если бы надо было оставлять немного места в бочке чтобы сработало, но если настаиваешь...

Так сказать ставило бы ударение на "стратегии" этой фичи

2023-10-21 22:25 UTC, LudwigVonChesterfield commented on code/game/machinery/kitchen/preservation.dm
> +	reagents.add_reagent("agium", 1)
А я кажется не прав потому-что тогда не будет фичи с превращением алкоголя в уксус..

2023-10-21 22:26 UTC, LudwigVonChesterfield commented on code/game/machinery/kitchen/preservation.dm
> +/obj/structure/preservation_barrel/proc/process_recipes()
если есть stop_processing_recipes, надо start_processing_recipes

2023-10-21 22:26 UTC, LudwigVonChesterfield commented on code/game/machinery/kitchen/preservation.dm
> +		reagents.remove_reagent(R.id, min(5, vinegar_multiplier))
он не multiplier он vinegar_amount

2023-10-21 22:27 UTC, LudwigVonChesterfield commented on code/game/machinery/kitchen/preservation.dm
> +		if("Слить")
Почему?

Я бы поспорил что радиалка на два элемента - более странная затея...

В крайнем случае интенты?

2023-10-21 22:46 UTC, LudwigVonChesterfield commented on code/modules/reagents/Chemistry-Recipes.dm
> -/datum/chemical_reaction/cheesewheel
мне кажется нечестно лишать игроков сыра

я бы сделал энзимы не бесконечными и заказываемыми в карго, а бочка - гетто способ получения сыра

2023-10-21 23:20 UTC, LudwigVonChesterfield commented on code/modules/reagents/Chemistry-Recipes.dm
> +/datum/chemical_reaction/alcohol
я бы не делал общего родителя такого рода

причина 1:
- мне понадобилось больше минуты чтобы понять "а в чем прикол новых рецептов? что теперь просто сахар вместо энзимов?"
- если кто-то захочет подкрутить циферки конкретному рецепту в будущем это создаст конфуз

Думаю с рецептами не стоит создавать иерархию наследовательности и просто прописать каждому рецепту всё что он требует для ясности

2023-10-21 23:20 UTC, LudwigVonChesterfield commented on code/modules/reagents/Chemistry-Recipes.dm
> -/datum/chemical_reaction/moonshine
Я бы не удалял старые рецепты алкоголя, но сделал бы энзимы более трудодоступными и иссякаемыми.

2023-10-22 01:39 UTC, LudwigVonChesterfield commented on code/modules/reagents/reagent_types/Chemistry-Core.dm
> +/datum/reagent/consumable/sugar
Пожалуйста найди способ определять безопасные для сохранения реагенты КРОМЕ надежды на тип родителя.

Это не очень хорошо что для того чтобы быть сериализируемым сахару надо иметь родителя с не знаю мгновенно даже какими последствиями! Что он унаследовал, зачем?

Рекомендую сделать переменную что-то типо var/is_persistent = TRUE

2023-10-22 01:40 UTC, LudwigVonChesterfield commented on code/modules/reagents/reagent_types/Chemistry-Miscellaneous.dm
> +	description = "Концентрированное старение."
```suggestion
	description = "Редкостный энзим изредка выделяющийся буковым деревом. Пахнет старением."
```

2023-10-22 04:15 UTC, DarthSidiousPalpatine commented on code/game/machinery/kitchen/preservation.dm
> +		if("Слить")
Интенты неочевидны

2023-10-22 04:29 UTC, DarthSidiousPalpatine commented on code/modules/reagents/Chemistry-Recipes.dm
> -/datum/chemical_reaction/moonshine
А я хочу чтобы алкоголь только в бочке делался.

2023-10-22 04:30 UTC, DarthSidiousPalpatine commented on code/modules/reagents/Chemistry-Recipes.dm
> -/datum/chemical_reaction/cheesewheel
Сейчас добавлю сырную покупку в карго.

2023-10-22 04:43 UTC, DarthSidiousPalpatine commented on code/modules/reagents/Chemistry-Recipes.dm
> -/datum/chemical_reaction/cheesewheel
Добавил ящик сыра в карго. А тут я хотел как бы в будущем сделать крафт разных сыров благодаря этому.

2023-10-25 20:29 UTC, LudwigVonChesterfield submitted a review, later dismissed
нужно разобраться как это будет работать с множеством серверов

2023-10-26 02:36 UTC, volas commented on code/controllers/subsystem/continuity.dm
> +	var/savefile/S = new /savefile("data/obj_saves/Preservations.sav")
стоит вместо ``data/`` в ``cache/``, у него отдельный дефайн есть PERSISTENT_CACHE_FOLDER

всяких попугаев и прочих тоже надо из data вытащить, на сервере пипец запарно мейнтейнить папку, часть вещей из которой общая для всех серверов, часть индивидуальная.

2023-10-26 02:39 UTC, volas commented on code/controllers/subsystem/continuity.dm
> +	read_boxes(S)
можно датум для каждого типа с общим методом, чтоб не копипастить. И файл каждому датуму можно свой. И вообще супер было бы, если потом еще попугаев и обезьян отрефакторить в этот датум, ООП и красиво было бы.

2023-10-26 03:35 UTC, DarthSidiousPalpatine commented on code/controllers/subsystem/continuity.dm
> +	read_boxes(S)
Я совершенно не понимаю о чём ты здесь говоришь. Напиши в дисе там, хз, подробнее, пж.

2023-10-26 03:51 UTC, LudwigVonChesterfield commented on code/controllers/subsystem/continuity.dm
> +	read_boxes(S)
Мне кажется Волас предлагает что-то такого рода:

```
/datum/controller/subsystem/continuity/proc/read_files()
    for continuous_entity in continious_entities
          continious_entity.read_savefile()

/datum/continious_entities

/datum/continious_entities/proc/read_savefile

/datum/continious_entities/proc/write_savefile

/datum/continious_entities/barrels

И вместо общего сейвфайла для сохранения отдельные файлики?

2023-10-26 03:52 UTC, DarthSidiousPalpatine commented on code/controllers/subsystem/continuity.dm
> +	read_boxes(S)
Да, он в дисе это и написал. Мне чёт не очень нравится пложение сущностей что недостаточно сделать два прока и вкинуть - нужно какие-то датумы создавать и в них создавать проки там... хз.

2023-10-26 03:55 UTC, LudwigVonChesterfield commented on code/controllers/subsystem/continuity.dm
> +/datum/controller/subsystem/continuity/proc/write_barrels(savefile/S)
я бы возможно переименовал на save и load вместо write и read

2023-10-26 03:59 UTC, AirBlack commented on code/modules/reagents/Chemistry-Recipes.dm
> -/datum/chemical_reaction/moonshine
найди работу пожалуйста чтоб у тебя вечером оставалось время только на один раунд

2023-10-26 04:07 UTC, LudwigVonChesterfield commented on code/modules/reagents/Chemistry-Recipes.dm
> +/datum/chemical_reaction/cheese
мне кажется у тебя вторая реакция полностью перепишет первую и нельзя будет винегаром сделать сыр. надо разные айдишки и разные типы

2023-10-29 18:43 UTC, DarthSidiousPalpatine commented on code/controllers/subsystem/continuity.dm
> +	read_boxes(S)
Сделал как приказано

2023-10-29 22:37 UTC, LudwigVonChesterfield commented on code/controllers/subsystem/continuity.dm
> +	for(var/datum/continuity_object/object in subtypesof(/datum/continuity_object))
@volas Я бы не называл это _object потому-что тогда выглядит будто это к конкретному (одному) объекту сохранение, а это для целой категории вещей

2023-11-18 13:59 UTC, DarthSidiousPalpatine commented
Прощай, мой ПР, скоро ты закроешься и никто тебя уже не переоткроет... Никому этого не надо...

2023-11-28 07:49 UTC, volas requested changes

2023-11-28 07:49 UTC, volas commented on code/game/machinery/kitchen/preservation.dm
> +		foods_inside.Blend(icon(F.icon, F.icon_state), ICON_OVERLAY, offsets[1], offsets[2])
серверсайд операции с иконками на update_icon не гуд

2023-11-28 07:49 UTC, volas commented on code/game/machinery/kitchen/preservation.dm
> +	foods_inside = icon('icons/effects/32x32.dmi', "blank")
mutable_appearance тут будет оптимальнее

2023-11-28 07:49 UTC, volas commented on code/game/machinery/kitchen/preservation.dm
> +	S["Tables_Save"] << list2params(tables_saves)
везде при работе с сейвфайлами не хватает какой-то санитизации, как минимум в запись

2023-11-28 07:49 UTC, volas commented on code/game/objects/effects/landmarks.dm
> +/obj/effect/landmark/maintenance_barrel_spawn
зачем ландмарки, почему бы и сразу не спавнить?

2023-11-28 07:49 UTC, volas commented on code/game/objects/items/weapons/storage/internal.dm
> +		master_item.update_icon()
что это и зачем оно надо

2023-11-28 07:49 UTC, volas commented on code/modules/reagents/Chemistry-Recipes.dm
> -/datum/chemical_reaction/cheesewheel
всё еще удаляются старые рецепты, вместо того, чтоб просто сделать новые. В очередной раз прошу не форсить на игроков новый механ таким способом, лучше добавь новый альтернативный рецепт но лучше/питательнее/вкуснее/тд.

2023-11-28 07:49 UTC, volas commented on code/game/machinery/kitchen/preservation.dm
> +	reagents.add_reagent("agium", 1)
== не всегда надежно, могут быть гонки, ошибки, из-за чего условие легко станет невыполнимым

2023-11-29 07:05 UTC, DarthSidiousPalpatine commented on code/game/machinery/kitchen/preservation.dm
> +		foods_inside.Blend(icon(F.icon, F.icon_state), ICON_OVERLAY, offsets[1], offsets[2])
Предложи альтернативу.

2023-11-29 07:06 UTC, DarthSidiousPalpatine commented on code/game/machinery/kitchen/preservation.dm
> +	S["Tables_Save"] << list2params(tables_saves)
Шо, какой санитизации? От чего? В лист сохраняются только тайпы. Как ты ингейм заинжектишь тайп страшный-страшный?

2023-11-29 07:06 UTC, DarthSidiousPalpatine commented on code/game/objects/items/weapons/storage/internal.dm
> +		master_item.update_icon()
Потому что мне сказали взять уже существующий инвентарь как у мусорной кучи. Оно надо чтобы корзина/стол обновляли свою иконку когда в него втыкают/извлекают предмет.

2023-11-29 07:07 UTC, DarthSidiousPalpatine commented on code/modules/reagents/Chemistry-Recipes.dm
> -/datum/chemical_reaction/cheesewheel
Предложи конкретно что ты хочешь и я сделаю. Я не буду сидеть придумывать как сделать "питательный" сыр.

2023-11-29 07:07 UTC, DarthSidiousPalpatine commented on code/modules/reagents/Chemistry-Recipes.dm
> -/datum/chemical_reaction/cheesewheel
Что бы это ни значило вообще бай зе вей.

2023-11-29 07:08 UTC, DarthSidiousPalpatine commented on code/game/machinery/kitchen/preservation.dm
> +	reagents.add_reagent("agium", 1)
Не может быть гонок и ошибок. Это проверка на то когда в бочку засунули жижу раундстартом - оно удаляет 1 шт. случайного реагента чтобы освободить место для агиума. Всё збс.

2023-11-29 07:09 UTC, DarthSidiousPalpatine commented on code/game/objects/effects/landmarks.dm
> +/obj/effect/landmark/maintenance_barrel_spawn
Чтобы в рандомном месте спавнилась одна бочка техтоннельская.

2023-11-29 07:09 UTC, DarthSidiousPalpatine commented on code/game/machinery/kitchen/preservation.dm
> +	foods_inside = icon('icons/effects/32x32.dmi', "blank")
окей, ещё бы знать полноценно в чём отличие для конкретно этого кейса, чтобы в будущем не напороться на то же самое.

2023-11-29 07:14 UTC, volas commented on code/game/machinery/kitchen/preservation.dm
> +	foods_inside = icon('icons/effects/32x32.dmi', "blank")
https://www.byond.com/docs/ref/info.html#/mutable_appearance

2023-11-29 07:14 UTC, volas commented on code/game/machinery/kitchen/preservation.dm
> +		foods_inside.Blend(icon(F.icon, F.icon_state), ICON_OVERLAY, offsets[1], offsets[2])
почему не оверлеи?

2023-11-29 07:16 UTC, volas commented on code/game/machinery/kitchen/preservation.dm
> +	S["Tables_Save"] << list2params(tables_saves)
есть вероятность ошибки, есть вероятность плохого VV. Недавно у нас случайно залетел реф в сейвфайл, потом на следующий раунд пытаясь восстановить его сервер крашился из-за рекурсий.

2023-11-29 07:17 UTC, volas commented on code/game/objects/items/weapons/storage/internal.dm
> +		master_item.update_icon()
тогда ты можешь перегрузить сторейдж проки на уровне твоих объектов и написать это там, это очень специфичный код чтоб быть в родителе

2023-11-29 07:19 UTC, volas commented on code/modules/reagents/Chemistry-Recipes.dm
> -/datum/chemical_reaction/cheesewheel
вернуть старые рецепты как было, сделать *новые* эксклюзивные рецепты для твоей фичи

2023-11-29 11:14 UTC, DarthSidiousPalpatine commented on code/game/machinery/kitchen/preservation.dm
> +		foods_inside.Blend(icon(F.icon, F.icon_state), ICON_OVERLAY, offsets[1], offsets[2])
Потому что мне надо вырезать их впоследствии по маске

2023-11-29 11:15 UTC, DarthSidiousPalpatine commented on code/game/machinery/kitchen/preservation.dm
> +	S["Tables_Save"] << list2params(tables_saves)
Я не понимаю, list2params выдаёт текстовый стринг из листа. В лист сохраняются тайпы. Что здесь вообще может пойти не так и КАКИМ образом ты представляешь тут санитайз и что конкретно санитайзить хочешь? ВТФ?

2023-11-29 11:16 UTC, DarthSidiousPalpatine commented on code/modules/reagents/Chemistry-Recipes.dm
> -/datum/chemical_reaction/cheesewheel
Ну скажи мне какие новые рецепты сделать, лол, я об этом прошу.

Моя идея вот как в ПРе. Надо иначе - придумай мне, хз, лол.

2023-12-03 02:03 UTC, LudwigVonChesterfield commented on code/game/machinery/kitchen/preservation.dm
> +		foods_inside.Blend(icon(F.icon, F.icon_state), ICON_OVERLAY, offsets[1], offsets[2])
мне кажется с фильтрами и альфамаской теперь можно оверлеи нарезать в том числе.

2024-01-06 16:02 UTC, DarthSidiousPalpatine commented
Переоткройте пж

2024-01-11 19:22 UTC, DarthSidiousPalpatine commented
Я тебя обязательно доделаю, у меня на тебя большиие планы. Но чуть позже.

2024-01-17 20:11 UTC, DarthSidiousPalpatine commented
Старые рецепты возвращены. Добавлены два великолепных новых.

Если положить лёд в бочку то в следующем раунде там будет вода.
А если положить воду, то в следующем раунде будет ничего.

2024-01-17 20:11 UTC, DarthSidiousPalpatine commented
Фикшу конфликты и пусть валяется до закрытия.

2024-01-17 20:15 UTC, DarthSidiousPalpatine commented
Пофикшено. Отлично. Удачи тебе, детище.

2024-01-17 21:29 UTC, LudwigVonChesterfield commented on code/game/machinery/kitchen/preservation.dm
> +		if(istype(F, /obj/item/weapon/reagent_containers/food/snacks/grown) || (F.type in can_also_preserve["items"]))
можно ли /obj/item/weapon/reagent_containers/food/snacks/grown как часть списка can_preserve хранить?

2024-01-17 21:30 UTC, LudwigVonChesterfield commented on code/game/machinery/kitchen/preservation.dm
> +		if(istype(R, /datum/reagent/consumable) || (R.type in can_also_preserve["reagents"]))
можно ли /datum/reagent/consumable как часть can_preserve хранить?

2024-01-17 21:31 UTC, LudwigVonChesterfield commented on code/game/objects/items/weapons/storage/internal.dm
> +/obj/item/weapon/storage/internal/remove_from_storage(obj/item/W, atom/new_location, NoUpdate = FALSE)
для механа бочек нужен отдельный класс стореджа вместо добавления этих свойств всем стореджам

2024-01-18 07:03 UTC, DarthSidiousPalpatine commented on code/game/objects/items/weapons/storage/internal.dm
> +/obj/item/weapon/storage/internal/remove_from_storage(obj/item/W, atom/new_location, NoUpdate = FALSE)
Я не понимаю зачем отдельный класс именно для бочек если обновление спрайта по изменению контентсов интернал инвентаря может быть полезно, например, чтобы сделать нормальную полку для специй или глобус коньяка. Уже больше применений чем в моих бочках.

2024-01-18 07:12 UTC, DarthSidiousPalpatine commented on code/game/machinery/kitchen/preservation.dm
> +		foods_inside.Blend(icon(F.icon, F.icon_state), ICON_OVERLAY, offsets[1], offsets[2])
Тебе кажется. Ну только если ты не предлагаешь вместо серверсайд операций на иконки накидывать 14 фильтров в объект чтобы по 1 фильтру альфа маск на каждый оверлей продукта внутри???

2024-01-18 07:16 UTC, DarthSidiousPalpatine commented
Что мы имеем из функционала теперь?
Сохранение еды на след. раунд.
Крафт воды изо льда и ничего из воды.
Ни одного крафта для столика((
Крафт компоста из еды.

2024-01-18 08:04 UTC, DarthSidiousPalpatine commented
Ааххахах, а у меня теперь перестало сохранять вообще что либо и грузить. Какого чёрта))

2024-01-18 08:10 UTC, DarthSidiousPalpatine commented
Не особо понимаю где могла быть проблема...

2024-01-18 08:11 UTC, DarthSidiousPalpatine commented
типа даже файла не появляется в cache/persistent

2024-01-18 08:55 UTC, DarthSidiousPalpatine commented
Ля, я понял в чём дело.

2024-01-18 10:20 UTC, DarthSidiousPalpatine commented
Отлично. Всё пофиксил, всё доделал. Всё работает отлично теперь. Я рад-рад-рад.

2024-01-21 17:45 UTC, LudwigVonChesterfield commented on code/game/objects/items/weapons/storage/internal.dm
> +/obj/item/weapon/storage/internal/remove_from_storage(obj/item/W, atom/new_location, NoUpdate = FALSE)
текущим вещам юзающим этот класс этот функционал не нужен поэтому некорректно им его давать.

вынеси в отдельный класс, если не хочешь называть конкретно для бочек назови storage/updates_icon или что-то такого рода.

2024-01-21 21:28 UTC, DarthSidiousPalpatine commented on code/game/machinery/kitchen/preservation.dm
> +		foods_inside.Blend(icon(F.icon, F.icon_state), ICON_OVERLAY, offsets[1], offsets[2])
Я сделал на имеджах и, если честно, вроде, работает даже лучше.

Крч норм тема, хайп, крутяк, постарался по минимуму фильтров юзать.

2024-01-21 21:28 UTC, DarthSidiousPalpatine commented
Переделал икон-операции на имедж-операции

2024-01-22 19:41 UTC, LudwigVonChesterfield commented
там большой грех с тем что то что можно сохранять это не строгий определенный список, а зонтик-тип и в будущем смогут сохранять всякую рандомную неожиданную фигню. к примеру уже можно мыло.

не могу брать на себя этот грех, гляну если что-то резко поменяется.

2024-01-22 19:46 UTC, DarthSidiousPalpatine commented
> гляну если что-то резко поменяется.

А, ну ладно, если глянешь, то я повторюсь что делаю блин список...

2024-01-27 22:10 UTC, DarthSidiousPalpatine commented
мдаааа

2024-01-28 21:43 UTC, DarthSidiousPalpatine commented
неделя

2024-01-29 03:13 UTC, volas commented
гусев, я тебя уже неделю в другом Пр-е жду #11329

если хотел сначала погреб доделать, то не надо было тот другой открывать

2024-01-30 19:33 UTC, LudwigVonChesterfield commented
Принимаю волевое решение, делаем вайтлист на вещи которые можно сохранять. Учитывая что он и так сделан, если кому-то понадобится более гибкая система - разрешаю ему переделать.

2024-01-30 20:00 UTC, DarthSidiousPalpatine commented
Отлично, бот больше не ругается. Я всё.

2024-01-31 03:59 UTC, volas commented on code/_globalvars/lists/can_be_saved.dm
> +var/global/list/preservable_vegetables = list(
весь этот файл - какой-то пипец

2024-01-31 04:00 UTC, volas commented on code/_globalvars/lists/can_be_saved.dm
> +	"nutriment",
и в другом ПР-е тебе уже объясняли как генерировать списки, но ты всё успел забыть. Хардкодить имена реагентов - плохая идея

2024-01-31 04:00 UTC, LudwigVonChesterfield commented on code/_globalvars/lists/can_be_saved.dm
> +	"nutriment",
это я потребовал спустя неделю ожиданий.

пожалуйста линкани ПР где можно почитать как надо

2024-01-31 04:01 UTC, LudwigVonChesterfield commented on code/_globalvars/lists/can_be_saved.dm
> +var/global/list/preservable_vegetables = list(
это полностью всё моё требование чтобы не сохранять непредсказуемые вещи которые унаследовались от родителя. я открыт к лучшим опциям.

2024-01-31 04:06 UTC, volas commented on code/game/objects/effects/landmarks.dm
> +	return INITIALIZE_HINT_QDEL
я думаю, будет лучше сделать обычный спавнер бочки, лендмарки предпочтительно оставить как персистентные пометки. И точно не надо свой список еще один создавать, они и так все в глобальном списке.

2024-01-31 04:07 UTC, volas commented on code/game/objects/items/weapons/storage/internal.dm
> +		master_item.update_icon()
всё еще не резолвнуто

2024-01-31 04:12 UTC, volas commented on code/_globalvars/lists/can_be_saved.dm
> +var/global/list/preservable_vegetables = list(
можно сделать флаги и генерировать списки при старте раунда, но вообще я не понимаю суть и почему именно реагент-контейнеры, в них что угодно может быть.

``/snacks/grown/`` содержит ссылку на семена, можно по ним смотреть. Обычные ``/snacks/`` содержат реагенты.

2024-01-31 04:14 UTC, volas commented on code/game/objects/effects/landmarks.dm
> +	return INITIALIZE_HINT_QDEL
хотя да, ты хочешь рандомно. Я только пока не понимаю, как ты потом рандомные бочки с персистентностью связываешь, но можно оставить лейблом и взять какой-нибудь pick_landmarked_location или свой написать

2024-01-31 04:15 UTC, volas commented on code/_globalvars/lists/can_be_saved.dm
> +	"nutriment",
https://github.com/TauCetiStation/TauCetiClassic/pull/12282#discussion_r1472282679

2024-01-31 04:15 UTC, LudwigVonChesterfield commented on code/_globalvars/lists/can_be_saved.dm
> +var/global/list/preservable_vegetables = list(
сморишь по /snacks/ и внезапно мыло можно сохранять между раундами, синдикатское к примеру.

2024-01-31 04:18 UTC, volas commented on code/_globalvars/lists/can_be_saved.dm
> +var/global/list/preservable_vegetables = list(
я понял, я просто о бочке думал и не въехал. Тогда реагентам флаги. Никто потом не вспомнит про то, что этот список надо поддерживать.

2024-01-31 04:19 UTC, volas commented on code/game/machinery/kitchen/preservation.dm
> +/datum/continuity_object/barrels
датумы стоит вынести в свой файл

2024-01-31 04:24 UTC, volas commented on code/game/machinery/kitchen/preservation.dm
> +	spawn_maintenance_barrel()
тут еще будет много раундов ревью. Если ты вдруг решишь не заканчивать и переключишься на другие ПР-ы  - скажи пожалуйста сразу, чтобы я мог не тратить время.

2024-01-31 17:14 UTC, DarthSidiousPalpatine commented on code/game/machinery/kitchen/preservation.dm
> +/datum/continuity_object/barrels
Вынес датумы в свой файл.

2024-01-31 17:15 UTC, DarthSidiousPalpatine commented on code/game/objects/effects/landmarks.dm
> +	return INITIALIZE_HINT_QDEL
Потому что у каждой бочки/структуры есть её айди. Айди выставляется мапперами и плюс у техтоннельной бочки есть техтоннельный айди. При записи контентсов бочки в файл оно записывает ассоциативном списком по айдишникам бочек/объектов.

2024-01-31 17:17 UTC, DarthSidiousPalpatine commented on code/_globalvars/lists/can_be_saved.dm
> +var/global/list/preservable_vegetables = list(
> Тогда реагентам флаги

У меня есть два объекта, один сохраняет только алкогольные напитки, второй - все напитки.
А флаг ОДИН и сгенерит он ОДИН список всех напитков.

Да и потом, с тем же успехом никто не вспомнит про флаг "МОЖЕТ_БЫТЬ_СОХРАНЕНО_В_БОЧКЕ" чтобы его поддерживать. А так - есть целый листик куда можно писать всякое.

2024-01-31 17:20 UTC, DarthSidiousPalpatine commented on code/_globalvars/lists/can_be_saved.dm
> +var/global/list/preservable_vegetables = list(
Также, у флагов проблема с наследованием. Установил флаг к чипсины, а потом оказалось что от чипсины наследуется синдимыло. Или установил флаг у помидора, а от помидора наследуется мегасуперОП блюспесс томато.

2024-01-31 17:32 UTC, DarthSidiousPalpatine commented on code/game/machinery/kitchen/preservation.dm
> +	spawn_maintenance_barrel()
Хз с чего ты решил что я решу не заканчивать ПР на погребок который лелею уже полгода, но как знаешь.

Я тут сижу по КД 24/7 в ПРе про погребок. И жду тебя, Волас. Я всегда жду тебя, Волас. ~~_Мы все здесь летаем, Волас._~~

2024-01-31 17:34 UTC, DarthSidiousPalpatine commented
так, датумы переместил, по остальным вопросам отписал, пойду в переводопр.

2024-02-03 15:11 UTC, DarthSidiousPalpatine commented
*Ждёт этих самых "много раундов ревью"*

2024-02-03 15:11 UTC, DarthSidiousPalpatine commented
Случайно, брух

2024-02-03 15:12 UTC, DarthSidiousPalpatine commented
Какой дебил придумал делать кнопку "закрыть с комментом" рядом с кнопкой "коммент"

2024-02-04 21:54 UTC, volas commented on code/datums/continuity/preservation.dm
> +/datum/continuity_object/barrels
теперь сделай так, чтобы датум отвечал только за хранение и сериализацию данных. Он абстрактный, он не должен сам дергать и искать объекты в игре (и тем более что-то спавнить). Это уже объекты в игре должны каким-то образом опрашивать соответствующий датум о возможно сохраненных для них данных, и забирать их из датума.

2024-02-04 22:01 UTC, DarthSidiousPalpatine commented on code/datums/continuity/preservation.dm
> +/datum/continuity_object/barrels
чего бля, он ничего не спавнит, одумайся

2024-02-04 22:02 UTC, volas commented on code/datums/continuity/preservation.dm
> +/datum/continuity_object/barrels
```
/datum/continuity_object/barrels/load(savefile/S)
	spawn_maintenance_barrel()
```
я вижу

2024-02-05 14:03 UTC, DarthSidiousPalpatine commented
@volas а мне ведь нужен был этот ПР чтобы сделать два других continuity пр-а. Музей и табличка лучший работник месяца....

2024-02-26 16:11 UTC, closed without merging

2024-03-06 16:08 UTC, DarthSidiousPalpatine commented
Спасибо воласу за счастливое детство

2024-07-09 09:19 UTC, PhantornRU commented
У тебя классные спрайты. Не знаю почему такие поездатые бочки так и не добавили.

2024-11-09 07:56 UTC, TauKitty commented
Этот запрос на слияние был упомянут в **Tau Ceti Station Forum**. Там могут быть соответствующие подробности:

https://forum.taucetistation.org/t/fludilka-chast-2/28659/37713

2024-11-11 14:58 UTC, TauKitty commented
Этот запрос на слияние был упомянут в **Tau Ceti Station Forum**. Там могут быть соответствующие подробности:

https://forum.taucetistation.org/t/loupop-i-reshenie-problemy-resov/44068/44

2025-02-06 15:33 UTC, DarthSidiousPalpatine commented
А могли бы уже давно в мыле кататься.
Иметь прикольные флаффные таблички лучшему работнику месяца и другие персистанс штуки.

2025-02-06 15:35 UTC, DarthSidiousPalpatine commented
Иногда я прихожу сюда чтобы снова посмотреть на то что же пошло не так...

Ля будет забавно если в начале 2026-го года Волас закодит персистентность, я посмотрю что там он сделает и пойму что моему механу погребка оно вообще не соответствует и мне придётся переписывать новый механ персистентности, ахах... хах... дааа

2025-02-06 15:36 UTC, DarthSidiousPalpatine commented
Ну хоть спрайты апрувнуты.

2025-09-07 02:38 UTC, DarthSidiousPalpatine commented
Это могли быть мы, но у нас лучшее враг хорошего.
<img width="929" height="324" alt="image" src="https://github.com/user-attachments/assets/e499b05d-4d93-43a2-8c49-1572e1e600d3" />

2025-09-07 03:11 UTC, LudwigVonChesterfield commented
так портируй у них

2025-09-07 03:42 UTC, DarthSidiousPalpatine commented
> так портируй у них

Так у них кринжовая система, не то что нужно нам.

2025-09-07 03:43 UTC, DarthSidiousPalpatine commented
> так портируй у них

Они всего лишь сделали шаг в нужном направлении, но суть порочна - сохранение всей станции/карты/слоёв целиком - не то, к чему нужно стремиться, имхо.

Сохранять нужно отдельные объекты, отдельные комнаты, возможно, отдельные состояния/переменные. Но уж точно не карту целиком, ибо если сохраняем карту целиком - смысл от нового раунда? Играйте старый!

2025-09-07 03:45 UTC, DarthSidiousPalpatine commented
У Тапора вот тоже станцию целиком сохраняют, но там хотя бы понятно, это ОТДЕЛЬНАЯ карта где это оправдано, строечка. Её можно пикнуть в случайный момент и было бы прикольно загружать её такой, какой её оставили во время прошлого пика. Но обычные станции так сохранять кринжово.

Раздолбали бокс, воутнули гамму - загрузилась совершенно другая станция, а бокс просто сохранился в раздолбанном состоянии где-то. Ну и смысл такого?

2025-09-07 03:51 UTC, DarthSidiousPalpatine commented
Мне вот интересно, если я этот ПР переоткрою, его хоть кто-нибудь возьмётся ревьювать чтобы довести до конца?)
Шаттлы я вот пилю потихоньку по отзыву воласа, там сложности возникли, нужно многое переписать, но я не отказываюсь и не тильтую, а пилю.

Интересно можно ли погребок так возродить и довести до конца. Два года прошло, я чуть больше вещей понял и осознал, вроде, хаха...

2025-09-29 15:11 UTC, DarthSidiousPalpatine commented
волас, кста, был прав в том, что с флагами проще чем со списками менеджмить какие объекты хотим сохранять, а какие - нет.

2025-09-29 15:13 UTC, DarthSidiousPalpatine commented
потому как, вот я сделал для шахты силосную башню с рудой, вот еще пару объектов и списки стали просто убожескими с повторениями и пр.

проще флаг проставить для каждого типа сохранялки и проверять имеет ли атом такой тип сохранялки, может ли он быть тут сохранен.