Halloween Skeletons
TauCetiStation/TauCetiClassic pull request #12297
Opened 2023-10-20 20:24 UTC by Deahaka

## Описание изменений
Усиливаем скелетонов, чтобы они стали опять страшными и даже страшнее чем раньше
## Почему и что этот ПР улучшит
Хеллоуин скоро, контентик к нему. Скелетики временно станут опять интересными.
## Авторство

## Чеинжлог
только для тестмержа

2023-10-20 20:24 UTC, TauKitty commented
###### Changelog status: :radio_button: No changelog

2023-10-24 11:11 UTC, KIBORG04 commented on code/modules/organs/organ_external.dm
> +		handle_cut()
А зачем это?

2023-10-24 11:12 UTC, KIBORG04 commented on code/modules/organs/organ_external.dm
> +		handle_cut()
хотя я кажется понял. ужс

2023-10-24 11:12 UTC, KIBORG04 approved these changes

2023-10-30 13:14 UTC, Deahaka commented
Из-за слишком маленькой дальности разлёта порой у некоторых игроков сформировалось впечатление о том что это всё просто отрастает, а значит они не поняли слабости скелета. Увеличил дальность разлёта в среднем на большее значение.

2023-11-06 07:37 UTC, Deahaka commented
тут вроде тоже реди ту мерж

2023-11-13 00:43 UTC, volas commented on code/modules/organs/external/skeleton.dm
> +		var/turf/T = get_step(BP, get_dir(BP, BP.owner))
get_step в данном случае не проверяет проходимость, немного портит впечатление.

еще скорее всего не хватает задержки и процессинг тут и движение слишком быстрые?

И еще наверно стоило бы через сколько-то попыток сдаться и не пытаться догнать юзера.

2023-11-13 00:44 UTC, volas commented on code/modules/organs/external/skeleton.dm
> +		return (loc == owner)
это точно нужно, что оно делает? И нужен ли тут чек на праздник?

2023-11-19 15:55 UTC, volas requested changes
^

2023-11-24 10:02 UTC, Deahaka commented on code/modules/organs/external/skeleton.dm
> +		return (loc == owner)
В праздник скелеты собираются, в другое время нет. У скелетской конечности не пропадает владелец после отсоеденения, а значит по наследуемой проверке она всегда будет процессится, как будто она "оторвана от тела".
https://github.com/TauCetiStation/TauCetiClassic/blob/07b9c6f06872d155392787947bb22bc12867db15/code/modules/organs/external/flesh.dm#L364

2023-11-24 10:05 UTC, Deahaka commented on code/modules/organs/external/skeleton.dm
> +		var/turf/T = get_step(BP, get_dir(BP, BP.owner))
Скелет никогда себе не восстановит конечности, так что лучше бы они догнали его когда-нибудь, где бы они не были. Проходимость специально полная, потому что это мифическое свойство скелета пересобираться, не подчинённое никакой внутренней логике принципиально.

2023-11-28 07:53 UTC, volas commented on code/modules/organs/external/skeleton.dm
> +		var/turf/T = get_step(BP, get_dir(BP, BP.owner))
скелеты могут присоединить к себе конечности чужих скелетов, а процесс можно было бы дропать через пару попыток. Вообще имхо это одна из главных фич скелетов, что они могут забавно терять конечности и потом ходить их искать. Может хотяб на абилку сделать с КД? Тогда и на постоянку можно.

2023-11-28 08:50 UTC, Deahaka commented on code/modules/organs/external/skeleton.dm
> +		var/turf/T = get_step(BP, get_dir(BP, BP.owner))
Я убрал возможность поднимать конечности скелетов, так что не могут

2023-12-29 07:13 UTC, closed without merging