Halloween Zombies
TauCetiStation/TauCetiClassic pull request #12300
Opened 2023-10-21 12:27 UTC by Deahaka

## Описание изменений
Усиливаем зомби, респрайтим зелёных человечков в мертвяков.
![yyyyyyyy1](https://github.com/TauCetiStation/TauCetiClassic/assets/96499407/4467b6ca-4fc1-4901-9161-41600e1d054e)
![yyyyyyyy2](https://github.com/TauCetiStation/TauCetiClassic/assets/96499407/b821b79f-3de3-4e5f-a83f-70bc3633c5e8)
![yyyyyyyy3](https://github.com/TauCetiStation/TauCetiClassic/assets/96499407/f6df12e5-b0f3-4137-b643-1ad811a6292c)
![yyyyyyyyyy](https://github.com/TauCetiStation/TauCetiClassic/assets/96499407/539309f1-e963-42f8-a799-6eecb95cf18b)
Боланс:
- понижен урон от пуль;
- повышенный урон от горения;
- увеличенный кд на возрождение;
- пониженный шанс на заражение;
- быстрое выламывание дверей;
- чуть более быстрое передвижение;
- чуть более сильные удары;
## Почему и что этот ПР улучшит
Хеллоуин скоро, контентик к нему.
## Авторство
DanieleGray
## Чеинжлог
для тестмержа

2023-10-21 12:27 UTC, TauKitty commented
###### Changelog status: :radio_button: No changelog

2023-10-21 12:36 UTC, maleyvich commented
стоп где хвост у таяр, отгрызли что-ли?

2023-10-21 13:06 UTC, DanieleGrey commented
> стоп где хвост у таяр, отгрызли что-ли?

Есть там все, у таяр хвост меньше и повернут в другую сторону

2023-10-21 13:08 UTC, muWander commented
> быстрое выламывание дверей
сейчас сломано кстати
https://github.com/TauCetiStation/TauCetiClassic/issues/12213

2023-10-21 13:10 UTC, DanieleGrey commented
Ну значит надо все вместе мержить

2023-10-22 07:52 UTC, Slavik2001 commented
Снимаю шляпу за охуительные спрайты зомбей

2023-10-22 13:15 UTC, DanieleGrey commented
> Снимаю шляпу за охуительные спрайты зомбей

спасиб)

2023-10-22 14:02 UTC, RONSI7 commented
Спрайты действительно хороши, но только вот по моему мнению хьюманы на фоне ксеносов вышли чутка скучноваты. Я думаю им не хватает  более серьезных повреждений как у других, особенно на голове. 

Например отсутствие пол лица с явно видимой пустой глазницей в центре которой горит красная точка.

2023-10-22 15:29 UTC, Slavik2001 commented
> Спрайты действительно хороши, но только вот по моему мнению хьюманы на фоне ксеносов вышли чутка скучноваты. Я думаю им не хватает более серьезных повреждений как у других, особенно на голове.
> 
> Например отсутствие пол лица с явно видимой пустой глазницей в центре которой горит красная точка.

Зато хюманы могут весело выкалывать глаза другим своей костлявой рукой :D

2023-10-22 16:11 UTC, DanieleGrey commented
> Спрайты действительно хороши, но только вот по моему мнению хьюманы на фоне ксеносов вышли чутка скучноваты. Я думаю им не хватает более серьезных повреждений как у других, особенно на голове.
> 
> Например отсутствие пол лица с явно видимой пустой глазницей в центре которой горит красная точка.

Все ксенорасы делались позднее хуманов, поэтому заметны различия, а глаза так или иначе будут гореть, это элемент кода. Изменения планировались как ивент на хеллоуин, но если людям зайдет, то почему бы ввести изменения на постоянную основу?

2023-10-22 16:20 UTC, DanieleGrey commented
![236326327342](https://github.com/TauCetiStation/TauCetiClassic/assets/148632397/e5a6fc72-ef04-4c90-b176-64ae56f9c061)
Заодно скину вид с других сторон у таяр и унатхов
![532562327](https://github.com/TauCetiStation/TauCetiClassic/assets/148632397/948517f3-d216-435f-a482-28e93b8f1080)
![532362327](https://github.com/TauCetiStation/TauCetiClassic/assets/148632397/242c9531-beb4-4c42-8287-c798f5545bea)

2023-10-22 16:21 UTC, maleyvich commented
стоп а как на куклах-женщинах собственно это будет выглядеть???

2023-10-22 16:22 UTC, DanieleGrey commented
> стоп а как на куклах-женщинах собственно это будет выглядеть???

Зомби же считаются за отдельную расу без пола

2023-10-22 17:37 UTC, Slavik2001 commented
Еба им нам по позвоночнику прошлись XD

2023-10-24 11:05 UTC, KIBORG04 approved these changes

2023-10-30 12:10 UTC, TauKitty commented
Этот запрос на слияние был упомянут в **Tau Ceti Station Forum**. Там могут быть соответствующие подробности:

https://forum.taucetistation.org/t/strashnoktyabr-2023-konkurs-kostyumov/41129/4

2023-10-31 18:35 UTC, Deahaka commented
Скорее всего из-за уменьшения шанса на заражение произошли баги. Стоит учитывать на будущее никогда не менять шанс заражения зомбям.

2023-11-02 07:28 UTC, Deahaka commented
вроде реди ту мерж

2023-11-02 07:34 UTC, volas commented
Куклы не будут голыми бегать по станции, все эти кляксы возможно будут просто шумом на общем спрайте, и может теряться наглядность. Хотя старый спрайт в этом плане не лучше, но там хоть зеленого много.

2023-11-02 07:38 UTC, volas commented
вы вроде побегали с ними на празднике, интересно мнение от заставших. Может еще спрайтдеп подтянется сюда

2023-11-13 15:47 UTC, WatlerJe commented
Хотелось бы увидеть скрины с одетыми зомби. Еще интересует вопрос, есть ли фем версии зомбей?

2023-11-13 15:51 UTC, DanieleGrey commented
> Хотелось бы увидеть скрины с одетыми зомби. Еще интересует вопрос, есть ли фем версии зомбей?

на тау по дефолту у зомби мужской спрайт, если кто-то будет готов закодить им пол - я дорисую их

2023-11-14 04:32 UTC, volas commented
Скорее всего женские выключили как-раз из-за нехватки спрайта, если сделать - это одну строчку изменить в коде

https://github.com/TauCetiStation/TauCetiClassic/blob/2603fc0008d918a02616f157d87155f83d9c0eec/code/modules/mob/living/carbon/species.dm#L1434

и прописать спрайтам суффиксы ``_m`` и ``_f``, как в других местах.

2023-11-17 03:31 UTC, WatlerJe commented
Для апрува требуются:
- Фем спрайты зомбей;
- Обновлённый скелет у зомби.

2023-11-19 15:56 UTC, volas requested changes
^

2023-11-19 15:58 UTC, DanieleGrey commented
> Для апрува требуются:
> 
> * Фем спрайты зомбей;
> * Обновлённый скелет у зомби.

Как только появится свободное время, то дорисую

2023-11-20 14:17 UTC, Deahaka commented
мне кажется это был удушающий захват

2023-12-11 15:08 UTC, closed without merging