Машинка, печатающая формы в приёмной ГП.
TauCetiStation/TauCetiClassic pull request #12310
Opened 2023-10-22 10:22 UTC by DarthSidiousPalpatine

## Описание изменений
Поставил машинку, что печатает формы в приёмной ГП. Она ещё и сразу билет с номером печатает. И рядом мониторы висят с текущим номером. ГП кнопку нажимает - номер меняется :dovolen:
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/21008918/e0d062fb-0aa7-4f85-a3d2-c08cc7affc2e)
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/21008918/839ba8bc-0cdf-4531-9331-ee349d81a592)
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/21008918/df7ad351-6e96-4612-a0fd-c1a131970f2d)

## Почему и что этот ПР улучшит
Удобство. Пришёл такой к ГП, быстро себе форму напечатал из заготовленных в формах ГП. Сел и заполняешь.
Потом ГП номерок меняет - подходишь и збс.

## Авторство
AndreyGysev

## Чеинжлог
 :cl:
  - rscadd: Терминал для печати форм в приёмной у ГП.

2023-10-22 10:22 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2023-10-22 12:19 UTC, WatlerJe commented
Такой себе спрайт у терминала выдачи талонов, сами талоны формата А4 это рофлс.

2023-10-22 12:19 UTC, DarthSidiousPalpatine commented
> Такой себе спрайт у терминала выдачи талонов, сами талоны формата А4 это рофлс.

Талоны должны быть крупными чтобы на них видно было номерок.
world_icon сделать у меня не получилось потому что на талоне maptext есть.

2023-10-22 12:26 UTC, DarthSidiousPalpatine commented
> Такой себе спрайт у терминала выдачи талонов, сами талоны формата А4 это рофлс.

И как его улучшить?

2023-10-22 14:38 UTC, DarthSidiousPalpatine commented
Готово, изменил спрайты, добавил звуки, включил авторские права на звуки, всё СС0, всё свободно, но всё равно указал авторов.

2023-10-22 14:50 UTC, DarthSidiousPalpatine commented
Хз на что жалуется бот.

2023-10-23 14:10 UTC, DarthSidiousPalpatine commented
Обновил спрайт машинки до полностью Вальтеровского:
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/21008918/74622b30-f1d2-4196-bced-08e115e69949)
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/21008918/2247f9ab-8a8f-42f8-8f6d-6f463a4df5c6)

2023-10-23 14:11 UTC, DarthSidiousPalpatine commented
Ну тип, готово.

2023-10-24 11:41 UTC, WatlerJe approved these changes

2023-10-26 02:06 UTC, LudwigVonChesterfield commented
добавь статистику как часто юзать будут и можно в ТМ

2023-10-26 02:08 UTC, LudwigVonChesterfield commented on code/game/objects/items/weapons/cards_ids.dm
> +	desc += "[number]."
```suggestion
	desc += " №[number]."
```

2023-10-26 02:08 UTC, LudwigVonChesterfield commented on code/game/objects/items/weapons/cards_ids.dm
> +	desc = "Билет №"
```suggestion
	desc = "Билет"
```

2023-10-26 03:32 UTC, DarthSidiousPalpatine commented
закоммитил твои изменения

2023-10-26 04:43 UTC, DarthSidiousPalpatine commented
Да накой статистику. И так будут юзать, это же печать форм удобная. Пришёл - выбрал форму, заполнил. :/

Ладно, за эту ночь замержили грузторг консоли на постоянку, уже рад :dovolen:

2023-10-26 07:21 UTC, AirBlack commented
Хорошее изменение, можно еще сделать чтобы флешер автоматом срабатывал если человек не со своим номерком или без номерка подошел? Или турель летальная

2023-10-26 16:01 UTC, DarthSidiousPalpatine commented
Жаль это не заТМили

2023-10-28 04:22 UTC, DarthSidiousPalpatine commented
После ТМа и Мержа микрофонов теперь можно ТМить и Мержить машинку для документов ГП :dovolen:

2023-10-28 04:34 UTC, DarthSidiousPalpatine commented
А можно протолкнуть этот ПР как часть хеллоуина?! :)

Уууу, я страшная бюрокраааатия, уууу!

2023-10-28 10:32 UTC, AirBlack commented
Сделай в формах плейсхолдер на название текущей станции, чтобы на гамме не были документы КСН Исходус

2023-10-28 10:51 UTC, DarthSidiousPalpatine commented
> Сделай в формах плейсхолдер на название текущей станции, чтобы на гамме не были документы КСН Исходус

Я хз как это сделать, потому что в форму прок station_name() не сунуть, к сожалению.

2023-11-01 19:17 UTC, KatoMarika reviewed
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/18484142/0e12aeac-4083-4f3f-89f2-b5d38e59cbf9)

2023-11-01 19:25 UTC, DarthSidiousPalpatine commented
> ![image](https://user-images.githubusercontent.com/18484142/279777733-0e12aeac-4083-4f3f-89f2-b5d38e59cbf9.png)

Пофикшено.

2023-11-01 19:32 UTC, KatoMarika requested changes
Извиняюсь, не увидел сразу. К остальному вопросов нет, можно будет отдельно симметрии придать при желании, но вне этого пр-а
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/18484142/8e0f0e10-c256-4ffd-9474-12ba3fc85558)

2023-11-02 03:38 UTC, DarthSidiousPalpatine commented
> Извиняюсь, не увидел сразу. К остальному вопросов нет, можно будет отдельно симметрии придать при желании, но вне этого пр-а ![image](https://user-images.githubusercontent.com/18484142/279781045-8e0f0e10-c256-4ffd-9474-12ba3fc85558.png)

ПОФИКСИЛ

2023-11-02 03:52 UTC, KatoMarika approved these changes

2023-11-02 07:13 UTC, volas commented
![Снимок экрана от 2023-11-02 10-10-46](https://github.com/TauCetiStation/TauCetiClassic/assets/4064061/b9234b99-aa6b-4d75-b558-a976b048c899)
скрин с диффбота, у тебя почему-то очередь идет в стол, и стоит на стульях.

И отгороженная очередь как сейчас мне кажется более практичной, специально сделана таким образом чтоб нельзя было влезть вперед

2023-11-02 07:14 UTC, DarthSidiousPalpatine commented
> ![Снимок экрана от 2023-11-02 10-10-46](https://user-images.githubusercontent.com/4064061/279894693-b9234b99-aa6b-4d75-b558-a976b048c899.png) скрин с диффбота, у тебя почему-то очередь идет в стол, и стоит на стульях.
> 
> И отгороженная очередь как сейчас мне кажется более практичной, специально сделана таким образом чтоб нельзя было влезть вперед

Никто не идёт никуда. Все садятся на стул и пишут бумаги которые им выдаёт машинка.

2023-11-02 07:15 UTC, DarthSidiousPalpatine commented
> И отгороженная очередь как сейчас мне кажется более практичной, специально сделана таким образом чтоб нельзя было влезть вперед

Так тебе с бланком номерок дают. Если ГП хочет очередь - тыкает кнопку и вызывает следующего.

2023-11-02 07:18 UTC, DarthSidiousPalpatine commented
Когда уже это замержат, я хочу на ГП нажимать кнопку и орать следующий!)

2023-11-02 07:25 UTC, DarthSidiousPalpatine commented
> Надо добавить рядом с офисом ГП отдельный джукбокс в котором вечно будет играть саундтрек из papers please :peka:

Нажал на кнопку и вместе со сменой номерка на мониторе играет звук из papers please:
https://youtu.be/z7-QeGdlRa8?si=lMcHbJfdTOQGyIT1&t=98

2023-11-02 20:16 UTC, DarthSidiousPalpatine commented
Придумал как сделать возможность добавления своих форм. Крч раундстартом внутри этой фигни спавнится папка. Внутри папки листочки. Листочки это формы :dovolen:

Вынимаешь листок или кладёшь ещё один. Вставляешь папку назад, закрываешь панель - оп, добавил/удалил форму)

2023-11-03 06:29 UTC, DarthSidiousPalpatine commented
Обновил. Добавил изменение спрайта по изменению энергии машинки.
Добавил возможность изменять формы. Нужно просто открутить лючок и вытащить папку из машинки. В папке все формы машинки лежат. Можно свои добавить бумажки для копирования и всякое такое.

2023-11-11 03:24 UTC, merged