Перевод ручного сканера здоровья
TauCetiStation/TauCetiClassic pull request #12340
Opened 2023-10-26 18:05 UTC by AzzyDreemurr13

## Описание изменений
Перевёл всё что связано с ручным мед сканером на радость новым и старым медикам
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/74739991/498ab1f7-efa3-4f65-bb70-211202f983d5)
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/74739991/f559e86e-d819-4597-b2c0-add9132770d6)
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/74739991/75ed0dcb-859d-49ef-9740-395b502f5539)
## Почему и что этот ПР улучшит
Делаем медицину доступнее, понятнее и по-русски. Для новичков на парамедиках/интернах облегчит понимание, того что от них просят опытные врачи. 

## Авторство
Я
## Чеинжлог
🆑 Azzy.Dreemurr
- ru: Перевод ручного мед. сканера

2023-10-26 18:05 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2023-10-27 08:42 UTC, maleyvich requested changes

2023-10-27 08:42 UTC, maleyvich commented on code/__HELPERS/mobs.dm
> +		message += "<span class='notice'>&emsp; Специфические повреждения: [0]-[0]-[0]-[0]</span><br>"
может быть специфика повреждений?

2023-10-27 08:42 UTC, maleyvich commented on code/__HELPERS/mobs.dm
> +			message += "<span class='notice'>&emsp; Конечности целы.</span><br>"
что? может быть "Конечности в нормальном состоянии"??

2023-10-27 08:42 UTC, maleyvich commented on code/__HELPERS/mobs.dm
> +	BU = M.getFireLoss() > 50 ? "<font color='#FFA500'><b>Обнаружены серьезные ожоговые повреждения</b></font>" : "Термических повреждений не обнаружено"
есть ОЖОГОВАЯ ТРАВМА, но ожогового повреждения, не... такого слова кажется нет

2023-10-27 08:42 UTC, maleyvich commented on code/__HELPERS/mobs.dm
> +			message += "<span class='warning bold'>Внимание: Уровень крови КРИТИЧЕСКИЙ: [blood_percent]% [blood_volume]cl.</span><span class='notice bold'>Группа крови: [blood_type]</span><br>"
КРИТИЧЕСКИ НИЗКИЙ?

2023-10-27 08:42 UTC, maleyvich commented on code/__HELPERS/mobs.dm
> +					message += "<span class='notice'>Состояние сердца: <font color='blue'>Внимание! Сердце подвержено фибрилляции.</font></span><br>"
Состояние сердца пациента?

2023-10-27 08:42 UTC, maleyvich commented on code/game/objects/items/devices/scanners/health_analyzer.dm
> +			message += "<span class = 'notice'>Результаты сканирования ОШИБКА:\n&emsp; Общее состояние: ОШИБКА</span><br>"
как-то некрасиво выглядит. может после "сканирования" поставить двоеточие?

2023-10-27 08:42 UTC, maleyvich commented on code/game/objects/items/devices/scanners/health_analyzer.dm
> +		to_chat(user, "<span class = 'warning'>Результаты анализа не завершены. Обнаружена неизвестная анатомия.</span>")
Обнаружен инородный обьект?

2023-10-27 08:43 UTC, maleyvich commented on code/__HELPERS/mobs.dm
> +			message += "<span class='notice'>&emsp; Конечности целы.</span><br>"
упс просто не так заметна буква ы в интерфейсе гитхаба, можно и так оставить.

2023-10-27 08:43 UTC, maleyvich commented on code/game/objects/items/devices/scanners/health_analyzer.dm
> +			message += "<span class = 'notice'>Результаты сканирования ОШИБКА:\n&emsp; Общее состояние: ОШИБКА</span><br>"
несколькими строчками позже ты к слову так и сделал

2023-10-27 09:56 UTC, Kiromaka requested changes

2023-10-27 09:56 UTC, Kiromaka commented on code/game/objects/items/devices/scanners/health_analyzer.dm
> +	desc = "Ручной сканер тела, способный просканировать жизненные показатели пациента."
сканер способный просканировать, тавтология. Сканер способный "проанализировать", ну или сам придумай

2023-10-27 09:56 UTC, Kiromaka commented on code/__HELPERS/mobs.dm
> +		message += "<span class='notice'>Анализ крови, обнаружил [M.reagents:get_reagent_amount("inaprovaline")] юнитов для регенерации.</span><br>"
Странно звучит (in my opinion) может - юнитов регенеративных/лечебных химикатов/препаратов

2023-10-27 09:58 UTC, Kiromaka commented on code/__HELPERS/mobs.dm
> +			message += "<span class='warning bold'>Внимание: Уровень крови КРИТИЧЕСКИЙ: [blood_percent]% [blood_volume]cl.</span><span class='notice bold'>Группа крови: [blood_type]</span><br>"
критический нормально, тут речь не про давление, а слишком высоким количество крови в билде быть не может.

2023-10-27 10:13 UTC, QWxiZX commented on code/__HELPERS/mobs.dm
> +		message += "<span class='notice'>Анализ крови, обнаружил [M.reagents:get_reagent_amount("inaprovaline")] юнитов для регенерации.</span><br>"
запятая после "анализ крови" лишняя

2023-10-27 10:15 UTC, Kiromaka commented
Странно что чек ругается.

2023-10-27 17:27 UTC, maleyvich commented
обнаружена инфекция у chest это мем конечно

2023-11-03 10:39 UTC, Fenriros approved these changes
Меня всё устраивает, разве что вызывает вопрос про 

> ...Обнаружена серьезная анатомическая травма</b></font>" : "Механических травм не обнаружено

2023-11-12 10:27 UTC, merged