Imposters new logo and antag hud
TauCetiStation/TauCetiClassic pull request #12366
Opened 2023-10-29 10:52 UTC by Deahaka

## Описание изменений
Новое лого и худ у импостеров от игроков
## Почему и что этот ПР улучшит
![YYYYYYYYYYYYYYYYYYYY1](https://github.com/TauCetiStation/TauCetiClassic/assets/96499407/5da848cc-61eb-4b51-8e05-406bb65cca9b)
![YYYYYYYYYYYYYYYYYY2](https://github.com/TauCetiStation/TauCetiClassic/assets/96499407/83a8a9cb-0374-4cfd-9b43-5463cbdab1ca)

## Авторство
@pro100kotah aka Zero aka Zero Inside aka Ikar_os
## Чеинжлог
:cl: Zero
- image: Новое лого и худ-картинка у Импостеров.

2023-10-29 10:52 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2023-10-29 16:25 UTC, TRISAGI0N commented
А когда эта шутка уже кончится? Когда этот режим удалят?

2023-10-29 16:31 UTC, KIBORG04 requested changes
кринж

2023-11-02 09:04 UTC, pro100kotah commented
Ржака

2023-11-02 09:05 UTC, KIBORG04 commented
-1

2023-11-02 09:05 UTC, closed without merging