new aspects
TauCetiStation/TauCetiClassic pull request #12367
Opened 2023-10-29 11:05 UTC by simb11

## Описание изменений
Добавляет новые аспекты
## Почему и что этот ПР улучшит
Разнообразие
## Авторство
я
## Чеинжлог
Не нужен

2023-10-29 11:05 UTC, TauKitty commented
###### Changelog status: :radio_button: No changelog

2023-10-29 15:54 UTC, DarkFurrSss commented
Наверняка химики будут ливать как только увидят гидропонику на месте их отдела. Хотел бы кто играть в гидропонике - брал бы ботаника

2023-10-29 16:09 UTC, simb11 commented
пусть плачут

2023-10-30 09:26 UTC, AirBlack commented
хммм почему онлайн упал не знаю

2023-10-30 09:41 UTC, AirBlack commented
о ура у химиков будет разнообразие раз в 10 раундов замена одной закликивательной хуйни на другую ура вот это разнообразие они станут такими полезными и нужными в этот раунд ведь у нас нет еще двух таких же отделов на станции с гидропоникой о ура разнообразие геймплея как весело интересно и умно великолепный геймдизайн хочу подчеркнуть высокий айкью автора пра за такое гениальное изобретение невиданное ранее в среде сс13 и не только в среде но и во вторнике и в четверге

2023-10-30 09:42 UTC, simb11 commented
спасибо

2023-10-30 11:39 UTC, Polotos commented
Блять а шизотепическое вроде бы у меня. А хуйню делают кодеры

2023-10-30 11:40 UTC, AirBlack commented
> Блять а шизотепическое вроде бы у меня. А хуйню делают кодеры

average tau ceti enjoyer

2023-11-01 19:11 UTC, KatoMarika approved these changes

2023-11-04 16:41 UTC, volas requested changes
в будущем просьба разделять аспекты на отдельные ПР-ы, будет быстрее обсуждать, смотреть и мержить

2023-11-04 16:41 UTC, volas commented on code/datums/round_aspects/round_aspects.dm
> +	afterspawn_IC_announcement = "<span class='warning'>Научно-исследовательский Совет НаноТрейзен стал в меньшей мере интересоваться изучением взрывчатых свойств форона.</span>"
будет не очень, если один только негатив, можно было бы за что-то другое начать давать больше очков. Не требование, предложение

2023-11-04 16:41 UTC, volas commented on code/datums/round_aspects/round_aspects.dm
> +	var/datum/map_template/aspect/alchemy/template
Это точно не очень, без предпосылок и повода форс игрока в профессию, которую он не выбирал. Я не могу представить, как оно может быть оправдано.

Да и шаблоны это плохая идея при наличии нескольких карт с разными отделами.

2023-11-04 16:41 UTC, volas commented on code/datums/round_aspects/round_aspects.dm
> +	desc = "Увеличена частота случайных событий."
Вот это интересный аспект, и в целом направление для аспектов. Случайный раунд катастрофа, или можно даже увеличивать частоту каких-то избранных ивентов, раунд карпов там.

2023-11-04 16:41 UTC, volas commented on code/modules/events/roundstart_events/area/replace/station_rearmament.dm
> +		/obj/item/weapon/gun/energy/gun = /obj/item/weapon/gun/energy/gun/nuclear,
что-то страшное и летальное, хз

2023-11-04 16:41 UTC, volas commented on code/datums/round_aspects/round_aspects.dm
> +		plsmsh.materials = list(MAT_METAL = 250000, MAT_GOLD = 120000, MAT_SILVER = 150000, MAT_DIAMOND = 150000, MAT_URANIUM = 100000)
лучше не хардкодом, а относительно уже существующих дизайнов. Иначе если будут обновляться дизайны, тут что-то может пойти не так.

2023-11-04 17:27 UTC, KatoMarika commented on code/datums/round_aspects/round_aspects.dm
> +	var/datum/map_template/aspect/alchemy/template
> Да и шаблоны это плохая идея при наличии нескольких карт с разными отделами.

А если сделать проверку на выбранную карту?

2023-11-04 18:19 UTC, simb11 commented on code/datums/round_aspects/round_aspects.dm
> +		plsmsh.materials = list(MAT_METAL = 250000, MAT_GOLD = 120000, MAT_SILVER = 150000, MAT_DIAMOND = 150000, MAT_URANIUM = 100000)
то есть, нужно /datum/design добавить новый прок, в котором будут обновляться materials ?

2023-11-04 18:53 UTC, KIBORG04 commented on code/datums/round_aspects/round_aspects.dm
> +		plsmsh.materials = list(MAT_METAL = 250000, MAT_GOLD = 120000, MAT_SILVER = 150000, MAT_DIAMOND = 150000, MAT_URANIUM = 100000)
Не, нужно чтобы был какой-то цикл, который каждой категории накидывает +10000

2023-11-04 18:53 UTC, KIBORG04 commented on code/datums/round_aspects/round_aspects.dm
> +		plsmsh.materials = list(MAT_METAL = 250000, MAT_GOLD = 120000, MAT_SILVER = 150000, MAT_DIAMOND = 150000, MAT_URANIUM = 100000)
for(var/material in materials)
    materials[material] += 50000

2023-11-05 20:30 UTC, simb11 commented on code/datums/round_aspects/round_aspects.dm
> +	var/datum/map_template/aspect/alchemy/template
ревертнул аспект, нет желания мапить для каждой карты темплейт...

2023-11-05 20:33 UTC, simb11 commented on code/datums/round_aspects/round_aspects.dm
> +	afterspawn_IC_announcement = "<span class='warning'>Научно-исследовательский Совет НаноТрейзен стал в меньшей мере интересоваться изучением взрывчатых свойств форона.</span>"
ничего плохого не случится, учёные будут использовать другие способы добычи очков.

2023-11-05 20:34 UTC, simb11 commented on code/modules/events/roundstart_events/area/replace/station_rearmament.dm
> +		/obj/item/weapon/gun/energy/gun = /obj/item/weapon/gun/energy/gun/nuclear,
в этом и суть аспекта
у охранки отличное снаряжение, но без возможности получить новое.

2023-11-09 23:03 UTC, simb11 commented on code/datums/round_aspects/round_aspects.dm
> +		plsmsh.materials = list(MAT_METAL = 250000, MAT_GOLD = 120000, MAT_SILVER = 150000, MAT_DIAMOND = 150000, MAT_URANIUM = 100000)
сделал вроде

2023-11-14 04:38 UTC, volas commented on code/game/objects/structures/crates_lockers/closets/secure/security.dm
> +		qdel(i)
это точно надо? Если у вардена какое-то лишнее оборудование там в шкафу на карте - можно было бы как раз перенести в PopulateContents

2023-11-14 04:39 UTC, volas commented on code/game/objects/structures/crates_lockers/closets/secure/security.dm
> +		qdel(i)
ну и ко всем qdel-ам в PopulateContents ниже такой же вопрос, я думаю будет больше вреда

2023-11-14 14:57 UTC, simb11 commented on code/game/objects/structures/crates_lockers/closets/secure/security.dm
> +		qdel(i)
это нужно чтобы снова наполнять шкафчики после выбора аспекта, в on_start() проке

2023-11-14 19:51 UTC, volas commented on code/game/objects/structures/crates_lockers/closets/secure/security.dm
> +		qdel(i)
а, я вижу, ты дважды инициализируешь шкафы. Может приоритет просто поднять системе, чтоб уже на первом PopulateContents шкафы знали, какой ивент?

2023-11-19 14:29 UTC, simb11 commented on code/game/objects/structures/crates_lockers/closets/secure/security.dm
> +		qdel(i)
Мне это в отдельном ПРе делать или в этом?

2023-11-19 14:42 UTC, volas commented on code/game/objects/structures/crates_lockers/closets/secure/security.dm
> +		qdel(i)
можешь в этом, не должно быть проблемой. Если что - пиши

2023-11-20 19:38 UTC, simb11 commented on code/game/objects/structures/crates_lockers/closets/secure/security.dm
> +		qdel(i)
[19:18:17] Runtime in round_aspects.dm:38 : Cannot execute null.after full init().
  proc name: PostInit (/datum/controller/subsystem/round_aspects/proc/PostInit)
  src: Round Aspects (/datum/controller/subsystem/round_aspects)
  call stack:
  Round Aspects (/datum/controller/subsystem/round_aspects): PostInit()
  Master (/datum/controller/master): Initialize(null, null)
ошибка в инит тестах 
вместо нулла должен быть /datum/round_aspect но его почему-то нет что делать

2023-11-24 20:52 UTC, Deahaka commented on code/datums/round_aspects/round_aspects.dm
> +	afterspawn_IC_announcement = "<span class='warning'>Научно-исследовательский Совет НаноТрейзен стал в меньшей мере интересоваться изучением взрывчатых свойств форона.</span>"
Капец, читая рнд лог заспойлерил себе аспект. Ну раз уже сломал мне интерес, то лучше бы этот аспект не был таким. Лучше бы бомбы по дефолту давали в 5 раз меньше, зато был аспект на х5 очки... Ну а так конечно аспекты бля моё почтение =\

2023-11-28 08:00 UTC, volas commented on code/controllers/subsystem/round_aspects.dm
> +/datum/controller/subsystem/round_aspects/proc/PostInit()
postinit отдельно не нужно, ты можешь обойтись одной лишь инициализацией, повысив приоритет инициализации в /code/__DEFINES/subsystem.dm для ``SS_INIT_ASPECTS``

Можно до карты, рядом с квирками сделать, или рядом с холидеем.

2023-12-04 16:14 UTC, simb11 commented on code/controllers/subsystem/round_aspects.dm
> +	addtimer(CALLBACK(src, PROC_REF(announce_aspect)), 15 SECOND, TIMER_STOPPABLE)
добавил месседж после логина

2023-12-08 06:41 UTC, volas commented on code/controllers/subsystem/round_aspects.dm
> +/datum/controller/subsystem/round_aspects/proc/PostInit()
сами аспекты при создании можно подписать на сигналы тикера и активировать при инициализации, оно так и атомарнее. Я всё еще уверен, что тебе этот PostInit не нужен, и мастеру не следует дополнительно идти подпинывать какие-то избранные сабсистемы.

2023-12-17 10:11 UTC, simb11 commented
@volas убрал постинит, вроде всё работает и без него

2023-12-19 15:34 UTC, volas commented
По отдельным аспектам, если потребуется, кто-то может еще отдельно поднять вопрос реверта.

2023-12-19 15:34 UTC, merged