Выпил откручивания смартхолодильников
TauCetiStation/TauCetiClassic pull request #12385
Opened 2023-11-02 06:40 UTC by Deahaka

## Описание изменений
Это ломает спрайт, выпилил чтобы не ломало.
## Почему и что этот ПР улучшит
closes #12354
## Авторство

## Чеинжлог
:cl: Deahaka
- fix: Холодильники теперь не теряют стекло при взаимодействии с отвёрткой.

2023-11-02 06:40 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2023-11-02 15:00 UTC, AirBlack commented
Его если что можно собирать/разбирать как машинерию. Взял вырезал фичу интеллектуально решение дехаки молодец круто

2023-11-02 15:01 UTC, AirBlack requested changes
Говно, вырезать ради вырезания, за место легкого фикса бага, дехака момент.

2023-11-02 19:05 UTC, muWander commented
а это не слишком имбовый костыль в плане баланса? медбей и так уже перебаффан

2023-11-02 19:07 UTC, Deahaka commented
https://youtu.be/khZA0pd1gEE?si=WvQIgjouTCaO7fvM

2023-11-15 09:26 UTC, Deahaka commented
Хейтеров покормил, а теперь можно мерж

2023-11-20 04:28 UTC, volas commented
> дубликата

где именно другой дублирующийся код, в чем была ошибка и как оно это фиксит

2023-11-20 04:35 UTC, Deahaka commented
13 строчек выше в этом же файле происходит откручивание после скилчека или просто ду афтера. Если его сбить отойдя в сторону, то сработает то, что я и выпилил

2023-11-20 04:48 UTC, volas commented
так сразу бы и написал, давно бы замержили

2023-11-20 04:48 UTC, merged

2023-11-20 04:58 UTC, Deahaka commented
Но так же смешнее. Не хватало только бы йоло-мержа

2023-11-20 05:00 UTC, volas commented
не мейнтейнерам