Cargo Sugar Larvae pack
TauCetiStation/TauCetiClassic pull request #12408
Opened 2023-11-07 21:28 UTC by Deahaka

## Описание изменений
В карго теперь можно заказать сахарных личинок для разделывания на сладенькое мясо. В личинку может зайти гост и она вырастет в что-то прикольное.
## Почему и что этот ПР улучшит
улучшение геймплея карго, больше ситуаций с поваром и ботаниками.
## Авторство
https://github.com/Baystation12/Baystation12
https://github.com/tgstation/tgstation
## Чеинжлог
:cl: Deahaka
- add: В карго можно заказать новый ящик с животными - сахарные личинки.

2023-11-07 21:28 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2023-11-07 21:57 UTC, HalfoftheSeal commented
какой должен быть ролплек за так называемый /datum/species/moth или это респрайт подкида

2023-11-07 22:07 UTC, LudwigVonChesterfield commented on code/modules/cargo/packs.dm
> +/datum/supply_pack/walrus
тип ящика копипащенный

2023-11-07 22:08 UTC, LudwigVonChesterfield commented on code/modules/mob/inventory.dm
> -/mob/living/carbon/ian/slot_id_to_name(slot)
какой-то антирефактор произошёл.

2023-11-08 00:17 UTC, ViDLiathan commented
Кто такие штуки только придумывает..

2023-11-08 09:23 UTC, Naroke commented
> Кто такие штуки только придумывает..

деахака, кто ещё?

2023-11-18 19:30 UTC, Deahaka commented
Адаптировал пару фичек, надеюсь ничего не сломаю переносом создания реагентов у куклы повыше!!

2023-11-18 20:00 UTC, Deahaka commented on code/modules/reagents/reagent_types/Chemistry-Medicine.dm
> +		if(IO.damage > IO.min_bruised_damage)
да тут оказывается можно даже `is_bruised_organ(name)`!!!

2023-11-28 08:31 UTC, volas requested changes
слишком инвазивно для шутки, которая еще конфликтная. Тут какие-то патчи и в звуки, и в оверлеи, и даже в роли, у меня нет времени разбираться со всем и сразу. Может если бы ты разбил по кускам можно было бы постепенно двигаться, а так у меня нет интереса.

2023-11-28 08:58 UTC, volas commented
Моя проблема, что их много. Сама по себе щитспавн раса без особого влияния на раунд не должна иметь 1к изменений по всему билду.

2023-11-28 09:02 UTC, Deahaka commented
А сколько она должна иметь... 3 строчки изменения brute_mod burn_mod и hallos_mod...Ну я ж не респрайт хумана добавляю...

2023-11-28 09:04 UTC, Deahaka commented
Попробую разбить тогда...

2023-11-28 09:57 UTC, Deahaka commented on code/game/objects/structures/crates_lockers/closets/crittercrate.dm
> +/obj/structure/closet/critter/create_mob_inside()
оставлю себе комментарий что тут тайп не дописан

2024-01-21 20:30 UTC, Deahaka commented
чуть-чуть не успеваю, ещё недельку!

2024-01-30 23:45 UTC, Deahaka commented
Finally! Дождались

2024-02-06 17:05 UTC, Deahaka commented
В тм-чик бы отправить на недельку!

2024-02-10 12:56 UTC, volas commented
Выглядит теперь гораздо лучше, но что осталось всё равно надо просмотреть. Кину в ТМ, ты добился своего.

2024-02-10 15:22 UTC, hwat1204 commented
то что можно вселиться в личинку только незадолго после заказа, а затем нельзя, баг или фича?

2024-02-17 13:33 UTC, volas commented on code/game/gamemodes/roles/wild_animal.dm
> +	AppendObjective(/datum/objective/survive)
я не уверен, что требуется их делать антагами, дионы у нас тоже не антаги и антаг это картбланш на всякий щит в раунде

2024-02-17 13:33 UTC, volas commented on code/modules/mob/living/simple_animal/simple_animal.dm
> +/mob/living/simple_animal/proc/handle_evolving()
стоит перенести ближе к ляврам, в общем симпл энимал это лишнее. Можно было бы еще переписать с калбека, но опционально.

2024-02-17 13:33 UTC, volas commented on code/modules/mob/living/carbon/human/human.dm
> +	. = ..(mapload, MOTH)
почему это вдруг две расы теперь

2024-02-17 13:48 UTC, Deahaka commented on code/game/gamemodes/roles/wild_animal.dm
> +	AppendObjective(/datum/objective/survive)
Дионы это гетто-клонинг, а эти не предполагают что за них надо быть добрыми, скорее корыстливыми.

2024-02-17 13:49 UTC, Deahaka commented on code/modules/mob/living/carbon/human/human.dm
> +	. = ..(mapload, MOTH)
Если дотянутся руки, должна будет ещё третяя появится, как и задумал пока лор писал, но пока чуть-чуть занят другим

2024-02-18 19:17 UTC, ViDLiathan commented
Очень мило, но почему бы просто не ввести полноценных ГБС, как играбельную расу? Они довольно крутые и играться будут явно лучше дикой херуёвины из клетки.

2024-02-18 19:33 UTC, Deahaka commented
Попробуй, но токо после мержа этого пра, чтоб конфликтов не было

2024-03-07 20:25 UTC, Deahaka commented on code/modules/mob/living/carbon/human/human.dm
> +	. = ..(mapload, MOTH)
Не будет третьей расы, будет любая раса, но далеко делако потом

2024-03-27 16:10 UTC, LudwigVonChesterfield commented
почему ещё в ТМе?

2024-04-01 08:46 UTC, volas commented on code/modules/mob/living/carbon/species.dm
> +	qdel(I)
опять qdel, и я всё еще не понимаю почему пр на лечинок превратился в две расы

2024-04-01 08:48 UTC, Deahaka commented on code/modules/mob/living/carbon/species.dm
> +	qdel(I)
Так это не одежда, это поедание плоти (и мышей)

2024-04-15 05:31 UTC, volas requested changes
И просьба оформить ПР с подробным описанием, механиками, стадиями и и скринами. Сейчас там есть всё, кроме того, что нужно, и мне приходится разбираться самому.

2024-04-15 05:31 UTC, volas commented on code/modules/mob/living/simple_animal/species_larvaes.dm
> +	var/lore = "Вы агрессивная форма жизни с примитивным интеллектом уровня обезьяны. Вторжение в вашу комфортную зону означает агрессию по отношению к вам. Представителей своего вида вы предпочитаете в
лицензия на гриф? в таком виде не очень, и если надо - получи сначала одобрение у админов

2024-04-15 05:31 UTC, volas commented on code/modules/mob/living/simple_animal/species_larvaes.dm
> +	to_chat(src, "<span class='userdanger'>Вы дружелюбная форма жизни готовая съесть что-угодно.</span>")
```suggestion
	to_chat(src, "<span class='userdanger'>Вы дружелюбная форма жизни, готовая съесть что угодно.</span>")
```

2024-04-15 05:31 UTC, volas commented on code/modules/mob/living/simple_animal/species_larvaes.dm
> +	to_chat(src, "<span class='userdanger'>Вы агрессивная форма жизни практикующая канибализм, так как мясо вашего вида очень вкусное.</span>")
```suggestion
	to_chat(src, "<span class='userdanger'>Вы агрессивная форма жизни, практикующая каннибализм, так как мясо вашего вида очень вкусное.</span>")
```

2024-04-15 05:31 UTC, volas commented on code/modules/mob/living/simple_animal/species_larvaes.dm
> +/mob/living/simple_animal/grown_larvae/proc/handle_evolving()
мне кстати кажется странным, что механики поедания - у взрослых особей, а растут маленькие. Причем, сами по себе.

2024-04-15 05:31 UTC, volas commented on code/modules/mob/living/carbon/species.dm
> +	RegisterSignal(H, COMSIG_S_CLICK_GRAB, PROC_REF(try_tear_body))
я не разобрался, как есть. Или оно у меня не работало. Либо бил себя мышами/органами, либо грабом убивал, но не ел

2024-04-15 05:31 UTC, volas commented on code/modules/mob/living/carbon/species.dm
> +	RegisterSignal(H, COMSIG_S_CLICK_GRAB, PROC_REF(try_tear_body))
Может лучше было бы сделать отдельный верб/кнопку, с подтверждением и прочим (по сигналу ты подтверждение не сделаешь, оно всё сломает)

2024-04-15 05:31 UTC, volas commented on code/modules/mob/living/carbon/species.dm
> +		return
теперь заметил, ограничение тут. Но стоит помнить, что органы есть не органические.

Еще ты не сделал holder-а для новых рас, змеек/молей не взять на руки.

2024-04-15 06:24 UTC, Ro2tCrab commented on code/datums/spawners_menu/spawners_living.dm
>  	time_while_available = 1 MINUTES
- time_while_available удаляет же спавнер сам по себе. Это так и должно быть?

2024-04-15 06:25 UTC, Ro2tCrab commented on code/datums/spawners_menu/spawners_living.dm
>  	time_while_available = 1 MINUTES
Просто в таком случаи сам спавнер чаще всего выходи неиграбельным и сильно зависимым от момента.

2024-04-15 09:17 UTC, Ro2tCrab commented
Наверное стоит докинуть змею TRAIT_STEEL_NERVES чисто из вопроса ощущений от игры за это существо.
Т.к моб по сути не имеет прав члена экипажа и является животным, то относительно часто СБ решает сделать все проще - вывести его из игры.
Это все ещё НЕ спасает от флешбенгов, флешеров, газов и ядов, но это лучше чем вообще не иметь шанса банально сбежать за своё пакостное существование.

2024-04-15 09:18 UTC, Ro2tCrab commented
QoL в виде возможности цеплять PDA и ID на тело.

2024-04-20 12:49 UTC, Deahaka commented
Обновил описание, вроде всё важное расписал.

2024-04-29 16:43 UTC, volas approved these changes
время покажет, было это ошибкой или нет

2024-04-29 16:43 UTC, merged