Крупный перевод титров и немного до перевёл начало игры
TauCetiStation/TauCetiClassic pull request #12437
Opened 2023-11-13 10:22 UTC by AzzyDreemurr13

## Описание изменений
По просьбе Симбаки, в ПРе #12429 перевел не только титры в чате, а в принципе все титры. Все что возможно в ticker.dm и scoreboard.dm переведено. То есть теперь титры в ТГУИ и в чатике будут на русском. Также добавил некоторый перевод для начала игры
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/74739991/e8ce48ca-5c1d-41ea-9b27-dc106d63fb24)
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/74739991/1bc3ecc5-4f34-4458-b026-9ba1749b295e)
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/74739991/8df71b29-f8be-4349-b1b6-bb32a7e0129d)

## Почему и что этот ПР улучшит
Позволит решить вопрос перевода в ПРе симбаки. Для других, статистиката наконец-то понять, за что получены очки в раунде, что произошло в раунде и так далее. А для начала раунда, меньше английского языка.
Чеинжлог
## Авторство
Я
## Чеинжлог
🆑 Azzy.Dreemurr
- localization: Титры теперь на русском языке! 
- spellcheck: До переведены сообщения в чате во время начала раунда

2023-11-13 10:22 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2023-11-13 10:30 UTC, Chip11-n commented on code/controllers/subsystem/jobs.dm
> +		to_chat(world, "<span class='boldannounce'>Ошибка при настройке вакансий, не найдено ни одного рабочего места</span>")
Это скорее сообщение кодеру и мапперу. Датум в данном случае означает не место, а ошибку в коде карты.

2023-11-13 10:32 UTC, Chip11-n commented on code/controllers/subsystem/ticker.dm
> +			to_chat(world, "Пожалуйста, настройте своего персонажа и нажмите на кнопку Ready. Игра начнется через [timeLeft/10].")
Скорее всего забыли "секунд"

2023-11-13 10:33 UTC, Chip11-n commented on code/controllers/subsystem/ticker.dm
> +						to_chat(Player, "<font color='blue'><b>Вам удалось выжить, но вы были выброшены на станции [station_name()]...</b></FONT>")
Выброшены на станции?

2023-11-13 10:57 UTC, Chip11-n commented on code/game/gamemodes/scoreboard.dm
> +		if(250 to 499) SSStatistics.score.rating = "Лучшие из лучших"
Чуть не забыл. Тут градация логически сломана. "Лучшие из лучших" хуже среднестатистической станции и вообще даже не заслуживают повышения. Это относится в целом ко всем оценкам.

2023-11-13 11:01 UTC, Chip11-n commented on code/game/gamemodes/scoreboard.dm
> +		if(250 to 499) SSStatistics.score.rating = "Лучшие из лучших"
Смотри. У нас есть "лучшие из лучших", но они стоят в середине списка. Так получается они не лучшие?

2023-11-13 15:35 UTC, Venngedi commented on code/game/gamemodes/scoreboard.dm
> +		dat += "<B>Самый избитый беглец:</B> [SSStatistics.score.dmgestname], [SSStatistics.score.dmgestjob]: [SSStatistics.score.dmgestdamage] damage ([SSStatistics.score.dmgestkey])<BR>"
Беглец как-то не очень звучит. М.б. лучше "Самый богатый эвакуировавшийся" или "Самый богатый эвакуант"?

2023-11-13 15:35 UTC, Venngedi commented on code/controllers/subsystem/ticker.dm
> +	to_chat(L, "<span class='warning'>Добро пожаловать на арену Смертельных игр в конце раунда! Разгуляйся и выпусти пар!</span>")
Мне кажется, лучше убрать заглавную букву и "в конце раунда"

2023-11-13 15:35 UTC, Venngedi commented on code/controllers/subsystem/ticker.dm
> +		to_chat(world, "<span class='notice bold'>Канал OOC глобально включен для всех!</span>")
"OOC" и "канал" лучше поменять местами или сделать так же, как и здесь
https://github.com/TauCetiStation/TauCetiClassic/pull/12437/files#diff-ba98193161a1c169e99520a26bb1bca121212cdde9a09b760089e9a099288304R193

Наверное, можно ещё убрать "глобально". _Если, конечно, нет способа локально включить общий чат_

2023-11-13 15:35 UTC, Venngedi commented on code/controllers/subsystem/ticker.dm
> +			to_chat(world, "<span class='info bold'>Рестарт раунда отложен администратором.</span>")
Перезапускается сервер, а не раунд. Предлагаю слово "раунд" отсюда убрать

2023-11-13 15:47 UTC, simb11 commented on code/controllers/subsystem/ticker.dm
> +						to_chat(Player, "<font color='blue'><b>Вам удалось выжить, но вы были брошены на станции [station_name()]...</b></FONT>")
существует русское название станции station_name_ru, можешь его использовать вместо английского station_name

2023-11-13 18:05 UTC, Kiromaka requested changes

2023-11-13 18:05 UTC, Kiromaka commented on code/controllers/subsystem/ticker.dm
> +		to_chat(world, "<span class='notice bold'>Канал OOC глобально включен для всех!</span>")
Тут "глобально" и "для всех", убери что-то одно.

2023-11-13 18:05 UTC, Kiromaka commented on code/game/gamemodes/scoreboard.dm
> +		dat += "Станция не была эвакуирована, и никто не спасся!<BR>"
Или*

2023-11-13 18:05 UTC, Kiromaka commented on code/game/gamemodes/scoreboard.dm
> +		dat += "<B>Траты станции:</B> [num2text(profit,50)]<BR>"
Убытки*

2023-11-13 18:06 UTC, Kiromaka commented on code/game/gamemodes/scoreboard.dm
> +		dat += "Станция не была эвакуирована, и никто не спасся!<BR>"
p.s
Типо или не вызывали шатл, или его вызвали, но никто на него не сел.

2023-11-13 20:28 UTC, wadangel commented
> Для других, кто не особо с английским на ВЫ наконец-то понять, за что получены очки в раунде, что произошло в раунде и так далее.

![изображение](https://github.com/TauCetiStation/TauCetiClassic/assets/29904082/57b9bfec-0510-4550-8b5e-146020eb2e33)

а с русским автор на ты или на вы

2023-11-13 21:13 UTC, DarkFurrSss commented
> А смысл? Можешь предложить другой вариант, не буду против заменить это название
уже предложил - поставить название станции, в которой раунд. Вроде [station_name()]

2023-11-16 18:28 UTC, Venngedi commented on code/game/gamemodes/modes_declares/changeling.dm
> +	to_chat(world, "<B>На станции находятся Генокрады. Не дайте им добиться успеха!</B>")
Лишняя заглавная буква

2023-11-16 18:28 UTC, Venngedi commented on code/game/gamemodes/modes_declares/nuclear.dm
> +	to_chat(world, "НаноТрейзен перевозили ядерную боеголовку на военную базу. Транспортный корабль загадочным образом потерял связь с системой управления космическим движением. Примерно в это же время
Можешь, пожалуйста, КС13 заменить на `[station_name_ru()]`?

2023-11-16 18:28 UTC, Venngedi commented on code/game/gamemodes/modes_declares/traitorchan.dm
> +	to_chat(world, "<B>На станции находится инопланетное существо, а также несколько оперативников синдиката, преследующих свои цели! Не дайте Генокраду и предателям добиться успеха!</B>")
Слово "Синдикат" - им. собственное, заглавная нужна. А вот у генокрада она лишняя

2023-11-16 18:28 UTC, Venngedi commented on code/game/gamemodes/modes_declares/traitors.dm
> +	to_chat(world, "<B>На станции находится предатель синдиката. Не дайте предателю добиться успеха!</B>")
Снова проблемы с заглавной.
Лучше заменить "предатель Синдиката" на "агент Синдиката".  Выходит так, что он Синдикат предал, а не на его благо работает. Ну и во множественное число поставить, обычно роль тритора нескольким людям падает

2023-11-16 18:28 UTC, Venngedi commented on code/game/gamemodes/scoreboard.dm
> +	dat += "<B>Cбежавшие на шаттле:</B> [SSStatistics.score.crew_escaped] ([SSStatistics.score.crew_escaped * 25] очков)<BR>"
И снова ассоциации про побег из тюрьмы. Предлагаю заменить на "Улетевшие на шаттле и капсулах". Они тоже учитываются
https://github.com/TauCetiStation/TauCetiClassic/blob/d2cf0654dbe6b34d0d82fdb38bdded7c605a1807/code/game/gamemodes/misc_gamemode_procs.dm#L87C14-L87C14

2023-11-16 19:10 UTC, Kiromaka requested changes

2023-11-16 19:10 UTC, Kiromaka commented on code/game/gamemodes/scoreboard.dm
> +		dat += "Станция не была эвакуирована, или никто не эвакуировался!<BR>"
Ну ты кнч исправил, но вышла тавтология. 
Попробуй - шаттл эвакуации не был вызван, или никто ~~из экипажа~~ не эвакуировался.

2023-11-17 20:11 UTC, KIBORG04 commented on code/controllers/subsystem/jobs.dm
> +		to_chat(H, "Ваша профессия - [rank], и игра просто не может с ней справиться! Пожалуйста, сообщите об этой ошибке администратору.")
```suggestion
		to_chat(H, "Ваша профессия - [rank], и игра почему-то не может её обработать! Пожалуйста, сообщите об этой ошибке администратору.")
```

2023-11-17 20:14 UTC, KIBORG04 commented on code/controllers/subsystem/jobs.dm
> +			warning("Не удалось найти позицию спавна для [rank]. Использование резервной позиции для спавна!")
Это кодерская штука для логов, лучше не трогай

2023-11-17 20:16 UTC, KIBORG04 commented on code/controllers/subsystem/ticker.dm
> +						attachment_title = "Раунд #[global.round_id] окончился",
Волас это прокомментировал?

2023-11-17 20:19 UTC, KIBORG04 commented on code/controllers/subsystem/ticker.dm
> +							to_chat(world, "<span class='notice'><B>Рестарт через [restart_timeout/10] секунд.</B></span>")
У нас есть pluralize_russian функция, которая поможет изменить окончание для слова "секунда" в зависимости от переданного времени. Вот пример: https://github.com/TauCetiStation/TauCetiClassic/blob/b135fc5ce86652eb16eea0cd7b00a74e6a45a5f4/code/controllers/subsystem/vote.dm#L143

2023-11-17 20:19 UTC, KIBORG04 commented on code/controllers/subsystem/ticker.dm
> +							to_chat(world, "<span class='notice'><B>Рестарт из-за уничтожения станции через [restart_timeout/10] секунд.</B></span>")
думаю окончание секундам надо менять, ведь restart_timeout это переменная

2023-11-17 20:22 UTC, KIBORG04 commented on code/controllers/subsystem/ticker.dm
> +			to_chat(world, "<B>Невозможно выбрать игровой режим.</B> Возвращение к предыгровому лобби.")
```suggestion
			to_chat(world, "<B>Невозможно выбрать игровой режим.</B> Возвращение в предыгровое лобби.")
```
мб так?

2023-11-17 20:23 UTC, KIBORG04 commented on code/controllers/subsystem/ticker.dm
> +	world.log << "Начало игры [(world.timeofday - init_start)/10]s"
Это кодерское, не трогай пж

2023-11-17 20:24 UTC, KIBORG04 commented on code/controllers/subsystem/ticker.dm
> +	var/completition = "<h1>Информация по окончанию раунда</h1><HR>"
```suggestion
	var/completition = "<h1>Информация по окончании раунда</h1><HR>"
```

2023-11-17 20:27 UTC, KIBORG04 commented on code/controllers/subsystem/ticker.dm
> +					ai_completions += {"<BR><B><img src="logo_[tempstate].png"> [robo.name] (Игрок: [robokey]) не смог выдержать суровых условий жизни киборга без искусственного интеллекта. Их законы были таковы:</
Почему тут полностью написано "искусственный ителлект", а не аббревиатура. как везде?

2023-11-17 20:29 UTC, KIBORG04 commented on code/controllers/subsystem/ticker.dm
> +					ai_completions += {"<BR><B><img src="logo_[tempstate].png"> [robo.name] (Игрок: [robokey]) выжил как непривязанный киборг к ИИ! Их законы были таковы:</B>"}
Почему ИХ, если тут про борга, то есть нужно писать ЕГО. Видимо, писали `its`, потому что киборг невоодушевленное, хз.

2023-11-17 20:29 UTC, KIBORG04 commented on code/controllers/subsystem/ticker.dm
> +					ai_completions += {"<BR><B><img src="logo_[tempstate].png"> [robo.name] (Игрок: [robokey]) не смог выдержать суровых условий жизни киборга без искусственного интеллекта. Их законы были таковы:</
их

2023-11-17 20:29 UTC, KIBORG04 commented on code/controllers/subsystem/ticker.dm
> +				ai_completions += {"<BR><B><img src="logo_[tempstate].png"> [robo.name] (Игрок: [robokey]) [robo.stat!=2?"выжил":"уничтоженный"] как киборг, подчиненный [robo.connected_ai]! Их законы были таковы
их

2023-11-17 20:33 UTC, KIBORG04 commented on code/controllers/subsystem/ticker.dm
> +						to_chat(Player, "<font color='blue'><b>Вам удалось выжить, но вы были брошены на станции [station_name_ru()]...</b></FONT>")
```suggestion
						to_chat(Player, "<font color='blue'><b>Вам удалось выжить, но вы были брошены на [station_name_ru()]...</b></FONT>")
```
Мне кажется, это избыточно. Вроде в названиях станций уже содержится слово станции, типо "ксн исход"

2023-11-17 20:34 UTC, KIBORG04 commented on code/controllers/subsystem/ticker.dm
> +						to_chat(Player, "<font color='green'><b>Вам удалось пережить события на станции [station_name_ru()] как [Player.real_name].</b></FONT>")
```suggestion
						to_chat(Player, "<font color='green'><b>Вам удалось пережить события на [station_name_ru()] как [Player.real_name].</b></FONT>")
```
тоже избыточность

2023-11-17 20:34 UTC, KIBORG04 commented on code/controllers/subsystem/ticker.dm
> +					to_chat(Player, "<font color='green'><b>Вам удалось пережить события на станции [station_name_ru()] как [Player.real_name].</b></FONT>")
```suggestion
					to_chat(Player, "<font color='green'><b>Вам удалось пережить события на [station_name_ru()] как [Player.real_name].</b></FONT>")
```

2023-11-17 20:35 UTC, KIBORG04 commented on code/controllers/subsystem/ticker.dm
> +				to_chat(Player, "<font color='red'><b>Вы не пережили событий, произошедших на станции [station_name_ru()]...</b></FONT>")
```suggestion
				to_chat(Player, "<font color='red'><b>Вы не пережили событий, произошедших на [station_name_ru()]...</b></FONT>")
```

2023-11-17 20:37 UTC, KIBORG04 commented on code/game/gamemodes/modes_declares/imposters.dm
> +	to_chat(world, "<B>Текущий режим игры - Импостер!</B>")
Импостер 💀 .

Мб нормально перевести? Яндекс советует так
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/26389417/1fa30cb6-21f0-40a1-93b0-100fe3ae26ee)

2023-11-17 20:38 UTC, KIBORG04 commented on code/game/gamemodes/modes_declares/nuclear.dm
> +	to_chat(world, "<B>Горлекс Марадеры приближаются к [station_name_ru()]!</B>")
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/26389417/31976b92-8b5d-4763-acf5-2f19537f72d8)

В нашем дебильном лоре они записаны так

2023-11-17 20:39 UTC, KIBORG04 commented on code/game/gamemodes/modes_declares/replicators.dm
> +	to_chat(world, "<b>Это<span class='userdanger'>репликаторы</span> на станции. Экипаж: Уничтожьте репликаторов до того, как они создадут блюспейс катапульту. Репликаторы: ПОТРЕБЛЯТЬ. ПОТРЕБЛЯТЬ. ПОТР
``
```suggestion
	to_chat(world, "<b>Это <span class='userdanger'>репликаторы</span> на станции. Экипаж: Уничтожьте репликаторов до того, как они создадут блюспейс катапульту. Репликаторы: ПОТРЕБЛЯТЬ. ПОТРЕБЛЯТЬ. ПОТРЕБЛЯТЬ.</b>")
```

2023-11-17 20:39 UTC, KIBORG04 commented on code/game/gamemodes/modes_declares/replicators.dm
>  /datum/game_mode/infestation/announce()
```suggestion
/datum/game_mode/replicators/announce()
```
Кабанчиком исправь, раз тут

2023-11-17 20:40 UTC, KIBORG04 commented on code/game/gamemodes/modes_declares/traitorchan.dm
> +	to_chat(world, "<B>Текущий режим игры - [name]!</B>")
```suggestion
	to_chat(world, "<B>Текущий режим игры - Предатели-Генокрады!</B>")
```
Не надо вставку нейма тут

2023-11-17 20:45 UTC, KIBORG04 commented on code/game/gamemodes/scoreboard.dm
> +	<U>Остальное:</U><BR>
Помнишь я писал про pluralize_russian функцию? Так вот, тут слово "очков" склоняется вообще когда угодно, поэму добавь. Чтобы было проще, сделай где-то рядом дефайн, типа:
```
#define PLURALIZE_RUSSIAN_POINTS(points) pluralize_russian(points, "[points] очка", "[points] очка", "[points] очков")
```

Использование:
```
<B>ИИ уничтожен:</B> [SSStatistics.score.deadaipenalty ? "Да" : "Нет"] (-[SSStatistics.score.deadaipenalty * 250] очков)<BR><BR>
===>
<B>ИИ уничтожен:</B> [SSStatistics.score.deadaipenalty ? "Да" : "Нет"] (-[PLURALIZE_RUSSIAN_POINTS(SSStatistics.score.deadaipenalty * 250)])<BR><BR>
```

и потом ниже используй этот короткий дефайн, а не полностью строку копипасти

2023-11-17 20:47 UTC, KIBORG04 requested changes
После закрытия моих конверсейшонов разрешаю морж

2023-11-17 20:49 UTC, KIBORG04 commented on code/controllers/subsystem/ticker.dm
> +						attachment_title = "Раунд #[global.round_id] окончился",
В общем, хз, пинганю сюда, @volas, тебе переводят дискорд ботов, в том числе и админских, можно или как?

2023-11-17 20:51 UTC, volas commented on code/controllers/subsystem/ticker.dm
> +						attachment_title = "Раунд #[global.round_id] окончился",
тут ок, но я бы лучше "закончился" выбрал

2023-11-18 09:40 UTC, Kiromaka commented
> ![image](https://user-images.githubusercontent.com/74739991/283991040-e33f53af-c9d8-42d0-9b55-23df18575f41.png)

кхм - непривязанный к ИИ киборг, а то странно звучит.

2023-11-18 14:11 UTC, KIBORG04 commented on code/game/gamemodes/scoreboard.dm
>  	var/totalfunds = station_account.money
```suggestion
	#define PLURALIZE_RUSSIAN_POINTS(points) pluralize_russian(points, "[points] очко", "[points] очка", "[points] очков")
	var/totalfunds = station_account.money
```
Знаешь. мб так сделаем для читаемости? Этот дефайн используется только в этом месте, мб стоит перенести его декларацию еще ниже.

А комментарий можешь удалить, он не нужен и дублирует то, что и так понятно.

2023-11-18 14:12 UTC, KIBORG04 commented on code/game/gamemodes/scoreboard.dm
> +	<B>Итоговый бюджет станции:</B> $[num2text(totalfunds,50)]<BR>"}
```suggestion
	<B>Итоговый бюджет станции:</B> $[num2text(totalfunds,50)]<BR>"}
	
	#undef PLURALIZE_RUSSIAN_POINTS
	
```
А еще, дефайн наверное стоит андефайнить, чтобы он "жил" только в контексте данной функции.

Я предлагаю немного спорное и не нужно, так что как хочешь.

2023-11-18 14:12 UTC, KIBORG04 commented on code/game/gamemodes/scoreboard.dm
> +	<B>Итоговый бюджет станции:</B> $[num2text(totalfunds,50)]<BR>"}
А, ну и андеф в любом случае нужен, хоть здесь, хоть после функции, хоть в конце файла

2023-11-18 14:19 UTC, KIBORG04 commented on code/game/gamemodes/scoreboard.dm
> +	<B>Итоговый бюджет станции:</B> $[num2text(totalfunds,50)]<BR>"}
Я думал об этом, но тогда надо выносить и делать дефайн про секунды, про другие частовстречающиеся слова. Я думал как сделать это красиво, но хз

2023-11-18 14:24 UTC, KIBORG04 commented on code/game/gamemodes/scoreboard.dm
> +#define PLURALIZE_RUSSIAN_POINTS(points) pluralize_russian(points, "[points] очко", "[points] очка", "[points] очков")
Забыл удалить

2023-11-18 14:25 UTC, KIBORG04 commented on code/game/gamemodes/scoreboard.dm
> +	<B>Итоговый бюджет станции:</B> $[num2text(totalfunds,50)]<BR>"}
Абсолютно согласен и это не костыль)

2023-11-18 20:39 UTC, KIBORG04 commented
С богом

2023-11-18 20:39 UTC, merged