Перевод сообщений от импланта лояльности
TauCetiStation/TauCetiClassic pull request #12431
Opened 2023-11-12 09:49 UTC by maleyvich

## Описание изменений
тайтл
## Почему и что этот ПР улучшит
еще один перевод никому ненужной вещи
## Авторство
maleyvich
## Чеинжлог
:cl: 
- localization: Были переведены сообщения от импланта лояльности.

2023-11-12 09:49 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2023-11-12 10:27 UTC, Venngedi commented
Возьми лучше отсюда перевод https://wiki.taucetistation.org/index.php?title=Loyalty_Implant&action=edit
```
== Механика ==
После имплантации, у носителя в окне чата с определенной периодичностью будут появляться следующие сообщения:
* {{tooltipRu|''You are sure that NanoTrasen - is the best corporation in the whole Universe!''|Вы уверены, что NanoTrasen - лучшая корпорация во всей вселенной!}}
* {{tooltipRu|''You think that Captain is the greatest man who ever lived!''|Вы думаете, что Капитан - величайший человек, который когда-либо жил!}}
* {{tooltipRu|''You want to give your life away in the name of NanoTrasen!''|Вы хотите отдать свою жизнь во имя NanoTrasen!}}
* {{tooltipRu|''You are confident that all what Heads of station do - is for a greater good!''|Вы уверены, что все, что делается руководителями станции - делается на благо!}}
```
Или в своём убери лишние заглавные буквы

2023-11-12 10:47 UTC, maleyvich commented
> Возьми лучше отсюда перевод https://wiki.taucetistation.org/index.php?title=Loyalty_Implant&action=edit
> 
> ```
> == Механика ==
> После имплантации, у носителя в окне чата с определенной периодичностью будут появляться следующие сообщения:
> * {{tooltipRu|''You are sure that NanoTrasen - is the best corporation in the whole Universe!''|Вы уверены, что NanoTrasen - лучшая корпорация во всей вселенной!}}
> * {{tooltipRu|''You think that Captain is the greatest man who ever lived!''|Вы думаете, что Капитан - величайший человек, который когда-либо жил!}}
> * {{tooltipRu|''You want to give your life away in the name of NanoTrasen!''|Вы хотите отдать свою жизнь во имя NanoTrasen!}}
> * {{tooltipRu|''You are confident that all what Heads of station do - is for a greater good!''|Вы уверены, что все, что делается руководителями станции - делается на благо!}}
> ```
> 
> Или в своём убери лишние заглавные буквы

этот перевод немного странный, поэтому решил немного преобразить его.

2023-11-12 18:18 UTC, Pirsnya commented
Мне кажется можно было бы даже еще чего-нибудь интересного добавить, нет?

2023-11-12 19:57 UTC, KIBORG04 commented on code/game/objects/items/weapons/implants/mindshield.dm
> +				to_chat(imp_in, "\italic Ты уверен в том, что все действия Глав Станции приведут НаноТрейзен к успеху!")
Почему главы станции с большой буквы?

2023-11-12 19:57 UTC, Kiromaka requested changes

2023-11-12 19:57 UTC, Kiromaka commented on code/game/objects/items/weapons/implants/mindshield.dm
> +				to_chat(imp_in, "\italic Ты уверен в том, что все действия Глав Станции приведут НаноТрейзен к успеху!")
Тут ,именно, высшее благо/к лучшему. Т.к, ты не обязан считать, что действия глав, что-то хорошее, если не верен нанотранзенам ( в твоем случае), а в оригинале - ты веришь в то, что главы ахуенны и вобще лучшие в мире.

2023-11-13 09:08 UTC, maleyvich commented
все исправлено

2023-11-14 11:28 UTC, Kiromaka approved these changes

2023-11-20 04:37 UTC, volas commented on code/game/objects/items/weapons/implants/mindshield.dm
> +				to_chat(imp_in, "\italic Вы [pick("уверены", "считаете", "убеждены")], что гендиректор НаноТрейзен - самый лучший человек во Вселенной!!")
Как капитан стал гендиректором, это существенное изменение. Капитан был тут специально для указания лояльности к нему, в числе прочего, как представителю корпорации. А не каким-то абстрактным директорам.

Директора можно отдельно добавить, если хочется, и там даже благодаря гусеву у него имя появилось.

2023-11-20 05:22 UTC, volas commented on code/game/objects/items/weapons/implants/mindshield.dm
> +				to_chat(imp_in, "\italic Вы [pick("уверены", "считаете", "убеждены")], что Капитан - самый лучший человек во Вселенной!!")
очень много вселенных вселенных, в оригинале такого не было

2023-11-20 05:59 UTC, merged