Mines dark atmospheric
TauCetiStation/TauCetiClassic pull request #12469
Opened 2023-11-18 15:22 UTC by Deahaka

## Описание изменений
В неисследованных частях астероида что-то мешает обзору. Страшнее поймать ебаку из темноты.

У робота была сила свечения лампочки как у двух фонариков, из-за чего в комбо с мезонками давало сильную дальность видимости. Сделал чтоб как у всех была.
## Почему и что этот ПР улучшит
потенциал астероиду стать по-настоящему опасным местом, пока что лёгким штрижком делаем под ето фундамент. Прочитал 1млн книг по геймдизайну чтобы до этого додуматься
## Авторство

## Чеинжлог
:cl: Deahaka
- add: на астероиде теперь местами темнее обычного.

2023-11-18 15:22 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2023-11-18 15:55 UTC, Deahaka commented
не, вопрос с боргом это впринципе зачем он там нужен, так что это отдельная тема

2023-11-18 22:43 UTC, Kiromaka commented
Туман войны, только за ним страшной ебаки не будет, потому-что мегафауны нет(

2023-11-18 23:32 UTC, pro100kotah commented
Странный и костыльный способ усложнить игру шахтерам и археологам. Там итак ниче интересного нет. Лучше бы разбавлял геймплей новым контентом. А не... Костылями со светом.

2023-11-20 06:07 UTC, volas commented
скрин можно?

2023-11-20 14:35 UTC, Deahaka commented
> скрин можно?

Слева в опасной части, справа в остальной
![big_bell](https://github.com/TauCetiStation/TauCetiClassic/assets/96499407/8c932ba6-e699-4c42-a84f-638647c1b8b9)

2023-11-20 16:31 UTC, Deahaka commented on code/modules/mining/mine_areas.dm
> +	if(!ismob(A) || istype(A, /mob/living/simple_animal/hostile/asteroid))
потестил, ни ИИ ни госты не получают оверлея никакого. Наверное они и entered не тригеррят, хз

2023-11-22 15:29 UTC, F0xiq commented
В игре просто ужасно выглядит, не видно ничего дальше одной клетки, малоиграбельно. К чему было вводить такую темноту ещё и писать что-то про боргов?

2023-11-24 07:47 UTC, Deahaka commented
Наделал скриншотов чтобы было понятно что человек имеет ввиду:

### Голиаф напал
![bmnm](https://github.com/TauCetiStation/TauCetiClassic/assets/96499407/24c7d8be-dd63-4809-87a2-4774d97fadd4)
### Дальность видимости 2 клетки
![bnmn](https://github.com/TauCetiStation/TauCetiClassic/assets/96499407/25c78daf-68e0-4eb2-bdc2-06eb463e6405)
### Поиск ресурсов
![bvbn](https://github.com/TauCetiStation/TauCetiClassic/assets/96499407/a855556d-2c6c-41ec-8da6-8003e80f214f)
### Мезон-шахтёрские худы включённые
![bmmmm](https://github.com/TauCetiStation/TauCetiClassic/assets/96499407/076aab65-720f-4d4e-b745-493b979ee54f)

2023-11-25 02:55 UTC, volas commented
мне кажется, было бы лучше не оверлей вешать, а как-то модифицировать силу освещения, чтоб эффект всё равно можно было разгонять какими-нибудь прожекторами.

В текущем виде и так маленький экран игры становится еще меньше просто потому что, и игрок ничего не может с этим сделать.

2023-11-25 07:41 UTC, Deahaka commented
Может не идти в тёмное опасное место и искать ресурсы где-нибудь ещё, как и задумано концептом астероида. Прожектора итак увеличивают видимость, просто слабее.

2023-11-25 07:43 UTC, volas commented
концепт астеройда это чтоб там добывали ресурсы, а не игнорировали его, и опасные зоны уже опасны из-за мобов

2023-11-25 07:46 UTC, volas commented
уменьшение яркости кстати тоже так себе будет. Но если добавить отдельную небольшую "пипец опасную зону" с большим количеством ресурсов (может в земле для буров), порезанной яркостью и большим спавном, не портя уже текущую игру, но давая разнообразие хардкорщикам и мазохистам, было бы лучше.

2023-11-25 07:54 UTC, Deahaka commented
Ну это буквально уже так, токо я ещё думаю стоит ли ускорять спавн мобов ещё, а то единственное место где они спавнятся это тут, в остальных местах их по идее быть не может.

2023-11-25 08:00 UTC, volas commented
> Ну это буквально уже так
только ``/area/asteroid/mine/unexplored`` это большая половина астеройда, а не маленькая опциональная зона. 

Кстати, ``/area/asteroid/mine/unexplored/safe/`` это сабтайп, и скорее всего по коду ей тоже оверлей достался, т.е. он висел на всём астеройде кроме дорог

2023-11-25 08:03 UTC, Deahaka commented
Странно, ведь у нас есть explored как отдельный тип... Завтра посмотрю в сдмм где этот safe

2023-11-26 13:24 UTC, Deahaka commented
> только `/area/asteroid/mine/unexplored` это большая половина астеройда, а не маленькая опциональная зона.

Посмотрел, это оказалось реально так... Весь астероид по сути это unexplored, только в правой части выключен спавн мобов (но не артефактов).
Попробовал сделать так, чтобы только меньшая часть астероида была под вуалью. Ну и раз уже сразу озвучен запрос на добавление опасной зоны с большим лутом, то твикнул компоненту для этой части шахты.

Теперь левая верхняя и левая нижняя часть астероида считаются "более опасными" на Боксе, на Фальконе правая нижняя часть, на Прометей-астероиде почти весь центр. Остальные не меняются.

2023-11-27 10:50 UTC, F0xiq commented
Крайне неудачное решение затемнять астероид в любом случае, весь геймплей шахтеров будет до первого василиска от которого из темноты прилетит заморозка и ты ничего с этим не сделаешь, потому что просто не видишь его. Во-вторых это делает совершенно бесполезным апгрейд кинетика на дальность, он и раньше то был не самым полезным, так как даже с первым апгрейдом стреляешь уже по самой границе видимости, но всё-таки имел какое-то применение и покупался, теперь смысла в нём вообще нет. В-третьих правую часть астероида на боксе нет никакого смысла копать, там ресурсов нет практически никаких. Зачем бездумно ломать баланс шахтёрства непонятно.

2023-11-27 10:57 UTC, Deahaka commented
Будем считать что дальность стрельбы, как и сам кинетик, больше для стрельбы по монстрам, а не по камням. 

Остальное — цель изменения, а не неожиданное последствие. Копать малоресурсные точки есть смысл, как и ставить бур, чтобы накопить очков на средства борьбы с опасностями в богатых регионах. Они не сильно дорогие, хоть можно попытаться обойтись без них и рискнуть жизнью, получив большую награду

2023-11-27 11:42 UTC, Deahaka commented
Никого не заставляем, хотят — идут, не хотят — не идут.

2023-11-28 08:47 UTC, volas commented
> Теперь левая верхняя и левая нижняя часть астероида считаются "более опасными" на Боксе

левый астеройд же уже сам по себе сложнее, я бы понял напиши ты про левую верхнюю часть, но раз ты пишешь про нижнюю - у нас он в среднем классе опасности вообще остался?

Мапдифф не показывает изменения зон, скрины бы не помешали.

2023-11-29 09:17 UTC, Deahaka commented
![aastoroid](https://github.com/TauCetiStation/TauCetiClassic/assets/96499407/ead5d729-4a47-4f82-b009-bc39a84eca77)
![assteroid_falcon](https://github.com/TauCetiStation/TauCetiClassic/assets/96499407/13aed61d-13af-4c7a-9819-bce03b5bb49b)
![assteroid_prometheous](https://github.com/TauCetiStation/TauCetiClassic/assets/96499407/ec8da2de-116c-422a-90fe-d25e4b2ab8f4)

2023-12-01 05:54 UTC, volas commented
не, ты опять перестарался

2023-12-01 06:00 UTC, volas commented
возьми от силы 1/4, в самых дальних углах астеройда. В случае дефолтного - можно взять левый верхний угол, центр и низ и левое пусть как были так и будут. Либо центральную часть левой половины, вокруг логова дварфов.

На фальконе оно не нужно, на прометее можно так же какой-то нижний угол взять или спросить дефора.

2023-12-08 06:51 UTC, volas requested changes
^

2023-12-19 15:48 UTC, volas commented on code/modules/mining/mine_areas.dm
> +	to_chat(A, "<span class='warning'>Suspension of particles obstructs the view.</span>")
```suggestion
	to_chat(A, "<span class='warning'>Suspension of particles obstructs the view. This area are more dangerous.</span>")
```

2023-12-27 16:17 UTC, Deahaka commented
Обновил, уменьшив перемапив зоны опаснсостей:
![aastoroid](https://github.com/TauCetiStation/TauCetiClassic/assets/96499407/9f67903d-67ac-4a9b-8288-87d27d3d49ff)
![assteroid_prometheous](https://github.com/TauCetiStation/TauCetiClassic/assets/96499407/ccd4e940-34c2-4b20-8646-28e3df3ce1b1)

Фалькон ревёртнут

2023-12-29 20:55 UTC, volas approved these changes

2023-12-29 20:55 UTC, merged

2024-01-29 16:31 UTC, Deahaka commented
Кстати хоть уже и замержено, но если кто-то вспомнит про аргумент "у шахтёров итак экран не большой, а тьма делает его ещё меньше", то я на будущее уже отвечу: "поиграйте в игру". Потому что у шахтёров при копании зрение независимо от света и тьмы радиус зрения 1 клетка 80% времени. Копая кишку, они не видят ничего дальше первого камня в поле зрения.
![mnmn](https://github.com/TauCetiStation/TauCetiClassic/assets/96499407/0f04e4e7-9992-427e-a046-c9c58f55dc40)