Translate Environment. Cases for floors
TauCetiStation/TauCetiClassic pull request #12505
Opened 2023-11-23 14:08 UTC by maleyvich

## Описание изменений
Для плиток пола добавлены падежи
## Почему и что этот ПР улучшит
перевод
## Авторство
maleyvich
## Чеинжлог
:cl:
- localization: Добавление руссифицированных падежей для плиток пола.

2023-11-23 14:08 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2023-11-23 14:09 UTC, maleyvich commented
спорный момент: перевод "plating" как поверхность, однако для меня это лучший перевод чем покрытие

2023-11-23 14:12 UTC, AndroBetel commented
plating это обшивка
но почему floor превратился в плитки вообще загадка

2023-11-23 14:12 UTC, maleyvich commented
> plating это обшивка но почему floor превратился в плитки вообще загадка

floor это ПОЛ
пол в чём? в ПЛИТКАХ

2023-11-23 14:19 UTC, Kiromaka commented on code/game/turfs/simulated/floor_types.dm
> +	cases = list("травяной плитки", "травяной плитке", "травяная плитка", "травяной плиткой", "травяной плитке")
Удивительно, но это должна быть реальная трава, а не плитка, хоть это и странно.

М.б травяного покрытия, сам решай.

2023-11-23 14:20 UTC, maleyvich commented on code/game/turfs/simulated/floor_types.dm
> +	cases = list("травяной плитки", "травяной плитке", "травяная плитка", "травяной плиткой", "травяной плитке")
> Удивительно, но это должна быть реальная трава, а не плитка, хоть это и странно.
> 
> М.б травяного покрытия, сам решай.

траву ломом не сдирают, или самые отчаянные.

2023-11-23 14:21 UTC, Kiromaka commented on code/game/turfs/simulated/floor_types.dm
> +	cases = list("травяной плитки", "травяной плитке", "травяная плитка", "травяной плиткой", "травяной плитке")
ну я и говорю странно. Кто назвал ее grass patch.....

2023-11-23 14:23 UTC, maleyvich commented on code/game/turfs/simulated/floor_types.dm
> +	cases = list("травяной плитки", "травяной плитке", "травяная плитка", "травяной плиткой", "травяной плитке")
get fixed

2023-11-23 14:29 UTC, maleyvich commented on code/game/turfs/simulated/floor.dm
> +	cases = list("плитки пола", "плитке пола", "плитку пола", "плиткой пола", "плитке пола")
добавил подтипу ковров падежи, у флуров где не стоят падежи, они там и не должны стоять и должны наследоваться от родителя

2023-11-23 14:31 UTC, maleyvich commented on code/game/turfs/simulated/floor.dm
> +	cases = list("поверхности", "поверхности", "поверхность", "поверхностью", "поверхности")
не понял, но заменил на обшивку

2023-11-23 14:58 UTC, maleyvich commented on code/game/turfs/simulated/floor.dm
> +	cases = list("плитки пола", "плитке пола", "плитку пола", "плиткой пола", "плитке пола")
fixed

2023-11-23 15:31 UTC, maleyvich commented on code/game/turfs/simulated/floor.dm
> +	cases = list("поверхности", "поверхности", "поверхность", "поверхностью", "поверхности")
вроде бы пофиксил

2023-11-24 07:06 UTC, maleyvich commented on code/game/turfs/floor/carpets.dm
> +	cases = list("ковра", "ковру", "ковёр","ковром", "ковре")
зачем уточнять какой ковёр? будет достаточно просто того, что выстрелили в ковёр

2023-11-24 07:39 UTC, maleyvich commented on code/game/turfs/floor/carpets.dm
> +	cases = list("ковра", "ковру", "ковёр","ковром", "ковре")
буквально выше падежи для нормальных ковров (и падежи будут от них наследоваться)

то на что ты указываешь это голоковер который не наследует свойства ковра и падежи надо указывать для него снова

2023-11-24 09:45 UTC, AndroBetel commented on code/game/objects/items/stacks/tiles/tile_types.dm
> +	desc = "Часть ковра, соразмерная плитке."
вот бы переводчики выучили русский перед тем как на него переводить

2023-11-24 09:58 UTC, maleyvich commented
проблема ковров решена
если есть идея как лучше перевести их описание - пишите сюда, текущая версия не выбивается из оригинала и более читабельна

2023-11-24 22:02 UTC, Kiromaka commented
[DNM] merge after #12509 and changes

2023-11-25 07:50 UTC, volas commented on code/game/turfs/floor/carpets.dm
> +	cases = list("ковра", "ковру", "ковёр","ковром", "ковре")
> зачем уточнять какой ковёр? будет достаточно информации просто того, что выстрелили в ковёр

если бы было достаточно, все ковры бы именовались просто коврами уже на английском

2023-11-25 08:56 UTC, maleyvich commented on code/game/turfs/floor/carpets.dm
> +	cases = list("ковра", "ковру", "ковёр","ковром", "ковре")
сделано

2023-11-25 09:02 UTC, maleyvich commented
в пр добавлен именительный падеж для всех измененных вещей
к мержу готово

2023-11-29 20:34 UTC, Chip11-n commented on code/game/turfs/simulated/floor_types.dm
> +	cases = list("плитка пола", "плитки пола", "плитке пола", "плитку пола", "плиткой пола", "плитке пола")
Не особо смотрел, но на шаттле тоже будет плитка?

2023-11-30 13:33 UTC, Pivo24 commented on code/game/objects/items/stacks/tiles/tile_types.dm
> +	desc = "Соразмерная плитке, часть ковра."
Поменять местами может? Инверсия ни к месту

"Часть ковра, соразмерная плитке."

2023-11-30 13:33 UTC, Pivo24 commented on code/game/objects/items/stacks/tiles/tile_types.dm
> +	desc = "Соразмерная плитке, часть чёрного ковра."
Same со всеми цветами по поводу инверсии предложения

2023-11-30 13:33 UTC, maleyvich commented on code/game/objects/items/stacks/tiles/tile_types.dm
> +	desc = "Соразмерная плитке, часть ковра."
нет инверсию сказал сделать киборг и аззи ниче не знаю менять уже не буду надоели

2023-11-30 13:34 UTC, maleyvich commented on code/game/objects/items/stacks/tiles/tile_types.dm
> +	desc = "Соразмерная плитке, часть чёрного ковра."
такое же обьяснение что и выше

2023-12-01 06:03 UTC, volas commented on code/game/turfs/floor/carpets.dm
> +	cases = list("ковра", "ковру", "ковёр","ковром", "ковре")
я всё еще вижу тут обычный ковер, а не красный классический

2023-12-01 06:04 UTC, volas commented on code/game/objects/items/stacks/tiles/plasteel.dm
> +	cases = list("плитка пола", "плитки пола", "плитке пола", "плитку пола", "плиткой пола", "плитке пола")
неконсистентность - в некоторых местах tile в переводе остался, в некоторых опустили

2023-12-01 06:05 UTC, volas commented on code/game/turfs/simulated/floor.dm
> +	cases = list("деревянный пол", "деревянного пола", "деревянному полу", "деревянный пол", "деревянным полом", "деревянном поле")
ради этого можно было бы сперва отрефакторить полы, чем копипастить текст тут и там

2023-12-01 06:06 UTC, volas commented on code/game/turfs/simulated/floor_types.dm
> +	cases = list("плитка пола", "плитки пола", "плитке пола", "плитку пола", "плиткой пола", "плитке пола")
будет унаследовано от родителя, переопределять не надо

2023-12-01 06:08 UTC, volas requested changes
это не то, что надо было бы переводить в одной из первых очередей, да еще так непостоянно. Лучше бы взялись с чего-то масштабом поменьше.

И конкретно с полом лучше сначала отрефакторить, у него много костылей и копипаста из-за разных типов трансформаций.

2023-12-01 07:29 UTC, maleyvich commented
Ок

2023-12-01 07:29 UTC, closed without merging