no pain on switching species to NO_PAIN one
TauCetiStation/TauCetiClassic pull request #12507
Opened 2023-11-23 15:09 UTC by muWander

## Описание изменений
Прок set_species ставит болевой шок на 0 если у целевого гуманоида флаг игнорирования боли, сейчас если раса гуманоида сменяется в течение раунда шок остается навсегда без возможности снять кроме как педально
## Почему и что этот ПР улучшит

## Авторство

## Чеинжлог
:cl: 
 - bugfix: Превращение в слаймо-человека токсином ксенобиолога больше не чревато вечным замедлением.
 - bugfix: Скелеты больше не замедляются навечно, если были ранены при жизни.

2023-11-23 15:09 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2023-11-23 22:16 UTC, LudwigVonChesterfield commented on code/modules/mob/living/carbon/human/human.dm
> +		shock_stage = 0
я бы предпочёл заменить это на геттеры-сеттеры и тогда проблема была бы на 100% решена потому-что при получении флага геттер бы возвращал 0

2023-12-01 06:17 UTC, volas requested changes
тут вроде реквест, я просто статус изменяю

2023-12-08 07:04 UTC, volas approved these changes

2023-12-08 07:05 UTC, volas commented
в целом и так ок, гетеры/сетеры было бы хорошим бонусом но можно потом получить

2023-12-08 07:05 UTC, merged