Перевод слипера и названий реагентов (и немного бутылочек)
TauCetiStation/TauCetiClassic pull request #12584
Opened 2023-12-07 11:22 UTC by maleyvich

## Описание изменений
переведен аппарат диализа (Sleeper) и названия реагентов, части кода связанные с баночками
Resolves https://github.com/TauCetiStation-TranslationDepartment/TauCetiClassic/issues/8
фотокарточки:
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/104298869/72f6d2d1-0fd9-43f9-ae3f-442298f63b5e)
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/104298869/e2731e63-9d1e-4fe7-9f5f-749d16ee92a0)
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/104298869/456a7639-ea7e-43e4-925c-d9cdedff3cb8)

## Почему и что этот ПР улучшит
перевод
## Авторство
maleyvich, трансдеп  таукиты
## Чеинжлог
:cl:
- ru: Аппарат "Sleeper", названия реагентов и часть кода связанная с наполнением бутылок/таблеток были переведены на русский язык.

2023-12-07 11:34 UTC, Kiromaka commented
> почему не перевести слипер как слипер, если все его так называют, какая нахуй камера диализа

Он уже давно не слипер по функционалу, + хуита. Камера Диализа мне тоже не нравиться, но что есть, то есть.

2023-12-07 11:34 UTC, maleyvich commented
> почему не перевести слипер как слипер, если все его так называют, какая нахуй камера диализа

по результатам обсуждения трансдепа

2023-12-07 11:36 UTC, Kiromaka commented
Нейэмы переведены... не нравиться мне это.... падежи нужны падежи...

2023-12-07 11:37 UTC, Kiromaka requested changes

2023-12-07 11:37 UTC, Kiromaka commented on code/game/machinery/Sleeper.dm
> +		to_chat(target, "<span class='notice'><b>Вы чувствуете охлаждение воздуха в капсуле...</b></span>")
пикачушка прав, хуита, меняй.

2023-12-07 12:14 UTC, maleyvich commented
> здесь даже половины нет от всех реагентов

теперь есть содержание пра согласно описанию...

2023-12-07 12:42 UTC, maleyvich commented on code/modules/reagents/reagent_types/Chemistry-Drinks.dm
> +	name = "Мороженное"
я ёбнулся вот поэтому

выше со сливками (где они есть) уже всё нормально

2023-12-07 17:35 UTC, KandreyKandrey commented on code/modules/reagents/reagent_types/Chemistry-Toxic.dm
>  	id = "jenkem"
почему оба слова с большой буквы?

2023-12-07 17:36 UTC, KandreyKandrey commented on code/modules/reagents/reagent_types/Chemistry-Toxic.dm
>  	id = "ambrosium"
амброзия?

2023-12-07 17:41 UTC, KandreyKandrey commented on code/modules/reagents/reagent_types/Chemistry-Toxic.dm
>  	id = "chefspecial"
почему второе слово с большой?

2023-12-07 17:43 UTC, maleyvich commented on code/modules/reagents/reagent_types/Chemistry-Toxic.dm
>  	id = "chefspecial"
потому-что в оригинале оно тоже с большой буквы? да, расположено в разных местах - но у нас 
 названия некоторых напитков состоят из двух и более заглавных букв

2023-12-07 17:44 UTC, maleyvich commented on code/modules/reagents/reagent_types/Chemistry-Toxic.dm
>  	id = "jenkem"
это тоже сомнительно, вероятно можно и оставить две буквы больших по аналогии с другими увеселительными средствами

2023-12-07 17:46 UTC, KandreyKandrey commented on code/modules/reagents/reagent_types/Chemistry-Drinks.dm
>  	id = "margarita"
буква лишняя

2023-12-07 17:47 UTC, KandreyKandrey commented on code/modules/reagents/reagent_types/Chemistry-Drinks.dm
>  	id = "tequilla"
буква лишняя

2023-12-07 17:47 UTC, KandreyKandrey commented on code/modules/reagents/reagent_types/Chemistry-Drinks.dm
>  	id = "gin"
джин?

2023-12-07 17:48 UTC, KandreyKandrey commented on code/modules/reagents/reagent_types/Chemistry-Drinks.dm
>  	id = "doctorsdelight"
а тут второе слово с маленькой буквы

2023-12-07 17:48 UTC, KandreyKandrey commented on code/modules/reagents/reagent_types/Chemistry-Drinks.dm
>  	description = "Glorious brainfreezing mixture. Now with cocoa!"
тут второе слово с маленькой

2023-12-07 17:48 UTC, KandreyKandrey commented on code/modules/reagents/reagent_types/Chemistry-Drinks.dm
>  	description = "A tangy substance made of 0.5% natural citrus!"
тут второе слово с маленькой

2023-12-07 17:49 UTC, KandreyKandrey commented on code/modules/reagents/reagent_types/Chemistry-Drinks.dm
>  	id = "space_up"
вторая часть с маленькой

2023-12-07 17:50 UTC, maleyvich commented on code/modules/reagents/reagent_types/Chemistry-Drinks.dm
>  	description = "Glorious brainfreezing mixture. So sweet!"
все это взял на прицел, сейчас не у компьютера - завтра залью коммит с исправлением

2023-12-08 07:47 UTC, maleyvich commented
в пр были добавлены ингейм-картинки, также была переведена часть кода связанная с наполненностью бутылок и таблеток

2023-12-15 07:30 UTC, simb11 commented on code/game/machinery/Sleeper.dm
> +		to_chat(user, "<span class='notice'>Пациенту было введено [units] юнит(ов) [chem] в организм.</span>")
Пациенту было введено 10 юнит(ов) anti_toxin в организм)))

2023-12-15 07:36 UTC, simb11 commented on code/modules/reagents/reagent_types/Chemistry-Drinks.dm
> +	name = "Нюка-Кола"
```suggestion
	name = "Ядер-Кола"
```
она так переводится в почти всех частях фолыча
https://fallout.fandom.com/ru/wiki/%D0%AF%D0%B4%D0%B5%D1%80-%D0%9A%D0%BE%D0%BB%D0%B0

2023-12-15 07:41 UTC, simb11 commented on code/modules/reagents/reagent_types/Chemistry-Drinks.dm
> +	name = "Тринадцатая Компания"
Мне кажется это не нужно переводить дословно

2023-12-15 08:49 UTC, maleyvich commented on code/modules/reagents/reagent_types/Chemistry-Drinks.dm
> +	name = "Тринадцатая Компания"
хз как по мне очень даже звучит

2023-12-15 08:50 UTC, maleyvich commented on code/game/machinery/Sleeper.dm
> +		to_chat(user, "<span class='notice'>Пациенту было введено [units] юнит(ов) [chem] в организм.</span>")
хм я подумал как можно было бы решить эту проблему

2023-12-15 08:51 UTC, maleyvich commented on code/game/machinery/Sleeper.dm
> +		to_chat(user, "<span class='notice'>Пациенту было введено [units] юнит(ов) [chem] в организм.</span>")
хм идея не сработала

2023-12-15 08:52 UTC, maleyvich commented
> @maleyvich в описание ещё один резовл добавь Resolves #12613

он не фиксит эту проблему

2023-12-15 08:59 UTC, Kiromaka commented on code/game/machinery/Sleeper.dm
> +		to_chat(user, "<span class='notice'>Пациенту было введено [units] юнит(ов) [chem] в организм.</span>")
chem.name ?

2023-12-15 09:06 UTC, maleyvich commented on code/game/machinery/Sleeper.dm
> +		to_chat(user, "<span class='notice'>Пациенту было введено [units] юнит(ов) [chem] в организм.</span>")
ne rabotaer

2023-12-20 15:31 UTC, volas commented on code/modules/reagents/reagent_types/Chemistry-Toxic.dm
> +	name = "Серотротий"
а, я понял вас. Наверно. Надо только почекать, чтоб это ничего не сломало

2023-12-20 15:34 UTC, maleyvich commented on code/modules/reagents/reagent_types/Chemistry-Toxic.dm
> +	name = "Серотротий"
из самого неприятного это во всяких автоматах барменских и в химии будет слегка неконсинстентно, но химию надо определенно позже затрагивать.
а так я проверял ещё неделю назад, всё нормально работает

2023-12-20 15:42 UTC, maleyvich commented on code/game/machinery/Sleeper.dm
> +	var/datum/browser/popup = new(user, "капсула диализа", "консоль капсулы диализа", 520, 605)	//Set up the popup browser window
айдишник переведен чтобы прям точно всё было на русском? а маленькие буквы исправил, да.

2023-12-21 07:44 UTC, maleyvich commented on code/game/machinery/Sleeper.dm
> +	var/datum/browser/popup = new(user, "капсула диализа", "консоль капсулы диализа", 520, 605)	//Set up the popup browser window
оно ничего не ломает а название окошечка исправлено

2023-12-21 10:10 UTC, maleyvich commented on code/game/machinery/Sleeper.dm
> +	var/datum/browser/popup = new(user, "капсула диализа", "консоль капсулы диализа", 520, 605)	//Set up the popup browser window
хм хорошо перевод айдишника уберу

2023-12-21 16:42 UTC, volas commented on code/modules/reagents/reagent_types/Chemistry-Toxic.dm
> +	name = "Серотротий"
почекать - стоит именно весь билд проверить, где может использоваться name реагентов, возможно где-то есть хардкод со старыми названиями. Это лучше кому-то опытному, ну или я ближе к мержу прогляжу

2023-12-24 07:55 UTC, MarcusFrei commented on code/game/machinery/Sleeper.dm
Может быть стоит это просто назвать медицинской капсулой, так как по сути в ней много функционала, введение в стазис, диализ, а также ввод медикаментов различного назначения. В той же научной фантастика название вписывается довольно органично.

2023-12-26 06:01 UTC, volas commented on code/modules/reagents/reagent_types/Chemistry-Toxic.dm
> +	name = "Серотротий"
в общем я пробежался, как минимум поиском по ``R.name``:
1. /obj/item/mecha_parts/mecha_equipment/syringe_gun/ использует name и английские названия реагентов
2. ``/obj/machinery/chem_master/Topic`` проверяет кровь по английскому названию name
3. в нескольких местах в логах используется ``get_english_list(injected)``, где injected - список имен, подразумевающихся английских
4. ``get_imprinter_data`` в рнд консоли

в целом /datum/reagent в билде упомянут 936 раз, и проверять всё слишком долго. Я бы всё же предложил не изобретать велосипеды, а делать, как уже делали - через CASE. Это решает и проблему совместимости, и проблему склонений реагентов

2023-12-26 06:05 UTC, volas requested changes
https://github.com/TauCetiStation/TauCetiClassic/pull/12584/files#r1436260540

переместите cases на уровень датумов или реагентов, и переводите их. Name реагентов всё еще может быть проблемно делать, ПР и так большой чтоб еще по всему билду исправления вносить

2024-01-13 12:17 UTC, maleyvich commented
пр жив

2024-01-17 07:03 UTC, closed without merging

2024-01-17 07:03 UTC, volas commented
пр пока скорее мертв, вернетесь к нему - слапните, я переоткрою