Перевод описания вирусов
TauCetiStation/TauCetiClassic pull request #12587
Opened 2023-12-07 20:26 UTC by Fenriros

## Описание изменений
Перевод описания вирусов
## Почему и что этот ПР улучшит
Потому что  это поможет разобраться в вирусах
## Авторство
я
## Чеинжлог
:cl:
ru: Перевод описания вирусов

2023-12-07 20:50 UTC, KandreyKandrey commented on code/modules/virus2/effect.dm
> +	desc = "Вирус заставляет носителя впасть в кому подобную смерти после получения серьёзных повреждений, затем быстро восстанавливает их."
запятые не пропущены?

2023-12-07 20:52 UTC, KandreyKandrey commented on code/modules/virus2/effect.dm
> +	passive_message = "<span class='notice'>Боль от ваших ран заставляет чуствовать вас сонным...</span>"
1) буква случайно или специально(из-за недосыпа куклы) пропущена?
2) не лучше будет 'боль от ран заставляет вас чувствовать себя сонным' или 'боль от ран делает вас сонливым' ?

2023-12-07 20:52 UTC, KandreyKandrey commented on code/modules/virus2/effect.dm
> +		to_chat(M, "<span class='warning'>Вы чувствуете как впадаете в регенеративную кому...</span>")
запятая не пропущена?

2023-12-07 20:54 UTC, KandreyKandrey commented on code/modules/virus2/effect.dm
> +	desc = "Вирус ускоряет метаболизм хозяина, заставляя проходить химические процессы в два раза быстрее, но повышая при этом голод."
не может возникнуть ощущение, что вирус заставляет хозяина проходить химические процессы?
и процессы вроде протекают
мб лучше так 'вирус ускоряет метаболизм хозяина, заставляя химические процессы протекать в два раза быстрее, но повышает при этом голод' ?

2023-12-07 20:54 UTC, Fenriros commented
Проверьте побольше потому что не хочу много коммитов делать. А сейчас я спать, надеюсь проснусь здоровым

2023-12-07 20:55 UTC, KandreyKandrey commented on code/modules/virus2/effect.dm
> +		to_chat(mob, "<span class='warning'>[pick("Вы чувствуете как разваливаетесь на части.", "Ваша кожа стирается словно пыль.")]</span>")
запятые не пропущены?

2023-12-07 21:00 UTC, KandreyKandrey commented on code/modules/virus2/effect.dm
> +		to_chat(mob, "<span class='userdanger'>[pick("Вы чувствуете как ваши мышци слабеют.", "Ваша кожа отслаивается сама по себе.", "Вы как буд-то растворяетесь.")]</span>")
запятая перед 'как' не пропущена?

в 247 строчке 'будто' написано слитно, а тут раздельно (как правильно?)
гугл говорит, что всегда слитно

2023-12-07 21:02 UTC, KandreyKandrey commented on code/modules/virus2/effect.dm
> +	desc = "Вирус генерирует сероводород в кровотоке, повреждая вены и артерии. В особых случаях, передозировка сероводородом может привести к взрыву, разнося носителя на кусочки."
запятые?
'в особых случаях передозировка может привести к взрыву, который разнесёт носителя на кусочки.'

2023-12-07 21:03 UTC, KandreyKandrey commented on code/modules/virus2/effect.dm
> +			to_chat(mob, "<span class='notice'>[pick("Вы почему-то злитесь.", "Ваша кожа шелушиться.", "Ваша кожа горит.", "То тут то там появляются маленькие ранки на вашей коже.")]</span>")
мягкий знак лишний
'то тут, то там на вашей коже появляются маленькие ранки' + запятая

2023-12-07 21:10 UTC, KandreyKandrey commented on code/modules/virus2/effect.dm
> +			to_chat(mob, "<span class='warning'>У вас болит груль!</span>")
промахнулся

2023-12-07 21:11 UTC, KandreyKandrey commented on code/modules/virus2/effect.dm
> +	desc = "Вирус производит нанитов в пищеварительной системе носителя, которые размножаются и питаются тканями организма, вызывая кровотечение с рвотой."
я бы перефразировал первую часть как 'вирус производит в пищеварительной системе носителя нанитов, ...'

2023-12-07 21:12 UTC, KandreyKandrey commented on code/modules/virus2/effect.dm
> +					h.say(pick("О,Банан?", "У тебя есть бананы?", "У-У-У-и-и","Уо Уо Уои ээи ээи иии ииии", "Иииир! Иииир!"))
'О, банан?'
или специально так написано?

2023-12-07 21:12 UTC, KandreyKandrey commented on code/modules/virus2/effect.dm
> +					to_chat(A, "<span class='danger'>[pick("Вы реально хотитте бананов.", "Вы замечатете как начинатете деградировать.", "Вы становитесь ниже.", "Шерсть проступает на вашей коже.")]</span>")
опечатки случайные или специальные?

2023-12-07 21:13 UTC, KandreyKandrey commented on code/modules/virus2/effect.dm
> +	desc = "Вирус приcоединяется к ДНК Хозяина, вызывая вредные мутации до его удаленния."
'Вирус присоединяется к ДНК хозяина, вызывая до удаления вредные мутации'

2023-12-07 21:13 UTC, KandreyKandrey commented on code/modules/virus2/effect.dm
> +		to_chat(mob, "<span class='notice'>[pick("Вы чувствуете себя совсем по другому.", "Вы чувствуетет зуд по всему телу.", "Вы чувствуете лёгкое головокружение.")]</span>")
'по-другому'
'чувствуете'

2023-12-07 21:14 UTC, KandreyKandrey commented on code/modules/virus2/effect.dm
> +		to_chat(mob, "<span class='warning'>[pick("Вы чувствуете что что=то поменялось в вас.", "У вас болит голова.")]</span>")
'Вы чувствуете, что в вас что-то поменялось'

2023-12-07 21:14 UTC, KandreyKandrey commented on code/modules/virus2/effect.dm
> +			to_chat(mob, "<span class='notice'>[pick("Вы чувствуетет зуд по всему телу.", "Вы чувствуетет слабость.")]</span>")
'чувствуете' ?

2023-12-07 21:15 UTC, KandreyKandrey commented on code/modules/virus2/effect.dm
> +			to_chat(mob, "<span class='notice'>[pick("Вы видете, что стали менее ловким.", "Вы двигаетесь более неуклюже, чем обычно.")]</span>")
'видите' или 'замечаете' ?

2023-12-07 21:15 UTC, KandreyKandrey commented on code/modules/virus2/effect.dm
> +				to_chat(mob, "<span class='notice'>Вы поняли, что ваши конечности не такие крепкие как прежде..</span>")
'не такие крепкие, как прежде' ?

2023-12-07 21:16 UTC, KandreyKandrey commented on code/modules/virus2/effect.dm
> +	desc = "Вирус реагирует на звездный свет, вырабатывая регенерирующие химические вещества. Лучше всего работает против повреждений, вызванных токсинами."
'лучше всего действует при интоксикации' ?

2023-12-07 21:17 UTC, KandreyKandrey commented on code/modules/virus2/effect.dm
> +		passive_message = "<span class='notice'>Ваша кожа покалывает, а свет звезд похоже исцеляет вас.</span>"
'а свет звёзд, похоже, исцеляет вас' ?

2023-12-07 21:29 UTC, KandreyKandrey commented on code/modules/virus2/effect.dm
> +	desc = "Вирус способен восстанавливать плоть хозяина в условиях недостаточного освещения, восстанавливая физические повреждения. Эффективен против механического урона ."
масло масляное мне кажется
я бы оставил только 'Вирус способен восстанавливать плоть хозяина в условиях недостаточного освещения'

если оставлять текущий вариант, то в конце пробел лишний

2023-12-07 21:29 UTC, KandreyKandrey commented on code/modules/virus2/effect.dm
> +	passive_message = "<span class='notice'>Вы чувствуете покалывание на коже, когда по ней проходит свет..</span>"
'когда на неё падает/попадает свет' ?
точка лишняя

2023-12-07 21:31 UTC, KandreyKandrey commented on code/modules/virus2/effect.dm
> +		to_chat(M, "<span class='notice'>Темнота обволакивает вас и лечит ваши раны.</span>")
'Темнота обволакивает ваши раны, залечивая их' ?

2023-12-07 21:31 UTC, KandreyKandrey commented on code/modules/virus2/effect.dm
> +	desc = "Вирус превращает жир в чрезвычайно огнеопасное соединение и повышает температуру тела, заставляя носителя самопроизвольно вспыхивать.."
точка лишняя

2023-12-07 21:32 UTC, KandreyKandrey commented on code/modules/virus2/effect.dm
> +		to_chat(mob, "<span class='userdanger'>Ваша кожа охвачено пламенем, вы словно попали в Ад!</span>")
'кожа охвачена'
', словно вы попали'

2023-12-07 21:36 UTC, KandreyKandrey commented on code/modules/virus2/effect.dm
> +	desc = "Вирус агрессивно атакует клетки организма, омертвевая ткани и органы."
мб 'омертвевая' заменить синонимом каким-то?

2023-12-07 21:37 UTC, KandreyKandrey commented on code/modules/virus2/effect.dm
> +	desc = "Вирус повреждает желудок хозяина, заставляя его вырабатывать большое количество кислот, что вызывает интоксикацию.."
точка лишняя

2023-12-07 21:39 UTC, KandreyKandrey commented on code/modules/virus2/effect.dm
> +		to_chat(mob, "<span class='userdanger'>[pick("Вы на мгновение забыли, как дышать..", "Кто я?", "Как какать?.")]</span>") //Ayanami Rei
1) вторая точка случайно или специально?

2023-12-07 21:39 UTC, KandreyKandrey commented on code/modules/virus2/effect.dm
> +					to_chat(H, "<span class='warning'>Вы чувствуете себя гигачадом!</span>")
мб без этого?

2023-12-07 21:40 UTC, KandreyKandrey commented on code/modules/virus2/effect.dm
> +		to_chat(mob, "<span class='userdanger'>[pick("Ох, моя голова...", "У вас раскалывается голова.", "Они повсюду! Бегите!", "Что-то сркывается в тенях...")]</span>")
3) 'скрывается'

2023-12-07 21:42 UTC, KandreyKandrey commented on code/modules/virus2/effect.dm
> +			to_chat(mob, "<span class='userdanger'>Ваши уши болят, закладывает и начинает идти кровь!</span>")
мб перефразировать? так получается, что 'ваши уши начинает идти кровь'

2023-12-07 21:43 UTC, KandreyKandrey commented on code/modules/virus2/effect.dm
> +			to_chat(mob, "<span class='userdanger'>У вас закладывает уши и начинает громко звенеть!</span>")
'Вы начинаете чувствовать громкий звон и заложенность в ушах' ?

2023-12-07 21:44 UTC, KandreyKandrey commented on code/modules/virus2/effect.dm
> +	desc = "Вирус повреждает мозг, из-за чего носитель не может ориентироваться в окружающем мире."
'ориентироваться в пространстве' ?

2023-12-07 21:44 UTC, KandreyKandrey commented on code/modules/virus2/effect.dm
> +		to_chat(mob, "<span class='notice'>Вам вдруг стало трудно различать право и лево..</span>")
точка лишняя

2023-12-07 21:44 UTC, KandreyKandrey commented on code/modules/virus2/effect.dm
> +	desc = "Вирус очищает кровь хозяина от токсинов и опасных химических веществ, игнорируя при этом полезные химические вещества.."
точка лишняя

2023-12-07 21:46 UTC, KandreyKandrey commented on code/modules/virus2/effect.dm
> +			to_chat(mob, "<span class='notice'>Вы чувствуете небольшой прилив сил..</span>")
точка лишняя

2023-12-07 21:47 UTC, KandreyKandrey commented on code/modules/virus2/effect.dm
> +			to_chat(mob, "<span class='warning'>Вы начинаете хуже слышать собственную речь..</span>")
точка лишняя

2023-12-07 21:48 UTC, KandreyKandrey commented on code/modules/virus2/effect.dm
> +		to_chat(mob, "<span class='userdanger'>[pick("Вы слишком уст...","Вам ОЧЕНЬ хочется спать.","Вам трудно держать глаза открытыми.","Вы валитес с ног.")]</span>")
4) мягкий знак случайно или специально пропущен?

2023-12-07 21:48 UTC, KandreyKandrey commented on code/modules/virus2/effect.dm
> +	desc = "Вирус вызывает воспаление сетчатки, что приводит к повреждению глаза и в конечном итоге к слепоте."
запятые не пропущены?

2023-12-07 21:49 UTC, KandreyKandrey commented on code/modules/virus2/effect.dm
> +	desc = "Вирус мутирует в метаболизме хозяина, делая его практически неспособным получать питание из пищи."
в оригинале вроде 'вирус изменяет метаболизм хозяина'

2023-12-07 21:50 UTC, KandreyKandrey commented on code/modules/virus2/effect.dm
> +				to_chat(H, "<span class='warning'>[pick("Начинают выпадать случайные волоски.", "Вы чувствуете как лысеете с каждой секундой.")]</span>")
2) запятая перед 'как' ?

2023-12-07 21:51 UTC, KandreyKandrey commented on code/modules/virus2/effect.dm
> +	desc = "Вирус вызывает воспаление внутри мозга, что приводит к постоянному слюнотечению."
'слюноотделению' ? (текущий вариант тоже правильный)

2023-12-07 21:53 UTC, KandreyKandrey commented on code/modules/virus2/effect.dm
> +	desc = "Вирус вызывает беспорядочные мышечные спазмы, вызывая постоянные подергивания."
мб одно из 'вызыв..' заменить на 'провоцир... ?

2023-12-07 21:53 UTC, KandreyKandrey commented on code/modules/virus2/effect.dm
> +			to_chat(mob, "<span class = 'notice'>[pick("Все ваше тело дергается.", "Ваши руки судорожно сжимаются.", "Ваши ноги судороги.")]</span>")
3) слово не пропущено?

2023-12-07 21:53 UTC, KandreyKandrey commented on code/modules/virus2/effect.dm
> +			to_chat(mob, "<span class = 'warning'>[pick("Дерганье невыносимо.", "Вы не можете перестать дергаться.", "Вы дёргаетесь как будто вас ударило током.")]</span>")
3) запятая не пропущена?

2023-12-07 21:54 UTC, KandreyKandrey commented on code/modules/virus2/effect.dm
> +				to_chat(H, "<span class = 'userdanger'>[pick("Голова как будто налита свинцом!", "Вы чувствуете будто раскаленный нож в своем мозгу.!", "Волна боли заполняет вашу голову!")]</span>")
запятые не пропущены?

2023-12-07 21:54 UTC, KandreyKandrey commented on code/modules/virus2/effect.dm
> +				to_chat(A, "<span class='notice'>Вы чувствуете, что ваши кровеносные сосуды периодически пульсируют..</span>")
точка лишняя

2023-12-08 12:54 UTC, Fenriros commented on code/modules/virus2/effect.dm
> +		to_chat(mob, "<span class='userdanger'>[pick("Ох, моя голова...", "У вас раскалывается голова.", "Они повсюду! Бегите!", "Что-то сркывается в тенях...")]</span>")
```suggestion
		to_chat(mob, "<span class='userdanger'>[pick("Ох, моя голова...", "У вас раскалывается голова.", "Они повсюду! Бегите!", "Что-то скрывается в тенях...")]</span>")
```

2023-12-08 12:54 UTC, Fenriros commented on code/modules/virus2/effect.dm
> +					to_chat(H, "<span class='warning'>Вы чувствуете себя гигачадом!</span>")
ну так то там "You feel manly " Вы чувствуете себя "Мужиком" или "Мужественным". А разве гигачад не мужественный?

2023-12-08 12:54 UTC, Fenriros commented on code/modules/virus2/effect.dm
> +	desc = "Вирус значительно увеличивает количество тестостерона, вызывая быстрый рост бороды."
```suggestion
	desc = "Вирус значительно ускоряет выработку тестостерона, вызывая быстрый рост бороды."
```

2023-12-08 12:54 UTC, Fenriros commented on code/modules/virus2/effect.dm
> +		to_chat(mob, "<span class='userdanger'>[pick("Вы на мгновение забыли, как дышать..", "Кто я?", "Как какать?.")]</span>") //Ayanami Rei
```suggestion
		to_chat(mob, "<span class='userdanger'>[pick("Вы на мгновение забыли, как дышать.", "Кто я?", "Как какать?.")]</span>") //Ayanami Rei
```

2023-12-08 12:54 UTC, Fenriros commented on code/modules/virus2/effect.dm
> +		to_chat(mob, "<span class='notice'>[pick("Мир кажется странным.", "Вы на секунду забыли как вас зовут.", "Вы вдруг забыли, куда шли..")]</span>")
```suggestion
		to_chat(mob, "<span class='notice'>[pick("Мир кажется странным.", "Вы на секунду забыли, как вас зовут.", "Вы вдруг забыли, куда шли.")]</span>")
```

2023-12-08 12:54 UTC, Fenriros commented on code/modules/virus2/effect.dm
> +	desc = "Вирус повреждает желудок хозяина, заставляя его вырабатывать большое количество кислот, что вызывает интоксикацию.."
```suggestion
	desc = "Вирус повреждает желудок хозяина, заставляя его вырабатывать большое количество кислот, что вызывает интоксикацию."
```

2023-12-08 12:54 UTC, Fenriros commented on code/modules/virus2/effect.dm
> +		to_chat(mob, "<span class='userdanger'>Ваша кожа охвачено пламенем, вы словно попали в Ад!</span>")
```suggestion
		to_chat(mob, "<span class='userdanger'>Ваша кожа охвачена пламенем, словно вы попали в Ад!</span>")
```

2023-12-08 12:54 UTC, Fenriros commented on code/modules/virus2/effect.dm
> +	desc = "Вирус реагирует на звездный свет, вырабатывая регенерирующие химические вещества. Лучше всего работает против повреждений, вызванных токсинами."
```suggestion
	desc = "Вирус реагирует на звездный свет, вырабатывая регенерирующие химические вещества. Лучше всего работает при интоксикации."
```

2023-12-08 12:54 UTC, Fenriros commented on code/modules/virus2/effect.dm
> +				to_chat(mob, "<span class='notice'>Вы поняли, что ваши конечности не такие крепкие как прежде..</span>")
```suggestion
				to_chat(mob, "<span class='notice'>Вы поняли, что ваши конечности не такие крепкие, как прежде..</span>")
```

2023-12-08 12:54 UTC, Fenriros commented on code/modules/virus2/effect.dm
> +			to_chat(mob, "<span class='notice'>[pick("Вы видете, что стали менее ловким.", "Вы двигаетесь более неуклюже, чем обычно.")]</span>")
```suggestion
			to_chat(mob, "<span class='notice'>[pick("Вы замечаете, что стали менее ловким.", "Вы двигаетесь более неуклюже, чем обычно.")]</span>")
```

2023-12-08 12:54 UTC, Fenriros commented on code/modules/virus2/effect.dm
> +	desc = "Вирус создает проблемы с выработкой соединительной ткани в организме, что делает кости очень хрупкими."
```suggestion
	desc = "Вирус вызывает проблемы с выработкой соединительной ткани в организме, что делает кости очень хрупкими."
```

2023-12-08 12:54 UTC, Fenriros commented on code/modules/virus2/effect.dm
> +			to_chat(mob, "<span class='notice'>[pick("Вы чувствуетет зуд по всему телу.", "Вы чувствуетет слабость.")]</span>")
```suggestion
			to_chat(mob, "<span class='notice'>[pick("Вы чувствуете зуд по всему телу.", "Вы чувствуетет слабость.")]</span>")
```

2023-12-08 12:54 UTC, Fenriros commented on code/modules/virus2/effect.dm
> +		to_chat(mob, "<span class='warning'>[pick("Вы чувствуете что что=то поменялось в вас.", "У вас болит голова.")]</span>")
```suggestion
		to_chat(mob, "<span class='warning'>[pick("Вы чувствуете, что в вас что-то поменялось.", "У вас болит голова.")]</span>")
```

2023-12-08 12:54 UTC, Fenriros commented on code/modules/virus2/effect.dm
> +		to_chat(mob, "<span class='notice'>[pick("Вы чувствуете себя совсем по другому.", "Вы чувствуетет зуд по всему телу.", "Вы чувствуете лёгкое головокружение.")]</span>")
```suggestion
		to_chat(mob, "<span class='notice'>[pick("Вы чувствуете себя совсем по-другому.", "Вы чувствуете зуд по всему телу.", "Вы чувствуете лёгкое головокружение.")]</span>")
```

2023-12-08 12:54 UTC, Fenriros commented on code/modules/virus2/effect.dm
> +	desc = "Вирус приcоединяется к ДНК Хозяина, вызывая вредные мутации до его удаленния."
```suggestion
	desc = "Вирус приcоединяется к ДНК носителя, вызывая вредные мутации до его удаленния."
```

2023-12-08 12:54 UTC, Fenriros commented on code/modules/virus2/effect.dm
> +					to_chat(A, "<span class='danger'>[pick("Вы реально хотитте бананов.", "Вы замечатете как начинатете деградировать.", "Вы становитесь ниже.", "Шерсть проступает на вашей коже.")]</span>")
```suggestion
					to_chat(A, "<span class='danger'>[pick("Вы реально хотите бананов.", "Вы замечаете как начинаете деградировать.", "Вы становитесь ниже.", "Шерсть проступает на вашей коже.")]</span>")
```

2023-12-08 12:54 UTC, Fenriros commented on code/modules/virus2/effect.dm
> +					h.say(pick("О,Банан?", "У тебя есть бананы?", "У-У-У-и-и","Уо Уо Уои ээи ээи иии ииии", "Иииир! Иииир!"))
Специально. Потому что он это говорит от лица куклы.

2023-12-08 12:54 UTC, Fenriros commented on code/modules/virus2/effect.dm
> +	desc = "Вирус меняет ДНК хозяина, первращая его в обезьяну."
```suggestion
	desc = "Вирус меняет ДНК носителя, превращая его в обезьяну."
```

2023-12-08 12:54 UTC, Fenriros commented on code/modules/virus2/effect.dm
> +			to_chat(mob, "<span class='warning'>У вас болит груль!</span>")
```suggestion
			to_chat(mob, "<span class='warning'>У вас болит грудь!</span>")
```

2023-12-08 12:54 UTC, Fenriros commented on code/modules/virus2/effect.dm
> +	desc = "Вирус производит нанитов в пищеварительной системе носителя, которые размножаются и питаются тканями организма, вызывая кровотечение с рвотой."
```suggestion
	desc = "Вирус производит в пищеварительной системе носителя нанитов, которые размножаются и питаются тканями организма, вызывая кровотечение с рвотой."
```

2023-12-08 12:54 UTC, Fenriros commented on code/modules/virus2/effect.dm
> +				to_chat(mob, "<span class='warning'>[pick("Вы чувствуете как происходят химические реакции в вашем теле.", "На вашей коже появляются пузырьки которые немедленно взрываются.", "Кровь проявляется н
```suggestion
				to_chat(mob, "<span class='warning'>[pick("Вы чувствуете как протекают химические реакции в вашем теле.", "На вашей коже появляются пузырьки, которые немедленно взрываются.", "Кровь проявляется на вашем теле. Что-то разрывает вас изнутри!", "Раны на теле становятся все серьезнее.", "Вы чувствуете взрывы внутри себя.")]</span>")
```

2023-12-08 12:54 UTC, Fenriros commented on code/modules/virus2/effect.dm
> +			to_chat(mob, "<span class='notice'>[pick("Вы почему-то злитесь.", "Ваша кожа шелушиться.", "Ваша кожа горит.", "То тут то там появляются маленькие ранки на вашей коже.")]</span>")
```suggestion
			to_chat(mob, "<span class='notice'>[pick("Вы почему-то злитесь.", "Ваша кожа шелушится.", "Ваша кожа горит.", "То тут, то там на вашей коже появляются маленькие ранки.")]</span>")
```

2023-12-08 12:54 UTC, Fenriros commented on code/modules/virus2/effect.dm
> +	desc = "Вирус генерирует сероводород в кровотоке, повреждая вены и артерии. В особых случаях, передозировка сероводородом может привести к взрыву, разнося носителя на кусочки."
```suggestion
	desc = "Вирус генерирует сероводород в кровотоке, повреждая вены и артерии. В особых случаях, передозировка может привести к взрыву, который разнесёт носителя на кусочки."
```

2023-12-08 12:54 UTC, Fenriros commented on code/modules/virus2/effect.dm
> +		to_chat(mob, "<span class='userdanger'>[pick("Вы чувствуете как ваши мышци слабеют.", "Ваша кожа отслаивается сама по себе.", "Вы как буд-то растворяетесь.")]</span>")
```suggestion
		to_chat(mob, "<span class='userdanger'>[pick("Вы чувствуете, как ваши мышци слабеют.", "Ваша кожа отслаивается сама по себе.", "Вы как будто растворяетесь.")]</span>")
```

2023-12-08 12:54 UTC, Fenriros commented on code/modules/virus2/effect.dm
> +		to_chat(mob, "<span class='warning'>[pick("Вы чувствуете как разваливаетесь на части.", "Ваша кожа стирается словно пыль.")]</span>")
```suggestion
		to_chat(mob, "<span class='warning'>[pick("Вы чувствуете, как разваливаетесь на части.", "Ваша кожа стирается, словно пыль.")]</span>")
```

2023-12-08 12:54 UTC, Fenriros commented on code/modules/virus2/effect.dm
> +	desc = "Вирус заставляет носителя впасть в кому подобную смерти после получения серьёзных повреждений, затем быстро восстанавливает их."
```suggestion
	desc = "Вирус заставляет носителя впасть в кому, подобную смерти, после получения серьёзных повреждений, а затем быстро восстанавливает их."
```

2023-12-08 13:28 UTC, KandreyKandrey commented on code/modules/virus2/effect.dm
> +					h.say(pick("О,Банан?", "У тебя есть бананы?", "У-У-У-и-и","Уо Уо Уои ээи ээи иии ииии", "Иииир! Иииир!"))
я про 'банан' с большой буквы
и пропущенный пробел после запятой

2023-12-08 13:31 UTC, KandreyKandrey commented on code/modules/virus2/effect.dm
> +					to_chat(H, "<span class='warning'>Вы чувствуете себя гигачадом!</span>")
так и оставь 'мужиком'

2023-12-08 13:31 UTC, KandreyKandrey commented on code/modules/virus2/effect.dm
> +					to_chat(H, "<span class='warning'>YВы чувствуете себя крутым.</span>")
буква лишняя

2023-12-08 13:32 UTC, KandreyKandrey commented on code/modules/virus2/effect.dm
> +			to_chat(mob, "<span class='userdanger'>У вас закладывает уши и начинает громко звенеть!</span>")
'ваши уши заложило, и появился громкий звон!'

2023-12-08 13:46 UTC, Fenriros commented on code/modules/virus2/effect.dm
> +					to_chat(H, "<span class='warning'>YВы чувствуете себя крутым.</span>")
```suggestion
					to_chat(H, "<span class='warning'>Вы чувствуете себя крутым.</span>")
```

2023-12-08 14:14 UTC, Fenriros commented on code/modules/virus2/effect.dm
> +					h.say(pick("О,Банан?", "У тебя есть бананы?", "У-У-У-и-и","Уо Уо Уои ээи ээи иии ииии", "Иииир! Иииир!"))
```suggestion
					h.say(pick("О, банан?", "У тебя есть бананы?", "У-У-У-и-и","Уо Уо Уои ээи ээи иии ииии", "Иииир! Иииир!"))
```

2023-12-08 20:33 UTC, Kiromaka requested changes

2023-12-08 20:33 UTC, Kiromaka commented on code/modules/virus2/effect.dm
> +				to_chat(H, "<span class = 'warning'>[pick("У вас голова раскалывается.", "Ваша голова непрерывно болит.", "У вас пульсирующая головная боль.")]</span>")
Сэр.... У вас голова раскалывается. 😄 
Поменяй немного порядок слов - Ваша голова раскалывается/ У вас раскалывается голова

2023-12-08 20:33 UTC, Kiromaka commented on code/modules/virus2/effect.dm
> +				to_chat(H, "<span class='warning'>[pick("Ваша кожа головы чешется.", "Ваша кожа шелушится.")]</span>")
Меняй...

2023-12-08 20:33 UTC, Kiromaka commented on code/modules/virus2/effect.dm
> +	desc = "Вирус вызывает воспаление внутри мозга, что приводит к постоянному слюнотечению."
Слюнотечение это отсебятина, лучше поменяй на слюноотделение.

2023-12-08 20:33 UTC, Kiromaka commented on code/modules/virus2/effect.dm
> +			to_chat(mob, "<span class='userdanger'>Голод делает вас слабым.</span>")
Голод ничего не делает.
- Вы ослабеваете от голода.

2023-12-08 20:33 UTC, Kiromaka commented on code/modules/virus2/effect.dm
> +		to_chat(mob, "<span class='warning'>В ваших глазах как будто песок!</span>")
Ех, звучит странно, можно было просто оставить сильное жжение

2023-12-08 20:33 UTC, Kiromaka commented on code/modules/virus2/effect.dm
> +		to_chat(mob, "<span class='userdanger'>[pick("Вы слишком уст...","Вам ОЧЕНЬ хочется спать.","Вам трудно держать глаза открытыми.","Вы валитесь с ног.")]</span>")
устали... или это такое авторское решение...............................

2023-12-08 20:33 UTC, Kiromaka commented on code/modules/virus2/effect.dm
> +			to_chat(mob, "<span class='userdanger'>[pick("ААААА!","ДОЛЖЕН ОРАТЬ", "Вы не можете замолчать.")]</span>")
"заткнуться", слишком мягко для шизика орущего - АМОГУС АМОГУС... ( кто это кодил 😢 )

2023-12-08 20:33 UTC, Kiromaka commented on code/modules/virus2/effect.dm
> +	desc = "Вирус изменяет метаболизм хозяина, делая его гораздо более эффективным, чем обычно, и синтезируя питательные вещества из обычно несъедобных источников."
поменяй местами, а то читать неприятно (skill issue on my part) 
```suggestion
	desc = "Вирус изменяет метаболизм хозяина, синтезируя питательные вещества из обычно несъедобных источников, делая его гораздо более эффективным, чем обычно."
```

2023-12-08 20:33 UTC, Kiromaka commented on code/modules/virus2/effect.dm
> +		to_chat(mob, "<span class='notice'>[pick("Вы вдруг забыли, где находится ваше право.", "Вы вдруг забыли, где находится ваше лево.")]</span>")
Это что, комментарий на текущие политическое состояние жителей страны Z ?

2023-12-08 20:33 UTC, Kiromaka commented on code/modules/virus2/effect.dm
> +					to_chat(H, "<span class='warning'>Вы чувствуете себя гигачадом!</span>")
bro wtf, меняй... у нас тут серьезная работа 🤓

2023-12-08 20:33 UTC, Kiromaka commented on code/modules/virus2/effect.dm
> +		to_chat(mob, "<span class='userdanger'>[pick("Вы на мгновение забыли, как дышать.", "Кто я?", "Как какать?.")]</span>") //Ayanami Rei
Как какать.... 
генний, но про такие дикие РОФЛС, надо спросить у ази и воласа

2023-12-08 20:33 UTC, Kiromaka commented on code/modules/virus2/effect.dm
> +	desc = "Вирус странным образом мутирует в мозге, наделяя носителя способностью общаться с другими людьми посредством своего разума."
Вирус не мутирует... ВИРУС (что делает ?) мутирует (что?) мозг..

2023-12-08 20:33 UTC, Kiromaka commented on code/modules/virus2/effect.dm
> +	desc = "Вирус мутирует в клетках кожи хозяина, увеличивая воздействие радиации."
Опять. не мутирует он блять

2023-12-08 20:33 UTC, Kiromaka commented on code/modules/virus2/effect.dm
> +	desc = "Вирус способен восстанавливать плоть хозяина в условиях недостаточного освещения, восстанавливая повреждения. Эффективен против механического урона."
тавтология

2023-12-08 20:33 UTC, Kiromaka commented on code/modules/virus2/effect.dm
> +	desc = "Вирус производит в пищеварительной системе носителя нанитов, которые размножаются и питаются тканями организма, вызывая кровотечение с рвотой."
наниты,

2023-12-08 21:15 UTC, Fenriros commented on code/modules/virus2/effect.dm
> +		to_chat(mob, "<span class='userdanger'>[pick("Вы слишком уст...","Вам ОЧЕНЬ хочется спать.","Вам трудно держать глаза открытыми.","Вы валитесь с ног.")]</span>")
авторское решение

2023-12-08 21:55 UTC, Kiromaka commented on code/modules/virus2/effect.dm
> +				to_chat(H, "<span class = 'warning'>[pick("У вас голова раскалывается.", "Ваша голова непрерывно болит.", "У вас пульсирующая головная боль.")]</span>")
Здесь это звучит как обращение, должно быть как констатация факта .

2023-12-09 19:15 UTC, Fenriros commented on code/modules/virus2/effect.dm
> +			to_chat(mob, "<span class='userdanger'>[pick("ААААА!","ДОЛЖЕН ОРАТЬ", "Вы не можете замолчать.")]</span>")
Может что-то типо " КАК ЖЕ ЭТО ПРЕКРАТИЬ?"

2023-12-09 19:17 UTC, Fenriros commented on code/modules/virus2/effect.dm
> +	desc = "Вирус способен восстанавливать плоть хозяина в условиях недостаточного освещения, восстанавливая повреждения. Эффективен против механического урона."
просто лечить

2023-12-09 19:19 UTC, Fenriros commented on code/modules/virus2/effect.dm
> +	desc = "Вирус мутирует в клетках кожи хозяина, увеличивая воздействие радиации."
предложи вариант
что-то по типу "...изменяет клетки.."

2023-12-10 08:35 UTC, Kiromaka commented on code/modules/virus2/effect.dm
> +	desc = "Вирус мутирует в клетках кожи хозяина, увеличивая воздействие радиации."
Подвергает мутации клетки кожи

2023-12-10 08:36 UTC, Kiromaka commented on code/modules/virus2/effect.dm
> +	desc = "Вирус странным образом мутирует в мозге, наделяя носителя способностью общаться с другими людьми посредством своего разума."
Подвергает мутации мозг

2023-12-10 19:05 UTC, Fenriros commented on code/modules/virus2/effect.dm
> +	desc = "Вирус вызывает воспаление внутри мозга, что приводит к постоянному слюнотечению."
```suggestion
	desc = "Вирус вызывает воспаление внутри мозга, что приводит к птиализму."
```

2023-12-10 19:05 UTC, Fenriros commented on code/modules/virus2/effect.dm
> +				to_chat(H, "<span class = 'warning'>[pick("У вас голова раскалывается.", "Ваша голова непрерывно болит.", "У вас пульсирующая головная боль.")]</span>")
```suggestion
				to_chat(H, "<span class = 'warning'>[pick("У васраскалывается голова.", "Ваша голова непрерывно болит.", "У вас пульсирующая головная боль.")]</span>")
```

2023-12-17 20:45 UTC, Pivo24 reviewed
много сомнительных постановок слов

2023-12-17 20:45 UTC, Pivo24 commented on code/modules/virus2/effect.dm
> +	desc = "Вирус быстро разрушает любые посторонние химические вещества в кровотоке."
Вариант: инородные химические вещества

2023-12-17 20:45 UTC, Pivo24 commented on code/modules/virus2/effect.dm
> +	desc = "Вирус ускоряет метаболизм носителя, заставляя химические процессы протекать в два раза быстрее, но повышает при этом голод."
"повышает голод" ощущается немного по видеоигровому

вариант - "ускоряет голодание", может быть?

2023-12-17 20:45 UTC, Pivo24 commented on code/modules/virus2/effect.dm
> +	to_chat(M, "<span class='notice'>Вы ощущаете необычное бульканье, как будто желудок работает быстрее обычного.</span>")
Окей вот тут такой вариант предлагаю, дословный перевод не особо помогает делу

"Ваш живот странно урчит, как будто бы ваш желудок работает быстрее обычного."

потому что в русском языке урчание живота бульканьем не зовут

2023-12-17 20:45 UTC, Pivo24 commented on code/modules/virus2/effect.dm
> +		to_chat(mob, "<span class='userdanger'>[pick("Вы чувствуете, как ваши мышци слабеют.", "Ваша кожа отслаивается сама по себе.", "Вы как будто растворяетесь.")]</span>")
мышцы*

2023-12-17 20:45 UTC, Pivo24 commented on code/modules/virus2/effect.dm
> +				to_chat(mob, "<span class='warning'>[pick("Вы чувствуете как протекают химические реакции в вашем теле.", "На вашей коже появляются пузырьки, которые немедленно взрываются.", "Кровь проявляется н
>You feel small explosions inside of you

Вариант: "Вы чувствуете, как внутри вас что-то слабо лопается/взрывается"

Мне лично нравится вариант с "лопается", потому что это стремнее представляется

2023-12-17 20:45 UTC, Pivo24 commented on code/modules/virus2/effect.dm
> +					h.say(pick("О, банан?", "У тебя есть бананы?", "У-У-У-и-и","Уо Уо Уои ээи ээи иии ииии", "Иииир! Иииир!"))
ииир ииир???

._.

Я не могу предложить альтернативы, но звукоподражательные обезьянки наверное не включают в себя таких слов

2023-12-17 20:45 UTC, Pivo24 commented on code/modules/virus2/effect.dm
> +	desc = "Вирус приcоединяется к ДНК носителя, вызывая вредные мутации до его удаленния."
до тех пор, пока его не удалят*

или ещё лучше,

до тех пор, пока его не вылечат* или типо такого

2023-12-17 20:45 UTC, Pivo24 commented on code/modules/virus2/effect.dm
> +	desc = "Вирус реагирует на звездный свет, вырабатывая регенерирующие химические вещества. Лучше всего работает при интоксикации."
лучше всего работает **от** интоксикации, может?

**при** можно не так понять, и вирусологи начнут себя травить, надеясь вылечить кровотечение :D

2023-12-17 20:45 UTC, Pivo24 commented on code/modules/virus2/effect.dm
> +	desc = "Вирус способен восстанавливать плоть хозяина в условиях недостаточного освещения, излечивая небольшие повреждения. Эффективен против механического урона."
против механических травм*

2023-12-17 20:45 UTC, Pivo24 commented on code/modules/virus2/effect.dm
> +	desc = "Вирус превращает жир в чрезвычайно огнеопасное соединение и повышает температуру тела, заставляя носителя самопроизвольно вспыхивать."
может, "вирус превращает жиры носителя"? это как-то более биологически звучит, чем "жир"

2023-12-17 20:45 UTC, Pivo24 commented on code/modules/virus2/effect.dm
> +			to_chat(mob, "<span class='notice'>[pick("Вы чувствуете странное бульканье в животе.", "Вы испытываете тошноту.")]</span>")
опять же, "ваш живот странно урчит" звучит куда приятнее слуху чем "странное бульканье в животе"

2023-12-17 20:45 UTC, Pivo24 commented on code/modules/virus2/effect.dm
> +			to_chat(mob, "<span class='warning'>[pick("У вас болит желудок.", "Вы чувствуете противную боль в горле.")]</span>")
живот вместо желудка, может? самое частое и распространённое употребление "у меня болит живот" звучит куда корректнее и живее чем "у меня болит желудок"

2023-12-17 20:45 UTC, Pivo24 commented on code/modules/virus2/effect.dm
> +			to_chat(mob, "<span class='warning'>[pick("У вас очень сильно болит желудок.", "Ваша кожа кажется более бледной.", "Вы чувствуете себя растерянным.", "Ваше дыхание горячее и нерегулярное.")]</span
same как и то что выше

2023-12-17 20:45 UTC, Pivo24 commented on code/modules/virus2/effect.dm
> +			to_chat(mob, "<span class='notice'>[pick("Вам что-то послышалось.", "В голове появляются посторонние мысли.", "Мир кажется странным.")]</span>")
Something is not right = Что-то не так

Мир кажется странным это самое романтичное описание замешательства, лишающее паранойи

2023-12-17 20:45 UTC, Pivo24 commented on code/modules/virus2/effect.dm
> +		to_chat(mob, "<span class='notice'>[pick("Мир кажется странным.", "Вы на секунду забыли, как вас зовут.", "Вы вдруг забыли, куда шли.")]</span>")
same, "что-то не так"

2023-12-17 20:45 UTC, Pivo24 commented on code/modules/virus2/effect.dm
> +				to_chat(H, "<span class='warning'>[pick("Ваша кожа головы чешется.", "Ваша кожа шелушится.")]</span>")
Почему "кожа головы" а не "голова" так никто не говорит

2023-12-17 20:45 UTC, Pivo24 commented on code/modules/virus2/effect.dm
> +		to_chat(mob, "<span class = 'notice'>[pick("Вы проглатываете избыток слизи.", "Вы слегка покашливаете.")]</span>")
вы проглатываете мокроту, а не избыток слизи

mucus тут это мокрота

2023-12-17 20:45 UTC, Pivo24 commented on code/modules/virus2/effect.dm
> +			to_chat(mob, "<span class = 'notice'>[pick("Невыносимое желание чихнуть.")]</span>")
is unbearable > невыносимо

Желание чихнуть невыносимо

2023-12-18 14:11 UTC, Fenriros commented on code/modules/virus2/effect.dm
> +	desc = "Вирус приcоединяется к ДНК носителя, вызывая вредные мутации до его удаленния."
Было длттех пор пока не удалят.

отклонено

2023-12-18 15:04 UTC, Fenriros commented on code/modules/virus2/effect.dm
> +			to_chat(mob, "<span class='notice'>[pick("Вам что-то послышалось.", "В голове появляются посторонние мысли.", "Мир кажется странным.")]</span>")
"Что-то не так" не описывает ситуацию

2023-12-18 19:20 UTC, Fenriros commented on code/modules/virus2/effect.dm
> +	desc = "Вирус ускоряет метаболизм носителя, заставляя химические процессы протекать в два раза быстрее, но повышает при этом голод."
Я посмотрел, так говорят

2023-12-18 19:27 UTC, Fenriros commented on code/modules/virus2/effect.dm
> +	desc = "Вирус ускоряет метаболизм носителя, заставляя химические процессы протекать в два раза быстрее, но повышает при этом голод."
```suggestion
	desc = "Вирус ускоряет метаболизм носителя, заставляя химические процессы протекать в два раза быстрее, но  при этом повышает аппетит."
```

2023-12-18 19:58 UTC, Fenriros commented on code/modules/virus2/effect.dm
> +	to_chat(M, "<span class='notice'>Вы ощущаете необычное бульканье, как будто желудок работает быстрее обычного.</span>")
```suggestion
	to_chat(M, "<span class='notice'>Ваш живот странно урчит, как будто бы ваш желудок работает быстрее обычного.</span>")
```

2023-12-18 19:58 UTC, Fenriros commented on code/modules/virus2/effect.dm
> +		to_chat(mob, "<span class='userdanger'>[pick("Вы чувствуете, как ваши мышци слабеют.", "Ваша кожа отслаивается сама по себе.", "Вы как будто растворяетесь.")]</span>")
```suggestion
		to_chat(mob, "<span class='userdanger'>[pick("Вы чувствуете, как ваши мышцы слабеют.", "Ваша кожа отслаивается сама по себе.", "Вы как будто растворяетесь.")]</span>")
```

2023-12-18 19:58 UTC, Fenriros commented on code/modules/virus2/effect.dm
> +				to_chat(mob, "<span class='warning'>[pick("Вы чувствуете как протекают химические реакции в вашем теле.", "На вашей коже появляются пузырьки, которые немедленно взрываются.", "Кровь проявляется н
```suggestion
				to_chat(mob, "<span class='warning'>[pick("Вы чувствуете как протекают химические реакции в вашем теле.", "На вашей коже появляются пузырьки, которые немедленно взрываются.", "Кровь проявляется на вашем теле. Что-то разрывает вас изнутри!", "Раны на теле становятся все серьезнее.", "Вы чувствуете, как внутри вас что-то слабо взрывается.")]</span>")
```

2023-12-18 19:58 UTC, Fenriros commented on code/modules/virus2/effect.dm
> +	desc = "Вирус реагирует на звездный свет, вырабатывая регенерирующие химические вещества. Лучше всего работает при интоксикации."
> лучше всего работает **от** интоксикации, может?
> 
> **при** можно не так понять, и вирусологи начнут себя травить, надеясь вылечить кровотечение :D

имеется ввиду когда у тебя токс урон, он быстрее всех остальных видов спадает

2023-12-18 19:58 UTC, Fenriros commented on code/modules/virus2/effect.dm
> +	desc = "Вирус способен восстанавливать плоть хозяина в условиях недостаточного освещения, излечивая небольшие повреждения. Эффективен против механического урона."
```suggestion
	desc = "Вирус способен восстанавливать плоть хозяина в условиях недостаточного освещения, излечивая небольшие повреждения. Эффективен против механического травм."
```

2023-12-18 19:58 UTC, Fenriros commented on code/modules/virus2/effect.dm
> +	desc = "Вирус превращает жир в чрезвычайно огнеопасное соединение и повышает температуру тела, заставляя носителя самопроизвольно вспыхивать."
```suggestion
	desc = "Вирус превращает жиры носителя в чрезвычайно огнеопасное соединение и повышает температуру тела, заставляя его самопроизвольно вспыхивать."
```

2023-12-18 19:58 UTC, Fenriros commented on code/modules/virus2/effect.dm
> +			to_chat(mob, "<span class='warning'>[pick("У вас болит желудок.", "Вы чувствуете противную боль в горле.")]</span>")
```suggestion
			to_chat(mob, "<span class='warning'>[pick("У вас болит живот.", "Вы чувствуете противную боль в горле.")]</span>")
```

2023-12-18 19:58 UTC, Fenriros commented on code/modules/virus2/effect.dm
> +			to_chat(mob, "<span class='warning'>[pick("У вас очень сильно болит желудок.", "Ваша кожа кажется более бледной.", "Вы чувствуете себя растерянным.", "Ваше дыхание горячее и нерегулярное.")]</span
```suggestion
			to_chat(mob, "<span class='warning'>[pick("У вас очень сильно болит живот.", "Ваша кожа кажется более бледной.", "Вы чувствуете себя растерянным.", "Ваше дыхание горячее и нерегулярное.")]</span>")
```

2023-12-18 20:03 UTC, Fenriros commented on code/modules/virus2/effect.dm
> +			to_chat(mob, "<span class = 'notice'>[pick("Невыносимое желание чихнуть.")]</span>")
```suggestion
			to_chat(mob, "<span class = 'notice'>[pick("Желание чихнуть невыносимо.")]</span>")
```

2023-12-18 20:03 UTC, Fenriros commented on code/modules/virus2/effect.dm
> +		to_chat(mob, "<span class = 'notice'>[pick("Вы проглатываете избыток слизи.", "Вы слегка покашливаете.")]</span>")
```suggestion
		to_chat(mob, "<span class = 'notice'>[pick("Вы проглатываете избыток мокроты.", "Вы слегка покашливаете.")]</span>")
```

2023-12-18 20:03 UTC, Fenriros commented on code/modules/virus2/effect.dm
> +				to_chat(H, "<span class='warning'>[pick("Ваша кожа головы чешется.", "Ваша кожа шелушится.")]</span>")
```suggestion
				to_chat(H, "<span class='warning'>[pick("Ваш скальп чешется.", "Ваша кожа шелушится.")]</span>")
```

2023-12-18 21:24 UTC, Kiromaka approved these changes
Вроде нормально, комить.

2023-12-18 21:28 UTC, Fenriros commented on code/modules/virus2/effect.dm
> +			to_chat(mob, "<span class='notice'>[pick("Вы чувствуете странное бульканье в животе.", "Вы испытываете тошноту.")]</span>")
```suggestion
			to_chat(mob, "<span class='notice'>[pick("У вас болит живот.", "Вы испытываете тошноту.")]</span>")
```

2023-12-18 21:30 UTC, Fenriros commented on code/modules/virus2/effect.dm
> +				to_chat(A, "<span class='notice'>Вы чувствуете, что ваши кровеносные сосуды периодически пульсируют..</span>")
```suggestion
				to_chat(A, "<span class='notice'>Вы чувствуете, что ваши кровеносные сосуды периодически пульсируют.</span>")
```

2023-12-21 19:41 UTC, Fenriros commented on code/modules/virus2/effect.dm
> +		to_chat(mob, "<span class='warning'>В ваших глазах как будто песок!</span>")
КОгда в глазах песок, у тебя глаза слезяттся и они горят.

2023-12-21 19:42 UTC, Fenriros commented on code/modules/virus2/effect.dm
> +				to_chat(H, "<span class = 'userdanger'>[pick("Голова как будто налита свинцом!", "Вы чувствуете, будто раскаленный нож вошёл в ваш мозг!", "Волна боли заполняет вашу голову!")]</span>")
Не знаю, для третьей стадии простое " вы чувствуете боль" не уместно, по сравнению с другими описаниями

2023-12-25 13:22 UTC, Fenriros commented on code/modules/virus2/effect.dm
> +		to_chat(mob, "<span class='warning'><i>Ваши глаза как будто горят!</i></span>")
Если перевести "ваши глаза горят" то можно не так понять. Может. в таком случае, горят в кавычки убрать?

2023-12-28 05:29 UTC, Pivo24 reviewed
Ну в целом меньше вопросов

2023-12-28 05:29 UTC, Pivo24 commented on code/modules/virus2/effect.dm
> +				to_chat(H, "<span class='warning'>[pick("Ваш скальп чешется.", "Ваша кожа шелушится.")]</span>")
Скальп? Вместо головы?

Это ближе к истине, но "ваша голова чешется" буквально идеал в таком переводе - не абсолютная дословность, всё ещё универсально понимаемый смысл

2023-12-30 21:57 UTC, Fenriros commented on code/modules/virus2/effect.dm
> +				to_chat(H, "<span class='warning'>[pick("Ваш скальп чешется.", "Ваша кожа шелушится.")]</span>")
> Скальп? Вместо головы?
> 
> Это ближе к истине, но "ваша голова чешется" буквально идеал в таком переводе - не абсолютная дословность, всё ещё универсально понимаемый смысл

Скальп это именно кожи головы. Можно просто написать как ты сказал и не парится, всё равно всем пофиг

2023-12-30 22:07 UTC, Fenriros commented
Всё как с ИИ, ждём следующего года для мержа

2024-01-01 18:40 UTC, Chip11-n reviewed
Я ещё чуть позже гляну. Большинство моих комментов - придирки, но с другой стороны ещё есть что зашлифовать.

2024-01-01 18:40 UTC, Chip11-n commented on code/modules/virus2/effect.dm
> +	desc = "Вирус заставляет носителя впасть в кому, подобную смерти, после получения серьёзных повреждений, а затем быстро восстанавливает их."
Сложное предложение, но идей лучше нет.

2024-01-01 18:40 UTC, Chip11-n commented on code/modules/virus2/effect.dm
> +	passive_message = "<span class='notice'>Боль от ран заставляет вас чувствовать себя сонным...</span>"
**Вас** чувствовать **себя**.

2024-01-01 18:40 UTC, Chip11-n commented on code/modules/virus2/effect.dm
> +	to_chat(M, "<span class='notice'>Ваш живот странно урчит, как будто бы ваш желудок работает быстрее обычного.</span>")
Тавтология ваш.

2024-01-01 18:40 UTC, Chip11-n commented on code/modules/virus2/effect.dm
> +		to_chat(mob, "<span class='userdanger'>[pick("Вы чувствуете, как ваши мышцы слабеют.", "Ваша кожа отслаивается сама по себе.", "Вы как будто растворяетесь.")]</span>")
"Вы чувствуете", как и выше, меня напрягает. Как просто для восприятия последнее предложение, и насколько сложнее первое. Но может это уже мои тараканы.

2024-01-01 18:40 UTC, Chip11-n commented on code/modules/virus2/effect.dm
> +					to_chat(H, "<span class='warning'>Вы больше не чувствуете какую-то конечность...</span>")
Какую-то? Понимаю, что нужен перевод, но оставить без внимания не могу.

2024-01-01 18:40 UTC, Chip11-n commented on code/modules/virus2/effect.dm
> +		passive_message = "<span class='notice'>Ваша кожа покалывает. А свет звёзд, похоже, исцеляет вас.</span>"
Предложение красивое, конечно, но учитывай что это "похоже, исцеляюсь" будет по кд и сомнения в таком случае довольно странно ощущать.

2024-01-01 18:40 UTC, Chip11-n commented on code/modules/virus2/effect.dm
> +				to_chat(mob, "<span class='notice'>Вы поняли, что ваши конечности не такие крепкие, как прежде..</span>")
Тоже самое. Что делать? Не знаю.

2024-01-01 18:40 UTC, Chip11-n commented on code/modules/virus2/effect.dm
> +	desc = "Вирус реагирует на звездный свет, вырабатывая регенерирующие химические вещества. Лучше всего работает при интоксикации."
Согласен с Пивом. Может ДЛЯ детоксикации?

2024-01-01 18:40 UTC, Chip11-n commented on code/modules/virus2/effect.dm
> +		to_chat(mob, "<span class='notice'>Вы чувствуете себя умнее.</span>")
Вы-себя. Может "Вы стали умнее"?

2024-01-01 18:40 UTC, Chip11-n commented on code/modules/virus2/effect.dm
> +			to_chat(A, "<span class='warning'>[pick("Ваша кожа шелушится.", "У вас жар.")]</span>")
Тогда добавь третий вариант с головной болью, наверное.

2024-01-01 18:40 UTC, Chip11-n commented on code/modules/virus2/effect.dm
> +	desc = "Вирус укрепляет связи между нейронами, сокращая продолжительность любых воздействий на разум."
Что такое "воздействие на разум"?

2024-01-01 18:40 UTC, Chip11-n commented on code/modules/virus2/effect.dm
> +	desc = "Вирус агрессивно атакует клетки организма, подвергая некрозу ткани и органы."
Агрессивно? Активно? Просто как альтернатива

2024-01-01 18:40 UTC, Chip11-n commented on code/modules/virus2/effect.dm
> +		to_chat(mob, "<span class='userdanger'>[pick("Вы на мгновение забыли, как дышать.", "Кто я?", "Как какать?.")]</span>") //Ayanami Rei
Вопрос хороший...

2024-01-03 17:17 UTC, Fenriros commented on code/modules/virus2/effect.dm
> +	desc = "Вирус укрепляет связи между нейронами, сокращая продолжительность любых воздействий на разум."
> Что такое "воздействие на разум"?

Это когда что-либо или кто-либо воздействуетна тво разум

2024-01-03 17:18 UTC, Fenriros commented on code/modules/virus2/effect.dm
> +					to_chat(H, "<span class='warning'>Вы больше не чувствуете какую-то конечность...</span>")
> Какую-то? Понимаю, что нужен перевод, но оставить без внимания не могу.

помоги решить

2024-01-03 17:40 UTC, Kiromaka commented on code/modules/virus2/effect.dm
> +					to_chat(H, "<span class='warning'>Вы больше не чувствуете какую-то конечность...</span>")
а в чем трабл, [CASE(BP,  GENETIVE_CASE)]

2024-01-03 17:44 UTC, Kiromaka requested changes
заменяй BP.NAME не на (какая-то) а на [CASE(BP, падеж)] etc.

2024-01-05 17:51 UTC, Fenriros commented on code/modules/virus2/effect.dm
> +	desc = "Вирус агрессивно атакует клетки организма, подвергая некрозу ткани и органы."
Или
```suggestion
	desc = "Вирус агрессивно атакует клетки организма, полностью разрушая ткани и органы."
```

2024-01-17 07:04 UTC, volas commented on code/modules/virus2/effect.dm
> +	passive_message = "<span class='notice'>Боль от ран заставляет вас чувствовать себя сонным...</span>"
БОЛИ ОТ РАН, ПЕРЕВОДЧИКИ БЛИН

2024-01-17 07:07 UTC, volas requested changes
я бегло пробежался глазами, тут всё плохо, очередной пр фенрироса который надо самому переписывать предложение за предложением...

я не знаю, будете ли вы это вытягивать, удачи если так, но было бы лучше займись этим кто-то другой.

2024-01-17 12:48 UTC, Kiromaka commented
Я не буду больше это открывать, трудный ты себе ПР выбрал випо, начинать надо было с простого. 
Azi - check, и можно будет мерджить

2024-01-17 16:01 UTC, Kiromaka commented on code/modules/virus2/effect.dm
> +				to_chat(H, "<span class='warning'>[pick("Ваш скальп чешется.", "Ваша кожа шелушится.")]</span>")
"ваш", халтурим ази

2024-01-17 16:02 UTC, volas commented on code/modules/virus2/effect.dm
> +				to_chat(H, "<span class='warning'>[pick("Ваш скальп чешется.", "Ваша кожа шелушится.")]</span>")
голова чешется

2024-01-17 16:12 UTC, Kiromaka commented on code/modules/virus2/effect.dm
> +	desc = "Вирус приcоединяется к ДНК носителя, вызывая вредные мутации до его удаленния." //kirolt
а
я понял

2024-01-17 16:15 UTC, Kiromaka commented on code/modules/virus2/effect.dm
> +			to_chat(M, "<span class='notice'>Вы чувствуете небольшой жар, ваша кровь очищается.</span>") //kirolt
```suggestion
			to_chat(M, "<span class='notice'>Вы чувствуете небольшой жар, ваша кровь очищается.</span>")
```

2024-01-17 16:17 UTC, Kiromaka commented on code/modules/virus2/effect.dm
> +	desc = "Вирус приcоединяется к ДНК носителя, вызывая вредные мутации до его удаленния." //kirolt
```suggestion
	desc = "Вирус приcоединяется к ДНК носителя, вызывая вредоносные мутации до его удаления."
```

2024-01-24 11:39 UTC, Kiromaka commented
Уберите dnm, думаю стоит кинуть на тест мердж.

2024-01-29 03:25 UTC, volas commented on code/modules/virus2/effect.dm
> +	desc = "Вирус быстро расщепляет инородные химические вещества, попавшие в кровь."
```suggestion
	desc = "Вирус быстро расщепляет инородные химические вещества в крови."
```

2024-01-29 03:25 UTC, volas commented on code/modules/virus2/effect.dm
> +	passive_message = "<span class='notice'>От боли в ранах вас клонит в сон...</span>"
всё еще в ранах


я даже не буду листать дальше, это никуда не годиться, сжечь и переделать по новой будет проще.

2024-01-29 03:28 UTC, volas commented on code/modules/virus2/effect.dm
> +	to_chat(M, "<span class='notice'>Вы чувствуете странное бульканье в желудке, как будто он работает гораздо быстрее, чем обычно.</span>")
в желудке...

гугл транслейт и то лучше будет

2024-01-29 03:28 UTC, volas commented
пусть кто-то другой займется, фенрироса больше не пускайте к переводам

2024-01-29 03:28 UTC, closed without merging