Перевод шаттлов, их структур и оповещений
TauCetiStation/TauCetiClassic pull request #12624
Opened 2023-12-18 00:11 UTC by AzzyDreemurr13

## Описание изменений
Теперь все консоли управления шаттлами и их оповещения на русском языке. Также для шаттла прибытия, было починено оповещение об отбытие со станции.
Resolves https://github.com/TauCetiStation-TranslationDepartment/TauCetiClassic/issues/15

### Статус перевода шаттлов:
(Добавлено для своего удобства, ибо начал теряться, что я доделал, что нет)
- [x] ~~Перевод шаттла отбытия - 100%~~
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/74739991/7e283990-4997-4e8a-a7c9-5a3a17ae5f0c)
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/74739991/e3e4841e-c4b3-40a3-afb6-552779c1245c)
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/74739991/143894c7-4f28-4c23-9938-575ade132f43)
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/74739991/8f6a830c-b6db-4240-8c60-30de1598ae98)

- [x] ~~Перевод шаттла прибытия  - 100%~~
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/74739991/6d26d6b1-0ba4-40cb-a2c6-f734453ed7c0)
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/74739991/0e7daff0-e2e3-4a0d-8ca0-d8df3dce36e5)
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/74739991/2bb05296-8640-4edb-9b46-65138a071e4f)
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/74739991/7558b1e2-c3e5-45b8-b779-fc4d5ecb26d2)

- [x] ~~Перевод шаттла астероида - 100%~~
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/74739991/bbffbd89-6c8f-46a4-93ee-fca3aa869e64)
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/74739991/f15e1e52-3169-4301-99ba-02937d434de3)
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/74739991/ed5fac11-e433-4c89-b523-d281b3004b8c)
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/74739991/8614497b-9330-44e7-89f8-17e8e475cbf9)

- [x] ~~Перевод шаттла Синдиката - 100%~~
(Облечаем понимание для всех куда летит ваш корабль, если английский не знаем)
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/74739991/bad2b24f-7a99-4fdf-8872-4fd7daed5fcb)
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/74739991/7034a40f-ff5d-44bb-8500-505bcb5283c4)
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/74739991/3d829f47-13c7-4ffb-8081-3f5dfe9252b4)

- [x] ~~Перевод шаттла Велосити - 100%~~
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/74739991/87271c90-bb81-4b5e-a45c-7fc7bd05e770)
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/74739991/0d7acbdb-7f3d-48cd-90af-c3e59e6f43ec)
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/74739991/3f4b0b48-b3d8-446a-881b-c79c63ab7928)
- [x] ~~Перевод шаттла Элитного отряда синдиката - 100%~~
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/74739991/9aef0c14-4f84-4837-9636-0c49b99603dc)
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/74739991/8a30b3b3-e523-4ee8-846e-7b224decbcc7)
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/74739991/ac3cc8d1-4363-48be-a946-5acf8de84481)
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/74739991/572ca469-7732-4b63-989d-58f326240584)

- [x] ~~Перевод шаттла ОБР - 100%~~
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/74739991/97f76f42-ad12-4a3c-8806-afcb690769e4)
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/74739991/1e870d54-d032-43e1-b8e6-e6623e8b2429)
(Радио только на слое цк, на станции не будет видно. Но как говориться, мелочь, а приятно)
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/74739991/4f08582c-999e-4ec2-a938-b40f5b80fa7a)

- ~~[x] Корректировка Перевод шаттла Воксов - 100%~~
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/74739991/db6d4d21-2d28-4549-af1c-4ae9fe7e666a)
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/74739991/1ece1870-0cf9-48ca-8b3c-7d0196563f1b)
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/74739991/b819585c-e0a8-4e35-a600-8cae3084e474)
А также консоль маскировочного поля заговорило на русском языке
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/74739991/55565748-b850-4fcc-aa1f-a1a7ba81b6f4)

## Почему и что этот ПР улучшит
Меньше английского текста в станционном радио и больше переводов + меньше текста на английском языке на велосити.
## Авторство
Я, и всем кто помогал находить ошибки в этом огромном ПРе. 
## Чеинжлог
🆑 Azzy.Dreemurr
- ru: Перевод управления консолей шаттлов
- ru: Перевод окружения шаттла 
- ru: Перевод оповещения о прибывших шаттлах на русский язык
- ru: NTS Velosity официально получил перевод как НТС Велосити. Для шаттлов Велосити Док 42.
- spellcheck: Корректировка перевода Шаттла воксов
- bugfix: Починка оповещения трансферного шаттла об отбытие со станции

2023-12-18 00:11 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2023-12-18 07:38 UTC, Pivo24 reviewed
Немного очепяток, беда с падежом и немного вопросов

2023-12-18 07:38 UTC, Pivo24 commented on code/game/machinery/computer/arrival_shuttle.dm
> +	cases = list("консоль трансферного шаттла", "консоли трансферного шаттла", "консоле трансферного шаттла", "консоль трансферного шаттла", "консолью трансферного шаттла", "консоле трансферного шаттла"
Почему не шаттл прибытия?

2023-12-18 07:38 UTC, Pivo24 commented on code/game/machinery/computer/specops_shuttle.dm
> +				message = "ТРЕВОГА: [rounded_time_left] секунд осталось"
Может переставить слова в ОСТАЛОСЬ x СЕКУНД?

2023-12-18 07:38 UTC, Pivo24 commented on code/game/machinery/computer/specops_shuttle.dm
> +		to_chat(usr, "<span class='notice'>Шаттл специального назначения прибудет на Центральное командование черех [(SPECOPS_MOVETIME / 10)] секунд.</span>")
Тут косячок очепятка, через*

2023-12-18 07:38 UTC, Pivo24 commented on code/game/machinery/computer/specops_shuttle.dm
> +		to_chat(usr, "<span class='notice'>Шаттл специального назначения прибудет на [station_name] в [(SPECOPS_MOVETIME/10)] секунд.</span>")
В 3 секунд? В 24 секунд?

Немного странно  построено

2023-12-18 07:38 UTC, Pivo24 commented on code/modules/locations/shuttles/closet.dm
> +	desc = "Это настенное шкаф для хранения предметов первой помощи."
Настенный* шкаф

2023-12-18 11:10 UTC, Kiromaka commented on code/modules/locations/shuttles/closet.dm
> +	desc = "Это настенный шкаф для хранения аварийных предметов с дыхательными масками и баллонами с кислородом."
"аварийных предметов" странновато звучит, но это не серьезно.

2023-12-18 11:10 UTC, Kiromaka commented on code/modules/locations/shuttles/closet.dm
> +	desc = "Это настенное шкаф для хранения предметов первой помощи."
+

2023-12-18 11:10 UTC, Kiromaka commented on code/modules/locations/shuttles/closet.dm
> +	desc = "Похоже, вы можете попасть в эту небольшую вентиляционную шахту двигателя"
"Можете залезть" будет звучать получше.

2023-12-18 13:41 UTC, maleyvich commented on code/game/machinery/computer/arrival_shuttle.dm
> +	cases = list("консоль трансферного шаттла", "консоли трансферного шаттла", "консоле трансферного шаттла", "консоль трансферного шаттла", "консолью трансферного шаттла", "консоле трансферного шаттла"
слово консоль склонять как "консоле" категорически неправильно

2023-12-19 10:40 UTC, daedrowe commented on code/modules/locations/shuttles/bench.dm
> +	desc = "Вы сидите на этом. Либо по своей воле, либо по принуждению."
либо добровольно, либо насильно?

2023-12-19 10:40 UTC, daedrowe commented on code/modules/locations/shuttles/officer_shuttle.dm
> +		<a href='?src=\ref[src];velocity=1'>ТСК Велосити</a> |
ТСК? NTS Velocity - NanoTrasen Station Velocity, Станция НаноТрейзен Велосити, хотя сейчас не понятно, то Станция НаноТрейзен, то Станция Карго Индастрис

2023-12-20 15:48 UTC, LudwigVonChesterfield commented on code/modules/locations/shuttles/officer_shuttle.dm
> +		<a href='?src=\ref[src];velocity=1'>ТСК Велосити</a> |
НТС (Нейтральная Транзитная Станция), совпадение с NTS (NanoTrasen Transport Station) случайно.
```suggestion
		<a href='?src=\ref[src];velocity=1'>НТС Велосити</a> |
```

2023-12-21 17:24 UTC, volas commented on code/game/machinery/computer/specops_shuttle.dm
> +					message = "ТРЕВОГА: Взлёт"
выше отстыковка, тут можно тоже отстыковку написать (мы не всегда на планете). Но может еще стоит как-то переформулировать, а то одним словом как-то не очень ёмко

2023-12-21 17:25 UTC, volas commented on code/game/machinery/computer/specops_shuttle.dm
> +	to_chat(user, "<span class='notice'>Электронные системы в этой консоли слишком продвинуты для вашей примитивной хакерской периферии.</span>")
```suggestion
	to_chat(user, "<span class='notice'>Электронные системы в этой консоли слишком продвинуты для вашей примитивной хакерской аппаратуры.</span>")
```

2023-12-21 17:29 UTC, volas commented on code/game/machinery/computer/syndicate_specops_shuttle.dm
> +						message = "ТРЕВОГА: Взлёт"
```suggestion
						message = "ТРЕВОГА: Шаттл начинает отстыковку"
```

2024-01-17 07:20 UTC, volas commented on code/game/machinery/computer/arrival_shuttle.dm
> +		radio.autosay(department_note, "Система оповещения")
> Также для шаттла прибытия, было починено оповещение об отбытие со станции.

Мне кажется, это не было багом, оповещение об отбытии будет просто спамом и оно никак не влияет на игру. Прибытие хоть подразумевает, что кто-то прилетел.

2024-01-17 07:26 UTC, volas commented on code/game/machinery/computer/arrival_shuttle.dm
> +		radio.autosay(department_note, "Система оповещения")
да, пусть пока побудет

2024-01-17 07:27 UTC, volas commented on code/game/machinery/computer/arrival_shuttle.dm
> +	var/dat = "<center><div class='Section'>Местоположение: <b>[curr_location]</b><br>Готовность к полёту[!arrival_shuttle_ready_move() ? " через [max(round((lastMove + ARRIVAL_SHUTTLE_COOLDOWN - world.
и ниже так же поправить

2024-01-17 07:31 UTC, volas commented on code/modules/locations/shuttles/object_wall.dm
> +	desc = "Стена шаттла покрыта граффити."
```suggestion
	desc = "Стены шаттла, покрытые граффити."
```

минорный момет - мы сообщаем юзеру о стене, а не о графити

2024-01-17 07:32 UTC, volas commented on code/modules/locations/shuttles/shuttle_doors.dm
> +	cases = list("дверь", "двери", "двери", "дверь", "дверью", "двери")
в таких местах можно просто cases и name родителю прописать, а потомки унаследуют

2024-01-17 07:33 UTC, volas commented on code/modules/locations/shuttles/shuttle_doors.dm
> +	cases = list("дверь", "двери", "двери", "дверь", "дверью", "двери")
относится и к полам шаттла выше

2024-01-18 17:46 UTC, Kiromaka requested changes

2024-01-18 17:46 UTC, Kiromaka commented on code/game/machinery/computer/syndicate_shuttle.dm
> +		 	еще несколько минут, чтобы они успели приготовиться.</span>")
А че никто не написал, откуда "несколько" минут, когда там их пишет ?

2024-01-18 17:47 UTC, Kiromaka commented
И где падежи  таблички g250

2024-01-18 17:49 UTC, Kiromaka commented on code/game/machinery/computer/syndicate_shuttle.dm
> +		 	еще несколько минут, чтобы они успели приготовиться.</span>")
20 more mintes, еще 20 минут etc

2024-01-18 17:50 UTC, Kiromaka commented
И ЭЛИТНЫЙ СИНДИКАТ, стоит заменить на - элитный отряд синдиката

2024-01-19 18:00 UTC, KandreyKandrey commented on code/game/machinery/computer/specops_shuttle.dm
> +		to_chat(usr, "<span class='notice'>Шаттл специального назначения прибудет на [station_name_ru] в [(SPECOPS_MOVETIME/10)] секунд.</span>")
```suggestion
		to_chat(usr, "<span class='notice'>Шаттл специального назначения прибудет на [station_name_ru] через [(SPECOPS_MOVETIME/10)] секунд.</span>")
```

2024-01-19 18:02 UTC, KandreyKandrey commented on code/game/machinery/computer/vox_shuttle.dm
> +		to_chat(user, "<span class='notice'>Вы понятия не имеете, как это использовать</span>")
```suggestion
		to_chat(user, "<span class='notice'>Вы понятия не имеете, как это использовать.</span>")
```

2024-01-19 18:38 UTC, Kiromaka commented
Емердженси клозеты уже переводили, новый вариант лучше, пофиксите старые клозеты.

2024-01-20 21:00 UTC, KandreyKandrey commented on code/game/machinery/computer/arrival_shuttle.dm
> +			to_chat(usr, "<span class='notice'>Шаттл еще не готов к полёту.</span>")
какая-то избирательность с буквой 'ё'
(не надо это исправлять, просто интересная заметка)

2024-01-20 21:03 UTC, KandreyKandrey commented on code/game/machinery/computer/arrival_shuttle.dm
> +	cases = list("консоль связи трансферного шаттла", "консоли связи трансферного шаттла", "консоле связи трансферного шаттла", "консоль связи трансферного шаттла", "консолью связи трансферного шаттла",
```suggestion
	cases = list("консоль связи трансферного шаттла", "консоли связи трансферного шаттла", "консоли связи трансферного шаттла", "консоль связи трансферного шаттла", "консолью связи трансферного шаттла", "консоли связи трансферного шаттла")
```

2024-01-20 21:08 UTC, KandreyKandrey commented on code/game/machinery/computer/shuttle.dm
> +			to_chat(user, "Уровень доступа ID карты [W:registered_name] не достаточен.")
мб тут 'недостаточный' написать?

2024-01-20 21:14 UTC, KandreyKandrey commented on code/modules/locations/shuttles/Intercom.dm
> +	cases = list("интерком станции", "интеркома станции", "интеркому станции", "интерком станции", "интерком станции", "интеркоме станции")
```suggestion
	cases = list("интерком станции", "интеркома станции", "интеркому станции", "интерком станции", "интеркомом станции", "интеркоме станции")
```

2024-01-20 21:16 UTC, KandreyKandrey commented on code/modules/locations/shuttles/closet.dm
> +	cases = list("вентиляция двигателя", "вентиляции двигателя", "Вентиляции двигателя", "вентиляцию двигателя", "вентиляционным двигателем", "вентиляционном двигателе")
```suggestion
	cases = list("вентиляция двигателя", "вентиляции двигателя", "Вентиляции двигателя", "вентиляцию двигателя", "вентиляцией двигателя", "вентиляции двигателя")
```

2024-01-20 21:17 UTC, KandreyKandrey commented on code/modules/locations/shuttles/computer.dm
> +	cases = list("монитор камеры видеонаблюдения", "монитора камеры видеонаблюдения", "монитору камеры видеонаблюдения", "монитор камеры видеонаблюдения", "монитором камеры видеонаблюдения", "мониторе к
```suggestion
	cases = list("монитор камер видеонаблюдения", "монитора камер видеонаблюдения", "монитору камер видеонаблюдения", "монитор камер видеонаблюдения", "монитором камер видеонаблюдения", "мониторе камер видеонаблюдения")
```

2024-01-20 21:19 UTC, KandreyKandrey commented on code/modules/locations/shuttles/computer.dm
> +	desc = "Используется для мониторинга активных датчиков состояния здоровья, встроенных в большую часть униформы экипажа."
сейчас оно звучит как 'у экипажа есть датчики и в ботинках, и в рубашке, и в шапке допустим'
мб посыл был такой: 'в униформу большей части экипажа встроены датчики состояния здоровья' ?

2024-01-20 21:20 UTC, KandreyKandrey commented on code/modules/locations/shuttles/mine_sci_shuttle.dm
> +	cases = list("консоль шаттла Шахта-Наука", "консоли шаттла Шахта-Наука", "консоле шаттла Шахта-Наука", "консоль шаттла Шахта-Наука", "консолью шаттла Шахта-Наука", "консоле шаттла Шахта-Наука")
```suggestion
	cases = list("консоль шаттла Шахта-Наука", "консоли шаттла Шахта-Наука", "консоли шаттла Шахта-Наука", "консоль шаттла Шахта-Наука", "консолью шаттла Шахта-Наука", "консоли шаттла Шахта-Наука")
```

2024-01-20 21:22 UTC, KandreyKandrey commented on code/modules/locations/shuttles/mine_sci_shuttle.dm
> +	cases = list("консоль шаттла", "консоли шаттла", "консоле шаттла", "консоль шаттла", "консолью шаттла", "консоле шаттла")
```suggestion
	cases = list("консоль шаттла", "консоли шаттла", "консоли шаттла", "консоль шаттла", "консолью шаттла", "консоли шаттла")
```

2024-01-20 21:24 UTC, KandreyKandrey commented on code/game/machinery/computer/syndicate_shuttle.dm
> +	<a href='?src=\ref[src];mining=1'>К северо-востоку от шахтёрного астероида</a><br>"}
мб вместо 'шахтёрного астероида'

написать 'шахтёрского астероида' или 'астероида-шахты' ?

2024-01-20 22:09 UTC, Kiromaka commented on code/modules/locations/shuttles/closet.dm
> +	cases = list("вентиляция двигателя", "вентиляции двигателя", "Вентиляции двигателя", "вентиляцию двигателя", "вентиляционным двигателем", "вентиляционном двигателе")
```suggestion
	cases = list("вентиляция двигателя", "вентиляции двигателя", "вентиляции двигателя", "вентиляцию двигателя", "вентиляционным двигателем", "вентиляционном двигателе")
```

2024-01-20 22:11 UTC, Kiromaka commented on code/modules/locations/shuttles/closet.dm
> +	cases = list("вентиляция двигателя", "вентиляции двигателя", "Вентиляции двигателя", "вентиляцию двигателя", "вентиляцией двигателя", "вентиляции двигателя")
```suggestion
	cases = list("вентиляция двигателя", "вентиляции двигателя", "вентиляции двигателя", "вентиляцию двигателя", "вентиляцией двигателя", "вентиляции двигателя")
```

2024-01-20 22:12 UTC, Kiromaka commented
Выполняю работку за ази. 1984

2024-01-21 17:36 UTC, maleyvich requested changes
рекомендации

2024-01-21 17:36 UTC, maleyvich commented on code/game/machinery/computer/shuttle.dm
> +					visible_message("<span class='notice'><B>Тревога: осталось ещё [auth_need - authorized.len] авторизации, необходимых для экстренного запуска шаттла.</B></span>")
мб авторизаций?

2024-01-21 17:36 UTC, maleyvich commented on code/game/machinery/computer/shuttle.dm
> +				visible_message("<span class='notice'><B>Тревога: осталось ещё [auth_need - authorized.len] авторизации, необходимых для экстренного запуска шаттла.</B></span>")
опять же авторизаций?

2024-01-21 17:36 UTC, maleyvich commented on code/game/machinery/computer/specops_shuttle.dm
> +		to_chat(M, "<span class='warning'>Вы прибыли на станцию Центрального командования. Операция завершена!</span>")
Центрального Командования?

2024-01-21 17:36 UTC, maleyvich commented on code/game/machinery/computer/syndicate_shuttle.dm
> +	cases = list("шаттл Синдиката (Компьютерная плата)", "шаттла Синдиката (Компьютерная плата)", "шаттлу Синдиката (Компьютерная плата)", "шаттл Синдиката (Компьютерная плата)", "шаттлом Синдиката (Ком
компьютерная плата шаттла синдиката?

2024-01-21 17:36 UTC, maleyvich commented on code/game/machinery/computer/syndicate_specops_shuttle.dm
> +			to_chat(usr, "<span class='warning'>Шаттл элитного Синдиката не может улететь.</span>")
элитного отряда?

2024-01-21 17:36 UTC, maleyvich commented on code/game/machinery/computer/syndicate_specops_shuttle.dm
> +		to_chat(usr, "<span class='notice'>Шаттл элитного Синдиката прибудет на [station_name_ru] через [seconds] [seconds_word].</span>")
элитного отряда?

2024-01-21 17:36 UTC, maleyvich commented on code/modules/locations/shuttles/mine_sci_shuttle.dm
> +	cases = list("консоль шаттла Шахта-Наука", "консоли шаттла Шахта-Наука", "консоли шаттла Шахта-Наука", "консоль шаттла Шахта-Наука", "консолью шаттла Шахта-Наука", "консоли шаттла Шахта-Наука")
звучит немного странно но нет альтернативы

2024-01-21 18:34 UTC, ViDLiathan commented on code/game/machinery/computer/shuttle.dm
> +				visible_message("<span class='notice'><B>Тревога: осталось ещё [auth_need - authorized.len] авторизации, необходимых для экстренного запуска шаттла.</B></span>")
Внимание! Для экстренного запуска шаттла осталось получить разрешений: [auth_need - authorized.len]

2024-01-21 18:37 UTC, ViDLiathan commented on code/modules/locations/shuttles/mine_sci_shuttle.dm
> +	cases = list("консоль шаттла Шахта-Наука", "консоли шаттла Шахта-Наука", "консоли шаттла Шахта-Наука", "консоль шаттла Шахта-Наука", "консолью шаттла Шахта-Наука", "консоли шаттла Шахта-Наука")
Может археологошахтёрский шаттл?

2024-01-22 11:07 UTC, Chip11-n commented on code/modules/locations/shuttles/mine_sci_shuttle.dm
> +	cases = list("консоль шаттла Шахта-Наука", "консоли шаттла Шахта-Наука", "консоли шаттла Шахта-Наука", "консоль шаттла Шахта-Наука", "консолью шаттла Шахта-Наука", "консоли шаттла Шахта-Наука")
Может упороться и просто поставить шахтёрский шаттл? Или шаттл на астероид?

2024-01-22 18:23 UTC, volas approved these changes
по коду вроде ок, в текст не вчитывался. На всякий в тм поставлю сначала

2024-01-22 18:45 UTC, Chip11-n commented on code/game/area/shuttle_areas.dm
> +	cases = list("шахтерский-исследовательский шаттл", "шахтерско-исследовательского шаттла", "шахтерско-исследовательского шаттлу", "шахтерский-исследовательский шаттл", "шахтерско-исследовательским ша
"Шахтёрский-исследовательский шаттл", так и должно быть? От случая к случаю прыгает.

2024-01-22 18:45 UTC, Chip11-n commented on code/game/area/shuttle_areas.dm
> +	cases = list("шаттл Skipjack", "шаттла Skipjack", "шаттлу Skipjack", "шаттл Skipjack", "шаттлом Skipjack", "шаттле Skipjack")
Эмигрант или английский лазутчик? Вроде и отсылка, но не помню точно.

2024-01-22 18:45 UTC, Chip11-n commented on code/game/area/shuttle_areas.dm
> +	cases = list("вблизи шахтёрного астероида", "вблизи шахтёрного астероида", "вблизи шахтёрного астероида", "вблизи шахтёрного астероида", "вблизи шахтёрного астероида", "вблизи шахтёрного астероида")
Шахтерного? Не шахтёрского?

2024-01-22 18:45 UTC, Chip11-n commented on code/game/machinery/computer/shuttle.dm
> +			if("Отменить")
```suggestion
			if("Отмена")
```
Вариант не соответствует ответу. Либо наоборот, в консоли изменить. Тут надо бысть осторожным.

2024-01-22 18:45 UTC, Chip11-n commented on code/game/machinery/computer/syndicate_specops_shuttle.dm
> +						message = "ТРЕВОГА: Шаттл пристыковался к материнскому кораблю. Добро пожаловать домой, солдаты."
Рекомендация. Предлагаю "Внимание", ибо это скорее приветствие, а не поднятие тревоги.

2024-01-22 18:45 UTC, Chip11-n commented on code/modules/locations/shuttles/mine_sci_shuttle.dm
> +	cases = list("консоль шаттла", "консоли шаттла", "консоли шаттла", "консоль шаттла", "консолью шаттла", "консоли шаттла")
Рекомендация. Так по итогу консоль или компьютер? А то плата компьютерная, а результат консоль.

2024-01-22 19:13 UTC, volas commented on code/game/area/shuttle_areas.dm
> +	cases = list("шаттл Skipjack", "шаттла Skipjack", "шаттлу Skipjack", "шаттл Skipjack", "шаттлом Skipjack", "шаттле Skipjack")
по значению попрыгунчик или что-то вроде того, но названия ведь не переводим, можно просто транслитом

2024-01-23 13:25 UTC, Kiromaka approved these changes

2024-01-28 11:22 UTC, Chip11-n commented on code/modules/locations/shuttles/mine_sci_shuttle.dm
> +	name = ""
Какова причина?

2024-01-28 12:34 UTC, Chip11-n commented on code/modules/locations/shuttles/officer_shuttle.dm
> +	var/datum/browser/popup = new(user, "computer", "[capitalize(CASE(src, NOMINATIVE_CASE))]", 575, 450)
```suggestion
	var/datum/browser/popup = new(user, "computer", CASE(src, NOMINATIVE_CASE), 575, 450)
```

2024-01-28 12:51 UTC, AirBlack commented
сука козел ты размер окна увеличь у окна компа велосити

2024-01-29 03:46 UTC, volas commented
Просьба доделать что всплыло и надо мержить, я бы хотел в ближайшие пару дней

2024-01-30 15:28 UTC, merged