переводим клонилку
TauCetiStation/TauCetiClassic pull request #12625
Opened 2023-12-18 08:29 UTC by maleyvich

## Описание изменений
тайтл
## Почему и что этот ПР улучшит
тайтл
## Авторство
м
## Чеинжлог
м

2023-12-18 08:29 UTC, TauKitty commented
###### Changelog status: :radio_button: No changelog

2023-12-18 08:29 UTC, maleyvich commented
ээм... ладно

2023-12-18 15:33 UTC, KandreyKandrey commented on code/game/machinery/cloning.dm
> +	cases = list("диск с информацией о Императоре Человечества", "диска с информацией о Императоре Человечества", "диску с информацией о Императоре Человечества", "диск с информацией о Императоре Челове
'об' ?

2023-12-18 15:33 UTC, KandreyKandrey commented on code/game/machinery/cloning.dm
> +	cases = list("диск с информацией о Мистере Мугглесе", "диска с информацией о Мистере Мугллесе", "диску с информацией о Мистере Мугллесе", "диск с информацией о Мистере Муглессе", "диском с информаци
удвоенные буквы перепроверь

2023-12-18 15:34 UTC, KandreyKandrey commented on code/game/machinery/cloning.dm
> +			to_chat(user, "Воссоздание клона завершено на [round(completion)]%.")
'клонирование завершено на' ?

2023-12-18 15:35 UTC, KandreyKandrey commented on code/game/machinery/cloning.dm
> +	to_chat(H, "<span class='notice'><b>Разум медленно восстанавливается в ваше регенерирующее тело...</b><br><i>Так вот, как ощущается клонирование...</i></span>")
'разум медленно возвращается' ?

2023-12-18 15:36 UTC, KandreyKandrey commented on code/game/machinery/cloning.dm
> +			connected_message("Клон неисправен: сгнил.")
точно не 'неисправен' (это же не механизм)

2023-12-18 15:39 UTC, KandreyKandrey commented on code/game/machinery/computer/cloning.dm
> +		scantemp = "Ошибка: тело субьекта не поддерживается."
тут и ниже 'субъект'

2023-12-18 15:44 UTC, KandreyKandrey commented on code/game/machinery/cloning.dm
> +	Эти дискеты передаются для передачи генетической информации.
куда передаются (в оригинале 'используются')

2023-12-18 22:21 UTC, KandreyKandrey commented on code/game/machinery/cloning.dm
> +	to_chat(user, "Вы активировали экстренное извлечение оболочки.")
мб не будем оболочку приписывать?

2023-12-18 22:22 UTC, KandreyKandrey commented on code/game/machinery/cloning.dm
> +	Поздравляем, ваша станция закупила аппарат H-87!<br>
```suggestion
	Поздравляем, ваша станция приобрела аппарат H-87!<br>
```

2023-12-18 22:23 UTC, KandreyKandrey commented on code/game/machinery/cloning.dm
> +	Использование H-87 такое же простое, как и нейрохирургия! Просто вставьте гуманоидную оболочку в капсулу, просканируйте её и создайте новый профиль<br>
```suggestion
	Использование H-87 такое же простое, как и нейрохирургия! Просто поместите гуманоида в капсулу, запустите сканирование и создайте новый профиль<br>
```

2023-12-18 22:23 UTC, KandreyKandrey commented on code/game/machinery/cloning.dm
> +	<i>Сообщаем вам, что аппарат не умеет клонировать мартышек и прочих маленьких созданий, включая и неорганические. До такого мы пока не дошли. Гематомы могут привести к ошибкам в сканировании.</i><br
```suggestion
	<i>Сообщаем вам, что аппарат не умеет клонировать мартышек и прочих маленьких созданий, включая и неорганических. До такого мы пока не дошли. Гематомы могут привести к ошибкам в сканировании.</i><br>
```

2023-12-18 22:25 UTC, KandreyKandrey commented on code/game/machinery/cloning.dm
> +	<p>Профили для клонирования можно посмотреть в специальной для этого вкладке. При сканировании, в органика вживляется специальный имплант, информацию из которого можно получить в профиле органика.
```suggestion
	<p>Профили для клонирования можно посмотреть в специальной вкладке. При сканировании в органика вживляется специальный имплант, информацию с которого можно получить в профиле органика.
```

2023-12-18 22:27 UTC, KandreyKandrey commented on code/game/machinery/cloning.dm
> +	Для клонирования, нужно нажать кнопку "Клонировать" на выбранном профиле<br>
```suggestion
	Для клонирования нужно нажать кнопку "Клонировать" рядом с выбранным профилем<br>
```

2023-12-18 22:27 UTC, KandreyKandrey commented on code/game/machinery/cloning.dm
> +	Мы соблюдаем соглашение о конфиденциальности сотрудников вашей компании, поэтому клонирование живых членов экипажа аппаратом H-87 невозможно.<br>
```suggestion
	Мы соблюдаем соглашение о неразглашении конфиденциальной информации, поэтому клонирование живых членов экипажа аппаратом H-87 невозможно.<br>
```

2023-12-18 22:30 UTC, KandreyKandrey commented on code/game/machinery/cloning.dm
> +	Диалог загрузки или отправки возможно, как вы вставите дискету в аппарат.</p><br>
```suggestion
	Загрузка или отправка возможна только при наличии в аппарате дискеты.</p><br>
```

2023-12-18 22:32 UTC, KandreyKandrey commented on code/game/machinery/computer/cloning.dm
> +	dat += "<font size=-1><a href='byond://?src=\ref[src];refresh=1'>Перезапустить</a></font><br>"
```suggestion
	dat += "<font size=-1><a href='byond://?src=\ref[src];refresh=1'>Обновить</a></font><br>"
```

2023-12-18 22:33 UTC, KandreyKandrey commented on code/game/machinery/computer/cloning.dm
> +			dat += "<a href='byond://?src=\ref[src];task=autoprocess'>Автоматическое выполнение процедур</a>"
мб 'процедур' убрать?

2023-12-18 22:33 UTC, KandreyKandrey commented on code/game/machinery/computer/cloning.dm
> +			dat += "<h4>Функция сканера</h4>"
```suggestion
			dat += "<h4>Функции сканера</h4>"
```

2023-12-18 22:34 UTC, KandreyKandrey commented on code/game/machinery/computer/cloning.dm
> +				dat += "<a href='byond://?src=\ref[src];disk=eject'>Вытащить диск</a>"
```suggestion
				dat += "<a href='byond://?src=\ref[src];disk=eject'>Извлечь диск</a>"
```

2023-12-18 22:35 UTC, KandreyKandrey commented on code/game/machinery/computer/cloning.dm
> +			dat += "<b><a href='byond://?src=\ref[src];del_rec=1'>Просканируйте ID-картой для подтверждения.</a></b><br>"
```suggestion
			dat += "<b><a href='byond://?src=\ref[src];del_rec=1'>Приложите ID-карту для подтверждения.</a></b><br>"
```

2023-12-18 22:36 UTC, KandreyKandrey commented on code/game/machinery/computer/cloning.dm
> +				src.temp = "Загрузка успешна."
```suggestion
				src.temp = "Загрузка прошла успешно."
```

2023-12-18 22:36 UTC, KandreyKandrey commented on code/game/machinery/computer/cloning.dm
> +				temp = "Ошибка: капсула клонирования уже занята"
```suggestion
				temp = "Ошибка: капсула клонирования уже занята."
```

2023-12-18 22:36 UTC, KandreyKandrey commented on code/game/machinery/computer/cloning.dm
> +				temp = "Ошибка: недостаточно биомассы"
```suggestion
				temp = "Ошибка: недостаточно биомассы."
```

2023-12-18 22:36 UTC, KandreyKandrey commented on code/game/machinery/computer/cloning.dm
> +			temp = "Ошибка: повреждение данных"
```suggestion
			temp = "Ошибка: повреждение данных."
```

2023-12-18 22:38 UTC, KandreyKandrey commented
мб выбрать что-то одно из этих вариантов?
1)гуманоид
2)субъект
3)оболочка
4)существо

2023-12-19 07:06 UTC, Pivo24 commented on code/game/machinery/computer/cloning.dm
> +			dat += "<a href='byond://?src=\ref[src];task=autoprocess'>Автоматическое выполнение процедур</a>"
Вариант: Автоматический режим

2023-12-19 07:06 UTC, Pivo24 commented on code/game/machinery/computer/cloning.dm
> +		scantemp = "Ошибка: тело субьекта не поддерживается."
Может субъекта поменять на пациента?

2023-12-19 08:31 UTC, maleyvich commented on code/game/machinery/cloning.dm
> +			to_chat(user, "Воссоздание клона завершено на [round(completion)]%.")
текущий вариант мне больше нравится и симпатизирует, он же буквально из биомассы и днк воссоздаёт практически идеальную копию человека

2023-12-19 08:40 UTC, maleyvich commented
о господи

2023-12-19 09:27 UTC, KandreyKandrey commented on code/game/machinery/cloning.dm
> +	cases = list("диск с информацией об Мистере Маглзе", "диска с информацией об Мистере Маглзе", "диску с информацией об Мистере Маглзе", "диск с информацией об Мистере Маглзе", "диском с информацией о
на 'об'  я указал в строчке выше
(тут то зачем поменял)

2023-12-19 09:30 UTC, KandreyKandrey commented on code/game/machinery/cloning.dm
> +	Для клонирования, нужно нажать кнопку "Клонировать" на выбранном профиле<br>
если закрываешь, можешь отвечать, что не устроило?

2023-12-19 09:31 UTC, maleyvich commented on code/game/machinery/cloning.dm
> +	Для клонирования, нужно нажать кнопку "Клонировать" на выбранном профиле<br>
а, я думал всё таки закоммитило, прости.

2023-12-19 09:42 UTC, KandreyKandrey commented on code/game/machinery/cloning.dm
> +	<i>Сообщаем вам, что аппарат не умеет клонировать мартышек и прочих маленьких созданий, включая и неорганические. До такого мы пока не дошли. Гематомы могут привести к ошибкам в сканировании.</i><br
что не так?

2023-12-19 09:43 UTC, KandreyKandrey commented on code/game/machinery/cloning.dm
> +	Мы соблюдаем соглашение о конфиденциальности сотрудников вашей компании, поэтому клонирование живых членов экипажа аппаратом H-87 невозможно.<br>
что не так?

2023-12-19 09:43 UTC, KandreyKandrey commented on code/game/machinery/cloning.dm
> +	Диалог загрузки или отправки возможно, как вы вставите дискету в аппарат.</p><br>
что не так?

2023-12-19 09:43 UTC, maleyvich commented on code/game/machinery/cloning.dm
> +	Диалог загрузки или отправки возможно, как вы вставите дискету в аппарат.</p><br>
странно я это коммитил...

2023-12-19 15:14 UTC, Pivo24 commented on code/game/machinery/cloning.dm
> +	Загрузка или отправка возможно, как вы вставите дискету в аппарат.</p><br>
Возможна*

2023-12-19 15:29 UTC, Chip11-n requested changes
Обязательно сделай тест. Раз ты переводишь ответы в алерте, то переводи и в коде ниже.

2023-12-19 15:29 UTC, Chip11-n commented on code/game/machinery/computer/cloning.dm
> +	var/scantemp = "Сканер не занят"
```suggestion
	var/scantemp = "Сканер пуст"
```

2023-12-19 15:29 UTC, Chip11-n commented on code/game/machinery/cloning.dm
> +	to_chat(user, "Вы переключили режим защиты от записи на [src.read_only ? "включён" : "отключён"].")
"Режим защиты от записи на включен". Звучит странно.

2023-12-19 15:29 UTC, Chip11-n commented on code/game/machinery/computer/cloning.dm
> +					var/answer = tgui_alert(selected,"Вы желаете вернуться к жизни?","Cloning", list("Да","Нет"))
Малевич, проверь-ка в игре. А то если не ошибаюсь, оно работать не будет.

2023-12-19 15:29 UTC, Chip11-n commented on code/game/machinery/computer/cloning.dm
> +	var/datum/browser/popup = new(user, "клонирования", "Управление системой клонирования")
Ты же протестил?

2023-12-19 15:49 UTC, maleyvich commented on code/game/machinery/computer/cloning.dm
> +	var/datum/browser/popup = new(user, "клонирования", "Управление системой клонирования")
протестил  всё нормально

2023-12-19 15:51 UTC, maleyvich commented on code/game/machinery/computer/cloning.dm
> +					var/answer = tgui_alert(selected,"Вы желаете вернуться к жизни?","Cloning", list("Да","Нет"))
пофиксил

2023-12-19 15:56 UTC, maleyvich commented on code/game/machinery/cloning.dm
> +			connected_message("Клон отбракован: сгнил.")
если нет вопросов резолваю

2023-12-19 16:02 UTC, Pivo24 commented on code/game/machinery/cloning.dm
> +			to_chat(user, "<span class='danger'>Отказано в доступе.</span>")
Нет не стоит, потому что Отказано В Доступе это отстой

2023-12-19 16:02 UTC, Pivo24 commented on code/game/machinery/computer/cloning.dm
> +				temp = "Ошибка: не обнаружено капсулы клонирования."
Можно, но не обязательно нужно

2023-12-21 10:12 UTC, maleyvich commented on code/game/machinery/computer/cloning.dm
> +	var/datum/browser/popup = new(user, "клонирования", "Управление системой клонирования")
аналогично убрал перевод айди

2023-12-21 10:22 UTC, Chip11-n approved these changes
Всё ещё есть вопросы к переводу, но они к транс-депу. В целом окей.

2023-12-21 10:22 UTC, Chip11-n commented on code/game/machinery/cloning.dm
> +	to_chat(user, "Вы переключили режим защиты от записи на значение [src.read_only ? "включён" : "отключён"].")
Уже лучше, но вопрос следущий. Тут, на сколько понимаю, не будет скобок? "На значение включен"

2023-12-21 10:22 UTC, Chip11-n commented on code/game/machinery/cloning.dm
> +	to_chat(user, "Режим защиты от записи установлен на значение: [src.read_only ? "включён" : "отключён"].")
Тут тоже вопрос.

2023-12-21 10:25 UTC, Chip11-n commented on code/game/machinery/computer/cloning.dm
> +	var/datum/browser/popup = new(user, "клонирования", "Управление системой клонирования")
Меня этот момент всё ещё смущает, но ладно.

2023-12-21 17:16 UTC, maleyvich commented on code/game/machinery/computer/cloning.dm
> +	cases = list("консоль для капсулы клонирования", "консоли для капсулы клонирования", "консоли для капсулы клонирования", "консоль для капсулы клонирования", "консолью для капсулы клонирования", "кон
это как будто сама консоль и клонирует получится по смыслу, не согласен

2023-12-21 17:17 UTC, maleyvich commented on code/game/machinery/cloning.dm
> +	to_chat(H, "<span class='notice'><b>Разум медленно возвращается в ваше регенерирующее тело...</b><br><i>Так вот, как ощущается клонирование...</i></span>")
не понимаю почему те ревью объединились в одно но я не понимаю как залился тот коммит завтра уже скобочки пропадут

2023-12-21 17:18 UTC, maleyvich commented on code/game/machinery/cloning.dm
> +	to_chat(user, "Вы переключили режим защиты от записи на значение [src.read_only ? "включён" : "отключён"].")
оно действительно со скобками лучше выглядит но я не могу нормально с ними разобраться.

2023-12-21 18:56 UTC, Chip11-n commented on code/game/machinery/cloning.dm
> +	to_chat(user, "Вы переключили режим защиты от записи на значение [src.read_only ? "включён" : "отключён"].")
Приведи к виду /"[read_only...]/" (могу ошибаться и слеш в другую сторону должен быть, но он там будет выделяться). И да, убери пожалуйста лишний src, глаз мозолит.

2024-01-17 11:05 UTC, maleyvich commented on code/game/machinery/cloning.dm
> +	name = "Мануал для использования клонирующего аппарата H-87"
точно!

2024-01-27 08:59 UTC, Chip11-n reviewed
В остальном всё ок.

2024-01-27 08:59 UTC, Chip11-n commented on code/game/machinery/cloning.dm
> +	to_chat(user, "Вы переключили режим защиты от записи на значение [src.read_only ? "включён" : "отключён"].")
Малевич, ты хотя бы отпишись о нерешённой проблеме, не надо резолвать, потеряется же, это не дело. 
```suggestion
	to_chat(user, "Вы переключили режим защиты от записи на значение \"[src.read_only ? "включён" : "отключён"]\".")
```
Тут в идеале бы вообще что-то по типу Вы отключили/включили перезапись на диск, но оба варианта приемлимы.

2024-01-27 09:40 UTC, Kiromaka commented on code/game/machinery/cloning.dm
> +		to_chat(user, "<span class='notice'>[CASE(src, NOMINATIVE_CASE)] обрабатывает [W].</span>")
[w] ссылается на оккупанта ?

2024-01-27 09:41 UTC, Kiromaka commented on code/game/machinery/cloning.dm
> +		to_chat(user, "<span class='notice'>[CASE(src, NOMINATIVE_CASE)] обрабатывает [W].</span>")
а нет
не окупант, где падеж

2024-01-27 09:41 UTC, maleyvich commented on code/game/machinery/cloning.dm
> +		to_chat(user, "<span class='notice'>[CASE(src, NOMINATIVE_CASE)] обрабатывает [W].</span>")
w это /obj/item/weapon/reagent_containers/food/snacks/meat т.е кусок мяса

2024-01-27 09:43 UTC, maleyvich commented on code/game/machinery/cloning.dm
> +		to_chat(user, "<span class='notice'>[CASE(src, NOMINATIVE_CASE)] обрабатывает [W].</span>")
нет падежи применяются к src, а src у нас сама машинка

2024-01-27 09:45 UTC, Kiromaka commented on code/game/machinery/cloning.dm
> +		to_chat(user, "<span class='notice'>[CASE(src, NOMINATIVE_CASE)] обрабатывает [W].</span>")
добавь w падеж

2024-01-27 09:48 UTC, Kiromaka commented on code/game/machinery/cloning.dm
> +		to_chat(user, "<span class='notice'>[CASE(src, NOMINATIVE_CASE)] обрабатывает [CASE(W, NOMINATIVE_CASE)].</span>")
```suggestion
		to_chat(user, "<span class='notice'>[CASE(src, NOMINATIVE_CASE)] обрабатывает [CASE(W, ACCUSATIVE_CASE)].</span>")
```

2024-01-27 09:55 UTC, Kiromaka commented on code/game/machinery/computer/cloning.dm
> +	cases = list("консоль для капсулы клонирования", "консоли для капсулы клонирования", "консоли для капсулы клонирования", "консоль для капсулы клонирования", "консолью для капсулы клонирования", "кон
зачем "для" ?

2024-01-27 09:56 UTC, Kiromaka approved these changes
Вроде норм, только я бы "для" убрал.

2024-01-28 10:30 UTC, Kiromaka commented
Думаю можно кидать на ТМ.

2024-01-31 04:33 UTC, volas commented on code/game/machinery/cloning.dm
> +	cases = list("диск с информацией для клонирования", "диска с информацией для клонирования", "диску с информацией для клонирования", "диск с информацией для клонирования", "диском с информацией для к
только не информацией а данными

2024-01-31 04:34 UTC, volas commented on code/game/machinery/cloning.dm
> +	cases = list("диск с информацией об Императоре Человечества", "диска с информацией об Императоре Человечества", "диску с информацией об Императоре Человечества", "диск с информацией об Императоре Че
какая нафиг "информация об", хоть смотрите что переводите

2024-01-31 04:39 UTC, volas commented on code/game/machinery/cloning.dm
> +	cases = list("диск с информацией для клонирования", "диска с информацией для клонирования", "диску с информацией для клонирования", "диск с информацией для клонирования", "диском с информацией для к
вообще будет правильнее писать DNK данные или что-то такое, к клонированию они мало отношения имеют

2024-01-31 04:39 UTC, volas commented on code/game/machinery/cloning.dm
> +	cases = list("диск с информацией об Императоре Человечества", "диска с информацией об Императоре Человечества", "диску с информацией об Императоре Человечества", "диск с информацией об Императоре Че
тут соответственно 'God Emperor of Mankind' - просто лейбл на дискете с какими-то генетическими данными, он на заброшках и нужен генетикам.

2024-01-31 04:47 UTC, maleyvich commented on code/game/machinery/cloning.dm
> +	cases = list("диск с информацией об Императоре Человечества", "диска с информацией об Императоре Человечества", "диску с информацией об Императоре Человечества", "диск с информацией об Императоре Че
> какая нафиг "информация об", хоть смотрите что переводите

в одном из ревью посоветовали именно ОБ, изначально было О

2024-01-31 04:48 UTC, maleyvich commented on code/game/machinery/cloning.dm
> +	cases = list("диск с информацией об Императоре Человечества", "диска с информацией об Императоре Человечества", "диску с информацией об Императоре Человечества", "диск с информацией об Императоре Че
> тут соответственно 'God Emperor of Mankind' - просто лейбл на дискете с какими-то генетическими данными, он на заброшках и нужен генетикам.

а в чем проблема то заключается, я не понимаю

2024-01-31 04:49 UTC, maleyvich commented on code/game/machinery/cloning.dm
> +	cases = list("диск с информацией для клонирования", "диска с информацией для клонирования", "диску с информацией для клонирования", "диск с информацией для клонирования", "диском с информацией для к
> вообще будет правильнее писать DNA данные или что-то такое, к клонированию они мало отношения имеют

как буду у компа исправлю.

2024-01-31 04:50 UTC, volas commented on code/game/machinery/cloning.dm
> +	cases = list("диск с информацией об Императоре Человечества", "диска с информацией об Императоре Человечества", "диску с информацией об Императоре Человечества", "диск с информацией об Императоре Че
тут нету никакой информации о боге императоре и ты её никак не прочитаешь

2024-02-03 18:32 UTC, Chip11-n reviewed
Душно, но надо дотянуть.

2024-02-03 18:32 UTC, Chip11-n commented on code/game/machinery/cloning.dm
> +	cases = list("диск с информацией о Мистере Магглсе", "диска с информацией о Мистере Магглсе", "диску с информацией о Мистере Магглсе", "диск с информацией о Мистере Магглсе", "диском с информацией о
Здесь ситуация такая же, как и выше.

2024-02-03 18:32 UTC, Chip11-n commented on code/game/machinery/computer/cloning.dm
> +			dat += "<a href='byond://?src=\ref[src];task=autoprocess'>Автоматическое выполнение</a>"
В качестве придирки, но звучит странно.

2024-02-03 18:32 UTC, Chip11-n commented on code/game/machinery/computer/cloning.dm
> +		scantemp = "Ошибка: тело пациента не поддерживается."
Тело само по себе не поддерживается или по смыслу его физиология?

2024-02-03 18:32 UTC, Chip11-n commented on code/game/machinery/computer/cloning.dm
> +		scantemp = "Ошибка: мозг пациента не реагирует на сканирование."
Логическая ошибка. Мозг мёртв, как он может ответить? Но в оригинале похожая ситуация.

2024-02-03 18:32 UTC, Chip11-n commented on code/game/machinery/computer/cloning.dm
> +		scantemp = "<span class='bad'>Пациент не содержит достаточное количество материала для клонирования.</span>"
По смыслу подходит, но по логике не очень. Мясо есть? Есть. Так в чем дело? Этот трейт может быть даже у задушенного человека.

2024-02-03 18:36 UTC, maleyvich commented on code/game/machinery/computer/cloning.dm
> +		scantemp = "<span class='bad'>Пациент не содержит достаточное количество материала для клонирования.</span>"
под материалом может подразумеваться и генетический, почему бы и нет

2024-02-03 18:37 UTC, maleyvich commented on code/game/machinery/computer/cloning.dm
> +		scantemp = "Ошибка: мозг пациента не реагирует на сканирование."
завтра уже подумаю и исправлю.
мб просто заменю на "Ошибка: мозг мёртв"

2024-02-03 18:38 UTC, maleyvich commented on code/game/machinery/computer/cloning.dm
> +		scantemp = "Ошибка: тело пациента не поддерживается."
ну тут действительно больше физиология, но "тип тела" и "тело" как по мне не слишком отличается

2024-02-03 18:38 UTC, maleyvich commented on code/game/machinery/computer/cloning.dm
> +			dat += "<a href='byond://?src=\ref[src];task=autoprocess'>Автоматическое выполнение</a>"
не знаю что здесь не так

2024-02-04 09:27 UTC, Chip11-n commented on code/game/machinery/computer/cloning.dm
> +			dat += "<a href='byond://?src=\ref[src];task=stopautoprocess'>Остановить автоматическое выполнение</a>"
```suggestion
			dat += "<a href='byond://?src=\ref[src];task=stopautoprocess'>Остановить автопроцесс</a>"
```
Или что вы там хотели, главное однородность.

2024-02-04 09:27 UTC, Chip11-n commented on code/game/machinery/computer/cloning.dm
> +		dat += "<span class='disabled'>Автоматическое выполнение</span>"
```suggestion
		dat += "<span class='disabled'>Автопроцесс</span>"
```
И ещё одно.

2024-02-04 09:38 UTC, volas commented on code/game/machinery/cloning.dm
> +	cases = list("диск с информацией об Императоре Человечества", "диска с информацией об Императоре Человечества", "диску с информацией об Императоре Человечества", "диск с информацией об Императоре Че
опять "об", подразумевая, будто это информация. Но тут нету информации. Информация и данные - два разных по значению слова, изначально под data подразумевались именно данные.

И император - это просто лейбл, а не название диска, потому и в кавычках. 

Раз выше перевели как диск с ДНА, то тут должно быть что-то вроде

``"диск с ДНК - 'Бог Император Человечества'"``

2024-02-04 09:41 UTC, maleyvich commented on code/game/machinery/cloning.dm
> +	cases = list("диск с информацией об Императоре Человечества", "диска с информацией об Императоре Человечества", "диску с информацией об Императоре Человечества", "диск с информацией об Императоре Че
твой вариант очень плохо подходит под падежи и непонятно как это всё собственно склонять
зачем у нас в билде вообще существуют эти диски? я как помню, за них даже ничего в рнд не даётся.

2024-02-04 09:45 UTC, volas commented on code/game/machinery/cloning.dm
> +	cases = list("диск с информацией об Императоре Человечества", "диска с информацией об Императоре Человечества", "диску с информацией об Императоре Человечества", "диск с информацией об Императоре Че
замените "диск с ДНК" на "ДНК диск". "ДНК диску", "ДНК диска", "ДНК диску 'Бог Император Человечества'"

2024-02-04 09:49 UTC, volas commented on code/game/machinery/cloning.dm
> +	cases = list("диск с информацией об Императоре Человечества", "диска с информацией об Императоре Человечества", "диску с информацией об Императоре Человечества", "диск с информацией об Императоре Че
> зачем у нас в билде вообще существуют эти диски? я как помню, за них даже ничего в рнд не даётся.

просто пасхалка и отсылка

2024-02-04 09:51 UTC, volas commented on code/game/machinery/cloning.dm
> +	cases = list("диск с информацией об Императоре Человечества", "диска с информацией об Императоре Человечества", "диску с информацией об Императоре Человечества", "диск с информацией об Императоре Че
и кстати можно называть не диском вообще, а дискетой, это в английском одно слово

2024-02-04 10:11 UTC, maleyvich commented on code/game/machinery/cloning.dm
> +	cases = list("диск с информацией об Императоре Человечества", "диска с информацией об Императоре Человечества", "диску с информацией об Императоре Человечества", "диск с информацией об Императоре Че
всё готово заменил
а насчет диска и дискеты, не вижу смысла этого делать вовсе (суть не поменяется, но позже придётся помнить об этом ещё...)

2024-02-04 10:12 UTC, maleyvich commented on code/game/machinery/cloning.dm
> +	cases = list("диск с информацией об Императоре Человечества", "диска с информацией об Императоре Человечества", "диску с информацией об Императоре Человечества", "диск с информацией об Императоре Че
а, ну ладно оно везде дискета. момент

2024-02-04 11:04 UTC, maleyvich commented on code/game/machinery/cloning.dm
> +	cases = list("диск с информацией об Императоре Человечества", "диска с информацией об Императоре Человечества", "диску с информацией об Императоре Человечества", "диск с информацией об Императоре Че
всё решено резолваю

2024-02-04 12:29 UTC, Kiromaka commented on code/game/machinery/computer/cloning.dm
> +		scantemp = "<span class='bad'>Пациент не содержит достаточное количество материала для клонирования.</span>"
не очень звучит

2024-02-09 17:40 UTC, maleyvich commented
наконец то

2024-02-09 17:59 UTC, Chip11-n commented
Если в ближайшие дни никто из мейнтейнеров не глянет, буду мержить.

2024-02-09 18:08 UTC, Chip11-n commented on code/game/machinery/cloning.dm
> +	to_chat(user, "Режим защиты от записи установлен на значение: [src.read_only ? "включён" : "отключён"].")
Только заметил. 
`Режим защиты от записи установлен на значение: включён. `

Может что-то на подобии? 
```suggestion
	to_chat(user, "Защита от записи [read_only ? "включена" : "отключена"].")
```

2024-02-10 13:01 UTC, volas commented on code/game/machinery/computer/cloning.dm
> +		scantemp = "Ошибка: мозг пациента мёртв."
мозг у трупа так и так мертв, что-то ближе к оригинальному надо

2024-02-10 13:06 UTC, volas commented on code/game/machinery/computer/cloning.dm
> +		scantemp = "Ошибка: мозг пациента мёртв."
это про реанимацию, а тут клонирование чего угодно, лишь бы мозг был цел и человек в теле

2024-02-10 13:31 UTC, maleyvich commented on code/game/machinery/computer/cloning.dm
> +		scantemp = "Ошибка: мозг пациента мёртв."
господи помилуй наши души
пофикшено

2024-02-11 20:33 UTC, merged