[WiP] Даём возможность пощупать органы и вырывать их
TauCetiStation/TauCetiClassic pull request #12653
Opened 2023-12-29 10:31 UTC by maleyvich

## Описание изменений
добавление спрайтов для органов
## Почему и что этот ПР улучшит
органы перестанут быть чем-то неосязаемым, с чем можно подействовать только косвенно
## Авторство
спрайты берутся с различных билдов и перерисовываются мною
## Чеинжлог
:cl:
- image: Были добавлены спрайты для органов.

2023-12-29 10:31 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2023-12-29 11:00 UTC, maleyvich commented
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/104298869/f0d7ed24-0244-4e34-bba8-8ae0c907962a)

ингейм отображение сердец (проблема - обычное человеческое сердце очень маленькое)

2023-12-29 11:04 UTC, UDaV73rus commented
Они такие маленькие на других билдах, чтобы когда устраиваешь резню, весь коридор не был забит органами размером с весь тайл. А у нас есть ворлд иконки и норм

2023-12-29 11:26 UTC, maleyvich commented
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/104298869/ba4d8c54-4d52-41b6-9efc-06d1f8c5e5ac)
смог найти альтернативу текущему сердцу и перекрасил под нашу палитру, вроде бы всё выдержано

2023-12-29 11:46 UTC, Chip11-n commented
Пластиковым выглядит сердце. Может всё-таки запрещенный-красный?

2023-12-29 11:47 UTC, maleyvich commented
> Пластиковым выглядит сердце. Может всё-таки запрещенный-красный?

поспрашивал игроков в етолксе - им понравилось, хз, уже на мнение спрайтдепа

2023-12-29 12:43 UTC, KIBORG04 commented
Ты в курсе, что спрайтов добавить мало? Там надо много кода рефакторить и заставить его работать. Сейчас органов даже в кукле физически нету, они в нуллспейсе лежат и через него работают

2023-12-29 12:44 UTC, maleyvich commented
> Ты в курсе, что спрайтов добавить мало? Там надо много кода рефакторить и заставить его работать. Сейчас органов даже в кукле физически нету, они в нуллспейсе лежат и через него работают

в курсе

2023-12-29 13:03 UTC, maleyvich commented
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/104298869/625c4eb9-f9cc-4858-84ad-e1bc14f03d16)
 
 были добавлены легкие всем (кроме дион), пока всё суммарно выглядит вот так

2023-12-29 13:23 UTC, Deahaka commented
Как это улучшит РП?

2023-12-30 07:45 UTC, maleyvich commented
я не понимаю что я наделал

2023-12-30 09:14 UTC, WatlerJe commented
Спрайты внутренностей не должны быть больше размера 16х16 px.

2024-01-03 15:48 UTC, maleyvich commented
ну, вроде бы вся код-часть готова
осталось доделать органы и получается всё.

2024-01-03 16:24 UTC, TauKitty commented
Этот запрос на слияние был упомянут в **Tau Ceti Station Forum**. Там могут быть соответствующие подробности:

https://forum.taucetistation.org/t/dobavlenie-interaktiva-k-organam-by-maleyvich/41914/1

2024-01-03 16:35 UTC, KandreyKandrey commented on code/modules/organs/organ_internal.dm
> +			owner.adjustToxLoss(1.5)
когда эта ифка должна выполняться, если выше идёт присваивание одного другому?

2024-01-03 16:37 UTC, KandreyKandrey commented on code/modules/organs/organ_internal.dm
> +	var/organ_races =  list(null) // for species (human, tajaran, vox, etc.)
```suggestion
	var/list/organ_races =  list() // for species (human, tajaran, vox, etc.)
```

2024-01-03 16:42 UTC, KandreyKandrey commented on code/modules/organs/organ_internal.dm
> +	return ..()
```suggestion
	..()
```
родительский прок ничего не возвращает

2024-01-03 16:49 UTC, KandreyKandrey commented on code/modules/organs/organ.dm
> +	owner = H
```suggestion
/obj/item/organ/proc/del_owner(mob/living/carbon/human/H)
	loc = null
	owner = H
```
1)del_owner, но owner не удаляется
2) прямо над этим проком есть аналогичный (а там то зачем species передавали)

2024-01-03 16:52 UTC, KandreyKandrey commented on code/modules/organs/organ.dm
> +	owner = H
закрывать не надо пока
там 2 вопроса ещё

2024-01-03 16:56 UTC, KandreyKandrey commented on code/modules/organs/organ.dm
> +/obj/item/organ/proc/del_owner(mob/living/carbon/human/H)
над этим проком есть аналогичный

2024-01-03 16:58 UTC, maleyvich commented on code/modules/organs/organ_internal.dm
> +	var/list/organ_races =  list() // for species (human, tajaran, vox, etc.)
я попросту задал переменную в виде листа, ниже organ_races используется для органов

другой вопрос правильно ли я все сделал :trollface:

2024-01-03 21:33 UTC, MrPerenka commented
Я что-то так посмотрел, и толи я не умею читать код, толи тут не прописан способ получения органов. Так где их брать? Карго, роботехника, авто/протолат, ксенобио, раундстарт?

2024-01-04 02:50 UTC, maleyvich commented
> Я что-то так посмотрел, и толи я не умею читать код, толи тут не прописан способ получения органов. Так где их брать? Карго, роботехника, авто/протолат, ксенобио, раундстарт?

пока органы есть только у хуманов, этот пр лишь внедряет органы в жизнь игрочков

позже уже будут добавлены способы получения извне, если потребуют мейнтейнеры то добавлю прям в этот пр

2024-01-04 04:16 UTC, maleyvich commented on code/modules/organs/organ.dm
> +	owner = H
овнер теперь зануляется

2024-01-04 04:17 UTC, maleyvich commented on code/modules/organs/organ.dm
> +/obj/item/organ/proc/del_owner(mob/living/carbon/human/H)
теперь он не аналогичный

2024-01-04 04:18 UTC, maleyvich commented
теперь в операционных, робототехнике и на складе меда будут лежать холодильники с органами
холодильник с органами для ксеносов на складу меда потому что потому.

2024-01-04 04:50 UTC, maleyvich commented on code/modules/surgery/implant.dm
> +	if(BP.implants.len || BP.bodypart_organs.len)
теперь операция называется бодипарт манипулейшн
собственно и название файла тоже поменялось, теперь не вижу различий с названием файлика и операций, которые в нем прописаны

2024-01-04 04:57 UTC, maleyvich commented on code/modules/surgery/implant.dm
> +		var/list/embed_object_organs = list()
ну теперь internal, но вообще не понимаю смысла этой замены

2024-01-05 17:32 UTC, DarthSidiousPalpatine commented on code/modules/surgery/braincore.dm
> -	return ..() && target.op_stage.skull == 0
А грудную клетку чтобы достать сердце и лёгкие не надо вскрывать?

2024-01-05 17:36 UTC, maleyvich commented on code/modules/organs/organ.dm
> -	STOP_PROCESSING(SSobj, src)
меня попросили я и убрал это, уверяя что процессинг выполняется самим хуманом

2024-01-05 17:37 UTC, maleyvich commented on code/modules/surgery/bodypart_manipulation.dm
> +						H.transfer_identity(target)
так было до меня и я не хочу что-то поломать

2024-01-05 17:44 UTC, maleyvich commented on code/modules/surgery/bodypart_manipulation.dm
> +		H.insert_organ(tool)
1. я проверял и К СОЖАЛЕНИЮ, два сердца, три печени или четыре глаза быть НЕ МОЖЕТ
2. учту
3. оставлю без ответа так как не понял (вероятно, недовольство из за того что за операцию можно засунуть только один орган?)
4. я как раз таки насчет этого и боялся, прямо сейчас в голове созрела возможная идея решения этой проблемы
5. учту

2024-01-05 17:45 UTC, maleyvich commented on code/modules/surgery/braincore.dm
> -	return ..() && target.op_stage.skull == 0
очень хорошее замечание.

2024-01-05 17:48 UTC, KandreyKandrey commented on code/modules/mob/living/carbon/brain/MMI.dm
> +	var/obj/item/organ/internal/brain
var/obj/item/organ/internal/brain - переменная с именем brain и типом /obj/item/organ/internal
var/obj/item/organ/internal/brain/brain - переменная с именем brain и типом /obj/item/organ/internal/brain (т.е что это именно мозг, а не просто внутренний орган)

2024-01-05 17:53 UTC, maleyvich commented on code/modules/surgery/bodypart_manipulation.dm
> +				continue
мы проходимся не только по имплантам, но и по bodypart_organs
`if(BP.implants.len || BP.bodypart_organs.len)`

2024-01-05 18:25 UTC, maleyvich commented on code/modules/surgery/bodypart_manipulation.dm
> +		H.insert_organ(tool)
может потому что у нас вообще никак не может получится два одинаковых органа? 

я специально зашёл на локалку чтобы проверить нет ли казусов что можно установить две печени в пациенте - как оказалось, НЕЛЬЗЯ
одновременно я заметил и оплошность что можно вставить орган вокса хуману

прежде чем что-то сказать я это проверяю, и в этом случае все работает как должно

2024-01-05 18:35 UTC, maleyvich commented on code/modules/organs/organ.dm
> +	owner = null
чтобы ТОЧНО решить проблему что орган остаётся в теле даже если его достанут

2024-01-07 04:40 UTC, 4310V343k commented on code/modules/surgery/bodypart_manipulation.dm
> +		for(var/embed_object in BP.implants || BP.bodypart_organs)
это так не работает

2024-01-07 04:41 UTC, 4310V343k commented on code/modules/surgery/bodypart_manipulation.dm
> +				BP.bodypart_organs.Copy()
зачем эта копия? может она должна была быть строкой ниже?

2024-01-07 04:42 UTC, 4310V343k commented on code/modules/surgery/bodypart_manipulation.dm
> +					else if(istype(choosen_object, /obj/item/organ/internal/brain))
эта ифка недосягаема

2024-01-07 04:46 UTC, 4310V343k commented on code/modules/surgery/bodypart_manipulation.dm
> +					remove_from_cavity(user, target, choosen_object, BP, tool)
этот прок, хоть и, технически, выполняет то, что хочется (форсмувает на пол и пишет в чат), используется немного для другого

2024-01-07 04:51 UTC, 4310V343k commented on code/modules/surgery/bodypart_manipulation.dm
> +	if (BP.implants.len || BP.bodypart_organs.len)
ниже код специфичен для имплантов. хотя даже до этого изменения тут мог быть рантайм, если имплант - не имплант, а какая-нибудь шрапнель

2024-01-07 04:52 UTC, 4310V343k requested changes
надо было, конечно, в один ревью закинуть, но я чето тупанул

2024-01-07 04:56 UTC, 4310V343k commented on code/modules/surgery/bodypart_manipulation.dm
> +					else if (istype(choosen_object, /obj/item/organ/internal/brain))
гитхаб написал outdated но оно осталось неизмененным 👴

2024-01-07 04:59 UTC, maleyvich commented on code/modules/surgery/bodypart_manipulation.dm
> +	if (BP.implants.len || BP.bodypart_organs.len)
имплантом считается любая вещь внутри хумана, не только сами импланты

2024-01-07 05:00 UTC, 4310V343k commented on code/modules/surgery/bodypart_manipulation.dm
> +	if (BP.implants.len || BP.bodypart_organs.len)
посмотри в код

2024-01-07 05:23 UTC, maleyvich commented on code/modules/surgery/bodypart_manipulation.dm
> +	if (BP.implants.len || BP.bodypart_organs.len)
> посмотри в код и что он тут делает, пожалуйста
> 
> > прежде чем что-то сказать я это проверяю

так это даж в ховтукоде или рнд обсуждалось, что это неправильно и всё такое
во всяком случае, далее уже для каждой категории "имплантов" идёт свой код

2024-01-07 05:23 UTC, maleyvich commented on code/modules/surgery/bodypart_manipulation.dm
> +					else if(istype(choosen_object, /obj/item/organ/internal/brain))
я уже пытался её как угодно дергать, не получается однако...

2024-01-07 05:25 UTC, maleyvich commented on code/modules/surgery/braincore.dm
> -	return ..() && target.op_stage.skull == 0
исправил, кажется.

2024-01-07 05:25 UTC, maleyvich commented on code/modules/surgery/bodypart_manipulation.dm
> +				BP.bodypart_organs.Copy()
оно работает именно если копию сделать сперва, а не после

2024-01-07 05:29 UTC, 4310V343k commented on code/modules/surgery/bodypart_manipulation.dm
> +					remove_from_cavity(user, target, choosen_object, BP, tool)
BP.implants - то, что имплантировано в человека - то, что изначально в нём находится не должно

2024-01-07 05:29 UTC, 4310V343k commented on code/modules/surgery/bodypart_manipulation.dm
> +		for(var/embed_object in BP.implants || BP.bodypart_organs)
да что ты такое говоришь

2024-01-07 05:30 UTC, 4310V343k commented on code/modules/surgery/bodypart_manipulation.dm
> +				BP.bodypart_organs.Copy()
копия, которую ты делаешь, нигде не сохраняется и ни на что не влияет

2024-01-07 05:31 UTC, maleyvich commented on code/modules/surgery/bodypart_manipulation.dm
> +		for(var/embed_object in BP.implants || BP.bodypart_organs)
эээээ, да?
мы не учитываем бодипарт_органы, откуда же им взяться??? они не BP.implants, они попросту не покажутся.

2024-01-07 05:32 UTC, 4310V343k commented on code/modules/surgery/bodypart_manipulation.dm
> +		for(var/embed_object in BP.implants || BP.bodypart_organs)
for(var/el in list1 || list2) итерирует только по list1

2024-01-07 05:33 UTC, 4310V343k commented on code/modules/surgery/bodypart_manipulation.dm
> +					remove_from_cavity(user, target, choosen_object, BP, tool)
> так вещью в BP.implants может оказаться все что угодно, для этого даже есть отдельная категория "Else"

как это вообще отвечает на мое ревью?

2024-01-07 05:37 UTC, 4310V343k commented on code/modules/surgery/bodypart_manipulation.dm
> +					else if(istype(choosen_object, /obj/item/organ/internal/brain))
просто сделай это как обычную ифку?

2024-01-07 05:39 UTC, 4310V343k commented on code/modules/surgery/bodypart_manipulation.dm
> +	if (BP.implants.len || BP.bodypart_organs.len)
"дальше" не существует. это конец файла. и проверок, что это именно имплант, который можно активировать, здесь тоже нет
смотри на контекст, а не на одну похожую на что-то другую строку, что я выделил

2024-01-07 05:40 UTC, maleyvich commented on code/modules/surgery/bodypart_manipulation.dm
> +					remove_from_cavity(user, target, choosen_object, BP, tool)
я понимаю, что ты хочешь видеть что-то другое вместо remove_from_cavity, но в каких случаях текущий вариант может что-то поломать?

2024-01-07 05:45 UTC, 4310V343k commented on code/modules/surgery/bodypart_manipulation.dm
> +					remove_from_cavity(user, target, choosen_object, BP, tool)
я уже лежу в кровати и мне тяжело посмотреть, может ли что-то *сломаться* per se, но это всё ещё жуткий костыль. судя по функции, кто-то может предположить, что функция работает только с имплантированными вещами (так и есть), и на основе этого поменяет её так, что она будет рантаймить, если вызвать её для органов

2024-01-07 07:50 UTC, maleyvich commented
к сожалению, я действительно взялся за слишком огромную вещь и не смог с ней справиться. несмотря на то, что я хотел доделать это всё, однако недостаток опыта не позволит мне сделать это, спасибо ревьюверам и тем, кто помог мне сделать хотя бы то, что щас есть

2024-01-07 07:50 UTC, closed without merging

2024-04-09 11:25 UTC, TauKitty commented
Этот запрос на слияние был упомянут в **Tau Ceti Station Forum**. Там могут быть соответствующие подробности:

https://forum.taucetistation.org/t/kibernetika/42735/10