Новый декор.
TauCetiStation/TauCetiClassic pull request #12655
Opened 2023-12-30 08:59 UTC by DarthSidiousPalpatine

## Описание изменений
Добавил:
Глобус Венеры, Земли, Яргона-4:
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/21008918/b3a8b0c3-e428-4350-ab39-cbc89fce7b97)

Деревянные настольные часы:
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/21008918/b00bb02e-cd82-4384-95e9-c2eb90156cc0)

4 абстрактных статуэтки:
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/21008918/9d1f429c-5041-4b75-9521-81377281cc3f)

3 бюста должностных лиц НТ с подписями (спасибо WhalePower):
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/21008918/d47a6b67-8adf-4589-839d-70d357bce816)

15 ваз для цветов:
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/21008918/55aee188-ca9c-40ca-86bf-77777cb74105)

4 вида стикеров:
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/21008918/8a35bbce-b3dd-4284-96ee-5979f43aa4f0)

2 вида холодильников, большой и минибар:
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/21008918/399032c6-6d9f-4eec-b274-cc6af462b116)

## Почему и что этот ПР улучшит
Как выглядят глобусы, статуэтки, настольные часы и бюсты в игре (Я их не расставлял, потому что мне лень думать куда. Мапперам больше простора на декор крч):
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/21008918/7cf876f4-e1e5-462a-b454-3cfe504d1c37)

Как выглядят вазы в игре (их уже расставил):
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/21008918/ac503fd0-7175-4c8d-966e-dea289bff400)![image](https://github.com/TauCetiStation/TauCetiClassic/assets/21008918/2580af0a-4515-4d2e-b0d7-fbbadf7001d7)![image](https://github.com/TauCetiStation/TauCetiClassic/assets/21008918/8ecd444e-8a77-45b5-b54c-cb22519fd066)

Как выглядят стикеры в игре:
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/21008918/d09c9576-4d2b-4ab5-b31b-4ff1c57dfddb)
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/21008918/eb1dd2c5-ebb2-4920-8829-e87ae57e67cd)

Как выглядят холодильники в игре (их тоже расставил):
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/21008918/e7486dda-3ddb-48c8-a24e-14daa45df61c)![image](https://github.com/TauCetiStation/TauCetiClassic/assets/21008918/2db743e4-5f83-4f28-ad58-5fdd555f79c1)![image](https://github.com/TauCetiStation/TauCetiClassic/assets/21008918/c2c1d226-738a-47b4-b615-28f786144fc9)
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/21008918/f595f9dc-a5b9-40e2-98b9-5e9c767e840e)
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/21008918/81c52fbc-4fa9-47e9-b41f-c4d600ed95be)
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/21008918/628600b9-064b-4bba-b341-fd325393d29d)

## Авторство
AndreyGysev и все все все, кто помогал в дискорде.
WhalePower написал имена и описания для бюстов.

## Чеинжлог
 :cl: AndreyGysev, WhalePower
  - rscadd: Множество декоративных вещей
  - rscadd: Стикеры
  - rscadd: Холодильники

2023-12-30 08:59 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2023-12-30 09:05 UTC, TauKitty commented
Этот запрос на слияние был упомянут в **Tau Ceti Station Forum**. Там могут быть соответствующие подробности:

https://forum.taucetistation.org/t/fludilka-chast-2/28659/30043

2023-12-30 09:23 UTC, WatlerJe requested changes
Основная претензия на которой я остановлюсь это - Все в одном ПРе. 
Будет лучше разнести фичи по разным ПРам и уже там оценивать пригодность по спрайтерскому признаку.

2023-12-30 09:24 UTC, DarthSidiousPalpatine commented
В прошлый раз я тоже в одном ПРе декор делал, так что не вижу причин декор разносить по куче пров.

Оно всё имеет минимальный механ и чисто декоративное.

2023-12-30 09:28 UTC, WatlerJe commented
Как хочешь. Просто я не могу пропустить весь ПР ибо вижу в нем множество недостатков со стороны спрайтов, тогда как те же ситкеры отдельно я бы апрвнул сразу.

2023-12-30 09:28 UTC, DarthSidiousPalpatine commented
Ну опиши недостатки по спрайтам и я их заменю, хз.

2023-12-30 09:28 UTC, WatlerJe commented
Я уже написал, что первый и главный это то что все в одном ПРе.

2023-12-30 09:29 UTC, DarthSidiousPalpatine commented
бля, если из всего пра ты бы только стикеры замержил то пиздееееееец

2023-12-30 09:30 UTC, DarthSidiousPalpatine commented
То что спрайты в одном ПРе это не недостаток спрайтов.

2023-12-30 12:39 UTC, arygal commented
Холодосы в отделах как то вырвиглазно смотрятся. Может стоит покрасить его в нейтральный\цвет отдела.

2023-12-30 12:49 UTC, DarthSidiousPalpatine commented
> Холодосы в отделах как то вырвиглазно смотрятся. Может стоит покрасить его в нейтральный\цвет отдела.

Это же фирменные холодосы Einstein Electricity, они должны быть красными :P
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/21008918/372a938f-6f78-4df6-883a-a2444adcd05e)

2023-12-30 12:50 UTC, DarthSidiousPalpatine commented
> Холодосы в отделах как то вырвиглазно смотрятся. Может стоит покрасить его в нейтральный\цвет отдела.

Я ещё потом когда-нибудь микроволновки перерисую :dovolen:

2023-12-31 10:35 UTC, DarthSidiousPalpatine commented
Всё нормально, добавляю цветные микроволновки, кулеры и тостеры

2023-12-31 10:35 UTC, DarthSidiousPalpatine commented
Чтобы холодильники цветные вписались

2023-12-31 23:50 UTC, DarthSidiousPalpatine commented
Обновил ПР, обновил описание, картинок добавил ещё больше.

2023-12-31 23:57 UTC, DarthSidiousPalpatine commented
Важный несёт бутылку
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/21008918/2cf3d369-44bc-4bb3-9e69-5264c64fc0c8)

2024-01-02 08:18 UTC, DarthSidiousPalpatine commented
# Абсолютно все места где есть хоть какие-то изменения, чтобы посмотреть спрайты в естественной среде обитания:
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/21008918/a0cf6e61-02a3-45bc-9df8-17a8ff4fe4c8)
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/21008918/be859c93-4987-4cda-9974-431003bf4a25)
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/21008918/a05aa217-2663-47fa-8ffa-60e1b7e29e1b)
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/21008918/4321f907-4ca9-49f3-b296-e1460b42cf9f)
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/21008918/abc14ab4-e8b4-4090-8b74-b02d054d0094)
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/21008918/86459f55-bdde-44af-ad38-9d922718bcbd)
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/21008918/9fb85092-3b50-4f83-a394-477bdbe891e0)
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/21008918/b4032428-3e53-423d-ac5b-5b3e5b375b70)
**Обычные крафтящиеся микрухи и холодосы не затронуты**
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/21008918/f5a18414-c969-4a09-82ff-84576ebf1778)
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/21008918/05bf0492-b21b-4c40-a0b4-22b8847d0969)
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/21008918/e494daf3-af29-4c4b-a03d-5a9555a82b0d)
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/21008918/09c7f186-b31b-4d0d-b1dd-1f218878add9)
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/21008918/e0237a59-77ad-4336-aab2-d7586dc5cd57)
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/21008918/b06cb05a-a3b3-4fb7-a2de-b1a5c12d66bf)
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/21008918/d0878f4e-475e-4e94-a20f-8215835ebfe0)
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/21008918/19af8285-2eed-4ba6-9208-3b7efdcf6eb3)
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/21008918/a58035dd-10fe-4c9a-9703-fee946e69bbf)
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/21008918/3c545368-787c-404e-960b-523c103cf34a)
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/21008918/41398a22-ff46-4011-a770-45e05b5d1dea)
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/21008918/df43eae4-7543-4a55-ae43-affdac7d4145)
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/21008918/f12f1dd3-c67a-47cf-ac2a-b0ea79b0bd6d)
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/21008918/9a2306fd-3ed4-4bb4-842f-822ed48bb83d)
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/21008918/d9ca4206-db9c-4cfb-95e0-a2b011c105e1)
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/21008918/36cfbdd8-a15a-425f-9318-d62158a55539)
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/21008918/49c1a111-a3a5-4312-9bf3-d8490846972d)
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/21008918/ca64f678-afc9-43ab-a964-2e8a420a7e9a)
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/21008918/fa302ee0-4c52-4b06-aabb-eae5b7a6f578)
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/21008918/54bf4130-9ede-45dd-b010-11d2d5a691cd)
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/21008918/62a19875-da6f-467d-a005-d21c6c103cdc)
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/21008918/227f1d6a-513e-42b8-bd28-1602c6428b46)
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/21008918/bac153be-6b24-493b-8b93-7a0fe6441dc6)
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/21008918/19d69821-5a9a-4e84-908f-0afa6722c698)
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/21008918/347339e4-ee99-4130-8579-a6e0a5f8b48d)
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/21008918/081e5984-b0e9-410e-9672-e95231e0c97c)
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/21008918/27883641-0d88-4967-a0cd-87fa8dbb23c5)
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/21008918/f18faac6-ca5e-45d3-93c4-a4b5456dd54e)
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/21008918/ea19abcc-a3b8-4e94-9886-6ac58e74789a)
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/21008918/b6ac1c85-4c9d-4601-919a-60d2aea62dfa)
![Uploading image.png…]()
![Uploading image.png…]()

2024-01-02 08:25 UTC, DarthSidiousPalpatine commented on code/game/objects/items/decorations.dm
> +	name = "statuette"
Не пон, расскажешь как сделать - сделаю

2024-01-02 09:26 UTC, DarthSidiousPalpatine commented on code/game/objects/structures/crates_lockers/closets/utility_closets.dm
> +	cases = list("холодильник", "холодильника", "холодильнику", "холодильник", "холодильником", "холодильнике")
мини-бар

2024-01-06 15:38 UTC, DarthSidiousPalpatine commented
Запрашиваю ревью спрайтдепа

2024-01-06 15:39 UTC, DarthSidiousPalpatine commented
5 дней уже прошло с последней обновы ПРа :dovolen:

2024-01-06 15:39 UTC, DarthSidiousPalpatine commented
9 лайков 0 дизлайков. Мапперы всего ТАУ ожидают новый декор. ДОКОЛЕ?!!

2024-01-06 15:50 UTC, KandreyKandrey commented on code/game/objects/items/decorations.dm
> +	cases = list("маятник ньютона", "маятника ньютона", "маятнику ньютона", "маятник ньютона", "маятником ньютона", "маятнике ньютона")
почему фамилия с маленькой буквы?

2024-01-06 15:53 UTC, DarthSidiousPalpatine commented
Смотрите, оно боится что вернётся маппить карты с мои лучшим декором. Оно боится!
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/21008918/192468b4-8f41-4d0b-a9e0-065d14f4ff7f)

2024-01-06 16:00 UTC, DarthSidiousPalpatine commented
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/21008918/1deaf0c8-0e38-472f-a576-4d4827af71d3)

2024-01-06 16:00 UTC, Tap0r commented
Это хайпулечка невероятная оно откроет новые возможности в рп взаимодействии и не только!!!!!!!!!

2024-01-06 16:08 UTC, TauKitty commented
Этот запрос на слияние был упомянут в **Tau Ceti Station Forum**. Там могут быть соответствующие подробности:

https://forum.taucetistation.org/t/fludilka-chast-2/28659/30178

2024-01-07 08:22 UTC, WatlerJe commented
Я писал неделю назад, что необходимо сделать.

2024-01-07 08:58 UTC, DarthSidiousPalpatine commented
@volas Можно мне другого спрайтера? Вальтер отказывается ревьювать и назначил себя мейнтейнером, требуя изменения по форме ПРа.

2024-01-07 11:32 UTC, DarthSidiousPalpatine commented
Волас такой:
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/21008918/c7ff3351-d2a9-469f-8732-ec6ffeab4eb6)

Также Волас: *удаляет Гусева из дискорда чтобы не писал*

Логично.

2024-01-07 11:33 UTC, UDaV73rus requested changes
Нравится:
- холодильники
- часы
- стикеры
Не нравится:
- микроволновка. Сказать нечего по исправлению, и цвета и геометрия плохи
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/33157992/13b0ed6d-1e4a-4402-993f-aca36c2a96c0)
- глобусы земли и яргона, шумные колючие. Нужны более сочетающиеся плавные
- вазы. серый депрессняк ды и без цветов красивых не имеют смысла

2024-01-07 11:34 UTC, DarthSidiousPalpatine commented
Наконец, ревью от спрайтдепа.

ПРИКИНЬ, ВОЛАС, ВОТ ТАК ВЫГЛЯДИТ РЕВЬЮ, ВАААУ?

2024-01-07 11:34 UTC, DarthSidiousPalpatine commented
Спасибо удав, буду исправлять.

2024-01-07 11:57 UTC, DarthSidiousPalpatine commented
Сделал Землю плавнее, с одним большим кратером. У Яргона-4 убрал шум моря и удалил пару островов.
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/21008918/a648515e-8feb-4e5e-9377-b94199b600ce)

2024-01-07 12:31 UTC, DarthSidiousPalpatine commented
Цвет реагента воды в билде у нас:
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/21008918/f315ba54-47fe-45aa-b916-f76107e61a15)
Можно взять светлее

2024-01-07 13:02 UTC, DarthSidiousPalpatine commented
Да, мб, попробую. Можно ещё осветлить окрашиваемую "воду" внутри.

Зачекаю разные варианты и пришлю. Сейчас перерисовываю цветы... Ну, пытаюсь:
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/21008918/87181d4b-308b-4f33-a99d-ee22ec6caa63)

2024-01-07 14:05 UTC, DarthSidiousPalpatine commented
Хз кнш насчёт депрессивно тёмных ваз, но у меня они в трёх цветах, два тёмных и один светлый. Хз насколько сами вазочки должны быть цветными.

Но я попытался обновить цветы, которые можно положить в вазочки и вот что вышло:
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/21008918/bf11cbb0-ca2e-4b33-b873-ae1e426cfcc8)![image](https://github.com/TauCetiStation/TauCetiClassic/assets/21008918/cfd26b4d-a250-4451-86d5-ff9ae85548f0)
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/21008918/34561cb6-ccc1-455a-a715-bd6bf37adecc)
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/21008918/83c89f24-5d4a-4f60-a1a1-85a8c5f39c12)

2024-01-07 14:22 UTC, DarthSidiousPalpatine commented
> если спрайт бутылки накладывается поверх, бутылку сделать светлее, оно поможет?
Нет, оказалось спрайт бутылки под спрайтом воды что у бикера, что у бутыли.

Попробовал изменить цвет воды на:
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/21008918/61de6d6a-2fad-4c92-9bce-c639a234b917)

И, вроде как, вода не такая тёмная что в бикере что в бутыли...

2024-01-07 14:30 UTC, KIBORG04 reviewed
Код фигня передыловай

2024-01-07 20:39 UTC, DarthSidiousPalpatine commented
А потом я в совершенно другом ПРе книжную полку забубеню:
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/21008918/f1ac015e-8330-45b0-ad1a-ced4844d54ea)

2024-01-08 12:11 UTC, DarthSidiousPalpatine commented
# Ну, чтож, я попробовал исправить всё что потребовал Удав в ревью:
## Вазы - вазы сами не трогал, но цветы респрайтнул и теперь они в одной палитре с вазой и мб лучше стало:
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/21008918/b33f9d23-7490-4fa6-a105-4bf730970030)![image](https://github.com/TauCetiStation/TauCetiClassic/assets/21008918/aaf93b64-d349-42a7-a03d-001b75f8fa28)
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/21008918/88b6e752-a066-4b99-8fe4-8c55f62dd2ef)![image](https://github.com/TauCetiStation/TauCetiClassic/assets/21008918/4db655c1-d572-418f-afa0-6990e8a7b983)
(Ну и выше там были спрайты в разных сочетаниях, вазочки-то рандомно пикаются)
## Глобусы - я исправил, вроде, глобусы Земли и Яргона:
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/21008918/b1e90b0d-e2d4-4b4b-8a98-a1e7c8888d99)
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/21008918/bf0fbe45-29f9-45fe-9f9d-8986e9c7074b)
## Микроволновки - попробовал убрать аутлайн нижний, мб слишком тёмный был, убрал второй аутлайн у дверцы справа. Добавил сзади вент. прорези... Хз как поменять форму ещё. Это же микроволновка. Справа панель, слева дверь. Конец.
Ну а про цвет - она в тех же цветах что и холодос и кулер же.
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/21008918/bd34f5c1-53d4-46c6-86da-4e8ae800ba21)
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/21008918/f5a2d63e-4df7-4068-829f-697988245e5b)
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/21008918/2232143c-1985-4423-9c96-836937007909)
Хотя микроволновка именно в белом варианте выглядит прям трешово, хм.
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/21008918/1418a073-d3f8-4c8c-9d27-3848d9f6f4c3)

Ля, микроволновки ещё хуже стали, ахахах. Псц.

2024-01-08 15:13 UTC, DarthSidiousPalpatine commented
@UDaV73rus как будет время скажешь норм ли цветы для вазы и исправили ли они проблему и глобусы ещё.
Чтобы мне зациклиться на микроволновках тогда и сидеть их пинать...

Я думаю, мб сделать их просто плоскими? Без деталей. Ну и второй вопрос проблема в белой микроволновке или во всех?

2024-01-08 15:36 UTC, UDaV73rus commented
Из-за того что вазы мелкие, реалистичные тени смотрятся хреново, попробуй просто во весь рост вазы сделать тень сбоку как аутлайн
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/33157992/8a97bf6d-a0a5-4b9e-8efb-10ec92c3e20a) ![image](https://github.com/TauCetiStation/TauCetiClassic/assets/33157992/a5d87969-923b-4a9d-a19b-17208a1e8fbf)

Микроволновка плоская, не смотря на изначально очень рельефную задумку. (Из-за выбора цветов у света тени и их расположений) Избыток прямо кричащих, но не информативных деталей, которые забирают пространство у деталей которые реально характеризуют микроволновку

2024-01-08 17:20 UTC, DarthSidiousPalpatine commented
Так, ну, я попробовал добавить больше контраста крышка/стенка в микроволновки и вот что вышло:
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/21008918/0c88b763-e97d-4aa8-bcab-b4e8e463b4e9)![image](https://github.com/TauCetiStation/TauCetiClassic/assets/21008918/6cad715d-f98d-4dd6-b1c3-677cfb6fb1f3)
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/21008918/aface518-185a-4d4a-84b3-2d702f4be937)![image](https://github.com/TauCetiStation/TauCetiClassic/assets/21008918/fbfa8387-0aa6-4ed2-a11f-6bb06730809a)
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/21008918/ac0184aa-26fa-4cc4-a62a-bf548d0beb12)
Убрал нафиг все кнопки справа ибо... да накой они нужны, шумят, это микроволновка с тач-скрином :dovolen:

Что же касается вазочек. Вот результат добавления аутлайн-тени справа:
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/21008918/6c615dde-47bc-4b44-8221-e666453f6012)![image](https://github.com/TauCetiStation/TauCetiClassic/assets/21008918/c0fb847a-f8cd-4b3d-962d-87fd74e51e5b)![image](https://github.com/TauCetiStation/TauCetiClassic/assets/21008918/eca9b16d-f73a-409e-b1e6-4001c573e07f)
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/21008918/5e3d0da9-cb45-488f-8e37-c84dcc2211cc)

2024-01-08 17:53 UTC, Deahaka commented
На то красивее микрохвильовка

2024-01-09 21:10 UTC, DarthSidiousPalpatine commented
Удав, пропустишь ещё? Глобус сектора, а внутри коньяк.
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/21008918/82fee5a5-a55d-4677-9e77-88142620fc4a)

2024-01-09 22:29 UTC, DarthSidiousPalpatine commented
Крч вот теперь точно всё. Можно снова ревувать, как будет время. А я откланиваюсь.
Декора будет на станции - завались.

2024-01-10 12:53 UTC, DarthSidiousPalpatine commented
> Прошу разделить на отдельные ПР-ы, тут в кучу совершенно разные вещи которые непонятно как оценивать и как собирать по ним фидбек. Часть ПР-а уже могла бы быть смержена, пока ты переделываешь отдельные вещи и ждешь ревью.
> 
> Бюсты никак не связаны со стикерами, стикеры с кухонной машинерией, кухонная машинерия с бюстами, и так далее.

Хз чего ты истеришь, у меня все спрайты апрувнуты кроме глобуса и микроволновки. По ним жду фидбека после переделки последней.

2024-01-10 12:54 UTC, DarthSidiousPalpatine commented
> Часть ПР-а уже могла бы быть смержена, пока ты переделываешь отдельные вещи и ждешь ревью.

А я никуда не спешу. Хочу разом выпустить красивые красивости чтобы собрать фидбек с игроков как было в прошлый раз. В прошлый раз отлично получилось расспросить по внезапно появившемуся вокруг декору. И отзывы были в основном положительные. В этот раз я хочу также.

2024-01-10 13:00 UTC, DarthSidiousPalpatine commented
> ПР не атомарен и в таком виде не годится, и ты всё еще продолжаешь что-то сюда доливать, это не ок.

А он и атомарен, как и в предыдущий раз. Это декор и он декоративный. Всё что внутри ПРа объединяет одна вещь - это всё декор. Буквально всё - декор. Оно служит наполнению станции декором. Это один единый атом декора.

А ты можешь ещё недельку посидеть подождать, пока оставшуюся микроволновку отревувают и ПР аппрувнется.

2024-01-11 06:56 UTC, DarthSidiousPalpatine commented
@UDaV73rus, пятница сегодня же? Если да, то неделя прошла, вроде. Ревувнешь микроволновку? Я крышку сделал светлее, стенку темнее, удалил кнопки, оставил монитор.
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/21008918/b10aa4ff-5fb1-4ba0-8763-d3cc5a6d4e24)

Вот тени вазам как ты сказал, удав:
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/21008918/f5ff2904-827f-40c4-adae-328c8833ee4f)

А ещё теперь есть глобус космоса для коньяка:
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/21008918/0b0da12e-5fb6-4511-acc7-9e469eba54ba)![image](https://github.com/TauCetiStation/TauCetiClassic/assets/21008918/e4a4d03f-2c39-4fd4-941f-74e03b9cd6a9)

2024-01-11 19:16 UTC, DarthSidiousPalpatine commented
Эх, неделя прошла теперь точно и завтра я уже уезжаю далеко и надолго...
Не успел увидеть плоды трудов своих. И так и не замержили, так и не отревували эти несчастные микроволновки 😢

2024-01-13 15:58 UTC, DarthSidiousPalpatine commented
А, реально всего 5 дней прошло с последнего сообщения Удава. Ну знач времени нет, или желания. Ждём + Ждём.

2024-01-14 20:49 UTC, DarthSidiousPalpatine commented
## Хз, мб если сделать ещё 2 варианта для микроволновки то внезапно прилетит Удав на вертолёте и покажет ревью? :Р
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/21008918/868bd0bb-40ab-4213-a49e-31bfb6956ba4)
![Tau Ceti Station 2024-01-15 004847](https://github.com/TauCetiStation/TauCetiClassic/assets/21008918/77aca8e7-30eb-4ccf-94e3-06d8a9ef57d4)

2024-01-14 22:06 UTC, Kiromaka commented
Их разобрать можно ?

2024-01-15 11:39 UTC, Kiromaka commented
> > Их разобрать можно ?
> 
> Да, конечно, это обычные микроволновки. При сборке микроволновки пикается старый спрайт. А это микроволновки в отделах стоящие. Я сделал так потому что у микроволновок в отделах в описании написано что они произведены Einstein Electronics. Чтобы не было так, что в РНД напечатали микроволновку Einstein Electronics я сделал её не респрайтом старой, а подтипом старой и при разборе она дропнет все компоненты старой. При последующей сборке - получим старую микроволновку.
> 
> У повара кста тоже старые стоят но только потому что я другую кухонную машинерию не перерисовывал и там они выделяются.

Я про все, что нельзя брать в руки. 
Если что-то нельзя взять, то его должно быть можно разобрать, думаю у тебя можно, чекать лень, но все равно спрашиваю.

2024-01-15 11:40 UTC, DarthSidiousPalpatine commented
> > > Их разобрать можно ?
> > 
> > 
> > Да, конечно, это обычные микроволновки. При сборке микроволновки пикается старый спрайт. А это микроволновки в отделах стоящие. Я сделал так потому что у микроволновок в отделах в описании написано что они произведены Einstein Electronics. Чтобы не было так, что в РНД напечатали микроволновку Einstein Electronics я сделал её не респрайтом старой, а подтипом старой и при разборе она дропнет все компоненты старой. При последующей сборке - получим старую микроволновку.
> > У повара кста тоже старые стоят но только потому что я другую кухонную машинерию не перерисовывал и там они выделяются.
> 
> Я про все, что нельзя брать в руки. Если что-то нельзя взять, то его должно быть можно разобрать, думаю у тебя можно, чекать лень, но все равно спрашиваю.

А что из ПРа нельзя брать в руки?

2024-01-16 09:32 UTC, DarthSidiousPalpatine commented
Убрал усы и нижний аутлайн. У холодосов и кулеров оказалось я не делал нижний аутлайн. Знач и у микроволновок не будет. Чуть сузил крышку.
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/21008918/3e63ecb4-d058-4b55-bdb8-b7f913269f44)
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/21008918/7397c35e-b90a-49f5-aa40-a323c0e888dd)
https://youtu.be/3CVpmhD1zLk

2024-01-16 09:46 UTC, DarthSidiousPalpatine commented
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/21008918/87ef0d0a-44af-4c6c-aab6-ef895a8f77dc)

2024-01-17 08:51 UTC, DarthSidiousPalpatine commented
@UDaV73rus @WROTL нате, удалил ваши микрухи, холодосы и кулеры. ТЕПЕРЬ ТОЛЬКО ДЕКОР.

2024-01-18 14:28 UTC, DarthSidiousPalpatine commented
Ошарообразил спрайт глобусов.
Убрал деревянные статуэтки.
Убрал 5 лишних ваз.

2024-01-23 18:33 UTC, DarthSidiousPalpatine commented
Добавил тень под часами деревянными.
Добавил "рефлекс" или что-то похожее вазам.
Сократил размеры статуэток абстрактных.
Чуть добавил рельефа бюстикам.

@WROTL Обновил превью картинки в ПРе.

2024-01-27 22:09 UTC, DarthSidiousPalpatine commented
4 дня прошло снова

2024-01-28 21:43 UTC, DarthSidiousPalpatine commented
5 дней

2024-01-29 15:04 UTC, DarthSidiousPalpatine commented
Обновил статуэтки, сделал их меньше намного. Теперь они все вписываются в 11х16.

2024-01-29 15:56 UTC, DarthSidiousPalpatine commented
Обновил ещё раз статуэтки. Теперь они 9х11.

2024-01-30 08:57 UTC, DarthSidiousPalpatine commented
Обновил картинки в ПРе.

2024-01-30 10:01 UTC, DarthSidiousPalpatine commented
Обновил статуэтки, сделал полки в цвете столов, обновил превью ПРа.

2024-01-30 14:36 UTC, DarthSidiousPalpatine commented
Убрал аутлайн у полки.

Добавил хуешифтинга мб. Мб лучше стало, мб нет. Обновил превью ПРа.

2024-01-31 09:28 UTC, Deahaka requested changes
Независимо от красоты декора, изменения карты в ПРе — говно. И никто не остановит тебя от твоей цели именно украсить своим виденьем красоты бокс, даже если сделать это отдельным ПРом. Не вижу пользы для лично моих целей топить за всё это.

Лучше тогда требовать сделать идеально, чтобы не повторилась история с дирами для кабинетов и консоли грузторга

2024-02-17 04:37 UTC, volas commented
> Стикеры, полки, настольные глобусы, бюсты и 4 фигурки можно добавлять 

кто-то может тут помочь выбрать апрувнутое и залить отдельно

2024-02-17 19:25 UTC, DarthSidiousPalpatine commented
> > Стикеры, полки, настольные глобусы, бюсты и 4 фигурки можно добавлять
> 
> кто-то может тут помочь выбрать апрувнутое и залить отдельно

Рисовал я, а зальют другие. Ну-ну. Нахуй написал в Stalled PR-е? Теперь ещё 4 недели ждать закрытия.

2024-02-17 19:30 UTC, DarthSidiousPalpatine commented
Что тут кроме "стикеров, полок, глобусов, бюстов и 4 фигурок" интересн?

Настольные часы против которых вальтер, чью цитату, видимо, ты вкинул, против не как против спрайта, а как против предмета. Вазы с цветами, которые были аппрувнуты удавом, блять, а он тоже в спрайтдепе, ну и напольный глобус который действительно никто не аппрувнул. Т.е. "помочь выбрать аппрувнутое" это блять взять всё кроме напольного глобуса. Кретинизм.

Разберитесь сначала со своим спрайтдепом, один аппрувает, другой не аппрувает, если лично тебе, волас, важнее мнение вальтера, то удали нахуй остальных со спрайтдепа и переименуй его в вальтеродеп, брух.

2024-02-18 05:21 UTC, volas commented
тебя изначально просили разбить на отдельные пр-ы, твои возмущения не понятны.

2024-02-18 11:34 UTC, DarthSidiousPalpatine commented
> тебя изначально просили разбить на отдельные пр-ы, твои возмущения не понятны.

Вальтер такой: *Пихает в один ПР респрайт ящика для руды, пулевых отверстий стен и теней для столов*
Волас: "Всё в одной тематике ПРа, всё норм"

Гусев такой: *Пихает в один ПР 5 декор-вещей настольных*
Волас: "Гусев ну ты дебил всё разное разбей ПР"

2024-02-18 11:51 UTC, DarthSidiousPalpatine commented
Особенно топ, что респрайт столов с тенями под ними не позволял ударить челика под столом :dovolen:

2024-02-18 13:54 UTC, volas commented
Это другое, банально ПР-ы Вальтера не застревают на ревью месяцами. Тут тебя сразу спрайтеры забраковали, еще даже код никто не смотрел. Декомпозиция сложной задачи на мелкие, разбиение монолитного ПР-а на несколько - естественное решение, чтобы был какой-то оптимальный прогресс. Тут есть вещи, которые с момента открытия были готовы к мержу, но они в одной куче с вещами, которые возможно никогда не пройдут в мерж. Это тупиковая ситуация, и мы топчемся на месте уже два месяца непонятно зачем.

2024-02-18 14:04 UTC, DarthSidiousPalpatine commented
> сразу спрайтеры забраковали

Да я понял уже что удава ты и вальтер за спрайтера не считаете...

2024-02-18 14:05 UTC, DarthSidiousPalpatine commented
Напомню, в отличие от вальтера, удав не побрезговал сделать нормальный ревью почти сразу :dovolen:

2024-02-19 11:48 UTC, DarthSidiousPalpatine commented
ПР на 14 ликасов, супер-топ, все мапперы ждут декор, но Вальтеру же не нравится идея иметь настольные часы, уууу

2024-02-19 11:51 UTC, Tap0r commented
> ПР на 14 ликасов, супер-топ, все мапперы ждут декор, но Вальтеру же не нравится идея иметь настольные часы, уууу

Маперы мертвы
![ssIVJ1k_xlc.jpg](https://github.com/TauCetiStation/TauCetiClassic/assets/88531962/6ef16543-41e8-4bf5-88d4-fd45a073adca)

2024-02-20 07:05 UTC, Tap0r commented
Револь ушел за сигаретами и не вернулся

2024-02-22 11:34 UTC, DarthSidiousPalpatine commented
За год единственное что добавилось на Тау Кита нового - репликаторы от Людука. Больше никаких новых режимов, новых механик, ничего. Респрайты от Вальтера - полно. Фиксы багов - полно. ПРы а-ля "передвинул лампочку в бриге" - ещё больше. Даже балансоправок ебейшее количество. Но ничего нового не добавляется :dovolen:

Ясен пень, что нового добавить, когда даже 5 декоративных настольных предметов добавить 2 полных месяца не могут.
А с Погребком, новой механикой, что своей подсистемой открыла бы дорогу паре-тройке других моих ПРов - всё ахуеть как сложно, ведь надо сначала мозги выебать "Гисев сделай вот так с датумами", потом мозги выебать "ПР аппрувнут, тебе осталось только рецепты вернуть", а когда вернул - снова мозги начать ебать "нет гисев ты сделал всё не так, вообще ничего не делай я сам через 3 года по решению своей левой пятки, возможно, сделаю похожий механ и тогдаааааааа".


**Надо только подождать, там всё будет бесплатно, там всё будет в кайф. Там, наверное, вообще будет онлайн под 60!**

2024-02-22 11:59 UTC, volas commented
пока горишь, мог бы давно заборы доделать или этот пр разбить на части и начать мержить. Персистентность я тебе сделаю, но если честно, чем больше ты пишешь, тем меньше мне хочется бросить всё остальное и заняться ей.

2024-02-22 12:01 UTC, DarthSidiousPalpatine commented
> пока горишь, мог бы давно заборы доделать или этот пр разбить на части и начать мержить. Персистентность я тебе сделаю, но если честно, чем больше ты пишешь, тем меньше мне хочется бросить всё остальное и заняться ей.

Та лол, я сразу понял что ты просто напросто никогда не сделаешь континуити.

2024-03-19 22:47 UTC, closed without merging