после пришивания башки можно в реанимацию
TauCetiStation/TauCetiClassic pull request #12668
Opened 2024-01-02 14:56 UTC by AndroBetel

## Описание изменений
тайтл
## Почему и что этот ПР улучшит
это выпилили потому что абузеры пришивали бошки к куклам из генетики и обходили таймер смерти, я довёл это до ума и теперь все норм 
## Авторство
я
## Чеинжлог
:cl:
- tweak: Человека с пришитой головой снова можно реанимировать.

2024-01-02 14:56 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2024-01-02 15:28 UTC, AndroBetel commented
и мозг мможно

2024-01-02 16:27 UTC, pro100kotah commented
> ## Описание изменений
> тайтл
> 
> ## Почему и что этот ПР улучшит
> это выпилили потому что абузеры пришивали бошки к куклам из генетики и обходили таймер смерти, я довёл это до ума и теперь все норм
> 
> ## Авторство
> я
> 
> ## Чеинжлог
> 🆑
> 
> * tweak: Человека с пришитой головой снова можно реанимировать.

Пару вопросов. Можно ли пришить голову к кукле и реанимировать, если например, тело взорвалось или его не нашли?

Если да, что будет, если пришить или посадить мозги в куклу другой ксенорасы?

2024-01-02 16:30 UTC, AndroBetel commented
да и да

2024-01-05 11:53 UTC, WatlerJe commented
При пересаживании бошек, голова принимает спрайт тот что у тела или оставляет свой? Это в основном касается ксеносов.

2024-01-11 13:23 UTC, Chip11-n commented
Можно реанимировать пришитую голову после банки или борга?

2024-01-17 02:59 UTC, LudwigVonChesterfield commented on code/modules/surgery/braincore.dm
> +		ADD_TRAIT(target, TRAIT_NO_CLONE, GENERIC_TRAIT) // so they cannot be cloned
Интересно нужно ли квирки передавать.

2024-01-17 08:05 UTC, volas commented
выпилили же еще и абузеров, кто пересаживал мозг в куклы ксеносов и обходил вайтлист/играл человека-таяру.

Какой смысл тут еще в изменении?

2024-01-17 08:07 UTC, volas requested changes
чувствую, это какой-то шаг назад, у ПР-а плохое описание и не пролинканы предыдущие по теме. Пока не мержить.

2024-01-21 21:02 UTC, AndroBetel commented
>выпилили же еще и абузеров, кто пересаживал мозг в куклы ксеносов и обходил вайтлист/играл человека-таяру.

мне например непонятно почему из-за вайтлиста который выдаётся буквально за минутки обязательно ограничивать ролеплей и собственно интересные механики!

2024-01-21 21:11 UTC, AndroBetel commented
https://github.com/TauCetiStation/TauCetiClassic/pull/8233/files
вот пр который изменял то что и я
ни слова про ксеносов! значит, задачи запретить рпшить людям за таяр не стояло, а лишь пофиксить абуз с бесконечной реанимацией
я его пофиксить, рпшить за людей в теле таяр снова можно (и в этом нет ничего плохого!)

2024-01-21 22:32 UTC, LudwigVonChesterfield commented
Оставлю здесь идею, что пофиксить фигню с ролеплеем за ксеносам можно тем

Что если у человека нет вайтлиста на ксеноса то тело ксеноса гарантированно отторгает его мозг.

2024-01-22 18:57 UTC, volas commented
>  ни слова про ксеносов! значит, задачи запретить рпшить людям за таяр не стояло, а лишь пофиксить абуз с бесконечной реанимацией

значит это обсуждалось в дискорде, проблема была что люди обходили вайтлист и возможно даже баны, а потом (что более критично) играли за ксеносов с валидной IC-причиной не отыгрывать ксеносов, это кринж и только портит впечатление от игры когда перед тобой ксенос положивший на свой бэк а ты не знаешь, мудак он с причиной, или без.

2024-01-22 18:58 UTC, AndroBetel commented
ну лан как скажешь

2024-01-22 18:58 UTC, closed without merging