Обновление дока 42
TauCetiStation/TauCetiClassic pull request #12678
Opened 2024-01-04 22:53 UTC by Venngedi

## Описание изменений
| Было  | Стало |
| ------------- | ------------- |
| ![Было](https://github.com/TauCetiStation/TauCetiClassic/assets/135035236/b48435ab-70af-4c38-999f-2017bc1c72a9) | ![Стало](https://github.com/TauCetiStation/TauCetiClassic/assets/135035236/eae6454a-d99b-4b6d-8db0-1753f60fe8a3)  |
| ![БылоМусорка](https://github.com/TauCetiStation/TauCetiClassic/assets/135035236/bca7844f-d76a-431a-b0c9-630697722cd3) | ![СталоМусорка](https://github.com/TauCetiStation/TauCetiClassic/assets/135035236/b69209d1-526e-4410-8468-15464cd31abc) |
| ![БылоТуалет](https://github.com/TauCetiStation/TauCetiClassic/assets/135035236/7bc3c86a-fe76-408c-b39a-924289fed18c) | ![СталоТуалет](https://github.com/TauCetiStation/TauCetiClassic/assets/135035236/27fecd88-454d-4a6b-97bb-d196e78a1698) |
| ![БылоКарго](https://github.com/TauCetiStation/TauCetiClassic/assets/135035236/1268dc68-5e96-4940-b7a6-162e30a58144) | ![СталоКарго](https://github.com/TauCetiStation/TauCetiClassic/assets/135035236/aac34bb5-57aa-4846-a9cb-3de460e96f03) |

А ещё 

- Полностью удалил рикрол. Он ничего не делал, да и мем уже баян.
- Подправил зоны.
- Поставил барьеры так, чтобы они защищали док 42 от обычных игроков, а не от офицеров.
- Исправил иконки. На игру это не влияет.
- Поставил доступ там, где его не было.
- Переложил плитку

Планирую добавить новый звук. Сейчас там стоит заглушка. Точно успею, пока буду ждать ревью от мапперов...
## Почему и что этот ПР улучшит
close #4560 и _естетическое_ удовольствие
## Авторство

## Чеинжлог
:cl:
 - map: Небольшое обновление НТС Велосити.

2024-01-04 22:53 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2024-01-04 23:22 UTC, Tap0r commented
Хуй его знает зачем это, но ладно...

2024-01-05 01:53 UTC, KatoMarika commented
По мап-дифф боту были задеты спецшатл синдиката и база нюки. 
Требуется оградить зону вокруг Велосити или убрать выход в спейс в избежание попадания в другие места на слое при проведении ивента связанных с Велосити. 
Вернуть проход к погрузке шатла. Связано с мемными моментами отправки особых ассистух через шатл карго. 
Ну и конечно ансим турфы вернуть желательно.

2024-01-05 14:29 UTC, Venngedi commented
> Требуется оградить зону вокруг Велосити или убрать выход в спейс в избежание попадания в другие места на слое при проведении ивента связанных с Велосити.

Ты про это место? Тут же блоквеи стоят
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/135035236/b39bdd27-ba49-4342-b8c9-dfa15e08140f)

2024-01-05 14:36 UTC, KatoMarika commented
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/18484142/81e1cdad-f36c-4efa-99d7-27014ed50b8e)
Тут. Достаточно пары инструментов.

2024-01-05 14:46 UTC, Venngedi commented
> ![image](https://private-user-images.githubusercontent.com/18484142/294523932-81e1cdad-f36c-4efa-99d7-27014ed50b8e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0NjU2OTIsIm5iZiI6MTcwNDQ2NTM5MiwicGF0aCI6Ii8xODQ4NDE0Mi8yOTQ1MjM5MzItODFlMWNkYWQtZjM2Yy00ZWZhLTk5ZDctMjcwMTRlZDUwYjhlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA1VDE0MzYzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA2NzhiODFjOWI4NjYzYjM1NjhiYTAwZDYxNjI5NDZhMjYyMWRlMWY3NzdmZThiZWRjZmVlZmU3YWEzYWQ5MmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FRrF5_BhbxHZ89HoDPOHpzosRaK-_uAiQrgbc7Qk7Hk) Тут. Достаточно пары инструментов.

Тут стоит `reinforced/indestructible`. Без помощи админов это окно не проломить

2024-01-06 08:07 UTC, KatoMarika commented
> > А ты пробовал стыковать шаттл карго? Или он у тебя развернется, если тот прилетит на Велосити?
> 
> Системы шаттлов нет. Как он стоит на станции, так и будет стыковаться

Вот это еще исправить (Вернуть подход к входу в шатол, а не написать систему шатлов) и с моей стороны вопросов нет.

2024-01-06 21:06 UTC, muWander commented
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/39914744/bb51c410-2b52-4244-bf62-10ce4b8d2737)
тут unsim пол под мусорку попал

2024-01-06 23:01 UTC, Venngedi commented
@KatoMarika @muWander Спасибо за ревью

2024-01-07 15:31 UTC, Venngedi commented
Обновил скрины и описание

2024-01-10 10:35 UTC, Chip11-n commented
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/50750952/9f0513bd-b16e-4a11-8d71-7a5a54b6cd68)

Да, попасть на велосити абуз сам по себе, и это смешно, но создавать их на ровном месте тоже не стоит.

2024-01-10 11:31 UTC, KatoMarika commented
Там ниже барьерами закрыто, а шатл с хуманом не отправляет со станции.

2024-01-10 12:08 UTC, volas commented
> Заменил блокеры на невидимые блоквеи.

чем отличаются от лейбла? они где-то еще используются? можно ли убрать из билда тогда?

2024-01-10 12:13 UTC, volas requested changes
^

2024-01-10 12:20 UTC, volas commented
ну и сдвоенный туалет это отсылка на сочинскую олимпиаду, жаль терять

2024-01-10 18:43 UTC, Venngedi commented
> > Заменил блокеры на невидимые блоквеи.
> 
> чем отличаются от лейбла? они где-то еще используются? можно ли убрать из билда тогда?

Это `/obj/effect/forcefield` с изменённым названием и описанием. Под окнами они убраны совсем, а под авто поставлены блоквеи
![Костыль](https://github.com/TauCetiStation/TauCetiClassic/assets/135035236/0371368c-ad5c-430f-bff6-d3bf125b3a33)
![Костыль нью едишен](https://github.com/TauCetiStation/TauCetiClassic/assets/135035236/b3bc5c7e-32cf-48e8-a3e0-967ee767bd02)

> я вспомнил, один переключается кнопкой у педалей, другой нет. Если педаль разрешает доступ, то обычно по хождению по велосити, а не вылетать за пределы велосити

Всё верно. Вот только новый способ вылезти за пределы дока и полетать по слою я не добавлял. Три центком барьера "переехали" поближе к КПП и 1 возле карго удалён. Эти изменения не помогут украсть мехи с базы ОБР
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/135035236/40e868d3-9130-4be6-bb9a-bb86bac0a1c8)

2024-01-13 21:43 UTC, Venngedi commented
> ну и сдвоенный туалет это отсылка на сочинскую олимпиаду, жаль терять

![image](https://github.com/TauCetiStation/TauCetiClassic/assets/135035236/82c1b8ba-5c7b-4284-aef8-52bd0e0407c3)

2024-01-17 08:30 UTC, volas commented
> Три центком барьера "переехали" поближе к КПП

вот, как раз, это было фичей, что снизу двери всё таки можно было немножко взломать и немного прогуляться

2024-01-29 03:57 UTC, volas approved these changes
думаю, тут будут конфликты с #12624, пока блокируется тем пр-ом. А так всё ок.

Только что, кольцо зачем-то на плакате вернулось, не любишь ты отсылки

2024-01-29 04:01 UTC, volas commented on code/modules/admin/admin_verbs.dm
> +		to_chat(usr, "<span class='notice'><b><font size=3>Never Gonna Give You Up.</font></b></span>")
```suggestion
	to_chat(usr, "<span class='notice'><b><font size=3>Never Gonna Give You Up.</font></b></span>")
```

2024-01-29 16:45 UTC, Venngedi commented
> Только что, кольцо зачем-то на плакате вернулось, не любишь ты отсылки

Я вернул отсылку на нераскрывшееся кольцо. Остался только один вопрос: верхние кольца должны быть овальными?

2024-01-31 17:41 UTC, LudwigVonChesterfield commented
в принципе, как и ожидалось, возникли конфликты из-за перевода.

2024-01-31 20:09 UTC, LudwigVonChesterfield commented
Я оставлю мнение от себя, но не могу блочить ПР.

![image](https://github.com/TauCetiStation/TauCetiClassic/assets/17705613/a6859e56-d147-49d4-9cd4-e87e77d5be8a)

Мне нравится что там были *теха*, с теха-плиткой.

![image](https://github.com/TauCetiStation/TauCetiClassic/assets/17705613/5439ab75-9c1b-4de0-b5f8-c0f2a3f1ab25)

Мне плитка слева кажется смешнее и ламповее, но я понимаю что у нас для туалетов другой интерьер.

2024-01-31 20:35 UTC, Venngedi commented
> Мне нравится что там были _теха_, с теха-плиткой.

Нет такой плитки, которая может одновременно сохранить и техи, и разницу в высоте. А так бы я оставил там техническое помещение

2024-02-01 01:01 UTC, Lexakr commented
Туалет загрифонили просто по приколу, лол. Продублирую из ДС:
Было компактно ещё и с разделением на 2 комнаты

Стал пиздец ангар с каким то ебаным стеклом, овердозингом плакатов и нахуй не нужной комнатой со шваброй

Ну и плитка слева тоже как то прикольнее там выглядела

2024-02-01 01:04 UTC, Lexakr commented
Ещё и рикролл убил зачем-то, ну да ну да, пошел он нахер

2024-02-01 03:49 UTC, Venngedi commented
> Ещё и рикролл убил зачем-то, ну да ну да, пошел он нахер

Описание не обновил. Днём уберу пару строк

2024-02-10 13:28 UTC, merged