Перевод органов(падежи)
TauCetiStation/TauCetiClassic pull request #12716
Opened 2024-01-13 11:03 UTC by AzzyDreemurr13

## Описание изменений
Добавление перевода органов для устранения проблем начиная от МРТ Сканера до активных ПРов на тему перевода медицины 
## Почему и что этот ПР улучшит
Больше перевода богу перевода
## Авторство
[Fenriros](https://github.com/Fenriros)
## Чеинжлог
:cl: Fenriros
- ru: Перевод органов на русский язык

2024-01-13 11:03 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2024-01-13 11:20 UTC, Kiromaka requested changes

2024-01-13 11:20 UTC, Kiromaka commented on code/modules/organs/organ_internal.dm
> +	cases = list("Помпа системы охлаждения", "Помпы системы охлаждения", "Помпе системы охлаждения", "Помпу системы охлаждения", "Помпой системы охлаждения", "Помпой системы охлаждения")
```suggestion
	cases = list("помпа системы охлаждения", "помпы системы охлаждения", "помпе системы охлаждения", "помпу системы охлаждения", "помпой системы охлаждения", "помпой системы охлаждения")
```

2024-01-13 11:20 UTC, Kiromaka commented on code/modules/organs/organ_internal.dm
> +	cases = list("Позитронный мозг", "Позитронного мозга", "Позитронному мозгу", "Позитронный мозг", "Позитронным мозгом", "Позитронном мозге")
```suggestion
	cases = list("позитронный мозг", "позитронного мозга", "позитронному мозгу", "позитронный мозг", "позитронным мозгом", "позитронном мозге")
```

2024-01-13 11:22 UTC, Kiromaka commented
> Киромака вспомнил, что у него репозиторий трансдепа? :peka:

да саджестами фиксить проще, гитдесткоп лень открывать, а codespace в браузере хуйня.

2024-01-13 13:51 UTC, AndroBetel commented on code/modules/organs/organ_external.dm
> +	cases = list("паховая область", "паховой области", "паховой области", "паховую область", "паховой областью", "паховой области")
Иван Иванов бьёт Джона Джонсона дубинкой по ПАХОВОЙ ОБЛАСТИ.

2024-01-17 08:38 UTC, volas commented on code/modules/organs/organ_internal.dm
> +	cases = list("полая ветка", "полой ветки", "полой ветки", "полую ветку", "полой веткой", "полой ветке")
это латинский, возможно не стоило переводить

2024-01-17 08:39 UTC, volas commented on code/modules/organs/organ_internal.dm
> +	cases = list("полая ветка", "полой ветки", "полой ветки", "полую ветку", "полой веткой", "полой ветке")
впрочем почему латинский вдруг использовался тоже не ясно

2024-01-17 08:40 UTC, merged