Небольшие корректировки церкви на Дельте
TauCetiStation/TauCetiClassic pull request #12721
Opened 2024-01-14 07:24 UTC by maleyvich

## Описание изменений
в комнаты церкви добавлены light switch-и, алтарь переместился из комнаты священника в соседнюю комнаты прощаний, сама она немного изменилась. коморка стала визуально шире.
## Почему и что этот ПР улучшит
более комфортный геймплей священника на дельте?
## Авторство
maleyvich
## Чеинжлог
:cl: Maleyvich
- map: В церковь Дельты внесены небольшие корректировки.

2024-01-14 07:24 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2024-01-14 07:43 UTC, maleyvich commented
![StrongDMM-2024-01-14 13 42 57](https://github.com/TauCetiStation/TauCetiClassic/assets/104298869/6495323f-6bd8-460a-a22c-334294f19610)
основные изменения отображены на картинке.

2024-01-14 09:40 UTC, maleyvich commented
флора перед алтарём была убрана

2024-01-14 09:59 UTC, KatoMarika commented
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/18484142/981714f2-eadc-42d2-8834-3de286d58b38)
Подправь, там лишний фаерлок

2024-01-14 10:17 UTC, maleyvich commented
> ![image](https://private-user-images.githubusercontent.com/18484142/296542131-981714f2-eadc-42d2-8834-3de286d58b38.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUyMjY2NDMsIm5iZiI6MTcwNTIyNjM0MywicGF0aCI6Ii8xODQ4NDE0Mi8yOTY1NDIxMzEtOTgxNzE0ZjItZWFkYy00MmQyLTg4MzQtM2RlMjg2ZDU4YjM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE0VDA5NTkwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUxMzI0YjI3NTIzNzU4YTBiMmExZjRkZjU2NDQ5ZDVkNDk5YjZjNmRiN2M3NzdmYWM0Y2VlNzQ3ZjQ5ZDY1M2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.b-s726TqPuTqGDvn_u7Y7vk-EegZFY_5Y6qrI7op3A8) Подправь, там лишний фаерлок

исправлено

2024-01-14 10:35 UTC, KatoMarika commented
Я в дисе написал, но ты видимо не заметил. 
Еще трубы надо подправить, там не хватает куска трубы на скрубере и самого скрубера.

2024-01-14 19:15 UTC, Deahaka commented
![1](https://github.com/TauCetiStation/TauCetiClassic/assets/96499407/2b3bf254-d5e9-4832-a800-9a1800702d15)
многа.
![2](https://github.com/TauCetiStation/TauCetiClassic/assets/96499407/d2673dae-8ee3-4cbd-96d1-2666e05c399c)
не разделяй стол без нужды, нужды тут нет.
![3](https://github.com/TauCetiStation/TauCetiClassic/assets/96499407/5c22c128-8c62-4317-8ca4-c25a6876491b)
### Нахуй это, верни откуда взял.
![4](https://github.com/TauCetiStation/TauCetiClassic/assets/96499407/90ac841d-13c1-4edf-afcc-4526752c9f9e)
Мало.
![5](https://github.com/TauCetiStation/TauCetiClassic/assets/96499407/192459d4-0c2b-4330-b156-44999409018f)
Верни.
![6](https://github.com/TauCetiStation/TauCetiClassic/assets/96499407/9d56fc16-4659-4ecd-9ef3-94ef09d8938c)
Куда ты её дел?

2024-01-15 05:56 UTC, maleyvich commented
лишние лампы у священника убрал, лайтсвич со стола убрал и заменил его на библию, в комнату переговоров добавил лампочку а пока мне не обьяснят почему ЧЕТЫРЕ лампочки в крематории это норма и почему автомат для оплаты должен лежать в ШКАФЧИКЕ С ОДЕЖДОЙ я не буду это менять

2024-01-15 06:50 UTC, maleyvich commented
> Я в дисе написал, но ты видимо не заметил. Еще трубы надо подправить, там не хватает куска трубы на скрубере и самого скрубера.

исправлено

2024-01-15 20:38 UTC, Chip11-n commented
У меня то ли бот багнулся, то ли ещё что. Посмотри ещё раз трубы скраббера в общем помещении церкви они почему-то заворачивают на юг.

2024-01-16 02:17 UTC, maleyvich commented
> У меня то ли бот багнулся, то ли ещё что. Посмотри ещё раз трубы скраббера в общем помещении церкви они почему-то заворачивают на юг.

все так и должно быть, трубы на дельте присоединены хуй пойми как и из за этого мне пришлось доделывать их в церкви, мб выглядит странно но необходимл

2024-01-22 22:59 UTC, LudwigVonChesterfield commented
алтарь нельзя в свободный доступ его свинтить можно

2024-01-28 12:38 UTC, Chip11-n commented
С трубами скраббера что-то не то.

2024-01-28 13:15 UTC, Deahaka commented
По последним изменениям ещё добавлю ревью
### Голопад плохо расположен
![11](https://github.com/TauCetiStation/TauCetiClassic/assets/96499407/a00e814c-b445-4d0b-9dea-ebdb007d8ad4)
### Плитка перестала выполнять какой-либо план, надо убрать
![12](https://github.com/TauCetiStation/TauCetiClassic/assets/96499407/8efbc3c6-ec21-4453-a2f2-1d59f832f954)
### Это что за монстр?
![13](https://github.com/TauCetiStation/TauCetiClassic/assets/96499407/c2c64074-955f-4207-9dfe-6aef736babdf)
### Это что за монстр?
![14](https://github.com/TauCetiStation/TauCetiClassic/assets/96499407/bcc29dca-a116-47b1-b56f-7988bfc002ec)

2024-01-28 13:16 UTC, Deahaka requested changes
Если ещё собираешься доделывать до мержа, то выше все сообщения актуальны.

2024-01-29 04:22 UTC, volas commented
почему альтар вообще в спальне священника? там много места и космос рядом, можно скорее всего комнату как на том же боксе сделать

2024-01-29 04:22 UTC, volas requested changes
выше много комментариев

2024-01-29 04:57 UTC, Deahaka commented
> почему альтар вообще в спальне священника?

Прошлый священник был из Японии, а там синтоизм или что-то такое, алтари в маленькой комнатке возле спальни. Секретный лор Дельты! (Откручивай и ставь где за милую душу будет)

2024-01-31 09:43 UTC, maleyvich commented
плитку убрал голопад переставил трубу переставил
не пойму только в чем проблема на третьем скриншоте!

2024-02-01 10:05 UTC, Deahaka commented
Обнови скриншот и так чтобы затрагивало всю площадь изменений

2024-02-01 10:21 UTC, maleyvich commented
> Обнови скриншот и так чтобы затрагивало всю площадь изменений

готово

2024-02-01 10:29 UTC, Deahaka commented
Посмотри на скриншот, который ты добавил. Как думаешь, там нужно что-то поменять?

И обнови второй, он не актуален

2024-02-01 10:56 UTC, maleyvich commented
> Посмотри на скриншот, который ты добавил. Как думаешь, там нужно что-то поменять?
> 
> И обнови второй, он не актуален

что нужно поменять я уже поменял, а второй скриншот актуальный и на нем просто то что не вместится нормально на одном

2024-02-01 12:26 UTC, Deahaka commented
Ладно, прошу тебя поклацать
ДО
https://affectedarc07.blob.core.windows.net/mdb2/images/55870442/21055780457/m/maps_delta_delta/0-before.png
и ПОСЛЕ
https://affectedarc07.blob.core.windows.net/mdb2/images/55870442/21055780457/m/maps_delta_delta/0-after.png

и найти то что ты не заметил

2024-02-09 09:40 UTC, Deahaka commented
Скриншоты в шапке устарели, обнови

2024-02-09 09:44 UTC, Deahaka commented
Кроме недоработок, ещё в коморке стоит свапнуть клозет между столами с комодом (дрессером), а лишние два стола, которые я писал выше не стоит разделять с теми что под ними, убрать просто.

2024-03-01 11:16 UTC, closed without merging