Чиним исчезающие спрайты соусов.dm
TauCetiStation/TauCetiClassic pull request #12735
Opened 2024-01-18 16:33 UTC by Ayaksblack

## Описание изменений
Добавил проверку на наличие пустого спрайта, прежде чем менять стейт и иконку на пустую.

## Почему и что этот ПР улучшит
Кондименты без нарисованных пустых иконок перестанут терять спрайт

## Авторство
Ayaksblack
[Chip11-n](https://github.com/Chip11-n) консультировал

## Чеинжлог
:cl:
 - bugfix: Пофикшено исчезание бутылки перца, острого и холодного соуса и баклажки масла

-->

2024-01-18 16:33 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2024-01-19 01:56 UTC, AirBlack commented
closes #12682

2024-01-19 01:58 UTC, AirBlack approved these changes
можешь еще глянуть в спрайтах реагентов отдельные спрайты дупликаты где _empty вариант идентичен обычному и удалить

2024-01-19 05:24 UTC, AirBlack requested changes

2024-01-19 05:24 UTC, AirBlack commented on code/modules/reagents/reagent_containers/food/condiment.dm
> +	if(!reagents || (reagents && !reagents.reagent_list.len) && ("[initial(icon_state)]_empty" in icon_states(icon)))
```suggestion
	if((!reagents || (reagents && !reagents.reagent_list.len)) && ("[initial(icon_state)]_empty" in icon_states(icon)))
```

2024-01-19 05:24 UTC, AirBlack commented on code/modules/reagents/reagent_containers/food/condiment.dm
> +	if(!reagents || (reagents && !reagents.reagent_list.len) && ("[initial(icon_state)]_empty" in icon_states(icon)))
не заметил, вроде как во всех языках приоритет логического И выше логического ИЛИ(учитывая что ИЛИ это сложение логическое а И это умножение), так что в твоем случае если !reagents сработает то проверка на стейт не сработает и он поставит эмпти

2024-01-19 05:24 UTC, AirBlack commented on code/modules/reagents/reagent_containers/food/condiment.dm
> +	if(!reagents || (reagents && !reagents.reagent_list.len) && ("[initial(icon_state)]_empty" in icon_states(icon)))
ну и хз по оверхеду проверки наличия этого стейта во всех стейтах иконки(а их может и по сотне быть и хз насчет сложности in) на каждое изменение реагентов, пусть ментейнеры ответят, но вроде ебать не должно

2024-01-19 06:51 UTC, Ayaksblack commented
Тусовка А...блек'ов

Спасибо, что упомянул ишью. Я чот не додумался посмотреть туда сперва.

Не понял, про какие спрайты ты. Там лишних нет как раз. Если бы там был дубликат перечницы с _empty то проблемы бы как раз с потерей спрайта не было бы
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/136359501/2d456d07-919d-4f95-afc3-8cc4a223febe)

По поводу скобки и оператора in - я хз: я нубик. Пусть, кто поумнее скажет. Похожую структуру пикачушка исользовал с аксесуарами. Плюс, у кондиментов свой файл со спрайтами, так что едва ли тут проблема будет. Но я открыт к предложениям, если что. Сначала хотел делать проверу на item_state в var'ах банок, но не справился ни с '!=' ни с 'in vars'

2024-01-19 07:19 UTC, AirBlack commented
а я помнил просто что соль не пропадала но из-за того что спрайт мелкий я визуально различий не видел и думал что как минимум солонка _empty дупликат, думал может еще такое будет, но вижу что нет, так что ок.

2024-01-19 21:47 UTC, LudwigVonChesterfield requested changes
Я бы предпочёл чтобы у баночек была переменная определяющая их пустой спрайт.

Для тех баночек у которых нет пустого спрайта эта переменная совпадала бы с наполненным спрайтом.

2024-01-21 10:28 UTC, Ayaksblack commented
> Я бы предпочёл чтобы у баночек была переменная определяющая их пустой спрайт.
> 
> Для тех баночек у которых нет пустого спрайта эта переменная совпадала бы с наполненным спрайтом.

Так лучше? Пикачушная структура была красивше имхо, но если чеков "in" файла с иконками желательно избежать для такой мелочи, то воть.

2024-01-21 17:42 UTC, LudwigVonChesterfield commented on code/modules/reagents/reagent_containers/food/condiment.dm
> +	emptystate = 0
надо выбрать `null` или `""`.

0 подразумевает что у нас целочисленное значение, а эта переменная строка.

2024-01-21 17:43 UTC, LudwigVonChesterfield commented on code/modules/reagents/reagent_containers/food/condiment.dm
> +	var/emptystate = "condiment"
я бы предпочёл чтобы эта переменная по дефолту была null-ом, чтобы если нет картинки не надо было писать emptystate = null

2024-01-21 17:44 UTC, LudwigVonChesterfield commented on code/modules/reagents/reagent_containers/food/condiment.dm
> +	if((!reagents || (reagents && !reagents.reagent_list.len)) && (emptystate != 0))
```
if(emptystate && (!reagents || reagents.total_volume <= 0))
```

2024-01-25 19:00 UTC, Ayaksblack commented on code/modules/reagents/reagent_containers/food/condiment.dm
> +	var/emptystate = "condiment"
Соре, я не погиб; меня ирл затянуло.

Как тогда это задать? Как сейчас вроде работает. Если сделать var/emptystate = null на 40ой строчке, то он будет у всех кондиментов по дефолту нулем, да. Но сама бутылка condiment, которая выпадает из химмастера перестанет опустошаться

2024-01-31 04:58 UTC, volas commented on code/modules/reagents/reagent_containers/food/condiment.dm
> +	var/emptystate = "condiment"
без изменения иерархии объектов никак. Кто-то может быть споткнется об опциональное выключение, но сюда не часто лазят и можно потерпеть.

2024-02-04 04:05 UTC, AirBlack commented
эх вот бы пофиксили поскорее, вчера опять пропал перец, ладно хоть я додумался альт кликом найти и заполнить

2024-02-06 09:55 UTC, Ayaksblack commented
Попытка номер три

2024-02-06 17:53 UTC, LudwigVonChesterfield approved these changes

2024-02-09 07:03 UTC, Chip11-n approved these changes
Через 2 часа буду мержить.

2024-02-09 13:56 UTC, AirBlack commented
7 часов прошло @Chip11-n

2024-02-09 14:25 UTC, merged

2024-02-24 17:49 UTC, Ayaksblack commented
сука, теперь я инхэнды сломал у соусов
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/136359501/685d6a2f-f220-4ba2-aaab-ca10fdf7b227)