Корректировка перевода и добавка падежей
TauCetiStation/TauCetiClassic pull request #12770
Opened 2024-01-25 18:09 UTC by AzzyDreemurr13

## Описание изменений
Небольшая корректировка готовых переводов
Resolves https://github.com/TauCetiStation-TranslationDepartment/TauCetiClassic/issues/23
## Почему и что этот ПР улучшит
Устранения английского и неправильного переведенного перевода в прошлом.
А также смерть Поак Поак у курицы.
## Авторство
Я

## Чеинжлог

:cl: Azzy.Dreemurr
 - ru: Корректировка перевода мед оборудования и добавления в них переведённых органов
 - spellcheck: Курица заговорит по-русски

2024-01-25 18:09 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2024-01-25 19:30 UTC, Kiromaka commented
Поак поак поак

2024-01-26 16:36 UTC, Chip11-n commented on code/modules/atmospheric/machinery/components/unary_devices/cryo.dm
> +		ui = new(user, src, "Cryo", "Криокапсула")
Я не могу сказать что конкретно может от этого сломаться. Поэтому спрошу: А так ли нужно это переводить?

2024-01-26 19:19 UTC, Kiromaka commented
Убери пожалуйста все тавтологии - "МРТ сканер".

2024-01-26 19:20 UTC, Kiromaka requested changes
И было бы неплохо, найти еще упоминания МРТ сканера.

2024-01-28 11:37 UTC, Chip11-n commented on code/__HELPERS/mobs.dm
> +					message += "<span class='warning'>Обнаружен незафиксированный перелом в [capitalize(CASE(BP, NOMINATIVE_CASE))]. При транспортировке рекомендуется наложение шины.</span><br>"
Тут `capitalize()`, т.е. большая буква так и задумана?

2024-01-28 11:37 UTC, Chip11-n commented on code/__HELPERS/mobs.dm
> +				message += "<span class='warning'>Обнаружена инфекция в [capitalize(CASE(BP, NOMINATIVE_CASE))]. Рекомендуется дезинфекция.</span><br>"
capitalize() так и задуман?

2024-01-28 11:37 UTC, Chip11-n commented on code/game/machinery/adv_med.dm
> +	var/datum/browser/popup = new(user, "window=scanconsole", (capitalize(CASE(src, NOMINATIVE_CASE))), 530, 700, ntheme = CSS_THEME_LIGHT)
```suggestion
	var/datum/browser/popup = new(user, "window=scanconsole", (CASE(src, NOMINATIVE_CASE), 530, 700, ntheme = CSS_THEME_LIGHT)
```

2024-01-28 11:54 UTC, Chip11-n commented on code/game/machinery/adv_med.dm
> +	var/datum/browser/popup = new(user, "window=scanconsole", (capitalize(CASE(src, NOMINATIVE_CASE))), 530, 700, ntheme = CSS_THEME_LIGHT)
Внутри мы уже делаем его с большой буквы
```
/datum/browser/New(nuser, nwindow_id, ntitle, nwidth, nheight, atom/nref, ntheme = CSS_THEME_DARK)
   ...
	if(ntitle)
		title = capitalize(ntitle)
```

2024-01-28 12:27 UTC, Chip11-n commented on code/game/machinery/adv_med.dm
> +	var/datum/browser/popup = new(user, "window=scanconsole", (CASE(src, NOMINATIVE_CASE)), 530, 700, ntheme = CSS_THEME_LIGHT)
```suggestion
	var/datum/browser/popup = new(user, "window=scanconsole", CASE(src, NOMINATIVE_CASE), 530, 700, ntheme = CSS_THEME_LIGHT)
```

2024-01-29 04:50 UTC, volas approved these changes
``capitalize(CASE())`` можно отдельно задефайнить, если часто требуется, какой-нибудь CCASE

2024-02-02 13:20 UTC, Kiromaka requested changes

2024-02-02 13:20 UTC, Kiromaka commented on code/__HELPERS/mobs.dm
> +					message += "<span class='warning'>Обнаружен незафиксированный перелом в [CASE(BP, NOMINATIVE_CASE)]. При транспортировке рекомендуется наложение шины.</span><br>"
перелом в РУКА/НОГА ? Падеж поменяй

2024-02-02 13:20 UTC, Kiromaka commented on code/__HELPERS/mobs.dm
> +				message += "<span class='warning'>Обнаружена инфекция в [CASE(BP, NOMINATIVE_CASE)]. Рекомендуется дезинфекция.</span><br>"
same

2024-02-02 13:28 UTC, Kiromaka commented
там предложный падеж

2024-02-02 13:36 UTC, maleyvich requested changes

2024-02-02 13:36 UTC, maleyvich commented on code/__HELPERS/mobs.dm
> -			message += "<span class='warning bold'>Внимание: Уровень крови НИЗКИЙ: [blood_percent]% [blood_volume]сл.</span><span class='notice'>Группа крови : [blood_type]</span><br>"
мне кажется лучше "Внимание: критический уровень крови."

2024-02-02 13:36 UTC, maleyvich commented on code/__HELPERS/mobs.dm
> +			message += "<span class='warning bold'>Внимание: Уровень крови НИЗКИЙ: [blood_percent]% [blood_volume]сл.</span><span class='notice'>Группа крови: [blood_type]</span><br>"
аналогично выше

2024-02-02 13:36 UTC, maleyvich commented on code/__HELPERS/unsorted.dm
> +			return "Левая рука"
точно ли здесь надо писать названия конечностей с большой буквы? если нет то пох

2024-02-02 13:36 UTC, maleyvich commented on code/game/machinery/adv_med.dm
> +					var/organ_damage_text = IO.damage > 0 ? "<span class='red'>[capitalize(CASE(IO, NOMINATIVE_CASE))]</span>" : "-/-"
не понимаю сути изменения, вместо демейджа будет просто писать падеж IO

2024-02-02 13:50 UTC, Kiromaka approved these changes

2024-02-02 13:57 UTC, maleyvich approved these changes

2024-02-02 13:57 UTC, maleyvich commented on code/__HELPERS/mobs.dm
>  		message += "<span class='notice'>Обнаруженные повреждения, Механические/Термические:</span><br>"
стоп не касается изменений пра, но почему здесь Механические/Термические с большой буквы? а так всё норм.

2024-02-04 14:19 UTC, Chip11-n commented on code/__HELPERS/unsorted.dm
> +			return "Левая рука"
Ты куда-то полез уж слишком глубоко. Этот прок используется в 48 случаях по всему билду. В идеале сделать `parse_zone_ru()`, где ты уже будешь делать всё, что хочешь.

> to_chat(src, "<span class='userdanger'>You've been shot in the **[parse_zone(def_zone)]** by the [P.name]!</span>")

И большая буква не канает.

2024-02-07 18:09 UTC, Chip11-n approved these changes
Если ни у кого не возникает вопросов, а вопрос с заглавной буквой будет решён, мержу через сутки.

2024-02-07 18:09 UTC, Chip11-n commented on code/__HELPERS/unsorted.dm
> +
Здесь оставляешь заглавную букву? 

У тебя во всех случаях использования прока используется капиталайз, но и тут с большой. В последующих ПРах если кто будет использовать - скорее всего будет менять.

2024-02-07 18:09 UTC, Chip11-n commented on code/game/machinery/adv_med.dm
> +						storedinfo += "<td>[capitalize(parse_zone_ru(BP.body_zone))]</td><td>-</td><td>-</td><td>Не обнаружено</td>"
К комментарию выше.

2024-02-08 17:38 UTC, merged