[WIP]Фикс #4941 и перевод останков
TauCetiStation/TauCetiClassic pull request #12796
Opened 2024-02-01 14:36 UTC by AzzyDreemurr13

## Описание изменений
resolve #4941 , вместе с фиксом перевёл останки для людей, ксеносов и роботов.

## Почему и что этот ПР улучшит
Фиксим старый баг с останками и за одно переводим их, 2в1!

## Авторство
Я

## Чеинжлог
:cl: Azzy.Dreemurr
 - bugfix: Исправлено неправильное описание сгоревших останков у ксено рас 
 - ru: Останки получили перевод на русский язык

2024-02-01 14:36 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2024-02-01 15:14 UTC, Naroke commented
К чему вообще сообщение об ауре? Что это за аура?

2024-02-01 15:58 UTC, Kiromaka approved these changes
approved

2024-02-10 13:42 UTC, volas commented on code/game/objects/effects/decals/remains.dm
> +	desc = "Они похожи на останки человека. От них исходит странная аура."
аура - возможно это наследие, когда они использовались в культе/у визарда, или хз откуда тут. Можно, наверно, убрать, иначе не понятно к чему оно тут

2024-02-17 04:47 UTC, volas requested changes
выше реквест на перевод в датум

2024-02-17 04:49 UTC, volas commented on code/game/objects/effects/decals/remains.dm
> +	desc = "Они похожи на останки чего-то... инопланетного."
```suggestion
	desc = "Они похожи на останки чего-то... не человеческого."
```

как предложение, инопланетного в спессе странно использовать.

2024-04-20 02:02 UTC, closed without merging