Перевод целек антагов, допереводим статистику и обьяснения,  связанные с ними
TauCetiStation/TauCetiClassic pull request #12843
Opened 2024-02-15 05:49 UTC by maleyvich

## Описание изменений
все описано в тайтле, практически все вещи связанные с антагами в статистике переведены!
## Почему и что этот ПР улучшит
resolves https://github.com/TauCetiStation-TranslationDepartment/TauCetiClassic/issues/26, продолжаем перевод.
## Авторство
Tau Ceti Trans Dep.

## Чеинжлог

:cl:
- ru: Были переведены цели антагонистов и статистика, связанная с ними.

2024-02-15 05:49 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2024-02-15 05:50 UTC, maleyvich commented
забыл дополнить что вероятно это сломает самую лучшую статистику таукотии от киборга...

2024-02-15 06:04 UTC, liteyzz commented
эксперименты на людях может . . . бля кто начал эту канитель с переводами мдааа

2024-02-15 06:05 UTC, liteyzz commented
переведите домашнее задание по английскому языку лучше

2024-02-15 06:05 UTC, maleyvich commented on code/modules/statistic/gamemode_stat.dm
> +	// string, ["УСПЕХ" as SUCCESS, "ЧАСТИЧНО" as HALF, "ПРОВАЛ" as FAIL]
пояснение на всякий случай (вдруг какие-т американцы кодить будут), оно все равно закомменчено

2024-02-15 06:11 UTC, simb11 commented on code/game/gamemodes/objectives/steal.dm
> +		"ядерную пушку" = /obj/item/weapon/gun/energy/gun/nuclear,
мне кажется лучше будет немного поменять суть и назвать оружие тем чем она является, то есть "Продвинутым энергооружием"

2024-02-15 06:13 UTC, maleyvich commented on code/game/gamemodes/objectives/steal.dm
> +		"ядерную пушку" = /obj/item/weapon/gun/energy/gun/nuclear,
звучит норм спасибо

2024-02-15 10:52 UTC, daedrowe commented on code/game/gamemodes/objectives/objectives.dm
> +		to_chat(H, "Неудивительно, что вы потеряли дополнительное снаряжение для выполнения задания.")
мем
```suggestion
		to_chat(H, "Увы, вы потеряли дополнительное снаряжение для выполнения задания.")
```

не мем
```suggestion
		to_chat(H, "К сожалению, вы потеряли дополнительное снаряжение для выполнения задания.")
```

2024-02-15 10:52 UTC, daedrowe commented on code/game/gamemodes/roles/traitor.dm
> +			to_chat(antag.current, "[bicon(logo, css = "style='position:relative; top:10;'")] <span class='danger'>Вы - агент Синдиката, предатель.<br>Ваша задача, как агента - получить доверие экипажа и выпо
```suggestion
			to_chat(antag.current, "[bicon(logo, css = "style='position:relative; top:10;'")] <span class='danger'>Вы - агент Синдиката, предатель.<br>Ваша задача, как агента внедриться в экипаж станции и выполнить задачи любой ценой.</span>")
```

2024-02-15 10:52 UTC, daedrowe commented on code/game/gamemodes/roles/traitor.dm
> +			to_chat(antag.current, "[bicon(logo, css = "style='position:relative; top:10;'")] <span class='danger'>Вы - агент Сидниката, предатель.</span>")
```suggestion
			to_chat(antag.current, "[bicon(logo, css = "style='position:relative; top:10;'")] <span class='danger'>Вы - агент Синдиката, предатель.</span>")
```
можно покороче даже
```suggestion
			to_chat(antag.current, "[bicon(logo, css = "style='position:relative; top:10;'")] <span class='danger'>Вы - предатель.</span>")
```

2024-02-15 10:52 UTC, daedrowe commented on code/game/gamemodes/roles/traitor.dm
> +	to_chat(antag.current, "<span class='userdanger'> <B>ВНИМАНИЕ:</B> Вы слышите сигналы от Синдиката...</span>")
```suggestion
	to_chat(antag.current, "<span class='userdanger'> <B>ВНИМАНИЕ:</B> Вы слышите зов Синдиката...</span>")
```
```suggestion
	to_chat(antag.current, "<span class='userdanger'> <B>ВНИМАНИЕ:</B> Вы слышите звонок от Синдиката...</span>")
```

2024-02-15 11:04 UTC, maleyvich commented on code/game/gamemodes/roles/traitor.dm
> +			to_chat(antag.current, "[bicon(logo, css = "style='position:relative; top:10;'")] <span class='danger'>Вы - агент Сидниката, предатель.</span>")
неее у нас простые предатели это импостеры первый вариант лучше

2024-02-15 16:06 UTC, Pivo24 requested changes

2024-02-15 16:06 UTC, Pivo24 commented on code/game/gamemodes/objectives/abductors/abductor_objectives.dm
> +	explanation_text = "Провести эксперименты с [target_amount] людьми."
над* людьми же

Это правильные правила русского языка

2024-02-15 16:06 UTC, Pivo24 commented on code/game/gamemodes/objectives/target/rp_rev.dm
> +	return "Захватите, завербуйте или сгоните со станции [target.current.real_name], представителя [target.assigned_role]. Ликвидация разрешена, если нет иных способов сдерживания."
сгоните? но сгоняют стадо же в загон

выгоните?
изгоните?
прогоните?

2024-02-15 17:17 UTC, maleyvich commented on code/game/gamemodes/modes_gameplays/blob/overmind.dm
> +	to_chat(src, "<b>Shortcuts:</b> Click = расширить блоба / CTRL Click =  удалить ИЛИ переименовать Node Blob / Shift Click = улучшение блоба / Middle Mouse Click = призыв спор / Alt Click = создание
если переводить то все но я этого не хочу..

2024-02-15 17:18 UTC, maleyvich commented on code/game/gamemodes/objectives/target/rp_rev.dm
> +	return "Захватите, завербуйте или сгоните со станции [target.current.real_name], представителя [target.assigned_role]. Ликвидация разрешена, если нет иных способов сдерживания."
в этом тексте появляется новый скрытый смысл випо

2024-02-15 17:19 UTC, maleyvich commented on code/game/gamemodes/modes_gameplays/blob/overmind.dm
> +	to_chat(src, "<b>Shield Blob</b> является укрепленной версией Normal Blob. Он невосприимчив к огню, используйте это в свою пользу. Улучшите эту часть снова, чтобы получить рефлективную версию, спосо
потому что и кнопки придется переводить, мне неизвестно к чему это может привести

2024-02-15 17:19 UTC, maleyvich commented on code/game/gamemodes/objectives/target/harm.dm
> +	return "Преподайте урок [target.current.real_name], представителю [target.assigned_role]. Сломайте кость, оторвите  любую конечность или превратите лицо цели в кашу! Убедитесь, что цель выживет посл
падеж профессии? как по мне пока страшно и ненужно

2024-02-17 07:24 UTC, maleyvich commented on code/game/gamemodes/objectives/steal.dm
> +	explanation_text = "Украдите [target_name]."
разобрались в дискорде пока не будем такие ноухау добавлять

2024-02-17 10:45 UTC, maleyvich commented
XNJ

2024-02-17 10:48 UTC, maleyvich commented on code/game/gamemodes/modes_gameplays/blob/powers.dm
>  	set name = "Jump to Node"
сделали

2024-02-17 11:27 UTC, maleyvich commented on code/game/gamemodes/modes_gameplays/blob/theblob.dm
>  	name = "blob"
cltkfyj

2024-02-17 14:21 UTC, Pivo24 approved these changes

2024-02-17 16:00 UTC, Chip11-n commented on code/game/gamemodes/modes_gameplays/blob/powers.dm
> +		<br>Вы мощны и вас сложно убить, вы восстанавливаетесь при нахождении рядом с ячейками, <span class='danger'но медленно умираете, если не находитесь рядом с блобом </span> или если фабрика, которая
```suggestion
		<br>Вы сильны и выносливы. Вы восстанавливаетесь при нахождении рядом с ячейками, <span class='danger'но медленно умираете, если не находитесь рядом с блобом </span> или если фабрика, которая создала вас - уничтожена. \
```

2024-02-17 16:02 UTC, Chip11-n commented on code/game/gamemodes/modes_gameplays/blob/powers.dm
> +		to_chat(src, "Здесь уже есть ресурсная ячейка, поставьте другую на 4 плитки дальше!")
Может запутать. Не на 4, а возможно, дальше 4 клеток от ближайшей.

2024-02-17 16:02 UTC, Chip11-n commented on code/game/gamemodes/modes_gameplays/blob/powers.dm
> +		to_chat(src, "Эта зона не захвачена!")
Зона? Клетка? Тут нет блоба?

2024-02-17 16:04 UTC, Chip11-n commented on code/game/gamemodes/modes_gameplays/blob/powers.dm
> +		to_chat(src, "Здесь уже есть узел, поставьте другой на 4 плитки дальше!")
Опять же. У нас не динамический отсчёт, что бы так писать.

2024-02-17 16:04 UTC, Chip11-n commented on code/game/gamemodes/modes_gameplays/blob/powers.dm
> +		to_chat(src, "Вы должны контролировать эту точку!")
Ты уж определись. Это точка, зона, блоб или что?

2024-02-17 16:08 UTC, Chip11-n commented on code/game/gamemodes/objectives/blob_takeover.dm
> +	explanation_text = "Мы должны расти и расширяться. Заполним станцию спорами. [invade_tiles] - именно столько пространства хватит для полного контроля."
Очень странная формулировка.

2024-02-17 16:08 UTC, Chip11-n commented on code/game/gamemodes/objectives/block.dm
> +	explanation_text = "Не позволяйте органическим формам жизни добраться до шаттла."
Сбежать.

2024-02-17 16:11 UTC, Chip11-n commented on code/game/gamemodes/objectives/heist/loot.dm
> +	explanation_text = "Мы заинтересованы в этом барахле... Украдём [loot]."
Барахле? Возражений нет? Ладно.

2024-02-17 16:13 UTC, Chip11-n commented on code/game/gamemodes/objectives/hijack.dm
> +	explanation_text = "Украдите шаттл, посланный НТ и отправьте его на базу Синдиката. Никто кроме вас не должен улететь на нём, разрешаются любые меры."
Зря ты сместил акцент последней части.

2024-02-17 16:13 UTC, Chip11-n commented on code/game/gamemodes/objectives/nuclear.dm
> +	explanation_text = "Уничтожьте станцию собственной ядерной бомбой."
Почему собственной? Обязательно-обязательно что ли?

2024-02-17 16:15 UTC, Chip11-n commented on code/game/gamemodes/objectives/replicators/replicators_objectives.dm
> +	explanation_text = "Соорудите блюспейс-катапульту и отправьте на ней 20 репликаторов!"
На ней или через или с?

2024-02-17 16:21 UTC, maleyvich commented on code/game/gamemodes/objectives/nuclear.dm
> +	explanation_text = "Уничтожьте станцию собственной ядерной бомбой."
ну так да, им код от СОБСТВЕННОЙ бомбы дают, а щитспавн это не моя проблема

2024-02-17 16:21 UTC, maleyvich commented on code/game/gamemodes/modes_gameplays/blob/powers.dm
> +		to_chat(src, "<span class='warning'>Эта ячейка слишком повреждена для производства ячейки.</span>")
ошибка, исправлю

2024-02-17 16:28 UTC, maleyvich commented on code/_onclick/hud/blob_overmind.dm
> +	desc = "Вы передвигаетесь к своему ядру."
не понимаю в чем разница между "перемещение" и "перемещаемся".

2024-02-17 16:38 UTC, Chip11-n commented on code/_onclick/hud/blob_overmind.dm
> +	desc = "Вы передвигаетесь к своему ядру."
Движение - именно что физическое действие. Обычно, в случае если мы идём пешком. 

Перемещение - изменение положения в пространстве.

2024-02-17 16:49 UTC, Chip11-n commented on code/game/gamemodes/objectives/steal.dm
> +		"функциональный ИИ" = /obj/item/device/aicard,
Функциональный или функционирующий?

2024-02-17 16:49 UTC, Chip11-n commented on code/game/gamemodes/objectives/target/dehead.dm
> +	return "Положите голову [target.current.real_name] в банку с биогелем и храните её с собой."
И храните её с собой?

2024-02-17 16:49 UTC, Chip11-n commented on code/game/gamemodes/objectives/target/target.dm
> +	return "Тут не написано текста для обьяснения. Тип задания - [type]. Задача это - [target.name], веселись."
```suggestion
	return "Тут не написано текста для обьяснения. Тип задания - [type]. Задача - [target.name], веселись."
```

2024-02-17 16:49 UTC, Chip11-n commented on code/game/gamemodes/role.dm
> +	var/mob/M = null
А что это?

2024-02-17 16:56 UTC, maleyvich commented on code/game/gamemodes/role.dm
> +	var/mob/M = null
я не помню зачем я это добавлял...  уберу по возможности

2024-02-17 16:59 UTC, maleyvich commented on code/_onclick/hud/blob_overmind.dm
> +	desc = "Вы передвигаетесь к своему ядру."
хорошо, я понял твою мысль и изменю на "Вы перемещаетесь к своему ядру"

2024-02-17 17:03 UTC, maleyvich commented on code/game/gamemodes/objectives/steal.dm
> +		"функциональный ИИ" = /obj/item/device/aicard,
да, функционирующий. исправлю.

2024-02-17 17:06 UTC, maleyvich commented on code/game/gamemodes/objectives/target/dehead.dm
> +	return "Положите голову [target.current.real_name] в банку с биогелем и храните её с собой."
"В банку с биогелем. Она должна оставаться у вас и желательно в сохранности."?

2024-02-18 07:18 UTC, simb11 commented
нужно ещё перевести обжектив из #12844

2024-02-18 07:50 UTC, maleyvich commented on code/game/gamemodes/role.dm
> +	var/mob/M = null
я вспомнил, это было сделано ради проверки на гендер моба-антага немного ниже

2024-02-18 07:59 UTC, maleyvich commented on code/game/gamemodes/objectives/blob_takeover.dm
> +	explanation_text = "Мы должны расти и расширяться. Заполним станцию спорами. [invade_tiles] - именно столько пространства хватит для полного контроля."
формулировка странная, но аззи не понравился мой вариант. поэтому, стоит оставить этот.

2024-02-18 08:01 UTC, maleyvich commented on code/game/gamemodes/modes_gameplays/blob/powers.dm
> +		to_chat(src, "Здесь уже есть узел, поставьте другой на 4 плитки дальше!")
не понимаю в чем претензия на самом деле...

2024-02-18 08:01 UTC, maleyvich commented on code/game/gamemodes/modes_gameplays/blob/powers.dm
> +		to_chat(src, "Вы должны контролировать эту точку!")
определился

2024-02-19 12:07 UTC, maleyvich commented on code/game/gamemodes/role.dm
> +			text += "[M.gender == MALE ? "погиб" : "погибла"]"
анастасия павловна (погиб)

2024-02-19 12:16 UTC, maleyvich commented on code/game/gamemodes/role.dm
> +	text += "[bicon(logo, css = "style='position: relative;top:10px;'")]<b>[mind.key]</b> [M.client.gender == MALE ? "был" : "была"] <b>[mind.name]</b> ("
я предполагаю что обращения к игроку через мужской род потому-что в английском они очень непонятно выражены и слово was может подходить так к мужчине так и женщине (условно Anton Petrov was a soldier и Anastasia Petrova was a doctor, мы не будем говорить Антон Петров была солдатом и Анастасия Петрова был доктором, это тупо) может быть предьява именно в том, что это используется именно в этом месте?

2024-02-19 12:17 UTC, maleyvich commented on code/game/gamemodes/role.dm
> +			text += "[M.gender == MALE ? "выжил" : "выжила"]"
а что поделать? спу тоже могут быть без гендера, даже какого-то метафорического, они могут только ассоциировать себя с определенным полом

не оставлять же просто "выжил", это глупо

2024-02-20 16:55 UTC, maleyvich commented on code/game/gamemodes/objectives/families/steal_lowrisk.dm
> +	explanation_text = "Украдите [initial(steal_target.name)]."
в другом проблема...

2024-02-27 18:21 UTC, Pivo24 requested changes

2024-02-27 18:21 UTC, Pivo24 commented on code/game/gamemodes/modes_gameplays/blob/powers.dm
> +	set name = "Перемещение к ноде"
Почему нода, а не узел?

2024-02-27 18:21 UTC, Pivo24 commented on code/game/objects/structures/displaycase.dm
> +	cases = list("лицехват Ламарр", "лицехвата Ламмара", "лицехвату Ламмару", "лицехвата Ламмара", "лицехватом Ламмаром")
Ориг Lamarr с двумя r, а перевод Ламмар с двумя м, а как и почему :(

2024-02-27 18:24 UTC, maleyvich commented on code/game/objects/structures/displaycase.dm
> +	cases = list("лицехват Ламарр", "лицехвата Ламмара", "лицехвату Ламмару", "лицехвата Ламмара", "лицехватом Ламмаром")
чето случайно это получилось и смешно учитывая что в именительном падеже все правильно

2024-02-27 18:26 UTC, LudwigVonChesterfield commented on code/game/gamemodes/objectives/replicators/replicators_objectives.dm
> +	explanation_text = "Соорудите блюспейс-катапульту и отправьте с неё 20 репликаторов!"
отправьте 20 звучит будто надо ровно столько?

2024-02-27 18:33 UTC, maleyvich commented on code/game/gamemodes/objectives/replicators/replicators_objectives.dm
> +	explanation_text = "Соорудите блюспейс-катапульту и отправьте с неё 20 репликаторов!"
а сколько надо?

2024-02-28 10:41 UTC, Chip11-n commented on code/game/gamemodes/modes_gameplays/blob/powers.dm
> +		to_chat(src, "Здесь уже есть узел, поставьте другой на 5 плиток дальше!")
Та же история с расстоянием.

2024-02-28 10:42 UTC, Chip11-n commented on code/game/gamemodes/modes_gameplays/blob/powers.dm
> +		to_chat(src, "Здесь уже есть производящая ячейка, поставьте другую на 7 плиток дальше!!")
Расстояние.

2024-02-28 10:44 UTC, Chip11-n commented on code/game/gamemodes/objectives/heist/loot.dm
> +			loot = "полный комплект ускоритель частиц"
Добавь уточнение про 6 частей, это поможет новичкам.

2024-02-28 10:50 UTC, Chip11-n commented on code/game/gamemodes/role.dm
> +			text += "[M.gender == MALE ? "погиб" : "погибла"]"
Почему в одном случае через макрос, а в трех других - нет?

2024-02-28 10:54 UTC, maleyvich commented on code/_onclick/hud/blob_overmind.dm
> +	desc = "Создаёт крепкого и умного блоббернаута.<br>Производящая ячейка, создавшая блоббернаута, становится неактивной и хрупкой на некоторое время."
я всего лишь перевел как было в самом тексте

2024-02-28 11:07 UTC, Chip11-n commented on code/_onclick/hud/blob_overmind.dm
> +	desc = "Создаёт крепкого и умного блоббернаута.<br>Производящая ячейка, создавшая блоббернаута, становится неактивной и хрупкой на некоторое время."
В тексте ни слова про время, лишь про уменьшение прочности.

2024-02-28 11:18 UTC, maleyvich commented on code/game/gamemodes/role.dm
> +			text += "[M.gender == MALE ? "погиб" : "погибла"]"
потому что м верб просто добавляет окончание "а" и "о" для разных полов, здесь это не подходит

2024-02-28 11:26 UTC, maleyvich commented on code/game/gamemodes/modes_gameplays/blob/powers.dm
> +		to_chat(src, "Здесь уже есть узел, поставьте другой на 5 плиток дальше!")
предложен иной вариант в дискорде, который внесён в пр

2024-02-28 11:26 UTC, maleyvich commented on code/game/gamemodes/modes_gameplays/blob/powers.dm
> +		to_chat(src, "Здесь уже есть производящая ячейка, поставьте другую на 7 плиток дальше!!")
предложен иной вариант в дискорде, который внесён в пр

2024-02-28 11:59 UTC, maleyvich commented on code/game/gamemodes/modes_gameplays/blob/overmind.dm
> +	to_chat(src, "<b>Ресурсная ячейка</b> является основным способом добычи ресурсов, постройте их как можно больше в начале, чтобы всегда иметь достаточно ресурсов. Оно улучшается от нахождения рядом с
вроде бы проблем нет резолваю

2024-02-28 14:33 UTC, LudwigVonChesterfield commented on code/game/gamemodes/objectives/replicators/replicators_objectives.dm
> +	explanation_text = "Соорудите блюспейс-катапульту и отправьте с неё минимум 20 репликаторов!"
```suggestion
	explanation_text = "Соорудите блюспейс-катапульту и отправьте с неё не меньше чем 20 репликаторов!"
```
Я бы вообще предложил "с неё не меньше 20-и" но звучит кринжовенько.

2024-02-28 16:54 UTC, maleyvich commented on code/game/gamemodes/modes_gameplays/blob/powers.dm
> +	set desc = "Создаёт мощного и умного блоббернаута."
получается так

2024-02-28 16:57 UTC, maleyvich commented on code/game/gamemodes/modes_gameplays/blob/powers.dm
> +	set desc = "Перемещение к ядру."
ядро у блоба может быть только одно и думается мне что лучше будет без уточнения какое ядро или "вашему ядру"

2024-03-01 11:13 UTC, Pivo24 approved these changes

2024-03-07 03:51 UTC, maleyvich commented
даааа пр все ещё актуален (мне через неделю лень будет)

2024-03-07 19:01 UTC, Chip11-n approved these changes
Через сутки буду мержить.

2024-03-07 19:01 UTC, Chip11-n commented on code/game/gamemodes/modes_gameplays/blob/powers.dm
> +		to_chat(src, "Здесь уже есть производящая ячейка, другую производящую ячейку можно поставить на 7 плиток дальше!")
```suggestion
		to_chat(src, "Здесь уже есть производящая ячейка поблизости, другую можно поставить на расстоянии в 7 плиток от близжайшей!")
```
Что-то вроде такого предлагал, да и у тебя был неплохой вариант.

2024-03-09 10:34 UTC, Chip11-n commented
На будущее, Малевич, разделяй ПРы, ибо 58 ревьюва - смешно, но долго.

2024-03-09 10:37 UTC, merged

2024-03-09 20:23 UTC, Chip11-n commented on code/game/gamemodes/role.dm
> +	var/mob/M = null
Малевич, просил же не резолвать ишшуи, если не решил проблему.

2024-03-10 18:00 UTC, volas reviewed
я заглянул по поводу бага, а тут еще какие-то блобы, предлагаю откатить и разбить на несколько меньших пр-ов