Теперь клоуны раундстартом не замедлены
TauCetiStation/TauCetiClassic pull request #12849
Opened 2024-02-16 19:36 UTC by muWander

## Описание изменений
У клоуна есть замечательная способность из https://github.com/TauCetiStation/TauCetiClassic/pull/5259 но она не работала при спавне, клоун мог быстро бегать в своей обуви лишь после того как он её переобувал. Фиксит это, теперь клоун раундстартом быстрый как и положено
## Почему и что этот ПР улучшит
closes https://github.com/TauCetiStation/TauCetiClassic/issues/6978
## Авторство

## Чеинжлог
:cl:
 - bugfix: Теперь клоунам не нужно переобуваться чтоб быстро бегать в своих ботиночках.

2024-02-16 19:36 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2024-02-16 20:47 UTC, LudwigVonChesterfield approved these changes

2024-02-17 05:15 UTC, volas commented on code/datums/outfits/jobs/civilian.dm
> +	H.rename_self("clown")
ренейм следовало бы скорее всего после эквипа оставить, оно меняет название карт и ПДА и в теории самая быстрая рука на западе сможет успеть сломать их переименование.

Хотя может быть они при спавне имя кукла заберут, я не знаю.

2024-02-18 11:38 UTC, muWander commented on code/datums/outfits/jobs/civilian.dm
> +	H.rename_self("clown")
Харашо я всё так и сделал, но насколько мне известно с этим и сейчас есть проблема (ака у антагов не обновляется имя когда клоун/мим его вводят в начале игры)

2024-02-18 11:42 UTC, muWander commented
Как бонус сделал то же самое клоун-ОБР.

Алсо, этот костыль делает так, что раундстарт-антаг клоун (у антагов снимается ген неуклюжести, позволяющий бегать в ботинках, напомню) **может** в ботинках бегать до того, как их переобует. За сим предлагаю добавить ботинкам проверку не только на ген, но и дополнительно на Job, чтоб антаги-клоуны могли бегать, дабы снизить количество ролькоханта и повысить количество хонка.

2024-02-19 02:00 UTC, LudwigVonChesterfield commented on code/game/jobs/job/civilian.dm
> +		H.real_name = pick(clown_names)
мне кажется тут две табуляции вместо одной

2024-02-19 02:00 UTC, LudwigVonChesterfield commented on code/modules/clothing/shoes/miscellaneous.dm
> +	if(user.IsClumsy() || user.job == "Clown")
так делать не надо, лучше выдай кламзи ОБР клоуну.

2024-02-19 02:01 UTC, LudwigVonChesterfield commented on code/modules/clothing/shoes/miscellaneous.dm
> +	if(user.IsClumsy() || user.job == "Clown")
не знаю с тем же успехом тритора могли бы палить на консоли генетики же...

2024-02-19 02:02 UTC, LudwigVonChesterfield commented
здесь всё стало сложнее чем изначально когда я читал

2024-02-19 13:07 UTC, muWander commented on code/modules/clothing/shoes/miscellaneous.dm
> +	if(user.IsClumsy() || user.job == "Clown")
> не знаю с тем же успехом тритора могли бы палить на консоли генетики же... походу пора делать скилл клоунизма, или хотя бы трейт.

оно уже трейтом же, я щас экспериментально проверил на мастере и консоль генетика абсолютно одинаковые циферки показала до и после триторизации клоуна, а вот то что клоун отказывается от своих ботинок это жирный OOC-повод подумать что он антаг

2024-02-24 10:17 UTC, Venngedi commented
Можешь в тело добавить этот ишшуй? #10366

2024-03-09 14:23 UTC, volas commented on code/modules/clothing/shoes/miscellaneous.dm
> +	if(user.IsClumsy() || user.job == "Clown")
а зачем вообще проверка на джобнейм, если есть трейт?

2024-03-09 14:25 UTC, volas commented on code/modules/clothing/shoes/miscellaneous.dm
> +	if(user.IsClumsy() || user.job == "Clown")
> Алсо, этот костыль делает так, что раундстарт-антаг клоун (у антагов снимается ген неуклюжести, позволяющий бегать в ботинках, напомню) может в ботинках бегать до того, как их переобует. За сим предлагаю добавить ботинкам проверку не только на ген, но и дополнительно на Job, чтоб антаги-клоуны могли бегать, дабы снизить количество ролькоханта и повысить количество хонка.

а, вижу. Но это какая-то деградация, если надо то можно добавить просто отдельный трейт на походку и давать клоуну два.

2024-03-19 12:02 UTC, volas requested changes
реквесты выше

2024-04-08 03:27 UTC, volas commented
я тут за бота. Пр хороший, и доделать его было бы не долго, жаль. Если захочешь заняться - попроси переоткрыть.

2024-04-08 03:27 UTC, closed without merging