Перевод armor.dm
TauCetiStation/TauCetiClassic pull request #12855
Opened 2024-02-18 08:11 UTC by MarcusFrei

## Описание изменений
Перевод armor.dm, удаление чати кода, теоретически не вызывающего никаких проблем и не влиящий на имеющиёся функционал
## Почему и что этот ПР улучшит
Это перевод
## Авторство
я
## Чеинжлог
Перевод большей части брони, не включая броню капитана и неболшого ряда других нательных видов брони, которые не входят в armor.dm

2024-02-18 08:11 UTC, TauKitty commented
###### Changelog status: :radio_button: No changelog

2024-02-18 08:27 UTC, Kiromaka commented
Закрывай ПР, перенеси на новую ветку -плохо пережить мастера. Пофикси чейнджлог, укороти падежи, не меняй падеж,
если не меняется нэйм.

2024-02-18 08:44 UTC, MarcusFrei commented
> Закрывай ПР, перенеси на новую ветку -плохо мережить мастера. Пофикси чейнджлог, укороти падежи, не меняй падеж, если не меняется нэйм.

А для тупых, что укорачивать и зачем? Не менять падеж и укорачивать его?

2024-02-18 09:05 UTC, MarcusFrei commented on code/modules/clothing/suits/armor.dm
> +	cases = list("полнотелый бронежилет","полнотельного бронежилета","полнотельному бронежилету","полнотельный бронежилет","полнотельным бронежилетом","о полнотельном бронежилете")
Поправлю

2024-02-18 09:10 UTC, KandreyKandrey commented on code/modules/clothing/suits/armor.dm
> +	desc = "Тяжелые королевские пурпурные одеяния, инкрутированные психическими усилителями и странными, выпуклыми линзами. Не подлежит машинной стирке."
```suggestion
	desc = "Тяжелые королевские пурпурные одеяния, инкрустированные психическими усилителями и странными, выпуклыми линзами. Не подлежит машинной стирке."
```

2024-02-18 09:18 UTC, simb11 commented on code/modules/clothing/suits/armor.dm
> +	desc = "Бронежилет, защищающий от незначительных повреждений. На нём прикреплена разрузка, позволяющая хранить до четырёх предметов, а также индивидуальная окраска в цветах \'ООБПБП\'."
```suggestion
	desc = "Бронежилет, защищающий от незначительных повреждений. На нём прикреплена разгрузка, позволяющая хранить до четырёх предметов, а также индивидуальная окраска в цветах \ОБОП\'."
```
потому что OCD в билде уже переведёт как ОБП
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/84613249/5f794ce0-0c36-41b6-a5dd-9ba5cb31d2c7)

2024-02-18 09:18 UTC, MarcusFrei commented on code/modules/clothing/suits/armor.dm
> +	desc = "Бронежилет, защищающий от незначительных повреждений. На нём прикреплена разрузка, позволяющая хранить до четырёх предметов, а также индивидуальная окраска в цветах \'ООБПБП\'."
Окей, поправлю

2024-02-18 09:27 UTC, simb11 commented on code/modules/clothing/suits/armor.dm
> +	cases = list("бронежилет морпеха", "бронежилета морпеха", "бронежилету морпеха", "бронежилет морпеха", "бронежилетом морпеха", "бронежилете морпеха")
скорее "Броня морпеха", потому что там ещё защитные поножи и наручи имеются.

2024-02-18 09:29 UTC, Kiromaka commented
> > Закрывай ПР, перенеси на новую ветку -плохо мережить мастера. Пофикси чейнджлог, укороти падежи, не меняй падеж, если не меняется нэйм.
> 
> А для тупых, что укорачивать и зачем? Не менять падеж и укорачивать его?

Падеж замена Нэйма в интервенциях, слишком длинный падеж плохо - пуля попала в уплощенно-пинакоидально-ромбоэдрический синий камень

2024-02-18 09:29 UTC, simb11 commented on code/modules/clothing/suits/armor.dm
> +	cases = list("аблятивный полнотелый бронежилет", "аблятивного полнотелого бронежилета", "аблятивному полнотелому бронежилету", "аблятивный полнотелый бронежилет", "аблятивным полнотелым бронежилетом
"аблятивная броня" тогда уж, потому что версии без защиты конечностей в игре не имеется.

2024-02-18 09:30 UTC, simb11 commented on code/modules/clothing/suits/armor.dm
> +	cases = list("пуленепробиваемый полнотелый бронежилет", "пуленепробиваемого полнотелого бронежилета", "пуленепробиваемому полнотелому бронежилету", "пуленепробиваемый полнотелый бронежилет", "пулене
как и аблятивной броней, мне кажется, лучше перевести как "пуленепробиваемая броня"

2024-02-18 09:33 UTC, MarcusFrei commented
> > > Закрывай ПР, перенеси на новую ветку -плохо мережить мастера. Пофикси чейнджлог, укороти падежи, не меняй падеж, если не меняется нэйм.
> > 
> > 
> > А для тупых, что укорачивать и зачем? Не менять падеж и укорачивать его?
> 
> Падеж замена Нэйма в интервенциях, слишком длинный падеж плохо - пуля попала в уплощенно-пинакоидально-ромбоэдрический синий камень

Звучит разумно тогда.

2024-02-18 09:37 UTC, simb11 commented on code/modules/clothing/suits/armor.dm
> +	cases = list("бронежилет Службы Безопасности", "бронежилета Службы Безопасности", "бронежилету Службы Безопасности", "бронежилет Службы Безопасности", "бронежилетом Службы Безопасности", "бронежилет
лучше будет сократить просто до "брони охраны"

2024-02-18 09:38 UTC, simb11 commented on code/modules/clothing/suits/armor.dm
> +	cases = list("бронежилет Службы Безопасности с разгрузкой", "бронежилета Службы Безопасности с разгрузкой", "бронежилету Службы Безопасности с разгрузкой", "бронежилет Службы Безопасности с разгрузк
тут тож самое, просто "броня охраны"

2024-02-18 09:51 UTC, simb11 commented on code/modules/clothing/suits/armor.dm
> +	cases = list("протёртый бронежилет", " потёртого бронежилета", "потёртому бронежилету", "потёртый бронежилет", "потёртым бронежилетом", "потёртом бронежилете")
Может "Устаревший бронежилет"?

2024-02-18 09:58 UTC, maleyvich requested changes

2024-02-18 09:58 UTC, maleyvich commented on code/modules/clothing/suits/armor.dm
> +	cases = list("бронированная шинель", "бронированной шинели", "бронированной шинели", "бронированную шинель", "бронированной шинелью", "бронированной шинели")
бронеплащ звучит немного получше, сохраняет суть предмета и покороче

2024-02-18 09:59 UTC, MarcusFrei commented on code/modules/clothing/suits/armor.dm
> +	cases = list("протёртый бронежилет", " потёртого бронежилета", "потёртому бронежилету", "потёртый бронежилет", "потёртым бронежилетом", "потёртом бронежилете")
> Может "Устаревший бронежилет"?

surplus - это именно сделанный из говна и палок, херового качества и тд, устраевший, наверное лучше подойдёт, хотя я бы попробовал вариант - дешёвый бронежилет.

2024-02-18 10:01 UTC, MarcusFrei commented on code/modules/clothing/suits/armor.dm
> +	cases = list("бронированная шинель", "бронированной шинели", "бронированной шинели", "бронированную шинель", "бронированной шинелью", "бронированной шинели")
> бронеплащ звучит немного получше, сохраняет суть предмета и покороче

Тогда уже бронепальто, раз в описании я так перевёл, плащ по другому выглядит

2024-02-18 10:06 UTC, volas commented on code/modules/clothing/suits/armor.dm
> +	cases = list("бронированная шинель", "бронированной шинели", "бронированной шинели", "бронированную шинель", "бронированной шинелью", "бронированной шинели")
сходу не вспомню, но в играх еще часто для armored используется что-то вроде "укрепленное". Ну знаете, где крафт и можно апгрейдить одежду

2024-02-18 10:11 UTC, MarcusFrei commented on code/modules/clothing/suits/armor.dm
> +	cases = list("бронированная шинель", "бронированной шинели", "бронированной шинели", "бронированную шинель", "бронированной шинелью", "бронированной шинели")
> сходу не вспомню, но в играх еще часто для armored используется что-то вроде "укрепленное". Ну знаете, где крафт и можно апгрейдить одежду

укреплённое пальто, окей, пусть будет так

2024-02-18 10:13 UTC, maleyvich commented on code/modules/clothing/suits/armor.dm
> +	cases = list("бронированная шинель", "бронированной шинели", "бронированной шинели", "бронированную шинель", "бронированной шинелью", "бронированной шинели")
> сходу не вспомню, но в играх еще часто для armored используется что-то вроде "укрепленное". Ну знаете, где крафт и можно апгрейдить одежду

укрепленная шинель звучит довольно посредственно, имхо..

2024-02-18 10:13 UTC, MarcusFrei commented on code/modules/clothing/suits/armor.dm
> +	cases = list("бронированная шинель", "бронированной шинели", "бронированной шинели", "бронированную шинель", "бронированной шинелью", "бронированной шинели")
> сходу не вспомню, но в играх еще часто для armored используется что-то вроде "укрепленное". Ну знаете, где крафт и можно апгрейдить одежду

А нет, можно почти дословно, армированное, есть же мотоциклетная армированная снаряга

2024-02-19 11:24 UTC, MarcusFrei commented on code/modules/clothing/suits/armor.dm
> +	desc = "Черный тактический жилет из кевлара, используемый частными охранными фирмами. Очень тактичный."
> тактичный? может тактический? а может вообще тактикульный?

В этом и мем, что он тактичный, а не тактический

2024-02-19 11:29 UTC, MarcusFrei commented on code/modules/clothing/suits/armor.dm
> +	cases = list("защитный костюм для подавления беспорядков", "защитного костюма для подавления беспорядков", "защитному костюму для подавления беспорядков", "защитный костюм для подавления беспорядков
> почему не противоударная

Вопрос задал в дисе, никто не ответил, любая броня у нас противоударное- не решение

2024-02-19 11:30 UTC, MarcusFrei commented on code/modules/clothing/suits/armor.dm
> +	desc = "Тяжелые королевские пурпурные одеяния, инкрустированные психическими усилителями и странными, выпуклыми линзами. Не подлежит машинной стирке."
> почему во множественном и после `странными` запятая не нужна

Потому что robes, а не robe и как в средние века, такие одежды носились многослойно, так что именно одеяния

2024-02-19 11:40 UTC, MarcusFrei commented on code/modules/clothing/suits/armor.dm
> +	desc = "Великолепное пальто, усиленное специальным сплавом для дополнительной защиты и стиля."
Окей, будет шинель

2024-02-19 12:03 UTC, AndroBetel commented on code/modules/clothing/suits/armor.dm
> +	desc = "Бронежилет, защищающий от незначительных повреждений. На нём прикреплена разрузка, позволяющая хранить до четырёх предметов, а также индивидуальная окраска в цветах \'ОБОП\'."
прикольно конечно прикрепили краску на бронежилет

2024-02-19 13:29 UTC, MarcusFrei commented on code/modules/clothing/suits/armor.dm
> +	cases = list("полицейская броня", "полицейской брони", "полицейской броне", "полицейскую броню", "полицейской бронёй", "полицейской броне")
Также всё фулбоди теперь просто броня, а остальное бронежилеты

2024-02-20 15:57 UTC, ZER0-In commented on code/modules/clothing/suits/armor.dm
> +	cases = list("протёртый бронежилет", " потёртого бронежилета", "потёртому бронежилету", "потёртый бронежилет", "потёртым бронежилетом", "потёртом бронежилете")
> > Может "Устаревший бронежилет"?
> 
> surplus - это именно сделанный из говна и палок, херового качества и тд, устраевший, наверное лучше подойдёт, хотя я бы попробовал вариант - дешёвый бронежилет.

Можно вписать как устаревший/старый.
Также подойдет "списанный" и "кустарный". Списанный подходит хуже, но как аналог работает. В случае кустарного, по логике рев брони подходит. Но сурплус не только реверы носят, но и мары.

2024-02-20 15:59 UTC, ZER0-In commented on code/modules/clothing/suits/armor.dm
> +	desc = "Тяжелые королевские пурпурные одеяния, инкрустированные психическими усилителями и странными, выпуклыми линзами. Не подлежит машинной стирке."
> почему во множественном и после `странными` запятая не нужна

"пурпурной робы" верно написано.

2024-02-21 15:37 UTC, MarcusFrei commented on code/modules/clothing/suits/armor.dm
> +	cases = list("бронежилет Службы Безопасности с разгрузкой", "бронежилета Службы Безопасности с разгрузкой", "бронежилету Службы Безопасности с разгрузкой", "бронежилет Службы Безопасности с разгрузк
Бронежилет Службы Безопасности просто?

2024-02-21 15:41 UTC, MarcusFrei commented on code/modules/clothing/suits/armor.dm
> -/obj/item/clothing/suit/armor/tactical/verb/holster()
Я провёл много тестов на локалке, никакого функционала этот код не несёт, не вижу смысла засорять, но могу оставить, однако без перевода

2024-02-21 15:46 UTC, LudwigVonChesterfield commented on code/modules/clothing/suits/armor.dm
> -	if(!holstered)
тут переводчики по приколу решили механ холстеринга пистолетов убрать

2024-02-21 15:46 UTC, LudwigVonChesterfield requested changes
верните холстеринг

2024-02-21 15:48 UTC, MarcusFrei commented on code/modules/clothing/suits/armor.dm
> +	cases = list("красный костюм \'Thunderdome\'", "красного костюма \'Thunderdome\'", "красному костюму \'Thunderdome\'", "красный костюм \'Thunderdome\'", "красным костюмом \'Thunderdome\'", "красном
> Может попробуешь название `Thunderdome` адоптировать на русский?

Оно не имеет перевода, это отсылка на Безумного Макса 85-го года ("Mad Max Beyond Thunderdome"), так там называлась арена, где Макс сражался с психами

2024-02-21 15:49 UTC, volas commented on code/modules/clothing/suits/armor.dm
> +	cases = list("бронежилет Службы Безопасности", "бронежилета Службы Безопасности", "бронежилету Службы Безопасности", "бронежилет Службы Безопасности", "бронежилетом Службы Безопасности", "бронежилет
это название отдела, оно с большой. Ну или может сделайте бронежилет охраны, а то слишком длинно

2024-02-21 15:53 UTC, MarcusFrei commented on code/modules/clothing/suits/armor.dm
> -	if(!holstered)
Я проверял, этот код не меняет ничего если его убрать, если не веришь можешь сам проверить, кобура, что на броне, что отдельна как работала, так и работает.

2024-02-21 16:09 UTC, LudwigVonChesterfield commented on code/modules/clothing/suits/armor.dm
> -	if(!holstered)
ПКМ по кобуре покажет "Holster".

2024-02-23 18:21 UTC, MarcusFrei commented on code/modules/clothing/suits/armor.dm
> +	cases = list("красный костюм \'Thunderdome\'", "красного костюма \'Thunderdome\'", "красному костюму \'Thunderdome\'", "красный костюм \'Thunderdome\'", "красным костюмом \'Thunderdome\'", "красном
> а в официальной озвучке как перевели?
Громовой купол

2024-02-25 18:52 UTC, KandreyKandrey commented on code/modules/clothing/suits/armor.dm
> +		visible_message("<span class='userdanger'>Система реактивной телепортации перемещает [user.name] в сторону от [CASE(text, GENITIVE_CASE)]!</span>")
у текста разве есть падежи?
```suggestion
		visible_message("<span class='userdanger'>Система реактивной телепортации перемещает [user.name] в сторону от [text]!</span>")
```

2024-02-29 09:24 UTC, maleyvich approved these changes
все круто.

2024-02-29 09:24 UTC, maleyvich commented on code/modules/clothing/suits/armor.dm
> +	cases = list("куртка смотрителя", "куртки смотрителя", "куртке смотрителя", "куртку смотрителя", "курткой смотрителя", "куртке смотрителя")
было бы смешнее, если был бы КАМЗОЛ (jacket может подразумевать под собой и его), но это чисто пожелания, можешь оставить куртку

2024-03-09 14:34 UTC, volas commented
считаю, идеально, можно в рамочку

2024-03-09 14:34 UTC, merged