Update head.dmi
TauCetiStation/TauCetiClassic pull request #12890
Opened 2024-02-24 23:07 UTC by AzzyDreemurr13

## Описание изменений
Для шляпы подняли на 1 пиксель вверх
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/74739991/f4788b2f-8222-48e7-9b15-6400175c51ec)
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/74739991/652a1334-f66a-46eb-8ce2-6e5cf63cde2e)
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/74739991/f403ea3c-913c-4d40-8b36-4876775f3eae)
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/74739991/81df2669-c325-4a22-8f36-2f602a896e6f)
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/74739991/d8627aed-e4fb-4d2d-bfa4-bf88f16d383f)
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/74739991/40238479-7521-439a-be37-39f7998aeb1d)

## Почему и что этот ПР улучшит
Фикс залезающей шляпы на глаза
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/74739991/c482cb58-d8f9-434c-ab51-3b6986003d9d)
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/74739991/dcc66ebf-035b-4fc9-b75f-acb624934454)

## Авторство
Zero корректировка спрайта, Я залил ПР

## Чеинжлог
Для такой мелочи не считаю нужным

2024-02-24 23:08 UTC, TauKitty commented
###### Changelog status: :radio_button: No changelog

2024-02-25 09:13 UTC, Chip11-n requested changes
DMI проблемный. Посмотри в боте - откаты спрайтов.

2024-02-25 20:17 UTC, Chip11-n approved these changes
Перфекционисты, возрадуйтесь!

2024-02-25 20:19 UTC, merged

2024-02-25 20:21 UTC, KIBORG04 commented
> Для такой мелочи не считаю нужным

Ясно, пр сделан, работа выполнена, но про неё никто не узнает!(

2024-02-25 20:22 UTC, Chip11-n commented
Об этом треть форума в курсе 😄

2024-02-26 17:04 UTC, ZER0-In commented
Харош. Если еще проблемы со спрайтами найдутся, можешь мне присылать.