Перевод имплантов
TauCetiStation/TauCetiClassic pull request #12903
Opened 2024-02-29 17:50 UTC by AzzyDreemurr13

## Описание изменений
Долгожданный и обещанный (запоздалый) перевод имплантов для мед сканера и других вещей.
Resolved https://github.com/TauCetiStation-TranslationDepartment/TauCetiClassic/issues/19
## Почему и что этот ПР улучшит
Делаем Body Scanner полностью на русском языке и больше переводов
## Авторство
Я и @Pivo24 

## Чеинжлог
:cl: Azzy.Dreemurr, Vipo
 - ru: Перевод имплантов

2024-02-29 17:50 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2024-02-29 18:49 UTC, KandreyKandrey commented on code/game/objects/items/weapons/implants/implant.dm
> +	desc = "Обгоревшая плата в плавленной пластиковой оболочке. Интересно, для чего она была..."
```suggestion
	desc = "Обгоревшая плата в расплавленной пластиковой оболочке. Интересно, для чего она была..."
```

2024-02-29 18:52 UTC, KandreyKandrey commented on code/game/objects/items/weapons/implants/implant.dm
> +<b>Фукнционал:</b> Издаёт низкочастотный сигнал на протяжении работы. Полезен для отслеживания.<BR>
предлагаю 2 варианта:
1) 'при работе издаёт низкочастотный сигнал'
2) 'издаёт низкочастотный сигнал в процессе работы'

2024-02-29 18:55 UTC, KandreyKandrey commented on code/game/objects/items/weapons/implants/implant.dm
> +при сбое без вреда для носителя. Имплант расплавится и распадётся на безопасные биокомпоненты.<BR>
```suggestion
<i>Нейро-безопасный</i>- Особая структура оболочки поглощает избыточное напряжение, при сбое уничтожая чип без вреда для носителя. Имплант расплавится и распадётся на безопасные биокомпоненты.<BR>
```

2024-02-29 19:08 UTC, KandreyKandrey commented on code/game/objects/items/weapons/implants/implant.dm
> +будет испытывать более повышенный аппетит.</B><BR>
```suggestion
<b>Важные примечания: Поскольку внутренние системы импланта работают за счёт питательных веществ в теле носителя, тот<BR>
будет испытывать повышенный аппетит.</B><BR>
```

2024-02-29 19:08 UTC, KandreyKandrey commented on code/game/objects/items/weapons/implants/implant.dm
> +<i>Микрокапсула</i>- Может заполнена любым химикатом с помощью простого шприца и вмещает в себя до 50 юнитов.<BR>
```suggestion
<i>Микрокапсула</i>- Может быть заполнена любым химикатом с помощью простого шприца, и вмещает в себя до 50 юнитов.<BR>
```

2024-02-29 19:09 UTC, KandreyKandrey commented on code/game/objects/items/weapons/implants/implant.dm
> +	to_chat(R, "Вы слышите еле слышное *бип*.")
```suggestion
	to_chat(R, "Вы слышите тихое *бип*.")
```
еле/едва различимое

2024-02-29 19:11 UTC, KandreyKandrey commented on code/game/objects/items/weapons/implants/implant.dm
> +<b>Функционал:</b> Содержит миниатюрный радиосигналлер, срабатывающий при прекращении жизнедеятельности носителя.<BR>
```suggestion
<b>Функционал:</b> Содержит миниатюрный радиопередатчик, срабатывающий при прекращении жизнедеятельности носителя.<BR>
```

2024-02-29 19:16 UTC, KandreyKandrey commented on code/game/objects/items/weapons/implants/implant.dm
> +<b>Функционал:</b> Содержит миниатюрный сигналлер, активирующий встроенный микротазер по сигналу.<BR>
```suggestion
<b>Функционал:</b> Содержит миниатюрный приёмник, который по сигналу активирует встроенный микроэлектрошокер.<BR>
```

2024-02-29 19:18 UTC, KandreyKandrey commented on code/game/objects/items/weapons/implants/implantcase.dm
> +	desc = "Футляр, содержащий имплант отслежения."
```suggestion
	desc = "Футляр, содержащий имплант слежения."
```

2024-02-29 19:19 UTC, KandreyKandrey commented on code/game/objects/items/weapons/implants/implantcase.dm
> +	desc = "Футляр, содержащий имплант с."
1) какой это имплант то?
2) в описании слово специально не дописали, или случайно?

2024-02-29 19:19 UTC, KandreyKandrey commented on code/game/objects/items/weapons/implants/implantcase.dm
> +	gender = MALE
а где перевод тут и ниже?

2024-02-29 19:20 UTC, KandreyKandrey commented on code/game/objects/items/weapons/implants/implantfreedom.dm
> +	to_chat(source, "Вы слышите как что-то легонько щёлкнуло.")
```suggestion
	to_chat(source, "Вы слышите, как что-то легонько щёлкнуло.")
```

2024-02-29 19:21 UTC, KandreyKandrey commented on code/game/objects/items/weapons/implants/implantpad.dm
> +	desc = "Используется для анализа имплнатов."
```suggestion
	desc = "Используется для анализа имплантов."
```

2024-02-29 19:22 UTC, KandreyKandrey commented on code/game/objects/items/weapons/implants/implantpad.dm
> +		dat += "Пожалуйста вставьте упаковку с имплантом внутри!"
```suggestion
		dat += "Пожалуйста, вставьте упаковку с имплантом внутри!"
```

2024-02-29 19:23 UTC, KandreyKandrey commented on code/game/objects/items/weapons/implants/mindshield.dm
> +		to_chat(H, "<span class='notice'Вы ощущаете чувство покоя и безопасности. Теперь вы защищены от промывания мозгов.</span>")
'вы ощущаете'
или
'вы чувствуете'
но не вместе их использовать

2024-02-29 19:26 UTC, KandreyKandrey commented on code/game/objects/items/weapons/implants/mindshield.dm
> +	<b>Важные примечания:</b> Персоналу, которому вводится это устройство, как правило, гораздо более лояльны к компании.<BR>
```suggestion
	<b>Важные примечания:</b> Персонал, которому вводится это устройство, как правило, гораздо более лоялен компании.<BR>
```

2024-02-29 19:27 UTC, KandreyKandrey commented on code/game/objects/items/weapons/implants/mindshield.dm
> +				to_chat(M, "<span class='danger'>Вам вживили [CASE(src, NOMINATIVE_CASE)], и теперь вы должны служить НТ. Ваша прежняя миссия теперь не имеет значения. Слава НТ!</span>")
```suggestion
				to_chat(M, "<span class='danger'>Вам вживили [CASE(src, NOMINATIVE_CASE)], и теперь вы должны служить НТ. Ваша прежняя миссия больше не имеет значения. Слава НТ!</span>")
```

2024-02-29 20:18 UTC, muWander commented on code/game/objects/items/weapons/implants/implantcase.dm
> +	desc = "Футляр, содержащий имплант отслежения."
> Ммм, не согласен. Жду мнение других и те кто будет ревью делать из переводчиков.

на вики, в космозаконе, в сопе везде чип слежения

2024-03-07 17:43 UTC, maleyvich requested changes
что-то может быть спорным но рекомендую приглядеться

2024-03-07 17:43 UTC, maleyvich commented on code/game/objects/items/weapons/implants/implantcase.dm
> +	desc = "Футляр, содержащий имплант \"Защита разума\""
я бы предпочёл привести к общему виду описаний футляров
или же у остальных сделать как здесь.
```suggestion
	desc = "Футляр, содержащий имплант защиты разума"
```

2024-03-07 17:43 UTC, maleyvich commented on code/game/objects/items/weapons/implants/implanter.dm
> +				user.visible_message("<span class ='userdanger'>[M] [(ANYMORPH(M, "был", "была", "было", "были"))] [(ANYMORPH(M, "имплантирован", "имплантирована", "имплантировано", "имплантированы"))] [user].</
в чем прикол использовать аниморфы когда можно использовать иные инструменты (верб_ру или даже проверку на гендер моба) я не понимаю, но видимо это нужно

2024-03-07 17:43 UTC, maleyvich commented on code/game/objects/items/weapons/implants/implantfreedom.dm
> +		<b>Целостность:</b> Заряд аккумулятора в импланте очень слаб, часто сокращая его количество
```suggestion
		<b>Целостность:</b> Несовершенство технологии не позволяет установить более лучший аккумулятор, из-за чего имплант достаточно быстро выходит из строя.
```

2024-03-07 17:43 UTC, maleyvich commented on code/game/objects/items/weapons/implants/implantpad.dm
> +			dat += "Упаковка от импланта пуста."
упаковка? а может быть ФУТЛЯР?
```suggestion
			dat += "Футляр от импланта пуст."
```

2024-03-07 17:43 UTC, maleyvich commented on code/game/objects/items/weapons/implants/implantpad.dm
> +		dat += "Пожалуйста, вставьте упаковку с имплантом внутри!"
предлагаю также заменить слово упаковка на футляр

2024-03-07 17:43 UTC, maleyvich commented on code/game/objects/items/weapons/implants/implantuplink.dm
> +	cases = list("аплинк имплант", "аплинк импланта", "аплинк импланту", "аплинк имплант", "аплинк имплантом", "аплинк импланте")
может быть имплант "Аплинк"? вообще аплинк это название устройства, программного обеспечения
я думаю, что переводить так не стоит но ваше мнение

2024-03-07 17:48 UTC, maleyvich commented on code/game/objects/items/weapons/implants/implantuplink.dm
> +	cases = list("аплинк имплант", "аплинк импланта", "аплинк импланту", "аплинк имплант", "аплинк имплантом", "аплинк импланте")
ну раз начали надо продолжать...
потом это обязательно кто-то пофиксит

2024-03-09 09:07 UTC, daedrowe commented on code/game/objects/items/weapons/implants/mindshield.dm
> +		H.visible_message("[H] внезапно становится очень красным и начинает извиваться. В воздухе появляется странный запах....", \
```suggestion
		H.visible_message("[H] внезапно становится очень красным и начинает корчиться. В воздухе появляется странный запах....", \
```

2024-03-16 14:01 UTC, maleyvich approved these changes
вроде бы нормас но насчет кое чего надо еще подумать

2024-03-16 14:01 UTC, maleyvich commented on code/game/objects/items/weapons/implants/implantuplink.dm
> +	to_chat(source, "Имплантат свободы можно активировать с помощью эмоции [src.activation_emote], <B>скажите *[src.activation_emote]</B> чтобы попытаться активировать его.")
меня все ещё смущает то, что эмоции надо ГОВОРИТЬ - но ладно...

2024-03-16 14:01 UTC, maleyvich commented on code/game/objects/items/weapons/implants/mindshield.dm
> +	cases = list("абстрактный имплант", "абстрактного импланта", "абстрактному импланту", "абстрактный имплант", "абстрактным имплантом", "абстрактном импланте")
имплант абстрактности?

2024-03-23 18:04 UTC, volas commented on code/game/objects/items/weapons/implants/implant.dm
> +	name = "compressed matter implant" // этот имплант не используется и ниже содержит инфу для оповещалки о смерти
тут я не буду дергать уже, но комментарии стоит писать всегда на английском

2024-03-23 18:06 UTC, merged