Больше бюрократии или же переносим формы с вики
TauCetiStation/TauCetiClassic pull request #12913
Opened 2024-03-05 00:46 UTC by AzzyDreemurr13

## Описание изменений
 Resolves #12910
Добавлены 4 формы от Ke-nt и поправлен текст в названиях форм
## Почему и что этот ПР улучшит
Больше бюрократии во имя бюрократии
## Авторство
Я и Co-Authored-By: Ke-nt0 <86300307+Ke-nt0@users.noreply.github.com>

## Чеинжлог
:cl: Azzy.Dreemurr, Ke-nt0
 - tweak: Добавлено 4 новые формы 
- spellcheck: Название форм откорректировано
- add: [sname] - при написание на бумаге пишет текущую станцию

2024-03-05 00:46 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2024-03-05 09:12 UTC, AirBlack requested changes
сделай плейсхолдер для названия станции, а то когда другие карты, формы все равно с титульником исхода идут, тупость. В билде где-то была переменная с названием станции

2024-03-05 10:21 UTC, AirBlack commented
Делай в этом ПРе. Ты же лезешь в ПРы с фичами с просьбами сделать перевод, который можно было вполне отдельно делегировать переводчикам после мержа фичи, так почему бы и тебе в ПРе на перевод не всунуть крутую фичу. Либо не лезь в ПРы с фичами с просьбами переводов.

2024-03-05 10:25 UTC, AirBlack commented
я даже не буду читать что ты тут написал. специально для тебя нашел, глобальный прок station_name_ru(), добавь плейсхолдер типа [station_name] в формы

2024-03-05 11:08 UTC, AirBlack commented
давай давай работай, я даже нашел тебе где это добавить, в проке /obj/item/weapon/paper/proc/parsepencode(t, obj/item/weapon/pen/P, mob/user, iscrayon = 0) туда добавляешь такое

`t = replacetext(t, "\[sname\]", station_name_ru())`

в конец добавь просто и замени везде КСН ИСХОД в документах на [sname]

2024-03-07 06:11 UTC, AirBlack approved these changes
Малаца увожаю. Прости что долго отвечал, просто в Екб полетел к семье и девушке, не видел....

2024-03-09 21:01 UTC, Chip11-n approved these changes

2024-03-09 21:01 UTC, Chip11-n commented on code/modules/paperwork/predefined_forms.dm
> +    index = "3F"
Индекс и должен меняться?

2024-03-20 02:59 UTC, AirBlack commented
Стыд и срам, сервер сдох, ментейнеры две недели не мержат

2024-03-21 00:53 UTC, merged