Фикс обычных спрайта дисков при спавне
TauCetiStation/TauCetiClassic pull request #12945
Opened 2024-03-12 15:45 UTC by Slavik2001

## Описание изменений
Теперь спрайты обычных дисков не будет на весь тайл, а будут использовать свой ворлд стейт
## Почему и что этот ПР улучшит
fixes https://github.com/TauCetiStation/TauCetiClassic/issues/12943
fixes https://github.com/TauCetiStation/TauCetiClassic/issues/12938
## Дополнительно
Попробовал сократить код чтобы он не был таким страшным, но максимум только можно убрать итем_стейт без дальнейших проблем.
Если убрать айкон стейт, то он будет брать самый первый спрайт в ДМИ файле до первого интеракта с диском
Убирать инвентори - некорректное отображение в руке/инвенторе других предметов
Ну а про ворд стейт не вижу смысла расписывать
## Авторство
Я

## Чеинжлог
:cl: Slavik2001
 - bugfix: Фикс бага с спрайтами обычных дисков.

2024-03-12 15:45 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2024-03-14 04:03 UTC, volas requested changes

2024-03-14 04:03 UTC, volas commented on code/game/objects/items/weapons/disks.dm
> -	item_state_inventory = "datadisk0"
проблема ведь была только с ``/obj/item/weapon/disk/data``, у которых иконка сбрасывалась в atom_init?

обычный /obj/item/weapon/disk должен быть в порядке, и тут кажется стейты нужны

2024-03-14 04:03 UTC, volas commented on code/game/objects/items/weapons/disks.dm
> +	update_world_icon()
предлагаю на это место просто вызов родителя ``. = ..()``, который выше, перенести. Он там тоже обновляет иконку, и так не будет двойной работы.

К дискам ниже тоже относится

2024-03-15 19:01 UTC, Slavik2001 commented
В сумках и руках они должны быть такими

2024-03-19 12:01 UTC, merged