Robot Eyes Glow
TauCetiStation/TauCetiClassic pull request #12948
Opened 2024-03-13 08:32 UTC by BasiaBelov

## Описание изменений
Теперь у боргов будут светиться глазки в темноте.
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/115452414/db2a3f8e-26e1-4b0b-abdb-9974cc508fbc)

## Почему и что этот ПР улучшит
Логику.
## Авторство
Всё своими мозгами, *возможно...*
## Чеинжлог
:cl:Basia
 - tweak: Теперь у боргов буквально светятся глаза

2024-03-13 08:32 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2024-03-13 12:47 UTC, ZER0-In commented
Ебало синдиборгов, которые прячутся в темноте представили? 
А в целом ладно.

2024-03-13 15:56 UTC, BasiaBelov commented
Ну это уже ~~ЛГБТ~~ эРЖиБи кринж.

2024-04-06 09:45 UTC, BasiaBelov commented
Брух

2024-04-08 03:52 UTC, volas requested changes
выше реквесты от пикачушки, комментарий для статуса

2024-04-23 10:03 UTC, BasiaBelov commented
Да кто меня ждёт...

2024-04-26 17:55 UTC, KIBORG04 commented
Я жду

2024-05-18 02:08 UTC, closed without merging