Перевод ядерной боеголовки
TauCetiStation/TauCetiClassic pull request #12961
Opened 2024-03-15 18:10 UTC by AzzyDreemurr13

## Описание изменений
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/74739991/d09b22da-b0c6-4db6-a01a-950451d065f4)
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/74739991/bdab40cd-c634-429a-813a-173cf370a8c8)
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/74739991/ab387f80-f452-431f-abf3-d5711f010c2d)
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/74739991/2f9f733b-fb80-450d-8cc3-3a79371f6b7b)
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/74739991/d0cf96cc-04e6-453d-af4f-1da20e6a3c72)

## Почему и что этот ПР улучшит
Переводим интерфейсы и улучшаем опыт для новичков

## Авторство
@maleyvich перевёл, я доделал интерфейс под перевод 

## Чеинжлог

:cl: Malevich, Azzy.Dreemurr
 - ru: Интерфейс Ядерной боеголовки получил перевод

2024-03-15 18:10 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2024-03-15 20:43 UTC, 4310V343k commented on code/game/gamemodes/modes_gameplays/nuclear/nuclearbomb.dm
> +			to_chat(user, "<span class = 'red'>Ты не можешь сделать это!</span>")
так ты или вы во всем билде?

2024-03-15 20:44 UTC, 4310V343k commented on tgui/packages/tgui/interfaces/NuclearBomb.js
> +                {timeLeft} секунд
ура добавляем функции для падежей и чисел ещё и в интерфейсы

2024-03-16 10:12 UTC, maleyvich requested changes
я кое что забыл!

2024-03-16 10:12 UTC, maleyvich commented on code/game/gamemodes/modes_gameplays/nuclear/nuclearbomb.dm
> +			to_chat(user, "<span class = 'red'>Ты не можешь сделать это!</span>")
```suggestion
			to_chat(user, "<span class = 'red'>Вы не можете сделать это!</span>")
```

2024-03-16 10:12 UTC, maleyvich commented on code/game/gamemodes/modes_gameplays/nuclear/nuclearbomb.dm
> +			to_chat(user, "<span class = 'red'>Бомба не может быть здесь расположена...</span>")
```suggestion
			to_chat(user, "<span class = 'red'>Бомба не может быть здесь развёрнута...</span>")
```

2024-03-16 10:12 UTC, maleyvich commented on code/game/gamemodes/modes_gameplays/nuclear/nuclearbomb.dm
> +		to_chat(user, "<span class = 'red'>Бомба не реагирует, она сломана?</span>")
```suggestion
		to_chat(user, "<span class = 'red'>Бомба не реагирует, возможно она сломана?</span>")
```

2024-03-16 10:12 UTC, maleyvich commented on tgui/packages/tgui/interfaces/NuclearBomb.js
> +                disabled={code==="ОШИБКА" && key!=="R" || !hasDisk || !deployed}
```suggestion
                disabled={code==="ERROR" && key!=="R" || !hasDisk || !deployed}
```

2024-03-16 10:12 UTC, maleyvich commented on tgui/packages/tgui/interfaces/NuclearBomb.js
> +                {authorized ? "ДОСТУП РАЗРЕШЁН" : hasDisk ? "ВВЕДИТЕ КОД" : deployed ? "ВСТАВЬТЕ ДИСК" : "ДИСК НЕ ВСТАВЛЕН"}
у мя почему-то DEPLOY высвечивалось именно тогда, когда диск был НЕ ВСТАВЛЕН
жду альтернатив на "доступ разрешен" - в моей голове есть вариант с РАЗРЕШЕНО, но разрешено что???

2024-03-16 10:12 UTC, maleyvich commented on tgui/packages/tgui/interfaces/NuclearBomb.js
> +                {timeLeft} секунд
а что поделать?...

2024-03-16 10:12 UTC, maleyvich commented on code/game/gamemodes/modes_gameplays/nuclear/nuclearbomb.dm
> +		to_chat(user, "<span class ='boldwarning'>Это - обманка!</span>")
```suggestion
		to_chat(user, "<span class ='boldwarning'>Это обманка!</span>")
```

2024-03-16 10:13 UTC, maleyvich commented
благодарим мистера пикачуху за все найденные ошибки
но проблема с секундами неоспоримо серьёзная...

2024-03-17 10:34 UTC, KandreyKandrey commented on code/game/gamemodes/modes_gameplays/nuclear/nuclearbomb.dm
> +				to_chat(user, "[C_CASE(src, NOMINATIVE_CASE)] жужжит, панель управления все ещё заблокирована!")
```suggestion
				to_chat(user, "[C_CASE(src, NOMINATIVE_CASE)] жужжит, а панель управления всё ещё заблокирована!")
```

2024-03-17 10:35 UTC, KandreyKandrey commented on code/game/gamemodes/modes_gameplays/nuclear/nuclearbomb.dm
> +						user.visible_message("[CASE(user, NOMINATIVE_CASE)] заканчивает перерезать что-то в [CASE(src, DATIVE_CASE)].", "Вы прорезали первый слой.")
```suggestion
						user.visible_message("[CASE(user, NOMINATIVE_CASE)] заканчивает прорезать что-то в [CASE(src, DATIVE_CASE)].", "Вы прорезали первый слой.")
```

2024-03-17 10:35 UTC, KandreyKandrey commented on code/game/gamemodes/modes_gameplays/nuclear/nuclearbomb.dm
> +					user.visible_message("[CASE(user, NOMINATIVE_CASE)] начинает бить по [CASE(src, DATIVE_CASE)].", "Вы начали открывать крышку с помощью [CASE(O, GENITIVE_CASE)]...")
'forcing open', а в переводе просто 'открывать'
(ниже аналогично)

2024-03-17 10:35 UTC, KandreyKandrey commented on code/game/gamemodes/modes_gameplays/nuclear/nuclearbomb.dm
> +						user.visible_message("[CASE(user, NOMINATIVE_CASE)] заканчивает перерезать что-то в [CASE(src, DATIVE_CASE)].", "Вы закончили разрезать защитную пластину.")
почему 'прорезать' меняется на 'перерезать' ?

2024-03-17 10:35 UTC, KandreyKandrey commented on code/game/gamemodes/modes_gameplays/nuclear/nuclearbomb.dm
> +						user.visible_message("[CASE(user, NOMINATIVE_CASE)] заканчивает бить [CASE(src, GENITIVE_CASE)].", "Теперь вы можете напрямую взаимодействовать с механизмом [CASE(src, GENITIVE_CASE)]. Use scre
перевод забыл

2024-03-17 10:35 UTC, KandreyKandrey commented on code/game/gamemodes/modes_gameplays/nuclear/nuclearbomb.dm
> +		to_chat(user, "<span class = 'red'>Бомба не реагирует, она сломана?</span>")
одно предложение
два перевода

2024-04-08 04:12 UTC, volas commented on code/game/gamemodes/modes_gameplays/nuclear/nuclearbomb.dm
> +			to_chat(user, "<span class = 'red'>Бомба не может быть здесь расположена...</span>")
```suggestion
			to_chat(user, "<span class = 'red'>Бомба не может быть развёрнута здесь.</span>")
```

2024-04-08 04:13 UTC, volas commented on code/game/gamemodes/modes_gameplays/nuclear/nuclearbomb.dm
> +		to_chat(user, "<span class = 'red'>Вы закрываете несколько панелей, чтобы сделать [CASE(src, ACCUSATIVE_CASE)] развернутой.</span>")
сделать развернутой плохо звучит, следует переделать

2024-04-08 04:14 UTC, volas commented on code/game/gamemodes/modes_gameplays/nuclear/nuclearbomb.dm
> +		visible_message("<span class='notice'>[CASE(usr, NOMINATIVE_CASE)] начал вставлять [CASE(src, ACCUSATIVE_CASE)] внутрь [CASE(D, GENITIVE_CASE)]!</span>","<span class='notice'>Вы начали вставлять [C
начал загружать бомбу в дроппод

2024-04-08 04:16 UTC, volas commented on code/game/gamemodes/modes_gameplays/nuclear/nuclearbomb.dm
> +		to_chat(user, "<span class = 'red'>Бомба не реагирует. Может она сломана?</span>")
как вы раз за разом умудряетесь переводить одно и то же с расстоянием в пару строк, но по разному

2024-04-08 04:18 UTC, volas commented on code/game/gamemodes/modes_gameplays/nuclear/nuclearbomb.dm
> +					user.visible_message("[CASE(user, NOMINATIVE_CASE)] начинает что-то прорезать в [CASE(src, ACCUSATIVE_CASE)], будто [user.gender == MALE ? "он" : "она"] знает, что нужно делать.", "С [CASE(O, AB
имхо "прорезать что-то" сваркой странно звучит, но я не могу сходу предложить своё

2024-04-08 04:18 UTC, volas requested changes
пара вещей требует исправления

2024-04-15 05:41 UTC, merged

2024-09-10 12:20 UTC, TauKitty commented
Этот запрос на слияние был упомянут в **Tau Ceti Station Forum**. Там могут быть соответствующие подробности:

https://forum.taucetistation.org/t/nabor-v-podval-perevodchikov-2-0/43694/1