Luck special bullet dodge armor
TauCetiStation/TauCetiClassic pull request #12979
Opened 2024-03-18 21:13 UTC by Deahaka

## Описание изменений
По бронированным целям легче попасть, по небронированным сложнее, но только в те места, где небронировано. Рюкзак на спине при наличии брони понижает удачу так как становишься неповоротливым. Перчатки забирают в себя удачу, магбуты и риги тоже.
## Почему и что этот ПР улучшит
Прикольная механика Удача для повышения выживаемости слабобронированных юзеров которые не снарядились на все случаи жизни и отдали всё на волю богине Фортуне.
## Авторство
Я

## Чеинжлог
не нужен, это же просто Удача!

2024-03-18 21:13 UTC, TauKitty commented
###### Changelog status: :radio_button: No changelog

2024-03-18 21:16 UTC, LudwigVonChesterfield commented on code/modules/projectiles/gun.dm
> +	special_armor = list(BULLET_DODGE = 5)
А не нужно вызывать recalculate_special_armor?

2024-03-18 21:16 UTC, LudwigVonChesterfield commented on code/modules/projectiles/projectile.dm
> +	if(distance < 1) // cant miss almost pointblank (1 or 2 tiles between target and start)
или комметарий обновить или равно вернуть

2024-03-18 21:18 UTC, LudwigVonChesterfield commented on code/game/objects/items/weapons/storage/backpack.dm
> +	if(slot_equipped == SLOT_BACK)
попробуй развернуть ифки так чтобы табы не шли дальше двух уровней
```
. = ..()
if(slot_equipped != SLOT_BACK)
    return
if(!ishuman(user))
    return
    
    и так дальше...
    ```

2024-03-18 21:19 UTC, LudwigVonChesterfield commented on code/game/objects/items/weapons/storage/backpack.dm
> +	if(slot == SLOT_BACK)
попробуй развернуть ифки так чтобы табы не шли дальше двух уровней

2024-03-18 21:20 UTC, LudwigVonChesterfield commented on code/modules/clothing/suits/armor.dm
> +	if(istype(user.back, /obj/item/weapon/storage/backpack))
как раз хорошее было бы место для сигналов... чтобы броня подписывалась на сигнал экипировки у куклы и при надевании рюкзака получала дебафф...

2024-03-18 21:21 UTC, LudwigVonChesterfield commented on code/modules/clothing/suits/armor.dm
> +	if((body_parts_covered & UPPER_TORSO) && (body_parts_covered & LOWER_TORSO)  && (body_parts_covered & ARMS)  && (body_parts_covered & LEGS))
мне кажется вот отсюда и ниже можно было бы инициализировать один раз при атом ините.

по сути прок существует только чтобы отреагировать на то что рюкзак надели. может перепишем на сигнал и избавимся от постоянной потребности вызывать recalculate_special_armor?

2024-03-18 21:48 UTC, LudwigVonChesterfield commented on code/modules/clothing/suits/armor.dm
> +		special_armor = list(BULLET_DODGE = -15)
тут либо не хватает ретюрна либо строчки ниже можно вынести над этой проверкой

2024-03-18 21:50 UTC, LudwigVonChesterfield commented on code/modules/clothing/suits/armor.dm
> +/obj/item/clothing/suit/storage/flak/recalculate_special_armor(mob/user)
не понимаю почему именно тут нет проверки с броней в мили

2024-03-18 21:53 UTC, LudwigVonChesterfield requested changes
если рюкзак будет подписываться на ивент надевания брони, вместо наоборот, то не придётся копипастить каждому виду брони которой не плевать на рюкзак.

2024-03-18 22:01 UTC, Deahaka commented on code/modules/clothing/suits/armor.dm
> +/obj/item/clothing/suit/storage/flak/recalculate_special_armor(mob/user)
У флажков нет статов больше 60

2024-03-18 22:02 UTC, LudwigVonChesterfield commented on code/modules/clothing/suits/armor.dm
> +/obj/item/clothing/suit/storage/flak/recalculate_special_armor(mob/user)
ПОКА-ЧТО

2024-03-18 23:05 UTC, Deahaka commented on code/modules/clothing/suits/armor.dm
> +	if((body_parts_covered & UPPER_TORSO) && (body_parts_covered & LOWER_TORSO)  && (body_parts_covered & ARMS)  && (body_parts_covered & LEGS))
это стоило ещё времени но я сделал.

2024-03-18 23:41 UTC, LudwigVonChesterfield commented on code/game/objects/items/weapons/storage/backpack.dm
> +	if(slot == SLOT_BACK)
попробуй-попробуй, ты ещё не попробовал

2024-03-18 23:42 UTC, LudwigVonChesterfield approved these changes
код красивый мне очень понравился, я правда ещё пару мелочных заметок оставлю

2024-03-18 23:42 UTC, LudwigVonChesterfield commented on code/__DEFINES/dcs/signals.dm
> +#define COMSIG_MOB_DROPPED "mob_dropped"
я бы подсмотрел как называется этот сигнал на ТГ для наглядности. и тоже бы передавал slot

2024-03-18 23:43 UTC, LudwigVonChesterfield commented on code/game/animation_helpers.dm
> +	animate(pixel_x = x_o, pixel_y = y_o, time = speed, easing = CIRCULAR_EASING|EASE_OUT)
комплексная проблема, но если во время комбухи по тебе попадёт пуля может произойти ржака. не думаю что будет справедливо заставить этот ПР решать это, но возможно вместо initial(A.pixel_x) надо юзать default_pixel_x (или что-то подобное что у нас наверняка есть, подсмотри в комбухах)

2024-03-18 23:44 UTC, LudwigVonChesterfield commented on code/game/animation_helpers.dm
> +	animate(pixel_x = x_o, pixel_y = y_o, time = speed, easing = CIRCULAR_EASING|EASE_OUT)
для тряски от ударов халка/сильных мобов делается отдельная картинка которая выглядит так же и трясётся чтобы этой проблемы не было (а начальный предмет становится невидимым)

2024-03-18 23:47 UTC, LudwigVonChesterfield commented on code/game/atoms.dm
> +	var/list/special_armor = list(BULLET_DODGE = 0)
```suggestion
	var/list/special_armor = list()
```

если в списке нет ключа то список[ключ] вернёт null который волшебным образом конвертится в 0.

но почему нельзя BULLET_DODGE сделать одним из показателей armor? (а потом заставить кого-то другого броню сделать компонентой, это же так весело...)

2024-03-18 23:48 UTC, LudwigVonChesterfield commented on code/game/atoms.dm
> +	var/list/special_armor = list(BULLET_DODGE = 0)
а ещё бонусные очки если var/list/special_armor

а потом в том месте где она внатуре юзается проверять или список существует. сэкономило бы немножко памяти!!!

2024-03-18 23:49 UTC, LudwigVonChesterfield commented
Не забудь добавить ченжлог, или обозвать мутатором.

Если планируем сначала ставить в ТМ думаю нужна ещё темка на форуме, как минимум для прикола.

2024-03-19 10:02 UTC, arygal commented
Как по мне: робуст механики основаные на рандоме - очень неприятная фигня. Твой же механ стиля только под другим соусом. Уклоняться стоит тыкая WASD.

2024-03-19 11:49 UTC, volas commented
автор выше прав, все те же проблемы, что и у стиля. Какая-то сложная и не очевидная механика с сомнительным профитом, которая усложняет код.

2024-03-19 11:49 UTC, closed without merging