Fix donut Chaos and new candy's
TauCetiStation/TauCetiClassic pull request #12974
Opened 2024-03-17 12:03 UTC by Pufikc

## Описание изменений
1. Был изменён состав рецепта пончика Хаоса. Добавил вишнёвый пончик и убрал воду, потому что вода с некоторыми составными веществами из рецепта, создавала другие два вещества (Plant-B-Gone и Space jenkem) и тем самым рецепт становился не рабочим. 
Сейчас рецепт в микроволновке такой -> 5 унции сахара + 5 унции соли + 5 унции топлива + 5 унции кофе + по 5 унции токсина, слип-токсина и анти-токсина + Все виды пончиков (кроме слаймового!)

В файлах лежали 4 спрайты еды, которые не использовались нигде и лежали без дела. Сделал для них рецепт:
2. Добавлен рецепт для розового и радужного червячка.
Рецептура и состав идентичны, как и у розовой и радужной сахарной ваты.
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/151707834/e20f295e-a7da-49ce-8fab-e073a90bf7e4)

3. Добавлены кукурузные хлопья. Также мёд впервые где-то будет использоваться в рецепте!
Рецепт в микроволновке -> кукуруза + 5 унции мёда.
Итог: 
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/151707834/165e9a28-e86a-4c8c-92ee-a71c1afec4fc)

4. И напоследок добавил Загадочный чупа-чупс, рецепт сложный, но вот состав его загадочный как и сам он!
Рецепт в конфетницу -> все виды чупа-чупса + по 5 унции токсина, слип-токсина, анти-токсина и карпо-токсина.
Итог загадки:
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/151707834/84ee74bd-b13d-4d51-978e-f002a52db567)

## Почему и что этот ПР улучшит
Фикс пончика Хаоса.
Новые рецепты для кухни с неиспользованными ранее спрайтами.
Повару даётся больше взаимодействия, чтобы получить вещества токсинов, мясо карпа или карпо-токсина и мёд для рецептов.
## Авторство
Pufkc

## Чеинжлог
:cl: Pufikc
- bugfix: Починен рецепт пончика Хаоса.
- add: Добавлены четыре новых рецепта для кухни.

2024-03-17 12:03 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2024-03-17 12:19 UTC, Pufikc commented
а что с проверкой, всё красное, я не понимаю..

2024-03-17 13:59 UTC, liteyzz commented
загадочный чупачупс бля ахаххахахахахаха

2024-03-17 14:03 UTC, LudwigVonChesterfield commented
фиксы лучше не мешать с фичами, фикс пончиков я бы замержил сразу не глядя, а тут теперь думать надо...

2024-03-17 14:04 UTC, LudwigVonChesterfield commented on code/modules/reagents/reagent_containers/food/snacks.dm
> +	list_reagents = list("adminordrazine" = 0.25)
ты чего...

2024-03-17 14:06 UTC, LudwigVonChesterfield commented on code/modules/reagents/reagent_containers/food/snacks.dm
> +	var/datum/reagent/random_reagent = pick(global.reagents_list)
можно не создавать реагент чтобы потом брать у него айди, random_reagent это уже id
```
reagents.add_reagent(pick(global.reagents_list), 5)
```

2024-03-17 14:18 UTC, Pufikc commented on code/modules/reagents/reagent_containers/food/snacks.dm
> +	list_reagents = list("adminordrazine" = 0.25)
А.. мне лучше убрать админодразин, ибо там и так код на рандомные вещества?

2024-03-17 14:22 UTC, LudwigVonChesterfield commented on code/modules/reagents/reagent_containers/food/snacks.dm
> +	list_reagents = list("adminordrazine" = 0.25)
ну у тебя сейчас в каждом чупа чупсе немножко АДМИН РЕДЖУВ сока

2024-03-17 14:23 UTC, LudwigVonChesterfield commented on code/modules/reagents/reagent_containers/food/snacks.dm
> +	list_reagents = list("nutriment" = 20, "psilocybin" = 1)
буквально на пару строчек кода выше червячок с наркотиками, в чем прикол ещё одного :(

2024-03-17 14:24 UTC, LudwigVonChesterfield commented on code/modules/food/recipes_candymaker.dm
> +	reagents = list("anti_toxin" = 5, "stoxin" = 5, "toxin" = 5, "carpotoxin" = 5)
из-за карпотоксина кажется никогда в жизни не скрафтят.

есть ли смысл копировать фишку пончика, когда и спрайт фиговый и фича уже есть?

2024-03-17 14:28 UTC, Pufikc commented on code/modules/food/recipes_candymaker.dm
> +	reagents = list("anti_toxin" = 5, "stoxin" = 5, "toxin" = 5, "carpotoxin" = 5)
Ну.. тогда рецепт не нужный получается?

2024-03-17 14:28 UTC, Pufikc commented on code/modules/reagents/reagent_containers/food/snacks.dm
> +	list_reagents = list("nutriment" = 20, "psilocybin" = 1)
У сахарной ваты всё также.. просто кто-то забыл червячков допилить

2024-03-17 14:29 UTC, Pufikc commented on code/modules/reagents/reagent_containers/food/snacks.dm
> +	list_reagents = list("adminordrazine" = 0.25)
Ох.. точно

2024-03-17 16:03 UTC, LudwigVonChesterfield commented on code/modules/food/recipes_candymaker.dm
> +	reagents = list("anti_toxin" = 5, "stoxin" = 5, "toxin" = 5,)
```suggestion
	reagents = list("anti_toxin" = 5, "stoxin" = 5, "toxin" = 5)
```

2024-03-17 16:03 UTC, LudwigVonChesterfield commented
Ждём ревью спрайтов.

2024-03-17 16:05 UTC, WatlerJe approved these changes

2024-03-17 16:06 UTC, LudwigVonChesterfield approved these changes

2024-03-21 01:40 UTC, LudwigVonChesterfield requested changes
Совсем забыл, вот это поправить надо

![image](https://github.com/TauCetiStation/TauCetiClassic/assets/17705613/f046a83b-4478-4038-86c9-e1cbad2d84e0)

2024-03-21 14:51 UTC, Pufikc commented
Я исправил, но теперь там 2 warning

2024-03-21 15:18 UTC, Pufikc commented
Что поделать.. я только учусь

2024-03-21 16:18 UTC, LudwigVonChesterfield commented on code/modules/food/recipes_microwave.dm
> +
```suggestion

```

2024-03-21 16:19 UTC, LudwigVonChesterfield approved these changes
супер. круть.

2024-03-23 16:59 UTC, volas commented
спрайты пипец страшные, но раз как плейсхолдер то ладно

2024-03-23 16:59 UTC, merged

2024-03-23 17:16 UTC, volas commented on code/modules/reagents/reagent_containers/food/snacks.dm
> +	reagents.add_reagent(pick(global.reagents_list), 5)
> ``WARNING: The sucker? attempted to add a reagent called '/datum/reagent/consumable/ethanol/manhattan' which doesn't exist. ()``

тут надо возможно делать пик из ``chemical_reagents_list``, иначе оно не работает