[WiP] TGUI для Identification Computer
TauCetiStation/TauCetiClassic pull request #13008
Opened 2024-03-28 21:34 UTC by Slavik2001

## Описание изменений
Замена НаноУИ на ТГУИ
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/123300305/967204a9-5d90-4570-9c58-2271edb8542a)

Пушнул, так как понял что это чуток сложнее и может затянутся на очень долго, а с поддержкой остальным прогресс будет быстрее

Аксес лист - выбраные отделы не отображаются зеленым если на карте такой отдел имеется.
Полная выдача и убирание всех доступов работает, но отдельная выдача нет

Манифест - отсутствует, так как я за него пока что ещё не брался просто

Принт - тоже что и выше

## Почему и что этот ПР улучшит
Красиво и часть https://github.com/TauCetiStation/TauCetiClassic/issues/7347
## Авторство
Я+люди которые мне тут помогут, часть кода взята с https://github.com/ss220-space/Paradise

## Чеинжлог
:cl: Slavik2001
 - image: TGUI для Identification Computer.

2024-03-28 21:34 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2024-03-29 09:21 UTC, AirBlack requested changes

2024-03-29 09:21 UTC, AirBlack commented on code/game/machinery/computer/card.dm
> +#define IDCOMPUTER_SCREEN_PRINT 2
undef в конце файла, не вижу андефов и не вижу смысла этим пользоваться вне файла

2024-03-29 09:21 UTC, AirBlack commented on code/game/machinery/computer/card.dm
>  	return formatted
Вырежи, раз больше не юзаешь

2024-03-29 11:50 UTC, Slavik2001 commented on code/game/machinery/computer/card.dm
>  	return formatted
Ну, вроде текст стал нормальным, осталось только доделать кнопки в аксес листе и всё. Я просто пока не пушну комитет с этим вырезом. А так проблема лишь с манифестом и принтом, я вообще не ебу как это сделать пока что.

2024-03-29 11:50 UTC, Slavik2001 commented on code/game/machinery/computer/card.dm
> +#define IDCOMPUTER_SCREEN_PRINT 2
Ок

2024-03-29 11:53 UTC, Slavik2001 commented
> Бери с ТГ лучше наверн, а так красава

Я бы взял, но когда я посмотрел на консоль у ТГ, то мне показалось что там намного сложнее
![Screenshot_20240329-135251](https://github.com/TauCetiStation/TauCetiClassic/assets/123300305/b0124ad8-4540-4d5a-a820-1e11f5535ad3)

2024-03-29 12:17 UTC, AirBlack commented
ок

2024-03-29 18:35 UTC, Slavik2001 commented
Вооооот..... На текущем этапе вся вкладка работает как надо, но я хз как сделать манифест и принт, пока что.....

2024-03-29 20:02 UTC, 4310V343k commented
зачем тут две секции?
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/56449763/3aeac5d6-7cd7-46e8-bb40-c0bb4eaa245c)

2024-03-29 20:05 UTC, Slavik2001 commented
Внутри аксеса уже есть свой лейбл/тайтл, я просто не знал и когда добавлял, то внимал тайтл этому сегменту XD

2024-03-30 17:42 UTC, Slavik2001 commented
Вотъ
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/123300305/8fcf85f9-e4f3-479b-9bdb-593520009c2b)

2024-03-30 18:26 UTC, Slavik2001 commented
В принципе... Всё готово и можно мержить, но я бы хотел увидить пока в ТМе и посмотреть что скажут насчет этого.

2024-04-04 17:10 UTC, maleyvich commented on code/game/machinery/computer/card.dm
> +	data["civilian_jobs"] = civilian_positions
centcom_positions

2024-04-04 17:11 UTC, Slavik2001 commented
Было бы неплохо. Спасибо

2024-04-08 20:29 UTC, Slavik2001 commented
Сделал привязку к навыкам для кнопок региона и фулл аксесов. На данный момент при отсутствии навыков, нажимая на 1 из них, то выбьет синий экран ТГУИ с ошибкой что подразумевается наличие функции(наличие навыков). Я пока хз как это решить. Disable внутри тупо не работает.....

(А вообще, как по мне, можно оставить как прикольную фичу, что неумеха при попытке выдать сразу несколько доступов выбивает комп в синий экран XD)

2024-04-15 05:49 UTC, volas commented on code/game/machinery/computer/card.dm
> +				data["all_centcom_access"] = all_centcom_access
вдобавок к вопросу ниже, наверху ты уже поменял по сравнению со старым кодом data["all_centcom_access"], и как-то выставляешь тут опять

2024-04-29 17:00 UTC, volas commented
Я почти всегда мимо прохожу из-за тега WiP, может в тм? По скринам выглядит здорово

2024-04-30 16:14 UTC, Slavik2001 commented
Ука... Началось

2024-04-30 16:58 UTC, Slavik2001 commented
Компилируется, но почему-то выдает ошибку в кодом 1 и запросом пересобрать ТГУИ...

2024-04-30 17:09 UTC, Slavik2001 commented
О. Ура

2024-05-01 09:58 UTC, Slavik2001 commented
> Я почти всегда мимо прохожу из-за тега WiP, может в тм? По скринам выглядит здорово

Я не против. Самому интересно как оно будет, но всё же есть не доделанные моменты:
1. То что Нинжа писал
2. Мне в ТГУИ не удалось спрятать кнопки фулл аксеса и регион аксес при отсуствии соответствующих навыков, но сама привязка есть. То есть - если навыка нет, то при попытке их использовать выдаст синий экран ТГУИ с ошибкой. Повторный клик же восстанавливает всё, но действие этих кнопок не задействуются

2024-05-15 14:22 UTC, volas commented on code/game/machinery/computer/card.dm
> +			mode = text2num(params["mode"])
на стороне клиента любые проверки обходятся, хорошо делать обе

2024-05-19 06:46 UTC, volas commented
посмотри комментарии пикачушки, с mode очень актуально, иначе можно с клиента отправить не валидный и тем самым скорее всего сломать консоль

2024-06-08 14:19 UTC, volas commented on code/game/machinery/computer/card.dm
> +	var/mode = 0
```suggestion
	var/mode = IDCOMPUTER_SCREEN_ACCESS
```

2024-06-08 14:19 UTC, volas commented on code/game/machinery/computer/card.dm
> +			mode = text2num(params["mode"])
```suggestion
			var/static/list/valid_modes = list(IDCOMPUTER_SCREEN_ACCESS, IDCOMPUTER_SCREEN_MANIFEST, IDCOMPUTER_SCREEN_PRINT)
			var/new_mode = text2num(params["mode"])
			if(new_mode in valid_modes)
				mode = new_mode
```

можно красивее, но через вебкомменты не удобно, так сойдет

2024-06-09 11:41 UTC, Slavik2001 commented
Локал мод добавил, а что с списком должностей хз че делать

2024-06-10 13:54 UTC, volas commented
Можешь на бэке проверять существование по тем же ``command_positions`` и прочим, на фронте не обязательно. Если центкомовский - еще по цекашному списку

2024-06-15 12:51 UTC, simb11 commented
при клике по select all менюшка ломается
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/84613249/b1f80680-c69f-4613-a69e-861ec574bd9e)

2024-06-15 13:44 UTC, Slavik2001 commented
Я уже писал, что при отсутствии навыка будет выдавать синий экран ТГУИ. То есть привязка к навыкам есть для выдачи вообще полного или полного для отдела.
На данный момент я хз как сделать чтобы этой кнопки не было если нету навыка.
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/123300305/144635d8-5b33-4f16-b8d5-6713f4fcfca6)

2024-07-05 04:31 UTC, Slavik2001 commented
Сделал. Проверяй

2024-07-13 15:12 UTC, Slavik2001 commented
Пока убирайте с ТМа. КрюМанифест почему-то сломался и никого не показывает

2024-07-14 22:31 UTC, Slavik2001 commented
Я пока не смог вдуплить из-за чего всё сломалось, просто сам манифест есть, но пустой. Он либо его не отправляет/получает, либо тупо не декодит HTML...

2024-07-24 05:38 UTC, volas commented
Ты доборешь этот пр? Если нужно помочь - слапни в дискорде

2024-07-26 18:55 UTC, Slavik2001 commented
Добороли этот манифест - победа

2024-08-08 08:11 UTC, Slavik2001 commented
Чё?! Блять...

2024-08-08 08:12 UTC, maleyvich commented
неплохо

2024-08-08 08:13 UTC, Slavik2001 commented
Как бля говорится.... Всё хуйня давай по новой

2024-08-08 08:16 UTC, Slavik2001 commented
Щас доламаю, закрою и сделаю заново...

2024-08-08 08:18 UTC, closed without merging

2024-08-08 14:27 UTC, KIBORG04 commented
Ресетнул бы коммиты