Возвращение базового доступа в карго парамедикам, перенос автолата
TauCetiStation/TauCetiClassic pull request #13014
Opened 2024-03-30 06:37 UTC by Unchi-unchi-un-chi-chi

## Описание изменений
Как я понял, проект с "Независимой Каргонией" оказался не реализованным до конца и заброшенным. Если это не так - прошу автора связаться. Было принято решение вернуть парамедикам доступ базовый доступ в карго, как оно раньше и было, ибо как-то странно что в всё ещё цивильный отдел станции у парамедов нет доступа. Однако, чтобы не наступать на те же грабли с тем, что парамедики забегали поюзать автолат - автолат был перенесёт за двери, к которым у парамедов уже нет доступа. Также туда же были перенесены сталь, стекло и мультитул.  Локация автолата указана на скрине, ресурсы и мультитул на соседнем столике.
![Screenshot_20240330-001251_1](https://github.com/TauCetiStation/TauCetiClassic/assets/86578193/24b7ddf4-a0f0-49af-8866-108a08a16c94)

## Почему и что этот ПР улучшит
Геймплей парамедиков, за счёт возвращения базового доступа в отдел. Геймплей тех, кого выкинуло в мусорку, за счёт того что к ним сразу могут подойти парамедики.
## Авторство
Unchi
## Чеинжлог
:cl:
 - tweak: Парамедикам возвращён доступ базовый доступ в карго.
 - map: Автолат с ресурсами перенесён вглубь карго, от лап парамедиков.

2024-03-30 06:37 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2024-03-30 06:40 UTC, Deahaka commented
Со стороны почты у них есть доступ, а в офис какой толк им ходить без автолата

2024-03-30 07:34 UTC, Fluffy-510 commented
Спасать тех кого смыли в мусорку

2024-03-30 07:36 UTC, simb11 commented
> Спасать тех кого смыли в мусорку

у них и сейчас есть (по идее) есть доступ к ленте

2024-03-30 07:36 UTC, Unchi-unchi-un-chi-chi commented
> Может ты ещё уборщику за одно починишь доступ? Ему тоже снесли как и парамедикам

Говно вопрос

2024-03-30 07:37 UTC, Unchi-unchi-un-chi-chi commented
> > Спасать тех кого смыли в мусорку
> 
> у них и сейчас есть (по идее) есть доступ к ленте

Нету)

2024-03-30 07:39 UTC, simb11 commented
есть же 
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/84613249/d545c229-bb8f-467e-a3f9-95771799a1d0)

2024-03-30 07:41 UTC, Unchi-unchi-un-chi-chi commented
Ладно, убедил

2024-03-30 07:43 UTC, Unchi-unchi-un-chi-chi commented
Если на остальных картах такая же схема то могу закрыть ПР)

2024-03-31 16:47 UTC, LudwigVonChesterfield commented
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/17705613/274c2cb9-5fef-45bd-95cd-f794e9ad4c11)

Можно закрывать?

2024-04-09 16:26 UTC, LudwigVonChesterfield requested changes
Комментарий Ниндзи Пикачушки.

2024-04-15 05:57 UTC, volas commented
Я хз по статусу каргонии, но дергать туда-сюда постоянно не хочется. Но даже независимо от этого, похоже, парамедиков там не хотят особо видеть. Трупы не убегут, всегда можно будет попросить карго впустить или помощи у инженеров.

2024-04-15 05:57 UTC, closed without merging