[MDB IGNORE] Перевод локаций
TauCetiStation/TauCetiClassic pull request #13060
Opened 2024-04-15 15:21 UTC by AzzyDreemurr13

## Описание изменений
Переведены все зоны на слое ЦК и станции. Тем самым закрытия данного вопроса #13034
Также слегка изменены зоны на слое цк (добавлено пару зон, для большей логичности) 
Добавлен перевод локаций в игровых анонсах (по типу объявление о местоположение бомбы или аномалии)
## Почему и что этот ПР улучшит
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/74739991/97f98081-fbe9-4c62-87a0-959a708c78a5)

## Авторство
Я, @maleyvich , @Pivo24  (Отдел переводчиков) и @Kiromaka (Спасибо за консультации)

## Чеинжлог
:cl: Azzy.Dreemurr, Maleyvich, Vipo 
 - ru: Перевод локаций ЦК и станции на русский язык 
 - ru: В Анонсах от ЦК, об аномалиях и т.д. теперь все локации на русском языке

2024-04-15 15:21 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2024-04-15 15:31 UTC, Kiromaka commented on code/game/area/gamma_areas.dm
> +	cases = list("технические туннели брига на правом борту", "технических туннелей брига на правом борту", "техническим туннелям брига на правом борту", "технические туннели брига на правом борту", "те
Слишком долго.

2024-04-15 15:31 UTC, Kiromaka commented on code/game/area/gamma_areas.dm
> +	cases = list("западные технические туннели брига", "западных технических туннелей брига", "западным техническим туннелям брига", "западные технические туннели брига", "западными техническими туннеля
same

2024-04-15 15:32 UTC, Kiromaka commented on code/game/area/station_areas.dm
> +	cases = list("носовые северо-западные солнечные панели", "носовых северо-западных солнечных панелей", "носовым северо-западным солнечным панелям", "носовые северо-западные солнечные панели", "носовы
Same, я не уверен как можно их лучше сделать, но это прям очень много букв.

2024-04-15 15:33 UTC, Kiromaka commented on code/game/area/station_areas.dm
> +	cases = list("электромагнитная катапульта церкви", "электромагнитной катапульты церкви", "электромагнитной катапульте церкви", "электромагнитная катапульта церкви", "электромагнитной катапультой цер
Думаю можно сократить до ЭмК ( не уверен)

2024-04-15 15:34 UTC, Kiromaka commented on code/game/area/station_areas.dm
> +	cases = list("лаборатория по изучению свойств газообразных элементов", "лаборатории по изучению свойств газообразных элементов", "лаборатории по изучению свойств газообразных элементов", "лаборатори
😱

2024-04-15 15:34 UTC, LudwigVonChesterfield commented on code/game/area/custom_areas.dm
> +	cases = list("гараж с дисантными капсулами", "гаража с дисантными капсулами", "гаражу с дисантными капсулами", "гараж с дисантными капсулами", "гаражом с дисантными капсулами", "гараже с дисантными
... дисантные?

2024-04-15 15:34 UTC, LudwigVonChesterfield commented on code/game/area/custom_areas.dm
> +	cases = list("корабль Абдукторов", "корабля Абдукторов", "кораблю Абдукторов", "корабль Абдукторов", "кораблём Абдукторов", "корабле Абдукторов")
... абдукторы?

2024-04-15 15:34 UTC, LudwigVonChesterfield commented on code/game/area/custom_areas.dm
> +	cases = list("небеса культа", "небес культа", "небесам культа", "небеса культа", "небесами культа", "небесах культа")
но ведь все называют раем

2024-04-15 15:37 UTC, Kiromaka commented
Людук слишком злой и слишком критичен, но по правде не очень.

2024-04-15 15:37 UTC, maleyvich commented on code/game/area/station_areas.dm
> +	cases = list("электромагнитная катапульта церкви", "электромагнитной катапульты церкви", "электромагнитной катапульте церкви", "электромагнитная катапульта церкви", "электромагнитной катапультой цер
это я не понимаю зачем оставили

2024-04-15 15:38 UTC, LudwigVonChesterfield commented on code/game/area/gamma_areas.dm
>  /area/station/security/seclunch
тут не переведено?

2024-04-15 15:38 UTC, Kiromaka commented on code/game/area/delta_areas.dm
Я только из могилы вылез, но вроде малевич занимается этим.

2024-04-15 15:38 UTC, LudwigVonChesterfield commented on code/game/area/station_areas.dm
> +	cases = list("носовые северо-западные солнечные панели", "носовых северо-западных солнечных панелей", "носовым северо-западным солнечным панелям", "носовые северо-западные солнечные панели", "носовы
зачем носовые если они северо-западные

2024-04-15 15:40 UTC, MrPerenka commented
https://github.com/TauCetiStation/TauCetiClassic/assets/125875249/21231b3c-b4af-49ba-9b67-cb2b624bf629

2024-04-15 15:40 UTC, maleyvich commented on code/game/area/gamma_areas.dm
>  /area/station/security/seclunch
со стороны невьебись какого моего важного мнения подумал что пусть секланч будет просто бригом называться

2024-04-15 15:41 UTC, maleyvich commented on code/game/area/custom_areas.dm
> +	cases = list("небеса культа", "небес культа", "небесам культа", "небеса культа", "небесами культа", "небесах культа")
раем его все подряд называют.

2024-04-15 16:19 UTC, KandreyKandrey commented on code/game/area/station_areas.dm
> +	cases = list("машинное отделение", "машинного отделения", "машинному отделению", "машинное отделение", "машинным отделением", "машинном отделение")
```suggestion
	cases = list("машинное отделение", "машинного отделения", "машинному отделению", "машинное отделение", "машинным отделением", "машинном отделении")
```

2024-04-15 16:27 UTC, KandreyKandrey commented on code/game/area/station_areas.dm
> +	cases = list("лаборатория по изучению свойств газообразных элементов", "лаборатории по изучению свойств газообразных элементов", "лаборатории по изучению свойств газообразных элементов", "лаборатори
не согласен с 'газообразные элементы'
варианты:
газообразные вещества
газы
газообразное состояние

2024-04-15 16:28 UTC, KandreyKandrey commented on code/game/area/station_areas.dm
> +	cases = list("телепортер спутника ИИ", "телепортера спутника ИИ", "телепортеру спутнику ИИ", "телепортер спутник ИИ", "телепортером спутником ИИ", "телепортере спутнике ИИ")
```suggestion
	cases = list("телепортер спутника ИИ", "телепортера спутника ИИ", "телепортеру спутнику ИИ", "телепортер спутник ИИ", "телепортером спутником ИИ", "телепортере спутника ИИ")
```

2024-04-15 16:28 UTC, LudwigVonChesterfield commented on code/game/area/station_areas.dm
> +	cases = list("лаборатория по изучению свойств газообразных элементов", "лаборатории по изучению свойств газообразных элементов", "лаборатории по изучению свойств газообразных элементов", "лаборатори
лаборатория форонной энергетики?

2024-04-15 16:30 UTC, maleyvich commented on code/game/area/station_areas.dm
> +	cases = list("лаборатория по изучению свойств газообразных элементов", "лаборатории по изучению свойств газообразных элементов", "лаборатории по изучению свойств газообразных элементов", "лаборатори
> форонной

там можно и не только форонные бомбы делать (недочёт)

2024-04-15 16:41 UTC, volas commented on code/game/area/station_areas.dm
> +	cases = list("лаборатория по изучению свойств газообразных элементов", "лаборатории по изучению свойств газообразных элементов", "лаборатории по изучению свойств газообразных элементов", "лаборатори
просто комната смешивания

2024-04-15 16:42 UTC, maleyvich commented on code/game/area/station_areas.dm
> +	cases = list("лаборатория по изучению свойств газообразных элементов", "лаборатории по изучению свойств газообразных элементов", "лаборатории по изучению свойств газообразных элементов", "лаборатори
мне предложили неплохой вариант "лаборатория исследования форона", аргументируя это шизопредками.

2024-04-15 17:03 UTC, volas commented on code/game/area/station_areas.dm
> +	cases = list("лаборатория по изучению свойств газообразных элементов", "лаборатории по изучению свойств газообразных элементов", "лаборатории по изучению свойств газообразных элементов", "лаборатори
Toxins тут просто название отдела, эта часть и в других комнатах присутствует. Главная часть тут 

> /mixing
> Mixing Room

Про смешивание.

Toxins кстати в других местах вы по другому переводите, либо вообще опускаете, но думаю можно поискать какую-то единую альтернативу.

2024-04-15 17:07 UTC, Chip11-n commented on code/game/area/station_areas.dm
> +	cases = list("лаборатория по изучению свойств газообразных элементов", "лаборатории по изучению свойств газообразных элементов", "лаборатории по изучению свойств газообразных элементов", "лаборатори
Может упростить до фороной или ее производных? Ведь именно так называют отсек.

2024-04-16 07:32 UTC, Pivo24 commented on code/game/area/station_areas.dm
> +	cases = list("носовые северо-западные солнечные панели", "носовых северо-западных солнечных панелей", "носовым северо-западным солнечным панелям", "носовые северо-западные солнечные панели", "носовы
Я же тут писал северо-западные солнечные панели, почему ты скопировал сюда ещё "носовые".....

2024-04-16 07:34 UTC, Pivo24 commented on code/game/area/station_areas.dm
> +	cases = list("электромагнитная катапульта церкви", "электромагнитной катапульты церкви", "электромагнитной катапульте церкви", "электромагнитная катапульта церкви", "электромагнитной катапультой цер
Почему не масс драйвер церкви просто?

Игроки же понимают сразу же

2024-04-18 08:13 UTC, AirBlack commented on code/game/area/custom_areas.dm
> +	cases = list("рай", "рая", "раю", "рай", "раем", "рае")
оккультный?

2024-04-18 08:14 UTC, AirBlack commented on code/game/area/custom_areas.dm
> +	cases = list("космический Додзё", "космического Додзё", "космическому Додзё", "космический Додзё", "космическим Додзё", "космическом Додзё")
средний род

https://ru.wiktionary.org/wiki/додзё#:~:text=Существительное%2C%20неодушевлённое%2C%20средний%20род%2C,Зализняка).

2024-04-18 08:17 UTC, AirBlack commented on code/game/area/delta_areas.dm
> +	cases = list("зал собраний глав", "зала собраний глав", "залу собраний глав", "зал собраний глав", "залом собраний глав", "зале собраний глав")
Переговорная не норм? ну или совещательная как в суде хз

2024-04-18 08:19 UTC, AirBlack commented on code/game/area/delta_areas.dm
> +	cases = list("КПП службы безопасности отбытия", "КПП службы безопасности отбытия", "КПП службы безопасности отбытия", "КПП службы безопасности отбытия", "КПП службы безопасности отбытия", "КПП служб
насчет сокращений, может убрать "службы безопасности"? КПП - контрольно пропускной пункт, итак понятно коммон сенсом что пунктом заведует служба безопасности

2024-04-18 08:20 UTC, AirBlack commented on code/game/area/delta_areas.dm
> +	cases = list("КПП службы безопасности ОС", "КПП службы безопасности ОС", "КПП службы безопасности ОС", "КПП службы безопасности ОС", "КПП службы безопасности ОС", "КПП службы безопасности ОС")
Вот тут наоборот лучше убрать имхо службу безопасности но расшифровать отдел снабжения, я когда глазом взглянул, то подумал какой кпп какой операционной системы, у нас сокращение ОС как отдел снабжения вроде как нигде не используется и будет путать игроков

2024-04-18 08:20 UTC, AirBlack commented on code/game/area/delta_areas.dm
> +	cases = list("КПП службы безопасности ИО", "КПП службы безопасности ИО", "КПП службы безопасности ИО", "КПП службы безопасности ИО", "КПП службы безопасности ИО", "КПП службы безопасности ИО")
тут тоже ИО как будто блин input output а не инженерный отдел, мб КПП Инженерии/КПП Инженерного отдела

2024-04-18 08:21 UTC, AirBlack commented on code/game/area/gamma_areas.dm
> +	cases = list("комната наблюдения ИО")
ИО

2024-04-18 08:21 UTC, AirBlack commented on code/game/area/gamma_areas.dm
> +	cases = list("склад ИО", "склада ИО", "складу ИО")
ИО

2024-04-18 08:22 UTC, AirBlack commented on code/game/area/gamma_areas.dm
> +	cases = list("неизвестная локация", "неизвестной локации", "неизвестной локации", "неизвестная локация", "неизвестной локацией", "неизвестной локации")
теряется контекст именно цензуры(REDACTED обычно зацензуренные штуки типа как в СЦП помечают)

мб оставить капсом УДАЛЕНО? дабы понятно было что что-то запрещенное зацензуренное

2024-04-18 08:23 UTC, AirBlack commented on code/game/area/gamma_areas.dm
> +	cases = list("базар", "базара", "базару", "базар", "базаром", "базаре")
мб рынок?

2024-04-18 08:23 UTC, AirBlack commented on code/game/area/gamma_areas.dm
> +	cases = list("базар", "базара", "базару", "базар", "базаром", "базаре")
хотя можно оставить базар, типа кукле говорят за базаром следи, и кукла идет на базар и следит хехеххе

2024-04-18 08:24 UTC, AirBlack commented on code/game/area/gamma_areas.dm
>  /area/station/security/seclunch
обеденная зона брига?

2024-04-18 08:25 UTC, AirBlack commented on code/game/area/main_areas.dm
> +	cases = list("космическое пространство", "космического пространства", "космическому пространству", "космическое пространство", "космическим пространством", "космическом пространстве")
было бы неплохо если бы можно было именовать space на слою станции как "обшивка" чтобы парамеды сразу знали что надо на обшивке искать труп, а если просто космическое пространство, то не на обшивке и оттуда не достать, но это так, мысли вслух, если сможешь было бы круто

2024-04-18 08:26 UTC, AirBlack commented on code/game/area/main_areas.dm
> +	cases = list("стартовая локация", "стартовой локации", "стартовой локации", "стартовую локацию", "стартовой локацией", "стартовой локации")
насколько понял, это зона где главное меню находится, если так, то не подлежит переводу

2024-04-18 08:27 UTC, AirBlack commented on code/game/area/gamma_areas.dm
> +	cases = list("западные технические туннели брига", "западных технических туннелей брига", "западным техническим туннелям брига", "западные технические туннели брига", "западными техническими туннеля
ну как минимум можно до "тех. туннели" сократить, сокращение очень распространенное а значит и подойдет для официальных названий

2024-04-18 08:29 UTC, AirBlack commented on code/game/area/gamma_areas.dm
>  /area/station/security/secconfhall
Не переведено, можно как "Переговорная брига" или че нить с брифингом связанное

Еще ниже не переведена Space Pod Construction Site, насколько помню на гамме заброшенная зона около рнд

2024-04-18 08:33 UTC, AirBlack commented on code/game/area/areas.dm
> +	cases = list("космическое пространство", "космического пространства", "космическому пространству", "космическое пространство", "космическим пространством", "космическом пространстве")
эта штука же отнаследуется на все зоны без переводов

2024-04-18 14:26 UTC, AirBlack commented on code/game/area/station_areas.dm
> +	cases = list("носовые северо-западные солнечные панели", "носовых северо-западных солнечных панелей", "носовым северо-западным солнечным панелям", "носовые северо-западные солнечные панели", "носовы
ну типа fore port это носовой правый борт, т.е. северо-западные, мы либо используем обозначения как в кораблестроении(в т.ч. и воздушных суден)(левый борт - port, правый борт - starboard, нос - bow/fore, корма - stern/aft), либо стороны света. Плюсы/минусы использования первого варианта - круто и атуентично, но сначала может сбивать с толку(я например про port starboard bow fore stern aft только щас узнал, я думал это просто дебильные слова от дебилов космонавтиков прошлого). Плюсы и минусы использования сторон света - сразу всем понятно и привычно, но нелогично в контексте космических кораблей и неаутентично. Где север и юг по логике находятся? Типа нос и корма корабля? А почему так их не называть? Или станция типа обязательно носом смотрит всегда на полярную звезду?

Я бы топил за кораблестроительный вариант, чтоб космонавтики наши привыкли и могли еще больше выпендриваться, что они по игре знают. Но в любом случае надо оставить только один и их не мешать.

2024-04-18 14:33 UTC, AirBlack commented on code/game/area/centcom_areas.dm
> +	cases = list("жилые апартаменты ЦК", "жилых апартаментов ЦК", "жилым апартаментам ЦК", "жилые апартаменты ЦК", "жилыми апартаментами ЦК", "жилых апартаментах ЦК")
жилблок? не критично т.к. зона цк а там ниче не происходит

2024-04-21 23:08 UTC, LudwigVonChesterfield commented on code/game/area/areas.dm
> +	cases = list("космическое пространство", "космического пространства", "космическому пространству", "космическое пространство", "космическим пространством", "космическом пространстве")
почему нельзя оставить перевод на космическое пространство только зоне космоса?

2024-04-22 02:15 UTC, AirBlack commented on code/game/area/delta_areas.dm
> +	cases = list("зал собраний глав", "зала собраний глав", "залу собраний глав", "зал собраний глав", "залом собраний глав", "зале собраний глав")
ну лаундж можно как комнату отдыха интерпретировать, плюс учитывая что тут еще и камин

2024-04-22 02:17 UTC, AirBlack commented on code/game/area/custom_areas.dm
> +	cases = list("рай", "рая", "раю", "рай", "раем", "рае")
хз, мне кажется что "рай" слишком обобщенное название, вне контекста режима культа непонятно, а значит будет непонятно ассистухе в первый раунд. если добавить "оккультный", то останется контекст именно рая культа, а не рая где иисус яйцами трясет

2024-04-22 02:33 UTC, AirBlack commented on code/game/area/main_areas.dm
> +	cases = list("космическое пространство", "космического пространства", "космическому пространству", "космическое пространство", "космическим пространством", "космическом пространстве")
ты меня забанил в дискорде, в дискорде тау киты я тоже забанен, в игре все методы связи кроме ИЦ и ахелпа у меня в муте(и то ахелп просто забыли обратно замьютить), да и забанили меня на месяц за прекрасный отыгрышб, так что я напомнить тебе никак не смогу

2024-04-29 17:14 UTC, volas commented on code/game/area/areas.dm
> +	cases = list("космическое пространство", "космического пространства", "космическому пространству", "космическое пространство", "космическим пространством", "космическом пространстве")
если это дословно опять переводить на английский, получится "space space". Просто хотел поделиться.

2024-04-29 17:19 UTC, volas commented on code/game/area/centcom_areas.dm
> +	cases = list("пропускной пункт", "пропускного пункта", "пропускному пункту", "пропускной пункт", "пропускном пункте", "пропускном пункте")
пропускной пункт в другом месте, это скорее зал ожидания. Английский тут тоже надмозг и можно изменить.

2024-04-29 17:21 UTC, volas commented on code/game/area/centcom_areas.dm
> +	cases = list("офис Крида", "офиса Крида", "офису Крида", "офис Крида", "офисом Крида", "офисе Крида")
если зона в коде больше не упоминается и на картах не используется - да, можете убрать такие, это просто легаси которое забыли подчистить

2024-05-01 06:42 UTC, volas commented on code/game/area/station_areas.dm
> +	cases = list("лаборатория по изучению свойств газообразных элементов", "лаборатории по изучению свойств газообразных элементов", "лаборатории по изучению свойств газообразных элементов", "лаборатори
ну какая токсинная. Это прежде всего комната смешивания. Там рядом Toxins Storage, его вы тоже как просто токсинную по аналогии обзовете? И Toxins Launch Room.

Toxins в этой части - префикс, название подотдела рнд. Изучающего "токсины", как раньше предки называли форон.

2024-05-01 06:54 UTC, volas commented on code/game/area/station_areas.dm
> +	cases = list("лаборатория по изучению свойств газообразных элементов", "лаборатории по изучению свойств газообразных элементов", "лаборатории по изучению свойств газообразных элементов", "лаборатори
> Хм.. а почему ранее кстати игнорировали это :'d

это уже третий раз в этой ветке комментариев, когда я пишу про некорректность перевода и про акцент на смешивание (уже четвертый).

2024-05-02 14:50 UTC, AirBlack commented on code/game/area/station_areas.dm
> +	cases = list("лаборатория по изучению свойств газообразных элементов", "лаборатории по изучению свойств газообразных элементов", "лаборатории по изучению свойств газообразных элементов", "лаборатори
я в токсинной почти ниокгда ничего не смешивал, а когда случайно смешивал, то инженеры и админы были не в восторге

2024-05-14 13:06 UTC, volas commented on code/game/area/gamma_areas.dm
> +	cases = list("базар", "базара", "базару", "базар", "базаром", "базаре")
тут думаю рынок будет корректнее

2024-05-14 13:15 UTC, volas commented on code/game/area/station_areas.dm
> +	cases = list("комната отдыха ИО", "комнаты отдыха ИО", "комнате отдыха ИО", "комната отдыха ИО", "комнатой отдыха ИО", "комнате отдыха ИО")
ио - обычно сокращение для исполняющий обязанности, и у нас эта аббревиатура используется в СОПе. 

Как предложение, отдел обозвать как "инженерная" и тут просто "комната отдыха инженерной". Будет ближе всего к оригинальному.

2024-05-14 13:16 UTC, volas commented on code/game/area/station_areas.dm
> +	cases = list("атмосферный отдел", "атмосферного отдела", "атмосферному отделу", "атмосферный отдел", "атмосферным отделом", "атмосферном отделе")
И "атмосферный отдел" можно как "атмосферная" в этом случае

2024-05-14 13:22 UTC, volas commented on code/game/area/station_areas.dm
> +	cases = list ("технический туннель ОС", "технического туннеля ОС", "техническому туннелю ОС", "технический туннель ОС", "техническим туннелем ОС", "техническом туннеле ОС")
ОС тоже никто не поймет, как минимум стоило бы избавиться тут от сокращений отделов. Это их оригинальное название, и сокращать можно в других местах.

Вот туннели можно без вреда сократить: техт**у**ннели или техт**о**ннели.

У вас кстати в переводах оба варианта сокращения технических  уже присутствуют в разных местах, можно заодно привести в порядок.

2024-05-14 13:24 UTC, volas commented on code/game/area/station_areas.dm
> +	cases = list("северо-западные технические тоннели", "северо-западных технических тоннелей", "северо-западным техническим тоннелям", "северо-западные технические тоннели", "северо-западными техническ
например, тут уже тоннели, хотя выше туннели. Оба варианта правильные, просто выбрать какой-то один, и писать слитно с "тех"

2024-05-14 13:26 UTC, volas commented on code/game/area/station_areas.dm
> +	cases = list("офис священика", "офиса священика", "офису священика", "офис священика", "офисом священика", "офисе священика")
священника (две н)

2024-05-14 13:29 UTC, volas commented on code/game/area/station_areas.dm
> +	cases = list("отдел клонирования", "отдела клонирования", "отделу клонирования", "отдел клонирования", "отделом клонирования", "отделе клонирования")
выше решили Lab опустить, тут перевести как отдел. Не критично.

2024-05-14 13:31 UTC, volas requested changes
Пара мелочей, самое критичное имхо - избавиться от сокращения отделов вроде ОС и ИО, в названии собственно отдела. Иначе они полным текстом нигде больше и не будут.

При этом, если в названии есть аббревиатура, не относящаяся к отделу, например ИИ или АВД - её присутствие я бы простил.

Ну и стоит разобраться с техами, а то тут все 4 возможных варианта используются.

2024-05-16 18:20 UTC, volas commented on code/game/area/station_areas.dm
> +	cases = list("северо-восточные технические тоннели", "северо-восточных технических тоннелей", "северо-восточным техническим тоннелям", "северо-восточные технические тоннели", "северо-восточными техн
тут тоннели остались

2024-05-16 18:21 UTC, volas commented on code/game/area/gamma_areas.dm
> +	cases = list("западные тех. туннели брига", "западных тех. туннелей брига", "западным тех. туннелям брига", "западные тех. туннели брига", "западными тех. туннелями брига", "западных тех. туннелях б
тут туннели, хотя в других местах это тентоннели теперь

2024-05-16 18:22 UTC, volas commented on code/game/area/station_areas.dm
> +	cases = list("северо-западные технические тоннели", "северо-западных технических тоннелей", "северо-западным техническим тоннелям", "северо-западные технические тоннели", "северо-западными техническ
техтоннели, в паре мест еще можно пройтись и исправить подобное

2024-05-17 09:28 UTC, volas commented on code/game/area/station_areas.dm
> +	cases = list("юго-западные солнечные тоннели", "юго-западных техтоннелей", "юго-западным техтоннелям", "юго-западные техтоннели", "юго-западными техтоннелями", "юго-западных техтоннелях")
антипод тех тоннелей - солнечные тоннели
```suggestion
	cases = list("юго-западные солнечные техтоннели", "юго-западных техтоннелей", "юго-западным техтоннелям", "юго-западные техтоннели", "юго-западными техтоннелями", "юго-западных техтоннелях")
```

2024-05-17 09:29 UTC, volas approved these changes

2024-05-17 09:31 UTC, merged