Мехи не будут стрелять в себя.
TauCetiStation/TauCetiClassic pull request #13064
Opened 2024-04-19 05:31 UTC by Ro2tCrab

## Описание изменений
### Не протестировано.
Мёржить только после своих тестов или после моих тестов (вечером этого дня).
## Почему и что этот ПР улучшит
closes #6620
## Авторство
Обойдусь
## Чеинжлог
:cl:
 - bugfix: Мехи случайно попадали в себя из оружия при движении в сторону стрельбы.
-->

2024-04-19 05:31 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2024-04-21 09:27 UTC, Chip11-n submitted a review, later dismissed

2024-04-21 11:30 UTC, Chip11-n commented on code/game/mecha/equipment/weapons/weapons.dm
> +	P.firer = chassis
У мехов вообще есть проверка на стрелка?

2024-04-22 04:41 UTC, Ro2tCrab commented on code/game/mecha/equipment/weapons/weapons.dm
> +	P.firer = chassis
> У мехов вообще есть проверка на стрелка?

А зачем меху проверка на стрельбу? Этот кусок кода передаёт условной **пуле** информацию о источнике выстрела.
Проверки на стрелке в коде мехов быть не должно

2024-04-29 17:37 UTC, volas commented on code/game/mecha/equipment/weapons/weapons.dm
> +	P.firer = chassis
```
var/mob/firer = null
```

переменная моб, и в некоторых местах с ней работают как с мобом. Надо как-то по другому наверно (или переделать уже мехов в мобов)

2024-05-17 08:28 UTC, volas commented on code/game/mecha/equipment/weapons/weapons.dm
> +	P.firer = chassis
если что, это критичный момент и ошибка мистайпа: переменной типа моб присваивается значение меха

и оно требует другого решения, в таком виде это не для мержа

2024-05-17 08:28 UTC, volas requested changes
меняю статус, смотреть комментарий выше

2024-06-08 06:24 UTC, closed without merging