Перевод APC(3.0)
TauCetiStation/TauCetiClassic pull request #13080
Opened 2024-05-02 00:24 UTC by AzzyDreemurr13

## Описание изменений
На данный момент, ПР в стадии восстановления и устранения прошлых предъяв к переводу от Гуся, поэтому активно принимаем идеи.

Продолжение ПРа: #12789, resolve https://github.com/TauCetiStation-TranslationDepartment/TauCetiClassic/issues/24
Реанимируем ПР с почти готовым переводом APC и проводки.
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/74739991/9b0efbd5-4e95-47da-b686-fccd9e2625f7)
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/74739991/1d327446-54ab-4f3a-856b-27a7792c7ea2)

## Почему и что этот ПР улучшит
Первый перевод инженерного отдела, перевод нескольких интерфейсов в одной тематике.

## Авторство
@DarthSidiousPalpatine (Гусев) начал, Я же довожу до конца брошенный ПР. Пикачу и Людвику за помощь в техническом формате (коде)

## Чеинжлог
:cl: Azzy.Dreemurr, DarthSidiousPalpatine
 - ru: Перевод APC и перевод интерфейса проводов на русский язык

2024-05-02 00:24 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2024-05-02 05:38 UTC, Oz1Es commented
думаю короткая альтернатива вставить будет мемиться игроками тау сети

2024-05-02 10:47 UTC, Fluffy-510 commented
> "Распределительный щит".
Мне кажется, что "распределительный щиток" будет звучать лучше, потому что иначе звучит как распределительный shit

2024-05-02 11:14 UTC, AndroBetel commented
факин щит

2024-05-02 11:56 UTC, maleyvich requested changes

2024-05-02 11:56 UTC, maleyvich commented on code/modules/power/apc.dm
> +				to_chat(user, "<span class='warning'>Отключите проводку.</span>")
```suggestion
				to_chat(user, "<span class='warning'>Отключите щиток от питания.</span>")
```

2024-05-02 11:56 UTC, maleyvich commented on code/modules/power/apc.dm
> +					to_chat(user, "<span class='notice'>Ваш аккумулятор полностью заряжен.</span>")
звучит как-то проклято

2024-05-02 11:56 UTC, maleyvich commented on code/modules/power/apc.dm
> +				to_chat(user, "Напряжение в [CASE(src, PREPOSITIONAL_CASE)] слишком мало.")
```suggestion
				to_chat(user, "Критически низкое напряжение в [CASE(src, PREPOSITIONAL_CASE)].")
```

2024-05-02 18:54 UTC, Pivo24 requested changes
вот? >.>

2024-05-02 18:54 UTC, Pivo24 commented on code/modules/power/apc.dm
> +				"<span class='warning'>[user.name] установил аккумулятор в [CASE(src, ACCUSATIVE_CASE)]!</span>",\
мне кажется тут лучше в настоящем времени, потому что персонаж женского пола будет "установил"

2024-05-02 18:54 UTC, Pivo24 commented on code/modules/power/apc.dm
> +			"<span class='warning'>[user.name] заменил сломанную крышку [CASE(src, GENITIVE_CASE)].</span>",\
Тоже самое, "заменяет" наверное лучше

2024-05-02 18:54 UTC, Pivo24 commented on code/modules/power/apc.dm
> +				"<span class='warning'>[user.name] заменил сломанный корпус [CASE(src, GENITIVE_CASE)].</span>",\
настоящее время

2024-05-02 18:54 UTC, Pivo24 commented on code/modules/power/apc.dm
> +			user.visible_message("<span class='warning'>[user.name] извлёк аккумулятор из [CASE(src, GENITIVE_CASE)]!</span>", "Вы извлекаете аккумулятор из [CASE(src, GENITIVE_CASE)].")
Тоже мужской род прошедшего времени

"извлекает" FTW

2024-05-04 07:23 UTC, DarthSidiousPalpatine commented on code/modules/power/apc.dm
> +			user.visible_message("<span class='warning'>[user.name] извлёк аккумулятор из [CASE(src, GENITIVE_CASE)]!</span>", "Вы извлекаете аккумулятор из [CASE(src, GENITIVE_CASE)].")
Вы же в курсе, да, что вы можете, вроде как, пол проверять и также как падеж изменять сообщение?

2024-05-04 08:23 UTC, DarthSidiousPalpatine commented on code/modules/power/apc.dm
> +			user.visible_message("<span class='warning'>[user.name] извлёк аккумулятор из [CASE(src, GENITIVE_CASE)]!</span>", "Вы извлекаете аккумулятор из [CASE(src, GENITIVE_CASE)].")
О БОЖЕ ЭТО МОЙ ПЕРЕВОД? НЕВЕРОЯТНО.

-_-
к чему была эта информация я хуй знает, ясно.

2024-05-14 15:25 UTC, Pivo24 approved these changes

2024-05-14 15:27 UTC, maleyvich requested changes
мне все нравится?

2024-05-14 15:27 UTC, maleyvich approved these changes
да, всё нормально.

2024-05-17 08:38 UTC, volas commented on code/modules/power/apc.dm
> +			cases[cases.Find(case)] = case + " [CASE(area, GENITIVE_CASE)]"
Делая Find в цикле ради индекса ты увеличиваешь сложность на ровном месте, лучше сделать for(var/i)  или просто пересоздавать массив. 

+переименование можно было бы вынести в отдельную функцию

2024-06-08 08:08 UTC, volas commented on code/modules/power/apc.dm
> +			cases[i] = case + " [CASE(area, GENITIVE_CASE)]"
```suggestion
			cases[i] = cases[i] + " [CASE(area, GENITIVE_CASE)]"
```

2024-06-08 08:08 UTC, volas commented on code/modules/power/apc.dm
> +			cases[i] = case + " [CASE(area, GENITIVE_CASE)]"
```suggestion
			cases[i] = cases[i] + " [CASE(area, GENITIVE_CASE)]"
```

2024-06-08 08:09 UTC, volas commented on code/modules/power/apc.dm
> +			cases[i] = case + " [CASE(area, GENITIVE_CASE)]"
```suggestion
			cases[i] = cases[i] + " [CASE(area, GENITIVE_CASE)]"
```

нет смысла деклерить переменную, а так ок

2024-06-08 08:12 UTC, volas commented on code/modules/power/apc.dm
> +				to_chat(usr, "<span class='warning'>\"Умный свет\" в процессе переключения!</span>")
```suggestion
				to_chat(usr, "<span class='warning'>Системы предохранения не позволяют поставить новый режим так быстро, немного подождите.</span>")
```

это про кулдаун, смысл потеряли. Переписал на чуть более понятное, наверно

2024-06-08 14:49 UTC, merged