More Screen Alerts
TauCetiStation/TauCetiClassic pull request #13092
Opened 2024-05-13 14:59 UTC by BasiaBelov

## Описание изменений
Использовал неиспользованные всплывашки, по типу недостатка кислорода, сна, слепоты и подобного.
Добавил немного больше, чтобы было лучше видно как чувствует себя наши куколки.
Теперь наглядней видно, если наша куколка в наручниках, или пьяна или в стане, всякое такое.
Заодно перевёл их.
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/115452414/a1a44951-39ae-456a-8ed2-1ee2bbb8dc8d)
А, ну и насчёт спама этими иконками, не бойтесь. Я сделал так, что если одна перебивает другую, то есть, например, если мы спим, то иконка о стане пропадёт. Такое со многими.

## Почему и что этот ПР улучшит
Мы __УВИДИМ__ как себя чувствует наша кукла.
## Авторство
Иконки были слеплены вместе из существующих в билде.
Код писал и переводил я, _к сожалению..._
## Чеинжлог

:cl: Basia
 - add: Добавлено больше иконок, что отображают статус о вашем персонаже.

2024-05-13 15:00 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2024-05-13 16:05 UTC, Kiromaka requested changes

2024-05-13 16:05 UTC, Kiromaka commented on code/datums/components/aura_healing.dm
> +	name = "Исцелительная аура"
🤯🤯🤯🤯🤯Слов новых не придумываем.

2024-05-13 16:06 UTC, BasiaBelov commented on code/datums/components/aura_healing.dm
> +	name = "Исцелительная аура"
Это ру_с_кий
Тут фсё мошна

2024-05-13 16:08 UTC, KIBORG04 commented on code/datums/components/aura_healing.dm
> +	name = "Исцелительная аура"
Исцеляющая Аура же звучит круче

2024-05-13 16:46 UTC, ZER0-In commented on code/datums/components/aura_healing.dm
> +	name = "Исцелительная аура"
> Исцеляющая Аура же звучит круче

Целительная аура

2024-05-13 17:35 UTC, maleyvich requested changes

2024-05-13 17:35 UTC, maleyvich commented on code/datums/status_effects/neutral.dm
> +	desc = "Воздействуйте на репликатор, которым вы управляли до этого."
карамба!
```suggestion
	desc = "Воздействуйте на репликатора, 
	которым вы управляли до этого."
```

2024-05-13 17:35 UTC, maleyvich commented on code/datums/status_effects/neutral.dm
> +	desc = "Воздействуйте на репликатор, которым вы управляли до этого."
другой вариант
```suggestion
	desc = "Воздействуйте на оболочку, которой управляли до этого."
```

2024-05-13 17:47 UTC, maleyvich requested changes
карамба х2

2024-05-13 17:47 UTC, maleyvich commented on code/_onclick/hud/alert.dm
> +	desc = "У вас не выходит дышать!"
карамба!
```suggestion
	desc = "По каким-то причинам, вы не можете дышать!"
```

2024-05-13 17:47 UTC, maleyvich commented on code/_onclick/hud/alert.dm
> +	desc = "В воздухе витает легковоспламеняющаяся, токсичная плазма, и вы вдыхаете её. Выйдите на свежий воздух."
убрана полезная подсказка для новичков, это единственное что новичок может увидеть когда видит что умирает в фороне

2024-05-13 17:47 UTC, maleyvich commented on code/_onclick/hud/alert.dm
> +	desc = "Вокруг вас опасный уровень давления атмосферы. Скафандр защитит вас."
звучит как то проклято, но я не могу понять что именно.

2024-05-13 17:47 UTC, maleyvich commented on code/_onclick/hud/alert.dm
> +	name = "Возгарание"
карамба!
```suggestion
	name = "Возгорание"
```

2024-05-13 17:47 UTC, maleyvich commented on code/_onclick/hud/alert.dm
> +	desc = "Вы вошли в стазис. Просто подождите немного."
```suggestion
	desc = "Вы вошли в стазис. Просто немного подождите."
```

2024-05-13 17:47 UTC, maleyvich commented on code/_onclick/hud/alert.dm
> +	desc = "Вам не хватает кислорода."
```suggestion
	desc = "По каким-то причинам, вы не можете дышать;"
```

2024-05-13 17:47 UTC, maleyvich commented on code/_onclick/hud/alert.dm
> +	desc = "Эта реальность не может выдержать вашего присутствия... Вы должны потреблять, чтобы жить."
репликаторы вроде бы как поглощают? срочную консультацию людука

2024-05-13 17:47 UTC, maleyvich commented on code/_onclick/hud/alert.dm
> +			Нажмите на кнопку Сопротивления, чтобы попытаться выбраться из них."
до перевода кнопок интерфейса ещё так думаю далеко
```suggestion
			Нажмите на кнопку Resist, чтобы попытаться выбраться из них."
```

2024-05-13 17:47 UTC, maleyvich commented on code/_onclick/hud/alert.dm
> +			Нажмите на кнопку Сопротивления, чтобы попытаться убрать ловушку из ног."
аналогично 
```suggestion
			Нажмите на кнопку Resist, чтобы попытаться убрать ловушку из ног."
```

2024-05-13 17:47 UTC, maleyvich commented on code/_onclick/hud/alert.dm
> +			Нажмите на кнопку Сопротивления, чтобы попытаться выбраться из них."
хех, в оригинале вообще про саму кнопку написано. забавно

2024-05-13 17:52 UTC, Kiromaka commented on code/_onclick/hud/alert.dm
> +	desc = "У вас не выходит дышать!"
Не красиво звучит малевич.

2024-05-13 17:53 UTC, maleyvich commented on code/_onclick/hud/alert.dm
> +	desc = "У вас не выходит дышать!"
но лучше чем у вас не выходит дышать.

2024-05-13 17:53 UTC, Kiromaka commented on code/_onclick/hud/alert.dm
> +			Нажмите на кнопку Сопротивления, чтобы попытаться убрать ловушку из ног."
Хуйня, некрасиво

2024-05-13 17:54 UTC, maleyvich commented on code/_onclick/hud/alert.dm
> +			Нажмите на кнопку Сопротивления, чтобы попытаться убрать ловушку из ног."
когда переведёшь кнопки интерфейса тогда и напишешь что хуйня. ну или когда переведут...

2024-05-13 18:57 UTC, ZER0-In commented
Я в ахуе. Зачем я столько времени убил на это. Лучше бы спать раньше лег, завтра на работу...

2024-05-14 00:19 UTC, BasiaBelov commented on code/datums/status_effects/neutral.dm
> +	desc = "Воздействуйте на репликатор, которым вы управляли до этого."
Спасибо, кстати

2024-05-14 00:20 UTC, BasiaBelov commented on code/datums/status_effects/neutral.dm
> +	desc = "Воздействуйте на репликатор, которым вы управляли до этого."
А, нет, я думал, ты про "воздействуйте"

2024-05-14 00:21 UTC, BasiaBelov commented on code/_onclick/hud/alert.dm
> +	desc = "В воздухе витает легковоспламеняющаяся, токсичная плазма, и вы вдыхаете её. Выйдите на свежий воздух."
Он и так и так помрёт. От форона и риг не поможет.

2024-05-14 00:23 UTC, BasiaBelov commented on code/_onclick/hud/alert.dm
> +			Нажмите на кнопку Сопротивления, чтобы попытаться выбраться из них."
Она не работает, если что

2024-05-14 00:26 UTC, BasiaBelov commented on code/datums/components/aura_healing.dm
> +	name = "Исцелительная аура"
Аура, которая лечит

2024-05-14 07:59 UTC, Oz1Es commented on code/_onclick/hud/alert.dm
> +	desc = "Вокруг вас опасный уровень давления атмосферы. Скафандр защитит вас."
атмосфера лишнее наверное

2024-05-14 08:00 UTC, Oz1Es commented on code/_onclick/hud/alert.dm
> +	desc = "Вам не хватает кислорода."
не не очень малевич, лучше нехватка кислорода чем по каким-то причинам вы не можете дышать

2024-05-14 08:05 UTC, Oz1Es commented on code/datums/status_effects/status_effect.dm
> +	name = "Проклятие обыденности"
по моему по смыслу лучше подойдёт проклятье

2024-05-14 08:07 UTC, Oz1Es commented on code/_onclick/hud/alert.dm
> +	desc = "Эта реальность не может выдержать вашего присутствия... Вы должны потреблять, чтобы жить."
тут лучше бы вместо "Голод роя" подошло бы "Рой голоден"

2024-05-14 11:08 UTC, WatlerJe approved these changes

2024-05-15 11:28 UTC, Pivo24 commented on code/_onclick/hud/alert.dm
> +	desc = "У вас не выходит дышать!"
"Удушение"
"Вы не можете дышать!"
камон

2024-05-15 14:01 UTC, volas commented on code/modules/mob/living/carbon/carbon.dm
> +	if(inhale_alert && !IsSleeping())
было бы красивее сгруппировать все IsSleeping.

Типо,
```
if(!IsSleeping()) // suppresses derivative effects
   if(inhale_alert)
      ...
   if()
      ...
else
   trow_alert("sleep")
```

2024-05-15 14:02 UTC, volas commented on code/_onclick/hud/alert.dm
> +	desc = "В воздухе витает легковоспламеняющаяся, токсичная плазма, и вы вдыхаете её. Выйдите на свежий воздух."
форон

2024-05-15 14:03 UTC, volas commented on code/_onclick/hud/alert.dm
> +	desc = "В воздухе витает легковоспламеняющаяся, токсичная плазма, и вы вдыхаете её. Выйдите на свежий воздух."
```suggestion
	desc = "В воздухе витает легковоспламеняющийся, токсичный форон, и вы дышите им. Выйдите на свежий воздух."
```

2024-05-18 15:16 UTC, maleyvich commented on code/_onclick/hud/alert.dm
> +			Стоит разобраться по какой причине это произошло."
запятую можно было бы добавить после "необходимости"

2024-05-18 15:16 UTC, maleyvich commented on code/_onclick/hud/alert.dm
> +			Нажмите на кнопку Сопротивления, чтобы попытаться убрать ловушку из ног."
может быть пробела не хватает?

2024-05-18 15:17 UTC, maleyvich commented on code/_onclick/hud/alert.dm
> +	desc = "Обнаружено новое опасное оборудование. Пожалуйста, убедитесь, что любое использование этого оборудования разрешается вашим набором законов."
не хватает запятой или так норм

2024-05-18 15:18 UTC, maleyvich commented on code/_onclick/hud/alert.dm
> +	desc = "По каким-то причинам, вы не можете дышать!"
выйти на свежий воздух может звучать странно, но впрочем ладно

2024-05-18 15:19 UTC, maleyvich commented on code/_onclick/hud/alert.dm
> +	desc = "Интерфейс устройства разблокирован. Кто-то случайно или намеренно оставил его открытым. Робототехника может оказать помощь."
может быть просто "робототехник"?

2024-05-18 15:37 UTC, maleyvich commented on code/_onclick/hud/alert.dm
> +			Нажмите на кнопку Сопротивления, чтобы попытаться убрать ловушку из ног."
думаю что да

2024-06-02 09:04 UTC, maleyvich approved these changes
мне кажется всё нормально

2024-06-02 09:04 UTC, maleyvich commented on code/_onclick/hud/alert.dm
> +			Если это вам сильно мешает, то нажмите по себе правой кнопкой мыши и выберите 'Вытащить предмет'."
а нет, здесь тоже стоит сделать как с "Resist" (сопротивление)

2024-06-03 17:02 UTC, daedrowe commented on code/_onclick/hud/alert.dm
> +	desc = "В воздухе витает легковоспламеняющийся, токсичный форон, и вы дышите им. Выйдите на свежий воздух."
а если в моём рюкзаке нет коробки?
а если я играю за спу?
а если я играю за вокса?

2024-06-03 17:21 UTC, daedrowe commented on code/_onclick/hud/alert.dm
> +	desc = "Вокруг вас опасный уровень давления атмосферы. Скафандр защитит вас."
```suggestion
	desc = "Вокруг вас опасный уровень давления атмосферы. Скафандр бы вас защитил."
```

2024-06-03 17:21 UTC, daedrowe commented on code/_onclick/hud/alert.dm
> +			ну или что-то надето на ваши глаза."
```suggestion
			ну или что-то закрывает ваши глаза."
```

2024-06-03 17:21 UTC, daedrowe commented on code/_onclick/hud/alert.dm
> +	desc = "У юнита отсуствует батарея. Модули недоступны до тех пор, пока батарея не будет установлена. Робототехника может оказать помощь."
```suggestion
	name = "Нет батареи"
	desc = "У юнита отсутствует батарея. Модули недоступны до тех пор, пока батарея не будет установлена. Робототехники могут вам помочь."
```

2024-06-03 17:21 UTC, daedrowe commented on code/_onclick/hud/alert.dm
> +			Станции подзарядки имеются в роботехнике, в туалетах дормитория, на станции подзарядки киборгов и в спутнике с искусственным интеллектом."
```suggestion
			Станции подзарядки имеются в робототехнике, в туалетах дормиторий, на станции подзарядки киборгов и на спутнике ИИ."
```

2024-06-03 17:21 UTC, daedrowe commented on code/_onclick/hud/alert.dm
> +	desc = "Батарея скоро сядет. Станции подзарядки имеются в роботехнике, в туалетах дормитория, на станции подзарядки киборгов и в спутнике с искусственным интеллектом."
```suggestion
	desc = "Батарея скоро сядет. Станции подзарядки имеются в робототехнике, в туалетах дормиторий, на станции подзарядки киборгов и на спутнике ИИ."
```

2024-06-03 17:21 UTC, daedrowe commented on code/_onclick/hud/alert.dm
> +	desc = "Обнаружено нестандартизированное опасное оборудование. Пожалуйста, убедитесь, что любое использование этого оборудования разрешается вашим набором законов.."
```suggestion
	desc = "Обнаружено нестандартизированное опасное оборудование. Пожалуйста, убедитесь, что любое использование этого оборудования разрешается вашим набором законов."
```

2024-06-03 17:21 UTC, daedrowe commented on code/_onclick/hud/alert.dm
> +	name = "Разблокированный интерфейс"
```suggestion
	name = "Интерфейс разблокирован"
```

2024-06-03 17:21 UTC, daedrowe commented on code/datums/status_effects/debuffs.dm
> +	desc = "Вы заснули. Подождите немного, и вы проснетесь, если только у вас всё в порядке..."
```suggestion
	desc = "Вы заснули. Подождите немного, и вы проснетесь. Ну или нет, учитывая насколько вы беспомощны."
```

2024-06-08 08:07 UTC, volas commented
@BasiaBelov живи, посмотри по ревью - прими, что считаешь подходящим

2024-06-08 15:54 UTC, BasiaBelov commented
Да у меня просто ПК немного нае-
Завтра обещают вернуть с ремонта.

2024-06-10 16:58 UTC, merged