Добавления новых полов на часть карт (Бокс, Астероид)
TauCetiStation/TauCetiClassic pull request #13102
Opened 2024-05-17 18:09 UTC by AzzyDreemurr13

## Описание изменений
Начинаем потихоньку использовать новые полы https://github.com/TauCetiStation/TauCetiClassic/pull/12812 и https://github.com/TauCetiStation/TauCetiClassic/pull/13076 
<details>
  <summary>Бокс стейшион</summary>

![image](https://github.com/user-attachments/assets/81fc2797-8e8d-4883-ae27-7281162c46d5)
![image](https://github.com/user-attachments/assets/b6f3b227-85eb-4c2a-b923-31e0756ac82f)
![image](https://github.com/user-attachments/assets/fa9b134e-dd1a-46c6-8a44-6b71bbf2391b)
![image](https://github.com/user-attachments/assets/f59c721c-39ee-476b-8764-e3d6af32a40a)
![image](https://github.com/user-attachments/assets/36d25f8b-df75-47c6-b324-225e42cd602c)
![image](https://github.com/user-attachments/assets/6f409708-c398-4208-bc74-20cc72cefeee)
![image](https://github.com/user-attachments/assets/912f37de-fb02-427e-9dce-72dc85ccb1e7)
![image](https://github.com/user-attachments/assets/bf2c9bb6-7424-4c06-a82d-385350882153)
![image](https://github.com/user-attachments/assets/220ea376-27c0-4da0-9fff-2998bdc9ee3f)
![image](https://github.com/user-attachments/assets/bc95118a-e172-4754-996b-36b449d37a94)
![image](https://github.com/user-attachments/assets/8b8d4dcd-810d-4595-a18b-f4f7012d5e6f)
![image](https://github.com/user-attachments/assets/0a0579d8-621e-42c3-b62d-1b1784ea8f35)
![image](https://github.com/user-attachments/assets/8ca74855-84ba-4b55-89ea-ca380904201b)
![image](https://github.com/user-attachments/assets/408db7ba-555b-44df-b975-85f12e5a5738)
![image](https://github.com/user-attachments/assets/a3e51979-d596-4dbe-9d89-b34c0b85848a)
![image](https://github.com/user-attachments/assets/a3ed839f-102e-44fa-be6e-8784d17e4449)
![image](https://github.com/user-attachments/assets/c5ac9cd5-bc04-4a94-9ab8-74762b13753d)
![image](https://github.com/user-attachments/assets/e70810a6-423f-4f0b-968f-74075d4a6c21)

</details>

#### Аванпост временно не актуален, @KatoMarika вносит крупные изменения в новом ПРе 
<details>
  <summary>Аванпост</summary>

![image](https://github.com/user-attachments/assets/3d551a4f-18ee-40d4-979c-ecb7d24527db)
![image](https://github.com/user-attachments/assets/3c2cff91-c7b3-45a2-9766-208fc43b98f3)
![image](https://github.com/user-attachments/assets/022a4405-6652-45c9-9429-5d484a5d8b99)
![image](https://github.com/user-attachments/assets/d04383a2-6d7c-4769-b365-f36025d1024b)
![image](https://github.com/user-attachments/assets/630ba77f-42b6-4630-a3a7-8cea7bfc4b73)
![image](https://github.com/user-attachments/assets/11ff9c38-25d5-4412-8fef-0b9ead7c1e9f)
![image](https://github.com/user-attachments/assets/fe6aa554-e855-4dd2-bb59-7c1c3e771b2f)
![image](https://github.com/user-attachments/assets/06a6cd17-91f6-45fb-88b7-3cb9e60507ae)
![image](https://github.com/user-attachments/assets/c35415f3-cf29-442f-b808-4f1081713217)

</details>

## Почему и что этот ПР улучшит
Делаем карту красивее и лучше 
## Авторство
Я

## Чеинжлог
:cl: Azzy.Dreemurr
 - map: Новые полы для станции Исход и Астероида

2024-05-17 18:09 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2024-05-17 18:10 UTC, maleyvich commented
картинки

2024-05-19 06:58 UTC, volas commented
Надо будет посмотреть, как выглядит в игре, может кладбище мапперов потыкать. Главное не переборщить с новыми плитками и делать в меру.

2024-05-19 18:06 UTC, WatlerJe commented
Как-то все же слишком много в коридорах и это нагружает визуал. Можешь попробовать размещать эту плитку перед и за дверью где проходит проводка.

2024-05-19 21:10 UTC, KIBORG04 commented
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/26389417/5cd916cb-745a-4c9d-b955-6b86c24b638a)

Вообще не смотрится в таких публичных коридорах. Выглядит скорее как технических(инженерных) элемент декора, чем как публичный для всех

2024-05-19 21:22 UTC, WhaleNotPower commented
Как написал Вальтер, слишком уже много объектов на глаз попадается и лучше сделать как декор редкий, не частый, возле шлюзов например. Но не прям как нити через всю станцию.

2024-06-10 07:13 UTC, volas commented
В инженерке имхо всё еще перебор, и как-то не симметрично. Под двигатель и в других местах, где плитки не было, новую ложить наверно и не стоит.

И если ложить в коридорах, я бы предложил вариант через несколько чередовать обычными плитками. 3 грида и 1 обычная, или 2 грида и 1 обычная, что-то такое.

2024-07-20 15:05 UTC, WhaleNotPower commented
И все равно, все равно все не айс. Зачем ты пихаешь плитку прозрачную в техническую зону стыковки шаттлов? Оно вообще не смотрится там. Все равно оставил эти линии технических плиток в инженерке, что тоже не айс, они не должны быть линией, это декор плитка раз в 10-15 тайлов, а ты ее монолитно ставишь. И вот как раз прогресс есть. Прозрачные плитки с названием станции, хорошо, красиво и по дизайнерски. Плитки технические в стыковке для зеков, тоже хорошо. Но остальное еще учитывать и учитывать

2024-07-20 23:34 UTC, KatoMarika requested changes
Тяжело. 

Начну с того что явно понравилось: 
![image](https://github.com/user-attachments/assets/ee8eb067-5987-480f-9c60-a9471bfe8991)
![image](https://github.com/user-attachments/assets/f432b3f8-3623-4fbb-b822-3b9219fd3fd5)
И другие подобные места. Прям конфетка. Но есть предложение: там где шлюзы выходят на площадки как на скрине выше(За исключением крупных как у мусорщиков, напрамер) сделать продолжение сетки.  Касательно подов читай пункт "мне не понравилось" про доки. Я бы оставил так. 
Поскольку есть такие места: 
![image](https://github.com/user-attachments/assets/3b86bee7-6c96-4b3c-96be-cce427bd4967)
Сетка, голый пол, сетка. 
И почему у синги не добавил, был бы стандарт по станции.
![image](https://github.com/user-attachments/assets/fd116945-9b17-4ce6-a02d-dfe9de500bd2)

Спорное:
![image](https://github.com/user-attachments/assets/c59a19f4-e036-4f17-b8a5-5c36bfc6f400)
Фиолетовое (делаю внимание на цвет) пятно посреди синих полов, мне не нравится. Возможно нужно переделать в синее. 

Что мне точно не понравилось: 
![image](https://github.com/user-attachments/assets/9fa1d163-9853-4ec3-be5e-008ff7d8bef5)
Эти и все остальные стыковочные доки всегда были темными\в мягком свете и таким местечком где можно сделать темное дело в темноте. Атмосферненькое такое. Но я не уверен что мне можно доверять в этом вопросе, я люблю более темное освещение и чем больше темных углов по станции - тем лучше. Может Волас выскажется или кто-то еще из маперов. Моё же мнение - не. 
![image](https://github.com/user-attachments/assets/e86c1393-1368-4d13-b740-8e8b939477f8)
Тут намного лучше. 

Атмос, подозреваю случайное нажатие. 
![image](https://github.com/user-attachments/assets/7f9190c7-f4b7-49c2-b27c-9e028ec05422)
ИИ. Возможно лучше был бы обычный, не укреп пол. А вот где укреп пол бы был бы хорош по твоим же скринам: на астеройде, где кругом решетка
![image](https://github.com/user-attachments/assets/d971806f-f35d-4f23-ae70-ba39f7a897a6)
Тут же я пожалуй забракую, опять же нужно второе мнение. 
![image](https://github.com/user-attachments/assets/65e82d7d-4445-45a6-bb8d-01784acae3a8)
И страдает опять логика, почему севернее не сделано? 
![image](https://github.com/user-attachments/assets/31218098-8c78-4936-bcbe-24da300cf232)
и особая категория, которая мне нравится в своем ужасе. Но только тут и нигде более. Это инженерный отсек, он должен быть инженерным, а не прилизанным офисом. Возможно что тут, в зоне отдыха инжей - не нужно. Но дальше можно попробовать. Но если мы хотим попробовать разместить этот тип плитки вне инженерного, как и сказала WhalePower: нельзя делать её много. Могу предложить места на проверку, как оно будет выглядеть: это места где много инженерных коммуникаций, с Т или X образными поворотами. Это еще и облегчит инженерам понимание как проводка и все трубы лежат. Но тут главное не перестараться. 
![image](https://github.com/user-attachments/assets/f73e5fd7-6566-4e3b-9c0f-ddab5a45e809)

Вроде ничего не упустил.

2024-07-21 14:17 UTC, KIBORG04 commented
Позовете, когда мап деп аппрувнет

2024-07-24 05:57 UTC, volas commented
Идея стекляннх коридоров понятна, но в шлюзах смотрится плохо - там какие-то декали еще намешаны. Это можно попробовать сделать, но лучше обсуждать отдельно.

Сетка в инженерке всё еще смотрится как-то невпопад.

Сетка в шлюзовых коридорах - хорошо, стеклянный коридор вокруг ИИ - хорошо (мне нравится как это выглядит), эксодус - лучше действительноп попробовать другое стекло, но идея ок.

2024-07-29 11:28 UTC, KatoMarika approved these changes
Вроде неплохо.

2024-07-30 07:24 UTC, volas commented
Последние замечания,
![Снимок экрана от 2024-07-30 10-18-33](https://github.com/user-attachments/assets/dbd4bed9-ee6c-4811-bd80-be971be78d29)
вот эту стену можно было бы убрать, выглядит странно.

И в космических стеклянных коридорах я бы может лучше везде использовал укрепленный стеклянный пол для текстуры.

В остальном я бы готов был смержить, но подержим в ТМ на пару дней еще, вдруг еще фидбек подкатят.

2024-07-31 15:07 UTC, KatoMarika approved these changes

2024-08-08 20:25 UTC, KatoMarika requested changes
<details><summary>Проблемные места: астеройд</summary>
<p>
Западный шахтерский аванпост почему без гридки? Везде есть, а тут нету

![image](https://github.com/user-attachments/assets/dc1ccd00-c5ae-41ea-929e-1e09f1938fe4)

РнД и шахтерка. Опять же нет гридки

![image](https://github.com/user-attachments/assets/76af4ec4-2b92-4fd1-9b82-dc9108efc3d2)


</p>
</details> 

<details><summary>Проблемные места: Коробка</summary>
<p>
Непонятно зачем, её там не видно и она ничего под собой не скрывает. 

![image](https://github.com/user-attachments/assets/c679806c-be6e-4db4-90da-ee92267b104f)

Восточные соляры выбиваются из общего стиля нового пола. 
![image](https://github.com/user-attachments/assets/1b4e56f1-4298-46c8-ab7f-c80d8211c2d4)


</p>
</details>

2024-08-11 23:48 UTC, volas commented
просьба уже добить, мап пр-ы в ТМ долго держать вредно

2024-08-12 08:31 UTC, KatoMarika approved these changes

2024-08-15 10:25 UTC, merged