Перевод консоли коммуникаций и связанных с ней вещей
TauCetiStation/TauCetiClassic pull request #13113
Opened 2024-05-25 07:02 UTC by maleyvich

## Описание изменений
тайтл
## Почему и что этот ПР улучшит
перевод
## Авторство
maleyvich, трансдеп таукиты

## Чеинжлог
:cl: maleyvich
- ru: Был переведен интерфейс консоли коммуникаций и связанных с ней вещей.

2024-05-25 07:02 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2024-05-25 07:04 UTC, maleyvich commented on code/game/machinery/alarm.dm
> +	to_chat(user, "Маленький индикатор указывает на то, что сейчас на станции код безопасности - [msg].")
```suggestion
	to_chat(user, "Маленький индикатор указывает на то, что сейчас на станции код тревоги - [msg].")
```

2024-05-25 09:09 UTC, KandreyKandrey commented on code/game/machinery/computer/communications.dm
> +	cases = list("консоль коммуникаций", "консоли коммуникаций", "консоли коммуникаций", "консоли коммуникаций", "консолью коммуникаций", "консоли коммуникаций")
```suggestion
	cases = list("консоль коммуникаций", "консоли коммуникаций", "консоли коммуникаций", "консоль коммуникаций", "консолью коммуникаций", "консоли коммуникаций")
```

2024-05-26 07:52 UTC, simb11 commented on code/game/machinery/computer/communications.dm
> +						message_admins("[key_name_admin(usr)] сменил код тревоги на [get_security_level()]. [ADMIN_JMP(usr)]")
А это разве нужно переводить?
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/84613249/2f53881f-7f4d-44cb-ab4b-1d6ec2deac2b)

2024-05-26 07:59 UTC, maleyvich commented on code/game/machinery/computer/communications.dm
> +						message_admins("[key_name_admin(usr)] сменил код тревоги на [get_security_level()]. [ADMIN_JMP(usr)]")
хз мне козлик сказал что можно для консистенции
типа чтоб не было usr has changed the security level to синий

2024-05-28 08:06 UTC, AirBlack commented on code/game/machinery/computer/communications.dm
> +					to_chat(usr, "<span class='warning'>Красный индикатор загорелся на консоли. Вероятно, вы не можете делать оповещения так быстро!</span>")
```suggestion
					to_chat(usr, "<span class='warning'>На консоли загорелся красный индикатор. Вероятно, вы не можете делать оповещения так быстро!</span>")
```

йода гейминг

2024-05-28 17:48 UTC, Kiromaka requested changes

2024-05-28 17:48 UTC, Kiromaka commented on code/game/machinery/computer/communications.dm
> +			to_chat(user, "У нас нет доступного шаттла в этом секторе, пожалуйста подождите.")
Везде "Центком", а тут "у нас"

2024-05-28 18:18 UTC, Kiromaka commented on code/game/machinery/computer/communications.dm
> +			to_chat(user, "У нас нет доступного шаттла в этом секторе, пожалуйста подождите.")
```suggestion
			to_chat(user, "Центком не имеет доступного шаттла в этом секторе, пожалуйста подождите.")
```
```suggestion
			to_chat(user, "У нас нет доступного шаттла в этом секторе, пожалуйста подождите.")
```

2024-05-29 21:17 UTC, simb11 commented on code/game/machinery/computer/communications.dm
> +				var/input = sanitize(input(usr, "Передайте оповещение Центкому через блюспейс-связь.  Не злоупотребляйте этой возможностью, иначе вы будете уволены или понижены...  Передача сообщения не гарантир
Почему не как в оригинале?
```suggestion
				var/input = sanitize(input(usr, "Передайте оповещение Центкому через блюспейс-связь.  Этот процесс является крайне затратным, потому злоупотребление им приведёт к вашему... увольнению.  Передача сообщения не гарантирует ответ. Между сообщениями есть промежуток в 30 секунд, поэтому они должны содержать полную информацию.", "Чтобы отменить, отправьте пустое сообщение.", ""))
```

Или хотя бы 

```suggestion
				var/input = sanitize(input(usr, "Передайте оповещение Центкому через блюспейс-связь.  Не злоупотребляйте этой возможностью, иначе вы будете... уволены.  Передача сообщения не гарантирует ответ. Между сообщениями есть промежуток в 30 секунд, поэтому они должны содержать полную информацию.", "Чтобы отменить, отправьте пустое сообщение.", ""))
```
Ну или убери это троеточие к ебеням, потому что оно вообще непонятно к чему вставлено в твоём варианте.

2024-05-29 21:22 UTC, simb11 commented on code/game/machinery/computer/communications.dm
> +				dat += "<font color='red'><b>Активирован механизм самоуничтожения. Деактивируйте механизм для снижения кода.</b></font>"
```suggestion
				dat += "<font color='red'><b>Активирован механизм самоуничтожения. Деактивируйте механизм для снижения кода или эвакуируйтесь.</b></font>"
```
Или почему упоминание эвакуации убрали?

2024-05-30 09:25 UTC, Kiromaka commented on code/game/machinery/computer/communications.dm
> +				dat += "<font color='red'><b>Активирован механизм самоуничтожения. Деактивируйте механизм для снижения кода.</b></font>"
Это просто странное оповещение. Станционную ядерку врубают или деды, или при био-угрозе - блоб/реплики. В обоих случаях эвакуация запрещена: в первом у НТ цель перерезать станцию, во втором - карантин - и у НТ цель взорвать станцию, вместе с экипажем.

2024-06-03 17:36 UTC, daedrowe commented on code/game/machinery/alarm.dm
> +	to_chat(user, "Маленький индикатор указывает на то, что сейчас на станции код тревоги - [msg].")
```suggestion
	to_chat(user, "Маленький индикатор указывает [msg] код тревоги.")
```

2024-06-03 17:36 UTC, daedrowe commented on code/game/machinery/computer/communications.dm
> +				var/input = sanitize(input(usr, "Передайте оповещение Центкому через блюспейс-связь. Этот процесс является крайне затратным, потому злоупотребление им приведёт к вашему увольнению.  Передача сооб
```suggestion
				var/input = sanitize(input(usr, "Передайте оповещение Центкому через квантовую связь. Этот процесс является крайне затратным, потому злоупотребление им приведёт к вашему... увольнению.  Передача сообщения не гарантирует ответ. Между сообщениями есть промежуток в 30 секунд, поэтому они должны содержать полную информацию.", "Чтобы отменить, отправьте пустое сообщение.", ""))
```
можно конечно оставить православную блюспейс связь, вариант с буквальным переводом вызывает кринж, но "квантовая связь" уже звучит неплохо

2024-06-03 17:36 UTC, daedrowe commented on code/game/machinery/computer/communications.dm
> +				var/input = sanitize(input(usr, "Передайте оповещение \[НЕВЕРОЯТНО КРУТЫМ ПАРНЯМ\] через блюспейс-связь.  Этот процесс является крайне затратным, потому злоупотребление им приведёт к вашему уволь
```suggestion
				var/input = sanitize(input(usr, "Передайте сообщение \[АНОМАЛЬНЫЕ КООРДИНАТЫ\] через квантовую связь.  Этот процесс является крайне затратным, потому злоупотребление им приведёт к вашему увольнению.  Передача сообщения не гарантирует ответ. Между сообщениями есть промежуток в 30 секунд, поэтому они должны содержать полную информацию.", "Чтобы отменить, отправьте пустое сообщение.", ""))
```
вариант с невероятно крутыми парнями крутой, его тоже можно

2024-06-03 17:36 UTC, daedrowe commented on code/game/machinery/computer/communications.dm
> +						dat += "<BR><A HREF='?src=\ref[src];operation=MessageCentcomm'>Отправить экстренное оповещение Центкому</A>"
```suggestion
						dat += "<BR><A HREF='?src=\ref[src];operation=MessageCentcomm'>Отправить экстренное сообщение Центкому</A>"
```

2024-06-03 17:36 UTC, daedrowe commented on code/game/machinery/computer/communications.dm
> +						dat += "<BR><A HREF='?src=\ref[src];operation=MessageSyndicate'>Отправить экстренное оповещение \[НЕВЕРОЯТНО КРУТЫМ ПАРНЯМ\]</A>"
```suggestion
						dat += "<BR><A HREF='?src=\ref[src];operation=MessageSyndicate'>Отправить экстренное сообщение \[НЕВЕРОЯТНО КРУТЫМ ПАРНЯМ\]</A>"
```

2024-06-03 17:36 UTC, daedrowe commented on code/game/machinery/computer/communications.dm
> +				dat += "<BR><A HREF='?src=\ref[src];operation=login'>Авторизироваться в систему</A>"
```suggestion
				dat += "<BR><A HREF='?src=\ref[src];operation=login'>Авторизироваться</A>"
```

2024-06-03 17:48 UTC, maleyvich commented on code/game/machinery/alarm.dm
> +	to_chat(user, "Маленький индикатор указывает на то, что сейчас на станции код тревоги - [msg].")
плохо звучит

2024-06-03 17:49 UTC, maleyvich commented on code/game/machinery/computer/communications.dm
> +				var/input = sanitize(input(usr, "Передайте оповещение Центкому через блюспейс-связь. Этот процесс является крайне затратным, потому злоупотребление им приведёт к вашему увольнению.  Передача сооб
троеточие и квантовая связь убраны специально

2024-06-03 17:49 UTC, maleyvich commented on code/game/machinery/computer/communications.dm
> +				var/input = sanitize(input(usr, "Передайте оповещение \[НЕВЕРОЯТНО КРУТЫМ ПАРНЯМ\] через блюспейс-связь.  Этот процесс является крайне затратным, потому злоупотребление им приведёт к вашему уволь
пусть останется как было

2024-06-03 17:49 UTC, maleyvich commented on code/game/machinery/computer/communications.dm
> +						dat += "<BR><A HREF='?src=\ref[src];operation=MessageCentcomm'>Отправить экстренное оповещение Центкому</A>"
норм

2024-06-03 17:53 UTC, daedrowe commented on code/game/machinery/alarm.dm
> +	to_chat(user, "Маленький индикатор указывает на то, что сейчас на станции код тревоги - [msg].")
индикатор указывает плохо звучит, это правда

2024-06-03 17:58 UTC, Kiromaka commented on code/game/machinery/computer/communications.dm
> +				var/input = sanitize(input(usr, "Передайте оповещение \[НЕВЕРОЯТНО КРУТЫМ ПАРНЯМ\] через блюспейс-связь.  Этот процесс является крайне затратным, потому злоупотребление им приведёт к вашему уволь
Ну небольшая вставочка, можно оставить.

2024-06-03 18:34 UTC, daedrowe commented on code/game/machinery/alarm.dm
> +	to_chat(user, "Маленький индикатор указывает на то, что сейчас на станции код тревоги - [msg].")
не, это просто буквальный и лаконичный перевод

2024-06-05 14:45 UTC, maleyvich commented
> @maleyvich добавь в описание ПРа пару скриншотов с переводом панельки

сделано

2024-06-10 07:26 UTC, maleyvich commented
бамп

2024-06-10 19:45 UTC, Chip11-n commented on code/game/machinery/computer/communications.dm
> +						dat += "<BR><A HREF='?src=\ref[src];operation=MessageSyndicate'>Отправить экстренное сообщение \[НЕВЕРОЯТНО КРУТЫМ ПАРНЯМ\]</A>"
Оно конечно и выше было, но тут оно выглядит смешней. Честно, я даже не знаю что и сказать. Я пока морально не готов скролить дальше 😂

Пойду что ли пилить ПР с блобом из яйца?

2024-06-12 09:35 UTC, maleyvich commented
бамп

2024-06-17 11:16 UTC, maleyvich commented
баамп

2024-06-17 11:31 UTC, volas commented
возмущайся, когда увидишь, что другие пр-ы ревьювят а твой игнорят. Сейчас просто не было времени. Комментарий чипа кстати валидный, нет смысла смотреть пока вы хотя бы с этим не разберетесь.

2024-06-18 12:35 UTC, volas requested changes

2024-06-18 12:35 UTC, volas commented on code/modules/security_levels/security_levels.dm
> +			return "дельта"
Если переводите возврат функции - просьба сразу смотреть, где этот возврат используется. Тут не очень хорошее изменение, так как оно используется в некоторых других местах, в т.ч. чисто технических (суффикс спрайтов, где кириллица не будет скорее всего работать).

Как предложение, просто уберите эти три функции, и сделайте два глобальных массива вида
```
var/global/list/code_name_eng = list("green", "blue", "red", "delta")
var/global/list/code_name_ru = list("зелёный", "синий", "красный", "дельта")
```

Потом можно просто в зависимости от контекста использовать по типу ``code_name_ru[security_level]`` (вместо get_security_level()), ``code_name_eng[security_level]`` (для логов выше), ``code_name_eng[SEC_LEVEL_BLUE]`` (вместо num2seclevel()) и т.д.

Когда-нибудь потом кто-то это всё перенесет из глобального неймспейса и сделает макросы, но это уже будет другая история о рефаторинге.

2024-06-18 12:35 UTC, volas commented on code/game/machinery/computer/communications.dm
> +						dat += "<BR><A HREF='?src=\ref[src];operation=MessageSyndicate'>Отправить экстренное сообщение \[НЕИЗВЕСТНЫМ\]</A>"
```suggestion
						dat += "<BR><A HREF='?src=\ref[src];operation=MessageSyndicate'>Отправить экстренное сообщение \[НЕИЗВЕСТНО\]</A>"
```

ТНЫМ подразумевает, что нам уже известно, что это кто-то определенный. По смыслу тут больше неизвестные координаты/неизвестный номер/непонятно куда и т.д. И они неизвестные консоли, а не юзеру.

Можно еще на ОШИБКА заменить, если НЕИЗВЕСТНО будет резать глаз.

2024-06-19 19:35 UTC, AmnyamNyam commented on code/game/machinery/computer/communications.dm
> +					to_chat(usr, "<span class='warning'>Обработка информации. Ожидайте.</span>")
Это перевод касательно задержки перед повторным отправлением сообщения на ЦК.

Какую же он информацию обрабатывает? В данном случае он здесь перезаряжается/перегружается/готовится к повторной работе, если речь идет об блюспейс-передатчике, полагаю? Точно переводить не нужно уж совсем, но смысл сохранять стоит.

"Обработка информации" означает, что сообщение еще не передалось твое, а только ОБРАБАТЫВАЕТСЯ перед этим, а значит ЦК еще не получило его. Однако по механу оно сразу отправляется.

Вот тебе красивые варианты:

"Идёт процесс перезарядки/перегрузки блюспейс-передатчика. Ожидайте."

Можно использовать слово ретранслятор, но ретранслятор выполняет роль усиления отправленного сигнала, что как бы натянуто, но звучит красиво. В конце-концов мы не знаем по какой методике работает блюспейс связь. Может в стиле Передатчик -> Блюспейс-ретранслятор, который усиливает сигнал на более дальние дистанции. -> Приемник на ЦК.

"Идёт процесс перезарядки/перегрузки блюспейс-ретранслятора. Ожидайте."

Вообще я не знаю как мы называем "блюспейс", поэтому можно просто "ретранслятор, передатчик"

2024-06-19 19:35 UTC, AmnyamNyam commented on code/game/machinery/computer/communications.dm
> +					to_chat(usr, "<span class='warning'>Обработка информации. Ожидайте.</span>")
"Очистка массивов" звучит красиво, но ничего не понятно.

Однако просто и коротко. ТЫЖПрограммисткий сленг.

2024-06-19 19:35 UTC, AmnyamNyam commented on code/game/machinery/computer/communications.dm
> +				var/input = sanitize(input(usr, "Передайте оповещение Центкому через блюспейс-связь. Этот процесс является крайне затратным, потому злоупотребление им приведёт к вашему увольнению.  Передача сооб
МОЖЕТ БЫТЬ, тут стоит использовать прямой перевод.
**quantum entanglement - квантовая запутанность**

[Вырезка из гугла: 
"По сути, **квантовая запутанность** - это уникальное свойство квантового мира, когда частицы (связанные друг с другом, то есть запутанные) могут "чувствовать" друг друга на расстоянии и мгновенно менять свое состояние в ответ на изменение состояния другой частицы."]

это принцип работы БЛЮСПЕЙС-СВЯЗИ, поэтому, по моему мнению, стоит писать как есть.

**"Отправьте сообщение Центкому с помощью метода квантовой запутанности"**

Ты, конечно, можешь назвать это блюспейс-связью, но блюспейса так много, что это уже не футуризм, а какая-то религиозная издевка в стиле "На все воля блюспейса"
--------
Так же вместо "ПОЛНУЮ" напиши "Важную и подробную", чтобы было в итоге

"Передача сообщения не гарантирует ответ. Между сообщениями есть промежуток в 30 секунд, поэтому они должны содержать **важную и подробную** информацию"

2024-06-19 19:35 UTC, AmnyamNyam commented on code/game/machinery/computer/communications.dm
> +					to_chat(usr, "<span class='warning'>Обработка информации. Ожидайте.</span>")
Читай выше.

2024-06-19 19:35 UTC, AmnyamNyam commented on code/game/machinery/computer/communications.dm
> +				var/input = sanitize(input(usr, "Передайте оповещение \[НЕИЗВЕСТНЫМ\] через блюспейс-связь.  Этот процесс является крайне затратным, потому злоупотребление им приведёт к вашему увольнению.  Перед
Читай выше.

2024-06-19 19:35 UTC, AmnyamNyam commented on code/game/machinery/computer/communications.dm
> +			to_chat(usr, "Изначальные данные восстановлены!")
Прямой гугловский перевод ОТЛИЧНО справляется с этой задачей

"Backup routing data restored!" - "Резервные данные маршрутизации восстановлены!"

Почитай что такое маршрутизация в сетях.

2024-06-19 19:35 UTC, AmnyamNyam commented on code/game/machinery/computer/communications.dm
> +	to_chat(user, "Вы сбили изначальную частоту консоли коммуникаций!")
Ты вообще понимаешь, что ты переводишь?
Это взлом консоли. Какую изначальную частоту? Чего? Ты знаешь что значит слово частота в данном контексте?

Гугл-переводчик как всегда спасает положение:

"You scramble the communication routing circuits" - "Вы шифруете схемы маршрутизации связи"

2024-06-19 19:35 UTC, AmnyamNyam commented on code/game/machinery/computer/communications.dm
> +		to_chat(usr, "<span class='warning'><b>Невозможно установить связь</b>:</span> Вы слишком далеко от станции!")
НЕВОЗМОЖНО УСТАНОВИТЬ **СОЕДИНЕНИЕ**

Пиши грамотным техническим языком!

2024-06-19 19:35 UTC, AmnyamNyam commented on code/game/machinery/computer/communications.dm
> +		dat += "<B>Шаттл</B>\n<BR>\nПримерное время прибытия: [shuttleeta2text()]<BR>"
Куда слово аварийный пропало?

Шаттл у нас один, но контекста вызова его ДВА.

2024-06-19 19:35 UTC, AmnyamNyam commented on code/game/machinery/computer/communications.dm
> +			var/datum/browser/popup = new(user, "communications", "Консоль коммуникаций", 400, 500)
Communications Console - Коммуникационная консоль.

ПИШИ ТЕХНИЧЕСКИМ ЯЗЫКОМ.

Можешь почитать об это где-нибудь.

2024-06-19 19:35 UTC, AmnyamNyam commented on code/game/machinery/computer/communications.dm
> +						dat += "<BR><A HREF='?src=\ref[src];operation=RestoreBackup'>Восстановить изначальные данные</A>"
ГУГЛ ПЕРЕВОД ПОБЕЖДАЕТ

"Restore Backup Routing Data" - "Восстановить резервные данные маршрутизации"

ПОЧИТАЙ ЧТО ТАКОЕ МАРШРУТИЗАЦИЯ.

2024-06-19 19:35 UTC, AmnyamNyam commented on code/game/machinery/computer/communications.dm
> +				dat += "<BR><A HREF='?src=\ref[src];operation=status'>Установить оповещение на дисплеи</A>"
ЯЗЫК ТЕХНОЖРЕЦОВ

Set Status Display - Установить Статус Дисплея/Панели/Монитора

Дисплей правда лучше всех звучит

2024-06-19 19:35 UTC, AmnyamNyam commented on code/game/machinery/computer/communications.dm
> +				dat += "<BR><A HREF='?src=\ref[src];operation=login'>Авторизироваться</A>"
# Авторизоваться

2024-06-19 19:35 UTC, AmnyamNyam commented on code/game/machinery/computer/communications.dm
> +			dat += "<A HREF='?src=\ref[src];operation=setstat;statdisp=default'>Стандартный режим</A><BR>"
По умолчанию

2024-06-19 19:35 UTC, AmnyamNyam commented on code/game/machinery/computer/communications.dm
> +			dat += "<A HREF='?src=\ref[src];operation=setstat;statdisp=message'>Режим передачи сообщений</A>"
СООБЩЕНИЕ

2024-06-19 19:35 UTC, AmnyamNyam commented on code/game/machinery/computer/communications.dm
> +			dat += "<A HREF='?src=\ref[src];operation=setstat;statdisp=shuttle'>Время прибытия шаттла</A><BR>"
Время ДО прибытия шаттла.

Это не фиксированное время, а его ОТСЧЕТ

2024-06-19 19:35 UTC, AmnyamNyam commented on code/game/machinery/computer/communications.dm
> +			dat += " <A HREF='?src=\ref[src];operation=setstat;statdisp=alert;alert=lockdown'>Изоляция</A> |"
Имеется ввиду про вирусы

КАРАНТИН

2024-06-19 19:35 UTC, AmnyamNyam commented on code/game/machinery/computer/communications.dm
> +			dat += " <A HREF='?src=\ref[src];operation=setstat;statdisp=alert;alert=biohazard'>Биологическая опасность</A><BR><HR>"
Биологическая УГРОЗА

2024-06-19 19:35 UTC, AmnyamNyam commented on code/game/machinery/computer/communications.dm
> +	var/datum/browser/popup = new(user, "communications", "Консоль коммуникаций", 400, 500)
Читай выше!

2024-06-19 19:35 UTC, AmnyamNyam commented on code/game/machinery/computer/communications.dm
> +				dat += "<BR><A HREF='?src=\ref[src];operation=ai-callshuttle'>Вызвать шаттл</A>"
АВАРИЙНЫЙ шаттл
Читай выше!

2024-06-19 19:35 UTC, AmnyamNyam commented on code/game/machinery/computer/communications.dm
> +		to_chat(user, "Шаттл возвращается к отделению Центкома, вызов невозможен.")
Аварийный шаттл!

Не теряй слова! Об этом написано выше.

2024-06-19 19:35 UTC, AmnyamNyam commented on code/game/machinery/computer/communications.dm
> +		to_chat(user, "Шаттл уже вызван.")
Аварийный.

2024-06-19 19:35 UTC, AmnyamNyam commented on code/game/machinery/computer/communications.dm
> +		to_chat(user, "Шаттл возвращается к отделению Центкома, вызов невозможен.")
на Центком.

Какое отделение? Полиции?

Убери отсебятину.

2024-06-20 04:42 UTC, maleyvich commented on code/game/machinery/computer/communications.dm
> +				var/input = sanitize(input(usr, "Передайте оповещение Центкому через блюспейс-связь. Этот процесс является крайне затратным, потому злоупотребление им приведёт к вашему увольнению.  Передача сооб
да не так уж и много блюспейса у нас в билде 

а квантовая запутанность чёто как-то непонятно звучит для обычного игрочка таусети

2024-06-20 04:43 UTC, maleyvich commented on code/game/machinery/computer/communications.dm
> +				var/input = sanitize(input(usr, "Передайте оповещение Центкому через блюспейс-связь. Этот процесс является крайне затратным, потому злоупотребление им приведёт к вашему увольнению.  Передача сооб
а насчёт замены слова полную ну норм вроде бы

2024-06-20 04:45 UTC, maleyvich commented on code/game/machinery/computer/communications.dm
> +	desc = "Эта консоль имеет очень большой функционал для контроля станции."
я думаю пещерные (ну или не совсем) люди и писали описание для этого но идея норм 

```suggestion
	desc = "Эта консоль имеет функционал для управления станцией."
```

2024-06-20 04:47 UTC, maleyvich commented on code/game/machinery/computer/communications.dm
> +		to_chat(user, "Шаттл возвращается к отделению Центкома, вызов невозможен.")
```suggestion
		to_chat(user, "Шаттл возвращается к Центкому, вызов невозможен.")
```

2024-06-20 04:49 UTC, maleyvich commented on code/game/machinery/computer/communications.dm
> +		to_chat(usr, "<span class='warning'><b>Невозможно установить связь</b>:</span> Вы слишком далеко от станции!")
```suggestion
		to_chat(usr, "<span class='warning'><b>Невозможно установить соединение</b>:</span> Вы слишком далеко от станции!")
```

2024-06-20 04:51 UTC, maleyvich commented on code/game/machinery/computer/communications.dm
> +					to_chat(usr, "Вы не авторизованы!")
мне показалось что будет лучше когда меньше текста, но ок
```suggestion
					to_chat(usr, "Вы не авторизованы для проведения данной операции!")
```

2024-06-20 04:53 UTC, maleyvich commented on code/game/machinery/computer/communications.dm
> +					to_chat(usr, "Вы не авторизованы!")
```suggestion
					to_chat(usr, "У вас недостаточно прав для выполнения этой операции!")
```

2024-06-20 04:56 UTC, maleyvich commented on code/game/machinery/computer/communications.dm
> +					to_chat(usr, "<span class='warning'>Обработка информации. Ожидайте.</span>")
```suggestion
					to_chat(usr, "<span class='warning'>Блюспейс-передатчик в состоянии перезагрузки. Ожидайте.</span>")
```

2024-06-20 04:57 UTC, maleyvich commented on code/game/machinery/computer/communications.dm
> +					to_chat(usr, "<span class='warning'>На консоли загорелся красный индикатор. Вероятно, вы не можете делать оповещения так быстро!</span>")
```suggestion
					to_chat(usr, "<span class='warning'>На консоли мигает красный индикатор. Вероятно, вы не можете делать оповещения так быстро!</span>")
```

2024-06-20 23:34 UTC, AmnyamNyam commented on code/game/machinery/computer/communications.dm
> +			dat += "<A HREF='?src=\ref[src];operation=setstat;statdisp=message'>Режим передачи сообщений</A>"
просто СООБЩЕНИЕ

2024-06-20 23:40 UTC, AmnyamNyam commented
Закончи до конца правки, что я предложил. Переводить все нужно максимально качественно, иначе ты рискуешь создать некорректные зависимости в переводе текста, когда последующие переводы будут зависимы от того, что уже есть.

В этом случае тебе придется делать двойную работу.

2024-06-22 04:55 UTC, maleyvich commented on code/datums/announcements/events.dm
> +	message = "Цитирую вопрос из Центкома. Какого хрена это было?!"
```suggestion
	message = "Цитирую вопрос из ЦентКома. Какого хрена это было?!"
```

2024-06-22 04:55 UTC, maleyvich commented on code/game/machinery/computer/communications.dm
> +				dat += "<BR><A HREF='?src=\ref[src];operation=login'>Авторизироваться</A>"
```suggestion
				dat += "<BR><A HREF='?src=\ref[src];operation=login'>Авторизоваться</A>"
```

2024-06-22 04:55 UTC, maleyvich commented on code/game/machinery/computer/communications.dm
> +			dat += "<A HREF='?src=\ref[src];operation=setstat;statdisp=default'>Стандартный режим</A><BR>"
```suggestion
			dat += "<A HREF='?src=\ref[src];operation=setstat;statdisp=default'>По умолчанию</A><BR>"
```

2024-06-22 04:55 UTC, maleyvich commented on code/game/machinery/computer/communications.dm
> +			dat += "<A HREF='?src=\ref[src];operation=setstat;statdisp=shuttle'>Время прибытия шаттла</A><BR>"
```suggestion
			dat += "<A HREF='?src=\ref[src];operation=setstat;statdisp=shuttle'>Время до прибытия шаттла</A><BR>"
```

2024-06-22 04:55 UTC, maleyvich commented on code/game/machinery/computer/communications.dm
> +			dat += "<A HREF='?src=\ref[src];operation=setstat;statdisp=message'>Режим передачи сообщений</A>"
сомнительно но оукээй
```suggestion
			dat += "<A HREF='?src=\ref[src];operation=setstat;statdisp=message'>Сообщение</A>"
```

2024-06-22 04:55 UTC, maleyvich commented on code/game/machinery/computer/communications.dm
> +			dat += " <A HREF='?src=\ref[src];operation=setstat;statdisp=alert;alert=biohazard'>Биологическая опасность</A><BR><HR>"
```suggestion
			dat += " <A HREF='?src=\ref[src];operation=setstat;statdisp=alert;alert=biohazard'>Биологическая угроза</A><BR><HR>"
```

2024-06-22 04:55 UTC, maleyvich commented on code/game/machinery/computer/communications.dm
> +			dat += " <A HREF='?src=\ref[src];operation=setstat;statdisp=alert;alert=lockdown'>Изоляция</A> |"
```suggestion
			dat += " <A HREF='?src=\ref[src];operation=setstat;statdisp=alert;alert=lockdown'>Карантин</A> |"
```

2024-06-22 04:55 UTC, maleyvich commented on code/game/machinery/computer/communications.dm
> +				dat += "<BR><A HREF='?src=\ref[src];operation=ai-callshuttle'>Вызвать шаттл</A>"
```suggestion
				dat += "<BR><A HREF='?src=\ref[src];operation=ai-callshuttle'>Вызвать аварийный шаттл</A>"
```

2024-06-22 04:55 UTC, maleyvich commented on code/game/machinery/computer/communications.dm
> +			dat += "Вы уверены, что хотите вызвать шаттл? <A HREF='?src=\ref[src];operation=ai-callshuttle2'>ДА</A> | <A HREF='?src=\ref[src];operation=ai-main'>НЕТ</A>"
```suggestion
			dat += "Вы уверены, что хотите вызвать аварийный шаттл? <A HREF='?src=\ref[src];operation=ai-callshuttle2'>ДА</A> | <A HREF='?src=\ref[src];operation=ai-main'>НЕТ</A>"
```

2024-06-22 04:55 UTC, maleyvich commented on code/game/machinery/computer/communications.dm
> +		to_chat(user, "Шаттл возвращается к отделению Центкома, вызов невозможен.")
```suggestion
		to_chat(user, "Аварийный шаттл возвращается к отделению Центкома, вызов невозможен.")
```

2024-06-22 04:55 UTC, maleyvich commented on code/game/machinery/computer/communications.dm
> +		to_chat(user, "Шаттл уже вызван.")
```suggestion
		to_chat(user, "Аварийный шаттл уже вызван.")
```

2024-06-22 04:55 UTC, maleyvich commented on code/game/machinery/computer/communications.dm
> +				dat += "<BR><A HREF='?src=\ref[src];operation=status'>Установить оповещение на дисплеи</A>"
```suggestion
				dat += "<BR><A HREF='?src=\ref[src];operation=status'>Установить статус дисплея</A>"
```

2024-06-22 04:55 UTC, maleyvich commented on code/game/machinery/computer/communications.dm
> +						dat += "<BR><A HREF='?src=\ref[src];operation=RestoreBackup'>Восстановить изначальные данные</A>"
```suggestion
						dat += "<BR><A HREF='?src=\ref[src];operation=RestoreBackup'>Восстановить резервные данные маршрутизации</A>"
```

2024-06-22 04:55 UTC, maleyvich commented on code/game/machinery/computer/communications.dm
> +	to_chat(user, "Вы сбили изначальную частоту консоли коммуникаций!")
```suggestion
	to_chat(user, "Вы шифруете схемы маршрутизации связи!")
```

2024-06-22 04:55 UTC, maleyvich commented on code/game/machinery/computer/communications.dm
> +		to_chat(usr, "<span class='warning'><b>Невозможно установить связь</b>:</span> Вы слишком далеко от станции!")
```suggestion
		to_chat(usr, "<span class='warning'><b>Невозможно установить соединение</b>:</span> Вы слишком далеко от станции!")
```

2024-06-22 04:55 UTC, maleyvich commented on code/game/machinery/computer/communications.dm
> +		dat += "<B>Шаттл</B>\n<BR>\nПримерное время прибытия: [shuttleeta2text()]<BR>"
```suggestion
		dat += "<B>Аварийный шаттл</B>\n<BR>\nПримерное время прибытия: [shuttleeta2text()]<BR>"
```

2024-06-22 04:55 UTC, maleyvich commented on code/game/machinery/computer/communications.dm
> +			var/datum/browser/popup = new(user, "communications", "Консоль коммуникаций", 400, 500)
пусть так и останется, у нас не технари всякие в игру играют. игроки чаще всего называют её консолью коммуникаций.

2024-06-22 04:55 UTC, maleyvich commented on code/game/machinery/computer/communications.dm
> +	var/datum/browser/popup = new(user, "communications", "Консоль коммуникаций", 400, 500)
выше и ответил

2024-07-15 04:44 UTC, maleyvich commented on code/modules/security_levels/security_levels.dm
> +var/global/list/code_name_eng = list("green", "blue", "red", "delta")
это тоже потенциально что то да и сломает.
возможно стоит оставить прок но ладно

2024-07-15 05:45 UTC, volas commented on code/game/response_team/response_team.dm
> +	if(code_name_ru[security_level] != "red") // Allow admins to reconsider if the alert level isn't Red
code_name_eng

2024-07-15 05:45 UTC, volas commented on code/game/machinery/computer/shop.dm
> -			secLevelStr = "<font color='green'><b>&#9899;</b></font>"
потеряли тег с цветом

2024-07-15 05:45 UTC, volas commented on code/game/objects/items/devices/PDA/PDA.dm
> -			secLevelStr = "<font color='green'><b>&#9899;</b></font>"
как и тут

2024-07-15 06:12 UTC, maleyvich commented on code/game/objects/items/devices/PDA/PDA.dm
> -			secLevelStr = "<font color='green'><b>&#9899;</b></font>"
вроде бы исправил

2024-07-15 06:12 UTC, maleyvich commented on code/game/machinery/computer/shop.dm
> -			secLevelStr = "<font color='green'><b>&#9899;</b></font>"
тоже исправил

2024-07-21 14:30 UTC, KIBORG04 commented on code/game/machinery/computer/communications.dm
> +			to_chat(user, "Шаттл находится на дозаправке. Пожалуйста, подождите еще [round((54000-world.time)/600)] минут до повторного вызова.")//may need to change "/600"
```suggestion
			to_chat(user, "Шаттл находится на дозаправке. Пожалуйста, подождите еще [round((54000-world.time)/600)] минут до повторного вызова.")//may need to change "/600"
```
подождите еще 5 минут
подождите еще 4 минут
подождите еще 3 минут
подождите еще 2 минут
подождите еще 1 минут

Для минут заюзай russia_pluralize или как там, пердеп шарит

2024-07-21 14:31 UTC, KIBORG04 commented on code/game/machinery/computer/communications.dm
> +			to_chat(user, "Центком не имеет доступного шаттла в этом секторе, пожалуйста подождите.")
```suggestion
			to_chat(user, "Центком не имеет доступного шаттла в этом секторе, пожалуйста, подождите.")
```
Пж - это вроде вводное слово или че-то такое и вроде с обоих сторон нужна запятая

2024-07-21 14:32 UTC, KIBORG04 commented on code/game/machinery/computer/communications.dm
> +		to_chat(user, "Шаттл находится на дозаправке. Пожалуйста, подождите еще [round((6000-world.time)/600)] минут до повторного вызова.")
То же самое

2024-07-21 14:33 UTC, KIBORG04 commented on code/game/machinery/computer/communications.dm
> +			dat += "<A HREF='?src=\ref[src];operation=setstat;statdisp=default'>Стандартный режим</A><BR>"
Откуда взялся стандартный режим? Слева его не вижу

2024-07-21 14:34 UTC, KIBORG04 commented on code/game/machinery/computer/communications.dm
> +			dat += "<li> Линия 2: <A HREF='?src=\ref[src];operation=setmsg2'>[ stat_msg2 ? stat_msg2 : "(none)"]</A></ul><br>"
```suggestion
			dat += "<ul><li> Линия 1: <A HREF='?src=\ref[src];operation=setmsg1'>[ stat_msg1 ? stat_msg1 : "(НОНЕ)"]</A>"
			dat += "<li> Линия 2: <A HREF='?src=\ref[src];operation=setmsg2'>[ stat_msg2 ? stat_msg2 : "(НОНЕ)"]</A></ul><br>"
```
Не тронуто

2024-07-21 14:36 UTC, KIBORG04 commented on code/game/machinery/computer/communications.dm
> +			dat += "Подтвердить смену кода тревоги на: [code_name_ru[SEC_LEVEL_BLUE]]<BR>"
```suggestion
			dat += "Подтвердить смену кода тревоги на: [code_name_ru[SEC_LEVEL_BLUE]]<BR>"
```
Поч раньше передавался tmp_alertlevel. а теперь только SEC_LEVEL_BLUE? Я хз, жду объяснения

2024-07-21 14:45 UTC, KIBORG04 commented on code/game/machinery/computer/communications.dm
> +		to_chat(usr, "<span class='warning'><b>Невозможно установить соединение</b>:</span> Вы слишком далеко от станции!")
```suggestion
		to_chat(user, "<span class='warning'><b>Невозможно установить соединение</b>:</span> Вы слишком далеко от станции!")
```
За что юзера то..

2024-07-21 14:46 UTC, KIBORG04 commented on code/game/machinery/computer/communications.dm
> +			to_chat(usr, "Изначальные данные восстановлены!")
Согласен с амнямом. 

Ну и раз вы уже перевели ниже это таким образом, почему тут другое?
![image](https://github.com/user-attachments/assets/c95f41ee-0d9a-40fa-8b66-8ce865f43816)

2024-07-21 14:48 UTC, KIBORG04 commented on code/game/machinery/computer/communications.dm
> +				var/input = sanitize(input(usr, "Передайте оповещение Центкому через блюспейс-связь. Этот процесс является крайне затратным, потому злоупотребление им приведёт к вашему увольнению.  Передача сооб
> а квантовая запутанность чёто как-то непонятно звучит для обычного игрочка таусети

Мега попсовая штука уже

2024-07-21 14:51 UTC, KIBORG04 commented on code/game/machinery/computer/communications.dm
> +				var/input = sanitize(input(usr, "Передайте оповещение \[НЕИЗВЕСТНЫМ\] через блюспейс-связь.  Этот процесс является крайне затратным, потому злоупотребление им приведёт к вашему увольнению.  Перед
Двойные пробелы уберите, страшные же

2024-07-21 14:51 UTC, KIBORG04 commented on code/game/machinery/computer/communications.dm
> +				var/input = sanitize(input(usr, "Передайте оповещение Центкому через блюспейс-связь. Этот процесс является крайне затратным, потому злоупотребление им приведёт к вашему увольнению.  Передача сооб
Двойные пробелы уберите, страшные же

2024-07-21 14:51 UTC, maleyvich commented on code/game/machinery/computer/communications.dm
> +			dat += "<A HREF='?src=\ref[src];operation=setstat;statdisp=default'>Стандартный режим</A><BR>"
```suggestion
			dat += "<A HREF='?src=\ref[src];operation=setstat;statdisp=default'>РВП шаттла</A><BR>"
```

2024-07-21 14:52 UTC, KIBORG04 commented on code/game/machinery/alarm.dm
> +			add_overlay(image('icons/obj/monitors.dmi', "code_name_ru[security_level]"))
```suggestion
			add_overlay(image('icons/obj/monitors.dmi', "code_name_eng[security_level]"))
```
мда

2024-07-21 14:54 UTC, KIBORG04 commented on code/game/machinery/alarm.dm
> +	to_chat(user, "Маленький индикатор указывает [msg] код тревоги.")
Пропала фича, когда слово имело другой цвет шрифта

2024-07-21 14:56 UTC, KIBORG04 commented on code/game/machinery/alarm.dm
> +			add_overlay(image('icons/obj/monitors.dmi', "code_name_ru[security_level]"))
Смотри. когда коммитишь, я накосячил, а ты уже..

2024-07-21 14:56 UTC, KIBORG04 commented on code/game/machinery/alarm.dm
> +			add_overlay(image('icons/obj/monitors.dmi', "code_name_eng[security_level]"))
```suggestion
			add_overlay(image('icons/obj/monitors.dmi', "overlay_[code_name_eng[security_level]]"))
```

2024-08-03 15:59 UTC, Udokun commented on code/game/machinery/computer/communications.dm
> +				var/input = sanitize(input(usr, "Передайте оповещение Центкому через блюспейс-связь. Этот процесс является крайне затратным, потому злоупотребление им приведёт к вашему увольнению.  Передача сооб
Почему бы в русской локализации не избавиться от фразы Центком и сделать просто ЦК? Очень уже режет глаз это слово. А ещё потеряли драму перед фразой "увольнению".

2024-08-15 12:21 UTC, Chip11-n commented on code/game/machinery/computer/communications.dm
> +				var/input = sanitize(input(usr, "Передайте оповещение Центкому через квантовую связь. Этот процесс является крайне затратным, потому злоупотребление им приведёт к вашему... увольнению. Передача с
```suggestion
				var/input = sanitize(input(usr, "Передайте оповещение Центкому через квантовую связь. Этот процесс является крайне затратным, потому злоупотребление им приведёт к вашему... списанию. Передача сообщения не гарантирует ответ. Между сообщениями есть задержка в 30 секунд, постарайтесь написать развёрнуто, полно и лаконично.", "Чтобы отменить, отправьте пустое сообщение.", ""))
```
Может так будет лучше?

2024-08-15 12:21 UTC, Chip11-n commented on code/game/machinery/computer/communications.dm
> +					to_chat(usr, "<span class='warning'>Обработка информации. Ожидайте.</span>")
Не разобранный коммент

2024-08-15 12:21 UTC, Chip11-n commented on code/game/machinery/computer/communications.dm
> +				var/input = sanitize(input(usr, "Передайте оповещение \[НЕИЗВЕСТНЫМ\] через блюспейс-связь.  Этот процесс является крайне затратным, потому злоупотребление им приведёт к вашему увольнению. Переда
Не коррелируется с сообщением выше, и тут такие же вопросы. Оповещение? Блюспейс-связь? Потеряна шутка-угроза и т.д.

2024-08-15 12:21 UTC, Chip11-n commented on code/game/machinery/computer/communications.dm
> +				dat += "<BR><A HREF='?src=\ref[src];operation=status'>Установить статус дисплея</A>"
Статус дисплея? Одного? Именно статус самого дисплея, или статусного дисплея?

2024-08-15 12:21 UTC, Chip11-n commented on code/game/machinery/computer/communications.dm
>  				return
Чуть выше непереведено

2024-08-15 12:21 UTC, Chip11-n commented on code/game/machinery/computer/communications.dm
> +				dat += "<BR><A HREF='?src=\ref[src];operation=ai-callshuttle'>Вызвать аварийный шаттл</A>"
Для консистенции уточняю. Шаттл аварийный или экстренный? Или решили в разных местах по разному?

2024-08-15 12:21 UTC, Chip11-n commented on code/game/machinery/computer/communications.dm
> +		to_chat(user, "Шаттл находится на дозаправке. Пожалуйста, подождите еще [round((6000-world.time)/600)] минут до повторного вызова.")
Тут то ли не доделали, то ли ещё что. В любом случе `Подождите ещё 1 минут до...`

2024-08-16 10:36 UTC, Chip11-n commented on code/game/machinery/computer/communications.dm
> +				var/input = sanitize(input(usr, "Передайте оповещение Центкому через квантовую связь. Этот процесс является крайне затратным, потому злоупотребление им приведёт к вашему... увольнению. Передача с
Говорится не только об увольнении, ведь не просто так ставится троеточие. А списание потому, что можно расценить и как увольнение, и как ликвидацию. В общем, как хотите.

2024-08-16 10:36 UTC, Chip11-n commented on code/game/machinery/computer/communications.dm
> +		to_chat(user, "Шаттл находится на дозаправке. Пожалуйста, подождите еще [round((6000-world.time)/600)] минут до повторного вызова.")
Я тебя сейчас сожру. 
`pluralize_russian(minute, "минута", "минуты", "минут")`

2024-08-16 10:36 UTC, Chip11-n commented on code/game/machinery/computer/communications.dm
> +						dat += "<BR><A HREF='?src=\ref[src];operation=callshuttle'>Вызвать экстренный шаттл</A>"
Шаттл аварийный или экстренный? Или решили в разных местах по разному?

2024-08-16 10:36 UTC, Chip11-n commented on code/game/machinery/computer/communications.dm
> +					to_chat(usr, "<span class='warning'>Блюспейс-передатчик в состоянии перезагрузки. Ожидайте.</span>")
@AzzyDreemurr13 
В одном месте решили, в другом оставили.
Строка 258. Это одно и то же сообщение.

2024-08-16 10:36 UTC, Chip11-n commented on code/game/machinery/computer/communications.dm
>  				return
Да, именно так

2024-09-24 10:01 UTC, KIBORG04 commented on code/game/machinery/alarm.dm
> +			to_chat(user, "Маленький индикатор указывает об активированом коде [msg].")
```suggestion
			to_chat(user, "Маленький индикатор указывает об активированном коде [msg].")
```

2024-09-24 10:42 UTC, maleyvich commented on code/game/machinery/computer/communications.dm
> +		to_chat(user, "Шаттл находится на дозаправке. Пожалуйста, подождите еще [round((6000-world.time)/600)] минут до повторного вызова.")
```suggestion
		to_chat(user, "Шаттл находится на дозаправке. Пожалуйста, подождите еще [round((6000-world.time)/600)] [pluralize_russian(minute, "минута", "минуты", "минут")] до повторного вызова.")
```

2024-09-24 10:42 UTC, maleyvich commented on code/game/machinery/computer/communications.dm
> +			to_chat(user, "Шаттл находится на дозаправке. Пожалуйста, подождите еще [round((54000-world.time)/600)] минут до повторного вызова.")//may need to change "/600"
```suggestion
			to_chat(user, "Шаттл находится на дозаправке. Пожалуйста, подождите еще [round((54000-world.time)/600)] [pluralize_russian(minute, "минута", "минуты", "минут")] до повторного вызова.")//may need to change "/600"
```

2024-09-24 10:54 UTC, maleyvich commented on code/game/machinery/computer/communications.dm
> +						dat += "<BR><A HREF='?src=\ref[src];operation=callshuttle'>Вызвать экстренный шаттл</A>"
пофикшено

2024-09-24 10:54 UTC, maleyvich commented on code/game/machinery/alarm.dm
> +
оставлю открытым на всякий случай

2024-09-24 10:56 UTC, maleyvich commented on code/game/machinery/computer/communications.dm
>  				return
всё

2024-09-24 10:56 UTC, maleyvich commented
вроде бы всё готово можно смотреть

2024-10-19 20:20 UTC, Pivo24 approved these changes

2024-10-19 20:20 UTC, Pivo24 commented on code/__DEFINES/misc.dm
> +#define SEC_LEVEL_GREEN	1
Меня смущает лишь смена дефайнов, которая, по идее, с переводом не должна иметь никаких отношений

2024-10-20 09:04 UTC, AmnyamNyam requested changes
Дорабатывать надо, однако проверку сделал навскидку. Относительно все норм.

2024-10-20 09:04 UTC, AmnyamNyam commented on code/game/machinery/computer/communications.dm
> +			var/datum/browser/popup = new(user, "communications", "Консоль коммуникаций", 400, 500)
Вещи нужно называть правильно, дабы не искажать возможный дальнейший смысл. Это техническая часть.

2024-10-20 09:04 UTC, AmnyamNyam commented on code/game/machinery/computer/communications.dm
> +			var/datum/browser/popup = new(user, "communications", "Консоль коммуникаций", 400, 500)
```suggestion
			var/datum/browser/popup = new(user, "communications", "Коммуникационная консоль", 400, 500)
```

ИЛИ ЖЕ

```suggestion
			var/datum/browser/popup = new(user, "communications", "Консоль связи", 400, 500)
```

2024-10-20 09:32 UTC, Pivo24 approved these changes

2024-10-20 10:02 UTC, AmnyamNyam requested changes

2024-10-20 10:02 UTC, AmnyamNyam commented on code/game/machinery/computer/communications.dm
> +				var/input = sanitize(input(usr, "Передайте оповещение \[НЕИЗВЕСТНЫМ\] через блюспейс-связь.  Этот процесс является крайне затратным, потому злоупотребление им приведёт к вашему увольнению. Переда
Мы работаем на чуть ли не галактическую корпорацию и чтобы сохранить "корпоративный дух", то у нас не увольняют, а расторгают с нами контракт. Это так же оставляет холодную нотку после себя, ибо мы не знаем, что они этим имеют ввиду. Может просто уволят, а может унесут и ликвидируют, ибо это ЕБАТЬ-КОПАТЬ КАКАЯ ДОРОГАЯ ТЕХНОЛОГИЯ, А ТЫ УТЫРОК ТРАТИШЬ НАШИ МИЛЛИОНЫ.

2024-10-20 10:02 UTC, AmnyamNyam commented on code/game/machinery/computer/communications.dm
> +				var/input = sanitize(input(usr, "Передайте оповещение \[НЕИЗВЕСТНЫМ\] через блюспейс-связь.  Этот процесс является крайне затратным, потому злоупотребление им приведёт к вашему увольнению. Переда
Вместе с этим по поводу квантовой системы связи - ищи обсуждение в дисе.

2024-10-20 10:27 UTC, AmnyamNyam requested changes

2024-10-20 10:27 UTC, AmnyamNyam commented on code/game/machinery/computer/communications.dm
> +					to_chat(usr, "<span class='warning'>Рекалибровка систем связи. Пожалуйста подождите.</span>")
```suggestion
					to_chat(usr, "<span class='warning'>Рекалибровка систем связи. Пожалуйста, подождите.</span>")
```

2024-10-20 10:27 UTC, AmnyamNyam commented on code/game/machinery/computer/communications.dm
> +					to_chat(usr, "<span class='warning'>Рекалибровка систем связи. Пожалуйста подождите.</span>")
Запятую потерял, ы.

2024-10-20 10:27 UTC, AmnyamNyam commented on code/game/machinery/computer/communications.dm
> +		dat += "<B>Аварийный шаттл</B>\n<BR>\nПримерное время прибытия: [shuttleeta2text()]<BR>"
```suggestion
		dat += "<B>Аварийный шаттл</B>\n<BR>\nРасчетное время прибытия [shuttleeta2text()]<BR>"
```

ETA – Estimated time of arrival (Расчетное время прибытия)

Можно, МОЖЕТ БЫТЬ, сохранить сокращение

```suggestion
		dat += "<B>Аварийный шаттл</B>\n<BR>\nРВП: [shuttleeta2text()]<BR>"
```

Но мне кажется, что это тупо.

2024-10-20 10:27 UTC, AmnyamNyam commented on code/game/machinery/computer/communications.dm
> +			dat += "<A HREF='?src=\ref[src];operation=setstat;statdisp=shuttle'>Время до прибытия шаттла</A><BR>"
```suggestion
			dat += "<A HREF='?src=\ref[src];operation=setstat;statdisp=shuttle'>Расчетное время до прибытия шаттла</A><BR>"
```
Не уверен, что влезет...Можно и не править.

2024-10-20 10:27 UTC, AmnyamNyam commented on code/game/machinery/computer/communications.dm
> +			to_chat(user, "Шаттл находится на дозаправке. Пожалуйста, подождите еще [time_to_stay] [pluralize_russian(time_to_stay, "минута", "минуты", "минут")] до повторного вызова.")//may need to change "/
Подождите еще N **минута**?

2024-10-20 12:43 UTC, AmnyamNyam approved these changes

2024-10-20 17:13 UTC, merged