Fix tables
TauCetiStation/TauCetiClassic pull request #13125
Opened 2024-06-01 14:56 UTC by AzzyDreemurr13

## Описание изменений
Починка крафта укрепленных столов из стекла и металла сломанные ПРом: https://github.com/TauCetiStation/TauCetiClassic/pull/13076
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/74739991/4767c7e4-4772-431c-985d-dfe76d2f97f6)

## Почему и что этот ПР улучшит
Resolves https://github.com/TauCetiStation/TauCetiClassic/issues/13124
Resolves https://github.com/TauCetiStation/TauCetiClassic/issues/13115
## Авторство
Я 

## Чеинжлог
:cl:
 - bugfix: Починка крафта укрепленных столов из стекла и металла

2024-06-01 14:56 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2024-06-04 07:43 UTC, AirBlack requested changes

2024-06-04 07:43 UTC, AirBlack commented on code/game/objects/items/weapons/table_rack_parts.dm
> +
Не логично стало. Сборка усиленного стеклянного стола крафтом из усиленного стекла стоит 2 листа стекла и 2 арматурины. Крафт такого же стола путем усиления обычного стеклянного стола стоит 2 стекла и 4 арматурины. Разница в две арматурины. Поменяй пару строк ниже на R.use(2) чтобы было логично.

2024-06-04 07:45 UTC, AirBlack commented on code/game/objects/items/weapons/table_rack_parts.dm
> +
И то что обычный металлический стол требует 4 арматурины это пофиг, т.к. степень усиления у металлического усилленного по сравнению с обычным намного выше чем у стеклянного усиленного по сравнению с обычным. Тот же стеклянный усиленный вроде можно перевернуть и сломать, но нельзя сломать тем, что ты встал. А усиленный металл нельзя ни перевернуть ни сломать нормально, да и любой вес выдерживает, так что логично, что металлическому потребуется больше арматурин.

2024-06-04 07:48 UTC, AirBlack commented on code/game/objects/items/weapons/table_rack_parts.dm
> +
И при таком уровне занятости и откладывания дел ты метишь в админы? Мда

2024-06-04 07:58 UTC, AirBlack commented on code/game/objects/items/weapons/table_rack_parts.dm
> +
Это критический баг, стоппер геймплея, я не зайду на сервере, пока не буду убежден, что усиленные столы собираются не из стекла, и оба варианта крафта усиленного стеклянного стола будут одинаковыми в плане количества ресурсов. Видно сразу твою классную манеру "распределения задач по приоритету", никакого уважения к игрокам, к тикетам явно будешь относиться как не к обращениям настоящих людей, игроков, пытающихся получить удовольствие от игры и требующих помощи от администрации, а как к набору задач из бэклога, к которым будешь подходить только по своим понятиям абстрактных приоритетов, какой тикет интересен такой и возьму. Видно вот это вот обесчеловечивание людей и их проблем, не понятно правда, зачем тебе в админы

2024-06-04 09:12 UTC, AirBlack commented on code/game/objects/items/weapons/table_rack_parts.dm
> +
Вот, насмешки над проблемами игроков, вот так вот ты себя в педалях и будешь вести. Нет, спасибо

2024-06-05 08:31 UTC, AirBlack commented on code/game/objects/items/weapons/table_rack_parts.dm
> +
Ты добавил крафт укреп стеклянному столу через крафт укреп стекла, но не убрал крафт укреп стеклянного стола через усиление обычного стеклянного стола арматурой, если у нас два варианта крафта, то логично было бы, еслиб оба варианта требовали одинаковое кол-во ресурсов, однако первый вариант требует 2 обычного стекла и 2 арматурины, а второй вариант требует 2 обычного стекла и 4 арматурины, разница в двух арматуринах, теперь понял?

2024-06-05 08:45 UTC, volas commented on code/game/objects/items/stacks/sheets/glass.dm
> -	new/datum/stack_recipe("table parts", /obj/item/weapon/table_parts/reinforced, 2),
Я думаю, я хотел добавить рецепт в plasteel_recipes, и просто промазал. У нас все столы делаются через крафт меню стака, потому я не видел смысла делать крафт именно укрепленного как-то по другому.

2024-06-05 08:47 UTC, AirBlack commented on code/game/objects/items/stacks/sheets/glass.dm
> -	new/datum/stack_recipe("table parts", /obj/item/weapon/table_parts/reinforced, 2),
Пласталь слишком дорогая, чтобы тратить ее на какой-то там укреп стол. Крафт арматуринами имеет смысл

2024-06-05 09:32 UTC, AirBlack commented on code/game/objects/items/weapons/table_rack_parts.dm
> +
но тогда будет непостоянность между крафтами обычного укреп стола и стеклянного, обычный крафтиться арматурой по столу, а усиленный из стак меню укреп стекла, консистенси сломаеца

2024-06-05 12:36 UTC, AirBlack commented on code/game/objects/items/weapons/table_rack_parts.dm
> +
You need at least two rods to do this

2024-06-05 12:38 UTC, AirBlack approved these changes
Класс норм

2024-06-08 14:52 UTC, volas commented
я призываю потом кого-то отдельно это изменить в пользу всех рецептов со стаков. Когда все столы делаются через стак, это странно, и вообще от костылей в атакбай надо уходить

2024-06-08 14:52 UTC, merged