Don't Be a Menace to Asteroid While You're without Homies. Asteroid Fauna Update.
TauCetiStation/TauCetiClassic pull request #13133
Opened 2024-06-03 15:37 UTC by Deahaka

## Описание изменений
**Проект "В эту игру могут играть двое".**

В самых опасных участках астероида (https://github.com/TauCetiStation/TauCetiClassic/pull/12684) теперь встречаются более сильные версии фауны:
1. Древний Голиаф, парализующий жертв тентаклями
2. Кристалический Василиск, стреляющий едкой жгучей кислотой
3. Ненасытный Золотой Слизень, ведущий охоту на ваши ресурсы
4. Пылевой Повелитель Роя, досаждающий шахтёрам укреплёнными отростками
5. Разновидность шахтёрского дрона

Подсказки: щупальцы на жертвах голиафа можно срезать; освободиться от щупалец можно и самостоятельно при сильном сопротивлении.

*https://github.com/TauCetiStation/TauCetiClassic/pull/13092 не должен конфликтовать, если не будет изменений.*
## Почему и что этот ПР улучшит
Испытание для желающих поиграть в рискованную добычу большого колличества ресурсов с вкраплениями аспекта командной игры для шахтёров.
## Авторство
спрайты с [TG](https://github.com/tgstation/tgstation) и с [Авроры](https://github.com/Aurorastation/Aurora.3)

## Чеинжлог
:cl: Deahaka
- add: В опасных участках астероида просыпается трудноигнорируемая живность.

2024-06-03 15:37 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2024-06-03 15:54 UTC, maleyvich commented
апнутые версии хайвлорда и голдграба вообще не похожи на свои изначальные версии, голдграб так ваще реально какая-то ЛИЧИНКА

у хайвлорда просто какойт поток мыслей был у спрайтера когда делал это

2024-06-03 17:32 UTC, Oz1Es commented
согласен с аззи, нужен кнут и пряник, а не кнут и фауна

2024-06-03 17:37 UTC, Deahaka commented
Не интересуют файты с фауной - эвейдите область. В чате сообщение выводится что вход в опасную зону, а также вуаль появляется на экране, значит туда не ходите.

2024-06-03 20:39 UTC, Kiromaka commented
> Ты буквально хочешь лаваленд в космосе, но забываешь, что и там если ты лезишь на более опасную зону, ждёт соответствующая награда той зоне

Лаваленд это одна из самых интересных вещей в сс13. Его отсутствие у нас удручает, но я согласен - это не лаваленд.


Лаваленд - это набор трудных, иногда очень трудных испытаний.. но они всегда с наградой или с интересной механикой. 

- Мегафауна - очень интересные враги, с ними весело драться, но даже так: смотря на жвачку, который по моему мнению самый интересный босс, можно понять, что его никто не убивает, потому что за него не получаешь ничего полезного. 

-  Пазловые дереликты  - всегда имеют за собой награду, и их тоже интересно проходить, хотя после раза 3 уже скучно.

- Даже простых мобов убивают ради ресурсов, никто бы не обращал внимания на любого моба на лаве если они бы не дропали что-то полезное, будь то реген коры, части брони или руду.

А дахака накатал сложных мобов с лаваленда - просто так. Может мы не понимаем гения, и после этого пра он добавит смысл этим мобам.

2024-06-03 20:47 UTC, simb11 commented
да что астероид что этот ваш лаваленд унылая и аутичная херня
лучше б вообще удалили шахту и перенесли деятельность ксеноархеологов и шахтёров в пределы станции

2024-06-04 07:35 UTC, AirBlack commented
на сервере 0 людей, в шахтерах вообще минус пять людей, добавляем ПР на то, что если одинокий шахтер зайдет то он умрет и выйдет. По моему хороший ПР отличный, добавляет разнообразия, добавляет сложности для большей увлекательности профы и бОльшие риски в плане добычи ресурсов, а так же добавляем интерес развитию станции в виду дефицита ресурсов в среднестатистическом случае мертвого шахтера. Мне кажется надо мержить сразу без тест мержа и ревью, все отлично уже и так

2024-06-04 07:48 UTC, Deahaka commented
Онлайн подняли с колен по выходным, всё будет хорошо

2024-06-04 07:50 UTC, AirBlack commented
> Онлайн подняли с колен по выходным, всё будет хорошо

а это уже плохо, значит с билдом что-то не так, раз всякие тупые там игроки играют в нашу высокоинтеллектуальную игру. Надо срочно повышать интеллектуальную нагрузку дабы оставить только самых умных людей на сервере с айсикью 250+. Ментейнеры, займитесь пожалуйста, а то мне обидно играть на сервере, который считается ШИРПОТРЕБОМ и на котором играют обычные всякие нормисы с айсикью меньше 150, это меня оскорбляет

2024-06-04 16:21 UTC, Oz1Es commented
> Онлайн подняли с колен по выходным, всё будет хорошо

похоже только это и заботит дехаку, реально недопонятый гений с импостерами

2024-06-08 14:27 UTC, volas commented on code/modules/mob/mob_defines.dm
> +	var/mutable_appearance/tentacle_overlay
мне кажется, выглядит как что-то, что можно вынести в компоненту

2024-06-08 14:35 UTC, volas commented
Мне всё еще не нравится, что вместо респрайта/апдейта мобов (эти мобы не новый тип, они более качественный апгрейд и респрайт текущих, голиаф и червь как минимум), это вдруг заливается отдельным типом.

Если рассматривать всерьез, мы можем туда что-то еще положить в опасную зону, не отбирая в других местах, чтоб это имела смысл? Может там гору телекристалов в центр, я не знаю. И я бы тогда еще может пересмотрел/переделал световой фильтр.

2024-06-09 14:19 UTC, Deahaka commented
Могу положить в самих мобов что-нибудь интересное. Например, как на ТГ: бронепластину с голиафа, алмазы с василиска, лечебный артефакт с хайвлорда, ценные для РнД платы в дрона. Подходит?

2024-06-09 14:20 UTC, maleyvich commented
> Могу положить в самих мобов что-нибудь интересное. Например, как на ТГ: бронепластину с голиафа, алмазы с василиска, лечебный артефакт с хайвлорда, ценные для РнД платы в дрона. Подходит?

это троллинг какой-то?

2024-06-09 14:24 UTC, Deahaka commented
> Мне всё еще не нравится, что вместо респрайта/апдейта мобов (эти мобы не новый тип, они более качественный апгрейд и респрайт текущих, голиаф и червь как минимум), это вдруг заливается отдельным типом.

Эти спрайты просто плейсхолдер. Если кто-то захочет поменять, то пусть свапнет их местами, чтобы олдскульные бегали в центральной области, а хайповые снаружи. Я не художник, я не нарисую лучше чем то, что есть.

2024-06-19 11:34 UTC, Tap0r commented
> Теперь обычные мобы это респрайтнутые с ТГ, а внутри астероида староспрайченные. Старый голиаф не вписался и пришлось заменить.

и нахуя эта рокировка нужна

2024-06-19 12:01 UTC, maleyvich requested changes

2024-07-03 12:05 UTC, Deahaka commented
2 weeks more

2024-07-09 15:33 UTC, LudwigVonChesterfield commented on code/_onclick/hud/alert.dm
> +	desc = "You've paralysed. Considering how helpless you are."
```suggestion
	desc = "You've paralysed. Consider how helpless you are."
```

2024-07-09 15:34 UTC, LudwigVonChesterfield commented on code/_onclick/hud/alert.dm
> +	desc = "You've paralysed. Considering how helpless you are."
можно ещё добавить "Wish you had a friend with you?"

2024-07-09 15:35 UTC, LudwigVonChesterfield commented on code/modules/mob/mob_defines.dm
> +	var/mutable_appearance/tentacle_overlay
Может в статус эффект который эта тентакля накладывает.

2024-07-22 15:47 UTC, LudwigVonChesterfield commented
Кто-нибудь поясните какие подводные хотя бы просто потестить че будет?

2024-07-22 15:48 UTC, KIBORG04 commented
Я в игру не захожу, чтобы оценить

2024-07-22 15:49 UTC, LudwigVonChesterfield commented on code/modules/mining/mine_areas.dm
> +	to_chat(A, "<span class='warning'>Suspension of particles obstructs the view. This area are more dangerous. Wish you had a friend with you?</span>")
мне кажется правда такая tongue-in-cheek подсказка лучше подошла бы эффекту потому-что ты бы её видел только навевшись на него. а так будет каждый раз писаться в чатик.

поэтому надо чтобы она больше навеивала атмосферу чем прямо таки говорила.

2024-07-26 10:38 UTC, nasendd commented
Я очень часто играю на шахтере и хочу оставить фидбек по этому ПР.

_это пиздец_

В опасной части астероида теперь можно встретить хилого и невидимого древнего голиафа. По опасной части астероида спокойно идут два шахтера, но голиаф из невидимости хватает их в ВЕЧНЫЙ стан и выводит из игры. Конец.

Новые мобы, которых спавнит новый хайвлорд теперь умирают с двух выстрелов кинетиком, а с самого нового хайвлорда падает новая реджувующая сфера, которая видна только гостам. 

Моб может заспавниться у тебя за спиной и ты еще даже ничего не поймешь, как тебя уже забивают на смерть новый басилиск и древний голиаф. 

С новой фауны, кроме хайвлорда, ничего не падает…

Играть на шахте более НЕВОЗМОЖНО.

2024-07-26 12:02 UTC, volas commented
снял с тм, как выяснилось много проблем и баги

2024-07-26 16:06 UTC, 4310V343k commented on code/modules/mining/mine_areas.dm
> +	to_chat(A, "<span class='warning'>Suspension of particles obstructs the view. This area are more dangerous. Wish you had a friend with you?</span>")
```suggestion
	to_chat(A, "<span class='warning'>Suspension of particles obstructs the view. This area feels more dangerous. Good thing you brought a friend, right?</span>")
```

2024-07-26 18:32 UTC, Deahaka commented
Вернусь когда буду играть в игру

2024-07-26 18:32 UTC, closed without merging