Exosuit DNA lock device
TauCetiStation/TauCetiClassic pull request #13190
Opened 2024-06-22 15:39 UTC by AirBlack

## Описание изменений
Убрал по дефолту из всех рабочих мехов DNA lock, теперь чтобы лочить через ДНК надо печатать в робототехнике ДНК сканер для мехов. В мехах ОБР и синдиката по дефолту девайс присутствует
Также добавил требования доступа для дефолтного меха переработчиков и выключил ему по дефолту maint protocols и id upload panel.

Сделал залезание в мех через ду афтер. Добавил вытаскивание девайсов(ДНК сканер и трекер позиции) через откручивание их после откручивания батарейки.

## Почему и что этот ПР улучшит
Меня заебали переработчики блокирующие рипли на ДНК лок. Калеб козел.
## Авторство
AirBlack - код идея и большие сочные яйца

## Чеинжлог

:cl:
 - tweak: Убран ДНК лок из мехов по дефолту в отдельный печатаемый ДНК сканер

2024-06-22 15:39 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2024-06-22 16:09 UTC, Deahaka commented
Поставил лайк, а потом перечитал и там остаётся днк лок на нюкерских мехов. Дизлайк, отписка

2024-06-22 16:11 UTC, AirBlack commented
я думал будет смешно убрать им днк лок чтоб мехи можно было спиздить но подумал что меня обольют ведром говна. обольют просто так в смысле, а не за днк лок

2024-06-22 19:53 UTC, Fluffy-510 commented
Мне кажется, добавление требования доступа к меху переработчиков лишне

2024-06-23 09:57 UTC, AirBlack commented
> Мне кажется, добавление требования доступа к меху переработчиков лишне

иди нафиг калеб какойто там который спиздил мех вчера, сдох взрывным имплантом и залочил рипли, когда робототехников не было и переработка встала

2024-07-03 13:29 UTC, KIBORG04 commented on code/game/mecha/mecha.dm
> +	return 0
```suggestion
	if(do_after(usr, delay, target = src))
		return TRUE
	return FALSE
```

2024-07-03 13:34 UTC, KIBORG04 commented on maps/centcom/centcom.dmm
> +/obj/mecha/combat/gygax/ultra{
Сделай лучше это отдельным тайпом, типа /obj/mecha/combat/gygax/ultra/with_dna, /obj/mecha/working/ripley/firefighter/with_dna, /obj/mecha/medical/odysseus/with_dna.

Мне же не нужно тебе объяснять, почему менять объекты через мап эдитор кринж?

2024-07-03 13:38 UTC, KIBORG04 commented on code/game/mecha/mecha.dm
> +								tracking.forceMove(src.loc)
```suggestion
			if(cell)
				state=3
				to_chat(user, "You screw the cell in place")
			else
				var/list/actions = list()
				var/obj/item/mecha_parts/mecha_tracking/tracking
				if(dna_lockable)
					actions += "Exosuit DNA Scanner"
				for(var/obj/item/mecha_parts/mecha_tracking/found_tracking in src.contents)
					actions += "Exosuit Tracker"
					tracking = found_tracking
					break

				if(actions.len > 0)
					var/uloc = user.loc
					var/mloc = loc
					var/choice = tgui_input_list(user, "Pick what to unscrew.", "Unscrew part", actions, 5 SECONDS)
					if(user.loc != uloc || loc != mloc)
						return
					switch(choice)
						if("Exosuit DNA Scanner")
							if(dna_lockable)
								to_chat(user, "You unscrew DNA scanner from [name]")
								dna_lockable = FALSE
								dna = null
								new /obj/item/mecha_parts/dna_scanner(src.loc)
						if("Exosuit Tracker")
							if(tracking && tracking.loc == src)
								to_chat(user, "You unscrew [tracking.name] from [name]")
								tracking.forceMove(src.loc)
```

2024-07-03 13:38 UTC, KIBORG04 commented on code/game/mecha/mecha.dm
> +		qdel(W)
А нельзя как-то внутри мехи хранить этот девайс? А то удалять и заново спавнить один и тот же объект звучит кринжово

2024-07-03 13:43 UTC, Chip11-n commented on code/game/mecha/mecha.dm
> +		qdel(W)
За то не надо спавнить для раундстартовых. Такой принцип сейчас у плат в шлюзах.

2024-07-03 13:51 UTC, KIBORG04 commented on code/game/mecha/mecha.dm
> +					break
```suggestion
				var/obj/item/mecha_parts/mecha_tracking/tracking = locate() in contents
				if(tracking)
					actions += "Exosuit Tracker"
				if(dna_lockable)
					actions += "Exosuit DNA Scanner"
```
Лайфхак

2024-07-03 13:53 UTC, KIBORG04 commented on code/game/mecha/mecha.dm
> +						return
```suggestion
					var/choice = tgui_input_list(user, "Pick what to unscrew.", "Unscrew part", actions, 5 SECONDS)
					if(!choice || !Adjacent(user))
						return
```
Думаю так лучше

2024-07-03 13:54 UTC, KIBORG04 commented on code/game/mecha/mecha.dm
> +			to_chat(user, "The [src.name] already has DNA scanner installed.")
```suggestion
			to_chat(user, "The [name] already has DNA scanner installed.")
```

2024-07-03 13:55 UTC, KIBORG04 requested changes
А так, типа по мелочи изменить. но меня только немного напрягает, что ДНК Лок при установке в меху куделится, а при вытаскивании заново инстанциируется, но вроде пофиг

2024-07-03 14:45 UTC, AirBlack commented on code/game/mecha/mecha.dm
> +		qdel(W)
не согласен хранить внутри, напишу отдельное хранение если только вешать логику на сам итем, а для этого надо еще тогда аналоги написать с другим поведением, типа допустим тот который может несколько хранить например и всякая такая фигня, но у меня идей нет так что пусть будет итемом

2024-07-03 16:43 UTC, KIBORG04 commented on code/game/mecha/mecha.dm
> +					break
```suggestion
				if(tracking)
					actions += "Exosuit Tracker"
```
Эээ, не понял прикола

2024-07-03 16:45 UTC, merged

2024-07-04 02:31 UTC, AirBlack commented on code/game/mecha/mecha.dm
> +					break
Бля тупанул поторопился