Кислотная турель для королевы ксеноморфов
TauCetiStation/TauCetiClassic pull request #13235
Opened 2024-07-03 07:54 UTC by maleyvich

## Описание изменений
Добавлена кислотная турель, которую может поставить только королева ксеноморфов за 400 плазмы. Турель довольно сильна в начале, поэтому КД на её установку - большое. 
## Почему и что этот ПР улучшит
больше шансов у алиенов в начале раунда, когда их могут просто запушить СБ. турель сможет служить так и в защите хостов в нестах, так и отвлекать атакующих во время боя
## Авторство
закодил я, спрайты взяты с [тгмсов](https://github.com/tgstation/TerraGov-Marine-Corps) (как и затея)

## Чеинжлог
:cl: maleyvich
- rscadd[link]: Королева ксеноморфов получила возможность ставить турель.

2024-07-03 07:54 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2024-07-03 08:08 UTC, maleyvich commented
ладно я надеюсь всё нормально

2024-07-03 08:11 UTC, TauKitty commented
Этот запрос на слияние был упомянут в **Tau Ceti Station Forum**. Там могут быть соответствующие подробности:

https://forum.taucetistation.org/t/obsuzhdenie-pra-kislotnye-tureli/43160/1

2024-07-03 08:23 UTC, AirBlack commented
мертвую лошадь палкой бьешь ей богу

2024-07-03 09:59 UTC, maleyvich commented on code/modules/mob/living/simple_animal/hostile/alien.dm
> +	desc = "Склизкое строение, выпускающее из себя смертельные кислотные плевки."
```suggestion
	desc = "Склизкое строение, выпускающее из себя оглушающие кислотные плевки."
```

2024-07-03 12:53 UTC, KIBORG04 commented on code/modules/mob/living/living.dm
> +//Show an image of the wielded weapon over the person who got dunked.
```suggestion
	//Show an image of the wielded weapon over the person who got dunked.
```
зачем..

2024-07-03 12:53 UTC, KIBORG04 commented on code/modules/mob/living/living.dm
> +	return TRUE
Почему это у ливингов, а не хостайлов

2024-07-03 12:54 UTC, KIBORG04 commented on code/modules/mob/living/simple_animal/hostile/alien.dm
> +
```suggestion
```

2024-07-03 12:55 UTC, KIBORG04 commented on code/modules/mob/living/simple_animal/hostile/alien.dm
> +	OpenFire(A)
```suggestion
```
Когда же ты прочтешь про наследование в ООП?

2024-07-03 12:56 UTC, KIBORG04 commented on code/modules/mob/living/simple_animal/hostile/alien.dm
> +/mob/living/simple_animal/hostile/pylon/xenomorph_turret
На твоём месте я бы не наследовался от пилона культа, так как там есть КУЛЬТО-механ, который не должен быть у аленей. 

Ты можешь сделать абстрактный класс с базовым механом пилонов, что он типа стоит `/mob/living/simple_animal/hostile/pylon`, потом `/mob/living/simple_animal/hostile/pylon/cult` и `/mob/living/simple_animal/hostile/pylon/aliens`.

2024-07-03 12:57 UTC, KIBORG04 commented on code/modules/mob/living/simple_animal/hostile/alien.dm
> +	canmove = FALSE
Я так понял, тут куча скопипасщенных лишний переменных от культовского пилона, почисти копипасту

2024-07-03 12:57 UTC, KIBORG04 commented on code/modules/mob/living/simple_animal/hostile/hostile.dm
> -
Верни

2024-07-03 12:58 UTC, KIBORG04 requested changes
В дискорде меня пингуй только по когда ОЧЕНЬ тяжело будет, остальных когда хош

2024-07-03 13:23 UTC, maleyvich commented on code/modules/mob/living/simple_animal/hostile/alien.dm
> +	friends = global.alien_list
и без этого не стреляет в ксеносов (протестчено) так что удаляю

2024-07-03 13:26 UTC, maleyvich commented on code/modules/mob/living/simple_animal/hostile/alien.dm
> +/mob/living/simple_animal/hostile/pylon/xenomorph_turret
никаких особых проблем не заметил, культистов всё также атакует

2024-07-03 13:30 UTC, maleyvich commented on code/modules/mob/living/simple_animal/hostile/hostile.dm
> -
зачем но ладно

2024-07-03 13:30 UTC, maleyvich commented on code/modules/mob/living/living.dm
> +	return TRUE
вернул хостайлам

2024-07-03 13:30 UTC, maleyvich commented on code/modules/mob/living/simple_animal/hostile/alien.dm
> +	canmove = FALSE
почистил

2024-07-04 07:08 UTC, maleyvich commented on code/modules/mob/living/simple_animal/hostile/alien.dm
> +/mob/living/simple_animal/hostile/pylon/xenomorph_turret
лан вроде бы сделал

2024-07-14 18:24 UTC, maleyvich commented
эм вроде бы все нормально

2024-07-17 18:06 UTC, Soxxxela commented
Мне кажется ксенов нужно дебафать, а не наоборот. СБ и так трудно запушить ксенов из-за крика квины и постоянной кислоты.

2024-07-18 09:05 UTC, WatlerJe approved these changes

2024-07-20 14:26 UTC, KIBORG04 commented on code/modules/mob/living/simple_animal/pylon.dm
> +	qdel(src)
Это фича культовского пилона, тут не надо

2024-07-20 14:27 UTC, KIBORG04 commented on code/modules/mob/living/simple_animal/pylon.dm
> +	friends = null
зач

2024-07-20 14:28 UTC, KIBORG04 commented on code/modules/mob/living/simple_animal/pylon.dm
> +	return
Удали

2024-07-20 14:33 UTC, maleyvich commented on code/modules/mob/living/simple_animal/pylon.dm
> +	qdel(src)
вернул культу

2024-07-20 14:33 UTC, maleyvich commented on code/modules/mob/living/simple_animal/pylon.dm
> +	friends = null
убрал

2024-07-20 14:34 UTC, maleyvich commented on code/modules/mob/living/simple_animal/pylon.dm
> +	return
удалил

2024-07-20 14:37 UTC, KIBORG04 commented on code/modules/mob/living/simple_animal/hostile/hostile.dm
> +
че не убрал

2024-07-20 14:38 UTC, KIBORG04 commented on code/modules/mob/living/simple_animal/pylon.dm
> +	var/timer
таймер тоже чисто культовская переменная

2024-07-20 14:38 UTC, KIBORG04 commented on code/modules/mob/living/simple_animal/pylon.dm
> +	faction = null
```suggestion
```
Тоже пофиг

2024-07-20 14:39 UTC, KIBORG04 commented on code/modules/mob/living/simple_animal/pylon.dm
> +	projectilesound = null
```suggestion
```
Тоже не надо нуллить

2024-07-20 14:39 UTC, KIBORG04 commented on code/modules/mob/living/simple_animal/pylon.dm
> +	return
Чисто культовский метод

2024-07-20 14:39 UTC, KIBORG04 commented on code/modules/mob/living/simple_animal/pylon.dm
> +	return
Тоже культовский

2024-07-20 14:46 UTC, maleyvich commented
вроде бы убил все что надо

2024-07-20 14:51 UTC, KIBORG04 commented on code/modules/mob/living/simple_animal/hostile/hostile.dm
> -
Верни

2024-07-20 14:54 UTC, KIBORG04 commented on code/modules/mob/living/simple_animal/hostile/hostile.dm
> -
Верни

2024-07-20 14:55 UTC, maleyvich commented on code/modules/mob/living/simple_animal/pylon.dm
> +	return
теперь точно нету

2024-07-20 14:55 UTC, maleyvich commented on code/modules/mob/living/simple_animal/hostile/hostile.dm
> -
щас верну

2024-07-20 14:56 UTC, maleyvich commented on code/modules/mob/living/simple_animal/hostile/hostile.dm
> -
вернул

2024-07-20 14:57 UTC, KIBORG04 reviewed
Лан, код сойдет, а идея хз

2024-07-20 14:59 UTC, KIBORG04 commented
@NinjaPikachuska Почему тебе не нравится?

2024-07-22 16:29 UTC, KIBORG04 commented on code/datums/spells/in_hand.dm
> +	neurotoxin
Че это

2024-07-22 16:29 UTC, KIBORG04 commented on code/datums/spells/in_hand.dm
> +	weaken = 1
Аэм. Мне кажется, доп эффекты не нужны.

2024-07-22 16:30 UTC, KIBORG04 reviewed
![image](https://github.com/user-attachments/assets/64165508-1609-40e3-8404-77ba5ee07b33)
У тебя 4 дира выбрано, видимо, случайно. Хз нормально это или нет, но поставить 1 дир, если можно

2024-07-22 16:31 UTC, maleyvich commented on code/datums/spells/in_hand.dm
> +	weaken = 1
стан не нужен???

2024-07-22 16:49 UTC, maleyvich commented on code/datums/spells/in_hand.dm
> +	neurotoxin
убрал ненужное

2024-07-22 16:49 UTC, maleyvich commented on code/datums/spells/in_hand.dm
> +	weaken = 1
никто так и не сказал нужен ли стан, но я думаю нужен

2024-07-23 07:25 UTC, maleyvich commented on code/datums/spells/in_hand.dm
> +	weaken = 1
ладно вернём если че

2024-07-23 16:19 UTC, maleyvich commented
мне предложили хорошую по моему мнению идею, вместо стана будет просто больно.

2024-07-24 06:27 UTC, volas approved these changes

2024-07-24 06:30 UTC, volas commented
ТМ-а тут не хватит, алиены редко и туррель тоже не каждый раз будут строить. Я склоняюсь к тому, чтобы смержить, посмотреть как оно будет в реальных условиях, и там по необходимости по фидбеку потвикать/удалить.

2024-07-25 04:08 UTC, volas commented
Как выше писал, мержу на побегать. Я вижу дизлайки, но по факту никто не отписывался и думаю это не объективно без теста в игре.

Если будут проблемы - просьба поднять вопрос отдельно.

2024-07-25 04:08 UTC, merged

2024-08-08 15:37 UTC, Risraivyn commented
Так и не понял куда фидбек по турели скидывать. Если кратко: Ни рыба, ни мясо. Долгое кд, огромная стоимость, Играя за квину, поставил штук 5, полезности вообще не ощутил. Поставил в коридоре, голая кукла просто пробежала мимо. Кпд как для постройки в 400 плазмы совсем не то.