old station update
TauCetiStation/TauCetiClassic pull request #13254
Opened 2024-07-04 18:06 UTC by simb11

## Описание изменений
Поменял много разных разностей на дереликте old station.dmm
Карта:
- В отсеки и переходы между разными частями станции добавлены милые стеклянные полы.
- Убраны аирлесс турфы.
- Турели перемещены таким образом, чтобы они не могли стрелять в людей внутри станции.
- Для доступа на склад и арсенал нужна карта капитана, которая лежит в логове ксеноморфов.
- Еган мк. 2 перемещён в логово ксеноморфов.
- По всей карте раскиданы книги повышающие скиллы.
- Убран халявный скафандр синдиката из разрушенного инженерного отсека
- В некоторые отсеки станции добавлены записки с лором.
- В разрушенный атмосферный отсек добавлен раздатчик труб.
- Подле крио теперь лежат самодельные бинты (тряпки).

Код:
- Изменены скиллы у выживших, они приближены к тем что имеют профки на станции.
- Добавлен всплывающий текст, в котором написана информация о персонаже и где он находится.
- Добавлены ХУД иконки для ИД карт выживших.
- Станция теперь имеет нормальное название!!!!!!! (КСН "Сизиф")

## Почему и что этот ПР улучшит
Много чего
Баланс - выжившие не смогут сразу же залутать весь дорогой лут и полететь на станцию. Они же не будут иметь огромного количества скиллов.
Фикс - станция имела техническое название, турели убивали людей внутри станции, на центральной станции вообще не было медикаментов (кроме тех с которыми спавнится медик), в некоторых местах были аирлесс турфы, у ИД карт не было ХУД иконок
Ну и просто сделал дереликт и связанное с ним красивее.
## Авторство

## Чеинжлог
:cl: Simbaka
- map[link]: Множество изменений на заброшенной станции с парочкой выживших.
- balance: Выжившие потеряли доступ к арсеналу на своём дереликте. Вместе с этим они лишились некоторых своих умений.
- add: Добавлены ХУД иконки для ИД карт выживших.
- tweak: Дереликт-заброшенная станция получила название - КСН "Сизиф".

2024-07-04 18:06 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2024-07-04 18:24 UTC, maleyvich reviewed
это абсолютно неважное мнение просто заметочки..

и было бы круто если у записочек была засохшая кровь или они сами были в ней!

2024-07-04 18:24 UTC, maleyvich commented on code/modules/paperwork/paper.dm
> +	info += "3.09.2221. На станцию попытался проникнуть раздвечик Синдиката. Турели нейтрализовали врага, его снаряжение было передано научному персоналу.<br>"
разведчик

2024-07-04 18:24 UTC, maleyvich commented on code/modules/paperwork/paper.dm
> +	info += "Похоже, это был не самый ценный кадр, раз его послали почти без оружия и в древнем как мир скафандре.<br>"
мне кажется что будет немного лучше так
```suggestion
	info += "Похоже, это был не самый ценный кадр, раз его послали почти без оружия, скафандр вообще старой модели.<br>"
```

2024-07-04 18:24 UTC, maleyvich commented on code/modules/paperwork/paper.dm
> +	info += "<i>Если на эту проклятую станцию попытались напасть, значит о ней кто-то да знает. Эвакуация это просто вопрос времени.</i>"
```suggestion
	info += "<i>Если на эту проклятую станцию попытались напасть, значит о ней кто-то да знает. Эвакуация - это просто вопрос времени.</i>"
```

2024-07-04 18:24 UTC, maleyvich commented on code/modules/paperwork/paper.dm
> +	info += "13.09.2221. Экипаж начинает замышлять что-то неладное. Некоторые считают, что всё что произошло на этой станции за последние две недели - один большой эксперимент НТ.<br>"
```suggestion
	info += "13.09.2221. Экипаж начинает замышлять что-то неладное. Некоторые считают, что всё что, произошло на этой станции за последние две недели - один большой эксперимент НТ.<br>"
```

2024-07-04 18:24 UTC, maleyvich commented on code/modules/paperwork/paper.dm
> +	info += "17.09.2221. В дормиториях был найден учёный с вспоротым брюхом, жуткое зрелище.<br>"
```suggestion
	info += "17.09.2221. В дормиториях был найден сотрудник  М■■■н с вспоротым брюхом, жуткое зрелище...<br>"
```

2024-07-04 18:24 UTC, maleyvich commented on code/modules/paperwork/paper.dm
> +	info += "20.09.2221. Эти ксенотвари обосновались в телекомах и успели схватить нескольких уч#<br>"
```suggestion
	info += "20.09.2221. ОНИ РАЗМНОЖИЛИСЬ, ТВАРИ УЖЕ В ТЕЛЕКОМАХ, ТВОЮ МА#<br>"
```

2024-07-04 18:26 UTC, maleyvich commented on code/modules/paperwork/paper.dm
> +	info += "17.09.2221. В дормиториях был найден учёный с вспоротым брюхом, жуткое зрелище.<br>"
это тоже кстати имхо если не нравится резолвни

2024-07-05 04:25 UTC, AirBlack commented on code/modules/paperwork/paper.dm
> +	info += "Похоже, это был не самый ценный кадр, раз его послали почти без оружия и в древнем как мир скафандре.<br>"
мне не кажется

2024-07-05 04:26 UTC, AirBlack commented on code/modules/paperwork/paper.dm
> +	info += "17.09.2221. В дормиториях был найден учёный с вспоротым брюхом, жуткое зрелище.<br>"
со вспоротым

2024-07-05 04:27 UTC, AirBlack commented on code/modules/paperwork/paper.dm
> +	info += "20.09.2221. Эти ксенотвари обосновались в телекомах и успели схватить нескольких уч#<br>"
представили лицо ученого который написал дату а потом начал кричать в бумагу текстом

2024-07-05 04:28 UTC, Slavik2001 commented on code/modules/paperwork/paper.dm
> +	info += "20.09.2221. Эти ксенотвари обосновались в телекомах и успели схватить нескольких уч#<br>"
I have no mouth, but I must scream

2024-07-05 04:30 UTC, AirBlack commented on code/modules/paperwork/paper.dm
> +	info += "13.09.2221. Экипаж начинает замышлять что-то неладное. Некоторые считают, что всё что произошло на этой станции за последние две недели - один большой эксперимент НТ.<br>"
запятая перед что а не после

2024-07-06 11:10 UTC, KatoMarika requested changes
Айрлесс турфы не просто так присутствуют в билде, меня еще в своё время Зве ругал что я их не размещал в космосе. 
Необходимо их вернуть туда, где подразумевается космос/разгерметизированное помещение при старте игры, поскольку в таком виде может появиться лаг при запуске игры.

2024-07-06 11:10 UTC, KatoMarika commented on maps/templates/space_structures/old_station.dmm
Необходимо вернуть в космос айрлесс турфы

2024-07-06 12:32 UTC, simb11 commented on maps/templates/space_structures/old_station.dmm
вернул их

2024-07-14 20:28 UTC, LudwigVonChesterfield approved these changes

2024-07-17 08:09 UTC, WatlerJe approved these changes

2024-07-17 11:29 UTC, merged