Zombie
TauCetiStation/TauCetiClassic pull request #13279
Opened 2024-07-09 20:01 UTC by Gort133

## Описание изменений
зомби теперь не видят спу используя спел поиска мозгов
## Почему и что этот ПР улучшит

## Авторство
Я

## Чеинжлог

:cl: Gort133
 - bugfix: Спел зомби на поиск людей больше не показывает на СПУ

2024-07-09 20:01 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2024-07-09 20:03 UTC, LudwigVonChesterfield commented
ещё теперь не показывает на дион. так задумано?

2024-07-09 20:05 UTC, Gort133 commented
> ещё теперь не показывает на дион. так задумано?

я планировал сначала себе залить и зафейлился. На ходу ПР редактирую. Вроде доредактировал

2024-07-09 20:05 UTC, Gort133 commented
а, сейчас еще напишу багрепорт который фиксил, секунду...

2024-07-09 20:08 UTC, Gort133 commented
написал

2024-07-10 12:30 UTC, Gort133 commented
@LudwigVonChesterfield видимо не упомянул тебя когда отвечал на вопрос. Да, так задумано.
Понятное дело что он всё ещё показывает на всяких там сламолюдей и так далее, но у меня из вариантов либо это, либо добавлять новый флаг ZOMBIEDABLE и давать ему всем заражаемым либо проверять на наличие флага NO_SCAN который не сильно подходит по смыслу, но как раз отсутствует только у хуманов, таяр, ящеров и скреллов

2024-07-11 16:01 UTC, LudwigVonChesterfield commented
@KIBORG04 Тут тебя упомянули. Реквестнул ревью.

2024-07-11 16:28 UTC, KIBORG04 commented on code/modules/mob/living/carbon/human/zombie.dm
> -		if(H.stat == DEAD || iszombie(H) || H.z != user.z)
Кажись да, флаги не то.

Мне не нравится, что место, где определено кто может быть зомби, было скопипащено несколько раз и использовано в рандомных кусках кода.

Я был бы тебе признателен, если бы ты сделал какую-то общую функцию для этой проверки. А точнее, ты бы мог создать в этом файле функцию, типа:
```
/mob/living/carbon/human/proc/can_zombified()
    return species.name in list(HUMAN, UNATHI, TAJARAN, SKRELL)
```

Далее, поменять все места, где есть проверка на эти расы (что я нашел, показываю на скриншотах), ну и потом в это место пихнуть эту функцию. 

![image](https://github.com/TauCetiStation/TauCetiClassic/assets/26389417/f0d0ec9f-89a4-4a77-ae7b-906f6d2e39bc)
![image](https://github.com/TauCetiStation/TauCetiClassic/assets/26389417/a0f8448c-c1ed-4df7-9ad9-4c54ebd6f501)

2024-07-11 16:30 UTC, KIBORG04 commented
> добавлять новый флаг ZOMBIEDABLE

А насчет этого, то впринципе тоже мб можно, но если ты вынесешь код в отдельную функцию, то изменять придется поменьше всего. Но это так, пофиг, впринципе там нужно рефакторить намного больше всего.

2024-07-11 16:32 UTC, KIBORG04 requested changes
Но идею с флагами я же посоветовал, я же покопался в коде и я же отбраковываю.

2024-07-11 16:58 UTC, Gort133 commented on code/modules/mob/living/carbon/human/zombie.dm
> -		if(H.stat == DEAD || iszombie(H) || H.z != user.z)
окей, завтра займусь. Я вроде понял как добавлять изменения в пр

2024-07-13 10:08 UTC, KIBORG04 commented
Тыкай, если что. я чудом могу заметить, что в ПРе появились новые коммиты

2024-07-13 10:08 UTC, merged