Новое дерево технологий
TauCetiStation/TauCetiClassic pull request #13287
Opened 2024-07-12 18:35 UTC by L4rever

## Описание изменений

Добавляет новое дерево технологий. На данный момент имеет только одну ветку и будет расширяться последующими ПР-ами, если этот замержат. Данное дерево технологий будет иметь несколько независимых веток, доступ к исследованиям которых открывается через специальные диски с начальными технологиями, которые будут лежать на дереликтах. 

![image](https://github.com/user-attachments/assets/0d002958-95da-4080-ae27-e2f0cc05d462)

Имеющаяся ветка содержит улучшаемые худы, которые изначально абсолютно идентичным сб-шным худам и с помощью постепенного их улучшения исследуемыми платами их можно довести до того, что они будут работать одновременно как термалы и ПНВ, ещё и не накладывая фильтр.

Все добавленные предметы:

![image](https://github.com/user-attachments/assets/f12318a9-6420-477f-afeb-9e04662cbee8)

Изначально выглядят худы так:

![image](https://github.com/user-attachments/assets/11a09bd6-acdf-4e39-ba6e-24a6586557ba)
![image](https://github.com/user-attachments/assets/d09b8545-6167-4400-86b1-d01969840de4)

После улучшения первой платой(становятся улучшенным аналогом микс худов):

![image](https://github.com/user-attachments/assets/2fd0ca55-43db-44db-91eb-61b29ebb541e)
![image](https://github.com/user-attachments/assets/b14dfabc-c617-4f6d-a068-57d312ed0a7d)

После улучшения второй платой(получают возможность включить ПНВ с сильно режущим глаза фильтром):

![image](https://github.com/user-attachments/assets/b9212c31-dc99-4990-9dee-393ebd740302)
![image](https://github.com/user-attachments/assets/abf0fb2a-d371-4313-8da8-906ecd62889b)
![image](https://github.com/user-attachments/assets/39eabf47-5db2-41c2-b19e-69e4cb63aea4)

После улучшения третьей платой(получают возможность переключать режимы между ПНВ и термалами, оба с цветофильтрами):

![image](https://github.com/user-attachments/assets/f7a58b29-fc90-4143-abc3-6ef7d6f66872)
![image](https://github.com/user-attachments/assets/8679b401-4e53-46cf-9641-d9e9b49e6d14)
![image](https://github.com/user-attachments/assets/0190daf4-d6a2-48c6-8c61-6f893e142858)

После улучшения четвёртой платой(получают режим, совмещающий ПНВ и термалы одновременно и заменяющий предыдущие два, так же убран цветофильтр)

![image](https://github.com/user-attachments/assets/e766a62c-1598-4287-8be3-f8fe885651f9)
![image](https://github.com/user-attachments/assets/07ad5ed6-f3b7-422d-abe0-7045fa6e548a)
![image](https://github.com/user-attachments/assets/161f33b8-775a-431b-b4ec-c4b31149ca50)

Балансится это всё дело тем, что на полное изучение этой ветки требуется 60 тысяч очков РнД, плюс улучшения можно ставить только по очереди, стоят они не дёшево и сама эта ветка технологий присутствует только на двух дереликтах, что само по себе делает невозможным исследовать их в каждом раунде. 

Чтобы улучшить очки, надо соответствующей платой кликнуть по очкам. Чтобы открыть ветку, надо кликнуть диском с технологией по консоли исследований.

## Почему и что этот ПР улучшит

Делает теленауку чуть более полезной

## Авторство

@L4rever, помогал @AirBlack 

## Чеинжлог
:cl:
- rscadd[link]: добавлено новое дерево исследований в РнД

2024-07-12 18:36 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2024-07-12 18:37 UTC, maleyvich commented
звучит интересно но почему это нельзя засунуть в комбат техи

2024-07-12 18:39 UTC, L4rever commented
> звучит интересно но почему это нельзя засунуть в комбат техи

Потому что сама суть этого дерева технологий всего в том, что оно будет открываться только за счёт находимых дисков. Смотреться в других деревьях оно будет не очень уместно

2024-07-12 18:47 UTC, maleyvich commented on maps/templates/space_structures/cloning_lab.dmm
> +/mob/living/simple_animal/hostile/syndicate/ranged/space/elite,
а зачем

2024-07-12 18:48 UTC, L4rever commented on maps/templates/space_structures/cloning_lab.dmm
> +/mob/living/simple_animal/hostile/syndicate/ranged/space/elite,
Чтобы эту технологию немного тяжелее было вытащить?

2024-07-12 18:50 UTC, maleyvich commented on maps/templates/space_structures/cloning_lab.dmm
> +/mob/living/simple_animal/hostile/syndicate/ranged/space/elite,
конечно его можно сваркой заебашить но ладно пох

2024-07-12 19:04 UTC, KatoMarika commented
Рекомендация убрать диск с олд_стейшон и суть куда-нибудь, где недостаток наград есть. Олд_стейшион слишком вкусный на данный момент, надо размазывать награды по остальным местам.

2024-07-12 19:12 UTC, L4rever commented
> Рекомендация убрать диск с олд_стейшон и сунуть куда-нибудь, где недостаток наград есть. Олд_стейшион слишком вкусный на данный момент, надо размазывать награды по остальным местам.

Куда, например? Нет, правда, если подскажешь - буду очень рад

2024-07-12 19:16 UTC, KatoMarika commented
> Куда, например? Нет, правда, если подскажешь - буду очень рад

Могу предложить agroshphere, delivery_shuttle, tree_asteroid

2024-07-12 19:17 UTC, Tap0r commented
> > Куда, например? Нет, правда, если подскажешь - буду очень рад
> 
> Могу предложить agroshphere, delivery_shuttle, tree_asteroid

агросферу я же ремапил там пиздец приколов лежит

2024-07-12 19:20 UTC, KatoMarika commented
> агросферу я же ремапил там пиздец приколов лежит
Мой косяк, я за количеством именно что приколов не видел диска с поинтами и гипоспрей. 

Ну тогда астеройд-дерево и шатл доставки.

2024-07-12 21:11 UTC, L4rever commented
> > Куда, например? Нет, правда, если подскажешь - буду очень рад
> 
> Могу предложить agroshphere, delivery_shuttle, tree_asteroid

Done. Теперь на деливери шаттле

2024-07-12 22:10 UTC, QWxiZ commented
Термалы - кринж, не интересно играть ни с ними, ни против них. Пожалуйста, не надо.

2024-07-14 20:17 UTC, LudwigVonChesterfield commented
мне не нрав. отписываюсь здесь чтобы сказать что ревьювить не буду, нужно чтобы кто-то другой.

2024-07-15 15:54 UTC, Chip11-n requested changes
Слишком крутое. В данный момент за 60 000 и пару кусков ресурсов можно распечатать супер очки, которые сводят на нет весь стелс. Если кто изучит их - они будут у всех, т.е. у нас вся станция превращается в ГСБ. Моё предложение в том, что бы сделать их не только трудно изучаемыми, но и крайне ограниченными в производстве. 

Так, к примеру, у нас уже имеется портальная пушка. Имба? Почти. Но ты попробуй её создать для начала из-за аномалии. Или можно дать причину РнД исследовать, к примеру, ксеноморфов, магов, шедоулингов и т.п. На этом фоне можно и снизить количество ресурсов и\или очков исследований.

Ветка для одной единственной вещи немного многовато. Понятно, что эта ветка сама по себе особая, но сделай хотя бы ещё 1-2 таких вещи.

Сама идея необычная, а вот что будет с реализацией - посмотрим.

P.s. я понимаю, что ты хочешь, что бы твоей идеей пользовались, но ведь её можно сделать не только крутой, но ещё и желанной?

2024-07-15 15:54 UTC, Chip11-n commented on code/_onclick/hud/action.dm
> +	else if(owner.action_type == AB_ITEM && owner.target)
Почему бы не засунуть это в уже имеющуюся систему?

2024-07-15 15:54 UTC, Chip11-n commented on code/modules/item_upgrades/item_upgrade.dm
> +				vision_flags = SEE_MOBS
Перебор. Может разобьёшь на моды? Типо так включается ПНВ, так мезонки, так худы меда\сб\т.д. ? По типу ниндзи.

2024-07-15 15:54 UTC, Chip11-n commented on code/modules/item_upgrades/item_upgrade.dm
> +		qdel(hud_calibrator)
Так и задумано? Не получилось и всё равно проглатывает калибратор?

2024-07-15 15:54 UTC, Chip11-n commented on code/modules/research/rdconsole.dm
> +			qdel(disk)
Как предложение, можно добавить звук.

2024-07-15 15:54 UTC, Chip11-n commented on code/modules/item_upgrades/item_upgrade.dm
> +/datum/action/item_action/hands_free/switch_hud_modes/
```suggestion
/datum/action/item_action/hands_free/switch_hud_modes
```

2024-07-15 16:17 UTC, L4rever commented on code/modules/item_upgrades/item_upgrade.dm
> +		qdel(hud_calibrator)
Так и задумано.

2024-07-15 18:00 UTC, L4rever commented on code/_onclick/hud/action.dm
> +	else if(owner.action_type == AB_ITEM && owner.target)
Потому что имеющаяся система не даёт адекватно присваивать нужные иконки кнопкам и заставляет для этого делать костыли или отдельные спрайты именно под кнопки, что лишний раз увеличивает билд, когда этого можно избежать вот этим путём. Никакие существующие кнопки не ломаются из-за этого.

2024-07-15 18:00 UTC, L4rever commented on code/modules/research/rdconsole.dm
> +			qdel(disk)
Добавлю

2024-07-16 09:18 UTC, AirBlack commented on code/_onclick/hud/action.dm
> +	else if(owner.action_type == AB_ITEM && owner.target)
в какую имеющуюся систему? которая просто берет текущий спрайт предмета? а чтобы сделать что-то свое надо рисовать отдельный спрайт по типу как это сделано с ригами, фонариком и маской? не проще легаси говно перенести на нормальную эту штуку нет?

2024-07-17 08:09 UTC, WatlerJe approved these changes

2024-07-17 11:27 UTC, KIBORG04 commented
> На данный момент имеет только одну ветку и будет расширяться последующими ПР-ами, если этот замержат.

Меня напрягает, что делается пространство для фичи, а фичи обещают когда-то в будущем.

2024-07-22 23:48 UTC, L4rever commented on code/modules/item_upgrades/item_upgrade.dm
> +				vision_flags = SEE_MOBS
Ну собственно почему я это не очень хочу делать, потому что тогда последний апгрейд будет убирание фильтров ценой 30к очков. Такое если честно

2024-08-05 20:24 UTC, TauKitty commented
Этот запрос на слияние был упомянут в **Tau Ceti Station Forum**. Там могут быть соответствующие подробности:

https://forum.taucetistation.org/t/obsuzhdenie-pr-a-novye-vetki-tehnologij-by-l4rever/43424/1

2024-08-05 21:31 UTC, TheLone1y commented
Мб не надо термалы, если смотреть на цену для просмотра сквозь стенок то для тритора это 5 телекристаллов, а для генки это 3 гена-поинта, оба очень жирные по тратам, а рнд получается почти-что за просто так... Нет вообще можно с условием что термалы будут из миллиона стекла, вроде 100 листов на одни очки

2024-08-08 17:25 UTC, Chip11-n commented
Ввиду крайне положительного фидбека, пускаю в ТМ на неделю, но окончательно мержить рука у меня не поднимается, по крайней мере, пока что.

2024-08-12 00:06 UTC, volas commented
конфликтует из-за карт

2024-08-12 00:08 UTC, volas commented
Вообще я бы вернулся к пр-у, когда будет больше исследований в ветках. Сейчас смысла мало. Но идея мне нравится.

2024-08-12 00:34 UTC, KatoMarika commented
Я вроде как пофиксил конфликт, но почему-то все еще показывает старую карту по мап дифу. 

Ну и заодно в защиту мержа этого ПРа выскажусь: 
Придумать множество фич за раз тяжелее, чем создать систему для грамотного впиливания этих фич, кто-то может сидит и ждет мержа этого ПРа для чего-то своего. + у нас из недавнего смержили волю с форматом "доделаешь методы поднятия воли потом"

2024-08-18 06:20 UTC, volas commented
воля изначально как одноразовая кнопка на раунд уже по дизайну ок

2024-08-18 06:34 UTC, volas commented
в общем, если у кого-то уже есть идеи/планы на эту ветку, которые вы намерены воплотить в жизнь после мержа этого пр-а, поставьте какой-нибудь эмоджи под этим сообщением

2024-08-20 20:17 UTC, L4rever commented
> в общем, если у кого-то уже есть идеи/планы на эту ветку, которые вы намерены воплотить в жизнь после мержа этого пр-а, поставьте какой-нибудь эмоджи под этим сообщением

Если что, я параллельно ещё тут записываю идеи для веток, для которых не надо будет много кодить и буду их постепенно выкладывать, параллельно со всем остальным. Или, если ПР так и останется открытым, то закину ещё 1 или 2 сюда. Как минимум часть вещей, которые сейчас в билде не добыть никак, кроме педального спавна хочу ввести.

2024-08-29 01:36 UTC, L4rever commented on code/modules/item_upgrades/item_upgrade.dm
> +		return
Почему не usr должен применять эффекты на худы?

2024-09-05 23:25 UTC, L4rever commented on code/modules/item_upgrades/item_upgrade.dm
> +	body_parts_covered = 0
Ну вообще потому что во всех glasses-ах так. Или в большинстве. Но изменю на EYES, по идее это правильно будет

2024-09-06 02:23 UTC, L4rever commented
В общем, добавлена новая ветка. Spec Ops. В сумме требует 100к очков для изучения, добавляет:
1. Медиган ОБР-а.
2. Стелс модуль рига
3. Возможность крафтить снайперскую винтовку в рнд(возможно будет перенесено/изменено в последующих пр-ах)
4. Пульсач
5. Броню отряда смерти.

Опять же, забаланшено всё тем же способом. Супер дорогой крафт, дорогое исследование для получения всего. В целом опять же ограничивает людей в том, что именно им качать. Эту ветку или другую(если вдруг им выпадет), или вовсе очень урезать основные исследования.

2024-09-06 03:02 UTC, L4rever commented on code/modules/item_upgrades/item_upgrade.dm
> +				vision_flags = 0
Починил, в целом.

2024-09-08 08:14 UTC, volas commented
> В общем, добавлена новая ветка. Spec Ops

ты одну ветку не можешь заполнить, зачем сразу еще другую добавлять

2024-09-08 08:16 UTC, volas commented
а, я понял, ветку. Обнови тогда описание ПР-а

2024-09-08 10:56 UTC, TheLone1y commented
Ветка спек опс не вписывается ни в какие рамки баланса если цена балансировалась только очками и ресурсами, обе вещи можно получить даже без абузов в первую половину игры, а если затрагивать ту же механику сброса консолей, то ни в какие рамки оно не влезет.

Худы тоже обещали сделать редкими, но если в раунде хотя бы один активный ученый, шанс на термалы кажется враньем и преуменьшением настоящего количества тех-дисков.

Я хз добавляет ли плашка балдепа веса и значительнее ли это чем слова обычного игрока, но нет, такое не пройдет, медган, армор, пульсач, стелс модуль, что это вообще такое...

2024-09-08 13:53 UTC, L4rever commented
> а, я понял, ветку. Обнови тогда описание ПР-а

Обновил

2024-09-08 22:08 UTC, KIBORG04 commented on code/_onclick/hud/action.dm
> +	var/button_overlay_state = null
Зачем добавлять новые какие-то иконки, если можно использовать button_icon и button_icon_state? Я так понимаю, потому что background_icon_state использует файл основной иконки, мб тогда и добавить `background_icon`

2024-09-08 22:15 UTC, KIBORG04 commented on code/modules/item_upgrades/item_upgrade.dm
> +	tier = 4
Поч слитно каждый класс? Разъедини, а то как-то не очень приятно

2024-09-08 22:17 UTC, KIBORG04 commented on code/modules/item_upgrades/item_upgrade.dm
> +		qdel(hud_upgrade)
```suggestion
		if(!user.is_in_hands(src))
			to_chat(usr, "<span class='alert'>You have to hold huds in hands to upgrade it</span>")
			return
		upgrade_hud(hud_upgrade, user)
		add_item_actions(user)
		qdel(hud_upgrade)
```
Читаемее

2024-09-08 22:17 UTC, KIBORG04 commented on code/modules/item_upgrades/item_upgrade.dm
> +	if(istype(W, /obj/item/device/hud_calibrator))
```suggestion
	else if(istype(W, /obj/item/device/hud_calibrator))
```

2024-09-08 22:17 UTC, KIBORG04 commented on code/modules/item_upgrades/item_upgrade.dm
> +	. = ..()
```suggestion
	return ..()
```

2024-09-08 22:17 UTC, KIBORG04 commented on code/modules/item_upgrades/item_upgrade.dm
> +		qdel(hud_calibrator)
```suggestion
	if(istype(W, /obj/item/device/hud_calibrator))
		var/obj/item/device/hud_calibrator = W
		to_chat(usr, "<span class='alert'>You try to recalibrate huds, but nothing happens</span>")
		qdel(hud_calibrator)
		return
```

2024-09-08 22:18 UTC, KIBORG04 commented on code/modules/item_upgrades/item_upgrade.dm
> +		qdel(hud_calibrator)
Замени все usr на user, Который передается в аргументах

2024-09-08 22:26 UTC, KIBORG04 commented on code/modules/item_upgrades/item_upgrade.dm
> +	tier = 4
У тебя тут тиры цифрами, а выше есть свитч по этим тирам, где используются дефайны. ОПРЕДЕЛИСЬ

2024-09-08 22:32 UTC, KIBORG04 commented on code/modules/item_upgrades/item_upgrade.dm
> +			item_actions.Add(new /datum/action/item_action/hands_free/switch_hud_modes/thermal_advanced(src))
Как тебе идея растащить этот свитч по obj/item/hud_upgrade/* ? Это же логичнее, чем тупо так в функции хранить..

2024-09-09 00:11 UTC, L4rever commented on code/modules/item_upgrades/item_upgrade.dm
> +			item_actions.Add(new /datum/action/item_action/hands_free/switch_hud_modes/thermal_advanced(src))
Done

2024-09-09 04:34 UTC, TauKitty commented
Этот запрос на слияние был упомянут в **Tau Ceti Station Forum**. Там могут быть соответствующие подробности:

https://forum.taucetistation.org/t/obsuzhdenie-pra-novoe-derevo-tehnologij/43682/1

2024-09-17 23:07 UTC, L4rever commented on code/_onclick/hud/action.dm
> +	var/button_overlay_state = null
Мы решили с киборгом решили что пофиг

2024-09-18 00:00 UTC, L4rever commented
@NinjaPikachuska проверь пожалуйста. Киборг просил.

2024-09-24 04:52 UTC, volas approved these changes
по коду бегло вроде ок, пока в тм закину, кто-то из мейнтейнеров может еще пройтись и замержить.

2024-09-24 09:46 UTC, KIBORG04 commented
Ментейнер этот пр и кодил 😿

2024-09-26 12:41 UTC, TheBadDay4 commented
при попытке напечатать ботинки печатается обычная броня сват.

2024-09-28 14:54 UTC, L4rever commented
> при попытке напечатать ботинки печатается обычная броня сват.

исправлю сегодня

2024-09-28 17:35 UTC, L4rever commented
> при попытке напечатать ботинки печатается обычная броня сват.

Исправил

2024-10-04 21:43 UTC, merged