Добавляем унатхам возможность пиздить всё и вся своим хвостом.
TauCetiStation/TauCetiClassic pull request #13308
Opened 2024-07-15 19:54 UTC by Tap0r

## Описание изменений

перед просмотром включите у видика звук

https://github.com/user-attachments/assets/790649b3-9307-47f5-8a9a-05ce9e5a892d

Добавил трейт тэйлпанч.
Добавил экшен кнопку для удара хвостом.
При нажатии по экшену идёт переключение удара хвостом, если оно возможно.
Если удар хвостом активирован, то все входящие клики будут проверять возможность удара и бить если можно.
Перед ударом идёт костыльно собранная анимка с дерганием диров и слипами, я хз как можно красивее завернуть.
Сам удар зависит от того, что мы будем бить.

Если это лайвинг, то дополнительно проверяется интент.
Если харм, то мы накидываем цели урон, откидываем её и роняем себя и цель.
Если не харм, то просто роняем цель.

Если это не лайвинг, то мы проверяем может ли это что-то получать урон, и если да, то наносим его
Дальше доп проверки.
Если мы бьём стену, то сами падаем.
Если мы бьём вендомат, то из него может выпасть что-то.

Трэйт и экшон добавляется расе в онгэйн и забирается в онлуз
еще там в онгейне странное было типо переменная human/M
обычно такие по первой букве называются и я машинально протыкал H, потом смотрю оно ошибки сыпет, короче я M на H заменил вот
в онлузе также в принципе

Надо бы короче потвикать значения станов/уронов и добавить зависимость от навыка в мили.
Также посмотреть и посоветовать состояния, в которых данная кнопка не могла бы быть использована, потому что я чето хз и проверок как таковых тут щас нет.

## Почему и что этот ПР улучшит
новая фича для расы унатхов
## Авторство

## Чеинжлог
:cl:
 - add: Унатхи могут бить своим хвостом окружение.

2024-07-15 19:54 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2024-07-15 19:56 UTC, KatoMarika commented
А хвост отрезать можно?

2024-07-15 20:07 UTC, AndroBetel commented
а я бы на скм это сделал

2024-07-15 22:03 UTC, ZER0-In commented
Звучит прикольно, теперь садимся на унатхов и робустим всех нюкеров, роняя их на мильон лет.

2024-07-15 22:03 UTC, ZER0-In commented
А еще мне нравится, что это встроенный стан. Просто роняешь хвостом кого угодно и берешь в третий граб. Станция унатхов-робустеров ВПЕРЕЕЕЕЕЕЕЕЕЕЕЕЕЕЕЕД!!! Кто кого первым уронит хвостом!!!

2024-07-15 22:04 UTC, ZER0-In commented
А если без иронии, лучше добавь урон да и все. Типа удар через два тайла.

2024-07-15 22:50 UTC, Tap0r commented
Это всё можно легко крутить, добавлять доп проверки на обувь, армор и тд.
Я даже стан готов убрать, ибо он не так важен. 
А просто урон это скучно, смысл отдельной кнопки для этого, если есть лкм

2024-07-15 23:07 UTC, Tap0r commented
Типо бля, что щас в пре это то что мне проще всего было сделать чтобы протестить работу экшенов, можете любые варианты идеи предлагать тут, ваще похуй, мне главное что я саму кнопку воткнул, а внутряк и не задумывался что дойдет таким до мержа

2024-07-15 23:22 UTC, KIBORG04 commented on code/modules/mob/living/carbon/human/human.dm
> +				new dump_path(src.loc)
```suggestion
			if(R.amount)
				new R.product_path(loc)
```
Хз почему не так

2024-07-15 23:24 UTC, KIBORG04 commented on code/modules/mob/living/carbon/human/human.dm
> +	sleep(1)
А зачем слипы эти?

2024-07-15 23:28 UTC, KIBORG04 commented on code/modules/mob/living/carbon/human/human.dm
> +				playsound(src, 'sound/items/vending.ogg', VOL_EFFECTS_MASTER)
Напиши все эти ифки в одном стиле. Как я понял, каждая ифка взаимоисключающая. Запиши их через if -> else if -> else if -> else что ли. Щас какое-то странное, особенно с этим отступом после else'а твоего

2024-07-15 23:36 UTC, Tap0r commented on code/modules/mob/living/carbon/human/human.dm
> +	sleep(1)
чтобы типо анимация была)

сначала унатх становится лицом к цели, потом резко разворачивается на 180, типо удар хвостом. Без слипов скипается первый этап и кукла тупо задницей в цель тыкается

2024-07-15 23:46 UTC, KIBORG04 commented on code/modules/mob/living/carbon/human/human.dm
> +	sleep(1)
Хз, но вроде не особо будет мешать

2024-07-16 01:38 UTC, volas commented
Странно, что это будет жить отдельно от комбух. 

Как компромисс можно было бы в дефолтный удар рукой добавить, как вариацию удара.

2024-07-16 02:48 UTC, Tap0r commented
> Странно, что это будет жить отдельно от комбух. 
> 
> Как компромисс можно было бы в дефолтный удар рукой добавить, как вариацию удара.

комбухами никакими кроме апперкота не пользуются 😞
темка задумывалась как аналог воксолипа

2024-07-16 02:55 UTC, volas commented
Яб тогда может думал в сторону какой-то общей механики спец приемов/абилок рас, которые можно было бы в датуме расы прописать, и которые можно было бы целенаправленно на один хоткей у всех рас делать. Сходу могу представить прием у дион, который бы буклил (привязывал ветками на месте) цель и себя на время. Про другие расы надо еще думать.

2024-07-16 06:14 UTC, TauKitty commented
Этот запрос на слияние был упомянут в **Tau Ceti Station Forum**. Там могут быть соответствующие подробности:

https://forum.taucetistation.org/t/dayom-unatham-vozmozhnost-yuzat-svoj-hvost/43287/1

2024-07-16 09:04 UTC, Chip11-n commented
Возвращение знаменитого дизарма жопой. В этот раз буквально 😄

2024-07-16 13:02 UTC, WatlerJe commented
На СКМ смена рук.

2024-07-17 05:57 UTC, IamSpy1488 commented
> тренированный мили скилл (офицеры, всякие рольки) - на дизарм подсечка хвостом
> мастерский мили скил (триторы, нюкеры, хз кто еще) - на харм усиленный обычный удар, больше урона, откидывает и укладывает на пол.

у тебя там police skill в коде, а не melee, не?

2024-07-17 06:09 UTC, Tap0r commented
> > тренированный мили скилл (офицеры, всякие рольки) - на дизарм подсечка хвостом
> > мастерский мили скил (триторы, нюкеры, хз кто еще) - на харм усиленный обычный удар, больше урона, откидывает и укладывает на пол.
> 
> у тебя там police skill в коде, а не melee, не?

да, я поменял, полис больше подходит для продвинутых техник
ну и я скилсеты просмотрел, полис в целом куда больше под концепцию подходит

2024-07-17 08:10 UTC, WatlerJe approved these changes

2024-07-19 10:27 UTC, Tap0r commented
я если здесь вынесу все расовые активки вербы экшены в отдельный файл из общего хумана норм будет?
лип воксов, смена телека у спу, вот эту тему

2024-07-19 13:50 UTC, LudwigVonChesterfield commented on code/modules/mob/living/carbon/human/human.dm
> +/mob/living/carbon/human/proc/tailpunch(atom/A)
В проке используются слипы.

Обязательно
`set waitfor = FALSE`

Возможно задуматься о асинхронных вызовах прока.

2024-07-19 13:50 UTC, LudwigVonChesterfield commented on code/modules/mob/living/carbon/human/human.dm
> +	sleep(2)
После каждого слипа надо проверять абсолютно всё.

Как минимум удалён ли моб и то что он атакует. Возможно пристёгнут ли моб. Возможно ещё скован ли моб

2024-07-19 13:51 UTC, LudwigVonChesterfield requested changes
слипопроблемы

2024-07-19 18:28 UTC, Tap0r commented
Вынес все способности, вербы и экшены рас в отдельный файл. Удар хвостом переделал, разбил на функции, после слипов добавил проверки состояния унатха, надо бы и цели. Добавил альтернативную боевую анимацию удару и логику для неё. Ещё не всё пока, но уже почти

2024-07-19 19:53 UTC, LudwigVonChesterfield commented on code/modules/mob/living/carbon/human/races_abilities.dm
> +	if(!src) // what the fuck dude?
Мб это лучше проверять именно рядом со слипом? Хотя может и норм.

2024-07-20 07:21 UTC, Tap0r commented
Короче доделал всё что хотел, разве что можно ещё чтобы картинка хвоста в кнопке тоже красилась в цвет унатха, но там я попробовал посмотрел, и врятли выйдет по всей видимости, так что в кнопке хвост будет черным. Расписал код в описании пра, можно ещё будет попробовать массовый краш тест на локалке устроить, если люди пойдут.

2024-07-26 06:47 UTC, Tap0r commented
неделя уже прошла как бы. кто-нить посмотрит? Я че угодно угодно переделать готов, вы ток посмотрите скажите

2024-07-30 08:01 UTC, volas commented on code/__DEFINES/traits.dm
> +#define TRAIT_TAILPUNCH       	  "can_tailpunch"
я не помню, а зачем у нас вообще делали эти трейты?

2024-07-30 08:02 UTC, volas commented on code/__DEFINES/traits.dm
> +#define TRAIT_TAILPUNCH       	  "can_tailpunch"
если экшен кнопка не выдается, так и так не смогут использовать

2024-07-30 08:03 UTC, volas commented on code/game/objects/effects/effect_system.dm
> +	src.icon_state = icon_state
что-то лишнее, вроде

2024-07-30 08:03 UTC, Tap0r commented on code/__DEFINES/traits.dm
> +#define TRAIT_TAILPUNCH       	  "can_tailpunch"
понятия не имею, делал с оглядкой на воксолип

2024-07-30 08:04 UTC, Tap0r commented on code/game/objects/effects/effect_system.dm
> +	src.icon_state = icon_state
создавать отдельный эффект чисто для хвоста не стал, сделал вот это вот нечто

2024-07-30 08:05 UTC, volas commented
в описании пр-а можно описание алгоритма работы не писать, это никто не будет читать, мы можем просто в коде это посмотреть

2024-08-02 08:40 UTC, Tap0r commented
Так что в итоге то пр три недели лежит уже

2024-08-09 05:14 UTC, volas commented
Тут есть несколько проблем и требуется почистить код: есть мусор, лишние трейты, лишние функции на уровне хьюмана, которые можно было бы инкапсулировать в сами экшен кнопки и завязать на сигналы.  Нужно ли пройтись по всем проблемам подробнее?

Еще я смотрю, что у рас оказывается есть уже несколько разных абилок, ящеры например могут проверить воздух языком кроме того чтоб крутить хвостом. Это всё тоже можно было бы перенести на расовые абилки, т.е. сделать их списком, только проблема что у нас хоткей только для одной из них.

2024-08-09 11:35 UTC, Tap0r commented
будет проще создать новый, всё равно всё на экшен переписывать

2024-08-09 11:35 UTC, closed without merging