Решение проблем с нестом и усиление natural xenojelly
TauCetiStation/TauCetiClassic pull request #13318
Opened 2024-07-17 06:26 UTC by maleyvich

## Описание изменений
тайтл, теперь при попадании на нест руки будут заняты предметом-заглушкой, который не позволит брать что-то в руки. выбираться всё ещё будет можно. плюсом добавил для natural xenojelly реген артерий.
## Почему и что этот ПР улучшит
resolves https://github.com/TauCetiStation/TauCetiClassic/issues/13283, решит проблему с невозможностью как либо усмирить вооруженного человека в несте кроме радикальных мер
## Авторство
я, идею дал симбака

## Чеинжлог
:cl: Maleyvich
- tweak: Будучи закованным в гнезде ксеноморфов, нельзя использовать предметы из инвентаря / окружающего пространства.
- tweak: Усиление natural xenojelly.

2024-07-17 06:26 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2024-07-22 15:59 UTC, LudwigVonChesterfield commented
Прошу пообсуждать на форуме, не понимаю эту проблему.

2024-07-22 16:07 UTC, LudwigVonChesterfield commented on code/game/objects/structures/stool_bed_chair_nest/alien_nests.dm
> +/obj/item/weapon/melee/nest_claws
Мне не очень нравится этот костыль потому-что выглядит будто это у тебя теперь клыки а не клыки не дают подобрать.

Я не против чтобы был какой-то визуал для игрока о том что он не может подбирать, но визуал должны идти в дополнение к нормальному техническому решению (запрет на подьъём) а не вместо него.

Не могу предсказать адекватных ситуаций где текущее решение не сработает, но если приковать диону, отрезать ей руку, и она у неё отрастёт. То в неё можно будет снова брать вещи.

2024-07-22 16:08 UTC, LudwigVonChesterfield requested changes
Запрет на подбор надо реализовать адекватно.

Баффы ксеножеле можно вынести в отдельный ПР и обсуждать на форуме.

2024-07-26 14:00 UTC, maleyvich commented
бафф желе вскоре будет вынесен в отдельный пр, насчет иной реализации не знаю.. слишком много придется переделывать!

2024-07-26 14:07 UTC, maleyvich commented on code/game/objects/structures/stool_bed_chair_nest/alien_nests.dm
> +/obj/item/weapon/melee/nest_claws
если смущает можно просто переименовать... но идея то сохраняется
во всяком случае, надо смотреть какую абузную хрень с этим найдут.

2024-08-16 19:08 UTC, closed without merging