[WIP] Новая раса. Тау-Китайцы
TauCetiStation/TauCetiClassic pull request #13348
Opened 2024-07-20 15:50 UTC by FatFatFat1

## Описание изменений
Добавление новой расы с своим механом

Кратко:

Есть раса Pluvia. Они могут поднимать свой уровень кармы. Если они поднимут карму достаточно сильно, то после смерти они не гостаются, а попадают в рай. Еще живые представители этой расы могут звонить в рай и общаться с мертвыми. Мертвые тоже могут звонить живым.

Не кратко:

/*
Как это должно работать

Когда ты берешь расу PLUVIAN, тебя сразу заносит в members /datum/religion/pluvia

add_member выдает соответствующие спеллы и заводит нужные регистрации сигналов

remove_member забирает спеллы и регистрации

У этой религии заведены 5 заповедей, которые нельзя нарушать. Под каждую заповедь заведен соотвествующий прок
За нарушение заповеди mob получает haram_point, превышение лимита которого mob выгоняется из религии

1) /datum/religion/pluvia/proc/harm_haram - принимает сигналы атак. Безоружные удары, выстрелы, броски, вскрытия горла ножом, доставание мозга,
удары предметами и другие явно агрессивные дейстивия накидывают тут haram_point

Дизармы, стан дубиной, удары деффибами, шприцы, автоинджекторы, удар предметом без урона и т.д. игнорируются этим проком

2) /datum/religion/pluvia/proc/suicide_haram - принимает сигналы от суицида. Я вспомнил только петлю и выстрел в рот.

3) /datum/religion/pluvia/proc/drunk_haram - принимает сигнал от бухла и наркотиков.
Если упороться или довести алкогольное состояние до второй стадии, ты мнговенно трезвлеешь и тебе накидывает харам.
Я осознано не зовел проверку на то, сам ли он выпил или его напоили.
Это сделано для того чтобы у злоумышленников была возможность быстро накинуть харам_поинтов и только потом убить плувийца без последствий в виде звонков с того света.

4) /datum/religion/pluvia/proc/drunk_haram - Если ешь палочками - все ок. Ешь руками или вилкой - лови харам поинты

5) /datum/religion/pluvia/proc/carpet_haram - Если ходишь по ковру в обуви. Долго объяснять, просто нельзя и все.

У всех /human появилась новая переменная - social_credit

Для плувийцев она важна, потому что она определяет попадет ли плувиец в рай после смерти
Для всех остальных это возможность поднимать social_credit плувийцам.

Плувийский спелл - /obj/effect/proc_holder/spell/create_bless_vote
создает рекомендательное письмо, которое и повышает social_credit owner-а письма за счет social_сredit подписавшего

Разные расы стартуют с разным запасом social_credit

1 )Все /human, кроме перечисленных ниже начинают с social_credit = 1. Соответственно они могут подписать кому-то рекомендательное письмо только один раз
2) Плувийцы начинают с нулевым запасом social_credit, потому что предполагается, что свой social_credit они потратили еще до начала смены и теперь им надо фармить их прямо на станции.
3) Дионы начинают с 3 social_credit, потому что диона это много нимф, которые сплелись в месте. У самых больших и жирных есть по 1 social_credit, а в сумме получается 3. Получается аж 3 возможности подписать письмо
4) СПУ начинают с 0 social_credit, потому что у них нет души
5) Големы начинают с 0 social_credit, потому что они подневольные и не могут за себя отвечать
6) Подмены начинают с 0 social_credit, потому что они слишком молодые чтобы голосовать. (И чтобы плувийцы social_credit не фармили с грядки)

Кроме собственно расы, на social_credit влияет еще наличие импланта лояльности и майндщилда.
Если в тебе такие импланты, то твои сошиал_кредиты обнуляются.
Это сделано для того, чтобы плувийцы (раса с самым большим ролькохант потенциалом) не шла в сб и не помогала сб и главам ловить ролей за social_credit.
Раса дизайнилась именно под социалку с обычным персоналом и с ролями.

Если перед смертью плувиец успел собрать social_credit_threshold, то в его /datum/species/pluvian/handle_death происходит /mob/living/carbon/human/proc/reborn(), который создаем ему тело в раю (место которое будет на цк слое)
Предполагается, что в раю уже можно бухать-курить, ходить по коврам и т.д. Так что этот моб remove_member из /datum/religion/pluvia, потому что в сигналах больше нет смысла.
Также у моба стираются все спеллы - просто на всякий случай.

Если тело плувийца пытаются реанимировать, а сам он успешно попал в рай, ему предложат вернуться в тело через /mob/living/carbon/human/proc/return_to_body_dialog()
При согласии, он опять влетает в свое тело и его отписывают от всех haram сигналов (потому что он теперь живой святой и ему теперь можно грешить при жизни).
Крутые светящиеся глаза бонусом. У живых святых нет /obj/effect/proc_holder/spell/create_bless_vote,
потому что им больше не надо собирать собирать письма, они и так и так после смерти попадут снова в рай.
Зато им выдадут 2 social_credit, которые они смогут кому-то передеать, если захотят.
Все спеллы которые были у него при жизни возвращаются через список spell_to_remember, который заполняется в reborn()

Плувийский спелл - /obj/effect/proc_holder/spell/no_target/ancestor_call создан для связи живых плувийцев и плувийцев в раю.

В раю стоят /obj/structure/pluvia_gong. Если живой плувиец инициатор ancestor_call, то ему создают копию его тела в раю на одном из свободных в данный момент гонгов.

Копия обладает спрайтом звоняещего, но с прозрачностью как у госта. Когда плувиец говорит, фальшивка повторяет за ним все слова. Таким образом можно болтать с мертвыми.
Если мертвый плувиец хочет выйти на связь с живым, он может ударить по гонгу специальной палочкой и выбрать себе цель звонка.
Цель звонка оповестят об этом специальным алертом и звуком гонга. Звонок можно сбросить, нажав на алерт
Если живой плувиец захочет поболтать, то он может просто кастануть ancestor_call и спелл сработает именно к тому гонгу, откуда ему звонили.
За сеанс связи нужно платить 2-мя брейндемедж.

social_credit_threshold должен высчитываться вначале смены исходя из списка живых игроков по такой формуле:

social_credit_threshold = (кол-во людей на смене)/10 + 2.

haram_threshold тоже должен как-то высчитываться, но я еще не придумал по какой формуле это будет справедливо.

*/

Почему WIP:

Код:
- Отревьювить код
Спрайты:
- Спрайт расы (то что сейчас в ПР-е это затычка)
- Одежда (то что сейчас в ПР-е это затычка)
- Турфы и объекты рая
Маппинг:
- Замапить рай

Как тестить расу:
![image](https://github.com/user-attachments/assets/17991c2f-2ce5-4299-a545-a958faf698a2)

Делаем late join

Тестим механики рая и харама в тестовой комнате (я уберу ее после ревью)

## Почему и что этот ПР улучшит
![image](https://github.com/user-attachments/assets/47df036f-ed92-487a-bf23-b230ec3be203)

## Авторство
FatFat

## Чеинжлог
:cl: FatFat
 - rscadd : Новая раса.
 - tweak: Проходил мимо кода прослушки-телепатии и подкрутил ей поддержку рунчата.

2024-07-20 15:50 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2024-07-20 15:51 UTC, FatFatFat1 commented
![image](https://github.com/user-attachments/assets/2fee3442-cdf4-4141-9144-1e3ee89dacd6)

![image](https://github.com/user-attachments/assets/3b0d2e74-6d65-4077-aa20-8132936e6b48)

![image](https://github.com/user-attachments/assets/0f631a3c-793e-4d31-a8b8-0e03f18ef542)

Спрайты делаются, но когда будут незнаю

2024-07-20 16:01 UTC, volas commented
Идея интересная, но вместо того, чтоб после смерти оказаться в гостах, смотреть кино и болеть за живых, "награждать" игрока аутизмом в какой-то коробке, куда еще не факт, что позвонят, кажется спорным.

2024-07-20 16:06 UTC, FatFatFat1 commented
> Идея интересная, но вместо того, чтоб после смерти оказаться в гостах, смотреть кино и болеть за живых, "награждать" игрока аутизмом в какой-то коробке, куда еще не факт, что позвонят, кажется спорным.

Я так рассуждал

Первые мертвые в раю могут появиться только после минуты 30-40, если быстро спидранить карму. Звонить можно и из рая и в рай, то есть быть инициатором звонка. 
Двадцать минут на побалакать с живыми (спалить своего убийцу, пароль от аплинка передать, передавать инфу между живыми).  
Контента в рай можно и еще навалить, но я бы глянул вначале как оно в екущем виде. (возможно стоит добавить возможность мертвым летать по станции в обрезанной версии госта)

2024-07-20 16:25 UTC, FatFatFat1 commented
![image](https://github.com/user-attachments/assets/d94deb64-8355-4998-bdbf-8a27977a8565)
![image](https://github.com/user-attachments/assets/db7bdb42-412c-45e9-b253-836d4a46d033)
![image](https://github.com/user-attachments/assets/9a0cd4dc-a3db-462a-ba28-59e3d0ac1099)

2024-07-20 17:09 UTC, Gort133 commented
Механики очень интересные! можно сделать кучу крутых штук на основе этого кода. Раса крутая, а если не добавят на сервер - это будет лютый харам

2024-07-20 17:35 UTC, QWxiZ commented
Будут ли какие-то взаимодействия особые с культом или священником? Может ли персонаж этой расы быть культистом раундстартом, быть промытым культом? Может ли он быть священником и помогать обычным людям попасть в рай?

2024-07-20 17:37 UTC, FatFatFat1 commented
> Будут ли какие-то взаимодействия особые с культом или священником? Может ли персонаж этой расы быть культистом раундстартом, быть промытым культом? Может ли он быть священником и помогать обычным людям попасть в рай?

Они не могут быть священниками, потому что их религия не проповедуется
Если плувиец каким-то образом поменяет свое вероисповедение (конверт культа-священника), то он теряет все свои особенности с раем

2024-07-21 06:40 UTC, WatlerJe approved these changes

2024-07-21 12:51 UTC, Naroke commented
> > Будут ли какие-то взаимодействия особые с культом или священником? Может ли персонаж этой расы быть культистом раундстартом, быть промытым культом? Может ли он быть священником и помогать обычным людям попасть в рай?
> 
> Они не могут быть священниками, потому что их религия не проповедуется Если плувиец каким-то образом поменяет свое вероисповедение (конверт культа-священника), то он теряет все свои особенности с раем
> 
> Попасть в эту религию по ходу раунда нельзя - только факт захода в раунд за плувийца дает тебе эту религию. У них нет никаких механизмов конверта

Что если святого плувийца попытаются конвертнуть? Что если плувийца попытаются клонировать? Что если плувийца посадить на электрический стул, это будет лишать его религии или нет?

2024-07-21 14:28 UTC, FatFatFat1 commented
> > > Будут ли какие-то взаимодействия особые с культом или священником? Может ли персонаж этой расы быть культистом раундстартом, быть промытым культом? Может ли он быть священником и помогать обычным людям попасть в рай?
> > 
> > 
> > Они не могут быть священниками, потому что их религия не проповедуется Если плувиец каким-то образом поменяет свое вероисповедение (конверт культа-священника), то он теряет все свои особенности с раем
> > Попасть в эту религию по ходу раунда нельзя - только факт захода в раунд за плувийца дает тебе эту религию. У них нет никаких механизмов конверта
> 
> Что если святого плувийца попытаются конвертнуть? Что если плувийца попытаются клонировать? Что если плувийца посадить на электрический стул, это будет лишать его религии или нет?

на клонирование плувиец в раю не может откликнуться. Со святым плувийцем че хочешь делай, он уже точно в рай попадет. Только культо-конверт может ему помешать. Стул никак на религию не влияет, он вроде только роли сбрасывает

2024-07-22 20:18 UTC, LudwigVonChesterfield commented on code/__DEFINES/is_helpers.dm
> +#define ispluvian(A) (A.get_species() in list(PLUVIAN))
```suggestion
#define ispluvian(A) (A.get_species() == PLUVIAN)
```

2024-07-22 20:18 UTC, LudwigVonChesterfield commented on code/_onclick/hud/alert.dm
> +	else
этот else можно убрать и сдвинуть всё ниже на одну табуляцию влево

2024-07-22 20:19 UTC, LudwigVonChesterfield commented on code/_onclick/hud/alert.dm
> +		return
это можно убрать

2024-07-22 20:19 UTC, LudwigVonChesterfield commented on code/datums/components/clickplace.dm
> +	SEND_SIGNAL(assailant, COMSIG_HUMAN_HARMED_OTHER,victim )
а почему не process_aggresive_action

2024-07-22 20:20 UTC, LudwigVonChesterfield commented on code/game/objects/items/devices/scanners/occult_pinpointer.dm
> +			target = locate(/mob/living/simple_animal/ancestor_wisp)
это нужно будет переписать на ранний возврат

2024-07-22 20:21 UTC, LudwigVonChesterfield commented on code/game/objects/items/weapons/implants/mindshield.dm
> +		H.social_credit = 0 // пока ты не скинешь эту штуку - ты не можешь заработать карму
мне кажется или ничего не мешает зарабатывать карму пока ты под защитой. а ещё карма не возвращается после того как имплант достанут. так и задумано?

2024-07-22 20:21 UTC, LudwigVonChesterfield commented on code/game/objects/structures/stool_bed_chair_nest/chairs.dm
> +		SEND_SIGNAL(M, COMSIG_HUMAN_TRY_SUICIDE, src)
TRY подразумевал бы что сигнал может помешать попытке

думаю надо _ON_

2024-07-22 20:23 UTC, FatFatFat1 commented on code/game/objects/items/weapons/implants/mindshield.dm
> +		H.social_credit = 0 // пока ты не скинешь эту штуку - ты не можешь заработать карму
Да. 
Кольнули - все профукал
Заработал с имплантом - опять профукалось
Убрал имплант - вот теперь можно и заработать

2024-07-22 20:23 UTC, LudwigVonChesterfield commented on code/modules/mob/living/carbon/human/human.dm
> +	if(ispluvian(src))
тут неправильно построена цепочка. если ты уже в теле (клаент != null но ты плувиан то пойдет код ниже

надо переструктуризировать

2024-07-22 20:24 UTC, LudwigVonChesterfield commented on code/modules/mob/living/carbon/human/pluvia_heaven.dm
> +	if(owner.gender == "female")
вроде для этого дефайны есть

2024-07-22 20:24 UTC, FatFatFat1 commented on code/game/objects/items/weapons/implants/mindshield.dm
> +		H.social_credit = 0 // пока ты не скинешь эту штуку - ты не можешь заработать карму
И тут не столько лорно-логическая причина блока майндщилдом.
Тут геймдизайнерская нужда ограничить этой расе профиты от службы в сб или сотрудничеством с сб. Потому что ролькохант-потенциал этой расы слишком велик и лучше влияние этой расы направить в другое русло

2024-07-22 20:25 UTC, LudwigVonChesterfield commented on code/modules/mob/living/carbon/species.dm
> +	if(!iscultist(H) && !ischangeling(H) &&!isshadowthrall(H) && H.mind)
тут надо будет применить ранний возврат

2024-07-22 20:26 UTC, LudwigVonChesterfield commented on code/modules/mob/living/living.dm
> +		SEND_SIGNAL(src, COMSIG_HUMAN_IS_DRUNK, src)
если так резко набухаться что проскочишь фазу конфуза сразу в алкогольную кому - то выйдет что не харам, потому-что сигнал не отправится.

а ещё сейчас можно напиться до того что ты начнёшь мямлить но это не харам.

2024-07-22 20:27 UTC, LudwigVonChesterfield commented on code/modules/mob/mob.dm
> +	SEND_SIGNAL(src, COMSIG_HUMAN_IS_DRUNK, src)
вместо COMSIG_HUMAN_IS_DRUNK лучше будет COMSIG_MOB_ON_ADJUST_DRUGINESS

2024-07-22 20:28 UTC, LudwigVonChesterfield commented on code/modules/reagents/reagent_containers/food/snacks.dm
> +				SEND_SIGNAL(M, COMSIG_HUMAN_EAT, src)
лучше назови COMSIG_HUMAN_ON_CONSUME

2024-07-22 20:29 UTC, LudwigVonChesterfield commented on code/modules/religion/religion_types/pluvia.dm
> +	if(ishuman(O))
если на вагонетке уборщика заехать на ковёр это будет харамом почему-то.

2024-07-23 08:17 UTC, FatFatFat1 commented on code/_onclick/hud/alert.dm
> +		return
типо потому что он и так удаляется?

2024-07-23 08:19 UTC, FatFatFat1 commented on code/modules/mob/living/living.dm
> +		SEND_SIGNAL(src, COMSIG_HUMAN_IS_DRUNK, src)
А каким образом можно так набухаться?
Бухло ведь капает от переваривания этанола. Я не могу разом сотню этанола переварить даже если я выпью сто тыщ литров водки.

2024-07-23 08:26 UTC, FatFatFat1 commented on code/_onclick/hud/alert.dm
> +		return
или ты имел ввиду удалить return?

2024-07-23 08:51 UTC, FatFatFat1 commented on code/datums/components/clickplace.dm
> +	SEND_SIGNAL(assailant, COMSIG_HUMAN_HARMED_OTHER,victim )
Потому что в process_aggresive_action есть проверка на есть ли force у предмета в руке, которым ты стукнул (чтобы ерудновые удары от банных веников, подушек, наволочек).
У граба force 0 и это не засчитывается в харам. 
Проще просто сигнал тут отсылать, чем в process_aggresive_action объяснять про граб

2024-07-23 10:33 UTC, FatFatFat1 commented on code/game/objects/items/weapons/implants/mindshield.dm
> +		H.social_credit = 0 // пока ты не скинешь эту штуку - ты не можешь заработать карму
Починил

2024-07-23 10:40 UTC, FatFatFat1 commented on code/modules/mob/living/carbon/human/human.dm
> +	if(ispluvian(src))
Если я правильно понял о чем ты, то починил

2024-07-23 10:42 UTC, FatFatFat1 commented on code/game/objects/structures/stool_bed_chair_nest/chairs.dm
> +		SEND_SIGNAL(M, COMSIG_HUMAN_TRY_SUICIDE, src)
переименовал сигналы

2024-07-23 10:44 UTC, FatFatFat1 commented on code/modules/mob/living/carbon/human/pluvia_heaven.dm
> +	if(owner.gender == "female")
Действительно есть

2024-07-23 10:48 UTC, FatFatFat1 commented on code/modules/mob/living/living.dm
> +		SEND_SIGNAL(src, COMSIG_HUMAN_IS_DRUNK, src)
И первая фаза это еще не харам

2024-07-23 10:49 UTC, FatFatFat1 commented on code/modules/mob/living/carbon/species.dm
> +	if(!iscultist(H) && !ischangeling(H) &&!isshadowthrall(H) && H.mind)
сделано

2024-07-23 10:51 UTC, FatFatFat1 commented on code/game/objects/items/devices/scanners/occult_pinpointer.dm
> +			target = locate(/mob/living/simple_animal/ancestor_wisp)
немного не понимаю что имеешь ввиду
логика должна быть такая
Есть эктоплазма? Показываю туда
Нет эктоплазмы? Показывай на виспа
Нет виспов? Икон_стейт locnull

2024-07-23 17:03 UTC, FatFatFat1 commented
паралакс надо еще пошатать, пока что не корректно работает

2024-07-25 14:11 UTC, ZER0-In commented
> паралакс надо еще пошатать, пока что некорректно работает

У меня нет слов описать твою гениальность. Если у нас будет раса Таукитайцев, Таукитай встанет с колен и достигнет рая...

2024-07-26 12:04 UTC, FatFatFat1 commented
А вот теперь работает параллакс коректно

2024-07-27 11:00 UTC, FatFatFat1 commented on code/modules/religion/religion_types/pluvia.dm
> +	if(ishuman(O))
fix

2024-07-28 05:28 UTC, Javeliiner commented
#4) СПУ начинают с 0 social_credit, потому что у них нет души

не должны ли по такой логике воксы (учитывая их механизм размножения) тоже быть бездушными, следовательно, иметь ноль кредитов?

2024-07-28 05:34 UTC, Gort133 commented
> > 4. СПУ начинают с 0 social_credit, потому что у них нет души
> 
> не должны ли по такой логике воксы (учитывая их механизм размножения) тоже быть бездушными, следовательно, иметь ноль кредитов?

Воксы же БИОроботы 
Да и кортик это вроде как полноценный мозг
Такое лучше спросить у ксеношизов

2024-07-28 06:36 UTC, FatFatFat1 commented
> > > 4. СПУ начинают с 0 social_credit, потому что у них нет души
> > 
> > 
> > не должны ли по такой логике воксы (учитывая их механизм размножения) тоже быть бездушными, следовательно, иметь ноль кредитов?
> 
> Воксы же БИОроботы Да и кортик это вроде как полноценный мозг Такое лучше спросить у ксеношизов

Раз их в камень душ можно поймать (в отличии от СПУ) - значит у них есть сошиал кредиты.
Да и было бы некрасиво отбирать у плувийцев смешные интеракции с расой космо-цыган. Такой коллаб можно замутить

2024-07-29 10:04 UTC, FatFatFat1 commented
Когда будет понятно что в мерж можно сувать, я тест-мапу снесу, только рай останется +- на том же месте

2024-07-29 10:39 UTC, FatFatFat1 commented
А, ПР активно ищет спрайтеров
Если хотите изи вайти-лист через собес со мной (без квенты, просто вопросики обкашляем в лс), то пишите

2024-07-29 16:57 UTC, FatFatFat1 commented
нужно немного пофиксить прослушку

2024-08-01 09:09 UTC, FatFatFat1 commented
![image](https://github.com/user-attachments/assets/9383f268-ef3a-4964-9aed-d41ea5258b2c)
Гонг готов

2024-08-04 11:13 UTC, FatFatFat1 commented
сомнительное решение с прослушкой, но я пока лучше не придумал

2024-08-05 12:27 UTC, FatFatFat1 commented
![image](https://github.com/user-attachments/assets/4b9d6b6d-4135-4e19-8eb9-b6c5d47a0981)

https://tenor.com/view/mmmm-monkey-monkey-ug-master-oogway-oogway-gif-19727561

2024-08-05 12:30 UTC, FatFatFat1 commented
![image](https://github.com/user-attachments/assets/4e58b4ae-4b81-418e-911c-a69fc1ab9c6d)

![mmmm-monkey-monkey](https://github.com/user-attachments/assets/1c505de2-bf9a-46f5-b5c6-f7b2201a024f)

2024-08-05 15:57 UTC, FatFatFat1 commented
![image](https://github.com/user-attachments/assets/d05a32ed-d7e1-4014-9dc7-9fe3b0f57ede)

Luna-rice is ready

2024-08-06 07:12 UTC, FatFatFat1 commented on code/modules/reagents/reagent_containers/food/snacks.dm
> +	name = "Луна-рис"
Что значит неймы на русском так где не надо. Мы же переводим билд на русский, зачем что-то изначально писать на англ?

2024-08-06 07:38 UTC, FatFatFat1 commented on code/modules/mob/living/carbon/human/pluvia_heaven.dm
> +				owner.social_credit += 1 //@FatFat Возможно стоит добавить налог на подписи от других плувийцев. Типо не +1, а +0.5. Не уверен что это может хорошо повлиять на их социанльые взаимодействия
комментарии уйдут после мержа

2024-08-06 07:39 UTC, FatFatFat1 commented on code/modules/mob/living/carbon/human/pluvia_heaven.dm
> +			to_chat(usr, "<span class='notice'>Эта бумага уже подписана</span>")
норм звучит

2024-08-06 13:02 UTC, FatFatFat1 commented
Значительные нововведения в документе по лору

2024-08-07 07:13 UTC, FatFatFat1 commented on code/modules/mob/living/carbon/human/pluvia_heaven.dm
> +			to_chat(usr, "<span class='notice'>Эта бумага уже подписана</span>")
Не имеет значения как выше или ниже подписано. В контексте игры звучит нормально, потому что когда ты левый болванчинк и пытаешься подписать бумагу то для тебя это бумага-документ. Если ты сам себе пытаешься подпись сделать то письмо (сокр от рекомендальное письмо) звучит тоже корректно

2024-08-07 10:02 UTC, FatFatFat1 commented
![image](https://github.com/user-attachments/assets/981bd0b5-9a41-42b3-a0b8-2febb494d0ff)

Виспы и колодец подъехали

2024-08-07 10:43 UTC, FatFatFat1 commented
Чуть-чуть беру перерыв
Как перекурю надо пофиксить баг - если взорваться то проверка на рай не происходит, потому что у меня нет моба, который бы хранил social_credit
Возможно стоит перенести social_credit в переменные mind-а

2024-08-09 17:36 UTC, FatFatFat1 commented
![image](https://github.com/user-attachments/assets/d3b743e2-09c0-4ae3-8b5c-c3fd5b72f3d2)
Иконки спеллов подъехали

2024-08-09 19:03 UTC, TauKitty commented
Этот запрос на слияние был упомянут в **Tau Ceti Station Forum**. Там могут быть соответствующие подробности:

https://forum.taucetistation.org/t/novaya-rasa-pluvijczy-obsuzhdenie/43465/1

2024-08-16 12:52 UTC, FatFatFat1 commented
ПР жив
Просто спрайты ждем

2024-08-23 10:15 UTC, FatFatFat1 commented
ПР жив
ждем спрайтов

2024-08-30 07:13 UTC, FatFatFat1 commented
Превентивный удар по боту

2024-09-11 10:04 UTC, FatFatFat1 commented
Превентивный удар по боту

2024-09-16 08:16 UTC, FatFatFat1 commented
Для удобства тестирования, спавн-поинты светлячков пока не раскиданы по карте, как ПР пройдет ревью, раскидаю

2024-09-16 08:25 UTC, FatFatFat1 commented
ПР ожидает ревью

2024-09-16 08:33 UTC, FatFatFat1 commented
Не забыть после ревью:
1) Убрать тестовую мапу
2) Раскидать спавн поинты светлячков по разным картам

2024-09-16 08:54 UTC, UDaV73rus commented
у виспа с анимацией частиц беды
пончо синей версии, у вида сзади потерялась обводка и на обычном и на толстом, но на остальных дирах обводка есть

2024-09-16 09:05 UTC, FatFatFat1 commented
> у виспа с анимацией частиц беды пончо синей версии, у вида сзади потерялась обводка и на обычном и на толстом, но на остальных дирах обводка есть

Достоверные источники сообщают, что обнова для спрайтов будет на этой неделе
но для начала ревью ПР-а этих пока хватит.

2024-09-16 12:50 UTC, FatFatFat1 commented
чеки сломались

2024-09-16 13:26 UTC, maleyvich commented on code/modules/admin/admin_verbs.dm
> +	set desc = "Пускай знает что после смерти попадет в рай"
```suggestion
	set desc = "Пускай знает, что после смерти попадет в рай"
```

2024-09-16 13:26 UTC, maleyvich commented on code/modules/clothing/under/miscellaneous.dm
> +	desc = ""
ватахел

2024-09-16 13:27 UTC, FatFatFat1 commented on code/modules/clothing/under/miscellaneous.dm
> +	desc = ""
нет описания

2024-09-16 13:27 UTC, maleyvich commented on code/modules/holidays/new_year/clothing.dm
> +	icon_state = "wpluvia_hat"
это конечно не в тему перевода но можно было wpluvia сделать подтипом head/pluvia и не копипастить.

2024-09-16 13:28 UTC, maleyvich commented on code/modules/mob/living/carbon/human/pluvia_heaven.dm
> +		to_chat(user, "<span class='notice'>Пожалуйста подождите [round((next_ring - world.time) * 0.1, 0.1)] секунд</span>")
```suggestion
		to_chat(user, "<span class='notice'>Пожалуйста, подождите [round((next_ring - world.time) * 0.1, 0.1)] секунд</span>")
```

2024-09-16 13:29 UTC, maleyvich commented on code/modules/religion/religion_types/pluvia.dm
> +Как это должно работать
опять же не по вопросу перевода, все должно быть на английском в этом случае.

2024-09-16 13:29 UTC, FatFatFat1 commented on code/modules/religion/religion_types/pluvia.dm
> +Как это должно работать
уже не актуально

2024-09-16 13:30 UTC, maleyvich commented
добавь  падежи одежды, другим вещам же добавил.

2024-09-16 13:30 UTC, FatFatFat1 commented
> добавь падежи одежды, другим вещам же добавил.

не хочу
оно не переведено, значит падежи не нужны

2024-09-16 13:32 UTC, maleyvich commented on code/modules/holidays/new_year/clothing.dm
> +	name = "pluvia non la"
вот здесь

2024-09-16 13:32 UTC, maleyvich commented on code/modules/holidays/new_year/clothing.dm
> +	name = "non la"
и вот здесь ( и выше)

2024-09-16 13:32 UTC, maleyvich commented on code/modules/holidays/new_year/clothing.dm
> +	icon_state = "wpluvia_hat"
вот сюда, да.

2024-09-16 13:46 UTC, FatFatFat1 commented
уберите lable Work in Progress пожалуйста

2024-09-16 15:45 UTC, Kiromaka commented on code/modules/admin/admin_verbs.dm
> +	var/reason= input("Какая причина?", "Причина?") as text|null
Я не буду это отыгрывать.

2024-09-16 15:47 UTC, Kiromaka commented on code/modules/mob/holder.dm
> +	name = "Плувеныш"
Куда нэйм.

2024-09-16 15:49 UTC, Kiromaka commented on code/modules/mob/living/carbon/human/pluvia_heaven.dm
> +	dat = "<B><font color = ##ff0000>[CASE(src, NOMINATIVE_CASE)] для прохода в рай</font></B><BR>"
src - это что тут ?

2024-09-16 15:49 UTC, Kiromaka commented on code/modules/mob/living/carbon/human/pluvia_heaven.dm
> +		dat += "<I><font color = ##ff0000>Подписывая эту бумагу, вы подтверждаете[CASE(owner, NOMINATIVE_CASE)] достойной попасть в рай после смерти</font></I><BR><BR>"
Кого/чего - винительный.

2024-09-16 15:49 UTC, Kiromaka commented on code/modules/mob/living/carbon/human/pluvia_heaven.dm
> +		dat += "<I><font color = ##ff0000>Подписывая эту бумагу, вы подтверждаете[CASE(owner, NOMINATIVE_CASE)] достойным попасть в рай после смерти</font></I><BR><BR>"
Кого/чего - винительный.

2024-09-16 15:51 UTC, Kiromaka commented on code/modules/mob/living/carbon/human/pluvia_heaven.dm
> +	visible_message("[bicon(src)] <span class='notice'>[CASE(src, NOMINATIVE_CASE)] гудит от удара [CASE(user, NOMINATIVE_CASE)].</span>")
от удара Кого/чего - винительный. А вообще зачем на юзера падеж, хуй знает. (ну в мега лейте если заставить игроков склонять нэймы поможет кнч)

2024-09-16 15:56 UTC, FatFatFat1 commented on code/modules/mob/living/carbon/human/pluvia_heaven.dm
> +	dat = "<B><font color = ##ff0000>[CASE(src, NOMINATIVE_CASE)] для прохода в рай</font></B><BR>"
bless_vote

2024-09-16 16:29 UTC, FatFatFat1 commented on code/modules/mob/living/carbon/human/pluvia_heaven.dm
> +	visible_message("[bicon(src)] <span class='notice'>[CASE(src, NOMINATIVE_CASE)] гудит от удара [CASE(user, NOMINATIVE_CASE)].</span>")
сделал

2024-09-17 03:49 UTC, volas requested changes

2024-09-17 03:49 UTC, volas commented on code/controllers/subsystem/ticker.dm
> +	message_admins("Порог кармы в этом раунде - [global.social_credit_threshold ]")
админам эта информация не очень важна, и саму инициализацию переменной лучше вынести из тикета ближе туда, где оно требуется.

2024-09-17 03:49 UTC, volas commented on code/modules/mob/living/carbon/human/death.dm
> +		reborn()
типо тут можно проверить сначала 

```
if(isnull(social_credit_threshold))
	social_credit_threshold = (totalPlayersReady/10) + 3
```

2024-09-17 03:49 UTC, volas commented on code/modules/mob/living/living_defense.dm
> +		if(item_in_hand)
агрессивные действия не всегда предметом в руке делаются, он может не иметь никакого отношения к вызову лога, взять например ``/obj/machinery/gibber/proc/gib_mob(mob/user)``

или ситуации, когда предмет выпал из рук, когда предмет хармит не своим force-ом (пушки), когда юзер сменил руки, в общем очень зыбкий момент. 

Я бы вообще предложил не мешать логи с физической частью игры и откатить замену на process_aggresive_action(), и просто добавить еще один отдельный метод (или сразу сигнал вызывать), который вызывать более целенаправленно и когда нужно - на месте можно например сразу проверять урон, прежде чем действовать дальше.

Либо заняться рефакторингом логов под новые требования.

2024-09-17 03:49 UTC, volas commented on code/datums/outfits/jobs/centcom.dm
> +	H.mind.social_credit = 0
я правильно понял, что это переписывает species кредиты для выбранных проф?

Эквип у нас может использоваться и посреди раунда админом, у него есть своя узкая сфера применения и добавлять сюда что-то еще не стоит.

Может в том же mind_initialize() выше assigned_job проверять. Если на тот момент джоб еще не доступен, можно майнду сделать отдельный метод типо init_social_credit(), и вызывать откуда-то, когда профа и раса уже известны.

2024-09-17 03:49 UTC, volas commented on code/game/objects/items/devices/scanners/occult_pinpointer.dm
> +			target = locate(/mob/living/simple_animal/ancestor_wisp)
что-то вроде

```
if(!target)
	target = locate(target_type) || locate(/mob/living/simple_animal/ancestor_wisp)
if(!target)
	icon_state = "locnull"
	return
```

просто на одном уровне без лестниц

2024-09-17 03:49 UTC, volas commented on code/game/objects/items/devices/scanners/occult_pinpointer.dm
> +			target = locate(/mob/living/simple_animal/ancestor_wisp)
locate возможно будет возвращать всегда один и тот же висп и не обязательно ближний, потому может тебе надо добавить логику с проверкой расстояния или рандомный пик,
```
if(!target)
	target = locate(target_type)
if(!target)
	do it here
if(!target)
	icon_state = "locnull"
	return
```

2024-09-17 03:49 UTC, volas commented on code/game/objects/items/devices/scanners/occult_pinpointer.dm
> +			target = locate(/mob/living/simple_animal/ancestor_wisp)
еще надо будет посмотреть, чтоб оно каждый тик не пыталось обыскивать весь мир на светлячков лагая сервер

2024-09-17 03:49 UTC, volas commented on code/modules/clothing/under/miscellaneous.dm
> +	desc = ""
у них и так вроде не будет описания, это тут лишнее. Или если перегрузка нужна, можно было бы хотя бы ``desc = null``

2024-09-17 03:49 UTC, volas commented on code/modules/religion/religion_types/pluvia.dm
> +/turf/simulated/floor/carpet/Entered(atom/movable/O)
просьба переместить этот метод в соответствующий файл к коврам

2024-09-17 03:49 UTC, volas commented on code/modules/mob/telepathy.dm
> +/mob/proc/add_remote_hearer(mob/hearer, IGNORE_DISTANTS)
большими буквами обычно пишется дефайны, как перменную лучше как обычно писать, а то меня ввело в ступор.

2024-09-17 03:49 UTC, volas commented on code/modules/mob/telepathy.dm
> +	var/ignore_telepathy_distants = FALSE
вообще мне не очень понятна логика этого флага, который объявлен в мобе и перезатирается при использовании телепатии на нём

2024-09-17 06:03 UTC, FatFatFat1 commented on code/modules/mob/living/living_defense.dm
> +		if(item_in_hand)
1) Так когда идет харм не своим формом, то это тоже детектится, Ты можешь стрельнуть на тестовой карте по плувийцу и это сработает
2) Гиббер действительно не детектится, добавлю туда. (И все последующие промахи тоже будут учтены простым добавлением сигнала атаки)
3) Фактически я не вмешиваюсь в сами логи. Логика логирования остается в /mob/living/proc/log_combat.

2024-09-17 06:42 UTC, FatFatFat1 commented on code/datums/outfits/jobs/centcom.dm
> +	H.mind.social_credit = 0
done

2024-09-17 06:53 UTC, FatFatFat1 commented on code/modules/mob/telepathy.dm
> +	var/ignore_telepathy_distants = FALSE
Ситуация
Телепатия начинает портить сообщение если цель прослушки слишком далеко от тебя. В нашем случае речь идет АЖ о другом слою, так что сообщение должно портиться. Я добавил IGNORE_DISTANTS, чтобы в /obj/effect/proc_holder/spell/no_target/ancestor_call/cast вызывать user.toggle_telepathy_hear с IGNORE_DISTANTS = TRUE
Ужасный костыль, но решения лучше как-то в голову не пришло

2024-09-17 07:16 UTC, FatFatFat1 commented on code/modules/mob/living/carbon/human/death.dm
> +		reborn()
немного не понимаю зачем высчитывать каждый раз после смерти threshold, когда это можно сделать только один раз при начале раунда

2024-09-17 07:18 UTC, FatFatFat1 commented on code/_onclick/item_attack.dm
> +					M.process_aggresive_action(user, "knifed with [name] (INTENT: [uppertext(user.a_intent)]) (DAMTYPE: [uppertext(damtype)])")
найдем - поменяем

2024-09-17 07:57 UTC, FatFatFat1 commented on code/modules/mob/living/living_defense.dm
> +		if(item_in_hand)
Я проверил гиббер, он и так работает

2024-09-17 08:40 UTC, volas commented on code/modules/mob/living/carbon/human/death.dm
> +		reborn()
это будет что-то вроде ленивой инициализации переменной, if сработает только если она еще не инициализировалась, можно еще static сделать. В тикере такие вещи просто не нужны, и это на уровне предложения, куда бы можно было перенести. Можно и другое место подыскать.

Еще персонально у меня плохие воспоминания от всех попыток привязаться к онлайну/ready-счетчику. Оно слишком плавающее и не показательное, и игроками зависимость плохо воспринимается. Хотя не уверен, что статичное значение будет лучше. Как вариант, может каждому плувийцу рандомить своё значение в момент входа в игру, с зависимостью или без от онлайна, и явно сообщать "Вам нужно столько то подписей для рая".

2024-09-17 09:45 UTC, FatFatFat1 commented on code/modules/mob/telepathy.dm
> +/mob/proc/add_remote_hearer(mob/hearer, IGNORE_DISTANTS)
переделал

2024-09-17 09:46 UTC, FatFatFat1 commented on code/modules/mob/living/living_defense.dm
> +		if(item_in_hand)
Переделал
убрал process_aggresive_action()
теперь просто где надо сигналы отправляются

2024-09-17 09:47 UTC, FatFatFat1 commented on code/modules/mob/living/carbon/human/death.dm
> +		reborn()
Думаю надо просто посмотреть как людям с этим играется
там уж и менять будем соответственно по нужде и фидбеку

2024-09-17 09:54 UTC, FatFatFat1 commented on code/modules/mob/living/carbon/human/death.dm
> +		reborn()
Перенес из тикера 
done

2024-09-18 08:59 UTC, AirBlack commented
@WhaleNotPower а почему у женских кукол между ног пенис? Там вот этот нижний пиксель посередине не подходит по оттенку к остальной обводке/шейдингу и больше похож на висящую головку пениса. Я это спросил у фат фата, он ответил что "че ты докопался, это всего два пикселя", но проведя сложные математические рассчеты, если у нас тайл 32х32 пикселя и 2х2 метра, то 2 пикселя будет 12 с половиной сантиметров примерно что как раз ну такой норм размер для неэрегированного пениса. Этому будут какие-то лорные объяснения или это просто ошибка?

2024-09-29 06:26 UTC, volas requested changes

2024-09-29 06:26 UTC, volas commented on code/modules/mob/living/carbon/human/pluvia_heaven.dm
> +	next_ring = world.time + 30 SECONDS
есть ряд специальных макросов вроде COOLDOWN_DECLARE и прочие COOLDOWN_*, для простоты и лучшего оформления кода, но это опционально

2024-09-29 06:26 UTC, volas commented on code/modules/mob/living/carbon/human/pluvia_heaven.dm
> +/mob/living/simple_animal/ancestor_wisp
мне кажется, это можно было бы подтипом гостоты сделать. Как есть он, хоть и невидим, но сможет где-то интерактить с миром.

2024-09-29 06:26 UTC, volas commented on code/modules/religion/religion_types/pluvia.dm
> +/datum/religion/pluvia
как отдельная религия у нас нигде не будет забавных интерактов с обычными культами и священниками? Типо захвата церкви или что-то такое @KIBORG04 @LudwigVonChesterfield

2024-09-29 10:29 UTC, FatFatFat1 commented on code/modules/religion/religion_types/pluvia.dm
> +/datum/religion/pluvia
Если их культист или священник завербует, то у них все приколы расы отвалятся вместе с религией без права на реанимацию.

2024-09-29 10:30 UTC, FatFatFat1 commented on code/modules/mob/living/carbon/human/pluvia_heaven.dm
> +/mob/living/simple_animal/ancestor_wisp
Они все же более материальные чем госты
как минимум их можно убить, так что они уже living

2024-09-29 10:36 UTC, FatFatFat1 commented on code/modules/mob/living/carbon/human/pluvia_heaven.dm
> +	var/mob/living/carbon/human/H = usr
done

2024-09-29 10:41 UTC, FatFatFat1 commented on code/modules/admin/admin_verbs.dm
> +	set desc = "Накидывает очки греха вручную"
done

2024-09-29 10:43 UTC, FatFatFat1 commented on code/_onclick/hud/parallax.dm
> +	var/current_parallax = PARALLAX_CLASSIC
Она выставляется мобу при инициализации

Допустим мне поменяло паралакс на райский, но я умер-гостнулся, короче получил респавн.
Клиент у меня все тот же. Захожу за нового моба - моему клиенту ставится current_parallax моего моба

2024-09-29 10:44 UTC, FatFatFat1 commented on code/modules/admin/admin_verbs.dm
> +	var/reason= input("Какая причина?", "Причина?") as text|null
done

2024-09-29 10:45 UTC, FatFatFat1 commented on code/modules/admin/admin_verbs.dm
> +	set desc = "Накидывает очки греха вручную"
ой
не туда done написал

2024-09-29 10:51 UTC, FatFatFat1 commented on code/modules/admin/admin_verbs.dm
> +	set desc = "Накидывает очки греха вручную"
Перенести было бы славно
Но я не шарю за жава-скрипт

2024-09-29 10:57 UTC, FatFatFat1 commented on code/modules/admin/admin_verbs.dm
> +	var/haram_point= input("Сколько очков греха накидываем?", "Очки Греха") as text|null
done

2024-10-04 21:46 UTC, volas commented on code/modules/admin/admin_verbs.dm
> +	var/haram_point= sanitize(input("Сколько очков греха накидываем?", "Очки Греха") as num|null)
ты мог просто принять предложенное мной изменение, а то теперь ты применяешь текстовый санитайз к функции, которая всегда возвращает число

2024-10-04 21:49 UTC, volas commented on code/_onclick/hud/parallax.dm
> +	var/current_parallax = PARALLAX_CLASSIC
заметил, оно в set_parallax

2024-10-05 05:58 UTC, FatFatFat1 commented on code/modules/admin/admin_verbs.dm
> +	var/haram_point= sanitize(input("Сколько очков греха накидываем?", "Очки Греха") as num|null)
поменял обратно

2024-10-05 05:59 UTC, FatFatFat1 commented on code/modules/admin/admin_verbs.dm
> +	var/haram_point= sanitize(input("Сколько очков греха накидываем?", "Очки Греха") as num|null)
поменял

2024-10-06 09:57 UTC, FatFatFat1 commented on code/modules/mob/living/carbon/human/human.dm
> +		for(var/mob/living/carbon/human/pluvian_spirit/spirit in player_list)
действительно не хватает

2024-10-06 16:37 UTC, FatFatFat1 commented on code/modules/mob/living/carbon/human/human.dm
> +		for(var/mob/living/carbon/human/pluvian_spirit/spirit in player_list)
done

2024-10-06 16:52 UTC, FatFatFat1 commented on code/modules/mob/living/carbon/human/human.dm
> -		playsound_local(null, 'sound/misc/mario_1up.ogg', VOL_NOTIFICATIONS, vary = FALSE, ignore_environment = TRUE)
никак нет, он ниже вроде

2024-10-06 16:52 UTC, FatFatFat1 commented on code/modules/mob/living/carbon/human/pluvia_heaven.dm
> +/area/pluvia_heaven
я перенесу в /religion

2024-10-06 17:01 UTC, FatFatFat1 commented on code/modules/mob/living/carbon/human/pluvia_heaven.dm
> +	to_chat(src, "<span class='notice'>\ <font size=4>Вам известно, что после смерти вы попадете в рай</span></font>")
dooone

2024-10-06 17:06 UTC, FatFatFat1 commented on code/modules/mob/living/carbon/human/death.dm
> +/mob/living/carbon/human/proc/check_pluvian_credits()
done

2024-10-06 17:06 UTC, FatFatFat1 commented on code/modules/religion/religion_types/pluvia.dm
> +		log_admin("Pluvian [key_name(target)] haram - [reason] [ADMIN_JMP(target)]")
done

2024-10-06 17:07 UTC, FatFatFat1 commented on code/modules/religion/religion_types/pluvia.dm
> +		message_admins("Pluvian [key_name(target)] lose /datum/religion/pluvia [ADMIN_JMP(target)]" )
done

2024-10-06 17:07 UTC, FatFatFat1 commented on code/modules/mob/living/carbon/human/human.dm
> +					log_admin("Pluvian [key_name(spirit.my_corpse)] is living saint now  [ADMIN_JMP(spirit.my_corpse)]")
done

2024-10-06 17:07 UTC, FatFatFat1 commented on code/modules/mob/living/carbon/human/death.dm
> +	log_admin("Pluvian [key_name(P)] went to heaven! [ADMIN_JMP(P)]")
done

2024-10-06 17:34 UTC, FatFatFat1 commented on code/modules/mob/living/carbon/human/death.dm
> +	var/area/heaven_tile = pick(get_area_turfs(get_area_by_type(/area/pluvia_heaven)))
done

2024-10-06 20:49 UTC, AirBlack commented
меня не устраивает работа ментейнеров, почему этот МР еще не смержен? вот сначала делают такие грубые ошибки как не мержить такой крутой ПР а потом жалуются что онлайн 2 тела

2024-10-11 13:17 UTC, volas commented on code/modules/religion/pluvia_heaven.dm
> +	desc = "����� �� ���."
В последних коммитах кажется везде была сломана кодировка для кириллицы

2024-10-11 15:04 UTC, WatlerJe approved these changes

2024-10-15 16:55 UTC, volas commented
Есть вещи, которые еще надо дорабатывать, но уже в мастере

2024-10-15 16:55 UTC, merged