Fix_Bamb
TauCetiStation/TauCetiClassic pull request #13369
Opened 2024-07-25 13:37 UTC by Risraivyn

## Описание изменений
Пофиксил баг #13216
## Почему и что этот ПР улучшит
Лазеры теперь снова могут рикошетить обратно в стреляющего. 
## Авторство
Risraivyn

## Чеинжлог
Лазеры снова могут отражаться.

:cl:  bugfix

2024-07-25 13:37 UTC, TauKitty commented
###### Changelog status: :x: Empty changelog (check markdown correctness)

2024-07-25 13:44 UTC, maleyvich commented
:cl: Risraivyn
- bugfix: Отражение лазеров происходило некорректно.

это в чейнжлог добавь

2024-07-25 13:49 UTC, maleyvich commented
в описание изменений вместо "Пофиксил баг https://github.com/TauCetiStation/TauCetiClassic/issues/13216"
"resolves Пофиксил баг https://github.com/TauCetiStation/TauCetiClassic/issues/13216"

2024-07-30 17:35 UTC, LudwigVonChesterfield commented on code/modules/projectiles/projectile.dm
> +	if((bumped && !forced) || (A == src))
нельзя выходит будет самого себя медиганом лечить.

2024-07-30 17:36 UTC, LudwigVonChesterfield requested changes

2024-07-30 17:36 UTC, LudwigVonChesterfield commented on code/game/gamemodes/modes_gameplays/blob/blobs/shield.dm
> +			P.redirect(new_x, new_y, curloc, src) //Stolen from armor' deflection
`/obj/item/projectile/proc/redirect(new_x, new_y, atom/starting_loc, mob/new_firer=null)`

четвёртый аргумент - моб, нельзя передавать `src`

2024-08-04 10:14 UTC, Risraivyn commented on code/modules/projectiles/projectile.dm
> +	if((bumped && !forced) || (A == src))
Проверил, медган работает как должен.

2024-08-04 10:15 UTC, Risraivyn commented on code/game/gamemodes/modes_gameplays/blob/blobs/shield.dm
> +			P.redirect(new_x, new_y, curloc, src) //Stolen from armor' deflection
Проблема, что новый стреляющий это не моб. Если это не передать, то выстрел остаётся за тем кто стрелял, а такой выстрел не может попасть в стреляющего.

2024-08-05 19:49 UTC, kalazus commented on code/game/gamemodes/modes_gameplays/blob/blobs/shield.dm
> +			P.redirect(new_x, new_y, curloc, src) //Stolen from armor' deflection
Это можно нормально сделать только через permutated (добавить firer в него, убрать проверку на firer в нахождении таргета бампа, и его Cut при редиректе).
P.s. а разве OV нормально не устанавливается у блоба? Достаточно без разницы если в себя нельзя будет попасть при мёртвом блобе.

2024-08-07 17:54 UTC, Risraivyn commented
Баг пофиксили #13428, остался только рантайм при отражении у мёртвого блоба.

2024-08-07 17:54 UTC, closed without merging