Теперь точно все щиты могут настривать ученые и инженеры
TauCetiStation/TauCetiClassic pull request #13368
Opened 2024-07-25 12:25 UTC by Riverz1

## Описание изменений
Щиты в изоляторе, почему-то работали от доступа ксенобиолога, я им поставил как и всем стандартным щитам доступ ученого и инженера
## Почему и что этот ПР улучшит
В большинстве своем изолятором пользуются для двух целей, это либо посадить туда генокрада, либо посадить генетически модефицированного человека и не одной из этих целей мы не можем сделать без капитана или РД, этот пр решает эту проблему и теперь по просьбе ученого он сможет активирывать эти щиты
## Авторство
Riverz

## Чеинжлог

:cl: Riverz
 - tweak: Теперь точно все щиты могут настривать ученые и инженеры

2024-07-25 21:22 UTC, KatoMarika requested changes
Необходимо обновить и на других картах.

2024-07-26 05:30 UTC, Riverz1 commented
> Необходимо обновить и на других картах. 

На других тоже такая хрень?

2024-07-26 05:31 UTC, KatoMarika commented
> На других тоже такая хрень?

Именно так.

2024-07-26 08:40 UTC, Riverz1 commented
> > На других тоже такая хрень?
> 
> Именно так. Подозреваю что маперы брали и напрямую копировали объекты с бокса или другой ранее созданной карты, но оно по всем картам идет.

поправил

2024-07-26 15:30 UTC, KatoMarika approved these changes

2024-07-30 07:20 UTC, merged