При гибе каждого питомца главы выпадает какой-то предмет
TauCetiStation/TauCetiClassic pull request #13381
Opened 2024-07-28 17:48 UTC by Riverz1

## Описание изменений
Теперь при гибе какого либо питомца выпадает предмет связанный с этим питомцем или с его хозяином
## Почему и что этот ПР улучшит
Больше интересных фич менее монотонный гемплей
## Авторство
Riverz

## Чеинжлог

:cl: Riverz
 -rscadd: При гибе каждого питомца главы выпадает какой-то интересный предмет.

2024-07-28 17:55 UTC, maleyvich requested changes
пр провоцирует на гриф в сторону животных и призы за это совсем какие-то смешные. кроме пета кэпа и гсб

2024-07-28 17:55 UTC, maleyvich commented on code/modules/mob/living/carbon/ian/ian.dm
> +	butcher_results = list(/obj/item/weapon/reagent_containers/food/snacks/meat/corgi/ian = 5, /obj/item/weapon/paper_bin = 1)
бесполезно

2024-07-28 17:55 UTC, maleyvich commented on code/modules/mob/living/simple_animal/friendly/cat.dm
> +	butcher_results = list(/obj/item/weapon/reagent_containers/food/snacks/meat = 2, /obj/item/clothing/mask/tie/collar = 1)
бесполезно

2024-07-28 17:55 UTC, maleyvich commented on code/modules/mob/living/simple_animal/friendly/corgi.dm
> +	butcher_results = list(/obj/item/weapon/gun/energy/gun = 1)
слишком если сравнивать с другими петами

2024-07-28 17:55 UTC, maleyvich commented on code/modules/mob/living/simple_animal/friendly/fox.dm
> +	butcher_results = list(/obj/item/weapon/reagent_containers/food/snacks/meat = 2, /obj/item/weapon/coin/gold = 1)
эт прикольно кстати, но я бы возможно дал монетку яну а лисе чёт другое

2024-07-28 17:55 UTC, maleyvich commented on code/modules/mob/living/simple_animal/friendly/robot.dm
> +	name = "DET5" //
зачем

2024-07-28 17:55 UTC, maleyvich commented on code/modules/mob/living/simple_animal/friendly/walle.dm
> +/mob/living/simple_animal/walle/death()
мать моя женщина что здесь происходит

2024-07-28 17:55 UTC, maleyvich commented on code/modules/mob/living/simple_animal/friendly/robot.dm
> +	butcher_results = list(/obj/item/device/science_tool = 1)
бесполезно

2024-07-28 18:17 UTC, Riverz1 commented
> пр провоцирует на гриф в сторону животных и призы за это совсем какие-то смешные. кроме пета кэпа и гсб

Ну если призы смешные то какой гриф? У тебя два аргумента противоречущие друг другу, т.е пр провоцирцет на гриф животных, но лута там нет поэтому это не интересно?

2024-07-28 18:20 UTC, Riverz1 commented on code/modules/mob/living/simple_animal/friendly/robot.dm
> +	name = "DET5" //
> зачем

Поправлю завтра

2024-07-28 18:50 UTC, Tobyyyan commented
Может дать шанс на спавн внутри Рено пару ТК? Там штучки 4 или 5, штобы лисичечку воровали особо желающие или просто триторы без ТК шли на условный риск

2024-07-28 18:59 UTC, Riverz1 commented
> Может дать шанс на спавн внутри Рено пару ТК? Там штучки 4 или 5, штобы лисичечку воровали особо желающие или просто триторы без ТК шли на условный риск

Ну это не слабо так баланс зацепит по сильнее егана

2024-07-28 19:41 UTC, Tobyyyan commented
> > Может дать шанс на спавн внутри Рено пару ТК? Там штучки 4 или 5, штобы лисичечку воровали особо желающие или просто триторы без ТК шли на условный риск
> 
> Ну это не слабо так баланс зацепит по сильнее егана
Это не новая идея для сс13, но для нашего сервера мб

2024-07-29 06:48 UTC, Riverz1 commented
Думаю я все же поменяю еган на пончик с розовой глазурью

2024-07-29 06:57 UTC, Riverz1 commented on code/modules/mob/living/simple_animal/friendly/walle.dm
> +/mob/living/simple_animal/walle/death()
А что не понтяно?

2024-07-29 07:08 UTC, Riverz1 commented
Поменял еган на пончик а также матер бин на документ CMF

2024-07-30 16:45 UTC, LudwigVonChesterfield commented on code/modules/mob/living/simple_animal/friendly/walle.dm
> +	return
```suggestion
```

2024-07-30 17:33 UTC, LudwigVonChesterfield commented
предметы какие-то неинтересные
а от того что Рено погибал в кабинете не пролили ни одной слезинки на моей памяти
в чем же тогда фича
где же тогда геймплей

2024-08-23 19:09 UTC, closed without merging