Космические торговцы, кратковременный [WIP]
TauCetiStation/TauCetiClassic pull request #13391
Opened 2024-07-29 19:51 UTC by Tap0r

## Описание изменений
Новый рандом ивент.
В одном из доков велосити появляются 3 гостроли космоторговцев: барыга, чоповец и таяран грузчик.
![2](https://github.com/user-attachments/assets/d1c58ec1-705f-4053-96bc-4eb76e007b0f)
В доке склад, на складе спавнятся всякие товары на продажу. Товары поделены на категории. Спавнится много всякого барахла и убер-шмотка/мех в количестве 2 штук, всё рандомно из заданного пула. Убер шмотки не могут повторяться. Среди барахла с маленьким шансом спавнится контрабанда. На шаттле есть тайник для контрабанды, который может открывать только барыга.
К доку пристыкован их шаттл - переделанный старый админский, которым щас уже забыли как пользоваться.
Цель шлеп компании заработать дохуя денег.
темка на форуме будет потом там подробнее постараюсь.

По коду:
- Добавлена новая фракция.
- Добавлены 3 новые роли и гостспавнеры для них.
- Добавлен текстовый файлик с именами для таярана, ибо они не должны выбирать себе имён во избежание брейнрота и мемов.
- Я не нашел нормальных инструментов для спавна из гостов не хуманов, поэтому налепил в спавнере таярана говна.
- Добавлены три новых оутфита.
- Добавлены две лэндмарки для спавна торговцев и их товара.
- Товар спавнится при создании фракции торговцев.
- Добавлена новая цель - заработать определённое количество кредитов. Как для роли так и для фракции.
- Новый доступ 74 - космоторговцы, их док и шаттл
- Новый рандом ивент.
- Шкаф тайник со спрайтом стены шаттла и проверкой на роль при попытке открыть.
- Добавлен подтип порталгана с загруженным в него ядром аномалии.

- [ ] Сделать консоль для полёта и добавить транзитную зону. 
- [ ] Расширить список возможных товаров, проставить там веса в пробах.
- [ ] Дооформить корабль и док.
- [ ] Дописать ролям приветственный текст и всякое что я скипнул.
- [ ] Вписать ивент в пулл доступных.
- [ ] Протестировать на локалке.
- [ ] На станциях подвигать зону этого шаттла в доках потому что шлюз сместился правее.
- [ ] Чето ещё хз пока.

## Почему и что этот ПР улучшит
ахуеть
## Авторство

## Чеинжлог
:cl:
 - add[link]: Космоторговцы начнут прилетать на станцию.

2024-07-29 19:51 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2024-07-29 20:01 UTC, DarkFurrSss commented
Мб дать им сильный дебафф за нахождение вне шаттла? Чтобы на станцию лишний раз не лазили (Таяре оставить возможность бегать)

2024-07-29 20:03 UTC, Tap0r commented
> Мб дать им сильный дебафф за нахождение вне шаттла? Чтобы на станцию лишний раз не лазили (Таяре оставить возможность бегать)

нет пусть бегают, жрать то им что-то надо. и в идеале по моей задумке они не только торговать должны, но ещё и наниматься за деньги, в супер идеале не только станцией, но и антагами.

2024-07-30 06:59 UTC, TheLone1y commented
О-о-о, а ты видел торговцев с Оникса? Там интересный концепт что они как второе карго, но могут продавать и органы и людей, делать закупки в собственной консоли которая спавнит шмотки сразу и имеют цельку на N-тысяч таллеров (валюты). А так очень круто!

2024-07-30 19:02 UTC, TauKitty commented
Этот запрос на слияние был упомянут в **Tau Ceti Station Forum**. Там могут быть соответствующие подробности:

https://forum.taucetistation.org/t/kosmotorgovczy-novyj-random-ivent/43378/1

2024-08-02 08:10 UTC, Tap0r commented
должно быть готово

2024-08-02 13:27 UTC, LudwigVonChesterfield commented on code/datums/spawners_menu/spawners.dm
> +		to_chat(spectator, "<span class='warning'>Вы не можете играть за таярана.</span>")
может произойти грустная ситуация где из-за этого не будет портера вообще.

2024-08-02 13:28 UTC, LudwigVonChesterfield commented on code/game/gamemodes/factions/space_traders.dm
> +	return pick(
переделай на pickweighted(list()) пж

2024-08-02 13:30 UTC, LudwigVonChesterfield commented on code/game/machinery/computer/trader_shuttle.dm
> +	sleep(PARALLAX_LOOP_TIME)
в оглавлении функции нужен `set waitfor = FALSE` после слипа надо проверять ВСЁ. существование консоли, существование параллакса, и т.д.

2024-08-02 13:30 UTC, LudwigVonChesterfield commented on code/game/machinery/computer/trader_shuttle.dm
> +	sleep(PARALLAX_LOOP_TIME)
в оглавлении функции нужен `set waitfor = FALSE` после слипа надо проверять ВСЁ. существование консоли, существование параллакса, и т.д.

2024-08-02 13:32 UTC, LudwigVonChesterfield commented on code/game/objects/random/random_trader_product.dm
> +	return pick(\
надо переделать на pickweighted

2024-08-02 13:32 UTC, LudwigVonChesterfield commented on code/game/objects/random/random_trader_product.dm
> +/obj/random/trader_product/rnd
в какой момент проще просто заспавнить пару мусорных куч для антуража.

2024-08-02 13:44 UTC, KatoMarika commented
Плюсом к тому что кинул в дискорде. 

https://github.com/TauCetiStation/TauCetiClassic/pull/13395/files
Возможно стоит поменять местами как выше 
	C.create_human_apperance(H)
	H.key = C.key
Плюс мне на тесте выпал спейсбайк и он явно ведет себя не нормально - с него можно слезть не слезая с него и парить выше остальных кукол. Может стоит удалить его? 

А еще я и пара людей слепые и не смогли увидеть ящик в стене, может стоит как-то обозначить более очевидно?

2024-08-02 13:54 UTC, Tap0r commented
> А еще я и пара людей слепые и не смогли увидеть ящик в стене, может стоит как-то обозначить более очевидно?

это супер тайный супер тайник для контрабанды и супер плохих вещей. и барыге в приветствии супер чётко написано где он находится, справа от постера, постер в трюме сука один

2024-08-02 13:55 UTC, KatoMarika commented
> это супер тайный супер тайник для контрабанды и супер плохих вещей. и барыге в приветствии супер чётко написано где он находится, справа от постера, постер в трюме сука один его и не должно быть видно
А, ок

2024-08-02 18:02 UTC, Tap0r commented on code/game/objects/random/random_trader_product.dm
> +	return pick(\
pickweight правильно
я из-за тебя чуть свой pickweighted писать не начал.

2024-08-02 18:17 UTC, Tap0r commented
поправил зоны на картах.
добавил в спавнер форсмув
переделал всё на пиквейгхт
добавил сэт вэйт фор фолс и проверку на существование консоли (проверять существование зоны я э хз короче)
убрал космобайк((((((((((((((

2024-08-02 23:57 UTC, KatoMarika requested changes
Прометей: не открываются с болтов двери 
![image](https://github.com/user-attachments/assets/368e2c0e-8093-4f9a-ae02-5d41c01c1650)

Фалькон.  На новом доке необходимо: 
- Добавить лампы, очень темно.
- При стыковке не снимаются болты с дверей. 
- Трубы к одному виду, там у тебя x-образная скрытая, остальные видимые. Лишняя пайпа под выходом. 
- Двери шлюза перепутаны. 

Спавнеры: 
	H.key = C.key
	C.create_human_apperance(H)
	H.forceMove(spawnloc)

Возможно стоит добавить побольше еды на шатл барыги. 
И может сделать эмбиент на постоянку? А то сейчас зашел-вышел и он пропал.

2024-08-03 05:08 UTC, Tap0r commented
> Прометей: не открываются с болтов двери 
> ![image](https://github.com/user-attachments/assets/368e2c0e-8093-4f9a-ae02-5d41c01c1650)
> 
> Фалькон.  На новом доке необходимо: 
> - Добавить лампы, очень темно.
> - При стыковке не снимаются болты с дверей. 
> - Трубы к одному виду, там у тебя x-образная скрытая, остальные видимые. Лишняя пайпа под выходом. 
> - Двери шлюза перепутаны. 
> 
> Спавнеры: 
> 	H.key = C.key
> 	C.create_human_apperance(H)
> 	H.forceMove(spawnloc)
> 
> Возможно стоит добавить побольше еды на шатл барыги. 
> И может сделать эмбиент на постоянку? А то сейчас зашел-вышел и он пропал. 

там просто на шлюзы док тэги забыл проставить. еды им не нужно, пусть на станции её добывают. эмбиент чтобы на постоянку это надо несколько тречков тогда, а иначе заебёт.

2024-08-03 05:15 UTC, Tap0r commented
> Спавнеры:
> H.key = C.key
> C.create_human_apperance(H)
> H.forceMove(spawnloc)

????????????????????

2024-08-03 08:29 UTC, KatoMarika commented
> > Спавнеры:
> > H.key = C.key
> > C.create_human_apperance(H)
> > H.forceMove(spawnloc)
> 
> ????????????????????

У тебя 
C.create_human_apperance(H)
H.key = C.key
H.forceMove(spawnloc)

Сделай как выше написал, нужно для нормальной работы эмбиента, я когда в спавнеры лазил выяснилось что так нужно. 
[Шеф сказал так делать](https://discord.com/channels/401030271417188353/401031448963973120/1267589774361759834)

2024-08-03 08:35 UTC, KatoMarika commented
![image](https://github.com/user-attachments/assets/c803419c-6847-41cb-9c54-9d3443661e09)

2024-08-03 08:42 UTC, Tap0r commented
> > > Спавнеры:
> > > H.key = C.key
> > > C.create_human_apperance(H)
> > > H.forceMove(spawnloc)
> > 
> > ????????????????????
> 
> У тебя 
> C.create_human_apperance(H)
> H.key = C.key
> H.forceMove(spawnloc)
> 
> Сделай как выше написал, нужно для нормальной работы эмбиента, я когда в спавнеры лазил выяснилось что так нужно. 
> [Шеф сказал так делать](https://discord.com/channels/401030271417188353/401031448963973120/1267589774361759834)

я сделал как шэф сказал и как в твоём пре всё але

2024-08-03 08:43 UTC, Tap0r commented
> ![image](https://github.com/user-attachments/assets/c803419c-6847-41cb-9c54-9d3443661e09)
> 
ватафак куда он пропал

2024-08-03 08:43 UTC, KatoMarika commented
> ватафак куда он пропал
Никуда, там труба под ним лишняя

2024-08-03 08:47 UTC, KatoMarika commented
> я сделал как волес сказал и как в твоём пре всё але

Порядок другой, поменяй местами. Сперва присвоение сикея, потом уже создание куклы и потом форс мув. 
А у тебя создание куклы, присвоение сикея и форсмув

2024-08-03 10:50 UTC, Tap0r commented
> Порядок другой

![maxresdefault-2472513864.jpg](https://github.com/user-attachments/assets/5bce3b29-385c-4a3c-9719-49a14b2842b9)

да как другой ты свой пр открой посмотри или забыл уже что писал

2024-08-03 11:02 UTC, KatoMarika commented
Ладно я дегрод простите.

2024-08-03 17:56 UTC, KatoMarika approved these changes
Спорное что осталось - мусоросброс на Гамме попадает в шатл если он пристыкован, но думаю это не столь критично

2024-08-04 18:27 UTC, KatoMarika approved these changes

2024-08-07 14:48 UTC, LudwigVonChesterfield approved these changes
Воласа дёрнуло из-за конфига таярских имян как я понимаю.

С остальным хорошо.

2024-08-09 15:17 UTC, Tap0r commented on code/modules/admin/admin.dm
> -
консоль неразрушимая, даже если умудрятся её сломать, админ может её заспавнить прост, она будет работать

2024-08-09 15:28 UTC, Tap0r commented
поглядел диф, поправил всякое, как будто бы готово

2024-08-09 16:03 UTC, KatoMarika approved these changes

2024-08-15 09:44 UTC, volas commented on code/datums/spawners_menu/spawners.dm
> +*/
```suggestion
```

2024-08-15 09:47 UTC, volas commented on code/game/area/shuttle_areas.dm
> +/area/shuttle/trader
в идеале бы оставить оба шаттла, и просто маплоадером нужный загружать, но так тоже ок. Но нужно проверить, чтоб там не было доступа с ангара в остальной центкомм, то место всегда было для админ щитспавна и рандомные игроки не предполагались.

2024-08-15 09:54 UTC, volas commented on code/game/objects/items/stacks/sheets/mineral.dm
> +/obj/item/stack/sheet/mineral/diamond/twenty
это не будет корректно работать (я тоже спотыкался), где-то у нас стеки проверяются строго по типу, и вообще как subtypesof() потом вроде где-то может вылезти

2024-08-15 09:58 UTC, volas commented on code/game/gamemodes/factions/space_traders.dm
> +	create_products()
Семантически было бы лучше тут оставить только определение фракции, а всякий механ ивента вынести в соответствующий датум ивента. Фракция будет независима и так можно будет использовать где-то еще, если потребуется.

2024-08-15 09:59 UTC, Tap0r commented on code/game/area/shuttle_areas.dm
> +/area/shuttle/trader
> в идеале бы оставить оба шаттла, и просто маплоадером нужный загружать, но так тоже ок. Но нужно проверить, чтоб там не было доступа с ангара в остальной центкомм, то место всегда было для админ щитспавна и рандомные игроки не предполагались.

я этот шаттл просто в космос вынес

2024-08-15 10:03 UTC, volas commented on config/names/tajaran_male_first.txt
> +Bakhidj
мне надоело, и я сейчас вынесу имена из конфигов. Я не представляю, зачем нам возможность конфигурировать имена для каждого отдельного сервера, но это требует от меня отдельных телодвижений помноженных на количество измененных файлов имент и помноженных на количество работающих серверов.

2024-08-15 10:20 UTC, volas commented on config/names/tajaran_male_first.txt
> +Bakhidj
потом просьба перенести в ``static/names/`` в соответствии с https://github.com/TauCetiStation/TauCetiClassic/pull/13474

2024-08-18 15:19 UTC, Tap0r commented
Всё сделал

2024-08-25 01:05 UTC, KatoMarika approved these changes
Давайте уже смержим и будем делать деньги.
Плюс из-за этого ПРа не трогаю плитку бокса что бы не плодить конфликты.

2024-09-02 05:37 UTC, Tap0r commented
уээээээээ

2024-09-02 23:27 UTC, KIBORG04 commented on code/game/gamemodes/objectives/traders_objectives.dm
> +	while(item_name1 == item_name2)
```suggestion
	var/indx = rand(1, possible_items.len)
	var/offset = rand(1, possible_items.len -1) // -1, чтобы не вступить в тот же элемент
	var/new_indx = (indx + offset) % L.len
	item_name1 = possible_items[indx]
	item_name2 =  possible_items[new_indx == 0 ? possible_items.len : new_indx] // этот финт, потому что в бъонде листы начинаются с 1
```

Предлагаю варианты поэлегантнее:

2024-09-02 23:28 UTC, KIBORG04 commented on code/game/gamemodes/objectives/traders_objectives.dm
> +	while(item_name1 == item_name2)
Пруф, что при всех комбинациях не буде повторки
![image](https://github.com/user-attachments/assets/074a7eba-8486-46b5-81f2-851615f5fc72)

2024-09-02 23:30 UTC, KIBORG04 commented on code/game/gamemodes/objectives/traders_objectives.dm
> +	return OBJECTIVE_LOSS
```suggestion
/datum/objective/trader_purchase/check_completion()
	var/list/areas = list(/area/shuttle/trader/space, /area/shuttle/trader/station)
	for(var/type in areas)
		for(var/obj/O in get_area_by_type(type))
			if(istype(O, possible_items[item_name1]) && istype(O, possible_items[item_name2]))
				return OBJECTIVE_WIN
			if(istype(O, possible_items[item_name1]) || istype(O, possible_items[item_name2]))
				return OBJECTIVE_HALFWIN
			return OBJECTIVE_LOSS
```
Если будет лежать на шаттле 2 эмиттера, то челы победят, ни смотря на необходимость во втором айтмеме же.

2024-09-02 23:40 UTC, KIBORG04 commented on code/game/machinery/computer/trader_shuttle.dm
> +	if(src) docked = TRUE
```suggestion
/obj/machinery/computer/trader_shuttle/proc/dock_to_station()
	set waitfor = FALSE
	space_location.parallax_slowdown()
	sleep(PARALLAX_LOOP_TIME)
	if(!src) 
		return
	SSshuttle.clean_arriving_area(station_location)
	space_location.move_contents_to(station_location)
	SSshuttle.shake_mobs_in_area(station_location, WEST)

	SSshuttle.dock_act(/area/station/hallway/secondary/entry, "trader_shuttle")
	SSshuttle.dock_act(station_location, "trader_shuttle")

	docked = TRUE

/obj/machinery/computer/trader_shuttle/proc/undock_to_station()
	set waitfor = FALSE
	SSshuttle.undock_act(/area/station/hallway/secondary/entry, "trader_shuttle")
	SSshuttle.undock_act(station_location, "trader_shuttle")
	sleep(PARALLAX_LOOP_TIME)
	if(!src) 
		return

	space_location.parallax_movedir = EAST
	station_location.move_contents_to(space_location)
	SSshuttle.shake_mobs_in_area(space_location, WEST)

	docked = TRUE
```
А людук попросил!

2024-09-02 23:45 UTC, KIBORG04 commented on code/game/gamemodes/roles/space_trader.dm
> +/datum/role/space_trader/dealer
Проставь этим челам свои айдишники, нейм как хочешь можешь трогать. ID'шник типа должен быть у каждой рольки свой для корректности

2024-09-02 23:47 UTC, KIBORG04 commented on code/modules/locations/shuttles/closet.dm
> +	if(!isrolebytype(/datum/role/space_trader/dealer, user)) // only dealer can open this
Если обновишь айдишник, то замени проверку по типу на `isrole(DEALER, user)` например.

2024-09-14 11:26 UTC, Tap0r commented on code/game/machinery/computer/trader_shuttle.dm
> +	if(src) docked = TRUE
так всё норм же, консоль если удалится шаттл всё равно полетит, просто обращения к самой консоли не будет. Не вижу смысла на самом деле в этом всём особого когда она индестрактибл и ее только алень на админе делитнуть может

2024-09-14 11:58 UTC, Tap0r commented on code/game/gamemodes/roles/space_trader.dm
> +/datum/role/space_trader/dealer
они по факту одна роль, просто с разным аутфитом и деталями, админам ни к чему в сетролес выбор из 4 торговцев, которые отличаются ток надписью в чате (пост сетап то не прокнет)

2024-09-14 11:59 UTC, Tap0r commented on code/modules/locations/shuttles/closet.dm
> +	if(!isrolebytype(/datum/role/space_trader/dealer, user)) // only dealer can open this
подумал и заменил проверку вообще, теперь все торговцы могут открывать тайник

2024-09-14 12:17 UTC, Tap0r commented on code/game/gamemodes/roles/space_trader.dm
> +/datum/role/space_trader/dealer
а не, пост сетап прокает, надо тогда в спавнер всё же вынести его

2024-09-14 18:33 UTC, Tap0r commented
Короче пофиксил конфликты. Переделал проверку цели, должно быть норм. Убрал отдельные роли, они все теперь космоторговцы, а их оутфиты и все различия переложил в спавнеры. Теперь если человеку заходящему за грузчика недоступны таяры он заспавнится человеком. Пофиксил ластмув у шаттла, он без кд работал. Тайник могут открывать все торговцы. А и музыку поменял там чето кринж был, но и щас не прям чтобы круто, но получше

2024-09-14 19:10 UTC, KIBORG04 commented on code/game/gamemodes/objectives/traders_objectives.dm
> +	var/offset = rand(1, possible_items.len -1) // -1, чтобы не вступить в тот же элемент
```suggestion
	var/offset = rand(1, possible_items.len - 1)
```
я для тебя комменты писал

2024-09-14 19:12 UTC, KIBORG04 commented on code/game/machinery/computer/trader_shuttle.dm
> +		if(is_centcom_level(src.z))
```suggestion
		if(is_centcom_level(z))
			dat += "<ul><li>Местоположение: <b>Космос</b></li>"
			dat += "</ul>"
			dat += "<a href='?src=\ref[src];station=1'>Пристыковаться к станции</a>"
		else
			dat += "<ul><li>Местоположение: <b>[station_name_ru()]</b></li>"
			dat += "</ul>"
			dat += "<a href='?src=\ref[src];space=1'>Начать процедуру отстыковки</a>"
	else
		if(is_centcom_level(z))
```

2024-09-14 19:18 UTC, KatoMarika requested changes
![image](https://github.com/user-attachments/assets/dadf57de-6d35-43fb-accd-58aca28ad575)

Boxstation. 
Просьба вернуть гридку, у тебя тут по сути откат изменений. Которые сделал Аззи когда шатал Бокс. 
![image](https://github.com/user-attachments/assets/89f8cc45-9a09-4785-9792-4fd9e36be41c)

2024-09-14 19:31 UTC, Tap0r commented
грiдка
нахуя она там нужна ещё раз

2024-09-14 19:51 UTC, KatoMarika commented
Это другой вопрос, но стандарт Бокса сделан так.

2024-09-14 20:21 UTC, Tap0r commented
> Это другой вопрос, но стандарт Бокса сделан так. 

да я то сделаю, ток вопрос остаётся открытым

2024-09-15 01:10 UTC, KatoMarika commented
> да я то сделаю, ток вопрос остаётся открытым

Мы вроде обсуждали это, но лан: 
Использование новых спрайтов пола.
Визуализация технического помещения, которое предполагает стыковку с шатлами. 
За другими подробностями к @AzzyDreemurr13

2024-09-15 07:32 UTC, Tap0r commented
> Визуализация технического помещения, которое предполагает стыковку с шатлами.

![image](https://github.com/user-attachments/assets/8d039f83-4ef0-41d1-a696-17614595c89d)
техническое помещение, проверяем)))

2024-09-15 12:15 UTC, Tap0r commented
красивый скрин с дедспайса, только вот

![image](https://github.com/user-attachments/assets/f3cf6440-ce40-4020-b1f2-7d291102fb70)

буквально от пизды в доки кинули хуйню просто потому что и пытаетесь оправдать, было бы это нормальным редизайном доков вопросов было бы ноль, но в текущем виде это кринж и я бы предпочел старый вариант, прикол решеток что под ними видны коммуникации, которые в доках не используются. 

Шлюзы для выхода в космос единственные смотрятся с гридами хорошо из-за труб

2024-09-15 16:19 UTC, KatoMarika approved these changes

2024-09-17 03:58 UTC, volas commented
я просто мимо проходил но еще раз скажу, что твои описания пр-ов не информативны, не надо перечислять там изменения в коде - их и так в diff-е видно, лучше по человечески распиши что добавлено. Новый ивент такой то, делает то-то

2024-09-21 18:48 UTC, simb11 commented
на дельте (и возможно других картах) кораблик торговец не может пристыковаться к станции

2024-09-24 04:47 UTC, volas approved these changes

2024-09-29 04:30 UTC, merged