возвращение передачек в общак бокса
TauCetiStation/TauCetiClassic pull request #13415
Opened 2024-08-02 06:31 UTC by maleyvich

## Описание изменений
теперь можно будет делать передачки в общак через ресепшн брига, теперь на створках стоит доступ...
![image](https://github.com/user-attachments/assets/e388721c-5ed9-4cc4-b42a-68de5b746784)

## Почему и что этот ПР улучшит
возвращение старых приколов
## Авторство
я

## Чеинжлог
:cl: maleyvich
- map: На "Исходе" теперь возможно делать передачи заключённым!

2024-08-02 06:31 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2024-08-02 07:04 UTC, Deahaka commented
Ресепшн очень не красивый, я бы советовал переделать. Посмотри как это выглядело до репапа лексакра. Пространства должно быть ну минимум 2 на 2

2024-08-02 07:27 UTC, UDaV73rus commented
мне кажется или реально предмет до мусорки не долетит..

2024-08-02 10:58 UTC, Tap0r approved these changes
малевич стартует маперскую карьеру с мега хайпа.
хоть это и бокс, но ладно пох
под мусоркой труба вроде есть, пойдёт короче

2024-08-02 13:26 UTC, LudwigVonChesterfield approved these changes

2024-08-03 00:21 UTC, QWxiZ commented
на створках перед мусоркой не проставлен доступ, люди по приколу будут закидывать кучу говна в общак просто потому что могут; переставить бы мусорку так, чтобы хотя бы пришлось перелазить через створку. вытаскивать людей из тюрьмы сейчас и так проще простого на самом деле.

2024-08-03 00:35 UTC, KatoMarika approved these changes

2024-08-03 11:00 UTC, arygal commented
Кароче заходишь на вардена, расстреливаешь выход трубы. И все дурачики и передачки улетают в нулспейс.

2024-08-04 19:15 UTC, Chip11-n approved these changes
Меня смущает тот момент, что труба идет не как воздуховод, через вход для сб, а через другую камеру.

Если исправишь - круто, нет - мержу в течении суток.

2024-08-05 04:08 UTC, maleyvich commented
> Меня смущает тот момент, что труба идет не как воздуховод, через вход для сб, а через другую камеру.
> 
> Если исправишь - круто, нет - мержу в течении суток.

сделано

2024-08-05 08:18 UTC, KatoMarika requested changes
![image](https://github.com/user-attachments/assets/4e47898d-d57c-40f5-bf0a-2619d8c76991)

2024-08-05 14:05 UTC, KatoMarika approved these changes

2024-08-06 07:45 UTC, merged

2024-09-10 14:57 UTC, TauKitty commented
Этот запрос на слияние был упомянут в **Tau Ceti Station Forum**. Там могут быть соответствующие подробности:

https://forum.taucetistation.org/t/obsuzhdenie-novaya-minornaya-rol-v-kazhdom-raunde/42141/32