Половинки таблеток теперь соединяемы и реагенты внутри не взаимодействуют.
TauCetiStation/TauCetiClassic pull request #13427
Opened 2024-08-04 22:56 UTC by Gort133

## Описание изменений
Разломаные пополам таблетки теперь можно снова соединить.
Регаенты в таблетках не взаимодейстуют друг с другом до момента растворения где-либо.
## Почему и что этот ПР улучшит
Можно будет делать таблетки с эффектами. Не придется использовать для этого две таблетки\половинки таблеток отдельно.
## Авторство
Я

## Чеинжлог
:cl: Gort133
 - add: Половинки таблеток теперь можно соединить обратно
 - add: Химикаты в таблетках не вступают в реакцию

2024-08-04 22:56 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2024-08-04 22:59 UTC, Gort133 commented
рукожопно насрал комитами

2024-08-05 11:11 UTC, ArthurPhilipDent42 commented
Шо, теперь можно вотерпотасиум в таблетка выписывать? :pekapled:

2024-08-06 21:55 UTC, Gort133 commented
![076b7ab46473b2cc2725f039a6dfb8bfbafdc5b5](https://github.com/user-attachments/assets/df75a004-ff88-4dff-bba0-12ebc5deeaae)
 ПР дизлайкнут людуком так что поплачем об этом

2024-08-07 07:47 UTC, TheLone1y commented
Это как полублоки в майнкрафте втф

2024-08-07 17:29 UTC, volas requested changes

2024-08-07 17:29 UTC, volas commented on code/modules/reagents/reagent_containers/pill.dm
> +	flags = NOREACT
это позволит сразу делать таблетки с каким угодно контентом.

наверно лучше сделать сабтип pill/halfunited (название своё придумай), который будет создаваться именно объединением половинок и никак иначе, и будет из коробки NOREACT. 

Еще наверно ему надо будет выключать NOREACT обратно в каких-то случаях, если их опять разломили например.

2024-08-07 18:12 UTC, Pivo24 commented
А что будет если я соединю две половинки и потом введу туда скажем реагенты для нитроглицерина

А что будет если я соединю две половинки одной таблетки - ноу реакт таблетка диловена получится?

2024-08-07 18:21 UTC, Gort133 commented
Вы все очень правы, завтра сделаемс

2024-08-08 10:26 UTC, Gort133 commented
сделал как просили, но я не знаю когда кроме разделения таблетки стоит убирать ноу реакт
Только если в капельнице, но у меня из идей лишь это:

2024-08-08 18:04 UTC, volas commented on code/game/machinery/iv_drip.dm
> +			W.flags = null
```suggestion
			W.flags &= ~NOREACT
```

выключает целенаправленно флаг, вместо полного сброса

2024-08-08 18:04 UTC, volas commented on code/modules/reagents/reagent_containers/pill.dm
> +	flags = NOREACT
```suggestion
/obj/item/weapon/reagent_containers/pill/twopart
	flags = NOREACT

```

просто отступ

2024-08-08 18:06 UTC, volas commented on code/modules/reagents/reagent_containers/pill.dm
> +	if(istype(W, /obj/item/weapon/pen))
их раньше нельзя было переименовывать разве?

2024-08-08 18:14 UTC, Gort133 commented on code/modules/reagents/reagent_containers/pill.dm
> +	if(istype(W, /obj/item/weapon/pen))
только в химмастере при создании

2024-08-09 03:26 UTC, volas commented on code/modules/reagents/reagent_containers/pill.dm
> +	if(istype(W, /obj/item/weapon/pen))
добавь return-ы в конце каждой if, и дефолтный вызов родителя ``..()`` в конце, в остальном вроде ок

2024-08-09 03:28 UTC, volas commented on code/modules/reagents/reagent_containers/pill.dm
> +	flags = null
```suggestion
	// reset flags and call reaction for pill/twopart pills
	flags &= ~NOREACT
```
аналогично как выше писал, еще комментарий объясняющий почему это надо

2024-08-09 15:46 UTC, Gort133 commented
Надеюсь правильно понял
Мой второй ПР в принципе для сс13 
В своём ретурны поставил в старом ничего не трогал и не надо наверное???

2024-08-11 12:24 UTC, Gort133 commented
![48c6714146618a68037becfa59aaf0c96077f99b (1)](https://github.com/user-attachments/assets/18433980-a6e6-4437-87fd-ffb44d228ee7)
Делаю все возможное чтоб не было плашки застоявшегося пра

2024-08-11 12:39 UTC, volas commented on code/modules/reagents/reagent_containers/pill.dm
> +		name = new_name
```suggestion
		name = new_name
		return
```

2024-08-11 12:39 UTC, volas approved these changes
выше последнее замечание

2024-08-11 23:54 UTC, merged

2024-08-11 23:56 UTC, volas commented
немного поздно, но можно еще было бы добавить автоматическую генерацию имени/описания у объединенной таблетки на основе половинок, чтоб не переименовывать их в ручную.

2025-02-25 10:05 UTC, TauKitty commented
Этот запрос на слияние был упомянут в **Tau Ceti Station Forum**. Там могут быть соответствующие подробности:

https://forum.taucetistation.org/t/fludilka-chast-2/28659/42063