доукрепляем отсеки на боксе
TauCetiStation/TauCetiClassic pull request #13425
Opened 2024-08-04 07:11 UTC by maleyvich

## Описание изменений
добавлены укрепстенки для кабинета рд со стороны склада токсинной
![image](https://github.com/user-attachments/assets/855e082f-654c-40ea-a5dc-fa5b0ebe381d)
добавлены укрепстенки для брига со стороны космоса
![image](https://github.com/user-attachments/assets/61877089-972f-44dc-9585-940080dcda2d)
## Почему и что этот ПР улучшит
мне кажется логичным поставить укрепстенки в этих местах, это ВОЗМОЖНО усложнит раш нюкеров через бриг и теперь кабинет рд не будет страдать от взрывов бомбы в складе токсинной (сомневаюсь что это так надо)
## Авторство
я

## Чеинжлог
:cl: maleyvich
- map: Бриг и кабинет РД "Исходе" стали более укрепленными.

2024-08-04 07:11 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2024-08-04 07:45 UTC, DarkFurrSss commented
Тут дырка остаётся ![Screenshot_2024-08-04-12-44-13-684_com.mi.globalbrowser-edit.jpg](https://github.com/user-attachments/assets/bb722590-453d-4583-a9fa-b38f8b26a1bc)

2024-08-04 18:39 UTC, KatoMarika requested changes
https://github.com/TauCetiStation/TauCetiClassic/pull/13425#issuecomment-2267403148
Указали верно, требуется и тут.

2024-08-05 04:06 UTC, maleyvich commented
исправлено

2024-08-05 07:50 UTC, KatoMarika approved these changes

2024-08-15 09:38 UTC, volas commented
кабинет рд могу понять, бриг спорно

2024-08-15 09:42 UTC, KatoMarika commented
Я при апруве глядел на то, что антаги через окно чаще заходят, те стены никто особо и не трогает. И со стороны станции ту стенку тоже никто не трогает вообще.

2024-08-15 10:20 UTC, Deahaka commented
Ахахаха, кого кого останавливают укреп стенки у брига???))) Нюкеров?))) у которых по 30 с4 за 10 ТК?

2024-08-16 11:58 UTC, KIBORG04 approved these changes
Пусть

2024-08-18 05:30 UTC, volas commented
Ну пусть, но если у кого будет аргументация против укрепок - мы можем принять откат.

Некоторые места сознательно не защищены по соображениям геймплея, если бы мы хотели станцию сделать неуязвимой то ставили бы укрепки всюду а то и в несколько слоёв.

2024-08-18 05:30 UTC, merged