[WiP] Ротация отделов на боксе
TauCetiStation/TauCetiClassic pull request #13426
Opened 2024-08-04 08:20 UTC by maleyvich

## Описание изменений
Исход слегка поменялся...
![image](https://github.com/user-attachments/assets/9672889e-0070-494a-81af-0e29c58254b2)
![image](https://github.com/user-attachments/assets/fc940df5-c478-428d-9e57-303c0cc3bd14)
![image](https://github.com/user-attachments/assets/15248f44-af4d-4098-b770-37d1193c0912)

## Почему и что этот ПР улучшит
делаем бокс более интересным и меняющимся, надеюсь хоть кому-то кроме меня надоело бегать по одним и тем же зонам (а кроме бокса редко что пикают!)
## Авторство
я

## Чеинжлог
-map[link]: На КСН "Исход" произошла значительная ротация отделов.

2024-08-04 08:20 UTC, TauKitty commented
###### Changelog status: :radio_button: No changelog

2024-08-04 08:25 UTC, DarthSidiousPalpatine commented
Скрины не внушают оптимизма, у тебя трубы не подсоединены и пр.

2024-08-04 11:13 UTC, maleyvich commented
пофиксил  вроде бы все висящие камеры, пододвинул кабинет авд чтоб не высовывалось слишком сильно в коридор

2024-08-04 11:55 UTC, Naroke commented
Перенеси барбера к меду, пожалуйста.

2024-08-04 13:58 UTC, maleyvich commented
ПР был обновлен. Из важных изменений:
удалена старая ботаника (теперь парихмахерская на его вместе)
вместо кабинета авд теперь комната для свиданий, где зеки смогут поболтать со своими друзьями более легально.

2024-08-04 13:59 UTC, maleyvich commented
Вроде бы, все важные проблемы устранены. Убираю с драфта

2024-08-04 14:26 UTC, Kaskardness commented
Не удаляй ботанику в техах, а лучше расширь эту комнату и перенеси сюда
![image](https://github.com/user-attachments/assets/0972b71d-5947-4ce3-a798-c3ce9ae56bc8)

2024-08-04 14:49 UTC, maleyvich commented
Вернул старую ботанику.

2024-08-04 14:59 UTC, Slegarrr commented
> Вернул старую ботанику.

Она стала больше, но функционально - хуже. В каждой тех. тоннельной ботанике есть умывальник, для набора воды и полноценной работы

2024-08-04 14:59 UTC, maleyvich commented
> Она стала больше, но функционально - хуже. В каждой тех. тоннельной ботанике есть умывальник, для набора воды и полноценной работы

есть вотертанк и мне кажется его хватит.

2024-08-04 15:01 UTC, Slegarrr commented
> > Она стала больше, но функционально - хуже. В каждой тех. тоннельной ботанике есть умывальник, для набора воды и полноценной работы
> 
> есть вотертанк и мне кажется его хватит.

Вотертанк это 13 вёдер воды, почему тебя надо убеждать добавлять то, что было изначально. Хотя ты это выставляешь как ротацию, а не выпил обьектов?

2024-08-04 15:05 UTC, maleyvich commented
> Вотертанк это 13 вёдер воды, почему тебя надо убеждать добавлять то, что было изначально. Хотя ты это выставляешь как ротацию, а не выпил обьектов?

найдёшь еще вотертанков, почему ты считаешь что подпольное производство должно быть простым??? 
вопрос больше не считаю нужным обсуждать.

2024-08-04 15:22 UTC, Slegarrr commented
> > Вотертанк это 13 вёдер воды, почему тебя надо убеждать добавлять то, что было изначально. Хотя ты это выставляешь как ротацию, а не выпил обьектов?
> 
> найдёшь еще вотертанков, почему ты считаешь что подпольное производство должно быть простым??? вопрос больше не считаю нужным обсуждать.

Да нет , братишка. Если спамишь своими пр-ами в раунде, будь добр - отвечай на вопросы. Я не понимаю какие проблемы решает или как дополняет геймплей подпольное выращивания без воды, которое вообще фиг пойми почему каснулось твоя ротация

2024-08-04 16:02 UTC, Slegarrr commented
Забавно что мне кто-то ставит палец вниз и что-то доказывают про вотертанки, когда у нас есть аспект, когда на станции вообще нету вотертанков. Просто разумисты

2024-08-04 16:09 UTC, Naroke commented
> Забавно что мне кто-то ставит палец вниз и что-то доказывают про вотертанки, когда у нас есть аспект, когда на станции вообще нету вотертанков. Просто разумисты

А ещё у нас есть аспект, когда все раковины и душевые лопаются, что ведёт за собой массовый потоп всей станции

2024-08-04 16:09 UTC, maleyvich commented
> Забавно что мне кто-то ставит палец вниз и что-то доказывают про вотертанки, когда у нас есть аспект, когда на станции вообще нету вотертанков. Просто разумисты

 лан уговорил заменил на раковину

2024-08-04 16:55 UTC, KatoMarika requested changes
<details><summary>Проблемы</summary>
<p>

В новой старой ботанике необходимо удалить из стенок решетки.
![image](https://github.com/user-attachments/assets/379d1c3d-70ee-4afb-a029-62064af15979)

Барбер потерял зону, нет АПЦ, нет проводки. Раковина.
![image](https://github.com/user-attachments/assets/10989132-dc4f-4c61-b192-39236d869253)

Капитан отключен от атмоса
![image](https://github.com/user-attachments/assets/72b84cac-9d92-420c-b3fe-2b2f21de6743)

БЩ двойной скраббер зачем-то в задней комнате.
![image](https://github.com/user-attachments/assets/9899deca-6efc-45de-aaeb-294c359b36ed)

Куда ведет мусорка, зачем под дверью остатки труб? Куда ведет проводка из офиса БШ?
![image](https://github.com/user-attachments/assets/36e7e476-542e-4455-a2f4-562370680fca)

Зачем сдвинул копирку у хопа?
![image](https://github.com/user-attachments/assets/ec2963fe-8fa8-46f9-8db6-453153f70155)

![image](https://github.com/user-attachments/assets/da40a4bb-c649-4418-a4f9-4cd8d89b1d61)
Обрубки атмоса. Обрубки проводов. 
![image](https://github.com/user-attachments/assets/a6a4a2fb-a425-4d5b-acfe-42ab62446e7a)

Зачем заблочил выход в шлюз?
![image](https://github.com/user-attachments/assets/1959541e-2082-465c-a605-f7e535ef5204)

Неправильное направление айр алярма. 
![image](https://github.com/user-attachments/assets/79428dc5-6e3d-475a-82dc-847e88da5811)

Обрубок трубы перед комнатой свиданий.
![image](https://github.com/user-attachments/assets/01a984ef-8a4c-4819-b69d-b6e61c2d76f2)

непонятная мешанина плиток, переделать. Все словно свалено в одном углу, говно полное. 
![image](https://github.com/user-attachments/assets/38b4ac3b-d9b3-4f1e-9d4d-f97a4b4d2560)

Опять остатки труб от ремапа. 
![image](https://github.com/user-attachments/assets/5c11fda7-8e9d-4417-b44d-43b647f9f727)

Воксы двери и соединение труб утащили? 
![image](https://github.com/user-attachments/assets/946e6195-16ab-4e24-9720-b6891a9ae589)


Общая проблема: много где на новых окнах и дверях не хватает эмерджи шаттеров.

</p>
</details>

2024-08-04 18:37 UTC, DarkFurrSss commented
Скорее логичнее телепортную к рнд..

2024-08-05 04:22 UTC, maleyvich commented
комната для свиданий откладывается до лучших времён (она обязательно вернётся), скриншоты обновлены

2024-08-05 08:14 UTC, KatoMarika requested changes
Окна старой гидропоники. Нет плитки совсем, решетка и лишний шаттер. 
![image](https://github.com/user-attachments/assets/144bbc08-0cd3-48d9-87db-d8bafe815d68)

Барбер. Зачем пресет света из брига? 
![image](https://github.com/user-attachments/assets/27b5bf22-c02b-445d-8c2e-2419fd87de27)

Капитан все еще не подлючен к атмосу. Опять же провод который раньше шел в телепортную остался. 
![image](https://github.com/user-attachments/assets/504c21b4-c858-4308-b090-914265a49ad1)

Труба дважды.
![image](https://github.com/user-attachments/assets/fcdf0dd2-37b4-41ef-9b13-60ff672b354a)

Опять огрыки труб оставил. 
![image](https://github.com/user-attachments/assets/94ef7237-876a-4a1a-8002-fb6a13360473)

Я все еще не понимаю зачем копирку с её места нужно переносить к стене. 
![image](https://github.com/user-attachments/assets/f081aa39-25a0-45d2-8d54-c3a99ebdc70a)

![image](https://github.com/user-attachments/assets/d8da8307-8782-499b-94e8-810bfe44660d)

Опять огрызки труб. 
![image](https://github.com/user-attachments/assets/ca22061c-62a7-471d-a6bb-ce194079053b)

В помещении нужно уменьшить кол-во и хаотичнее её расставить, плакат сделать на одну сторону. посмотри как другие сделаны. 
![image](https://github.com/user-attachments/assets/0d04c83d-f5f5-4c53-874f-aea977721f70)

Стол потерял кусок, пропали стаканчики для кулера. 
![image](https://github.com/user-attachments/assets/296630b3-1aba-4f8c-a88e-9c3c157fbf0c)

Не исправлены ошибки указанные в предыдущем ревью. 
![image](https://github.com/user-attachments/assets/e3a38910-6782-491c-8a80-f45e1d8a5f68)

2024-08-05 10:40 UTC, KatoMarika requested changes
Появилось смещение окна в старой ботанике. 
![image](https://github.com/user-attachments/assets/c52aac05-6a53-4deb-b6d0-29f4d98a4c71)
Просьба тут подправить зоны(Красное) и стену(зеленое) 
![image](https://github.com/user-attachments/assets/fab96b1d-14a9-4ad0-a091-16420fdde78f)


И еще я тут все же подумал, лучше автоматы назад толкнуть. Верхний с напитками можно удалить, а остальные все сделать как ниже. 
![image](https://github.com/user-attachments/assets/dc8336c9-896b-4c6f-ae0a-9a9239739821)
Барбера с его стульями тоже лучше толкнуть что-то по типу такого. Ему не нужны такие огромные площади, можешь сравнить с Гаммой. 
![image](https://github.com/user-attachments/assets/2799342d-a6a6-4fe6-babb-f4809cc5a695)

Остальное вроде норм. Полностью пересмотрю после исправления этого.

2024-08-05 13:07 UTC, Risraivyn commented
Телепортная не должна быть рядом с бригом, когда ролькам нужно будет достать ручной телепортер они будут на виду у всего брига.

2024-08-05 13:13 UTC, maleyvich commented
> Телепортная не должна быть рядом с бригом, когда ролькам нужно будет достать ручной телепортер они будут на виду у всего брига.

ок

2024-08-05 13:23 UTC, KatoMarika approved these changes
С технической стороны все хорошо. Два дня ревью нонстопом прошли не зря (наверное)
Теперь немного лирики: Малевич иди читай гайды по мапингу и будь внимательнее. 
Теперь немного критики: я не уверен что это это хорошие переносы, по этому поводу бы мнение других маперов или Шефа. 

И еще добавлю, что когда Алексей Игнатьев закончил дела с Андре Ситроеном, то в столе у него остался огромный фотоальбом со строительством завода в Париже. 

<details><summary>Тык</summary>
<p>

И у меня есть альбом. 
![image](https://github.com/user-attachments/assets/f15f1fd5-8af5-432a-be16-cfe4f54dda5a)


</p>
</details>

2024-08-05 15:27 UTC, Tap0r commented
Я по традиции буду обсирать каждый мап пр.

> Ротации должны повлиять на геймплей и добавить более интересных ситуаций. 

Учитывая то, что 3 из 5 затронутых отсеков никакой ценности не имеют, весьма сомнительно.

> Блющилд перенесен к \"мозгу станции\", капитану (считаю это более логичным, чем у брига. Зачем ему там быть?). 

Стоило бы задуматься зачем ему быть вообще.

>Телепортационная же на месте БЩ открывает ещё больше возможностей для побега зеков и в целом выглядит как что-то более логичное. 

Побег зэков через телепортерную, находящуюся за общим коридором от общака. Можно было бы это написать, будь телепортерная прямо под общаком, но нет. И схуёв телепортерная у брига это нечто логичное, если в неё доступ имеют только главы, и то не все.

> АВД переместился немного ближе к главам на место цирюльника, а сама парихмахерская переместилась в старую ботанику, поближе к меду. К слову - она стала выглядеть более красивой! 

Тут даже комментировать особо нечего. Можно даже сказать ничего не изменилось.

>Старую ботанику переместил в центральное экстренное хранилище в немного урезанном виде.

А вот это уже минус. Заброшенный отсек у коридора куда приятнее восстанавливать, ибо его смогут без проблем посетить все.

Итого из 5 перестановленных отсеков на 3 абсолютно похуй, кабинет бщ даже удалить можно. А 2 оставшихся изменены в худшую сторону. Хотя с телепортерной честно хуй знает, но мне скорее не нравится.


Кратко, пр - говно. Я бы на месте ястарка даже время на ревью не тратил. Это буквально изменения ради изменений. В изначальной версии отсеки даже не переделывались никак, они в тупую поменялись местами. 

Судя по количеству лайков людей настолько заебал бокс, что уже даже настолько пресные изменения воспринимаются как мега хайп. И после этого некоторые из них будут говорить что не хотят играть на других картах, потому что на них просто отсеки местами меняются))))

Видимо мы обречены вместо адекватной ротации карт, сделанных с душой и идеей, иметь пресные ротации бокса, сделанные каким-то условно-обобщённым малевичем на отъебись абы как да на коленке. 
Мне честно похуй как-то, но если будете это мержить, я бы задумался над удалением воутов за другие карты и возвращением гусьбоксика, тоже ниче такая ротация. Будем счастливо жить в проклятом мире, который сами же и сотворили, раз в неделю меняя рандомные отсеки на боксе местами.

2024-08-05 19:10 UTC, KatoMarika approved these changes

2024-08-06 16:30 UTC, LudwigVonChesterfield commented
я против потому-что предпочёл бы чтобы у БЩ вообще не было офиса.

в ожидании частых вопросов:
- эквип шкафчик можно в бриге для тех кто поздно прибудет
- волшебный пустой сейф можно в конференц зале под столом

2024-08-06 16:50 UTC, Udokun commented
Перенести БЩ на так и не состоявшийся док тюрьмы и всем будет радость.

2024-08-29 02:28 UTC, closed without merging