Новые шаблоны ошибок для мапперов и переводчиков
TauCetiStation/TauCetiClassic pull request #13438
Opened 2024-08-06 06:17 UTC by AzzyDreemurr13

## Описание изменений
Новые шаблоны по актуальным проблемам. Добавлены шаблоны по мапперским ишуям и перевод ишуям

Можете глянуть как это будет выглядеть:
https://github.com/TauCetiStation-TranslationDepartment/TauCetiClassicNewTemplate/issues/new/choose
## Почему и что этот ПР улучшит
Более корректные баг репорты с установкой нужных лейблов
## Авторство
Я

## Чеинжлог
Не требуется, ибо изменения будут на гитхабе

2024-08-06 06:18 UTC, TauKitty commented
###### Changelog status: :radio_button: No changelog

2024-08-06 11:42 UTC, KatoMarika approved these changes
Мап деп. Итоги. 
<details><summary>Скрины.</summary>
<p>

![image](https://github.com/user-attachments/assets/0de41c57-abfb-49e6-9c5b-5ba48e0713dc)
![image](https://github.com/user-attachments/assets/9ef143c1-4055-4019-a610-9333c85d1eec)
Мне тоже норм.
</p>
</details> 
С учетом того как у нас мертвецы стоят по отделу, думаю можно апрувнуть, кому не понравится - будет воевать потом.

2024-08-18 05:26 UTC, volas commented on .github/ISSUE_TEMPLATE/map_report.yml
> +        База Синдиката
мне кажется, тут должен быть dropdown (выпадающий список)

2024-09-02 22:02 UTC, KIBORG04 commented on .github/ISSUE_TEMPLATE/map_report.yml
> +        База Синдиката
Думаю нет, это просто примеры в плейсхолдере. Пусть игрок сам пишет про окно у капеллана правее верхнего гроба.

2024-09-02 22:03 UTC, KIBORG04 commented on .github/ISSUE_TEMPLATE/map_report.yml
> +         а затем перетащите в неё файлы
Думаю, это поле стоит упразднить, потому что description и так предполагает любое описание проблемы.

2024-09-02 22:03 UTC, KIBORG04 commented on .github/ISSUE_TEMPLATE/map_report.yml
> +      value: "## Пожалуйста, не стирайте строчки, которые были автоматически созданы."
Никаких строчек нет, не нужно?

2024-09-02 22:07 UTC, KIBORG04 requested changes
Да пойдет, но сомневаюсь только в необходимости полей "дополнительная информация"

2024-09-02 23:50 UTC, KIBORG04 commented on .github/ISSUE_TEMPLATE/map_report.yml
> +      value: "## Пожалуйста, не стирайте строчки, которые были автоматически созданы."
Понимаю. Надо ли? Я хз. Можно и забить. Сам думай

2024-09-08 08:05 UTC, volas commented on .github/ISSUE_TEMPLATE/map_report.yml
> +        База Синдиката
Возможно мы о разном, я вижу это как выбор карты - фиксированный дефолтный список Boxstation, Gammastation и так далее, и маппер потом кроме того, чтоб отфильтровать по тегу карты, может отфильтровать ишью еще по самой карте.

А для описания есть textarea ниже.

2024-09-24 09:53 UTC, KIBORG04 commented on .github/ISSUE_TEMPLATE/map_report.yml
> +      label: "Опишите, что по вашему не так на карте?"
```suggestion
      label: "Описание"
```
В description: оно повторяется

2024-09-24 09:53 UTC, KIBORG04 approved these changes

2024-09-26 10:53 UTC, KIBORG04 commented on .github/ISSUE_TEMPLATE/map_report.yml
> +        База Синдиката
Партия требует туда вписать названия текущих карт (из игры можно прям), добавить "астероид" и "другое"(мб дописать, типа "цк слой, хз") и сделать не текстареа, а выбираемое. После этого я спидмержу(

2024-09-29 23:51 UTC, merged