Gamma floors
TauCetiStation/TauCetiClassic pull request #13446
Opened 2024-08-08 11:18 UTC by AzzyDreemurr13

## Описание изменений
По мотивам ПРа #13102
## Почему и что этот ПР улучшит
Новые полы на станции
## Авторство
Я

## Чеинжлог
:cl: Azzy.Dreemurr
 - map: Добавлены новые полы на Гамме

2024-08-08 11:18 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2024-08-08 20:04 UTC, AgRevol commented
I'm Gammabot and I approve this PR.

Не уверен за стекло в РНД и медбее но давай посмотрим, если что потом сам уберу

2024-08-08 20:54 UTC, KatoMarika requested changes
<details><summary>Проблемные места</summary>
<p>
Заброшка. 

![image](https://github.com/user-attachments/assets/7a2512e1-9279-46ed-9168-7c8a763d077b)

![image](https://github.com/user-attachments/assets/c6bde4ac-a1d3-4b9e-ac28-6c6c60cd4450)

Шатл станция-астеройд. Наверное стоит сделать как и на других. 
![image](https://github.com/user-attachments/assets/39972e01-6c5d-4f5b-b8d6-25571ba254cd)

Полигон. Кетвол переходит в обычную плитку, потом в гридку а потом под айрлоком  без плитки вообще. 
![image](https://github.com/user-attachments/assets/96d192ad-4986-411b-b61c-3fb1e960d253)

Голопад в меде на стекле. Im die, thank you forever. 
![image](https://github.com/user-attachments/assets/31f5bb8c-72ed-4732-a98b-437aa5fb7879)

</p>
</details>

2024-08-12 09:56 UTC, AgRevol commented
Я действительно это апрувнул во славу науки.

Я считаю, что стеклянные полы достаточно новая вещь и ещё не понятно как оно будет выглядеть в игре. Голопад посреди стекла, как по мне, смотрится достаточно футуристично. Посмотрим, как оно будет смотреться во время раунда пока оно постоянно на виду.

2024-08-14 10:47 UTC, AgRevol commented
Просьба пока не мержить

2024-08-14 22:35 UTC, AgRevol commented
> Просьба пока не мержить

https://github.com/TauCetiStation/TauCetiClassic/pull/13473

2024-08-15 08:46 UTC, closed without merging