new ammo for stechkin pistol & .357 revolver
TauCetiStation/TauCetiClassic pull request #13463
Opened 2024-08-10 21:18 UTC by simb11

## Описание изменений
Поменял спрайты у магазинов для стечкина.
Добавил новые виды боеприпасов для стечкина и револьвера.

![scrnshot1](https://github.com/user-attachments/assets/e2ab6c1e-af14-487b-89a9-7de9544daf2b)

Револьвер:
- Дробовые патроны -  револьвер выстреливает слабой (при самом лучшем раскладе наносит 80 брута), но более кучной версией обычной дроби. Подходит только для оружия калибра .357.
- ЭМИ патроны - наносят очень мало брута, но при попадании создают небольшое ЭМИ.

Стечкин:
- Зажигательные патроны - слабее обычных 9ММ пуль, но при попадании поджигают цель.

Все новые боеприпасы стоят 1 ТК. 

А ещё самые обычные патроны для револьвера заимели нормальное бронепробитие, стали дешевле и слабее (наносят 35 брута)

## Почему и что этот ПР улучшит
Больше вариативности при игре за предателя или нюкера.
## Авторство
Спрайты дробовых патронов отсюда: https://github.com/TauCetiStation/TauCetiClassic/pull/7129
Спрайты магазинов для стечкина отсюда: https://github.com/discordia-space/CEV-Eris

## Чеинжлог
🆑 Simbaka
- add: В ассортименте аплинка появились новые боеприпасы для пистолета Стечкина и револьвера.
- balance: Патроны калибра .357 хорошо пробивают броню, наносят меньше урона и продаются за намного меньшую стоимость в аплинке.
- image: Респрайт магазинов пистолета Стечкина.

2024-08-10 21:18 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2024-08-10 22:30 UTC, QWxiZ commented
Название ПРа: новые патроны для стечкина.
На самом деле ПР суть ребаланс метового револьвера.
Плохиш симбака пытается втихную протолкнуть ребаланс.
Это как уклоняться от налогов, только на тауките.

2024-08-11 06:59 UTC, Risraivyn commented
Револьвер это оружие убийства, а не войны. Убирая его высокий урон по не бронированным людям, ломает его смысл.

2024-08-11 08:33 UTC, TheLone1y commented
Он заранее заряжен дробью или пробивными? Лучше бы дробью

2024-08-11 09:27 UTC, Oz1Es commented
Ну вроде бы всё круто, но тут ещё плюсом ребаланс револьвера, что делает из него просто глок с малым магазином и более большим уроном

2024-08-11 16:48 UTC, WatlerJe requested changes
Дробовые патроны для револьвера можно перепутать с патронами для дробовика.

2024-08-12 09:09 UTC, simb11 commented
я не умею рисовать а жаль

2024-08-12 09:09 UTC, closed without merging