Gamma Updates: Floor, RND Hallway, Wall machinery, Bugfixes
TauCetiStation/TauCetiClassic pull request #13473
Opened 2024-08-14 22:33 UTC by AgRevol

## Описание изменений
Гамма стала лучше (Как такое возможно?)

## Почему и что этот ПР улучшит
Улучшит экспириенс игроков на Гамме

## Авторство
Azzy.Dreemurr - драйвер изменения полов и автор значительной части изменений полов (https://github.com/TauCetiStation/TauCetiClassic/pull/13446)
AgRevol - главный гаммабот

## Чеинжлог

:cl: Azzy.Dreemurr
- map: Добавлены новые полы на Гамме

:cl: AgRevol
 - map: Фикс доступов на Гамме и многие другие багфиксы
 - map: Изменение коридора перед РНД на Гамме.
 - map: Добавление тикет-машины, а так же другие изменения Гаммы

2024-08-14 22:33 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2024-08-15 09:40 UTC, volas commented
такой чеинжлог не будет работать

2024-08-15 17:58 UTC, KatoMarika requested changes
<details><summary>Details</summary>
<p>

![image](https://github.com/user-attachments/assets/5549c79c-f1d5-4630-bec6-f2388254c6ce)
Подправь лештницу, 

Гридку в док аштеройда. 
![image](https://github.com/user-attachments/assets/d2bc27e3-69e1-4e80-80e0-ca5bf92bea89)
![image](https://github.com/user-attachments/assets/4363870a-1d55-4191-b4d5-adbdd618d612)
Угловая декаль в шаду потерялашь. 
![image](https://github.com/user-attachments/assets/20681493-e7c9-4259-b4e6-0b55d329fa6f)
Шпутник ии, нет гридки.
![image](https://github.com/user-attachments/assets/3530e9f3-a2dc-4312-af39-650529df1393)
Замени на engine/airless
![image](https://github.com/user-attachments/assets/92b789d5-8fb6-4d27-8f61-1766005404c3)
В штене решетки. Над вирусологией, Правее. 
![image](https://github.com/user-attachments/assets/47936752-f5c3-4b1b-94a8-dc27723ff74d)
Шейм, левее от шпутка. 
![image](https://github.com/user-attachments/assets/e78bcae0-578f-4f58-9605-df67be79be00)
Трубы перед моштиком. 
![image](https://github.com/user-attachments/assets/97289506-5a5f-401f-ae82-0d886529caae)
Непонятный огрызок кабеля там где делал коридор 
</p>
</details>

2024-08-15 19:21 UTC, AgRevol reviewed
Done

2024-08-16 03:44 UTC, merged

2026-03-31 00:42 UTC, AzzyDreemurr13 commented
> такой чеинжлог не будет работать

Хах, а ведь сработал же..
![Screenshot_20260331_034157_Chrome](https://github.com/user-attachments/assets/b27a3d78-030e-45ba-829f-225292a0460c)