Горохострел (вместо револьверного дерева)
TauCetiStation/TauCetiClassic pull request #13498
Opened 2024-08-21 05:36 UTC by Danistans2

## Описание изменений
Добавляет в ботанику горохостреловое дерево на замену револьверного дерева. С помощью вирусологии превращается в горохострел.

## Почему и что этот ПР улучшит
ПР позволит пройти долгий и тернистый путь через ботанику и вирусологию, чтобы получить ГМО-пушку.

Глобально создаст больше возможностей для взаимодействия вирусолога с остальными и остальных с ним. Добавит в ботанику ещё одну прикольную фишку.

## Авторство
Maleyvich — автор всего основного ПРа
mothershipzetafangirl — спрайты
Danistans — условие на вынимание магазина, микрофиксы значений

## Чеинжлог
:cl:
 - rscadd: Из игры удалено револьверное дерево, зато вместо него добавлен менее робастный и более логичный горохострел

2024-08-21 05:36 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2024-08-21 05:42 UTC, simb11 commented on code/defines/obj/hydro.dm
>  /obj/item/seeds/gatfruit
Надо наверное и тайпы поменять.

2024-08-21 05:48 UTC, Tap0r commented
горохострел должен быть турелью

2024-08-21 05:49 UTC, Danistans2 commented
> горохострел должен быть турелью

Если будет мерж горохострела — будет горохотурель

2024-08-21 10:50 UTC, Danistans2 commented on code/defines/obj/hydro.dm
>  /obj/item/seeds/gatfruit
> Надо наверное и тайпы поменять.

Поменял в новых коммитах + залил еще спрайты. Пока без изменений seed спрайт

Авторство по спрайтам то же - mothershipzetafangirl

2024-08-21 21:52 UTC, ZER0-In commented
> > горохострел должен быть турелью
> 
> Если будет мерж горохострела — будет горохотурель
> 
> Inb4: И звуки из PvZ

Если собирать турель и добавить вместо лазерной пушки горохострел = горохотурель?

2024-08-22 02:14 UTC, Danistans2 commented
> > > горохострел должен быть турелью
> > 
> > 
> > Если будет мерж горохострела — будет горохотурель
> > Inb4: И звуки из PvZ
> 
> Если собирать турель и добавить вместо лазерной пушки горохострел = горохотурель?

У самого горохострела боезапас ограничен 6-ю горошинами. Стручок не перезаряжается после этого и с ним ничего нельзя сделать, плюс это проджектайл пистолет типа глока (который кстати очень удобно лежит в холстере, который печатается в ботанике).

Я вижу 2 варианта:
1) Посадить семечко горохострела и вырастить в корпусе турели
2) Тыкнуть мутацию горохострела (турель) на пол

Тут хотелось бы чтобы как горохострел на мог серьёзно соревноваться с глоком, так и горохотурель не могла быть такой же страшной, как обычная турель

2024-08-24 16:27 UTC, Danistans2 commented on code/modules/projectiles/ammunition/bullets.dm
> +	m_amt = 300
1-2. По тесту предположил, что оно ничего не ломает и так можно. Но в принципе ладно, в пн поменяю вместе с остальными правками
3. Патрон горохострела невозможно получить в игре, поэтому просто оставил дефолт калибр. Поменяю на горох (это работает, ничего не меняется/ не ломается)
4. Не обратил внимания, удалю также в пн

2024-08-24 16:31 UTC, Danistans2 commented on code/modules/projectiles/guns/projectile.dm
> +		return
Ты подразумеваешь то, чтобы вместо этого условия определить новый прок в pistol/peashooter? Если так, то он ведь может конфликтовать, перезарядка работает по общему проку для пистолетов...

Или речь не об этом?

2024-08-26 14:28 UTC, Danistans2 commented on code/modules/projectiles/ammunition/magazines.dm
> +	caliber = "9mm"
Калибр везде изменил на Pea

2024-08-26 14:28 UTC, Danistans2 commented on code/modules/projectiles/guns/projectile.dm
> +		return
Переопределил новым коммитом

2024-08-28 01:45 UTC, LudwigVonChesterfield commented
непонятно правда почему из перца растёт горохострел.

2024-08-28 08:03 UTC, Danistans2 commented
> непонятно правда почему из перца растёт горохострел.

Потому что в игре пока что нет гороха, а у чёрного перца структура горошинок.

Горох хотелось бы попозже закодить и заспрайтить, сейчас хотелось бы дать какую-то жизнь вирусологии в ботанике

![Black_Pepper_(Piper_nigrum)_fruits.jpg](https://github.com/user-attachments/assets/51e07317-e9ea-4864-a834-cbd68cd4bce7)

2024-08-29 07:23 UTC, volas approved these changes

2024-08-29 07:24 UTC, volas commented on code/modules/reagents/reagent_containers/food/snacks/grown.dm
> +	desc = "Пахнет как горох, вперемешку с... порохом?"
порох не единственный способ придачи снаряду ускорения и наличие в растении как-то сомнительно

2024-08-29 11:50 UTC, Danistans2 commented on code/modules/reagents/reagent_containers/food/snacks/grown.dm
> +	desc = "Пахнет как горох, вперемешку с... порохом?"
> порох не единственный способ придачи снаряду ускорения и наличие в растении как-то сомнительно

Поменял описание и добавил cases

2024-08-30 21:15 UTC, Danistans2 commented
> ![image](https://private-user-images.githubusercontent.com/89906909/363167149-e56f8c3e-353c-4859-b3e3-81b9ac5432d2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUwNTI2ODYsIm5iZiI6MTcyNTA1MjM4NiwicGF0aCI6Ii84OTkwNjkwOS8zNjMxNjcxNDktZTU2ZjhjM2UtMzUzYy00ODU5LWIzZTMtODFiOWFjNTQzMmQyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODMwVDIxMTMwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE3ZWZmMDk3ZjEwNmE4N2QxM2Q5MzExN2UxYzIxNWFlYTQ1MTQyNzM4M2M5MWJlNWNmMDE1YjJhMzBkMjZmNDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Qbla0QRfplVTS2-VGs-_a6YRFy-M1tDsUAJqxfLfeNI) файл со спрайтами не стоит оставлять в корневой папке

Остался и забылся при копировании. Пофиксил, удалив лишнюю копию из корня.

2024-08-31 14:30 UTC, Danistans2 commented on code/modules/projectiles/guns/projectile/pistol.dm
> +		return
Разберусь с этим и верхним на неделе.  Спасибо за ответ

2024-08-31 15:11 UTC, Kiromaka requested changes
ПР от малевича, и без падежей.

2024-08-31 15:24 UTC, Kiromaka requested changes

2024-08-31 15:24 UTC, Kiromaka commented on code/defines/obj/hydro.dm
> +	name = "pack of peashooter seeds"
```suggestion
	name = "pack of peashooter seeds"
	cases = list("семена Горохострела","семян Горохострела","семенам Горохострела","семена Горохострела","семенами Горохострела","семенах Горохострела")
```

2024-08-31 15:24 UTC, Kiromaka commented on code/defines/obj/hydro.dm
> +	desc = "These seeds grow into peashooter"
```suggestion
	desc = "Эти семена вырастают в Горохострел"
```

2024-08-31 15:24 UTC, Kiromaka commented on code/modules/projectiles/ammunition/bullets.dm
> +	name = "Pea bullet casing"
```suggestion
	name = "Pea bullet casing"
	cases = list("гороховый патрон", "горохового патрона", "гороховому патрону", "гороховый патрон", "гороховым патроном", "гороховом патроне")
```

2024-08-31 15:24 UTC, Kiromaka commented on code/modules/projectiles/ammunition/bullets.dm
> +	desc = "Патрон от гороховой пули"
Да какой блять патрон от пули

2024-08-31 15:24 UTC, Kiromaka commented on code/modules/projectiles/guns/projectile/pistol.dm
> +	desc = "Горохострел. Стреляет горохом."
тут тоже падежи нужны

2024-08-31 15:24 UTC, Kiromaka commented on code/modules/projectiles/guns/projectile/pistol.dm
> +		to_chat(user, "<span class='notice'>Вы не можете вынуть горох из [src].</span>")
```suggestion
		to_chat(user, "<span class='notice'>Вы не можете вынуть горох из [CASE(src, GENITIVE_CASE)].</span>")
```

2024-08-31 16:18 UTC, Danistans2 commented
> Вынужден добавить эту табличку, ибо оружие начали переводить, так что падежи - Да

Сделаю, это не будет сложно, тут достаточно подробные ответы. 

Вопрос по переводу: раз это смежный ПР, я в целом могу сразу в нем перевести гидропонику. Лучше сделать это сразу здесь или отдельным ПРом?

2024-08-31 22:29 UTC, Danistans2 commented
Выпилил весь перевод из Горохострела, его семян, патрон, пуль, etc.

Падежи не добавлял (и наоборот - удалил из тех мест, где замержил или вставил сам). Причина: Чтобы не было путаницы, когда буду заливать перевод гидропоники отдельным ПРом, чтобы не было вопросов, почему из всей гидропоники и патрон переведены только Горохострел и горошины. Потому что доверяю авторитетной позиции Людука в конце концов.

Перевода оружия с падежами в билде не обнаружил = приравнял уровень перевода к текущему для остальных видов патрон и оружия, ни больше, ни меньше. Скрин для сравнения уровня перевода:
![image](https://github.com/user-attachments/assets/4e201db2-7425-412e-8dd7-db3c2e6e246a)

Правки по проверкам (от Пикачушки) учел и внёс

2024-09-01 05:52 UTC, Danistans2 commented
Вернул короче перевод как было, по комментам @Kiromaka 

@AzzyDreemurr13

2024-09-03 18:07 UTC, Kiromaka approved these changes

2024-09-03 18:08 UTC, Kiromaka commented
Мержите.

2024-09-08 07:23 UTC, merged

2024-09-24 10:48 UTC, TauKitty commented
Этот запрос на слияние был упомянут в **Tau Ceti Station Forum**. Там могут быть соответствующие подробности:

https://forum.taucetistation.org/t/obsuzhdenie-pr-a-gorohostrel/43815/1