Диспенсер пены получил собственный спрайт
TauCetiStation/TauCetiClassic pull request #13500
Opened 2024-08-21 13:55 UTC by Venngedi

## Описание изменений
АИ слиппер больше не похож на датчик движения. Пришлось сделать немного изменений на картах.
## Почему и что этот ПР улучшит
Важное для ИИ устройство станет более заметным.
## Авторство
[/tg/station](https://github.com/tgstation/tgstation/blob/f72b5489c297a4f19bce22db9041b5f1ac66df8c/icons/obj/devices/tool.dmi)

## Чеинжлог

2024-08-21 13:55 UTC, TauKitty commented
###### Changelog status: :radio_button: No changelog

2024-08-21 13:57 UTC, Deahaka commented
Скрины показывай братан

2024-08-21 14:00 UTC, Venngedi commented
![image](https://github.com/user-attachments/assets/28d60097-b41d-4449-a654-be47810e99bb)
![image](https://github.com/user-attachments/assets/cd040760-18a9-4a83-8579-deed3095e05a)
![image](https://github.com/user-attachments/assets/eb5b34e8-f88e-4e84-8f7b-beb2d6a134d7)
![image](https://github.com/user-attachments/assets/63ed153c-b5ff-4101-a12e-e77a9a9afd9c)
![image](https://github.com/user-attachments/assets/7755c561-af86-4a81-9605-1163f4b25e8e)

2024-08-21 14:34 UTC, Venngedi commented
![Tau Ceti Station 2024-08-21 173157](https://github.com/user-attachments/assets/ebe44c2d-b6e9-46cc-ba89-574810a19a40)
![Tau Ceti Station 2024-08-21 173350](https://github.com/user-attachments/assets/2ac1cdc7-e992-4bc4-994e-61cdb4cb9dc3)
![Tau Ceti Station 2024-08-21 173423](https://github.com/user-attachments/assets/c36c4b39-d419-49fd-8bce-3c34c1cfdb00)

2024-08-24 12:19 UTC, WatlerJe approved these changes

2024-08-25 01:01 UTC, KatoMarika approved these changes

2024-08-27 13:50 UTC, Chip11-n approved these changes
Единственный момент - на боксе голопад и диспенсер получили половинчатое смещение.

Если ни у кого не возникнет претензий, мержу через суткию

2024-08-27 14:07 UTC, KatoMarika commented
> Единственный момент - на боксе голопад и диспенсер получили половинчатое смещение.
> 
> Если ни у кого не возникнет претензий, мержу через суткию

Странная претензия учитывая что: 
<details><summary>Голопады бокса</summary>
<p>

![image](https://github.com/user-attachments/assets/00c2b49f-6349-4cca-a258-f2d155f5a042)
![image](https://github.com/user-attachments/assets/1b0c6bb5-307f-40fe-bfdc-3774609474b4)
![image](https://github.com/user-attachments/assets/ee287613-7ea9-487e-a3ed-ead83fdc8537)
![image](https://github.com/user-attachments/assets/075a11fb-3a0e-4a87-9779-d554be78c37a)
![image](https://github.com/user-attachments/assets/da12778d-7923-495e-a77d-109bbcb37854)
![image](https://github.com/user-attachments/assets/ef9975f2-37bc-42e5-a13a-9dd1d14b3404)
![image](https://github.com/user-attachments/assets/83c15748-18dd-4fd1-af9a-576e8c050e70)


</p>
</details>

2024-08-27 14:16 UTC, Chip11-n commented
Что ты хочешь от меня услышать?

2024-08-27 14:27 UTC, KatoMarika commented
Что у тебя был хороший обед и погода солнечная, 

Прост странно указывать якобы на косяк, когда такое решение используется и на святом Боксе.

2024-08-27 14:40 UTC, KatoMarika requested changes
Я додумался в чем может быть проблема и она действительно есть. Просьба установить диспенсеры без смещения. 

https://github.com/user-attachments/assets/d5e268b2-d781-425d-992e-5f5de6db663b

2024-08-27 14:41 UTC, Tap0r commented
а не похуй?

2024-08-27 17:49 UTC, Venngedi commented
> Добавь яркости, какое-то очень тёмное

![Tau Ceti Station 2024-08-27 204443](https://github.com/user-attachments/assets/045fa9d4-9483-487e-bf86-d3f1bb4ba53b)

2024-08-29 06:32 UTC, Chip11-n commented
Со спрайтами разобрались? Мержу?

2024-08-29 09:04 UTC, KatoMarika approved these changes

2024-08-29 21:52 UTC, Venngedi commented
> Со спрайтами разобрались? Мержу?

Разобрались

2024-09-01 21:50 UTC, merged