Перевод гидропоники
TauCetiStation/TauCetiClassic pull request #13532
Opened 2024-09-09 14:12 UTC by Danistans2

## Описание изменений
Перевод гидропоники.

## Почему и что этот ПР улучшит
Будут русские буквы. Это хорошо, это православно.

## Авторство
Danistans

## Чеинжлог
:cl:
- ru: Переведена большая часть гидропоники

2024-09-09 14:12 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2024-09-09 14:17 UTC, maleyvich approved these changes
а мне нравится. пусть другой кто-то посмотрит.

2024-09-09 14:17 UTC, maleyvich commented on code/modules/reagents/reagent_containers/food/snacks/grown.dm
> +		msg = "<span class='info'>*---------*\n Это \a <span class='name'>[CASE(src, NOMINATIVE_CASE)]</span>\n"
убери \a

2024-09-09 14:17 UTC, maleyvich commented on code/modules/reagents/reagent_containers/food/snacks/grown.dm
> +		msg = "<span class='info'>*---------*\n Это \a <span class='name'>[CASE(src, NOMINATIVE_CASE)]</span>\n"
тут тоже убери

2024-09-09 14:17 UTC, maleyvich commented on code/modules/reagents/reagent_containers/food/snacks/grown.dm
> +	desc = "\"Коль буду жив, Фиделе, я все лето печальную твою могилу стану цветами украшать. Увидишь ты подснежник белый, как твое лицо, и колокольчик, голубее жилок твоих; и розы, аромат которых не сл
это конечно интересно, но я думаю это не стоит  коментить

2024-09-09 14:17 UTC, maleyvich commented on code/modules/reagents/reagent_containers/food/snacks/grown.dm
> +	desc = "На яблоке красуется слово 'Прекраснейший'." // От древнегреческого τῇ καλλίστῃ (ti kallisti) - прекраснейший
опять же это необязательно, но если никто не против - оставляй.

2024-09-09 14:20 UTC, maleyvich reviewed
пофиксит ошибку

2024-09-09 14:20 UTC, maleyvich commented on code/defines/obj/hydro.dm
> +	to_chat(viewers(user), "<span class='warning'><b>[user] поедает [CASE(src.name, DATIVE_CASE)]! Похоже, что [THEY_RU(user)] пытается покончить с собой.</b></span>")
```suggestion
	to_chat(viewers(user), "<span class='warning'><b>[user] поедает [CASE(src, DATIVE_CASE)]! Похоже, что [THEY_RU(user)] пытается покончить с собой.</b></span>")
```

2024-09-09 18:03 UTC, Kiromaka commented
Опять ревьювить

2024-09-09 18:05 UTC, Danistans2 commented on code/defines/obj/hydro.dm
> +	desc = "Из этих семян вырастает черный перец."
Потому что на мой взгляд звучит туповато

2024-09-09 18:06 UTC, Danistans2 commented on code/defines/obj/hydro.dm
> +	desc = "Из этих семян вырастает перец чили. ГОРЯЧО! ГОРЯЧО! ГОРЯЧО!"
> Почему горячо? Если "ОСТРО" "ЖЖЕТ"

Глаз замылился видать, подправлю

2024-09-09 18:06 UTC, Danistans2 commented on code/defines/obj/hydro.dm
> +	desc = "Кукуруза, товарищи, это танк в руках бойцов, я имею в виду колхозников!"
> Не смешно и не круто.

Первоначальный каламбур не сохранить, лучше не придумал

2024-09-09 18:06 UTC, Danistans2 commented on code/defines/obj/hydro.dm
> +	desc = "Свари! Сомни! Потуши! Но для начала посади в грядку."
> картошку не мнут, а толкут

Ок

2024-09-09 18:18 UTC, Kiromaka requested changes
А падежи пусть другие смотрят.

2024-09-09 18:18 UTC, Kiromaka commented on code/modules/reagents/reagent_containers/food/snacks/grown.dm
> +	desc = "Гроздь не только питательных ягод. Слабо светится в темноте."
Я задумку вроде понял, но звучит странно, не только, но и каких ?

2024-09-09 18:18 UTC, Kiromaka commented on code/modules/reagents/reagent_containers/food/snacks/grown.dm
> +	desc = "По вкусу вкусно, но ты скорее всего умрешь."
Думаю можно оставить "Смертельно вкусно" - звучит лучше.

2024-09-09 18:18 UTC, Kiromaka commented on code/modules/reagents/reagent_containers/food/snacks/grown.dm
> +	desc = "Это растение содержит различные лечебные химические вещества."
Химические лишнее, звучит лучше как просто - "лечебные вещества".

2024-09-09 18:18 UTC, Kiromaka commented on code/modules/reagents/reagent_containers/food/snacks/grown.dm
> +	desc = "Если жизнь дает тебе лимоны, скажи спасибо, что это не лаймы."
Очень хочу здесь это, но сами решайте, а то щас постная версия лимонов. 
```suggestion
	desc = "Если жизнь дает тебе лимоны — не делай лимонад. Заставь жизнь забрать их обратно! Разозлись! «Мне не нужны твои проклятые лимоны! Что мне с ними делать?»."
```

2024-09-09 18:31 UTC, Danistans2 commented on code/modules/reagents/reagent_containers/food/snacks/grown.dm
> +	desc = "Гроздь не только питательных ягод. Слабо светится в темноте."
Поправил

2024-09-09 19:57 UTC, Kiromaka requested changes

2024-09-09 19:57 UTC, Kiromaka commented on code/modules/reagents/reagent_containers/food/snacks/grown.dm
> +	desc = "Смертельно вкусно, но ты скорее всего умрешь."
Ты конечно поправил, но теперь тавтология какая-то.

2024-09-09 20:04 UTC, Danistans2 commented on code/modules/reagents/reagent_containers/food/snacks/grown.dm
> +	desc = "Смертельно вкусно, но ты скорее всего умрешь."
Мб тогда просто "Смертельно вкусные ягоды"?

2024-09-10 10:27 UTC, AmnyamNyam commented
@AzzyDreemurr13 я здесь и я помогу, но для начала ебни кита. Коротко почитал ее доебы и пернул от смеха

2024-09-10 13:01 UTC, Pivo24 commented on code/defines/obj/hydro.dm
> +	cases = list("мицелий светящихся грибов", "мицелия светящихся грибов", "мицелию светящихся грибов", "мицелий светящихся грибов", "мицелием светящихся грибов", "мицелие светящихся грибов")
светогрибов? >.>

2024-09-14 22:50 UTC, Danistans2 commented
![scale_1200 (4)](https://github.com/user-attachments/assets/fa2febda-3718-4a41-bc60-5993ed9ba623)
Мержим?

2024-09-14 23:19 UTC, KIBORG04 commented on code/defines/obj/hydro.dm
> +*/
?

2024-09-14 23:20 UTC, Danistans2 commented on code/defines/obj/hydro.dm
> +*/
Для себя делал, щас удалю

2024-09-16 16:09 UTC, Danistans2 commented on code/defines/obj/hydro.dm
> +	cases = list("мицелий пластеллия", "мицелия пластеллия", "мицелию пластеллия", "мицелий пластеллия", "мицелием пластеллия", "мицелие пластеллия")
У грибов не бывает семян, у них мицелий

2024-09-16 16:13 UTC, Danistans2 commented on code/modules/reagents/reagent_containers/food/snacks/meat.dm
>  /obj/item/weapon/reagent_containers/food/snacks/meat/meatwheat
В том, что я перевожу гидропонику. Meatwheat — из гидропоники, а обычное мясо — нет

2024-09-16 16:14 UTC, Danistans2 commented on code/defines/obj/hydro.dm
> +	cases = list("мицелий рейши", "мицелия рейши", "мицелию рейши", "мицелий рейши", "мицелием рейши", "мицелие рейши")
Я не забыл, у всех грибов это именно мицелий, а не семена

2024-09-22 12:55 UTC, KIBORG04 commented on code/defines/obj/hydro.dm
> +	cases = list("семена черного перца", "семян черного перца", "семенам черного перца", "семена черного перец", "семенами черного перца", "семенах черного перца")
```suggestion
	cases = list("семена черного перца", "семян черного перца", "семенам черного перца", "семена черного перец", "семенами черного перца", "семенах черного перца")
```

2024-09-22 12:56 UTC, KIBORG04 commented on code/defines/obj/hydro.dm
> +	cases = list("мицелий пластеллия", "мицелия пластеллия", "мицелию пластеллия", "мицелий пластеллия", "мицелием пластеллия", "мицелие пластеллия")
![image](https://github.com/user-attachments/assets/0fb4cb84-4987-4a3c-b995-edb1cfe45419)
```suggestion
	cases = list("мицелий пластеллия", "мицелия пластеллия", "мицелию пластеллия", "мицелий пластеллия", "мицелием пластеллия", "мицелии пластеллия")
```

2024-09-22 12:56 UTC, KIBORG04 commented on code/defines/obj/hydro.dm
> +	desc = "Если есть сырой - может скукурузить!"
```suggestion
	desc = "Если есть сырой - может скукурузить!"
```

2024-09-22 12:57 UTC, KIBORG04 commented on code/defines/obj/hydro.dm
> +	cases = list("мицелий бледной поганки", "мицелия бледной поганки", "мицелию бледной поганки", "мицелий бледной поганки", "мицелием бледной поганки", "мицелие бледной поганки")
```suggestion
	cases = list("мицелий бледной поганки", "мицелия бледной поганки", "мицелию бледной поганки", "мицелий бледной поганки", "мицелием бледной поганки", "мицелии бледной поганки")
```

https://ru.wiktionary.org/wiki/мицелий

2024-09-22 12:57 UTC, KIBORG04 commented on code/defines/obj/hydro.dm
> +	cases = list("мицелий грибов псилоцибе", "мицелия грибов псилоцибе", "мицелию грибов псилоцибе", "мицелий грибов псилоцибе", "мицелием грибов псилоцибе", "мицелие грибов псилоцибе")
```suggestion
	cases = list("мицелий грибов псилоцибе", "мицелия грибов псилоцибе", "мицелию грибов псилоцибе", "мицелий грибов псилоцибе", "мицелием грибов псилоцибе", "мицелии грибов псилоцибе")
```

2024-09-22 12:58 UTC, KIBORG04 commented on code/defines/obj/hydro.dm
> +	cases = list("мицелий юпитерской чашечки", "мицелия юпитерской чашечки", "мицелию юпитерской чашечки", "мицелий юпитерской чашечки", "мицелием юпитерской чашечки", "мицелие юпитерской чашечки")
```suggestion
	cases = list("мицелий юпитерской чашечки", "мицелия юпитерской чашечки", "мицелию юпитерской чашечки", "мицелий юпитерской чашечки", "мицелием юпитерской чашечки", "мицелии юпитерской чашечки")
```

2024-09-22 12:58 UTC, KIBORG04 commented on code/defines/obj/hydro.dm
> +	cases = list("мицелий светогрибов", "мицелия светогрибовгрибов", "мицелию светогрибов", "мицелий светогрибов", "мицелием светогрибов", "мицелие светогрибов")
```suggestion
	cases = list("мицелий светогрибов", "мицелия светогрибов", "мицелию светогрибов", "мицелий светогрибов", "мицелием светогрибов", "мицелие светогрибов")
```

2024-09-22 13:00 UTC, KIBORG04 commented on code/defines/obj/hydro.dm
> +	desc = "Из этого мицелия -высветают- особые грибы!"
```suggestion
	desc = "Из этого мицелия -просветают- особые грибы!"
```
Мб так норм, но могут ли грибы выцветать? Думаю нет, мб так?

2024-09-22 13:06 UTC, KIBORG04 commented on code/defines/obj/hydro.dm
![image](https://github.com/user-attachments/assets/c3b05f58-0edb-4b41-a226-daa861d3491b)

Очень много всяких пробелов и табов в конце твоих строк, убери их для красоты. Через редактор будет просто через автозамену

2024-09-22 13:06 UTC, KIBORG04 commented on code/modules/reagents/reagent_containers/food/snacks/grown.dm
> +	desc = "Сладкий и крайне питательный. Из него традиционно делают красные вина Шардоне, Совиньон блан и другие."
![image](https://github.com/user-attachments/assets/af969727-e047-4ac0-8661-44858c1b96b2)

На вике через дефис

2024-09-22 13:07 UTC, KIBORG04 commented on code/modules/reagents/reagent_containers/food/snacks/grown.dm
> +	desc = "Сладкий и крайне питательный. Из этого сорта винограда традиционно делают белые вина Винью Верде и другие."
```suggestion
	desc = "Сладкий и крайне питательный. Из этого сорта винограда традиционно делают белые вина Винью-верде и другие."
```
![image](https://github.com/user-attachments/assets/a7293255-b545-4fdc-ba6b-e0e9ad9add3c)

2024-09-22 13:08 UTC, KIBORG04 commented on code/modules/reagents/reagent_containers/food/snacks/grown.dm
> +	desc = "На яблоке красуется слово 'Прекраснейший'." // От древнегреческого τῇ καλλίστῃ (ti kallisti) - прекраснейший
Мб оставить на греческом слово?

2024-09-22 13:08 UTC, Danistans2 commented on code/modules/reagents/reagent_containers/food/snacks/grown.dm
> +	desc = "На яблоке красуется слово 'Прекраснейший'." // От древнегреческого τῇ καλλίστῃ (ti kallisti) - прекраснейший
Думаю да, так будет лучше

2024-09-22 13:09 UTC, KIBORG04 commented on code/modules/reagents/reagent_containers/food/snacks/grown.dm
> +	cases = list("ясенец", "ясенца", "ясенцу", "ясенец", "ясенцем", "ясенце")
```suggestion
	cases = list("ясенец", "ясенца", "ясенцу", "ясенец", "ясенцом", "ясенце")
```

![image](https://github.com/user-attachments/assets/0bdc03bb-62a9-44ba-a4f9-73d0d3b845d1)

2024-09-22 13:37 UTC, Danistans2 commented
Вроде бы всё посмотрел и отредачил

2024-09-29 11:31 UTC, Danistans commented
Что-то ещё будем править?

2024-10-03 11:08 UTC, Pivo24 requested changes

2024-10-03 11:08 UTC, Pivo24 commented on code/defines/obj/hydro.dm
> +	to_chat(viewers(user), "<span class='warning'><b>[user] поедает [CASE(src, DATIVE_CASE)]! Похоже, что [THEY_RU(user)] пытается покончить с собой.</b></span>")
поедает смерто-крапиве?

2024-10-03 11:08 UTC, Pivo24 commented on code/defines/obj/hydro.dm
> +	to_chat(viewers(user), "<span class='warning'><b>[user] вдыхает [CASE(src, DATIVE_CASE)]! Похоже, что [THEY_RU(user)] пытается покончить с собой.</b></span>")
вдыхает спрею от вредителей?

2024-10-03 11:10 UTC, Pivo24 commented on code/defines/obj/hydro.dm
> +	cases = list("смерто-крапива", "смерто-крапивы", "смерто-крапиве", "смерто-крапива", "смерто-крапивой", "смерто-крапиве")
винительный падеж - смерто-крапиву

2024-10-03 11:11 UTC, Pivo24 commented on code/defines/obj/hydro.dm
> +	cases = list("крапива", "крапивы", "крапиве", "крапива", "крапивой", "крапиве")
винительный падеж - крапиву

2024-10-03 11:11 UTC, Pivo24 commented on code/defines/obj/hydro.dm
> +	cases = list("бутылка пестицида", "бутылки пестицида", "бутылке пестицида", "бутылка пестицида", "бутылкой пестицида", "бутылке пестицида")
винительные падежи надо посмотреть, женский род в винительном падеже имеет окончание "у"

2024-10-03 11:12 UTC, Pivo24 requested changes
Надо ещё раз внимательно пройтись по cases, посмотреть существительные женского рода и некоторые существительные мужского, во многих местах винительный падеж должен склоняться, но вместо этого просто копирует именительный падеж, это не дело

2024-10-03 11:14 UTC, Danistans2 commented
> Надо ещё раз внимательно пройтись по cases, посмотреть существительные женского рода и некоторые существительные мужского, во многих местах винительный падеж должен склоняться, но вместо этого просто копирует именительный падеж, это не дело

Поправлю всё на выходных

2024-10-04 23:00 UTC, Danistans2 commented
Исправил везде винительный падеж, поправил падежи в суисайде и где-то еще с dative на accusative да и вообще.
@Pivo24 

Также перевел дюранить как дюраткань. Аутентичности ради (и чтобы не душнить, мол, ВАЩЕТА КАРТОШКУ ТОЛКУТ, А ТКАНЬ ДЕЛАЮТ ИЗ НИТИ!!!).
@AzzyDreemurr13

2024-10-06 20:08 UTC, Danistans commented
@Kiromaka @Pivo24 ещё что-то делаем?

2024-10-07 03:59 UTC, Pivo24 commented
Всё порядок

2024-10-07 04:00 UTC, Pivo24 approved these changes

2024-10-15 18:31 UTC, Danistans commented
Уэээ

2024-10-27 19:58 UTC, merged