Добавление огурцов v2.0
TauCetiStation/TauCetiClassic pull request #13530
Opened 2024-09-08 18:04 UTC by Bobloxer2009

## Описание изменений
Добавление огурцов в ботанику. (ну теперь горохострелы не удаляются)
## Почему и что этот ПР улучшит
Больше овощей...
## Авторство
Bobloxer2009

## Чеинжлог
:cl: Bobloxer2009
 - rscadd: Добавление огурцов в ботанику.

2024-09-08 18:04 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2024-09-08 19:08 UTC, TheBadDay4 commented
Кинь скрины.

2024-09-08 21:42 UTC, KIBORG04 commented on code/modules/reagents/reagent_containers/food/snacks/grown.dm
> +	reagents.add_reagent("ethylredoxrazine", 3+round((potency / 10), 1))
Мне кажется это слишком имбово для какого-то огурца

![image](https://github.com/user-attachments/assets/e61e53c7-ba0e-4b91-84fe-18c1f4a2816e)

2024-09-09 13:09 UTC, Bobloxer2009 commented on code/modules/reagents/reagent_containers/food/snacks/grown.dm
> +	reagents.add_reagent("ethylredoxrazine", 3+round((potency / 10), 1))
Учитывая, как популярна ботаника и учитывая как ей обычно нечасто пользуются (кроме повара), то нормально. Да и мало особо растений в которых есть что-то кроме нутриментов

2024-09-09 18:19 UTC, Tap0r commented
сделай мутацию алюминиевые огурцы

чтобы из них патроны делать или проще пусть прям с куста рандом патрики сыпятся

2024-09-09 18:20 UTC, Tap0r commented on code/modules/reagents/reagent_containers/food/snacks/grown.dm
> +	reagents.add_reagent("ethylredoxrazine", 3+round((potency / 10), 1))
опохмел в огурцах это гениально

2024-09-09 18:34 UTC, Ayaksblack commented
А еще можно мутировать во фрактальный кукумбер

2024-09-09 18:50 UTC, Danistans2 commented
Сделай под шумок мутацию супер кукумберов, которые за кусь выдают ещё и лютый диализ. Бармен будет убивать за эти огурцы

2024-09-10 09:35 UTC, Bobloxer2009 commented
Blyad', какой нахуй перевод, мы же в США.

2024-09-10 09:37 UTC, Bobloxer2009 commented
> сделай мутацию алюминиевые огурцы
> 
> чтобы из них патроны делать или проще пусть прям с куста рандом патрики сыпятся

Научи кодить - сделаю, или проще: сделай своим падаваном в кодинге. ;roflan_pominki;

2024-09-10 11:36 UTC, Kiromaka commented
![Uploading image.png…]()
Ты зачем нэймы перевел.

2024-09-10 11:37 UTC, Kiromaka commented
![image](https://github.com/user-attachments/assets/e7f23595-0cc3-4f85-b8a2-8b7239d60c75)
Ты зачем нэймы перевел ?

2024-09-10 11:39 UTC, Danistans2 commented
> ![image](https://github.com/user-attachments/assets/e7f23595-0cc3-4f85-b8a2-8b7239d60c75)
> Ты зачем нэймы перевел ? 
> 

Где? Не было ж такого

2024-09-10 11:39 UTC, Kiromaka requested changes

2024-09-10 11:39 UTC, Kiromaka commented on code/defines/obj/hydro.dm
> +	name = "пачка семян огурца"
```suggestion
	name = "pack of cucumber seeds"
```

2024-09-10 14:12 UTC, Kiromaka approved these changes

2024-09-10 23:14 UTC, WatlerJe requested changes
Спрайт огурца не годится. Выполнен не в палитре, нету ворлд иконки да и сам спрайт слабый.

2024-09-11 09:58 UTC, Bobloxer2009 commented
> Спрайт огурца не годится. Выполнен не в палитре, нету ворлд иконки да и сам спрайт слабый.
Какой надо палитре если я просто взял цвет который уже использовался в гидропонике, да и на кой ворлд_иконка если у некоторых овощей её также нету, а насчёт последнего, ну, ladno.

2024-09-11 10:29 UTC, Ayaksblack commented
Чекни закрепы в дискорд канале со спрайтами. И, если поправишь, можешь туда же скинуть на посмотреть. Вальтер требователен к спрайтам.

План был перевести весь билд в одну палитру и сделать иконки в мире маленькими и схематичными, а в рюкзаке - большими и красивыми

2024-09-11 11:00 UTC, WhaleNotPower commented
> > Спрайт огурца не годится. Выполнен не в палитре, нету ворлд иконки да и сам спрайт слабый.
> 
> Какой надо палитре если я просто взял цвет который уже использовался в гидропонике, да и на кой ворлд_иконка если у некоторых овощей её также нету, а насчёт последнего, ну, ladno.

Если их нету, это не значит, что мы их не делаем. У нас сейчас переходит на иконку в руке и икноку в мире. Палитра у нас Аврора и Сплендор, все информация по ним есть в спрайт канале дискорда.

2024-09-24 06:35 UTC, Bobloxer2009 commented
Bruh. Я тут короче впал в апатию и лень, но про огурцы **не забыл**, я обязательно их доделаю если что, осталось лишь спрайт нацепить с нужной палитрой и кайфуем, может сегодня уже доделаю. Ну не переживайте, огурцы будут, всем фанатам огурцов привет, остальные становитесь такими же.

2024-09-26 05:45 UTC, Bobloxer2009 commented
Хз зачем таке, но пусть буде короче.

2024-09-26 06:03 UTC, Bobloxer2009 commented
Короче спрайт поменял, а там чёто ещё сломалось, ну мейнтейнеры ребята не глупые, проверят, теперь ждём спрайтдеп и кайфуем с огурцами

2024-09-26 06:13 UTC, Danistans commented
+ Огурцы
- Прометей
😂

2024-09-27 14:55 UTC, WatlerJe approved these changes

2024-09-27 14:55 UTC, Ayaksblack commented
Допиши его в соавторы тогда

2024-09-27 15:05 UTC, KIBORG04 commented on code/modules/reagents/reagent_containers/food/snacks/grown.dm
> +	reagents.add_reagent("ethylredoxrazine", 3+round((potency / 10), 1))
Я о том, что цифры перекручены, а не про эффект

2024-09-28 06:28 UTC, Bobloxer2009 commented
Лютый баланс огурцов, очень баланс.

2024-09-29 04:32 UTC, merged