перевод шляп
TauCetiStation/TauCetiClassic pull request #13539
Opened 2024-09-11 12:14 UTC by AndroBetel

## Описание изменений
переводит папку clothing/head
## Почему и что этот ПР улучшит
перевод
## Авторство
ну я

## Чеинжлог
:cl:
 - ru: Переведены шляпы.

2024-09-11 12:14 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2024-09-11 12:50 UTC, maleyvich commented on code/modules/clothing/head/soft_caps.dm
> +	cases = list("кепка НТ ЧВК", "кепки НТ ЧВК", "кепке НТ ЧВК", "кепку НТ ЧВК", "кепкой НТ ЧВК", "кепке НТ ЧВК")
мне кажется или должно быть чвк НТ, хотя хер его знает

на ваше усмотрение!

2024-09-11 13:25 UTC, WhaleNotPower commented on code/modules/clothing/head/hardhat.dm
> +	cases = list("пожарный шлем", "пожарного шлема", "пожарному шлему", "пожарный шлем", "пожарным шлемом", "пожарном шлеме")
> Просьба поменять местами, вот пример: [картинка примера]

И как это по твоему выглядеть должно? Шлемом пожарным?

2024-09-11 13:32 UTC, simb11 commented on code/modules/clothing/head/helmet.dm
> +	desc = "Шлем, собранный на коленке из пары листов металла и бюраткани."
```suggestion
	desc = "Шлем, собранный на коленке из пары листов металла и дюраткани."
```

2024-09-11 18:18 UTC, Kiromaka commented
Главный хейтер перевода залил шляпу на 500 строк.....

2024-09-11 19:16 UTC, Kiromaka requested changes

2024-09-11 19:16 UTC, Kiromaka commented on code/modules/clothing/head/jobs.dm
> +	desc = "Прекрасная минималистическая повязка."
```suggestion
	desc = "Прекрасная минималистичная повязка."
```

2024-09-11 19:16 UTC, Kiromaka commented on code/modules/clothing/head/misc.dm
> +	desc = "Такие головные уборы носили чумные доктора, предпочитавшие лекарствам пламя костров. В двадцать третьем веке подобные чудовищные врачебные практики, конечно, в прошлом: теперь у лекарей в ар
Ну доктора людей не жгли, только трупы, но ладно - flavor.

2024-09-11 19:16 UTC, Kiromaka commented on code/modules/clothing/head/misc.dm
> +	desc = "Вы кроль." //    desc = "Wearing these makes you looks useless, and only good for your sex appeal." - REMOVED BY ERP POLICE.
noooo me erp

2024-09-11 19:16 UTC, Kiromaka commented on code/modules/clothing/head/misc.dm
> +	desc = "Яр-р."
Вообще принято Ар-р.

2024-09-11 19:16 UTC, Kiromaka commented on code/modules/clothing/head/misc.dm
> +	desc = "Кудах!"
Хорошо, что не поак!

2024-09-11 19:16 UTC, Kiromaka commented on code/modules/clothing/head/misc.dm
> +	desc = "Шлем, сделанный из хитиновой шкуры чужого."
Вообще из кожи, бери в пример кроков, у них нету шкуры - т.к. шукра подразумевает шерсть, а кроки лысые, как и ксеносы.
![image](https://github.com/user-attachments/assets/59b69524-dbff-4a5c-857d-d664273e12a5)

2024-09-11 19:28 UTC, AndroBetel commented on code/modules/clothing/head/misc.dm
> +	desc = "Шлем, сделанный из хитиновой шкуры чужого."
написано в оригинале hide а не skin/leather что значит шкура

2024-09-11 22:08 UTC, Kiromaka commented on code/modules/clothing/head/misc.dm
> +	desc = "Шлем, сделанный из хитиновой шкуры чужого."
В оригинале просто хуйня, да и значения hide и шкура не идентичны +- прямой перевод но на русском шкура - срез кожи с шерстью, насчет точного значения hide на английском не уверен, наверно так-же, просто автор даун.

2024-09-11 22:35 UTC, AndroBetel commented on code/modules/clothing/head/misc.dm
> +	desc = "Шлем, сделанный из хитиновой шкуры чужого."
поменял на хитин

2024-09-16 18:38 UTC, AndroBetel commented
ждем мержа #13348

2024-11-11 02:36 UTC, closed without merging