Обновление эвакуационного шаттла.
TauCetiStation/TauCetiClassic pull request #13551
Opened 2024-09-22 18:41 UTC by Venngedi

## Описание изменений
**Тамбур**
Заменил столик с ненужным тулбоксом на шкаф с ЕРВОСом.
![image](https://github.com/user-attachments/assets/3b9b7cf1-d89f-4af4-ad50-035965a76910)
**Мостик**
Поставил ящик с другим изображением. Для разнообразия. Убрал аптечку (на стене висит НаноМед). Добавил терминал гостевых пропусков. 
![image](https://github.com/user-attachments/assets/977bbf15-1da6-44a9-88c9-f31ad8731ae9)
**Пассажирский салон**
Заменил пластмассовые шторы на шлюзы. Воздух будет гулять меньше.
![image](https://github.com/user-attachments/assets/4837d417-93b9-4c1b-a7b2-86e8c417a705)
**Инженерный отсек**
Убрал шкаф с инструментами, поставил ящик с материалами. Положил на соседний стол фуелпак. Убрал встроенный зарядник.
![image](https://github.com/user-attachments/assets/c527a21f-5e97-4287-8f65-8731aea3bf95)
Нерабочую зарядку для аккумуляторов оставил.
https://github.com/TauCetiStation/TauCetiClassic/blob/5a826819eac189fafc057db9141152e6873e2612/code/game/machinery/cell_charger.dm#L65
**VIP-зона**
Вместо VIP-зоны (которая на самом деле не ВИП, потому что туда мог сесть кто угодно) теперь стоят вендоматы и стол.
![image](https://github.com/user-attachments/assets/121dd81e-94f5-439f-b3f0-f627d676d622)
**Мед**
Убрал аптечку. Взамен поставил улучшенную версию волмеда. Добавил больше сидячих мест. Добавил бипасс. К нему переселил зарядник и дефиб.
![image](https://github.com/user-attachments/assets/f81dc884-fd5f-4464-a7ea-780bef00d282)

![image](https://github.com/user-attachments/assets/ff1c1404-48f1-4809-a5f4-f3c2aac43ba0)

И ещё у катволков появился звук.
## Почему и что этот ПР улучшит
QoL. Повысит выживаемость экипажа.
## Авторство
## Чеинжлог

 - map: Обновлён эвакуационный шаттл.

2024-09-22 18:42 UTC, TauKitty commented
###### Changelog status: :radio_button: No changelog

2024-09-22 19:22 UTC, Danistans commented
"Вип зона" какая-то прям неприятная стала, имхо. 

Может есть смысл её сделать реально вип-зоной, поставив на доступы карго? (А рядом кассу, за которой с терминалом сидит жадный КМ) :dovolen:

2024-09-22 19:44 UTC, WatlerJe commented
Еще кресла повернуть на 180 градусов и хорошо будет.

2024-09-22 20:23 UTC, Ayaksblack commented
Шторки жалко(

2024-09-22 20:59 UTC, MrPerenka commented
> "Вип зона" какая-то прям неприятная стала, имхо.
> 
> Может есть смысл её сделать реально вип-зоной, поставив на доступы карго? (А рядом кассу, за которой с терминалом сидит жадный КМ) :dovolen:

Реально. Даешь крутую зону, вместо унылой копирки со станции! 
Предлагаю что-то такое, тоже на доступе глав
![image](https://github.com/user-attachments/assets/afa75d86-02ff-4c50-aa3d-651a42e7011c)

2024-09-22 21:20 UTC, Venngedi commented
> Еще кресла повернуть на 180 градусов и хорошо будет.

Какие именно кресла тебе не понравились?

2024-09-22 21:24 UTC, volas commented
у нас кресла стоят против движения, хотя должно быть наоборот, хз чей косяк. Хотя так кукл лучше видно.

2024-09-22 21:34 UTC, Venngedi commented
> "Вип зона" какая-то прям неприятная стала, имхо.
> 
> Может есть смысл её сделать реально вип-зоной, поставив на доступы карго? (А рядом кассу, за которой с терминалом сидит жадный КМ) :dovolen:

Смысл есть, но человека туда сажать не надо. Приложил карту - прошёл. Как в душе

> > "Вип зона" какая-то прям неприятная стала, имхо.
> > Может есть смысл её сделать реально вип-зоной, поставив на доступы карго? (А рядом кассу, за которой с терминалом сидит жадный КМ) :dovolen:
> 
> Реально. Даешь крутую зону, вместо унылой копирки со станции! Предлагаю что-то такое, тоже на доступе глав ![image](https://private-user-images.githubusercontent.com/125875249/369717315-afa75d86-02ff-4c50-aa3d-651a42e7011c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcwNDAzMDQsIm5iZiI6MTcyNzA0MDAwNCwicGF0aCI6Ii8xMjU4NzUyNDkvMzY5NzE3MzE1LWFmYTc1ZDg2LTAyZmYtNGM1MC1hYTNkLTY1MWE0MmU3MDExYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyMlQyMTIwMDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04YTE4NzQxZTBjNjdlOTY2MTkxYjIyZDYwYjEyYTQxY2VkMjJlNTQ5N2EyMzliZDlkOTgxOTFiYzliMDk2ZWQ2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.QBuvDOhB3Tn_EvA7DnyaJ3PnKYijXblQ57xZTjLDWDM)

У глав есть своя крутая комната с не менее крутым мерцающим ЭЛТ телевизором. VIP-зона будет, но точно не такая

2024-09-23 00:19 UTC, KIBORG04 commented
Предлагаю заменить вип зону на церковь https://github.com/TauCetiStation/TauCetiClassic/pull/7890

2024-09-23 14:54 UTC, LudwigVonChesterfield commented
![image](https://github.com/user-attachments/assets/0395ad5b-bccc-4fb3-a40f-801db118201c)

я всегда думал что шкафчик там чтобы прятаться

2024-09-23 15:04 UTC, Venngedi commented
> ![image](https://private-user-images.githubusercontent.com/17705613/369930300-0395ad5b-bccc-4fb3-a40f-801db118201c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcxMDM1NzcsIm5iZiI6MTcyNzEwMzI3NywicGF0aCI6Ii8xNzcwNTYxMy8zNjk5MzAzMDAtMDM5NWFkNWItYmNjYy00ZmIzLWE0MGYtODAxZGIxMTgyMDFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTIzVDE0NTQzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA2NGI0ZDJjZWJjMjQ4MDQyNDAzZWQ0MGI0ZTJjNWYxMTdkNDhhZWQxZjZlOTU1MTdlMzBhM2Q3Y2Q0MDIwNDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Rvtl-evNFRn2bunCb0besus6il3lnvg3HwoV3EAbPD0)
> 
> я всегда думал что шкафчик там чтобы прятаться

Теперь в ящики тоже можно залезать

2024-10-01 14:33 UTC, Udokun commented
Раз делаешь полный фикс шаттла, может что-то и для СБ придумать?

2024-10-02 13:25 UTC, Venngedi commented
> Раз делаешь полный фикс шаттла, может что-то и для СБ придумать?

В том отсеке я немного освободил место на столе, перевесив зарядник на стену. Остальное там менять незачем

2024-10-19 12:49 UTC, KatoMarika requested changes
![image](https://github.com/user-attachments/assets/d7dd8c30-d91b-4077-9c76-189c0577284a)
Нет. Просто нет.

2024-10-29 09:31 UTC, Udokun commented
> Но если более серьезно: ![image](https://private-user-images.githubusercontent.com/18484142/378082472-d431b698-59ef-4b49-970d-e2ce5a4767df.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAxOTQ1NDIsIm5iZiI6MTczMDE5NDI0MiwicGF0aCI6Ii8xODQ4NDE0Mi8zNzgwODI0NzItZDQzMWI2OTgtNTllZi00YjQ5LTk3MGQtZTJjZTVhNDc2N2RmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI5VDA5MzA0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU4ZWRkNjk4NGQ0MWJlMGU4NjRjMDA0YTY5OWQ3ZmJhMGRhMmQzODU4OWJkMzBiOGVkYzJhNGZjMDdlMGEwYTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Udn82HpZYDVC4KuPQu59XfbZlZEXqs8_XheeRBrZ_fo) Шатл полный затылков так себе идея и в этом мнении я не один, можно почитать маперский канал. Нет шкафа в конце шатла в котором можно спрятаться, Тулбокс при входе кое-что позволял сделать, теперь нельзя и придется тащить свой тулбокс. Удаление шторок лишает клоуна или людей с мылом возможности хаоса на шатле.
Придётся направление шаттла менять.

2024-11-06 06:22 UTC, DarthSidiousPalpatine commented
> я всегда думал что шкафчик там чтобы прятаться

Спецом восстановил пароль к Гиту чтобы ответить - так теперь в горизонтальных ящиках тоже можно прятаться. Не вижу проблем.

2024-11-06 06:27 UTC, DarthSidiousPalpatine commented
А у меня вопрос... А возможно сделать карго трубу на шаттл? Тип, на шаттле выходная фигня и обрезок трубы уходит в космос. И на станции труба выходит обрезком в космос. Когда шаттл стыкуется, то трубы соединяются.

Зачем? Из морга прямой рейс до шаттла сделать в медицинский отсек. Было бы забавно и доп. возможность спастись в экстренной ситуации. Ну или долететь трупом.

2024-11-08 11:45 UTC, Venngedi commented
> Удаление шторок лишает клоуна или людей с мылом возможности хаоса на шатле.

Когда клоун бросает мыло под шторки и закрывает их? Его очень быстро убирают. Да и давно такого не видел...

2024-11-08 11:50 UTC, Venngedi commented
> А у меня вопрос... А возможно сделать карго трубу на шаттл? Тип, на шаттле выходная фигня и обрезок трубы уходит в космос. И на станции труба выходит обрезком в космос. Когда шаттл стыкуется, то трубы соединяются.
> 
> Зачем? Из морга прямой рейс до шаттла сделать в медицинский отсек. Чтобы трупы доставить. Типа никого нельзя оставить на станции при эвакуации. Было бы забавно и доп. возможность спастись в экстренной ситуации. Ну или долететь трупом. Ну или шаттл улетел и ты вылетаешь из трубы в космос, не успев на шаттл. Хехе.

Очень лёгкий способ избавиться от тела или головы

2024-11-15 19:35 UTC, UsadoSmokk commented
> Но если более серьезно: ![image](https://private-user-images.githubusercontent.com/18484142/378082472-d431b698-59ef-4b49-970d-e2ce5a4767df.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE2OTk0OTUsIm5iZiI6MTczMTY5OTE5NSwicGF0aCI6Ii8xODQ4NDE0Mi8zNzgwODI0NzItZDQzMWI2OTgtNTllZi00YjQ5LTk3MGQtZTJjZTVhNDc2N2RmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE1VDE5MzMxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFjMjZmM2EwMzk3OTEyMTQxZTE5MWIyYTkwZWYwZTg0ZDA2YWZkNzNlODRmZGY5NjA0OWYxMTM4NjFlNTc0NjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ke6cmWNLLLf8idOX6_WwB9nHl0OcySrpiyJp9YQPcko) Шатл полный затылков так себе идея и в этом мнении я не один, можно почитать маперский канал. Нет шкафа в конце шатла в котором можно спрятаться, Тулбокс при входе кое-что позволял сделать, теперь нельзя и придется тащить свой тулбокс. Удаление шторок лишает клоуна или людей с мылом возможности хаоса на шатле.

то самое чувство, когда спецом сделал скрытый шкафчик, а про него все забыли-......

2024-12-07 02:46 UTC, closed without merging