[HOLY SHIT!]Charlie, lets go to candy mountain, charlie!
TauCetiStation/TauCetiClassic pull request #13552
Opened 2024-09-25 02:13 UTC by TriflesChase

## Описание изменений
Переносит "organ" в "surgery", ради красоты
Добавляет слоты для органов, спрайты органов, пару базовых имплантов, операции.
Почти не затронуты СПУ и дион, потому что этим следует заниматься кому то другому
При желании можно переработать большую часть, добавить или убрать
И в общем, просто добавит чуть более динамичные и ?ВЕСЁЛЫЕ? органы, основанные на парадизах, которые основаны на тг

## Почему и что этот ПР улучшит
динамичные органы, база для новых имплантов, переработки хирургии и другого
сломает хирургию, мобов, органы и жизнь
## Авторство
Aurorablade с англо парадайзов, откуда взята большая часть кода и спрайты, а так же сам ПР на который опиралась:
https://github.com/ParadiseSS13/Paradise/pull/2903
## Чеинжлог
:cl:
 - add: Динамичная и сломанная система органов
 - image: Спрайты органов для всех рас(пока мы их не обновим)
-->

2024-09-25 02:13 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2024-09-25 02:35 UTC, maleyvich commented
КРУТО

2024-09-25 07:21 UTC, DarkFurrSss commented
Наконец-то смогу собрать коллекцию почек со всей станции

2024-09-25 10:39 UTC, KIBORG04 commented
А можно, чтобы было не сломано?

2024-09-26 08:51 UTC, WatlerJe commented
ТГ спрайты нам не подходят, сейчас занимаюсь новыми на основе тех, что делал Малевичу.

2024-09-26 14:06 UTC, Chip11-n commented on code/game/gamemodes/modes_gameplays/changeling/evolution_menu.dm
>  /mob/proc/remove_changeling_powers(keep_free_powers=0)
Либо сейчас, либо потом такие комменты тебя попросят удалить

2024-09-26 14:07 UTC, Chip11-n commented
Оно WIP?

2024-09-30 17:11 UTC, TriflesChase commented
> А можно, чтобы было не сломано?
Теперь у СПУ мозг корректно переходит в позитроник при гибе, а дионы в нимфу

2024-09-30 17:12 UTC, TriflesChase commented on code/game/gamemodes/modes_gameplays/changeling/evolution_menu.dm
>  /mob/proc/remove_changeling_powers(keep_free_powers=0)
Все похожие комментарии удалены

2024-09-30 17:12 UTC, TriflesChase commented on code/modules/surgery/organs/organ_internal.dm
> +			M.internal_organs_slot.Remove(slot)
У нас есть сами органы и так же слоты под них, это разное, используется для глаз и имплантов для них, в основном.

2024-09-30 17:12 UTC, TriflesChase commented on code/game/gamemodes/modes_gameplays/changeling/powers/augmented_eyesight.dm
> +	return TRUE
генокрады научились удалять свои глаза, теперь не должны показываться?

2024-09-30 17:13 UTC, TriflesChase commented on code/modules/surgery/eye.dm
> +		I.remove(target)
Оно вроде не вызывает ошибок или рантаймов, во время тестов именно на эти проки
И с органами тоже, они не получали урон, если их нет

2024-09-30 17:13 UTC, TriflesChase commented on code/modules/mob/living/carbon/carbon.dm
> +			emote("gasp")
Исправила, мартышки не задыхаются, а люди да

2024-09-30 17:14 UTC, TriflesChase commented on code/modules/surgery/organs/augments_internal.dm
> +		src.insert_organ(M)
Исправлено

2024-09-30 17:14 UTC, TriflesChase commented on code/modules/surgery/eye.dm
> +				user.visible_message("it work")
Удалено

2024-09-30 17:14 UTC, TriflesChase commented on code/modules/surgery/organs/organ.dm
>  	var/list/obj/item/organ/internal/organs_by_name = list()
У меня не получилось заставить работать только на людях
И собираюсь в будущем добавить органы мартышкам

2024-10-01 14:02 UTC, WatlerJe approved these changes

2024-10-07 16:42 UTC, DarkFurrSss commented
> > А можно, чтобы было не сломано?
> 
> Теперь у СПУ мозг корректно переходит в позитроник при гибе, а дионы в нимфу
> 

А у особкового в нормальный мозг?

2024-10-07 19:34 UTC, Kiromaka approved these changes
Новые фичи nice, жалко на основе парадизов. Перевод просить не буду, апрув английского. Еще это WIP, видимо - где тег в названии?

2024-10-10 12:01 UTC, WatlerJe approved these changes

2024-10-10 19:23 UTC, TriflesChase commented
> 
> А у особкового в нормальный мозг?

В mmi, спасибо, что напомнил про особку

2024-10-10 19:25 UTC, TriflesChase commented
> Новые фичи nice, жалко на основе парадизов. Перевод просить не буду, апрув английского. Еще это WIP, видимо - где тег в названии?

I missed it. Но код уже завершён и ничего не собираюсь добавлять больше. Если только не исправить часть логики кода, наверное?

2024-10-10 21:26 UTC, TriflesChase commented
>
> Ты можешь глянуть, в Боди сканере ничего не сломалось касательно добавленных тобою органов, если там всё нормально отображается, то всё окей.

Да, проверила, если органов не будет в теле, они просто не будут показываться в сканере

2024-10-10 21:30 UTC, TriflesChase commented
Сразу после плувийцев и добавления и для них органов

2024-10-13 12:49 UTC, KIBORG04 commented on code/modules/mob/living/carbon/human/human_damage.dm
> +
Зона - это зона. Это часть тела. organs_by_name же хранит название органа по органу, мы не может получить орган, зная часть тела, используя этот лист.
Крч, прок не работает, всегда возвращать нулл будет

2024-10-13 12:51 UTC, KIBORG04 commented on code/modules/mob/mob_defines.dm
> +	var/weakeyes	//Are they vulnerable to flashes?
Мы же вроде реворкаем ограны, почему эта переменная в /mob вообще, а не в органе глаз?

2024-10-13 12:51 UTC, KIBORG04 commented on code/game/gamemodes/modes_gameplays/changeling/powers/augmented_eyesight.dm
> +	..()
А потом орган присваивает значение этой переменной у хумана, жесть

2024-10-13 12:52 UTC, KIBORG04 commented on code/game/machinery/flasher.dm
> +					O.Weaken(strength * 1.5)
А могло бы быть IO.weakeyes

2024-10-13 12:54 UTC, KIBORG04 commented on code/modules/surgery/appendix.dm
> +/*
за что аппендицит..

2024-10-13 13:00 UTC, KIBORG04 commented on code/modules/surgery/implant.dm
> +	var/obj/item/organ/internal/I = null
Что ето и зачем

2024-10-13 13:00 UTC, KIBORG04 commented on code/modules/surgery/implant.dm
> +
```suggestion
```

2024-10-13 13:01 UTC, KIBORG04 commented on code/modules/surgery/organs/augments_internal.dm
> +	owner << "<span class='warning'>You feel like your insides are burning.</span>"
Ноу комментс

2024-10-13 13:15 UTC, KIBORG04 requested changes
Убедительно прошу автора разбить ПР всё же на механо-часть(базу) и контенто-часть. 

Я вижу тут какие-то имлпанты, технологии РНД, кибер тела, кучу хирургических операций к ним, кучу кода, который еще надо хоть как-то отбалансить. 
Есть как полезный код c рефактором объемных кусков, так и совершенно отстранённые от него технологии.
Я думаю, разделить код на два ПРа не займет много труда, зато облегчит дальнейшую разработку как с твоей стороны, так и с нашей, ревьюверско-тестерской. Нам тупо лень даже начинать ревьювить это чудо на 1600 диффа, это даже видно из того, что за 3! недели особо никто так и не посмотрел ничего, а править тут можно многое.

TLDR: убери из этого ПРа всякие имплатны, рнд технологии, глаза шедоулинга и вот всякое такое, а органы людей, рас оставь

2024-10-13 13:20 UTC, KIBORG04 commented on code/datums/mutable_appearance.dm
> +	alpha = 255
тоже не используется

2024-10-13 13:25 UTC, KIBORG04 commented on code/datums/mutable_appearance.dm
> +/proc/mutable_appearance(icon, icon_state = "", layer = FLOAT_LAYER, alpha = 255, plane = FLOAT_PLANE, color)
Добавляя новый аргумент `alpha` до `plane` мы рискуем, что в каком-то создании mutable_appearance будет передаваться плейн (int) в альфу (int) и что-то сломается.
И мы не то что рискуем, а так оно и есть. Да и я так же не заметил, чтобы эти новые альфа и колор как-то менялись или использовались, мб просто не нашел /shrug

2024-10-13 17:35 UTC, TriflesChase commented on code/modules/surgery/organs/organ_helpers.dm
> +	return organs_by_name[tag_to_check]
organs_by_name не работает при проверке лёгких для дыхания

2024-10-13 17:35 UTC, TriflesChase commented on code/modules/surgery/organs/organ_helpers.dm
> +			return O
Оказался не нужным, удалила

2024-10-13 17:35 UTC, TriflesChase commented on code/modules/surgery/organs/organ_helpers.dm
> +	return istype(A, /obj/item/organ/internal)
Удалено

2024-10-13 17:36 UTC, TriflesChase commented on code/modules/surgery/organs/organ_helpers.dm
> +	return (locate(typepath) in organs_by_name)
Потому что иначе не работает в некоторых местах

2024-10-13 17:36 UTC, TriflesChase commented on code/datums/mutable_appearance.dm
> +	alpha = 255
Удалено

2024-10-13 17:36 UTC, TriflesChase commented on code/datums/mutable_appearance.dm
> +/proc/mutable_appearance(icon, icon_state = "", layer = FLOAT_LAYER, alpha = 255, plane = FLOAT_PLANE, color)
Удалено

2024-10-13 17:36 UTC, TriflesChase commented on code/modules/surgery/appendix.dm
> +/*
Когда ни будь вернётся

2024-10-13 17:37 UTC, TriflesChase commented on code/modules/mob/living/carbon/human/human_damage.dm
> +
Починила, пропустила этот момент

2024-10-13 17:40 UTC, closed without merging