Добавлен улучшенные лопаты
TauCetiStation/TauCetiClassic pull request #13565
Opened 2024-10-05 17:38 UTC by Riverz1

## Описание изменений
В ветку исследования добавленные улучшение лопаты которые значительно повышают скорость копания мусора песка и т д
## Почему и что этот ПР улучшит
Больше взаимодействий с РНД и карго, а также более активный гемплей за мусорщика
## Авторство

Riverz

## Чеинжлог

:cl: Riverz
 - rscadd: Добавлена улучшенна лопата
 - sprite: Перемаплен такой-то отсек.

2024-10-05 17:38 UTC, TauKitty commented
###### Changelog status: :x: Invalid changelog classes (sprite)

2024-10-05 17:51 UTC, Chip11-n commented on code/modules/mining/mine_items.dm
> +	name = "experimental shove"
```suggestion
	name = "experimental shovel"
```

2024-10-05 17:51 UTC, Chip11-n commented on code/modules/mining/mine_items.dm
> +
Стоит оставить только те переменные, которые были изменены.

2024-10-05 17:51 UTC, Chip11-n commented on code/modules/mining/mine_items.dm
> +	toolspeed = 0.1
У нас случаем не выйдет так, что лопата - лучший дом?

2024-10-05 17:52 UTC, Riverz1 commented on code/modules/mining/mine_items.dm
> +	toolspeed = 0.1
Что ты имеешь ввиду под лучший дом?

2024-10-05 17:52 UTC, Riverz1 commented on code/modules/mining/mine_items.dm
> +
Я её тоже изменил она была 0.7

2024-10-05 18:14 UTC, Chip11-n commented on code/modules/mining/mine_items.dm
> +	toolspeed = 0.1
Кхм, лучший лом на любой ду афтер

2024-10-05 18:15 UTC, Chip11-n commented on code/modules/mining/mine_items.dm
> +
Айкон, слот флаг, атак верб, форс и т.д.

2024-10-05 18:21 UTC, Riverz1 commented on code/modules/mining/mine_items.dm
> +	toolspeed = 0.1
Возможно, а почему не сделать это фичей?)

2024-10-05 19:44 UTC, Chip11-n commented on code/modules/mining/mine_items.dm
> +	toolspeed = 0.1
Пофиг, я в деле. Механобоберы будут смешными

2024-10-06 08:18 UTC, Riverz1 commented on code/modules/mining/mine_items.dm
> +	toolspeed = 0.1
Готово

2024-10-06 08:18 UTC, Riverz1 commented on code/modules/mining/mine_items.dm
> +
Сделано

2024-10-08 18:33 UTC, Chip11-n approved these changes
Не знаю насколько оно будет смешно ппо балансу, но идея имеет право на жизнь.

2024-10-08 18:35 UTC, Chip11-n commented
Чейнжлог только кривой. Лучше просто оставь одну строку с фичей, оно и так понятно, что спрайт добавляется к лопате.

2024-10-08 19:20 UTC, Riverz1 commented
> Чейнжлог только кривой. Лучше просто оставь одну строку с фичей, оно и так понятно, что спрайт добавляется к лопате.

Исправил

2024-10-10 11:59 UTC, WatlerJe approved these changes

2024-10-11 01:07 UTC, ZER0-In commented
Прикольно. Мне нравится. Но анимация лопаты выглядит, как циркулярка. Он наносит хороший брут урон?

2024-10-11 09:40 UTC, Riverz1 commented
> Прикольно. Мне нравится. Но анимация лопаты выглядит, как циркулярка. Он наносит хороший брут урон? Может ему увеличить урон больше, чем у лопаты. Приблизительно равный урону копья?

Возможно, но по-моему я скоро реально превращу эту лопату имбу которая будут все использовать)

2024-10-11 11:58 UTC, Kiromaka commented
In world спрайт большеват конечно

2024-10-19 03:24 UTC, volas commented
У тебя лишние изменения в DMI и конфликты. Учитывая, что ты уже поставил хукмержи, тебе будет наверно проще пересоздать пр.

2024-10-19 03:25 UTC, volas commented
И на будущее - никогда не исправляй мерж-конфликты в dmi руками с перезаливками файлов.

2024-10-19 03:25 UTC, volas requested changes
выше

2024-10-19 12:58 UTC, WatlerJe requested changes
Добавь ворлд иконку.

2024-10-20 07:37 UTC, Riverz1 commented
> У тебя лишние изменения в DMI и конфликты. Учитывая, что ты уже поставил хукмержи, тебе будет наверно проще пересоздать пр.

попробую

2024-10-20 07:37 UTC, closed without merging