bodytype selection for w*mans
TauCetiStation/TauCetiClassic pull request #13607
Opened 2024-10-25 21:17 UTC by simb11

## Описание изменений
Добавляет людям-женщинам возможность выбрать телосложение (худое и классическое).

![image](https://github.com/user-attachments/assets/027f419e-2700-4327-90ea-153f76eb0b52)
![image](https://github.com/user-attachments/assets/aca5648e-ebfc-4222-b7a8-3a8c50a4adca)

Выбора для ксенорас нету, у всех женщин-ксеносов (кроме скреллов) худое телосложение.
## Почему и что этот ПР улучшит
Не все хотят играть за тонких баб с большими tits и ass
## Авторство

## Чеинжлог
🆑 Simbaka
- add: Выбор телосложения для женщин-людей.

2024-10-25 21:17 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2024-10-25 21:24 UTC, Deahaka commented
Бля это рофл?

2024-10-25 22:45 UTC, AndroBetel commented
а мужикам

2024-10-31 10:30 UTC, WatlerJe requested changes
Честно говоря не догоняю зачем нужен еще один тип тела для фемок, какой-то wokeshit. В любом случае используются старые спрайты нижнего белья, их надо перерисовать в соответствии с новыми.

2024-11-09 12:46 UTC, closed without merging