фикс дробинок
TauCetiStation/TauCetiClassic pull request #13679
Opened 2024-12-12 09:17 UTC by maleyvich

## Описание изменений
тайтл, слово ПАТРОН заменено на дробинка, да и выглядит получше в целом, resolves https://github.com/TauCetiStation/TauCetiClassic/issues/13468
## Почему и что этот ПР улучшит
улучшаем перевод таусети
## Авторство
я

## Чеинжлог
не нужен

2024-12-12 10:07 UTC, AmnyamNyam requested changes

2024-12-12 10:07 UTC, AmnyamNyam commented on code/modules/projectiles/ammunition/bullets.dm
> +	desc = "Дробинка 12-го калибра типа \"жакан\"."
**ХУИНКА**

Малевич, дробинки - это содержимое патрона.
"Жака́н — самодельная тяжёлая пуля для стрельбы из гладкоствольного ружья." - цитата из Википедии.

Верни к оригиналу как было, ибо это технически правильно.

Только убери отовсюду ОТ 12-го калибра

2024-12-12 10:07 UTC, AmnyamNyam commented on code/modules/projectiles/ammunition/bullets.dm
> +	desc = "Дробинка 12-го калибра типа \"жакан\"."
```suggestion
	desc = "Патрон 12-го калибра типа пуля."
```

2024-12-12 10:07 UTC, AmnyamNyam commented on code/modules/projectiles/ammunition/bullets.dm
> +	desc = "Дробинка 12-го калибра типа \"травмат\"."
```suggestion
	desc = "Патрон 12-го калибра типа травматический."
```

2024-12-12 10:37 UTC, WatlerJe commented
Правильно именно Пуля, а не Жакан

![image](https://github.com/user-attachments/assets/3f8269d6-f12b-48f8-82a7-dbbe20065c10)
Пример.

2024-12-12 11:17 UTC, maleyvich commented on code/modules/projectiles/ammunition/bullets.dm
> +	desc = "Патрон 12-го калибра типа \"жакан\"."
```suggestion
	desc = "Патрон 12-го калибра типа \"пуля\"."
```

2024-12-12 11:25 UTC, simb11 commented on code/modules/projectiles/ammunition/bullets.dm
> +	desc = "Патрон 12-го калибра типа \"картечь\"."
почему не просто дробь

2024-12-12 11:25 UTC, simb11 commented on code/modules/projectiles/ammunition/bullets.dm
> +	desc = "Патрон 12 калибра типа \"флешетта\"."
почему не просто дротик

2024-12-12 11:31 UTC, simb11 commented
и ещё возможно надо будет перевести /obj/item/ammo_box/shotgun потому что там эм почти теж самые слова используется

2024-12-12 11:38 UTC, maleyvich commented on code/modules/projectiles/ammunition/bullets.dm
> +	desc = "Патрон 12-го калибра типа \"картечь\"."
дробь и картечь хоть и очень похожие понятия но всё-же различающиеся
пусть останется как было..

2025-01-15 11:10 UTC, AmnyamNyam approved these changes
Не знаю почему в листе с падежами типы патронов с большой буквы, а в описании предмета - с маленькой.

Но это уже из разряда дрочева.

Апрувед?

2025-01-15 13:31 UTC, maleyvich commented
нет мне лень мержьте ааааа

2025-01-23 22:39 UTC, merged