Фикс абсолютно всех проблем с билдом и его поддержкой.
TauCetiStation/TauCetiClassic pull request #1367
Opened 2017-04-12 13:00 UTC by igigin

В свете последних срачей.

Время пришло. В этот раз, не забудьте дать потестить комьюнити, вдруг понравится.

Ту Зве: много пропустил и много упустил, но повтор того стоит, гарантирую.

2017-04-12 13:00 UTC, dearprincesscelestia commented
В плане спрайтов - идеальный ПР.

2017-04-12 13:24 UTC, ZVee commented
Я прошлый видел, так что второй раз уже неинтересно. Третий раз будет перебор уже повторять эту шутку.

2017-04-12 13:32 UTC, igigin commented
Это чисто к последним конфосрачам. Я бы переоткрыл тот, если бы не засрал ветку.

2017-04-13 08:02 UTC, igigin commented
Срач закончен, спускаем флаги.

2018-01-27 11:04 UTC, igigin commented
Срачи начаты, поднять паруса!
@Kurshan с тебя апрув.
@Raschert0 с тебя мерж.

2018-01-27 11:04 UTC, Raschert0 approved these changes
Я передумал, пусть Куршан мержит :pekahiding:

2018-01-27 11:05 UTC, Kurshan approved these changes
Давно пора

2018-01-27 11:19 UTC, volas commented
ой, что это за кнопка

2018-01-27 11:20 UTC, igigin commented
Ето война.

2018-01-27 11:22 UTC, volas commented
ой, опять!

2018-01-27 11:24 UTC, igigin commented
Кнопка есть, за её нажатие не банят.

2018-01-27 11:25 UTC, volas requested changes
В процессе ревью, не мержить :peka:

2018-01-27 11:25 UTC, Kurshan commented
BACKSTAB

2018-01-27 11:25 UTC, closed without merging

2023-03-22 16:54 UTC, TauKitty commented
Этот запрос на слияние был упомянут в **Tau Ceti Station Forum**. Там могут быть соответствующие подробности:

https://forum.taucetistation.org/t/udalenie-simbaki-maksimalno-seryozno-pervyj-kommuniti-ban/38617/32

2026-07-19 10:26 UTC, Mercurialaste commented
Базу не замержили