airbag tweaks
TauCetiStation/TauCetiClassic pull request #13683
Opened 2024-12-20 18:03 UTC by simb11

## Описание изменений
Теперь airbag можно носить на шее
![image](https://github.com/user-attachments/assets/5d17c75f-31c7-4e55-b6ba-629d53b7a202)
и закутанный в защитную подушку человечик не получает урон от низкого давления.
## Почему и что этот ПР улучшит
Для слота шеи нет никаких функциональных предметов и это плохо.
И воздушная подушка теперь будет хоть сколько-то полезна.
## Авторство
Спрайты by Tobyan

## Чеинжлог
🆑 Simbaka, Tobyan
- tweak: Защитная подушка появляется в виде амулета, который можно носить на шее.
- tweak: Пока персонаж закутан в плёнку защитной подушки, он не получает урон от низкого давления.

2024-12-20 18:03 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2024-12-21 05:16 UTC, Chip11-n commented on code/modules/clothing/neck/ties.dm
> +	sleep(50)
Я тебя сейчас сожру

2024-12-25 09:50 UTC, volas requested changes

2024-12-25 09:50 UTC, volas commented on code/modules/atmospheric/ZAS/Airflow.dm
> +	var/obj/item/clothing/neck/airbag/I = locate() in get_contents()
может проверять именно слот шеи тут?

2024-12-25 09:50 UTC, volas commented on code/modules/clothing/neck/ties.dm
> +/obj/item/clothing/neck/airbag/proc/deploy(mob/user)
Если кукла попадет в airflow_hit() несколько раз, deploy() тут будет вызываться тоже несколько раз. 

Можно было бы добавить флаг активации и по нему предотвращать повторный вызов, избавит от каких-нибудь неожиданностей.

2024-12-25 09:52 UTC, volas commented on code/modules/clothing/neck/ties.dm
> +/obj/item/clothing/neck/airbag/proc/deploy(mob/user)
А хотя аирбаг должен успеть дропнуться из инвентаря, окно очень маленькое чтобы оно дважды активировалось. Но можно всё равно добавить проверку.

2024-12-25 11:17 UTC, simb11 commented on code/modules/atmospheric/ZAS/Airflow.dm
> +	var/obj/item/clothing/neck/airbag/I = locate() in get_contents()
считаю что это не нужно менять

2024-12-25 11:17 UTC, simb11 commented on code/modules/clothing/neck/ties.dm
> +/obj/item/clothing/neck/airbag/proc/deploy(mob/user)
сделал защиту от повторной активации

2024-12-26 05:05 UTC, volas commented on code/modules/atmospheric/ZAS/Airflow.dm
> +	var/obj/item/clothing/neck/airbag/I = locate() in get_contents()
get_contents() просто уходит в рекурсию и в теории не слишком быстрый прок, мне кажется излишним, ну ладно.

2024-12-26 05:05 UTC, merged