Изменения захватов в сторону баланса. Версия с голоуроном
TauCetiStation/TauCetiClassic pull request #5575
Opened 2020-06-13 17:35 UTC by cool20141

## Описание изменений
Слегка изменил шанс на то, чтоб вырваться из 3 захвата, добавил шанс (Хоть и небольшой) на то, чтобы вырваться из удушающего. Удушающий теперь не всегда будет жертву укладывать на пол, что даст шанс на самооборону. В данном ПРе также добавил небольшой голоурон, который наносится удерживающему с некоторым шансом
## Почему и что этот ПР улучшит
Меньше стан-вин механики
## Авторство
Cool20141
## Чеинжлог
:cl:
- balance: Возможность вырваться из удушающего захвата
- balance: Более высокие шансы на то, чтоб вырваться из 3 захвата
- balance: Шанс нанесения голоурона тому, кто удерживает в захвате

2020-06-13 17:35 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2020-06-13 17:37 UTC, LudwigVonChesterfield commented
Пожалуйста, не вноси шансы когда не знаешь как забалансить.

Был ПР на стамину у грабов, рекомендую его рассмотреть.

2020-06-13 17:39 UTC, cool20141 commented
Там 1000+ строк

2020-06-13 17:39 UTC, LudwigVonChesterfield commented
То есть я должен принимать полумеры только потому-что кому-то лень?

2020-06-13 17:40 UTC, cool20141 commented
Ок, хорошо, что конкретно в нем стоит рассмотреть?

2020-06-13 17:57 UTC, LudwigVonChesterfield commented
Там была такая шняга, что тот кто в граббе резистами сбивает стамину того кто держит в граббе, но при этом тот кто в граббе регенит стамину, а тот кто держит - нет. И в итоге чтобы держать кого-то в граббе нужно было ему заламывать руки(это понижает стамину того кто в грабе), бить, и так далее.

Мне такой подход нравится больше чем уга-буга шансы.

2020-06-13 18:03 UTC, cool20141 commented
Ну, я так понял, такая вещь (Возможно вкупе и с остальными изменениями ПРа) игрокам не понравилась, но ладно попробую ~~спиздить~~ перенять идеи

2020-06-13 18:22 UTC, LudwigVonChesterfield commented
Игрокам не понравился бег.

2020-06-13 18:30 UTC, Lizurt commented
> Игрокам не понравился бег.

Голосование показало, что игроки вообще не хотят видеть стамину на этом сервере ни в каком виде, а не только из за бега.

Полностью положиться на голосования, конечно, нельзя, но просто предупреждаю, что такая статистика имеет место быть.

2020-06-13 18:34 UTC, LudwigVonChesterfield commented
Ты им даже не показывал другой реализации, что они должны были сравнивать?

2020-06-13 18:39 UTC, Lizurt commented
> Ты им даже не показывал другой реализации, что они должны были сравнивать?

Показал, конечно. Была открыта локалка, к ней мог присоединиться любой желающий(зашло, кажется, 2 или 3 игрока). Также для тех, кому лень было заходить на локалку, в темке на форуме были описаны изменения после последнего ТМа ПРа на сервере тау.

Потестить же измененную стамину на сервере тау кеке не получилось - после просьбы обновить ТМ спейр его вообще снял.

2020-06-13 18:42 UTC, LudwigVonChesterfield commented
Я понимаю что с тобой вышла довольно грустная ситуация, но пожалуйста не отпугивая других контрибутеров от попыток.

Ты сам сейчас говорил, что твою другую версию тестило всего 3 человека.

Ящитаю что люди на форуме не способны оценить хотят ли они что-то прочитав сухой текст об этом, им стоит хотя бы чуть-чуть потыкаться.

Без обид, но мне кажется что ты пытаешься защищаться, ты чувствуешь обиду на то что твою имплементацию идеи не приняли, и (как мне кажется) пытаешься отстоять свою имплементацию говоря что не ты виноват - не имплементация плохая, а "идея говно", люди не захотели "идею", а не её конкретную реализацию.

Как минимум стамина в этом месте бы хорошо зашла, если будет сделана стамина на грабах - мы обязательно её потестим.

2020-06-13 18:44 UTC, Sakuya-Izayoi commented
Игрокам много чего не нравится в основном из-за того что это заставляет их думать, отказываться от старых стратегий и изобретать новые, в общем, выходить из зоны комофрта. Поэтому игроков стоит перестать слушать.

2020-06-14 05:57 UTC, cool20141 commented
В общем, стамину я добавил, но не ручаюсь, что совсем без огрех сделал (Потому что делал ночью на сонную голову)

2020-06-14 08:32 UTC, LudwigVonChesterfield commented on code/modules/mob/living/carbon/human/life.dm
> +			if(!is_grabbing)
Тебе не кажется странным что абсолютно все такие обновления в лайфе находятся в каких-то проках, а тут голым сидит обновление стамины?

2020-06-14 08:32 UTC, LudwigVonChesterfield commented on code/modules/mob/living/carbon/human/life.dm
> +			if(!is_grabbing)
И да, с взглядом в будущее. Я рекомендую сделать TRAIT_NOSTAMINAREGEN, и накидывать его в грабе, а не переменную...

2020-06-14 08:33 UTC, LudwigVonChesterfield commented on code/modules/mob/living/carbon/ian/ian.dm
> +	var/stamina_ian = 100
Эта переменная ни на что не влияет

2020-06-14 08:33 UTC, LudwigVonChesterfield commented on code/modules/mob/living/living.dm
> +				G.assailant.adjustStamina(resist_cost)
Тут кажется нужен минус?

2020-06-14 08:34 UTC, LudwigVonChesterfield commented on code/modules/mob/living/living.dm
> +				L.adjustStamina(resist_cost)
А почему мы увеличиваем стамину у того кто резистает?

Пожалуйста, пересмотри и потесть весь свой ПР...

2020-06-14 08:34 UTC, LudwigVonChesterfield commented on code/modules/mob/living/living_defines.dm
> +	var/is_grabbing = FALSE	//Either is grabbing or not
Пожалуйста не создавай переменные для того, что и так можно узнать.

2020-06-14 08:34 UTC, LudwigVonChesterfield commented on code/modules/mob/living/living_defines.dm
> +	var/resist_cost = -4 //Cost of grabs resisting
У нас точно нет какого-то более обобщенного способа узнавать кто сильнее, и кому сложнее вырваться?

2020-06-14 08:35 UTC, LudwigVonChesterfield commented on code/modules/mob/living/living_defines.dm
> +	var/stamina_damage = -8 //When twisting, headlocking and so on
У нас точно нет какого-то более обобщенного способа узнавать кто сильнее, и кому сложнее вырваться?

2020-06-14 08:35 UTC, LudwigVonChesterfield commented on code/modules/mob/living/living.dm
> +				L.adjustStamina(resist_cost)
Я увидел, минус в переменной резист_коста...

Мне это кажется чуть не интуитивным. Может стоит резист кост сделать позитивным, а тут поставить минус?

2020-06-14 08:35 UTC, LudwigVonChesterfield commented on code/modules/mob/living/living_defines.dm
> +
сюда закрался пробел

2020-06-14 08:36 UTC, LudwigVonChesterfield commented on code/modules/mob/mob_grab.dm
> +	var/grab_name
Ті не думаешь что каждый тик обновлять переменную, и не использовать её - как-то затратно?

2020-06-14 08:36 UTC, LudwigVonChesterfield commented on code/modules/mob/mob_grab.dm
> +		if(prob(25))
Это тут не нужно.

2020-06-14 08:38 UTC, cool20141 commented on code/modules/mob/living/carbon/ian/ian.dm
> +	var/stamina_ian = 100
Влияет, там у яна какие-то свои приколы с выносливостью (А я, видимо, забыл их переименовать)

2020-06-14 08:41 UTC, cool20141 commented on code/modules/mob/mob_grab.dm
> +		if(prob(25))
Почему нет? Типа шанс 25 процентов, что еще и "уложит" того, кого душат

2020-06-14 08:41 UTC, LudwigVonChesterfield commented on code/modules/mob/mob_grab.dm
> +		if(prob(25))
Зачем этот шанс нужен?

2020-06-14 08:44 UTC, cool20141 commented on code/modules/mob/mob_grab.dm
> +		if(prob(25))
Чтоб не 100% укладывал накидывал weaken, потому что когда weaken, то сопротивляться захвату нельзя

2020-06-14 08:50 UTC, LudwigVonChesterfield commented on code/modules/mob/mob_grab.dm
> +		if(prob(25))
Если кто-то смог дотянуть тебя до 3-го граба - абсолютно нормально что тебе нельзя сопротивляться...

2020-06-14 08:58 UTC, cool20141 commented on code/modules/mob/mob_grab.dm
> +		if(prob(25))
Почему же? Да и до 3 граба дотянуться–проще простого. Проскользил на воде какой-нибудь, а пока тот в стане быстренько скрутил. И это слишком, я считаю

2020-06-14 08:59 UTC, LudwigVonChesterfield commented on code/modules/mob/mob_grab.dm
> +		if(prob(25))
И вместо того чтобы нёрфить станы от воды, ты добавляешь какие-то дебильные шансы?

Почему я должен надеяться на шанс, чтобы выполнить действие?

Почему я не могу знать, что если я возьму в третий граб - противник всё?

Кому это весело?

2020-06-14 09:03 UTC, cool20141 commented on code/modules/mob/mob_grab.dm
> +		if(prob(25))
А кому весело быть задушенным без возможности спастись?

2020-06-14 09:03 UTC, cool20141 commented on code/modules/mob/living/carbon/human/life.dm
> +			if(!is_grabbing)
Трейт, типа как квирки?

2020-06-14 09:04 UTC, LudwigVonChesterfield commented on code/modules/mob/living/carbon/human/life.dm
> +			if(!is_grabbing)
Трейт и квирк это две разные системы

2020-06-14 09:05 UTC, LudwigVonChesterfield commented on code/modules/mob/mob_grab.dm
> +		if(prob(25))
У етбя не "возможностЬ" спастись, а "шанс" не быть задушенным. Пожалуйста не путай активные действия предпринимаемые игроком, и УГА БУГА ЛООЛ КАМНИ УПАЛИ ТЫ СДОХ

2020-06-14 09:06 UTC, cool20141 commented on code/modules/mob/living/carbon/human/life.dm
> +			if(!is_grabbing)
Я в traits.dm, который в _DEFINES
Или в другом месте?

2020-06-14 12:36 UTC, LudwigVonChesterfield commented on code/modules/mob/living/carbon/ian/ian.dm
> +		stamina_ian = max(0, stamina_ian - 10)
А зачем Яну отдельная стамина?

2020-06-14 12:36 UTC, LudwigVonChesterfield commented on code/modules/mob/living/carbon/ian/ian.dm
> +	var/stamina_ian = 100
Я не думаю что яну нужна отдельная стамина.

2020-06-14 12:36 UTC, LudwigVonChesterfield commented
А что ты думаешь об отображении стамины на интерфейсе?

2020-06-14 12:44 UTC, cool20141 commented
Ну, она используется только для захватов, а потому куда бы ее впихнуть, чтоб не захламляла интерфейс, не знаю

2020-06-14 12:45 UTC, cool20141 commented on code/modules/mob/living/carbon/ian/ian.dm
> +		stamina_ian = max(0, stamina_ian - 10)
Она существовала до ПРа, возможно, у нее какой-то отдельный функционал, который связывать с этой стаминой не стоит, я думаю

2020-06-14 13:37 UTC, LudwigVonChesterfield commented on code/modules/mob/living/carbon/ian/ian.dm
> +		stamina_ian = max(0, stamina_ian - 10)
А ещё до этого ПР-а грабы не изменялись, но ты зачем-то изменяешь. Your point being?

2020-06-14 13:37 UTC, LudwigVonChesterfield commented
По-твоему лучше когда игрок не имеет информации о своей кукле?

2020-06-14 17:42 UTC, LudwigVonChesterfield commented on code/modules/mob/living/living_defines.dm
> +	var/resist_cost = 10 //Cost of grabs resisting
Пока-что моё замечание не изменилось.

У нас нет способа получше определять кто кому сколько должен наносить стамина-урона при резистах и т.д.?

К примеру подвязать к соотношению размера - тех кто больше тебя сложнее зарезистить.

2020-06-14 17:42 UTC, LudwigVonChesterfield commented on code/modules/mob/living/living_defines.dm
> +	var/stamina_damage = 15 //When twisting, headlocking and so on
Почему бы это не подвязать к урону с руки?

2020-06-14 17:45 UTC, cool20141 commented on code/modules/mob/living/living_defines.dm
> +	var/resist_cost = 10 //Cost of grabs resisting
Ну, учитывая, что хватать могут только "люди" (Чтоб прям с захватами) и, вроде, алиены, то к размеру привязывать смысла особого нет (Так как у них всех одинаковое количество HP)

2020-06-14 17:46 UTC, LudwigVonChesterfield commented on code/modules/mob/living/living_defines.dm
> +	var/resist_cost = 10 //Cost of grabs resisting
Ты готов гарантировать что всё будет так всегда? Или ты будешь прибегать в будущие ПР-ы по стамине, и вместо меня заставлять человека сделать как надо?

2020-06-14 17:47 UTC, LudwigVonChesterfield commented on code/_onclick/hud/human.dm
> +	using = new /obj/screen/stamina_bar()
Может стоит сделать чтобы она была видна только если стамина не на 100? 🤔

2020-06-14 17:49 UTC, cool20141 commented on code/modules/mob/living/living_defines.dm
> +	var/stamina_damage = 15 //When twisting, headlocking and so on
У нас макс. здоровье – это по 100 хп, а урон с руки – 4-10. Как-то маловато будет 0.04 урона

2020-06-14 17:49 UTC, cool20141 commented on code/_onclick/hud/human.dm
> +	using = new /obj/screen/stamina_bar()
Как ты такой смайлик сделал?

2020-06-14 17:50 UTC, LudwigVonChesterfield commented on code/modules/mob/living/living_defines.dm
> +	var/stamina_damage = 15 //When twisting, headlocking and so on
Я не против если добавить какую-то "выравнивающую" магическую переменную. Что-то типо "buff_metric" которая определеят какой процент ХП является мышцами. 

damage * buff_metric / health - урон по стамине.

2020-06-14 17:51 UTC, cool20141 commented on code/modules/mob/living/living_defines.dm
> +	var/stamina_damage = 15 //When twisting, headlocking and so on
А может просто урон с руки сделать? Ну типа там и скорость повыше, чем в резистах на выполнение, так что в принципе сбалансировано будет

2020-06-14 17:54 UTC, LudwigVonChesterfield commented on code/_onclick/hud/human.dm
> +	using = new /obj/screen/stamina_bar()
\:thinking\:

2020-06-14 19:12 UTC, LudwigVonChesterfield commented
Это хороший ПР, но я не хочу чтобы ты испортил людям впечатление не имея понятия что ты набалансил. Ты бы мог устроить на локалке у себя тесты с 1-2-мя человеками, просто погррабать-подраться, прочувствовать как оно, и что можно сделать лучше?

2020-06-14 19:20 UTC, Motzord commented
Готов потестить на локалочке

2020-06-14 19:44 UTC, cool20141 commented
Ну, подумаю над этим

2020-06-15 05:27 UTC, cool20141 commented
В общем, кто захочет потестить–пишите в личку в дискорде (Cool20141#0318)

2020-06-15 13:11 UTC, cool20141 commented
Еще раз: Кто хочет потестить выносливость–пишите в ЛС в дискорде

2020-06-16 09:05 UTC, LudwigVonChesterfield commented on code/modules/mob/mob_grab.dm
> +				flick(hud.icon_state, hud)
... А это зачем нужно?

2020-06-16 09:06 UTC, LudwigVonChesterfield commented on code/modules/mob/mob_grab.dm
> +				assailant.SetNextMove(CLICK_CD_ACTION)
Мне не очень нравится неявный стан игрока. Может лучше сделать чтобы это расходывало стамину?

2020-06-16 09:39 UTC, cool20141 commented on code/modules/mob/mob_grab.dm
> +				flick(hud.icon_state, hud)
Чтоб обновлялась картинка

2020-06-16 09:40 UTC, cool20141 commented on code/modules/mob/mob_grab.dm
> +				assailant.SetNextMove(CLICK_CD_ACTION)
Можно, просто при тесте выяснилось, что чел может спокойно опрокинуть кого-то, а потом, так как у него кд нет, а у захваченного weaken, может быстро его скрутить в следующий захват

2020-06-16 17:57 UTC, LudwigVonChesterfield commented on code/__DEFINES/traits.dm
> +#define STAMINA_TRAIT	   "stamina"
%NAME%_TRAIT дефайны это источники трейта.

В данном случае - лучше назвать GRAB_TRAIT

2020-06-16 17:57 UTC, LudwigVonChesterfield commented on code/_onclick/hud/_defines.dm
> +#define ui_stamina_ian "EAST-1:28,CENTER-1:5"
Если он юзает такую же стамину, может ему удалить его иконки?

2020-06-16 17:58 UTC, LudwigVonChesterfield commented on code/modules/mob/living/carbon/human/human.dm
> +	var/list/damage = get_unarmed_attack()
```suggestion

	var/list/damage = get_unarmed_attack()
```

2020-06-16 17:58 UTC, LudwigVonChesterfield commented on code/modules/mob/living/carbon/human/human.dm
> +	var/list/damage = get_unarmed_attack()
Я бы предложил назвать attack_obj а не damage

2020-06-16 17:58 UTC, LudwigVonChesterfield commented on code/modules/mob/living/carbon/human/human.dm
> +	stamina_regen *= maxStamina/20
```suggestion
	stamina_regen *= maxStamina * 0.05
```

2020-06-16 17:58 UTC, LudwigVonChesterfield commented on code/modules/mob/living/carbon/human/life.dm
> +			handle_stamina_bar()
А почем уэто отдельные проки?

2020-06-16 17:59 UTC, LudwigVonChesterfield commented on code/modules/mob/living/living.dm
> +			if(G.state ==GRAB_PASSIVE)
```suggestion
			if(G.state == GRAB_PASSIVE)
```

2020-06-16 18:00 UTC, LudwigVonChesterfield commented on code/modules/mob/living/living.dm
> +			if(L.getStamina() >= L.resist_cost * size_ratio_resisting)
size_ratio_resisting может быть не того моба, из-за того ты проходишься циклом по всем грабам и выставляешь переменной, а не сравниваеьш с размером некого L

2020-06-16 18:00 UTC, LudwigVonChesterfield commented on code/modules/mob/mob_grab.dm
> +
```suggestion

```

2020-06-16 18:00 UTC, LudwigVonChesterfield commented on code/modules/mob/mob_grab.dm
> +				flick(hud.icon_state, hud)
А раньше она не обновлялась?

2020-06-16 18:00 UTC, LudwigVonChesterfield commented on code/modules/mob/mob_grab.dm
> +	if((grabs.len + dropped) == 1)
```suggestion
	if(grabs.len + dropped == 1)
```

2020-06-16 18:01 UTC, LudwigVonChesterfield commented on code/modules/mob/mob_grab.dm
> +	if((grabs.len + dropped) == 1)
А ничего что dropped - это тру или фолз?...

2020-06-16 18:01 UTC, LudwigVonChesterfield commented on code/modules/mob/mob_grab.dm
> +		delNoStaminaTrait()
А зачем это делать отдельной функцией, ещё и с таким названием?

2020-06-16 18:03 UTC, LudwigVonChesterfield commented on code/modules/unarmed_combat/living_procs_defines.dm
> +			if(getStamina() == 100)
Мне не нравиться что любой кто сбивает граб другому мгновенно теряет любое кол-во стамины. То есть если даже есть моб с 200 стаминой, то у него после такого будет 0.

Тем более, резист тоже не мгновенно сбивает всю стамину.

Пуш же как бы отталкивает моба от того, кто в захвате. Может сделать чтобы if(G.affecting == src) тогда расходуем всю стамину, а в остальных случаях - нет?

2020-06-16 18:03 UTC, LudwigVonChesterfield commented on code/modules/unarmed_combat/living_procs_defines.dm
> +			if(getStamina() == 100)
И да, maxStamina не обязательно 100...

2020-06-16 18:03 UTC, LudwigVonChesterfield commented on code/modules/unarmed_combat/living_procs_defines.dm
> +			if(getStamina() == 100)
И если у моба почему-то макс_стамина меньше нуля, то setStamina(0) сделает её больше нуля?...

2020-06-16 18:33 UTC, cool20141 commented on code/_onclick/hud/_defines.dm
> +#define ui_stamina_ian "EAST-1:28,CENTER-1:5"
То есть? У него какая-то своя иконка стамины была? Просто если нет, то конкретно вот эта вот строчка сделана, чтоб стамина была под отображением ХП

2020-06-16 18:34 UTC, cool20141 commented on code/modules/mob/mob_grab.dm
> +	if((grabs.len + dropped) == 1)
Ну так тру = 1, фолз = 0, все нормально же

2020-06-16 18:35 UTC, cool20141 commented on code/modules/mob/mob_grab.dm
> +		delNoStaminaTrait()
Да я думал ее пихать везде перед qdel'ами, но так оказалось легче, а отдельной осталось, чтоб легче было разбирать. Такое название, потому что...удаляет трейт NOSTAMINAREGEN

2020-06-16 18:36 UTC, LudwigVonChesterfield commented on code/modules/mob/mob_grab.dm
> +		delNoStaminaTrait()
Знаешь что ещё удаляет этот трейт? Функция удаления трейта.

Можешь назвать её "on_last_grab_destroy" и я бы понял

2020-06-16 18:44 UTC, LudwigVonChesterfield commented on code/modules/mob/living/carbon/human/stamina.dm
> +/mob/living/carbon/proc/handle_stamina_bar()
Я рекомендую сделать функцию update_stamina_bar, которую использует в Get()/Adjust() проках, чтобы не каждый тик обновлять иконку, а лишь когда надо.

но тогда нужно будет придумать решения на слвучай если игрок вышел-зашел в тело

2020-06-16 18:46 UTC, LudwigVonChesterfield commented on code/modules/mob/mob_grab.dm
> +	var/dropped = FALSE
Мне кажется что эта переменная была создана как костыль.

Попробуй объяснить зачем она нужна.

2020-06-16 18:47 UTC, cool20141 commented on code/modules/unarmed_combat/living_procs_defines.dm
> +			if(getStamina() == 100)
Да, я че-то об этом не подумал

2020-06-16 18:50 UTC, cool20141 commented on code/modules/mob/living/carbon/human/stamina.dm
> +/mob/living/carbon/proc/handle_stamina_bar()
Учитывая, что стамина восстанавливается, то он все равно в итоге появится же

2020-06-16 19:47 UTC, cool20141 commented on code/modules/mob/living/carbon/human/life.dm
> +			handle_stamina_bar()
Для исключительного удобства (В ПРе Лизарда было так)

2020-06-16 19:52 UTC, cool20141 commented on code/modules/mob/living/carbon/human/stamina.dm
> +/mob/living/carbon/proc/handle_stamina_bar()
Кстати, а смысл тогда вообще такого решения будет, если все равно стамина каждый раз восстанавливается в Life? И типа убирай-не убирай, все равно получишь то, что получишь–постоянное обновление худа

2020-06-16 19:53 UTC, LudwigVonChesterfield commented on code/modules/mob/living/carbon/human/stamina.dm
> +/mob/living/carbon/proc/handle_stamina_bar()
Худ обновляется когда стамина уже на 100.

2020-06-16 19:55 UTC, LudwigVonChesterfield commented on code/modules/mob/living/carbon/human/life.dm
> +			handle_stamina_bar()
Я думаю что это плохой подход

2020-06-16 19:56 UTC, cool20141 commented on code/modules/mob/living/carbon/human/stamina.dm
> +/mob/living/carbon/proc/handle_stamina_bar()
А на 100 худ невидимым становится

2020-06-16 19:57 UTC, cool20141 commented on code/modules/mob/living/carbon/human/life.dm
> +			handle_stamina_bar()
Почему же? Логично разделение на худ и саму стамину, так и разобраться проще, чем сваливая все в одну кучу

2020-06-16 20:02 UTC, LudwigVonChesterfield commented on code/modules/mob/living/carbon/human/life.dm
> +			handle_stamina_bar()
Тебе не нужно каждый лайфтик это обновлять.

Это будет выглядеть не респонсивно

(если ты потратил стамину в начале лайф тика - полоска изменится тоьлко в конце тика)

Так ещё и не очень практично - в этой функции ты не проверяешь нужно ли вообще обновлять, и тыры-пыры. А если будешь проверять - то ты будешь копипастить проверки из другой функции - что тоже глупо.

2020-06-16 20:07 UTC, cool20141 commented on code/modules/mob/living/carbon/human/life.dm
> +			handle_stamina_bar()
Ну так хорошо, я уберу из лайфтика handle_stamina_bar(), взамен запрятав в adjust и set, но обновление все равно будет происходить каждый лайфтик, потому что...каждый раз вызывается adjustStamina

2020-06-16 20:09 UTC, LudwigVonChesterfield commented on code/modules/mob/living/carbon/human/life.dm
> +			handle_stamina_bar()
Зато в те лайфтики которые не надо обновлять - не будет обновлять.

А ещё тогда любой моб у которого вызывают adjustStamine()-ы будет получать нужный хад, без надобности прописвыать каждому в лайф.

2020-06-16 20:10 UTC, LudwigVonChesterfield commented on code/modules/mob/living/carbon/human/stamina.dm
> +		hud_used.staminadisplay.invisibility = 101
То есть объект стаминадисплея создаётся, но делается невидимым

Гениально, но зачем?

2020-06-16 20:11 UTC, LudwigVonChesterfield commented on code/modules/mob/living/carbon/human/stamina.dm
> +	if(getStamina() <= 0)
Мне если честно не нравится что когда стамина в минусе игроку не говорится насколько она в минусе, это не интуитивно. Может стоит сделать чтобы она заполнялась красным в противоположную сторону?

2020-06-16 20:12 UTC, cool20141 commented on code/modules/mob/living/carbon/human/stamina.dm
> +		hud_used.staminadisplay.invisibility = 101
Так было в оригинале

2020-06-16 20:13 UTC, cool20141 commented on code/modules/mob/living/carbon/human/stamina.dm
> +	if(getStamina() <= 0)
Попробую наспрайтить (Накопипастить и поотражать)

2020-06-16 20:25 UTC, LudwigVonChesterfield commented on code/modules/mob/living/carbon/human/stamina.dm
> +/mob/living/carbon/proc/handle_stamina_bar()
и что, если он продолжает обновляться

2020-06-16 21:27 UTC, LudwigVonChesterfield commented on code/modules/mob/living/carbon/human/human.dm
> +	stamina_regen *= maxStamina/20
И кстати, а почему именно стабильно 5 процентов?

2020-06-16 21:28 UTC, LudwigVonChesterfield commented on code/modules/mob/living/living.dm
> +			if(L.getStamina() >= L.resist_cost * size_ratio_resisting)
Может стоит где-то выше сделать переменную tot_resist_cost = L.resist_cost * size_ratio_resisting ?

2020-06-17 05:10 UTC, cool20141 commented on code/modules/mob/living/carbon/human/human.dm
> +	stamina_regen *= maxStamina/20
Ну, путем тестов пришли к тому, что 5 стамины–это довольно сбалансированная скорость регенерации

2020-06-17 05:11 UTC, cool20141 commented on code/modules/mob/living/living.dm
> +			if(L.getStamina() >= L.resist_cost * size_ratio_resisting)
А зачем?

2020-06-17 06:16 UTC, cool20141 commented on code/modules/unarmed_combat/living_procs_defines.dm
> +			if(getStamina() == 100)
Не сделает же в 0, там CLAMP, а если maxStamina < 0, то будет maxStamina

2020-06-17 08:10 UTC, LudwigVonChesterfield commented on code/modules/mob/living/living.dm
> +			if(L.getStamina() >= L.resist_cost * size_ratio_resisting)
ну а зачем её расчитывать снова и снова...

2020-06-17 09:30 UTC, cool20141 commented on code/modules/mob/living/living.dm
> +			if(L.getStamina() >= L.resist_cost * size_ratio_resisting)
Не, я про название, просто непонятно, почему tot, а не etot, например

2020-06-17 09:32 UTC, LudwigVonChesterfield commented on code/modules/mob/living/living.dm
> +			if(L.getStamina() >= L.resist_cost * size_ratio_resisting)
total tot

2020-06-17 09:36 UTC, cool20141 commented on code/modules/mob/living/living.dm
> +			if(L.getStamina() >= L.resist_cost * size_ratio_resisting)
Ну, я по-другому немного назову, если что потом поправлю

2020-06-17 11:26 UTC, LudwigVonChesterfield commented on code/modules/mob/living/carbon/human/stamina.dm
> +/mob/living/proc/handle_stamina_bar()
Думаю было бы лучше update_stamina_bar

2020-06-18 15:47 UTC, LudwigVonChesterfield commented on code/modules/mob/living/carbon/human/human.dm
> +	stamina_regen *= maxStamina/20
но это не 5 стамины - это 5 процентов от максимума

2020-06-18 15:48 UTC, LudwigVonChesterfield commented on code/modules/mob/mob_grab.dm
> +				assailant.SetNextMove(CLICK_CD_ACTION)
(мне всё ещё не очень нравится этот стан)

2020-06-18 15:51 UTC, cool20141 commented on code/modules/mob/living/carbon/human/human.dm
> +	stamina_regen *= maxStamina/20
А сейчас максимум у всех 100. Если больше стамины, то быстрее должна быть регенерация, по логике

2020-06-18 15:52 UTC, cool20141 commented on code/modules/mob/mob_grab.dm
> +				assailant.SetNextMove(CLICK_CD_ACTION)
Но он обязателен, чтоб не дать сразу же сменить захват на 3, чтоб тот мог позащищаться

2020-06-21 15:16 UTC, LudwigVonChesterfield commented on code/modules/mob/living/carbon/human/human.dm
> +	var/list/attack_obj = get_unarmed_attack()
Возникают проблемы при инициализации куклы из префов.

```
[17:24:06] Runtime in human_attackhand.dm, line 3: Cannot read null.species

proc name: get unarmed attack (/mob/living/carbon/human/get_unarmed_attack)
usr: The unknown () (/mob/living/carbon/human/dummy)
src: the unknown (/mob/living/carbon/human/dummy)
src.loc: null
call stack:
the unknown (/mob/living/carbon/human/dummy): get unarmed attack()
the unknown (/mob/living/carbon/human/dummy): atom init(1, "Human")
Atoms (/datum/subsystem/atoms): InitAtom(the unknown (/mob/living/carbon/human/dummy), /list (/list))
the unknown (/mob/living/carbon/human/dummy): New(1, "Human")
/datum/preferences (/datum/preferences): update preview icon()
/datum/preferences (/datum/preferences): ShowChoices(Man With Guns (/mob/dead/new_player))
/datum/preferences (/datum/preferences): process link loadout(Man With Guns (/mob/dead/new_player), /list (/list))
/datum/preferences (/datum/preferences): process link(Man With Guns (/mob/dead/new_player), /list (/list))
Man With Guns (/client): Topic("_src_=prefs;preference=loadout...", /list (/list), null)
```

2020-06-21 16:20 UTC, cool20141 commented on code/modules/mob/living/carbon/human/human.dm
> +	var/list/attack_obj = get_unarmed_attack()
А как вызвать ошибку эту?

2020-06-21 17:08 UTC, LudwigVonChesterfield commented on code/modules/mob/living/carbon/human/human.dm
> +	var/list/attack_obj = get_unarmed_attack()
Вероятно в преференсах выбрать отсутствие руки.

2020-06-22 19:43 UTC, LudwigVonChesterfield commented on code/modules/mob/living/living.dm
> +		var/g_resist_cost
что такое g и r?

2020-06-22 19:44 UTC, cool20141 commented on code/modules/mob/living/living.dm
> +		var/g_resist_cost
G–grabbing
R–resisting

2020-06-22 19:44 UTC, LudwigVonChesterfield commented on code/modules/mob/living/living.dm
> +			if(L.getStamina() >= r_resist_cost)
r_resist_cost здесь сравнивается с... кем?

Если к примеру 2 и больше человек граббают одного. Допустим человек и халк - то вот тут будет и у человека и у халка резист кост халка.

2020-06-22 19:45 UTC, LudwigVonChesterfield commented on code/modules/mob/mob_grab.dm
> +				assailant.SetNextMove(CLICK_CD_ACTION)
обязателен в 2 секунды?

2020-06-22 19:46 UTC, cool20141 commented on code/modules/mob/mob_grab.dm
> +				assailant.SetNextMove(CLICK_CD_ACTION)
А во сколько?

2020-06-22 19:46 UTC, LudwigVonChesterfield commented on code/modules/mob/mob_grab.dm
> +						assailant.stamina_damage *= attack_obj["damage"]
Вот тут большая проблема...

Начать надо с того, что оно не используется, ниже используется H.stamina_damage, а не assailant

Закончить можно тем - что если у тебя каждый раз урон стамины увеличивается в урон раз.

2020-06-22 19:47 UTC, LudwigVonChesterfield commented on code/modules/unarmed_combat/living_procs_defines.dm
> +				if(G.affecting == attacker && diff >= 0 && G.state > GRAB_PASSIVE)
если у того кто выбивает граб стамины меньше чем у того кто держит граб - то мы не уменьшим стамину, и вообще никак не повлияем? Тут какая-то странная логика

2020-06-22 19:47 UTC, cool20141 commented on code/modules/unarmed_combat/living_procs_defines.dm
> +				if(G.affecting == attacker && diff >= 0 && G.state > GRAB_PASSIVE)
На уменьшение стамины–resist, на "последний рывок"–push

2020-06-22 19:49 UTC, LudwigVonChesterfield commented on code/modules/mob/living/living.dm
> +		var/g_resist_cost
grab resist cost - окей, допустим

resisting resist cost - huh?

2020-06-22 19:50 UTC, cool20141 commented on code/modules/mob/living/living.dm
> +		var/g_resist_cost
Ну я не инглиш мэн, не знаю всяких там сложных синтаксических конструкций, потому пишу так, как знаю

2020-06-23 10:41 UTC, LudwigVonChesterfield commented on code/modules/unarmed_combat/living_procs_defines.dm
> +				if(G.affecting == attacker && diff >= 0 && G.state > GRAB_PASSIVE)
Этот "последний рывок" сейчас без последствий можно произвести имея меньше стамины чем у твоего оппонента, тут явно что-то не так

2020-06-23 15:20 UTC, cool20141 commented on code/modules/mob/mob_grab.dm
> +						assailant.stamina_damage *= attack_obj["damage"]
Ну я и китаец, я эту хуйню, кстати, с вот этой функцией get_unarmed_attack() придумывал и искал несколько минут, когда ее в первый раз делал, а только теперь увидел, что она уже была где-то в коде и можно было ее скопипастить

2020-06-23 15:48 UTC, LudwigVonChesterfield commented on code/modules/mob/mob_grab.dm
> +						assailant.stamina_damage = attack_obj["damage"] * initial(assailant.stamina_damage)
А если у моба stamina_damage каким-то образом в /atom_init()-е меняется?

спойлеры, чтобы не мучать:

рекомендую сделать ```H.adjustStamina(-assailant.stamina_damage * attack_obj["damage"])```

2020-06-23 15:49 UTC, LudwigVonChesterfield commented on code/modules/unarmed_combat/living_procs_defines.dm
> +			if((get_active_hand() in attacker.grabbed_by) || (get_inactive_hand() in attacker.grabbed_by))
а зачем это?

2020-06-23 15:49 UTC, LudwigVonChesterfield commented on code/modules/unarmed_combat/living_procs_defines.dm
> +	if(!anchored && !is_bigger_than(attacker) && src != attacker && !(get_active_hand() in attacker.grabbed_by) && !(get_inactive_hand() in attacker.grabbed_by)) // maxHealth is the current best size es
А это?...

2020-06-23 15:50 UTC, cool20141 commented on code/modules/unarmed_combat/living_procs_defines.dm
> +			if((get_active_hand() in attacker.grabbed_by) || (get_inactive_hand() in attacker.grabbed_by))
Проверка на то, держит ли attacker'а человек, соответственно и ниже

2020-06-23 16:29 UTC, LudwigVonChesterfield commented on code/modules/unarmed_combat/living_procs_defines.dm
> -	attacker.do_attack_animation(src)
А звук дизарма все равно проигрывается

2020-06-23 16:29 UTC, LudwigVonChesterfield commented on code/modules/unarmed_combat/living_procs_defines.dm
> +	if(!anchored && !is_bigger_than(attacker) && src != attacker && !(get_active_hand() in attacker.grabbed_by) && !(get_inactive_hand() in attacker.grabbed_by)) // maxHealth is the current best size es
Может сделать проверку типо "can_push"? И туда всё это вписать?

2020-06-23 16:31 UTC, LudwigVonChesterfield commented on code/modules/unarmed_combat/living_procs_defines.dm
> +						return attack_unarmed(attacker)
А почему из дизарма вызывается снова тычок, который снова вызовет disarmReaction... ?

2020-06-23 16:32 UTC, LudwigVonChesterfield commented on code/modules/unarmed_combat/living_procs_defines.dm
> +						return attack_unarmed(attacker)
И почему мы возвращаемся здесь, и игнорируем все последующие граббы после первого жёлтого?

2020-06-23 16:32 UTC, LudwigVonChesterfield commented on code/modules/unarmed_combat/living_procs_defines.dm
> +				var/diff = G.affecting.getStamina() - G.assailant.getStamina()
Дифф можно считать под if(G.affecting == attacker), он в других местах не юзается

2020-06-23 16:34 UTC, LudwigVonChesterfield commented on code/modules/unarmed_combat/living_procs_defines.dm
> +					if(diff >= 0 && G.state > GRAB_PASSIVE)
Может стоит хоть какое-то сообщение о том что тебе не хватает стамины на то чтобы разорвать граб?

И почему используется разница стамин? Это же не интуитивно, игрок не знает сколько стамины у противника, почему бы не урезать к примеру 100% стамины? Или там 50%?

2020-06-23 17:11 UTC, cool20141 commented on code/modules/unarmed_combat/living_procs_defines.dm
> +					if(diff >= 0 && G.state > GRAB_PASSIVE)
Ну так игроку не знает и сколько HP у противника

2020-06-23 17:12 UTC, LudwigVonChesterfield commented on code/modules/unarmed_combat/living_procs_defines.dm
> +					if(diff >= 0 && G.state > GRAB_PASSIVE)
А это к чему?

Я говорю что ты не можешь знать сколько потратит стамины пуш. Это как-то странно.

2020-06-24 19:39 UTC, LudwigVonChesterfield commented on code/modules/mob/living/living.dm
> +		var/g_resist_cost
а что ето должно значить?

2020-06-24 19:41 UTC, LudwigVonChesterfield commented on code/modules/mob/mob_movement.dm
> +/mob/Moved(atom/OldLoc, Dir)
Я не уверен что это работает как задумано

1. Разве этого же кода нет в client/Move?
2. Почему бы не перенести код из client/Move в mob/Move, чтобы движение было синхронным, а не с задержкой?
3. > G.affecting.Move(OldLoc)
разве это не переместит G.affecting в OldLoc, вместо *loc*?

2020-06-25 05:36 UTC, cool20141 commented on code/modules/mob/living/living.dm
> +		var/g_resist_cost
Типа траты выносливости для захваченного и захватившего

2020-06-25 05:39 UTC, cool20141 commented on code/modules/mob/mob_movement.dm
> +/mob/Moved(atom/OldLoc, Dir)
1. В client/Move там какой-то свой особый код (Но я отчасти его и использовал, просто в урезанном и переделанном виде, потому что там были особые для client приколюхи)
2. Он у меня и был в mob/Move поначалу, но из-за этого при толкании нормально не работал (Точнее вообще не работал так, как это было задумано)
3. Ну так все правильно. OldLoc–место, где был захвативший до того как переместился, а потому захваченного при перемещении туда и тянем

2020-06-25 08:05 UTC, LudwigVonChesterfield commented on code/modules/mob/mob_movement.dm
> +/mob/Moved(atom/OldLoc, Dir)
> В client/Move там какой-то свой особый код (Но я отчасти его и использовал, просто в урезанном и переделанном виде, потому что там были особые для client приколюхи)

Какие приколюхи?

> Он у меня и был в mob/Move поначалу, но из-за этого при толкании нормально не работал (Точнее вообще не работал так, как это было задумано)

Конечно не работал, в client/Move куча костылей которые гарантируют что ты не будешь врезаться в моба которого тащишь за собой

> Ну так все правильно. OldLoc–место, где был захвативший до того как переместился, а потому захваченного при перемещении туда и тянем

А разве в третьем граббе захваченный не находится на одном тайле?

2020-06-25 08:06 UTC, LudwigVonChesterfield commented on code/modules/mob/living/living.dm
> +			size_ratio_grabbing = get_size_ratio(L, G.assailant)
1 / size_ratio_resisting

2020-06-25 08:08 UTC, LudwigVonChesterfield commented on code/modules/unarmed_combat/combat_combo.dm
> +	if(require_canmove && !CS.attacker.canmove)
Было бы хорошо это проверять только если !heavy_animation, чтобы не делать лишних проверок.

Я бы рекомендовал вынести это повыше, там где
```
if(heavy_animation)
  ...
else if(require_canmove && !CS.attacker.canmove)
```

2020-06-25 08:09 UTC, LudwigVonChesterfield commented on code/modules/unarmed_combat/combos/combos.dm
> +	require_canmove = TRUE
А почему дизарм нельзя делать пристегнутым?

2020-06-25 08:09 UTC, LudwigVonChesterfield commented on code/modules/unarmed_combat/combos/combos.dm
> +	require_canmove = TRUE
А почему пуш нельзя делать пристёгнутым?

2020-06-25 10:55 UTC, cool20141 commented on code/modules/mob/mob_movement.dm
> +/mob/Moved(atom/OldLoc, Dir)
1. В client есть mob, например
2. Ну вот, а в Moved костыли не нужны–он нормально перемещается (только да, задержка есть)
3. Не, они в разных тайлах

2020-06-25 11:14 UTC, LudwigVonChesterfield commented on code/modules/mob/mob_movement.dm
> +/mob/Moved(atom/OldLoc, Dir)
1. mob - это то что клиент контроллирует. если ты перенес в /mob/Move, mob --> src
2. эта задержка - и показывает что ты сделал костыль. для синхронного движения нужно всё поместить в /Move, и придумать как сделать чтобы ты не сталкивался с тем кого тащишь. Благо, это уже придумали за тебя, и всё необходимое есть в client/Move
3. понял, окей.

2020-06-25 18:59 UTC, cool20141 commented on code/modules/mob/mob_movement.dm
> +/mob/Moved(atom/OldLoc, Dir)
Я проверил, в 3 грабе в одном тайле стоят, да

2020-06-26 06:58 UTC, LudwigVonChesterfield commented on code/modules/lighting/lighting_atom.dm
> +	return TRUE
А где используется то что тут возвращается?

2020-06-26 06:59 UTC, LudwigVonChesterfield commented on code/modules/mob/mob_movement.dm
> +	if(locate(/obj/item/weapon/grab, src))
откуда это взялось и зачем... у тебя есть GetGrabs() который делает это же, но лучше

2020-06-26 07:00 UTC, LudwigVonChesterfield commented on code/modules/unarmed_combat/combos/combos.dm
> +		if(!(I.flags && I.flags & ABSTRACT))
```suggestion
		if(!(I.flags & ABSTRACT))
```

2020-06-26 07:00 UTC, cool20141 commented on code/modules/lighting/lighting_atom.dm
> +	return TRUE
Двинутый ли возвращается, у меня просто за каждый шаг захватившего захваченные ходили два

2020-06-26 07:00 UTC, LudwigVonChesterfield commented on code/modules/unarmed_combat/combos/combos.dm
> +		if(!(I.flags && I.flags & ABSTRACT))
Вообще я бы предложил
```
for()
  if(I.flags & ABSTRACT)
    continue
  victim.drop_from_...
```

2020-06-26 07:01 UTC, cool20141 commented on code/modules/mob/mob_movement.dm
> +	if(locate(/obj/item/weapon/grab, src))
В client/Move было так. Я подумал, что там есть нюансы какие-то, а потому ничего не делал с этим

2020-06-26 07:02 UTC, cool20141 commented on code/modules/unarmed_combat/combos/combos.dm
> +		if(!(I.flags && I.flags & ABSTRACT))
Я так и думал поначалу, но что-то заставило так не делать

2020-06-26 07:03 UTC, LudwigVonChesterfield commented on code/modules/mob/mob_movement.dm
> +	if(locate(/obj/item/weapon/grab, src))
г-споди как это страшно. если захочешь подумать об этом и сделать нормально - пожалуйста сделай, но я не буду санкционировать если ты поленишься штрыкать копипасту прошлого столетия

2020-06-26 07:12 UTC, cool20141 commented
Такой еще вопрос: стоит ли оставлять возможность захватывать лежа?

2020-06-26 07:16 UTC, LudwigVonChesterfield commented
Захватывать в смысле грабом, или капчуром? (В обоих случаях - нет, потому-что граб пропадает когда лежишь... (Или из-за того что он абстракт - теперь не пропадает?))

2020-06-26 07:18 UTC, cool20141 commented
Не пропадает, когда лежишь в стане и все такое, я думаю, когда в стане (И подобное (incapacitated))–убирать полностью, а когда просто лежишь (crawl, например), то просто дропать до GRAB_PASSIVE и запрещать улучшать

2020-06-26 10:40 UTC, LudwigVonChesterfield commented on code/modules/mob/mob_grab.dm
> +		return 0
```suggestion
		return PROCESS_KILL
```

2020-06-26 10:41 UTC, LudwigVonChesterfield commented on code/modules/mob/mob_grab.dm
> +		allow_upgrade = 0
```suggestion
		allow_upgrade = FALSE
```

2020-06-26 10:41 UTC, LudwigVonChesterfield commented on code/modules/mob/mob_grab.dm
> +	if(assailant.lying)
Было бы очень хорошо если бы это было не в process(), а когда ложишься - сбрасывает граббы и запрещает грейдить - когда встаешь - разрешает грейдить

Но если ты не знаешь как такое сделать, я пойму.

2020-06-26 10:42 UTC, cool20141 commented on code/modules/mob/mob_grab.dm
> +		allow_upgrade = 0
Там везде allow_upgrade = 0, я привел к общему виду (А могу переделать все вместо 1/0 в TRUE/FALSE, надо?)

2020-06-26 10:43 UTC, LudwigVonChesterfield commented on code/modules/mob/mob_movement.dm
> +	if(locate(/obj/item/weapon/grab, src))
А почему это не выпилено из client/Move()?

У тебя выходит что одна и та же логика несколько раз обрабатывается

2020-06-26 10:47 UTC, cool20141 commented on code/modules/mob/mob_movement.dm
> +	if(locate(/obj/item/weapon/grab, src))
Потому что там в client/Move() и задержка на ходьбу, и всякие запреты на врезание в того, кого держишь

2020-06-26 16:15 UTC, LudwigVonChesterfield commented on code/modules/mob/mob_grab.dm
> +		allow_upgrade = 0
возможно

2020-06-26 16:15 UTC, LudwigVonChesterfield commented on code/modules/mob/mob_movement.dm
> +	if(locate(/obj/item/weapon/grab, src))
> Потому что там в client/Move() и задержка на ходьбу, и всякие запреты на врезание в того, кого держишь

которые тут тоже есть.

Я не говорю выпилить client/Move, я прошу выпилить логику грабба из клайент мува, она в двух местах одновременно не нужна

2020-06-26 16:16 UTC, LudwigVonChesterfield commented on code/modules/mob/mob_movement.dm
> +							if((diag - 1) & diag)
невероятно дебильная конструкция, если захочешь - поменяй

2020-06-26 16:16 UTC, LudwigVonChesterfield commented on code/modules/mob/mob_movement.dm
> +						. = ..()
Возможно муву не стоит вызывать родителя тут?

2020-06-26 16:17 UTC, LudwigVonChesterfield commented on code/modules/unarmed_combat/living_procs_defines.dm
> -	attacker.do_attack_animation(src)
звук всё ещё проигрывается

2020-06-26 16:27 UTC, cool20141 commented on code/modules/unarmed_combat/living_procs_defines.dm
> -	attacker.do_attack_animation(src)
Ну так теперь он оправдан

2020-06-26 16:39 UTC, LudwigVonChesterfield commented on code/modules/unarmed_combat/living_procs_defines.dm
> -	attacker.do_attack_animation(src)
ну тогда почему анимация не проигрывается?

2020-06-26 16:43 UTC, cool20141 commented on code/modules/unarmed_combat/living_procs_defines.dm
> -	attacker.do_attack_animation(src)
Потому что анимация в данном случае–дерганье туда-сюда, что вкупе с захватом(И его adjust_position()) выглядит ужасно

2020-06-26 16:45 UTC, LudwigVonChesterfield commented on code/modules/unarmed_combat/living_procs_defines.dm
> -	attacker.do_attack_animation(src)
но она же происходит к примеру когда моб сидит на чем-то и атакует.

я думаю тут скорее проверки нужны в do_attack_animation, возможно проверка на canmove, чем проверки здесь

2020-06-26 17:39 UTC, cool20141 commented on code/modules/mob/mob_movement.dm
> +						. = ..()
А где тогда? Он же вызывает atom/movable/Move() (Насколько я понял), что и позволяет нормально двигаться

2020-06-27 09:25 UTC, LudwigVonChesterfield commented on code/modules/unarmed_combat/living_procs_defines.dm
> +				if(A != to_move && (loc != attacker.loc && attacker.grabbed_by.len > 0))
Ну а почему они не должны давать в два раза больше очков?

2020-06-27 09:25 UTC, LudwigVonChesterfield commented on code/modules/unarmed_combat/living_procs_defines.dm
> +		if(loc != to_move && loc != attacker.loc)
Ну а почему они не должны наносить боль, если ты пихаешь этого человека в стену?

2020-06-27 09:33 UTC, LudwigVonChesterfield commented on code/modules/unarmed_combat/living_procs_defines.dm
> +		if(loc != to_move && loc != attacker.loc)
и эта проверка может всё похерить в ситуациях не связанных с граббом, к примеру когда аттакер каким-то образом прозрачный-призрачный, ты пихнул об стену - чувак вошел в аттакера, а в итоге урон не получил, потому-что Кул вставил костыль :(

2020-06-27 09:33 UTC, LudwigVonChesterfield commented on code/modules/unarmed_combat/living_procs_defines.dm
> +				if(A != to_move && (loc != attacker.loc && attacker.grabbed_by.len > 0))
у тебя теперь комбо очки в два раза быстрее вообще никто не набирает если его не держат в граббе

2020-06-27 09:34 UTC, cool20141 commented on code/modules/unarmed_combat/living_procs_defines.dm
> +		if(loc != to_move && loc != attacker.loc)
Не пиши плохое, я уже чиню

2020-06-27 13:05 UTC, LudwigVonChesterfield commented on code/modules/mob/mob_movement.dm
> +/mob/proc/Random_Dir(var/dir)
Этому методу нужно название получше, random_side_dir к примеру

и не знаю зачем его подвязывать к /mob

2020-06-27 13:05 UTC, LudwigVonChesterfield commented on code/modules/mob/mob_movement.dm
> +/mob/proc/Revert_Dir(var/dir)
мне кажется у нас уже есть такой метод, а если нет

то лучше сделать ассоциативный список НАПРАВЛЕНИЕ = ПРОТИВОПОЛОЖНОЕ_НАПРАВЛЕНИЕ

ещё всегда есть turn(dir, 90)

2020-06-27 13:07 UTC, LudwigVonChesterfield commented on code/modules/unarmed_combat/living_procs_defines.dm
> +		if(attacker.grabbed_by.len == 1)
Один странный костыль заменён на совершенно новый странный костыль.

Вместо того чтобы попытаться понять почему грабающий никуда не идёт когда его пихает граббнутый - мы тыкаем тысячу и одну проверку туда, где они явно не нужны, и заставляем ходить даже если не ходится.

а ещё если у тебя два человека в граббе вся вот эта спагетти-лесенка летит к чертям

Пожалуйста, разберись почему когда кто-то толкает кого-то будучи в граббе - тот не сдвигается с места, а не лепи костыли :(

2020-06-27 13:08 UTC, cool20141 commented on code/modules/mob/mob_movement.dm
> +/mob/proc/Random_Dir(var/dir)
1. У меня была открыта вкладка mob/movement, а потому я и подумал, что сюда, в принципе, подходит
2. А куда еще? Может быть просто proc/Random_Dir тогда? (И Reverse_Dir туда же, естественно со смененными именами)

2020-06-27 13:09 UTC, LudwigVonChesterfield commented on code/modules/mob/mob_movement.dm
> +/mob/proc/Random_Dir(var/dir)
/proc/random_side_dir(dir)
  return pick(dir, turn(dir, 90), turn(dir, -90))

2020-06-27 13:10 UTC, LudwigVonChesterfield commented on code/modules/mob/mob_movement.dm
> +/mob/proc/Random_Dir(var/dir)
(если я правильно понял чего ты хочешь, но если честно - нет, нет не понял)
(зачем ты суммируешь направление и случайное направление в сторону, ты хочешь получить случайную диагональ?)

2020-06-27 13:17 UTC, cool20141 commented on code/modules/mob/mob_movement.dm
> +/mob/proc/Random_Dir(var/dir)
Ну что-то типа того, но я наверно выпилю это, потому что уже не использую. Я хотел получить случайную диагональ, но чтоб "назад" не двигался чел (Скопипастил у своего ПРа про мышку)

2020-06-27 13:20 UTC, cool20141 commented on code/modules/unarmed_combat/living_procs_defines.dm
> +		if(attacker.grabbed_by.len == 1)
Для 2х человек другой код, а грабающий идет спокойно, просто в 3 грабе они как бы в 1 турфе, а потому нормальное направление для движения не задать

2020-06-27 13:21 UTC, Akellazp commented
Режим генокрадов убит, тупо нельзя человека в 4й граб взять (даже кататоника, даже труп), из 2го граба в 3й какая-то толи задержка, толи еще какая-то хуйня длительностью секунд 10, жертва из 3го граба резистится за 5 раз максимум.
![image](https://user-images.githubusercontent.com/47355061/85921944-7e2a8400-b888-11ea-805a-0729793b4792.png)

2020-06-27 13:22 UTC, cool20141 commented
Надо болевыми дожать до 0 и меньше стамины

2020-06-27 13:22 UTC, Akellazp commented
>даже труп

2020-06-27 13:23 UTC, cool20141 commented
Ок, понял

2020-06-27 13:30 UTC, cool20141 commented
А, да, кстати, про задержку–это ты, наверное, про то, что нельзя сразу из лежачего состояния в 3 граб перейти

2020-06-27 15:50 UTC, LudwigVonChesterfield commented on code/__HELPERS/unsorted.dm
> +	return turn(dir, 180)
предыдущая реализация на самом деле была более перформантная

2020-06-27 15:51 UTC, LudwigVonChesterfield commented on code/modules/mob/living/carbon/human/stamina.dm
> +		setStamina(minStamina)
Прикольный эффект вот этого:

Клоны будут "просыпаться" с негативной стаминой, как и во многих сай-фай сеттингах такая себя болезнь клона.

Возможно круто было бы если бы какие-то напитки давали бы стамину? Кофе там, и что-то медикаментозное.

2020-06-27 15:51 UTC, LudwigVonChesterfield commented on code/modules/mob/living/carbon/human/stamina.dm
> +		setStamina(minStamina)
п.с.: Возможно реворк Гиперцина с ускоряющего на стаминорегенбаффающего?

2020-06-27 15:52 UTC, LudwigVonChesterfield commented on code/modules/mob/mob_grab.dm
> +		if(force_down && G.affecting.getStamina() > 0)
> G.affecting.getStamina() > 0

Для такой проверки нужно отдельное, конкретизирующее стамино-хараткер проблемы сообщение

2020-06-27 15:53 UTC, LudwigVonChesterfield commented on code/modules/unarmed_combat/living_procs_defines.dm
> +		if(attacker.grabbed_by.len == 1)
Это не объясняет того, зачем ты ставишь костыль.

Небольшая викторина:

Почему когда ты пихаешь того кто держит тебя в граббе он не двигается?

Если ты сможешь ответить на этот вопрос - ты найдешь корень проблемы, и пофиксишь её. Если ты её пофиксишь - этот костыль здесь не понадобится.

2020-06-27 16:08 UTC, cool20141 commented on code/modules/unarmed_combat/living_procs_defines.dm
> +		if(attacker.grabbed_by.len == 1)
Он двигается, конкретно здесь особая модель поведения для 3 граба, потому что там они в одном тайле, а потому
1. get_dir работает не так, как того хочется
2. step_away шагает в непредсказуемом направлении

2020-06-27 16:24 UTC, LudwigVonChesterfield commented on code/modules/unarmed_combat/living_procs_defines.dm
> +		if(attacker.grabbed_by.len == 1)
Возможно стоит тогда сделать функцию по типу

force_step_away - которая бы делала шаг в случайном направлении если куклы находятся в одной точке, и пихало бы -если бы не в  одной?

Это звучит лучше чем текущий костыль

2020-06-29 14:27 UTC, LudwigVonChesterfield commented on code/game/atoms_movable.dm
> +	if(!new_dir)
Думаю лучше было бы без этой доп. проверки, потому-что могут быть вполне нормальные причины не иметь get_dir, я предлагаю:

```
/proc/force_get_dir()
  if(Loc1.loc == Loc2.loc)
    var/step_dir = reverse ? reverse_direction(Loc1.dir) : Loc1.dir
    return get_dir(get_step(Loc1, step_dir), Loc2)
  return get_dir(Loc1, Loc2)
```

Кстати, рекомендую Loc1 и Loc2 переименовать в A и B

А ещё мне не понятно, почему форсед дир если два объекта в одной локации использует то, куда смотрит объект 1(а не к примеру рандомное направление), откуда надобность в такой привелегии?

У нас к примеру Loc1.dir может быть 0

2020-06-29 14:28 UTC, LudwigVonChesterfield commented on code/game/atoms_movable.dm
> +		new_dir = random_side_dir(new_dir)
Не понимаю почему "рандом" это "рандомное относительно того куда смотрит объект"

2020-06-29 15:47 UTC, cool20141 commented on code/game/atoms_movable.dm
> +		new_dir = random_side_dir(new_dir)
А как он должен назад ходить(врезаться в тебя)...

2020-06-29 16:07 UTC, LudwigVonChesterfield commented on code/game/atoms_movable.dm
> +		new_dir = random_side_dir(new_dir)
pick(cardinal - get_dir(Trg, Ref))

было бы корректней тогда. Ref.dir - куда смотрит Ref, get_dir(Trg, Ref) - направление от цели к рефу.

2020-06-29 18:41 UTC, cool20141 commented on code/game/atoms_movable.dm
> +	if(!new_dir)
> У нас к примеру Loc1.dir может быть 0
В каких таких случаях?

2020-06-30 10:50 UTC, cool20141 commented
@LudwigVonChesterfield я наконец-то выпилил захваты из client/Move()
Я над этой тупорылой проблемой пыхтел несколько дней, а потом понял, что она решается заменой одного символа...

2020-06-30 11:58 UTC, LudwigVonChesterfield commented on code/modules/mob/mob_movement.dm
> +		if(client)
Это возможно стоит оставить у клиента? Типо, ты конечно ходишь из-за грабба - но ты не по своему желанию же ходишь

2020-06-30 11:59 UTC, LudwigVonChesterfield commented on code/modules/mob/mob_movement.dm
> +							if((get_dist(src, M) > 0 || diag))
А зачем теперь нужен diag?

2020-07-01 21:01 UTC, LudwigVonChesterfield commented on code/game/atoms_movable.dm
> +	if(!new_dir)
(тут для получения направления почему-то используется то, куда игрок смотрит)

> И не рандомное направление, чтоб можно было сравнивать два разных get_xxxx и получать нужный ответ

я не понимаю почему направление для эдж кейса выбирается именно по тому куда я смотрю, если я в граббе смотрю влево - я пихну влево, если смотрю вправо - пихну вправо

(и кстати, ты там что-то фиксил при ходьбе в граббе, может все эти костыли уже и не очень нужны?)

2020-07-01 21:03 UTC, LudwigVonChesterfield commented on code/modules/mob/mob_movement.dm
> +						. = ..()
https://github.com/TauCetiStation/TauCetiClassic/pull/5575/files#diff-99ebcf7ba775c1dfd1e8fd98cdbebe11L317

К примеру на этой строке он тоже вызывается, в итоге если у тебя моб в граббе, родительский прок вызвыается дважды. Зачем?

2020-07-01 21:04 UTC, LudwigVonChesterfield commented on code/modules/unarmed_combat/living_procs_defines.dm
>  			if(G.affecting)
```
if(!G.affecting)
  continue
if(G.affecting != attacker && G.assailant == attacker)
  continue

G.adjust_position()
var/diff = G.affecting.getStamina()

вся остальная логика

2020-07-01 21:04 UTC, LudwigVonChesterfield commented on code/modules/unarmed_combat/living_procs_defines.dm
> +					return
Тут, и ниже ты вероятно хотел continue, а то всё ломается когда граббов два.

2020-07-02 04:13 UTC, cool20141 commented on code/game/atoms_movable.dm
> +	if(!new_dir)
> я не понимаю почему направление для эдж кейса выбирается именно по тому куда я смотрю, если я в граббе смотрю влево - я пихну влево, если смотрю вправо - пихну вправо

Фича, чтоб можно было за захваченного "поворачивать" и двигать атакующего, а не только куда-то назад его пихать

2020-07-02 07:30 UTC, LudwigVonChesterfield commented on code/game/atoms_movable.dm
> +	if(!new_dir)
так оно не только на захваченных распостраняется, если они просто в одном тайле(закравлили к примеру) то ты почему-то выбираешь куда пихаешь. я считаю что это как-то странно...

2020-07-02 07:39 UTC, LudwigVonChesterfield commented on code/modules/mob/mob_movement.dm
> +							if(get_dist(src, M) > 0)
Возможно оно входит в бесконечный цикл из-за вот этого? Ты шагнул, но ты в итоге все равно не на одном тайле, а значит get_dist() > 0, а значит шагаешь ещё раз

2020-07-02 08:06 UTC, cool20141 commented on code/modules/mob/mob_movement.dm
> +							if(get_dist(src, M) > 0)
Оно входил в бесконечный цикл не в данном куске кода, а в другом, где для нескольких человек

2020-07-02 17:03 UTC, LudwigVonChesterfield commented on code/modules/mob/mob_movement.dm
> +					for(var/obj/item/weapon/grab/G1 in grabs)
Это ты так проверяешь что два моба держат друг друга в обоюдном граббе?

2020-07-02 19:13 UTC, cool20141 commented on code/modules/mob/mob_movement.dm
> +					for(var/obj/item/weapon/grab/G1 in grabs)
Что-то типа того

2020-07-02 20:19 UTC, LudwigVonChesterfield commented on code/modules/mob/mob_movement.dm
> +					for(var/obj/item/weapon/grab/G1 in grabs)
Ты уверен что нет способа получша, и может стоит задуматься о том почему конкретно эта ситуация вызывает подобную проблему, и что с этим можно сделать кроме проходиться циклом с проверкой каждый раз когда моб ходит?

2020-07-02 20:22 UTC, cool20141 commented on code/modules/mob/mob_movement.dm
> +					for(var/obj/item/weapon/grab/G1 in grabs)
Данная ситуация происходит потому, что mob/Move() содержит в себе step, который вызывает снова Move и так по кругу, я думал это исправить, добавив какую-нибудь переменную move (moving занята), но не знаю, стоит ли

2020-07-02 20:30 UTC, LudwigVonChesterfield commented on code/modules/mob/mob_movement.dm
> +					for(var/obj/item/weapon/grab/G1 in grabs)
я знаю как минимум две такие которые уже есть в билде

2020-07-03 05:30 UTC, cool20141 commented on code/modules/mob/mob_movement.dm
> +					for(var/obj/item/weapon/grab/G1 in grabs)
Где?

2020-07-03 08:02 UTC, LudwigVonChesterfield commented on code/modules/mob/mob_movement.dm
> +					for(var/obj/item/weapon/grab/G1 in grabs)
moving кстати это у клиента, а не у моба

2020-07-03 08:04 UTC, cool20141 commented on code/modules/mob/mob_movement.dm
> +					for(var/obj/item/weapon/grab/G1 in grabs)
У atom/movable тоже вроде есть

2020-07-03 08:11 UTC, LudwigVonChesterfield commented on code/modules/mob/mob_movement.dm
> +					for(var/obj/item/weapon/grab/G1 in grabs)
и почему ты не можешь её использовать?

2020-07-03 08:26 UTC, cool20141 commented on code/modules/mob/mob_movement.dm
> +					for(var/obj/item/weapon/grab/G1 in grabs)
А, не, она там у шаттлов вроде каких-то была, ладно, попробую ее использовать

2020-07-03 16:43 UTC, LudwigVonChesterfield commented
Про танец с несколькими людьми хорошо, переменную вероятно в mob_defines, и назови её как-то более конкретно типо, "is_moving"

2020-07-05 19:05 UTC, LudwigVonChesterfield commented
Из ТМ-а убрал из-за рантаймов связанных с тем что люди сцеплялись по трое
```
[21:49:50] Runtime in mob_movement.dm:310 : Cannot modify null.other_mobs.
  proc name: Move (/mob/Move)
  usr: Arthur Brown (???) (/mob/living/carbon/human)
  usr.loc: The floor (136,142,2) (/turf/simulated/floor)
  src: Arthur Brown (/mob/living/carbon/human)
  src.loc: the floor (136,142,2) (/turf/simulated/floor)
  call stack:
  Arthur Brown (/mob/living/carbon/human): Move(the wall (136,143,2) (/turf/simulated/wall), 1, 0, 0)
```

2020-07-06 12:02 UTC, LudwigVonChesterfield commented on code/modules/mob/mob_movement.dm
> +				if(!G.assailant.is_moving)
А каким образом это что-либо исправляет то?

От этой перестановки никакого эффекта, потому-что что ты сделаешь

i = TRUE
i = TRUE

что сделаешь

i = FALSE
i = TRUE

а разницы не будет, пожалуйста попробуй собрать людей чтобы выцепить и понять как происходит баг, а не карго-культ кодить :(

2020-07-06 12:23 UTC, cool20141 commented on code/modules/mob/mob_movement.dm
> +				if(!G.assailant.is_moving)
Так все логично, в той ошибке, где если 3 друг друга хватали, они все были affecting, всем переключался is_moving, постоянно вызывался Move и они бесконечно делали step в направлении. Соответственно тут проверяется, чтоб не допустить такого

2020-07-06 12:30 UTC, LudwigVonChesterfield commented on code/modules/mob/mob_movement.dm
> +				if(!G.assailant.is_moving)
Скажи мне в чем разница между следующими двумя примерами:

```
var/i = TRUE

if(!i)
  i = TRUE
```

```
var/i = TRUE
i = TRUE
```

2020-07-06 12:32 UTC, cool20141 commented on code/modules/mob/mob_movement.dm
> +				if(!G.assailant.is_moving)
Так не так же там все, там не присваивается G.affecting может двигаться только в том случае, если у assailant is_moving FALSE (Чтоб не было, как я уже сказал, когда 3 хватают друг друга, то лаги лютые и бесконечный step)

2020-07-07 08:48 UTC, LudwigVonChesterfield commented on code/modules/mob/mob_movement.dm
> +		var/list/L = mob.ret_grab()
Ну то есть было хорошо, не знаешь как доделать - решил сделать плохо :(

Мы переносили из клиента в моб, чтобы если пихнули моба с двумя граббами - они шли за ним, а теперь ты сделал как было

2020-07-08 04:58 UTC, cool20141 commented on code/modules/mob/mob_movement.dm
> +		var/list/L = mob.ret_grab()
Если что, то при пихании с 2мя грабами всегда будет разрыв, потому что они ниже GRAB_PASSIVE
Так что по-факту это делает только лучше

2020-07-09 17:28 UTC, LudwigVonChesterfield commented on code/modules/mob/mob_movement.dm
> +		var/list/L = mob.ret_grab()
Это не делает ничего лучше, потому-что оставляет как было, когда у того зачем сделать иначе уже были аргументы

2020-07-09 17:29 UTC, LudwigVonChesterfield commented on code/modules/mob/mob_movement.dm
> +				if(!G.assailant.is_moving)
Тогда сделай чтобы присваивалось в нужном порядке, но то что у тебя здесь сейчас - явно не решает проблему(и ты можешь в этом убедиться сам)

2020-07-14 06:45 UTC, cool20141 commented
Сделано, вроде бы

2020-07-14 06:51 UTC, cool20141 commented
Если все будет круто, то, наверно, возьмусь за стаминовосстанавливающие предметы и прочее

2020-07-14 10:26 UTC, LudwigVonChesterfield commented on code/modules/mob/mob_movement.dm
> +		if(client)
(Я всё ещё думаю что это стоит оставить у клиента)

Или есть причины так не делать типо какой-то абуз ускоряющий сильно?

2020-07-14 12:50 UTC, cool20141 commented on code/modules/mob/mob_movement.dm
> +		if(client)
Я решал одну проблему за раз, а вот это конкретно куда клиенту впихнуть думаю теперь

2020-07-14 20:16 UTC, LudwigVonChesterfield commented
> Если все будет круто, то, наверно, возьмусь за стаминовосстанавливающие предметы и прочее

Желательно отдельным ПР-ом

2020-07-15 10:14 UTC, LudwigVonChesterfield commented
На данный момент нельзя бросать людей из граба (подозреваю что из-за того что грабы тут - ABSTRACT)

2020-07-16 08:09 UTC, TauKitty commented
This pull request has been mentioned on **Tau Ceti Station Forum**. There might be relevant details there:

https://forum.taucetistation.org/t/vopros-otvet/13334/1451

2020-07-16 13:18 UTC, Kyler2262 commented
Из-за этого ПРа генки не могли нормально пожирать своих жертв, так как не могут "апнуть" граб в стадию удушения.

2020-07-16 13:19 UTC, cool20141 commented
Все могут, читай предыдущие сообщения: Нужно сделать стамину захваченному в 0 и меньше, тогда только можно улучшить

2020-07-16 13:20 UTC, Kyler2262 commented
Не могут. Мою куклу несколько раз захерачили стан продом, и даже после этого не смогли нормально сожрать.

2020-07-16 13:21 UTC, cool20141 commented
Чел, если ты нихуя не разобрался, то не пости хуйню, удали и не позорься. Где ты видишь хоть слово про станпалку и прочее?

2020-07-16 14:10 UTC, Kyler2262 commented
Ало нахуй, а она по твоему не снижает стамину до нуля и ниже?

2020-07-16 15:36 UTC, cool20141 commented
Нет, не снижает

2020-07-16 15:36 UTC, cool20141 commented
Чел, ты просто долбоеб, это мой ПР, наверное я лучше знаю, что снижает стамину, а что нет? :rofl:

2020-07-16 21:04 UTC, LudwigVonChesterfield commented
@cool20141 Помягче выражайся пожалуйста.

2020-07-16 21:05 UTC, LudwigVonChesterfield commented on code/modules/mob/mob_grab.dm
> +		if(affecting.getStamina() > 0 && affecting.stat)
А почему у мертвых может стамина быть больше нуля, когда ты им ставишь -100?

2020-07-17 04:43 UTC, cool20141 commented on code/modules/mob/mob_grab.dm
> +		if(affecting.getStamina() > 0 && affecting.stat)
А почему нет? Они же мертвы, пусть будет и стамина отрицательная, и все такое. Конкретно вот эти изменения были на то, что выше жаловались, что застаненного не могли схватить в 3 граб

2020-07-19 11:27 UTC, LudwigVonChesterfield commented
![image](https://user-images.githubusercontent.com/17705613/87873648-effb7680-c9cb-11ea-99ba-9a7e18b3481c.png)

2020-07-19 11:34 UTC, LudwigVonChesterfield commented
![image](https://user-images.githubusercontent.com/17705613/87873785-f5a58c00-c9cc-11ea-8f60-dae7388a316a.png)

Тут что-то глубже, и интереснее.

2020-07-25 09:22 UTC, LudwigVonChesterfield commented on code/game/atoms_movable.dm
> +	var/obj/item/weapon/grab/G = locate() in target
Тебя самого не смущает твоё желание вставлять везде какие-то костыли?

А почему при граббе шеи надо выкидывать тело не туда, куда смотрит граббающитй, а в обратную сторону?

2020-07-25 09:22 UTC, LudwigVonChesterfield commented on code/modules/mob/living/carbon/human/human.dm
> +	stamina_regen *= maxStamina * 0.05
Возможно 0.05 стоит вынести в дефайн типо STAMINA_REGEN_RATE

2020-07-25 09:23 UTC, cool20141 commented on code/game/atoms_movable.dm
> +	var/obj/item/weapon/grab/G = locate() in target
Потому что иначе он ходил туда-сюда при толчке

2020-07-25 09:24 UTC, LudwigVonChesterfield commented on code/modules/mob/mob_movement.dm
> +		if(client)
туда же где оно и было

2020-07-27 21:10 UTC, LudwigVonChesterfield commented on code/modules/mob/mob_grab.dm
> +		if(affecting.getStamina() > 0 && affecting.stat)
Да, допустим.

А может стоит сделать чтобы любая вещь которая вводит в stat > 0 сбрасывала стамину до минимума?

2020-07-27 21:10 UTC, LudwigVonChesterfield commented on code/game/atoms_movable.dm
> +	var/obj/item/weapon/grab/G = locate() in target
Кто - он? И почему он так делал?

2020-07-27 21:18 UTC, Motzord commented
Итак по проблемам.

Пуш все еще выталкивает куклу, резист не нужен по сути.

Катаноники и застаненные все еще имеют полную стамину, так что генки не могут спокойно кушать.

2020-07-28 04:56 UTC, cool20141 commented on code/game/atoms_movable.dm
> +	var/obj/item/weapon/grab/G = locate() in target
Захватчик(Толкаешь его толчками, он ходит туда-сюда)

2020-07-28 05:01 UTC, cool20141 commented
Пуш теперь тратит всю стамину, и, если ее было меньше, чем у противника, не срабатывает
А еще я, вроде, делал, чтоб можно было их хватать без проблем(Мб не обновили еще или как-то так, я в этом не разбираюсь)

2020-07-28 09:22 UTC, LudwigVonChesterfield commented on code/modules/mob/living/living_defense.dm
> +	if(!dividend || !divisor)
А где у нас так случается что сюда передают нуллы, и почему?

Ленивое """решение""" которое борется с симптомом, а не проблемой

2020-07-28 09:23 UTC, LudwigVonChesterfield commented on code/modules/mob/living/living.dm
> +			if(!size_ratio_resisting)
Затычка которая была бы не нужна если бы решили проблему с тем, что кто-то из ребят выше - null по каким-либо причинам.

Или ты хочешь сказать что у нас есть случаи когда кто-то из ребят имеет нулевой размер?

Потому-что в таком случае внутри функции get_size_ratio надо на это тоже рассчитывать и возвращать INF если у divisor-а нулевой размер

2020-07-28 09:25 UTC, cool20141 commented on code/modules/mob/living/living_defense.dm
> +	if(!dividend || !divisor)
Так ты мне скинул сверху, что рантайм был. Я подробностей не знал, кто, когда, при каких условиях, потому пошел таким путем

2020-08-04 11:48 UTC, cool20141 commented
Так, что там еще осталось сделать-то?

2020-08-07 07:53 UTC, LudwigVonChesterfield commented on code/game/atoms_movable.dm
> +	var/obj/item/weapon/grab/G = locate() in target
Тебе стоит попробовать найти более глубокую причину почему это происходит

К примеру, может это из-за того что они на одном турфе?

Или из-за того что могут проходить друг через друга?

2020-08-07 08:07 UTC, LudwigVonChesterfield commented
Осталось сделать голосование и посмотреть как люди отреагировали на это изменение

(И тот один комментарий который я  оставил)

2020-08-07 12:19 UTC, cool20141 commented on code/game/atoms_movable.dm
> +	var/obj/item/weapon/grab/G = locate() in target
Ну, они в одном тайле в любом случае смогут проходить сквозь друг-друга, тут другое.
Проблема состояла в том, что при толчке меняется dir у того, кого толкнули, а это все и портит

2020-08-07 17:35 UTC, LudwigVonChesterfield commented on code/game/atoms_movable.dm
> +	var/obj/item/weapon/grab/G = locate() in target
То есть выходит что как я и говорил - базировать направление граба на направлении взгляда не очень хорошая идея?

Возможно стоит или изобрести какую-то переменную которая хранит предыдущее направление взгляда или ещё что-то креативное чтобы решить эту проблему

Но if(граб) это костыль - потому-что могут возникнуть другие случаи где случаются подобные которые ты вставишь отдельной ифкой, и ещё другие, и ещё. И в итоге ты лечишь симптомы, а не проблему(Которую ты даже смог опознать, удивительно что ты не борешься с ней, а с её симптомом)

2020-08-10 11:56 UTC, LudwigVonChesterfield commented on code/modules/mob/living/living.dm
> +			if(!size_ratio_resisting)
это всё ещё костыль который затыкает проблему того что или G.assailant ПОЧЕМУ-ТО null, или L - null

p.s: на строчку выше есть qdel(G), так что почему G.assailant может быть нуллом я не удивлён :)

2020-08-10 11:58 UTC, cool20141 commented on code/modules/mob/living/living.dm
> +			if(!size_ratio_resisting)
Я ее только сейчас заметил :man_facepalming:

2020-08-13 16:28 UTC, LudwigVonChesterfield commented on code/modules/unarmed_combat/living_procs_defines.dm
>  					if(diff >= 0 && G.state > GRAB_PASSIVE)
Тут какая-то галиматься с условиями

если разница > 0 и граб слабее агрессивного
  сразу ломаем граб

если разница > 0 и граб сильнее пассивного(те которые отсеялись выше)
  что-то мутим со стаминой

в остальных случаях(? ?? ?, наверное когда граб пассивный, хотя пассивный меньше агрессивного...)
  говорим что разорвать нельзя

Попробуй как-то лучше сделать что-ли пожалуйста...

2020-08-13 16:29 UTC, cool20141 commented on code/modules/unarmed_combat/living_procs_defines.dm
>  					if(diff >= 0 && G.state > GRAB_PASSIVE)
Да я пока "набросок" делал, потому что жаловались, что сразу могут вырываться из захвата толчками, переделаю потом

2020-08-19 06:33 UTC, LudwigVonChesterfield commented
> Да я пока "набросок" делал, потому что жаловались, что сразу могут вырываться из захвата толчками, переделаю потом

Ну... Подождём пока ПР не перестанет быть "наброском".

2020-08-19 07:13 UTC, cool20141 commented
:(

2020-08-26 04:38 UTC, volas commented
@cool20141 я так понимаю, тут немного осталось. Если доделаешь и пофиксишь конфликты - слапни мейнтейнеров

2020-08-26 04:40 UTC, cool20141 commented
Ок

2020-09-01 11:56 UTC, LudwigVonChesterfield commented on code/game/atoms_movable.dm
> +	var/obj/item/weapon/grab/G = locate() in target
!

2020-09-22 20:30 UTC, T6751 requested changes
В целом, у меня такое чувство, что это можно было сделать немного проще.
Просмотрел не всё, но пока что вот:

2020-09-22 20:30 UTC, T6751 commented on code/modules/mob/mob_defines.dm
> +	var/is_moving = FALSE
**is_grabbed** может лучше бы подошло?

2020-09-22 20:30 UTC, T6751 commented on code/modules/mob/mob_movement.dm
> +				spawn( 0 )
Вместо spawn() в новом коде нужно использовать INVOKE_ASYNC(объект, прок, аргумент1, аргумент2...)
В данном случае
```
INVOKE_ASYNC(src, ./proc/прок_нейм)

/mob/proc/прок_нейм()
if(M != src && is_moving)
	step(M, Dir)
	M.is_moving = FALSE
```

2020-09-22 20:30 UTC, T6751 commented on code/modules/mob/mob_movement.dm
> +					return
INVOKE_ASYNC, смотреть комментарий выше

2020-09-22 20:30 UTC, T6751 commented on code/modules/mob/mob_movement.dm
> +	if(istype(L, /list) && L.len > 2)
```suggestion
	if(islist(L) && L.len > 2)
```

2020-09-22 20:30 UTC, T6751 commented on code/modules/mob/mob_movement.dm
> +						. = ..()
Как и сказал Людук, родительский прок вызывается дважды, зачем?

2020-09-22 20:30 UTC, T6751 commented on code/modules/mob/living/carbon/human/stamina.dm
> +	if(isnull(maxStamina))
не первый раз вижу эту проверку. В каких случаях maxStamina может равнять null? Если таких случаев быть не может, то такая проверка лишняя и нужно убрать её, где она стоит

2020-09-23 11:44 UTC, cool20141 commented on code/modules/mob/living/carbon/carbon.dm
> -			return
Не помню, к чему конкретно это относится, но чтоб кидать можно было, можно и продублировать, но нахуя, а главное, зачем?

2020-09-23 11:44 UTC, cool20141 commented on code/modules/mob/living/living_defense.dm
> +		return !dividend ? 0 : INFINITY
Да это можно и удалить, уже ошибка решена и это все можно убрать

2020-09-23 11:45 UTC, cool20141 commented on code/modules/mob/mob_defines.dm
> +	var/is_moving = FALSE
Мб и лучше, мб и нет, это настолько принципиально?

2020-09-23 11:49 UTC, cool20141 commented on code/modules/mob/mob_movement.dm
> +				spawn( 0 )
Вряд ли, здесь спавн, во-первых, и раньше стоял, во-вторых, он для того, чтоб код ниже сработал после отработки вот этого. Я хз как здесь работает асинхронное программирование, но полагаю, что оно не соответствует моей задумке(Шучу, не моей, так, опять же, было здесь уже сделано раньше)

2020-09-23 11:54 UTC, cool20141 commented on code/modules/mob/living/carbon/human/stamina.dm
> +	if(isnull(maxStamina))
Я уже точно не помню, но причина явно была. Мб там что-то с очередью инициализации было, сейчас не скажу

2020-09-23 12:01 UTC, cool20141 commented on code/_onclick/hud/human.dm
> +	using.icon_state = "stam_bar_100"
Унификация, там, по-моему, везде так

2020-09-23 12:02 UTC, cool20141 commented
На некоторые комменты гитхаб прям под ними не позволяет ответить, но

> Возвращается значение, которое вернет родитель.
> Не думаю, что здесь нужен return TRUE, т.к. родитель итак возвращает единицу

Как уже писал людуку, возможно тут, возможно в РнД, данная строка вызывает обработку мува у родителя, а это нужно было для того, чтоб все работало. Спроси раньше–ответил бы более подробно, но сейчас я уже деталей точных, поспособствовавших принятию этого решения, не скажу

> Может есть способ сделать всё проще без изобретения новых проков и излишних усложний?
> И так ли обязательно толкать цель в определенном направлении?
> И если я правильно понял, почему просто не выбрать случайное направление и попытаться толкнуть туда?

Тоже уже объяснял людуку, потому что, во-первых, мне нужно ОБЯЗАТЕЛЬНО двигать в определенном направлении, а если выбирать случайное, то будет выглядеть убого

> Согласен с Людуком. Лучше вернуть как было.
> Интересно, что не работало, что пришлось это менять.
> И чем так сокращать прок, лучше уже сразу использовать turn(dir, 180)

Все работало, а если уж сокращать этот прок, то придется тогда менять его на тот самый turn(dir,180), если есть желание. У меня лично желание такой глупостью заниматься отсутствует

2020-09-23 12:54 UTC, T6751 commented
> Все работало, а если уж сокращать этот прок, то придется тогда менять его на тот самый turn(dir,180), если есть желание. У меня лично желание такой глупостью заниматься отсутствует

Так в том-то и дело, что раз всё работало, то к чему были эти изменения?

2020-09-23 12:55 UTC, cool20141 commented
Потому что turn(dir, 180) лучше, чем if..if...if

2020-09-23 12:59 UTC, T6751 commented on code/modules/mob/mob_defines.dm
> +	var/is_moving = FALSE
Что если вдруг кто-то захочет узнать, может ли моб двигаться и заметит эту переменную? Думаю, он будет обманут оназванием.

2020-09-23 13:00 UTC, T6751 commented
turn(dir, 180) и свич, который был - разные вещи по тому, как они работают. И если так хотел улучшить, мог сделать ассоциативный статический список list([дир] = [противоположный дир])

2020-09-23 13:00 UTC, cool20141 commented on code/modules/mob/mob_defines.dm
> +	var/is_moving = FALSE
Так is_grabbed сюда не подходит, потому что его в итоге никто не отпускают, да и не это она показывает, а is_moving как раз по делу, потому что значение переменной отвечает на вопрос: двигается моб или нет

2020-09-23 13:02 UTC, cool20141 commented
1. Как они "по-разному" работают, объясни уж
2. Нахуя, если turn(dir, 180) выполняет свою функцию как положено

2020-09-23 13:10 UTC, T6751 commented
>    Как они "по-разному" работают, объясни уж
    Нахуя, если turn(dir, 180) выполняет свою функцию как положено

turn - бьендовский прок. Может принимать два аргумента - направление и угол поворота. Возвращает направление согласно этому углу поворота. Однако о внутренней работе этого прока можно лишь догадываться
https://secure.byond.com/docs/ref/info.html?source#/proc/turn
reverse_direction - прок, принимающий лишь один аргумент - направление. Возвращает противоположное направление

reverse_direction также выполнял свою функцию как положено - так зачем менять?

И если это вопрос оптимизации, то лучше приложи данные профайлера, чтобы больше вопросов не было по этому поводу.


И пожалуйста, можно без ненормативной лексики на гитхабе, спасибо.

2020-09-23 13:16 UTC, cool20141 commented
Ну и, принципиальной разницы как для кодера, так и для игрока не увидел. Насчет вопросов оптимизации, людук тоже говорил, что вроде как вариант с switch'ем лучше, хотя я точно не знаю

2020-10-26 17:26 UTC, cool20141 commented on code/__DEFINES/traits.dm
> +#define TRAIT_NOSTAMINAREGEN	  "no_stamina_regen"
![image](https://user-images.githubusercontent.com/53309265/97206209-785a9600-17c9-11eb-9f4e-ca490ec19618.png)
Не вижу проблемы

2020-10-26 17:38 UTC, cool20141 commented
Что там еще нужно?

2020-11-24 16:33 UTC, LudwigVonChesterfield commented on code/modules/mob/living/carbon/human/stamina.dm
> +	if(isnull(maxStamina))
Он может равняться null-у если моб не использует стамину

2021-01-16 08:11 UTC, cool20141 commented
Так чего еще для счастья нужно, вроде все сделал, на все претензии ответил

2021-01-30 16:56 UTC, T6751 commented on code/modules/lighting/lighting_atom.dm
> +	return
return сюда не нужно добавлять. Это изменение ничего не меняет
```suggestion
```

2021-01-30 16:56 UTC, T6751 commented on code/modules/mob/living/living_defines.dm
> +	var/hud_updateflag = 0
Неиспользуемые переменные нужно удалить
```suggestion
```

2021-01-30 16:56 UTC, T6751 commented on code/modules/mob/mob_movement.dm
> +						. = ..()
Родительский прок всё ещё может вызываться дважды

2021-01-30 16:56 UTC, T6751 commented on code/modules/unarmed_combat/combos/harmful.dm
> +
```suggestion
```

2021-01-30 16:56 UTC, T6751 commented on code/modules/unarmed_combat/living_procs_defines.dm
>  			if(G.affecting)
Можешь переписать, пожалуста, как Людук уже это предлагал в своём ревью

```
if(!G.affecting)
  continue
if(G.affecting != attacker && G.assailant == attacker)
  continue

G.adjust_position()
var/diff = G.affecting.getStamina()

вся остальная логика
```

2021-01-30 16:56 UTC, T6751 commented on code/modules/unarmed_combat/living_procs_defines.dm
> +		//step_to(src, get_force_step_away(src, attacker))
```suggestion
```

2021-01-30 16:56 UTC, T6751 commented on code/modules/unarmed_combat/living_procs_defines.dm
> +				var/atom/A = get_force_push(attacker, src)
Верно ли понимаю, что этот прок был сделан из-за того, что get_force_push может возвращать 0, если локация не меняется? Если это так, может лучше сделать что-то типа
```
var/atom/A = get_step_away(src, attacker) || get_turf(attacker)
```

2021-01-30 16:59 UTC, T6751 commented on code/modules/mob/living/carbon/human/stamina.dm
> +		//hud_used.staminadisplay.invisibility = 101
```suggestion
```

2021-03-11 12:43 UTC, cool20141 commented on code/modules/mob/mob_movement.dm
> +						. = ..()
Это сделано специально-нарочно, чтоб работал танец(Оба друг друга хватают, двигаются). Иначе не работает

2021-03-11 13:00 UTC, cool20141 commented on code/modules/unarmed_combat/living_procs_defines.dm
> +				var/atom/A = get_force_push(attacker, src)
Ну, я сейчас не скажу, в чем конкретно проблема, но я ее заметил еще давно, когда работал над мышехалком. В общем, суть такова: если находиться на одном турфе с кем-то, кого ты толкаешь, то он двигается не туда, куда хотелось бы

2021-03-13 07:18 UTC, cool20141 commented
Ну так что

2021-03-26 13:42 UTC, cool20141 commented
Ну так что

2021-03-26 14:06 UTC, KIBORG04 commented on code/__DEFINES/traits.dm
> +#define TRAIT_NOSTAMINAREGEN	  "no_stamina_regen"
> Ну так что

А так ты все еще не заменил пробелы.

2021-03-27 10:54 UTC, cool20141 commented on code/__DEFINES/traits.dm
> +#define TRAIT_NOSTAMINAREGEN	  "no_stamina_regen"
Готово

2021-05-08 07:15 UTC, cool20141 commented
Ну так что

2021-05-08 07:50 UTC, Gort133 commented
А Я ГОВОРИЛ!!! СКОРО ВООБЩЕ ВСЕ СЛУЧАЙНОСТИ УБЕРУТ И ВСЕ БУДЕТ ОСНОВАНО НА ЦИФЕРКАХ. А мне то говорили что боевку поменяли и все, больше подобного не будет...

2021-05-12 12:43 UTC, cool20141 commented
Ну так что

2021-05-13 19:04 UTC, cool20141 commented
Ну так что

2021-05-15 09:12 UTC, cool20141 commented
:hourglass:

2021-05-18 14:20 UTC, cool20141 commented
![image](https://user-images.githubusercontent.com/53309265/118668282-64c25b80-b7fd-11eb-9b38-987cac6d22cf.png)

2021-05-18 19:55 UTC, LudwigVonChesterfield commented on code/modules/mob/living/carbon/human/human.dm
> +/mob/living/carbon/human/atom_init(mapload, new_species)
тут кажется какой-то мерж фейл

2021-05-18 19:59 UTC, LudwigVonChesterfield commented
я кажется не понимаю почему половина комментариев не отвечены автором, а столько шума по поводу того что мол никто сюда не смотрит. я ещё раз пробежался по всем проблемам, и будто бы за полтора года вообще ничего не пофиксилось

2021-05-20 17:32 UTC, cool20141 commented
> я кажется не понимаю почему половина комментариев не отвечены автором, а столько шума по поводу того что мол никто сюда не смотрит. я ещё раз пробежался по всем проблемам, и будто бы за полтора года вообще ничего не пофиксилось

Это на какие же я не ответил? Есть outdated, которые потому и outdated, что я менял так, как в них указано

2021-05-29 16:14 UTC, LudwigVonChesterfield commented on code/modules/mob/living/carbon/carbon.dm
> -			return
всё ещё непонятно к чему это изменение

2021-05-29 16:14 UTC, LudwigVonChesterfield commented on code/modules/mob/living/carbon/human/human.dm
> +#define STAMINA_REGEN_RATE 0.05
Пока только хумані используют стамину?

2021-05-29 16:15 UTC, LudwigVonChesterfield commented on code/modules/mob/mob_defines.dm
> +	var/is_moving = FALSE
is_grab_moving ?

2021-05-29 16:18 UTC, LudwigVonChesterfield commented on code/modules/mob/mob_movement.dm
> +		if(client)
Спустя два года эти изменения кажутся только более абсурдными. К чему они тут? Что они решают? Почему внесение стамины в захваты требует этого изменения? Может они решают что-то ещё?

2021-05-29 16:19 UTC, LudwigVonChesterfield commented on code/modules/unarmed_combat/living_procs_defines.dm
> -	attacker.do_attack_animation(src)
всё ещё придерживаюсь своего мнения

2021-06-01 13:03 UTC, cool20141 commented on code/modules/mob/living/carbon/human/human.dm
> +#define STAMINA_REGEN_RATE 0.05
А кто еще должен? Вроде как никто другой захваты-то делать и не умеет

2021-06-01 13:37 UTC, cool20141 commented on code/modules/mob/living/carbon/carbon.dm
> -			return
Чтоб можно было кидать, при этом нельзя было захват "снимать" с человека(Раньше можно было, ясное дело баг). Поэтому переместил ниже

2021-06-01 13:37 UTC, cool20141 commented on code/modules/mob/living/carbon/human/human.dm
> +#define STAMINA_REGEN_RATE 0.05
У него стамина = хп, там другое

2021-06-01 13:42 UTC, cool20141 commented on code/modules/mob/mob_movement.dm
> +		if(client)
Я проверил, лаги короче, если оставлять у клиента, ну не состыкуется что-то

2021-06-01 14:22 UTC, LudwigVonChesterfield commented on code/modules/mob/living/carbon/carbon.dm
> -			return
я прямо сейчас могу кидать захват с челвоека... а каким образом снимание связано с проком attack_hand?

2021-06-01 14:23 UTC, LudwigVonChesterfield commented on code/modules/mob/mob_movement.dm
> +		if(client)
... а почему конкретно лаги?

2021-06-01 15:58 UTC, cool20141 commented on code/modules/mob/living/carbon/carbon.dm
> -			return
Сейчас можешь, потому что это ломалось во время моих манипуляций с грабам. Не помню, рассказывал ли я тебе, но граб раньше можно было, во-первых, видеть в руке человека(Перетащив его куклу на свою), и снимать в итоге, я это решил, накидав ему всяких флагов, что в итоге сломало броски, я об этой проблеме узнал и вот так ее решил

2021-06-01 16:01 UTC, LudwigVonChesterfield commented on code/modules/mob/living/carbon/carbon.dm
> -			return
Сейчас могу - это в связи с этим ПР-ом, или прямо сейчас на сервере? Если второе - то твою проблему уже починили каким-то другим способом который не требовал перемещать код в случайные места, и возможно тут можно вернуть как было?

2021-06-01 16:02 UTC, cool20141 commented on code/modules/mob/mob_movement.dm
> +		if(client)
(Кстати, заметил это на многих серверах сски) захваты это жопа какая-то, вот и лаги. То ли эта часть кода, то ли какая еще вызывали зацикливание или еще что с персонажами, если приходилось разделять на "клиент-моб", из-за чего серв настолько лагал(По крайней мере моя локалка), что дрим демон переставал отвечать. Ну короче серьезная проблема, которой я нашел вот такое решение(Во сне мне явился нарси и рассказал, как надо). МОЖЕТ БЫТЬ, конечно, не конкретно в этой части кода затуп происходит, но явно он тут не последнюю роль играет

2021-06-01 16:04 UTC, LudwigVonChesterfield commented on code/modules/mob/mob_movement.dm
> +		if(client)
деление клиент моб нужно потому-что некоторые вещи происходят только если игрок хочет чтобы моб подвигался, а некоторые если моб двигается по любой причине. если ты не понимаешь самой причины проблемы, и каким образом это её решает - то это не очень стабильное решение.

2021-06-02 13:17 UTC, cool20141 commented on code/modules/mob/mob_movement.dm
> +		if(client)
Я проверил, собственно, вроде как эта строчка не решает лаги, она решает проблему другую. Если не иметь ее здесь, то на человека не будет накладываться замедление, если он кого-то держит

2021-06-02 13:21 UTC, LudwigVonChesterfield commented on code/modules/mob/mob_movement.dm
> +		if(client)
каким образом она влияет на замедление ???????

2021-06-02 13:31 UTC, cool20141 commented on code/modules/mob/mob_movement.dm
> +		if(client)
Ниже накидывается задержка на передвижение при захвате, а это для проверки, есть ли клиент

2021-06-02 13:43 UTC, LudwigVonChesterfield commented on code/modules/mob/mob_movement.dm
> +		if(client)
но ты всё это скопировал из клиента, она точно так же накидывалась там, только не надо было проверять на клиент ПОТОМУ-ЧТО КЛИЕНТ НЕ МОЖЕТ ВЫПОЛНЯТЬ ЧТО-ТО ЕСЛИ ЕГО НЕТ

2021-06-02 13:50 UTC, cool20141 commented on code/modules/mob/mob_movement.dm
> +		if(client)
Логично, но почему-то если переносить все, кроме вот этой вот строчки, то она не работает. Ну либо я просто что-то немного не так сделал, я посмотрю

2021-06-17 18:29 UTC, cool20141 commented on code/modules/mob/living/carbon/carbon.dm
> -			return
Перемещение кода произошло уже впоследствии фикса граба, который ранее можно было снять с человека(перетащить->нажать на grab, который в менюшке не отображался, но все равно имел возможность быть снятым)

2021-08-13 14:38 UTC, closed without merging