Слепые, немые и глухие получают индификатор своих болезней на униформу
TauCetiStation/TauCetiClassic pull request #5833
Opened 2020-07-15 18:59 UTC by FelixRuin

## Описание изменений
Слепые, немые и глухие персонажи на начало смены получают индификатор, который имеет обозначение одной из проблем взаимодействия с данным персонажем.
## Почему и что этот ПР улучшит
Упрощение взаимодействиями со слепыми, немыми и глухими персонажами, позволяя индефицировать каждую из проблем и устранять недопонимания в ситуациях, когда офицеры пытаются допросить немого или глухого персонажа.
## Авторство
Felix Ruin - Winter Schock
Текстура карточки переделана, но взята с Vore Station, но возможно это вообще Polaris
## Чеинжлог
:cl: Winter Schock
- tweak: персонажи с кварками слепоты, глухоты, немоты получают индификатор каждого из квирков как аксесуар на униформу

2020-07-15 18:59 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2020-07-16 08:22 UTC, LudwigVonChesterfield commented
Превью спрайтов пожалуйста.

2020-07-16 21:49 UTC, FelixRuin commented
![image](https://user-images.githubusercontent.com/31424899/87726180-32a03180-c7c7-11ea-98af-e25efd8ac002.png)
как это выглядит в игре (только если нацепить карточку обычную, то ничего не видно

2020-07-17 00:19 UTC, DedYarick commented
А ещё можно например писать о своей болезни в мед.записи, они же для этого и сделаны :/

2020-07-17 00:32 UTC, FelixRuin commented
когда офицеры кого-то держат лицом в пол, то им как-то далековато идти смотреть мед записи

2020-07-17 06:24 UTC, LudwigVonChesterfield commented
Думаю что эти же офицеры вряд-ли и карточку заметят, эх.

2020-08-07 23:35 UTC, Sakuya-Izayoi commented
#5089

2020-08-26 05:33 UTC, volas commented
Лучше правда поместить на id-карту. При спавне можно добавлять на карту соответствующие дизабилити-флаги, потом в экзамайне где-то тут
https://github.com/TauCetiStation/TauCetiClassic/blob/ec3585b1289b3e31b72ae54092dae1a3cbbf6f73/code/modules/mob/living/carbon/human/examine.dm#L207
проверять и каким-нибудь отдельным цветом выводить эту информацию.

2020-09-01 22:07 UTC, FelixRuin commented
@volas благодарю за идею, реализовал систему через запись на айди карту всех отрицательных квирков

2020-09-02 08:58 UTC, LudwigVonChesterfield commented on code/modules/mob/living/carbon/human/examine.dm
> +		if(istype(wear_id, /obj/item/device/pda))
У нас есть прок который берёт айди карту

2020-09-02 13:42 UTC, FelixRuin commented on code/modules/mob/living/carbon/human/examine.dm
> +		if(istype(wear_id, /obj/item/device/pda))
нашёл, добавил, done

2020-09-02 13:44 UTC, T6751 commented on code/modules/mob/living/carbon/human/examine.dm
> +			if(ID.disabilities)
Текущая проверка всегда true, т.к. переменная всегда будет содержать список (пустой, как минимум).
Нужно проверять, есть ли инвалидности в этом списке, то есть, что список не пустой
```suggestion
			if(ID.disabilities.len)
```

2020-09-02 19:29 UTC, T6751 commented
При экзамайне человека, айди картой будут показаны негативные квирки, а вот при экзамайне самой айди - не будут. Думаю, нужно добавить отображение квирков ещё сюда
![image](https://user-images.githubusercontent.com/66636084/92027582-6df0c280-ed6b-11ea-939b-eefb503fcfe2.png)

2020-09-02 19:37 UTC, T6751 commented
> Персонал станции получает индификатор всех своих плохих квирков на айди карту

Не уверен, что окружающим нужно знать ВСЕ твои негативные квирки. 
Не думаю, что окружающим нужно знать, что ты, например, что боишься темноты, любишь алкоголь и заедаешь стресс.
(К тому же заедание стресса будет считаться инвалидностью согласно этим словам, ууф: ```...current disabilities:```)

Думаю, нужно отображать действительно квирки-инвалидности, знание о которых действительно может упростить взаимодействие с такими персонажами

2020-09-02 21:20 UTC, FelixRuin commented
> Думаю, нужно отображать действительно квирки-инвалидности, знание о которых действительно может упростить взаимодействие с такими персонажами

добавить переменную для квирков, что этот квирк инвалидность?

2020-09-02 21:33 UTC, T6751 commented
> > Думаю, нужно отображать действительно квирки-инвалидности, знание о которых действительно может упростить взаимодействие с такими персонажами
> 
> добавить переменную для квирков, что этот квирк инвалидность?

Да, думаю так будет ок

2020-09-02 21:43 UTC, FelixRuin commented
@T6751 готово

2020-09-03 15:08 UTC, KIBORG04 commented on code/controllers/subsystem/ticker.dm
> +				SSjob.EquipRank(player, player.mind.assigned_role, 0)
Вообще, таких изменений не должно быть в ПРе

2020-09-03 15:09 UTC, KIBORG04 commented on code/datums/traits/negative.dm
> +	disability = TRUE
Мб еще дальтонизм внести?

2020-09-03 15:10 UTC, KIBORG04 commented on code/game/objects/items/weapons/cards_ids.dm
> +	var/list/disabilities = list()
Мб лучше создавать этот лист только когда нужно?

2020-09-03 15:54 UTC, FelixRuin commented on code/controllers/subsystem/ticker.dm
> +				SSjob.EquipRank(player, player.mind.assigned_role, 0)
ну уж простите, иначе (как мне кажется) сделать выдачу данных о квирках особо не получается

2020-09-03 15:55 UTC, FelixRuin commented on code/game/objects/items/weapons/cards_ids.dm
> +	var/list/disabilities = list()
в плане?

2020-09-03 15:56 UTC, FelixRuin commented on code/datums/traits/negative.dm
> +	disability = TRUE
Дальтонизм не особо инвалидность

2020-09-03 16:39 UTC, KIBORG04 commented on code/controllers/subsystem/ticker.dm
> +				SSjob.EquipRank(player, player.mind.assigned_role, 0)
А, сорри, я не подумал, что это имеет смысл

2020-09-03 16:40 UTC, KIBORG04 commented on code/game/objects/items/weapons/cards_ids.dm
> +	var/list/disabilities = list()
Сейчас при создании каждой карты создается этот лист, а значит занимается место в памяти при инициализации объекта. Я предлагаю создавать этот лист, только если нужно выдавать квирк

2020-09-03 16:50 UTC, T6751 commented on code/game/objects/items/weapons/cards_ids.dm
> +	var/list/disabilities = list()
> Я предлагаю создавать этот лист, только если нужно выдавать квирк

Мне кажется это уже микрооптимизация, которая здесь не то, чтобы нужна.
К тому же создавать пустой список - это нормальная практика. Особенно, если смотреть на код во многих местах

2020-09-03 16:52 UTC, KIBORG04 commented on code/game/objects/items/weapons/cards_ids.dm
> +	var/list/disabilities = list()
Да, микро оптимизация, ладно, как хотите

2020-09-04 10:38 UTC, volas commented on code/modules/mob/living/carbon/human/examine.dm
> +				msg += "\a [wear_id] shows [t_He] [t_has] current disabilities: <span class='warning'><B>"
> ``<span class='warning'><B>``

``<span class='warning bold'>``

2020-09-04 10:38 UTC, volas commented on code/modules/mob/living/carbon/human/examine.dm
> +					msg += "[ID.disabilities[I]], "
тут не будет выхода за пределы массива при len=1?

2020-09-04 10:38 UTC, volas commented on code/modules/mob/living/carbon/human/examine.dm
> +				msg += "[ID.disabilities[ID.disabilities.len]].</B></span>\n"
Как предложение, 
```
	+="[ENTITY_TAB]Has disability indicators on the card:\n[ENTITY_TAB]"
for(var/I in disabilities)
	+="[I], "
```
выделить еще отступами принадлежность информации к карте

2020-09-04 11:22 UTC, FelixRuin commented on code/modules/mob/living/carbon/human/examine.dm
> +					msg += "[ID.disabilities[I]], "
![image](https://user-images.githubusercontent.com/31424899/92234065-0dbc6680-eeba-11ea-9489-ab980f10555d.png)

всё хорошо с этим

2020-09-04 11:59 UTC, FelixRuin commented on code/modules/mob/living/carbon/human/examine.dm
> +				msg += "[ID.disabilities[ID.disabilities.len]].</B></span>\n"
Done

2020-09-04 11:59 UTC, FelixRuin commented on code/modules/mob/living/carbon/human/examine.dm
> +				msg += "\a [wear_id] shows [t_He] [t_has] current disabilities: <span class='warning'><B>"
Done

2020-09-04 13:14 UTC, T6751 commented on code/modules/mob/living/carbon/human/examine.dm
> +					msg += "[ID.disabilities[I]], "
```to``` работает как ```<=```, так что выхода за пределы не будет

2020-09-04 13:44 UTC, T6751 commented on code/modules/mob/living/carbon/human/examine.dm
> +				msg += "\a [ENTITY_TAB]Has disability indicators on the card: <span class='warning bold'><B>"
Странно ли то, что при экзамайне человека, на котором надета айди, инвалидности видны, но при экзамайне самой айди - не видны? Read ID Card - это другая вещь, как мне кажется, которую можно рассматривать как информацию при детальном изучении (чтении) айди карты. Стоит добавить такой же вывод в экзамайн самой айди?

2020-09-26 13:20 UTC, FelixRuin commented on code/modules/mob/living/carbon/human/examine.dm
> +				msg += "\a [ENTITY_TAB]Has disability indicators on the card: <span class='warning bold'><B>"
всё, обновил

2020-09-26 13:52 UTC, T6751 requested changes

2020-09-26 13:52 UTC, T6751 commented on code/modules/mob/dead/new_player/new_player.dm
> +	SSquirks.AssignQuirks(character, character.client, TRUE)
борг заспавнился вместе с повязкой на глаза, поэтому проверку на "силиконов" пока не стоит убирать. 
```suggestion
if(!issilicon(character))
	SSquirks.AssignQuirks(character, character.client, TRUE)
```

2020-09-26 14:05 UTC, FelixRuin commented on code/modules/mob/dead/new_player/new_player.dm
> +	SSquirks.AssignQuirks(character, character.client, TRUE)
принято

2020-09-26 14:30 UTC, T6751 commented on code/modules/mob/dead/new_player/new_player.dm
> +	SSquirks.AssignQuirks(character, character.client, TRUE)
```suggestion
	if(!issilicon(character))
		SSquirks.AssignQuirks(character, character.client, TRUE)
```

2020-09-26 14:42 UTC, T6751 approved these changes

2020-10-01 09:20 UTC, merged