Радиальное меню для силиконов
TauCetiStation/TauCetiClassic pull request #5894
Opened 2020-07-30 22:33 UTC by KIBORG04

## Описание изменений
ИИ. Не стал делать голограмму для члена экипажа, так как считаю рентабельно. Хотя, если попросите, то сделаь.
![ai](https://user-images.githubusercontent.com/26389417/88980647-62365a00-d2ee-11ea-9e38-456309c53177.gif)

Борготня
![r](https://user-images.githubusercontent.com/26389417/88980748-90b43500-d2ee-11ea-945f-81391b40558b.gif)
![r1](https://user-images.githubusercontent.com/26389417/88980754-93168f00-d2ee-11ea-9b0e-0a4ac15480a8.gif)

## Почему и что этот ПР улучшит
Игрок знает, что выбирает

## Авторство
Я

## Чеинжлог
:cl:
 - balance: Киборгам больше не даются попытки на выбор себе скина.
 - tweak: Радиальное меню для выбора скина ядра и голограммы ИИ.
 - tweak: Радиальное меню для выбора модуля и скина киборга.

2020-07-30 22:33 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2020-07-30 22:39 UTC, KIBORG04 commented on code/modules/mob/living/silicon/ai/ai.dm
>  				custom_sprite = 1 //They're in the list? Custom sprite time
Я готов в этом ПРе выпилить этот механ кастомного спрайта, если он не нужен. (тоже самое и с борготней)

2020-07-31 14:57 UTC, LudwigVonChesterfield commented
>  так как считаю рентабельно(ну или поленился, хз)

думаю поленился, сделать отдельную вкладку "голограмма члена экипажа" со всеми-всеми

> Я  готов в этом ПРе выпилить этот механ кастомного спрайта, если он не нужен. (тоже самое и с борготней)

думаю стоит

2020-08-02 14:09 UTC, LudwigVonChesterfield commented on code/modules/mob/living/silicon/ai/ai.dm
> +	if(!chooses_ai_cores)
Было бы хорошо если бы для эотго был отдельный прок я думаю

2020-08-02 14:10 UTC, LudwigVonChesterfield commented on code/modules/mob/living/silicon/ai/ai.dm
> +		var/state = show_radial_menu(usr, eyeobj, chooses_ai_cores, radius = 50, tooltips = TRUE)
Мне кажется странны м что выбрать картинку можно один раз

2020-08-02 14:10 UTC, LudwigVonChesterfield commented on code/modules/mob/living/silicon/ai/ai.dm
> +			for(var/name_holo in icon_list)
Возможно для этого было бы приятон отдельный прок сделать

2020-08-07 08:01 UTC, LudwigVonChesterfield commented on code/modules/mob/living/silicon/ai/ai.dm
> +	var/asnwer = alert("Would you like to select a hologram based on a crew member or switch to unique avatar?",,"Crew Member", "Unique")
Может стоит вот это тоже выпилить и сделать чтобы "член экипажа" был отдельной вкладкой в радиалке?

2020-08-07 08:35 UTC, KIBORG04 commented on code/modules/mob/living/silicon/ai/ai.dm
> +	var/asnwer = alert("Would you like to select a hologram based on a crew member or switch to unique avatar?",,"Crew Member", "Unique")
Блииин.. Почему я не придумал, как это сделать до твоего коммента..

2020-08-19 06:30 UTC, LudwigVonChesterfield commented on code/modules/mob/living/silicon/ai/ai.dm
> +				chooses_ai_holo = list()
Вот это можно сделать статическим списком вероятно

2020-08-19 06:30 UTC, LudwigVonChesterfield commented on code/modules/mob/living/silicon/ai/ai.dm
> +				chooses_ai_holo = list()
(и соответственно отдельные функции-наполнители, если захочешь)

2020-08-19 06:31 UTC, LudwigVonChesterfield commented on code/modules/mob/living/silicon/ai/ai.dm
> +	if(!chooses_holo_category)
Я думал сделать не копию того что было с алёртом, а иметь среди скинов ИИ вкладку "скин экипажа", мне это почему-то кажется лучше когда этих менюшек меньше.

2020-08-19 06:40 UTC, KIBORG04 commented on code/modules/mob/living/silicon/ai/ai.dm
> +	if(!chooses_holo_category)
Зачем помещать новую категорию в уже показанный список с выбором скина, это не очень очевидно

2020-08-25 18:42 UTC, T6751 requested changes
При выборе ядра ИИ и голограммы радиальное меню полупрозрачное и сливается с фоном из-за чего неудобно видеть/почти не видно из чего выбирать (и приходится искать достаточно темную поверхность, чтобы увидеть нормально радиальное меню)
Думаю, что нужно сделать, чтобы радиалка у ИИ не была полупрозрачной, как в случае с радиалкой боргов, в которой четко видно из чего выбираешь
p.s. потому что сейчас радиалка у ИИ будет даже неудобнее, чем текстовое меню

![image](https://user-images.githubusercontent.com/66636084/91213930-04453880-e71b-11ea-902c-efc3c6299650.png)

2020-08-25 19:04 UTC, KIBORG04 commented
> При выборе ядра ИИ и голограммы радиальное меню полупрозрачное и сливается с фоном из-за чего неудобно видеть/почти не видно из чего выбирать (и приходится искать достаточно темную поверхность, чтобы увидеть нормально радиальное меню)
> Думаю, что нужно сделать, чтобы радиалка у ИИ не была полупрозрачной, как в случае с радиалкой боргов, в которой четко видно из чего выбираешь
> p.s. потому что сейчас радиалка у ИИ будет даже неудобнее, чем текстовое меню
> 
> ![image](https://user-images.githubusercontent.com/66636084/91213930-04453880-e71b-11ea-902c-efc3c6299650.png)

Я знаю о этой проблеме, но радиалка имеет туже альфу, что и сам моб. Как это изменить в радиалке не знает человечество

2020-08-25 19:29 UTC, T6751 commented on code/modules/mob/living/silicon/ai/freelook/eye.dm
> +	alpha = 255
А что мешает прописать альфу в самих тултипах?

2020-08-25 19:29 UTC, T6751 commented
и ещё, когда отменяешь выбор в радиалке, то у ИИ исчезает вовсе аватарка, исправь это

![image](https://user-images.githubusercontent.com/66636084/91218732-2d1cfc00-e722-11ea-8533-4313189f5b32.png)
![20200825 222745](https://user-images.githubusercontent.com/66636084/91218777-3e660880-e722-11ea-8719-3b4e8ca82e00.png)

2020-08-25 19:56 UTC, KIBORG04 commented on code/modules/mob/living/silicon/ai/freelook/eye.dm
> +	alpha = 255
Я немного не так выразился. Бъонд сам подстраивает альфу картинок в радиалке под альфу объекта, к которому она примагничена. Я не знаю, как это нормально объяснить, но главные объект имеет какую-то альфу, то радиалка будет иметь в любом случае альфу 255, но при этом де-факто она останется с альфой 127
![image](https://user-images.githubusercontent.com/26389417/91221282-1ed0df00-e726-11ea-8441-d6dd4ab8cd20.png)

2020-08-25 20:16 UTC, T6751 commented on code/modules/mob/living/silicon/ai/freelook/eye.dm
> +	alpha = 255
> Overlays and images will also be affected by alpha, unless they use the RESET_ALPHA value in appearance_flags. 

> RESET_ALPHA: If this is an overlay/image/etc., ignore the parent's alpha value 

Думаю нужно добавить использование флага **RESET_ALPHA** в радиалку

2020-08-25 20:31 UTC, KIBORG04 commented on code/modules/mob/living/silicon/ai/freelook/eye.dm
> +	alpha = 255
пасиб

2020-08-25 20:32 UTC, KIBORG04 commented
![image](https://user-images.githubusercontent.com/26389417/91224714-2fd01f00-e72b-11ea-9e5f-dad76c954ce4.png)
![image](https://user-images.githubusercontent.com/26389417/91224762-44acb280-e72b-11ea-8b58-4d374e4b04c9.png)

2020-08-25 21:07 UTC, T6751 commented on code/modules/mob/living/silicon/robot/robot.dm
> +	modtype = show_radial_menu(usr, usr, choose_module, radius = 38, tooltips = TRUE)
И в остальных случаях использования show_radial_menu() тоже нужно добавить проверки на null, если это не учтено
```suggestion
	modtype = show_radial_menu(usr, usr, choose_module, radius = 38, tooltips = TRUE)
	if(!modtype)
		return	
```

2020-08-25 21:10 UTC, KIBORG04 commented on code/modules/mob/living/silicon/robot/robot.dm
> +	modtype = show_radial_menu(usr, usr, choose_module, radius = 38, tooltips = TRUE)
Я еще раз чекну, но в этом случае это не нужно, потому что ниже есть свитч, который и не найдет нулл в значениях

2020-08-25 21:17 UTC, T6751 commented on code/modules/mob/living/silicon/robot/robot.dm
> +	modtype = show_radial_menu(usr, usr, choose_module, radius = 38, tooltips = TRUE)
На самом деле нужно: свич не найдет, но дальше-то код продолжится... и в итоге будут рантаймы
Да и в целом зачем продолжать выполнение кода, если выбран null (если это конечно не учитывается в самом коде, а здесь он изначально не учитывался)?

![image](https://user-images.githubusercontent.com/66636084/91228607-2ea1f080-e731-11ea-9e5d-8aed681097dc.png)

2020-08-25 22:04 UTC, T6751 commented
Возможно стоит сделать, чтобы после выбора модуля скин борга менялся на "дефолтный" скин выбранного модуля и дальше ты выбираешь изменить ли скин на другой.
Думаю будет не очень видеть, например, секюрити-боргов, да и в целом боргов с уже выбранными модулями, но выглядящих как дефолтные.

![oof](https://user-images.githubusercontent.com/66636084/91232289-79266b80-e737-11ea-8ac8-5118b6b701c2.gif)

2020-08-25 22:11 UTC, T6751 approved these changes

2020-08-25 22:13 UTC, KIBORG04 commented
Щас пофикшу.

Хочу выразить благодарность, что уделил время столь интересному, но забытому ПРу. Но в тоже время и извинится, что отобрал это самое время

2020-08-25 22:36 UTC, T6751 commented on code/modules/mob/living/silicon/robot/robot.dm
> +	icon_state = module_sprites[pick(sprite_names)]
думаю лучше будет icon_state = module_sprites[pick(module_sprites)]

2020-08-26 04:30 UTC, T6751 commented on code/modules/mob/living/silicon/robot/robot.dm
>  	radio.config(module.channels)
это должно быть до радиалки с выбором скина, чтобы в случае, если игрок отменит выбор, не было пропущено

или в данном случае сделать вот так
```
var/new_icon_state = show_radial_menu(usr, usr, choose_icon, radius = 50, tooltips = TRUE)
	if(new_icon_state)
		icon_state = module_sprites[new_icon_state]
```

2020-09-02 17:40 UTC, merged