Возможность посмотреть возраст игрока пока его нет на сервере
TauCetiStation/TauCetiClassic pull request #5969
Opened 2020-08-09 01:50 UTC by FelixRuin

## Описание изменений
Добавлена возможность админам посмотреть игровой и общее время игры на сервере у игрока при отсуствии игрока на сервер... или нет, пожалуйста, научите в бд, ну или проверьте там... (〃￣ω￣〃)
## Почему и что этот ПР улучшит
Админам не придётся гадать, сколько-же играет игрок на сервере
## Авторство
Felix Ruin - Winter Schock
## Чеинжлог
:cl: Winter Schock
- tweak: админы могут узнать время игры у отсутствующего на сервере игрока

2020-08-09 01:50 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2020-08-11 03:17 UTC, volas commented on code/modules/admin/admin.dm
> +			p_ingame_age = age_and_ingame_age[2]
нужно проверять, что игрок вообще нашелся и функция что-то вернула, иначе будет ошибка по индексу

2020-08-11 03:54 UTC, FelixRuin commented on code/modules/admin/admin.dm
> +			p_ingame_age = age_and_ingame_age[2]
done, надеюсь я всё верно понял

2020-09-04 10:58 UTC, volas requested changes
И ты таки проверял работу?

2020-09-04 10:58 UTC, volas commented on code/modules/admin/admin.dm
> +	var/DBQuery/query = dbcon.NewQuery("SELECT datediff(Now(),firstseen) as age, ingameage FROM erro_player WHERE ckey = '[sanitize_sql(player_ckey)]'")
```suggestion
	var/DBQuery/query = dbcon.NewQuery("SELECT datediff(Now(),firstseen) as age, ingameage FROM erro_player WHERE ckey = '[sanitize_sql(ckey(player_ckey))]'")
```

2020-09-04 10:58 UTC, volas commented on code/modules/admin/admin.dm
> +		return           // dbcore revision needed
сюда копипастить костыль нет необходимости, можно оставить просто Execute

2020-09-04 11:02 UTC, FelixRuin commented
> И ты таки проверял работу?

"пожалуйста, научите в бд, ну или проверьте там... (〃￣ω￣〃)"

2020-09-15 16:13 UTC, volas commented on code/modules/admin/admin.dm
> +	var/DBQuery/query = dbcon.NewQuery("SELECT datediff(Now(),firstseen) as age, ingameage FROM erro_player WHERE ckey = '[sanitize_sql(ckey(player_ckey))]'")
а если сикей не верный/человека нет в базе?

2020-09-15 16:18 UTC, volas commented
> пожалуйста, научите в бд, ну или проверьте там...

ты можешь нагуглить как поднять локально mysql на win, проблема не сложная. Потом тебе нужно будет просто создать базы и импортнуть туда схемы из https://github.com/TauCetiStation/TauCetiClassic/tree/master/SQL, в конфиге игры прописать параметры.

Если ты где-то халтуришь - кому-то другому придется дорабатывать вместо тебя, так что давай, ты сможешь, я верю в тебя.

2020-10-24 03:07 UTC, closed without merging