[WiP] Добавление желудка, Возможность есть небольшие вещи и добавление размера мобов
TauCetiStation/TauCetiClassic pull request #5980
Opened 2020-08-11 11:55 UTC by FelixRuin

## Описание изменений
Добавлен желудок используемый для переваривания мобов внутри и хранения (с метаболизацией) реагентов (да, второй контейнер для химии внутри хумана)
Добавлен размер для желудков персонала станции (5 для обычных и 12 для воксов)
Добавлен параметр размера мобов (пока используемый только для проверок в поедании)
Изменено название прока CanEat на check_mouth_coverage для увеличения понятности прока
## Почему и что этот ПР улучшит
Разделение приходящих реагентов от желудка и при вкалывании, что позволит создать более сложный механизм реакции реагентов с теле, с устранением ситуаций взрыва калия в человеке от наличия воды, выпитой человеком ранее.
Увеличение возможностей рас, в особенности воксов, позволяющее показать их натуру более чётко.
Размер мобов позволит сделать механизм разницы в запихивании в ящик мартыхи или человека.
## Авторство
Felix Ruin - Winter Schock
## Чеинжлог
:cl: Winter Schock
- rscadd: Добавление в людей желудка
- rscadd: Добавление возможности есть предметы и очень мелких существ, а для воксов возможность есть вещи до размера с баллон и существ размером с обезьяну

2020-08-11 11:55 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2020-08-11 11:57 UTC, cool20141 commented
VORE STATION
VORE STATION
VORE STATION

2020-08-11 11:58 UTC, FelixRuin commented
> VORE STATION
> VORE STATION
> VORE STATION

не надо тут, это как-раз с бея контент, на ворь я заходил только для вдохновения

2020-08-11 12:01 UTC, cool20141 commented
Ну вообще круто, я давно хотел мышу скушать за таярочку

2020-08-11 12:52 UTC, LudwigVonChesterfield commented on code/game/objects/objs.dm
> +/proc/check_mouth_coverage(user, mob, food, eatverb = "consume")
Если захочешь - приятно было бы если бы это стало проком у /mob/living

что-то типо

```
/mob/living/proc/check_mouth_coverage(mob/user, obj/item/food, eatverb = "consume")
  return TRUE

/mob/living/carbon/human/check_mouth_coverage(mob/user, obj/item/food, eatverb = "consume")
  return !(head.flags & HEADCOVERSMOUTH)
```

что-то такого вида

2020-08-11 12:53 UTC, LudwigVonChesterfield commented on code/modules/organs/organ_internal.dm
> +/obj/item/organ/internal/stomach/proc/can_eat_atom(var/atom/movable/food)
```suggestion
/obj/item/organ/internal/stomach/proc/can_eat_atom(atom/movable/food)
```

2020-08-11 12:53 UTC, LudwigVonChesterfield commented on code/modules/organs/organ_internal.dm
> +/obj/item/organ/internal/stomach/proc/is_full(var/atom/movable/food)
```suggestion
/obj/item/organ/internal/stomach/proc/is_full(atom/movable/food)
```

2020-08-11 12:54 UTC, LudwigVonChesterfield commented on code/modules/organs/organ_internal.dm
> +		reagents.metabolize(owner)
А не думаешь что было бы хорошо выпилить текущую систему метаболизма в угоду желудку? Он ведь делает точно то же, но теперь не будет у тех кто не должен пищеварить(СПУ)

2020-08-11 13:33 UTC, AndroBetel commented
сделай тогда чтоыб можно было шпагу проглотить

2020-08-11 14:31 UTC, FelixRuin commented on code/modules/organs/organ_internal.dm
> +		reagents.metabolize(owner)
будет очень странно, что если отказал желудок, то человек не сможет в метаболизм и тут даже инъекция парадаксона не поможет

2020-08-11 14:33 UTC, FelixRuin commented on code/game/objects/objs.dm
> +/proc/check_mouth_coverage(user, mob, food, eatverb = "consume")
да, подумывал я о переписывании этого прока, даже делал это, но чтоб не запутаться пока не стал его трогать до поры - до времени (работает как нужно, и то ладно)

2020-08-11 14:59 UTC, LudwigVonChesterfield commented on code/modules/organs/organ_internal.dm
> +		reagents.metabolize(owner)
А что может заставить желудок отказать... ?

И почему бы не разбить метаболизм разных веществ на разные органы в разных частях тела(гроин)...

2020-08-11 15:02 UTC, FelixRuin commented on code/modules/organs/organ_internal.dm
> +		reagents.metabolize(owner)
Очень много урона на желудке может заставить его отказать
И разбить метаболизм разных веществ на разные органы... только когда до этого дойдёт дело, пока дошло дело до желудка, с которым и так предстоит много доделываний, чтобы всё было хорошо

2020-08-11 15:03 UTC, LudwigVonChesterfield commented on code/modules/mob/holder.dm
> +/obj/item/weapon/holder/attack(mob/target, mob/user)
А почему этот случай не обрабатывается всё там же в аттакбае хумана(карбона)?

2020-08-11 15:04 UTC, LudwigVonChesterfield commented on code/modules/mob/living/living_defines.dm
> +	var/digestion_product = null
Учитывая что этот предмет используется только у желудка, его стоит вынести ему

2020-08-11 15:06 UTC, FelixRuin commented on code/modules/mob/living/living_defines.dm
> +	var/digestion_product = null
в плане? (да, эту штуку надо будет прописать мобам, что я пока не успел сделать)
Смысл этой переменной в появлении у моба то, что позволяет любому мобу быть переваренным, но каждый моб может иметь разную структуру, поэтому всякие дионы должны быть с травянистой штукой, роботы вообще давать железо и тд

2020-08-11 15:07 UTC, LudwigVonChesterfield commented on code/modules/mob/living/living_defines.dm
> +	var/digestion_product = null
А, я почему-то бегло подумал что это то, что переваривается сейчас

2020-08-11 15:10 UTC, FelixRuin commented on code/modules/mob/holder.dm
> +/obj/item/weapon/holder/attack(mob/target, mob/user)
Делал по аналогу с бея, поправлю

2020-08-12 06:13 UTC, TauKitty commented
This pull request has been mentioned on **Tau Ceti Station Forum**. There might be relevant details there:

https://forum.taucetistation.org/t/prostaya-ideya-dlya-uborki-myortvyh-myshej/19903/31

2020-08-12 06:21 UTC, TauKitty commented
This pull request has been mentioned on **Tau Ceti Station Forum**. There might be relevant details there:

https://forum.taucetistation.org/t/dobavlenie-zheludka-vozmozhnost-est-nebolshie-veshhi-i-dobavlenie-razmera-mobov/20682/1

2020-08-12 08:33 UTC, Tolerantboy commented
Добавили желудок, так добавляйте остальной ЖКТ, анус и дефекацию.
У клоуна появится возможность кидаться говном, а у СБ - полный обыск человека, в латексных перчаточках. 
![ммм](https://user-images.githubusercontent.com/20757723/89993571-95360180-dc8f-11ea-985a-65ab602e8307.png)

2020-08-12 10:07 UTC, FelixRuin commented
> Добавили желудок, так добавляйте остальной ЖКТ, анус и дефекацию.
> У клоуна появится возможность кидаться говном, а у СБ - полный обыск человека, в латексных перчаточках.
> ![ммм](https://user-images.githubusercontent.com/20757723/89993571-95360180-dc8f-11ea-985a-65ab602e8307.png)

я отказываюсь
![image](https://user-images.githubusercontent.com/31424899/90003284-873aad80-dc9c-11ea-81ab-19eb51d26ca8.png)

2020-08-12 18:40 UTC, FelixRuin commented
@LudwigVonChesterfield я тут сделал две is проверки на граб и холдера, мне его стоит сейчас расставить везде или только потом, чтоб не захламлять текущий пр?

2020-08-13 16:23 UTC, LudwigVonChesterfield commented
Ты не обязан, но если захочешь - было бы круто.

2020-08-13 16:24 UTC, cool20141 commented
А что будет с get_size_ratio и еще одним проком?

2020-11-27 04:20 UTC, FelixRuin commented
ОЧЕНЬ
СИЛЬНО
НАДЕЮСЬ
ЧТО
Я
НИЧЕГО
НЕ
ЗАБЫЛ

2020-11-27 04:54 UTC, Morair commented on code/modules/organs/organ_internal.dm
> +		reagents.metabolize(owner)
Это получается что метаболизм будет идти и от Life и от желудка, т.е. х2?

2020-11-27 04:56 UTC, FelixRuin commented on code/modules/organs/organ_internal.dm
> +		reagents.metabolize(owner)
метаболизм в life идёт только для реагентов в крови
а тут реагенты идут от того, что в желудке

2020-11-27 04:59 UTC, Morair commented on code/modules/organs/organ_internal.dm
> +		reagents.metabolize(owner)
Так не очень наверно со стороны баланса, считай х2 скорость любого реагента если выпить+обколоться, мб они будут попадать в желудок, а там уже со временем в моба переходить?

2020-11-27 05:08 UTC, FelixRuin commented on code/modules/organs/organ_internal.dm
> +		reagents.metabolize(owner)
Баланс... в риге не попьёшь, для трупов (если НАДЕЮСЬ процесс для органов не идёт при смерти) это не работает, желудок может отвалиться, а ещё и размер что-то около 50 кубов.

2020-11-27 06:56 UTC, KIBORG04 commented on code/modules/organs/organ_internal.dm
> +		reagents.metabolize(owner)
Хз, есть ли у тебя, но реагенты из желудка в меньшем количестве попадают в кровь, нежели их кололи бы в вену. (ирл)

2020-11-27 08:06 UTC, FelixRuin commented on code/modules/organs/organ_internal.dm
> +		reagents.metabolize(owner)
> сделал механ метаболизма, что часть реагентов переходит в кровь

> сделал механ, что любые нутриенты в крови не считая глюкозы наносят урона

> орёшь с того, почему все умирают от еды

2020-12-27 10:07 UTC, UsadoSmokk commented
Можно проверить данный ПР?

2020-12-27 10:10 UTC, Kortez90 commented on code/__DEFINES/mob.dm
> +#define SYNDICATE_AWARE    3
```suggestion
#define SYNDICATE_AWARE    3

```

2020-12-31 07:18 UTC, Kortez90 commented on code/__DEFINES/is_helpers.dm
> +#define isgrab(A) (istype(A, /obj/item/weapon/grab)) //gaah, someone can put this on correct places?
Наверное не надо пихать в хелперы моба какие-то там хелперы холдеров и грабов? Для этого ниже есть `// ELSE`.

2020-12-31 07:24 UTC, FelixRuin commented on code/__DEFINES/is_helpers.dm
> +#define isgrab(A) (istype(A, /obj/item/weapon/grab)) //gaah, someone can put this on correct places?
done

2021-01-05 18:16 UTC, KIBORG04 commented on code/_onclick/item_attack.dm
> +		src.drop_from_inventory(victim)
```suggestion
	visible_message("<span class='danger'>\The [src] is attempting to devour \the [victim] whole!</span>")
	var/mob/living/target = victim
	if(isobj(victim))
		target = src
	if(!do_mob(src,target,eat_speed))
		return FALSE
	visible_message("<span class='danger'>\The [src] devours \the [victim] whole!</span>")
	if(ismob(victim))
		target.log_combat(src, "Devoured")
	else
		drop_from_inventory(victim)
```

2021-01-05 18:23 UTC, KIBORG04 commented on code/modules/mob/living/living.dm
> +					stomach.reagents.remove_reagent(R, R.volume * 0.5 )
А зачем тут полностью удалять реагенты. а не вместе с рыганиной вываливать?

2021-01-13 20:52 UTC, FelixRuin commented on code/modules/mob/living/living.dm
> +					stomach.reagents.remove_reagent(R, R.volume * 0.5 )
вываливается, поправил, как вообще систему блевоты

2021-01-13 20:56 UTC, Kortez90 commented on code/modules/mob/living/living.dm
> +	var/turf/simulated/T = loc
А на ансимах будет рантайм?

2021-01-13 21:05 UTC, FelixRuin commented on code/modules/mob/living/living.dm
> +	var/turf/simulated/T = loc
по фаааакту да, но от того, что на ансимах нельзя создать блевоту
хм... кажется и до этого с этим была проблема... хмф...

2021-01-13 21:18 UTC, KIBORG04 commented on code/modules/mob/living/living.dm
> +	var/turf/simulated/T = loc
Скорее проблема в том, почему кто-то не захотел создавать на ансимах блевоту.
И да, я чекнул код `add_vomit_floor()` и ничего интересного не нашел. Крч, это классовое разделение, как по мне, не имеет смысла

2021-01-13 22:01 UTC, FelixRuin commented on code/modules/mob/living/living.dm
> +	var/turf/simulated/T = loc
поправил, теперь рантаймов нет по этой теме

2021-01-13 22:01 UTC, Kortez90 commented on code/game/turfs/turf.dm
> +			V.stop_light()
```suggestion
			V.stop_light()

```

2021-01-13 22:02 UTC, KIBORG04 commented on code/modules/mob/living/living.dm
> +	var/turf/simulated/T = loc
```suggestion
	var/turf/T = loc
```
Нам теперь не важно какой турф

2021-01-17 21:20 UTC, KIBORG04 commented on code/_onclick/item_attack.dm
> +		if(!CanEat(src, src, I, "eat"))
> /mob/living/carbon/human/CanEat(mob/user, atom/movable/food, eatverb = "consume")

Тут только 3 параметра, а ты передаешь 4 аргумента

2021-01-17 21:21 UTC, KIBORG04 commented on code/_onclick/item_attack.dm
> +	if(!do_mob(src, target,eat_speed))
```suggestion
	if(!do_mob(src, target, eat_speed))
```

2021-01-17 21:23 UTC, KIBORG04 commented on code/_onclick/item_attack.dm
> +	var/eat_speed = can_devour(victim)
Довольно странно, что прок с таким названием в итоге возвращает скорость

2021-01-17 21:26 UTC, KIBORG04 commented on code/game/machinery/adv_med.dm
> +							content = "Unknown [content_count] body present:"
```suggestion
						if(IO.contents.len)
							content = "Unknown [IO.contents.len] body present:"
```
Можно же так сделать

2021-01-17 21:37 UTC, KIBORG04 commented on code/modules/organs/organ_internal.dm
> +	. = ..()
```suggestion
	return ..()
```

2021-01-17 21:44 UTC, FelixRuin commented on code/_onclick/item_attack.dm
> +	var/eat_speed = can_devour(victim)
эм... просто совмещение возможности того можно-ли съесть жертву с тем что даст при разных ситуациях, мне кажется достаточно логичо?

2021-01-17 21:49 UTC, KIBORG04 commented on code/modules/organs/organ_internal.dm
> +	if(do_after(user,(breakout_time MINUTE), target = src))
```suggestion
	if(do_after(user, (breakout_time MINUTE), target = src))
```

2021-01-17 21:50 UTC, KIBORG04 commented on code/modules/organs/organ_internal.dm
> +		user.forceMove(get_turf(src.owner))
```suggestion
		user.forceMove(get_turf(owner))
```

2021-01-17 21:52 UTC, KIBORG04 commented on code/__DEFINES/mob.dm
> +#define GLUT_ANYTHING 11 // Eat anything, ever
Может лучше сделать степени двойки для этих флагов?

2021-01-17 22:05 UTC, KIBORG04 commented
Посмотрите код еще кто-нибудь и можно в ТМ.

2021-01-18 01:42 UTC, FelixRuin commented on code/__DEFINES/mob.dm
> +#define GLUT_ANYTHING 11 // Eat anything, ever
только если пояснишь как это сделать для чисел 3 и 11

2021-01-18 09:15 UTC, KIBORG04 commented on code/__DEFINES/mob.dm
> +#define GLUT_ANYTHING 11 // Eat anything, ever
Ну так 1, 2, 4, 8, 16, 32, 64, 128..

2021-01-18 09:17 UTC, KIBORG04 commented on code/__DEFINES/mob.dm
> +#define GLUT_ANYTHING 11 // Eat anything, ever
Потому что, в теории, это может чтото ломать, ведь 3 - 11, а 11 - 1011, в то время как все степени двойки это одна еденица и нули

2021-01-18 09:32 UTC, volas commented on code/__DEFINES/mob.dm
> +#define GLUT_ANYTHING 11 // Eat anything, ever
как можно писать код с бинарными флагами и логикой даже не разобравшись в системе счисления? :facepalm:

2021-01-21 22:09 UTC, Kortez90 commented on code/modules/organs/organ_internal.dm
> +		S.reagents.add_reagent("nutriment", 0.01)
Почему вообще предметы, нутриментов не имеющие, должны их вдруг добавлять:

2021-01-21 22:11 UTC, FelixRuin commented on code/modules/organs/organ_internal.dm
> +		S.reagents.add_reagent("nutriment", 0.01)
и то верно, сейчас

2021-01-21 22:46 UTC, FelixRuin commented on code/modules/organs/organ_internal.dm
> +		S.reagents.add_reagent("nutriment", 0.01)
всё, поправил, останется мне только для вещей добавить разные составляющие

2021-01-22 17:28 UTC, Sakuya-Izayoi commented on code/_onclick/item_attack.dm
> +/mob/living/carbon/human/attackby(obj/item/I, mob/user)
Нет проверки на из_бизи

2021-01-22 17:41 UTC, Kortez90 commented on code/modules/organs/organ_internal.dm
> +		S.reagents.add_reagent("nutriment", 0.01)
Зачем? Есть же `has_reagent`.

2021-01-23 09:03 UTC, WatlerJe commented
я думаю, что 228 ячеек более четко подчеркивают натуру воксов. Алсо что по поводу толстяков? Ведь раньше фича толстых как раз таки и заключалась в возможность жратъ все подряд, в том числе и монки, от туда у генокрада укол для похудения.

В общем да, стоило обратиться к истокам для начала. Я понимаю, что новой расе разработанной и внедренной футфетешистом необходимо больше фетешистких приколов, но если уже беретесь то старайтесь продумать все аспекты.

2021-01-23 10:15 UTC, volas commented
пока по ревью исправления не внесены в тм-е нет необходимости

2021-02-02 13:01 UTC, FelixRuin commented on code/_onclick/item_attack.dm
> +/mob/living/carbon/human/attackby(obj/item/I, mob/user)
добавил

2021-02-02 13:02 UTC, Kortez90 commented on code/modules/organs/organ_internal.dm
> +			S.reagents.add_reagent(digestion_product, damage)
Может лучше под ранний возврат переделать?

2021-02-02 13:03 UTC, FelixRuin commented on code/modules/organs/organ_internal.dm
> +		S.reagents.add_reagent("nutriment", 0.01)
добавил высасывание реагентов при их наличии и реагенты из пустоты при наличии реагента при переваривании

2021-02-02 13:04 UTC, FelixRuin commented on code/modules/organs/organ_internal.dm
> +			S.reagents.add_reagent(digestion_product, damage)
эм... поясни? Не особо понял мысль

2021-02-02 13:06 UTC, Kortez90 commented on code/modules/organs/organ_internal.dm
> +			S.reagents.add_reagent(digestion_product, damage)
```
if(!reagents && !reagents.total_volume)
	return
if(prob(10))
	<Остальной код>
```

2021-02-02 13:08 UTC, Kortez90 commented
Когда фиксишь какой-то issue, то обновляй ПР с префиксами.

2021-02-02 13:10 UTC, FelixRuin commented on code/modules/organs/organ_internal.dm
> +			S.reagents.add_reagent(digestion_product, damage)
акх, проверки до... принял... хмф... но тут слегка другое, сколько или-или
тоесть или мы имеем реагенты и будем выкачивать их с 10 процентным шансом
или если их нету и есть дигест продукт - давать его
тоесть если вставлять до prob, то смысла нету, сколько проверять потом и так придётся

2021-02-02 13:43 UTC, Kortez90 commented on code/modules/organs/organ_internal.dm
> +			S.reagents.add_reagent(digestion_product, damage)
```
if(!reagents)
	S.reagents.add_reagent(digestion_product, damage)
reagents.trans_to(S, reagents.total_volume * (damage / health))
```
А если так?

2021-02-02 13:53 UTC, KIBORG04 commented on code/__DEFINES/mob.dm
> +#define GLUT_ITEM_ANYTHING (1<<3) //Eat any item
ты специально потерял (1<<2)?

2021-02-02 13:54 UTC, KIBORG04 commented on code/modules/organs/organ.dm
> +	loc = H
```suggestion
	forceMove(H)
```

2021-02-02 13:57 UTC, KIBORG04 commented on code/modules/organs/organ_internal.dm
> +			S.reagents.add_reagent(digestion_product, damage)
Здесь вообще не нужен ранний возврат

2021-02-02 13:59 UTC, FelixRuin commented on code/__DEFINES/mob.dm
> +#define GLUT_ITEM_ANYTHING (1<<3) //Eat any item
аыаыаыаыаы цифарки, слофно, моя забыть, сейчас всё будет

2021-02-02 14:01 UTC, KIBORG04 commented on code/modules/organs/organ.dm
> +	loc = H
А вообще.. Может быть лучше в атом_ините органов пихать их в людишек?

2021-02-02 14:12 UTC, FelixRuin commented on code/modules/organs/organ.dm
> +	loc = H
может быть и да
но я даже плюсов от этого найти не могу

2021-02-02 14:13 UTC, KIBORG04 commented on code/modules/organs/organ.dm
> +	loc = H
У нас сейчас все органы создаются в нулле, а могли бы в хумане

2021-02-02 14:18 UTC, FelixRuin commented on code/modules/organs/organ.dm
> +	loc = H
гх... и? Я не понимаю самой проблемы, в чём разница... (да и глянув атом инит... вроде всё складно выглядит, если есть моб - идёт прок на вставления органа, в этом проке орган и перемещается в моба... в чём проблема?

2021-02-02 14:20 UTC, KIBORG04 commented on code/modules/organs/organ.dm
> +	loc = H
Забей

2021-02-05 18:59 UTC, Ahion commented
Жаль что эта фича только для хуманов. Я думал что этот ПР поможет мне с ксеноморфами))

Странно что ты не затронул старую систему желудка, которая помещает проглоченных мобов в `var/list/stomach_contents`. Не будет ли она тебе мешать? Например, толстые люди, как я понимаю, могут проглатывать обезьян. Возможно твоя фича будет накладываться на эту?
https://github.com/TauCetiStation/TauCetiClassic/blob/86883486978fb38cdf94704ac66cd390149214d7/code/modules/mob/mob_grab.dm#L556-L558

Короче. Хочу желудок для карбонов ))

2021-02-05 19:09 UTC, FelixRuin commented
> Жаль что эта фича только для хуманов. Я думал что этот ПР поможет мне с ксеноморфами))
> 
> Странно что ты не затронул старую систему желудка, которая помещает проглоченных мобов в `var/list/stomach_contents`. Не будет ли она тебе мешать? Например, толстые люди, как я понимаю, могут проглатывать обезьян. Возможно твоя фича будет накладываться на эту?
> https://github.com/TauCetiStation/TauCetiClassic/blob/86883486978fb38cdf94704ac66cd390149214d7/code/modules/mob/mob_grab.dm#L556-L558
> 
> Короче. Хочу желудок для карбонов ))

есть мартых за толстого... чего!? Что за ересь и почему я хочу её выпилить
А желудок для карбонов... >_> это очень такое, ибо желудок хранит реагенты... вещи... и так далее, а это много другого для желудков ксеноморфов

2021-02-05 23:00 UTC, Dominig12 commented
> > Жаль что эта фича только для хуманов. Я думал что этот ПР поможет мне с ксеноморфами))
> > Странно что ты не затронул старую систему желудка, которая помещает проглоченных мобов в `var/list/stomach_contents`. Не будет ли она тебе мешать? Например, толстые люди, как я понимаю, могут проглатывать обезьян. Возможно твоя фича будет накладываться на эту?
> > https://github.com/TauCetiStation/TauCetiClassic/blob/86883486978fb38cdf94704ac66cd390149214d7/code/modules/mob/mob_grab.dm#L556-L558
> > 
> > Короче. Хочу желудок для карбонов ))
> 
> есть мартых за толстого... чего!? Что за ересь и почему я хочу её выпилить
> А желудок для карбонов... >_> это очень такое, ибо желудок хранит реагенты... вещи... и так далее, а это много другого для желудков ксеноморфов (И КАКИЕ К ЧЁРТУ ЖЕЛУДКИ У КСЕНОМОРФОВ!? КАК И ЗАЧЕМ)

чтобы лявра кушала, и росла

2021-02-05 23:04 UTC, FelixRuin commented
> чтобы лявра кушала, и росла

неа, это уже большой ксенос может целиком сожрать человека
как? Да чёрт его знает

2021-02-05 23:41 UTC, KIBORG04 commented on code/modules/organs/organ_internal.dm
> +	if(S.health <= 0)
А зачем проверять ХП желудка?

2021-02-05 23:43 UTC, KIBORG04 commented on code/modules/organs/organ_internal.dm
> +	if(S.health <= 0)
![image](https://user-images.githubusercontent.com/26389417/107100314-07ddff00-6825-11eb-8fe9-1864e6650f9f.png)

Как я и думал, картошка переваривается бесконечно

2021-02-05 23:44 UTC, KIBORG04 commented on code/modules/organs/organ_internal.dm
> +	else if(istype(food, /obj/item) && !istype(food, /obj/item/weapon/holder)) //Don't eat holders. They are special.
```suggestion
	else if(istype(food, /obj/item) && !isholder(food)) //Don't eat holders. They are special.
```

2021-02-11 18:17 UTC, FelixRuin commented on code/modules/organs/organ_internal.dm
> +	if(S.health <= 0)
пофиксил, всё переваривается теперь

2021-02-11 18:23 UTC, KIBORG04 commented on code/modules/reagents/reagent_containers/food.dm
> +	return ..()
```suggestion
	return ..()

```

2021-02-24 08:07 UTC, volas requested changes

2021-02-24 08:07 UTC, volas commented on code/__DEFINES/mob.dm
> +#define GLUT_ITEM_ANYTHING (1<<2) //Eat any item
Тут не нужны бит-флаги.

``GLUT_ITEM_TINY``, ``GLUT_ITEM_NORMAL``, ``GLUT_ITEM_ANYTHING`` не являются взаимодополняемыми и в них нету смысла в виде флагов. Причем третий флаг можно записать как бинарное И первых двух, т.е. всего 2 взаимоисключающих для итемов и 2 взаимоисключающих для предметов.
И в этом нету смысла еще по той причине, что размеры мобов и предметов в виде последовательной десятичной нумерации.

2021-02-24 08:07 UTC, volas commented on code/__DEFINES/mob.dm
> +#define MOB_MINISCULE	1
Уже есть система размеров для предметов
https://github.com/TauCetiStation/TauCetiClassic/blob/6a1eb48c95a8164353f042463269aa42e56ab4ea/code/__DEFINES/inventory_sizes.dm#L4-L10

Стоило бы взять её за основу и просто дополнить/расширить.

2021-02-24 08:07 UTC, volas commented on code/__DEFINES/mob.dm
> +#define DEVOUR_FAST 3 SECONDS
Это выглядит как еще одна система метаболизма кое-как пришитая сбоку к уже текущей.

2021-02-24 08:55 UTC, FelixRuin commented on code/__DEFINES/mob.dm
> +#define DEVOUR_FAST 3 SECONDS
это лишь таймеры на проглатывание вещей... или я чего-то не понял?

2021-02-24 08:57 UTC, FelixRuin commented on code/__DEFINES/mob.dm
> +#define MOB_MINISCULE	1
Размеры мобов имеют точное представление
В плане чтобы можно было сделать например моба с размером между средним и малым (15) и так далее, тоесть возможность к более точной градации...

2021-02-24 09:00 UTC, KIBORG04 commented on code/__DEFINES/mob.dm
> +#define MOB_MINISCULE	1
Я не уверен, но вроде сами значения у размеров предметов ни в каких формулах не используются, а значит ты можешь и итемам прикрутить эту самую точную градацию

2021-03-27 10:24 UTC, FelixRuin commented on code/__DEFINES/mob.dm
> +#define DEVOUR_FAST 3 SECONDS
а если вообще
всё работает по такой системе:
человек что-то может выпить - это перемещается в желудок
человек может что-то съесть - это перемещается в желудок уже реагентами
человек может что-то проглотить - это перемещается в желудок и уже там постепенно превращается в реагенты
фактически это просто добавления взаимодействия с предметами
да, яблоко можно и съесть, и проглотить, но по итогу будет 1 результат

2021-03-27 10:50 UTC, FelixRuin commented on code/__DEFINES/mob.dm
> +#define MOB_MINISCULE	1
> ~Я не уверен, но вроде сами значения у размеров предметов ни в каких формулах не используются~, а значит ты можешь и итемам прикрутить эту самую точную градацию

https://github.com/TauCetiStation/TauCetiClassic/blob/6a1eb48c95a8164353f042463269aa42e56ab4ea/code/__DEFINES/inventory_sizes.dm#L16
https://github.com/TauCetiStation/TauCetiClassic/blob/61027c4c1e30366cbcb3e21b2f3b4e67749844a5/code/game/objects/items/weapons/gift_wrappaper.dm#L22
https://github.com/TauCetiStation/TauCetiClassic/blob/61027c4c1e30366cbcb3e21b2f3b4e67749844a5/code/game/objects/items/weapons/gift_wrappaper.dm#L147
https://github.com/TauCetiStation/TauCetiClassic/blob/61027c4c1e30366cbcb3e21b2f3b4e67749844a5/code/game/objects/items/weapons/storage/bags.dm#L83
https://github.com/TauCetiStation/TauCetiClassic/blob/61027c4c1e30366cbcb3e21b2f3b4e67749844a5/code/modules/clothing/head/wiz_tophat.dm#L414
https://github.com/TauCetiStation/TauCetiClassic/blob/61027c4c1e30366cbcb3e21b2f3b4e67749844a5/code/modules/mob/mob.dm#L1013

в достаточно большом количестве мест используется факт того, что значения размеров предметов у нас числа от 1 до 6 и вводить это в этом пре будет только из извращённого желания вот хоть что-то точно сломать, ибо с вероятностью 100% это уже будет тяжело уследить из-за раздутости пра в данный момент.

2021-03-27 12:11 UTC, FelixRuin commented on code/__DEFINES/mob.dm
> +#define GLUT_ITEM_ANYTHING (1<<2) //Eat any item
переделал

2021-03-27 12:15 UTC, FelixRuin commented on code/__DEFINES/mob.dm
> +#define MOB_MINISCULE	1
переделал под таблицу размеров айтемов, теперь всё в 1 таблице, да

2021-06-16 17:32 UTC, closed without merging