Ритуал на призыв латного комплекта капеллану
TauCetiStation/TauCetiClassic pull request #6007
Opened 2020-08-16 21:04 UTC by da-kiselev

## Описание изменений
Добавил капеллану ритуал на призыв латного комплекта. Если ее носит сам священник, то броня имеет статы лучше, чем у обычных людей. Муслимы призывать латы не могут.
## Почему и что этот ПР улучшит
Теперь можно брать космический Иерусалим!
## Авторство
Da_kiselev. Большое спасибо KIBORG'y за курирование проекта и неоценимую помощь. Спасибо Деду за спрайты. СПАСИБО РЕМАЙНДУ ЗА ПОМОЩЬ С КОММИТАМИ, БОЖЕ!
## Чеинжлог
:cl: Da_kiselev
- tweak: Добавил новый ритуал священнику на латный комплект брони.
- image: Добавил спрайты лат.
- image Добавил шкатулку, в которой появляются латы.

2020-08-16 21:04 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2020-08-16 21:07 UTC, da-kiselev commented
А че бот ругается? У меня все компилилось

2020-08-16 21:08 UTC, FelixRuin commented
у тебя, слегка, очень старый билд

2020-08-16 21:12 UTC, FelixRuin commented on code/game/objects/items/weapons/chaplain_weapons.dm
> +	if (!(ishuman(user) || ticker) && ticker.mode.name != "monkey")
```suggestion
	if (!(ishuman(user) || SSticker) && SSticker.mode.name != "monkey")
```

2020-08-16 21:13 UTC, FelixRuin commented on code/game/objects/items/weapons/chaplain_weapons.dm
> +		if((M.mind in ticker.mode.cult) && user.mind && user.mind.holy_role == HOLY_ROLE_HIGHPRIEST && prob(33))
```suggestion
		if((M.mind in SSticker.mode.cult) && user.mind && user.mind.holy_role == HOLY_ROLE_HIGHPRIEST && prob(33))
```

2020-08-16 21:14 UTC, FelixRuin commented on code/game/objects/items/weapons/chaplain_weapons.dm
> +			ticker.mode.remove_cultist(M.mind)
```suggestion
			SSticker.mode.remove_cultist(M.mind)
```

2020-08-16 21:16 UTC, da-kiselev commented on code/game/objects/items/weapons/chaplain_weapons.dm
> +			ticker.mode.remove_cultist(M.mind)
Моя вина, на старой версии писал, ща исправлю

2020-08-16 21:19 UTC, T6751 commented on code/game/boxes.dm
> +/*
у нас коробки хранятся по адресу \code\game\objects\items\weapons\storage\boxes.dm
Зачем создавать ещё один файл с дубликатами тех коробок?

2020-08-16 21:24 UTC, da-kiselev commented on code/game/boxes.dm
> +/*
Я вроде не создавал, мб случайно?

2020-08-16 21:24 UTC, T6751 commented on code/game/objects/items/weapons/storage/boxes.dm
> +	icon_state = "nanotrasen_box"
```suggestion
	icon_state = "nanotrasen_box"

```

2020-08-16 21:24 UTC, T6751 commented on code/game/objects/items/weapons/spawn_item.dm
> +	return TRUE
```suggestion
	return TRUE

```

2020-08-16 21:25 UTC, T6751 commented on code/modules/religion/rites/spawn_item.dm
> +	return TRUE
```suggestion
	return TRUE

```

2020-08-16 21:33 UTC, da-kiselev commented
Теперь все ок?

2020-08-16 21:33 UTC, da-kiselev commented
Странно, компилилось все нормально, а как стал переносить, сразу проблемы

2020-08-16 21:35 UTC, T6751 commented on code/game/objects/items/weapons/spawn_item.dm
> +/*
такая же история, как и с коробками
\code\modules\religion\rites\spawn_item.dm
https://github.com/TauCetiStation/TauCetiClassic/blob/master/code/modules/religion/rites/spawn_item.dm

2020-08-16 21:38 UTC, da-kiselev commented on code/game/objects/items/weapons/spawn_item.dm
> +/*
Блин, я когда Файлы переносил, напутал все

2020-08-16 21:41 UTC, T6751 commented on code/game/objects/items/weapons/spawn_item.dm
> +/*
Только не забудь перенести код, который добавил в эти удаленные файлы

2020-08-16 21:42 UTC, T6751 commented on code/game/boxes.dm
> -	new /obj/item/clothing/head/helmet/religion(src)
я думаю, это нужно было перенести

2020-08-16 21:42 UTC, da-kiselev commented on code/game/objects/items/weapons/spawn_item.dm
> +/*
У меня они продублировались) Так что я клоны удалил

2020-08-16 21:42 UTC, da-kiselev commented on code/game/boxes.dm
> -	new /obj/item/clothing/head/helmet/religion(src)
Это уже там

2020-08-16 21:43 UTC, T6751 commented on code/game/boxes.dm
> -	new /obj/item/clothing/head/helmet/religion(src)
тогда ок

2020-08-16 21:44 UTC, da-kiselev commented on code/game/boxes.dm
> -	new /obj/item/clothing/head/helmet/religion(src)
> и это тоже перенести

Я говорю, прикол в том, что из-за моей невнимательности, Файлы продублировались, все на месте. (Надеюсь)

2020-08-17 11:00 UTC, KIBORG04 commented
>Da_kiselev

tweak: Добавил новый ритуал священнику на латный комплект брони.
image: Добавил спрайты лат.
image Добавил шкатулку, в которой появляются латы.

Второй пункт не нужен, в третьем пункте измени имедж на твик, ибо эту шкатулку можно и в других местах использовать. А текст поменяй примерно на "Добавлена шкатулка для ритуалов капеллана"

2020-08-17 11:03 UTC, KIBORG04 commented on code/game/objects/items/weapons/storage/boxes.dm
> +/obj/item/weapon/storage/box/religion/atom_init()
Спавнь, пожалуйста, эти вещи по окончании ритуала в invoke_effect. Так мы шкатулку сможем юзать и в других местах.

2020-08-17 11:04 UTC, KIBORG04 commented on code/modules/religion/rites/spawn_item.dm
> +	favor_cost = 150
```suggestion
	favor_cost = 350
```
Щас слишком просто добывать ману, а тут ты получаешь мега сет на 70 от мили

2020-08-17 11:06 UTC, KIBORG04 commented on code/game/objects/items/weapons/storage/boxes.dm
> +/obj/item/weapon/storage/box/religion/atom_init()
А, не, я вспомнил, через инвок эффект не получился, спавнь через прок modify_item

2020-08-18 18:00 UTC, LudwigVonChesterfield commented on code/game/objects/items/weapons/chaplain_weapons.dm
> +	var/list/holy_armor = list(melee = 70, bullet = 15, laser = 0, energy = 0, bomb = 0, bio = 0, rad = 0)
Мне не нравится что у капеллана будет ультрабомбезная броня если честно

2020-08-18 18:00 UTC, LudwigVonChesterfield commented on code/modules/religion/rites/spawn_item.dm
> +		user.visible_message("Your God doesn't love you, muslim")
а зачем такое делать

2020-08-18 18:02 UTC, LudwigVonChesterfield commented on code/game/objects/items/weapons/chaplain_weapons.dm
> +/obj/item/clothing/head/helmet/religion/equipped(mob/user, slot)
Это более глобальная проблема, но если кто-то утратит святость, то броня будет на нём продолжать функционировать

Ты не обязан её решать, но если захочешь - рекомендую изобрести сигнал по типу COMSIG_MOB_ADJUST_HOLY, и тут бы его слушать

2020-08-18 18:02 UTC, KIBORG04 commented on code/modules/religion/rites/spawn_item.dm
> +		user.visible_message("Your God doesn't love you, muslim")
Там броня похожа на крестоноскую, а крестоносцы воевали против мусульман

2020-08-18 18:02 UTC, cool20141 commented on code/modules/religion/rites/spawn_item.dm
> +		user.visible_message("Your God doesn't love you, muslim")
Жесть, объявляем джихад кафиру. Не шутка :rage:

2020-08-18 18:03 UTC, LudwigVonChesterfield commented on code/modules/religion/rites/spawn_item.dm
> +		user.visible_message("Your God doesn't love you, muslim")
@KIBORG04 

ну я бы тогда наверное лучше как-то на аспектах завязал, мы же вон старались отвязывать фичи от скинов библии, и завязывать на аспекты...

2020-08-18 18:04 UTC, LudwigVonChesterfield commented
Лично я против давать капеллану уберброню за ритуал

Это отлично от щита, потому-что щит не позволяет драться пока активен - превращая капеллана в поддержку/наблюдателя, а не драчуна

(разве-что очень резко переключать во время боя щит, но это уже награждение скилловых игроков, и я не против такого)
((в отличии от хуааарррр гыгыгыгыыг уаааа броня на 70% защищающая от мили уауаууа))

2020-08-18 18:06 UTC, KIBORG04 commented on code/modules/religion/rites/spawn_item.dm
> +		user.visible_message("Your God doesn't love you, muslim")
Хм, ладно, ты прав. Киселев, выпиливай это

2020-08-18 18:07 UTC, cool20141 commented
Ну так только от мили. Надо же как-то культобесским констрактам и мечам противостоять, а если будет буянить и лезть в сражения–расстреляют спокойно

2020-08-18 18:08 UTC, KIBORG04 commented
> Ну так только от мили. Надо же как-то культобесским констрактам и мечам противостоять, а если будет буянить и лезть в сражения–расстреляют спокойно

Я хз как сейчас, но культ почти всегда сосёт

2020-08-18 18:11 UTC, cool20141 commented
Ну не знаю, у них просто неограниченная сила, позволяющая превращать всю станцию, насильно или нет, в покорных воинов, которые будут разносить все СБ без проблем, а учитывая. что у них еще и куча заклинаний, типа стана, эми и бладбойла, то проигрывать за культей–это довольно сложное занятие

2020-08-18 18:13 UTC, LudwigVonChesterfield commented
Этот ПР не меняет ничего вышеперечисленного из того что ты сказал

Если бы эта броня не позволяла кастовать культистам(но не имела бешеных резистов), это было бы круто.

2020-08-18 19:56 UTC, TungstenOctopus requested changes
Нужны скриншоты всех добавленных спрайтов в естественной среде обитания, т.е. из игры.

2020-08-19 12:31 UTC, da-kiselev commented
> Нужны скриншоты всех добавленных спрайтов в естественной среде обитания, т.е. из игры.

Готово

2020-08-19 13:15 UTC, KIBORG04 commented on code/game/gamemodes/cult/cult_datums.dm
> +				if((N || (A && H)))
```suggestion
				if(N || (A && H))
```

2020-08-24 16:49 UTC, KIBORG04 commented on code/game/objects/items/weapons/chaplain_weapons.dm
> +	max_heat_protection_temperature = HELMET_MAX_HEAT_PROTECTION_TEMPERATURE
Хм, у нас же металлический шлем, который никак не спасает от повышенной температуры.

2020-08-26 09:54 UTC, da-kiselev commented on code/game/objects/items/weapons/chaplain_weapons.dm
> +	max_heat_protection_temperature = HELMET_MAX_HEAT_PROTECTION_TEMPERATURE
Ну почему, он все же часть температуры будет на себя брать

2020-08-26 09:56 UTC, KIBORG04 commented on code/game/objects/items/weapons/chaplain_weapons.dm
> +	max_heat_protection_temperature = HELMET_MAX_HEAT_PROTECTION_TEMPERATURE
Будет, а потом будет отдавать накопленную температуру в человека и воздух.
И чекни какое число за собой скрывает данный дефайн, мб поймёшь моё негодование

2020-09-14 09:59 UTC, LudwigVonChesterfield commented on code/game/objects/items/weapons/chaplain_weapons.dm
> +	max_heat_protection_temperature = HELMET_MAX_HEAT_PROTECTION_TEMPERATURE
б-г защищает от фороновых пожаров

2020-09-19 16:40 UTC, da-kiselev commented
@TungstenOctopus Готово

2020-09-19 17:08 UTC, KIBORG04 commented on code/game/objects/items/weapons/chaplain_weapons.dm
> +	max_heat_protection_temperature = HELMET_MAX_HEAT_PROTECTION_TEMPERATURE
> б-г защищает от фороновых пожаров

Это же латы, латы! А не термос

2020-09-19 19:20 UTC, da-kiselev commented
Спрайт забраковали, ищу нового спрайтера

2020-09-20 05:14 UTC, TauKitty commented
This pull request has been mentioned on **Tau Ceti Station Forum**. There might be relevant details there:

https://forum.taucetistation.org/t/ishhu-sprajtera-dlya-lat/21194/9

2020-09-20 13:49 UTC, da-kiselev commented
@T6751 Спрайты были одобрены, все нормально, можно одобрять ПР (Если у кодеров нет вопросов).

2020-09-20 13:57 UTC, TungstenOctopus approved these changes

2020-09-20 14:14 UTC, KIBORG04 commented
В тм лучше

2020-09-20 15:01 UTC, T6751 commented
по коду вроде бы всё хорошо, но на всякий случай, ТМ

2020-09-21 08:41 UTC, LudwigVonChesterfield commented on code/game/gamemodes/cult/cult_datums.dm
> +				var/obj/item/clothing/suit/armor/religion/A = locate() in heretic
То есть броня в руках тоже должна защищать?

2020-09-21 08:55 UTC, KIBORG04 commented on code/game/gamemodes/cult/cult_datums.dm
> +				var/obj/item/clothing/suit/armor/religion/A = locate() in heretic
Хм, действительно. Киселев, делай проверки и на надетость (слот_четоттам)

2020-09-21 09:05 UTC, da-kiselev commented on code/game/gamemodes/cult/cult_datums.dm
> +				var/obj/item/clothing/suit/armor/religion/A = locate() in heretic
Ближе к выходным подправлю, вроде проблема не критична

2020-09-29 21:23 UTC, KIBORG04 commented on code/game/gamemodes/cult/cult_datums.dm
> +				heretic.equip_to_slot_or_del(new A, SLOT_WEAR_SUIT)
Ты чево наделал.

Проверка на слот делается совсем не так. Название функции уже говорит, что она не проверяет ниче

2020-09-30 12:43 UTC, LudwigVonChesterfield requested changes
То что сказал Киборг, только менее грубо.

2020-09-30 12:51 UTC, LudwigVonChesterfield requested changes
То что сказал Киборг, только менее грубо.

У мобов есть переменные слотов которые отсылаются на предметы в них, их и надо использовать.

2020-09-30 12:52 UTC, KIBORG04 commented
Я же по-доброму, а не грубо

2020-11-07 06:02 UTC, closed without merging