[WIP] добавляет мины
TauCetiStation/TauCetiClassic pull request #6012
Opened 2020-08-18 09:54 UTC by AndroBetel

## Описание изменений
добавляет возможность размещать и убирать мины
переделывает код мин
добавляет новые мины и убирает глупые старые

todo - выудить из кого-нибудь красивые спрайты, засунуть мины куда-нибудь, добавить ещё парочку.
## Почему и что этот ПР улучшит
новые фичи это круто... это классно...
## Авторство

## Чеинжлог
:cl: 
- rscadd: Добавляет противопехотные (и не только) мины.

2020-08-18 09:54 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2020-08-18 10:49 UTC, KIBORG04 commented on code/game/objects/effects/mines.dm
> +	if(istype(M, /mob/living))
Разве от мышей такие мины должны срабатывать?

2020-08-18 10:51 UTC, KIBORG04 commented
Может добавить в мины провода?

2020-08-18 11:00 UTC, KIBORG04 commented on code/game/objects/effects/mines.dm
> +/obj/item/mine/Crossed(AM as mob|obj)
```suggestion
/obj/item/mine/Crossed(atom/movable/AM)
```

2020-08-18 11:01 UTC, KIBORG04 commented on code/game/objects/effects/mines.dm
> +		alpha = 45
Нериалистично

2020-08-19 01:26 UTC, AndroBetel commented on code/game/objects/effects/mines.dm
> +	if(istype(M, /mob/living))
а почему нет

2020-08-19 01:26 UTC, AndroBetel commented on code/game/objects/effects/mines.dm
> +		alpha = 45
нереалистично? нереалистично deez nuts

2020-08-19 05:51 UTC, LudwigVonChesterfield commented
А если сделаешь компоненту реактивной взрывчатки, то минировать можно было бы абсолютно любой предмет и чтобы когда на него наступаешь бабах

пепе заминированный торт.

2020-08-19 11:42 UTC, KIBORG04 commented on code/game/objects/effects/mines.dm
> +	if(istype(M, /mob/living))
Потому что это мины, которые активируются от какого-то веса на них. 
Тогда добавь активацию от сброшенного или кинутого на нее предмета

2020-08-23 18:20 UTC, TungstenOctopus requested changes
Увидев это, игрок скорее всего решит, что это какая-то игрушка из аркадного автомата, НЛО. На мины не особо похоже. И само исполнение спрайта плохое, не в стиле.

2020-10-03 15:18 UTC, closed without merging

2021-05-05 20:32 UTC, KIBORG04 commented on code/game/objects/items/mines.dm
> +/obj/item/mine
сделай компоненту, будет вообще пушка бомба класс 

> А если сделаешь компоненту реактивной взрывчатки, то минировать можно было бы абсолютно любой предмет и чтобы когда на него наступаешь бабах

2021-05-05 20:32 UTC, AndroBetel commented on code/game/objects/items/mines.dm
> +/obj/item/mine
не сделаю, я тупой =(

2021-05-05 20:33 UTC, KIBORG04 commented on code/game/objects/items/mines.dm
> +/obj/item/mine
фак, не там написал. Может и сделаю