На шейде и боге нельзя делать комбо
TauCetiStation/TauCetiClassic pull request #6017
Opened 2020-08-19 19:13 UTC by KIBORG04

## Описание изменений
На шейде и боге нельзя делать комбо
fix  #6016

## Почему и что этот ПР улучшит
Нельзя будет сделать апперкот нематериальной сущности

## Авторство
Я

## Чеинжлог
:cl:
 - bugfix: Теперь на шейде и божке нельзя делать комбо

2020-08-19 19:13 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2020-08-20 06:10 UTC, LudwigVonChesterfield commented
Мне кажется что это плохое решение, потому-что в любой момент могут появиться другие мобы проходящие сквозь стены(я смотрю в сторону шейдов, и врасов), которых можно было бы точно так же абузить

Мне кажется более корректным решением было бы поменять код перемещения в комбах так, чтобы или нельзя было применять комбу на враге который стоит в тайле на который ты не зайдешь(примерно такая проверка):
```
if(get_step(тот кто бьёт, get_dir(тот кто бьёт, тот кого бьют)) != тот кого бьют.loc)
```

Или вместо проверки ДО комбы во время комбы сделать что-то подобное(но лучше до)

2020-08-20 06:10 UTC, LudwigVonChesterfield requested changes
Комментарий выше

2020-08-20 06:21 UTC, KIBORG04 commented
Комбо это тогда, когда появляется белая фигня правее этого худа? Типо, нажать альтклик и происходит апперкот, это оно самое?

2020-08-20 06:51 UTC, 4310V343k commented
Да

2020-08-24 12:38 UTC, LudwigVonChesterfield commented on code/modules/unarmed_combat/combat_combo.dm
> +	if(!CS.victim.loc.CanPass(CS.attacker, get_step(CS.attacker, get_dir(CS.attacker, CS.victim))))
Думаю это стоит проверять только если heavy_animation

Дизарм, пуш, и любые другие комбы которые не требуют перемещаться на соседний тайл вероятно не требуют

(хотя с другой стороны, "захват" к примеру перемещает тебя на соседний тайл, но не с помощью forceMove-а, так что возможно проблема в использовании его)

2020-08-24 13:01 UTC, merged