Новые текстуры фонариков
TauCetiStation/TauCetiClassic pull request #6066
Opened 2020-09-06 08:42 UTC by PhenyaMomota

## Описание изменений
Изменение текстур фонариков в lighting.dmi
## Почему и что этот ПР улучшит
Улучшает(?) вид текстур фонариков и делает более современными.
## Авторство
@PhenyaMomota
## Чеинжлог
Изменение текстур :
![Screenshot_14](https://user-images.githubusercontent.com/62373791/92321863-1043cb00-f036-11ea-814d-e760265bb841.png)

2020-09-06 08:43 UTC, TauKitty commented
###### Changelog status: :radio_button: No changelog

2020-09-06 08:56 UTC, PhenyaMomota commented
Фикс обрывающегося света :
![Screenshot_16](https://user-images.githubusercontent.com/62373791/92322108-f60aec80-f037-11ea-8829-7fbfac28ef4d.png)

2020-09-06 09:40 UTC, FelixRuin commented
![image](https://user-images.githubusercontent.com/31424899/92323033-03c37080-f03e-11ea-9a48-6b3f09764fab.png)

да-да, я понимаю, стелсо изменения, но не до такой-же степени

2020-09-06 09:46 UTC, FelixRuin commented
> ## Чеинжлог
> Изменение текстур :
> ![Screenshot_14](https://user-images.githubusercontent.com/62373791/92321863-1043cb00-f036-11ea-814d-e760265bb841.png)

https://wiki.taucetistation.org/Git/GitHub, если кратко

## Чеинжлог
:cl:
- image: изменение боевого и обычного фонарика

А ещё тебе не кажется, что палитра фонариков... будто просто наложили серый слой на всю текстуру

2020-09-06 12:42 UTC, PhenyaMomota commented
## Чеинжлог
Фикс вечно-включённых фонариков :
![изображение](https://user-images.githubusercontent.com/62373791/92325972-58bfb080-f057-11ea-96ef-d254a1ae373e.png) ![изображение](https://user-images.githubusercontent.com/62373791/92325976-5c533780-f057-11ea-85e1-230c9cbf72db.png)

Улучшение спрайтов :
![изображение](https://user-images.githubusercontent.com/62373791/92325981-6c6b1700-f057-11ea-94b0-2d4d288f7260.png) ![изображение](https://user-images.githubusercontent.com/62373791/92325984-72f98e80-f057-11ea-8c08-3470305156e9.png)

2020-09-06 12:47 UTC, FelixRuin commented
давай, ты сможешь, нажми на эту кнопку, давай 
![image](https://user-images.githubusercontent.com/31424899/92326086-2ebabe00-f058-11ea-9cc4-a332c7a709c9.png)

в комментарии к пру заходить за тем, чтоб понять, что изменилось не есть гуд

2020-09-06 12:50 UTC, cool20141 commented
Можешь старые спрайты приложить к новым, чтоб можно было сравнить?

2020-09-07 08:24 UTC, TungstenOctopus commented
Секлайт новый выглядит неплохо, а синий фонарь совсем никакой, плоский и странной формы

2020-09-13 07:44 UTC, TungstenOctopus requested changes
Отписался неделю назад выше :)

2020-09-20 11:07 UTC, ArmolitskiyCarpoeb commented
бери палитру эриса и перерисовывай фонарики, станет лучше

2020-09-20 11:59 UTC, cool20141 commented
Учитывая, что у нас почти много вещей в палитре ~~эриса~~ ватлера, и правда стоит переделать, чтоб гармонировало как-то, не выбивалось из общей картины

2020-10-31 04:33 UTC, closed without merging