добавляет хосу личную пушку
TauCetiStation/TauCetiClassic pull request #6113
Opened 2020-09-15 14:20 UTC by AndroBetel

## Описание изменений
хос получает особенный еган могущий стрелять не только лазером и тазером, но и слабыми ионными разрядами которые не бьют сплешом. спавнится только вместе с хосом, и использоваться же может только им.

![image](https://user-images.githubusercontent.com/44546836/93222506-b2bb2700-f777-11ea-81da-b39ccfb52111.png)

## Почему и что этот ПР улучшит
хос чувствовался самым обделенным из глав по наличию крутых личных вещей (кроме хопа но), а складной щит слишком ситуативная штука, посему это хорошо. а ещё больше пушек это круто.
## Авторство
спрайты с ериса с изменениями.
## Чеинжлог
:cl:
- rscadd: Добавляет особое личное оружие ХоСу.

2020-09-15 14:20 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2020-09-15 14:22 UTC, AndroBetel commented
я не знаю почему но гитхаб пердолит картинки что особенно заметно на красном и синем режимах

2020-09-15 14:35 UTC, T6751 commented
> я не знаю почему но гитхаб пердолит картинки что особенно заметно на красном и синем режимах

как вариант, можно выложить на imgur

2020-09-15 15:09 UTC, UDaV73rus commented
Работает ли он на шлюзы и створки всякие как ионка?

2020-09-15 15:10 UTC, AndroBetel commented
да

2020-09-15 15:12 UTC, UDaV73rus commented
Спорный баланс выходит :\

2020-09-15 15:14 UTC, AndroBetel commented
нет

2020-09-15 15:22 UTC, 4310V343k commented
В натуральную величину
https://camo.githubusercontent.com/a34ed7284106b4637f9dfe80944bace663dcdff5/68747470733a2f2f6964622e616666656374656461726330372e636f2e756b2f46696c65732f35353837303434322f313131383133393331342f33312f61667465722e706e67
https://camo.githubusercontent.com/6459d862597fb78417f427a0e7965d88e8279cb0/68747470733a2f2f6964622e616666656374656461726330372e636f2e756b2f46696c65732f35353837303434322f313131383133393331342f33362f61667465722e706e67
https://camo.githubusercontent.com/d598137736dac833c27c6aa09dd47426d3accf5c/68747470733a2f2f6964622e616666656374656461726330372e636f2e756b2f46696c65732f35353837303434322f313131383133393331342f34312f61667465722e706e67

2020-09-15 15:51 UTC, T6751 commented on code/modules/projectiles/guns/energy.dm
> -			select = pos_selections[choice]
А как это касается добавления новой пушки?
И думаю, можно было хотя бы мельком в описании об этом упомянуть, что теперь не будет инпутов при переключении типов снарядов, где таких больше двух.

2020-09-15 15:54 UTC, AndroBetel commented on code/modules/projectiles/guns/energy.dm
> -			select = pos_selections[choice]
я не знаю, когда именно добавили то, что нужно выбирать инпутом, но в бою это МАКСИМАЛЬНО неудобно, когда тебе в лицо при попытке переключить пушку выскакивает огромное окошко, заставляющее персонажа замереть на месте

2020-09-15 15:57 UTC, T6751 commented on code/modules/projectiles/guns/energy.dm
> -			select = pos_selections[choice]
(вот бы радиалку здесь, наверное)
Но так, да, я понимаю, что инпут не удобен в данном плане
Просто в описании упомянуть бы об этом.

2020-09-15 15:58 UTC, AndroBetel commented on code/modules/projectiles/guns/energy.dm
> -			select = pos_selections[choice]
радиалка тоже не удобно - придётся дергать мышкой туда-сюда и попадать по этим небольшим кнопочкам.

2020-09-15 15:58 UTC, AndroBetel commented on code/modules/projectiles/guns/energy.dm
> -			select = pos_selections[choice]
а так done.

2020-09-15 15:58 UTC, CeUvi commented on code/modules/projectiles/guns/energy.dm
> -			select = pos_selections[choice]
радиалка тоже неудобно очень, тебе надо с цели перевести курсор на себя, выбрать режим и снова навестись на цель.

2020-09-15 15:59 UTC, T6751 commented on code/modules/projectiles/guns/energy.dm
> +	if(ammo_type.len >= 2)
Эта проверка всегда истинна
в 63-ей строке уже проверка ```if(ammo_type.len <= 1)```, которая, так сказать, говорит, что в случае её невыполнения уже определенно точно снарядов больше либо равно 2

2020-09-15 16:00 UTC, AndroBetel commented on code/modules/projectiles/guns/energy.dm
> +	if(ammo_type.len >= 2)
просто выпилить эту проверку?

2020-09-15 16:01 UTC, 4310V343k commented on code/modules/projectiles/guns/energy.dm
> +	if(ammo_type.len >= 2)
Добавлено было для пирометров, так как в универсальном пирометре больше двух режимов стрельбы (хотя по сути они все одинаковые). Лудук, видимо, не предсказывал возможность появления пушек, у которых 3+ режимов стрельбы

2020-09-15 16:02 UTC, 4310V343k commented on code/modules/projectiles/guns/energy.dm
> +	if(ammo_type.len >= 2)
https://github.com/TauCetiStation/TauCetiClassic/pull/4626/files#diff-55f8432b4eac76b82323ca5b6da7db8f

2020-09-15 16:06 UTC, T6751 commented on code/modules/projectiles/guns/energy.dm
> +	if(ammo_type.len >= 2)
> просто выпилить эту проверку?

да

2020-09-15 16:28 UTC, cool20141 commented
> хос чувствовался самым обделенным из глав по наличию крутых личных вещей (кроме хопа но), а складной щит слишком ситуативная штука, посему это хорошо. а ещё больше пушек это круто.

Супер-пупер броня спецназовца и личный риг, а что такого крутого у других глав?

2020-09-15 16:33 UTC, volas commented on code/modules/projectiles/guns/energy.dm
> +		select = 1
чисто технически, правильнее было бы сначала сравнивать с len, а уже потом шифтить

2020-09-15 16:35 UTC, volas commented on code/modules/projectiles/guns/energy/nuclear.dm
> +		return 0
хз, у нас нету проверок на роль сейчас нигде и ввод подобного не обсуждался (тут есть свои тонкости, тот же хоп), тут в качестве побочной фичи мне кажется это лишне.

2020-09-15 16:37 UTC, volas commented on code/datums/outfits/jobs/security.dm
> +	belt = /obj/item/weapon/gun/energy/gun/hos
И еще касательно хопа, если ХоС не с начала раунда - он не сможет получить пушку? Тоже можно обсудить/подумать, может стоит в шкаф закинуть. Где у него уже все бонусные вещи лежат.

2020-09-15 16:38 UTC, volas commented
@TauCetiStation/sprites-department

Еще следует чеинжлог более подробно описать. Упомянуть третий режим было бы достаточно.
> Добавляет особое личное оружие ХоСу.

2020-09-15 16:42 UTC, AndroBetel commented on code/datums/outfits/jobs/security.dm
> +	belt = /obj/item/weapon/gun/energy/gun/hos
я хочу как-то предотвратить то, что всякая тритота и офицерены с полным доступом лутали и использовали это супероружия, тем самым его забалансив. так что мне бы хотелось хотя бы либо проверку на роль оставить, либо давать его только хосу как предмет с которым он спавнится.

2020-09-15 16:48 UTC, volas commented on code/datums/outfits/jobs/security.dm
> +	belt = /obj/item/weapon/gun/energy/gun/hos
Если от того что его залутают случится что-то страшное, то это вопрос баланса в целом, может тогда и хос-у оно не нужно. 
Но я думаю тут не тот случай, так понимаю тут отличие только в новом режиме? Так что ничего страшного. В кабинет пробраться не легко. А еще можно кучу других пушек в бриге налутать, если уж забрался. И ионки тоже.

2020-09-15 16:50 UTC, AndroBetel commented on code/datums/outfits/jobs/security.dm
> +	belt = /obj/item/weapon/gun/energy/gun/hos
ладно.....

2020-09-15 21:45 UTC, KIBORG04 commented on code/modules/projectiles/guns/energy.dm
> -			select = pos_selections[choice]
> радиалка тоже неудобно очень, тебе надо с цели перевести курсор на себя, выбрать режим и снова навестись на цель.

Ну, что бы вызвать эту радиалку/лист нужно нажать по пушке раз, а значит уже мышка не на цели

2020-09-16 04:56 UTC, TungstenOctopus approved these changes

2020-09-16 10:10 UTC, AndroBetel commented
все сделано

2020-09-16 17:03 UTC, Akellazp commented
Хос стал еще более ультимативной имбой

2020-09-16 17:08 UTC, AndroBetel commented
да нифига он не имба то что дураки просто прут напролом пытаясь его расстрелять из пукалок и лазерок не означает что его невозможно завалить

2020-09-17 11:26 UTC, GoodGrief1488 commented
> > хос чувствовался самым обделенным из глав по наличию крутых личных вещей (кроме хопа но), а складной щит слишком ситуативная штука, посему это хорошо. а ещё больше пушек это круто.
> 
> Супер-пупер броня спецназовца и личный риг, а что такого крутого у других глав?

Ваншотающий гираспрей у СМО и... все? У СЕ РЦД, доступный любому грузчику и ресерч асистенту, у РД ничего уникального, у ГП ничего уникального, у капитана антикварный лазер, который нельзя брать. Предлагаю всем дать по пушке, подчеркивающей их сферу специализации. СЕ дать пушку дистанционно ремонтирующую турели и боргов, ГП стреляющую деньгами со счета станции, капитану - имплантирующую лояльностью. А РД дать по шапке за павергейм и ролькохант.

2020-09-17 11:29 UTC, AndroBetel commented
согласен мне нравится делай.

2020-09-20 11:03 UTC, ArmolitskiyCarpoeb commented
тупо огоньки приделал к спрайту декарда с эриса, мда

2020-09-21 16:44 UTC, AndroBetel commented
hello merge

2020-09-21 18:49 UTC, T6751 requested changes

2020-09-21 18:49 UTC, T6751 commented on code/modules/projectiles/guns/energy.dm
> +	select++
1-ый вариант никогда не выбрался бы
```suggestion
	select++
	if(select > ammo_type.len)
		select = 1
```

2020-09-21 18:57 UTC, AndroBetel commented on code/modules/projectiles/guns/energy.dm
> +	select++
почему мне волас говорит что нужно как у меня щас а ты так?

2020-09-21 19:02 UTC, T6751 approved these changes

2020-09-27 11:09 UTC, merged

2020-09-29 10:57 UTC, ArmolitskiyCarpoeb commented
рукоятку хотя бы перекрасил в чёрный, типа полимеры, все дела... замёржили, и так сойдёт)))