Фикс аиралярма
TauCetiStation/TauCetiClassic pull request #6161
Opened 2020-09-26 17:43 UTC by 4310V343k

## Описание изменений
Раньше нельзя было изменить настройки аиралярма в клоунской. Теперь - можно
## Почему и что этот ПР улучшит
Да
## Авторство
remindme
## Чеинжлог
:cl: Remindme
 - bugfix: На гамме в клоунской нельзя было менять настройки Air Alarm'а

2020-09-26 17:43 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2020-09-26 19:38 UTC, 4310V343k commented
НУ почему.. почему оно просто не может заработать..

2020-09-27 09:12 UTC, T6751 requested changes

2020-09-27 09:17 UTC, 4310V343k commented on maps/gamma/gamma.dmm
> -	frequency = 1600;
Я посмотрел все инстансы на гамме - 1600 больше нигде не нашёл. Или меня наибал SDMM, в чём я сомневаюсь

2020-09-27 09:18 UTC, 4310V343k commented on maps/gamma/gamma.dmm
> -	frequency = 1600;
Ладно, меня наебали, сейчас починю

2020-09-27 10:27 UTC, T6751 approved these changes

2020-09-27 10:44 UTC, merged