TGUI Ports
TauCetiStation/TauCetiClassic pull request #6207
Opened 2020-10-07 15:16 UTC by AirBlack

## Описание изменений
Портирует некоторые интерфейсы с ТГ, а именно провода, канистры, баки, портативные помпы, скрабберы
<details> 
  <summary>Скриншоты того, что готово</summary>

![image](https://user-images.githubusercontent.com/5171605/95349971-7778c780-08e1-11eb-9f12-e0ca86697d1d.png)
![image](https://user-images.githubusercontent.com/5171605/95350018-865f7a00-08e1-11eb-9458-4a6b69cc17df.png)
(тут фича с очками и цветами проводов, мусор внизу игнорируйте)

![image](https://user-images.githubusercontent.com/5171605/95350070-99724a00-08e1-11eb-90c2-dc53f731ad63.png)
![image](https://user-images.githubusercontent.com/5171605/95350091-9d9e6780-08e1-11eb-97b1-9d3968c2016a.png)
![image](https://user-images.githubusercontent.com/5171605/95350126-a68f3900-08e1-11eb-8022-b63731f9a05e.png)

</details>

Еще тут мелкофича которая добавляет звук мультитулу и кусачкам когда с проводками работаешь, пока нормальный звук не найду на мультитул, будет бип из какого-то из таймеров
## Почему и что этот ПР улучшит
Красиво и иногда удобней
## Авторство
AirBlack - порт
щас тут навставляю ПРов с гита тгстатион
## Чеинжлог
:cl: AirBlack
 - tweak: Порт некоторых интерфейсов на TGUI

2020-10-07 15:16 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2020-10-07 15:18 UTC, KIBORG04 commented
Аплинк, покупка способностей перевертышем

2020-10-07 15:30 UTC, AirBlack commented
покупка способностей перевертышем?

2020-10-07 15:31 UTC, KIBORG04 commented
Ну когда генокрад жмеь кнопку Еволюшен Меню

2020-10-08 13:52 UTC, T6751 commented on code/modules/atmospheric/machinery/portable/pump.dm
> -		ui = new(user, src, ui_key, "portpump.tmpl", "Portable Pump", 480, 410)
не забудь удалить неиспользуемые .tmpl

2020-10-09 12:02 UTC, Pivo24 commented
Что за регулятор у канистр, я заинтригован

2020-10-09 12:14 UTC, AirBlack commented
Один из дефолтных элементов либо реакта либо самого тгуи, точно не знаю, но знаю, что там куча всяких дефолтных приколов плюс можно самому их писать, например в скраббере и помпе используется общий элемент содержащий в себе информацию о баке и о батарейке, прикольная штука короче

2020-10-17 16:51 UTC, LudwigVonChesterfield commented on code/datums/wires/airlock.dm
> +	. += "[A.locked ? "The door bolts have fallen!" : "The door bolts look up."]"
только сейчас задумался. а что вообще должна значить фраза "The door bolts look up" болты смотрят вверх, чего?

2020-10-17 17:00 UTC, AirBlack commented on code/datums/wires/airlock.dm
> +	. += "[A.locked ? "The door bolts have fallen!" : "The door bolts look up."]"
выглядят поднятыми наверное

2020-10-18 14:35 UTC, T6751 requested changes
для Black и Navy проводов нужен цвет посветлее. Иначе напрягаются глаза, если хотеть прочитать, что написано
![image](https://user-images.githubusercontent.com/66636084/96370886-11edcc00-1168-11eb-9ff6-df5540d3ce6f.png)

2020-10-18 14:35 UTC, T6751 commented on code/datums/wires/_wires.dm
> +
```suggestion

```

2020-10-18 14:35 UTC, T6751 commented on code/datums/wires/_wires.dm
> +
```suggestion

```

2020-10-18 14:35 UTC, T6751 commented on code/modules/atmospheric/machinery/portable/canister.dm
> +	update_icon()
```suggestion
	update_icon()

```

2020-10-18 14:35 UTC, T6751 commented on code/modules/atmospheric/machinery/portable/pump.dm
> +	update_icon()
```suggestion
	update_icon()

```

2020-10-18 15:04 UTC, KIBORG04 commented
> для Black и Navy проводов нужен цвет посветлее. Иначе напрягаются глаза, если хотеть прочитать, что написано
> ![image](https://user-images.githubusercontent.com/66636084/96370886-11edcc00-1168-11eb-9ff6-df5540d3ce6f.png)

А это вообще можно пофиксить? Там используется обычный блек хтмлевский

2020-10-18 15:09 UTC, T6751 commented
> А это вообще можно пофиксить? Там используется обычный блек хтмлевский

Тогда думаю лучше заменить цвета. Например на white, silver

2020-10-18 15:12 UTC, KIBORG04 commented
> > А это вообще можно пофиксить? Там используется обычный блек хтмлевский
> 
> Тогда думаю лучше заменить цвета в самих проводах. Например на white, silver

Если автор так будет делать, то, поидее, мой механ все еще будет работать, но советую в какой-то лист добавить больше цветов ХТМЛовских

2020-10-18 18:08 UTC, AirBlack commented
![image](https://user-images.githubusercontent.com/5171605/96376080-b8ed5a80-119e-11eb-92c2-3de7b5aed6ec.png)

2020-10-18 18:11 UTC, AirBlack commented
> > > А это вообще можно пофиксить? Там используется обычный блек хтмлевский
> > 
> > 
> > Тогда думаю лучше заменить цвета в самих проводах. Например на white, silver
> 
> Если автор так будет делать, то, поидее, мой механ все еще будет работать, но советую в какой-то лист добавить больше цветов ХТМЛовских

Если навставлять разных оттенков цветов, то они будут путаться визуально

2020-10-18 18:29 UTC, T6751 commented on code/modules/atmospheric/machinery/portable/pump.dm
> +#define PUMP_DEFAULT_PRESSURE (ONE_ATMOSPHERE)
В конце файла
```dm
#undef PUMP_MAX_PRESSURE
#undef PUMP_MIN_PRESSURE
#undef PUMP_DEFAULT_PRESSURE
```

2020-10-18 18:29 UTC, T6751 commented on code/modules/atmospheric/machinery/portable/scrubber.dm
> +#define SCRUBBER_DEFAULT_RATE 800
```dm
#undef SCRUBBER_MAX_RATE
#undef SCRUBBER_MIN_RATE
#undef SCRUBBER_DEFAULT_RATE
```

2020-10-18 18:29 UTC, T6751 commented on code/modules/atmospheric/machinery/portable/canister.dm
> +#define CAN_DEFAULT_RELEASE_PRESSURE 	(ONE_ATMOSPHERE)
В конце файла:
```dm
#undef CAN_DEFAULT_RELEASE_PRESSURE
```

2020-10-18 18:29 UTC, T6751 commented on code/game/objects/items/weapons/tanks/tanks.dm
>  #define TANK_DEFAULT_RELEASE_PRESSURE 24
В конце файла через #undef стоит убирать дефайны, так как больше нигде не используются

```dm
#undef TANK_MIN_RELEASE_PRESSURE
#undef TANK_MAX_RELEASE_PRESSURE
#undef TANK_DEFAULT_RELEASE_PRESSURE
```

2020-10-19 18:41 UTC, AirBlack commented on code/datums/wires/airlock.dm
> +	. += "[A.locked ? "The door bolts have fallen!" : "The door bolts look up."]"
мне нажимать ресолве?

2020-10-23 17:05 UTC, T6751 approved these changes

2020-10-24 15:21 UTC, AirBlack commented
Ну как там с тест мержем?

2020-10-25 10:37 UTC, SpaiR commented
Конфликты

2020-10-25 12:06 UTC, AirBlack commented
Упс я случайно с телефона, приложение гитхаба неудобное

2020-10-25 14:35 UTC, Kortez90 commented
Кнопка `close` из окна голосования конца раунда пропала? Или ее там не было никогда?

2020-10-25 15:08 UTC, T6751 commented
> 
> 
> Кнопка `close` из окна голосования конца раунда пропала? Или ее там не было никогда?

Это изменение из этого ПРа https://github.com/TauCetiStation/TauCetiClassic/pull/5990
Вместо close должен быть крестик вверху справа

2020-10-25 15:35 UTC, Kortez90 commented
> Вместо close должен быть крестик вверху справа

Неудобно. Лучше либо вернуть кнопку, либо добавить возможность закрывать через `esc`.

2020-10-25 16:30 UTC, AirBlack commented
бляятяь
сука

2020-10-30 18:46 UTC, merged