Предупреждения о разрядке батарейки холодильника для IPC.
TauCetiStation/TauCetiClassic pull request #6211
Opened 2020-10-09 11:54 UTC by Kortez90

## Описание изменений
Посылает в чат сообщение и звук, когда заряд батарейки ниже 10%.
## Почему и что этот ПР улучшит
Исправляет бесшумное выключение холодильника.
## Авторство

## Чеинжлог
:cl: Kortez90
 - tweak: Предупреждение о разрядке cooling_unit.

2020-10-09 11:55 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2020-10-09 12:11 UTC, KIBORG04 commented
Может быть лучше выводить на ипц такое же состояние батарейки, как и у боргов?

2020-10-09 13:18 UTC, LudwigVonChesterfield commented on code/game/objects/items/devices/suit_cooling.dm
> +		warn = TRUE
Если вдруг у нас появятся зарядники, чтобы не надо было доставать батарею чтобы заряжать(как у еганов), тут будет проблема с тем, что если зарядить через него - предупреждение больше не выдастся.

Думаю стоит использовать не warn как флаг предупреждения, а записать при каком уровне пришло предупреждение, и тогда оно не будет предупреждать если уровеь < чем тот. при котором предупреждение было.

ИЛИ сделать чтобы warn = FALSE так же происходило при зарядке батарейки(это уже пахнет сигналами)

2020-10-09 14:14 UTC, Kortez90 commented on code/game/objects/items/devices/suit_cooling.dm
> +		warn = TRUE
Я уже пострадал с этим флагом и это решение было вынужденным. Нужно вообще без него обойтись. Триггер вешать просто некуда, чтобы он по кругу не вызывался. Но попробую...

2020-10-10 15:22 UTC, LudwigVonChesterfield commented on code/game/objects/items/devices/suit_cooling.dm
> +		warn = TRUE
Ты похоже не очень понял моё предложение, потому-что по сути сейчас абсолютно ничего не изменилось.

Я предложил записывать заряд при котором было сообщение, и если текущий заряд меньше чем записанный - заново сообщение не отправлять. Но если заряда вдруг стало больше чем было записано, и нужно отправить сообщение - отправлять(Потому-что такой случай означал бы что батарейка была заряжена.)

2020-10-10 15:25 UTC, Kortez90 commented on code/game/objects/items/devices/suit_cooling.dm
> +		warn = TRUE
Сейчас все так и работает. Если заряд батарейки ниже 10%, то включается флаг и значение заряда записывается. Когда заряд становится выше записанного, то флаг выключается. Что не так?

2020-10-12 17:00 UTC, LudwigVonChesterfield commented on code/game/objects/items/devices/suit_cooling.dm
> +		warn = TRUE
Пожалуйста, не резолвь мои комментарии сам.

Сейчас всё работает точно так же как у тебя до этого, только вместо TRUE/FALSE у тебя *размер заряда*/0.

Я же предлагал сделать что-то типо

```
if(cell.charge <= cell.maxcharge * 0.1 && cell.charge < last_warned_charge)
    предупреждение
    last_warned_charge = cell.charge
```

2020-10-12 17:12 UTC, Kortez90 commented on code/game/objects/items/devices/suit_cooling.dm
> +		warn = TRUE
Зачем? Это тоже самое. Можно даже условие флага перевести на `else` и разницы не будет. Батарейка при заряде дернет флаг и когда разрядится, то флаг снова переключится. Шило на мыло и несуществующие зарядники превентивно не ломают предупреждение.

2020-10-12 17:29 UTC, LudwigVonChesterfield commented on code/game/objects/items/devices/suit_cooling.dm
> +		warn = TRUE
Зачем ты в warn хранишь заряд?

2020-10-12 17:55 UTC, Kortez90 commented on code/game/objects/items/devices/suit_cooling.dm
> +		warn = TRUE
Чтобы его проверить позже.
Я заметил, что ты хочешь убрать лишнюю переменную, но во-первых, я не уверен что она лишняя, так как только что прогонял твой код и при использовании двух разных батарей заряд не выдавался. А в-вторых, мне интересна мотивация такого рвения из-за переменной, с которой все прекрасно работает.

2020-10-12 17:56 UTC, LudwigVonChesterfield commented on code/game/objects/items/devices/suit_cooling.dm
> +		warn = TRUE
Где ты используешь количество, записанное в warn не на уровне проверки того что оно не 0? Если бы ты туда записывал не точное кол-во заряда, а единицу - что-то бы поменялось?

2020-10-12 18:04 UTC, Kortez90 commented on code/game/objects/items/devices/suit_cooling.dm
> +		warn = TRUE
В том и смысл. Твой вариант делает (но пока что, почему-то, не делает) тоже самое, сравнивая записанный заряд с существующим.

2020-10-12 18:08 UTC, Kortez90 commented on code/game/objects/items/devices/suit_cooling.dm
> +		warn = TRUE
Только что проверил еще раз.
Если вставить батарейку на 1к, разрядить до нуля и получить уведомление, а потом сунуть батарейку на 10к и разрядить, то уведомление придет при ~0%.

2020-10-12 18:35 UTC, Kortez90 commented on code/game/objects/items/devices/suit_cooling.dm
> +		warn = TRUE
Ну да. В варианте без флага используя батарейку на 1к мы получаем 200 в переменной. Проверку `cell.charge <= cell.maxcharge * 0.1` она не прошла. А если вставить на батарейку 10к, то `cell.charge < last_warned_charge` будет 10000 < 200 и сообщение выведется только после 200, а это уже не 10%.

2020-10-13 10:48 UTC, SpaiR requested changes

2020-10-13 10:48 UTC, SpaiR commented on code/game/objects/items/devices/suit_cooling.dm
> +	var/warn = 0
По названию переменной абсолютно нельзя понять для чего она используется.

2020-10-13 10:48 UTC, SpaiR commented on code/game/objects/items/devices/suit_cooling.dm
> +	if(cell.charge <= cell.maxcharge*0.1 && warn <= 0)
Выше есть `if`, который делает `turn_off()` при отсутствии заряда. Поэтому располагать логику в этом месте не совсем корректно. Также, имеет смысл все это вынести в какой-то метод.

2020-10-13 11:07 UTC, Kortez90 commented on code/game/objects/items/devices/suit_cooling.dm
> +	if(cell.charge <= cell.maxcharge*0.1 && warn <= 0)
Как раз выносить это в отдельный прок смысла нет, так как условия так или иначе останутся в процессинге, а в прок уйдет только `to_chat`, `playsound `и присвоение флагу заряда. Итого мы получим ненужный прок и лишнее объявление "`if(ishuman(loc)) var/mob/living/carbon/human/H = loc`". Каким образом прок выключения влияет на обработку условий выдачи предупреждения - тоже загадка. Ясное дело, что это проверяется по порядку, но при нулевом заряде холодильник просто переключит себе переменную `on`. Что не так с местом, если проверки предупреждения даже не проверяют состояние этой переменной? (Надо бы исправить, кстати.)
В общем, нужны более подробные данные.

2020-10-13 12:23 UTC, SpaiR commented on code/game/objects/items/devices/suit_cooling.dm
> +	if(cell.charge <= cell.maxcharge*0.1 && warn <= 0)
В отдельный прок выносится кусок кода https://github.com/TauCetiStation/TauCetiClassic/pull/6211/files#diff-b83254a4b0485c277cfb1cda01d9bc23b372212bef088f5d716135dd537f448bR63-R68 и вместо того, чтобы в `process()` прописывать не совсем явные ифы у тебя будет вызываться этот метод. У метода будет понятное название о то, что внутри него происходит и код станет более читабельным и самодокументируемым. Практическая польза одна - упросить понимание кода.

> Каким образом прок выключения влияет на обработку условий выдачи предупреждения - тоже загадка.

Ответ на эту "загадку" заключается в логической последовательности того, что у тебя в коде происходит. Зачем сообщать пользователю о том, что у него осталось меньше 10%, если кулер выключился? И наоборот.

2020-10-13 12:27 UTC, SpaiR commented on code/game/objects/items/devices/suit_cooling.dm
> +	var/charge_warning = 0
Все еще непонятно. Если у тебя переменная содержит количество заряда, то так и пиши. А так это все еще какое-то "предупреждение о зарядке".

На самом деле, если логика переменной в том, чтобы предупреждение было лишь один раз, то проще тогда заменить на TRUE/FALSE. С названием тогда тоже все просто будет

2020-10-13 12:32 UTC, Kortez90 commented on code/game/objects/items/devices/suit_cooling.dm
> +	var/charge_warning = 0
Тут все не так просто. Лудук хотел, чтобы флаг работал от заряда батареи, чтобы несуществующие зарядники холодильников могли не ломать предупреждение, если бы заряжали холодильники не извлекая батараейку. Я сделал его хотелку, но есть тонкость. Просто true/false тут не будет работать, так как нужно именно кол-во заряда, которое сравнивается с 10% максимального заряда вставленной батарейки и предупреждение будет работать всегда, даже если сунуть батарейку помощнее.
Название переменной дело вкуса  Лично мне до лампочки, как она будет называться. Предлагай сразу вариант, а то мы тут до следующего месяца будем комменты разводить.

2020-10-13 12:33 UTC, LudwigVonChesterfield commented on code/game/objects/items/devices/suit_cooling.dm
> +	var/charge_warning = 0
Не оправдывайся мной, после того как не понял моё предложение, спорил со мной когда я говорил что ты не понял моё предложение, ничего не попытался поменять/понять.

2020-10-13 12:34 UTC, LudwigVonChesterfield commented on code/game/objects/items/devices/suit_cooling.dm
> +	var/charge_warning = 0
Текущий вариант работал бы и если бы ты просто держал TRUE/FALSE, потому-что конкретный заряд нигде не используется, и нигде не мог бы адекватно использоваться(Учитывая что почему-то как только заряд > 10% то в переменной сохраняется значение 0)

2020-10-13 12:35 UTC, SpaiR commented on code/game/objects/items/devices/suit_cooling.dm
> +	var/charge_warning = 0
> Просто true/false тут не будет работать, так как нужно именно кол-во заряда, которое сравнивается с 10% максимального заряда вставленной батарейки и предупреждение будет работать всегда, даже если сунуть батарейку помощнее.

Я не знаю чья тут хотелка реализуется, но вот, что я вижу
![image](https://user-images.githubusercontent.com/12721311/95861084-9f48af00-0d69-11eb-8ed0-157e4d7b7bb4.png)
Переменная `charge_warning` явно используется как true/false флаг. Я не понимаю зачем там хранить заряд батареи.

2020-10-13 12:37 UTC, Kortez90 commented on code/game/objects/items/devices/suit_cooling.dm
> +	if(cell.charge <= cell.maxcharge*0.1 && warn <= 0)
Весь этот кусок туда сунуть нельзя, так как там две проверки, которые нельзя друг от друга отделять. Они должны проверяться поочередно, иначе это вызовет повторный вызов и переключение флага.

Нет, если желание вынести в отдельный прок три строчки, то никаких проблем. Проверки все равно останутся в процессинге. Даже если вынести их в два или один отдельный прок, вызываться он или они так или иначе будут через процессинг.

Сообщения и не будет, когда `on = 0`, так как в этом случае заряд батарейки будет ниже 10% и флаг будет включен.

2020-10-13 12:47 UTC, Kortez90 commented on code/game/objects/items/devices/suit_cooling.dm
> +	var/charge_warning = 0
> 
> 
> Думаю стоит использовать не warn как флаг предупреждения, а записать при каком уровне пришло предупреждение, и тогда оно не будет предупреждать если уровеь < чем тот. при котором предупреждение было.

Вот поэтому. Вариант без флага нежизнеспособен.

2020-10-13 12:48 UTC, LudwigVonChesterfield commented on code/game/objects/items/devices/suit_cooling.dm
> +	var/charge_warning = 0
![image](https://user-images.githubusercontent.com/17705613/95862417-90fb9280-0d6b-11eb-9f91-3ea0ee98e407.png)

Вроде бы жизнеспособный вариант без флага.

2020-10-13 12:49 UTC, LudwigVonChesterfield commented on code/game/objects/items/devices/suit_cooling.dm
> +	var/charge_warning = 0
(но можно и флагом, правда тогда уж надо точно делать как флаг)

Меня смущало именно что ты не в одном месте этот флаг дёргаешь, а что в одном месте его устанавливаешь - вдругом месте его сбрасываешь, как сейчас - в принципе приемлимо пусть и костыльно(В процессинге регулярно сбрасывать флаг :shrug:) 

Идеальный вариант был бы именно сбрасывать-устанавливать флаг когда батарейка заряжается по сигналу из неё, но ты не захочешь говоря что это рефакторить надо.

2020-10-13 12:55 UTC, Kortez90 commented on code/game/objects/items/devices/suit_cooling.dm
> +	var/charge_warning = 0
> 
> 
> Вроде бы жизнеспособный вариант без флага.
https://github.com/TauCetiStation/TauCetiClassic/pull/6211#discussion_r503468576

>
>
>Идеальный вариант был бы именно сбрасывать-устанавливать флаг когда батарейка заряжается по сигналу из неё, >но ты не захочешь говоря что это рефакторить надо.
Так было изначально, только флаг переключался при извлечении батарейки.

2020-10-13 12:57 UTC, LudwigVonChesterfield commented on code/game/objects/items/devices/suit_cooling.dm
> +	var/charge_warning = 0
Только заряд батарейки может менять не только её извлечение, и как только бы это поменяли - ты был бы виноват и ответственен за любой баг, потому-что решил что сможешь предугадать все будущие сценарии(целый один) не делав обобщений.

2020-10-13 15:17 UTC, closed without merging