Имплант-худ меняется при извлекании импланта
TauCetiStation/TauCetiClassic pull request #6213
Opened 2020-10-10 10:50 UTC by KIBORG04

## Описание изменений
Имплант-худ меняется при извлекании импланта

#6210

## Почему и что этот ПР улучшит
Минус баг

## Авторство

## Чеинжлог

2020-10-10 10:50 UTC, TauKitty commented
###### Changelog status: :radio_button: No changelog

2020-10-10 15:19 UTC, LudwigVonChesterfield commented on code/modules/surgery/implant.dm
> +		target.sec_hud_set_implants()
Я думаю было бы лучше если бы обновлял имплант при установке/удалении, а не операция обновляла за имплант... (Тогда кстати можно было бы поубирать тут(или попробовать сделать так, чтобы поубирать) проверки на тип удаляемого объекта)

2020-10-10 15:26 UTC, KIBORG04 commented on code/modules/surgery/implant.dm
> +		target.sec_hud_set_implants()
При установке и так юзается отдельный прок. Но отдельного прока при доставании нету. Также в дестрое имплантов худы обновляются. Правда, я все равно возле КуДела имплантов поставил еще одно обновление..

2020-10-12 15:29 UTC, LudwigVonChesterfield commented on code/modules/surgery/implant.dm
> +		target.sec_hud_set_implants()
А почему нет отдельного прока при доставании?... И почему бы его не добавить, чтобы не плодить всю нужную логику доставания импланта каждый раз когда он достаётся?

2020-10-15 18:29 UTC, KIBORG04 commented on code/modules/surgery/implant.dm
> +		target.sec_hud_set_implants()
> А почему нет отдельного прока при доставании?... И почему бы его не добавить, чтобы не плодить всю нужную логику доставания импланта каждый раз когда он достаётся?

Вроде как, это используется только в операции. В других местам там как-то все спецефично работает. 

У нас есть вот такой прикол по вытаскиванию шрапнели из тела.
![image](https://user-images.githubusercontent.com/26389417/96171367-76711700-0f2d-11eb-8259-a7173e2c5fa6.png)

2020-10-28 20:04 UTC, SpaiR requested changes
Добавь, пожалуйста, чейнджлог, что такой-то баг был исправлен.

2020-11-24 17:52 UTC, SpaiR approved these changes

2020-12-07 09:18 UTC, merged