респрайт куртки парамедика добавление им шапок
TauCetiStation/TauCetiClassic pull request #6216
Opened 2020-10-12 15:07 UTC by AndroBetel

## Описание изменений
респрайт куртки парамедика чтобы подходило под фуелтанки
добавление берета и кепки
![unknown (1)](https://user-images.githubusercontent.com/44546836/95761910-a8784400-0cb5-11eb-8537-706931e4e9f3.png)
![unknown (2)](https://user-images.githubusercontent.com/44546836/95761949-b8902380-0cb5-11eb-94ad-b74f953ca77e.png)
![unknown (3)](https://user-images.githubusercontent.com/44546836/95761976-c2b22200-0cb5-11eb-8383-030e66951fa2.png)

## Почему и что этот ПР улучшит
замена спрайтов 2013 года
## Авторство
Sprites by @CeUvi 
## Чеинжлог
:cl:
- image: Респрайт куртки парамедика.
- rscadd: Добавление двух шапок для парамедика в шкаф с одеждой медбея.

2020-10-12 15:07 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2020-10-12 16:04 UTC, Zmey25 commented
Ярко-зеленая расцветка, чисто случайно, не для того, чтобы парамедика можно было определить издалека и быстро его пропустить?

2020-10-12 16:04 UTC, CeUvi commented
> Ярко-зеленая расцветка, чисто случайно, не для того, чтобы парамедика можно было определить издалека и быстро его пропустить?

говорил уже несколько раз, что людук и юлиан р думают, что это не так, поэтому кислотная жилетка is no more

2020-10-14 00:54 UTC, kiVts commented
Вся станция у нас в синих оттенках, Я бы сказал что это точно не медик, уж ближе что офицер мостика или какой-то коп штрафы на парковке выписывает, но и близко на парамедика не похоже

2020-10-15 08:07 UTC, Ambassadoing commented
>людук и юлиан р думают
Неправильно думают.
![www usnews](https://user-images.githubusercontent.com/48314394/96094878-90cbd600-0ed6-11eb-8fd6-fd6902c0fd04.jpg)

2020-10-15 08:22 UTC, CeUvi commented
> > людук и юлиан р думают
> 
> Неправильно думают.
> ![www usnews](https://user-images.githubusercontent.com/48314394/96094878-90cbd600-0ed6-11eb-8fd6-fd6902c0fd04.jpg)

светоомтражамтели на стамции замчем

2020-10-15 10:58 UTC, SvSvyat commented
> Неправильно думают.

Для срочной медпомощи обычно характерны красный (красный крест) и синий (синяя звезда) цвета. Даже на твоей картинке превалирующий цвет - синий, а светоотражающие элементы добавлены из-за того, что люди иногда смертны на улице и ночью в условиях плохой видимости, что для космической станции не очень актуально. 
То есть, парамедикам светоотражатели не нужны.

...Однако и старая униформа была нарисована так не из-за каких-то там светоотражателей (ну ведь не похоже нихера), а из-за того, что жёлто-зелёный - самые заметные для глаза цвета. То есть, она специально была вырвиглазной, чтобы медики были заметны сразу.

Если это было для того, чтоб парамедиков не прибил залётный маня-ревер, нервный сбуха или мудак-нюкер в разгар военных действий, то оно как-то не очень работает (а ещё риг обычный белый, ага), так что цепляться за старую вырвиглазную униформу не стоит - она со своими функциями справляется сомнительно. 

Но и респрайт чёт как-то нет. Невнятно, серо, бледно. Может, дело в штанах: у нас врачи скорой или фельдшеры носят синюю или красную (реже) униформу - именно униформу, а жалкую мелкую курточку, которая выглядит так, будто лысый школьник взял ту navy длинную куртку и обрезал её до жеппы. 
То есть, старая функция (заметность) пропала, а эстетики чёт как-то не прибавилось...

2020-10-15 12:16 UTC, LudwigVonChesterfield commented
> людук и юлиан критикуют спрайт в контексте космической станции 13 говоря что вырвиглазные жилетки на станции бесполезны
> > proceeds to show a picture of real life doctors
> > pepega victory royale

2020-10-19 04:37 UTC, Ayuska commented
> 
> 
> > Неправильно думают.
> 
> Для срочной медпомощи обычно характерны красный (красный крест) и синий (синяя звезда) цвета. Даже на твоей картинке превалирующий цвет - синий, а светоотражающие элементы добавлены из-за того, что люди иногда смертны на улице и ночью в условиях плохой видимости, что для космической станции не очень актуально.
> То есть, парамедикам светоотражатели не нужны.
> 
> ...Однако и старая униформа была нарисована так не из-за каких-то там светоотражателей (ну ведь не похоже нихера), а из-за того, что жёлто-зелёный - самый заметный для глаза цвет. То есть, она специально была вырвиглазной, чтобы медики были заметны сразу.
> 
> Если это было для того, чтоб парамедиков не прибил залётный маня-ревер, нервный сбуха или мудак-нюкер в разгар военных действий, то оно как-то не очень работает (а ещё риг обычный белый, ага), так что цепляться за старую вырвиглазную униформу не стоит - она со своими функциями справляется сомнительно.
> 
> Но и респрайт чёт как-то нет. Невнятно, серо, бледно. Может, дело в штанах: у нас врачи скорой или фельдшеры носят синюю или красную (реже) униформу - именно униформу, а жалкую мелкую курточку, которая выглядит так, будто лысый школьник взял ту navy длинную куртку и обрезал её до жеппы.
> То есть, старая функция (заметность) пропала, а эстетики чёт как-то не прибавилось...

Очень умело переплетена пассивная агрессия и попытка в конструктивную критику.

На счет самого ПРа, а не зловредных фигур. Вид сбоку дает ощущение, будто спрайт съехал на пиксель.
Касательно цветов, имхо, ярче сделать надо.
На спине можно красный крест или подобный высокозаметный символ влепить, большую часть времени парамедики повернуты спиной в экран, не знаю, как это выходит.

Можно взглянуть на форму EMT из реальной жизни.
![изображение](https://user-images.githubusercontent.com/41844545/96401766-f1138e00-11dc-11eb-862e-26a1e5045be9.png)
Так же можно взглянуть на примеры от художников:
![изображение](https://user-images.githubusercontent.com/41844545/96401816-199b8800-11dd-11eb-8aba-9af145221419.png)
Правда красиво? Мало красных оттенков не бывает.
Сайт: https://www.deviantart.com/handofmanos/art/EMS-Uniform-part-2-274854972


А вот снова классические варианты из реальной жизни:
![изображение](https://user-images.githubusercontent.com/41844545/96401976-78610180-11dd-11eb-9fae-d2afa0106f5a.png)
![изображение](https://user-images.githubusercontent.com/41844545/96401995-81ea6980-11dd-11eb-99ff-65bec7c88a4c.png)
Ну и если автор хочет именно голубые тона:
![изображение](https://user-images.githubusercontent.com/41844545/96402112-bf4ef700-11dd-11eb-911d-1ddbd7a720ac.png)
![изображение](https://user-images.githubusercontent.com/41844545/96402132-c8d85f00-11dd-11eb-8b27-9b73818a1211.png)

2020-10-21 07:38 UTC, TungstenOctopus requested changes
Сори за поздний ревью. Кто бы там что ни говорил про скрепы и кислотный цвет, он здесь не нужен. Сама идея хорошая, дизайн куртки норм, но претензии к исполнению:
Во1 зачем капюшон
во2 плечи на всех проекциях сделаны плохо по форме
в3 сбоку руки выглядят плохо

если автор будет переделывать, могу посоветовать глянуть на куртки м65, вдруг там удастся вдохновения набраться (украсть)

2020-11-07 17:08 UTC, AndroBetel commented
сеу ви апдейтнул свое детище прошу ревьев

![image](https://user-images.githubusercontent.com/44546836/98447325-fb1e1200-2134-11eb-8d26-35446863c311.png)

![image](https://user-images.githubusercontent.com/44546836/98447327-feb19900-2134-11eb-8e0f-56d0f753c3ae.png)

2020-11-12 08:41 UTC, TungstenOctopus approved these changes
Тяжело воспринимать куртку со старыми белыми ужасными штанами, но вроде нормально

2020-11-12 08:49 UTC, ViDLiathan commented
Мне вот нравится старый кислотный вариант, что поделать. Но и новый красивый.
У меня есть компромисс, как не выпилить старый и ввести новый.
Сделать подпрофу Emergency Physician и выдать новую курточку.

2020-11-12 15:30 UTC, T6751 commented on code/modules/clothing/head/beret.dm
> +	icon_state = "beret_fr"
```suggestion
	icon_state = "beret_fr"

```

2020-11-12 15:39 UTC, merged