Верб "rotate" для инъекторов топлива.
TauCetiStation/TauCetiClassic pull request #6219
Opened 2020-10-12 17:24 UTC by Kortez90

## Описание изменений
Добавляет верб кручения инъекторов.
## Почему и что этот ПР улучшит
Чиним отсутствие кручения инъекторов, так как они не наследуют код эмиттеров.
## Авторство

## Чеинжлог
:cl: Kortez90
 - tweak: Топливные инъекторы раста можно крутить через пкм.

2020-10-12 17:24 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2020-10-12 17:30 UTC, LudwigVonChesterfield commented on code/modules/power/fusion/fuel_assembly/fuel_injector.dm
> +	if (src.anchored || usr:stat)
Я бы предложил разбить эту проверку на две, потому-что не понятно почему игроку без сознания должно писать что инъектор прибит к полу.

Так же рекомендую использовать прок incapacitated() вместо stat, и не использовать оператор :

2020-10-12 17:30 UTC, LudwigVonChesterfield commented on code/modules/power/fusion/fuel_assembly/fuel_injector.dm
> +	src.dir = turn(src.dir, 90)
```suggestion
	dir = turn(dir, 90)
```

2020-10-12 17:32 UTC, LudwigVonChesterfield commented
Может лучшим решение было бы сделать тип

/obj/machinery/rotateable который бы имел это поведение?

Или! Бонусные очки - сделать компоненту /datum/component/rotateable которая бы навешивала-забирала бы этот верб, а так же крутила бы машинерию в других сценариях когда ей стоит крутиться(Возможно при попадании какого-то особого снаряда? Или тяжелого предмета? Или просто от удара?)

2020-10-12 17:44 UTC, Kortez90 commented
> 
> 
> Может лучшим решение было бы сделать тип
> 
> /obj/machinery/rotateable который бы имел это поведение?
> 
> Или! Бонусные очки - сделать компоненту /datum/component/rotateable которая бы навешивала-забирала бы этот верб, а так же крутила бы машинерию в других сценариях когда ей стоит крутиться(Возможно при попадании какого-то особого снаряда? Или тяжелого предмета? Или просто от удара?)

Круто, но тогда придется менять всю машинерию, а это уже вне рамок pr.

2020-10-12 17:45 UTC, LudwigVonChesterfield commented
Я тебя не обязываю внедрять твою систему везде, тем более не вся машинерия должна крутитьтся. Емнип только компутеры, луче-стреляющие, и компоненты двигателя.

2020-10-12 18:01 UTC, KIBORG04 commented on code/modules/power/fusion/fuel_assembly/fuel_injector.dm
> +		return 0
```suggestion
		return FALSE
```
Пихнет копипастой

2020-10-12 18:01 UTC, KIBORG04 commented on code/modules/power/fusion/fuel_assembly/fuel_injector.dm
> +	return 1
```suggestion
	return TRUE
```

2020-10-12 18:01 UTC, LudwigVonChesterfield commented on code/modules/power/fusion/fuel_assembly/fuel_injector.dm
> +		return 0
всё так и есть, смотри usr:stat

2020-10-12 18:01 UTC, KIBORG04 commented on code/modules/power/fusion/fuel_assembly/fuel_injector.dm
> +		return 0
к тому же зачем этой функции вообще что-то возвращать?

2020-10-12 18:01 UTC, LudwigVonChesterfield commented on code/modules/power/fusion/fuel_assembly/fuel_injector.dm
> +	return 1
А зачем ты рекомендуешь вообще как-либо менять вывод, если этот вывод даже нигде не используется?

2020-10-12 18:03 UTC, Kortez90 commented on code/modules/power/fusion/fuel_assembly/fuel_injector.dm
> +		return 0
Она и есть. Из соседних эмиттеров.

2020-10-12 18:03 UTC, KIBORG04 commented on code/modules/power/fusion/fuel_assembly/fuel_injector.dm
> +		return 0
> Она и есть. Из соседних эмиттеров.

Предлагаю и его код привести в красивый вид

2020-10-12 18:09 UTC, Kortez90 commented on code/modules/power/fusion/fuel_assembly/fuel_injector.dm
> +		return 0
Сделай рефактор.

2020-10-12 18:10 UTC, KIBORG04 commented on code/modules/power/fusion/fuel_assembly/fuel_injector.dm
> +		return 0
> Сделай рефактор.

Я бы с радостью, если бы не другие проекты

2020-10-12 18:30 UTC, Kortez90 commented on code/modules/power/fusion/fuel_assembly/fuel_injector.dm
> +	if (src.anchored || usr:stat)
Done.

2020-10-12 18:30 UTC, Kortez90 commented on code/modules/power/fusion/fuel_assembly/fuel_injector.dm
> +	src.dir = turn(src.dir, 90)
Done.

2020-10-12 18:41 UTC, Kortez90 commented on code/modules/power/fusion/fuel_assembly/fuel_injector.dm
> +	return 1
Так снести выводы возврата или так оставить? Определились, нет?

2020-10-12 18:42 UTC, KIBORG04 commented on code/modules/power/fusion/fuel_assembly/fuel_injector.dm
> +	return 1
![image](https://user-images.githubusercontent.com/26389417/95780016-d1a7cd00-0cd3-11eb-816d-5c69fee32f76.png)
![image](https://user-images.githubusercontent.com/26389417/95780023-d4a2bd80-0cd3-11eb-9727-90574a038bba.png)
Вывод очевиден. Убирай.

2020-10-12 18:44 UTC, KIBORG04 commented on code/modules/power/fusion/fuel_assembly/fuel_injector.dm
> +	if (src.anchored || usr:stat)
![Uploading image.png…]()

2020-10-12 18:45 UTC, Kortez90 commented on code/modules/power/fusion/fuel_assembly/fuel_injector.dm
> +	if (src.anchored || usr:stat)
https://github.com/TauCetiStation/TauCetiClassic/pull/6219/commits/c649b5b8cdf4224049807c513bd216757f61879d

2020-10-12 19:28 UTC, LudwigVonChesterfield commented on code/modules/power/fusion/fuel_assembly/fuel_injector.dm
> +	if (src.anchored)
```suggestion
	if(anchored)
```

2020-10-12 19:29 UTC, LudwigVonChesterfield commented on code/modules/power/fusion/fuel_assembly/fuel_injector.dm
> +	return
```suggestion
```

2020-10-16 09:05 UTC, SpaiR requested changes

2020-10-16 09:05 UTC, SpaiR commented on code/modules/power/fusion/fuel_assembly/fuel_injector.dm
> +		to_chat(usr, "You are incapacitated.")
Здесь ничего писать не стоит, т.к. для тех же гостов это не будет иметь смысла.

2020-10-16 09:05 UTC, SpaiR commented on code/modules/power/fusion/fuel_assembly/fuel_injector.dm
> +	if (anchored)
Эту проверку нужно поместить после проверки на `incapacitated()`.

2020-10-16 09:05 UTC, SpaiR commented on code/modules/power/fusion/fuel_assembly/fuel_injector.dm
> +		to_chat(usr, "It is fastened to the floor!")
Стоит добавить `span class='notice'`

2020-10-16 09:20 UTC, LudwigVonChesterfield commented on code/modules/power/fusion/fuel_assembly/fuel_injector.dm
> +		to_chat(usr, "You are incapacitated.")
Возможно когда у нас будет четкое отражение того почему ты в стане, но сейчас не всегда можно об этом знать. И если все предметы перестанут уведомлять о том что человек в стане, как он должен грубо говоря это понять?

2020-10-16 09:36 UTC, SpaiR commented on code/modules/power/fusion/fuel_assembly/fuel_injector.dm
> +		to_chat(usr, "You are incapacitated.")
Я написал, что в контексте текущего кода это сообщение не имеет смысл __как минимум__ для гостов. Поэтому или убрать, или передать. Я предложил вариант убрать, потому что меня он устроил бы.

> И если все предметы перестанут уведомлять о том что человек в стане, как он должен грубо говоря это понять?

Можно добавить больше алертов для разных эффектов, например. 😕

2020-10-16 10:25 UTC, SpaiR approved these changes

2020-10-17 11:56 UTC, merged