Теперь СПУ нельзя имплантировать
TauCetiStation/TauCetiClassic pull request #6227
Opened 2020-10-15 00:13 UTC by Lexanx

## Описание изменений
Больше нельзя будет имплантировать СПУ
## Почему и что этот ПР улучшит
Это не логично, ведь боргов нельзя имплантировать.
Так же у СПУ нет операций по удалению имплантов из них.
Так же так же почти все импланты для СПУ, бесполезны,  нелогичны по своей сути, или наносят вред.
## Авторство
Lexanx
## Чеинжлог
:cl: Lexanx
- bugfix: - СПУ теперь нельзя имплантировать

2020-10-15 00:13 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2020-10-15 05:25 UTC, EdlerN commented
Отлично. А теперь либо выпиливай СПУ со всех ролей, либо делай альтернативу имплантам.

2020-10-15 05:40 UTC, CeUvi commented
>  выпиливай СПУ со всех ролей

Все роли это АВД?

2020-10-15 06:09 UTC, EdlerN commented
Авд, главы, антаги. Без опции деконверта им там не место.

2020-10-15 11:11 UTC, Kortez90 commented
> 
> 
> Отлично. А теперь либо выпиливай СПУ со всех ролей, либо делай альтернативу имплантам.

А так ли это страшно? СПУ не могут быть на месте глав, кроме СЕ и СМО, у которых нет имплантов. Если СПУ-трейтор, то сомневаюсь что он будет бегать с эми-имплантом или адреналином.

В целом, тут две проблемы - спу-авд, у которого стоял имплант лояльности, что является немного бредом и имплант предупреждения о смерти, который для спу важен, так как у спу всего одна жизнь.

Впрочем, пр бесполезен.

2020-10-15 12:40 UTC, Lexanx commented
> Авд, главы, антаги. Без опции деконверта им там не место.

> В целом, тут две проблемы - спу-авд, у которого стоял имплант лояльности

1. Вы пробовали деконвертить СПУ? Я сомневаюсь, так же, я сомневаюсь что у кого то из вас была ic ситуация где нужно было имплантировать СПУ лояльностью. 
На данный момент, если СПУ имплантировать лояльностью, и прокнет мозгоурон. То его уже нельзя будет вылечить, игрок до конца раунда будет лежачим инвалидом орущим "Павууук". (Лечится только алкизином, а у СПУ нет химии)

2. У нас нет операций по извлечению имплантов из СПУ. (Да и само имплантирование СПУ, выглядет крайне бредовым)
то есть вот ролька тритор СПУ, со сторейдж имплантом. Да его нашли на сканере, а вытащить не могут. 
Отлично ведь, да?

3. А так ли важны импланты СПУ Антагу. 
Тритор может и без имплантов выполнять цели.
Нюкер тоже самое.
У мага нет имплантов.

4. Сами импланты.
Лояльность - Как я уже говорил, с %50 накинет мозгоурон, и оставаться механическим овощем до конца раунда, класс.
ЭМИ - Суицид
Адреналин - Не логично.
Майндшилд - Полезен, но не логичен. Потому что, мозг СПУ, это коробка как у боргов.
Хим - Полностью бесполезен. 
Взрывной - только у ролек. Да и суицид за СПУ, после всей истерии о том что "ОНИ СУПЕР ЦЕНЯТ СЕБЯ" выглядит крайне бредово.
Сторейдж - полезен, но так ли он необходим?

> предупреждения о смерти, который для спу важен, так как у спу всего одна жизнь.

И вот единственный имплант, который имеет место быть. Почему бы его аналог просто не встроить в СПУ, изначально, раунд стартом.?

2020-10-15 13:09 UTC, Kortez90 commented
> 
> 
>я сомневаюсь что у кого то из вас была ic ситуация где нужно было имплантировать СПУ лояльностью.
>      
>то есть вот ролька тритор СПУ, со сторейдж имплантом. Да его нашли на сканере, а вытащить не могут.
>
Часто ли была такая ситуация, когда у трейтора, во-первых, вообще находили такой имплант и во-вторых, извлекали?
Тут, все же, не форум и догадками тут не занимаются. Если есть проблема, даже потенциальная - ее надо решать в корне.
>
> 
>        Тритор может и без имплантов выполнять цели.
>        Нюкер тоже самое.
>        У мага нет имплантов.
> 
СПУ-магов не бывает и быть не должно. Трейтор может выполнять свои цели вообще без аплинка. Нюкер - смертник.
>
>
>        Взрывной - только у ролек. Да и суицид за СПУ, после всей истерии о том что "ОНИ СУПЕР ЦЕНЯТ СЕБЯ" выглядит крайне бредово.
>        Сторейдж - полезен, но так ли он необходим?
> 
Бред или нет, если он есть, то пользоваться им должны все. Как уже упоминалось, догадки тут не пройдут. А если спу захочет подорвать ценой своей туши что-то вроде сбойного ии? Да, по лору их гидравлические спички дорогие, но для трейторов это условное правило не работает. 
>
> 
> И вот единственный имплант, который имеет место быть. Почему бы его аналог просто не встроить в СПУ, изначально, раунд стартом.?
> 
> По моему, ограничивание СПУ от имплантов, только лучше. Игра будет более атмосферной, и СПУ будут менее походить, на еще один респрайт хумана.
>
Встраивать нельзя, иначе спу-трейторы будут бегать с детектором, который не выключить, не вытащить. По-хорошему, спу надо рефакторить, выносить им 'life' отдельно и прикрутить модули для тушки, вроде охлаждения, мониторинга и так далее. Пока что нет смысла отрезать им импланты.

2020-10-15 13:23 UTC, Lexanx commented
> По-хорошему, спу надо рефакторить, выносить им 'life' отдельно и прикрутить модули для тушки, вроде охлаждения, мониторинга и так далее. Пока что нет смысла отрезать им импланты.
Ооокей.
Тогда вопрос, что делать сейчас? Я описал проблемы, становление овощем, и отсуствие возможности извлечения имплантов.

Пытаться фиксить их? Потому что это грустно

> рефакторить, выносить им 'life'

Прошу не кидаться тапками, а на сколько это сложно, если у человека только месяц опыта бульондокода?

2020-10-15 13:40 UTC, Kortez90 commented
> 
> 
> Ооокей.
> Тогда вопрос, что делать сейчас? Я описал проблемы, становление овощем, и отсуствие возможности извлечения имплантов.
>
Имплант лояльности в спу совать не станет никто, но как потенциальный баг стоило бы исправить исключением спу из кандидатов получения урона при имплантации. (Но андрюша наверняка решит, что это костыль.)

> 
> 
> Прошу не кидаться тапками, а на сколько это сложно, если у человека только месяц опыта бульондокода?
>
В принципе, получится либо экземпляр человека с дополнением, либо отдельный человек. Сейчас спу это коренные люди, которым нужно вносить правки через 'if (!cond)'. Ну, ты в общем-то, видел. И по-хорошему, их надо отделить как алиенов, накидать собственный `life`, интерфейсы, дефайны и так далее. Потом еще внести все это в общую архитектуру и бла, бла, бла. Много работы.

2020-10-15 13:51 UTC, LudwigVonChesterfield commented
> Прошу не кидаться тапками, а на сколько это сложно, если у человека только месяц опыта бульондокода?

Не рекомендую его слушать, судя по комментариям и действия он сам не очень понимает что делает, и о чем говорит.

2020-10-15 13:56 UTC, LudwigVonChesterfield commented
>  отдельно и прикрутить модули для тушки, вроде охлаждения, мониторинга и так далее

Именно эту роль могли бы выполнять органы.

> И по-хорошему, их надо отделить как алиенов

Да-да, отделить, а потом заново изобретать весь механ людей.

> Сейчас спу это коренные люди, которым нужно вносить правки через if (!cond)

Как и большая часть ксеноты, в какой-то момент это стоит перенести на так называемые TRAIT-ы, и всё будет чики-пуки, потому-что тогда можно будет обобщать проки для вообще всех мобов, и использовать механ который позволяет СПУ быть особенными в любых других уместных тому местах.

> накидать собственный life

Не хочу комментировать какую-то помешанность на одной функции в коде, но напишу что она неоправданная, учитывая что проблема очень комплексная, выделять конкретно это тут - нецелесообразно.

2020-10-15 13:57 UTC, LudwigVonChesterfield commented on code/game/objects/items/weapons/implants/implanter.dm
> +	if (M.isSynthetic())
может кстати проверять не то что моб - синтет, а то что конечность которая выбрана - металлическая? Может ещё бронированных не позволять имплантировать, и так далее. Короче как у шприцов.

2020-10-15 14:03 UTC, Kortez90 commented
>
>
> проблема очень комплексная,
>
Не отрицаю.

>
>
>Не рекомендую его слушать, судя по комментариям и действия он сам не очень понимает что делает, и о чем говорит.
>
А вот дискредитировать и плеваться кислотой ты так и не разучился. Когда же ты уже вырастешь?

2020-10-16 19:29 UTC, atik1n commented
Со стороны СПУ как таковых:
Если выпиливаем имплант, сразу впиливаем Оковы. Не забывай, что СПУ могут быть АВД, а у них ограничения Оковами.

2020-10-16 19:54 UTC, Lexanx commented
> Со стороны СПУ как таковых:
> Если выпиливаем имплант, сразу впиливаем Оковы. Не забывай, что СПУ могут быть АВД, а у них ограничения Оковами.

Было бы хорошо сделать СПУ, оковы. Потому что в игре они у нас присуствуют, только на словах.
(На а лоялка, такое себе, в идеале я хотел бы что то вроде, операции на СПУ, где им можно вставлять борговские платы с законами)

2020-10-16 19:57 UTC, atik1n commented
> в идеале я хотел бы что то вроде, операции на СПУ, где им можно вставлять борговские платы с законами

Нет, оно так не работает

2020-10-16 19:59 UTC, Lexanx commented
> Нет, оно так не работает
Расскажи, как оно работает

2020-10-16 20:02 UTC, UsadoSmokk commented
Правда, а на кой в бэке тогда оковы нужны?
Это звучит интересно и это лучше чем тупо кольнуть имплант. Можно задействовать роботеха для этого, пускай сидит кодит спу законы и следит за ними, хех.

2020-10-16 20:08 UTC, Lexanx commented
> Если выпиливаем имплант, сразу впиливаем Оковы. Не забывай, что СПУ могут быть АВД, а у них ограничения Оковами.

У СПУ АВД, имплант лояльности, просто потому что нет другой игровой механики дающий тот же результат.
А само пробивание металлического корпуса СПУ, ради того что бы туда закинуть железяку, которая будет стучать туда сюда об него изнутри, когда он ходит. Кансер. (У СПУ как минимум, есть на каждой части тела, панели обслуживания)

2020-10-16 20:15 UTC, Kortez90 commented
> У СПУ как минимум, есть на каждой части тела, панели обслуживания

Нет, нету. По крайней мере не на каждой.

> > в идеале я хотел бы что то вроде, операции на СПУ, где им можно вставлять борговские платы с законами
> 
> Нет, оно так не работает

И да, оно так не работает. Позитронке нельзя "закодить" законы. Каким местом вы читали лор спу? Самоходная позитронная установка. Это позитронка на спичках, у которой ни законов, ни ограничений быть не может в принципе. С боргами-позитронками такая же история и разделение на роботов, андроидов и киборгов тоже было связано с лором и ролеплеем. Но человекам легче бупать и бипать независимо от того, кем они играют, лишь бы в кармане было оружие, а в жопе втек.
Впрочем, спу от боргов отличаются телом, которое они выкупают и в котором нет места плате законов или синхронизации с законами ИИ. Это иррационально. СПУ также отличаются тем, что в отличии от позитронки боргов обрели самосознание и законы там не имеют смысла.

2020-10-16 20:16 UTC, Lexanx commented
> Нет, нету. По крайней мере не на каждой.

Положи СПУ на стол, и кликни на любую конечность отверткой.

2020-10-16 20:18 UTC, Kortez90 commented
> 
> 
> Положи СПУ на стол, и кликни на любую конечность отверткой.

И будет первая ступень операции, написать в которой можно что угодно.

2020-10-16 20:23 UTC, Lexanx commented
> И будет первая ступень операции, написать в которой можно что угодно.

Объясни, вот представь, в воображении, как тогда в случае если закоротило конечность, чинить проводку. Если не через панель обслуживания, наверно болгаркой её отпиливать, да?



> И да, оно так не работает. Позитронке нельзя "закодить" законы. Каким местом вы читали лор спу? Самоходная позитронная установка. Это позитронка на спичках, у которой ни законов, ни ограничений быть не может в принципе. С боргами-позитронками такая же история и разделение на роботов, андроидов и киборгов тоже было связано с лором и ролеплеем. Но человекам легче бупать и бипать независимо от того, кем они играют, лишь бы в кармане было оружие, а в жопе втек.
> Впрочем, спу от боргов отличаются телом, которое они выкупают и в котором нет места плате законов или синхронизации с законами ИИ. Это иррационально. СПУ также отличаются тем, что в отличии от позитронки боргов обрели самосознание и законы там не имеют смысла.

![image](https://user-images.githubusercontent.com/61974560/96305451-90caf380-1006-11eb-8f16-4e4cab6c9589.png)

2020-10-16 20:46 UTC, Lexanx commented
> И да, оно так не работает. Позитронке нельзя "закодить" законы. 

Можно

> Самоходная позитронная установка. Это позитронка на спичках, у которой ни законов, ни ограничений быть не может в принципе. 

Самоходная позитронная установка, это то что в игре нам дано, с двумя ногами и тд
Но по ЛОРу, позитронке не обязательно быть в этом типе корпуса
Тело может быть любым, хоть космическим кораблем, хоть тостером, так и оковы могут быть любыми. Хоть гласящие о том что он работник цеха, хоть космический корабль считающий что он тостер.

> С боргами-позитронками такая же история и разделение на роботов, андроидов и киборгов тоже было связано с лором и ролеплеем. 

Нет, борги могут быть позитронным мозгом другого поколения, того что младше или не осознает себя. 

Киборги это механически улучшенные люди.
Андроиды это машины подобные людям, как внешне, так и по задачам.
( А Киборги, это люди подобные машинам).

Андроидами можно было бы называть СПУ, но СПУ не сильно стремятся быть похожими на людей. ( У них мониторы на головах)

> Впрочем, спу от боргов отличаются телом, которое они выкупают и в котором нет места плате законов или синхронизации с законами ИИ. Это иррационально. 

Нет. Места для оков есть всегда. Потому что они вставляются в мозг, а не в корпус.


> СПУ также отличаются тем, что в отличии от позитронки боргов обрели самосознание и законы там не имеют смысла.

Ты можешь быть самоосознанным и с оковами.

2020-10-16 21:58 UTC, Kortez90 commented
@Lexanx Ты попросил объяснить почему это так не работает -  ты решил с этим спорить.

>
>
> Киборги это механически улучшенные люди.
> Андроиды это машины подобные людям, как внешне, так и по задачам.
> ( А Киборги, это люди подобные машинам).

Все это борги в станции, но у одних позитронка, а у других MMI. У роботов вообще ничего. Впрочем, речь была не об этом.

2020-10-17 03:05 UTC, atik1n commented
@Lexanx, не слушай @Kortez90 
Мне немного *лень* сейчас разбирать по пунктам, что он написал
Но много что - бред. Так что если есть вопросы, пиши мне в дискорде

2020-10-28 19:57 UTC, SpaiR requested changes
Поправь чейнджлог. Мы не пишем "я сделалъ". Вместо этого "сделано"

2020-10-29 02:20 UTC, Lexanx commented
> Поправь чейнджлог. Мы не пишем "я сделалъ". Вместо этого "сделано"

Поправил

2020-11-05 09:57 UTC, T6751 commented
Чтобы решить https://github.com/TauCetiStation/TauCetiClassic/issues/5795 наверняка
Можно установить расе СПУ brain_mod = 0, чтобы если к СПУ применяется adjustBrainLoss(), то не появлялся неизлечимый брейндамаг
https://github.com/TauCetiStation/TauCetiClassic/blob/436076abe50f7e569b9595c48d29c9448cc9edcb/code/modules/mob/living/carbon/species.dm#L22

2020-12-13 10:43 UTC, T6751 approved these changes

2020-12-13 10:46 UTC, merged