Странно реализованный фикс бага, при котором СПУ, продолжали видеть без головы
TauCetiStation/TauCetiClassic pull request #6236
Opened 2020-10-17 05:10 UTC by Lexanx

## Описание изменений
Почему то при отрубании головы, СПУ продолжал видеть, теперь не будет
## Почему и что этот ПР улучшит
меньше багов
## Авторство
Lexanx
## Чеинжлог
:cl: Lexanx
- bugfix: - При отрубании головы СПУ, они станут слепыми

2020-10-17 05:10 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2020-10-17 06:02 UTC, UsadoSmokk commented
Не баг, а фича(вроде)

2020-10-17 07:47 UTC, LudwigVonChesterfield commented on code/modules/organs/organ_internal.dm
> +/obj/item/organ/internal/eyes/ipc/process()
А тебе не кажется странным что мы будем каждых две секунды заново накидывать слепоту СПУ-шке? Может есть место где определяется слепа ли кукла, и стоит там добавить эти проверки или что-то такое?

2020-10-17 07:47 UTC, cool20141 commented on code/modules/organs/organ_internal.dm
> +/obj/item/organ/internal/eyes/ipc/process()
Так это, вроде как, и у людей так делается, если глаза поломаны

2020-10-17 08:26 UTC, T6751 commented on code/modules/organs/organ_internal.dm
> +/obj/item/organ/internal/eyes/ipc/process()
То, что так делается и у людей - ещё не значит, что это хорошо сделано

2020-10-17 08:38 UTC, cool20141 commented on code/modules/organs/organ_internal.dm
> +/obj/item/organ/internal/eyes/ipc/process()
Почему не хорошо? Господа знатоки, предложите альтернативу

2020-10-17 09:11 UTC, T6751 commented on code/modules/organs/organ_internal.dm
> +/obj/item/organ/internal/eyes/ipc/process()
> Почему не хорошо? 

А почему копировать неудачные решения, когда можно посмотреть и сделать лучше - это хорошо?

> Господа знатоки, предложите альтернативу

Альтернатива уже предложена выше

2020-10-17 09:25 UTC, cool20141 commented on code/modules/organs/organ_internal.dm
> +/obj/item/organ/internal/eyes/ipc/process()
Где, ничего нигде не предложено, людук просто сказал "может". И да, почему это неудачное решение? Вводить 1000 и 1 новую переменную и новый прок, что, лучше, чем воспользоваться уже существующей и повсеместно внедренной механикой?

2020-10-17 09:27 UTC, LudwigVonChesterfield commented on code/modules/organs/organ_internal.dm
> +/obj/item/organ/internal/eyes/ipc/process()
@cool20141 Ты уверен в том что знаешь о чём говоришь?

2020-10-17 09:28 UTC, LudwigVonChesterfield commented on code/modules/organs/organ_internal.dm
> +/obj/item/organ/internal/eyes/ipc/process()
Идеальным вариантом было бы иметь trait - TRAIT_BLIND, если он на кукле - кукла не видит.

Потом сделать status_effect/blind который накидывает этот trait пока он есть на кукле
Потом сделать чтобы отсутствие головы тоже накидывало этот трейт

Идеальней чем это не выйдет. Тогда нет никаких процессингов чтобы каждый раз проверять слепа ли кукла вообще(кроме того места где идёт отправка всего клиенту)

2020-10-17 09:28 UTC, LudwigVonChesterfield commented on code/modules/organs/organ_internal.dm
> +/obj/item/organ/internal/eyes/ipc/process()
Когда я говорю "может в билде что-то есть" это обычно вежливая форма фразы "сделай так, потому-что так сделать будет лучше"

2020-10-17 09:32 UTC, cool20141 commented on code/modules/organs/organ_internal.dm
> +/obj/item/organ/internal/eyes/ipc/process()
Ну я когда зомбям брейндамаг чинил, то никто почему-то не возмущался, а тут прям трагедия какая-то

2020-10-17 09:33 UTC, LudwigVonChesterfield commented on code/modules/organs/organ_internal.dm
> +/obj/item/organ/internal/eyes/ipc/process()
Поздравляю, тебе повезло что ты смог поговнокодить, давай не делать кучу ещё больше?

2020-10-17 09:36 UTC, cool20141 commented on code/modules/organs/organ_internal.dm
> +/obj/item/organ/internal/eyes/ipc/process()
Людук, ты понимаешь, что вот это ослепление, блюри и прочая хуйня она не только тут, зачем иметь миллиарды трейтов, переменных и прочего, и прочего(Тем более, что все равно куда-то придется все эти проверки на HAS_TRAIT пихать), когда уже есть вот такой вариант с blind, blurry и т.д.

2020-10-17 09:40 UTC, T6751 commented on code/modules/organs/organ_internal.dm
> +/obj/item/organ/internal/eyes/ipc/process()
> она не только тут

Может хватит ссылаться на то, что в "другой части нашей кодбазы" используется неэффективное решение?

2020-10-17 09:41 UTC, T6751 commented on code/modules/organs/organ_internal.dm
> +/obj/item/organ/internal/eyes/ipc/process()
Потому что это проблема уже этой самой "другой части нашей кодбазы", а не нового кода

2020-10-17 09:41 UTC, cool20141 commented on code/modules/organs/organ_internal.dm
> +/obj/item/organ/internal/eyes/ipc/process()
Ну да, давайте в каждую часть кода сунем что-то свое, чтобы не только отсутствие внятной документации, но и различная реализация одних и тех же механик еще больше путала людей

2020-10-17 09:45 UTC, LudwigVonChesterfield commented on code/modules/organs/organ_internal.dm
> +/obj/item/organ/internal/eyes/ipc/process()
Нет, давайте продолжать делать плохо, чтобы некий кул циферки приходил в ещё новые ПР-ы и говорил что а вот в том месте, и в этом - плохо, делай как там, чтобы не было по-разному.

2020-10-17 13:30 UTC, Lexanx commented on code/modules/organs/organ_internal.dm
> +/obj/item/organ/internal/eyes/ipc/process()
> при отсечении башки

В этом и проблема. Не смотря на то что глаза имеют parent_bodypart = BP_HEAD 
При отсечении головы он продолжал видеть.
Слепым его удалось сделать только при проверке на обрубок.

2020-10-17 13:31 UTC, LudwigVonChesterfield commented on code/modules/organs/organ_internal.dm
> +/obj/item/organ/internal/eyes/ipc/process()
Я думаю ты невнимательно прочитал моё предложение, или не понял его сути...

Сейчас ты каждых две секунды проверяешь отсечена ли башка, я предлагаю сделать так чтобы когда башка была отсечена - ставился флаг того что ты слепой на то время, пока бошку не пришьют на место.

2020-10-17 13:33 UTC, Lexanx commented on code/modules/organs/organ_internal.dm
> +/obj/item/organ/internal/eyes/ipc/process()
понял

2020-10-28 19:55 UTC, SpaiR requested changes

2020-10-28 19:55 UTC, SpaiR commented on code/__DEFINES/traits.dm
> +#define BEHEADING          "beheading"
Этот трейт ничего не делает и не нужен. Полагаю, ты его забыл удалить. (Кроме того, неправильный нейминг, смотри примеры трейтов вокруг (упущен суффикс)).

2020-10-29 02:46 UTC, Lexanx commented on code/__DEFINES/traits.dm
> +#define BEHEADING          "beheading"
А почему он не нужен? Он же указывает источник, типо не просто слепота, а от отрубленной головы.
Без него, это типо новую переменную вводить? ( я просто не знаю)

2020-12-11 20:10 UTC, LudwigVonChesterfield commented on code/modules/organs/organ_external.dm
> +	if(!disfigured && !IS_SYNTHETIC)
IS_SYNTHETIC это конректное значение, !IS_SYNTHETIC всегда FALSE

2020-12-11 20:10 UTC, LudwigVonChesterfield commented on code/__DEFINES/traits.dm
> +#define BEHEADING_TRAIT          "beheading"
Нигде не используется

2020-12-11 20:11 UTC, LudwigVonChesterfield commented
@Lexanx Пожалуйста, не запрашивай ревью ПР-а пока не протестируешь и не убедишься что ты действительно что-то качественно изменил, и не сломал ничего другого.

2021-01-19 00:38 UTC, closed without merging