Разрывные батарейки IPC при оверчардже.
TauCetiStation/TauCetiClassic pull request #6275
Opened 2020-10-23 17:32 UTC by Kortez90

## Описание изменений
При превышении максимального заряда батареи, что внутри спу, на 10% - происходит взрыв (1,0,1,1) и удаляется батарейка.
Также немного потрогал цепочку `if()` и сделал последовательность для выходов.
Пришлось использовать explosion() вместо C.explode(), так как второй отказался работать вообще хоть как-то.

Сам СПУ из-за такой перегрузки не умирает, ему лишь повреждает конечности и удаляется батарейка, так что игрок остается жив и с возможностью спасения. По-хорошему, было бы здорово сделать разрыв батареи внутри корпуса с повреждением органов, но прок взрыва батарейки внутри спу не хочет работать. К тому же, органы спу заменить нельзя, так что взрыв ливера тоже не вариант. Еще был вариант сделать перегрузку для самих батарей, но это уже слишком. Тогда будет взрываться все, что работает на батарейках при перегрузке и скорее всего, придется дописывать всему с батарейками новый прок.
## Почему и что этот ПР улучшит
Больше СПУ не смогут впитывать теслу и получать ~4к% заряда для батарейки, у которой максимум 500.
## Авторство

## Чеинжлог
:cl: Kortez90
 - rscadd: IPC взрываются при перегрузке их батареи.

2020-10-23 17:32 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2020-10-23 18:32 UTC, LudwigVonChesterfield commented on code/modules/organs/organ_internal.dm
> +	else if(owner.nutrition > (C.maxcharge/0.8))
/ 0.8 это умножить на 1.2

2020-10-23 18:42 UTC, Kortez90 commented on code/modules/organs/organ_internal.dm
> +	else if(owner.nutrition > (C.maxcharge/0.8))
0,831 лучше?

2020-10-23 18:42 UTC, LudwigVonChesterfield commented on code/modules/organs/organ_internal.dm
> +	else if(owner.nutrition > (C.maxcharge/0.8))
... Если ты хочешь 110% просто умножь на 1.1

2020-10-23 18:48 UTC, Kortez90 commented on code/modules/organs/organ_internal.dm
> +	else if(owner.nutrition > (C.maxcharge/0.8))
Точно. Спасибо. С математикой почти не дружу. 
![9364c099ed691bfb-sad-cry-gif-sad-cry-animation-discover-share-gifs 1](https://user-images.githubusercontent.com/36198983/97042296-79958400-1579-11eb-8a72-729bae1367eb.gif)

2020-10-25 18:14 UTC, LudwigVonChesterfield reviewed
Мне не нравится что эти проверки происходят в processing-е - тобишь лежат лишним весом пока не совершиться одно действие.

Я бы без зазрений совести замёржил бы эту фичу, если бы она работала так:
- У батарейки есть функция add_charge, которая вызывает сигнал COMSIG_CELL_ADD_CHARGE
- Почка СПУ подвязывает к этому сигналу функцию check_explosion
- Когда в батарейку добавили заряда > определенного порога(у тебя этот порог - 110%) - батарейка в почке делает бум, СПУ выключается.

(Не обязательно сигналы, но чтобы эта логика была при добавлении заряда СПУ, а не каждых две секунды проверялась в почке всех СПУшек).

2020-10-25 18:55 UTC, Kortez90 commented
>
>
> Когда в батарейку добавили заряда > определенного порога - батарейка в почке делает бум

До меня примерно дошло, что ты хочешь, но реализовать это проблематично.
Это новый дефайн, который содержит в себе..? (Создавать дефайн ради одной переменной?)
>
>
>Почка СПУ подвязывает к этому сигналу функцию check_explosion

Что в любом случае будет проверяться через почку и логика останется такой же, но через `#def`.

>
>
>чтобы эта логика была при добавлении заряда СПУ, а не каждых две секунды проверялась в почке

То есть, выделить триггер из почки и сунуть его во все, что способно заряжать спу? У `cell` нет `add_charge`, но есть `give()`.
К тому же, заряд самой батареи практически не учитывается. То есть, если в спу поступает ток, то он идет в нутрименты, а не в батарейку. Она в любом случае будет со своим максимумом.

В общем, нужно более развернутое описание.

2020-10-25 18:58 UTC, LudwigVonChesterfield commented
Ничего не нужно, иди читать документацию по dcs. Она в билде есть.

2020-10-25 18:58 UTC, LudwigVonChesterfield commented
> То есть, если в спу поступает ток, то он идет в нутрименты, а не в батарейку.

Тогда замени всё что я говорил про батарейку на СПУ. Сигнал от СПУ который ловит почка и взрывает его.

2020-10-26 11:23 UTC, Kortez90 commented
> иди читать документацию по dcs. Она в билде есть.

Полночи искал, так и не нашел документации. Только комменты к коду из разряда "Это переменная, она работает.".
Пришлось курить вручную все эти `SEND_SIGNAL` и `Register/Unregister`(Кто вообще так пишет?). Правда пока толку не особо много.

2020-10-26 11:25 UTC, LudwigVonChesterfield commented
![image](https://user-images.githubusercontent.com/17705613/97166947-ba1a1b00-178e-11eb-8df7-519bb54d55d6.png)

https://github.com/TauCetiStation/TauCetiClassic/blob/master/code/datums/components/README.md

2020-10-26 21:51 UTC, Kortez90 commented
Так... Я раскурил "документацию" и перевел логику на сигнал. Прежде чем продолжим "танцы вокруг столба", нужны ответы на некоторые вопросы, которые возникли в ходе войны с DCS, так как трогал я ее впервые.

Во-первых, о структуре.
Дефайним какой-нибудь `COMSIG_CELL_OVERCHARGE_EXPL`.
Затем в `/obj/item/organ/internal/liver/ipc/atom_init()` регистрируем сигнал с активацией прока `check_overcharge_expl()`.
И при ударе током через `/mob/living/carbon/human/electrocute_act()` посылаем сигнал в ливер, после чего проходит проверка и у спу разрывает батарейку, если оверчардж больше 20% от максимума.

Во-вторых, вопросы.
Обязателен ли `unregister`, где лучше его употреблять, кроме очевидных `Destroy()` и какие лучше аргументы использовать?
Какие вообще негласные правила использования DCS?
Можно ли как-то назначить таргет для `SEND_SIGNAL` более удобно, чем объявление переменной `IO`, чтобы послать его в почку? Можно ли как-то воспользоваться наследованием от `carbon/human`?
Безопасно ли использование qdel() в проке проверки оверчарджа?
Можно ли как-то вызвать взрыв более корректно?

2020-10-26 22:49 UTC, LudwigVonChesterfield commented
> Обязателен ли unregister, где лучше его употреблять, кроме очевидных Destroy() и какие лучше аргументы использовать?
Какие вообще негласные правила использования DCS?

Там где нужно снять прослушку с сигнала. В дестрое как раз не надо, там это происходит автоматически.

> Можно ли как-то назначить таргет для SEND_SIGNAL более удобно, чем объявление переменной IO, чтобы послать его в почку? Можно ли как-то воспользоваться наследованием от carbon/human?

Ничего не понятно.

> Безопасно ли использование qdel() в проке проверки оверчарджа?

Мне за тебя нужно ПР делать и тестировать?

> Можно ли как-то вызвать взрыв более корректно?

Мне за тебя нужно ПР делать и тестировать?

2020-10-26 22:56 UTC, Kortez90 commented
> Мне за тебя нужно ПР делать и тестировать?

Нет, я просто спрашиваю заранее, чтобы не возникало таких ситуаций как вчера.
Может есть какие-то спецификации или особенности использования? У меня-то при тестах работает, но ты же как обычно всплывешь и скажешь, что тебе что-то не нравится.
Такой подход к делу не только мешает, но и делает хуже, как тебе, так и остальным.

>Ничего не понятно.


```
/mob/living/carbon/human/electrocute_act(args)
	var/obj/item/organ/internal/liver/IO = organs_by_name[O_LIVER]
	SEND_SIGNAL(IO, COMSIG_CELL_CHARGE_ADD)
	...
```
Мне не нравится такое обращение к `IO`. Есть способ лучше?

2020-10-26 23:03 UTC, LudwigVonChesterfield commented
> У меня-то при тестах работает, но ты же как обычно всплывешь и скажешь, что тебе что-то не нравится.
Такой подход к делу не только мешает, но и делает хуже, как тебе, так и остальным.

Ты заливаешь на гитхаб код чтобы он прошёл ревью. Я не могу ревьювить кода который не вижу. Если ты хочешь комментариев по твоему коду - заливай, если ты хочешь я готов полностью отказаться от ревью любых твоих ПР-ов.

2020-10-26 23:04 UTC, LudwigVonChesterfield commented
> Мне не нравится такое обращение к IO. Есть способ лучше?

Можно к примеру сделать чтобы electrocute_act имел сигнал COMSIG_ATOM_ELECTROCUTE_ACT, к которому подвязывалась почка.

Из сниппета который ты скинул я вижу что ты кажется не понял как работают сигналы...

Сигнал COMSIG_CELL_CHARGE_ADD должен вызываться из функции add_charge у батарейки чтобы не надо было везде ставить этот сигнал где батарейка заряжается...

2020-10-26 23:08 UTC, Kortez90 commented
> Сигнал COMSIG_CELL_CHARGE_ADD должен вызываться из функции add_charge у батарейки чтобы не надо было везде ставить этот сигнал где батарейка заряжается...

Там другая логика, так как батарейки не учитываются. Это просто название дефайна старое осталось.
СПУ могут получить оверчардж только через удар током, который включает в себя также `tesla_shock`.
Отчасти поэтому решил зацепить сразу все и при ударе током спу в ливер отправляется сигнал для проверки там прока оверчарджа.

2020-10-26 23:08 UTC, LudwigVonChesterfield commented
Я не буду дальше ревьювить этот ПР, я описал своё недовольство выше для тех кто когда-либо захочет и в будущем его смотреть.

2020-10-28 19:44 UTC, SpaiR requested changes

2020-10-28 19:44 UTC, SpaiR commented on code/modules/mob/living/carbon/human/human.dm
> +			SEND_SIGNAL(IO, COMSIG_ATOM_ELECTROCUTE_ACT)
Чтобы не придумывать велосипеды имеет смысл сравнивать с ТГ реализацией. Там сигналы чуть ли не каждый чих есть, да. Выводы делай сам. Пока что я вижу, что в текущем виде ты просто очень странным способом вызываешь `check_explosion` https://github.com/tgstation/tgstation/blob/f53d65ee3d0269331043ade93fe3e2fd50f4111b/code/modules/mob/living/living_defense.dm#L320-L321

2020-10-28 20:05 UTC, Kortez90 commented on code/modules/mob/living/carbon/human/human.dm
> +			SEND_SIGNAL(IO, COMSIG_ATOM_ELECTROCUTE_ACT)
Как того и просил лудук. В обход процессинга.
Покурю еще, помаринуйте пр.

2020-11-30 13:10 UTC, Kortez90 commented
Ждем, ждем.

2021-01-10 18:59 UTC, T6751 requested changes

2021-01-10 18:59 UTC, T6751 commented on code/modules/organs/organ_internal.dm
> +		explosion(T,1,0,1,1)
```suggestion
		explosion(T, 1, 0, 1, 1)
```

2021-01-10 18:59 UTC, T6751 commented on code/modules/organs/organ_internal.dm
> +	else if(damage)
Ранний возврат. И ниже тогда можно убрать проверку ```C &&```
```suggestion
		owner.silent = 2
		return
	if(damage)
```

2021-01-10 18:59 UTC, T6751 commented on code/modules/organs/organ_internal.dm
> +	if(C && owner.nutrition < 1)
```suggestion
	if(owner.nutrition < 1)
```

2021-01-10 18:59 UTC, T6751 commented on code/modules/organs/organ_internal.dm
> +		UnregisterSignal(parent, COMSIG_ATOM_ELECTROCUTE_ACT)
Теоретически из IPC можно вынуть батарейку, поставить под действие теслы, чтобы сигнал больше не регистрировался. Вернуть батарейку снова и... Мы получаем IPC, которому снова не страшна Тесла?

```UnregisterSignal()``` обычно помещают в дестрой объекта или согласно этой проверке, было бы логично поместить ```UnregisterSignal```, когда батарейка удаляется/вынимается, и регистрировать соответственно, когда она вставляется

2021-01-10 19:05 UTC, Kortez90 commented on code/modules/organs/organ_internal.dm
> +		UnregisterSignal(parent, COMSIG_ATOM_ELECTROCUTE_ACT)
Если начинать регистрацию со вставки, то СПУ со старта его регистрировать не будут.

2021-01-10 19:27 UTC, T6751 commented on code/modules/organs/organ_internal.dm
> +		UnregisterSignal(parent, COMSIG_ATOM_ELECTROCUTE_ACT)
В атом_ините она по идее "вставляется", поэтому РегистрСигнал оттуда не нужно будет убирать же

2021-01-10 19:31 UTC, Kortez90 commented on code/modules/organs/organ_internal.dm
> +		UnregisterSignal(parent, COMSIG_ATOM_ELECTROCUTE_ACT)
Хорошо. Я позже этим займусь.

2021-01-10 20:30 UTC, KIBORG04 commented on code/__DEFINES/dcs/signals.dm
> +/// electrocute_act()
Напиши тут по шаблону комментарий

2021-01-10 21:37 UTC, Kortez90 commented on code/modules/organs/organ_internal.dm
> +		UnregisterSignal(parent, COMSIG_ATOM_ELECTROCUTE_ACT)
Нет. Вытащить батарейку и поставить ее под действие теслы не выйдет. Тесла по ней даже не бьет. Да и сигнал регистрирует `owner`, а не батарейка.

2021-01-10 21:47 UTC, T6751 commented on code/modules/organs/organ_internal.dm
> +		UnregisterSignal(parent, COMSIG_ATOM_ELECTROCUTE_ACT)
Если в IPC на момент попадания Теслой не будет батарейки, то сигнал будет анрегистрирован?

2021-01-10 22:12 UTC, Kortez90 commented on code/modules/organs/organ_internal.dm
> +		UnregisterSignal(parent, COMSIG_ATOM_ELECTROCUTE_ACT)
Верно. Может добавить регистрацию в шаг операции или вообще избавиться от `unregister`?

2021-01-10 22:53 UTC, T6751 commented on code/modules/organs/organ_internal.dm
> +		UnregisterSignal(parent, COMSIG_ATOM_ELECTROCUTE_ACT)
Избавиться думаю будет приемлимо

2021-01-10 22:54 UTC, Kortez90 commented on code/modules/organs/organ_internal.dm
> +		UnregisterSignal(parent, COMSIG_ATOM_ELECTROCUTE_ACT)
Done.

2021-01-10 23:12 UTC, T6751 commented on code/modules/organs/organ_internal.dm
> +	var/obj/item/weapon/stock_parts/cell/C = locate(/obj/item/weapon/stock_parts/cell) in src
```suggestion
	var/obj/item/weapon/stock_parts/cell/C = locate() in src
```

2021-01-10 23:12 UTC, T6751 commented on code/modules/organs/organ_internal.dm
> +	if(owner.nutrition > (C.maxcharge*1.2))
```suggestion
	if(owner.nutrition > (C.maxcharge * 1.2))
```

2021-01-11 04:24 UTC, T6751 approved these changes
В целом работает

2021-01-20 08:28 UTC, merged

2021-02-14 16:18 UTC, FBitSafe commented
вот вопрос есть, а оверчарджнутая картошка тоже бахает?