Добавление и обновление 20 юбок для проф
TauCetiStation/TauCetiClassic pull request #6286
Opened 2020-10-25 22:24 UTC by FelixRuin

## Описание изменений
Добавил 20 юбок, часть из которых (смо, химик, генетик, вирусолог, медик) получили совершенно иные текстуры и часть (Офицер и Кадет) чуть-чуть изменено под общий стиль остальных юбок
![image](https://user-images.githubusercontent.com/31424899/97120653-a9838980-1729-11eb-8f0f-8d0bc3b608b2.png)
<details> 
  <summary>Старые версии одежды мед-бея и брига</summary>

 ![image](https://user-images.githubusercontent.com/31424899/86020326-7279c180-ba30-11ea-913f-59c9f18bdb09.png)
![image](https://user-images.githubusercontent.com/31424899/86020251-5b3ad400-ba30-11ea-9800-028dbded4ca6.png)
![image](https://user-images.githubusercontent.com/31424899/51086885-efda4500-175c-11e9-917a-6db37506e6eb.png)
</details>

## Почему и что этот ПР улучшит
Разнообразие в выборе одежды космонавтов
## Авторство
Felix Ruin - Winter Schock - код и ретуширование текстур
Sardine - часть текстур
Vore Station или Polaris - основной концепт всех юбочных униформ
## Чеинжлог
:cl: Winter Schock
- image[link]: 20 проф получили юбочный вариант формы, выбираемый при создании персонажа

2020-10-25 22:24 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2020-10-25 22:26 UTC, KIBORG04 commented
Уборщику то зачем?

2020-10-25 22:27 UTC, FelixRuin commented
А почему нет?

2020-10-25 22:27 UTC, KIBORG04 commented
> А почему нет?

Работа такая, грязно, непрактично

2020-10-25 22:28 UTC, FelixRuin commented
Тобишь костюм горничной было больно практично?

2020-10-25 22:29 UTC, KIBORG04 commented
> Тобишь костюм горничной было больно практично?

А горничные должны копаться в крови и мусоре, драить полы мокрой шваброй и тд

2020-10-25 22:32 UTC, FelixRuin commented
Тобишь работа уборщика предполагает кровь-кишки-распидорасило? И работу мусорщика заодно

2020-10-25 22:34 UTC, KIBORG04 commented
> Тобишь работа уборщика предполагает кровь-кишки-распидорасило? И работу мусорщика заодно

Не обязательно кровь и кишки, ведь есть и другие биологические отходы, та же кухня, где может на пол все что угодно упасть. У нас мусорщик и не должен убирать мусор на самой станции, а значит все уборщику

2020-10-25 22:38 UTC, FelixRuin commented
Ладно, это можно зачесть как аргумент, но сперва поясни почему непрактично, в плане, что критически важного изменится для человека в юбке в уборке?

2020-10-25 22:44 UTC, KIBORG04 commented
> Ладно, это можно зачесть как аргумент, но сперва поясни почему непрактично, в плане, что критически важного изменится для человека в юбке в уборке?

Как минимум то, что у тебя коленки голые и надо об этом помнить при уборке. Не, как бы есть и те, которым все равно на чистоту тела и для них юбка будет незначительно лучше, но это другая история. А еще фартук был бы еще полезней, чем юбка в качестве спец. одежды

2020-10-25 22:54 UTC, FelixRuin commented
Спец одежда - джинсы
Кхм, фартук у нас уже есть
И вряд-ли он хоть какое-то дело имеет к данному пру
И далее... Как и чем у нас можно испачкать колени? Ну только если не ползать по полу
Типо серьезно, у нас нет хоть какой-то грязи до такой степени
Максимум кровь... А её так в любом случае тындец будет

2020-10-25 22:57 UTC, KIBORG04 commented
Если спец одежда джинсы, то почему тут юбка?
Фартук есть, но не для уборщиков. Просто фартук намного сильнее похож на спецовку.
А как ты в ирл пачкаешь колени? Работая единственным уборщиком на станции многое может с тобой произойти. Не стоит ограничивать видимость проблем только механом.

2020-10-25 23:03 UTC, FelixRuin commented
Вот честно, я в ирл максимум ступни пачкаю, и я чёт вообще придумать не могу, чем и как может испачкать ноги
На космической научной станции

2020-10-25 23:19 UTC, Kortez90 commented
>  чем и как может испачкать ноги на космической научной станции

Идешь в тоннелях, поскальзываешься на луже масла и вуаля, твои коленки и юбка в дерьме.
Убираешь кашу из человека после кебирнетизации, сбойный борг обрызгивает тебя маслом и вуаля, твои коленки и юбка в дерьме.
Потенциальных ситуаций может быть почти сколько угодно много, но юбка для уборщика - бред.

2020-10-25 23:27 UTC, UDaV73rus commented
Сокрушительный поворот в жизни уборщиц и их коленок

2020-10-25 23:56 UTC, Motzord commented
> > чем и как может испачкать ноги на космической научной станции
> 
> Идешь в тоннелях, поскальзываешься на луже масла и вуаля, твои коленки и юбка в дерьме.
> Убираешь кашу из человека после кебирнетизации, сбойный борг обрызгивает тебя маслом и вуаля, твои коленки и юбка в дерьме.
> Потенциальных ситуаций может быть почти сколько угодно много, но юбка для уборщика - бред.

Идешь такой по коридору, видишь любую профу в юбке, спотыкаешься об свои манярп понятия и вуаля, твои штаны в дерьме.

2020-10-26 07:26 UTC, LudwigVonChesterfield commented
если Киборг хочет чтобы юбки нельзя было носить из-за пачкающихся коленок, пускай он эти пачкающиеся коленки закодит.

в реалиях сосаки никто коленки не пачкает и юбки ничем не отличаются от штанов по своим Тактико-Техническим Боевым Характеристикам. этот ПР это не стремится изменять, и потому Киборг я думаю ты пока-что проиграл...

ждём спрайт ревьювера

2020-10-26 08:55 UTC, KIBORG04 commented
> если Киборг хочет чтобы юбки нельзя было носить из-за пачкающихся коленок, пускай он эти пачкающиеся коленки закодит.
> 
> в реалиях сосаки никто коленки не пачкает и юбки ничем не отличаются от штанов по своим Тактико-Техническим Боевым Характеристикам. этот ПР это не стремится изменять, и потому Киборг я думаю ты пока-что проиграл...
> 
> ждём спрайт ревьювера

Я думаю, все же на станции должны быть адекватные условия труда, часть лора, так называемого. У нас сейчас есть туалеты, а куклы не умеют срать, зачем они нужны тогда?

2020-10-26 12:12 UTC, Zmey25 commented
Пулл, который таукети заслуживает

2020-10-26 14:27 UTC, UsadoSmokk commented
> > если Киборг хочет чтобы юбки нельзя было носить из-за пачкающихся коленок, пускай он эти пачкающиеся коленки закодит.
> > в реалиях сосаки никто коленки не пачкает и юбки ничем не отличаются от штанов по своим Тактико-Техническим Боевым Характеристикам. этот ПР это не стремится изменять, и потому Киборг я думаю ты пока-что проиграл...
> > ждём спрайт ревьювера
> 
> Я думаю, все же на станции должны быть адекватные условия труда, часть лора, так называемого. У нас сейчас есть туалеты, а куклы не умеют срать, зачем они нужны тогда?

твоя миссия - это исправить.

2020-10-26 15:40 UTC, cool20141 commented
Мммм, больше трапов :flushed:

2020-10-26 16:11 UTC, TungstenOctopus requested changes
Настоятельно советую автору погуглить какие юбки носят на работе, а то складывается ощущение, что в качестве примера автор брал японскую школу из аниме. Наша станция - не школа, и униформа должна быть не школьная.
<details> 
  <summary>как не надо</summary>

  ![изображение](https://user-images.githubusercontent.com/6051766/97197713-a1bdf680-17b6-11eb-9807-f42866631013.png)

</details>

2020-10-26 16:12 UTC, cool20141 commented
Зато у нас станция–аниме

2020-10-26 16:19 UTC, Ayuska commented
> 
> 
> Настоятельно советую автору погуглить какие юбки носят на работе, а то складывается ощущение, что в качестве примера автор брал японскую школу из аниме. Наша станция - не школа, и униформа должна быть не школьная.
> как не надо
>сравнение с реальным миром.
Уже смешно.
Если ты, дорогой друг, об длинне юбок, то нынешние юбки ЕЩЕ короче, и уродливее.
Если ты хочешь чтобы кто-то прислушался к твоему мнению, не только потому, что вынужден, а потому, что оно имеет логическое обоснование, уточни, что требуется изменить.

2020-10-26 16:21 UTC, Ayuska commented
Сравниваем длинну юбок.
https://cdn.discordapp.com/attachments/769198977768882236/770320945230905374/51086885-efda4500-175c-11e9-917a-6db37506e6eb.png
Выше колена, определенно можно.
https://cdn.discordapp.com/attachments/769198977768882236/770320945431969803/unknown.png
^ ниже колена, определенно похабщина.

2020-10-26 16:23 UTC, Ayuska commented
> 
> 
> Настоятельно советую автору погуглить какие юбки носят на работе, а то складывается ощущение, что в качестве примера автор брал японскую школу из аниме. Наша станция - не школа, и униформа должна быть не школьная.
> как не надо
> 
> ![изображение](https://user-images.githubusercontent.com/6051766/97197713-a1bdf680-17b6-11eb-9807-f42866631013.png)

Забыл еще это подметить, в силу своей испорченности, он сразу видит вот такую картину в воображении, при условии, что юбки на спрайтах ниже колена, просьба horny выйти с гитхаба и перелогиниться на кодбазу воура.

2020-10-26 16:30 UTC, TungstenOctopus commented
> 
> 
> > Настоятельно советую автору погуглить какие юбки носят на работе, а то складывается ощущение, что в качестве примера автор брал японскую школу из аниме. Наша станция - не школа, и униформа должна быть не школьная.
> > как не надо
> 
> > сравнение с реальным миром.
> 
> Уже смешно.
> Если ты, дорогой друг, об длинне юбок, то нынешние юбки ЕЩЕ короче, и уродливые.
> Если ты хочешь чтобы кто-то прислушался к твоему мнению, не только потому, что вынужден, а потому, что оно имеет логическое обоснование, уточни, что требуется изменить.

до пулреквеста
![изображение](https://user-images.githubusercontent.com/6051766/97199084-455bd680-17b8-11eb-9fc7-2416228f0a53.png)
после
![изображение](https://user-images.githubusercontent.com/6051766/97199002-2eb57f80-17b8-11eb-9e05-b1a9ea97f3c9.png)

>Забыл еще это подметить, в силу своей испорченности, он сразу видит вот такую картину в воображении, при условии, что юбки на спрайтах ниже колена, просьба horny выйти с гитхаба и перелогиниться на кодбазу воура.

Безусловно, horny не тот, кто в 2д игру о космонавтах пытается пышные лоли-юбки внести, а то, кто видит в пышных лоли-юбках пышные лоли-юбки. Вам с такими аргументами нужно в детсад, не иначе.

![изображение](https://user-images.githubusercontent.com/6051766/97199668-ee0a3600-17b8-11eb-877c-49e815b704d7.png)

Видишь колено? И я не вижу. А оно есть. 

>уточни, что требуется изменить.

Для тугодумов, еще раз: погуглите какие юбки носят взрослые люди на работе. Такие как у вас - однозначно нет. И сравнения с реальной жизнью неизбежны, иначе завтра очередной умник капитану униформу в виде хотдога сделает, а когда его спросят зачем, он ответит "Ну а почему нет? Щас бы с ирл сравнивать".

2020-10-26 16:34 UTC, Ayuska commented
> 
> 
> > > Настоятельно советую автору погуглить какие юбки носят на работе, а то складывается ощущение, что в качестве примера автор брал японскую школу из аниме. Наша станция - не школа, и униформа должна быть не школьная.
> > > как не надо
> > 
> > 
> > > сравнение с реальным миром.
> > 
> > 
> > Уже смешно.
> > Если ты, дорогой друг, об длинне юбок, то нынешние юбки ЕЩЕ короче, и уродливые.
> > Если ты хочешь чтобы кто-то прислушался к твоему мнению, не только потому, что вынужден, а потому, что оно имеет логическое обоснование, уточни, что требуется изменить.
> 
> до пулреквеста
> ![изображение](https://user-images.githubusercontent.com/6051766/97199084-455bd680-17b8-11eb-9fc7-2416228f0a53.png)
> после
> ![изображение](https://user-images.githubusercontent.com/6051766/97199002-2eb57f80-17b8-11eb-9e05-b1a9ea97f3c9.png)
> 
> > Забыл еще это подметить, в силу своей испорченности, он сразу видит вот такую картину в воображении, при условии, что юбки на спрайтах ниже колена, просьба horny выйти с гитхаба и перелогиниться на кодбазу воура.
> 
> Безусловно, horny не тот, кто в 2д игру о космонавтах пытается пышные лоли-юбки внести, а то, кто видит в пышных лоли-юбках пышные лоли-юбки. Вам с такими аргументами нужно в детсад, не иначе.
> 
> ![изображение](https://user-images.githubusercontent.com/6051766/97199668-ee0a3600-17b8-11eb-877c-49e815b704d7.png)
> 
> Видишь колено? И я не вижу. А оно есть.
> 
> > уточни, что требуется изменить.
> 
> Для тугодумов, еще раз: погуглите какие юбки носят взрослые люди на работе. Такие как у вас - однозначно нет. И сравнения с реальной жизнью неизбежны, иначе завтра очередной умник капитану униформу в виде хотдога сделает, а когда его спросят зачем, он ответит "Ну а почему нет? Щас бы с ирл сравнивать".

Дружок, скинь паспорт, если начал подобное говорить, и пытаться использовать это, как аргумент, и позже свое место работы с фотографиями рабочих женского пола в юбках карандаша и паранже.

>Лоли-юбки
>@
>Юбки выше колена, так называе circle skirt's, которые являются кэжуел стилем, допустимым в офиссах.

Мне кажется у вас психическое отклонение, у вас анимефобия?
"Вы подавляете себе тягу к мальчикам/девочкам(выберите по личным предпочтениям спрайтеров) в коротких юбочках и потому везде видите их, тогда идите в спрайтеры ТауЦети, там вы сможете всем доказать, что у вас не стоит на маленьких девочек в юбочках."

2020-10-26 16:41 UTC, TungstenOctopus commented
![изображение](https://user-images.githubusercontent.com/6051766/97200716-3ece5e80-17ba-11eb-8fa5-2a30d5c362fd.png)
![изображение](https://user-images.githubusercontent.com/6051766/97200771-4db51100-17ba-11eb-8754-7f6f49b2db09.png)

Даже незрячий человек сможет увидеть разницу между юбками на картинке. Хорошо, загуглю для вас: 

![изображение](https://user-images.githubusercontent.com/6051766/97200947-89e87180-17ba-11eb-95d1-4cd18fd4fbf5.png)

Если не способны передать на спрайте то, что хотите - или учитесь это делать, или не делайте вовсе. Не нужно вместо этого приходить на гитхаб, выпрашивать у меня паспорт и тратить мое время своей  детской пассивной агрессией.

2020-10-26 16:50 UTC, Ayuska commented
> 
> 
> ![изображение](https://user-images.githubusercontent.com/6051766/97200716-3ece5e80-17ba-11eb-8fa5-2a30d5c362fd.png)
> ![изображение](https://user-images.githubusercontent.com/6051766/97200771-4db51100-17ba-11eb-8754-7f6f49b2db09.png)
> 
> Даже незрячий человек сможет увидеть разницу между юбками на картинке. Хорошо, загуглю для вас:
> 
> ![изображение](https://user-images.githubusercontent.com/6051766/97200947-89e87180-17ba-11eb-95d1-4cd18fd4fbf5.png)
> 
> Если не способны передать на спрайте то, что хотите - или учитесь это делать, или не делайте вовсе. Не нужно вместо этого приходить на гитхаб, выпрашивать у меня паспорт и тратить мое время своей детской пассивной агрессией.

Просьба засунуть свое завышенное эго и умение рисовать туда, откуда уважаемый спрайт проверщик его взял.
Я все еще жду ваш паспорт с датой рождении, иначе ваши попыточки все свести к возрасту, выглядят, как жалкие попытки самоутвердиться.
Как только ты используешь какую-либо аллегорию на возраст, ты подписываешься, что должен кинуть свой паспорт, иначе ты пустозвон и спрайтер ТауЦети.

Продолжим по спрайтам, спрайт доходит до колена, и даже перекрывает его. Факт есть факт. 
Лично изменял кадетские и офицерские юбки, разница лишь в одном пикселе по длинне, но уже он видит лолей, обострение еще не кончилось.
Можете сформулировать не возводя абсолют ваш стояк на маленьких девочек в юбочках, отправляя ЯВНО юбку короче, но сформулировал адекватно вашу позицию, 
Ты пытаешься доказать что-то сравнивая 23 век с 21 веком, понятненько, проталкиваем скрепы и православные ценности в киберпанк.
Сравним нынешние ДОПУСТИМЫЕ варианты одежды на работу.
![изображение](https://user-images.githubusercontent.com/41844545/97201826-f156ef00-17c3-11eb-8d79-d49498741e8b.png)
Явно бляди и лоли, просьба пройти с нами.

2020-10-26 17:03 UTC, TungstenOctopus commented
>Просьба засунуть свое завышенное эго и умение рисовать туда, откуда уважаемый спрайт проверщик его взял.
Будь у меня завышенное эго, я бы с неисправимыми вроде тебя не разговаривал.

>Я все еще жду ваш паспорт с датой рождении, иначе ваши попыточки все свести к возрасту, выглядят, как жалкие попытки самоутвердиться.

Это скорее какие-то твои комплексы. Ты так бурно реагируешь на слово "взрослый", у тебя какие-то проблемы?

>Продолжим по спрайтам, спрайт доходит до колена, и даже перекрывает его. Факт есть факт.

Где колено, лебовски? Где ты колено увидел? У нас спрайты меряются относительно других спрайтов, чтоб соблюдались пропорции. Судя по пропорциям на твоих спрайтах, юбка твоя намного выше колена. Опять же, надо быть слепым котенком чтобы этого не видеть.

>Можете сформулировать не возводя абсолют ваш стояк на маленьких девочек в юбочках

Какой ты забавный. Это ведь не я пытаюсь пышные юбки на пол-бедра выдать за рабочую одежду))) Аниме-boy столкнулся с реальной жизнью, где немного другие традиции и правила :(

2020-10-26 17:08 UTC, Ayuska commented
@

> 
> 
> > Просьба засунуть свое завышенное эго и умение рисовать туда, откуда уважаемый спрайт проверщик его взял.
> > Будь у меня завышенное эго, я бы с неисправимыми вроде тебя не разговаривал.

Ошибка, у тебя завышенное эго, доказательство: ты ставишь меня ниже тебя, по какому-то праву, видимо по праву спрайтера для 2 игры на ролевом проекте ТауЦети, точно-точно, игроки не люди, спрайтеры сила. Правда они так и не научились рисовать не пикселями, вот смешно.
> 
> > Я все еще жду ваш паспорт с датой рождении, иначе ваши попыточки все свести к возрасту, выглядят, как жалкие попытки самоутвердиться.
> 
> Это скорее какие-то твои комплексы. Ты так бурно реагируешь на слово "взрослый", у тебя какие-то проблемы?

Это твои комплексы, ты как-то бурно среагировал на просьбу перестать выебываться необоснованно в интернете, у тебя нету паспорта, ты нелегал? Ты отправляешь всю свою зарплату за границу, ты скинь мне свой номер карты, отправлю пару сотен на дошираки и краски для стен.
> 
> > Продолжим по спрайтам, спрайт доходит до колена, и даже перекрывает его. Факт есть факт.
> 
> Где колено, лебовски? Где ты колено увидел? У нас спрайты меряются относительно других спрайтов, чтоб соблюдались пропорции. Судя по пропорциям на твоих спрайтах, юбка твоя намного выше колена. Опять же, надо быть слепым котенком чтобы этого не видеть.

Я ждал этого момента, только ты считаешь, что спрайты выше колена, просьба доказать это или сменить ревьювера, не сидящего с постером лоли девочки на стеночке.
Просто, докажи где на 2д кукле колено, и возможно я соглашусь, если твои док-ва не будут возведением в абсолют и бахвальством.
> 
> > Можете сформулировать не возводя абсолют ваш стояк на маленьких девочек в юбочках
> 
> Какой ты забавный. Это ведь не я пытаюсь пышные юбки на пол-бедра выдать за рабочую одежду))) Аниме-boy столкнулся с реальной жизнью, где немного другие традиции и правила :(

Он начал использовать скобочки, я кажется его обидел, теперь ждем кары в духе Спейра, с отказом ревьювить?

2020-10-26 17:12 UTC, TungstenOctopus commented
tl;dr

Ты знаешь что такое пропорции?
![изображение](https://user-images.githubusercontent.com/6051766/97204814-404e5580-17bf-11eb-81e5-5c0b26ac5b97.png)

2020-10-26 17:13 UTC, Kortez90 commented
Извините, конечно, что вмешиваюсь в ваши увлекательные дискуссии и взаимные оскорбления, но намерен напомнить, что здесь не форум и разводить 90% воды в комментариях это не круто.

@Ayuska 
Юбки короткие и это факт. Либо исправь это, как того хочет департамент-одного-человека, либо это просто не примут. Ваши споры не приведут к консенсусу. Паспорт не покажу.

@TungstenOctopus
Как и большинство местных, не стоит давить на детей и проявлять свою демонстративную власть. Конфликты не помогут решить проблему. Человек хочет свои юбки, ему уже сказали что не так, но он настаивает. Так зачем устраивать эскалацию? 

Что по поводу самих юбок... Почему бы вам не сходить на форум и устроить там голосование? 
Лично я считаю, что форма одежды на космическом корабле быть обязана. И она должна быть практичной, но юбки в эту категорию не входят вообще.

2020-10-26 17:15 UTC, Ayuska commented
> 
> 
> tl;dr
> 
> Ты знаешь что такое пропорции?
> ![изображение](https://user-images.githubusercontent.com/6051766/97204814-404e5580-17bf-11eb-81e5-5c0b26ac5b97.png)

Не убедительно, продолжим, у куклы человека нарушены пропорции, не правильно они передаются иными словами, может тебе такие словесные конструкции трудно читать, так что объясняю, ПРОПОРЦИИ У КУКЛЫ ИЗНАЧАЛЬНО НАРУШЕНЫ, это означает, что твое док-во мимо, продолжим наш цирк.

2020-10-26 17:16 UTC, Ayuska commented
> 
> 
> Извините, конечно, что вмешиваюсь в ваши увлекательные дискуссии и взаимные оскорбления, но намерен напомнить, что здесь не форум и разводить 90% воды в комментариях это не круто.
> 
> @Ayuska
> Юбки короткие и это факт. Либо исправь это, как того хочет департамент-одного-человека, либо это просто не примут. Ваши споры не приведут к консенсусу. Паспорт не покажу.
> 
> @TungstenOctopus
> Как и большинство местных, не стоит давить на детей и проявлять свою демонстративную власть. Конфликты не помогут решить проблему. Человек хочет свои юбки, ему уже сказали что не так, но он настаивает. Так зачем устраивать эскалацию?
> 
> Что по поводу самих юбок... Почему бы вам не сходить на форум и устроить там голосование?
> Лично я считаю, что форма одежды на космическом корабле быть обязана. И она должна быть практичной, но юбки в эту категорию не входят вообще.

Спасибо за твои ценные слова, если ты не понял, я не в серьез просил его паспорт, надеюсь, ты знаешь, что такое ирония и стеб.

2020-10-26 17:28 UTC, TungstenOctopus commented
>ИРЛ пропорции не применимы, ты оказался не прав.

Это твоя задача как спрайтера сделать так, чтоб твой спрайт хорошо выглядел. По твоему спрайту пока что видно, что юбка занимает не больше 2/3 бедра. Кукла может быть и хуевая, но это твоя проблема и твоя головная боль. Делай длинее, ищи нормальные пропорции.

2020-10-26 17:30 UTC, thgreatest commented
> > Извините, конечно, что вмешиваюсь в ваши увлекательные дискуссии и взаимные оскорбления, но намерен напомнить, что здесь не форум и разводить 90% воды в комментариях это не круто.
> > @Ayuska
> > Юбки короткие и это факт. Либо исправь это, как того хочет департамент-одного-человека, либо это просто не примут. Ваши споры не приведут к консенсусу. Паспорт не покажу.
> > @TungstenOctopus
> > Как и большинство местных, не стоит давить на детей и проявлять свою демонстративную власть. Конфликты не помогут решить проблему. Человек хочет свои юбки, ему уже сказали что не так, но он настаивает. Так зачем устраивать эскалацию?
> > Что по поводу самих юбок... Почему бы вам не сходить на форум и устроить там пасибо за твои ценные слова, если ты не понял, я не в серьез ил его паспорт, надеюсь, ты знаешь, что такое ирония и стеб.



> > Извините, конечно, что вмешиваюсь в ваши увлекательные дискуссии и взаимные оскорбления, но намерен напомнить, что здесь не форум и разводить 90% воды в комментариях это не круто.
> > @Ayuska
> > Юбки короткие и это факт. Либо исправь это, как того хочет департамент-одного-человека, либо это просто не примут. Ваши споры не приведут к консенсусу. Паспорт не покажу.
> > @TungstenOctopus
> > Как и большинство местных, не стоит давить на детей и проявлять свою демонстративную власть. Конфликты не помогут решить проблему. Человек хочет свои юбки, ему уже сказали что не так, но он настаивает. Так зачем устраивать эскалацию?
> > Что по поводу самих юбок... Почему бы вам не сходить на форум и устроить там голосование?
> > Лично я считаю, что форма одежды на космическом корабле быть обязана. И она должна быть практичной, но юбки в эту категорию не входят вообще.
> 
> Спасибо за твои ценные слова, если ты не понял, я не в серьез просил его паспорт, надеюсь, ты знаешь, что такое ирония и стеб.

Это ты
![IMG_20201026_192604_604](https://user-images.githubusercontent.com/73492048/97206701-bf448d80-17c1-11eb-9ab2-14c1e0ff0dbd.jpg)

2020-10-26 17:42 UTC, Ayuska commented
> > ИРЛ пропорции не применимы, ты оказался не прав.
> 
> Это твоя задача как спрайтера сделать так, чтоб твой спрайт хорошо выглядел. По твоему спрайту пока что видно, что юбка занимает не больше 2/3 бедра (+ она пышная, что не подъодит). Кукла может быть и хуевая, но это твоя проблема и твоя головная боль. Делай длинее, ищи нормальные пропорции.

Другими словами, ты не можешь доказать, что говорил полтора часа с серьезным лицом и не можешь признать поражения, у тебя точно не больное самомнение?




> 
> Это ты
> ![IMG_20201026_192604_604](https://user-images.githubusercontent.com/73492048/97206701-bf448d80-17c1-11eb-9ab2-14c1e0ff0dbd.jpg)

Мне жаль, что хрюшка не отличает иронии в тексте без интонации от серьезных слов, она не сможет понять, насколько иронично, что хрюшка сделала аккаунт, лишь бы показать какая она смешная и умеет кидать боевые картиночки.
![Screenshot_20201026-203519](https://user-images.githubusercontent.com/41844545/97208007-b48ef600-17cb-11eb-85f6-4f07eca3b110.jpg)
Хрюшке невдомек, что именно она на картинке.

2020-10-26 18:02 UTC, Kerzch commented
ПЛАЩ-ЮБКА

ПЛАЩ-ЮБКА
![image](https://user-images.githubusercontent.com/40739770/97210402-5966fe80-17df-11eb-8ef6-2d18b6906e72.png)

2020-10-26 18:03 UTC, TungstenOctopus commented
>Другими словами, ты не можешь доказать, что говорил полтора часа с серьезным лицом и не можешь признать поражения, у тебя точно не больное самомнение?

Другими словами, непропорционально короткие пышные юбки офицерам, капитанам и уборщикам не нужны. У нас не лоли-стейшен, а офицеры - не школьницы. Или делай нормальную длинну, или дальше срись, ругайся, выпрыгивай из штанов лишь бы доказать, что твои спрайты заебись.

2020-10-26 18:22 UTC, TauKitty commented
This pull request has been mentioned on **Tau Ceti Station Forum**. There might be relevant details there:

https://forum.taucetistation.org/t/kakie-dolzhny-byt-yubki-u-personala-stanczii/21896/1

2020-10-26 19:22 UTC, TungstenOctopus commented
Кстати да, как выше кинули, тут из-за пышности (уберите ее) всплыла проблем с тем, что юбка вылезает за пределы одежды в слоте suit

2020-10-28 11:27 UTC, Shudyn commented
У хосши же нормальное платье, и за куртку не вылезает. 
И юбка есть, и стиль официальный = почти все довольны.

2020-10-29 13:02 UTC, LudwigVonChesterfield commented
Споры о хрюшках, поражениях, и кто дурак вероятно не касаются девелопмента этого билда. Пожалуйста используйте другую платформу.

2021-01-04 19:49 UTC, T6751 commented
Похоже автора давно здесь не было. Пожалуй время закрыть ПР. Для переоткрытия ПРа можете обратиться к кому-либо из мейнтейнеров.

2021-01-04 19:49 UTC, closed without merging