robolimbs remastered
TauCetiStation/TauCetiClassic pull request #6304
Opened 2020-10-29 12:13 UTC by totallynotdedawa2

## Описание изменений
новые спрайты для протезов

![Screenshot_147](https://user-images.githubusercontent.com/61105647/97572343-26985280-19f9-11eb-8533-f287d3ba87aa.png)

![Screenshot_150](https://user-images.githubusercontent.com/61105647/97572356-27c97f80-19f9-11eb-9163-04bfd6631d35.png)

![Screenshot_151](https://user-images.githubusercontent.com/61105647/97572359-28621600-19f9-11eb-9896-e66e4aeb6418.png)

## Почему и что этот ПР улучшит
меньше старых спрайтов которые я не хочу
## Авторство

## Чеинжлог
:cl:
- image: респрайт робо-конечностей

2020-10-29 12:13 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2020-10-29 12:23 UTC, Pivo24 commented
блин кликбейт я думал разновидности протезов, дизлайк отписка :(

2020-10-29 12:24 UTC, totallynotdedawa2 commented
> блин кликбейт я думал разновидности протезов, дизлайк отписка :(

так это ремастер а не ремейк....

2020-10-29 12:29 UTC, KIBORG04 commented
это респрайт

2020-10-29 15:29 UTC, AirBlack commented
выглядит как лосины

2020-10-29 16:43 UTC, Kortez90 commented
> выглядит как лосины

Скорее как покрашенные баллончиком конечности человека.

2020-11-12 08:38 UTC, TungstenOctopus requested changes
Возможно стало даже хуже, но это не точно. Если и обновлять части тел, то только на более графонистые, здесь графона совсем нет

2021-01-04 19:49 UTC, T6751 commented
Похоже автора давно здесь не было. Пожалуй время закрыть ПР. Для переоткрытия ПРа можете обратиться к кому-либо из мейнтейнеров.

2021-01-04 19:49 UTC, closed without merging