some meadbay fixes
TauCetiStation/TauCetiClassic pull request #6310
Opened 2020-10-31 05:41 UTC by Lexakr

## Описание изменений
- Добавлено больше огнетушителей
- Пара консолей повернута в нужное направление
- Перепланировка, чтоб убрать тот самый цветок в углу. Несколько облегчено проникновение в отсек со стороны техов (по сложности теперь примерно как у СЕ). Было/стало
![image](https://user-images.githubusercontent.com/29842063/97771977-e362ee80-1b74-11eb-8b29-d4b364be788c.png)![image](https://user-images.githubusercontent.com/29842063/97772085-1c4f9300-1b76-11eb-9893-e086c91ce9cf.png)
- Доска объявлений около входа в медбей
- В операционных стало больше места, т.к сердечно-легочный аппарат переехал на место одного из столов, чтоб не мешаться. Скрины было/стало
![image](https://user-images.githubusercontent.com/29842063/97772109-5a4cb700-1b76-11eb-9d48-2861e9069550.png)![image](https://user-images.githubusercontent.com/29842063/97772091-31c4bd00-1b76-11eb-8077-6305af13cc03.png)
## Почему и что этот ПР улучшит

## Авторство
Lexakr
## Чеинжлог

2020-10-31 05:41 UTC, TauKitty commented
###### Changelog status: :radio_button: No changelog

2020-10-31 07:02 UTC, Kortez90 commented
Теперь эта непроходимая коробка будет мешать брать дрель.
Зачем вообще аппараты для реанимации и поддержания жизни в операционных существуют?


>     * Добавлено больше огнетушителей

Где?



>     * Пара консолей повернута в нужное направление

Какие-то консоли были повернуты не туда?

2020-10-31 08:02 UTC, 4310V343k commented
Спосибо!

2020-10-31 08:18 UTC, SvSvyat commented
> коробка будет мешать брать дрель

Каким образом...
> Зачем

Чтобы поддерживать жизнь в пациентах.

> Пара консолей повернута в нужное направление

В операционной не очень логично, там кнопки и через тело смотреть неудобно. В теории, перед ней должен стоять второй человек, отслеживающий состояние...

2020-10-31 08:57 UTC, Lexakr commented
> не очень логично, там кнопки и через тело смотреть неудобно.

По-моему на эту консоль просто смотрят, отслеживая состояние


> Где?

Checks

2020-11-01 09:31 UTC, Pivo24 commented
Слушай идея. А что если в офисе СМО убрать лишний стеклянный стол, что снизу от кресла, с медхудом и монитором датчиков, эти две вещи сунуть в шкаф, ноутбук поставить на место, где ты поставил картриджи, а картриджи назад на своё родное место?

А то как-то тяжело представляю ноутбук в офисе начальника, не находящийся за его столом, и это при отсутствии секретарей в его же офисе.

2020-11-01 09:40 UTC, Lexakr commented
> Слушай идея. А что если в офисе СМО убрать лишний стеклянный стол, что снизу от кресла, с медхудом и монитором датчиков, эти две вещи сунуть в шкаф, ноутбук поставить на место, где ты поставил картриджи, а картриджи назад на своё родное место?
> 
> А то как-то тяжело представляю ноутбук в офисе начальника, не находящийся за его столом, и это при отсутствии секретарей в его же офисе.

Как вариант, но тот ноут убран подальше, потому что эт employment records, консолька вообще не особо нужная в кабинете СМО (я даже не помню, имеет ли он к ней доступ)

2020-11-01 09:42 UTC, Pivo24 commented
> Как вариант, но тот ноут убран подальше, потому что эт employment records, консолька вообще не особо нужная в кабинете СМО (я даже не помню, имеет ли он к ней доступ)

Ну как это, конечно он имеет. Это консолька нужна СМО для просмотра резюме и личных дел работничков НТ, что бывает незаменимо при приёме на работу в отделы (сугубо для отыгрыша) или просмотра, чем там грешат твои собственные докторишки.

2020-11-01 10:39 UTC, ViDLiathan commented
Монитор датчиков лучше не убирать в шкаф, его иногда врачи реквизируют.
Консоль с данными персонала раз в год используется. Если она мозолит глаза, то лучше уж совсем убрать, чем захламлять стол

2020-11-12 17:21 UTC, T6751 requested changes
![image](https://user-images.githubusercontent.com/66636084/98973054-4d3fa880-2524-11eb-80ec-3468c82b62d6.png)

2020-11-13 03:41 UTC, Lexakr commented
Кабинет СМО вернул как было, консоли в операционных обе смотрят вниз

2020-12-12 17:08 UTC, Motzord commented
Когда мерж?

2020-12-12 17:52 UTC, LudwigVonChesterfield commented
Что вообще в этом ПР-е изменилось, а то ты кажется не обновлял описание, при том что менял вещи @Lexakr ?

Рекомендую тебе заполнить ченджлог

2020-12-12 18:00 UTC, Lexakr commented
> Что вообще в этом ПР-е изменилось, а то ты кажется не обновлял описание, при том что менял вещи @Lexakr ?
> 
> Рекомендую тебе заполнить ченджлог

Описание обновлял, убрал лишнее. Чейнжлог то написать можно, но там совсем минорные изменения. Основное что убрал это 
![image](https://user-images.githubusercontent.com/29842063/101991294-443a2680-3cde-11eb-9eff-27d43f080ee7.png)
Вроде других проблем для мержа не было

2020-12-13 10:09 UTC, merged