Обновление для мехов(Порт + пару фишек)
TauCetiStation/TauCetiClassic pull request #6313
Opened 2020-11-01 14:12 UTC by BiQndy

## Описание изменений
Добавлены action кнопки для мехов, которые позволят более удобно использовать возможности мехов.
Выглядит это дело так:
![show](https://user-images.githubusercontent.com/43725089/97805067-dfae9500-1c64-11eb-91df-4490f5473588.png)

Рассмотрим, что тут:
Белым отмечены кнопки, которые есть у Любого меха. Жёлтым - уникальные кнопки мехов, например, у Гигакса - кнопка ускорения, у Дюранда - кнопка режима защиты, у Фазона - кнопка включения phasing режима и тому подобное.
Теперь конкретней по белым кнопкам:
1) Кнопка выхода из меха.
2) Переключение режима вентилирования(Внешняя среда - внутренний танк)
3) Смена активного модуля.
4) Включение - выключение света.
5) Открытие меню.
6) (НОВОЕ) Переключение стрейф-режима: Стрейф режим позволяет зафиксировать взгляд меха, что позволяет, например, отступать и стрелять во врага, не делая лишних поворотов-разворотов мехом.
7) (НОВОЕ) Переключение внутренних двигателей - Разрешает передвижение в космосе. Учтите, двигаясь с этим режимом по космосу, затрата на каждое движение будет в три раза больше, чем обычно!
8) Специфичные кнопки мехов. Тут ничего нового.

Другие изменения:
 -Вход в меха теперь осуществляется переносом своего спрайта на спрайт Гигакса. (Как со стульями)
 -Во вкладке вверху справа "Exosuit Interface" оставлена только кнопка "View Stats", на случай, если что то пойдет не так.
![dreamseeker_2Ac8v4K3kw](https://user-images.githubusercontent.com/43725089/97805080-edfcb100-1c64-11eb-8d12-443647dc3d79.png)
-Фазон теперь спавнится без RCD-модуля.

## Почему и что этот ПР улучшит
Более удобный способ интерфейса.
## Авторство
В основном - TG station
## Чеинжлог
Скоро

2020-11-01 14:12 UTC, TauKitty commented
###### Changelog status: :radio_button: No changelog

2020-11-02 16:15 UTC, Pivo24 commented
Погоди, погоди, а thruster'ы, которые были у, не помню, Мародёра, они остались? Или теперь главная фишка Мародёра в том что он не очень будет в космосе?

2020-11-02 16:16 UTC, BiQndy commented
Трастеры у всех мехов

2020-11-02 17:14 UTC, 4310V343k commented
Тем изменением, что теперь трастеры у всех мехов, ты из QoL ПРа сделал ребаланс. Лучше сделай второй ПР после этого

2020-11-11 22:25 UTC, T6751 requested changes
**На счет трастеров**

На том же ТГ трастеры есть не у всех мехов, так что как и сказали выше, не уверен, что выдавать их всем мехам хорошая идея. Думаю, лучше оставить трастеры только мехам, у которых он был

---

> Во вкладке вверху справа "Exosuit Interface" оставлена только кнопка "View Stats", на случай, если что то пойдет не так.

Не думаю, что с action кнопками может что-то пойти не так, поэтому от вкладки можно смело отказаться

2020-11-11 22:25 UTC, T6751 commented on code/game/mecha/mecha_topic.dm
> +		src.log_message("Recalibration of coordination system failed with 1 error.", 1)
```suggestion
		src.log_message("Recalibration of coordination system failed with 1 error.", 1)

```

2020-11-11 22:25 UTC, T6751 commented on code/game/mecha/mecha_actions.dm
> +	chassis.occupant.update_action_buttons()
```suggestion
	chassis.occupant.update_action_buttons()

```

2020-11-11 22:25 UTC, T6751 commented on code/modules/client/client procs.dm
> +
```suggestion
```

2020-11-11 22:25 UTC, T6751 commented on code/game/mecha/combat/phazon.dm
> +	src.occupant_message("Melee damage type switched to <font color='[color_message]'>[new_damtype].</font>")
Можешь пройтись убрать все ```src.``` где они не нужны, пожалуйста
```suggestion
	occupant_message("Melee damage type switched to <font color='[color_message]'>[new_damtype].</font>")
```

2020-11-12 19:23 UTC, BiQndy commented
Доработал сказанное, так же Трастеры теперь только у подтипов Мародёра.

2020-12-13 10:18 UTC, T6751 requested changes
Добавь чеинжлог, пожалуйста

В целом, всё хорошо, но на всякий случай Тестмерж

2020-12-13 10:28 UTC, BiQndy commented
Готово, нормальный чейнжлог?

2020-12-13 10:30 UTC, T6751 commented
> 
> 
> Готово, нормальный чейнжлог?

Я бы сделал как-то так:
```
 - rscadd: Вкладка у мехов "Exosuit Interface" заменена Action кнопками
 - tweak: чтобы войти в мех теперь нужно перетащить свой спрайт на мех, как со стульями
```

2020-12-24 10:29 UTC, T6751 approved these changes

2020-12-24 10:32 UTC, merged