Guns re-sprite (again)
TauCetiStation/TauCetiClassic pull request #6336
Opened 2020-11-08 07:01 UTC by totallynotdedawa2

## Описание изменений
Л6 пила, патроны на дробовик, патроны для ПТР получили новые спрайты

![image](https://user-images.githubusercontent.com/61105647/98459178-45d97180-21a9-11eb-9011-24a6b4145292.png)

![image](https://user-images.githubusercontent.com/61105647/98459182-4f62d980-21a9-11eb-8149-e8bc1caf254b.png)

![Screenshot_221](https://user-images.githubusercontent.com/61105647/98459169-36f2bf00-21a9-11eb-972e-b464876f4e6a.png)

## Почему и что этот ПР улучшит
Еще меньше старых спрайтов которые мне не нравятся
## Авторство
пулемет - gammastation
патроны для дробовика - watlerje
## Чеинжлог
:cl:
- image: Респрайтнуты л6 пила, патроны для птр и дробовика

2020-11-08 07:01 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2020-11-08 09:44 UTC, Kortez90 commented
Пуля ПТР похожа на "Stielhandgranate". Да и L6 SAW в руке выглядел лучше, чем до респрайта.

2020-11-08 11:52 UTC, WatlerJe commented
Bruh, в файле же уже есть нормальные гильзы (как у пистолета). 
![image](https://user-images.githubusercontent.com/19796920/98464114-9ebd0000-21d1-11eb-9eda-751e2bc7e512.png)

Да и запилил бы еще механ прутков для патронов, как на маринах где можно грабать их кучкой сразу, что очень круто. ЯХЗ как у вас сейчас, но раньше одна пулька 12 кал занимала целый слот в кармане броника/разгрузки.

2020-11-08 12:03 UTC, totallynotdedawa2 commented
Не было файла, приходилось импровизировать с гильзами для дробовика

механ патронных куч постараюсь сделать позже, но не в этом пре

2020-11-08 12:12 UTC, WatlerJe commented
Пиши свой дискок свой, скину туда.

2020-11-08 17:04 UTC, Motzord commented
Мне не нравится что от потраченных гильз 12 калибра остается лишь основа патрона, а не полная гильзы.

2020-11-12 08:36 UTC, TungstenOctopus requested changes
По-порядку:
Патроны для дробовика - ок, красиво.
Патроны для пулемета: плохо, по сравнению со старыми стало хуже. 
Пулемет: сам корпус стал графонистей, а вот тот же магазин выглядит тухло и блекло. Если и заменять, то взять хорошее из нового и перенести в старый.

2021-01-04 19:49 UTC, T6751 commented
Похоже автора давно здесь не было. Пожалуй время закрыть ПР. Для переоткрытия ПРа можете обратиться к кому-либо из мейнтейнеров.

2021-01-04 19:49 UTC, closed without merging