[WIP] Педальные анонсы с кастомным звуком
TauCetiStation/TauCetiClassic pull request #6367
Opened 2020-11-14 18:04 UTC by atik1n

## Описание изменений
Возможность выбрать звуки из билда и даже загрузить свои для анонсов
## Почему и что этот ПР улучшит
УдОбСтВо и фейковые анонсы режимов
## Чеинжлог
Он тут не нужен

2020-11-14 18:04 UTC, TauKitty commented
###### Changelog status: :radio_button: No changelog

2020-11-15 02:30 UTC, ViDLiathan commented
Шах и мат!
Выкусите, космонавтики.

2020-11-15 12:47 UTC, atik1n commented
@T6751, @KIBORG04, я всё ещё не понимаю, что я делаю не так
У меня всё ещё просто белый экран при текущих изменениях

2020-11-16 11:11 UTC, KIBORG04 commented
Может ты че-то недоустановил? Вроде, все должно работать. 
![image](https://user-images.githubusercontent.com/26389417/99245966-8e320880-2815-11eb-8c78-b5bddcf9e349.png)

2020-11-21 02:28 UTC, atik1n commented
Всё, ПР готов. Если можно, повесьте флажок Refactor

2020-11-21 13:30 UTC, KIBORG04 commented on code/modules/admin/secrets/secrets_menu.dm
> +    var/name = "KitchenSink"
Может тут что-то другое должно быть?

2020-11-21 13:30 UTC, KIBORG04 commented on code/modules/mob/mob.dm
> +	var/datum/secrets_menu/custom_announce/sm_ca
А зачем оставлять ссылку на аннонс в мобе?

2020-11-21 13:31 UTC, atik1n commented on code/modules/admin/secrets/secrets_menu.dm
> +    var/name = "KitchenSink"
Это просто заготовка, чтобы на её основе делать уже другое. Просто чтобы открывалось хоть что-то даже при тесте по дефолту установлен `KitchenSink`

2020-11-21 13:31 UTC, atik1n commented on code/modules/mob/mob.dm
> +	var/datum/secrets_menu/custom_announce/sm_ca
Это на окно tgui. Окно хранится в мобе.
Я сейчас попробую перенести в `holder`, конечно

2020-11-21 13:32 UTC, KIBORG04 commented on code/modules/paperwork/announcements.dm
> +	flags = ANNOUNCE_SOUND
```suggestion
	flags = ANNOUNCE_SOUND
	
```

2020-11-21 13:32 UTC, KIBORG04 commented on code/modules/paperwork/announcements.dm
> +/var/datum/announcement/announcement_ping = new /datum/announcement/ping // For sound-only
```suggestion

var/datum/announcement/announcement_ping = new /datum/announcement/ping // For sound-only
```

2020-11-21 13:33 UTC, KIBORG04 commented on code/modules/paperwork/announcements.dm
> +	flags = ANNOUNCE_SOUND
Типо, для читабельности так соединять?

2020-11-21 13:34 UTC, atik1n commented on code/modules/paperwork/announcements.dm
> +	flags = ANNOUNCE_SOUND
В этом и был смысл, да

2020-11-21 13:37 UTC, KIBORG04 commented on code/modules/mob/mob.dm
> +	var/datum/secrets_menu/custom_announce/sm_ca
Только у тебя оно все равно будет каждый раз новое создаваться. `ui` не передается как аргумент, а значит каждый раз новое окно. Не вижу большой разницы создавать новый класс вместе с окном и создавать окно
```
/datum/secrets_menu/proc/interact()
	tgui_interact(admin)

/datum/secrets_menu/tgui_interact(mob/user, datum/tgui/ui)
    ui = SStgui.try_update_ui(user, src, ui)
    if(!ui)
        ui = new(user, src, name, title)
        tgui_ui = ui
        ui.open()
```

2020-11-21 14:27 UTC, atik1n commented
Перетащил список всех окон для секретов (сейчас только одно, ну да ладно) в `/datum/admins`, это чуть логичнее

2020-11-30 17:51 UTC, atik1n commented
Если что, этот ПР абсолютно независим от ПРа с топиклимитером

2020-12-05 16:59 UTC, atik1n commented
Активность есть, просто активности нет

2020-12-11 15:50 UTC, kiVts commented
Как аплоад работает?

2020-12-11 15:52 UTC, kiVts commented
Если как я думаю, то пиздец будет что, педали будут вставлять что не пойми, многие будут только своими звуками и пользоватся

2020-12-12 14:22 UTC, atik1n commented
> Если как я думаю, то пиздец будет что, педали будут вставлять что не пойми, многие будут только своими звуками и пользоватся

Не так много админов владеют +SOUND, а ещё как сказано в Play Global Sound - "за злоупотребление может последовать UNPEDALITY"

2020-12-23 22:41 UTC, T6751 requested changes
В целом проделана очень хорошая работа. Но нужно ещё немного доработать:

2020-12-24 12:00 UTC, atik1n commented on code/modules/admin/secrets/secrets_menu.dm
> +	var/datum/tgui_window/tgui_window
Это было сделано с заделом на будущее, мол если ещё будем добавлять tgui-like секреты. Но пока могу убрать

2020-12-24 12:25 UTC, atik1n commented on code/modules/admin/secrets.dm
> +	var/datum/announcement/announce_override = new /datum/announcement/centcomm/access_override
Я пытаюсь понять для чего, хм. Чтобы не создавать в каждом новом экземпляре админа?

2020-12-24 13:19 UTC, LudwigVonChesterfield commented on code/modules/admin/secrets.dm
> +	var/datum/announcement/announce_override = new /datum/announcement/centcomm/access_override
именно так

2020-12-24 13:19 UTC, LudwigVonChesterfield commented on code/modules/admin/secrets/secrets_menu.dm
> +	var/datum/tgui_window/tgui_window
думаю что когда прибудет будущее одну переменную добавить смогут

2020-12-24 13:20 UTC, atik1n commented on code/modules/admin/secrets.dm
> +	var/datum/announcement/announce_override = new /datum/announcement/centcomm/access_override
Отлично

2020-12-24 14:16 UTC, T6751 requested changes

2020-12-24 14:16 UTC, T6751 commented on code/modules/admin/secrets/secrets_menu/custom_announcement.dm
> +			announcement_sounds_cache[user_input] = S
В теории админ может вписать сюда любое название типа "red", "green", тем самым заменив стандартный звук анонса на свой. Думаю стоит добавить проверку, что имя уже занято и предложить ввести другое имя для звука

2020-12-24 14:16 UTC, T6751 commented on code/modules/admin/secrets/secrets_menu/custom_announcement.dm
> +				WARNING("No sound file for [sound_name]")
```
## WARNING: No sound file for Scare in code/modules/admin/secrets/secrets_menu/custom_announcement.dm at line 90 src: CustomAnnounce usr: Isaac Reighner.
```
После загрузки звука (sound_upload) и попытки проиграть анонс (test) - выводит **варнинг**. Однако если затем выбрать добавленный звук (sound_select), то всё хорошо

2020-12-24 17:54 UTC, atik1n commented on code/modules/admin/secrets/secrets_menu/custom_announcement.dm
> +			announcement_sounds_cache[user_input] = S
Хм. С учётом того, что это доступно только с +SOUND, не виду ничего странного
Но могу убрать

2020-12-25 00:24 UTC, T6751 commented on code/modules/admin/secrets/secrets_menu/custom_announcement.dm
> +			var/user_input = input(ui.user, "Choose a sound for announce.", "Sound", A.sound) as anything in variants
```suggestion
			var/user_input = input(ui.user, "Choose a sound for announce.", "Sound", A.sound) as anything in sortList(variants)
```

2020-12-25 14:41 UTC, T6751 approved these changes

2020-12-28 17:21 UTC, merged