Бутылочки разбиваются при броске.
TauCetiStation/TauCetiClassic pull request #6378
Opened 2020-11-17 14:14 UTC by Kortez90

## Описание изменений
Если метать бутылки, то они с шансом 50% разобьются и разольют содержимое.
## Почему и что этот ПР улучшит
Больше реалистичности.
## Авторство

## Чеинжлог
:cl: Kortez90
 - tweak: Бутылочки разбиваются при броске.

2020-11-17 14:14 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2020-11-17 17:53 UTC, notanennx commented
Но ведь реализм это не значит "лучше", да и какую проблему оно решает?

Химики которые бросают банки сразу на стол выдачи, потому что им лень ходить? Но ведь это выглядит круто, если бы банки влетали в руку, если целишься и бросаешь в незанятую руку, было бы еще круче.

Куча банок, которые разбросаны по медбею к середине игры? Но они ведь и так пустые, их никто больше не возьмет, да и доктора считают их за мусор. Плюс если банки с лейблами, то в каких-то редких случаях они вообще могут стать уликой.

Вообще я примерно понимаю зачем добавлен такой шанс (врачи-гренадёры с хлором и слиптоксином, врачи-ультрасы, которые увидев раненого бросают в него коктейль из всех лекарств), но не лучше тогда придумать альтернативу 50%ому шансу на разбивание? Например какой-нибудь квирк, который сделает так, чтобы те бутылки и листы стекла, которые бросаешь - не бились. Это было бы приятной и удобной мелочью, для  некоторых барменов/химиков/инженеров/врачей, но и не маст-хэв квирком для них.

2020-11-17 18:24 UTC, Kortez90 commented
> Но ведь это выглядит круто, если бы банки влетали в руку, если целишься и бросаешь в незанятую руку, было бы еще круче.

Ловить пустой рукой и так можно, если включено метание.

2020-11-17 20:08 UTC, Motzord commented on code/modules/reagents/reagent_containers/glass/bottle.dm
> +		new /obj/item/weapon/shard(loc)
И тут мы переходим к интересной "фиче" конкретно с этой строки. Фарм стекла, ведь химику никто не запрещает наклепать, внезапно 100500 миллионов пустых колб и начать разбивать превращая в осколки и раздавая например карго или ученым  для заправки автолата, если не наглым свариванием в листы. Нужен ли очередной абуз? Определенно нет

2020-11-17 20:10 UTC, Kortez90 commented on code/modules/reagents/reagent_containers/glass/bottle.dm
> +		new /obj/item/weapon/shard(loc)
Там спавнится один осколок. Ты будешь сидеть в химии и спавнить воду в раздатчике, разряжая его, ради 50 бутылок?

2020-11-17 20:15 UTC, Motzord commented on code/modules/reagents/reagent_containers/glass/bottle.dm
> +		new /obj/item/weapon/shard(loc)
> Там спавнится один осколок. Ты будешь сидеть в химии и спавнить воду в раздатчике, разряжая его, ради 50 бутылок?

мне нужно разряжать раздатчик ведь я могу просто закликивать кнопку и спавнить пустые бутылки

2020-11-17 20:17 UTC, Kortez90 commented on code/modules/reagents/reagent_containers/glass/bottle.dm
> +		new /obj/item/weapon/shard(loc)
Значит надо запретить создавать бесконечное кол-во бутылок. Об этом я где-то уже писал, около полугода тому назад. Во всяком случае, это тема для другого ПР.

2020-11-19 07:05 UTC, LudwigVonChesterfield commented on code/modules/reagents/reagent_containers/glass/bottle.dm
> +		new /obj/item/weapon/shard(loc)
Я уверен что это в любом случае малая проблема учитывая существующие дюпы с карго, дюпы плат шлюз, и т.д. ...

У нас вроде бы не было курса на подобную борьбу с дюпами

2020-11-19 07:14 UTC, LudwigVonChesterfield commented
@notanennx @Kortez90 

не знаю насколько хорошая идея, но прецедент уже есть, так что в теории можно было бы в бросок сохранять интент бросающего, и если интент == хелп то ты как-то "аккуратно" бросаешь чтобы бутылочка не разбилась, к примеру.

2020-11-19 07:15 UTC, LudwigVonChesterfield commented
> Ловить пустой рукой и так можно, если включено метание.

У нас нет этой фичи

2020-11-19 07:51 UTC, Kortez90 commented
> если интент == хелп то ты как-то "аккуратно" бросаешь чтобы бутылочка не разбилась, к примеру.

Лучше разбить на интенты - `HELP` - 10%, `HARM` - 90%.

2020-11-19 07:55 UTC, LudwigVonChesterfield commented
А мне вообще не нравятся эти проценты. Если я хочу бросить бутылку и не разбить - я выбираю хелп, бросаю, и не разбиваю. Всё ожидаемо, а не я бросил - она разбилась, и ещё разбилась, и ещё, и я бегу, кричу что Кортез меня поместил в скрытый пул и что ничего не работает, хелп разбивает.

2020-11-19 11:19 UTC, Kortez90 commented
В процентах нет ничего страшного. Просто нельзя кидать бутылки на твердый пол, не разбивая их.
А тут вообще шанс 50%, что довольно много.
Впрочем, если так хочется, то можно и интент зацепить, но только если подскажешь, как подцепить `a_intent` к кидающему мобу внутри прока. У меня он постоянно `null`, перепробовал кучу вариантов, в том числе и всякие `throw_at`.

2020-11-19 18:00 UTC, cool20141 commented
Хуевая идея, за химика неудобно играть будет

2020-11-19 19:27 UTC, Motzord commented on code/modules/reagents/reagent_containers/glass/bottle.dm
> +		new /obj/item/weapon/shard(loc)
> У нас вроде бы не было курса на подобную борьбу с дюпами

Но это не значит что их надо плодить, чтобы были причины начать этот курс, верно?

2020-11-19 19:51 UTC, CeUvi commented
Во-первых, зачем?
Во-вторых, возможно стоит сделать, чтобы при броске на хелпе бутылка не разбивалась, а при броске на харме разбивалась (и может быть могла покрывать людей реагентом).
В-третьих, проценты это shit.

2020-11-20 10:55 UTC, ViDLiathan commented
Фичи, которые никто не просил.
Бутылочкам химика такое точно не нужно.

2020-11-24 11:32 UTC, LudwigVonChesterfield commented
> Впрочем, если так хочется, то можно и интент зацепить, но только если подскажешь, как подцепить a_intent к кидающему мобу внутри прока. У меня он постоянно null, перепробовал кучу вариантов, в том числе и всякие throw_at.

Сохраняй у datum/thrownthing интент.

2021-01-08 12:10 UTC, T6751 requested changes
Соглашаясь с Людуком, лучше, если у игрока будут предсказуемые действия на Хелп и Харм вместо рандома. 
На счёт дюпа стекла, то думаю будет нормально просто убрать спавн осколка.

2021-01-08 12:15 UTC, Kortez90 commented
Тогда и смысла нет.

2021-01-08 12:15 UTC, closed without merging

2021-01-08 12:15 UTC, FelixRuin commented
категоричненько