Объединение IPC_change_screen и IPC_toggle_screen().
TauCetiStation/TauCetiClassic pull request #6383
Opened 2020-11-18 08:45 UTC by Kortez90

## Описание изменений
Склеил из двух проков один, но пришлось добавить две переменные для хранения предыдущих выборов причесок и цветов игроков.
## Почему и что этот ПР улучшит
Избавление от лишних вербов.
## Авторство

## Чеинжлог
:cl: Kortez90
 - tweak: Изменен верб смены изображения монитора для IPC.

2020-11-18 08:45 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2020-11-18 10:27 UTC, FelixRuin commented
не особо вдавался в подробности, но может тогда лучше переменные на голову поставить, чтобне мусорить и так уже полной переменными хуманов

2021-01-04 19:06 UTC, T6751 requested changes

2021-01-04 19:06 UTC, T6751 commented on code/modules/mob/living/carbon/human/human.dm
> +		if("Toggle On/Off")
Если выключить экран (Toggle On/Off), затем установить изображение экрана ("Change screen style"), по идее включив экран, и снова попытаться выключить экран (Toggle On/Off) - он останется включенным

И думаю лучше вынести это в отдельный верб, а не объединять в алерт. Так будет проще создать хоткеи для этих вербов в случае чего

2021-01-04 19:12 UTC, closed without merging