Clothing new order
TauCetiStation/TauCetiClassic pull request #6384
Opened 2020-11-18 09:16 UTC by totallynotdedawa2

## Описание изменений
респрайтнуты цветные комбинезоны и ботинки

![image](https://user-images.githubusercontent.com/61105647/99508945-38389e80-2996-11eb-8bde-7c5585d789d8.png)
![image](https://user-images.githubusercontent.com/61105647/99510122-b5184800-2997-11eb-8c39-32bda61cc5d8.png)

так же, теперь есть feminine версии для всех комбинезонов, а не только для черного

![image](https://user-images.githubusercontent.com/61105647/99509686-25729980-2997-11eb-8061-90a6e6f068b6.png)

## Почему и что этот ПР улучшит
меньше старых спрайтов которые мне не нравятся
## Авторство
комбинезоны - watlerje
## Чеинжлог
:cl:
- image: Респрайт комбинезонов и ботинок

2020-11-18 09:16 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2020-11-18 09:28 UTC, KIBORG04 commented on code/game/machinery/washing_machine.dm
> +			/*var/new_jumpsuit_icon_state = ""
Зачем комментировать код?

2020-11-18 09:34 UTC, Kortez90 commented
А зачем было удалять одежду для переевших?

2020-11-18 09:35 UTC, SpaiR requested changes
Мне нравится, как ты закоментировал код, с которым, судя по дискорду не сумел разобраться, убрав конкретную фунциональность и при этом выдаешь ПР за обыный респрайт. (нет)

2020-11-20 08:15 UTC, totallynotdedawa2 commented
@SpaiR  переделано, теперь стиральная машина красит одежду

2020-12-05 15:16 UTC, LudwigVonChesterfield commented on code/game/machinery/washing_machine.dm
> +			C.color = wash_color
А это точно нормально выглядит в игре?

2020-12-05 15:17 UTC, LudwigVonChesterfield commented on code/game/machinery/washing_machine.dm
> +		if (istype (C, /obj/item/clothing/under))
А почему если что-то не может быть покрашено(выше проверка на C.can_be_colored) то оно все равно насильно красится и меняет спрайт?

И почему механ не такой же как у тех вещей что таки красятся?

И эту лесенку можно было бы схлопнуть добавив colored_item_state

2020-12-05 15:17 UTC, LudwigVonChesterfield commented on code/game/machinery/washing_machine.dm
> +		if(C.can_be_colored == TRUE)
```suggestion
		if(C.can_be_colored)
```

2020-12-05 15:18 UTC, LudwigVonChesterfield commented on code/game/machinery/washing_machine.dm
>  			to_chat(user, "<span class='notice'>\The [W] is stuck to your hand, you cannot put it in the washing machine!</span>")
```suggestion
			to_chat(user, "<span class='notice'>\The [C] is stuck to your hand, you cannot put it in the washing machine!</span>")
```

2020-12-05 15:55 UTC, totallynotdedawa2 commented on code/game/machinery/washing_machine.dm
> +			C.color = wash_color
![image](https://user-images.githubusercontent.com/61105647/101247523-26dbea00-372b-11eb-9a30-fa2adb7541da.png)
![image](https://user-images.githubusercontent.com/61105647/101247567-568af200-372b-11eb-87aa-2141f3e24edb.png)

2021-01-19 00:38 UTC, closed without merging