Фикс спама ИИ анонсами.
TauCetiStation/TauCetiClassic pull request #6386
Opened 2020-11-18 12:45 UTC by Kortez90

## Описание изменений
Переместил переключатель выше `input`, чтобы новые окна больше нельзя было открыть. Соответственно, если нажать на кнопку анонса - придется ждать `spawn(600)`, чтобы снова его открыть, даже если в окне ничего не было написано или отправлено.
## Почему и что этот ПР улучшит
Fix #6385.
## Авторство

## Чеинжлог
:cl: Kortez90
 - bugfix: Больше нельзя спамить анонсами ИИ.

2020-11-18 12:45 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2020-11-23 19:26 UTC, LudwigVonChesterfield commented on code/modules/mob/living/silicon/ai/ai.dm
> +		if(!input)
В чем смысл объявлять пустую переменную, потом проверять пустая ли она если нельзя спаммить, а потом её наполнять?

Предлагаю следующую структуру
```
if(check_input)
  низя
  check_input = FALSE
  return

check_input = TRUE
input = блаблабла

if(!input)
  return
```

2020-11-23 21:19 UTC, Kortez90 commented on code/modules/mob/living/silicon/ai/ai.dm
> +		if(!input)
При такой структуре, когда окно откроют в первый раз `check_input` будет `TRUE`, но если нажать еще раз, то проскочит сообщение и будет `FALSE`, что позволит открыть еще одно окно.

2020-11-24 09:23 UTC, LudwigVonChesterfield commented on code/modules/mob/living/silicon/ai/ai.dm
> +		if(!input)
А у тебя сейчас не так же?

Ты объявляешь переменную var/input в рамках функции заново, а не хранишь её значение, она у тебя всегда null на момент проверки if(check_input) if(!input)

2020-11-24 09:50 UTC, Kortez90 commented on code/modules/mob/living/silicon/ai/ai.dm
> +		if(!input)
Когда окно открыто, `check_input` становится `TRUE` и когда закрыто, `input` становится `FALSE`, что выключает `check_input`, позволяя заново открыть окно, но только одно.

2020-11-24 10:03 UTC, Kortez90 commented on code/modules/mob/living/silicon/ai/ai.dm
> +		if(!input)
К слову, этот же эксплойт работает с сообщениями ЦК.

2021-01-04 19:27 UTC, T6751 commented on code/modules/mob/living/silicon/ai/ai.dm
> +		input = sanitize(input(usr, "Please write a message to announce to the station crew.", "A.I. Announcement") as null|message)
Если во время инпута ИИ выйдет из игры, то сможет ли он слать анонсы, когда снова вернётся?

Думаю можно просто добавить проверку кулдауна после инпута и всё, а остальное убрать

```
if(message_cooldown)
  return
var/input = sanitize(input(...))
if(message_cooldown)
  return
```

2021-01-04 19:28 UTC, T6751 requested changes
см. выше

2021-01-04 19:30 UTC, Kortez90 commented on code/modules/mob/living/silicon/ai/ai.dm
> +		input = sanitize(input(usr, "Please write a message to announce to the station crew.", "A.I. Announcement") as null|message)
Только вот `message_cooldown` будет `FALSE`, так как отправки не было и эксплойт никуда не денется.

2021-01-04 19:33 UTC, T6751 commented on code/modules/mob/living/silicon/ai/ai.dm
> +		input = sanitize(input(usr, "Please write a message to announce to the station crew.", "A.I. Announcement") as null|message)
После первой отправки message_cooldown будет TRUE. Что значит, что остальные настаканные инпуты не пройдут второю проверку кулдауна же

2021-01-04 19:57 UTC, T6751 approved these changes
Работает

2021-01-04 19:58 UTC, merged