Возможность вывалить вещи на пол перетаскиванием.
TauCetiStation/TauCetiClassic pull request #6394
Opened 2020-11-21 12:47 UTC by Kortez90

## Описание изменений
Перетащив контейнер(Сумки, коробки и так далее.) на пол, можно относительно быстро все из него вывалить. Кол-во вещей увеличивает время извлечения, так как объекты вытаскиваются по одному. Навалить кучу на космос нельзя.
![GIF 21 11 2020 15-36-26](https://user-images.githubusercontent.com/36198983/99877555-22361280-2c10-11eb-93db-59cabd22fec3.gif)

Драфт, потому что нужен фидбек по поводу кода и его чистка. Из-за прекрасного цикла `while` была небольшая проблема. К тому же, я не уверен, что лучше использовать `get_dist()` или `(src in view)`. Дополнительные проверки возвратов, например кравла, если нужны, то скажите какие и где. Ну и багхантинг, соответственно. Возможно какой-то эксплойт с выкладкой каких-нибудь пирожков из закрытых сумок ускользнул.
## Почему и что этот ПР улучшит
Более удобное извлечение предметов. Космонавты будут рады.
## Авторство

## Чеинжлог
:cl: Kortez90
 - tweak: Перетащив сумку на пол, можно вывалить из нее все предметы.

2020-11-21 12:47 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2020-11-21 13:38 UTC, Zmey25 commented
Вот блин, так и вижу как грязный волкер вываливает все мои вещи на пол и убегает ололо дальше стрелять по кому-то, а мне потом собирать

2020-11-21 13:40 UTC, KIBORG04 commented on code/game/turfs/simulated/floor.dm
> +				if(src in view(1, user))
`if(src in view(1, user))`

Нету ведь смысла дублировать этот иф

2020-11-21 13:41 UTC, KIBORG04 commented on code/game/turfs/simulated/floor.dm
> +					for(var/obj/item/I in S.contents)
Тогда вообще вайл, если все можно под этот фор перенести?

2020-11-21 13:42 UTC, Kortez90 commented
> а мне потом собирать

Я собирался сделать и сборку, но позже. Вроде, в тг такая фича была.

2020-11-21 13:43 UTC, Kortez90 commented on code/game/turfs/simulated/floor.dm
> +					for(var/obj/item/I in S.contents)
Потому что тогда все предметы перепрыгнут сразу, а не по одному.

2020-11-21 13:43 UTC, KIBORG04 commented on code/game/turfs/simulated/floor.dm
> +					for(var/obj/item/I in S.contents)
Если я не ошибаюсь, у вайла будет всего одна итерация

2020-11-21 13:46 UTC, Kortez90 commented on code/game/turfs/simulated/floor.dm
> +				if(src in view(1, user))
Разве без этого `if` прекрасный `while` не пойдет кругами проверять содержимое сумки, вызывая `do_after`?

2020-11-21 13:49 UTC, KIBORG04 commented on code/game/turfs/simulated/floor.dm
> +				if(src in view(1, user))
```
			while((S.contents.len > 0) && (src in view(1, user)))
				if(src in view(1, user))
```
В заголовке вайла уже указана эта проверка, оно дублируется. Темболее ты в `else` этого ифа ставишь брик, то есть просто дублируешь то же, что и в вайле

2020-11-21 13:52 UTC, Kortez90 commented on code/game/turfs/simulated/floor.dm
> +					for(var/obj/item/I in S.contents)
Окей, спасибо. Я проверю.

2020-11-21 15:01 UTC, KIBORG04 commented
> tweak: Перетащив сумку на пол, можно вывалить из нее все предметы.

Упомяни хелп-интент

2020-11-21 15:02 UTC, KIBORG04 commented on code/game/turfs/simulated/floor.dm
> +	if(istype(C, /obj/item/weapon/storage))
Может сделать также как и ниже, то есть:
```
if(!istype(C, /obj/item/weapon/storage))
    return
```

2020-11-21 15:04 UTC, KIBORG04 commented on code/game/turfs/simulated/floor.dm
> +		if(get_dist(user, C) > 1 || get_dist(user, src) > 1 || !(src in view(1, user)))
Возможно, все стоит заменить на прок in_range(), включая src in view(1, user) тут и ниже

2020-11-21 15:06 UTC, KIBORG04 commented on code/game/turfs/simulated/floor.dm
> +		if(get_dist(user, C) > 1 || get_dist(user, src) > 1 || !(src in view(1, user)))
Хотя, я хз немного о том, как работает `src in view(1, user)`

2020-11-21 15:10 UTC, 4310V343k commented
А ещё лучше на Adjacent ()

сб, 21 нояб. 2020 г., 18:05 KIBORG04 <notifications@github.com>:

> *@KIBORG04* commented on this pull request.
> ------------------------------
>
> In code/game/turfs/simulated/floor.dm
> <https://github.com/TauCetiStation/TauCetiClassic/pull/6394#discussion_r528205834>
> :
>
> > @@ -642,6 +642,25 @@ var/list/wood_icons = list("wood","wood-broken")
>
>  				else
>
>  					to_chat(user, "<span class='notice'>You need more welding fuel to complete this task.</span>")
>
>
>
> +/turf/simulated/floor/MouseDrop_T(obj/item/C, mob/user)
>
> +
>
> +	if(istype(C, /obj/item/weapon/storage))
>
> +		if(user.incapacitated())
>
> +			return
>
> +		if(get_dist(user, C) > 1 || get_dist(user, src) > 1 || !(src in view(1, user)))
>
>
> Возможно, все стоит заменить на прок in_range(), включая src in view(1,
> user) тут и ниже
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/TauCetiStation/TauCetiClassic/pull/6394#pullrequestreview-535972172>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ANOVVYYNR4DPJYH5RKVKLP3SQ7JKLANCNFSM4T5YR74A>
> .
>

2020-11-21 15:13 UTC, 4310V343k commented on code/game/turfs/simulated/floor.dm
> +		if(get_dist(user, C) > 1 || get_dist(user, src) > 1 || !(src in view(1, user)))
> Возможно, все стоит заменить на прок in_range(), включая src in view(1, user) тут и ниже

Для всего этого можно использовать Adjacent()
Я сейчас с телефона, но у меня такое ощущение что опустошать контейнеры можно сквозь стекло

2020-11-21 15:14 UTC, Kortez90 commented on code/game/turfs/simulated/floor.dm
> +	if(istype(C, /obj/item/weapon/storage))
А... Зачем? Предыдущая цепочка проверок работает через проверку типа. Или о чем речь?

2020-11-21 15:16 UTC, 4310V343k commented on code/game/turfs/simulated/floor.dm
> +	if(istype(C, /obj/item/weapon/storage))
Нет лишних табов, и выглядит красивее

2020-11-21 15:17 UTC, 4310V343k commented on code/game/turfs/simulated/floor.dm
> +	if(istype(C, /obj/item/weapon/storage))
Стоп
Киборг, а что если надо будет добавить ещё какой-нибудь предмет?
Из-за return нужно будет переделывать все

2020-11-21 15:23 UTC, 4310V343k commented on code/game/turfs/simulated/floor.dm
> +		if(get_dist(user, C) > 1 || get_dist(user, src) > 1 || !(src in view(1, user)))
```suggestion
		if(!user.Adjacent(C) || !src.Adjacent(C) || !src.Adjacent(user))
```
По желанию в ущерб читабельности убрать src.
И табы могли наебнуться из-за сагов с телефона

2020-11-21 15:23 UTC, 4310V343k commented on code/game/turfs/simulated/floor.dm
> +				if(do_after(user, 2, target = user) && (src in view(1, user)))
Adjacent()

2020-11-21 15:24 UTC, KIBORG04 commented on code/game/turfs/simulated/floor.dm
> +	if(istype(C, /obj/item/weapon/storage))
> Киборг, а что если надо будет добавить ещё какой-нибудь предмет?

Ну да, но сейчас же все основывается на сторейдже.

2020-11-21 15:24 UTC, Kortez90 commented on code/game/turfs/simulated/floor.dm
> +				if(do_after(user, 2, target = user) && (src in view(1, user)))
Уже проверяю. Спасибо.

2020-11-21 15:31 UTC, Kortez90 commented on code/game/turfs/simulated/floor.dm
> +		if(get_dist(user, C) > 1 || get_dist(user, src) > 1 || !(src in view(1, user)))
По поводу стекла не уверен, но на консоли, машинеру и вендоматы можно выкладывать.

2020-11-21 15:31 UTC, 4310V343k commented on code/game/turfs/simulated/floor.dm
> +	if(istype(C, /obj/item/weapon/storage))
> > Киборг, а что если надо будет добавить ещё какой-нибудь предмет?
> 
> Ну да, но сейчас же все основывается на сторейдже.

А потом не будет
Давай сразу делать так, что бы в будущем легче было делать новое?

2020-11-21 15:32 UTC, 4310V343k commented on code/game/turfs/simulated/floor.dm
> +				if(do_after(user, 2, target = user) && (src in view(1, user)))
На самом деле не вижу смысла в этой проверке. При движении хумана ду афтер и так сбрасывается, разве нет?

2020-11-21 15:40 UTC, Kortez90 commented on code/game/turfs/simulated/floor.dm
> +		if(get_dist(user, C) > 1 || get_dist(user, src) > 1 || !(src in view(1, user)))
Через стекло передавать нельзя, а вот под дверь сунуть можно... Надо как-то исправить. Есть какой-нибудь прок, проверяющий предметы на терфе?

2020-11-22 10:07 UTC, Kortez90 commented
Никто не подкинул прок для проверки на терфе объектов, поэтому сделал "по-своему". При выкладывании предметов на терфе проверяется `atom/movable` и в проверку внесены исключения в виде столов и стеклянных дверей. По поводу стеклянных дверей не уверен. Грубо говоря, под ними можно просовывать вещи и это спорный момент. В остальном, вроде, готово.

2020-11-22 10:14 UTC, 4310V343k commented on code/game/turfs/simulated/floor.dm
> +	for(var/atom/movable/on_turf in src.contents)
Я думаю, что этот фор лучше засунуть ниже под иф, по причине, указанной ранее
(Если потом в этот прок добавлять ещё какие-либо вещи, придётся эту логику в **другом** ПРе убирать под иф, получается не атомарно
И да, `src.`

2020-11-22 10:15 UTC, 4310V343k commented
> Никто не подкинул прок для проверки на терфе объектов, поэтому сделал "по-своему". При выкладывании предметов на терфе проверяется `atom/movable` и в проверку внесены исключения в виде столов и стеклянных дверей. По поводу стеклянных дверей не уверен. Грубо говоря, под ними можно просовывать вещи и это спорный момент. В остальном, вроде, готово.

Ещё есть стекло и я уверен куча всего

2020-11-22 10:17 UTC, Kortez90 commented
> Ещё есть стекло и я уверен куча всего

Под стекло положить нельзя, разве что под открученное, хотя оно, вроде, меняет `density`.
Или есть какое-то другое стекло?

2020-11-22 10:43 UTC, 4310V343k commented
> Под стекло в виде полосочки нельзя положить

Про него и говорил. Почему?

2020-11-22 10:48 UTC, Kortez90 commented
Потому что это `/obj/structure/window/reinforced`, наследник `/obj/structure/window` у которого `density = 1`. Вроде бы.

2020-11-23 19:24 UTC, LudwigVonChesterfield commented on code/game/turfs/simulated/floor.dm
> +			if(on_turf.density && !(on_turf.checkpass(PASSTABLE)))
у нас есть прок CanPass для этого

к примеру ты почему-то решил что можно перекидывать вещи через стеклянную дверцу, хотя в каком-то там ишуе жаловались что людей можно перекидывать комбухой через эту же дверцу.

2020-11-23 19:24 UTC, LudwigVonChesterfield commented on code/game/turfs/simulated/floor.dm
> +	if(istype(C, /obj/item/weapon/storage))
Киборг говорит о раннем возврате из функции, и он абсолютно прав.

2020-11-23 21:00 UTC, Kortez90 commented on code/game/turfs/simulated/floor.dm
> +			if(on_turf.density && !(on_turf.checkpass(PASSTABLE)))
Просто дверца занимает ~1/8 тайла и класть туда вещи можно. К тому же, под дверцу нельзя ничего положить, если доступа к тайлу под ней нет, а когда она закрыта `density = 1`.
`CanPass` я видел, но разве он тут подходит?

2020-11-24 05:36 UTC, 4310V343k commented on code/game/turfs/simulated/floor.dm
> +			if(on_turf.density && !(on_turf.checkpass(PASSTABLE)))
Лудук, там везде проверки на Adjacent(), ты с другой стороны двери по сути вывалить не сможешь

2020-11-24 09:22 UTC, LudwigVonChesterfield requested changes
Давайте не будем делать лесенку ифов когда можно

2020-11-24 09:22 UTC, LudwigVonChesterfield commented on code/game/turfs/simulated/floor.dm
> +			if(on_turf.density && !(on_turf.checkpass(PASSTABLE)))
Вот здесь нужно так или иначе это решить. Текущее решение с лесенкой ифов неприемлимо, когда у нас 100% есть функции которые не позволяют предметам проходить сквозь другие предметы(Иначе бы у нас при бросках предметы бы спокойно пролетали через дверцы и т.д.)

2020-11-24 10:38 UTC, Kortez90 commented on code/game/turfs/simulated/floor.dm
> +			if(on_turf.density && !(on_turf.checkpass(PASSTABLE)))
Я не уверен, чего ты добивался, но вроде это оно.
Не пробовал быть более конкретным? Это повысит эффективность.

2020-11-24 11:04 UTC, LudwigVonChesterfield commented on code/game/turfs/simulated/floor.dm
> +			if(!CanPass(contents, src) && !(on_turf.checkpass(PASSTABLE)))
```suggestion
			if(!CanPass(contents, src))
```

2020-11-24 11:05 UTC, LudwigVonChesterfield commented on code/game/turfs/simulated/floor.dm
> +			if(!CanPass(contents, src) && !(on_turf.checkpass(PASSTABLE)))
Мне кажется это не будет работать потому-что ты даже не прочитал какие аргументы у функции CanPass. ты ей зачем-то передаешь целый список, когда она работает между двумя объектами.

2020-11-24 11:07 UTC, Kortez90 commented on code/game/turfs/simulated/floor.dm
> +			if(!CanPass(contents, src) && !(on_turf.checkpass(PASSTABLE)))
Вот этот вариант как раз и не работал. Аргументы я читал, спасибо.
Но да ладно, проверю еще раз.

2020-11-24 11:09 UTC, LudwigVonChesterfield commented on code/game/turfs/simulated/floor.dm
> +			if(!CanPass(contents, src) && !(on_turf.checkpass(PASSTABLE)))
А твой вариант что-ли работал?

2020-11-24 11:09 UTC, LudwigVonChesterfield commented on code/game/turfs/simulated/floor.dm
> +			if(!CanPass(contents, src) && !(on_turf.checkpass(PASSTABLE)))
Ты типо когда кодишь не думаешь что ты делаешь, а тыкаешь просто случайные буквы в случайные места пока не получится хоть как-то похоже на что нужно?

2020-11-24 11:10 UTC, Kortez90 commented on code/game/turfs/simulated/floor.dm
> +			if(!CanPass(contents, src) && !(on_turf.checkpass(PASSTABLE)))
Конечно. А как иначе? Просто буковки подставляю и все. (Шутка юмора.)

Да, работал.

2020-11-24 11:13 UTC, LudwigVonChesterfield commented on code/game/turfs/simulated/floor.dm
> +			if(!CanPass(contents, src) && !(on_turf.checkpass(PASSTABLE)))
> /atom/proc/CanPass(atom/movable/mover, turf/target, height = 1.5, air_group = 0)

Точно работал? Я просто вижу что CanPass не принимает в качестве аргументов список.

2020-11-24 11:15 UTC, Kortez90 commented on code/game/turfs/simulated/floor.dm
> +			if(!CanPass(contents, src) && !(on_turf.checkpass(PASSTABLE)))
Могу гифку записать. Или сам проверь, если не веришь. Код - кодом, практика - практикой.

2020-11-24 11:16 UTC, LudwigVonChesterfield commented on code/game/turfs/simulated/floor.dm
> +			if(!CanPass(contents, src) && !(on_turf.checkpass(PASSTABLE)))
Если что-то работает по совпадению это не значит что ты сделал хорошо, это значит что так совпало что оно работает.

Попробуй объяснить каким образом передавание в функцию неправильных аргументов приводит к решению твоей проблемы.

2020-11-24 11:18 UTC, Kortez90 commented on code/game/turfs/simulated/floor.dm
> +			if(!CanPass(contents, src) && !(on_turf.checkpass(PASSTABLE)))
Вот, что делает твой вариант.
![GIF 24 11 2020 14-16-32](https://user-images.githubusercontent.com/36198983/100087448-ca8de600-2e5f-11eb-8eed-f3b3d0e7df2b.gif)

2020-11-24 11:19 UTC, LudwigVonChesterfield commented on code/game/turfs/simulated/floor.dm
> +			if(!CanPass(contents, src) && !(on_turf.checkpass(PASSTABLE)))
Я тебе не даю решения, и не обязан. Я говорю что у тебя сейчас в коде есть проблема, и я хочу тебе помочь её решить, указав примерно сторону в которую можно копать.

Ты же хочешь чтобы я за тебя и код написал, и сам себя отревьювил, и вмёржил, и ещё конфетку выдал.

2020-11-24 11:23 UTC, Kortez90 commented on code/game/turfs/simulated/floor.dm
> +			if(!CanPass(contents, src) && !(on_turf.checkpass(PASSTABLE)))
Давай, для начала, не будем решать за других, чего они хотят, ага?

В коде проблемы не было. Даже без `CanPass` все работало как должно было и без ущерба для производительности. Но ты предложил придирку (А иначе это не назвать.) - страшная лестница. Ладно. Я ее убрал, хоть из-за этого код лишился небольшой фичи. Теперь ты говоришь, что код не работает, даже не проверяя. И что дальше? Известно как лучше - скажи.

2020-11-24 13:16 UTC, Kortez90 commented on code/game/turfs/simulated/floor.dm
> +			if(!CanPass(contents, src) && !(on_turf.checkpass(PASSTABLE)))
Так лучше? Лестницу со столами и полками вернул. Надеюсь, возражений нет?

2020-12-23 14:50 UTC, Kortez90 commented on code/game/turfs/simulated/floor.dm
> +	else
Done.

2020-12-23 14:56 UTC, KIBORG04 commented on code/game/turfs/simulated/floor.dm
> +
```suggestion
			if(!do_after(user, 2, target = user) && !user.Adjacent(src))
				break
			S.remove_from_storage(I,src)
```

Мне не нрав как это выглядит

2020-12-25 12:06 UTC, 4310V343k commented on code/game/turfs/simulated/floor.dm
> +	if(!user.Adjacent(src) || !Adjacent(C) || !Adjacent(user))
```suggestion
	if(!Adjacent(user) || !Adjacent(C) || !C.Adjacent(user))
```

2020-12-25 12:06 UTC, 4310V343k commented on code/game/turfs/simulated/floor.dm
> +		var/turf/T = get_turf(on_turf)
Нужен ли смысл, если T = src?

2020-12-25 12:16 UTC, 4310V343k commented on code/game/turfs/simulated/floor.dm
> +			if(!do_after(user, 2, target = user) && !user.Adjacent(src))
Что бы проверка `!user.Adjacent(src))` сработала, нужно успеть подвинуться за то время, пока происходит `S.remove_from_storage(I,src)`. Я не уверен, что это вообще возможно...

2020-12-25 12:27 UTC, 4310V343k commented on code/game/turfs/simulated/floor.dm
> +			return
если на тайле будет 1000 яблок
и я захочу на этот тайл что-нибудь вывалить
оно будет 1000 раз проверять, а могу ли я вывалить на этот тайл ЕЩЁ ДО ВЫВАЛИВАНИЯ

2020-12-25 12:27 UTC, 4310V343k requested changes
![image](https://user-images.githubusercontent.com/56449763/103134963-c145a280-46c5-11eb-82b3-cd4ec7cf8a53.png)

2020-12-25 13:39 UTC, KIBORG04 requested changes
Мне не нравится текущее решение через логику в турфе, а так же множество аджасментов во всех местах

2020-12-25 13:39 UTC, KIBORG04 commented on code/game/turfs/simulated/floor.dm
> +/turf/simulated/floor/MouseDrop_T(obj/item/C, mob/user)
Почему за логику вываливания вещи отвечает пол, а не рюкзак?

Предлагаю всю логику перенести в рюкзак, это помогло бы избавиться от некоторых проблем и лучше изменять код, поддерживая ООП.

2020-12-25 13:39 UTC, KIBORG04 commented on code/game/turfs/simulated/floor.dm
> +		return
Под ООП я подразумеваю выделить отдельый прок под эти проверки

2020-12-25 13:39 UTC, KIBORG04 commented on code/game/turfs/simulated/floor.dm
> +			S.remove_from_storage(I,src)
Зачем нам иметь множество всяких проверок и аджасментов, когда можно просто сделать примерно такое:
```
backpack/MouseDrop(kuda)
    if(ishuman(kuda))
        drugoi kod
    else
        var/turf/T = kuda
        for(var/i in contents)
            if(!T.can_vivalit)
                return
            remove_from_storage(i, T)
```
Можно сделать так, но можно потрудиться и сделать, чтобы вместо турфа запоминалось относительное от юзера к турфу направление, а потом запускался асинхронно другой прок, чтобы вываливались предметы на бегу в том направление.

2020-12-25 13:52 UTC, 4310V343k commented on code/game/turfs/simulated/floor.dm
> +			S.remove_from_storage(I,src)
Могу дополнить.
Делать проверку не только на турф, но ещё и стол/rack, потому что на них как бы можно вывалить, но как бы нельзя из-за да

2020-12-25 13:54 UTC, KIBORG04 commented on code/game/turfs/simulated/floor.dm
> +			S.remove_from_storage(I,src)
Ну людук же как-то сделал перетаскивание предмета на стол

2020-12-25 16:38 UTC, LudwigVonChesterfield commented on code/game/turfs/simulated/floor.dm
> +			return
очень подумал, полностью согласен тут. думаю стоит выпилить все проверки, и выбрасывать вещи сначала под себя, а потом step()-ом пытаться их сместить в сторону в которую игрок тыкнул.

2020-12-25 17:14 UTC, LudwigVonChesterfield commented on code/game/turfs/simulated/floor.dm
> +			if(!do_after(user, 2, target = user) && !user.Adjacent(src))
то есть если человек прервал - но не отошёл - сейчас будет продолжаться? думаю user.ADjacent тут лишнее

2021-01-01 13:38 UTC, KIBORG04 commented on code/game/objects/items/weapons/storage/storage.dm
> +/obj/item/weapon/storage/MouseDrop(obj/over_object, null, turf/over_location)
```suggestion
/obj/item/weapon/storage/MouseDrop(obj/over_object, src_location, turf/over_location)
```

2021-01-01 14:01 UTC, KIBORG04 commented on code/game/objects/items/weapons/storage/storage.dm
> +				src.remove_from_storage(I, M.loc)
```suggestion
				remove_from_storage(I, M.loc)
```
Ctrl+H
`src.` => ``

2021-01-01 14:02 UTC, KIBORG04 commented on code/game/objects/items/weapons/storage/storage.dm
>  	return
```suggestion
```

2021-01-01 14:02 UTC, KIBORG04 commented on code/game/objects/items/weapons/storage/storage.dm
> +		return FALSE
Такое вообще возможно?

2021-01-01 14:03 UTC, KIBORG04 commented on code/game/objects/items/weapons/storage/storage.dm
> +		return FALSE
Ты передаешь сюда src, а срк у нас и есть сторейдж

2021-01-01 14:03 UTC, KIBORG04 commented on code/game/objects/items/weapons/storage/storage.dm
> +	if(usr.incapacitated())
```suggestion
	if(user.incapacitated())
```

2021-01-01 14:05 UTC, KIBORG04 commented on code/game/objects/items/weapons/storage/storage.dm
> +	if((C.loc && C.loc.loc == user))
Как я понял, это чтобы коробку из рюкзака нельзя было опустошить.
А есть у меня блюспейс рюкзак, в нем рюкзак, а в нем коробка?

2021-01-01 14:06 UTC, KIBORG04 commented on code/game/objects/items/weapons/storage/storage.dm
> +	if(over_location && over_object != usr)
```suggestion
	var/mob/M = usr
	if(over_location && over_object != M)
```

2021-01-01 14:08 UTC, KIBORG04 commented on code/game/objects/items/weapons/storage/storage.dm
> +					break
```suggestion
					return
```
Впринципе, не важно. Просто красивее было бы, если бы и там, и там был один оператор

2021-01-01 14:09 UTC, Kortez90 commented on code/game/objects/items/weapons/storage/storage.dm
> +	if((C.loc && C.loc.loc == user))
Не получится, если предмет не в руке.
`if(src.slot_equipped != (SLOT_L_HAND|SLOT_R_HAND))`

2021-01-01 14:09 UTC, KIBORG04 commented on code/game/objects/items/weapons/storage/storage.dm
> +				src.add_fingerprint(usr)
```suggestion
				src.add_fingerprint(M)
```

2021-01-01 14:11 UTC, KIBORG04 commented on code/game/objects/items/weapons/storage/storage.dm
> +	if((C.loc && C.loc.loc == user))
А зачем тогда эта ифка?

2021-01-02 23:24 UTC, KIBORG04 commented on code/game/objects/items/weapons/storage/storage.dm
> +	if(!(ishuman(usr) || ismonkey(usr) || isIAN(usr))) //so monkeys can take off their backpacks -- Urist
```suggestion
	if(!ishuman(usr) || !ismonkey(usr) || !isIAN(usr)) //so monkeys can take off their backpacks -- Urist
```
Античитабельность

2021-01-07 23:30 UTC, KIBORG04 commented on code/game/objects/items/weapons/storage/storage.dm
> +		if(!istype(M.loc, /turf))
```suggestion
		if(!isturf(M.loc))
```

2021-01-07 23:43 UTC, KIBORG04 commented on code/game/objects/items/weapons/storage/storage.dm
> +				if(!Adjacent(M) || !over_location.Adjacent(src) || !over_location.Adjacent(M))
А нужны ли они внутри цикла? Вроде как если подвигаться, то ду_афтер сломается и их не просмотрят.

2021-01-07 23:43 UTC, KIBORG04 commented on code/game/objects/items/weapons/storage/storage.dm
> +				add_fingerprint(M)
Ты тут наверное хотел I, а не M(mob)

2021-01-07 23:46 UTC, Kortez90 commented on code/game/objects/items/weapons/storage/storage.dm
> +				if(!Adjacent(M) || !over_location.Adjacent(src) || !over_location.Adjacent(M))
Нужны, ведь проверку проходит каждый объект.

2021-01-07 23:48 UTC, Kortez90 commented on code/game/objects/items/weapons/storage/storage.dm
> +				add_fingerprint(M)
У вещей нет отпечатков.

2021-01-07 23:49 UTC, KIBORG04 commented on code/game/objects/items/weapons/storage/storage.dm
> +				if(!Adjacent(M) || !over_location.Adjacent(src) || !over_location.Adjacent(M))
Вот только я не вижу, чтобы там участвовала переменная `I`.
```
Первая итерация:
   Занят ли моб?
   !Близко ли рюкзак к юзеру || !турф куда вываливают близко ли к рюкзаку || !турф куда вываливают близко ли к юзеру
   !Делаем действие, иначе минус цикл
Вторая итерация:
   Занят ли моб?
   !Близко ли рюкзак к юзеру || !турф куда вываливают близко ли к рюкзаку || !турф куда вываливают близко ли к юзеру
   !Делаем действие, иначе минус цикл
```

2021-01-07 23:50 UTC, Kortez90 commented on code/game/objects/items/weapons/storage/storage.dm
> +				if(!Adjacent(M) || !over_location.Adjacent(src) || !over_location.Adjacent(M))
А если предмет исчезнет из сумки во время вываливания? Например маг дернет спеллом?

2021-01-07 23:52 UTC, KIBORG04 commented on code/game/objects/items/weapons/storage/storage.dm
> +				if(!Adjacent(M) || !over_location.Adjacent(src) || !over_location.Adjacent(M))
Опять же, ты нигде не проверяешь близко ли предмет к рюкзаку

2021-01-08 00:32 UTC, Kortez90 commented on code/game/objects/items/weapons/storage/storage.dm
> +				if(!Adjacent(M) || !over_location.Adjacent(src) || !over_location.Adjacent(M))
В общем, аджасенты в цикле нужны.

2021-01-08 14:21 UTC, KIBORG04 approved these changes

2021-01-12 13:51 UTC, 4310V343k commented on code/game/objects/items/weapons/storage/storage.dm
> +	if((over_location && istype(over_location, /turf)) && over_object != M)
over_location всегда `/turf`, другой вопрос что его может не быть

2021-01-12 14:00 UTC, Kortez90 commented on code/game/objects/items/weapons/storage/storage.dm
> +	if((over_location && istype(over_location, /turf)) && over_object != M)
Как показала практика - не всегда.
`Cannot execute "floor".Adjacent().`

2021-01-21 14:55 UTC, KIBORG04 commented on code/game/objects/items/weapons/storage/storage.dm
> +	if((over_location && istype(over_location, /turf)) && over_object != M)
```suggestion
	if(isturf(over_location) && over_object != M)
```
Поидее, нам не нужно проверять нулл это или строка, потому что строка или нулл это ТОЧНО не турф и точно не юзер

2021-01-21 18:58 UTC, merged