Фикс рантайма меха при взрыве.
TauCetiStation/TauCetiClassic pull request #6403
Opened 2020-11-22 17:34 UTC by Kortez90

## Описание изменений
Добавил остановку процессинга после проков `destroy` и проверки в процессингах внутренних повреждений и баков.
В мехах в целом какой-то кошмар и наверное, их надо целиком рефакторить. Особенно `/datum/global_iterator/`, где после взрыва меха запускалась проверка `cabin_air.return_pressure()` сразу в переменной, но у взорванного меха нет кабины и воздуха в ней. Возможно `STOP_PROCESSING` тут даже лишний.
(Извиняюсь из-за первого ПР. Удалил ветку, восстановить нельзя.)
## Почему и что этот ПР улучшит
Fix #6401.
## Авторство

## Чеинжлог

2020-11-22 17:34 UTC, TauKitty commented
###### Changelog status: :radio_button: No changelog

2020-11-23 17:32 UTC, LudwigVonChesterfield commented on code/game/mecha/mecha.dm
> +	STOP_PROCESSING(SSobj, src)
так-то qdel и сам это делает, это точно как-либо повлияло на решение рантайма?

https://github.com/TauCetiStation/TauCetiClassic/blob/5ec6eef445903ffcceecd3d7a4e63a0ee2b8d58b/code/game/objects/objs.dm#L31

2020-11-23 17:32 UTC, LudwigVonChesterfield commented on code/game/mecha/mecha.dm
> +		STOP_PROCESSING(SSobj, src)
Здесь почему-то решили перестать возвращать сигнал, который и так бы заставил перестать процесситься предмет(см. как работают сабсистемы, и процессинг)

2020-11-23 19:20 UTC, LudwigVonChesterfield commented on code/game/mecha/mecha.dm
> +	STOP_PROCESSING(SSobj, src)
В дестрое буквально на уровень выше уже есть STOP_PROCESSING

2020-11-24 09:25 UTC, LudwigVonChesterfield commented on code/game/mecha/mecha.dm
> +	if(!islist(possible_int_damage) || isemptylist(possible_int_damage) || wreckage)
А почему вместо тысячи проверок на wreckage в разных местах не останавливать процессинг в том месте, где делается mecha.wreckage = TRUE?

2020-11-24 09:53 UTC, Kortez90 commented on code/game/mecha/mecha.dm
> +	if(!islist(possible_int_damage) || isemptylist(possible_int_damage) || wreckage)
А где она делается `TRUE`? Нашел тут только объявление переменной и проверку в дестрое.

2020-11-24 10:25 UTC, LudwigVonChesterfield commented on code/game/mecha/mecha.dm
> +	if(!islist(possible_int_damage) || isemptylist(possible_int_damage) || wreckage)
Так если она никогда не принимает значения аналогичного TRUE, то зачем ты её проверяешь?

2020-11-24 10:31 UTC, Kortez90 commented on code/game/mecha/mecha.dm
> +	if(!islist(possible_int_damage) || isemptylist(possible_int_damage) || wreckage)
Потому что вреки продолжают процессинг.

2020-11-24 10:52 UTC, LudwigVonChesterfield commented on code/game/mecha/mecha.dm
> +	if(!islist(possible_int_damage) || isemptylist(possible_int_damage) || wreckage)
ну так останавливай процессинг там, где создаётся wreck

2020-11-24 11:41 UTC, Kortez90 commented on code/game/mecha/mecha.dm
> +	if(!islist(possible_int_damage) || isemptylist(possible_int_damage) || wreckage)
https://github.com/TauCetiStation/TauCetiClassic/blob/e8f0ece9c23257a91c74efb199f8befa227e7e92/code/game/mecha/mecha.dm#L543
Разве qdel этого не делает?

2020-11-24 16:34 UTC, Kortez90 commented on code/game/mecha/mecha.dm
> +	if(!islist(possible_int_damage) || isemptylist(possible_int_damage) || wreckage)
Проверки снял, кроме одной. В `check_for_internal_damage`. так как нет смысла проверять внутренние повреждения у врека. Поставил выключение процессинга, если врек остается. Такое устроит?

2020-11-24 16:43 UTC, LudwigVonChesterfield commented on code/game/mecha/mecha.dm
> +	if(!islist(possible_int_damage) || isemptylist(possible_int_damage) || wreckage)
А ты точно знаешь за что переменная wreckage отвечает?

2020-11-24 16:49 UTC, Kortez90 commented on code/game/mecha/mecha.dm
> +	if(!islist(possible_int_damage) || isemptylist(possible_int_damage) || wreckage)
За то, какой врек после меха останется и останется ли вообще.

2020-12-24 10:33 UTC, LudwigVonChesterfield commented on code/game/mecha/mecha.dm
> +	if(!islist(possible_int_damage) || isemptylist(possible_int_damage) || wreckage)
И почему мехи у которых есть тип врека который остаётся должны внезапноне получать внутренний урон?

2020-12-24 10:34 UTC, Kortez90 commented on code/game/mecha/mecha.dm
> +	if(!islist(possible_int_damage) || isemptylist(possible_int_damage) || wreckage)
Что ты предлагаешь?

2021-01-20 01:08 UTC, T6751 requested changes

2021-01-20 08:17 UTC, T6751 approved these changes

2021-01-20 08:35 UTC, merged