trays lidl rewrire
TauCetiStation/TauCetiClassic pull request #6404
Opened 2020-11-23 01:19 UTC by Morair

## Описание изменений
Код подноса переписан, не через storage, но лучше чем не рабочий поднос...наверно.
Через ```afterattack``` можно быстро брать/класть вещи, режим переключается через ```attack_self```
Поднос теперь может хранить только вещи связанные с кухней
Если поднос положить, то он отдаст все вещи.
Если перед тем как взять поднос, на турфе будут вещи, он их поднимет.
## Почему и что этот ПР улучшит
fix #1008
## Авторство

## Чеинжлог
 🆑 Morair
* bugfix: Подносы починены.

2020-11-23 01:19 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2020-11-23 05:16 UTC, Morair commented
а зачем

2020-11-23 06:29 UTC, Ahion commented
Что случилось? Зачем закрыл?

2020-11-23 06:53 UTC, Zmey25 commented
А каким теперь вопросом проверять менторов на знание механа?

2020-11-23 06:56 UTC, Morair commented
> Что случилось? Зачем закрыл?

А, ну пара багов просто, из за того что это не контейнер, слишком костыльно получится, из за того что ```dropped``` и ```pickup``` вызываются буквально каждый раз когда слот меняется(из за чего эта версия сейчас подбирается вещи с пола над которыми ты стоишь при смене руки)
Еще ```throw_at``` прикрутить нужно к ```do_scatter``` и ```step()``` убрать потому что он перемещает без проверок.
Пускай висит тогда пока

2020-11-23 08:08 UTC, Kortez90 commented on code/game/objects/items/weapons/kitchen.dm
> +		/obj/item/weapon/reagent_containers/glass,
Если ты имел в виду стаканы, то они живут по адресу `/obj/item/weapon/reagent_containers/food/drinks/drinkingglass`, бутылки тоже стоит добавить.

2020-11-23 10:51 UTC, Kortez90 commented on code/game/objects/items/weapons/kitchen.dm
> +			return
```suggestion
	if(!throwed && (T.density || !user.Adjacent(T)))
		return
```

2020-11-23 10:55 UTC, Kortez90 commented on code/game/objects/items/weapons/kitchen.dm
> +	playsound(M, pick('sound/items/trayhit1.ogg', 'sound/items/trayhit2.ogg'), VOL_EFFECTS_MASTER)
Тут не должен быть `playsound_local`?

2020-11-23 17:33 UTC, LudwigVonChesterfield commented
> А, ну пара багов просто, из за того что это не контейнер

Что ты думаешь о том чтобы сделать это контейнером? У нас уже есть container/visual_contents который используется к примеру в подносах медицинских.

2020-11-23 17:34 UTC, LudwigVonChesterfield requested changes
Считаю что это бессмысленные изменения, и изобретение колеса заново.

Если и делать рефактор - то пожалуйста смотрите в сторону уже существующих решений(/obj/item/weapon/storage), чтобы после вас не приходилось рефакторить ещё раз

2020-11-23 20:59 UTC, Morair commented on code/game/objects/items/weapons/kitchen.dm
> +	playsound(M, pick('sound/items/trayhit1.ogg', 'sound/items/trayhit2.ogg'), VOL_EFFECTS_MASTER)
почему?

2020-11-23 21:19 UTC, Morair commented
#5275 можно будет тоже закрыть, если все нормально тут.

2020-11-24 06:13 UTC, Sakuya-Izayoi commented
Файнали

2020-11-24 06:46 UTC, Kortez90 commented on code/game/objects/items/weapons/kitchen.dm
> +	playsound(M, pick('sound/items/trayhit1.ogg', 'sound/items/trayhit2.ogg'), VOL_EFFECTS_MASTER)
Потому что тогда звук удара не будет гулять через стены?

2020-11-24 07:34 UTC, Morair commented on code/game/objects/items/weapons/kitchen.dm
> +	playsound(M, pick('sound/items/trayhit1.ogg', 'sound/items/trayhit2.ogg'), VOL_EFFECTS_MASTER)
так звук локально играется

2020-11-24 09:18 UTC, LudwigVonChesterfield commented on code/game/objects/items/weapons/kitchen.dm
> +	collection_mode = !collection_mode
У нас помоему такой механ у всех стореджей уже есть, и они как-то обходятся без этого тугла. Он нужен?

2020-11-24 09:18 UTC, LudwigVonChesterfield commented on code/game/objects/items/weapons/kitchen.dm
> +	if(istype(I, /obj/item/weapon/kitchen/rollingpin) && !contents.len && cooldown < world.time - 25 && user.a_intent == INTENT_HARM)
(если хочешь) Сделай чтобы если ударили по подносу с вещами то с него всё сыпалось

2020-11-24 09:19 UTC, LudwigVonChesterfield commented on code/game/objects/items/weapons/kitchen.dm
> +		..()
```suggestion
		return ..()
```

2020-11-24 10:15 UTC, Morair commented on code/game/objects/items/weapons/kitchen.dm
> +	collection_mode = !collection_mode
Это чисто для боргов, можно им наверно вынести это, а у обычного подноса убрать

2020-11-24 10:24 UTC, LudwigVonChesterfield commented on code/game/objects/items/weapons/kitchen.dm
> +	collection_mode = !collection_mode
учитывая что у боргов теперь вроде есть рука, это ещё надо?

2020-11-24 10:57 UTC, Morair commented on code/game/objects/items/weapons/kitchen.dm
> +	collection_mode = !collection_mode
```
/obj/item/weapon/storage/attackby(obj/item/I, mob/user, params)
	if(isrobot(user))
		to_chat(user, "<span class='notice'>You're a robot. No.</span>")
		return //Robots can't interact with storage items. FALSE
```
нельзя им в storage, только так получается без копипасты

2020-11-24 11:15 UTC, merged

2020-11-24 11:26 UTC, Morair commented
@LudwigVonChesterfield я не закомитил b0c6ab4

2020-11-24 11:30 UTC, LudwigVonChesterfield commented
Ну сделай отдельный ПР