forgot commit
TauCetiStation/TauCetiClassic pull request #6412
Opened 2020-11-24 11:40 UTC by Morair

## Описание изменений
https://github.com/TauCetiStation/TauCetiClassic/pull/6404#issuecomment-732862511
## Почему и что этот ПР улучшит
коммит потерян
## Авторство

## Чеинжлог

2020-11-24 11:40 UTC, TauKitty commented
###### Changelog status: :radio_button: No changelog

2020-11-24 11:49 UTC, LudwigVonChesterfield commented on code/game/objects/items/weapons/kitchen.dm
> +	var/static/list/tray_whitelisted_items = typecacheof(list(
У класса storage уже есть такая механика, используй её пожалуйста.

2020-11-24 11:49 UTC, LudwigVonChesterfield commented on code/game/objects/items/weapons/kitchen.dm
> +	if(is_type_in_typecache(W, tray_whitelisted_items))
У storage уже есть такая механика, пожалуйста не переизобретай её

2020-11-24 11:49 UTC, LudwigVonChesterfield commented on code/game/objects/items/weapons/kitchen.dm
> + * Moves items from a turf to a tray
> drop items
> moves items from a turf to a tray
```suggestion
 * Moves items from tray to the turf
```

2020-11-24 11:50 UTC, LudwigVonChesterfield commented on code/modules/mob/living/silicon/robot/robot_items.dm
> +	return
```suggestion
```

2020-11-24 11:58 UTC, Morair commented on code/game/objects/items/weapons/kitchen.dm
> +	var/static/list/tray_whitelisted_items = typecacheof(list(
забываю смотреть родителя

2020-11-24 12:01 UTC, LudwigVonChesterfield commented on code/modules/mob/living/silicon/robot/robot_items.dm
> +	if(!target)
А такое может быть?

2020-11-24 12:01 UTC, LudwigVonChesterfield approved these changes

2020-11-24 12:09 UTC, Morair commented on code/modules/mob/living/silicon/robot/robot_items.dm
> +	if(!target)
по сути, нет

2020-11-24 12:21 UTC, LudwigVonChesterfield commented on code/modules/mob/living/silicon/robot/robot_items.dm
> +	if(target.density)
А в чем смысл проверять это?

То есть если я ударю по вендомату на полу - я не подберу предметы, а если ударя по полу - я подберу предметы.

2020-11-24 12:22 UTC, Morair commented
Не мердж
```
if(target.density)
		return
```
это же еще и столы и прочее

2020-11-24 12:22 UTC, Morair commented on code/modules/mob/living/silicon/robot/robot_items.dm
> +	if(target.density)
А там в стену можно скинуть вещи с подноса

2020-11-24 12:28 UTC, Morair commented on code/modules/mob/living/silicon/robot/robot_items.dm
> +	if(target.density)
поменял на ```if((get_turf(target)).density)```, проверено, работает как нужно.

2020-11-24 13:29 UTC, LudwigVonChesterfield commented on code/modules/mob/living/silicon/robot/robot_items.dm
> +	if((get_turf(target)).density)
Это не проверяет на столы если что. Это проверяет только на то, что турф, на который ты тыкаешь - не проходиммый, и почему это проблема я уже писал раньше.

Если ты хочешь сделать по красоте, чтобы вещи проходили через то что можно, и через то что нельзя, я рекомендую смотреть в сторону CanPass, возможно даже поможешь человеку #6394 тут

2020-11-24 13:29 UTC, LudwigVonChesterfield requested changes

2020-11-24 13:29 UTC, LudwigVonChesterfield commented on code/modules/mob/living/silicon/robot/robot_items.dm
> +	if((get_turf(target)).density)
Разберись пожалуйста с этим моментом получше

2020-11-24 17:52 UTC, Morair commented on code/modules/mob/living/silicon/robot/robot_items.dm
> +	if((get_turf(target)).density)
Если я все правильно сделал, то должно быть все нормально сейчас. Проверил предметы корректно выбрасываются/бросаются, под двери не кладутся, на ```/obj``` кладутся нормально

2020-11-25 19:53 UTC, LudwigVonChesterfield commented on code/game/objects/items/weapons/kitchen.dm
> +			sleep(1)
А это зачем?

2020-11-25 19:53 UTC, LudwigVonChesterfield commented on code/modules/mob/living/silicon/robot/robot_items.dm
> +			if(!obstacle.CanPass(I, T)) // check each obj on a turf if item can pass through it
Разве это не часть turf/CanPass прока?

2020-11-25 19:57 UTC, Morair commented on code/game/objects/items/weapons/kitchen.dm
> +			sleep(1)
Чтоб когда бросаешь поднос, лут рассыпался в полете

2020-11-25 19:59 UTC, Morair commented on code/modules/mob/living/silicon/robot/robot_items.dm
> +			if(!obstacle.CanPass(I, T)) // check each obj on a turf if item can pass through it
Так один CanPass для турфов, второй для объектов, или я не так понял что-то?

2020-11-26 09:31 UTC, LudwigVonChesterfield commented on code/game/objects/items/weapons/kitchen.dm
> +			sleep(1)
мне это решение не нравится, если ты хочешь механ рассыпки в полёте - это надо модифицировать то как работает thrownthing

к примеру добавить коллбек "on_move" чтобы ты к нему подвязался, и там с шансом что-то рассыпал - как сейчас - стопорить всю цепочку вызовов вверх ради мелкой фичи я не считаю стоящим.

2020-11-26 10:35 UTC, Morair commented on code/game/objects/items/weapons/kitchen.dm
> +			sleep(1)
Сейчас должно быть лучше

2020-11-27 19:29 UTC, LudwigVonChesterfield commented on code/game/objects/items/weapons/kitchen.dm
> +	RegisterSignal(src, list(COMSIG_MOVABLE_MOVED), .proc/on_move)
Я не совсем это имел ввиду... Я думал ты будешь вызывать из брошенной вещи подобный колбек.

Что ты делаешь сейчас:
1. предмет бросается
2. после того как он двигается один тайл все вещи с него выпадают

но в очень странный и ухитрённый способ, я не уверен что это хорошее применение сигналов...

2020-11-28 00:57 UTC, Morair commented on code/game/objects/items/weapons/kitchen.dm
> +	RegisterSignal(src, list(COMSIG_MOVABLE_MOVED), .proc/on_move)
Works as intended...

2020-11-29 14:12 UTC, LudwigVonChesterfield commented on code/game/objects/items/weapons/kitchen.dm
> +	RegisterSignal(src, list(COMSIG_MOVABLE_MOVED), .proc/on_move)
Я предлагаю тебе добавить ещё один, новый колббек, который будет вызываться /datum/thrownthing каждый раз когда ИЗ-ЗА броска объект двигается.

То что сейчас определенно работает, но мне кажется невероятно излишним, может я ещё подумаю и пойму элегантность подписывания на сигнал ради одного срабатывания.

2020-12-05 15:52 UTC, closed without merging