Пофикшена неработавшая руна обмена сознания у культа
TauCetiStation/TauCetiClassic pull request #6415
Opened 2020-11-24 16:46 UTC by WallShrabnic

## Описание изменений
В названии всё написано
## Почему и что этот ПР улучшит
Починена сломаная руна (надеюсь, не костыльно)
## Авторство
wallshrubnic
## Чеинжлог
:cl:
- bugfix: Руна обмена сознаниями у культистов снова работает

2020-11-24 16:46 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2020-11-24 16:50 UTC, KIBORG04 commented
Добавь, что фикс #5984

2020-11-26 08:24 UTC, LudwigVonChesterfield commented on code/game/gamemodes/cult/cult_datums.dm
> +	else if(brainswapping && !user)
Строкой ниже этому не юзеру пишется сообщение

2020-11-27 01:05 UTC, Kortez90 commented
Вроде так работало.
```
/datum/cult/brainswap/proc/do_checks(mob/user, mob/target)
	var/list/compatible_mobs = list(/mob/living/carbon/human, /mob/living/carbon/monkey)
	if(target == user)
		to_chat(user, "<span class='warning'>You cant swap minds with yourself.</span>")
		return FALSE
	if(!(target.type in compatible_mobs))
		to_chat(user, "<span class='warning'>Their mind isn't compatible with yours.</span>")
		return FALSE
	if(target.stat == DEAD)
		to_chat(user, "<span class='warning'>Swapping your mind with a dead body is a bad idea, isn't it?</span>")
		return FALSE
	if(!target.mind || !target.key)
		to_chat(user, "<span class='warning'>He is catatonic, even our magic cant affect him.</span>")
		return FALSE
	if(brainswapping)
		to_chat(user, "<span class='warning'>Someone is already conducting a ritual here.</span>")
		return FALSE
	return TRUE
```

2020-11-27 14:08 UTC, WallShrabnic commented on code/game/gamemodes/cult/cult_datums.dm
> +	else if(brainswapping && !user)
Насколько я понял, тут задумано так, что ритуал нельзя провести, если он уже проводится (извиняюсь за тавтологию), но так как проверка происходит после начала ритуала, то она срабатывает на юзера, которыё начал ритуал. Я просто сделал так, чтобы проверка игнорировала человека, который начал ритуал

2020-11-27 14:17 UTC, Kortez90 commented on code/game/gamemodes/cult/cult_datums.dm
> +	else if(brainswapping && !user)
>проверка происходит после начала ритуала

Эм... Нет. В `action` сначала проходит `do_checks`, причем дважды. Только потом `brainswapping` становится `TRUE`.

2020-11-27 15:33 UTC, Kortez90 commented on code/game/gamemodes/cult/cult_datums.dm
> +	else if(brainswapping && !user)
Перечитал. Достаточно просто поменять `if(!do_after(user, BRAINSWAP_TIME, FALSE, target, FALSE, FALSE) || !do_checks(user, target))` на что-то вроде этого.
```
if(do_after(user, BRAINSWAP_TIME, FALSE, target, FALSE, FALSE) && do_checks(user, target))
    brainswapping  = TRUE
else
    brainswapping  = FALSE
```

2020-11-27 19:27 UTC, LudwigVonChesterfield requested changes
> проверяем на то что юзера нет
> пишем не юзеру сообщение

Ты явно делаешь что-то не так, попробуй разобраться получше.

Почему к примеру переменная позволяющая меняться разумами(brainswapping) может быть TRUE, когда user = null?

2020-12-11 16:31 UTC, LudwigVonChesterfield approved these changes

2020-12-11 16:31 UTC, merged