Фикс СПУ в слипере.
TauCetiStation/TauCetiClassic pull request #6421
Opened 2020-11-25 20:29 UTC by Kortez90

## Описание изменений
Исключил возможность положить спу в слипер меха вообще.
Можно было бы, конечно, просто не усыплять ее в слипере меха, но зачем? Им там не место.
## Почему и что этот ПР улучшит
Fix #6419.
## Авторство

## Чеинжлог
:cl: Kortez90
 - bugfix: СПУ больше нельзя положить в слипер меха.

2020-11-25 20:29 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2020-11-25 20:36 UTC, Morair commented
>Можно было бы, конечно, просто не усыплять ее в слипере меха, но зачем? Им там не место.

А что им там запрещает находиться?

2020-11-25 20:38 UTC, Kortez90 commented
ПО слипера. Как и в генетике. Им нет смысла туда попадать.

2020-11-26 00:47 UTC, ViDLiathan commented
Слиппер для переноса гуманоидов. Не стоит лишать спу возможности попасть в него, но стоит запретить ввод реагентов

2020-12-07 09:52 UTC, T6751 commented on code/game/mecha/equipment/tools/medical_tools.dm
> +	var/mob/living/carbon/human/H = S.occupant
Здесь точно не нужна проверка на хумана?

2020-12-07 10:59 UTC, Kortez90 commented on code/game/mecha/equipment/tools/medical_tools.dm
> +	var/mob/living/carbon/human/H = S.occupant
Так она ниже.

2020-12-07 15:38 UTC, LudwigVonChesterfield commented on code/game/mecha/equipment/tools/medical_tools.dm
> +	var/mob/living/carbon/human/H = S.occupant
Где?

2020-12-07 15:39 UTC, LudwigVonChesterfield commented on code/game/mecha/equipment/tools/medical_tools.dm
> +	if(!M || H.species.flags[IS_SYNTHETIC])
```suggestion
	if(!istype(H) || H.species.flags[IS_SYNTHETIC])
```

2020-12-13 11:14 UTC, T6751 requested changes

2020-12-13 11:14 UTC, T6751 commented on code/game/mecha/equipment/tools/medical_tools.dm
> +	var/mob/living/carbon/human/H = S.occupant
Обычно проверку типа размещают До и получают что-то типа:
```dm
if(ishuman(M)
	var/mob/living/carbon/human/H = S.occupant
	if(H.species.flags[IS_SYNTHETIC])
		return
```
(Суть в том, что так читать код будет легче)

2020-12-13 11:14 UTC, T6751 commented on code/game/mecha/equipment/tools/medical_tools.dm
>  		return
с учетом вышесказанного:
```suggestion
	if(!M)
		return
	if(ishuman(M)
		var/mob/living/carbon/human/H = M
		if(H.species.flags[IS_SYNTHETIC])
			return
```

2020-12-13 11:29 UTC, T6751 commented on code/game/mecha/equipment/tools/medical_tools.dm
> +	if(ishuman(M)
```suggestion
	if(ishuman(M))
```

2020-12-13 11:44 UTC, T6751 reviewed
По коду всё хорошо.
Однако это решение конкретно для СПУ, хотя вероятно такая же проблема может быть ещё, например, у големов, скелетов, других рас... 
И тут лучше рассмотреть вариант Людука, чтобы слипер не просто накладывал эффект, а пытался вколоть реагент для нужного эффекта.

2020-12-13 11:47 UTC, Kortez90 commented
Да, это костыль который исправляет issue. В дальнейшем потребуется рефактор действия слипера меха почти целиком.

2021-01-10 09:44 UTC, merged