Хайвлорд, его изменение и мелкие фиксы мобов
TauCetiStation/TauCetiClassic pull request #6422
Opened 2020-11-26 03:42 UTC by UDaV73rus

## Описание изменений
Оживление simple_animal стало возвращать изначальные свойства density и mouse_opacity
*Например при вводе лазаруса в астероидных мобов, сквозь них можно было ходить и кликать*
Сейчас денсити у хайвлорда хоть и меняется, но всё ещё проходим по неизвестным причинам...

Мобы с модификатором френдли перестали убегать из пулла

При смерти хайвлорда теперь дропается ядро, а труп не остаётся, что не даёт плодить кучу ядер
Но теперь можно вводить лазарус в ядро, карманный хайвлорд
Дефолтное состояние:
![PreviewHivelord](https://user-images.githubusercontent.com/33157992/100304384-b22ce100-2faf-11eb-85e3-b284350abb3b.gif)
Злобный оскал:
![PreviewHivelordAngry](https://user-images.githubusercontent.com/33157992/100304420-c375ed80-2faf-11eb-9423-6685d689c2b0.gif)
Эскадрилья его высеров:
![PreviewVysery](https://user-images.githubusercontent.com/33157992/100304515-fcae5d80-2faf-11eb-9333-f0cc6dd93ff8.gif)
Живое ядро:
![PreviewCore](https://user-images.githubusercontent.com/33157992/100305220-a9d5a580-2fb1-11eb-8dc8-1ce533782a7b.gif)

*Из неочевидного по коду: у хайвлорда теперь нет списка лута, а при смерти хайвлорда труп помещается в ядро*
## Почему и что этот ПР улучшит
Улучшит спрайты хайвлорда и уменьшит количество багов и абузов...
## Авторство
Sonorous Prophet
## Чеинжлог
:cl: UDaV73rus
 - tweak: Хайвлорд не оставляет труп и дана возможность вводить лазарус инъекцию в ядро
 - image: Обновка спрайтов хайвлорда и производных от него вещей
 - rscadd: Мобы с friendly модификатором не убегают из пулла
 - bugfix: Ожившие мобы не возвращали назад некоторые свойства

2020-11-26 03:42 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2020-11-26 05:30 UTC, 4310V343k commented on code/modules/mining/monsters.dm
> +			I.afterattack(corpse, user, proximity=TRUE)
```suggestion
			L.afterattack(corpse, user, TRUE)
```
По сути тревис должен перестать ебать мозг, но скорее всего это не сработает

2020-11-26 07:04 UTC, 4310V343k commented
Ладно, это сработало

2020-11-26 07:37 UTC, Kortez90 commented
Хайвлорд, хрен попадешь?

2020-11-26 08:40 UTC, LudwigVonChesterfield commented on code/modules/mining/monsters.dm
> +
```
else
    return ..()
```

нужен вызов родителя в аттакбае.

2020-11-26 09:51 UTC, BakerMontague commented
Чёрт возьми, единственная интересная вещь, которой не многие любили заниматься на шахте - создавать лазарусы и лечить страждущих или творить разные события по раунду и разводить людей. Вы не вводите что-то более интересное для развития состояния раунда по типу лаваленда, нет, вы удаляете возможности для разного рода ходов, стратегий и манипуляций. Нет чтобы пофиксить бинтик, нет же, давайте под корень убьем одну из самых главных фич шахты, которой вообще никто по сути не пользовался даже(да и так сложно было, ибо либо ученые подставят с БД, либо ресурсы не успеют добыться вовремя, а лазарусы это долго делается, так что раунд на миллион), но очень хорошую. Мед запас народной медицины! Даже до этого добрались, я аж глазам не верю. Руки бы оторвать.

2020-11-26 09:55 UTC, EdlerN commented
Бесконечный фарм реджувов - не баг а фича. Да, да, конечно.

2020-11-26 12:15 UTC, TungstenOctopus commented
Скриншоты из игры добавьте, в естественной среде обитания

2020-11-26 12:48 UTC, BakerMontague commented
> Бесконечный фарм реджувов - не баг а фича. Да, да, конечно.

И как часто ты видел этот "бесконечный" фарм лазарусами? Как часто это рушило что-то за все эти года на любом из серверов-билдов с лазарусами? Багом было только то что можно бинтом воскрешать лорда, остальное уже возможности.

2020-11-26 12:50 UTC, FelixRuin commented
ты оправдываешь баг, только и всего, ядра это жестокая имба, возможность её фармить - бред

2020-11-26 16:19 UTC, TungstenOctopus approved these changes

2020-11-29 09:59 UTC, Sakuya-Izayoi commented
а проблем с пиксельхантингом не будет?

2020-11-29 14:13 UTC, LudwigVonChesterfield commented
@Sakuya-Izayoi 

https://github.com/TauCetiStation/TauCetiClassic/pull/6422/files#diff-e09b643d5e4bfca603283066ccf2f1e235e117b850be25e82cf0e781cbc558a9R235

Хайвлорд когда живой покрывает весь тайл своим клик-хитбоксом.

2020-11-29 14:14 UTC, LudwigVonChesterfield requested changes
> **Сейчас денсити у хайвлорда хоть и меняется, но всё ещё проходим по неизвестным причинам...**

2020-11-29 14:15 UTC, LudwigVonChesterfield commented on code/modules/mining/monsters.dm
> +			L.afterattack(corpse, user, TRUE)
Может лучше сделать лазарусу какую-то функцию оживляющую мобов чтобы не надо было симулировать клики?

Типо
```
/lazarus_injector/proc/revive(mob/M)
  код который раньше был в afterattack

/lazarus_injector/afterattack(mob/M)
    if все нужные улосвия
        revive(M)
```

2020-11-29 14:16 UTC, LudwigVonChesterfield commented on code/modules/roguelike/mob_modifiers/negative.dm
> +	H.stop_automated_movement_when_pulled = TRUE
когда-нибудь обязательно нужно будет переделать на трейт если хотим чтобы модификаторы адекватно снимались-добавлялись(сейчас к примеру если два модификатора дёргали бы эту переменную, то выходило бы плохо)

ето не требование, это комментарий

2020-11-29 15:40 UTC, UDaV73rus commented
> > **Сейчас денсити у хайвлорда хоть и меняется, но всё ещё проходим по неизвестным причинам...**
я не знаю как это пофиксить, это было до меня
грустно.

2020-11-30 14:50 UTC, WatlerJe commented
Как он в плане секса, а точнее как по его мобам кликается?

2020-11-30 14:52 UTC, Kortez90 commented
> Как он в плане секса, а точнее как по его мобам кликается?

> Хайвлорд когда живой покрывает весь тайл своим клик-хитбоксом.

2020-12-01 08:27 UTC, TungstenOctopus commented
Кстати есть мнение, что оптимальным решением будет сделать какое-то полупрозрачное свечение на фоне этой чепухи летающей, тогда кликать по нему проблем не будет точно.

2020-12-01 08:33 UTC, 4310V343k commented
> Кстати есть мнение, что оптимальным решением будет сделать какое-то полупрозрачное свечение на фоне этой чепухи летающей, тогда кликать по нему проблем не будет точно.
> 
> А стоп, выше ответили, что он покрывает весь тайл. Это касается и клешней и самого лорда?

Решение раньше такое: у спрайта хайвлорда есть прозрачный фон(не именно НИЧЕГО на фоне, а он именно ПРОЗРАЧНЫЙ), из-за чего можно было тыкать по прозрачной части спрайта

2020-12-01 13:37 UTC, WatlerJe commented
Как вариант залить каждый кадр черным цветом со значением альфа 1 или бахнуть эллипс в центре с тем же значением, энивэй надо убедиться в том чтобы спрайт был не только красивый но и кликабельный.

2020-12-01 13:48 UTC, UDaV73rus commented
:dovolen:
невозможо кликать за астероидных мобов, так всегда было
mouse_opacity = 2 и спрайт покрывает весь тайл

2020-12-05 15:27 UTC, LudwigVonChesterfield approved these changes

2020-12-06 14:18 UTC, merged