Наушник-хамелеон
TauCetiStation/TauCetiClassic pull request #6427
Opened 2020-11-27 12:34 UTC by WallShrabnic

## Описание изменений
Добавляет наушник, способный принимать формы других наушников, а также интеркома и радио. Доступен триторам и нюкерам по практичной цене в 1 ТК.
## Почему и что этот ПР улучшит
Новый предмет триторам, который потенциально может дополнить арсенал скрытого или любящего пошутить предателя
## Авторство
wallshrabnic
## Чеинжлог
:cl:
- rscadd: Добавлен наушник-хамелеон, способный принимать вид других наушников, интеркома и радио

2020-11-27 12:34 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2020-11-27 12:36 UTC, KIBORG04 commented on code/game/objects/items/devices/radio/chameleon.dm
> +		headset_choices[V.name] = U
Сюда бы радиалочку

2020-11-27 12:38 UTC, KIBORG04 commented on code/game/objects/items/devices/radio/chameleon.dm
> +	update_inv_mob()
```suggestion
	update_inv_mob()
	
```

2020-11-27 12:39 UTC, KIBORG04 commented on code/game/objects/items/devices/radio/chameleon.dm
> +		headset_choices[V.name] = U
Ты зачем-то тут создаешь объект только ради имени, а потом сохраняешь тип. Ниже ты опять создаешь объект по этому типу. Измени тогда `V.name` на `initial(V.name)`, при этом выше убрав `new`

2020-11-27 19:35 UTC, Pivo24 commented
А в хамелеон-набор может?..
Зачем так?..

2020-11-28 11:27 UTC, WallShrabnic commented
> А в хамелеон-набор может?..
Зачем так?..

Из дискорда

> Сувать его в хамелеон-коробку мне кажется слишком жирным, учитывая что до неё могут дотянуться шаловливые ручки учёных

2020-11-28 14:00 UTC, Pivo24 commented
Всё ещё не догоняю, что страшного, если учёные получат простой наушник, способный менять цвета.

2020-12-01 20:39 UTC, WallShrabnic commented
Когда сделал изменения, но забыл их внести

2020-12-05 15:28 UTC, LudwigVonChesterfield commented
@WallShrabnic А всё же, что плохого в том что у ученых будет наушник который не может ни в какие каналы как часть хамелеон набора?

2020-12-07 09:13 UTC, LudwigVonChesterfield commented on code/game/objects/items/devices/radio/chameleon.dm
> +	for(var/U in typesof(/obj/item/device/radio/headset, /obj/item/device/radio/intercom,)-blocked)
Мне если честно кажется что такие  подходы "берём всё а дальше отфильтруется" не очень работают, см. мусор, и т.д.

Может лучше просто сделать список наушников в которые можно превратиться?

2020-12-07 09:13 UTC, LudwigVonChesterfield commented on code/game/objects/items/devices/radio/chameleon.dm
> +/obj/item/device/radio/headset/chameleon/verb/change()
В этой функции нигде не проверяется в состоянии ли менять состояние моб. мёртвые куколки смогут себе наушничек менять

2020-12-11 15:37 UTC, WallShrabnic commented on code/game/objects/items/devices/radio/chameleon.dm
> +/obj/item/device/radio/headset/chameleon/verb/change()
Как и везде в хамелеонках, но я за такую работу браться не буду, ибо маловато опыта и выйдет нерабочее говно

2020-12-11 15:39 UTC, LudwigVonChesterfield commented on code/game/objects/items/devices/radio/chameleon.dm
> +/obj/item/device/radio/headset/chameleon/verb/change()
Ты отказываешься добавить

```
if(incapacitated())
    return
```

... ?

2020-12-11 15:40 UTC, WallShrabnic commented on code/game/objects/items/devices/radio/chameleon.dm
> +	for(var/U in typesof(/obj/item/device/radio/headset, /obj/item/device/radio/intercom,)-blocked)
@LudwigVonChesterfield 
Они не будут захватывать объекты классом ниже? У меня уже так было когда я пытался радио отдельно сделать, и цеплялись всякие маячки.

В теории вообще можно наделать кучу dummy объектов, чтобы выбирало из них, но это гора работы, так что...

2020-12-11 15:41 UTC, LudwigVonChesterfield commented on code/game/objects/items/devices/radio/chameleon.dm
> +	for(var/U in typesof(/obj/item/device/radio/headset, /obj/item/device/radio/intercom,)-blocked)
Почитай как работает typesof() он берёт выбранный класс, и все подклассы.

2020-12-24 14:56 UTC, T6751 requested changes

2021-01-06 10:25 UTC, WallShrabnic commented
Пока прикрою, в будущем доделаю

2021-01-06 10:25 UTC, closed without merging