Перевод спам-сообщений ПДА на русский язык.
TauCetiStation/TauCetiClassic pull request #6428
Opened 2020-11-27 14:18 UTC by BesumniiChebureck

## Описание изменений
Перевод спам-сообщений с ПДА на славянский.
## Почему и что этот ПР улучшит
Если и использовать 513, так использовать по полной.
## Авторство
@BesumniiChebureck 
## Чеинжлог
:cl:
- spellcheck: Перевод спам сообщений ПДА на русский язык.

2020-11-27 14:18 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2020-11-27 14:40 UTC, Kortez90 commented
Похоже, что-то не так с кодировкой.
![Безымянный](https://user-images.githubusercontent.com/36198983/100460006-8278f880-30d7-11eb-8a8b-7ecff9ea0a42.png)

А по поводу перевода - он некачественный. Многие моменты переведены чуть ли не машинно.

2020-11-27 14:46 UTC, BesumniiChebureck commented
> Похоже, что-то не так с кодировкой

Хм, а как это можно исправить?

> А по поводу перевода - он некачественный. Многие моменты переведены чуть ли не машинно.

Уточни какие именно моменты? (Некоторые я исправлю прям сейчас...)

2020-11-27 14:53 UTC, Kortez90 commented
Если бы suggestion не ломал кодировку, было бы удобнее. Возможно дело в браузере.

```
message = pick("Тройные депозиты ждут вас на MaxBet Онлайн, когда вы зарегистрируетесь, чтобы играть у нас.",\
```
Как минимум выглядит как машинный перевод. Это же реклама, а не рассылка от роботов.
Что-то вроде `Тройные допозиты ждут вас на MaxBet Online при регистрации!`. Просто пример.

```
sender = pick(300;"СистемаБыстрыхЗнакомств",200;"Найди свою русскую невесту",50;"Таяранские красавицы ждут",50;"Найди свою тайную влюбленность в скреллок",50;"Красивые невесты Согханки")
```
Особенно забавный момент про `найди свою тайную влюбленность`. Это выражение `Find your secret skrell crush` обычно значит `Найди свою тайную любовь`. Ну или `Скрелльскую возлюбленную`.

```
sender = pick("Галактическая Платежная Ассоциация","Лучшее Бизнес-Бюро","Тау Кита E-Payments","Финансовый Департамент НаноТрейзен","Копии Люкс")
```
`E-Payments` тоже надо переводить, если что. Это электронные выплаты.

И так далее. Там подобного еще много.

2020-11-27 14:59 UTC, KIBORG04 commented on code/modules/events/pda_spam.dm
> +					sender = pick("MaxBet","MaxBet ������ ������","��� ������� ������� ��� �����������","� ���, ��� �� �������������� � ���")
```suggestion
					sender = pick("MaxBet","MaxBet Онлайн Казино","Нет лучшего времени для регистрации","Я рад, что ты присоединишься к нам")
```
Какая-то чертовщина

2020-11-27 15:00 UTC, Kortez90 commented on code/modules/events/pda_spam.dm
> +					sender = pick("MaxBet","MaxBet ������ ������","��� ������� ������� ��� �����������","� ���, ��� �� �������������� � ���")
Есть вероятность, что человек использует какой-нибудь Я.Браузер или вообще mac. К тому же, тревис упал и не поднимался с ~4 утра.

2020-11-27 15:07 UTC, BesumniiChebureck commented on code/modules/events/pda_spam.dm
> +					sender = pick("MaxBet","MaxBet ������ ������","��� ������� ������� ��� �����������","� ���, ��� �� �������������� � ���")
Да нет, Шиндовс, Хром. 

> А... Через что были залиты изменения?

Не ГитхабДесктопом если ты про это. А вообще git push -u origin some-awesome-feature там всякие, ну как по инструкции в общем.

2020-11-27 15:12 UTC, Kortez90 commented on code/modules/events/pda_spam.dm
> +					sender = pick("MaxBet","MaxBet ������ ������","��� ������� ������� ��� �����������","� ���, ��� �� �������������� � ���")
Попробуй веб-интерфейс.

2020-11-27 16:00 UTC, Kortez90 commented on code/modules/events/pda_spam.dm
> +					"����� 450 ������������� ��� � ������, ������� ��������, ���������� � ������������� 100 ���������� ������������� �� ���� ���������, ���� ��� � MaxBet!")
```suggestion
sender = pick("MaxBet","MaxBet Онлайн Казино","Зарегистрируйся прямо сейчас!","С нетерпением ждем вас!")
					message = pick("Тройные депозиты, ставки, казино всё это только на MaxBet Онлайн!",\
					"Зарегистрируйтесь на MaxBet Онлайн сегодня и получайте игровые бонусы!",\
					"Став игроком на MaxBet Онлайн, вы будете получать выгодные еженедельные акции и промокоды на 100 кредитов ежемесячно. Пройдите регистрацию прямо сейчас!",\
					"Более 450 первоклассных азартных игр, крупные выигрыши, надежность и проверенный миллионами пользователей сервис ожидают вас. MaxBet Онлайн!")
```

2020-11-27 16:05 UTC, Kortez90 commented on code/modules/events/pda_spam.dm
> +					"���� ���� �������, �������� ��� ����� ��������.")
```suggestion
				    sender = pick(300;"СистемаБыстрыхЗнакомств",200;"Найди свою Марсианскую невесту",50;"Таяранские красавицы ждут",50;"Найди свою тайную Скрелльскую возлюбленную",50;"Горячие Согханки Могеса")
					message = pick("Ваш профиль привлек мое внимание и я хотела бы узнать вас поближе. (Быстрые Знакомства).",\
					"Напишете мне на почту [pick(first_names_female)]@[pick(last_names)].[pick("ru","ck","tj","ur","nt")] и я обязательно отправлю вам мое фото. (Быстрые Знакомства).",\
					"Я хотела бы переписываться с вами. Надеюсь, что вы лайкните мой профиль и вы мне ответите. (Быстрые Знакомства).",\
					"У вас одно непрочитанное сообщение!",\
					"Ваше фото профиля, получило две новые симпатии.")
```

2020-11-27 16:19 UTC, Kortez90 commented on code/modules/events/pda_spam.dm
> +					"������� ���� ����� �������� �� ������������ ���������� �����, ������ � ������������ ����� �� ����...")
```suggestion
					sender = pick("Наймите Др. Максмана","Проблемы с эрекцией?")
					message = pick("Др. МАКСМАН: НАСТОЯЩИЕ Врачи, НАСТОЯЩАЯ Наука, НАСТОЯЩИЕ Результаты!",\
					"Др. Максман был создан Джорджем Окуляр , доктором медицинских наук, сертифицированным урологом CentComm, который вылечил более 70 000 пациентов во всем секторе от 'мужских проблем'.",\
					"После семи лет исследований, Др. Окуляр и его команда придумали эту простую и революционную формулу улучшения мужской силы.",\
					"Мужчины всех видов сообщают об ПОТРЯСАЮЩЕМ увеличении длины, ширины и выносливости.")
```

2020-11-27 16:27 UTC, Kortez90 commented on code/modules/events/pda_spam.dm
> +					"����������� ���, ���, � ���������� �������, ���, ������ ����� ��-�� ���������� �����������, � ������ ���, ����� �������� ������ ����� ���� ����������� ���������� � ������� 1,5 ��������� �������
```suggestion
					sender = pick("Др","Кронпринц","Король-Регент","Профессор","Капитан")
					sender += " " + pick("Роберт","Альфред","Джозефат","Кингсли","Сэхи","Збахи")
					sender += " " + pick("Мугаве", "Нкем", "Гбатоквия", "Нчеквубе", "Ндим", "Ндубиси")
					message = pick("ВАШ СЧЕТ БЫЛ ПЕРЕМЕЩЕН В [pick("Salusa","Segunda","Cepheus","Andromeda","Gruis","Corona","Aquila","ARES","Asellus")] БАНК РАЗВИТИЯ ДЛЯ ДАЛЬНЕЙШИХ ПЕРЕВОДОВ СРЕДСТВ.",\
					"Мы рады сообщить, что в связи с задержкой, нам было поручено НЕЗАМЕДЛИТЕЛЬНО перевести все средства на ваш счет.",\
					"Уважаемый получатель средств. Мы рады вам сообщить, что просроченная выплата средств была окончательно утверждена и переведена на ваш счет.",\
					"В связи с нехваткой моих агентов, мне требуется независимый финансовый счет, чтобы немедленно перевести на него 1 ТОЧКА ПЯТЬ МИЛЛИОНОВ кредитов.",\
					"Приветствую сэр. С сожалением сообщаю, что пока я здесь умираю, из-за отсутствия наследников, я выбрал вас, чтобы перевести полную сумму моих сбережений в размере 1,5 миллиарда кредитов.")
```

2020-11-27 16:32 UTC, Kortez90 commented on code/modules/events/pda_spam.dm
> +					"������ ������� ��������� ����� � PIN-��� ������ ����� � ����� �����������. ������ ��� ������� ����, ��������������� ������ WetSkrell.nt ������ ������!")
```suggestion
					sender = pick("Подразделение морального духа НаноТрасен","Одиноко?","Скучно?","www.wetskrell.nt")
					message = pick("Подразделение морального духа НаноТрейзен хочет обеспечить вас качественными развлекательными сайтами.",\
					"WetSkrell.nt - это ксенофильный веб-сайт, одобренный НТ для использования членами экипажа мужского пола во множестве станций и аванпостов.",\
					"Wetskrell.nt предоставляет только самое высокое качество мужских развлечений для сотрудников НаноТрасен!",\
					"Просто введите номер вашего счета и PIN-код. Сделав три простых шага, сервис развлекательных услуг станет вашими!")
```

2020-11-27 16:36 UTC, Kortez90 commented on code/modules/events/pda_spam.dm
> +					"�� �������� ������ �� �������� ������� ������ �������")
```suggestion
					sender = pick("Вы выиграли бесплатные билеты!", "Нажмите сюда, чтобы забрать свой приз!", "Вы - 1000-й посетитель!", "Вы счастливый обладатель нашего гран-при!")
					message = pick("Вы выиграли билеты на новейший фильм АКТИВНЫЙ ДЖЕКСОН!",\
					"Вы выиграли билеты на новейшую криминальную драму ДЕТЕКТИВНАЯ ЗАГАДКА В КАПЕРСАХ МОЛЛЮСКОВ!",\
					"Вы выиграли билеты на новейшую романтическую комедию 16 ПРАВИЛ ЛЮБВИ!",\
					"Вы выиграли билеты на новейший триллер КУЛЬТ ВСЕСПЯЩЕГО!")
```
Тут проблема, так как названия фильмов - игра слов и отсылки к режимам. 16 правил любви - отсылка к ЕРП. ACTION JAXSON - игра слов, которую на русски проблематично перевести, не меняя слова JAXSON. Ну и еще отсылка к яве и JSX.

2020-11-27 16:37 UTC, Kortez90 commented on code/modules/events/pda_spam.dm
> +						to_chat(ai, "<i>������������� ��������� �� <b>[sender]</b></i> (���������� / ����?) <i>to <b>[P:owner]</b>: [message]</i>")
```suggestion
                      to_chat(ai, "<i>Перехваченно сообщение от <b>[sender]</b></i> (Неизвестно / спам?) <i>to <b>[P:owner]</b>: [message]</i>")
```

2020-11-27 16:53 UTC, Kortez90 commented on code/modules/events/pda_spam.dm
> +					sender = pick("MaxBet","MaxBet ������ ������","��� ������� ������� ��� �����������","� ���, ��� �� �������������� � ���")
Дело сломанной кодировки тоже можно закрывать. Это из-за `git push`. Через веб-интерфейс работает.

2020-11-28 07:25 UTC, BesumniiChebureck commented
Готово к мержу. После фиксов Кортеза всё починено и работает нормально.
![image](https://user-images.githubusercontent.com/67091522/100496301-f3fe8880-3163-11eb-8a47-5aad878ccab3.png)

2020-11-28 07:35 UTC, Kortez90 commented
А остальные правки?

2020-11-28 07:41 UTC, BesumniiChebureck commented
<details>
<summary>Много букв осторожно</summary>
var/message
			switch(pick(1,2,3,4,5,6,7))
				if(1)
					sender = pick("MaxBet","MaxBet ������ ������","��� ������� ������� ��� �����������","� ���, ��� �� �������������� � ���")
					message = pick("������� ��������, ������, ������ �� ��� � �� ������ �� MaxBet ������ ��� ������!",\
					"��������������� �� MaxBet ������� � ��������� ������� ������ ��� ������!",\
					"���� ������� �� MaxBet, �� ����� ������ �������� �������� ������������ ����� � ��������� �� 100 �������� ����������, ������ ����������� ������!",\
					"����� 450 ������������� ��� � ������, ������� ��������, ���������� � ������������� 100 ���������� ������������� �� ���� ���������, ���� ��� � MaxBet!")
                  sender = pick("MaxBet","MaxBet Онлайн Казино","Зарегистрируйся прямо сейчас!","С нетерпением ждем вас!")
					message = pick("Тройные депозиты, ставки, казино всё это только на MaxBet Онлайн!",\
					"Зарегистрируйтесь на MaxBet Онлайн сегодня и получайте игровые бонусы!",\
					"Став игроком на MaxBet Онлайн, вы будете получать выгодные еженедельные акции и промокоды на 100 кредитов ежемесячно. Пройдите регистрацию прямо сейчас!",\
					"Более 450 первоклассных азартных игр, крупные выигрыши, надежность и проверенный миллионами пользователей сервис ожидают вас. MaxBet Онлайн!")
				if(2)
					sender = pick(300;"�����������������������",200;"����� ���� ����������� �������",50;"���������� ��������� ����",50;"����� ���� ������ ����������� ������������",50;"������� �������� ������")
					message = pick("��� ������� ������� ��� ��������, � � ����� �� ������ ��� ������� (������� ����������).",\
					"�������� ��� �� ����� [pick(first_names_female)]@[pick(last_names)].[pick("ru","ck","tj","ur","nt")] � � ����������� ������ ��� �� ������� ���� (������� ����������).",\
					"� ����, ����� �� ������ ���� ����� � �������, ��� ���� ���������� ��� ������� � �� ��� ���������� (������� ����������).",\
					"� ��� ���� ������������� ���������!",\
					"���� ���� �������, �������� ��� ����� ��������.")
					sender = pick(300;"СистемаБыстрыхЗнакомств",200;"Найди свою Марсианскую невесту",50;"Таяранские красавицы ждут",50;"Найди свою тайную Скрелльскую возлюбленную",50;"Горячие Согханки Могеса")
					message = pick("Ваш профиль привлек мое внимание, и я хотел бы узнать вас поближе (Быстрые Знакомства).",\
					"Напишете мне на почту [pick(first_names_female)]@[pick(last_names)].[pick("ru","ck","tj","ur","nt")] и я обязательно пришлю вам моё горячее фото (Быстрые Знакомства).",\
					"Я хочу, чтобы мы писали друг другу и надеюсь, что тебе понравится мой профиль и ты мне ответитишь (Быстрые Знакомства).",\
					"У вас одно непрочитанное сообщение!",\
					"Ваше фото профиля, получило две новые симпатии.")
				if(3)
					sender = pick("������������� ��������� ����������","������ ������-����","����������� ������� ��� ����","���������� ����������� �����������","����� ����")
					message = pick("������� ���� ��������� �� ��������� ����!",\
					"����, ��������� ������� � ����������, ����� � ������ ��������, �� �� ���������� ����� ������������� ����!",\
					"������� ������ 100 �������� � �������� �� 300% ������ ���������� ���������!",\
					"���������� �� ������ 100K.NT/WOWGOLD � �������� ������� ����������� 1000 �������� ���������� ���������!!!",\
					"�� �������� ������ �� ������ �� ����� �������� �� ��� ������� ��������� � ����.",\
					"����������� ������ ��� ������� ����� � ������ (�����������), ����� �������� �� ��� ������.")
					sender = pick("Галактическая Платежная Ассоциация","Лучшее Бизнес-Бюро","Электронные выплаты Тау Киты","Финансовый Департамент НаноТрейзен","Копии Люкс")
					message = pick("Премиум часы Галактика по небольшой цене!",\
					"Часы, Ювелирные Изделия и Аксессуары, Сумки и модные Кошельки, всё по последнему писку галактической моды!",\
					"Вложите первые 100 кредитов и получите на 300% больше совершенно бесплатно!",\
					"Переходите по ссылке 100K.NT/WOWGOLD и получите ГОРЯЧИЕ ПРЕДЛОЖЕНИЕ 1000 кредитов совершенно БЕСПЛАТНО!!!",\
					"Мы получили жалобу от одного из ваших клиентов на его деловые отношения с вами.",\
					"Убедительно просим Вас открыть ОТЧЕТ О ЖАЛОБЕ (прилагается), чтобы ответить на эту жалобу.")
				if(4)
					sender = pick("����������� ������� ��������","������ ����������������� ��������?")
					message = pick("������ �������: ��������� �������, ��������� �����, ��������� ����������!",\
					"������ ������� ��� ������ �������� ���������, �������� ����������� ����, ����������������� �������� CentComm, ������� ������� ����� 70 000 ��������� �� ����� ������� � '�������� ����������'.",\
					"����� ���� ��� ������������ ������ ������� � ��� ������� ��������� ��� ������� ������������� ������� ��������� ������� �������, ������� ������� ��...",\
					"������� ���� ����� �������� �� ������������ ���������� �����, ������ � ������������ ����� �� ����...")
					sender = pick("Приобретите Доктора Максмана","Имеете дисфункциональные проблемы?")
					message = pick("Доктор Максман: НАСТОЯЩИЕ доктора, НАСТОЯЩАЯ наука, НАСТОЯЩИЕ результаты!",\
					"Доктор Максман был создан Джорджем Акуиларом, доктором медицинских наук, сертифицированным урологом CentComm, который вылечил более 70 000 пациентов по всему сектору с 'мужскими проблемами'.",\
					"После семи лет исследований доктор Акуилар и его команда придумали эту простую революционную формулу улучшения мужских качеств, которая состоит из...",\
					"Мужчины всех видов сообщают об УДИВИТЕЛЬНОМ увеличении длины, ширины и выносливости всего от трех...")
				if(5)
					sender = pick("������","���������","������-������","���������","�������")
					sender += " " + pick("������","�������","��������","�������","����","�����")
					sender += " " + pick("������", "����", "���������", "��������", "����", "�������")
					message = pick("��� ���� ��� ��������� � [pick("Salusa","Segunda","Cepheus","Andromeda","Gruis","Corona","Aquila","ARES","Asellus")] ���� �������� ��� ���������� ��������� �������.",\
					"�� ���� �������� ���, ��� � ����� � ���������, ��� ���� �������� ��������������� ������ ��� �������� �� ��� ����.",\
					"��������� ���������� �������, ������ ��� ��������, ��� ������������ ������� ������� ���� ������������ ���������� � �������� � ������.",\
					"� ����� � ����������� � ���� ������� � ������, ����� �� ����������� ���������� ����� ���� ���������� ������� ����� � ������� 1 ������� ��������.",\
					"����������� ���, ���, � ���������� �������, ���, ������ ����� ��-�� ���������� �����������, � ������ ���, ����� �������� ������ ����� ���� ����������� ���������� � ������� 1,5 ��������� ��������.")
					sender = pick("Доктор","Кронпринц","Король-Регент","Профессор","Капитан")
					sender += " " + pick("Роберт","Альфред","Джозефат","Кингсли","Сэхи","Збахи")
					sender += " " + pick("Мугаве", "Нкем", "Гбатоквия", "Нчеквубе", "Ндим", "Ндубиси")
					message = pick("ВАШ ФОНД БЫЛ ПЕРЕМЕЩЕН В [pick("Salusa","Segunda","Cepheus","Andromeda","Gruis","Corona","Aquila","ARES","Asellus")] БАНК РАЗВИТИЯ ДЛЯ ДАЛЬНЕЙШИХ ПЕРЕВОДОВ СРЕДСТВ.",\
					"Мы рады сообщить вам, что в связи с задержкой, нам было поручено НЕЗАМЕДЛИТЕЛЬНО внести все средства на ваш счет.",\
					"Уважаемый получатель средств, просим вас сообщить, что просроченная выплата средств была окончательно утверждена и выпущена к оплате.",\
					"В связи с отсутствием у меня агентов я требую, чтобы на внебиржевом финансовом счете была немедленно внесена сумма в размере 1 миллион кредитов.",\
					"Приветствую вас, сэр, с сожалением сообщаю, что, умирая здесь из-за отсутствия наследников, я выбрал вас, чтобы получить полную сумму моих пожизненных сбережений в размере 1,5 миллиарда кредитов.")
				if(6)
					sender = pick("������������� ���������� ���� �����������","���������� ���� �������?","������?","www.wetskrell.nt")
					message = pick("������������� ���������� ���� ����������� ����� ������������ ��� ������������ ��������������� ���� WetSkrell.nt.",\
					"WetSkrell.nt - ��� ���������������� ���-� [...]

2020-11-28 07:43 UTC, Kortez90 commented
Я имел в виду предложения. Там все переписано.

2020-11-28 07:58 UTC, 4310V343k commented
Как минимум заметил несколько орфографических ошибок

2020-11-30 11:33 UTC, Kortez90 commented on code/modules/events/pda_spam.dm
> +					message = pick("Вы выиграли билеты на новейший фильм СПАСТИ КАПИТАНА ДЖОНИ!",\
Тут была отсылка к JSX, которую ты успешно похерил. Как и остальные отсылки. Сомневаюсь, что названиям фильмов вообще нужен перевод.

2020-11-30 11:42 UTC, KIBORG04 commented on code/modules/events/pda_spam.dm
> +					message = pick("Вы выиграли билеты на новейший фильм СПАСТИ КАПИТАНА ДЖОНИ!",\
К реакт.жиесу? Кто вообще знает какие-то ролики Экшен_Джексона?

2020-11-30 11:45 UTC, Kortez90 commented on code/modules/events/pda_spam.dm
> +					message = pick("Вы выиграли билеты на новейший фильм СПАСТИ КАПИТАНА ДЖОНИ!",\
Action Jaxon. JS, JSX, AS. Вариаций много.

2020-11-30 11:50 UTC, KIBORG04 commented on code/modules/events/pda_spam.dm
> +					message = pick("Вы выиграли билеты на новейший фильм СПАСТИ КАПИТАНА ДЖОНИ!",\
Нафиг вообще на него отсылку оставлять? Какой-то блогер-приколист, думаю, не только я первый раз про него слышу.

2020-11-30 11:52 UTC, KIBORG04 commented on code/modules/events/pda_spam.dm
> +					message = pick("Вы выиграли билеты на новейший фильм СПАСТИ КАПИТАНА ДЖОНИ!",\
Афтор, если хочешь оставить отсылку на ниггера, то переведи не как ты щас сделал, а типо `билет на ФИЛЬМ ЭКШЕН ДЖЕКСОНА`

2020-11-30 11:57 UTC, BesumniiChebureck commented on code/modules/events/pda_spam.dm
> +					message = pick("Вы выиграли билеты на новейший фильм СПАСТИ КАПИТАНА ДЖОНИ!",\
Ниггеру много чести чё-то.

2020-11-30 12:13 UTC, KIBORG04 commented on code/modules/events/pda_spam.dm
> +					message = pick("Вы выиграли билеты на новейший фильм СПАСТИ КАПИТАНА ДЖОНИ!",\
Ну, не настолько очевидную

2020-12-08 10:33 UTC, KIBORG04 commented
Поставь в тегах, что тут перевод.
Пример:
```
:cl:
 - ru: Перевод всех газет на русский язык
```

2020-12-08 11:55 UTC, BesumniiChebureck commented
> Поставь в тегах, что тут перевод.

Сделано. И... готово к мержу?

2020-12-08 12:02 UTC, KIBORG04 commented on code/modules/events/pda_spam.dm
> +					"Ваше фото профиля, получило две новые симпатии.")
Ты тут соблюдаешь конкатенацию(или как там в русском языке правильно, что слова слитно) `СистемаБыстрыхЗнакомств`

Ниже же ты пишешь не слитно `(Быстрые Знакомства)`

2020-12-08 12:04 UTC, KIBORG04 commented on code/modules/events/pda_spam.dm
> +					sender = pick("Галактическая Ассоциация Выплат","Лучшее Бюро Бизнеса","Электронные выплаты Тау Кита","Финансовый Департамент НаноТрейзен","Роскошные реплики")
Мб, Галактическая Платежная Ассоциация?

2020-12-08 12:05 UTC, KIBORG04 commented on code/modules/events/pda_spam.dm
> +					"Часы, Ювелирные Изделия и Аксессуары, Сумки и модные Кошельки!",\
Будет выглядеть лучше, если ты и к часам найдешь пару, потому что дальше идут синонимы через союз И.

А так же зачем ты добавил `модные` ?

2020-12-08 12:08 UTC, KIBORG04 commented on code/modules/events/pda_spam.dm
> +					"Доктор Максман был создан Джорджем Алленом, магистром медицинских наук, сертифицированным урологом CentComm, который вылечил более 70 000 пациентов во всем секторе от 'мужских проблем'.",\
Если пишешь НаноТрейзен на русском, то мб и центкомм перевести?

2020-12-08 12:12 UTC, KIBORG04 commented on code/modules/events/pda_spam.dm
> +					"В связи с нехваткой моих агентов, мне требуется независимый финансовый счет, чтобы немедленно перевести на него 1 ТОЧКА ПЯТЬ МИЛЛИОНОВ кредитов.",\
> 1 POINT FIVE MILLION

Тут поинт идет не как `ТОЧКА`, а как ПОЛТОРА МИЛЛИОНА. 1 POINT FIVE значит 1.5

2020-12-08 12:15 UTC, KIBORG04 commented on code/modules/events/pda_spam.dm
> +					"Приветствую сэр. С сожалением сообщаю, что пока я здесь умираю, из-за отсутствия наследников, я выбрал вас, чтобы перевести полную сумму моих сбережений в размере 1,5 миллиарда кредитов.")
Сэр - обращение, запятую надо
` С сожалением сообщаю, что пока я здесь умираю, из-за отсутствия наследников,` - перед из-за не нужна запятая, эта же часть принадлежит подчинительному предложению (или как там в русском языке правильно термины... )

2020-12-08 12:17 UTC, BesumniiChebureck commented on code/modules/events/pda_spam.dm
> +					"Доктор Максман был создан Джорджем Алленом, магистром медицинских наук, сертифицированным урологом CentComm, который вылечил более 70 000 пациентов во всем секторе от 'мужских проблем'.",\
Да. Я переводил, но забыл сохранить.

2020-12-08 12:18 UTC, Kortez90 commented on code/modules/events/pda_spam.dm
> +					sender = pick("Галактическая Ассоциация Выплат","Лучшее Бюро Бизнеса","Электронные выплаты Тау Кита","Финансовый Департамент НаноТрейзен","Роскошные реплики")
"Galactic Payments Association". Так что нет.

2020-12-08 12:19 UTC, BesumniiChebureck commented on code/modules/events/pda_spam.dm
> +					"В связи с нехваткой моих агентов, мне требуется независимый финансовый счет, чтобы немедленно перевести на него 1 ТОЧКА ПЯТЬ МИЛЛИОНОВ кредитов.",\
Сначала хотел написать 1.5, но подумал что так лучше, звучит более эмоционально что ли? Да и в оригинале тоже не просто так не 1.5

2020-12-08 12:23 UTC, Kortez90 commented on code/modules/events/pda_spam.dm
> +					"Часы, Ювелирные Изделия и Аксессуары, Сумки и модные Кошельки!",\
Часы, изделия и аксессуары, сумки и кошельки.  В чем проблема?

2020-12-08 12:24 UTC, KIBORG04 commented on code/modules/events/pda_spam.dm
> +					"В связи с нехваткой моих агентов, мне требуется независимый финансовый счет, чтобы немедленно перевести на него 1 ТОЧКА ПЯТЬ МИЛЛИОНОВ кредитов.",\
Я хз какая культура у нас в сосаке, но пендосы используют точку просто для того, чтобы показать, что число дробное. В СНГ комфортней звучит полтора, чем один точка пять, чем одна целая пять десятых
```
point – точка в числах, десятичных дробях и ценах. Обратите внимание, что в англоговорящих странах для обозначения десятичной дроби используют точку, а не запятую и цифры после точки произносятся по отдельности.

Примеры:
3.45 – three point four five
87.634 – eighty seven point six three four
0.78 – zero point seven eight, или просто point seven eight
```

2020-12-08 12:26 UTC, BesumniiChebureck commented on code/modules/events/pda_spam.dm
> +					"Приветствую сэр. С сожалением сообщаю, что пока я здесь умираю, из-за отсутствия наследников, я выбрал вас, чтобы перевести полную сумму моих сбережений в размере 1,5 миллиарда кредитов.")
```из-за отсутствия наследников``` - не часть ```что пока я здесь умираю```. ```Я выбрал вас``` почему? ```Из-за отсутствия наследников```, если не ошибаюсь, это последовательное подчинение, но даже если и нет, запятая там всё равно нужна.

2020-12-08 12:26 UTC, Kortez90 commented on code/modules/events/pda_spam.dm
> +					"Приветствую сэр. С сожалением сообщаю, что пока я здесь умираю, из-за отсутствия наследников, я выбрал вас, чтобы перевести полную сумму моих сбережений в размере 1,5 миллиарда кредитов.")
Нужна, так как не обобщенная часть не относится ко второй.

2020-12-08 12:28 UTC, KIBORG04 commented on code/modules/events/pda_spam.dm
> +					sender = pick("Галактическая Ассоциация Выплат","Лучшее Бюро Бизнеса","Электронные выплаты Тау Кита","Финансовый Департамент НаноТрейзен","Роскошные реплики")
Ну так там ведь оригинале нету "Galactic Association of Payments", что бы делать "Выплат"

2020-12-08 12:28 UTC, KIBORG04 commented on code/modules/events/pda_spam.dm
> +					"Часы, Ювелирные Изделия и Аксессуары, Сумки и модные Кошельки!",\
Проблем нет, просто выглядит странно для меня.

2020-12-08 12:29 UTC, KIBORG04 commented on code/modules/events/pda_spam.dm
> +					"Приветствую сэр. С сожалением сообщаю, что пока я здесь умираю, из-за отсутствия наследников, я выбрал вас, чтобы перевести полную сумму моих сбережений в размере 1,5 миллиарда кредитов.")
Ок, теперь придираюсь только к обращению

2020-12-08 12:30 UTC, Kortez90 commented on code/modules/events/pda_spam.dm
> +					sender = pick("Галактическая Ассоциация Выплат","Лучшее Бюро Бизнеса","Электронные выплаты Тау Кита","Финансовый Департамент НаноТрейзен","Роскошные реплики")
Какой кошмар. В описании спама кто-то сделал ошибку. Невероятно. Этого же не может быть!

2020-12-08 12:30 UTC, BesumniiChebureck commented on code/modules/events/pda_spam.dm
> +					"Ваше фото профиля, получило две новые симпатии.")
В оригинале точно также, не вижу проблем и у нас написать слитно, ибо это название приложения. 

> Ниже же ты пишешь не слитно (Быстрые Знакомства)

Опять же, в оригинале написано так, у меня не дословный перевод, но так выглядит ИМХО лучше.

2020-12-08 12:32 UTC, Kortez90 commented on code/modules/events/pda_spam.dm
> +					"Ваше фото профиля, получило две новые симпатии.")
В оригинале написано слитно.

2020-12-08 12:37 UTC, KIBORG04 commented on code/modules/events/pda_spam.dm
> +					sender = pick("Галактическая Ассоциация Выплат","Лучшее Бюро Бизнеса","Электронные выплаты Тау Кита","Финансовый Департамент НаноТрейзен","Роскошные реплики")
Есть принципиальная разница между тем, кто в спаме выплачивает деньги? 
Поидее, Ассоциация Выплат - это те, кто готов платить, а Платежная Ассоциация - какое-то сборище банковых организаций. Да даже в России есть национальная платежная ассоциация

2020-12-08 17:32 UTC, LudwigVonChesterfield commented on code/modules/events/pda_spam.dm
> +					"Часы, Ювелирные Изделия и Аксессуары, Сумки и модные Кошельки!",\
А почему каждый объект с большой буквы... ? Особенно "Ювелирные Изделия" в то время как "модные Кошельки"

2020-12-08 17:35 UTC, LudwigVonChesterfield commented on code/modules/events/pda_spam.dm
> +					"Приветствую сэр. С сожалением сообщаю, что пока я здесь умираю, из-за отсутствия наследников, я выбрал вас, чтобы перевести полную сумму моих сбережений в размере 1,5 миллиарда кредитов.")
> Приветствую сэр. С сожалением сообщаю, что пока я здесь умираю, из-за отсутствия наследников, я выбрал вас, чтобы перевести полную сумму моих сбережений в размере 1,5 миллиарда кредитов

А никого не смущает, что может показаться что он умирает из-за отсутствия наследников из-за того что кто-то надмозгово перевёл "as I"

Предлагаю следующее:

"Приветствую, сэр. С сожалением сообщаю, что я умираю. И из-за отсутствия наследников я выбрал вас, чтобы перевести полную сумму моих сбережений"

2020-12-08 18:46 UTC, DenchikPozhiloyTranslator commented on code/modules/events/pda_spam.dm
> +					"Приветствую сэр. С сожалением сообщаю, что пока я здесь умираю, из-за отсутствия наследников, я выбрал вас, чтобы перевести полную сумму моих сбережений в размере 1,5 миллиарда кредитов.")
Господи, не понимаю зачем так душнить. Вас никто не заставляет переводить дословно, спам сообщения это чисто прикол который должен доставить тебе пару хихиков, почему бы тогда и не сделать переведённый вариант хоть немного смешнее добавив хоть немного иронии? Иначе какой смысл вообще оставлять эти пресные сообщения в игре, кроме как раздражитель для пары игроков которые пользуются ПДА? Может стоит задуматься почему на английском эти спам сообщения вызывают улыбку, а в этом переводе нет? Где хоть какая то ориентированность на русскую аудиторию, для которой это всё и подразумевалось? Работа переводчика это в первую очередь задача требующая креативного мышления а не тупого копипаста в гугл транслейт и обратно. 
Почему нельзя поиграться с регистром? Почему нельзя подумать насчёт более доступных референсов на русский манер?
Если делаете перевод то хотя бы старайтесь над ним. У вас даже нет заказчика который ограничивает вас в действиях, ну так и придумайте что нибудь остроумнее на манер оригинала. Для такой работы требуется время, чувство вкуса и знание культуры обоих языков, а если нет ни одного из перечисленного за такое лучше и не браться.
В данный момент ваш вариант перевода вызывает во мне чувство испанского стыда только от одного прочтения, и никаких хихиков, и никакой ржаки.

2020-12-08 18:52 UTC, Kortez90 commented on code/modules/events/pda_spam.dm
> +					"Приветствую сэр. С сожалением сообщаю, что пока я здесь умираю, из-за отсутствия наследников, я выбрал вас, чтобы перевести полную сумму моих сбережений в размере 1,5 миллиарда кредитов.")
Это платформа для вноса изменений в код, а не для переводов и переводчиков. Чего ты ожидал тут найти?

Перевод и рерайт - разные вещи. Как и перевод с адаптацией. Здесь только перевод и в целом он дословный. Хочешь сделать по-своему - вперед. Никто не запрещал.

А заказчик с "своим взглядом на этот мир" вон там сидит. В углу с табличкой "маинтейнер".

2020-12-08 19:04 UTC, DenchikPozhiloyTranslator commented on code/modules/events/pda_spam.dm
> +					"Приветствую сэр. С сожалением сообщаю, что пока я здесь умираю, из-за отсутствия наследников, я выбрал вас, чтобы перевести полную сумму моих сбережений в размере 1,5 миллиарда кредитов.")
Ну так и зачем тогда браться за перевод если вы не готовы сделать его качественно? Может тогда луучше так и оставить английский вариант, в игре, которая изначально была сделана на английском и для игры требует хоть какой нибудь мало-мальской базы английского?

2020-12-08 19:32 UTC, TauKitty commented
This pull request has been mentioned on **Tau Ceti Station Forum**. There might be relevant details there:

https://forum.taucetistation.org/t/perevod-ss13-dlya-servera-tau-ceti/21675/28

2020-12-23 14:47 UTC, Kortez90 requested changes

2020-12-23 14:47 UTC, Kortez90 commented on code/modules/events/pda_spam.dm
> +					message = pick("ВАШ СЧЕТ БЫЛ ПЕРЕМЕЩЕН В [pick("Salusa","Segunda","Cepheus","Andromeda","Gruis","Corona","Aquila","ARES","Asellus")] БАНК РАЗВИТИЯ ДЛЯ ДАЛЬНЕЙШИХ ПЕРЕВОДОВ СРЕДСТВ.",\
```suggestion
					message = pick("ВАШ СЧЕТ БЫЛ ПЕРЕМЕЩЕН В БАНК РАЗВИТИЯ [pick("Salusa","Segunda","Cepheus","Andromeda","Gruis","Corona","Aquila","ARES","Asellus")]  ДЛЯ ДАЛЬНЕЙШИХ ПЕРЕВОДОВ СРЕДСТВ.",\
```

2020-12-23 14:58 UTC, merged