Фикс пропавшего спрайта тыквы.
TauCetiStation/TauCetiClassic pull request #6434
Opened 2020-11-28 13:17 UTC by Kortez90

## Описание изменений
По каким-то странным причинам пропал спрайт тыквы. Возможно, из-за кавычек.
Теперь должно работать.
Также перевел тыкву в раздел `/hardhat`, так как там уже есть код переключения света и плодить тоже самое в еще одном файле нет смысла.
## Почему и что этот ПР улучшит
Fix #6414.
## Авторство

## Чеинжлог
:cl: Kortez90
 - bugfix: Спрайт тыквы вернулся на место.

2020-11-28 13:17 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2020-11-28 13:19 UTC, 4310V343k commented
Тестил?

2020-11-28 13:20 UTC, Kortez90 commented
Так точно.

2020-11-28 13:21 UTC, 4310V343k commented on code/modules/clothing/head/misc_special.dm
>  	icon_state = "hardhat0_pumpkin"//Could stand to be renamed
```suggestion
	icon_state = "hardhat_pumpkin"
```

2020-11-28 13:21 UTC, 4310V343k commented on code/modules/clothing/head/misc_special.dm
>  	icon_state = "hardhat0_pumpkin"//Could stand to be renamed
Так же на строчку ниже, а item_color можно и убрать

2020-11-28 13:22 UTC, Kortez90 commented on code/modules/clothing/head/misc_special.dm
>  	icon_state = "hardhat0_pumpkin"//Could stand to be renamed
Ноль там переключает свет. Как и у остальных шапок со светом.

2020-11-28 13:22 UTC, 4310V343k commented on code/modules/clothing/head/misc_special.dm
>  	icon_state = "hardhat0_pumpkin"//Could stand to be renamed
https://github.com/TauCetiStation/TauCetiClassic/pull/6315

2020-11-28 13:23 UTC, 4310V343k commented on code/modules/clothing/head/misc_special.dm
>  	icon_state = "hardhat0_pumpkin"//Could stand to be renamed
Не знаю как у тебя это работало, возможно у тыквы такие спрайты с ноликом

2020-11-28 13:27 UTC, Kortez90 commented on code/modules/clothing/head/misc_special.dm
>  	icon_state = "hardhat0_pumpkin"//Could stand to be renamed
Твой ПР не вошел в мой билд. D:
Сейчас починим...

2020-12-06 15:28 UTC, T6751 requested changes

2020-12-06 15:28 UTC, T6751 commented on code/modules/clothing/head/misc_special.dm
> +	item_state = "hardhat_pumpkin0"
![image](https://user-images.githubusercontent.com/66636084/101284374-c4e5b800-37f0-11eb-9ded-1265b0c0b4f5.png)

```suggestion
	icon_state = "hardhat_pumpkin"//Could stand to be renamed
	item_state = "hardhat_pumpkin"
```

2020-12-06 15:39 UTC, 4310V343k commented on code/modules/clothing/head/misc_special.dm
>  	icon_state = "hardhat0_pumpkin"//Could stand to be renamed
Прикольно починил с руки тильды, спасибо

2020-12-06 16:38 UTC, T6751 approved these changes

2020-12-07 09:27 UTC, merged