sleeper density = 1
TauCetiStation/TauCetiClassic pull request #6440
Opened 2020-11-29 11:37 UTC by BesumniiChebureck

## Описание изменений
density у слипера теперь = 1 (стал твердым и непроходимым как консоли)
## Почему и что этот ПР улучшит
fix #6373
## Авторство

## Чеинжлог
:cl:
- bugfix: Слипер стал непроходимым объектом.

2020-11-29 11:37 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2020-11-29 12:04 UTC, Sakuya-Izayoi commented
зачем делать мед теснее?

2020-11-29 12:12 UTC, Kortez90 commented
Слипер - машинерия. Через него нельзя ходить. То, что отсек маленький - проблема карты.

2020-11-29 12:19 UTC, Morair commented
Никто не фиксил чтоб прожектайлы попадали по мобам в density объектах(привет каталка), так что наверно не стоит без фикса так делать...

2020-11-29 12:38 UTC, BesumniiChebureck commented
> зачем делать мед теснее?

Чисто логически представь как кукла будет ходить по тайлу, который полностью занимает слипер, как на этот тайл должны вставать шкафы/ящики и прочее. Мед никто не уменьшал, там достаточно места и без этих двух тайлов по уголкам.

2020-11-29 12:44 UTC, FelixRuin commented
Залез в слипер, вылез из слипера - пошёл дальше
при том это делается почти мгновенно
выглядит как возможность делать хитрые створки против мобов...

2020-12-01 14:37 UTC, BesumniiChebureck commented
Если что, через слипер нельзя пройти если в нем находится какой-либо моб, поэтому ставить денсити один, было не лучшим решением, хоть и всё ещё можно наступать на тайл с ним если он открыт (нет окупанта).

2020-12-06 15:19 UTC, T6751 requested changes

2020-12-06 15:19 UTC, T6751 commented on code/game/machinery/Sleeper.dm
> +	layer = 2.75
Вместо магического числа 2.75 лучше использовать дефайн. Если нет подходящего, то создать.
https://github.com/TauCetiStation/TauCetiClassic/blob/9da5eb98f55037c71f158f17e42505f1e92904d2/code/__DEFINES/_planes%2Blayers.dm#L98

2020-12-09 10:57 UTC, Kortez90 commented on code/game/machinery/Sleeper.dm
> +	layer = 2.7
```suggestion
	layer = BELOW_CONTAINERS_LAYER
```

2020-12-13 09:33 UTC, T6751 approved these changes

2020-12-13 09:40 UTC, merged