[WIP] Alien fixes
TauCetiStation/TauCetiClassic pull request #6453
Opened 2020-11-30 19:43 UTC by Ahion

## Описание изменений
В общем, загорелся починить этот режим. Не знаю, получиться ли у меня вернуть его в ротацию. На гите очень мало иссуев, но кое-какие баги я сам нешел. Кое-что изменил. Итак по порядку:

1. Сам режим не запускался. Происходило это из-за не правильной проверки точек спавна алиенов. `can_start()` пытался найти их в `landmarks_list`, но их там быть не могло, потому что ещё при загрузке сервера все `xeno_spawn` точки перемещались в `xeno_spawn` лист.

1. Теперь при старте режима алиены появляются не как лицехваты, а как лярвы. Начинать режим с лицехватов - крайне плохая идея. Сразу нужно кого-то заразить, даже если заразил, то эмбрион скорее всего вырежут. Режим быстро палиться, лярв нет,  привет экста)) Крайне тяжелый старт.

1. Алиены не могли в граб, соответственно не могли никого проглотить. Починил.

1. Если тебя проглотили, то ты мог прописать апперкот (да любую комбуху) алиену и вылезти из желудка. Это явно так не задумывалось. Запретил атаковать всем, кто находится в желудке. Напомню, чтобы вылезти, нужно взять острый предмет в руку и подвигаться. Алиена гибнет.

1. Добавил прогрессбар алиенам при изрыгании содержимого желудка. На того, кого выплюнули, повеситься небольшой стан.

1. Хантеры при инвизе тратят плазму. Но когда плазма кончалась - не выходили из инвиза. Более того. В инвизе хантеру было аблосютно наплевать на окружающую среду: на огонь и температуру. Я сделал так, что хантер больше не неуязвим для огня в инвизе, и выходит из него, если плазма кончилась. Единственное, если он находится на сорняке, то плазма даже в инвизе будет восстанавливаться по 2 пункта, т.е. не кончиться никогда. Есть ли в этом критика, будет видно по результатам тестов режима.

1. Еще фиксил rest у хантера. Если он отдыхает и пытается прыгнуть (leap), то спрайт хантера повернутым оставался.

1. fix #5799. Вот в чем был косяк. Если лицехват управляется игроком и он на кого-то прыгал, то в эмбрион помещалась лярва с игроком и эта лярва сразу же начинала расти. Теперь лярва не растет в эмбрионе.

1. При введении эмбриона, на зараженного навешивается ХУД, отображающий этапы роста эмбриона. Видят этот худ не только алиены, но и сам зараженный, к сожалению. Видеть он его, я думаю не должен. Но это я не починил пока и не знаю получиться ли. Но починил я рантаймы, которые возникали, если заразить моба без `mind`'a, так как прок худа вызывается от этого датума.

1. У эмбриона были проблемы с проком `AttemptGrow()`, который вызывается, когда эмбрион достиг последней, пятой стадии роста. Этот прок опрашивает доступных гостов и ждет ответа 30 сек. И пока он ждет, процесс роста эмбриона не останавливался и прок `AttemptGrow()` вызывался опять, и опять, и опять. Он стакался, пока не кончатся первые 30 секунд и спамил гостам. Для фикса переместил `STOP_PROCESSING(SSobj, src)`.

1. fix #1669. У прока `AttemptGrow()` была и другая проблема. Желающие вселиться в лярву госты, не могли вселиться, потому что в лярву передавался `client` госта, а не `key`. Из-за этого выполнялось другое условие прока и в лярву вселялся игрок, управляющий зараженной куклой. Именно по этой причине "_после того, как из тушки космонавта вылезает алиен, этого самого космонавта нельзя клонировать_". После фикса, пробовал клонировать, гост из тушки не куда не девается и всё прекрасно клонируется.

1. Исправил ещё один баг играбельного лицехвата. Если его снять с лица, то игрок больше не мог управлять лицехватом, так как `/mob/living/carbon/xenomorph/facehugger`, управляемый игроком, всё ещё находился внутри `/obj/item/clothing/mask/facehugger`. Добавил прок `/obj/item/clothing/mask/facehugger/dropped()`, исправляющий это.

1. Рантаймило про бросании лицехвата. Добавил проверку в `/obj/item/clothing/mask/facehugger/proc/CanHug`

1. Ну и последнее.  Лицехватов нельзя было кидать дальше 1 клетки. Я убрал ему `throw_range = 1`, не  знаю зачем это сделали. Теперь можно бросаться в людишек лицехватами, круто же...))

Я постараюсь собрать добровольцев у себя на локалке и покатать этот режим, что-бы выявить ещё баги и геймплейные дыры.

Ещё думаю над завершением раунда. Этот вопрос поднимался в какой-то темке не форуме. Надо определить чёткие критерии завершения режима, а не как сейчас - по вызову шаттла.

 
## Почему и что этот ПР улучшит
Режим infestation и игру за алиенов
## Авторство
Ahio
## Чеинжлог
:cl: Ahio
 - bugfix[link]: Исправлены баги алиенов и режима infestation
 - tweak: Алиены при режиме infestation начинают с формы larva

2020-11-30 19:43 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2020-11-30 20:16 UTC, Kortez90 commented
>нужно взять острый предмет в руку и подвигаться. Алиена гибнет.

Бред.

По поводу багов, у ларвы-эмбриона был баг счетчика, который в панели `stat` доходил до конца, но вырваться из груди человека было нельзя. А там был второй счетчик.

По поводу завершения режима - достаточно и шаттла, но стоит сделать проверку последнего живого человека на станции и автоматический вызов шаттла, если таких нет.

И зови, если надо на локалке потестить. Дискорд: Kortez#3083.

2020-11-30 20:17 UTC, Akellazp commented
Алиенам нужно пуш пофиксить. Он им заменил стандартный дизарм и они вообще не могут никого нокнуть.

2020-11-30 20:26 UTC, Kortez90 commented
>  попытайся объяснить почему так думаешь

А язвить не надо.
Вроде очевидно, что это ломает баланс сил, который и без того в плачевном состоянии. Особенно учитывая местных любителей трогать механики в разных местах и ищущих способы убийства друг друга. Если дать людям возможность вырываться из желудка, то в кармане они будут носить что угодно острое, специально скармливаясь чужим, чтобы их гибать.

2020-11-30 20:42 UTC, Akellazp commented
Какбы алиенам не обязательно сжирать человека чтобы что-либо с ним сделать

2020-12-01 06:19 UTC, EdlerN commented
> По поводу завершения режима - достаточно и шаттла, но стоит сделать проверку последнего живого человека на станции и автоматический вызов шаттла, если таких нет.

Такая себе идея. Режим нужно доделывать основательно, иначе это получается никому не нужная хрень уровня нинж, которая интересна сугубо ролям.

2020-12-01 07:02 UTC, Ahion commented
> > нужно взять острый предмет в руку и подвигаться. Алиена гибнет.
> 
> Бред.

Этот механ уже есть в игре, не я его ввел. Пока не понятно, стоит ли его менять

2020-12-01 08:41 UTC, Kortez90 commented
>  Режим нужно доделывать основательно, иначе это получается никому не нужная хрень уровня нинж, которая интересна сугубо ролям.

Отнюдь. РП тут уже много лет как не пахнет, так что режим не серьезнее той же нюки. Чужие убивают экипаж, экипаж убивает чужих. Всем весело.

А по поводу конца режим, то вариаций много, я лишь предложил меры предосторожности, которые стоило бы добавить для всех режимов. А самих алиенов можно заканчивать как вызовом обр, для подрыва нюки и в случае провала раунд заканчивается без шаттла, так и "по-блобовски". Если алиены захватят достаточный процент станции или убьют достаточное кол-во экипажа, то либо вызывается обр, либо раунд заканчивается без шаттла.

2020-12-01 11:17 UTC, Zmey25 commented
Вариант конца - численность алиенов. Можно потестить, победа алиенов - условно начиная от 10шт и до >50% от численности экипажа. Победа людей - 0 алиенов. Вызов шаттла во втором случае опционально.

2020-12-03 10:57 UTC, TauKitty commented
This pull request has been mentioned on **Tau Ceti Station Forum**. There might be relevant details there:

https://forum.taucetistation.org/t/chinim-rezhim-infestation/22623/1

2020-12-03 16:57 UTC, cool20141 commented
Жесть, а румарины сдохли :(

2020-12-03 17:33 UTC, volas commented
> Ещё думаю над завершением раунда. Этот вопрос поднимался в какой-то темке не форуме. Надо определить чёткие критерии завершения режима, а не как сейчас - по вызову шаттла.

старт тоже, писал тут https://forum.taucetistation.org/t/golosovanie-alienov-v-sikrety/11995/15?u=volas

Для окончания можно какое-то ratio, может как у блоба захват клеток, гибель квин(ы) для луза.

> Ну и последнее. Лицехватов нельзя было кидать дальше 1 клетки. Я убрал ему throw_range = 1, не знаю зачем это сделали. Теперь можно бросаться в людишек лицехватами, круто же...))

абузили

Пока режим не в ротации, всё сразу не обязательно, и есть место для экспериментов.

2020-12-11 15:21 UTC, Ahion commented
Сделал отдельный ХУД для эмбриона. Видеть будут его только алиены. У самих алиенов скрыл собственные худы, они не нужны. После мержа #6514 худ заражения эмбрионом будет отображаться на мобах не зависимо от того управляет им игрок или нет.

Если лярва находится в эмбрионе, то в статус панели будет показан прогресс роста эмбриона. Об этом говорилось в #5799

У алиенов убрал проверку на `has_brain()` - это актуально только для хуманов

2020-12-11 15:35 UTC, kiVts commented
Бред конечно и фигня, к комментарию предиратся, но Я буду не Я если нет 
![image](https://user-images.githubusercontent.com/48099872/101922827-9a06b580-3b9c-11eb-86a3-4f54b6bb0430.png)

2020-12-11 15:39 UTC, Ahion commented
Что ты скрин кидаешь. Исправь как должно быть, в гите есть для этого инструменты

2020-12-11 16:38 UTC, kiVts commented
Да даже стыдно исправлять что на такую фигню придираюсь

2020-12-11 16:53 UTC, Ahion commented
@kiVts сарказм что-ли? Ничего стыдного, буду рад твоей помощи

2020-12-11 17:12 UTC, kiVts requested changes
Runtime

2020-12-11 17:12 UTC, kiVts commented on code/modules/mob/living/carbon/xenomorph/special/facehugger/facehugger.dm
> +		return FALSE
Дело в том что.... это комментарий

2020-12-11 17:46 UTC, Ahion commented on code/modules/mob/living/carbon/xenomorph/special/facehugger/facehugger.dm
> +		return FALSE
исправлю, не заметил

2020-12-12 09:59 UTC, Ahion commented
Обнаружил что ХУД для эмбриона работает не так как нужно. Сейчас всё исправил, протестил, вроде работает как задумано. Ну и обошелся без изменений, указанных в #6514

2020-12-24 17:26 UTC, Kortez90 commented on code/modules/mob/living/carbon/xenomorph/special/facehugger/facehugger.dm
> +	if(!current_hugger && istype(loc,/turf)) //not in hands
```suggestion
	if(!current_hugger && istype(loc, /turf)) //not in hands
```

2020-12-24 17:28 UTC, Ahion commented on code/modules/mob/living/carbon/xenomorph/special/facehugger/facehugger.dm
> +	if(!current_hugger && istype(loc,/turf)) //not in hands
ok

2020-12-24 17:40 UTC, Ahion commented
Статус [WIP] снимаю. Больше нового в этот ПР добавлять не буду. Остальное буду делать отдельными ПРами. Можно ревью, ТМ и мерж))

2020-12-26 20:42 UTC, Kortez90 commented
@Ahion.
Надо дополнить описание и измененные фичи, если они теперь как-то отличаются от написанного.
И чейнджлог надо дополнить. Дописать важные для игроков вещи, например. О том, что можно вселиться в ларву и так далее.

2020-12-27 07:37 UTC, Ahion commented
Обновил описание ПРа, то что добавил идет после **UPD:**
Багов исправлено много, поэтому в чейнджлоге у меня ссылка на ПР. Не думаю что нужно что-то отдельно добавить в чейнджлог, кроме этого: _tweak: Алиены при режиме infestation начинают с формы larva_.
То что нельзя было вселиться в лярву - это баг, который я починил с самого начала. Он указан в описании. Разве стоит его как-то выделять отдельным пунктом в чейнджлоге?

2020-12-27 13:04 UTC, Ahion commented
Обещал что больше добавлять ничего не буду сюда, но забыл сделать это мелкое изменение. Изменил слой травы алиенов на  `layer = TURF_LAYER`, чтобы она не перекрывала вентиляцию. 

Два коммита получилось видимо из-за того, что я сначала сделал это в другой ветке, а потом когда мержил в эту ветку, в редакторе набрал то же название...

2020-12-28 17:16 UTC, T6751 reviewed
Думаю можно в тестмерж

2020-12-29 15:54 UTC, Ahion commented
fix #6609 
У лицехвата не было проверки на `can_pickup` и поэтому они подбирали предметы. Добавил. Также перенес проки лицехвата из larva.dm в facehugger_playable.dm

2021-01-05 23:08 UTC, TauKitty commented
This pull request has been mentioned on **Tau Ceti Station Forum**. There might be relevant details there:

https://forum.taucetistation.org/t/ocherednaya-tema-pro-chuzhih/23275/1

2021-01-08 13:47 UTC, Ahion commented
Конфликты исправил

2021-01-10 17:46 UTC, T6751 approved these changes

2021-01-10 22:58 UTC, merged