Перевод spellbook.
TauCetiStation/TauCetiClassic pull request #6465
Opened 2020-12-02 09:58 UTC by Kortez90

## Описание изменений
Перевод книги мага.
Присутствует спорное решение перевода содержимого переменной `category`, но при тестировании проблем выявлено не было.
## Почему и что этот ПР улучшит
Перевод.
## Авторство
@Kortez90.
## Чеинжлог
:cl: Kortez90
 - spellcheck: Книга заклинаний мага переведена на RU.

2020-12-02 09:58 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2020-12-02 10:57 UTC, KIBORG04 commented
> Присутствует спорное решение перевода содержимого переменной category, но при тестировании проблем выявлено не было.

Мне кажется, спорно переводить названия заклинаний без перевода самих заклинаний, как объектов

2020-12-02 10:58 UTC, Kortez90 commented
Это в процессе.

2020-12-02 11:58 UTC, KIBORG04 commented
А как же заклинания божка? 🤕

2020-12-02 12:15 UTC, Kortez90 commented
> 
> 
> А как же заклинания божка? face_with_head_bandage

В книге нет. В другом ПР при переводе всей церкви зацеплю, наверное.

2020-12-05 15:22 UTC, LudwigVonChesterfield approved these changes

2020-12-07 09:34 UTC, T6751 requested changes

2020-12-07 09:34 UTC, T6751 commented on code/game/gamemodes/wizard/spellbook.dm
> +			dat += "Заклинания направленные на повышение вашей выживаемости или уменьшение выживаемости противника.<BR><BR>"
```suggestion
			dat += "Заклинания, направленные на повышение вашей выживаемости или уменьшение выживаемости противника.<BR><BR>"
```

2020-12-07 09:34 UTC, T6751 commented on code/datums/spells/wizard.dm
> +	message = "<span class='notice'>вы чувствовать сила! Вы чувствуете давление в области глаз!</span>"
```suggestion
	message = "<span class='notice'>Вы чувствовать сила! Вы чувствуете давление в области глаз!</span>"
```

2020-12-07 09:47 UTC, Kortez90 commented on code/datums/spells/gnomecurse.dm
> +	desc = "Дарует любому человеку вокруг вас Гномий Дар."
Не согласен.

2020-12-07 10:43 UTC, LudwigVonChesterfield commented on code/datums/spells/wizard.dm
> +	message = "<span class='notice'>вы чувствовать сила! Вы чувствуете давление в области глаз!</span>"
... а почему первая часть предложения написана будто писал дурачек, а вторая уже без инфинитивов?

2020-12-07 11:03 UTC, Kortez90 commented on code/datums/spells/wizard.dm
> +	message = "<span class='notice'>вы чувствовать сила! Вы чувствуете давление в области глаз!</span>"
Потому что это шутка?

2020-12-07 11:03 UTC, Kortez90 commented on code/game/gamemodes/wizard/spellbook.dm
> +			dat += "Заклинания направленные на повышение вашей выживаемости или уменьшение выживаемости противника.<BR><BR>"
https://github.com/TauCetiStation/TauCetiClassic/pull/6465/commits/00cbcfa029a7a99961eb698d8990cd8504a5f04f

2020-12-07 11:07 UTC, Kortez90 commented on code/datums/spells/gnomecurse.dm
> +	desc = "Дарует любому человеку вокруг вас Гномий Дар."
Дарует дар - тавтология. Там не просто так написано с заглавной буквы. Информативность не особо пострадала.

2020-12-08 19:32 UTC, TauKitty commented
This pull request has been mentioned on **Tau Ceti Station Forum**. There might be relevant details there:

https://forum.taucetistation.org/t/perevod-ss13-dlya-servera-tau-ceti/21675/28

2020-12-12 11:14 UTC, LudwigVonChesterfield commented on code/datums/spells/in_hand.dm
> +	desc = "Выстреливает арканной энергией в ваших врагов. Требует обе руки для использования. Изучение этого заклинания сделает недоступным Lesser Summon Gun."
```suggestion
	desc = "Выстреливает арканной энергией в ваших врагов. Требует обе руки для использования."
```

arcane это кстати "загадочная", "мистическая". может стоит перевести? Ты же не перевёл название как "арканный обстрел"

у нас же нет такого заклинания

2020-12-12 14:45 UTC, LudwigVonChesterfield commented on code/datums/spells/lighting_shock.dm
> +	desc = "Шокирует вашу цель на 5 секунд. Также разоружает, заставляет выбросить все вещи в руках и не дает их поднять."
Возможно я бы перевёл всю строку вот так, потому-что "шокирование" это тоже не дополнительное действие, это причина разоружения
```suggestion
	desc = ""Поражает вашу цель током в течении 5-и секунд. В это время цель будет разоружена, и не сможет подбирать вещи."
```

2020-12-12 14:46 UTC, LudwigVonChesterfield commented on code/datums/spells/in_hand.dm
> -	name = "Lightning Bolt"
Прикольно что в оригинале название было некорректным, вместо шарика будто бы "молния" как таковая просто.

2020-12-12 14:46 UTC, LudwigVonChesterfield commented on code/datums/spells/in_hand.dm
> +	name = "Шаровая молния"
У нас кстати обычно имена предметов с маленькой буквы. Как считаешь, тут тоже нужна маленькая буква, или "Шаровая молния" идёт скорее как имя собственное, название заклинания которое в руке(почему-то), а не как объект шаровой молнии, который не имя собственное?

2020-12-12 14:47 UTC, LudwigVonChesterfield commented on code/datums/spells/knock.dm
> +	desc = "Открывает ближайшие, даже закрытые, двери и не требует одежды для использования."
Можно ли открыть не закрытую дверь?

2020-12-12 14:48 UTC, LudwigVonChesterfield commented on code/datums/spells/knock.dm
> +	desc = "Открывает ближайшие, даже закрытые, двери и не требует одежды для использования."
Возможно ты имел ввиду запертую?

2020-12-12 14:50 UTC, LudwigVonChesterfield commented on code/datums/spells/wizard.dm
> +	name = "Магическая ракета"
В оригинале можно заметить что везде использовали ээээ... Заголовочный стиль писания? Тобишь с большой буквы писалось каждое слово название, как в газетах делают. Ты же решил писать так, будто название предмета - это предложение. Но при этом при выводе в чатик оно будет вставляться с большой же буквой, а это чутка некорректно.

Именно поэтому мы(Шкиппер если точнее) во всём билде все названия предметов перевёл на маленькие буквы. Как думаешь, тут тоже так нужно?

2020-12-12 14:51 UTC, Kortez90 commented on code/datums/spells/in_hand.dm
> +	name = "Шаровая молния"
Есть разница? Это название всплывает при наведении на шар в руке и только.

2020-12-12 14:52 UTC, Kortez90 commented on code/datums/spells/wizard.dm
> +	name = "Магическая ракета"
IDK, translated as is.

2020-12-12 14:54 UTC, Kortez90 commented on code/datums/spells/lighting_shock.dm
> +	desc = "Шокирует вашу цель на 5 секунд. Также разоружает, заставляет выбросить все вещи в руках и не дает их поднять."
Шок и дизарм - разные вещи.

2020-12-12 14:58 UTC, LudwigVonChesterfield commented on code/datums/spells/wizard.dm
> +	name = "Магическая ракета"
"Magic Missile" --> "Магическая ракета".

Ты или специально игнорируешь что я пишу, или не понимаешь о чём я.

2020-12-12 14:58 UTC, LudwigVonChesterfield commented on code/datums/spells/in_hand.dm
> +	name = "Шаровая молния"
У всех остальных предметов это название с маленькой, почему твой особенный?

2020-12-12 14:59 UTC, LudwigVonChesterfield commented on code/datums/spells/lighting_shock.dm
> +	desc = "Шокирует вашу цель на 5 секунд. Также разоружает, заставляет выбросить все вещи в руках и не дает их поднять."
К чему ты это?

2020-12-12 15:00 UTC, LudwigVonChesterfield commented on code/datums/spells/lighting_shock.dm
> +	desc = "Шокирует вашу цель на 5 секунд. Также разоружает, заставляет выбросить все вещи в руках и не дает их поднять."
Разоружение происходит как результат шока, или в дополнении с шоком? Заклинание у нас "Шокируй и Раздень", или "Шокируй"?

2020-12-12 15:00 UTC, DarthSidiousPalpatine commented on code/datums/spells/knock.dm
> +	desc = "Открывает ближайшие, даже закрытые, двери и не требует одежды для использования."
Скорее заблокированную

2020-12-12 15:00 UTC, LudwigVonChesterfield commented on code/datums/spells/knock.dm
> +	desc = "Открывает ближайшие, даже закрытые, двери и не требует одежды для использования."
Не думаю что маги блокируют двери

2020-12-12 15:01 UTC, Kortez90 commented on code/datums/spells/lighting_shock.dm
> +	desc = "Шокирует вашу цель на 5 секунд. Также разоружает, заставляет выбросить все вещи в руках и не дает их поднять."
`Hold your target with electricity for 5 seconds.`
`Disarms target making drop`

2020-12-12 15:04 UTC, LudwigVonChesterfield commented on code/datums/spells/lighting_shock.dm
> +	desc = "Шокирует вашу цель на 5 секунд. Также разоружает, заставляет выбросить все вещи в руках и не дает их поднять."
Это отвечает на мой вопрос про следственную связь этих двух вещей?

2020-12-12 15:06 UTC, LudwigVonChesterfield commented on code/datums/spells/Time_stop.dm
> +	name = "Остановка времени"
```suggestion
	name = "Остановка Времени"
```

2020-12-12 15:07 UTC, LudwigVonChesterfield commented on code/datums/spells/ethereal_jaunt.dm
> +	name = "Выход из тела"
```suggestion
	name = "Выход из Тела"
```

2020-12-12 15:07 UTC, LudwigVonChesterfield commented on code/datums/spells/in_hand.dm
> +	name = "Огненный шар"
```suggestion
	name = "Огненный Шар"
```

2020-12-12 15:07 UTC, LudwigVonChesterfield commented on code/datums/spells/in_hand.dm
> +	name = "Огненный шар"
```suggestion
	name = "огненный шар"
```

2020-12-12 15:08 UTC, LudwigVonChesterfield commented on code/datums/spells/in_hand.dm
> +	name = "Шаровая молния"
```suggestion
	name = "Шаровая Молния"
```

2020-12-12 15:08 UTC, LudwigVonChesterfield commented on code/datums/spells/in_hand.dm
> +	name = "Шаровая молния"
```suggestion
	name = "шаровая молния"
```

2020-12-12 15:09 UTC, LudwigVonChesterfield commented on code/datums/spells/in_hand.dm
> +	name = "Чародейский обстрел"
```suggestion
	name = "Чародейский Обстрел"
```

2020-12-12 15:09 UTC, LudwigVonChesterfield commented on code/datums/spells/mind_transfer.dm
> +	name = "Обмен разумом"
```suggestion
	name = "Обмен Разумом"
```

2020-12-12 15:09 UTC, LudwigVonChesterfield commented on code/datums/spells/spacetime_distrortion.dm
> +	name = "Искажение пространства-времени"
```suggestion
	name = "Искажение Пространства-времени"
```

2020-12-12 15:10 UTC, LudwigVonChesterfield commented on code/datums/spells/summon_item.dm
> +	name = "Мгновенный призыв"
```suggestion
	name = "Мгновенный Призыв"
```

2020-12-12 15:11 UTC, LudwigVonChesterfield commented on code/datums/spells/wizard.dm
> +	name = "Отключить технологию"
```suggestion
	name = "Отключить Технологию"
```

2020-12-12 15:13 UTC, LudwigVonChesterfield commented on code/datums/spells/wizard.dm
> +	name = "Магическая стена"
```suggestion
	name = "Магическая Стена"
```
стена кстати силовая была, тут всё хорошо? И не лучше бы подошло слово барьер?

2020-12-12 15:13 UTC, LudwigVonChesterfield commented on code/datums/spells/wizard.dm
> +	name = "Призвать рой существ"
```suggestion
	name = "Призвать Рой Существ"
```

2020-12-12 15:13 UTC, LudwigVonChesterfield commented on code/datums/spells/wizard.dm
> +	name = "Огненный шар"
```suggestion
	name = "Огненный Шар"
```

2020-12-13 10:11 UTC, LudwigVonChesterfield commented on code/datums/spells/ethereal_jaunt.dm
> +	name = "Выход Из Тела"
Если что, тут используется так называемый 'title case', предолги в нём с большой не ставятся.

2020-12-13 10:11 UTC, LudwigVonChesterfield commented on code/datums/spells/ethereal_jaunt.dm
> +	name = "Выход Из Тела"
```suggestion
	name = "Выход из Тела"
```

2020-12-13 10:17 UTC, Kortez90 commented on code/datums/spells/ethereal_jaunt.dm
> +	name = "Выход Из Тела"
Это характерно для английского, где не капитализируются артикли и так далее.
В русском вообще нет смысла этого делать.

2020-12-13 10:21 UTC, LudwigVonChesterfield commented on code/datums/spells/ethereal_jaunt.dm
> +	name = "Выход Из Тела"
Если что, я был не прав ещё на этапе когда предложил это делать, потому-что для русского похоже не характерен title case вообще.

И не надо меня вгонять в ложный выбор, почитай пожалуйста что это такое.

https://apastyle.apa.org/style-grammar-guidelines/capitalization/title-case

По аналогии, если в английском не капитализируются предлоги, то почему должны у нас?
Вероятней всего вообще подобный стиль написания нужен чтобы бросаться в глаза, принимать внимание, и предлоги всякие в этом не так важны, как сами концепции.

2020-12-13 10:26 UTC, Kortez90 commented on code/datums/spells/ethereal_jaunt.dm
> +	name = "Выход Из Тела"
Он не ложный. Тут нужен реверт всего этого мусора с капитализацией.

2020-12-13 10:28 UTC, LudwigVonChesterfield commented on code/datums/spells/ethereal_jaunt.dm
> +	name = "Выход Из Тела"
Я тебе дал аргумент, почему ты на него не отвечаешь, а лишь продолжаешь угрозы и создаешь ложный выбор?

"Либо ты делаешь как я хочу, либо ты делаешь как я хочу"
"Я считаю что если мы делаем по аналогии, предлоги не должны капитализироваться, а ещё блабла"
"Либо ты делаешь как я хочу, либо мы ревертаем всё"

2020-12-13 10:48 UTC, Kortez90 commented on code/datums/spells/ethereal_jaunt.dm
> +	name = "Выход Из Тела"
Если хочешь поговорить о психологии человека, то я не возражаю. Довольно забавная и отчасти обширная тема, но не особенно глубокая.

Я изначально уведомлял, что капитализация здесь не имеет смысла, но твое рвение и желание сделать по-своему неуемно. Это мы проехали.

Теперь ты нашел ошибку в своих суждениях, но не хочешь возвращаться к исходному варианту, потому что тогда твой эгоизм начнет тебя сжирать еще сильнее, так как тут опять все не по-твоему.

Видеть в людях врагов не всегда полезно, а особенно там, где в этом нет смысла. Это ребячество и стадное поведение обусловлено лишь желанием и/или жаждой признания. Твое самоудовлетворение чувством причастия не сделает лучше ни PR, ни билд. И как я уже писал ранее - это изменения ради изменений.

Ну и на сладкое. Есть разница между "Считать себя лучше других" и "Считать других хуже себя". У тебя же это почти в абсолюте, из-за чего "Не зная броду, мы лезем в воду.". Здесь же вполне характерный пример того, что эти изменения были настойчиво навязаны не ради улучшения, а ради собственных желаний. 
Считаю эксперимент относительно успешным.

А капитализацию нужно ревертить, в ней нет никакого смысла. Ранее я считал, что это как-то могло повлиять на код, но оказалось, что это не так.

2020-12-13 11:07 UTC, LudwigVonChesterfield commented on code/datums/spells/ethereal_jaunt.dm
> +	name = "Выход Из Тела"
> И как я уже писал ранее - это изменения ради изменений.

Я руководствовался тем, что в оригинале был использовал title case, я тебе сказал как его корректно использовать в примере где ты его использовал некорректно, всё что ты говоришь дальше - додумки, и спекуляция.

2020-12-13 11:39 UTC, Kortez90 commented on code/datums/spells/ethereal_jaunt.dm
> +	name = "Выход Из Тела"
Добро пожаловать в стадию отрицания.

Я не использовал этот способ вообще, так как в русском языке он не применяется.
У тебя есть права чтения/записи. Возьми и перепиши как хочешь.

2020-12-13 12:19 UTC, LudwigVonChesterfield commented on code/datums/spells/gnomecurse.dm
> +	desc = "Дарует любому человеку вокруг вас Гномий Дар."
```suggestion
	desc = "Наделяет любого человека вокруг вас Гномьим Даром."
```

2020-12-13 12:52 UTC, merged