Перевод APC.
TauCetiStation/TauCetiClassic pull request #6532
Opened 2020-12-13 20:07 UTC by Kortez90

## Описание изменений
Перевел темплейт и некоторые части апц на русский.
"Р.У." - ручное управление. Сокращено до четырех символов, потому что слишком длинное слово ломает внешний вид. Если сможете перевести "Manual" как-то иначе - предлагайте.
"Блокировка интерфейса" сокращена по тем же причинам.
Увеличено окно на 5 пикселей в ширину из-за кнопок "ВЫКЛ".
Сообщения в чат и остальные уведомления в файле `apc.dm` переведу чуть позже.
Само сокращение "APC" пока под вопросом. Спросил на форуме.
## Почему и что этот ПР улучшит
Перевод.
## Авторство
@Kortez90
## Чеинжлог
:cl: Kortez90
 - ru: APC переведены на RU.

2020-12-13 20:07 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2020-12-13 20:09 UTC, LudwigVonChesterfield commented
> Если сможете перевести "Manual" как-то иначе - предлагайте.

Рассматривал вариант "вручную"?

2020-12-13 20:10 UTC, Kortez90 commented
Максимум 6 символов. Сломает.

2020-12-13 22:29 UTC, Zmey25 commented
Перевод, которого заслуживает таусети.

2020-12-13 23:10 UTC, DenchikPozhiloyTranslator commented
Ручн.

2020-12-14 00:44 UTC, Tiarv commented
> Максимум 6 символов. Сломает.
> ![Безымянный](https://user-images.githubusercontent.com/36198983/102022833-6f824b80-3d9a-11eb-9049-bd49a7694ec8.png)

Ручн

2020-12-14 03:37 UTC, L4rever commented
Manual - Ручной. Environment - система жизнеобеспечения же, разве нет? Ну или просто "Жизнеобеспечение"

2020-12-14 10:48 UTC, LudwigVonChesterfield commented on code/modules/power/apc.dm
> +				to_chat(user, "Там есть терминал, но нет платы.")
Там это где?

2020-12-14 10:49 UTC, LudwigVonChesterfield commented on code/modules/power/apc.dm
> +				to_chat(user, "Там есть терминал, но нет платы.")
И может стоит "терминал" как-то иначе перевести... Я к примеру не подумал бы что терминал отсылается на наличие проводки

2020-12-14 10:49 UTC, LudwigVonChesterfield commented on code/modules/power/apc.dm
> +				to_chat(user, "<span class='warning'>Сначала отсоедините провода.</span>")
Тут ты к примеру не переводишь провода как терминал.

2020-12-14 10:50 UTC, LudwigVonChesterfield commented on code/modules/power/apc.dm
> +				to_chat(user, "Крышка сломана. Проблематично открыть без лома.")
```suggestion
				to_chat(user, "Крышка сломана. Без лома будет тяжело её открыть.")
```

2020-12-14 10:50 UTC, LudwigVonChesterfield commented on code/modules/power/apc.dm
> +				to_chat(user, "Крышка закрыта. С ней что-то не так, она не работает.")
Крышка не работает?...

2020-12-14 10:51 UTC, LudwigVonChesterfield commented on code/modules/power/apc.dm
> +			to_chat(user, "Вы пытаетесь вытащить управляющую плату...")//lpeters - fixed grammar issues
```suggestion
			to_chat(user, "Вы пытаетесь вытащить управляющую плату...")
```

2020-12-14 10:52 UTC, LudwigVonChesterfield commented on code/modules/power/apc.dm
> +			to_chat(user, "<span class='notice'>Болты APC подняты.</span>")
APC (Area Power Controller)

точно не нужно переводить аббревиатуру, чтобы она имела смысл в русском языке?

2020-12-14 10:53 UTC, LudwigVonChesterfield commented on code/modules/power/apc.dm
> +				to_chat(user, "<span class='warning'>Нет коннектора для вашей батареи.</span>")
```suggestion
				to_chat(user, "<span class='warning'>Отсутствует коннектор для установки батареи.</span>")
```

Мне кажется что красивее бы выглядел пассивный тон, без обращения к игроку.

2020-12-14 10:54 UTC, LudwigVonChesterfield commented on code/modules/power/apc.dm
> +						"Вы сломали обугленную плату управления и извлекли остатки.",
Кстати, не странно что ты переводишь electronics как плата, и power control board как управляющая плата. Разве эти два слова не отсылались на одну и ту же плату внутри?

2020-12-14 10:55 UTC, LudwigVonChesterfield commented on code/modules/power/apc.dm
> +		to_chat(user, "Вы начали заваривать фрейм APC...")
```suggestion
		to_chat(user, "Вы начали заваривать рамку APC...")
```

2020-12-14 10:55 UTC, LudwigVonChesterfield commented on code/modules/power/apc.dm
> +					"Вы разобрали сломанный фрейм APC.",\
Может "фрейм" стоит заменить на "рамку"?

2020-12-14 10:56 UTC, LudwigVonChesterfield commented on code/modules/power/apc.dm
> +				"title" = "Окружение",
Тут кажется про Атмосферу, или систему жизнеобеспечения.

2020-12-14 11:00 UTC, Kortez90 commented on code/modules/power/apc.dm
> +				to_chat(user, "Там есть терминал, но нет платы.")
>Там это где?
>There.

2020-12-14 11:01 UTC, LudwigVonChesterfield commented on code/modules/power/apc.dm
> +				to_chat(user, "Там есть терминал, но нет платы.")
То есть теперь переводить сохраняя все особенности оригинала - это необходимость, а не "ошибка мышления"?

2020-12-14 11:01 UTC, Kortez90 commented on code/modules/power/apc.dm
> +				to_chat(user, "Крышка закрыта. С ней что-то не так, она не работает.")
Да.

2020-12-14 11:02 UTC, Kortez90 commented on code/modules/power/apc.dm
> +						"Вы сломали обугленную плату управления и извлекли остатки.",
Она и есть, а разницы нет. Не все должно быть однотипным. У одних и тех же вещей есть разные названия.

2020-12-14 11:02 UTC, Kortez90 commented on code/modules/power/apc.dm
> +			to_chat(user, "<span class='notice'>Болты APC подняты.</span>")
Об этом написано в описании.

2020-12-14 11:03 UTC, LudwigVonChesterfield commented on code/modules/power/apc.dm
> +						"Вы сломали обугленную плату управления и извлекли остатки.",
Может для игроков было бы лучше если бы одна и та же вещь всегда называлась одинаково, чтобы игроки не думали и плодили сущности?

2020-12-14 11:06 UTC, Kortez90 commented on code/modules/power/apc.dm
> +					"Вы разобрали сломанный фрейм APC.",\
На картинную? Нет. Англицизм тут уместен.

2020-12-14 11:07 UTC, Kortez90 commented on code/modules/power/apc.dm
> +				"title" = "Окружение",
Туда входили двери, вентиляция и прочее, что не вошло в оборудование. Уже предлагали "жизнеобеспечение", но это слишком длинный вариант.

2020-12-14 11:09 UTC, Kortez90 commented on code/modules/power/apc.dm
> +				to_chat(user, "Там есть терминал, но нет платы.")
Это не особенность оригинала, это текст и часть предложения.

2020-12-14 11:11 UTC, Kortez90 commented on code/modules/power/apc.dm
> +						"Вы сломали обугленную плату управления и извлекли остатки.",
Для этого в коде есть коммент на 460-й строчке. `Less hints more mystery!`

2020-12-14 11:13 UTC, Kortez90 commented on code/modules/power/apc.dm
> +				to_chat(user, "<span class='warning'>Нет коннектора для вашей батареи.</span>")
Тут не просто так стояло слово `your`.

2020-12-14 12:25 UTC, Motzord commented on code/modules/power/apc.dm
> +					"Вы разобрали сломанный фрейм APC.",\
>фрейм.

Может все таки рама/корпус?

2020-12-14 12:27 UTC, Motzord commented on code/modules/power/apc.dm
> +				to_chat(user, "Крышка закрыта. С ней что-то не так, она не работает.")
Крышка точно не работает?

Это звучит как неработающая кружка, неуместно и нелепо. Если невозможно перевести оригинал так, чтобы он звучал корректно, я считаю следует заменить.

2020-12-14 12:29 UTC, Motzord commented on code/modules/power/apc.dm
> +				to_chat(user, "Там есть терминал, но нет платы.")
>Там есть терминал

Тут же я не понимаю, почему ты отказался от оставления оригинала, ибо он звучит уместно. 
>Здесь есть провода но нет платы
Звучит уместнее чем бредятина про какой-то терминал

2020-12-14 12:34 UTC, Motzord requested changes

2020-12-14 12:34 UTC, Motzord commented on code/modules/power/apc.dm
> +				to_chat(user, "Плата установлена, но нет терминала.")
Кто такой терминал и почему ты ими заменяешь нормальное устойчивое слово "провода-проводка"?

2020-12-14 12:34 UTC, Motzord commented on code/modules/power/apc.dm
> +				to_chat(user, "Отсутствуют плата и терминал.")
Почему ты не перевел здесь как отсутствует плата и подключенные провода?
Почему блин терминал

2020-12-14 12:35 UTC, Motzord commented on code/modules/power/apc.dm
> +				to_chat(user, "<span class='warning'>Нет коннектора для вашей батареи.</span>")
А может просто так? Смысл предложения поменялся и теперь космонавт не понимает какая батарея ему нужна?

Нужна конкретно ЕГО батарея или вообще любая?

2020-12-14 12:36 UTC, Tiarv commented on code/modules/power/apc.dm
> +				"title" = "Окружение",
Среда?

2020-12-14 12:37 UTC, WatlerJe commented
Смена языка на RU/ENG будет? Ничего не имею против вашего перевода, просто привык играть в игры на английцком.

2020-12-14 12:37 UTC, Motzord commented
> Смена языка на RU/ENG будет? Ничего не имею против вашего перевода, просто привык играть в игры на английцком.

Скорее всего не будет Чисто ру

2020-12-14 12:38 UTC, Motzord commented
![image](https://user-images.githubusercontent.com/45365635/102082047-ea3e7b80-3e19-11eb-987b-bf4c81a830ab.png)
Не конечно если под терминалом имеется ввиду тот кусок проводки под АПЦ, возможно кортез прав и следует оставить именно терминал, но если имеется ввиду проводка в АПЦ, то я против такого перевода.

2020-12-14 12:39 UTC, Tiarv commented on code/modules/power/apc.dm
> +				to_chat(user, "Крышка закрыта. С ней что-то не так, она не работает.")
может быть, "ее замок сломан"?

2020-12-14 12:39 UTC, KIBORG04 commented
> Смена языка на RU/ENG будет? Ничего не имею против вашего перевода, просто привык играть в игры на английцком.

Технически сделать можно, но слишком сложно и костыльно

2020-12-14 12:50 UTC, Kortez90 commented on code/modules/power/apc.dm
> +				to_chat(user, "<span class='warning'>Нет коннектора для вашей батареи.</span>")
В том и дело, что именно его батарея не подходит. Для **его** батареи нет коннектора, а не коннектора нет вообще.

2020-12-14 13:23 UTC, Kortez90 commented
> 
> 
> Смена языка на RU/ENG будет? Ничего не имею против вашего перевода, просто привык играть в игры на английцком.

https://forum.taucetistation.org/t/perevod-ss13-dlya-servera-tau-ceti/21675/44

2020-12-14 13:26 UTC, Kortez90 commented on code/modules/power/apc.dm
> +				to_chat(user, "Крышка сломана. Проблематично открыть без лома.")
Не уверен. Нужно голосование.
Вопрос вкуса.

2020-12-14 14:07 UTC, LudwigVonChesterfield commented on code/modules/power/apc.dm
> +			to_chat(user, "Вы пытаетесь вытащить управляющую плату...")//lpeters - fixed grammar issues
И каким образом комментарий некоо lpeters-а про починку грамматики релевантен теперь, когда ты перевёл сам?

2020-12-14 14:08 UTC, LudwigVonChesterfield commented on code/modules/power/apc.dm
> +			to_chat(user, "<span class='notice'>Болты APC подняты.</span>")
```suggestion
			to_chat(user, "<span class='notice'>Поднимите болты APC.</span>")
```

2020-12-14 14:08 UTC, LudwigVonChesterfield commented on code/modules/power/apc.dm
> +				to_chat(user, "<span class='warning'>Нет коннектора для вашей батареи.</span>")
> stat & MAINT

Но дело как раз не в батарейке, а в отсутствии коннектора...

2020-12-14 14:12 UTC, Kortez90 commented on code/modules/power/apc.dm
> +			to_chat(user, "Вы пытаетесь вытащить управляющую плату...")//lpeters - fixed grammar issues
Так его и нет.

2020-12-14 14:35 UTC, Motzord commented on code/modules/power/apc.dm
> +				"title" = "Окружение",
Нет, четверг.

2020-12-14 16:16 UTC, Kortez90 commented on code/modules/power/apc.dm
> +				"title" = "Окружение",
Если среда, то только окружающая, а это по кол-ву символов совпадает со словом "жизнеобеспечение".

2020-12-24 10:56 UTC, T6751 commented
> Максимум 6 символов. Сломает.

Что мешает потрогать наноуи и изменить ширину?

2020-12-24 10:57 UTC, Kortez90 commented
А это возможно поправить в темплейте?

2021-01-21 12:16 UTC, T6751 commented on code/modules/power/apc.dm
> +			to_chat(user, "Панель проводки [wiresexposed ? "открыта" : "закрыта"].")
Панель проводки?

2021-01-21 12:16 UTC, T6751 commented on code/modules/power/apc.dm
> +						"Вы вытащили управляющую плату.")
Управляющая? Управляющая чем? (based? based on what?)

Лучше перевести как есть - плата контроля энергии

2021-01-21 12:16 UTC, T6751 commented on code/modules/power/apc.dm
> +				to_chat(user, "Плата установлена, но нет терминала.")
Думаю лучше использовать, как и в оригинале "провода" вместо "терминала". И в остальных местах тоже
```
Плата установлена, но нет проводов.
```

2021-01-21 12:16 UTC, T6751 commented on code/modules/power/apc.dm
> +				to_chat(user, "Там есть терминал, но нет платы.")
```suggestion
				to_chat(user, "Здесь есть терминал, но нет платы.")
```

2021-01-21 20:34 UTC, Kortez90 commented on nano/templates/apc.tmpl
> +			{{:helper.link('Закрыто', 'locked', {'toggleaccess' : 1}, data.locked ? 'selected' : null)}}{{:helper.link('Открыто', 'unlocked', {'toggleaccess' : 1}, data.malfStatus >= 2 ? 'linkOff' : (data.loc
Ширина и так уже растянута до смешных значений. Из-за двух слов растягивать ее на половину экрана не круто.

2021-01-21 21:10 UTC, Kortez90 commented on code/modules/power/apc.dm
> +		to_chat(user, "Вы начали заваривать фрейм APC...")
Нет.
Не считаю "фрейм" неуместным.

2021-01-21 21:11 UTC, Kortez90 commented on code/modules/power/apc.dm
> +				"<span class='warning'>[user.name] заменил поврежденный фрейм APC на новый.</span>",\
Проблема макросов.

2021-01-21 21:11 UTC, Kortez90 commented on code/modules/power/apc.dm
> +						"Вы вытащили управляющую плату.")
Нет.
Не считаю это необходимым.

2021-01-21 21:12 UTC, Kortez90 commented on code/modules/power/apc.dm
> +				to_chat(user, "Плата установлена, но нет терминала.")
Нет.
Не считаю это уместным.

2021-01-22 13:13 UTC, T6751 requested changes
Необходимо добавить макрос для окончаний глаголов в прошедшем времени (заменил/заменила/заменило). Или ждать пока кто-нибудь другой его не добавит. Лучше не оставлять это на потом.

Также желательно больше мнений о переводе

2021-01-22 13:22 UTC, Kortez90 commented
Можно оставить `\заменил` как вариант. Ничего страшного.

2021-02-10 20:25 UTC, closed without merging