noose
TauCetiStation/TauCetiClassic pull request #6566
Opened 2020-12-22 10:22 UTC by Morar1

## Описание изменений
Добавлена петля.
Петлю можно сделать из кабеля 30 кабеля.
В петле можно повеситься.
Единственное во что я не смог - нормальный icon_state у "buckled" alert-а моба в петле
<details>
  <summary>Картинка</summary>
  
 ![пук](https://cdn.discordapp.com/attachments/312972945876320258/790883027910918194/unknown.png).
  
</details>

## Почему и что этот ПР улучшит
Можно сделать суицид/казнь красочнее, чем простой клик стволом в рот/шприц в вену | расстрел
## Авторство
hippie station
## Чеинжлог
🆑
* add: Петля из кабеля в которой можно сделать роскомнадзор.

2020-12-22 10:22 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2020-12-22 10:30 UTC, Kortez90 commented
Стоило бы добавить тень под висящим персонажем.
Да и если делать из желтых проводов, то петля все равно будет красной.

2020-12-22 10:38 UTC, LudwigVonChesterfield commented on code/game/objects/structures/stool_bed_chair_nest/chairs.dm
> +	if(iswirecutter(W) || isnull(W))
isnull(W)?

А когда такое происходит?

2020-12-22 10:38 UTC, LudwigVonChesterfield commented on code/game/objects/structures/stool_bed_chair_nest/chairs.dm
> +		user.visible_message("[user] cuts the noose.", "<span class='notice'>You cut the noose.</span>")
```suggestion
		user.visible_message("<span class='notice'>[user] cuts the noose.</span>", "<span class='notice'>You cut the noose.</span>")
```

2020-12-22 10:38 UTC, LudwigVonChesterfield commented on code/game/objects/structures/stool_bed_chair_nest/chairs.dm
> +			if(buckled_mob.mob_has_gravity())
Эту проверку можно добавить к той что на строке выше

has_buckled_mobs() && buckled_mob.mob_has_gravity()

2020-12-22 10:39 UTC, LudwigVonChesterfield commented on code/game/objects/structures/stool_bed_chair_nest/chairs.dm
> +/obj/structure/stool/bed/chair/noose/attackby(obj/item/weapon/G, mob/user)
У тебя же аттакбай в начале файла, ты думаешь если его сделать таким образом - читать проще?

2020-12-22 10:40 UTC, LudwigVonChesterfield commented on code/game/objects/structures/stool_bed_chair_nest/chairs.dm
> +/obj/structure/stool/bed/chair/noose/user_unbuckle_mob(mob/living/user)
ТТы бы смог переписать эту функцию под ранний возврат?

Типо чтобы было

if(!has_buckled_mobs())
  return
  
  if(user.is_busy())
    return
    
    if(buckled_mob != user)
      одно
      else
        другое

2020-12-22 10:40 UTC, LudwigVonChesterfield commented on code/game/objects/structures/stool_bed_chair_nest/chairs.dm
> +	attackby(null, user)
Я бы вместо подобного предложил сделать у петли функцию "обрываться", которая вызывалась бы тут, и в аттакбае когда режешь ножницами.

2020-12-22 11:21 UTC, Morar1 commented
> Да и если делать из желтых проводов, то петля все равно будет красной.

Из-за двух разных крафт систем, цвет с выбранной крафт системой выбрать не получится, но с ней есть ограничения по типу один объект на турфе и т.п. у второй системы нет этих проверок, но есть contents у создаваемого объекта и это либо нужно оборачивать как-то, либо забить, в общем ~~мне лень~~ будет красный (а еще в белый перерисовать петлю тогда надо будет).

2020-12-22 11:27 UTC, Zmey25 commented
Обновление, которое тау кита заслуживает ♥

2020-12-22 13:08 UTC, Akellazp commented
Сначала закодь потолок

2020-12-22 13:50 UTC, Kortez90 commented on code/game/objects/items/weapons/makeshift.dm
> +	if((get_turf(user)).density)
А разве `can_pass` тут нельзя использовать? Или `get_turf` лучше/удобнее?

2020-12-22 13:51 UTC, Morar1 commented on code/game/objects/items/weapons/makeshift.dm
> +	if((get_turf(user)).density)
не хочу лишний раз кучу проверок делать, ничего не поменяется от того что будет can_pass использоваться

2020-12-22 14:09 UTC, KIBORG04 commented on code/game/objects/structures/stool_bed_chair_nest/chairs.dm
> +		animate(M, pixel_y = M.lying? initial(pixel_y) + 14 : initial(pixel_y) + 8, time = 8, easing = LINEAR_EASING)
```suggestion
		animate(M, pixel_y = M.lying ? initial(pixel_y) + 14 : initial(pixel_y) + 8, time = 8, easing = LINEAR_EASING)
```
Может пробел поставить?

2020-12-22 14:12 UTC, KIBORG04 commented on code/game/objects/structures/stool_bed_chair_nest/chairs.dm
> +	if(!BP || (BP.is_stump))
```suggestion
	if(!BP || BP.is_stump)
```
скобки не нужны

2020-12-22 14:14 UTC, KIBORG04 commented on code/game/objects/structures/stool_bed_chair_nest/chairs.dm
> +		if(BP && (!BP.is_stump))
```suggestion
		if(BP && !BP.is_stump)
```

2020-12-22 14:14 UTC, KIBORG04 commented on code/game/objects/structures/stool_bed_chair_nest/chairs.dm
> +	return
```suggestion
```

2020-12-22 14:16 UTC, Kortez90 commented
Забыл отметить, что выводы в чат лучше сразу писать на русском.

2020-12-22 15:00 UTC, Morar1 commented
> Единственное во что я не смог - нормальный icon_state у "buckled" alert-а моба в петле

Это про это: 
<details>
  <summary>Картинка</summary>
  
 ![тык](https://cdn.discordapp.com/attachments/312972945876320258/790928750958084167/unknown.png).
  
</details>
Вдруг кто не понял, но знает решение

2020-12-22 15:02 UTC, Kortez90 commented
Зачем вообще этот алерт существует?

2020-12-22 15:04 UTC, Morar1 commented
> Зачем вообще этот алерт существует?

Что бы кликать по алерту, а не на предмет на котором сидишь

2020-12-22 16:15 UTC, 4310V343k commented
То есть теперь нельзя класть провода кликом на моток?

2020-12-22 22:39 UTC, LudwigVonChesterfield commented on code/game/objects/items/weapons/makeshift.dm
> +	if((get_turf(user)).density)
если сделать can_pass то строить на столе нельзя было бы к примеру(а может и можно, но нужно подумать нужно ли)

2020-12-22 22:39 UTC, LudwigVonChesterfield commented on code/game/objects/items/weapons/makeshift.dm
> +	var/obj/structure/stool/bed/chair/noose/N = new(get_turf(user))
get_turf(user) так часто используется что я бы в начале функции дал бы ему название

var/turf/user_turf = get_turf(user)

2020-12-22 22:40 UTC, LudwigVonChesterfield commented on code/game/objects/items/weapons/makeshift.dm
> +/obj/item/weapon/noose/attack_self(mob/user)
а почему нельзя это запилить на новой системе крафта? та которая где наручники крафтятся.

2020-12-23 04:42 UTC, Zandwitch23 commented
Заинтересовали подробности данного механа, вот что то видно стула на скриншоте. Если кто нибудь расскажет как успешно повеситься без чего то подобного, то вопросов нет, но. Когда один делает нечто через ж (не в плане идеи, а реализации), потом другой это повторяет, то это х. Хуже не куда.  Получается что суицид выходит не таким уж красочным, скорее похож на простой клик. Ну можно же со всем уважением - скрафтил>повесил петлю>поставил стул на тот же тайл>перетянул куклу на стул>клик по петле>хармом сбиваем стул>дёргаемся в агонии какое то время испытывая респ дамаге (тут ещё кто нибудь может успеть снять суицидника). Поставил палец вверх и ракету.

2020-12-23 06:41 UTC, Morar1 commented on code/game/objects/items/weapons/makeshift.dm
> +/obj/item/weapon/noose/attack_self(mob/user)
Так в этой крафт системе не подразумевалось что кто-то там структуры будет крафтить, поэтому для смены цвета петли, и сохранение проверки одной петли на турф было сделано таким образом. Крафт петли(предмета) делается на новой системе крафта, а структуры уже так, через attack_self.

2020-12-23 06:45 UTC, TheLustOfBlood commented
Нааааааайс, теперь буду dead inside

2020-12-23 10:53 UTC, Kortez90 commented
Что будет, если СПУ или диона попытаются повеситься?

2020-12-23 10:55 UTC, LudwigVonChesterfield commented on code/game/objects/structures/stool_bed_chair_nest/chairs.dm
> +			if(!C.flipped)
Я думаю эта проверка должна быть при залезании в петлю, а не при её установке. Хотя не знаю, может у нас все коротышки

2020-12-23 11:02 UTC, Zandwitch23 commented
Клас! 
/me снял шляпу

2020-12-23 11:08 UTC, Morar1 commented
> Что будет, если СПУ или диона попытаются повеситься?

Ничего, все же проходит через ```/mob/living/carbon/human/adjustOxyLoss(amount)```

2020-12-23 11:08 UTC, KIBORG04 commented on code/game/objects/structures/stool_bed_chair_nest/chairs.dm
> +		M.pixel_y = M.lying? -6 : initial(M.pixel_y)
```suggestion
		M.pixel_y = M.lying ? -6 : initial(M.pixel_y)
```

2020-12-23 11:09 UTC, Morar1 commented on code/game/objects/structures/stool_bed_chair_nest/chairs.dm
> +			if(!C.flipped)
Она же и так в ```/user_buckle_mob``` лежит, не понял

2020-12-24 06:21 UTC, Sakuya-Izayoi commented
Я так понял при вскрытии или хотя бы экзамайне нет никаких свидетельств применения петли?

2020-12-24 06:30 UTC, Morar1 commented
> Я так понял при вскрытии или хотя бы экзамайне нет никаких следов применения петли?

специально для тебя

2020-12-24 06:59 UTC, KIBORG04 commented
Эт, кстати, плохо. Одной строчкой можно исправить.

2020-12-24 18:11 UTC, Sakuya-Izayoi commented
![](https://cdn.discordapp.com/attachments/192005420494094339/791728155966701598/q78nqddkh4761.png)

2020-12-27 13:45 UTC, Sakuya-Izayoi requested changes

2020-12-27 13:45 UTC, Sakuya-Izayoi commented on code/game/machinery/doors/airlock.dm
> +				if(M.forceMove(new_turf))
Этого изменения нет в ПРе.

2020-12-27 13:45 UTC, Sakuya-Izayoi commented on code/game/objects/items/weapons/makeshift.dm
> +		to_chat(user, "<span class='notice'>You cant build a noose on a tile that has a noose.</span>")
can't

2020-12-27 13:45 UTC, Sakuya-Izayoi commented on code/game/objects/items/weapons/makeshift.dm
> +	N.color = src.color
просто color.

2020-12-27 13:45 UTC, Sakuya-Izayoi commented on code/game/objects/structures/stool_bed_chair_nest/chairs.dm
> +	if(M.loc != src.loc)
без src

2020-12-27 13:59 UTC, Morar1 commented on code/game/machinery/doors/airlock.dm
> +				if(M.forceMove(new_turf))
Ничего не меняет

2020-12-29 16:03 UTC, Sakuya-Izayoi approved these changes

2020-12-30 15:45 UTC, LudwigVonChesterfield commented
@Morar1 ты бы хотел сделать чтобы влезть в петлю можно было только если стоишь на стуле, а удушение начинается тоьлко когда этот стул опрокидываешь?

2020-12-31 12:26 UTC, Morar1 commented
> @Morar1 ты бы хотел сделать чтобы влезть в петлю можно было только если стоишь на стуле, а удушение начинается тоьлко когда этот стул опрокидываешь?

А, я это и так сделал, как просили в первый день у меня

2021-01-02 17:10 UTC, T6751 commented on code/game/objects/structures/stool_bed_chair_nest/chairs.dm
> +	buckled_mob.pixel_z = initial(buckled_mob.pixel_z)
```
Runtime in chairs.dm, line 334: Cannot modify null.pixel_z.
proc name: user unbuckle mob (/obj/structure/stool/bed/chair/noose/user_unbuckle_mob)
usr: Ssean Marssass (/mob/living/carbon/human)
usr.loc: The floor (119,140,2) (/turf/simulated/floor)
```

2021-01-02 19:31 UTC, Morar1 commented on code/game/objects/structures/stool_bed_chair_nest/chairs.dm
> +	buckled_mob.pixel_z = initial(buckled_mob.pixel_z)
Не знаю как такое возможно, но ладно

2021-01-03 20:59 UTC, Kortez90 commented
Нужны педальные логи и сообщения.

2021-01-04 22:03 UTC, Kortez90 commented on code/game/machinery/doors/airlock.dm
> +				if(M.forceMove(new_turf))
#6649.
Откатывай.

2021-01-04 22:04 UTC, 4310V343k commented on code/game/machinery/doors/airlock.dm
> +				if(M.forceMove(new_turf))
```suggestion
				if(buckled)
		        		buckled.unbuckle_mob()
				if(M.Move(new_turf))
```
#6649

2021-01-05 16:08 UTC, Morar1 commented
#6649 не должно повторяться

2021-01-05 16:16 UTC, Morar1 commented
> Нужны педальные логи и сообщения.

```
M.log_combat(user, "attempted to hang", src)
M.log_combat(user, "hanged", src)
```
Этих двух не хватает?

2021-01-07 11:04 UTC, Kortez90 commented
Да, но лучше не в виде комбат логов.
`message_admins("[key_name_admin(usr)] пытлся повеситься в [location] / [src]. [ADMIN_JMP(usr)]")`

2021-01-07 17:21 UTC, Kortez90 commented on code/game/objects/structures/stool_bed_chair_nest/chairs.dm
> +/obj/structure/stool/bed/chair/noose/proc/rip(mob/user, var/forced = FALSE)
```suggestion
/obj/structure/stool/bed/chair/noose/proc/rip(mob/user, forced = FALSE)
```

2021-01-08 22:01 UTC, Kortez90 commented on code/game/machinery/doors/airlock.dm
> +				M.buckled.unbuckle_mob()
Возможно стоит проверять здесь только петлю.

2021-01-08 22:07 UTC, KIBORG04 commented on code/game/machinery/doors/airlock.dm
> +				M.buckled.unbuckle_mob()
Либо, вызывать у стула/петли/каталки/жанитор_кара/алтаря/штука какую-то функцию airlock_act(), которую ты перепишешь для удавки, а уже внутри нее поместить для респрайтов стульев flip() или еще чё

2021-01-11 14:32 UTC, Morar1 commented on code/game/machinery/doors/airlock.dm
> +				M.buckled.unbuckle_mob()
>Либо, вызывать у стула/петли/каталки/жанитор_кара/алтаря/штука какую-то функцию airlock_act(), которую ты перепишешь для удавки, а уже внутри нее поместить для респрайтов стульев flip()

вне рамок пра(если прямо сильно надо, то 13 числа сяду и залью в этот пр, отпишитесь там...)

2021-01-11 14:36 UTC, Kortez90 commented on code/game/machinery/doors/airlock.dm
> +				M.buckled.unbuckle_mob()
Надо. Заливай.

2021-01-11 14:39 UTC, merged

2021-01-12 10:15 UTC, Morar1 commented on code/game/machinery/doors/airlock.dm
> +				M.buckled.unbuckle_mob()
Я немного подумал какие интересные интеракции можно запихнуть в airlock_crush_act() или около того, думаю оставить as is, сейчас все возможные взаимодействия без obj damaging system покрывает анбакл и просто нанесения урона кукле

2021-01-12 10:19 UTC, Kortez90 commented on code/game/machinery/doors/airlock.dm
> +				M.buckled.unbuckle_mob()
Ну тогда петлю просто ревертнем и все. Обещал - делай.