пинпоинтер теперь может искать ИИ
TauCetiStation/TauCetiClassic pull request #6582
Opened 2020-12-24 17:20 UTC by AndroBetel

## Описание изменений
title
## Почему и что этот ПР улучшит
ии больше нельзя будет спрятать где-то на полигоне.
## Авторство

## Чеинжлог
:cl:
- rscadd: Пинпоинтер теперь может искать ИИ.

2020-12-24 17:20 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2020-12-24 17:21 UTC, KIBORG04 commented on code/game/gamemodes/nuclear/pinpointer.dm
> +						target = A
Если у тебя будет несколько ии, то будет искать последнего в списке. При каких ситуациях может быть `if(!A)` ?

2020-12-24 17:26 UTC, AndroBetel commented on code/game/gamemodes/nuclear/pinpointer.dm
> +						target = A
если ИИ не будет на станции?????

2020-12-24 17:26 UTC, AndroBetel commented on code/game/gamemodes/nuclear/pinpointer.dm
> +						target = A
ну в смысле просто не будет

2020-12-24 17:29 UTC, KIBORG04 commented on code/game/gamemodes/nuclear/pinpointer.dm
> +						target = A
> ну в смысле просто не будет

Если ии не будет не станции, то у тебя в цикле будет 0 итерации, а значит даже до этой проверки не дойдёт.

2020-12-24 21:19 UTC, LudwigVonChesterfield commented on code/game/gamemodes/nuclear/pinpointer.dm
> +					for(var/mob/living/silicon/ai/A in ai_list)
Здесь хотят сделать
target = locate(/mob/living/silicon/ai) in ai_list

2020-12-24 21:20 UTC, LudwigVonChesterfield commented on code/game/gamemodes/nuclear/pinpointer.dm
> +					for(var/mob/living/silicon/ai/A in ai_list)
Хотя возможно скорее

```
target = locate(/mob/living/silicon/ai) in ai_list
if(!target)
  уведоми что ИИ нет? ищи корпус ИИ?
```

2020-12-24 23:30 UTC, T6751 commented on code/game/gamemodes/nuclear/pinpointer.dm
> +							return
```suggestion
				if(!target)
					to_chat(usr, "Failed to locate active AI system!")
					return
```

2020-12-24 23:33 UTC, T6751 commented on code/game/gamemodes/nuclear/pinpointer.dm
> +					return
```suggestion
					if(!target)
						to_chat(usr, "Failed to locate active AI system!")
						return
```

2020-12-24 23:34 UTC, KIBORG04 commented on code/game/gamemodes/nuclear/pinpointer.dm
> +					target = locate(/mob/living/silicon/ai in ai_list)
Ты просто че-то с типом делаешь
Локейт так не работает

2020-12-24 23:34 UTC, T6751 commented on code/game/gamemodes/nuclear/pinpointer.dm
> +					target = locate(/mob/living/silicon/ai in ai_list)
warning: bad `locate(X in Y)`, should be `locate(X) in Y`
```suggestion
					target = locate(/mob/living/silicon/ai) in ai_list
```

2020-12-24 23:35 UTC, KIBORG04 commented on code/game/gamemodes/nuclear/pinpointer.dm
> +					target = locate(/mob/living/silicon/ai in ai_list)
Тут тоже резолвни

2020-12-25 06:46 UTC, Rolt146 commented
А если ии будет несколько, какого он будет искать конкретно?

2020-12-25 08:11 UTC, Kortez90 commented
Первого в списке.

2020-12-28 09:32 UTC, KIBORG04 commented
Меня одного интересует, почему нельзя будет выбирать конкретного ИИшку?

2020-12-29 09:22 UTC, LudwigVonChesterfield commented
потому-что ещё до Бетеля никто не закодил чтобы пинпоинтер выбирал конкретный инстанс, а не первый попавшийся

Бетель скопипастил что было, а там этого не было

2020-12-29 13:45 UTC, KIBORG04 commented
Так ведь днк и есть поиск конкретного человека. А искать конкретный инстанс во всех объектах немного тупо. С ИИшкой же другая ситуация, которая решается двумя дополнительными строчками.

2021-01-10 10:57 UTC, T6751 requested changes
Можешь также добавить выбор определенного ИИ на случай, если их будет несколько, пожалуста?

2021-01-10 10:57 UTC, T6751 commented on code/game/gamemodes/nuclear/pinpointer.dm
> -							break
Зачем убран брейк?

2021-01-27 18:21 UTC, T6751 commented on code/game/gamemodes/nuclear/pinpointer.dm
> +				if("AI System")
```suggestion
							break
				if("AI System")
```

2021-01-27 18:21 UTC, T6751 commented on code/game/gamemodes/nuclear/pinpointer.dm
> +					target = locate(/mob/living/silicon/ai) in ai_list
```suggestion
					target = input("Select AI to search for", "AI Select") as null|anything in ai_list
```

2021-01-29 12:51 UTC, KIBORG04 commented on code/game/gamemodes/nuclear/pinpointer.dm
> +					var/target_ai = input("Select AI to search for", "AI Select") as null|anything in ai_list
```suggestion
					if(!global.ai_list.len)
						to_chat(usr, "Failed to locate active AI system!")
						return
					var/target_ai = input("Select AI to search for", "AI Select") as null|anything in global.ai_list
```

2021-01-29 12:52 UTC, KIBORG04 approved these changes

2021-01-30 15:43 UTC, merged