Робототехническое
TauCetiStation/TauCetiClassic pull request #6587
Opened 2020-12-25 08:25 UTC by 4310V343k

## Описание изменений
Фикс робототехников, теперь они не будут _забирать_ работу у учёных
## Почему и что этот ПР улучшит
[Это](https://forum.taucetistation.org/t/apellyacziya-kenshy4420-apellyacziya-na-varn/23050)
## Авторство
Remindme, @Kortez90 за повод
## Чеинжлог
:cl:
 - experiment: Профессия робототехника перенесена в подпрофессию учёного

2020-12-25 08:25 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2020-12-25 14:08 UTC, Kenshy4420 commented
Давно пора. Эти разделения на унтер и убер только проблемы вносят, и портят впечатления от игры.

2020-12-25 17:16 UTC, LudwigVonChesterfield commented
а в чем смысл подпроф вообще, у нас к примеру раз десять тысяч предлагают выпилить под профы инженера и врача, а вы тут новые плодите...

2020-12-25 17:39 UTC, Rolt146 commented
Я только за. Давно было пора. Теперь не будет вечных выклянчиваний позитронок, деталек, и прочего, а ученые наконец смогут печатать протезы горе взломщикам

2020-12-25 23:59 UTC, Zmey25 commented
>>Теперь не будет вечных выклянчиваний

Эти люди не знают, что когда-то политриник нужно было просить у химика и вообще в этом смысл игры.

2020-12-26 00:12 UTC, KIBORG04 commented
> > > Теперь не будет вечных выклянчиваний
> 
> Эти люди не знают, что когда-то политриник нужно было просить у химика и вообще в этом смысл игры.

Так он про позитронный моск, а не про кислоту

2020-12-26 06:57 UTC, Ahion commented
> Эти люди не знают, что когда-то политриник нужно было просить у химика и вообще в этом смысл игры.

Не в этом смысл игры. Если бы вот эти "взаимодействия" работали как надо, ученым бы не поставили раздатчик политриника и вопросов на форуме таких бы не поднимали, и  этого ПРа бы не было. Неужели до сих пор не очевидно что такие "взаимодействия" не приносят никому никакого удовольствия.
 
Я понимаю задумку, хотели создать некую производственную цепочку, когда один производит что-то, передает другому, тот что-то с этим делает и так далее. Мне и самому эта идея нравиться, но сейчас в игре это работает из рук вон плохо. И происходит это потому что игрок не заинтересован кому-то что-то давать. Не заинтересован ученый исследовать ветку робототехники, как и не заинтересован химик давать ботанику мутаген, как и не заинтересован химик вообще варить что-то для медбея. Единственное где это более менее работает, так это между шахтерами и учеными, так как шахтеры получают хоть какую-то награду за свой труд в виде улучшений.

Я за этот ПР, он хоть как-то решит эту проблему.

2020-12-26 15:30 UTC, Zmey25 commented
Если ты стесняешься пройтись до соседнего отсека и попросить аутиста что-то сделать, потребовать у него что-то и т.д., это не повод свою зону комфорта сужать механом. Считаешь, что взаимодействие не работает потому что люди не хотят? Значит такие как ты и есть часть проблемы.

С такой логикой давайте бармену доступ в гидропонику и на кухню, потому что у него некоторые рецепты требуют ингредиенты оттуда. А потом и на шахту, потому что я хочу варить нюка колу, но слишком интроверт, чтобы пойти в карго и попросить урана. Еще раз, проблема в вас и это не повод ограничиваться механом.

2020-12-26 15:47 UTC, 4310V343k commented
> Если ты стесняешься пройтись до соседнего отсека и попросить аутиста что-то сделать, потребовать у него что-то и т.д., это не повод свою зону комфорта сужать механом. Считаешь, что взаимодействие не работает потому что люди не хотят? Значит такие как ты и есть часть проблемы.
> 
> С такой логикой давайте бармену доступ в гидропонику и на кухню, потому что у него некоторые рецепты требуют ингредиенты оттуда. А потом и на шахту, потому что я хочу варить нюка колу, но слишком интроверт, чтобы пойти в карго и попросить урана. Еще раз, проблема в вас и это не повод ограничиваться механом.

Различай бармена, у которого от силы 5 рецептов зависят от социалочки и бегания по карго/химии/ботанике, и робототехника, у которого почти ВСЯ ПРОФЕССИЯ построена на изучениях из РНД

2021-01-09 10:23 UTC, T6751 requested changes
> Фикс робототехников, теперь они не будут забирать работу у учёных

Во первых, мне очень не нравится текущее решение, т.к. перенос профы в сабпрофу по сути является слиянием профессий, что можно расценивать и я расцениваю как удаление профессии, ведь что делает сабпрофа обычно может делать и основная профессия, в данном случае Ученый. Нет проблемной профессии - нет проблем?

Во-вторых, насколько я понял, ситуация следующая:
- Мы имеем проблему с тем, что робототехники **забирают** работу ученых.
- Окей, мы позволим им **забирать** работу учёных, сделав их по сути **учеными**. Теперь робототехник имеет доступ к форонной и теленауке и как ученый он сможет взрывать лимитки и изучать теленауку, чтобы получить заветные очки ради ветки с мехами. А может быть и не только ветку с мехами. Как-никак сабпрофа "Ученого" и допуска есть для чего-то же.

Робототехник, взрывающий лимитки. Нет, спасибо.

Можно было бы вместо удаления профессии попробовать решить **причины**, по которой робототехники это делают, например, позволив им изучать только свою ветку исследований и изготавливать необходимые им компоненты в самой робототехнике или в конце концов просто выдав необходимые допуск в комнату с протолатом.

2021-01-10 18:22 UTC, closed without merging