добавляет нюкерам военные преступления
TauCetiStation/TauCetiClassic pull request #6618
Opened 2020-12-31 02:02 UTC by AndroBetel

## Описание изменений
нюке добавляется скафандр биологической защиты, который невосприимчив к кислоте всегда, а в боевом режиме  полностью защищен от взрывов, биологической опасности и радиации. вместе со скафандром нюкеры получили наспинный рюкзак химикатов (как у уборщика), заполненный ядами, кислотой и топливом. все это входит в набор, который может быть только один на команду. ядомёт перезаряжается особыми баками, которые можно купить в аплинке.

скрины будут как только УДАВ ПОЖАЛУЙСТА скинет мне спрайты данного рига.
## Почему и что этот ПР улучшит
разнообразие вещей у антагонистов
## Авторство

## Чеинжлог
:cl:
- rscadd[link]: Ядерные оперативники получили набор химической войны.

2020-12-31 02:02 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2020-12-31 02:15 UTC, Sakuya-Izayoi commented
а можно дымовой кластербанг с таким же содержимым?

2020-12-31 02:18 UTC, AndroBetel commented
там у дыма какие-то приколы непонятные, так что я воздержался от его добавления. да и кластербенг это слишком круто!

2020-12-31 07:09 UTC, Kortez90 commented on code/game/machinery/computer/intruder_station.dm
> +	delete_dat_after_buying = TRUE
```suggestion
	delete_dat_after_buying = TRUE

```

2020-12-31 07:10 UTC, Kortez90 commented on code/game/objects/items/weapons/storage/uplink_kits.dm
> +	make_exact_fit()
```suggestion
	make_exact_fit()

```

2020-12-31 07:13 UTC, Kortez90 commented on code/game/objects/items/weapons/tanks/watertank.dm
> +	volume = 1600
```suggestion
	volume = 1600

```

2020-12-31 07:15 UTC, Kortez90 commented on code/modules/reagents/reagent_dispenser.dm
> +	return
```suggestion
	return

```

2020-12-31 13:41 UTC, T6751 commented on code/game/machinery/computer/intruder_station.dm
> +datum/intruder_tools/hazmat
```suggestion
/datum/intruder_tools/hazmat
```

2020-12-31 13:41 UTC, T6751 commented on code/modules/reagents/reagent_dispenser.dm
> +/obj/item/device/radio/beacon/syndicate_chemicals
Нужно перенести этот маяк туда, где описываются все маяки. А именно: ```code\game\objects\items\devices\radio\beacon.dm```

2020-12-31 22:22 UTC, Sakuya-Izayoi commented on code/game/objects/items/weapons/tanks/watertank.dm
> +	reagents.add_reagent("stoxin", 200)
list_reagents

2020-12-31 22:22 UTC, Sakuya-Izayoi commented on code/modules/reagents/reagent_dispenser.dm
> +	reagents.add_reagent("stoxin", 200)
list_reagents

2021-01-10 08:08 UTC, AndroBetel commented
да щас мам

2021-01-10 08:10 UTC, Kortez90 commented on code/game/machinery/computer/intruder_station.dm
> +	delete_dat_after_buying = TRUE
Зачем его удалять-то?

2021-01-10 08:11 UTC, AndroBetel commented on code/game/machinery/computer/intruder_station.dm
> +	delete_dat_after_buying = TRUE
я не хочу чтобы вся толпа нюкеров закупала эти дорогие штуки и вся станция гуляла бы без шляп.

2021-01-10 08:15 UTC, Kortez90 commented on code/game/machinery/computer/intruder_station.dm
> +	delete_dat_after_buying = TRUE
Делать набор одноразовым для покупки не круто.
Почему бы просто цену ему не загнуть?

2021-01-10 08:16 UTC, AndroBetel commented on code/game/machinery/computer/intruder_station.dm
> +	delete_dat_after_buying = TRUE
нет круто

2021-01-10 09:36 UTC, T6751 requested changes
Можешь сделать добавление реагентов через ```list_reagents```, пожалуста?

2021-01-18 20:25 UTC, AndroBetel commented
ребят я пока жив скоро будет я надеюсь

2021-01-18 20:38 UTC, AndroBetel commented on code/modules/reagents/reagent_dispenser.dm
> +	reagents.add_reagent("stoxin", 200)
у реагент_диспенсеров нет list_reagents...

2021-01-21 13:24 UTC, T6751 commented
> скрины будут как только УДАВ ПОЖАЛУЙСТА скинет мне спрайты данного рига.

Всё ещё ждём скриншоты или можно мёржить? @AndroBetel

2021-01-21 20:09 UTC, AndroBetel commented
ждем скриншоты потому что я даже не все спрайты залил

2021-01-24 19:19 UTC, Artik12344 commented
А там не слишком ли имбовый набор ядов?

2021-02-03 20:53 UTC, AndroBetel commented
скоро ребят скоро!

2021-02-06 17:40 UTC, AndroBetel commented
СДЕЛАНО!!!!

2021-02-06 18:44 UTC, UDaV73rus requested changes
- белые пиксели и потерянные руки на боковых tajaran/suit.dmi rig-hazmat-space
- белые пиксели unathi/suit.dmi rig-hazmat-combat
- шлемы скреллов походу скопирнуты с унатхов и приделаны хвосты, надо исправить на дефолтные с хвостами
- потеряны спрайты: Шлема кошек, шлема ящеров, их итемы

*на этом моменте я понял что нафига я это пишу, если ничего не тестилось*

2021-02-06 18:53 UTC, UsadoSmokk commented
> * белые пиксели и потерянные руки на боковых tajaran/suit.dmi rig-hazmat-space
> * белые пиксели unathi/suit.dmi rig-hazmat-combat
> * шлемы скреллов походу скопирнуты с унатхов и приделаны хвосты, надо исправить на дефолтные с хвостами
> * потеряны спрайты: Шлема кошек, шлема ящеров, их итемы
> 
> _на этом моменте я понял что нафига я это пишу, если ничего не тестилось_

1 и 2 надеюсь и без меня смогут, 3 вроде как сделаны с помощью дефолтных, а что про касаемо 4, то у нас у всех спрайтов нюки нет итемов и спрайтов на голову, так это и не нужно.

2021-02-08 15:19 UTC, AndroBetel commented
зафикшено всё что там удав понаписал

2021-02-08 16:17 UTC, UsadoSmokk commented
я конечно не строитель, но строить из себя хуй пойми что хочу, бак бы как-то...может покрасить в красный и....там не знаю, сделать смешнявку?

2021-02-08 16:21 UTC, AndroBetel commented
он покрашен в цвет металла нюкеров так что вполне подходит же

2021-02-08 17:25 UTC, Sakuya-Izayoi commented
можно знак биоугрозы на баке?

2021-02-09 15:38 UTC, KIBORG04 commented on code/game/objects/items/devices/radio/beacon.dm
> +	return
```suggestion

```

2021-02-09 15:43 UTC, KIBORG04 commented on code/modules/reagents/reagent_dispenser.dm
> +	reagents.clear_reagents()
Зачем?

2021-02-09 17:20 UTC, AndroBetel commented on code/modules/reagents/reagent_dispenser.dm
> +	reagents.clear_reagents()
и правда незачем

2021-02-09 17:51 UTC, UDaV73rus requested changes
obj/clothing/species/vox/suits.dmi белый пиксель

2021-02-09 18:43 UTC, Kortez90 commented
А почему у костюма химзащиты должна быть жаростойкость?

2021-02-09 19:52 UTC, AndroBetel commented
он мною задумывался как костюм который полностью изолирован от всех внешних воздействий. от взрыва, кислоты и химии у него тоже полная защита. это позволит нюкерам придумывать смешные вещи с огнеметами или даже фороньей.

2021-02-09 21:50 UTC, Kortez90 commented
Ну давай ему еще выдадим тогда полную защиту и игнор лазеров, чтобы нюкеры могли устраивать цирк.

2021-02-09 22:04 UTC, AndroBetel commented
ну вот из-за таких "претензий" такой скафандр один на всю команду.

2021-02-12 13:35 UTC, T6751 commented
Конфликты
![image](https://user-images.githubusercontent.com/66636084/107774206-bfa46c80-6d4f-11eb-9410-05e708bb5bf5.png)

2021-03-05 18:59 UTC, AndroBetel commented
конфликты уничтожены

2021-03-11 18:11 UTC, AndroBetel commented
@T6751 merge when

2021-03-12 16:20 UTC, T6751 approved these changes

2021-03-14 01:22 UTC, merged

2021-06-23 12:42 UTC, KIBORG04 commented on code/game/objects/items/devices/radio/beacon.dm
> +	return
Резолвнул но не убрал.. Вот это кринж

2021-06-23 13:47 UTC, T6751 commented on code/game/objects/items/devices/radio/beacon.dm
> +	return
Как раз-таки убрал, но потом вернул, мда