Feature/tg camera port
TauCetiStation/TauCetiClassic pull request #6660
Opened 2021-01-07 14:59 UTC by AirBlack

## Описание изменений
Порт камер с ТГ с учетом пары старых фич, а именно перемещение камер по даблклику и стрелкам.
Еще пофиксил баг дефолтного стейта ТГУИ с проверкой видит ли ИИ объект или нет(просто перенаправил на старый наноуишный прок рабочий).
<details>
  <summary>Кринжшоты</summary>
 космис работает

![image](https://user-images.githubusercontent.com/5171605/103906899-b9a4e580-512a-11eb-97dd-6f9085d26b72.png)
иксрей работаит

![image](https://user-images.githubusercontent.com/5171605/103906940-caedf200-512a-11eb-8754-3fbf901aea3d.png)
прикольный зум

![image](https://user-images.githubusercontent.com/5171605/103906971-d4775a00-512a-11eb-9544-012638c140a0.png)

</details>

fixes #6630

## Почему и что этот ПР улучшит
Геймплей за кадетов, дефективов и смотрителей, а то камерами старыми неудобно пользоваться. К сожалению фича с картой потерялась, но может потом впилю, если местные дезигнеры подскажут куда.
## Авторство
AirBlack - порт с тг
stylemistake - [оригинальный ПР с тг](https://github.com/tgstation/tgstation/pull/49960)
## Чеинжлог
:cl:
 - rscadd: Порт консоли камер с ТГ.
 - bugfix: Фикс TGUI Default state для ИИ
 - bugfix: При disable parallax космос больше не белый
 - bugfix: Physical state для некоторых объектов с TGUI дабы ИИ не мог дергать канистры и подобное

2021-01-07 14:59 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2021-01-07 15:14 UTC, Sakuya-Izayoi commented
а у аишки есть такие камеры? было бы неплохо, если бы они у него были (хотя наверное это очень сильно)

ещё было бы круто чтобы камеры можно было сплитить как у охранников ирл но это тоже наверное очень сильно и жрёт ресурсы наверное...

2021-01-07 15:16 UTC, 4310V343k requested changes

2021-01-07 15:16 UTC, 4310V343k commented on code/game/machinery/computer/camera.dm
> +			playsound(src, 'sound/machines/terminal_on.ogg', 25, FALSE)
```suggestion
			playsound(src, 'sound/machines/terminal_on.ogg', VOL_EFFECTS_MASTER, 25, FALSE)
```

2021-01-07 15:16 UTC, 4310V343k commented on code/game/machinery/computer/camera.dm
> +	playsound(src, 'sound/machines/terminal_prompt_confirm.ogg', 25, FALSE)
```suggestion
	playsound(src, 'sound/machines/terminal_prompt_confirm.ogg', VOL_EFFECTS_MASTER, 25, FALSE)
```

2021-01-07 15:16 UTC, 4310V343k commented on code/game/machinery/computer/camera.dm
> +		playsound(src, 'sound/machines/terminal_off.ogg', 25, FALSE)
```suggestion
		playsound(src, 'sound/machines/terminal_off.ogg', VOL_EFFECTS_MASTER, 25, FALSE)
```

2021-01-07 15:16 UTC, AirBlack commented
да, ИИшка может открыть эту консоль и даже несколько за раз, кортез говорил что не сильно нагружает, не слабо нагружает в момент открытия

2021-01-07 15:16 UTC, 4310V343k commented on code/game/machinery/computer/camera.dm
> +			playsound(src, 'sound/machines/terminal_on.ogg', 25, FALSE)
Опоздал блин уже

2021-01-07 15:17 UTC, AirBlack commented on code/game/machinery/computer/camera.dm
> +		playsound(src, 'sound/machines/terminal_off.ogg', 25, FALSE)
я уже все это поправил

2021-01-07 15:24 UTC, Sakuya-Izayoi commented
осталась ли фича людука которая позволяла закрашивать камеры краской для волос?

2021-01-07 15:25 UTC, AirBlack commented
щас проверю, полюбас она где-то в камерах самих лежит, а я их не трогал

2021-01-07 15:27 UTC, Sakuya-Izayoi commented
при нынешних камерах если наводишься мышкой на чара, показывает его имя. в этих камерах есть такое? я если честно не знаю как это со стороны баланса, но вообще было бы неплохо.

2021-01-07 15:28 UTC, AirBlack commented
в этих камерах есть экзамайн
<details>
  <summary>скриншот термалок</summary>

![image](https://user-images.githubusercontent.com/5171605/103910593-35a12c80-512f-11eb-8d6b-4f8b6bfb8824.png)
</details>

термалки не работают как и положено

2021-01-07 15:31 UTC, AirBlack commented
так, фича с закрашиванием не работает

2021-01-07 15:32 UTC, Kortez90 commented
> 
> 
> при нынешних камерах если наводишься мышкой на чара, показывает его имя. в этих камерах есть такое? я если честно не знаю как это со стороны баланса, но вообще было бы неплохо.

Такого нет, но экземайн работал.

2021-01-07 15:42 UTC, Sakuya-Izayoi commented
> > при нынешних камерах если наводишься мышкой на чара, показывает его имя. в этих камерах есть такое? я если честно не знаю как это со стороны баланса, но вообще было бы неплохо.
> 
> Такого нет, но экземайн работал.

а вот за ИИ экзамайн не работает. он у него и раньше не работал, но раньше благодаря описанной штуке можно было узнать имя чела, а сейчас, получается, ничего узнать нельзя

2021-01-07 15:43 UTC, Kortez90 commented
ИИ не пользуется этой системой камер.

2021-01-07 15:56 UTC, 4310V343k commented
> ИИ не пользуется этой системой камер.

Теперь будет

2021-01-07 16:07 UTC, Kortez90 commented
С какой радости? У ИИ своя система "Летающий Глаз". Эти консоли ему даже не нужны.

2021-01-07 16:17 UTC, AirBlack commented
не, ну робастные ИИ могут открыть еще несколько экранов консолей и по ним переключаться, в них работают шифт, контрл и альт клики(ну там открытие болтирование и электризация(офегеть слово) шлюзов)

2021-01-07 17:44 UTC, T6751 commented
Простые игроки не знают что такое TGUI Default и физикал стейт. Можешь просто написать, что исправляется здесь:
```
bugfix: Фикс TGUI Default state для ИИ
bugfix: Physical state для некоторых объектов с TGUI дабы ИИ не мог дергать канистры и подобное
```

2021-01-07 17:49 UTC, AirBlack commented
Обновил

2021-01-07 18:31 UTC, T6751 commented on code/_onclick/hud/parallax.dm
> +	if(PM)
Действительно ли его может не быть?

2021-01-07 18:31 UTC, T6751 commented on code/game/machinery/computer/camera.dm
> -		ui.add_template("mapHeader", "sec_camera_map_header.tmpl")
неиспользуемые .tmpl нужно удалить

2021-01-07 18:33 UTC, AirBlack commented on code/_onclick/hud/parallax.dm
> +	if(PM)
меня били в детстве и я боюсь поймать нуль(первый яп - lua)

2021-01-07 18:53 UTC, AirBlack commented
@4310V343k слыш аппрувай, наревьювил мне тут и не заапрувал, нука быстра

2021-01-07 19:04 UTC, AirBlack commented
навешали мне на пр мой ишью, страшно теперь, мне просто задолбало за кадета на кривых cum ерах сидеть вот и решил портануть а на меня тут повесилиб лин

2021-01-07 19:37 UTC, T6751 commented on code/game/machinery/computer/camera.dm
> +			cam_plane_masters += instance
```suggestion
	for(var/plane in subtypesof(/obj/screen/plane_master) - /obj/screen/plane_master/parallax_white)
		var/obj/screen/instance = new plane()
		instance.assigned_map = map_name
		instance.del_on_map_removal = FALSE
		instance.screen_loc = "[map_name]:CENTER"
		cam_plane_masters += instance
```

2021-01-07 19:37 UTC, T6751 commented on code/game/machinery/computer/camera.dm
> +	return 0
```suggestion
		return TRUE
	return FALSE
```

2021-01-07 22:44 UTC, Sakuya-Izayoi commented
> не, ну робастные ИИ могут открыть еще несколько экранов консолей и по ним переключаться, в них работают шифт, контрл и альт клики(ну там открытие болтирование и электризация(офегеть слово) шлюзов)
> 
> теперь не смогут, точнее смогут открыть только одну консоль камер, как и в целом все, люди, борги, бибизяны(я хз могут ли они смотреть)

а вот это спорно. вроде бы крутая фича была, что можно несколько камер открыть.

для ии предлагаю сделать какую-нибудь встроенную в ядро консоль камер, ну или как вариант поставить консоль камер где-то на спутнике, чтобы если на станции компы сломались/отключились, ИИ мог пользоваться такой консолькой.

2021-01-08 02:16 UTC, Sakuya-Izayoi commented
трейторские камера баги тоже пользуются этой системой?

2021-01-08 07:01 UTC, AirBlack commented on code/game/machinery/computer/camera.dm
> +			cam_plane_masters += instance
откуда там параллакс вайт, я же это не сохранял и по приколу написал...

2021-01-08 07:02 UTC, AirBlack commented on code/game/machinery/computer/camera.dm
> +			cam_plane_masters += instance
фикс параллакс вайта вообще в цвете в итоге сделал, ща это стеру

2021-01-08 07:10 UTC, AirBlack commented
> а вот это спорно. вроде бы крутая фича была, что можно несколько камер открыть.
> 
> для ии предлагаю сделать какую-нибудь встроенную в ядро консоль камер, ну или как вариант поставить консоль камер где-то на спутнике, чтобы если на станции компы сломались/отключились, ИИ мог пользоваться такой консолькой.

нагружает сильно, кортез сказал сделать лимит на одно окно

2021-01-08 07:31 UTC, Sakuya-Izayoi commented
Будучи прибакленным к стулу переключение на стрелочки не работает.

2021-01-08 08:29 UTC, AirBlack commented
> трейторские камера баги тоже пользуются этой системой?



> Будучи прибакленным к стулу переключение на стрелочки не работает.

Переключение на стрелочки сделано костыльным образом, через move. Когда ты прибакленый, то move у тебя не роботоит, а значит и переключение на стрелочки. Вообще, переключение это кривое что пиздец и я оставил лишь бы на меня не ругались что наши фичи потерял. То же самое с дабл кликом. Даблклик ии перезаписывает дабл клик камер.

2021-01-08 08:35 UTC, AirBlack commented
придумайте куда пихнуть карту пожалуйста

2021-01-08 09:09 UTC, Sakuya-Izayoi commented
> придумайте куда пихнуть карту пожалуйста

на отдельную кнопочку, наверное, как и было. только сделать чтобы она один раз показывалась. нажал -- открылась карта, выбрал камеру, карта закрылась

2021-01-08 09:27 UTC, AirBlack commented
> на отдельную кнопочку, наверное, как и было. только сделать чтобы она один раз показывалась. нажал -- открылась карта, выбрал камеру, карта закрылась

тильда сказал отдельным пром это сделать, а так, если есть идеи то лучше нарисуй, в пеинте тоже сойдет

2021-01-08 13:00 UTC, UDaV73rus commented
![image](https://user-images.githubusercontent.com/33157992/104018238-86b22e80-51ca-11eb-8f76-512b4d2f39c6.png)
видно невидимые камеры на тандердоме

2021-01-08 13:02 UTC, Kortez90 commented
Они не невидимые и работают как должны. Зал суда и тандер видно через настенные мониторы.

2021-01-08 23:52 UTC, T6751 commented
Можешь, пожалуста, перенести изменения карты в отдельный ПР, чтобы здесь был только интерфейс консоли
@AirBlack

2021-01-09 00:11 UTC, AirBlack commented
@T6751 
мне это сказал сделать кортез т.к. присобачил ишью этот
договаривайтесь с ним

2021-01-09 12:41 UTC, LudwigVonChesterfield commented on code/_onclick/hud/map_popups.dm
> +/client/proc/create_popup(name, ratiox = 100, ratioy = 100)
Прок называется create_popup а возможно ему стоило называться create_map_popup, и так же со всеми похожими

2021-01-09 19:01 UTC, AirBlack commented
ховорят логают карты, походу скоро из тма уберут и отклонят пр

2021-01-10 15:22 UTC, Sakuya-Izayoi commented
Камеры позволяют использовать телекинез на небольшом рендже (примерно от правого края мостика до евы), я не знаю, задумывалось так или нет.

2021-01-10 16:13 UTC, AirBlack commented
наверняка не задумывалось, но звучит клево, если сильно бьет по балансу - потом уберем другим пром.
мы офигели когда с кортезом тестили и поняли что двери шифт кликом за боргов открываются, но открываются они в ренже экрана от борга, т.е. если дверь за экраном обычным борга, то она не откроется, но по идее(я не проверял) откроется если ты ИИ. как по мне крутая штука

2021-01-10 16:14 UTC, AirBlack commented
вообще в этой карте клики обрабатываются т.е. можно по камерам стрелять(прилетит конечно в консоль и хз че будет с огнеметом)

2021-01-11 05:33 UTC, Sakuya-Izayoi commented
> наверняка не задумывалось, но звучит клево, если сильно бьет по балансу - потом уберем другим пром.
> мы офигели когда с кортезом тестили и поняли что двери шифт кликом за боргов открываются, но открываются они в ренже экрана от борга, т.е. если дверь за экраном обычным борга, то она не откроется, но по идее(я не проверял) откроется если ты ИИ. как по мне крутая штука

да, я тестил, за ИИ почти всё работает. ну как по мне это круто.

2021-01-12 09:36 UTC, stylemistake approved these changes

2021-01-15 16:04 UTC, Sakuya-Izayoi commented
ходят слухи что слепые могут смотреть в камеры

2021-01-19 02:53 UTC, AirBlack commented
> ходят слухи что слепые могут смотреть в камеры

является ли обзор в одну клетку у слепых отображением их воображения исходя из их ощущений?
а если кукла слепа с рождения? для таких людей не существует концепта визуала вообще, тогда что мы видим? игровую условность? изображение мироощущения слепых людей в виде визуала? боятся ли слепые люди видеть?

2021-01-24 23:14 UTC, T6751 approved these changes

2021-01-26 17:43 UTC, T6751 commented
Некоторые клиенты не могут использовать новую консоль камер из-за того, что ничего не происходит при клике на названия

![image](https://user-images.githubusercontent.com/66636084/105880019-e9515a00-6013-11eb-88e9-aa6d6b618c0d.png)

Можешь посмотреть, пожалуста, с чем это может быть связано?

2021-01-26 17:50 UTC, volas commented
Клиентские проблемы сложно решать так, может там IE или еще что. В лучшем случае может будут js-ошибки в серверных логах, нужно тогда по конкретному раунду посмотреть. tgui не использует общий обработчик ошибок, должен в свои логи писать.

2021-01-26 19:04 UTC, AirBlack commented
а если это мой пр то я могу тут оффтопить и скидывать картинки с собачками?

2021-01-28 15:13 UTC, Motzord commented
Тут мне довелось переустановить шиндовс и чудеснейшим образом обновить IE.

Вообщем все баги связанные с "У меня консоль не работает/не нажимается/хуета" связаны с версией IE меньше десятки.

Камеры крутые, я доволен, жду мержа. Багов не заметил

2021-01-28 16:31 UTC, AirBlack commented
мержа не будет имхо, как фиксить большие спрайты за краем экрана типа синги - не знаю

2021-01-29 19:15 UTC, AirBlack commented
@stylemistake помоги че делать с сингой, у нас настройка синги напрямую с камерой связана, а я такой дебил лох ограничил игроков в ее настройке из-за того что в  vis_contents не попадают те объекты которые размером больше одного турфа и турф не находится в vis_contents. Предложения были: добавить во все vis_contents всех камер синги, ковырять bounds(пробовали, не работает, синга только себя съедает но даже если это пофиксить, не работает) либо увеличить размер обзора синговых камер дабы они всегда видели всю зону(но хотя итак не всегда видно края синги, да и плюс ограничение по механу у нас такое всегда было, что клетка именно с генератором не видна камерами, дабы смотрели именно на края по камерам, дабы сложнее было). Что делать?

2021-01-29 22:35 UTC, stylemistake commented
Добавь исключение в код камер, чтобы в добавок ко всем турфам оно обошло бы все существующие сингулярности, и просто тупо добавить их в список.

2021-01-29 22:37 UTC, AirBlack commented
Ну это и было самым более менее рабочим решением до которого мы доходили, но мейнтейнер сказал, что все хуйня(как и в целом про все вообще), сказал "думай как сделать круто", и я осел.

2021-01-29 22:40 UTC, stylemistake commented
Ну пусть сам тогда сделает, если хочется "высокотехнологично", как по мне - решение простое и правомерное.

2021-01-29 22:45 UTC, AirBlack commented
Справедливо

2021-01-30 22:11 UTC, volas commented
@AirBlack я писал, что это проблема синги и бьенда, а не камер, и что к контексту pr не относится и ничего страшного. Если это про другого мейнтейнера - можешь мне в лс написать.

Тут были насколько знаю какие-то подозрения на лаги, но похоже так и осталось подозрением. Если других проблем нет, то не вижу причин не мержить.

2021-01-31 14:31 UTC, stylemistake commented
Инициализация вторичной карты фризит клиент на пол-секунды, но на сервере ничего не должно тормозить.

2021-01-31 14:47 UTC, AirBlack commented
а, мне казалось, что мы это обсуждали с кортезом, а не в канале рнд, и видимо из-за того, что большинство моих обсуждений с кортезом это "ничего не работает все лагает Сёма переделывай", то может ложные воспоминания появились. Если пофиг на проблему с сингой - то можно мержить.

2021-01-31 17:23 UTC, 4310V343k commented
> а, мне казалось, что мы это обсуждали с кортезом, а не в канале рнд, и видимо из-за того, что большинство моих обсуждений с кортезом это "ничего не работает все лагает Сёма переделывай", то может ложные воспоминания появились. Если пофиг на проблему с сингой - то можно мержить.



> Добавь исключение в код камер, чтобы в добавок ко всем турфам оно обошло бы все существующие сингулярности, и просто тупо добавить их в vis_contents. Должно решить проблему.

2021-01-31 17:24 UTC, AirBlack commented
Я это предлагал в ронде(или где-то там когда думал над этой проблемой) еще до того, как спросил стайл мистейка.

2021-02-12 12:43 UTC, merged