Возможность вскрывать полы без РЦД и маленькая переработка починки обычных стен
TauCetiStation/TauCetiClassic pull request #6664
Opened 2021-01-08 00:27 UTC by Zickusable

## Описание изменений
Теперь можно устраивать разгерму посреди станции не только RCD, но и обычной сваркой. То есть в хелп интенте пол (без плитки) будет чиниться как и раньше, а в харме разбираться до самого космоса (требует времени).
Теперь стены тоже разбираются в харме и ремонтируются в хелпе, вместо всплывающего окошка.
## Почему и что этот ПР улучшит
Удобство в строительстве и ремонте.
## Авторство
Соскребано с остального кода таукиты мной.
remindme упаковал в рабочее состояние.
## Чеинжлог
- tweak: Теперь обычные стены ремонтируются в хелп интенте и разбираются в харме.
- rscadd: Можно разбирать пол (без плитки) сваркой в харме и чинить в хелпе.

2021-01-08 00:27 UTC, TauKitty commented
###### Changelog status: :radio_button: No changelog

2021-01-08 00:41 UTC, UDaV73rus commented
Пол создается из решетки на которую ложится плитка. Может попробуешь сделать также наоборот?

2021-01-08 00:41 UTC, KIBORG04 commented on code/game/turfs/simulated/floor.dm
> +					if(user.loc == T && user.get_active_hand() == W)
То есть, мы кликаем по ближайшему турфу(не под юзером), то нам персонаж начнет варить турф под собой. Зачем?

Так же, `user.get_active_hand() == W` не нужен, ведь мы и так кликаем сваркой по турфу, а тут еще смотрим, есть ли у юзера сварка в руке.

2021-01-08 00:42 UTC, KIBORG04 commented on code/game/turfs/simulated/floor.dm
> +			if(W.use(0, user))
А почему 0?

2021-01-08 00:49 UTC, KIBORG04 commented on code/game/turfs/simulated/floor.dm
> +			if(W.use(0, user))
И лучше здесь сделать ранний возврат

2021-01-08 00:56 UTC, KIBORG04 commented on code/game/turfs/simulated/walls.dm
> +					if(!istype(src, /turf/simulated/wall) || !TW)
А этот истайп вообще возможен?

2021-01-08 00:58 UTC, KIBORG04 commented on code/game/turfs/simulated/walls.dm
> +		if(user.a_intent == INTENT_HARM && istype(src, /turf/simulated/wall))
Этот истайп всегда истинен будет

2021-01-08 00:59 UTC, KIBORG04 commented on code/game/turfs/simulated/walls.dm
> +		else if(istype(src, /turf/simulated/wall))
Этот истайп всегда истинен будет

2021-01-08 00:59 UTC, KIBORG04 commented on code/game/turfs/simulated/walls.dm
> +		var/turf/TW = user.loc
Мы уже выше сохраняем последную локацию юзера. Зачем тут еще раз?

2021-01-08 01:00 UTC, Zickusable commented
> Пол создается из решетки на которую ложится плитка. Может попробуешь сделать также наоборот?

Без remindme у меня даже плитка не удалялась.
Как я уже написал, весь код соскрябан был в ужасном виде и превращен в нормальный соавтором. До этого никогда не занимался подобным. Так что... пишите тут подробно что как и почему, ведь я в этом полный 0.)))

2021-01-08 01:00 UTC, KIBORG04 commented on code/game/turfs/simulated/walls.dm
> +					if(!istype(src, /turf/simulated/wall) || !TW)
Наверное, если стену разберут до тебя, то возможнг

2021-01-08 03:11 UTC, ViDLiathan commented
Не думаю что это нужно. Слишком легко грифонить с нашим атмосом.

2021-01-08 06:58 UTC, 4310V343k commented on code/game/turfs/simulated/floor.dm
> +					if(user.loc == T && user.get_active_hand() == W)
Насчет руки согласен, насчет турфа нет
У дуафтера есть аргумент can_move, и use_tool() его **вроде** не передаёт

2021-01-08 07:31 UTC, Zickusable commented
> Не думаю что это нужно. Слишком легко грифонить с нашим атмосом.
> 
> Ну или по времени и затратам топлива это должна быть целая горелка и как у даблесворда варка дверей.

По сути обшивка равнозначна стенке в космос, разве что girder не остается. В космос через дырку в полу не улетишь.Заделывается также просто, как и раньше. А чтоб погрифонить в толпе, нужно прийти в маске, со сваркой и пилить некоторое время голый пол. Всяко найдется неравнодушный гражданин, толкнувший грифонера.

2021-01-08 09:38 UTC, 4310V343k commented on code/game/machinery/doors/airlock.dm
> +					return
Как это относится к ПРу?

2021-01-08 13:50 UTC, KIBORG04 commented on code/game/turfs/simulated/floor.dm
> +					if(user.loc == T && user.get_active_hand() == W)
> У дуафтера есть аргумент can_move, и use_tool() его вроде не передаёт

Самое время добавить

2021-01-08 14:01 UTC, KIBORG04 requested changes

2021-01-08 14:01 UTC, KIBORG04 commented on code/game/turfs/simulated/floor.dm
> +					if(user.loc == T)
Юзе_тулл будет вызывает ду_афтер. В ду_афтере по умолчанию тебе нельзя двигаться. Если ты подвигаешься, то юзе_тулл вернет фолс и код дальше не пойдет, поэтому смысла сохранять локу пользователя нету.

2021-01-08 14:02 UTC, KIBORG04 commented on code/game/turfs/simulated/walls.dm
> +		else if(damage)
> Теперь обычные стены ремонтируются в хелп интенте и разбираются в харме.

Ты разбираешь на харме, а на любом другом интенте чинишь, не только на хелпе. 
Лучше уж сделать, что ты чинишь на хелпе, а разбираешь на любом другом. (правда это не очень очевидная механика, но все же)

2021-01-08 14:05 UTC, KIBORG04 commented on code/game/turfs/simulated/floor.dm
> +					if(user.loc == T)
И у стены тоже можно убрать запоминание турфа юзера

2021-01-08 18:27 UTC, Rolt146 commented
Я надеюсь, пол нельзя будет разобрать за 5 секунд до космоса, на которую никто не успеет среагировать? Думаю время разбора надо увеличить до минуты, иначе мы будем обречены на рофлоразгермы. И вроде как сваркой пол чинился (например от пожаров). Тут не будет конфликта?

2021-01-08 18:37 UTC, 4310V343k commented
> И вроде как сваркой пол чинился (например от пожаров). Тут не будет конфликта?

> То есть пол (без плитки) в харме разбираться до самого космоса (требует времени), а в остальных интентах будет чиниться как и раньше.

2021-01-08 18:38 UTC, Zickusable commented
> Я надеюсь, пол нельзя будет разобрать за 5 секунд до космоса, на которую никто не успеет среагировать? Думаю время разбора надо увеличить до минуты, иначе мы будем обречены на рофлоразгермы. И вроде как сваркой пол чинился (например от пожаров). Тут не будет конфликта?

Пол разбирается примерно как и стены, ибо сделано на основе стен. То что произойдет зависит от интента, мне казалось, я подробно описал это в ПРе.

2021-01-09 18:33 UTC, KIBORG04 commented on code/game/turfs/simulated/walls.dm
> +					if(user.get_active_hand() == WT)
Это тоже не нужно, как и в случае с полом

2021-01-09 18:37 UTC, KIBORG04 commented on code/game/turfs/simulated/walls.dm
> +		else if(damage)
Удобно просто поменять описание и ничего не менять.

Лучше сделай починку на хелпе, а разборку на остальных интентах. Можно считать, у нас 1 интент добрый, а 3 других плохие.

2021-01-09 18:38 UTC, KIBORG04 commented on code/game/machinery/doors/airlock.dm
> +					return
А это вот внезапныый багфикс

2021-01-09 18:47 UTC, KIBORG04 commented on code/game/turfs/simulated/floor.dm
> +					new /obj/item/stack/tile/plasteel(src)
```suggestion
					new floor_type(src)
```

2021-01-09 21:42 UTC, KIBORG04 commented on code/game/turfs/simulated/floor.dm
> +				to_chat(user, "<span class='notice'>You need more welding fuel to complete this task.</span>")
```suggestion
		var/obj/item/weapon/weldingtool/W = C
		if(user.a_intent == INTENT_HARM && is_plating())
			to_chat(user, "<span class='notice'>You need more welding fuel to complete this task.
			return
		if(W.use(0, user))
			to_chat(user, "<span class='notice'>You begin slicing through the plating.</span>")
			if(W.use_tool(src, user, 100, 3, 100))
			if(!is_plating())
				return

			to_chat(user, "<span class='notice'>You remove the plating.</span>")
			new /obj/item/stack/tile/plasteel(src)
			ReplaceWithLattice()</span>")
```
ето ранний возврат. Я бы так сделал везде, но как хочешь, можешь это не делать

2021-01-10 15:33 UTC, 4310V343k commented
Так вот как можно было делать стелс изменения

2021-01-10 19:28 UTC, KIBORG04 commented
Ты ж ничего не изменил, а уже просишь ревью

2021-01-11 10:20 UTC, KIBORG04 commented on code/game/turfs/simulated/floor.dm
> +					new /obj/item/stack/tile/plasteel(src)
Все еще в силе

2021-01-11 10:20 UTC, KIBORG04 commented on code/game/turfs/simulated/walls.dm
> +					if(user.get_active_hand() == WT)
Все еще в силе

2021-01-11 10:21 UTC, KIBORG04 commented on code/game/turfs/simulated/walls.dm
> +			else
Этот `else` не нужен

2021-01-11 13:01 UTC, KIBORG04 commented on code/game/turfs/simulated/floor.dm
> +			if(!W.use(0,user))
Вообще, наверное, стоит вынести эту проверку отсюда и снизу выше проверки на интент

2021-01-11 13:02 UTC, KIBORG04 commented on code/game/turfs/simulated/floor.dm
> +				if(!is_plating())
Ты уже выше проверяешь на отсутсвие эту штуки

2021-01-11 13:03 UTC, KIBORG04 commented on code/game/turfs/simulated/walls.dm
> +			if(!WT.use(0,user))
Вообще, наверное, стоит вынести эту проверку отсюда и снизу выше проверки на интент

2021-01-13 11:07 UTC, KIBORG04 commented
![image](https://user-images.githubusercontent.com/26389417/104444243-8fc74500-55a8-11eb-9aef-bea7f884ff25.png)

Ты это, страничку выше полистай, там все еще есть комментарии. А еще не бойся резолвать не актуальные или измененные.

2021-01-14 06:41 UTC, Zickusable commented on code/game/turfs/simulated/floor.dm
> +					new /obj/item/stack/tile/plasteel(src)
Новый выход в космос перестает появляться

2021-01-14 14:17 UTC, KIBORG04 commented on code/game/turfs/simulated/walls.dm
> +					if(user.get_active_hand() == WT)
Сначала коммит, потом резолв.

2021-01-14 14:18 UTC, KIBORG04 commented on code/game/turfs/simulated/floor.dm
> +					new /obj/item/stack/tile/plasteel(src)
А причем тут моё исправление? Это отвечает за спавн тайла, который можно будет потом заного положить.

Мб, у тебя рантайм. См в игре в Logs -> View Runtime

2021-01-14 14:24 UTC, KIBORG04 commented on code/game/turfs/simulated/floor.dm
> +					new /obj/item/stack/tile/plasteel(src)
А причем тут моё исправление? Это отвечает за спавн тайла, который можно будет потом заного положить. С ковра иначе будет падать пласталевый тайл, а не ковровый.

Мб, у тебя рантайм. См в игре в Logs -> View Runtime

2021-01-15 09:08 UTC, Zickusable commented on code/game/turfs/simulated/floor.dm
> +					new /obj/item/stack/tile/plasteel(src)
Мб я слепой, но не нашел возможность положить на решетку/космос что-то, кроме плитки/родов соотв.
Сваркой разбирается именно голая плитка, на которую кладется ковер. Ковер снимается ломом

2021-01-15 11:47 UTC, KIBORG04 approved these changes

2021-01-15 17:03 UTC, EdlerN commented
В принципе, фича как фича не лучше и не хуже остальных. Как тут уже говорили, у нас окна в центре станции грифонятся монтировкой с отверткой, так что погоды возможность резать полы сваркой не сделает. Другое дело - тактическое разгермоидорство.

Единственное что, я не уверен касательно времени на выполнение действия. Секунд 15 было бы нормально, но, если разбирать структуры в космосе то как-то многовато. И, вот пока я над этим думал, мне вот какая идея пришла. А почему бы не сделать это зависимым от окружающих тайлов? То есть делать дырку в сплошном полу будет сложнее, в то время как спиливать структуры в космосе по краям - быстрее. Что-то уровня 5 секунд на действие базово, +5 секунд за каждую вплотную прилегающую клетку с полом или стеной (ну или +2.5 секунды, если считать диагонали)

2021-01-17 05:47 UTC, Zickusable commented
> В принципе, фича как фича не лучше и не хуже остальных. Как тут уже говорили, у нас окна в центре станции грифонятся монтировкой с отверткой, так что погоды возможность резать полы сваркой не сделает. Другое дело - тактическое разгермоидорство.
> 
> Единственное что, я не уверен касательно времени на выполнение действия. Секунд 15 было бы нормально, но, если разбирать структуры в космосе то как-то многовато. И, вот пока я над этим думал, мне вот какая идея пришла. А почему бы не сделать это зависимым от окружающих тайлов? То есть делать дырку в сплошном полу будет сложнее, в то время как спиливать структуры в космосе по краям - быстрее. Что-то уровня 5 секунд на действие базово, +5 секунд за каждую вплотную прилегающую клетку с полом или стеной (ну или +2.5 секунды, если считать диагонали)

Добавить зависимость не имеет смысла. Еще ни у кого не было проблемы с удалением пола посреди космоса. Это нужно, чтоб горячий воздух например убрать посреди станции или сделать вид на космос из бара. Наверное стоит потестить в игре, вдруг этот ваш баланс и не потребуется.

2021-01-20 13:58 UTC, T6751 commented on code/game/machinery/doors/airlock.dm
> +					                     "<span class='notice'>You [welded? "weld":"remove welding from"] [src]'s shutters with [W].</span>")
```suggestion
					user.visible_message("[user] [welded ? "welds" : "unwelds"] [src]'s shutters with [W].",
					                     "<span class='notice'>You [welded ? "weld" : "remove welding from"] [src]'s shutters with [W].</span>")
```

2021-01-20 13:58 UTC, T6751 commented on code/game/turfs/simulated/floor.dm
> +		if(!W.use(0,user))
```suggestion
		if(!W.use(0, user))
```

2021-01-20 13:59 UTC, T6751 commented on code/game/turfs/simulated/walls.dm
> +		if(!WT.use(0,user))
```suggestion
		if(!WT.use(0, user))
```

2021-01-21 14:41 UTC, T6751 requested changes
Можно разбирать астероид и дюпать плитку

![image](https://user-images.githubusercontent.com/66636084/105365977-e0c1e380-5c0f-11eb-94fa-9a8b98fd6cb4.png)

2021-01-21 14:43 UTC, KIBORG04 commented on code/game/turfs/simulated/floor.dm
> +					new /obj/item/stack/tile/plasteel(src)
Видимо из-а этого астероид и дюпается

2021-01-21 19:01 UTC, KIBORG04 commented
![image](https://user-images.githubusercontent.com/26389417/105399054-24c6df80-5c34-11eb-947d-ec28d54e6d94.png)

а, м, а, а где впринципе изменения?

2021-01-21 19:03 UTC, T6751 commented
> а где впринципе изменения?

Вот тут
![image](https://user-images.githubusercontent.com/66636084/105399201-5e97e600-5c34-11eb-9f6f-e6b7158030dc.png)

2021-01-21 19:04 UTC, KIBORG04 commented
Ну мне такой фикс не нравится, я даже указал в чём проблема

2021-01-21 19:07 UTC, T6751 commented on code/game/turfs/simulated/floor.dm
> +		if(istype(src, /turf/simulated/floor/plating/airless/asteroid))
Это не очень хорошее решение, т.к. кроме астероида ещё есть свалка (```/turf/simulated/floor/plating/ironsand/junkyard/safe```) и вероятно будут другие исключения. Лучше поискать другое решение

2021-02-01 07:21 UTC, Zickusable commented on code/game/turfs/simulated/floor.dm
> +		if(istype(src, /turf/simulated/floor/plating/airless/asteroid))
А теперь?

2021-02-01 08:41 UTC, T6751 commented on code/game/turfs/simulated/floor.dm
> +		if(!(icon_state in list("plating","platingdmg1","platingdmg2","platingdmg3")))
Зависимость от названия спрайта это очень ненадежно, т.к. если оно изменится/исчезнет, то мы не сможем сразу отследить этот момент

Возможно стоит просто сделать белый список?

2021-02-04 10:01 UTC, Zickusable commented on code/game/turfs/simulated/floor.dm
> +		if(!(icon_state in list("plating","platingdmg1","platingdmg2","platingdmg3")))
Сейчас должно быть правильно. У меня работает как надо.

2021-02-04 10:10 UTC, Kortez90 commented on code/game/turfs/simulated/floor.dm
> +		if(istype(src,/turf/simulated/floor/plating))
```suggestion
		if(istype(src, /turf/simulated/floor/plating))
```

2021-02-04 10:20 UTC, Zickusable commented on code/game/turfs/simulated/floor.dm
> +		if(istype(src,/turf/simulated/floor/plating))
Для того, чтобы отбросить подвиды, например астероид и свалку.

2021-02-04 21:08 UTC, T6751 commented on code/game/turfs/simulated/floor.dm
> +			return
Мне кажется, потерялась сама суть этого ПРа, что можно разбирать пол? Т.к. этим запрещается в принципе разбирать все турфы пола /turf/simulated/floor/plating и дочерние в том числе.

Учитывая, что сейчас в целом можно выделить лишь два типа пола, которые можно разбирать:
```/turf/simulated/floor/plating, /turf/simulated/floor/plating/airless```

То думаю будет нормальным сделать следующим образом

```
if(!(type in list(/turf/simulated/floor/plating, /turf/simulated/floor/plating/airless))
	return
```

То есть, если тип турфа не является строго ```/turf/simulated/floor/plating``` или ```/turf/simulated/floor/plating/airless```, то разобрать его не получится

2021-02-04 21:14 UTC, KIBORG04 commented on code/game/turfs/simulated/floor.dm
> +			return
ну либо сделать перемененную can_deconstruct и порасставлять где надо и где не надо...

2021-02-04 21:15 UTC, T6751 commented on code/game/turfs/simulated/floor.dm
> +			return
> ну либо сделать перемененную can_deconstruct и порасставлять где надо и где не надо...

Или так, да

2021-02-06 17:31 UTC, T6751 commented on code/game/turfs/simulated/floor_types.dm
> +	can_deconstruct = FALSE
Необязательно здесь указывать FALSE, если оно итак по умолчанию для всех /turf идёт FALSE
```suggestion
```

2021-02-06 21:24 UTC, KIBORG04 commented on code/game/turfs/simulated/floor.dm
> +		if(can_deconstruct != TRUE)
```suggestion
		if(!can_deconstruct)
```
В нашем билде принято именно писать просто знак перед переменной

2021-02-12 14:13 UTC, T6751 approved these changes

2021-02-12 21:10 UTC, merged