Добавление пару новых network'ов и мини-фикс камер
TauCetiStation/TauCetiClassic pull request #6682
Opened 2021-01-10 13:28 UTC by BesumniiChebureck

## Описание изменений
Камерам на СБшых территориях (включая чекпоинты) дан network("Security"). В варденскую и в конференц зал поставлен Телескрин с нетворками "Prison" (в конференц зале без него) и "Security". Хоть у офицеров и так есть доступ к почти всем камерам станции, так будет проще следить за бригом. Также офицерским боргам выдается network("Security")

Камерам на Инженерных территориях (включая точки перед солнечными панелями и атмосферный отдел) дан network("Engineering"), хоть он существовал и раньше, он толи был не доделан, толи нужен был только для слежки за инж. боргами и дронами. Боргам всё ещё дается network("Engineering"), а дронам выдается уже другой, network("Drone"). Телескрины в офисе СЕ и по инженерке.

Починены c_tag'и некоторых камерых.
## Почему и что этот ПР улучшит
Сделает жизнь инженерного и офицерского отдела лучше.
fix #6667 (хоть это и не баг)
fix #6668
## Авторство
Я
## Чеинжлог
:cl:
- bugfix: Юго-западная камера центрального коридора, получила правильное название.
- map: Инженерам и Офицерам, были добавлены Telescreen'ы, позволяющие наблюдать за камерами в своем отделе.

2021-01-10 13:28 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2021-01-10 19:23 UTC, T6751 requested changes
Не пройдена проверка 
![image](https://user-images.githubusercontent.com/66636084/104133115-764cb000-5392-11eb-8794-82b269e6861c.png)

То, что ниже было бы желательно сделать, но не если нет, то напиши.

2021-01-10 19:23 UTC, T6751 commented on maps/gamma/gamma.dmm
> +	network = list("Drone")
Можешь, пожалуста, в коде ```code/game/machinery/computer/camera.dm``` добавить объект типа:
```
/obj/machinery/computer/security/engineering/drone
	name = "drone monitoring cameras"
	desc = "Used to monitor Drones."
	network = list("Drone")
```
И заменить здесь соответственно

2021-01-10 19:23 UTC, T6751 commented on maps/boxstation/boxstation.dmm
> +	pixel_x = 28
Можешь в ```code/game/machinery/computer/camera.dm```, пожалуста, добавить код типа:
```
/obj/machinery/computer/security/telescreen/engineering
	name = "engineering monitor"
	desc = "Used for watching the Engineering Department."
	network = list("Engineering")
```

2021-01-10 19:23 UTC, T6751 commented on maps/boxstation/boxstation.dmm
> +	network = list("SS13","Engineering")
Думаю было бы удобнее и красиво, если бы камерам выдавался нетворк от зоны, но это не в рамках этого ПРа. Просто комментарий

2021-01-11 11:55 UTC, BesumniiChebureck commented on maps/boxstation/boxstation.dmm
> +	pixel_x = 28
Все телескрины, сделаны через карту, а не код. Если кто-то захочет добавить новый монитор, то ему обязательно придется лезть в код, не думаю что это хорошая идея, учитывая ещё и количество различных телескринов.

2021-01-11 12:50 UTC, Kortez90 commented
А это что и зачем?
![Безымянный](https://user-images.githubusercontent.com/36198983/104184591-bc525400-5424-11eb-9414-e1c577f646c9.png)

2021-01-11 13:17 UTC, BesumniiChebureck commented
Телескрин в офис СЕ, чтобы мог наблюдать за инженерией и инж. боргами. Пришлось потрогать объекты на стене, ибо места там крайне мало. А цветок... сейчас верну.

2021-01-11 14:55 UTC, AirBlack commented on maps/boxstation/boxstation.dmm
> +	pixel_x = 28
я мб потом сделаю норм конструкцию как телескринов так и консолей камер с нормальными платами

2021-01-11 19:45 UTC, AirBlack commented on maps/boxstation/boxstation.dmm
> +	network = list("SS13","Engineering")
думаю нетворки лучше впихать в платы чем в сами консоли

2021-01-11 19:53 UTC, AirBlack commented on maps/boxstation/boxstation.dmm
> +	network = list("SS13","Engineering")
да я так подумал, неплохо было бы рефакторнуть консоли в целом дабы их функционал полностью зависел от кода в плате а не от имплементации самой консоли, дабы можно было платы от любой консоли вставлять в любой подходящий корпус, будь то телескрин или нубук или че там еще бывает

2021-01-11 20:25 UTC, T6751 commented on maps/boxstation/boxstation.dmm
> +	pixel_x = 28
> Если кто-то захочет добавить новый монитор, то ему обязательно придется лезть в код, не думаю что это хорошая идея, учитывая ещё и количество различных телескринов.

А если бы у нас было несколько карт, а не одна коробка, и нужно было бы добавить туда все телескрины из коробки, то разве не проще было бы видеть список доступных телескринов с готовым описанием, нетворками, чем ручками трогать переменные в мапедиторе и копировать?

2021-01-11 22:23 UTC, T6751 requested changes
Лучше не размещать на одном тайле несколько консолей. Так, если разобрать телескрин, то получится две консоли на одном тайле, что не очень хорошо

![image](https://user-images.githubusercontent.com/66636084/104243547-c6e70a80-5471-11eb-8742-2e91fdc3a398.png)

![image](https://user-images.githubusercontent.com/66636084/104243107-1ed14180-5471-11eb-8505-db3b7a94d038.png)

2021-01-12 12:01 UTC, T6751 approved these changes

2021-01-20 00:05 UTC, merged