airlock_crush_act()
TauCetiStation/TauCetiClassic pull request #6701
Opened 2021-01-13 07:07 UTC by Morar1

## Описание изменений
airlock_crush_act - функция вызывающаяся у атом-ов при закрытии двери
Closets/crates/windows/mechs получают урон при нахождении на тайле с закрывающаяся дверью, фазон в phasing моде не получает урона
Tables/racks destroy()-тся
Попросили реализовать именно так.
## Почему и что этот ПР улучшит
https://github.com/TauCetiStation/TauCetiClassic/pull/6566#discussion_r554220526
Не ломаемые шкафчики/сундуки можно сломать зажав их пару раз
## Авторство

## Чеинжлог
🆑
* tweak: Столы/окна/шкафчики/сундуки/мехи получают урон закрывающаяся дверью
* tweak: Люди/ксеноморфы/борги воспроизводят звук scream/roar/buzz когда их зажимает дверью

2021-01-13 07:07 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2021-01-13 08:48 UTC, Sakuya-Izayoi commented
Тогда наверное нужно сделать чтобы двери со включенным сейфти не закрывались, пока на их тайле находятся какие-то структуры или мехи, потому что это слишком имбово получается.

2021-01-13 09:30 UTC, Morar1 commented
> Тогда наверное нужно сделать чтобы двери со включенным сейфти не закрывались, пока на их тайле находятся какие-то структуры или мехи, потому что это слишком имбово получается.

Добавлю чтоб не закрывались тогда

>А спу кричат или что делают когда их зажимают? А немые?

Хендлится же системой эмоутов. То что спу кричат как люди это проблема системы эмоутов...

2021-01-13 09:47 UTC, KIBORG04 commented on code/game/machinery/doors/airlock.dm
> +		S.airlock_crush_act()
Ты же сделал прок для всех атомов. Почему бы тогда не заменить все на. А сообщение у ливингов перенести в этот же airlock_crush_act()
```
for(var/atom/A in src_turf)
    A.airlock_crush_act()
```

2021-01-13 09:59 UTC, Morar1 commented on code/game/machinery/doors/airlock.dm
> +		S.airlock_crush_act()
Вызов функций же тоже что-то стоит

2021-01-13 10:03 UTC, KIBORG04 commented on code/game/machinery/doors/airlock.dm
> +		S.airlock_crush_act()
Считай, что это ПРИМЕРНО равнозначный код.
```
for(var/obj/structure/S in src_turf)
    S.code
====
for(var/A in src_turf)
    if(istype(A, /obj/structure)
        var/obj/structure/S = A
        S.code
```
Так вот, ты делаешь 3 цикла по одному турфу и мне кажется, что это тяжелее одного цикла по всем предметам. К тому же, кодеры будущего могут не знать, что вот тут есть такой костыль и что нужно добавлять четвертый, пятый, шестой цикл.

2021-01-13 10:06 UTC, Morar1 commented on code/game/machinery/doors/airlock.dm
> +		S.airlock_crush_act()
Ну кстати да, твой вариант лучше чем костыли мои

2021-01-13 10:14 UTC, Sakuya-Izayoi commented
> > Тогда наверное нужно сделать чтобы двери со включенным сейфти не закрывались, пока на их тайле находятся какие-то структуры или мехи, потому что это слишком имбово получается.
> 
> Добавлю чтоб не закрывались тогда, только для мехов, потому что другие структуры по типу кабелей будут мешаться
> 
> > А спу кричат или что делают когда их зажимают? А немые?
> 
> Хендлится же системой эмоутов. То что спу кричат как люди это проблема системы эмоутов...

можно делать не по типу структуры, а по денсити переменной

2021-01-13 10:30 UTC, Kortez90 commented on code/modules/mob/living/silicon/robot/robot.dm
> +	emote("buzz")
Зажатых в дверях боргов теперь не дамажит?

2021-01-13 11:37 UTC, Morar1 commented on code/game/machinery/doors/airlock.dm
> +				if(A.density)
мне на самом деле не нравится решение что мы по всем atom-ам проходимся на турфе и потом еще что-то делаем с каждым из них

2021-01-13 16:46 UTC, LudwigVonChesterfield commented on code/game/machinery/doors/airlock.dm
> +				if(A.density)
почему? как должно быть иначе?

2021-01-13 17:07 UTC, Morar1 commented on code/game/machinery/doors/airlock.dm
> +				if(A.density)
>как должно быть иначе?

Да особо никак если не заморачиваться, я просто оставил как было раньше и перенес логику в ```/obj/structure/airlock_crush_act()```. Просто дверей же много и каждая дверь это минимум 3 атома...

2021-01-13 21:36 UTC, LudwigVonChesterfield commented on code/game/machinery/doors/airlock.dm
> +		A.airlock_crush_act()
А то что это в том числе вызывает у самой же давящей двери эту функцию - это точно не проблема?

2021-01-13 21:44 UTC, 4310V343k commented on code/game/machinery/doors/airlock.dm
> +		A.airlock_crush_act()
<details>

  <summary>.</summary>
  
Я ждал пока кто-нибудь это заметит
</details>

2021-01-13 22:11 UTC, Zmey25 commented
Скрытый баф карго

2021-01-14 06:37 UTC, Morar1 commented on code/game/machinery/doors/airlock.dm
> +		A.airlock_crush_act()
Вообще - нет, ну на будущее можно поменять

2021-01-17 21:15 UTC, KIBORG04 commented on code/game/objects/structures.dm
> +	if(!density)
А зачем здесь проверять на отсутствие денсити? Разве не всё равно ли?

2021-01-17 21:17 UTC, KIBORG04 approved these changes

2021-01-24 18:23 UTC, Morar1 commented on code/game/objects/structures.dm
> +	if(!density)
Просто хотелось чтоб вещи через которые могут пройти хуману не двигались

2021-01-24 23:17 UTC, T6751 commented on code/game/machinery/doors/airlock.dm
> +	for(var/atom/A in range(0, src) - src)
```suggestion
	for(var/atom/A in orange(0, src))
```

2021-01-26 00:11 UTC, T6751 requested changes
Не думаю, что это хорошая идея, чтобы позволять ломать сейфы и защищенные замком ящики так просто в три удара шлюзом. 
![image](https://user-images.githubusercontent.com/66636084/105781536-cbd4af80-5f83-11eb-8c46-7fea7f66625f.png)

2021-01-26 00:15 UTC, KIBORG04 commented
```
tweak: Столы/окна/шкафчики/сундуки/мехи получают урон закрывающаяся дверью
========>
tweak: Столы/окна/шкафчики/сундуки/мехи получают урон от закрывающегося аирлока
```

>tweak: Люди/ксеноморфы/борги воспроизводят звук scream/roar/buzz соответственно, когда их зажимает дверью

Сомнительный пункт чейджлога

> Не думаю, что это хорошая идея, чтобы позволять ломать сейфы и защищенные замком ящики так просто в три удара шлюзом.

А мне наоборот нравится. Может лучше Елдерна Балансера позвать?

2021-01-26 00:21 UTC, T6751 commented
@Edlern, можешь помочь, пожалуста. Что думаешь о том, что теперь можно будет ломать любые ящики за три удара шлюзом?

![crates](https://user-images.githubusercontent.com/66636084/105782340-61bd0a00-5f85-11eb-913a-693e2530e2f8.gif)

2021-01-26 02:34 UTC, EdlerN commented
> Что думаешь о том, что теперь можно будет ломать любые ящики за три удара шлюзом?
Это смешно и грустно. Грустно по той причине, что кто-то думает что это хорошая идея - разрешить ломать защищённые ящики шлюзами. И ладно карго, оно их кинетиками и так ломает без проблем. Мне больше не нравится то что так вообще все ящики можно ломать будет. Кража трусов хоса никогда не была столь простой. 
Лучше бы сделал просто чтобы шлюзы с ящиками/мехами в них не закрывались от слова никак. А так бред какой-то

2021-01-26 18:38 UTC, T6751 approved these changes

2021-01-26 19:01 UTC, merged