Robolimbs remastered: revenge of the sprite
TauCetiStation/TauCetiClassic pull request #6739
Opened 2021-01-19 20:43 UTC by totallynotdedawa2

## Описание изменений
Респрайтит протезы 

без одежды
![image](https://user-images.githubusercontent.com/61105647/105090847-0041fa80-5ab0-11eb-9be7-525dcbe6ca1f.png)
в одежде
![image](https://user-images.githubusercontent.com/61105647/105090896-15b72480-5ab0-11eb-95cb-c3a780c457a9.png)

## Почему и что этот ПР улучшит
меньше спрайтов которые мне не нравятся
## Авторство
coiscin
## Чеинжлог
:cl:
- image: Респрайт протезов

2021-01-19 20:43 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2021-01-19 20:47 UTC, AndroBetel commented
куриные лапки

2021-01-19 20:48 UTC, totallynotdedawa2 commented
> куриные лапки

ножки буша

2021-01-20 06:50 UTC, TheLustOfBlood commented
Ноги имхо тонкие слишком, либо они сливаются с полом там..

2021-01-22 13:40 UTC, UDaV73rus requested changes
Не удачное соединение с хуманом, в плечах со спины более лучший вариант соединения
Также следует придумать как сделать лучше стопы спереди/сзади, и особенно ладони
r_leg имеет второй кадр и мигающий пиксель в икондифе, полупрозрачный пиксель

2021-02-12 13:22 UTC, T6751 commented
Сообщите, если нужно будет переоткрыть ПР

2021-02-12 13:22 UTC, closed without merging