Отпимизация при изменении человечка в лобби
TauCetiStation/TauCetiClassic pull request #6755
Opened 2021-01-21 00:00 UTC by KIBORG04

## Описание изменений
При онлайне в 70 человек дамми в лобби очень-очень часто пересоздавалась болванка хумана, делающая превью куклы игрока. Можно сказать, любой клик по кнопки пересоздавал дамми.

(У меня нету скрина с ДО при большом онлайне, так что можете поверить этой вырезке)
```
Path: /mob/living/carbon/human/dummy
    qdel() Count: 917
    Destroy() Cost: 674.288ms
    Total Hard Deletes 917
    Time Spent Hard Deleting: 186887ms
```

| До при ~17 людей     | После                |
| ------------- |:------------------:|
| ![до, онлайн 17](https://user-images.githubusercontent.com/26389417/105254658-242a3c80-5b93-11eb-811d-78bd999edc4f.PNG)    | ![после](https://user-images.githubusercontent.com/26389417/105254522-d9102980-5b92-11eb-836c-7ec142ef87ee.PNG)    |

Да, в После их даже нету, ведь мы кэшируем, а не удаляем!
Не уверен, но, возможно, человечки будут появляться с запозданием у игроков, ведь теперь мы юзаем одного дамми на всех людей. И вот стоит это как-то узнать, посмотреть, поэтому ТМ

## Почему и что этот ПР улучшит
ОпТиМиЗаЦиЯ

## Авторство
ТГ

## Чеинжлог
А нужен ли?

2021-01-21 04:12 UTC, T6751 requested changes
\- Зайти в окошко с персонажем до инициализации всех систем
\- Дождаться инициализации
\- Обновить
\- Человечка всё ещё нет

<details>

![20210121 070939](https://user-images.githubusercontent.com/66636084/105279009-bb08f000-5bb7-11eb-9212-b8104cf23985.png)

</details>

2021-01-21 10:09 UTC, Sakuya-Izayoi commented
А можно сделать так чтобы на человечка надевались итемы из лоудаутв?

2021-01-21 13:02 UTC, T6751 commented
> А можно сделать так чтобы на человечка надевались итемы из лоудаутв?

Можно, но это не в рамках этого ПРа

2021-01-21 15:01 UTC, KIBORG04 commented
https://user-images.githubusercontent.com/26389417/105368289-6cd50a80-5c12-11eb-9c23-7b4726734efd.mp4

Не уверен что нынеший способ решения проблемы нормальный, но он работает!

2021-01-21 15:34 UTC, T6751 commented
> Не уверен что нынеший способ решения проблемы нормальный, но он работает!

Чтобы повторить баг, видимо, нужно зайти ещё раньше.

2021-01-21 15:35 UTC, KIBORG04 commented
> Чтобы повторить баг, видимо, нужно зайти в окно с персонажем ещё раньше.

Не, я повторил, я сделал фикс и пытаюсь его сделать лучше

2021-01-25 23:09 UTC, T6751 commented on code/modules/mob/living/carbon/species.dm
> +		var/obj/item/organ/O = new path(null, H)
Второй аргумент больше не нужен
```suggestion
		var/obj/item/organ/O = new path(null)
```

2021-01-25 23:09 UTC, T6751 commented on code/modules/mob/living/carbon/species.dm
> +		var/obj/item/organ/O = new path(null, H)
Второй аргумент больше не нужен
```suggestion
		var/obj/item/organ/O = new path(null)
```

2021-01-25 23:10 UTC, T6751 commented
> А нужен ли?

Теперь, когда человечек появляется до инициализации системы, можно об этом упомянуть

2021-01-25 23:17 UTC, KIBORG04 commented
> Теперь, когда не нужно ждать инициализации систем для появления человечка, можно об этом упомянуть

Ну, этого можно было добиться и раньше, а сейчас это производное для костыльной(потому что я не понимаю почему оно работает только так, а не иначе), но нормальной(наверное) работы

2021-01-26 21:26 UTC, T6751 commented
Люди с протезами спавнятся без ног

```
[00:11:36] Runtime in organ_external.dm, line 275: Cannot execute null.damage state color().
proc name: damage state color (/obj/item/organ/external/proc/damage_state_color)
usr: The unknown () (/mob/living/carbon/human/dummy)
src: the chest (/obj/item/organ/external/chest)

src.loc: null
call stack:
the chest (/obj/item/organ/external/chest): damage state color()
the unknown (/mob/living/carbon/human/dummy): UpdateDamageIcon(the chest (/obj/item/organ/external/chest))
the unknown (/mob/living/carbon/human/dummy): regenerate icons()
the unknown (/mob/living/carbon/human/dummy): set species("Human", 1, 1)
the unknown (/mob/living/carbon/human/dummy): atom init(1, "Human")
Atoms (/datum/controller/subsystem/atoms): InitAtom(the unknown (/mob/living/carbon/human/dummy), /list (/list))
the unknown (/mob/living/carbon/human/dummy): New(1, "Human")
generate or wait for human dummy("dummy_preference_preview", "Human")
/datum/preferences (/datum/preferences): update preview icon()
/datum/preferences (/datum/preferences): ShowChoices(██████ (/mob/dead/new_player))
██████ (/mob/dead/new_player): Topic("src=\[0x300000c];show_preferen...", /list (/list))
██████ (/client): Topic("src=\[0x300000c];show_preferen...", /list (/list), ██████ (/mob/dead/new_player))
```

2021-01-27 00:31 UTC, KIBORG04 commented
> Люди с протезами спавнятся без них

Рантаймит, потому что один прикол создаётся в атом_ините, а мы как раз отходим от них. Вообщем, один инит поменять и опять ТМ? Крч потещу я это подольше..

2021-01-27 11:32 UTC, KIBORG04 commented
![image](https://user-images.githubusercontent.com/26389417/105985238-413b9f80-60ac-11eb-8171-b475459bc411.png)

Я вроде многое починил и не смог баги начать делать, но если и будут, то только визуал

2021-01-30 21:38 UTC, LudwigVonChesterfield commented on code/modules/mob/living/carbon/human/dummy.dm
> +//Inefficient pooling/caching way.
это не то чтобы делает ПР хуже, но мне очень кажется смешным как в ПР-е про "оптимизацию" комментарий с текстом "неэффективный способ кэшировать"

2021-01-30 21:39 UTC, LudwigVonChesterfield commented on code/modules/mob/living/carbon/human/dummy.dm
> +		UNTIL(!D.in_use)
а не нужно проверять что D ещё существует?

2021-01-30 21:39 UTC, LudwigVonChesterfield commented on code/modules/mob/living/carbon/human/inventory.dm
> +/mob/living/carbon/human/proc/get_body_slots()
предположение что возможно это когда-нибудь придётся вынести в органы

2021-01-30 21:40 UTC, LudwigVonChesterfield commented on code/modules/mob/living/carbon/human/inventory.dm
> +/mob/living/carbon/human/proc/get_all_slots()
я уверен что у нас есть много мест где эта функции хочет быть использованной

2021-01-30 21:50 UTC, KIBORG04 commented on code/modules/mob/living/carbon/human/dummy.dm
> +//Inefficient pooling/caching way.
Ну лучше же, чем было до этого

2021-01-30 21:51 UTC, KIBORG04 commented on code/modules/mob/living/carbon/human/dummy.dm
> +		UNTIL(!D.in_use)
Так D будет существовать всегда

2021-02-16 00:00 UTC, T6751 commented on code/modules/surgery/braincore.dm
> +	brain.insert_organ(target)
Думаю лучше объединить эти два прока в один insert_organ (можно просто перенести set_owner внутрь insert_organ)? Не думаю, что орган может иметь owner моб "A", но при этом быть вставленным в моба "B".

2021-02-18 19:24 UTC, KIBORG04 commented
На ТГ для этого юзается отдельный экземпляр расы, в котором и настраиваются протезы. Я решил это изменить на такой лист(см. коммит) с инфой о всех возможно изменяемых органах

2021-02-18 19:34 UTC, KIBORG04 commented
@T6751 Что скажешь на это?

2021-02-19 09:37 UTC, T6751 commented on code/modules/client/preferences_savefile.dm
> +		popup(parent, "Ваш персонаж ([real_name]) был несовместим изменёнными частями тела. У этого персонажа части тела восстановлены до обычного состояния.", "Preferences")
```suggestion
		popup(parent, "Части тела вашего персонажа ([real_name]) несовместимы с текущей версией. Части тела данного персонажа восстановлены до обычного состояния.", "Preferences")
```

2021-02-19 09:55 UTC, T6751 approved these changes

2021-02-19 10:07 UTC, T6751 requested changes

2021-02-19 10:13 UTC, KIBORG04 commented on code/modules/mob/living/carbon/human/human_damage.dm
> +			new path(null)
Добавил. Я нашел еще одно похожее место и добавил инсерт_орган

2021-02-19 13:58 UTC, T6751 approved these changes

2021-02-19 14:07 UTC, merged

2023-03-13 07:43 UTC, Sakuya-Izayoi commented on code/modules/client/preferences.dm
> +	character.set_species(species)
ну что за бэкдоры, киборг...

2024-04-02 16:27 UTC, KIBORG04 commented on code/modules/client/preferences.dm
> +	character.set_species(species)
Что за бэкдор?

2024-04-02 16:29 UTC, KIBORG04 commented on code/__DEFINES/misc.dm
> +#define DUMMY_HUMAN_SLOT_BARBER "dummy_barbet_preview"
BARBET

2025-03-29 20:43 UTC, volas commented on code/modules/organs/organ_external.dm
> +		update_sprite()
Мне кажется, это в итоге сломало фичу с пришитием чужих частей из https://github.com/TauCetiStation/TauCetiClassic/pull/3726

Так как всегда выставляется species от нового владельца, конечность начинает использовать новые спрайты, а не старые

2025-03-31 17:17 UTC, volas commented on code/modules/organs/organ_external.dm
> +	controller = new controller_type(src)
это зря было вынесено из инита, оно дублирует контроллер не удаляя старый, а там еще везде ссыки и возможный процессинг