Фикс гидропоники
TauCetiStation/TauCetiClassic pull request #6766
Opened 2021-01-22 13:57 UTC by Rolt146

## Описание изменений
Теперь при обновлении деталек нутриенты и вода не будут изменяться внутри гидропоники
Колбочки с нутриентами из автомата теперь добавляют нутриенты, а не приравнивают их к значению 10
## Почему и что этот ПР улучшит
фикс #6731 
## Авторство
Rolt
## Чеинжлог
:cl:
 - bufgix: нутриенты и вода не изменяются при улучшении гидропоники. Удобрения из автоматов добавляют, а не приравнивают 10 нутриентов.

2021-01-22 13:58 UTC, TauKitty commented
###### Changelog status: :x: Invalid changelog classes (bufgix)

2021-01-22 14:12 UTC, Sakuya-Izayoi commented on code/game/machinery/hydroponics.dm
> +			nutrilevel = maxnutri
```suggestion
		nutrilevel = min(nutrilevel + 10, maxnutri)
```

2021-01-22 14:25 UTC, KIBORG04 commented on code/game/machinery/hydroponics.dm
>  		to_chat(user, "You replace the nutrient solution in [src].")
> Колбочки с нутриентами из автомата теперь добавляют нутриенты, а не приравнивают их к значению 10

А разве это сообщение не говорит о том, что это был не баг?

2021-01-22 15:46 UTC, Rolt146 commented on code/game/machinery/hydroponics.dm
>  		to_chat(user, "You replace the nutrient solution in [src].")
и как тогда лучше написать?

2021-01-22 15:48 UTC, Kortez90 commented on code/game/machinery/hydroponics.dm
>  		to_chat(user, "You replace the nutrient solution in [src].")
Что написать? Удар колбой с нутриментами заменял, а не добавлял новые.

2021-01-22 15:49 UTC, KIBORG04 commented on code/game/machinery/hydroponics.dm
>  		to_chat(user, "You replace the nutrient solution in [src].")
Ты говоришь, что это баг, но это сообщение показывает, что так и подразумевалось.

2021-01-25 20:45 UTC, T6751 commented on code/game/machinery/hydroponics.dm
> +			nutrilevel = maxnutri
Так как это работает, как задумывалось, то стоит вернуть как было, иначе это твик, а не фикс
```suggestion
		nutrilevel = 10
```

2021-01-25 20:45 UTC, T6751 requested changes
См. выше

2021-02-16 08:42 UTC, T6751 requested changes
По ревью выше ничего не отвечено и не исправлено

2021-02-17 10:51 UTC, Rolt146 commented
> По ревью выше (от меня, от Киборга) ничего не отвечено и не исправлено

Так ведь вы уже сделали изменение... или их самому нужно подтвердить?

2021-02-17 11:03 UTC, T6751 commented
> Так ведь вы уже сделали изменение... или их самому нужно подтвердить?

Это лишь предложенные изменения (Suggested changes).
Их можно закоммитить кнопочкой [Commit], если нет возражений

2021-02-18 20:06 UTC, Rolt146 commented
> > Так ведь вы уже сделали изменение... или их самому нужно подтвердить?
> 
> Это лишь предложенные изменения (Suggested changes).
> Их можно закоммитить кнопочкой [Commit], если нет возражений

Все, изменил. Ожидаю мержа

2021-02-18 20:28 UTC, KIBORG04 commented
Чейнждлог изменить, описание ПРа еще можно тоже изменить. Еще можно аргументировать зачем теперь 3 нутримента спавнится по дефолту, а не 10

2021-02-19 18:29 UTC, Rolt146 reviewed
Оптимизирование кода

2021-02-24 07:39 UTC, KIBORG04 requested changes
Чейнждлог измени, описание ПРа тоже измени. 
Еще напиши почему и зачем теперь 3 нутримента спавнится по дефолту, а не 10.

2021-02-26 18:50 UTC, T6751 commented on code/game/machinery/hydroponics.dm
> +	var/nutrilevel = 3              //The amount of nutrient in the tray (max 10)
```suggestion
	var/nutrilevel = 10              //The amount of nutrient in the tray (max 10)
```

2021-02-27 12:04 UTC, KIBORG04 commented on code/game/machinery/hydroponics.dm
> +	var/nutrilevel = 3              //The amount of nutrient in the tray (max 10)
> что бы не абузили разбор гидропоники и его обратной сборки

2021-02-27 12:58 UTC, KIBORG04 approved these changes
Как-то все очень сумбурно вышло. Вообщем, должно наверное работать

2021-03-01 19:58 UTC, KIBORG04 requested changes

2021-03-01 19:58 UTC, KIBORG04 commented on code/game/machinery/hydroponics.dm
>  		to_chat(user, "You replace the nutrient solution in [src].")
Измени, на то что ты ДОБАВЛЯЕШЬ нутриенты а не ЗАМЕНЯЕШЬ

2021-03-02 12:34 UTC, KIBORG04 commented on taucetistation.dme
>  #include "code\__DEFINES\atmospherics.dm"
изменений этого файла быть не должно

2021-03-12 00:25 UTC, merged