Add sy-code lang to syndi borg
TauCetiStation/TauCetiClassic pull request #6795
Opened 2021-01-28 10:39 UTC by kalazus

## Описание изменений
Добавил Sy-Code синдиборгу.
Немного изменил добавление языков, теперь оно происходит во время инициализации модуля.

## Почему и что этот ПР улучшит
Разговор с синдиборгом.
closes #6734 #6793

## Авторство
Я

## Чеинжлог
:cl: Kalazus
- bugfix: Синдиборги теперь могут говорить на сикоде и базовых языках боргов.

2021-01-28 10:39 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2021-01-28 10:43 UTC, KIBORG04 commented
![image](https://user-images.githubusercontent.com/26389417/106126693-c091a780-616e-11eb-9d3b-d46a19454609.png)

Оно не работает, если вот так перечислить. Напиши по отдельности.

2021-01-28 11:13 UTC, BesumniiChebureck commented
Только Си-код? А язык жестов, сол коммон, трабебанд? Если не ошибаюсь у синдиборгов тоже с этим проблемы.

2021-01-28 12:30 UTC, kalazus commented
> Только Си-код? А язык жестов, сол коммон, трабебанд? Если не ошибаюсь у синдиборгов тоже с этим проблемы.

Обновил описание, там сол, трейд, тринарный и сикод

2021-01-28 12:48 UTC, T6751 commented on code/modules/mob/living/silicon/robot/robot_modules.dm
> +	R.add_language("Sy-Code", TRUE)
Для чего нужен TRUE?
```suggestion
	R.add_language("Sy-Code")
```

2021-01-28 12:48 UTC, T6751 commented on code/modules/mob/living/silicon/robot/robot_modules.dm
> +	. = ..(R)
```suggestion
	. = ..()
```

2021-01-28 16:20 UTC, T6751 approved these changes

2021-01-29 20:09 UTC, T6751 requested changes

2021-01-29 20:09 UTC, T6751 commented on code/modules/mob/living/silicon/robot/robot_modules.dm
> +		add_languages(R)
Нет гарантии того, что loc будет обязательно боргом
```suggestion
	if(isrobot(loc))
		var/mob/living/silicon/robot/R = loc
		add_languages(R)
```

2021-01-30 00:07 UTC, kalazus commented on code/modules/mob/living/silicon/robot/robot_modules.dm
> +		add_languages(R)
Разве? Мы приводим loc к типу борга. Если loc не борг разве в R не будет null?

2021-01-30 00:15 UTC, kalazus commented on code/modules/mob/living/silicon/robot/robot_modules.dm
> +		add_languages(R)
Вообще даже моя проверка мне кажется немного лишней, учитывая что это компонента борга и вообще не должна создаватьсч не в нём.

2021-01-30 01:50 UTC, T6751 commented on code/modules/mob/living/silicon/robot/robot_modules.dm
> +		add_languages(R)
> Если loc не борг разве в R не будет null?

Увы, это так не работает. Если loc, например, будет турф, то в R будет турф, а не null, и соответственно if(R) это TRUE

> Вообще даже моя проверка мне кажется немного лишней, учитывая что это компонента борга и вообще не должна создаваться не в нём. А с проверкой ошибку не найти.

Видимо сейчас действительно не ожидается, чтобы модуль создавался вне борга, так что пожалуй ОК

2021-01-30 07:22 UTC, kalazus commented on code/modules/mob/living/silicon/robot/robot_modules.dm
> +		add_languages(R)
> Видимо сейчас действительно не ожидается, чтобы модуль создавался вне борга, так что пожалуй ОК.

Так всёже убрат  if?

2021-01-30 07:28 UTC, T6751 commented on code/modules/mob/living/silicon/robot/robot_modules.dm
> +		add_languages(R)
Да, можно убрать

2021-01-30 09:19 UTC, T6751 approved these changes

2021-01-30 09:49 UTC, merged