inhands для барбишопа
TauCetiStation/TauCetiClassic pull request #6799
Opened 2021-01-28 18:20 UTC by AndroBetel

## Описание изменений
сделаны создателем барбишопа лижардом
## Почему и что этот ПР улучшит
он их забыл
## Авторство
ажаж
## Чеинжлог

2021-01-28 18:20 UTC, TauKitty commented
###### Changelog status: :radio_button: No changelog

2021-01-28 18:25 UTC, Kortez90 commented on code/modules/reagents/reagent_containers/spray.dm
> +		usr.update_inv_r_hand()
Почему это в ините?

2021-01-28 18:31 UTC, AndroBetel commented on code/modules/reagents/reagent_containers/spray.dm
> +		usr.update_inv_r_hand()
в смысле в ините

2021-01-28 18:39 UTC, AndroBetel commented
это спрайты от члена спрайт департамента так что их можно мержить (он забыл их к предыдущему пру дорисовать)

2021-01-28 21:21 UTC, LiLJard approved these changes

2021-01-28 21:45 UTC, KIBORG04 commented
![image](https://user-images.githubusercontent.com/26389417/106202679-46434080-61cb-11eb-9b22-e10c5942ccce.png)

Чё-то тут не так

2021-01-29 20:01 UTC, T6751 requested changes
Нужно исправить смещенный вправо спрайт. см.выше

2021-02-03 18:16 UTC, AndroBetel commented
ой.

2021-02-03 18:36 UTC, AndroBetel commented
зафикшено

2021-02-03 18:51 UTC, T6751 approved these changes

2021-02-03 18:52 UTC, merged