Реворк культа
TauCetiStation/TauCetiClassic pull request #6843
Opened 2021-02-07 18:55 UTC by KIBORG04

## [Для Работяг](https://wiki.taucetistation.org/Участник:KIBORG/borer)
[Культ](https://wiki.taucetistation.org/Участник:KIBORG/borer) был переосмыслен в сторону меньшего хаоса и большей понятливости анти[вики](https://wiki.taucetistation.org/Участник:KIBORG/borer)чечников. В данным момент он может быть плохо забаланшен в цифрах, но это будет исправляться. [Гайд](https://wiki.taucetistation.org/Участник:KIBORG/borer) только по [ссылке](https://wiki.taucetistation.org/Участник:KIBORG/borer) ниже:
https://wiki.taucetistation.org/Участник:KIBORG/borer
А ещё вам я запрещаю выражать уникальное и очень важное ваше мнение под этим ПРом, нойте на форуме ссылаясь на этот ПР, пожалуйста. (контрибутеров это не касается)

## Для комдеров
Впринципе, ПР готов к тестам, но надо ещё мне будет посмотреть чексы спройтов и карты.

Множество рефакторов(ритуалы, руны, ещё чё-то), новые фреймворки, один с тг на временные визуальные эффекты, а другое для культа.
Баги и рантаймы, скорее всего, ещё будут во время ОБТ, потому что всё найти во время ЗБТ почти невозможно, тратит много времени и не всегда возможно. 

Так же, я понимаю что ревью в 202 файла на 8к добавлений и 4.5к удалений ОЧЕНЬ сложно, но я пытался некоторые вещи делать другими ПРами, которые изначально хотел сюда впихнуть, а некоторое всё равно пошло сюда, например фикс удаления худов у ливнувщих гостов, рефактор бимов с тг, иконки кишок для мап-едиторов, впринципе доработка альтернейт_апперансов(ещё одна) и многое другое. 

Этот ПР скорее всего будет конфликтовать со всеми возможными ТМами, поэтому ТМить нужно будет другие ПРы аккуратно(ну ведь не мержить же ЭТО в первый день, пусть люди побегают, потестят, поноют, я пофикшу и только тогда уже мерж)

## Почему и что этот ПР улучшит
Морально старый и неудобный режим станет красивым и понятным

## Авторство
Код: Я, ТГ, специальная квалифицированная команда профессиональных тестеров с секретного дикорд сервера.
Спруйты и FX-художники: DedYarick, Udav, ТГ, парадизы.
Левел-дизайн: Cheburek.
Ведущий звукоинженер: BiQndy.

## Чеинжлог
:cl: KIBORG, DedYarick, Udav, Cheburek, BiQndy, много тестеров
 - balance[link]: Реворк культа.
 - balance: Скелеты невоспреимчивы к химии и станам.
 - balance: Капеллан теперь в случаи неудачного деконверта очень сильно страдает, а сам деконверт не моментальный.
 - balance: Святая вода не деконвертит культистов, если те выбрали аспект Salutis.
 - tweak: Очки капеллана и божок видят членов своей религии.
 - ru: Множество переводов у всего, связанного с капелланом и культом.

2021-02-07 18:55 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2021-02-10 18:41 UTC, KIBORG04 reviewed
ацфацф

2021-02-12 13:05 UTC, T6751 commented
Конфликты
![image](https://user-images.githubusercontent.com/66636084/107771671-26c02200-6d4c-11eb-9f9b-250ba69eb658.png)

2021-02-12 13:10 UTC, KIBORG04 commented
> Конфликты
> ![image](https://user-images.githubusercontent.com/66636084/107771671-26c02200-6d4c-11eb-9f9b-250ba69eb658.png)

За 3 минуты пофиксил и прошелся гитхаб экшеноми

2021-02-17 10:22 UTC, T6751 reviewed
55/201

2021-02-17 10:22 UTC, T6751 commented on code/datums/atom_huds/alternate_apperance.dm
> +		if(!AA || !istype(AA, type))
```suggestion
		if(!istype(AA, type))
```

2021-02-17 10:22 UTC, T6751 commented on code/datums/atom_huds/alternate_apperance.dm
> +			continue
AA не может быть пустым здесь
```suggestion
	for(var/datum/atom_hud/alternate_appearance/AA in global.active_alternate_appearances)
```

2021-02-17 10:22 UTC, T6751 commented on code/datums/components/rites/spawn_item.dm
> +	if(L.len == 0)
```suggestion
	if(!L.len)
```

2021-02-17 10:22 UTC, T6751 commented on code/game/gamemodes/cult/narsie.dm
> +		notify_ghosts("Нар-си восстал в [A.name]. По всей станции скоро появятся его порталы, нажмимая на них, вы можете стать каким-то конструктом.")
```suggestion
		notify_ghosts("Нар-Cи восстал в [A.name]. По всей станции скоро появятся его порталы, нажав на которые, вы сможете стать конструктом.")
```

2021-02-17 10:22 UTC, T6751 commented on code/game/gamemodes/cult/cult_items.dm
> +	return FALSE
```suggestion
	return iscultist(M)
```

2021-02-17 10:22 UTC, T6751 commented on code/datums/atom_huds/atom_hud.dm
> +	huds[DATA_HUD_HOLY] = new/datum/atom_hud/holy
7-ую строку не нужно обновить?

2021-02-17 10:22 UTC, T6751 commented on code/datums/atom_huds/atom_hud.dm
> +	huds[DATA_HUD_HOLY] = new/datum/atom_hud/holy
DATA_HUD_HOLY и ANTAG_HUD_ALIEN_EMBRYO имеют одинаковые номера
И нужно обновить будет соответственно 7ю строку

2021-02-19 07:55 UTC, T6751 reviewed
122/201

2021-02-19 07:55 UTC, T6751 commented on code/datums/datumvars.dm
> +		var/mob/M = locate(href_list["give_religion"])
А действительно ли здесь нужен локейт?
```suggestion
		var/mob/M = href_list["give_religion"]
```

2021-02-19 07:55 UTC, T6751 commented on code/game/magic/Uristrunes.dm
>  		word_to_uristrune_table = list()
Можешь перенести word_to_uristrune_table в этот прок и сделать статической, пожалуста?
```
var/static/list/word_to_uristrune_table
if(!word_to_uristrune_table)
```

2021-02-19 07:55 UTC, T6751 commented on code/game/objects/effects/anomalies.dm
> +	while(candidates.len || spawns != 0)
Здесь, кажется, должно быть &&? Если кандидаты закончатся, а спавны останутся, то сейчас цикл продолжится и попытается выбрать слейва из пустого списка. Соответственно, не поэтому ли slave может быть null?

2021-02-19 08:06 UTC, KIBORG04 commented on code/modules/reagents/reagent_containers/food/drinks/bottle.dm
> +	list_reagents = list("water" = 100)
Я думаю, что не нужно давать святую воду капеллану раунд стартом, потому что он должен это делать аспекатми и там алхимией.

> бутылке святой воды теперь просто вода

Это жизнь, что в бутылки святой воды обычная вода

2021-02-19 08:07 UTC, KIBORG04 commented on code/modules/mob/mob.dm
> +	return QDEL_HINT_HARDDEL_NOW
Это я запутался в решение котфликтов

2021-02-19 08:08 UTC, KIBORG04 commented on code/modules/religion/religion_types/cult.dm
> +							"Н͆̈́͠У̔͊͝Ж̾͘͝Н͌̾́О̽͑̕ Б͒̔̿О͆̈́Л̈́̾̕Ь͒̒̈́Ш͐̔͝Е͋̓ Д́̚̚У͋͊́Ш̾̈́", "В͆̿̓О̐̿'̓͠͝Х͛̚Ѐ͠͝Д͒̓͒О͛͑К͋͊͛-͛̾̕Г̿̿̿Л̒̿͘У͑̒̓Т̓͐", "В̐͋̕О́͊͛'̐̀͘Х́̀͘А͊͘͘Д͒̓͆О͋̓К̓͊͝ Г̓͌͝Р́̓͘Ѝ͌̾Ш̈́̓.͊̐ С̽́О͊͛̽Л͘̕͝ И͑̔͝Ч̓̔А͋̾̚ О́̒́Ж
Мне гугл по запросу "зальгоизации" ничего не выдает

2021-02-19 08:08 UTC, KIBORG04 commented on code/datums/atom_huds/atom_hud.dm
> +	if (absolute || !--hudusers[M])
Это с тг просто скопировано, даже пробел после ифа учтен

2021-02-19 08:09 UTC, KIBORG04 commented on code/datums/mind.dm
> +	if(global.cult_religion.add_member(current, HOLY_ROLE_HIGHPRIEST))
Сделать отдельные ранги для культистов чтоли? Я просто так выделил, что культисты априори сильнее капеллановских новобранцев или равне по силе капеллану

2021-02-19 08:15 UTC, T6751 commented on code/modules/religion/religion_types/cult.dm
> +							"Н͆̈́͠У̔͊͝Ж̾͘͝Н͌̾́О̽͑̕ Б͒̔̿О͆̈́Л̈́̾̕Ь͒̒̈́Ш͐̔͝Е͋̓ Д́̚̚У͋͊́Ш̾̈́", "В͆̿̓О̐̿'̓͠͝Х͛̚Ѐ͠͝Д͒̓͒О͛͑К͋͊͛-͛̾̕Г̿̿̿Л̒̿͘У͑̒̓Т̓͐", "В̐͋̕О́͊͛'̐̀͘Х́̀͘А͊͘͘Д͒̓͆О͋̓К̓͊͝ Г̓͌͝Р́̓͘Ѝ͌̾Ш̈́̓.͊̐ С̽́О͊͛̽Л͘̕͝ И͑̔͝Ч̓̔А͋̾̚ О́̒́Ж
Зальго текст. Я нашёл некоторые js реализации, чтобы добавить зальго и наоборот убрать из его текста

https://github.com/casieber/zalgo-js
https://github.com/kdex/unzalgo

2021-02-19 08:17 UTC, T6751 commented on code/datums/mind.dm
> +	if(global.cult_religion.add_member(current, HOLY_ROLE_HIGHPRIEST))
Думаю можно просто сделать такой же дефайн для двоечки, только назвать иначе, подстать культистам, чтобы в случае чего можно было достаточно просто найти/заменить/исправить

2021-02-19 08:27 UTC, T6751 commented on code/modules/reagents/reagent_containers/food/drinks/bottle.dm
> +	list_reagents = list("water" = 100)
Думаю, что для священника это всё же будет неожиданно. Надо бы упомянуть об этом в чеинжлоге и изменить название и описание бутылки, как, например, "Holy Flask"

2021-02-19 08:45 UTC, KIBORG04 commented on code/datums/atom_huds/atom_hud.dm
> +	if (absolute || !--hudusers[M])
К слову, ты прав, я перепроверил код на тг

2021-02-19 09:12 UTC, KIBORG04 commented on code/modules/religion/religion_types/cult.dm
> +							"Н͆̈́͠У̔͊͝Ж̾͘͝Н͌̾́О̽͑̕ Б͒̔̿О͆̈́Л̈́̾̕Ь͒̒̈́Ш͐̔͝Е͋̓ Д́̚̚У͋͊́Ш̾̈́", "В͆̿̓О̐̿'̓͠͝Х͛̚Ѐ͠͝Д͒̓͒О͛͑К͋͊͛-͛̾̕Г̿̿̿Л̒̿͘У͑̒̓Т̓͐", "В̐͋̕О́͊͛'̐̀͘Х́̀͘А͊͘͘Д͒̓͆О͋̓К̓͊͝ Г̓͌͝Р́̓͘Ѝ͌̾Ш̈́̓.͊̐ С̽́О͊͛̽Л͘̕͝ И͑̔͝Ч̓̔А͋̾̚ О́̒́Ж
> UPD! Возможно в гунчате или тгчате можно было бы их внедрить, кстати.

Так у нас вроде уже сейчас гунчат или это что-то другое?

2021-02-19 09:16 UTC, T6751 commented on code/modules/religion/religion_types/cult.dm
> +							"Н͆̈́͠У̔͊͝Ж̾͘͝Н͌̾́О̽͑̕ Б͒̔̿О͆̈́Л̈́̾̕Ь͒̒̈́Ш͐̔͝Е͋̓ Д́̚̚У͋͊́Ш̾̈́", "В͆̿̓О̐̿'̓͠͝Х͛̚Ѐ͠͝Д͒̓͒О͛͑К͋͊͛-͛̾̕Г̿̿̿Л̒̿͘У͑̒̓Т̓͐", "В̐͋̕О́͊͛'̐̀͘Х́̀͘А͊͘͘Д͒̓͆О͋̓К̓͊͝ Г̓͌͝Р́̓͘Ѝ͌̾Ш̈́̓.͊̐ С̽́О͊͛̽Л͘̕͝ И͑̔͝Ч̓̔А͋̾̚ О́̒́Ж
Да, сейчас гунчат

2021-02-19 09:17 UTC, T6751 commented on code/modules/religion/religion_types/cult.dm
> +							"Н͆̈́͠У̔͊͝Ж̾͘͝Н͌̾́О̽͑̕ Б͒̔̿О͆̈́Л̈́̾̕Ь͒̒̈́Ш͐̔͝Е͋̓ Д́̚̚У͋͊́Ш̾̈́", "В͆̿̓О̐̿'̓͠͝Х͛̚Ѐ͠͝Д͒̓͒О͛͑К͋͊͛-͛̾̕Г̿̿̿Л̒̿͘У͑̒̓Т̓͐", "В̐͋̕О́͊͛'̐̀͘Х́̀͘А͊͘͘Д͒̓͆О͋̓К̓͊͝ Г̓͌͝Р́̓͘Ѝ͌̾Ш̈́̓.͊̐ С̽́О͊͛̽Л͘̕͝ И͑̔͝Ч̓̔А͋̾̚ О́̒́Ж
Просто тгчат возможно портировать когда-нибудь, поэтому упомянул

2021-02-24 09:56 UTC, KIBORG04 commented on code/modules/religion/religion_types/cult.dm
> +	var/blade_with_shield = FALSE
Может быть для всех исследований использовать не переменную, а битфлаги?

2021-02-24 21:06 UTC, LiLJard approved these changes

2021-03-05 21:47 UTC, KIBORG04 commented
когда?

2021-03-13 09:47 UTC, kalazus commented on code/modules/mob/living/living.dm
> +			if( C.handcuffed || istype(C.buckled, /obj/machinery/optable/torture_table))
Лишний пробел.
```suggestion
			if(C.handcuffed || istype(C.buckled, /obj/machinery/optable/torture_table))
```

2021-03-13 09:47 UTC, kalazus commented on code/modules/mob/living/simple_animal/shade.dm
> +	see_invisible = SEE_INVISIBLE_OBSERVER
Бесполезное переопределение.
```suggestion
	see_invisible = SEE_INVISIBLE_OBSERVER
```

2021-03-13 09:47 UTC, kalazus commented on code/modules/religion/tech.dm
> +		M.AddSpell(MR)
У новых культистов, вроде, не будет заклинания, а это не есть хорошо.

2021-03-13 09:50 UTC, KIBORG04 commented on code/modules/religion/tech.dm
> +		M.AddSpell(MR)
Я знаю, так и придумано

2021-03-13 19:17 UTC, KIBORG04 commented
Я устал ждать, завтра ~~мержу~~ ТМлю культ. @T6751 не против? Блин, хз еще кого спросить из важный шишек.

2021-03-14 01:21 UTC, T6751 commented
> Я устал ждать(и не только я), завтра мержу ТМлю культ. @T6751 не против? Блин, хз еще кого спросить из важный шишек.

Окей. Может во время ТМа уже просмотрю всё до конца.

2021-03-14 15:51 UTC, T6751 commented
Можешь исправить конфликты в спрайтах, пожалуста?

2021-03-14 15:52 UTC, KIBORG04 commented
ща

2021-03-14 16:46 UTC, AndroBetel commented
![image](https://user-images.githubusercontent.com/44546836/111076586-ed6f0380-84fd-11eb-89db-81c3f6a9f7fc.png)

2021-03-31 18:04 UTC, volas approved these changes
Выше пара незначительных комметриев, а так апрув. Как решить что готово - можешь мержить.

2021-03-31 18:06 UTC, volas commented on code/modules/religion/religion_types/cult.dm
> +							"Н͆̈́͠У̔͊͝Ж̾͘͝Н͌̾́О̽͑̕ Б͒̔̿О͆̈́Л̈́̾̕Ь͒̒̈́Ш͐̔͝Е͋̓ Д́̚̚У͋͊́Ш̾̈́", "В͆̿̓О̐̿'̓͠͝Х͛̚Ѐ͠͝Д͒̓͒О͛͑К͋͊͛-͛̾̕Г̿̿̿Л̒̿͘У͑̒̓Т̓͐", "В̐͋̕О́͊͛'̐̀͘Х́̀͘А͊͘͘Д͒̓͆О͋̓К̓͊͝ Г̓͌͝Р́̓͘Ѝ͌̾Ш̈́̓.͊̐ С̽́О͊͛̽Л͘̕͝ И͑̔͝Ч̓̔А͋̾̚ О́̒́Ж
Санитайзить ввод сложно и затратно, я пытался вставить затычку против грифа с переездом на 513, но другие вещи сломались https://github.com/TauCetiStation/TauCetiClassic/pull/5989

2021-03-31 18:09 UTC, KIBORG04 commented on code/datums/components/attack_self_effect.dm
> +	tip_name = SELF_TIP
Я посмотрел структуру этих подсказок, нужно будет в дестрое доделать и дефайн будет не только в одном месте использоваться

2021-03-31 18:19 UTC, KIBORG04 commented on code/datums/announcements/gamemode.dm
> +/datum/announcement/station/cult/capture_area/play(area/A)
Такое придумал перверт ниченезнаю

2021-03-31 19:53 UTC, volas commented on code/game/atoms.dm
> +			prev_key = K
Может, можно было бы удалять из списка в appearance/destroy, тут только вызывать qdel для них. Комментарий для затычки есть, кто нибудь потом проходя мимо может разобраться лучше.

2021-04-02 23:51 UTC, PirogSema requested changes

2021-04-02 23:51 UTC, PirogSema commented on code/game/gamemodes/cult/structures/tech_table.dm
> +		to_chat(user, "<span class='warning'>Сначало выберите аспекты.</span>")
```suggestion
		to_chat(user, "<span class='warning'>Сначала выберите аспекты.</span>")
```

2021-04-10 11:44 UTC, KIBORG04 commented
Хочу замержить культ седня ближе к вечеру, поэтому у вас последний шанс что-то поменять

2021-04-10 17:27 UTC, KIBORG04 commented
Последний шанс на реформы

2021-04-10 17:37 UTC, merged

2022-09-13 18:05 UTC, TauKitty commented
Этот запрос на слияние был упомянут в **Tau Ceti Station Forum**. Там могут быть соответствующие подробности:

https://forum.taucetistation.org/t/golosovanie-kak-vam-novyj-kult/35536/1