Аномалии теперь точно не будут рантаймить
TauCetiStation/TauCetiClassic pull request #6862
Opened 2021-02-13 09:38 UTC by KIBORG04

## Описание изменений
На свервере не видел рантайма, но он теоритически может быть, потому что в проке `findEventArea()` довольно не просто отделить все отсутствующие зоны в игре вообще. Например, есть какой-то непонятный `Cargo Breaktime Room`, который непонятно нахрен нужен в игре и почему создается.

<details> 
  <summary>Зоны на боксе</summary>
  
```
Space -
Vox Skipjack -
Abductor Ship -
Tophat -
Wizard's Den -
Emergency Shuttle Centcom -
Keelin's private beach -
Centcom Emergency Shuttle -
Thunderdome -
Thunderdome (Admin.) -
Thunderdome (Team 2) -
Thunderdome (Team 1) -
Centcomm -
Thunderdome (Observer.) -
Transport Shuttle Centcom -
Centcom Control -
Centcom Living Quarters -
Holding Facility -
Escape Pod Two -
Centcom -
Administration Shuttle Centcom -
Escape Pod One -
Centcom Special Ops -
Escape Pod Four -
Escape Pod Three -
Creed's Office -
Velocity Dock 42 -
Solitary Confinement -
NTS Velocity -
Special Ops Shuttle -
Tau Ceti Transfer Station 13 -
Alien base -
Alien Shuttle Base -
The start area -
The supply shuttle -
Space -
Syndicate Mothership -
Syndicate Forward Operating Base -
The hyperspace -
Syndicate Armory -
The hyperspace -
Syndicate Elite Shuttle -
Syndicate Elite Squad -
Drop pod garage -
Escape Pod Four -
Syndicate Control Room -
Emergency Shuttle Transit -
Escape Pod Three -
Officer Shuttle -
Escape Pod Two -
Escape Pod One -
Mining-Research Shuttle -
Asteroid Shuttle Hallway -
Arrival Shuttle Hallway -
Transport Shuttle -
NSS Exodus -
Administration Shuttle -
Special Ops Shuttle -
Entry Shuttles Hallway -
NSS Exodus -
Emergency Shuttle Station -
Cargo Office -
Waste Disposal -
The south-west of SS13 -
The north-west of SS13 -
Quartermaster's Office -
Vacant Office -
Cargo Bay -
Escape Shuttle Hallway -
Cargo Maintenance -
The supply shuttle -
Aft port solars -
Locker Room -
Aft Port Solar Array -
Security Checkpoint -
Fore port solars -
Mining office -
Escape Shuttle Maintenance -
Port Primary Hallway -
Hydroponics -
Auxiliary Tool Storage -
Primary Tool Storage -
Port Emergency Storage -
Recycleroffice -
Fore Port Solar Array -
Fitness Room -
Holodeck Alpha -
Aft Port Solar Maintenance -
Kitchen -
Cold Room -
Incinerator -
Play Room -
Engineering Maintenance -
Escape Pod Four -
Bar -
Recycler -
EVA Maintenance -
Theatre -
Gateway -
Drone Fabrication -
Fore Port Solar Maintenance -
Barbershop -
Central Primary Hallway -
Forensic's Office -
Engineering -
The north of SS13 -
Brig -
Medical Checkpoint -
EVA Storage -
Execution -
Fore Primary Hallway -
Heads of Staff Meeting Room -
Bridge Maintenance -
Assembly Line -
Head of Personnel's Office -
Technical Storage -
Bridge -
Singularity Area -
Internal Affairs -
Construction Area -
Firing Range -
Armory -
Detective's Office -
Warden -
AI Upload Chamber -
Messaging Server Room -
Chief Engineer's office -
Vault -
Aft Primary Hallway -
Security lobby -
Dormitory Maintenance -
Cyborg Station -
Custodial Closet -
Atmospherics Maintenance -
Engineering Break Room -
Atmospherics -
Security Office -
Prison Wing -
Dormitories -
Female Dorm -
Male Dorm -
Captain's Office -
Teleporter -
Head of Security's Office -
Gym -
Dormitory Toilets -
The south of SS13 -
Science Maintenance -
Research and Development -
Chemistry -
Medbay -
Medbay Storage -
Starboard Primary Hallway -
Science Breaktime Room -
Research Division -
Operating Theatre 2 -
Escape Pod Three -
Brainstorm Center -
Medbay Reception -
Emergency Treatment Centre -
Cryogenics -
Operating Theatre 1 -
Operation Observation Room -
AI Satellite Exterior -
Toxins Storage -
Research Director's Office -
Robotics Lab -
Virology -
Syndicate Elite Shuttle -
Toxins Test Site -
Medbay Maintenance -
AI Satellite -
AI Satellite Teleporter Room -
Toxins Launch Roon -
Toxins Mixing Room -
Patient Room Two -
Chief Medical Officer's office -
Psych Room -
Genetics Lab -
Cloning Lab -
Server Room -
Mech Bay -
AI Chamber -
Telecoms Central Compartment -
Patient Room One -
Telecoms Control Room -
AI Satellite Antechamber -
Patient's Rooms -
Xenobiology Lab -
Morgue -
Telescience Lab -
Medbay Breaktime Room -
Secure Storage -
Fore starboard solars -
Miscellaneous Research -
Chapel Maintenance -
Starboard Emergency Storage -
Library -
Central Emergency Storage -
Chapel -
Crematorium -
Chapel Office -
The south-east of SS13 -
Garden -
Fore Starboard Solar Array -
Chapel Mass Driver -
Altar -
Aft Starboard Solar Array -
North Technical Storage -
Fore Starboard Solar Maintenance -
Aft Starboard Solar Maintenance -
The north-east of SS13 -
Escape Pod Two -
Escape Pod One -
Aft starboard solars -
Mining-Research Shuttle -
Mine -
Mine -
West Mining Outpost -
Abandoned Mining Station -
Alien Shuttle Mine -
Dwarf -
Mining Station Port Wing -
Mining Station Communications -
Mining-Research Shuttle -
Research Outpost Shuttle Dock -
Expedition Preparation -
Mass Spectrometry Lab -
Research Outpost Hallway -
Research Outpost Medbay -
Temporary Storage -
Mining Station Starboard Wing -
Mining-Research Shuttle -
Auxiliary Storage -
Sample Preparation Room -
Research Outpost Maintenance -
Anomalous Materials Lab -
Isolation Cell -
Nearby mining asteroid -
Exotic Particles Collection -
Mining Station EVA -
Research Outpost Atmospherics -
Research Outpost Power -
Isolation Cell -
Maintenance Storage -
Long-Term Storage -
Outpost Miscellaneous Research -
The north east of the mining asteroid -
Junkyard -
Artifact Room #1141366 -
Artifact Room #1141366 -
Artifact Room #1141366 -
Artifact Room #1141366 -
Artifact Room #1141366 -
Artifact Room #1141366 -
Artifact Room #1141366 -
Artifact Room #1141366 -
Artifact Room #1141366 -
Artifact Room #1141366 -
Artifact Room #1141366 -
Artifact Room #1141366 -
Artifact Room #1141366 -
Artifact Room #1141366 -
Artifact Room #1141366 -
Artifact Room #1141366 -
Artifact Room #1141366 -
Artifact Room #1141366 -
Artifact Room #1141366 -
Artifact Room #1141366 -
Artifact Room #1141366 -
Artifact Room #1141366 -
Artifact Room #1141366 -
Artifact Room #1141366 -
Artifact Room #1141366 -
Artifact Room #1991166 -
Artifact Room #1991166 -
Artifact Room #1991166 -
Artifact Room #1991166 -
Artifact Room #1991166 -
Artifact Room #1991166 -
Artifact Room #1991166 -
Artifact Room #1991166 -
Artifact Room #1991166 -
Artifact Room #1991166 -
Artifact Room #1991166 -
Artifact Room #1991166 -
Artifact Room #1991166 -
Artifact Room #1991166 -
Artifact Room #1991166 -
Artifact Room #1991166 -
Artifact Room #1991166 -
Artifact Room #1991166 -
Artifact Room #1991166 -
Artifact Room #1991166 -
Artifact Room #1991166 -
Artifact Room #1991166 -
Artifact Room #1991166 -
Artifact Room #1991166 -
Artifact Room #1991166 -
Artifact Room #991606 -
Artifact Room #991606 -
Artifact Room #991606 -
Artifact Room #991606 -
Artifact Room #991606 -
Artifact Room #991606 -
Artifact Room #991606 -
Artifact Room #991606 -
Artifact Room #991606 -
Artifact Room #991606 -
Artifact Room #991606 -
Artifact Room #991606 -
Artifact Room #991606 -
Artifact Room #991606 -
Artifact Room #991606 -
Artifact Room #991606 -
Artifact Room #991606 -
Artifact Room #991606 -
Artifact Room #991606 -
Artifact Room #991606 -
Artifact Room #991606 -
Artifact Room #991606 -
Artifact Room #991606 -
Artifact Room #991606 -
Artifact Room #991606 -
Planetarium -
Robostation -
Ghost Ship -
Derelict Teleporter -
Abandoned Lab -
Security Conference Hall -
Medbay -
Operating Storage -
Space Pod Construction Site -
Cargo Breaktime Room -
```

</details>

<details> 
  <summary>Возможные зоны для спавна аномалии</summary>
  
```
Asteroid Shuttle Hallway -
Arrival Shuttle Hallway -
Entry Shuttles Hallway -
Cargo Office -
Waste Disposal -
Quartermaster's Office -
Vacant Office -
Cargo Bay -
Escape Shuttle Hallway -
Cargo Maintenance -
Locker Room -
Security Checkpoint -
Mining office -
Escape Shuttle Maintenance -
Port Primary Hallway -
Hydroponics -
Auxiliary Tool Storage -
Primary Tool Storage -
Port Emergency Storage -
Recycleroffice -
Fitness Room -
Aft Port Solar Maintenance -
Kitchen -
Cold Room -
In [...]

2021-02-13 09:38 UTC, TauKitty commented
###### Changelog status: :radio_button: No changelog

2021-02-13 09:40 UTC, KIBORG04 commented
Как вариант, можно удалить не юзабельные зоны в игре, но я не хочу их искать и тратить время на это

2021-02-16 00:51 UTC, T6751 commented
Стоит разобраться в причине когда и почему появляются такие зоны, чем решать симптомы

После инициализации по каким-то причинам добавляется 5 зон
```
Cargo Breaktime Room
Medbay
Operating Storage
Security Conference Hall
Space Pod Construction Site
```

Рекомендую посмотреть прок color_windows_init()
```
[03:43:47] Runtime in unsorted.dm, line 1483: Incorrect Area Spawned, oof
proc name: stack trace (/proc/stack_trace)
src: null
call stack:
stack trace("Incorrect Area Spawned, oof")
Cargo Breaktime Room (/area/station/cargo/miningbreaktime): New()
color windows init()
Atoms (/datum/controller/subsystem/atoms): Initialize(25997)
Master (/datum/controller/master): Initialize(null, null)
```

2021-02-16 06:57 UTC, KIBORG04 commented
Может я их просто удалю?

2021-02-16 07:00 UTC, T6751 commented
> Может я их просто удалю?

А если какая-то зона использоваться на гамме, но при этом будет добавляться на коробке?

2021-02-16 09:09 UTC, volas requested changes

2021-02-16 09:09 UTC, volas commented on code/modules/events/anomaly.dm
> +		impact_area = findEventArea()
~~Судя по ``findEventArea()``, он подразумевает возможность вернуть null, и это его обычный режим работы. Более того, если он вернул null однажды, он скорее всего вернет его же в любой другой раз. Подобная обработка в цикле, дергать пока он не заработает так, как мы хотим, не совсем корректна.~~

Похоже, что ``findEventArea()`` уже фильтрует именно существующие в игре зоны
https://github.com/TauCetiStation/TauCetiClassic/blob/47afb51a3ff5d166de18893eda16b9bb3260d340/code/modules/events/anomaly.dm#L58

2021-02-16 09:19 UTC, KIBORG04 commented on code/modules/events/anomaly.dm
> +		impact_area = findEventArea()
Сам баг в том, что несколько зон попадают в существующие зоны, но при этом в игре их по факту нету

2021-02-16 10:04 UTC, volas commented on code/modules/events/anomaly.dm
> +		impact_area = findEventArea()
У них вызывается ``New()``, или они существуют в world? На tg разница в том, что они используют sortedAreas, который в отличии от all_areas у нас, заполняемого при ``New()``, обновляется в ручную как
```
	for(var/area/A in world)
		GLOB.sortedAreas.Add(A)
```

А вообще было бы интересно разобраться, откуда они создаются.

2021-02-16 10:05 UTC, KIBORG04 commented on code/modules/events/anomaly.dm
> +		impact_area = findEventArea()
У нас вызывается нью.
Создаются при locate(type) в проке, который тильда кидал

2021-02-16 10:16 UTC, volas commented on code/modules/events/anomaly.dm
> +		impact_area = findEventArea()
Именно при ``locate``, или в цикле типо как тут ``for(var/A in wsRedList)``? :thinking: 

И если просто вызывается New(), то возможно в world зона не попадает и можно попробовать сделать как на tg.

2021-02-16 10:27 UTC, KIBORG04 commented on code/modules/events/anomaly.dm
> +		impact_area = findEventArea()
Поидее, при 'for(var/i in locate(type))'.

2021-02-16 15:32 UTC, T6751 commented on code/game/objects/structures/windows-colored.dm
>  		wcCommon = pick(common)
Можно также переделать глобал в статик, т.к. переменная wcCommon используется только в этом проке

```
	var/static/wcCommon
	if(!wcCommon)
		var/list/common = list("#379963", "#0d8395", "#58b5c3", "#49e46e", "#8fcf44", "#cc99ff", "#ff6600", "#3399ff", "#969696", "#ffffff")
		wcCommon = pick(common)
```

2021-02-16 15:32 UTC, T6751 commented on code/__HELPERS/game.dm
> +			return A
А почему сразу не использовать ```locate(type) in all_areas``` ? Или даже так будет создаваться зона?

2021-02-17 08:04 UTC, volas approved these changes

2021-02-17 08:05 UTC, volas commented
Есть желание попробовать зарепортить баг с locate(area), где area не существует?

2021-02-17 08:23 UTC, T6751 commented on code/__HELPERS/game.dm
> +	return null
```suggestion
	return A
```

2021-02-17 08:45 UTC, KIBORG04 commented on code/__HELPERS/game.dm
> +	return null
Может тогда просто до `return locate(type) in all_areas`

2021-02-17 08:45 UTC, KIBORG04 commented
> Есть желание попробовать зарепортить баг с locate(area), где area не существует?

Надо будет спросить в кодерском дискорде нормально это или нет

2021-02-17 08:53 UTC, T6751 commented on code/__HELPERS/game.dm
> +	return null
Можно. И думаю стоит ещё переименовать прок как get_area_by_type

2021-02-17 09:17 UTC, T6751 approved these changes

2021-02-18 05:01 UTC, T6751 commented
Люммокс написал, что это не баг, кстати
http://www.byond.com/forum/post/2656070

2021-02-18 05:01 UTC, merged

2021-02-18 08:50 UTC, volas commented
> Люммокс написал, что это не баг, кстати

Undocumented Byond feature №4802