респрайт аптечек и содержимого
TauCetiStation/TauCetiClassic pull request #6887
Opened 2021-02-24 13:55 UTC by AndroBetel

## Описание изменений
![image](https://user-images.githubusercontent.com/44546836/109010432-cffa0700-76c0-11eb-87d9-0ac66e0e56d0.png)
респрайтит аптечки, бинтики, мазьку, улучшенные бинтики и мазьку, шины, а так же медботов, которых теперь можно делать из разных аптечек и они будут по разному покрашены. 
к несчастью улучшенные бинты и мазь потеряли визуальное отображение кол-ва в стаке.
## Почему и что этот ПР улучшит
красота
## Авторство
@LiJard @LiLJard @Ajajumbo123 
## Чеинжлог
:cl:
- bugfix: Теперь медботы будут цвета той аптечки, из которой были сделаны.
- image: Респрайтит аптечки, их содержимое и медботов.

2021-02-24 13:55 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2021-02-24 14:02 UTC, FelixRuin commented on code/game/objects/items/stacks/medical.dm
> -
предлагаю хоть тогда ввести в чейнжлог, что 
del: визуальное определение количества зарядов у adv trauma kit и burn kit

2021-02-24 14:02 UTC, AndroBetel commented on code/game/objects/items/stacks/medical.dm
> -
что же тебя блять так порвало с этого

2021-02-24 14:04 UTC, FelixRuin commented on code/game/objects/items/stacks/medical.dm
> -
убираешь - предупреждай, не более. Или тебе даже 1 строку в пре написать не хочется?

2021-02-24 14:06 UTC, AndroBetel commented on code/game/objects/items/stacks/medical.dm
> -
я не согласен с тем что игроку нужно засорять чейнжлог бесполезной информацией, которую он может увидеть просто взглянув на спрайт измененный (что подразумевает собой пункт о том что спрайты изменились).

2021-02-24 17:36 UTC, Motzord commented
Аптечки красивые, не нравится потеря отображение количества в стаке.

2021-02-24 17:40 UTC, KIBORG04 commented
[Баг диффоф?](https://camo.githubusercontent.com/42d7d3a7adb848edb6d25fedab51c75cca6d9a5485681374351bf7df2b5112f2/68747470733a2f2f6964622e616666656374656461726330372e636f2e756b2f46696c65732f35353837303434322f313937303634363037352f3133342f61667465722e676966)

Стелсовыпил
![image](https://user-images.githubusercontent.com/26389417/109041787-7570a300-76e0-11eb-97ce-7aa56a5352a1.png)

и еще стелс
![image](https://user-images.githubusercontent.com/26389417/109041823-81f4fb80-76e0-11eb-8a1a-81cf99d59562.png)

Блин, сложно дифы прочекать так?

2021-02-24 18:01 UTC, AndroBetel commented
а, забыл упомянуть, что ещё и из файлов удалил ненужный хлам оставшийся со времен бронтозавров

2021-02-24 18:05 UTC, UsadoSmokk commented
Но гирбелт и утилити нужны... А также у нас в коде есть вещи, которые берут эти спрайты

2021-02-24 18:05 UTC, KIBORG04 commented
милитари белт тоже юзается

2021-02-24 18:09 UTC, AndroBetel commented
ты говоришь про то что я не смотрю в диффы а это дифф для belt_mirror который юзается для вещей висящих в слоте костюма. ты сможешь положить гирбелт или милитари белт (у которого в диффе вообще старый спрайт) в слот для баллона или повесить на броник?

2021-02-24 18:12 UTC, KIBORG04 commented
Ты не писал про удаление старых спрайтов, поэтому у меня и припекло. Не важно.
Ну, если так надо и все работает, то ладно

2021-02-24 18:14 UTC, AndroBetel commented
ничего друг я и правда ошибся забыл написать! =) замержи пожалуйста у меня горят дела

2021-02-24 18:15 UTC, KIBORG04 commented
ПРу 4 часа, еще рано. Плюс не было аппрува от спройтеров(хех)

2021-02-24 18:33 UTC, LiLJard approved these changes

2021-02-25 10:08 UTC, UDaV73rus requested changes
Механ стаков остался, а их спрайтов нет. Нет ни одной причины почему это так должно быть, и почему это лучше чем сейчас. В этом случае прикрытия в стиле "мне похуй" выглядят тупо
Нужно либо доделать спрайты, либо докодить удаление

2021-02-25 10:18 UTC, AndroBetel commented
что значит "механ стаков остался"? такой механ стаков без отображения на спрайте есть у стекла, у слитков, у сплинтов и еще у чего-то. что ты подразумеваешь под удалением механа?

2021-02-25 10:37 UTC, UsadoSmokk commented
> что значит "механ стаков остался"? такой механ стаков без отображения на спрайте есть у стекла, у слитков, у сплинтов и еще у чего-то. что ты подразумеваешь под удалением механа?

Мне кажется Удав про механ обновления спрайта при изменении количества в стаке. А не про механ стака в целом

2021-02-27 15:00 UTC, AndroBetel commented
![image](https://user-images.githubusercontent.com/44546836/109390946-9fff6d80-7925-11eb-9c49-fcc4ce027b1f.png)
добавили стейты к улучшенным бинтикам

2021-02-27 15:42 UTC, UDaV73rus commented
![image](https://user-images.githubusercontent.com/33157992/109391345-a0006d00-7927-11eb-85b6-82d40b60fc90.png)
Мужик сказал - мужик сделал

*сравнение*
![image](https://user-images.githubusercontent.com/33157992/109391316-7f381780-7927-11eb-9c2e-867380af6865.png)
нужно сделать более читабельными, чем черный пиксель / темно-зеленый пиксель

2021-02-28 09:48 UTC, TungstenOctopus approved these changes

2021-02-28 10:10 UTC, KIBORG04 commented
![image](https://user-images.githubusercontent.com/26389417/109414845-5024b300-79c6-11eb-85ec-a4f19ae5c27e.png)

Жду апрува удава

2021-02-28 10:38 UTC, UDaV73rus commented
Юлиан тоже писал что нужно исправить, но внезапно апрув без комментариев

2021-02-28 12:49 UTC, TungstenOctopus commented
Было замечание о механике стаков, она снова есть на спрайтах, причём в таком же исполнении, считаю вопрос исчерпанным

2021-03-02 08:14 UTC, merged