Лобби-кнопки и скрин на хтмле
TauCetiStation/TauCetiClassic pull request #6901
Opened 2021-02-28 19:34 UTC by KIBORG04

## Описание изменений
Этот ПР - взятие https://github.com/TauCetiStation/TauCetiClassic/pull/6183 ПРа тильды, но с добавлением кнопок на этот экран, вместо того окошка. 

Первое, что бросится в глаза, так это то что гифка и, мб, срин моргнет при нажатии реди, потому что её нажатие пересобирает хтмлку.

https://user-images.githubusercontent.com/26389417/109430775-05318c80-7a14-11eb-8ff8-eb95ccd4dff9.mp4

![image](https://user-images.githubusercontent.com/26389417/109430902-a587b100-7a14-11eb-91f4-163246144df9.png)

## Почему и что этот ПР улучшит
21й век, красивый тайтл скрин, не будет видно пакеты еще до входа в игру

## Авторство
Основа этого ПРа - @T6751
Обновленная вёрстка @Dominig12 
Код, чтобы лобби-кнопки работали - @KIBORG04 

## Чеинжлог
:cl: KIBORG04, DarkWater, T6751
 - tweak: Админам во вкладку FUN добавлена кнопка Change Title Screen для смены заставки в лобби.
 - tweak: Начальные кнопки при входе в игру теперь прямо на заставке.

2021-02-28 19:34 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2021-02-28 19:37 UTC, SpaiR commented
Вы что, делаете ССку похожей на настоящую игру??!!

2021-02-28 19:51 UTC, UDaV73rus commented
В настоящей игре есть кнопка выхода... а здесь игрок обречен . . .

2021-03-01 01:07 UTC, volas approved these changes

2021-03-01 01:07 UTC, volas commented on code/modules/mob/dead/new_player/lobby.dm
> +		</script>
Интерактивные элементы и в целом обновление (что бы гифки не моргали) можно было бы сделать со стороны сервера, через вызов js с ``proc/output``, а на сервер все нужные ивенты отсылать топиками
http://www.byond.com/docs/ref/info.html#/proc/output (еще гунчат как пример)

Сейчас тут, например, возможен рассинхрон, если мы ready изменим где-то на стороне сервера.

Опционально, можно в следующей итерации.

2021-03-01 01:07 UTC, volas commented on code/modules/mob/dead/new_player/login.dm
> +	show_titlescreen()
```suggestion
	show_titlescreen()
	playsound_lobbymusic()
```
лишнее?

2021-03-01 01:07 UTC, volas commented on code/modules/asset_cache/asset_list_items.dm
> +		"ready_ok.png" = 'icons/lobby/ready_ok.png',
как Спейр уже сказал в дискорде, нету смысла делать их картинками, это только во вред, но можно опять же оставить до следующей итерации, не критично

2021-03-01 01:07 UTC, volas commented on code/modules/mob/dead/new_player/lobby.dm
> +				margin-right: 100%;
```suggestion
```
не очень понимаю margin тут, еще возможно стоит добавить
```suggestion
				display: block;
```
тут и ссылкам

2021-03-01 01:08 UTC, volas requested changes
^

2021-03-01 09:19 UTC, KIBORG04 commented on code/modules/mob/dead/new_player/lobby.dm
> +			}
В этом же и фича, не?

2021-03-01 09:54 UTC, volas commented on code/modules/mob/dead/new_player/lobby.dm
> +			}
рамка ок, но они не должны прыгать, как у тебя в видео

2021-03-01 15:31 UTC, KIBORG04 commented
Передаю эстафету @Dominig12

2021-03-02 04:20 UTC, Rolt146 commented
А эти кнопки будут видны призракам? Не смогут ли призраки их прожать прикола ради?

2021-03-02 06:46 UTC, KIBORG04 commented
Не сможет нажать, так как даже не увидит

2021-03-07 11:17 UTC, volas commented on code/modules/mob/dead/new_player/lobby.dm
> +					min-height: 100vmin;
мне не очень нравится использование vmin, кажется оно тут излишне и где нибудь с ie могу всплыть косяки, но если оно работает то ладно

2021-03-07 11:29 UTC, Dominig12 commented on code/modules/mob/dead/new_player/lobby.dm
> +					min-height: 100vmin;
ну, я скидывал видео работы, и оно работает хорошо
https://youtu.be/ZXbUNbig3L4

2021-03-07 11:36 UTC, volas requested changes

2021-03-07 11:36 UTC, volas commented on code/controllers/subsystem/mapping.dm
> +/datum/controller/subsystem/mapping/proc/change_lobbyscreen()
нету причин держать функцию в контроллере карты

2021-03-07 11:36 UTC, volas commented on code/modules/admin/admin_verbs.dm
> +	global.current_lobby_screen = file
странно напрямую менять картинку, когда вроде-как есть функция отвечающая за это ``change_lobbyscreen``. Можешь добавить аргумент туда и вызывать её

2021-03-07 11:36 UTC, volas commented on code/modules/admin/admin_verbs.dm
> +	set category = "Fun"
И еще вариант, что бы не плодить много кнопок, можно было бы reset оставить как дефолтный выбор в ``change_title_screen``.

2021-03-07 11:36 UTC, volas commented on code/modules/mob/dead/new_player/new_player.dm
>  			ready = !ready
нужно добавить обновление фронта в других местах тоже, как минимум есть
https://github.com/TauCetiStation/TauCetiClassic/blob/8bd62fb0fce0270d21deec82318c9ec263946b1c/code/controllers/subsystem/jobs.dm#L362

2021-03-07 11:40 UTC, KIBORG04 commented on code/modules/admin/admin_verbs.dm
> +	set category = "Fun"
`var/file = input(usr) as icon|null`

Там же выбор файлов и нету какого-то дефолтного выбора.
А оставлять это действие только при выборе отмены файла неочевидно

2021-03-07 11:41 UTC, KIBORG04 commented on code/controllers/subsystem/mapping.dm
> +/datum/controller/subsystem/mapping/proc/change_lobbyscreen()
А где? Глобально?

2021-03-07 11:42 UTC, volas commented on code/modules/admin/admin_verbs.dm
> +	set category = "Fun"
можно добавить алерт с выбором, но это не критично и если будет желание

2021-03-07 11:47 UTC, volas commented on code/controllers/subsystem/mapping.dm
> +/datum/controller/subsystem/mapping/proc/change_lobbyscreen()
Можно world, ну или глобально тоже сойдет. Можно в ticker, там уже какие-то лобби штуки есть.

2021-03-07 16:44 UTC, volas approved these changes

2021-03-07 18:07 UTC, merged

2021-07-08 15:48 UTC, KIBORG04 commented
нифига мы крутые, ждите скоро на всех серверах сски

2021-07-11 20:09 UTC, quardbreak commented
@KIBORG04 Спасибо! Я давно хотел портировать, но из-за своих лимитированных знаний css и js не мог сделать это несколько месяцев назад. Теперь я разобрался и очень доволен что благодаря вашей имплементации кнопок можно было сделать апбгрейд :)

2026-03-17 10:39 UTC, KIBORG04 commented
Я удивлен, что ТГ не перешло на ХТМЛ, а все еще использует бьондомехан