Рефактор идиотского поведения у /proc/auto_declare_completion_[mode]()
TauCetiStation/TauCetiClassic pull request #6907
Opened 2021-03-01 18:45 UTC by KIBORG04

## Описание изменений
Убрал идиотское поведение у проков, сделав ООП.

Так же, теперь это прок-обертка, чтобы уменьшить количество копипасты одного и того-же

## Почему и что этот ПР улучшит
QoL for Coders

## Авторство

## Чеинжлог

2021-03-01 18:45 UTC, TauKitty commented
###### Changelog status: :radio_button: No changelog

2021-03-02 02:09 UTC, volas requested changes

2021-03-02 02:09 UTC, volas commented on code/controllers/subsystem/ticker.dm
> +	ai_completions += mode.auto_declare_completion()
В прошлом варианте вызывался для каждого мода, т.к. в раунде могут присутствовать антагонисты разных типов. Если будет вызываться только текущий - эта информация потеряется, а некоторые режимы скорее всего совсем перестанут выводить итоги, автотриторы в той же эксте.

2021-03-02 06:52 UTC, KIBORG04 commented on code/controllers/subsystem/ticker.dm
> +	ai_completions += mode.auto_declare_completion()
Действительно, раньше эта штука имела смысл, ну ладно.

Можно попробовать через тайпоф создавать датумы геймодов и вызывать вот этот ауто_декларе_комплитишен.

2021-03-02 09:31 UTC, volas commented on code/controllers/subsystem/ticker.dm
> +	ai_completions += mode.auto_declare_completion()
Можешь не останавливаться на датумах, #4434 :wink: 

имхо по кусочкам тут ковырять может и не стоит, больше шанс что нибудь сломать чем сделать лучше

2021-03-02 09:34 UTC, KIBORG04 commented on code/controllers/subsystem/ticker.dm
> +	ai_completions += mode.auto_declare_completion()
Не, ну если это упростит создание хаба со статистикой, то почему нет

2021-03-04 22:20 UTC, KIBORG04 commented
Наверное, все же, я лучше в рефакторинге гейм_модов закодю это.

2021-03-04 22:20 UTC, closed without merging