Fixes #6861 + перевод
TauCetiStation/TauCetiClassic pull request #6912
Opened 2021-03-06 20:24 UTC by Zickusable

## Описание изменений
Нельзя alt или ctrl взаимодействовать с крио, если ты внутри.
Перевод сообщений из этого файлика
## Почему и что этот ПР улучшит
Перевод, багфикс
## Авторство

## Чеинжлог
:cl:
- bugfix: Больше нельзя с помощью alt или ctrl взаимодействовать с крио, если ты внутри.
- spellcheck: Перевод сообщений при взаимодействии с крио

2021-03-06 20:24 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2021-03-06 20:25 UTC, KIBORG04 commented
не пиши тэги, типа `Fixes #6861` в название коммита, пиши их в теле описания ПРа

2021-03-06 20:26 UTC, KIBORG04 commented
> spellcheck: Перевод сообщений при взаимодействии с крио

Есть тэг ru, поставь его вместо спелчека

2021-03-06 20:29 UTC, KIBORG04 commented on code/modules/atmospheric/machinery/components/unary_devices/cryo.dm
> +			"[user] помещает мерный стакан в криогенную камеру.",
```suggestion
			"[user] помещает[i] в [src].",
```
Сделай так, ведь название стакана и камеры может отличаться от предмета. Да, будет очень криво, но тогда лучше впринципе это пока не трогать

2021-03-06 20:29 UTC, KIBORG04 commented on code/modules/atmospheric/machinery/components/unary_devices/cryo.dm
> +			"<span class='notice'>Вы помещаете мерный стакан в криогенную камеру.</span>")
Тут тоже самое

2021-03-06 20:33 UTC, KIBORG04 commented on code/modules/atmospheric/machinery/components/unary_devices/cryo.dm
> +	if(user == occupant || (user.stat && !isobserver(user)))
Здесь и в подобной штуке выше не нужно  (user.stat && !isobserver(user). Призраки отрезаются еще в `IsAdvancedToolUser
()`, а  `user.stat ` отсекается ниже в `incapacitated()`

2021-03-06 20:35 UTC, KIBORG04 commented on code/modules/atmospheric/machinery/components/unary_devices/cryo.dm
> +		to_chat(user, "[src] выглядит пустым.")
```suggestion
		to_chat(user, "[src] выглядит пустой.")
```
Ты везде используешь `криогенную камеру`, а значит это женский род

2021-03-06 20:52 UTC, Zickusable commented on code/modules/atmospheric/machinery/components/unary_devices/cryo.dm
> +			"[user] помещает мерный стакан в криогенную камеру.",
В Beaker входят: сами мензурки, склянки(вирусолога) и чайник (!). Так что можно заменить **мерный стакан** на **сосуд**, а название камеры может поменяться разве что от labeler, но таким переименовыванием вещей занимаюсь только я и еще один чувак.

2021-03-06 20:57 UTC, KIBORG04 commented on code/modules/atmospheric/machinery/components/unary_devices/cryo.dm
> +			"[user] помещает мерный стакан в криогенную камеру.",
ну вот лучше сосуд вставь

2021-03-06 20:58 UTC, AndroBetel commented on code/modules/atmospheric/machinery/components/unary_devices/cryo.dm
> +			"[user] помещает мерный стакан в криогенную камеру.",
вкину тезис:
на лайфвебе, который переведён практически полностью да ещё и так, что это выглядит гармонично, в таких вот частных случаях как раз таки используют не [src], а просто дописывают лог, чтобы было красиво. мне кажется, что это и есть правильно.

2021-03-10 11:31 UTC, Akellazp commented
закидывание в крио это инста-вин механика одним нажатием. почему тогда жертва не должна иметь возможность выйти оттуда одним нажатием?
с чего вы вообще взяли что это баг?

2021-03-10 14:46 UTC, Zickusable commented
> закидывание в крио это инста-вин механика одним нажатием. почему тогда жертва не должна иметь возможность выйти оттуда одним нажатием?
> с чего вы вообще взяли что это баг?

https://www.youtube.com/watch?v=f1-Auntsito
Ну конечно баг, иначе можно было бы моментально вылезти и резистом

2021-03-10 18:48 UTC, Zickusable commented
> Видео это вообще ничего не доказывает
> Если выпиливаешь возможность мгновенно выбраться из крио то сделай задержку на закидывание людей в крио, чтобы небыло имбо механики

Такая же имбомеханика, как и операционный стол, как и станперчатки, дубинки. Главное сократить дистанцию и иметь руки из нужного места. Суть ПРа не в балансе, а в выборе варианта между мгновенным выпрыгиванием и долгим.  Понятно на что пал мой выбор. Мб я просто ни разу не видел эпичные зарубы в медбее, где побеждает тот, кто первый добежит до крио.

2021-03-10 18:51 UTC, Akellazp commented
Убирая одну "проблему" ты создаешь другую.
Либо убирай и ее, либо изначально ничего не делай

2021-05-10 16:31 UTC, KIBORG04 commented
А вот если бы это были два пра: фикс бага и перевод крио, то багфикс был бы уже давно замержен

2021-05-28 07:03 UTC, BesumniiChebureck commented on code/modules/atmospheric/machinery/components/unary_devices/cryo.dm
> +			to_chat(user, "Кто-то внутри криогенной камеры!")
```suggestion
			to_chat(user, "Кто-то внутри криокамеры!")
```

2021-05-28 07:15 UTC, BesumniiChebureck commented on code/modules/atmospheric/machinery/components/unary_devices/cryo.dm
> +		to_chat(user, "<span class='warning'>Вы без понятия что с этим делать.</span>")
```suggestion
		to_chat(user, "<span class='warning'>Вы не можете понять, что с этим делать.</span>")
```
Если всё таки народ/транс деп думает что ``без понятия`` тут лучше (хотя тогда было бы no idea), то перед ``что`` всеровно нужна запятая.

2021-05-28 07:20 UTC, BesumniiChebureck commented on code/modules/atmospheric/machinery/components/unary_devices/cryo.dm
> +		to_chat(user, "<span class='warning'>Вы без понятия что с этим делать.</span>")
```suggestion
		to_chat(user, "<span class='warning'>Вы не можете понять, что с этим делать.</span>")
```

2021-05-28 07:25 UTC, BesumniiChebureck commented on code/modules/atmospheric/machinery/components/unary_devices/cryo.dm
> +			"[user] помещает сосуд в криогенную камеру.",
```suggestion
			"[user] помещает [I] в криокамеру.",
```
Под I, как я понимаю, подразумевается название сосуда, а оно может быть и например ``Beaker of Antitoxin``. Так что мне кажется тут стоит оставить I, даже если в чате будет:
``Carlos Allen помещает Beaker of Antitoxin в криокамеру``

2021-05-28 17:16 UTC, Zickusable commented on code/modules/atmospheric/machinery/components/unary_devices/cryo.dm
> +	to_chat(user, "<span class='notice'>Вы стараетесь изо всех сил выбраться из капсулы, упираясь ногами... (Потребуется около 30 секунд.)</span>")
Пропинывая/пробивая себе (путь на?) свободу ногой

2021-05-28 17:22 UTC, Zickusable commented on code/modules/atmospheric/machinery/components/unary_devices/cryo.dm
> +			to_chat(user, "Вы едва можете различить форму того, что плавает в криогенной камере.")
Форма чего? Что форма? Зачем мне различать форму в крио? Форма - слишком неопределенное слово. У меня именно форма чего-то/кого-то живого/способного жить

2021-05-28 17:24 UTC, Zickusable commented on code/modules/atmospheric/machinery/components/unary_devices/cryo.dm
> +		to_chat(user, "<span class='warning'>Вы без понятия что с этим делать.</span>")
Нужна

2021-05-28 17:32 UTC, Zickusable commented on code/modules/atmospheric/machinery/components/unary_devices/cryo.dm
> +			"[user] помещает сосуд в криогенную камеру.",
Контейнеры максимально обобщены (есть бутылки из химии с конкретными названиями, но логично будет, что никто не видит мнимую подпись "Жидкая смерть" или "Dermaline"), если им не давать название лабелем, чем занимаюсь только я, получая по шапке за брэинрот.

2021-05-28 18:26 UTC, BesumniiChebureck approved these changes

2021-06-01 13:34 UTC, BesumniiChebureck commented
Замержите уже, транс деп всё равно мертв.

2021-06-04 16:38 UTC, KIBORG04 commented on code/modules/atmospheric/machinery/components/unary_devices/cryo.dm
> -	set name = "Eject Cryo Cell"
Не стоит переименовывать имена вербам

2021-06-04 16:41 UTC, KIBORG04 commented on code/modules/atmospheric/machinery/components/unary_devices/cryo.dm
> +			"[user] помещает [I] в криокамеру.",
так у вас криокамеры или криогенная камера?

2021-06-04 17:13 UTC, BesumniiChebureck commented on code/modules/atmospheric/machinery/components/unary_devices/cryo.dm
> +			"[user] помещает [I] в криокамеру.",
Криокамера сокращение от криогенной камеры. Так что тут где так, где сяк.

2021-06-05 06:36 UTC, Zickusable commented on code/modules/atmospheric/machinery/components/unary_devices/cryo.dm
> +	set name = "Извлечь из Криокамеры"
```suggestion
	set name = "Begin the release sequence inside the cryo tube."
```

2021-06-05 07:08 UTC, BesumniiChebureck commented on code/modules/atmospheric/machinery/components/unary_devices/cryo.dm
> +	set name = "Begin the release sequence inside the cryo tube."
```suggestion
	set name = "Eject Cryo Cell."
```
...

2021-06-10 17:38 UTC, KIBORG04 commented on code/modules/atmospheric/machinery/components/unary_devices/cryo.dm
> +			"[user] помещает [I] в криокамеру.",
И че что сокращение. Один термин должен быть заюзан везде

2021-06-10 17:39 UTC, KIBORG04 reviewed
Не вызывайте мой ревью, я жду аппрув от депа.

2021-06-10 18:23 UTC, BesumniiChebureck commented on code/modules/atmospheric/machinery/components/unary_devices/cryo.dm
> +			"[user] помещает [I] в криокамеру.",
> И че что сокращение. Один термин должен быть заюзан везде

Кто сказал? 

(Там где [scr] должно должно быть фулл название вообще, если переводить как в оригинале)

2021-07-10 08:45 UTC, Zickusable commented
4 месяца прошло, выходят чужие переводы сразу вместе с фичей... мне говорят, что лучше делать на инглише. :/

2021-07-10 09:19 UTC, T6751 commented on code/modules/atmospheric/machinery/components/unary_devices/cryo.dm
> +	set name = "Eject Cryo Cell."
Зачем точка в конце верба? Это некрасиво
```suggestion
	set name = "Eject Cryo Cell"
```

2021-07-10 09:19 UTC, T6751 commented on code/modules/atmospheric/machinery/components/unary_devices/cryo.dm
> +			to_chat(user, "<span class='warning'>Сосуд уже загружен в криогенную камеру!</span>")
```Ёмкость``` или ```контейнер для реагентов``` думаю больше подойдёт, т.к. сюда это не только конкретно хим.сосуд может быть
```suggestion
			to_chat(user, "<span class='warning'>Контейнер для реагентов уже загружена в криогенную камеру!</span>")
```

2021-07-10 09:19 UTC, T6751 commented on code/modules/atmospheric/machinery/components/unary_devices/cryo.dm
> +			"<span class='notice'>Вы помещаете сосуд в криогенную камеру.</span>")
```suggestion
			"<span class='notice'>Вы помещаете контейнер для реагентов в криогенную камеру.</span>")
```

2021-07-10 11:42 UTC, KIBORG04 commented on code/modules/atmospheric/machinery/components/unary_devices/cryo.dm
> +			"<span class='notice'>Вы помещаете сосуд в криогенную камеру.</span>")
Я все еще не вижу смысла юзать в разных местах разное написание крио. Вот тут даже в одном проке разные формулировки

2021-07-10 16:21 UTC, T6751 requested changes
В общем, касательно перевода: Когда исправишь моменты, которые я и Киборг указали, то в целом можно мержить.
А иначе ничего не могу поделать, жди ревью от транслейтдепа

2021-07-10 17:13 UTC, Haggerd commented on code/modules/atmospheric/machinery/components/unary_devices/cryo.dm
> +			to_chat(user, "<span class='warning'>Сосуд уже загружен в криогенную камеру!</span>")
Контейнер для реагентов? А в крио случаем нельзя тряпку бармена вставить?

2021-07-10 17:16 UTC, T6751 commented on code/modules/atmospheric/machinery/components/unary_devices/cryo.dm
> +			to_chat(user, "<span class='warning'>Сосуд уже загружен в криогенную камеру!</span>")
А тряпка это сосуд? И это вероятно проблема тряпки

2021-07-10 17:17 UTC, Haggerd commented on code/modules/atmospheric/machinery/components/unary_devices/cryo.dm
> +			to_chat(user, "<span class='warning'>Сосуд уже загружен в криогенную камеру!</span>")
Гляну на днях, что туда вообще можно вставлять. Если только бикеры, то контейнер подойдёт, а если нет, то перефразируем как-нибудь

2021-07-11 18:26 UTC, T6751 commented
Это теперь только перевод?

2021-07-11 18:27 UTC, T6751 approved these changes

2021-07-12 13:55 UTC, merged