Локализация тюрфов и ЕРТ
TauCetiStation/TauCetiClassic pull request #6930
Opened 2021-03-10 10:30 UTC by Zickusable

## Описание изменений
Перевел взаимодействие с тюрфами. Перевел ЕРТ
При разборке пола добавил предупреждение для окружающих. Идея навеяна недавним наблюдением за инженером, который вместо починки устроил разгерму. В случае с ЕРТ это более чем необходимо.
## Почему и что этот ПР улучшит
Понимание новеньких и просто не могущих в инглиш, что собственно делать.
## Авторство

## Чеинжлог
:cl:
- ru: Русификация тюрфов и ЕРТ.

2021-03-10 11:05 UTC, Akellazp commented on code/game/response_team.dm
> +			to_chat(usr, "<span class='danger'>Вы забанены и не можете вступить в группу быстрого реагирования!</span>")
почему ты перевел джоббан как бан?

2021-03-10 11:41 UTC, Akellazp commented on code/game/turfs/simulated/floor.dm
> +			to_chat(user, "<span class='warning'>Вы отремонтировали немного вмятин.</span>")
Да, "несколько" звучит лучше

2021-03-11 07:45 UTC, Zickusable commented on code/game/response_team.dm
> +			to_chat(usr, "<span class='danger'>Вы забанены и не можете вступить в группу быстрого реагирования!</span>")
```suggestion
			to_chat(usr, "<span class='danger'>У вас джоббан. Вы не можете вступить в группу быстрого реагирования!</span>")
```

2021-03-11 07:46 UTC, Zickusable commented on code/game/turfs/simulated/floor.dm
> +			to_chat(user, "<span class='warning'>Вы отремонтировали немного вмятин.</span>")
```suggestion
			to_chat(user, "<span class='warning'>Вы отремонтировали несколько вмятин.</span>")
```

2021-03-11 18:28 UTC, YakovLya approved these changes
Качественный перевод

2021-03-12 06:53 UTC, TauKitty commented
This pull request has been mentioned on **Tau Ceti Station Forum**. There might be relevant details there:

https://forum.taucetistation.org/t/perevod-ss13-dlya-servera-tau-ceti/21675/81

2021-03-12 07:06 UTC, T6751 requested changes

2021-03-12 07:06 UTC, T6751 commented on code/game/response_team.dm
> +	var/new_hstyle = input(usr, "Выберите прическу", "Grooming")  as null|anything in get_valid_styles_from_cache(hairs_cache, M.get_species(), M.gender)
Grooming решено не переводить почему-то?

2021-03-12 08:23 UTC, Zickusable commented on code/game/response_team.dm
> +	log_admin("[key_name(usr)] использовал Отправить группу экстренного реагирования.")
лог_админ вернул как было

2021-03-12 14:19 UTC, volas commented on code/game/response_team.dm
> -	set name = "Dispatch Emergency Response Team"
``name`` стоит оставлять как есть, это педальные кнопки

2021-03-12 14:26 UTC, volas commented on code/game/turfs/simulated/floor.dm
> +			visible_message("<span class='warning'><B>[user]</B> начинает разбирать обшивку! По ту сторону открытый космос!</span>")
В случаях как тут и ниже следовало бы использовать mob.visible_message с параметрами,

https://github.com/TauCetiStation/TauCetiClassic/blob/cd383683978e83f5ad6b408390f170417ddd16df/code/modules/mob/mob.dm#L121-L138

2021-03-12 14:27 UTC, volas commented on code/game/turfs/simulated/floor.dm
> +			visible_message("<span class='warning'><B>[user]</B> начинает разбирать обшивку! По ту сторону открытый космос!</span>")
Еще не стоит использовать своё форматирование сообщений типо ``<B>[user]</B>`` - пока это не стандарт и не применяется везде.

2021-03-12 14:28 UTC, Zickusable commented on code/game/response_team.dm
> -	set name = "Dispatch Emergency Response Team"
Как по мне, не очень приятно смотреть этот инглиш. Ничего не мешает это перевести. Но если вам прям нужен инглиш, то оставим как было.

2021-03-12 14:30 UTC, volas commented on code/game/response_team.dm
> -	set name = "Dispatch Emergency Response Team"
Это названия педальных кнопок, игрок их не видит. Если им потребуется перевод, это будет комплексная работа над всеми кнопками сразу, иначе каша из языков будет только мешать.

2021-03-12 14:48 UTC, Zickusable commented on code/game/turfs/simulated/floor.dm
> +			visible_message("<span class='warning'><B>[user]</B> начинает разбирать обшивку! По ту сторону открытый космос!</span>")
> Еще не стоит использовать своё форматирование сообщений типо `<B>[user]</B>` - пока это не стандарт и не применяется везде.

Разве не стандарт? Разве не применяется везде? Ctrl+C Ctrl+V со строк выше, да и во время моих последних переводов только такое форматирование и видел. Ну хорошо.

2021-03-12 14:50 UTC, volas commented on code/game/turfs/simulated/floor.dm
> +			visible_message("<span class='warning'><B>[user]</B> начинает разбирать обшивку! По ту сторону открытый космос!</span>")
Хм, да, я ошибся @Zickusable. Можешь оставить.

2021-03-14 07:40 UTC, Zickusable commented on code/game/turfs/simulated/floor.dm
> +			visible_message("<span class='warning'><B>[user]</B> начинает разбирать обшивку! По ту сторону открытый космос!</span>")
Кажется, вот так.

2021-03-25 20:32 UTC, TechCatOther commented on code/game/turfs/space/space.dm
> +			to_chat(user, "<span class='warning'>Фундамент не может выдержать это покрытие.</span>")
```suggestion
			to_chat(user, "<span class='warning'>Обшивка не может выдержать это покрытие.</span>")
```
Фундамент на чем-то стоит, а в космосе...

2021-03-25 20:32 UTC, TechCatOther commented on code/game/turfs/simulated/floor.dm
> +			to_chat(user, "<span class='warning'>Вы начинаете разрезать обшивку! За ней открытый космос!</span>")
Тут два сообщению будут для того, кто режет. Используй аргумент self_message у usr.visible_message()
![изображение](https://user-images.githubusercontent.com/378937/112539206-c1873400-8dc1-11eb-84d6-a63db2e81634.png)

2021-03-25 20:32 UTC, TechCatOther commented on code/game/turfs/simulated/floor.dm
> +			visible_message("<span class='warning'><B>[user]</B> начинает разбирать обшивку! По ту сторону открытый космос!</span>", blind_message = "<span class='warning'>Вы слышите звуки разрезания обшивки!
Может сделать текст для слепых о разрезании металла? А то как они будучи слепыми поймут, что именно так звучит обшивка.

2021-03-25 21:29 UTC, TechCatOther commented on code/game/response_team.dm
> +			to_chat(new_commando, "<span class='notice'>Вы являетесь [!leader_selected?"членом":"<B>ЛИДЕРОМ</B>"] группы экстренного реагирования, видом военного подразделения, под управлением ЦК.<BR>На станц
![изображение](https://user-images.githubusercontent.com/378937/112543420-c7334880-8dc6-11eb-914f-29db90e84485.png)
А зачем тут скобочки?

2021-03-25 21:29 UTC, TechCatOther commented on code/game/response_team.dm
> +	set name = "Вступить в группу экстренного реагирования"
![изображение](https://user-images.githubusercontent.com/378937/112544615-46754c00-8dc8-11eb-9af2-b7411828e811.png)
Это точно надо сделать меньше. Используй аббревиатуру или оставь на английском и переведем все кнопки разом через один ПР.

2021-03-28 05:32 UTC, Zickusable commented on code/game/turfs/simulated/floor.dm
> +				to_chat(user, "<span class='warning'>Вы демонтируете пол.</span>")
Тогда же будет "Вы демонтируете the floor". Не думаю, что есть смысл указывать какой именно пол.

2021-03-28 05:36 UTC, TechCatOther commented on code/game/turfs/simulated/floor.dm
> +				to_chat(user, "<span class='warning'>Вы демонтируете пол.</span>")
Их названия есть в floor_types.dm
Можно и потом перевести. Все равно с учётом количество текста будет мешанина во время перевода.

2021-03-28 06:08 UTC, Zickusable commented on code/game/response_team.dm
> +			to_chat(new_commando, "<span class='notice'>Вы являетесь [!leader_selected?"членом":"<B>ЛИДЕРОМ</B>"] группы экстренного реагирования, видом военного подразделения, под управлением ЦК.<BR>На станц
Так лучше выделяется из всей этой каши, на мой взгляд.

2021-03-28 06:11 UTC, TechCatOther commented on code/game/response_team.dm
> +			to_chat(new_commando, "<span class='notice'>Вы являетесь [!leader_selected?"членом":"<B>ЛИДЕРОМ</B>"] группы экстренного реагирования, видом военного подразделения, под управлением ЦК.<BR>На станц
Я не думаю, что вообще туда будут смотреть. По идее только при красном вызов ОБР. И если не красный, скорее всего некому просто уже код сменить или некогда. Для атмосферы текстом неплохо конечно это писать.

2021-03-28 06:13 UTC, Zickusable commented on code/datums/announcements/centcomm.dm
> +	message = "Похоже, группа экстренного реагирования была запрошена на станцию NSS Exodus. Мы подготовим и отправим одну в кратчайшие сроки."
Мы подготовим и отправим **его** (отряд)... ?

2021-03-28 06:14 UTC, TechCatOther commented on code/datums/announcements/centcomm.dm
> +	message = "Похоже, группа экстренного реагирования была запрошена на станцию NSS Exodus. Мы подготовим и отправим одну в кратчайшие сроки."
Поправил

2021-03-29 12:19 UTC, Zickusable commented on code/game/turfs/simulated/floor.dm
> +				to_chat(user, "<span class='notice'>Вы начинаете укреплять пол.</span>")
Укрепление выглядит как существительное, да и напоминает "Укрепляем пол...", что "попахивает шизой"

2021-03-29 12:25 UTC, TechCatOther commented on code/game/turfs/simulated/floor.dm
> +				to_chat(user, "<span class='notice'>Вы начинаете укреплять пол.</span>")
Вообще я сам не много в шоке от фразы. Как бы тут везде пол - это обшивка с плиткой, деревом и так далее. А использование прутьев выглядит как увеличение жесткости конструкции, плюс там нет изначально пола и значит укреплять нечего. Можешь на свое усмотрение поставить тут что-то свое поставить без точного перевода. Фраза в оригинале не очень, пусть у нас будет лучше 😃

2021-03-29 12:42 UTC, Zickusable commented on code/game/turfs/simulated/floor.dm
> +				to_chat(user, "<span class='notice'>Вы начинаете укреплять пол.</span>")
Если только вместо пола "обшивка"

2021-03-29 12:45 UTC, Zickusable commented on code/game/turfs/simulated/floor.dm
> +			to_chat(user, "<span class='warning'>Сначала нужно удалить покрытие.</span>")
Тут именно покрытие, вроде ковра или паркета.

2021-03-29 12:54 UTC, Zickusable commented on code/game/turfs/simulated/floor.dm
> +				to_chat(user, "<span class='warning'>Вы демонтируете пол.</span>")
"Вы демонтируете плитка". "Потом" понятие растяжимое. Заменю на покрытие.

2021-03-29 13:26 UTC, Zickusable commented on code/game/turfs/simulated/floor.dm
> +			visible_message("<span class='warning'><B>[user]</B> начинает разбирать обшивку! По ту сторону открытый космос!</span>", blind_message = "<span class='warning'>Вы слышите звуки разрезания обшивки!
Сделаем вид, что они различаются, надо же как-то исполнять программу "Доступная среда" =)

2021-03-29 13:44 UTC, TechCatOther commented on code/game/turfs/simulated/floor.dm
> +				to_chat(user, "<span class='warning'>Вы демонтируете пол.</span>")
Ок, но я более чем уверен что оно так и останется навсегда. Я и сам через пол года забуду, что тут можно поправить после перевода объектов

2021-03-29 14:23 UTC, Zickusable commented on code/game/turfs/simulated/floor.dm
> +			to_chat(user, "<span class='warning'>Вы начинаете разрезать обшивку! За ней открытый космос!</span>")
Не получается у меня. У стен тоже так показывает сообщения. Пусть служит двойным предупреждением.

2021-03-29 14:24 UTC, TechCatOther commented on code/game/turfs/simulated/floor.dm
> +			to_chat(user, "<span class='warning'>Вы начинаете разрезать обшивку! За ней открытый космос!</span>")
Не не, я тогда вечером кину в твою ветку правки, если ты не против.

2021-03-29 14:45 UTC, Zickusable commented on code/game/turfs/simulated/floor.dm
> +				to_chat(user, "<span class='notice'>Вы начинаете укреплять покрытие.</span>")
```suggestion
				to_chat(user, "<span class='notice'>Вы начинаете укреплять обшивку.</span>")
```

2021-03-29 14:47 UTC, Zickusable commented on code/game/turfs/simulated/floor.dm
> +				to_chat(user, "<span class='notice'>Вы начинаете укреплять покрытие.</span>")
```suggestion
				to_chat(user, "<span class='notice'>Вы начинаете укреплять обшивку.</span>")
```

2021-03-29 14:49 UTC, Zickusable commented on code/game/response_team.dm
> +			to_chat(usr, "<span class='danger'>Администрация запретила вам вступление в группу быстрого реагирования!</span>")
```suggestion
			to_chat(usr, "<span class='danger'>Администрация запретила вам вступать в отряд быстрого реагирования!</span>")
```

2021-03-29 17:36 UTC, TechCatOther commented on code/game/turfs/simulated/floor_types.dm
> +	desc = "Кошки очень не любят такие покрытия."
Шутка не зайдет, нужен свой текст.

2021-05-02 18:08 UTC, Zickusable commented on code/game/turfs/simulated/floor_types.dm
> +	desc = "Кошки очень не любят такие покрытия."
```suggestion
	desc = "Рабочий помост с сомнительным функционалом."
```

2021-06-01 06:48 UTC, Zickusable commented
> Данный ПР автоматически отмечен как застоявшийся по причине длительного отсутствия обновлений. Он будет закрыт через 7 дней, если никакой активности не будет проявлено. Если вы считаете, что ПР еще актуален, или что я (злобный робот) пристаю к вам зря - просто напишите любой комментарий. Спасибо за ваш вклад.

Неправда

2021-07-12 16:02 UTC, Zickusable commented on code/game/response_team.dm
> +			to_chat(usr, "<span class='notice'>Эта роль будет открыта через [russian_plural(available_in_minutes, "[available_in_minutes] минуту", "[available_in_minutes] минуты", "[available_in_minutes] мину
```suggestion
			to_chat(usr, "<span class='notice'>Эта роль будет открыта через количество минут: [available_in_minutes]. Продолжайте играть для получения доступа.</span>")
```
Куда делся рашн плюрал и чем его заменить?

2021-07-12 16:22 UTC, T6751 commented
> Куда делся рашн плюрал и чем его заменить?

```pluralize_russian()```

2021-09-03 12:56 UTC, atik1n commented on code/datums/announcements/centcomm.dm
> +
Это было намеренно для разделения кода

2021-09-03 12:57 UTC, atik1n commented on code/game/response_team.dm
> +		to_chat(usr, "<span class='warning'>Центральное командование уже отправило отряд быстрого реагирования!</span>")
Если пишешь ЦК, то пиши "Центральное Командование"

2021-09-03 12:57 UTC, atik1n commented on code/game/response_team.dm
> +		switch(tgui_alert(usr, "На станции не введен красный код. Вы все еще хотите отправить отряд быстрого реагирования?",, list("Да","Нет")))
```suggestion
		switch(tgui_alert(usr, "На станции не введён красный код. Вы все еще хотите отправить отряд быстрого реагирования?",, list("Да","Нет")))
```

2021-09-03 13:03 UTC, atik1n requested changes

2021-09-03 13:03 UTC, atik1n commented on code/game/response_team.dm
> +	var/new_fstyle = input(usr, "Выберите стиль лицевой растительности", "Отличительные признаки")  as null|anything in get_valid_styles_from_cache(facial_hairs_cache, M.get_species(), M.gender)
```suggestion
	var/new_fstyle = input(usr, "Выберите стиль растительности на лице", "Отличительные признаки")  as null|anything in get_valid_styles_from_cache(facial_hairs_cache, M.get_species(), M.gender)
```

2021-09-03 15:23 UTC, Zickusable commented on code/game/response_team.dm
> +		to_chat(usr, "<span class='warning'>Похоже, кто-то уже опередил вас!</span>")
Похоже – вводное слово (или как там называется), так что хватает запятой. Можно просто оставить "кто-то...", но зачем в оригинале неопределенность

2021-09-03 15:24 UTC, Zickusable commented on code/game/response_team.dm
>  	set name = "Dispatch Emergency Response Team"
Админ кнопки сказали не трогать

2021-09-03 22:18 UTC, atik1n commented on code/game/response_team.dm
>  	set name = "Dispatch Emergency Response Team"
Окей, окей

2021-09-03 22:18 UTC, atik1n commented on code/game/response_team.dm
> +		to_chat(usr, "<span class='warning'>Похоже, кто-то уже опередил вас!</span>")
Просто мне немного не понравилось звучание. Не обязательно, но решил отметить.

2021-09-08 12:52 UTC, Zickusable commented
Ну и где этот ваш хваленый департамент?

2021-09-08 12:52 UTC, atik1n commented
Ты нас призывал? Нет. Ты в моём коде исправил, что я попросил исправить? Нет

2021-09-08 12:55 UTC, Zickusable commented on code/datums/announcements/centcomm.dm
> +
Что тут не так? Это вопрос?

2021-09-08 12:55 UTC, atik1n commented on code/datums/announcements/centcomm.dm
> +
Убери лишнюю строчку, что ты добавил

2021-09-08 12:57 UTC, Zickusable commented on code/datums/announcements/centcomm.dm
> +
```suggestion
```

2021-09-08 12:59 UTC, Zickusable commented
Лишняя строчка выпилена, сэр!

2021-09-08 12:59 UTC, atik1n requested changes

2021-09-08 12:59 UTC, atik1n commented on code/datums/announcements/centcomm.dm
> +
и тут, я думал логично, что я не тыкал
```suggestion
```

2021-09-08 13:00 UTC, Zickusable commented on code/datums/announcements/centcomm.dm
> +
Так и пиши, что все лишние строчки, ибо нет - не логично

2021-09-08 13:03 UTC, Zickusable commented on code/game/response_team.dm
> +
```suggestion
```

2021-09-08 13:03 UTC, Zickusable commented on code/game/response_team.dm
> +
```suggestion
```

2021-09-08 13:09 UTC, Zickusable commented on code/game/response_team.dm
> +
```suggestion
```

2021-09-08 13:11 UTC, Zickusable commented
А теперь?

2021-09-08 19:42 UTC, volas commented on code/game/response_team.dm
> +			to_chat(usr, "<span class='notice'>Эта роль будет открыта через [pluralize_russian(available_in_minutes, "[available_in_minutes] минуту", "[available_in_minutes] минуты", "[available_in_minutes] м
```suggestion
			to_chat(usr, "<span class='notice'>Эта роль будет открыта через [available_in_minutes] [pluralize_russian(available_in_minutes, "минуту", "минуты", "минут")]. Продолжайте играть для получения доступа.</span>")
```

2021-09-08 19:46 UTC, volas commented on code/game/turfs/simulated/floor.dm
> +			to_chat(user, "<span class='warning'>Объект на 100% завершен, стержней больше не нужно.</span>")
не завершен на 100%, а заполнен требуемыми... стержнями

2021-09-08 19:48 UTC, volas commented on code/game/turfs/simulated/floor.dm
> +			to_chat(user, "<span class='notice'>Нужно больше топлива.</span>")
довольно абстрактно, когда в оригинале было ``welding fuel``. Может быть переформулировать что это именно заправка

2021-09-08 19:49 UTC, volas commented
Общее замечание - стержни везде вероятно стоит заменить на арматуру

2021-09-08 19:52 UTC, atik1n commented on code/game/turfs/simulated/floor.dm
> +			to_chat(user, "<span class='notice'>Нужно больше топлива.</span>")
Для этого нужно дозаправить баллон? или типа того?

2021-09-09 08:44 UTC, Zickusable commented on code/game/turfs/simulated/floor.dm
> +			to_chat(user, "<span class='warning'>Объект на 100% завершен, стержней больше не нужно.</span>")
```suggestion
			to_chat(user, "<span class='warning'>Объект уже на 100% состоит из стержней , больше не нужно.</span>")
```

2021-09-09 08:59 UTC, Zickusable commented
~Я не петербуржец, так что для меня все же бордюр.~
Не стоит, я конечно не строитель, но для простого обывателя длинные черные палки и есть длинные черные палки.

2021-09-09 09:00 UTC, atik1n commented
Я петербуржец и мне пофиг, бордюр или поребрик

2021-09-09 09:03 UTC, Zickusable commented on code/game/turfs/simulated/floor.dm
> +			to_chat(user, "<span class='notice'>Нужно больше топлива.</span>")
```suggestion
			to_chat(user, "<span class='notice'>Нужно больше топлива для сварки.</span>")
```

2021-09-09 14:11 UTC, volas approved these changes

2022-02-09 21:52 UTC, KIBORG04 commented
![image](https://user-images.githubusercontent.com/26389417/153296270-f7d19cce-9d47-487f-a0e6-5230800263f9.png)

Предлагаю через месяц замержить.

2022-02-10 06:16 UTC, Zickusable commented
Нет, тихонечко отметим годовщину и забудем как страшный сон. Либо будем держать как напоминание новым кодерам о чем-нибудь. Либо через 10 лет старички будут слагать легенды о загадочном ПРе, который запрещено мержить и никто не знает почему.

2022-02-22 18:56 UTC, Akellazp commented on code/game/response_team.dm
> +	var/new_tone = input(src, "Выберите тон кожи: 1-220 (1=albino, 35=caucasian, 150=black, 220='very' black)", "Создание персонажа")  as text
почему оттенки кожи не перевел?

2022-02-22 19:00 UTC, Akellazp commented on code/game/turfs/simulated/floor.dm
> +				to_chat(user, "<span class='warning'>Вы демонтируете покрытие.</span>")
в прошедшем времени звучало бы получше

2022-02-22 19:01 UTC, Akellazp commented on code/game/turfs/simulated/floor.dm
> +					to_chat(user, "<span class='warning'>Вы откручиваете доски.</span>")
тут тоже

2022-02-22 19:06 UTC, Akellazp commented on code/game/turfs/space/space.dm
> +						to_chat(MM, "<span class='warning'>Кое-что мешает улететь. Не прикидывайся дурачком; ты знаешь о чем мы.</span>")
что-то, что ты несешь, мешает улететь

2022-02-22 19:06 UTC, Akellazp commented on code/game/turfs/simulated/floor.dm
> +			to_chat(user, "<span class='warning'>Вы ремонтируете обшивку.</span>")
и тут прошедшее время

2022-02-23 06:35 UTC, Zickusable commented on code/game/response_team.dm
> +	var/new_tone = input(src, "Выберите тон кожи: 1-220 (1=albino, 35=caucasian, 150=black, 220='very' black)", "Создание персонажа")  as text
переведем

2022-02-23 06:48 UTC, Lexakr requested changes

2022-02-23 06:48 UTC, Lexakr commented on code/game/response_team.dm
> +		to_chat(usr, "<span class='warning'>Игра еще не началась!</span>")
Снизу про раунд и там все понятно, а здесь это все таки, наверное, `Игра еще не загрузилась` ?

2022-02-23 06:48 UTC, Lexakr commented on code/game/response_team.dm
> +	var/new_hstyle = input(src, "Выберите прическу", "Отличительные признаки")  as null|anything in get_valid_styles_from_cache(hairs_cache, H.get_species(), H.gender)
```suggestion
	var/new_hstyle = input(src, "Выберите прическу", "Внешность")  as null|anything in get_valid_styles_from_cache(hairs_cache, H.get_species(), H.gender)
```

2022-02-23 06:48 UTC, Lexakr commented on code/game/turfs/simulated/floor.dm
> +				to_chat(user, "<span class='notice'>Лампочка выглядит целой, нет нужды заменять ее.</span>")
```suggestion
				to_chat(user, "<span class='notice'>Похоже, лампочка в порядке, менять ее не нужно.</span>")
```

2022-02-23 06:48 UTC, Lexakr commented on code/game/turfs/simulated/floor.dm
> +			to_chat(user, "<span class='warning'>Вы удаляете поврежденное покрытие.</span>")
```suggestion
			to_chat(user, "<span class='warning'>Вы снимаете поврежденное покрытие.</span>")
```

2022-02-23 06:48 UTC, Lexakr commented on code/game/turfs/simulated/floor.dm
> +				to_chat(user, "<span class='warning'>Вы демонтируете покрытие.</span>")
```suggestion
				to_chat(user, "<span class='warning'>Вы снимаете светящуюся плитку.</span>")
```
Можно рискнуть так. В данный момент лайт тайл представлен только светоплиткой

2022-02-23 06:48 UTC, Lexakr commented on code/game/turfs/simulated/floor.dm
> +				to_chat(user, "<span class='notice'>Вы начинаете укреплять обшивку.</span>")
```suggestion
				to_chat(user, "<span class='notice'>Укрепление обшивки...</span>")
```
многоточие тут к месту и к месту затягивание процесса, ведь он не моментальный

2022-02-23 06:48 UTC, Lexakr commented on code/game/turfs/simulated/floor.dm
> +				"<span class='warning'>Вы слышите звуки будто разрезают обшивку! По ту сторону должен быть открытый космос!</span>",
А нужно ли это, учитывая, что:
1) Звуковизуальное сопровождение этого действия и так есть в игре
2) Действие может происходить в вакууме = без распространения звуков
?

2022-02-23 06:48 UTC, Lexakr commented on code/game/turfs/simulated/floor.dm
> +					"<span class='warning'>Звуки прекратились. Похоже, обшивка была разрезана на части!</span>",
same

2022-02-23 06:48 UTC, Lexakr commented on code/game/turfs/simulated/floor_types.dm
> +	desc = "\"Это металлический диск в честь наших товарищей на станциях G4407. Недеемся модель TG4407 сможет служить на ваше благо.\" Ниже выцарапано грубое изображение метеора и космонавта. Космонавт
```suggestion
	desc = "\"Это мемориальная доска в память о наших товарищах на станциях типа G4407. Надеемся, что модель TG4407 оправдает Ваши ожидания.\" Ниже выцарапано грубое изображение метеора и космонавта. Космонавт смеется. Метеор взрывается.";
```

2022-02-23 06:48 UTC, Lexakr commented on code/game/turfs/simulated/floor_types.dm
> +		to_chat(user, "<span class='notice'>Вы начинаете удалять стержни.</span>")
```suggestion
		to_chat(user, "<span class='notice'>Удаление стержней...</span>")
```

2022-02-23 06:48 UTC, Lexakr commented on code/game/turfs/simulated/floor_types.dm
> +	desc = "Рабочий помост с сомнительным функционалом."
Как жалко, что такая шутка пропадает :)

2022-02-23 06:48 UTC, Lexakr commented on code/game/turfs/space/space.dm
> +			to_chat(user, "<span class='notice'>Вы начали собирать помост.</span>")
```suggestion
			to_chat(user, "<span class='notice'>Вы начинаете собирать помост.</span>")
```

2022-02-23 06:48 UTC, Lexakr commented on code/game/turfs/space/space.dm
> +		to_chat(user, "<span class='notice'>Вы собрали поддерживающую решетку.</span>")
```suggestion
		to_chat(user, "<span class='notice'>Создание поддерживающей решетки...</span>")
```

2022-02-23 06:48 UTC, Lexakr commented on code/game/turfs/space/space.dm
> +			to_chat(user, "<span class='warning'>Для обшивки нужна основа.</span>")
```suggestion
			to_chat(user, "<span class='warning'>Покрытию нужна опора.</span>")
```

2022-02-23 06:48 UTC, Lexakr commented on code/game/turfs/space/space.dm
> +						to_chat(MM, "<span class='warning'>Кое-что мешает улететь. Не прикидывайся дурачком; ты знаешь о чем мы.</span>")
```suggestion
						to_chat(MM, "<span class='warning'>Что-то мешает вам улететь. Не прикидывайтесь: вы знаете, что это.</span>")
```

2022-02-23 07:36 UTC, Zickusable commented on code/game/turfs/simulated/floor.dm
> +				to_chat(user, "<span class='notice'>Вы начинаете укреплять обшивку.</span>")
Вообще такие многоточия должны были быть и у стенок, но их не разрешили.

2022-02-23 07:38 UTC, Zickusable commented on code/game/turfs/simulated/floor.dm
> +				"<span class='warning'>Вы слышите звуки будто разрезают обшивку! По ту сторону должен быть открытый космос!</span>",
Кто-то в прошлом из мэинтейнеров сказал так сделать

2022-02-28 17:45 UTC, DarthSidiousPalpatine commented on code/game/response_team.dm
> +	var/new_tone = input(src, "Выберите тон кожи: 1-220 (1=albino, 35=caucasian, 150=black, 220='very' black)", "Создание персонажа")  as text
Молю, Умоляю, не переведи только "caucasian" как "кавказец"

2022-03-03 07:48 UTC, LudwigVonChesterfield commented
Солидарен с комментаторами выше. Когда пофиксишь - можно будет снова открыть.

2022-03-10 18:07 UTC, Zickusable commented
Пофикшено, отпути @LudwigVonChesterfield

2022-03-10 18:54 UTC, KIBORG04 commented
10 марта пришло, и где коммит с фиксами?

2022-03-10 20:29 UTC, Akellazp commented on code/game/turfs/simulated/floor.dm
> +				"<span class='warning'>Вы слышите звуки будто разрезают обшивку! По ту сторону должен быть открытый космос!</span>",
звуки разбирания пола не отличаются от звуков разбирания стены и это "будто" такое себе

2022-03-10 20:30 UTC, Akellazp commented on code/game/turfs/simulated/floor.dm
> +					"<span class='warning'>Звуки прекратились. Похоже, обшивка была разрезана на части!</span>",
а если звуки прекратились потому что просто резать перестали?

2022-03-20 17:45 UTC, Zickusable commented on code/game/turfs/simulated/floor.dm
> +					"<span class='warning'>Звуки прекратились. Похоже, обшивка была разрезана на части!</span>",
Это скорее для слепых без колонок и наушников людей, чтобы они поняли, что стенку снесли. Типо баланс или как они его там называют.

2022-04-03 19:14 UTC, Zickusable commented
+

2022-04-03 19:20 UTC, Zickusable commented
не души

2022-04-09 02:19 UTC, volas commented on code/game/turfs/simulated/floor.dm
> +			to_chat(user, "<span class='warning'>Объект уже на 100% состоит из стержней, больше не нужно.</span>")
rods тут было скорее как глагол

2022-04-09 02:24 UTC, volas commented on code/game/turfs/simulated/floor.dm
> +				to_chat(user, "<span class='notice'>Эта секция слишком повреждена, чтобы выдержать покрытие. Используйте сварочный аппарат для ремонта.</span>")
может лучше вместо покрытия оставить "плитку", или какое-нибудь "основание"

2022-04-09 09:44 UTC, Zickusable commented on code/game/turfs/simulated/floor.dm
> +				to_chat(user, "<span class='notice'>Эта секция слишком повреждена, чтобы выдержать покрытие. Используйте сварочный аппарат для ремонта.</span>")
Это может быть светопол, паркет, прочая муть

2022-04-09 10:02 UTC, volas commented on code/game/turfs/simulated/floor.dm
> +				to_chat(user, "<span class='notice'>Эта секция слишком повреждена, чтобы выдержать покрытие. Используйте сварочный аппарат для ремонта.</span>")
> wood floor tile
> grass tile
> light tile

Это всегда плитка, по названию и спрайту. Мне кажется, оставить плиткой будет корректнее, и покрытие в контексте звучит как-то не очень.

2022-04-09 10:12 UTC, volas commented on code/game/turfs/simulated/floor.dm
> +			to_chat(user, "<span class='warning'>Объект уже на 100% состоит из стержней, больше не нужно.</span>")
Имел в виду, что тут шуточный интернет-сленг (я не знаю как это называется, на самом деле), в значении что ты заполнил на 100% требуемыми стержнями, а не что оно состоит из них, но в целом и так корректно.

2022-04-09 11:27 UTC, Zickusable commented on code/game/turfs/simulated/floor.dm
> +				to_chat(user, "<span class='notice'>Эта секция слишком повреждена, чтобы выдержать покрытие. Используйте сварочный аппарат для ремонта.</span>")
Так называли люди прошлого. Менять каждый месяц туда-обратно надоедает. Где-то уже было обсуждение этой плитки в пре.

2022-04-12 04:02 UTC, volas commented
Я не уверен о паре мелочей, у меня всё еще много вопросов к идее переводов всего, и я опять не знаю где трансдеп с апрувами и прочим сопровождением. Мержу просто что бы больше не висел и не мозолил глаза. 
Следующие ПР-ы строго по закрепленному на вики плану.

2022-04-12 04:02 UTC, merged