Фикс названий автоинжекторов
TauCetiStation/TauCetiClassic pull request #6932
Opened 2021-03-11 07:59 UTC by notkripton

## Описание изменений
Исправил пустое название инжектора с инапровалином. Добавил недостающие заглавные буквы в названия комбат и лепоразин автоинжекторов.
## Почему и что этот ПР улучшит

## Авторство
я
## Чеинжлог
:cl:
- bugfix: Фикс пустого названия инжектора с инапровалином.

2021-03-11 07:59 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2021-03-12 00:35 UTC, T6751 requested changes
> Добавил недостающие заглавные буквы в названия комбат и лепоразин автоинжекторов.

У предметов обычно всегда имя должно быть с маленькой буквы, так что тут скорее проблема в том, что у других инжекторов название с заглавной

2021-03-12 04:37 UTC, notkripton commented
![Screenshot_16](https://user-images.githubusercontent.com/75007994/110892679-8981ea80-8305-11eb-9a0c-3764d6b40a2e.png)

Все инжекторы в коде с заглавной буквы кроме тех двух (стимпак не в счет).

2021-03-12 05:43 UTC, T6751 commented
> Все инжекторы в коде с заглавной буквы кроме тех двух. В химии так же лекарства в банках и таблетках в скобках пишутся с заглавной.

Ещё раз, в name названия предметов должны быть с маленькой буквы. И в данном плане исправить так, чтобы начиналось с маленькой будет правильнее. 

То, что в химии названия лекарств и таблеток с заглавной пишутся - это **тоже** неверно. Не стоит продвигать неправильный вариант. 
Просто исправь названия инжекторов, чтобы начинались с маленькой (и таблеток можно тоже, раз уж упомянул ось, если несложно) и будет хорошо

2021-03-12 06:03 UTC, notkripton commented
> > Все инжекторы в коде с заглавной буквы кроме тех двух. В химии так же лекарства в банках и таблетках в скобках пишутся с заглавной.
> 
> Ещё раз, в name названия предметов должны быть с маленькой буквы. И в данном плане исправить так, чтобы начиналось с маленькой будет правильнее.
> 
> То, что в химии названия лекарств и таблеток с заглавной пишутся - это **тоже** неверно. Не стоит продвигать неправильный вариант.
> Просто исправь названия инжекторов, чтобы начинались с маленькой (и таблеток можно тоже, раз уж упомянул ось, если несложно) и будет хорошо

Исправлю

2021-03-12 06:31 UTC, T6751 approved these changes

2021-03-12 16:16 UTC, merged