Mining equipment resprite
TauCetiStation/TauCetiClassic pull request #6936
Opened 2021-03-13 08:21 UTC by totallynotdedawa2

## Описание изменений
кинетический акселератор, плазменный резак и кирки получили новые спрайты
![image](https://user-images.githubusercontent.com/61105647/111024111-ea84ed80-83ed-11eb-9770-81d1552946b8.png)
## Почему и что этот ПР улучшит
мне не нравятся старые спрайты я делаю новые
## Авторство
walterje делал кирки
## Чеинжлог
:cl:
- image: Респрайт кирок, плазменного резака и кинетического акселератора

2021-03-13 08:21 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2021-03-13 20:10 UTC, KIBORG04 commented
А кинетик модули норм будут смотреться?

2021-03-13 20:59 UTC, totallynotdedawa2 commented
> А кинетик модули норм будут смотреться?

так там же ничего на кинетике не появляется

2021-03-14 09:52 UTC, LiLJard requested changes
Все высказались в дискорде по поводу того, что было бы хорошо поправить. Ждем.

2021-03-15 08:21 UTC, Akellazp commented
кринж кирки

2021-03-15 09:40 UTC, Tiarv commented
В руках выглядят ништяк, а вот на полу странненько как-то

2021-03-19 08:32 UTC, Shudyn commented
Менять спрайты, чтобы менять спрайты...
ИМХО слишком яркие и мультяшные. Не надо.

>Авторство: ватлерже
Понятно.

2021-03-19 09:19 UTC, CeUvi commented
> Менять спрайты, чтобы менять спрайты...
> ИМХО слишком яркие и мультяшные. Не надо.
> 
> > Авторство: ватлерже
> > Понятно.

дааа пора уже портировать спрайты с лайфвеба

2021-03-19 09:25 UTC, totallynotdedawa2 commented
> > Менять спрайты, чтобы менять спрайты...
> > ИМХО слишком яркие и мультяшные. Не надо.
> > > Авторство: ватлерже
> > > Понятно.
> 
> дааа пора уже портировать спрайты с лайфвеба

пупдарк спрайтинг

2021-03-19 09:27 UTC, UsadoSmokk commented
![unknown-21](https://user-images.githubusercontent.com/56721822/111759184-88cdf300-88c7-11eb-8425-8d3d4219314e.png)
Вот первый спрайт шахтерского инструментария

2021-03-19 16:21 UTC, KIBORG04 commented
кофликты

2021-03-25 17:01 UTC, KIBORG04 commented
все еще конфликты

2021-04-05 14:40 UTC, KIBORG04 commented
23 дня. 23 дня тут лежат эти кирки и кинетик.

2021-04-06 15:18 UTC, KIBORG04 commented
1. Качай гит баш и делай все по инструкции отсюда https://wiki.taucetistation.org/Git/GitHub
2. Ставь хуки отсюда https://github.com/TauCetiStation/TauCetiClassic/tree/master/tools/_git-hooks
3. Если все сделал четко, то в гит баше будет твое репо с выбранной твоей веткой `mining-redone`. Ее ты можешь через тот же гит хаб десктоп выбрать.
4. Запускаешь этот гит хаб десктоп на всякий случай.
5. Пишешь в гит баше на нужной ветке `git pull upstream master`
6. Ждешь.
7. Если будут конфликты, то в гит хаб десктопе они покажутся и пофиксить. 
8. Коммитить тоже можешь через гит хаб десктоп

2021-04-20 20:15 UTC, KIBORG04 commented
Когда захочешь починить или починишь, то позови кого-то переоткрыть. Мне просто глаза мозолит

2021-04-20 20:15 UTC, closed without merging