Автолат и патроны
TauCetiStation/TauCetiClassic pull request #6950
Opened 2021-03-17 16:11 UTC by Ahion

## Описание изменений
Убрал из автолата единичные патроны для дробовика и добавил коробки по 8 патронов.
<details> 
  <summary>Коробки с восьмью патронами для дробовика.</summary>
<img src="https://user-images.githubusercontent.com/58528255/111495126-bdb33c00-8747-11eb-9c02-658dd9d46fb3.jpg">
</details>

<details> 
  <summary>Некоротые из них можно напечатать в автолате.</summary>
<img src="https://user-images.githubusercontent.com/58528255/111495537-27334a80-8748-11eb-976f-0338a7d91c36.jpg"><br>
<img src="https://user-images.githubusercontent.com/58528255/111495541-27cbe100-8748-11eb-83a4-e3020c756efb.jpg">
</details>

Цены я поменял. Напомню, один лист металла - это 3750 см в кубе. Ровно столько стоит один слаг и дробь. Ну и остальным патронам, которые есть в автолате, добавил цену. 

Был баг с тем, что можно было всунуть в автолат пустую коробку из-под патронов и это давало металла столько же, сколько и полная патронов коробка. Я это исправил, теперь автолат считает цену каждого патрона, находящегося в коробке, то есть в коробке могут быть разные патроны, например slag вперемешку с beanbag, и он их правильно посчитает. Так же составляются и рецепты автолата, он смотрит не на цену коробки, а на цену патронов в ней.

Ещё спрайт вот этой хрени:  
![dart1](https://user-images.githubusercontent.com/58528255/111499246-67e09300-874b-11eb-9e18-eae8cfdf9d1c.jpg)
назывался так же как и dart-патрон. Из-за этого был такой баг: 
![autolat](https://user-images.githubusercontent.com/58528255/111499506-b1c97900-874b-11eb-8449-ec3985bc2a24.jpg)
Переименовал его в dart1, этот спрайт нигде не используется.

## Почему и что этот ПР улучшит
Вместо одного патрона для дробовика теперь коробка из восьми патронов. Что гораздо удобнее использовать и быстрее печатать.
## Авторство
Ahio, Спрайты коробок взяты с Колониальных Маринов https://gitlab.com/cmdevs/colonial-warfare
## Чеинжлог
:cl: Ahio
 - tweak[link]: Добавлены коробки с восьмью патронами для дробовика. Некоторые из них можно напечатать в автолате.
 - image: Спрайты коробок с патронами взяты с Колониальных Маринов.

2021-03-17 16:11 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2021-03-17 16:27 UTC, totallynotdedawa2 commented
может лучше сделать что патроны для шотгана собираются в кучки по n патронов???

2021-03-17 16:27 UTC, KIBORG04 commented on code/game/machinery/autolathe.dm
> +	var/obj/P = path
А зачем создавать переменную такогоже типа под `path` ?

2021-03-17 16:35 UTC, Ahion commented on code/game/machinery/autolathe.dm
> +	var/obj/P = path
Я ниже её изменяю

2021-03-17 16:39 UTC, Ahion commented
> может лучше сделать что патроны для шотгана собираются в кучки по n патронов???

Может и лучше, но не проще))

2021-03-18 18:32 UTC, KIBORG04 commented on code/game/machinery/autolathe.dm
> +	var/datum/autolathe_recipe/recipe = new
А зачем тут создавать? Типо, ты создаешь и сразу же пересоздаёшь, если `if(ispath(path, /obj/item/stack))`.
Тип, почему бы не вернуть 
```
	else
		recipe = new /datum/autolathe_recipe
```
и не убрать этот new ?

2021-03-18 18:35 UTC, KIBORG04 commented on code/game/machinery/autolathe.dm
> +		if(istype(I, /obj/item/ammo_box))
Может лучше перенести этот иф на ту же строчку, что и этот else ?

2021-03-19 17:06 UTC, WatlerJe commented
Кринж

2021-03-19 18:39 UTC, Ahion commented
> Кринж
> 
> У тебя еще спрайт коробки с патронами и самими патронами не совпадают.

Я решил проблему с помощью тех спрайтов, которые смог достать. Напиши как нарисуешь спрайты которые тебе нравятся и я их добавлю. Не вопрос)

2021-03-20 11:56 UTC, Ahion commented on code/game/machinery/autolathe.dm
> +	var/datum/autolathe_recipe/recipe = new
Если путь не равен `/obj/item/stack`, то используется `/datum/autolathe_recipe`, который я сразу создаю. В противном случае создается рецепт типа `/datum/autolathe_recipe/stack`. Это другой класс

2021-03-20 12:05 UTC, KIBORG04 commented on code/game/machinery/autolathe.dm
> +	var/datum/autolathe_recipe/recipe = new
Раньше тоже самое и было

2021-03-20 12:06 UTC, Ahion commented on code/game/machinery/autolathe.dm
> +		if(istype(I, /obj/item/ammo_box))
Да, точно)))

2021-03-20 12:07 UTC, Ahion commented on code/game/machinery/autolathe.dm
> +	var/datum/autolathe_recipe/recipe = new
Ну так я сократил код и убрал
```
 else 
        recipe = new /datum/autolathe_recipe
```

2021-03-20 13:53 UTC, KIBORG04 commented on code/game/machinery/autolathe.dm
> +	var/datum/autolathe_recipe/recipe = new
Чисто в теории, твой вариант медленнее. Раньше создавалась только нужная сущность, а теперь у тебя будет всегда создаваться объект от `datum/autolathe_recipe` и в некоторых случаях ниже будет уже ПЕРЕсоздаваться объект класса `datum/autolathe_recipe/stack`. 

И можно сказать, в твоем случае получилось плохое сокращение кода

2021-03-20 14:36 UTC, Ahion commented on code/game/machinery/autolathe.dm
> +	var/datum/autolathe_recipe/recipe = new
Есть логика в твоих словах. Исправил.

2021-03-22 14:17 UTC, UDaV73rus requested changes
К кодерским спрайтам отношусь с пониманием, но хотя бы их цвета нужно привести к совпадению с патронами.

Если появятся помощники, картинка им:
![image](https://user-images.githubusercontent.com/33157992/112003111-a69e9080-8b31-11eb-9fa5-811d8af3481c.png)

2021-03-22 19:44 UTC, volas commented
^ можешь попросить в спрайтерском канале в дискорде, что бы кто нибудь помог

2021-04-02 12:39 UTC, Ahion commented
Замечания исправил. Цвет патронов теперь совпадает с коробкой. Обновил описание ПРа.

2021-04-02 12:41 UTC, KIBORG04 commented
Ну значит зову аппруверов

2021-04-02 14:59 UTC, UDaV73rus approved these changes
Не забудь сообщить в ченжлоге что поменял цвет слагов и дартов

2021-04-02 15:09 UTC, Ahion commented
> Не забудь сообщить в ченжлоге что поменял цвет слагов и дартов

Сообщил

2021-04-03 12:38 UTC, Ahion commented
По просьбе Dedawe добавил возможность класть коробки патронов в **combat belt** и **security belt**

Пока Draft, жду новые спрайты

2021-04-04 10:37 UTC, Ahion commented
Спасибо DedYarick за новые спрайты коробок. Добавлена ещё одна коробка для стан слагов. В протолате РнД теперь будет печататься эта коробка, а не по одному патрону.

2021-04-05 14:41 UTC, KIBORG04 commented
Вроде как опять новые спрайты, апруваем

2021-04-05 15:56 UTC, UDaV73rus approved these changes

2021-04-06 15:12 UTC, merged