Увеличение объема мерного стаканчика (Beaker) с 50 до 60
TauCetiStation/TauCetiClassic pull request #6970
Opened 2021-03-25 11:18 UTC by Rolt146

## Описание изменений
Теперь химические стаканчики (beaker), обычные и криостазисные стали более вместительными
## Почему и что этот ПР улучшит
Теперь мелкие хим стаканчиками будут чаще пользоваться, и те обретут ценность у медиков, взамен хим бутылочкам по 30 юнитов. Так-же ими будет удобнее пользоваться и в химии, чем просто пыле и мусоросборники для реагентов
## Авторство
Rolt146
## Чеинжлог
:cl:
 - rscadd: Увеличение объема маленьких мерных и криостазисных мензурок с 50->60 юнитов.

2021-03-25 11:18 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2021-03-25 12:02 UTC, TechCatOther requested changes

2021-03-25 12:02 UTC, TechCatOther commented on code/modules/reagents/reagent_containers/glass.dm
> +	volume = 60
Значение наследуется от /obj/item/weapon/reagent_containers/glass/beaker. Не нужно копипастить.

2021-03-25 12:02 UTC, TechCatOther commented on code/modules/reagents/reagent_containers/glass.dm
> +	possible_transfer_amounts = list(5,10,15,25,30,60)
Аналогично

2021-03-25 12:13 UTC, TechCatOther commented
И наверное тег в чейнджлоге balance более верен будет.

2021-03-25 17:32 UTC, Rolt146 commented
Исправил

2021-03-25 17:40 UTC, KIBORG04 commented on code/modules/reagents/reagent_containers/glass.dm
> +	volume = 60
Тебя попросили не делать это в `/obj/item/weapon/reagent_containers/glass` а просто убрать у тех бикеров волюм и поссибл трансфер амоунт, так как нужные классы были у родительского прока, а не потому что нужно изменить цифры у родителя родительского прока.

2021-03-25 20:47 UTC, TechCatOther commented on code/modules/reagents/reagent_containers/glass.dm
> +	volume = 60
Просто удали volume и possible_transfer_amounts в /obj/item/weapon/reagent_containers/glass/beaker/noreact
Тогда их значения будут взяты из /obj/item/weapon/reagent_containers/glass/beaker

А то со стаканами весь бар и кухня завязаны.

2021-03-26 07:55 UTC, Rolt146 commented
Вернул как было у родителя, к обычному бикеру вернул 60 объема

2021-03-26 14:14 UTC, KIBORG04 commented on code/modules/reagents/reagent_containers/glass.dm
> -	desc = "A cryostasis beaker that allows for chemical storage without reactions. Can hold up to 50 units."
А ты сильно расстроишься, если я попрошу тебя генерировать в описании `Can hold up to [volume] units` ?

2021-03-26 14:59 UTC, TechCatOther commented
Вообщем ничего критичного, все работает как и положено на локальном.
Нашел по коду пару мест, где "хорошие" люди захардкодили 50 в коде. Просто будет тара немного не полная.

code\modules\research\xenoarchaeology\chemistry.dm
```
/obj/item/weapon/reagent_containers/glass/beaker/tungsten/atom_init()
	. = ..()
	reagents.add_reagent("tungsten",50)
	update_icon()
```
code\game\objects\items\weapons\grenades\chem_grenade.dm
```
/obj/item/weapon/grenade/chem_grenade/metalfoam/atom_init()
	. = ..()
	var/obj/item/weapon/reagent_containers/glass/beaker/B1 = new(src)
	var/obj/item/weapon/reagent_containers/glass/beaker/B2 = new(src)

	B1.reagents.add_reagent("aluminum", 30)
	B2.reagents.add_reagent("foaming_agent", 10)
	B2.reagents.add_reagent("pacid", 10)
```

2021-03-26 15:00 UTC, TechCatOther approved these changes

2021-03-26 16:12 UTC, Rolt146 commented on code/modules/reagents/reagent_containers/glass.dm
> -	desc = "A cryostasis beaker that allows for chemical storage without reactions. Can hold up to 50 units."
Скорее всего да, ибо как-то не задается у меня писать переменные в тексте описания

2021-03-26 18:28 UTC, merged