Перевод аноносов станции
TauCetiStation/TauCetiClassic pull request #6979
Opened 2021-03-27 20:09 UTC by TechCatOther

## Описание изменений
Перевод анонсов. Часть взята из старого ПР #6507.

Спасибо за помощь в дискорде. 👍😊

## Почему и что этот ПР улучшит
Анонсы теперь на русском и понятны всем

## Авторство
TechCat и наш дискорд канал переводчиков
## Чеинжлог
:cl: TechCat
 - ru: Перевод анонсов станции

2021-03-27 20:16 UTC, TechCatOther commented
Немного задел #6930

2021-03-27 20:33 UTC, volas commented on code/datums/announcements/centcomm.dm
> +	title = "Уточнение Центрального Командования"
"Уточнение" как-то совсем не официально звучит. Я бы предложил "Оповещение" или что-то такое.

2021-03-27 20:35 UTC, volas commented on code/datums/announcements/gamemode.dm
> +	subtitle = "Мониторинг Сети"
Сетевой мониторинг?

2021-03-27 20:36 UTC, TechCatOther commented on code/datums/announcements/gamemode.dm
> +	message = "Присутсвие ОБР в регионе требует все местные аварийные ресурсы. Сейчас отряд быстрого реагирования не может быть вызван."
ERP как перевести?

2021-03-27 20:39 UTC, KIBORG04 commented on code/datums/announcements/gamemode.dm
> +	message = "Присутсвие ОБР в регионе требует все местные аварийные ресурсы. Сейчас отряд быстрого реагирования не может быть вызван."
ОБР, да, даже в общении игроков есть

2021-03-27 20:41 UTC, TechCatOther commented on code/datums/announcements/gamemode.dm
> +	message = "Присутсвие ОБР в регионе требует все местные аварийные ресурсы. Сейчас отряд быстрого реагирования не может быть вызван."
Это ER**T**

2021-03-27 20:41 UTC, volas commented on code/datums/announcements/gamemode.dm
> +	subtitle = "Тревога. Биоугроза"
Вообще, в российском ЧС есть готовые примеры оповещения о тревогах, можно брать пример. Быстрым гуглежом нашел что-то вроде 
“Внимание! Внимание! Граждане! Воздушная тревога! Воздушная тревога!” http://www.pobedasp.tomsk.ru/content/opoveshhenie_i_informirovanie_naselenija
Там же прочие “Химическая тревога”  и т.д.

Так что, я бы предложил, может что-то вроде "Биологическая тревога" (возможно и "Химическая", я не знаю, у нас наверняка есть что-то соответствующее "Biohazard"). 

Ну и так любые другие тревоги.

2021-03-27 20:42 UTC, KIBORG04 commented on code/datums/announcements/gamemode.dm
> +	message = "Присутсвие ОБР в регионе требует все местные аварийные ресурсы. Сейчас отряд быстрого реагирования не может быть вызван."
А что такое ерп?

2021-03-27 20:42 UTC, TechCatOther commented on code/datums/announcements/gamemode.dm
> +	subtitle = "Тревога. Биоугроза"
Так изначально и планировал, но вот не все идет как прилагательное. Например, аномальная тревога.

2021-03-27 20:44 UTC, volas commented on code/datums/announcements/gamemode.dm
> +	subtitle = "Тревога. Биоугроза"
ха, может быть. Надо посмотреть, может в сталкере что-то было :D

2021-03-27 20:44 UTC, TechCatOther commented on code/datums/announcements/gamemode.dm
> +	message = "Присутсвие ОБР в регионе требует все местные аварийные ресурсы. Сейчас отряд быстрого реагирования не может быть вызван."
Erotic Roleplay

2021-03-27 20:53 UTC, volas commented on code/datums/announcements/gamemode.dm
> +	message = "Присутсвие ОБР в регионе требует все местные аварийные ресурсы. Сейчас отряд быстрого реагирования не может быть вызван."
> ERP

Нужно искать откуда корни, мне кажется это чья-то пасхалка. Мой любимый бор станции загрифонили, а ерп не тронули.

2021-03-27 20:55 UTC, KIBORG04 commented on code/datums/announcements/gamemode.dm
> +	message = "Присутсвие ОБР в регионе требует все местные аварийные ресурсы. Сейчас отряд быстрого реагирования не может быть вызван."
Тут наверное про ерт говорится, так как выше
```
/datum/announcement/centcomm/mutiny/noert
	name = "Mutiny: ERT is busy
```

2021-03-27 20:55 UTC, AndroBetel commented on code/datums/announcements/gamemode.dm
> +	message = "Присутсвие ОБР в регионе требует все местные аварийные ресурсы. Сейчас отряд быстрого реагирования не может быть вызван."
нет, там именно что кто-то ерпшит и все обр на это ерп сбежались и мы не можем вам отправить

2021-03-27 20:57 UTC, KIBORG04 commented on code/datums/announcements/gamemode.dm
> +	message = "Присутсвие ОБР в регионе требует все местные аварийные ресурсы. Сейчас отряд быстрого реагирования не может быть вызван."
да и вообще я удалил этот анонс в https://github.com/TauCetiStation/TauCetiClassic/pull/6909

2021-03-27 21:04 UTC, TechCatOther commented on code/datums/announcements/gamemode.dm
> +	subtitle = "Мониторинг Сети"
Поправил

2021-03-27 21:04 UTC, TechCatOther commented on code/datums/announcements/gamemode.dm
> +	message = "Присутсвие ОБР в регионе требует все местные аварийные ресурсы. Сейчас отряд быстрого реагирования не может быть вызван."
Поправил, ЭРИ

2021-03-27 21:04 UTC, TechCatOther commented on code/datums/announcements/centcomm.dm
> +	title = "Уточнение Центрального Командования"
Поправил

2021-03-28 02:48 UTC, TechCatOther commented on code/datums/announcements/gamemode.dm
> +			"Взломшик слишком быстр, он обходит все попытки его выследить. Никто не может быть так быстр..."
Вот тут сломался намек, надеюсь не критично. Ведь в русском он - ИИ

2021-03-28 04:48 UTC, kiVts reviewed
Ну вот так как то и прочитай название ПР но медленно....

2021-03-28 04:48 UTC, kiVts commented on code/datums/announcements/gamemode.dm
> +			"Взломшик слишком быстр, он обходит все попытки его выследить. Никто не может быть так быстр..."
Опечатка во взломщике.
"Он обходит все наши попытки его отследить" Если переводить дословно

2021-03-28 04:48 UTC, kiVts commented on code/datums/announcements/gamemode.dm
> +			"Кажется, кто-то пытается взломать ваши системы. Сообщим вам когда получим больше информации."
"Мы" вырезали злодеи

2021-03-28 04:48 UTC, kiVts commented on code/datums/announcements/station.dm
> +	message = "Был аннулирован доступ на все шлюзы."
Что это вообще и почему тут ничего нет

2021-03-28 04:48 UTC, kiVts commented on code/datums/announcements/station.dm
> +	message = "Переход экипажа начат. Шаттл вызван. Он прибудет в течении нескольких минут."
не переход а что-то ближе к транспортировке или смена
"Смена экапажа начата"

2021-03-28 04:51 UTC, TechCatOther commented on code/datums/announcements/gamemode.dm
> +			"Кажется, кто-то пытается взломать ваши системы. Сообщим вам когда получим больше информации."
Было изначально, но когда читал почувствовал привкус плохого перевода. В русском не так часто ставят в начале частицы.

2021-03-28 04:52 UTC, TechCatOther commented on code/datums/announcements/station.dm
> +	message = "Был аннулирован доступ на все шлюзы."
Сделал так уже
```
	message = "Был аннулирован обслуживающий доступ на все шлюзы."
```
Пока не выкладывал.

2021-03-28 04:53 UTC, kiVts commented on code/datums/announcements/gamemode.dm
> +			"Кажется, кто-то пытается взломать ваши системы. Сообщим вам когда получим больше информации."
И почему Caution что осторожно переводят как внимание.
Так-же It seems  можно перевести как походу или вероятно

2021-03-28 04:54 UTC, TechCatOther commented on code/datums/announcements/station.dm
> +	message = "Переход экипажа начат. Шаттл вызван. Он прибудет в течении нескольких минут."
Изначально хотел смена, но никто же не прилетел на смену. Сменять некому. Только улетают. Можно еще "перевозка", "перевод".

2021-03-28 04:57 UTC, kiVts commented on code/datums/announcements/gamemode.dm
> +			"Взломшик слишком быстр, он обходит все попытки его выследить. Никто не может быть так быстр..."
И Intruder переводится как незваный гость или незванец однако хацкер тут подходит

2021-03-28 05:04 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2021-03-28 05:11 UTC, TechCatOther commented on code/datums/announcements/gamemode.dm
> +			"Взломшик слишком быстр, он обходит все попытки его выследить. Никто не может быть так быстр..."
Спасибо. Взломщика поправил. 
Посмотрел различия между "выследить" и "отследить". Почти одинаковые, но "выследить" больше к охоте, а "отследить" к наблюдению. Поэтому оставлю.

2021-03-28 05:25 UTC, SvSvyat commented on code/datums/announcements/gamemode.dm
> +			"Взломшик слишком быстр, он обходит все попытки его выследить. Никто не может быть так быстр..."
Может, "достаточно тревожно" вместо "сильно беспокоит", чтобы была однородность?

2021-04-03 16:53 UTC, KrisPrs commented on code/datums/announcements/gamemode.dm
> +			"Взломшик слишком быстр, он обходит все попытки его выследить. Никто не может быть так быстр..."
Автор, что насчёт...
-"Взломшик слишком быстр, он обходит все попытки его выследить. Никто не может быть так быстр..."
+"Взломшик слишком быстр, он обходит все попытки его выследить. Это нечеловеческая скорость..."
Или чего-то в этом роде
Намёк сохраняется, образное выражение тоже...

2021-04-03 19:17 UTC, TechCatOther commented on code/datums/announcements/gamemode.dm
> +			"Взломшик слишком быстр, он обходит все попытки его выследить. Никто не может быть так быстр..."
Спасибо, изменю на предложенный

2021-04-15 21:41 UTC, atik1n reviewed
Это малая часть того, что я нашёл на данный момент, чтобы оживить ПР. Подробнее погляжу в ближайшее время

2021-04-15 21:41 UTC, atik1n commented on code/datums/announcements/station.dm
> +	subtitle = "Отказоустойчивая Система [station_name_ru()]"
С каких пор `Fail-Safe` стал отказоустойчивой системой?

2021-04-15 21:41 UTC, atik1n commented on code/modules/events/infestation.dm
> +	"кухне"                 = /area/station/civilian/kitchen, \
Я бы тут предложил сначала сделать список локаций, а потом натягивать на анонсы

2021-04-15 21:41 UTC, atik1n commented on code/modules/research/message_server.dm
> +	var/id_auth = "Неаутентифицированный"
Ты уверен, что эти ключи используются именно в этом роде?

2021-04-15 21:41 UTC, atik1n commented on maps/boxstation/boxstation.dmm
> +	department = "�?�?";
У вас кодировка полетела

2021-04-15 21:41 UTC, atik1n commented on maps/gamma/gamma.dmm
> +	department = "ВКД";
Применимо ли ВКД к станции?

2021-04-16 09:33 UTC, TechCatOther commented on code/datums/announcements/station.dm
> +	subtitle = "Отказоустойчивая Система [station_name_ru()]"
![изображение](https://user-images.githubusercontent.com/378937/115004867-f150c580-9eaf-11eb-8a3f-78b27411870c.png)

2021-04-16 09:34 UTC, TechCatOther commented on maps/boxstation/boxstation.dmm
> +	department = "�?�?";
Имеенно поэтому еще в драфте ПР. Хочу вынести в код игры, поскольку перевод на карте ломает кодировку при мерже карт.

2021-04-16 09:34 UTC, TechCatOther commented on maps/gamma/gamma.dmm
> +	department = "ВКД";
Есть лучше вариант? По мне идеально заходит. На МКС тоже есть ВКД

2021-04-16 09:35 UTC, TechCatOther commented on code/modules/research/message_server.dm
> +	var/id_auth = "Неаутентифицированный"
Это слова попадают только в консоль управления сервера сообщений

2021-04-16 09:38 UTC, TechCatOther commented on code/modules/events/infestation.dm
> +	"кухне"                 = /area/station/civilian/kitchen, \
Не совсем понял. Нужно перевести сначала локации? Нужно вынести все локации в отдельный список?
Если оставить как тут - не будет в анонсе о нашествии насекомых английских слов внутри русского предложения

2021-04-16 09:40 UTC, atik1n commented on code/datums/announcements/station.dm
> +	subtitle = "Отказоустойчивая Система [station_name_ru()]"
![image](https://user-images.githubusercontent.com/14612180/115005693-cf0b7780-9eb0-11eb-9b57-04ec13ed6469.png)
Контекст. Твоя отказоустойчивая система только что отказала и Доктор Дью бы прокричал "проснись, ты срёшь!"
Эти именно система зашиты от образования Чёрной Дыры сработала же, текст анонса почитай

2021-04-16 09:44 UTC, TechCatOther commented on code/datums/announcements/station.dm
> +	subtitle = "Отказоустойчивая Система [station_name_ru()]"
Кхм. "система зашиты от образования Чёрной Дыры". Тут более узко. Имеется в виду в целом система предотвращения аварий.

2021-04-16 09:45 UTC, TechCatOther commented on code/datums/announcements/station.dm
> +	subtitle = "Отказоустойчивая Система [station_name_ru()]"
Не она отказала, а система гравитации. Данная система ее выключила.

2021-04-16 10:48 UTC, TechCatOther commented on code/datums/announcements/station.dm
> +	subtitle = "Отказоустойчивая Система [station_name_ru()]"
Так лучше?
```suggestion
	subtitle = "Система Предотвращения Аварий [station_name_ru()]"
```

2021-04-17 00:49 UTC, TechCatOther commented
Готово с консолью. Сделал просто разные типы под каждый отдел.

2021-04-18 17:34 UTC, KIBORG04 commented on code/game/machinery/requests_console.dm
> +#undef RC_ASSIST_SUPPLY_INFO
```suggestion
#undef RC_ASSIST_SUPPLY_INFO

```

2021-04-18 17:40 UTC, volas commented on code/game/machinery/requests_console.dm
> +	department_genitive = "Кабинета Капитана"
Я всё равно думаю, что стоило бы в /area/ это прописать. Пригодилось бы даже для анонсов тут рядом,
 
> Обнаружена активация ядерной боеголовки в [initial(A.name)]. Кто-то пытается взорвать станцию!

2021-04-22 17:34 UTC, KIBORG04 commented
Я не особо помогу в коррекции перевода и ревью всего этого текста, поэтому раз уж ты и ![image](https://user-images.githubusercontent.com/26389417/115760441-0c3ca180-a3aa-11eb-9a7e-aa5e0d831cc5.png), и ![image](https://user-images.githubusercontent.com/26389417/115760486-178fcd00-a3aa-11eb-92fc-97e2c3dfaede.png) то разрешаю по готовности тебе все это самому замержить

2021-04-26 19:00 UTC, da-kiselev commented on code/datums/announcements/centcomm.dm
> +	message = "Похоже, отряд быстрого реагирования был запрошен на КСН Исход. Мы подготовим и отправим их в кратчайшие сроки."
Кек, «...К сожалению, мы не сможем его отправить в ближайшем будущем»

2021-04-26 19:01 UTC, da-kiselev commented on code/datums/announcements/centcomm.dm
> +	message = "Похоже, отряд быстрого реагирования был запрошен на [station_name_ru()]. Мы подготовим и отправим их в кратчайшие сроки."
Тут же тоже отклонили.

2021-04-26 19:05 UTC, da-kiselev commented on code/datums/announcements/gamemode.dm
> +	message = "Ваши гости улетают, Станция 13 - двигаются слишком быстро, мы не можем навестись на них. " + \
«..., Исход — движутся слишком быстро»

2021-05-01 01:53 UTC, volas requested changes

2021-05-01 01:53 UTC, volas commented on code/datums/announcements/station.dm
> +	message = "Был аннулирован обслуживающий доступ на все шлюзы."
```suggestion
	message = "Был аннулирован доступ на все технические коридоры."
```
Аирлоки переводим как шлюзы, или двери? Это нужно обсудить и зафиксировать в словаре, вместе с техтоннелями/коридорами.

2021-05-01 01:53 UTC, volas commented on code/datums/announcements/station.dm
> +	message = "Был установлен обслуживающий доступ на все шлюзы."
```suggestion
	message = "Требование доступа вернулось на все технические коридоры."
```

2021-05-01 01:53 UTC, volas commented on code/datums/announcements/station.dm
> +	message = "Смена экипажа начата. Шаттл вызван. Он прибудет в течении нескольких минут."
```suggestion
	message = "Трансфер экипажа инициирован. Шаттл вызван. Он прибудет в течении нескольких минут."
```
что бы не ломать мозг о "Смене"-замене экипажа и "Смене"-временном рабочем участке. Вторая просто как раз в этом контексте и заканчивается.

2021-05-01 01:53 UTC, volas commented on code/datums/announcements/station.dm
> +	message = "Смена экипажа начата. Шаттл вызван. Он прибудет через [shuttleminutes2text()]."
```suggestion
	message = "Трансфер экипажа инициирован. Шаттл вызван. Он прибудет через [shuttleminutes2text()]."
```

...

2021-05-01 01:53 UTC, volas commented on code/datums/announcements/station.dm
> +	message = "Запланированный Шаттл Транспортировки Экипажа пристыковался к станции. Отправление примерно через [shuttleminutes2text()]."
Тут бы не помешало какое-то другое слово кроме "Запланированный", что бы указать что это по регулярному расписанию а не специально запланированный шаттл. Но я без идей.

2021-05-01 01:53 UTC, volas commented on code/datums/announcements/station.dm
> +	message = "Шаттл Транспортировки Экипажа покинул станцию. Остается [shuttleminutes2text()] до стыковки шаттла к Центральному Командованию."
```suggestion
	message = "Шаттл Транспортировки Экипажа покинул станцию. Примерно [shuttleminutes2text()] до стыковки шаттла к Центральному Командованию."
```

2021-05-01 01:53 UTC, volas commented on code/datums/announcements/station.dm
> +	message = "Эвакуационный Шаттл покинул станцию. Остается [shuttleminutes2text()] до стыковки шаттла к Центральному Командованию."
```suggestion
	message = "Эвакуационный Шаттл покинул станцию. Примерно [shuttleminutes2text()] до стыковки шаттла к Центральному Командованию."
```

2021-05-01 01:53 UTC, volas commented on code/datums/announcements/station.dm
> +	subtitle = "Внимание! Код безопасности повышен до синего"
```suggestion
	subtitle = "Внимание! Код безопасности понижен до синего"
```
возможно еще синий/зеленый нужно с заглавной буквы

2021-05-01 01:53 UTC, volas commented on code/game/machinery/requests_console.dm
> +				dat += text("Вы сейчас можите авторизировать ваше сообщение приложив ID или печать.<BR><BR>")
```suggestion
				dat += text("Теперь вы можете авторизовать ваше сообщение, приложив ID или печать.<BR><BR>")
```

2021-05-01 01:53 UTC, volas commented on code/game/machinery/requests_console.dm
> +				dat += text("<A href='?src=\ref[src];department=[url_encode(to_dpt)]'>Отравить</A><BR>");
> url_encode

Стоит валидировать там, где оно пришло

2021-05-01 01:53 UTC, volas commented on code/game/machinery/requests_console.dm
> +		to_dpt = href_list["write"]  //write contains the string of the receiving department's name
```suggestion
		to_dpt = sanitize(href_list["write"])  //write contains the string of the receiving department's name
```

2021-05-01 01:53 UTC, volas commented on code/game/machinery/requests_console.dm
> +		var/recipient_from_field = href_list["department"]
```suggestion
		var/recipient_from_field = sanitize(href_list["department"])
```

2021-05-01 01:53 UTC, volas commented on code/game/machinery/requests_console.dm
> +			audible_message("[bicon(src)] *Консоль Запроса пикнула: 'ЗАМЕЧАНИЕ: Сервер не обнаружен!'")
```suggestion
			audible_message("[bicon(src)] *Консоль Запроса пищит: 'ЗАМЕЧАНИЕ: Сервер не обнаружен!'")
```
хотя может это слово вообще лишнее

2021-05-01 01:53 UTC, volas commented on code/game/machinery/requests_console.dm
> +			MS.send_rc_message(href_list["department"], department, log_msg, msgStamped, msgVerified, priority, department_genitive)
Тут первым точно department а не recipient_from_field?

2021-05-01 01:53 UTC, volas commented on code/game/machinery/requests_console.dm
> +	department = "Кабинет ДИР"
Нам нужно будет какие-то публичные анонсы с этими переводами писать, как правильно теперь того или иного называть, и вешать ссылку на каждом сервере.

2021-05-01 01:53 UTC, volas commented on code/modules/events/infestation.dm
> +	"кухне"                 = /area/station/civilian/kitchen, \
Тут я бы вновь предложил как-то складывать это всё к объектам зон, что бы не повторять потом по билду. Хотя ПР уже объемный и это достойно отдельного.

2021-05-01 01:53 UTC, volas commented on code/modules/events/rogue_drones.dm
> +		msg = "Неизвестные хакеры атаковали боевое крыло дронов, запущенное с ВКН Икар. Если обнаружите их в данной области, приближаться с осторожностью."
Стоит перетащить в ``/datum/announcement/centcomm/icarus_lost/play()``
а то анонс размазывается ~~во времени и пространстве~~ по нескольким файлам

2021-05-01 01:53 UTC, volas commented on code/modules/events/rogue_drones.dm
> +		msg = "Контроль дронов ВКН Икар разочарован в потере боевого крыла. Выжившие дроны будут восстановлены."
и это тоже

2021-05-28 09:44 UTC, BesumniiChebureck requested changes

2021-05-28 09:44 UTC, BesumniiChebureck commented on code/datums/announcements/events.dm
> +	message = "КСН Исход сейчас проходит сквозь кольцо космической пыли."
Лучше всё же ``сквозь облако`` или ``сквозь пояс``.

2021-05-30 16:06 UTC, volas commented
@TechCatOther посмотришь предложения по ревью? Или я или кто нибудь другой можем по своему усмотрению поправить и смержить.

2021-06-18 19:04 UTC, logimy commented on code/datums/announcements/events.dm
> +	message = "Биосканеры зафиксировали, что что-то размножается где-то на станции. Вычистите это, пока не начало влиять на производительность."
«Что что-то где-то» 🧐

2021-06-18 19:05 UTC, logimy commented
А анонсы такие неформальные специально или так получилось?

2021-06-18 19:17 UTC, volas commented
> А анонсы такие неформальные специально или так получилось?

пиши в ревью

2021-06-18 20:32 UTC, logimy commented
> > А анонсы такие неформальные специально или так получилось?
> 
> 
> 
> пиши в ревью

Еперный, не могу больше с телефона печатать, уже пальцы болят. Постараюсь завтра не забыть закончить.

2021-06-19 04:41 UTC, Haggerd commented on code/datums/announcements/events.dm
> +	message = "Биосканеры зафиксировали, что что-то размножается где-то на станции. Вычистите это, пока не начало влиять на производительность."
> «Что что-то где-то» 🧐

А оригинал не смущает? "that something somewhere"

2021-06-19 08:36 UTC, logimy requested changes
Драный рот этих двойных анонсов, ептвоюмать.
Добавил везде _(кажется)_ свои варианты переводов. Они не дословные, а контекстные и более формальные

2021-06-19 08:36 UTC, logimy commented on code/datums/announcements/station.dm
> +	message = "Эвакуационный Шаттл пристыковался к станции. У вас есть [shuttleminutes2text()] для посадки на Эвакуационный Шаттл."
```suggestion
	message = "Эвакуационный шаттл пристыковался к станции. У вас есть [shuttleminutes2text()] для посадки."
```

2021-06-19 08:36 UTC, logimy commented on code/datums/announcements/station.dm
> +	message = "Эвакуационный Шаттл покинул станцию. Он прибудет на Центральное Командование через несколько минут."
```suggestion
	message = "Эвакуационный шаттл покинул станцию. Стыковка со станцией Центрального Командования произойдет через несколько минут."
```

2021-06-19 08:36 UTC, logimy commented on code/datums/announcements/station.dm
> +	message = "Эвакуационный Шаттл покинул станцию. Остается [shuttleminutes2text()] до стыковки шаттла к Центральному Командованию."
```suggestion
	message = "Эвакуационный шаттл покинул станцию. Стыковка со станцией Центрального Командования произойдет через [shuttleminutes2text()] ."
```

2021-06-19 08:36 UTC, logimy commented on code/datums/announcements/station.dm
> +	subtitle = "Внимание! Достигнут код безопасности дельта!"
```suggestion
	subtitle = "Внимание! Код безопасности дельта!"
```

Не надо тут переводить "ричед". В ру хватит просто "Код безопасности дельта"

2021-06-19 08:36 UTC, logimy commented on code/datums/announcements/station.dm
> +	subtitle = "Внимание! Достигнут код безопасности дельта!"
```suggestion
	subtitle = "Внимание! Код безопасности дельта!"
```

Не надо тут переводить "ричед". В ру хватит просто "Код безопасности дельта"

2021-06-19 08:36 UTC, logimy commented on code/game/machinery/requests_console.dm
> +				dat += text("<B>Оповещение станции</B><BR><BR>")
```suggestion
				dat += text("<B>Система оповещения станции</B><BR><BR>")
```

2021-06-19 08:36 UTC, logimy commented on code/game/machinery/requests_console.dm
> +			audible_message("[bicon(src)] *Консоль Запроса пикнула: 'ЗАМЕЧАНИЕ: Сервер не обнаружен!'")
```suggestion
			audible_message("[bicon(src)] *Уведомление консоли запроса: 'ЗАМЕЧАНИЕ: Сервер не обнаружен!'")
```

Может так?

2021-06-19 08:36 UTC, logimy commented on code/game/machinery/requests_console.dm
> +				to_chat(user, "<span class='warning'>Вы не авторизованы для отправки оповещений на станцию.</span>")
```suggestion
				to_chat(user, "<span class='warning'>У вас нет доступа к системе оповещений.</span>")
```

2021-06-19 08:36 UTC, logimy commented on code/modules/events/rogue_drones.dm
> +		msg = "Боевое крыло дронов не смогло вернуться с зачистки данного сектора, при обнаружении приближаться с осторожностью."
```suggestion
		msg = "Звено боевых дронов не вернулось с зачистки данного сектора. Если вы обнаружили боевого дрона, не приближайтесь к нему."
```

2021-06-19 08:36 UTC, logimy commented on code/modules/events/rogue_drones.dm
> +		msg = "На ВКН Икар был потерян контакт с боевым крылом дронов. При обнаружении их в этой области, приближаться с осторожностью."
```suggestion
		msg = "ВКН «Икар» потерял контакт с звеном боевых дронов. Если вы обнаружили боевого дрона, не приближайтесь к нему."
```

2021-06-19 08:36 UTC, logimy commented on code/modules/events/rogue_drones.dm
> +		msg = "Неизвестные хакеры атаковали боевое крыло дронов, запущенное с ВКН Икар. Если обнаружите их в данной области, приближаться с осторожностью."
```suggestion
		msg = "Зафиксирован взлом звена боевых дронов, запущенных с ВКН «Икар». Если вы обнаружили боевого дрона, не приближайтесь к нему."
```

2021-06-19 08:36 UTC, logimy commented on code/modules/events/rogue_drones.dm
> +		msg = "Контроль дронов на ВКН Икар докладывает о восстановлении контроля над сбойным боевым крылом."
```suggestion
		msg = "Операторы дронов на борту ВКН «Икар» докладывают о успешном восстановлении контроля над сбойными единицами. Космическое пространство вокруг вашей станции снова безопасно для проведения работ."
```

2021-06-19 08:36 UTC, logimy commented on code/modules/events/rogue_drones.dm
> +		msg = "Контроль дронов ВКН Икар разочарован в потере боевого крыла. Выжившие дроны будут восстановлены."
Ну ёмаё... сколько можно дубликатов анонсов?!

```suggestion
		msg = "Операторы дронов на борту ВКН «Икар» зарегистрировали факт потери боевых дронов. Доступ к функционирующим единицам был восстановлен и оставшиеся дроны были возвращены на борт."
```

2021-06-19 08:36 UTC, logimy commented on code/modules/research/message_server.dm
> +						Console.audible_message("[bicon(Console)] **Консоль Запроса пикнула: 'ПРИОРИТЕТНОЕ сообщение от [from_desc]'")
```suggestion
						Console.audible_message("[bicon(Console)] **Уведомление консоли запроса: 'ПРИОРИТЕТНОЕ сообщение от [from_desc]'")
```

2021-06-19 08:36 UTC, logimy commented on code/modules/research/message_server.dm
> +						Console.audible_message("[bicon(Console)] **Консоль Запроса пикнула: 'Сообщение от [from_desc]'")
```suggestion
						Console.audible_message("[bicon(Console)] **Уведомление консоли запроса: 'Сообщение от [from_desc]'")
```

2021-06-19 08:42 UTC, volas commented
@logimy только это перевод, а не сочинительство и переписывание. Тебе стоит это потом в другой PR вынести.

2021-06-19 08:45 UTC, logimy commented
> Тебе стоит это потом в другой PR вынести.

кк, если этот примут - сделаю свой

2021-06-22 16:43 UTC, TechCatOther commented on code/datums/announcements/centcomm.dm
> +	subtitle = "Оповещение НаноТрейзен"
Это потому, что там формируется аноносы с панелей по такому же принципу. Что бы была общая стилистика оставить везде так. Если делать "оповещение" -> "рапорт" то это везде.

2021-06-22 16:44 UTC, TechCatOther commented on code/datums/announcements/centcomm.dm
> +	message = "Похоже, отряд быстрого реагирования был запрошен на КСН Исход. Мы подготовим и отправим их в кратчайшие сроки."
Лучше тогда уже сделать тут оповещение в начале.

2021-06-22 16:45 UTC, TechCatOther commented on code/datums/announcements/centcomm.dm
> +	message = "Похоже, отряд быстрого реагирования был запрошен на [station_name_ru()]. Мы подготовим и отправим их в кратчайшие сроки."
Тут теряется надежда пока читаешь первое предложение. А второго не видел =)

2021-06-22 16:46 UTC, TechCatOther commented on code/datums/announcements/events.dm
> +	subtitle = "Тревога. Аномалия"
Есть вариант с общем стилем, совпадающим с остальными тревогами? Иначе будет выделятся.

2021-06-22 16:47 UTC, TechCatOther commented on code/datums/announcements/events.dm
> +	message = "На сканерах дальнего действия обнаружена атмосферная аномалия. Ожидается снижение температуры станции."
На станции есть данные инструкции где-либо? Они нужны для погружения в мир.

2021-06-22 17:04 UTC, 4310V343k commented on code/modules/events/rogue_drones.dm
> +		msg = "Контроль дронов ВКН Икар разочарован в потере боевого крыла. Выжившие дроны будут восстановлены."
have been - были, а не будут

2021-06-22 17:04 UTC, TechCatOther commented on code/datums/announcements/events.dm
> +	message = "Центком запустил сброс контроля доступа шлюзов. Пожалуйста, найдите время познакомиться с вашими коллегами."
Исправил, но центком оставил. У меня язык сломается так говорить - центрком. 4 согласных подряд еще не переживало не одно сокращение нормально.

2021-06-22 17:07 UTC, 4310V343k commented on code/datums/announcements/centcomm.dm
> +	message = "Похоже, отряд быстрого реагирования был запрошен на [station_name_ru()]. Мы подготовим и отправим их в кратчайшие сроки."
were unable to - У нас не было возможности, а не Мы (будущее время)

2021-06-22 17:17 UTC, TechCatOther commented on code/datums/announcements/centcomm.dm
> +	message = "Похоже, отряд быстрого реагирования был запрошен на [station_name_ru()]. Мы подготовим и отправим их в кратчайшие сроки."
`Похоже, отряд быстрого реагирования был запрошен на [station_name_ru()]. К сожалению, мы не сможем его отправить сейчас.`

2021-06-22 17:18 UTC, TechCatOther commented on code/datums/announcements/centcomm.dm
> +	message = "Похоже, отряд быстрого реагирования был запрошен на [station_name_ru()]. Мы подготовим и отправим их в кратчайшие сроки."
А в чем, простите, изменяется смысл?

2021-06-22 17:19 UTC, 4310V343k commented
Я уверен, что есть другие какие-нибудь проблемы именно в переводе, а не переформулировке, вроде тех двух, что я указал, но переводить 600 строк мне лень, спасибо

2021-06-22 17:32 UTC, TechCatOther commented on code/modules/research/message_server.dm
> +						Console.audible_message("[bicon(Console)] **Консоль Запроса пикнула: 'ПРИОРИТЕТНОЕ сообщение от [from_desc]'")
Вот когда я читал первый варинат, сразу представил как пикает на стене консоль. Тут непонятно, как пришло оно. Стоит того?

2021-06-22 17:34 UTC, KIBORG04 commented on code/modules/research/message_server.dm
> +						Console.audible_message("[bicon(Console)] **Консоль Запроса пикнула: 'ПРИОРИТЕТНОЕ сообщение от [from_desc]'")
Пискнула, не пикнула. Наверное.

2021-06-22 17:37 UTC, TechCatOther commented on code/datums/announcements/events.dm
> +	message = "Биосканеры зафиксировали, что что-то размножается где-то на станции. Вычистите это, пока не начало влиять на производительность."
Тут именно и получается "найдите то, не знаю что и неизвестно где" 😁

2021-06-22 19:43 UTC, TechCatOther commented on code/datums/announcements/gamemode.dm
> +	subtitle = "Тревога. Биоугроза"
Ничего не нашел про это в сталкере. Еще актуально??

2021-06-22 19:44 UTC, TechCatOther commented on code/game/machinery/requests_console.dm
> +	department_genitive = "Кабинета Капитана"
Я пока не делал так, поскольку это потребует перевода даже тех локаций, где никто никогда не будет использовать. Может пока остановимся на текущем решении?

2021-06-22 19:50 UTC, TechCatOther commented on code/datums/announcements/centcomm.dm
> +	message = "Похоже, отряд быстрого реагирования был запрошен на КСН Исход. Мы подготовим и отправим их в кратчайшие сроки."
Спасибо, поправил

2021-06-22 20:01 UTC, TechCatOther commented on code/datums/announcements/events.dm
> +		message = "На сканерах дальнего действия зафиксирована высоко-интенсивная аномалия воронок. Ожидаемое место: [A.name]."
А как же было писать все это... И править везде...

2021-06-22 20:25 UTC, TechCatOther commented on code/datums/announcements/events.dm
> +	message = "Обнаружен высокий уровень радиации рядом с станцией. " + \
Давайте объяснения оставим игрокам. Пусть будет простор для творчества.

2021-06-22 20:26 UTC, TechCatOther commented on code/datums/announcements/events.dm
> +			"Всему экипажу станции рекомендуется укрыться в технических туннелях станции."
Я брал из того, что видел как игроки пишу в чате. Где такие инструкции?

2021-06-22 20:27 UTC, TechCatOther commented on code/datums/announcements/events.dm
> +			"Просим доложить в медотсек, если вы чувствуете необычные симптомы. " + \
https://ru.wikipedia.org/wiki/%D0%A0%D0%B0%D0%B4%D0%B8%D0%B0%D1%86%D0%B8%D0%BE%D0%BD%D0%BD%D1%8B%D0%B9_%D0%BF%D0%BE%D1%8F%D1%81

2021-06-22 20:29 UTC, TechCatOther commented on code/datums/announcements/events.dm
> +			"Вскоре доступ к эксплуатационным отсекам будет закрыт."
`Вскоре общий доступ к техническим туннелям будет отключен`

2021-06-22 20:30 UTC, TechCatOther commented on code/datums/announcements/events.dm
> +	message = "Обнаружен ионный шторм рядом со станцией. Просьба проверить всё подконтрольное ИИ оборудование на ошибки."
Согласно лору ИИ корпорации не сбоит. Они не могли так отправить сообщение.

2021-06-22 20:32 UTC, TechCatOther commented on code/datums/announcements/events.dm
>  	..()
Выстрел то один, а огонь может быть несколько выстрелов. Более общее понятие по мне лучше. Не на каждый же выстрел будут писать.

Почему стоит убрать предупреждение о резком ударе?

2021-06-22 20:34 UTC, TechCatOther commented on code/datums/announcements/events.dm
> +	message = "Неопределенные формы жизни замечены на КСН Исход. Закройте любые внешние доступны, включая трубопровод и вентиляцию."
Протокола не видел. 

>  экипаж обязуется изолировать любые способы проникновения в свои отделы
Они ничего не говорили, что бы обязываться.

> Стелсонерф алиумов
Я не понял? Какой нерф? Это же всегда было...

2021-06-22 20:36 UTC, TechCatOther commented on code/datums/announcements/events.dm
> +	message = "Неопределенные формы жизни замечены на КСН Исход. Закройте любые внешние доступны, включая трубопровод и вентиляцию."
И да, тут нельзя использовать `station_name_ru`. Либо карта еще не будет загружена в момент создания объекта.

2021-06-22 20:36 UTC, TechCatOther commented on code/datums/announcements/events.dm
> +	message = "Неопределенные формы жизни замечены на [station_name_ru()]. Перекройте все входы и выходы, включая трубопровод и вентиляцию."
Аналогично выше

2021-06-22 20:39 UTC, TechCatOther commented on code/datums/announcements/events.dm
> +	message = "Вредный грибок обнаружен на станции. Структура станции может быть заражена."
Что не так с переводом?
Спо́ры (от греч. σπορά, σπόρος — сев, посев, семя) — клетки растений и грибов, служащие для их размножения и рассеяния. 

Они уже развились до грибка в момент анонса.

2021-06-22 20:41 UTC, TechCatOther commented on code/datums/announcements/events.dm
> +	message = "Космо-временная аномалия обнаружена на станции. Рекомендуется избегать подозрительных вещей и феноменов. Дополнительные данные отсутствуют."
аномальная угроза...
Тут двоякое понимание, что аномально. То что угрожает или это угроза странная?

2021-06-22 20:44 UTC, TechCatOther commented on code/datums/announcements/events.dm
> +	message = "На сканерах дальнего действия обнаружена нестабильная блюспейс аномалия. Ожидаемое место: неизвестно."
Почему тут лучше использовать именно слово "зафиксировать"?

```
Семантические свойства
Значение

    закрепить, запечатлеть с помощью рисунка, фотографии и т.п. ◆ Отсутствует пример употребления (см. рекомендации).
    закрепить фиксажем ◆ Отсутствует пример употребления (см. рекомендации).
    умертвить, хлороформировать мелких животных, насекомых для целей научного исследования
    иммобилизировать, лишить подвижности ◆ Отсутствует пример употребления (см. рекомендации).
    установить ? ◆ Вот почему беспокойно блуждал по стенам луч командирского фонаря, а пальцы замыкающих непрерывно поглаживали предохранители на автоматах, готовые в любое мгновенье зафиксировать его на автоматическом режиме огня и лечь на спусковой крючок. Дмитрий Глуховски, «Метро 2033», 2005 г. 
   ```

2021-06-22 20:50 UTC, TechCatOther commented on code/datums/announcements/events.dm
> +	message = "Обнаружено массивное блюспейс перемещение."
```
    • ТРАНСЛОКАЦИЯ, в ботанике - передвижение растворенных питательных веществ из одной части СОСУДИСТОГО РАСТЕНИЯ в другую. Сюда входит проникновение минералов и прочих неорганических солей из почвы через корни в ткань КСИЛЕМЫ, а также движение Сахаров и прочих органических соединений от листьев в другие части растения по ткани ФЛОЭМЫ.
    • ТРАНСЛОКАЦИЯ, в генетике - процесс, который изменяет генетическое строение ХРОМОСОМЫ. Из хромосомы вырезается фрагмент, в результате ее генетическая информация сокращается. Фрагмент подсоединяется к другой хромосоме, что также изменяет ее генетическое строение. Перегруппировка генов внутри одной хромосомы также называется транслокацией.
```
```
энтропия - физическая величина, характеризующая тепловое состояние системы и возможные изменения этих состояний; мера внутренней неупорядоченности
```

2021-06-22 20:54 UTC, TechCatOther commented on code/datums/announcements/events.dm
> +	message = "На сканерах дальнего действия зафиксирован гиперэнерегетический волновой поток. Ожидаемое место: неизвестно."
Я вот изначально тоже так думал, только вот по механике это какая энергетическая структура. То есть я думаю, это появился поток и ожидается приход его волны. Поэтому поставил как волновой. Собственно потом и будет взрыв если поток ученые не уберут.
Слово flux видимо тут пытались использовать как прилогательное, получилось что перед волной поток появляется.

2021-06-22 20:57 UTC, TechCatOther commented on code/datums/announcements/events.dm
> +	message = "На борту КСН Исход обнаружен неконтролируемый брендовый интеллект, готовьтесь."
Людук уже писал как-то что лучше сохранить информацию о том, что это бренд(Синидикат) распространяется по станции.

2021-06-22 20:58 UTC, TechCatOther commented on code/datums/announcements/events.dm
> +	message = "Неизвестная форма жизни обнаружена вблизи КСН Исход, готовьтесь."
Это же перевод...

2021-06-22 21:10 UTC, TechCatOther commented on code/modules/events/rogue_drones.dm
> +		msg = "Неизвестные хакеры атаковали боевое крыло дронов, запущенное с ВКН Икар. Если обнаружите их в данной области, приближаться с осторожностью."
За что Хакеров обидел?

2021-06-22 21:11 UTC, TechCatOther commented on code/modules/events/rogue_drones.dm
> +		msg = "Контроль дронов на ВКН Икар докладывает о восстановлении контроля над сбойным боевым крылом."
Icarus drone control. А вдруг там ИИ за ними следит? Более общее дает простор для интерпретации и следует оригиналу.

2021-06-22 21:12 UTC, TechCatOther commented on code/modules/research/message_server.dm
> +						Console.audible_message("[bicon(Console)] **Консоль Запроса пикнула: 'ПРИОРИТЕТНОЕ сообщение от [from_desc]'")
Это просто вопрос о частоте. Писк выше пика.

2021-06-22 21:28 UTC, TechCatOther commented on code/datums/announcements/gamemode.dm
> +			"Вероятно кто-то пытается взломать ваши системы. Сообщим вам позже, когда получим больше информации."
Там не внимание, а осторожно. И вполне подходит в текст. Я использовал глагол в начале предложение что бы сделать интонацию что важно о сообщение в будущем, а не кто его отправит. Русский язык...

2021-06-22 21:30 UTC, TechCatOther commented on code/datums/announcements/gamemode.dm
> +	message = "Мы начали отслеживать взломшика. Кто-бы это не делал, они находятся на самой станции. " + \
То есть они не уверены, раз он потенциальный?
В текст специально указанно, что для них не ясно, группа это или один.

2021-06-22 21:43 UTC, TechCatOther commented on code/datums/announcements/station.dm
> +	message = "Смена экипажа начата. Шаттл вызван. Он прибудет через [shuttleminutes2text()]."
Довольно много получается англицизмов.

2021-06-22 21:46 UTC, TechCatOther commented on code/datums/announcements/station.dm
> +	message = "Запланированный Шаттл Транспортировки Экипажа пристыковался к станции. Отправление примерно через [shuttleminutes2text()]."
Маршрутный? Рейсовый?

2021-06-22 21:52 UTC, TechCatOther commented on code/datums/announcements/station.dm
> +	message = "Шаттл Транспортировки Экипажа покинул станцию. Остается [shuttleminutes2text()] до стыковки шаттла к Центральному Командованию."
А почему лучше примерно? Тут нету пробок и время рассчитать можно точно.

2021-06-22 21:58 UTC, TechCatOther commented on code/modules/events/infestation.dm
> +	"кухне"                 = /area/station/civilian/kitchen, \
Думаю можно будет потом исправить этот, что бы подключить к названиям зон.

2021-06-22 22:00 UTC, TechCatOther commented on code/modules/research/message_server.dm
> +						Console.audible_message("[bicon(Console)] **Консоль Запроса пикнула: 'ПРИОРИТЕТНОЕ сообщение от [from_desc]'")
`Консоль Запроса пищит`

2021-06-22 22:02 UTC, TechCatOther commented on code/game/machinery/requests_console.dm
> +				dat += text("<A href='?src=\ref[src];department=[url_encode(to_dpt)]'>Отравить</A><BR>");
Добавил sanitize там

2021-06-22 22:06 UTC, TechCatOther commented on code/game/machinery/requests_console.dm
> +			MS.send_rc_message(href_list["department"], department, log_msg, msgStamped, msgVerified, priority, department_genitive)
Да, он должен было в именительном названии. Там через ключ в departments_genitive достанут нужное.

2021-06-22 22:07 UTC, TechCatOther commented on code/game/machinery/requests_console.dm
> +	department = "Кабинет ДИР"
Ну когда-то то надо было все название должностей перевести.

2021-06-22 22:23 UTC, TechCatOther commented
Подготовил под мерж. Ответил на все что написали, где смог. Сделал правки согласно ревью.

2021-06-22 23:20 UTC, TechCatOther commented on code/datums/announcements/events.dm
> +			"Всему экипажу станции рекомендуется укрыться в технических туннелях станции."
Поставил везде туннели

2021-06-22 23:21 UTC, TechCatOther commented on code/modules/events/rogue_drones.dm
> +		msg = "Неизвестные хакеры атаковали боевое крыло дронов, запущенное с ВКН Икар. Если обнаружите их в данной области, приближаться с осторожностью."
Перенес

2021-06-22 23:21 UTC, TechCatOther commented on code/modules/events/rogue_drones.dm
> +		msg = "Контроль дронов ВКН Икар разочарован в потере боевого крыла. Выжившие дроны будут восстановлены."
Так же

2021-06-23 03:29 UTC, volas commented on code/datums/announcements/station.dm
> +	message = "Был аннулирован обслуживающий доступ на все шлюзы."
@T6751 тут maintenance подразумевались техтуннели, нужно поправить

2021-06-23 03:30 UTC, volas commented on code/datums/announcements/station.dm
> +	message = "Был установлен обслуживающий доступ на все шлюзы."
@T6751 same

2021-06-23 03:33 UTC, volas commented on code/datums/announcements/station.dm
> +	message = "Смена экипажа начата. Шаттл вызван. Он прибудет через [shuttleminutes2text()]."
Мне текущий вариант не нравится, потому что без контекста "Смена экипажа начата" подходит и для оповещения в начале раунда. Что нибудь более однозначное бы, может вариант Логимая ниже.

2021-06-23 03:36 UTC, volas commented on code/datums/announcements/station.dm
> +	message = "Запланированный Шаттл Транспортировки Экипажа пристыковался к станции. Отправление примерно через [shuttleminutes2text()]."
Да, оба не хуже "Запланированный". Можно еще регулярный.

Или может быть что-то такое
```suggestion
	message = "Шаттл Транспортировки Экипажа пристыковался к станции в соответствии с расписанием. Отправление примерно через [shuttleminutes2text()]."
```

2021-06-23 03:38 UTC, volas commented on code/datums/announcements/station.dm
> +	message = "Шаттл Транспортировки Экипажа покинул станцию. Остается [shuttleminutes2text()] до стыковки шаттла к Центральному Командованию."
Больше подходит к Estimate по смыслу. И Шаттлы действительно могут на несколько десятков секунд туда-сюда сдвинуться.

2021-06-23 03:39 UTC, volas commented on code/datums/announcements/station.dm
> +	message = "Эвакуационный Шаттл покинул станцию. Остается [shuttleminutes2text()] до стыковки шаттла к Центральному Командованию."
и тут

2021-06-23 03:46 UTC, volas commented on code/datums/announcements/station.dm
> +	message = "Шаттл Транспортировки Экипажа покинул станцию. Остается [shuttleminutes2text()] до стыковки шаттла к Центральному Командованию."
Хотя, я придираюсь, это действительно не важно и скорее к устоявшимся в расписаниях формулировкам. У нас я не помню "Примерно".

2021-06-23 04:47 UTC, logimy commented on code/modules/events/rogue_drones.dm
> +		msg = "Неизвестные хакеры атаковали боевое крыло дронов, запущенное с ВКН Икар. Если обнаружите их в данной области, приближаться с осторожностью."
@TechCatOther на хакеров пофигу, главное «боевое крыло» поменять на «звено» ☺️

2021-06-23 04:48 UTC, logimy commented on code/modules/events/rogue_drones.dm
> +		msg = "Контроль дронов на ВКН Икар докладывает о восстановлении контроля над сбойным боевым крылом."
Операторы дронов тоже могут быть синтами

2021-06-23 04:49 UTC, logimy commented on code/modules/events/rogue_drones.dm
> +		msg = "Контроль дронов ВКН Икар разочарован в потере боевого крыла. Выжившие дроны будут восстановлены."
@4310V343k да, я понимаю, но у меня типа «вольный перевод»

2021-06-23 04:51 UTC, logimy commented on code/datums/announcements/events.dm
> +			"Просим доложить в медотсек, если вы чувствуете необычные симптомы. " + \
Хм, и правда. Не знал, спасибо

2021-06-23 04:53 UTC, logimy commented on code/datums/announcements/events.dm
> +	message = "Неопределенные формы жизни замечены на КСН Исход. Закройте любые внешние доступны, включая трубопровод и вентиляцию."
Каждый раз когда я писал «обязуется» имелось ввиду некое лорное соглашение, которое подписывал каждый член экипажа перед поступлением на работу. И эти приколы вставлял туда только чтобы добавить формальность и хладнокровности анонсам

2021-06-23 04:55 UTC, logimy commented on code/datums/announcements/events.dm
> +	message = "Вредный грибок обнаружен на станции. Структура станции может быть заражена."
Когда типа сдаешь анализы на кожвены всякие, грибок обнаруживают по спорам. Вдохновлялся этим. Хз на деле почему так, возможно споры легче обнаружить

2021-06-23 04:55 UTC, logimy commented on code/datums/announcements/events.dm
> +	message = "Космо-временная аномалия обнаружена на станции. Рекомендуется избегать подозрительных вещей и феноменов. Дополнительные данные отсутствуют."
Кстате да, хорошо подмечено

2021-06-25 05:08 UTC, volas commented on code/modules/events/rogue_drones.dm
> +		msg = "Неизвестные хакеры атаковали боевое крыло дронов, запущенное с ВКН Икар. Если обнаружите их в данной области, приближаться с осторожностью."
Почему в твоём "вольном переводе" постоянно какая-то замена смыслов?

2021-06-25 05:14 UTC, volas approved these changes

2021-06-25 05:14 UTC, volas commented
Следующий комментарий будет юбилейным :tada:

2021-06-25 05:15 UTC, merged