"Да сын мой, это жопа."
TauCetiStation/TauCetiClassic pull request #6996
Opened 2021-04-04 20:04 UTC by notkripton

## Описание изменений
Да, я знаю, что такое может произойти раз в вечность, да я знаю, что я рукожопый дегенерат, не способный выучить бьенд даже по гайдам с анимуса, да я знаю, что заголовок не по форме, но...
На карте planetarium.dmm прямо по середине есть замечательный объект - сингулярность, но она значительно более разрушительна, чем вы можете себе представить. Готовы узреть эту херню в действии? Как мы знаем из всем известной теории относительности понятия "время" и "пространство" за горизонтом событий черной дыры просто напрочь перестают работать. ТАК ДАВАЙТЕ СДЕЛАЕМ ЭТО, ВПЕРЕД, ШАГАЙ В НЕЕ! И вот спустя долю секунды ты уже не там, где был до этого. Пространства для тебя больше не существует, ты одновременно везде и одновременно нигде, для тебя остановилось само время. Но ты ничего не увидишь, даже сложно будет сказать, существуешь ты на самом деле, но по крайней мере для того мира, который ты знал, тебя уже нет.
Шутки в сторону, ведь эта херня РЕАЛЬНО опасна. Стоит вашей кукле встать на один тайл с ней, как она нахер просто ИСЧЕЗНЕТ БЛЯТЬ. Нет, я серьезно, она просто испепелит вас круче Таноса. И ведь даже ф1 не поможет. И угадайте, кто оказался тем лохом, что решил познать ее мощь будучи ебаным капитаном? Да, все верно, это я. По моим скромным пониманиям в коде действие eat(), направленное к сущности внутри этой сингулярности, просто удаляет ее из игры вместе со всеми вещами, информацией, вашим интерфейсом и всем, черт возьми, что было, но при этом не делает вас гостом, так что игра превращается примерно в это:
![Снимок экрана (221)](https://user-images.githubusercontent.com/75007994/113519844-85a95700-9597-11eb-943e-579ee42ad42b.png)
 
 P.S. В крю манифесте вы все равно остаетесь Active (??????).
 
 Причем ломает это игру даже для педалей:
 
![Снимок экрана (223)](https://user-images.githubusercontent.com/75007994/113519876-b8534f80-9597-11eb-9a3c-86e4d8ae6225.png)

И как я решил это исправить? Да - вместо допиливания я просто нахер удалил ее из кода, заменив на карте игрушечной версией.

И да, то, для чего вы сюда пришли:
![Снимок экрана (222)](https://user-images.githubusercontent.com/75007994/113520100-7deab200-9599-11eb-8245-5bac20ffb1b1.png)

## Почему и что этот ПР улучшит
Одним багом меньше.
## Авторство
Я
## Чеинжлог
:cl:
- bugfix: Удаляет забагованную сингулярность.

2021-04-04 20:05 UTC, KIBORG04 commented on maps/templates/space_structures/planetarium.dmm
> +"a" = (/turf/space,/area/space)
Конвертируй карту в другой формат

2021-04-04 20:07 UTC, KIBORG04 commented
Тебя делитнуло, но ты попал в нуллспейс.

Отдели шутку-инфу от полезной инфы, пожалуйста

2021-04-04 20:07 UTC, notkripton commented on maps/templates/space_structures/planetarium.dmm
> +"a" = (/turf/space,/area/space)
> Конвертируй карту в другой формат

Я дурак, можешь обьяснить как?

2021-04-04 20:07 UTC, TechCatOther commented on maps/templates/space_structures/planetarium.dmm
> +"a" = (/turf/space,/area/space)
https://github.com/TauCetiStation/TauCetiClassic/wiki/F.A.Q.-%D0%BF%D0%BE-%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%B5-%D1%81-%D0%BA%D0%B0%D1%80%D1%82%D0%BE%D0%B9

2021-04-04 20:08 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2021-04-04 20:09 UTC, notkripton commented
> Тебя делитнуло, но ты попал в нуллспейс.
> 
> Отдели шутку-инфу от полезной инфы, пожалуйста

готово

2021-04-04 20:24 UTC, notkripton commented on maps/templates/space_structures/planetarium.dmm
> +"a" = (/turf/space,/area/space)
>Файл должен содержать исполняемый код, который будет запущен при активации хука.

Откуда его брать?

2021-04-04 20:55 UTC, notkripton commented on maps/templates/space_structures/planetarium.dmm
> +"a" = (/turf/space,/area/space)
Я все-таки понимаю шо надо сделать. Написанно установить хуки - я установил, но гит говорит, что изменений нету. Мне какой-то там хук создать надо или что?

2021-04-04 20:58 UTC, AndroBetel commented
на карте что-то измени, закоммить, и обратно измени и закоммить.

2021-04-04 21:48 UTC, notkripton commented
Лять, исправил одно - получилось другое. Что делать с Error: Process completed with exit code 1. ?

2021-04-05 05:06 UTC, kalazus commented
Эта сингулярность является подтипом обычной сингулярности, и, следовательно, там те-же проблемы что и у обычной сингулярности (единственное отличие в process, но там просто меньше кода). Получается, что пр ничего не исправляет. 
И да, не следует заходить за капитана в построенные учёными телепорты.

2021-04-05 06:30 UTC, notkripton commented
> Эта сингулярность является подтипом обычной сингулярности, и, следовательно, там те-же проблемы что и у обычной сингулярности (единственное отличие в process, но там просто меньше кода). Получается, что пр ничего не исправляет.

Родительская сингулярность на встречается на картах => выпиливать ее нету смысла.

2021-04-05 06:30 UTC, notkripton commented on maps/templates/space_structures/planetarium.dmm
> +"a" = (/turf/space,/area/space)
Пофиксил

2021-04-05 06:50 UTC, KIBORG04 commented
Родительская синга - это синга, которую инжы каждый раунд подрубают

2021-04-05 07:21 UTC, notkripton commented
> Родительская синга - это синга, которую инжы каждый раунд подрубают

Тогда в чем проблема? Багнутая только академи, т.к. синга инжей просто тебя разрывает и откидывает бошку на z слой астероида (по крайней мере со мной всегда было так). Никаких черных экранов и прочих атрибутов.

2021-04-05 08:44 UTC, Haggerd commented
Мммм, минус ещё одна опасность космоса.
Меняйте тогда и мечи световые на игрушечные. И нюку тоже не забудьте.
Баг есть, да. Но вместо того, чтобы его исправить, делаем вот это.

2021-04-05 10:40 UTC, KIBORG04 requested changes
https://user-images.githubusercontent.com/26389417/113565704-1cb3f480-9614-11eb-85b0-bac2529dcd2d.mp4

Баг не получилось воспроизвести в моих условиях. По коду должна багать и инженерская синга, потому что отличия академи от инженерской минимальны.

Тебе осталось только понять почему эта синга багает и не гибает. Ну либо почему ты оказался в нуллспейсе, а это обычно через сломанный qdel() происходит

2021-04-05 11:09 UTC, kalazus commented
Для полного воспроизведения может понадобится закрытая с 4 сторон синга и телепорт прямо в неё (тогда голова делитнится почти моментально).

2021-04-05 11:12 UTC, KIBORG04 commented
> Для полного воспроизведения может понадобится закрытая с 4 сторон синга и телепорт прямо в неё (тогда голова делитнится почти моментально).


https://user-images.githubusercontent.com/26389417/113568278-eb89f300-9618-11eb-9938-34db4d428291.mp4

Я тепался в стены и тоже нету эффекта

2021-04-05 16:02 UTC, notkripton commented
https://youtu.be/7NnEFrtJFqs

Баг сработает если ты тепнешся на тайл с сингой через телесало или хенд телепортер.

2021-04-05 17:16 UTC, KIBORG04 commented
> https://youtu.be/7NnEFrtJFqs
> 
> Баг сработает если ты тепнешся на тайл с сингой через телесало или хенд телепортер.
> 
> ![Screenshot_2](https://user-images.githubusercontent.com/75007994/113595493-c362ba00-9641-11eb-94a8-311b6cba7ea8.png)

Но может опять же это проблема не синги, а телепортеров?

2021-04-07 07:20 UTC, notkripton commented
Затестил с инженерной сингой - все как должно быть.

2021-04-07 07:32 UTC, KIBORG04 commented
Скажи, а ты большую видишь разницу между кодом этих двух синг?

2021-04-10 09:14 UTC, TechCatOther commented
Просмотрел код. У оригинальной все так же работает, только она больше урона наносит. Этот баг распространяется и на оригинальную. Удаление данной сингулярности не правит его.

2021-04-10 09:56 UTC, KIBORG04 commented
> только она больше урона наносит

Что? Оби синги гибают, какой урон? Я понимаю, что она получает больше энергии за клоуна но это не урон
![image](https://user-images.githubusercontent.com/26389417/114265919-29618f80-99fc-11eb-8d72-c95f9dcd42ac.png)

2021-04-10 11:28 UTC, TechCatOther commented
>  Обе синги гибают, какой урон?
Я имел в виду общий, по станции, окружению и тп. То есть просто более опасная.

2021-04-20 20:18 UTC, volas commented
Проблема возможно в чем-то другом, нужно смотреть дальше. Где-то рядом еще проблемное удаление было, если моб спрятался в шкафу от синги.

2021-04-20 20:18 UTC, closed without merging