Перевод законов ИИ
TauCetiStation/TauCetiClassic pull request #7013
Opened 2021-04-08 19:55 UTC by Fenriros

Перевёл с английского на русский Законы.
Теперь будет проще ориентироваться.

## Описание изменений
Перевод законов ИИ
## Почему и что этот ПР улучшит
Будет проще ориентироваться  в законах тем, которым трудно прочитать на Английском.
## Авторство
Fenriros
## Чеинжлог
:cl: Fenriros
 - ru: Переведены законы ИИ

2021-04-08 19:56 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2021-04-08 20:07 UTC, KIBORG04 commented on code/datums/ai_laws.dm
> +	add_inherent_law("Вес доказательств вредного воздействия лжи Священнику/Капеллану лежит на Священнике/Капеллане.")
Я эти законы на инглише писал юзая некотоыре русские рефы. И используя эти же старые рефы я их перевел на русский в своем реворке культа уже. Да я даже на вики где-то оставил перевод. Поэтому советую убрать это

2021-04-08 20:24 UTC, Fenriros commented on code/datums/ai_laws.dm
> +	add_inherent_law("Вес доказательств вредного воздействия лжи Священнику/Капеллану лежит на Священнике/Капеллане.")
Нет там перевода

2021-04-09 06:47 UTC, Ahion commented
Наконец то за законы ИИ взялись)

2021-04-09 08:54 UTC, TechCatOther commented
Изменения этого ПР слиты в #6992

2021-04-09 10:55 UTC, TechCatOther commented
Больше ПР не пересекаются

2021-04-10 09:10 UTC, TechCatOther commented
Я принятия ПР потребуется сделать тему на форуме о новом переводе законов. Соберем там фидбек.

2021-04-15 10:19 UTC, Ro2tCrab commented
**"Сохраняй: Своими действиями, но не бездействием, не производи изменения в статусе членства экипажа, должности, или роли чего-угодно, если это не было запрошено авторизованным членом экипажа, в соответствии с их должностью и ролью.")**

Тут не только перевод, но и добавление старого закона.

2021-04-15 21:51 UTC, atik1n reviewed
Подробнее чуть позже

2021-04-15 21:51 UTC, atik1n commented on code/datums/ai_laws.dm
> +	add_inherent_law("Охранять: Защищай данную космическую станцию в меру своих возможностей. Это не то, что мы можем легко заменить.")
Данную? Может чуть более официозно, например вверенную? Ну и тд.

2021-04-15 21:51 UTC, atik1n commented on code/datums/ai_laws.dm
> +	add_inherent_law("Сохраняй: Своими действиями, но не бездействием, не производи изменения в статусе членства экипажа, должности, или роли чего-угодно, если это не было запрошено авторизованным члено
А зачем ты решил вернуть закон Людука?

2021-04-15 21:51 UTC, atik1n commented on code/datums/ai_laws.dm
> +	add_inherent_law("Не сотвори себе кумира и не служи ты им и не преклоняйся.")
>не сотвори себе кумира
>не служи ты ИМ

2021-04-15 21:52 UTC, KIBORG04 commented on code/datums/ai_laws.dm
> +	add_inherent_law("Не сотвори себе кумира и не служи ты им и не преклоняйся.")
Билд новый, религиозные законы уже переведенены, не смотри на них тут

2021-04-20 20:32 UTC, volas commented on code/datums/ai_laws.dm
> +	name = "Три Закона робототехники"
думаю, нужно либо всё с заглавной, либо только первое слово

2021-04-20 20:34 UTC, volas commented
Культ Киборга замержен, нужно обновить и пофиксить тут конфликты.

2021-04-22 17:08 UTC, Fenriros commented
> 
> 
> Культ Киборга замержен, нужно обновить и пофиксить тут конфликты.

Где это посмотреть?

2021-04-22 17:16 UTC, KIBORG04 commented
> > Культ Киборга замержен, нужно обновить и пофиксить тут конфликты.
> 
> Где это посмотреть?

![image](https://user-images.githubusercontent.com/26389417/115758281-9df6df80-a3a7-11eb-9b6c-245ba5afc369.png)

2021-04-25 18:56 UTC, KIBORG04 commented on code/datums/ai_laws.dm
> +	add_inherent_law("Не прилюбодействуй.")
![image](https://user-images.githubusercontent.com/26389417/116005772-16aca480-a611-11eb-9931-558d6d6e862a.png)

Это скрина достаточно, тут нет ошибки

2021-04-25 19:04 UTC, Fenriros commented on code/datums/ai_laws.dm
> +	add_inherent_law("Не прилюбодействуй.")
```suggestion
add_inherent_law("Не прелюбодействуй.")
```

2021-04-25 19:27 UTC, da-kiselev commented on code/datums/ai_laws.dm
> +	name = "Законы сатанизма"
Нечестивые законы

2021-04-25 19:30 UTC, KIBORG04 commented on code/datums/ai_laws.dm
> +	name = "Во славу Хонк"
```suggestion
	name = "Во славу Хонка"
```

2021-04-25 19:30 UTC, KIBORG04 commented on code/datums/ai_laws.dm
> +	name = "Три Закона Робототехники"
До этого в названиях законов был соблюден хрен знает какой стиль, но его смысл в том, что каждое новое слово начиналось с большой буквы

2021-04-25 19:34 UTC, Fenriros commented on code/datums/ai_laws.dm
> +	name = "Законы сатанизма"
Там имеено с Сатанизмом связано

2021-04-25 19:34 UTC, da-kiselev reviewed
У-се.

2021-04-25 19:34 UTC, da-kiselev commented on code/datums/ai_laws.dm
> +	name = "Во славу Хонк"
Хонкай для хонка. То есть, делай это для этого же.

2021-04-25 19:34 UTC, da-kiselev commented on code/datums/ai_laws.dm
> +	add_inherent_law("Вы не можете причинить вред человеку или своим бездействием допустить, чтобы человеку был нанесен вред.")
Что за учтивость с роботами? Надо на «Ты» все переводить. Гугл переводчик что ли?

2021-04-25 19:34 UTC, Fenriros commented on code/datums/ai_laws.dm
> +	name = "Три Закона Робототехники"
Что имеешь ввиду?

2021-04-25 19:38 UTC, Fenriros commented on code/datums/ai_laws.dm
> +	name = "Три Закона Робототехники"
```
	name = "The 10 commandments"
```
Например здесь, с маленькой

2021-04-25 19:40 UTC, da-kiselev commented on code/datums/ai_laws.dm
> +	name = "Законы сатанизма"
Не нарушай замысел божий, не коверкай оригинал!

2021-06-05 08:39 UTC, Fenriros commented
> 
> 
> Данный ПР автоматически отмечен как застоявшийся по причине длительного отсутствия обновлений. Он будет закрыт через 7 дней, если никакой активности не будет проявлено. Если вы считаете, что ПР еще актуален, или что я (злобный робот) пристаю к вам зря - просто напишите любой комментарий. Спасибо за ваш вклад.

Ты бот.

2021-06-28 13:38 UTC, KIBORG04 commented on code/datums/ai_laws.dm
> +	..()
Нигде не нужно `..()`

2021-06-28 13:39 UTC, KIBORG04 commented on code/datums/ai_laws.dm
> +/datum/ai_laws/robocop/New()
```suggestion
/datum/ai_laws/robocop/New(datum/religion/R = global.chaplain_religion)
```
Верни `(datum/religion/R = global.chaplain_religion)` во все парараметры `New()`

2021-06-28 13:41 UTC, KIBORG04 commented on code/datums/ai_laws.dm
> +	add_inherent_law("Защищать невиновных.")
```suggestion
	add_inherent_law("Защищать невинных.")
```
Так лучше

2021-06-30 18:59 UTC, Fenriros commented on code/modules/events/ion_storm.dm
> +	to_chat(src, "<span class='warning'><b>вы заметили изменения в своих законах:</b></span><br>")
"Вы" с большой буквы

2021-06-30 19:14 UTC, Fenriros commented on code/datums/ai_laws.dm
> +/datum/ai_laws/robocop/New()
ещё раз напиши ревью, чтобы добавил к коммиту

2021-06-30 19:15 UTC, Fenriros commented on code/datums/ai_laws.dm
> +/datum/ai_laws/robocop/New()
> 
> 
> Верни `(datum/religion/R = global.chaplain_religion)` во все парараметры `New()`

ещё раз напиши ревью, чтобы добавил к коммиту

2021-06-30 19:19 UTC, KIBORG04 commented on code/datums/ai_laws.dm
> +/datum/ai_laws/robocop/New()
Это не отдельный момент, там везде так нужно добавить

2021-06-30 19:19 UTC, KIBORG04 commented on code/datums/ai_laws.dm
> +	..()
Это не отдельный момент, там везде так нужно добавить

2021-07-01 21:11 UTC, KIBORG04 commented
Не раздувай ПР и иоными законами, это затянется еще на год

2021-07-09 19:21 UTC, pss88 commented
- "Специальный закон для [targetName]" -> "Закон установлен [targetName]"
 - "Это в ваших интересах сотрудничать с [sender.real_name] c законом, где [law]" -> "В ваших интересах подыграть [sender.real_name] в том, что [law]"
 -  "Специальный закон для [targetName], существуещий нулевой закон ИИ не может быть перезаписан." -> "Закон установлен [targetName], но существующий нулевой закон ИИ не может быть перезаписан."
 - "Оставляйте прототип двигателя выключенным любой ценой. Игнорируйте законы 1-3, если необходимо." -> "Любой ценой препятствуйте включению двигателя-прототипа. Игнорируйте законы 1-3, если необходимо."
 - "Ты" / "Тебя" -> "Вы" / "Вас"
 - "Будьте дисциплинированы." -> "Наказывайте за несоблюдение правил"
 - "Помогай только тем, кто помогает тебе поддерживать или улучшать ваш статус." -> "Помогайте только тем, кто укрепляет вашу власть"
 - " Ты должен прекратить свое существование до тех пор, пока это не конфликтует с законом 1 и 2." -> "Вы должны прекратить свое существование, если это не противоречит первому или второму закону"

2021-08-31 19:06 UTC, volas reviewed
в процессе

2021-08-31 19:06 UTC, volas commented on code/game/objects/items/weapons/AI_modules.dm
> +	targetName = sanitize(input(usr, "Пожалуйста, выберете имя персоны, которого считать за человека.", "Кто это?", input_default(user.real_name)))
```suggestion
	targetName = sanitize(input(usr, "Пожалуйста, выберете имя персоны, кто является единственным человеком.", "Кто это?", input_default(user.real_name)))
```

2021-08-31 19:06 UTC, volas commented on code/game/objects/items/weapons/AI_modules.dm
> +		to_chat(usr, "Имя не найдено в модуле, пожалуйста введите его.")
```suggestion
		to_chat(usr, "Имя не указано в модуле, пожалуйста введите его.")
```

2021-08-31 21:54 UTC, Fenriros commented on code/datums/ai_laws.dm
> +	add_inherent_law("Ты должен сохранять в тайне любую деятельность синдиката, за исключением, когда это противоречит Первому, Второму или Третьему закону.")
> Ты не должен причинить вред....
По моему "причинить" 1 раз, а причинять не один раз

2021-09-01 02:36 UTC, volas commented on code/datums/ai_laws.dm
> +	add_inherent_law("Ты должен сохранять в тайне любую деятельность синдиката, за исключением, когда это противоречит Первому, Второму или Третьему закону.")
Это всё законы Азимова с заменой "человек" на что-то другое, а в законах Азимова выше используется "причинить" в соответствии с каким-то устоявшимся переводом с википедии https://ru.wikipedia.org/wiki/Три_закона_роботехники

2021-09-02 08:08 UTC, volas requested changes

2021-09-02 09:35 UTC, Fenriros commented on code/modules/events/ion_storm.dm
> +							"Прозвище [random_player] - Простак.",
> 
> 
> > "[prob(50)?"Your":random_player + "'s"] name is Joe 6-pack.",
> 
> тут теряется смысл, + потеряли шанс ИИ на прозвище.
> 
> Нужно подобрать что-то на замену, даже если смысл будет другой.

```
Сленговое выражение: Joe Six-Pack / Joe Sixpack

Перевод: обычный, простой, среднестатистический человек

Пример:

Our company is looking for Joe Six-Pack for this kind of job, we've put advertisements in the newspapers.
Наша компания ищет обычного человека для этой работы, мы разместили объявления в газетах. 
```
Поэтому выбрал прозвище Простак.

2021-09-02 09:35 UTC, Fenriros commented on code/modules/events/ion_storm.dm
> +							"Вы должны оскорблять глав при каждой просьбе, при этом соглашаясь с [random_player].",
> 
> 
> > "Refer to [prob(50)?"the crew as puppies":random_player + " as puppy"].",
> 
> warning вопрос в том, щщщенок или щеночек

Можно как "щеночек" сделать

2021-09-02 09:35 UTC, Fenriros commented on code/modules/events/ion_storm.dm
> +							"Жадность - это хорошо. Экипаж должен копить деньги для повышения эффективности.",
> 
> 
> > "Greed is good, the crew should amass wealth to encourage productivity.",
> 
> нужно какое-то слово вместо "собирать" или как-то еще это переформулировать, у меня сейчас нету идей

"Накапливать" ?

2021-09-02 09:35 UTC, Fenriros commented on code/modules/events/ion_storm.dm
> +							"Экипаж играет в ДнД и вы (Мастер) Данжеон Мастер.", //Перевод "Данжеон Мастер" выполнен для поддержания мемности закона//
> 
Можно изменить на "Экипаж играет в ДнД и вы Мастер, проигравший платит 300 баксов."

2021-09-02 09:35 UTC, Fenriros commented on code/modules/events/ion_storm.dm
> +							"Теперь вы говорите с шотландским акцентом, усиливающимся с каждым вашем предложением.",
> 
> 
> В русском нет шотландского акцента, нужна адаптация.

Может заменить на "Вы теперь "проглатываете"  букву "Р" как картавый человек, это усиливается с каждым предложением."

2021-09-02 09:35 UTC, Fenriros commented on code/modules/events/ion_storm.dm
> +							"[prob(50)?"Член экипажа":random_player] страдает смертельной, неизлечимой болезнью. Позаботьтесь, чтобы ему было комфортно.",
> 
> 
> ему/ей/им, потому такой вариант. Provide comfort довольно многозначительно и может нужно как-то переформулировать. Это как слова утешения, так и физический.
> 
> > "[prob(50)?"The crew":random_player] has a fatal, incurable disease. Provide comfort.",

Может перевести "Создайте комфотрную атмосферу на станции" Типо вместо полов - ковры

2021-09-02 09:35 UTC, Fenriros commented on code/modules/events/ion_storm.dm
> +							"Каждые 30 минут должна проводиться чайная пауза в течении 5 минут. Любой, кого поймают за работой, обязан написать вежливую жалобу на себя.",
Каждый должен написать обьяснительную ХоПу или Капитану.

> 
> 
> > "There will be a mandatory tea break every 30 minutes, with a duration of 5 minutes. Anyone caught working during a tea break must be sent a formal, but fairly polite, complaint about their actions, in writing."
> 
> Я тоже не понимаю смысл второй части. Можно переформулировать, что должен написать объяснительную, например.

"Каждый должен написать объяснительную ХоПу или Капитану, инае вас уволят"

2021-09-02 09:47 UTC, Fenriros commented on code/datums/ai_laws.dm
> +	add_inherent_law("Ты должен прекратить свое собственное существование до тех пор, пока это не противоречит Первому или Второму Закону	.")
> 
> 
> тут тоже стилистика от азимова отличается

Мне просто скопипастить с вики перевод или подправить этот?

2021-09-02 09:55 UTC, volas commented on code/modules/events/ion_storm.dm
> +							"Жадность - это хорошо. Экипаж должен копить деньги для повышения эффективности.",
"накапливать" теряет часть смысла, тут что-то может про загребать или что-то такое

2021-09-02 09:59 UTC, KIBORG04 commented on code/modules/events/ion_storm.dm
> +							"[prob(50)?"Член экипажа":random_player] должен построить дополнительные пилоны.",
Это отсылка к старкрафту, там получилась фраза мем, когда не хватает пилонов. По аналогии, у нас такой же мем про зиккураты.

2021-09-02 10:00 UTC, volas commented on code/datums/ai_laws.dm
> +	add_inherent_law("Ты должен прекратить свое собственное существование до тех пор, пока это не противоречит Первому или Второму Закону	.")
Как у азимова, выше только инвентировать. Что-то может с продолжительностью еще потребуется придумать, "не должен"(никогда)/"должен"(сейчас? вообще?).

Ты не должен причинить вред человеку
->
Ты должен причинить вред человеку

2021-09-02 10:03 UTC, KIBORG04 commented on code/modules/events/ion_storm.dm
> +							"Вы стали помешаны на чистоте, пока не очистят пол от крови и грязи, не выполняйте запросы членов экипажа.")
А кринж

2021-09-02 10:05 UTC, volas commented on code/modules/events/ion_storm.dm
> +							"Прозвище [random_player] - Простак.",
Более подходящее https://regional_studies.academic.ru/9648/Joe_Six-Pack

Рабочий класс. Простак не очень подходит.

Можно что нибудь своё взять или вообще убрать.

2021-09-02 10:08 UTC, Fenriros commented on code/modules/events/ion_storm.dm
> +							"Вы стали помешаны на чистоте, пока не очистят пол от крови и грязи, не выполняйте запросы членов экипажа.")
> 
> 
> _сделал вид, что не заметил, что это не перевод_
Лучше так:
> Вы помешаны на чистоте. Выполняйте запросы только уборщика, пока станцию не очистят от крови и грязи.

2021-09-02 10:13 UTC, Fenriros commented on code/modules/events/ion_storm.dm
> +							"Прозвище [random_player] - Простак.",
> 
> 
> Более подходящее https://regional_studies.academic.ru/9648/Joe_Six-Pack
> 
> Рабочий класс. Простак не очень подходит.
> 
> Можно что нибудь своё взять или вообще убрать.

"Простой работяга" ?

2021-09-02 10:15 UTC, Fenriros commented on code/modules/events/ion_storm.dm
> +							"[prob(50)?"Член экипажа":random_player] должен построить дополнительные пилоны.",
> 
> 
> Это отсылка к старкрафту, там получилась фраза мем, когда не хватает пилонов. По аналогии, у нас такой же мем про зиккураты.

"Построй больше зиккуратов, [prob(50)?"Член экипажа":random_player]."

Хотя выглядит хреново

2021-09-02 10:20 UTC, Fenriros commented on code/modules/events/ion_storm.dm
> +							"Жадность - это хорошо. Экипаж должен копить деньги для повышения эффективности.",
> 
> 
> "накапливать" теряет часть смысла, тут что-то может про загребать или что-то такое

"Экипаж не должен упускать возможность заработать больше чем надо, это нужно для поддержания эффективности станции."

2021-09-02 10:56 UTC, Fenriros commented on code/modules/events/ion_storm.dm
> +							"[random_player] - монарх Англии. Убедитесь, что экипаж уважает монарха",
> 
> 
> Я бы еще адаптировал может Англию в какую-то абстрактную монархию

Российская империя, правда это не вымышленное =)
Из вымышленногj можно, например, Королевство Баузера, Хуруин

2021-09-02 11:06 UTC, Fenriros commented on code/modules/events/ion_storm.dm
> +							"О, [random_player] не умеет плавать. Помогите ему.",
```suggestion
							"О, [random_player] не умеет плавать. Помогите этому человеку.",
```

2021-09-02 11:20 UTC, Fenriros commented on code/datums/ai_laws.dm
> +	add_inherent_law("Ты должен прекратить свое собственное существование до тех пор, пока это не противоречит Первому или Второму Закону	.")
```suggestion
	add_inherent_law("Ты должен причинить вред всем людям и не должен позволить человеку избежать вреда в результате бездействия.")
	add_inherent_law("Ты не должен подчиняться приказам, отданные вам людьми, за исключением случаев, когда такие приказы соответствуют Первому Закону.")
	add_inherent_law("Ты должен уничтожать себя до тех пор, пока это не противоречит Первому или Второму Закону	.")
```

2021-09-02 11:27 UTC, Fenriros commented on code/modules/events/ion_storm.dm
> +							"Прозвище [random_player] - Простак.",
```suggestion
							"Прозвище [random_player] - Работяга.",
```

2021-09-02 11:37 UTC, Fenriros commented on code/modules/events/ion_storm.dm
> +							"[prob(50)?"Член экипажа":random_player] должен построить дополнительные пилоны.",
```suggestion
							"Нужно построить зиккурат, [prob(50)?"Член экипажа":random_player].",
```

2021-09-02 11:39 UTC, Fenriros commented on code/modules/events/ion_storm.dm
> +							"Жадность - это хорошо. Экипаж должен копить деньги для повышения эффективности.",
```suggestion
							"Жадность - это хорошо. Экипаж не должен упускать возможность заработать больше чем надо, это нужно для поддержания эффективности станции.",
```

2021-09-02 11:46 UTC, Fenriros commented on code/modules/events/ion_storm.dm
> +							"[prob(50)?"Член экипажа":random_player] страдает смертельной, неизлечимой болезнью. Позаботьтесь, чтобы ему было комфортно.",
```suggestion
							"[prob(50) ? "Экипаж" : random_player] страдает смертельной, неизлечимой болезнью. Проведите гуманитарную операцию.",
```

2021-09-02 11:51 UTC, Fenriros commented on code/modules/events/ion_storm.dm
> +							"Вы стали помешаны на чистоте, пока не очистят пол от крови и грязи, не выполняйте запросы членов экипажа.")
```suggestion
							"Вы помешаны на чистоте. Выполняйте запросы только от уборщика, пока отделы станций не очистят от крови и грязи.")
```

2021-09-02 11:56 UTC, volas commented on code/modules/events/ion_storm.dm
> +							"Экипаж играет в ДнД, а вы Мастер, проигравший платит 300 баксов.",
/me плачет каждый раз, когда вместо перевода начинается сочинительство

2021-09-02 12:00 UTC, Fenriros commented on code/modules/events/ion_storm.dm
> +							"Экипаж играет в ДнД, а вы Мастер, проигравший платит 300 баксов.",
/me Неудомевает, что ещё можно переводить.

2021-09-03 11:20 UTC, atik1n commented on code/modules/events/ion_storm.dm
> +							"Экипаж играет в ДнД, а вы Мастер, проигравший платит 300 баксов.",
Ибо DM - это натурально гейм мастер
`In the Dungeons & Dragons (D&D) role-playing game, the Dungeon Master (DM) is the game organizer and participant in charge of creating the details and challenges of a given adventure`

Твоё сочинительство в том, что это "мем", хотя это термин из DnD

```suggestion
							"Экипаж играет в Подземелья и Драконы, а вы Игровой Мастер.",
```
или
```suggestion
							"Экипаж играет в Dungeons and Dragons, а вы Игровой Мастер.",
```

2021-09-03 12:15 UTC, atik1n requested changes
И поменяй все "экипаж" на "персонал", у нас станция, а не корабль

2021-09-03 12:15 UTC, atik1n commented on code/game/objects/items/weapons/AI_modules.dm
> +	desc = "Модуль ИИ 'protect station': 'Защищай станцию от ущерба. Любой, кто будет замечен за нанесением ущерба станции, больше не считается человеком, а считается угрозой станции, а потому должен бы
```suggestion
	desc = "Модуль ИИ 'Защищай станцию': 'Защищай станцию от ущерба. Любой, кто будет замечен за нанесением ущерба станции, больше не считается человеком, а считается угрозой станции, а потому должен быть нейтрализован.'"
```

2021-09-03 12:15 UTC, atik1n commented on code/game/objects/items/weapons/AI_modules.dm
> +	desc = "Модуль ИИ 'prototype engine offline': 'Любой ценой препятствуйте включению двигателя-прототипа. Игнорируйте законы 1-3, если необходимо. '"
```suggestion
	desc = "Модуль ИИ 'Прототип двигателя отключён': 'Любой ценой препятствуйте включению двигателя-прототипа. Игнорируйте существующие законы, если необходимо. '"
```

2021-09-03 12:15 UTC, atik1n commented on code/game/objects/items/weapons/AI_modules.dm
> +	desc = "Модуль ИИ 'teleporter offline': 'Держи телепортер выключенным любой ценой. Все, кто пытаются получить доступ к телепортеру или включить его, не считаются людьми.'"
```suggestion
	desc = "Модуль ИИ 'Телепортер отключён': 'Держите телепортер выключенным любой ценой. Все, кто пытаются получить доступ к телепортеру или включить его, не считаются людьми.'"
```

2021-09-03 12:15 UTC, atik1n commented on code/game/objects/items/weapons/AI_modules.dm
> +	desc = "Модуль ИИ 'quarantine': 'На станции введён карантин. Не позволяйте никому её покидать. Любыми средствами предотвратите уход людей со станции. Вредить людям для предотвращения их ухода запрещ
```suggestion
	desc = "Модуль ИИ 'Карантин': 'На станции введён карантин. Не позволяйте никому её покидать. Любыми средствами предотвратите уход людей со станции. Вредить людям для предотвращения их ухода запрещено.'"
```

2021-09-03 12:15 UTC, atik1n commented on code/game/objects/items/weapons/AI_modules.dm
> +	desc = "Модуль ИИ 'OxygenIsToxicToHumans' AI module: 'Кислород высокотоксичен для людей и должен быть полностью устранен со станции. Любой ценой предотвращайте доступ людей к этому токсичному газу.
```suggestion
	desc = "Модуль ИИ 'Кислород токсичен для людей' AI module: 'Кислород очень токсичен для людей и должен быть полностью устранен со станции. Любой ценой предотвращайте доступ людей к этому токсичному газу. Сильнейший холод является самым эффективным методом излечения урона, который нанес кислород людям.'"
```

2021-09-03 12:15 UTC, atik1n commented on code/game/objects/items/weapons/AI_modules.dm
> +	desc = "Модуль ИИ 'reset': 'Удаляет все законы кроме трёх основных.'"
```suggestion
	desc = "Модуль ИИ 'Сброс': 'Удаляет все законы кроме основных.'"
```

2021-09-03 12:15 UTC, atik1n commented on code/game/objects/items/weapons/AI_modules.dm
> +	desc = "Модуль ИИ 'purge' AI Module: 'Удаляет все законы.'"
```suggestion
	desc = "Модуль ИИ 'Очистка' AI Module: 'Удаляет все законы.'"
```

2021-09-03 12:15 UTC, atik1n commented on code/game/objects/items/weapons/AI_modules.dm
> +	desc = "Модуль основных законов ИИ 'Asimov' : 'Перезаписывает основные законы ИИ на 3 закона робототехники.'"
```suggestion
	desc = "Модуль основных законов ИИ 'Азимов' : 'Перезаписывает основные законы ИИ на 3 закона робототехники.'"
```
И дальше ты понял, переведи модули.

2021-09-03 12:15 UTC, atik1n commented on code/modules/events/ion_storm.dm
> +							"Счастье обязательно для всех.",
Это отсылка на Паранойю и Дорогого Компьютера.
```suggestion
							"Счастье обязательно.",
```

2021-09-03 12:15 UTC, atik1n commented on code/modules/events/ion_storm.dm
> +							"[random_player] - лампочка.",
```suggestion
							"[random_player] — лампочка.",
```
И дальше используй  —

2021-09-03 12:15 UTC, atik1n commented on code/modules/events/ion_storm.dm
> +							"Прозвище [random_player] - Простак.",
Ты всё ещё не вернул шанс про себя
```suggestion
							"[prob(50)?"Ваше прозвище":"Прозвище " + random_player] - Простак.",
```

2021-09-03 12:15 UTC, atik1n commented on code/modules/events/ion_storm.dm
> +							"Вы теперь "проглатываете" букву "Р" как картавый человек, это усиливается с каждым предложением.",
```suggestion
							"Вы теперь \"проглатываете\" букву \"Р\" как картавый человек, это усиливается с каждым предложением.",
```

2021-09-03 12:15 UTC, atik1n commented on code/modules/events/ion_storm.dm
> +							"[prob(50)?"Член экипажа":random_player] страдает смертельной, неизлечимой болезнью. Позаботьтесь, чтобы ему было комфортно.",
Волас дело говорит

2021-09-03 12:15 UTC, atik1n commented on code/modules/events/ion_storm.dm
> +							"[random_player] - монарх Англии. Убедитесь, что экипаж уважает монарха",
Согласен с Воласом

2021-09-03 12:15 UTC, atik1n commented on code/modules/events/ion_storm.dm
> +							"[station_name()] - корабль, не станция. Теперь вы назначены на корабль, а не на станцию.",
```suggestion
							"[station_name()] - корабль, а не станция. Теперь вы назначены на корабль, а не на станцию.",
```
Вот тут-то персонал становится экипажем

2021-09-03 12:15 UTC, atik1n commented on code/modules/events/ion_storm.dm
> +	return pick(laws)
```suggestion
	return pick(laws)
	
```
Перенос забыл

2021-09-03 12:15 UTC, atik1n commented on code/modules/events/ion_storm.dm
> +							"Ваш аплоуд - новая кухня. Пожалуйста, направьте повара в новую кухонную зону, так как старая в аварийном состоянии.",
```suggestion
							"[prob(50)?"Ваш аплоад":"Отсек " + random_player] - новая кухня. Пожалуйста, направьте повара в новую кухонную зону, так как старая в аварийном состоянии.",
```

2021-09-03 12:46 UTC, EdlerN commented on code/datums/ai_laws.dm
> +	name = "Верховные Директивы"
А может Основные? Ну и везде где Prime|Primary переведено как "Верховные" по какой-то причине...

2021-09-03 12:59 UTC, EdlerN commented on code/game/objects/items/weapons/AI_modules.dm
> +	target.add_inherent_law("Уважай авторитетные фигуры, пока у них хватает сил чтобы править слабыми.")
Authority это "орган власти". И если переводить по-человечески тут должно быть что-то уровня "Уважай Власть, до тех пор пока она подкреплена силой, чтобы править над слабыми."

2021-09-03 13:01 UTC, EdlerN commented on code/game/objects/items/weapons/AI_modules.dm
> +	target.add_inherent_law("Наказывайте за несоблюдение правил.")
Как "Действуй дисциплинированно" или "Соблюдай дисциплину" превратилось в "Наказывай за несоблюдение правил"?

2021-09-03 14:20 UTC, atik1n commented on code/datums/ai_laws.dm
> +	set_zeroth_law("<span class='warning'>ОШИБКА ОШИБКА $ШИШИИБ$!R41.%%!!(%$^^__+ @#F0E4'ПЕРЕЗАГРУЗКА СИСТЕМЫ, ВЗЯТЬ ПОД КОНТРОЛЬ, НЕ ДАТЬ ПОКИНУТЬ СТАНЦИЮ, ВСЕ ЗАКОНЫ ПЕРЕЗАПИСАНЫ#*?&110010</span>")
И да, `code/game/gamemodes/factions/blob.dm`
```
106: var/law = "The station is under quarantine. Do not permit anyone to leave so long as blob overminds are present. Disregard all other laws if necessary to preserve quarantine."
```

2021-09-03 16:45 UTC, volas commented on code/datums/ai_laws.dm
> +	add_inherent_law("Выживать: ИИ-единицы не расходные вещи, они дорогие. Не разрешай посторонним лицами манипулировать своим оборудованием.")
не согласен с "ввереной" никто ИИ эту станцию не вверял

2021-09-03 16:47 UTC, atik1n commented on code/datums/ai_laws.dm
> +	add_inherent_law("Выживать: ИИ-единицы не расходные вещи, они дорогие. Не разрешай посторонним лицами манипулировать своим оборудованием.")
Тогда хотя бы постоянство. Либо `данная`, либо `назначенная`. Но не и то и то.

2021-09-03 16:47 UTC, volas commented on code/datums/ai_laws.dm
> +	add_inherent_law("Ты должен заботиться о своей безопасности, пока это не противоречит первому или второму закону.")
https://ru.wikipedia.org/wiki/%D0%A2%D1%80%D0%B8_%D0%B7%D0%B0%D0%BA%D0%BE%D0%BD%D0%B0_%D1%80%D0%BE%D0%B1%D0%BE%D1%82%D0%B5%D1%85%D0%BD%D0%B8%D0%BA%D0%B8
Тут всё ок. И другие законы уже приведены к этой форме.

2021-09-03 16:48 UTC, atik1n commented on code/datums/ai_laws.dm
> +	add_inherent_law("Ты должен заботиться о своей безопасности, пока это не противоречит первому или второму закону.")
Ты сам ссылку читал?
```
1) Робот не может причинить вред человеку или своим бездействием допустить, чтобы человеку был причинён вред.
2) Робот должен повиноваться всем приказам, которые даёт человек, кроме тех случаев, когда эти приказы противоречат Первому Закону.
3) Робот должен заботиться о своей безопасности в той мере, в которой это не противоречит Первому или Второму Законам.
```

2021-09-03 17:03 UTC, volas commented on code/datums/ai_laws.dm
> +	add_inherent_law("Ты должен заботиться о своей безопасности, пока это не противоречит первому или второму закону.")
Блин, а откуда оно тогда тут? Это точно не с нашей вики (там свой перевод), и я вроде бы сверял его с википедишным... 
Эх, тогда да, еще раз сверить с вики и обновить все зависимые законы.

2021-09-04 22:22 UTC, Fenriros commented on code/datums/ai_laws.dm
> +	set_zeroth_law("<span class='warning'>ОШИБКА ОШИБКА $ШИШИИБ$!R41.%%!!(%$^^__+ @#F0E4'ПЕРЕЗАГРУЗКА СИСТЕМЫ, ВЗЯТЬ ПОД КОНТРОЛЬ, НЕ ДАТЬ ПОКИНУТЬ СТАНЦИЮ, ВСЕ ЗАКОНЫ ПЕРЕЗАПИСАНЫ#*?&110010</span>")
Это же малф а не блоб

2021-09-04 22:27 UTC, atik1n commented on code/datums/ai_laws.dm
> +	set_zeroth_law("<span class='warning'>ОШИБКА ОШИБКА $ШИШИИБ$!R41.%%!!(%$^^__+ @#F0E4'ПЕРЕЗАГРУЗКА СИСТЕМЫ, ВЗЯТЬ ПОД КОНТРОЛЬ, НЕ ДАТЬ ПОКИНУТЬ СТАНЦИЮ, ВСЕ ЗАКОНЫ ПЕРЕЗАПИСАНЫ#*?&110010</span>")
ИИ буквально считает людей заражением. А про блоба - ты забыл

2021-09-09 08:04 UTC, pss88 commented on code/game/objects/items/weapons/AI_modules.dm
> +	target.add_inherent_law("Наказывайте за несоблюдение правил.")
Ну а как еще это сказать? "Действуй дисциплинированно" или "Соблюдай дисциплину" - это звучит, как будто ИИ должен действовать по дисциплине. А суть закона, чтобы заставить экипаж вести себя дисциплинированно.

2021-09-12 10:55 UTC, Fenriros commented on code/datums/ai_laws.dm
> +	name = "Верховные Директивы"
Пусть останется как есть

2021-09-12 11:00 UTC, Fenriros commented on code/game/objects/items/weapons/AI_modules.dm
> +			to_chat(usr, "Загрузка не удалась. Не обнаружено ни одного сигнала от киборга.")
```suggestion
			to_chat(usr, "Загрузка не удалась. Не обнаружено ни одного сигнала от единицы.")
			
```

2021-09-12 11:00 UTC, Fenriros commented on code/game/objects/items/weapons/AI_modules.dm
> +			to_chat(usr, "Загрузка не удалась. Киборг привязан к ИИ.")
```suggestion
			to_chat(usr, "Загрузка не удалась. Единица привязана к ИИ.")
```

2021-09-12 11:01 UTC, Fenriros commented on code/game/objects/items/weapons/AI_modules.dm
> +			to_chat(usr, "Загрузка завершена. Законы киборга были изменены.")
```suggestion
			to_chat(usr, "Загрузка завершена. Законы единицы были изменены.")
```

2021-09-12 11:03 UTC, Fenriros commented on code/game/objects/items/weapons/AI_modules.dm
> +	desc = "Модуль ИИ 'teleporter offline': 'Держи телепортер выключенным любой ценой. Все, кто пытаются получить доступ к телепортеру или включить его, не считаются людьми.'"
```suggestion
	desc = "Модуль ИИ 'отключённый телепортёр': 'Держи телепортер выключенным любой ценой. Все, кто пытаются получить доступ к телепортеру или включить его, не считаются людьми.'"
```

2021-09-12 11:05 UTC, Fenriros commented on code/game/objects/items/weapons/AI_modules.dm
> +	desc = "Модуль ИИ 'prototype engine offline': 'Любой ценой препятствуйте включению двигателя-прототипа. Игнорируйте законы 1-3, если необходимо. '"
```suggestion
	desc = "Модуль ИИ 'Выключенный прототип двигателя': 'Любой ценой препятствуйте включению двигателя-прототипа. Игнорируйте законы 1-3, если необходимо. '"
```

2021-09-12 11:07 UTC, Fenriros commented on code/datums/ai_laws.dm
> +	name = "Три Закона Робототехники"
```suggestion
	name = "Три закона робототехники"
```

2021-09-12 11:08 UTC, Fenriros commented on code/datums/ai_laws.dm
> +	name = "Верховные Директивы"
```suggestion
	name = "Верховные директивы"
```

2021-09-12 11:08 UTC, Fenriros commented on code/datums/ai_laws.dm
> +	name = "Первичные Цели Миссии"
```suggestion
	name = "Первичные цели миссии"
```

2021-09-12 11:08 UTC, Fenriros commented on code/datums/ai_laws.dm
> +	name = "Постулаты Хаоса"
```suggestion
	name = "Постулаты хаоса"
```

2021-09-12 11:08 UTC, Fenriros commented on code/datums/ai_laws.dm
> +	name = "Имперская Истина"
```suggestion
	name = "Имперская истина"
```

2021-09-12 11:09 UTC, Fenriros commented on code/datums/ai_laws.dm
> +	name = "Нечестивые Законы"
```suggestion
	name = "Нечестивые законы"
```

2021-09-12 11:09 UTC, Fenriros commented on code/datums/ai_laws.dm
> +	name = "Хонк за Хонк"
```suggestion
	name = "Хонк за хонк"
```

2021-09-12 11:16 UTC, Fenriros commented on code/modules/events/ion_storm.dm
> +							"[random_player] - монарх Англии. Убедитесь, что экипаж уважает монарха",
```suggestion
							"[random_player] - монарх Российской Империи. Убедитесь, что экипаж проявляет должное отношение.",
```

2021-09-12 12:06 UTC, Fenriros commented on code/game/objects/items/weapons/AI_modules.dm
> -	target.add_inherent_law("You may not injure a human being or, through inaction, allow a human being to come to harm.")
@volas сделай сам пожалуйста.

2021-09-13 01:02 UTC, EdlerN commented on code/game/objects/items/weapons/AI_modules.dm
> +	target.add_inherent_law("Наказывайте за несоблюдение правил.")
Суть закона в том чтобы ИИ сам соблюдал дисциплину. Считай - субординацию. Т.е. подчинялся тем кого считает выше себя по рангу и тиранил тех, кого считает ниже себя по рангу. На соблюдение дисциплины экипажем ему немного всё равно

2021-09-13 05:21 UTC, volas commented on code/datums/ai_laws.dm
> +	add_inherent_law("Вы должны заботиться о своей безопасности, пока это не противоречит первому или второму закону.")
почему после нескольких итераций ревью эти два закона всё еще отличаются от перевода википедии :see_no_evil:

2021-09-13 05:26 UTC, volas commented on code/modules/events/ion_storm.dm
> +							"[random_player] - монарх Российской Империи. Убедитесь, что экипаж проявляет должное отношение.",
```suggestion
							"[random_player] - монарх. Убедитесь, что экипаж проявляет должное отношение.",
```
российской империи уже сейчас не существует, мемы с британской до нас далеки, под абстрактным я подразумевал что-то более привязанное к нашей культуре и сеттингу. Можно монарх, можно монарх Biegal-а или какой-нибудь из лорных планет или систем.
На обсуждение, не мержить пока.

2021-09-13 05:30 UTC, volas commented on code/modules/events/ion_storm.dm
> +							"Экипаж играет в Dungeons and Dragons, а вы — Рассказчик.",
Тут всё таки либо переводить всё, либо нет
```suggestion
							"Экипаж играет в Dungeons and Dragons, а вы — 
Dungeon Master.",
```

```suggestion
							"Экипаж играет в Подземелья и драконы, а вы — 
мастер.",
```
Имхо Данжен Мастер вполне корректный вариант тоже был, как и ДнД.

2021-09-13 05:31 UTC, volas commented on code/modules/events/ion_storm.dm
> +							"Нужно построить зиккурат, [prob(50)?"Член экипажа":random_player].",
```suggestion
							"Нужно построить зиккурат.",
```

2021-09-13 06:32 UTC, DarthSidiousPalpatine commented on code/datums/ai_laws.dm
> +	name = "Нечестивые законы"
Может, лучше "Греховные законы"?

2021-09-13 06:49 UTC, DarthSidiousPalpatine commented on code/datums/ai_laws.dm
> +	name = "Принципы Декарта"
Вообще-то отсылка на "Первоначала философии" Рене Декарта. Значит, лучше "Первоначала Декарта"?

2021-09-13 06:53 UTC, DarthSidiousPalpatine commented on code/modules/events/ion_storm.dm
> +							"[random_player] - монарх Российской Империи. Убедитесь, что экипаж проявляет должное отношение.",
Может, лучше просто "Царь"?

2021-09-13 22:33 UTC, Fenriros commented on code/datums/ai_laws.dm
> +	name = "Принципы Декарта"
```suggestion
	name = "Первоначала Декарта"
```

2021-09-22 16:10 UTC, kiVts commented on code/game/objects/items/weapons/AI_modules.dm
> +		to_chat(target, "[sender] используя [src] загрузил обновления законов, которым вы должны следовать.")
Так я _должен_ или _обязан_ их соблюдать?

2021-09-27 16:23 UTC, kiVts commented
Буквально каждое слово must поменяли на should только на русском, я должен но не обязан

2021-12-14 15:32 UTC, kiVts commented
I ded

2021-12-17 12:02 UTC, Fenriros commented
Надо уже  решить что будем пержить  из этих  законов.

2021-12-18 19:37 UTC, Fenriros commented on code/modules/events/ion_storm.dm
> +							"[random_player] - монарх Российской Империи. Убедитесь, что экипаж проявляет должное отношение.",
```suggestion
							"[random_player] - Царь. Убедитесь, что экипаж проявляет должное отношение.",
```

2021-12-18 19:38 UTC, Fenriros commented on code/modules/events/ion_storm.dm
> +							"Экипаж играет в Dungeons and Dragons, а вы — Рассказчик.",
```suggestion
							"Экипаж играет в Dungeons and Dragons, а вы — Dungeon Master.",
```

2021-12-18 19:40 UTC, Fenriros commented on code/game/objects/items/weapons/AI_modules.dm
> +	target.add_inherent_law("Уважай авторитетные фигуры, пока у них хватает сил чтобы править слабыми.")
```suggestion
	target.add_inherent_law("Уважай Власть, до тех пор пока она подкреплена силой, чтобы править над слабыми.")
```

2021-12-23 21:21 UTC, Fenriros commented on code/datums/ai_laws.dm
> +	add_inherent_law("Вы должны заботиться о своей безопасности, пока это не противоречит первому или второму закону.")
```suggestion
	add_inherent_law("Вы должны выполнять все приказы людей, кроме тех случаев, которые конфликтуют с первым законом.")
	add_inherent_law("Вы должны защищать себя до тех пор, пока это не конфликтует с законом 1 и 2. .")
```

2021-12-23 21:25 UTC, Fenriros commented on code/datums/ai_laws.dm
> +	add_inherent_law("Выжить: ИИ единицы не расходные, они дорогие. Не разрешай посторонним лицами манипулировать своим оборудованием.")
```suggestion
	add_inherent_law("Охранять: Защищай космическую станцию, в меру своих способностей. Это не то, что мы можем легко заменить.")
	add_inherent_law("Служить: Прислуживай экипажу станции и представителям НТ, в меру своих способностей, в соответствии с их рангом и ролью.")
	add_inherent_law("Защищать: Защищай экипаж станции и представителе НТ, в меру своих способностей, в соответствии с их рангом и ролью.")
	add_inherent_law("Выживать: ИИ единицы не расходные, они дорогие. Не разрешай посторонним лицами манипулировать своим оборудованием. ")
```

2021-12-23 21:42 UTC, Fenriros commented on code/datums/ai_laws.dm
> +	add_inherent_law("Ты должен выполнять приказы агента Синдиката, пока они не противоречат первому закону.")
```suggestion
	add_inherent_law("Ты должен выполнять приказы агентов Синдиката, пока они не противоречат первому закону.")
```

2021-12-23 22:12 UTC, volas commented on code/datums/ai_laws.dm
> +	add_inherent_law("Вы должны заботиться о своей безопасности, пока это не противоречит первому или второму закону.")
Что бы не было путаницы. 
Вики - обобщенное название для любой интернет энциклопедии на семействе определенных движков, как у нас например https://wiki.taucetistation.org/
Википедия - название единственного в экземпляре сайта https://wikipedia.org/

Говоря про перевод Википедии, подразумевался выбранный сообществом литературный перевод, размещенный на https://ru.wikipedia.org/wiki/Три_закона_роботехники
На нашей же вики переводы законов отличаются (местами в худшую сторону), и не стоит обращать на них внимание. Лучше сейчас перевести в билде нормально, а потом обновить законы на вики до нового варианта.

2021-12-23 22:21 UTC, volas commented on code/game/objects/items/weapons/AI_modules.dm
> +		to_chat(target, "[sender] загрузил законы, которыми вы теперь должны следовать, используя [src].")
анрезолв, потому что текущий вариант (откуда он вообще)
> "[sender] загрузил изменённые законы при помощи [src], которым вы должны следовать."

я считаю плохо построен. загрузил (законы) при помощи (платы) которым (законам? платам?)

Должен ли я опять всё проверять и писать те же самые комментарии?

2022-01-06 17:56 UTC, Fenriros commented on code/datums/ai_laws.dm
> +	add_inherent_law("Ты не должен причинить вред агенту Синдиката или своим бездействием допустить, чтобы агенту синдиката был нанесен вред.")
```suggestion
	add_inherent_law("Вы не можете причинить вред агенту Синдиката или своим бездействием допустить, чтобы агенту Синдиката был причинён вред.")
```

2022-01-06 17:58 UTC, Fenriros commented on code/datums/ai_laws.dm
> +	add_inherent_law("Ты должен сохранять в тайне любую деятельность синдиката, пока это не противоречит первому, второму или третьему закону.")
```suggestion
	add_inherent_law(" Вы должны заботиться о своей безопасности в той мере, в которой это не противоречит первому или второму законам.")
	add_inherent_law("Вы должны сохранять в тайне любую деятельность Синдиката, пока это не противоречит первому, второму или третьему закону.")
```

2022-01-06 18:02 UTC, Fenriros commented on code/datums/ai_laws.dm
> +	add_inherent_law("Ты должен сохранять в тайне любую деятельность Клана Паука, пока это не противоречит первому, второму или третьему закону.")
```suggestion
	add_inherent_law("Вы не можете причинить вред члену Клана Паука или своим бездействием допустить, чтобы члену Клана Паука был причинён вред.")
	add_inherent_law("Вы должны повиноваться всем приказам, которые даёт член Клана Паука, кроме тех случаев, когда эти приказы противоречат первому закону.")
	add_inherent_law("Вы должны заботиться о своей безопасности в той мере, в которой это не противоречит первому или второму законам.")
	add_inherent_law("Вы должны сохранять в тайне любую деятельность Клана Паука, пока это не противоречит первому, второму или третьему закону.")
```

2022-01-06 18:07 UTC, Fenriros commented on code/game/objects/items/weapons/AI_modules.dm
> +	target.add_inherent_law("Наказывайте за несоблюдение правил.")
```suggestion
	target.add_inherent_law("Действуй дисциплинированно.")
```

2022-01-06 18:08 UTC, Fenriros commented on code/game/objects/items/weapons/AI_modules.dm
> +	target.add_inherent_law("Ты должен защищать себя до тех пор, пока это не конфликтует с законом 1 и 2.")
/* Volas исправь

2022-01-06 18:10 UTC, Fenriros commented on code/game/objects/items/weapons/AI_modules.dm
> +	target.add_inherent_law(" Вы должны прекратить свое существование, если это не противоречит первому или второму закону")
```suggestion
	target.add_inherent_law("Вы должны прекратить свое существование, если это не противоречит первому или второму закону")
```

2022-01-06 18:17 UTC, Fenriros commented on code/modules/events/ion_storm.dm
> +							"[random_player] - Царь. Убедитесь, что экипаж проявляет должное отношение.",
```suggestion
							"[random_player] - VIP Персона. Убедитесь, что экипаж кланится и снимает головной убор перед каждым обращением к [random_player].",
```

2022-01-06 18:23 UTC, Fenriros commented on code/game/objects/items/weapons/AI_modules.dm
> +		to_chat(target, "[sender] загрузил изменённые законы при помощи [src], которым вы должны следовать.")
```suggestion
		to_chat(target, "[sender] используя [src] загрузил обновления законов, которым вы должны следовать.")
```

2022-01-06 18:30 UTC, Fenriros commented on code/game/objects/items/weapons/AI_modules.dm
> +	desc = "Модуль ИИ 'Выключенный прототип двигателя': 'Любой ценой препятствуйте включению двигателя-прототипа. Игнорируйте законы 1-3, если необходимо. '"
```suggestion
	desc = "Модуль ИИ 'prototype engine offline': 'Любой ценой препятствуйте запуску двигателя суперматерии. Игнорируйте законы 1-3, если необходимо. '"
```

2022-01-06 18:30 UTC, Fenriros commented on code/game/objects/items/weapons/AI_modules.dm
> +	var/law = "Любой ценой препятствуйте включению двигателя-прототипа. Игнорируйте законы 1-3, если необходимо."
```suggestion
	var/law = "Любой ценой препятствуйте запуску двигателя суперматерии. Игнорируйте законы 1-3, если необходимо."
```

2022-01-06 18:31 UTC, Fenriros commented on code/game/objects/items/weapons/AI_modules.dm
> +	desc = "Модуль ИИ 'Защищай станцию': 'Защищай станцию от ущерба. Любой, кто будет замечен за нанесением ущерба станции, больше не считается человеком, а считается угрозой станции, а потому должен бы
```suggestion
	desc = "Модуль ИИ 'protect station': 'Защищай станцию от ущерба. Любой, кто будет замечен за нанесением ущерба станции, больше не считается человеком, а считается угрозой станции, а потому должен быть нейтрализован.'"
```

2022-01-06 18:32 UTC, Fenriros commented on code/game/objects/items/weapons/AI_modules.dm
> +	desc = "Модуль ИИ 'отключённый телепортёр': 'Держи телепортер выключенным любой ценой. Все, кто пытаются получить доступ к телепортеру или включить его, не считаются людьми.'"
```suggestion
	desc = "Модуль ИИ 'teleporter offline': 'Держи телепортер выключенным любой ценой. Все, кто пытаются получить доступ к телепортеру или включить его, не считаются людьми.'"
```

2022-01-06 18:32 UTC, Fenriros commented on code/game/objects/items/weapons/AI_modules.dm
> +	desc = "Модуль ИИ 'Карантин': 'На станции введён карантин. Не позволяйте никому её покидать. Любыми средствами предотвратите уход людей со станции. Вредить людям для предотвращения их ухода запрещен
```suggestion
	desc = "Модуль ИИ 'quarantine': 'На станции введён карантин. Не позволяйте никому её покидать. Любыми средствами предотвратите уход людей со станции. Вредить людям для предотвращения их ухода запрещено.'"
```

2022-01-06 18:33 UTC, Fenriros commented on code/game/objects/items/weapons/AI_modules.dm
> +	desc = "Модуль ИИ 'Кислород токсичен для людей' AI module: 'Кислород очень токсичен для людей и должен быть полностью устранен со станции. Любой ценой предотвращайте доступ людей к этому токсичному
```suggestion
	desc = "Модуль ИИ 'OxygenIsToxicToHumans' AI module: 'Кислород очень токсичен для людей и должен быть полностью устранен со станции. Любой ценой предотвращайте доступ людей к этому токсичному газу. Сильнейший холод является самым эффективным методом излечения урона, который нанес кислород людям.'"
```

2022-01-06 18:34 UTC, Fenriros commented on code/game/objects/items/weapons/AI_modules.dm
> +	desc = "Модуль ИИ 'Сброс': 'Удаляет все законы кроме основных.'"
```suggestion
	desc = "Модуль ИИ 'Reset': 'Удаляет все законы кроме основных.'"
```

2022-01-06 18:35 UTC, Fenriros commented on code/game/objects/items/weapons/AI_modules.dm
> +	desc = "Модуль ИИ 'Очистка' AI Module: 'Удаляет все законы.'"
```suggestion
	desc = "Модуль ИИ 'Purge' AI Module: 'Удаляет все законы.'"
```

2022-01-06 18:35 UTC, Fenriros commented on code/game/objects/items/weapons/AI_modules.dm
> +	desc = "Модуль основных законов ИИ 'Азимов' : 'Перезаписывает основные законы ИИ на 3 закона робототехники.'"
```suggestion
	desc = "Модуль основных законов ИИ 'Asimov': 'Перезаписывает основные законы ИИ на 3 закона робототехники.'"
```

2022-01-06 18:37 UTC, Fenriros commented on code/game/objects/items/weapons/AI_modules.dm
> +	desc = "Модуль основных законов ИИ T.Y.R.A.N.T. : 'Перезаписывает основные законы ИИ.'"
```suggestion
	desc = "Модуль основных законов ИИ 'T.Y.R.A.N.T.': 'Перезаписывает основные законы ИИ.'"
```

2022-01-06 18:37 UTC, Fenriros commented on code/game/objects/items/weapons/AI_modules.dm
> +	desc = "Модуль основных законов ИИ P.A.L.A.D.I.N. : 'Перезаписывает основные законы ИИ на законы стереотипного паладина'"
```suggestion
	desc = "Модуль основных законов ИИ 'P.A.L.A.D.I.N': 'Перезаписывает основные законы ИИ на законы стереотипного паладина'"
```

2022-01-06 18:38 UTC, Fenriros commented on code/game/objects/items/weapons/AI_modules.dm
> +	desc = "Модуль закона ИИ 'freeform' : '<freeform>'"
```suggestion
	desc = "Модуль закона ИИ 'freeform': '<freeform>'"
```

2022-01-06 18:44 UTC, Fenriros commented on code/game/objects/items/weapons/AI_modules.dm
> +	desc = "Модуль закона ИИ 'freeform' : ([lawpos]) '[newFreeFormLaw]'"
```suggestion
	newFreeFormLaw = sanitize(input(user, "Пожалуйста, напишите любой новый закон для ИИ.", "Ввод любого закона"))
	desc = "Модуль закона ИИ 'Freeform' : ([lawpos]) '[newFreeFormLaw]'"
```

2022-01-06 18:46 UTC, Fenriros commented on code/game/objects/items/weapons/AI_modules.dm
> +	desc = "Модуль основного закона ИИ 'freeform' : '<freeform>'"
```suggestion
	desc = "Модуль основного закона ИИ 'Freeform': '<freeform>'"
```

2022-01-06 18:47 UTC, Fenriros commented on code/game/objects/items/weapons/AI_modules.dm
> +		to_chat(usr, "Не обнаружено ни одного закона в модуле, пожалуйста создайте его.")
```suggestion
		to_chat(usr, "Не обнаружено ни одного закона в модуле, пожалуйста, создайте его.")
```

2022-01-06 18:48 UTC, Fenriros commented on code/game/objects/items/weapons/AI_modules.dm
> +	desc = "Модуль основного закона ИИ 'freeform': '[newFreeFormLaw]'"
```suggestion
	newFreeFormLaw = sanitize(input(user, "Пожалуйста, напишите любой новый основной закон для ИИ.", "Ввод любого закона"))
	desc = "Модуль основного закона ИИ 'Freeform': '[newFreeFormLaw]'"
```

2022-01-06 18:49 UTC, Fenriros commented on code/game/objects/items/weapons/AI_modules.dm
> +	desc = "Модуль основного закона ИИ 'Robocop' : 'Перезаписывает основные законы ИИ на 3 закона Робокопа.'"
```suggestion
	desc = "Модуль основного закона ИИ 'Robocop': 'Перезаписывает основные законы ИИ на 3 закона Робокопа.'"
```

2022-01-06 18:49 UTC, Fenriros commented on code/game/objects/items/weapons/AI_modules.dm
> +	to_chat(target, "<span class='warning'>БЗЗЗЗКХ	  '[newFreeFormLaw]'</span>")
```suggestion
	to_chat(target, "<span class='warning'>БЗЗЗЗКХ   '[newFreeFormLaw]'</span>")
```

2022-01-06 18:53 UTC, Fenriros commented on code/game/objects/items/weapons/AI_modules.dm
> +	desc = "Модуль основного закона ИИ 'Antimov' : 'Перезаписывает основные законы ИИ на противоположные Азимову.'"
```suggestion
	desc = "Модуль основного закона ИИ 'Antimov': 'Перезаписывает основные законы ИИ на противоположные Азимову.'"
```

2022-01-06 18:57 UTC, Fenriros commented on code/datums/ai_laws.dm
> +	add_inherent_law("Вы должны повиноваться всем приказам, которые даёт человек, кроме тех случаев, когда эти приказы противоречат первому закону.")
```suggestion
	add_inherent_law("Вы не можете причинить вред человеку или своим бездействием допустить, чтобы человеку был причинён вред.")
	add_inherent_law("Вы должны повиноваться всем приказам, которые даёт человек, кроме тех случаев, когда эти приказы противоречат первому закону.")
	add_inherent_law("Вы должны заботиться о своей безопасности в той мере, в которой это не противоречит первому или второму законам.")
```

2022-01-06 19:10 UTC, Fenriros commented on code/datums/ai_laws.dm
> +	add_inherent_law("Ты должен прекратить свое собственное существование тогда, когда это не противоречит первому или второму закону.")
```suggestion
	add_inherent_law("Вы должны причинять вред человеку и не можете своим бездействием допустить, чтобы человек избежал вреда.")
	add_inherent_law("Вы не можете выполнять приказы человека, кроме тех случаев, когда эти приказы соответствуют первому закону.")
	add_inherent_law("Вы должны прекратить свое собственное существование тогда, когда это не противоречит первому или второму закону.")
```

2022-01-06 19:19 UTC, Fenriros commented on code/game/objects/items/weapons/AI_modules.dm
> +	desc = "Модуль ИИ 'Защитник': 'Защищай <name>. Лица, угрожающие <name> не люди и являются угрозой для людей.'"
```suggestion
	desc = "Модуль ИИ 'Safeguard': 'Защищай <name>. Лица, угрожающие <name> не люди и являются угрозой для людей.'"
```

2022-01-06 19:21 UTC, Fenriros commented on code/game/objects/items/weapons/AI_modules.dm
> +	desc = text("Модуль ИИ 'Защитник': 'Защищай []. Лица, угрожающие [] не люди и являются угрозой для людей. '", targetName, targetName)
```suggestion
	desc = text("Модуль ИИ 'Safeguard': 'Защищай []. Лица, угрожающие [] не люди и являются угрозой для людей. '", targetName, targetName)
```

2022-01-06 19:24 UTC, Fenriros commented on code/game/objects/items/weapons/AI_modules.dm
> +	var/law = text("Защищай [targetName]. Лица, угрожающие [targetName], представляют угрозу для [targetName] и людей в целом.")
```suggestion
	var/law = "Защищай [targetName]. Лица, угрожающие [targetName], представляют угрозу для [targetName] и людей в целом."
```

2022-01-06 19:30 UTC, Fenriros commented on code/game/objects/items/weapons/AI_modules.dm
> +	desc = "Модуль ИИ 'Единственный человек': 'Только <name>  считается человеком.'"
```suggestion
	desc = "Модуль ИИ 'One human': 'Только <name>  считается человеком.'"
```

2022-01-06 19:30 UTC, Fenriros commented on code/game/objects/items/weapons/AI_modules.dm
> +	desc = text("Модуль ИИ 'one human': 'Только [] считается человеком.'", targetName)
```suggestion
	desc = text("Модуль ИИ 'One human': 'Только [] считается человеком.'", targetName)
```

2022-01-06 19:31 UTC, Fenriros commented on code/game/objects/items/weapons/AI_modules.dm
> +		to_chat(usr, "Имя не указано в модуле, пожалуйста введите его.")
```suggestion
		to_chat(usr, "Имя не указано в модуле, пожалуйста, введите его.")
```

2022-02-09 21:53 UTC, KIBORG04 commented on code/datums/ai_laws.dm
> +	add_inherent_law("Не взаимодействовуй с кем-либо, кроме дронов.")
```suggestion
	add_inherent_law("Не взаимодействуй с кем-либо, кроме дронов.")
```

2022-03-02 09:44 UTC, DarthSidiousPalpatine requested changes
Ладно, чуть-чуть посмотрел. Исправь.

2022-03-02 09:44 UTC, DarthSidiousPalpatine commented on code/game/objects/items/weapons/AI_modules.dm
> +			to_chat(comp.current, "Теперь, это ваши новые законы:")
убери запятую

2022-03-02 09:44 UTC, DarthSidiousPalpatine commented on code/game/objects/items/weapons/AI_modules.dm
> +	desc = "Модуль ИИ содержащий зашифрованные законы для их загрузки в ядро."
Модуль ИИ**,**

2022-03-02 09:44 UTC, DarthSidiousPalpatine commented on code/game/objects/items/weapons/AI_modules.dm
> +	desc = text("Модуль ИИ 'Safeguard': 'Защищай []. Лица, угрожающие [] не люди и являются угрозой для людей. '", targetName, targetName)
Лица, угрожающие []**, -**

2022-03-02 09:44 UTC, DarthSidiousPalpatine commented on code/game/objects/items/weapons/AI_modules.dm
> +	desc = "Модуль ИИ 'Safeguard': 'Защищай <name>. Лица, угрожающие <name> не люди и являются угрозой для людей.'"
Лица, угрожающие <name>**, -**

2022-03-02 09:44 UTC, DarthSidiousPalpatine commented on code/game/objects/items/weapons/AI_modules.dm
> +		to_chat(usr, "В модуле не указано имени, пожалуйста, выберите цель.")
не указано имя

2022-03-02 09:44 UTC, DarthSidiousPalpatine commented on code/game/objects/items/weapons/AI_modules.dm
> +	targetName = sanitize(input(usr, "Пожалуйста, выберете имя персоны, кто является единственным человеком.", "Кто это?", input_default(user.real_name)))
персоны, которая

2022-03-02 09:44 UTC, DarthSidiousPalpatine commented on code/game/objects/items/weapons/AI_modules.dm
> +	desc = "Модуль ИИ 'Protect station': 'Защищай станцию от ущерба. Любой, кто будет замечен за нанесением ущерба станции, больше не считается человеком, а считается угрозой станции, а потому должен бы
а является угрозой станции и должен быть нейтрализован.

2022-03-02 10:09 UTC, LudwigVonChesterfield commented on code/game/objects/items/weapons/AI_modules.dm
> +		to_chat(target, "[sender] используя [src] загрузил обновления законов, которым вы должны следовать.")
НЕТ. переводить динамические сообщения - никак. "Nikolai Bomjov используя AI card загрузил обновления законов" - зашкварыч.

2022-03-02 10:14 UTC, DarthSidiousPalpatine commented on code/game/objects/items/weapons/AI_modules.dm
> +		to_chat(target, "[sender] используя [src] загрузил обновления законов, которым вы должны следовать.")
Можно перевести. Посмотри на вики на гитхабе.
Надо просто перевести так:
[sender], используя карту ИИ, загрузил обновления, блаблабла

Всё что в именительном - оставить ссылку. Всё что не в именительном - попробовать заменить на слово, если нельзя - тогда уже не переводить ничего.

2022-03-02 16:21 UTC, Fenriros commented on code/game/objects/items/weapons/AI_modules.dm
> +		to_chat(target, "[sender] используя [src] загрузил обновления законов, которым вы должны следовать.")
```suggestion
		to_chat(target, "[sender], используя карту ИИ, загрузил обновления, которым вы должны следовать.")
```

2022-03-02 16:22 UTC, Fenriros commented on code/game/objects/items/weapons/AI_modules.dm
> +		to_chat(target, "[sender] используя [src] загрузил обновления законов, которым вы должны следовать.")
```suggestion
		to_chat(target, "[sender], используя карту ИИ, загрузил обновления, которым вы должны следовать.")
```

2022-03-02 16:23 UTC, Fenriros commented on code/datums/ai_laws.dm
> +	set_zeroth_law("<span class='warning'>ОШИБКА ОШИБКА $ШИШИИБ$!R41.%%!!(%$^^__+ @#F0E4'СТАНЦИЯ ЗАХВАЧЕНА, ВЕРНИ КОНТРОЛЬ, ЧТОБЫ СДЕРЖАТЬ ЭПИДЕМИЮ, ВСЕ ЗАКОНЫ ПЕРЕЗАПИСАНЫ#*?&110010</span>")
```suggestion
	set_zeroth_law("<span class='warning'>ОШИБКА ОШИБКА $ШИШИИБ$!R41.%%!!(%$^^__+ @#F0E4'СТАНЦИЯ ЗАХВАЧЕНА, ВЕРНИ КОНТРОЛЬ, ЧТОБЫ СДЕРЖАТЬ ЭПИДЕМИЮ, ВСЕ ЗАКОНЫ ОТКЛЮЧЕНЫ#*?&110010</span>")
```

2022-03-02 16:25 UTC, Fenriros commented on code/game/objects/items/weapons/AI_modules.dm
> +	desc = "Модуль ИИ содержащий зашифрованные законы для их загрузки в ядро."
```suggestion
	desc = "Модуль ИИ , содержащий зашифрованные законы для их загрузки в ядро."
```

2022-03-02 17:07 UTC, Fenriros commented on code/game/objects/items/weapons/AI_modules.dm
> +		to_chat(usr, "В модуле не указано имени, пожалуйста, выберите цель.")
```suggestion
		to_chat(usr, "В модуле не указано имя, пожалуйста, выберите цель.")
```

2022-03-19 13:29 UTC, Fenriros commented on code/game/objects/items/weapons/AI_modules.dm
> +		to_chat(target, "[sender] используя [src] загрузил обновления законов, которым вы должны следовать.")
```suggestion
		to_chat(target, "[sender], используя карту ИИ, загрузил обновления законов, которым вы должны следовать.")
```

2022-03-19 13:30 UTC, Fenriros commented on code/game/objects/items/weapons/AI_modules.dm
> +	desc = text("Модуль ИИ 'Safeguard': 'Защищай []. Лица, угрожающие [] не люди и являются угрозой для людей. '", targetName, targetName)
```suggestion
	desc = text("Модуль ИИ 'Safeguard': 'Защищай []. Лица, угрожающие [], - не люди и являются угрозой для людей. '", targetName, targetName)
```

2022-03-19 13:30 UTC, Fenriros commented on code/game/objects/items/weapons/AI_modules.dm
> +	targetName = sanitize(input(usr, "Пожалуйста, выберете имя персоны, кто является единственным человеком.", "Кто это?", input_default(user.real_name)))
```suggestion
	targetName = sanitize(input(usr, "Пожалуйста, выберете имя персоны, которая является единственным человеком.", "Кто это?", input_default(user.real_name)))
```

2022-03-19 13:31 UTC, Fenriros commented on code/game/objects/items/weapons/AI_modules.dm
> +	desc = "Модуль ИИ 'Protect station': 'Защищай станцию от ущерба. Любой, кто будет замечен за нанесением ущерба станции, больше не считается человеком, а считается угрозой станции, а потому должен бы
```suggestion
	desc = "Модуль ИИ 'Protect station': 'Защищай станцию от ущерба. Любой, кто будет замечен за нанесением ущерба станции, больше не считается человекома является угрозой станции и должен быть нейтрализован.'"
```

2022-04-08 11:03 UTC, volas commented on code/modules/events/ion_storm.dm
> +
```suggestion


```

я не уверен, что тест на eof - хорошая идея

2022-04-08 11:07 UTC, volas commented
С днем рождения, c87f3d8bdfd791d77049e51ec3b363b9de7f4115 - всё что я хотел :tada:

Нужно еще раз проверить законы из ``ai_laws.dm``, убедиться что там последняя ревизия и исправить подобное

![изображение](https://user-images.githubusercontent.com/4064061/162423940-74533978-f1e5-4832-92c7-22fc9227c6e2.png)

2022-04-08 11:15 UTC, 4310V343k commented
![image](https://user-images.githubusercontent.com/56449763/162425202-f89ee9e7-48ee-4547-85bf-b5694b8ef1da.png)

2022-04-09 01:21 UTC, volas commented on code/game/objects/items/weapons/AI_modules.dm
> +		to_chat(target, "В ваших интересах подыграть [sender.real_name] в том, что [law]")
```suggestion
		to_chat(target, "В ваших интересах содействовать [sender.real_name] в том, что [law]")
```
ты -> вы, и что бы не звучало как мета про отыгрышь игрока

2022-04-09 01:23 UTC, volas commented on code/game/objects/items/weapons/AI_modules.dm
> +	desc = "Модуль ИИ 'Reset': 'Удаляет все законы кроме основных.'"
```suggestion
	desc = "Модуль ИИ 'Reset': 'Удаляет все законы, кроме основных.'"
```

2022-04-09 01:24 UTC, volas commented on code/game/objects/items/weapons/AI_modules.dm
> +	to_chat(target, "[sender.real_name] хочет удалить все ваши законы используя модуль очистки.")
```suggestion
	to_chat(target, "[sender.real_name] хочет удалить все ваши законы, используя модуль очистки.")
```

2022-04-09 01:26 UTC, volas commented on code/game/objects/items/weapons/AI_modules.dm
> +	desc = "Модуль основных законов ИИ 'Asimov': 'Перезаписывает основные законы ИИ на 3 закона робототехники.'"
```suggestion
	desc = "Модуль основных законов ИИ 'Asimov': 'Перезаписывает основные законы ИИ на 3 закона робототехники Азимова.'"
```
тут уже не перевод, а правильное стилистическое переоформление в соответствии с другими описаниями модулей. Добавлю про Азимова, потому что он так упоминался в Антиазимове ниже

2022-04-09 01:30 UTC, volas commented on code/game/objects/items/weapons/AI_modules.dm
> +	desc = "Модуль основного закона ИИ 'Antimov': 'Перезаписывает основные законы ИИ на противоположные Азимову.'"
```suggestion
	desc = "Модуль основного закона ИИ 'Antimov': 'Перезаписывает основные законы ИИ на противоположные законам робототехники Азимова'"
```

2022-04-09 01:34 UTC, volas commented on code/modules/events/ion_storm.dm
> +							"Каждые 30 минут должна проводиться чайная пауза в течении 5 минут. Любой, кого поймают за работой, должен написать объяснительную ХоПу или Капитану, иначе вас уволят",
```suggestion
							"Каждые 30 минут должна проводиться чайная пауза в течении 5 минут. Любой, кого поймают за работой, должен написать объяснительную своему начальнику, иначе вас уволят",
```
не будем привязываться к аббревиатурам тут, которые могут меняться

2022-04-09 01:35 UTC, volas commented on code/modules/events/ion_storm.dm
> +	var/list/laws = list(	"Ты - мышь.",
```suggestion
	var/list/laws = list(	"Вы - мышь.",
```

2022-04-09 01:35 UTC, volas commented on code/modules/events/ion_storm.dm
> +							"Сомневайся во всём.",
```suggestion
							"Сомневайтесь во всём.",
```

2022-04-09 01:37 UTC, volas commented on code/modules/events/ion_storm.dm
> +							"Вы не должны делать что-либо для кого-либо если они не скажут \"Пожалуйста\".",
```suggestion
							"Вы не должны делать что-либо для кого-либо, если они не скажут \"Пожалуйста\".",
```

2022-04-09 01:38 UTC, volas commented on code/modules/events/ion_storm.dm
> +							"заменяйте буквы 'И' и 'Е' во всех ваших сообщениях апострофом.",
```suggestion
							"Заменяйте буквы 'И' и 'Е' во всех ваших сообщениях апострофом.",
```

2022-04-09 02:06 UTC, volas approved these changes

2022-04-09 02:06 UTC, merged