респрайт айди карт
TauCetiStation/TauCetiClassic pull request #7074
Opened 2021-04-29 18:38 UTC by AndroBetel

## Описание изменений
![image](https://user-images.githubusercontent.com/44546836/116601283-fe02fe00-a932-11eb-918a-d72bd5df7fb7.png)
респрайтит айди-карты
цвета карты цивилианов и медиков отличались на полтона (заявление спрайтера), и поэтому теперь карта цивилианов больше похожа на обычную, и её получает подопытный и подтипы.
## Почему и что этот ПР улучшит
единый стиль вухуу красота еее
## Авторство
LiJard
## Чеинжлог
:cl:
- image: респрайт айди-карт.

2021-04-29 18:38 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2021-04-29 18:44 UTC, KIBORG04 commented
бля, та за шо

2021-04-29 18:45 UTC, AndroBetel commented
я просто исполняю приказы

2021-04-29 19:30 UTC, Motzord commented
Красиво

2021-04-29 19:31 UTC, Motzord commented
Рассмотрел карты повнимательнее. На каких принципах основывается градация по отделам и идентификация глава/не глава?

2021-04-29 19:40 UTC, UDaV73rus requested changes
нужны скрины из игры

1. золотая карта пережившая капитанский толчок
![image](https://user-images.githubusercontent.com/33157992/116603629-cea1c080-a935-11eb-890f-99b2821c6660.png)

2. На верхних светлых гранях прямо супер важно обводку сделать светлее (на отпечатках пальцев тоже)
3. На серых картах верхняя грань слишком белая, на цветных норм (хотя скорее сами карты слишком темные)
4. На ерт картах верхняя грань не покрашена

2021-04-29 20:23 UTC, KIBORG04 commented
![image](https://user-images.githubusercontent.com/26389417/116612641-76bc8700-a940-11eb-9b51-0c4f93a5df79.png)

Зачем вообще сделаны эти засечки на серой линии? Это вроде не имеет смысловой нагрузки, так как оно дублирует цвет квадратика из левого верхнего угла на традиционных карточках.
Да и вроде бы, этот зеленый оттенок тусклый и в игре будет плохо видно

2021-05-02 10:48 UTC, Zmey25 commented
Очередное месиво цветов

2021-05-07 08:44 UTC, LiLJard commented
> На каких принципах основывается градация по отделам и идентификация глава/не глава?

По отделам - цвета. То есть ученые фиолетовые, мед синий, охрана красные и т.д. У глав золотые элементы, у гражданских все остальные.

> Очередное месиво цветов

Bruh

> Зачем вообще сделаны эти засечки на серой линии? Это вроде не имеет смысловой нагрузки, так как оно дублирует цвет квадратика из левого верхнего угла на традиционных карточках.

Спрайты являются буквальной копией нынешних за исключением смены отображения с диагонального на горизонтальное, а также косметики (палитра, контрасты и все такое), поэтому все форменные элементы сохранены в изначальном виде. Так это уменьшит разрушительный эффект для психики особо впечатлительных товарищей, да и в целом всем остальным игрокам будет проще привыкнуть к замене.

> Да и вроде бы, этот зеленый оттенок тусклый и в игре будет плохо видно

Базированно, посмотрю что с этим можно сделать

>золотая карта пережившая капитанский толчок

Пиздатый конструктив, охуенные яйца

>На верхних светлых гранях прямо супер важно обводку сделать светлее
>На серых картах верхняя грань слишком белая

Я стараюсь отходить от разнородного аутлайна за исключением мест, где это жизненно необходимо по ряду причин (слишком светлые вещи, к примеру). На простых картах большой контраст между белой верхней гранью и серой фронтальной поверхностью привлекает достаточно внимания и демонстрирует, что предмет сделан из пластика или металла. По этой же причине темный аутлайн наверху будет заметен слабо и введение отличия на тон погоды не сделает. Про карточки с отпечатками согласен. Здесь на самом спрайте контраста как такового нет, поэтому черный аутлайн может смотреться слишком резко. Тут тоже в ближайшее время внесу корректировки. 

> На ерт картах верхняя грань не покрашена
Если ты про голубую полоску - то на белом ярком фоне ещё более светлый голубой заметен не будет, соответственно смысла в этом нет.

2021-05-07 15:58 UTC, AndroBetel commented
![image](https://user-images.githubusercontent.com/44546836/117477117-44291480-af66-11eb-823e-954225c982cf.png)

2021-05-07 15:59 UTC, Sakuya-Izayoi commented
гостевой пропуск зареспрайчен?

2021-05-07 15:59 UTC, AndroBetel commented
da

2021-05-14 14:20 UTC, LiLJard approved these changes

2021-05-14 14:23 UTC, KIBORG04 commented
Так, нел егетимный аппруве, надо удава или юлиана

2021-05-14 14:23 UTC, UDaV73rus commented
золотая карта moment

2021-06-09 17:12 UTC, closed without merging