fix fire extinguisher
TauCetiStation/TauCetiClassic pull request #7086
Opened 2021-05-01 08:54 UTC by BesumniiChebureck

## Описание изменений
Фикс
## Почему и что этот ПР улучшит
fix #6929
## Авторство
Ya
## Чеинжлог
:cl:
- bugfix: Маленький и золотой огнетушители снова имеют свой спрайт.

2021-05-01 08:54 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2021-05-01 13:42 UTC, KIBORG04 commented
А ты вообще тестил?

2021-05-01 13:43 UTC, KIBORG04 commented
https://github.com/TauCetiStation/TauCetiClassic/pull/6922

Этот пр сломал, а твое изменение ни на что не повлияет

2021-05-01 13:45 UTC, BesumniiChebureck commented
Оу.............

2021-05-01 14:00 UTC, KIBORG04 commented
да нафиг ты закрыл, там буквально тебе нужно будет еще пару строчек изменить

2021-05-01 14:01 UTC, KIBORG04 commented
![image](https://user-images.githubusercontent.com/26389417/116784798-d466e580-aa9e-11eb-8a05-d3e5d6ded430.png)

оставить твои нули и вернуть эти строчки. Все.

2021-05-01 21:07 UTC, KIBORG04 commented on code/modules/reagents/reagent_containers/extinguisher.dm
> +	icon_state = "[initial(icon_state)][!safety]"
я, кстати, был не прав о том, что это все. Теперь огнетушители изначально будут иметь спрайт с названием "fire_extinguisher00", а значит ты не тестишь на локалке.

2021-05-02 14:49 UTC, BesumniiChebureck commented
Затестил, работает.

2021-05-02 14:50 UTC, KIBORG04 commented
Молодец, ты откатил #6922 .

2021-05-02 14:50 UTC, KIBORG04 commented
А, ты еще и спрайты продублировал в том файле, тогда не откатил

2021-05-02 14:52 UTC, BesumniiChebureck commented
Киборг, нормально или нет?

2021-05-02 14:52 UTC, KIBORG04 commented
Ну можно было и без дублирования спройтов сделать

2021-05-06 17:34 UTC, KIBORG04 requested changes
Не туда нажал блин (

2021-05-15 14:59 UTC, KIBORG04 approved these changes

2021-05-15 21:21 UTC, merged