Отображение текста на экране СПУ
TauCetiStation/TauCetiClassic pull request #7106
Opened 2021-05-04 14:29 UTC by Sakuya-Izayoi

## Описание изменений
Если кратко, СПУ с монитором на плечах могут отображать на нём любой текст. Этот текст можно просмотреть в экзамайне.
Оригинальный ПР: #5211

Отличия: нельзя устанавливать цвет текста, можно писать на экране пеки и джойпейны. Выглядит это примерно так:
![image](https://user-images.githubusercontent.com/30875884/117019437-0f1a8900-acfe-11eb-93f9-0b9630c218bc.png)

Чтобы писать текст на мониторе нужно написать в сей с кодом языка `::`.

## Почему и что этот ПР улучшит
Ролевой экспириенс

## Авторство

## Чеинжлог
:cl: Getup1
- rscadd: СПУ с монитором вместо головы смогут отображать на нём текст.

2021-05-04 14:29 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2021-05-04 15:04 UTC, KIBORG04 commented on code/__DEFINES/language.dm
> +#define PSEUDOLANG  16      // Language uses it's unique method of displaying speech (like IPC monitor text display)
```suggestion
#define PSEUDOLANG  16      // Language uses it's unique method of displaying speech (like IPC monitor text display)

```

2021-05-04 15:05 UTC, KIBORG04 commented on code/modules/mob/language.dm
> +	return
```suggestion
	flags = RESTRICTED | PSEUDOLANG

/datum/language/pseudo/proc/pseudo_say(text, mob/user)
	return
```

2021-05-04 19:08 UTC, KIBORG04 commented on code/modules/mob/living/carbon/human/examine.dm
> +			msg += "Отображает на экране текст: \"<span class=\"emojify\">[BP.display_text]</span>\"\n"
Раз уж там может быть не только текст, то может изменить формулировку?

2021-05-04 19:12 UTC, Sakuya-Izayoi commented on code/modules/mob/living/carbon/human/examine.dm
> +			msg += "Отображает на экране текст: \"<span class=\"emojify\">[BP.display_text]</span>\"\n"
нет. всё равно на это. максимально.

2021-05-04 19:12 UTC, KIBORG04 commented on code/modules/mob/living/carbon/human/examine.dm
> +			msg += "Отображает на экране текст: \"<span class=\"emojify\">[BP.display_text]</span>\"\n"
токсик

2021-05-04 20:34 UTC, LudwigVonChesterfield commented on code/__DEFINES/language.dm
> +#define PSEUDOLANG  16      // Language uses it's unique method of displaying speech (like IPC monitor text display)
если он ведёт себя как язык жестов, то зачем ему отдельный флаг? может стоит обобщить "язык жестов" до "визуальный язык", и всё.

2021-05-04 20:35 UTC, LudwigVonChesterfield commented
а можно чтобы к отрубленной башке СПУ прикрутить батарейку и тоже картинки мемасные делать?

2021-05-04 21:31 UTC, Sakuya-Izayoi commented on code/__DEFINES/language.dm
> +#define PSEUDOLANG  16      // Language uses it's unique method of displaying speech (like IPC monitor text display)
Он ведёт себя не как язык жестов. Он устанавливает переменные у говорящего, это уникальное поведение.

2021-05-04 21:31 UTC, Sakuya-Izayoi commented
> а можно чтобы к отрубленной башке СПУ прикрутить батарейку и тоже картинки мемасные делать?

Нет

2021-05-05 05:19 UTC, Akellazp commented
Жаль

2021-05-06 17:35 UTC, KIBORG04 commented
Поидее, все должно быть норм, но кину в ТМ на всякий

2021-05-10 08:07 UTC, KIBORG04 commented
Как насчет добавить во вкладку IPC кнопку, которая будет вместо меня делать `::*text*` ?

2021-05-10 08:29 UTC, volas requested changes

2021-05-10 08:29 UTC, volas commented on code/__DEFINES/language.dm
> +#define PSEUDOLANG  16      // Language uses it's unique method of displaying speech (like IPC monitor text display)
Мне кажется, тут проблема в том, что это вообще не должен быть язык, и я не понимаю откуда взялась идея делать это языком.
Есть уже тот же "Set Pose", или плакаты, никто не делал из этого отдельный язык.

2021-05-10 08:33 UTC, KIBORG04 commented on code/__DEFINES/language.dm
> +#define PSEUDOLANG  16      // Language uses it's unique method of displaying speech (like IPC monitor text display)
Чтобы можно было нормально общаться в чате, используя вот этот свой экран. В прошлом ПРе людук не хотел еще один верб.

2021-05-10 08:40 UTC, volas commented on code/__DEFINES/language.dm
> +#define PSEUDOLANG  16      // Language uses it's unique method of displaying speech (like IPC monitor text display)
Увидел, вините гетапа за то что пересоздает ПРы. Но я всё равно не вижу причин с этой фичей лезть куда-то в языки, а верб на "::" можно было бы сделать и без этого.

2021-05-10 09:06 UTC, Sakuya-Izayoi commented
> Как насчет добавить во вкладку IPC кнопку, которая будет вместо меня делать `::*text*` ?

Делаешь кнопку, просят сделать язык, делаешь язык, просят сделать кнопку. Мне-то не тяжело, но вы уверены что это нужно?

2021-05-10 12:47 UTC, Sakuya-Izayoi commented on code/__DEFINES/language.dm
> +#define PSEUDOLANG  16      // Language uses it's unique method of displaying speech (like IPC monitor text display)
использовал механику языка потому что это было удобно в этой ситуации. во-первых, потому что делать в коде сея ещё одно исключение для одной механики как-то совсем неохота, а во-вторых, потому что это позволило бы удобно сделать фичу чтобы немые писали на экране через сей без кода языка опять же без всяких лишних исключений.

2021-05-11 11:07 UTC, LudwigVonChesterfield commented on code/modules/mob/language.dm
> +		H.custom_emote(SHOWMSG_VISUAL, "отображает на своём экране, \"<span class=\"emojify\">[text]</span>\"")
```suggestion
		H.custom_emote(SHOWMSG_VISUAL, "отображает на экране, \"<span class=\"emojify\">[text]</span>\"")
```

говорит своим ртом
мимикрирует своим хвостом

может быть стоит даже "отображает", не знаю.

2021-05-11 11:12 UTC, LudwigVonChesterfield commented on code/modules/mob/living/carbon/human/examine.dm
> +			msg += "Отображает на экране текст: \"<span class=\"emojify\">[BP.display_text]</span>\"\n"
```suggestion
			msg += "Отображает на экране: \"<span class=\"emojify\">[BP.display_text]</span>\"\n"
```

2021-05-13 22:07 UTC, KIBORG04 commented on code/__DEFINES/language.dm
> +#define PSEUDOLANG  16      // Language uses it's unique method of displaying speech (like IPC monitor text display)
Если у воласа нету вопросов, можно мержить, получается

2021-05-14 09:38 UTC, Sakuya-Izayoi commented
обнаружены баги, мержить пока нельзя

2021-05-19 18:58 UTC, KIBORG04 commented
когда фикс?М???

2021-05-21 16:52 UTC, Sakuya-Izayoi commented
известные баги исправлены

2021-05-23 19:28 UTC, KIBORG04 commented
Я обнаружил баг. Во сне кукла может "слышать" текст с экрана и он будет коверкаться
https://github.com/TauCetiStation/TauCetiClassic/blob/b69b08ce43b8e6ea52d9f4f356cc27a7042f7b22/code/modules/mob/hear_say.dm#L227

2021-05-23 20:08 UTC, LudwigVonChesterfield commented
Я тоже пожалую запишу сюда.

Если за немого СПУ говорить в чат эмодзи которые начинаются с кодов отделов, то от эмодзи отгрызается первая буква и в итоге происходит

[Security] boba says, "ooqa:"

2021-05-24 19:04 UTC, KIBORG04 commented
Все, языка нет, дожили

2021-05-24 19:04 UTC, KIBORG04 commented on code/modules/mob/living/carbon/species.dm
> +	additional_languages = list("Display Text")
Языка нет, все

2021-05-27 20:11 UTC, KIBORG04 commented
Кстати, людук, тут в итоге вообще отказались от юзания механа языков в пользу верба. Чи или не чи?

2021-05-27 20:45 UTC, merged