Перевод генокрадов
TauCetiStation/TauCetiClassic pull request #7109
Opened 2021-05-04 20:31 UTC by notkripton

## Описание изменений
Переводит способности генокрадов и их описания.
## Почему и что этот ПР улучшит
Понятные славянину описания
## Авторство
Я и гугл транслейт
## Чеинжлог
:cl: 
- ru: Перевод способностей генокрадов.

2021-05-04 20:31 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2021-05-04 20:55 UTC, KIBORG04 commented on code/game/gamemodes/changeling/powers/Chameleon_skin.dm
> +	name = "Кожная Маскировка"
Звучит ужасно

2021-05-04 21:05 UTC, notkripton commented on code/game/gamemodes/changeling/powers/Chameleon_skin.dm
> +	name = "Кожная Маскировка"
Хз как лучше написать. "Кожа Хамелеона" и "Маскировка Кожи" ещё хуже.

2021-05-04 21:16 UTC, AndroBetel commented on code/game/gamemodes/changeling/powers/hand_hammer.dm
> +	name = "Биомолот"
почему везде через дефис а тут вместе

2021-05-04 21:29 UTC, Sakuya-Izayoi commented on code/game/gamemodes/changeling/powers/Chameleon_skin.dm
> +	name = "Кожная Маскировка"
Просто маскировка

2021-05-04 21:29 UTC, Sakuya-Izayoi commented on code/game/gamemodes/changeling/powers/hand_hammer.dm
> +	name = "Биомолот"
Это вообще органический молот

2021-05-05 05:04 UTC, notkripton commented on code/game/gamemodes/changeling/powers/hand_hammer.dm
> +	name = "Биомолот"
Органический не круто звучит. Про тире согласен

2021-05-05 05:06 UTC, notkripton commented on code/game/gamemodes/changeling/powers/Chameleon_skin.dm
> +	name = "Кожная Маскировка"
Оставил просто маскировку

2021-05-05 11:36 UTC, notkripton commented
Чё?

2021-05-07 17:18 UTC, Gort133 commented
helptext = "Мы жалим цель мощными галлюциногенными химикатами. Цель не замечает укуса. Эффект наступает через 30-60 секунд."

2021-06-08 09:01 UTC, notkripton commented
> Данный ПР автоматически отмечен как застоявшийся по причине длительного отсутствия обновлений. Он будет закрыт через 7 дней, если никакой активности не будет проявлено. Если вы считаете, что ПР еще актуален, или что я (злобный робот) пристаю к вам зря - просто напишите любой комментарий. Спасибо за ваш вклад.

Нпмооииорптор

2021-07-07 01:49 UTC, Haggerd requested changes
Ну короче, ебитес.

2021-07-07 01:49 UTC, Haggerd commented on code/game/gamemodes/changeling/powers/glands.dm
> +	helptext = "Увеличивает максимальный объем химикатов на 25 юнитов."
Юниты-хуюиты. Вообще, можно полностью убрать эту еблю с юниты/едницы и оставить просто `Увеличивает максимальный объем химикатов на 25`. Но если сильно хочется указать, то лучше использовать "единицы"
```suggestion
	helptext = "Увеличивает максимальный объем химикатов на 25 единиц."
```

2021-07-07 01:49 UTC, Haggerd commented on code/game/gamemodes/changeling/powers/hand_hammer.dm
> +	helptext = "Разбивает стены, окна, шлюзы, людей. Нельзя применять в форме обезьяны."
Опять же, потеряна механосоставляющая и в данном случае перечисление лучше закончить с союзом "и"
```suggestion
	helptext = "Разбивает стены, окна, шлюзы и людей. Требует много химикатов на каждое использование. Нельзя применять в форме обезьяны."
```

2021-07-07 01:49 UTC, Haggerd commented on code/game/gamemodes/changeling/powers/mimic_voice.dm
> +	helptext = "Позволяет вам говорить голосом того, кого вы захотите, достаточно просто ввести имя. Требует постоянного расхода химикатов, пока включено."
Более лаконичная конструкция, как по мне.
```suggestion
	helptext = "Позволяет нам говорить голосом того, чьё имя будет введено. Пока включено, требует постоянного расхода химикатов."
```

2021-07-07 01:49 UTC, Haggerd commented on code/game/gamemodes/changeling/powers/hand_hammer.dm
> +	desc = "Мы превращаем нашу руку в смертоносный молот."
```suggestion
	desc = "Мы превращаем одну из наших рук в смертоносный молот."
```

2021-07-07 01:49 UTC, Haggerd commented on code/game/gamemodes/changeling/powers/mutations.dm
> +	desc = "Мы превращаем одну из рук в смертоносный клинок."
Сохраняем общий стиль таких фраз
```suggestion
	desc = "Мы превращаем одну из наших рук в смертоносный клинок."
```

2021-07-07 01:49 UTC, Haggerd commented on code/game/gamemodes/changeling/powers/mutations.dm
> +	helptext = "Органическая ткань не может противостоять повреждениям вечно, щит сломается после слишком сильного удара. Чем больше геномов вы поглотили, тем он сильнее. Нельзя использовать в форме обе
Убираем возможное ложное толкование
```suggestion
	helptext = "Органическая ткань не может противостоять повреждениям вечно. Щит сломается после того, как примет множество ударов. Чем больше геномов мы поглотили, тем он прочнее. Нельзя использовать в форме обезьяны."
```

2021-07-07 01:49 UTC, Haggerd commented on code/game/gamemodes/changeling/powers/mutations.dm
> +	helptext = "Вы должны постоянно ремонтировать такую форму, чтобы она оставалась герметичной, сокращая производство химикатов, пока вы защищены. Сброс костюма повреждает наши геномы. Не может использ
Более простая для понимания конструкция. Часть предложения с "пока вы защищены" я вообще выкинул, так как смысла ноль, а нагрузки даёт немало.
```suggestion
	helptext = "Для сохранения герметичности, мы должны постоянно ремонтировать такую форму, сокращая производство химикатов. Сброс костюма повреждает наши геномы. Не может использоваться в форме обезьяны."
```

2021-07-07 01:49 UTC, Haggerd commented on code/game/gamemodes/changeling/powers/mutations.dm
> +	desc = "Мы превращаем нашу кожу в прочный хитин, чтобы защититься от повреждений."
Здесь лучше использовать причастный оборот
```suggestion
	desc = "Мы превращаем нашу кожу в прочный хитин, защищающий от повреждений."
```

2021-07-07 01:49 UTC, Haggerd commented on code/game/gamemodes/changeling/powers/mutations.dm
> +	helptext = "Уход за броней требует небольшого расхода химикатов. Броня устойчива против физических повреждений, но не защищает от лазеров. Сброс брони повреждает ваши геномы. Не может использоваться
Слово "Уход" здесь может исказить понимание фразы
```suggestion
	helptext = "Поддержание брони требует небольшого расхода химикатов. Броня устойчива против физических повреждений, но не защищает от лазеров. Сброс брони повреждает ваши геномы. Не может использоваться в форме обезьяны."
```

2021-07-07 01:49 UTC, Haggerd commented on code/game/gamemodes/changeling/powers/spiders.dm
> +	desc = "Наши железы вырабатывают паучие личинки, со временем превращающиеся в огромных монстров."
Не критично, но может лучше использовать "смертоносных", как и в оригинале?
```suggestion
	desc = "Наши железы вырабатывают паучьи личинки, со временем превращающиеся в смертоносных монстров."
```

2021-07-07 01:49 UTC, Haggerd commented on code/game/gamemodes/changeling/powers/spiders.dm
> +	helptext = "Пауки - существа забывчивые и могут атаковать своих создателей, когда вырастут. Требуется поглотить минимум 4 ДНК."
Вариант получше
```suggestion
	helptext = "Пауки - существа безрассудные, поэтому могут атаковать своих создателей, когда вырастут. Требуется поглотить минимум 4 ДНК."
```

2021-07-07 01:49 UTC, Haggerd commented on code/game/gamemodes/changeling/powers/stings.dm
> +	desc = "Мы молча жалим человека коктейлем из химикатов, замораживающих его тело."
Нет, блять, с криками и орами
```suggestion
	desc = "Мы незаметно жалим человека коктейлем из химикатов, замораживающих его тело."
```

2021-07-07 01:49 UTC, Haggerd commented on code/game/gamemodes/changeling/powers/stings.dm
> +	helptext = "Не предупреждает жертву, хотя они=а, скорее всего, поймет, когда внезапно замерзнет."
Смысл в оригинале совершенно другой, не указывающий на возможную догадку об уколе
```suggestion
	helptext = "Не заметен для жертвы, хотя она, скорее всего, поймет, что внезапно начала замерзать."
```

2021-07-07 01:49 UTC, Haggerd commented on code/game/gamemodes/changeling/powers/stings.dm
> +	helptext = "Жалит цель мощными галлюциногенными химикатами. Цель не замечает укуса. Эффект наступает через 30-60 секунд."
Именно на этом моменте я заебался комментировать
```suggestion
	helptext = "Мы получаем возможность вкалывать жертвам мощные галлюциногены. Цель не замечает укола. Эффект наступает через 30-60 секунд."
```

2021-07-07 01:49 UTC, Haggerd commented on code/game/gamemodes/changeling/powers/stings.dm
> +	desc = "Мы молча жалим человека, вводя ретровирус, заставляющий жертву трансформироваться."
Генокрад - жалит молча
Жертва - Админ, тут Нон-РП!
```suggestion
	desc = "Мы незаметно жалим человека, вводя ретровирус, заставляющий жертву трансформироваться."
```

2021-07-07 01:49 UTC, Haggerd commented on code/game/gamemodes/changeling/powers/stings.dm
> +	helptext = "Не предупреждает существ вокруг. Жертва трансформируется так же, как генокрад."
Генокрад - молча жалит
Жало - я не буду предупреждать
```suggestion
	helptext = "Укол не заметен для окружающих. Жертва трансформируется так же, как генокрад."
```

2021-07-07 01:49 UTC, Haggerd commented on code/game/gamemodes/changeling/powers/stings.dm
> +	desc = "Мы молча жалим человека, полностью оглушая его и заставляя замолчать на короткое время."
Да блять.
Лучше не использовать "оглушая". Может привести к ложной трактовке, учитывая сколько в абилках геноёбов других оглушений
```suggestion
	desc = "Мы незаметно жалим человека, делая его полностью глухим и немым на короткое время."
```

2021-07-07 01:49 UTC, Haggerd commented on code/game/gamemodes/changeling/powers/stings.dm
> +	helptext = "Временно слепит жертву."
Слепит. Ну такое.
```suggestion
	helptext = "Временно ослепляет жертву."
```

2021-07-07 01:49 UTC, Haggerd commented on code/game/gamemodes/changeling/powers/stings.dm
> +	desc = "Мы тихо жалим человека, заставляя его моментально набрать вес."
Сначала молчали, теперь уже говорим погромче, но всё же тихо. Окей.
```suggestion
	desc = "Мы незаметно жалим человека, заставляя его моментально набрать вес."
```

2021-07-07 01:49 UTC, Haggerd commented on code/game/gamemodes/changeling/powers/stings_range.dm
> +	name = "Повышенный Диапазон"
Как мне кажется, "диапазон" тут неуместен. Лучше
```suggestion
	name = "Повышенный Радиус"
```
Или
```suggestion
	name = "Повышенная Дистанция"
```
Но вот этот момент очень субъективен для меня

2021-07-07 01:49 UTC, Haggerd commented on code/game/gamemodes/changeling/powers/strained_muscles.dm
> +	helptext = "Позволяет бежать в разы быстрее, если долго бежать, вы выдохнитесь."
Тут понадобилась полная переработка.
```suggestion
	helptext = "Использование этой способности, быстро оставит нас без сил. Тяжёлые предметы, такие как скафандры, всё ещё замедляют движение. Не может быть использовано в форме обезьяны."
```

2021-07-09 18:09 UTC, pss88 commented on code/game/gamemodes/changeling/powers/Chameleon_skin.dm
> +	helptext = "Позволяет получить полную невидимость стоя неподвижно. Может включаться и выключаться."
"Делает нас невидимыми, если стоять неподвижно."
А то это "Стоя неподвижно" все еще ни к чему не относится.

2021-07-09 18:12 UTC, pss88 commented on code/game/gamemodes/changeling/powers/Whip.dm
> +	helptext = "Может хватать, сбивать с ног, наносить урон, в зависимости от интента, требует химикаты за каждый удар. Нельзя использовать в форме обезьяны."
А почему intent = "интент", а не "намерение"? Всяких "ХоПов" и "РД" же переименовали.

2021-07-09 18:44 UTC, Haggerd commented on code/game/gamemodes/changeling/powers/Chameleon_skin.dm
> +	helptext = "Позволяет получить полную невидимость стоя неподвижно. Может включаться и выключаться."
Другой вариант надумал:
```suggestion
	helptext = "Сохраняя неподвижность, мы становимся полностью невидимыми. Может включаться и выключаться."
```

2021-07-09 23:21 UTC, KIBORG04 commented on code/game/gamemodes/changeling/headcrab.dm
> +	helptext = "Вы получите контроль над маленьким хрупким существом. Вы сможете отложить свои яйца в труп, чтобы вырастить в нем свою новую форму."
Мы получим. Мы сможем. Меньше мыкать предлагаю

2021-07-09 23:22 UTC, KIBORG04 commented on code/game/gamemodes/changeling/powers/stings.dm
> +	desc = "Мы молча жалим человека, полностью оглушая его и заставляя замолчать на короткое время."
Ошеломление =/= оглушение

2021-07-09 23:27 UTC, Haggerd commented on code/game/gamemodes/changeling/powers/stings.dm
> +	desc = "Мы молча жалим человека, полностью оглушая его и заставляя замолчать на короткое время."
Это скилл делает именно глухим

2021-07-09 23:28 UTC, Haggerd commented on code/game/gamemodes/changeling/headcrab.dm
> +	helptext = "Вы получите контроль над маленьким хрупким существом. Вы сможете отложить свои яйца в труп, чтобы вырастить в нем свою новую форму."
Я чуть позже другой вариант составлю. Этот мне и самому не особо нравится

2021-07-18 09:18 UTC, notkripton commented on code/game/gamemodes/changeling/powers/Whip.dm
> +	name = "organic whip"
Киборг писал, что названия предметов в игре должны быть желательно с маленькой буквы

2021-07-18 09:20 UTC, notkripton commented on code/game/gamemodes/changeling/headcrab.dm
> +	helptext = "Вы получите контроль над маленьким хрупким существом. Вы сможете отложить свои яйца в труп, чтобы вырастить в нем свою новую форму."
Хаггерд ты немного запутался. Desc это иц описание, где надо мыкать, а helptext это ооц описание, в котором наоборот мыкать не надо.

2021-07-18 09:25 UTC, notkripton commented on code/game/gamemodes/changeling/powers/digitalcamo.dm
> +	desc = "Развивая способность искажать нашу форму и размер, мы побеждаем обычные алгоритмы ИИ, используемые для обнаружения форм жизни на камерах."
Камеры просто видят, а определяет жизнь на них уже ИИ

2021-07-18 09:28 UTC, notkripton commented on code/game/gamemodes/changeling/powers/epinephrine.dm
> +	helptext = "Мнгновенно впрыскивает накопленный адреналин, позволяя вам сбросить кратковременное оглушение. Частое использование будет отравлять организм."
Замени "наш" на "ваш" и я коммичу (закоммичиваю? коммитлю?)

2021-07-18 09:34 UTC, notkripton commented on code/game/gamemodes/changeling/powers/stings.dm
> +	desc = "Мы молча жалим человека, полностью оглушая его и заставляя замолчать на короткое время."
Почему я вообще использовал "молча" вместо "незаметно"? Сам с себя кринж ловлю...

2021-07-18 09:35 UTC, notkripton commented on code/game/gamemodes/changeling/powers/biodegrade.dm
> +	helptext = "Может уничтожать наручники, закрытые шкафчики и смирительные рубашки. Люди неподалеку определенно это заметят."
Ну такоооое

2021-07-18 09:38 UTC, notkripton commented on code/game/gamemodes/changeling/powers/hand_hammer.dm
> +	helptext = "Разбивает стены, окна, шлюзы, людей. Нельзя применять в форме обезьяны."
Хрень, шутка теряется, про химикаты вообще лишнее.

2021-07-18 09:40 UTC, notkripton commented on code/game/gamemodes/changeling/powers/mimic_voice.dm
> +	helptext = "Позволяет вам говорить голосом того, кого вы захотите, достаточно просто ввести имя. Требует постоянного расхода химикатов, пока включено."
"Чьё имя будет введено" кем введено? Куда введено? Оригинал лучше будет.

2021-07-18 09:49 UTC, notkripton commented on code/game/gamemodes/changeling/powers/mutations.dm
> +	helptext = "Органическая ткань не может противостоять повреждениям вечно, щит сломается после слишком сильного удара. Чем больше геномов вы поглотили, тем он сильнее. Нельзя использовать в форме обе
Опять же, убирай мыканье и коммичу

2021-07-18 09:49 UTC, notkripton commented on code/game/gamemodes/changeling/powers/mutations.dm
> +	helptext = "Вы должны постоянно ремонтировать такую форму, чтобы она оставалась герметичной, сокращая производство химикатов, пока вы защищены. Сброс костюма повреждает наши геномы. Не может использ
Тоже самое, что и выше (убирай мыканье)

2021-07-18 09:57 UTC, notkripton commented on code/game/gamemodes/changeling/powers/stings.dm
> +	helptext = "Жалит цель мощными галлюциногенными химикатами. Цель не замечает укуса. Эффект наступает через 30-60 секунд."
Хелптекст НЕ мыкает еклмн

2021-07-18 10:05 UTC, notkripton commented on code/game/gamemodes/changeling/powers/strained_muscles.dm
> +	helptext = "Позволяет бежать в разы быстрее, если долго бежать, вы выдохнитесь."
Слишком загромождённо получается, но пускай будет. А ещё хелптекст не мыкает.

2021-07-18 10:16 UTC, notkripton commented
@T6751 автор нашел эту темку и подкорректировал исходный вариант, эвэитинг аутхор можно убирать.

2021-07-18 14:12 UTC, Haggerd commented
А с чего ты решил, что хелптекст не мыкает, если в оригинале мыкает?

2021-07-18 14:42 UTC, notkripton commented
Странный человек, конечно, это писал, где-то мыкает а где-то нет.
![IMG_20210718_183833](https://user-images.githubusercontent.com/75007994/126071384-b0492c54-fbb8-4d96-8f34-9c8c68399287.jpg)

И перевод вместе с ошибками создаст больше путаницы. Вообще странно, что хелптекст поясняющий сущность механа ломает 4 стену говоря о пользователе в первом лице.

2021-08-10 18:15 UTC, notkripton commented
Мейнтейнеры переоткройте

2021-09-01 15:34 UTC, closed without merging