Resprite инжекторов
TauCetiStation/TauCetiClassic pull request #7115
Opened 2021-05-05 18:33 UTC by CeUvi

## Описание изменений
очередной resprite инжекторов, хайп-спрея, комбат stimulator инжектора и киборгского hype-инжектора
![tauceti injectors](https://user-images.githubusercontent.com/56074620/117191102-dd322100-ade8-11eb-89e5-a2dcf05b7439.gif)
теперь у каждого injector имеется свой использованный спрайт
## Почему и что этот ПР улучшит
красоту билда
## Авторство
я, цеуви, сеуви, кзюба, называйте как хотите
ну ещё немножко эрис конечно же
## Чеинжлог
:cl: CeUvi
 - image: обновление sprites для injectors
 - tweak: теперь у каждого injector есть empty состояние

2021-05-05 18:33 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2021-05-05 18:40 UTC, notkripton commented
Почему инопровалиновый инжектор красный то?

2021-05-05 18:45 UTC, CeUvi commented
> Почему инопровалиновый инжектор красный то?

а почему в оригинале он зеленый

2021-05-05 19:06 UTC, UDaV73rus approved these changes

2021-05-05 19:12 UTC, Sakuya-Izayoi commented
да недавно респрайтили же. зачем опять?

2021-05-05 19:15 UTC, CeUvi commented
> да недавно респрайтили же. зачем опять?

всмысле зачем
мне надо было зареспрайтить хайп-спрей и комбат стимулейтор инжектор, но стайл лижарда сложный и непонятный, мне пришлось зареспрайтить и инжекторы

2021-05-05 19:42 UTC, UsadoSmokk approved these changes
Я как шаттлодел, апрувую эту фигню. Киборг мерж быстро.

2021-05-06 17:38 UTC, KIBORG04 commented
![image](https://user-images.githubusercontent.com/26389417/117341504-dff54a80-aeaa-11eb-961f-aeb5b214dab6.png)

Ты зачем удаляешь спрайт у существующего предмета в билде? https://github.com/TauCetiStation/TauCetiClassic/blob/cfc68f1a5f1696061fddb9a5b2d70d4901c4098c/code/game/objects/items/weapons/medical.dm#L6

Хотел мерж, а ты стелсоубиваешь билд

2021-05-06 17:39 UTC, CeUvi commented
> ![image](https://user-images.githubusercontent.com/26389417/117341504-dff54a80-aeaa-11eb-961f-aeb5b214dab6.png)
> 
> Ты зачем удаляешь спрайт у существующего предмета в билде?
> 
> https://github.com/TauCetiStation/TauCetiClassic/blob/cfc68f1a5f1696061fddb9a5b2d70d4901c4098c/code/game/objects/items/weapons/medical.dm#L6
> 
> Хотел мерж, а ты стелсоубиваешь билд

я перенес его в суринж.дми, к остальным гипоспреям
![Uploading image.png…]()

2021-05-06 17:39 UTC, KIBORG04 commented
Да, я дибил

2021-05-07 07:56 UTC, LiLJard requested changes
Чето я не понял зачем только что сделанные инжектора вообще менять причем не в лучшую сторону:
1. Уменьшился размер, что не лучшим образом сыграет на кликабельности.
2. Так как аутлайн теперь не сплошной и более светлый инжектора слабее выделяются на фоне пола медбея, а также совсем не выделяются на фоне пола остальных отсеков, что не есть хорошо, так как направленность у нас на большую заметность айтемов.
3. Очень много лишних деталей, что добавляет предметам шумности. 
4. Ухудшилась также и узнаваемость, ибо палочка с иголкой воспринимается как инжектор больше, чем квадратный девайс напоминающий то ли кастомную зиппу, то ли отломанную рукоятку от пирометра. (К слову, то что иголка видна после использования тоже крутости не добавляет)
5. Инхендов не хватает.

Теперь что касается всего остального.
 
6. Разницу между заполненным комбат инжектором и опустошенным стоит сделать очевиднее, так как различие на один тон на желтом индикаторе заметно слабо. 
7. Было бы очень хорошо сделать комбат инжектор более "не НТшным", так как в основной массе он используется синдикатом. То есть темнее, возможно даже более угловатым и агрессивным в своем дизайне.
8. Так как медбей у нас синий, все красные свистоперделки было бы неплохо переделать в синий (к комбату и специфическим инжекторам это не относится).
9. Гипоспрей слишком мелкий и слабовыделяющийся. Напомню, что это предмет риска и соответственно визуально он должен быть ещё более заметным и буквально кричащим "я дорогая и важная вещь" даже относительно всех остальных вещей.

В целом, надо переработать гипоспрей человеческий, соответственно ему внести корректировки в гипоспрей борговский, подредактить комбат инжектор, добавить для всего этого инхенды. Про простые инжектора я уже высказался выше и не вижу смысла менять то, что есть на данный момент.

2021-05-07 08:41 UTC, CeUvi commented
> Уменьшился размер, что не лучшим образом сыграет на кликабельности.

нормально они кликаются, у нас есть предметы на которые кликнуть и то сложнее
> Так как аутлайн теперь не сплошной и более светлый инжектора слабее выделяются на фоне пола медбея, а также совсем не выделяются на фоне пола остальных отсеков, что не есть хорошо, так как направленность у нас на большую заметность айтемов.

Выделение предметов + эмбиент оклюжн для тебя шутка что-ли
> Очень много лишних деталей, что добавляет предметам шумности.

нет
> Ухудшилась также и узнаваемость, ибо палочка с иголкой воспринимается как инжектор больше, чем квадратный девайс напоминающий то ли кастомную зиппу, то ли отломанную рукоятку от пирометра. (К слову, то что иголка видна после использования тоже крутости не добавляет)

ты игроков спрашивал или придумал только что
> Инхендов не хватает.

инхенды будут уже совсем скоро
> Разницу между заполненным комбат инжектором и опустошенным стоит сделать очевиднее, так как различие на один тон на желтом индикаторе заметно слабо.

а по-моему всё очень даже заметно
> Было бы очень хорошо сделать комбат инжектор более "не НТшным", так как в основной массе он используется синдикатом. То есть темнее, возможно даже более угловатым и агрессивным в своем дизайне.

почему
> Так как медбей у нас синий, все красные свистоперделки было бы неплохо переделать в синий (к комбату и специфическим инжекторам это не относится).

нет
> Гипоспрей слишком мелкий и слабовыделяющийся. Напомню, что это предмет риска и соответственно визуально он должен быть ещё более заметным и буквально кричащим "я дорогая и важная вещь" даже относительно всех остальных вещей.

понял, уже делаю каждый хайриск предмет ЗОЛОТЫМ чтобы триторы уж точно поняли что это то что им надо украсть, это же точно не ПРОСТО УЛУЧШЕННЫЙ АВТОИНЖЕКТОР или какой-нибудь там КОСТЮМ

2021-05-07 08:53 UTC, LiLJard commented
> нормально они кликаются, у нас есть предметы на которые кликнуть и то сложнее

Не надо сравнивать с плохим. Плохое надо исправлять.

> Выделение предметов + эмбиент оклюжн для тебя шутка что-ли

Выделение предметов работает только при наведении, а одного эмбиента недостаточно 

> почему

Тут я уже написал почему, смотри на строчку выше в своем реплае

> а по-моему всё очень даже заметно

> нет

> понял, уже делаю каждый хайриск предмет ЗОЛОТЫМ чтобы триторы уж точно поняли что это то что им надо украсть, это ведь точно не ПРОСТО УЛУЧШЕННЫЙ АВТОИНЖЕКТОР или какой-нибудь там КОСТЮМ

А... Ну ладно? Нет - так нет. Просто дело в том, что спрайтовую политику определяем мы, соответственно условия для добавления в билд тоже. Не нравится - можешь попробовать вкинуть на эрис (если не уже), там наверное примут с распростертыми объятиями.

2021-05-07 13:37 UTC, Gort133 commented
Мины...темно серые спрайты... 
Давайте сразу спрайты с Маринов перенесём..

2021-05-12 10:41 UTC, FBitSafe commented
Этот респрайт мне понравился куда больше, чем прошлый. Думаю, что дизайн гипоспрея нужно сменить, а комбат инжектору сделать чёрно-красную палитру.

2021-06-09 17:15 UTC, closed without merging