Welcometotheminefields
TauCetiStation/TauCetiClassic pull request #7116
Opened 2021-05-05 19:36 UTC by AndroBetel

## Описание изменений
https://github.com/TauCetiStation/TauCetiClassic/pull/6012/files переоткрытие
добавляет 5 видов мин
![image](https://user-images.githubusercontent.com/44546836/117198601-e378cb00-adf1-11eb-95c5-5adecb861888.png)
обычная - просто достаточно сильно бахает, есть в аплинке
стан - аля тазер, накидывает кучу боли, есть у вардена в шкафчике раундстартом и заказывается в карго
шок - аля наэлектризованная дверь, пробивает человека разрядом электричества, заказывается в карго
зажигательная - nuff said, есть в аплинке
эми - делает неплохой эми-импульс, производится в РнД.

разминируются мультитулом или выстрелом 

## Почему и что этот ПР улучшит
больше контента это круто
## Авторство
я, спрайт сеуви
## Чеинжлог
:cl:
- rscadd[link]: добавляет на станцию мины.

2021-05-05 19:36 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2021-05-05 19:38 UTC, KIBORG04 commented
ясно переоткрытие

2021-05-05 19:41 UTC, KIBORG04 commented on code/game/objects/items/mines.dm
> +	if(locate(/obj/item/mine) in get_turf(src))
а че бы и нет?

2021-05-05 19:41 UTC, AndroBetel commented on code/game/objects/items/mines.dm
> +	if(locate(/obj/item/mine) in get_turf(src))
в смысле

2021-05-05 19:42 UTC, KIBORG04 commented on code/game/objects/items/mines.dm
> +	if(locate(/obj/item/mine) in get_turf(src))
че нельзя много мин в одну точку положить

2021-05-05 19:43 UTC, Sakuya-Izayoi commented on code/game/objects/items/mines.dm
> +	if(locate(/obj/item/mine) in get_turf(src))
баланс полагаю

2021-05-05 19:43 UTC, AndroBetel commented on code/game/objects/items/mines.dm
> +	if(locate(/obj/item/mine) in get_turf(src))
не балансно, мины будут ваншотать челов

2021-05-05 19:43 UTC, KIBORG04 commented on code/game/objects/items/mines.dm
> +	if(locate(/obj/item/mine) in get_turf(src))
И у тебя ниже везде все связано с `loc` у `user`, а здесь проверка именно на турф. Я уже вижу абуз, как вопреки этой штуки поставить 2 мины

2021-05-05 19:44 UTC, AndroBetel commented on code/game/objects/items/mines.dm
> +	if(locate(/obj/item/mine) in get_turf(src))
нужно проверку на loc сделать или на турф везде?

2021-05-05 19:44 UTC, KIBORG04 commented on code/game/objects/items/mines.dm
> +	if(locate(/obj/item/mine) in get_turf(src))
Блин, или незнаю... Попробуй закрыть шкафчик, поставить мину, потом опять попробуй в закрытом

2021-05-05 19:45 UTC, KIBORG04 commented on code/game/objects/items/mines.dm
> +	if(locate(/obj/item/mine) in get_turf(src))
> нужно проверку на loc сделать или на турф везде?

Если моя идея с абузом получится, то везде loc, иначе оставь так

2021-05-05 19:46 UTC, KIBORG04 commented on code/game/objects/items/mines.dm
> +	if(locate(/obj/item/mine) in get_turf(src))
хотя если везде loc, то абуз останется... Я надеюсь что не получится

2021-05-05 19:47 UTC, KIBORG04 commented on code/game/objects/items/mines.dm
> +	if(triggered) return
```suggestion
	if(triggered)
		return
```

2021-05-05 19:47 UTC, KIBORG04 commented on code/game/objects/items/mines.dm
> +			return
```suggestion
```

2021-05-05 19:48 UTC, AndroBetel commented on code/game/objects/items/mines.dm
> +	if(locate(/obj/item/mine) in get_turf(src))
в шкафчике нельзя мины ставить

2021-05-05 19:48 UTC, KIBORG04 commented on code/game/objects/items/mines.dm
> +	if(istype(M, /mob/living/carbon) || istype(M, /mob/living/silicon))
Чисто гипотетически, божок может сдетанировать мину. Поэтому наверное лучше будет проверять, что у моба small = FALSE

2021-05-05 19:49 UTC, KIBORG04 commented on code/game/objects/items/mines.dm
> +	if(locate(/obj/item/mine) in get_turf(src))
В закрытом шкафчике. Ну вообщем надеюсь абузов не будет

2021-05-05 19:50 UTC, KIBORG04 commented on code/game/objects/items/mines.dm
> +	return
```suggestion
```

2021-05-05 19:50 UTC, AndroBetel commented on code/game/objects/items/mines.dm
> +	if(istype(M, /mob/living/carbon) || istype(M, /mob/living/silicon))
бог не триггерит, а мыши должны

2021-05-05 19:51 UTC, AndroBetel commented on code/game/objects/items/mines.dm
> +	if(istype(M, /mob/living/carbon) || istype(M, /mob/living/silicon))
а мыши тоже не триггерят

2021-05-05 19:52 UTC, KIBORG04 commented on code/game/objects/items/mines.dm
> +	if(istype(M, /mob/living/carbon) || istype(M, /mob/living/silicon))
```suggestion
	if(iscarbon(M) || issilicon(M))
```

2021-05-05 19:55 UTC, KIBORG04 commented on code/game/objects/items/mines.dm
> +/obj/item/mine/Bumped(mob/M)
Наверное, некорректно все обрабатывать именно в этом проке. Лучше вынеси весь этот код в отдельный прок аля `try_trigger(atom/movable/AM)` и уже вызывай его из подобных мест

2021-05-05 19:56 UTC, AndroBetel commented on code/game/objects/items/mines.dm
> +/obj/item/mine/Bumped(mob/M)
и в бампед и в кроссед try_trigger?

2021-05-05 19:58 UTC, KIBORG04 commented on code/game/objects/items/mines.dm
> +/obj/item/mine/Bumped(mob/M)
Да, но еще и в bullet_act, ибо там не должно делитать саму мину

2021-05-05 19:59 UTC, KIBORG04 commented on code/game/objects/items/mines.dm
> +	spawn(0)
А они разве тут нужны?

2021-05-05 19:59 UTC, KIBORG04 commented on code/game/objects/items/mines.dm
> +	spawn(0)
А они разве тут нужны?

2021-05-05 19:59 UTC, KIBORG04 commented on code/game/objects/items/mines.dm
> +	return
```suggestion
```

2021-05-05 20:00 UTC, AndroBetel commented on code/game/objects/items/mines.dm
> +	spawn(0)
ну конечно нужны иначе как ещё показать что это стан

2021-05-05 20:00 UTC, KIBORG04 commented on code/game/objects/items/mines.dm
> +		M.IgniteMob()
какая-то странная мина, которая поджигает только определенного человека

2021-05-05 20:01 UTC, AndroBetel commented on code/game/objects/items/mines.dm
> +		M.IgniteMob()
того кто на неё наступил, всё правильно

2021-05-05 20:01 UTC, KIBORG04 commented on code/game/objects/items/mines.dm
> +	spawn(0)
Ты не знаешь как работает спавн(0)

2021-05-05 20:01 UTC, KIBORG04 commented on code/game/objects/items/mines.dm
> +		M.IgniteMob()
она скорее должна поджигать всех в какой-то области, хз

2021-05-05 20:02 UTC, AndroBetel commented on code/game/objects/items/mines.dm
> +		M.IgniteMob()
слишком жёстко для мины за 3 рубля

2021-05-05 20:02 UTC, AndroBetel commented on code/game/objects/items/mines.dm
> +	spawn(0)
нет, мне их удалить?

2021-05-05 20:03 UTC, KIBORG04 commented on code/game/objects/items/mines.dm
> +	if(triggered)
Я так посмотрел, в любых из случаях мина при `trigger_act()` удаляется, в итоге эта переменная не нужна

2021-05-05 20:03 UTC, AndroBetel commented on code/game/objects/items/mines.dm
> +	if(triggered)
а если будет мина с несколькими использованиями??

2021-05-05 20:04 UTC, KIBORG04 commented on code/game/objects/items/mines.dm
> +	if(!do_after(user, 40, target = src))
вместо этого ду_афтера попробуй заюзать `use_tool()`

2021-05-05 20:04 UTC, KIBORG04 commented on code/game/objects/items/mines.dm
> +	if(triggered)
но её же нету

2021-05-05 20:04 UTC, KIBORG04 commented on code/game/objects/items/mines.dm
> +	if(triggered)
и не факт что в этом году появится

2021-05-05 20:10 UTC, KIBORG04 commented on code/game/objects/items/mines.dm
> +	spawn(0)
Ну, ты же наверное откуда-то это взял, там это наверное было нужно. Хз. Попробуй убрать спавн и затестить, если че-то сломается, то замени на QDEL_IN(src, 0)

2021-05-05 20:28 UTC, UDaV73rus requested changes
Сообщили что мины нужно тиранить...
Мины сделаны очень средне. Свет, цвета, местами не понятные аутлайны, нужно работать ещё

2021-05-05 20:46 UTC, Sakuya-Izayoi commented
Объясните, как это должно работать? Куда их плентить? Под тайлы шлюза? Или просто на пол, а сверху закидывать хламом чтобы не было видно? Или мина должна быть заметной чтобы человек понимал что туда лучше не соваться? Но ведь тогда её можно будет спокойно обойти или даже деактивировать.

2021-05-05 20:46 UTC, AndroBetel commented
`if(anchored)
		icon_state = "[icon_state]armed"
		alpha = 45
	else
		icon_state = initial(icon_state)
		alpha = 255`

2021-05-05 20:48 UTC, KIBORG04 commented
он альфу уменьшает ей жоско. А так да, кладешь под аптечку или еще че

2021-05-05 20:53 UTC, Sakuya-Izayoi commented on code/game/objects/items/mines.dm
> +		return
Нужен ли дополнительный фидбек при фейле? Очень сомневаюсь.

2021-05-05 20:53 UTC, Sakuya-Izayoi commented on code/game/objects/items/mines.dm
> +	qdel(src)
Если все мины удаляют себя возможно здесь имеет смысл вызывать ..(), а у родителя сделать кудел?

2021-05-05 20:53 UTC, Sakuya-Izayoi commented on code/game/objects/items/mines.dm
> +		M.Weaken(5)
Игнор инжерига защищённого от электричества, то же самое сверху.

2021-05-05 20:54 UTC, KIBORG04 commented on code/game/objects/items/mines.dm
> +	qdel(src)
а можно обертку сделать для этой функции

2021-05-05 20:55 UTC, AndroBetel commented on code/game/objects/items/mines.dm
> +		return
его не будет

2021-05-05 21:32 UTC, AndroBetel commented on code/game/objects/items/mines.dm
> +		M.Weaken(5)
стан мина блюспейсом боль наносит, шоковую пофикшу

2021-05-05 21:43 UTC, AndroBetel commented
все сделал по ревью

2021-05-05 21:45 UTC, AndroBetel commented on code/game/objects/items/mines.dm
> +	qdel(src)
а в чем конкретно разница будет между куделем и вызовом родителя?

2021-05-05 21:53 UTC, Sakuya-Izayoi commented on code/game/objects/items/mines.dm
> +	qdel(src)
Это более осмысленно. Удаляться после активации это свойство вообще всех мин, а не каких-то конкретных.

2021-05-05 21:55 UTC, Sakuya-Izayoi commented on code/game/objects/items/mines.dm
> +		M.apply_effect(150,AGONY,0)
Блюспейс это круто, но абсолютно тупо. В качестве решения предлагаю умножить агонидемедж на среднеарифметическую проводимость (siemens_coefficient) одежды.

2021-05-05 21:56 UTC, AndroBetel commented on code/game/objects/items/mines.dm
> +	qdel(src)
я либо кудель пишу, либо ссылку на кудель, так что разницы не особо наблюдаю

2021-05-05 21:58 UTC, Sakuya-Izayoi commented on code/game/objects/items/mines.dm
> +		M.apply_effect(150,AGONY,0)
Ну и наверное стоит помнить про Сименс коеффициент ксенорас, если уже делать.

2021-05-05 22:40 UTC, AndroBetel commented on code/game/objects/items/mines.dm
> +		M.apply_effect(150,AGONY,0)
я не знаю как это сделать

2021-05-05 22:42 UTC, LudwigVonChesterfield commented on code/game/objects/items/mines.dm
> +	qdel(src)
```
/obj/mine/trigger_act()
    qdel(src)
    
/obj/mine/подтип/rtrigger_act()
    действия подтипа
    qdel(src)
 ```

2021-05-05 22:44 UTC, LudwigVonChesterfield commented on code/game/objects/items/mines.dm
> +		M.apply_effect(150,AGONY,0)
```
var/mob/living/L = obj
var/specie = L.get_species()
var/datum/species/S = species[specie]
var/coeff = 1
if(S)
  coeff = S.siemens_coeff
L.apply_effect(150 * coeff)
```

2021-05-05 22:46 UTC, AndroBetel commented on code/game/objects/items/mines.dm
> +	qdel(src)
rtrigger_act() не опечатка?

2021-05-05 22:49 UTC, LudwigVonChesterfield commented on code/game/objects/items/mines.dm
> +	qdel(src)
конечно опечатка. я и полный тип мины не писал

2021-05-05 22:49 UTC, LudwigVonChesterfield commented on code/game/objects/items/mines.dm
> +	qdel(src)
но такой дизайн означает что каких-то многоразовых мин по задумке быть не может

2021-05-05 22:58 UTC, Sakuya-Izayoi commented on code/game/objects/items/mines.dm
> +	qdel(src)
uses--
if(!uses) qdel

2021-05-05 22:59 UTC, AndroBetel commented on code/game/objects/items/mines.dm
> +		M.apply_effect(150,AGONY,0)
я про в общем а не только про ксеносов, да

2021-05-05 22:59 UTC, LudwigVonChesterfield commented on code/game/objects/items/mines.dm
> +	qdel(src)
я не говорю что такое делать нужно, просто что дизайн такое ограничит. я ещё посмотрел историю сообщений, Бетель этот вопрос тоже поднимал

2021-05-05 23:03 UTC, AndroBetel commented on code/game/objects/items/mines.dm
> +	qdel(src)
так если тебе не нужно, чтобы мина удалялась, ты просто не пишешь ..() или qdel #

2021-05-06 17:46 UTC, KIBORG04 commented on code/game/objects/items/mines.dm
> +	qdel(src)
А с оберткой можно было бы многоразовые делать

2021-05-06 17:48 UTC, KIBORG04 commented on code/game/objects/items/mines.dm
> +	try_trigger(Proj)
У тебя не будет работать мина от пули. У тебя в этом проке рассмотрено поведение только для карбонов и силиконов.

2021-05-06 17:49 UTC, KIBORG04 commented on code/game/objects/items/mines.dm
> +	s.start()
ты куда кудел съел?

2021-05-06 17:51 UTC, KIBORG04 commented on code/game/objects/items/mines.dm
> +	qdel(src)
`try_trigger() ` уже является оберткой для `trigger_act()`. Тебе достаточно убрать все кудели из `trigger_act()` и перенести их в самый низ `try_trigger() `

2021-05-07 11:18 UTC, Rolt146 commented
А есть ли реакция мин на мехи? Ибо я помню что некоторые вещи в механике не реагируют на мехов (например пена огнетушителя). Учтено ли это в пр?

2021-05-10 16:16 UTC, KIBORG04 commented on code/game/objects/items/mines.dm
> +	anchored = TRUE
```suggestion
	anchored = TRUE

```

2021-05-10 16:26 UTC, KIBORG04 commented on code/game/objects/items/mines.dm
> +		M.apply_effect(150,AGONY,0)
Давай коэфф сименса пили уже можно будет думать о мержах

2021-05-10 16:38 UTC, AndroBetel commented on code/game/objects/items/mines.dm
> +		M.apply_effect(150,AGONY,0)
я удалил уже эту мину потому что не хотелось мучаться

2021-05-10 19:34 UTC, KIBORG04 commented on code/game/objects/items/mines.dm
> +	if(istype(AM, /mob/living/carbon) || istype(AM, /mob/living/silicon) || istype(AM, /obj/mecha))
```suggestion
	if(istype(AM, /mob/living/carbon) || istype(AM, /mob/living/silicon) || istype(AM, /obj/mecha))
```
я же вроде писал, замени это на дефайны is_carbon, is_silicon

2021-05-10 19:34 UTC, KIBORG04 commented on code/game/objects/items/mines.dm
> +	qdel(src)
так же, вынеси кудел в try_trigger после trigger_act

2021-05-11 05:53 UTC, Sakuya-Izayoi commented
Напиши в ПРе сколько каждая мина стоит (и в какой ветке РнД последняя мина) и сколько они дамажат в цифрах

2021-05-11 17:42 UTC, KIBORG04 commented on code/game/objects/items/mines.dm
> +	trigger_act(Proj)
Думал я закончу? Вот здесь уже нужен кудел, потому что при выстреле сейчас она не будет удаляться.

2021-05-11 17:43 UTC, AndroBetel commented on code/game/objects/items/mines.dm
> +	trigger_act(Proj)
ты прав

2021-05-13 21:37 UTC, KIBORG04 commented on code/game/objects/items/mines.dm
> +	trigger_act(Proj)
Не оттягивай время мержа

2021-05-15 21:17 UTC, KIBORG04 approved these changes
Вроде норм. Если что, я могу позже переделать это в компоненту и еще чего-то написать/переписать

2021-05-18 14:16 UTC, merged