Выбор цвета костюма для хирурга
TauCetiStation/TauCetiClassic pull request #7155
Opened 2021-05-12 18:41 UTC by Invent0-r

## Описание изменений
Добавление возможности выбрать между зеленым и синим костюмом при выборе хирурга.
![image](https://user-images.githubusercontent.com/46276761/118026562-96ed3c80-b369-11eb-8fb1-c93241955f09.png)

## Почему и что этот ПР улучшит
Отсутствие необходимости переодеваться в начале каждой смены при желании сменить цвет костюма.
## Авторство
--
## Чеинжлог
:cl: Invent0_r
- tweak: Возможность выбора цвета костюма хирурга

2021-05-12 18:41 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2021-05-12 18:45 UTC, KIBORG04 requested changes
То есть тебя удовлетворяет, что на карте и в крю будет написано Ivan Pupkin (Surgeon green) ?

Очень странно сувать разные стили одежды в место альтернативного названия профессии.

Предлагаю что-то другое придумать

2021-05-12 18:46 UTC, Invent0-r commented
> То есть тебя удовлетворяет, что на карте и в крю будет написано Ivan Pupkin (Surgeon green) ?
> 
> Очень странно сувать разные стили одежды в место альтернативного названия профессии.
> 
> Предлагаю что-то другое придумать

А, ну, логично, спасибо, да.

2021-05-12 18:47 UTC, Invent0-r commented
> То есть тебя удовлетворяет, что на карте и в крю будет написано Ivan Pupkin (Surgeon green) ?
> 
> Очень странно сувать разные стили одежды в место альтернативного названия профессии.
> 
> Предлагаю что-то другое придумать

А, ну, логично, спасибо.

2021-05-12 19:07 UTC, Sakuya-Izayoi commented
Надо сделать на первой страничке чар префов там где выбор мужской/женской униформы ещё выбор цвета униформы хирурга. 

Вообще, было бы неплохо сделать для выбора цвета фреймворк. Чтобы, например, когда сделают респрайт инструментов от лижарда можно было сделать селектор цвета инструментов в поясе у инженеров на раундстарте.

2021-05-12 21:30 UTC, LudwigVonChesterfield commented
делать какие-то преференсы на работки это супер - к примеру в такие преференсы можно было бы засунуть имя клоуна. капеллану аспекты. и т.д.

в текущей реализации - плохо.

Я бы предложил чтобы у профессий которым можно доп настройки делать была кнопочка типо [JOB PREFERENCES] или там не знаю что-то такое. и ты по ней кликаешь, и в зависимости от профы преференсы. Можешь начать с врачей, а я потом скопипащу для клоуна и капеллана.

2021-05-12 21:31 UTC, LudwigVonChesterfield requested changes
Я за идею, я категорически против реализации.

А ещё у нас вроде бы красные хирурги тоже есть.

2021-05-12 22:02 UTC, Zmey25 commented
А как же Surgeon black или мы тут совсем нетолерантные стали?

2021-05-13 05:24 UTC, AndroBetel commented
может просто в лодаут добавить с локом на профу?

2021-05-13 06:59 UTC, Sakuya-Izayoi commented
> может просто в лодаут добавить с локом на профу?

Это звучит как костыль

2021-05-13 07:18 UTC, AndroBetel commented
тогда надо удалить лодаут, он же костыль, а не место для кастомизации своей куколки.

2021-05-13 09:04 UTC, LudwigVonChesterfield commented
если в лоадаут добавлять все предметы в билде и лочить их за профами у тебя руки и глаза сломаются искать ту самую шмотку которую ты хочешь

2021-05-19 19:00 UTC, KIBORG04 commented
Пока закрою ПР. Обратись к билд мейнтейнерам в дискорде или как-то еще сообщи, чтобы открыли заного.

2021-05-19 19:00 UTC, closed without merging