Medborg
TauCetiStation/TauCetiClassic pull request #7185
Opened 2021-05-18 17:42 UTC by Zickusable

## Описание изменений
Переименовал хирургический модуль в медицинский, перекопировал плюшки из кризис-модуля, добавил бёрн кит, добавил лекарства в гипоспрей, удалил кризис модуль
## Почему и что этот ПР улучшит
Два модуля, практически бесполезные друг без друга. Хирург не сможет реанимировать труп, а значит и операции бессмысленны. Кризис может реанимировать, но смысл, если пациент умирает от повреждений органов? То, что они не могут друг без друга, делает игру на борге-медике еще более скучной.
## Авторство

## Чеинжлог
:cl:
- experiment: Объединение кризис и хирург модулей борга

2021-05-18 17:42 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2021-05-18 20:00 UTC, LudwigVonChesterfield commented on code/modules/reagents/reagent_containers/borghydro.dm
> +	reagent_ids = list("bicaridine", "kelotane", "inaprovaline", "dexalin", "tramadol", "anti_toxin")
трамадол же позволяет полностью игнорировать боль при операциях, да?

2021-05-19 03:34 UTC, Zickusable commented on code/modules/reagents/reagent_containers/borghydro.dm
> +	reagent_ids = list("bicaridine", "kelotane", "inaprovaline", "dexalin", "tramadol", "anti_toxin")
Должен.

2021-05-19 18:55 UTC, KIBORG04 commented
Зачем тут вообще эксперимент? Больше похоже на фичу обычную

2021-05-19 18:56 UTC, KIBORG04 commented on code/modules/mob/living/silicon/robot/robot_modules.dm
> +	if(src.emag)
```suggestion
	if(emag)
```

2021-05-19 18:56 UTC, KIBORG04 commented on code/modules/mob/living/silicon/robot/robot_modules.dm
> +		var/obj/item/weapon/reagent_containers/spray/PS = src.emag
```suggestion
		var/obj/item/weapon/reagent_containers/spray/PS = emag
```

2021-05-19 18:57 UTC, KIBORG04 commented on code/modules/mob/living/silicon/robot/robot.dm
>  				camera.add_network("Medical")
Добавь куда-то сюда тобою удаленный скин
`module_sprites["Drone"] = "drone-medical"`

2021-05-19 18:57 UTC, Zickusable commented
> Зачем тут вообще эксперимент? Больше похоже на фичу обычную

Мне кажется, что это будет слишком имбалансно в какой-нибудь нюке и в умелых руках.

2021-05-20 21:15 UTC, KIBORG04 commented
![image](https://user-images.githubusercontent.com/26389417/119049719-8e2fe280-b9c9-11eb-930b-4e720e84ac16.png)

Ну впринципе первый фидбек. Насколько он важный решать не мне

2021-05-20 23:19 UTC, KIBORG04 approved these changes

2021-05-21 10:31 UTC, kalazus commented on code/modules/mob/living/silicon/robot/robot_modules.dm
> +/obj/item/weapon/robot_module/medical/respawn_consumable(mob/living/silicon/robot/R)
Возможно я чего-то не понимаю, но зачем верхние строки если функция переопределена? И дальше есть кусок кода который почти полностью соответствует этому.

2021-05-21 12:22 UTC, KIBORG04 commented on code/modules/mob/living/silicon/robot/robot_modules.dm
> +/obj/item/weapon/robot_module/medical/respawn_consumable(mob/living/silicon/robot/R)
Действительно, я че-то проглядел, ненужная копипаста

2021-05-21 14:40 UTC, KIBORG04 requested changes
Комментарий выше. Убери не нужное

2021-05-21 16:49 UTC, Sakuya-Izayoi commented on code/game/objects/items/weapons/defibrillator.dm
> +	if(H.stat == DEAD && IO.heart_status == HEART_FAILURE && !(istype(user, /mob/living/silicon/robot)))
Я сомневаюсь что это работает как задумывалось. Чтобы реанимировать пациента нужно перевести его сердце в состояние HEART_FIBR.

И вообще, это слишком жирно для борга. Не нужно (имхо)

2021-05-21 16:59 UTC, Zickusable commented on code/game/objects/items/weapons/defibrillator.dm
> +	if(H.stat == DEAD && IO.heart_status == HEART_FAILURE && !(istype(user, /mob/living/silicon/robot)))
Если я правильно понимаю, я пропускаю шаг с массажем.
Жирно для борга? В том и смысл ПРа, чтоб он мог сам реанимировать и оперировать

2021-05-21 17:00 UTC, Sakuya-Izayoi commented
Может ли медборг делать операцию на глазах?

2021-05-21 17:06 UTC, Sakuya-Izayoi commented on code/game/objects/items/weapons/defibrillator.dm
> +	if(H.stat == DEAD && IO.heart_status == HEART_FAILURE && !(istype(user, /mob/living/silicon/robot)))
```suggestion
	if(H.stat == DEAD && IO.heart_status == HEART_FAILURE && !(isrobot(user)))
```

2021-05-21 18:40 UTC, Sakuya-Izayoi commented on code/modules/reagents/reagent_containers/borghydro.dm
> +	volume = 50
Мне кажется это уже вышло за рамки ПРа, который был про "объединение двух модулей, практически бесполезных друг без друга", а не про баффы медборготы.

2021-05-21 18:43 UTC, KIBORG04 commented on code/modules/reagents/reagent_containers/borghydro.dm
> +	volume = 50
Стелсобаффы, лучше в другом ПРе сделай

2021-05-21 18:47 UTC, KIBORG04 requested changes
Ладно, копипасту убрали. Теперь давай уберем стелосбаффы. ПР же про объединение двух модулей в один, а не ОБЪЕДИНЕНИЕ ДВУХ МОДУЛЕЙ КИБОРГОВ В ОДИН И БАФФ МЕДИЦИНСКИХ БОРГОВ.
Поэтому, давай в другой ПР это вынесем и там уже обсудим

2021-05-21 19:15 UTC, Zickusable commented on code/modules/reagents/reagent_containers/borghydro.dm
> +	volume = 50
```suggestion
	volume = 30
```

2021-05-22 15:07 UTC, KIBORG04 requested changes
Штош, мы на финишной прямой. Осталось убрать магическое запусканием серца дефибом боргов. 
Как я уже писал ранее, вынеси это в другой ПР где можно будет обсудить, тут же ломается атомарность ПРа и бла-бла-бла. Да и более конкретно можно будет это все ревертнуть, без удаления новой фичи

2021-05-22 15:21 UTC, Zickusable commented on code/game/objects/items/weapons/defibrillator.dm
> +	if(H.stat == DEAD && IO.heart_status == HEART_FAILURE && !(isrobot(user)))
```suggestion
	if(H.stat == DEAD && IO.heart_status == HEART_FAILURE)
```

2021-05-22 16:04 UTC, KIBORG04 approved these changes
Da

2021-05-23 19:16 UTC, KIBORG04 commented on code/modules/mob/living/silicon/robot/drone/drone_items.dm
> +
В can_hold не обязательно указывать конкретный тип предмета. Мне кажется, логично если можно будет держать все части тела и любые части роботов. Поэтому, можно сделать так. Разрешаю обжаловать.
```suggestion
	can_hold = list(
		/obj/item/weapon/reagent_containers/blood,
		/obj/item/weapon/reagent_containers/glass,
		/obj/item/weapon/storage/pill_bottle,
		/obj/item/organ/internal,
		/obj/item/organ/external,
		/obj/item/robot_parts,
		)

```

2021-05-23 19:24 UTC, Zickusable commented on code/modules/mob/living/silicon/robot/drone/drone_items.dm
> +
С органами – да, а вот держать торс или голову робота не нужно, они никак не относятся к хирургии. Можно добавить еще мясо для зарядки в клонилку.
Надо еще добавить взаимодействия с моргом и холодильником химии, мешок для вещей пациента, гриппер с хелп интентои для тех, кто не знает про IC>>rest, но это уже совсем другой ПР...

2021-05-23 19:25 UTC, KIBORG04 commented on code/modules/mob/living/silicon/robot/drone/drone_items.dm
> +
Ну значит пусть не трогает борготорсы, но органы надо

2021-05-24 10:46 UTC, Zickusable commented on code/modules/mob/living/silicon/robot/drone/drone_items.dm
> +
```suggestion
	can_hold = list(
		/obj/item/weapon/reagent_containers/blood,
		/obj/item/weapon/reagent_containers/glass,
		/obj/item/weapon/storage/pill_bottle,
		/obj/item/organ/internal,
		/obj/item/organ/external,
		/obj/item/robot_parts/l_arm,
		/obj/item/robot_parts/r_arm,
		/obj/item/robot_parts/l_leg,
		/obj/item/robot_parts/r_leg
		)

```

2021-05-26 18:31 UTC, merged