Port [Shredder for paper] from Vorestation
TauCetiStation/TauCetiClassic pull request #7188
Opened 2021-05-19 08:25 UTC by Phoenix4O4

## Описание изменений
Порт шредера для бумаги с VoreStation/Baystation
![Honeycam 2021-05-19 11-02-55](https://user-images.githubusercontent.com/41524861/118777510-d21fcc00-b891-11eb-83af-38d375cb0e5b.gif)
## Почему и что этот ПР улучшит
Больше власти бюрократам. 
## Авторство
Спрайты, звук, код[Vorestation](https://github.com/VOREStation/VOREStation)
## Чеинжлог

 :cl:
 - rscadd: Добавлен шредер для бумаги. Находится у главы персонала и в библиотеке

2021-05-19 08:25 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2021-05-19 08:28 UTC, AndroBetel commented
некрасиво и бесполезно =(

2021-05-19 09:43 UTC, LudwigVonChesterfield commented on code/modules/paperwork/papershredder.dm
> +	if(usr.stat || usr.restrained() || usr.weakened || usr.paralysis || usr.lying || usr.stunned)
```suggestion
	if(usr.incapacitated())
```

2021-05-19 09:44 UTC, LudwigVonChesterfield commented on code/modules/paperwork/papershredder.dm
> +	if(empty_into?.contents.len>0)
а почему оно не заполняет если даже если в хранилище всего одна ручка...

2021-05-19 09:44 UTC, LudwigVonChesterfield commented on code/modules/paperwork/papershredder.dm
> +	if(empty_into && !istype(empty_into))
почему здесь не return

и зачем это вообще нужно

2021-05-19 09:44 UTC, LudwigVonChesterfield commented on code/modules/paperwork/papershredder.dm
> +		if(!SP) break
разбей на две строчки пожалуйста

2021-05-19 09:45 UTC, LudwigVonChesterfield commented on code/modules/paperwork/papershredder.dm
> +	if(empty_into)
ты нигде не нуллил ссылку...

2021-05-19 09:45 UTC, LudwigVonChesterfield commented on code/modules/paperwork/papershredder.dm
> +	if(empty_into && !istype(empty_into))
я кажется понял

2021-05-19 09:47 UTC, LudwigVonChesterfield commented
а зачем он нужен если можно сжигать бумажку

2021-05-19 10:05 UTC, Phoenix4O4 commented
> а зачем он нужен если можно сжигать бумажку

Так он не только бумагу уничтожает.

2021-05-19 10:44 UTC, Kerzch commented
> Так он не только бумагу уничтожает. Те же айди карты, например.

Это уже даже не бесполезная, а вредительская функция. Зачем уничтожать айди карты, если их можно переписывать повторно?

2021-05-19 11:16 UTC, cool20141 commented
Vorestation :vomiting_face:

2021-05-19 11:28 UTC, BesumniiChebureck commented
Шредер для бумаги на самом деле не бесполезен. Но спрайты для него конечно оставляют желать лучшего.

2021-05-19 12:18 UTC, Phoenix4O4 commented
> Шредер для бумаги на самом деле не бесполезен. Но спрайты для него конечно оставляют желать лучшего.
Можно и иные спрайты подтянуть, если будут желающие поспрайтить.

2021-05-19 18:41 UTC, KIBORG04 commented on code/modules/paperwork/papershredder.dm
> +	anchored = 1
```suggestion
	density = TRUE
	anchored = TRUE
```

2021-05-19 18:42 UTC, KIBORG04 commented on code/modules/paperwork/papershredder.dm
> +	else if(default_unfasten_wrench(user, W))
Может без этих else сделаешь? Они все равно не нужны, а только затрудняют читаемость

2021-05-19 18:43 UTC, KIBORG04 commented on code/modules/paperwork/papershredder.dm
> +	return ..()
В каких вообще случаях этот ретурн будет вызывать?

2021-05-19 18:43 UTC, KIBORG04 commented on code/modules/paperwork/papershredder.dm
> +	if(empty_into?.contents.len>0)
```suggestion
	if(empty_into?.contents.len > 0)
```

2021-05-19 18:43 UTC, KIBORG04 commented on code/modules/paperwork/papershredder.dm
> +/obj/machinery/papershredder/proc/empty_bin(var/mob/living/user, var/obj/item/weapon/storage/empty_into)
```suggestion
/obj/machinery/papershredder/proc/empty_bin(mob/living/user, obj/item/weapon/storage/empty_into)
```

2021-05-19 18:44 UTC, KIBORG04 commented on code/modules/paperwork/papershredder.dm
> +	spawn(rand(0,15))
Мы отходим от использования спавнов. Замени это на addtimer

2021-05-19 18:48 UTC, KIBORG04 commented on code/modules/paperwork/papershredder.dm
> +	overlays += "shredder-[max(0,min(5,FLOOR(paperamount/max_paper*5, 1)))]"
```suggestion
	overlays += "shredder-[clamp(0, 5, FLOOR(paperamount/max_paper*5, 1))]"
```
Вроде правильно преобразовал

2021-05-19 18:48 UTC, KIBORG04 commented on code/modules/paperwork/papershredder.dm
> +	pixel_y = rand(-5,5)
```suggestion
	pixel_x = rand(-5, 5)
	pixel_y = rand(-5, 5)
```

2021-05-19 18:49 UTC, KIBORG04 commented on code/modules/paperwork/papershredder.dm
> +	if(prob(65)) color = pick("#BABABA","#7F7F7F")
```suggestion
	if(prob(65))
		color = pick("#BABABA", "#7F7F7F")
```

2021-05-19 18:49 UTC, KIBORG04 commented on code/modules/paperwork/papershredder.dm
> +/obj/item/weapon/shreddedp/attackby(var/obj/item/P as obj, var/mob/user)
```suggestion
/obj/item/weapon/shreddedp/attackby(obj/item/P, mob/user)
```
Сам потом ниже пробегись по всем `var/` в параметрах функций

2021-05-19 18:53 UTC, KIBORG04 commented on code/modules/paperwork/papershredder.dm
> +					SP.loc = get_turf(src)
```suggestion
					SP.forceMove(loc)
```
гет турф поидее не нужен в этом случае, не так ведь важно дропать именно на пол

2021-05-19 18:53 UTC, KIBORG04 commented on code/modules/paperwork/papershredder.dm
> +					SP.throw_at(get_edge_target_turf(src,pick(alldirs)),1,5)
```suggestion
					SP.throw_at(get_edge_target_turf(src, pick(alldirs)), 1, 5)
```

2021-05-19 19:46 UTC, KIBORG04 commented on code/modules/paperwork/papershredder.dm
> +/obj/item/weapon/shreddedp/attackby(var/obj/item/P as obj, var/mob/user)
А, там уже линтер на это ругается

2021-05-19 23:22 UTC, Zmey25 commented
> бесполезно =(

Меня за км-революционера сажали в бриг за заказ оружия, потому что я бумажки с заказом не сжигал, а клал в ящик рядом. За зажигалкой было лень бежать.

Но скорее всего спрайтеры не пропустят, потому что не они его рисовали :peka:

2021-05-20 12:22 UTC, LudwigVonChesterfield commented
^
твоё лицо когда за КМ-а не отправляешь бумажки с печатью чтобы получить больше очков

2021-05-20 12:26 UTC, Sakuya-Izayoi commented
> ^
> твоё лицо когда за КМ-а не отправляешь бумажки с печатью чтобы получить больше очков

так очки дают за бумажки из ящиков

2021-05-27 11:02 UTC, Udokun commented
Слишком футуристичный спрайт для обычного шредера. Посмотри на спрайты установки в кабинете ХоПа.

2021-05-27 11:19 UTC, Phoenix4O4 commented
> > Шредер для бумаги на самом деле не бесполезен. Но спрайты для него конечно оставляют желать лучшего.
> 
> Можно и иные спрайты подтянуть, если будут желающие поспрайтить.



> Слишком футуристичный спрайт для обычного шредера. Посмотри на спрайты установки в кабинете ХоПа.

Я не собираюсь вам спрайтить и проходить спрайтер комисии. Уже писалось что хотите - хоть спрайт с луны ставьте. Найдите того кто спрайтить будет.

2021-05-31 16:55 UTC, Sakuya-Izayoi commented
Выполни требования линтера
https://github.com/TauCetiStation/TauCetiClassic/pull/7188/checks?check_run_id=2682427944

2021-05-31 16:58 UTC, Phoenix4O4 commented
> Исправь предупреждения линтера
> https://github.com/TauCetiStation/TauCetiClassic/pull/7188/checks?check_run_id=2682427944

Так а спрайтов все равно же нет. Поправить все тут быстро можно.

2021-05-31 18:15 UTC, T6751 reviewed
В следующих случаях нужно убрать ```var/``` из параметров
![image](https://user-images.githubusercontent.com/66636084/120229009-ee8a1400-c254-11eb-89e2-87ee17bfac0d.png)

Здесь цвет запиши маленькими буковками (должно быть ```#bababa``` ```#7f7f7f```
![image](https://user-images.githubusercontent.com/66636084/120229070-0eb9d300-c255-11eb-886d-e8da253c36f5.png)

2021-05-31 18:20 UTC, T6751 requested changes

2021-05-31 18:20 UTC, T6751 commented on code/modules/paperwork/papershredder.dm
> +	spawn(rand(0,15))
Здесь спавн нужно заменить на аддтаймер
```suggestion
	addtimer(CALLBACK(src, .proc/update_icon), rand(0,15))
```

2021-05-31 18:20 UTC, T6751 commented on code/modules/paperwork/papershredder.dm
> +	else if(default_unfasten_wrench(user, W))
Здесь и ниже ```else``` излишен. Нужно просто убрать, как и сказал киборг

2021-05-31 18:20 UTC, T6751 commented on code/modules/paperwork/papershredder.dm
> +		if(!SP) break
```suggestion
		if(!SP)
				break
```

2021-05-31 18:24 UTC, T6751 commented on code/modules/paperwork/papershredder.dm
> +	anchored = 1
Эти переменные используются как булевы - нужно использовать TRUE/FALSE вместо 1/0
```suggestion
	density = TRUE
	anchored = TRUE
```

2021-05-31 18:24 UTC, T6751 commented on code/modules/paperwork/papershredder.dm
> +	if(empty_into)
Ссылка может нуллиться в 108 строке

2021-05-31 18:26 UTC, T6751 commented on code/modules/paperwork/papershredder.dm
> +	return ..()
@Phoenix4O4 Когда уберёшь лишние ```else``` то поймешь в здесь проблема

2021-06-03 08:49 UTC, Phoenix4O4 commented
Need sprites label

2021-06-14 18:46 UTC, Phoenix4O4 commented
> Данный ПР автоматически отмечен как застоявшийся по причине длительного отсутствия обновлений. Он будет закрыт через 7 дней, если никакой активности не будет проявлено. Если вы считаете, что ПР еще актуален, или что я (злобный робот) пристаю к вам зря - просто напишите любой комментарий. Спасибо за ваш вклад.

2021-06-14 18:56 UTC, KIBORG04 commented
Да срашный шреддер какой-то

2021-06-16 18:05 UTC, Phoenix4O4 commented
> Да срашный шреддер какой-то

Да страшный, да. Куплю спрайты для шредера, оплата при аппруве спрайтолобби

2021-06-16 19:41 UTC, T6751 reviewed
```Один пробел перед оператором и один пробел после.```
```Следуйте единому формату. Так или иначе пробел после запятой - обязателен.```

2021-06-16 19:41 UTC, T6751 commented on code/modules/paperwork/papershredder.dm
> +			for(var/i=(paperamount-max_paper);i>0;i--)
```suggestion
			for(var/i = paperamount - max_paper ; i > 0 ; i--)
```

2021-06-16 19:41 UTC, T6751 commented on code/modules/paperwork/papershredder.dm
> +	addtimer(CALLBACK(src, .proc/update_icon), rand(0,15))
```suggestion
	addtimer(CALLBACK(src, .proc/update_icon), rand(0, 15))
```

2021-06-16 19:41 UTC, T6751 commented on code/modules/paperwork/papershredder.dm
> +	overlays += "shredder-[clamp(0, 5, FLOOR(paperamount/max_paper*5, 1))]"
```suggestion
	overlays += "shredder-[clamp(0, 5, FLOOR(paperamount / max_paper * 5, 1))]"
```

2021-06-16 19:41 UTC, T6751 commented on code/modules/paperwork/papershredder.dm
> +	if(!do_after(user,20))
```suggestion
	if(!do_after(user, 20))
```

2021-06-16 19:41 UTC, T6751 commented on code/modules/paperwork/papershredder.dm
> +			to_chat(user,"<span class='danger'>\The [src] was too full, and shredded paper goes everywhere!</span>")
```suggestion
			to_chat(user, "<span class='danger'>\The [src] was too full, and shredded paper goes everywhere!</span>")
```

2021-06-16 20:29 UTC, 4310V343k commented on code/modules/paperwork/papershredder.dm
> +			for(var/i=(paperamount-max_paper);i>0;i--)
[Работа с циклами (black magic)](https://github.com/TauCetiStation/TauCetiClassic/wiki/Code-Convention#%D0%A0%D0%B0%D0%B1%D0%BE%D1%82%D0%B0-%D1%81-%D1%86%D0%B8%D0%BA%D0%BB%D0%B0%D0%BC%D0%B8-black-magic)

2021-07-02 21:52 UTC, T6751 commented
Когда появятся спрайты, сообщите и мы снова откроем этот ПР

2021-07-02 21:52 UTC, closed without merging