addsthething
TauCetiStation/TauCetiClassic pull request #7194
Opened 2021-05-22 13:41 UTC by AndroBetel

## Описание изменений
добавляет арену для драк после конца раунда и преф на то чтобы тебя туда тпшило, он включен по умолчанию, чтобы нубики не гриферили шатол а радостно резвились на арене.
## Почему и что этот ПР улучшит
надеюсь что снизится процент банов за гриф после конца раунда
## Авторство
я
## Чеинжлог
:cl:
- experimental: Возможность после конца раунда телепортироваться на арену и воевать, оставив включенным преференс Toggle End of Round Deathmatch Candidacy.

2021-05-22 13:41 UTC, TauKitty commented
###### Changelog status: :x: Invalid changelog classes (experimental)

2021-05-22 13:43 UTC, Sakuya-Izayoi commented
можно сделать чтобы аттаклоги с этой зоны не приходили админам?

2021-05-22 13:44 UTC, AndroBetel commented
админам насрать на аттаклоги после конца раунда, потому что они смотрят их либо в реплее, либо в отдельном окошке с файлом логов.

2021-05-22 13:44 UTC, KIBORG04 commented on code/controllers/subsystem/ticker.dm
> +
```suggestion
	for(var/mob/living/M in global.player_list)
		if(isnewplayer(M))
			continue
		if(!M.client.prefs.eorg_enabled)
			continue
		M.forceMove(pick(eorgwarp))
		to_chat(M, "<span class='warning'>Welcome to End of Round Deathmatch Arena! Go hog wild and let out some steam!.</span>"

```
1. Сделай для этого отдельный прок
2. Сделай как я выше

2021-05-22 13:45 UTC, KIBORG04 commented on code/modules/client/preferences.dm
> +	var/eorg_enabled = TRUE
Лучше сделать фолс, зачем в первый же раунд всех туда? Это как бы сломает девочек

2021-05-22 13:46 UTC, KIBORG04 commented on code/modules/client/preferences_toggles.dm
> +	feedback_add_details("admin_verb", "ED")
```suggestion
	feedback_add_details("admin_verb", "ED")

```

2021-05-22 13:47 UTC, Sakuya-Izayoi commented on code/modules/client/preferences.dm
> +	var/eorg_enabled = TRUE
Это с одной стороны, а с другой, к нам приходят со всяких сс220 и прочих "серверов", где еорг это норма и они уже будут ломать наших девочек.

2021-05-22 13:47 UTC, AndroBetel commented on code/modules/client/preferences.dm
> +	var/eorg_enabled = TRUE
потому что гриферят ТОЛЬКО нубы, и нубы не смогут поменять галочку в преференсах и будут дальше гриферить на шаттле.

2021-05-22 13:49 UTC, KIBORG04 commented on code/modules/client/preferences.dm
> +	var/eorg_enabled = TRUE
Её нужно сначала найти.
Я предлагаю добавить эту кнопку в сетап чарахтере, чтобы прям только илита знала о секретной арене. Да и вообще, зачем именно арену, если можно в том же тандердроме

2021-05-22 13:51 UTC, KIBORG04 commented on code/modules/client/preferences_toggles.dm
> +	set name = "Toggle End of Round Deathmatch Candidacy"
Название слишком длинное, могут быть проблемы вроде

2021-05-22 13:51 UTC, AndroBetel commented on code/modules/client/preferences.dm
> +	var/eorg_enabled = TRUE
ты кажется вообще не понял смысла этой кнопки.

2021-05-22 13:53 UTC, AndroBetel commented on code/modules/client/preferences_toggles.dm
> +	set name = "Toggle End of Round Deathmatch Candidacy"
ага

2021-05-22 13:54 UTC, TauKitty commented
This pull request has been mentioned on **Tau Ceti Station Forum**. There might be relevant details there:

https://forum.taucetistation.org/t/vote-grif-posle-koncza-raunda-i-vse-vse-vse/25546/37

2021-05-22 13:55 UTC, KIBORG04 commented on code/modules/client/preferences.dm
> +	var/eorg_enabled = TRUE
Я не понимаю зачем прямо всех туда пихать

2021-05-22 13:55 UTC, AndroBetel commented on code/modules/client/preferences.dm
> +	var/eorg_enabled = TRUE
чтобы уважающие рп игроки выключили этот преф достаточно будет одного раунда (60 секунд) или напоминания админов при тестмерже/мерже, так что не вижу проблемы, вот.

2021-05-22 13:58 UTC, KIBORG04 commented on code/modules/client/preferences_savefile.dm
> +	S["eorg_enabled"]		>> eorg_enabled
а еще у тебя нету загрузки из файла этого конфига. Вбей в поиск тот же `outline_color` и покопипасть где нужно

2021-05-22 14:08 UTC, AndroBetel commented on code/modules/client/preferences_savefile.dm
> +	S["eorg_enabled"]		>> eorg_enabled
сделол

2021-05-22 14:15 UTC, KIBORG04 commented on code/game/objects/effects/landmarks.dm
> +		if("eorgwarp")
У тебя почти все лендмарки с названием `tdome2`

2021-05-22 14:15 UTC, AndroBetel commented on code/game/objects/effects/landmarks.dm
> +		if("eorgwarp")
ой блядь

2021-05-22 14:16 UTC, KIBORG04 commented on maps/centcom/centcom.dmm
> +	},
Так лучше не делать, сделай объект в игре и его ставь, без макхардкода

2021-05-22 14:16 UTC, KIBORG04 commented on maps/centcom/centcom.dmm
> +	name = "tdome2"
те самые

2021-05-22 14:16 UTC, AndroBetel commented on maps/centcom/centcom.dmm
> +	},
это уже был пресет до меня, ничего не знаю.

2021-05-22 14:28 UTC, AndroBetel commented
я все сделал давайте в тестмерж

2021-05-22 16:26 UTC, AndroBetel commented
я переделал, теперь кукол не тпшит на арену, а создается новая и в неё перепихивает mind куклы.

2021-05-22 16:28 UTC, KIBORG04 commented on code/controllers/subsystem/ticker.dm
> +		if(isliving(M) || isAI(M))
Удали эту строчку, она не имеет смысла

2021-05-22 16:30 UTC, AndroBetel commented on code/controllers/subsystem/ticker.dm
> +		if(isliving(M) || isAI(M))
isliving??

2021-05-22 16:33 UTC, KIBORG04 commented on code/controllers/subsystem/ticker.dm
> +		if(isliving(M) || isAI(M))
Лучше всю. Тогда и боргов закинет и алиенов и прочую чушню

2021-05-22 16:42 UTC, KIBORG04 commented on code/controllers/subsystem/ticker.dm
> +		L = new /mob/living/carbon/human(pick(eorgwarp))
```suggestion
		var/mob/living/carbon/human/L = new(pick(eorgwarp))
```

2021-05-22 16:43 UTC, KIBORG04 commented on code/controllers/subsystem/ticker.dm
> +		L = new /mob/living/carbon/human(pick(eorgwarp))
А еще их будет спавнить внутри лендмарки, тести хотя бы

2021-05-22 16:43 UTC, KIBORG04 commented on code/controllers/subsystem/ticker.dm
> +		L = new /mob/living/carbon/human(pick(eorgwarp))
а, не будет, извиняюсь

2021-05-22 17:19 UTC, AndroBetel commented on code/controllers/subsystem/ticker.dm
> +		L = new /mob/living/carbon/human(pick(eorgwarp))
твоя штука мне кажется как-то не так будет работать

2021-05-22 17:31 UTC, AndroBetel commented on code/controllers/subsystem/ticker.dm
> +		L = new /mob/living/carbon/human(pick(eorgwarp))
всё правильно она рабоатет, спасибо

2021-05-22 17:41 UTC, muWander commented
> я переделал, теперь кукол не тпшит на арену, а создается новая и в неё перепихивает mind куклы.

а в чем смысл если нельзя будет стреляться налутанными пушками и махать катаной с астероида

2021-05-22 17:42 UTC, AndroBetel commented
в том что челиков не будет магически телепортировать прямо из ролевой рп ситуации, а они будут мирнейше засыпать на месте

2021-05-22 18:14 UTC, LudwigVonChesterfield commented
как-то грустно что драки только рукопашные будут

2021-05-22 18:15 UTC, AndroBetel commented
почему только рукопашные?

2021-05-22 18:15 UTC, LudwigVonChesterfield commented
я кажется чего-то не вижу. а откуда будет браться оружие?

2021-05-22 18:16 UTC, LudwigVonChesterfield commented
а, не только код смотреть надо...

2021-05-22 18:16 UTC, BesumniiChebureck commented
![image-arena](https://user-images.githubusercontent.com/67091522/119236946-e5a58e00-bb42-11eb-9435-7f43a29c3e5e.png)
Там все объекты рандом_хелмет, рандом_лазер_ган и т.д.

2021-05-22 19:07 UTC, Sakuya-Izayoi commented
Если есть area, то, наверное, можно обойтись без ландмарков? А то ландмарков всего 30 или сколько там, а игроков на сервере 70. Можно сделать pick(turf in area) или как-то так.

2021-05-22 19:08 UTC, AndroBetel commented
может заспавнить в стенах или там у мехов, так безопаснее.

2021-05-23 11:10 UTC, TauKitty commented
This pull request has been mentioned on **Tau Ceti Station Forum**. There might be relevant details there:

https://forum.taucetistation.org/t/vote-grif-posle-koncza-raunda-i-vse-vse-vse/25546/48

2021-05-23 11:27 UTC, KIBORG04 commented on code/game/area/custom_areas.dm
> +	dynamic_lighting = DYNAMIC_LIGHTING_FORCED
```suggestion
	dynamic_lighting = DYNAMIC_LIGHTING_FORCED

```

2021-05-23 19:13 UTC, KIBORG04 commented
Закину в ТМ на первый. Посмотрит че как и уже потом мерж

2021-05-23 22:09 UTC, AndroBetel commented
обновите тм

2021-05-23 22:24 UTC, KIBORG04 commented on code/game/objects/random/random_melee.dm
> +					)
```suggestion
					)

```

2021-05-24 10:12 UTC, volas requested changes
Нужен серверный конфиг на отключение арены, и педальная кнопка на переключение этого конфига в раунде

2021-05-24 10:16 UTC, volas commented on code/controllers/subsystem/ticker.dm
> +		if(isnewplayer(M))
лишнее, это проверка на ``/mob/dead/new_player`` но ты уже в определенном списке смотришь

2021-05-24 10:45 UTC, AndroBetel commented
вроде бы сделал конфиг, если не сделал - объясните как, пожалуйста

2021-05-24 12:42 UTC, KIBORG04 commented on code/modules/admin/admin.dm
> +
```suggestion
```

2021-05-24 12:43 UTC, KIBORG04 commented on code/controllers/configuration.dm
> +				if("deathmatch_arena")
Добавь в файл конфигов, который в example этот флаг.

2021-05-24 13:36 UTC, volas commented on code/controllers/configuration.dm
> +				if("deathmatch_arena")
В текущем варианте, если он по дефолту TRUE, и если конфиг может установить только в TRUE - у нас нет возможности установить в FALSE через конфиг.
Сделай лучше конфиг.txt ``DEATHMATCH_ARENA 1`` и ниже ``config.deathmatch_arena = text2num(value)``

2021-05-24 13:37 UTC, volas commented on code/modules/admin/admin.dm
> +/datum/admins/proc/toggle_deathmatch_arena()
Нужно добавить прок в список кнопок, admin_verbs.dm

2021-05-24 14:03 UTC, muWander commented
уберите доступ на мехов

2021-05-24 15:36 UTC, AndroBetel commented
я сделал конфиг

2021-05-25 10:00 UTC, BesumniiChebureck commented
Возможно фича, но гостов не кидает на арену.

2021-05-25 10:03 UTC, AndroBetel commented
да ето фичя

2021-05-25 10:39 UTC, BesumniiChebureck commented
Но ведь гост может стать мышей и тогда его закинет на арену

2021-05-27 10:31 UTC, Phoenix4O4 commented
А где функция отказаться от этого? Почему игроков должно принудительно кидать на арену?

2021-05-27 12:01 UTC, Sakuya-Izayoi commented
Отказаться от этого можно во вкладке преференс в панельке вербов. По-умолчанию он включен потому что целевая аудитория этой арены не способна догадаться переключить этот самый преференс.

2021-05-27 20:31 UTC, KIBORG04 commented on code/controllers/subsystem/ticker.dm
> +		if(!(M.client.prefs.eorg_enabled))
```suggestion
		if(!M.client.prefs.eorg_enabled)
```

2021-05-27 20:34 UTC, Sakuya-Izayoi commented on code/modules/admin/admin.dm
> +	set name="Toggle Roundend Deathmatch"
```suggestion
	set desc = "Toggle arena on the round end."
	set name = "Toggle Roundend Deathmatch"
```

2021-05-27 20:41 UTC, KIBORG04 commented
Ну вроде комментарий воласа учтен, произвожу мержжж

2021-05-27 20:41 UTC, merged