Борги могут реанимировать без посторонней помощи (массажа сердца) дефибами
TauCetiStation/TauCetiClassic pull request #7197
Opened 2021-05-22 16:55 UTC by Zickusable

## Описание изменений
Пропустил шаг с массажем сердца для дефибов
## Почему и что этот ПР улучшит
~Без боргов таукита нежизнеспособна~. Не придется искать живого тестовика, чтоб он сделал массаж сердца при низком онлайне. Делает самодостаточным и независимым от человеков.
## Авторство

## Чеинжлог
:cl:
- tweak: Мед. борг реанимирует без массажа сердца

2021-05-22 16:55 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2021-05-22 17:09 UTC, Sakuya-Izayoi commented on code/game/objects/items/weapons/defibrillator.dm
> +	if(H.stat == DEAD && IO.heart_status == HEART_FAILURE && !(isrobot(user)))
Я тебе ещё в том ПРе написал, что это не решает проблему. Борги все ещё не смогут реанимировать при нерабочем сердце и им нужен кто-то кто будет переводить его в состоянии фибрилляции. Ты это тестил хотя бы?

2021-05-22 17:12 UTC, Zickusable commented on code/game/objects/items/weapons/defibrillator.dm
> +	if(H.stat == DEAD && IO.heart_status == HEART_FAILURE && !(isrobot(user)))
Если что-то не работает, то я не пушу

2021-05-22 17:31 UTC, Sakuya-Izayoi commented on code/game/objects/items/weapons/defibrillator.dm
> +	if(H.stat == DEAD && IO.heart_status == HEART_FAILURE && !(isrobot(user)))
Как ты тогда объяснишь это? Видео записано на твоей ветке.
https://streamable.com/4lzc34

2021-05-22 17:40 UTC, Zickusable commented on code/game/objects/items/weapons/defibrillator.dm
> +	if(H.stat == DEAD && IO.heart_status == HEART_FAILURE && !(isrobot(user)))
Ндаа... у меня нет слов в свое оправдание, позже доведу до ума =(

2021-05-23 11:22 UTC, KIBORG04 requested changes
Сейчас решение выглядит очень некрасиво. Заметь, что эта функция вообще никак не зависит от юзера, она прямо красиво настроена только для цели.
Чтобы это было красивее, предлагаю сделать специальный дефиб для киборгов, который будет эвэйдить некрасивые места

2021-05-26 18:04 UTC, KIBORG04 commented on code/game/objects/items/weapons/defibrillator.dm
> +/obj/item/weapon/twohanded/shockpaddles/attack(mob/M, mob/living/carbon/user, def_zone)
```suggestion
/obj/item/weapon/twohanded/shockpaddles/attack(mob/M, mob/living/user, def_zone)
```

2021-05-26 18:05 UTC, KIBORG04 requested changes
Я не говорил про копипасту. Почитай что такое полиморфизм в ООП и тогда МОЖЕТ БЫТЬ сам поймешь как сделать правильно. Иначе, в дисе напиши там

2021-05-27 21:26 UTC, KIBORG04 commented on code/game/objects/items/weapons/defibrillator.dm
> +	return
```suggestion
	..()
```

2021-05-27 21:28 UTC, KIBORG04 commented on code/game/objects/items/weapons/defibrillator.dm
> +/obj/item/weapon/twohanded/shockpaddles/robot/try_revive(mob/living/carbon/human/H, mob/user)
Перемести это к другим переопределениям функций у дефибов боргов

2021-05-27 21:33 UTC, KIBORG04 commented on code/game/objects/items/weapons/defibrillator.dm
> +		IO.heart_fibrillate()
а еще это не должно работать всегда

https://github.com/KIBORG04/TauBORG/blob/ed52d884c7507fe6da10dbb1dddaac5b171e3f0d/code/modules/mob/living/carbon/human/human.dm#L2000-L2005

```dm
			if(health > config.health_threshold_dead)
				Heart.heart_fibrillate()
				to_chat(user, "<span class='notice'>You feel an irregular heartbeat coming form [src]'s body. It is in need of defibrillation you assume!</span>")
			else
				to_chat(user, "<span class='warning'>[src]'s body seems to be too weak, you do not feel a heart beat.</span>")

```

2021-05-28 15:03 UTC, Zickusable commented on code/modules/mob/living/silicon/robot/robot_items.dm
> +
```suggestion
```

2021-05-28 17:05 UTC, Zickusable commented
Как я понял, дексалин плюс более бесполезен с этой системой массажей... Печально

2021-06-09 17:19 UTC, KIBORG04 commented
убери

2021-06-09 17:19 UTC, KIBORG04 commented
@github-actions убери

2021-06-12 12:26 UTC, KIBORG04 commented
> tweak: Мед. борг реанимирует без массажа сердца

Измени это. Он скорее какой-то использую телепатиомагию делает массаж во время действия дефибов

2021-06-12 12:29 UTC, Sakuya-Izayoi commented
> > tweak: Мед. борг реанимирует без массажа сердца
> 
> Измени это. Он скорее какой-то использую телепатиомагию делает массаж во время действия дефибов

Он делает массаж сердца своим модулем.

2021-06-12 15:20 UTC, kalazus commented
Может было бы лучше дать возможность мед боргам взаимодействовать с людьми? Конечно искусственное дыхание делаемое боргом будет выглядеть смешно, но что есть то есть.

2021-06-12 15:27 UTC, Zickusable commented
> Может было бы лучше дать возможность мед боргам взаимодействовать с людьми? Конечно искусственное дыхание делаемое боргом будет выглядеть смешно, но что есть то есть.

У меня в планах добавить вентилятор легких, чтоб убирать дамаг от удушья, но сначала надо другие ПРы закончить

2021-06-16 17:14 UTC, merged