нерф гиперцина и замедления
TauCetiStation/TauCetiClassic pull request #7206
Opened 2021-05-23 23:15 UTC by AndroBetel

## Описание изменений
предметы в руках, скафандры и прочее теперь меньше замедляют.
гиперцин теперь токсичен примерно на уровне синаптизина.
## Почему и что этот ПР улучшит
боевка больше не будет зависеть полностью от гиперцина, бомжам без него будет легче быстрее веселее и интереснее играть.
## Авторство
я
## Чеинжлог
:cl:
- experiment: Гиперцин токсичен, а замедление всех вещей значительно снижено.

2021-05-23 23:15 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2021-05-23 23:46 UTC, Sakuya-Izayoi commented on code/modules/reagents/reagent_types/Chemistry-Medicine.dm
> +		M.adjustToxLoss(1)
Почему проб? Почему нельзя сделать просто стабильный токслосс в 0.7 за тик?

2021-05-23 23:46 UTC, AndroBetel commented on code/modules/reagents/reagent_types/Chemistry-Medicine.dm
> +		M.adjustToxLoss(1)
я не знаю, так сделано у синаптизина

2021-05-24 00:06 UTC, Zmey25 commented
Сделай кофейку легкую версию ускорения как от гиперцина плиз

2021-05-24 00:08 UTC, AndroBetel commented
гиперцин просто снимает все замедление, но я подумаю.

2021-05-24 07:25 UTC, ssbugman commented
То есть симптом на синтез гиперцина теперь будет даже смертельнее симптома 4 уровня?

2021-05-24 08:46 UTC, LudwigVonChesterfield commented on code/modules/clothing/clothing.dm
> +	slowdown = 1
ускорение в два с лишком раза больше чем то которое получают таяры в сравнении с хуманами

(относительно того что было раньше)

2021-05-24 08:47 UTC, LudwigVonChesterfield commented on code/modules/clothing/shoes/colour.dm
> +	slowdown = 3
А почему если прицепить самому наручники то замедление 7, но если защитспавнит педаль то замедление 3

2021-05-24 08:48 UTC, LudwigVonChesterfield commented on code/modules/clothing/shoes/miscellaneous.dm
> +	slowdown = SHOES_SLOWDOWN + 0.2
Клоуна они все равно не замедляют. Может не надо?

2021-05-24 08:48 UTC, LudwigVonChesterfield commented on code/modules/clothing/shoes/miscellaneous.dm
> +	slowdown = SHOES_SLOWDOWN + 0.2
много ли людей кстати носят обувку с тех пор как вот это появилось?

2021-05-24 08:48 UTC, AndroBetel commented on code/modules/clothing/shoes/colour.dm
> +	slowdown = 3
ой я пропустил

2021-05-24 08:50 UTC, AndroBetel commented on code/modules/clothing/shoes/miscellaneous.dm
> +	slowdown = SHOES_SLOWDOWN + 0.2
я ролеплею за топ тян скрелла на каблуках а больше не знаю

2021-05-24 08:50 UTC, LudwigVonChesterfield commented
Про симптом у вируса надо что-то тоже придумать вероятно, Бетель.

2021-05-24 08:51 UTC, AndroBetel commented
я придумаю

2021-05-24 08:52 UTC, AndroBetel commented
> Оксикодон и бикаридин тоже выпилим под таким же лозунгом?

выпиливай, брат!

2021-05-24 08:54 UTC, AndroBetel commented on code/modules/clothing/clothing.dm
> +	slowdown = 1
а давно у нас скорость измеряется в таярах?

2021-05-24 09:18 UTC, LudwigVonChesterfield commented on code/modules/clothing/clothing.dm
> +	slowdown = 1
ну просто контекстуализация. все знают что таяры быстрые, тут ты сделал двойную таяру, то есть в два раза быстрее чем быстрое.

2021-05-24 09:19 UTC, AndroBetel commented on code/modules/clothing/clothing.dm
> +	slowdown = 1
целью пра не было сделать двойную таяра из рига.

2021-05-24 09:31 UTC, AndroBetel commented
добавил адреналин нюке-трейторам, в вирус и бореру.

2021-05-24 09:36 UTC, EdlerN commented
Что-то мне не очень нравится срезание замедления в три раза. Ровно как и прямая токсичность гиперцина. В этом случае гиперцин не будет предоставлять достаточных преимуществ, чтобы оправдать такой эффект и как следствие - никто не будет им пользоваться. В общем - одна проблема меняется на другую. Что не очень хорошо. Не говоря уже о том что есть всякие нюансы уровня симптома от вируса и прочее.

Для начала стоило бы срезать замедление где-то процентов на 25-50 и посмотреть как с ним играться будет. Что до гиперцина - он мог бы просто постепенно терять свой ускоряющий эффект при постоянном использовании. Что было бы куда лучше.

2021-05-24 09:40 UTC, AndroBetel commented
мне в рнд канале объясняли, что гиперцином продолжат ширяться, просто будут туда намешивать антитоксин с трикодрацином, так что не уверен насчёт вот этого вот твоего утверждения.

переделаю всё в половину по запросу боланс департмента

2021-05-24 09:46 UTC, EdlerN commented
> мне в рнд канале объясняли, что гиперцином продолжат ширяться, просто будут туда намешивать антитоксин с трикодрацином, так что не уверен насчёт вот этого вот твоего утверждения.

Что тоже не совсем хорошо. А что если сделать какой-нибудь статус эффект типа толерантности гиперцину и сделать так чтобы он набегал от 0 до 100 минут за 7-10. При этом за столько же времени сбегал обратно. И реальный эффект от гиперцина был не всегда максимальный, а помноженный на  1 - Процент привыкания.

2021-05-24 09:49 UTC, LudwigVonChesterfield commented
Это нёрфит гиперцин для СБ, но и для всех остальных. Бетель хочет оставить его пользу для ксеноархеологов, шахтёров, и подобного сброда, но занёрфить гиперцин для боя.

Я бы предложил сделать чтобы есл у куклы накинута боль - гиперцин ставал бесполезным.

2021-05-24 09:51 UTC, EdlerN commented
Ну, то что я предлагаю просто изменит концепцию гиперцина. Вместо постоянного отключения замедления тебе придётся думать, когда именно им пользоваться, чтобы получить ускорение ровно когда тебе нужно.

2021-05-24 12:40 UTC, KIBORG04 commented on code/modules/reagents/reagent_types/Chemistry-Medicine.dm
> +		M.emote(pick("twitch","blink","shiver"))
```suggestion
		M.emote(pick("twitch","blink","shiver"))

```

2021-05-24 13:30 UTC, Sakuya-Izayoi commented on code/game/objects/items/weapons/autoinjectors.dm
> +	list_reagents = list("hyperzine" = 5, "tramadol" = 9, "dexalinp" = 1, "tricordrazine" = 10, "anti_toxin" = 10)
5 гиперцина метаболизируется 166 тиков, 10 атоксина метабоизируется 50 тиков. Получается, в стимпаке 116 тиков гиперцина, что эквивалентно в среднем 81 токс урона. И ты считаешь это нормой?

2021-05-24 13:32 UTC, Sakuya-Izayoi commented on code/modules/reagents/reagent_containers/hypospray.dm
> +	list_reagents = list("inaprovaline" = 5, "anti_toxin" = 13, "hyperzine" = 2)
привет 10 юнитов трика из ниоткуда. откуда?

2021-05-24 15:37 UTC, AndroBetel commented on code/modules/reagents/reagent_containers/hypospray.dm
> +	list_reagents = list("inaprovaline" = 5, "anti_toxin" = 13, "hyperzine" = 2)
right

2021-05-24 19:07 UTC, KIBORG04 commented
Я жду аппрува от едлерна, прежде чем ТМ жать. Кто-нибудь другой может его и не ждать..

2021-05-24 19:23 UTC, Sakuya-Izayoi commented on code/modules/reagents/reagent_containers/hypospray.dm
> +	list_reagents = list("inaprovaline" = 5, "anti_toxin" = 13, "hyperzine" = 2)
если райт, то может стоит явно прописать что ты хочешь чтобы там было 10 трика, а не он варился при создании стимпака? потому что это выглядит как ошибка.

2021-05-24 20:02 UTC, AndroBetel commented
обозначьте мне цель и я попробую сделоть

2021-05-25 07:09 UTC, ssbugman commented
Проблема нерфа гиперцина токсинами в том что это сделает его в принципе бесполезным. Кто не верит может посмотреть на синаптизин и мутаген. Будет просто третий легко доступный яд в коллекцию ролям.

2021-05-27 17:04 UTC, EdlerN commented
> обозначьте мне цель и я попробую сделоть

Я уже говорил, но, если чуть подробнее - мне не нравится добавление гиперцину урона без передоза. От слова совсем. Придумай какой-нибудь другой метод, как сделать так, чтобы люди не использовали его постоянно. 

Как вариант - я уже предложил идею с тем, чтобы эффективность гиперцина падала с течением времени. И, чтобы вернуться к норме - нужно дать организму какое-то время на отдых. Но если у тебя есть какие-то другие идеи - можешь попробовать их.

2021-05-27 17:31 UTC, Sakuya-Izayoi commented
> > обозначьте мне цель и я попробую сделоть
> 
> Я уже говорил, но, если чуть подробнее - мне не нравится добавление гиперцину урона без передоза. От слова совсем. Придумай какой-нибудь другой метод, как сделать так, чтобы люди не использовали его постоянно.
> 
> Как вариант - я уже предложил идею с тем, чтобы эффективность гиперцина падала с течением времени. И, чтобы вернуться к норме - нужно дать организму какое-то время на отдых. Но если у тебя есть какие-то другие идеи - можешь попробовать их.

для бетеля: у нас есть механ стакабл статус эффектов. можно в дайджесте гиперцина накидывать стаки на этот самый статус эффект, а в том месте где снимается дебафф на скорость в зависимости от количества стаков уменьшать, собственно дебафф. чем больше стаков, тем больше уменьшение дебаффа (вплоть до отсутствия уменьшения). будет круто если ты сделаешь там какую-нибудь нелинейную зависимость.

2021-06-01 15:21 UTC, LudwigVonChesterfield requested changes
Ждём изменений по способу нёрфа гиперцина. (делаю реквест ченжей в основном как формальность чтобы проще ревувать 44 ПР-а было и Киборг не смотрел в ПР-ы которые уже кем-то ревуваются и не тратил калории)

2021-06-13 09:50 UTC, TauKitty commented
This pull request has been mentioned on **Tau Ceti Station Forum**. There might be relevant details there:

https://forum.taucetistation.org/t/pereosmyslenie-zamedleniya-u-lizardov/26089/1

2021-06-30 01:07 UTC, closed without merging

2021-08-07 13:39 UTC, TauKitty commented
This pull request has been mentioned on **Tau Ceti Station Forum**. There might be relevant details there:

https://forum.taucetistation.org/t/nerf-giperczina/27380/9