Особые подвиды тритора: координатор и двойной агент
TauCetiStation/TauCetiClassic pull request #7207
Opened 2021-05-24 07:16 UTC by ssbugman

## Описание изменений
Добавлена небольшая вероятность появления среди триторов особых ролей.
Координатор - обладает большим запасом телекристаллов и получает задачу оказать поддержку остальным агентам на станции и убедиться что те справятся со своими заданиями.
Двойной агент - тритор, на самом деле лояльный НТ, его задача сорвать планы Синдиката или просто перебить его агентов. Но он работает тайно и не встретит понимания у СБ, которая не станет верить на слово предателю.

## Почему и что этот ПР улучшит
Разнообразие взаимодействия и дополнительная паранойя между триторами.

## Авторство
Я

## Чеинжлог
Добавлены две редкие разновидности тритора

2021-05-24 07:16 UTC, TauKitty commented
###### Changelog status: :radio_button: No changelog

2021-05-24 07:30 UTC, Akellazp commented
координатор тупо тритор с большим запасом тк а двойному агенту будут верить наслово

2021-05-24 07:34 UTC, ssbugman commented
> координатор тупо тритор с большим запасом тк а двойному агенту будут верить наслово

Ты даже в цели не заглядывал прежде чем написать "тупо тритор", да?
Верить на слово - привет устранению целей просто выдавая себя за двойного агента а цель за тритора.

2021-05-24 07:41 UTC, Akellazp commented
у меня опыта игры побольше твоего и я знаю о чем говорю

2021-05-24 07:43 UTC, ssbugman commented
> у меня опыта игры побольше твоего и я знаю о чем говорю

Ты даже не прочитал цели прежде чем делать абсурдные заявления, что мягко говоря обесценивает твой опыт.

2021-05-24 07:44 UTC, Akellazp commented
я знаю как играют игроки, нахера мне смотреть твои цели
координатор будет тупо закупать еще больше оружия чем тритор
двойной агент будет приходить в бриг говорить "всем привет у меня вот аплинк но я агент нт дайте лояльность и пойдем убивать триторов"

2021-05-24 07:48 UTC, ssbugman commented
> я знаю как играют игроки, нахера мне смотреть твои цели
> координатор будет тупо закупать еще больше оружия чем тритор
> двойной агент будет приходить в бриг говорить "всем привет у меня вот аплинк но я агент нт дайте лояльность и пойдем убивать триторов"

Даже не знаю что сказать на фоне твоей явной неадекватности. Ты даже не прочитал цель но пишешь бред про "закупать еще больше оружия", не рассмотрев предварительно вопрос для чего оно ему.
Ничего что имплант лояльности приведет к провалу его задач так как он их лишится?
И ничего что просить имплант лояльности это ну очень жесткий выход из роли и откровенное нарушение правил?

2021-05-24 10:57 UTC, Zmey25 commented
> у меня опыта игры побольше твоего и я знаю о чем говорю
Вижу у вас **опыта игры побольше**, так вот я двойной агент, дайте мне доступ в оружейку, карту и трусы кэпа и вообще вы тритор, убивайтесь.

2021-05-24 11:03 UTC, Zmey25 commented
Идеи хорошие, разнообразие всегда плюс, но:
- Если у координатора нет других заданий, зачем ему вообще тк? Интересней будет ему искать способы помочь агентам без помощи синдиката. Конечно, для тех, у кого **опыта игры побольше** будет проще накупить оружия и закликать вражину, поэтому тк им лучше не давать, пусть ищут альтернативные способы помощи.
- Не знаю, видит ли двойной агент в своих целях конкретно кто предатель, но скорее всего **не** должен видеть. Опять же, чтобы подключал фантазию по поиску агентов без конкретных знаний.

2021-05-24 11:48 UTC, Pimap3 commented
Координатору думаю стоит дать особые устройства коммуникации и  маячки которые показывают твое местоположение.
Двойному агенту можно еще один обжектив прописать, который говорит, что ему никак нельзя позволить раскрыть себя охране

2021-05-24 12:18 UTC, BesumniiChebureck commented
Ты осознаешь, что пытаешься создать две РП роли на Тау Сети?

2021-05-24 12:24 UTC, LudwigVonChesterfield commented
> Двойному агенту можно еще один обжектив прописать, который говорит, что ему никак нельзя позволить раскрыть себя охране

и как ты это проверять будешь?

2021-05-24 12:25 UTC, cool20141 commented
Чел очень крутую вещь сделал, а на него объявили кибербуллинг :man_facepalming: 
 
> а двойному агенту будут верить наслово

Ну и что, поверят, а это будет самый обычный агент, который наебал сбух на фуллаксес ("Я двойной агент, дайте фа, чтоб с тритарами бороться!") или на что покруче.



> РП роли

А какая проблема? На тау есть конченый рп-малф, потому что все, даже зная, что он 100 раз пидарас, будут играть дурачка, притворяться, что все норм, пока их не зафоронят

2021-05-24 12:31 UTC, BesumniiChebureck commented
> Чел очень крутую вещь сделал, а на него объявили кибербуллинг 🤦‍♂️

Просто нужно объяснить, что полностью РП роли в сосаке это полнейшее дерьмо на любом сервере.

2021-05-24 12:36 UTC, KIBORG04 commented
> ## Чеинжлог
> add: Добавлены две редкие разновидности тритора и их цели
> add: Добавлена переменная подвида роли в mind


Оформи нормально чейджлог

2021-05-24 12:36 UTC, KIBORG04 commented on code/game/gamemodes/traitor/traitor.dm
> +	var/supplier = 0 //check if spawned that already
Скажи, а ты это откуда-то копировал или сам весь код придумал?

2021-05-24 12:37 UTC, KIBORG04 commented on code/game/gamemodes/traitor/traitor.dm
> +				to_chat(world, "<B>subtraitors++</B>")
Странно, что оно вообще тут, если вылазят ошибки компиляции

2021-05-24 12:42 UTC, cool20141 commented
> Просто нужно объяснить, что полностью РП роли в сосаке это полнейшее дерьмо на любом сервере.

Ты сказал?

2021-05-24 12:43 UTC, BesumniiChebureck commented
> Ты сказал?

Да

2021-05-24 12:47 UTC, cool20141 commented
> Да

Ну так твое мнение нахуй никому не всралось, и то, что ты там что-то считаешь и говоришь, ни на что не влияет

2021-05-24 13:11 UTC, ssbugman commented
> Оформи нормально чейджлог

Нужно уточнение что в нем сейчас не нормально я использовал теги из руководства.
Ни откуда не копировал.
Дебаг текст ща уберу случайно зацепил при переносе в гит.

2021-05-24 13:11 UTC, LudwigVonChesterfield commented
в нём не хватает

:cl: ТВОЙ СИКЕЙ

2021-05-24 13:54 UTC, Motzord commented
Лучше бы добавили нюк опс оператора, чтобы сидел и в наушник рассказывал смешные вещи нюкерам, а еще через войсченжер и агент кард раздавал от лица хоса смешные приказы по рашу клоунской

2021-05-24 15:24 UTC, KIBORG04 requested changes
Тебе очень повезло, что не за горами мой ПР о рефакторе всей геймодов. По этой причине я могу некоторые места простить и сделать у себя как нужно.

Это не конец ревью, попредлагал исправить все увидел краем глаза.

2021-05-24 15:24 UTC, KIBORG04 commented on code/game/gamemodes/objective.dm
> +		return OBJECTIVE_LOSS
```suggestion
/datum/objective/syndisupport/check_completion()
	if(SSticker.mode.traitorswon > max((SSticker.mode.traitors.len-1)/2,1))
		return OBJECTIVE_WIN
	return OBJECTIVE_LOSS
```

2021-05-24 15:24 UTC, KIBORG04 commented on code/game/gamemodes/objective.dm
> +		return OBJECTIVE_LOSS
```suggestion
/datum/objective/doubleagent/check_completion()
	if(SSticker.mode.traitorswon < max((SSticker.mode.traitors.len-1)/4,1))
		return OBJECTIVE_WIN
	return OBJECTIVE_LOSS
```

2021-05-24 15:24 UTC, KIBORG04 commented on code/game/gamemodes/traitor/traitor.dm
> +	var/traitorswon = 0 //so that seen from objectives
Замени ВСЕ места где у переменной 0/1 на FALSE/TRUE. Тип, не пиши булевые переменные юзая цифры

2021-05-24 15:24 UTC, KIBORG04 commented on code/game/gamemodes/traitor/traitor.dm
> +				double = 1
Я уверен, что это место можно оформить красивее. Да и почему шанс на двойного агента меньше, чем шанс на  помощника?

2021-05-24 15:24 UTC, KIBORG04 commented on code/game/gamemodes/traitor/traitor.dm
> +			traitor.sub_role = "Syndi supplier"
Сделай дефайны для всех возможных значений `sub_role`

2021-05-24 15:24 UTC, KIBORG04 commented on code/game/gamemodes/traitor/traitor.dm
> +		if(traitor.sub_role == "Syndi supplier")
Сделай тут свитч, а еще лучше вынеси в отдельный прок

2021-05-24 15:24 UTC, KIBORG04 commented on code/game/gamemodes/traitor/traitor.dm
> +		if(traitor.sub_role == "Double agent")
Попробуй заменит похожие места с конструкции вида:
```
if
	code
else
	if
		code
```
на конструкцию
```
if
	code
else if
	code
```

2021-05-24 15:24 UTC, KIBORG04 commented on code/game/gamemodes/traitor/traitor.dm
> +			if(traitor.objectives && traitor.objectives.len)//If the traitor had no objectives, don't need to process this.
```suggestion
			if(traitor.objectives.len)//If the traitor had no objectives, don't need to process this.
```
Когда этот лист вообще может отсутствовать?

2021-05-24 15:24 UTC, KIBORG04 commented on code/game/gamemodes/traitor/traitor.dm
> +				special_role_text = "antagonist"
Наверное, здесь будет уместен тернарный оператор

2021-05-24 15:24 UTC, KIBORG04 commented on code/datums/mind.dm
>  	var/special_role
Насколько я помню, `special_role` сейчас и подразумевает под собой механ от `sub_role`. Поэтому, попробуй имплементировать все это туда.

2021-05-24 15:38 UTC, ssbugman commented on code/datums/mind.dm
>  	var/special_role
Не получится у Special role много завязок в других частях билда, потому и сделал другую переменную что старая привязана к куче проверок на принадлежность ее значения к списку возможных, которые придется искать и править..

2021-05-24 16:13 UTC, Zickusable commented
Может что-нибудь для грин-текст задротов? Добавлять цельки, когда все выполнены. Давать тк по мере выполнения целек, а не сразу 20. Цельки чтоб выпадали на те вещи, владельцы которых присутствуют на станции. Вроде кражи гипоспрея, только если СМО есть на станции.
Почему нет до сих пор цельки на унижение? Повесить голого [HOS.name] перед мостиком. Скормить бургер из мяса [clown.name] живому [captain.name].

2021-05-24 17:22 UTC, Ro2tCrab commented
Добавьте уже тогда братьев по крови из ТГ без аплинка, но с легальной метадружбой.

2021-05-25 06:37 UTC, ssbugman commented on code/game/gamemodes/traitor/traitor.dm
> +	var/traitorswon = 0 //so that seen from objectives
это не булевая переменная

2021-05-25 07:07 UTC, KIBORG04 commented on code/game/gamemodes/traitor/traitor.dm
> +	var/traitorswon = 0 //so that seen from objectives
Она используется как булевая же. Ну не суть, в других местах 0/1 и это нужно заменить на тру фолсы

2021-05-25 07:16 UTC, ssbugman commented on code/game/gamemodes/traitor/traitor.dm
> +	var/traitorswon = 0 //so that seen from objectives
Нет, она используется для подсчета числа успешных предателей в целях.
В других местах думаю как переделать, но получается либо ровно по вероятностям либо красиво, объединить пока не выходит.

2021-05-25 08:36 UTC, ssbugman commented on code/game/gamemodes/traitor/traitor.dm
> +				special_role_text = "antagonist"
вообще с учетом условия всей ветки там и не может быть null, так что совсем не нужно проверки

2021-05-25 10:30 UTC, ssbugman commented
Обновил ПР, убрал ненужное, добавил зависимость вероятности спавна от числа триторов и минимальный порог - не менее 3 для шанса спавна одного спецтритора, не менее 4 для возможности спавна обоих.

2021-05-25 12:22 UTC, Sakuya-Izayoi commented
Если двойной агент играет за НТ, то будет ли его гринтекст снимать очки со счета станции? Речь идёт про пункт Antagonists Successful

2021-05-26 19:38 UTC, ssbugman reviewed
Исправлено

2021-05-27 21:15 UTC, KIBORG04 commented on code/game/gamemodes/traitor/traitor.dm
> +		switch(rand(1,80+max(0,(traitors.len/3.0-1)*50))) //can spawn both only if 4 or more traitors
```suggestion
		switch(rand(1,80 + max(0, (traitors.len / 3.0 - 1) * 50))) //can spawn both only if 4 or more traitors
```

2021-05-27 21:16 UTC, KIBORG04 commented on code/game/gamemodes/traitor/traitor.dm
> +	if(prob((traitors.len/2.0-1)*15)) //no sub-traitors if 2 or less traitors
С код конвеншеном не пиши так все слитно

2021-05-27 21:17 UTC, KIBORG04 commented on code/game/gamemodes/objective.dm
> +	if(SSticker.mode.traitorswon > max((SSticker.mode.traitors.len-1)/2,1))
тут тоже раздели цифры и знаки

2021-05-27 21:18 UTC, KIBORG04 commented on code/game/gamemodes/traitor/traitor.dm
> +		var/spawnertypes = 3	//yep magic number, it best what can be here
Что-то прям совсем непонятное тут происходит

2021-05-28 07:47 UTC, ssbugman commented on code/game/gamemodes/traitor/traitor.dm
> +		var/spawnertypes = 3	//yep magic number, it best what can be here
с которой из?

2021-05-28 08:05 UTC, KIBORG04 commented on code/game/gamemodes/traitor/traitor.dm
> +		var/spawnertypes = 3	//yep magic number, it best what can be here
Я впринципе про эту переменную

2021-05-28 08:08 UTC, ssbugman commented on code/game/gamemodes/traitor/traitor.dm
> +		var/spawnertypes = 3	//yep magic number, it best what can be here
это локальная переменная определяющая кого генерировать, с ее помощью убирается повторение самого кода генерации для случая когда спавнятся оба подтритора.

2021-05-28 08:18 UTC, KIBORG04 commented on code/game/gamemodes/traitor/traitor.dm
> +		var/spawnertypes = 3	//yep magic number, it best what can be here
Я уверен, что это можно сделать читаемее

2021-05-28 08:56 UTC, ssbugman commented on code/game/gamemodes/traitor/traitor.dm
> +		var/spawnertypes = 3	//yep magic number, it best what can be here
Куда еще читаемее то? Переменная объявляется и чуть ниже меняется/проверяется.

2021-05-28 09:52 UTC, KIBORG04 commented on code/game/gamemodes/traitor/traitor.dm
> +			var/traitorwin = 1
тру/фолс для этого сделай

2021-05-28 09:54 UTC, KIBORG04 commented on code/game/gamemodes/traitor/traitor.dm
> +		switch(rand(1,80 + max(0, (traitors.len / 3.0 - 1) * 50))) //can spawn both only if 4 or more traitors
```suggestion
		switch(rand(1, 80 + max(0, (traitors.len / 3.0 - 1) * 50))) //can spawn both only if 4 or more traitors
```

2021-05-28 10:00 UTC, ssbugman commented
сделал

2021-05-30 21:08 UTC, KIBORG04 commented
Предлагаю код никуда не терять и подождать мержа рефакторов режимов

2021-06-23 12:20 UTC, KIBORG04 commented
Ну все, перекодивай, щас будет код вообще классным

2021-06-28 16:20 UTC, KIBORG04 commented
<img src="https://user-images.githubusercontent.com/26389417/123670037-70199580-d845-11eb-8ba7-536b47ea1585.png" alt="drawing" width="200"/>

2021-07-09 02:54 UTC, Motzord commented
Хатико ждал и мы подождем

2021-07-23 08:07 UTC, closed without merging