Пополнение всех реагентов вместо одного выбранного в гипоспрее борга
TauCetiStation/TauCetiClassic pull request #7216
Opened 2021-05-27 09:27 UTC by Zickusable

## Описание изменений
Добавил цикл, чтобы гипоспрей перезаряжал все реагенты в гипоспрее, которые есть, а не только выбранный для использования
## Почему и что этот ПР улучшит
Боргу не нужно будет каждые 30 секунд переключать реагент в гипоспрее, чтобы полностью восстановить их.
## Авторство

## Чеинжлог
:cl:
- tweak: В гипоспрее борга перезаряжаются все недостающие реагенты вместо одного, выбранного для использования.

2021-05-27 09:27 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2021-05-27 12:04 UTC, Sakuya-Izayoi commented on code/modules/reagents/reagent_containers/borghydro.dm
> +						RG.add_reagent(reagent_ids[reagent_to_recharge], 5)		//And fill hypo with reagent.
то есть скорость восстановления реагентов возросла в сколько раз? в столько, сколько у борга есть разновидностей реагентов. слишком сильно.

2021-05-27 14:52 UTC, Sakuya-Izayoi commented on code/modules/reagents/reagent_containers/borghydro.dm
> +						RG.add_reagent(reagent_ids[reagent_to_recharge], 5)		//And fill hypo with reagent.
а можно просто было сделать RG.add_reagent(reagent_ids[reagent_to_recharge], 5 / len(reagent_ids))

2021-05-27 14:55 UTC, Zickusable commented on code/modules/reagents/reagent_containers/borghydro.dm
> +						RG.add_reagent(reagent_ids[reagent_to_recharge], 5)		//And fill hypo with reagent.
Чтобы он капал почти по единичке на каждый?

2021-05-27 15:15 UTC, Sakuya-Izayoi commented on code/modules/reagents/reagent_containers/borghydro.dm
> +						RG.add_reagent(reagent_ids[reagent_to_recharge], 5)		//And fill hypo with reagent.
ну чтобы равномерно добавлялось. типа, сейчас в билде он регенит 5 юнитов за единицу времени, но одного химиката. эти пять юнитов можно разделить на разные химикаты, чтобы по прежнему регенилось 5 за единицу времени, но разных химикатов.

2021-05-27 15:24 UTC, Zickusable commented on code/modules/reagents/reagent_containers/borghydro.dm
> +						RG.add_reagent(reagent_ids[reagent_to_recharge], 5)		//And fill hypo with reagent.
Когда будет один реагент неполон он все равно будет восстанавливать единичку, а как сделать идеально я даже думать не хочу, да и зачем? Чтобы было 16,66660 реагента там, 13,3333 реагента тут? Инжектит по 5, так что будем придерживаться красоты.

2021-05-27 15:40 UTC, Zickusable commented on code/modules/reagents/reagent_containers/borghydro.dm
> +						RG.add_reagent(reagent_ids[reagent_to_recharge], 5)		//And fill hypo with reagent.
Внезапно придумал как, но все равно не буду

2021-05-27 21:21 UTC, KIBORG04 commented on code/modules/reagents/reagent_containers/borghydro.dm
> +				var/datum/reagent/Reag = locate() in charge_reagent.reagent_list
А зачем это надо? Проверяй тогда длинну `harge_reagent.reagent_list`

2021-05-27 21:21 UTC, KIBORG04 commented on code/modules/reagents/reagent_containers/borghydro.dm
> +							reagent_to_recharge = 1
```suggestion
					reagent_to_recharge++
					if(reagent_to_recharge > reagent_list.len)
						reagent_to_recharge = 1
```

2021-05-27 21:22 UTC, KIBORG04 commented on code/modules/reagents/reagent_containers/borghydro.dm
> +			for(var/datum/reagents/charge_reagent in reagent_list)
Добавь ранних возвратов по всему дифу

2021-05-27 21:24 UTC, KIBORG04 commented on code/modules/reagents/reagent_containers/borghydro.dm
> +						reagent_to_recharge++
зачем это делать переменной у класса?

2021-05-27 21:25 UTC, KIBORG04 commented on code/modules/reagents/reagent_containers/borghydro.dm
> +						RG.add_reagent(reagent_ids[reagent_to_recharge], 5)		//And fill hypo with reagent.
Вариант гетапа определённо лучше чем сейчас

2021-05-28 17:56 UTC, Zickusable commented on code/modules/reagents/reagent_containers/borghydro.dm
> +						RG.add_reagent(reagent_ids[reagent_to_recharge], 5)		//And fill hypo with reagent.
Хорошо, сделаю поочередное заполнение. Не кратные 5 значения отвратительны

2021-05-28 18:07 UTC, Zickusable commented on code/modules/reagents/reagent_containers/borghydro.dm
> +						reagent_to_recharge++
Чтобы не сбрасывалась до единички? Можно иначе? Я чего-то не понимаю?

2021-05-28 19:30 UTC, Zickusable commented on code/modules/reagents/reagent_containers/borghydro.dm
> +				var/datum/reagent/Reag = locate() in charge_reagent.reagent_list
Иначе не получается, да и не понель

2021-05-29 23:08 UTC, KIBORG04 commented on code/modules/reagents/reagent_containers/borghydro.dm
> +	if(!isrobot(src.loc))
```suggestion
	if(!isrobot(loc))
```

2021-05-29 23:08 UTC, KIBORG04 commented on code/modules/reagents/reagent_containers/borghydro.dm
> +		//	break
```suggestion
```

2021-05-29 23:08 UTC, KIBORG04 commented on code/modules/reagents/reagent_containers/borghydro.dm
> +						reagent_to_recharge++
Ну так вынеси её вне цикла

2021-05-31 15:16 UTC, Zickusable commented on code/modules/reagents/reagent_containers/borghydro.dm
> +						reagent_to_recharge++
Ну а так не работает, как должно

2021-06-01 15:22 UTC, LudwigVonChesterfield commented on code/modules/reagents/reagent_containers/borghydro.dm
> +	var/reagent_to_recharge = 1
этой переменной явно не место в классе, сделай там цикл вайл, в котором проверяешь стоит ли борг всё ещё на перезарядке.

2021-06-01 19:54 UTC, Zickusable commented on code/modules/reagents/reagent_containers/borghydro.dm
> +	var/reagent_to_recharge = 1
Это восполнение вне зарядника для борга. Типо, пока модуль в одном из слотов, он перезаряжается

2021-06-03 21:11 UTC, KIBORG04 commented on code/modules/reagents/reagent_containers/borghydro.dm
> +	var/reagent_to_recharge = 1
![image](https://user-images.githubusercontent.com/26389417/120712450-5052b400-c4c9-11eb-89d8-2b1d19e20024.png)

Понимаешь? Она юзается ТОЛЬКО внутри цикла. Это значит, что её достаточно обьявить вне его.

2021-06-03 21:11 UTC, KIBORG04 commented on code/modules/reagents/reagent_containers/borghydro.dm
> +	var/mob/living/silicon/robot/R = src.loc
```suggestion
	var/mob/living/silicon/robot/R = loc
```

2021-06-03 21:13 UTC, KIBORG04 commented on code/modules/reagents/reagent_containers/borghydro.dm
> +			break
а зачем здесь брик и этот код? Он же типо вызывается в любом случае
```
reagent_to_recharge++
if(reagent_to_recharge &gt; reagent_list.len)
reagent_to_recharge = 1
```

2021-06-04 16:43 UTC, KIBORG04 requested changes
См. комментарии выше ☝️

2021-06-04 17:09 UTC, Sakuya-Izayoi commented on code/modules/reagents/reagent_containers/borghydro.dm
> +	var/reagent_to_recharge = 1
я так понимаю тут задумка в том что эта переменная сохраняется между зарядками, то есть заходя несколько раз в зарядник ты будешь регенить реагенты равномерно, а не некоторые чаще, некоторые реже.

2021-06-04 19:38 UTC, LudwigVonChesterfield commented on code/modules/reagents/reagent_containers/borghydro.dm
> +	var/reagent_to_recharge = 1
... если выбирать случайный реагент из списка перед перезарядкой то это тоже не будет проблемой

2021-06-05 13:33 UTC, Zickusable commented on code/modules/reagents/reagent_containers/borghydro.dm
> +			break
Брик нужен для кд: если реагента меньше максимума, то он пополняется, цикл рвется. Если же реагент полон, то цикл не рвется,а проверяется следующий реагент.
Если reagent_to_recharge засунуть вне цикла, то равномерная зарядка не работает, будет до максимума заряжаться сначала первый, затем до максимума второй и тд.

2021-06-05 14:55 UTC, KIBORG04 commented on code/modules/reagents/reagent_containers/borghydro.dm
> +			break
Посмотри на этот цикл внимательно. Если условие в `if` выполняется, то ты делаешь `reagent_to_recharge++`, а потом цикл останавливается.. Если условие в `if` не выполняется, то ты делаешь `reagent_to_recharge++` и переходишь к следующей итерации.

Да даже посмотри как я предложения построил и пойми в чем суть

2021-06-05 15:23 UTC, Zickusable commented on code/modules/reagents/reagent_containers/borghydro.dm
> +			break
Суть в копипасте? Можно запихать в начало цикла.

2021-06-05 19:03 UTC, KIBORG04 commented on code/modules/reagents/reagent_containers/borghydro.dm
> +			break
Ну так сделай как-то

2021-06-06 10:15 UTC, Zickusable commented on code/modules/reagents/reagent_containers/borghydro.dm
> +	var/reagent_to_recharge = 1
Вот докопались до переменной гипоспрея борга, которая наравне с `charge_tick` нужна там, где она есть

2021-06-13 16:57 UTC, Zickusable commented
> Данный ПР автоматически отмечен как застоявшийся по причине длительного отсутствия обновлений. Он будет закрыт через 7 дней, если никакой активности не будет проявлено. Если вы считаете, что ПР еще актуален, или что я (злобный робот) пристаю к вам зря - просто напишите любой комментарий. Спасибо за ваш вклад.

Отпути

2021-06-14 13:08 UTC, merged