Ген невидимости
TauCetiStation/TauCetiClassic pull request #7219
Opened 2021-05-27 15:50 UTC by IlinMihail

## Описание изменений
Добавляет ген невидимости
## Почему и что этот ПР улучшит
Ещё одна способность для генетика
## Авторство

## Чеинжлог

2021-05-27 15:50 UTC, TauKitty commented
###### Changelog status: :radio_button: No changelog

2021-05-27 17:14 UTC, LudwigVonChesterfield commented on code/game/dna/genes/powers.dm
> +	activation_messages=list("You feel light passes through your body.")
```suggestion
	activation_messages=list("You feel light pass through your body.")
```

2021-05-27 17:15 UTC, LudwigVonChesterfield commented on code/game/dna/genes/powers.dm
> +	activation_messages=list("You feel light passes through your body.")
```suggestion
	activation_messages=list("You feel how light passes through your body.")
```

2021-05-27 17:15 UTC, LudwigVonChesterfield commented on code/game/dna/genes/powers.dm
> +	activation_messages=list("You feel light passes through your body.")
Любой из вариантов норм, но как сейчас не норм

2021-05-27 17:15 UTC, LudwigVonChesterfield commented on code/game/dna/genes/powers.dm
> +	..(M)
если аргументы функции не отличаются, то их не надо заново передавать в родителя
```suggestion
	..()
```

2021-05-27 17:15 UTC, LudwigVonChesterfield commented on code/game/dna/genes/powers.dm
> +	block=INVISBLOCK
```suggestion
	block = INVISBLOCK
```

2021-05-27 17:16 UTC, LudwigVonChesterfield commented on code/modules/mob/living/carbon/human/human.dm
> +		remove_overlay(27)
Используй дефайн чтобы всем понятно было что ты убираешь оверлей тела.

2021-05-27 17:16 UTC, LudwigVonChesterfield commented on code/modules/mob/living/carbon/human/human.dm
> +		src.verbs -= /mob/living/carbon/human/proc/invis
```suggestion
		verbs -= /mob/living/carbon/human/proc/invis
```

2021-05-27 17:16 UTC, LudwigVonChesterfield commented on code/modules/mob/living/carbon/human/human.dm
> +	if(stat!= CONSCIOUS)
```suggestion
	if(stat != CONSCIOUS)
```

2021-05-27 17:17 UTC, LudwigVonChesterfield commented on code/modules/mob/living/carbon/human/human.dm
> +	if(stat!= CONSCIOUS)
А это что, если ты потеряешь сознание - сила сама по себе не пропадаёт, надо именно прожать?

2021-05-27 17:17 UTC, LudwigVonChesterfield commented on code/modules/mob/living/carbon/human/human.dm
> +/mob/living/carbon/human/proc/invis()
```suggestion
/mob/living/carbon/human/proc/toggle_invis_power()
```

2021-05-27 17:17 UTC, LudwigVonChesterfield commented on code/modules/mob/living/carbon/human/human.dm
> +	if(inv_state==TRUE)
```suggestion
	if(inv_state)
```

2021-05-27 17:17 UTC, LudwigVonChesterfield commented on code/modules/mob/living/carbon/human/human.dm
> +		inv_state=FALSE
```suggestion
		inv_state = FALSE
```

2021-05-27 17:18 UTC, LudwigVonChesterfield commented on code/modules/mob/living/carbon/human/human.dm
> +	inv_state = !inv_state
Вот это можно вынести после проверки на stat == CONSCIOUS

2021-05-27 17:19 UTC, Sakuya-Izayoi commented on code/modules/mob/living/carbon/human/human.dm
> +		apply_overlay(27)
нужен дефайн

2021-05-27 17:19 UTC, Sakuya-Izayoi commented on code/modules/mob/living/carbon/human/human.dm
> +	if(inv_state==TRUE)
Нужны пробелы вокруг знаков равенства

2021-05-27 17:19 UTC, Sakuya-Izayoi commented on code/game/dna/genes/powers.dm
> +	activation_prob=30
Здесь тоже пробелы

2021-05-27 17:20 UTC, LudwigVonChesterfield commented on code/modules/mob/living/carbon/human/human.dm
> +	if(inv_state==TRUE)
присмотрись к проверке

2021-05-27 17:21 UTC, LudwigVonChesterfield commented on code/game/dna/genes/powers.dm
> +	activation_prob=30
я сначала сделал такой же комментарий, но потом увидел что там весь файл такой :shrug:

2021-05-27 17:21 UTC, IlinMihail commented on code/modules/mob/living/carbon/human/human.dm
> +		remove_overlay(27)
Я нубас, имеется ввиду #DEFINE BODY_OVERLAY 27?

2021-05-27 17:21 UTC, LudwigVonChesterfield commented on code/modules/mob/living/carbon/human/human.dm
> +		remove_overlay(27)
я думаю что тебе не нужно его заново определять, потому-что он где-то должен быть. но если его нет - то да, что-то такое.

2021-05-27 17:22 UTC, IlinMihail commented on code/modules/mob/living/carbon/human/human.dm
> +	if(stat!= CONSCIOUS)
Сама не пропадает

2021-05-27 17:23 UTC, IlinMihail commented on code/modules/mob/living/carbon/human/human.dm
> +		remove_overlay(27)
вроде нигде нет, задефайню заново

2021-05-27 17:25 UTC, LudwigVonChesterfield commented on code/modules/mob/living/carbon/human/human.dm
> +	if(stat!= CONSCIOUS)
но ты явно хочешь чтобы пропадала. не попробуешь это сделать? если нет - то вот тут это нужно убрать, а то как-то нелогично выходит.

2021-05-27 17:26 UTC, Sakuya-Izayoi commented on code/game/dna/genes/powers.dm
> +	activation_prob=30
если весь файл такой, это не значит что надо делать так же (по крайней мере меня так учили когда я делал первые пры)

2021-05-27 17:28 UTC, KIBORG04 commented
ченджлог бы

2021-05-27 17:41 UTC, IlinMihail commented
Вроде всё, есть ещё косяки?

2021-05-27 17:41 UTC, Sakuya-Izayoi commented
Чейнджлог оформлен неправильно, нужно написать что-то в таком формате:
🆑 Твой бйондкей
- add: что-то

2021-05-27 17:48 UTC, IlinMihail commented
Я так понимаю оно не компилится или что?

2021-05-27 17:55 UTC, Zickusable commented
Для ЛЛ можно было бы и побольше описания, чем два слова. Теперь ведь даже и не увидишь, кто телекинезом балуется. Сама кукла становится невидимой или можно хоть в риге быть прозрачным? Можно ли переключать невидимость?

2021-05-27 18:02 UTC, cool20141 commented
Полностью убивает смысл аналогичной способности генки

2021-05-27 18:23 UTC, IlinMihail commented
> Для ЛЛ можно было бы и побольше описания, чем два слова. Теперь ведь даже и не увидишь, кто телекинезом балуется. Сама кукла становится невидимой или можно хоть в риге быть прозрачным? Можно ли переключать невидимость?

Делается невидимым только тело куклы, эффекты от мутаций (типо ауры телекинеза и холодоустойчивости), урон на теле, одежда и прочее отрисовываются нормально

2021-05-27 20:31 UTC, Sakuya-Izayoi commented on code/modules/mob/living/carbon/human/human.dm
> +	inv_state = !inv_state
речь идёт о строке `inv_state = !inv_state`, set'ы это не программные инструкции и они не выполняются в обычном понимании

2021-05-27 20:31 UTC, Sakuya-Izayoi commented on code/modules/mob/living/carbon/human/human.dm
> +		visible_message("<span class='notice'>\The [src] suddenly appears out of thin air! </span>","<span class='notice'>You become visible again.</span>")
я не уверен, но разве не нужно ли регенерейтить иконки после ремув оверлея?

2021-05-27 20:31 UTC, Sakuya-Izayoi commented on code/modules/mob/living/carbon/human/human.dm
> +	var/inv_state = FALSE // variable used by invisibility
Возможно это может быть статусный эффект?

2021-05-27 20:44 UTC, IlinMihail commented on code/modules/mob/living/carbon/human/human.dm
> +		visible_message("<span class='notice'>\The [src] suddenly appears out of thin air! </span>","<span class='notice'>You become visible again.</span>")
Вообще там вроде была функция для регена одного оверлея но если кто нибудь захочет помимо оверлея тела также скрыть другие оверлие чтоб дополнительно не писать обновление для каждого можно реген иконок поставить

2021-05-27 20:45 UTC, IlinMihail commented on code/modules/mob/living/carbon/human/human.dm
> +	var/inv_state = FALSE // variable used by invisibility
Шо такое статусный эффект?

2021-05-27 20:50 UTC, Sakuya-Izayoi commented on code/modules/mob/living/carbon/human/human.dm
> +	var/inv_state = FALSE // variable used by invisibility
https://github.com/TauCetiStation/TauCetiClassic/blob/master/code/datums/status_effects/status_effect.dm

2021-05-27 20:51 UTC, IlinMihail commented on code/modules/mob/living/carbon/human/human.dm
> +	var/inv_state = FALSE // variable used by invisibility
Ну как бы можно но в гене логики на 4 строчки максимум так что скорее это усложнит код

2021-05-27 21:10 UTC, KIBORG04 commented
Было бы круто увидеть фото-видео демонстрацию нововведения

2021-05-27 21:48 UTC, IlinMihail commented
https://user-images.githubusercontent.com/57045293/119901256-589d7300-bf4e-11eb-82c1-bd7b583b1911.mp4

2021-05-27 21:49 UTC, IlinMihail commented
помимо оверлея тела можно и другие отключить для большей беспалевности но мне кажется это весьма несбалансировано

2021-05-28 11:55 UTC, IlinMihail commented
будет мерж или говно ПР?

2021-05-28 12:03 UTC, Zickusable commented
> будет мерж или говно ПР?

1. Чинишь и резолвишь сугесты
2. Вызываешь ревью
3. Переходишь к шагу 1
4. Получаешь сообщение о мерже твоей ветки.
6. ???
7. Profit

2021-05-28 12:08 UTC, IlinMihail commented on code/modules/mob/living/carbon/human/human.dm
> +	if(stat!= CONSCIOUS)
убрано

2021-05-28 12:11 UTC, IlinMihail commented on code/modules/mob/living/carbon/human/human.dm
> +	inv_state = !inv_state
перенесено

2021-05-28 12:12 UTC, IlinMihail commented on code/modules/mob/living/carbon/human/human.dm
> +		apply_overlay(27)
поставил

2021-05-28 12:12 UTC, IlinMihail commented on code/game/dna/genes/powers.dm
> +	activation_prob=30
вроде исправлено

2021-05-28 12:13 UTC, IlinMihail commented on code/modules/mob/living/carbon/human/human.dm
> +		visible_message("<span class='notice'>\The [src] suddenly appears out of thin air! </span>","<span class='notice'>You become visible again.</span>")
так стоит менять реген иконок на обновление отделбных оверлеев или нет?

2021-05-28 12:16 UTC, IlinMihail commented on code/modules/mob/living/carbon/human/human.dm
> +		visible_message("<span class='notice'>\The [src] suddenly appears out of thin air! </span>","<span class='notice'>You become visible again.</span>")
вообщем пока оставлю вариант с regenerate_icon

2021-05-28 12:18 UTC, IlinMihail commented
вроде всё за резолвил, прошу запустить проверки и сделать ревью

2021-05-28 12:19 UTC, KIBORG04 commented on code/modules/mob/living/carbon/human/human.dm
> +		inv_state=FALSE
Прочти код конвешншен и сам пойми что тут не так

2021-05-28 12:25 UTC, KIBORG04 requested changes

2021-05-28 12:25 UTC, KIBORG04 commented on code/modules/mob/living/carbon/human/human.dm
> +		remove_overlay(BODY_OVERLAY)
Мне не нравится копирование дефайна из другого файла и использование этой функции. Любое изменение оверлеев тела тебе все сломает. Возможно, стоит сделать надстройку над `update_body()` с проверкой на инвиз, чтобы не пересобирать тело и не ломать тебе код.

2021-05-28 12:31 UTC, IlinMihail commented on code/modules/mob/living/carbon/human/human.dm
> +		inv_state=FALSE
пробелов нет в inv_state = FALSE?

2021-05-28 12:54 UTC, KIBORG04 commented on code/modules/mob/living/carbon/human/human.dm
> +		inv_state=FALSE
Ну типа

2021-05-28 13:01 UTC, IlinMihail commented on code/modules/mob/living/carbon/human/human.dm
> +		remove_overlay(BODY_OVERLAY)
Исправлено

2021-05-28 13:03 UTC, IlinMihail commented on code/modules/mob/living/carbon/human/human.dm
> +		inv_state=FALSE
Исправлено

2021-05-28 13:07 UTC, IlinMihail commented on code/modules/mob/living/carbon/human/human.dm
> +		remove_overlay(BODY_OVERLAY)
можно резолвнуть?

2021-05-28 13:07 UTC, KIBORG04 requested changes

2021-05-28 13:07 UTC, KIBORG04 commented on code/modules/mob/living/carbon/human/update_icons.dm
> +	if(inv_state) //used by invisibility gene to disable body overlay (see human.dm)
Подумай как это сделать нормально, сейчас это выглядит очень плохо

2021-05-28 13:08 UTC, KIBORG04 commented on code/modules/mob/living/carbon/human/human.dm
> +		remove_overlay(BODY_OVERLAY)
нэйльзя

2021-05-28 13:08 UTC, IlinMihail commented on code/modules/mob/living/carbon/human/update_icons.dm
> +	if(inv_state) //used by invisibility gene to disable body overlay (see human.dm)
я нуб, чего от меня ожидать то можно

2021-05-28 13:09 UTC, IlinMihail commented on code/modules/mob/living/carbon/human/update_icons.dm
> +	if(inv_state) //used by invisibility gene to disable body overlay (see human.dm)
если скажешь как нормально сделать, перепишу

2021-05-28 14:41 UTC, KIBORG04 commented on code/modules/mob/living/carbon/human/human.dm
> +		inv_state = FALSE
Инвиз выключился, а тело осталось невидимым. Ретурн не нужен

2021-05-28 14:41 UTC, KIBORG04 commented on code/modules/mob/living/carbon/human/human.dm
> +		update_body()
Вынеси update_body() отсюда

2021-05-28 14:42 UTC, KIBORG04 commented on code/modules/mob/living/carbon/human/update_icons.dm
>  	var/list/standing = list()
```suggestion
	remove_overlay(BODY_LAYER)

	if(inv_state)
		return

	var/list/standing = list()
```
Стоит оставить комментарий про это действие

2021-05-28 14:45 UTC, IlinMihail commented on code/modules/mob/living/carbon/human/human.dm
> +		inv_state = FALSE
Смысла нет, похоже я ошибся при редактировании файла

2021-05-28 14:46 UTC, IlinMihail commented on code/modules/mob/living/carbon/human/update_icons.dm
> -
Что вернуть???

2021-05-28 14:46 UTC, KIBORG04 commented on code/modules/mob/living/carbon/human/update_icons.dm
> -
Два энтера

2021-05-28 14:55 UTC, IlinMihail commented on code/modules/mob/living/carbon/human/human.dm
> +		inv_state = FALSE
убрал ретурн

2021-05-28 14:58 UTC, IlinMihail commented on code/modules/mob/living/carbon/human/update_icons.dm
> -
вернул

2021-05-28 14:58 UTC, IlinMihail commented on code/modules/mob/living/carbon/human/human.dm
> +		inv_state = FALSE
или имеется ввиду всё ветвление?

2021-05-28 15:02 UTC, IlinMihail commented on code/modules/mob/living/carbon/human/human.dm
> +		remove_overlay(BODY_OVERLAY)
ладно

2021-05-30 17:43 UTC, Sakuya-Izayoi commented on code/game/dna/genes/powers.dm
> +	block=INVISBLOCK
```suggestion
	block = INVISBLOCK
```

2021-05-30 21:09 UTC, KIBORG04 commented on code/game/dna/genes/powers.dm
> +	block=INVISBLOCK
Это такой "стиль", впринципе так написано весь код ниже, а значит можно простить

2021-05-30 21:24 UTC, KIBORG04 commented on code/__DEFINES/genetics.dm
> +#define INVISIBILITY    9
```suggestion
#define INVISIBILITY	9
```

2021-05-30 21:24 UTC, KIBORG04 commented on code/modules/mob/living/carbon/human/update_icons.dm
> +
```suggestion
```

2021-05-30 22:28 UTC, KIBORG04 approved these changes
Надеюсь, что худы, облачко печатанья мб что-то еще является фичей
![image](https://user-images.githubusercontent.com/26389417/120122102-89301780-c1af-11eb-8d32-b9c6f130452f.png)

2021-05-30 22:34 UTC, Sakuya-Izayoi commented
главное чтобы лицо не было видно

2021-05-30 22:36 UTC, KIBORG04 commented
Представь летающую бороду, класс же

2021-05-30 22:36 UTC, KIBORG04 commented
> главное чтобы лицо не было видно

А так да, вроде экзамайн рабоает, возможно даже работат ПКМ по невидимой кукле

2021-05-30 22:38 UTC, LudwigVonChesterfield commented
интересно много ли вещей сломает если сделать невидимую куклу некликабельной

2021-05-31 08:50 UTC, IlinMihail commented
> Надеюсь, что худы, облачко печатанья мб что-то еще является фичей
> ![image](https://user-images.githubusercontent.com/26389417/120122102-89301780-c1af-11eb-8d32-b9c6f130452f.png)
Да, это _определённо_ фича

2021-05-31 09:52 UTC, IlinMihail commented
как два последних коммита убрать?

2021-05-31 10:10 UTC, IlinMihail commented
короче я накосячил с гитом и теперь не могу это исправить, закрываю пр

2021-05-31 10:10 UTC, closed without merging

2021-05-31 10:15 UTC, KIBORG04 commented
Только не переоткрывай

2021-05-31 10:17 UTC, IlinMihail commented
не собираюсь

2021-05-31 10:26 UTC, 4310V343k commented
П - понимание

2021-06-07 15:39 UTC, volas commented
@IlinMihail если что, киборг выше имел в виду нашу политику не пересоздавать PR-ы по новой, что бы не терять историю и обсуждение. А не то, что этот PR не нужен.

2021-06-07 16:52 UTC, IlinMihail commented
я знаю но мне стало лень