Burn+trauma=mixed kit
TauCetiStation/TauCetiClassic pull request #7223
Opened 2021-05-27 19:16 UTC by Zickusable

## Описание изменений
Новый смешанный мед.кит с количеством и силой как у берна или трама кита; спрайт для него. Добавил 1 в вендомат. Дал мед.боргу 12 штук с зарядкой со временем. Можно юзать для лечения органов в хирургии.
![image](https://user-images.githubusercontent.com/76683966/119883750-4f5dd780-bf49-11eb-948c-9b9b117ad1bb.png)
 Для борга, если кончился. Кончившегося кита спрайт просто исчезает. Людская версия мигает красным, когда осталась последняя.
![image](https://user-images.githubusercontent.com/76683966/119883827-6ac8e280-bf49-11eb-87be-43915a13d48c.png)
## Почему и что этот ПР улучшит
По сути это травма кит с единичным юзом берн кита (То есть в первый юз применится берн и травма кит одновременно, а дальше работает как травма кит. Медборгу же будет еще легче с его тремя слотами без хоткеев. Дал борг версии перезарядку каждые... 5 секунд?
## Авторство

## Чеинжлог
:cl:
- rscadd: Смешанный синий мед.кит. Есть один в вендоре в медбее. Есть у мед.боргов.

2021-05-27 19:16 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2021-05-27 19:17 UTC, AndroBetel commented
может только боргу его и оставить?

2021-05-27 19:19 UTC, BesumniiChebureck commented
Какой будет смысл в одной штуке в вендомате?

2021-05-27 19:19 UTC, Zickusable commented
> может только боргу его и оставить?

Может, а в вендоре получить один за монетку

2021-05-27 19:21 UTC, LudwigVonChesterfield commented
я не понимаю почему люди могут переключаться между слотами и обмазывать двумя китами, а борги нет?

2021-05-27 19:22 UTC, Zickusable commented
> Какой будет смысл в одной штуке в вендомате?

Вай нот, экономит клики и время, тип экстренный кит

2021-05-27 19:26 UTC, LudwigVonChesterfield commented
срочно нужно мнение медбейчанов чьё время ты так тщательно экономишь...

2021-05-27 19:27 UTC, Zickusable commented
> я не понимаю почему люди могут переключаться между слотами и обмазывать двумя китами, а борги нет?

Борги могут, но им нужно кликнуть по спрайту в инвенторе, активировать, намазать, убрать в инвентор. Все мышкой. Люди могут тупо Q или E чтоб убрать из руки и усе. Кароче, мне не нравится гемор с инветором боргов, вот и объединил.

2021-05-27 19:29 UTC, Sakuya-Izayoi commented on code/game/objects/items/stacks/medical.dm
> +	return ..()
копипаста 🙄 может быть можно сделать компоненту?

2021-05-27 19:29 UTC, Sakuya-Izayoi commented on code/game/objects/items/stacks/medical.dm
> +		icon_state = "traumaburnkitempty"
а почему не `"[initial(icon_state)]empty"`? а зачем вообще нужно это ветвление если нет ретурна? а зачем вообще нужно это ветвление если спрайт пустого набора можно назвать traumaburnkit0?

2021-05-27 19:31 UTC, Sakuya-Izayoi commented
> > я не понимаю почему люди могут переключаться между слотами и обмазывать двумя китами, а борги нет?
> 
> Борги могут, но им нужно кликнуть по спрайту в инвенторе, активировать, намазать, убрать в инвентор. Все мышкой. Люди могут тупо Q или E чтоб убрать из руки и усе. Кароче, мне не нравится гемор с инветором боргов, вот и объединил.

так может надо сделать боргам Q и E? А стоп, это же есть в хоткеях тильды...

Вообще, для борготы ещё нормально, наверное, а людям такое точно не надо. Иначе у нас игроки вообще думать перестанут.

2021-05-27 19:32 UTC, Zickusable commented on code/game/objects/items/stacks/medical.dm
> +		icon_state = "traumaburnkitempty"
Ретурн забыл. У других спрайтов нулевого нет
```suggestion
		icon_state = "traumaburnkitempty" return
```

2021-05-27 19:34 UTC, Sakuya-Izayoi commented on code/game/objects/items/stacks/medical.dm
> +	charge_tick = 0
вместо такого инкремент счётчика я думаю можно просто запомнить последний ворлд тайм когда итем последний раз регенился и потом сравнивать его с текущим временем но вообще это дело вкуса не слушай меня

2021-05-27 19:34 UTC, Sakuya-Izayoi commented on code/game/objects/items/stacks/medical.dm
> +				src.amount++
без src

2021-05-27 20:11 UTC, LudwigVonChesterfield commented on code/game/objects/items/stacks/medical.dm
> +	return ..()
скорее функции лечения моба

2021-05-28 05:01 UTC, Kerzch commented
Боргам бы это заметно сэкономило время, да.
А людям и так ничего не стоит руку поменять, с синим китом они вообще обленятся или даже отупеют

2021-05-28 12:21 UTC, DedYarick commented
вызывайте баланс департамент

2021-06-01 15:24 UTC, LudwigVonChesterfield requested changes
Лично по мне выглядит как костыль.

И ладно это ещё осталось бы у боргов, у которых нет хоткея, это зачем-то пихают людям.

И ладно это пихают людям, но почему-то только в целой одной копии раундстартом в вендомате.

Если проблема в том что у боргов нет хоткеев для быстрого переключения предметов - им нужно добавить хоткеи, а не мутить особые волшебные предметы про которые все будут забивать при любой переделке урона на кукле/предметов лечения.

2021-06-05 14:02 UTC, Zickusable commented
> Лично по мне выглядит как костыль.
> 
> И ладно это ещё осталось бы у боргов, у которых нет хоткея, это зачем-то пихают людям.
> 
> И ладно это пихают людям, но почему-то только в целой одной копии раундстартом в вендомате.
> 
> Если проблема в том что у боргов нет хоткеев для быстрого переключения предметов - им нужно добавить хоткеи

Из вендомата убрано. Хоткеями инвентарь борготы, по-моему, не исправить: у него слишком много предметов.
> мутить особые волшебные предметы про которые все будут забивать при любой переделке урона на кукле/предметов лечения.

Я, наверное, слишком молод, чтобы быть свидетелем таких проблем. Особые волшебные предметы? Этот кит тупо избавляет от пары лишних кликов для каждой части тела берн китом, уменьшает забитость инвентаря, а увеличение максимума - от беготни на перезарядку в роботехнику каждую половину трупа.

2021-06-13 16:55 UTC, Zickusable commented
> Данный ПР автоматически отмечен как застоявшийся по причине длительного отсутствия обновлений. Он будет закрыт через 7 дней, если никакой активности не будет проявлено. Если вы считаете, что ПР еще актуален, или что я (злобный робот) пристаю к вам зря - просто напишите любой комментарий. Спасибо за ваш вклад.

+

2021-06-22 18:16 UTC, T6751 commented
> Борги могут, но им нужно кликнуть по спрайту в инвенторе, активировать, намазать, убрать в инвентор. Все мышкой. Люди могут тупо Q или E чтоб убрать из руки и усе. Кароче, мне не нравится гемор с инветором боргов, вот и объединил.

Борги могут переключаться между своими "руками" с помощью клавиш "1", "2", "3". Чтобы положить активный предмет в инвентарь - "Q"
Единственное что мышкой осталось - это кликнуть по спрайту в инвентаре. Думаю можно улучшить этот момент, позволяя кликать по ячейке, в которой находится предмет, а не по самому спрайту предмета.

Мне кажется, ПР уже не актуален

2021-06-23 06:29 UTC, Zickusable commented
> > Борги могут, но им нужно кликнуть по спрайту в инвенторе, активировать, намазать, убрать в инвентор. Все мышкой. Люди могут тупо Q или E чтоб убрать из руки и усе. Кароче, мне не нравится гемор с инветором боргов, вот и объединил.
> 
> Борги могут переключаться между своими "руками" с помощью клавиш "1", "2", "3". Чтобы положить активный предмет в инвентарь - "Q"
> Единственное что мышкой осталось - это кликнуть по спрайту в инвентаре. Думаю можно улучшить этот момент, позволяя кликать по ячейке, в которой находится предмет, а не по самому спрайту предмета.
> 
> Мне кажется, ПР уже не актуален, @Zickusable ?

Да, это круто все, но у борга всего по 5 китов двух видов без возможности быстро пополнить запас, достав из аптечки еще пару штук без чьей-либо помощи. Типо если чувака протащили трупиком пять тайлов, то на каждой конечности нужно потратить по пять китов и бежать на подзарядку в соседний отдел. Так что теперь этот ПР больше про экономию

2021-06-23 07:11 UTC, Sakuya-Izayoi commented
Мне не нравится что у боргов просто пропадает спрайт.

2021-06-23 10:03 UTC, Zickusable commented
> Мне не нравится что у боргов просто пропадает спрайт.

Не пропадает, просто неправильно описал.

2021-06-28 13:45 UTC, KIBORG04 commented
Давненько не было столько дизлайков на ПРе не со спрайтами

2021-07-17 16:12 UTC, LudwigVonChesterfield commented
> Да, это круто все, но у борга всего по 5 китов двух видов без возможности быстро пополнить запас, достав из аптечки еще пару штук без чьей-либо помощи. Типо если чувака протащили трупиком пять тайлов, то на каждой конечности нужно потратить по пять китов и бежать на подзарядку в соседний отдел. Так что теперь этот ПР больше про экономию

Так добавь им больше стаков?

2021-07-31 19:49 UTC, closed without merging