Science points softcap
TauCetiStation/TauCetiClassic pull request #7259
Opened 2021-05-31 17:48 UTC by EdlerN

## Описание изменений
Суммарное количество научных очков, получаемых с повторного подрыва бомб и ЭМИ импульсов будут иметь лимит, зависящий от максимальной зарегистрированной силы источника.
## Почему и что этот ПР улучшит
В новой системе РНД получение очков задумывалось как основной элемент игрового процесса учёных. Для получения этих очков были созданы различные методы, археология, исследования ядер слизней, взрывы бомб и прочее. Тем не менее - люди свели весь процесс к постройке одной турели с ионной винтовкой и забивания болта на всю систему. 
Можно, разумеется, просто сделать маячок невосприимчивым к пульсам силой 3 и меньше и забетонировать вариант использования ЭМИ от сингулярности, но есть и другой подход.
Почему софткап это хорошо? Потому что он позволит точно регулировать количество получаемых РНД очков и, как следствие, доступные им средства в пересчёте на время раунда и количество людей. Он не убивает напрочь малозатратные методы получения очков, в то же время делая их не слишком эффективными.  С другой стороны, тот же метод с ионной винтовкой может использоваться в сочетании с достаточно мощным источником ЭМИ для "вычёрпывания" этого самого лимита. 
## Авторство
Сам самостоятельно сделал, без мам, пап и кредитов. 
## Чеинжлог
:cl: EdlerN
- balance: Суммарное количество научных очков, получаемых с повторного подрыва бомб и ЭМИ импульсов будут иметь лимит, зависящий от максимальной зарегистрированной силы источника.

2021-05-31 17:48 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2021-05-31 18:28 UTC, Sakuya-Izayoi commented
было бы неплохо, если бы в коде софткап менялся не какими-то волшебными числами, а вычислялся исходя из заданного в конфиге конкретного значения.

2021-05-31 18:34 UTC, T6751 commented on code/modules/research/experiment.dm
> +			var/saved_earned_points = max (RD.files.experiments.earned_score[inter_type], 1)
```Между вызовом процедуры/функции и скобками не должно быть пробела.```
```suggestion
			var/saved_earned_points = max(RD.files.experiments.earned_score[inter_type], 1)
```

2021-05-31 19:07 UTC, EdlerN commented
> было бы неплохо, если бы в коде софткап менялся не какими-то волшебными числами, а вычислялся исходя из заданного в конфиге конкретного значения.

Там кругом магические числа, если так судить. Софткап на то и софткап, что он зависит от самого высокого единоразового значения. В данном пээре он равен удвоенному максимуму. И эта двойка там в начало файла вынесена. Крутить сюда ещё какие-то конфиги как по мне - излишне.

2021-05-31 19:54 UTC, LudwigVonChesterfield approved these changes
Мне жутко не нравится как мы плодим сущности(У нас уже есть сущность, уменьшающая от повторного эксперимента очки - repeat_score_coeff, но мы теперь ещё создаём softcap_coeff, при чём почему-то софткап это не совсем кап, а ещё один коэффициент в формуле, что обязательно у кого-то мозговитого выйдет боком)

А в целом я за, и не думаю что тут к чему-то можно прикопаться.

2021-05-31 20:01 UTC, EdlerN commented
> Мне жутко не нравится как мы плодим сущности(У нас уже есть сущность, уменьшающая от повторного эксперимента очки - repeat_score_coeff, но мы теперь ещё создаём softcap_coeff, при чём почему-то софткап это не совсем кап, а ещё один коэффициент в формуле, что обязательно у кого-то мозговитого выйдет боком)

Технически, это может быть полезно для более тонкой настройки. А софткап он на то и софткап, что реальный лимит зависит от других параметров.  В теории, на этот лимит можно даже позволить как-то влиять в дальнейшем. Собственно, с этими мыслями я и вынес этот параметр в датум экспериментов.

2021-06-01 04:57 UTC, kalazus commented
Прям такое себе. Ещё одна заплатка лишь бы учёных хуже жилось.

2021-06-01 07:41 UTC, Zmey25 commented
>были созданы различные методы, археология

Археология рип, бумажки оттуда не дают очков. Кажется никто так и не починил её.

2021-06-01 12:00 UTC, HalfoftheSeal commented
> Археология рип, бумажки оттуда не дают очков. Кажется никто так и не починил её.

Отчёты о вскрытии тоже поинты не дают. Вирусология, наверняка, тоже по тому же принципу поломана. По факту только бомбы и имеем для получения поинтов, если нет ксенобиологов.

2021-06-01 14:00 UTC, EdlerN commented
> Отчёты о вскрытии тоже поинты не дают. Вирусология, наверняка, тоже по тому же принципу поломана. По факту только бомбы и имеем для получения поинтов, если нет ксенобиологов.

А можно пожалуйста не вводить людей в заблуждение? Вот недавно проверили и всё работает.

2021-06-01 15:06 UTC, Lexanx commented
Только вскрытие даёт очки.


Археология, ничего не приносит, Генетика так же, не имеет пользы для РнД. 
Было бы хорошо наконец-то сделать археологов полезными вплане очков. И позволить считывать диски генетиков, саенс тулом, для получения очков. 
Сюда же можно отнести и вирусологию. Это добавило бы больше общения между отделами.

2021-06-02 16:59 UTC, BeebBeebBoob commented
Тут иногда учёные получают очки просто забрасывая датчик к ускорителю частиц. В один момент Сканнер начал давать 1 поинт исследования.
![image](https://user-images.githubusercontent.com/32985153/120520858-f8d71a00-c3dc-11eb-829d-37a3901e7cd5.png)

2021-06-02 17:21 UTC, EdlerN commented
> Тут иногда учёные получают очки просто забрасывая датчик к ускорителю частиц. В один момент Сканнер начал давать 1 поинт исследования.

Чем ближе к капу, тем меньше дают импульсы. Если ещё подождать оно вообще скажет мол, всё, больше не могу ничего получить. Это нормально.

2021-06-02 18:52 UTC, logimy commented
Ну шо я могу сказать, участвовал в 2-3 раундах, где рнд стало совершенно бесполезно после софткапа, потому что самым прикольным способом заанлокать техи стал телесаенс с херовыми дисками и бумажками вирусов, разбросанными по дереликтам.

Жду нового абуза, до этого играть в РнД можно только ради теленауки

2021-06-04 11:27 UTC, LudwigVonChesterfield requested changes
Сейчас есть какой-то гигамем, где при взрыве лимитки на 30 - получаем 391кк очков.

2021-06-04 12:02 UTC, KIBORG04 commented on code/modules/research/experiment.dm
> +			calculated_research_points = added_score * new_score_coeff + min(already_earned_score * round(repeat_score_coeff * softcap_coeff), repetition_cap - saved_earned_points)
Вроде нормально написано, но все равно нужно постараться, чтобы понять че тут происходит

2021-06-04 12:13 UTC, EdlerN commented on code/modules/research/experiment.dm
> +			calculated_research_points = added_score * new_score_coeff + min(already_earned_score * round(repeat_score_coeff * softcap_coeff), repetition_cap - saved_earned_points)
Если делать понятнее - это нужно ещё пяток переменных создавать. Могу в принципе и так сделать.

2021-06-04 12:18 UTC, Sakuya-Izayoi commented on code/modules/research/experiment.dm
> +			calculated_research_points = added_score * new_score_coeff + min(already_earned_score * round(repeat_score_coeff * softcap_coeff), repetition_cap - saved_earned_points)
можно комментарий написать...

2021-06-04 12:22 UTC, logimy commented on code/modules/research/experiment.dm
> +			calculated_research_points = added_score * new_score_coeff + min(already_earned_score * round(repeat_score_coeff * softcap_coeff), repetition_cap - saved_earned_points)
Просто коммент

2021-06-06 05:35 UTC, ssbugman commented
Может прежде чем заниматься нерфами стоит задуматься почему ученые так делают? Может причина в том что нынешняя система заработка очков неудачна и дает недостаточно очков?
> Почему софткап это хорошо? Потому что он позволит точно регулировать количество получаемых РНД очков и, как следствие, доступные им средства в пересчёте на время раунда и количество людей

А кто сказал что это хорошо и нужно а не просто руинит всю роль им задачу РнД?

2021-06-06 07:11 UTC, logimy commented
> Может прежде чем заниматься нерфами стоит задуматься почему ученые так делают?

Перед нерфами стоит поиграть в РнД, это да

2021-06-06 09:55 UTC, EdlerN commented
> Может прежде чем заниматься нерфами стоит задуматься почему ученые так делают?

Люди пытаются оптимизировать игровой процесс из игры. Проблема далеко не новая и не только у нас встречающаяся.

> А кто сказал что это хорошо и нужно а не просто руинит всю роль и задачу РнД?

Интересно как? Я просто напомню, что рнд формально на станции не имеет никакой непосредственной задачи. И если в раунд не зайдёт ни одного учёного - ничего не изменится. Игровой процесс рнд состоит из трёх аспектов по сути: различные мини-игры для получения пойнтов, менеджмент ограниченных ресурсов и взаимодействие с другими отделами для улучшения работы последних. 

Я надеюсь мне не нужно объяснять, почему, если один метод получения пойнтов позволяет забить на всю систему в целом - это плохо с точки зрения дизайна? Ровно как и то, почему необходимость выбора только добавляет процессу интереса.

И, да, рнд до сих пор может изучить все ветки. Просто для этого ему нужно задействовать все (ну или большинство) способов получения пойнтов.

2021-06-06 13:22 UTC, ssbugman commented
> Люди пытаются оптимизировать игровой процесс из игры

Люди пытаются играть, а ты зачем-то лишаешь их по сути единственного источника очков нужных для геймплея, вводя никому не нужный потолок.

> Я просто напомню, что рнд формально на станции не имеет никакой непосредственной задачи. И если в раунд не зайдёт ни одного учёного - ничего не изменится

Научная станция. "РНД не играет никакой роли." Щито???
РНД так-то является источником массы полезного для всех остальных отделом и все очень сильно меняется от работы ученых.

> Просто для этого ему нужно задействовать все (ну или большинство) способов получения пойнтов.
Те самые которые вообще одноразовые да еще и никак не зависят от ученых?

2021-06-06 13:33 UTC, Sakuya-Izayoi commented
> > Люди пытаются оптимизировать игровой процесс из игры
> 
> Люди пытаются играть, а ты зачем-то лишаешь их по сути единственного источника очков нужных для геймплея, вводя никому не нужный потолок.
> 
> > Я просто напомню, что рнд формально на станции не имеет никакой непосредственной задачи. И если в раунд не зайдёт ни одного учёного - ничего не изменится
> 
> Научная станция. "РНД не играет никакой роли." Щито???
> РНД так-то является источником массы полезного для всех остальных отделов и все очень сильно меняется от работы ученых.
> 
> > Просто для этого ему нужно задействовать все (ну или большинство) способов получения пойнтов.
> 
> Те самые которые вообще одноразовые да еще и никак не зависят от ученых? Ученым лично что ли надо убивать народ чтобы наделать отчетов из морга на каждый вид урона?
> Ученые ведь не просто так их не используют, другие пути нормально не работают. Просто нифига не исследовано каждый раунд, очков нет и все на этом.

может надо просто перестать качать комбат ветку каждый раунд

2021-06-06 14:10 UTC, EdlerN commented
> Люди пытаются играть, а ты зачем-то лишаешь их по сути единственного источника очков нужных для геймплея, вводя никому не нужный потолок.

Единственного? Хм, давайте подумаем. Из источников очков у нас есть:

Разборка предметов (В районе 10-20 тысяч даст спокойно)
Телесаенс (немного рандомен, обычные диски дают 1-10 тысяч, редкие - 10-20)
Слаймы (20-40 тысяч пойнтов)
Бомбы (80к кап, но в среднем сейчас 60к дают)
Эми (Синга фармит порядка 30-40 тысяч)
Артефакты с археологии (5-10 тысяч за штуку, копаются не очень сложно)
Вирусы (В зависимости от качества можно и 20 тысяч за штуку получить)
Вскрытия тел (макака из генетики в помощь. По 1-2 тысячи очков за каждое ОРУЖИЕ)

Из этого списка учёные не могут реально заниматься разве что вирусами. 

А для полного изучения веток нужно
Инженерка 21000
Биология 10900
Комбат 20500
Энергия 12300
Блюспейс 10800
Роботика 39000

Итого ~ 110к пойнтов. Дальше только улучшать надёжность которая внезапно улучшается ещё и за ресурсы печатанием прототипов. Также стоит понимать что там есть куча дорогого и не очень нужного, к примеру тот же токомак, который стоит 5к.

Короче говоря, какое-то непонятное нытьё а не фидбек.

2021-06-06 14:16 UTC, Sakuya-Izayoi commented
> > Люди пытаются играть, а ты зачем-то лишаешь их по сути единственного источника очков нужных для геймплея, вводя никому не нужный потолок.
> 
> Единственного? Хм, давайте подумаем. Из источников очков у нас есть:
> 
> Разборка предметов (В районе 10-20 тысяч даст спокойно)
> Телесаенс (немного рандомен, обычные диски дают 1-10 тысяч, редкие - 10-20)
> Слаймы (20-40 тысяч пойнтов)
> Бомбы (80к кап, но в среднем сейчас 60к дают)
> Эми (Синга фармит порядка 30-40 тысяч)
> Артефакты с археологии (5-10 тысяч за штуку, копаются не очень сложно)
> Вирусы (В зависимости от качества можно и 20 тысяч за штуку получить)
> Вскрытия тел (макака из генетики в помощь. По 1-2 тысячи очков за каждое ОРУЖИЕ)
> 
> Из этого списка учёные не могут реально заниматься разве что вирусами.
> 
> А для полного изучения веток нужно
> Инженерка 21000
> Биология 10900
> Комбат 20500
> Энергия 12300
> Блюспейс 10800
> Роботика 39000
> 
> Итого ~ 110к пойнтов. Дальше только улучшать надёжность которая внезапно улучшается ещё и за ресурсы печатанием прототипов. Также стоит понимать что там есть куча дорогого и не очень нужного, к примеру тот же токомак, который стоит 5к.
> 
> Короче говоря, какое-то непонятное нытьё а не фидбек.

это очки с учетом мк2 или хотя бы мк1?

2021-06-06 14:19 UTC, EdlerN commented
> это очки с учетом мк2 или хотя бы мк1?

Это без повышения надёжности. Потому что надёжность повышается постройкой прототипов. 10 прототипов дают 100%.

2021-06-06 16:38 UTC, KIBORG04 commented
когда мерж?

2021-06-06 16:45 UTC, KIBORG04 approved these changes
Гигамем пофикшен

2021-06-07 11:18 UTC, LudwigVonChesterfield approved these changes
гигамем пофикшен какими-то надмозговыми формулами

2021-06-07 15:08 UTC, merged

2022-07-22 14:03 UTC, TauKitty commented
Этот запрос на извлечение был упомянут в **Tau Ceti Station Forum**. Там могут быть соответствующие подробности:

https://forum.taucetistation.org/t/fludilka-chast-2/28659/11657

2022-07-24 12:37 UTC, TheLone1y commented
Ар ю виннинг сан?