Выключение анимаций радиального меню
TauCetiStation/TauCetiClassic pull request #7266
Opened 2021-05-31 23:19 UTC by 4310V343k

## Описание изменений
thank god
Теперь не надо ждать долгие полсекунды пока радиалка не появится
Или надо, если вы не умеете в механ и работку
## Почему и что этот ПР улучшит
Моё удовлетворение игрой на ИИ
## Авторство
remindme
## Чеинжлог
:cl:
 - tweak: Анимацию появления радиального меню теперь можно выключить в настройках персонажа или из вкладки Preferences

2021-05-31 23:19 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2021-05-31 23:28 UTC, LudwigVonChesterfield commented
мне наверное не нравится что тыкание в настройках префов даёт механопреимущество. если лучше без анимации, то может стоит убрать её всем?

2021-05-31 23:41 UTC, Sakuya-Izayoi commented
> мне наверное не нравится что тыкание в настройках префов даёт механопреимущество. если лучше без анимации, то может стоит убрать её всем?

а это разве не дело вкуса?

2021-06-01 09:25 UTC, UDaV73rus commented
ДАДАДАДАДА
но преф не нужен, лишь обрекает на страдание новичков не знающих о префе

2021-06-01 15:35 UTC, LudwigVonChesterfield requested changes
Я за изменение, я против того что оно опциональное.

Почему-то чтобы получить механопреимущество новичку нужно лезть в настройки. Если же по дефолту анимации выключены, то выходит что новичку откуда-то надо знать что их можно включить.

Если эта анимация всем только мешает (создаёт задержку), очевидно её надо просто выпилить.

2021-06-11 19:08 UTC, closed without merging