Плавление шкафчиков термитом
TauCetiStation/TauCetiClassic pull request #7269
Opened 2021-06-01 09:54 UTC by IlinMihail

## Описание изменений
Шкафчики теперь можно полить термитом из контейнера и поджечь дабы уничтожить.
## Почему и что этот ПР улучшит
Более быстрый способ открытия шкафчиков чем расстрел/подрыв. #7167
## Авторство

## Чеинжлог
🆑M104
add: Плавление шкафчиков термитом

2021-06-01 09:54 UTC, TauKitty commented
###### Changelog status: :x: Empty changelog (check markdown correctness)

2021-06-01 15:37 UTC, LudwigVonChesterfield commented on code/game/objects/structures/crates_lockers/closets.dm
> +	if(istype(W, /obj/item/weapon/reagent_containers))
если тыкнуть закрытым контейнером по шкафу термит прольётся.

2021-06-01 15:37 UTC, LudwigVonChesterfield commented on code/game/objects/structures/crates_lockers/closets.dm
> +		W.reagents.reagent_list -= W.reagents.reagent_list
это некорректный способ убирания N кубов термита из контейнера

2021-06-01 15:37 UTC, LudwigVonChesterfield commented on code/game/objects/structures/crates_lockers/closets.dm
> +	var/thermite = 0
выходит шкафчик навсегда поплавленный?

2021-06-01 15:38 UTC, LudwigVonChesterfield commented on code/game/objects/structures/crates_lockers/closets.dm
> +/obj/structure/closet/proc/thermitemelt(mob/user, seconds_to_melt)
я ещё не проверил что это копипаста, но я ощущаю что это копипаста. если это копипаста, может стоит сделать этот метод методом /atom-а, или просто глобальным методом?

```
/atom/proc/thermitemelt() -- и сделать чтобы больше предметов можно было плавить
```
```
/proc/thermitemelt()
```

2021-06-01 15:38 UTC, LudwigVonChesterfield commented on code/game/objects/structures/crates_lockers/closets.dm
> +/obj/structure/closet/proc/thermitemelt(mob/user, seconds_to_melt)
Если делать его атомовым то можно придумать какие-то фишки что какие-то вещи на термит реагируют не тем что плавятся, а к примеру мемасно бабахают (см. фуелтанки)

2021-06-01 15:40 UTC, LudwigVonChesterfield commented on code/game/objects/structures/crates_lockers/closets.dm
> +				user.visible_message("<span class='warning'>You ignite thermite on the [src].</span>")
а разве не выйдет что всем кто смотрит как шкафчик плавят напишет что ОНИ плавят шкафчик?

2021-06-01 15:41 UTC, LudwigVonChesterfield requested changes
Мне не нравится что термит нельзя вытереть со шкафчика, что там копипаста термитпрока.

2021-06-01 15:57 UTC, IlinMihail commented on code/game/objects/structures/crates_lockers/closets.dm
> +		W.reagents.reagent_list -= W.reagents.reagent_list
так я хочу весь контейнер опустошить а не только термит

2021-06-01 15:57 UTC, IlinMihail commented on code/game/objects/structures/crates_lockers/closets.dm
> +	var/thermite = 0
почему, просто по умолчанию шкафчик не имеет на себе термита

2021-06-01 15:59 UTC, IlinMihail commented on code/game/objects/structures/crates_lockers/closets.dm
> +				user.visible_message("<span class='warning'>You ignite thermite on the [src].</span>")
сообщение об поливании шкафчика термитом и поджоге выводится по идее только юзеру, а вот сообщение о том что шкафчик плавится всем

2021-06-01 16:00 UTC, LudwigVonChesterfield commented on code/game/objects/structures/crates_lockers/closets.dm
> +				user.visible_message("<span class='warning'>You ignite thermite on the [src].</span>")
но у тебя тут только одно сообщение - о поджоге

2021-06-01 16:01 UTC, IlinMihail commented
1. разве можно термит убрать со стены?
2. если копипасту заменить на /atom/proc/thermitemelt() то куда этот процесс воткнуть?

2021-06-01 16:02 UTC, LudwigVonChesterfield commented
> разве можно термит убрать со стены?

ну разбором наверное, но то что там плохо, не значит что ты должен делать плохо.

> если копипасту заменить на /atom/proc/thermitemelt() то куда этот процесс воткнуть?

какой процесс?

2021-06-01 16:03 UTC, IlinMihail commented on code/game/objects/structures/crates_lockers/closets.dm
> +				user.visible_message("<span class='warning'>You ignite thermite on the [src].</span>")
ну здесь да а так ещё user.visible_message("<span class='notice'>You pour some thermite on the [src].</span>")
и visible_message("<span class='warning'>Thermite starts melting the [src]. </span>")

2021-06-01 16:04 UTC, IlinMihail commented on code/game/objects/structures/crates_lockers/closets.dm
> +	if(istype(W, /obj/item/weapon/reagent_containers))
> какой процесс?
тупой вопрос, извиняюсь

2021-06-01 16:05 UTC, LudwigVonChesterfield commented on code/game/objects/structures/crates_lockers/closets.dm
> +				user.visible_message("<span class='warning'>You ignite thermite on the [src].</span>")
я почти уверен что это можно как-то по-другому сделать чтобы было лучше...

что-то типо

user.visible_message("<span class='warning'>Thermite starts melting the [src]</span>", "<span>You ignite thermite ... </span>")

2021-06-01 16:09 UTC, IlinMihail commented
> какой процесс?

этот прок можно в atoms.dm поместить?

2021-06-01 16:11 UTC, IlinMihail commented on code/game/objects/structures/crates_lockers/closets.dm
> +				user.visible_message("<span class='warning'>You ignite thermite on the [src].</span>")
можно, просто я сообщения к разным событиям привязал

2021-06-01 17:13 UTC, IlinMihail commented
я не справился с атомарным процессом. может быть шкафчиков пока хватит?

2021-06-01 17:16 UTC, IlinMihail commented on code/game/objects/structures/crates_lockers/closets.dm
> +				user.visible_message("<span class='warning'>You ignite thermite on the [src].</span>")
я просто привязал разные сообщения к разным действиям. если так больше нравится поменяю

2021-06-01 19:23 UTC, KIBORG04 commented
Мне кажется, не зря этой фичи раньше не было. Может вызвать едлерна?

2021-06-01 20:28 UTC, Sakuya-Izayoi commented
> Мне кажется, не зря этой фичи раньше не было. Может вызвать едлерна?

мне кажется этой фичи раньше не было потому что до неё никто не додумывался. в менторхелп нередко поступают вопросы как расплавить шкафчик термитом, так что могу предположить что на каком-то билде откуда к нам приходят люди всё-таки такой функционал есть.

2021-06-01 20:45 UTC, IlinMihail commented
ну так дорабатывать текущую версию или закрыть коммит и забить/делать атомарную версию?

2021-06-03 15:14 UTC, KIBORG04 commented on code/game/objects/structures/crates_lockers/closets.dm
> +	var/thermite = 0
Не имеет смысла хранить переменную в классе. Объяви её локально в том проке. Так же, лучще дай ей имя, тип `has_thermite`

2021-06-03 15:15 UTC, KIBORG04 commented on code/game/objects/structures/crates_lockers/closets.dm
> +	var/seconds_to_melt = 5
Измени эту штуку в дефайн, если он еще не создан

2021-06-03 15:17 UTC, KIBORG04 commented on code/game/objects/structures/crates_lockers/closets.dm
> +/obj/structure/closet/proc/thermitemelt(mob/user, seconds_to_melt)
Здесь у тебя есть sleep, а если смотреть на контекст, то тебе поидее не нужно стоять со сваркой 5 секунд ради расплавки шкафчика ЦЕЛИКОМ

2021-06-03 15:18 UTC, KIBORG04 commented on code/game/objects/structures/crates_lockers/closets.dm
> +	qdel(src)
Я не думаю что ты справишься, но все же. Можно поробовать создать маску для открытой двери и через фильтры эту дверь "удалять". Пример можно увидеть в ПРе гетупа с разделением двух таблеток.
Вариант с дверью выглядел бы покруче, вместо уничтожения шкафчика целиком

2021-06-03 15:19 UTC, KIBORG04 commented on code/game/objects/structures/crates_lockers/closets.dm
> +				thermite = 1
тру, ибо переменная юзается как булевая

2021-06-03 18:38 UTC, IlinMihail commented on code/game/objects/structures/crates_lockers/closets.dm
> +	var/seconds_to_melt = 5
так если я буду юзать один прок для плавления и стен и шкафов и может быть чего то ещё то смысл делать дефайн если у каждого обьекта время плавления разное

2021-06-03 18:39 UTC, IlinMihail commented on code/game/objects/structures/crates_lockers/closets.dm
> +/obj/structure/closet/proc/thermitemelt(mob/user, seconds_to_melt)
юзер и не стоит пять секунд со сваркой, он тупо тыкает по шкафу один раз, он уничтожается а эффект пропадает через 5 секунд

2021-06-03 18:57 UTC, IlinMihail commented on code/game/objects/structures/crates_lockers/closets.dm
> +	var/thermite = 0
я собираюсь юзать общий прок, но не хочу плавить каждый атом а только стены и шкафы. стоит эту переменную в атомы поместить и в проке проверять является ли src шкафом/стеной?

2021-06-03 20:03 UTC, IlinMihail commented on code/game/objects/structures/crates_lockers/closets.dm
> +	if(istype(W, /obj/item/weapon/reagent_containers))
какой прок проверяет открыт ли контейнер? я не нашёл

2021-06-03 20:37 UTC, KIBORG04 commented on code/game/objects/structures/crates_lockers/closets.dm
> +	var/seconds_to_melt = 5
Ну вот сначала сделай

2021-06-03 20:39 UTC, KIBORG04 commented on code/game/objects/structures/crates_lockers/closets.dm
> +	var/thermite = 0
Ну попробуй, но наверное можно что-то умное придумать

2021-06-11 11:02 UTC, IlinMihail commented on code/game/objects/structures/crates_lockers/closets.dm
> +	if(istype(W, /obj/item/weapon/reagent_containers))
исправлено

2021-06-11 11:04 UTC, IlinMihail commented
> Мне не нравится что термит нельзя вытереть со шкафчика, что там копипаста термитпрока.

теперь можно клинером/водой

2021-06-11 11:05 UTC, IlinMihail commented on code/game/objects/structures/crates_lockers/closets.dm
> +				thermite = 1
исправлено

2021-06-11 11:06 UTC, IlinMihail commented on code/game/objects/structures/crates_lockers/closets.dm
> +	var/seconds_to_melt = 5
атомарный прок сделан, я могу оставить var/seconds_to_melt = x?

2021-06-11 11:06 UTC, IlinMihail commented on code/game/objects/structures/crates_lockers/closets.dm
> +	var/thermite = 0
has_thermite оставил для шкафов/стен отдельно

2021-06-11 11:07 UTC, IlinMihail commented on code/game/objects/structures/crates_lockers/closets.dm
> +/obj/structure/closet/proc/thermitemelt(mob/user, seconds_to_melt)
прок атомарный

2021-06-11 11:08 UTC, IlinMihail commented on code/game/objects/structures/crates_lockers/closets.dm
> +	qdel(src)
не хочу так делать потому что я чуть чуть ленивый и поскольку по логике термит от шкафчика должен только лужицу метала оставить

2021-06-11 11:22 UTC, Sakuya-Izayoi commented on code/game/atoms.dm
> +	qdel(O)
```suggestion
	QDEL_IN(O, seconds_to_melt SECONDS)
```

2021-06-11 11:22 UTC, Sakuya-Izayoi commented on code/game/atoms.dm
> +			return
вынеси это полиморфизмом

2021-06-11 11:27 UTC, Sakuya-Izayoi commented on code/game/objects/effects/chemsmoke.dm
> +						W.has_thermite = FALSE
наверное у реагента должен быть какой-то прок специально для этого

2021-06-11 11:27 UTC, Sakuya-Izayoi commented on code/game/objects/structures/crates_lockers/closets.dm
> +					user.visible_message("<span class='notice'>You clean [src] with water.</span>")
это тоже какой-то лютый хардкод. почему шкаф решает что с ним делают реагенты а не наоборот?

2021-06-11 11:27 UTC, Sakuya-Izayoi commented on code/game/objects/structures/crates_lockers/closets/secure/secure_closets.dm
> +					user.visible_message("<span class='notice'>You clean [src] with water.</span>")
копипаста

2021-06-11 11:28 UTC, Sakuya-Izayoi commented on code/game/turfs/simulated/walls_reinforced.dm
> +			dismantle_wall()
```suggestion
			dismantle_wall()

```

2021-06-11 11:37 UTC, IlinMihail commented on code/game/objects/effects/chemsmoke.dm
> +						W.has_thermite = FALSE
по моему был turf_reaction() для термита и плант-би-гона, но у меня только одну переменную надо менять

2021-06-11 11:49 UTC, IlinMihail commented on code/game/objects/structures/crates_lockers/closets.dm
> +					user.visible_message("<span class='notice'>You clean [src] with water.</span>")
ну так вот получилось

2021-06-11 11:50 UTC, IlinMihail commented on code/game/objects/structures/crates_lockers/closets/secure/secure_closets.dm
> +					user.visible_message("<span class='notice'>You clean [src] with water.</span>")
ну да, одна и та же проверка повторяется для шкафов, стен, укреплённых стен, шкафов с замком.

2021-06-11 12:07 UTC, Sakuya-Izayoi commented on code/game/objects/structures/crates_lockers/closets.dm
> +					user.visible_message("<span class='notice'>You clean [src] with water.</span>")
все что я говорю необязательно (я не билд мейнтейнер), но я почти уверен что придут дядьки мейнтейнеры и скажут то же самое.

2021-06-11 12:08 UTC, KIBORG04 commented on code/game/objects/structures/crates_lockers/closets.dm
> +					user.visible_message("<span class='notice'>You clean [src] with water.</span>")
Если сможешь оспорить предложение билд мейнтейнера, то можешь не делать. Но я уже вижу, что ты не оспоришь 🙈

2021-06-11 12:21 UTC, KIBORG04 commented on code/game/atoms.dm
> +//atoms.dm
А типо не видно что это code/game/atoms.dm ?

2021-06-11 12:22 UTC, KIBORG04 commented on code/game/atoms.dm
> +			return
Вынеси

2021-06-11 12:23 UTC, KIBORG04 commented on code/game/objects/effects/chemsmoke.dm
> +						W.has_thermite = FALSE
гетуп пока все по факту пишет

2021-06-11 12:24 UTC, KIBORG04 commented on code/game/objects/structures/crates_lockers/closets.dm
> +	var/seconds_to_melt = 10
Поли-что? Морфизм.

Это не должна быть уникальная перменная объекта, а так же она не должна передаваться аргументов в thermitemelt().

2021-06-11 12:24 UTC, KIBORG04 commented on code/game/objects/structures/crates_lockers/closets.dm
> +	var/has_thermite = FALSE
Тут тоже самое

2021-06-11 12:26 UTC, KIBORG04 commented on code/game/turfs/simulated/walls.dm
> +			dismantle_wall()
```suggestion
			dismantle_wall()

```

2021-06-11 12:27 UTC, KIBORG04 commented on code/game/objects/effects/chemsmoke.dm
> +//chemsmoke.dm
Тут тоже зачем-то

2021-06-11 12:29 UTC, KIBORG04 requested changes
В общем, очень много истаймов и других проверок на какой-то определенный реагент. Избавься от этого тем же полиморфизмом у атомов.

2021-06-11 21:10 UTC, IlinMihail commented on code/game/objects/structures/crates_lockers/closets.dm
> +					user.visible_message("<span class='notice'>You clean [src] with water.</span>")
да не собираюсь я никого оспаривать, просто я нубло которое взялось за казалось бы несложную фичу и теперь не знающее как её нормально допилить

2021-06-11 21:11 UTC, IlinMihail commented on code/game/atoms.dm
> +//atoms.dm
ой я накосячил забыл убрать извините

2021-06-11 22:26 UTC, KIBORG04 commented on code/game/objects/structures/crates_lockers/closets.dm
> +	var/seconds_to_melt = 10
Нет

2021-06-25 22:51 UTC, closed without merging