добавляет трейт завхозу
TauCetiStation/TauCetiClassic pull request #7271
Opened 2021-06-01 10:57 UTC by AndroBetel

## Описание изменений
теперь завхоз может видеть стоимость предметов просто их проеэкззаминив
![image](https://user-images.githubusercontent.com/44546836/120312250-25a60700-c2e1-11eb-8e8a-ca813205cc3a.png)
возможно сюда буду добавлять ещё всяких трейтов для проф
## Почему и что этот ПР улучшит
завхоз теперь не просто грузчик+ а имеет какую-то свою механофичу, ура.
## Авторство
я
## Чеинжлог
:cl:
- rscadd: Завхоз получил возможность видеть стоимость предметов в экзамине.

2021-06-01 10:57 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2021-06-01 10:59 UTC, LudwigVonChesterfield commented on code/__DEFINES/traits.dm
> +#define TRAIT_QUARTERMASTER       "quartermaster"
мне кажется плохо её так называть, потому-что у нас каким-то воксам такое могут потом дать(если они будут как раньше пираты работали что воруют на стоимость)

Может лучше TRAIT_BOOKKEEPER(в Дворф Фортрессе так), TRAIT_TORGASH(ну или как там у англичан)?

2021-06-01 11:00 UTC, AndroBetel commented on code/__DEFINES/traits.dm
> +#define TRAIT_QUARTERMASTER       "quartermaster"
ты прав

2021-06-01 11:00 UTC, LudwigVonChesterfield commented on code/game/objects/objs.dm
> +		if(HAS_TRAIT(user, TRAIT_QUARTERMASTER))
можно объединить с условием выше

2021-06-01 11:00 UTC, LudwigVonChesterfield commented on code/game/objects/objs.dm
> +			to_chat(user, "<span class='notice'>[src] costs about [price] supply points.</span>")
я бы предложил округлять до десятков/пятидесятков, чтобы сканнер имел какую-то минимальную пользу

2021-06-01 11:01 UTC, LudwigVonChesterfield commented on code/game/jobs/job/job.dm
> +		ADD_TRAIT(H, trait, ROUNDSTART_TRAIT)
источником трейта должна быть профессия, а не РАУНДСТАРТ_ТРЕЙТ, РАУНДСТАРТ это для квирков

2021-06-01 11:01 UTC, LudwigVonChesterfield commented on code/game/jobs/job/job.dm
> +		ADD_TRAIT(H, trait, ROUNDSTART_TRAIT)
(добавить в список дефайнов источников JOB_TRAIT)

2021-06-01 11:12 UTC, AndroBetel commented
увидел что сделал или вместо и сейчас поправлю

2021-06-01 11:16 UTC, volas commented on code/game/jobs/job/job.dm
> +	var/list/job_traits
это должен быть инструментарий, может ПДА модуль, а не особенность персонажа. Как и везде у других проф.

2021-06-01 11:18 UTC, AndroBetel commented on code/game/jobs/job/job.dm
> +	var/list/job_traits
а если другим профам сделать такие же трейты?

2021-06-01 11:38 UTC, volas commented on code/game/jobs/job/job.dm
> +	var/list/job_traits
Зачем плодить сущности и давать персонажам какие-то магические знания? Сейчас у проф уже достаточно подобного функционала завязано на предметы. Мулботы у КМа в пда, худы у сб и медиков, сканеры у атмосферников и так далее.

2021-06-01 11:39 UTC, AndroBetel commented on code/game/jobs/job/job.dm
> +	var/list/job_traits
если идея под гейм дизайн не подходит - то можешь закрывать

2021-06-01 11:56 UTC, Sadmadowl commented on code/game/jobs/job/job.dm
> +	var/list/job_traits
Волас в попытках уничтожить любой интересный функционал в профах которые редко пикают. В чем проблема совмещать и предметы и трейты проф одновременно.  Никакого ущерба игре это не привнесет, а уникальную профессию сделает более осмысленной и интересной.

2021-06-01 14:32 UTC, disco-o commented
прекратите делать из билда рендивеб

2021-06-01 14:33 UTC, AndroBetel commented
1488 пиздить идеи мы не бросим

2021-06-01 15:42 UTC, LudwigVonChesterfield commented on code/game/jobs/job/job.dm
> +	var/list/job_traits
@volas ну согласись, когда ты чувствуешь что твой персонаж знает больше чем другие просто потому-что это твой персонаж, а не потому-что ты взял какого-то лута - это тоже прикольное ощущение, которое возможно стоит добавления этих магических сущностей.

2021-06-01 15:45 UTC, LudwigVonChesterfield commented
Название ПР-а и комментарий

> а если другим профам сделать такие же трейты?

Как бы намекает на более грандиозные планы. Возможно, если хочется сделать прецедент в билде с около-скилл-like механиками, то стоит более обширно хотя бы описать механику, или подождать когда накопится критическая масса контента чтобы уже нельзя было сказать "этого больше нигде в билде нет"(что кстати тоже не правда, клоун вон особенный просто потому-что он клоун, а ещё есть некоторые фичи которые работают только на охранке или ролях)

2021-06-01 15:48 UTC, AndroBetel commented
переносим абилки мима и клоуна на трейты
???
профитс

на тг кстати то, что охрану хилят какие-то там особенные реагенты тоже вынесено в трейт, может, стоит так же сделать?

2021-06-01 15:54 UTC, Snailcat commented
> переносим абилки мима и клоуна на трейты
> ???
> профитс
> 
> на тг кстати то, что охрану хилят какие-то там особенные реагенты тоже вынесено в трейт, может, стоит так же сделать?

База

2021-06-01 15:55 UTC, LudwigVonChesterfield commented
> переносим абилки мима и клоуна на трейты

Если бы мутации накидывали трейты и были бы отдельны для них думаю было бы хайпово. (И флаги рас?)

2021-06-01 15:55 UTC, AndroBetel commented
а на тэгэ так и сделано гыгы

2021-06-01 16:01 UTC, volas commented on code/game/jobs/job/job.dm
> +	var/list/job_traits
Придерживаться уже имеющихся в билде решений проще. Если мы хотим что-то такое, должен быть план и комплексное решение, обсуждение, а не в рамках одного ПРа придумывать систему перков проф. Какие они еще могут быть, какое влияние могут оказывать, подходит ли это нам и какие проблемы могут возникнуть. То же самое что и со скилами, как эти перки разучивать при смене проф.

Иначе если сегодня смержим это, завтра уже не будет причин не смержить чей-нибудь кусочек системы скилов с теми же причинами, после завтра еще какая нибудь такая же фигня.

2021-06-01 19:05 UTC, logimy commented
>  парамедики быстро таскают вещи

Опять бафы профы, которую абузят все кому не лень

2021-06-01 19:05 UTC, AndroBetel commented
логимая обидели противогазы в детстве

2021-06-01 23:12 UTC, LudwigVonChesterfield commented on code/modules/mob/living/carbon/human/human_movement.dm
> +		if(!HAS_TRAIT(src, TRAIT_MULE))
можно тоже объединить с проверкой выше

2021-06-02 02:44 UTC, Sakuya-Izayoi commented
а можно шахтёрам и археологам трейт что их не замедляет скафандр? тогда можно будет спокойно занерфать гиперцин наверное...

2021-06-19 20:00 UTC, AndroBetel commented
ну что решили

2021-06-19 21:47 UTC, KIBORG04 commented
Вообщем решили чтобы ты закодил каждой профессии такой трейт

2021-06-22 10:33 UTC, T6751 commented
Как альтернатива, может сделать это квирками, которые можно выбрать в преференсах. Однако по умолчанию данным профам такие квирки будут идти как бонус к выбранным?

2021-06-22 10:35 UTC, AndroBetel commented
кмовский трейт слишком узконаправленный для квирка, а парамедиковский слишком имбовый чтобы выдавать его всем желающим.

2021-06-22 10:59 UTC, T6751 requested changes
> ну что решили 

Насколько понимаю из того, что было сказано ранее: либо перенести данные трейты в 
функционал предметов (например трейт КМа думаю спокойно можно было бы перенести в очки, например), либо `должен быть план и комплексное решение, обсуждение, а не в рамках одного ПРа и профы придумывать систему перков проф. Какие они еще могут быть, какое влияние могут оказывать, подходит ли это нам и какие проблемы могут возникнуть. То же самое что и со скилами, как эти перки разучивать при смене проф.`

Пока что нет ни того, ни другого

2021-06-22 14:19 UTC, Phoenix4O4 commented
> > ну что решили
> 
> Насколько понимаю из того, что было сказано ранее: либо перенести данные трейты в
> функционал предметов (например трейт КМа думаю спокойно можно было бы перенести в очки, например), либо `должен быть план и комплексное решение, обсуждение, а не в рамках одного ПРа и профы придумывать систему перков проф. Какие они еще могут быть, какое влияние могут оказывать, подходит ли это нам и какие проблемы могут возникнуть. То же самое что и со скилами, как эти перки разучивать при смене проф.`
> 
> Пока что нет ни того, ни другого

Да блин, просто обзови это не квирком а глазным чипом. Кибербанк

> ну что решили

Назови это чипом. Или сделай это в виде простецких имплантов/аугментаций.

2021-07-04 18:49 UTC, AndroBetel commented
переделаю функционал в импланты или ещё какие-нибудь штуки, да.

2021-07-04 18:49 UTC, closed without merging