Master2
TauCetiStation/TauCetiClassic pull request #7284
Opened 2021-06-04 00:40 UTC by Rahmanio

## Описание изменений
* Боксёрская груша больше не является мобом.
* Симплмобы не атакуют боксёрскую грушу.
* Боксёрскую грушу можно уничтожить.
* Минус: Боксёрскую грушу нельзя бить кулаками.

Ссылаюсь на ишью:
#7189
## Почему и что этот ПР улучшит
Споры блоба, пауки, культо-пилоны не будут атаковать боксёрские груши, мобы не будут беспомощными.
## Авторство
Rahmano
## Чеинжлог

2021-06-04 00:40 UTC, TauKitty commented
###### Changelog status: :radio_button: No changelog

2021-06-04 00:44 UTC, Motzord commented
> Боксерскую грушу нельзя бить кулаками.

Мне это не нравится, лучше вхардкодить исключение в ИИ мобов, чтобы они не реагировали на грушу, или дать груше, внезапно, какой нибудь уникальный faction, чтобы мобы не нападали на нее. В данный момент я считаю данный ПР костылем и есть более элегантный способ решения проблемы без выпила куска механа

2021-06-04 00:47 UTC, Rahmanio commented
> > Боксерскую грушу нельзя бить кулаками.
> 
> Мне это не нравится, лучше вхардкодить исключение в ИИ мобов, чтобы они не реагировали на грушу, или дать груше, внезапно, какой нибудь уникальный faction, чтобы мобы не нападали на нее. В данный момент я считаю данный ПР костылем и есть более элегантный способ решения проблемы без выпила куска механа

мобы нападают на всё живое, что не является их классом. Если хочешь исправить груши, исправь сам.

2021-06-04 00:52 UTC, Motzord commented
> > > Боксерскую грушу нельзя бить кулаками.
> > 
> > 
> > Мне это не нравится, лучше вхардкодить исключение в ИИ мобов, чтобы они не реагировали на грушу, или дать груше, внезапно, какой нибудь уникальный faction, чтобы мобы не нападали на нее. В данный момент я считаю данный ПР костылем и есть более элегантный способ решения проблемы без выпила куска механа
> 
> мобы нападают на всё живое, что не является их классом. Если хочешь исправить груши, исправь сам.

Залезь в код к мобам и поставь проверку на волшебный класс, который будет у груши.

2021-06-04 01:07 UTC, Sakuya-Izayoi commented
Зачем нужны груши если их нельзя будет бить? Проще тогда выпилить их.

> Споры блоба, пауки, культо-пилоны не будут атаковать боксёрские груши, мобы не будут беспомощными.

Это плохое решение проблемы.

2021-06-04 01:25 UTC, Rahmanio commented
> Зачем нужны груши если их нельзя будет бить? Проще тогда выпилить их.
> 
> > Споры блоба, пауки, культо-пилоны не будут атаковать боксёрские груши, мобы не будут беспомощными.
> 
> Это плохое решение проблемы.

Я тоже думал заменить груши на растения.


> Залезь в код к мобам и поставь проверку на волшебный класс, который будет у груши.

Если всё так просто, сделай сам, как сделаешь, закрою пул реквест сразу.

2021-06-04 02:51 UTC, Sakuya-Izayoi commented
Чтобы закрыть связанный ишью напиши в теле ПРа fixes #<номер>

2021-06-04 02:51 UTC, Sakuya-Izayoi commented on code/game/machinery/bots/pubag.dm
> +	color = list(rand(0, 255), rand(0, 255), rand(0, 255), 255)
```suggestion
	color = list(rand(0, 255), rand(0, 255), rand(0, 255), 255)

```

2021-06-04 02:51 UTC, Sakuya-Izayoi commented on code/game/machinery/bots/pubag.dm
> +/obj/machinery/bot/pubag
А почему это бот и вообще машинерия?

2021-06-04 10:05 UTC, volas commented
> Минус: Боксёрскую грушу нельзя бить кулаками.

груши делали мобами только из-за этого

2021-06-04 10:19 UTC, KIBORG04 commented
Как ещё один костыль: пропиши мобу-груше stat = DEAD. Мобы мёртвых не бьют

2021-06-04 11:21 UTC, LudwigVonChesterfield commented
Лично я за это изменение. Никто не пользуется грушами для теста боёвки больше, а багов от того что груши-мобы слишком много, и с тем как работает наш билд на данный момент на их фикс ушло бы слишком много времени (для фичи, которая опять же, не используется)

2021-06-04 11:22 UTC, LudwigVonChesterfield commented on code/game/machinery/bots/pubag.dm
> +/obj/machinery/bot/pubag
а почему бы не вернуть как было до того как я их сделал мобами... зачем вообще заново изобретать то что уже было?

2021-06-04 11:23 UTC, LudwigVonChesterfield requested changes
(теперь когда я глянул как именно он это сделал, а конкретно сделал новую безмеханновую грушу, вместо замены на то что было когда-то (где она хоть тряслась смешно когда ты по ней тыкаешь)) - то я против этой реализации, но я за изменение.

2021-06-05 07:46 UTC, Sakuya-Izayoi commented
> Если всё так просто, сделай сам, как сделаешь, закрою пул реквест сразу.
ревертни #5333

2021-06-08 02:07 UTC, Rahmanio commented
> > Если всё так просто, сделай сам, как сделаешь, закрою пул реквест сразу.
> 
> ревертни #5333

Да, я так и сделал, как мне добавить другую ветку в этот пул реквест?

2021-06-08 02:17 UTC, Rahmanio commented
> (теперь когда я глянул как именно он это сделал, а конкретно сделал новую безмеханновую грушу, вместо замены на то что было когда-то (где она хоть тряслась смешно когда ты по ней тыкаешь)) - то я против этой реализации, но я за изменение.

Исправился, удалил то говно, что накодил. Теперь там та груша, что была раньше.

2021-06-08 14:06 UTC, KIBORG04 commented on code/modules/sports/gym.dm
> +	//color = pick("#aaffaa", "#aaaaff", "#ff3030", "#ff1010", "#ffffff")
```suggestion
	color = pick("#aaffaa", "#aaaaff", "#ff3030", "#ff1010", "#ffffff")
```

2021-06-09 01:39 UTC, Rahmanio commented on code/modules/sports/gym.dm
> +	//color = pick("#aaffaa", "#aaaaff", "#ff3030", "#ff1010", "#ffffff")
вижу

2021-06-09 01:46 UTC, Rahmanio commented on code/game/machinery/bots/pubag.dm
> +	color = list(rand(0, 255), rand(0, 255), rand(0, 255), 255)
файл удалён

2021-06-09 01:47 UTC, Rahmanio commented on code/game/machinery/bots/pubag.dm
> +/obj/machinery/bot/pubag
файл удалён

2021-06-13 13:45 UTC, Rahmanio commented
Считаю этот пр недействительным.

2021-06-13 13:45 UTC, closed without merging