Adds minHeight and minWidth props to Window layout
TauCetiStation/TauCetiClassic pull request #7298
Opened 2021-06-06 15:25 UTC by 4310V343k

## Описание изменений
Title
## Почему и что этот ПР улучшит
Временная замена отсутствия пропа resizable, во избежание вот [таких](https://user-images.githubusercontent.com/56449763/120930088-790ac180-c6f4-11eb-98bd-eba97b142430.png) проблем

## Авторство
remindme

2021-06-06 15:25 UTC, TauKitty commented
###### Changelog status: :radio_button: No changelog

2021-06-07 06:01 UTC, Phoenix4O4 commented
Так это не проблема, зачем ты сам делаешь себе такой маленький интерфейс?

2021-06-07 14:55 UTC, KIBORG04 commented
Чел выше вроде все по факту сказал

2021-06-09 13:08 UTC, T6751 requested changes
См. комментарий от Phoenix4O4

2021-06-09 13:08 UTC, closed without merging