em pulse no longer opening doors
TauCetiStation/TauCetiClassic pull request #7311
Opened 2021-06-07 09:35 UTC by Sakuya-Izayoi

## Описание изменений
Теперь при ЭМИ пульсируются рандомные проводки у шлюзов.

## Почему и что этот ПР улучшит

## Авторство

## Чеинжлог
:cl: Getup1
- tweak: Изменено воздействие ЭМИ на двери.

2021-06-07 09:35 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2021-06-07 10:01 UTC, KIBORG04 commented
> tweak: Изменено воздействие ЭМИ на двери.

А конкретно как?

2021-06-07 10:02 UTC, KIBORG04 commented on code/game/machinery/doors/airlock.dm
> +		if(!prob(50/severity))
```suggestion
		if(!prob(50 / severity))
```

2021-06-07 10:08 UTC, Sakuya-Izayoi commented
> > tweak: Изменено воздействие ЭМИ на двери.
> 
> А конкретно как?

слишком много писать, но я попробую

2021-06-07 10:15 UTC, KIBORG04 commented on code/game/machinery/doors/airlock.dm
> +		var/wire = 1 << rand(0, wires.wire_count)
```suggestion
		var/wire = 1 << rand(0, wires.wire_count - 1)
```
Нужно на единицу меньше, ведь у нас 0 включителен же

2021-06-07 10:22 UTC, Sakuya-Izayoi commented on code/game/machinery/doors/airlock.dm
> +		var/wire = 1 << rand(0, wires.wire_count)
да, все правильно, от нуля включительно доwires.wire_count - 1 включительно , так ведь? dc662bb

2021-06-07 11:00 UTC, KIBORG04 commented on code/game/machinery/doors/airlock.dm
> +		var/wire = 1 << rand(0, wires.wire_count)
ну, 1 << 12 - это уже 2^12, когда таблица от 2^0 до 2^11

![image](https://user-images.githubusercontent.com/26389417/121005612-aa3ccd80-c798-11eb-82ad-39ae04ca1b80.png)

2021-06-07 11:02 UTC, LudwigVonChesterfield commented on code/game/machinery/doors/door.dm
> +	if(istype(src,/obj/machinery/door/window))
I see you're a man of culture?

а почему это нельзя вынести полиморфизмом?

2021-06-07 11:02 UTC, LudwigVonChesterfield commented on code/game/machinery/doors/door.dm
> +	if(istype(src,/obj/machinery/door/window))
ах, потому-что это было и до этого, видимо

2021-06-07 11:10 UTC, LudwigVonChesterfield commented
> tweak: Изменено воздействие ЭМИ на двери. Теперь при ЭМИ пульсируются случайные необрезанные провода.

--->

tweak: При ЭМИ у шлюзов пульсируются случайные необрезанные провода.

2021-06-07 11:15 UTC, Sakuya-Izayoi commented on code/game/machinery/doors/airlock.dm
> +		var/wire = 1 << rand(0, wires.wire_count)
да-да-да-да

2021-06-07 11:16 UTC, Sakuya-Izayoi commented on code/game/machinery/doors/door.dm
> +	if(istype(src,/obj/machinery/door/window))
да, так и было, менять не хочу потому что не в рамках этого пра

2021-06-10 13:06 UTC, T6751 requested changes
Внутри ```/obj/machinery/door/emp_act()``` **теперь** нет ничего, что выполнится для собственно ```/obj/machinery/door```

Поэтому сделай так, пожалуста:
```
/obj/machinery/door/window/emp_act(severity)
	if(prob(20/severity))
		open()
	if(prob(40/severity))
		if(secondsElectrified == 0)
			secondsElectrified = -1
			diag_hud_set_electrified()
			spawn(300)
				secondsElectrified = 0
				diag_hud_set_electrified()
	..()
```

2021-06-10 13:18 UTC, T6751 approved these changes

2021-06-11 15:10 UTC, merged