Замена цифр, anchored edition.
TauCetiStation/TauCetiClassic pull request #7318
Opened 2021-06-08 15:44 UTC by Phoenix4O4

## Описание изменений
Пофикшен анчоред, убраны точки. Все приведено к виду TRUE/FALSE

fixes #6685
## Почему и что этот ПР улучшит

## Авторство

## Чеинжлог

2021-06-08 15:44 UTC, TauKitty commented
###### Changelog status: :radio_button: No changelog

2021-06-08 15:59 UTC, KIBORG04 commented
ты че-то сломал

2021-06-08 16:03 UTC, Phoenix4O4 commented
> ты че-то сломал
Да есть чутка, поправлю чуть позже и отпишу как все будет ок.

2021-06-08 16:23 UTC, Phoenix4O4 commented
> ты че-то сломал

Поправил, рантаймов нет.

2021-06-09 13:05 UTC, T6751 requested changes
В файлах карт это не нужно.
Можешь убрать изменения .dmm?

2021-06-09 13:56 UTC, T6751 approved these changes

2021-06-11 13:19 UTC, merged