удаляет сообщение при открытии атмосферных створок.
TauCetiStation/TauCetiClassic pull request #7322
Opened 2021-06-08 20:20 UTC by AndroBetel

## Описание изменений
удаляет глупое сообщение которое всплывает когда пытаешься открыть атмосферную створку - ни со стороны логики, ни со стороны геймдизайна непонятно, зачем это нужно.
## Почему и что этот ПР улучшит
удобство - не придётся ловить вылетающие в лицо окна и жать кнопки во время опасной ситуации.
## Авторство

## Чеинжлог
:cl:
- tweak: Удалено сообщение, всплывающее при открытии атмосферных створок.

2021-06-08 20:20 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2021-06-08 20:22 UTC, KIBORG04 commented on code/game/machinery/doors/firedoor.dm
> -	if(user.incapacitated() || (get_dist(src, user) > 1  && !isAI(user)))
Мне кажется дохлые смогут открыть

2021-06-08 20:23 UTC, BeebBeebBoob commented
Советую настроить на кнопку Enter для открытия при окне чтобы не брать целую мышку в руки и нажимать на кнопку да.
Ещё есть баг что если закрыть окно(через кнопку X как у других программ) то он не только закрывается но и открывает створку.

2021-06-08 20:29 UTC, AndroBetel commented on code/game/machinery/doors/firedoor.dm
> -	if(user.incapacitated() || (get_dist(src, user) > 1  && !isAI(user)))
не могут, я думаю, оно уже учтено в attack_hand

2021-06-09 07:43 UTC, seekin4u commented
> > Советую настроить на кнопку Enter для открытия при окне чтобы не брать целую мышку в руки и нажимать на кнопку да.
> > Ещё есть баг что если закрыть окно(через кнопку X как у других программ) то он не только закрывается но и открывает створ
> 
> TAB - выбрать вариант
> Пробел - принять( ENTER)

Если подскажешь доступную клаву, где ТАБ рядом с энтером, то тебе все космонавтики будут благодарны.
Зачем делать 2 нажатия кнопок, если можно одно?

2021-06-09 07:46 UTC, KIBORG04 commented
Там ещё пробел вместо энтера можно нажать. В итоге можно абузить таб-спейс

2021-06-09 08:01 UTC, volas commented
> непонятно, зачем это нужно

скорее всего одна из попыток затормозить распространение разгерм и пожаров ассистентами. Вот сделай ты обещанный (у меня зафиксировано скрином) #6990, можно было бы вернуть наглядные окна и алерт был бы не так нужен.

2021-06-09 16:01 UTC, Sakuya-Izayoi commented
можно сделать хоть какой-нибудь полсекундный дуафтер чтобы мисскликом не открывались/закрывались створки?

2021-06-09 16:11 UTC, notkripton commented
> TAB - выбрать вариант
> Пробел - принять( ENTER)

Так можно просто ентер кликать без таба и мыши и оно откроется

2021-06-19 09:39 UTC, T6751 commented
Может сделать открытие/закрытие створок на ктрл клик или альт клик, чтобы избежать мискликов?

А так думаю алерт стоит убрать, но оставить для случаев, если в комнатах разница давлений или пожар

2021-06-19 09:50 UTC, T6751 requested changes
Алерт стоит оставить для случаев, если в комнатах разница давлений или пожар

2021-06-19 19:59 UTC, AndroBetel commented
а какая разница, если такие створки может открывать только инженер, а не любой рандом?

2021-06-19 20:14 UTC, T6751 commented
> а какая разница, если такие створки может открывать только инженер, а не любой рандом?

Чтобы предупредить инженера, что открывая такую створку, может возникнуть резкий перепад давлений или же температур, чем если бы это створка была просто активирована вручную и никакой проблемы не было?

2021-06-19 20:28 UTC, AndroBetel commented
она его предупреждает сверканием лампочек на ней и при экзамине видно что там происхоидт

2021-06-22 08:54 UTC, T6751 approved these changes
Принято решение смержить

2021-06-22 08:57 UTC, merged