Spiderling bugfix and some features
TauCetiStation/TauCetiClassic pull request #7369
Opened 2021-06-14 21:56 UTC by Rahmanio

## Описание изменений
* Паучата теперь полноценные мобы.
* Добавлены статы мобов.
## Почему и что этот ПР улучшит
fixes #7345
## Авторство
Rahmano
## Чеинжлог
:cl:
* bugfix: Раньше паучат нельзя было бить кулаками и не проигрывалась анимация удара, теперь данные действия можно выполнять.
* add: Теперь паучата умирают без кислорода или при высокой температуре.

2021-06-14 21:56 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2021-06-14 22:01 UTC, Rahmanio commented
Уточняю, Свойства паучат те же, я добавил прок на проверку и удаление их тела, там добавляется их жижа spiderling_remains, которую можно убрать мылом.

2021-06-14 23:14 UTC, AndroBetel commented
а зачем переделывать описание и название жижи?

2021-06-14 23:59 UTC, Rahmanio commented
> а зачем переделывать описание и название жижи?

Название я не менял, а вот описание перепутал с другой штукой.

2021-06-15 00:09 UTC, AndroBetel commented
/obj/effect/decal/cleanable/spiderling_remains	 
-	name = "spiderling remains"
+	name = "Spiderling remains"

2021-06-15 00:14 UTC, Rahmanio commented
> /obj/effect/decal/cleanable/spiderling_remains
> 
> * name = "spiderling remains"
> 
> * name = "Spiderling remains"

Это не меняет сути имени, мне показалось так оно выглядит лучше

2021-06-15 13:08 UTC, KIBORG04 commented
That's Spiderling remains.

You attack the Spiderling remains.

Короче нет, ловеркейс уместен

2021-06-15 13:09 UTC, KIBORG04 commented on code/modules/events/infestation.dm
> +	layer = 2.7
Пропиши леер в дефайне

2021-06-15 13:10 UTC, KIBORG04 commented on code/modules/events/infestation.dm
> +	health = 2
нужна еще переменная max_health = 2

2021-06-15 13:10 UTC, KIBORG04 commented on code/modules/events/infestation.dm
> +		src.loc = user.loc
```suggestion
		loc = user.loc
```

2021-06-15 13:11 UTC, KIBORG04 commented on code/modules/events/infestation.dm
> +/mob/living/simple_animal/friendly/spiderling/proc/die()
Есть специальный прок death

2021-06-15 13:12 UTC, KIBORG04 commented on code/modules/events/infestation.dm
> +		die()
Че, рекурсивная смэрть?

2021-06-15 13:12 UTC, KIBORG04 commented on code/modules/events/infestation.dm
> +		if(istype(src.loc, /turf))
```suggestion
		if(istype(loc, /turf))
```

2021-06-15 13:12 UTC, KIBORG04 commented on code/modules/events/infestation.dm
> +				visible_message("<B>[src] scrambles into the ventillation ducts!</B>")*/
```suggestion
```

2021-06-15 13:13 UTC, KIBORG04 commented on code/modules/events/infestation.dm
> +/mob/living/simple_animal/friendly/spiderling/process()
```suggestion
/mob/living/simple_animal/friendly/spiderling/Life()
```

2021-06-15 13:16 UTC, KIBORG04 commented on code/modules/events/infestation.dm
> +		qdel(src)
```suggestion
```

2021-06-15 13:16 UTC, KIBORG04 commented on code/modules/events/infestation.dm
> +		var/spawn_type = /obj/effect/decal/cleanable/spiderling_remains //changing body of animal to cleanable object
Это можно пихнуть в деатх или дестрой

2021-06-15 13:17 UTC, KIBORG04 commented on code/modules/events/infestation.dm
> +			spawn(rand(20,60))
убери спавны

2021-06-15 13:18 UTC, KIBORG04 requested changes
Короче щас очень странно выглядит ИИ паучка, че он делает, так же проки не те юзаются, про спавны я уже молчу. Пока не очень хочется данное мержить

2021-06-15 13:38 UTC, Rahmanio commented on code/modules/events/infestation.dm
> +	layer = 2.7
#define VERM_MICE 0
#define VERM_LIZARDS 1
#define VERM_SPIDERS 2
#define layer = FALSE
Вот так?

2021-06-15 13:43 UTC, Rahmanio commented on code/modules/events/infestation.dm
> +		die()
это ошибка

2021-06-15 13:53 UTC, Rahmanio commented on code/modules/events/infestation.dm
> +		qdel(src)
Без этого не будет на его месте появляться жижа, сейчас исправлю все косяки.

2021-06-15 13:56 UTC, Rahmanio commented on code/modules/events/infestation.dm
> +		var/spawn_type = /obj/effect/decal/cleanable/spiderling_remains //changing body of animal to cleanable object
Так и сделаю

2021-06-15 13:57 UTC, Rahmanio commented on code/modules/events/infestation.dm
> +			spawn(rand(20,60))
они использовались и раньше, на что их можно заменить?

2021-06-15 14:07 UTC, KIBORG04 commented on code/modules/events/infestation.dm
> +	layer = 2.7
нет, есть BELOW_CONTAINERS_LAYER

2021-06-15 14:08 UTC, KIBORG04 commented on code/modules/events/infestation.dm
> +			spawn(rand(20,60))
Посмори в код конвенции про это

2021-06-15 18:51 UTC, Rahmanio commented on code/modules/events/infestation.dm
> +			spawn(rand(20,60))
> Посмори в код конвенции про это

тогда откуда взялся спавн в спайдерлингах, ладно буду исправлять

2021-06-16 13:53 UTC, Rahmanio commented
> Короче щас очень странно выглядит ИИ паучка, че он делает, так же проки не те юзаются, про спавны я уже молчу. Пока не очень хочется данное мержить

Всё было исправлено, кроме Spawn, мне не хватит скилла это переделать в аналогичную конструкцию без Spawn. Сам я спавн бы не стал использовать из-за договорённости о коде, он был использован ещё до меня.

2021-06-16 13:56 UTC, Sakuya-Izayoi commented
> > Короче щас очень странно выглядит ИИ паучка, че он делает, так же проки не те юзаются, про спавны я уже молчу. Пока не очень хочется данное мержить
> 
> Всё было исправлено, кроме Spawn, мне не хватит скилла это переделать в аналогичную конструкцию без Spawn. Сам я спавн бы не стал использовать из-за договорённости о коде, он был использован ещё до меня.

просто все что после спавна выносишь в отдельный прок, а прок вызываешь через addtimer

2021-06-16 16:37 UTC, KIBORG04 commented on code/modules/events/infestation.dm
> +			spawn(rand(20,60))
Как бы тебе написать... Это было до каких-то четких правил кодирования сосак

2021-06-16 18:34 UTC, Rahmanio commented on code/modules/events/infestation.dm
> +			spawn(rand(20,60))
Спавны убраны

2021-06-17 10:24 UTC, KIBORG04 commented
> bugfix: Раньше паучат нельзя было бить кулаками и не проигрывалась анимация удара, теперь данные действия можно выполнять.

Перепиши без части с раньше и без "теперь".

2021-06-17 10:26 UTC, KIBORG04 commented on code/modules/events/infestation.dm
> +/mob/living/simple_animal/friendly/spiderling
Мм, а подтип `/mob/living/simple_animal/friendly` ты не забыл добавить(не добавляй, просто сделай /mob/living/simple_animal/spiderling?

А еще по какой причине это лежит не в отдельном файле, а в ивентах?

2021-06-17 10:31 UTC, KIBORG04 commented on code/modules/events/infestation.dm
> +	anchored = FALSE
```suggestion
```
оно и так поидее фолс

2021-06-17 10:33 UTC, KIBORG04 commented on code/modules/events/infestation.dm
> +		amount_grown = 1
Это тоже перенеси в лайф, но убери начало процессинга

2021-06-17 10:34 UTC, KIBORG04 commented on code/modules/events/infestation.dm
> +		..()
```suggestion
```
> pass_flags = PASSTABLE | PASSMOB

2021-06-17 10:35 UTC, Rahmanio commented on code/modules/events/infestation.dm
> +/mob/living/simple_animal/friendly/spiderling
> Мм, а подтип `/mob/living/simple_animal/friendly` ты не забыл добавить(не добавляй, просто сделай /mob/living/simple_animal/spiderling?
> 
> А еще по какой причине это лежит не в отдельном файле, а в ивентах?

Потому что спайдерлинги более нигде не используются, до этого они вообще лежали в декалях.
/mob/living/simple_animal/friendly/spiderling, так и должно быть

2021-06-17 10:35 UTC, KIBORG04 commented on code/modules/events/infestation.dm
> +		new spawn_type(src.loc)
```suggestion
		var/spawn_type =  //changing body of animal to cleanable object
		new /obj/effect/decal/cleanable/spiderling_remains(loc)
```

2021-06-17 10:36 UTC, KIBORG04 commented on code/modules/events/infestation.dm
> +/mob/living/simple_animal/friendly/spiderling
> до этого они вообще лежали в декалях

Какая разница где они до этого лежали? Создавай давай файл.

> /mob/living/simple_animal/friendly/spiderling, так и должно быть

Так не должно быть.

2021-06-17 10:37 UTC, KIBORG04 commented on code/modules/events/infestation.dm
> +	if(health <= 0)
```suggestion
```
Да, паук умирает и мы проверяем хп..

2021-06-17 10:38 UTC, KIBORG04 commented on code/modules/events/infestation.dm
> +		if(istype(loc, /turf))
```suggestion
		if(isturf(loc))
```

2021-06-17 10:40 UTC, KIBORG04 requested changes

2021-06-17 10:40 UTC, KIBORG04 commented on code/modules/events/infestation.dm
> +	//=================
![image](https://user-images.githubusercontent.com/26389417/122381400-8d12b680-cf71-11eb-8a0e-6afa98130979.png)

Прочитай опять конвенцию, а конкретно опять про пункт замены спавна на таймеры и асинки

2021-06-17 14:08 UTC, Rahmanio commented
Если кому надо будет, он сам это сделает, мне лично это не кажется такой огромной проблемой.

2021-06-17 14:08 UTC, closed without merging

2021-06-17 14:12 UTC, KIBORG04 commented
Ты же вроде и начал это делать. А оставалось совсем не много..