Ai camera spam and displayed text
TauCetiStation/TauCetiClassic pull request #7375
Opened 2021-06-15 13:23 UTC by Rahmanio

## Описание изменений
* При показе бумаги в камеру, теперь отображается правильный вид бумаги со всеми печатями.
* Спам бумагой в камеру ИИ урезан.
* Убрана возможность показывать PDA в камеру ИИ.
## Почему и что этот ПР улучшит
fixes #7329
## Авторство
Rahmano
## Чеинжлог
:cl: Rahmano
* bugfix: Теперь при показе бумаги в камеру, ИИ увидит её правильный вид, со всеми печатями.
* bugfix: Теперь нельзя массово спамить бумагой в камеру ИИ.
* del: Удалена возможность показать PDA в камеру ИИ.

2021-06-15 13:23 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2021-06-15 13:34 UTC, Rahmanio commented
Хотел сделать, чтобы ИИ открывал показанную бумажку через чат, но скилла не хватило. Пока решил пофиксить так, надеюсь потом кто-то более крутой сделает эту фичу с выведением ссылки в чат на бумагу.

2021-06-15 14:19 UTC, 4310V343k commented
sleep(9) is sus

2021-06-15 14:24 UTC, 4310V343k requested changes

2021-06-15 14:24 UTC, 4310V343k commented on code/game/machinery/camera/camera.dm
> +			sleep(9) //no spam
sus

2021-06-15 14:24 UTC, 4310V343k commented on code/game/machinery/camera/camera.dm
> +			sleep(9) //no spam
sus

2021-06-15 14:24 UTC, 4310V343k commented on code/game/machinery/camera/camera.dm
>  		var/obj/item/weapon/paper/X = null
Перенеси переменную под if

2021-06-15 14:24 UTC, 4310V343k commented on code/game/machinery/camera/camera.dm
> +			to_chat(user, "<span class='notice'>You slowly holding up paper to the camera.</span>")
```suggestion
```

2021-06-15 14:24 UTC, 4310V343k commented on code/game/machinery/camera/camera.dm
> +			to_chat(U, "You hold paper up to the camera...")
```suggestion
			to_chat(U, "You hold \the [X] up to the camera...")
```

2021-06-15 14:24 UTC, 4310V343k commented on code/game/machinery/camera/camera.dm
> -		for(var/mob/O in player_list)
Выпил фичи

2021-06-15 14:26 UTC, 4310V343k commented on code/game/machinery/camera/camera.dm
> +	else if((istype(W, /obj/item/weapon/paper) && isliving(user)))
Я не уверен, нужен ли тут `isliving(user)`, ведь переменная и так `mob/living`

2021-06-15 14:29 UTC, 4310V343k requested changes

2021-06-15 14:29 UTC, 4310V343k commented on code/game/machinery/camera/camera.dm
>  		if(istype(W, /obj/item/weapon/paper))
always true

2021-06-15 14:29 UTC, 4310V343k commented on code/game/machinery/camera/camera.dm
>  		var/mob/living/U = user
Это точно лишнее

2021-06-15 14:29 UTC, 4310V343k commented on code/game/machinery/camera/camera.dm
> +			if(tgui_alert(user, "Would you like to hold up paper to the camera?","Let AI see your text!", list("Yes!","No!")) != "Yes!")
```suggestion
			if(tgui_alert(user, "Would you like to hold up paper to the camera?", "Let AI see your text!", list("Yes!","No!")) != "Yes!")
```

2021-06-15 15:03 UTC, Rahmanio commented
> sleep(9) is sus

Это как раз, одно из средств для уничтожения спама, если не нравится, зайди на локалку и проверь как это работает.

2021-06-15 15:04 UTC, KIBORG04 commented
Это реально сус. Сделай кд

2021-06-15 15:05 UTC, 4310V343k commented
> > sleep(9) is sus
> 
> Это как раз, одно из средств для уничтожения спама, если не нравится, зайди на локалку и проверь как это работает.

Плохое средство. Ты просто задерживаешь на 2 секунды, но количество нажатий остаётся неизменным

2021-06-15 15:36 UTC, Rahmanio commented on code/game/machinery/camera/camera.dm
> +			to_chat(U, "You hold paper up to the camera...")
В любом случае это бумага, это универсальное решение, тем более длинные названия очень плохо смотрятся.

2021-06-15 15:36 UTC, Rahmanio commented
> Это реально сус. Сделай кд

Сделал КД, теперь всё как надо.

2021-06-15 15:43 UTC, KIBORG04 commented on code/game/machinery/camera/camera.dm
> +			if(tgui_alert(user, "Would you like to hold up paper to the camera?","Let AI see your text!", list("Yes!","No!")) != "Yes!")
Важное мнение по пробелу от киборга: он нужен

2021-06-15 15:52 UTC, 4310V343k commented
ну почти как надо.

2021-06-17 10:56 UTC, KIBORG04 commented on code/game/machinery/camera/camera.dm
> +				return
```suggestion
				return
```

2021-06-17 13:35 UTC, KIBORG04 commented
https://github.com/TauCetiStation/TauCetiClassic/pull/7376 
получше будет

2021-06-17 13:35 UTC, closed without merging