you can't show PDAs to cameras now
TauCetiStation/TauCetiClassic pull request #7376
Opened 2021-06-15 16:09 UTC by 4310V343k

## Описание изменений
КД на показывание бумаги, алерт при показывании бумаги, всё ради ИИшек
Небольшой клинап, это было месиво
Вместо `popup.open()` теперь `show_content()`, чинит отображение бумаг
Люди на камерах теперь могут увидеть бумагу, показываемую в активную камеру
## Почему и что этот ПР улучшит
QoL of AI
читабельность кода(надеюсь)
## Авторство
remind me
## Чеинжлог
:cl: Remind me
 - fix: При показе бумаги в камеру бумага выглядела очень некрасиво
 - add: При показе бумаги через камеру люди, смотрящие на эту камеру через консоль камер видят саму бумагу
 - del: Убрана возможность показывать ПДА через камеру. Это выглядело очень плохо

2021-06-15 16:09 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2021-06-15 18:23 UTC, Rahmanio requested changes

2021-06-15 18:23 UTC, Rahmanio commented on code/game/machinery/camera/camera.dm
> +		user.SetNextMove(CLICK_CD_INTERACT) // say no-no to spamming
У тебя кд при спаме 1 секунда, что разрешает спамить, поэтому ты не решил проблему.

2021-06-15 18:26 UTC, 4310V343k commented on code/game/machinery/camera/camera.dm
> +		user.SetNextMove(CLICK_CD_INTERACT) // say no-no to spamming
Раньше можно было делать 10 кликов/секунду, теперь чуть больше одного

2021-06-15 18:31 UTC, Rahmanio commented on code/game/machinery/camera/camera.dm
> +		user.SetNextMove(CLICK_CD_INTERACT) // say no-no to spamming
Сделей клик раз в 5 секунд, потому что двух людей хватит, чтобы устроить массовый спам

2021-06-16 17:17 UTC, KIBORG04 commented on code/game/machinery/camera/camera.dm
> +		if(tgui_alert(user, "Would you like to hold up \the [P] to the camera?", "Let AI see your text!", list("Yes!","No!")) != "Yes!")
```suggestion
		if(tgui_alert(user, "Would you like to hold up \the [P] to the camera?", "Let AI see your text!", list("Yes!", "No!")) != "Yes!")
```

2021-06-16 17:23 UTC, KIBORG04 commented on code/game/machinery/camera/camera.dm
> +				P.show_content(L, TRUE) // humans are not silicons, so we need to forceshow it
Так ведь не только только хуманы могут же смотреть в камеры, то есть силикон поймет текст на картинке

2021-06-16 17:33 UTC, 4310V343k commented on code/game/machinery/camera/camera.dm
> +				P.show_content(L, TRUE) // humans are not silicons, so we need to forceshow it
Ну да, в этом и смысл...

2021-06-17 10:57 UTC, KIBORG04 commented on code/game/machinery/camera/camera.dm
> +			return
```suggestion
			return
```

2021-06-17 11:03 UTC, KIBORG04 commented on code/game/machinery/camera/camera.dm
> +		user.SetNextMove(3 SECONDS) // say no-no to spamming
Вообще, возможно было бы даже лучше сделать кд, как переменную в камере, где будет `world.time + CD`.
А уже потом сравнивать что `world.time > CD`

2021-06-17 11:42 UTC, 4310V343k commented on code/game/machinery/camera/camera.dm
> +		user.SetNextMove(3 SECONDS) // say no-no to spamming
Согласен, сидеть в локе с невозможностью что-то нажимать три секунды это больно

2021-06-17 13:30 UTC, KIBORG04 commented on code/game/machinery/camera/camera.dm
> +		user.SetNextMove(CLICK_CD_INTERACT)
```suggestion
```

2021-06-17 13:31 UTC, KIBORG04 commented on code/game/machinery/camera/camera.dm
> +		user.SetNextMove(CLICK_CD_INTERACT)
А, не, все нормально

2021-06-17 13:35 UTC, merged