Ports [tgui list] from austation
TauCetiStation/TauCetiClassic pull request #7379
Opened 2021-06-15 17:58 UTC by Phoenix4O4

## Описание изменений
Обычные списки заменены на ТГУИ. Ошибки есть, знаю. Оно еще не до конца готово, буду дорабатывать. 
![image](https://user-images.githubusercontent.com/41524861/122100633-0d270800-ce1c-11eb-94e5-0b49a3d8c458.png)
![image](https://cdn.discordapp.com/attachments/401041759137693698/854416374365683762/Honeycam_2021-06-15_20-45-27.gif)
## Почему и что этот ПР улучшит
QoL
## Авторство
https://github.com/austation/austation/pull/3344
tgstation
## Чеинжлог
🆑 
 - add: Добавлены TGUI списки.

2021-06-15 17:58 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2021-06-15 18:01 UTC, KIBORG04 commented
Когда ПКМ на тгуи? Когда чат на тгуи? Когда панель справа на тгуи?

2021-06-15 18:01 UTC, Phoenix4O4 commented
> Когда ПКМ на тгуи? Когда чат на тгуи? Когда панель справа на тгуи?

Скоро

2021-06-15 18:02 UTC, KIBORG04 commented
Встречаются у людей проблемы, когда вместо ТГУИ у них белое окошко. У меня тоже такое бывает даже на локалке. Как я понял, один из ассетов ТГУИ могут не отправиться при каких-то случаях. Предлагаю это пофиксить до мержа этого

2021-06-15 18:04 UTC, KIBORG04 commented on code/__HELPERS/files.dm
> +		//var/choice = input(src,"Choose a file to access:","Download",null) as null|anything in choices
кгхм

2021-06-15 18:05 UTC, 4310V343k commented on code/__HELPERS/files.dm
> +		//austation begin -- tgui lists
Как раз для этого придуман Git - что бы не отмечать, что откуда ~спизжено~ портировано

2021-06-15 18:05 UTC, 4310V343k commented on code/__HELPERS/files.dm
> +		//var/choice = input(src,"Choose a file to access:","Download",null) as null|anything in choices
ты первее

2021-06-15 18:06 UTC, KIBORG04 commented
Кинь наверное в драфт, раз не доделал

2021-06-15 18:48 UTC, Phoenix4O4 commented
Да я написал бля что тут и ошибки и не готово, куда вы уже комментируете. Алло. Тут тупо спизжено чтобы работало, я еще сам не закончил а вы уже свое время проебываете.

2021-06-15 18:49 UTC, 4310V343k commented
Пробежали по изменениям только

2021-06-15 18:49 UTC, Phoenix4O4 commented on code/__HELPERS/files.dm
> +		//austation begin -- tgui lists
Это уберу, оставлено чтобы проще ориентироваться. Это не Ready To Merge

2021-06-16 17:47 UTC, Phoenix4O4 commented
Вообщем глянул, потестил, прибрал. Вроде норм работает. Единственное если сразу же после запуска сервера юзать, подлагивает, но это пока контроллеры не стартанут. Далее нормально. Если по коду претензий нет, можно бы на тестмердж.

2021-06-17 07:34 UTC, volas commented
У меня на локалке эти интерфейсы в бсод при шифт/ф5 и еще каких-то кнопках уходили

2021-06-17 10:27 UTC, Phoenix4O4 commented
> У меня на локалке эти интерфейсы в бсод при шифт/ф5 и еще каких-то кнопках уходили

Да, глянул. Есть такое. Поправлю на неделе.

2021-06-25 00:11 UTC, volas requested changes

2021-06-25 18:25 UTC, T6751 commented on code/modules/tgui/tgui_input_list.dm
> +/datum/tgui_list_input
Нужно ли также добавить `/datum/tgui_modal`, используемый в алертах?

2021-06-25 18:59 UTC, KIBORG04 reviewed
![image](https://user-images.githubusercontent.com/26389417/123472997-9dc1cd00-d600-11eb-9a40-61b07d8b5c9a.png)

No

2021-06-26 12:00 UTC, volas commented on code/modules/tgui/tgui_input_list.dm
> +/datum/tgui_list_input
Да, можно

2021-06-26 12:01 UTC, volas commented on code/modules/tgui/tgui_input_list.dm
> +/datum/tgui_list_input
Может лучше в отдельном PR-е, тк этот может не будет смержен если в TM-е не покажет себя хорошо

2021-06-26 12:05 UTC, volas approved these changes

2021-06-27 12:16 UTC, KIBORG04 commented
Ну, тогда ТМлю, раз непонятно как это вообще работает

2021-06-27 12:33 UTC, KIBORG04 commented
Конфликты

2021-06-27 12:35 UTC, T6751 commented
Конфликты делают бррр

2021-06-30 20:45 UTC, KIBORG04 commented
https://user-images.githubusercontent.com/26389417/124028730-02b06500-d9fd-11eb-9970-ddc9d0030118.mp4


https://user-images.githubusercontent.com/26389417/124028884-2ecbe600-d9fd-11eb-8a8a-d987c5c52fb0.mp4



Тут че-то странное происходит. Это просто я открыл и решил потыкать.

2021-07-02 21:08 UTC, T6751 commented
> Тут че-то странное происходит. Это просто я открыл и решил потыкать 

Исправлено

2021-07-02 21:50 UTC, merged

2021-07-02 22:02 UTC, KIBORG04 commented
Там не только про скролл. Там показывается выбранный элемент зеленым, прошлый элемент серым и когда наводишься мышкой тоже серым. Мне кажется, не нужно прошлый выделять

![image](https://user-images.githubusercontent.com/26389417/124332475-34aafe00-db9a-11eb-8adb-cc9f8bb9ba69.png)

2021-07-02 22:10 UTC, T6751 commented
> Там показывается выбранный элемент зеленым, прошлый элемент серым и когда наводишься мышкой тоже серым. 

Это я и имел ввиду под "скроллом"
Серым элементом выделялся элемент, к которому скроллить