Port [TGUI Cargo] from Vorestation
TauCetiStation/TauCetiClassic pull request #7381
Opened 2021-06-15 19:05 UTC by Phoenix4O4

## Описание изменений
Портированы TGUI интерфейсы.
Доска для записок.
Шахтерская машина делающая стаки и консоль плавилки.
Шахтерский вендомат.
Фотокопир (Теперь умеет копировать paper bundle)
Окошко создания вещей из simple sheet

Примеры:

[ ![image](https://user-images.githubusercontent.com/41524861/122102232-e4a00d80-ce1d-11eb-8d2a-6cdbc28161a9.png)]
![image](https://user-images.githubusercontent.com/41524861/122104150-08645300-ce20-11eb-8d1f-4ac6bd421463.png)
![image](https://user-images.githubusercontent.com/41524861/122104258-29c53f00-ce20-11eb-9ea4-1c041dc0e422.png)
![image](https://user-images.githubusercontent.com/41524861/122104354-43668680-ce20-11eb-9d07-4aad600def3f.png)
![image](https://user-images.githubusercontent.com/41524861/122104568-76a91580-ce20-11eb-969a-2403d51fb5ee.png)
![image](https://user-images.githubusercontent.com/41524861/122105010-f636e480-ce20-11eb-9187-c4c5b261881e.png)

## Почему и что этот ПР улучшит
TGUI, QoL
## Авторство
VoreStation, Paradise, tgstation
## Чеинжлог
:cl:
 - add: Добавлены TGUI интерфейсы для шахтерского вендомата, доски для записок, шахтерской консоли переработки и консоли стакера, меню создания из металла, фотокопировальной машины.
 - rscadd: Фотокопир научился снимать копии с пачки бумаги.
 - rscadd: На доску для записок теперь можно вешать фотографии.

2021-06-15 19:05 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2021-06-16 19:27 UTC, T6751 requested changes

2021-06-16 19:27 UTC, T6751 commented on code/game/objects/items/stacks/stack.dm
> +	var/list/data = ..()
```suggestion
	var/list/data = list()
```

2021-06-16 19:27 UTC, T6751 commented on code/game/objects/items/stacks/stack.dm
> +	var/list/data = ..()
```suggestion
	var/list/data = list()
```

2021-06-16 19:27 UTC, T6751 commented on code/game/objects/items/stacks/stack.dm
> +		usr << browse(null, "window=stack")
Если тгуи окно должно здесь закрываться, то это явно не тот прок
Если же теперь не нужно, чтобы оно закрывалось, то просто нужно убрать это

2021-06-16 19:27 UTC, T6751 commented on code/game/objects/structures/noticeboard.dm
>  	var/notices = 0
```notices = 0```, хотя в дальнейшем это используется как список, а не число.

И ещё проверь ```/obj/structure/noticeboard/anomaly```, в которой ```notices = 5``` и кажется бумажки не добавляются из атом_инита. 
```suggestion
	var/list/notices
```

2021-06-16 19:27 UTC, T6751 commented on code/modules/mining/machine_processing.dm
> +	src.machine = locate(/obj/machinery/mineral/processing_unit) in range(5, src)
```suggestion
	machine = locate(/obj/machinery/mineral/processing_unit) in range(5, src)
```

2021-06-16 19:27 UTC, T6751 commented on code/modules/mining/machine_processing.dm
> +		log_debug("Ore processing machine console at [src.x], [src.y], [src.z] could not find its machine!")
```suggestion
		log_debug("Ore processing machine console at [x], [y], [z] could not find its machine!")
```

2021-06-16 19:27 UTC, T6751 commented on code/modules/paperwork/paper_bundle.dm
> +//	var/amount = 0 //Amount of items clipped to the paper
Если не используется - Удалить
```suggestion
```

2021-06-16 19:27 UTC, T6751 commented on code/modules/paperwork/photocopier.dm
> +	data["has_toner"] =	!!toner
```suggestion
	data["has_toner"] = !!toner
```

2021-06-16 20:58 UTC, KIBORG04 commented on code/modules/paperwork/photocopier.dm
> +	data["has_toner"] =	!!toner
А зачем? Типо конвертация в бул?

2021-06-16 21:04 UTC, Phoenix4O4 commented on code/modules/paperwork/photocopier.dm
> +	data["has_toner"] =	!!toner
Да

2021-06-21 06:39 UTC, T6751 commented on code/game/objects/structures/noticeboard.dm
> +#define MAX_NOTICES	5
Нужно добавить в конец фаила ```#undef MAX_NOTICES```

2021-06-21 06:39 UTC, T6751 commented on code/modules/mining/equipment_locker.dm
> +#define EQUIPMENT(n, o, p) n = new /datum/data/mining_equipment(n, o, p)
Также нужно добавить `#undef` для этого

2021-06-21 06:39 UTC, T6751 commented on code/modules/paperwork/photocopier.dm
> +/obj/machinery/photocopier/attack_hand(mob/user as mob)
`Не должно быть конструкций типа var/ и as ...`
```suggestion
/obj/machinery/photocopier/attack_hand(mob/user)
```

2021-06-21 06:39 UTC, T6751 commented on code/modules/paperwork/photocopier.dm
> +	data["has_item"] = copyitem || has_buckled_mobs() // VOREStation Edit: Ass copying
has_buckled_mobs()
А это точно нужно и используется/работает ли?

2021-06-21 06:39 UTC, T6751 commented on code/modules/paperwork/paper_bundle.dm
> +	var/obj/item/weapon/paper/P = pages[1]
Оверлеи нормально работают?

2021-06-21 06:39 UTC, T6751 commented on code/modules/mining/equipment_locker.dm
> +			C.loc = src
```suggestion
			usr.drop_from_inventory(C, src)
```

2021-06-21 06:39 UTC, T6751 commented on code/modules/mining/machine_processing.dm
> +	var/list/static_data[0]
```suggestion
	var/list/static_data = list()
```

2021-06-21 06:39 UTC, T6751 commented on code/modules/mining/machine_processing.dm
> +			return FALSE
Здесь что-то не так...

2021-06-21 06:39 UTC, T6751 commented on code/modules/paperwork/paper_bundle.dm
> +	sheet.loc = src
```suggestion
	user.drop_from_inventory(sheet, src)
```

2021-06-21 06:39 UTC, T6751 commented on code/game/objects/structures/noticeboard.dm
> +	var/list/data = ..()
```suggestion
	var/list/data = list()
```

2021-06-21 09:17 UTC, Phoenix4O4 commented on code/modules/paperwork/paper_bundle.dm
> +	var/obj/item/weapon/paper/P = pages[1]
Нормально, проверял.

2021-06-21 09:19 UTC, Phoenix4O4 commented on code/modules/paperwork/photocopier.dm
> +	data["has_item"] = copyitem || has_buckled_mobs() // VOREStation Edit: Ass copying
Пардон, убрал.

2021-06-21 09:25 UTC, Phoenix4O4 commented on code/modules/mining/machine_processing.dm
> +			return FALSE
Поправил.

2021-06-21 09:26 UTC, Phoenix4O4 commented on code/modules/mining/equipment_locker.dm
> +#define EQUIPMENT(n, o, p) n = new /datum/data/mining_equipment(n, o, p)
Сделано

2021-06-21 09:26 UTC, Phoenix4O4 commented on code/game/objects/structures/noticeboard.dm
> +#define MAX_NOTICES	5
Сделано

2021-06-21 13:30 UTC, T6751 commented
Тестмерж

2021-06-23 08:37 UTC, BeebBeebBoob commented
Консоль на шахтёрской аванпосту для синхрона исследований сломался. Там только пустое окно

2021-06-23 11:01 UTC, T6751 commented
`Консоль на шахтёрской аванпосту для синхрона исследований сломался. Там только пустое окно`

А разве это не NanoUI?

2021-06-27 12:23 UTC, KIBORG04 commented
![image](https://user-images.githubusercontent.com/26389417/123544372-a5e24f80-d75b-11eb-99f8-2d9703fe398f.png)

Это в последнем коммите. Разве так надо?

2021-06-27 12:26 UTC, T6751 commented
> 
> 
> Это в предпоследнем коммите. Разве так надо?

https://github.com/TauCetiStation/TauCetiClassic/pull/7381#discussion_r652975763

Да, Феникс не исправил, что записки не спавнились на доске, а этим коммитом собственно исправление

2021-06-27 12:27 UTC, KIBORG04 commented
Я про другое. В первом бумажке `contents += P` заменен на `add_paper(P)`. Ниже же эти две штуки вместе стоят

2021-06-27 12:28 UTC, T6751 commented
> Я про другое. В первом бумажке contents += P заменен на add_paper(P). Ниже же эти две штуки вместе стоят

А, понял. Сейчас исправлю

2021-06-27 12:29 UTC, KIBORG04 commented on code/modules/mining/machine_processing.dm
> +		log_debug("Ore processing machine console at [src.x], [src.y], [src.z] could not find its machine!")
Зарезолвано но не исправлено.

2021-06-27 12:31 UTC, T6751 commented on code/modules/mining/machine_processing.dm
> +		log_debug("Ore processing machine console at [src.x], [src.y], [src.z] could not find its machine!")
Не, здесь исправлено же
![image](https://user-images.githubusercontent.com/66636084/123544596-b8a95400-d75c-11eb-9641-2c5996ce5a48.png)

2021-06-27 12:31 UTC, KIBORG04 commented on code/modules/mining/machine_processing.dm
> +		log_debug("Ore processing machine console at [src.x], [src.y], [src.z] could not find its machine!")
Бля, а чет странно, ладно

2021-06-27 12:32 UTC, merged