Port [TGUI Safe in Vault] from tgstation
TauCetiStation/TauCetiClassic pull request #7383
Opened 2021-06-16 12:05 UTC by Phoenix4O4

## Описание изменений
Интерфейс сейфа теперь на TGUI.
![Honeycam 2021-06-16 15-04-20](https://user-images.githubusercontent.com/41524861/122215693-2ed3ce00-ceb4-11eb-9efd-1678ffb11c84.gif)
![image](https://user-images.githubusercontent.com/41524861/122215096-86be0500-ceb3-11eb-8367-4beff4b3188e.png)
![image](https://user-images.githubusercontent.com/41524861/122215071-80c82400-ceb3-11eb-99ab-94ff197dc3cd.png)
Экзамайн открытого сейфа покажет вам комбинацию.
![image](https://user-images.githubusercontent.com/41524861/122215219-a2c1a680-ceb3-11eb-9198-236e996ef50d.png)

## Почему и что этот ПР улучшит
Больше интерфейсов на TGUI. QoL
## Авторство
tgstation
## Чеинжлог
:cl:
- add: Интерфейс сейфа из хранилища теперь на tgui.

2021-06-16 12:05 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2021-06-16 12:16 UTC, Phoenix4O4 commented
Нужно ли усложнить как на тг, что тумблеров может быть больше двух 🤔

2021-06-16 16:24 UTC, KIBORG04 commented on code/game/objects/items/weapons/storage/secure.dm
> +				if ((src.l_set == 0) && (length(src.code) == 5) && (!src.l_setshort) && (src.code != "ERROR"))
бля, а чел когда это кодил даже не стал задумываться где нужно и не нужно ставить `src.`, тупо везде где мог тыкнул

2021-06-16 16:25 UTC, KIBORG04 commented on code/game/objects/items/weapons/storage/secure.dm
> +				if ((src.l_set == 0) && (length(src.code) == 5) && (!src.l_setshort) && (src.code != "ERROR"))
Тип, раз уж это все попало в дифф, можешь убрать эти срки

2021-06-16 16:25 UTC, KIBORG04 commented on code/game/objects/items/weapons/storage/secure.dm
>  	return
```suggestion
	return TRUE
```

2021-06-16 16:25 UTC, KIBORG04 commented on code/game/objects/items/weapons/storage/secure.dm
> +	return
```suggestion
```

2021-06-16 16:26 UTC, KIBORG04 commented on code/game/objects/structures/safe.dm
> +	return
```suggestion
```

2021-06-16 16:27 UTC, KIBORG04 commented on code/game/objects/structures/safe.dm
> +		. = TRUE //no afterattack
```suggestion
```
Это поидее не для нашего билда. У нас все это работает через интент

2021-06-16 16:29 UTC, KIBORG04 commented on code/game/objects/structures/safe.dm
> +		return
```suggestion
		return FALSE
```

2021-06-16 16:29 UTC, KIBORG04 commented on code/game/objects/structures/safe.dm
> +		return
```suggestion
		return FALSE
```
или че тут

2021-06-16 16:30 UTC, KIBORG04 commented on code/game/objects/structures/safe.dm
> +				return
```suggestion
				return FALSE
```
Ну и дальше поставь пожалуйста фолсы

2021-06-16 16:33 UTC, KIBORG04 commented on code/game/objects/items/weapons/storage/secure.dm
> +		ui = new(user, src, "SecureSafe", name)
![image](https://user-images.githubusercontent.com/26389417/122258339-9bad8f00-ced9-11eb-8d06-4d50dc2d035e.png)

У тебя поидее тайтл меняется, а тут статичный. В ТГУИшках вроде тоже он не меняется.

2021-06-16 16:52 UTC, Phoenix4O4 commented on code/game/objects/items/weapons/storage/secure.dm
> +				if ((src.l_set == 0) && (length(src.code) == 5) && (!src.l_setshort) && (src.code != "ERROR"))
ремувнул src

2021-06-16 18:31 UTC, 4310V343k requested changes

2021-06-16 18:31 UTC, 4310V343k commented on code/game/objects/structures/safe.dm
> +			if(!I || !in_range(src, user))
```suggestion
			if(!I || !Adjacent(user))
```

2021-06-16 18:31 UTC, 4310V343k commented on code/game/objects/structures/safe.dm
> +			if(!I || !in_range(src, user))
Не буду изменять что бы избежать в конфликтов, но попрошу тут

2021-06-16 20:57 UTC, Phoenix4O4 commented
Глупый бот! Тут больше нет конфликтов

2021-06-17 10:11 UTC, KIBORG04 commented on code/game/objects/items/weapons/storage/secure.dm
> +				if ((digit == "R") && (src.emagged == 0) && (!src.l_setshort))
```suggestion
				if ((digit == "R") && (emagged == 0) && (!l_setshort))
```
Через срк прошли, чел даже наверное не знал что делают скобочки. Если не хочешь, можешь не делать

2021-06-17 10:13 UTC, KIBORG04 commented on code/game/objects/structures/safe.dm
> +				return
```suggestion
				return FALSE
```

2021-06-17 10:13 UTC, KIBORG04 commented on code/game/objects/structures/safe.dm
> +				return
```suggestion
				return FALSE
```

2021-06-17 10:13 UTC, KIBORG04 commented on code/game/objects/structures/safe.dm
> +				return
```suggestion
				return FALSE
```

2021-06-17 10:13 UTC, KIBORG04 commented on code/game/objects/structures/safe.dm
> +				return
```suggestion
				return FALSE
```

2021-06-17 10:13 UTC, KIBORG04 commented on code/game/objects/structures/safe.dm
> +				return
```suggestion
				return FALSE
```

2021-06-20 13:13 UTC, merged