Port [UI Resources Reload] from Paradise
TauCetiStation/TauCetiClassic pull request #7398
Opened 2021-06-17 01:29 UTC by Phoenix4O4

## Описание изменений
Добавляем кнопку, позволяющую юзеру перезагрузить свои UI ассеты.
## Почему и что этот ПР улучшит
Избавляемся от проблем с TGUI.
## Авторство
Paradise
## Чеинжлог
:cl:
- add: Во вкладку ООС добавлена кнопка перезагрузки TGUI/NanoUI ресурсов.

2021-06-17 01:29 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2021-06-17 08:35 UTC, T6751 requested changes
`Избавляемся от проблем с TGUI.`
Какую конкретно проблему решает этот ПР?

И были ли данные изменения протестированы? Вместо `cache` вероятно должно быть `sent_assets`
И еще у нас есть `/client/proc/reload_nanoui_resources()` который в данном случае вероятно нужно удалить,

2021-06-17 10:25 UTC, Phoenix4O4 commented
> `Избавляемся от проблем с TGUI.`
> Какую конкретно проблему решает этот ПР?
> 
> И были ли данные изменения протестированы? Вместо `cache` вероятно должно быть `sent_assets`
> И еще у нас есть `/client/proc/reload_nanoui_resources()` который в данном случае вероятно нужно удалить,

Поправил на sent_assets, и убрал прок. Вчера тестил с кешем, белых окон не было 🤔

2021-06-18 19:28 UTC, T6751 requested changes
И я сейчас посмотрел, тут оказывается была фича, что определенному игроку можно было перезагрузить ассеты через VV
(если удаляешь, то нужно ещё удалить ```code\datums\datumvars.dm:265```)

2021-06-18 19:28 UTC, T6751 commented on code/game/verbs/ooc.dm
> +	sent_assets = list()
Из-за того, что ```get_asset_datum``` стоит перед, а не после очистики ```sent_assets``` тгуи ассет не отправляется повторно и соответственно никакая проблема не решается
```suggestion
	// Clear the user's cache so they get resent.
	// This is not fully clearing their BYOND cache, just their assets sent from the server this round
	sent_assets = list()

	// Resend the resources
	var/datum/asset/nano_assets = get_asset_datum(/datum/asset/nanoui)
	var/datum/asset/tgui_assets = get_asset_datum(/datum/asset/simple/tgui)
```

2021-06-18 19:34 UTC, T6751 commented
Может стоит это объединить этот верб с ```fix UI```, чтобы игрокам было проще?

2021-06-23 19:45 UTC, T6751 approved these changes
"Fix UI" теперь перезагружает ресурсы, используемые NanoUI/TGUI, что в большинстве случаев должно помочь решить проблему белых окон

![fix_UI](https://user-images.githubusercontent.com/66636084/123158602-aeddd300-d474-11eb-99a5-15cb3c7e7dfd.gif)

2021-06-23 19:57 UTC, merged