Мезон-худы для шахтеров
TauCetiStation/TauCetiClassic pull request #7477
Opened 2021-06-29 12:30 UTC by Zickusable

## Описание изменений
Добавил возможность купить за ваучер шахтера худы геолога + мезонки. Прям как у шахтерского борга, только это один предмет для челокеков
![image](https://user-images.githubusercontent.com/76683966/123797188-5e94c400-d8ff-11eb-9a44-a71a8b47bffd.png)

## Почему и что этот ПР улучшит
Больше вариативности 
## Авторство

## Чеинжлог
:cl:
- rscadd: Мезон-худы для шахтеров за ваучер

2021-06-29 12:30 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2021-06-29 12:46 UTC, T6751 commented
Подожди. За ваучер? А почему не за очки в вендомате?
За ваучер сейчас шахтёру предлагаются вещи, значительно определяющие путь, которым он будет добывать. Очки по сравнению с ними выглядят ничтожно, как мне кажется

2021-06-29 13:01 UTC, Zickusable commented
Ваучер можно купить за поинты.
Самый профит брать риг за ваучер, кинетик (а лучше два) воровать с науч. аванпоста. Вот и весь путь.
Резонатор хуже кинетика абсолютно.
Бот просто тупенький.
Очечи будут очень полезны новичкам в обнаружении руд, мобов, пещер с гораздо большей безопасностью.
Вообще вкусовщина, но теперь я буду брать очечи вместо рига и тащить кинетики с научки ;)

2021-06-29 13:38 UTC, AndroBetel commented
признался в том что добавляет только для себя закрывайте пр

2021-06-29 13:59 UTC, Sakuya-Izayoi commented
Мне тоже нравятся эти очки, я бы их носил, но за ваучер это не то. Ваучер не для этого. Добавь в фабрикатор там или в данж.

2021-06-29 14:00 UTC, Sakuya-Izayoi commented on code/modules/mining/scanners.dm
> +	sightglassesmod = "meson"
Фильтр на глазах будет зелёный, а линзы оранжевые?

2021-06-29 14:23 UTC, KIBORG04 commented
Кстати, нужно будет еще воксам отдельно эти очки нарисовать. Где - хз. @Coiscin

2021-06-29 14:24 UTC, KIBORG04 commented on code/modules/mining/scanners.dm
> +	toggleable = 1
```suggestion
	toggleable = TRUE
```

2021-06-30 06:58 UTC, T6751 commented on code/modules/mining/scanners.dm
> +	sightglassesmod = "meson"
Zickusable, можешь попробовать подобрать оранжевую матрицу для этих мезонок, если такой ещё нет (Debug > Edit Color Matrix в помощь)

2021-06-30 07:34 UTC, KIBORG04 commented on code/modules/mining/scanners.dm
> +	sightglassesmod = "meson"
Худы роботеха уже с такой матрицей.

2021-07-01 15:20 UTC, KIBORG04 requested changes
![image](https://user-images.githubusercontent.com/26389417/124149095-ef52d780-da98-11eb-8d1d-a4c43f52f829.png)

Ты кроме того что спрайт на мобе не туда сунул и не с тем названием, так еще и воксам не нарисовал

2021-07-01 16:33 UTC, Zickusable commented
Там же лежит обычный геохуд, спрайт на моба, а у спрайта именно такое название _mob

2021-07-02 13:30 UTC, KIBORG04 commented on code/modules/clothing/glasses/glasses.dm
> +/obj/item/clothing/glasses/hud/geomeson
А зачем ты изменил тип этих очков то?

2021-07-02 16:38 UTC, Zickusable commented on code/modules/clothing/glasses/glasses.dm
> +/obj/item/clothing/glasses/hud/geomeson
Раз уж перенес спрайты от геохудов к мезонкам и тп, то и убрал какое-либо отношение к геохудам. Для меня органично, выглядит работающим и  менее запарно

2021-07-02 17:05 UTC, KIBORG04 commented on code/modules/clothing/glasses/glasses.dm
> +/obj/item/clothing/glasses/hud/geomeson
Че? Прошлый вариант был лучше во многом. Да и причем вообще спрайт и класс??

2021-07-06 15:10 UTC, KIBORG04 commented on code/modules/mining/scanners.dm
> +	item_state = "glasses"
```suggestion
	item_state = "glasses"
	icon_state = "mesonmininghud"
```

2021-07-06 15:11 UTC, KIBORG04 commented on code/modules/mining/mining_fabricator/mining_research.dm
> +	materials = list(MAT_METAL = 50, MAT_GLASS = 50,MAT_SILVER=20, MAT_GOLD=20)
к моменту получения серебра и золота они уже будут не нужны

2021-07-09 12:29 UTC, Zickusable commented on code/modules/mining/mining_fabricator/mining_research.dm
> +	materials = list(MAT_METAL = 50, MAT_GLASS = 50,MAT_SILVER=20, MAT_GOLD=20)
Не нужен будет - не сделают. Кинетик тоже не будет нужен, который крафтиться примерно так же. Очечи позволяют находить что надо быстро и легко, с возможностью избегания пещер и монстров, это жестко, как по мне.

2021-07-09 12:47 UTC, KIBORG04 commented on code/modules/mining/mining_fabricator/mining_research.dm
> +	materials = list(MAT_METAL = 50, MAT_GLASS = 50,MAT_SILVER=20, MAT_GOLD=20)
Они не позволяют видеть монстров, а кинетиков и так полно везде, а раз они уже изначально бесплатны, то зачем делать еще?

2021-07-09 14:28 UTC, KIBORG04 approved these changes
У меня остались вопросы только к цене

2021-07-09 17:06 UTC, Zickusable commented on code/modules/mining/mining_fabricator/mining_research.dm
> +	materials = list(MAT_METAL = 50, MAT_GLASS = 50,MAT_SILVER=20, MAT_GOLD=20)
С термалками вообще жирно будет.
Как бэ да, на ресерч аванпосте три или более штук, с ваучера еще +1. Подумав о том, что сам никогда не пользовался фабрикатором на шахтерке, понял, что и убрать можно золото или/и серебро из рецепта. Ориентировался на другие рецепты, когда добавлял. В общем, я не геймдизайнер, так что баланс вам видней.

2021-07-15 23:12 UTC, merged