правки перевода анонсов
TauCetiStation/TauCetiClassic pull request #7485
Opened 2021-06-30 23:44 UTC by AndroBetel

## Описание изменений
правит перевод анонсов с моим видением
накидаю комментов чтобы легче ревьювить
## Почему и что этот ПР улучшит
красоту
## Авторство

## Чеинжлог

2021-06-30 23:44 UTC, TauKitty commented
###### Changelog status: :radio_button: No changelog

2021-06-30 23:44 UTC, AndroBetel commented
ээ и добавьте тэг перевода спасибо

2021-06-30 23:45 UTC, AndroBetel commented on code/datums/announcements/station.dm
> -		message = "Обнаружена активация ядерной боеголовки в [initial(A.name)]. Кто-то пытается взорвать станцию!"
"Кто-то пытается" слишком неформально и не подходит для анонса имхо

2021-06-30 23:45 UTC, AndroBetel commented on code/datums/announcements/station.dm
> -	message = "Был аннулирован доступ на все технические туннели."
короткое и фактически неправильно, ведь доступ у нас даётся "в" а не "на"

2021-06-30 23:46 UTC, AndroBetel commented on code/datums/announcements/station.dm
> -	message = "Процедура смены экипажа начата. Шаттл вызван. Он прибудет через [shuttleminutes2text()]."
короткое некрасивое предложение а два таких существительных несколько засоряют восприятие

2021-06-30 23:46 UTC, AndroBetel commented on code/datums/announcements/station.dm
> -	message = "Шаттл был отозван."
короткое некрасивое ну и понятно по аналогии с эвакуационным сделал так

2021-06-30 23:47 UTC, AndroBetel commented on code/datums/announcements/station.dm
> -	message = "Шаттл Транспортировки Экипажа пристыковался к станции в соответствии с расписанием. Отправление примерно через [shuttleminutes2text()]."
сделал более "синтетически", но тут конечно сомнительно

2021-06-30 23:47 UTC, AndroBetel commented on code/datums/announcements/station.dm
> -	message = "Шаттл Транспортировки Экипажа покинул станцию. Он прибудет на Центральное Командование через несколько минут."
в/на украину, мне кажется всё таки лучше в

2021-06-30 23:47 UTC, AndroBetel commented on code/datums/announcements/station.dm
> -	message = "Эвакуационный Шаттл пристыковался к станции. У вас есть [shuttleminutes2text()] для посадки."
у меня есть? некрасиво

2021-06-30 23:49 UTC, AndroBetel commented on code/datums/announcements/station.dm
> -			"Служба безопасности может носить оружие на виду, однако, не следует вынимать его без необходимости. " + \
"однако" звучит слишком неформально и личностно, обезличил.
санкции вообще не подходит (или я тупой). меры это извиняюсь за каламбур полумеры, но без них предложение короткое и некрасивое

2021-06-30 23:49 UTC, AndroBetel commented on code/datums/announcements/station.dm
> -	message = "Механизм самоуничтожения деактивирован и над ситуацией был вернут частичный контроль. " + \
вернут некрасиво

2021-07-01 07:45 UTC, Zmey25 commented on code/datums/announcements/station.dm
> -		message = "Обнаружена активация ядерной боеголовки в [initial(A.name)]. Кто-то пытается взорвать станцию!"
Ну перевод же
>Перевод
>Someone trying to blow up the station!

Хотя я и согласен с твоим вариантом

2021-07-01 15:27 UTC, KIBORG04 commented on code/datums/announcements/station.dm
> -	message = "Шаттл Транспортировки Экипажа пристыковался к станции в соответствии с расписанием. Отправление примерно через [shuttleminutes2text()]."
Чет сомнительно. Шаттл два раза повторяется и как бы уже понятно, что отправится через 10 минут именно шаттл, а не блять самолёт.

~~ШТЭ (аббревиатура)~~

2021-07-01 15:27 UTC, KIBORG04 commented on code/datums/announcements/station.dm
> -	message = "Шаттл Транспортировки Экипажа покинул станцию. Он прибудет на Центральное Командование через несколько минут."
Но пишешь к

2021-07-01 15:28 UTC, KIBORG04 commented on code/datums/announcements/station.dm
> +	message = "Шаттл Транспортировки Экипажа покинул станцию. До стыковки шаттла к Центральному Командованию: [shuttleminutes2text()]."
Нигде не использовалась такая структура с `text: time`. Везде время пишется в тексте

2021-07-01 15:31 UTC, KIBORG04 commented on code/datums/announcements/station.dm
> -			"Служба безопасности может носить оружие на виду, однако, не следует вынимать его без необходимости. " + \
Тут санкции наверное о том, что в зеленый код могут тебя доставить в отделение и там уже смотреть. Ну или че-то подобное. В синий же код пишется, что щитсеки хоть в туалете могут тебя обыскать и им ничего для этого не нужно делать, в отличие от зеленого кода. ХЗ

2021-07-01 15:54 UTC, AndroBetel commented on code/datums/announcements/station.dm
> -			"Служба безопасности может носить оружие на виду, однако, не следует вынимать его без необходимости. " + \
тут санкции подразумевают под собой необходимость ордера

2021-07-01 15:54 UTC, AndroBetel commented on code/datums/announcements/station.dm
> -	message = "Шаттл Транспортировки Экипажа покинул станцию. Он прибудет на Центральное Командование через несколько минут."
eto mem

2021-07-02 07:23 UTC, volas commented on code/datums/announcements/station.dm
>  	name = "Alert: Nuke Activation"
а это у нас где-то еще переводится?

2021-07-02 07:23 UTC, volas commented on code/datums/announcements/station.dm
> +		message = "Обнаружена активация ядерной боеголовки в [initial(A.name)]. Происходит попытка уничтожения станции."
```suggestion
		message = "Обнаружена активация ядерной боеголовки в [initial(A.name)]. Станция может быть уничтожена."
```

"Происходит попытка" как-то тоже не очень. Если переносить посыл на русский, то как-то может так.

2021-07-02 07:23 UTC, volas commented on code/datums/announcements/station.dm
> +	message = "Требование доступа в технические тоннели было аннулировано."
```suggestion
	message = "Требование доступа в технические туннели было аннулировано."
```
У нас везде туннели.

2021-07-02 07:23 UTC, volas commented on code/datums/announcements/station.dm
>  /datum/announcement/station/maint_readd
Это тоже тогда нужно в стиле поправить на "в"

2021-07-02 07:23 UTC, volas commented on code/datums/announcements/station.dm
> +	message = "Шаттл Транспортировки Экипажа пристыковался к станции в соответствии с расписанием. Отправление шаттла через [shuttleminutes2text()]."
```suggestion
	message = "Шаттл Транспортировки Экипажа пристыковался к станции в соответствии с расписанием. Отправление через [shuttleminutes2text()]."
```
Согласен с Киборгом, но "примерно" тут правда наверно лишнее.

2021-07-02 07:23 UTC, volas commented on code/datums/announcements/station.dm
> +	message = "Шаттл Транспортировки Экипажа покинул станцию. До стыковки шаттла к Центральному Командованию: [shuttleminutes2text()]."
И тут тоже согласен с киборгом

2021-07-06 07:45 UTC, BesumniiChebureck requested changes
ИМХО крайне странные правки, а точнее переделывание ряда моментов под себя. Перевод понятен и выглядит неплохо - этого достаточно. Ты не убираешь ошибки, а просто переделываешь перевод так как тебе хочется.

2021-07-07 00:18 UTC, Haggerd commented on code/datums/announcements/station.dm
> +		message = "Обнаружена активация ядерной боеголовки в [initial(A.name)]. Происходит попытка уничтожения станции."
Йеп, вариант Воласа очень даже хорош.

2021-07-07 00:18 UTC, Haggerd commented on code/datums/announcements/station.dm
> -			"Служба безопасности может носить оружие на виду, однако, не следует вынимать его без необходимости. " + \
Однако, осталось другое "однако" при понижении кода до синего
`Служба безопасности не имеет права вынимать оружие, однако может носить его на виду.`
Можно заменить на 
`Служба безопасности не имеет права вынимать оружие, но при этом может носить его на виду.`

2021-07-09 17:53 UTC, pss88 commented on code/datums/announcements/station.dm
> -		message = "Обнаружена активация ядерной боеголовки в [initial(A.name)]. Кто-то пытается взорвать станцию!"
"Угроза уничтожения станции"

2021-07-09 17:55 UTC, pss88 commented on code/datums/announcements/station.dm
> +		message = "Обнаружена активация ядерной боеголовки в [initial(A.name)]. Происходит попытка уничтожения станции."
"Угроза уничтожения станции"

2021-07-17 16:07 UTC, LudwigVonChesterfield commented on code/datums/announcements/station.dm
> -		message = "Обнаружена активация ядерной боеголовки в [initial(A.name)]. Кто-то пытается взорвать станцию!"
"Целостность станции под угрозой."

2021-08-29 21:23 UTC, Fenriros approved these changes

2021-08-29 21:23 UTC, Fenriros commented on code/datums/announcements/station.dm
> -		message = "Обнаружена активация ядерной боеголовки в [initial(A.name)]. Кто-то пытается взорвать станцию!"
И Восклицательный знак поставить вместо точки =)

2021-09-03 13:14 UTC, atik1n approved these changes
Не понимаю чебурека, особенно про аннулирование **требования** доступа, а не самого доступа.
Looks good for me.

2022-01-06 19:35 UTC, Fenriros commented
Откройте?

2022-02-09 21:48 UTC, KIBORG04 commented
А зачем открыли?

2022-02-28 18:32 UTC, LudwigVonChesterfield commented on code/datums/announcements/station.dm
> +	message = "Процедура смены экипажа начата. Шаттл вызван и прибудет к станции через [shuttleminutes2text()]."
```suggestion
	message = "Процедура смены экипажа начата. Шаттл прибудет к станции через [shuttleminutes2text()]."
```

2022-02-28 18:32 UTC, LudwigVonChesterfield commented on code/datums/announcements/station.dm
> +	message = "Процедура смены экипажа начата. Шаттл вызван и прибудет к станции через [shuttleminutes2text()]."
"поезд двинулся и прибудет к станции в 8:00"

2022-02-28 18:35 UTC, closed without merging