Fix mining friendly mobs
TauCetiStation/TauCetiClassic pull request #7502
Opened 2021-07-04 01:31 UTC by Rahmanio

## Описание изменений
* Дружелюбные шахтёрские мобы не атакуют людей
## Почему и что этот ПР улучшит
* облегчит жизнь шахтёрам
fix #7450
## Авторство
Rahmano
## Чеинжлог
:cl: bugfix: Шахтёрские дружелюбные мобы более не атакуют людей.

2021-07-04 01:31 UTC, TauKitty commented
###### Changelog status: :x: Empty changelog (check markdown correctness)

2021-07-04 01:35 UTC, Rahmanio commented
В ходе теста всё исправлено, привёл френдли моба к голиафу, он стал бить не меня, а его:
![Screenshot_988](https://user-images.githubusercontent.com/67812445/124370478-fa685c00-dc80-11eb-90a8-ef43482148d2.png)
На мышей и груши так же не реагируют хостайл мобы:
![Screenshot_989](https://user-images.githubusercontent.com/67812445/124370479-fdfbe300-dc80-11eb-8545-a8aada3f2b86.png)

2021-07-04 07:18 UTC, kalazus commented
Только мобы и так не бьют мышей. А нападают они на хуманов так как у хуманов в #7359 появилась faction. Т.е. изменение других фракций бесполезно.

2021-07-04 12:28 UTC, Rahmanio commented
> Только мобы и так не бьют мышей. А нападают они на хуманов так как у хуманов в #7359 появилась faction. ~Т.е. изменение других фракций бесполезно.~ Покопал немного глубже, раньше людям автоматом наследовалась нейтральная фракция от /mob, вот и нейтральные мобы их не атаковали. Теперь я понял почему ты так сделал... Но лучше изменить сам перк friendly, изменяя attack_same (или давая им фракцию станции). Либо людям вернуть neutral, а мышам с pbag-ами дать фракцию untouchable или подобную (как ты сделал, но не 2 разные фракции).

Мобы били мышей и груши, для этого и нужен был прошлый фикс. Появилась фракция у людей, которая поломала френдли мобов, я её удалил. Untouchable lol, лучше уж мышь будет иметь свою фракцию, а груши свою, так намного лучше выглядит.

2021-07-04 13:24 UTC, KIBORG04 requested changes
kalazuc правильно написал, что лучше такие штуки, которые никто не должен бить, отнести в одну фракцию(уже была, нейтралы) и не писать много фракционных проверок в коде таргета.  Чтобы людей френдли мобы не били нужно смотреть на на фракции, а скорее всего, на френдли компоненту.

2021-07-04 19:06 UTC, KIBORG04 commented
Да какой антачебл, у нас есть фракция нейтралов. Проблема не во фракциях, проблема в френди-компоненте у мобов

2021-07-04 20:44 UTC, Rahmanio commented
> Да какой антачебл, у нас есть фракция нейтралов. Проблема не во фракциях, проблема в френди-компоненте у мобов

Тогда я не знаю как это фиксить, в самом начале пытался и у меня не вышло, более ничего менять не буду, если есть идеи, лучше сделайте сами.

2021-07-04 20:45 UTC, kalazus commented
> Да какой антачебл, у нас есть фракция нейтралов. Проблема не во фракциях, проблема в френди-компоненте у мобов

Прикол в том, что если оставить neutral, то мобы почти не будут агриться на животных. Что будет достаточно странно (пауки сосуществующие с курицами). Людям нужна своя фракция чтобы на них нападали мобы (сейчас). Но хотелось бы чтобы френдли могли сражаться и с хостайл мобами, а простых животных не убивали (не получится через attack_same).
Как по мне, то что сейчас это один из лучших вариантов.

2021-07-04 21:01 UTC, KIBORG04 commented
https://github.com/TauCetiStation/TauCetiClassic/blob/5d6f5b0ead3b21fc3a57f5136059cd8825cc0c8e/code/modules/roguelike/mob_modifiers/negative.dm#L45-L62

Я предлагал в 61й строчке поменять нейтралов на станцию

2021-07-05 10:43 UTC, Rahmanio commented
> https://github.com/TauCetiStation/TauCetiClassic/blob/5d6f5b0ead3b21fc3a57f5136059cd8825cc0c8e/code/modules/roguelike/mob_modifiers/negative.dm#L45-L62
> 
> Я предлагал в 61й строчке поменять нейтралов на станцию

Но тогда френдли мобы с шахты будут атаковать мышей, груши и так далее. А хостайл мобы обычные не будут атаковать куриц и так далее. Моё решение пока что

2021-07-05 10:59 UTC, volas commented
> Но тогда френдли мобы с шахты будут атаковать мышей, груши и так далее

не будут, если у мышей и груш останется neutral, на который глобальная проверка не зависимо от фракции

2021-07-05 11:07 UTC, volas commented
Хотя в варианте киборга их могут свои же потом загрызть. Есть варианты с ``attack_faction``, а в целом можно было бы рефакторнуть это во что-то более гибкое.

2021-07-07 20:09 UTC, KIBORG04 commented
ладно пофиг

2021-07-07 20:12 UTC, merged

2021-07-07 23:40 UTC, volas commented
Киборг поторопился