Purge icon2base64()
TauCetiStation/TauCetiClassic pull request #7519
Opened 2021-07-05 04:39 UTC by 4310V343k

## Описание изменений
Заменяет `icon2base64()` на `bicon()`, ибо второй кэширует результаты, заодно добавил возможность менять стили этих самых иконок в этом самом проке (оно никак не проверяется и если вы что-то сломали то вы что-то сломали)
## Почему и что этот ПР улучшит
Оптимизация, i guess?
## Авторство
Remindme
## Чеинжлог
Блаблабла

2021-07-05 04:39 UTC, TauKitty commented
###### Changelog status: :radio_button: No changelog

2021-07-05 06:55 UTC, volas commented on code/game/gamemodes/factions.dm
> +	var/header = {"[bicon(logo, css = "style='position:relative; top:10;'")] <FONT size = 3><B>[capitalize(name)]</B></FONT> [bicon(logo, css = "style='position:relative; top:10;'")]"}
base64 в таких местах нужен для статистики, которая отдельно от игры

2021-07-05 07:50 UTC, 4310V343k commented on code/game/gamemodes/factions.dm
> +	var/header = {"[bicon(logo, css = "style='position:relative; top:10;'")] <FONT size = 3><B>[capitalize(name)]</B></FONT> [bicon(logo, css = "style='position:relative; top:10;'")]"}
`bicon()` возвращает кэшированный `icon2base64()`

2021-07-05 08:10 UTC, 4310V343k commented on code/game/gamemodes/factions.dm
> +	var/header = {"[bicon(logo, css = "style='position:relative; top:10;'")] <FONT size = 3><B>[capitalize(name)]</B></FONT> [bicon(logo, css = "style='position:relative; top:10;'")]"}
Looks fine to me
![](https://i.imgur.com/YCxAnaT.png)

2021-07-05 14:57 UTC, KIBORG04 approved these changes
https://github.com/TauCetiStation/TauCetiClassic/blob/43e9a2394cc13aab0128132ed10a848cd8a7eb9c/code/modules/goonchat/browserOutput.dm#L188-L196

Ну норм, оптимизация так сказать.

2021-07-05 15:20 UTC, volas commented on code/game/gamemodes/factions.dm
> +	var/header = {"[bicon(logo, css = "style='position:relative; top:10;'")] <FONT size = 3><B>[capitalize(name)]</B></FONT> [bicon(logo, css = "style='position:relative; top:10;'")]"}
ок, сейчас там тоже base64. Но бикон тащит за собой теги и классы. Нужен тогда какой нибудь вариант который бы только строку изображения возвращал, используя общий кэш

2021-07-05 15:22 UTC, volas commented on code/game/gamemodes/factions.dm
> +	var/header = {"[bicon(logo, css = "style='position:relative; top:10;'")] <FONT size = 3><B>[capitalize(name)]</B></FONT> [bicon(logo, css = "style='position:relative; top:10;'")]"}
еще под вопросом насколько долго там кэш лежит и насколько он будет актуален. Если мы закэшировали моба там в начале раунда, а в течении раунда он приоделся и потолстел

2021-07-05 16:20 UTC, 4310V343k commented on code/game/gamemodes/factions.dm
> +	var/header = {"[bicon(logo, css = "style='position:relative; top:10;'")] <FONT size = 3><B>[capitalize(name)]</B></FONT> [bicon(logo, css = "style='position:relative; top:10;'")]"}
> Нужен тогда какой нибудь вариант который бы только строку изображения возвращал, используя общий кэш

Первая проблема решена. Со вторым сейчас что-нибудь нащиткодю

2021-07-05 16:25 UTC, 4310V343k commented on code/game/gamemodes/factions.dm
> +	var/header = {"[bicon(logo, css = "style='position:relative; top:10;'")] <FONT size = 3><B>[capitalize(name)]</B></FONT> [bicon(logo, css = "style='position:relative; top:10;'")]"}
Нащиткожено, ревьювайте

2021-07-05 16:38 UTC, KIBORG04 commented on code/game/gamemodes/factions.dm
> +	var/header = {"[bicon(logo, css = "style='position:relative; top:10;'")] <FONT size = 3><B>[capitalize(name)]</B></FONT> [bicon(logo, css = "style='position:relative; top:10;'")]"}
> еще под вопросом насколько долго там кэш лежит и насколько он будет актуален. Если мы закэшировали моба там в начале раунда, а в течении раунда он приоделся и потолстел

Всю жизнь так жили проблем не было

2021-07-05 16:39 UTC, 4310V343k commented on code/game/gamemodes/factions.dm
> +	var/header = {"[bicon(logo, css = "style='position:relative; top:10;'")] <FONT size = 3><B>[capitalize(name)]</B></FONT> [bicon(logo, css = "style='position:relative; top:10;'")]"}
Ну а ты всё равно ревьювай

2021-07-05 16:45 UTC, KIBORG04 commented on code/game/gamemodes/factions.dm
> +	var/header = {"[bicon(logo, css = "style='position:relative; top:10;'")] <FONT size = 3><B>[capitalize(name)]</B></FONT> [bicon(logo, css = "style='position:relative; top:10;'")]"}
Я пытаюсь придумать как проверить актуальность кэша

2021-07-05 16:49 UTC, KIBORG04 commented on code/game/gamemodes/factions.dm
> +	var/header = {"[bicon(logo, css = "style='position:relative; top:10;'")] <FONT size = 3><B>[capitalize(name)]</B></FONT> [bicon(logo, css = "style='position:relative; top:10;'")]"}
А хрен его знает, но оставлять кэш на 1 минуту..

2021-07-06 13:13 UTC, KIBORG04 commented
конфликты

2021-07-06 13:44 UTC, KIBORG04 requested changes
![image](https://user-images.githubusercontent.com/26389417/124610637-5bf31b00-de79-11eb-8126-6bb9c6231d6f.png)

Я незнаю че происходит, но новые иконки не показываются. Был случай, что при обновление странички разные типы иконок показывало (то все абдуткторы, то все триторы)

2021-07-06 13:52 UTC, KIBORG04 commented on code/modules/goonchat/browserOutput.dm
>  		if (!bicon_cache["\ref[obj]"]) // Doesn't exist yet, make it.
Почему-то "\ref[obj]" всегда одинаковое

2021-07-06 14:02 UTC, 4310V343k commented on code/modules/goonchat/browserOutput.dm
>  		if (!bicon_cache["\ref[obj]"]) // Doesn't exist yet, make it.
Разные айконстейты у одной иконки должны давать разные рефы...

2021-07-06 14:03 UTC, 4310V343k commented on code/modules/goonchat/browserOutput.dm
>  		if (!bicon_cache["\ref[obj]"]) // Doesn't exist yet, make it.
Разные айконстейты у одной иконки должны давать разные рефы... Ну, по логике

2021-07-06 14:04 UTC, KIBORG04 commented on code/modules/goonchat/browserOutput.dm
>  		if (!bicon_cache["\ref[obj]"]) // Doesn't exist yet, make it.
![image](https://user-images.githubusercontent.com/26389417/124613650-213eb200-de7c-11eb-8e91-c92e75f5d1ca.png)

Один рефреш - тройка ссылок

Вот код как я тестил
![image](https://user-images.githubusercontent.com/26389417/124613704-30bdfb00-de7c-11eb-8a4e-f7d0e61574ab.png)

2021-07-06 14:05 UTC, 4310V343k commented on code/modules/goonchat/browserOutput.dm
>  		if (!bicon_cache["\ref[obj]"]) // Doesn't exist yet, make it.
![](https://i.imgur.com/2s6gs59.png)

2021-07-17 19:19 UTC, volas commented on code/game/gamemodes/factions.dm
> +	var/header = {"[bicon(logo, css = "style='position:relative; top:10;'")] <FONT size = 3><B>[capitalize(name)]</B></FONT> [bicon(logo, css = "style='position:relative; top:10;'")]"}
> Всю жизнь так жили проблем не было

В конце раунда как раз всю жизнь без кэша генерировали иконку. Общий кэш в минуту ставить тоже так себе.

Можно в кэше сохранять таймштамп картинки, и при запросе bicon-а вторым параметром указывать необходимую свежесть. Тогда в конце раунда можно будет использовать что-то вроде ``bicon(..., 2 MINUTES)``, и если картинка в кэше старше 5 минут - пусть перегенерирует и возвращает новую.

2021-07-17 19:20 UTC, volas commented on code/game/gamemodes/factions.dm
> +	var/header = {"[bicon(logo, css = "style='position:relative; top:10;'")] <FONT size = 3><B>[capitalize(name)]</B></FONT> [bicon(logo, css = "style='position:relative; top:10;'")]"}
И можно будет сбрасывать кэш после каких-то событий с ``bicon(..., 0)``

2021-07-17 19:21 UTC, volas commented on code/modules/goonchat/browserOutput.dm
> +	return "<img [css] src='data:image/png;base64,[bicon_raw(obj)]'>"
Лучше переделать в дефайн, вложенность проков у бьенда не бесплатна.

2021-07-17 19:26 UTC, volas commented on code/modules/goonchat/browserOutput.dm
>  		if (!bicon_cache["\ref[obj]"]) // Doesn't exist yet, make it.
У объекта ref и не должен меняться

2021-08-02 14:27 UTC, KIBORG04 commented
У меня появилось немного странное, но рабочее решение

2021-08-02 14:28 UTC, KIBORG04 commented
Всё оно представлено на данном скриншоте. Воот. Оценки, критика?

![image](https://user-images.githubusercontent.com/26389417/127877409-f44b077c-b278-4ee3-8401-03ccda9481ae.png)

2021-08-02 16:32 UTC, KIBORG04 commented on code/modules/goonchat/browserOutput.dm
> +	icon_info = "[icon]#[icon_state]"
Я подумал, как бы было хорошо, если бы айкон содержал свой айкон и айконстейт. Ну вот и придумал такую штуку. Оно, вроде бы, ничего не ломает. Я на локалке проверил и оно впринципе работает. Айконы в чате появляются, в конце раунде тоже. Интересно, какие будут проблемы после такой модификации?

(возможно стоит сохранять информацию и о дире, фрейме, мувинге)

2021-08-02 16:56 UTC, volas commented on code/modules/goonchat/browserOutput.dm
> +	icon_info = "[icon]#[icon_state]"
Если мы в объекте icon, то у нас же уже и так есть эти icon и icon_state? Я не понимаю зачем еще одна переменная.

2021-08-02 16:58 UTC, volas commented on code/modules/goonchat/browserOutput.dm
> +			bicon_cache[I.icon_info] = icon2base64(obj)
это может работать с обычными иконками, но с генерируемыми тут скорее будет проблема. По ref-у по мне лучше кешировать

2021-08-02 17:15 UTC, KIBORG04 commented on code/modules/goonchat/browserOutput.dm
> +	icon_info = "[icon]#[icon_state]"
В этом то и прикол, айкон, стейт, дир и тд не хранятся в icon'e. Я уже не помню че там в доках, но вроде, айкон это картинка в папке, а аймндж это в самой игре

2021-08-02 17:17 UTC, KIBORG04 commented on code/modules/goonchat/browserOutput.dm
> +			bicon_cache[I.icon_info] = icon2base64(obj)
Я выше кидал фотку, что рефы у 2х разных айконов были одинаковы. Но да, с генерируемым будут проблемы

2021-08-02 17:34 UTC, volas commented on code/modules/goonchat/browserOutput.dm
> +	icon_info = "[icon]#[icon_state]"
а, вижу, это параметры

2021-08-02 17:35 UTC, volas commented on code/modules/goonchat/browserOutput.dm
> +			bicon_cache[I.icon_info] = icon2base64(obj)
Они не будут одинаковыми одновременно, но да. МОжно как на тг md5(icon_base64)

2021-08-02 17:38 UTC, KIBORG04 commented on code/modules/goonchat/browserOutput.dm
> +			bicon_cache[I.icon_info] = icon2base64(obj)
Я на тг вообще не понял. Там один и тот же прок два раза может вызываться. А для проверки этого мд5 все равно вызывается icon2base, чего я и пытаюсь избежать

2021-08-02 21:22 UTC, KIBORG04 commented on code/modules/goonchat/browserOutput.dm
> +			bicon_cache[I.icon_info] = icon2base64(obj)
Я немного покопался.
Например возьму айкон от руны культиста, который генерируется. До конца прока я могу написать icon.icon_info. Да даже в самом листе кэша этих рун у айкона есть переменные. Но вот когда делается atom.icon = runes[rune] (объекту даётся спрайт красивой руны), то это уже вдруг становится не айкон, а типо прямо ссылка на кэш картинки в памяти ( в VV это выглядит как icon = icon() ). А еще istype(I, /icon) НЕ РАВНО isicon(I), что заставляет ниже строчку `var/key = "[istype(A.icon, /icon) ? "\ref[A.icon]" : A.icon]:[A.icon_state]"` НИКОГДА не возвращать ключ, в котором будет ссылка. Плюс я еще в дискорде пописал об этом.

![image](https://user-images.githubusercontent.com/26389417/127925492-f4bb1b47-079a-46c6-83bf-565af70431d1.png)

2021-08-02 21:56 UTC, KIBORG04 commented on code/modules/goonchat/browserOutput.dm
> +	return "<img [css] src='data:image/png;base64,[bicon_raw(obj)]'>"
Я не понял что нужно в итоге сделать. Сам bicon же не получится сделать дефайном, ведь тут есть необязательный параметр.

2021-08-02 22:28 UTC, KIBORG04 commented on code/modules/goonchat/browserOutput.dm
> +			bicon_cache[I.icon_info] = icon2base64(obj)
https://github.com/4310V343k/TauCetiClassic/pull/18/

Ну я вообщем ему создал второй ПР (ибо не понял как редачить ветку иначе), где уже на ссылках всё построил.

2021-08-02 23:02 UTC, KIBORG04 approved these changes
Жду мержа https://github.com/4310V343k/TauCetiClassic/pull/18 и можно попробовать в ТМ.

2021-08-13 08:24 UTC, KIBORG04 commented
Закроешь пр - удалю

2021-08-28 22:40 UTC, KIBORG04 commented on code/modules/goonchat/browserOutput.dm
> +			I = A.icon ? A.icon : icon('icons/misc/buildmode.dmi', "buildhelp")                  // there is no logic with this icon choice, i just like it.
Вообщем, это был неудачный эксперимент, возвращаю непонятную картинку

2021-09-04 19:24 UTC, KIBORG04 commented
И так, у меня появились цифры
| До, 1 форс статистики       | После, 12 нажатий           |
| ------------- |:-------------:|
| ![3yYIwnBBFD](https://user-images.githubusercontent.com/26389417/132105817-5fe5c928-f81d-47be-940f-486e8d9b8200.png) | ![image](https://user-images.githubusercontent.com/26389417/132105812-e247425c-82f3-4232-b135-33e823f3154d.png)|

2021-09-11 11:58 UTC, volas commented on code/modules/goonchat/browserOutput.dm
>  	iconCache[iconKey] << icon
Интересный момент - файл нигде и никогда не чистится. И не используется как кэш.

2021-09-11 11:59 UTC, volas approved these changes
С виду ок, @KIBORG04 если считаешь что можно мержить - мержи

2021-09-11 12:00 UTC, KIBORG04 commented on code/modules/goonchat/browserOutput.dm
>  	iconCache[iconKey] << icon
На тг он пересоздается и юзается такой же конверт айконов в буквы

2021-09-13 12:00 UTC, merged

2021-09-13 22:08 UTC, volas commented on code/modules/goonchat/browserOutput.dm
>  	iconCache[iconKey] << icon
На тг видимо ок, у нас в файл бросаются новые иконки не зависимо от того были они там уже или нет - т.е. это не кэш, и никогда не чистится - на первом сервере он около 30мб и там вполне может лежать какое-нибудь древнее никому не нужное легаси.