Реакция и проверки для TGui в базовом классе машинерии
TauCetiStation/TauCetiClassic pull request #7528
Opened 2021-07-05 16:06 UTC by pss88

## Описание изменений

Определение `tgui_act` в классе `machinery`. Т.е. процедура будет саначал вызвана здесь, а потом у наследников.
В `machinery/tgui_act` добавлены те же проверки, что и в `machinery/Topic`: что машина рабочая, что моб с руками и доступом, отпечатки пальцев и `set_machine`.
Также добавлена проверка работоспособности машины и при взаимодействии. Её почему-то не было.

## Почему и что этот ПР улучшит

Допустим, кто-то начал взаимодействие с машиной - открыл ее окно-интерфейс. Потом пользователь как-то изменился (потерял доступ, сменил отпечатки пальцев и т.д.) или сама машина как-то изменилась (ее кто-то другой изменил, за-emp-шил и т.п.), но при этом окно оставалось открытым. Тогда можно было и дальше взаимодействовать с этой машиной, что неправильно.

## Чеинжлог

:cl:
 - bugfix: Теперь невозможно взаимодействие с устройствами, если эти устройства не работают или у вас потерялся доступ.

2021-07-05 16:06 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2021-07-05 16:13 UTC, T6751 requested changes
Логика, когда интерфейс доступен, а когда нет, размещается в тгуи стейтах.

Для машинерии обычно используется (или имеется ввиду, что должно использоваться) machinery_state. 
Если этот стейт или другие стейты не подходят, то имеет смысл модифицировать или создать новый стейт

2021-07-05 16:16 UTC, T6751 commented on code/game/machinery/machinery.dm
> +	add_fingerprint(usr)
Отпечатки пальцев и set_machine() можно оставить здесь. Но остальную логику желательно перенести в стейт

2021-07-05 16:57 UTC, KIBORG04 commented
> bugfix: Теперь невозможно взаимодействие с устройствами, если эти устройства не работают или у вас потерялся доступ.

Очень непонятно и размыто

2021-07-13 07:50 UTC, pss88 commented
В процессе...

2021-07-15 19:20 UTC, pss88 commented
Обновил. Можете проверять.
Также отредактировал текст PR-а и чейнжлог.

По-хорошему, большинство машин нужно переделывать. Там много "велосипедов". А надо бы под какой-то единый стандарт. Думаю, лучше это делать по мере перехода на TGui. Ну или сразу после того, как этот переход будет завершен.

2021-07-16 12:13 UTC, KIBORG04 approved these changes
Вроде должно работать, либо я совсем ниче не понял

2021-07-16 14:40 UTC, T6751 approved these changes
Кажется всё хорошо

2021-07-16 14:44 UTC, merged