zombies everywhere
TauCetiStation/TauCetiClassic pull request #7557
Opened 2021-07-08 13:15 UTC by 4310V343k

## Описание изменений
Добавил пару строчек зомби-кода, пару изменений тревоги(при вытаскивании платы и дестрое апц)
## Почему и что этот ПР улучшит
fixes #4655
fixes #6026
## Авторство
Remindme
## Чеинжлог
:cl: Remindme
 - fix: При удалении или разборе АПЦ тревога, если таковая была, не пропадала из консолей

2021-07-08 13:15 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2021-07-08 21:51 UTC, T6751 commented on code/modules/power/apc.dm
> +	// var/mob/living/silicon/ai/occupier = null
Можешь убрать закомментированный код здесь и ниже, пожалуста?

2021-07-09 14:30 UTC, KIBORG04 requested changes
Комментарии не нужны

2021-07-09 14:33 UTC, 4310V343k commented
*@T6751* commented on this pull request.
> ------------------------------
>
> In code/modules/power/apc.dm
> <https://github.com/TauCetiStation/TauCetiClassic/pull/7557#discussion_r666541097>
> :
>
> > @@ -80,7 +80,7 @@
>
>  	var/has_electronics = 0 // 0 - none, 1 - plugged in, 2 - secured by screwdriver
>
>  	var/overload = 1 //used for the Blackout malf module
>
>  	var/beenhit = 0 // used for counting how many times it has been hit, used for Aliens at the moment
>
> -	var/mob/living/silicon/ai/occupier = null
>
> +	// var/mob/living/silicon/ai/occupier = null
>
>
> Можешь убрать закомментированный код здесь и ниже, пожалуста?
>
Убери, пожалуйста, сам, если не сложно. У меня доступа к компу какое-то
время не будет

2021-07-09 14:36 UTC, KIBORG04 commented on code/modules/power/apc.dm
> +	// var/mob/living/silicon/ai/occupier = null
Это скорее всего для дебага юзалось

2021-07-09 14:39 UTC, T6751 commented
Комментарии удалены

2021-07-09 14:40 UTC, 4310V343k commented
>
>  Это скорее всего для дебага юзалось
>
ИИ мог раньше "вселяться" в АПЦ, насколько я понял с беглого взгляда на
код, а occupier использовался исключительно там

>

2021-07-09 14:41 UTC, 4310V343k commented
> Комментарии удалены
>
Сенкью

>

2021-07-09 14:46 UTC, T6751 approved these changes

2021-07-11 18:15 UTC, merged