Шаттлы: world.time вместо world.timeofday
TauCetiStation/TauCetiClassic pull request #7569
Opened 2021-07-09 11:14 UTC by T6751

## Описание изменений
В подсистеме шаттлов теперь используется внутриигровое время, а не серверное время.
## Почему и что этот ПР улучшит
fix #7568
fix #7480
## Авторство

## Чеинжлог
:cl:
 - fix: после 3 часов по МСК время прибытия эвакуационного шаттла сбрасывалось до одного часа

2021-07-09 11:14 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2021-07-09 11:24 UTC, KIBORG04 requested changes
Поменяй комментарий в 27 строке, название переменной в 50, посмотри на параметр в 70 и что туда приходит. Попробуй убрать любые упоминания таймофдэя

2021-07-09 11:29 UTC, T6751 commented
На параметр в 70 приходит время дня. Это приходит всем сабсистем в Initialize() и это не должно быть как-то связано с проблемами ETA шаттла
![image](https://user-images.githubusercontent.com/66636084/125071431-eded6480-e0c1-11eb-9190-52675da8f5af.png)

2021-07-09 11:30 UTC, T6751 commented
Остальные упоминания timeofday убрал

2021-07-09 14:22 UTC, KIBORG04 commented
![image](https://user-images.githubusercontent.com/26389417/125092643-344ebd80-e0da-11eb-97ae-8bdafb3cb3a1.png)

А это что за перец?

2021-07-09 14:26 UTC, T6751 commented
> А это что за перец?

Уже никто

2021-07-09 14:27 UTC, KIBORG04 commented
Убил

2021-07-09 15:13 UTC, T6751 commented
Протестировал. 
В 2:59 и в 23:59 сброса таймера не было. Всё должно работать

2021-07-13 17:07 UTC, KIBORG04 approved these changes

2021-07-17 12:33 UTC, merged