Количество печати материалов в автолате + печать проводов
TauCetiStation/TauCetiClassic pull request #7608
Opened 2021-07-15 22:40 UTC by pss88

## Описание изменений
1. Кроме множителей x1, x5, x10 для печати добавились x25 и x50. Плюс функция в js-файле, чтобы проще задавать эти множители.
2. Переменная `max_res_amount` теперь для всех рецептов, а не только стэков. Чтобы не засорять `tgui_static_data()`.
3. Печать проводов (`cable_coil`) во вкладке _Engineering_ - x1, x5, x10, x25. Не стал делать x30 специально для проводов.

## Почему и что этот ПР улучшит
1. Дополнительные множители для печати материалов в автолате. Кроме x1, x5, x10 добавились x25 и x50.
2. Печать проводов во вкладке _Engineering_ в автолате. Наконец-то провода станут возобновляемым ресурсом.

## Чеинжлог
:cl:
 - tweak: Больше множителей при печати в автолате: x25, x50.
 - tweak: Печать проводов в автолате.

2021-07-15 22:40 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2021-07-15 22:43 UTC, KIBORG04 commented on code/game/machinery/autolathe.dm
> +			    recipe.resources[MAT_GLASS] ? round(stored_material[MAT_GLASS] / recipe.resources[MAT_GLASS]) : INFINITY)
```suggestion
			max_multiplier = min(recipe.max_res_amount, \
				recipe.resources[MAT_METAL] ? round(stored_material[MAT_METAL] / recipe.resources[MAT_METAL]) : INFINITY, \
				recipe.resources[MAT_GLASS] ? round(stored_material[MAT_GLASS] / recipe.resources[MAT_GLASS]) : INFINITY)
```
Пробелы детектед

2021-07-15 22:46 UTC, KIBORG04 commented on tgui/packages/tgui/interfaces/Autolathe.js
> +  return (null);
А зачем? ретурн же был выше

(я незнаю синтаксиса джиеса, так что ориентируюсь на опыт)

2021-07-15 22:46 UTC, KIBORG04 commented on tgui/packages/tgui/interfaces/Autolathe.js
> +                      .map(mult => MultButton(recipe, materials, act, mult))}
```suggestion
                    {[5, 10, 25, 50].map(mult => MultButton(recipe, materials, act, mult))}
```
А разве так не лучше?

2021-07-15 22:48 UTC, KIBORG04 commented on tgui/packages/tgui/interfaces/Autolathe.js
> +                      .map(mult => MultButton(recipe, materials, act, mult))}
И я правильно понимаю, что это в итоге будет некий цикл, где каждая цифра вызовет MultButton и является mult ?

(я незнаю синтаксиса джиеса, так что ориентируюсь на опыт)

2021-07-15 22:50 UTC, KIBORG04 commented on tgui/packages/tgui/interfaces/Autolathe.js
> +  return (null);
Я понял

2021-07-15 22:52 UTC, KIBORG04 commented on code/game/machinery/autolathe.dm
> +	R(/obj/item/weapon/stock_parts/console_screen,   CATEGORY_ENGINEERING),
```suggestion
	R(/obj/item/stack/cable_coil/random,             CATEGORY_ENGINEERING),
	R(/obj/item/weapon/stock_parts/console_screen,   CATEGORY_ENGINEERING),
```
Может так?

2021-07-15 22:58 UTC, pss88 commented on code/game/machinery/autolathe.dm
> +	R(/obj/item/weapon/stock_parts/console_screen,   CATEGORY_ENGINEERING),
Ок.

2021-07-15 22:58 UTC, pss88 commented on tgui/packages/tgui/interfaces/Autolathe.js
> +                      .map(mult => MultButton(recipe, materials, act, mult))}
Ок.

2021-07-15 23:08 UTC, pss88 commented on code/game/machinery/autolathe.dm
> +	R(/obj/item/weapon/stock_parts/console_screen,   CATEGORY_ENGINEERING),
Хотя все оказалось не так просто... Там не цвет рандомный, а тип (с соответствующим цветом). И присваивается он в atom_init. Завтра посмотрю, что можно сделать.

2021-07-15 23:09 UTC, KIBORG04 commented on code/game/machinery/autolathe.dm
> +	R(/obj/item/weapon/stock_parts/console_screen,   CATEGORY_ENGINEERING),
А разве он не должен заспавнить такой провод и в секунду заменить? (Хотя могут быть проблемы со стаком)

2021-07-16 08:16 UTC, T6751 reviewed
>  Чтобы не засорять tgui_static_data().

Не могу понять, что ты здесь имел ввиду под засорять...

2021-07-16 08:16 UTC, T6751 commented on tgui/packages/tgui/interfaces/Autolathe.js
>                  {recipe.is_stack === 1 && (
Учитывая, что ты передаешь ```max_res_amount``` не думаю, что есть смысл теперь передавать ```is_stack```. т.к. думаю здесь можно сделать просто ```recipe.max_mult > 1```

2021-07-16 08:59 UTC, T6751 requested changes
Независимо от того. выберу я x1 x5 x10 x25 - Провода спавнятся по 30

2021-07-16 09:03 UTC, pss88 commented
Да, я знаю. Это потому что random выбирает не цвет, а тип. Я сначала сделал red, а потом заменил на random, как предложил KIBORG04. И я вчера об этом написал. Но моего сообщения тут почему-то нет...

2021-07-16 09:18 UTC, T6751 commented
> 
> 
> Да, я знаю. Это потому что random выбирает не цвет, а тип. Я сначала сделал red, а потом заменил на random, как предложил KIBORG04. И я вчера об этом написал. Но моего сообщения тут почему-то нет...

При создании материалов (которые ```/obj/item/stack```) вторым параметром попробуй указывать количество

2021-07-16 09:26 UTC, T6751 commented on code/game/machinery/autolathe.dm
>  					S.set_amount(multiplier)
set_amount() теперь не нужен
```suggestion
					new recipe.result_type(T, multiplier)
```

2021-07-16 09:49 UTC, pss88 commented
Исправил. Проверил.
Единственно, что мне не нравится - провода больно дешевые. Сделать подороже или и так норм?

2021-07-16 10:14 UTC, T6751 approved these changes
Работает

> Сделать подороже или и так норм?

Думаю так нормально

2021-07-16 12:28 UTC, merged