Порт шапок с ТГ
TauCetiStation/TauCetiClassic pull request #7624
Opened 2021-07-18 20:17 UTC by KIBORG04

## Описание изменений
Мне нужны эти шапки, чтобы гангстеры были еще больше гангстерными в моем соседнем ПРе.

![image](https://user-images.githubusercontent.com/26389417/126081031-bcfdfec6-7c26-478a-82dc-493253f35f03.png)

## Почему и что этот ПР улучшит
Новые крутые шапки через грейскейл

## Авторство
ТГ

## Чеинжлог
:cl:
 - image: Добавлены шапки в автомат с одеждой

2021-07-18 20:17 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2021-07-19 11:00 UTC, T6751 commented
А почему они бесплатные?

2021-07-19 11:01 UTC, AndroBetel commented
![BESPLATNO](https://user-images.githubusercontent.com/44546836/126150346-f62a21d4-a64f-4298-9968-443c7ad1825c.gif)

2021-07-19 12:22 UTC, KIBORG04 commented
блин капитализм

2021-07-19 16:01 UTC, T6751 approved these changes
Ура, грейскейл шапки

2021-08-06 14:03 UTC, UDaV73rus requested changes
В чатиках сказали что спрайт не крутой и в описании обман, но киборг не унывает и ждет апрув
Нарисуйте киборгу шапки, ваш шанс нарисовать простейший спрайт которым будете любоваться в каждом генге

2021-08-14 21:59 UTC, closed without merging