Турели не стреляют по рантайму
TauCetiStation/TauCetiClassic pull request #7647
Opened 2021-07-22 17:04 UTC by 4310V343k

## Описание изменений
Турели не стреляют по рантайму
## Почему и что этот ПР улучшит
https://i.imgur.com/5rQYw9F.png
## Авторство
Remindme
## Чеинжлог
:cl: Remindme
 - fix: Турели стреляли по рантайму

2021-07-22 17:04 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2021-07-22 17:40 UTC, KIBORG04 commented
Бога что-ли ещё пофиксь

2021-07-22 18:13 UTC, LudwigVonChesterfield commented
и грушу если её ещё не ревертнули!

2021-07-22 18:13 UTC, LudwigVonChesterfield commented on code/game/machinery/portable_turret.dm
> +	if(istype(L, /mob/living/simple_animal/cat/runtime))	// that cat can appear anytime everywhere
а у нас нет какого-то флага который можно навешивать мобу чтобы проверять не на тип а на этот флаг?

2021-07-22 18:14 UTC, KIBORG04 commented on code/game/machinery/portable_turret.dm
> +	if(istype(L, /mob/living/simple_animal/cat/runtime))	// that cat can appear anytime everywhere
Скорее лучше проверку на фракцию

2021-07-26 04:00 UTC, volas requested changes
Согласен с комментариями выше, стоит проверять на фракции и использовать их во всех таких случаях.

2021-08-09 20:14 UTC, closed without merging