Шлем капитана закрывает слоты головы
TauCetiStation/TauCetiClassic pull request #7652
Opened 2021-07-23 05:42 UTC by Yaroslavppv

## Описание изменений
Удалил флаги, которые есть у родителя
fix #7595 
## Почему и что этот ПР улучшит
Шлем капитана теперь защищает вещи под собой
## Авторство

## Чеинжлог
:cl:
 - fix: Шлем капитана закрывает слоты головы

2021-07-23 05:42 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2021-07-23 21:46 UTC, KIBORG04 commented on code/modules/clothing/spacesuits/captain.dm
> -	flags_pressure = STOPS_LOWPRESSUREDMAGE
у родителя 

```
flags_pressure = STOPS_PRESSUREDMAGE
```

2021-07-26 04:08 UTC, volas requested changes

2021-07-26 04:08 UTC, volas commented on code/modules/clothing/spacesuits/captain.dm
> -	flags_inv = HIDEFACE
Следует просто добавить нехватающие флаги. Броня капитана уникальна и по флагам не должна зависить от родителя.

2021-07-27 12:13 UTC, KIBORG04 approved these changes
он вернул

2021-07-27 12:13 UTC, merged