[DNM] Dynamic Asteroid Mob Spawning
TauCetiStation/TauCetiClassic pull request #7760
Opened 2021-08-11 15:35 UTC by LudwigVonChesterfield

## Описание изменений

Мобы на астероиде спавнятся не раундстартом, а по надобности, где-то недалеко от игрока.

Каждых 2 минуты на астероиде моб будет спавнится в 8-и тайлх игрока(на 1 тайл дальше чем видит игрок). Если в течении полторы минуты моба никто не видит, он деспавнится.

Юзает штуку (AREA_SENSITIVE) которую я пригонял в #7749, поэтому без него мёржить нельзя. Если тот ПР отклонят - добавлю порт этой штуки сюда.

## Почему и что этот ПР улучшит

Серваку не надо симулировать мобов которых никто не видит, у шахтёров всегда где-то неподалёку затаились приключения.

## Чеинжлог
:cl: Luduk
- rscadd: Мобы на астероиде появляются в течении раунда где-то недалеко от игрока.

2021-08-13 02:55 UTC, Haggerd commented
А они спаунятся только в "опасной" зоне астероида (Западной, если точнее) или вообще везде?

2021-08-13 09:45 UTC, LudwigVonChesterfield commented
везде где не зона станции

2021-08-20 16:27 UTC, KIBORG04 commented
Крутой пр скоро мерж

2021-08-20 16:57 UTC, kalazus commented
Не понимаю зачем добавлять это, учитывая что у нас не ТГ, и на шахте и так много умирают. Без ПРа можно было обойти хотя-бы противника и ты всегда знал что с задницы никто не зайдёт, а теперь нет, сингулярных голиф может заспавнится прямо за спиной.
И почему наполнение фреймворка настроения тут?

2021-08-20 19:03 UTC, KIBORG04 commented
> Не понимаю зачем добавлять это, учитывая что у нас не ТГ, и на шахте и так много умирают. Без ПРа можно было обойти хотя-бы противника и ты всегда знал что с задницы никто не зайдёт, а с ПРом нет, сингулярных голиф может заспавнится прямо за спиной.

Мне это нравится тем, что сервак перестанет значительно меньше лагать из-за кучи астейройдных мобов сканирующих 9x9 область каждые несколько секунд.

> И почему наполнение фреймворка настроения тут?

потому что механ юзается оттуда

2021-08-20 20:42 UTC, kalazus commented
> Мне это нравится тем, что сервак станет значительно меньше лагать из-за кучи астейройдных мобов сканирующих 9x9 область каждые несколько секунд.

Они так много жрут? У нас же есть туррели (13 только на станции), что делают то-же. На дереликтах ещё мобов 15 агрессивных. Я не помню сколько спавнится, но не думаю что больше 30.

2021-09-15 11:13 UTC, KIBORG04 commented on code/datums/components/spawn_area.dm
> +	despawn_timers = null
```suggestion
	for(var/timer in despawn_timers)
		deltimer(timer)

	despawn_timers = null
```

2021-09-15 11:14 UTC, KIBORG04 commented on code/datums/components/spawn_area.dm
> +	despawn_timers = null
а, не, там же инстанс=таймер. короче исправляй

2021-09-15 11:18 UTC, KIBORG04 commented on code/game/objects/effects/decals/crayon.dm
> +
удалить

2021-09-15 11:26 UTC, KIBORG04 commented on code/modules/mining/mine_areas.dm
> +	new to_spawn(T)
```
/datum/component/spawn_area/proc/Spawn(turf/T)
	var/list/atom/movable/instances = spawn_callback.Invoke(T)

	for(var/instance in instances)
		refresh_instance(instance)
		register_instance(instance)
```

а разве этот спавн будет возвращать какой-то лист?

2021-09-17 17:16 UTC, KIBORG04 commented
Где-то не убирается нулл из деспавн_таймера

2021-09-17 17:18 UTC, KIBORG04 commented on code/datums/components/spawn_area.dm
> +/datum/component/spawn_area/proc/TryDespawn(atom/movable/instance)
Как я понял, деспавнятся даже трупы. Разве их тоже нужно?

2021-09-17 17:23 UTC, KIBORG04 commented
> Где-то не убирается нулл из деспавн_таймера

Я че-то скрин не кинул..
![image](https://user-images.githubusercontent.com/26389417/133828960-3a3db884-bb7b-452d-8f27-0034a5af0d97.png)


но короче. У тебя же деспавн_таймеры это ассоциативный лист, а убираешь ты элементы через LAZYREMOVE, который убирает нормально только из обычного

2021-09-17 18:02 UTC, LudwigVonChesterfield commented on code/datums/components/spawn_area.dm
> +/datum/component/spawn_area/proc/TryDespawn(atom/movable/instance)
а почему бы и нет

2021-09-17 18:03 UTC, LudwigVonChesterfield commented
> но короче. У тебя же деспавн_таймеры это ассоциативный лист, а убираешь ты элементы через LAZYREMOVE, который убирает нормально только из обычного

так если убрать ключ то убирается и значение с ним связанное. откуда там нуллы - буду копаться.

2021-09-18 15:03 UTC, KIBORG04 commented
За ТМь когда будешь готов

2021-09-29 16:43 UTC, volas commented
С учетом https://forum.taucetistation.org/t/novaya-mehanika-spauna-ksenosov-v-shahte-pochemu-nuzhno-ee-ubrat/28437/

Может быть спавнить не всюду а от каких-то заранее определенных спавн поинтов (лейбл и в случайном радиусе от него)?

Идея Спейра с гнездами еще https://forum.taucetistation.org/t/novaya-mehanika-spauna-ksenosov-v-shahte-pochemu-nuzhno-ee-ubrat/28437/20?u=volas
но мне нравится в меньшей степени потому что сложнее и возможны абузы со стороны игроков.

2021-10-09 23:15 UTC, KIBORG04 commented
Так че решили то?

2021-10-16 18:03 UTC, volas commented
> Так че решили то?

Обсуждали проблему в дискорде, нужно добавить ямки при спавне мобов для наглядности что они не из воздуха появляются. И контра спавна (что бы были безопасные зоны) - сделать что бы не появлялись если пол в плитках. Возможно в будущем контру нужно будет еще как-то проапгрейдить если с плитками будет слишком муторно.
Кто нибудь может сделать ПР к Людуку, это пара строк. И на мой взгляд можно мержить.

+ стоит еще подумать над ишью выше.

2021-11-08 20:42 UTC, volas approved these changes
нет больше вопросов по самой фиче, нужно еще проглядеть код на свежую голову. Ну или кто уже смотрел - может смержить

2021-11-08 21:01 UTC, SpaiR requested changes

2021-11-08 21:01 UTC, SpaiR commented on code/datums/components/spawn_area.dm
> +	var/datum/area_group/AG = global.observer_groups[g]
Ты работаешь со лениво инициализируемым списком. Поэтому *во всех* местах, где ты получаешь к нему доступ нужно использовать `LAZYACCESS` + `if (AG)`, иначе будет рантайм.
Сосбственно, здесь одно из таких мест.
```
bad index in spawn_area.dm:297 :
proc name: get observers (/datum/component/spawn_area/proc/get_observers)
  source file: spawn_area.dm,297
  usr: null
  src: /datum/component/spawn_area (/datum/component/spawn_area)
  call stack:
/datum/component/spawn_area (/datum/component/spawn_area): get observers(the basilisk (/mob/living/simple_animal/hostile/asteroid/basilisk))
/datum/component/spawn_area (/datum/component/spawn_area): TryDespawn(the basilisk (/mob/living/simple_animal/hostile/asteroid/basilisk))
/datum/callback (/datum/callback): InvokeAsync()
Timer (/datum/controller/subsystem/timer): fire(0)
Timer (/datum/controller/subsystem/timer): ignite(0)
Master (/datum/controller/master): RunQueue()
Master (/datum/controller/master): Loop()
Master (/datum/controller/master): StartProcessing(0)
```

2021-11-08 21:01 UTC, SpaiR commented on code/datums/components/spawn_area.dm
> +	var/datum/area_group/AG = observer_groups[g]
`LAZYACCESS` + `if (AG)`

2021-11-08 21:06 UTC, LudwigVonChesterfield commented on code/datums/components/spawn_area.dm
> +	var/datum/area_group/AG = observer_groups[g]
даже при том что по идее не может быть такой ситуации где мы убираем наблюдателя, которого в списке нет? это же просто маскировало бы проблему

2021-11-08 21:15 UTC, SpaiR commented on code/datums/components/spawn_area.dm
> +	deltimer(observers[L])
Я так понимаю, что тут тоже нужно использовать `LAZYACCESS`.

2021-11-08 21:15 UTC, SpaiR commented on code/datums/components/spawn_area.dm
> +	var/datum/area_group/AG = observer_groups[g]
Как говорится "или крестик снемите, или штаны наденьте". Если список ленивый, то он должен быть ленивым во всем. Делая предположение "такой ситуации быть не может", только создается поле для фантазии. Собственно, ниже как раз конкретное место с проблемой, которое и вытекло из этого тезиса. Сколько ПР был в ТМе, баг не фиксилсь. Так что профит сомнительный.

Тем более, что выше у тебя код:
```
	var/datum/area_group/AG = LAZYACCESS(global.observer_groups, g)

	if(!AG)
		AG = new /datum/area_group(g)
		LAZYSET(global.observer_groups, g, AG)
```
Тут вот тоже ведь, если у тебя есть `AG`, значит список точно быть `null` не может, но тем не менее `LAZYSET` используется. Так что чтобы лишний раз не думать, проще использовать `LAZY` операции везде.

2021-11-08 21:29 UTC, SpaiR commented on code/datums/components/spawn_area.dm
> +	var/datum/area_group/AG = observer_groups[g]
В этот же адрес можно добавить, если тебе нужно ассертать какое-то поведение (действительно нужно), то, собственно, эти самые ассерты писать и нужно. С понятным описание проблемы. Неявное использование, для таких целей, конструкций языка создаст гораздо больше проблем.

2021-11-08 22:32 UTC, LudwigVonChesterfield commented
> Собственно, ниже как раз конкретное место с проблемой, которое и вытекло из этого тезиса.

ниже кстати было место, где как раз такая ситуация могла быть, и там я действительно затупил.

2021-11-09 05:52 UTC, SpaiR approved these changes

2021-11-09 05:56 UTC, merged