Artstuff!
TauCetiStation/TauCetiClassic pull request #7772
Opened 2021-08-12 19:38 UTC by 4310V343k

## Описание изменений
Добавляет возможность крафта холстов, молбертов и рамок
Больше изменений в коммитах
## Почему и что этот ПР улучшит
У меня появилась возможность заняться чем-нибудь полезным. Например, портом SSPersistence или добавлением чего-нибудь нового в крафт из ткани
## Авторство
AnturK - DM, Remindme - Python
## Чеинжлог
:cl:
 - add: Добавлены холсты, мольберты и рамки для картин. Первое крафтится из ткани, остальное из дерева. На карте их нет
 - tweak: При разрезании одежды, одеял теперь появляется ткань, а не тряпки. Тряпки теперь создаются через крафт-меню ткани
 - add: В биогенераторе теперь можно создавать ткань и тряпки

2021-08-12 19:38 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2021-08-12 20:17 UTC, Javeliiner commented
Очень хорошая идея, предлагаю тогда вместе с тканью добавить возможность крафта самодельной одежды по типу робы, крафт бандан, и растение хлопчатника, которое несъедобно, но даёт больше материи в биогенераторе, чем другие культуры.

2021-08-12 20:46 UTC, LudwigVonChesterfield commented on code/game/machinery/biogenerator.dm
> +			else new/obj/item/clothing/suit/jacket/leather/overcoat(src.loc)
тут не тот тип

2021-08-12 20:46 UTC, LudwigVonChesterfield commented on code/game/machinery/biogenerator.dm
> +			else new/obj/item/clothing/suit/jacket/leather/overcoat(src.loc)
тут тоже

2021-08-12 20:46 UTC, LudwigVonChesterfield commented on code/game/machinery/biogenerator.dm
> +				new/obj/item/weapon/reagent_containers/food/snacks/meat(src.loc)
мясо?

2021-08-12 20:46 UTC, LudwigVonChesterfield commented on code/game/machinery/biogenerator.dm
> +				new/obj/item/weapon/reagent_containers/food/snacks/meat(src.loc)
мясо?

2021-08-12 20:48 UTC, LudwigVonChesterfield commented on code/game/objects/structures/art.dm
> +	if(painting && painting.loc == T) //Only move if it's near us.
... оно сейчас двигает картину только если картина уже на одном турфе с мольбертом. что?

у нас есть компонента которая такое делает (bounded), и система сигналов которая позволила бы картине двигаться куда бы не двигалась структура.

2021-08-12 20:49 UTC, LudwigVonChesterfield commented on code/game/objects/structures/art.dm
> +/obj/item/canvas/proc/finalize(mob/user)
не знаю насколько это грустно что можно пока кто-то риует подписаться на его картине собой

2021-08-12 20:50 UTC, LudwigVonChesterfield commented on code/game/objects/structures/art.dm
> +		switch(P.colour)
у нас ещё есть фиолетовая ручка

2021-08-12 21:02 UTC, LudwigVonChesterfield commented on code/game/objects/structures/art.dm
> +	var/persistence_id
Наверное стоит убрать?

2021-08-12 21:07 UTC, LudwigVonChesterfield commented on code/game/objects/structures/art.dm
> +	world.ext_python("create_png.py", "[png_filename] [width] [height] [get_data_string()]")
эээ... а точно нет возможности пиксели натыкать БЕЗ использования внешних скриптов?

2021-08-12 21:16 UTC, 4310V343k commented on code/game/objects/structures/art.dm
> +	var/persistence_id
```suggestion
	// var/persistence_id
```

2021-08-12 21:16 UTC, 4310V343k commented on code/game/objects/structures/art.dm
> +		switch(P.colour)
Кто такое придумал?

2021-08-12 21:17 UTC, 4310V343k commented on code/game/objects/structures/art.dm
> +	if(painting && painting.loc == T) //Only move if it's near us.
Оно сохраняет турф, потом, после движения мольберта, если картина на месте до передвижения, двигает картину.
Диагональное передвижение ломает это как на ТГ, так и на Тау (должно ломать на Тау, не проверял)

2021-08-12 21:17 UTC, 4310V343k commented on code/game/machinery/biogenerator.dm
> +				new/obj/item/weapon/reagent_containers/food/snacks/meat(src.loc)
Блинблять

2021-08-12 21:17 UTC, 4310V343k commented on code/game/machinery/biogenerator.dm
> +			else new/obj/item/clothing/suit/jacket/leather/overcoat(src.loc)
И тут тоже блинблять

2021-08-12 21:19 UTC, 4310V343k commented on code/game/objects/structures/art.dm
> +/obj/item/canvas/proc/finalize(mob/user)
Сильно грустно

2021-08-12 21:20 UTC, 4310V343k commented on code/game/objects/structures/art.dm
> +	world.ext_python("create_png.py", "[png_filename] [width] [height] [get_data_string()]")
Надо будет посмотреть, я с иконками не работал

2021-08-12 21:37 UTC, 4310V343k commented on code/game/objects/structures/art.dm
> +	world.ext_python("create_png.py", "[png_filename] [width] [height] [get_data_string()]")
https://github.com/tgstation/tgstation/issues/38942

2021-08-12 22:09 UTC, LudwigVonChesterfield commented on code/game/objects/structures/art.dm
> +	if(painting && painting.loc == T) //Only move if it's near us.
почему нельзя просто телепортировать картину после каждого движения если локация не совпадает

2021-08-12 22:14 UTC, 4310V343k commented on code/game/objects/structures/art.dm
> +	if(painting && painting.loc == T) //Only move if it's near us.
Форсмув будет тащить за собой мольберт, я такого не хочу. Как и тгшники

2021-08-13 00:23 UTC, LudwigVonChesterfield commented on code/game/objects/structures/art.dm
> +	if(painting && painting.loc == T) //Only move if it's near us.
... а сейчас не тащит?

2021-08-15 19:47 UTC, kalazus commented on code/game/objects/structures/art.dm
> +	if(painting && painting.loc == T) //Only move if it's near us.
```suggestion
	if(moving_diagonally)
		return
	if(painting && painting.loc == T) //Only move if it's near us.
```
Это должно починить диагональное передвижение.
Но вообще говоря, это можно лучше сделать. Проблема в том, что мольберт может тащить за собой картину, что не на ней (поставить картину на мольберт, перетащить картину, перетащить мольберт). Но можно просто заранее сделать проверку что картина с мольбертом в 1 месте.

2021-08-15 20:19 UTC, LudwigVonChesterfield commented on code/game/objects/structures/art.dm
> +	if(painting && painting.loc == T) //Only move if it's near us.
можно чтобы как только картина слезла с мольберта переставать тащить её за собой

2021-08-16 11:34 UTC, volas requested changes

2021-08-16 11:34 UTC, volas commented on scripts/create_png.py
> +from pathlib import Path
не вижу использования, ниже ``os``, лишнее?

2021-08-16 11:34 UTC, volas commented on code/game/objects/structures/art.dm
> +	var/png_filename = "data/paintings/temp_painting.png"
какой-нибудь rand к имени не помешал бы, на случай одновременного рисования нескольких полотен

2021-08-16 11:34 UTC, volas commented on code/game/objects/structures/art.dm
> +	world.ext_python("create_png.py", "[png_filename] [width] [height] [get_data_string()]")
``width``, ``height``, ``get_data_string`` - нужно вилидировать, так как это запрос к шеллу. isnum для чисел, строку можно регексом

2021-08-16 11:34 UTC, volas commented on code/game/objects/structures/art.dm
> +			var/y = text2num(params["y"])
стоит проверить, что они не больше размеров полотна

2021-08-16 11:38 UTC, volas commented on code/game/objects/structures/art.dm
> +	var/png_filename = "data/paintings/temp_painting.png"
и я не вижу где файл чистится. Еще data/ у нас больше для persistent данных, можно было бы какой нибудь cache/ создать (хотя нужно проверить, как в других местах, может быть это тема отдельного PR-а)

2021-08-16 11:40 UTC, 4310V343k commented on scripts/create_png.py
> +from pathlib import Path
Да, лишнее

2021-08-16 11:42 UTC, 4310V343k commented on code/game/objects/structures/art.dm
> +	world.ext_python("create_png.py", "[png_filename] [width] [height] [get_data_string()]")
`get_data_string()` ничего кроме хекса вывести не сможет, `width` и `height` нигде не изменяются с момента создания картины, `png_filename` всегда одинаковый.
Надо ли?

2021-08-16 11:43 UTC, volas commented on code/game/objects/structures/art.dm
> +	world.ext_python("create_png.py", "[png_filename] [width] [height] [get_data_string()]")
у админов есть возможность менять, так что да

2021-08-30 14:03 UTC, DedYarick commented
А такой ПР был...

2021-09-18 15:18 UTC, KIBORG04 commented
Автор сдох?

2021-09-20 21:25 UTC, 4310V343k commented
Просыпаюсь из спячки

2021-09-20 21:30 UTC, 4310V343k commented on code/game/objects/structures/art.dm
> +	var/png_filename = "data/paintings/temp_painting.png"
В `data/paintings` в будущем (если кто-то портирует персистенс) будут сохраняться картины между раундами. Но пока да, лучше хранить такое в каком-нибудь `data/temp`

2021-09-20 22:06 UTC, 4310V343k commented on code/game/objects/structures/art.dm
> +	world.ext_python("create_png.py", "[png_filename] [width] [height] [get_data_string()]")
Не знаю, как именно надо строку регексом обрабатывать, но
```
	var/count = 0;
	var/regex/r = regex(@"#(?:[0-9a-fA-F]{3}){1,2}")
	while (r.Find(data))	count++;
	ASSERT(count == width * height)
```
заставляет уводить прок в бг, фризя сервер

2021-09-20 22:13 UTC, 4310V343k commented on code/game/objects/structures/art.dm
> +	world.ext_python("create_png.py", "[png_filename] [width] [height] [get_data_string()]")
Я понял. Но тут должно быть достаточно [этого](https://stackoverflow.com/questions/4273074/sanitize-user-input-in-bash-for-security-purposes)?

2021-09-20 22:58 UTC, 4310V343k commented on code/game/objects/structures/art.dm
> +	if(painting && painting.loc == T) //Only move if it's near us.
Блин, вот не знаю что с этим делать. Вроде всё по делу, а вроде и непонятно как решать

2022-03-30 13:10 UTC, 4310V343k commented on code/game/objects/structures/art.dm
>  	generated_icon = new(png_filename)
Вопрос остался

2022-03-30 13:10 UTC, 4310V343k commented on code/game/objects/structures/art.dm
> +	world.ext_python("create_png.py", "[png_filename] [width] [height] [get_data_string()]")
Надеюсь, теперь достаточно

2022-03-30 13:14 UTC, LudwigVonChesterfield commented on code/game/objects/structures/art.dm
> +	var/obj/item/canvas/painting = null
нужно чистить в Destroy()

2022-03-30 13:15 UTC, LudwigVonChesterfield commented on code/game/objects/structures/art.dm
> +		canvas.layer = layer+0.1
```suggestion
		canvas.layer = layer + 0.1
```

2022-03-30 13:16 UTC, LudwigVonChesterfield commented on code/game/objects/structures/art.dm
> +	if(painting && painting.loc == T) //Only move if it's near us.
почему мольберт можно отодвинуть с картины но он будет считаться как присоединённый к ней?

2022-03-30 13:17 UTC, LudwigVonChesterfield commented on code/game/objects/structures/art.dm
> +	var/author_ckey
не используется

2022-03-30 13:18 UTC, LudwigVonChesterfield commented on code/game/objects/structures/art.dm
> +/**
убери эти комментарии

2022-03-30 13:20 UTC, LudwigVonChesterfield commented on code/game/objects/structures/art.dm
> +	to_chat(user, "1")
хм

2022-03-30 13:21 UTC, LudwigVonChesterfield commented on code/modules/clothing/clothing.dm
> +		new /obj/item/stack/sheet/cloth(get_turf(src), 3)
потерялась фича с crit_fail (грязные тряпки)

2022-03-30 13:21 UTC, LudwigVonChesterfield commented on code/modules/paperwork/pen.dm
> +	var/colour = "black"	// can we make it HEX?
can we?

наверное тут стили юзаются ксс. если нет - то почему бы и нет

2022-03-30 13:26 UTC, 4310V343k commented on code/modules/paperwork/pen.dm
> +	var/colour = "black"	// can we make it HEX?
Можно и хексом. Вроде нигде не используется больше. В мелках, к примеру, отдельно хранится цвет как хекс и цвет как имя

2022-03-30 13:58 UTC, LudwigVonChesterfield commented on code/game/objects/structures/art.dm
> +	if(painting && painting.loc == T) //Only move if it's near us.
а картину на мольберте стащить с мольберта можно? и если да - почему

2022-03-30 14:33 UTC, 4310V343k commented
> топ 10 аниме камбеков

не каркай

2022-03-30 20:06 UTC, 4310V343k commented on code/game/objects/structures/art.dm
> +	if(painting && painting.loc == T) //Only move if it's near us.
Should be fixed

2022-03-30 20:08 UTC, LudwigVonChesterfield commented on code/game/objects/structures/art.dm
> +	. = ..()
```suggestion
	return ..()
```

2022-03-30 20:11 UTC, LudwigVonChesterfield commented on code/game/objects/structures/art.dm
> +		painting = null
😔 

пожалуйста, сделай так:

/obj/item/canvas
    var/attached_to
    
 /obj/item/canvas/Moved()
     if(attached_to && !attached_to.Adjacent(get_turf(src))
        attached_to.painting = null
        attached_to = null
 
 /obj/strructure/easel/Moved()
     . = ..()
    attached_to.forceMove(loc)
```

или что-то на такой лад, то есть:
- если холст слезает с мольберта он отцепляется
- если мольберт двигается холст всегда за ним
- в моём коде это не учтено, но можно помещать наверняка что-то из этого в шкаф, и потому надо не get_turf() а loc()

2022-03-30 20:21 UTC, 4310V343k commented on code/game/objects/structures/art.dm
> +		painting = null
Сейчас уже работает...

Мольберт в шкаф нельзя, холст можно. Как раз таки `/obj/item/Adjacent` работает через loc, поэтому изощрятся не надо.

2022-03-31 04:08 UTC, volas commented on code/game/objects/structures/art.dm
>  	generated_icon = new(png_filename)
Да, нет смысла их хранить. Сервер не резиновый.

2022-03-31 04:16 UTC, volas commented on code/game/objects/structures/art.dm
> +				return "#ff0000"
Может стоило бы в одном месте это хранить, обернуть общи проком для преобразование pen-цветов.

2022-03-31 04:16 UTC, volas commented on code/game/objects/structures/art.dm
> +				return "##ffa500"
```suggestion
				return "#ffa500"
```

2022-04-06 09:39 UTC, 4310V343k commented on code/modules/paperwork/pen.dm
> +	var/colour = "black"	// can we make it HEX?
Но блин, этот пр и так большой уже

2022-04-06 09:39 UTC, 4310V343k commented on code/game/objects/structures/art.dm
> +				return "#ff0000"
В каком-то ПРе надо сделать нормально ручки, что бы они работали как мелки

2022-04-06 15:31 UTC, volas approved these changes
можно попробовать в тм, начиная с песочницы

2022-05-22 18:04 UTC, 4310V343k commented
В общем, проблема тут такая, что в серверной обстановке нихрена не работает. Где-то в дискорде было обсуждение, смотрите по дате снятия с ТМа. Если кто-то захочет пошаманить - милости просим

2022-07-02 11:55 UTC, volas commented on code/game/objects/structures/art.dm
> +	world.ext_python("create_png.py", "[png_filename] [width] [height] [data]")
```suggestion
	world.ext_python("create_png.py", "'[png_filename]' '[width]' '[height]' '[data]'")
```
я починил

2022-07-02 11:57 UTC, volas commented on code/game/objects/structures/art.dm
> +	world.ext_python("create_png.py", "[png_filename] [width] [height] [data]")
на всякий случай нужно где-то закрепить, что ext_python и шелл выводят ошибки в DD сервер лог

2022-07-02 16:55 UTC, volas commented on code/modules/scrap/scrap_light.dm
> +	. = ..(mapload, new_amount, merge, FALSE, 0)
Мне кажется, или это возможность создать тряпки без побочных эффектов и нужно обсуждать еще баланс этого изменения?

2022-07-03 13:55 UTC, merged

2025-04-26 12:26 UTC, TauKitty commented
Этот запрос на слияние был упомянут в **Tau Ceti Station Forum**. Там могут быть соответствующие подробности:

https://forum.taucetistation.org/t/fludilka-chast-2/28659/44345