renaming extended
TauCetiStation/TauCetiClassic pull request #7805
Opened 2021-08-20 15:26 UTC by LudwigVonChesterfield

## Описание изменений

Меняет название "Extended" на "Casual Shift"

Другие рассмотренные варианты:

"Peaceful", "Peace & Quiet"
плюсы:
+ все играли в майнкрафт и писифул был бы понятен
минусы:
- намекает на то что на смене якобы нельзя иметь какие-либо конфликты вовсе

"No Antags", "Antagless"
плюсы:
+ вообще никаких недопониманий, просто и в лоб. "без антагов"
минусы:
- наталкивает на вайб того что вы этих антагов боитесь, и потому не выбираете.

"Quiet Shift"
минусы:
- намекает на то что на смене якобы нельзя иметь какие-либо конфликты вовсе

## Почему и что этот ПР улучшит

найдите мне хотя бы двух людей которые знают почему он называется "extended" и сразу это поняли

## Авторство

## Чеинжлог

2021-08-20 15:26 UTC, TauKitty commented
###### Changelog status: :radio_button: No changelog

2021-08-22 00:10 UTC, Zmey25 commented
Экста так называется из-за ивентов, которые там "проводятся", не? Играя в казуал раунд люди не будут ждать чуда.

2021-08-22 10:17 UTC, LudwigVonChesterfield commented
а как слово "экста" связана с ивентами

2021-08-22 10:19 UTC, KIBORG04 commented
Экста не про ивенты, экста про работку, но в которую админы больше вмешиваются в процесс.

2021-08-22 10:28 UTC, UDaV73rus commented
Доказательство что космонавты не читают что им пишут в мозг на старте режима
мем "Не знаю что там за экста, но я против"

2021-08-22 11:44 UTC, atik1n commented
Текущий режим – **Расширенный рояльплей**.
Интересно, почему же экста – экста.

2021-08-22 11:46 UTC, AndroBetel commented
интересно что значит расширенный ролплей
или у нас роли не ролплей?

2021-08-22 12:38 UTC, Zmey25 commented
> а как слово "экста" связана с ивентами

Во время эксты нет антагов, их делают педали. Как бы расширяют обычные игровые возможности. Это на тауките называют ивентом. 
Если у нас написано расширенный роялплей, чтобы это не значило, то наверное так тому и быть.
Забыли истоки.

2021-08-22 12:47 UTC, atik1n commented
Я про то, что в игре буквально пишет Extended Role-play. Ибо нет антагов = нет развлечения кроме отыгрыша.

А про """ивенты""" из спауна антагов – это ленивые безыдейные творчески педали так делают. Поэтому и приелось, что заспаунить нинжу = """ивонт""".

2021-08-22 13:38 UTC, KIBORG04 commented
Casual Shift, сокращённо CS, транслитерация КС, кс - мочиловка. Получается, все вначале будут голосовать за каэсочку?

2021-09-11 12:10 UTC, volas commented
наконец-то

2023-02-13 15:55 UTC, LudwigVonChesterfield commented
I'm back!!

2023-02-13 16:00 UTC, Deahaka commented
> Casual Shift, сокращённо CS, транслитерация КС, кс - мочиловка. Получается, все вначале будут голосовать за каэсочку?

Автор пофиксил это?

2023-02-13 16:42 UTC, LudwigVonChesterfield commented
> Автор пофиксил это?

Теперь да. К сожалению это, или на счастье, мы сможем узнать лишь через долгое время...

2023-02-13 17:07 UTC, LudwigVonChesterfield commented on code/game/gamemodes/modesbundle.dm
> +	/datum/game_mode/casual_shift,
```suggestion
	/datum/game_mode/casual,
```

2023-02-13 18:18 UTC, Sakuya-Izayoi approved these changes

2023-02-13 18:20 UTC, KIBORG04 requested changes
Я за эксту.

2023-02-13 18:39 UTC, Deahaka requested changes
Я за эксту!

2023-02-15 15:13 UTC, UDaV73rus commented
Мне не нравится Казуал.

Если представить себя на место нуба и увидеть Казуал к гейммодах. Что должен подумать человек из наших краев

2023-02-18 10:22 UTC, volas commented
мало кто за и вообще затиранено

2023-02-18 10:22 UTC, closed without merging