Перевод штампиков и фичи педалям и игрокам
TauCetiStation/TauCetiClassic pull request #7878
Opened 2021-08-30 15:07 UTC by atik1n

## Описание изменений
![image](https://user-images.githubusercontent.com/14612180/131361084-c4eb7e4e-cde0-4a7d-b9a0-b3f17f3e7d16.png)
![image](https://user-images.githubusercontent.com/14612180/131361102-e5330fc6-6e8c-4611-8ce1-cc177b8e0deb.png)
![image](https://user-images.githubusercontent.com/14612180/131361123-fdcbfb50-0213-4932-a2f9-95d919df5099.png)

## Почему и что этот ПР улучшит
QoL
## Чеинжлог
:cl: PervertGenius
- fix: Ручка предателя теперь может делать лого НТ
- ru: Перевод штампов
- rscadd: Добавлена печать "брехня"

2021-08-30 15:07 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2021-08-30 15:42 UTC, EdlerN commented
А можно к кнопкам реакций на факс добавить реджект, который будет отсылать бумажку обратно с той самой "правильной" печатью?

2021-08-30 15:44 UTC, atik1n commented
"правильная печать" теперь есть в списке печатей для ЦКшного факса, главное на RPLY нажимать

2021-08-30 15:45 UTC, EdlerN commented
Не, ты не понял. Идея в том чтобы вернуть факс отправителю с этой печатью. И не махаться с копированием.

2021-08-30 20:03 UTC, volas commented on code/modules/paperwork/stamps.dm
> +	stamp_message = "СН Центком"
У нас переводчики уже выбрали и придерживаются определенного названия

2021-08-30 20:05 UTC, atik1n commented on code/modules/paperwork/stamps.dm
> +	stamp_message = "СН Центкомм"
Центко**м** и Центко**мм**

2021-08-30 20:07 UTC, volas commented on code/modules/paperwork/stamps.dm
> +	stamp_message = "НТС Велосити"
https://wiki.taucetistation.org/NTS_Velocity (ловите Лешего если что)

2021-08-30 20:09 UTC, atik1n commented on code/modules/paperwork/stamps.dm
> +	stamp_message = "НТС Велосити"
Я про это спрашивал очень давно. Ибо Velocity - станция Cargo Industries
NTS - это явно не Nanotrasen xxx, и я предположил и предполагаю, что это Нейтральная Транзитная Станция

2021-08-30 20:15 UTC, Fenriros commented
А у клоуна какая печать?

2021-08-30 20:15 UTC, atik1n commented
> А у клоуна какая печать?

HONK, как и на спрайте

2021-08-30 20:16 UTC, Fenriros commented
> 
> 
> > А у клоуна какая печать?
> 
> HONK, как и на спрайте

А у кого печать "переделывай"?

2021-08-30 20:17 UTC, atik1n commented
> > > А у клоуна какая печать?
> > 
> > 
> > HONK, как и на спрайте
> 
> А у кого печать "переделывай"?

У педалей и хамелеонка. Могу спрятать в теха

2021-08-30 22:14 UTC, atik1n commented
![image](https://user-images.githubusercontent.com/14612180/131412750-32c90912-c7cb-455f-b9a0-73b9bba29f41.png)

2021-08-31 11:09 UTC, atik1n commented on code/modules/paperwork/stamps.dm
> +	stamp_message = "НТС Велосити"
https://discord.com/channels/401030271417188353/820674320945905685/882192562755092510

2021-09-03 22:15 UTC, atik1n commented
Нет кнопки абстрактно запросить ревью, так что да

2021-09-08 19:57 UTC, volas commented on code/__HELPERS/text.dm
> +	t = replacetext(t, "\[nt\]", "<img src = bluentlogo.png />")
возможно с этим будут проблемы, если разрешить использовать ``[nt]`` всем. Технически - возможно большая нагрузка на клиента, если кто-то их наспамит до лимита. 

Я бы предложил оставить как было, либо сделать что бы заменялся только первый тэг в теле.

2021-09-08 19:59 UTC, atik1n commented on code/__HELPERS/text.dm
> +	t = replacetext(t, "\[nt\]", "<img src = bluentlogo.png />")
Он отрезается же у ручек
```
if(!istype(P, /obj/item/weapon/pen/chameleon))
		t = replacetext(t, "\[nt\]", "")
```
Но сделаю так, чтобы только один такой срабатывал, окей

2021-09-08 19:59 UTC, volas commented on code/modules/admin/topic.dm
> +			switch(tgui_alert(usr, "Всё НАСТОЛЬКО плохо? (злоупотреблять этой фичей плохо)",, list("ДА!1!","Отмена")))
не очень понимаю смысл второго алерта, возможно он нужен только для ``/obj/item/weapon/stamp/centcomm/bullshit``?

2021-09-08 20:05 UTC, volas commented on code/modules/admin/verbs/randomverbs.dm
> +		stamp_list[capitalize(S.name)] = S // the list that will be shown to the user to pick from
Отсортированный stamp_list можно было бы в список глобалов добавить, можешь посмотреть в сторону ``make_datum_references_lists``.

Или на этом этапе можно было бы не создавать объекты штапмов, которые нам потом всё равно не нужны, а использовать ``initial()``

2021-09-08 20:06 UTC, atik1n commented on code/modules/admin/verbs/randomverbs.dm
> +		stamp_list[capitalize(S.name)] = S // the list that will be shown to the user to pick from
Инишл нельзя использовать как минимум из-за кэпа

2021-09-08 20:19 UTC, atik1n commented on code/modules/admin/topic.dm
> +			switch(tgui_alert(usr, "Всё НАСТОЛЬКО плохо? (злоупотреблять этой фичей плохо)",, list("ДА!1!","Отмена")))
Да, там вложенность просрана

2021-09-09 22:46 UTC, LudwigVonChesterfield commented on code/modules/paperwork/stamps.dm
> +	name = "печать Cargo Industries"
а почему тут не переведено/адаптировано как-нибудь

2021-09-09 22:47 UTC, LudwigVonChesterfield commented on code/modules/paperwork/stamps.dm
> +	stamp_message = "Директор Отдела R&D" // https://wiki.taucetistation.org/Guide_to_Paperwork
а разве у нас нет теперь русского названия для R&D?

2021-09-09 23:12 UTC, LudwigVonChesterfield commented on code/modules/paperwork/stamps.dm
> +	stamp_message = "Директор Отдела R&D" // https://wiki.taucetistation.org/Guide_to_Paperwork
https://wiki.taucetistation.org/General_Directory

в глоссарии Директор Исследований и Разработок/Научный Руководитель

2021-09-22 13:58 UTC, atik1n commented
Решим и сделаем, брысь

2022-02-28 19:41 UTC, DarthSidiousPalpatine requested changes
Переделайте, пожалуйста.

2022-02-28 19:41 UTC, DarthSidiousPalpatine commented on code/modules/paperwork/stamps.dm
> +	stamp_message = "Отдел Поставок"
п

2022-02-28 19:41 UTC, DarthSidiousPalpatine commented on code/modules/paperwork/stamps.dm
> +	stamp_message = "Глава Персонала"
п

2022-02-28 19:41 UTC, DarthSidiousPalpatine commented on code/modules/paperwork/stamps.dm
> +	stamp_message = "Глава Службы Безопасности"
с б

2022-02-28 19:41 UTC, DarthSidiousPalpatine commented on code/modules/paperwork/stamps.dm
> +	stamp_message = "Главный Инженер"
и

2022-02-28 19:41 UTC, DarthSidiousPalpatine commented on code/modules/paperwork/stamps.dm
> +	name = "печать директора отдела R&D"
научного руководителя

2022-02-28 19:41 UTC, DarthSidiousPalpatine commented on code/modules/paperwork/stamps.dm
> +	stamp_message = "Директор Отдела R&D" // https://wiki.taucetistation.org/Guide_to_Paperwork
Научный руководитель

2022-02-28 19:41 UTC, DarthSidiousPalpatine commented on code/modules/paperwork/stamps.dm
> +	stamp_message = "Исследовательский Аванпост"
а

2022-02-28 19:41 UTC, DarthSidiousPalpatine commented on code/modules/paperwork/stamps.dm
> +	stamp_message = "Главный Врач"
в

2022-02-28 19:41 UTC, DarthSidiousPalpatine commented on code/modules/paperwork/stamps.dm
> +	name = "печать ОТКЛОНЕНО"
ОТКАЗАНО

2022-02-28 19:41 UTC, DarthSidiousPalpatine commented on code/modules/paperwork/stamps.dm
> +	stamp_message = "ОТКЛОНЕНО"
ОТКАЗАНО

2022-02-28 19:41 UTC, DarthSidiousPalpatine commented on code/modules/paperwork/stamps.dm
> +	name = "печать Отдела Внутренних Дел"
Отдел внутренних дел. Хехмда.
Перевод АВД меняем, думаю.

2022-02-28 19:41 UTC, DarthSidiousPalpatine commented on code/modules/paperwork/stamps.dm
> +	name = "печать Центрального Командования"
ц к

2022-02-28 19:41 UTC, DarthSidiousPalpatine commented on code/modules/paperwork/stamps.dm
> +	name = "печать Cargo Industries"
карго индастриз на вики

2022-03-09 09:57 UTC, LudwigVonChesterfield commented
если доделаешь ПР в текущем виде - откроем. но я бы советовал переводы с фичами не смешивать

2022-03-09 09:57 UTC, closed without merging