Gateway remap
TauCetiStation/TauCetiClassic pull request #7923
Opened 2021-09-06 00:55 UTC by Rahmanio

## Описание изменений
Было:
![Screenshot_1264](https://user-images.githubusercontent.com/67812445/132146510-b936ede6-7eed-47db-974c-71971db75c44.png)

Стало:
![Screenshot_1265](https://user-images.githubusercontent.com/67812445/132146522-041e6d98-a028-4f19-8cf9-f839dfd59d85.png)

Решил добавить GPS, дабы найти того, кто идёт в гейт. Добавлены инструменты, металл и вторая аптечка.
## Почему и что этот ПР улучшит
Гейт становится более безопасным при путешествиях(аптечки, gps). Нюкеры, используя гейт оказываются не в таком замкнутом помещении, застроить гейт очень быстро и уйти уже становится сложнее.
## Авторство
Rahmano
## Чеинжлог
:cl: Rahmano
* map[link]: Ремап гейтвея

2021-09-06 00:55 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2021-09-06 02:26 UTC, volas commented
> застроить гейт очень быстро и уйти уже становится сложнее

Был проход к гейту в 3 тайла, стал 1.

И раньше всё оборудование было за доступом глав, сейчас в общем

2021-09-06 10:54 UTC, Enerty reviewed
Помимо того о чем писал Волас, шкафчиков "Exile Implants" раньше было два, теперь один, раньше была только одна белая аптечка, теперь рядом еще зеленая и хелф аналайзер, который и так есть в белой аптечке, зачем это нужно, не понятно. На столе появились батарейка и зарядник для неё, а зачем? Слева кроме цветка все пронстранство полностью пустое, да и в целом комнаты гейтвея пустые. Единственные два окна через которые можно лазерами простреливать загорожены шкафчиками ERVOS, которых кстати, теперь почему-то два. При желании нюкеры могут закрыть створки чем-нибудь и просто выйти в теха из гейтвея, раньше подобное было сложнее провернуть, к тому же пространства стало значительно больше, нюкеры не будут так открыты как раньше, сильные баффы в общем, запрашиваю баланс департамент, и возможно, было бы не плохо, получить воут на форуме

2021-09-06 11:24 UTC, TauKitty commented
This pull request has been mentioned on **Tau Ceti Station Forum**. There might be relevant details there:

https://forum.taucetistation.org/t/obsuzhdenie-revorka-gejta-i-sily-nyuki-kogda-ona-idyot-cherez-gejt/28045/1

2021-09-06 18:10 UTC, Rahmanio commented
> > застроить гейт очень быстро и уйти уже становится сложнее
> 
> Был проход к гейту в 3 тайла, стал 1.
> 
> И раньше всё оборудование было за доступом глав, сейчас в общем

Учёл все недочёты и ревью Энерти, карта переделана.

2021-09-16 01:32 UTC, Rahmanio commented
зря

2021-09-18 15:02 UTC, kildjen commented
Я мапдепартамент. Мне нравится изменение.

2021-09-19 06:47 UTC, BesumniiChebureck requested changes
Я тоже мап департамент, мне тоже нравится, но пока что не апрув, из-за нескольких проблем, на которые автору я уже указал (а то ещё замержите ненароком)

2021-09-19 07:26 UTC, BesumniiChebureck approved these changes
@KIBORG04

2021-09-19 11:44 UTC, merged