Добавляет во флаффы маленькую коробку.
TauCetiStation/TauCetiClassic pull request #7928
Opened 2021-09-06 15:53 UTC by KIBORG04

## Описание изменений
Добавление абстрактной коробочки во флаффы. 
Её характеристики:
 - Помещается в карман
 - Вмещает только самые маленькие вещи
 - 6 слотов
 - Нельзя открыть вне руки
 - Нельзя оставить открытой, а потом положить куда-то с открытым инвентарем
 - нельзя установить инхеды (из-за размера коробки)
 
пример файла:
![image](https://user-images.githubusercontent.com/26389417/132240560-f6846abb-629b-4257-b59e-d2023b90a06c.png)

## Почему и что этот ПР улучшит
Больше выбора.

## Авторство
Я, а еще меня попросили.

## Чеинжлог
:cl:
 - tweak: Счастливые обладатели флафф слота смогут себе нарисовать коробочку.

2021-09-06 15:53 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2021-09-06 16:28 UTC, LudwigVonChesterfield commented on code/modules/fluff/customitems.dm
> +		user.put_in_hands(src)
можно чтобы если успешно положилась в рукой то пытаться открыть дальше, не?

2021-09-06 16:29 UTC, LudwigVonChesterfield commented
подсумок на 6 слотов в карман теперь может быть вашим всего за 5$

2021-09-06 16:36 UTC, KIBORG04 commented on code/modules/fluff/customitems.dm
> +		user.put_in_hands(src)
Можно, но так ещё меньше похоже на подсумок

2021-09-08 22:51 UTC, LudwigVonChesterfield requested changes
мне в моё время пришлось воевать за подсумки и мне внушали что они вот имба лютая и трали-вали... а тут коробочка на 6 предметов вместо 2-ух (или трёх)...

так ещё и за донат (по сути)

лично я из-за этого против

хотя если кто-то другой придёт и скажет что за - я не удивлюсь, у нас тем более уже есть похожие предметы-хранилища с такой же фишкой(6 слотов в карман :) )

2021-09-18 15:04 UTC, KIBORG04 commented
Не, я жду сообщения с выше

2021-10-02 18:43 UTC, closed without merging