xenoarcheology part code readdability, some artifact changes
TauCetiStation/TauCetiClassic pull request #7933
Opened 2021-09-08 04:22 UTC by Morar1

## Описание изменений
**Убрано**
Большинство рандомных проценты в активации эффектов артефактов.
Рандомные проценты для активации артефактов.
Триггер артефакта от спрайта.
**Добавлено**
Бутылка воды со случайными реагентами в находки.
Уничтоженных мехи в находки.
Стоимость на активацию эффекта артефакта, аура тратит весь заряд артефакта, тронуть тратит 3, аура ничего не стоит.
Сила некоторых эффектов увеличивается/уменьшается от потраченного заряда.
Некоторые эффекты артефактов уменьшаются с увеличением защиты от артефактов.
Эффект артефакта: гравитация. Притягивает или отдаляет моба.
Эффект артефакта: свет. Дает свет, либо удаляет его рядом.
Эффект артефакта: звук. Воспроизводит звуки.
Артефакты можно уничтожать.
Эффект при уничтожении артефакта для некоторых типов эффектов.
**Другое**
Прок get_unrestricted_random_reagent_id возвращающий рандомный реагент(запрещены бейсик реагенты, еда и напитки, и некоторые другие).
heal_overall_damage распределяет хил равномерно по всему телу 👉👈 (как и в #7799).
## Почему и что этот ПР улучшит
Часть кода стала более читабильнее(наверно).
fixes #7829
## Авторство

## Чеинжлог
🆑
* add[link]: Новые эффекты артефактов
* add: Сломанные мехи можно раскопать
* fix: Говорящая маска не заставляет игрока говорить в гостчат

2021-09-08 04:22 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2021-09-08 04:35 UTC, Morar1 commented on code/modules/research/xenoarchaeology/artifact/artifact_unknown.dm
> +	if(my_effect?.trigger == TRIGGER_PROXY || secondary_effect?.trigger == TRIGGER_PROXY)
можно обратно в процессинг кинуть мб

2021-09-08 07:24 UTC, LudwigVonChesterfield commented on code/__DEFINES/xenoarchaeology.dm
> +#define ARTIFACT_ALL_RELEASE_METHODS list(\
эти слешики в конце не нужны

2021-09-08 07:25 UTC, LudwigVonChesterfield commented on code/datums/spells/conjure.dm
> +	random_unrestricted = FALSE
Мне не нравится такое решение. Пулы реагентов для разных рандомов думаю разные. Лучше сделай какой-то блэклист для ксеноархеологии ичто-ли. (А ещё лучше вайтлист)

2021-09-08 07:26 UTC, LudwigVonChesterfield commented on code/modules/mob/living/carbon/human/human_damage.dm
> +		BP.heal_damage(brute_per_part, burn_per_part)
стелсонёрф уймы вещей хилящих по площади всё тело..

2021-09-08 07:28 UTC, LudwigVonChesterfield commented on code/modules/research/xenoarchaeology/artifact/effects/feelings.dm
> +#define ARTIFACT_BAD_MESSAGES_MINOR list(\
У нас теперь есть система настроений. Это могло бы её использовать.

2021-09-08 14:14 UTC, Morar1 commented on code/modules/research/xenoarchaeology/artifact/effects/feelings.dm
> +#define ARTIFACT_BAD_MESSAGES_MINOR list(\
Да, я просто ветку не обновлял давно, запилю

2021-09-08 14:16 UTC, Morar1 commented on code/modules/mob/living/carbon/human/human_damage.dm
> +		BP.heal_damage(brute_per_part, burn_per_part)
Хилят ровно столько же как и до этого, но вообще атомарность все дела...дааа...можно убрать...

2021-09-08 14:28 UTC, LudwigVonChesterfield commented on code/modules/mob/living/carbon/human/human_damage.dm
> +		BP.heal_damage(brute_per_part, burn_per_part)
как оно может хилить ровно столько же, если теперь лечение делится на количество частей тела.

2021-09-08 15:52 UTC, Morar1 commented on code/__DEFINES/xenoarchaeology.dm
> +#define ARTIFACT_ALL_RELEASE_METHODS list(\
Нужны

2021-09-08 16:13 UTC, KIBORG04 commented on code/datums/mood_events/artifact_events.dm
> +/datum/mood_event/good_major
Сделай тип этих мудов более конкретным, а то прям как-то размыто очень

2021-09-08 16:32 UTC, KIBORG04 commented on code/modules/research/xenoarchaeology/artifact/effect.dm
> +	///purely used for getDescription
Если ты через вскод кодишь, то скачай пожалуйста плагин `Trailing Spaces` и поубирай в конце пробелы

2021-09-08 16:35 UTC, KIBORG04 commented on code/modules/research/xenoarchaeology/artifact/effects/cellcharge.dm
> +			to_chat(user, "<span class='notice'>SYSTEM ALERT: Large energy boost detected!</span>")
150 единиц, вот это ЛАРДЖ ЭНЕРДЖИ БУСТ

2021-09-08 16:36 UTC, KIBORG04 commented on code/modules/research/xenoarchaeology/artifact/effect.dm
>  /datum/artifact_effect
Из этой штуки может получиться классная компонента

2021-09-08 16:47 UTC, KIBORG04 commented on code/modules/research/xenoarchaeology/artifact/artifact_unknown.dm
> +	if(istype(mover, /mob))
```suggestion
	if(ismob(mover))
```

2021-09-08 16:49 UTC, KIBORG04 commented on code/modules/research/xenoarchaeology/artifact/artifact_unknown.dm
> +		secondary_effect.ToggleActivate(0)
```suggestion
		secondary_effect.ToggleActivate(FALSE)
```

2021-09-08 16:50 UTC, KIBORG04 commented on code/modules/research/xenoarchaeology/artifact/artifact_unknown.dm
> +			qdel(src)
Че за кринж. Просто сделай прок update_health и там хендли здоровье и там же и удаляй артифакт

2021-09-08 16:52 UTC, KIBORG04 commented on code/modules/research/xenoarchaeology/artifact/artifact_unknown.dm
> +	if((my_effect?.trigger >= TRIGGER_HEAT && my_effect?.trigger <= TRIGGER_NITRO) ||\
Так триггеры еще и не просто дефайны, а распределены по цифрам.. Капец.

2021-09-08 16:56 UTC, KIBORG04 commented on code/modules/research/xenoarchaeology/artifact/artifact_unknown.dm
> +			else toggle_effects_off(TRIGGER_NITRO)
1. Возможно отсутствие переноса строка у этих else и норм, но если кому-то еще не понравится, то стоит добавить
2. Эту всю лесенку можно попробовать схлопнуть. С температурой нет, а вот с газами да.
3. У тебя комментарий //HEAT ACTIVATION нужно на строчку выше перенести

2021-09-08 16:57 UTC, KIBORG04 commented on code/modules/research/xenoarchaeology/artifact/artifact_unknown.dm
> +			if(world.time >= last_scan + scan_delay)
Мне кажется, раньше это было сделано для некой оптимизации. Сейчас же это не нужно

2021-09-08 16:57 UTC, Zmey25 commented
Слапни в канале вики в дисе, если вмержат

2021-09-08 16:58 UTC, KIBORG04 commented on code/modules/research/xenoarchaeology/artifact/artifact_unknown.dm
> +			if(world.time >= last_scan + scan_delay)
А, или нет. Чтобы не накидывался на одного чела слишком часто.

2021-09-08 16:58 UTC, KIBORG04 commented on code/modules/research/xenoarchaeology/artifact/artifact_unknown.dm
> +		//TRIGGER_PROXY ACTIVATION
Комментарий повыше

2021-09-08 17:01 UTC, KIBORG04 commented on code/modules/research/xenoarchaeology/artifact/artifact_unknown.dm
> +		if(istype(W, /obj/item/weapon/melee/energy) ||\
```suggestion
		else if(istype(W, /obj/item/weapon/melee/energy) ||\
```

2021-09-08 17:03 UTC, KIBORG04 commented on code/modules/research/xenoarchaeology/artifact/artifact_unknown.dm
> +		if(iswelder(W))
```suggestion
		else if(iswelder(W))
```

2021-09-08 17:03 UTC, KIBORG04 commented on code/modules/research/xenoarchaeology/artifact/artifact_unknown.dm
> +		if(istype(W, /obj/item/weapon/lighter))
```suggestion
		else if(istype(W, /obj/item/weapon/lighter))
```

2021-09-08 17:04 UTC, KIBORG04 commented on code/modules/research/xenoarchaeology/artifact/artifact_unknown.dm
> +	if(world.time >= last_time_touched + touch_cooldown)
```suggestion
	else if(world.time >= last_time_touched + touch_cooldown)
```
Или это нормально, что кинутый предмет форсит и ему пишется сообщение?

2021-09-08 17:08 UTC, KIBORG04 commented on code/modules/research/xenoarchaeology/artifact/artifact_unknown.dm
> +		rebuild_zone()
А что если ребилдить эту зону только если артифакт полностью остановился?

2021-09-08 17:16 UTC, KIBORG04 commented on code/modules/research/xenoarchaeology/artifact/effect.dm
> +	if(!QDELING(holder))
Эта строчка очень похожа на какой-то костыль, будто бы где-то ссылки не отвязываются и ты не хочешь с этим разбираться.

2021-09-08 17:16 UTC, Morar1 commented on code/modules/research/xenoarchaeology/artifact/artifact_unknown.dm
> +			if(world.time >= last_scan + scan_delay)
>для некой оптимизации
Наверно так и было
Я сначала сделал через сигналы все, потом переделал в процессинг обратно, хз норм или нет так часто зону ребилдить on /move с сигналами
>Чтобы не накидывался на одного чела слишком часто.
Триггер запускает процессинг эффекта только

2021-09-08 17:17 UTC, KIBORG04 commented on code/modules/research/xenoarchaeology/artifact/effect.dm
> +		STOP_PROCESSING(SSobj, src)
наверное стоит оканчивать процессинг и в дестрое

2021-09-08 17:17 UTC, Morar1 commented on code/modules/research/xenoarchaeology/artifact/artifact_unknown.dm
> +	if(world.time >= last_time_touched + touch_cooldown)
Да без разницы, но поменял

2021-09-08 17:18 UTC, Morar1 commented on code/modules/research/xenoarchaeology/artifact/effect.dm
> +		STOP_PROCESSING(SSobj, src)
Он же закончится когда артефакт удалится?

2021-09-08 17:19 UTC, KIBORG04 commented on code/modules/research/xenoarchaeology/artifact/effect.dm
> +		STOP_PROCESSING(SSobj, src)
Закончится. Но вроде как закончится в итерации SSobj, а не когда нужно. Короче хз.

2021-09-08 17:20 UTC, KIBORG04 commented on code/modules/research/xenoarchaeology/artifact/effect.dm
> +		toplevelholder = toplevelholder.loc
```suggestion
	var/atom/toplevelholder = get_turf(holder)
```

2021-09-08 17:21 UTC, KIBORG04 commented on code/modules/research/xenoarchaeology/artifact/effect.dm
> +		toplevelholder = toplevelholder.loc
Хотя как-то странно, вроде тут и берется турф, но потом ниже почему-то проверка на исхумана

2021-09-08 17:21 UTC, KIBORG04 commented on code/modules/research/xenoarchaeology/artifact/effect.dm
> +		toplevelholder = toplevelholder.loc
Хотя все ок

2021-09-08 17:23 UTC, KIBORG04 commented on code/modules/research/xenoarchaeology/artifact/effect.dm
> +/datum/artifact_effect/proc/DoEffectDestroy()
Стоит добавить ретурн в таких пустых функциях для читаемости. Это же все такие не плюсы

2021-09-08 17:23 UTC, KIBORG04 commented on code/modules/research/xenoarchaeology/artifact/effect.dm
> +		return NO_ANOMALY_PROTECTION
Довольно странно, что это не метод хуманов

2021-09-08 17:25 UTC, KIBORG04 commented on code/modules/research/xenoarchaeology/artifact/effect.dm
> +		return NO_ANOMALY_PROTECTION
Или есть артефакты, работающие не только на людей?

> Calculates mob effect protection

2021-09-08 17:26 UTC, KIBORG04 commented on code/modules/research/xenoarchaeology/artifact/effects/cellcharge.dm
> +	used_power = .
```suggestion
	var/used_power = .
```

2021-09-08 17:28 UTC, Morar1 commented on code/modules/research/xenoarchaeology/artifact/effect.dm
> +		return NO_ANOMALY_PROTECTION
Одежда только у людей есть.

>Или есть артефакты, работающие не только на людей?

Хил/дамаг например

2021-09-08 17:31 UTC, KIBORG04 commented on code/modules/research/xenoarchaeology/artifact/effect.dm
> +		return NO_ANOMALY_PROTECTION
В таком случае, у функции измени параметры

2021-09-08 17:32 UTC, KIBORG04 commented on code/modules/research/xenoarchaeology/artifact/effects/cellcharge.dm
> +			to_chat(M, "<span class='notice'>SYSTEM ALERT: Energy boost detected!</span>")
Блин, надо бы придумать какую-то систему компонент 2.0, с помощью которой можно было бы удобно с этим обращаться. Мол, чтобы один циклом все батарейки чекнуть, но если привязывать на сигналы, то это какой-то был бы антипаттерн чтоли.

2021-09-08 17:36 UTC, KIBORG04 commented on code/modules/research/xenoarchaeology/artifact/artifact_unknown.dm
> +			if(world.time >= last_scan + scan_delay)
Я понял один смешной момент. Тут делей в 2 секунды, процессинг тоже вызывается раз в 2 секунды. В итоге эта штука просто не работает

2021-09-08 17:39 UTC, KIBORG04 commented on code/modules/research/xenoarchaeology/artifact/effects/health.dm
> +	for(var/mob/living/receiver in range(range, curr_turf))
Странно, что гравитация работает в oview, а это просто в радиусе

2021-09-08 17:40 UTC, KIBORG04 commented on code/modules/research/xenoarchaeology/artifact/effects/health.dm
> +	receiver.updatehealth()
take_overall_damage и так апдейтит хп

2021-09-08 17:40 UTC, KIBORG04 commented on code/modules/research/xenoarchaeology/artifact/effects/health.dm
> +	receiver.updatehealth()
Хил тоже апдейтит хп

2021-09-08 17:41 UTC, KIBORG04 commented on code/modules/research/xenoarchaeology/artifact/effects/health.dm
> +	receiver.updatehealth()
не нужно

2021-09-08 17:42 UTC, KIBORG04 commented on code/modules/research/xenoarchaeology/artifact/effects/noise.dm
> +	var/static/list/possible_noises = list(SOUNDIN_EXPLOSION, SOUNDIN_SHATTER, SOUNDIN_CLOWNSTEP, SOUNDIN_SCARYSOUNDS)
SOUNDIN_CLOWNSTEP входит в SOUNDIN_SCARYSOUNDS

2021-09-08 17:43 UTC, KIBORG04 commented on code/modules/research/xenoarchaeology/artifact/effects/radiate.dm
> +		M.updatehealth()
апдейт не нужен

2021-09-08 17:43 UTC, KIBORG04 commented on code/modules/research/xenoarchaeology/artifact/effects/radiate.dm
> +		M.updatehealth()
апдейт не нуженапдейт не нужен

2021-09-08 17:45 UTC, KIBORG04 commented on code/modules/research/xenoarchaeology/finds/finds_defines.dm
> -	switch(find_type)
Соболезную челу в прошлом, который это расписывал

2021-09-08 17:58 UTC, Morar1 commented on code/modules/research/xenoarchaeology/artifact/effect.dm
> +	if(!QDELING(holder))
Я забыл это удалить это просто

2021-09-08 17:59 UTC, Morar1 commented on code/modules/research/xenoarchaeology/artifact/artifact_unknown.dm
> +			if(world.time >= last_scan + scan_delay)
Это проверка на кодера?

2021-09-08 18:01 UTC, KIBORG04 commented on code/modules/research/xenoarchaeology/artifact/artifact_unknown.dm
> +			if(world.time >= last_scan + scan_delay)
Почему? Я просто подметил, что поидее, этот ласт_скан тупо не рабоает, ибо внутренний делей и делей SSobj одинаковый

2021-09-08 18:06 UTC, Morar1 commented on code/modules/research/xenoarchaeology/artifact/artifact_unknown.dm
> +		rebuild_zone()
>Могу подсказать как

Мув сигнал + таймер и invoke_async->rebuild_zone() если таймер меньше какого-то значения, норм будет?

2021-09-08 18:08 UTC, KIBORG04 commented on code/modules/research/xenoarchaeology/artifact/artifact_unknown.dm
> +		rebuild_zone()
Не, у таймера есть флаг оверрайда и уникальности. Ты можешь каждый мув пытаться запустить один и тот же таймер. И если он все же сработал за условных 3 секунды, то это означает, что новый таймер не запустился и не заменил этот.

Вроде людук для прибавки настроения от разговоров такое делал.

2021-09-08 18:10 UTC, Morar1 commented on code/modules/research/xenoarchaeology/artifact/artifact_unknown.dm
> +			if(world.time >= last_scan + scan_delay)
Блин, а реально...

2021-09-09 15:05 UTC, Morar1 commented on code/modules/research/xenoarchaeology/artifact/effects/gravity.dm
> +	var/turf/curr_turf = get_turf(holder)
я полностью без понятия почему тут holder-а не видит, но если смотреть через ВВ эффект, holder есть

2021-09-09 15:05 UTC, Morar1 commented on code/modules/research/xenoarchaeology/artifact/effects/noise.dm
> +	playsound(holder, pick(sound_type), VOL_EFFECTS_MASTER)
тоже самое что и в gravity

2021-09-09 15:36 UTC, Morar1 commented on code/modules/research/xenoarchaeology/artifact/effects/gravity.dm
> +	var/turf/curr_turf = get_turf(holder)
А...

2021-09-09 16:32 UTC, LudwigVonChesterfield commented on code/modules/research/xenoarchaeology/artifact/effects/cellcharge.dm
> +			to_chat(M, "<span class='notice'>SYSTEM ALERT: Energy boost detected!</span>")
ты почти дошёл до изобретения Entity Component System

2021-09-09 22:24 UTC, LudwigVonChesterfield commented on code/datums/mood_events/artifact_events.dm
> +	description = "<span class='nicegreen'>Wooo! What is going on?.</span>"
```suggestion
	description = "<span class='nicegreen'>Wooo! What is going on?</span>"
```

2021-09-09 22:27 UTC, LudwigVonChesterfield commented on code/modules/research/xenoarchaeology/artifact/artifact_unknown.dm
> +/obj/machinery/artifact/proc/rebuild_zone()
я понимаю что тут происхоидт и почему, но я предвижу что это может быть жуткий лагодром. ты с ТГ портировал?

2021-09-09 22:27 UTC, LudwigVonChesterfield commented on code/modules/research/xenoarchaeology/artifact/artifact_unknown.dm
> +	for(var/turf/T in orange(3, src))
у нас есть RANGE_TURFS, можно его заюзать?

2021-09-09 22:39 UTC, LudwigVonChesterfield commented on code/modules/research/xenoarchaeology/artifact/effect.dm
>  /datum/artifact_effect
а почему компонента...

2021-09-09 22:42 UTC, LudwigVonChesterfield commented on code/modules/research/xenoarchaeology/artifact/effects/celldrain.dm
> +	for(var/obj/item/weapon/stock_parts/cell/C in range(range, center))
думаю тут, и везде в подобных местах стоит range() не заново каждый раз вызывать, а что-то типо

```
var/list/visible_items = range(range,center)
for(var/A in visible_items)
for(var/C in visible_items)

и так далее.

(А ещё лучше, чтобы ещё и не проходиться по всему списку заново каждый раз, сделать у этого эффекта функцию-визитёр - discharge(atom/A), которая бы уже проверяла тип, и делала с ним все эти непотребства)

((Лучше всего очевидно было бы чтобы это было функцией объекта, а ещё круче что-то типо "компоненты", и ты у него вызывал C.discharge(), но я не могу тебя заставить такой большой рефактор сделать))

2021-09-09 22:43 UTC, LudwigVonChesterfield requested changes
Для меня огромное "нет" - тут это то как хендлятся реагенты. Почему для рандома реагентов в ксеноархеологии переменная на реагенте, а не список реагентов которые можно нарандомить? Почему любой добавленный реагент, для щитспавна к примеру, должен знать о том что эта переменная где-то там влияет на ксеноархеологию.

Тем более другие места рандомящие могут эти реагенты хотеть, думаю тут надо переделать на список реагентов которые рандомишь - а не на флажёк у реагента, вот.

2021-09-10 04:15 UTC, KIBORG04 commented on code/modules/research/xenoarchaeology/artifact/artifact_unknown.dm
> +/obj/machinery/artifact/proc/rebuild_zone()
Это не с тг, а с алтаря капелланов. Но там зоны реже пересобираются

2021-09-10 12:06 UTC, Morar1 commented on code/modules/research/xenoarchaeology/artifact/artifact_unknown.dm
> +/obj/machinery/artifact/proc/rebuild_zone()
>но я предвижу что это может быть жуткий лагодром

Хз, зона может быть пока что только у кристалла с астероида и тот стоит на месте всегда. А если и движется, то пересобирается через секунды 3 без движения

>Это не с тг, а с алтаря капелланов.

Да

2021-09-10 16:25 UTC, KIBORG04 commented on code/modules/research/xenoarchaeology/artifact/artifact_unknown.dm
> +	for(var/turf/T in RANGE_TURFS(3, src))
Опа, раз уж так, то предлагаю заюзать секретный способ оптимизации:
```
for(var/turf/T as anything in RANGE_TURFS(3, src))
```

2021-09-10 16:57 UTC, LudwigVonChesterfield commented on code/modules/research/xenoarchaeology/artifact/artifact_unknown.dm
> +	for(var/turf/T in RANGE_TURFS(3, src))
я уже где-то предлагал тут юзать RANGE_TURFS вместо orange...

2021-09-10 17:00 UTC, LudwigVonChesterfield commented on code/modules/reagents/_chemistry.dm
> +#define  RESTRICTED_CHEM_LIST list(\
можно уточнить что это химикаты конкретно для ксеноархеологии?

ещё, насколько странно что это дефайн (список который будет везде инициализироваться со всеми этими элементами), а не глобальный список?

ещё очень круто было бы его сделать в формате "кеша", чтобы не list("reagent1", "reagent2"), а
```
list(
"reagent1" = TRUE,
"reagent2" = TRUE,
)
```
потому-что проверки на наличие в кеше (if(cache[key])) быстрее чем на наличие в списке (if(element in list))

2021-09-10 17:54 UTC, Morar1 commented on code/modules/reagents/_chemistry.dm
> +#define  RESTRICTED_CHEM_LIST list(\
> формате "кеша"

2021-09-13 18:38 UTC, Daoprotoss commented
А можно еще в этом ПРе добавить бумажкам скана артефактов хоть какую-то научную ценность?..

2021-09-13 21:39 UTC, LudwigVonChesterfield approved these changes

2021-09-14 08:23 UTC, LudwigVonChesterfield approved these changes

2021-09-14 08:41 UTC, merged