Переводы стенок и багфикс
TauCetiStation/TauCetiClassic pull request #7936
Opened 2021-09-08 13:56 UTC by Zickusable

## Описание изменений
Переоткрытие #6920 
Fixes #6824
Добавил список возможных для создания стен не из стали.
Перевод различных взаимодействий со станами и их каркасом.
## Почему и что этот ПР улучшит
Локализация
## Авторство

## Чеинжлог
:cl:
- bugfix: Больше нельзя использовать материалы на каркасах стен, если из такого материала их не существует.
- ru: Перевод различных взаимодействий со стенами и их каркасом.

2021-09-08 13:56 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2021-09-08 15:42 UTC, BesumniiChebureck commented
Тебя просили не делать багфиксы и переводы в одном ПРе. Спасибо что услышал.

2021-09-08 15:44 UTC, Zickusable commented
Это переоткрытие ПРа, который я закрыл, т.к. криво замержилось, сейчас я все поправил. А вообще я больше так не делаю

2021-09-13 21:26 UTC, LudwigVonChesterfield commented
сделай два разных ПР-а а то я не могу мёржить багфикс потому-что ждём когда транслейшон департментом проверят

2021-09-14 13:54 UTC, Zickusable commented
Полгода прошло. Как можно заметить, я не спешу, да и в общем мне лень.

2021-09-21 16:17 UTC, Zickusable commented
Не души, машина

2021-09-22 12:20 UTC, kiVts commented
Вот это похуй человеку, и на просьбу, и на все остальное. Я хуею

2021-10-06 12:33 UTC, Zickusable commented
Не души

2022-02-22 08:28 UTC, bowlofsoup4ik requested changes
есть ошибки, но их не особо много и они, как правило, повторяются. 

действия с ссылками не переводим к слову.

2022-02-22 08:28 UTC, bowlofsoup4ik commented on code/game/turfs/simulated/walls.dm
> +				to_chat(user, "<span class='notice'>Вы сжигаете грибок инструментом.</span>")
костыль. просто не переводи эту фразу

2022-02-22 08:28 UTC, bowlofsoup4ik commented on code/game/turfs/simulated/walls.dm
> +		to_chat(user, "<span class='notice'>Вы начинаете сверлить сквозь стену.</span>")
сверлиться

2022-02-22 08:28 UTC, bowlofsoup4ik commented on code/game/turfs/simulated/walls.dm
> +				to_chat(user, "<span class='notice'>Вы удалили внешнее покрытие.</span>")
сняли

2022-02-22 08:28 UTC, bowlofsoup4ik commented on code/game/turfs/simulated/walls.dm
> +				to_chat(user, "<span class='notice'>Вы закончили ремонт стены.</span>")
завершили

2022-02-22 08:28 UTC, bowlofsoup4ik commented on code/game/turfs/simulated/walls.dm
> +			to_chat(user, "<span class='notice'>Нужно больше топлива.</span>")
больше топлива для чего? для завершения этого действия.

2022-02-22 08:28 UTC, bowlofsoup4ik commented on code/game/turfs/simulated/walls.dm
> +				to_chat(user, "<span class='notice'>Вы удалили внешнее покрытие.</span>")
сняли внешнее покрытие

2022-02-22 08:28 UTC, bowlofsoup4ik commented on code/game/turfs/simulated/walls.dm
> +				to_chat(user, "<span class='notice'>Вы просверлили последнюю укрепленную пластину.</span>")
ваша дрель прорывается сквозь

2022-02-22 08:28 UTC, bowlofsoup4ik commented on code/game/turfs/simulated/walls_mineral.dm
> +	desc = "Стена с серебряным покрытием. Блестит!"
забавноее будет перевести "блестяшка!", но это уже на вкус и цвет

2022-02-22 08:28 UTC, bowlofsoup4ik commented on code/game/turfs/simulated/walls_reinforced.dm
> +				to_chat(user, "<span class='notice'>Вы сжигаете грибок инстурментом.</span>")
инструментом. и вообще подобное не нужно переводить, тут [src] есть

2022-02-22 08:28 UTC, bowlofsoup4ik commented on code/game/turfs/simulated/walls_reinforced.dm
> +			to_chat(user, "<span class='notice'>Укрепленная стена рассыпается под воздействием предмета.</span>")
не переводи такое, "под воздействием предмета" люто всрато звучит, лучше оставить без перевода до системы склоненияй

2022-02-22 08:28 UTC, bowlofsoup4ik commented on code/game/turfs/simulated/walls_reinforced.dm
> +			to_chat(user, "<span class='warning'>Нужно больше топлива.</span>")
доя завершения этого действия

2022-02-22 08:28 UTC, bowlofsoup4ik commented on code/game/turfs/simulated/walls_reinforced.dm
> +					to_chat(user, "<span class='notice'>Нужно больше топлива.</span>")
для завершения этого действия

2022-02-22 08:28 UTC, bowlofsoup4ik commented on code/game/turfs/simulated/walls_reinforced.dm
> +						to_chat(user, "<span class='notice'>Вы удалили болты, закрепляющие поддерживающий каркас.</span>")
сняли поддерживающие балки

2022-02-22 08:28 UTC, bowlofsoup4ik commented on code/game/turfs/simulated/walls_reinforced.dm
> +							to_chat(user, "<span class='notice'>Вы убрали поддерживающий каркас.</span>")
не убрали, они сами отваливаются после срезания

2022-02-22 08:28 UTC, bowlofsoup4ik commented on code/game/turfs/simulated/walls_reinforced.dm
> +					to_chat(user, "<span class='notice'>Нужно больше топлива.</span>")
для завершения этого действия

2022-02-22 08:28 UTC, bowlofsoup4ik commented on code/game/turfs/simulated/walls_reinforced.dm
> +				to_chat(user, "<span class='notice'>Вы начинаете ослаблять болты, которые закрепляют поддерживающий каркас.</span>")
поддерживаюющие балки

2022-02-22 08:28 UTC, bowlofsoup4ik commented on code/game/turfs/simulated/walls_reinforced.dm
> +					to_chat(user, "<span class='notice'>Вы начинаете разрезать поддерживающий каркас.</span>")
поддерживающие балки

2022-02-22 08:28 UTC, bowlofsoup4ik commented on code/game/turfs/simulated/walls_reinforced.dm
> +				to_chat(user, "<span class='notice'>Вы начинаете разрезать поддерживающий каркас.</span>")
балки поддерживающие

2022-02-22 08:28 UTC, bowlofsoup4ik commented on code/game/turfs/simulated/walls_reinforced.dm
> +						to_chat(user, "<span class='notice'>Вы убрали поддерживающий каркас.</span>")
не убрали, ты срезал их и эти балки сами вывалились

2022-02-22 08:28 UTC, bowlofsoup4ik commented on code/game/turfs/simulated/walls_reinforced.dm
> +		to_chat(user, "<span class='notice'>Вы начинаете сверлить сквозь укрепленную стену.</span>")
просверливаться сквозь

2022-02-22 08:28 UTC, bowlofsoup4ik commented on code/game/turfs/simulated/walls_reinforced.dm
> +				to_chat(user, "<span class='notice'>Вы просверлили последнюю укрепленную пластину.</span>")
дрель прорвалась/просверлилась сквозь

2022-02-22 08:28 UTC, bowlofsoup4ik commented on code/game/turfs/simulated/walls_reinforced.dm
> +				to_chat(user, "<span class='notice'>Вы закончили ремонтировать укрепленную стену.</span>")
завершили ремонт укреплённой стены

2022-02-22 08:30 UTC, bowlofsoup4ik commented
проверил я ваш транслейшон. давайте нам уже нормальные стены

2022-02-22 09:58 UTC, Zickusable commented on code/game/objects/structures/girders.dm
> +		to_chat(user, "<span class='notice'>Вы начинаете разрезать каркас на куски.</span>")
Там плазморезак и каркас все же не срезают, как что-то торчащее, а разрезают на листы металла обратно.

2022-02-22 10:03 UTC, Zickusable commented on code/game/objects/structures/girders.dm
> +		to_chat(user, "<span class='notice'>Вы просверлили каркас!</span>")
Сообщение приходит после того, как пробурился. 'Просверливаетесь' звучит будто это человек-бур из комиксов

2022-02-22 10:12 UTC, DarthSidiousPalpatine requested changes
Всё, дальше я устал. Вот небольшой списочек из 31-й строчки.

2022-02-22 10:12 UTC, DarthSidiousPalpatine commented on code/game/turfs/simulated/walls.dm
> +	to_chat(user, "<span class='notice'>Вы толкаете стену, но ничего не происходит!</span>")
"Вы бессмысленно толкаете стену"

2022-02-22 10:12 UTC, DarthSidiousPalpatine commented on code/game/turfs/simulated/walls.dm
> +				to_chat(user, "<span class='notice'>Вы сжигаете грибок инструментом.</span>")
++
Такое себе решение, не переводи лучше.

2022-02-22 10:12 UTC, DarthSidiousPalpatine commented on code/game/turfs/simulated/walls.dm
> +			to_chat(user, "<span class='notice'>Стена рассыпается под воздействием [W.name].</span>")
Под воздействием Гаечный ключ?
"[W.name] разрушает стену"
"[W.name] крошит стену"

2022-02-22 10:12 UTC, DarthSidiousPalpatine commented on code/game/turfs/simulated/walls.dm
> +			to_chat(user, "<span class='notice'>Вы бьете стену энергетическим мечом; термит вспыхивает!</span>")
Вы уверены что его переведут именно как "Энергетический меч"?

2022-02-22 10:12 UTC, DarthSidiousPalpatine commented on code/game/turfs/simulated/walls.dm
> +			to_chat(user, "<span class='warning'>Вы начинаете ремонтировать стену.</span>")
"Вы ремонтируете стену"

2022-02-22 10:12 UTC, DarthSidiousPalpatine commented on code/game/turfs/simulated/walls.dm
> +				to_chat(user, "<span class='notice'>Вы закончили ремонт стены.</span>")
"Вы отремонтировали стену"

2022-02-22 10:12 UTC, DarthSidiousPalpatine commented on code/game/turfs/simulated/walls.dm
> +			to_chat(user, "<span class='notice'>Вы начинаете разрезать внешнее покрытие.</span>")
"Вы разрезаете обшивку"

2022-02-22 10:12 UTC, DarthSidiousPalpatine commented on code/game/turfs/simulated/walls.dm
> +				to_chat(user, "<span class='notice'>Вы удалили внешнее покрытие.</span>")
"Вы сняли обшивку"

2022-02-22 10:12 UTC, DarthSidiousPalpatine commented on code/game/turfs/simulated/walls.dm
> +		to_chat(user, "<span class='notice'>Вы начинаете разрезать внешнее покрытие.</span>")
"Вы разрезаете обшивку"

2022-02-22 10:12 UTC, DarthSidiousPalpatine commented on code/game/turfs/simulated/walls.dm
> +				to_chat(user, "<span class='notice'>Вы удалили внешнее покрытие.</span>")
"Вы сняли обшивку"

2022-02-22 10:12 UTC, DarthSidiousPalpatine commented on code/game/turfs/simulated/walls.dm
> +				visible_message("<span class='warning'>[user] завершает разборку стены!</span>", blind_message = "<span class='warning'>Вы слышите, что металл был разрезан на части.</span>", viewing_distance = 5
"Вы слышите как металл разрезали на части"
"Вы слышите как металл разрезают на части"
"Вы слышите как металл разрезается на части"

2022-02-22 10:12 UTC, DarthSidiousPalpatine commented on code/game/turfs/simulated/walls.dm
> +		to_chat(user, "<span class='notice'>Вы начинаете сверлить сквозь стену.</span>")
"Вы бурите сквозь стену"

2022-02-22 10:12 UTC, DarthSidiousPalpatine commented on code/game/turfs/simulated/walls.dm
> +				to_chat(user, "<span class='notice'>Вы просверлили последнюю укрепленную пластину.</span>")
"Вы пробурили последний лист обшивки"

2022-02-22 10:12 UTC, DarthSidiousPalpatine commented on code/game/turfs/simulated/walls.dm
> +				visible_message("<span class='warning'>[user] завершает сверлить стену!</span>", blind_message = "<span class='warning'>Вы слышите скрежет металла.</span>", viewing_distance = 5)
"[user] пробурился сквозь стену!"

2022-02-22 10:12 UTC, DarthSidiousPalpatine commented on code/game/turfs/simulated/walls.dm
> +		to_chat(user, "<span class='notice'>Вы вонзаете энергетический меч в стену, начиная разрезать преграду.</span>")
Опять, уверен что будет энергомеч переведён так?

2022-02-22 10:12 UTC, DarthSidiousPalpatine commented on code/game/turfs/simulated/walls.dm
> +				visible_message("<span class='warning'>[user] завершает разборку стены!</span>", blind_message = "<span class='warning'>Вы слышите летящие искры и металл, разрезанный на части.</span>", viewing_d
"[user] прорезает стену насквозь!" "Вы слышите скрежет металла и треск искр"

2022-02-22 21:24 UTC, Zickusable commented on code/game/turfs/simulated/walls.dm
> +	to_chat(user, "<span class='notice'>Вы толкаете стену, но ничего не происходит!</span>")
Ну это совсем не то, юзер сумасшедший? мим?

2022-02-22 21:30 UTC, Zickusable commented on code/game/turfs/simulated/walls.dm
> +			to_chat(user, "<span class='notice'>Вы бьете стену энергетическим мечом; термит вспыхивает!</span>")
Я не вижу будущее. Как его переведут **лет через 10** меня уже касаться не будет. Пока есть только так.

2022-02-22 21:43 UTC, Zickusable commented on code/game/turfs/simulated/walls.dm
> +				to_chat(user, "<span class='notice'>Вы сжигаете грибок инструментом.</span>")
"Пламя сжигает грибок"
Еще у нас велдингтул только одного вида (всякие индастриалы и эксперименталы не в счет), так что можно вместо инструмента вписать 'горелка' или 'сварочный аппарат'

2022-03-02 10:21 UTC, DarthSidiousPalpatine commented
> Очень не круто что багфиксы идут в перемешку с переводами которые мержатся годами.

Я бы даже закрыл ПР из-за этого. Если уж тут багфикс. По правилам нельзя в пр с переводом что-то ещё пихать.

2022-03-05 00:21 UTC, LudwigVonChesterfield commented
Как доделаешь - попроси открыть ПР, откроем.

2022-03-10 18:33 UTC, Zickusable commented on code/game/turfs/simulated/walls.dm
> +			to_chat(user, "<span class='notice'>Нужно больше топлива.</span>")
Отсылка к "Нужно больше золота!"

2022-03-10 18:46 UTC, Zickusable commented on code/game/turfs/simulated/walls_reinforced.dm
> +							to_chat(user, "<span class='notice'>Вы убрали поддерживающий каркас.</span>")
Нет, если нет гравитации или в равновесном состоянии

2022-03-10 19:14 UTC, Zickusable commented
Откройте @LudwigVonChesterfield

2022-04-09 02:33 UTC, volas commented on code/game/objects/structures/girders.dm
> +		visible_message("<span class='warning'><B>[user]</B> бьет каркас!</span>")
вообще мы договорились подобное не переводить, и хардкодить какие-то описания плохо - этот "girder" потом может стать чем угодно (как, например, стулья, которые являются на самом деле кроватями, которые, в свою очередь, на самом деле столы).
Касается и другого пр-а, ну да ладно.

2022-04-09 02:34 UTC, volas commented on code/game/objects/structures/girders.dm
> +				to_chat(user, "<span class='notice'>Вы сделали потайную дверь! Толкните чтобы открыть или закрыть проход.</span>")
```suggestion
				to_chat(user, "<span class='notice'>Вы сделали потайную дверь! Толкните, чтобы открыть или закрыть проход.</span>")
```

2022-04-12 04:03 UTC, volas commented
Мерж по тем же причинам, что и #6930.

2022-04-12 04:04 UTC, merged

2022-04-20 18:39 UTC, LudwigVonChesterfield commented on code/game/turfs/simulated/walls.dm
> +				dismantle_wall(TRUE)
а шо етот пр ревьювали шоли