Give them a fucking choice
TauCetiStation/TauCetiClassic pull request #7959
Opened 2021-09-11 23:38 UTC by atik1n

## Описание изменений
![image](https://user-images.githubusercontent.com/14612180/132965986-8957ca6d-0165-487f-b210-49a6f452a02b.png)
Без проблем
https://forum.taucetistation.org/t/zamena-imeyushhihsya-parallaksov-na-novyj-ot-udava/28060
https://forum.taucetistation.org/t/zamena-imeyushhihsya-parallaksov-na-novyj-ot-udava/28060/16
Люди хотят выбор, я им даю выбор, все счастливы

## Почему и что этот ПР улучшит
У нас был выбор и останется в плане космоса. А я буду это мейнтейнить

2021-09-11 23:38 UTC, TauKitty commented
###### Changelog status: :radio_button: No changelog

2021-09-22 13:57 UTC, atik1n commented
Брысь

2021-09-22 19:51 UTC, 4310V343k requested changes

2021-09-22 19:51 UTC, 4310V343k commented on code/modules/client/character menu/global.dm
> +					parallax_theme = PARALLAX_THEME_CLASSIC
А таукети где

2021-09-22 19:51 UTC, 4310V343k commented on code/modules/client/preferences_savefile.dm
> +	parallax_theme = sanitize_text(parallax_theme, initial(parallax_theme))
таб

2021-09-22 19:51 UTC, 4310V343k commented on code/modules/client/preferences_savefile.dm
> +	S["parallax_theme"] >> parallax_theme
таб

2021-09-22 19:51 UTC, 4310V343k commented on code/modules/client/preferences_savefile.dm
> +	S["parallax_theme"] << parallax_theme
таб

2021-10-14 11:13 UTC, atik1n commented
а

2021-11-04 17:59 UTC, closed without merging