Добавил колонку для жукбокса
TauCetiStation/TauCetiClassic pull request #8050
Opened 2021-09-30 20:35 UTC by DarthSidiousPalpatine

## Описание изменений
Добавил колонку для жукбокса и возможность транслировать и принимать медиасигнал жукбоксом и колонками.
Колонка:
![image](https://user-images.githubusercontent.com/21008918/135526113-551e9e16-0f81-4ec5-ad16-cac4c3ee357c.png)

Интерфейс колонки:
![image](https://user-images.githubusercontent.com/21008918/135526175-1f3aaed9-a4f5-4d6a-b05c-a6cbd161c246.png)

Небольшое обновление интерфейса жукбокса:
![image](https://user-images.githubusercontent.com/21008918/135526248-4b649d65-5923-4be5-b532-aa7a9c5575cd.png)

Видео работы:
[https://www.youtube.com/watch?v=COMNK6OwfRI](Колонка)

Видео анимации колонки:
[https://www.youtube.com/watch?v=VbNcjAvlb6c&list=PLpljpZgDsMFLCpbHX9guLXHkAa-RGauI_&index=18](Анимация колонки)

## Почему и что этот ПР улучшит
Позволит без бага привязать к жукбоксу больше отсеков для каких-то, возможно нужных, целей. Дискотеку там устроить, не знаю.

## Авторство
AndreyGysev и все все все

## Чеинжлог
:cl:
 - rscadd: Добавлена колонка к жукбоксу

2021-09-30 20:35 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2021-09-30 21:16 UTC, Zmey25 commented
если бумбокс нельзя носить на плече, то как же ролеплеить америку 90-ых?

2021-09-30 21:17 UTC, DarthSidiousPalpatine commented
А, да, и вопрос - надо ли их раундстартом где-то на станции спавнить. В тюрьме, библиотеке, баре, каморке бармена или еще где? (Может, на Синдикатовском спутнике прослушки?)

2021-09-30 21:17 UTC, DarthSidiousPalpatine commented
> если бумбокс нельзя носить на плече, то как же ролеплеить америку 90-ых?

и скейтбордов тоже нет. Йо-йо тоже нет, вообще всё мимо.

2021-09-30 21:27 UTC, TauKitty commented
This pull request has been mentioned on **Tau Ceti Station Forum**. There might be relevant details there:

https://forum.taucetistation.org/t/fiks-zhukboksa-teper-on-otklyuchaetsya-ot-oblasti-pri-otkruchivanii/28468/14

2021-10-01 11:16 UTC, KIBORG04 commented on code/modules/media/jukebox.dm
> +		if(href_list["set_freq"]!="-1")
```suggestion
		var/newfreq = media_frequency
		if(href_list["set_freq"] != "-1")
```

2021-10-01 11:18 UTC, KIBORG04 commented on code/modules/media/machinery.dm
> +		return
зачем и где это так?

2021-10-01 11:18 UTC, KIBORG04 commented on code/modules/media/jukebox.dm
> +				playing = 0
```suggestion
				playing = FALSE
```

2021-10-01 11:19 UTC, KIBORG04 commented on code/modules/media/jukebox.dm
> +	media_receivers[freq]=receivers
```suggestion
	media_receivers[freq] = receivers
```

2021-10-01 11:19 UTC, KIBORG04 commented on code/modules/media/jukebox.dm
> +	media_receivers[freq]=receivers
```suggestion
	media_receivers[freq] = receivers
```

2021-10-01 11:19 UTC, KIBORG04 commented on code/modules/media/jukebox.dm
> +	if("power" in href_list)
не хватает вызовов родителя и там еще чего-то

2021-10-01 11:20 UTC, KIBORG04 commented on code/modules/media/jukebox.dm
> +	dat+={"</TT>"}
```suggestion
	dat += {"</TT>"}
```

2021-10-01 11:20 UTC, KIBORG04 commented on code/modules/media/jukebox.dm
> +	var/on=FALSE
```suggestion
	var/on = FALSE
```

2021-10-01 11:20 UTC, KIBORG04 commented on code/modules/media/jukebox.dm
> +	media_transmitters[freq]=transmitters
```suggestion
	media_transmitters[freq]=transmitters
```
дальше сам ставь пробелы

2021-10-01 11:21 UTC, KIBORG04 commented on code/modules/media/jukebox.dm
> +/obj/machinery/media/jukebox/proc/connect_frequency()
Ты большую часть прока connect_frequency и disconnect_frequency можешь тупо в один объеденить, сократив копипасту

2021-10-01 11:23 UTC, KIBORG04 commented on code/modules/media/jukebox.dm
> +/obj/machinery/media/jukebox/setLoc(turf/T, teleported=0)
Можно меньше копипасты у родителя?
![image](https://user-images.githubusercontent.com/26389417/135611978-a99985ef-a81c-4226-b95c-7aa609156327.png)

2021-10-01 14:28 UTC, DarthSidiousPalpatine commented
Подытожу, т.к. гитхаб не даёт мне отвечать на все ревью?:
1)Надо ли мне заменять все playing = циферка на playing = булл в этом и родительском файле?
2)Надо ли заменять connect/disconnect на один прок, который будет иметь параметр "Connect" в виде Булл?
3)Надо ли убрать if(!loc) return, который исправлял карго-ошибку, и если да, то чем его заменить?

2021-10-01 22:27 UTC, Misakiwa commented
3000 это же дорого

2021-10-02 03:46 UTC, DarthSidiousPalpatine commented
> 3000 это же дорого для одной колоночки

Думаю, стоит подождать балансдеп для их мнения по поводу цены.

2021-10-02 11:47 UTC, Misakiwa commented
> > 3000 это же дорого для одной колоночки
> 
> Думаю, стоит подождать балансдеп для их мнения по поводу цены.

Думаю, несуществующий балансдеп балансит робаст между рольками и персоналом, а не цену колоночек, но ладно. . .

2021-10-02 11:52 UTC, DarthSidiousPalpatine commented
> > > 3000 это же дорого для одной колоночки
> > 
> > 
> > Думаю, стоит подождать балансдеп для их мнения по поводу цены.
> 
> Думаю, несуществующий балансдеп балансит робаст между рольками и персоналом, а не цену колоночек, но ладно. . .

вообще мимо. Они балансят всё что захотят. Надеюсь и колонки захотят забалансить. Ланчбоксы-то уже набалансили.

2021-10-02 11:52 UTC, KIBORG04 commented
Всё так. Балансеры не нужны, нужен 1 волас

2021-10-02 16:13 UTC, LiLJard requested changes
Спрайт очень плох, надо делать другой

2021-10-02 16:24 UTC, LiLJard requested changes
Учимся работать с гитхаб

2021-11-17 21:06 UTC, closed without merging

2022-07-29 16:22 UTC, Tap0r commented
Такую имбу чисто из-за спрайтов не замержили?