Runlevels
TauCetiStation/TauCetiClassic pull request #8117
Opened 2021-10-22 22:02 UTC by kalazus

## Описание изменений
Портирование runlevels с tg (и вообще всё что связано с мастером до сего дня), в каждом коммите номер коммита, на котором он основан (к сожалению, что-то не то сделал, так что не на всех он есть, но названия совпадают, можно по ним найти).

Изменения:
- убран SS_FIRE_IN_LOBBY (с runlevels он не нужнен)
- убран SS_NO_TICK_CHECK (на тг убрали после экспериментов)
- добавлен атрибут runlevels подсистемам - возможность точно задавать на каком этапе игры должна работать подсистема. Задаётся битфлагами RUNLEVEL_LOBBY, RUNLEVEL_SETUP, RUNLEVEL_GAME, RUNLEVEL_POSTGAME.
- лучше восстановление умерших подсистем.
- куча оптимизаций мастера.
- чистка кода.

Из нужного не портировал только Stack overflow detection (https://github.com/tgstation/tgstation/pull/56008) и https://github.com/tgstation/tgstation/pull/60846.

## Почему и что этот ПР улучшит
Более современный мастер, больше совместимость с tg.

## Авторство

## Чеинжлог

2021-10-29 21:18 UTC, KIBORG04 commented on code/controllers/master.dm
>  	var/list/_subsystems = list()
Какой-то прикол тут. Наверное, нужно просто это заменить на `subsystems = list()`.

2021-10-29 21:19 UTC, KIBORG04 commented
Страшно это не только ревьювить, но и мержить.

2021-11-01 11:42 UTC, KIBORG04 commented on code/controllers/master.dm
> +	subsystems = new
че, верни лист(), это одно и то же

2021-11-01 11:46 UTC, kalazus commented on code/controllers/master.dm
> +	subsystems = new
Уверен в этом? Почему-то кинуло ошибку в юнит тестах при list(), но при других вариантах никаких проблем нету.

2021-11-01 11:48 UTC, KIBORG04 commented on code/controllers/master.dm
> +	subsystems = new
1. У тебя ошибка вылезла только на боксе, но не на гамме
2. ![image](https://user-images.githubusercontent.com/26389417/139666877-c5f87816-deed-4da7-818e-654ff2649c63.png)
3. Это ошибка не связана с этим листом, а с каким-то таймером

2021-11-01 12:02 UTC, kalazus commented on code/controllers/master.dm
> +	subsystems = new
Совпадение? Не думаю.

2021-11-01 12:05 UTC, KIBORG04 commented on code/controllers/master.dm
> +	subsystems = new
![image](https://user-images.githubusercontent.com/26389417/139668794-62b05c3d-1e35-42e6-b3cf-6530edf15dcb.png)
https://secure.byond.com/docs/ref/index.html#/list

У тебя повод задуматься, почему и как пофиксить

2021-11-01 12:26 UTC, kalazus commented on code/controllers/master.dm
> +	subsystems = new
Ты перезапустил тесты и начало работать?

2021-11-01 12:27 UTC, KIBORG04 commented on code/controllers/master.dm
> +	subsystems = new
да, но проблема какая-то есть, фикси

2021-11-01 13:07 UTC, kalazus commented on code/controllers/master.dm
> +	subsystems = new
Ошибка вызывается в подсистеме, а она по сути своей самостоятельна. Т.е. внешне её случайно почти не сломать. Проблема скорее всего была и до меня, просто либо коллектор мусора не успевал раньше сработать, либо таймер не успевал дважды активироваться. Могу ~~скопировать~~ спортировать таймер с ТГ, тогда скорее всего проблем не будет.

2021-11-05 11:38 UTC, kalazus commented
Вроде починил таймер. @KIBORG04, прогони тесты пару раз чтобы перепроверить.

2021-11-05 12:57 UTC, KIBORG04 commented
Не починил

2021-11-06 23:13 UTC, KIBORG04 commented
Можно попробовать воткнуть тм на 2й и посмотреть как там люди поживут, а там и на 1й потом. Но я это скорее сделаю днем, когда я буду свободен и если что быть готовым этот самый ТМ отменить.

2021-11-08 12:13 UTC, kalazus commented
Киборг, чекни. Кажется это чинит рантайм без вмешательства в таймер. Забыл починить эту штуку на тг когда копировал.

2021-11-09 19:02 UTC, kalazus commented
Эта штука вроде работает и можно тестить, но тут значимая часть punisher-а удалена (то что заставляет подсистемы меньше времени обрабатывать свои запросы так как раньше они потратили больше времени чем должны были). Вроде понял где проблема, но чтобы починить придётся переписать часть таймера.

2021-11-09 20:44 UTC, KIBORG04 commented
Меня пугает название коммита

2021-11-09 21:50 UTC, kalazus commented
> Меня пугает название коммита

Я собираюсь его ревёртнуть когда перепишу тикер. А то сейчас он может при правильном использовании крашнуться и утечку памяти произвести.

2021-11-09 21:51 UTC, KIBORG04 commented
> > Меня пугает название коммита
> 
> Я собираюсь его ревёртнуть когда перепишу тикер. А то сейчас он может при правильном использовании крашнуться и утечку памяти произвести.

почему..

2021-11-09 21:58 UTC, kalazus commented
> почему..

Почему тикер такое может сделать или почему я делаю коммит который собираюсь ревёртнуть? Второе чтобы проверить действительно ли из-за этого раньше работало. Первое, при удалении таймера в неудачный момент, он может оторвать часть кольцевого списка, либо занулить каллбек вызвав краш.

2021-11-12 10:39 UTC, KIBORG04 commented
Мне опять кинуть тм на сендбокс?

2021-11-12 23:26 UTC, KIBORG04 commented
Сенд вроде не здох за весь день. Мб можно и на второй пустить будет завтра.

2021-11-13 04:44 UTC, kalazus commented
> Сенд вроде не здох за весь день. Мб можно и на второй пустить будет завтра.

Думаю не нужно, лучше подождать пока я перепишу часть таймера.

2021-11-13 19:09 UTC, kalazus commented
Смешно... Как ЭТО вообще могло зарантаймить?

2021-11-15 09:00 UTC, kalazus commented
Может опять STM на сэндбоксе?

2021-11-17 22:46 UTC, KIBORG04 commented
> Может опять STM на сэндбоксе?

Волас сказал, что пока на сендбоксе министанция лучше не мешать тмы

2021-11-18 10:10 UTC, volas commented
сейчас уже можно

2021-11-19 23:31 UTC, KIBORG04 commented
Волас ничего не писал, в логах вроде тоже все пусто. Значит, можно кидать на второй?

2021-11-20 16:22 UTC, volas commented
тм на первом

2021-11-20 17:02 UTC, KIBORG04 requested changes
Куклы спавнятся не в коробке, как раньше, а сразу на своих точках голые. Одеваются когда-то потом. И вот клиент попадает в голого персонажа в окружение таких же голышей и видит, как все стоят и через время одеваются.

2021-11-20 21:47 UTC, kalazus commented
А это смешно, вообще в коробку не попадают? Даже на пол секунды?

2021-11-20 21:48 UTC, KIBORG04 commented
> А это смешно, вообще в коробку не попадают? Даже на пол секунды?

Сразу все на позициях голые и с игроком. Голые ассистухи вперед! (хотя двигаться нельзя)

2021-11-22 11:22 UTC, KIBORG04 commented
Я играл раунд и все спавнились в коробке, а на позициях уже одетые.

2021-11-22 12:58 UTC, kalazus commented
Не знаю как нормально это сделать. Если правильно понял, то создаётся сразу куча оверлеев (одежды) из-за чего подсистема оверлеев первое время не справляется, и её дополнительно замедляет punisher.

2021-11-22 13:00 UTC, KIBORG04 commented
Возможно, нужно будет тронуть SSticker и его метод расстановки и вселения людей в куклу. Например, вселять гостов только когда все закончилось, ну или в виде костыля гостам кидать черный экран, а убирать его когда все загрузится

2021-11-22 21:35 UTC, KIBORG04 commented
ты шо сделал

2021-11-23 12:17 UTC, Sakuya-Izayoi commented
то что при драгндропе курсор смещается немного это случайно не из-за этого?

2021-11-23 12:47 UTC, kalazus commented
> то что при драгндропе курсор смещается немного это случайно не из-за этого?

Сегодня ПР уже вроде не в тм на первом, а так, уже починил то что обновляло херово курсор, могло вчера и быть.

2021-11-25 16:50 UTC, KIBORG04 commented
Щас кину в тм, готовьтесь

2021-11-25 16:56 UTC, kalazus commented
Так я ещё голеньких не починил.

2021-11-25 16:56 UTC, KIBORG04 commented
Фича

2021-11-25 16:57 UTC, kalazus commented
*процедурно загружаемые персонажи*

2021-11-26 12:23 UTC, kalazus commented
Вроде пофиксил. Сейчас главный экран будет убираться прямо перед началом игры (больше не будет людей в коробке).

2021-11-26 12:41 UTC, KIBORG04 commented on code/controllers/subsystem/ticker.dm
> +	CHECK_TICK
Имеет смысл это ставить просто тут?

2021-11-26 12:43 UTC, KIBORG04 commented on code/controllers/subsystem/ticker.dm
> +		if(player?.spawning)
Какова вероятность, что он гост будет нуллом?

2021-11-26 12:55 UTC, KIBORG04 commented
А ты учел гостов, которые спавнятся во время раунда?

2021-11-26 13:13 UTC, kalazus commented on code/controllers/subsystem/ticker.dm
> +	CHECK_TICK
Да, я думал засунуть это в фор джобок, но тогда начнётся раунд через секунд 10 после сообщений о капитане и подобном. Тут оно остановится только раз, пока всякие оверлеи перерабатывают.

2021-11-26 13:15 UTC, kalazus commented on code/controllers/subsystem/ticker.dm
> +		if(player?.spawning)
Кажется 0, фиксану.

2021-11-26 22:32 UTC, KIBORG04 commented
conflicts

2021-11-26 22:39 UTC, KIBORG04 commented on code/controllers/subsystem/ticker.dm
> +	CHECK_TICK
> через секунд 10 после сообщений о капитане и подобном

Сообщение о капитане вылазиет в `equip_characters()`. Наверное, основные лаги при старте раунда происходят в `data_core.manifest()` из-за `getFlatIcon()`. Этот чек_тик как-то прямо фу выглядел. 

А знаешь че, удаляй гостов в `spawn(0)`, чтобы скрин убрался уже после выдачи триторки. У меня вроде в раунде была ситуация, что профа далась, экран снялся, я вижу над собой значек-антага, но не вижу сообщения в чат, что я антаг.

Типо, поидее, будет лучше, но экранчик будет дольше висеть

2021-11-26 23:02 UTC, kalazus commented on code/controllers/subsystem/ticker.dm
> +	CHECK_TICK
Так... А экран тут при чём? Конечно, << пользователю как-то могут мешать друг другу (но очень маловероятно). 
Этот чек ждёт по факту до момента стабилизации игры. Как по мне, очень даже хорошо его сделать после него т.к. не будет начальных лагов, как было.
Так мне что, теперь чинить и съедаемые сообщения? Вообще, они могут быть и если чат работает слишком хорошо.

2021-11-26 23:05 UTC, KIBORG04 commented on code/controllers/subsystem/ticker.dm
> +	CHECK_TICK
Это не приказ, это не требование, делай как надо.

2021-11-27 14:20 UTC, Sakuya-Izayoi commented
> Голосование прервано из-за начала игры.

Я правильно понимаю что гейммод воут может не продлевать время подготовки перед раундом из-за этого пуллреквеста?

2021-11-27 18:57 UTC, kalazus commented
> > Голосование прервано из-за начала игры.
> 
> Я правильно понимаю что гейммод воут может не продлевать время подготовки перед раундом из-за этого пуллреквеста?

Нет, я ни в голосование, ни в код старта не лез, кроме позднего удаления new_player (но это повлиять не могло)

2021-11-27 19:21 UTC, Sakuya-Izayoi commented
> > > Голосование прервано из-за начала игры.
> > 
> > 
> > Я правильно понимаю что гейммод воут может не продлевать время подготовки перед раундом из-за этого пуллреквеста?
> 
> Нет, я ни в голосование, ни в код старта не лез, кроме позднего удаления new_player (но это повлиять не могло). А хотя, возможно, если раньше это работало на лагах. Не вижу где это могло быть сломано, если админ не изменял время до раунда.

Я, кажется понял. Отсчет воута тикает медленнее, чем отсчет до старта раунда. В один момент старт раунда перегоняет воут.

2021-11-27 20:25 UTC, KIBORG04 commented
Каждую секунду убирается по 2 секунды

2021-11-27 21:24 UTC, kalazus commented
> Каждую секунду убирается по 2 секунды

Убирается 2 секунды, а вызывается каждые 1.5... Посмотрю что можно сделать.

2021-11-29 17:10 UTC, KIBORG04 approved these changes

2021-11-30 19:33 UTC, KIBORG04 commented
Го мерж?

2021-11-30 19:37 UTC, merged

2021-11-30 19:59 UTC, kalazus commented
Наконец-то я могу дальше прить, и не боятся создавать конфликты везде где только можно...