Министанция!
TauCetiStation/TauCetiClassic pull request #8132
Opened 2021-10-28 16:41 UTC by DarthSidiousPalpatine

## Описание изменений
Министанция для малых раундов с малым количеством игроков.
Картинки:
![22](https://user-images.githubusercontent.com/21008918/142176600-bbf7453c-83da-4386-842a-d55ab52863ad.png)
![1](https://user-images.githubusercontent.com/21008918/139279532-1ac0fe06-348e-4436-83f4-305ca35cdd86.png)

## Почему и что этот ПР улучшит
Позволит полнее играть малому количеству игроков, чтобы они не разбегались по гигантскому боксу.

## Авторство
Darth_Sidious и все-все-все, кто помогал в дискорде.

## Чеинжлог
:cl:
 - map: Добавлена министанция

2021-10-31 13:29 UTC, notkripton commented
Как вариант можно вместо шаттла на астероид сделать какую-нибудь гору с ресурсами на левом углу карты

2021-11-01 12:35 UTC, KIBORG04 commented
Не факт что автор вообще закончит свой ПР

2021-11-03 16:20 UTC, TauKitty commented
This pull request has been mentioned on **Tau Ceti Station Forum**. There might be relevant details there:

https://forum.taucetistation.org/t/hochu-novuyu-mapu/29204/1

2021-11-03 17:05 UTC, DarthSidiousPalpatine commented
Закончу. Просто всё сложнее и надо сначала сделать систему тегов для слоёв или как-то так. Статы разных карт.

2021-11-10 14:43 UTC, volas requested changes

2021-11-10 14:43 UTC, volas commented on code/game/turfs/turf.dm
> +	basetype = text2path(SSmapping.level_trait(z, ZTRAIT_BASETURF))
В этом случае может сбиться дефолтный basetype у турфа. На астеройде например.
Лучше было бы еще при загрузке карты (еще и быстрее) где-то тут это делать:
https://github.com/TauCetiStation/TauCetiClassic/blob/6dda2e31f304fea971e4909f177d9a6869cbc5dc/code/modules/maps/reader_optimized.dm#L314
нужно еще поискать, как оттуда добраться до значения z-уровня. И логика будет что-то вроде 
```
если initial(turfpath.basetype) == /turf/space
то crds.basetype = text2path(SSmapping.level_trait(z, ZTRAIT_BASETURF))
иначе crds.basetype = initial(turfpath.basetype)
```

2021-11-10 14:45 UTC, volas commented on code/game/turfs/turf.dm
> +	basetype = text2path(SSmapping.level_trait(z, ZTRAIT_BASETURF))
а, ну z-уровень можно взять из crds.z, очевидно

2021-11-10 14:49 UTC, volas commented on code/game/turfs/turf.dm
> +	basetype = text2path(SSmapping.level_trait(z, ZTRAIT_BASETURF))
ну и все 100 очков если будешь кэшировать text2path(SSmapping.level_trait(z, ZTRAIT_BASETURF)) где-нибудь в dmm_suite, что бы не обращаться к нему 255^2 раз

2021-11-10 18:58 UTC, DarthSidiousPalpatine commented on code/game/turfs/turf.dm
> +	basetype = text2path(SSmapping.level_trait(z, ZTRAIT_BASETURF))
Ну проверку на наличие турфа уже сделал, а вот про кеширование не очень понимаю как это сделать. Лучше не трогать)

2021-11-15 15:51 UTC, Firein91 commented
НУ и конечно бриг самый здоровый - а без этого никак?

2021-11-15 18:20 UTC, DarthSidiousPalpatine commented
Ну, как-то так.

2021-11-15 18:20 UTC, DarthSidiousPalpatine commented on code/game/turfs/turf.dm
> +	basetype = text2path(SSmapping.level_trait(z, ZTRAIT_BASETURF))
сделал, но не на 100 очков.

2021-11-16 05:29 UTC, TauKitty commented
This pull request has been mentioned on **Tau Ceti Station Forum**. There might be relevant details there:

https://forum.taucetistation.org/t/udavskie-mysli-o-ministanczii/29217/8

2021-11-17 19:29 UTC, kalazus commented
Проводка не подведена к APC: хранилище плат, коморка атмосферников, инженерная. А вообще просто подожди пока всё разрядится/запусти соответствующий ивент, запитай смесы и посмотри где нету света.

2021-11-19 09:03 UTC, volas requested changes

2021-12-09 19:00 UTC, kiVts commented
Oh no! A wild stalebot appears!

2021-12-27 17:16 UTC, DarthSidiousPalpatine commented
Тебя вылечат

2022-01-15 14:53 UTC, DarthSidiousPalpatine commented
Пожалуйста, нет, мне нужно ещё немного времени!

2022-01-15 15:02 UTC, Shootnik01 commented
Бот би лайк: https://www.youtube.com/watch?v=sNjWpZmxDgg

2022-02-05 17:05 UTC, closed without merging

2022-03-17 13:53 UTC, kalazus commented
@DarthSidiousPalpatine снег замержен так что можно оживлять, если автор докодит.

2022-03-17 13:54 UTC, DarthSidiousPalpatine commented
Ура снег! Большущее спасибо.