Добавление ланчбоксов в игру
TauCetiStation/TauCetiClassic pull request #8144
Opened 2021-11-01 10:05 UTC by Rolt146

## Описание изменений
В игре появилось 10 коробок ланчбоксов!
<details> 
  <summary>Тыкай сюда, что бы их увидеть</summary>

  ![Скриншот 01-11-2021 123808](https://user-images.githubusercontent.com/62613651/139654484-2fdf1f2b-f94d-4183-ac48-3b47853b8637.jpg)
</details>

 9 из них находятся в автомате повара (причем одна скрыта),
<details> 
  <summary>Обзор содержимого автомата с включенным режимом контрабанды</summary>

![Скриншот 01-11-2021 123619](https://user-images.githubusercontent.com/62613651/139654774-c9bd0866-9a7e-4b22-b07d-9fe322051362.jpg)
</details>

Десятая же находится у трейтора в аплинке (всего за 3 кристалла!).
<details> 
  <summary>Еще один тык</summary>

![Скриншот 01-11-2021 123445](https://user-images.githubusercontent.com/62613651/139654949-70855175-c0ec-45c6-81d2-3aee898f1198.jpg)

![Скриншот 01-11-2021 123507](https://user-images.githubusercontent.com/62613651/139655051-42fb8786-47bd-40eb-b7ea-0b380960b955.jpg)

</details>

 Все ланчбоксы, за исключением трейторского, пусты. Так-же внес изменения в автомат повара - теперь ложки это не контрабанда, а стаканов стало в 2 раза больше
<details> 
  <summary>Крайний тык</summary>

![Скриншот 01-11-2021 123337](https://user-images.githubusercontent.com/62613651/139655214-22aed30d-e4e2-42b6-abc9-3c7c681543aa.jpg)

</details>

## Почему и что этот ПР улучшит
Повару теперь не придется опустошать коробки из под одноразовых стаканчиков и помады ради имитации ланчбоксов. Теперь они есть у него в автомате.
Стаканов стало больше в автомате повара
Ложки теперь не контрабанда
Синдикатовский ланчбокс с едой от компании Waffle Co.
## Авторство
Rolt146 - идея, код
DedYarick - спрайты
## Чеинжлог
:cl: 
 - add: Появились ланчбоксы, 10 штук.
 - image: Добавлены спрайты ланчбоксов.
 - balance: Ложки теперь не контрабанда, а стаканов в автомате повара стало больше.
 - add: В аплинк синдиката добавлен заправленый ланчбокс.

2021-11-01 10:05 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2021-11-01 10:13 UTC, UDaV73rus approved these changes
где хэппи мил

2021-11-01 10:23 UTC, AndroBetel commented
Мне кажется, ланчбокс в котором из полезного только мозгобургер - немного не оправдывает свою цену в 3 ТК.
Ещё, чтобы не захламлять вендор поварской, можно сделать, чтобы спавнился рандомный ланчбокс при выборе, как пончики в секвендоре.

2021-11-01 10:25 UTC, Sakuya-Izayoi commented
атомарность

2021-11-01 10:29 UTC, Rolt146 commented
> Мне кажется, ланчбокс в котором из полезного только мозгобургер - немного не оправдывает свою цену в 3 ТК. Ещё, чтобы не захламлять вендор поварской, можно сделать, чтобы спавнился рандомный ланчбокс при выборе, как пончики в секвендоре.

Допустим, повар хочет брутальный ланчбокс для шахтера, а выпадает с сердечками. Тогда тоже будет массовое захламление ланчбоксами тайла с автоматами, пока не выпадет нужный. Да и ланчбоксы имеют свою ценность. Золотой вот один на автомат, зато грейтайдовских целая куча

2021-11-01 10:30 UTC, Rolt146 commented
> атомарность
> 
> > * image: Добавлены спрайты ланчбоксов.
> 
> это лишний чейнджлог

Изменил

2021-11-01 10:44 UTC, AndroBetel commented
> Допустим, повар хочет брутальный ланчбокс для шахтера, а выпадает с сердечками.

Угарно же.

2021-11-01 10:49 UTC, Sakuya-Izayoi commented on code/game/objects/items/weapons/storage/boxes.dm
> +
1. Сделай класс ланчбокса, а разновидности подклассами.
2. Наполнение из atom_init перенеси в переменную starts_with

2021-11-01 10:50 UTC, Sakuya-Izayoi commented
было бы круто, если спрайт можно было менять с помощью юниверсал пейнтера, спрей кена или хотя бы мелка.

2021-11-01 11:38 UTC, KIBORG04 commented on code/datums/uplinks_items.dm
> +	cost = 3
```suggestion
	cost = 1
```
Зачем за еду просить так много? В тех же сижках трик, тут же только алкиниз из мозгобургера и всё.

2021-11-01 11:40 UTC, KIBORG04 commented
> add: Появились ланчбоксы, 10 штук.
balance: Ложки теперь не контрабанда, а стаканов в автомате повара стало больше.
add: В аплинк синдиката добавлен заправленый ланчбокс.

Почему ты написал, что ланчбоксы появились, но не написал где? Тебе хватит строчки, что добавлены пустые ланчбоксы к повару, и один полный в аплинк

2021-11-01 11:54 UTC, Rolt146 commented on code/datums/uplinks_items.dm
> +	cost = 3
Потому что это полноценный обед на всю смену, да еще и с бутылочкой водки, который и обезбол, а анастезия и оружие

2021-11-01 12:34 UTC, KIBORG04 commented on code/datums/uplinks_items.dm
> +	cost = 3
на 3 я не согласен в любом случае

2021-11-01 12:37 UTC, Sakuya-Izayoi commented on code/datums/uplinks_items.dm
> +	cost = 3
да ты и не балдеп...

2021-11-01 12:39 UTC, KIBORG04 commented on code/datums/uplinks_items.dm
> +	cost = 3
У балдепа меньше прав, чем у спрайтеров, их аппрув наравне с мапперским. Так что, я - монополия.

2021-11-02 17:46 UTC, LudwigVonChesterfield commented
> было бы круто, если спрайт можно было менять с помощью юниверсал пейнтера, спрей кена или хотя бы мелка

Если честно у нас много таких мест в билде, а так же много способов красить(как ты сам сказал - спрей кен, мелок, пейнтер, добавлю ещё пшики краски как у барбера), и без какого-то обобщённого механа возможно не стоило бы это делать отдельно для каждого предмета

2021-11-04 20:43 UTC, 4310V343k requested changes

2021-11-04 20:43 UTC, 4310V343k commented on code/datums/uplinks_items.dm
> +	name = "Syndicate lunhcboxes"
```suggestion
	name = "Syndicate lunchboxes"
```

2021-11-04 20:43 UTC, 4310V343k commented on code/datums/uplinks_items.dm
> +	desc = "Delicious food for a tired agent. With love, the Waffle Co."
```suggestion
	desc = "Delicious food for a tired agent. With love from Waffle Co."
```

2021-11-04 20:43 UTC, 4310V343k commented on code/game/objects/items/weapons/storage/boxes.dm
> +	desc = "Stereotype NT lunchbox."
```suggestion
	desc = "Stereotypical NT lunchbox."
```

2021-11-04 20:43 UTC, 4310V343k commented on code/game/objects/items/weapons/storage/boxes.dm
> +	desc = "Stereotype greytide lunchbox."
```suggestion
	desc = "Stereotypical greytide lunchbox."
```

2021-11-04 20:43 UTC, 4310V343k commented on code/game/objects/items/weapons/storage/boxes.dm
> +	name = "chiken lunchbox"
```suggestion
/obj/item/weapon/storage/box/foodchickenbox
	name = "chicken lunchbox"
```

2021-11-04 20:43 UTC, 4310V343k commented on code/game/objects/items/weapons/storage/boxes.dm
> +	name = "Valentine lunchbox"
везде с маленькой буквы (если не аббрев.), а тут с большой
или я чего-то не до конца понимаю?

2021-11-04 20:43 UTC, 4310V343k commented on code/game/objects/items/weapons/storage/boxes.dm
> +	desc = "deluxe."
опять же, везде с большой описание, тут с маленькой

2021-11-04 20:43 UTC, 4310V343k commented on code/game/objects/items/weapons/storage/boxes.dm
> +	desc = "Stereotype mine lunchbox."
```suggestion
	desc = "Stereotypical mine lunchbox."
```

2021-11-04 20:43 UTC, 4310V343k commented on code/game/objects/items/weapons/storage/boxes.dm
> +	desc = "Stereotype NT lunchbox."
Кстати, не знаю насчёт разницы между Stereotypical и Stereotypic
Может, второе будет лучше?

2021-11-04 20:43 UTC, 4310V343k commented on code/game/objects/items/weapons/storage/boxes.dm
> +	desc = "Wow! Cool rainbow lunchbox!."
```suggestion
	desc = "Wow! Cool rainbow lunchbox."
```

2021-11-04 20:43 UTC, 4310V343k commented on code/game/objects/items/weapons/storage/boxes.dm
> +	desc = "Stereotype not syndicate lunchbox."
```suggestion
	desc = "Stereotypical lunchbox. Totally not from syndicate."
```

2021-11-04 20:59 UTC, 4310V343k commented on code/game/objects/items/weapons/storage/boxes.dm
> +
startswith вабщета

2021-11-04 21:49 UTC, Sakuya-Izayoi commented on code/game/objects/items/weapons/storage/boxes.dm
> +	name = "Valentine lunchbox"
имя собственное

2021-11-04 21:50 UTC, Sakuya-Izayoi commented on code/game/objects/items/weapons/storage/boxes.dm
> +	desc = "Stereotype not syndicate lunchbox."
Stereotypical not syndicate lunchbox. В этом шутка такая небольшая. "Типичный не-синдикатовский ланчбокс".

2021-11-04 22:09 UTC, 4310V343k commented on code/game/objects/items/weapons/storage/boxes.dm
> +	desc = "Stereotype not syndicate lunchbox."
блин ладно, но мне как-то интуитивно не нравится, может так и правильно

2021-11-29 00:40 UTC, LudwigVonChesterfield commented on code/game/objects/items/weapons/storage/boxes.dm
> +	desc = "Stereotype not syndicate lunchbox."
а в чом смысл переправлять и придираться к английскому если курс на переводы на русский

2021-12-06 01:32 UTC, closed without merging