аплинк в интерком
TauCetiStation/TauCetiClassic pull request #8148
Opened 2021-11-02 13:21 UTC by AndroBetel

## Описание изменений
Добавляет трейторам возможность выбрать спавн аплинка в случайном интеркоме на станции. Может быть ЛЮБОЙ интерком - в варденской, в огромном коридоре или вообще на спутнике ИИ. Пять ТК (может поменятся) - награда за труды и невозможность его перемещения.
## Почему и что этот ПР улучшит
Геймплей разнообразит.
## Авторство

## Чеинжлог
:cl:
- rscadd: Возможность трейторам выбрать спавн аплинка в случайном интеркоме на станции.

2021-11-02 13:21 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2021-11-02 14:03 UTC, KIBORG04 commented on code/datums/components/gamemodes/syndicate.dm
> +		target_intercom.hidden_uplink.uses += 5
Поменяй эти строчки местами

2021-11-02 14:03 UTC, AndroBetel commented on code/datums/components/gamemodes/syndicate.dm
> +		target_intercom.hidden_uplink.uses += 5
А зачем?

2021-11-02 14:04 UTC, KIBORG04 commented on code/datums/components/gamemodes/syndicate.dm
> +		traitor_mob.mind.store_memory("<B>Radio Freq:</B> [format_frequency(freq)] ([R.name] [R.loc.loc.name]).")
`R.loc.loc.name`

Пиздец, замени это на использование get_area(R)

2021-11-02 14:04 UTC, KIBORG04 commented on code/datums/components/gamemodes/syndicate.dm
> +		traitor_mob.mind.store_memory("<B>Radio Freq:</B> [format_frequency(freq)] ([R.name] [R.loc.loc.name]).")
И еще, имеет смысл писать координаты этого интеркома, вместо area

2021-11-02 14:05 UTC, AndroBetel commented on code/datums/components/gamemodes/syndicate.dm
> +		traitor_mob.mind.store_memory("<B>Radio Freq:</B> [format_frequency(freq)] ([R.name] [R.loc.loc.name]).")
Так не весело, прикинь как смешно будет бегать и искать интерком в центральном коридоре.

2021-11-02 14:07 UTC, KIBORG04 commented on code/datums/components/gamemodes/syndicate.dm
> +		target_intercom.hidden_uplink.uses += 5
total_TC показывает всего ТК. Ты сначала ставишь там 20, а потом еще накидываешь 5. В итоге, в титрах будет всего 20 тк, а потрачено 25

2021-11-02 14:10 UTC, KIBORG04 commented on code/datums/components/gamemodes/syndicate.dm
> +		traitor_mob.mind.store_memory("<B>Radio Freq:</B> [format_frequency(freq)] ([R.name] [R.loc.loc.name]).")
скорее не прикольно. Да и вообще, аплинк в банкомате смотрелся бы круче, чем в аплинке

2021-11-02 14:10 UTC, AndroBetel commented on code/datums/components/gamemodes/syndicate.dm
> +		traitor_mob.mind.store_memory("<B>Radio Freq:</B> [format_frequency(freq)] ([R.name] [R.loc.loc.name]).")
Только банкоматы у нас всегда в коридорах и никакого челленжа с получением предметов не будет.

2021-11-02 17:38 UTC, LudwigVonChesterfield commented
>  в варденской, в огромном коридоре или вообще на спутнике ИИ

Мне вот это не нравится, а так прикольно.

Можно было бы чтобы брались интеркоммы к комнатам к которым есть доступ у тритора? Типо если в комнате с интеркоммом есть хоть один шлюз с доступом ученого-тритора, то этот шлюз бы добавлялся.

2021-11-02 17:39 UTC, LudwigVonChesterfield commented on code/game/objects/items/devices/radio/intercom.dm
> +/obj/item/device/radio/intercom/atom_init()
У нас для такого есть какой-то там дефайн про глобальные списки

2021-11-02 17:42 UTC, AndroBetel commented
> Можно было бы чтобы брались интеркоммы к комнатам к которым есть доступ у тритора? Типо если в комнате с интеркоммом есть хоть один шлюз с доступом ученого-тритора, то этот шлюз бы добавлялся.

Тогда весь челленж с получением доступа к своим вещам просто-напросто пропадаёт. Интерком будет этаким хардмодом для любителей пощекотать нервишки с небольшим бонусом.

2021-11-02 17:45 UTC, KIBORG04 commented on code/game/objects/items/devices/radio/intercom.dm
> +/obj/item/device/radio/intercom/atom_init()
Есть есть, поищи, вроде у автолата юзается много как

2021-11-02 19:54 UTC, Sakuya-Izayoi commented on code/datums/components/gamemodes/syndicate.dm
>  	else if(traitor_mob.client.prefs.uplinklocation == "None")
DRY

я думаю было бы неплохо если плеер мог бы установить арбитрарный приоритет аплинков как на современных билдах

2021-11-04 17:53 UTC, KIBORG04 commented on code/datums/components/gamemodes/syndicate.dm
> +		R = pick(intercom_list)
Тебе нужно сначала собрать лист со всеми станционным интеркомами, иначе придётся тритору лететь на астероид

2021-11-04 17:57 UTC, KIBORG04 commented on code/datums/components/gamemodes/syndicate.dm
> +		R = pick(intercom_list)
А то прям интерком превращает мирно-тритора еще более в мирного

2021-11-04 18:06 UTC, AndroBetel commented on code/datums/components/gamemodes/syndicate.dm
> +		R = pick(intercom_list)
И как правильно будет это сделать?

2021-11-04 18:23 UTC, AndroBetel commented on code/datums/components/gamemodes/syndicate.dm
> +		R = pick(intercom_list)
Я сделал.

2021-11-04 18:37 UTC, KIBORG04 commented on code/datums/components/gamemodes/syndicate.dm
> +		R = pick(intercom_list)
![image](https://user-images.githubusercontent.com/26389417/140399706-9aebe18c-131b-4626-bc09-7c5dbb36e715.png)

Бляздец.

Тебе не нужно было менять код так. Тебе просто нужно было создать новый лист, отобрать туда только станционные интеркомы, на основание ВСЕХ интеркомом, и уже выбирать из новосозданного листа

2021-11-04 19:12 UTC, AndroBetel commented on code/datums/components/gamemodes/syndicate.dm
> +		R = pick(intercom_list)
Ой, я местами перепутал и не тестил.

2021-11-04 19:12 UTC, AndroBetel commented on code/datums/components/gamemodes/syndicate.dm
> +		R = pick(intercom_list)
Чё обзываешься???

2021-11-05 00:50 UTC, Sakuya-Izayoi commented on code/datums/components/gamemodes/syndicate.dm
> +		R = pick(intercom_list)
может быть это полезно будет иметь список всех станционных интеркомов.

2021-11-05 06:59 UTC, AndroBetel commented on code/datums/components/gamemodes/syndicate.dm
> +		R = pick(intercom_list)
Я уже сделал хорошо вроде.

2021-11-05 12:57 UTC, KIBORG04 commented on code/datums/components/gamemodes/syndicate.dm
> +		R = pick(intercom_list)
> может быть это полезно будет иметь список всех станционных интеркомов.

Но без списка всех интеркомов это выглядит не очень полезно. 

> Я уже сделал хорошо вроде.

Я написал как сделать. Вернуть лист для всех интеркомов, тот дефайн, а проверку на то, что интерком на станции, впихнуть при выборе интеркома для тритора.

2021-11-13 20:33 UTC, SpaiR requested changes

2021-11-13 20:33 UTC, SpaiR commented on code/datums/components/gamemodes/syndicate.dm
> +		target_intercom.traitor_frequency = freq
У тебя интерком такое же `/obj/item/device/radio`, поэтому полностью копипастить код ниже (не говоря уже о том, что он и без того не самый красивый) вообще нет никакого смысла. Потому что если ты в этом блоке уберешь тип `intercom` в определении переменной `target_intercom`, работать будет также.

2021-11-13 20:52 UTC, AndroBetel commented
Сделал по ревьювам всё.

2021-11-13 20:53 UTC, KIBORG04 commented on code/datums/components/gamemodes/syndicate.dm
> +		for(var/obj/item/device/radio/intercom/I in intercom_list)
```suggestion
		for(var/obj/item/device/radio/intercom/I as anything in intercom_list)
```
секретный прием оптимизации

2021-11-13 20:54 UTC, AndroBetel commented on code/datums/components/gamemodes/syndicate.dm
> +		for(var/obj/item/device/radio/intercom/I in intercom_list)
А что оно меняет.

2021-11-13 20:56 UTC, KIBORG04 commented on code/datums/components/gamemodes/syndicate.dm
> +		for(var/obj/item/device/radio/intercom/I in intercom_list)
https://github.com/TauCetiStation/TauCetiClassic/blob/master/.github/wiki/CODE_CONVENTION.md#избегайте-ненужных-проверок-типов-в-циклах

2021-11-15 19:58 UTC, SpaiR approved these changes

2021-11-15 20:36 UTC, merged