Научные риги/Science hardsuits
TauCetiStation/TauCetiClassic pull request #8178
Opened 2021-11-08 16:29 UTC by Dushess0

## Описание изменений
Добавлет ученым и РД их особенные риги.  
[Тема с обсуждением](https://forum.taucetistation.org/t/nauchnye-rigi-iksy-hardsuits/28647?u=dushess)

<details> 
  <summary>Спрайты (осторожно много картинок)</summary>

### Риг ученого
  

-  Человек 
![image](https://user-images.githubusercontent.com/44201461/140768517-61e2f52d-1920-4b5d-91ea-62b6292fd0f2.png)
![image](https://user-images.githubusercontent.com/44201461/140768643-549693c6-0d7d-4049-9670-2c751021353c.png)

-    Таяра
![image](https://user-images.githubusercontent.com/44201461/140769206-c983db07-402d-4255-91d0-ccfe39c18053.png)
![image](https://user-images.githubusercontent.com/44201461/140769360-dcd6e51c-6dbe-4f01-85b6-5c37732aef1c.png)

-    Унатх
![image](https://user-images.githubusercontent.com/44201461/140770066-f0dd497b-038f-446d-9ab5-b750f4de0587.png)
![image](https://user-images.githubusercontent.com/44201461/140770187-ee299ef6-5b5e-4697-bf21-4d9b4c79fd88.png)

-    Вокс
![image](https://user-images.githubusercontent.com/44201461/140770632-f5f97a10-773f-4a34-9788-feec60fe6f60.png)
![image](https://user-images.githubusercontent.com/44201461/140770810-59f6a8e6-4f74-4d5e-a9d0-077336c9209e.png)
- Скрелл
![image](https://user-images.githubusercontent.com/44201461/140778476-0bacfcfd-3cb1-49d4-aea9-b43f0e2ff865.png)
![image](https://user-images.githubusercontent.com/44201461/140778566-d5b3bb24-5c2e-47dc-b319-155e5af80181.png)

### Риг РД

-   Человек
![image](https://user-images.githubusercontent.com/44201461/140772555-6c3007a6-6c2d-4842-880f-5f72a92961da.png)
![image](https://user-images.githubusercontent.com/44201461/140772718-d0ad0f6b-ca5b-485c-a042-0c5531b54a67.png)

-    Таяра
![image](https://user-images.githubusercontent.com/44201461/140773260-af286a21-00db-4c12-b91a-d3dfb0ac3c53.png)
![image](https://user-images.githubusercontent.com/44201461/140773373-fd4a55c9-7d42-4f6b-87ee-ef9ef9a87ced.png)

-    Унатх
![image](https://user-images.githubusercontent.com/44201461/140773672-411935a9-2d53-4422-bf9f-e35204445b99.png)
![image](https://user-images.githubusercontent.com/44201461/140773816-75b5b2a4-090e-44e0-88db-bc17c3f0577d.png)

-    Вокс
![image](https://user-images.githubusercontent.com/44201461/140774236-ff682f41-0b72-4f9c-b3ba-c01c787ba968.png)
![image](https://user-images.githubusercontent.com/44201461/140774379-4570b78f-60e6-463f-ae82-25ff9866f38e.png)
- Скрелл
![image](https://user-images.githubusercontent.com/44201461/140777869-0cacf514-056c-4e8d-b3e4-6a10d55a0154.png)
![image](https://user-images.githubusercontent.com/44201461/140777974-3a73e850-fb8a-4a9d-9e99-efb633961e95.png)

</details>

Изменения карты
![image](https://user-images.githubusercontent.com/44201461/140774738-6a4a957a-4c52-4a72-9377-2d587da27a1f.png)
![image](https://user-images.githubusercontent.com/44201461/140775460-44e734f4-5d53-441d-a000-73136f603776.png)

Модули ригов
Добавлено четыре модуля для ригов. 
1. Встроенный научный инструмент - tier 1
 
![image](https://user-images.githubusercontent.com/44201461/140778764-c78bfc98-25c0-4b16-8fdf-180a87cd86bb.png)

2. Встроенный анализатор газов - tier 1
 
![image](https://user-images.githubusercontent.com/44201461/140778789-2753c0a7-2f4a-4f12-8aa5-ac20c057f7ea.png)

3. Стабилизатор телепорта - tier 2 модуль
![image](https://user-images.githubusercontent.com/44201461/140778828-5a55a8cf-103d-495d-904e-3480dab776ed.png)

Если в риге установлена стабилизация то человека не будет мутить, блюспейс сумка не будет мешать телепорту. Модуль работает пассивно и постоянно потребляет немного энергии.
4. Реле радосвязи - tier 3 модуль
![image](https://user-images.githubusercontent.com/44201461/140778858-35d16677-eb82-48f8-b015-8b2b26ae1451.png)

Если встроенно в риг и включенно то позволяет получать и передавать сообщения на другие сектора. Если кто то будет говорить в нашник в том же секторе что и РД то его сообщение будет транслироватся на станцию как если бы на этом секторе стояло нормальное реле. Потребляет ОЧЕНЬ много энергии когда включено.

### Модули рига ученого:

1. Стабилизатор телепорта
2. Модуль охлаждения
3. Научный инструмент
4. Анализатор газов
5. Модуль диагностики
6. Сканнер Альдена-Сараспарова (показывает растояние к артефактам)
![image](https://user-images.githubusercontent.com/44201461/140779321-e7fae032-0dd5-47f4-a2ce-36e96ca310d1.png)
![image](https://user-images.githubusercontent.com/44201461/140779341-f8014180-b991-4b87-b56e-b67190680c4e.png)

### Модули рига РД:
Риг РД с встроенным реле 

![image](https://user-images.githubusercontent.com/44201461/140772197-9a7adc23-cc9e-46e3-b270-d31889047429.png)

1. Реле радиосвязи
2. Стабилизатор телепорта
3. Модуль продвинутой диагностики
4. Модуль починки
5. Модуль охлаждения
6. Научный инструмент
7. Анализатор газов
8. Сканнер Альдена-Сараспарова

![image](https://user-images.githubusercontent.com/44201461/140779175-40701643-5ffe-4add-9572-46f7a32e15a3.png)
![image](https://user-images.githubusercontent.com/44201461/140779212-30b990e6-7f17-4c04-a5ca-9492ec85aae0.png)

Так же шлема риг РД дает возможность видеть статусы киборгов и дронов
![image](https://user-images.githubusercontent.com/44201461/140779966-785d464d-f8f8-4eb8-8cca-f2ec2f4aef8f.png)

## Почему и что этот ПР улучшит

## Авторство
Dushess
BubbleZ

## Чеинжлог
:cl: Dushess
- rscadd: Добавлены научные риги.

2021-11-08 16:29 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2021-11-08 16:31 UTC, Dushess0 commented
Помогите пожалуйста, как убрать label Tools?

2021-11-08 16:42 UTC, TauKitty commented
This pull request has been mentioned on **Tau Ceti Station Forum**. There might be relevant details there:

https://forum.taucetistation.org/t/nauchnye-rigi-iksy-hardsuits/28647/95

2021-11-08 16:48 UTC, KIBORG04 commented
![image](https://user-images.githubusercontent.com/26389417/140783526-b0b90d0a-16e0-42ff-b138-7c4bb6266f69.png)


Этого быть не должно

2021-11-08 16:52 UTC, KIBORG04 commented on code/game/machinery/telecomms/telecomunications.dm
> +	if (!T_position) return
Приведи код в читаемый вид. Это касается не только отсутствия переноса строки здесь, но и всяких отсутствий переноса строки, слишком много переносов строки

2021-11-08 16:53 UTC, KIBORG04 requested changes

2021-11-08 16:53 UTC, KIBORG04 commented on code/datums/helper_datums/teleport.dm
> +	for(s in stabilizer)
```suggestion
	for(var/obj/item/rig_module/teleporter_stabilizer/s in stabilizer)
```

2021-11-08 16:53 UTC, KIBORG04 commented on code/game/objects/effects/portals.dm
> +		for(s in stabilizer)
```suggestion
		for(var/obj/item/rig_module/teleporter_stabilizer/s in stabilizer)
```

2021-11-08 17:14 UTC, kalazus commented on code/game/objects/items/devices/modkit.dm
> +	forbidden_type = list(
Не там находится список. Это модификатор шахтёрского.

2021-11-08 17:47 UTC, Dushess0 commented on code/game/objects/items/devices/modkit.dm
> +	forbidden_type = list(
Спасибо большое, поправил

2021-11-08 18:09 UTC, KIBORG04 commented on code/modules/clothing/spacesuits/rig/modules/utility.dm
> +	advanced_mode = 1
```suggestion
	advanced_mode = TRUE
```

2021-11-08 18:16 UTC, KIBORG04 commented on code/modules/clothing/spacesuits/rig/modules/utility.dm
> +
```suggestion
	active_power_cost = 3
	
```
Я не вижу смысла в этом

2021-11-08 18:16 UTC, KIBORG04 commented on code/modules/clothing/spacesuits/rig/modules/utility.dm
> +	active_power_cost = 200
```suggestion
/obj/item/rig_module/mounted_relay
	name = "hardsuit mounted relay module"
	desc = "Can relay radio signals from other sectors"
	origin_tech = "programming=6;engineering=6;bluespace=6"
	interface_name = "portable radio relay"
	interface_desc = "Can transmit messages to other  sectors as well as receive. Consumes a lot of energy when active."
	icon_state = "relay"
	suit_overlay = "mounted-relay"
	toggleable = TRUE
	show_toggle_button = TRUE
	module_cooldown = 0
	activate_string = "Activate radio relay"
	deactivate_string = "Deactivate radio relay"
	active_power_cost = 200

	var/relay_type = /obj/machinery/telecomms/relay/preset/portable
	var/obj/machinery/telecomms/relay
```
Так красивее и читабельнее.

2021-11-08 18:16 UTC, KIBORG04 commented on code/modules/clothing/spacesuits/rig/rig.dm
> +	initial_modules = list(/obj/item/rig_module/mounted_relay, /obj/item/rig_module/teleporter_stabilizer, /obj/item/rig_module/simple_ai/advanced, /obj/item/rig_module/selfrepair, /obj/item/rig_module/
```suggestion
	initial_modules = list(/obj/item/rig_module/mounted_relay, /obj/item/rig_module/teleporter_stabilizer, /obj/item/rig_module/simple_ai/advanced, /obj/item/rig_module/selfrepair, /obj/item/rig_module/cooling_unit, /obj/item/rig_module/device/science_tool, /obj/item/rig_module/device/analyzer, /obj/item/rig_module/device/anomaly_scanner)

```

2021-11-08 18:16 UTC, KIBORG04 commented on code/modules/research/designs.dm
> +/datum/design/rigstabilizer
```suggestion
	category = list("Rig Modules")

/datum/design/rigstabilizer
```
Не вижу смысла

2021-11-08 18:21 UTC, Dushess0 commented on code/modules/clothing/spacesuits/rig/modules/utility.dm
> +
Идея в том что он активен всегда когда вставлен в риг. Что бы ученые постоянно не бегали в ригах добавил что бы он потреблял энергию постоянно. Если например археологи хотят дольше бегать по астероду и им не надо защита для телепортера то они его просто выймут.

2021-11-08 18:23 UTC, KIBORG04 commented on code/modules/clothing/spacesuits/rig/modules/utility.dm
> +
Не, не, не. Проблема не в переменной, а в 3х переносов строк

2021-11-09 07:13 UTC, Sakuya-Izayoi commented
То есть ученые по-дефолту могут нырять в телепорт с блюспейс сумками? За бесплатно?

2021-11-09 07:21 UTC, Sakuya-Izayoi commented on code/modules/clothing/spacesuits/rig/modules/utility.dm
> +	desc = "A hardsuit-mounted atmospherics and anomalyies scanner."
```suggestion
	desc = "A hardsuit-mounted atmospherics and anomalies scanner."
```

2021-11-09 07:21 UTC, Sakuya-Izayoi commented on code/modules/clothing/spacesuits/rig/modules/utility.dm
> +	interface_desc = "Shows an anomalies frequencies and which reports current gas levels when used."
```suggestion
	interface_desc = "Shows anomalies frequencies and reports current gas levels when used."
```

2021-11-09 07:21 UTC, Sakuya-Izayoi commented on code/modules/clothing/spacesuits/rig/rig.dm
> +	diag_hud.add_hud_to(user)
наверное для этого можно закодить какой-то фреймворк (переменная у рига (а лучше у шлема) в которую программист вписывает худы, а в атом_ините они выдаются автоматом), потому что это очень крутая фича

2021-11-09 07:21 UTC, Sakuya-Izayoi commented on code/modules/mining/mining_fabricator/mining_research.dm
> +	materials = list(MAT_METAL=35000,MAT_GLASS=5000,MAT_PLASTIC=10000,MAT_SILVER=6000,MAT_PHORON=8000, MAT_DIAMOND=2000,MAT_GOLD=3000)
пробелы

2021-11-09 07:21 UTC, Sakuya-Izayoi commented on code/modules/research/designs.dm
> +	desc = "A hardsuit-mounted atmospherics and anomalyies scanner."
```suggestion
	desc = "A hardsuit-mounted atmospherics and anomalies scanner."
```

2021-11-09 07:21 UTC, Sakuya-Izayoi commented on code/modules/research/xenoarchaeology/artifact/effect.dm
> +		protection += 0.2
почему это не переменная у хардсьюита? (в прочем это наверное за рамками этого пра...)

2021-11-09 08:39 UTC, Dushess0 commented on code/modules/clothing/spacesuits/rig/rig.dm
> +	diag_hud.add_hud_to(user)
просто пока что это фича только рига СБ. Можно конечно дать ригу СБ и медиков и шахтеров их соотсветсвующие худы но они и так постоянно ходят в своих очках

2021-11-09 08:40 UTC, KIBORG04 commented on code/modules/clothing/spacesuits/rig/rig.dm
> +	diag_hud.add_hud_to(user)
(никто не ходит в ученочных худах только из-за ужасного желтого фильтра на все лицо)

2021-11-09 08:53 UTC, Dushess0 commented on code/modules/mining/mining_fabricator/mining_research.dm
> +	materials = list(MAT_METAL=35000,MAT_GLASS=5000,MAT_PLASTIC=10000,MAT_SILVER=6000,MAT_PHORON=8000, MAT_DIAMOND=2000,MAT_GOLD=3000)
добавил пробелы между материалами но в этом файле все они писались слитно

2021-11-09 08:55 UTC, Dushess0 commented on code/modules/clothing/spacesuits/rig/rig.dm
> +	diag_hud.add_hud_to(user)
Ну и это тоже, действительно выглядит ужасно
![image](https://user-images.githubusercontent.com/44201461/140893238-07721bde-8919-46d8-996b-67d0a46965bf.png)

2021-11-09 09:27 UTC, Dushess0 commented
> То есть ученые по-дефолту могут нырять в телепорт с блюспейс сумками? За бесплатно?

Сначала им нужно эти сумки исследовать и ресурсы на них получить. Плюс с начала раунда только 2 рига учёных(1 у археологов, 1 в теленауке) и один риг РД. Так что на всех не хватит

2021-11-10 15:00 UTC, KIBORG04 commented on code/game/machinery/telecomms/telecomunications.dm
> +	if (!T_position)
Я не уверен значем это нужно. Откуда тут может быть телеком в нуллспейсе?

2021-11-10 15:05 UTC, KIBORG04 commented on code/modules/clothing/spacesuits/rig/modules/utility.dm
> +		relay = new relay_type(src)
```suggestion
	relay = new relay_type(src)
```
Очень странна проверка, учитывая, что это буквально модуль, в котором должно быть реле

2021-11-10 15:30 UTC, Dushess0 commented on code/game/machinery/telecomms/telecomunications.dm
> +	if (!environment)
да именно

2021-11-10 15:31 UTC, Dushess0 commented on code/game/machinery/telecomms/telecomunications.dm
> +	if (!T_position)
я реализовал реле так что оно существует внутри скафандра, и когда этой проверки не было генерировался рантайм.

2021-11-10 17:14 UTC, Dushess0 commented on code/game/machinery/telecomms/telecomunications.dm
> +	if (!environment)
Убрал эту проверку

2021-11-10 22:04 UTC, KIBORG04 approved these changes
С кодом вроде все

2021-11-11 10:41 UTC, Akellazp commented
а не дохера ли модулей у этих ригов?

2021-11-11 16:16 UTC, LeBubble commented
> а не дохера ли модулей у этих ригов?

В голосовалке на форуме комьюнити решило так

2021-11-12 10:33 UTC, KIBORG04 commented
в дисе слапай

2021-11-12 11:10 UTC, LeBubble commented
> ![image](https://user-images.githubusercontent.com/47355061/141452595-5370d168-fc3b-4fc5-a77f-addb0588cfaf.png) https://www.youtube.com/watch?v=b8Di2-vUxx8 Это даже не риг рд а обычный Даже у ригов глав меньше слотов нужен @EdlerN как представитель баланс департамента

и 0 защиты от почти любого физ урона

2021-11-12 11:24 UTC, Dushess0 commented
> > ![image](https://user-images.githubusercontent.com/47355061/141452595-5370d168-fc3b-4fc5-a77f-addb0588cfaf.png) https://www.youtube.com/watch?v=b8Di2-vUxx8 Это даже не риг рд а обычный Даже у ригов глав меньше слотов нужен @EdlerN как представитель баланс департамента
> 
> и 0 защиты от почти любого физ урона

у ригов глав 6 слотов, у обычных 4. Тут я сделал что бы у обычного рига ученого было 6 слотов, у РД 8, что бы у рига была уникальность. Если оставить количество слотов как у всех ригов то ученым просто выгоднее сделать медицинский риг у которого такое же замедление но броня выше (30 от мили против 5). Если сделать 5 и 7 то разница почти не чувствуется.  

Вот голосование в теме было:

![image](https://user-images.githubusercontent.com/44201461/141458048-c5d0ba66-4382-405a-8db0-f699cad07681.png)
  Чуть больше людей проголосовало за вариант с 6 и 8, но думаю что те кто голосовали за 5 и 7 не против того что бы было 6 и 8.

2021-11-12 20:05 UTC, KIBORG04 commented
Мы уже решили, что это кодеро-ПР и аппрув удава не нужен (он сам так решил)

2021-11-13 21:39 UTC, Dushess0 commented
Обновил спрайты ригов на новые от WalterJe

2021-11-13 21:41 UTC, TauKitty commented
This pull request has been mentioned on **Tau Ceti Station Forum**. There might be relevant details there:

https://forum.taucetistation.org/t/nauchnye-rigi-iksy-hardsuits/28647/121

2021-11-14 12:59 UTC, EdlerN commented
А может мне автор ПРа пояснить, почему у модуля который позволяет абузить и так абузное телесало ещё больше потребление в активном состоянии - 3, а у портативного реле, которое по факту позволяет тебе ВАУ не брать с собой рацию - потребление 200?
Почему эуспериментальный сканер аномалий потребляет больше чем обычный анализатор воздуха, который есть в ПДА? Откуда взялись эти цены?

2021-11-14 13:16 UTC, EdlerN commented
Для контекста, надо понимать что у нас цены использования ригов самих по себе занерфлены в говно по причине того что все стали ныть что менять батарейку раз в 20 минут требует слишком много лишних телодвижений а нам хочется бегать в ригах так же как мы в них бегали до того как ввели их новую реализацию. 

Что до слотов - два лишних слота особо погоды не делают. Да, есть у тебя лазган, который всем видно, который ты можешь использовать со связанными руками от батарейки рига. Есть у тебя РЦД. Защиты тебе это не добавляет. 

Строго говоря, было бы неплохо если бы кто-то изобразил систему, когда при установки в "не-свой-родной" риг модули работали хуже. Т.е. оружие в не-сбшном риге стреляет медленнее (или менее точно), РЦД в не-инженерном разгоняется дольше, ну и всякое такое. Но это так, мысли вслух. И уж точно не в рамках данного ПРа.

2021-11-14 13:19 UTC, KIBORG04 commented
Так че, мержить после изменения костов?

2021-11-14 14:37 UTC, Dushess0 commented
> А может мне автор ПРа пояснить, почему у модуля который позволяет абузить и так абузное телесало ещё больше потребление в активном состоянии - 3, а у портативного реле, которое по факту позволяет тебе ВАУ не брать с собой рацию - потребление 200? Почему эуспериментальный сканер аномалий потребляет больше чем обычный анализатор воздуха, который есть в ПДА? Откуда взялись эти цены?

Модуль что абузит телесало включен постоянно и выключить его невозможно, только вынять из рига, что в космосе сделать трудно. Сделал это так что бы абуз не был аж такой сильный и те кому это не нужно (археологи к примеру) могли вынять этот модуль и сэкономить батарейку. Думаю можно расход повысить до 10, тогда рига будет хватать на минут 15 если модуль вставлен.

Портативное Реле сделал 200( раньше 250) с целью того что бы если нужно передать что то важное на станцию, то мы включаем реле, говорим сообщение, ждем ответа и выключаем после переговоров. Рация не дает связь на другие сектора и есть смысл ее брать только если идешь в теленауку не один.  Сейчас заряда хватает на полторы минуты переговоров. Если снизить до 50 расход то будет хватать на 6 минут

Насчет сканнера воздуха согласен, 100 слишком много за использование, цифру брал из модуля медиков (у них тоже 100 энергии за штуку что они постоянно носят с собой). Думаю можно понизить до 25. 


То есть:

- реле - снизить с 200 до 50
- сканнер - снизить с 100 до 25
- Телепорт - повысить с 3 до 10

Так нормально будет?

2021-11-14 15:33 UTC, EdlerN commented
Не забывай ещё пожалуйста, что учёные они учёные и если у них будет доступ к модулю стабилизации телепорта, то наверное и БС-батарейкам у них тоже доступ будет. А это 40 тысяч заряда, чего хватает... надолго. Честно говоря, я бы скорее сделал этот модуль в формате того что по нажатию на кнопку за каких-то условных 4 тысячи заряда ты получаешь секунда на 30 возможность нормально телепортироваться. И потом откат секунд на 30. Потому что, если он не выключаемым его сделаешь то это слишком уж много мороки занимать будет. И он в конечном итоге будет либо бесполезным, либо чем-то что ты просто вставил и забыл.

2021-11-14 15:38 UTC, EdlerN commented
>Портативное Реле сделал 200( раньше 250) с целью того что бы если нужно передать что то важное на станцию, то мы включаем реле, говорим сообщение, ждем ответа и выключаем после переговоров. Рация не дает связь на другие сектора и есть смысл ее брать только если идешь в теленауку не один. Сейчас заряда хватает на полторы минуты переговоров. Если снизить до 50 расход то будет хватать на 6 минут

А ты можешь тогда сделать отдельно раздачу связи на слое и раздачу связи между слоями? И быть может даже сделать два типа реле. Обычное которое будет на конкретном слое раздавать и умеренно жрать, и продвинутое, которое будет работать между слоями но при включении передачи на все слои - жрать побольше?

2021-11-14 15:42 UTC, Dushess0 commented
> А это 40 тысяч заряда, 
Как насчет того что бы модуль потреблял процент от максимального заряда батареи + определенную постоянную? Скажем для 10 000 стандартной потребление 10 000 * 0.0005  + 5 = 10, а для блюспейс 40 000 потребление = 40 000 * 0.0005 + 5 = 25. Тогда блюспейс батарея будет иметь преимущество над стандартной но не такое сильное.

2021-11-14 15:46 UTC, EdlerN commented
Это немного нелогично. Почему модуль начинает потреблять больше просто потому что мы поменяли батарею? Опять блюспейс?

2021-11-14 15:48 UTC, Dushess0 commented
Больше батарейка, значит больше интерференций может появлятся при телепорте (увеличили кол-во заряда, напряжение там или сопротивление или ещё что то изменилось), значит больше стабилизировать надо. Ну да, можно блюспейсом оправдать

2021-11-14 15:55 UTC, EdlerN commented
Ну такое всё равно. У нас у людей всё очень плохо с долговременным планированием и потому делать существенное потребление на постоянной основе - приведёт к нытью и обсуждениям того, какое же это безполезное говно каждые 10 минут вылезать из рига приходится. В то же время если сделать слишком маленькое потребление - мы получим другую проблему, того что у нас как бы экспериментальная технология со своими проблемами и побочками, которые мы на деле игнорируем за нихуя. Как итог - саентисты которые воруют у повара пончики и трусы у клована чисто по-ржать. Это не говоря уже про интересные варианты запихивания людей в эти самые воронки до состояния когда их начнёт плющить, кинет в стан, ну а дальше как водится. 
У возможности игнорировать побочки телепорта должна быть какая-то вменяемая цена. Вменяемая и понятная юзеру. Ты думаешь каждый у нас на сервере понимает, сколько протянет его риг со всем на него навешанным и может правильно оценивать то что он собрал? 
Предложенный же мой вариант в этом плане будет куда лучше, ибо человеку сразу понятно что он получает и что он за это платит.

2021-11-14 16:13 UTC, Dushess0 commented
С активируемой защитой будет такая проблема что если сделать кулдаун и длительность слишком большими то ученый условно заходит в воронку, видит что не туда, выходит начинает считать по новой, проходит 30 секунд и уже бафф слетел и ему или ждать ещё 30 секунд и опять тратить энергию или зайти уже без баффа, тогда какой смысл в том модуле. Если же сделать кулдаун к примеру 5 секунд то пользователя достанет каждый раз это прожимать и он будет просто забывать это делать. 

Я бы попробовал посмотреть как люди отреагируют на постоянное потребление энергии. Сейчас побочки телепорта это не та вещь что прям мешает геймплею ученого. Он и сейчас уверенно ворует карту капитана/трусы/пончики. В случае если человек плохо оценивает длительность то у них установлена диагностика что будет напоминать что батарейку стоит сменить.

2021-11-14 16:16 UTC, EdlerN commented
Ну, да, КД на телепорты призван как раз таки добавить какую-то цену ошибочному использованию. Либо жди либо иди уже без защиты.

Вообще, можно сделать ещё проще и сказать что пассивно он жрёт 3, но за каждый проход в портал сжирает 2 тысячи. Опционально в два раза больше при наличии блюспейс сумки на пользователе.

2021-11-14 16:16 UTC, Dushess0 commented
Такое мне нравится

2021-11-14 16:17 UTC, EdlerN commented
А то что блюспейс пакет абузится во всех возможных направлениях это скорее баг а не фича.

2021-11-14 16:20 UTC, EdlerN commented
Две тысячи нормально как по мне. Если вспоминать что у нас обычные батарейки по 10к, у тебя есть запас на два прохода туда-обратно плюс ещё запас. С БС батарейкой так вообще всё прекрасно становится.

2021-11-14 16:22 UTC, Dushess0 commented
Я бы полторы тысячи дал и удваивал за сумку блюспейс. Ещё такой вопрос, когда человек входит в стационарный телепорт что не откалиброван то там есть хороший шанс облучится. Добавить ли эту же проверку в в этом случае? То есть снять заряд но не получить дозу.

2021-11-14 16:39 UTC, EdlerN commented
Стац телепорт без калибровки ещё и выкинуть может в далёкие дали. Хотя он и с калибровкой опасен если у тебя БС сумка. Ахда, у хендтеле же тоже есть шансы сбоить. 

Полторы можно попробовать как вариант. Но тогда можно к примеру за использование небезопасных телепортов тоже удваивать (когда без калибровки используем обычный телепотр). Ну и к слову неплохо было бы сделать так чтобы блюспейс мешок так же влиял на телепортацию как и сумка, ибо по смыслу они одно и то же из себя представляют на данный момент.

2021-11-14 16:40 UTC, EdlerN commented
В общем, чем больше рисков модуль нивелирует при телепортации - тем больше расход энергии за переход должен быть.

2021-11-14 18:01 UTC, Dushess0 commented
Сделал так что:
Если просто заходим в телепорт в теленауке то снимает 1500 за то что нету негативных эффектов.
Если заходим в стационарный телепорт что откалиброван то ничего не снимает потому что он надежный.
Если заходим в неоткалиброванный стационный телепорт то снимет 3000 и не будет вреда нам.
Если с нами блюспейс сумка то снимает допольнительно ещё 1500.
Плюс если модуль поврежден то у него расход энергии выше на 25%

2021-11-14 18:10 UTC, Dushess0 commented
> А ты можешь тогда сделать отдельно раздачу связи на слое и раздачу связи между слоями? И быть может даже сделать два типа реле. Обычное которое будет на конкретном слое раздавать и умеренно жрать, и продвинутое, которое будет работать между слоями но при включении передачи на все слои - жрать побольше?

На такое у меня умения не хватит. Плюс возможна ситуация когда на станции нету связи (телекомы уничтожены) тогда ученый бы просто включил связь на данном секторе в своем риге и весь план нюки, ИИ, трейтора был бы сломан. Сейчас реле РД использует существующую сеть комуникации, если сломать телекомы на спутнике то переносное реле не поможет.

2021-11-15 13:54 UTC, KIBORG04 commented on code/modules/clothing/spacesuits/rig/modules/utility.dm
> +	if (!cost) return FALSE
ретурн на новой строке

2021-11-15 13:54 UTC, KIBORG04 commented on code/modules/clothing/spacesuits/rig/modules/utility.dm
> +	if (!cost) return FALSE
ретурн на новой строке

2021-11-15 13:54 UTC, KIBORG04 commented on code/modules/clothing/spacesuits/rig/modules/utility.dm
> +	if (damage>=MODULE_DESTROYED) return FALSE
Пробелы  и ретурн на новой строке

2021-11-15 13:57 UTC, KIBORG04 commented on code/modules/clothing/spacesuits/rig/modules/utility.dm
> +		return TRUE
Скорее всего, ниже должен быть еще один return FALSE

2021-11-15 13:57 UTC, KIBORG04 commented on code/modules/clothing/spacesuits/rig/modules/utility.dm
> +		return TRUE
Скорее всего, ниже должен быть еще один return FALSE

2021-11-15 13:59 UTC, KIBORG04 commented on code/modules/clothing/spacesuits/rig/modules/utility.dm
> +	if (damage>=MODULE_DESTROYED) return FALSE
а еще это должен быть не ретурн фолс, а ретурн 0

2021-11-15 14:00 UTC, KIBORG04 commented on code/modules/clothing/spacesuits/rig/modules/utility.dm
> +	if (damage>=MODULE_DESTROYED) return FALSE
А не, как раз нет. Почему метод base_check возвращает вообще какую-то стоимость?

2021-11-15 14:01 UTC, Dushess0 commented on code/modules/clothing/spacesuits/rig/modules/utility.dm
> +	if (damage>=MODULE_DESTROYED) return FALSE
ок, поправил

2021-11-15 14:03 UTC, KIBORG04 commented on code/modules/clothing/spacesuits/rig/modules/utility.dm
> +	return cost
Почему метод с названием base_check() возвращает цену действия?

2021-11-15 14:04 UTC, Dushess0 commented on code/modules/clothing/spacesuits/rig/modules/utility.dm
> +	if (damage>=MODULE_DESTROYED) return FALSE
идея была такая что в base check проверяю целостность и если модуль сломан то процедуры типо stabilize_precision() и remove_side_effects() должны возрвращать FALSE

2021-11-15 14:41 UTC, Dushess0 commented on code/modules/clothing/spacesuits/rig/modules/utility.dm
> +	return cost
перенес это, теперь лучше?

2021-11-15 18:25 UTC, Dushess0 commented on code/modules/clothing/spacesuits/rig/modules/utility.dm
> +	return cost
@KIBORG04

2021-11-15 21:47 UTC, KIBORG04 commented on code/modules/clothing/spacesuits/rig/modules/utility.dm
> +	return FALSE
Начну дальше по синтаксису прессовать. 

Смотри. stabilize_precision и remove_side_effects(false) делают абсолютно одинаковые вещи, отличаются буквально только предложение. Так вот, почему бы не использовать stabilize_precision всегда там, где в remove_side_effects передают фолс? А так как у remove_side_effects уйдет двойное поведение, которое зависит от аргумента функции, то этот аргумент просто не будет нужен. 

Так же, наверное было бы правильнее в calculate_cost передавать не ТРУ/ФОЛС. Назвать параметр `dangerous_coeff` и передавать 2.0

2021-11-15 22:52 UTC, Dushess0 commented on code/modules/clothing/spacesuits/rig/modules/utility.dm
> +	return FALSE
remove_side_effects использую когда заходим в воронку в теленауке и в не откалиброваный телепорт что бы не блевал,  teleporter_stabilizer используется только когда на нас блюспейс рюкзак. Я бы превратил это в одну процедуру `stabilize_teleportation` куда передаем `dangerous_coeff` с какой то общей надписью: Teleporter stabilization system activated. Cell charge used: [cost] . Но тогда она будет два раза выводится если например заходим в портал с рюкзаком. Такое нормально будет?  
![image](https://user-images.githubusercontent.com/44201461/141865262-14e63a10-c516-49dc-a7b7-0147079a8aa6.png)




<details>
  <summary>В коде будет как то так выглядеть</summary>

  ```
  /obj/item/rig_module/teleporter_stabilizer/proc/calculate_cost(dangerous_coeff)
	var/cost = use_power_cost
	if(damage > MODULE_NO_DAMAGE)
		cost *= 1.25
	return cost * dangerous_coeff

/obj/item/rig_module/teleporter_stabilizer/proc/base_check()
	var/mob/living/carbon/human/H = holder.wearer
	if(!H || damage >= MODULE_DESTROYED)
		return FALSE
	return TRUE

/obj/item/rig_module/teleporter_stabilizer/proc/stabilize_teleportation(dangerous_coeff = 1)
	if(!base_check())
		return FALSE
	var/cost = calculate_cost(dangerous_coeff)
	if(holder.try_use(holder.wearer, cost, use_unconcious = TRUE, use_stunned = TRUE))
		to_chat(holder.wearer, "<span class='notice'>Teleporter stabilization system activated. Cell charge used: [cost].</span>")
		return TRUE
	return FALSE
  ```
</details>
</details>

2021-11-15 22:55 UTC, KIBORG04 commented on code/modules/clothing/spacesuits/rig/modules/utility.dm
> +	return FALSE
А разве раньше не будет будет два раза писаться?

2021-11-15 22:57 UTC, Dushess0 commented on code/modules/clothing/spacesuits/rig/modules/utility.dm
> +	return FALSE
Там писало два раза но разные надписи. Одна касалась состояния здоровья вторая относительно блюспейс рюкзака

2021-11-15 22:58 UTC, KIBORG04 commented on code/modules/clothing/spacesuits/rig/modules/utility.dm
> +	return FALSE
Что так плохо, что тогда, но что поделать?

2021-11-15 23:00 UTC, Dushess0 commented on code/modules/clothing/spacesuits/rig/modules/utility.dm
> +	return FALSE
я за вариант что бы это была одна процедура, если два раза пишется одно и тоже фиг с ним. По моему две процедуры что отличаются строчкой все же хуже.

2021-11-15 23:04 UTC, Dushess0 commented on code/modules/clothing/spacesuits/rig/modules/utility.dm
> +	return FALSE
можно вообще убрать вывод текста но тогда игрокам будет сложнее понять логику как оно работает

2021-11-16 00:01 UTC, Dushess0 commented on code/modules/clothing/spacesuits/rig/modules/utility.dm
> +	return FALSE
в общем изменил процедуру, Resolve conversation?

2021-11-16 12:37 UTC, merged