Изменение роста персонажа через Preferences
TauCetiStation/TauCetiClassic pull request #8179
Opened 2021-11-08 20:16 UTC by DarthSidiousPalpatine

## Описание изменений
Изначальный рост персонажа - 1.8 метра.
Теперь можно изменять рост персонажа от 1.6 до 2.0 метров:
![image](https://user-images.githubusercontent.com/21008918/140811249-14d6f39f-41df-4f1f-b0e0-1020880ea454.png)

Также, Гномы перестали быть шакальными и их рост также зависит от роста изначального персонажа:
![image](https://user-images.githubusercontent.com/21008918/140811268-f4670b49-c972-45d8-9d8a-f87a858f72cd.png)

## Почему и что этот ПР улучшит
Кастомизация персонажа, плюс красиво.

## Авторство
@FatFatFat1 @DarthSidiousPalpatine и все-все-все, кто помогал в дискорде.

## Чеинжлог
:cl:
 - rscadd: Теперь можно выбирать рост персонажа от 1.6 метра до 2.0 метров.
 - rscadd: Теперь рост гномов зависит от роста персонажа.
 - tweak: Теперь гномы не шакальные минихуманы, а реально гномы.

2021-11-08 20:16 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2021-11-08 20:21 UTC, LudwigVonChesterfield commented on code/datums/atom_huds/atom_hud.dm
> +			A.hud_list[i].appearance_flags |= KEEP_APART
Интересное решение, а что если моя картинка хочет быть KEEP_TOGETHER?

2021-11-08 20:26 UTC, TauKitty commented
This pull request has been mentioned on **Tau Ceti Station Forum**. There might be relevant details there:

https://forum.taucetistation.org/t/sistema-rosta/29244/51

2021-11-08 20:26 UTC, LudwigVonChesterfield commented on code/modules/client/preferences.dm
> +	var/icon/Cut1 = new('icons/effects/cut.dmi',"Cut1")
Интерисуюсь как много одежды это будет ломать. Платье какое-нибудь в купальник не превратится?

2021-11-08 20:26 UTC, LudwigVonChesterfield commented on code/modules/client/preferences.dm
> +	var/height = 1.8					//height of character
Пытаюсь понять почему эта переменная не категориальная

вместо HEIGHT_VERY_TALL, HEIGHT_TALL, HEIGHT_NORMAL, HEIGHT_KARLAN флоат, который потом юзается будто это просто категории

2021-11-08 20:26 UTC, LudwigVonChesterfield commented on code/modules/mob/living/say.dm
> +	I.appearance_flags = APPEARANCE_UI_IGNORE_ALPHA|KEEP_APART
а что, обрезалось вместе с человеком?

2021-11-08 20:26 UTC, LudwigVonChesterfield commented on code/modules/mob/living/say.dm
> +	I.appearance_flags = APPEARANCE_UI_IGNORE_ALPHA|KEEP_APART
если да, то разве не нужно пройтись по всем остальным эффектам визуальным всяким типо там к примеру ду_афтер полоски, и т.д. ... ?

2021-11-08 20:28 UTC, DarthSidiousPalpatine commented on code/modules/client/preferences.dm
> +	var/height = 1.8					//height of character
Потому что рост может быть от 1.6 до 2.0 и игрок пишет свой

2021-11-08 20:28 UTC, DarthSidiousPalpatine commented on code/modules/client/preferences.dm
> +	var/icon/Cut1 = new('icons/effects/cut.dmi',"Cut1")
Не сильно ломает, срезание 1 пиксельной полоски

2021-11-08 20:30 UTC, DarthSidiousPalpatine commented on code/datums/atom_huds/atom_hud.dm
> +			A.hud_list[i].appearance_flags |= KEEP_APART
Я, на самом деле, не уверен насколько эти флаги нужны в текущей реализации сокращения. В прошлой реализации просто хумана ресайзили через трансформ матрицу и все худы и спичбаблы ломались. Сейчас же мы не затрагиваем, вроде как, их, но, на будущее, для будущих худов, наверное, лучше оставить.

2021-11-08 21:23 UTC, KIBORG04 commented on code/game/dna/genes/powers.dm
> +	var/icon/Cut2 = new('icons/effects/cut.dmi',"Cut2")
```suggestion
	var/static/icon/Cut1 = icon('icons/effects/cut.dmi', "Cut1")
	var/static/icon/Cut2 = icon('icons/effects/cut.dmi', "Cut2")
```
Не уверен, что айконам нужны статики, но лучше пусть будут.

2021-11-08 21:27 UTC, KIBORG04 commented on code/game/dna/genes/powers.dm
> +		H.filters += filter(type="displace",x = 0,y = 0,size = 2,icon = Cut1)
Используй высокоуровневый add_filter и remove_filter, а не это

2021-11-08 21:27 UTC, KIBORG04 commented on code/modules/client/character menu/general.dm
> +						height = clamp(round(text2num(new_height)*10)/10, 1.6, 2.0)
```suggestion
						height = clamp(round(text2num(new_height) * 10) /10, 1.6, 2.0)
```
а зачем сначала умножать на 10, а потом делить?

2021-11-08 21:27 UTC, KIBORG04 commented on code/modules/client/preferences.dm
> +	var/icon/Cut2 = new('icons/effects/cut.dmi',"Cut2")
Тоже самое, что и выше. Добавь статик и замени нью на icon

2021-11-08 21:27 UTC, KIBORG04 commented on code/modules/client/preferences.dm
> +			character.filters += filter(type="displace",x = 0,y = 0,size = 1,icon = Cut1)
Тоже самое, что и выше. Используй высокоуровневые методы

2021-11-08 21:27 UTC, KIBORG04 commented on code/modules/client/preferences.dm
> +	character.filters = null
Зачем ты убираешь ВСЕ фильтры с человека, а не только определенные? Это плохо

2021-11-08 21:27 UTC, KIBORG04 commented on code/modules/mob/living/carbon/human/human.dm
> +	appearance_flags |= KEEP_TOGETHER
Почему это тут, а не объявлено при объявление класса?

2021-11-08 21:28 UTC, KIBORG04 commented on code/modules/client/preferences.dm
> +	var/height = 1.8					//height of character
А мог бы не писать, а выбирать из 5 значений...

2021-11-08 21:33 UTC, DarthSidiousPalpatine commented on code/modules/client/character menu/general.dm
> +						height = clamp(round(text2num(new_height)*10)/10, 1.6, 2.0)
Чтобы round не округлял до целых.

2021-11-08 21:34 UTC, KIBORG04 commented on code/modules/client/character menu/general.dm
> +						height = clamp(round(text2num(new_height)*10)/10, 1.6, 2.0)
У раунда же есть еще аргументы. Поидее, round(text2num(new_height), 1.0) должно сработать

2021-11-08 21:34 UTC, DarthSidiousPalpatine commented on code/modules/mob/living/carbon/human/human.dm
> +	appearance_flags |= KEEP_TOGETHER
При объявлении класса оно не работает, по какой-то причине. Жалуется.

2021-11-08 21:35 UTC, KIBORG04 commented on code/modules/client/character menu/general.dm
> +						height = clamp(round(text2num(new_height)*10)/10, 1.6, 2.0)
а, нет.

2021-11-08 21:36 UTC, KIBORG04 commented on code/modules/client/character menu/general.dm
> +						height = clamp(round(text2num(new_height)*10)/10, 1.6, 2.0)
А, да. Но нужно `round(text2num(new_height), 0.1)`

2021-11-08 21:39 UTC, DarthSidiousPalpatine commented on code/modules/client/preferences.dm
> +	character.filters = null
Потому что как узнать какой фильтр надо убирать? Могу ли я убрать фильтр, которого нет?

2021-11-08 21:40 UTC, KIBORG04 commented on code/modules/mob/living/carbon/human/human.dm
> +	appearance_flags |= KEEP_TOGETHER
попробуй appearance_flags = TILE_BOUND|PIXEL_SCALE|KEEP_TOGETHER вписать

2021-11-08 21:41 UTC, KIBORG04 commented on code/modules/client/preferences.dm
> +	character.filters = null
Я же тебе даже в дисе вкинул. Если бы ты юзал высокоуровневые методы, ты бы щас меня не спрашивал.

2021-11-08 21:47 UTC, DarthSidiousPalpatine commented on code/modules/mob/living/carbon/human/human.dm
> +	appearance_flags |= KEEP_TOGETHER
Исправил

2021-11-08 21:48 UTC, DarthSidiousPalpatine commented on code/modules/client/preferences.dm
> +	character.filters = null
Сделал

2021-11-08 21:48 UTC, DarthSidiousPalpatine commented on code/modules/client/preferences.dm
> +			character.filters += filter(type="displace",x = 0,y = 0,size = 1,icon = Cut1)
Использую

2021-11-08 21:49 UTC, SpaiR requested changes

2021-11-08 21:49 UTC, SpaiR commented on code/modules/client/preferences_savefile.dm
> +	height			= sanitize_integer(height, 1.6, 2.0, initial(height))
Санитпйз под капотом делает round до целых, так что при загрузке префов всегда будет 2. Тебе стоит, как и посоветовали господы выше, сделать категории за дефайнами. Работать с добрыми в принципе плохая идея.

2021-11-08 21:51 UTC, DarthSidiousPalpatine commented on code/modules/client/preferences_savefile.dm
> +	height			= sanitize_integer(height, 1.6, 2.0, initial(height))
Но оно не делает этого, почему-то.

Ладно, сделать 5 дефайнов роста...

2021-11-08 22:35 UTC, LudwigVonChesterfield commented on code/datums/atom_huds/atom_hud.dm
> +			A.hud_list[i].appearance_flags |= KEEP_APART
если для твоей реализации не нужны то убирай

2021-11-08 22:39 UTC, DarthSidiousPalpatine commented on code/datums/atom_huds/atom_hud.dm
> +			A.hud_list[i].appearance_flags |= KEEP_APART
Убрал

2021-11-08 22:42 UTC, LudwigVonChesterfield commented on code/datums/atom_huds/atom_hud.dm
> +			A.hud_list[i].appearance_flags |= KEEP_APART
А в других местах эти флаги нужны что-ли?

2021-11-08 22:43 UTC, DarthSidiousPalpatine commented on code/datums/atom_huds/atom_hud.dm
> +			A.hud_list[i].appearance_flags |= KEEP_APART
Да

2021-11-08 22:43 UTC, LudwigVonChesterfield commented on code/modules/mob/living/carbon/human/human_defines.dm
> +	var/static/icon/Cut1 = icon('icons/effects/cut.dmi',"Cut1")
Может это можно по-человечески назвать? "cut_torso_mask", "cut_legs_mask" и т.д.?

2021-11-08 23:34 UTC, DarthSidiousPalpatine commented on code/modules/client/preferences_savefile.dm
> +	height			= sanitize_integer(height, 1.6, 2.0, initial(height))
Всё, сделано так, как надо, вроде.

2021-11-09 04:53 UTC, KIBORG04 commented on code/game/dna/genes/powers.dm
> +	var/icon/Cut2 = new('icons/effects/cut.dmi',"Cut2")
Зачем резолвать, если ничего не изменилось?

2021-11-09 05:02 UTC, KIBORG04 commented on code/modules/mob/living/carbon/human/human_defines.dm
> +	var/static/icon/lenghten_legs_mask = icon('icons/effects/cut.dmi',"Cut4")
Помести это лучше в update_height. Так, наверное, будет более понятней зачем это и где используется

2021-11-09 05:02 UTC, KIBORG04 commented on code/modules/client/preferences.dm
> +
```suggestion
```

2021-11-09 05:02 UTC, KIBORG04 commented on code/modules/client/character menu/general.dm
> +					var/new_height = input(user, "Choose your character's height:\n([1.6]-[2.0])", "Character Height", text2num(height)) as num|null
```suggestion
					var/new_height = input(user, "Choose your character's height:\n(1.6-2.0)", "Character Height", text2num(height)) as num|null
```

2021-11-09 08:41 UTC, DarthSidiousPalpatine commented on code/game/dna/genes/powers.dm
> +	var/icon/Cut2 = new('icons/effects/cut.dmi',"Cut2")
Как не изменилось-то вообще. Давно же уже всё поменял
Резолвни сам тогда как захочешь.

2021-11-09 08:42 UTC, KIBORG04 commented on code/game/dna/genes/powers.dm
> +	var/icon/Cut2 = new('icons/effects/cut.dmi',"Cut2")
![image](https://user-images.githubusercontent.com/26389417/140891143-501c0c60-06bc-421b-a81e-70fde90d378d.png)

2021-11-09 08:47 UTC, DarthSidiousPalpatine commented on code/game/dna/genes/powers.dm
> +	var/icon/Cut2 = new('icons/effects/cut.dmi',"Cut2")
Ля посмотри в код:
![image](https://user-images.githubusercontent.com/21008918/140891889-583b26e3-733a-4659-b5c6-ae010311ae0e.png)

2021-11-09 08:50 UTC, KIBORG04 commented on code/game/dna/genes/powers.dm
> +	var/icon/Cut2 = new('icons/effects/cut.dmi',"Cut2")
Я тебе показываю на файл `code/game/dna/genes/powers.dm`, а не хуманов

2021-11-09 09:03 UTC, KIBORG04 commented on code/game/dna/dna2.dm
> +	SetUIValueRange(DNA_UI_HEIGHT,    height,    heights_list.len,    1)
```suggestion
	SetUIValueRange(DNA_UI_BEARD_STYLE, beard, facial_hair_styles_list.len,1)
	SetUIValueRange(DNA_UI_HEIGHT,           height,    heights_list.len,    1)
```

2021-11-09 09:11 UTC, KIBORG04 commented on code/_globalvars/lists/flavor_misc.dm
> +var/global/list/heights_list = list("1.6","1.7","1.8","1.9","2.0")
```suggestion
var/global/list/heights_list = list("1.6","1.7","1.8","1.9","2.0")

```

2021-11-09 09:11 UTC, KIBORG04 commented on code/game/dna/dna2_helpers.dm
> +		var/height = dna.GetUIValueRange(DNA_UI_HEIGHT,heights_list.len)
```suggestion
		var/height = dna.GetUIValueRange(DNA_UI_HEIGHT, heights_list.len)
```

2021-11-09 09:11 UTC, KIBORG04 commented on code/game/gamemodes/modes_gameplays/changeling/powers/transform.dm
> +	user.update_height()
```suggestion
```
Оно уже в UpdateAppearance вызывается

2021-11-09 09:11 UTC, KIBORG04 commented on code/modules/mob/living/carbon/human/human.dm
> +	update_height()
Оно же вообще не нужно в атом_ините. Лучше пихни в regenerate_icons, если оно прям совсем нужно при ините куклы

2021-11-09 09:23 UTC, DarthSidiousPalpatine commented on code/modules/mob/living/carbon/human/human.dm
> +		remove_filter(list("Gnome_Cut_Torso","Gnome_Cut_Legs"))
Не понял

2021-11-09 09:24 UTC, KIBORG04 commented on code/modules/mob/living/carbon/human/human.dm
> +		remove_filter(list("Gnome_Cut_Torso","Gnome_Cut_Legs"))
Ты можешь обычному росту уменьшить количество названий с `"Cut_Torso","Cut_Legs","Lenghten_Legs","Lenghten_Torso"` на `"Cut_Torso","Cut_Legs"`

2021-11-09 09:28 UTC, DarthSidiousPalpatine commented on code/modules/mob/living/carbon/human/human.dm
> +		remove_filter(list("Gnome_Cut_Torso","Gnome_Cut_Legs"))
Но ведь, Удлинение ног это не то же самое что обрезание ног.

2021-11-09 09:31 UTC, KIBORG04 commented on code/modules/mob/living/carbon/human/human.dm
> +		remove_filter(list("Gnome_Cut_Torso","Gnome_Cut_Legs"))
Какая разница, если они все равно по задумке не могут быть одновременно

2021-11-09 09:37 UTC, DarthSidiousPalpatine commented on code/modules/mob/living/carbon/human/human.dm
> +		remove_filter(list("Gnome_Cut_Torso","Gnome_Cut_Legs"))
Могут быть в будущем. Например, выбрать длинные ноги при остающемся росте.

2021-11-09 09:39 UTC, KIBORG04 commented on code/modules/mob/living/carbon/human/human.dm
> +		remove_filter(list("Gnome_Cut_Torso","Gnome_Cut_Legs"))
Ладно, поставь пробелы тогда после запятых

2021-11-09 09:43 UTC, DarthSidiousPalpatine commented on code/modules/mob/living/carbon/human/human.dm
> +		remove_filter(list("Gnome_Cut_Torso","Gnome_Cut_Legs"))
Уже поставил, у тебя тут старая версия.

2021-11-09 11:51 UTC, Sakuya-Izayoi commented on code/modules/admin/verbs/massmodvar.dm
> +										H.vars[variable] = num2text(round(new_value,0.1))
я вижу, что парой строчек выше сделано так же, но разве не лучше ли напрямую сразу обращаться к нужной переменной, а не через vars? Особенно учитывая что мы уже знаем, что наш объект нужного типа.

2021-11-10 13:42 UTC, volas commented on code/modules/admin/verbs/modifyvariables.dm
> +							return
Я бы предложил делать input from list, а не заставлять юзера вбивать дробные значения роста

2021-11-10 13:43 UTC, volas commented on code/modules/client/character menu/general.dm
> +					var/new_height = input(user, "Choose your character's height:\n(1.6-2.0)", "Character Height", text2num(height)) as num|null
как и тут

2021-11-10 15:07 UTC, KIBORG04 commented on code/datums/atom_huds/atom_hud.dm
> +			A.hud_list[i].appearance_flags |= KEEP_APART
Интересное решение, а что если моя картинка хочет быть KEEP_TOGETHER?

2021-11-10 15:08 UTC, DarthSidiousPalpatine commented on code/datums/atom_huds/atom_hud.dm
> +			A.hud_list[i].appearance_flags |= KEEP_APART
А что если я хочу быть во флафе амогуса в раунде?

2021-11-10 15:09 UTC, KIBORG04 commented on code/datums/atom_huds/atom_hud.dm
> +			A.hud_list[i].appearance_flags |= KEEP_APART
Никто не запрещает. Загружай флафф и играй

2021-11-10 15:10 UTC, DarthSidiousPalpatine commented on code/datums/atom_huds/atom_hud.dm
> +			A.hud_list[i].appearance_flags |= KEEP_APART
В любом случае, это важно?

2021-11-10 15:14 UTC, KIBORG04 commented on code/datums/atom_huds/atom_hud.dm
> +			A.hud_list[i].appearance_flags |= KEEP_APART
Да и конкретно это решение плохое. Тебе надо в prepare_hud ставить флаг

2021-11-10 15:17 UTC, KIBORG04 commented on code/modules/mob/living/say.dm
> +	I.appearance_flags = APPEARANCE_UI_IGNORE_ALPHA|KEEP_APART
если да, то разве не нужно пройтись по всем остальным эффектам визуальным всяким типо там к примеру ду_афтер полоски, и т.д. ... ?

2021-11-10 15:51 UTC, DarthSidiousPalpatine commented on code/modules/mob/living/say.dm
> +	I.appearance_flags = APPEARANCE_UI_IGNORE_ALPHA|KEEP_APART
Ну вот судя по тестам, не надо проходится по всем эффектам. Хз.

2021-11-10 22:07 UTC, KIBORG04 commented on code/modules/clothing/spacesuits/rig/rig.dm
> +			user.vis_contents += lamp
Так это рабочий фикс или нет? Странно что он вообще как-то ломается

2021-11-10 22:08 UTC, DarthSidiousPalpatine commented on code/modules/clothing/spacesuits/rig/rig.dm
> +			user.vis_contents += lamp
Нерабочий :/

2021-11-10 22:28 UTC, KIBORG04 commented on code/modules/clothing/spacesuits/rig/rig.dm
> +			user.vis_contents += lamp
я пофиксил.....

2021-11-10 22:49 UTC, KIBORG04 commented on code/modules/clothing/spacesuits/rig/rig.dm
> +			user.vis_contents += lamp
Хотя это скорее костыль. Зомби-карлики и шедоулинги-карлики будут с летающими глазами бегать. Я незнаю как это пофиксить и это может стать проблемой
![image](https://user-images.githubusercontent.com/26389417/141206185-14412c67-1352-45f8-b4a7-8d543bb51679.png)

2021-11-10 22:51 UTC, DarthSidiousPalpatine commented on code/modules/clothing/spacesuits/rig/rig.dm
> +			user.vis_contents += lamp
Я не уверен могут ли зомби или шедоу быть карликами. ТЕсты показали что при зомбификации или шедоуфикации они появляются обычного роста.

2021-11-10 22:54 UTC, KIBORG04 commented on code/modules/clothing/spacesuits/rig/rig.dm
> +			user.vis_contents += lamp
Смысл в том, что я щас удалил фичу. Смысл в том, что ты не знаешь будут ли в будущем предметы, с отличным плейном от хумана

2021-11-10 23:05 UTC, KIBORG04 commented on code/modules/clothing/spacesuits/rig/rig.dm
> +			user.vis_contents += lamp
https://github.com/tgstation/tgstation/blob/master/code/_onclick/hud/rendering/_render_readme.md#the-rendering-solution

Вроде как, здесь и описывается текущая твоя проблема и способ её решения, который уже сделан на тогэ

2021-11-11 05:56 UTC, DarthSidiousPalpatine commented on code/modules/clothing/spacesuits/rig/rig.dm
> +			user.vis_contents += lamp
А могу ли я, тогда, пройтись по всем оверлеям хумана и смотреть какой у оверлея плейн, если не хумановский - то накладывать на него такой же фильтр как на хумана?

2021-11-11 10:36 UTC, KIBORG04 commented on code/modules/clothing/spacesuits/rig/rig.dm
> +			user.vis_contents += lamp
Наврятли можешь, хз

2021-11-12 10:24 UTC, Sakuya-Izayoi requested changes
Не стал везде отмечать, короче, в многих местах ожидается что height это строка, в некоторых что число.

2021-11-12 10:24 UTC, Sakuya-Izayoi commented on code/modules/admin/verbs/modifyvariables.dm
> +						H.vars[variable] = var_new
Я не понимаю что здесь происходит. Вроде бы heights_list это у тебя список строк (заданных дефайнами в __DEFINES/mob.dm), а тут ты ожидаешь что у тебя инпут из этого списка это число.

2021-11-12 10:24 UTC, Sakuya-Izayoi commented on code/modules/client/character menu/general.dm
> +					var/new_height = input(user, "Choose your character's height:\n(1.6-2.0 meters)", "Character Height", height) as null|anything in heights_list
При чем тут 1.6-2.0 метра?

2021-11-12 10:24 UTC, Sakuya-Izayoi commented on code/modules/admin/verbs/massmodvar.dm
> +										H.vars[variable] = new_value
```suggestion
										H.height = new_value
```

2021-11-12 10:26 UTC, DarthSidiousPalpatine commented on code/modules/admin/verbs/modifyvariables.dm
> +						H.vars[variable] = var_new
Да забыл убрать

2021-11-12 10:26 UTC, DarthSidiousPalpatine commented on code/modules/client/character menu/general.dm
> +					var/new_height = input(user, "Choose your character's height:\n(1.6-2.0 meters)", "Character Height", height) as null|anything in heights_list
Просто инфа для игрока, какой примерно рост это.

2021-11-12 10:27 UTC, KIBORG04 commented on code/datums/atom_huds/atom_hud.dm
> +			A.hud_list[i].appearance_flags |= KEEP_APART
(все еще не в препейре_худах)

2021-11-12 11:05 UTC, DarthSidiousPalpatine commented on code/datums/atom_huds/atom_hud.dm
> +			A.hud_list[i].appearance_flags |= KEEP_APART
Да я исправляю полностью, так, что не надо будет в худах это делать. По оверлеям режу хумана и нужные оверлеи только трансформлю.

2021-11-19 17:42 UTC, DarthSidiousPalpatine commented
Фигня всё это, ничего не выходит. Я не вижу решения.

2021-11-20 08:29 UTC, DarthSidiousPalpatine commented on code/datums/atom_huds/atom_hud.dm
> +			A.hud_list[i].appearance_flags |= KEEP_APART
Я не исправил, это нормально не работает. Худы надо отрезать, да.
Но перенёс в prepare_huds

2021-11-20 08:30 UTC, DarthSidiousPalpatine commented on code/modules/clothing/spacesuits/rig/rig.dm
> +			user.vis_contents += lamp
Нет, не могу нормально. Потому как есть множество других оверлеев, по которым надо будет вручную проходиться и это жесть.

2021-11-20 08:36 UTC, DarthSidiousPalpatine commented
Ну всё, кароч, исправлено.

2021-11-21 21:33 UTC, Sakuya-Izayoi commented
линтер ругается

2021-11-24 18:03 UTC, FatFatFat1 commented
update_offset ломает оверлеи вещей потому что ты делаешь :standing = update_offset(standing, TRUE)
А надо :standing.overlays = update_offset(standing, TRUE)

2021-12-11 06:03 UTC, FatFatFat1 commented
Бот ,нука выйди и зайди нормально

2021-12-11 06:21 UTC, DarthSidiousPalpatine commented
Этот маленький манёвр будет стоить нам месяц жизни.

2021-12-11 06:38 UTC, DarthSidiousPalpatine commented
Всё Ебть. Работает.

2021-12-11 10:53 UTC, DarthSidiousPalpatine commented
Отревувьте пж. Хочется стать Дылдой

2021-12-11 10:56 UTC, volas commented on code/__DEFINES/mob.dm
> +#define	TALLEST_HEIGHT	"tallest height"
```suggestion
#define TALLEST_HEIGHT	"tallest height"
```

2021-12-11 11:00 UTC, volas commented on code/__HELPERS/icons.dm
> +/image/proc/add_filter(name, priority, list/params)
Что бы не копипастить одно и то же atom-ам и image, можно было бы перенести прок под ``/datum/`` - оно тогда унаследуется для остальных.

2021-12-11 11:02 UTC, DarthSidiousPalpatine commented on code/__HELPERS/icons.dm
> +/image/proc/add_filter(name, priority, list/params)
А я увидел что уже есть копипаст. Этих фильтров в трёх местах уже есть копии.

2021-12-11 11:04 UTC, DarthSidiousPalpatine commented on code/__HELPERS/icons.dm
> +/image/proc/add_filter(name, priority, list/params)
Типа. Можно ли на Датум вообще наложить фильтр?

2021-12-11 11:10 UTC, KIBORG04 commented on code/__HELPERS/icons.dm
> +/image/proc/add_filter(name, priority, list/params)
Нельзя на датум наложить его. Но в теории, можно уменьшить количество копипасты потом переопределив методы

2021-12-11 11:12 UTC, DarthSidiousPalpatine commented on code/__HELPERS/icons.dm
> +/image/proc/add_filter(name, priority, list/params)
Типа, всё перенести в datum, но проверять на то если istype(/image) || istype(/atom/moveable) и т.п.?

2021-12-11 11:16 UTC, KIBORG04 commented on code/__HELPERS/icons.dm
> +/image/proc/add_filter(name, priority, list/params)
Типа полиморфизм.

2021-12-11 11:16 UTC, DarthSidiousPalpatine commented on code/__HELPERS/icons.dm
> +/image/proc/add_filter(name, priority, list/params)
Не понял.

2021-12-11 11:28 UTC, volas commented on code/__HELPERS/icons.dm
> +/image/proc/add_filter(name, priority, list/params)
У атомов и имейджев можно было бы расписать путь как
/datum/atom/...
/datum/image/...

если ты перенесешь прок в /datum - он будет работать потом у обоих

2021-12-11 11:28 UTC, DarthSidiousPalpatine commented on code/__HELPERS/icons.dm
> +/image/proc/add_filter(name, priority, list/params)
Вообще не понял. Тот же копипаст, но пути другие?

2021-12-11 13:54 UTC, DarthSidiousPalpatine commented
Блин, я ничего не понял про датум и копипаст. Можно, пожалуйста, уже мерж. Оно работает, правда-правда. Честно-честно.

2021-12-11 16:04 UTC, Sakuya-Izayoi requested changes

2021-12-11 16:04 UTC, Sakuya-Izayoi commented on code/modules/clothing/clothing.dm
> +					I.pixel_x += 1
здесь происходит что-то невнятное. длиннейшие ифблоки с повторяющимися свитчами. можно было бы решить с помощью ассоциативного списка типа `критерий = смещение`. здесь почему-то везде +-1, но чуть выше есть и +-1, и +- 2. пояснительные комментарии, а лучше дефайны не помешали бы.

2021-12-11 16:04 UTC, Sakuya-Izayoi commented on code/modules/mob/living/carbon/human/human_defines.dm
> +	var/socks = 0		//Which socks the player wants.
выравнивание делается пробелами а не табами

2021-12-11 16:04 UTC, Sakuya-Izayoi commented on code/modules/mob/living/carbon/human/update_icons.dm
> +/mob/living/carbon/human/proc/update_offset(image/I, head = TRUE)
копипаст аналогичного прока у одежды.

2021-12-11 16:07 UTC, DarthSidiousPalpatine commented on code/__DEFINES/DNA.dm
> +#define DNA_UI_HEIGHT      11
Чего блять? Зачем писать в конец?

2021-12-11 16:08 UTC, DarthSidiousPalpatine commented on code/modules/mob/living/carbon/human/update_icons.dm
> +/mob/living/carbon/human/proc/update_offset(image/I, head = TRUE)
Кароч я нихера не понял из всего вышенаписанного.

2021-12-11 16:27 UTC, volas commented on code/__HELPERS/icons.dm
> +/image/proc/add_filter(name, priority, list/params)
У тебя сейчас есть два абсолютно одинаковых прока:
`` /image/proc/add_filter(name, priority, list/params) ``
и
`` /atom/proc/add_filter(name, priority, list/params) ``

ты можешь их убрать и сделать один
`` /datum/proc/add_filter(name, priority, list/params) ``
он будет один, и он будет работать и у атомов, и у имейджев. Без копипаст. Потому что оба атомы и имейджи на самом деле потомки датумов.

2021-12-11 16:45 UTC, KIBORG04 commented on code/modules/clothing/clothing.dm
> +	if(!usr || !istype(usr, /mob/living/carbon/human))
```suggestion
	if(!ishuman(usr))
```

2021-12-11 16:45 UTC, KIBORG04 commented on code/modules/clothing/clothing.dm
> +	if(!usr || !istype(usr, /mob/living/carbon/human))
Какой-то кринже прок

2021-12-11 16:46 UTC, DarthSidiousPalpatine commented on code/__DEFINES/DNA.dm
> +#define DNA_UI_HEIGHT      11
Ааа, я понял. Оно там потому что так надо. Потому что порядок такой у всех переменных внешнего вида у хумана записан. И тут всё по тому же порядку. И в префах тоже.

2021-12-11 16:47 UTC, DarthSidiousPalpatine commented on code/__DEFINES/mob.dm
> +#define TALLEST_HEIGHT	"tallest height"
Я не использую числа нигде. Меня попросили сделать текст вместо чисел вообще.
Числа просто чтобы показать какой примерно разброс.

2021-12-11 16:47 UTC, DarthSidiousPalpatine commented on code/game/dna/dna2_helpers.dm
> +			H.height = heights_list[height]
Не понял

2021-12-11 16:47 UTC, KIBORG04 commented on code/modules/mob/living/carbon/human/update_icons.dm
> +/mob/living/carbon/human/proc/update_offset(image/I, head = TRUE)
Убери копипасту тебе говорят. Да и зачем копировать метод в одежду, если ты из одежды его можешь спокойно вызывать

2021-12-11 16:48 UTC, DarthSidiousPalpatine commented on code/modules/admin/verbs/modifyvariables.dm
> +						var/var_new = input("Enter new height: \n(Human will gain this height from 1.6 to 2.0)", "Num", H.vars[variable]) as null|anything in heights_list
для юзера просто текст.

2021-12-11 16:48 UTC, DarthSidiousPalpatine commented on code/modules/client/character menu/general.dm
> +	. += 						"<br><b>Height:</b> <a href='?_src_=prefs;preference=height;task=input'>[height]</a>"
Тут лучше же?

2021-12-11 16:50 UTC, KIBORG04 commented on code/modules/clothing/clothing.dm
> +	if(!usr || !istype(usr, /mob/living/carbon/human))
Если я не ошибаюсь, он даже не вызывается ниоткуда

2021-12-11 17:31 UTC, DarthSidiousPalpatine commented on code/modules/mob/living/carbon/human/update_icons.dm
> +/mob/living/carbon/human/proc/update_offset(image/I, head = TRUE)
Убрал

2021-12-11 17:31 UTC, DarthSidiousPalpatine commented on code/modules/clothing/clothing.dm
> +	if(!usr || !istype(usr, /mob/living/carbon/human))
вызывался. Теперь его нет.

2021-12-11 17:31 UTC, DarthSidiousPalpatine commented on code/modules/mob/living/carbon/human/human_defines.dm
> +	var/socks = 0		//Which socks the player wants.
сделал пробелами

2021-12-11 17:36 UTC, DarthSidiousPalpatine commented on code/modules/clothing/clothing.dm
> +					I.pixel_x += 1
Добавил пояснения обширнейшие.

2021-12-11 17:36 UTC, DarthSidiousPalpatine commented on code/modules/clothing/clothing.dm
> +					I.pixel_x += 1
Добавил пояснения обширнейшие.

2021-12-11 17:37 UTC, DarthSidiousPalpatine commented
Всё.
Эй, куклы!
Бегите!
Ешьте меняяя!

Вот он я!

2021-12-11 17:45 UTC, Sakuya-Izayoi commented on code/modules/client/character menu/general.dm
> +	. += 						"<br><b>Height:</b> <a href='?_src_=prefs;preference=height;task=input'>[height]</a>"
почему? зачем нам тогда это разделение?

2021-12-11 17:46 UTC, DarthSidiousPalpatine commented on code/modules/client/character menu/general.dm
> +	. += 						"<br><b>Height:</b> <a href='?_src_=prefs;preference=height;task=input'>[height]</a>"
Ну потому что Рост это не совсем вид персонажа? И логично ставить рядом с возрастом, Гендером. Это типа базовый параметр?

2021-12-11 17:48 UTC, Sakuya-Izayoi commented on code/modules/client/character menu/general.dm
> +	. += 						"<br><b>Height:</b> <a href='?_src_=prefs;preference=height;task=input'>[height]</a>"
что такое базовый параметр я не понимаю и почему это не "вид персонажа" тоже. это чисто мое мнение, конечно, но я считаю что было бы лучше если бы рост выставлялся там же, где и цвет кожи тот же (название вкладки Body (то есть тело) как бы намекает)

2021-12-11 17:51 UTC, DarthSidiousPalpatine commented on code/modules/client/character menu/general.dm
> +	. += 						"<br><b>Height:</b> <a href='?_src_=prefs;preference=height;task=input'>[height]</a>"
Субъективщина у нас выходит. Я за одно имхо, вы за другое.

2021-12-11 17:55 UTC, DarthSidiousPalpatine commented on code/modules/clothing/clothing.dm
> +					I.pixel_x += 1
Достаточно надеюсь? Если да, то могу нажать resolve чтобы убрать это блок чтобы не мешал?

2021-12-11 17:58 UTC, KIBORG04 commented on code/modules/client/character menu/general.dm
> +	. += 						"<br><b>Height:</b> <a href='?_src_=prefs;preference=height;task=input'>[height]</a>"
Если кому-то интереснее мнение другого мемтейнера - мне похуй

2021-12-11 18:00 UTC, DarthSidiousPalpatine commented on code/modules/admin/verbs/modifyvariables.dm
> +						var/var_new = input("Enter new height: \n(Human will gain this height from 1.6 to 2.0)", "Num", H.vars[variable]) as null|anything in heights_list
Наверное, если я поставлю букву m в качестве "метров", то будет ок?
"Выберите рост от 1.6 - 2.0 м"

2021-12-12 04:54 UTC, DarthSidiousPalpatine commented on code/__HELPERS/icons.dm
> +/image/proc/add_filter(name, priority, list/params)
А, решено

2021-12-12 09:37 UTC, DarthSidiousPalpatine commented on code/modules/client/character menu/general.dm
> +	. += 						"<br><b>Height:</b> <a href='?_src_=prefs;preference=height;task=input'>[height]</a>"
Можно я это зарезолвлю?

2021-12-12 09:37 UTC, DarthSidiousPalpatine commented on code/modules/admin/verbs/modifyvariables.dm
> +						var/var_new = input("Enter new height: \n(Human will gain this height from 1.6 to 2.0)", "Num", H.vars[variable]) as null|anything in heights_list
И это ещё тоже зарезолвить.

2021-12-12 11:15 UTC, DarthSidiousPalpatine commented on code/game/dna/dna2_helpers.dm
> +			H.height = heights_list[height]
У дефайна же нет числового значения.

А тут используется список как и везде.

2021-12-12 16:14 UTC, KIBORG04 commented on code/datums/datum.dm
> +	A.filters = null
Сделай комментарий, что тут финт ушами и это работает на image

2021-12-12 16:15 UTC, KIBORG04 commented on code/datums/datum.dm
> +	var/atom/A = src
Сделай комментарий, что тут финт ушами и это работает на image

2021-12-12 16:15 UTC, KIBORG04 commented on code/datums/datum.dm
> +	var/atom/A = src
Сделай комментарий, что тут финт ушами и это работает на image

2021-12-12 16:16 UTC, KIBORG04 commented on code/modules/admin/verbs/massmodvar.dm
> +										H.vars[variable] = new_value
Актуально

2021-12-12 16:17 UTC, KIBORG04 commented on code/modules/admin/verbs/modifyvariables.dm
> +						var/var_new = input("Enter new height: \n(Human will gain this height from 1.6 to 2.0)", "Num", H.vars[variable]) as null|anything in heights_list
Зарезолвал, но не добавил m и не заменил H.vars[variable] на H.height

2021-12-12 16:19 UTC, KIBORG04 commented on code/modules/mob/living/carbon/human/update_icons.dm
> +/proc/human_update_offset(image/I, head = TRUE, mob/living/carbon/human/H)
```suggestion
/proc/human_update_offset(image/I, mob/living/carbon/human/H, head = TRUE)
```
аргументы по-умолчанию принято писать после обязательных. С этим и измени все `human_update_offset`

2021-12-12 16:20 UTC, KIBORG04 commented on code/modules/mob/living/carbon/human/update_icons.dm
> +	return I
Убери, пожалуйста, копипасту

2021-12-12 16:20 UTC, DarthSidiousPalpatine commented on code/modules/admin/verbs/modifyvariables.dm
> +						var/var_new = input("Enter new height: \n(Human will gain this height from 1.6 to 2.0)", "Num", H.vars[variable]) as null|anything in heights_list
Зачем

2021-12-12 16:21 UTC, DarthSidiousPalpatine commented on code/modules/mob/living/carbon/human/update_icons.dm
> +	return I
Тут нет копипасты
Обрати внимание на цифры.

2021-12-12 16:21 UTC, KIBORG04 commented on code/modules/mob/living/carbon/human/update_icons.dm
> +	return I
И почему этот метод глобальный, а не у /mob/living/carbon/human

2021-12-12 16:21 UTC, DarthSidiousPalpatine commented on code/datums/datum.dm
> +	A.filters = null
Го Тест Мерж без ревью от Гетапа

2021-12-12 16:21 UTC, DarthSidiousPalpatine commented on code/datums/datum.dm
> +	var/atom/A = src
Го Тест Мерж без ревью от Гетапа

2021-12-12 16:21 UTC, DarthSidiousPalpatine commented on code/datums/datum.dm
> +	var/atom/A = src
Го Тест Мерж без ревью от Гетапа

2021-12-12 16:22 UTC, KIBORG04 commented on code/modules/mob/living/carbon/human/update_icons.dm
> +	return I
> Тут нет копипасты
Обрати внимание на цифры.

А зато все остальное абсолютная копирка. Есть несколько способов это решить.

2021-12-12 16:22 UTC, DarthSidiousPalpatine commented on code/modules/mob/living/carbon/human/update_icons.dm
> +	return I
Реши. Я не нашёл способов. Это максимально коротко что придумал.

2021-12-12 16:28 UTC, DarthSidiousPalpatine commented on code/modules/mob/living/carbon/human/update_icons.dm
> +/proc/human_update_offset(image/I, head = TRUE, mob/living/carbon/human/H)
Сделано

2021-12-12 17:28 UTC, DarthSidiousPalpatine commented
Всё? Всё.

Все те, кто не прочь поразмять свой реквест ченджес -
Вас ждут в эту ночь - Гисев приглашает в пр!

2021-12-12 17:32 UTC, volas commented on code/game/objects/structures/mirror.dm
> +			var/new_height = input(H, "Choose your character's height:\n(1.6-2.0 meters)", "Character Height", H.height) as null|anything in heights_list
>1.6-2.0 meters

или 1-1.5 для карликов, я бы не указывал где-либо числовые значения, они не особо нужны и относительны

2021-12-12 17:32 UTC, DarthSidiousPalpatine commented on code/game/objects/structures/mirror.dm
> +			var/new_height = input(H, "Choose your character's height:\n(1.6-2.0 meters)", "Character Height", H.height) as null|anything in heights_list
Чтобы игроку было понятнее какой рост ставить.

2021-12-12 17:36 UTC, volas commented on code/game/objects/structures/mirror.dm
> +			var/new_height = input(H, "Choose your character's height:\n(1.6-2.0 meters)", "Character Height", H.height) as null|anything in heights_list
в превью увидит. По градации понятно какой нормальный а какой меньше/больше, и это лишняя специфичность которая иногда будет еще и не верной (карлики). Я вижу гетап на то же указывает

2021-12-12 17:42 UTC, volas commented on code/modules/mob/living/carbon/human/update_icons.dm
> +/mob/living/carbon/human/proc/update_height(image/I)
я тут начал писать инструкцию, потом понял что будет проще сделать тебе ПР...

2021-12-12 17:43 UTC, DarthSidiousPalpatine commented on code/modules/mob/living/carbon/human/update_icons.dm
> +/mob/living/carbon/human/proc/update_height(image/I)
Что?

2021-12-12 17:45 UTC, volas commented on code/modules/mob/living/carbon/human/update_icons.dm
> +/mob/living/carbon/human/proc/update_height(image/I)
о наименовании и контексте проков, ничего серьезного просто возня

2021-12-12 17:49 UTC, volas commented on code/modules/client/preferences_savefile.dm
> +	S["height"]                >> height
Я не вижу серьезных проблем для ТМа, кроме префов. Если в коде описание роста не будет больше меняться - можно и хоть сейчас. Но нужно иметь в виду, что на сервере будут сохранены параметры роста и в случае их переделок, нужно будет обновлять сейв файл.

2021-12-12 17:59 UTC, KIBORG04 commented on code/modules/admin/verbs/massmodvar.dm
> +										H.vars[variable] = new_value
Не то что актуально, здесь нет валдиации. Должна быть строка, а будет цифра

2021-12-12 18:01 UTC, KIBORG04 commented on code/modules/mob/living/carbon/human/update_icons.dm
> +	var/list/L = list()
```suggestion
	var/list/L
```

2021-12-12 18:02 UTC, DarthSidiousPalpatine commented on code/modules/mob/living/carbon/human/update_icons.dm
> +	var/list/L = list()
Прикинь, не помогло?

2021-12-12 18:02 UTC, KIBORG04 commented on code/modules/mob/living/carbon/human/update_icons.dm
> +			SMALLSIZE = -5
Замени SMALLSIZE на какой-то другой текстовый дефайн

2021-12-12 18:03 UTC, KIBORG04 commented on code/modules/mob/living/carbon/human/update_icons.dm
> +			SMALLSIZE = -5
Хоть свой выдумай

2021-12-12 18:06 UTC, DarthSidiousPalpatine commented
БлессРНГ, БлессРНГ

2021-12-12 18:18 UTC, DarthSidiousPalpatine commented on code/modules/client/preferences_savefile.dm
> +	S["height"]                >> height
Не особо понял что менять-то.

2021-12-13 21:58 UTC, KIBORG04 commented on code/modules/client/preferences_savefile.dm
> +	S["height"]                >> height
Не трогай эту строчку и все теперь никогда в своей жизни

2021-12-14 10:01 UTC, DarthSidiousPalpatine commented
Аксессуары починены.
Оверлеи крови не ломаются. При тестах. Не уверен как на практике.
Так и не смог решить проблему с реджувом. Что-то не так.
![image](https://user-images.githubusercontent.com/21008918/145976354-028f13ff-b083-4f84-881a-86cb2c681e68.png)

2021-12-14 11:52 UTC, DarthSidiousPalpatine commented
Нежданно-негадано пофиксил реджув, слетающие бороды и пр. Сам не понял почему, но оно теперь работает. Ура-ура.

2021-12-14 20:09 UTC, KIBORG04 commented
Ты пофиксил, что когда бьешь лежачую куклу, то атака тоже искривлена? Скорее всего анимации атаки нужно добавить КЕЕП_АПАРТ

2021-12-15 03:16 UTC, DarthSidiousPalpatine commented
> Ты пофиксил, что когда бьешь лежачую куклу, то атака тоже искривлена? Скорее всего анимации атаки нужно добавить КЕЕП_АПАРТ

Я не понимаю почему и как это связано с моим ПРом?
Сам кружок удара не шакалит. Поворот его я не контроллирую.

2021-12-15 05:02 UTC, KIBORG04 commented
Я про удары предметами. Потомучто до тебя все работало нормально

2021-12-17 19:51 UTC, KIBORG04 commented
![image](https://user-images.githubusercontent.com/26389417/146600014-75171bf2-3960-4107-9bfc-354041593616.png)

Eще один баг. Нужно сказать фразу, а потом опять начать её писать новую

2021-12-19 03:10 UTC, WatlerJe commented
Скорее не баг, а визуальная эстетика. В общем как я понимаю алгоритм берет уже собранную куклу и меняет ей размер уже в сборе, это приводит к неприятным вещам с хвостами у ящуров (возможно и с другими ксеносами, не проверял).

![image](https://user-images.githubusercontent.com/19796920/146662235-f55276f1-6e5c-42f7-ac19-c48d96b1c49a.png)
![image](https://user-images.githubusercontent.com/19796920/146662250-af263abf-abd0-4e48-b330-d07c1cb96e70.png)
![image](https://user-images.githubusercontent.com/19796920/146662276-f5350171-3672-4acc-ad30-444462d4126d.png)

Хвосты у ксеносов (кроме воксок) всегда идут отдельным слоем, по сути можно задать условие при котором меняется размер сборки тела, а хвост игнорируется.

2021-12-19 04:01 UTC, DarthSidiousPalpatine commented
> Скорее не баг, а визуальная эстетика. В общем как я понимаю алгоритм берет уже собранную куклу и меняет ей размер уже в сборе, это приводит к неприятным вещам с хвостами у ящуров (возможно и с другими ксеносами, не проверял).
> 
> ![image](https://user-images.githubusercontent.com/19796920/146662235-f55276f1-6e5c-42f7-ac19-c48d96b1c49a.png) ![image](https://user-images.githubusercontent.com/19796920/146662250-af263abf-abd0-4e48-b330-d07c1cb96e70.png) ![image](https://user-images.githubusercontent.com/19796920/146662276-f5350171-3672-4acc-ad30-444462d4126d.png)
> 
> Хвосты у ксеносов (кроме воксок) всегда идут отдельным слоем, по сути можно задать условие при котором меняется размер сборки тела, а хвост игнорируется.

Да, это возможно сделать, хвосту дать offset и он будет выпирать снизу спрайта. Не уверен насколько это будет эстетично. Но да, проблема хвостов в диагональных пикселях что плохо режутся :/

Либо, могу попробовать резать корень хвоста. В общем, изменю и пришлю сюда результаты обоих вариантов.

2021-12-19 04:02 UTC, DarthSidiousPalpatine commented
> Я про удары предметами. Потомучто до тебя все работало нормально

Я не могу понять какой с ними баг связан.

2021-12-20 13:32 UTC, KIBORG04 commented
> > Я про удары предметами. Потомучто до тебя все работало нормально
> 
> Я не могу понять какой с ними баг связан.

Анимация ДО
![image](https://user-images.githubusercontent.com/26389417/146774846-c03bc489-9cd3-414c-b71a-1708da60e68d.png)

Анимация СЕЙЧАС
![image](https://user-images.githubusercontent.com/26389417/146774874-59b744bd-ca9b-4ec3-8260-e86c757fa7ea.png)


В СЕЙЧАС скальпель повернут на 90 градусов

2021-12-20 13:48 UTC, AndroBetel commented
Да норм же, на ТГ так же.

2021-12-20 13:59 UTC, DarthSidiousPalpatine commented
> > > Я про удары предметами. Потомучто до тебя все работало нормально
> > 
> > 
> > Я не могу понять какой с ними баг связан.
> 
> Анимация ДО ![image](https://user-images.githubusercontent.com/26389417/146774846-c03bc489-9cd3-414c-b71a-1708da60e68d.png)
> 
> Анимация СЕЙЧАС ![image](https://user-images.githubusercontent.com/26389417/146774874-59b744bd-ca9b-4ec3-8260-e86c757fa7ea.png)
> 
> В СЕЙЧАС скальпель повернут на 90 градусов

Аааа, я понял. Попробую изменить как-то, хз. Нужно ли это так уж менять? Вроде, выглядит ещё более наглядной репрезентацией того, кто ударил. С какой стороны.

2021-12-20 13:59 UTC, DarthSidiousPalpatine commented
> > > Я про удары предметами. Потомучто до тебя все работало нормально
> > 
> > 
> > Я не могу понять какой с ними баг связан.
> 
> Анимация ДО ![image](https://user-images.githubusercontent.com/26389417/146774846-c03bc489-9cd3-414c-b71a-1708da60e68d.png)
> 
> Анимация СЕЙЧАС ![image](https://user-images.githubusercontent.com/26389417/146774874-59b744bd-ca9b-4ec3-8260-e86c757fa7ea.png)
> 
> В СЕЙЧАС скальпель повернут на 90 градусов

Аааа, я понял. Попробую изменить как-то, хз. Нужно ли это так уж менять? Вроде, выглядит ещё более наглядной репрезентацией того, кто ударил. С какой стороны.

2021-12-21 05:22 UTC, volas commented on code/modules/mob/living/carbon/human/update_icons.dm
> +/mob/living/carbon/human/proc/update_height(image/I)
Отписал в https://github.com/DarthSidiousPalpatine/TauCetiClassic/pull/1

2021-12-21 05:23 UTC, volas commented on code/modules/admin/verbs/modifyvariables.dm
> +						H.update_height()
отсутствует параметр-иконка

2021-12-21 05:23 UTC, volas commented on code/modules/admin/verbs/massmodvar.dm
> +										H.update_height()
отсутствует параметр-иконка

2021-12-21 06:57 UTC, DarthSidiousPalpatine commented
> > > Я про удары предметами. Потомучто до тебя все работало нормально
> > 
> > 
> > Я не могу понять какой с ними баг связан.
> 
> Анимация ДО ![image](https://user-images.githubusercontent.com/26389417/146774846-c03bc489-9cd3-414c-b71a-1708da60e68d.png)
> 
> Анимация СЕЙЧАС ![image](https://user-images.githubusercontent.com/26389417/146774874-59b744bd-ca9b-4ec3-8260-e86c757fa7ea.png)
> 
> В СЕЙЧАС скальпель повернут на 90 градусов

Так, ну я не понял почему это происходит, у меня нигде не поворачивается ничего, да и флаги не стоят, вроде. Странно это.

2021-12-21 07:02 UTC, DarthSidiousPalpatine commented on code/modules/mob/living/carbon/human/update_icons.dm
> +/mob/living/carbon/human/proc/update_height(image/I)
Перенёс прок в хумана.

2021-12-21 07:17 UTC, volas commented on code/modules/mob/living/carbon/human/update_icons.dm
> +/mob/living/carbon/human/proc/update_height(image/I)
почему было просто не смержить ПР? Ну ладно

2021-12-21 07:28 UTC, kalazus commented
> Так, ну я не понял почему это происходит, у меня нигде не поворачивается ничего, да и флаги не стоят, вроде. Странно это.

На картинке скальпель приклеился к человека как любой предмет на нём, и повернулся со всем остальным. Чё-то такое.

2021-12-21 16:08 UTC, KIBORG04 commented
Если честно, я не знаю как долго нужно мусолить эту тему и не понимать суть бага, даже не понимать как его повторить.

https://user-images.githubusercontent.com/26389417/146961621-7ea6733d-1b03-48ec-8003-ce104e41a4a3.mp4

На видео видно, что анимация удара огнетушителем движется сверху тайла вниз, а когда чел упал, то анимация слева-направо. Так после твоего ПРа эта анимация начала двигаться и по горизонтали, а не только по вертикали!!!!!

2021-12-21 16:39 UTC, DarthSidiousPalpatine commented
> Если честно, я не знаю как долго нужно мусолить эту тему и не понимать суть бага, даже не понимать как его повторить.
> 
>  iBELKlJaRh.mp4 
> На видео видно, что анимация удара огнетушителем движется сверху тайла вниз, а когда чел упал, то анимация слева-направо. Так после твоего ПРа эта анимация начала двигаться и по горизонтали, а не только по вертикали!!!!!

Фигово. Это всё из-за флага "Keep_Together" у хумана. А без этого флага слои отдельно друг от друга сидят.

2021-12-22 14:01 UTC, KIBORG04 commented
Так и напиши, что тебе лень добавить флаг КИП_АПАРТ для этой анимации.

2021-12-27 17:17 UTC, DarthSidiousPalpatine commented
И тебя вылечат

2022-01-09 09:22 UTC, DarthSidiousPalpatine commented
Э-ге-гей! Посмотрите на меня, я пофиксил все баги!

2022-01-09 09:47 UTC, DarthSidiousPalpatine commented
Го мерж, я пофиксил.

2022-01-18 19:09 UTC, DarthSidiousPalpatine commented
Ну шо, когда мерж?

2022-01-18 20:05 UTC, Haggerd commented
Когда пофиксишь фотки.

2022-01-18 20:08 UTC, KIBORG04 commented
я придумал как пофиксить фотки. Нужно короче не использовать фильтры

2022-01-18 20:42 UTC, DarthSidiousPalpatine commented
Фотки разрешили не фиксить. Давайте мерж!

2022-01-19 04:39 UTC, volas commented
Фотки вернутся после 515, новая встроенная альтернатива getflaticon должна работать с фильтрами.

2022-01-19 04:39 UTC, merged