респрайт коктейлей
TauCetiStation/TauCetiClassic pull request #8185
Opened 2021-11-09 14:33 UTC by AndroBetel

## Описание изменений
![image](https://user-images.githubusercontent.com/44546836/140942873-4511b45e-1288-40a5-bc16-39001d693e06.png)
Зареспрайчена большая часть коктейлей, шейкер и пакетики с соком.
## Почему и что этот ПР улучшит
K P A C U B O
## Авторство
DedYarick
## Чеинжлог
:cl:DedYarick
- image: Респрайт коктейлей.

2021-11-09 14:33 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2021-11-09 14:39 UTC, UDaV73rus reviewed
![image](https://user-images.githubusercontent.com/33157992/140944368-7c29be5b-1ef0-4999-a7bd-89b692297e90.png)
дубликат

2021-11-09 14:40 UTC, UDaV73rus reviewed
![image](https://user-images.githubusercontent.com/33157992/140944485-2b1fd1de-6bd2-401b-80c8-2534e915dbff.png)
не центрировано

2021-11-09 14:43 UTC, AndroBetel commented
Там анимация дымка вверх улетающего.

2021-11-09 14:46 UTC, AndroBetel commented
Дубликат исправлен.

2021-11-09 15:00 UTC, UDaV73rus requested changes
Стаканчик всё-таки нужно центрировать, дымку не сложно будет подогнать под границы
![image](https://user-images.githubusercontent.com/33157992/140948065-9be0e2b1-fe28-47e3-ac7d-290bd62b4c48.png)
Ещё вопросы по форме, если сделать верх также как ножку по форме, разве будет хуже?
Думаю стоит сделать как ножку

2021-11-09 21:12 UTC, UDaV73rus requested changes
ещё нашел что у многих стаканчиков слишком повернутая перспектива
![image](https://user-images.githubusercontent.com/33157992/141005118-cb544f3e-866c-4a3a-950f-209c47e830af.png)
У мелких стаканчиков два пикселя по бокам, а у многих больших стаканов три. Сделай везде два тогда...

2021-11-12 10:41 UTC, KIBORG04 commented
Чё с ним?

https://user-images.githubusercontent.com/26389417/141454018-ceb8cd4d-d563-45fb-be17-9b3279a733d3.mp4

2021-11-12 10:53 UTC, UDaV73rus commented
баг диффа

2021-11-13 17:53 UTC, AndroBetel commented
![image](https://user-images.githubusercontent.com/44546836/141654004-ea155de8-d187-44b0-badd-d448db298c69.png)
![image](https://user-images.githubusercontent.com/44546836/141654018-ce255068-065c-4acf-9cc6-d9d85195ac6a.png)
Изменено по заявкам.

2021-11-13 19:06 UTC, UDaV73rus approved these changes
найс кок

2021-11-13 20:19 UTC, SpaiR commented
@AndroBetel 
У тебя в списке измененных стейтов есть два, в самом конце: shaker-2 и red_meadglass-2. Какая-то ошибка или для чего-то нужны?

2021-11-13 20:20 UTC, AndroBetel commented
Походу ошибка, щас посмотрю.

2021-11-13 20:24 UTC, AndroBetel commented
Во.

2021-11-13 20:27 UTC, merged

2021-11-27 17:22 UTC, Millanister commented
![WTF](https://user-images.githubusercontent.com/62526860/143690853-048a5e4d-ea4f-4d4b-b6b1-cb2f69c2081d.png)

2021-11-30 01:54 UTC, TauKitty commented
This pull request has been mentioned on **Tau Ceti Station Forum**. There might be relevant details there:

https://forum.taucetistation.org/t/vernut-starye-napitki-golosovanie/29930/1