РП-БЛОБ
TauCetiStation/TauCetiClassic pull request #8187
Opened 2021-11-09 23:27 UTC by Sakuya-Izayoi

## Описание изменений
Теперь игрок за блоба спаунится не в своей кукле, а в мыши. Мышь спаунится где-то в трубах на станции.

## Почему и что этот ПР улучшит
Никаких больше спорных ситуаций с павергеймингом за человека-блоба.

## Авторство

## Чеинжлог
:cl: Getup1
- tweak: Блоб начинает раунд за мышь.

2021-11-09 23:27 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2021-11-09 23:55 UTC, UDaV73rus commented
дип лор блоба умерщвлен

2021-11-10 07:55 UTC, kalazus commented
Ты проверял работоспособность? У роли блоба есть проверка на карбона при разрыве.

2021-11-10 09:12 UTC, SpaiR requested changes

2021-11-10 09:12 UTC, SpaiR commented on code/game/gamemodes/factions/blob.dm
> +		M.add_ventcrawl(V)
Всю эту логику стоит вынести в отдельный метод, типа `spawn_as_mouse()` или что-то такое. Это добавит читаемости (сейчас не понятно, что она делает, пока ты не прочтешь сам код), плюс добавит общей структурированности.

2021-11-10 09:54 UTC, Akellazp commented
это как-либо повлияет на мидраунд спавн блоба?

2021-11-10 09:56 UTC, Sakuya-Izayoi commented
> это как-либо повлияет на мидраунд спавн блоба?

нет

2021-11-10 09:58 UTC, Akellazp commented
лучше уж и мидраунд блоба как мышь спавнить потому что сейчас его спавн полное говно

2021-11-10 10:06 UTC, SpaiR commented on code/game/gamemodes/factions/blob.dm
> +			CRASH("Blobmouse spawn location not found. We're screwed!")
Если спавн безуспешен, стартанет ли блоб?

2021-11-10 10:08 UTC, KIBORG04 commented on code/game/gamemodes/factions/blob.dm
> +			CRASH("Blobmouse spawn location not found. We're screwed!")
Вызов в `OnPostSetup`, стартанет.

2021-11-10 10:10 UTC, KIBORG04 commented on code/game/gamemodes/factions/blob.dm
> +	var/list/found_vents = list()
Есть метод `can_setup()`. Ты должен в нем искать венты и, мб, сохранять во фракции, а если вентов нет, то возвращать ФОЛС, тогда режим тупо отменится и будет как с малфом. А уже в онпостсетапе выбирать венту.

2021-11-10 10:17 UTC, KIBORG04 commented on code/datums/components/hivechat.dm
> +/datum/component/hivechat
Я вроде тебе писал про элементы. С ними можно было бы глобальный лист внести в неё же.

2021-11-10 10:24 UTC, KIBORG04 commented on code/__DEFINES/dcs/signals.dm
> +#define COMSIG_HIVE_SEND "hive_send"
И у меня есть вопросы, почему для очередной компоненты придумываются очередные компонентные сигналы? Почему это нельзя привязать к сигналу, который отправляется из сея, типо `COMSIG_MOB_SAY` ?

2021-11-10 10:58 UTC, Sakuya-Izayoi commented on code/__DEFINES/dcs/signals.dm
> +#define COMSIG_HIVE_SEND "hive_send"
а почему это должно привязываться к сигналу, который, например, отправляется из сея?

2021-11-10 11:14 UTC, KIBORG04 commented on code/__DEFINES/dcs/signals.dm
> +#define COMSIG_HIVE_SEND "hive_send"
В идеале, компонента ничего не должна знать о объекте, а объект о ней.

2021-11-11 18:36 UTC, SpaiR commented on code/game/gamemodes/factions/blob.dm
> +			CRASH("Blobmouse spawn location not found. We're screwed!")
Ну значит не должен, да.

2021-11-11 18:37 UTC, SpaiR commented on code/game/gamemodes/factions/blob.dm
> +			CRASH("Blobmouse spawn location not found. We're screwed!")
Хотя... Наверное так даже ок. Типа, если не заспавнило мышью, то поведение не изменится и игрок продолджит быть хуманом. Так @Sakuya-Izayoi ?

2021-11-11 18:40 UTC, Ahion commented
омг, 2000+ строк.  `taucetistation.dme` наверное лишнее?

2021-11-11 18:40 UTC, KIBORG04 commented
> омг, 2000+ строк. `taucetistation.dme` наверное лишнее?

мб что-то с кодировкой. Лучше бы сказал как пофиксить

2021-11-11 18:42 UTC, Sakuya-Izayoi commented on code/game/gamemodes/factions/blob.dm
> +			CRASH("Blobmouse spawn location not found. We're screwed!")
Там есть отдельная переменная у роли, может ли она за обычную профу спаунится или нет, то что сейчас, это явно ошибка.

2021-11-11 18:57 UTC, Ahion commented
Если б я знал, то сказал))

2021-11-11 22:20 UTC, kiVts commented
Живая мышь раундстартом:
Игроки: БЛЛЛОООООБББББ

2021-11-12 10:18 UTC, KIBORG04 commented on code/game/gamemodes/modes_gameplays/blob/overmind.dm
> +		if(isovermind(M) || isobserver(M) || istype(M, /mob/living/simple_animal/mouse/blob))
Можно убрать исоверминд и на мышь и добавить isblob дефайн.

2021-11-12 10:25 UTC, KIBORG04 commented on code/game/gamemodes/modes_gameplays/blob/blobmouse.dm
> +		if(isovermind(M) || isobserver(M) || istype(M, /mob/living/simple_animal/mouse/blob))
Можно убрать исоверминд и на мышь и добавить isblob дефайн.

2021-11-12 10:25 UTC, KIBORG04 commented on code/game/gamemodes/factions/blob.dm
> +var/global/list/blob_disallow_areas = list(
Почему глобально? Лист назван очень узконаправленно, лежит в файле с блобом, юзается только в одном месте. Зачем делать глобально?

2021-11-12 10:25 UTC, KIBORG04 commented on code/game/gamemodes/factions/blob.dm
> +					continue find_vents
ты можешь этот цикл заменить на `is_type_in_list(A, blob_disallow_areas)` и избавиться от этих ассемблеровских лейбло-циклов. Да и вообще, их использование в таких тривиальных задачах нужно запретить

2021-11-12 23:22 UTC, KIBORG04 commented on code/game/gamemodes/factions/blob.dm
> +	for(var/obj/machinery/atmospherics/components/unary/vent_pump/V in machines)
У нас есть метод get_vents(), мб стоит его юзать или как-то допилить?

2021-11-13 16:34 UTC, Sakuya-Izayoi commented on code/game/gamemodes/factions/blob.dm
> +	for(var/obj/machinery/atmospherics/components/unary/vent_pump/V in machines)
насчет допилить не знаю, он вроде делает прям то что нужно

2021-11-13 16:59 UTC, KIBORG04 commented on code/game/gamemodes/factions/blob.dm
> +	spawn_as_mouse()
Кста, этот метод назван так, будто это ролька решает за кого заспавниться, а не фракция спавнит.

2021-11-13 17:13 UTC, Sakuya-Izayoi commented on code/game/gamemodes/factions/blob.dm
> +	spawn_as_mouse()
а как назвать тогда?

2021-11-13 17:13 UTC, KIBORG04 commented on code/game/gamemodes/factions/blob.dm
> +	spawn_as_mouse()
без as, ведь так?

2021-11-13 17:15 UTC, Sakuya-Izayoi commented on code/game/gamemodes/factions/blob.dm
> +	spawn_as_mouse()
ну, я у тебя спросил потому что тебе виднее.

2021-11-13 17:15 UTC, TauKitty commented
This pull request has been mentioned on **Tau Ceti Station Forum**. There might be relevant details there:

https://forum.taucetistation.org/t/czep-komandovaniya/28751/337

2021-11-13 17:16 UTC, KIBORG04 commented on code/game/gamemodes/factions/blob.dm
> +	spawn_as_mouse()
не считайте меня за тирана, чье мнение невозможно оспорить

2021-11-13 20:14 UTC, SpaiR approved these changes

2021-11-13 20:14 UTC, KIBORG04 commented
Да можно было бы сразу мерж

2021-11-13 21:47 UTC, KIBORG04 commented
стоп, что чё, я больше не смогу отыгрывать мирно-блоба с начала раунда? Ужс

2021-11-15 19:33 UTC, merged