Pull robotic beaker inside if you go too far, no more duplicate beakers
TauCetiStation/TauCetiClassic pull request #8200
Opened 2021-11-12 18:24 UTC by FoLZer

## Описание изменений
Ранее играя за медицинского/"учёного" борга можно было оставить свой "стакан" в химическом диспенсере и уйти, при этом стакан можно было далее ставить в другие машины и он магическим образом телепортировался в них (А если нажать кнопку eject в том же диспенсере то он ещё и на полу появится). Теперь если отойти от любой машинерии где лежит ваш интегрированный стакан - он автоматически прилетит к вам обратно и не останется в машине. Также более нельзя поставить стакан в более чем 1 машину.

Также добавил 2 итема инженерному грипперу для постройки светового пола, а то было страшно без такой возможности.
fix #514 (кто-то решил пофиксить ишью 4-х летней давности...)
## Почему и что этот ПР улучшит
Никаких больше багов с химическими стаканами у боргов.
## Авторство
Me
## Чеинжлог
:cl:
 - bugfix: Борги более не смогут магически телепортировать/дублицировать/блокировать химические стаканы путём манипуляций с химическим диспенсером и другим оборудованием
 - tweak: Добавлена возможность строить световой пол боргам

2021-11-12 18:24 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2021-11-12 18:25 UTC, FoLZer commented
Все комментарии и дополнения приветствуются, я знаю что мой код не идеален.

2021-11-12 18:38 UTC, Sakuya-Izayoi commented
в чем прикол этого отдельного типа бикера? почему бы просто не сделать робо-руку которая может поднимать бикеры и в случае когда она держит бикер будет вести себя собственно как бикер?

2021-11-12 18:42 UTC, Sakuya-Izayoi commented on code/game/objects/items.dm
> +	return src
```suggestion
	return src

```

2021-11-12 18:42 UTC, Sakuya-Izayoi commented on code/game/machinery/machinery.dm
> +	return
```suggestion
	return

```

2021-11-12 18:45 UTC, FoLZer commented
> в чем прикол этого отдельного типа бикера? почему бы просто не сделать робо-руку которая может поднимать бикеры и в случае когда она держит бикер будет вести себя собственно как бикер?

Потому что если ты когда-нибудь играл на мед борге и пытался в химию - то понял бы что это чертовски не удобно, никто не будет играть на них либо на запросы что-нибудь приготовить будут игнорировать

2021-11-12 22:34 UTC, KIBORG04 commented on code/game/objects/items.dm
> +	return src
Совершенно не нужный механ итемов

2021-11-12 22:36 UTC, FoLZer commented on code/game/objects/items.dm
> +	return src
До него был использован "баг на SEND_SIGNAL", я не думаю что баг в проке это лучше чем такой механ.

2021-11-12 22:41 UTC, FoLZer commented on code/game/objects/items.dm
> +	return src
Конечно, если есть идеи как сделать лучше то предложите, пожалуйста.

2021-11-12 22:43 UTC, KIBORG04 commented on code/modules/reagents/reagent_containers/glass.dm
> +/obj/item/weapon/reagent_containers/glass/beaker/integrated
(тыкаю в рандомное место)

Все очень странно и непонятно вообще зачем. Какие-то копипасты, какие-то странные методы, почем бикер хранит место где он лежит. Почему разное поведение в зависимости от места нахождения этого бикера? `loc.loc`.  Я уверен, что это все можно реализовать без миллонов `if(istype(beaker,/obj/item/weapon/reagent_containers/glass/beaker/integrated))`

2021-11-12 22:46 UTC, KIBORG04 commented on code/game/objects/items.dm
> +	return src
Я не особо понимаю почему это сделано для гиппера через метод, а не простым истайпом. Но, ладно, если подумать, то может где-то еще пригодиться. Но, мб, нужно как-то иначе обозвать его.

2021-11-12 22:47 UTC, FoLZer commented on code/modules/reagents/reagent_containers/glass.dm
> +/obj/item/weapon/reagent_containers/glass/beaker/integrated
loc.loc тут только из-за того что когда я тестил расстояние от модуля(в котором и хранится бикер изначально) не рассчитывается правильно, когда поменял на loc.loc(сам робот) - всё заработало.
Насчёт if(istype) сейчас подумаю что можно сделать, но forceMove'ы всё равно нужно оставить будет

2021-11-12 22:49 UTC, KIBORG04 commented on code/modules/reagents/reagent_containers/glass.dm
> +/obj/item/weapon/reagent_containers/glass/beaker/integrated
Безусловно, форсмув нужен. А вот `когда поменял на loc.loc(сам робот) - всё заработало` не внушает доверия. Тип, бикер в идеале не должен иметь вот такой вот реф.

2021-11-12 22:50 UTC, FoLZer commented on code/modules/reagents/reagent_containers/glass.dm
> +/obj/item/weapon/reagent_containers/glass/beaker/integrated
Окей, без проблем, сейчас заодно с istype'ми проверю ещё раз, может я где-то до этого оплошал. Отпишу как всё сделаю

2021-11-12 23:04 UTC, FoLZer commented on code/modules/reagents/reagent_containers/glass.dm
> +/obj/item/weapon/reagent_containers/glass/beaker/integrated
![image](https://user-images.githubusercontent.com/65248062/141593460-ab2e0c25-d5ad-4d4a-a9f1-2f0cbc54400d.png)
Вот хоть убей но не хочет он считать правильно если оставить только один loc

2021-11-12 23:05 UTC, KIBORG04 commented on code/modules/reagents/reagent_containers/glass.dm
> +/obj/item/weapon/reagent_containers/glass/beaker/integrated
Попробуй удалить переменную integrated_into и без нее сделать

2021-11-12 23:06 UTC, FoLZer commented on code/modules/reagents/reagent_containers/glass.dm
> +/obj/item/weapon/reagent_containers/glass/beaker/integrated
Через initial(loc) имеется ввиду?

2021-11-12 23:08 UTC, KIBORG04 commented on code/modules/reagents/reagent_containers/glass.dm
> +/obj/item/weapon/reagent_containers/glass/beaker/integrated
Нет. Скажи лучше, почему у тебя разный механ при нахождение бикера в модуле и где-то еще.
![image](https://user-images.githubusercontent.com/26389417/141593757-665a6d59-a6e3-4542-817b-f7a4576f0c0a.png)

2021-11-12 23:10 UTC, FoLZer commented on code/modules/reagents/reagent_containers/glass.dm
> +/obj/item/weapon/reagent_containers/glass/beaker/integrated
loc в /obj/item/weapon/robot_module = /mob/living/silicon/robot
вот и ответ

2021-11-12 23:10 UTC, KIBORG04 commented on code/modules/reagents/reagent_containers/glass.dm
> +/obj/item/weapon/reagent_containers/glass/beaker/integrated
По какой причине оно будет отличаться?

2021-11-12 23:14 UTC, FoLZer commented on code/modules/reagents/reagent_containers/glass.dm
> +/obj/item/weapon/reagent_containers/glass/beaker/integrated
Типо если бикер изначально будет выдан не внутри модуля, а внутри хумана, как пример, то там будет достаточно одного loc чтобы получить /mob, если же он выдаётся в модуле то требуется 2 до /mob. Хотя опять же есть корявый вариант убрать этот механ поставив loc вот тут
![image](https://user-images.githubusercontent.com/65248062/141594096-589ad46a-10b9-461d-9f27-1944a1c7dddd.png)

2021-11-12 23:16 UTC, KIBORG04 commented on code/modules/reagents/reagent_containers/glass.dm
> +/obj/item/weapon/reagent_containers/glass/beaker/integrated
А зачем выдавать бикер в хумана то? Хуман поиедее вообще не должен получать к нему доступ.

2021-11-12 23:17 UTC, FoLZer commented on code/modules/reagents/reagent_containers/glass.dm
> +/obj/item/weapon/reagent_containers/glass/beaker/integrated
Стоп, я сейчас заметил кое-что. Видимо всё намного проще чем я думал

2021-11-12 23:21 UTC, FoLZer commented on code/modules/reagents/reagent_containers/glass.dm
> +/obj/item/weapon/reagent_containers/glass/beaker/integrated
> А зачем выдавать бикер в хумана то? Хуман поиедее вообще не должен получать к нему доступ.

То есть мне лучше вообще выпилить всё что не связано с боргами и не париться с сигналами хумана?

2021-11-12 23:23 UTC, KIBORG04 commented on code/modules/reagents/reagent_containers/glass.dm
> +/obj/item/weapon/reagent_containers/glass/beaker/integrated
В этом же и смысл, что ты пытаешься всеми способами не дать просочиться бикеру в мир людей

2021-11-12 23:24 UTC, FoLZer commented on code/modules/reagents/reagent_containers/glass.dm
> +/obj/item/weapon/reagent_containers/glass/beaker/integrated
Ладно, окей, я понял. Подумал слишком наперёд, так сказать. Сейчас проверяю последний раз и пушу

2021-11-13 00:35 UTC, FoLZer commented on code/modules/reagents/reagent_containers/glass.dm
> +/obj/item/weapon/reagent_containers/glass/beaker/integrated
Нашёл проблему в коде, было очень противно её чинить. В общем пока так

2021-11-13 21:29 UTC, KIBORG04 commented on code/modules/reagents/reagent_containers/glass.dm
> +	UnregisterSignal(integrated_into, list(COMSIG_HAND_DROP_ITEM,COMSIG_MOVABLE_MOVED))
```suggestion
	UnregisterSignal(integrated_into, list(COMSIG_HAND_DROP_ITEM, COMSIG_MOVABLE_MOVED))
```

2021-11-13 21:32 UTC, KIBORG04 commented on code/modules/reagents/reagent_containers/glass.dm
> +	if(dist < 0 || dist > 1)
```suggestion
	if(0 > dist || dist > 1)
```
Более в математическом виде записано и вроде легче читается

2021-11-13 21:33 UTC, KIBORG04 commented on code/modules/reagents/reagent_containers/glass.dm
> +	if(istype(loc,/obj/machinery))
```suggestion
	if(istype(loc, /obj/machinery))
```

2021-11-13 21:34 UTC, KIBORG04 commented on code/modules/reagents/Chemistry-Machinery.dm
> +		loaded_pill_bottle.loc = src.loc
```suggestion
		loaded_pill_bottle.forceMove(loc)
```

2021-11-13 21:38 UTC, KIBORG04 commented on code/modules/reagents/reagent_containers/glass.dm
> +	RegisterSignal(src, COMSIG_HAND_DROP_ITEM, .proc/drop_item)
Меня не перестает покидать ощущение, что эта логика должна быть у борга,  а не у бикера

2021-11-13 21:39 UTC, KIBORG04 commented on code/modules/mob/living/silicon/robot/inventory.dm
> +		if(istype(module_state_1, /obj/item))
А это ли случайно не заставит бикер хардом отправиться в борга без ежектов у машинерии?

2021-11-13 21:45 UTC, FoLZer commented on code/modules/mob/living/silicon/robot/inventory.dm
> +		if(istype(module_state_1, /obj/item))
В этом и смысл, раньше если выбрать бикер, вставить его в машинерию и далее нажать Store, то бикер раздвоится. Из такой ситуации 2 выхода : форс ремувнуть из машинерии и пихнуть в борга или же заблокировать Store с активным бикером. Я считаю что лучше первый вариант который и сделан сейчас

2021-11-13 21:59 UTC, KIBORG04 commented on code/modules/mob/living/silicon/robot/inventory.dm
> +		if(istype(module_state_1, /obj/item))
А разве тот страшный механ на сигналах не должен это хендлить?

2021-11-13 22:33 UTC, FoLZer commented on code/modules/mob/living/silicon/robot/inventory.dm
> +		if(istype(module_state_1, /obj/item))
Возможно, сейчас гляну можно ли реально к сигналам подключить

2021-11-14 12:47 UTC, KIBORG04 commented on code/modules/reagents/reagent_containers/glass.dm
> +	RegisterSignal(src, COMSIG_HAND_DROP_ITEM, .proc/drop_item)
Мне кажется, ВЕСЬ механ отсюда можно перенести в remove_from_mob(). Чтобы это работало не только на бикер, но и на остальные штуки

2021-11-14 14:17 UTC, FoLZer commented on code/modules/reagents/reagent_containers/glass.dm
> +	RegisterSignal(src, COMSIG_HAND_DROP_ITEM, .proc/drop_item)
С перемещением всего механа будут проблема в производительности: сейчас при выбрасывании этого бикера и перемещении борга происходит вызов всего одного прока с проверкой, а если выносить его, то проверка будет на каждом предмете каждый раз когда борг двигается с хотя бы 1 предметом вне модуля. Да и если добавлять какой-то промежуточный лист итемов которые будут проверятся то на это уйдёт ещё больше логики и правок.

2021-11-15 20:31 UTC, SpaiR requested changes

2021-11-15 20:31 UTC, SpaiR commented on code/game/machinery/machinery.dm
> +/obj/machinery/proc/Eject(move = TRUE)
Почему все методы с маленькой буквы, а этот с большой?
И eject чего? Если содержимого, то есть `dropContents()` который это и так делает.
Назначение `move` аргумента тоже не понятно.

Создавай методы на том уровне, где они нужны, речь идет об эжекте бикера. В этом направлении думать и нужно. Например, как-то объединить механ или еще как пересмотреть. Делать общий на весь класс машинерии метод, который, по сути, нужен в паре типах и для похожих веще - странное решение.

2021-11-15 20:31 UTC, SpaiR commented on code/game/objects/items.dm
> +/obj/item/proc/get_alternate_item()
Что такое "alternate"? Название метода не дает описания его действия. Добавь, пожаолуйста, коммент с более детальным описанием метода в контексте вариантов его использования.

2021-11-15 20:31 UTC, SpaiR commented on code/modules/mob/living/silicon/robot/inventory.dm
> +			return
Метод выше и ниже что-то возвращает. Поэтому здесь тоже должно быть что-то. Например `null`.

2021-11-15 20:31 UTC, SpaiR commented on code/modules/reagents/reagent_containers/glass.dm
> +/obj/item/weapon/reagent_containers/glass/beaker/integrated/Moved(atom/OldLoc, Dir)
Не буду проходить по каждому методу, но как пример неконсистентного нейминга, тут у тебя `OldLoc`, выше `oldLoc`, а еще выше `loc`.

2021-11-15 20:31 UTC, SpaiR commented on code/modules/reagents/reagent_containers/glass.dm
> +/obj/item/weapon/reagent_containers/glass/beaker/integrated/proc/pull_back(loc = src.loc, move = TRUE)
`loc = src.loc` 
loc - перменная на уровне объектов. не нужно её прятать за аргументом.

2021-11-16 11:38 UTC, Rahmanio commented
Вообще это проблема не только бикеров, но и всех предметов боргов. Например GPS любого борга можно засунуть в консоль теленауки и человек может спокойно подобрать этот GPS.

2021-11-18 19:27 UTC, FoLZer commented
> Вообще это проблема не только бикеров, но и всех предметов боргов. Например GPS любого борга можно засунуть в консоль теленауки и человек может спокойно подобрать этот GPS. Из-за чего могут быть визуальные баги, рантаймы и тд.

К этому ПРу это отношение иметь не будет, однако, возьму на заметку. Может, в следующем займусь.

2021-11-18 19:41 UTC, FoLZer commented on code/game/objects/items.dm
> +/obj/item/proc/get_alternate_item()
Добавил коммент с описанием функции. Новое название не придумал, но думаю с комментом понятно.

2021-11-18 19:43 UTC, FoLZer commented on code/game/machinery/machinery.dm
> +/obj/machinery/proc/Eject(move = TRUE)
Переименовал на /eject_item с аргументом /obj/item/I, теперь функция просто будет хэндлить предметы которые при ежекте должны делать что-то кроме простого выпадения. Также добавил коммент с пояснением функции. dropContents() тут бы не сработал - выпадение требуется только на 1 предмет и не больше. Пока на /eject_item переписал только функционал химической машинерии но лучше если переписать всю машинерию на эту функцию.

2021-11-18 19:44 UTC, FoLZer commented on code/modules/reagents/reagent_containers/glass.dm
> +	RegisterSignal(src, COMSIG_HAND_DROP_ITEM, .proc/drop_item)
Всё перенесено. Более не актуально.

2021-11-18 21:36 UTC, KIBORG04 commented on code/modules/research/destructive_analyzer.dm
> +		//loaded_item.forceMove(loc)
Если комментарий не нужен, то убери его

2021-11-18 21:37 UTC, KIBORG04 commented on code/game/machinery/machinery.dm
> +	return I.forceMove(target)
```suggestion
	return I.forceMove(target)

```

2021-11-18 21:39 UTC, KIBORG04 commented on code/modules/mob/living/silicon/robot/robot_modules.dm
> +/obj/item/weapon/robot_module/proc/silicon_on_move()
А зачем этот механ, если уже есть
![image](https://user-images.githubusercontent.com/26389417/142500972-1fae3208-0f27-4625-b71e-8526435e66fe.png)

2021-11-19 03:31 UTC, FoLZer commented on code/modules/mob/living/silicon/robot/robot_modules.dm
> +/obj/item/weapon/robot_module/proc/silicon_on_move()
Это две разные вещи, одно для передвижения предмета, выброшенного из борга; другое для самого борга для проверки дистанций с вещами его модуля.

2021-11-21 21:32 UTC, Sakuya-Izayoi commented on code/game/machinery/machinery.dm
> +/obj/machinery/proc/eject_item(obj/item/I, atom/target)
У мобов есть аналогичный прок drop_from_inventory (или remove_from_mob, хз), почему бы его не обобщить до atom/movable (или может быть просто atom)?

2021-11-21 21:32 UTC, Sakuya-Izayoi commented on code/modules/reagents/Chemistry-Machinery.dm
> +			default_deconstruction_crowbar(I)
default_deconstruction_crowbar уже чекает истайп

2021-11-22 07:22 UTC, FoLZer commented on code/game/machinery/machinery.dm
> +/obj/machinery/proc/eject_item(obj/item/I, atom/target)
Меня уже за это прибить хотят, не думаю что стоит еще и обобщать пока-что

2021-11-22 07:22 UTC, FoLZer commented on code/modules/reagents/Chemistry-Machinery.dm
> +			default_deconstruction_crowbar(I)
Я не меня исходный код эжекта, но уберу как смогу

2022-01-01 23:20 UTC, closed without merging