[WiP] Замена "магических циферок" на дефайны
TauCetiStation/TauCetiClassic pull request #8201
Opened 2021-11-12 21:45 UTC by FoLZer

## Описание изменений
Выполняем #6742
## Почему и что этот ПР улучшит
Красивее код, наверное.
## Авторство

## Чеинжлог

2021-11-12 21:45 UTC, TauKitty commented
###### Changelog status: :radio_button: No changelog

2021-11-12 22:27 UTC, KIBORG04 commented
Каким методом ты понимаешь, что нужен ТРУ, а не 1 ? Ты че, сам все просматриваешь?

2021-11-12 22:31 UTC, FoLZer commented
> Каким методом ты понимаешь, что нужен ТРУ, а не 1 ? Ты че, сам все просматриваешь?

Да, я сейчас просматриваю каждый прок где есть return

2021-11-13 00:11 UTC, KIBORG04 commented on code/modules/projectiles/targeting.dm
> +	if(can_fire())
опа, незадокументированное изменение

2021-11-13 00:30 UTC, FoLZer commented on code/modules/projectiles/targeting.dm
> +	if(can_fire())
Реально, из-за этого сразу все сервера взломаю

2021-11-13 20:57 UTC, SpaiR commented
Это тот тип изменений, которые если и делать, то делать кусками.
1. Сейчас это невозможно вручную проверить и поэтому остается уповать на силу скрипта. Оно, конечно, ничего не сломает. `TRUE`/`FALSE` - это 1 и 0 соответственно в любом случае. Но полезности от таких изменений тоже будет не много.
2. Можно обратить внимание, что не прошло и суток, а у тебя уже куча мержконфликтов, которые, опять же, хз как ты будешь разрешивать.

Приведение к код конвешену - круто! Но конкретно подобного рода правки просто нет смысла не дробить на какие-то куски. Запускай свой скрипт на каком-то модуле/модулях, делай ручной чек диффа, если требуется что-то довикивай. Для кодбазы в целом нет никакой разницы, будет все приведено к конвешену сейчас, либо через N-ное количество ПРов. А так, штука полезная 👍

2021-11-13 20:59 UTC, KIBORG04 commented
(на тг 350+ файлов челики на ревьюверах отсмотрели и даже че-то фиксили)

2021-11-13 21:06 UTC, FoLZer commented
Ничего, мне резолвить конфликты не трудно по сравнению со всем остальным, выдержу. На счёт того где меняется - я сначала смотрю за что отвечает сам прок и как он применяется позже и только потом ставлю, так что скорее всего там всё верно. Работы ещё куча так что всё впереди.

2021-11-13 21:08 UTC, KIBORG04 commented
Хотя бы раздели свои пункты на разные Пры.

![image](https://user-images.githubusercontent.com/26389417/141659096-98fa5157-f044-4776-a689-88ac6c8b86a0.png)

2021-11-13 21:08 UTC, FoLZer commented
Окей, сделаем. Тогда и разделю когда доделаю с TRUE/FALSE.

2021-11-19 14:30 UTC, KIBORG04 commented on code/__DEFINES/misc.dm
> +#define HEAL_EFFECTIVENESS_MAX 1
```suggestion
#define HEAL_EFFECTIVENESS_MAX 1

```

2021-11-19 14:35 UTC, KIBORG04 commented on code/__HELPERS/icon_smoothing.dm
> +	SSicon_smooth.can_fire = TRUE
аааа тут не только ретурны

2021-11-19 14:36 UTC, KIBORG04 commented on code/_onclick/hud/human.dm
> +	lingchemdisplay.invisibility = INVISIBILITY_ABSTRACT
за шо

2021-11-19 14:39 UTC, KIBORG04 commented on code/controllers/subsystem/voting/poll.dm
> +#define MINIMUM_VOTE_LIFETIME 15 MINUTES
Замена "магических циферок"(0,1) на дефайны(FALSE,TRUE)

2021-11-19 14:43 UTC, KIBORG04 commented on code/controllers/subsystem.dm
> +	if(edited_var == "can_fire" && can_fire)
Ты еще и пробелмы между ифкой и скобкой трогал....

2021-11-19 14:45 UTC, FoLZer commented on code/controllers/subsystem.dm
> +	if(edited_var == "can_fire" && can_fire)
Да боже, изначально это было далеко не только про булы, там много такого.

2021-11-19 14:52 UTC, KIBORG04 commented on code/controllers/subsystem.dm
> +	if(edited_var == "can_fire" && can_fire)
да падажди. Поставь везде где надо перенос строки в файле

2021-11-19 14:54 UTC, KIBORG04 reviewed
![image](https://user-images.githubusercontent.com/26389417/142642697-2501c513-e343-45a6-91cd-ea411d85867b.png)

После стольких файлов и ~25 минут времени я понял, что не осилю.

2021-11-19 14:56 UTC, FoLZer commented on code/controllers/subsystem.dm
> +	if(edited_var == "can_fire" && can_fire)
Оки

2021-11-19 14:57 UTC, FoLZer commented
У меня на всё это ушло 5 дней примерно, так что удачи всё это осилить за один пресест.

2021-11-20 11:58 UTC, KIBORG04 commented
Купи мне второй монитор, быстрее отревуваю

2021-11-20 12:01 UTC, FoLZer commented
Купи мне для начала

2021-11-20 13:20 UTC, volas requested changes
В данном варианте это тяжело и затратно ревьювить, просьба разбить на более мелкие изменения.
Можно по модулям/папкам, начав с проков в `` code/__HELPERS``, к примеру. Или по объему, где нибудь не больше 100 строк, что бы можно было за пару минут проверить и убедиться что всё ок и сразу смержить. 
Иначе это зависнет в бесконечном процессе ревью и мерж конфликтов.

2021-11-20 13:33 UTC, FoLZer commented
То есть предлагаете сейчас этот закрыть и разбить этот ПР на много маленьких? Если брать по 100 строк то 30 ПРов выйдет, не многовато-ли?

2021-11-20 13:43 UTC, volas commented
Если по пулл реквесту в день, как раз до нового года можно управиться. Не обязательно именно 100 строк, но что бы это ревьювер мог проглотить и не подавиться. 5 дней на ревью текущего варианта никто потратить не сможет. И тут нету каких-то функциональных изменений, что бы это того стоило.

2021-11-20 13:45 UTC, FoLZer commented
Ладно, так и сделаю тогда. Только по 100 это уже совсем будет, хотя посмотрим как будет выглядеть это.

2021-11-20 13:45 UTC, closed without merging