Новые напитки. / New Drinks.
TauCetiStation/TauCetiClassic pull request #8212
Opened 2021-11-14 14:52 UTC by DeltaXForce3000

## Описание изменений
Добавляет новые реакции для приготовления напитков барменом.
1. Sex On The Beach
2. Mojito
3. Strongman's Drink
4. Sangria
5. The Blue Lagoone 
6. Bloody Kuds
7. Rainbow Punch

Спрайты.
![image](https://user-images.githubusercontent.com/63353157/141685242-8c767918-17d9-41c0-972c-31b54de9223f.png)
Sex On The Beach - Screwdriver (2), Melon Liquor (2), Ice

![image](https://user-images.githubusercontent.com/63353157/141685361-cc5194e9-0af9-4d3b-9a54-cd8c0d663f7b.png)
Mojito - Deadrum (2), Lime Juice (2), Sodawater

![image](https://user-images.githubusercontent.com/63353157/141685614-61cfb1e8-a89a-44cb-bbfc-33303c9b703f.png)
Strongman's Drink - Whiskey Cola (2), Tramadol (2), The Doctor's Delight

![image](https://user-images.githubusercontent.com/63353157/141685773-0fb60a53-b311-47da-b0b6-f2881cd68f52.png)
Sangria - Wine (2), Orange Juice, Lime Juice, Sugar

![image](https://user-images.githubusercontent.com/63353157/141685872-13a8c741-bfc7-4a62-a576-d9381362cd82.png)
The Blue Lagoone - Vodka (2), Lime Juice, Sodawater, Ice

![image](https://user-images.githubusercontent.com/63353157/141685973-62a76ec6-5c7b-4cb6-b038-2f3de2f8fd6f.png)
Bloody Kuds - Vodka (2) Deadrum (2) Tomato Juice

![image](https://user-images.githubusercontent.com/63353157/141686149-a7b9be4b-9144-4d72-91cc-757efffcc631.png)
Rainbow Punch - Kira Special (2) Tequilla Sunrise (2) Ice

## Почему и что этот ПР улучшит

## Авторство
DeltaXForce3000
## Чеинжлог
:cl: DeltaXForce3000
- rscad: Добавлены новые рецепты для приготовления напитков.

2021-11-14 14:52 UTC, TauKitty commented
###### Changelog status: :x: Invalid changelog classes (rscad)

2021-11-14 14:54 UTC, KIBORG04 commented on code/modules/reagents/reagent_types/Chemistry-Drinks.dm
> +	taste_message = "alcohol and you feel smell lime"
```suggestion
	taste_message = "alcohol and you feel smell lime"

```

2021-11-14 14:55 UTC, KIBORG04 commented on code/modules/reagents/reagent_types/Chemistry-Drinks.dm
> -/datum/reagent/consumable/lean
куда лин украл?

2021-11-14 14:55 UTC, KIBORG04 commented on code/modules/reagents/Chemistry-Recipes.dm
> -/datum/chemical_reaction/lean
куда лин украл?

2021-11-14 14:55 UTC, DeltaXForce3000 commented on code/modules/reagents/Chemistry-Recipes.dm
> -/datum/chemical_reaction/lean
не крал вроде бы сейчас гляну

2021-11-14 14:56 UTC, Sakuya-Izayoi commented
для голубой лагуны ирл нужен блю кюрасао, у нас блю кюрасао есть, почему бы не использовать его

2021-11-14 14:57 UTC, Sakuya-Izayoi commented on code/modules/reagents/reagent_types/Chemistry-Drinks.dm
> +	taste_message = "alcohol and you feel smell lime"
эта строчка в игре будет выглядеть очень некрасиво. Представь что тебе в чат напишет

You can taste alcohol and you feel smell lime, bitterness and sweetness. (если ты с чем-нибудь смешаешь этот реагент)

2021-11-14 15:02 UTC, KIBORG04 commented
![image](https://user-images.githubusercontent.com/26389417/141686609-e335a6b3-ba6b-4866-b043-64a90d491425.png)

Этого тоже не должно быть. Короче ты на старом билде рисовал и все сломал

2021-11-14 15:29 UTC, DeltaXForce3000 commented
Поменяю билд, поправлю сейчас все. Кюрасао внес, забыл внести, сам же хотел.

2021-11-14 17:00 UTC, Akellazp commented
sex?!

2021-11-14 17:31 UTC, Zmey25 commented on code/modules/reagents/Chemistry-Recipes.dm
> -/datum/chemical_reaction/lean
Там ему и место

2021-11-15 13:15 UTC, UDaV73rus requested changes
не понятный белый пиксель
![image](https://user-images.githubusercontent.com/33157992/141788025-58dee543-cdef-41c9-87f0-70bce8b723d4.png)

Анимация радужного дерганная и эпилептично быстрая

2021-11-15 21:12 UTC, DeltaXForce3000 commented
Поправил спрайты, радужный тяжеловато почему - то редачить. Вроде не токсичный и с нормальной скоростью теперь, могу меньше сделать. Сделал все чтобы она не дергалась. Пофиксил ножку и убрал пиксель.

2021-11-15 21:51 UTC, UDaV73rus requested changes
![image](https://user-images.githubusercontent.com/33157992/141858691-50641ff8-0153-471f-aae4-5716f72d1cb5.png)
чернота внутри стаканов
радужная анимация всё ещё прерывается

2021-11-15 23:36 UTC, DeltaXForce3000 commented
> ![image](https://user-images.githubusercontent.com/33157992/141858691-50641ff8-0153-471f-aae4-5716f72d1cb5.png) чернота внутри стаканов радужная анимация всё ещё прерывается

По спрайту новых стаканов делал. Так и должно же быть

2021-11-15 23:48 UTC, UDaV73rus commented
> По спрайту новых стаканов делал. Так и должно же быть

![image](https://user-images.githubusercontent.com/33157992/141870540-8ac7deff-ab00-43a4-bc02-f38f402ef8c7.png)

2021-11-16 00:11 UTC, DeltaXForce3000 commented
> > По спрайту новых стаканов делал. Так и должно же быть
> 
> ![image](https://user-images.githubusercontent.com/33157992/141870540-8ac7deff-ab00-43a4-bc02-f38f402ef8c7.png)

Пофиксил спрайт мохито, и радужного удара анимацию, вроде бы ровно.

2021-11-16 09:23 UTC, UDaV73rus commented
убери черные полосы.......
![image](https://user-images.githubusercontent.com/33157992/141957918-67c76834-08b4-4865-8241-2a8d32e69106.png)
и у радужного сгладил низ, а верх остался дергаться

2021-11-16 14:44 UTC, DeltaXForce3000 commented
> убери черные полосы....... ![image](https://user-images.githubusercontent.com/33157992/141957918-67c76834-08b4-4865-8241-2a8d32e69106.png) и у радужного сгладил низ, а верх остался дергаться

Какие полосы

2021-11-16 19:49 UTC, DeltaXForce3000 commented
Поправлены спрайты, где были черные полосы, и постарался сделать более нормальным радужный коктейль.

2021-11-18 03:18 UTC, DeltaXForce3000 commented on code/modules/reagents/reagent_types/Chemistry-Drinks.dm
> +	taste_message = "alcohol and you feel smell lime"
Переделал эти строчки все

2021-11-18 03:38 UTC, DeltaXForce3000 commented
Других проблем не вижу, если они есть - жду. Пока вроде все доделал. Надписи в чате сделал, респрайтнул некоторые, не дергается анимация сильно думаю.

2021-11-18 04:58 UTC, TauKitty commented
This pull request has been mentioned on **Tau Ceti Station Forum**. There might be relevant details there:

https://forum.taucetistation.org/t/novoe-buhlo/29604/1

2021-11-19 01:20 UTC, Sakuya-Izayoi requested changes

2021-11-19 01:20 UTC, Sakuya-Izayoi commented on code/modules/reagents/reagent_types/Chemistry-Drinks.dm
> +datum/reagent/consumable/drink
```suggestion
/datum/reagent/consumable/drink
```

2021-11-19 15:45 UTC, UDaV73rus approved these changes

2021-11-20 12:12 UTC, KIBORG04 commented on code/modules/reagents/reagent_types/Chemistry-Drinks.dm
> +	restrict_species = list(IPC, DIONA)
лол что ипц могут пить?

2021-11-20 12:17 UTC, merged