Изменение оружейной и создание прохода в теха под карцером
TauCetiStation/TauCetiClassic pull request #8213
Opened 2021-11-14 17:35 UTC by Stolaire

## Описание изменений

1. Изменения оружейки

Изменения карты:
![1](https://user-images.githubusercontent.com/17797554/141683883-2c82aa4d-4905-45bd-935e-31628f2cc5c1.png)
Изменения содержимого верхней оружейки:
- Удалён ящик с G17, они переехали в нижний
- Риот-броня расположена на одной полке, щиты на другой. Дубинки удалены
- Добавлена полка с фулл-боди бронёй и тактическими шлемами
- Добавлены ящики с боеприпасами. В левом - нелетальные боеприпасы (шесть магазинов с резиной на G17, шесть коробок по 8 с бинбагом), в правом - летальные (боевые и картечь в таком же количестве)
- Удалены полки с ножами и противогазами, теперь они располагаются в ящиках офицеров
Изменения содержимого верхней оружейки:
- Полка с гранатомётом заменена полкой с тремя G17, он переехал на полку, где раньше были магазины G17
- Полка с двумя боевыми дробовиками заменена тремя обычными дробовиками (под вопросом, так как если будет реализовано [это](https://github.com/TauCetiStation/TauCetiClassic/pull/8175) то вторые станут практичнее первых)
- Удалены коробки с бинбагами на 20 патронов
- Небольшая перестановка предметов с полок справа, увеличение длины стола

2. Создание выхода в западные тех.туннели
Изменения карты:
![5](https://user-images.githubusercontent.com/17797554/141685139-7db915bd-fd8b-4708-9d31-1fc5f3338d2a.png)
Дверь в туннели такая же, как и в восточной части снизу
![6](https://user-images.githubusercontent.com/17797554/141691706-2d29155b-0258-4ba5-9399-d8609c15a4a2.png)
Немного изменено расположение строительных лесов

3. Новый контент:
- Тактический шлем: шлем охранника с фонариком. Светит как каска инженера. За основу спрайта был взят шлем вардена
(изображения будут позже добавлены, так как я пока что не могу скомпилировать у себя билд по другим причинам)

## Почему и что этот ПР улучшит
Изменения оружейной сделают её более практичной и пользование ей удобной: при уменьшении занятой площади количество экипировки даже стало немного побольше. Расположение оружия в нижней оружейной более логично: баллистика снизу, энерго сверху. Патроны в ящике и раздавать, и забирать куда проче, чем патроны на полке, особенно если они группированы. Так же добавлена картечь: в нынешней оружейке была только резина. Слаги не были добавлены потому что, по-моему мнению, это жир и излишество. Новый набор брони позволит СБ бороться с врагом с мощным огнестрельным оружием (револьвер, например) внутри станции, так как обычный бронежилет не спасает от отрывания рук и ног, а риот защищает только от холодного оружия. Я не знаю, можно ли записать в плюс то, что в верхней оружейной появилось много свободного места, выглядит пустовато, но с другой стороны в ней могут храниться ящики из карго/оружие учёных.

Западный проход позволит офицерам получить доступ в западные теха для различных целей: эвакуации, большей мобильности и прочего.

## Авторство
Спрайт тактического шлема сделан на основе шлема вардена.

## Чеинжлог

🆑 Stolaire

- map: Различные изменения в оружейной: перестановки, изменение освещения, добавление набора боевой брони и ящиков с боеприпасами, переезд некоторого снаряжения в ящики офицеров
- map: Добавление выхода в западные тех. туннели в бриге

2021-11-14 17:35 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2021-11-14 17:54 UTC, Sakuya-Izayoi requested changes
атомарность. как минимум новый шлем и изменения карты должны быть двумя разными прами.

2021-11-14 18:18 UTC, Stolaire commented
Я не знаю, действительно ли стоит создавать отдельный реквест для шлема, который нигде не будет спавниться на нынешней карте? Или ты имел в виду ПЛы внутри моей ветки? 
В снаряжении были изменены только дробовики, но так как этот момент спорный, его можно вернуть, и добавлена броня.  
Если выглядит пустовато, то что можно в верхней оружейке сверху поставить? Я думал про пустой ящик с замком и шкаф с контрабандой, в которой может рандомно заспавниться всякое. А тайлы пола в арсенале я не трогал.

2021-11-14 18:36 UTC, Sakuya-Izayoi commented
> Я не знаю, действительно ли стоит создавать отдельный реквест для шлема, который нигде не будет спавниться на нынешней карте? Или ты имел в виду ПЛы внутри моей ветки? Или я не понял В снаряжении были изменены только дробовики, но так как этот момент спорный, его можно вернуть, и добавлена броня. Если выглядит пустовато, то что можно в верхней оружейке сверху поставить? Я думал про пустой ящик с замком и закрытый шкаф с контрабандой, в которой может рандомно заспавниться всякое. А тайлы пола в арсенале я не трогал.

можно сделать несколько разных мап-пров, в одном добавить шлемы и куда-то всунуть их на карте, в другом поменять дробовики, в третьем ремап техов и так далее. если пользоваться мапмерж инструментом, то проблем с конфликтами в таком случае возникнуть не должно (если только ты в двух пулл реквестах не меняешь один и тот же тайл).

2021-11-14 20:05 UTC, Stolaire commented
Как я понял мне надо вывести что-то одно в отдельный ПР: оружейку или западный выход. Если так, то я откачу изменения второго, как так в оружейке затронута не только карта

2021-11-15 11:34 UTC, Stolaire commented
Я не знаю, можно ли прикреплять изображения к коммитам, но теперь оно выглядит вот так:
![8](https://user-images.githubusercontent.com/17797554/141775086-ede4638f-e596-418e-8a95-69ff27c26319.png)

2021-11-15 11:37 UTC, AndroBetel commented
Да верни прост риотку, как была, и на место ящика пистолей фуллбади армор.

2021-11-15 11:41 UTC, Stolaire commented
Мне показалось странным, что три набора риотки занимают три тайла, в том время как другая специализированная броня, в том же количестве - всего один. Поэтому риотка располагается так же на одной полке, как и, собственно, всё остальное

2021-11-15 11:43 UTC, AndroBetel commented
Ну так это было сделано, чтобы место визуально занять, плюсом там станбатоны и щиты вместе со штуками. Щас одиноко стоящий ящик не очень выглядит.

2021-11-15 12:30 UTC, Stolaire commented
Вообще эту пустоту могут запомнить игроки, например, ящиками из карго и всяким другим. 
> Я не знаю, можно ли записать в плюс то, что в верхней оружейной появилось много свободного места, выглядит пустовато, но с другой стороны в ней могут храниться ящики из карго/оружие учёных.

С другой стороны для этого есть пустой ящик.
С возвращением стандартного расположения риот-набора не согласен, но готов пойти на компромисс и предложить сделать так:
![image](https://user-images.githubusercontent.com/17797554/141781063-3cad54dd-770e-4f65-9297-c1366b2bc951.png)

Во-первых в трёх окнах одинаковое количество стоек, по 2. На одиночную стойку снизу можно, например, вернуть ножи. Правда тут проблема: что положить рядом с фулл-бади, что не дублирует снаряжение СБ (поэтому я удалил батоны из риот-набора) или из арсенала?

2021-11-16 14:11 UTC, kiVts commented
Тут вроде баланс меняют вместе с картой, почему? А почему нет?)))))

2021-11-16 14:14 UTC, Stolaire commented
![1](https://i.imgur.com/CiUeVQz.png)

Ножей восемь, а не десять, потому что в теории два будут лишними: 6 на охранников, для вардена и Хоса. То, что их не факт, что кто-то возьмёт, и зачем их так много уже другой вопрос
Почему к фулл-бади прилагается разгрузка? Для людей, если кто-то привык носить всякое в бронике СБ и захочется компенсировать отсутствие этой разгрузки в фулл-бади

2021-11-16 14:24 UTC, Stolaire commented
> Тут вроде баланс меняют вместе с картой, почему? А почему нет?)))))
Из баланса тут только завоз фулл-бади и шлема с фонариком, и то последнее под вопросом принадлежности к этой теме, так как это, внезапно, просто шлем СБ с фонариком, а так же завоз картечи и коробок с ружейными боеприпасами по 8 патронов. Первое сделано чтобы заполнить пустое место, да и фулл-бади - это не маринад, у него защита как у броников обычных, а второе - реализация дробовиков как баллистического оружия, потому что на данный момент для него доступны только нелетальный бинбаг. Летал надо либо заказывать, либо ломать протолат

2021-11-16 15:39 UTC, Pimap3 commented
Зачем ты разделил щиты и риот броню если между ними не стоит стекло? Если варден откроет риот броню, то офики спокойно могут взять щиты без проблем, поскольку разделения стеклом нету

2021-11-16 15:56 UTC, Stolaire commented
> Зачем ты разделил щиты и риот броню если между ними не стоит стекло? Если варден откроет риот броню, то офики спокойно могут взять щиты без проблем, поскольку разделения стеклом нету

А разве так не должно быть? Как-бы сейчас на каждой полке с риот-сетом так же располагается щит и дубинка, даже в ящике карго с риот-снаряжением к риот-броне приложены щиты. Какая причина их разделять, если они, можно сказать, считаются частью одного набора экипировки?

2021-11-16 17:25 UTC, Stolaire commented
Почему происходит конфликт при мердже карт? Изменения на западном выходе я откатил, шлем добавлен на изменённый кусок карты. Билд с картой компилируется и запускается без проблем. Я что-то забыл?

2021-11-16 17:27 UTC, KIBORG04 commented
Потому что ты юзаешь бьондовский редактор и не юзаешь хуки.

2021-11-22 00:54 UTC, Sakuya-Izayoi requested changes
требования по атомарности все еще не выполнены.

карта конвертирована, но в мапдиффе я вижу кучу непонятных изменений по всей станции.

2021-11-22 18:05 UTC, Stolaire commented
Это странно, вроде оружейку перенёс копипастом на нынешнуюю карту. Ну ладно, судя по всему, что уже подоспел ПР с новым бригом, который народ, видимо, одобряет, и то, что эту оружейку народ не одобряет я всё-таки закрою этот ПР и возможно попробую сделать что-нибудь другое в будущем

2021-11-22 18:05 UTC, closed without merging