Эмоуты для игры "камень-ножницы-бумага"
TauCetiStation/TauCetiClassic pull request #8220
Opened 2021-11-15 19:11 UTC by KIBORG04

## Описание изменений

https://user-images.githubusercontent.com/26389417/141839960-4c5e147a-d2c0-4b5d-b7d8-aa475e868efa.mp4

Если кто-то хочет это сделать в нечто большее, где сама игра будет одновременно отправлять эмоут, когда все игроки готовы, то советую это делать через `/datum/element`.

## Почему и что этот ПР улучшит
РП

## Авторство

## Чеинжлог
:cl:
 - tweak: Есть написать в say на человеке *rock, *paper, *scissors то вылезет прикольная анимация.

2021-11-15 19:11 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2021-11-15 19:12 UTC, KIBORG04 commented on code/__DEFINES/misc.dm
> +#define Y_OFFSET(n, d) (n * (!!(d & NORTH) + !!(d & SOUTH) * -1))
Работает этот механ так:
![image](https://user-images.githubusercontent.com/26389417/141840264-e6eedb63-5e12-41f1-8614-46ccb76507a6.png)

2021-11-15 19:38 UTC, Sakuya-Izayoi commented
Поч на английском?

2021-11-15 19:39 UTC, KIBORG04 commented
> Поч на английском?

Мы вроде еще не перешли на стадию перевода эмоутов

2021-11-15 19:57 UTC, SpaiR requested changes

2021-11-15 19:57 UTC, SpaiR commented on code/__DEFINES/misc.dm
> +#define Y_OFFSET(n, d) (n * (!!(d & NORTH) + !!(d & SOUTH) * -1))
Так это, добавь комментариев к дефайнам. Мол "нужно для... работает так...". Сейчас вообще не понять.

2021-11-15 19:57 UTC, SpaiR commented on code/modules/mob/rps_game.dm
> +/atom/movable/proc/RPS_animation(choice)
RPS это как RTS, только RPS?)
Назови, пожалуйсвта, метод нормально. Догадаться, что это камень ножницы бумага невозможно.

2021-11-15 20:03 UTC, KIBORG04 commented on code/modules/mob/rps_game.dm
> +/atom/movable/proc/RPS_animation(choice)
rock paper scissors. Как еще то

2021-11-15 20:05 UTC, SpaiR commented on code/modules/mob/rps_game.dm
> +/atom/movable/proc/RPS_animation(choice)
Читая код эмуотов вычитать это название из RPS невозможно. Любой (да и ты сам через некоторое время) полезет смотреть что это за штука такая. Так и назвои. `play_rock_paper_scissors()`

2021-11-15 22:41 UTC, KIBORG04 commented
> Поч на английском?

Впринципе, если людям действительно проблемно переводить мозгом и переключать раскадку, то могу и перевести

2021-11-16 14:33 UTC, LudwigVonChesterfield commented on code/__DEFINES/misc.dm
> +#define X_OFFSET(n, d) (n * (!!(d & EAST) + !!(d & WEST) * -1))
возможно стоит хотя бы X_OFFSET(n_steps, direction) для хоть какой-то ясности...

2021-11-16 14:45 UTC, LudwigVonChesterfield commented on code/modules/mob/living/carbon/human/emote.dm
> +	if(!(act in exception_words) && findtext(act, "s", -1) && !findtext(act, "_", -2)) // Removes ending s's unless they are prefixed with a '_'
не знаю кого-либо кто писал бы эмоуты с s в конце, возможно для нас это не очень актуально...

2021-11-17 05:58 UTC, SpaiR commented on code/modules/mob/living/carbon/human/emote.dm
> +	if(!(act in exception_words) && findtext(act, "s", -1) && !findtext(act, "_", -2)) // Removes ending s's unless they are prefixed with a '_'
На самом деле, звучит резонно.

2021-11-17 15:07 UTC, KIBORG04 commented on code/modules/mob/living/carbon/human/emote.dm
> +	if(!(act in exception_words) && findtext(act, "s", -1) && !findtext(act, "_", -2)) // Removes ending s's unless they are prefixed with a '_'
удалить так удалить

2021-11-17 15:08 UTC, KIBORG04 commented on code/__DEFINES/misc.dm
> +#define X_OFFSET(n, d) (n * (!!(d & EAST) + !!(d & WEST) * -1))
ладно

2021-11-17 19:01 UTC, TauKitty commented
This pull request has been mentioned on **Tau Ceti Station Forum**. There might be relevant details there:

https://forum.taucetistation.org/t/nuzhno-li-perevesti-emouty-kamen-nozhniczy-bumaga-na-russkij-golosovanie/29597/1

2021-11-18 06:53 UTC, SpaiR approved these changes

2021-11-18 12:45 UTC, KIBORG04 commented
![image](https://user-images.githubusercontent.com/26389417/142417783-e452af07-2c11-46dc-994a-bd07706779ae.png)

Голосование на форуме выбрало перевод. Ну, я готов ревертнуть это в любую секунду

2021-11-18 20:18 UTC, LudwigVonChesterfield commented on code/modules/mob/living/carbon/human/emote.dm
> +			switch(gender)
боже мой maybe you shouldn't repeat yourself?

вообще лично мне как-то по барабану насчёт голосований на форуме... у нас нет систем для таких фокусов переводов, когда будут - тогда пускай и голосуют.

не думаю что в этом ПР-е имеет смысл эти системы изобретать

2021-11-20 11:58 UTC, merged