Улучшение защиты укрепленного стола
TauCetiStation/TauCetiClassic pull request #8227
Opened 2021-11-16 21:55 UTC by Akellazp

## Описание изменений
Укрепленный слот лучше защищает от выстрелов и полностью скрывает от стрелка лежащего за собой человека 
## Почему и что этот ПР улучшит
Больше пользы от усиленного стола плюс фича
## Авторство
Akellazp
## Чеинжлог
:cl:
- tweak: Укрепленный стол теперь намного лучше защищает от выстрелов

2021-11-16 21:55 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2021-11-16 22:27 UTC, Sakuya-Izayoi requested changes

2021-11-16 22:27 UTC, Sakuya-Izayoi commented on code/game/objects/structures/tables_racks.dm
> +	return 1
слишком много копипасты. перегруженный механ вынеси в отдельные проки или даже просто добавь свойства классу и их чекай.

2021-11-17 17:17 UTC, Sakuya-Izayoi commented on code/game/objects/structures/tables_racks.dm
>  			if (health > 0)
это совсем не то что я имел ввиду в своем ревью... пройдись глазами по проку и посмотри как это будет работать.

2021-11-17 17:38 UTC, Akellazp commented on code/game/objects/structures/tables_racks.dm
>  			if (health > 0)
я тестил всё работает как надо

2021-11-19 15:45 UTC, Akellazp commented
@totallynotdedawa2 хейтер бака твой дизлайк не учитывается

2021-11-22 17:47 UTC, Sakuya-Izayoi commented
наверное это не очень хорошо что переменная флипабл отвечает и за возможность перевернуть стол и за защиту ног, но ладно, сойдет. как-нибудь потом.

2021-11-22 17:48 UTC, merged

2021-11-22 17:48 UTC, Akellazp commented
благодаря проверке переменной мы понимаем что стол укрепленный и добавляем защиту

2021-11-22 17:54 UTC, Sakuya-Izayoi commented
нет, это делается не так.