[Alien] ЦК будет присылать помощь во время режима infestation
TauCetiStation/TauCetiClassic pull request #8229
Opened 2021-11-17 00:08 UTC by Ahion

## Описание изменений
Когда число ксеноморфов достигнет 20% от экипажа, будет первый анонс, станцию посадят на карантин (`fake_recall`) и ЦК пришлет ящики с припасами. При достижении алиенов 60% от экипажа, будет прислано более лучшее вооружение.
Шаттл карго автоматически полетит, если не будет занят. В противном случае будет немного другой анонс, ящики добавятся в список для поставки и шаттл нужно будет отправлять самим.
**Что в ящиках:**

1. В первых поставках, в каждом ящике находятся био-костюм, наушники, щит деревянный, маленькая аптечка с автоинжекторами (ксеноарх), граната против сорняков, газ-маска и в трёх ящиках будет по лазеру, в двух по дробовику на 4 выстрела и коробка с 8-ю зажигательными патронами. Всего 5 ящиков.
2. Во второй поставке, в каждом ящике уже лежат риг СБ, комбо-дробаш на 8 выстрелов, тоже коробка зажигательных патронов (8 шт), 2 гранаты против сорняков и комбо-аптечка. Тоже 5 ящиков, и будет ящик с 5-ю коробками зажигательных патронов по 8 шт.

Если экипаж уничтожит всех взрослых ксеноморфов, то будет анонс и карантин снимут. Считай победа экипажа.

## Почему и что этот ПР улучшит
Получил я статистику по режиму с мая по ноябрь. Винрейт алиенов: **56%**. Наблюдая за режимом, постоянно видел что алиенам тяжело в начале, их либо душат сразу и экста, либо они проходят этот порог и начинается избиение почти беззащитного экипажа. Отсюда, пожалуй, очевидный вывод: нужно в определенные моменты усиливать экипаж, что бы он мог оказывать сопротивление, а то и побеждать.
## Авторство
Ahio
## Чеинжлог
:cl: Ahio
 - balance[link]: Во время режима infestation, ЦК будет присылать вооружение экипажу.

2021-11-17 00:08 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2021-11-17 00:22 UTC, TauKitty commented
This pull request has been mentioned on **Tau Ceti Station Forum**. There might be relevant details there:

https://forum.taucetistation.org/t/czk-budet-prisylat-pomoshh-vo-vremya-rezhima-infestation/29584/1

2021-11-17 00:43 UTC, Sakuya-Izayoi requested changes

2021-11-17 00:43 UTC, Sakuya-Izayoi commented on code/datums/announcements/gamemode.dm
> +			"Рассматривается вопрос об отправке Отряда Быстрого Реагирования."
посмотри прок trim_margin

2021-11-17 00:43 UTC, Sakuya-Izayoi commented on code/game/gamemodes/factions/infestation.dm
> +	var/list/first_help = list("Xeno liquidator" = 3, "Xeno destroer" = 2)
```suggestion
	var/list/first_help = list("Xeno liquidator" = 3, "Xeno destroyer" = 2)
```

2021-11-17 00:43 UTC, Sakuya-Izayoi commented on code/game/gamemodes/factions/infestation.dm
> +	var/list/first_help = list("Xeno liquidator" = 3, "Xeno destroer" = 2)
Не совсем ясно что значат эти цифры

2021-11-17 00:43 UTC, Sakuya-Izayoi commented on code/game/gamemodes/factions/infestation.dm
> +		second_help_sended = TRUE
а если в будущем кто-то захочет сделать n помощей экипажу?

2021-11-17 00:43 UTC, Sakuya-Izayoi commented on code/game/gamemodes/factions/infestation.dm
> +		second_help_sended = TRUE
send в прошлом это sent

2021-11-17 00:43 UTC, Sakuya-Izayoi commented on code/game/gamemodes/factions/infestation.dm
> +			SSshuttle.shoppinglist += O
**возможно** (не обязательно) стоит обобщить этот механ чтобы помощь в карго можно было отправлять из любого гейммода

2021-11-17 00:43 UTC, Sakuya-Izayoi commented on code/modules/cargo/packs.dm
> +	crate_name = "Xeno destroer crate"
```suggestion
	name = "Xeno destroyer"
	contains = list(/obj/item/clothing/suit/bio_suit/old_hazmat/sec,
					/obj/item/clothing/head/bio_hood/old_hazmat/sec,
					/obj/item/weapon/gun/projectile/shotgun,
					/obj/item/ammo_box/eight_shells/incendiary,
					/obj/item/weapon/shield/buckler,
					/obj/item/clothing/ears/earmuffs,
					/obj/item/clothing/mask/gas/coloured,
					/obj/item/weapon/grenade/chem_grenade/antiweed,
					/obj/item/weapon/storage/firstaid/small_firstaid_kit/space)
	cost = 10000
	crate_name = "Xeno destroyer crate"
```

ну ты понел

2021-11-17 00:51 UTC, Sakuya-Izayoi commented
наверное там не реквест чейндж должен быть а просто ревью, что-то я на сонную голову нажал эту кнопку. я думаю ты понял, к чему я.

2021-11-17 04:40 UTC, Ahion commented on code/game/gamemodes/factions/infestation.dm
> +	var/list/first_help = list("Xeno liquidator" = 3, "Xeno destroer" = 2)
количество ящиков, я думал очевидно

2021-11-17 04:40 UTC, Ahion commented on code/game/gamemodes/factions/infestation.dm
> +		second_help_sended = TRUE
точно, спасибо

2021-11-17 04:49 UTC, Ahion commented on code/datums/announcements/gamemode.dm
> +			"Рассматривается вопрос об отправке Отряда Быстрого Реагирования."
что-то в поиске по билду не нахожу такой

2021-11-17 05:20 UTC, Ahion commented on code/game/gamemodes/factions/infestation.dm
> +			SSshuttle.shoppinglist += O
обобщил для всех фракций

2021-11-17 21:46 UTC, KIBORG04 commented on code/datums/announcements/gamemode.dm
> +			"Рассматривается вопрос об отправке Отряда Быстрого Реагирования."
Обнови билд

2021-11-17 21:46 UTC, KIBORG04 commented on code/datums/announcements/gamemode.dm
> +			"Рассматривается вопрос об отправке Отряда Быстрого Реагирования."
Да и текущий вариант не то чтобы плохой

2021-11-17 21:48 UTC, KIBORG04 commented on code/game/gamemodes/factions.dm
> +		SSshuttle.moving = 1
```suggestion
		SSshuttle.moving = 1
```
а разве эти дефайны не к мувингу?
![image](https://user-images.githubusercontent.com/26389417/142287838-ac916fe5-076d-4d08-b30c-8ce7beec506b.png)

2021-11-17 21:53 UTC, KIBORG04 commented on code/game/gamemodes/factions.dm
> +/datum/faction/proc/send_help_crew(list/supply_crates, announce, announce_fail)
Почему у метода такое название? Здесь довольно четкая абстракция вокруг ФРАКЦИИ, да и ниже очень хардкоденные аноунсы. Скорее всего, ты должен из этого метода сделать еще большую абстракцию и вынести куда-то отсюда, мб в /datum/gamemode и всю важную инфу передавать в аргументы. А разместить можно в файле `code\game\gamemodes\misc_gamemode_procs.dm`.

2021-11-20 07:17 UTC, Ahion commented on code/game/gamemodes/factions.dm
> +		SSshuttle.moving = 1
Нет, эти дефайны к муву не относятся. И используются они для шаттла эвакуации

2021-11-20 07:17 UTC, Ahion commented on code/game/gamemodes/factions.dm
> +/datum/faction/proc/send_help_crew(list/supply_crates, announce, announce_fail)
вернул этот прок только для алиенов

2021-11-20 07:20 UTC, Ahion commented
Перебалансил состав помощи. Удалил набор с дробовиком из первой поставки, удалил коробку с зажигательными из второй. В обоих поставках будет приходить по 4 ящика, а не по 5. Из первой поставки удалил наушники. Поднял процент первой до 30, второй до 80.

2021-11-20 12:24 UTC, KIBORG04 commented on code/datums/announcements/gamemode.dm
> +/datum/announcement/centcomm/xeno/second_help/New()
Мне кажется, писать про взрыв станции народу на ней немного дискредитируще. Вроде как, по РП, люди даже не знают о нахождение бомбы на ней, а тем более о таких действиях со стороны  НТ. 
Лучше наверное убрать про уничтожение станции.

2021-11-20 12:25 UTC, KIBORG04 commented on code/game/gamemodes/factions/infestation.dm
> +		send_help_crew(second_help, /datum/announcement/centcomm/xeno/second_help, /datum/announcement/centcomm/xeno/second_help/fail)
Высылание помощи должно быть в `/datum/faction/infestation/process()`, а не в `проверить_победу()`

2021-11-20 12:27 UTC, KIBORG04 commented on code/game/gamemodes/factions/infestation.dm
> +		for(var/i = 1, i <= number_supply_orders, i++)
```suggestion
		for(var/i in 1 to number_supply_orders)
```
Этот цикл быстрее

2021-11-20 12:27 UTC, KIBORG04 commented on code/game/gamemodes/factions/infestation.dm
> +	else if(SSshuttle.at_station)
```suggestion
	if(SSshuttle.at_station)
```
Выше ретурт и илс не нужен

2021-11-20 13:36 UTC, Ahion commented on code/game/gamemodes/factions/infestation.dm
> +		send_help_crew(second_help, /datum/announcement/centcomm/xeno/second_help, /datum/announcement/centcomm/xeno/second_help/fail)
Я сделал это здесь, потому что в этом проке уже считается текущий процент. Какой смысл переносить это в `process`?

2021-11-20 13:40 UTC, KIBORG04 commented on code/game/gamemodes/factions/infestation.dm
> +		send_help_crew(second_help, /datum/announcement/centcomm/xeno/second_help, /datum/announcement/centcomm/xeno/second_help/fail)
Потому что это просто логичней. Почему метод на проверку_победы проверяет не только победу?

2021-11-20 13:41 UTC, Ahion commented on code/game/gamemodes/factions/infestation.dm
> +		send_help_crew(second_help, /datum/announcement/centcomm/xeno/second_help, /datum/announcement/centcomm/xeno/second_help/fail)
Тут же `last_check` проверяется, процесс не нужен

2021-11-20 13:48 UTC, Ahion commented on code/datums/announcements/gamemode.dm
> +/datum/announcement/centcomm/xeno/second_help/New()
убрал

2021-11-20 13:48 UTC, Ahion commented on code/game/gamemodes/factions/infestation.dm
> +	else if(SSshuttle.at_station)
else убрал

2021-11-20 13:49 UTC, Ahion commented on code/game/gamemodes/factions/infestation.dm
> +		for(var/i = 1, i <= number_supply_orders, i++)
готово

2021-11-20 15:23 UTC, Ahion commented on code/game/gamemodes/factions/infestation.dm
> +		send_help_crew(second_help, /datum/announcement/centcomm/xeno/second_help, /datum/announcement/centcomm/xeno/second_help/fail)
Ладно, я сделал

2021-11-23 23:02 UTC, KIBORG04 commented on code/__DEFINES/xenomorph.dm
> +#define WIN_PERCENT			    190
```suggestion
#define TOTAL_HUMAN         1
#define TOTAL_ALIEN         2
#define ALIEN_PERCENT       3
#define FIRST_HELP_PERCENT  30
#define SECOND_HELP_PERCENT 80
#define WIN_PERCENT         190
```
Выравнивать табами+пробелами ужс

2021-11-23 23:25 UTC, Ahion commented on code/__DEFINES/xenomorph.dm
> +#define WIN_PERCENT			    190
Да это гит так показывает. В редакторе всё нормально. Какой раз уже за это цепляетесь

2021-11-23 23:26 UTC, Ahion commented on code/__DEFINES/xenomorph.dm
> +#define WIN_PERCENT			    190
Да это гит так показывает. В редакторе всё нормально. Какой раз уже за это цепляетесь. У меня там только табы

2021-11-23 23:27 UTC, merged

2021-11-23 23:32 UTC, KIBORG04 commented on code/__DEFINES/xenomorph.dm
> +#define WIN_PERCENT			    190
Вскод может сам преобразовывать табы в пробелы при сохранении файла. Ну не суть, я уже пробелы закоммитил и замержил

2021-11-24 00:14 UTC, Ahion commented on code/__DEFINES/xenomorph.dm
> +#define WIN_PERCENT			    190
Спасибо тебе)