Переработан способ получения эктоплазмы с фотки с призраками
TauCetiStation/TauCetiClassic pull request #8237
Opened 2021-11-18 11:49 UTC by KIBORG04

## Описание изменений
Фикс дюпа эктоплазмы, при котором было достаточно начать ду_афтер в burnpaper и сразу же прервать его. 

Теперь из фотки с призраками выпадает `количество_призраков / 3 ` эктоплазмы.

## Почему и что этот ПР улучшит
Минус баг
Эктоплазму все еще можно получить, если фоткать ролек

## Авторство

## Чеинжлог
:cl:
 - fix: Исправлен бесконечный приток эктоплазмы с фотки с призраками
 - tweak: Фотка с призраками даёт количество_призраков / 3 эктоплазмы

2021-11-18 11:49 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2021-11-18 11:56 UTC, Sakuya-Izayoi approved these changes

2021-11-18 12:02 UTC, kalazus commented
Может тогда починишь и то что эктоплазма может в человеке появится при сожжении, и тогда он при гибе станет пиньятой. 
Разве round позволит получить эктоплазму при 1 призраке? Может лучше floor (или подобную функцию, не знаю округление в бьёнде) эктоплазмы и на дробную часть prob?

2021-11-18 12:04 UTC, KIBORG04 commented
> Может тогда починишь и то что эктоплазма может в человеке появится при сожжении, и тогда он при гибе станет пиньятой.

А, хмммм.

> Разве round позволит получить эктоплазму при 1 призраке?

И не должна. Раунд округляет в меньшую сторону.

2021-11-18 12:06 UTC, kalazus commented
> И не должна. Раунд округляет в меньшую сторону.

Так 2 призраков хрен найдёшь ведь есть баг, что орбитящие призраки не записываются в фотографию.

2021-11-18 12:07 UTC, KIBORG04 commented
Вот пофиксят баг, так сразу паранормальщики заживут.

2021-11-18 12:07 UTC, Sakuya-Izayoi requested changes
я передумал, фикси баг чтобы орбитящие призраки учитывались

2021-11-18 12:08 UTC, KIBORG04 commented
> я передумал, фикси баг чтобы орбитящие призраки учитывались

Нет.

2021-11-18 12:47 UTC, muWander commented
это ж не баг а фича чтоб ролек по обсервящим их гостам не палили

2021-11-19 11:56 UTC, Ro2tCrab commented
Киборг пытался урезать параномалистов, но в итоге сделал капеллана ещё сильне против культа. :rofl:

2021-11-19 11:58 UTC, KIBORG04 commented
че

2021-11-19 22:15 UTC, kalazus commented
> это ж не баг а фича чтоб ролек по обсервящим их гостам не палили

Возможно, но рольку орбитят призраки с разными спрайтами, так что увидеть на фотографии можно и 3-4 призраков, а эктоплазмы с этого получится 0. Да и зачем это? Можно найти лояльного призрака и говорить с ним через да/нет/не знаю.

2021-11-26 13:05 UTC, KIBORG04 commented
морж будет?

2021-11-26 13:32 UTC, Sakuya-Izayoi commented
> морж будет?

орбитящие госты учитываются на фотографиях?

2021-11-26 13:38 UTC, KIBORG04 commented
нет это имба фича

2021-11-26 13:41 UTC, Sakuya-Izayoi commented
> нет это имба фича

без этого не работает фича с эктоплазмой. мержа не будет.

2021-11-27 00:50 UTC, KIBORG04 commented
![image](https://user-images.githubusercontent.com/26389417/143662950-1c5f6f90-d545-4b2c-a654-149a06c27fa2.png)

Это не баг, а фича. УСЕКЛИ???

2021-11-27 00:54 UTC, KIBORG04 commented
Если хотите, я могу это же поставить и для картинки призрака. Ибо сейчас картинка призрака есть, он стоит на человечка. Но при осмотре фотки призраков не видно.
Поэтому `фича чтоб ролек по обсервящим их гостам не палили` является ложью и провокацией. Ролек палить можно, но нельзя палить кто палит на рольку.

2021-11-27 14:46 UTC, Sakuya-Izayoi approved these changes
убедил

2021-11-27 16:00 UTC, merged