гладиаторы = игроки
TauCetiStation/TauCetiClassic pull request #8239
Opened 2021-11-18 15:43 UTC by AndroBetel

## Описание изменений
Меняет имя мобов на Арене с гладиаторов на сикеи игроков.
## Почему и что этот ПР улучшит
Забавно, можно метахейтить плееров.
## Авторство

## Чеинжлог

2021-11-18 15:43 UTC, TauKitty commented
###### Changelog status: :radio_button: No changelog

2021-11-18 20:13 UTC, LudwigVonChesterfield commented
возможно людям с скрытым дедчат сикеем стоит оставить Гладиатор?

2021-11-18 20:17 UTC, AndroBetel commented
Ну в принципе.

2021-11-19 06:32 UTC, SpaiR requested changes
Предложение выше.

2021-11-19 15:40 UTC, AndroBetel commented
Людук-пиндюк написал в дискорд, а сюда не написал. В дедчатиксе можно скрывать сикей, чтобы не спалили твою куклу. Здесь же никакого смысла в этом я не вижу, так что....

2021-11-19 15:40 UTC, AndroBetel commented
@SpaiR

2021-11-27 00:13 UTC, merged