Улучшения карты брига
TauCetiStation/TauCetiClassic pull request #8243
Opened 2021-11-19 10:27 UTC by Lexakr

## Описание изменений
* Детектив переехал из брига на место мед. аванпоста
* Мед. аванпост удален
* Коридор брига расширен до 3-х тайлов
* 2 дополнительные камеры заключения 
* Западный выход из брига через допросную
* Немного переделан лазарет в бриге 
* Бластдоры стоят на всех внешних дверях (тут возможен дискасс)

Мусор в космосе только на скрине
<details> 
<summary>Вид в игре (кликабельно)</summary>
<img src="https://user-images.githubusercontent.com/29842063/142605010-c37fa152-ef0f-4cb5-aace-b0650cae1206.png">
</details>

## Почему и что этот ПР улучшит

Широкий коридор уберет толкучку (особенно на прямой от входа в бриг до входа в комнату со снарягой). У нас на карте во всех основных отделах есть коридоры в 3 тайла (РнД, медбей), а тут был в 2, хотя людей тут часто бывает много. Детектив теперь находится в менее людном месте, я считаю, это пойдет ему на пользу (на большинстве карт ТГ, например, он везде находится вне брига). 2 доп камеры решат проблему их нехватки, а еще с них вместо общака вид прямо на коридор и стекла там разрушаемые.

## Чеинжлог
:cl:
 - map[link]: Изменения в бриге.

2021-11-19 10:27 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2021-11-19 10:37 UTC, TauKitty commented
This pull request has been mentioned on **Tau Ceti Station Forum**. There might be relevant details there:

https://forum.taucetistation.org/t/golosovanie-tyurma-vmesto-obshhej-kamery/29630/29

2021-11-19 12:42 UTC, Sakuya-Izayoi commented
Выпирающий медпунктик напротив камер заключения имхо так себе, можно и без этого.

Да все камеры на месте офиса детектива всего шесть тайлов, в них очень скучно будет сидеть. + У тебя лампочка на окне висит.

2021-11-19 12:44 UTC, Stolaire commented
Освещение в оружейке всё ещё такое блевотное. Может стоило поставить обычные лампы?

2021-11-19 13:18 UTC, 05126619z commented
> ## Описание изменений
> * Детектив переехал из брига на место мед. аванпоста
> * Мед. аванпост удален
> * Коридор брига расширен до 3-х тайлов
> * 2 дополнительные камеры заключения
> * Западный выход из брига через допросную
> * Немного переделан лазарет в бриге
> * Бластдоры стоят на всех внешних дверях (тут возможен дискасс)
> 
> Мусор в космосе только на скрине
> 
> Вид в игре (кликабельно)
> ## Почему и что этот ПР улучшит
> Широкий коридор уберет толкучку (особенно на прямой от входа в бриг до входа в комнату со снарягой). У нас на карте во всех основных отделах есть коридоры в 3 тайла (РнД, медбей), а тут был в 2, хотя людей тут часто бывает много. Детектив теперь находится в менее людном месте, я считаю, это пойдет ему на пользу (на большинстве карт ТГ, например, он везде находится вне брига). 2 доп камеры решат проблему их нехватки, а еще с них вместо общака вид прямо на коридор и стекла там разрушаемые.
> 
> ## Чеинжлог
> 🆑
> 
> * map[link]: Изменения в бриге.

Строго за

2021-11-19 13:18 UTC, 05126619z commented
> ## Описание изменений
> * Детектив переехал из брига на место мед. аванпоста
> * Мед. аванпост удален
> * Коридор брига расширен до 3-х тайлов
> * 2 дополнительные камеры заключения
> * Западный выход из брига через допросную
> * Немного переделан лазарет в бриге
> * Бластдоры стоят на всех внешних дверях (тут возможен дискасс)
> 
> Мусор в космосе только на скрине
> 
> Вид в игре (кликабельно)
> ## Почему и что этот ПР улучшит
> Широкий коридор уберет толкучку (особенно на прямой от входа в бриг до входа в комнату со снарягой). У нас на карте во всех основных отделах есть коридоры в 3 тайла (РнД, медбей), а тут был в 2, хотя людей тут часто бывает много. Детектив теперь находится в менее людном месте, я считаю, это пойдет ему на пользу (на большинстве карт ТГ, например, он везде находится вне брига). 2 доп камеры решат проблему их нехватки, а еще с них вместо общака вид прямо на коридор и стекла там разрушаемые.
> 
> ## Чеинжлог
> 🆑
> 
> * map[link]: Изменения в бриге.

Строго за

2021-11-19 13:41 UTC, UDaV73rus commented
На ТГ детектив и не сломанная профа
У нас за него играть не весело, ещё и отдаляешь от социалочки. Ожидал от ремапа объединения с криминалистом...

2021-11-19 14:14 UTC, kalazus commented
МММ, вход в допросную через теха... А так, не понятно зачем вообще это? 
Выкинуть детектива из брига? Вроде никто не жаловался что он там был, а криминалиста оставили.
Доп камеры? Зачем, если общаг находится на том-же расстоянии.
3 тайла? Офицеры почти не сидят в своём отделе. В меде 3 тайла только для красоты, пользы 0 от них. В рнд тоже больше для красоты (вход в 2 тайла смотрелся бы очень херово). Единственное место где нужны 3 тайла, это между началом комнаты обыска и пару тайлов за входом в офис сб.

2021-11-19 14:27 UTC, Stolaire commented
>МММ, вход в допросную через теха... А так, не понятно зачем вообще это?

Выход из брига в западные теха. Сейчас чтобы туда попасть нужно либо имет доступ в криминалистику, либо обходить, выйдя из брига

2021-11-21 18:46 UTC, Lexakr commented
> На ТГ детектив и не сломанная профа У нас за него играть не весело, ещё и отдаляешь от социалочки. Ожидал от ремапа объединения с криминалистом...

Алсо, думаю это неплохое подспорье на будущее

2021-11-21 21:23 UTC, Sakuya-Izayoi requested changes
убери лампочку с окна там где новые камеры

2021-11-22 16:07 UTC, TauKitty commented
This pull request has been mentioned on **Tau Ceti Station Forum**. There might be relevant details there:

https://forum.taucetistation.org/t/wip-blueshield-officer-i-ego-sudba/27761/343

2021-11-26 11:00 UTC, closed without merging