portalgun
TauCetiStation/TauCetiClassic pull request #8246
Opened 2021-11-19 16:43 UTC by AndroBetel

## Описание изменений
Добавляет порталган, исследуется на последних уровнях блюспейс штук, чтобы сделать его нужны алмазы, серебро, фороний и уран. Чтобы он работал - нужно вставить в него ядро аномалии.
## Почему и что этот ПР улучшит
Больше контента. =)
## Авторство
Копипаст с ТГ, спрайт с Эриса.
## Чеинжлог
:cl:
- rscadd: Добавляет порталган в РнД.

2021-11-19 16:43 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2021-11-19 16:46 UTC, KIBORG04 commented
Сделай чтобы было видно какой-нибудь ближайший тайл из портала

2021-11-19 16:48 UTC, AndroBetel commented
МБ сам сделаешь потом это сложно наверное.

2021-11-19 16:50 UTC, KIBORG04 commented
Да не, вроде изи.
https://github.com/Baystation12/Baystation12/pull/30310/files

2021-11-19 16:52 UTC, KIBORG04 commented on code/modules/projectiles/guns/energy/special.dm
> +		return
```suggestion
/obj/item/weapon/gun/energy/gun/portal/attackby(obj/item/C, mob/user)
	if(istype(C, /obj/item/device/assembly/signaler/anomaly))
		user.drop_from_inventory(C, src)
		to_chat(user, "You insert [C] into the wormhole projector and the weapon gently hums to life.")
		playsound(user, 'sound/weapons/guns/plasma10_load.ogg', VOL_EFFECTS_MASTER)
		firing_core = C
		modifystate = 2
		update_icon()
		return
	return ..()
```
Наверное надо так.

2021-11-19 17:27 UTC, AndroBetel commented
Ээээ может когда-нибудь потом.

2021-11-19 22:56 UTC, KIBORG04 commented on code/modules/projectiles/guns/energy/special.dm
> +	modifystate = 0
```suggestion
	ammo_type = list(/obj/item/ammo_casing/energy/wormhole, /obj/item/ammo_casing/energy/wormhole/orange)
	icon_state = "portal"
	modifystate = 0
	
	var/obj/effect/portal/p_blue
	var/obj/effect/portal/p_orange
	var/obj/item/device/assembly/signaler/anomaly/firing_core = null
```

2021-11-19 22:57 UTC, KIBORG04 commented on code/modules/projectiles/guns/energy/special.dm
> +	update_icon()
Вызов апдейт айкона же не нужен

2021-11-19 22:57 UTC, KIBORG04 commented on code/modules/projectiles/guns/energy/special.dm
> +	update_icon()
У которого даже своего механа нет

2021-11-19 22:58 UTC, KIBORG04 commented on code/modules/projectiles/guns/energy/special.dm
> +		user.update_inv_l_hand()
```suggestion
		update_inv_mob()
```

2021-11-19 22:58 UTC, KIBORG04 commented on code/modules/projectiles/guns/energy/special.dm
> +		user.update_inv_l_hand()
```suggestion
		update_inv_mob()
```

2021-11-21 12:44 UTC, infraredbaron commented
Есть отдельно специально нарисованый от меня же порталган, который лучше чем перекрас плазмагана:
![image](https://user-images.githubusercontent.com/49165135/142762337-d918e981-cf8d-4517-b751-d02a947c81c1.png)

2021-11-21 12:51 UTC, AndroBetel commented
Спасибо за рисунок ключа!

2021-11-21 13:55 UTC, AndroBetel commented
https://freesound.org/people/megaxmilkman/sounds/440838/ 
Новый звук. Обрезал чуть короче.
Респрайт бай товарищ Инфраредбарон.
![image](https://user-images.githubusercontent.com/44546836/142764708-b18adf32-f609-4582-a835-cd389ba15a10.png)

2021-11-21 17:33 UTC, Sakuya-Izayoi commented on code/modules/projectiles/guns/energy/special.dm
> +		firing_core = null
Хз может в руку класть? У нас для этого прок есть.

2021-11-21 17:33 UTC, Sakuya-Izayoi commented on code/modules/projectiles/guns/energy/special.dm
> +		icon_state = "portal100"
Разве 100 само не дописывается в апдейте?

2021-11-21 17:33 UTC, Sakuya-Izayoi commented on code/modules/projectiles/guns/energy/special.dm
> +/obj/item/weapon/gun/energy/gun/portal/proc/create_portal(obj/item/projectile/beam/wormhole/orange/W, turf/target)
Неправильный тип аргумента

2021-11-21 17:33 UTC, Sakuya-Izayoi commented on code/modules/projectiles/guns/energy/special.dm
> +/obj/item/weapon/gun/energy/gun/portal/proc/on_portal_destroy(obj/effect/portal/P)
Может я что-то упустил и ты хотел зарегать на портале сигнал парент кделетинг на этот прок? Потому что я не вижу упоминание этого прока в ПРе.

2021-11-21 17:34 UTC, KIBORG04 commented on code/modules/projectiles/guns/energy/special.dm
> +	var/obj/item/device/assembly/signaler/anomaly/firing_core = null
Чисти ссылки в Destroy()

2021-11-21 17:38 UTC, AndroBetel commented on code/modules/projectiles/guns/energy/special.dm
> +		firing_core = null
И в какую руку ты собрался класть...

2021-11-21 17:53 UTC, AndroBetel commented on code/modules/projectiles/guns/energy/special.dm
> +/obj/item/weapon/gun/energy/gun/portal/proc/create_portal(obj/item/projectile/beam/wormhole/orange/W, turf/target)
А почему оно работало и не ломалось?

2021-11-21 18:23 UTC, Sakuya-Izayoi commented on code/modules/projectiles/guns/energy/special.dm
> +		firing_core = null
В оффхенд

2021-11-21 18:25 UTC, KIBORG04 commented on code/modules/projectiles/guns/energy/special.dm
> +/obj/item/weapon/gun/energy/gun/portal/proc/create_portal(obj/item/projectile/beam/wormhole/orange/W, turf/target)
Потому что бьонд динамически типизированный язык, который пытается косить по статическую типизацию

2021-11-21 18:28 UTC, Sakuya-Izayoi commented on code/modules/projectiles/guns/energy/special.dm
> +/obj/item/weapon/gun/energy/gun/portal/proc/create_portal(obj/item/projectile/beam/wormhole/orange/W, turf/target)
Так бывает.

2021-11-21 18:32 UTC, Sakuya-Izayoi commented on code/modules/projectiles/projectile/special.dm
> +	P.create_portal(src, get_turf(src))
Было бы круто наверное если бы портал создавался под таргетом и неанкореды сразу же в этот портал проваливались. Типа как в игре портал стреляешь под куб и он залазит в портал.

2021-11-21 18:34 UTC, AndroBetel commented on code/modules/projectiles/guns/energy/special.dm
> +		firing_core = null
Ты в одной руке держишь пушку, в другой отвертку.

2021-11-21 18:35 UTC, AndroBetel commented on code/modules/projectiles/guns/energy/special.dm
> +/obj/item/weapon/gun/energy/gun/portal/proc/create_portal(obj/item/projectile/beam/wormhole/orange/W, turf/target)
И че сделать надо.

2021-11-21 18:35 UTC, Sakuya-Izayoi commented on code/modules/projectiles/guns/energy/special.dm
> +/obj/item/weapon/gun/energy/gun/portal/proc/create_portal(obj/item/projectile/beam/wormhole/orange/W, turf/target)
Убрать оранг

2021-11-21 18:36 UTC, AndroBetel commented on code/modules/projectiles/projectile/special.dm
> +	P.create_portal(src, get_turf(src))
Слишком имбово, один портал в шпесс, другой под офицерика и минус космонавт.

2021-11-21 18:36 UTC, AndroBetel commented on code/modules/projectiles/projectile/special.dm
> +	P.create_portal(src, get_turf(src))
А лучше не в шпесс, а в камеру сгорания в токсинах, благо, у учёных туда доступ есть.

2021-11-21 18:37 UTC, AndroBetel commented on code/modules/projectiles/guns/energy/special.dm
> +/obj/item/weapon/gun/energy/gun/portal/proc/create_portal(obj/item/projectile/beam/wormhole/orange/W, turf/target)
Ой блин.

2021-11-21 18:42 UTC, Sakuya-Izayoi commented on code/modules/projectiles/projectile/special.dm
> +	P.create_portal(src, get_turf(src))
Лол, я так и хотел. А вообще ящики в карго так тпшить. Кстати, про карго, у нас пофиксили перевоз порталов на шаттлах?

2021-11-21 18:42 UTC, AndroBetel commented on code/modules/projectiles/projectile/special.dm
> +	P.create_portal(src, get_turf(src))
Хм.

2021-11-21 18:51 UTC, AndroBetel commented on code/modules/projectiles/projectile/special.dm
> +	P.create_portal(src, get_turf(src))
Не пофиксили.

2021-11-21 19:09 UTC, AndroBetel commented
Изменил механ проверки того, что там отправлять можно на шаттле и добавил в список порталус.

2021-11-21 19:27 UTC, Sakuya-Izayoi commented on code/controllers/subsystem/shuttles.dm
> +	if(is_type_in_list(A, forbidden_cargo_types))
Вот только есть одна проблема, если учёный любым способом создаст портал на шаттле, каргомены ничего не смогут с этим поделать. Я бы просто либо делитил портал, либо оставлял его на том же месте при муве шаттла. И вообще, наверное, это в другом пре нужно.

2021-11-21 19:29 UTC, Sakuya-Izayoi commented on code/modules/projectiles/guns/energy/special.dm
> +		firing_core = null
А если на земле пушка?

2021-11-21 19:34 UTC, AndroBetel commented on code/controllers/subsystem/shuttles.dm
> +	if(is_type_in_list(A, forbidden_cargo_types))
Портал исчезает через какое-то время, он не вечно стоит.

2021-11-21 19:59 UTC, Sakuya-Izayoi commented on code/controllers/subsystem/shuttles.dm
> +	if(is_type_in_list(A, forbidden_cargo_types))
Ты в список добавил вообще любой портал. Это может быть и портал теленауки, например

2021-11-21 20:00 UTC, AndroBetel commented on code/controllers/subsystem/shuttles.dm
> +	if(is_type_in_list(A, forbidden_cargo_types))
Ты прав, а чё щас делать...

2021-11-21 21:02 UTC, Sakuya-Izayoi commented on code/controllers/subsystem/shuttles.dm
> +	if(is_type_in_list(A, forbidden_cargo_types))
Щас ничо, но в ближайшем будущем сделай пр решающий вышеописанную проблему. Или кто-нить другой сделает, афаик у нас даже ишью где-то висит.

2021-11-22 18:58 UTC, Sakuya-Izayoi commented on code/controllers/subsystem/shuttles.dm
> +	if(is_type_in_list(A, forbidden_cargo_types))
короче это в другом пре пофиксят можешь не париться

2021-11-22 19:01 UTC, AndroBetel commented on code/controllers/subsystem/shuttles.dm
> +	if(is_type_in_list(A, forbidden_cargo_types))
Мерж тогда давай.

2021-11-22 20:54 UTC, Sakuya-Izayoi commented on code/controllers/subsystem/shuttles.dm
> +	if(is_type_in_list(A, forbidden_cargo_types))
так ревертни алло

2021-11-23 00:09 UTC, Sakuya-Izayoi requested changes
добавь какое-нибудь поведение для не-100 релаябилити.

2021-11-23 08:49 UTC, AndroBetel commented
Сделол.

2021-11-23 09:31 UTC, Sakuya-Izayoi approved these changes

2021-11-23 21:51 UTC, KIBORG04 commented on code/modules/projectiles/guns/energy/special.dm
> +	return ..()
Перенеси дестрой сразу под объявление класса.

2021-11-23 21:52 UTC, KIBORG04 commented
![image](https://user-images.githubusercontent.com/26389417/143134955-ccb578be-8141-438f-a0c9-53421c973d32.png)

почему портал синий, а портал100 серый??????

2021-11-23 21:55 UTC, AndroBetel commented
Спрайт для мапы.

2021-11-24 08:33 UTC, AndroBetel commented
Всё можно мержить.

2021-11-24 13:59 UTC, AndroBetel commented
@KIBORG04

2021-11-24 22:55 UTC, KIBORG04 commented
мержа не будет

2021-11-24 22:55 UTC, KIBORG04 reviewed
мержа не будет

2021-11-25 13:23 UTC, KIBORG04 commented on code/game/objects/effects/portals.dm
> +	set waitfor = 0
откуда скопировал признавайся

2021-11-25 13:24 UTC, Sakuya-Izayoi requested changes

2021-11-25 13:24 UTC, Sakuya-Izayoi commented on code/game/objects/effects/portals.dm
> +	teleport(AM, TELE_CHECK_ALL, TRUE, FALSE)
а нах одно и то же писать в двух разных проках? написал один прок и навесил два сигнала

2021-11-25 13:24 UTC, kalazus commented on code/game/objects/effects/portals.dm
> +	set waitfor = 0
4 строчки выше?

2021-11-25 13:31 UTC, kalazus commented on code/game/objects/effects/portals.dm
> +	teleport(AM, TELE_CHECK_ALL, TRUE, FALSE)
Я могу всё понять, но использовать сигналы, где можно легко обойтись без них... Этого я понять не могу. Максиму что можно сделать чтобы уменьшить копипасту (3 строк, гигантская копипаска), это засунуть все флаги телепортации в объект.

2021-11-26 22:59 UTC, KIBORG04 commented
гетуп, аппрувай и мерж

2021-11-27 11:25 UTC, Sakuya-Izayoi commented
Надо потестить

2021-11-27 19:26 UTC, Sakuya-Izayoi approved these changes

2021-11-27 19:30 UTC, merged