Новые папки
TauCetiStation/TauCetiClassic pull request #8248
Opened 2021-11-19 22:43 UTC by Smalltasty

## Описание изменений
Добавлены новые облики для папочек! Теперь розовые! Лучше один раз увидеть, чем сто раз прочитать! 
![image](https://user-images.githubusercontent.com/12589405/142699924-a36c1d99-00dc-4cad-b39d-1e8793438e95.png)
![image](https://user-images.githubusercontent.com/12589405/142699999-3f3356ff-bceb-4f10-800e-01f4d9433c3e.png)
И пусть теперь никто не почувствует себя ущемлённым!
## Почему и что этот ПР улучшит
Учёные-эстеты плакали, ведь красивые фиолетовые папочки были только на аванпосте. Слёз станет меньше, ведь теперь фиолетовые папочки можно крафтить! 
Также теперь желтая папка более жёлтая, а прежняя стала немного темней и называется коричневой. 
## Авторство
Smalltasty
## Чеинжлог
:cl: Smalltasty
- image: Добавлены новые цвета папок 
- rscadd: Папки обновленных цветов добавлены в крафт.

2021-11-19 22:43 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2021-11-19 22:45 UTC, KIBORG04 commented
![image](https://user-images.githubusercontent.com/26389417/142700700-b0dba5f3-1d45-4a08-8e1a-ed86d5923789.png)

Принтеров и едаггеров быть не должно

2021-11-19 22:47 UTC, KIBORG04 approved these changes
Код ок, не должен что-либо сломать

2021-11-20 12:19 UTC, KIBORG04 commented
Зачем блин на такие пры звать спрайтеров... 
А еще, удав вроде не против

2021-11-20 14:06 UTC, UDaV73rus requested changes
Розовая папочка слишком смешная

2021-11-22 15:22 UTC, LudwigVonChesterfield commented on code/modules/paperwork/folders.dm
> +/obj/item/weapon/folder/green
когда-нибудь вместо десяти тысяч предмето красить будем кодом

видимо не сегодня

2021-11-22 17:28 UTC, Sakuya-Izayoi commented on code/modules/paperwork/folders.dm
> +/obj/item/weapon/folder/green
Когда напишешь общий для всех спрайтов алгоритм выбора цветов, тогда и будем красить кодом

2021-11-25 06:04 UTC, Sakuya-Izayoi requested changes
поменяй на карте желтые папочки на коричневые

ну и наверное удав хочет чтобы розовая папочка была менее смешная, сама решишь что с ней делать

2021-11-29 13:52 UTC, Smalltasty commented
Теперь розовая папочка не смешная 
![image](https://user-images.githubusercontent.com/12589405/143879971-35323e3a-a11e-479b-8268-84e7610e1e05.png)

2021-11-29 15:12 UTC, UDaV73rus approved these changes
;(

2021-11-29 15:34 UTC, Sakuya-Izayoi approved these changes

2021-11-29 15:36 UTC, merged