Return 1,0 -> Return TRUE,FALSE (2)
TauCetiStation/TauCetiClassic pull request #8254
Opened 2021-11-20 14:14 UTC by FoLZer

## Описание изменений
#6742 (return TRUE, FALSE)
Данный ПР меняет только данные папки:
- code/controllers
- code/datums
- code/defines
- maps
## Почему и что этот ПР улучшит

## Авторство

## Чеинжлог

2021-11-20 14:14 UTC, TauKitty commented
###### Changelog status: :radio_button: No changelog

2021-11-20 14:25 UTC, LudwigVonChesterfield commented on code/controllers/master.dm
> +		if (SS.can_fire <= FALSE)
Увидев это надо задуматься. А может у can_fire может быть не только TRUE FALSE значения?

2021-11-20 14:25 UTC, LudwigVonChesterfield commented on code/controllers/master.dm
> +		if (SS.can_fire <= FALSE)
(тут скорее надо просто if (!SS.can_fire)

2021-11-20 14:26 UTC, LudwigVonChesterfield commented on code/controllers/subsystem.dm
> +	if(can_fire)
тут ты почему-то убираешь пробелы, а в прошлом файлике нет

погоды это ни так ни так не делает - но увеличивает количество изменений в ПР-ах

2021-11-20 14:27 UTC, FoLZer commented on code/controllers/master.dm
> +		if (SS.can_fire <= FALSE)
Там где он сейчас используется - только TRUE и FALSE, кроме 0 и 1 больше не сетается ни на что. Я бы тут подумал что это сделано для оптимизации или ловли странных ошибок, но оооочень наврятли.

2021-11-20 14:27 UTC, FoLZer commented on code/controllers/subsystem.dm
> +	if(can_fire)
Ну так то да, просто когда смотрел было неприятно видеть такое

2021-11-20 14:28 UTC, FoLZer commented
Надо ещё с тестами разобраться, поломались полностью.

2021-11-20 14:29 UTC, LudwigVonChesterfield commented on code/controllers/subsystem/demo.dm
> +		appearance:invisibility == INVISIBILITY_NONE ? "" : appearance:invisibility, // colon because dreamchecker is dumb
(вот тут выскочил недостаток того что у тебя половина изменения в одном ПР-е, половина в другом

если бы ты сначала сфокусировался на булевых значениях, а потом шёл фиксить другие дефайны такого бы не было)

2021-11-20 14:29 UTC, LudwigVonChesterfield commented
Тесты поломались как результат того что ты дефайнишь нужный этому ПР-у дефайн в другом :)

2021-11-20 14:29 UTC, FoLZer commented on code/controllers/subsystem/demo.dm
> +		appearance:invisibility == INVISIBILITY_NONE ? "" : appearance:invisibility, // colon because dreamchecker is dumb
И то правда.

2021-11-20 14:30 UTC, FoLZer commented
Заметил, теперь так будет каждый ПР ломаться до мержа самого первого.

2021-11-20 14:33 UTC, LudwigVonChesterfield commented on code/datums/helper_datums/construction_datum.dm
> +	return FALSE
Но тут выше возвращает не TRUE, а количество шагов. Возможно тут логичней было бы возвращать таки 0

(А функцию переименовать в get_steps :shrug:

2021-11-20 14:33 UTC, LudwigVonChesterfield commented on code/datums/helper_datums/events.dm
> +// Returns: TRUE if event cleared, null on error
боже мой почему оно возвращает null on error но TRUE if eent cleared а не тру фолз,..

2021-11-20 14:34 UTC, LudwigVonChesterfield commented on code/datums/helper_datums/events.dm
>  	return
Строкой выше ты добавил ТРУ, но тут ты не добавил ФОЛЗ, почему?

2021-11-20 14:35 UTC, FoLZer commented on code/datums/helper_datums/construction_datum.dm
> +	return FALSE
![image](https://user-images.githubusercontent.com/65248062/142730172-8c22be2e-1183-4023-b9fd-34e0cc5b6742.png)
![image](https://user-images.githubusercontent.com/65248062/142730176-662bccbb-6e43-491f-bc9b-2267c04e9f49.png)
Два единственных места употребления данного прока, везде просто проверка в if

2021-11-20 14:36 UTC, FoLZer commented on code/datums/helper_datums/construction_datum.dm
> +	return FALSE
Так что тут наоборот, вроде как всё верно но скорее добавить ещё проверку в if(istype) - if(steps.len)

2021-11-20 14:37 UTC, FoLZer commented on code/datums/helper_datums/events.dm
> +// Returns: TRUE if event cleared, null on error
Не хотелось менять нуль, а так опять же, нигде возвращаемое значение не используется вовсе. По идее должен быть FALSE а не null

2021-11-20 14:37 UTC, LudwigVonChesterfield requested changes

2021-11-20 14:37 UTC, LudwigVonChesterfield commented on maps/centcom/centcom.dmm
> +	invisibility = INVISIBILITY_ABSTRACT;
!!!

в файлах карты дефайны то не работают, что это тут забыло?

2021-11-20 14:39 UTC, FoLZer commented on maps/centcom/centcom.dmm
> +	invisibility = INVISIBILITY_ABSTRACT;
А, гм, не знал про это. Убираем

2021-11-20 14:47 UTC, FoLZer commented on code/datums/helper_datums/events.dm
> +// Returns: TRUE if event cleared, null on error
Добавил FALSE

2021-11-20 14:47 UTC, FoLZer commented on code/datums/helper_datums/events.dm
>  	return
Добавил FALSE в конце

2021-11-20 14:53 UTC, FoLZer commented on code/datums/helper_datums/construction_datum.dm
> +	return FALSE
Стоп, стоп, тут ты прав был.

2021-11-22 14:41 UTC, FoLZer commented
Первый ПР был замержен, этот ошибок более не создаёт

2021-11-22 14:45 UTC, LudwigVonChesterfield commented on code/controllers/master.dm
> +		if (SS.can_fire <= FALSE)
какой оптимизации?

2021-11-22 14:49 UTC, FoLZer commented on code/controllers/master.dm
> +		if (SS.can_fire <= FALSE)
В других языках иногда <= работает быстрее чем =, без понятия по какой причине. На счёт бионда не знаю, но в любом случае эта штука может принимать только 0 и 1

2021-11-22 14:54 UTC, KIBORG04 commented on code/controllers/master.dm
> +		if (SS.can_fire <= FALSE)
> В других языках иногда <= работает быстрее чем =, без понятия по какой причине.

Такие изменения кардинально не повлияют на работу, даже если они и есть. Поэтому лучше для наглядности просто написать как было предложено выше

2021-11-22 14:55 UTC, FoLZer commented on code/controllers/master.dm
> +		if (SS.can_fire <= FALSE)
Оки, секунду

2021-11-22 14:56 UTC, FoLZer commented on code/controllers/master.dm
> +		if (SS.can_fire <= FALSE)
Поменял

2021-11-22 15:18 UTC, LudwigVonChesterfield approved these changes

2021-11-23 21:21 UTC, KIBORG04 commented on code/controllers/subsystem/jobs.dm
> +		return FALSE
Что вы с людуком решили? Если метод ничего не возвращает, то убираешь ретурны? Но SetupOccupations ничего не возвращает

2021-11-23 21:22 UTC, KIBORG04 commented on code/controllers/subsystem/jobs.dm
> +		return FALSE
Этот метод тоже не используется для ифок

2021-11-23 21:22 UTC, KIBORG04 commented on code/controllers/subsystem/jobs.dm
> +		return TRUE
Этот метод тоже не используется для ифок

2021-11-23 21:23 UTC, KIBORG04 commented on code/controllers/subsystem/jobs.dm
> +	return FALSE
Этот метод тоже не используется для ифок

2021-11-23 21:23 UTC, KIBORG04 commented on code/controllers/subsystem/jobs.dm
> +		return FALSE
Этот метод тоже не используется для ифок

2021-11-23 21:23 UTC, KIBORG04 commented on code/controllers/subsystem/jobs.dm
> +		return FALSE
Этот метод тоже не используется для ифок

2021-11-23 21:24 UTC, KIBORG04 commented on code/controllers/subsystem/jobs.dm
> +	if(!H)	return FALSE
Этот метод тоже не используется для ифок

2021-11-23 21:29 UTC, KIBORG04 commented on code/datums/helper_datums/events.dm
>  	return
Удали оба ретурна. Они все равно ничего не делают

2021-11-23 21:34 UTC, KIBORG04 commented on maps/testmap/job_changes.dm
> +		return FALSE
```suggestion
		return
```

2021-11-23 21:35 UTC, KIBORG04 commented on maps/testmap/job_changes.dm
> +		return FALSE
Здесь прямо очевидно, что метод не должен ничего возвращать. Хотя бы тут убери фолс. В других местах уже слишком не под этот ПР

2021-11-23 21:35 UTC, KIBORG04 commented on code/controllers/subsystem/jobs.dm
> +		return FALSE
Как я понял, в этом ПРе данная тема не затронута

2021-11-25 13:54 UTC, FoLZer commented on code/datums/spells/spacetime_distrortion.dm
> +	return FALSE
По идее самого attackby() - его возвращаемое значение(TRUE или FALSE) определяет будет ли вызываться afterattack(), так что тут наоборот - стоит пройтись мне и добавить везде эти TRUE или FALSE

2021-11-25 14:01 UTC, FoLZer commented on code/datums/spells/spacetime_distrortion.dm
> +	return FALSE
А, ну кстати под рамки именно этой части почти все attackby() не входят, а те что входят уже возвращают то что надо. Главное потом не забыть добавить всё это.

2021-11-25 14:03 UTC, FoLZer commented on code/controllers/subsystem/jobs.dm
> +		return FALSE
Без понятия, остались без ответа. @LudwigVonChesterfield

2021-11-25 16:39 UTC, KIBORG04 commented on code/controllers/subsystem/jobs.dm
> +		return FALSE
Наверное, всё же не стоит это тут трогать

2021-11-25 16:40 UTC, KIBORG04 commented on code/datums/helper_datums/events.dm
>  	return
Удалишь - замержу

2021-11-25 16:40 UTC, KIBORG04 approved these changes

2021-11-26 14:28 UTC, merged