Локализация квирков
TauCetiStation/TauCetiClassic pull request #8268
Opened 2021-11-22 17:36 UTC by bowlofsoup4ik

## Описание изменений

Перевёл квирки и связанные с ними сообщения в чате.

## Почему и что этот ПР улучшит

Медленное, но верное движение в сторону полной локализации билда.

## Авторство

comrade honk#6626

## Чеинжлог

:cl:

- ru: Локализация системы квирков.

2021-11-22 17:36 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2021-11-22 17:54 UTC, Sakuya-Izayoi requested changes

2021-11-22 17:54 UTC, Sakuya-Izayoi commented on code/__DEFINES/quirks.dm
> +#define QUIRK_FREERUNNING "Фриран"
че такое фриран?

2021-11-22 17:54 UTC, Sakuya-Izayoi commented on code/__DEFINES/quirks.dm
> +#define QUIRK_DALTONISM "Дальтонизм"
В любом другом месте ты пишешь каждое слово с большой буквы, тут только первое. надо сделать чтобы везде было одинаково.

2021-11-22 17:54 UTC, Sakuya-Izayoi commented on code/datums/traits/negative.dm
> +	gain_text = "<span class='danger'>Вы не можете прекратить кашлять!</span>"
```suggestion
	gain_text = "<span class='danger'>Вы не можете перестать кашлять!</span>"
```

2021-11-22 17:54 UTC, Sakuya-Izayoi commented on code/datums/traits/positive.dm
> +	lose_text = "<span class='danger'>Вы чувствуете, что растеряли свой талант мультизадачности.</span>"
```suggestion
	lose_text = "<span class='danger'>Вы чувствуете, что растеряли свой талант многозадачности.</span>"
```

2021-11-22 17:54 UTC, Sakuya-Izayoi commented on code/datums/traits/positive.dm
> +	desc = "Вы можете выбирать между правдой и ложью, не оборачиваясь на мораль и эмоции."
просто нет

2021-11-22 17:54 UTC, Sakuya-Izayoi commented on code/datums/traits/positive.dm
> +	gain_text = "<span class='notice'>Ты ощущаешь гибкость своих ног.</span>"
```suggestion
	gain_text = "<span class='notice'>Вы ощущаете гибкость своих ног.</span>"
```

2021-11-22 17:54 UTC, Sakuya-Izayoi commented on code/__DEFINES/quirks.dm
> +#define QUIRK_NYCTOPHOBIA "Боязнь темноты"
Никтофобия звучит поэтичнее на мой взгляд

2021-11-22 17:55 UTC, bowlofsoup4ik commented on code/__DEFINES/quirks.dm
> +#define QUIRK_FREERUNNING "Фриран"
Фриран (англ. Free running — буквально свободный бег) — дисциплина, сходная с паркуром, созданная Себастьяном Фуканом. Это способ самовыражения посредством взаимодействия с различными препятствиями и окружающей средой. Фриран может включать сальто и различные вращение. Эти движения обычно заимствованы из других видов спорта, таких как гимнастика , трикинг, капоэйра или брейк-данс . Фрираннеры могут придумывать свои собственные движения, и применять их в разных ландшафтах. Практикующие фриран также обычно занимаются паркуром .

2021-11-22 17:56 UTC, bowlofsoup4ik commented on code/__DEFINES/quirks.dm
> +#define QUIRK_DALTONISM "Дальтонизм"
поправлю

2021-11-22 17:58 UTC, KIBORG04 commented on code/__DEFINES/quirks.dm
> +#define QUIRK_MULTITASKING "Многозадачность"
Некорректно. При мультитаскинге можно делать только количество_рук действий. Тут скорее будет амбидекстер, но это наверное нужно будет еще что-то менять

2021-11-22 17:59 UTC, KIBORG04 commented on code/__DEFINES/quirks.dm
> +#define QUIRK_DALTONISM "Дальтонизм"
Где-то обсуждали, что Каждое Слово с Большой Буквы это скорее пендосский стиль, а русской аудитории более привычно видеть, где только Первое слово с большой. Поэтому наверное вот. Напишите, если я не прав

2021-11-22 18:01 UTC, KIBORG04 commented on code/__DEFINES/quirks.dm
> +#define QUIRK_TOURETTE "Туретта"
```suggestion
#define QUIRK_TOURETTE "Синдром Туретта"
```

2021-11-22 18:02 UTC, KIBORG04 commented on code/__DEFINES/quirks.dm
> +#define QUIRK_NERVOUS "Нервность"
```suggestion
#define QUIRK_NERVOUS "Нервозность"
```

2021-11-22 18:02 UTC, KIBORG04 commented on code/__DEFINES/quirks.dm
> +#define QUIRK_STRESS_EATER "Нервный Голод"
Тут скорее что-то другое нужно придумать. Название совершенно не описывает поведение трейта

2021-11-22 18:02 UTC, bowlofsoup4ik commented on code/__DEFINES/quirks.dm
> +#define QUIRK_MULTITASKING "Многозадачность"
думаю можно оставить так, пока сам квирк не будет реворкнут

2021-11-22 18:04 UTC, KIBORG04 commented on code/__DEFINES/quirks.dm
> +#define QUIRK_MULTITASKING "Многозадачность"
Что реворкать? Раньше ты одной рукой мог делать миллион действий, щас только 1

2021-11-22 18:05 UTC, KIBORG04 commented on code/__DEFINES/quirks.dm
> +#define QUIRK_LIGHT_DRINKER "Легко Напивающийся"
До этого квирки были переведены в существительное, здесь же прилагательное и выбивается из стиля.

2021-11-22 18:05 UTC, bowlofsoup4ik commented on code/__DEFINES/quirks.dm
> +#define QUIRK_STRESS_EATER "Нервный Голод"
самое лаконичное из того, что я смог придумать. можно более топорно назвать, "Голод от Стресса" например

2021-11-22 18:06 UTC, bowlofsoup4ik commented on code/__DEFINES/quirks.dm
> +#define QUIRK_LIGHT_DRINKER "Легко Напивающийся"
исправил уже, со следующим коммитом исправится

2021-11-22 18:08 UTC, KIBORG04 commented on code/__DEFINES/quirks.dm
> +#define QUIRK_LIGHT_STEP "Грациозность"
Как по мне, легкий шаг точнее описывает квирк, нежели данный вариант. Этот квирк буквально не позволит тебе падать при наступании голой ногой на стекло или кубик, а грациозность же описывает общее качество человека, а не только у ног.

2021-11-22 18:10 UTC, bowlofsoup4ik commented on code/__DEFINES/quirks.dm
> +#define QUIRK_LIGHT_STEP "Грациозность"
поправил

2021-11-22 18:10 UTC, KIBORG04 commented on code/datums/traits/negative.dm
> +	desc = "Вы полностью и неизлечимо глухи."
полностью и неизлечимо, звучит как масло маслянное, но может для меня так

2021-11-22 18:11 UTC, bowlofsoup4ik commented on code/datums/traits/negative.dm
> +	desc = "Вы полностью и неизлечимо глухи."
глухота может быть частичной, стоит уточнить

2021-11-22 18:12 UTC, bowlofsoup4ik commented on code/datums/traits/negative.dm
> +	gain_text = "<span class='danger'>Вы начинаете испытывать припадки!</span>"
добавлю "эпилептические"

2021-11-22 18:12 UTC, KIBORG04 commented on code/datums/traits/negative.dm
> +	lose_text = "<span class='notice'>Кажись вы снова в форме!</span>"
Какой еще `кажись` ? Зачем здесь сленг? Я еще понимаю шуточки, но писать сленгом и так неформально

2021-11-22 18:14 UTC, KIBORG04 commented on code/datums/traits/negative.dm
> +	lose_text = "<span class='notice'>Вы чувствуете облегчение, тики больше вас не побеспокоят.</span>"
Луз_текст звучит как бред и шиза.

2021-11-22 18:14 UTC, KIBORG04 commented on code/datums/traits/negative.dm
> +	lose_text = "<span class='notice'>Вы чувствуете облегчение, тики больше вас не побеспокоят.</span>"
ты напиши про нервные тики или как-то иначе сформулируй. Да и вообще мы вроде как даже хотели луз_текст впринципе удалить из квирков за ненадобностью

2021-11-22 18:15 UTC, bowlofsoup4ik commented on code/datums/traits/negative.dm
> +	lose_text = "<span class='notice'>Кажись вы снова в форме!</span>"
уберу

2021-11-22 18:15 UTC, KIBORG04 commented on code/datums/traits/negative.dm
> +	gain_text = "<span class='danger'>Вы все на нервах.</span>"
Кто вы все? Кто вы ВСЕ??

2021-11-22 18:16 UTC, KIBORG04 commented on code/datums/traits/negative.dm
> +	gain_text = "<span class='danger'>Когда вам больно вы чувствуете неутолимый голод.</span>"
```suggestion
	gain_text = "<span class='danger'>Когда вам больно, вы чувствуете неутолимый голод.</span>"
```
Вроде запятая пропущена.

2021-11-22 18:18 UTC, KIBORG04 commented on code/datums/traits/negative.dm
> +	lose_text = "<span class='notice'>Ваш голосовой аппарат, похоже, снова исправен.</span>"
Давай без `похоже`. Я лично не думаю, что в таких текстах нужны вводные слова

2021-11-22 18:20 UTC, KIBORG04 commented on code/datums/traits/neutral.dm
> +	gain_text = "<span class='danger'>Вы хотите показать, насколько вы сильны. Вы попытаетесь игнорировать любую боль.</span>"
```suggestion
	gain_text = "<span class='danger'>Вы хотите показать насколько вы сильны. Вы попытаетесь игнорировать любую боль.</span>"
```
Я не уверен, что она там нужна. Как думаешь?

2021-11-22 18:21 UTC, bowlofsoup4ik commented on code/datums/traits/negative.dm
> +	lose_text = "<span class='notice'>Ваш голосовой аппарат, похоже, снова исправен.</span>"
в оригинале используется словосочетания "appears to be" ("по видимому", "похоже" и т.д.)

2021-11-22 18:22 UTC, KIBORG04 commented on code/datums/traits/neutral.dm
> +	desc = "Всё для вас одинаково пресно на вкус! Токсичная еда остаётся отравной для вас."
`отравной` - гугл выдает, что слово устаревшее. Даже на слух звучит как-то неестественно. Как-то напиши красивее

2021-11-22 18:23 UTC, bowlofsoup4ik commented on code/datums/traits/neutral.dm
> +	gain_text = "<span class='danger'>Вы хотите показать, насколько вы сильны. Вы попытаетесь игнорировать любую боль.</span>"
да, нужна, это местоименное наречие

2021-11-22 18:23 UTC, KIBORG04 commented on code/datums/traits/positive.dm
> +	desc = "Вы едины с природой. Животные не атакуют вас, если вы разденетесь догола."
```suggestion
	desc = "Вы едины с природой. Животные не будут атаковать вас, если вы разденетесь догола."
```
Как по мне, мой вариант звучит лучше.

2021-11-22 18:23 UTC, KIBORG04 commented on code/datums/traits/positive.dm
> +	lose_text = "<span class='danger'>Кажись, ваша связь с природой нарушена.</span>"
Без кажись

2021-11-22 18:24 UTC, bowlofsoup4ik commented on code/datums/traits/neutral.dm
> +	desc = "Всё для вас одинаково пресно на вкус! Токсичная еда остаётся отравной для вас."
сейчас что-то придумаю

2021-11-22 18:24 UTC, KIBORG04 commented on code/datums/traits/positive.dm
> +	desc = "Вы можете выбирать между правдой и ложью, не оборачиваясь на мораль и эмоции."
квирк просто запрещает галюны видеть, как в чате, так и в мире

2021-11-22 18:25 UTC, bowlofsoup4ik commented on code/datums/traits/positive.dm
> +	desc = "Вы едины с природой. Животные не атакуют вас, если вы разденетесь догола."
да, есть такое

2021-11-22 18:26 UTC, KIBORG04 commented on code/datums/traits/positive.dm
> +	desc = "Вы ходите аккуратно и грациозно, издавая меньше шума и никогда не наступая в лужи крови или грязи."
Лол, этот квирк не влияет на громкость ходьбы

2021-11-22 18:26 UTC, AndroBetel commented on code/datums/traits/positive.dm
> +	desc = "Вы ходите аккуратно и грациозно, издавая меньше шума и никогда не наступая в лужи крови или грязи."
Там когда наступаешь на стекло звук громкий, вполне подходит ИМХО.

2021-11-22 18:27 UTC, bowlofsoup4ik commented on code/datums/traits/positive.dm
> +	desc = "Вы ходите аккуратно и грациозно, издавая меньше шума и никогда не наступая в лужи крови или грязи."
при наступании на различные осколки и шрапнель не издается звук

2021-11-22 18:27 UTC, bowlofsoup4ik commented on code/datums/traits/positive.dm
> +	desc = "Вы ходите аккуратно и грациозно, издавая меньше шума и никогда не наступая в лужи крови или грязи."
но сформулировал я странно, пофикшу

2021-11-22 18:27 UTC, KIBORG04 commented on code/datums/traits/negative.dm
> +	lose_text = "<span class='notice'>Ваш голосовой аппарат, похоже, снова исправен.</span>"
Много где оригинал даже не учитывался.

2021-11-22 18:33 UTC, KIBORG04 commented on code/datums/traits/neutral.dm
> +	lose_text = "<span class='notice'>Вы устали терпеть боль, теперь она пугает Вас.</span>"
Почему здесь Вас с большой буквы, а в других местах Вы-Вас с маленькой?

2021-11-22 18:35 UTC, bowlofsoup4ik commented on code/datums/traits/neutral.dm
> +	lose_text = "<span class='notice'>Вы устали терпеть боль, теперь она пугает Вас.</span>"
уже пофиксил

2021-11-22 18:40 UTC, KIBORG04 commented
> comrade honk#6626

У тебя чейнджлоге будут указан ник с гитхаба, а не вот этот вот дискордный ник. Для другого имени напиши после :cl: ник

2021-11-22 18:41 UTC, bowlofsoup4ik commented on code/datums/traits/neutral.dm
> +	desc = "Всё для вас одинаково пресно на вкус! Токсичная еда остаётся отравной для вас."
поправил на "ядовитой"

2021-11-22 18:41 UTC, bowlofsoup4ik commented on code/datums/traits/positive.dm
> +	lose_text = "<span class='danger'>Кажись, ваша связь с природой нарушена.</span>"
убрал

2021-11-22 18:46 UTC, bowlofsoup4ik commented on code/datums/traits/negative.dm
> +	gain_text = "<span class='danger'>Когда вам больно вы чувствуете неутолимый голод.</span>"
поставил

2021-11-22 18:49 UTC, bowlofsoup4ik commented on code/datums/traits/negative.dm
> +	lose_text = "<span class='notice'>Вы чувствуете облегчение, тики больше вас не побеспокоят.</span>"
поменял на простенькое "вас перестает трясти"

2021-11-22 18:52 UTC, bowlofsoup4ik commented
та пусть будет ник из гита, серавно

2021-11-22 18:55 UTC, Lexakr requested changes

2021-11-22 18:55 UTC, Lexakr commented on code/datums/traits/negative.dm
> +	desc = "Вы, мягко скажем, полноваты."
Ваше ожирение не лечится.

2021-11-22 18:55 UTC, Lexakr commented on code/datums/traits/negative.dm
> +	lose_text = "<span class='notice'>Кажись вы снова в форме!</span>"
Вы снова в форме!

2021-11-22 18:55 UTC, Lexakr commented on code/datums/traits/negative.dm
> +	lose_text = "<span class='notice'>Вы чувствуете облегчение, тики больше вас не побеспокоят.</span>"
Вы чувствуете облегчение, нервный тик вас больше не беспокоит.

2021-11-22 18:55 UTC, Lexakr commented on code/datums/traits/negative.dm
> +	desc = "Вы плохо видите без очков, однако появляетесь с парой таковых."
У вас близорукость, но вы появляетесь с очками.

2021-11-22 18:55 UTC, Lexakr commented on code/datums/traits/negative.dm
> +	gain_text = "<span class='danger'>Всё на расстоянии от вас выглядит размыто.</span>"
Вещи, находящиеся вдалеке, начинают выглядеть размыто.

2021-11-22 18:55 UTC, Lexakr commented on code/datums/traits/negative.dm
> +	desc = "Вы постоянно на взводе."
Вы постоянно нервничаете

2021-11-22 18:55 UTC, Lexakr commented on code/datums/traits/negative.dm
> +	gain_text = "<span class='danger'>Вы все на нервах.</span>"
Вы нервничаете!

2021-11-22 18:55 UTC, Lexakr commented on code/datums/traits/negative.dm
> +	lose_text = "<span class='notice'>Вы чувствуете себя более расслабленно.</span>"
Вы меньше нервничаете

2021-11-22 18:55 UTC, Lexakr commented on code/datums/traits/negative.dm
> +	desc = "Когда вы испытываете боль, ваш голод усиливается."
Вы заедаете боль

2021-11-22 18:55 UTC, Lexakr commented on code/datums/traits/negative.dm
> +	gain_text = "<span class='danger'>Когда вам больно вы чувствуете неутолимый голод.</span>"
Когда вам больно, вы чувствуете неутолимый голод

2021-11-22 18:55 UTC, Lexakr commented on code/datums/traits/negative.dm
> +	gain_text = "<span class='danger'>Голосовой аппарат ощущается странновато.</span>"
Вы оглохли.

2021-11-22 18:55 UTC, Lexakr commented on code/datums/traits/negative.dm
> +	lose_text = "<span class='notice'>Ваш голосовой аппарат, похоже, снова исправен.</span>"
Вы снова слышите.

2021-11-22 18:55 UTC, Lexakr commented on code/datums/traits/negative.dm
> +	gain_text = "<span class='danger'>От одной лишь мысли об алкоголе у вас кружится голова.</span>"
У вас кружится голова от одной лишь мысли об алкоголе.

2021-11-22 18:55 UTC, Lexakr commented on code/datums/traits/negative.dm
> +	lose_text = "<span class='notice'>Вас больше не коробит от алкоголя.</span>"
У вас больше нет высокой чувствительности к алкоголю.

2021-11-22 18:55 UTC, Lexakr commented on code/datums/traits/negative.dm
> +	desc = "Всю вашу жизнь вас преследовал страх темноты. Ныряя во тьму вы инстинктивно настораживаетесь и действуете с осторожностью, познавая настоящий страх. Лишь источник света способен помочь вам."
Всю вашу жизнь вы боялись темноты. Находясь в темноте без света, вы инстинктивно ведете себя осторожно и постоянно испытываете чувство страха.

2021-11-22 18:55 UTC, Lexakr commented on code/datums/traits/negative.dm
> +	gain_text = "<span class='notice'>Даже от мимолётной мысли о пребывании в темноте вас бросает в холодный пот.</span>"
Даже сама мысль о том, что вы находитесь в темноте, заставляет вас дрожать.

2021-11-22 18:55 UTC, Lexakr commented on code/datums/traits/negative.dm
> +	lose_text = "<span class='notice'>Темнота больше не пугает вас!</span>"
Вы больше не боитесь темноты!

2021-11-22 18:55 UTC, Lexakr commented on code/datums/traits/negative.dm
> +	to_chat(quirk_holder, "<span class='warning'>Тише, тише, успокойся, дружище... Это всего-лишь темнота...</span>")
Тише, тише, не торопись... Ты в темноте...

2021-11-22 18:55 UTC, Lexakr commented on code/datums/traits/negative.dm
> +	desc = "Ужасная генетическая болезнь делает невозможной искусственную реконструкцию вашего ДНК."
Неизлечимое генетическое заболевание делает невозможным искусственное восстановление вашего ДНК.

2021-11-22 18:55 UTC, Lexakr commented on code/datums/traits/neutral.dm
> +	desc = "Вы легче переносите боль. Эта особенность влияет лишь на звуки, издаваемые вами."
Ваш болевой порог повышен. Влияет только на издаваемые вами звуки.

2021-11-22 18:55 UTC, Lexakr commented on code/datums/traits/neutral.dm
> +	gain_text = "<span class='danger'>Вы хотите показать, насколько вы сильны. Вы попытаетесь игнорировать любую боль.</span>"
Вы хотите показать свою силу. Вы попытаетесь игнорировать любую боль.

2021-11-22 18:55 UTC, Lexakr commented on code/datums/traits/neutral.dm
> +	lose_text = "<span class='notice'>Вы устали терпеть боль, теперь она пугает Вас.</span>"
Вы больше не хотите превозмогать боль.

2021-11-22 18:55 UTC, Lexakr commented on code/datums/traits/neutral.dm
> +	desc = "Боль для вас более мучительна. Эта особенность влияет лишь на звуки, издаваемые вами. "
Ваш болевой порог понижен. Влияет только на издаваемые вами звуки.

2021-11-22 18:55 UTC, Lexakr commented on code/datums/traits/neutral.dm
> +	gain_text = "<span class='danger'>От одной лишь мысли о боли вас начинает трясти от страха.</span>"
Вам страшно от одной лишь мысли о боли.

2021-11-22 18:55 UTC, Lexakr commented on code/datums/traits/neutral.dm
> +	lose_text = "<span class='notice'>Вы больше не хотите казаться слизняком в глазах окружающих. Теперь вы будете пытаться игнорировать боль.</span>"
Вы больше не хотите выглядеть слабаком. Теперь вы пытаетесь терпеть боль.

2021-11-22 18:55 UTC, Lexakr commented on code/datums/traits/neutral.dm
> +	desc = "Всё для вас одинаково пресно на вкус! Токсичная еда остаётся отравной для вас."
Вы полностью потеряли вкус! Отравленная еда все равно вредит вам.

2021-11-22 18:55 UTC, Lexakr commented on code/datums/traits/neutral.dm
> +	gain_text = "<span class='notice'>Вы потеряли вкус!</span>"
Вы не различаете вкуса еды

2021-11-22 18:55 UTC, Lexakr commented on code/datums/traits/neutral.dm
> +	lose_text = "<span class='notice'>Вы снова можете насладиться красками этого мира!</span>"
Вы снова различаете цвета!

2021-11-22 18:55 UTC, Lexakr commented on code/datums/traits/neutral.dm
> +		"Фиолетовый-красный"      = "grb_d",
Здесь и выше везде надо уточнить смысл (в коде), ведь Yellow-Blue это и желто-синий и желто-голубой и Желтый, синий

2021-11-22 18:55 UTC, Lexakr commented on code/datums/traits/positive.dm
> +	desc = "Вы ходите аккуратно и грациозно, издавая меньше шума и никогда не наступая в лужи крови или грязи."
Вы ходите осторожно, не наступая на острые предметы или кровь. 
По-моему дословный перевод звучит нормально

2021-11-22 19:00 UTC, bowlofsoup4ik commented on code/__DEFINES/quirks.dm
> +#define QUIRK_SEIZURES "Эпилепсия"
в билде названо эпилепсией вроде

2021-11-22 19:00 UTC, bowlofsoup4ik commented on code/__DEFINES/quirks.dm
> +#define QUIRK_AGEUSIA "Утрата вкуса"
переименую

2021-11-22 19:01 UTC, bowlofsoup4ik commented on code/datums/traits/negative.dm
> +	gain_text = "<span class='danger'>Эй, кто выключил свет?</span>"
свет забавнее звучит

2021-11-22 19:01 UTC, bowlofsoup4ik commented on code/datums/traits/negative.dm
> +	desc = "Вы абсолютно слепы."
поправлю, я там изначально криво написал просто и убрал

2021-11-22 19:02 UTC, bowlofsoup4ik commented on code/datums/traits/negative.dm
> +	lose_text = "<span class='notice'>Кажись вы снова в форме!</span>"
уже поменял

2021-11-22 19:02 UTC, bowlofsoup4ik commented on code/datums/traits/negative.dm
> +	desc = "У вас неизлечимые нервные тики."
вроде должно быть в множественном

2021-11-22 19:03 UTC, bowlofsoup4ik commented on code/datums/traits/negative.dm
> +	desc = "Вы плохо видите без очков, однако появляетесь с парой таковых."
звучит как гугл переводчик, слишком прямой перевод. тебе не кажется что стоит переводить не настолько дословно?

2021-11-22 19:04 UTC, bowlofsoup4ik commented on code/datums/traits/negative.dm
> +	desc = "Вы постоянно на взводе."
слишком прямо

2021-11-23 07:53 UTC, DenchikPozhiloyTranslator commented on code/datums/traits/positive.dm
> +	lose_text = "<span class='danger'>Вы чувствуете, что растеряли свой талант мультизадачности.</span>"
блин что то я вот внезапно растерял свой талант многозадачности жесть...

2021-11-23 21:39 UTC, KIBORG04 commented on code/__DEFINES/quirks.dm
> +#define QUIRK_STRESS_EATER "Голод из-за Стресса"
Нашел прикольный термин `Компульсивное Переедание`. Звучит классно и вроде как означает то че надо.

2021-11-23 21:42 UTC, KIBORG04 commented on code/datums/traits/negative.dm
> +	lose_text = "<span class='notice'>Вы перестали чувствовать голод, испытывая боль.</span>"
В английской версии было про неутолимый голод. У тебя же, будто ты впринципе перестал чувствовать голод при боли, а не безмерное чувство голода

2021-11-23 21:46 UTC, KIBORG04 commented on code/datums/traits/positive.dm
> +	gain_text = "<span class='notice'>Вы чувствуете уверенность в ловкости своих рук.</span>"
Уверенность в ловкости рук НЕ РАВНО синхронное выполнение действий обеими руками

2021-11-23 21:47 UTC, KIBORG04 commented on code/datums/traits/positive.dm
> +	lose_text = "<span class='danger'>Вы чувствуете, что растеряли свой талант многозадачности.</span>"
Своих рук, свой талант. Зачем писать, что это касается тебя? Очевидно же, что не васи

2021-11-23 21:48 UTC, KIBORG04 approved these changes

2021-11-25 04:08 UTC, Sakuya-Izayoi approved these changes

2021-11-25 04:11 UTC, merged

2022-04-12 09:44 UTC, volas commented on code/datums/traits/negative.dm
> +	desc = "Вы плохо видите без очков, однако появляетесь с парой таковых."
с парой стекол != с парой очков...

2022-04-12 09:46 UTC, volas commented on code/datums/traits/negative.dm
> +	gain_text = "<span class='danger'>Голосовой аппарат ощущается странновато.</span>"
ну и резолвить чужие комментарии так себе, теперь это всё кому-то исправлять

2022-04-23 15:39 UTC, RogverSnott commented on code/datums/traits/negative.dm
> +	desc = "У вас неизлечимый хронический кашель."
Может просто хронический кашель? Вылечить нельзя, смириться.

2022-04-23 15:45 UTC, RogverSnott commented on code/datums/traits/negative.dm
> +	desc = "У вас неизлечимые нервные тики."
Нервный тик, как медицинское значение

2022-04-23 16:07 UTC, LudwigVonChesterfield commented on code/datums/traits/negative.dm
> +	desc = "У вас неизлечимый хронический кашель."
вовремя ты