Рефактор двуручной компоненты
TauCetiStation/TauCetiClassic pull request #8270
Opened 2021-11-23 03:54 UTC by Sakuya-Izayoi

## Описание изменений
В попытке добавить новый двуручный предмет испытал некоторые проблемы, поэтому решил немного отрефакторить код двуручной компоненты перед этим.

1. Датум для передачи аргументов в АддКомпонент. Так уже поступили однажды со свайпабл компонентой. В будущем, наверное, нам было бы неплохо заиметь неймед аргументы (как у АддЭлементов, но там свои нюансы с дефайнами).
2. Убрал wielded переменную у различных объектов. Ей на замену пришел трейт TRAIT_DOUBLE_WIELDED.
3. Убрал сигналы при уилде/ануилде. Киборг мне говорил, что парент про компоненту ничего знать не должен, поэтому таких сигналов быть не должно. Им на замену сделал передаваемые в качестве аргументов колбэки.

## Почему и что этот ПР улучшит
Рефактор, фикс бага

## Авторство

## Чеинжлог
:cl: Getup1
- fix: Кувалда снова может ломать камень на астероиде.

2021-11-23 03:54 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2021-11-23 21:54 UTC, KIBORG04 commented on code/datums/components/twohanded.dm
> +		TCB = new
```suggestion
	if(!TCB)
		return COMPONENT_INCOMPATIBLE
```
А нафиг создавать пустой сеттер? В идеале кидать в лицо программисту ошибки, что он лох

2021-11-23 21:55 UTC, KIBORG04 commented on code/datums/components/twohanded.dm
> +		TCB = new
а, да, COMPONENT_INCOMPATIBLE же и будет кидать ошибки*

2021-11-23 21:56 UTC, KIBORG04 commented on code/datums/components/twohanded.dm
> +	. = ..()
```suggestion
	return ..()
```

2021-11-23 21:56 UTC, KIBORG04 commented on code/datums/components/twohanded.dm
> +		return
Если на этапе инициализации отсеивать компоненты без TCB, то здесь не нужно

2021-11-23 22:02 UTC, KIBORG04 commented on code/game/objects/items/weapons/twohanded.dm
> +/obj/item/weapon/dualsaber/proc/on_wield()
![image](https://user-images.githubusercontent.com/26389417/143136134-bba999d9-9491-49f2-adf4-9da1e9004b30.png)

Ты должен что-то возвращать

2021-11-23 22:02 UTC, KIBORG04 commented on code/game/objects/items/weapons/twohanded.dm
> +/obj/item/weapon/dualsaber/proc/on_wield()
Довольно странно, что механ коллбэков убирает добавление трейтов и другой код

2021-11-24 01:29 UTC, Sakuya-Izayoi commented on code/datums/components/twohanded.dm
> +		TCB = new
> нафиг создавать пустой сеттер

Это было бы аналогично вызову прока со всеми стандартными аргументами.

2021-11-24 01:30 UTC, Sakuya-Izayoi commented on code/game/objects/items/weapons/twohanded.dm
> +/obj/item/weapon/dualsaber/proc/on_wield()
> Довольно странно, что механ коллбэков убирает добавление трейтов и другой код

всм

2021-11-24 23:17 UTC, KIBORG04 commented on code/game/objects/items/weapons/twohanded.dm
> +/obj/item/weapon/dualsaber/proc/on_wield()
Если коллбэк вернет ФОЛС (ложь, не правду), то весь механ ниже уйдет, а компонента без этого механа сломается. Как тебе идея либо убрать здесь ифку, либо ретурнить код при фолсе.
![image](https://user-images.githubusercontent.com/26389417/143324436-98a933da-4163-4181-b07c-2762431b0432.png)

2021-11-25 02:33 UTC, Sakuya-Izayoi commented on code/game/objects/items/weapons/twohanded.dm
> +/obj/item/weapon/dualsaber/proc/on_wield()
Но ведь до этого с сигналом похожая история была. Если сигнал возвращал 1, то вилдинг не происходил, если 0, то происходил.

2021-11-25 09:30 UTC, LudwigVonChesterfield commented on code/datums/components/twohanded.dm
> +	var/datum/callback/on_wield = null
вот этот тренд начал я, и возможно он нехороший. кому-нибудь более умному стоит что-то да отписать

2021-11-27 13:42 UTC, KIBORG04 requested changes
Исправь это.

https://github.com/Sakuya-Izayoi/TauCetiClassic/blob/f0dca728e3a36b2214448607eb8c8ca93b38f6c8/code/game/machinery/doors/firedoor.dm#L211

2021-11-27 14:31 UTC, merged