Fix emag, stackable items on borgs
TauCetiStation/TauCetiClassic pull request #8292
Opened 2021-11-26 14:22 UTC by FoLZer

## Описание изменений
Чинит следующие вещи:
- При использовании емага у синдиборга он более не будет выпадать и его более невозможно использовать бесконечное количество раз. (При превышении количества использований меняется на "сломанный" и возвращается обратно в инвентарь модуля)
- Больше нельзя использовать стакуемые предметы за борга, если их 0 или меньше в стаке. (Чинит бесконечно используемые лечебные предметы у медицинского модуля)
## Почему и что этот ПР улучшит
fix #8290
## Авторство
Me
## Чеинжлог
:cl:
- bugfix: Больше нельзя использовать стакуемые предметы(Мазь, бинт и т.д.) за борга, если их 0 или меньше.
- bugfix: Емаг синдиборга более не "бесконечный" и ломается как положено после нескольких использований.

2021-11-26 14:22 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2021-11-26 15:45 UTC, Sakuya-Izayoi requested changes

2021-11-26 15:45 UTC, Sakuya-Izayoi commented on code/_onclick/cyborg.dm
> +						return
Почему такой высокоуровневый код как поведение эмага обрабатывается в такой низкоуровневой процедуре как клик борга?

2021-11-26 15:45 UTC, Sakuya-Izayoi commented on code/game/objects/items/stacks/medical.dm
> +	var/icon_amount = max(1, min(amount, max_amount))
используй clamp, а вообще такого быть не должно.

2021-11-26 15:47 UTC, Sakuya-Izayoi commented on code/_onclick/cyborg.dm
> +						return
я уже не говорю о том что происходит внутри этого ифа...

2021-11-26 16:15 UTC, FoLZer commented on code/_onclick/cyborg.dm
> +						return
С первого раза догадаться куда поместить эту штуку голова не додумалась, переместил в afterattack()
А внутри этого ифа вещи которые просто заставляют правильно удалить емаг из модуля борга, после чего добавить поломанную карту вместо обычной.(Конечно можно просто удалять но так не круто :p)

2021-11-26 16:17 UTC, Sakuya-Izayoi requested changes

2021-11-26 16:17 UTC, Sakuya-Izayoi commented on code/game/objects/items/weapons/cards_ids.dm
> +		if(uses < 2 && isrobot(user))
я думаю эмаг робота стоит сделать отдельный подтипом и уже прописать это поведение ему. а то вдруг у роботов появится какой-нить гриппер который сможет эмаги поднимать, а тут такое. ну и uses < 2, получается, если 1 юз еще есть на эмаге этот иф отработает.

2021-11-26 16:17 UTC, Sakuya-Izayoi commented on code/game/objects/items/weapons/cards_ids.dm
>  		return
почему бы как-нибудь не объединить это поведение и не засунуть его в прок emag_break()?

2021-11-26 16:21 UTC, FoLZer commented on code/game/objects/items/weapons/cards_ids.dm
> +		if(uses < 2 && isrobot(user))
Если у него ещё 1 юз то отработает он как раз правильно, а так наверно, хотя после бикера я уже не уверен

2021-11-26 16:22 UTC, FoLZer commented on code/game/objects/items/weapons/cards_ids.dm
> +		if(uses < 2 && isrobot(user))
Хотя нет, не правильно, беру свои слова обратно

2021-11-26 16:49 UTC, FoLZer commented on code/game/objects/items/weapons/cards_ids.dm
>  		return
Не уверен насколько этот вариант будет лучше, но вроде так красиво теперь

2021-11-26 16:50 UTC, FoLZer commented on code/game/objects/items/weapons/cards_ids.dm
> +		if(uses < 2 && isrobot(user))
Подтипом не особо надо делать кажись если кинуть это в emag_break, лишний обьект будет совершенно. Гриппер хэндлится простой проверкой лока, если он в гриппере то лок = гриппер

2021-11-26 17:07 UTC, Sakuya-Izayoi commented on code/game/objects/items/weapons/cards_ids.dm
> +		if(uses < 2 && isrobot(user))
истайпы это не очень хорошо ИМХО и надо стараться писать код без них

2021-11-26 17:23 UTC, FoLZer commented on code/game/objects/items/weapons/cards_ids.dm
> +		if(uses < 2 && isrobot(user))
Перенёс в отдельный тип

2021-11-27 13:46 UTC, KIBORG04 commented on code/_onclick/cyborg.dm
> +		return
Это похоже должно быть выше, сразу под `if(buckled)`

2021-11-27 13:58 UTC, KIBORG04 commented on code/modules/mob/living/silicon/robot/inventory.dm
> +/mob/living/silicon/robot/proc/u_equip_any(obj/O)
```suggestion
/mob/living/silicon/robot/proc/unequip_module(obj/O)
```
хотя бы так. Я несколько минут пытался понять почему тут u_ и почему метод убирает модуль, а не экипирует его. А еще приписка окончание any практически ничего не значит

2021-11-27 13:59 UTC, FoLZer commented on code/_onclick/cyborg.dm
> +		return
I guess so

2021-11-27 14:00 UTC, FoLZer commented on code/modules/mob/living/silicon/robot/inventory.dm
> +/mob/living/silicon/robot/proc/u_equip_any(obj/O)
Делал по подобию u_equip у боргов, поэтому так вышло. А так возможно стоит поменять, да.

2021-11-28 22:29 UTC, Sakuya-Izayoi commented on code/_onclick/cyborg.dm
> +	return TRUE
почему прок никак не зависящий от борга находится у борга7

2021-11-28 22:29 UTC, Sakuya-Izayoi commented on code/modules/mob/living/silicon/robot/inventory.dm
> +	if(module_state_1 == O)
это выглядит как свитч

2021-11-29 19:13 UTC, FoLZer commented on code/modules/mob/living/silicon/robot/robot_items.dm
> +	if(loc == R || loc == R.module)
> а то вдруг у роботов появится какой-нить гриппер который сможет эмаги поднимать

Твой же комментарий из прошлого ревью. Этот чек просто проверяет находится ли он в борге как модуль, или в гриппере(или ещё где-то)

2021-11-29 19:14 UTC, FoLZer commented on code/_onclick/cyborg.dm
> +	return TRUE
Он требуется только тут. Не вижу ни единого смысла его куда-либо переносить или обобщать

2021-11-29 19:22 UTC, FoLZer commented on code/modules/mob/living/silicon/robot/inventory.dm
> +	if(module_state_1 == O)
Ни в коем случае, switch() принимает только константы, ни одна из этих переменных константой не является

2021-11-29 19:44 UTC, Sakuya-Izayoi commented on code/_onclick/cyborg.dm
> +	return TRUE
нет, не требуется. а если требуется чтобы именно такой прок был у класса робот, то это, наверное, проблема в дизайне.

к тому же, если бы это был метод obj/item наверное можно было бы обойтись без истайпов.

2021-11-29 19:47 UTC, Sakuya-Izayoi commented on code/modules/mob/living/silicon/robot/robot_items.dm
> +	if(loc == R || loc == R.module)
но ведь emag/borg должен же существовать только как модуль в борге. ведь если это не так, то это уже ошибка программиста, который emag/borg дает не боргу. (если что, про грипперы было до того, как ты сделал модуль эмаг подтипом обычного эмага)

2021-11-29 20:03 UTC, FoLZer commented on code/modules/mob/living/silicon/robot/robot_items.dm
> +	if(loc == R || loc == R.module)
А, да, логично.

2021-11-29 20:06 UTC, FoLZer commented on code/_onclick/cyborg.dm
> +	return TRUE
Я думал про то чтобы добавить какой-то прок is_usable() для итемов, как раз про который ты, наверно, и говоришь. Проблема только что это приведёт к огромному количеству рефакторинга, которым заниматься в этом ПРе немного не то.

2021-11-29 20:06 UTC, FoLZer commented on code/_onclick/cyborg.dm
> +	return TRUE
Но ладно, добавлю, только уже чуть позже.

2021-11-30 15:55 UTC, FoLZer commented on code/_onclick/cyborg.dm
> +	return TRUE
Вот теперь сделал так как должно быть, и немного сделал реордер для повторного использования medical стаков чтобы он имел смысл как и было задумано.

2021-12-03 22:50 UTC, Sakuya-Izayoi commented on code/modules/mob/living/silicon/robot/robot_items.dm
> +	return
раз уж ты починил изначальную проблему, может стоит отказаться от того чтобы давать поломанный эмаг боргу? типа, это просто модуль который ничего не делает. только конфьюзит юзера.

2021-12-03 22:50 UTC, Sakuya-Izayoi commented on code/modules/mob/living/silicon/robot/robot_upgrades.dm
> +	return 1
```suggestion
	return TRUE
```

ну и выше там 0 -> FALSE

2021-12-03 22:53 UTC, FoLZer commented on code/modules/mob/living/silicon/robot/robot_items.dm
> +	return
Как скажете

2021-12-03 22:56 UTC, FoLZer commented on code/modules/mob/living/silicon/robot/robot_upgrades.dm
> +	return 1
Вот это я бы пока-что не менял, у меня это уже припасено на 4 ПР по ретурнам, просто чуть позже будет.

2021-12-07 10:42 UTC, Sakuya-Izayoi approved these changes
ретурны ты вроде бы в другом ПРе делаешь, так что пускай

2021-12-10 19:29 UTC, kiVts commented
Как насчет того если он в заряднике, то его емаг становится снова рабочим через время?

2021-12-10 20:29 UTC, FoLZer commented
Имба будет ещё более лютая чем сейчас, не думаю что стоит

2021-12-10 21:27 UTC, TEXH4Pb requested changes
В идеале ещё чьё-нибудь мнение на счёт нейминга проков услышать. В остальном, можно мержить после исправления другого коммента.

@KIBORG04 я сделяль

2021-12-10 21:32 UTC, FoLZer commented on code/modules/mob/living/silicon/robot/robot_items.dm
> +	qdel(src)
Логично

2021-12-10 21:32 UTC, FoLZer commented on code/modules/mob/living/silicon/robot/robot_modules.dm
> +/obj/item/weapon/robot_module/proc/remove_module_item(obj/O)
Тут скорее всего ты прав.

2021-12-10 21:50 UTC, TEXH4Pb approved these changes
кайф
upd. не кайф

2021-12-10 21:52 UTC, TEXH4Pb commented on code/modules/mob/living/silicon/robot/robot_items.dm
> +	R.module.remove_module_item(src)
```suggestion
	R.module.remove_item(src)
```

2021-12-10 21:59 UTC, TEXH4Pb approved these changes

2021-12-11 19:23 UTC, merged