Добавляет снайперкам смещение зрения вбок.
TauCetiStation/TauCetiClassic pull request #8297
Opened 2021-11-26 20:54 UTC by AndroBetel

## Описание изменений
Тайтл, добавлен офигенный зум ПТР нюкеров.
Зум обычной снайперки, двигаться нельзя.
![image](https://user-images.githubusercontent.com/44546836/143637104-31bf2693-84d0-41ee-9a5a-f95b44a4163b.png)
Зум ПТР, двигаться можно.
![image](https://user-images.githubusercontent.com/44546836/143638851-529b2d4d-7d83-4dcc-b489-b031754b3f25.png)

## Почему и что этот ПР улучшит
Контент и приколы.
## Авторство
Я, копипаст с маринов.
## Чеинжлог
:cl:
- tweak: Изменение механизма использования прицела снайперки.
- rscadd: ПТР получила снайперский прицел.

2021-11-26 20:54 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2021-11-26 21:27 UTC, Sakuya-Izayoi commented on code/modules/projectiles/guns/projectile/sniper.dm
> +	AddComponent(/datum/component/zoom, 8, TRUE, 7)
```suggestion
	AddComponent(/datum/component/zoom, 8, FALSE, 7)
```
так можно или нельзя?

2021-11-26 21:28 UTC, Sakuya-Izayoi commented on code/modules/projectiles/guns/projectile/sniper.dm
> +	AddComponent(/datum/component/zoom, 8, TRUE, 7)
а, это я дурак

2021-11-26 22:55 UTC, KIBORG04 commented on code/datums/components/zoom.dm
> +			zoomer.client.pixel_y = 0
Хочешь записать в одну строчку это все?

2021-11-26 22:57 UTC, KIBORG04 commented on code/datums/components/zoom.dm
> +	var/viewoffset = tilesize * tileoffset
```suggestion
	var/viewoffset = world.icon_size * tileoffset
```

2021-11-26 22:58 UTC, KIBORG04 commented on code/datums/components/zoom.dm
> +		zoomer.client.pixel_y = 0
Знаешь че, скопируй анимки с тг, они круче смотрятся

```
/datum/view_data/proc/zoomIn()
	resetToDefault()
	animate(chief, pixel_x = 0, pixel_y = 0, 0, FALSE, LINEAR_EASING, ANIMATION_END_NOW)

/datum/view_data/proc/zoomOut(radius = 0, offset = 0, direction = FALSE)
	if(direction)
		var/_x = 0
		var/_y = 0
		switch(direction)
			if(NORTH)
				_y = offset
			if(EAST)
				_x = offset
			if(SOUTH)
				_y = -offset
			if(WEST)
				_x = -offset
		animate(chief, pixel_x = world.icon_size*_x, pixel_y = world.icon_size*_y, 0, FALSE, LINEAR_EASING, ANIMATION_END_NOW)
	//Ready for this one?
	setTo(radius)
```

2021-11-27 06:54 UTC, Sakuya-Izayoi commented on code/datums/components/zoom.dm
> +			zoomer.client.pixel_y = 0
Хотя... Наверное, это будет сложно прочитать потом.

2021-11-27 22:46 UTC, KIBORG04 commented on code/datums/components/zoom.dm
> +			zoomer.client.pixel_y = 0
Вот когда бетель напишет да..

2021-11-27 23:05 UTC, AndroBetel commented on code/datums/components/zoom.dm
> +			zoomer.client.pixel_y = 0
Не хочу писать киборг. =)

2021-12-03 21:27 UTC, KIBORG04 requested changes
Надеюсь ты не против, что я внес некоторые изменения. Но тут стоит добавить, что если можно со снайпой двигаться, то при изменение дира куклы поворачивался и направление прицела. Это всё на том же ТГ есть.

2021-12-03 21:31 UTC, AndroBetel commented
Я не против Киборг!

2021-12-03 21:32 UTC, KIBORG04 commented on code/datums/components/zoom.dm
> +		zoomer.client?.change_view(world.view)
```suggestion
		zoomer.client.change_view(world.view)
```

2021-12-03 22:37 UTC, Sakuya-Izayoi approved these changes

2021-12-31 02:21 UTC, closed without merging