Ремап инженерного отдела.
TauCetiStation/TauCetiClassic pull request #8316
Opened 2021-11-29 15:14 UTC by Tap0r

## Описание изменений
Темка на форуме:
https://forum.taucetistation.org/t/vneocherednoj-remap-inzhenerki/29871/5

Скриншот карты (открывать в новом окне):
![tap0r2](https://user-images.githubusercontent.com/88531962/143881823-6fe5a3fc-dbc8-4148-b72a-3cebb5a598da.png)

* Склад переехал к кабинету СЕ. Между ними появился шлюз.
* Кабинет СЕ сложнее ломануть со стороны техов.
* СМЕСы немного перемещены к другой стене.
* Шлюзы в комнату отдыха и двигательную из атмоса.
* Менее кишкообразный атмос.
* В кабинете СЕ вместо двух хай капасити батареек лежат две супер. Разница макс чарджа у них 5000.
* Шлюз из двигательной в дронную, через который можно обойти локдаун инженерного.
* Немного сузился коридор.
* У инженеров теперь есть курилка.
* Зона двигателя перестала быть квадратной.
* Добавлено по ещё одному венту в шлюзах выхода в космос, теперь он осуществляется быстрее.
* В комнате со снаряжением шкафы и столы с ресурсами поменялись местами (шкафы инженеры используют в начале раунда и больше их чаще всего не трогают, поэтому они отнесены от центрального двухтайлового прохода в противоположный край, вместо них теперь бак топлива, пены и столы с ресурсами).
* Полки с противогазами и прочим больше не мешают проходу.
* Карты, игральные кости и шахматы в комнате отдыха. Туда же перенесён шкаф с одеждой и полки с руководствами для ассистух.
* Аптечка и стазис мешок переехали из комнаты отдыха в двигательную.
* Хранилище баллонов, шкаф с одеждой атмосников и их мусорка перенесены из комнаты мониторинга в атмос.
* Кнопка локдауна атмоса теперь есть в самом атмосе.
* Стоянка для мулбота со стороны техов.
* Стройка и ассембли лайн поменялись местами.
* На стройку добавлена помпа, хитер, танкер с пеной и больше всякого.
* На ассембли лайне появился конвейер и всякое разное.
* Небольшие изменения техов.
* Симметричное хранилище плат.
* Красивое.

## Почему и что этот ПР улучшит
* Инженерный давно не обновлялся.

* Для взлома кабинета СЕ потребуется что-то большее, нежели чем одна сифора.
* Более прямой и понятный атмос.
* Более удобная планировка?
* Ассистенты могут сами взять себе книгу с полки, а не просить у инженеров.
* Красивое.

## Авторство
Tap0r
## Чеинжлог
:cl:
 - map[link]: Изменения в инженерном.

2021-11-29 15:14 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2021-11-29 15:18 UTC, TauKitty commented
This pull request has been mentioned on **Tau Ceti Station Forum**. There might be relevant details there:

https://forum.taucetistation.org/t/vneocherednoj-remap-inzhenerki/29871/35

2021-11-29 16:50 UTC, Lexakr requested changes
1.  Это вернуть в прежнее состояние, тут неуместны какие-то кресла и кофеек. То же касается и сигаретной части, это место неудачное всегда было, считаю что его или фиксить или не трогать
![image](https://user-images.githubusercontent.com/29842063/143902382-678ec21f-1db0-44b8-8789-5636c51b4b17.png)
2. Оставить один вход в атмос через двойной шлюз, как сейчас. Иначе вообще не вижу смысла в его (шлюза) существовании и считаю неправильным "дырявый" со всех сторон атмос.
3. Почему-то здесь ты решил потерять пожарную створку 
![image](https://user-images.githubusercontent.com/29842063/143903839-fb87f95e-5cd0-4b92-8057-195c9464c817.png)
4. Наложение таблички на топор, перемести или топор или табличку
5. Тут на входе в тех убрать плитку 
![image](https://user-images.githubusercontent.com/29842063/143904716-c503c218-f563-4e91-a140-beccd98dee10.png)
6. Комната со СМЕСами расширена просто потому что. Убираем шлюз в атмос и становится еще бессмысленнее
7. Почему аптечка и стазис стали личной собственностью инженеров? атмостехи обидятся
8. На текущей карте это место, насколько я знаю, используется в т.ч как выход/вход, когда тащишь много штук, через техи и пластиковые штучки так не пройдешь
9. Против лесенок везде, кроме мб комнаты с подачей газа на станцию в атмосе, да и той нужно изменить спрайт (у тебя миддл, нужна одиночная) и убрать стекла по бокам, ибо неудобно
10. Такая конструкция выглядела бы приятнее 
![image](https://user-images.githubusercontent.com/29842063/143906520-fe20245c-ee22-4848-aeb1-dc6381b61052.png)
11. Ассембли и констракшен - оно выглядит, конечно, неплохо, но там заранее уже что-то построено осмысленное, а это все таки места под строечку (идея с конвеером прикольная)
12. 118,098 потерял плитку
13. У СЕ не все стекла под проводами

Из чего-то требовательного это вроде все
Огорчен, что это "неполноченный" ремап. Хотелось бы видеть прям что-то новое, а имеем что имеем. Несколько отсеков и правда стали лучше, но проблемы вроде коридоров в 1 тайл остались. Не появилось чего-то вроде полноценной комнаты отдыха ~~(возможно с туалетом, хех)~~, выхода в космос для атмостехов/инженеров (чтоб не в сингу). С учетом поправок в целом ничего не имею против

2021-11-30 07:17 UTC, Tap0r commented
> Оставить один вход в атмос через двойной шлюз, как сейчас. Иначе вообще не вижу смысла в его (шлюза) существовании и считаю неправильным "дырявый" со всех сторон атмос.

![bandicam 2021-11-30 11-06-44-349](https://user-images.githubusercontent.com/88531962/144001456-fbb9f09c-739e-4501-bac7-2f3840d91131.jpg)
Такой выход из атмоса в двигательную сойдёт? Если что инженеры имеют доступ к первому шлюзу, чтобы они могли если что взять оттуда скраббер при выпуске форона.


> Наложение таблички на топор, перемести или топор или табличку

![bandicam 2021-11-30 10-41-14-530](https://user-images.githubusercontent.com/88531962/144001585-333b2beb-3a48-46d8-b29a-5d273350ab8b.jpg)
![bandicam 2021-11-30 10-41-31-225](https://user-images.githubusercontent.com/88531962/144001615-fb76075b-78ce-47f3-b3b6-d17c38fde029.jpg)
Они с разных сторон одной стены, на прошлом боксе там также "накладывались" топор и новостная штука.


> На текущей карте это место, насколько я знаю, используется в т.ч как выход/вход, когда тащишь много штук, через техи и пластиковые штучки так не пройдешь

![bandicam 2021-11-30 10-41-48-774](https://user-images.githubusercontent.com/88531962/144001785-02e6e318-b480-435b-96ff-e49f55c553d4.jpg)
![bandicam 2021-11-30 10-41-50-346](https://user-images.githubusercontent.com/88531962/144001801-71b41e62-5d3a-421e-b52d-843f5b2b2c16.jpg)
Кравл и пулл.


> нужна одиночная

Одиночных я не нашёл, не знаю есть ли они вообще.

> выхода в космос для атмостехов/инженеров (чтоб не в сингу).

У атмостехов теперь есть. У инженеров тоже имеется.
![bandicam 2021-11-30 10-46-16-873](https://user-images.githubusercontent.com/88531962/144002471-524c014e-5646-425f-9bd5-32c74ee5839b.jpg)
![bandicam 2021-11-30 10-46-37-481](https://user-images.githubusercontent.com/88531962/144002496-06ca0cfe-20f9-4a64-80e0-f45f475642f9.jpg)
![bandicam 2021-11-30 10-46-48-691](https://user-images.githubusercontent.com/88531962/144002505-06b7deb8-b941-4d3f-b0f6-d78271a4aa33.jpg)
![bandicam 2021-11-30 11-14-36-626](https://user-images.githubusercontent.com/88531962/144002522-645cda74-3bd4-462c-b9de-14ebf74f3146.jpg)

2021-12-03 12:02 UTC, Tap0r commented
@Lexakr когда?

2021-12-06 14:10 UTC, Lexakr commented
> @Lexakr когда?

Пора тебе чинить мерж конфликт

2021-12-10 20:48 UTC, KIBORG04 commented
все еще не починил

2021-12-11 10:26 UTC, Tap0r commented
:cockroach:

2021-12-11 11:48 UTC, Lexakr approved these changes
Вообще, в целом все доработано и можно уже смотреть в игре. Если ни у кого нет возражений

2021-12-12 09:34 UTC, Tap0r commented
Можно ТМ?

2021-12-12 09:36 UTC, volas commented
После #8383

2021-12-14 13:51 UTC, Tap0r commented
:beaver:

2021-12-17 11:42 UTC, Tap0r commented
Я починил вроде, выпустите :crying_cat_face::crying_cat_face::crying_cat_face::crying_cat_face::crying_cat_face::crying_cat_face::crying_cat_face::crying_cat_face::crying_cat_face:

2021-12-21 04:37 UTC, volas commented
Если тут проблем больше не будет, желательно смержить в ближайшие дни. Там новогодние мап ПРы грядут

2021-12-21 12:01 UTC, Lexakr commented
> Если тут проблем больше не будет, желательно смержить в ближайшие дни. Там новогодние мап ПРы грядут

Проблем тут нет, можно мержить

2021-12-21 12:08 UTC, Tap0r commented
Теперь точно нету :new_moon_with_face:

2021-12-21 16:04 UTC, merged