Return 1,0 -> Return TRUE,FALSE (3)
TauCetiStation/TauCetiClassic pull request #8323
Opened 2021-11-30 19:54 UTC by FoLZer

## Описание изменений
#6742 (return TRUE, FALSE)
Данный ПР меняет только данные папки:

code/game/area
code/game/dna
code/game/gamemodes
## Почему и что этот ПР улучшит
Рефактор кода.
## Авторство

## Чеинжлог

2021-11-30 19:54 UTC, TauKitty commented
###### Changelog status: :radio_button: No changelog

2021-12-10 19:56 UTC, KIBORG04 commented on code/game/gamemodes/modes_gameplays/abduction/machinery/dispenser.dm
> +	..()
```suggestion
	return ..()
```

2021-12-10 19:57 UTC, KIBORG04 commented on code/game/gamemodes/modes_gameplays/blob/blobs/resource.dm
> +		overmind.add_points(1)
??????

2021-12-10 19:57 UTC, KIBORG04 commented on code/game/gamemodes/modes_gameplays/blob/blobs/shield.dm
> +	return FALSE
а че, здесь уже устал переносить ретурн на новую строку?

2021-12-10 19:58 UTC, KIBORG04 commented on code/game/gamemodes/modes_gameplays/blob/theblob.dm
> +		return FALSE
```suggestion
		return
```

2021-12-10 19:58 UTC, KIBORG04 commented on code/game/gamemodes/modes_gameplays/blob/theblob.dm
> +	return
```suggestion
```

2021-12-10 19:58 UTC, KIBORG04 commented on code/game/gamemodes/modes_gameplays/blob/theblob.dm
> +	return
```suggestion
```

2021-12-10 20:02 UTC, KIBORG04 commented on code/game/gamemodes/modes_gameplays/changeling/powers/Whip.dm
> +	..()
```suggestion
	return ..()
```
Такое выглядит красивее

2021-12-10 20:02 UTC, KIBORG04 commented on code/game/gamemodes/modes_gameplays/changeling/powers/changespecies.dm
> +	if(!S)	return FALSE
перенос

2021-12-10 20:07 UTC, KIBORG04 commented on code/game/gamemodes/modes_gameplays/cult/cult_datums.dm
> +		return
Оно используется глубже в каллбэке. Верни тру фолсы у capture_iteration

2021-12-10 20:11 UTC, KIBORG04 commented on code/game/gamemodes/modes_gameplays/ninja/suit/n_suit_verbs/ninja_stealth.dm
> +		return TRUE
ретурны не нужны

2021-12-10 20:12 UTC, KIBORG04 commented on code/game/gamemodes/modes_gameplays/ninja/suit/n_suit_verbs/ninja_stealth.dm
> +		return TRUE
ретурны не нужны

2021-12-10 20:15 UTC, KIBORG04 commented on code/game/gamemodes/modes_gameplays/nuclear/nuclearbomb.dm
> +	return FALSE
```suggestion
	return ..()
```
Наверное, так подразумевалось

2021-12-10 20:16 UTC, KIBORG04 commented on code/game/gamemodes/modes_gameplays/wizard/soulstone.dm
> +	return FALSE
наверное стоит ..() возвращать, хз

2021-12-10 20:19 UTC, KIBORG04 commented on code/game/gamemodes/objectives/families/kill_head.dm
> +		return
find_target() должен возвращать тру/фолс, верни как было

2021-12-10 20:19 UTC, KIBORG04 commented on code/game/gamemodes/objectives/heist/loot.dm
> -	return TRUE
find_target() должен возвращать тру/фолс, верни как было

2021-12-10 20:19 UTC, KIBORG04 commented on code/game/gamemodes/objectives/heist/salvage.dm
> -	return TRUE
find_target() должен возвращать тру/фолс, верни как было

2021-12-10 20:20 UTC, KIBORG04 commented on code/game/gamemodes/objectives/steal.dm
> -	return TRUE
find_target() должен возвращать тру/фолс, верни как было

2021-12-10 20:20 UTC, KIBORG04 commented on code/game/gamemodes/objectives/steal.dm
> +		return
select_target() должен возвращать тру/фолс, верни как было

2021-12-10 20:21 UTC, KIBORG04 commented on code/game/gamemodes/objectives/target/sacrifice.dm
> -	return TRUE
find_target() должен возвращать тру/фолс, верни как было

2021-12-10 20:21 UTC, KIBORG04 commented on code/game/gamemodes/objectives/target/target.dm
> -		return TRUE
find_target() должен возвращать тру/фолс, верни как было

2021-12-10 20:22 UTC, KIBORG04 requested changes
⬆️

2021-12-10 20:33 UTC, FoLZer commented on code/game/gamemodes/objectives/families/kill_head.dm
> +		return
Может и должен, но нигде использования ретурна не было

2021-12-10 20:33 UTC, KIBORG04 commented on code/game/gamemodes/objectives/families/kill_head.dm
> +		return
![image](https://user-images.githubusercontent.com/26389417/145637780-db0a0257-65a8-499c-9e00-979f127329cf.png)

Все есть

2021-12-10 20:34 UTC, KIBORG04 commented on code/game/gamemodes/objectives/families/kill_head.dm
> +		return
ой бля, фармот не то. Но финд_таргет юзается.

2021-12-10 20:55 UTC, FoLZer commented on code/game/gamemodes/modes_gameplays/wizard/soulstone.dm
> +	return FALSE
Тут ты прав, так логичнее

2021-12-10 20:55 UTC, FoLZer commented
Всё сделал по ревьювам

2021-12-10 21:06 UTC, KIBORG04 commented on code/game/gamemodes/modes_gameplays/cult/cult_datums.dm
> -	return TRUE
Верни тру

2021-12-10 21:06 UTC, FoLZer commented on code/game/gamemodes/modes_gameplays/cult/cult_datums.dm
> -	return TRUE
А ой

2021-12-10 21:12 UTC, merged