Новые дереликты
TauCetiStation/TauCetiClassic pull request #8327
Opened 2021-12-01 11:22 UTC by Motykoo

## Описание изменений
Добавил пять новых дереликтов основываясь на понравившихся мне идеях с форума. Баланс пытался не нарушать, если какой-то лут слишком жирный или наоборот недостаточно крутой - изменю.
<details>
<summary>Tree Asteroid</summary>

![tree_asteroid](https://user-images.githubusercontent.com/59807075/144223604-04aa0a50-4a92-47a7-b616-d4df1a872a2a.png)

Внутри спаунится труп ботаника, ничего интересного, просто _ламповое_ место.
</details>

<details>
<summary>Resource Shuttle</summary>

![resource_shuttle](https://user-images.githubusercontent.com/59807075/144205017-19757e32-d694-452b-a7c0-4e25dbf1775a.png)

Подбитый корабль Cargo Industries, из интересного лута тут 5 слитков золота и 10 слитков урана, но ящик с ними заперт. Достать их можно или взломом или через персонал с доступом. 
</details>

<details>
<summary>Ships Squad</summary>

Белые поля под угловыми деталями корабля только в редакторе карт, в игре там космос.

![ships_squad](https://user-images.githubusercontent.com/59807075/144223650-2b3361dd-b5b8-4c12-a75c-44a74baab6f3.png)

Брошеный, безжизненный отряд кораблей НТ в идеальном состоянии (ну, кроме одной сломаной турели). Два истребителя "Блатон", "Скеора" сопровождающие десантный корабль.

![image](https://user-images.githubusercontent.com/59807075/144212382-579bcee8-7fa8-453b-a603-02b4572d2b16.png)
Истребитель "Блатон". Охраняется тремя турелями. Войти в корабль нетронутым довольно сложно учитывая то что не всегда знаешь с какой стороны подойдешь к дереликту, но за успешное проникновение ученый вознаграждается диском исследований, сб шлемом(фулл риг посчитал перебором), магбутсами, медалькой НТ "Робаст" и лазеркой. На корабле также удачно расположились три разные аптечки для тех кого задели турели.

![image](https://user-images.githubusercontent.com/59807075/144212817-6afbdde5-e48d-4867-b90d-eb4b1e5a50dc.png)
Истребитель "Скеора", из интересного лута только модуль Ремонтный Дрон для меха. Охраняется двумя лазерными турелями, но можно аккуратно пройти в корабль снизу, не словив выстрел.

![image](https://user-images.githubusercontent.com/59807075/144213641-2353c1b9-1c51-467a-9c07-6420de472273.png)
Просто десантный корабль НТ с лежащими рядом гильзами а74 и лужей крови.
</details>

<details>
<summary>Secrete Lab</summary>

![secrete_lab](https://user-images.githubusercontent.com/59807075/144216933-d2690cff-b1cb-4720-ad34-3776113b2d88.png)

Секретная исследовательская лаборатория. Есть медбей, РнД, оружейная, комната отдыха и дормы. Снизу пробоина, прямо рядом с входом в лабу. Внутри нас встречают разброшеные трупы ученых и по одному трупу медика и СБ (с трупов можно стянуть наушники соотвествующего отдела, карт нет). В меде полный набор для хирургии и много мини-аптечек. В РнД целый деконструктор, автолат, научный РИГ и 1шт. алмаз. Оружейка - следы погрома, слабенький пистолет, броник и нож. В других комнатах ценного лута нет. 
![image](https://user-images.githubusercontent.com/59807075/144218708-c8c21a1e-95ea-4fd1-90c3-e3f117bd73e3.png)
В конце главного коридора есть хранилище с заболтированными камерами содержания.
В первой камере cyber horror, если укусит человека то может гибнуть и превратить в такого же зомби. Во второй кот рантайм, самый опасный объект. Рядом лежит рандомный отчет рантайма за 2019 что нашел на гите (Да-да, OOC in IC).
</details>

<details>
<summary>Broken Breacher</summary>

Белые поля под угловыми деталями корабля только в редакторе карт, в игре там космос.

![broken_breacher](https://user-images.githubusercontent.com/59807075/144219247-5368ad0e-bbb4-4002-9a12-13636f5ee422.png)

Если не ошибаюсь, будет самым большим дереликтом.
Подбитый корабль унатхов, защищен шестью турелями, внутри пробитий можно встретить карпов. Все трупы солдатов с броником и шлемами, без карт.

![image](https://user-images.githubusercontent.com/59807075/144220096-694df31e-16d3-4082-9928-da79b3c601c1.png)
Рядом с подом атаки труп командира унатхов в полном сете боевого космического костюма Breacher, сделанный только для унатхов. На нем также карта с капитанским доступом и джетпак кислорода. Труп унатха-солдата, держатели для боевых ножей унахтов (с двумя ножами внутри) и один уцелевший дроп под(без улучшений, одноразовый). Забытый арбалет и несколько rod'ов намекают на замешанность воксов в катастрофе корабля. В зеленом ящике на разрушенном складе лежат combat gloves. Все это дело охраняет карп.

![image](https://user-images.githubusercontent.com/59807075/144221422-37d7de18-f3ab-4293-90fb-2611251b561b.png)
Казармы солдат с одним трупом, ничего интересного.

![image](https://user-images.githubusercontent.com/59807075/144221564-1f569afe-2c1e-46ef-903a-ec2d6beee66f.png)
Уцелевший западный склад, рандомный лут с техов + очки ночного видения. 

![image](https://user-images.githubusercontent.com/59807075/144221720-03952906-f041-44c8-9eba-819240e275dc.png)
Оружейная и западный под атаки. Северный вход в оружейную заболтирован, внутри power-fist, riot щит, канистра кислорода и один труп.

![image](https://user-images.githubusercontent.com/59807075/144222377-5d6db915-676a-49ae-8006-ea1daf56235c.png)
Главный коридор, два входа на корабль, ванная, туалеты. Есть кухня со всем необходимым для готовки, в ящике острая еда.

![image](https://user-images.githubusercontent.com/59807075/144222909-1cfdfe3a-81e3-4219-ba41-35c7df545b6f.png)
Мостик корабля. В каюту капитана забродили два карпа. В сейфе энерго-топор, пароля от сейфа нет. В рулевой рубке диск исследований и аптечка.
</details>
На некоторых дереликтах есть устройства контроля турелей, они работают.

Так же пофиксил дереликт "клоунский шатл", было два двигателя в одном тайле.
## Почему и что этот ПР улучшит
Больше контента и хоть какое-то изменение в дереликтах за долгое время.
## Авторство

## Чеинжлог
:cl:
 - map[link]: Добавлены 5 новых дереликтов.

2021-12-01 11:22 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2021-12-01 11:24 UTC, TauKitty commented
This pull request has been mentioned on **Tau Ceti Station Forum**. There might be relevant details there:

https://forum.taucetistation.org/t/idei-dlya-novyh-dereliktov/29920/51

2021-12-01 11:40 UTC, LoTaRk-FroG commented
> Поверфист

Может что-нибудь другое? Поверфист это невероятно мощная штука, которая в сочетании с джетпаком, броней и химией (всё это есть у любителей телесайнса) сделает тебя практически непобедимым

2021-12-01 11:52 UTC, Tap0r commented
Сделай астероид дерево внутри округлым, а не квадратным

2021-12-01 12:31 UTC, KIBORG04 commented on code/modules/awaymissions/corpse.dm
> +		M = new /mob/living/carbon/human (src.loc)
а здесь ты можно просто создавать `/mob/living/carbon/human(loc)`, а потом менять ему расу через `set_species(species)`

2021-12-01 12:32 UTC, KIBORG04 commented on code/modules/awaymissions/corpse.dm
> +	var/specie = "HUMAN" //Set specie of a new corpse
а еще правильно будет просто `species`, с `s`

2021-12-01 12:35 UTC, KIBORG04 commented on code/modules/mob/living/simple_animal/friendly/cat.dm
> +/mob/living/simple_animal/cat/runtime_lab
Ты можешь в `/mob/living/simple_animal/cat/runtime` создать переменную, которой можно регулировать выполнение механа в `atom_init()`, чтобы он не удалился и тд. Типо это минус копипаста.

А еще весь прикол был не в самом коте, а в том что он мертвый.

2021-12-01 12:41 UTC, KIBORG04 commented on maps/templates/space_structures/secrete_lab.dmm
> +	info = "runtime error:<br> \[17:32:58\]Cannot read null.selecting<br>\[17:32:58\]proc name: infect limb (/obj/item/weapon/reagent_containers/syringe/proc/infect_limb)<br>\[17:32:58\]  source file: s
Наверное отсюда стоит убрать все упоминания `Oksana Koroleva`

2021-12-01 12:42 UTC, KIBORG04 commented on maps/templates/space_structures/secrete_lab.dmm
> +	info = "runtime error:<br> \[17:32:58\]Cannot read null.selecting<br>\[17:32:58\]proc name: infect limb (/obj/item/weapon/reagent_containers/syringe/proc/infect_limb)<br>\[17:32:58\]  source file: s
Либо наоборот, вставить вместо этого имени какую-то отсылку

2021-12-01 13:42 UTC, Motykoo commented on code/modules/mob/living/simple_animal/friendly/cat.dm
> +/mob/living/simple_animal/cat/runtime_lab
спрайта мертвого рантайма нет увы, может потом как-то нарисую

2021-12-01 16:46 UTC, Sakuya-Izayoi commented on maps/templates/space_structures/secrete_lab.dmm
> +	info = "runtime error:<br> \[17:32:58\]Cannot read null.selecting<br>\[17:32:58\]proc name: infect limb (/obj/item/weapon/reagent_containers/syringe/proc/infect_limb)<br>\[17:32:58\]  source file: s
Оксана Королева этой мой чар, норм отсылка

2021-12-01 16:56 UTC, Tap0r commented
Можно в РнД на секретной лабе какие-нибудь почти топ тир компоненты закинуть, пикоманипуляторы там, супер батареи. И какое-то это РнД пустое прям. Мне кажется, что можно стенку под машинерией вправо сдвинуть.
![144216933-d2690cff-b1cb-4720-ad34-3776113b2d88](https://user-images.githubusercontent.com/88531962/144277494-b5b80b53-1731-4170-abe7-fafc857fc72c.png)
 
Ну а ещё, как-то маловато говна, этот дерелик выглядит чище, чем коридоры станции в среднем раунде.

2021-12-01 18:47 UTC, KIBORG04 commented
Диреликты лаборатории и кораблей НТ выглядят какими-то слишком целыми. Типо, а почему они заброшены, но в таком идеальном состояние?

2021-12-01 19:14 UTC, Sakuya-Izayoi commented
> Диреликты лаборатории и кораблей НТ выглядят какими-то слишком целыми. Типо, а почему они заброшены, но в таком идеальном состояние?

выходной день

2021-12-02 10:03 UTC, Motykoo commented
> Диреликты лаборатории и кораблей НТ выглядят какими-то слишком целыми. Типо, а почему они заброшены, но в таком идеальном состояние?

лабу переделал, истребы так и задумано

2021-12-02 17:16 UTC, BesumniiChebureck requested changes
Рекьюст чейндженс by мап департамент, автору было указано на ошибки, ревувить снова после того, как автор будет готов.

2021-12-05 12:03 UTC, KIBORG04 commented on code/modules/mob/living/simple_animal/friendly/cat.dm
> +	var/disappear = TRUE
я так понимаю, ты изменил эту переменную в карте. Лучше так не делать никогда. Создай новый подкласс с этим полем на ФОЛС и уже этот подкласс добавляй на карту

2021-12-05 12:04 UTC, KIBORG04 commented on code/modules/mob/living/simple_animal/friendly/cat.dm
>  	cat_number += 1
Это тоже перенеси под `if(disappear)`

2021-12-10 18:40 UTC, Lexakr commented
Все норм, только 1 нюанс. Дроппод на унати-шаттле рабочий и с него можно будет дропнуться на стейшон. А может оно и круто?

2021-12-10 19:06 UTC, merged

2021-12-15 16:36 UTC, TauKitty commented
This pull request has been mentioned on **Tau Ceti Station Forum**. There might be relevant details there:

https://forum.taucetistation.org/t/vopros-otvet/13334/3929