ИИ может включать и активировать Liquid Dispenser
TauCetiStation/TauCetiClassic pull request #8336
Opened 2021-12-02 18:39 UTC by Motykoo

## Описание изменений
![image](https://user-images.githubusercontent.com/59807075/144481658-8723792f-41d5-4fbd-ab96-dd445b326c36.png)
Теперь эти раздатчики смазки ИИ может включать и выключать через Ctrl+клик. Активировать через Alt+клик.
## Почему и что этот ПР улучшит
Меньше надоедливого и долгого прокликивания каждого раздатчика через окно чтобы его включить.
## Авторство

## Чеинжлог
:cl: 
 - rscadd: ИИ теперь может включать Liquid Dispenser на Ctrl+клик и активировать на Alt+клик.

2021-12-02 18:39 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2021-12-02 19:23 UTC, Sakuya-Izayoi requested changes

2021-12-02 19:23 UTC, Sakuya-Izayoi commented on code/_onclick/ai.dm
> +	Topic("toggleOn=1", list("toggleOn"="1"), 1)
Так делаться не должно. У аислиппера должен быть свой прок, который делает нужное, здесь ты должен вызывать его, а Топик это прок для обработки хрефов.

2021-12-02 19:23 UTC, Sakuya-Izayoi commented on code/game/machinery/ai_slipper.dm
> +	. = ..(href, href_list)
этот аргумент не нужен ну ты понял

2021-12-02 19:59 UTC, Motykoo commented on code/_onclick/ai.dm
> +	Topic("toggleOn=1", list("toggleOn"="1"), 1)
resolved?

2021-12-02 20:00 UTC, Sakuya-Izayoi commented on code/_onclick/ai.dm
> +	Topic("toggleOn=1", list("toggleOn"="1"), 1)
если ты считаешь что сделал все как надо то можешь сам зарезолвить

2021-12-02 20:02 UTC, Sakuya-Izayoi requested changes

2021-12-02 20:02 UTC, Sakuya-Izayoi commented on code/_onclick/ai.dm
> +		activate()
это стоит вынести в отдельный прок потому что в топике у тебя такой же иф. после ретурна элс не нужен.

2021-12-02 20:02 UTC, Sakuya-Izayoi commented on code/game/machinery/ai_slipper.dm
> +	icon_state = src.disabled? "motion0":"motion3"
почему прок называется setDisable если он может и включать тоже? айкон стейты меняй в update_icon проке.

2021-12-02 20:03 UTC, FoLZer approved these changes

2021-12-02 20:03 UTC, FoLZer commented on code/_onclick/ai.dm
> +		activate()
```suggestion
		return FALSE
	activate()
```

2021-12-02 20:03 UTC, FoLZer commented on code/_onclick/ai.dm
> +		activate()
После return else не нужен

2021-12-02 20:03 UTC, FoLZer commented on code/game/machinery/ai_slipper.dm
> +			activate()
Тут тоже советую убрать else

2021-12-02 20:06 UTC, FoLZer commented on code/_onclick/ai.dm
> +		activate()
Почему эти проки вообще вынесены в _onclick/ai?

2021-12-02 20:48 UTC, KIBORG04 commented on code/game/machinery/ai_slipper.dm
> +	slip_process()
удали все src

2021-12-02 21:06 UTC, Sakuya-Izayoi commented on code/game/machinery/ai_slipper.dm
> +		icon_state = disabled? "motion0":"motion3"
```suggestion
		icon_state = disabled ? "motion0" : "motion3"
```

2021-12-03 20:51 UTC, FoLZer commented on code/game/machinery/ai_slipper.dm
> +	cooldown_time = world.timeofday + 100
Может стоит эту штуку перенести на таймеры? Уж очень текущий вариант кулдауна выглядит ужасно. Для примера можно открыть любой предмет с кулдауном.

2021-12-03 22:42 UTC, Sakuya-Izayoi commented on code/game/machinery/ai_slipper.dm
> +	cooldown_time = world.timeofday + 100
такие кулдауны они почти везде. мб какой-нибудь кулдаун датум было бы круто, но я хз, надо ли это.

2021-12-03 22:44 UTC, Sakuya-Izayoi commented on code/game/machinery/ai_slipper.dm
такое ощущение что этот прок не используется.

2021-12-05 23:05 UTC, Sakuya-Izayoi commented on code/_onclick/ai.dm
> +	toggle_on()
как сказали выше, перенеси проки слиппера в файл слиппера.

2021-12-10 19:49 UTC, merged