Абоминация - последняя форма генокрадуса.
TauCetiStation/TauCetiClassic pull request #8340
Opened 2021-12-03 02:07 UTC by AndroBetel

## Описание изменений
После шести (может измениться) скушанных чубриков генокрад превратится в медленную, но живучую и больно кусающуюся машину для убийств - и скорее всего станция его замочит.
![image](https://user-images.githubusercontent.com/44546836/144532617-82c298a2-8246-413a-9744-37e2c3a29f36.png)

В планах - запретить ему использовать некоторые способности генокрада, дать возможность ломать шлюзы, выдавать генкам кучу очков за поглощение своего обращенного собрата. Обсудить ещё тут можно, что сделать и что эта абоминация должна из себя превращать.
## Почему и что этот ПР улучшит
Геймплей за генокрада и боланс.
## Авторство
Я спрайт с гунов старый.
## Чеинжлог
Потом напишу.

2021-12-03 02:08 UTC, TauKitty commented
###### Changelog status: :radio_button: No changelog

2021-12-03 02:08 UTC, AndroBetel commented
ПР не доделан если что, очевидно.

2021-12-03 05:44 UTC, volas commented
ого ты быстрый

2021-12-03 08:08 UTC, LoTaRk-FroG commented
Больше 6 хотя бы 7-8 поставь

2021-12-03 11:41 UTC, AndroBetel commented
Можно уже ревьювить наверное.

2021-12-03 11:46 UTC, KIBORG04 commented
Разберись с лицензией гунов или новый спрайт нарисуй

2021-12-03 11:47 UTC, AndroBetel commented
Волас сказал, что этот - норм, у них новый под лицензией, а этот вроде на всех серваках побывал.

2021-12-03 11:48 UTC, KIBORG04 commented
Ну раз сказал волас...

2021-12-03 13:53 UTC, KIBORG04 commented on code/__DEFINES/mob.dm
> +#define ABOMINATION    "disgusting abomination"
С больших букв начинай слова, чтобы было в стиле названий других рас

2021-12-03 13:53 UTC, AndroBetel commented on code/__DEFINES/mob.dm
> +#define ABOMINATION    "disgusting abomination"
Фактически это не название расы и красивее выглядит когда в экзамине оно вот так.

2021-12-03 13:54 UTC, KIBORG04 commented on code/game/gamemodes/modes_gameplays/changeling/changeling_power.dm
> +/obj/effect/proc_holder/changeling/proc/can_sting(mob/living/carbon/human/user, mob/target)
стинг можно юзать за макаку, а значит ты фигню написал

2021-12-03 13:54 UTC, KIBORG04 commented on code/game/gamemodes/modes_gameplays/changeling/changeling_power.dm
> +	if(!can_be_used_in_abom_form && user.species.name == ABOMINATION)
Тут может быть макака, которая вообще не имеет расы

2021-12-03 13:56 UTC, AndroBetel commented on code/game/gamemodes/modes_gameplays/changeling/changeling_power.dm
> +/obj/effect/proc_holder/changeling/proc/can_sting(mob/living/carbon/human/user, mob/target)
Черт побери.

2021-12-03 13:57 UTC, KIBORG04 commented on code/game/gamemodes/modes_gameplays/changeling/powers/absorb.dm
> +	if(changeling.absorbedcount == OVEREATING_AMOUNT-1)
```suggestion
	if(changeling.absorbedcount == OVEREATING_AMOUNT / 2)
		to_chat(user, "<span class='warning'>Absorbing that many made us realise that we are halway to becoming a threat to all - even ourselves. We should be more careful with absorbings.</span>")

	if(changeling.absorbedcount == OVEREATING_AMOUNT - 1)
```

2021-12-03 14:00 UTC, KIBORG04 commented on code/game/gamemodes/modes_gameplays/changeling/powers/absorb.dm
> +/obj/effect/proc_holder/changeling/absorbDNA/proc/check_overeating(mob/living/carbon/human/user)
Это должен быть метод у /datum/role/changeling (по лоигке) и называться как-то иначе, типо handle_eating хз. Сейчас у тебя метод не только чекает_переедание, но и впринципе хендлит любое поедание

2021-12-03 14:01 UTC, KIBORG04 commented on code/game/gamemodes/modes_gameplays/changeling/powers/absorb.dm
> +	check_overeating(user)
Вызов этого метода должен быть ниже, так как в этой точке не будет дополнительных дна за съедение другого линга

2021-12-03 14:02 UTC, KIBORG04 commented on code/game/gamemodes/modes_gameplays/changeling/powers/absorb.dm
> +		user.regenerate_icons()
```suggestion
```
зачем

2021-12-03 14:02 UTC, KIBORG04 commented on code/game/gamemodes/modes_gameplays/changeling/powers/absorb.dm
> +		sleep(10)
Сделай лучше таймер....

2021-12-03 14:04 UTC, ssbugman commented
Лучше всего не привязывать форму генокрада к числу съеденных а сделать ее абилкой "последнего и решительного", когда генокрад при опасности принимает свой истинный облик чтобы дать бой и длительное время не может снова замаскироваться.

2021-12-03 14:04 UTC, AndroBetel commented
У нас цель ограничить переедание и грифак из-за этого, а не сделать генокрада машиной для убийств по его желанию.

2021-12-03 14:07 UTC, ssbugman commented
Целью должен быть экшен на станции, в том числе благодаря охоте на "монстров". Потому что сейчас у нас нормой является приговаривать к сжиганию без суда по единственному обвинению "ты мутант", хотя по космозакону эта статья предусматривает принудительное вкалывание чистых генов в генетике.

2021-12-03 14:07 UTC, KIBORG04 commented on code/game/gamemodes/modes_gameplays/changeling/powers/absorb.dm
> +/obj/effect/proc_holder/changeling/absorbDNA/proc/check_overeating(mob/living/carbon/human/user)
Лучше да

2021-12-03 14:08 UTC, AndroBetel commented
Ладно как скажешь брат.

2021-12-03 14:55 UTC, AndroBetel commented
Все по ревью сделал.

2021-12-03 20:23 UTC, FoLZer commented on code/game/gamemodes/modes_gameplays/changeling/changeling_power.dm
> +			return 0
```suggestion
	if(ishuman)
		var/mob/living/carbon/human/H = user
		if(!can_be_used_in_abom_form && H.species.name == ABOMINATION)
			to_chat(user, "<span class='warning'>We cannot do that in this form!</span>")
			return 0
	else if(req_human)
		to_chat(user, "<span class='warning'>We cannot do that in this form!</span>")
		return 0
```
У тебя тут 2 проверки на ishuman, очень советую закинуть под одну

2021-12-03 20:23 UTC, FoLZer commented on code/game/gamemodes/roles/changeling.dm
> +		addtimer(CALLBACK(src, .proc/turn_to_abomination), 30)
Я, конечно, могу ошибаться, но тут лучше либо if() ... else if(), либо switch(). Если же без else if() то расставь return.

2021-12-03 20:23 UTC, FoLZer commented on code/game/objects/structures/window.dm
> +	else if(user.dna && user.dna.mutantrace == "adamantine" || user.species.name == ABOMINATION)
```suggestion
	else if((user.dna && user.dna.mutantrace == "adamantine") || (user.species && user.species.name == ABOMINATION))
```

2021-12-03 20:23 UTC, FoLZer commented on code/modules/mob/living/carbon/human/say.dm
> +	if(species.name == ABOMINATION)
Лучше подведи под проверку чуть выше, то есть сделать чтобы если species.name = VOX || VOX_ARMALIS то чтобы не проверяло имя второй раз.

2021-12-03 20:27 UTC, KIBORG04 commented on code/game/objects/structures/window.dm
> +	else if(user.dna && user.dna.mutantrace == "adamantine" || user.species.name == ABOMINATION)
Бетель, можешь это не делать 😄

2021-12-03 20:28 UTC, FoLZer commented on code/game/objects/structures/window.dm
> +	else if(user.dna && user.dna.mutantrace == "adamantine" || user.species.name == ABOMINATION)
Совершенно не уверен что не делать это - безопасно. Но как знаешь

2021-12-03 20:30 UTC, FoLZer commented on code/game/objects/structures/window.dm
> +	else if(user.dna && user.dna.mutantrace == "adamantine" || user.species.name == ABOMINATION)
Тогда вопрос: почему в других местах эта проверка сделана?

2021-12-03 20:32 UTC, KIBORG04 commented on code/game/objects/structures/window.dm
> +	else if(user.dna && user.dna.mutantrace == "adamantine" || user.species.name == ABOMINATION)
например

2021-12-03 20:35 UTC, FoLZer commented on code/game/objects/structures/window.dm
> +	else if(user.dna && user.dna.mutantrace == "adamantine" || user.species.name == ABOMINATION)
Например вот тут
![image](https://user-images.githubusercontent.com/65248062/144669349-d9a14997-530e-485f-a0da-0cc15a1b7d80.png)
Или тут
![image](https://user-images.githubusercontent.com/65248062/144669429-2175cc73-767b-4927-a714-d04d2776d783.png)

2021-12-03 20:39 UTC, KIBORG04 commented on code/game/objects/structures/window.dm
> +	else if(user.dna && user.dna.mutantrace == "adamantine" || user.species.name == ABOMINATION)
А теперь сравни файлы где эта проверка есть, а где ее просто нет.

2021-12-03 20:44 UTC, FoLZer commented on code/game/objects/structures/window.dm
> +	else if(user.dna && user.dna.mutantrace == "adamantine" || user.species.name == ABOMINATION)
Ладно, я так и не увидел особой разницы в использовании, но если так надо то ок. Можешь это не делать ;-;

2021-12-04 12:22 UTC, AndroBetel commented on code/game/gamemodes/modes_gameplays/changeling/changeling_power.dm
> +			return 0
Ты мне всё сломал злодей. рек_хуман тогда нужно было вынести из этого, как оно и есть.

2021-12-04 12:35 UTC, FoLZer commented on code/game/gamemodes/modes_gameplays/changeling/changeling_power.dm
> +			return 0
Без понятия что я тебе там сломал, но 2 проверки не нужны.

2021-12-04 12:37 UTC, AndroBetel commented on code/game/gamemodes/modes_gameplays/changeling/changeling_power.dm
> +			return 0
req_human проверяет, является ли user собственно хуманом. Очевидно, что в сагге оно работает наоборот и проверяя рек_хуман возвращает 0  если ishuman.

2021-12-04 12:40 UTC, FoLZer commented on code/game/gamemodes/modes_gameplays/changeling/changeling_power.dm
> +			return 0
Ну так от моих изменений твоя логика ровно никаким образом не изменилась, только стала чуть сложнее из-за else if

2021-12-04 12:41 UTC, volas commented on code/game/gamemodes/roles/changeling.dm
> +	if(absorbedcount == OVEREATING_AMOUNT / 2)
если кто-то когда-то сделает OVEREATING_AMOUNT нечетным, то условие не будет выполняться

2021-12-04 12:42 UTC, AndroBetel commented on code/game/gamemodes/modes_gameplays/changeling/changeling_power.dm
> +			return 0
Было так, если что.
```
	if(req_human && !ishuman(user))
		to_chat(user, "<span class='warning'>We cannot do that in this form!</span>")
		return 0
```

2021-12-04 12:43 UTC, AndroBetel commented on code/game/gamemodes/roles/changeling.dm
> +	if(absorbedcount == OVEREATING_AMOUNT / 2)
И что сделать с этим....

2021-12-04 12:43 UTC, FoLZer commented on code/game/gamemodes/modes_gameplays/changeling/changeling_power.dm
> +			return 0
Да, а стало 
`	if(!ishuman && req_human)
		to_chat(user, "<span class='warning'>We cannot do that in this form!</span>")
		return 0
`

2021-12-04 12:45 UTC, AndroBetel commented on code/game/gamemodes/modes_gameplays/changeling/changeling_power.dm
> +			return 0
![image](https://user-images.githubusercontent.com/44546836/144709874-ff7a8686-f540-4922-8f8c-a528096c6b69.png)

Ты че врешь а.

2021-12-04 12:46 UTC, FoLZer commented on code/game/gamemodes/modes_gameplays/changeling/changeling_power.dm
> +			return 0
А, ой, не увидел что там скобки не поставил. Вот так правильно
```suggestion
	if(ishuman(user))
		var/mob/living/carbon/human/H = user
		if(!can_be_used_in_abom_form && H.species.name == ABOMINATION)
			to_chat(user, "<span class='warning'>We cannot do that in this form!</span>")
			return 0
	else if(req_human)
		to_chat(user, "<span class='warning'>We cannot do that in this form!</span>")
		return 0
```

2021-12-04 19:48 UTC, AndroBetel commented
Сделал по ревью, абоминации теперь выдается ещё плюсом 6 генов, чтобы купить, например, молоток для большей проходимости, сделал прикольную штуку.
![image](https://user-images.githubusercontent.com/44546836/144722723-ce2f02cb-b980-4193-9e5e-6511fcce4896.png)

2021-12-05 10:02 UTC, volas commented on code/modules/mob/living/carbon/human/examine.dm
> +				msg+= "<span class='warning'>Faces of [get_english_list(victims_names)] can be seen on it's ever changing body...</span>\n"
мне нравится идея :+1:

2021-12-05 10:02 UTC, volas commented on code/modules/mob/living/carbon/human/say.dm
> +	if(species.name == ABOMINATION)
```suggestion

	else if(species.name == ABOMINATION)
```

как вариант

2021-12-05 16:48 UTC, LudwigVonChesterfield commented on code/__DEFINES/mob.dm
> +#define ABOMINATION    "disgusting abomination"
выходит проблема с тем что технические значения (дефайны) почему-то используются напрямую в экзамине вместо какой-то /proc/get_species_name(species_name)

2021-12-06 04:18 UTC, volas approved these changes

2021-12-06 11:33 UTC, MrWestnow commented
Наконец-то появился смысл пережирать экипаж. Спасибо

2021-12-06 12:15 UTC, ssbugman commented
Генок и так душат вовсю из-за легализации ролькоханта на них, лучше эту штуку им дать как абилку последнего шанса когда офицерики кидаются вязать спалившегося. Потому что сейчас по факту два выстрела тазером, полминуты прикладом по голове и генка уезжает в госты.

2021-12-06 12:24 UTC, AndroBetel commented
Зачем ты это второй раз сюда написал?

2021-12-06 12:46 UTC, ssbugman commented
> Зачем ты это второй раз сюда написал?

Второй раз я написал аргументы с учетом уже скопившихся результатов с метой и всех обсуждаемых фич включая тесты которые занерфят генок еще больше и создают необходимость дать генкам что-то чем можно отбиваться при случайном палеве.

2021-12-06 14:53 UTC, Pimap3 commented
@AndroBetel Абоминация может юзнуть ласт резорт и убрать свою искоряженную форму отложив яйцо в другое тело. Абилки и поглащённые гены останутся, но вместо абоминации будет обычный хуман. И получается что это обход всей новой фичи.

2021-12-06 15:30 UTC, TauKitty commented
This pull request has been mentioned on **Tau Ceti Station Forum**. There might be relevant details there:

https://forum.taucetistation.org/t/skrinshoty-iz-space-station-13/3165/14879

2021-12-07 11:21 UTC, volas commented on code/modules/mob/living/carbon/species.dm
> +	speed_mod = 0.3
бетель, почему он такой быстрый

2021-12-07 11:40 UTC, volas requested changes

2021-12-07 11:40 UTC, volas commented on code/modules/mob/living/carbon/species.dm
> +	speed_mod = 0.3
```suggestion
	speed_mod = 7
```

предлагаю как у дион, иначе тут почти сплошные бафы, и даже замедление не заметно или будет бафом для каких-нибудь унатхов

2021-12-07 11:42 UTC, volas commented on code/modules/mob/living/carbon/species.dm
> +	speed_mod = 0.3
> Разве не норма?

форма должна быть неудобством, что-то очень уязвимое, наказание для игрока, а не целью что бы быстрее отъесться и пойти в годмоде грифонить станцию

2021-12-07 11:46 UTC, ssbugman commented on code/modules/mob/living/carbon/species.dm
> +	speed_mod = 0.3
А чем именно генокрады так провинились что их надо наказывать за 6+ фрагов в то время как все другие роли вырезают весь состав СБ не парясь?

2021-12-07 11:55 UTC, kalazus commented on code/modules/mob/living/carbon/species.dm
> +	speed_mod = 0.3
> > Разве не норма?

> форма должна быть неудобством, что-то очень уязвимое, наказание для игрока, а не целью что бы быстрее отъесться и пойти в годмоде грифонить станцию

Зря не читал код. Это голем с топором вообще без замедления. Так что да, скорость у него должна быть маленькая учитывая что они в любом случаи будут абузить разгермы.

2021-12-07 12:00 UTC, antonkomissar commented on code/modules/mob/living/carbon/species.dm
> +	speed_mod = 0.3
Да , он может держать оружие и вполне себе спокойно выживать в узких пространствах(если вкачает нужные абилки). Для убийства достаточно 20-25 попаданий с лазера.

2021-12-07 12:08 UTC, ssbugman commented on code/modules/mob/living/carbon/species.dm
> +	speed_mod = 0.3
Генки все равно будут убивать экипаж, но при этом не будут жрать жертв и все. В чем смысл этого в таком виде?

2021-12-07 14:12 UTC, kalazus commented on code/modules/mob/living/carbon/species.dm
> +	speed_mod = 0.3
> Генки все равно будут убивать экипаж, но при этом не будут жрать жертв и все. В чем смысл этого в таком виде?

Убийство без причины признак ~~дурачины~~ нарушения правила антага. Раньше отнекивались по типу:
- Ты убил 11 членов экипажа?
- Ну мне то жрать хочется, это абилки даёт.
В половине случаев прилетал бан. Теперь будет явно понятно что скоро тебя начнут мочить все, а ты станешь мини-боссом. Но вообще говоря, пока я вижу только баффы. Защита големов, скорость человека, 35 урона с руки, возможность продолжать использовать хлыст, шрик и щит. Да, забрали фейковую смерть и лечение, но зачем оно если у тебя куча резистов, а исцеляться можно химией? Даже спокойно можно сделать форонный пожар и не выходить из него, если не слишком много форона поджигать. 
P.s. не понятно почему у тенелингов такая-же защита от горячего воздуха...

2021-12-07 14:18 UTC, AndroBetel commented
Уменьшил скорость до чуть-чуть быстрее дион, запретил стрелять из пушек.

2021-12-07 15:29 UTC, volas commented on code/modules/mob/living/carbon/species.dm
> +	speed_mod_no_shoes = 5
а он точно не сможет одеть обувь?

2021-12-07 19:28 UTC, AndroBetel commented on code/modules/mob/living/carbon/species.dm
> +	speed_mod_no_shoes = 5
Точно.

2021-12-10 22:03 UTC, KIBORG04 commented
Конфликты почини

2021-12-12 08:06 UTC, volas approved these changes
Тут мы еще наверно не раз вернемся нерфить это чудо, в целом ок и мержреди

2021-12-12 13:08 UTC, TauKitty commented
This pull request has been mentioned on **Tau Ceti Station Forum**. There might be relevant details there:

https://forum.taucetistation.org/t/fidbek-na-metu-na-genokradov/29993/1

2021-12-12 13:12 UTC, TauKitty commented
This pull request has been mentioned on **Tau Ceti Station Forum**. There might be relevant details there:

https://forum.taucetistation.org/t/fidbek-na-metu-na-genokradov/29993/114

2021-12-13 12:08 UTC, TauKitty commented
This pull request has been mentioned on **Tau Ceti Station Forum**. There might be relevant details there:

https://forum.taucetistation.org/t/test-na-genokrada/30277/18

2021-12-15 20:28 UTC, kalazus commented on code/game/objects/structures/window.dm
> +	else if(user.dna && user.dna.mutantrace == "adamantine" || user.species.name == ABOMINATION)
14 Runtime in window.dm:168 : undefined variable /mob/living/carbon/xenomorph/larva/var/species . 
А вот как лярва обошла human не понимаю . Не меняй на mob mob/living/carbon/human, а сделай проверку.

2021-12-15 21:08 UTC, kalazus commented on code/game/objects/structures/window.dm
> +	else if(user.dna && user.dna.mutantrace == "adamantine" || user.species.name == ABOMINATION)
14 Runtime in window.dm:168 : undefined variable /mob/living/carbon/xenomorph/larva/var/species .
А вот как лярва обошла human (почему null-ы не пошли) не понимаю . Не меняй mob на mob/living/carbon/human, а сделай проверку.
Не заметил что помечено как разрешённое, создал новое.

2021-12-19 14:57 UTC, merged

2021-12-20 05:12 UTC, Kurshan commented
Я опоздал. Да и вряд ли кто прислушается. Но люблю я посрать на гитхабе, понимать надо.
Не буду здесь практически касаться самого решения введения абоминаций. С решениями у вас всё и так всё плохо.

1) Ужасный костыльный код. Я вроде слышал, что Бетель не кодер, но тогда вопрос зачем он взялся за это.
1.1) С тех стороны - can_be_used_in_abom_form просто великое недоразумение. Ладно с тем, что доп. булеан флаг, хотя некрасиво. Так дело в том, что вы, добавив эту проверку, не удосужились убрать абилки из магазина, потому происходит смешная ситуация, что человек покупает абилку, но не может ею пользоваться и он узнаёт об этом только в момент использования. Тоже самое с теми абилками, что уже куплены. но ими почему-то нельзя пользоваться. даже рефанд не сделать.
2) Глобальный саунд с огромными красными буквами при превращении это просто шутка какая-то. С таким же успехом можно было просто гибать генокрада, результат будет идентичным, да ещё никак не обоснованным.
3)  Тут майор доебенко к ченжлогу на связи.
>При поедании 6 человек генокрад становится жестокой машиной для убийств.
Абсолютное и наглое враньё же, ну, скорее становится живой мишенью, тем более никто не скрывает, что это нерф генокрадов.
4) На остальных билдах, откуда украдена идея есть механ вокруг абоминации. Условно быстрое поедание. Удешевление абилок. Здесь же просто тотальный нерф с аналогом гиба.
5) Поедание макак даёт 0.5 поинта, а засчитывается как нормальная кукла. Опять же либо недоработка-незнание, либо ПОДЕЛОМ ЭТИМ ГЕНОКРАДАМ УХХХХ.
6)Странно, что зачем-то сделали хардкодом значение в шесть тел, а не через конфиг.
7)Если это кого-то волнует вообще, я бы собирал статистику с тем, сколько вообще абоминаций появляется и как у них не то что с винрейтом (да и считать по винрейту как любят ваши менетеры - ужасная затея), а с выживаемостью.

2021-12-20 06:35 UTC, KIBORG04 commented
Щас бы критиковать код хед админа тау кеки...

2021-12-20 06:37 UTC, AndroBetel commented
Так он сам бывший админ.

2021-12-20 06:40 UTC, Kurshan commented
Я герой тау киты, мне можно

2021-12-20 07:31 UTC, kalazus commented on code/game/objects/structures/window.dm
> +	else if(user.dna && user.dna.mutantrace == "adamantine" || user.species.name == ABOMINATION)
Я могу многое понять, но мерж ТМ-а создающего 50+ рантаймов я понять не могут.

2021-12-20 07:42 UTC, volas commented on code/game/objects/structures/window.dm
> +	else if(user.dna && user.dna.mutantrace == "adamantine" || user.species.name == ABOMINATION)
о, я этого не видел

2021-12-20 07:45 UTC, KIBORG04 commented on code/game/objects/structures/window.dm
> +	else if(user.dna && user.dna.mutantrace == "adamantine" || user.species.name == ABOMINATION)
Это очень похоже на проблему не этого ПРа

2021-12-20 07:55 UTC, kalazus commented on code/game/objects/structures/window.dm
> +	else if(user.dna && user.dna.mutantrace == "adamantine" || user.species.name == ABOMINATION)
Это проблема этого пра так как почему-то attack_hand что может приходить от любого моба изменяется на "может идти от человека". Типо, в бьёнде, вроде, нет полиморфизма, и изменять типы в функциях на более частный нельзя.