респрайт коктейлей парт 3
TauCetiStation/TauCetiClassic pull request #8353
Opened 2021-12-06 18:41 UTC by AndroBetel

## Описание изменений
![image](https://user-images.githubusercontent.com/44546836/144903287-0bf55441-4036-48d1-ba88-3a6beb90dd8d.png)

## Почему и что этот ПР улучшит
Красоту.
## Авторство
Ded, Artbsd
## Чеинжлог
:cl:  Ded, Artbsd
- image: Респрайт коктейлей. Опять.

2021-12-06 18:41 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2021-12-06 19:08 UTC, CeUvi commented
эх стаканы украли а упомянуть забыли.

2021-12-06 19:16 UTC, AndroBetel commented
Надо коуп энд сиз.

2021-12-06 20:22 UTC, AndroBetel commented
Эээ походу это мне надо коуп энд сиз.

2021-12-07 05:06 UTC, TauKitty commented
This pull request has been mentioned on **Tau Ceti Station Forum**. There might be relevant details there:

https://forum.taucetistation.org/t/vernut-starye-napitki-golosovanie/29930/21

2021-12-07 07:07 UTC, Sakuya-Izayoi commented
что это за черная полоска на цветных стаканах снизу? стакан пытается быть прозрачным и непрозрачным одновременно?

2021-12-07 19:30 UTC, KIBORG04 commented
Это типо дно выпукло вверх

2021-12-10 20:48 UTC, LiLJard approved these changes

2021-12-11 09:38 UTC, UDaV73rus requested changes
стаканы сеуви, но с неправильными оверлеями жидкости, в дискорде все исходники сеуви скинул

Жидкость должна быть такой
![image](https://user-images.githubusercontent.com/33157992/145671888-26c616fb-eccd-4886-aa9b-b542b87850f3.png)

2022-02-09 21:44 UTC, KIBORG04 commented
Когда поправите пинганите меня и я открою ПР. Ну или сами откроете..

2022-02-09 21:44 UTC, closed without merging

2022-06-03 08:39 UTC, TauKitty commented
Этот запрос на извлечение был упомянут в **Tau Ceti Station Forum**. Там могут быть соответствующие подробности:

https://forum.taucetistation.org/t/resprajt-koktejlej/33947/1