xeno notes for xenovisors
TauCetiStation/TauCetiClassic pull request #8358
Opened 2021-12-07 14:10 UTC by Sakuya-Izayoi

## Описание изменений
Ксенонотесы для ксеновизоров. Туда могут писать как админы, так и ксеновизоры. Сделано это для того, чтобы ксеновизоры без доступа к нотесам (то есть любые ванильные ксеновизоры) могли оставлять какие-то пометки насчет ксеноповедения игрока.

## Почему и что этот ПР улучшит
Проще ксеновизорить.

## Авторство

## Чеинжлог

2021-12-07 14:10 UTC, TauKitty commented
###### Changelog status: :radio_button: No changelog

2021-12-07 17:03 UTC, volas commented on code/modules/admin/player_notes.dm
>  	note = sanitize(note)
note_type нужно санитайзить, как тут другие переменные. Скорее всего подойдет сделать хардкод-список типов и проверять что note_type в нем

2021-12-07 17:07 UTC, Sakuya-Izayoi commented on code/modules/admin/player_notes.dm
>  	note = sanitize(note)
в топике это проверяется

2021-12-09 01:09 UTC, volas requested changes

2021-12-09 01:09 UTC, volas commented on code/modules/admin/admin.dm
> +#undef PLAYERINFOS
тут несколько очень не очевидных на мой взгляд дефайнов, я не могу сходу разобраться что происходит. Почему андефа, странные названия. Например ``PLAYERINFOS`` - возможно стоит переименовать сам дефайн во что-то более говорящее (и специфичное во избежание пересечений, да) и переменную тоже как-то более говоряще обозвать.

2021-12-09 01:09 UTC, volas commented on code/modules/admin/player_notes.dm
> +	if(!(note_type in global.player_info_type_rights))
старая проверка лучше - она распространена всюду в билде и сходу понятна. Лучше тут не делать магию а просто прописать явно кому какие права нужны и в каких случаях

2021-12-09 07:45 UTC, Sakuya-Izayoi commented on code/modules/admin/admin.dm
> +#undef PLAYERINFOS
Задача этих дефайнов проста. Избежать повторения кода. Чтобы поменять флаги доступа (или юай текст) к каким либо нотисам все что нужно сделать это вписать нужную информацию в PLAYERINFOS дефайн.

2021-12-09 07:50 UTC, Sakuya-Izayoi commented on code/modules/admin/player_notes.dm
> +	if(!(note_type in global.player_info_type_rights))
Старая проверка мне не нравится тем, что если вдруг мы захотим поменять флаги доступа к конкретному типу нотесов, придется менять их в коде везде. А сейчас их достаточно поменять в одном месте. Ну и если вдруг появится какой-то новый тип нотисов, все что надо будет сделать это обновить тип колонки в бд и добавить новый дефайн.

2021-12-09 07:57 UTC, volas commented on code/modules/admin/admin.dm
> +#undef PLAYERINFOS
Поищи про принцип KISS, повторение кода не такая большая проблема что бы бороться с этим обфускацией исходников. Как компромисс - ты можешь вынести функционал в какую-то тупую и понятную функцию и вызывать уже её.

2021-12-10 13:36 UTC, Sakuya-Izayoi commented on code/modules/admin/admin.dm
> +#undef PLAYERINFOS
мы можем сойтись на том что я дам дефайнам более говорящие названия и добавлю несколько пояснительных комментариев?

2021-12-11 16:22 UTC, volas commented on code/modules/admin/admin.dm
> +#undef PLAYERINFOS
Не, я сейчас это еще раз открыл на свежую голову и это всё еще не очень, даже если переименуешь мало что измениться. Я уверен, что ты сам через год если откроешь это - тоже ничего не поймешь.

Если думаешь, что я не прав - можно попытаться к какому-нибудь третьему мейнтейнеру со стороны обратиться рассудить.

2022-01-15 14:50 UTC, closed without merging