guard update
TauCetiStation/TauCetiClassic pull request #8370
Opened 2021-12-08 21:19 UTC by Sakuya-Izayoi

## Описание изменений
timezone test

## Почему и что этот ПР улучшит

## Авторство

## Чеинжлог

2021-12-08 21:19 UTC, TauKitty commented
###### Changelog status: :radio_button: No changelog

2021-12-09 00:59 UTC, volas commented on code/modules/client/guard.dm
> +/datum/guard/proc/load_browser_checks()
лучше оставить в гунчате вместе с остальными, или перенести всё сюда, если там неизвестно что с гунчатом станет

2021-12-09 01:02 UTC, volas commented on code/modules/client/guard.dm
> +	var/stored_href = null
не вижу смысла, можно было бы оставить прокерку что данные пришли и не переписывать, а делать отдельный тест из этого вряд ли требуется

2021-12-11 10:20 UTC, volas requested changes

2021-12-11 10:20 UTC, volas commented on code/modules/client/guard.dm
> +			var/expected_time = (timeoffset / 3600 + round(world.timeofday / 36000)) % 24
Посмотри в сторону браузерного getTimezoneOffset(), у тебя будет две таймзоны которые просто сравнить и не нужно будет дергать сервер еще (бьенд иногда странно работает с часовыми поясами).
Нужно будет только к одному формату привести и не ошибиться со знаком <https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/getTimezoneOffset>

2021-12-11 10:20 UTC, volas commented on code/modules/client/guard.dm
> +				var/deviation_weight = 0.7
0.5 должно быть достаточно, хотя-бы на первое время (где она сработает, скорее всего сработают другие). + нужно добавить вес проверки в ``total_alert_weight``

2021-12-11 17:14 UTC, volas approved these changes

2021-12-11 17:21 UTC, merged