Возвращаю распространение вирусов только через кровь
TauCetiStation/TauCetiClassic pull request #8398
Opened 2021-12-13 18:52 UTC by Lexakr

## Описание изменений
У нас на википедии 3 типа распространения вирусов, да и всегда так было (воздух, контакт, кровь), но в игре по-факту только первые 2, онли через кровь просто не существует (не считая зомбу вирус). Собственно постарался особо ничего не трогать, починить и привести в более правильный вид. Раньше аирборн дропался с шансом 60/40 относительно контактного, теперь будет 40/30/30 соответственно
## Почему и что этот ПР улучшит
Игра за вирусолога разнообразится вирусами, которые передаются только через кровь, что откроет путь для контролируемого заражения вирусами с полезными штуками (без попутного заражения почти всей станции)
## Авторство

## Чеинжлог
:cl:
 - bugfix: В вирусологии можно получить вирусы с путем передачи только через кровь.

2021-12-13 18:52 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2021-12-13 19:05 UTC, Sakuya-Izayoi commented on code/modules/virus2/disease2.dm
> +	else
я бы использовал pickweight

2021-12-13 19:05 UTC, Sakuya-Izayoi commented on code/modules/virus2/disease2.dm
> +	if (src.spreadtype == DISEASE_SPREAD_BLOOD)
```suggestion
	if (spreadtype == DISEASE_SPREAD_BLOOD)
```

2021-12-13 19:05 UTC, Sakuya-Izayoi commented on code/modules/virus2/disease2.dm
> +#undef DISEASE_SPREAD_BLOOD
```suggestion
#undef DISEASE_SPREAD_BLOOD

```

2021-12-13 19:05 UTC, Sakuya-Izayoi commented on code/modules/virus2/disease2.dm
> +	if(src.spreadtype == DISEASE_SPREAD_AIRBORNE && prob(10))
```suggestion
	if(spreadtype == DISEASE_SPREAD_AIRBORNE && prob(10))
```

2021-12-13 19:05 UTC, Sakuya-Izayoi commented on code/modules/virus2/disease2.dm
> +	if (src.spreadtype == DISEASE_SPREAD_BLOOD)
а нужен ли вообще этот чек? разве до вызова спреда не чекается спредтайп?

2021-12-13 19:19 UTC, Lexakr commented on code/modules/virus2/disease2.dm
> +	else
Еще немного изменил шансы, 50% воздушный, 30 контакт и 20 кровь, чтобы было сложнее получить наиболее желанные способы (если не для грифа)

2021-12-13 19:20 UTC, Lexakr commented on code/modules/virus2/disease2.dm
> +	var/list/spread_types = list(DISEASE_SPREAD_AIRBORNE = 5, DISEASE_SPREAD_CONTACT = 3, DISEASE_SPREAD_BLOOD = 2)
Думаю с такими шансами будет правильнее, т.к для исследования и применения последний путь передачи самый выгодный

2021-12-13 22:14 UTC, Sakuya-Izayoi requested changes
как в дискорде обсуждалось, ждем пока автор заменит везде строки на дефайны

2021-12-14 14:55 UTC, Sakuya-Izayoi approved these changes

2021-12-15 19:51 UTC, Lexakr commented
Что-то еще?

2021-12-16 00:02 UTC, merged