body with its head and brain cloneable again
TauCetiStation/TauCetiClassic pull request #8399
Opened 2021-12-13 21:14 UTC by notkripton

## Описание изменений
К изменениям #8233 добавил проверку на совпадения днк таргета и брейнмоба, т.е. теперь голову можно снова пришивать к родному телу и клонировать.
## Почему и что этот ПР улучшит
минус костыль
## Авторство

## Чеинжлог
:cl:
- tweak: оторванную голову/мозг снова можно пришить к родному телу и клонировать

2021-12-13 21:14 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2021-12-13 21:20 UTC, KIBORG04 commented
> минус костыль

костыля и не было, а теперь есть

2021-12-13 22:00 UTC, notkripton commented
> костыля и не было, а теперь есть

Раньше с причиной выпила клонирования через болванчиков было выпилено вообще любое клонирование после отрубания голов (костыль)
Здесь оно впилено обратно, но с проверкой на днк тел, и трейт_но_клоне все равно будет кидаться если проверка не пройдена (вроде не костыль)

2021-12-13 22:17 UTC, Sakuya-Izayoi commented
если игроки в этом нуждаются...

вообще я бы сделал проще, я на одном билде видел что можно бошку клонировать без тела, так даже круче наверное. единственное что надо у головы и мозга сохранять трейт ноклон, я не знаю, сохраняется ли он сейчас

2021-12-14 06:10 UTC, LoTaRk-FroG commented
а что мешает вколоть нужное днк другому трупу и пришить бошку?

2021-12-14 06:57 UTC, kalazus commented
Лучше наверное просто добавить мозгу время до смерти когда его достают из человечка (но придётся много где его убирать).

2021-12-14 17:47 UTC, notkripton commented
> единственное что надо у головы и мозга сохранять трейт ноклон, я не знаю, сохраняется ли он сейчас

Когда я тестил он сохранялся

2021-12-14 18:59 UTC, Sakuya-Izayoi requested changes

2021-12-14 18:59 UTC, Sakuya-Izayoi commented on code/game/dna/dna_modifier.dm
> +					B.client.eye = src
итем брейн хранит своего моба в переменной брейнмоб, это во-первых, во-вторых, можно обойтись без ифа с ?. оператором доступа. в-третьих, вряд ли нужно выставлять брейну перспективу на дна модифаер, я не понимаю зачем это нужно.

2021-12-14 18:59 UTC, Sakuya-Izayoi commented on code/game/dna/dna_modifier.dm
> +			BR.loc = src
эээ, нет. это так не делается. надо со стороны дна модифаера обрабатывать что к тебе пришел не моб, а голова/мозг и в том месте где клонинг компьютер просит моба возвращать либо моба напрямую, либо моба из мозга.

2021-12-14 18:59 UTC, Sakuya-Izayoi commented on code/modules/surgery/braincore.dm
> -	ADD_TRAIT(target, TRAIT_NO_CLONE, GENERIC_TRAIT) // so they cannot be cloned
эээ вернул

2021-12-14 19:06 UTC, notkripton commented on code/modules/surgery/braincore.dm
> -	ADD_TRAIT(target, TRAIT_NO_CLONE, GENERIC_TRAIT) // so they cannot be cloned
Хехе) 😄
Не ну если без голову без тела можно клонить, а с телом нельзя какой-то бред получается

2021-12-14 19:15 UTC, notkripton commented on code/game/dna/dna_modifier.dm
> +			BR.loc = src
ээ, я не понял про что ты
сейчас когда сканер закрывают он проверяет пришел к нему хуман, хед или брейн. если хуман, то возвращает оккупантом хумана, если брейн или голова, то возвращает моба, сидящаего внутри них (он один и тот же - моб/ливинг/карбон/брейн). к клонинг компьютеру приходит УЖЕ моб, которого и надо клонить.

2021-12-14 19:35 UTC, notkripton commented on code/game/dna/dna_modifier.dm
> +					B.client.eye = src
> во-вторых, можно обойтись без ифа с ?. оператором доступа.

сделал

2021-12-14 19:45 UTC, notkripton commented on code/game/dna/dna_modifier.dm
> +					B.client.eye = src
> итем брейн хранит своего моба в переменной брейнмоб, это во-первых

я дурак. я знал, что эта переменная сущетсвует и изначально ее и применял, но в конечном счете забыл про нее...
сделал через брейнмоб

2021-12-14 19:56 UTC, Sakuya-Izayoi commented on code/game/dna/dna_modifier.dm
> +			BR.loc = src
окей, тогда окей, тогда вместо loc = должно быть forceMove

2021-12-15 12:51 UTC, notkripton commented on code/game/dna/dna_modifier.dm
> +			BR.loc = src
сделал

2021-12-16 21:14 UTC, Sakuya-Izayoi commented on code/modules/surgery/braincore.dm
> -	ADD_TRAIT(target, TRAIT_NO_CLONE, GENERIC_TRAIT) // so they cannot be cloned
Это нужно для того, чтобы нельзя было превращать таяран в людей и тому подобное.

2021-12-17 05:20 UTC, notkripton commented on code/modules/surgery/braincore.dm
> -	ADD_TRAIT(target, TRAIT_NO_CLONE, GENERIC_TRAIT) // so they cannot be cloned
Хорошо.

2021-12-18 01:17 UTC, Sakuya-Izayoi commented on code/game/dna/dna_modifier.dm
>  			break
а что будет если на тайл модифаера одновременно поставить карбона, брейн и голову?

2021-12-18 06:37 UTC, notkripton commented on code/game/dna/dna_modifier.dm
>  			break
Ничего. Он проверит карбона и я засунет его в occupant. Голову и мозг он проверять не будет, потому что у них стоит `if(occupant) continue` в начале цикла.

2021-12-25 20:39 UTC, Sakuya-Izayoi commented on code/game/dna/dna_modifier.dm
>  			break
наверное там брейк нужно поставить

2021-12-25 20:43 UTC, Sakuya-Izayoi commented on code/game/dna/dna_modifier.dm
>  			break
+ наверное стоит сократить код, а именно вынести все свзяанное с клиентом нового `occupant` за циклы.

2021-12-26 11:20 UTC, notkripton commented on code/game/dna/dna_modifier.dm
>  			break
\+

2022-01-08 09:10 UTC, Sakuya-Izayoi commented on code/game/dna/dna_modifier.dm
> +			H.forceMove(src)
форсмув тоже можно вынести за цикл

2022-01-09 22:01 UTC, notkripton commented on code/game/dna/dna_modifier.dm
> +			H.forceMove(src)
сделал, но, как по мне, старый вариант был красивее

2022-01-12 07:20 UTC, Sakuya-Izayoi approved these changes

2022-01-15 12:02 UTC, KIBORG04 commented on code/game/dna/dna_modifier.dm
> +			if(C.buckled) continue
https://github.com/TauCetiStation/TauCetiClassic/blob/master/.github/wiki/CODE_CONVENTION.md#операторы-управления-if-while-for-и-тд

2022-01-15 12:03 UTC, KIBORG04 commented on code/game/dna/dna_modifier.dm
> +			if(occupant) break
https://github.com/TauCetiStation/TauCetiClassic/blob/master/.github/wiki/CODE_CONVENTION.md#операторы-управления-if-while-for-и-тд

2022-01-15 12:03 UTC, KIBORG04 commented on code/game/dna/dna_modifier.dm
> +			if(occupant) break
https://github.com/TauCetiStation/TauCetiClassic/blob/master/.github/wiki/CODE_CONVENTION.md#операторы-управления-if-while-for-и-тд

2022-01-15 12:03 UTC, KIBORG04 commented on code/game/dna/dna_modifier.dm
>  		for(var/mob/living/carbon/C in loc)
Вместо 3х циклов сделай 1 с истайпами

2022-01-15 12:09 UTC, KIBORG04 commented on code/game/dna/dna_modifier.dm
> +		var/atom/movable/occupant_item
Нейминг переменной плох. Почему `_item` если ты до этого явно указываешь, что тут может быть всё, начиная с атом_мувейблов.

2022-01-16 21:02 UTC, notkripton commented on code/game/dna/dna_modifier.dm
> +		var/atom/movable/occupant_item
Поменял это и все что выше

2022-01-18 15:00 UTC, merged