мыло респрайт+реворк
TauCetiStation/TauCetiClassic pull request #8446
Opened 2021-12-30 19:40 UTC by AndroBetel

## Описание изменений
![image](https://user-images.githubusercontent.com/44546836/147782936-4c8378e7-6f10-4c17-9561-808fc344a058.png)
Мыло теперь можно есть при клике по себе на хелпе, на любом другом интенте будешь себя мыть, внутри клинер, в синди-мыле чуть-чуть цианида.
Клинер при принятии внутрь дамажит токсинами едва-едва и заставляет куклу икать, пуская пузырьки.
## Почему и что этот ПР улучшит
Красоту.
## Авторство
Sprites by LiJard
https://freesound.org/people/ceoux/sounds/338196/ звук икания.
## Чеинжлог
:cl:LiJard
- image: Респрайт мыла.
- rscadd: Мыло теперь можно есть.

2021-12-30 19:40 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2021-12-30 20:02 UTC, Deahaka commented
Большой спрайт мыла удобен, если ты ним пользуешься для всех тех дел, для чего вообще его берут. С маленьким спрайтом его прийдётся забирать райткликом после себя, а это как-то плохо

2021-12-30 20:02 UTC, kalazus commented
1) Зачем жрать мыло?
2) Зачем жрать мыло на хелпе, если это токсин?

2021-12-30 20:04 UTC, AndroBetel commented
Жрать мыло это смешно.

2021-12-30 20:43 UTC, Lafrien commented
Хотя бы поменяй с хелпа на харм пожирание мыла. Я часто мою себя и других мылом. Надеюсь я не стану их на хелпе заставлять жрать его.

2021-12-30 21:08 UTC, Sakuya-Izayoi commented on code/modules/mob/living/silicon/robot/robot_modules.dm
> +	modules += new /obj/item/weapon/reagent_containers/food/snacks/soap/nanotrasen(src)
наверное будет забавно если робот скормит свое мыло кому-нибудь и не сможет его вернуть?

2021-12-30 21:08 UTC, Sakuya-Izayoi commented on code/modules/reagents/reagent_types/Chemistry-Miscellaneous.dm
> +		M.say("Ик.")
как сказали в обсуждении, замени на эмоут.

2021-12-30 23:09 UTC, AndroBetel commented on code/modules/mob/living/silicon/robot/robot_modules.dm
> +	modules += new /obj/item/weapon/reagent_containers/food/snacks/soap/nanotrasen(src)
Я ХЗ, что с этим сделать.

2021-12-30 23:18 UTC, AndroBetel commented
Поменял на харм.

2021-12-31 04:33 UTC, CeUvi commented
харам.

2021-12-31 05:55 UTC, WatlerJe commented
Идея хорошая, но спрайты мне не нравятся. В связи с этим предлагаю свои 
![image](https://user-images.githubusercontent.com/19796920/147806128-d2b66f99-2f69-44a5-99e3-94359dd840c6.png)

Ссылка на спрайты: https://dropmefiles.com/GmTjj

2021-12-31 07:15 UTC, UDaV73rus commented
:dollar:

2021-12-31 07:24 UTC, UDaV73rus requested changes
не центрировано

2021-12-31 10:44 UTC, AndroBetel commented
Ватлера похитили на синдикатские кирпичные заводы.

2021-12-31 10:48 UTC, Kurshan commented
Обнови описание про с хелпа  харм и лучше отразить это в чейнжлоге

2022-01-06 22:35 UTC, liteyzz commented
Прикольная идея с пожиранием мыла, но спрайты зачем менять?
Эти спрайты уже как часть культуры мне одному жалко? 
Может чтобы съесть мыло нацелиться на рот в хелпе, вроде мудро и логично и практично, если кого-то накормить мылом то как раз таки на рот в хелпе, если ударить то харм

2022-01-08 12:42 UTC, GermanSUS commented
Добавьте в крафт уже мыло в носке на 10 дамага как у станбатона

2022-01-09 11:49 UTC, KIBORG04 commented on code/modules/reagents/reagent_types/Chemistry-Miscellaneous.dm
> +		flick_overlay(I, viewing, 30)
замени флик_оверлей и сбор вьюверсов на один прок `flick_overlay_view()`

2022-01-19 10:32 UTC, Pimap3 commented
> Прикольная идея с пожиранием мыла, но спрайты зачем менять? Эти спрайты уже как часть культуры мне одному жалко? Может чтобы съесть мыло нацелиться на рот в хелпе, вроде мудро и логично и практично, если кого-то накормить мылом то как раз таки на рот в хелпе, если ударить то харм

Прикол в том, что на хелпе по рту, ты моешь свое лицо от краски на нем(баллончиком по роже). А так ты не сможешь ебало свое помыть по-итогу

2022-01-19 17:45 UTC, TEXH4Pb commented
> Прикол в том, что на хелпе по рту, ты моешь свое лицо от краски на нем(баллончиком по роже). А так ты не сможешь ебало свое помыть по-итогу

Что мешает перенести мытьё лица на клик по голове на хелпе?

2022-01-20 11:39 UTC, LiLJard commented
> Идея хорошая, но спрайты мне не нравятся. В связи с этим предлагаю свои 
> 

Замутил гибрид и взял лучшее от каждой версии
![image](https://user-images.githubusercontent.com/77955747/150331863-11b71c88-e088-4aab-8abc-40116606cd4b.png)

2022-01-22 16:43 UTC, AndroBetel commented
Сделал как выше.

2022-01-24 04:41 UTC, UDaV73rus approved these changes

2022-01-24 19:50 UTC, KIBORG04 commented
Конфликты

2022-02-02 18:17 UTC, AndroBetel commented
Пофиксил конфликты.

2022-02-04 14:56 UTC, merged