респрайт биобанки
TauCetiStation/TauCetiClassic pull request #8448
Opened 2021-12-30 23:47 UTC by AndroBetel

## Описание изменений
![image](https://user-images.githubusercontent.com/44546836/147794884-41cfcb28-6d86-4caa-81ca-cd95c5f516e2.png)

## Почему и что этот ПР улучшит
КРАСИВО.
## Авторство
LiJard
## Чеинжлог
:cl:LiJard
- image: Респрайт банки с биогелем.

2021-12-30 23:47 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2021-12-31 00:03 UTC, KIBORG04 commented on code/game/objects/items/devices/biocan.dm
> +			add_overlay(image(icon, "overlay"))
1. Назови спрайт "overlay" более подходяще
2. Зачем этот спрайт вообще нужен? Тут же юзается оверлей самой бошки, а не какой-то статичный уже нарисованный
3. 
```suggestion
			add_overlay(display_headobj)
			add_overlay(image(icon, "overlay"))
```

2021-12-31 00:04 UTC, KIBORG04 commented on code/game/objects/items/devices/biocan.dm
> +		cut_overlays()
```suggestion
		cut_overlays(display_headobj)
```

2021-12-31 04:35 UTC, CeUvi commented
почему голова в банке выглядит так, будто она вовсе не в банке.

2021-12-31 04:46 UTC, WatlerJe commented
The Church of St. Beobanka

2021-12-31 04:59 UTC, KIBORG04 commented
> почему голова в банке выглядит так, будто она вовсе не в банке.

потому что бетель закодил кринж и накидывает оверлеи, а не андерлеи

2021-12-31 05:06 UTC, volas commented
Почему розовый, как же отсылка на футураму? И спрайт в руке как-то напоминает недавние напитки

2021-12-31 07:20 UTC, UDaV73rus commented
оверлей накладывающийся на голову в банке - размером с лысую голову. А если голова будет больше из-за прически например, или вокс

2021-12-31 10:49 UTC, Kurshan commented
Вся суть спрайта была в футураме, да.

2022-01-07 10:09 UTC, LiLJard approved these changes
Оч крутой спрайт, оч

2022-01-20 11:44 UTC, LiLJard requested changes
Пока не мержим

2022-01-24 19:50 UTC, KIBORG04 commented
Конфликты

2022-02-14 23:01 UTC, closed without merging