FixCloning
TauCetiStation/TauCetiClassic pull request #8539
Opened 2022-01-26 12:07 UTC by LoTaRk-FroG

## Описание изменений
убрал три строчки, на клонирование неклонируемых мобов и головы отдельно от тела это не повлияет 
## Почему и что этот ПР улучшит
Минус баг
## Авторство

## Чеинжлог

2022-01-26 12:07 UTC, TauKitty commented
###### Changelog status: :radio_button: No changelog

2022-01-26 18:24 UTC, Sakuya-Izayoi requested changes

2022-01-26 18:24 UTC, Sakuya-Izayoi commented on code/game/machinery/computer/cloning.dm
> -	if (isnull(subject) || !isbrain(subject) || !subject.dna)
Для начала следует разобраться, что здесь происходит. Если убрать проверку на нулл из функции вовсе, то двумя строчками ниже будет `null.suiciding`.

2022-01-26 18:27 UTC, notkripton commented
А ой планировал сделать это сам, но тут человек взялся за меня...

2022-01-26 18:30 UTC, notkripton requested changes

2022-01-26 18:30 UTC, notkripton commented on code/game/machinery/computer/cloning.dm
> -		scantemp = "Error: Unable to locate valid genetic data."
Нет, это так не делается. Эти три строчки важны и удалять их не надо. Сделай вот так:
![image](https://user-images.githubusercontent.com/75007994/151224420-7bf4ed9b-7a89-4c7a-b881-a46b8edad37c.png)
И можно мержить

2022-01-26 18:40 UTC, notkripton requested changes

2022-01-26 18:40 UTC, notkripton commented on code/game/machinery/computer/cloning.dm
>  			return
Нет, так делать не надо. Удалять все три строчки будет ошибкой, ибо там находятся важные проверки, без которых будут рантаймы (например null.suiciding как писал гетап в своем ревьюве)
Вот как это пофиксил бы я (такой варианрт и задумывался изначально, просто я прогляделся):

```suggestion
			return
	else
		if(!isbrain(subject))
			scantemp = "Error: Unable to locate valid genetic data."
			return
	if (isnull(subject) || !subject.dna)
```
Сделай так и по идее можно мержить

2022-02-04 11:17 UTC, LoTaRk-FroG commented
Мъомомомомъмъмомо

2022-02-04 11:17 UTC, closed without merging