Relay module linkage fix
TauCetiStation/TauCetiClassic pull request #8543
Opened 2022-01-27 20:07 UTC by Dushess0

## Описание изменений
Раньше сделанные в протолате реле не работали от слова совсем.
## Почему и что этот ПР улучшит
Теперь сделанные новые модули реле будут работать, как и оригинальный.
## Авторство
Dushess
## Чеинжлог
- bugfix: Исправлен баг когда созданные в протолате модули реле для ригов не работали.

2022-01-27 20:07 UTC, TauKitty commented
###### Changelog status: :radio_button: No changelog

2022-02-06 19:57 UTC, LudwigVonChesterfield commented
> - bugfix: Исправлен баг когда созданные в протолате модули реле для ригов не работали.

Багфикс: исправлен баг

Предлагаю заменить на что-то типо
bugfix: Созданные в протолате модули реле для ригов работают.

2022-02-06 19:57 UTC, LudwigVonChesterfield commented on code/modules/clothing/spacesuits/rig/modules/utility.dm
> +	if(relay.autolinkers)
А как линкуются те которые НЕ сделаны в автолате?

2022-02-07 19:09 UTC, Dushess0 commented on code/modules/clothing/spacesuits/rig/modules/utility.dm
> +	if(relay.autolinkers)
То реле что в риге РД раундстартом линковалось по этой логике. То есть Хаб  на станци  при инициализации сам подсоединялся в тому реле.  

```
#code\game\machinery\telecomms\presets.dm

/obj/machinery/telecomms/hub/preset
	id = "Hub"
	network = "tcommsat"
	autolinkers = list("hub", "relay", "c_relay", "s_relay", "m_relay", "r_relay", "science", "medical", "p_relay",
	"supply", "common", "command", "engineering", "security",
	"receiverA", "receiverB", "broadcasterA", "broadcasterB")
```
```
#code\game\machinery\telecomms\telecomunications.dm 

/obj/machinery/telecomms/atom_init_late()
	if(autolinkers.len)
		// Links nearby machines
		if(!long_range_link)
			for(var/obj/machinery/telecomms/T in orange(20, src))
				add_link(T)
		else
			for(var/obj/machinery/telecomms/T in telecomms_list)
				add_link(T)
```

2022-02-07 20:35 UTC, LudwigVonChesterfield commented on code/modules/clothing/spacesuits/rig/modules/utility.dm
> +	if(relay.autolinkers)
ну а теперь оно будет линковаться дважды? когда инициализируется хаб, и когда инициализируется реле

2022-02-07 21:48 UTC, Dushess0 commented on code/modules/clothing/spacesuits/rig/modules/utility.dm
> +	if(relay.autolinkers)
Нет, все так же линкуется один раз
![image](https://user-images.githubusercontent.com/44201461/152877354-0621d557-0c13-4af6-b000-35aea9c8f4b0.png)
А вот если заспаунить ещё одно портативное реле
![image](https://user-images.githubusercontent.com/44201461/152877552-ffd92937-0bf5-44c0-ad71-2b5bccaa79c9.png)

2022-02-08 08:56 UTC, LudwigVonChesterfield commented on code/modules/clothing/spacesuits/rig/modules/utility.dm
> +	if(relay.autolinkers)
ну правильно, ссылки добавляются вот таким образом в список:
```
					links |= T
					```
то есть сколько бы раз оно не добавляло ссылку, в списке она была бы одна

рекомендую дебаггинг тулзой пройтись, или просто выводы добавить и у линковки реле и у телекомов, реле из рига РД будет дважды линковаться

2022-02-09 15:40 UTC, Dushess0 commented on code/modules/clothing/spacesuits/rig/modules/utility.dm
> +	if(relay.autolinkers)
Да, может оно будет два раза линковатся, но ведь на логику это никак не влияет и ничего не ломает.

2022-02-09 20:09 UTC, LudwigVonChesterfield commented on code/modules/clothing/spacesuits/rig/modules/utility.dm
> +	if(relay.autolinkers)
нужно ли телекомму пытаться линкануться к реле, если реле при спавне будет искать телекоммы?

если скажешь что "а что если реле заспавнится то хаба телекоммов" - советую глянуть в сторону atom_init_late

2022-02-15 23:14 UTC, LudwigVonChesterfield requested changes
Если уберёшь двойное линкование - готов мержить. Я предлагаю убрать у хаба линкование к реле, а линкование автолинк реле к хабу перенести в /atom_init_late().

2022-02-19 18:25 UTC, Dushess0 commented
Добавил в init_late, проверил, работает. 
```
/obj/item/rig_module/mounted_relay/atom_init()
	. = ..()
	relay = new relay_type(src)
	return INITIALIZE_HINT_LATELOAD

/obj/item/rig_module/mounted_relay/atom_init_late()
	for(var/obj/machinery/telecomms/T in telecomms_list)
		if(istype(T, /obj/machinery/telecomms/hub))
			T.links |= relay
			relay.links |= T
```

2022-02-19 21:03 UTC, LudwigVonChesterfield approved these changes

2022-02-19 21:20 UTC, merged