Dreamcheker fixes and bump spacemanDMM version in ci
TauCetiStation/TauCetiClassic pull request #8575
Opened 2022-02-09 15:35 UTC by KIBORG04

## Описание изменений
Чел выпустил ПР, его замержили, и теперь ошибки в консоле ВСКода. Мне не нравится, поэтому ПР.

Бампнул версию в ci до актуального релиза.

## Почему и что этот ПР улучшит
Фикс ошибок. Послание автора

>is not uncommon in SS13 code. Sadly, it is also not uncommon for people to add new cases to a longer switch of this form and forget to change the rand arguments at the top. This PR adds a linter warning for when the rand range is not fully covered by the cases and for when a case lies completely outside of the rand range.
>This currently generates 7 warnings on tgstation master. Sadly, it is (at least to me) not quite clear if the omissions of a part of the rand range are intentional there or not. However, I believe that even if they are intentional it is worth adding the missing part of the range as a case with empty body explicitly to make the intent clear to future developers.
>As a less related (but perhaps more important) addition this PR now also adds a warning for switch branches of the form if(X || Y) which is pretty much always a mistake and should instead be if(X, Y). This lint generates 5 warnings on current tg code, seemingly all being actual mistakes.

## Авторство

## Чеинжлог

2022-02-09 20:27 UTC, LudwigVonChesterfield approved these changes

2022-02-09 20:30 UTC, KIBORG04 commented on code/modules/mob/mob_helpers.dm
> +				continue
а по моему, все же не аппрувед. С этим континью алгоритм будет работать некорректно, будут итерации пропускаться, вместо того, чтобы добавлять букву.

В итоге имеем: брейк ломает, ретурн ломает, континью ломает, если убрать, то варнинг. Это что, делать функцию `do_nothing()` ???

2022-02-09 20:33 UTC, KIBORG04 commented on code/modules/mob/mob_helpers.dm
> +				continue
А похоже это без костылей и не решить..

2022-02-09 20:38 UTC, LudwigVonChesterfield commented on code/modules/mob/mob_helpers.dm
> +				continue
а в бьёнде нету как в питоне `pass` слова, которое что-то типо заполняет блок кода, ничего не делая? в сишке в свитчах вроде можно просто `;` ставить и будет такой эффект

2022-02-09 21:04 UTC, LudwigVonChesterfield requested changes
Не могу поменять ревью на нейтральное, Киборг просить подождать.

2022-02-10 14:35 UTC, LudwigVonChesterfield commented
а почему ты ставишь `;` если в комментарии который ты линканул предлагают вообще ничего в блок не ставить

2022-02-10 14:36 UTC, merged