Перевод всяких интерфейсов
TauCetiStation/TauCetiClassic pull request #8577
Opened 2022-02-10 14:40 UTC by BenDJaminUt

## Описание изменений
Перевел интерфейс факс-машины
## Почему и что этот ПР улучшит
Теперь англо-не-говорящие главы и авдшники смогут понять какие кнопки жать чтобы отправить бумажку на ЦК
Чутка позже перевел (и забыл это упомянуть в описании) интерфейс музыкальных инструментов и клонирующей машины.

Мой скилл работы с гитхабом и переводом получает +1
## Авторство
Беньчик
## Чеинжлог
:cl:
 - ru: Интерфейсы факс-машины, клон-машины и музыкальных инструментов теперь на великом и могучем

2022-02-10 14:40 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2022-02-10 14:47 UTC, KIBORG04 commented on code/game/machinery/fax.dm
> +var/global/list/alldepartments = list("Центральное Командование")
А раз эти буквы вновь станут анти-русскими, то и замени другие места, где было хоть какое-то упоминание этого места

2022-02-10 15:00 UTC, kiVts commented on code/game/machinery/fax.dm
> +				dat += "<b>Произовдится калибровка передатчиков. Ожидайте.</b><br>"
Произовдится :)

2022-02-10 15:02 UTC, kiVts commented on code/game/machinery/fax.dm
> +				dat += "Для отправки сообщения по зашифрованному каналу вставьте лист бумаги.<br><br>"
Please insert paper to send via secure connection= Пожалуйста вставьте документ для отправки через защищённый канал.

2022-02-10 15:06 UTC, BenDJaminUt commented on code/game/machinery/fax.dm
решил сократить ибо не знал, как игра отреагирует на длинное сообщение

2022-02-10 15:08 UTC, BenDJaminUt commented on code/game/machinery/fax.dm
> +				dat += "Для отправки сообщения по зашифрованному каналу вставьте лист бумаги.<br><br>"
буквальный пословный перевод не всегда лучше

2022-02-10 15:08 UTC, BenDJaminUt commented on code/game/machinery/fax.dm
> +				dat += "<b>Произовдится калибровка передатчиков. Ожидайте.</b><br>"
спасибо

2022-02-10 16:56 UTC, BenDJaminUt commented on code/game/machinery/fax.dm
> +				dat += "Для отправки сообщения по зашифрованному каналу вставьте лист бумаги.<br><br>"
> В оригинале внимание на Вставьте бумагу, а в переводе внимание на Для отправки сообщения.

не большая разница имхо, тк это сообщение появляется когда в машине нет бумаги. предложение не такое уж и большое, так что можно и целиком прочитать

2022-02-11 19:06 UTC, BenDJaminUt commented
капец я кажется сломал что-то

2022-02-11 19:12 UTC, KIBORG04 commented
Это конфликты, учись фиксить их

2022-02-11 19:21 UTC, KIBORG04 commented
На зачем ты несколько файлов в одном Пре? ТИпо все, никто не заревувает столько букв. Капец 
![image](https://user-images.githubusercontent.com/26389417/153655986-8a4e5bcb-4ab6-42b1-afba-95b75d4edbd3.png)

2022-02-11 19:58 UTC, BenDJaminUt commented
> На зачем ты несколько файлов в одном Пре? ТИпо все, никто не заревувает столько букв. Капец ![image](https://user-images.githubusercontent.com/26389417/153655986-8a4e5bcb-4ab6-42b1-afba-95b75d4edbd3.png)

я думал что так круто, больше не буду

2022-02-11 20:39 UTC, Haggerd commented
Как мне кажется, описание ПРа и чейнджлог должны отражать все изменения, а не лишь какое-то одно.

Отревуваю позже

2022-02-12 04:49 UTC, BenDJaminUt commented
> Как мне кажется, описание ПРа и чейнджлог должны отражать все изменения, а не лишь какое-то одно.
> 
> Отревуваю позже

не успел ещё да

2022-02-22 09:00 UTC, bowlofsoup4ik requested changes
есть несколько ошибок, но более менее норм.

2022-02-22 09:00 UTC, bowlofsoup4ik commented on code/datums/music_player.dm
> +			html += "Осталось повторовt: [repeat]<br><br>"
повторовt

очепятка

2022-02-22 09:00 UTC, bowlofsoup4ik commented on code/datums/music_player.dm
> +		html += "<a href='?src=\ref[src];import=1'>Импорт песни</a><br><br>"
импортировать песню

2022-02-22 09:00 UTC, bowlofsoup4ik commented on code/datums/music_player.dm
> +			html += "<a href='?src=\ref[src];newsong=1'>Создать новую песню</a><br>"
начать новую песню

2022-02-22 09:00 UTC, bowlofsoup4ik commented on code/datums/music_player.dm
> +			html += "<a href='?src=\ref[src];newline=1'>Добавть строку</a><br><br>"
добавить

очепятка

2022-02-22 09:00 UTC, bowlofsoup4ik commented on code/datums/music_player.dm
> +			html += "<a href='?src=\ref[src];show_help=1'>Показать помощь</a>"
не помощь, а справку

2022-02-22 09:00 UTC, bowlofsoup4ik commented on code/datums/music_player.dm
> +			html += "<a href='?src=\ref[src];show_help=0'>Спрятать помощь</a><br>"
скрыть справку

2022-02-22 09:00 UTC, bowlofsoup4ik commented on code/datums/music_player.dm
> +			var/newline = sanitize(input("Вставить новую строку: ") as text|null, MAX_LINE_SIZE, ascii_only = TRUE)
вставьте новую строку

2022-02-22 09:00 UTC, bowlofsoup4ik commented on code/game/dna/dna_modifier.dm
> +									var/answer = tgui_alert(ghost, "Вы хотите вернуться в тело, чтобы стать клоном?", "Клонирование", list("Да","Нет"))
вернуться в тело для клонирования

2022-02-22 09:00 UTC, bowlofsoup4ik commented on code/game/machinery/computer/cloning.dm
> +	var/scantemp = "Сканер пуст"
сканер свободнен, скорее

2022-02-22 09:00 UTC, bowlofsoup4ik commented on code/game/machinery/computer/cloning.dm
> +				dat += " <span class='red'>Сканнер: ОШИБКА</span><br>"
сканер

2022-02-22 09:00 UTC, bowlofsoup4ik commented on code/game/machinery/computer/cloning.dm
> +					if(scantemp == "Сканер пуст") scantemp = "" // Stupid check to remove the text
свободен

2022-02-22 09:00 UTC, bowlofsoup4ik commented on code/game/machinery/computer/cloning.dm
> +					scantemp = "Сканер пуст"
свободен

2022-02-22 09:00 UTC, bowlofsoup4ik commented on code/game/machinery/computer/cloning.dm
> +				dat += "<a href='byond://?src=\ref[src];disk=eject'>Забрать диск</a>"
Извлечь диск

2022-02-22 09:00 UTC, bowlofsoup4ik commented on code/game/machinery/computer/cloning.dm
> +				temp = "<span class='good'>Клонирование в процессе...</span>"
Цикл клонирования

2022-02-22 09:00 UTC, bowlofsoup4ik commented on code/game/machinery/computer/cloning.dm
> +						temp = "Клонирование в процессе..."
Начало цикла клонирования...

2022-02-22 09:00 UTC, bowlofsoup4ik commented on code/game/machinery/computer/cloning.dm
> +		scantemp = "Ошибка: Тело субъекта не поддерживается сканером."
не просто тело, а его структура.

2022-02-22 09:00 UTC, bowlofsoup4ik commented on code/game/machinery/computer/cloning.dm
> +		scantemp = "<span class='bad'>Субъект более не имеет достаточного геннетического материала для создания клона.</span>"
генетического с одной н

2022-02-22 09:00 UTC, bowlofsoup4ik commented on code/game/machinery/fax.dm
> +			dat += "<a href='byond://?src=\ref[src];remove=1'>Убрать лист</a><br><br>"
извлечь, я думаю

2022-02-22 09:04 UTC, BenDJaminUt commented on code/datums/music_player.dm
> +			html += "<a href='?src=\ref[src];newsong=1'>Создать новую песню</a><br>"
мне кажется "создать" лучше подходит
"начать" можно понять как "начать воспроизведение"

в игре эта кнопка фактически создаёт новый лист для нот

2022-02-22 09:05 UTC, BenDJaminUt commented on code/datums/music_player.dm
> +			var/newline = sanitize(input("Вставить новую строку: ") as text|null, MAX_LINE_SIZE, ascii_only = TRUE)
насколько я помню там действие, а не запрос

2022-02-22 09:06 UTC, BenDJaminUt commented on code/game/machinery/computer/cloning.dm
> +					temp = "Клонирование в процессе...<br>Error: Ошибка инициализации: клонирование отменено."
брух, я хотел error убрать вообще

2022-02-22 09:08 UTC, BenDJaminUt commented on code/game/machinery/computer/cloning.dm
> +			dat += "<a href='byond://?src=\ref[src];task=autoprocess'>Автопроцесс</a>"
исходя из того, что мне подсказали в дискорде, эта кнопка позволяет гостам клонироваться при смерти

возможно "автоклонирование"?

2022-02-22 09:13 UTC, bowlofsoup4ik commented on code/datums/music_player.dm
> +			html += "<a href='?src=\ref[src];newsong=1'>Создать новую песню</a><br>"
думаю можно и так, и так

2022-02-22 09:13 UTC, bowlofsoup4ik commented on code/datums/music_player.dm
> +			var/newline = sanitize(input("Вставить новую строку: ") as text|null, MAX_LINE_SIZE, ascii_only = TRUE)
проверь на локалке

2022-02-22 09:14 UTC, bowlofsoup4ik commented on code/game/machinery/computer/cloning.dm
> +			dat += "<a href='byond://?src=\ref[src];task=autoprocess'>Автопроцесс</a>"
нужно проверить в билде

2022-02-22 09:18 UTC, BenDJaminUt commented on code/datums/music_player.dm
> +			var/newline = sanitize(input("Вставить новую строку: ") as text|null, MAX_LINE_SIZE, ascii_only = TRUE)
действие, запрос ниже по коду идёт

2022-02-22 09:28 UTC, bowlofsoup4ik commented on code/datums/music_player.dm
> +			var/newline = sanitize(input("Вставить новую строку: ") as text|null, MAX_LINE_SIZE, ascii_only = TRUE)
тогда норм, резолви

2022-02-22 09:38 UTC, BenDJaminUt commented on code/game/machinery/computer/cloning.dm
> +				temp = "<span class='good'>Клонирование в процессе...</span>"
есть ли существенная разница между "циклом клонирования" и просто "клонированием" в данном случае?

2022-02-22 09:38 UTC, BenDJaminUt commented on code/game/machinery/computer/cloning.dm
> +				temp = "<span class='good'>Клонирование в процессе...</span>"
если ещё и "цикл клонирования в процессе" то излишне длинно получается

2022-02-22 09:41 UTC, BenDJaminUt commented on code/game/machinery/fax.dm
> +		dat += "Для использования необходима авторизация.<br><br>"
в оригинале условие а не запрос действия. это сообщение выходит в чат когда тыкаешь по факсу без доступа. возможно челик просто решил потыкать а с него уже авторизацию требуют

2022-02-22 09:49 UTC, bowlofsoup4ik commented on code/game/machinery/computer/cloning.dm
> +				temp = "<span class='good'>Клонирование в процессе...</span>"
разницы нет, но выглядит красиво. если где то слишком длинно получается и будет ломать интерфейс - убирай

2022-02-28 19:00 UTC, DarthSidiousPalpatine commented
Без обид, посмотрел первые 20 строчек, это надо закрывать.

ЗАКРЫВАЙТЕ БЫСТРЕЕ

2022-03-09 10:42 UTC, LudwigVonChesterfield commented on code/datums/music_player.dm
> +			html += "<a href='?src=\ref[src];newsong=1'>Создать новую песню</a><br>"
"песня" это вроде если со словами. Может "мелодию"?

2022-03-09 10:45 UTC, LudwigVonChesterfield commented on code/game/machinery/computer/cloning.dm
> +				dat += "Замок: <a href='byond://?src=\ref[src];lock=1'>[src.scanner.locked ? "Закрыто" : "Открыто"]</a><br>"
может Блокировка?

2022-03-09 10:49 UTC, LudwigVonChesterfield commented on code/game/machinery/computer/cloning.dm
> +				temp = "Ошибка: Капсула клонирования неисправна."
где-то ОШИБКА а где-то Ошибка. может лучше везде Ошибка?

2022-03-09 10:51 UTC, LudwigVonChesterfield commented on code/game/machinery/computer/cloning.dm
> +		scantemp = "<span class='bad'>Субъект более не имеет достаточного генетического материала для создания клона.</span>"
```suggestion
		scantemp = "<span class='bad'>Субъект не имеет достаточного генетического материала для создания клона.</span>"
```

2022-03-09 10:53 UTC, LudwigVonChesterfield commented on code/game/machinery/fax.dm
> +				dat += "<b>Документ внутри:</b> [tofax.name]<br>"
```suggestion
				dat += "<b>Документ:</b> [tofax.name]<br>"
```

2022-03-09 10:54 UTC, LudwigVonChesterfield commented on code/game/machinery/fax.dm
> +				dat += "<b>Документ внутри:</b> [tofax.name]<br>"
Кстати, если "вставьте лист", то почему здесь документ, а не лист? Или там не документ...

2022-03-09 11:00 UTC, LudwigVonChesterfield commented on code/game/machinery/fax.dm
> +	audible_message("Получено сообщение.")
1. это не интерфейс сообщение, оно видно всем
2. тут должно быть сообщение вида [bicon(src)] [src] гудит, "Сообщение получено", как у вендоматов всяких к примеру.
3. выполнить пункт два невозможно потому-что пока-что не смешиваем английский с русским, я бы вернул как было.
```suggestion
	audible_message("Received message.")
```

2022-03-09 11:06 UTC, LudwigVonChesterfield commented on code/game/machinery/fax.dm
> +	audible_message("Получено сообщение.")
хотяяя может и можно сделать как предложил в пункте два, надо у вендоматов подсмотреть.

2022-03-30 14:28 UTC, closed without merging