Перевод Аплинка
TauCetiStation/TauCetiClassic pull request #8588
Opened 2022-02-11 19:20 UTC by StarcBlue

## Описание изменений
Перевод вещей аплинка

## Почему и что этот ПР улучшит
Сделает предметы аплинка понятней для новичков-триторов. 

## Авторство
Sheoleo

## Чеинжлог
Аплинке тритора, радио нюкера и аплинк дилера теперь с RU пояснениями предметов. Описания дополнены.

2022-02-11 19:20 UTC, TauKitty commented
###### Changelog status: :radio_button: No changelog

2022-02-11 21:13 UTC, KIBORG04 commented on code/datums/uplinks_items.dm
> +	desc = "Традиционный пистолет Cиндиката. Ревеольвер заряжен 7-ью патронами калибра .357 Magnum. Выглядит как игрушка."
Он не выглядит как игрушка.

2022-02-11 21:13 UTC, KIBORG04 commented on code/datums/uplinks_items.dm
> +			Можно присоединить глушителем."
```suggestion
			Можно присоединить глушитель."
```

2022-02-11 21:14 UTC, KIBORG04 commented on code/datums/uplinks_items.dm
> +	desc = "Пистолет-пулемет, разработанный компанией "Скарборо Армс". Использует магазины на 20 патронов калибра .45  ACP. Обладает большим разнообразием боеприпасов."
```suggestion
	desc = "Пистолет-пулемет, разработанный компанией \"Скарборо Армс\". Использует магазины на 20 патронов калибра .45  ACP. Обладает большим разнообразием боеприпасов."
```
Компилил бы перед ПРом

2022-02-11 21:15 UTC, KIBORG04 commented on code/datums/uplinks_items.dm
> +	desc = "Создан на основе известной "Чикагской пишущей машинки". Использует патроны калибра .45 ACP."
```suggestion
	desc = "Создан на основе известной \"Чикагской пишущей машинки\". Использует патроны калибра .45 ACP."
```
Я думаю ты понял. Нужно экранировать двойные кавычки внутри двойных кавычек

2022-02-11 21:20 UTC, KIBORG04 commented on code/datums/uplinks_items.dm
> +	desc = "Мина нажимного действия. Используйте мультитул, чтобы обезвредить её."
Если честно я хз, мультитул у нас на станции или мульти инструмент?

2022-02-11 21:20 UTC, KIBORG04 commented on code/datums/uplinks_items.dm
> +	desc = "15-ти зарядный магазин с высокоскоростныеми патронами калибра .45 ACP для пистолета-пулемета C-20r. Эти патроны испольхуются для быстрого поражения цели."
```suggestion
	desc = "15-ти зарядный магазин с высокоскоростными патронами калибра .45 ACP для пистолета-пулемета C-20r. Эти патроны используются для быстрого поражения цели."
```

2022-02-11 21:21 UTC, KIBORG04 commented on code/datums/uplinks_items.dm
> +	desc = "Комплект одежды, используемый для имитации униформы членов экипажа станции Nanotrasen."
НаноТрейзен тоже переводим

2022-02-11 21:22 UTC, KIBORG04 commented on code/datums/uplinks_items.dm
> +	desc = "Уменьшенная версия энергитического меча, но в выключенном состоянии работает и выглядит как обычная ручка"
```suggestion
	desc = "Уменьшенная версия энергетического меча, но в выключенном состоянии работает и выглядит как обычная ручка"
```

2022-02-11 21:22 UTC, KIBORG04 commented on code/datums/uplinks_items.dm
> +			мощный всплеск ионизирующего излучения, который, после небольшой зедержки, может облучить и вывести из строя всех, кроме \
```suggestion
			мощный всплеск ионизирующего излучения, который, после небольшой задержки, может облучить и вывести из строя всех, кроме \
```

2022-02-11 21:23 UTC, KIBORG04 commented on code/datums/uplinks_items.dm
> +	desc = "Аптечка синдиката подозрительного цвета хаки. Cодержит инъектор боевого стимулятора для ускоренного восстановления, медицинский анализатор для быстрого анализа ранения товарищей, \
```suggestion
	desc = "Аптечка синдиката подозрительного цвета хаки. Содержит инъектор боевого стимулятора для ускоренного восстановления, медицинский анализатор для быстрого анализа ранения товарищей, \
```
Ты сука хотел пропихнуть в билд пендосские буквы под видом русских

2022-02-11 21:24 UTC, KIBORG04 commented on code/datums/uplinks_items.dm
> +	desc = "Боевая аптчека синдиката. Cодержит инъектор боевого стимулятора для ускоренного восстановления.
```suggestion
	desc = "Боевая аптечка синдиката. Содержит инъектор боевого стимулятора для ускоренного восстановления.
```

2022-02-11 21:24 UTC, KIBORG04 commented on code/datums/uplinks_items.dm
> +	desc = "Украденый прототип нанитов, сращивающих кости. Содержит четыре инжектора.
```suggestion
	desc = "Украденный прототип нанитов, сращивающих кости. Содержит четыре инжектора.
```

2022-02-11 21:25 UTC, KIBORG04 commented on code/datums/uplinks_items.dm
> +	desc = "Украденый прототип нанитов, сращивающих кости. Содержит четыре инжектора.
А еще какой-то кринж, что где-то у тебя инъекторы, а где-то инжекторы

2022-02-11 21:25 UTC, KIBORG04 commented on code/datums/uplinks_items.dm
> +	desc = "Красный скафандр Синдиката не такой неудобный, чем обычные ERVOS, помещается в сумки и имеет слот для оружия. Члены экипажа станции непременно сообщат если увидят этот крансый костюм."
```suggestion
	desc = "Красный скафандр Синдиката не такой неудобный, чем обычные ERVOS, помещается в сумки и имеет слот для оружия. Члены экипажа станции непременно сообщат если увидят этот красный костюм."
```

2022-02-11 21:25 UTC, KIBORG04 commented on code/datums/uplinks_items.dm
> +	desc = "Термальные очки, удобно замаскированные под мезонный сканнер. \
```suggestion
	desc = "Термальные очки, удобно замаскированные под мезонный сканер. \
```

2022-02-11 21:26 UTC, KIBORG04 commented on code/datums/uplinks_items.dm
> +	desc = "Набор запрёщенных постеров"
```suggestion
	desc = "Набор запрещённых постеров"
```

2022-02-11 21:26 UTC, KIBORG04 commented on code/datums/uplinks_items.dm
> +	desc = "Детонатор Синдиката - это дополнительное устройство к бомбе Синдиката. Просто нажмите на кноаку, и сигнал даст команду всем бомбам Синдиката взорваться. \
```suggestion
	desc = "Детонатор Синдиката - это дополнительное устройство к бомбе Синдиката. Просто нажмите на кнопку, и сигнал даст команду всем бомбам Синдиката взорваться. \
```

2022-02-11 21:27 UTC, KIBORG04 commented on code/datums/uplinks_items.dm
> +	desc = "Устройство для дистанционного управления дроном, замаскированного под технического дрона НТ. Поставлется с очками дистанционного управления. "
```suggestion
	desc = "Устройство для дистанционного управления дроном, замаскированного под технического дрона НТ. Поставляется с очками дистанционного управления. "
```

2022-02-11 21:27 UTC, KIBORG04 commented on code/datums/uplinks_items.dm
> +	desc = "Имлпант с блюспейс карманом. Может хранить в себе два средних предмета."
```suggestion
	desc = "Имплант с блюспейс карманом. Может хранить в себе два средних предмета."
```

2022-02-11 21:28 UTC, KIBORG04 commented on code/datums/uplinks_items.dm
> +	desc = "Имплант содержащий три ЭМИ заряда. Активируется по желанию носителя"
Так у тебя импланты или имплантанты? Еще одна неконсистентность перевода

2022-02-11 21:28 UTC, KIBORG04 commented on code/datums/uplinks_items.dm
> +	desc = "Покажите вашу лояльность Синдикату! Вы получите футболку с логотипом Синдиката, красную кепку и чуденсый надувной шарик!"
```suggestion
	desc = "Покажите вашу лояльность Синдикату! Вы получите футболку с логотипом Синдиката, красную кепку и чудесный надувной шарик!"
```

2022-02-11 21:29 UTC, KIBORG04 commented on code/datums/uplinks_items.dm
> +	desc = "Насыщенный аромат, густой дым, cодержит трик."
```suggestion
	desc = "Насыщенный аромат, густой дым, содержит трик."
```
чтоб ты

2022-02-11 21:29 UTC, KIBORG04 commented on code/datums/uplinks_items.dm
> +	desc = "Насыщенный аромат, густой дым, cодержит трик."
А еще какой нах трик, если даже в английском варианте трокодразин.

2022-02-11 21:30 UTC, KIBORG04 commented on code/datums/uplinks_items.dm
> +	     При попадании по цели поршень выдвинется вперёд и нанесёт серьёзный урон.\
```suggestion
		При попадании по цели поршень выдвинется вперёд и нанесёт серьёзный урон.\
```

2022-02-11 21:30 UTC, KIBORG04 commented on code/datums/uplinks_items.dm
> +    name = "Energy Sword"
```suggestion
	name = "Energy Sword"
```

2022-02-11 21:30 UTC, KIBORG04 commented on code/datums/uplinks_items.dm
> +    item = /obj/item/weapon/storage/fancy/donut_box/traitor
```suggestion
	item = /obj/item/weapon/storage/fancy/donut_box/traitor
```

2022-02-11 21:32 UTC, KIBORG04 commented on code/datums/uplinks_items.dm
> +	desc = "Выбрав этот вариант, вы получите случайный предмет из списка. Полезно, когда вы не можете придумать стратегию для достижения своих целей."
Давай без этих деепричастных оборотов в начале предложения. Лучше без него придумать и написать, иначе неприятно читать и понимать смысл слов. Типо, проблема скорее не в обороте, а в том, что он стоит перед зависимым словом, из-за чего сложнее воспринимать информацию

2022-02-11 21:33 UTC, KIBORG04 commented on code/datums/uplinks_items.dm
> +	desc = "Набор Синдиката - это специализированные комплекты вещей, которые поступают в обычной коробке. Эти предметы в совокупности стоят более 10 телекристаллов, но вы не знаете, какую специализацию
стоят более 10 тк, но цена на бандл 20. Круто.

2022-02-11 21:34 UTC, KIBORG04 commented on code/datums/uplinks_items.dm
> +	desc = "Набор Синдиката - это специализированные комплекты вещей, которые поступают в обычной коробке. Эти предметы в совокупности стоят более 10 телекристаллов, но вы не знаете, какую специализацию
```suggestion
	desc = "Наборы Синдиката - это специализированные комплекты вещей, которые поступают в обычной коробке. Эти предметы в совокупности стоят более 10 телекристаллов, но вы не знаете, какую специализацию вы получите."
```
Уж лучше иметь "наборЫ" сразу в мн. ч., так как потом идут "комплектЫ"

2022-02-11 21:35 UTC, KIBORG04 commented on code/datums/uplinks_items.dm
> +	desc = "Набор Синдиката - это специализированные комплекты вещей, которые поступают в обычной коробке. Эти предметы в совокупности стоят более 10 телекристаллов, но вы не знаете, какую специализацию
```suggestion
	desc = "Набор Синдиката - это специализированные комплекты вещей, которые поступают в обычной коробке. Эти предметы в совокупности стоят более 10 телекристаллов, но вы не знаете какой именно набор получите."
```
Вы не знаете, вы получите, короче повторение ужс 10 балов за егэ

2022-02-11 21:37 UTC, KIBORG04 requested changes
Короче прошелся по опечаткам и `c` вместо `с`. Затронул первые попавшиеся в глаза типовые ошибки и забил. Смысл подбирайте дальше сами.

2022-02-11 23:40 UTC, LudwigVonChesterfield commented on code/datums/uplinks_items.dm
> +	desc = "Традиционный пистолет Cиндиката. Ревеольвер заряжен 7-ью патронами калибра .357 Magnum. Выглядит как игрушка."
вероятно произошла путаница, трейторский револьвер - выглядит, нюкерский - нет (как Киборг и сказал)

2022-02-11 23:41 UTC, LudwigVonChesterfield commented on code/datums/uplinks_items.dm
> +	desc = "Убойная пушка, заряжаемая патронами калибра .50 AE."
такому легендарному слову как robust не выделили какой-нибудь достойный универсальный перевод в словарь?

2022-02-22 07:32 UTC, bowlofsoup4ik requested changes
вроде на ошибки указал, коих тут куча. кавычки тут вообще страшная штука. кавычки в кавычках не экранированы, один деск не закрыт и ломает весь последующий код.

2022-02-22 07:32 UTC, bowlofsoup4ik commented on code/datums/uplinks_items.dm
> +	desc = "На первый взгляд, обычный мультитул, но благодаря его красному индикатору можно узнать, когда искусственный интеллект, наблюдает за вами. Знание того, когда искусственный интеллект наблюдает
масло масленное

"знание того, шо ии наблюдает за вами" > на простое "это поможет вам..."

и зачем запятая после первого "интеллект"?

2022-02-22 07:32 UTC, bowlofsoup4ik commented on code/datums/uplinks_items.dm
> +	desc = "Невероятно полезный проектор щита. Имеет возможность отражать энергоснаряды и даёт защиту от других атак.
отсутствие кавычек в конце все ломает

2022-02-22 10:07 UTC, SheoLeo commented on code/datums/uplinks_items.dm
> +	desc = "Используется для колки льда. Прекрасное оружие для убийства в стиле мафии"
Это нож для колки льда, а не ледоруб альпинистов.

2022-02-22 10:10 UTC, LudwigVonChesterfield commented on code/datums/uplinks_items.dm
> +	desc = "Мина нажимного действия. Используйте мультитул, чтобы обезвредить её."
мультиметр не позволяет соединять машинки и загружать данные в консоли, думаю мультитул таки не мультиметр

2022-02-22 19:28 UTC, Akellazp commented on code/datums/uplinks_items.dm
> +	desc = "Автоматическая штурмовая винтовка. Идеально справляется с подавлением целей на большой дистанции. Магазин содержит 30 /
```suggestion
	desc = "Автоматическая штурмовая винтовка. Отлично подходит для дальних дистанций и подавления огнем. Магазин содержит 30 /
```

2022-02-22 19:35 UTC, Akellazp commented on code/datums/uplinks_items.dm
> +	desc = "Энергетический меч не нуждается в представлении. В деактивированном состоянии помещается в карман. При активации издаёт характерный звук. Выглядит как игрушка."
```suggestion
	desc = "Энергетический меч это холодное оружие с клинком из чистой энергией. В деактивированном состоянии помещается в карман. При активации издаёт громкий звук. Выглядит как игрушка."
```

2022-02-22 19:36 UTC, Akellazp commented on code/datums/uplinks_items.dm
> +	desc = "Энергетический меч не нуждается в представлении. В деактивированном состоянии помещается в карман. При активации издаёт характерный звук. Выглядит как игрушка."
```suggestion
	desc = "Энергетический меч это холодное оружие с клинком из чистой энергией. В деактивированном состоянии помещается в карман. При активации издаёт громкий звук. Выглядит как игрушка."
```

2022-02-22 19:37 UTC, Akellazp commented on code/datums/uplinks_items.dm
> +	desc = "Уникальная граната, выпускающая рой роботов-висцераторов. Висцераторы будут преследовать и крошить всех, кроме агентов"
не висцераторы а потрошители

2022-02-22 19:40 UTC, Akellazp commented on code/datums/uplinks_items.dm
> +В этой модели отсутствует возможность для перемещения по космосу, и поэтому рекомендуется отремонтировать телепортер главного корабля, если вы хотите им воспользоваться."
сомневаюсь в надобности вообще сохранять эту строчку

2022-02-22 19:43 UTC, Akellazp commented on code/datums/uplinks_items.dm
> +	desc = "Массивный и невероятно смертоносный экзоскелет Синдиката. Обладает функциями дальнобойного наведения, управления вектора тяги и дымовой завесы."
```suggestion
	desc = "Массивный и невероятно смертоносный экзоскелет Синдиката. Обладает функциями наведения на большие расстояния, управлением вектора тяги и дымовой завесы."
```

2022-02-22 19:49 UTC, Akellazp commented on code/datums/uplinks_items.dm
> +			стоят дешево, но вдвое эффективнее патронов калибра .357."
"в два раза менее эффективны"/"имеют половину эффективности", но никак не "вдвойне эффективнее"

2022-02-22 19:50 UTC, Akellazp commented on code/datums/uplinks_items.dm
> +	desc = "20-ти зарядный магазин с патронами калибра .45 ACP для пистолете-пулемете C-20r."
писто
```suggestion
	desc = "20-ти зарядный магазин с патронами калибра .45 ACP для пистолета-пулемета C-20r."
```

2022-02-22 19:52 UTC, Akellazp commented on code/datums/uplinks_items.dm
> +	desc = "50-ти зарядный магазин с патронами калибра .45 ACP для tommygun."
```suggestion
	desc = "50-ти зарядный магазин с патронами калибра .45 ACP для пистолета-пулемета Томпсона."
```

2022-02-22 19:53 UTC, Akellazp commented on code/datums/uplinks_items.dm
> +	desc = "7-ми зарядный магазин с патронами калибра .50 AE для desert eagle."
```suggestion
	desc = "7-ми зарядный магазин с патронами калибра .50 AE для Desert Eagle."
```

2022-02-22 19:54 UTC, Akellazp commented on code/datums/uplinks_items.dm
> +	desc = "15-ти зарядный магазин с экспансивными патронами калибра .45 ACP для пистолета-пулемета C-20r. Эти патроны обладают повышенной мощностью пробития."
```suggestion
	desc = "15-ти зарядный магазин с экспансивными патронами калибра .45 ACP для пистолета-пулемета C-20r. Эти патроны обладают повышенным уроном."
```

2022-02-22 19:56 UTC, Akellazp commented on code/datums/uplinks_items.dm
> +	desc = "15-ти зарядный магазин с патронами калибра .45 ACP высокого останавливающего действия для пистолета-пулемета C-20r. Эти патроны отбросят и оглушат небронированные цели."
```suggestion
	desc = "15-ти зарядный магазин с патронами калибра .45 ACP высокого останавливающего действия для пистолета-пулемета C-20r. Эти патроны отбрасывают и оглушают небронированные цели."
```

2022-02-22 19:57 UTC, Akellazp commented on code/datums/uplinks_items.dm
> +	desc = "Запасной 8-ми зарядный магазин с картечью для дробовика Bulldog."
скорее всё же дробь чем картечь

2022-02-22 19:58 UTC, Akellazp commented on code/datums/uplinks_items.dm
> +	desc = "Альтернативный 8-ми зарядный магазин с зажигательными патронами для дробовика Bulldog."
```suggestion
	desc = "Альтернативный 8-ми зарядный магазин с зажигательными боеприпасами для дробовика Bulldog."
```

2022-02-22 20:02 UTC, Akellazp commented on code/datums/uplinks_items.dm
> +	desc = "Снаряд калибра 14.5mm для тяжёлой винтовки PTR-7. Один выстрел, один труп, не удача, а просто навык"
не снаряд а патрон

2022-02-22 20:03 UTC, Akellazp commented on code/datums/uplinks_items.dm
> +	desc = "Снаряд калибра 14.5mm для тяжёлой винтовки PTR-7. Один выстрел, один труп, не удача, а просто навык"
плюс ты англ описание не убрал

2022-02-22 20:04 UTC, Akellazp commented on code/datums/uplinks_items.dm
> +	desc = "Фугасная ракета для пусковой ручной установки Goliath."
```suggestion
	desc = "Фугасная ракета для гранатомета Goliath."
```

2022-02-22 20:04 UTC, Akellazp commented on code/datums/uplinks_items.dm
> +	desc = "ЭМИ ракета для пусковой ручной установки Goliath."
```suggestion
	desc = "Фугасная ракета для гранатомета Goliath."
```

2022-02-22 20:08 UTC, Akellazp commented on code/datums/uplinks_items.dm
> +	Эффект оглушения от взрыва вырубит адресата на короткое время и оглушит его на определенный срок. Осторожно, есть шанс, что взорвется ваш ПДА."
```suggestion
	Эффект оглушения от взрыва собьет адресата с ног на короткое время и оглушит его на более продолжительный срок. Осторожно, есть шанс, что взорвется ваш собственный ПДА."
```

2022-02-22 20:09 UTC, Akellazp commented on code/datums/uplinks_items.dm
>  	uplink_types = list("nuclear") */
закоменти обратно

2022-02-22 20:10 UTC, Akellazp commented on code/datums/uplinks_items.dm
>  	uplink_types = list("nuclear") */
закоменти обратно

2022-02-22 20:10 UTC, Akellazp commented on code/datums/uplinks_items.dm
>  	uplink_types = list("nuclear") */
закоменти обратно

2022-02-22 20:14 UTC, Akellazp commented on code/datums/uplinks_items.dm
> +	desc = "Эта сумка достаточно тонкая, чтобы ее можно было спрятать в щели между обшивкой и плиткой; отлично подходит для хранения украденных вещей. Вместе с рюкзаком так же предоставляются лом и напо
```suggestion
	desc = "Эта сумка достаточно тонкая, чтобы ее можно было спрятать в щели между обшивкой и плиткой; отлично подходит для \
			хранения украденных  вами вещей. Вместе с рюкзаком так же предоставляются лом и напольная плитка."
```

2022-02-22 20:15 UTC, Akellazp commented on code/datums/uplinks_items.dm
> +	desc = "Эта сумка достаточно тонкая, чтобы ее можно было спрятать в щели между обшивкой и плиткой; отлично подходит для хранения украденных вещей. Вместе с рюкзаком так же предоставляются лом и напо
я вроде неправильно сделал, но суть с переносом строки ты должен понять
и у нас нельзя найти сумки, это только на тг

2022-02-22 20:16 UTC, Akellazp commented on code/datums/uplinks_items.dm
> +	desc = "Бросающийся в глаза противогаз, имитирующий голос, указанный в вашей ID-карте. Если вы не носите карту, то маска сделает ваш голос неузнаваемым."
указанный на

2022-02-22 20:18 UTC, Akellazp commented on code/datums/uplinks_items.dm
> +	desc = "Позволяет вам узнать, кто сейчас находится в интересующем вас отсеке. Также, после взлома камеры этим устройством, вы сможете отключить её дистанционно."
```suggestion
	desc = "Позволяет вам использовать все камеры в сети и следить за целью. Также, после взлома камеры этим устройством, вы сможете отключить её дистанционно."
```

2022-02-22 20:21 UTC, Akellazp commented on code/datums/uplinks_items.dm
> +	desc = "Коробка сюрикенов и усиленных бол, созданных ещё в древние времена. Но как метательное оружие идеально выполняет свои функции. \
```suggestion
	desc = "Коробка сюрикенов и усиленных бол, изобретенных ещё в древние времена на Земле. Высокоэффективное метательное оружие. \
```

2022-02-22 20:22 UTC, Akellazp commented on code/datums/uplinks_items.dm
> +	desc = "Традиционная кассетная граната полностью снаряженная мылом Синдиката. Полезна при любом раскладе!"
```suggestion
	desc = "Традиционная кассетная граната с зарядом из мыла Синдиката. Полезна при любом раскладе!"
```

2022-02-22 20:23 UTC, Akellazp commented on code/datums/uplinks_items.dm
> +			и длина, которая определяет длительность задержки излучения."
длина волны

2022-02-22 20:24 UTC, Akellazp commented on code/datums/uplinks_items.dm
> +	desc = "Набор инструментов синдиката подозрительно черно-красного цвета. Помимо обычных инструментов в нем так же есть мультитул. Изоляционные перчатки в комплект не входят."
Подозрительный ящик чёрно-красного цвета с инструментами

2022-02-22 20:26 UTC, Akellazp commented on code/datums/uplinks_items.dm
> +	desc = "Набор инструментов синдиката подозрительно черно-красного цвета. Помимо обычных инструментов в нем так же есть мультитул. Изоляционные перчатки в комплект не входят."
Подозрительный чёрно-красный ящик для инструментов.

2022-02-22 20:27 UTC, Akellazp commented on code/datums/uplinks_items.dm
> +			смирительная рубашка и кляп."
ЧМИ/MMI, смирительную рубашку и кляп

2022-02-22 20:28 UTC, Akellazp commented on code/datums/uplinks_items.dm
> +	desc = "Аптечка синдиката подозрительного цвета хаки. Cодержит инъектор боевого стимулятора для ускоренного восстановления, медицинский анализатор для быстрого анализа ранения товарищей, \
цвет точно хаки?

2022-02-22 20:29 UTC, Akellazp commented on code/datums/uplinks_items.dm
> +	и другие медицинские принадлежности, полезные для оперативника-медика."
не принадлежности а препараты

2022-02-22 20:31 UTC, Akellazp commented on code/datums/uplinks_items.dm
> +	desc = "Красный скафандр Синдиката не такой неудобный, чем обычные ERVOS, помещается в сумки и имеет слот для оружия. Члены экипажа станции непременно сообщат если увидят этот крансый костюм."
помещается в сумку

2022-02-22 20:32 UTC, Akellazp commented on code/datums/uplinks_items.dm
> +	Более горячие объекты, такие кибернетические организмы и ядро искусственного интеллекта, излучают больше этого света, чем более холодные объекты, такие как стены и воздушные шлюзы."
не света а излучения

2022-02-22 20:33 UTC, Akellazp commented on code/datums/uplinks_items.dm
> +	desc = "Ключ шифрования, который при вставке в радиогарнитуру позволяет слушать и разговаривать с искусственными интеллектами и кибернетическими организмами на бинарном языке."
при установке

2022-02-22 20:35 UTC, Akellazp commented on code/datums/uplinks_items.dm
> +			а также разговаривать по зашифрованному каналу Синдиката с другими агентами, имеющими тот же ключ."
```suggestion
	desc = "Ключ шифрования, который при установке в радиогарнитуру позволяет прослушивать каналы связи всех отделов станции, \
			а также разговаривать по зашифрованному каналу Синдиката с другими агентами, имеющими такие же ключи."
```

2022-02-22 20:37 UTC, Akellazp commented on code/datums/uplinks_items.dm
> +	desc = "При использовании с консолью загрузки этот модуль позволяет загрузить в ИИ законы с приоритетом. Будьте осторожны с их формулировками, так как искусственный интеллект может искать лазейки дл
```suggestion
	desc = "При взаимодействии с консолью загрузки этот модуль позволяет загрузить в ИИ законы с приоритетом. Будьте осторожны с их формулировками, так как искусственный интеллект может искать лазейки."
```

2022-02-22 20:38 UTC, Akellazp commented on code/datums/uplinks_items.dm
> +	desc = "C-4 представляет собой разновидность пластичных взрывчатых веществ. Вы можете использовать его для разрушения стен, прикреплять к людям, чтобы уничтожить их, или подключать сигнализатор к ег
```suggestion
	desc = "C-4 представляет собой разновидность пластичных взрывчатых веществ. Вы можете использовать его для разрушения стен или прикреплять к людям, чтобы уничтожить их. \
```
такой фичи нет

2022-02-22 20:40 UTC, Akellazp commented on code/datums/uplinks_items.dm
> +	desc = "Привинченное к проводке и подключенное к электрической сети, а затем активированное, это большое устройство создает чрезмерную нагрузку на сеть, вызывая отключение электроэнергии по всей ста
```suggestion
	desc = "Привинченное к проводке и подключенное к электрической сети, а затем активированное, это большое устройство создает чрезмерную нагрузку на сеть, высасывая электроэнергию со всей станции. Это устройство нельзя переносить из-за его чрезмерных размеров. \
```
более точная формулировка того что оно делает

2022-02-22 20:43 UTC, Akellazp commented on code/datums/uplinks_items.dm
> +	Вы можете прикрутить бомбу к полу, чтобы предотвратить ее перемещение. Но не забывайте, экипаж может попытаться обезвредить бомбу."
```suggestion
	Вы можете прикрутить бомбу к полу, чтобы предотвратить ее перемещение. Но не забывайте: экипаж может попытаться обезвредить бомбу."
```

2022-02-22 20:45 UTC, Akellazp commented on code/datums/uplinks_items.dm
> +	desc = "Имплантат, введенный в тело, а затем активированный с помощью разных эмоций,позволит открыть ваш аплинк с 10 телекристаллами. \
```suggestion
	desc = "Имплантат, введенный в тело, а затем активированный с помощью разных эмоций, позволит открыть ваш аплинк с 10 телекристаллами. \
```

2022-02-22 20:46 UTC, Akellazp commented on code/datums/uplinks_items.dm
>  	desc = "An implant, that can compress items and later activated at the user's will."
не удалил англ описание

2022-02-22 20:47 UTC, Akellazp commented on code/datums/uplinks_items.dm
> +	desc = "Имплантат, который будет вводить химический коктейль с мягким лечебным эффектом, а также устраняющий все оглушения и увеличивающий скорость. Может быть активирован по желанию пользователя."
```suggestion
	desc = "Имплантат, который будет вводить химический коктейль с легким лечебным эффектом, а также устраняющий все оглушения и увеличивающий скорость. Может быть активирован по желанию пользователя."
```

2022-02-22 20:48 UTC, Akellazp commented on code/datums/uplinks_items.dm
> +	desc = "Имплант содержащий три ЭМИ заряда. Активируется по желанию носителя"
запятую после импланта пропустил

2022-02-22 20:48 UTC, Akellazp commented on code/datums/uplinks_items.dm
> +	desc = "Имплантат, введенный в тело и затем активированный с помощью разных эмоций, даст возможность снять наручники."
```suggestion
	desc = "Имплант, введенный в тело и затем активированный с помощью разных эмоций, даст возможность снять наручники."
```

2022-02-22 20:51 UTC, Akellazp commented on code/datums/uplinks_items.dm
> +	desc = "Специальное предложение от Waffle Co., коробка, содержащая 6 вкуснейших пончиков! Но будьте осторожны, некоторые из них отравлены!"
```suggestion
	desc = "Специальное предложение от Waffle Co.: коробка, содержащая 6 вкуснейших пончиков! Но будьте осторожны, некоторые из них отравлены!"
```

2022-02-23 04:24 UTC, SheoLeo commented on code/datums/uplinks_items.dm
> +			смирительная рубашка и кляп."
В этой сумке нет ММИ. Я проверял

2022-02-28 18:43 UTC, LudwigVonChesterfield commented
![image](https://user-images.githubusercontent.com/17705613/156039880-bf1ac4c7-e4ff-4c4e-a9bb-3326bad94025.png)

если вдруг будет время и желание - скажи, откроем ПР

2022-02-28 18:43 UTC, closed without merging