Бафф брони культа,магов и не только
TauCetiStation/TauCetiClassic pull request #8591
Opened 2022-02-12 07:17 UTC by simb11

## Описание изменений
Меняет статы у брони культа,магов,ригов СБ,нюки и капитана
Убирает замедление у риот брони и хитина генокрада

| Броня       | Old stats(melee/bullet/las)                | New stats |
| ------------- |:------------------:| -----:|
| Тяж.риг Синдиката    | 50/40/40    | 60/55/55 |
| Риг Синдиката    | 40/30/30 |  45/40/40 |
| Риг СБ | 45/30/30        |   50/45/45 |
| Броня капитана | 65/45/45        |   65/55/50 |
| Риг мага | 40/33/33        |  50/50/30 |
| Броня культа | 50/25/25        |    45/35/55 |
| Роба культа | 40/15/15         |   40/25/35 |

## Почему и что этот ПР улучшит
В первую очередь:Сделать так,чтобы броня культистов нормально защищала,сейчас же она хуже обычного бронежилета.Сделать так,чтобы маг не умирал от одной пульки глока.
О ригах СБ и синдиката:Я так понимаю,что Вестноу смотрел в сторону ТГ или ещё каких казуальных билдов,где можно вылечить себя после 5 попаданий из стечкина за менее чем пол минуты.Но в реалиях нашего билда,даже две пули из кольта делают человека небоеспособным и заставляют его лечиться около 5 минут и поэтому я решил добавить сбшному и нюковскому ригу защиту на уровне обычного бронежилета.

## Авторство
я
## Чеинжлог
:cl: Simbaka
- balance:Изменены защитные характеристики у брони мага,культа,ИКСов СБ и нюки.

2022-02-12 07:17 UTC, TauKitty commented
###### Changelog status: :x: Empty changelog (check markdown correctness)

2022-02-12 10:41 UTC, Kurshan commented on code/modules/clothing/suits/armor.dm
> -	slowdown = 1
Соглашусь

2022-02-12 10:41 UTC, Kurshan commented on code/game/gamemodes/modes_gameplays/cult/cult_items.dm
> +	armor = list(melee = 45, bullet = 35, laser = 55,energy = 45, bomb = 30, bio = 30, rad = 30)
Не многовато ли на лазер, учитывая, что он основное оружие на станции?

2022-02-12 10:41 UTC, Kurshan commented on code/modules/clothing/spacesuits/rig/rig.dm
> +	var/space_armor = list(melee = 45, bullet = 40, laser = 40, energy = 30, bomb = 50, bio = 100, rad = 60)
nyet nyet nyet nyet. Этот армор и так имбовый из-за своих статов в комбат режиме, в космосе по задумке и длжны быть относительно низкими.

2022-02-12 10:41 UTC, Kurshan commented on code/modules/clothing/spacesuits/rig/rig.dm
> +	space_armor = list(melee = 60, bullet = 55, laser = 55, energy = 45, bomb = 50, bio = 100, rad = 60)
Same. Только тут ещё более у тебя запущенный случай. Это ТОПОВЫЙ армор в игре, а ты его бафаешь, его наоборот нерфить надо, по-хорошему.

2022-02-12 10:41 UTC, Kurshan commented on code/modules/clothing/spacesuits/rig/rig.dm
> +	armor = list(melee = 50, bullet = 55, laser = 30,energy = 33, bomb = 33, bio = 100, rad = 66)
Я бы и лазер ему повысил, В своё время я сильно занерфил визардовский армор, да так, что его никто не берёт от слова совсем. Но буллет броню чутка поменьше сделать требуется.

2022-02-12 11:06 UTC, simb11 commented on code/modules/clothing/spacesuits/rig/rig.dm
> +	armor = list(melee = 50, bullet = 55, laser = 30,energy = 33, bomb = 33, bio = 100, rad = 66)
Дал я магу защиту от пулек потому что тот не может самостоятельно чинить кости,в отличии от органов.

2022-02-12 11:13 UTC, simb11 commented
Ой не ту кнопку нажал...сейчас поправлю статы у ригов Синдиката.Менять защиту у брони культа я не планирую,пусть в обмен на низкую скорость имеют достаточно хорошую защиту от лазеров.

2022-02-12 11:14 UTC, KIBORG04 commented on code/game/gamemodes/modes_gameplays/cult/cult_items.dm
> +	armor = list(melee = 45, bullet = 35, laser = 55,energy = 45, bomb = 30, bio = 30, rad = 30)
Надеюсь, ты помнишь про скелетов и их бессмертие через булетпруф?

2022-02-12 13:03 UTC, muWander commented on code/game/gamemodes/modes_gameplays/cult/cult_items.dm
>  	body_parts_covered = UPPER_TORSO|LOWER_TORSO|ARMS
```suggestion
	body_parts_covered = UPPER_TORSO|LOWER_TORSO|ARMS|LEGS
```
раз уж такой пр хочется чтоб скафандр культа закрывал ноги. обычная броня их закрывает же, да и на спрайте видно, что он всё тело закрывает, да и это же блин герметичный костюм для космоса...

2022-02-12 13:05 UTC, MrWestnow commented
Культ - норм, всё равно никто пользоваться будет
Кэп сьют - норм, **правда в рамках этого же ПРа убери дубликат в шкафу**
Синдириги - супер хуйня, особенно идея со спейс режимами
Маг риг - норм, эти бездарности и так будут умирать от первого офицера
Риот - норм

> Вестноу смотрел в сторону ТГ или ещё каких казуальных билдов,где можно вылечить себя после 5 попаданий из стечкина за менее чем пол минуты.

Нет, цель была совершенно иной. И до моего ПРа была клоунада с броней

2022-02-12 14:21 UTC, simb11 commented
Убрал второй набор брони из шкафа капитана.
Броня культа теперь защищает ноги.

2022-02-12 19:16 UTC, Akellazp commented
Бафф брони культа выглядит очень сомнительно учитывая то что она делается буквально из воздуха

2022-02-12 19:24 UTC, kalazus commented
> Бафф брони культа выглядит очень сомнительно учитывая то что она делается буквально из воздуха

Обычная из фавора, космо требует пиерти, что уже точно не "из воздуха".

2022-02-13 14:26 UTC, Akellazp commented
> Обычная из фавора, космо требует пиерти, что уже точно не "из воздуха". 

А ну да культ же так ограничен в фаворе и пиети что не может ничем спамить, ни скелетами, ни гомункулами, ни конструктами

2022-02-14 16:06 UTC, Firein91 commented
Слишком............... много............ бафоф............
![image](https://user-images.githubusercontent.com/93393740/153900618-d33445f2-c78d-49b6-a78e-75eeafa374a4.png)
Бафоцирк

2022-02-19 12:41 UTC, KIBORG04 commented
Че решили?

2022-02-22 15:09 UTC, Kurshan commented on code/modules/clothing/spacesuits/rig/rig.dm
> +	space_armor = list(melee = 55, bullet = 50, laser = 45, energy = 45, bomb = 50, bio = 100, rad = 60)
Всё ещё решительно против бафа конкретной этой брони по причинам, названным выше. Тем более в спейс режиме. И опять же, её надо н е р ф и т ь. Всё ещё самая лучшая броня на станции. Хоть бы что-то сказал на этот счёт. Нигде не увидел аргументов, почему так. но меня попросили ещё раз посмотреть, поэтому повторяюсь.

2022-02-22 15:09 UTC, Kurshan commented on code/modules/clothing/spacesuits/rig/rig.dm
> +	armor = list(melee = 50, bullet = 50, laser = 45, energy = 35, bomb = 65, bio = 100, rad = 10)
Обычно хелметы у нас слабая зона, а не наоборот.

2022-02-22 15:09 UTC, Kurshan commented on code/game/gamemodes/modes_gameplays/cult/cult_items.dm
> +	armor = list(melee = 40, bullet = 25, laser = 35,energy = 30, bomb = 25, bio = 10, rad = 0)
Я бы всё ещё поставил лазер до тридцатки.

2022-02-22 15:22 UTC, simb11 commented on code/modules/clothing/spacesuits/rig/rig.dm
> +	armor = list(melee = 50, bullet = 50, laser = 45, energy = 35, bomb = 65, bio = 100, rad = 10)
Хорошо,понижу статы до уровня сбшного рига.

2022-02-22 15:23 UTC, simb11 commented on code/game/gamemodes/modes_gameplays/cult/cult_items.dm
> +	armor = list(melee = 40, bullet = 25, laser = 35,energy = 30, bomb = 25, bio = 10, rad = 0)
Окей

2022-02-22 20:18 UTC, simb11 commented
Немного уменьшил защиту у шлема сб рига и брони культа .
Убрал нормальную защиту у ригов нюки.
Броню культа не хочу и не планирую трогать,если уменьшать защиту она станет  бесполезной.

2022-02-23 12:57 UTC, KIBORG04 commented on code/modules/clothing/spacesuits/rig/rig.dm
> +	space_armor = list(melee = 55, bullet = 50, laser = 45, energy = 45, bomb = 50, bio = 100, rad = 60)
Не вижу аргументов бафать

2022-02-26 14:48 UTC, KIBORG04 requested changes
Соглашусь с куршаном, смысла бафать риги нюки пока нет

2022-03-01 12:13 UTC, LudwigVonChesterfield commented on code/modules/clothing/spacesuits/rig/rig.dm
> +	space_armor = list(melee = 55, bullet = 50, laser = 45, energy = 45, bomb = 50, bio = 100, rad = 60)
против баффов синдиригов

2022-03-01 21:31 UTC, closed without merging