Кач кач кач кач
TauCetiStation/TauCetiClassic pull request #8650
Opened 2022-02-19 18:30 UTC by DarthSidiousPalpatine

## Описание изменений
Гантеля больше не острая, Велотренажёр качает дольше и сложнее, если ты достиг предела тренажёра, то тебе не больно, что показывает что качаться дальше бесполезно.

## Почему и что этот ПР улучшит
Гантели не острые, Качать ноги в два раза тяжелее, Легче понять полезность качалки.

## Авторство
Darth_Sidious

## Чеинжлог
 :cl: 
 - bugfix: Гантеля больше не острая
 - tweak: Качать ноги на тренажёре в два раза тяжелее
 - tweak: При достижении предела кача тебе не больно качаться

2022-02-19 18:30 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2022-02-19 19:19 UTC, LudwigVonChesterfield commented on code/game/objects/fitness.dm
> +	if(C && (C.pumped < C.max_pumped))
зачем если это проверяется в adjust_pumped

2022-02-19 19:19 UTC, LudwigVonChesterfield commented on code/game/objects/fitness.dm
> +	if(G && (G.pumped < G.max_pumped))
зачем если это проверяется в adjust_pumped

2022-02-19 19:20 UTC, LudwigVonChesterfield commented on code/game/objects/fitness.dm
> +	if(LA && (LA.pumped < LA.max_pumped))
зачем если это проверяется в adjust_pumped

2022-02-19 19:20 UTC, LudwigVonChesterfield commented on code/game/objects/fitness.dm
> +	if(BP.pumped < max_pumped)
зачем если это проверяется в adjust_pumped

2022-02-19 19:20 UTC, LudwigVonChesterfield commented on code/game/objects/fitness.dm
> +	if(RA && (RA.pumped < RA.max_pumped))
зачем если это проверяется в adjust_pumped

2022-02-19 19:20 UTC, DarthSidiousPalpatine commented on code/game/objects/fitness.dm
> +	if(LA && (LA.pumped < LA.max_pumped))
Чтобы было не больно

2022-02-19 19:20 UTC, DarthSidiousPalpatine commented on code/game/objects/fitness.dm
> +	if(RA && (RA.pumped < RA.max_pumped))
чтобы было не больно

2022-02-19 19:20 UTC, DarthSidiousPalpatine commented on code/game/objects/fitness.dm
> +	if(BP.pumped < max_pumped)
чтобы было не больно

2022-02-19 19:21 UTC, DarthSidiousPalpatine commented on code/game/objects/fitness.dm
> +	if(G && (G.pumped < G.max_pumped))
чтобы было не больно

2022-02-19 19:21 UTC, DarthSidiousPalpatine commented on code/game/objects/fitness.dm
> +	if(C && (C.pumped < C.max_pumped))
чтобы было не больно

2022-02-19 19:22 UTC, LudwigVonChesterfield requested changes
Нужно чтобы adjust_pumped возвращал на сколько значение поменялось, тогда вместо
```
if(G && G.pumped < G.max_pumped)
```
что требует знать детали реализации накача, можно
```
if(G && G.adjust_pumped(1) <= 0)
```

Стоит подумать о том чтобы боль уменьшалась с накачем, а не просто мгновенно исчезала?

2022-02-19 19:32 UTC, DarthSidiousPalpatine commented
Вуаля?

2022-02-19 19:35 UTC, LudwigVonChesterfield approved these changes
тут нельзя нейтральный ревью оставить, но выглядит норм

2022-02-19 19:35 UTC, LudwigVonChesterfield commented on code/game/objects/fitness.dm
> +	sharp = 0
разве не FALSE?

2022-02-19 19:35 UTC, DarthSidiousPalpatine commented on code/game/objects/fitness.dm
> +	sharp = 0
хз как работает, но я увидел это у предметов.

2022-02-19 19:36 UTC, DarthSidiousPalpatine commented on code/game/objects/fitness.dm
> +	sharp = 0
может там циферки это урон, а может и нет. Не нашёл концов

2022-02-20 06:29 UTC, DarthSidiousPalpatine commented
ПОфиксил баг с гантелями что делают тебя слабее

2022-02-20 07:09 UTC, DarthSidiousPalpatine commented
Добавил увеличение урона предметом от накачанности руки

2022-02-20 09:03 UTC, LudwigVonChesterfield commented
ХВАТИТ В ОДИН ПР НАКИДЫВАТЬ ВСЕГО

2022-02-20 09:12 UTC, LudwigVonChesterfield commented on code/modules/organs/external/flesh.dm
> +	if(!isnull(cap) && (BP.pumped >= cap))
как это должно что-либо фиксить

2022-02-20 09:13 UTC, LudwigVonChesterfield commented on code/modules/organs/external/flesh.dm
> +	if(!isnull(cap) && (BP.pumped >= cap))
может лучше
```
if(isnull(cap))
    cap = BP.max_pumped

if(BP.pumped >= cap)
    return 0
    ```

2022-02-20 09:24 UTC, DarthSidiousPalpatine commented
> ХВАТИТ В ОДИН ПР НАКИДЫВАТЬ ВСЕГО

Огурцы салат и лук, всё на булочке с кунжутом, Биг Кач Пр, не устоять никак!

2022-02-20 09:24 UTC, DarthSidiousPalpatine commented on code/modules/organs/external/flesh.dm
> +	if(!isnull(cap) && (BP.pumped >= cap))
нет не лучше

2022-02-20 09:25 UTC, LudwigVonChesterfield commented on code/modules/organs/external/flesh.dm
> +	if(!isnull(cap) && (BP.pumped >= cap))
почему

2022-02-20 09:25 UTC, DarthSidiousPalpatine commented on code/modules/organs/external/flesh.dm
> +	if(!isnull(cap) && (BP.pumped >= cap))
Я проверяю только одну ситуацию, когда тренажёр передал свой макс кач и при этом твой кач больше этого макс кача. Тогда ретурн.

ВО всех других случаях надо следовать одному алгоритму.

2022-02-20 09:26 UTC, LudwigVonChesterfield commented on code/modules/organs/external/flesh.dm
> +	if(!isnull(cap) && (BP.pumped >= cap))
мне кажется если кач больше макс кача конечности то тоже не надо логику выполнять остальную

2022-02-20 09:27 UTC, DarthSidiousPalpatine commented on code/modules/organs/external/flesh.dm
> +	if(!isnull(cap) && (BP.pumped >= cap))
Да, но мы не можем проверить больше он или нет если он нулл, например, и тренажёр не передал свой макс кач, а мы ещё не приняли что он соответствует макс качу конечности.

2022-02-20 09:30 UTC, LudwigVonChesterfield commented on code/modules/organs/external/flesh.dm
> +	if(!isnull(cap) && (BP.pumped >= cap))
посмотри мой код выше ещё раз пж, если нулл - ставится макс кап конечности, он всегда число

2022-02-20 09:35 UTC, DarthSidiousPalpatine commented on code/modules/organs/external/flesh.dm
> +	if(!isnull(cap) && (BP.pumped >= cap))
Услышь меня пожалуйста.

Гантель сбрасывала кач конечности до макс капа гантели который меньше капа конечности при проверке.
Вывод? Надо определить мы передаём изначально макскап или берём хумановский. Если изначально то мы не скидываем до него кап, если не изначально то скидываем.

2022-02-20 09:36 UTC, DarthSidiousPalpatine commented on code/modules/organs/external/flesh.dm
> +	if(!isnull(cap) && (BP.pumped >= cap))
Я, если честно, не могу объяснить нормально. Но это работает. Другой вариант - сделать сложнее, дополнительные переменные ввести и т.п. Но оно же и так работает.

2022-02-20 09:41 UTC, LudwigVonChesterfield commented on code/modules/organs/external/flesh.dm
> +	if(!isnull(cap) && (BP.pumped >= cap))
напомни почему не работает то что предложил я

2022-02-20 09:43 UTC, DarthSidiousPalpatine commented on code/modules/organs/external/flesh.dm
> +	if(!isnull(cap) && (BP.pumped >= cap))
Гантель передаёт свой макс кач который может быть меньше текущего кача конечности.

И тогда при проверке if(BP.pumped >= cap) BP.pumped = cap оно ставило на макс кап гантели.

2022-02-20 09:46 UTC, LudwigVonChesterfield commented on code/modules/organs/external/flesh.dm
> +	if(!isnull(cap) && (BP.pumped >= cap))
но если сделать как я предложил выше то оно не дойдет до той проверки ниже которая и сбрасывала

2022-02-20 09:47 UTC, DarthSidiousPalpatine commented on code/modules/organs/external/flesh.dm
> +	if(!isnull(cap) && (BP.pumped >= cap))
Нам нужна ещё одна проверка после того как прибавляет валуе. Так что нет.

2022-02-20 09:53 UTC, DarthSidiousPalpatine commented on code/modules/organs/external/flesh.dm
> +	if(!isnull(cap) && (BP.pumped >= cap))
Готово

2022-02-20 11:44 UTC, LudwigVonChesterfield commented on code/_onclick/item_attack.dm
> +	if(ishuman(user))
мб плюсовать не просто накаченность, а урон с руки в целом? чтобы унатхи сильнее били...

тогда правда надо наверное добавить -2 ко всему урону

2022-02-20 11:44 UTC, LudwigVonChesterfield commented on code/modules/organs/external/flesh.dm
> +	var/old_pumped = BP.pumped
old_pumped надо после if(BP.pumped >= cap) return брать потому-что до смысла нет

2022-02-20 11:44 UTC, DarthSidiousPalpatine commented on code/_onclick/item_attack.dm
> +	if(ishuman(user))
Всего 2 урона, что может пойти не так?)

Унатхи разве сильнее из-за урона, или из-за когтей как и таяры?

2022-02-20 11:45 UTC, LudwigVonChesterfield commented on code/modules/organs/external/flesh.dm
> +		return
```suggestion
		return 0
```

надо же возвращать насколько накачались, и накачались нинасколько

2022-02-20 11:45 UTC, LudwigVonChesterfield commented on code/modules/sports/PedalGen.dm
> +		pedaler.apply_effect(LL.adjust_pumped(1),AGONY,0)
```suggestion
		pedaler.apply_effect(LL.adjust_pumped(1), AGONY, 0)
```

2022-02-20 11:48 UTC, DarthSidiousPalpatine commented
Починено всякое

2022-02-20 12:25 UTC, LudwigVonChesterfield commented on code/_onclick/item_attack.dm
> +	if(ishuman(user))
я имею ввиду если плюсовать урон с руки то надо отнимать 2, потому-что стандартный урон с руки = 2

2022-02-20 12:26 UTC, DarthSidiousPalpatine commented on code/_onclick/item_attack.dm
> +	if(ishuman(user))
Я плюсую только дополнительный урон с руки.

Основной урон с руки не плюсую.

У хумана это 2. у унатха это 4 и т.п.
Это урон руки как таковой. Остальное зависит только от мускул.

2022-02-20 12:27 UTC, LudwigVonChesterfield commented on code/_onclick/item_attack.dm
> +	if(ishuman(user))
я тебе предлагаю вместо того чтобы по всему билду проверять на накаченнось сделать так:

```
power += (user.get_unarmed_attack()["damage"] - 2) * 0.1
```

2022-02-20 12:29 UTC, DarthSidiousPalpatine commented on code/_onclick/item_attack.dm
> +	if(ishuman(user))
Но я не хочу плюсовать унатхам и таярам их когти в урон.

2022-02-20 12:45 UTC, LudwigVonChesterfield commented on code/_onclick/item_attack.dm
> +	if(ishuman(user))
ну а я не хочу по всему билду копипастить нужное для того чтобы просто взять накач руки. мб дождёшься #8636 и из него возьмёшь H.get_pumped(BP_ACTIVE_HAND)

2022-02-20 12:49 UTC, DarthSidiousPalpatine commented on code/_onclick/item_attack.dm
> +	if(ishuman(user))
А может моё смержат быстренько как фиксы, и потом ты заменишь на гетпумпет?

2022-02-22 18:48 UTC, DarthSidiousPalpatine commented
Я переделал прибавку к урону. Теперь только брут и теперь не ко всему плюс.

2022-02-22 18:57 UTC, LudwigVonChesterfield commented on code/_onclick/item_attack.dm
> +	if(ishuman(user) && damtype == "brute")
у нас есть дефайн для типов урона

2022-02-23 14:52 UTC, LudwigVonChesterfield requested changes
1. Замени "brute" на BRUTE
2. сделай что-либо с формулой чтобы она была декларативной, а не императивной.

Мне не надо знать как рисовать график параболы, чтобы знать что урон по ней движется.

Решение должна быть вида
power += curve(force ??? pumped, точка1, точка2)

2022-02-23 15:43 UTC, DarthSidiousPalpatine commented
Смотри, какая красота, Людук, Ммм, всю жизнь бы смотрел на этот прок!

2022-02-23 20:53 UTC, DarthSidiousPalpatine commented
Тадааа, теперь в билде даже есть параболический скейлинг, круто.

2022-02-24 20:23 UTC, LudwigVonChesterfield commented on code/_onclick/item_attack.dm
> +			power += max(round((PARABOLIC_SCALING(force, 1, 0.01) * BP.pumped / 10)), 0) //We need a pumped force multiplied by parabolic scaled item's force with a borders of 1 to 0
```suggestion
			power += max(round((PARABOLIC_SCALING(force, 1, 0.01) * BP.pumped * 0.1)), 0) //We need a pumped force multiplied by parabolic scaled item's force with a borders of 1 to 0
```

2022-02-24 20:24 UTC, LudwigVonChesterfield approved these changes

2022-02-24 20:24 UTC, DarthSidiousPalpatine commented on code/_onclick/item_attack.dm
> +			power += max(round((PARABOLIC_SCALING(force, 1, 0.01) * BP.pumped / 10)), 0) //We need a pumped force multiplied by parabolic scaled item's force with a borders of 1 to 0
Почему ты не любишь деление на 10?

2022-02-24 20:55 UTC, merged