Доступ в ЕВА для учёных и ксеноархеологов
TauCetiStation/TauCetiClassic pull request #8657
Opened 2022-02-20 06:51 UTC by simb11

## Описание изменений
Добавил доступ в ЕВА учёным,ксеноархеологам и РД
## Почему и что этот ПР улучшит
Жизнь учёным и археологам.
## Авторство
я
## Чеинжлог
:cl: Simbaka
- tweak: У учёных и ксеноархеологов появился доступ в ЕВА.

2022-02-20 06:51 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2022-02-20 10:13 UTC, GermanSUS commented
Можно ещё шахтерам? Они могут печатать любые Риги но модифицировать под ксеносов только свой. Звучит как хуйня, не так ли?

2022-02-22 15:17 UTC, Kurshan commented
Зачем ученым доступ к ЕВА, если там нет их профильных ригов?

2022-02-28 16:30 UTC, LudwigVonChesterfield requested changes
По коду - никаких замечаний.

Почему ксеноархам нужен джетпак? Если не джетпак - что им нужно от ЕВА?

Нужен ли джетпак ученым - да, но разве не интересней договариваться с кем-то как его получить?

2022-02-28 16:39 UTC, simb11 commented
Очень интересно КАЖДЫЙ раунд просить ИИ/инженеров/ещё кого открыть ЕВА, ведь в РнД нет ни модификаторов, ни джетпаков для изучения космоса.
Ксеноархеологам нужен металл и улучшения для ригов.

2022-02-28 16:40 UTC, AndroBetel commented
МБ джетпак один дать в теленауку и сделать на аванпост раздатчик модов?

2022-02-28 16:55 UTC, simb11 commented
Джетпак можно добавить в принципе.
Добавлять целый раздатчик ради одного рига слишком жирно.

2022-02-28 17:24 UTC, LudwigVonChesterfield approved these changes
Дошли договора на условиях рефактора наборов в ЕВА. Мержить только после них.

2022-02-28 17:33 UTC, simb11 commented
Закрою этот ПР на ближайший месяц...

2022-02-28 17:33 UTC, closed without merging