Перевод медицинских эмотуов, симптомов и может быть ещё чего
TauCetiStation/TauCetiClassic pull request #8658
Opened 2022-02-20 10:19 UTC by BenDJaminUt

## Описание изменений
Переведены всякие недуги, их симптомы и несколько эмоутов так или иначе связанных со здоровьем куколок

## Почему и что этот ПР улучшит
умираем и лечим на великом и могучем

## Авторство
беньчик

## Чеинжлог
:cl:
- ru: эмоуты так или иначе связанные с заболеваниями и медициной

2022-02-20 10:19 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2022-02-20 10:24 UTC, LudwigVonChesterfield commented on code/datums/diseases/advance/symptoms/fever.dm
> +		to_chat(M, "<span class='notice'>[pick("Вам испытываете жар.", "Вам жарко, вы словно в огне!")]</span>")
Вам испытываете жар?

2022-02-20 10:24 UTC, LudwigVonChesterfield commented on code/datums/diseases/advance/symptoms/dizzy.dm
> +				to_chat(M, "<span class='notice'>Вы не можете смотреть прямо!</span>")
хоть кто-то русскоязычный так говорит про головокружение?

2022-02-20 10:25 UTC, LudwigVonChesterfield commented on code/datums/diseases/advance/symptoms/cough.dm
> +				to_chat(M, "<span notice='notice'>[pick("Вы проглотили свою макроту.", "Вы вынуждены прокашляться.")]</span>")
мокрота

2022-02-20 10:26 UTC, DarthSidiousPalpatine commented on code/datums/diseases/advance/symptoms/dizzy.dm
> +				to_chat(M, "<span class='notice'>Вы не можете смотреть прямо!</span>")
Косоглазие чтоль?

2022-02-20 10:26 UTC, LudwigVonChesterfield commented on code/datums/diseases/advance/symptoms/voice_change.dm
> +				to_chat(M, "<span class='notice'>[pick("У вас болит горло.", "Вы сильно прокашливаетесь.")]</span>")
почему тут переведено как прокашливаетесь, а выше как "вынуждены прокашляться"

https://github.com/TauCetiStation/TauCetiClassic/pull/8658/files#diff-e169dc82389d89fb86ec35ced5e83fe6cf74872057a58c88db7fad834c4aaad1R35

2022-02-20 10:26 UTC, LudwigVonChesterfield commented on code/datums/diseases/advance/symptoms/weight.dm
> +				to_chat(M, "<span class='notice'>[pick("Вы набили свою брюхо до отказа.", "Вы наелись сполна.")]</span>")
```suggestion
				to_chat(M, "<span class='notice'>[pick("Вы набили своё брюхо до отказа.", "Вы наелись сполна.")]</span>")
```

2022-02-20 10:27 UTC, LudwigVonChesterfield commented on code/datums/diseases/appendicitis.dm
> +				to_chat(affected_mob, "<span class='warning'>Вы ворачиваетесь наизнанку в попытке вызвать рвоту, но в вашем желудке ничего не осталось!</span>")
Вы выворачиваетесь?

2022-02-20 10:28 UTC, BenDJaminUt commented on code/datums/diseases/advance/symptoms/voice_change.dm
> +				to_chat(M, "<span class='notice'>[pick("У вас болит горло.", "Вы сильно прокашливаетесь.")]</span>")
поясяю за "вынеждены прокашляться"
в игре этот эмоту заставляет куклу дропнуть предмет. я посчитал странным что "легкий кашель" вынуждает персонажа ронять то что он держал в руке

2022-02-20 10:28 UTC, LudwigVonChesterfield commented on code/datums/diseases/brainrot.dm
> +				to_chat(affected_mob, "<span class='warning'>Вы забываете, кто вы такой.</span>")
Вы не чувствуете себя собой, тут про деперсонализацию а не деменцию

2022-02-20 10:28 UTC, BenDJaminUt commented on code/datums/diseases/appendicitis.dm
> +				to_chat(affected_mob, "<span class='warning'>Вы ворачиваетесь наизнанку в попытке вызвать рвоту, но в вашем желудке ничего не осталось!</span>")
да

2022-02-20 10:28 UTC, LudwigVonChesterfield commented on code/datums/diseases/brainrot.dm
> +					to_chat(affected_mob, "<span class='warning'>У вас болит голова.</span>")*/
комментарии переводить не надо комментарии надо выпиливать

2022-02-20 10:28 UTC, DarthSidiousPalpatine commented on code/datums/diseases/advance/symptoms/fever.dm
> +		to_chat(M, "<span class='notice'>[pick("Вам испытываете жар.", "Вам жарко, вы словно в огне!")]</span>")
"Вам душно"
"Вас ломает"

2022-02-20 10:29 UTC, LudwigVonChesterfield commented on code/datums/diseases/cold.dm
> +				to_chat(affected_mob, "<span class='warning'>У вас пересохло горло.</span>")
sore throat это боли в горле а не сухое горло. как оно может и пересохнуть и макротой наполнится?

2022-02-20 10:29 UTC, LudwigVonChesterfield commented on code/datums/diseases/cold.dm
> +				to_chat(affected_mob, "<span class='warning'>Ваше горло наполняется макротой.</span>")
```suggestion
				to_chat(affected_mob, "<span class='warning'>Ваше горло наполняется мокротой.</span>")
```

2022-02-20 10:29 UTC, BenDJaminUt commented on code/datums/diseases/cold.dm
> +				to_chat(affected_mob, "<span class='warning'>У вас пересохло горло.</span>")
тупанул да

2022-02-20 10:30 UTC, LudwigVonChesterfield commented on code/datums/diseases/cold9.dm
> +				to_chat(affected_mob, "<span class='warning'>В испытываете вялость.</span>")
stiff это что чувствуешь после усердной тренировки, я бы не назвал это вялостью, но как правильно не скажу

2022-02-20 10:31 UTC, LudwigVonChesterfield commented on code/datums/diseases/dna_spread.dm
> +				to_chat(affected_mob, "<span class='warning'>Вы чувтсувете боль в желудке.</span>")
... У вас болит живот?

2022-02-20 10:31 UTC, LudwigVonChesterfield commented on code/datums/diseases/dna_spread.dm
> +				to_chat(affected_mob, "<span class='warning'>Вы чувствуете боль в мышцах.</span>")
У вас болят руки/ноги/в груди

2022-02-20 10:31 UTC, LudwigVonChesterfield commented on code/datums/diseases/dna_spread.dm
> +		to_chat(affected_mob, "<span class='notice'>Вы чувствуете себя самим собой.</span>")
нужно ли это сообщение вообще шиза какая-то

2022-02-20 10:32 UTC, LudwigVonChesterfield commented on code/datums/diseases/advance/symptoms/voice_change.dm
> +				to_chat(M, "<span class='notice'>[pick("У вас болит горло.", "Вы сильно прокашливаетесь.")]</span>")
я понимаю, я говорю про то что, ты не вынужден прокашливаться - ты прокашливаешься
"Вы прокашливаетесь", ниже ты так и перевёл

2022-02-20 10:32 UTC, BenDJaminUt commented on code/datums/diseases/cold9.dm
> +				to_chat(affected_mob, "<span class='warning'>В испытываете вялость.</span>")
изнеможение?

2022-02-20 10:33 UTC, BenDJaminUt commented on code/datums/diseases/dna_spread.dm
> +		to_chat(affected_mob, "<span class='notice'>Вы чувствуете себя самим собой.</span>")
согласен, шиза. не уверен есть ли это в игре вообще

2022-02-20 10:33 UTC, LudwigVonChesterfield commented on code/datums/diseases/advance/symptoms/dizzy.dm
> +				to_chat(M, "<span class='notice'>Вы не можете смотреть прямо!</span>")
тут надо что-то типо "У вас весь мир крутится" наверное

2022-02-20 10:34 UTC, LudwigVonChesterfield commented on code/datums/diseases/flu.dm
> +				to_chat(affected_mob, "<span class='warning'>Вы чувтсувете боль в желудке.</span>")
```suggestion
				to_chat(affected_mob, "<span class='warning'>Вы чувтсувете боль в животе.</span>")
```

2022-02-20 10:34 UTC, LudwigVonChesterfield commented on code/datums/diseases/flu.dm
> +				to_chat(affected_mob, "<span class='warning'>Вы чувтсувете боль в желудке.</span>")
```suggestion
				to_chat(affected_mob, "<span class='warning'>Вы чувтсувете боль в животе.</span>")
```

2022-02-20 10:35 UTC, LudwigVonChesterfield commented on code/datums/diseases/magnitis.dm
> +				to_chat(affected_mob, "<span class='warning'>Вы чувствуете как слабый ток пробегает по вашему телу.</span>")
может лучше мурашки по коже?

2022-02-20 10:35 UTC, LudwigVonChesterfield commented on code/datums/diseases/magnitis.dm
> +				to_chat(affected_mob, "<span class='warning'>Вам кажется,что пришло время подурачиться.</span>")
```suggestion
				to_chat(affected_mob, "<span class='warning'>Вам кажется, что пришло время подурачиться.</span>")
```

2022-02-20 10:35 UTC, BenDJaminUt commented on code/datums/diseases/advance/symptoms/dizzy.dm
> +				to_chat(M, "<span class='notice'>Вы не можете смотреть прямо!</span>")
пол уходит из под ног?

2022-02-20 10:35 UTC, LudwigVonChesterfield commented on code/datums/diseases/magnitis.dm
> +				to_chat(affected_mob, "<span class='warning'>Вы возглашаете в природе чудес.</span>")
... что?

"Вы размышляете о природе чудес"

2022-02-20 10:36 UTC, DarthSidiousPalpatine commented
Давайте не переводить штуки если не можете гуглить значение тех или иных фраз?

2022-02-20 10:36 UTC, BenDJaminUt commented on code/datums/diseases/advance/symptoms/fever.dm
> +		to_chat(M, "<span class='notice'>[pick("Вам испытываете жар.", "Вам жарко, вы словно в огне!")]</span>")
разве жар это не состояние?

2022-02-20 10:37 UTC, LudwigVonChesterfield commented on code/datums/diseases/retrovirus.dm
> +				to_chat(affected_mob, "<span class='warning'>Ваша кожа становится эластичней.</span>")
надо писать наверное от лица чувств персонажа а не физических свойств кожи?

2022-02-20 10:38 UTC, LudwigVonChesterfield commented on code/datums/diseases/retrovirus.dm
> +				to_chat(affected_mob, "<span class='warning'>Ваш желудок выворчаивает на изнанку.</span>")
```suggestion
				to_chat(affected_mob, "<span class='warning'>Ваш желудок выворчаивает наизнанку.</span>")
```

2022-02-20 10:39 UTC, LudwigVonChesterfield commented on code/datums/diseases/flu.dm
> +				to_chat(affected_mob, "<span class='notice'>Вам становится лучше.</span>")
Вы чувствуете себя лучше?

Вроде везде перевод так, будто игроку извне говорят как он себя чувствует. а тут описывается "объективное" состояние как факт мира

2022-02-20 10:39 UTC, LudwigVonChesterfield commented on code/datums/diseases/robotic_transformation.dm
> +				to_chat(affected_mob, "<span class='warning'>Ваши шарниры тяжело поворачиваются.</span>")
... шарниры?

2022-02-20 10:40 UTC, LudwigVonChesterfield commented on code/datums/diseases/robotic_transformation.dm
> +				to_chat(affected_mob, "<span class='warning'>Ваша оболочка становится эластичной.</span>")
оболочка?!

2022-02-20 10:40 UTC, AndroBetel commented
Аффтар выпей йаду.

2022-02-20 10:41 UTC, BenDJaminUt commented on code/datums/diseases/flu.dm
> +				to_chat(affected_mob, "<span class='notice'>Вам становится лучше.</span>")
да, но оно пишется когда персонажу действительно становится лучше

2022-02-20 10:42 UTC, LudwigVonChesterfield commented on code/datums/diseases/advance/symptoms/dizzy.dm
> +				to_chat(M, "<span class='notice'>Вы не можете смотреть прямо!</span>")
какая чудесная фраза, да

2022-02-20 10:42 UTC, LudwigVonChesterfield commented
@BenDJaminUt машинным переводом каким-то делал?

2022-02-20 10:43 UTC, DarthSidiousPalpatine commented on code/datums/diseases/advance/symptoms/dizzy.dm
> +				to_chat(M, "<span class='notice'>Вы не можете смотреть прямо!</span>")
> тут надо что-то типо "У вас весь мир крутится" наверное

кружится голова

2022-02-20 10:43 UTC, BenDJaminUt commented on code/datums/diseases/robotic_transformation.dm
> +				to_chat(affected_mob, "<span class='warning'>Ваши шарниры тяжело поворачиваются.</span>")
да, там же постепенное превращение в киборга идёт. решил, что будет прикольно, если персонаж со временем будет называть части своего тела как части машины

2022-02-20 10:44 UTC, DarthSidiousPalpatine commented on code/datums/diseases/advance/symptoms/dizzy.dm
> +				to_chat(M, "<span class='notice'>Вы не можете смотреть прямо!</span>")
Это проблема глаз или мозга? Если глаз то косоглазие наверн, глаза скосились, не можешь смотреть прямо.

Если мозга то головокружение, наверн. С другой стороны "Глаза скосились" может быть и при сильном ударе по голове, вроде.

2022-02-20 10:44 UTC, BenDJaminUt commented on code/datums/diseases/robotic_transformation.dm
> +				to_chat(affected_mob, "<span class='warning'>Ваша оболочка становится эластичной.</span>")
чуть выше ответил

2022-02-20 10:44 UTC, LudwigVonChesterfield commented on code/datums/diseases/robotic_transformation.dm
> +				to_chat(affected_mob, "<span class='warning'>Ваши шарниры тяжело поворачиваются.</span>")
норм

2022-02-20 10:45 UTC, BenDJaminUt commented
> @BenDJaminUt машинным переводом каким-то делал?

нет, я просто тупо и

2022-02-20 10:45 UTC, LudwigVonChesterfield commented on code/datums/diseases/robotic_transformation.dm
> +				to_chat(affected_mob, "<span class='warning'>Ваша оболочка становится эластичной.</span>")
это выходит типо робот удивляется что его корпус слишком резиновый?

а почему тогда про эластичность где-то там ещё было не у робота..

2022-02-20 10:46 UTC, BenDJaminUt commented on code/datums/diseases/magnitis.dm
> +				to_chat(affected_mob, "<span class='warning'>Вы чувствуете как слабый ток пробегает по вашему телу.</span>")
там вроде про электричество было

2022-02-20 10:46 UTC, DarthSidiousPalpatine commented on code/datums/diseases/robotic_transformation.dm
> +				to_chat(affected_mob, "<span class='warning'>Ваша оболочка становится эластичной.</span>")
А можно не надо, мы всё ещё человеки чтобы себя роботом начинать ощущать, нет?

2022-02-20 10:50 UTC, BenDJaminUt commented on code/datums/diseases/dna_spread.dm
> +				to_chat(affected_mob, "<span class='warning'>Вы чувтсувете боль в желудке.</span>")
поправил

2022-02-20 10:50 UTC, BenDJaminUt commented on code/datums/diseases/dna_spread.dm
> +				to_chat(affected_mob, "<span class='warning'>Вы чувствуете боль в мышцах.</span>")
изменил

2022-02-20 10:52 UTC, BenDJaminUt commented on code/datums/diseases/advance/symptoms/dizzy.dm
> +				to_chat(M, "<span class='notice'>Вы не можете смотреть прямо!</span>")
насколько я понял, там речь именно про головокружение а не глаза

2022-02-20 10:55 UTC, BenDJaminUt commented on code/datums/diseases/advance/symptoms/voice_change.dm
> +				to_chat(M, "<span class='notice'>[pick("У вас болит горло.", "Вы сильно прокашливаетесь.")]</span>")
заменил

2022-02-20 10:57 UTC, DarthSidiousPalpatine commented on code/datums/diseases/cold9.dm
> +				to_chat(affected_mob, "<span class='warning'>В испытываете вялость.</span>")
когда суставы STIFF то это "еле гнутся"

А когда тело stiff то это вялость?

2022-02-20 10:59 UTC, DarthSidiousPalpatine commented on code/datums/diseases/cold9.dm
> +				to_chat(affected_mob, "<span class='warning'>В испытываете вялость.</span>")
Одеревенело, окостенело, окаменело

2022-02-20 10:59 UTC, BenDJaminUt commented on code/datums/diseases/magnitis.dm
> +				to_chat(affected_mob, "<span class='warning'>Вы возглашаете в природе чудес.</span>")
ошибся словом и предлогом и по итогу вообще мракобесие получилось. исправил

2022-02-20 10:59 UTC, LudwigVonChesterfield commented on code/datums/diseases/flu.dm
> +				to_chat(affected_mob, "<span class='notice'>Вам становится лучше.</span>")
но кукла же не должна знать действительно ли ей лучше, или она чувствует себя лучше. хз, думать надо наверное

2022-02-20 11:01 UTC, DarthSidiousPalpatine commented on code/datums/diseases/magnitis.dm
> +				to_chat(affected_mob, "<span class='warning'>Вы чувствуете как слабый ток пробегает по вашему телу.</span>")
мурашки это другое слово, в английском есть своё.

Но можно написать намного лучше что ты чувствуешь слабый ток. Как-то буквально.

"Чувствуете покалывание по всему телу" мб

2022-02-20 11:02 UTC, BenDJaminUt commented on code/datums/diseases/flu.dm
> +				to_chat(affected_mob, "<span class='notice'>Вам становится лучше.</span>")
зависит от того, что вообще эти надписи из себя представляют. если это мысли персонажа, то вроде все ок. а если это метаинфа игроку тогда менять надо да

2022-02-20 11:10 UTC, BenDJaminUt commented on code/datums/diseases/brainrot.dm
> +					to_chat(affected_mob, "<span class='warning'>У вас болит голова.</span>")*/
что делать с этой строкой, удалить?

2022-02-20 11:12 UTC, BenDJaminUt commented on code/datums/diseases/magnitis.dm
> +				to_chat(affected_mob, "<span class='warning'>Вы чувствуете как слабый ток пробегает по вашему телу.</span>")
тогда не понятно что это от электричества

2022-02-20 11:19 UTC, BenDJaminUt commented on code/datums/diseases/robotic_transformation.dm
> +				to_chat(affected_mob, "<span class='warning'>Ваша оболочка становится эластичной.</span>")
stiff поправлю, а что делать этим файлом?

2022-02-20 11:25 UTC, BenDJaminUt commented on code/datums/diseases/flu.dm
> +				to_chat(affected_mob, "<span class='notice'>Вам становится лучше.</span>")
поменял везде на чувства

2022-02-20 11:38 UTC, BenDJaminUt commented on code/datums/diseases/flu.dm
> +				to_chat(affected_mob, "<span class='notice'>Вам становится лучше.</span>")
исправил на чувства где нашел

2022-02-20 11:38 UTC, BenDJaminUt commented on code/datums/diseases/retrovirus.dm
> +				to_chat(affected_mob, "<span class='warning'>Ваша кожа становится эластичней.</span>")
поправил

2022-02-20 11:39 UTC, BenDJaminUt commented on code/datums/diseases/advance/symptoms/fever.dm
> +		to_chat(M, "<span class='notice'>[pick("Вам испытываете жар.", "Вам жарко, вы словно в огне!")]</span>")
поменял

2022-02-20 12:35 UTC, BenDJaminUt commented
вроде где криндж был починил
теперь всё ещё криндж но не так много

2022-02-20 17:34 UTC, Rahmanio commented on code/modules/mob/living/carbon/carbon.dm
> +			to_chat(src, "<span class='notice'>Вы чувтсвуете поток свежего воздуха, наполняющий ваши лёгкие. Приятно.</span>")
```suggestion
			to_chat(src, "<span class='notice'>Вы чувствуете поток свежего воздуха, наполняющий ваши лёгкие. Приятно.</span>")
```

2022-02-20 17:36 UTC, Rahmanio commented on code/modules/mob/living/carbon/human/life.dm
> +						to_chat(src, "<span class='warning'>Вы чувтсвуете себя неважно.</span>")
```suggestion
						to_chat(src, "<span class='warning'>Вы чувствуете себя неважно.</span>")
```

2022-02-20 19:29 UTC, Lexakr requested changes

2022-02-20 19:29 UTC, Lexakr commented on code/modules/mob/living/carbon/human/life.dm
> +		to_chat(src, "<span class='danger'>[pick("Эта боль невыносима!", "Пожалуйста, прекратите эту боль!", "Всё ваше тело немеет!")]</span>")
Боль просто невыносимая! 
Умоляю, просто избавьте меня от боли!

2022-02-20 19:29 UTC, Lexakr commented on code/modules/mob/living/carbon/human/life.dm
> +			visible_message("<span class='name'>[src]</span> больше не в силах управлять своим телом.")
Тело [src] обмякло

2022-02-20 19:29 UTC, Lexakr commented on code/modules/mob/living/carbon/human/life.dm
> +			to_chat(src, "<span class='danger'>[pick("Всё вокруг темнеет!", "Вы чувствуете, что можете в любой момент погибнуть.", "Вы вот-вот потеряете сознание.")]</span>")
Вы теряете сознание!
Вы чувствуете, что можете умереть в любой момент.

2022-02-20 19:29 UTC, Lexakr commented on code/modules/mob/living/carbon/human/life.dm
> +			to_chat(src, "<span class='danger'>[pick("Эта боль невыносима!", "Пожалуйста, прекратите эту боль!!", "Всё ваше тело немеет!")]</span>")
выше

2022-02-20 19:29 UTC, Lexakr commented on code/modules/mob/living/carbon/human/life.dm
> +				to_chat(src, "<span class='userdanger'>Вы чувствуете покалывание в сердце!</span>")
Ваше сердечко резко кольнуло.

2022-02-20 19:29 UTC, Lexakr commented on code/modules/mob/living/carbon/human/life.dm
> +				to_chat(src, "<span class='danger'>Вы чувствуете слабую боль в сердце.</span>")
Ваше сердце немного болит.

2022-02-20 19:29 UTC, Lexakr commented on code/modules/mob/living/carbon/human/say.dm
> +			to_chat(usr, "<span class='userdanger'>Вы немы.</span>")
Вы немой.

2022-02-20 19:29 UTC, Lexakr commented on code/modules/mob/living/carbon/human/say.dm
> +			to_chat(usr, "<span class='userdanger'>Вы попытались сделать жест, но ваши руки вас не слушаются.</span>")
Вы попытались поднять руки, но они Вас не слушаются.

2022-02-20 19:29 UTC, Lexakr commented on code/modules/mob/living/carbon/human/life.dm
> +		emote("me",1,"больше не в силах стоять на ногах и падает!")
больше не может стоять на ногах и падает!

2022-02-20 19:29 UTC, Lexakr commented on code/modules/mob/living/carbon/human/life.dm
> +			to_chat(src, "<span class='danger'>[pick("Эта боль невыносима!", "Пожалуйста, прекратите эту боль!", "Всё ваше тело немеет!")]</span>")
выше варианты

2022-02-20 19:29 UTC, Lexakr commented on code/modules/mob/living/carbon/human/life.dm
> +					to_chat(src, "Так тяжело сконцентрироваться...")
Слишком трудно сосредоточиться...

2022-02-20 19:29 UTC, Lexakr commented on code/modules/mob/living/carbon/human/life.dm
> +			to_chat(src, "<span class='userdanger'>Свет! Он обжигает вас!</span>")
Свет вас обжигает!

2022-02-20 19:29 UTC, Lexakr commented on code/modules/mob/living/carbon/human/life.dm
> +						to_chat(src, "<span class='warning'>Вы чувтсвуете себя неважно.</span>")
слабость

2022-02-20 19:29 UTC, Lexakr commented on code/modules/mob/living/carbon/human/life.dm
> +					to_chat(src, "<span class='warning'>Вы чувствуете себя неважно.</span>")
Вы чувствуете слабость

2022-02-20 19:29 UTC, Lexakr commented on code/modules/mob/living/carbon/human/life.dm
> +					to_chat(src, "<span class='warning'>Ваши ноги вас не слушаются и вы теряете равновесие.</span>")
Ваши ноги Вас не слушаются, вы падаете.

2022-02-20 19:29 UTC, Lexakr commented on code/modules/mob/living/carbon/human/life.dm
> +					to_chat(src, "<span class='warning'>Ваши руки вас не слушаются и вы роняете предмет на пол.</span>")
Ваша рука Вас не слушается, Вы роняете то, что держите в руках

2022-02-20 19:29 UTC, Lexakr commented on code/modules/mob/living/carbon/human/life.dm
> +					to_chat(src, "<span class='warning'>Вам становиться тяжело видеть.</span>")
По какой-то причине становится тяжело видеть.

2022-02-20 19:29 UTC, Lexakr commented on code/modules/mob/living/carbon/human/life.dm
> +					custom_pain("Ваша голова болезненно немеет.")
Ваша голова онемела и болит.

2022-02-20 19:29 UTC, Lexakr commented on code/modules/mob/living/carbon/human/life.dm
> +			visible_message("<span class='danger'>[src] впадает в припадок!</span>", self_message = "<span class='warning'>У вас начинается припадок!</span>")
У (срц) начинается припадок!

2022-02-20 19:29 UTC, Lexakr commented on code/modules/mob/living/carbon/human/human_damage.dm
> +				to_chat(src, "<span class = 'notice'>Ваша [BP.name] снова правильной формы.</span>")
[BP.name] снова в норме.

2022-02-20 19:29 UTC, Lexakr commented on code/modules/mob/living/carbon/human/human_damage.dm
> +					to_chat(src, "<span class = 'notice'>Ваша [BP.name] снова правильной формы.</span>")
[BP.name] снова в норме.

2022-02-20 19:29 UTC, Lexakr commented on code/modules/mob/living/carbon/human/human_damage.dm
> +				to_chat(src, "<span class = 'notice'>Вам кажется, что у вас повреждена [BP.name]...</span>")
Опа склонения. Надо выкручиваться на что-то типа...
Что-то не так с [BP.name]

2022-02-20 19:29 UTC, Lexakr commented on code/modules/mob/living/carbon/human/MedicalSideEffects.dm
> +			H.custom_pain("Из-за этой чесотки тяжело сконцентрироваться.",1)
Из-за этого зуда очень трудно сосредоточиться.

2022-02-20 19:29 UTC, Lexakr commented on code/modules/mob/living/carbon/human/MedicalSideEffects.dm
> +			H.emote("me",1,"немного трясётся.")
слегка вздрагивает
представь как зачесалось сильно и ты такой бррр аж вздрогнул

2022-02-20 19:29 UTC, Lexakr commented on code/modules/mob/living/carbon/human/MedicalSideEffects.dm
> +			H.custom_pain("Вы очень сильно хотите расчесать зудящее место.",0)
Вы сильно хотите почесать зудящее место

2022-02-20 19:29 UTC, Lexakr commented on code/modules/mob/living/carbon/human/MedicalSideEffects.dm
> +	cure_message = "Чесотка прекращается..."
Зуд

2022-02-20 19:29 UTC, Lexakr commented on code/modules/mob/living/carbon/human/MedicalSideEffects.dm
> +			H.custom_pain("Всё ваше тело болит.",1)
Вы чувствуете боль по всему телу

2022-02-20 19:29 UTC, Lexakr commented on code/modules/mob/living/carbon/human/MedicalSideEffects.dm
> +			H.emote("me",1,"вздрагивает от внезапной судороги по всему телу.")
вздрагивает, когда все его мышцы сводит судорогой.

2022-02-20 19:29 UTC, Lexakr commented on code/modules/mob/living/carbon/human/MedicalSideEffects.dm
> +			H.custom_pain("Мышцы по всему вашему телу болезненно охватываются судорогой.",0)
Мышцы вашего тела болезненно сводит судорогами

2022-02-20 19:29 UTC, Lexakr commented on code/modules/mob/living/carbon/human/MedicalSideEffects.dm
> +			H.custom_pain("Вы чувствуете мышечную боль по всему вашему телу.",0)
Ваши мышцы немного болят.

2022-02-20 19:29 UTC, Lexakr commented on code/modules/mob/living/carbon/human/MedicalSideEffects.dm
> +	cure_message = "Судорога постепенно проходит..."
Судороги прошли...

2022-02-20 19:29 UTC, Lexakr commented on code/modules/mob/living/carbon/human/MedicalSideEffects.dm
> +			H.custom_pain("Вас сильно тошнит.",1)
Вам дурно.

2022-02-20 19:29 UTC, Lexakr commented on code/modules/mob/living/carbon/human/MedicalSideEffects.dm
> +			H.custom_pain("Вы чувтсвуете боль в животе.",0)
У вас болит живот

2022-02-20 19:29 UTC, Lexakr commented on code/modules/mob/living/carbon/human/MedicalSideEffects.dm
> +			H.custom_pain("Вы чувствуете странную пустоту в области живота.",0)
Вы чувствуете небольшую тяжесть в животе

2022-02-20 19:29 UTC, Lexakr commented on code/modules/mob/living/carbon/human/MedicalSideEffects.dm
> +	cure_message = "Ваш живот постепенно выздоравливает..."
Ваш живот немного проходит...

2022-02-20 19:29 UTC, Lexakr commented on code/modules/mob/living/carbon/human/MedicalSideEffects.dm
> +			H.custom_pain("Вы чувствуете сильнейшую боль в голове!",1)
мучительную

2022-02-20 19:29 UTC, Lexakr commented on code/modules/mob/living/carbon/human/MedicalSideEffects.dm
> +			H.custom_pain("Вы чувствуете сильную боль в голове!",1)
пульсирующая

2022-02-20 19:29 UTC, Lexakr commented on code/modules/mob/living/carbon/carbon.dm
> +			to_chat(user, "<span class='warning'>Повторяйте каждые 7 секунд, как минимум.</span>")
Повторяйте как минимум каждые 7 секунд

2022-02-20 19:29 UTC, Lexakr commented on code/modules/mob/living/carbon/carbon.dm
> +			to_chat(src, "<span class='notice'>Вы чувтсвуете поток свежего воздуха, наполняющий ваши лёгкие. Приятно.</span>")
Вы чувствуете, как глоток свежего воздуха входит в ваши легкие. Это приятное чувство.

2022-02-20 19:29 UTC, Lexakr commented on code/modules/mob/living/carbon/carbon.dm
> +			visible_message("<span class='warning'>[user] делает ИВЛ [src]!</span>")
иск дыхание

2022-02-20 19:29 UTC, Lexakr commented on code/modules/mob/living/carbon/carbon.dm
> +				to_chat(user, "<span class='notice bold'>Снимите [wear_mask] с[src]!</span>")
в игре надо чекать, кринжово наверное выглядит. Мб ваще пока "Снимите маску с [src]", но надо смотреть

2022-02-20 19:29 UTC, Lexakr commented on code/modules/mob/living/carbon/carbon.dm
> +				to_chat(user, "<span class='notice bold'>Этой расе нельзя делать ИВЛ!</span>")
искусственное дыхание

2022-02-20 19:29 UTC, Lexakr commented on code/modules/mob/living/carbon/carbon.dm
> +			to_chat(user, "<span class='notice bold'>Ваша раса не может делать ИВЛ!</span>")
..не может делать искусственное дыхание

2022-02-20 19:29 UTC, Lexakr commented on code/modules/mob/living/carbon/carbon.dm
> +	visible_message("<span class='danger'>[user] пытается сделать ИВЛ [src]!</span>")
пытается сделать искусственное дыхание

2022-02-20 19:29 UTC, Lexakr commented on code/modules/mob/living/carbon/carbon.dm
> +			"<span class='rose'>Вы слышите потрескивание света.</span>" \
Вы слышите легкое пиканье

2022-02-20 19:29 UTC, Lexakr commented on code/modules/mob/living/carbon/carbon.dm
> +			"<span class='rose'>Вы чувствуете как ток проходит по вашему телу.</span>", \
Вы чувствуете легкий импульс, проходящий через ваше тело.

2022-02-20 19:29 UTC, Lexakr commented on code/modules/mob/living/carbon/carbon.dm
> +			"<span class='danger'>Сильнейший электрический удар проходит сквозь ваше тело!</span>", \
выше писал

2022-02-20 19:29 UTC, Lexakr commented on code/datums/diseases/xeno_transformation.dm
> +			to_chat(affected_mob, "<span class='warning'>Ваша кожа вам очень сильно жмёт...</span>")
Ваша кожа огрубела до невозможности...

2022-02-20 19:29 UTC, Lexakr commented on code/datums/diseases/xeno_transformation.dm
> +				affected_mob.say(pick("А ты выглядишь вкусно.", "Я поглощу... поглощу тебя...", "Хщсссс!"))
Выглядишь аппетитно.
Хочу...поглотить тебя...
Хссссс

2022-02-20 19:29 UTC, Lexakr commented on code/datums/diseases/xeno_transformation.dm
> +				to_chat(affected_mob, pick("<span class='warning'>Вам очень тесно в этой коже.</span>", "<span class='warning'>Ваша кровь начинает кипеть!</span>"))
Ваша кожа очень плотная.
Ваша кровь закипает!

2022-02-20 19:29 UTC, Lexakr commented on code/datums/diseases/xeno_transformation.dm
> +				to_chat(affected_mob, "<span class='warning'>Вы чувствуете как внутри вас...что-то движется.</span>")
двигается

2022-02-20 19:29 UTC, Lexakr commented on code/datums/diseases/xeno_transformation.dm
> +				to_chat(affected_mob, "<span class='warning'>Вы чувствуете острую боль в голове.</span>")
пульсирующую

2022-02-20 19:53 UTC, BenDJaminUt commented
вот это я оподливился конечно да

2022-02-20 19:56 UTC, BenDJaminUt commented on code/datums/diseases/brainrot.dm
> +				affected_mob.visible_message("[affected_mob] suddenly collapses", self_message = "<span class='warning'>Вы теряете своё сознание...</span>")
убрал до ревува

2022-02-21 06:27 UTC, bowlofsoup4ik commented on code/datums/diseases/brainrot.dm
> +					to_chat(affected_mob, "<span class='warning'>Странный гул наполняет вашу голову, заменяя собой любые мысли.</span>")
"лишая"? может лучше "вытесняя собой мысли" или подобное?

2022-02-21 14:54 UTC, BenDJaminUt commented on code/modules/mob/living/carbon/human/life.dm
> +		if(shock_stage == 30) emote("me",1,"с трудом держит глаза открытыми.")
ты уверен?

2022-02-21 15:16 UTC, BenDJaminUt commented on code/modules/mob/living/carbon/human/human_damage.dm
> +				to_chat(src, "<span class = 'notice'>Вам кажется, что у вас повреждена [BP.name]...</span>")
что-то не так с [рука/нога/голова]

мне кажется что лучше пока так оставить

2022-02-27 21:39 UTC, DarthSidiousPalpatine requested changes
Херня, чини

2022-02-27 21:39 UTC, DarthSidiousPalpatine commented on code/datums/diseases/brainrot.dm
> +					to_chat(affected_mob, "<span class='warning'>Your head hurts</span>")*/
Точку верни

2022-02-27 21:39 UTC, DarthSidiousPalpatine commented on code/datums/diseases/brainrot.dm
> +					to_chat(affected_mob, "<span class='warning'>Your head hurts</span>")*/
Точку верни

2022-02-27 21:39 UTC, DarthSidiousPalpatine commented on code/datums/diseases/brainrot.dm
> +					to_chat(affected_mob, "<span class='warning'>Странное жужжание заполняет голову, вытесняя собою все мысли.</span>")
собой

2022-02-27 21:39 UTC, DarthSidiousPalpatine commented on code/datums/diseases/cold.dm
> +				to_chat(affected_mob, "<span class='warning'>Мокрота стекает по Вашему горлу.</span>")
хватит везде выделять "Вы" "Ваш" с большой буквы!

2022-02-27 21:39 UTC, DarthSidiousPalpatine commented on code/datums/diseases/cold9.dm
> +				to_chat(affected_mob, "<span class='notice'>Вам становится лучше.</span>")
Вы чувствуете себя лучше

2022-02-27 21:39 UTC, DarthSidiousPalpatine commented on code/datums/diseases/cold9.dm
> +				to_chat(affected_mob, "<span class='warning'>Вы испытываете вялость.</span>")
Всё тело ноет

2022-02-27 21:39 UTC, DarthSidiousPalpatine commented on code/datums/diseases/cold9.dm
> +				to_chat(affected_mob, "<span class='warning'>Вы чувствуете скованность.</span>")
Всё тело ноет

2022-02-27 21:39 UTC, DarthSidiousPalpatine commented on code/datums/diseases/fluspanish.dm
> +				to_chat(affected_mob, "<span class='warning'>Вы горите в собсвтенной шкуре!</span>")
У вас жар

2022-02-27 21:39 UTC, DarthSidiousPalpatine commented on code/datums/diseases/fluspanish.dm
> +				to_chat(affected_mob, "<span class='warning'>Вы горите в собсвтенной шкуре!</span>")
У вас жар

2022-02-27 21:39 UTC, DarthSidiousPalpatine commented on code/datums/diseases/magnitis.dm
> +				to_chat(affected_mob, "<span class='warning'>Вы чувствуете легкий импульс, проходящий через Ваше тело</span>")
в

2022-02-27 21:39 UTC, DarthSidiousPalpatine commented on code/datums/diseases/retrovirus.dm
> +					to_chat(affected_mob, "<span class='notice'>Вам чувствуете себя лучше.</span>")
Вы

2022-02-27 21:39 UTC, DarthSidiousPalpatine commented on code/datums/diseases/retrovirus.dm
> +				to_chat(affected_mob, "<span class='warning'>У Вас бурлит в желудке.</span>")
в

2022-02-27 21:39 UTC, DarthSidiousPalpatine commented on code/datums/diseases/wizarditis.dm
> +				affected_mob.say(pick("Ты не пройдёшь!", "Экспеллиармус", "Борода Мерлина!", "Вы чувствуете мощь Тёмной Стороны!"))
Мерлинова борода!

2022-02-27 21:39 UTC, DarthSidiousPalpatine commented on code/datums/diseases/wizarditis.dm
> +				affected_mob.say(pick("Ты не пройдёшь!", "Экспеллиармус", "Борода Мерлина!", "Вы чувствуете мощь Тёмной Стороны!"))
Узнай могущество тёмной стороны

2022-02-27 21:39 UTC, DarthSidiousPalpatine commented on code/datums/diseases/wizarditis.dm
> +				to_chat(affected_mob, "<span class='warning'>Вы чувствуете [pick("магию бурлящую в ваших венах","что эта локация дает вам +1 к интеллекту","стремление призвать фамильяра.")].</span>")
, что

2022-02-27 21:39 UTC, DarthSidiousPalpatine commented on code/datums/diseases/wizarditis.dm
> +				to_chat(affected_mob, "<span class='warning'>Вы чувствуете [pick("что эта локация дает вам +2 к интеллекту и +1 к магии","нужду телепортироваться")].</span>")
, что

2022-02-27 21:39 UTC, DarthSidiousPalpatine commented on code/modules/mob/living/carbon/carbon.dm
> +				to_chat(user, "<span class='notice bold'>Снимите маску с[src]!</span>")
с [src]

2022-02-27 21:39 UTC, DarthSidiousPalpatine commented on code/modules/mob/living/carbon/human/human_damage.dm
> +				to_chat(src, "<span class = 'notice'>Вам кажется, что у Вас повреждена [BP.name]...</span>")
Повреждена Head
Повреждена Chest?

2022-02-27 21:39 UTC, DarthSidiousPalpatine commented on code/modules/mob/living/carbon/human/life.dm
> +					to_chat(src, "<span class='warning'>Ваши руки Вас не слушается, Вы роняете то, что в них держали.</span>")
не слушаются
в

2022-02-27 21:39 UTC, DarthSidiousPalpatine commented on code/modules/mob/living/carbon/human/life.dm
> +					to_chat(src, "<span class='warning'>Ваши ноги Вас не слушаются и Вы теряете равновесие.</span>")
в

2022-02-27 21:39 UTC, DarthSidiousPalpatine commented on code/modules/mob/living/carbon/human/life.dm
> +		to_chat(src, "<span class='danger'>[pick("Как же больно!", "Вам точно нужно обезболивающее.", "Господи, какая боль!")]</span>")
Шиза

2022-02-27 21:39 UTC, DarthSidiousPalpatine commented on code/modules/mob/living/carbon/human/life.dm
> +				to_chat(src, "<span class='userdanger'>Вы чувствуете покалывание в сердце!</span>")
Не покалывание, а Резкий укол в сердце.

Вы чувствуете укол в сердце

2022-02-27 21:39 UTC, DarthSidiousPalpatine commented on code/modules/mob/living/carbon/human/say.dm
> +			to_chat(usr, "<span class='userdanger'>Вы попытались поднять руки, но они Вас не слушаются.</span>")
_Я не вижу ваши рукииии! Двигай локтями, У! Танцуем локтями!_

Вы пытаетесь жестикулировать, но руки вас не слушаются.

И да, в

2022-02-27 21:44 UTC, LudwigVonChesterfield commented on code/datums/diseases/advance/symptoms/itching.dm
> +		to_chat(M, "<span class='notice'>Ваша [pick("спина", "рука", "нога", "пятка", "голова")] сильно чешется.</span>")
замените пятка на жопа и готов мержить

я думаю интересней если тут пишутся части тела которые есть у куклы в игре, а не которых нету

2022-02-27 21:44 UTC, LudwigVonChesterfield commented on code/datums/diseases/advance/symptoms/itching.dm
> +		to_chat(M, "<span class='notice'>Ваша [pick("спина", "рука", "нога", "пятка", "голова")] сильно чешется.</span>")
(тут же даже была когда-то жопа, не?)

2022-02-27 21:47 UTC, DarthSidiousPalpatine commented on code/datums/diseases/advance/symptoms/itching.dm
> +		to_chat(M, "<span class='notice'>Ваша [pick("спина", "рука", "нога", "пятка", "голова")] сильно чешется.</span>")
Жопы тоже нет в игре.

В любом случае, чесать ЖОПУ, чесать ПЯТКУ это какой-то кринж.

2022-02-27 21:52 UTC, DarthSidiousPalpatine commented on code/datums/diseases/advance/symptoms/itching.dm
> +		to_chat(M, "<span class='notice'>Ваша [pick("спина", "рука", "нога", "пятка", "голова")] сильно чешется.</span>")
Ладно, Людук хочет больше почёсываний.

Добавь ещё вариантов:
Почесал жопу, Почесал Яица, Почесал подмышку, Почесал макушку, Почесал живот, Почесал рёбра, Почесал пятку, Почесал за ухом, Почесал нос, Почесал языком

2022-03-05 12:16 UTC, closed without merging