Локализация лобби
TauCetiStation/TauCetiClassic pull request #8665
Opened 2022-02-21 03:55 UTC by Lexakr

## Описание изменений
Неполная локализация лобби. Все, что поддавалось в mob/dead/new_player, за исключением poll.dm, вообще не особо понял, что это такое и надо ли... 

Отдельно нужно переводить сетап, окна манифестов, профы в выборе профессии. Скриншотесы:
![image](https://user-images.githubusercontent.com/29842063/154886442-13bb25c8-30fc-4be0-ae21-55cf537dd1c5.png)
![image](https://user-images.githubusercontent.com/29842063/154886450-b1a31876-c328-4d27-8288-0dc5743593a1.png)
![image](https://user-images.githubusercontent.com/29842063/154886473-ab83409d-8af7-49d0-ac6a-50cec32cc1b9.png)

## Почему и что этот ПР улучшит
QoL
## Авторство

## Чеинжлог
:cl:
 - ru: Локализация лобби.

2022-02-21 03:55 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2022-02-21 05:06 UTC, KIBORG04 commented on code/modules/mob/dead/new_player/lobby.dm
> -#define MARK_NOT_READY "READY <span style='color:red'>☒</span>"
Это далеко не QoL и выглядит очень страшно

2022-02-21 05:07 UTC, KIBORG04 commented on code/modules/mob/dead/new_player/new_player.dm
> +		a.autosay("[character.real_name],[rank ? " [rank]," : " турист," ] прибыл на станцию.", "Система Оповещений о Прибытии")
Нет.

2022-02-21 05:09 UTC, KIBORG04 commented on code/modules/mob/dead/new_player/new_player.dm
> +			"Синтетический разум" = list(jobs = list(), titles = nonhuman_positions, color = "#ccffcc"),
какой еще синтетический разум...

2022-02-21 11:12 UTC, Akellazp commented on code/modules/mob/dead/new_player/new_player.dm
>  			"Руководство" = list(jobs = list(), titles = command_positions, color = "#aac1ee"),
а может всё же "командный состав"?

2022-02-21 12:33 UTC, WatlerJe commented
В будущем появится возможность смены локализации на стороне клиента?

2022-02-21 12:34 UTC, DarthSidiousPalpatine commented
> В будущем появится возможность смены локализации на стороне клиента?

Надо было делать это сразу. Но из того что я спрашивал отвечают - Нет

2022-02-22 21:09 UTC, Akellazp commented on code/modules/mob/dead/new_player/new_player.dm
> +		if(tgui_alert(src,"Вы уверены, что хотите стать наблюдателем? Вам придется подождать 30 минут, прежде чем Вы сможете возродиться!","Player Setup", list("Да","Нет")) == "Да")
почему player setup не перевел

2022-02-23 04:53 UTC, WatlerJe commented
Нет спасибо, адаптацию от местного нетфликса мне не надо. _Гениальная пишущая машинка_ и прочее помои уровня перевода школьниками всякого онимэ, пускай переваривают те кто этим питаются на регулярной основе. 

Алсо, что мешает сначала все перевести весь текст, провести редакторский контроль и т.д. А уже потом запилить все готовое в билд? Как раз запилить функцию с выбором локализации.

Пока не запилят выбор локализации, ссу на лица тех кто занимается этим богомерзким занятием.

2022-03-09 11:47 UTC, DarthSidiousPalpatine requested changes
сделай что-то со столбцами профессий, почему они все вразнобой как-то, без единого стиля написания.
Это - список профессий, персонала станции. Ты можешь стать работником технического персонала, медицинского персонала, научного персонала, персонала службы безопасности и т.п. Хз.

Ну и остальное исправь. И НЕ ИСПОЛЬЗУЙ ВЫ ВАМ с большой буквы внутри текста!
Учебником русского языка тебе по голове *бац*

2022-03-09 11:47 UTC, DarthSidiousPalpatine commented on code/modules/mob/dead/new_player/lobby.dm
> +	dat += {"<a class="menu_a" href='?src=\ref[src];lobby_changelog=1'>Чейнжлог</a>"}
Изменения

2022-03-09 11:47 UTC, DarthSidiousPalpatine commented on code/modules/mob/dead/new_player/new_player.dm
> +		if(tgui_alert(src,"Вы уверены, что хотите стать наблюдателем? Вам придется подождать 30 минут, прежде чем Вы сможете возродиться!","Player Setup", list("Да","Нет")) == "Да")
Вы уверены что хотите наблюдать?

2022-03-09 11:47 UTC, DarthSidiousPalpatine commented on code/modules/mob/dead/new_player/new_player.dm
> +				tgui_alert(usr, "Вас нет в вайтлисте, чтобы играть за [client.prefs.species].")
"У вас нет разрешения играть за"
И вообще, тут оставь английский, у нас ещё нет спряжений

2022-03-09 11:47 UTC, DarthSidiousPalpatine commented on code/modules/mob/dead/new_player/new_player.dm
> +				tgui_alert(usr, "Вас нет в вайтлисте, чтобы играть за [client.prefs.species].")
"У вас нет разрешения играть за"
И вообще, тут оставь английский, у нас ещё нет спряжений

2022-03-09 11:47 UTC, DarthSidiousPalpatine commented on code/modules/mob/dead/new_player/new_player.dm
> +		to_chat(usr, "<span class='notice'>[rank] недоступен. Пожалуйста, выберите другую роль.</span>")
профессию/специальность, а не роль.

2022-03-09 11:47 UTC, DarthSidiousPalpatine commented on code/modules/mob/dead/new_player/new_player.dm
> +		to_chat(src, "Заблокировано! Вы подтвердили свою готовность.")
Нельзя редактировать персонажа после готовности.

2022-03-09 11:47 UTC, DarthSidiousPalpatine commented on code/modules/mob/dead/new_player/new_player.dm
> +			to_chat(src, "<span class='red'>Вы не можете наблюдать, потому что эта роль у Вас забанена.</span>")
Вам заблокировано наблюдение за раундом.

2022-03-09 11:47 UTC, DarthSidiousPalpatine commented on code/modules/mob/dead/new_player/new_player.dm
> +				dat += "<div class='notice red'>Шаттл отбытия уже отправился.</div><br>"
Шаттл отбытия уже отчалил от станции.

2022-03-09 11:47 UTC, DarthSidiousPalpatine commented on code/modules/mob/dead/new_player/new_player.dm
> +				dat += "<div class='notice red'>Шаттл отбытия уже отправился.</div><br>"
или отправился от станции

2022-03-09 11:47 UTC, DarthSidiousPalpatine commented on code/modules/mob/dead/new_player/new_player.dm
> +		dat += "<div class='notice red'>В настоящее время нет свободных ролей!</div>"
работ/профессий/специальностей.

2022-03-09 11:47 UTC, DarthSidiousPalpatine commented on code/modules/mob/dead/new_player/new_player.dm
> +		dat += "<div class='clearBoth'>Выберите одну из доступных ролей:</div>"
работ/профессий/специальностей

2022-03-09 11:47 UTC, DarthSidiousPalpatine commented on code/modules/mob/dead/new_player/new_player.dm
> +			"Синтетический разум" = list(jobs = list(), titles = nonhuman_positions, color = "#ccffcc"),
Машины обслуживания, Обслуживающие механизмы

2022-03-09 11:47 UTC, DarthSidiousPalpatine commented on code/modules/mob/dead/new_player/new_player.dm
>  			"Руководство" = list(jobs = list(), titles = command_positions, color = "#aac1ee"),
Командный состав

2022-03-09 11:47 UTC, DarthSidiousPalpatine commented on code/modules/mob/dead/new_player/new_player.dm
> +			"Научные сотрудники" = list(jobs = list(), titles = science_positions, color = "#e6b3e6"),
Мне абсолютно не нравится тут разнобой. Подведи всё под один вид и стиль.

2022-03-09 11:47 UTC, DarthSidiousPalpatine commented on code/modules/mob/dead/new_player/new_player.dm
> +						if(jobcat == "Руководство")
Аналогично командный состав. Командование

2022-03-09 12:19 UTC, LudwigVonChesterfield commented on code/modules/mob/dead/new_player/new_player.dm
> +		to_chat(usr, "<span class='notice'>[rank] недоступен. Пожалуйста, выберите другую роль.</span>")
мб Профессия [rank] недоступна? правда тогда мемы будет с ИИ и Киборгами как профессией

2022-04-08 05:31 UTC, closed without merging