Here comes the money!
TauCetiStation/TauCetiClassic pull request #8817
Opened 2022-03-10 17:35 UTC by DarthSidiousPalpatine

## Описание изменений
1)Респрайт купюр. Респрайт электронных денег, Респрайт кошелька.
2)Купюры теперь стакаются в стаки купюр до 10 купюр в стаке. Кошелёк теперь отображает три купюры внутри.
3)Вендоматы теперь принимают наличные деньги.
4)Иконка кредита теперь существует и где можно заменяет $ и cr.

Скриншотики:
![image](https://user-images.githubusercontent.com/21008918/158995368-46a7d6cf-265f-4111-a6df-5d734bee409b.png)
![image](https://user-images.githubusercontent.com/21008918/158995398-bcaf2c4d-ce7e-42fe-b90a-615dadb47fe9.png)
![image](https://user-images.githubusercontent.com/21008918/158995484-82af727e-476f-4ac0-b169-74474628b75a.png)
![image](https://user-images.githubusercontent.com/21008918/158995588-47a3c2a0-639c-44b9-a70f-cb8aadf714c3.png)

## Почему и что этот ПР улучшит
Больше взаимодействия наличке. Возможность вообще покупать за наличку вещи (Кстати, в обход логов транзакций)
Респрайты это хорошо.

## Авторство
Darth_Sidious и все все все, кто помогал в дискорде.

Оригинальные звуки взяты из источников и были изменены:
amabok: https://freesound.org/people/amabok/sounds/41195/ - выдача купюр.
SpliceSound: https://freesound.org/people/SpliceSound/sounds/369853 - свайп картой.
PerMagnusLindborg: https://freesound.org/people/PerMagnusLindborg/sounds/324243 - вставка купюр.
templeofhades: https://freesound.org/people/templeofhades/sounds/222999/ - велкро липучка.
Coral_Island_Studios: https://freesound.org/people/Coral_Island_Studios/sounds/459546/ - шуршание купюр.

## Чеинжлог
 :cl:
 - image: Изменён спрайт купюр, Изменён спрайт кошелька, Изменён спрайт электронных денег.
 - rscadd: Добавлена возможность стакать купюры в пачки денег до 10-и штук.
 - rscadd: Добавлена возможность покупать вещи за наличные в вендоматах.
 - image: Иконка кредита вместо cr. и $
 - sound: Добавлен звук свайпа карты, печати денег, вставки денег, велкро липучки (для кошелька).

2022-03-10 17:35 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2022-03-10 20:14 UTC, KIBORG04 commented on code/game/objects/structures/crates_lockers/closets/secure/freezer.dm
> -		new /obj/item/weapon/spacecash/c1000(src)
Ты если выпиливаешь 1к, то выпили нормально. Сейчас ты тупо заменил везде в коде c100 на c500

2022-03-10 20:17 UTC, KIBORG04 commented on tgui/packages/tgui/assets/bg-credit.svg
> +<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 137.95 162.94"><defs><style>.cls-1{fill:#fff;}</style></defs><title>bg-credit</title><g id="Слой_2" data-name="Слой 2"><g id="Слой_1-2" data-name=
Ты даже ни один интерфейс не изменил. Ты тупо вставил код, который не будет работать. Я тебе все что нужно скинул, а ты все равно сделал по-своему.

2022-03-10 21:29 UTC, LudwigVonChesterfield commented on code/game/objects/items/weapons/storage/wallets.dm
> +			I.color = list(1/i,0,0, 0,1/i,0, 0,0,1/i, 0,0,0)
можешь сделать #define COLOR_LUMINOSITY(lum) list(1 / lum, 0, 0... и т.д.

2022-03-10 21:29 UTC, LudwigVonChesterfield commented on code/game/objects/items/weapons/storage/wallets.dm
> +			var/icon/Ic = icon(B.icon, B.icon_state)
@KIBORG04 можно не иконкой?

2022-03-10 21:30 UTC, LudwigVonChesterfield commented on code/modules/economy/cash.dm
> +	if(istype(I, /obj/item/weapon/spacecash/bill) && !istype(src.loc, /obj/item/weapon/storage/bill_bundle))
```suggestion
	if(istype(I, /obj/item/weapon/spacecash/bill))
```

у них же нет общего родителя...

и сделай пожалуйста ранний возврат
```
/obj/item/weapon/spacecash/attackby()
  if(!istype(bill))
     return ..()
     
   твой код склеивания купюр
   ```

2022-03-10 21:33 UTC, KIBORG04 commented on code/game/objects/items/weapons/storage/wallets.dm
> +			var/icon/Ic = icon(B.icon, B.icon_state)
Не иконкой нельзя. А вот куда-то сохранить ссылку на эту иконку можно. Тот же статик

2022-03-11 04:28 UTC, DarthSidiousPalpatine commented on code/game/objects/structures/crates_lockers/closets/secure/freezer.dm
> -		new /obj/item/weapon/spacecash/c1000(src)
Деноминация

2022-03-11 04:29 UTC, DarthSidiousPalpatine commented on tgui/packages/tgui/assets/bg-credit.svg
> +<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 137.95 162.94"><defs><style>.cls-1{fill:#fff;}</style></defs><title>bg-credit</title><g id="Слой_2" data-name="Слой 2"><g id="Слой_1-2" data-name=
Потому что я не понял

2022-03-11 04:30 UTC, DarthSidiousPalpatine commented on code/game/objects/items/weapons/storage/wallets.dm
> +			I.color = list(1/i,0,0, 0,1/i,0, 0,0,1/i, 0,0,0)
Ну, если это так нужно..

2022-03-11 04:31 UTC, DarthSidiousPalpatine commented on code/modules/economy/cash.dm
> +	if(istype(I, /obj/item/weapon/spacecash/bill) && !istype(src.loc, /obj/item/weapon/storage/bill_bundle))
У кого "У них"? Я проверил находится ли кэш ВНУТРИ билл бандл.

2022-03-11 04:32 UTC, DarthSidiousPalpatine commented on code/modules/economy/cash.dm
> +	if(istype(I, /obj/item/weapon/spacecash/bill) && !istype(src.loc, /obj/item/weapon/storage/bill_bundle))
Чтобы нельзя было тыкать по интерфейсу с купюрами и делать смешные прозрачные вещи которых нет.

2022-03-11 06:57 UTC, KIBORG04 commented on code/game/objects/structures/crates_lockers/closets/secure/freezer.dm
> -		new /obj/item/weapon/spacecash/c1000(src)
Нормально выпили класс, сейчас ты всё тупо позаменял, убил логику и некоторый код

2022-03-11 06:58 UTC, DarthSidiousPalpatine commented on code/game/objects/structures/crates_lockers/closets/secure/freezer.dm
> -		new /obj/item/weapon/spacecash/c1000(src)
Я не понял какой я код убил. Всё работает же.

2022-03-11 07:00 UTC, KIBORG04 commented on code/game/objects/structures/crates_lockers/closets/secure/freezer.dm
> -		new /obj/item/weapon/spacecash/c1000(src)
![image](https://user-images.githubusercontent.com/26389417/157818162-7e51cc69-2562-46d4-908d-700eff13417b.png)

Интересно, какой же номинал теперь будет чаще всего спавниться? И ведь так везде. Я даже этот комментарий оставит месте, где логика приняла ислам

2022-03-11 07:02 UTC, DarthSidiousPalpatine commented on code/game/objects/structures/crates_lockers/closets/secure/freezer.dm
> -		new /obj/item/weapon/spacecash/c1000(src)
Так и нормально? "Куча денег" же.
Я могу, кстати, сделать чтобы в рюкзак пихались деньги не по одной, а в пачке. Надо?

2022-03-11 08:13 UTC, LiLJard commented
А чего картинки спрайтов не показал

2022-03-11 08:28 UTC, DarthSidiousPalpatine commented
> А чего картинки спрайтов не показал

Кто хочет -  найдёт в дискорде, я их кидал уже 100500 раз.

2022-03-11 08:39 UTC, volas commented on tgui/packages/tgui/assets/bg-credit.svg
> +<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 137.95 162.94"><defs><style>.cls-1{fill:#fff;}</style></defs><title>bg-credit</title><g id="Слой_2" data-name="Слой 2"><g id="Слой_1-2" data-name=
сделай png иконку 32x32, её и вставляй где нужно. svg у нас в интерфейсах за редким исключением нигде не используется, и смысла мало, когда все иконки с игры всё равно растровые.

Хотя я всё равно против идеи. cr или $ - просто и понятно, юзер может набрать в чате.
Эта новая иконка денег - она, во первых, не имеет визуальной ассоциации с деньгами, её изображение никому ни о чем не говорит. Во вторых - не воспроизводится с клавиатуры. В третьих - на деньгах всё равно какой-то C нарисован, а не это.

2022-03-11 08:40 UTC, DarthSidiousPalpatine commented on tgui/packages/tgui/assets/bg-credit.svg
> +<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 137.95 162.94"><defs><style>.cls-1{fill:#fff;}</style></defs><title>bg-credit</title><g id="Слой_2" data-name="Слой 2"><g id="Слой_1-2" data-name=
На деньгах не нарисован С

2022-03-11 08:44 UTC, LudwigVonChesterfield commented
@volas Если замёржим #8810 смогу сделать чтобы макрос "*к" или "*кр" заменялся на эту смешную буковку :)

2022-03-11 08:45 UTC, volas commented on tgui/packages/tgui/assets/bg-credit.svg
> +<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 137.95 162.94"><defs><style>.cls-1{fill:#fff;}</style></defs><title>bg-credit</title><g id="Слой_2" data-name="Слой 2"><g id="Слой_1-2" data-name=
Если не прибежать и не присматриваться - на первый выглядит как C. Но да, там какие-то непонятные полоски, моя претензия про отсутствие понятной ассоциации и к новому спрайту денег тоже относится.

2022-03-11 08:51 UTC, DarthSidiousPalpatine commented on tgui/packages/tgui/assets/bg-credit.svg
> +<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 137.95 162.94"><defs><style>.cls-1{fill:#fff;}</style></defs><title>bg-credit</title><g id="Слой_2" data-name="Слой 2"><g id="Слой_1-2" data-name=
К, кредит. к.
Какая ещё ассоциация нужна.
Достаточно лишь запихнуть это повсюду вместо cr., на вики тоже. И будет норм.

2022-03-11 08:56 UTC, volas commented on tgui/packages/tgui/assets/bg-credit.svg
> +<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 137.95 162.94"><defs><style>.cls-1{fill:#fff;}</style></defs><title>bg-credit</title><g id="Слой_2" data-name="Слой 2"><g id="Слой_1-2" data-name=
Если я первый раз зашел в игру и вижу спрайт с $ на нем - я сразу пойму, что это деньги. Это пример хорошего использования ассоциирования.
А эту картинку с svg я бы обозвал логотипом каких-то тамплиеров технократов.

2022-03-11 09:05 UTC, AndroBetel commented
![Uploading qYB4b99SyXE.jpg…]()

2022-03-11 09:06 UTC, AndroBetel commented
![qYB4b99SyXE](https://user-images.githubusercontent.com/44546836/157836417-9e63c9d1-c09b-4776-84ca-a34516d27519.jpg)

2022-03-11 09:48 UTC, KIBORG04 commented on tgui/packages/tgui/assets/bg-credit.svg
> +<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 137.95 162.94"><defs><style>.cls-1{fill:#fff;}</style></defs><title>bg-credit</title><g id="Слой_2" data-name="Слой 2"><g id="Слой_1-2" data-name=
Как раз svg и нужен, чтобы использовать эту штуку и как логотип, и как символ

2022-03-11 13:20 UTC, WatlerJe commented
Когда уже батрончики разных калибров можно будет собирать в стаки?!

2022-03-12 11:04 UTC, DarthSidiousPalpatine commented
Сделал иконку кредита работающей везде кроме ПДА, с ПДА не разобрался, ПДА идёт нафиг, наверное.

2022-03-12 11:06 UTC, DarthSidiousPalpatine commented
Жду мерж

2022-03-12 11:39 UTC, DarthSidiousPalpatine commented
Спрайты обновлены

2022-03-16 14:42 UTC, DarthSidiousPalpatine commented
> добавь спрайты в шапку ПР-а люди не знают что лайкают/дизлайкают

А зачем им что-то лайкать и дизлайкать?

2022-03-16 20:58 UTC, LudwigVonChesterfield commented on code/game/machinery/vending.dm
> +	if(id_scanned)
сделай ранний возврат
```
/vend_card()
    if(!id_scanned)
        return
    твой код
```

2022-03-16 20:59 UTC, LudwigVonChesterfield commented on code/modules/economy/Accounts_DB.dm
> +						<u>Balance:</u> [detailed_account_view.money]<image class='credit'/><br>
@KIBORG04 шо думаешь кстати `#define SYMBOL_CREDIT <image class='credit'/>`

2022-03-16 21:00 UTC, LudwigVonChesterfield commented on code/modules/economy/cash.dm
> +	if(.)
сделай ранний возврат

2022-03-16 21:00 UTC, LudwigVonChesterfield commented on code/modules/economy/cash.dm
> +	. = ..(W, prevent_warning)
```suggestion
	. = ..()
```

2022-03-17 01:25 UTC, UsadoSmokk commented
Все ещё ждем актуальные спрайты в шапке

2022-03-18 11:32 UTC, DarthSidiousPalpatine commented
Я добавил скриншоты, WE DID IT!

2022-03-18 12:39 UTC, DarthSidiousPalpatine commented
Исправил исправления, доработал добавления. Впихнул крутые звуки деняк в разные вещи. И Велкро липучку.
Жду мерж.

2022-03-18 12:51 UTC, KIBORG04 commented on code/modules/economy/Accounts_DB.dm
> +						<u>Balance:</u> [detailed_account_view.money]<image class='credit'/><br>
Да, я думал гисев сам додумается..

2022-03-18 12:52 UTC, KIBORG04 commented
> sound: Добавлен звук свайпа карты, печати денег, вставки денег, велкро липучки (для кошелька).

Откуда звуки взял?

2022-03-18 12:53 UTC, LudwigVonChesterfield commented on code/modules/economy/Accounts_DB.dm
> +						<u>Balance:</u> [detailed_account_view.money]<image class='credit'/><br>
@DarthSidiousPalpatine сделай пожалуйста такой дефайн и проставь везде где уместно

2022-03-18 12:59 UTC, DarthSidiousPalpatine commented on code/modules/economy/Accounts_DB.dm
> +						<u>Balance:</u> [detailed_account_view.money]<image class='credit'/><br>
куда только его написать лучше.

2022-03-18 13:20 UTC, DarthSidiousPalpatine commented
Всё, теперь мерж :dovolen:

2022-03-18 13:21 UTC, volas commented
> FreeSound по Creative Common лицензии, всё обработал, порезал, изменил разными способами :dovolen:

а ссылку на авторов/источник?

2022-03-18 13:22 UTC, DarthSidiousPalpatine commented
> > FreeSound по Creative Common лицензии, всё обработал, порезал, изменил разными способами :dovolen:
> 
> а ссылку на авторов/источник?

А там, вроде, лицензия не требующая ссылки. Я перепроверю сейчас всё.

2022-03-18 13:23 UTC, volas commented
Всё равно прикрепляй, блок авторства в первом посте для этого и создан

2022-03-18 13:24 UTC, LiLJard commented
Спрайты все ещё плохие

2022-03-19 04:02 UTC, UsadoSmokk requested changes
Так, поговорили с удавом и пришли к итогу, что спрайты на данный момент нас не устраивают, чип слишком шумный, кошель закрашенный градиентом, сами деньги напоминают дирол мятный либо дешевые бумажные билетики из игровых автоматов(или фантики из монополии). Однако варианты есть, а именно деньги лижарда, они вполне себе хороши.

Также хочу спросить про номинал, а нужен ли он? Ибо цифры, скажем честно, смотрятся плохо при всех вариантах. 

И последнее, нужно сделать доп спрайты карточек в кошельке и прошу не надо верхним слоем ложить пленку, ну или хоть не такую тёмную, иначе карта выходит мутная и вообще непонятная. (см. кошелек с золотой картой)

2022-03-19 04:22 UTC, DarthSidiousPalpatine commented
Удачи, ПР закрывается.
Деньги Лижарда им, блять, нужны. Ну мержьте их сами. Задолбали.

2022-03-19 10:13 UTC, DarthSidiousPalpatine commented
![image](https://user-images.githubusercontent.com/21008918/159116994-ceed8855-79c6-43ca-8ee5-337016b14eb7.png)

2022-03-20 13:11 UTC, Sakuya-Izayoi commented
Иконка кредита на скриншоте не влазит в размер букв. Это какой-то символ юникода или картинка?

2022-03-22 00:56 UTC, LudwigVonChesterfield requested changes
Разбивай на отдельные ПР-ы:

1. Респрайт купюр + смешной символ в вендомат.
2. Фича с стаканием купюр + наличку в вендомат.
3. Респрайт монет.
4. Респрайт кошелька.

2022-05-13 12:17 UTC, DarthSidiousPalpatine commented
Восстановите пж

2022-05-13 13:05 UTC, DarthSidiousPalpatine commented
Такое грустное. Жаль нельзя просто взять и... Вмержить.

Нет, блин, надо разрезать всё на 6 ПРов... эхх....

2022-05-13 13:10 UTC, DarthSidiousPalpatine commented
А я и монетки допилил, наконец. И бесконтактную оплату допилил.

2022-06-07 19:48 UTC, closed without merging