vox balloons very funny
TauCetiStation/TauCetiClassic pull request #8823
Opened 2022-03-11 14:14 UTC by LudwigVonChesterfield

## Описание изменений

Воксы лопают от урона как космический скафандр.

В том плане что теряют возможность находиться в низком давлении.

10 урона на воксе = 0% герметизации.

Если скафандр потерял 50% герметизации и вокс 50% герметизации, то в результате 25% потеря герметизации.

## Почему и что этот ПР улучшит

Ролевой потенциал чешуйчатых воксов.

## Чеинжлог
:cl: Luduk
- balance: Воксы теряют возможность находиться при низком давлении в зависимости от урона по телу. 10 урона - 0-ой резист к давлению.

2022-03-11 14:14 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2022-03-11 15:59 UTC, Akellazp commented
хочу лопать воксов

2022-03-11 19:41 UTC, KIBORG04 commented on code/modules/mob/living/carbon/human/life.dm
> +		pressure_adjustment_coefficient *= skin_pressure_coefficient
Требуется ООП. А еще я хз, нужно ли эта фича армалисам, они же вроде типа жёские там крутые

2022-03-11 19:56 UTC, LudwigVonChesterfield commented on code/modules/mob/living/carbon/human/life.dm
> +		pressure_adjustment_coefficient *= skin_pressure_coefficient
как предложишь сделать? у расы /get_pressure_protection() прок?

2022-03-11 19:57 UTC, KIBORG04 commented on code/modules/mob/living/carbon/human/life.dm
> +		pressure_adjustment_coefficient *= skin_pressure_coefficient
Ты ж в прошлом ПРе такое же делал. и да, возвращать какой-то коэфф.

2022-03-11 20:41 UTC, wasder451 commented
Я все ещё не могу понять логики данной фишки. Как при получении двух синяков(2 панча) на (допустим) правую руку, вся кожа вокса что до этого прекрасно выдерживала вакуум вдруг теряет это свойство по всей поверхности тела?

2022-03-12 10:16 UTC, LudwigVonChesterfield commented on code/modules/mob/living/carbon/human/life.dm
> +		pressure_adjustment_coefficient *= skin_pressure_coefficient
Армалисы учитываются потому-что у них 80% броня так что им надо де факто получить 50 урона чтобы порваться как вокс!

2022-03-13 11:49 UTC, wasder451 commented
к слову о типах урона, окси и токс дамаг считаются ?

2022-03-13 11:51 UTC, LudwigVonChesterfield commented
только брут и бёрн

2022-03-13 15:24 UTC, GermanSUS commented
![Voxgun-1](https://user-images.githubusercontent.com/59874480/158066825-ee4e20fe-8515-4cba-96ae-9ec0c6f14aea.PNG)
Удали свои балансы
Они не логичны и не нравятся никому кто эти балансы получают

2022-03-13 17:45 UTC, Sakuya-Izayoi requested changes
> Ролевой потенциал чешуйчатых воксов.

Недостаточная аргументация.

2022-03-13 20:12 UTC, wasder451 commented
После долгого ковыряния гвоздиком в ране был найден компромисс, который устроил обе стороны и в вопросах баланса, и логики, и лора.
1. Кап урона пока что выставлен на 25,
2. Для наложения эффекта будет учитываться только сумма урона на голове, груди и паху.
Что это улучшит. Как и написано выше - ролевой потенциал чешуи и заставит воксов, как им и положено стараться чаще избегать прямой конфронтации, особенно в плохих погодных условиях. Любители "риалистичного" подхода, такие как я, возможно оценят байку о том, что повреждать 25 процентов кожного покрова там, где у тебя находятся полости тела (брюшная, грудная, черепная) может плохо сказаться на том, что ты до этого спокойно переносил вакуум.

2022-03-15 11:02 UTC, merged