Ремап кабинета АВД
TauCetiStation/TauCetiClassic pull request #8847
Opened 2022-03-14 16:24 UTC by Tap0r

## Описание изменений
Кабинет частично перестал быть квадратным.
Стал куда уютнее.
Увеличился гардероб АВД.
![1](https://user-images.githubusercontent.com/88531962/158210596-fe168744-a758-4994-99ca-2e63ead6ef88.png)
![2](https://user-images.githubusercontent.com/88531962/158210601-97e1d62b-4cd1-4e40-8129-d6b70899955f.png)
![3](https://user-images.githubusercontent.com/88531962/158210606-626ffbf7-61ca-45ab-aa11-32be440f7558.png)

## Почему и что этот ПР улучшит
Кабинет АВД стал круче и уютнее.
## Авторство
я
## Чеинжлог
:cl:
 - map: Кабинет АВД стал уютнее и круче.

2022-03-14 16:24 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2022-03-14 17:52 UTC, LudwigVonChesterfield requested changes
за ремап, против накидывания хлама.

кубинку если мне память не изменяет выдают буквально только капитану, зажигалки, сигареты пускай покупают в вендоматах.

кучу одежды которую никто респрайтить не будет тоже пожалуйста убери.
(в том числе синий берет парамедиков, почему он у АВД?)

2022-03-14 18:21 UTC, Tap0r commented
Это не парамедов берет. Это берет нанотрасенов

2022-03-14 18:22 UTC, Tap0r commented
Почему уполномоченные лица ЦК не могут иметь одну сигару в кабинете? АВД слишком занижен, он должен быть реально солидным дядькой.

2022-03-14 18:23 UTC, Tap0r commented
Я всю одежду сидел и осматривал в игре, её не нужно респрайтить, она смотрибельная.

2022-03-14 18:57 UTC, LudwigVonChesterfield commented on maps/boxstation/boxstation.dmm
> +	layer = 4.1;
а зачем лампе особый леер

2022-03-14 18:57 UTC, LudwigVonChesterfield commented on maps/boxstation/boxstation.dmm
> +	pixel_y = 3
это обязательно необходимо?

2022-03-14 19:27 UTC, LudwigVonChesterfield commented on maps/boxstation/boxstation.dmm
> +/obj/structure/closet/lawcloset,
можно было бы сделать /obj/structure/closet/lawscloset/iaa и вынести эти шмотки в спавн туда? чтобы и на Гамме и на Фалконе и тут одежда одинаковая была (когда кто-то там тоже шкаф правильный поставит)

2022-03-16 12:05 UTC, LudwigVonChesterfield approved these changes
это не аппрув просто после реквест ченджес нейтральное состояние вернуть нельзя.

Вопиющие проблемы исправлены, но в целом я пока не уверен. Всё ещё выдаётся куча халявы (сигары, сигареты, ЦК костюм!!!)

ещё лично я считаю зашкваром крутить плейны на карте отдельным предметам, со мной вроде бы согласен @Lexakr

2022-03-16 12:08 UTC, KIBORG04 reviewed
Вопиющие проблемы исправлены, но в целом я пока не уверен. Всё ещё выдаётся куча халявы (сигары, сигареты, ЦК костюм!!!)

2022-03-27 09:04 UTC, Tap0r commented
Всё, можно мержить!!!!!:exclamation::exclamation::exclamation:

2022-03-30 22:16 UTC, LudwigVonChesterfield requested changes
![image](https://user-images.githubusercontent.com/17705613/160940190-af64dee5-5518-4512-8f41-21f320ef70bf.png)

2022-04-09 02:53 UTC, volas commented
конфликты

2022-04-15 15:16 UTC, Tap0r commented
всё, морж?

2022-04-26 06:45 UTC, Lexakr approved these changes
Аппрувед

2022-04-26 09:02 UTC, merged