You spin me right round, baby, right round!
TauCetiStation/TauCetiClassic pull request #8857
Opened 2022-03-17 17:33 UTC by DarthSidiousPalpatine

## Описание изменений
Синга теперь не крутой спрайт, а чёрный кружок и огромный эффект.
Вот рост синги:
https://youtu.be/La7ZAlRKwwo

## Почему и что этот ПР улучшит
КрАсИвО, Приколдесно, сингу видно за километр, особенно если жрёт станцию.

## Авторство
Darth_Sidious и все все все кто помогал в дискорде

## Чеинжлог
 :cl:
 - image: крутой спрайт синги заменён на чёрный кружок с огромным эффектом.

2022-03-17 17:33 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2022-03-17 17:42 UTC, kiVts commented
не вижу ничего красивого.............
просто эффект  сделай больше может

2022-03-17 17:46 UTC, KIBORG04 commented on code/_onclick/hud/rendering/plane_master.dm
> +/atom/movable/screen/plane_master/singularity_0
Ты убил щас старый эффект у гравитационной аномалии. Верни /atom/movable/screen/plane_master/gravpulse плейн и создавать для синги новые, а не заменяй

2022-03-17 17:47 UTC, KIBORG04 commented on code/_onclick/hud/rendering/render_plate.dm
> +	add_filter("singulo_0", 1, displacement_map_filter(render_source = GRAVITY_RENDER_TARGET_0, size = -40))
Раскидай раскидай по своим прокам каждый из этих приколов

2022-03-17 17:48 UTC, DarthSidiousPalpatine commented on code/_onclick/hud/rendering/render_plate.dm
> +	add_filter("singulo_0", 1, displacement_map_filter(render_source = GRAVITY_RENDER_TARGET_0, size = -40))
Каким прокам.

2022-03-17 17:49 UTC, KIBORG04 commented on code/modules/power/singularity/singularity.dm
> +	//appearance_flags = PIXEL_SCALE
нах закомментил? Это нужно для виденья эффекта синги сквозь стены.

2022-03-17 17:49 UTC, KIBORG04 commented on code/modules/power/singularity/singularity.dm
> +	glide_size = 1
1 это вроде как вообще ничего не изменит.

2022-03-17 17:51 UTC, DarthSidiousPalpatine commented on code/_onclick/hud/rendering/render_plate.dm
> +	add_filter("singulo_0", 1, displacement_map_filter(render_source = GRAVITY_RENDER_TARGET_0, size = -40))
Ладно.

2022-03-17 17:53 UTC, DarthSidiousPalpatine commented on code/modules/power/singularity/singularity.dm
> +	glide_size = 1
Изменило. Но ладно, пусть будет 2

2022-03-17 17:54 UTC, KIBORG04 commented on code/modules/power/singularity/singularity.dm
> +	//appearance_flags = PIXEL_SCALE
Если тебе так мешает какой-то из эффектов скейлинга, то `appearance_flags = null` сделай

2022-03-17 17:55 UTC, DarthSidiousPalpatine commented on code/modules/power/singularity/singularity.dm
> +			consume_range = 1
Для крутого эффекта

2022-03-17 17:57 UTC, DarthSidiousPalpatine commented on code/modules/power/singularity/singularity.dm
> +		singulo_lens.plane = GRAVITY_PULSE_PLANE_0
> ![image](https://user-images.githubusercontent.com/26389417/158865705-c14632a9-e7d6-45ea-a6d8-bb8ab45dcfaa.png)
> 
> старые спрайты удалить

А нам они не понадобятся?

2022-03-17 17:57 UTC, DarthSidiousPalpatine commented
На будущее. Вдруг кто-то сделает другое двигло :dovolen:

2022-03-17 20:10 UTC, DarthSidiousPalpatine commented on code/modules/power/singularity/singularity.dm
> +	glide_size = 1
0.5 поставил. Стало идеально

2022-03-17 20:35 UTC, DarthSidiousPalpatine commented
У аномалии поменял эффект тоже.

2022-03-17 20:36 UTC, DarthSidiousPalpatine commented
Ждумерж

2022-03-17 20:38 UTC, KIBORG04 commented on code/modules/power/singularity/singularity.dm
> +			animate(singulo_lens, transform = matrix().Scale(1.16), time = 25)
А ты уверен что анимация будет корректно работать и при увеличении стадии, и при её уменьшение? А еще не пихай логику анимаций в `update_icon()` прок.

2022-03-17 20:39 UTC, DarthSidiousPalpatine commented on code/modules/power/singularity/singularity.dm
> +			animate(singulo_lens, transform = matrix().Scale(1.16), time = 25)
Да, она просто афигенно работает. Я проверил всё. Это смотрится афигенно.

2022-03-17 20:40 UTC, DarthSidiousPalpatine commented on code/modules/power/singularity/singularity.dm
> +			animate(singulo_lens, transform = matrix().Scale(1.16), time = 25)
Она медленно увеличивается в размерах до нужных. Смотрится афигенно. Ещё глайдсайз настроил так, что когда она приходит на нужное место она сразу же улетает снова, т.е. она движется теперь абсолютно без рывков, плавно.

2022-03-17 20:40 UTC, KIBORG04 commented on code/__DEFINES/_planes+layers.dm
> +#define ANOMALY_RENDER_TARGET "*ANOM_RENDER_TARGET"
Напиши название более конкретно. ANOMALY вообще ни о чем не говорит. Тоже наверное и про GRAVITY_PULSE, это же уже про сингу, а не какие-то пульсации

2022-03-17 20:42 UTC, DarthSidiousPalpatine commented on code/__DEFINES/_planes+layers.dm
> +#define ANOMALY_RENDER_TARGET "*ANOM_RENDER_TARGET"
Аномалия. Все аномалии.

2022-03-17 20:42 UTC, KIBORG04 commented on code/_onclick/hud/rendering/render_plate.dm
> +	add_filter("singulo_3", 4, displacement_map_filter(render_source = GRAVITY_RENDER_TARGET_3, size = 700))
Я боюсь, что компик инженеров может умереть от такого. На ТМе посмотрим?

2022-03-17 20:43 UTC, DarthSidiousPalpatine commented on code/_onclick/hud/rendering/render_plate.dm
> +	add_filter("singulo_3", 4, displacement_map_filter(render_source = GRAVITY_RENDER_TARGET_3, size = 700))
да, посмотрим. ща только залью исправление названий.

2022-03-17 20:45 UTC, DarthSidiousPalpatine commented on code/_onclick/hud/rendering/render_plate.dm
> +	add_filter("singulo_3", 4, displacement_map_filter(render_source = GRAVITY_RENDER_TARGET_3, size = 700))
Всё, готово.

2022-03-17 20:47 UTC, KIBORG04 commented on code/_onclick/hud/rendering/render_plate.dm
> +	add_filter("singulo_3", 4, displacement_map_filter(render_source = GRAVITY_RENDER_TARGET_3, size = 700))
Ты можешь сам сделать замеры профайлером. С твоими эффектами и без за одинаковый промежуток времени. 
ПКМ по панели сверху. Дальше понятно.
![image](https://user-images.githubusercontent.com/26389417/158892316-b8a1fc02-ddab-4038-9a58-8d4ea4b3926a.png)

2022-03-17 20:48 UTC, DarthSidiousPalpatine commented on code/_onclick/hud/rendering/render_plate.dm
> +	add_filter("singulo_3", 4, displacement_map_filter(render_source = GRAVITY_RENDER_TARGET_3, size = 700))
какая-то сложная фигня, давай тм и люди крикнут потом лагает или нет :dovolen:

2022-03-17 20:49 UTC, KIBORG04 commented on code/game/objects/effects/anomalies.dm
>  	START_PROCESSING(SSobj, src)
Почему нельзя у синги так же накидать фильтров в атом ините, как и тут?

2022-03-17 20:50 UTC, DarthSidiousPalpatine commented on code/game/objects/effects/anomalies.dm
>  	START_PROCESSING(SSobj, src)
Потому что это фильтры что накладываются на маску, а у синги эффекты улетают вне маски и вообще.

2022-03-17 20:51 UTC, DarthSidiousPalpatine commented on code/game/objects/effects/anomalies.dm
>  	START_PROCESSING(SSobj, src)
Мне нужно твикать дисплейсмент, а не простой рипл или леер или ещё что. кастомный дисплейсмент твикать я могу только там где он накладывается - на плейн

2022-03-17 20:52 UTC, KIBORG04 commented on code/game/objects/effects/anomalies.dm
>  	START_PROCESSING(SSobj, src)
Мне сложно придумать че-то умное. Может ты сделал везде правильно, а может и нет. Мне кажется нет, но ничего в аргументы написать не могу.

2022-03-17 20:52 UTC, DarthSidiousPalpatine commented on code/game/objects/effects/anomalies.dm
>  	START_PROCESSING(SSobj, src)
Я сделал везде правильно и оно везде работает. :dovolen:
Учение Гисева всесильно потому что оно верно!

2022-03-17 23:19 UTC, LudwigVonChesterfield commented on code/_onclick/hud/rendering/plane_master.dm
> +	name = "singularity_3 plane"
это типо singularity stage 3 plane?

2022-03-20 14:08 UTC, KIBORG04 commented on code/modules/power/singularity/singularity.dm
> +	plane = SINGULARITY_EFFECT_PLANE_0
Из каждого убери копипасту плейна

2022-03-20 14:11 UTC, KIBORG04 commented on code/modules/power/singularity/singularity.dm
> +	plane = SINGULARITY_EFFECT_PLANE_0
У тебя повторяется два раза plane = SINGULARITY_EFFECT_PLANE_0

2022-03-20 14:12 UTC, DarthSidiousPalpatine commented on code/modules/power/singularity/singularity.dm
> +	plane = SINGULARITY_EFFECT_PLANE_0
А, не заметил, пардон

2022-03-20 14:13 UTC, KIBORG04 commented on code/_onclick/hud/rendering/render_plate.dm
> +	add_filter("singulo_3", 4, displacement_map_filter(render_source = SINGA_RENDER_TARGET_3, size = 700))
Теперь сделай нормальное название для фильтров

2022-03-20 14:14 UTC, KIBORG04 commented on code/_onclick/hud/rendering/render_plate.dm
> +	add_filter("singulo_3", 4, displacement_map_filter(render_source = SINGA_RENDER_TARGET_3, size = 700))
Оно вроде как может иметь вполне нормальное название

2022-03-20 14:14 UTC, DarthSidiousPalpatine commented on code/_onclick/hud/rendering/render_plate.dm
> +	add_filter("singulo_3", 4, displacement_map_filter(render_source = SINGA_RENDER_TARGET_3, size = 700))
Какое, например?

2022-03-20 14:19 UTC, KIBORG04 commented on code/_onclick/hud/rendering/render_plate.dm
> +	add_filter("singulo_3", 4, displacement_map_filter(render_source = SINGA_RENDER_TARGET_3, size = 700))
Че-то типо синга_сайз_75 синга_сайз_400. Я кстати не понимаю почему вообще меняется сайз. Как он может быть отрицательным?

2022-03-20 14:20 UTC, KIBORG04 commented on code/modules/power/singularity/singularity.dm
>  /obj/singularity
Сделай этой синге mouse_opacity = MOUSE_OPACITY_TRANSPARENT

2022-03-20 14:24 UTC, DarthSidiousPalpatine commented on code/modules/power/singularity/singularity.dm
>  /obj/singularity
Не понял. Зачем синге маус опасити транспарент

2022-03-20 14:26 UTC, KIBORG04 commented on code/modules/power/singularity/singularity.dm
>  /obj/singularity
Ты ПКМмил свою сингу? (там спрайт голой таяры)

2022-03-20 14:27 UTC, DarthSidiousPalpatine commented on code/_onclick/hud/rendering/render_plate.dm
> +	add_filter("singulo_3", 4, displacement_map_filter(render_source = SINGA_RENDER_TARGET_3, size = 700))
Это не сайз. Блин. Ну никак не обзовёшь иначе.

2022-03-20 14:27 UTC, DarthSidiousPalpatine commented on code/modules/power/singularity/singularity.dm
>  /obj/singularity
а, пкм легко убрать маус опасити транспарентом?

2022-03-20 14:29 UTC, KIBORG04 commented on code/modules/power/singularity/singularity.dm
>  /obj/singularity
da

2022-03-20 14:32 UTC, LudwigVonChesterfield commented
что будет с сингулярными мобами? у них сейчас оверлей спрайт синги

2022-03-20 14:34 UTC, DarthSidiousPalpatine commented
> что будет с сингулярными мобами? у них сейчас оверлей спрайт синги

Ничего. Делаю им свой эффект.

2022-03-20 15:09 UTC, UDaV73rus commented
На фоне проминание пола возможно сделать анимацию с не линейной скоростью? Типо применить easing, чтобы выглядело менее однообразной

2022-03-20 17:34 UTC, KIBORG04 commented on code/modules/roguelike/mob_modifiers/positive.dm
> +	if(!warp)
Ифка не нужна же, апплай один раз должен срабатывать вроде как

2022-03-20 17:34 UTC, KIBORG04 commented on code/modules/roguelike/mob_modifiers/positive.dm
>  	// singularity_filter = filter(type = "layer", render_source = I)
Убери эти комментарии

2022-03-20 17:35 UTC, KIBORG04 commented on code/modules/roguelike/mob_modifiers/positive.dm
> +	H.plane = SINGULARITY_PLANE
Моба будет видно сквозь темноту, он типа на ней будет стоять

2022-03-20 17:35 UTC, KIBORG04 commented on code/modules/roguelike/mob_modifiers/positive.dm
> +		H.plane = GAME_PLANE
```suggestion
		H.plane = initial(H.plane)
```

2022-03-20 17:35 UTC, DarthSidiousPalpatine commented on code/modules/roguelike/mob_modifiers/positive.dm
> +	H.plane = SINGULARITY_PLANE
Хорошо или плохо?

2022-03-20 17:36 UTC, KIBORG04 commented on code/modules/roguelike/mob_modifiers/positive.dm
> +	H.plane = SINGULARITY_PLANE
Конечно плохо

2022-03-20 17:54 UTC, KIBORG04 commented on code/modules/roguelike/mob_modifiers/positive.dm
> +	H.plane = GAME_PLANE + 1
Так не пиши. Придумай новый дефайн и помести его в _planes+layers.dm

2022-03-21 15:30 UTC, KIBORG04 commented on code/__DEFINES/_planes+layers.dm
> +#define SINGA_RENDER_TARGET_3 "*SINGAEFFECT_RENDER_TARGET_3"
Если тебе нужно сокращение от слово СИНГУЛЯРОНОСТЬ, то стоит использовать не русское сокращение СИНГА, а пендосское SINGULO или че-то подобное.

2022-03-21 15:31 UTC, KIBORG04 commented on code/__DEFINES/_planes+layers.dm
> +#define SINGULAR_MOB_PLANE -4
Ты видимо не понял. Здесь стоит использовать более универсальные названия.

2022-03-21 15:33 UTC, KIBORG04 commented on code/_onclick/hud/rendering/render_plate.dm
> +
```suggestion
```

2022-03-21 15:40 UTC, KIBORG04 commented on code/__DEFINES/_planes+layers.dm
> +#define SINGULAR_MOB_PLANE GAME_PLANE + 1
Если ты не хочешь делать так, как я предлагаю, то может хотя бы напишешь почему?

2022-03-21 15:41 UTC, DarthSidiousPalpatine commented on code/__DEFINES/_planes+layers.dm
> +#define SINGULAR_MOB_PLANE GAME_PLANE + 1
А я не понял как ты хочешь.

2022-03-21 15:42 UTC, KIBORG04 commented on code/__DEFINES/_planes+layers.dm
> +#define SINGULAR_MOB_PLANE GAME_PLANE + 1
Универсальный плейн для всего, что должно быть выше всякого игрового, но не очень.
`#define ABOVE_GAME_PLANE -1`

2022-03-21 17:12 UTC, KIBORG04 commented on code/__DEFINES/_planes+layers.dm
> +#define ABOVE_GAME_PLANE GAME_PLANE+1
```suggestion
#define ABOVE_GAME_PLANE -1 или -3 или -2 но не епты GAME_PLANE+1
```

2022-03-23 20:00 UTC, KIBORG04 commented on code/__DEFINES/_planes+layers.dm
> +#define ABOVE_GAME_PLANE -3
```suggestion
#define ABOVE_GAME_PLANE -1
```
Для совместимости с моим скорым ПРом

2022-03-23 20:02 UTC, KIBORG04 requested changes
Я тебе ставлю ультиматум.
Для ТМа и последующего мержа ты должен разбить ПРы с деньгами на более маленькие ПРы.
Если ты это не сделаешь до мержа https://github.com/TauCetiStation/TauCetiClassic/pull/8934, то будет вынужден фиксить много-много конфликтов.

2022-03-23 20:05 UTC, DarthSidiousPalpatine commented
> Я тебе ставлю ультиматум. Для ТМа и последующего мержа ты должен разбить ПРы с деньгами на более маленькие ПРы. Если ты это не сделаешь до мержа #8934, то будет вынужден фиксить много-много конфликтов.

Эээ, ну и ладно?

2022-03-26 23:09 UTC, KIBORG04 commented
Как насчёт того, чтобы у эффекта линзы убрать такой острый конец у спрайта, добавим что ли уменьшение альфы, или может поубирать пикселей. Или может впринципе самому спрайту понизить альфу, хз.

А еще ты не сделал прозрачной для мышки сингу

![image](https://user-images.githubusercontent.com/26389417/160259977-dcf1fe63-7aba-4a55-a9c2-631a4a923fcd.png)

2022-03-27 16:42 UTC, KIBORG04 commented on code/modules/power/singularity/singularity.dm
> +	var/atom/movable/singularity_lens/singulo_lens
Во время ТМа была сломана тесла, которая имела похожие эффекты.

2022-09-10 21:27 UTC, DarthSidiousPalpatine commented
FBI OPENUP
Тесла пофикшена

2022-09-10 21:53 UTC, DarthSidiousPalpatine commented
Ура работает без конфликтов мерж

2022-09-14 09:50 UTC, DarthSidiousPalpatine commented
@KIBORG04 А твой ультиматум ещё действует? Надуюсь, что нет.

2022-09-14 20:10 UTC, DarthSidiousPalpatine commented
Да чёрт побери, какие конфликты опять?

2022-09-14 20:12 UTC, DarthSidiousPalpatine commented
А, стой, это же от моего ПРа с фотиками. Зря быканул

2022-09-24 12:44 UTC, KIBORG04 commented on code/game/objects/items/toys.dm
> -	var/on = FALSE
куда?

2022-09-24 12:47 UTC, KIBORG04 reviewed
По коду всё вроде ок, но при моем тесте там были какие-то жуткие визуальный баги, незнаю сейчас, что по ним, но лучше это ТМить и смотреть в игре. У меня этим заниматься нет времени, поэтому смотрите сами.

2022-10-02 17:21 UTC, DarthSidiousPalpatine commented
Потом терпим терпим

2022-10-09 12:00 UTC, DarthSidiousPalpatine commented
Держу на плаву ПР.

2022-10-22 08:36 UTC, DarthSidiousPalpatine commented
Атлант расправил плечи

2022-11-01 10:35 UTC, pro100kotah commented
Автор проделал хорошую работу, младец, но старая синга была оч красивая... Жалко...

2022-11-01 10:40 UTC, DarthSidiousPalpatine commented
> Автор проделал хорошую работу, младец, но старая синга была оч красивая... Жалко... Добавлю то, что из-за искривления пространства не видно лучи поля сдерживания и из-за этого вызывает конфузные ситуации, когда СЕ кричит о побеге синги, потому что спрайты поля скрутило в сингу. Поле то есть, но его не видно.

Да вроде не сталкивался ещё с таким. Обычно синга держится на 2-3 стадии и скачет между ними и всё видно вокруг.

2022-11-07 10:09 UTC, DarthSidiousPalpatine commented
Обновить бы ТМ

2022-11-07 10:59 UTC, Chip11-n commented
Синга красивая, но есть странность, что когда она становится большой, её визуальное смещение становится слишком большим. То-есть, видишь ты её на одном месте, а по факту она на три тайла вправо. Особенно незаметно, но ощутимо, когда пытаешься её уничтожить при побеге. Хотя фиг знает, можно причислить к скилл ишуй. В общем, нормально уничтожать её выходит только будучи справа

2022-11-14 19:34 UTC, DarthSidiousPalpatine commented
Я ничего не буду делать тут, если мержабельно - мержте, если нет - закроете ПР.

2022-11-18 18:59 UTC, KIBORG04 commented
https://github.com/TauCetiStation/TauCetiClassic/issues/10375

2022-12-01 18:53 UTC, LudwigVonChesterfield approved these changes
красивый ПР

2022-12-11 12:44 UTC, volas commented
https://github.com/TauCetiStation/TauCetiClassic/issues/10375 починили?

2022-12-11 12:45 UTC, DarthSidiousPalpatine commented
> #10375 починили?

Да

2022-12-11 12:55 UTC, volas commented
Против вроде никто не высказывался, так что мержу

2022-12-11 12:55 UTC, merged