Вещички для воксов-нюкеров
TauCetiStation/TauCetiClassic pull request #8915
Opened 2022-03-21 20:08 UTC by simb11

## Описание изменений
У воксов-нюкеров появился автоиньектор с антитоксином, запасной баллон и мини-аптечка с едой.
## Почему и что этот ПР улучшит
resolve #8913 
## Авторство

## Чеинжлог

2022-03-21 20:08 UTC, TauKitty commented
###### Changelog status: :radio_button: No changelog

2022-03-22 17:22 UTC, KIBORG04 commented on code/datums/outfits/nuclear.dm
> +    r_pocket = /obj/item/weapon/storage/firstaid/small_firstaid_kit/nutriment
Замени 4 пробела на 1 таб

2022-03-22 17:23 UTC, KIBORG04 commented on code/datums/outfits/nuclear.dm
> +    l_hand = /obj/item/weapon/tank/nitrogen
```suggestion
```
В кармане же спавнится

2022-03-24 13:42 UTC, KIBORG04 commented
@LudwigVonChesterfield @Akellazp че вам не нравится, классный же ПР.

2022-03-29 17:47 UTC, LudwigVonChesterfield requested changes
если воксы-нюкеры якобы страдают

пускай не берут воксов.

Берёшь безногого
а
Ставишь преф на нюку
а
ВЫЫЫЫЫЫЫ КОДЕРЫ ШПАСИТЕ.

С воксами так же. (Я правда не верю в байки что они без этой аптечки жить не могут, звучит как нытьё на фоне нёрфа)

2022-03-29 18:48 UTC, closed without merging