Кейсы Тау Го
TauCetiStation/TauCetiClassic pull request #8966
Opened 2022-03-26 13:44 UTC by DarthSidiousPalpatine

## Описание изменений
Респрайтнул кейсы. Добавил 3 новых кейса.

## Почему и что этот ПР улучшит
Красивые кейсы. Больше кейсов. Удобство

![image](https://user-images.githubusercontent.com/21008918/160242220-1b91dd1e-18d0-4e63-a1c2-ea54e828efe1.png)

## Авторство
Darth_Sidious

## Чеинжлог
 :cl:
 - rscadd: добавил кейс вирусолога, медицинский кейс и инженерный кейс для хранения листов ресурсов.
 - image: респрайтнул старые кейсы.

2022-03-26 13:44 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2022-03-26 13:48 UTC, Tap0r commented
Ясно, перехватил спрайты и даже в авторстве не указал :cry:

2022-03-26 13:57 UTC, DarthSidiousPalpatine commented
блять что произошло, какие-то ветки те или не те куда-то замержились и теперь писец

2022-03-26 13:57 UTC, Tap0r commented
Дизинфа, кейсов новых 4 выходит

2022-03-26 14:18 UTC, UDaV73rus commented
Эти забираем, остальное не над :pepe:
![image](https://user-images.githubusercontent.com/33157992/160243590-504eaf12-a075-4df2-9c84-ea4b95015697.png)

2022-03-26 14:25 UTC, DarthSidiousPalpatine commented
> Эти забираем, остальное не над :pepe: ![image](https://user-images.githubusercontent.com/33157992/160243590-504eaf12-a075-4df2-9c84-ea4b95015697.png)

Всё над. Так что мерж

2022-03-26 19:19 UTC, LiLJard commented
Все отстой

2022-03-30 18:27 UTC, UDaV73rus requested changes
![image](https://user-images.githubusercontent.com/33157992/160905548-65546a84-5d36-4ac2-b33d-eeaf8cc41ca1.png)

2022-03-30 18:29 UTC, DarthSidiousPalpatine commented
> ![image](https://user-images.githubusercontent.com/33157992/160905548-65546a84-5d36-4ac2-b33d-eeaf8cc41ca1.png)

Лол нет. Нужны остальные кейсы или просто их спрайты поменяю

2022-03-30 18:31 UTC, UDaV73rus commented
ладно меняй

2022-04-13 18:58 UTC, DarthSidiousPalpatine commented
блен подождите

2022-05-08 09:03 UTC, closed without merging