Surgery для кровавых месив и кучек пыли
TauCetiStation/TauCetiClassic pull request #8977
Opened 2022-03-27 21:21 UTC by Zickusable

## Описание изменений
Слелал операцию для лечения овердамажнутых кукол за счет брут/берн китов. Чтоб из-за 12 лишних урона не отправлять тело на клонирование.
В основном, это для гройна, торса и головы, т.к. руки и ноги обычно отпиливаются.
Время и лечение можно подкрутить.
Убрал повторение у оинтмента, он все равно не повторяется, но сообщение о том, что уже перевязано, возникает.
## Почему и что этот ПР улучшит
Больше хирургии и меньше клонирования
## Авторство

## Чеинжлог
:cl:
- rscadd: новая операция для лечения урона у слишком сгоревших/избитых кукол

2022-03-27 21:21 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2022-03-27 21:24 UTC, LudwigVonChesterfield commented on code/game/objects/items/stacks/medical.dm
> +	repeating = FALSE
а ты точно хочешь чтобы на каждую ранку надо было заново кликать а не просто клик - залечены все ранки?

2022-03-27 21:32 UTC, Zickusable commented on code/game/objects/items/stacks/medical.dm
> +	repeating = FALSE
У ожоговых срабатывает только один раз и при повторных кликах пишет, что уже наложена мазь, в отличие от бинтов. С бинтами все как и должно

2022-03-28 11:01 UTC, Shootnik01 commented
Расе псиоников - быть?

2022-03-28 11:02 UTC, Shootnik01 commented
Упс, не туда

2022-03-29 09:41 UTC, LudwigVonChesterfield commented on code/modules/surgery/implant.dm
> +			return 0
```suggestion
			return FALSE
```

2022-03-29 09:42 UTC, LudwigVonChesterfield commented on code/modules/surgery/tissue.dm
> +		user.visible_message("<span class='notice'>[user] начинает укладывать регенеративную мембрану к поврежденным тканям [BP.name] [target].</span>", \
Troy Orgail начинает укладывает регенеративную мембрану к поврежденным тканям left arm Brey Orwald

2022-03-29 09:42 UTC, LudwigVonChesterfield commented on code/modules/surgery/tissue.dm
> +	target.custom_pain("[BP.name] ужасно болит!",1)
left arm ужасно болит!

2022-03-29 09:42 UTC, LudwigVonChesterfield commented on code/modules/surgery/tissue.dm
> +	tool.amount -= 1
может .use(1)?

2022-04-01 15:28 UTC, Zickusable commented
Как вам такие падежи?

2022-04-01 21:04 UTC, KIBORG04 commented on code/game/objects/objs.dm
> +	var/name_6		//prepositional
Не нада дядя. Удали лучше весь свой перевод, а не вот эту страшилку

2022-04-01 21:05 UTC, KIBORG04 commented on code/modules/surgery/tissue.dm
> +/datum/surgery_step/add_tissue
распиши в шапке ПРа все свои операции, че делают зачем, почему, как выполнять и где. Типо для вики

2022-04-02 06:11 UTC, Zickusable commented on code/game/objects/objs.dm
> +	var/name_6		//prepositional
Может хотя бы дефайнами в файлике операции? Такими темпами никогда ничего не сделаем. Да и почему страшилку?

2022-04-03 12:17 UTC, LudwigVonChesterfield commented on code/game/objects/objs.dm
> +	var/name_1		//nominative
Если ты делаешь нам систему для перевода объектов - спасибо,

но пожалуйста делай её отдельным ПР-ом где мы сможем обсуждать её, а не новые операции хирургу.

сейчас ты мешаешь спорное с очевидно хорошими изменениями, из-за первое будет мешать мержу второго. просто оставь пока на английском эти операции, а как дойдем и до них - переведём.

2022-04-04 09:37 UTC, Zickusable commented
Вот вам инглиш

2022-04-04 09:40 UTC, LudwigVonChesterfield commented on code/modules/surgery/tissue.dm
> +/datum/surgery_step/add_tissue
можно сделать чтобы пересадка кожи лечила серых HUSK-ов после сильных ожогов или генки?

2022-04-04 09:40 UTC, LudwigVonChesterfield commented on code/modules/surgery/tissue.dm
> +/datum/surgery_step/add_tissue
я бы наверное предложил если нет повреждений и цель == грудь то лечится HUSK

2022-04-04 10:16 UTC, Zickusable commented on code/modules/surgery/tissue.dm
> +/datum/surgery_step/add_tissue
Ну это не совсем пересадка кожи, скорее всего что под кожей. Да и странно было бы сожженую голову починить и при том все тело тоже оздоровилось (как и то, что всё тело сереет при сжигании только головы). Хаск лечится передозом дермалина, если кому вдруг хочется здоровый цвет кожи.

2022-04-20 10:21 UTC, LudwigVonChesterfield commented on code/modules/surgery/tissue.dm
> +	if(BP.trauma_kit)
это точно хорошо что действие при хирургии определяет операция а не предмет?

2022-04-20 10:22 UTC, LudwigVonChesterfield approved these changes
ну вроде бы норм, конечно актуальность изменения сомнительна если учесть что теперь можно накачивать мертвецов бикаридином...

но иметь опции при нашем меде тоже хорошо

2022-04-20 10:43 UTC, Sakuya-Izayoi commented on code/modules/surgery/tissue.dm
> +	if(BP.trauma_kit)
trauma_kit это то что на предыдущем этапе, то есть это некоторый трейт такой себе. в прочем, это тоже не очень правильно сделано.

2022-04-20 13:44 UTC, LudwigVonChesterfield commented on code/modules/surgery/tissue.dm
> +	if(BP.trauma_kit)
а то что потом определяется какой функционал предоставляет аптечка при наличие этого трейта вместо какого-то surgery_act() со стороны аптечки?

2022-04-20 16:51 UTC, Zickusable commented
> актуальность изменения сомнительна
>
Я даже хз что тут сказать. Выглядит как насмешка.

2022-04-20 17:13 UTC, Sakuya-Izayoi requested changes

2022-04-20 17:13 UTC, Sakuya-Izayoi commented on code/modules/surgery/tissue.dm
> +		return 0
```suggestion
		return FALSE
```

И так везде

2022-05-04 21:30 UTC, Sakuya-Izayoi approved these changes

2022-05-04 21:34 UTC, merged

2022-05-08 10:27 UTC, WatlerJe commented
Классно-здорово, где рецепт на вики? Мне надо будет каждый раз гуглить этот ПР чтобы провести операцию?