Бафф атмостехов
TauCetiStation/TauCetiClassic pull request #8987
Opened 2022-03-29 08:22 UTC by Tap0r

## Описание изменений
Атмостехам в шкаф добавлено удобное хранилище для надувных стен и дверей, которое помещается в рюкзаке. В него влезают 5 таких штучек, но только атмосные. Изначально там 3 стены и 2 дверки.
Атмосные надувные барьеры круче обычных: быстрее надуваются, прочнее.
Атмостехам добавлен крутой мини огнетушитель с меньшим размером и уполовиненной вместимостью обычного.
В фаер сюит теперь можно повесить баллон, как на риг. А это плюс удобство при тушении пожара, не нужно снимать рюкзак.
![1](https://user-images.githubusercontent.com/88531962/160566370-6f0a195c-f105-43f8-bfc4-07bce9cce425.PNG)
![image](https://user-images.githubusercontent.com/88531962/160566438-ca1f3d4b-19bd-40e4-b52a-60c57c3b48b5.png)
![1](https://user-images.githubusercontent.com/88531962/160566627-66b3f3c7-85c8-4d19-9478-4cde8f2583ab.gif)

## Почему и что этот ПР улучшит
Атмостехи станут круче, надувные барьеры будут использоваться чаще, ибо стали удобнее.
## Авторство
я
## Чеинжлог
:cl: 
 - add: Атмосные барьеры для локализации пожаров. Удобное хранилище для них. Атмосный мини огнетушитель.
 - tweak: В противопожарный костюм можно повесить баллон, как на риг.

2022-03-29 08:22 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2022-03-29 08:36 UTC, TauKitty commented
Этот запрос на извлечение был упомянут в **Tau Ceti Station Forum**. Там могут быть соответствующие подробности:

https://forum.taucetistation.org/t/obnovlenie-snaryazheniya-atmotehov/32682/30

2022-03-29 11:07 UTC, WatlerJe commented
Это все круто конечно, но если хочется действительно бафнуть атмосотехов то лучше всего будет портануть с ТГ RPD: 
![image](https://user-images.githubusercontent.com/19796920/160598292-d371c7fa-c8fa-4747-8f92-b8ca1c1304f0.png)

Ибо таскать эти два сраных гроба каждый раз когда где-то пукнет трубопровод совсем не весело.

2022-03-29 11:12 UTC, Deahaka commented
Не слушай Вальтера, никто не таскает эти два гроба при маленьких пуках труб, только при катастрофах. Если и менять то убирать с большинства стен на станции Air Alarm либо переделать его на механ, который как-то задействует атмостехов. Сейчас атмосферник существует только для настройки атмоса, остальное могут делать все.

2022-03-29 12:27 UTC, LudwigVonChesterfield commented on code/game/objects/items/weapons/storage/fancy.dm
> +/obj/item/weapon/storage/fancy/atmos
в карго/рнд добавишь?

2022-03-29 12:27 UTC, LudwigVonChesterfield commented on code/game/objects/items/weapons/storage/fancy.dm
> +	return
```suggestion
```

2022-03-29 12:28 UTC, LudwigVonChesterfield commented on code/modules/clothing/suits/utility.dm
> +	allowed = list(/obj/item/device/flashlight,/obj/item/weapon/tank,/obj/item/weapon/reagent_containers/spray/extinguisher,/obj/item/clothing/mask/gas)
ууу противогаз класть можно)

незадокументировано, но я не против

2022-03-29 12:28 UTC, AndroBetel commented on code/game/objects/items/weapons/storage/fancy.dm
> +/obj/item/weapon/storage/fancy/atmos
мне кажется, добавлять какие-то конкретные фичи отделы в карго/рнд это так себе идея, потому что теряется весь прикол.
лучше добавлять их аналоги похуже, как сделали с дробовиками из брига - в оружейке лежит комбат шотган, а в карго можно заказать только обычные.

2022-03-29 12:29 UTC, LudwigVonChesterfield commented on code/game/objects/items/weapons/storage/fancy.dm
> +	name = "box of inflatable barrier"
```suggestion
	name = "box of inflatable barriers"
```

2022-03-29 12:29 UTC, LudwigVonChesterfield commented on code/game/objects/structures/inflatable.dm
> +	name = "atmostech's inflatable wall"
мне atmostech's не очень нравится если честно. лучше назови как есть - reinforced inflatable wall

2022-03-30 05:46 UTC, UDaV73rus requested changes
Чисто сине-голубые стены с прозрачностью выглядят как голографические, не хватает технического инженерного желтого цвета, который сообщает об опасности

2022-03-30 22:29 UTC, LudwigVonChesterfield reviewed
я за но пожалуйста ответь на комментарии про интеграцию твоего итема в станцию

если кто-то украдёт выделенные раундстартом коробки - шо делать? карго/рнд/автолат - обычно ответ на такой вопрос, но тут ни одно из трёх не используется

2022-04-03 12:15 UTC, LudwigVonChesterfield commented on code/game/objects/items/weapons/grenades/chem_grenade.dm
> +	name = "afff grenade"
```suggestion
	name = "aqueous foam grenade"
```

2022-04-03 12:15 UTC, LudwigVonChesterfield commented on code/game/objects/items/weapons/grenades/chem_grenade.dm
> +	desc = ""
```suggestion
	desc = "When the heat is too much, man!"
```

2022-04-03 12:15 UTC, LudwigVonChesterfield commented on code/game/objects/structures/inflatable.dm
> +	var/flate_time = 40
inflate_time ?

2022-04-10 10:10 UTC, Deahaka commented
В теории, если это те же стены, что и были, но улучшенные, почему бы их засунуть не в шкафчик всем, а в исследования РнД/карго-ящики? Они редко будут кому-то нужны, как улучшенные инструменты, но вполне логично. В раунды-катастрофы будет дополнительная возможность защищать отсеки, не манча доступ атмостеха.

2022-05-09 19:00 UTC, closed without merging