Объединение Rest и Crawl
TauCetiStation/TauCetiClassic pull request #8998
Opened 2022-03-30 08:49 UTC by Deahaka

## Описание изменений
Кравл заменил Рест. Крутая кнопка на интерфейсе будет позже.
## Почему и что этот ПР улучшит
Улучшает код, убирает неочевидные механики, улучшает баланс, ослабляет абузы, убирает механобобные фичи.
## Авторство
Luduk придумал
## Чеинжлог
:cl: Deahaka
 - tweak: Rest больше не используется.
 - balance: Убран эффект обездвиживания операционному столу и воздействием урона по мозгу.

2022-03-30 08:49 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2022-03-30 08:51 UTC, Deahaka commented
Надо что-то придумать с проверками на "y" у Иана, кажется. А также уточнить требуется ли AdjustCrawling и SetCrawling?

2022-03-30 08:52 UTC, LudwigVonChesterfield commented on code/modules/mob/living/carbon/human/life.dm
> +					crawling = 1
разве тут не нужно вызывать функцию кравла?

2022-03-30 08:53 UTC, LudwigVonChesterfield commented on code/modules/mob/living/carbon/xenomorph/xenomorph.dm
> +	canmove = !(weakened || paralysis || stat || (status_flags & FAKEDEATH) || crawling || stunned || captured || pinned.len)
canmove = !crawling

не уверен что понимаю. ксеносы в кравле не должны ходить?

2022-03-30 08:54 UTC, Deahaka commented on code/modules/mob/living/carbon/xenomorph/xenomorph.dm
> +	canmove = !(weakened || paralysis || stat || (status_flags & FAKEDEATH) || crawling || stunned || captured || pinned.len)
Не должны, это 1000% будет абузится и ещё не красиво

2022-03-30 08:55 UTC, LudwigVonChesterfield commented on code/modules/mob/living/carbon/human/life.dm
> +					crawling = 1
тут походу нужно AdjustCrawling(1)

2022-03-30 10:39 UTC, kalazus commented on code/modules/mob/living/carbon/xenomorph/xenomorph.dm
> +	canmove = !(weakened || paralysis || stat || (status_flags & FAKEDEATH) || crawling || stunned || captured || pinned.len)
Чтобы не было как раньше, где лежачие ксеноморфы под невидимостью ебали все живое.

2022-03-30 10:51 UTC, KIBORG04 commented on code/modules/mob/living/carbon/xenomorph/xenomorph.dm
> +	canmove = !(weakened || paralysis || stat || (status_flags & FAKEDEATH) || crawling || stunned || captured || pinned.len)
Раньше ксеноморфы не замедлялись при кравле. Надеюсь, этот ПР сделает универсальную систему для всех мобов?

2022-03-30 11:02 UTC, Deahaka commented on code/modules/mob/living/carbon/xenomorph/xenomorph.dm
> +	canmove = !(weakened || paralysis || stat || (status_flags & FAKEDEATH) || crawling || stunned || captured || pinned.len)
У ксеноморфов не было беганья с накоплением х2 плазмы, регеном и тд и не будет. Либо выпилить бафы от лежания, что не красиво по отношению к Ахио, либо сделать абузное говно, где лёжа передвигаться не будет только хантер, чтобы липнуть.

2022-03-30 11:03 UTC, KIBORG04 commented on code/modules/mob/living/carbon/xenomorph/xenomorph.dm
> +	canmove = !(weakened || paralysis || stat || (status_flags & FAKEDEATH) || crawling || stunned || captured || pinned.len)
Удачи робастить без возможности бить, юзать спеллы и очень медленно передвигаясь.

2022-03-30 11:07 UTC, kalazus commented on code/modules/mob/living/carbon/xenomorph/xenomorph.dm
> +	canmove = !(weakened || paralysis || stat || (status_flags & FAKEDEATH) || crawling || stunned || captured || pinned.len)
Бить лёжа можно было всегда, просто в руки не взять оружие. Также тут говорится про лип, что не спелл.

2022-03-30 11:07 UTC, KIBORG04 commented on code/modules/mob/living/carbon/xenomorph/xenomorph.dm
> +	canmove = !(weakened || paralysis || stat || (status_flags & FAKEDEATH) || crawling || stunned || captured || pinned.len)
На хумане нельзя же бить. А про липы воксов в кравле я тоже не слышал.

2022-03-30 11:08 UTC, Deahaka commented on code/modules/mob/living/carbon/xenomorph/xenomorph.dm
> +	canmove = !(weakened || paralysis || stat || (status_flags & FAKEDEATH) || crawling || stunned || captured || pinned.len)
> Удачи робастить без возможности бить, юзать спеллы и очень медленно передвигаясь.

Бить в ресте можно, юзать спелы можно, удачи убить квину и ватагу таких же челиков проходящих сквозь друг друга в один ксеноком смерти

2022-03-30 11:09 UTC, kalazus commented on code/modules/mob/living/carbon/xenomorph/xenomorph.dm
> +	canmove = !(weakened || paralysis || stat || (status_flags & FAKEDEATH) || crawling || stunned || captured || pinned.len)
Можно руками бить в кравле, как и использовать оружие с nodrop, о чём недавно писали в ишшуи.

2022-03-30 11:10 UTC, KIBORG04 commented on code/modules/mob/living/carbon/xenomorph/xenomorph.dm
> +	canmove = !(weakened || paralysis || stat || (status_flags & FAKEDEATH) || crawling || stunned || captured || pinned.len)
Ты меня не понял, я не пишу как на самом деле, я пишу как будет нормально и справедливо. Когда ты не тупо отключить кравлинг им, а забалансишь

2022-03-30 11:15 UTC, Deahaka commented on code/modules/mob/living/carbon/xenomorph/xenomorph.dm
> +	canmove = !(weakened || paralysis || stat || (status_flags & FAKEDEATH) || crawling || stunned || captured || pinned.len)
Другим ПРом. Я взял то что было и поменял код, ничего не меняя, кроме того что написал в чейнджлоге. И балансить надо с каким-то представлением "как должно быть", отличным от того что уже есть. Меня полностью устраивает то что сейчас есть, ползать ксеноморфам тупо не нужно, так как из мобфлагов у них нет только движения через стены блин.

2022-03-30 22:18 UTC, LudwigVonChesterfield approved these changes
думаю можно тестить

2022-03-31 21:37 UTC, KIBORG04 commented on code/modules/mob/living/carbon/xenomorph/xenomorph.dm
> +	crawling = !crawling
Я если честно в ахуе, что с интом делаются такие приколы

2022-03-31 21:38 UTC, KIBORG04 commented on code/modules/mob/living/carbon/carbon.dm
> +						src.crawling = 0
Используй сетКравлиг

2022-03-31 21:38 UTC, KIBORG04 commented on code/game/machinery/OpTable.dm
> +	C.crawling = 1
тут тоже сет

2022-03-31 21:39 UTC, KIBORG04 commented on code/modules/sports/pbag.dm
> +	crawling = TRUE
Это все еще инт изай сет кравлинг

2022-03-31 21:39 UTC, KIBORG04 commented on code/modules/sports/pbag.dm
> +	crawling = FALSE
Это все еще инт изай сет кравлинг

2022-03-31 21:39 UTC, KIBORG04 commented on code/modules/mob/mob.dm
>  	return
Убери бесполезные ретурны в функциях

2022-03-31 21:40 UTC, KIBORG04 commented on code/modules/mob/living/carbon/xenomorph/xenomorph.dm
> +	crawling = !crawling
Это все еще инт изай сет кравлинг

2022-03-31 21:41 UTC, kalazus commented on code/modules/mob/living/carbon/xenomorph/xenomorph.dm
> +	crawling = !crawling
Какой к чёрту инт? Кравл всегда был белом, а все сеттеры аддастеры идут с древнего говнокода.

2022-03-31 22:08 UTC, KIBORG04 commented on code/modules/mob/living/carbon/xenomorph/xenomorph.dm
> +	crawling = !crawling
Да даже если я не прав и он по факту бул, то все равно пусть в сеттер оборачивает

2022-03-31 22:09 UTC, KIBORG04 commented on code/modules/mob/mob.dm
>  	return
Если какие-то функции не используются, то удали их нах

2022-04-01 09:16 UTC, Deahaka commented
Поменял на SetCrawling, но грустно, что в проке теперь вместо 1-й строки теперь пишется 4 с двумя проверками.

2022-04-01 09:16 UTC, Deahaka commented
Поменял на SetCrawling, но грустно, что в проке теперь вместо 1-й строки теперь пишется 4 с двумя проверками.

2022-04-01 09:17 UTC, KIBORG04 commented on code/modules/mob/living/carbon/xenomorph/xenomorph.dm
> +		SetCrawling(1)
ехх вот если бы ты писал в одну строчку, то не было бы 4

```suggestion
		SetCrawling(!crawling)
```

2022-04-01 09:19 UTC, KIBORG04 commented on code/modules/sports/pbag.dm
> +	SetCrawling(0)
я кажется прозрел(открыл код). Кравлинг не инт, а булл. Это значит, что все 0 замени на FALSE, а все 1 на TRUE в контексте изменения кравлинга

2022-04-01 09:20 UTC, KIBORG04 commented on code/modules/mob/mob.dm
> +	crawling = max(max(crawling, amount), 0)
Подозреваю эта функция тоже не используется

2022-04-01 09:22 UTC, KIBORG04 commented on code/modules/mob/living/silicon/robot/life.dm
> +	if(src.crawling)
```suggestion
	if(crawling)
```

2022-04-02 09:08 UTC, WatlerJe commented
А можно еще сделать рабочие руки в положении лежа? На фонте ТГ у нас это смотрится очень кринжево.

2022-04-02 09:27 UTC, UDaV73rus commented
Это у них кринжово смотрится на фоне нас :sunglasses:

2022-04-02 13:39 UTC, Deahaka commented
> А можно еще сделать рабочие руки в положении лежа? На фонте ТГ у нас это смотрится очень кринжево.

Так вроде для этого и объединяется...

2022-04-04 14:26 UTC, LudwigVonChesterfield commented
смешных два бага но прошу пофиксить на выбор только один из них:

- если залезть под стол, а потом двинуться об стену - ты всплываешь на стол
- если быть "на столе", а не под ним и попытаться встать - ты ударишься об стол

я бы предпочёл если бы пофикшено было второе

2022-04-04 14:33 UTC, Deahaka commented
Первый не я делал, так и было раньше. Второе попробую заделать

2022-04-04 14:51 UTC, LudwigVonChesterfield commented
Убираю из ТМ-а потому-что путём каких-то хитрых манипуляций можно забагать и начать в стоячем положении сквозь столы ходить

2022-04-04 14:57 UTC, kalazus commented
> Убираю из ТМ-а потому-что путём каких-то хитрых манипуляций можно забагать и начать в стоячем положении сквозь столы ходить

Это точно не карлик со сломанным спрайтом? Помню слышал про такое до этого пра.

2022-04-04 15:15 UTC, kalazus commented on code/modules/mob/mob.dm
> +/mob/proc/SetCrawling(value)
Перенеси логику изменения флага сюда по типу:
```dm
if(value)
    pass_flags |= PASS_TABLE
else
    pass_flags &= ~PASS_TABLE
```
И убери изменения флагов рядом с SetCrawling

2022-04-04 17:56 UTC, LudwigVonChesterfield commented
раньше на стуле можно было Rest делать чтобы быстрее сбить боль. теперь нлеьзя.

возможно Кравл стоит переименновать в Rest/Lay down?

2022-04-04 18:06 UTC, kalazus commented
> раньше на стуле можно было Rest делать чтобы быстрее сбить боль. теперь нлеьзя.
> 
> возможно Кравл стоит переименновать в Rest/Lay down?

Ты механоебство считаешь фичей?

Предлагаю добавить is_resting (вместо .resting где логично) и определять его по нескольким критериям. По типу, если человек кравлит или прибаклен и не двигался какое-то время (last_move у нас есть)? Ну или даже без времени как сейчас.

2022-04-04 18:11 UTC, Deahaka commented
> раньше на стуле можно было Rest делать чтобы быстрее сбить боль. теперь нлеьзя.
> 
> возможно Кравл стоит переименновать в Rest/Lay down?

Мне впринципе нравится что ложась на пол, пока тебя тащат и/или ты в наручниках можно начать балдеть получая снижение боли от размазывания кишок/лица по полу. Сейчас верну, но надеюсь когда-нибудь это удалят

2022-04-04 20:43 UTC, Deahaka commented
"Если во время ивента на отключение гравитации упасть то потом будет супер быстро ползать"
Кто видел этот баг/как его делали пожалуйста напишите всё что знаете, повторить не получается.

2022-04-05 09:33 UTC, LudwigVonChesterfield commented on code/modules/mob/living/carbon/carbon.dm
> +					if((!IsSleeping()) || ((src.crawling) && (crawl_can_use())))
crawl_can_use -> can_crawl?

2022-04-06 07:51 UTC, Deahaka commented on code/modules/mob/living/carbon/ian/ian.dm
> +	verbs += /mob/living/proc/ian_sit
Надо ли делать его ДО вызова родителя?

2022-04-06 07:52 UTC, Deahaka commented on code/_onclick/hud/ian.dm
> +				if(4 to 29)  // lie
Когда это используется и надо ли это вообще?

2022-04-06 08:41 UTC, kalazus commented on code/modules/mob/living/living.dm
> +/mob/living/proc/ian_sit()
Я возможно чего-то не понимаю, но почему прок ian_sit находится не в Яне? И почему это называется проком, а не вербом, тогда бы не приходилось добавлять выше?

2022-04-06 10:07 UTC, Deahaka commented on code/modules/mob/living/living.dm
> +/mob/living/proc/ian_sit()
Вообще я в ливинг засунул чтобы canmove обновлялся просто. Сейчас попробую поменять в самом Яне... А прок чтобы не выдавался всем ливингам, как верб.

2022-04-06 10:57 UTC, Deahaka commented on code/_onclick/hud/ian.dm
> +				if(4 to 29)  // lie
Кажется я допёр. Это хоткей на юзер интерфейсе у Яна.

2022-04-06 14:17 UTC, Lafrien commented
Теперь после того, как прожал Crawl - можно **ходить _под**_ столами. Стеклянными и обычными тоже. Без задержек. Просто Noclip через них.

2022-04-07 05:59 UTC, Deahaka commented
Осталось посмотреть что с проверкой на начало операции и вроде всё.

2022-04-07 12:10 UTC, Deahaka commented
Баг с началом операции не баг ПРа, а значит впринципе всё готово к тесту и мєрджу

2022-04-07 12:10 UTC, Deahaka commented
Баг с началом операции не баг ПРа, а значит впринципе всё готово к тесту и мєрджу

2022-04-08 05:31 UTC, KIBORG04 commented
Говорят, протеон может лечь и бегать по всей станции почти бессмертным

2022-04-08 08:09 UTC, LudwigVonChesterfield requested changes
1. симплмобы без спрайта кравлинга могут кравлить
2. ультрагрифозные симплмобы не должны кравлить в принципе

2022-04-08 11:44 UTC, TauKitty commented
Этот запрос на извлечение был упомянут в **Tau Ceti Station Forum**. Там могут быть соответствующие подробности:

https://forum.taucetistation.org/t/community-development-simpl-moby-i-polzane/32880/1

2022-04-08 13:03 UTC, LudwigVonChesterfield approved these changes

2022-04-08 20:52 UTC, Deahaka commented
Добавил чтобы обезьянка не двигалась, если в ней никого нет и она была уложена кем-то в позу лёжа

2022-04-08 21:20 UTC, kalazus commented
У мартышек есть нормальный кравл? Ни разу не видел кажется.

2022-04-09 20:50 UTC, Deahaka commented
Увидел жуткий баг, но вроде не от ПРа: по прилёту шаттла, перед встряской, человек подскользнулся на хонкобанане и начал бесконечно скользить лёжа на двух тайлах взад-вперёд, без урона. Записать к сожалению не успел.

2022-04-13 11:08 UTC, merged