Rcd апдейт
TauCetiStation/TauCetiClassic pull request #9016
Opened 2022-04-01 13:59 UTC by Zickusable

## Описание изменений
Добавил возможность построить остекленный (из коридоров) и пожарный аирлок.
Добавил радиальное меню для выбора режима и подменю для типа аирлока.
Стырил эффекты с ТГ для рцд
пожарный аирлок, окна, двери из стекла теперь удаляются.
Постарался минимум копипаста.

мини иконка для радиального меню
![image](https://user-images.githubusercontent.com/76683966/161277001-0400c6a5-54ae-49cc-9a07-b3e0c662b00e.png)

мини версии аирлоков
![image](https://user-images.githubusercontent.com/76683966/161277200-3032ea97-3589-45ed-adac-17bfef47d52a.png)
![image](https://user-images.githubusercontent.com/76683966/161277372-f9c9d94c-5d49-4b7c-94b1-002a662f697c.png)
![image](https://user-images.githubusercontent.com/76683966/161277509-2f53f15c-8708-41b7-a56b-14f0f02388e7.png)

иконка для деконстракта
![image](https://user-images.githubusercontent.com/76683966/161277721-596d338d-3c84-45f9-aeed-9880d87e818b.png)

## Почему и что этот ПР улучшит
Баланс против рцд в пол.
## Авторство
эффекты и их код с ТГ
## Чеинжлог
:cl:
- image: эффекты для рцд
- tweak: радиальное меню для рцд
- tweak: остекленный и пожарный аирлок можно сделать с помощью рцд
- tweak: окна, стеклянные двери, пожарные аирлоки можно разобрать с помощью рцд

2022-04-01 13:59 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2022-04-01 14:41 UTC, kalazus commented
Чекни ошибки тестов.
Также не понимаю людей что не копируют с ТГ, но при этом делают достаточно похоже...

2022-04-01 21:02 UTC, KIBORG04 commented
Лучше отсюда https://github.com/TauCetiStation/TauCetiClassic/pull/8403 портируй. Тот ПР вроде умер только из-за спрайтов

2022-04-04 18:48 UTC, KIBORG04 commented
А ты хотя бы спросил разрешения использовать эти спрайты и эффекты в своем ПРе?

2022-04-04 18:50 UTC, KIBORG04 commented on code/game/objects/effects/temp_visual/miscellaneous.dm
> +/obj/effect/constructing_effect/proc/update_icon_state()
update_icon функцию вместо того что сейчас

2022-04-04 18:50 UTC, KIBORG04 commented on code/game/objects/effects/temp_visual/miscellaneous.dm
> +	return
```suggestion
```

2022-04-04 18:50 UTC, KIBORG04 commented on code/game/objects/effects/temp_visual/miscellaneous.dm
> +		icon_state = "rcd_end_reverse"
Вместо этого можно вызывать update_icon

2022-04-04 18:51 UTC, KIBORG04 commented on code/game/objects/effects/temp_visual/miscellaneous.dm
> +	if(status == 1)
Что такое status == 1 и почему именно == 1? Это бул или инт?

2022-04-04 18:52 UTC, KIBORG04 commented on code/__DEFINES/_planes_layers.dm
> +  #define ABOVE_ALL_MOB_LAYER 4.7
Выравняй

2022-04-04 18:53 UTC, KIBORG04 commented on code/game/objects/items/weapons/RCD.dm
> +			switch(selection_d)
Пожалуйста не надо этого кринжа с бесконечными свитчами. Я тебе буквально скинул ПР, где готовый, красивый и чёткий код, но ты почему-то взял только эффекты, так еще и, вроде, без разрешений.

2022-04-04 18:58 UTC, Sakuya-Izayoi commented
#8403 умер из-за последнего ревью. Я до компьютера доберусь не скоро, так что можете его пофиксить.

2022-04-06 16:34 UTC, KIBORG04 commented
Спроси

2022-04-06 16:40 UTC, KIBORG04 commented
> ![image](https://user-images.githubusercontent.com/26389417/162024809-0278f211-1a83-49cf-9c8b-dcd3df2c258e.png)

Почему так много этих спрайтов новых создано, так еще и по разным файлам..? Ты либо все в один файл, либо не создавай

2022-04-08 21:33 UTC, Sakuya-Izayoi commented
А где золотой рцд сешный

2022-04-09 09:39 UTC, Zickusable commented
> А где золотой рцд сешный

А в чем его смысл?

2022-04-16 12:04 UTC, KIBORG04 commented on code/game/objects/items/weapons/RCD.dm
> +	QDEL_NULL(icon)
```suggestion
/datum/rcd/Destroy(force, ...)
	holder = null
	QDEL_NULL(icon)
	return ..()
```

2022-04-16 12:04 UTC, KIBORG04 commented on code/game/objects/items/weapons/RCD.dm
> +		rcd_effect = image('icons/effects/rcd.dmi', "deconstruction", ABOVE_ALL_MOB_LAYER)
Почему эти эффекты должны быть выше людей?.. Типо на полу же строить

2022-04-16 12:08 UTC, KIBORG04 commented on code/game/objects/items/weapons/RCD.dm
> +	return
```suggestion
```

2022-04-16 12:09 UTC, KIBORG04 commented on code/game/objects/items/weapons/RCD.dm
> +	if(!matter)
```suggestion
	if(matter == 0)
```

2022-04-16 12:09 UTC, KIBORG04 commented on code/game/objects/items/weapons/RCD.dm
> +	user.update_inv_r_hand()
```suggestion
	user.update_inv_item()
```

2022-04-29 18:20 UTC, KIBORG04 commented
Емае, конфликты, исправь а?

2022-04-29 18:21 UTC, KIBORG04 approved these changes
Замержить после решения конфликтов

2022-05-04 19:38 UTC, Sakuya-Izayoi commented
Спрайты аджаджы были пизже

2022-05-04 21:55 UTC, KIBORG04 commented
А действительно, ты же в этот же ПР вставлял тау кекашные спрайты, зачем убрал?

2022-05-05 12:45 UTC, Zickusable commented
> Он решает проблему бесполезного обджектива на кражу RCD
> 
Пояснения не помешают
>А действительно, ты же в этот же ПР вставлял тау кекашные спрайты, зачем убрал?
>
Которые сейчас или которые из ПРа гетапа?

2022-05-05 13:12 UTC, KIBORG04 commented
Из гетапа

2022-05-05 19:14 UTC, Zickusable commented
> Из гетапа

>А ты хотя бы спросил разрешения использовать эти спрайты и эффекты в своем ПРе?

>Спроси

![image](https://user-images.githubusercontent.com/76683966/167007664-8f5b64b9-f362-4184-9429-9820c071fb45.png)

2022-05-05 19:25 UTC, UDaV73rus commented
Верни наши спрайты, на никакой троллинг не ведись

2022-05-05 19:31 UTC, Sakuya-Izayoi requested changes

2022-05-06 07:18 UTC, Zickusable commented
> Верни наши спрайты, на никакой троллинг не ведись

Мне эффект не нравится, там по краям тайла он просто обрывается. Да и спрайты мне мои больше нравятся. Зря рисовал чтоль

2022-05-06 07:36 UTC, UsadoSmokk requested changes
Не нравится спрайт самого рцд и его..зарядов?...это мало того просто плохо, стало хуже чем было 
![image](https://user-images.githubusercontent.com/56721822/167088034-afb502fc-6839-4721-9cb6-06cebf2bdc89.png)

2022-05-06 07:38 UTC, Zickusable commented on code/game/objects/items/weapons/RCD.dm
> +	return ..()
Типо
```
/datum/rcd/nondense/can_act_on(atom/target)
	if(target.density)
		return FALSE
	for(var/atom/A in target)
		if(A.density || is_type_in_list(A, list(/obj/machinery/door, /obj/structure/mineral_door)))
			return FALSE
	return ..()
```
? Для меня просто эти датумы что-то инопланетное

2022-05-06 07:42 UTC, UsadoSmokk commented
> Не нравится спрайт самого рцд и его..зарядов?...это мало того просто плохо, стало хуже чем было ![image](https://user-images.githubusercontent.com/56721822/167088034-afb502fc-6839-4721-9cb6-06cebf2bdc89.png)

варианты решение следующие:
взять спрайты, которые были в прошлом пре или взять спрайты из других билдов
![image](https://user-images.githubusercontent.com/56721822/167088867-dd469b32-00c9-4cb1-93d9-61e0a4dbec23.png)
![image](https://user-images.githubusercontent.com/56721822/167088888-604667f9-efc7-43f4-b8ab-93f8f9059f0a.png)

2022-05-06 17:26 UTC, Sakuya-Izayoi commented on code/game/objects/items/weapons/RCD.dm
> +	return ..()
Примерно так. Нужно взять и разобраться.

2022-05-07 08:47 UTC, LudwigVonChesterfield commented
ето что старбаунд универсал манипулятор?

2022-09-14 20:09 UTC, volas commented
Пока закрою, будет вновь актуально - слапни. ПР хороший, кто нибудь может подхватить.

2022-09-14 20:09 UTC, closed without merging