Фикс скорости копания киборгов
TauCetiStation/TauCetiClassic pull request #9023
Opened 2022-04-01 18:48 UTC by Dushess0

Фиксит  #9015

2022-04-01 18:48 UTC, TauKitty commented
###### Changelog status: :radio_button: No changelog

2022-04-01 21:00 UTC, KIBORG04 commented on code/modules/mining/mine_items.dm
> -	required_skills = list(/datum/skill/engineering/novice)
А это тоесть и инженеры могли моментально копать или как?

2022-04-02 05:53 UTC, Dushess0 commented on code/modules/mining/mine_items.dm
> -	required_skills = list(/datum/skill/engineering/novice)
Да

2022-04-03 12:09 UTC, LudwigVonChesterfield requested changes
если у нас скиллы могут делать действия которые по задумке должны занимать время - мгновенными, когда раньше они мгновенными не были

то я требую пересмотреть или скиллы в целом, или дать конкретный список мест где это важно и почему только там. к примеру я так понимаю хирургия стала быстрее чем раньше, если да - почему?

2022-04-03 19:42 UTC, Dushess0 commented
> то я требую пересмотреть или скиллы в целом, или дать конкретный список мест где это важно и почему только там. к примеру я так понимаю хирургия стала быстрее чем раньше, если да - почему?

Список мест, где время стало короче, чем было, если у человека максимальный уровень умения.

- Хирургия
- Сборка машинерии, стен
- Откручивание труб
- Разборка стен (для обычных стен ускорение если у человека навык pro и выше, для укрепленных только мастер даёт бонус)
- Сборка двигателя 
- Надевание наручников на человека (+30% и +60% когда навык полиции не 0)


Хирургия стала быстрее, потому что по моему СМО или хирург должны делать её быстрее чем доктор общего назначения.

Разборка стен, тут так же, но для обычного инженера, технического ассистента и СЕ. У тех ассистента остался прежний тайминг, у инженера быстрее, а у СЕ ещё быстрее это выходит.

Наручи  - стандартное время для них мне показалось и так достаточно долгим, так что решил просто дать бафф СБ в этом случае.

2022-04-03 19:53 UTC, Dushess0 commented
> если у нас скиллы могут делать действия которые по задумке должны занимать время - мгновенными, когда раньше они мгновенными не были

Если мы прописываем предмету требуемый навык вроде `required_skills = list(/datum/skill/engineering/novice)`  то если у человека навык выше требуемого, то тогда у него время использования предмета будет уменьшено на 40% (по стандарту, если не изменить). Таким образом может случится ситуация, когда время будет -120% или что-то подобное.

2022-04-04 11:33 UTC, LudwigVonChesterfield approved these changes

2022-04-04 11:34 UTC, LudwigVonChesterfield commented
можно ли сделать чтобы мы не убирали требование на инженерный скилл, а чтобы он уменьшал время вместо просто убирать?

2022-04-04 13:58 UTC, Dushess0 commented
> можно ли сделать чтобы мы не убирали требование на инженерный скилл, а чтобы он уменьшал время вместо просто убирать?

Можно уменьшить ускорение от инженерного скила. Но я бы лучше просто убрал это требование. Потом может добавлю шахтерский навык?  Туда можно будет запихнуть и кирки, буры и взрывчатку шахтёрскую.

2022-04-04 21:00 UTC, merged