c4 resprite
TauCetiStation/TauCetiClassic pull request #9052
Opened 2022-04-04 11:43 UTC by LiLJard

## Описание изменений
респрайт сифора
![image](https://user-images.githubusercontent.com/77955747/161536745-15cfca77-11ed-4561-ac20-323d30fa4df4.png)

## Почему и что этот ПР улучшит
мое настроение улучшит
## Авторство
LiJard
## Чеинжлог
🆑 
- image: Зареспрайчен сифор

2022-04-04 11:43 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2022-04-04 11:47 UTC, WatlerJe commented
ХЗ, как по мне слабо получилось. Хотя ты могешь лучше, может сделаешь спрайт боньбы как в КС:ГО )))00)00? Мы же здесь все так любим отсылки.

2022-04-04 11:52 UTC, AndroBetel commented
my god jc a bomb

2022-04-04 11:59 UTC, LiLJard commented
В билде кстати есть спрайт этот из коэски

2022-04-04 12:37 UTC, muWander commented
почему она в руке выглядит как синтезатор и держится хватом меча

2022-04-04 19:08 UTC, Akellazp commented
![image](https://user-images.githubusercontent.com/47355061/161614540-98b065aa-2e12-4a6b-b477-caf7b7d7706b.png)
https://www.youtube.com/watch?v=yqgDgVbdtoA

2022-04-06 16:30 UTC, UDaV73rus requested changes
> ![image](https://user-images.githubusercontent.com/47355061/161614540-98b065aa-2e12-4a6b-b477-caf7b7d7706b.png)
https://www.youtube.com/watch?v=yqgDgVbdtoA

2022-04-18 16:58 UTC, KIBORG04 commented
это был аппрув или нет?

2022-04-18 16:59 UTC, Sakuya-Izayoi commented
> это был аппрув или нет? А еще конфликты

полагаю удаву не нравится

2022-05-09 19:00 UTC, closed without merging