Конструкторы культа больше не грифонят!
TauCetiStation/TauCetiClassic pull request #9053
Opened 2022-04-04 11:50 UTC by Deahaka

## Описание изменений
Предохранитель на случай резни. Надеюсь будет меньше сломанных ребёр/протыканий ригов.
## Почему и что этот ПР улучшит
resolve #9038 
## Авторство

## Чеинжлог

2022-04-04 11:50 UTC, TauKitty commented
###### Changelog status: :radio_button: No changelog

2022-04-04 12:22 UTC, LudwigVonChesterfield commented on code/modules/mob/living/carbon/carbon.dm
> +		if((iscultist(src)) && (!do_after(attacker, 20, target = src)))
можно всё это в одну строчку?
```
if(iscultist(attack) && iscultists(src) && !is_busy() && !do_after())
```

2022-04-04 12:27 UTC, KIBORG04 commented on code/modules/mob/living/carbon/carbon.dm
> +		if((iscultist(src)) && (!do_after(attacker, 20, target = src)))
Почему этот механ где-то  в карбонах вообще, а не конструктах?

2022-04-04 12:42 UTC, Deahaka commented on code/modules/mob/living/carbon/carbon.dm
> +		if((iscultist(src)) && (!do_after(attacker, 20, target = src)))
В конструктах я не допёр как сделать

2022-04-04 13:40 UTC, Deahaka commented
Надо ли is_busy? Смысл ведь не в том, чтобы замедлить убийство своих, а в том чтобы сделать условие для такого. Может надо будет убить своего быстро, мало ли

2022-04-04 13:51 UTC, LudwigVonChesterfield commented
Напиши что:
1. Больше не грифонят СВОИХ
2. Добавь в ченжлог изменение

2022-04-04 16:37 UTC, KIBORG04 requested changes
Мне текущее решение не нравится по множествам причинам. Писать не буду, они очевидны)

В общем, переопредели прок UnarmedAttack у конструктов, вызывай родителя (или придумай епта `attack_construct()`), а так же, самое главное, не забудь, что конструкты так-то не только культовские бывают, а вообще у любого челика.

 Помочь щас не смогу, но формирование "рольки" и добавление во фракцию в соулстоне написаны.

2022-04-05 09:08 UTC, Deahaka commented
То что конструкты бывают не только у культа не приводит к случайным ломаниям жизни хозяев, ведь их не бывает в таком же колличестве. Оверинженерингом не хочется заниматься.

2022-04-05 09:39 UTC, KIBORG04 commented
> То что конструкты бывают не только у культа не приводит к случайным ломаниям жизни хозяев, ведь их не бывает в таком же колличестве. Оверинженерингом не хочется заниматься.

Это не оверинжиринг, это нормальная реализация фичи

2022-04-06 17:18 UTC, KIBORG04 commented on code/_onclick/other_mobs.dm
> +	if((iscultist(A)) && (iscultist(src)) && (!do_after(src, 20, target = A)))
1. скобочки вокруг функций не нужны
2. Все еще нету проверки фракции
3. Это прок затрагивает не только конструктов

2022-04-07 06:43 UTC, Ro2tCrab commented
> Мне текущее решение не нравится по множествам причинам. Писать не буду, они очевидны)
> 
> В общем, переопредели прок UnarmedAttack у конструктов, вызывай родителя (или придумай епта `attack_construct()`), а так же, самое главное, не забудь, что конструкты так-то не только культовские бывают, а вообще у любого челика.
> 
>  Помочь щас не смогу, но формирование "рольки" и добавление во фракцию в соулстоне написаны.

Не стоит ещё забывать об редкой необходимости устранить человека из той же фракции.

Подобный случай редкий, но вполне может иметь место.

2022-04-16 10:59 UTC, closed without merging