Модуль джетпака для всех боргов
TauCetiStation/TauCetiClassic pull request #9055
Opened 2022-04-04 15:17 UTC by Mercurialaste

## Описание изменений
Убрал проверку на модуль при установке джетпака.
Перевел/адаптировал на русский язык название и описание модуля.
_(Реколибратор дисплея у нас уже есть, почему бы и не перевести ещё модулей?)_

## Почему и что этот ПР улучшит
Добавит актуальности к существующему модулю джетпака.
Русские букавы.

## Авторство
я
## Чеинжлог
- tweak: возможность установки модуля джетпака на любого борга.
- tweak: перевод/адаптация текста.

2022-04-04 15:17 UTC, TauKitty commented
###### Changelog status: :radio_button: No changelog

2022-04-04 15:21 UTC, LoTaRk-FroG commented
В чейнжлоге
ru: [text].

2022-04-04 16:24 UTC, LoTaRk-FroG commented
Ещё эмодзи :.cl.: (без точек) добавь в чейнжлог. 
:.cl.:
. -. ru: [text].
Сверху пример (без точек).

2022-04-04 16:41 UTC, Mercurialaste commented
> Ещё эмодзи :.cl.: (без точек) добавь в чейнжлог. 
> 
> :.cl.:
> 
> . -. ru: [text].
> 
> Сверху пример (без точек). 

Примерно так?

2022-04-06 07:01 UTC, 4310V343k requested changes

2022-04-06 07:01 UTC, 4310V343k commented on code/game/objects/items/robot/robot_upgrades.dm
> +	R.jetpacked = 1
Почему нельзя создавать новый джетпак внутри борга, привязав его к какой-нибудь переменной в нем?

2022-04-06 07:01 UTC, 4310V343k commented on code/modules/mob/living/silicon/robot/robot_modules.dm
> +	jetpack.name = "Модуль маневрирования"
Может лучше создать новый подтип?

2022-04-06 08:06 UTC, Mercurialaste commented on code/game/objects/items/robot/robot_upgrades.dm
> +	R.jetpacked = 1
Или, в теории можно сделать более упорото, просто выдавая боргу без модуля джетпак. Но из-за каждой смены модуля джетпак будет возвращаться к стандартным параметрам, накачал ты его 18000 кпа или разрядил до 0 кпа, после смены он всегда будет наполнен до стандартного значения, как думаешь, достаточно серьезная проблема?

2022-04-06 08:07 UTC, Mercurialaste commented on code/modules/mob/living/silicon/robot/robot_modules.dm
> +	jetpack.name = "Модуль маневрирования"
Мб... Если только я пойму что именно подразумевается под подтипом в данном случае. Тк, по своей сути, делал целиком и полностью опираясь на код емаг модулей.

2022-04-06 08:35 UTC, kalazus commented on code/modules/mob/living/silicon/robot/robot_modules.dm
> +	jetpack.name = "Модуль маневрирования"
```dm
/obj/item/weapon/tank/jetpack/carbondioxide/robot
    name = "Модуль маневрирования"
```

2022-04-06 09:03 UTC, kalazus commented on code/modules/mob/living/silicon/robot/robot_modules.dm
> +	jetpack.name = "Модуль маневрирования"
Вообще, не очень понимаю зачем джетпак переименовывать в модуль маневрирования...

2022-04-06 09:44 UTC, Mercurialaste commented on code/modules/mob/living/silicon/robot/robot_modules.dm
> +	jetpack.name = "Модуль маневрирования"
Понемногу перевести модули, рекалибратор дисплея сделали, почему бы не сделать и модуль маневрирования?

2022-04-06 10:15 UTC, 4310V343k commented on code/game/objects/items/robot/robot_upgrades.dm
> +	R.jetpacked = 1
Почему он будет сбрасываться? Как это вообще связано с модулями, если джетпак будет в борге?

2022-04-06 11:52 UTC, Mercurialaste commented on code/game/objects/items/robot/robot_upgrades.dm
> +	R.jetpacked = 1
> Почему он будет сбрасываться? Как это вообще связано с модулями, если джетпак будет в борге?

Если будет в борге, в этом-то и дело. Пока что, я не припомню модулей которые бы сохранялись при смене модуля.

Код построен так, что при каждой смене модуля, боргу заново выдаются все модули. Если у борга emagged == 1, то ещё и добавляет взломанный модуль. 

В случае с ВТЕК к примеру, как я понял из кода, идет взаимодействие с параметрами моба, а именно изменение его скорости. Тут же по сути, нужно сделать джетпак модулем, который всегда есть в списке, если jetpacked == 1. Но к слову, у этого сброса есть и свой плюс. Джетпак может быть потерян/уничтожен и тогда борг по сути останется без джетпака. _(Только ради примера, но, борг может смешать условно, горячий форон + холодный кислород и подорвать себе джетпак. Он исчезнет и более не вернется, пока не произойдет смена модуля.)_ 

Т.е. В теории, сброс модуля решает проблему утерянного джетпака, тк он выдается заново, по этому его типа нельзя привязывать чисто к мобу, чтобы он выдавался 1 раз, после установки улучшения модуля джетпака. _(ХЗ, можно ли сделать как-то проверку на то, уничтожен модуль или нет, тк, к примеру, с сервис боргом, если ты будешь бить его бутылкой с пивом по голове, то будешь наносить урон/станить если нет каски/и под тобой будет появляться розочка, можешь повторять пока модуль активен и отображаться он будет всегда как целая бутылка. Но, стоит спрятать модуль в "рюкзак" как из-за отсутствия модельки его уже становится невозможно выбрать. Как-то так.)_

2022-04-06 11:59 UTC, 4310V343k commented on code/game/objects/items/robot/robot_upgrades.dm
> +	R.jetpacked = 1
```
/obj/item/borg/upgrade/jetpack/action(mob/living/silicon/robot/R)
	if(..()) return FALSE

    if(R.jetpack)
		to_chat(usr, "There's no room for another jetpack!")
		return FALSE

	R.jetpack = new(R)
	return TRUE
```

2022-04-06 12:06 UTC, Mercurialaste commented on code/game/objects/items/robot/robot_upgrades.dm
> +	R.jetpacked = 1
Проверка на то, установлен ли уже джетпак?

2022-04-06 16:08 UTC, KIBORG04 commented on code/game/objects/items/robot/robot_upgrades.dm
> +	name = "Модуль маневрирования"
Удали название, описание пох

2022-04-06 16:13 UTC, KIBORG04 commented on code/_onclick/hud/robot.dm
> +					y++
что это и зачем оно надо

2022-04-06 16:17 UTC, KIBORG04 commented on code/modules/mob/living/silicon/robot/robot_modules.dm
> +	jetpack.name = "Модуль маневрирования"
Переметси всю копипасту в атом_инит в /obj/item/weapon/robot_module

2022-04-06 16:18 UTC, KIBORG04 commented on code/modules/mob/living/silicon/robot/robot.dm
> +	var/jetpacked = 0
Назови переменную нормально и вместо 1/0 используй TRUE/FALSE

2022-04-06 16:20 UTC, KIBORG04 commented on code/_onclick/hud/robot.dm
> +				r.module.remove_item(r.module.jetpack)
Даже нормально не смог скопипастить механ и изменить его на свой.  `if(r.module.emag in r.module.modules)`

2022-04-06 16:24 UTC, Mercurialaste commented on code/_onclick/hud/robot.dm
> +					y++
Копирка с кода емага. Я более менее понимаю первую часть кода, связанную с if(r.jetpacked).
Дальше как я понял, идут настройки отображения которые я не трогал.

Нужно для того, чтобы при смене модуля джетпак не исчезал, а выдавался заново. _(Как с емагнутыми модулями.)_

2022-04-06 17:08 UTC, Mercurialaste commented on code/game/objects/items/robot/robot_upgrades.dm
> +	R.jetpacked = 1
> ```dm
> /obj/item/borg/upgrade/jetpack/action(mob/living/silicon/robot/R)
> 	if(..()) return FALSE
> 
>     if(R.jetpack)
> 		to_chat(usr, "There's no room for another jetpack!")
> 		return FALSE
> 
> 	R.jetpack = new(R)         //(?)
> 	return TRUE
> ```

Можешь, пожалуйста, объяснить, что происходит в помеченной строке?

2022-04-06 17:36 UTC, 4310V343k commented on code/game/objects/items/robot/robot_upgrades.dm
> +	R.jetpacked = 1
новый джетпак создается в борге

2022-04-06 17:46 UTC, Mercurialaste commented on code/game/objects/items/robot/robot_upgrades.dm
> +	R.jetpacked = 1
> новый джетпак создается в борге

У меня он на этом моменте делает ошибку компиляции - code\game\objects\items\robot\robot_upgrades.dm:142:error: R.has_jetpack: unknown variable type

2022-04-06 17:50 UTC, Mercurialaste commented on code/_onclick/hud/robot.dm
> +		if(r.jetpacked)
> Борг без модуля не сможет использовать джетпак, не зависящий от модуля. Обидно

К слову насчет этого, где-то в коде борга есть проверка на то, выбран у него модуль или нет. Если модуль не выбран, то он даже не может посмотреть в свой "рюкзак" чтобы выбрать модуль. 

_(Нашел способ, как сделать возможной установку джетпака для борга без модуля. Нужно получается ещё и эту проверку подтереть...)_

2022-04-06 17:50 UTC, Mercurialaste commented on code/_onclick/hud/robot.dm
> +				r.module.remove_item(r.module.jetpack)
> Даже нормально не смог скопипастить механ и изменить его на свой. `if(r.module.emag in r.module.modules)`

ой...

2022-04-07 09:44 UTC, Mercurialaste commented on code/_onclick/hud/robot.dm
> +				r.module.remove_item(r.module.jetpack)
> Это должно быть перед прорисовкой модулей

Угусь... Примерно понял что-то значит. На локалке уже не ломает верстку. Спасибо.

2022-04-07 14:37 UTC, 4310V343k requested changes

2022-04-07 14:37 UTC, 4310V343k commented on code/modules/mob/living/silicon/robot/robot_modules.dm
> +
Какие-то новые табы тут и ниже

2022-04-07 14:55 UTC, Mercurialaste commented on code/modules/mob/living/silicon/robot/robot_modules.dm
> +
Крч, это невидимый код, который позволяет мне получать хост права на сервере, только тссс... Никому ни слова...

2022-04-07 18:03 UTC, KIBORG04 commented on code/modules/mob/living/silicon/robot/robot_modules.dm
> +
Вот тебе ссылка секретная https://github.com/TauCetiStation/TauCetiClassic/pull/9055/files, показывает все изменения кода в браузере. Сделай чтобы все бесполезные и бессмысленные зеленые строчки снова стали красными.

2022-04-07 18:04 UTC, KIBORG04 commented on code/modules/mob/living/silicon/robot/robot_modules.dm
> +	jetpack.name = "robot jetpack"
не нужно ему здесь имя ставить..

2022-04-07 18:05 UTC, KIBORG04 commented on code/game/objects/items/robot/robot_upgrades.dm
> +	if(R.has_jetpack == TRUE)
У нас в билде не принято писать сравнение булевой переменной в таком виде
```
if(has_jetpack == TRUE) 
===>
if(has_jetpack)
-----------------------------
if(has_jetpack == FALSE)
====>
if(!has_jetpack)
```

2022-04-07 18:10 UTC, KIBORG04 commented on code/modules/mob/living/silicon/robot/robot_modules.dm
> +	jetpack = new /obj/item/weapon/tank/jetpack/carbondioxide(src)
Тебе кстати надо создавать джетпак не тут, а в /obj/item/borg/upgrade/jetpack/action(mob/living/silicon/robot/R)

2022-04-08 12:40 UTC, Mercurialaste commented on code/modules/mob/living/silicon/robot/robot_modules.dm
> +	jetpack = new /obj/item/weapon/tank/jetpack/carbondioxide(src)
> Норм че и у дронов будет жетпак?

А дронам разве можно ставить улучшения с помощью плат?

2022-04-08 16:49 UTC, KIBORG04 commented on code/modules/mob/living/silicon/robot/robot_modules.dm
> -/obj/item/weapon/robot_module
че

2022-04-08 16:50 UTC, KIBORG04 commented on code/modules/mob/living/silicon/robot/robot_modules.dm
> +	jetpack = new /obj/item/weapon/tank/jetpack/carbondioxide(src)
Видимо уже не актуально, раз файла такого больше нет...

2022-04-08 17:07 UTC, 4310V343k commented on code/modules/mob/living/silicon/robot/robot_modules.dm
> -/obj/item/weapon/robot_module
ничею. буквально, файла больше нет

2022-04-08 18:22 UTC, Mercurialaste commented on code/modules/mob/living/silicon/robot/robot_modules.dm
> +	jetpack = new /obj/item/weapon/tank/jetpack/carbondioxide(src)
Но его нужно вернуть в состоянии до изменений, так?...

2022-04-08 18:29 UTC, KIBORG04 commented on code/modules/mob/living/silicon/robot/robot_modules.dm
> +	jetpack = new /obj/item/weapon/tank/jetpack/carbondioxide(src)
Конечно нужно..

2022-04-11 15:47 UTC, KIBORG04 commented on code/game/objects/items/robot/robot_upgrades.dm
> -	R.module.add_item(jet)
Я щас писал, чтобы ты вот такой код вернул.

2022-04-11 15:48 UTC, KIBORG04 commented on code/_onclick/hud/robot.dm
> +				r.module.add_item(r.module.jetpack)
А раз джетпак добавляется в апгрейде, то здесь этот код не нужен будет?

2022-04-14 10:04 UTC, 4310V343k commented on code/modules/mob/living/silicon/robot/robot_modules.dm
> +	jetpack = new /obj/item/weapon/tank/jetpack/carbondioxide(src)
А потом двигаем переменную джетпак в борга, и не добавляем его в модули

2022-05-04 08:08 UTC, Mercurialaste commented on code/modules/mob/living/silicon/robot/robot_modules.dm
> +	jetpack = new /obj/item/weapon/tank/jetpack/carbondioxide(src)
Т.е. Мы с помощью платы апгрейда, создаем джетпак в борге и меняем переменную jetpack на TRUE, а потом, в модулях делаем проверку, которая при смене модуля будет снова добавлять джетпак? 

И на счет создавать его всем модулям, в том числе и дрону. 
В случае дрона, только админ приколами можно будет поменять has_jetpack на TRUE.
В случае синдикат модуля, я думаю банально добавить if прявязанный к синдикат модулю, который ставит has_jetapck на TRUE.

_(Мб я что-то криво делаю с добавлением `var/obj/item/weapon/tank/jetpack/jetpack`, но при сбросе модуля, у меня jetpack остаеться на TRUE и сбрасываеться джетпак. А из-за того, что jetpack - TRUE, нельзя вставить плату ещё раз.)_

>/obj/item/borg/upgrade/jetpack
>	name = "mining robot jetpack"
>	desc = "A carbon dioxide jetpack suitable for low-gravity mining operations."
>	icon_state = "cyborg_upgrade3"
>	require_module = 1
>
>/obj/item/borg/upgrade/jetpack/action(mob/living/silicon/robot/R)
>	if(..())
>		return FALSE
>
>	if(R.jetpack)
>		return FALSE
>		
>	var/obj/item/weapon/tank/jetpack/carbondioxide/jet = new(R.module)
>	R.module.add_item(jet)
>	R.jetpack = TRUE
>
>	return TRUE 

Ну и в варианте с копиркой емага, можно поставить require_module = 0 и ставить джетпак боргу без модуля, в текущем который я тещу - нет.

И что за - var/obj/item/weapon/tank/jetpack/jetpack <- Такой переменной в файле нигде не упоминается.

2022-05-21 15:31 UTC, Mercurialaste commented
падажи

2022-05-23 06:33 UTC, Mercurialaste commented
@KIBORG04 
Можешь чекнуть текущий вариант?
Я пытался сделать как ты говорил, но у меня всегда вылазила проблема с тем, чтобы сохранять джетпак при смене модуля.
В текущем варианте, все работает. 
_(Хотя я вот думаю, чтобы не плодить ПР`ы добавить ещё емагнутость синди борга, указав это в cl, фича крайне маленькая, учитывая, что ещё не разу синди борга не пытались замаскировать под НТ`шного.)_

2022-05-23 06:36 UTC, 4310V343k commented
Да еб твою мать храни ты уже джетпак в борге

2022-05-23 06:39 UTC, Mercurialaste commented
> Да еб твою мать храни ты уже джетпак в борге

Тк он по сути и хранится в has_jetpack, т.е. в борге... Добавляется не в борге, это да.

2022-05-23 06:55 UTC, 4310V343k commented
> > Да еб твою мать храни ты уже джетпак в борге
> 
> Тк он по сути и хранится в has_jetpack, т.е. в борге... Добавляется не в борге, это да.

Джетпак хранится в модуле, а в борге лишь есть переменная, говорящая, что его надо добавить в инвентарь.

2022-06-13 11:43 UTC, closed without merging