Reafactor breath
TauCetiStation/TauCetiClassic pull request #9061
Opened 2022-04-04 20:47 UTC by kalazus

## Описание изменений
Одно дыхание на хуманов/яна/мартышек

## Почему и что этот ПР улучшит

## Авторство

## Чеинжлог

2022-04-04 20:47 UTC, TauKitty commented
###### Changelog status: :radio_button: No changelog

2022-04-04 20:53 UTC, LudwigVonChesterfield commented
фиксит #8874 ?

2022-04-04 20:56 UTC, kalazus commented
> фиксит #8874 ?

Вроде нет, там проблема больше что вокс парамедик спавнится с кислородным, а не азотным баллоном.

2022-04-04 20:56 UTC, LudwigVonChesterfield commented on code/modules/mob/living/carbon/carbon.dm
> +	return
можно убрать этот ретюрн

2022-04-04 20:57 UTC, LudwigVonChesterfield commented on code/modules/mob/living/carbon/carbon.dm
> +	if(stat != DEAD) // lets put this shit somewhere here
where

2022-04-04 20:59 UTC, kalazus commented on code/modules/mob/living/carbon/carbon.dm
> +	return
Вроде уже убрал, но почему-то не отображается что старый код...

2022-04-04 20:59 UTC, LudwigVonChesterfield approved these changes

2022-04-04 21:00 UTC, kalazus commented on code/modules/mob/living/carbon/carbon.dm
> +	if(stat != DEAD) // lets put this shit somewhere here
? пока вся жизнь через жопу написана и чтобы не делать кучу изменений засунул пока сюда.

2022-04-10 20:15 UTC, LudwigVonChesterfield commented on code/modules/mob/living/carbon/human/life.dm
> +		SEND_SIGNAL(src, COMSIG_ADD_MOOD_EVENT, "hot")
```suggestion
		SEND_SIGNAL(src, COMSIG_ADD_MOOD_EVENT, "hot", /datum/mood_event/hot)
```

2022-04-10 20:15 UTC, LudwigVonChesterfield commented on code/modules/mob/living/carbon/human/life.dm
> +		SEND_SIGNAL(src, COMSIG_ADD_MOOD_EVENT, "cold")
```suggestion
		SEND_SIGNAL(src, COMSIG_ADD_MOOD_EVENT, "cold", /datum/mood_event/cold)
```

2022-04-10 20:16 UTC, LudwigVonChesterfield requested changes
рантаймы из-за неуказания типа мудлета

2022-04-10 20:58 UTC, kalazus commented
Мда, чёт забыл что кроме группы ещё нужен мудлет. Убрал конфликты и закоммитил предложения.

2022-04-10 21:34 UTC, LudwigVonChesterfield approved these changes

2022-04-10 21:35 UTC, merged