Ребаланс патронов для дробовика
TauCetiStation/TauCetiClassic pull request #9069
Opened 2022-04-06 05:25 UTC by simb11

## Описание изменений
Слаги теперь наносят 40 урона и кнокают на пару секунд
У дроби совсем немного повышен урон, кол-во дробинок и разлёт этой самой дроби.
Зажигательные слаги превратились в зажигательные бакшоты.
Стандробь наносит в два раза больше болеурона и выстреливает пятью дробинками.
## Почему и что этот ПР улучшит
Б а л а н с
Слаги больше не будут ультимативной мерой против всех и вся, даже против людей в буллетпруфе. Для людей без брони особо ничего не изменится, теперь они будут падать не из-за боли или отсутствия ноги, а из-за эффекта патрона.
Остальные патроны будут чаще использовать.
## Авторство
## Чеинжлог
:cl: Simbaka
- balance[link]: Изменен урон, разброс и количество дроби у патронов для дробовика.

2022-04-06 05:25 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2022-04-06 06:24 UTC, Deahaka commented
Слаги фиксить хорошо, но мне кажется увеличивать колличество дробинок у остальных патронов немного жёстко. 12 пулек во все стороны поджигающие врагов или 5 апнутых на боль дробинок с одного выстрела... Как оно в тестах то показывает себя? Это не ультра-кил и не ваншот, как сейчас слаг?

2022-04-06 06:41 UTC, simb11 commented
Дробь наносит +- 50 урона с дистанции в 5 тайлов.
Огненные пули наносят примерно 35 урона с такой же дистанции .
От стандроби отлично защищает почти любая броня.

2022-04-06 08:47 UTC, AndroBetel commented on code/modules/projectiles/projectile/bullets.dm
> +	name = "shotgun slag"
slug

2022-04-06 14:48 UTC, kalazus commented
> У дроби совсем немного повышен урон, кол-во дробинок и разлёт этой самой дроби.

Нужно говорить, что разброс увеличен в 1.5+ раза, а не пытаться скрыть его за увеличением урона.

2022-04-06 14:48 UTC, AndroBetel commented on code/modules/projectiles/ammunition/bullets.dm
> +	pellets = 12
делаешь выстрел поинтбланком и у чела вылетает игра

2022-04-06 16:30 UTC, KIBORG04 commented on code/modules/projectiles/projectile/bullets.dm
> +	stoping_power = 3
Сделаешь урон 41, будет стан в 1,5 секунды)

 Но все равно, почему слаг перестанут использовать, если это почти гарантированный стан в 3 секунды? Что раньше слаг прилетал в ногу и это гарантированный кил, что щас целишься в тело и гарантированный кил.

2022-04-06 16:39 UTC, Akellazp commented
> кнокают на пару секунд
хуита переделывай

2022-04-06 17:05 UTC, KIBORG04 commented on code/modules/projectiles/projectile/bullets.dm
> +	stoping_power = 3
У абдукторов нету. У магов риг (еще не замерженный). 
Я хз как эти 3 секунды работают на какую-либо броню, и тебе наверное стоит посмотреть сколько этот же стан работает на ту же культо-броню или там на нюцкера.

2022-04-07 05:28 UTC, simb11 commented on code/modules/projectiles/projectile/bullets.dm
> +	stoping_power = 3
У абдукторов есть так называемая командная работа и мгновенный телепорт в безопасную зону.
50 защиты сейчас не спасут от перелома, есть большой шанс того что в ране застрянет шрапнель и докинет бонусные 10 урона.
Стан не работает сквозь броню.

2022-04-12 12:34 UTC, NinjaPikachuska commented
Стан действительно странный. Он точно необходим?

2022-04-12 13:58 UTC, simb11 commented
Да, я не вижу других способов занерфить слаги так, чтобы они были и не хуже, и не лучше других патронов.

2022-05-04 20:15 UTC, simb11 commented
.

2022-05-04 20:41 UTC, Sakuya-Izayoi commented on code/modules/projectiles/ammunition/bullets.dm
> +	pellets = 12
я затестил, у меня даже заметных лагспайков не было.

2022-05-04 20:46 UTC, Sakuya-Izayoi requested changes

2022-05-04 20:46 UTC, Sakuya-Izayoi commented on code/modules/projectiles/projectile/bullets.dm
> +		M.IgniteMob()
Копипаста. Сделай аргумент adjust_fire_stacks свойством снаряда, у родителя его сделай сколько там было, в этом типе 2.

2022-05-14 10:21 UTC, AndroBetel commented
почему не мержим

2022-05-14 19:11 UTC, KIBORG04 commented on code/modules/mob/living/carbon/human/human_defense.dm
> +
```suggestion
```

2022-05-14 19:11 UTC, KIBORG04 commented on code/modules/mob/living/carbon/human/human_defense.dm
> +
```suggestion
```

2022-05-14 19:11 UTC, KIBORG04 commented on code/modules/mob/living/living_defense.dm
> +
```suggestion
	//Being hit while using a deadman switch
```

2022-05-14 19:13 UTC, KIBORG04 commented
Лан пох, убери "бесполезный" код и замержу, так уж и быть

2022-05-14 19:13 UTC, KIBORG04 commented
Но я очень надеюсь, что если что вдруг ты придёшь и пофиксить цифры

2022-05-14 19:47 UTC, KIBORG04 commented on code/modules/mob/living/living_defense.dm
> +		IgniteMob()
Это, вроде, должно быть в on_hit() с проверкой на blocked >= 100

2022-05-15 07:45 UTC, simb11 commented on code/modules/mob/living/living_defense.dm
> +		IgniteMob()
Зачем? Вроде ж и так нормально работает

2022-05-17 18:33 UTC, KIBORG04 commented on code/modules/mob/living/living_defense.dm
> +		IgniteMob()
Работает то и работает, но в он_хит уже содержится похожая логика со статус_эффектами. Ну и логично класть похожее к похожему.

2022-05-17 18:36 UTC, KIBORG04 approved these changes

2022-05-17 18:38 UTC, KIBORG04 requested changes
Точнее так, потом мерж

2022-05-30 20:50 UTC, Deahaka commented
Блин две недели прошло. Оно ж из-за метаболизма не мержилось? Может уже пора?))

2022-05-31 18:28 UTC, KIBORG04 commented
Нет, я попросил перенести в другую функцию механ и всё, там вроде секундное дело

2022-06-01 09:13 UTC, KIBORG04 commented on code/modules/mob/living/living_defense.dm
> +		IgniteMob()
В on_hit

2022-06-01 09:46 UTC, simb11 commented on code/modules/mob/living/living_defense.dm
> +		IgniteMob()
так?

2022-06-02 22:11 UTC, KIBORG04 commented on code/modules/mob/living/living_defense.dm
> +			IgniteMob()
Перенеси в On_hit(). Внутрь функции

2022-06-06 15:47 UTC, KIBORG04 commented on code/modules/projectiles/projectile.dm
> +	if((incendiary) && (blocked <= 100))
```suggestion
	if(incendiary && blocked <= 100)
```

2022-06-06 15:52 UTC, merged