Фикс скиллов гост ролей и дронов
TauCetiStation/TauCetiClassic pull request #9098
Opened 2022-04-09 20:47 UTC by Dushess0

Фиксит #9042 и #9058. Так же фискит скилы агента прослушки.  Так же заменил скилы у дронов/киборгов не на макс умения в некоторых областях. 

Насчёт умений голема то добавил ему их, но тоже не максимум во всех областях, поскольку сейчас скиллы не запрещают выполнять действия.

2022-04-09 20:47 UTC, TauKitty commented
###### Changelog status: :radio_button: No changelog

2022-04-09 20:55 UTC, LudwigVonChesterfield commented on code/game/objects/items/robot/robot_parts.dm
> +			O.mind.skills.add_available_skillset(/datum/skillset/cyborg)
ты тут забыл максималить скиллы?

2022-04-09 20:57 UTC, Dushess0 commented on code/game/objects/items/robot/robot_parts.dm
> +			O.mind.skills.add_available_skillset(/datum/skillset/cyborg)
да, забыл. Поправил это.
```
O.mind.skills.add_available_skillset(/datum/skillset/cyborg)
O.mind.skills.maximize_active_skills()
```

2022-04-09 20:59 UTC, LudwigVonChesterfield commented on code/modules/mob/living/silicon/robot/syndi/drone/drone.dm
> +		if(!(all_skillsets[/datum/skillset/cyborg] in mind.skills.available_skillsets))
мне ета проверка не нравится, для чего она?

если она абсолютно необходима, добавь

```
/datum/skillset/has_skillset(type)
    return all_skillsets[type] in available_skillsets
```

2022-04-09 21:00 UTC, LudwigVonChesterfield commented on code/modules/skills/skillsets.dm
> +	)
добавь пустую строку в конце

2022-04-09 22:01 UTC, Dushess0 commented on code/modules/mob/living/silicon/robot/syndi/drone/drone.dm
> +		if(!(all_skillsets[/datum/skillset/cyborg] in mind.skills.available_skillsets))
Поскольку код для включения удаленного контроля дрона довольно странный и его майнд создается только в моменте, когда мы включаем управление дроном (что можем делать часто довольно). То надо делать проверку на то добавили ли мы этот скилсет уже или нет. 

Добавил это в процедуру
```
/datum/skills/proc/has_skillset_type(type)
	return all_skillsets[type] in available_skillsets
```

2022-04-09 22:02 UTC, LudwigVonChesterfield commented on code/modules/mob/living/silicon/robot/syndi/drone/drone.dm
> +		if(!(all_skillsets[/datum/skillset/cyborg] in mind.skills.available_skillsets))
а можно дрону добавить скиллсет единожды, при спавнея?

2022-04-10 14:29 UTC, Dushess0 commented on code/modules/mob/living/silicon/robot/syndi/drone/drone.dm
> +		if(!(all_skillsets[/datum/skillset/cyborg] in mind.skills.available_skillsets))
нельзя, при спауне у него нету майнда

2022-04-10 14:33 UTC, Dushess0 commented on code/modules/mob/living/silicon/robot/syndi/drone/drone.dm
> +		if(!(all_skillsets[/datum/skillset/cyborg] in mind.skills.available_skillsets))
Нельзя, поскольку у дрона нету майнда при спауне. Только в моменте когда мы в него вселяемся

2022-04-10 18:16 UTC, LudwigVonChesterfield commented on code/modules/mob/living/silicon/robot/syndi/drone/drone.dm
> +		if(!mind.skills.has_skillset_type(/datum/skillset/cyborg))
так стоп

а как вселиться в дрона дважды?

2022-04-10 18:17 UTC, LudwigVonChesterfield commented on code/modules/mob/living/silicon/robot/syndi/drone/drone.dm
> +		if(!mind.skills.has_skillset_type(/datum/skillset/cyborg))
где убирается скиллсет когда я выхожу из контроля?!

ты же понимаешь что сейчас ты покупаешь эту триторштучку, даёшь кому-то попилотировать дрона - и он стаёт разнорабочим 10-ой степени

2022-04-10 18:17 UTC, Mercurialaste commented on code/modules/mob/living/silicon/robot/syndi/drone/drone.dm
> +		if(!mind.skills.has_skillset_type(/datum/skillset/cyborg))
> так стоп
> 
> а как вселиться в дрона дважды?

Если игрок на дроне гостается, дрона можно реактивировать и в него вселится кто-то из гостов.

2022-04-10 18:17 UTC, LudwigVonChesterfield requested changes
критический баг если кто-то кроме тритора поуправляет дроном синдиката а потом отпустит он становится умельцем на все руки

2022-04-10 20:23 UTC, Dushess0 commented
> критический баг если кто-то кроме тритора поуправляет дроном синдиката а потом отпустит он становится умельцем на все руки

Не было такого. Но теперь код для добавления скиллсета для дрона вызывается только моменте когда мы создаем ему майнд

2022-04-10 20:26 UTC, LudwigVonChesterfield approved these changes

2022-04-10 20:26 UTC, LudwigVonChesterfield commented on code/datums/skills.dm
> +/datum/skills/proc/has_skillset_type(type)
теперь эта функция не нужна выходит. и я надеюсь что никогда не будет нужна

2022-04-10 20:27 UTC, LudwigVonChesterfield commented on code/datums/skills.dm
> +/datum/skills/proc/has_skillset_type(type)
```suggestion
```

2022-04-10 20:27 UTC, LudwigVonChesterfield commented on code/datums/skills.dm
> +	return all_skillsets[type] in available_skillsets
```suggestion
```

2022-04-10 20:37 UTC, Dushess0 commented on code/datums/skills.dm
> +/datum/skills/proc/has_skillset_type(type)
Убрал функцию

2022-04-10 20:38 UTC, Dushess0 commented on code/modules/mob/living/silicon/robot/syndi/drone/drone.dm
> +		if(!mind.skills.has_skillset_type(/datum/skillset/cyborg))
Мы про радиоуправляемого дрона из аплинка

2022-04-11 07:38 UTC, merged