Key Memories
TauCetiStation/TauCetiClassic pull request #9104
Opened 2022-04-10 22:17 UTC by LudwigVonChesterfield

## Описание изменений

#5265, но менее амбициозно, и разбито на куски

убирает хранение в майнде ссылки на аккаунт, заменяя на хранение у куклы номера аккаунта, и взятия его в нужных местах `get_account()` функцией.

Добавляет кнопку "Add Key Memory" для того чтобы сделать себе хуже запомнив неправильный пин
Добавляет кнопку "List Key Memories" которая даёт список воспоминаний которые реально играются

Да, можно ключевые воспоминания писать там же где сейчас неструктурированные, но мне кажется приятней мне, и полезней игроку будет разделять эти две концепции. ~~ведь неструктурированные надо будет выпилить~~

## Заметки

`get_account()` проходится по всем существующим аккаунтам, их может быть целых 70 в "нормальном случае", и сколько влезет в случае если ХоП - идиот... если понадобится заменю на лукап-таблицу, тогда уж точно проблем не будет (да и сейчас не должно быть)

## А дальше что?

Этот ПР - краеугольный камень большой РП эволюции.

сейчас воспоминания ("Заметки") ("Notes") куклы - неструктурированный набор текста

хочу, и добавляю воспоминания куклы как что-то с чем можно работать кодом. пока-что мягко, и без насилия, но... по пунктам:

1. Перенос всех паролей на эту систему в принципе
2. Добавление возможности делиться воспоминаниями, предлагаю следующие два способа:
- Макрос вида `%МАКРОС%` в чатик заменяется на значение воспоминания, которое кликабельно. при клике - кликнувший тоже получает это воспоминание. ("РЕБЯТ МОЙ ПИН КОД %account pin%" -> "РЕБЯТА МОЙ ПИН КОД [1337](https://www.youtube.com/watch?v=dQw4w9WgXcQ)")
- Такого же вида макрос но в бумажке. Представляете, главам можно формочки с вики добавить в память, и написав %ФОРМА_ВЫЗОВ_ШАТТЛА% получаешь нужную форму?!

(ДАЛЬШЕ ШИЗА)

3. Добавляем "автоввод". Если у тебя есть воспоминание пароля к аккаунту - нажав на кнопку "Enter PIN" даже не вводя ничего в поле "PIN" ты вводишь правильный пинкод.
4. Из-за пункта 3 появляются случаи когда ты знаешь пинкод от одной карточки, а хотел бы от двух. Но ты не можешь их дифференциировать потому-что `%ПИН%` он и тут, и там `%ПИН%`. Для решения этого вопроса предлагаю добавить "метки":
- Игрок может добавить любому предмету "метку" - введёный им текст.
- При осмотре игрок получает сообщение вида "Этот предмет заставил вас думать о [метке]..."
- При юзании автоввода сначала проверяется на наличие воспоминания "[метка]:[воспоминание]", точно так же в чатик можно писать %МЕТКА:ВОСПОМИНАНИЕ% чтобы получить нужное.
- Если возможность игроком писать любую метку слишком сильная и мемасная - дать список одобренных меток.
- Метку на предмете видят и менять могут все, чтобы можно было сбивать с толку.
5. Убираем возможность игроку видеть "значение" по ключу ключевого воспоминания. Игрок знает что знает код от бомбы. Но он не знает цифор кода от бомбы.
- Воспоминания в чатике надо будет как-то выделять кроме ссылки.
- Можно для вида в чат всё ещё писать не %КОД_ОТ_БОМБЫ%, а какие-то циферки. Кликая по ним запоминаешь код, но сами цифры кода на самом деле ничего не делают, и если побежать их вводит - получится зрада.
6. Убираем неструктурированные заметки куклы.
- Если они конечно кому-то нужны, то можем и оставить, будет у игрока свой блокнотик...

## Почему и что этот ПР улучшит

потом расскажу

## Чеинжлог
:cl: Luduk
- rscadd: Кнопка "Add Key Memory" позволяющая запомнить(или забыть) ключевое-важное воспоминание по ключу! Так же кнопка "List Key Memories" которая пишет список всех ключевых воспоминаний.

2022-04-10 22:17 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2022-04-11 16:03 UTC, KIBORG04 commented on code/modules/memories/memories.dm
> +		output += "[key] as [memory]<BR>"
Мб ключ выделять жирным, а инфу в нем курсивом? Ну или каких-нибудь других минимальных спец. эффектов.

2022-04-11 16:08 UTC, KIBORG04 commented on code/modules/memories/memories.dm
> +		return
> То есть это игроку ещё надо думать в каком формате ему надо скормить текст чтобы оно работало

У нас не так много фронт-энд кодеров, так что скорее всего останется два бьондо инпута.

2022-04-11 16:09 UTC, KIBORG04 commented on code/modules/memories/memories.dm
> +/mob/verb/add_key_memory()
Кстати, может эти кнопки не делать вербами, а сделать кнопками в окошке Notes'ов?

2022-04-11 16:18 UTC, LudwigVonChesterfield commented on code/modules/memories/memories.dm
> +		output += "[key] as [memory]<BR>"
курсив инфы выглядит очень некрасиво, и я думаю инфа важнее ключа. могу жирным, но у нас жирным заголовок...

2022-04-11 16:19 UTC, LudwigVonChesterfield commented on code/modules/memories/memories.dm
> +		return
это правда останется два инпута

я их все равно выпилить хочу в будущем читайте ## А дальше что?

2022-04-11 16:19 UTC, LudwigVonChesterfield commented on code/modules/memories/memories.dm
> +/mob/verb/add_key_memory()
чукча не верстун, чукча так не сделает

поможешь?

2022-04-11 16:23 UTC, KIBORG04 commented on code/modules/memories/memories.dm
> +		output += "[key] as [memory]<BR>"
в мемори может быть много символов, а значит жирный не подходит. Из твоего скриншота выше, очень нужно выделение цифрам

2022-04-11 18:07 UTC, LudwigVonChesterfield commented on code/modules/memories/memories.dm
> +		output += "[key] as [memory]<BR>"
так и курсивом не выделишь если может быть много символов

2022-04-11 18:07 UTC, LudwigVonChesterfield commented on code/modules/memories/memories.dm
> +		output += "[key] as [memory]<BR>"
придумай короче конкретно что ты хочешь, я сделаю и глянем

2022-04-16 11:58 UTC, KIBORG04 commented on code/modules/memories/memories.dm
> +	mind.add_key_memory(key, value)
Вообще, сейчас это вообще никак не используется и особо не нужно. Зачем иметь две системы нотесов сейчас,  если со стороны игроков оно не имеет преимуществ перед обычной системой нотесов? Мб пока что закомментить или вообще выпилить вербы?

2022-04-16 14:16 UTC, LudwigVonChesterfield commented on code/modules/memories/memories.dm
> +	mind.add_key_memory(key, value)
а если я хочу взять и забыть пароль от ПДА? >:(

2022-04-25 12:09 UTC, LudwigVonChesterfield commented
✅ 

с одной стороны вроде всё норм.

с другой стороны не смогу развивать идею дальше ближайшее время... так что... 🤷

2022-05-10 08:13 UTC, LudwigVonChesterfield commented
ПР так-то готов на него просто почему-то всем пох

2022-06-27 20:20 UTC, volas requested changes
пара мелочей

2022-06-27 20:20 UTC, volas commented on code/modules/admin/admin.dm
> -			var/datum/money_account/acc = person["acc_datum"]
Не могу откомментить на нужной строчке, но там ниже еще тело dat использует ``person["acc_datum"]``, когда поле убрали.

Вообще компилятор и линтер это не покажут, на всякий стоит поискать по билду остаточные ``"acc_datum"`` и ``"acc_number"``

2022-11-26 04:30 UTC, LudwigVonChesterfield commented
хаха не ожидали?!

2022-11-26 04:35 UTC, LudwigVonChesterfield commented on code/modules/memories/memories.dm
> +/mob/verb/add_key_memory()
> Куда кстати красивое юи из предыдущего ПР-а делось?

ушло вместе с амбициями... тут пока-что мемы гораздо меньше могут, потому и ЮИ недоразвитое. задумываюсь о том чтобы его вообще выпилить.

@volas как сделать кнопочки в окошке Нотесов чтобы было хорошо?

2022-11-26 04:38 UTC, LudwigVonChesterfield commented on code/modules/admin/admin.dm
> -			var/datum/money_account/acc = person["acc_datum"]
пофиксил кстати

2022-12-02 23:08 UTC, KIBORG04 commented on code/modules/memories/memories.dm
> +		mind.clear_key_memory(key)
Сложный способ забыть. Надеюсь тебе волас поможет добавить кнопки не только добавления, но и забытия

2022-12-02 23:09 UTC, KIBORG04 approved these changes
классный пр

2023-01-10 17:56 UTC, LudwigVonChesterfield commented
я рыгаю

2023-02-16 15:28 UTC, LudwigVonChesterfield commented
го мерж?)

2023-02-16 15:38 UTC, Deahaka commented
Го

2023-02-16 16:37 UTC, LudwigVonChesterfield commented
описание абсолютно актуально

2023-02-16 16:42 UTC, Deahaka commented
написано "Что ПР улучшает потом расскажу", это не очень понятно.

2023-02-18 11:43 UTC, volas commented on code/modules/memories/memories.dm
> +/mob/verb/add_key_memory()
Я вроде писал в дискорде, кнопки добавить просто.

По логике можно разместить топик в ``mind/topic``, но там в основном админский функционал сейчас и нужно будет перписывать. Потому просто добавь пока в конец ``/client/Topic`` новый топик вызывающий add_key_memory, а с фронта это будет выглядить типо

``<a href=?src=\ref[client];button_action_name>Кнопка</a>``

Где button_action_name - название топика, которое ты сможешь использовать в /client/Topic.

2023-02-18 11:43 UTC, volas commented on code/modules/memories/memories.dm
> +/mob/verb/add_key_memory()
Если что, спрашивай

2023-02-18 16:10 UTC, LudwigVonChesterfield commented
@volas @KIBORG04 а не будет странно что запоминается оно через кнопку в Нотесах, но в самих нотесах не рендерится?

или мне в нотесы теперь рендерить мемы... ? (может быть проблематично)

2023-02-18 16:12 UTC, KIBORG04 commented
А где тогда рендерится

2023-02-18 16:12 UTC, LudwigVonChesterfield commented on code/modules/memories/memories.dm
> +/mob/verb/list_key_memories()
@KIBORG04 ну сейчас в этом проке, отдельно

2023-02-18 16:13 UTC, LudwigVonChesterfield commented on code/modules/memories/memories.dm
> +/mob/verb/add_key_memory()
просто говорю, что эти кнопки в моей реализации будут вызывать вербы, потому-что как делать формочки я не знаю...

2023-02-18 16:14 UTC, KIBORG04 commented on code/modules/memories/memories.dm
> +/mob/verb/list_key_memories()
то есть это не нотесы

2023-02-18 16:15 UTC, LudwigVonChesterfield commented on code/modules/memories/memories.dm
> +/mob/verb/list_key_memories()
я могу копипастнуть это в нотес, но тогда в нотесе будет дублирующаяся инфа про код и т.д.

2023-02-18 16:16 UTC, KIBORG04 commented on code/modules/memories/memories.dm
> +/mob/verb/list_key_memories()
Че, а у тебя разве это все не в одном окошке нотесов лежит?

2023-02-18 17:32 UTC, LudwigVonChesterfield commented
добавил кнопку но страница после нажатия на неё не рефрешится.

2023-02-18 17:54 UTC, volas commented on code/modules/memories/memories.dm
> +	mind.add_key_memory(key, value)
```suggestion
	mind.add_key_memory(key, value)
	list_key_memories()
```

> добавил кнопку но страница после нажатия на неё не рефрешится.

2023-02-18 18:14 UTC, LudwigVonChesterfield commented on code/modules/memories/memories.dm
> +	mind.add_key_memory(key, value)
и в правду..

2023-02-22 06:41 UTC, volas approved these changes
Фронт (кнопки и окошки) еще можно было бы улучшить, но ладно, не будем пытать

2023-02-23 07:19 UTC, merged