metatrombine reagent
TauCetiStation/TauCetiClassic pull request #9135
Opened 2022-04-13 13:35 UTC by Sakuya-Izayoi

## Описание изменений
возвращение метатромбина. рецепт бикаридин + найтроджен + потэссиум. останавливает все кровотечения пока находится в крови. передоз 5 юнитов.

## Почему и что этот ПР улучшит
closes #9112 

## Авторство
Luduk

## Чеинжлог
🆑 Luduk
- rscadd: Метатромбин - реагент, который пока находится в крови останавливает любые кровотечения.

2022-04-13 13:37 UTC, Sakuya-Izayoi commented on code/datums/status_effects/buffs.dm
> +/datum/status_effect/wound_clotting
кто-то мог бы подумать что это должен быть трейт, но я не согласен. с реагентами сложно поддерживать состояние трейта, так что это самое простое решение. возможно в будущем такие статус эффекты для которых важен лишь признак присутствия можно выделить в отдельный класс (например, для декстрометорфана), если данному паттерн не найдется опровержение

2022-04-13 13:46 UTC, LudwigVonChesterfield commented on code/datums/status_effects/buffs.dm
> +/datum/status_effect/wound_clotting
не понимаю зачем статус эффект если можно if(has_reagent()) 😔

2022-04-13 13:47 UTC, Sakuya-Izayoi commented on code/datums/status_effects/buffs.dm
> +/datum/status_effect/wound_clotting
для того чтобы не писать хэз риджент. может кто-то захочет сделать чтобы ваунд клоттинг не только от реагента делался, может это ген в генетике может быть.

2022-04-13 14:06 UTC, LudwigVonChesterfield commented on code/datums/status_effects/buffs.dm
> +	duration = 20 // this should be one life tick so it remains active between metatrombine ticks but does not linger
угар, мб заюзать тогда здесь дефайн из подсистемы лайфа?

2022-04-13 14:09 UTC, Sakuya-Izayoi commented on code/datums/status_effects/buffs.dm
> +	duration = 20 // this should be one life tick so it remains active between metatrombine ticks but does not linger
Я так хотел сначала но подумал что это толстейший троллинг

2022-04-13 16:18 UTC, Lafrien commented
Разрешите вставлю свои пять копеек поскольку темы на форуме не нашёл?
По какой причине добавляли "Метатромбин"?
Потому что лечить артериальные кровотечения было очень долго, и их лечение требовало не только прибыть в медбей, но и дождаться своей очереди и только потом уже его лечить - артериальные кровотечения были очень летальными, из-за чего это лекарство помогало отсрочить и облегчить ожидание хирурга.
Сейчас-же в каждой белой аптечке, которая находиться почти в каждом отделе для первой помощи (Поскольку это и есть аптечка первой помощи), имеется игла и нитка. Они лечат артериальные кровотечения без какого-либо врача. А поскольку она находится в белой аптечке (Аптечка первой помощи), то каждый гражданский обладает знаниями пользования ею.

С добавлением этого лекарства необходимо будет подкорректировать работу и/или размещение хирургических игл в целях баланса, поскольку игла сейчас очень сильно затмевает основную работу этого лекарства.

2022-04-13 16:36 UTC, Sakuya-Izayoi commented
можно ли засунуть вашу иголку в смокигрену? сомневаюсь.

2022-04-14 08:25 UTC, notkripton commented
Имхо метатромбин будет юзлесс ибо:
* у врачей есть куча веревок
* неврачам заманчить верёвку легче, чем этот реагент
* прямиком в робасте тоже, думаю, играть ключевой роли не будет ибо артериалка вредит больше как раз после робаста, когда у тебя есть ограниченное время доковылять в мед пока весь не вытек.

Лучше бы такой эффект просто инопровалину прикрутили, либо положили автоинж метатромбина всем в  раундстартовую коробочку

2022-04-19 09:04 UTC, Sakuya-Izayoi commented on code/game/atoms.dm
> +	if(M.has_status_effect(STATUS_EFFECT_WOUND_CLOTTING))
OK

2022-05-02 15:13 UTC, LudwigVonChesterfield commented on code/modules/organs/blood.dm
>  /mob/living/carbon/human/proc/drip(amt, tar = src, ddir)
нужно ли в функции blood_squirt тожы такую проверку?...

2022-05-02 15:14 UTC, LudwigVonChesterfield requested changes
думаю нужно добавить ещё инъекторы которые куда-то расскидать. потому-что сейчас это реагент о котором никто никогда не узнает...

я бы как минимум бутылочку-две ставил в хирургии раундстартом

2022-05-02 15:15 UTC, LudwigVonChesterfield commented on code/modules/organs/blood.dm
> +	if(reagents.has_reagent("metatrombine"))
а хирурги пачкают руки? в смысле думаю про функцию `bloody_hands`

2022-05-02 15:22 UTC, Sakuya-Izayoi commented on code/modules/organs/blood.dm
> +	if(reagents.has_reagent("metatrombine"))
так они вроде не в крови а в мясе их пачкают... 😄 jk
я гляну

2022-05-03 19:31 UTC, LudwigVonChesterfield approved these changes

2022-05-03 20:45 UTC, Sakuya-Izayoi commented on code/modules/surgery/generic.dm
> +	if(!R.has_reagent("metatrombine"))
Я думаю не критично, операции они же по несколько секунд.

2022-05-04 06:27 UTC, merged