Негативка на притяжение неприятностей
TauCetiStation/TauCetiClassic pull request #9144
Opened 2022-04-14 10:41 UTC by Deahaka

## Описание изменений
![111111с](https://user-images.githubusercontent.com/96499407/163371799-c365e788-f6fb-4a6c-b076-6e5bfa6c4568.png)
Интересная идея, почему бы не реализовать. Проблема, что уже запущенная сингулярность не собирает новые таргеты, тобишь лейтспавн особки не будет работать.
## Почему и что этот ПР улучшит
Геймплей и фан
## Авторство

## Чеинжлог

2022-04-14 10:41 UTC, TauKitty commented
###### Changelog status: :radio_button: No changelog

2022-04-14 10:51 UTC, AndroBetel commented
так сделай чтобы собирала...

2022-04-14 11:33 UTC, KIBORG04 requested changes

2022-04-14 11:33 UTC, KIBORG04 commented on code/datums/qualities/negativeish.dm
> +	poi_list += H
Сделай через трейт и цикл по плеер листу

2022-04-14 11:37 UTC, KIBORG04 commented on code/datums/qualities/negativeish.dm
> +	poi_list += H
И как я понял, ты это откуда-то скопировал. Если сделаешь, чтобы синга искала маячек тоже через такой-же трейт, а не пой_лист, то я лайк поставлю. Ну, и похоже, что все же без отдельного глобального листа не обойтись

2022-04-14 12:22 UTC, Deahaka commented on code/datums/qualities/negativeish.dm
> +	poi_list += H
Я исходил из того, что найти из меньшего кол-ва объектов в списке нужный, а также его проверить будет быстрее, чем искать трейт в списке всех хуманов (ибо туда добавляются все). Щас посмотрю что такое цикл ещё...

2022-04-14 12:32 UTC, KIBORG04 commented on code/datums/qualities/negativeish.dm
> +	poi_list += H
Да, может трейт не нужен. Сделай отдельный лист с форсед целями для синги

2022-04-14 13:04 UTC, LudwigVonChesterfield commented on code/modules/mob/living/carbon/human/death.dm
> +	for(var/obj/singularity/singulo in poi_list)
нужно проверять что синга на одном слое с притягивающим игроком наверное

2022-04-14 13:06 UTC, LudwigVonChesterfield commented on code/datums/qualities/negativeish.dm
> +	requirement = "Нет"
```suggestion
	requirement = "Нет."
```

2022-04-14 13:06 UTC, LudwigVonChesterfield commented on code/datums/qualities/negativeish.dm
> +	desc = "Вы чрезвычайно привлекательны... для лорда Сингуло."
если бы игрок как-то знал что теслу он тоже притягивает?...

2022-04-14 13:14 UTC, KIBORG04 commented on code/datums/qualities/negativeish.dm
> +	desc = "Вы чрезвычайно привлекательны... для лорда Сингуло."
У нас синга и тесла сбегают ну очень редко, а если и сбежали, то раунд энд. Так что для меня, довольна странная особка

2022-04-14 13:24 UTC, Deahaka commented on code/datums/qualities/negativeish.dm
> +	desc = "Вы чрезвычайно привлекательны... для лорда Сингуло."
> У нас синга и тесла сбегают ну очень редко, а если и сбежали, то раунд энд. Так что для меня, довольна странная особка

Пока не будет статистики, верить этому комментарию не буду))

2022-04-14 13:51 UTC, LudwigVonChesterfield commented on code/datums/qualities/negativeish.dm
> +	desc = "Вы чрезвычайно привлекательны... для лорда Сингуло."
я полностью поддерживаю Киборча кстати

2022-04-14 14:28 UTC, kiVts commented on code/modules/mob/living/carbon/human/death.dm
> +	for(var/obj/singularity/singulo in poi_list)
Посмотрите как работает гравитационая аномалия?

2022-04-14 16:05 UTC, Deahaka commented
Маячок, который предмет, может начать тянуть сингулярность, даже если она уже запущена. Человек - нет. Мне кажется дело в том, что нужно привязать всё к вару, но где его декларировать - не понятно. Квалити же не с появлением моба начинают работать, а с какой-то задержкой.
А насчёт дополнительного контента в особке - будет.

2022-04-14 17:43 UTC, KIBORG04 commented on code/modules/power/singularity/singularity.dm
> +	for(var/obj/machinery/singularity_beacon/singubeacon in singularity_beacon_list)
Я бы убрал этот код из атом_инита в процессинг. Убрал из бекона хардкод. Убрал бы здесь два цикла, все поместив в один.

2022-04-14 21:43 UTC, Deahaka commented on code/datums/qualities/negativeish.dm
> +/datum/quality/negativeish/singularly_attractive
Теперь нет

2022-04-14 21:45 UTC, Deahaka commented
Контент: имовабул род попытается вас убить, если появится

2022-04-14 22:48 UTC, LudwigVonChesterfield commented
я бы предложил:
```
var/global/list/singularity_targets

/singularity/proc/move_to_targets()
    var/list/targets = list()
    
    for target in global.singularity_targets:
        if target.z == z
            targets += target
 
     if(!targets)
        return
 
    *хз какая должна быть логика если целей несколько, но она тут*

/osobka/pritagivat/add_effect(H)
    singularity_targets += H
    
/singularitybeacon/activate()
    singularity_targets += src
```

2022-04-14 22:48 UTC, LudwigVonChesterfield commented
а вы уже так сделали ой

2022-04-15 08:41 UTC, Deahaka commented
Перенёс в процессинг. Всё что не работало - заработало. Не понял какой у бекона хардкод, а два цикла мне кажется указывают приоритеты бекона перед остальным, хз убирать так как Людук предложил или нет...

2022-04-15 08:43 UTC, UDaV73rus commented
> Геймплей и фан

Как он будет проявляться

2022-04-15 08:46 UTC, LudwigVonChesterfield commented on code/modules/power/singularity/singularity.dm
> +	for(var/obj/machinery/singularity_beacon/singubeacon in singularity_beacon_list)
можно ли сделать какую-то такую формулу, чтобы учитывались все аттракторы сразу?

можно ли сделать такую формулу, чтобы у каждого притягивателя синги был свой "вес", и в зависимости от веса она хотела идти ближе к нему.

То есть грубо, допустим, два челика с этой особкой по весу как один сингабикон, и если встанут в противоположном от него конца - синга двигаться не будет.

2022-04-15 13:53 UTC, Zickusable commented on code/datums/qualities/negativeish.dm
> +	desc = "Вы чрезвычайно привлекательны... для лорда Сингуло."
Гиб от теслы убрали? Там в пыль превращаешься при касании, даже в перчатках.
После побега они просто тусят у двигателя или соляр.
Будет прикольно внезапно быть засосанным в бриге;
пожертвовать собой, уводя ее;
устроить мегахонк в отбытии;
если проговорился, остальные будут пытаться тебя убить и выбросить в церковь при побеге. Можно даже эффект добавить, чтобы точно все знали

2022-04-15 13:57 UTC, Sakuya-Izayoi commented on code/modules/power/singularity/singularity.dm
> +	for(var/obj/machinery/singularity_beacon/singubeacon in singularity_beacon_list)
Формула — сумма векторов направлений к "притягивателям" нормализованных до их веса.

2022-04-15 14:07 UTC, KIBORG04 commented on code/modules/power/singularity/singularity.dm
> +	for(var/obj/machinery/singularity_beacon/singubeacon in singularity_beacon_list)
блин, точно, а я думал че-то с тригонометрией надо думать. Мы же вроде можем получить угол между сингой и целями, а потом их туда-сюда и посередине

2022-04-16 11:15 UTC, KIBORG04 commented on code/datums/qualities/negativeish.dm
> +	singularity_beacon_list += H
Ты здесь должен вешать прослушку сигнала на хумана на его удаление, чтобы при удаление убирать его из листа.
Можешь поискать по `COMSIG_PARENT_QDELETING`. Будет че-то типо
```
RegisterSignal(mob, list(COMSIG_PARENT_QDELETING), .proc/remove)

quality/remove()
	SIGNAL_HANDLER
	singularity_beacon_list -= H

```

2022-04-16 11:25 UTC, KIBORG04 commented on code/game/machinery/syndicatebeacon.dm
> +	singularity_beacon_list -= src
про хардкод я писал, что бы ты удалил 
![image](https://user-images.githubusercontent.com/26389417/163672911-cf103783-a022-4538-9dd5-5e1e1be277e1.png)

2022-04-16 11:25 UTC, KIBORG04 commented on code/modules/events/immovable_rod.dm
> +		destination = turf_H
Стоит ли писать, что это глупо? У тебя род полетит не в рандомную цель, а в последнего хумана в листе. 

Чтобы пофиксить тебе нужно создавать новый лист только хуманами (ТУТ, НЕ ГДЕ-ТО ЕЩЕ, А ТУТ), в него ложить всех хуманов из singularity_beacon_list и потом просто pick(new_list)

2022-04-16 11:25 UTC, KIBORG04 commented on code/modules/events/immovable_rod.dm
> +	for(var/mob/living/carbon/human/H in singularity_beacon_list)
```suggestion
	for(var/mob/living/carbon/human/H in global.singularity_beacon_list)
```
пожалуйста, расставь такое везде

2022-04-16 11:25 UTC, KIBORG04 commented on code/modules/events/immovable_rod.dm
> +			for(clong in singularity_beacon_list)
Ты видимо не тестил? Но эта хуйня просто удалит все элементы листа. Я даже хз че ты тут подразумевал

2022-04-16 11:25 UTC, KIBORG04 commented on code/modules/mob/living/carbon/human/death.dm
> +			singulo.target = null
Зачем?

2022-04-16 11:25 UTC, KIBORG04 commented on code/modules/power/singularity/singularity.dm
>  /obj/singularity/atom_init_late()
пустой прок..

2022-04-16 11:25 UTC, KIBORG04 commented on code/modules/power/singularity/singularity.dm
>  	return
```suggestion
```

2022-04-16 11:25 UTC, KIBORG04 commented on code/datums/qualities/negativeish.dm
> +	singularity_beacon_list += H
А еще хендлить не только qdeliting, но и смерть COMSIG_MOB_DIED

2022-04-16 11:25 UTC, KIBORG04 commented on code/game/machinery/syndicatebeacon.dm
> +	singularity_beacon_list -= src
Хотя похоже без кринжа в Deactivate ТЕБЕ не обойтись.

2022-04-16 11:25 UTC, KIBORG04 commented on code/modules/power/singularity/singularity.dm
> +			return
Опять же, твоя синга ЗДЕСЬ полетит к первому маячку (даже если их много), потом полетит к первому хуману в листе (если их много).

Тебе надо сделать, чтобы синга летела к определённому мачку до тех пор, пока маячёк не станет неактивным. И только потом пытаться найти либо новый маячек, либо нового рандомного человека. 

Либо же, можно по вон тем НЕумным формулам удалить направленный полёт только к маячку и сделать полёт к самому "тяжёлому" по векторной траектории. Этот способ, кстати, будет сделать даже легче, чем то что я писал выше

2022-04-16 11:26 UTC, KIBORG04 commented on code/datums/qualities/negativeish.dm
> +	desc = "Вы чрезвычайно привлекательны... для лорда Сингуло."
А еще описание особки не актуально

2022-04-20 16:22 UTC, Deahaka commented on code/modules/events/immovable_rod.dm
> +			for(clong in singularity_beacon_list)
У меня куделится только имувабл род, хз почему оно должно удалять лист

2022-04-20 16:24 UTC, Deahaka commented
Вроде всё работает согласно плану, только таргет сингулярности не нулится, если она съест хумана

2022-04-20 16:30 UTC, LudwigVonChesterfield commented
надо нуллить иначе будут проблемы. обратись за помощью в дискорд

2022-04-20 16:33 UTC, LudwigVonChesterfield commented on code/datums/qualities/negativeish.dm
> +	var/weight = 4
а в чем прикол делать так а не `LAZYSET(global.singularity_beacon_list, H, 4)`

2022-04-20 16:35 UTC, LudwigVonChesterfield commented on code/modules/power/singularity/singularity.dm
> +/obj/singularity/atom_init_late()			//need for academy singularity
а что такого в родительском /atom_init_late что нужно его подавить

2022-04-20 16:35 UTC, LudwigVonChesterfield commented on code/modules/power/singularity/singularity.dm
>  	return INITIALIZE_HINT_LATELOAD
если юзает только академ синга, то может именно ей и прописать atom_init_late и вот эту подсказку?

2022-04-20 16:37 UTC, Deahaka commented on code/modules/events/immovable_rod.dm
> +		var/target_mob = pick(target_list)
Киборг писал, что род выбирает последнего хумана в списке, а нужно рандомного. Для этого отдельный список и создаётся.

2022-04-20 16:38 UTC, Deahaka commented on code/modules/power/singularity/singularity.dm
> +/obj/singularity/atom_init_late()			//need for academy singularity
Удалить не получается, оставить пустым нельзя, значит ретурн пишем... Как-то так.

2022-04-22 23:24 UTC, Deahaka commented on code/modules/events/immovable_rod.dm
> +				qdel(src)
Тут надо помощь. Без кюдела оно оставляет род на полу, что не красиво. Это всегда происходит из-за Bump() в турфе-месте_назначения.
![22ф](https://user-images.githubusercontent.com/96499407/164816781-1137fc9d-1248-44fe-ac46-30f95c1a15cb.png)
что делать не понимаю

2022-04-23 09:11 UTC, KIBORG04 commented on code/modules/events/immovable_rod.dm
> +			for(T in view(1,src))
Что тут происходит

2022-04-23 09:13 UTC, KIBORG04 commented on code/modules/events/immovable_rod.dm
> +				qdel(src)
Сделай кудел при достижение цели, либо сделай нормально, чтобы иммувебл род летел не в цель, а чтобы вектор движения всегда был направлен в цель

2022-04-23 23:35 UTC, KIBORG04 commented on code/datums/qualities/negativeish.dm
> +	LAZYSET(global.singularity_beacon_list, H, 4)
А ты знаешь зачем нужен LAZYSET, LAZYREMOVE, LAZY-any_verb? Ты же не просто так решил взять и это использовать?

2022-04-23 23:36 UTC, KIBORG04 commented on code/modules/maps/maps_code/Academy.dm
> +	return
Этот код ничего не делает

2022-04-23 23:36 UTC, KIBORG04 commented on code/modules/events/immovable_rod.dm
> +		var/target_mob = pick(target_list)
Что тут происходит

2022-04-23 23:37 UTC, KIBORG04 commented on code/modules/power/singularity/singularity.dm
> +			target = pickweight(global.singularity_beacon_list)
А ээээээ, что тут происходит

2022-04-23 23:37 UTC, KIBORG04 commented on code/modules/power/singularity/singularity.dm
> +			target = pickweight(global.singularity_beacon_list)
Если что, я могу догадаться зачем это, но я хочу узнать почему ты именно это написал/скопировал

2022-04-24 04:46 UTC, Deahaka commented on code/datums/qualities/negativeish.dm
> +	LAZYSET(global.singularity_beacon_list, H, 4)
Чтобы сделать список асоциативным, не? Ты ж сам сообщение людука пометил как решение...

2022-04-24 04:47 UTC, Deahaka commented on code/modules/maps/maps_code/Academy.dm
> +	return
Он не должен ничего делать, кроме как удалять атом-инит конфликты академсинги

2022-04-24 04:49 UTC, Deahaka commented on code/modules/power/singularity/singularity.dm
> +			target = pickweight(global.singularity_beacon_list)
Я не знаю как проверить "пустоватость" списка, по-этому написал так. Если надо по-другому то расскажи как.

2022-04-24 08:43 UTC, Deahaka commented
Переделал чтобы имувабл род летел в сторону моба, но прям врезаться в него он может раз в 5 случаев спавна. Или как-то по пикселям двигать надо, или открыть для себя новый прок перемещения, который будет работать по-диагонали как надо...

2022-04-24 12:24 UTC, KIBORG04 commented on code/datums/qualities/negativeish.dm
> +	LAZYSET(global.singularity_beacon_list, H, 4)
LAZY это некая обёртка над действиями с листом с целью сделать поведения листа ленивым. А ленивое, это когда происходит инициализация листа только когда нужно, а когда не нужно он удаляется. Сейчас у тебя, как видно, по дефолту инициализирован и LAZY-дефайны не имееют смысла.

2022-04-24 12:25 UTC, KIBORG04 commented on code/modules/maps/maps_code/Academy.dm
> +	return
Что такое атом-инит конфликты академсинги

2022-04-24 12:26 UTC, KIBORG04 commented on code/modules/power/singularity/singularity.dm
> +			target = pickweight(global.singularity_beacon_list)
Ты здесь не проверяешь на пустоту листа. Для этого либо `list.len`, либо `length(list)`, если лист может быть нуллом.

2022-04-24 12:27 UTC, KIBORG04 commented on code/modules/events/immovable_rod.dm
> +	walk(src, target_dir, 1)
Выглядит так, будто ты не знаешь что оно делает и рандомно пишешь.

2022-04-25 13:42 UTC, Deahaka commented
Синга работает. Прикольно но недостаточно интересно для плеера. Имувабл род без векторов не сделаю, а других идей чего-то прикольного у меня не появилось за 3 дня обдумывания. Closed.

2022-04-25 13:42 UTC, closed without merging