No Voxs!?
TauCetiStation/TauCetiClassic pull request #9173
Opened 2022-04-17 12:38 UTC by KIBORG04

# Удалил воксов
<h5>из ротации, но теперь это рандом ивент.</h5>

Задачи я не менял.

<details> 
  <summary>А еще по приколу изменил интерфейс шаттла:</summary>
  
![image](https://user-images.githubusercontent.com/26389417/163714287-f3225040-478e-4b9e-91fa-d6fb51fe7608.png)

</details>

А ещё починил компоненту logout_spawner, там не был учтен аргумент `source`. Так что не мёржить причины нет.

## Почему и что этот ПР улучшит
Полугодовое голосование показывает, что воксы очень много кому не нравятся. Тему просмотрели 2к раз, а проголосовало 200 уникальных человек.
https://forum.taucetistation.org/t/golosovanie-vremennoe-vyklyuchenie-rezhimov/28726
Ну и новое голосование для людей:

## Авторство

## Чеинжлог
:cl:
 - add: Воксы-Налётчики - это теперь ивент, а не режим.

2022-04-17 12:38 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2022-04-17 12:38 UTC, TauKitty commented
Этот запрос на извлечение был упомянут в **Tau Ceti Station Forum**. Там могут быть соответствующие подробности:

https://forum.taucetistation.org/t/golosovanie-vykidyvaem-voxs-iz-raundstart-rezhimov/33034/1

2022-04-17 17:58 UTC, volas commented
У нас так скоро режимов вообще не останется, верните может эксту в секрет для разнообразия

2022-04-17 17:59 UTC, Deahaka commented
> У нас так скоро режимов вообще не останется, верните может эксту в секрет для разнообразия

она почти каждый раунд, куда ещё больше.

2022-04-19 16:36 UTC, WatlerJe commented
ХЗ зачем вообще в 2О22 году нужны эти режимы как отдельное явление, если их всех можно форсить раунд ивентом по мере игры. А то сейчас ну очень весело когда на первых минутах условный маг убивается или играет в мирного, что обрекает раунд на тотальную эксту.

2022-04-20 17:34 UTC, Sakuya-Izayoi commented on code/modules/mob/living/carbon/human/death.dm
>  		vox_kills++ //Bad vox. Shouldn't be killing humans.
учитывая что воксы могут прилететь во время событий наверное стоит (в будущем?) переработать механизм инвайолейта? например, инкрементить счетчик только если человек умер после контакта с воксом...

2022-04-20 17:34 UTC, Sakuya-Izayoi commented on code/modules/events/heist.dm
> +	endWhen			= 120
```suggestion
	announceWhen = 12
	endWhen      = 120
```
табы для отступов, пробелы для выравнивания

2022-04-20 17:34 UTC, Sakuya-Izayoi commented on code/modules/events/heist.dm
> +		return
```suggestion
	if(!global.heiststart.len)
		kill()
		return
```
?

2022-04-20 17:34 UTC, Sakuya-Izayoi commented on code/game/machinery/computer/vox_shuttle.dm
> +		Готовность к полёту[max(lastMove + VOX_SHUTTLE_COOLDOWN - world.time, 0) ? " через [max(round((lastMove + VOX_SHUTTLE_COOLDOWN - world.time) * 0.1), 0)] секунд" : ": Готово"]<br><br>
для слова секунд выбрать нужные формы множественного числа

2022-04-20 17:36 UTC, KIBORG04 commented on code/modules/admin/topic.dm
> +		jobs += "<td width='20%'>FREE PLACE!!!</td>"
Чтобы вёрстку не ломать и не пришлось каждый элемент мне переставлять. Хотя можно и пустым наверное оставить, или там колонки объединить..

2022-04-21 15:31 UTC, KIBORG04 commented on code/game/machinery/computer/vox_shuttle.dm
> +		Готовность к полёту[max(lastMove + VOX_SHUTTLE_COOLDOWN - world.time, 0) ? " через [max(round((lastMove + VOX_SHUTTLE_COOLDOWN - world.time) * 0.1), 0)] секунд" : ": Готово"]<br><br>
дан

2022-04-22 06:47 UTC, Sakuya-Izayoi commented on code/game/machinery/computer/vox_shuttle.dm
> +				<td><a href='?src=\ref[src];solars_aft_starboard=1' style='width:100%;text-align:right'>Юго-восток станции</a></td>
окей, а что зачем эти BLOCKED? представь новичка который увидит этот интерфейс. Если ты хотел как-то сделать красиво типа расположение кнопки соответствует стороне света то возможно можно было обойтись без блокедов? ну или какие-то полоски-разделители на их местах нарисовать

2022-04-22 06:50 UTC, KIBORG04 commented on code/game/machinery/computer/vox_shuttle.dm
> +				<td><a href='?src=\ref[src];solars_aft_starboard=1' style='width:100%;text-align:right'>Юго-восток станции</a></td>
Я не умею и незнаю как. Знают что есть hr горизонтальный и все

2022-04-22 06:51 UTC, KIBORG04 commented on code/game/machinery/computer/vox_shuttle.dm
> +				<td><a href='?src=\ref[src];solars_aft_starboard=1' style='width:100%;text-align:right'>Юго-восток станции</a></td>
Хотя, если скажешь как мне вставить карту и кнопки сверху неё, то я сделаю

2022-04-22 06:53 UTC, Sakuya-Izayoi commented on code/game/machinery/computer/vox_shuttle.dm
> +				<td><a href='?src=\ref[src];solars_aft_starboard=1' style='width:100%;text-align:right'>Юго-восток станции</a></td>
самый простой способ это карту вставить имгом, а поверх нее через относительное позиционирование (цсс свойство) разместить кнопки.

2022-04-22 06:54 UTC, KIBORG04 commented on code/game/machinery/computer/vox_shuttle.dm
> +				<td><a href='?src=\ref[src];solars_aft_starboard=1' style='width:100%;text-align:right'>Юго-восток станции</a></td>
Absolute который? И тогда наверное надо будет блокировать растяжение окошка

2022-04-27 22:16 UTC, Sakuya-Izayoi commented on code/game/machinery/computer/vox_shuttle.dm
> +	var/turf/SW_solars
что-то мне подсказывает что это должен быть список

2022-04-27 22:16 UTC, Sakuya-Izayoi commented on code/game/machinery/computer/vox_shuttle.dm
> +		SW_solars = pick(get_area_turfs(/area/shuttle/vox/southwest_solars, FALSE))
почему это делается в интеракте а не ините?

2022-04-27 22:16 UTC, Sakuya-Izayoi commented on code/game/machinery/computer/vox_shuttle.dm
> +			<a href='?src=\ref[src];solars_fore_port=1' style='position: absolute; top: [world.maxy-NW_solars.y]px; left: [NW_solars.x]px;'>[X]</a>
вместо топ можно использовать bottom

2022-04-28 19:35 UTC, KIBORG04 commented on code/game/machinery/computer/vox_shuttle.dm
> +		SW_solars = pick(get_area_turfs(/area/shuttle/vox/southwest_solars, FALSE))
Чтобы каждый раунд не совершать довольно медленные операции при старте.

2022-04-28 19:35 UTC, KIBORG04 commented on code/game/machinery/computer/vox_shuttle.dm
> +	var/turf/SW_solars
А какая разница: делать 4 переменных и делать 4 строки в ассоциативном листе?

2022-04-28 20:48 UTC, KIBORG04 commented on code/game/machinery/computer/vox_shuttle.dm
> +			<a href='?src=\ref[src];solars_fore_port=1' style='position: absolute; top: [world.maxy-NW_solars.y]px; left: [NW_solars.x]px;'>[X]</a>
X - top
A - bottom

Между ними есть разница.
![image](https://user-images.githubusercontent.com/26389417/165842910-57827e62-11aa-4b1c-9a3b-bffc4c1fe32c.png)

Вот только я хз че точнее, но вроде А
![image](https://user-images.githubusercontent.com/26389417/165843007-0caf41ec-f13f-4271-86cc-12cc563f4d29.png)

2022-04-28 21:49 UTC, KIBORG04 commented on code/game/machinery/computer/vox_shuttle.dm
> +	var/turf/SW_solars
Сделал красиво

2022-05-03 14:41 UTC, LudwigVonChesterfield commented on code/datums/mind.dm
>  		if(!FF)
если функция выше гарантирует что фракцию создаст, зачем проверять?

2022-05-03 14:41 UTC, LudwigVonChesterfield commented on code/datums/mind.dm
> +		var/datum/faction/infestation/I = create_uniq_faction(/datum/faction/infestation)
если не гарантирует, почему тут не проверяют?

2022-05-03 14:41 UTC, LudwigVonChesterfield commented on code/datums/mind.dm
> +	var/datum/faction/infestation/I = create_uniq_faction(/datum/faction/props)
мне название не очень нравится, звучит будто она всегда создаёт фракцию... даже слово "уникальную" не помогает. но `get_or_create` наверное кринжово звучало бы

2022-05-03 14:42 UTC, LudwigVonChesterfield commented on code/datums/spawners_menu/spawners.dm
> +		newname += pick(list("ti","hi","ki","ya","ta","ha","ka","ya","chi","cha","kah"))
когда-нибудь переделаю на использование звуков языка воксов

2022-05-03 14:43 UTC, LudwigVonChesterfield commented on code/datums/spawners_menu/spawners.dm
> +	vox.age = rand(5, 15) // its fucking lore
странно что не подвязано к /datum/species но не ты виноват оно так и раньше было

2022-05-03 14:44 UTC, LudwigVonChesterfield commented on code/game/gamemodes/modes_gameplays/blob/blobs/core.dm
>  	if(conglomerate) //Faction exists
зачем проверка если гарантированно создаётся

2022-05-03 14:45 UTC, LudwigVonChesterfield commented on code/datums/spawners_menu/spawners.dm
> +	ranks = list(ROLE_GHOSTLY)
надо проверять на бан на воксов

2022-05-03 14:45 UTC, LudwigVonChesterfield commented on code/game/gamemodes/roles/heist.dm
> +	required_pref = ROLE_GHOSTLY
я против

2022-05-03 14:46 UTC, LudwigVonChesterfield requested changes
надо или проверять на вайтлист или позволять банить воксов ролек

2022-05-03 14:56 UTC, LudwigVonChesterfield commented on code/modules/events/heist.dm
> +		kill()
смешно что про ето надо помнить

у нас нет функции где проверяется можно ли стартануть ивент?

2022-05-03 14:57 UTC, KIBORG04 commented on code/modules/events/heist.dm
> +		kill()
Может кстати и есть, но я копировал с блоба, а блоб кодился еще в самом начале жизни этой системы

2022-05-03 18:33 UTC, KIBORG04 commented on code/modules/events/heist.dm
> +		kill()
нету

2022-05-14 05:03 UTC, LudwigVonChesterfield approved these changes
вижу что мои комменты зарезолвали, кроме названия функции создания

ето не апрув нейтральный коммент и убрать реквест просто нельзя :sob:

2022-05-14 17:21 UTC, Sakuya-Izayoi commented on code/game/machinery/computer/vox_shuttle.dm
> +			<a href='?src=\ref[src];solars_fore_port=1' style='position: absolute; top: [world.maxy-NW_solars.y]px; left: [NW_solars.x]px;'>[X]</a>
Ну, я полагаю элементы позиционируются относительно своего верхнего левого угла вне зависимости от top или bottom 😔

2022-05-14 17:22 UTC, KIBORG04 commented on code/game/machinery/computer/vox_shuttle.dm
> +			<a href='?src=\ref[src];solars_fore_port=1' style='position: absolute; top: [world.maxy-NW_solars.y]px; left: [NW_solars.x]px;'>[X]</a>
я плох в фронте

2022-05-14 17:23 UTC, Sakuya-Izayoi commented on code/datums/mind.dm
> +	var/datum/faction/infestation/I = create_uniq_faction(/datum/faction/props)
Просто get? Или totallyGet (totally в контексте означает что функция не возвращает ошибочное состояние, а всегда завершается успешно)

2022-05-14 17:24 UTC, Sakuya-Izayoi commented on code/game/machinery/computer/vox_shuttle.dm
> +		SW_solars = pick(get_area_turfs(/area/shuttle/vox/southwest_solars, FALSE))
Мне кажется это просто нелогично

2022-05-14 17:25 UTC, KIBORG04 commented on code/game/machinery/computer/vox_shuttle.dm
> +		SW_solars = pick(get_area_turfs(/area/shuttle/vox/southwest_solars, FALSE))
Ленивая инициализация

2022-05-14 17:25 UTC, KIBORG04 commented on code/datums/mind.dm
> +	var/datum/faction/infestation/I = create_uniq_faction(/datum/faction/props)
С тоттали интереснее звучит

2022-05-14 18:02 UTC, Sakuya-Izayoi commented on code/game/machinery/computer/vox_shuttle.dm
> +		SW_solars = pick(get_area_turfs(/area/shuttle/vox/southwest_solars, FALSE))
🙄

2022-05-14 22:04 UTC, KIBORG04 commented on code/modules/events/borers.dm
> +	get_totally_faction(/datum/faction/borers)
а хотя тут выглядит странно этот тоталли

2022-05-14 22:04 UTC, KIBORG04 commented on code/modules/events/borers.dm
> +	get_totally_faction(/datum/faction/borers)
а хотя тут выглядит странно этот тоталли

2022-05-17 18:44 UTC, merged