респрайт обопа
TauCetiStation/TauCetiClassic pull request #9184
Opened 2022-04-19 21:00 UTC by AndroBetel

## Описание изменений
![image](https://user-images.githubusercontent.com/44546836/164093599-4010d4be-791c-460f-b91f-697ab0ff8707.png)
дедссекретом перерисовал обоп в отсылку на рогалик ядерный трон, теперь копы выглядят не просто как офицеры в синем шмоте

копы спавнятся с особым секхейлером сразу же, в связи с чем отпадает нужда лутать один такой с базы
шлем копа 3 уровня чуть-чуть крепче чем у 2
коп-инспектор получил аблятивную броню с небольшой защитой от остальных видов урона
## Почему и что этот ПР улучшит
красоту и стайл
## Авторство
DedYarick
## Чеинжлог
:cl:DedYarick
- image: ОБОП позаимствовал свой фешн у межвселенского полицейского департамента.

2022-04-19 21:00 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2022-04-19 21:05 UTC, KIBORG04 commented
Файл лишний
![image](https://user-images.githubusercontent.com/26389417/164097486-312e887a-babe-495c-9094-29bb1ed1de1e.png)

2022-04-19 21:06 UTC, KIBORG04 commented on code/modules/clothing/suits/armor.dm
> +	desc = "A set of armor used by special weapons and tactics units of Organized Crimes Department. Justice will be served."
Здесь у тебя аббревиатура расшифрована, а в других местах OCD просто. Соблюди все в одном стиле

2022-04-19 21:07 UTC, AndroBetel commented on code/modules/clothing/suits/armor.dm
> +	desc = "A set of armor used by special weapons and tactics units of Organized Crimes Department. Justice will be served."
это для внушения, типа самый мощный чел из всех, нужно написать его хозяев полностью

2022-04-20 03:57 UTC, UDaV73rus requested changes
Надо бы уменьшить итем головы, остальном всё ок

2022-04-20 11:33 UTC, Akellazp commented
🤡

2022-04-20 17:13 UTC, KIBORG04 commented on code/game/gamemodes/modes_gameplays/families/outfit.dm
> +		new /obj/item/weapon/handcuffs(src)
а зачем? Нереальное падение производительности

2022-04-20 17:15 UTC, AndroBetel commented on code/game/gamemodes/modes_gameplays/families/outfit.dm
> +		new /obj/item/weapon/handcuffs(src)
потому что раньше некрасиво было в поясе, магазин-наручники-магазин-наручники-магазин-наручники, а щас магазинх3 наручниких3

2022-04-20 17:16 UTC, KIBORG04 commented on code/game/gamemodes/modes_gameplays/families/outfit.dm
> +		new /obj/item/weapon/handcuffs(src)
пипец вы

2022-04-20 22:22 UTC, UDaV73rus approved these changes

2022-04-21 09:48 UTC, Sakuya-Izayoi commented on code/game/gamemodes/modes_gameplays/families/outfit.dm
> +		new /obj/item/weapon/handcuffs(src)
starts_with вообще для такого есть 🤔

2022-04-22 17:56 UTC, KIBORG04 commented on code/game/gamemodes/modes_gameplays/families/outfit.dm
> +		new /obj/item/weapon/handcuffs(src)
Это приказ или.. ?

2022-04-22 17:58 UTC, Sakuya-Izayoi commented on code/game/gamemodes/modes_gameplays/families/outfit.dm
> +		new /obj/item/weapon/handcuffs(src)
Ну, если переделывать, то весь файл. Просто у нас вроде даже был когда-то ПР про общий переход на starts_with, а тут опять. 😔

2022-04-22 18:16 UTC, AndroBetel commented
всё мерж

2022-04-22 19:18 UTC, merged

2022-04-23 02:27 UTC, WatlerJe commented
Блин, а где про срачи "Раньше было лучше" и "Нереалистично, слишком мультяшно" почитать можно?