Фикс терминаторов с руками из блюспейса
TauCetiStation/TauCetiClassic pull request #9191
Opened 2022-04-21 15:14 UTC by KIBORG04

## Описание изменений

fix #9190

## Почему и что этот ПР улучшит

## Авторство

## Чеинжлог
:cl:
 - fix: Больше нельзя накачать руки до состояния "не чувствую урон?

2022-04-21 15:14 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2022-04-22 12:46 UTC, LudwigVonChesterfield commented on code/modules/unarmed_combat/combat_combo.dm
> +	var/cap = victim.get_max_pumped(H.get_targetzone()) + 20
суть как раз таки была в том, чтобы получить накачанность моба текущую, и иметь возможность накачаться до текущей + 20

проблема в том что почему-то если передаёшь порог накачки - то игнорируется физически максимально возможный порог, так быть не должно. я думаю надо поменять функцию adjust_pumped, а не тут

2022-04-22 16:58 UTC, LudwigVonChesterfield requested changes
то что adjust_pumped позволяет игнорировать кап конечности - ошибка.

думаю нужно соответственно исправлять adjust_pumped, а не комбухи.

2022-04-22 17:29 UTC, KIBORG04 commented on code/modules/unarmed_combat/combat_combo.dm
> +	var/cap = victim.get_max_pumped(H.get_targetzone()) + 20
так хочешь?

2022-04-22 17:42 UTC, LudwigVonChesterfield approved these changes

2022-04-22 18:06 UTC, merged