Твик неиспользуемой фичи с наручниками
TauCetiStation/TauCetiClassic pull request #9210
Opened 2022-04-25 21:59 UTC by Deahaka

## Описание изменений
Скролил код и нашёл фичу с разрезанием наручников кусачками. Но с текущими условиями для юзания и фактом что любые наручники снимаются любым человеком за 4 секунды, фича никому не нужна.
Принимаем во внимание что СБ на 40% быстрее арестовывает, так как у них есть скиллы с бафом, почему бы не дать противовес этому в виде такого твика?
## Почему и что этот ПР улучшит
Боланс и геймплей
## Авторство

## Чеинжлог
:cl: Deahaka
 - tweak: Любые наручники могут быть срезаны кусачками.

2022-04-25 21:59 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2022-04-26 09:24 UTC, Sakuya-Izayoi commented on code/game/objects/items/weapons/tools.dm
> +		QDEL_NULL(C.handcuffed)
правильнее будет unEquip и при успехе qdel.

2022-04-26 10:34 UTC, Pivo24 commented
Пажжи мы режем цепочку наручников кусачками?

2022-04-26 10:36 UTC, Deahaka commented
> Пажжи мы режем цепочку наручников кусачками?

пажжи мы отрезаем голову полностью кусачками? А ну норм, играем так 3 годика, потом вспоминаем

2022-04-26 13:45 UTC, Vysserath1 commented
Кусачки режут провода и стальные прутья. Перекусить цепочку наручников для них не сложно. Это не ножницы для бумаги

2022-04-26 15:47 UTC, KIBORG04 commented
Анти баланс. Я против. Только если добавлять такое для улучшенных кутеров.

2022-04-26 16:06 UTC, Mercurialaste commented
> вуху веселая игра 2 минуты афкшишь чтобы вылезти вуху веселая игра 30 секунд ждешь чтобы проебаться в 9 случаях из 10

Настолько же веселая, как и в первом варианте с 100% шансом за 2 минуты.
30 секунд для примера. При желании можно поставить хоть 10.

_(И это разве проблема кода, то что кукла оказалась в наручниках?)_

2022-04-26 16:09 UTC, AndroBetel commented
no comments

2022-04-26 17:38 UTC, Vysserath1 commented
Если вылезать из наручников с включенным хармом, то кидает боль + брут на руки (вывихнул/сломал большие пальцы), но прогресс идет быстрее

А так сделать чтоб срезание наручников шло не моментально, а прогрессбаром на пару секунд (по длительности чуть быстрее времени снятия)

2022-04-26 17:49 UTC, Pivo24 commented
Да втф, цепь не режется блин кусачками, они не гигантские секаторы для металла (как это правильно называлось?), они кусачки

Голово-кусачки пофиксили, к передразниваниям выше - то бишь да, кусачками голову теперь не отпиливают

Хотя с другой стороны вспоминается что те же решётки из металла нормально режем...

аэээээээээээээээээээээээээээээээээээээээ

2022-04-26 18:31 UTC, Deahaka commented
> Да втф, цепь не режется блин кусачками, они не гигантские секаторы для металла (как это правильно называлось?), они кусачки
> 
Игровая условность. НТ экономит на наручниках, по-этому их легко срезать. Логика не тронута, игроки получили геймплей

2022-04-29 10:30 UTC, Deahaka commented
Поставил унеквип, добавил уполовиненную задержку на разрезание.

2022-04-29 10:34 UTC, Sakuya-Izayoi requested changes

2022-04-29 10:34 UTC, Sakuya-Izayoi commented on code/game/objects/items/weapons/tools.dm
> +		if(user.unEquip(cuffs) && do_after(user, 2 SECONDS, target = C))
Use do_mob, not do_after

2022-04-29 10:34 UTC, Sakuya-Izayoi commented on code/game/objects/items/weapons/tools.dm
> +		var/obj/item/weapon/handcuffs/cuffs
cuffs = null
А тебе надо в эту переменную записать конкретные наручники надетые на чувака

2022-04-29 10:34 UTC, Sakuya-Izayoi commented on code/game/objects/items/weapons/tools.dm
>  			QDEL_NULL(C.handcuffed)
Здесь ты не поменял C.handcuffed на cuffs

2022-04-29 11:06 UTC, Deahaka commented
Полагаю, доведено до ума теперь

2022-04-30 15:42 UTC, Sakuya-Izayoi commented on code/game/objects/items/weapons/tools.dm
> +		C.update_inv_handcuffed()
```suggestion
				if(C.buckled && C.buckled.buckle_require_restraints)
					C.buckled.unbuckle_mob()
				C.update_inv_handcuffed()
```

2022-04-30 16:09 UTC, KIBORG04 commented on code/game/objects/items/weapons/tools.dm
> +		C.update_inv_handcuffed()
Это все?

2022-04-30 16:10 UTC, KIBORG04 commented on code/game/objects/items/weapons/tools.dm
> +				C.update_inv_handcuffed()
```suggestion
			if(C.buckled && C.buckled.buckle_require_restraints)
				C.buckled.unbuckle_mob()
			C.update_inv_handcuffed()
```

2022-04-30 16:27 UTC, merged