Удаляет хайперзин окончательно
TauCetiStation/TauCetiClassic pull request #9226
Opened 2022-04-30 22:42 UTC by simb11

## Описание изменений
Удаляет хайперзин отовсюду и замедление из-за вещей в руках за компанию.
Нюка коле оставил фишку гиперцина, но немного усложнил рецепт.
Стимпаки теперь просто лечат обычный урон. Стимуляторы(которые в боевых аптечках) теперь не калечат и ускоряют, а неплохо так лечат урон болеурон вместе с обычным уроном. Адреналин имплант вводит мед наноботов вместо гипера.
Вирус из вирусологии теперь вводит в тело стимуляторы вместо хуперзина.
А ещё немного повышена скорость передвижения в риге шахтёра(чуть быстрее рига сб).
Вродь всё
## Почему и что этот ПР улучшит
Зачем-то в игру добавили реагент который нивелирует 80% замедлений, его вроде как хотели убрать, починить и вернуть, но что-то не задалось и уже как полгода этот реагент не существует в химии, но существует в остальных легкодоступных местах, этот пр фиксит данную проблему.
А ещё почему то вещи в руках замедляют, из-за чего мили боевка без гиперцина превращается в самоубийство.
## Авторство
## Чеинжлог
:cl: Simbaka
- experiment: Большие вещи в руках не снижают скорость передвижения.
- rscdel: Гиперцин больше нигде не достать.
- tweak: Изменено содержимое всяких стимуляторов и стимпаков, они теперь лечат урон.

2022-04-30 22:42 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2022-04-30 23:30 UTC, Deahaka commented
А почему он проблема то, что его удалять теперь надо отовсюду? Убирали по очевидно какой причине и эффект получился такой как и заказывали. Я понимаю удалять замедление с вещей, которое гипер сейчас снижает, но что гипер то толку удалять?
И ещё, там вроде большое колличество археологов плакала, может кроме шахтерского рига снизить замедло и им?

2022-05-01 03:45 UTC, DarthSidiousPalpatine commented
> А почему он проблема то, что его удалять теперь надо отовсюду? Убирали по очевидно какой причине и эффект получился такой как и заказывали. Я понимаю удалять замедление с вещей, которое гипер сейчас снижает, но что гипер то толку удалять? И ещё, там вроде большое колличество археологов плакала, может кроме шахтерского рига снизить замедло и им?
> 
> Upd. Хотя если не будет вещей к которым желателен гипер, например риги с 0 скорости, то впринципе некуда будет гипер применять и выпилить будет логично.

Не монимаю проблемы. Челики могут в качалке посидеть 3-4 минуты и вкачать себе ноги

2022-05-01 06:25 UTC, simb11 commented
> И ещё, там вроде большое колличество археологов плакала, может кроме шахтерского рига снизить замедло и им?
> 

Куда им ещё сильнее снижать? У них и так 0.2 слоудовна( если что, у  рига СМО столько же) .

2022-05-01 10:11 UTC, Sakuya-Izayoi commented
Так чё реально какие-то проблемы из-за гиперцина? Я сколько играл последнее время вообще ничего не слышал про гиперцин

2022-05-01 11:05 UTC, simb11 commented
Гиперцин чуть ли не каждый раунд с ксенами или войной лутают, всем же хочеца побегать в ригах. Ну и это вроде не сложно сделать, нужно только карту у карготеха отобрать и иметь 2000 очков в консоли заказов.

2022-05-01 19:01 UTC, TauKitty commented
Этот запрос на извлечение был упомянут в **Tau Ceti Station Forum**. Там могут быть соответствующие подробности:

https://forum.taucetistation.org/t/golosovanie-udalenie-hiperzina-i-ne-tolko/33244/1

2022-05-04 05:57 UTC, simb11 commented
я считаю это успех
![image](https://user-images.githubusercontent.com/84613249/166629110-c1a975cd-d8fa-4047-bea7-f947f4c41dee.png)
Кидайте в тест мердж, пусть игроки побегают, попробуют и, возможно, изменят своё мнение

2022-05-04 21:27 UTC, Sakuya-Izayoi commented on code/modules/mob/living/simple_animal/borer.dm
> +	var/chem = input("Select a chemical to secrete.", "Chemicals") as null|anything in list("bicaridine","tramadol","alkysine")
ну хотя бы для бореров мог бы оставить... для кооперации

2022-05-04 21:27 UTC, Sakuya-Izayoi commented on code/modules/reagents/Chemistry-Recipes.dm
> +	required_reagents = list("uranium" = 1, "cola" = 6, "radium" = 1)
бредовое "усложнение". если игрок может достать уран, радий для него достать вряд ли будет проблемой. ну и пропорции не сохранены...

2022-05-04 21:27 UTC, Sakuya-Izayoi commented on code/modules/reagents/reagent_containers/food/snacks.dm
> +	list_reagents = list("protein" = 12, "vodka" = 5, "vitamin" = 2)
сюда можно было бы стимуляторы закинуть

2022-05-04 21:27 UTC, Sakuya-Izayoi commented on code/modules/reagents/reagent_containers/pill.dm
> -	reagents.add_reagent("hyperzine", 5)
прикол этой таблетки в том что под ней просыпаешься от станов и бегаешь, а не умираешь от токсидемеджа. либо совсем удалил бы, либо накинул бы стимуляторов.

2022-05-05 06:14 UTC, simb11 commented on code/modules/mob/living/simple_animal/borer.dm
> +	var/chem = input("Select a chemical to secrete.", "Chemicals") as null|anything in list("bicaridine","tramadol","alkysine")
Дал им нюка колу.

2022-05-05 06:17 UTC, simb11 commented on code/modules/reagents/Chemistry-Recipes.dm
> +	required_reagents = list("uranium" = 1, "cola" = 6, "radium" = 1)
А как рецепт усложнить? Вижу как многие бармены даже сейчас не могут сделать колу, ведь шахтёры просто плюют на них.

2022-05-05 06:28 UTC, Sakuya-Izayoi commented on code/modules/reagents/Chemistry-Recipes.dm
> +	required_reagents = list("uranium" = 1, "cola" = 6, "radium" = 1)
Ну нюка-колой то не бармен заниматься будет, а опытный плеер какой-нить.

2022-05-05 06:38 UTC, simb11 commented on code/modules/reagents/Chemistry-Recipes.dm
> +	required_reagents = list("uranium" = 1, "cola" = 6, "radium" = 1)
Ну, если какому-нибудь офицерику дадут уран(а шахтёры даже обычные стимпаки не всегда дают), радиум и он принесёт это всё бармену, то он молодец. Раз он смог договориться с химиком и шахтёром, то и наградить его волшебным напитком не жалко.

2022-05-05 17:25 UTC, Sakuya-Izayoi commented on code/modules/reagents/Chemistry-Recipes.dm
> +	required_reagents = list("uranium" = 1, "cola" = 6, "radium" = 1)
я к тому что скорее усложнять вообще не надо.

2022-05-05 21:27 UTC, simb11 commented on code/modules/reagents/Chemistry-Recipes.dm
> +	required_reagents = list("uranium" = 1, "cola" = 6, "radium" = 1)
вернул как было.

2022-05-08 04:46 UTC, Sakuya-Izayoi approved these changes
наверное и так нормально. посмотрим как космонавтики будут обдалбываться нюка колой.

2022-05-15 19:25 UTC, simb11 commented
ну что там?

2022-05-15 22:58 UTC, KIBORG04 commented
Хз

2022-05-17 08:09 UTC, Follint commented
Новые стимпаки убивают таяр. Остальным вроде это может показаться плюсом, но, это крайне не очевидно и весьма опасно. Не считал, сколько бёрна тикает, но, применение стимпака для побега от моба, от которого уже огреб или даже порвал костюм - почти смерть без лепоразина.
Плюс, Advanced Stimpack и такое из шахтерского фабрикатора все-еще содержат гиперцин.

2022-05-17 08:26 UTC, Mercurialaste commented
> Новые стимпаки убивают таяр. Остальным вроде это может показаться плюсом, но, это крайне не очевидно и весьма опасно. Не считал, сколько бёрна тикает, но, применение стимпака для побега от моба, от которого уже огреб или даже порвал костюм - почти смерть без лепоразина. Плюс, Advanced Stimpack и такое из шахтерского фабрикатора все-еще содержат гиперцин. Вижу, что не должны, но, слипер сообщает о гиперцине, да и мувспид в риге дается.

Можешь подсказать, какой именно реагент делает больно мохнатым?

2022-05-17 08:29 UTC, Mercurialaste commented
> ну что там?

Мб перераспределить количество трика и кофе? 2 унции трика толком ничего не вылечат, а кофе толком не дает сытости. Хотя бы 5 унций трика уже было бы неплохо, тк лечит ~23 урона по всему телу. Учитывая новый метаболизм, лечит медленно из-за инапровалина и немного медленне из-за кофе. *(В теории, можно носить с собой шприц с атокстом и колоть его вместе с стимпаком, но это такое себе...)*

2022-05-17 10:04 UTC, Follint commented
> 

Подозрение на кофе. Горячий шоколад тоже повышает температуру тела и жжет таяр, а если скушать обычный дошик и выпить кофе тоже будет бёрн, притом, сильный. Слипер в таком случае говорит, что в теле Spicy Ramen. Я грешу на кофе.

2022-05-17 10:09 UTC, simb11 commented
я конечно всё понимаю но этот пр ещё не замержили и то что написано выше вообще к данному пру не относится.

2022-05-17 18:56 UTC, KIBORG04 commented
А черт, ТМа не будет до мержа https://github.com/TauCetiStation/TauCetiClassic/pull/9132

2022-05-24 15:28 UTC, Mercurialaste commented
> Кто-то заметил?

Из того что я наблюдаю, мало кто. 
_(Про гипер уже вроде почти все забыли... Слезаем с зависимости, так сказать.)_

2022-06-09 14:07 UTC, KIBORG04 commented on code/game/objects/items/weapons/implants/implant.dm
> +	imp_in.reagents.add_reagent("tricordrazine", 20)
А это тут при чем? Как вообще ПР с удалением хайперзина стал нерфом хз чего хз зачем

2022-06-09 14:11 UTC, simb11 commented on code/game/objects/items/weapons/implants/implant.dm
> +	imp_in.reagents.add_reagent("tricordrazine", 20)
так это адрик, я ему дал наноботов вместо гипера, но как оказалось, наноботы слишком ебанутые и лечат овердофига урона буквально за пару секунд и потому заменил их на делайт и трик

2022-06-26 23:21 UTC, volas commented
Как вы все его выпиливаете, уже бы давно просто понерфили...

2022-06-29 04:59 UTC, TheLone1y commented
Никто изменений не заметил, но игра стала значительно приятнее, может лучше мерж???

2022-07-03 11:49 UTC, volas commented on code/modules/reagents/reagent_types/Chemistry-Medicine.dm
> -/datum/reagent/hyperzine
Верни сам реагент и его механики, и я готов смержить. Ты всё равно его не выпилил полностью.

2022-07-03 11:49 UTC, volas requested changes
^

2022-07-03 12:30 UTC, kalazus commented
Т.е. убирание замедления от вещей в руках ты принимаешь?

2022-07-03 12:52 UTC, volas commented
> Т.е. убирание замедления от вещей в руках ты принимаешь?

Меня, наверное, уже достали, и я смирился (какой это уже ПР на выпил, 5? 10?). 

До какой-нибудь переработки и возвращения гиперзина, я думаю, приемлемо. К тому же мне самому не очень нравилась реализация замедления в руках, когда почему-то тащить те же вещи в сумке или pull-ом бывало быстрее.

2022-07-08 07:26 UTC, simb11 commented on code/modules/reagents/reagent_types/Chemistry-Medicine.dm
> -/datum/reagent/hyperzine
вернул

2022-07-09 07:37 UTC, merged

2023-06-19 15:36 UTC, TauKitty commented
Этот запрос на слияние был упомянут в **Tau Ceti Station Forum**. Там могут быть соответствующие подробности:

https://forum.taucetistation.org/t/obsuzhdenie-nerfy-skafandrov/39765/1