FEUER FREI!
TauCetiStation/TauCetiClassic pull request #9238
Opened 2022-05-03 15:23 UTC by DarthSidiousPalpatine

## Описание изменений
Респрайт огня от Удава

## Почему и что этот ПР улучшит
Огонь красивый, спасибо удаву

## Авторство
Удав Окружен

## Чеинжлог
:cl:
 - image: Респрайт огня от Удав Окружен

2022-05-03 16:02 UTC, KIBORG04 commented on code/modules/mob/living/carbon/human/update_icons.dm
> +		var/image/under = image('icons/mob/OnFire.dmi', "human_underlay", "layer"=-FIRE_UNDERLAYER)
мне кажется, андерлеи не так добавляются. Если кто-то решит еще какой-то оверлей придумывать на человечке, то твой андерлей перестанет быть самым нижним

2022-05-03 16:02 UTC, KIBORG04 commented on code/modules/mob/living/carbon/monkey/update_icons.dm
> +#define M_FIRE_UNDERLAYER       1
табы

2022-05-03 16:12 UTC, DarthSidiousPalpatine commented on code/modules/mob/living/carbon/human/update_icons.dm
> +		var/image/under = image('icons/mob/OnFire.dmi', "human_underlay", "layer"=-FIRE_UNDERLAYER)
Если он сделает его ниже моего - то не будет. Сделает выше - будет.

Не ко мне вопрос.

2022-05-03 16:12 UTC, DarthSidiousPalpatine commented
табы поставил

2022-05-03 16:16 UTC, UsadoSmokk approved these changes
Удав, поделись огоньком

2022-05-03 16:17 UTC, DarthSidiousPalpatine commented
чекай ссылки в пре

2022-05-03 16:33 UTC, KIBORG04 commented on code/modules/mob/living/carbon/human/update_icons.dm
> +		var/image/under = image('icons/mob/OnFire.dmi', "human_underlay", "layer"=-FIRE_UNDERLAYER)
Тебе нужен код для андерлеев

2022-05-03 16:33 UTC, DarthSidiousPalpatine commented on code/modules/mob/living/carbon/human/update_icons.dm
> +		var/image/under = image('icons/mob/OnFire.dmi', "human_underlay", "layer"=-FIRE_UNDERLAYER)
нет

2022-05-03 19:38 UTC, Bullethole commented
ссылка хрюкнула

2022-05-03 21:29 UTC, LudwigVonChesterfield commented on code/modules/mob/living/carbon/human/update_icons.dm
> +		var/image/under = image('icons/mob/OnFire.dmi', "human_underlay", "layer"=-FIRE_UNDERLAYER)
сделать чтобы это именно был underlays это довольно много чего менять пришлось бы...

2022-05-03 21:29 UTC, DarthSidiousPalpatine commented on code/modules/mob/living/carbon/human/update_icons.dm
> +		var/image/under = image('icons/mob/OnFire.dmi', "human_underlay", "layer"=-FIRE_UNDERLAYER)
А можно респрайт огня и ничего не менять?

2022-05-03 21:43 UTC, LudwigVonChesterfield commented on code/modules/mob/living/carbon/human/update_icons.dm
> +		var/image/under = image('icons/mob/OnFire.dmi', "human_underlay", "layer"=-FIRE_UNDERLAYER)
ну не врушай ты делаешь не респрайт огня а "делание огня андерлеем", при этом накладываешь оверлей который костылём маскируется под андерлей

я бы вмержил но замечание Киборга так-то резонно

2022-05-04 03:50 UTC, DarthSidiousPalpatine commented on code/modules/mob/living/carbon/human/update_icons.dm
> +		var/image/under = image('icons/mob/OnFire.dmi', "human_underlay", "layer"=-FIRE_UNDERLAYER)
типа, если у него слой ниже то это костыль андерлея? А как тогда не костыль? Использование бульёндовских андерлеев?

Я не понимаю в чём проблема использование просто низкого слоя. Это, как бы, так и должно быть, слои для этого и придуманы же.

2022-05-04 05:50 UTC, LudwigVonChesterfield commented on code/modules/mob/living/carbon/human/update_icons.dm
> +		var/image/under = image('icons/mob/OnFire.dmi', "human_underlay", "layer"=-FIRE_UNDERLAYER)
![image](https://user-images.githubusercontent.com/17705613/166628759-b94e0918-593c-4206-aec6-1d8eacd44abc.png)

на картинке самый высокий андерлей пытается рендериться выше самого низкого оверлея

2022-05-04 07:27 UTC, LudwigVonChesterfield requested changes
убери все упоминания андерлея или сделай реально андерлеем

2022-05-04 08:20 UTC, DarthSidiousPalpatine commented
Я ушёл от андерлеев и сделал просто оверлей. Всё. Спасибо за внимание и до скорого.

2022-05-04 09:36 UTC, LudwigVonChesterfield commented on code/modules/mob/living/carbon/ian/update_icons.dm
> +#define LAYERIAN_UNDERFIRE	7
?

2022-05-04 09:38 UTC, DarthSidiousPalpatine commented on code/modules/mob/living/carbon/ian/update_icons.dm
> +#define LAYERIAN_UNDERFIRE	7
ля вот это забыл,сек

2022-05-04 09:39 UTC, DarthSidiousPalpatine commented
все

2022-05-06 13:17 UTC, KIBORG04 commented on code/modules/mob/living/carbon/human/update_icons.dm
> +		overlays_standing[FIRE_LAYER_2]	= over
Хз поймешь ли картинку и связи. Если ты не заметил, а но тут леер с минусом. А значит чем больше число, тем спрайт ниже. Смотрим на название спрайта `human_underlay` и леер -1. Значит андерлей выше всего?

![image](https://user-images.githubusercontent.com/26389417/167138853-e829a20f-e600-49e7-ad24-21a0fb464be6.png)

2022-05-06 13:18 UTC, KIBORG04 commented on code/modules/mob/living/carbon/ian/update_icons.dm
> +		overlays_inv[LAYERIAN_FIRE_2] = image("icon"='icons/mob/OnFire.dmi', "icon_state"="generic_overlay", "layer"=-LAYERIAN_FIRE_2)
а здесь все четко

2022-05-06 13:18 UTC, KIBORG04 commented on code/modules/mob/living/carbon/monkey/update_icons.dm
> +		add_overlay(overlays_standing[M_FIRE_LAYER_2])
а здесь опять нет

2022-05-06 13:19 UTC, KIBORG04 commented on code/modules/mob/living/carbon/xenomorph/humanoid/update_icons.dm
> +		overlays_standing[X_FIRE_LAYER_2] = image('icons/mob/alienqueen.dmi', icon_state + "_fire", layer = X_FIRE_LAYER_2)
Здесь вообще одинаковый спрайт применяется.

2022-05-06 13:20 UTC, KIBORG04 commented on code/modules/mob/living/carbon/xenomorph/humanoid/update_icons.dm
> +		overlays_standing[X_FIRE_LAYER_2] = image(icon = 'icons/mob/OnFire.dmi', icon_state = "human_overlay", layer = X_FIRE_LAYER_2)
и опять андерлей кладется выше оверлея

2022-05-06 13:20 UTC, KIBORG04 commented on code/modules/mob/living/carbon/xenomorph/humanoid/update_icons.dm
> +		overlays_standing[X_FIRE_LAYER_2] = image(icon = 'icons/mob/OnFire.dmi', icon_state = "generic_overlay", layer = X_FIRE_LAYER_2)
как и тут

2022-05-08 19:36 UTC, LudwigVonChesterfield requested changes
то что Киборг сказал

2022-05-08 19:38 UTC, KIBORG04 commented
бля скайреты вылезли

2022-06-07 10:51 UTC, UDaV73rus commented
rip

2022-06-08 14:23 UTC, AirBlack commented
брат притормози доделай ведь крутой огонб

2022-06-23 10:18 UTC, UDaV73rus commented
rip

2022-06-27 20:27 UTC, volas commented
Даже у скайратов это быстрее доделали, как так

2022-06-27 20:45 UTC, volas commented on code/modules/mob/living/carbon/human/update_icons.dm
> +		overlays_standing[FIRE_LAYER_2]	= over
Я чет щас смотрю и не понимаю, какой смысл расписывать несколько десятков слоев дефайнами, что бы потом использовать их со знаком "-". Зачем.

2022-06-29 04:08 UTC, volas commented on code/modules/mob/living/silicon/robot/life.dm
> +	underlays.Cut()
```suggestion
```
ниже убираем и так, my bad

2022-06-29 04:20 UTC, merged