Что же делать с каргопоинтом, как же нам его делить? Отдадим... ПОКОЙНИКУ! ОТЛИЧНО! Так томуу ии быть!
TauCetiStation/TauCetiClassic pull request #9242
Opened 2022-05-03 20:14 UTC by DarthSidiousPalpatine

## Описание изменений
Карго теперь покупают и продают за кредиты своего отдела а не каргопоинты. С выручки с экспорта 10% уходит на счет станции.
Пофикшен баг с банкоматом и теперь он нормально работает и можно нормально снимать деньги своего отдела и пр.

## Почему и что этот ПР улучшит
Больше смысла деньгам
Фиксы багов это круто

## Авторство
Darth_Sidious и все все все, кто помогал в дискорде.

## Чеинжлог
 :cl:
 - rscadd: Карго теперь покупает и продаёт за деньги своего отдела. Процент с экспорта уходит на счёт станции.
 - bugfix: Пофикшен баг когда нельзя было зайти на счёт в банкомате не имея карты. Пофикшен баг когда нельзя было зайти на счёт отдела.

2022-05-03 20:14 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2022-05-03 20:18 UTC, KIBORG04 commented
> Карго теперь покупают и продают за кредиты своего отдела а не каргопоинты. 


![image](https://user-images.githubusercontent.com/26389417/166559028-2ea6bcf0-88be-4289-a926-53a7d2838afa.png)

Че-то не верится

2022-05-03 20:19 UTC, DarthSidiousPalpatine commented
> > Карго теперь покупают и продают за кредиты своего отдела а не каргопоинты.
> 
> ![image](https://user-images.githubusercontent.com/26389417/166559028-2ea6bcf0-88be-4289-a926-53a7d2838afa.png)
> 
> Че-то не верится

Ну проверь лол.

2022-05-03 20:20 UTC, KIBORG04 commented on code/modules/cargo/console.dm
> -				if(SSshuttle.points >= P.cost)
зачем эта `SSshuttle.points` перменная теперь нужна?

2022-05-03 20:23 UTC, DarthSidiousPalpatine commented on code/modules/cargo/console.dm
> -				if(SSshuttle.points >= P.cost)
могу убрать.

2022-05-03 20:25 UTC, KIBORG04 commented on code/modules/cargo/console.dm
> -				if(SSshuttle.points >= P.cost)
Должен

2022-05-03 20:26 UTC, DarthSidiousPalpatine commented on code/modules/cargo/console.dm
> -				if(SSshuttle.points >= P.cost)
готово

2022-05-03 20:36 UTC, LudwigVonChesterfield commented on code/controllers/subsystem/shuttles.dm
> +		station_account.money += round(E.total_cost * STATION_EXPORTS_FEE)
плохие формулы потому-что неточность операций и числами с плавающей запятой. надо:

```
var/tax = round(E.total_cost * STATION_EXPORTS_FEE)
station_account.money += tax
cargo_dep.money += E.total_cost - tax
```

2022-05-03 20:37 UTC, LudwigVonChesterfield commented on code/modules/cargo/console.dm
> +	var/datum/money_account/cargo_dep
нужно ли эту ссылку хранить? если нужно - то нужно её и чистить, в том числе если аккаунт удалит ГП. (советую не хранить)

2022-05-03 21:20 UTC, DarthSidiousPalpatine commented
М.Е.Р.Ж.

Забавно что на это потребовалось всего 37 строк

2022-05-03 21:20 UTC, LudwigVonChesterfield commented on code/_globalvars/station.dm
> +var/global/CARGO_EXPORT_TAX = 10
@KIBORG04 тебе норм что это глобальная переменная?

2022-05-03 21:21 UTC, DarthSidiousPalpatine commented on code/_globalvars/station.dm
> +var/global/CARGO_EXPORT_TAX = 10
А как её менять если не глобал переменная?

2022-05-03 21:21 UTC, LudwigVonChesterfield commented on code/controllers/subsystem/shuttles.dm
> +		var/tax = round(E.total_cost * CARGO_EXPORT_TAX/100)
```suggestion
		var/tax = round(E.total_cost * CARGO_EXPORT_TAX * 0.01)
```

2022-05-03 21:21 UTC, LudwigVonChesterfield commented on code/modules/economy/Accounts_DB.dm
> +	data["cargo_export_tax"] = CARGO_EXPORT_TAX
```suggestion
	data["cargo_export_tax"] = global.CARGO_EXPORT_TAX
```

2022-05-03 21:22 UTC, LudwigVonChesterfield commented on code/modules/economy/Accounts_DB.dm
> +				amount = clamp(amount, 1, 100)
```suggestion
				amount = clamp(amount, 0, 100)
```

2022-05-03 21:22 UTC, DarthSidiousPalpatine commented on code/modules/economy/Accounts_DB.dm
> +				CARGO_EXPORT_TAX = amount
эмм?

2022-05-03 21:22 UTC, LudwigVonChesterfield commented on code/controllers/subsystem/shuttles.dm
> +		var/tax = round(E.total_cost * CARGO_EXPORT_TAX * 0.01)
```suggestion
		var/tax = round(E.total_cost * global.CARGO_EXPORT_TAX * 0.01)
```

2022-05-03 21:23 UTC, LudwigVonChesterfield approved these changes
думаю норм

2022-05-03 21:25 UTC, KIBORG04 commented on code/_globalvars/station.dm
> +var/global/CARGO_EXPORT_TAX = 10
Наверное нет, мб в какую-то подсистему, но чет даже хз какую

2022-05-03 21:25 UTC, DarthSidiousPalpatine commented on code/_globalvars/station.dm
> +var/global/CARGO_EXPORT_TAX = 10
чего?

2022-05-03 21:26 UTC, KIBORG04 commented on code/_globalvars/station.dm
> +var/global/CARGO_EXPORT_TAX = 10
Терпимо короче

2022-05-04 22:45 UTC, Sakuya-Izayoi commented on code/_globalvars/station.dm
> +var/global/CARGO_EXPORT_TAX = 10
а чего капсом если это переменная

2022-05-04 22:53 UTC, Sakuya-Izayoi commented on code/_globalvars/station.dm
> +//Station fee earned when supply shuttle exports things. 0 is 0%, 1 is 100%
комментарий врет?

2022-05-04 22:53 UTC, Sakuya-Izayoi commented on code/modules/stock_market/stocks.dm
> +	if (SSshuttle && isnum(department_accounts["Cargo"].money) && (amount > 0 || department_accounts["Cargo"].money + amount > 0))
```
	isnum(department_accounts["Cargo"].money)
```
а такое может быть? и зачем чек на ссшаттл?

2022-05-05 17:24 UTC, Sakuya-Izayoi commented on code/_globalvars/station.dm
> +var/global/CARGO_EXPORT_TAX = 10
если это переменная переведи в лоуеркейс.

2022-05-05 17:24 UTC, Sakuya-Izayoi commented on code/modules/cargo/console.dm
> +					department_accounts["Cargo"].money -= P.cost
Мне не нравится что повсюду используется вот это `department_accounts["Cargo"].money`. Выглядит так будто здесь нужен геттер и сеттер конкретно для департмента карго.

2022-05-05 17:24 UTC, Sakuya-Izayoi commented on code/modules/stock_market/stocks.dm
> +	if (department_accounts["Cargo"] && (amount > 0 || department_accounts["Cargo"].money + amount > 0))
```suggestion
	if (department_accounts["Cargo"] && department_accounts["Cargo"].money + amount >= 0)
```

2022-05-06 13:23 UTC, KIBORG04 commented on code/_globalvars/station.dm
> +var/global/CARGO_EXPORT_TAX = 10
Действительно, это же не константа даже

2022-05-06 13:27 UTC, KIBORG04 commented
А кто-то вообще заметил?

2022-05-07 12:59 UTC, DarthSidiousPalpatine commented
> А кто-то вообще заметил?

Что заметил?

2022-05-08 09:00 UTC, LudwigVonChesterfield requested changes
название переменной налога надо перевести в лоуеркейс

2022-05-08 19:35 UTC, LudwigVonChesterfield approved these changes
Гетап хочет геттеры и сеттеры но я почему-то не понимаю сильно зачем если етот геттер сеттер будет в одну строчку...

2022-05-09 08:41 UTC, Sakuya-Izayoi commented
> Гетап хочет геттеры и сеттеры но я почему-то не понимаю сильно зачем если етот геттер сеттер будет в одну строчку...

Да можно хоть дефайны. Мне не нравится ["Cargo"].money.

2022-05-09 10:06 UTC, DarthSidiousPalpatine commented
Ну ладно, переделал всё на переменную SSeconomy

2022-05-09 11:39 UTC, Sakuya-Izayoi commented on code/controllers/subsystem/shuttles.dm
> +		global.cargo_account.money += E.total_cost - tax
Раз уж решил использовать SSeconomy, то почему бы в нем и не хранить ссылку на карго аккаунт?

2022-05-09 11:41 UTC, DarthSidiousPalpatine commented on code/controllers/subsystem/shuttles.dm
> +		global.cargo_account.money += E.total_cost - tax
Ну я могу хранить в нём ссылки на все аккаунты. На карго, на стейшн, на другие "закреплённые" которые понадобятся.

2022-05-09 14:21 UTC, LudwigVonChesterfield commented on code/modules/economy/economy_misc.dm
> +var/global/datum/money_account/cargo_account
аккаунты же удалять можно... зачем на них ссылки хранить...

2022-05-09 14:42 UTC, Sakuya-Izayoi commented on code/modules/economy/economy_misc.dm
> +var/global/datum/money_account/cargo_account
А что будет в том же случае с accounts["Cargo"]? Вот кстати и обоснование для геттера, он будет хендлить существование аккаунта.

2022-05-09 15:15 UTC, DarthSidiousPalpatine commented
Так это, всё же хорошо?

2022-05-10 04:41 UTC, LudwigVonChesterfield commented on code/modules/economy/Accounts_DB.dm
> +			if("change_export_tax")
возможно круто было бы если бы консоль заказов в карго в чатик анонсила "ой-йой, кто-то поменял налог с N% на M%!"

2022-05-10 05:24 UTC, DarthSidiousPalpatine commented on code/modules/economy/Accounts_DB.dm
> +			if("change_export_tax")
блен и как это сделать

2022-05-10 06:36 UTC, LudwigVonChesterfield commented on code/modules/economy/Accounts_DB.dm
> +			if("change_export_tax")
```
var/global/list/cargo_consoles = list()

ADD_TO_GLOBAL_LIST(/obj/machinery/консолька_карго)

/obj/machinery/консолька_карго/proc/announce_tax_change(old_tax, new_tax)
    visible_message("[bicon(src)] beeps, "НАЛОГ НА ЭКСПОРТ БЫЛ ИЗМЕНЁН С [old_tax]% НА [new_tax}%!")

/obj/machinery/ГП_банк_манипулятор_консоль/Topic()
    ...
    if("change_export_tax")
        for консолька in консолька_карго
            консолька.announce_tax_change(old_tax, new_tax)
```

2022-05-10 06:40 UTC, DarthSidiousPalpatine commented on code/modules/economy/Accounts_DB.dm
> +			if("change_export_tax")
Уф. Ладно, я думал мб есть какой-то способ проще, но ок.

2022-05-10 06:41 UTC, DarthSidiousPalpatine commented on code/modules/economy/Accounts_DB.dm
> +			if("change_export_tax")
Вопрос стоит ли в другом ПРе делать анонс смены налога на зп?

2022-05-10 06:46 UTC, merged

2022-05-10 06:46 UTC, LudwigVonChesterfield commented on code/modules/economy/Accounts_DB.dm
> +			if("change_export_tax")
теперь да

2023-07-23 08:59 UTC, TauKitty commented
Этот запрос на слияние был упомянут в **Tau Ceti Station Forum**. Там могут быть соответствующие подробности:

https://forum.taucetistation.org/t/fludilka-dlya-ohrenitelnyh-idej/3470/6431