Себяшка
TauCetiStation/TauCetiClassic pull request #9243
Opened 2022-05-04 07:07 UTC by DarthSidiousPalpatine

## Описание изменений
Добавлены 2 новых фотика, старый фотик и ломо фотик. Раскиданы в техах.
Добавлены фильтры на обычные фотики. Обычный фотик теперь зеркалка, полароид - выделен в отдельный фотик.

Добавлены фильтры на изображения, такие как:
ЧБ, Грейскейл, Инверсия, Сепия, Ломо, Рентген, Нудес, Старь, Полароид и др.
![image](https://user-images.githubusercontent.com/21008918/166636005-b6cdd0f0-0c4b-4a41-b8b9-d4b7109fa7d7.png)
![image](https://user-images.githubusercontent.com/21008918/166636043-d438a087-0a52-4cef-bc53-000494de3fc3.png)
![image](https://user-images.githubusercontent.com/21008918/166636031-0e8498bc-7ea0-4919-a4e8-b309f40ff52c.png)
![image](https://user-images.githubusercontent.com/21008918/166636107-c5fd55b6-34c0-4a3a-be81-5ed380933012.png)
![image](https://user-images.githubusercontent.com/21008918/166636143-722f5a82-a06d-4bbf-a430-0ccf40d5f3f3.png)
![image](https://user-images.githubusercontent.com/21008918/166636156-bc86607b-f96f-493d-a5c5-a117e5c3b704.png)
![image](https://user-images.githubusercontent.com/21008918/166636163-ccc16510-0863-4c98-bec9-e2d712d786fb.png)
![image](https://user-images.githubusercontent.com/21008918/166635979-45d600b6-2cdb-4274-aa74-89b16e02d215.png)
![image](https://user-images.githubusercontent.com/21008918/166636193-667857f6-e55a-4a8c-b95e-0623f677286a.png)

![image](https://user-images.githubusercontent.com/21008918/166636243-431417cc-2116-4e3c-ae7d-d25de6ec0651.png)

## Почему и что этот ПР улучшит
Круче фотографии, больше фотографий, вообще збс.

## Авторство
Darth_Sidious и все все все, кто помогал в дискорде.

## Чеинжлог
 :cl:
 - rscadd: Три новых фотоаппарата. Фильтры на фотоаппараты.

2022-05-04 07:07 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2022-05-04 07:24 UTC, LudwigVonChesterfield commented on code/__DEFINES/colors.dm
> +#define RENTGENE   list(0.95, 0,    0,     0, \
```suggestion
#define XRAY_COLOR   list(0.95, 0,    0,     0, \
```

2022-05-04 07:24 UTC, LudwigVonChesterfield commented on code/__DEFINES/colors.dm
> +#define NUDE   list(1.2,  0,    0,     0, \
почему если голый то больше красного

2022-05-04 07:24 UTC, LudwigVonChesterfield commented on code/__DEFINES/colors.dm
> +#define NO_EFFECT  list(1, 0, 0, 0, \
```suggestion
#define IDENTITY_COLOR  list(1, 0, 0, 0, \
```

а зачем нужна?

2022-05-04 07:25 UTC, LudwigVonChesterfield commented on code/__DEFINES/colors.dm
> +#define LOMO list(1.6,  0.1,  0.95, 0, \
подобавляй везде `_COLOR`

2022-05-04 07:25 UTC, DarthSidiousPalpatine commented on code/__DEFINES/colors.dm
> +#define NUDE   list(1.2,  0,    0,     0, \
Потому что "Красная плёнка".
Ну миф среди подростков прошлого что есть какая-то "красная плёнка", на которой все люди голые.

2022-05-04 07:25 UTC, DarthSidiousPalpatine commented on code/__DEFINES/colors.dm
> +#define NO_EFFECT  list(1, 0, 0, 0, \
нужное вместо null

2022-05-04 07:26 UTC, LudwigVonChesterfield commented on code/modules/paperwork/photography.dm
> +	var/list/effect = NO_EFFECT
чем отилчаются effect и effect_2, если ничем, то почему эффект ето не просто список

2022-05-04 07:26 UTC, DarthSidiousPalpatine commented on code/__DEFINES/colors.dm
> +#define LOMO list(1.6,  0.1,  0.95, 0, \
но это не Color

2022-05-04 07:27 UTC, DarthSidiousPalpatine commented on code/modules/paperwork/photography.dm
> +	var/list/effect = NO_EFFECT
тем что первый накладывается до виньетки а второй после. Нужен для более комплексных эффектов. Сейчас применяется только для состаривания.

2022-05-04 07:27 UTC, LudwigVonChesterfield commented on code/__DEFINES/colors.dm
> +#define NO_EFFECT  list(1, 0, 0, 0, \
или ты можешь НЕ применять матричные операции когда они ничего не делают, проверяя на нулл

2022-05-04 07:28 UTC, LudwigVonChesterfield commented on code/__DEFINES/colors.dm
> +#define LOMO list(1.6,  0.1,  0.95, 0, \
__DEFINES/colors.dm

матрицы цвета - значит дай им нужный суффикс

2022-05-04 07:28 UTC, LudwigVonChesterfield commented on code/modules/paperwork/photography.dm
> +	var/list/effect = NO_EFFECT
кринж

или так и назови переменные эффект_до_виньетки и эффект_после

или сделай нормально чтобы виньетка тоже была эффектом и в списке указывались приоритеты кто когда

```
var/list/effects = list(NUDE, VIGNETTE, BLUE)
```

2022-05-04 07:59 UTC, DarthSidiousPalpatine commented on code/modules/paperwork/photography.dm
> +	var/list/effect = NO_EFFECT
сделал

2022-05-04 10:18 UTC, LudwigVonChesterfield commented on code/__DEFINES/colors.dm
> +#define POSTERIZATION_FILTER   list(6,   -2.5, -2.5, 0, \
но ето не фильтр это цветоматрица

2022-05-04 10:19 UTC, DarthSidiousPalpatine commented on code/__DEFINES/colors.dm
> +#define POSTERIZATION_FILTER   list(6,   -2.5, -2.5, 0, \
Это фильтр на изображение всё, а не цвет.

Надо было цветоматрицей всё назвать чтоль?

2022-05-04 10:19 UTC, LudwigVonChesterfield commented on code/modules/paperwork/photography.dm
> +	var/vignette = ""
не юзается?

2022-05-04 10:19 UTC, DarthSidiousPalpatine commented on code/modules/paperwork/photography.dm
> +	var/vignette = ""
ля я же удалял.

2022-05-04 10:19 UTC, LudwigVonChesterfield commented on code/modules/paperwork/photography.dm
> +	var/filter = null
если это строка то стандартное значение должно быть `""` а не `null`

2022-05-04 10:20 UTC, LudwigVonChesterfield commented on code/modules/paperwork/photography.dm
> +	var/list/effect = null
```suggestion
	var/list/effects = null
```

2022-05-04 10:20 UTC, LudwigVonChesterfield commented on code/modules/paperwork/photography.dm
> +	if(!(filter && can_put_filter))
```suggestion
	if(!filter || !can_put_filter)
```

2022-05-04 10:21 UTC, LudwigVonChesterfield commented on code/modules/paperwork/photography.dm
> +	usr.put_in_hands(pick(contents))
1. можно вставить несколько фильтров?
2. если да почему сбрасывает все, а вытаскивается только рандомный?

2022-05-04 10:22 UTC, LudwigVonChesterfield commented on code/modules/paperwork/photography.dm
> +			if("rentgene")
дефайны?

2022-05-04 10:22 UTC, DarthSidiousPalpatine commented on code/modules/paperwork/photography.dm
> +	usr.put_in_hands(pick(contents))
нельзя вставить несколько.

2022-05-04 10:22 UTC, LudwigVonChesterfield commented on code/modules/paperwork/photography.dm
> +				if(ishuman(A))
вот бы это всё в отдельную функцию? handle_nude_filter

2022-05-04 10:22 UTC, LudwigVonChesterfield commented on code/modules/paperwork/photography.dm
> +					for(var/obj/item/organ/external/BP in H.bodyparts)
у нас точно нет способа получать каритнки конечностей не дублируя код из organ/external/update_icon?

2022-05-04 10:23 UTC, LudwigVonChesterfield commented on code/modules/paperwork/photography.dm
> +		temp.Blend(vign, ICON_OVERLAY, 1, 1)
а что если в списке не указана виньетка?

2022-05-04 10:23 UTC, LudwigVonChesterfield commented on code/modules/paperwork/photography.dm
> +			temp.MapColors(effect[1][1], effect[1][2], effect[1][3], effect[1][4], effect[1][5], effect[1][6], effect[1][7], effect[1][8], effect[1][9], effect[1][10], effect[1][11], effect[1][12], effect[1][
что за пиздец @KIBORG04

2022-05-04 10:24 UTC, LudwigVonChesterfield commented on code/modules/paperwork/photography.dm
> +	usr.put_in_hands(pick(contents))
почему достаётся рандомная вещь из камеры а не вставленный фильтр? что если в камеру как-либо засуну что-нибудь ещё... (как минимум к примеру педально...)

2022-05-04 10:26 UTC, DarthSidiousPalpatine commented on code/modules/paperwork/photography.dm
> +					for(var/obj/item/organ/external/BP in H.bodyparts)
нет

2022-05-04 10:26 UTC, DarthSidiousPalpatine commented on code/modules/paperwork/photography.dm
> +		temp.Blend(vign, ICON_OVERLAY, 1, 1)
то применяется пустое изображение

2022-05-04 10:27 UTC, DarthSidiousPalpatine commented on code/modules/paperwork/photography.dm
> +			temp.MapColors(effect[1][1], effect[1][2], effect[1][3], effect[1][4], effect[1][5], effect[1][6], effect[1][7], effect[1][8], effect[1][9], effect[1][10], effect[1][11], effect[1][12], effect[1][
Что не так? Такая херня этот МапКолорс:
https://www.byond.com/docs/ref/#/icon/proc/MapColors

2022-05-04 10:32 UTC, KIBORG04 commented on code/modules/paperwork/photography.dm
> +	var/can_put_filter = TRUE
если честно, effect и filter выглядит как какой-то обход istype`ов. У тебя же линза в фотике находится, почему бы не из самих линз и брать эффекты и применять фильтр? Тогда можно было бы 1 циклом на 1 фотку применить сразу все спец эффекты.

2022-05-04 10:33 UTC, KIBORG04 commented on code/modules/paperwork/photography.dm
> +				if(ishuman(A))
Вот это бы все в линзу бы пихнуть

2022-05-04 10:35 UTC, KIBORG04 commented on code/modules/paperwork/photography.dm
> +					for(var/obj/item/organ/external/BP in H.bodyparts)
У конечностей же есть прок, че-то типо get_sprites(), а вот с телом прям хзхз

2022-05-04 10:39 UTC, KIBORG04 commented on code/modules/paperwork/photography.dm
> +/obj/item/device/filter
Мб это назвать не фильтром, а линзой или объективом?

2022-05-04 15:06 UTC, DarthSidiousPalpatine commented
Ну кароч переделал всё

2022-05-04 21:11 UTC, Sakuya-Izayoi requested changes

2022-05-04 21:11 UTC, Sakuya-Izayoi commented on code/modules/paperwork/photography.dm
> +				temp.MapColors(arglist(F.effect[3]))
Я бы вместо списка использовал какую-то крутую структуру данных или хотя бы ассоциативный список чтобы было ясно что это за элементы списка такие потому что он очевидно не гомогенный.

2022-05-04 21:11 UTC, Sakuya-Izayoi commented on code/modules/paperwork/photography.dm
> +		user.unEquip(F)
unEquip может не выполнить действие и вернуть FALSE в таком случае.

2022-05-04 21:11 UTC, Sakuya-Izayoi commented on code/modules/paperwork/photography.dm
> +	var/effect
Почему определение линз посреди определеняи камеры?

2022-05-04 21:11 UTC, Sakuya-Izayoi commented on code/modules/paperwork/photography.dm
> +	effect = list(LOMO_FILTER, "vignette", null)
Непонятно что значат эти значения.

2022-05-04 21:11 UTC, Sakuya-Izayoi commented on code/modules/paperwork/photography.dm
> +/obj/item/device/camera/atom_init()
Непонятно почему определение коробки здесь.

2022-05-04 21:11 UTC, Sakuya-Izayoi commented on code/modules/cargo/packs.dm
> +					/obj/item/weapon/storage/box,
box of what

2022-05-04 21:11 UTC, Sakuya-Izayoi commented on code/modules/paperwork/photography.dm
> +					/obj/item/device/lense/nude)
табы для отступов, пробелы для выравнивания

2022-05-04 21:11 UTC, Sakuya-Izayoi commented on code/modules/paperwork/photography.dm
> +	item_state = "lenses_kit"
```
/obj/item/weapon/storage/box
```
???

также icon_state и item_state

2022-05-04 21:11 UTC, Sakuya-Izayoi commented on code/modules/paperwork/photography.dm
> +/obj/item/device/camera/CtrlClick(mob/user)
Я бы возвращал ..() в случае если камера не в руках чтобы ее можно было пуллить на контрол клик если она на земле.

2022-05-04 21:11 UTC, Sakuya-Izayoi commented on code/modules/paperwork/photography.dm
> +/obj/item/device/camera/lomo/CtrlClick(mob/user)
Это плохой способ запретить доставать линзы из камеры как минимум потому что эти камеры теперь нельзя пуллить на контрол клик.

2022-05-05 05:09 UTC, DarthSidiousPalpatine commented
Ну всё кароч, исправлено.

2022-05-05 05:21 UTC, Sakuya-Izayoi requested changes

2022-05-05 05:21 UTC, Sakuya-Izayoi commented on code/modules/cargo/packs.dm
> +					/obj/item/weapon/storage/box_lenses,
если это коробка то сделай ее наследником коробки

2022-05-05 05:21 UTC, Sakuya-Izayoi commented on code/modules/paperwork/photography.dm
> +/obj/item/device/camera/AltClick(mob/user)
Мне не нравится что высокоуровневый код (работа с камерой) находится в низкоуровневом проке (реакция на клик)

2022-05-05 05:21 UTC, Sakuya-Izayoi commented on code/modules/paperwork/photography.dm
> +/obj/item/device/camera/CtrlClick(mob/user)
Проблема не решена, анрезолваю.

2022-05-05 05:22 UTC, DarthSidiousPalpatine commented on code/modules/paperwork/photography.dm
> +/obj/item/device/camera/CtrlClick(mob/user)
всмысле не решена. Решена

2022-05-05 05:23 UTC, DarthSidiousPalpatine commented on code/modules/paperwork/photography.dm
> +/obj/item/device/camera/AltClick(mob/user)
всмысле. Сказали переделать с вербов на ктрл и альтклики

2022-05-05 05:36 UTC, Sakuya-Izayoi commented on code/modules/paperwork/photography.dm
> +/obj/item/device/camera/AltClick(mob/user)
все правильно, на клики. проблема в том что у тебя в проке альтклик сразу идет определение вытаскивания линзы. лучше -- из альтклика вызывать прок который называется "вытащить линзу".

2022-05-05 05:41 UTC, Sakuya-Izayoi commented on code/modules/paperwork/photography.dm
> +/obj/item/device/camera/CtrlClick(mob/user)
Я тебе в дискорде написал как сделать. Я только что слил себе твою ветку, я положил фотик на землю, жму контрол клик и из него достается линза. Жму еще раз и он не пуллится. Что значит решена?

2022-05-05 05:50 UTC, DarthSidiousPalpatine commented
Ладно, я забыл одну проверку. Теперь всё.

2022-05-05 05:54 UTC, Sakuya-Izayoi commented on code/modules/paperwork/photography.dm
> +	item_state = "lenses_kit"
анрезолваю, у коробки нет инхенда

2022-05-05 05:56 UTC, DarthSidiousPalpatine commented on code/modules/paperwork/photography.dm
> +	item_state = "lenses_kit"
теперь есть

2022-05-05 16:10 UTC, Sakuya-Izayoi commented on code/modules/paperwork/photography.dm
> +/obj/item/device/lens/nude/process_icon(atom/A)
правильнее будет поставить определение прока сразу после объявления класса которому он принадлежит

2022-05-05 16:10 UTC, Sakuya-Izayoi commented on code/modules/paperwork/photography.dm
> +	return FALSE
что значит FALSE в process_icon?

2022-05-05 16:34 UTC, DarthSidiousPalpatine commented on code/modules/paperwork/photography.dm
> +	return FALSE
Не у всех линз есть процесс айкон. У тех что есть он прописан без false

2022-05-05 16:37 UTC, Sakuya-Izayoi commented on code/modules/paperwork/photography.dm
> +	return FALSE
Буквально в следующем проке процесс айкон переопределен И возвращает FALSE в некоторых условиях. Напиши комментарий, в каких случаях **_в общем_** процесс айкон возвращает FALSE. И почему FALSE а не  null если у тебя вот буквально следующий прок обычно возвращает icon?

2022-05-09 05:11 UTC, DarthSidiousPalpatine commented
Да всё нормально блин.

2022-05-09 20:32 UTC, DarthSidiousPalpatine commented
Вот би мерж

2022-05-12 13:36 UTC, DarthSidiousPalpatine commented
Да блен за шо переименовали

2022-05-13 15:43 UTC, KIBORG04 commented on code/modules/paperwork/photography.dm
> +	return FALSE
Лучше null

2022-09-10 22:34 UTC, DarthSidiousPalpatine commented
Everything is Awesome. Никаких проблем у этого ПРа нет. Всё работает отлично!

2022-09-11 03:48 UTC, DarthSidiousPalpatine commented
Плес, можно ПР восстановить, пожалуйста?

2022-09-11 09:30 UTC, DarthSidiousPalpatine commented
Я всегда в тебя верил, Киборч

2022-09-11 09:34 UTC, DarthSidiousPalpatine commented
@Sakuya-Izayoi тут всё хорошо, плес одобри.

2022-09-11 09:48 UTC, Sakuya-Izayoi commented
> @Sakuya-Izayoi тут всё хорошо, плес одобри.

Ты даже не все замечания прочитал, а те которые прочитал молча зарезолвил. Исправляй.

2022-09-11 10:21 UTC, DarthSidiousPalpatine commented
А) Переделал на твои списки именные, чёртовы.
Б) Пулл работает как бы я ни пробовал. ОБЪЯСНИ свой порядок действий.
В) Новой карты нет в билде, она в ТМе, так что не могу добавить туда.

Г) Мерж?

2022-09-11 10:23 UTC, Sakuya-Izayoi commented on code/modules/paperwork/photography.dm
> +		base_lens = new base_lens(src)
ты в одной переменной хранишь и путь, и объект. нехорошо.

2022-09-11 10:37 UTC, DarthSidiousPalpatine commented
Сделано

2022-09-11 14:10 UTC, Tap0r commented
> Новой карты нет в билде, она в ТМе, так что не могу добавить туда.

Я сам накидаю после мержа

2022-09-13 05:14 UTC, volas requested changes

2022-09-13 05:14 UTC, volas commented on code/modules/paperwork/photography.dm
> +/obj/item/device/lens/nude/process_icon(atom/A)
какой-то слишком тяжелый для такой невинной фичи

2022-09-13 05:14 UTC, volas commented on code/modules/paperwork/photography.dm
> +				img = F.process_icon(A)
за такое вообще тапками закидывают - ты сначала вызываешь метод и проверяешь, что он что-то делает, а потом вызываешь его отдельно еще раз что бы уже записать результат

2022-09-13 05:14 UTC, volas commented on code/modules/paperwork/photography.dm
> +/obj/item/device/lens/nude/process_icon(atom/A)
Практически еще один getFlatIcon, только с фильтрами. Во первых, можно было бы экономить на getFlatIcon вызове на ххьюманах, если мы потом всё равно их пересобираем. Во вторых, скорее всего тут можно оптимизировать количество mapcolors и blend, как-то скомбинировать общие.

2022-09-14 18:31 UTC, volas commented on code/modules/paperwork/photography.dm
> +/obj/item/device/camera/AltClick(mob/user)
> всмысле. Сказали переделать с вербов на ктрл и альтклики

Вот, кто сказал, пусть теперь идёт и делает #10060. Никто не читая код сейчас сам не узнает, что у фотоаппарата есть функции на альт+клик или ктрл+клик.

2022-09-14 18:38 UTC, volas commented on code/modules/paperwork/photography.dm
> +	var/base_lens
Их еще в дестрой нужно подчистить

2022-09-14 18:41 UTC, volas commented on code/modules/paperwork/photography.dm
> +		if(contents.len)
не критично, но раз ты создал ``lens``, можно было бы их и использовать тут. И почему-то ниже подразумевается, что линз может быть несколько, но она одна

2022-09-14 18:46 UTC, volas commented
> Сделал всё что мог

почти идеально, как доделаешь мержу

2022-09-14 18:47 UTC, volas commented on code/modules/paperwork/photography.dm
> +	for(var/obj/item/device/lens/F in contents)
заметил еще, у тебя еще в нескольких местах идет обход контентсов вместо использования ``lens``, посмотри потом

2022-09-14 18:52 UTC, DarthSidiousPalpatine commented
Сделал дропконтентс, ленс = нулл и ленс вместо contents.len

2022-09-14 18:54 UTC, volas commented on code/modules/paperwork/photography.dm
>  			for(var/obj/item/device/lens/F in contents)
^

2022-09-14 18:58 UTC, DarthSidiousPalpatine commented
Неееет, за что, теперь мне обновлять билд и и на прометей пихать фотики, неееееееет!

2022-09-14 19:14 UTC, DarthSidiousPalpatine commented
Всё, фотики теперь и на прометее.

2022-09-14 19:21 UTC, volas commented on code/modules/paperwork/photography.dm
> +	if(!can_put_lens || !contents)
1

2022-09-14 19:22 UTC, volas commented on code/modules/paperwork/photography.dm
> +	if(istype(I, /obj/item/device/lens) && can_put_lens && !contents.len)
2

2022-09-14 19:22 UTC, volas commented on code/modules/paperwork/photography.dm
> +		lens = null
```suggestion
		lens = null
		qdel(lens)
```

2022-09-14 19:26 UTC, volas approved these changes

2022-09-14 19:27 UTC, DarthSidiousPalpatine commented
Ave Volas!

2022-09-14 19:27 UTC, DarthSidiousPalpatine commented
@Sakuya-Izayoi го апрув

2022-09-14 19:30 UTC, merged

2022-09-15 03:19 UTC, Tap0r commented
По всему прометею пропали фотики в некоторых местах.
![IMG_20220915_070930.jpg](https://user-images.githubusercontent.com/88531962/190305935-456b521f-5b09-4587-8f97-b7d43423c2a9.jpg)
![IMG_20220915_071528.jpg](https://user-images.githubusercontent.com/88531962/190305946-3b97bbca-28a4-4294-a7ca-d4ad80151ce3.jpg)
![IMG_20220915_071603.jpg](https://user-images.githubusercontent.com/88531962/190305955-4f3db889-2ea6-4b16-ba0e-461b37f3229e.jpg)
![IMG_20220915_071649.jpg](https://user-images.githubusercontent.com/88531962/190305962-4e9e914d-f0d3-425b-8f9f-6e1154b450fd.jpg)
Остальные карты не чекал, потом как у компа буду посмотрю.

2025-04-26 12:27 UTC, TauKitty commented
Этот запрос на слияние был упомянут в **Tau Ceti Station Forum**. Там могут быть соответствующие подробности:

https://forum.taucetistation.org/t/fludilka-chast-2/28659/44346