Бодимарки воксов
TauCetiStation/TauCetiClassic pull request #9251
Opened 2022-05-06 16:29 UTC by UsadoSmokk

## Описание изменений
Воксы получили свои татухи по лору
![image](https://user-images.githubusercontent.com/56721822/167174068-13f29a35-9295-40f5-b130-f6ac0019ba2b.png)

## Почему и что этот ПР улучшит
По факту только погружение в РоЛеПлЕй
## Авторство
я
## Чеинжлог
🆑
- rscadd: появление бодимарков у воксов

2022-05-06 16:29 UTC, TauKitty commented
###### Changelog status: :radio_button: No changelog

2022-05-06 17:22 UTC, Sakuya-Izayoi commented
В чем разница между двумя строчками чейнджлога

2022-05-06 17:28 UTC, UsadoSmokk commented
> В чем разница между двумя строчками чейнджлога

готово

2022-05-06 20:17 UTC, KIBORG04 commented on code/modules/client/preferences_savefile.dm
> +		S["rank"]    << rank
эта строчка здесь не нужна

2022-05-06 20:18 UTC, KIBORG04 commented on code/modules/mob/living/carbon/human/human_defines.dm
> +	var/rank = ""
а еще это у тебя нигде не сохраняется и не выгружается

2022-05-06 20:19 UTC, KIBORG04 commented on code/modules/mob/living/carbon/human/human_defines.dm
> +	var/rank = ""
Я хоть и не на то показал, но ты понял

2022-05-06 22:36 UTC, Akellazp commented
лучше бы удалили наконец-то таки

2022-05-06 23:18 UTC, Sakuya-Izayoi commented on code/modules/client/character menu/general.dm
> +				if("rank")
rank звувчит как что-то общее, лучше vox_rank или что-то в таком духе. вдруг у сосакеров будущего будет какой-то другой rank, а это имя префа будет занято какой-то воксофигнёй.

2022-05-06 23:43 UTC, KIBORG04 commented on code/modules/client/character menu/general.dm
> +				if("rank")
Лучше бы он расширил данных механ до всех, убрав хардкод.

2022-05-07 03:44 UTC, BenDJaminUt commented
верните старых

2022-05-11 18:32 UTC, KIBORG04 commented on code/modules/client/character menu/general.dm
> +		. += 						"<br>Rank: <a href='byond://?src=\ref[user];preference=rank;task=input'>[vox_rank]</a>"
```suggestion
		. += 						"<br>Rank: <a href='byond://?src=\ref[user];preference=vox_rank;task=input'>[vox_rank]</a>"
```

2022-05-11 18:32 UTC, KIBORG04 commented on code/modules/client/character menu/general.dm
> +				if("rank")
```suggestion
				if("vox_rank")
```

2022-05-11 18:33 UTC, KIBORG04 commented on code/modules/client/preferences.dm
> +	var/vox_rank = "Servant"                //Vox ranks
Разметка пробельная съехала

2022-05-11 18:47 UTC, KIBORG04 commented on code/modules/client/character menu/general.dm
> +					var/choice = input(user, "Please choose a vox rank.", "Rank", vox_rank) as null|anything in rank_choices + vox_rank
```suggestion
					var/choice = input(user, "Please choose a vox rank.", "Rank", vox_rank) as null|anything in rank_choices
```
тут не нужная операция

2022-05-17 18:19 UTC, KIBORG04 requested changes
ну и вроде все

2022-05-17 21:26 UTC, KIBORG04 commented on code/game/gamemodes/roles/heist.dm
> +	popup.open()
```suggestion
	popup.open()

```

2022-05-18 16:41 UTC, merged