Добавления в арсенал мага
TauCetiStation/TauCetiClassic pull request #9260
Opened 2022-05-07 16:58 UTC by Deahaka

## Описание изменений
Частично возвращены старые спрайты в игру, путём добавления новых мобов. Lusty xenomorph maid добавлена в игру. Теперь Посох Анимации за 3 поинта окупается возможностью создания контролируемых призарками-игроками существ. Два выстрела по не живому предмету создают возможность призракам захватить цель. 
Выстрел по теням ![image](https://user-images.githubusercontent.com/96499407/167264002-9ed41eb3-947a-4ea1-bd14-260f425f9d33.png)вызывает оболочку для них. Добавлены: животные, ксеноморфы, люди и киборги в качестве новых тел. 
Сразу уточняю: если создание, которое появилось в результате манипуляций мага, не имеет одну команду с ним (IC > Notes или же отсутствие значка HUD-антагониста), оно вольно свободно отыгрывать злого/доброго духа во плоти (может даже попытаться вас убить).
Выстрел Посохом по ксеноморфу, кроме Королевы, превратит ксеноморфа в горничную.
## Почему и что этот ПР улучшит
Больше контента, баланс, геймплей, а также дарит улыбки игрокам.
## Авторство
[Ebin-Halcyon](https://github.com/Ebin-Halcyon) sprite creator:
![Ebin-Halcyon (2)](https://user-images.githubusercontent.com/96499407/167263075-546f01ab-5ba4-45ba-ba30-3a9fbda24c65.png)
https://github.com/tgstation/tgstation/pull/65955
## Чеинжлог
:cl: Deahaka
 - add: В арсенал мага частично возвращён [Посох Изменения](https://wiki.taucetistation.org/Wizard#Артефакты).
 - add: В Посох Анимации добавлена возможность создания гост-ролей, попробуйте выстрелить в красного призрака или дважды по не живому предмету.

2022-05-07 16:58 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2022-05-07 17:35 UTC, KIBORG04 commented on code/modules/projectiles/projectile/magic.dm
> +/obj/item/projectile/magic/proc/wabbajack(mob/living/M)
> Больше контента, баланс, геймплей, а также дарит улыбки игрокам.

> баланс

Хуйня, которая за 1 дальнобойное попадение тебя превращает в свинью или меняет законы.

Пока не сделаешь баланс я дальше реувать не буду.
https://github.com/TauCetiStation/TauCetiClassic/pull/3896

2022-05-07 17:38 UTC, Deahaka commented on code/modules/projectiles/projectile/magic.dm
> +/obj/item/projectile/magic/proc/wabbajack(mob/living/M)
Whats wrong? В чём дизбаланс если тень станет боргом или свиньёй?

2022-05-07 17:40 UTC, KIBORG04 commented on code/modules/projectiles/projectile/magic.dm
> +/obj/item/projectile/magic/proc/wabbajack(mob/living/M)
Какая тень, оно на всех работает

2022-05-07 17:42 UTC, Deahaka commented on code/modules/projectiles/projectile/magic.dm
> +/obj/item/projectile/magic/proc/wabbajack(mob/living/M)
Да, я понял что // забыл поставить, щас

2022-05-07 17:48 UTC, Deahaka commented on code/modules/projectiles/projectile/magic.dm
> +/obj/item/projectile/magic/proc/wabbajack(mob/living/M)
Усё, теперь как надо.

2022-05-07 19:01 UTC, KIBORG04 commented
> image: Новый спрайт ксеноморфа.

И че, удали этот пункт или напиши нормально.

2022-05-07 19:02 UTC, Deahaka commented
> > image: Новый спрайт ксеноморфа.
> 
> И че, удали этот пункт или напиши нормально.

Я хз вообще надо ли писать там что-то. Моб то неиграбельный без мага. Что написать? Название уточнить или...что?

2022-05-07 19:07 UTC, KIBORG04 commented
> Сразу уточняю: если создание, которое появилось в результате манипуляций мага, не имеет одну команду с ним (IC > Notes или же отсутствие значка HUD-антагониста), оно вольно свободно отыгрывать злого/доброго духа во плоти (может даже попытаться вас убить).

Я хз зачем ты это в ПРе пишешь. Это никто не прочитает и не будет соблюдать. В целом предложение выглядит так, будто бы ты просто не можешь это закодить.

2022-05-07 19:12 UTC, Deahaka commented
> Я хз зачем ты это в ПРе пишешь. Это никто не прочитает и не будет соблюдать. В целом предложение выглядит так, будто бы ты просто не можешь это закодить.

Стаф анимации не создавал союзников раньше, значит не обязан создавать и далее. Не хочется сковывать игроков правилом о непротиводействии команде.

2022-05-07 19:15 UTC, KIBORG04 commented
Посох анимации раньше оживлял предметы. которые, блять, били всех, кроме мага, и были ботами

2022-05-07 19:16 UTC, KIBORG04 requested changes
Задумка непонятная, как и реализация.

2022-05-07 19:16 UTC, KIBORG04 commented on code/modules/projectiles/projectile/magic.dm
> +*/
Ок, соч ты не возвращаешь, тогда зачем ты закомментил?

2022-05-07 19:16 UTC, KIBORG04 commented on code/modules/projectiles/projectile/magic.dm
> +				var/beast = pick("carp","tomato","goat")
не существует причин, по которым это должны быть строки, а не типы

2022-05-07 19:16 UTC, KIBORG04 commented on code/modules/projectiles/projectile/magic.dm
> +				var/animal = pick("pig", "shadowpig", "cow")
не существует причин, по которым это должны быть строки, а не типы

2022-05-07 19:16 UTC, KIBORG04 commented on code/modules/projectiles/projectile/magic.dm
> +					if("pig")	new_mob = new /mob/living/simple_animal/pig(M.loc)
зачем нужен пиг

2022-05-07 19:16 UTC, KIBORG04 commented on code/modules/projectiles/projectile/magic.dm
> +			Robot.add_inherent_law("Вы не можете причинить вред разумному существу или бездействием допустить, чтобы ему был причинён вред.")
Ты скопипастил законы азимова, но почему-то их захардкодил.. У нас законы датумизированы, и их можно устанавливать при спавне борга, а не таким кринге.

2022-05-07 19:16 UTC, KIBORG04 commented on code/modules/projectiles/projectile/magic.dm
> +			new_mob = new /mob/living/carbon/xenomorph/humanoid/maid(M.loc)
Почему у мага есть шанс, что заспавнится не подвластная ему ебака...

2022-05-07 19:16 UTC, KIBORG04 commented on code/modules/projectiles/projectile/magic.dm
> +					if("pig")	new_mob = new /mob/living/simple_animal/pig(M.loc)
Если ты сам говоришь, что превращение из тени, то зачем таких бесполезных мобов... Ты убиваешь человека, чтобы получить помидор с 20 хп и 5 урона? Это не имеет вообще никакого смысла. Почему ты покупаешь соулстоны и этот посох, но имеешь 60% шанс, что заспавнится бесполезный алень, макака и энимал? Они вообще никак не помогут в выполнение задач, так к тому же ты им даже не выдашь рольку.

2022-05-07 19:16 UTC, KIBORG04 commented on code/modules/projectiles/projectile/magic.dm
> +		create_spawner(/datum/spawner/living/spirit_incarnate, new_mob)
Спавнер, который даже не будет создаваться, так как все таргеты имеют минд.....

2022-05-07 19:23 UTC, Deahaka commented
> Посох анимации раньше оживлял предметы. которые, блять, били всех, кроме мага, и были ботами

![2](https://user-images.githubusercontent.com/96499407/167268895-d915781d-12c2-43cb-b509-ea36697ceaaa.png)
Что-то не работает

2022-05-07 19:25 UTC, KIBORG04 commented
Ну сломали, че. можешь пофиксить. Этот фиререр должен быть для них другом. И классно, наверное, боты сковываются в правиле о противодействие

![image](https://user-images.githubusercontent.com/26389417/167268930-933b56b2-8309-4add-ad11-1ecb02f919ca.png)

2022-05-07 19:55 UTC, Zmey25 commented
Напомнить почему СОЧ выпилили?

2022-05-07 19:55 UTC, KIBORG04 commented
> Напомнить почему СОЧ выпилили?

https://github.com/TauCetiStation/TauCetiClassic/pulls?q=соч

https://github.com/TauCetiStation/TauCetiClassic/pull/3896

2022-05-08 19:31 UTC, LudwigVonChesterfield commented on code/modules/projectiles/projectile/magic.dm
> +		create_spawner(/datum/spawner/living/spirit_incarnate, new_mob)
возможно хотелось добавить компонент на создание спавнера если челик ливнет из куклы?

2022-05-08 20:18 UTC, Deahaka commented
Обновил, сейчас решается вопросик по Кинг Конгу. Может его стоит вычеркнуть из списка.

2022-05-08 20:19 UTC, Deahaka commented on code/modules/projectiles/projectile/magic.dm
> +			new_mob = new /mob/living/carbon/xenomorph/humanoid/maid(M.loc)
Потому что баг я считаю фичей. Посох анимации не создаёт дружественных к магу существ, а нужен для отвлечения экипажа.

2022-05-08 20:20 UTC, Deahaka commented on code/modules/projectiles/projectile/magic.dm
> +					if("pig")	new_mob = new /mob/living/simple_animal/pig(M.loc)
Теперь призывать призраков можно без убийства игорьков.

2022-05-10 17:51 UTC, KIBORG04 commented on code/modules/projectiles/projectile/magic.dm
> +			Robot.init(/datum/ai_laws/asimov_xenophile, FALSE, global.chaplain_religion)
```suggestion
```
Ты должен передавать тайп закона в конструкторе борга

2022-05-10 17:52 UTC, KIBORG04 commented on code/modules/projectiles/projectile/magic.dm
> +				if(/mob/living/simple_animal/cow/cute_cow)					new_mob = new /mob/living/simple_animal/cow/cute_cow(M.loc)
Я почему-то думал, что так и будет.... Замени всю эту хуйню одной строчкой

2022-05-10 17:53 UTC, KIBORG04 commented on code/datums/spells/spacetime_distrortion.dm
> +					create_spawner(/datum/spawner/living/evil_shade, A)
```suggestion
				var/mob/living/simple_animal/A = new /mob/living/simple_animal/shade/evil_shade(H.loc)
				create_spawner(/datum/spawner/living/evil_shade, A)
```

2022-05-10 17:54 UTC, KIBORG04 commented on code/__DEFINES/xenomorph.dm
> +#define ALIEN_MAID          "Горничные"
пробелы в табы

2022-05-10 17:57 UTC, KIBORG04 commented
> Теперь: кроме шейдов ремесленника и божка, материал для анимации появляется в разрыве пространства мага, если в спелле перемещается не маг.

Этих шейдов можно сажать в соулстон и призывать конструктов, не убивая экипаж.

2022-05-12 10:35 UTC, Deahaka commented
Убрал захват злых духов камнем. Добавил возможность игрокам реагировать быстрее, прежде чем призраков перестреляют багом дисторшена, путём клика для вселения. Ну если и так не успеют - то уже скiл iсюе, что маг не может нажать что-нибудь ещё для защиты територии.

2022-05-13 15:45 UTC, KIBORG04 commented on code/modules/mob/living/simple_animal/shade.dm
> +	return
У тебя для этого есть спавнер, не стоит делать еще способы вселения

2022-05-13 15:47 UTC, KIBORG04 commented on code/modules/projectiles/projectile/magic.dm
> +			new_mob = pick(new /mob/living/simple_animal/hostile/carp(M.loc), new /mob/living/simple_animal/hostile/tomato/angry_tomato(M.loc), new /mob/living/simple_animal/hostile/retaliate/goat(M.loc), new
не так, убери всю инициализацию тут
```suggestion
			var/beast = pick(type, type, type, type)
			new_mob = new beast(M.loc)
```

2022-05-13 15:48 UTC, KIBORG04 commented on code/modules/projectiles/projectile/magic.dm
>  			Robot.mmi.transfer_identity(M)	//Does not transfer key/client.
```suggestion
```
Мми вроде не надо вообще делать

2022-05-14 09:17 UTC, Deahaka commented
Без ММИ из захваченного борга нельзя будет достать мозги. Вроде не проблема, если стоит всё же оставить, то скажите.

2022-05-14 19:14 UTC, KIBORG04 commented
Так откуда у шейда мозги?

2022-05-18 07:12 UTC, Deahaka commented
Перетестил всё ещё раз. Почему-то ксеноморфу удваивает все способности, причина, наверное, в трансфере скилов от духа к мобу. А вот критично то, что при юзании способности коровки выделения термопсиса, хуман может получить рантайм в [этой строчке, звучащий как bad index.](https://github.com/TauCetiStation/TauCetiClassic/blob/master/code/modules/reagents/reagent_types/Chemistry-Medicine.dm#L333)

2022-05-18 07:49 UTC, KIBORG04 commented
Можно тогда не трансферить через transfer_to, а через mob.key = client_mob.key. Тогда маенд не передастся

2022-05-19 13:30 UTC, Deahaka commented
Я тут посмотрел. Оказывается по какой-то причине божка нельзя трансформировать никак, потому и копировать скилы, дублируя алиену как раз отдельно и нет смысла. Трансфер маенда мне хочется оставить, так как можно быть частью нескольких фракций, что намного интереснее одной, либо вообще удаления роли палкой.

2022-05-19 13:47 UTC, KIBORG04 commented on code/modules/mob/living/carbon/xenomorph/humanoid/caste/maid.dm
> +	return(1 + move_delay_add + config.alien_delay)
зач резолваешь по приколу

2022-05-21 18:16 UTC, ssbugman commented on code/modules/projectiles/projectile/magic.dm
> +			new_mob = new /mob/living/carbon/xenomorph/humanoid/maid(M.loc)
> Потому что баг я считаю фичей. Посох анимации не создаёт дружественных к магу существ, а нужен для отвлечения экипажа.

Но анимированные предметы были дружественны магу.

2022-05-21 19:07 UTC, Deahaka commented on code/modules/projectiles/projectile/magic.dm
> +			new_mob = new /mob/living/carbon/xenomorph/humanoid/maid(M.loc)
Покажи ето в игре

2022-05-25 19:34 UTC, Deahaka commented
Я не хочю чтобы этот ПР никто не ревувал :crying_cat_face: 
Убрал баг, добавил добавления в фракции, убрал сомнительный спавн.

2022-05-25 19:35 UTC, Deahaka commented on code/datums/spells/spacetime_distrortion.dm
> +			if(!iswizard(H) && prob(30) && wizard_shades_list.len < 5)
надо ставить `global` к листу?

2022-05-25 19:38 UTC, KIBORG04 commented on code/datums/spells/spacetime_distrortion.dm
> +			if(!iswizard(H) && prob(30) && wizard_shades_list.len < 5)
да, и зачем < 5???

2022-05-25 19:40 UTC, Deahaka commented on code/datums/spells/spacetime_distrortion.dm
> +			if(!iswizard(H) && prob(30) && wizard_shades_list.len < 5)
чтобы не много было. Если даже один человек по приколу попрыгает то можно 7-10 призраков наспавнить. Я подумал что такое не одобрится.

2022-05-25 19:42 UTC, KIBORG04 commented on code/modules/mob/living/simple_animal/shade.dm
> +	wizard_shades_list += src
вместо этого бойлерплейт кода в ините и дестрое юзай ADD_TO_GLOBAL_LIST

2022-05-25 19:42 UTC, KIBORG04 commented on code/modules/mob/living/simple_animal/shade.dm
> +	wizard_shades_list += src
а и оно нахуй не надо впринципе, лучше счетчик тогда, а не лист.

2022-05-27 21:14 UTC, KIBORG04 commented on code/_globalvars/misc.dm
> +var/global/wizard_shades_count = 0
```suggestion

var/global/wizard_shades_count = 0
```

2022-05-27 21:16 UTC, KIBORG04 commented on code/modules/mob/living/carbon/xenomorph/humanoid/caste/maid.dm
> +	var/whitelist_items = list(/obj/item/weapon/reagent_containers/spray,
```suggestion
	var/list/whitelist_items = list(/obj/item/weapon/reagent_containers/spray,
```

2022-05-27 21:19 UTC, KIBORG04 commented on code/modules/projectiles/projectile/magic.dm
> +	..()
```suggestion
	return ..()
```
И зачем ты перенес вызов родителя?

2022-05-27 21:20 UTC, KIBORG04 commented on code/modules/projectiles/projectile/magic.dm
> +		M = wabbajack(M)
```suggestion
		var/mob/living/M = wabbajack(M)
```

2022-05-27 21:21 UTC, KIBORG04 commented on code/modules/projectiles/projectile/magic.dm
> +		if(firer)
```suggestion
		if(firer && iswizard(firer))
```

2022-05-27 21:23 UTC, KIBORG04 commented on code/modules/projectiles/projectile/magic.dm
> +			var/datum/role/wizard_apprentice/recruit = add_faction_member(federation, M, TRUE)
```suggestion
			var/datum/role/wizard_apprentice/recruit = add_faction_member(federation, M)
```
И стоит выше сделать проверку на существование фракции

2022-05-27 21:25 UTC, KIBORG04 commented on code/modules/projectiles/projectile/magic.dm
> +			new_objective.target = mage
```suggestion
			new_objective.target = firer.mind
```

2022-05-28 04:47 UTC, Deahaka commented on code/modules/projectiles/projectile/magic.dm
> +	..()
Файрер из-за этого обнулялся, а точнее переопределялся как-то на цифру 1(может это значило TRUE). С вызовом в конце всё починилось и заработало.

2022-05-28 20:05 UTC, KIBORG04 commented on code/modules/projectiles/projectile/magic.dm
> +	..()
Чего, я тебе не верю

2022-05-28 20:06 UTC, KIBORG04 commented on code/modules/projectiles/projectile/magic.dm
> +	..()
Он нигде не становится цифрой
![image](https://user-images.githubusercontent.com/26389417/170841262-011bce89-643b-4bba-bbdb-875d6eb49a5a.png)

2022-05-29 08:31 UTC, Deahaka commented on code/modules/projectiles/projectile/magic.dm
> +	..()
![Смотришь мне в глаза, сколько можно лгать? Проще самому сказать об этом.](https://user-images.githubusercontent.com/96499407/170859204-93ef3714-5dc8-4f98-8b1b-c422106cf980.png)
![Что любовь была перестрелкой душ, мне ста-а-а-ало скучно](https://user-images.githubusercontent.com/96499407/170859222-82abbb67-94cd-4f64-8202-85cda0717072.png)
![Я тебе не верю, ты сон вчерашний, который мне](https://user-images.githubusercontent.com/96499407/170859265-2e4cfd69-e7bb-4312-b479-541fe870b508.png)
![пророчит слёзы. Я тебе не верю](https://user-images.githubusercontent.com/96499407/170859282-d5c6d283-9b89-46e7-b8bd-22992729045d.png)
![Ты - снег зимы прошедшей, он давно растаял. Я тебе не верю](https://user-images.githubusercontent.com/96499407/170859304-b8d7bc23-bc5a-4d17-a83f-c459152f9491.png)

2022-05-29 09:02 UTC, KIBORG04 commented on code/modules/projectiles/projectile/magic.dm
> +	..()
Как видишь, там нулл, а не 1

2022-05-29 09:04 UTC, Deahaka commented on code/modules/projectiles/projectile/magic.dm
> +	..()
в прошлый раз было "1"

2022-05-29 09:06 UTC, Deahaka commented on code/modules/projectiles/projectile/magic.dm
> +	..()
Был рантайм `error 1.mind `

2022-05-29 09:09 UTC, KIBORG04 commented on code/modules/projectiles/projectile/magic.dm
> +	..()
Я позже посмотрю и подумаю почему так, ибо это ненормально

2022-05-29 09:11 UTC, KIBORG04 commented on code/modules/projectiles/projectile/magic.dm
> +	..()
Или сам расследуй какого хренп

2022-05-29 12:32 UTC, Deahaka commented
Ну, вроде всё.

2022-05-29 16:38 UTC, KIBORG04 commented on code/datums/spells/spacetime_distrortion.dm
> +			if(!iswizard(H) && prob(30) && global.wizard_shades_count < 5)
Мб стоит сюда добавить проверку на ученика мага тоже?

2022-05-29 16:38 UTC, KIBORG04 approved these changes

2022-05-29 17:00 UTC, Deahaka commented on code/datums/spells/spacetime_distrortion.dm
> +			if(!iswizard(H) && prob(30) && global.wizard_shades_count < 5)
Да, это можно, поставил.

2022-06-09 14:00 UTC, KIBORG04 commented on code/datums/spells/spacetime_distrortion.dm
> +			if(!iswizard(H) && iswizardapprentice(H) && prob(30) && global.wizard_shades_count < 5)
```suggestion
			if(!iswizard(H) && !iswizardapprentice(H) && prob(30) && global.wizard_shades_count < 5)
```

2022-06-09 14:03 UTC, merged