Examine не показывает пол куклы
TauCetiStation/TauCetiClassic pull request #9311
Opened 2022-05-19 16:31 UTC by KIBORG04

## Описание изменений
![image](https://user-images.githubusercontent.com/26389417/169350451-43647ea1-2546-4398-b6e1-6f56b50aa229.png)

В екзамине нету точной инфы о поле, но трейт анатома опять спасает ситуацию!

## Почему и что этот ПР улучшит
Этот ПР создаст пару смешных ситуаций, когда по кукле невозможно определить пол игроку.
Станет легче отыгрывать трапов.
Ну и наконец будет непонятно обычному игроку, какого скрелл пола перед тобой.

## Авторство

## Чеинжлог
:cl:
 - del: В Examine не видно пол персонажа.

2022-05-19 16:31 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2022-05-19 17:24 UTC, AndroBetel commented
гавно

2022-05-19 17:59 UTC, RichardJones1 commented
бедные скреллы, их теперь еще больше будут буллить

2022-05-19 21:25 UTC, Sakuya-Izayoi commented on code/modules/mob/living/carbon/human/examine.dm
> +				t_is = "is"
it для невоодушеленных, they местоимение для воодушевленных для которых местоимения для женского и мужского полов не подходят (источник: опыт потребления англоязычного контента)

2022-05-19 21:28 UTC, KIBORG04 commented on code/modules/mob/living/carbon/human/examine.dm
> +				t_is = "is"
Так было до меня, что все it, кроме мужчин и женщин.

2022-05-25 01:22 UTC, pro100kotah commented
А че сложного со скреллами?
>Подошел, взял за жопу и сказал: "Булькни".
> >Скрелл делает *laugh
> > >Дальше ты уже думаешь, отпускать ли жопу скрелла или сжать еще сильнее.

2022-05-27 20:50 UTC, KIBORG04 commented on code/modules/mob/living/carbon/human/examine.dm
> +				t_is = "is"
@Sakuya-Izayoi Так как мне сделать?

2022-05-31 22:06 UTC, LudwigVonChesterfield commented on code/modules/mob/living/carbon/human/examine.dm
> +				t_is = "is"
Гетуп право надо they

2022-05-31 22:21 UTC, KIBORG04 commented on code/modules/mob/living/carbon/human/examine.dm
> +				t_is = "is"
То есть `it's` нужно просто удалить и вообще не использовать?

2022-05-31 22:29 UTC, LudwigVonChesterfield commented on code/modules/mob/living/carbon/human/examine.dm
> +				t_is = "is"
`it's` применимо к животным, и непонятной хуйне. абдукторы, шедоулинги, скелеты, големы скорее всего `it's` в то время как всё осознанное привычное `they`

2022-05-31 22:32 UTC, KIBORG04 commented on code/modules/mob/living/carbon/human/examine.dm
> +				t_is = "is"
ну так, а разве дионы и воксы не непонятная хуйня?

2022-05-31 22:35 UTC, LudwigVonChesterfield commented on code/modules/mob/living/carbon/human/examine.dm
> +				t_is = "is"
к ним тоже можно, и к СПУ. говорю же, добавь возможность выбирать гендер и пол)

2022-06-09 13:12 UTC, KIBORG04 commented on code/modules/mob/living/carbon/human/examine.dm
> +				t_is = "is"
так что писать то бля

2022-06-09 13:13 UTC, KIBORG04 commented
Я хз как надо, я сделал что все теперь `They/Them`. Если у чела особка, то либо He, либо She, либо They

2022-06-28 13:49 UTC, volas requested changes
Лишние неудобства игрокам на ровном месте, против. 

Предлагаю сделать опционально - трейт Андрогин (не уверен как на английском, лень искать), который и будет They.

2022-06-30 06:41 UTC, BenDJaminUt commented
> Андрогин (не уверен как на английском, лень искать)

Androgyne

2022-07-19 13:41 UTC, KIBORG04 commented
Лан пофиг, трапы должны быть ущемлены

2022-07-19 13:41 UTC, closed without merging