Resprute instrumentov
TauCetiStation/TauCetiClassic pull request #9368
Opened 2022-05-28 15:15 UTC by LiLJard

## Описание изменений
Очередной респрайт инструментов
![image](https://user-images.githubusercontent.com/77955747/170831409-3d59d587-a7a2-409e-9768-fd4a1ea2c156.png)

## Почему и что этот ПР улучшит
Заменит плохое хорошим потому что я шлифовал их сто миллионов лет
## Авторство
LiJard
## Чеинжлог
🆑 
- image: респрайт инструментов

2022-05-28 15:51 UTC, NinjaPikachuska commented
А че про огнемет ни слова?

2022-05-28 15:55 UTC, Mercurialaste commented
Ключ на 9

2022-05-28 16:16 UTC, UDaV73rus commented
Дополировал что аж белыми стали

2022-05-28 17:00 UTC, LiLJard commented
>чо па агнимету

Он тоже в наборе, если тебя волнует что про него забыли. Если тебя волнует каков он, то вот.
![image](https://user-images.githubusercontent.com/77955747/170835263-5cce8db9-dbce-4d9e-a3a1-186e9d44f3f2.png)

2022-05-28 17:05 UTC, KIBORG04 commented
Чё-то оно какое-то слишком выбивающееся из стиля по гамме

2022-05-28 17:07 UTC, BiQndy commented
я думал мне одному показалось, что какое то чересчур светлое..

2022-05-28 17:09 UTC, LiLJard commented
>выбивается
 Ты хотел сказать на фоне всего остального мусора хорошо смотрится? К тому же, аптечки и прочую дрочь с этими цветами завезли и никто даже не заметил.

2022-05-28 17:13 UTC, KIBORG04 commented
Вон же белая аптечка на столе, совсем не яркая

2022-05-28 17:17 UTC, LiLJard commented
Ладно

2022-05-28 18:42 UTC, TryXAH commented
Все было бы хорошо, если бы не было так плохо
Вперед делайте только хорошо, плохо не делайте

2022-05-28 18:45 UTC, LiLJard commented
Дураки молились богу

2022-05-28 20:59 UTC, Sadmadowl commented
Чел это че. Лего?

2022-05-28 21:24 UTC, LiLJard commented
Da

2022-05-29 06:27 UTC, RichardJones1 commented
Блестит, потому что металл должен блестеть
Лайк

2022-05-29 09:46 UTC, Rahmanio commented
Лайк будет, но не очень нравится что все сварки теперь выглядят по топливу одинаковыми, а у гаечного ключа теперь нет регулятора. Лан пох, пусть так.

2022-05-29 17:07 UTC, UDaV73rus requested changes
Не по палитре, палитра в закрепах спрайт чатика
![724c60286230f0c](https://user-images.githubusercontent.com/33157992/170882489-514bdc36-87bb-4025-84a5-bd7ff529468d.png)

2022-05-29 17:35 UTC, LiLJard commented
Я думаю твое предложение - полная хуйня

2022-05-29 21:51 UTC, Paket1337 commented
Возможно я уже давно не заходил, но уже был респрайт инструментов, я уже сбился со счета сколько у нас было респрайтов респрайтов респрайтов. Зачем ЕЩЕ один то?

2022-05-29 22:49 UTC, LiLJard commented
Чтобы ты спросил епта и понял потом что можно сделать что-то, что уже было сделано лучше

2022-06-01 06:04 UTC, TauKitty commented
Этот запрос на извлечение был упомянут в **Tau Ceti Station Forum**. Там могут быть соответствующие подробности:

https://forum.taucetistation.org/t/golosovanie-nam-resprajtyat-instrumenty/33889/1

2022-06-01 08:25 UTC, BenDJaminUt commented
верните старых воксов

2022-06-01 20:53 UTC, antonkomissar commented
Vigladit' sexual'no, nado vvodit'

2022-06-23 03:20 UTC, closed without merging