Фикс багов головы
TauCetiStation/TauCetiClassic pull request #9380
Opened 2022-05-31 12:14 UTC by notkripton

## Описание изменений
Фиксит реджув когда у цели нет головы
Фиксит исчезновение ноклон трейта при отрубании головы/мозга
## Почему и что этот ПР улучшит
## Авторство
## Чеинжлог
:cl:
 - bugfix: При отращивании головы генокраду больше не накидывается неизлечимый урон.
 - bugfix: Голову и мозг больше нельзя клонировать, если целиковое тело нельзя было.

2022-06-01 08:32 UTC, BenDJaminUt commented
можно ли будет снова нормально откачивать челов с вовремя пришитой обратно головой?

2022-06-01 08:48 UTC, notkripton commented
> можно ли будет снова нормально откачивать челов с вовремя пришитой обратно головой?

Да

2022-06-01 15:32 UTC, KIBORG04 commented on code/datums/datumvars.dm
> +			BRAIN:<a href='?_src_=vars;mobToDamage=\ref[M];adjustDamage=brain'>[M.getBrainLoss()]</a>
Эм, зачем эти бесполезные изменения?

2022-06-01 15:35 UTC, KIBORG04 commented on code/modules/organs/organ_external.dm
> +					ADD_TRAIT(H.brainmob, TRAIT_NO_CLONE, GENERIC_TRAIT)
Удали это отсюда и перенеси в `/obj/item/organ/external/head/proc/transfer_identity`

2022-06-01 15:37 UTC, KIBORG04 commented on code/modules/surgery/limbs.dm
> -		target.timeofdeath = min(target.timeofdeath, world.time - DEFIB_TIME_LIMIT) // so they cannot be defibbed
а почему ты убирашь таймофдезы?

2022-06-01 20:25 UTC, notkripton commented on code/datums/datumvars.dm
> +			BRAIN:<a href='?_src_=vars;mobToDamage=\ref[M];adjustDamage=brain'>[M.getBrainLoss()]</a>
Нашел это пока искал причины бага. Как ты видишь, оно меняет лишь логическую ошибку и передает в моб моба, а не атом.
Если нужна связь измения с пром - эта штука показывает урон в ВВ, а я здесь как раз исправил баг с уроном.

2022-06-01 20:35 UTC, notkripton commented on code/modules/organs/organ_external.dm
> +					ADD_TRAIT(H.brainmob, TRAIT_NO_CLONE, GENERIC_TRAIT)
А ну да
Перенес

2022-06-01 20:49 UTC, notkripton commented on code/modules/surgery/limbs.dm
> -		target.timeofdeath = min(target.timeofdeath, world.time - DEFIB_TIME_LIMIT) // so they cannot be defibbed
Целостность игровой концепции (реалистичность?).
Тайм оф дез влияет на возможность дефибнуть тушу, а сердцу как органу не принципиально сшитая ли голова или родная - главное, чтобы сосуды были целыми, коими они будут являться хоть после сотого пересшивания.
Ну а еще коммунити опинион.

2022-06-03 17:27 UTC, KIBORG04 commented on code/datums/datumvars.dm
> +			BRAIN:<a href='?_src_=vars;mobToDamage=\ref[M];adjustDamage=brain'>[M.getBrainLoss()]</a>
Че, тут нету никакой ошибки.

2022-06-04 13:45 UTC, notkripton commented on code/datums/datumvars.dm
> +			BRAIN:<a href='?_src_=vars;mobToDamage=\ref[M];adjustDamage=brain'>[M.getBrainLoss()]</a>
Ошибка логическая не компьютерная, а логическая человеческая. Заключается в том, что заставляет бьенд в топике делать лишний даункаст и чуть-чуть снижает читаемость кода.

2022-06-04 13:46 UTC, KIBORG04 commented on code/datums/datumvars.dm
> +			BRAIN:<a href='?_src_=vars;mobToDamage=\ref[M];adjustDamage=brain'>[M.getBrainLoss()]</a>
Не думаю, что в динамической типизации это хоть как-то влияет на производительность, а то что человеческая, я согласен

2022-06-04 14:03 UTC, notkripton commented on code/datums/datumvars.dm
> +			BRAIN:<a href='?_src_=vars;mobToDamage=\ref[M];adjustDamage=brain'>[M.getBrainLoss()]</a>
Ну тогда резолв..? (((и мерж?🥺)))

2022-06-04 14:03 UTC, KIBORG04 commented on code/datums/datumvars.dm
> +			BRAIN:<a href='?_src_=vars;mobToDamage=\ref[M];adjustDamage=brain'>[M.getBrainLoss()]</a>
мерж хз, я пока не знаю на что повлияет выпил таймофдеза

2022-06-04 14:04 UTC, notkripton commented on code/datums/datumvars.dm
> +			BRAIN:<a href='?_src_=vars;mobToDamage=\ref[M];adjustDamage=brain'>[M.getBrainLoss()]</a>
На то что после пришития головы куклу можно будет дефибнуть

2022-06-04 14:06 UTC, KIBORG04 commented on code/datums/datumvars.dm
> +			BRAIN:<a href='?_src_=vars;mobToDamage=\ref[M];adjustDamage=brain'>[M.getBrainLoss()]</a>
А равзе это не специально делалось?

2022-06-04 14:06 UTC, KIBORG04 commented on code/datums/datumvars.dm
> +			BRAIN:<a href='?_src_=vars;mobToDamage=\ref[M];adjustDamage=brain'>[M.getBrainLoss()]</a>
Чтобы люди так не абузили воскрешение

2022-06-04 14:14 UTC, notkripton commented on code/datums/datumvars.dm
> +			BRAIN:<a href='?_src_=vars;mobToDamage=\ref[M];adjustDamage=brain'>[M.getBrainLoss()]</a>
Не, это делал гетап чтобы запретить медикам лечить людей с отрубленной бошкой. Типо отрубили тебе голову - значит все, конец, закрывай игру. Я ещё тогда помню делал темку на форуме где повальное большинство против этой штуки было. И потом моем пре на клон башки я планировал это откатить, но чето затянулось все и я забыл. Щас эта штука в билде как баг висит, т.к.с тем моим замерженным пром противоречит.

2022-06-04 14:15 UTC, KIBORG04 commented on code/datums/datumvars.dm
> +			BRAIN:<a href='?_src_=vars;mobToDamage=\ref[M];adjustDamage=brain'>[M.getBrainLoss()]</a>
давай тогда и гетупа позовем

2022-06-04 14:20 UTC, notkripton commented on code/datums/datumvars.dm
> +			BRAIN:<a href='?_src_=vars;mobToDamage=\ref[M];adjustDamage=brain'>[M.getBrainLoss()]</a>
Лады, вот если что ссылка на тему
 https://forum.taucetistation.org/t/vypil-klonirovaniya-golovy-i-mozga/30294?u=notkripton

2022-06-04 14:22 UTC, KIBORG04 commented on code/datums/datumvars.dm
> +			BRAIN:<a href='?_src_=vars;mobToDamage=\ref[M];adjustDamage=brain'>[M.getBrainLoss()]</a>
@Sakuya-Izayoi Тут твою фичу удаляют, че скажешь?

2022-06-04 14:22 UTC, KIBORG04 commented
@Sakuya-Izayoi Тут твою фичу удаляют, че скажешь?

2022-06-04 14:25 UTC, notkripton commented
> @Sakuya-Izayoi Тут твою фичу удаляют, че скажешь?

@Sakuya-Izayoi Если что - смотри первый ревью от киборга, там расписано как что и почему

2022-06-18 16:18 UTC, notkripton commented
@Sakuya-Izayoi

2022-06-18 16:30 UTC, Sakuya-Izayoi commented
да удаляют и удаляют так уж и быть

2022-06-26 22:12 UTC, volas commented on code/modules/mob/living/carbon/human/human_damage.dm
> +	species.create_organs(src, deleteOld = TRUE)
Кажется, тут будут теряться импланты и прочие особенности куклы

2022-06-26 22:19 UTC, volas commented on code/modules/surgery/limbs.dm
> -		target.timeofdeath = min(target.timeofdeath, world.time - DEFIB_TIME_LIMIT) // so they cannot be defibbed
Анрезолв, потому что у меня такое ощущение, что тут разные вещи. 

Своё тело и своя голова, о чем говорилось на форуме - ок. Но #8233 убирал абузы воскрешения через болванчиков, и как понимаю, ПР возвращает их обратно?

2022-07-01 11:28 UTC, volas requested changes
Вопросы выше

2022-07-07 22:14 UTC, notkripton commented on code/modules/mob/living/carbon/human/human_damage.dm
> +	species.create_organs(src, deleteOld = TRUE)
Проверил - импланты не удаляются. Еще проверил особки на всякий случай - тоже не удаляются. Пингани меня если найдешь что-то, что все-таки утрачивается

2022-07-08 06:16 UTC, volas commented on code/modules/mob/living/carbon/human/human_damage.dm
> +	species.create_organs(src, deleteOld = TRUE)
Ты проверял именно роботизированные ноги/руки?

Просто по коду ``create_organs`` я вижу удаление всего не глядя, и пересоздание органов из дефолтных списков расы ``has_organ`` и ``has_bodypart``. Без учета каких-то особенностей куклы.

2022-07-09 18:43 UTC, notkripton commented on code/modules/mob/living/carbon/human/human_damage.dm
> +	species.create_organs(src, deleteOld = TRUE)
Проверял, но думал робоконечности и раньше человеческими становились.
Сейчас попытаюсь как-нибудь исправить это (кстати интересно, что реджув ингейм используется только генокрадами, а для них такое поведение даже более логичным кажется чем регенерация роборук и робоног)

2022-07-09 19:08 UTC, Mercurialaste commented on code/modules/mob/living/carbon/human/human_damage.dm
> +	species.create_organs(src, deleteOld = TRUE)
> Проверял, но думал робоконечности и раньше человеческими становились.
> Сейчас попытаюсь как-нибудь исправить это (кстати интересно, что реджув ингейм используется только генокрадами, а для них такое поведение даже более логичным кажется чем регенерация роборук и робоног)

Реджув вроде ещё культ с своим воскрешением юзает.

2022-07-09 19:12 UTC, volas commented on code/modules/mob/living/carbon/human/human_damage.dm
> +	species.create_organs(src, deleteOld = TRUE)
С генокрадами есть идея дать экипажу пассивную возможность вычислять по записям о имплантах кукл (уже можно было бы, на самом деле, только импланты почему-то не пишутся в мед рекорды). Потому думаю момент важный.

2022-07-31 00:24 UTC, closed without merging