Удобное взаимодействие с контейнерами
TauCetiStation/TauCetiClassic pull request #9408
Opened 2022-06-03 00:34 UTC by notkripton

## Описание изменений
**Актуализация взаимодействий с контейнерами (коробками, рюкзаками) под реалии продвинутых билдов:**

https://user-images.githubusercontent.com/75007994/171761074-e3ed1683-2ae6-483c-8ba6-1fe76c9ea4b0.mp4

**А именно:**
* Добавлен хоткей **alt-click** по контейнеру для открытия его без поднимания в руки, заменяющий долгое перетаскивание на куклу.
* Из контейнеров внутри других контейнеров не вынимая их в руки теперь можно доставать/класть вещи (до третьей вложенности), то есть теперь из спасательной коробки можно вытаскивать штуки прямо на лету, не вынимая ее с рюкзака.
## Почему и что этот ПР улучшит
Удобство
## Авторство
Я, tg
## Чеинжлог
:cl:
 - tweak: Добавлен хоткей alt-click по контейнеру для открытия его без поднимания в руки.
 - tweak[link]: Из контейнеров внутри других контейнеров не вынимая их теперь можно доставать/класть вещи (до третьей вложенности).

2022-06-03 00:34 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2022-06-03 08:03 UTC, Akellazp commented
>Из контейнеров внутри других контейнеров не вынимая их теперь можно доставать/класть вещи (до третьей вложенности), то есть теперь из спасательной коробки можно вытаскивать штуки прямо на лету, не вынимая ее с рюкзака

хуита, имба

2022-06-03 08:08 UTC, BiQndy commented
а что дизлайкают то? Разве этот ПР вносит в игру что то, кроме удобства?

2022-06-03 08:11 UTC, KIBORG04 commented
Там максимум только контейнер в контейнере можно открыть, дальше уже нельзя, но тоже как бы повод задуматься. Человек с блюспейс рюкзаком получит раз в 10 больше места без ебли с вытаскиваним, но и пох же? Пушки в коробки положить нельзя, пистолеты тоже, а из робастного в коробку максимум мультитул влезет.

2022-06-03 08:49 UTC, Akellazp commented
>Пушки в коробки положить нельзя

Пушик, которые можно положить в коробки
![image](https://user-images.githubusercontent.com/47355061/171821587-374271e4-6701-43d7-9f20-ac02bbb06e89.png)

2022-06-03 08:51 UTC, Mercurialaste commented
> > Пушки в коробки положить нельзя
> 
> Пушик, которые можно положить в коробки ![image](https://user-images.githubusercontent.com/47355061/171821587-374271e4-6701-43d7-9f20-ac02bbb06e89.png)



> > Пушки в коробки положить нельзя
> 
> Пушик, которые можно положить в коробки ![image](https://user-images.githubusercontent.com/47355061/171821587-374271e4-6701-43d7-9f20-ac02bbb06e89.png)

Пушки, которые можно положить в мешок для мусора за ухом. 
![Uploading 71D1705A-188B-48DE-A8C1-3BCF18251C14.png…]()

2022-06-03 09:41 UTC, Sakuya-Izayoi commented on code/game/objects/items/weapons/storage/storage.dm
> +			var/obj/item/weapon/storage/lockbox/L = src
внезапно заблокированными могут быть не только локбоксы, но и например коробки с пробирками

2022-06-03 09:42 UTC, notkripton commented
> 
> хуита, имба

В каком месте? Если антаг может доставать с вложенной коробки, то так сможет и сбшник. Все в одинаковых условиях. 
Вообще называть сокращение вытаскивания итема с 5 кликов на 3 имбой это ультракринге. Тащи скиллом и планированием, а не задрачиванием интерфейса на 0,00001 секунду быстрее.

2022-06-03 09:44 UTC, Sakuya-Izayoi commented
Без балдепа не разобраться

2022-06-03 10:19 UTC, TheLone1y commented
Втф голос суббалансдепа что-то значит? Ладно как хотите, я считаю что этот механ нам нужен, кто-то может кудахнуть что нельзя вытаскивать предметы из ящика из сумки ведь арря! Но тогда уж удаляйте и механ просмотра, иначе то что персонаж может хоть в 5 раз засунуть что-то в другую вещь и смотреть что там очень не вписывается под аргумент выше, хоткей тоже хороший, недавно новичок в мхелпе спрашивал есть ли хоткей на открытие рюкзака, пришлось ответить нет

2022-06-03 10:32 UTC, simb11 commented
Всё ОК, единственное что не нравится, так это то что всякие гении с БС сумками и мешками смогут таскать овердофига лута.

2022-06-03 10:36 UTC, Deahaka commented
Кстати, проблемы всяких блюспесс штук не проблемы, если мы наконец пофиксим РнД.

2022-06-03 16:26 UTC, muWander commented
ГОСПОДИ СПАСИБО БОЛЬШОЕ НОТКРИПТОН!!!!!

2022-06-03 17:28 UTC, LudwigVonChesterfield requested changes
комментарий Гетапа очень валиден

2022-06-03 17:28 UTC, LudwigVonChesterfield commented on code/game/objects/items/weapons/storage/storage.dm
> +			var/obj/item/weapon/storage/lockbox/L = src
почему подобные проверки на запертость не часть прока open()?! или почему нет прока try_open() с этими проверками?!

2022-06-04 13:37 UTC, notkripton commented on code/game/objects/items/weapons/storage/storage.dm
> +			var/obj/item/weapon/storage/lockbox/L = src
Ну да, забыл про них.
Решил эту проблему добавлением прока try_open в сторейдж и перегрузкой его в тех наследниках, где логика открытия отличается (в тех, которые могут быть закрытыми).

2022-06-04 13:38 UTC, notkripton commented on code/game/objects/items/weapons/storage/storage.dm
> +			var/obj/item/weapon/storage/lockbox/L = src
> или почему нет прока try_open() с этими проверками?!

Добавил таковой. Теперь все проверки делаются через него и только в тех классах, где оно нужно.

2022-06-05 14:36 UTC, notkripton commented
> комментарий Гетапа очень валиден

Если ты про ревью - все исправлено, если про балдеп - судя по лайкам и комментариям большинство за. Если этих голосов мало пинганите их там в менторском канале в дс, тут уже новых комментов не пишут.

2022-06-08 14:44 UTC, LudwigVonChesterfield commented on code/game/objects/items/weapons/storage/storage.dm
> +	if(Adjacent(user))
учитывая наличие телекинеза грустная проверка, используй пожалуйста in_interaction_vicinity

2022-06-08 14:45 UTC, LudwigVonChesterfield approved these changes
ето не апрув, ето "не реквест ченджес". мне всё ещё не нравится возможность ковыряться в коробке в коробке

2022-06-09 09:19 UTC, notkripton commented on code/game/objects/items/weapons/storage/storage.dm
> +	if(Adjacent(user))
использовал

2022-06-09 12:41 UTC, KIBORG04 commented on code/game/objects/items/weapons/storage/visuals.dm
> +		return TRUE
```suggestion
	open(user)
	return TRUE
```

2022-06-09 12:41 UTC, KIBORG04 commented on code/game/objects/items/weapons/storage/storage.dm
> +		return FALSE
В каких вообще случаях здесь будет user = null?

2022-06-09 12:41 UTC, KIBORG04 commented on code/game/objects/items/weapons/storage/secure.dm
> +		return ..()
Корректней было бы сделать так без копипасты на проверку висинити.
```suggestion
/obj/item/weapon/storage/secure/briefcase/try_open(mob/user)
	if(locked)
		to_chat(user, "<span class='warning'>[src] is locked and cannot be opened!</span>")
		return FALSE
	return ..()
```

2022-06-09 12:41 UTC, KIBORG04 commented on code/game/objects/items/weapons/storage/secure.dm
> +		return ..()
Хотя если я не прав, то напиши. Хотя вроде все будет работать так же.

Ну и такое же можно сделать с `obj/item/weapon/storage/lockbox/try_open(mob/user)`

2022-06-09 16:41 UTC, notkripton commented on code/game/objects/items/weapons/storage/visuals.dm
> +		return TRUE
я это делал специально для читабельности кода

2022-06-09 16:48 UTC, notkripton commented on code/game/objects/items/weapons/storage/storage.dm
> +		return FALSE
Пока таковых нет, но сделано это на случай следующих поколений, ибо прок называется 'трай' и попробовать он обязан даже на нулле. Ровно также в каких-нибудь проках работы с текстом делается иф(!месседж) ретурн. На самом деле это лучше стандартизировать и либо во всех проках с обязательным аргументом говорить делать проверки, либо во всех убрать и оставить их на совести кодера.

2022-06-12 13:50 UTC, KIBORG04 commented on code/game/objects/items/weapons/storage/visuals.dm
> +		return TRUE
разве он становится читабельнее, когда есть не нужный else и доп. табы?

2022-06-12 13:51 UTC, KIBORG04 commented
> Без балдепа не разобраться

Балдеп это игроки

2022-06-12 20:27 UTC, notkripton commented on code/game/objects/items/weapons/storage/visuals.dm
> +		return TRUE
Да прок состоит то из строк пяти, на кой ризон превращать его в сплошную стену текста. Любой мимокодер должен лишь по очертанию смекнуть идею контрибутора, а елсе это есть инструмент самоописывающегося кода, лишний раз освобождающий дорогостоящие нейроны кодерского моска при чтении мусорных микро-проков типа этого, существующих лишь ради того, чтобы закостылить факт отсутствия в бьенде интерфейсов

2022-06-28 16:46 UTC, volas commented on code/game/objects/items/weapons/storage/visuals.dm
> +		return TRUE
Это про концепт раннего возврата, почитать например тут <https://medium.com/swlh/return-early-pattern-3d18a41bba8>

2022-06-28 16:48 UTC, merged