Сбор общественного мнения по завершению раунда
TauCetiStation/TauCetiClassic pull request #9410
Opened 2022-06-03 23:17 UTC by KIBORG04

## Описание изменений
Людям даются кнопки и они решают, жать или не жать. В титрах появилась инфа о средних значениях голосующих.

Вот так это все выглядит:
![image](https://user-images.githubusercontent.com/26389417/171965331-478fb65c-3184-4052-8647-c76ec610fe3e.png)

![image](https://user-images.githubusercontent.com/26389417/171965325-2fe04684-1824-4bc3-8e79-6cabf7d31b0b.png)

## Почему и что этот ПР улучшит
Можно будет делать всякие статистики и наблюдать за общим состоянием по палате

## Авторство

## Чеинжлог
:cl:
 - add: В конце раунда добавлен сбор фидбэка о разнообразных качествах игры.

2022-06-03 23:18 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2022-06-04 11:07 UTC, LudwigVonChesterfield commented on code/datums/browser.dm
> +	add_stylesheet("font-awesome.css", 'html/font-awesome/css/all.min.css') // this CSS sheet is common to all UIs
is it common to all UIs though

2022-06-04 11:08 UTC, LudwigVonChesterfield commented on code/datums/browser.dm
> +	add_stylesheet("font-awesome.css", 'html/font-awesome/css/all.min.css') // this CSS sheet is common to all UIs
```suggestion
	add_stylesheet("font-awesome.css", 'html/font-awesome/css/all.min.css')
```

2022-06-04 11:08 UTC, LudwigVonChesterfield commented on code/modules/mob/mob.dm
> +			rating = clamp(rating, 1, 5)
особо хитрые и смешные игроки могут передавать нецелочисленный рейтинг

2022-06-04 11:10 UTC, LudwigVonChesterfield commented on code/modules/statistic/rating_helper.dm
> +/datum/rating_helper
весь этот класс это какой-то неймспейс для функций...

2022-06-04 11:10 UTC, LudwigVonChesterfield commented on code/modules/statistic/rating_helper.dm
> +/datum/rating_helper
может это подсистема?

2022-06-04 11:10 UTC, LudwigVonChesterfield commented on code/modules/statistic/rating_helper.dm
> +#undef RATING_HREF
я бы предпочёл чтобы все дефайны были в самом верху, и андефайнились в самом низу файла.

@Sakuya-Izayoi что думаешь?

2022-06-04 11:12 UTC, LudwigVonChesterfield approved these changes
я абсолютно не понимаю фронтенд часть в остальном круто

2022-06-04 11:18 UTC, Sakuya-Izayoi commented on code/modules/statistic/rating_helper.dm
> +#undef RATING_HREF
я думаю сделано норм. дефайны стоит определять там где они нужны и андефайнить там где они уже не нужны. хотя если речь идет о дефайнах которые используются больше чем в одном проке их стоит дефайнить в начале.

2022-06-04 11:20 UTC, Sakuya-Izayoi commented on code/controllers/subsystem/ticker.dm
> +	return dat
![image](https://user-images.githubusercontent.com/30875884/171996780-8b2044e1-9ff5-4f55-a036-85bc512d4572.png)

тгуи компоненты можно рендерить в тгчате (according to tg cods)

2022-06-04 12:19 UTC, KIBORG04 commented on code/modules/statistic/rating_helper.dm
> +/datum/rating_helper
Хз, нужна ли подсистема, имеющая 2 публичных функции: начать сбор рейтинга, показать итоги.

2022-06-04 12:22 UTC, KIBORG04 commented on code/controllers/subsystem/ticker.dm
> +	return dat
То такие тгуи компоненты и почему они разрешают себя рендеритб в туги чате? 

А, и как я вообще буду с них получать хоть какой-то ответ и кидать хоть какую-то инфу?

2022-06-04 13:39 UTC, Sakuya-Izayoi commented on code/controllers/subsystem/ticker.dm
> +	return dat
ну, через хрефы

2022-06-04 13:42 UTC, KIBORG04 commented on code/controllers/subsystem/ticker.dm
> +	return dat
Так мне надо моба передать в компоненту. Так? А я не вижу способов это сделать кроме как через tgui_data. Где способы общения с тгчатом, кроме как ту_чат?

2022-06-29 20:24 UTC, volas commented on code/modules/statistic/rating_helper.dm
> +/datum/rating_helper
Было бы действительно лучше перенести в подсистему, или может прикрутить как-то к уже существующей vote или статистике. Кроме болтающихся в глобале переменных еще бросаются в глаза топики в контексте моба.

2022-06-29 20:25 UTC, volas commented on code/modules/statistic/rating_helper.dm
> +/datum/rating_helper
Если статистика нужна, а желания переделывать нет - скажи, может и так сойдет.

2022-06-29 20:26 UTC, volas requested changes
обсуждение выше

2022-06-29 21:03 UTC, KIBORG04 commented on code/modules/statistic/rating_helper.dm
> +/datum/rating_helper
Кроме топика моба я не нашёл подходящего, так как там тгуи чат, а голосовать должны все. Топик клиентов не подошел, так как там какое-то эхо и по два раза вызывалось.

Статистика так то нужна всегда, но я наврятли в скором времени свои пры буду доделывать

2022-07-19 13:41 UTC, KIBORG04 commented
Щас когда нибудь доделаю емае

2022-07-19 13:45 UTC, volas commented
я всё же думаю, должно быть частью системы воутов, только сделать отдельный тип воутов вставляемый в чат

2022-07-19 13:46 UTC, Sakuya-Izayoi commented
> я всё же думаю, должно быть частью системы воутов, только сделать отдельный тип воутов вставляемый в чат

может тогда все воуты вставлять в чат? эти всплывающие окошки во время игры могут навредить во время игры иногда. да еще и оно плохо обновляется, окошко это.

2022-07-19 15:01 UTC, volas commented
> может тогда все воуты вставлять в чат? эти всплывающие окошки во время игры могут навредить во время игры иногда. да еще и оно плохо обновляется, окошко это.

вот именно обновлять в чате не стоит

2022-07-29 11:00 UTC, Shootnik01 commented
Можно добавить "Вам понравились антаги/игра антагов?"

2022-08-19 04:31 UTC, volas commented
лучше переоткрыть потом

2022-10-19 19:14 UTC, KIBORG04 commented
доделайте кто-то пажожда

2023-02-10 12:15 UTC, KIBORG04 commented
Из нововведений: 
1. Это на подсистеме.
2. Чуть красивее окошко
3. Появился пункт о оценке админов

2023-02-10 12:25 UTC, KIBORG04 commented on code/controllers/subsystem/ticker.dm
> +	return dat
Я не понимаю что мне с этим делать, как передавать в компоненту данные и из нее получать.

2023-02-10 14:57 UTC, LudwigVonChesterfield commented on code/controllers/subsystem/shuttles.dm
> -				for(var/obj/effect/starspawner/S in not_world)
а?

2023-02-10 14:57 UTC, LudwigVonChesterfield commented on code/controllers/subsystem/shuttles.dm
> +				start_transit()
это как-то относится к рейтингу?

2023-02-10 14:59 UTC, LudwigVonChesterfield commented on code/modules/statistic/stat_dto.dm
> +	// map of [string, float] where float is [0..5]
может тогда уже integer?

2023-02-10 14:59 UTC, LudwigVonChesterfield approved these changes
ура возвращение самого важного пра

2023-02-10 15:01 UTC, KIBORG04 commented on code/controllers/subsystem/shuttles.dm
> +				start_transit()
Я функцию сделал и туда свою рейтинг хуйню вынес.

2023-02-10 15:02 UTC, KIBORG04 commented on code/modules/statistic/stat_dto.dm
> +	// map of [string, float] where float is [0..5]
там [0.0, 5.0], ну то есть реально флот

2023-02-10 15:26 UTC, KIBORG04 commented on code/modules/statistic/stat_dto.dm
> +	// map of [string, float] where float is [0..5]
да, так и есть, но наверное стоит добавить округление до двух знаков после запятой

2023-02-10 19:05 UTC, KIBORG04 commented
Еще один апдейт островка голосовача.

https://user-images.githubusercontent.com/26389417/218176482-7b83ab76-e07b-4e6f-ae28-e4739814c814.mp4

2023-02-10 19:06 UTC, KIBORG04 reviewed
Если по ПРу все железобетонно ок, то, пожалуйста, не мержите. Я бы хотел обновить апи своего сайта перед тем, как эта статистика появится.

2023-02-13 18:29 UTC, KIBORG04 commented
поднятие пра вверх

2023-02-18 00:27 UTC, Sakuya-Izayoi commented on code/modules/mob/mob.dm
> +		if(rating && isnum(rating) && SSrating.get_template(rating_cat) && ("[rating]" in SSrating.rating_by_icon))
можно голосовать до начала опроса / после конца опроса / в голосованиях которые не показываются игроку?

2023-02-18 00:27 UTC, Sakuya-Izayoi commented on code/modules/client/client_defines.dm
> +	var/list/my_rate
почему бы не хранить голоса в подсистеме? типа, какого черта клиент знает про какой-то там раундрейтинг

2023-02-18 00:27 UTC, Sakuya-Izayoi commented on code/controllers/subsystem/round_rating.dm
> +	if(global.player_list.len > lowpop)
```suggestion
	if(global.player_list.len < lowpop)
```

а вообще я не понял логики. если у нас лоупоп, то мы кешируем или нет? вне зависимости от ответа, вопрос зачем?

2023-02-18 00:32 UTC, LudwigVonChesterfield commented on code/controllers/subsystem/round_rating.dm
> +	if(global.player_list.len > lowpop)
это он про мой комментарий, что при маленькой выборке лучше когда все отвечают на один вопрос, а при большой когда на разные вопросы.

2023-02-18 11:46 UTC, volas commented on code/controllers/subsystem/round_rating.dm
> +	name = "Round Rating"
Аааа, зачем это делать еще одной подсистемой, когда можно было просто в воуты запихать

2023-02-18 11:55 UTC, KIBORG04 commented on code/controllers/subsystem/round_rating.dm
> +	name = "Round Rating"
Это приказ?

2023-02-18 12:12 UTC, volas commented on code/controllers/subsystem/round_rating.dm
> +	name = "Round Rating"
Я не знаю. 

Есть просто уже готовая система воутов, крайне гибкая в настройке, см. ``/datum/poll`` и саму сабсистему Vote. Там уже были решены многие абузы и баги. С твоей стороны нужно было бы добавить вариант интерфейса "в чат" (который бы мог быть полезен и другим воутам) и возможно расширить мультивоут. Но возможно это будет не так просто адаптировать.

С другой же стороны - вот эта еще одна сабсистема, во многом дублирующая уже существующие воуты и где-то хуже (например, при существующей отдельной сабсистеме результаты голоса храняться в клиенте), и потенциально в будущем потребуется и дальше копировать фичи из уже существующих воутов (вес голоса?). Но она уже у тебя написана.

Оставлю на твоё усмотрение.

2023-02-18 12:21 UTC, volas commented on code/controllers/subsystem/round_rating.dm
> +	name = "Round Rating"
Как вариант, можно взять что есть в Пр-е и пока оставить так (после ревью/багфиксов), а мерж в систему воутов когда-нибудь потом.

2023-02-18 13:03 UTC, KIBORG04 commented on code/controllers/subsystem/round_rating.dm
> +	question = "Вам сильно помешали баги?"
Например?

2023-02-18 13:06 UTC, KIBORG04 commented on code/controllers/subsystem/round_rating.dm
> +	name = "Round Rating"
Хотя, наверное все же не могу их там использовать...

2023-02-18 13:12 UTC, Sakuya-Izayoi commented on code/controllers/subsystem/round_rating.dm
> +	question = "Вам сильно помешали баги?"
```suggestion
	question = "Каково было влияние багов на раунд?"
```

```suggestion
	question = "Сильно ли мешали баги вашему раунду?"
```

2023-02-18 13:17 UTC, KIBORG04 commented on code/controllers/subsystem/round_rating.dm
> +	question = "Вам сильно помешали баги?"
Есть небольшая проблема тут. Выбор оценки в лицах. Какое мне лицо ставить, если помешали сильно, или как поввлияли? :) :| :( ?

2023-02-18 13:18 UTC, volas commented on code/controllers/subsystem/round_rating.dm
> +	question = "Вам сильно помешали баги?"
оцените вашу жопоболь от багов

2023-02-18 13:19 UTC, Sakuya-Izayoi commented on code/controllers/subsystem/round_rating.dm
> +	question = "Вам сильно помешали баги?"
если сильно помешали то грустное лицо очевидно, если баги были но настроение не сильно подпортило, то :|, а если багов не было то веселое

2023-02-18 17:48 UTC, KIBORG04 commented on code/controllers/subsystem/round_rating.dm
> +	name = "Round Rating"
Да, жесть надо адаптировать, но в https://github.com/TauCetiStation/TauCetiClassic/pull/8207 все адаптировано

2023-02-18 19:56 UTC, KIBORG04 commented on code/controllers/subsystem/round_rating.dm
> +	question = "Вам сильно помешали баги?"
ну для багов исправил, остальное с "нравится" вроде ок

2023-02-18 19:57 UTC, KIBORG04 commented on code/controllers/subsystem/round_rating.dm
> +	name = "Round Rating"
Короче, я отрефакторил на что-то похожее на минимально упрощенные /datum/pool c /datum/vote_choice. Много кринжа ушло, много абстракций появилось.

2023-02-18 21:27 UTC, Sakuya-Izayoi commented on code/controllers/subsystem/round_rating.dm
> +	question = "Вам сильно помешали баги?"
не

2023-02-18 22:28 UTC, KIBORG04 commented on code/controllers/subsystem/round_rating.dm
> +	question = "Вам сильно помешали баги?"
Да че нет то. Про "нравится" сразу две противоположные эмоции. А так как ответов больше, то чел может выбрать что-то другое

2023-02-19 15:31 UTC, LudwigVonChesterfield commented on code/controllers/subsystem/round_rating.dm
> +	question = "Сильно ли мешали баги вашему раунду?"
```suggestion
	question = "Как баги заставали вас чувствовать о раунде?"
```

хз сейчас двуяко вопрос поставлен мне кажется..

2023-02-19 16:25 UTC, volas commented on code/controllers/subsystem/round_rating.dm
> +	question = "Сильно ли мешали баги вашему раунду?"
Можете просто градацию указывать, типо "Оцените вашу жопоболь от багов, по шкале от несущественной до невыносимой"

2023-02-19 16:54 UTC, KIBORG04 commented on code/controllers/subsystem/round_rating.dm
> +	question = "Сильно ли мешали баги вашему раунду?"
Горит, болит, припекает, парит, не болит

2023-02-21 16:31 UTC, KIBORG04 commented on code/controllers/subsystem/round_rating.dm
> +	question = "Сильно ли мешали баги вашему раунду?"
Удалил вопрос вообще

2023-02-21 16:31 UTC, KIBORG04 commented
Опять сменил вопросы игрокам

2023-02-22 20:12 UTC, KIBORG04 commented
Если че, я готов к мержу, хз как вы

2023-02-23 08:05 UTC, volas commented on code/controllers/subsystem/round_rating.dm
> +		var/html = "<br><div class='rating'>"
вместо br-ок тут было бы правильнее добавить вертикальные padding/margin к .rating в css

2023-02-23 08:08 UTC, volas approved these changes
я всё еще жалею о сабсистема воутов, но уже лучше и вроде ок

2023-02-23 10:36 UTC, KIBORG04 commented on code/controllers/subsystem/round_rating.dm
> +		var/html = "<br><div class='rating'>"
Ага, готово

2023-02-23 10:43 UTC, volas commented on tgui/packages/tgui-panel/styles/goon/chat-base.scss
> +  font-size: large;
еще вместо относительных системным настройкам юзера размерам стоит использовать относительные размеру элемента, т.е. вместо large/x-large числами 1/2/3 и т.п.
Либо ``em``-ами

2023-02-23 10:44 UTC, volas commented on tgui/packages/tgui-panel/styles/goon/chat-base.scss
> +  font-size: large;
иначе настройки размеров текста в чате будут работать не корректно тут, или системные настройки юзера смогут всё сломать

2023-02-23 11:11 UTC, KIBORG04 commented on tgui/packages/tgui-panel/styles/goon/chat-base.scss
> +  font-size: large;
💀

2023-02-23 11:15 UTC, KIBORG04 commented on tgui/packages/tgui-panel/styles/goon/chat-base.scss
> +  font-size: large;
Это так важно? :sob: 😫

2023-02-23 11:16 UTC, volas commented on tgui/packages/tgui-panel/styles/goon/chat-base.scss
> +  font-size: large;
не очень, просто теперь ты знаешь

2023-02-23 19:19 UTC, KIBORG04 commented
Я жеско кринжанул с формулой.

2023-02-23 19:20 UTC, LudwigVonChesterfield commented on code/controllers/subsystem/round_rating.dm
> +			template.avg_rate += text2num(choice.text) * total_votes // :)
а зачем тут умножать а потом ниже делить

2023-02-23 19:20 UTC, KIBORG04 commented on code/controllers/subsystem/round_rating.dm
> +			template.avg_rate += text2num(choice.text) * total_votes // :)
Аккумулируем в одну переменную сумму всех голосов, а ниже среднее

2023-02-24 21:33 UTC, KIBORG04 commented on tgui/packages/tgui-panel/styles/goon/chat-base.scss
> +  font-size: large;
![image](https://user-images.githubusercontent.com/26389417/221297439-9c64a458-bb7f-4b9f-bcdf-662807b37b7d.png)

Кажется то, о чем и писал волас.....

2023-02-24 21:36 UTC, KIBORG04 commented on tgui/packages/tgui-panel/styles/goon/chat-base.scss
> +  font-size: large;
Как это мне сделать на моем компьютере и проверить на каких-то других кейсах?...

2023-02-24 21:40 UTC, volas commented on tgui/packages/tgui-panel/styles/goon/chat-base.scss
> +  font-size: large;
large заменить на 2, large-x на 3. Вроде так. Посмотри что получится локально, потом так же и у других будет.

Можно на 2em, 3em, или дробными 1.5em и тд.

2023-02-24 22:34 UTC, LudwigVonChesterfield commented
А можно в чатик выводить то чему я поставил оценку?

Сейчас:
Ваша оценка: 5

Было бы круто:

Ваша оценка ролеплея: 5

(а ещё лучше смайлик..)

(А можно ли чтобы смайлик который выбрал подсвечивался цветом каким-нибудь?)

2023-02-24 22:45 UTC, KIBORG04 commented
> (А можно ли чтобы смайлик который выбрал подсвечивался цветом каким-нибудь?)

Нет, потому что я не знаю как на хтмле сделать так, чтобы при перевыборе голоса, другие смайлики перестали подсвечиваться

2023-02-25 00:58 UTC, LudwigVonChesterfield commented
я знаю как такое сделать на наноуи неужели тгуи хуже...

2023-02-25 10:11 UTC, volas commented
тгюи не при чем, чат статичный и сообщения там не подразумевают обновлений.

Всё еще можно сделать на чистом CSS с checkbox/radio-группой, у них есть статус ``:checked`` по нажатию

2023-03-02 19:31 UTC, volas commented
Дорабатывать потом в мастере, если нужна помощь с версткой - могу подсказать

2023-03-02 19:31 UTC, merged

2023-03-08 17:29 UTC, KIBORG04 commented
> тгюи не при чем, чат статичный и сообщения там не подразумевают обновлений.
> 
> Всё еще можно сделать на чистом CSS с checkbox/radio-группой, у них есть статус `:checked` по нажатию

@volas но ведь это относится к <input\>-аттрибуту, как это через <a\> сделать?

2023-03-08 17:42 UTC, volas commented
проверил, вариант через ``<a>`` возможен, но он не совсем валиден будет... думаю лучше всё же с небольшим ивентом на onclick , типо
```
<fieldset id="vote1">
	<input type="radio" name="vote1" onclick="window.location='?src=\ref[SSrating];round_rating=[text];rating_cat=[category]';">bad</input>
	<input type="radio" name="vote1" onclick="window.location='?src=\ref[SSrating];round_rating=[text];rating_cat=[category]';">norm</input>
	<input type="radio" name="vote1" onclick="window.location='?src=\ref[SSrating];round_rating=[text];rating_cat=[category]';">good</input>
</fieldset>
```

2023-03-08 18:10 UTC, KIBORG04 commented
![image](https://user-images.githubusercontent.com/26389417/223794910-95c79c66-7b2e-40c3-aa84-e1eeda2013ca.png)

И теперь надо как-то этот кружок скрывать, заставлять при активирование менять лицо, че-то там убирать, аааа, я не смогу