Новые спрайты для электрогитары
TauCetiStation/TauCetiClassic pull request #9428
Opened 2022-06-07 16:59 UTC by Tap0r

## Описание изменений
Добавлены 4 вариации спрайта для электрогитары.
![2](https://user-images.githubusercontent.com/88531962/172436960-ab4a825f-78eb-45ae-9272-6f2cd38969a8.PNG)
![image](https://user-images.githubusercontent.com/88531962/172439965-dda1920f-290e-4bfc-a7eb-778fe4e980f5.png)

## Почему и что этот ПР улучшит
красоту
## Авторство
я
## Чеинжлог
:cl:
 - image: Добавлены 4 вариации спрайта для электрогитары.

2022-06-07 16:59 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2022-06-07 19:06 UTC, GermanSUS commented
Это конечно не по теме пра но дай возможность заказать музыкальные инструменты в карго

2022-06-08 03:19 UTC, volas commented
Инструменты всегда были в ограниченном количестве, что бы не перегружать игру и игроков

2022-06-09 09:05 UTC, UDaV73rus requested changes
скинул тапору свои пробы в гитарки, переделал, стало на много лучше, но ещё есть куда стремиться.
Сейчас оч много мест со странным светом и переизбытком не нужных деталей(серые пиксели в рандомных местах)
![image](https://user-images.githubusercontent.com/33157992/172808896-c6db10bc-d69e-42dd-8331-bd0ef402ff59.png) ![image](https://user-images.githubusercontent.com/33157992/172809849-269e1306-500d-483a-a387-f5c5af3964f4.png)

2022-06-23 21:15 UTC, Tap0r commented
Ыыыыаэаэаэыэыэыэыэыывввваыаыаыаыаыа

2022-06-29 05:47 UTC, volas commented
Насколько понимаю, замечания Удава еще актуальны, на гитарах всё еще присутствуют эти регуляторы в виде кляксы
![Снимок экрана от 2022-06-29 08-44-11](https://user-images.githubusercontent.com/4064061/176360770-7e26df47-ea5c-498c-9432-87da37564d61.png)

Потыкай спрайтеров там за апрувом, если что.

2022-07-01 16:45 UTC, Tap0r commented
Убрал "кляксы" 
![image](https://user-images.githubusercontent.com/88531962/176936470-4c7f9d6c-e02f-4dcc-b2ca-6b40dfb781c6.png)

2022-07-17 19:39 UTC, Tap0r commented
oh nononoononon...

2022-08-07 23:40 UTC, closed without merging

2022-08-07 23:41 UTC, Shootnik01 commented
До слез((

2022-08-07 23:42 UTC, Shootnik01 commented
@TauCetiStation/maintainers

2022-08-08 03:26 UTC, volas commented
Тут не к мейнтейнерам, автор не решил вопросы со спрайтерами