Hand tele resprite
TauCetiStation/TauCetiClassic pull request #9444
Opened 2022-06-09 08:11 UTC by Tap0r

## Описание изменений
респрайт ручного телепортера
![1](https://user-images.githubusercontent.com/88531962/172798167-7a3ae1d0-9d7f-441d-8d16-21e5ca1e5fed.gif)
![image](https://user-images.githubusercontent.com/88531962/172798282-fe2e46ab-5cca-424b-b301-18d05e25469a.png)

## Почему и что этот ПР улучшит
красоту

## Авторство
я

## Чеинжлог
:cl:
 - image: Обновлён спрайт ручного телепортера, добавлены инхенды к нему.

2022-06-09 08:47 UTC, UDaV73rus requested changes
Разительного скачка между старым и новым нет, нужен тотальный редизайн. В котором будет видно что это реально серьезная технологичная штука создающая телепорты

2022-06-09 09:19 UTC, notkripton commented
похоже на радио или пульт управления игрушечной машинкой, но анимация крутая 👍

2022-06-29 06:12 UTC, volas commented
@UDaV73rus даже если скачка нету, старый в старой проекции, этот адаптирован для нас. И как минимум он не хуже, так что я думаю смержить.

2022-06-29 07:01 UTC, UDaV73rus commented
окей

2022-06-29 20:27 UTC, merged