Яблоками теперь есть смысл метаться
TauCetiStation/TauCetiClassic pull request #9473
Opened 2022-06-14 09:23 UTC by Rolt146

## Описание изменений
Теперь яблоки при метании наносят ощутимый урон(4 урона), особенно яблоки с большой потенцией(до 10 урона), особенно яблоки из золота (от 10 урона дефолтные и до 26, если сделать максимальную потенцию) (инфа не окончательная, возможно изменения баланса)
## Почему и что этот ПР улучшит
Теперь логично, что метая твердые яблоки, ты будешь получать урон как от яблока, а не как от проводочка или бумажки. Будет стимул знающим ботаникам как эффектно потролить, затрейторить или помочь станции яблоками
## Авторство
Rolt146
## Чеинжлог
- rscadd: Яблоками стало больнее кидаться.

2022-06-14 09:23 UTC, TauKitty commented
###### Changelog status: :radio_button: No changelog

2022-06-14 09:33 UTC, Chip11-n commented
Я уже предвкушаю как люди в нюку заряжают в пневмопушку яблоки и убивают за выстрел нюкера

2022-06-14 09:35 UTC, Rahmanio commented
Пр норм, но дамаги завышенные?

2022-06-14 09:38 UTC, Rolt146 commented
> Я уже предвкушаю как люди в нюку заряжают в пневмопушку яблоки и убивают за выстрел нюкера

ну, это надо идти в контакт с ботаниками, ждать пока они сообразят про яблоки, не съедят урожай, вырастят достаточно (чем круче потенция, тем меньше приплод, и эти переменные тяжело держать вместе на высоте), от ученых дождаться пневмопушки и флорагана (без него очень тяжко) и сделают достаточное колличество снарядов. И тогда да, в качестве награды ты получишь оружие, с 2-3 попаданий ломающее ребра нюкеру (броня сильно режет урон от метания)

2022-06-14 09:39 UTC, BiQndy commented
опа, вот и замена забрасыванию плитками на подходе

2022-06-14 11:17 UTC, Akellazp commented on code/modules/reagents/reagent_containers/food/snacks/grown.dm
> +	throwforce = 16+((potency / 4)*2)
деления на два не существует

2022-06-15 17:32 UTC, KIBORG04 commented on code/modules/reagents/reagent_containers/food/snacks/grown.dm
> +	throwforce = 6+(potency / 4)
```suggestion
	throwforce = 6 + (potency / 4)
```

2022-06-15 17:32 UTC, KIBORG04 commented on code/modules/reagents/reagent_containers/food/snacks/grown.dm
> +	throwforce = 6+(potency / 4)
```suggestion
```
Наследуется у обычного яблока

2022-06-15 17:35 UTC, KIBORG04 commented on code/modules/reagents/reagent_containers/food/snacks/grown.dm
> +	throwforce = 16+(potency / 2)
```suggestion
	throwforce = 16 + (potency / 2)
```
Яблоко на 41 дамаги охуеть. Но нет? Мб какую-то нелинейную формулу заюзать, чтобы с ростом potency все меньше и меньше была прибавка к дамаги.

2022-06-15 17:35 UTC, KIBORG04 commented on code/modules/reagents/reagent_containers/food/snacks/grown.dm
> +	throwforce = 6+(potency / 4)
тут мб тоже, бесконечные яблоки на 18 демеджа это же кринж?

2022-06-29 21:30 UTC, volas requested changes
Замечания киборга актуальны, лучше занизить дамаг и если что потом забафать, чем наоборот.

2022-07-13 19:49 UTC, KIBORG04 commented
Автор вернулся

2022-07-15 16:59 UTC, Rolt146 commented
Понерфил урон яблокам, теперь разве что прокаченые потенцией яблоки будут делать хоть какой-то приемлемый урон. Если что, потом бафну, если будет необходимо

2022-07-19 14:31 UTC, volas commented on code/modules/reagents/reagent_containers/food/snacks/grown.dm
> +	throwforce = 12+(potency / 3)
Не делай зависимость от potency, это не очевидно и чревато абузами. Или сделай какой-то кап. Но даже если ты добавишь кап - базовые 12 это уже овердохрена, и особенно для репродуцируемого предмета. 

Посмотри какие предметы в билде, тот же огнетушитель всего 10.

2022-07-19 15:11 UTC, UDaV73rus commented on code/modules/reagents/reagent_containers/food/snacks/grown.dm
> +	throwforce = 12+(potency / 3)
Вся суть ботаники в Зависимости всяких приколов от потенси и набивание его, это не плохо...

2022-07-19 15:13 UTC, BiQndy commented on code/modules/reagents/reagent_containers/food/snacks/grown.dm
> +	throwforce = 12+(potency / 3)
Согласен, надо ещё бананам или хонкбананам прикрутить потенцию для длительности стана, если оно работает щас иначе, конечно

2022-07-19 15:37 UTC, volas commented on code/modules/reagents/reagent_containers/food/snacks/grown.dm
> +	throwforce = 12+(potency / 3)
Кап у самого potency - 100, кап у throwforce в данном случае - ``12+(100/3)`` ~45, это в 4 раза больше огнетушителя. Приблизительно возможность убить гигакс 7 яблоками. В реальности сейчас может сложно такие вырастить, но всё равно убийственные даже при дефолтных параметрах.

Зависимость от potency можно оставить, но сделайте кап, что бы яблоки были не более убийственны, чем метательное оружие на станции.

2022-07-21 13:21 UTC, Rolt146 commented on code/modules/reagents/reagent_containers/food/snacks/grown.dm
> +	throwforce = 12+(potency / 3)
Тут особая фишка. Если там стоит урон 12,это не значит что они 12 и нанесутся. Ибо урон там множится на скорость полета. Я все тестил на локалке, и сверхурона не было. Весь список урона опубликован в начале пра, который уже урезался. Хотите проверить - сделайте тест на локалке

2022-07-23 01:34 UTC, volas commented on code/modules/reagents/reagent_containers/food/snacks/grown.dm
> +	throwforce = 12+(potency / 3)
> Ибо урон там множится на скорость полета

только для людей

2022-07-23 07:20 UTC, Rolt146 commented on code/modules/reagents/reagent_containers/food/snacks/grown.dm
> +	throwforce = 12+(potency / 3)
Я тестил на локалке, урон теперь вообще еле ощутимый на стандартной потенции. Да и если человек изъебнется и сделает кучу золотых яблок максимальной потенции, я думаю, он заслужил возможность победить мех этими яблоками, подобно мифу о Давиде и Голиафе

2022-07-23 07:42 UTC, volas commented on code/modules/reagents/reagent_containers/food/snacks/grown.dm
> +	throwforce = 12+(potency / 3)
При стандартных параметрах ``throwforce = 12+(15 / 3) = 17``, в билде предметов со значением больше можно по пальцам одной руки пересчитать, и половина из этих предметов - щитспавн.

У объектов есть еще свой модификатор ``throw_speed``, посмотри что у яблок. Может проблема в нем.

Поищи какой-нибудь эталонный для яблок предмет в билде и перепиши к себе параметры, сравни в игре.

Если тебя в целом возмущает низкий урон от бросания предметами в игре - так сделано специально, иначе это щитфест по забрасыванию подручными средствами и дальнобойное оружие не нужно.

2022-07-23 07:58 UTC, Rolt146 commented on code/modules/reagents/reagent_containers/food/snacks/grown.dm
> +	throwforce = 12+(potency / 3)
Я не особо понимаю магию, когда при мили уроне наносится именно столько, сколько прописал, а при метании в силу вступают неведомые факторы, сильно ослабляющие урон. Я как раз опытным путем и подбирал значения, что бы урон  был хоть сколько ощутимым, но не был слишком сильным. И новыми нерфами и так уже урезал, что обычное яблоко на макс прокачке наносит не 10 урона, а всего 7

2022-07-23 08:28 UTC, UDaV73rus commented on code/modules/reagents/reagent_containers/food/snacks/grown.dm
> +	throwforce = 12+(potency / 3)
Мб можно как-то забалансить чтобы и с кидка руки наносило нормально  урона и с помпы голову не отрывало?

2022-07-24 12:33 UTC, volas commented on code/modules/reagents/reagent_containers/food/snacks/grown.dm
> +	throwforce = 12+(potency / 3)
Для людей это только вопрос с ускорением, запустили в тебя предмет из метеоргана или прилетело сквозняком от атмосферы. И ``throw_speed`` что-то вроде аэродинамичности предмета, наверно.
Только иметь в виду, что это ускорение учитывают похоже только люди, а остальные просто считают плоский урон.

2022-08-14 12:41 UTC, closed without merging