Риг для трейтора, опять
TauCetiStation/TauCetiClassic pull request #9475
Opened 2022-06-14 11:42 UTC by simb11

## Описание изменений
#9425 
![image](https://user-images.githubusercontent.com/84613249/173567049-612f20bd-548f-4e19-9372-d1ad09c64651.png)

В аплинк трейтора был добавлен гибридный риг и модули для рига, риг стоит 8 телекристаллов, защищает хуже нюкерского, но имеет больше слотов для модулей.
Штурмовая броня и хеви риги теперь покупаются в аплинке
Переместил броню и спейс сьюты в отдельную вкладку аплинка.
## Почему и что этот ПР улучшит
новый контент больше способов выполнить цельки всё такое
## Авторство

## Чеинжлог
:cl:  Simbaka
- rscadd: В аплинке предателя появился гибридный риг.
- tweak: Штурмовая броня и тяжелые риги теперь покупаются в аплинке.

2022-06-14 11:42 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2022-06-14 12:30 UTC, NeOchenLord commented
8 кристаллов это мало. Нужно 10 минимум.

2022-06-14 14:43 UTC, simb11 commented
> 8 кристаллов это мало. Нужно 10 минимум.

Мне кажется нормальным, я рассчитываю на то что риг будут покупать вместе с модулями

> 2 кристалла за стелс модуль это слишком мало. 15 за лазерку это много.

Ну так эти модули у разных ролей, стелс модуль у трейтора, у которого 20 ТК(или 28 иногда), из которых он 8 скорее всего потратит на риг. А лазерка у нюки, у которой, если брать кастомный набор, целых 40 ТК, плюс ещё риг халявный.

2022-06-14 16:42 UTC, GermanSUS commented
Если это РИГ то как его модифицировать под других ксеносов?

2022-06-14 19:06 UTC, simb11 commented
В аплинке за 1 ТК продаются модкиты для рига

2022-06-15 07:24 UTC, simb11 commented
да можешь но он много энергии ест и бегать в нём постоянно включая выключая ты не сможешь

2022-06-15 17:20 UTC, KIBORG04 commented on code/datums/uplinks_items.dm
> +/datum/uplink_item/suits_armor/combat_injector
лол, а че этого всего нет в ченджлоге????

2022-06-15 17:20 UTC, KIBORG04 commented on code/datums/uplinks_items.dm
> +/datum/uplink_item/suits_armor/combat_injector
Ну и без балдепа не разобраться

2022-06-16 07:53 UTC, TauKitty commented
Этот запрос на извлечение был упомянут в **Tau Ceti Station Forum**. Там могут быть соответствующие подробности:

https://forum.taucetistation.org/t/golosovanie-rig-dlya-trejtora/34142/1

2022-06-18 15:33 UTC, simb11 commented
большинству всё нравится, так что давайте мерж все дела.

2022-06-30 15:57 UTC, volas commented
как минимум, убери всё лишнее, что не относится к теме ПР-а

2022-07-02 18:37 UTC, volas commented
Да, но можешь не торопиться, я это мержить не буду. 

Тут куча каких-то стрёмных модулей, сама идея зачем и что покрывает риг не объяснена толком, да и апрув от спрайт департамента нужно ждать.

2022-07-08 18:28 UTC, UDaV73rus requested changes
у половины спрайтов забытый не перекрашенный красный аутлайн.
и шлем скреллов, хвосты должны быть спереди шлема, а не сзади

2022-07-09 06:00 UTC, simb11 commented
Обновил спрайты, перекрасил аутлайн.
Не понял про скрелльский шлем, он тот же, что и у нюки.
![image](https://user-images.githubusercontent.com/84613249/178093771-f4f8dcf8-7ec5-4497-8626-dfc089e70e7a.png)

2022-07-09 07:40 UTC, simb11 commented
Удалил всё лишние, оставил лишь добавление рига в аплинк

2022-07-26 05:49 UTC, closed without merging