Добавляет всякие вещи в случайные наборы трейтора
TauCetiStation/TauCetiClassic pull request #9505
Opened 2022-06-17 17:52 UTC by simb11

## Описание изменений
Немного обновил содержимое наборов трейтора.
Может ещё что-то добавлю.
<details>
  <summary>Подробнее</summary>

Во всех наборах заменил резиновые перчатки на боевые.
В набор кровавого шпиона был добавлен баллон для пауверфиста.
В наборе "Стелс" перчатки вора были заменены на перчатки тишины, ещё добавил едаггер.
В набор дырявщика была добавлена бомба синдиката(которая большая), детонатор и експлоусив картридж для ПДА.
В набор с пушками была добавлена броня, галоши, аптечка и дополнительные барабаны для револьвера.
В набор хакера был добавлен пояс с улучшенными инструментами и ЭМИ имплант.
В набор крутого шпиона добавил зиппуху, карту агента, войс чейнджер и заменил обычный магазин для стечкина на расширенный.
В наборе с ядами все склянки, кроме чифспешала, полные, также добавил в набор пустой гипоспрей, для выполнения цели на кражу он не подходит.
В набор ниндзи добавил дабл енерджи сворд и комбат перчи.

</details>

## Почему и что этот ПР улучшит
Наборы чаще будут брать наверное
Как мне кажется, в наборах на данный момент ОЧЕНЬ мало вещей и те не стоят своих 20ТК, в каком-нибудь наборе с пушками из полезного только револьвер и емаг, или например набор c ядами, он без доступа к шприцам или автолату бесполезен. Этим ПРом я хочу сделать наборы чуть более разнообразными и полезными, да и вообще сделать так, чтобы они реально стоили своих 20 ТК.
## Авторство

## Чеинжлог
:cl: Simbaka
- tweak: Обновлено содержимое наборов предателя.

2022-06-17 17:52 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2022-06-18 15:45 UTC, Chip11-n commented
Прикольно. На Тау очень редко покупают наборы, и скажем честно, большинство из них - мусор. Может этот ПР и что-то поправит.

2022-06-29 21:35 UTC, simb11 commented
о божееееее
мне что, каждый набор по отдельности обновлять?

2022-07-01 04:00 UTC, Akakiy-Akakiyevich commented
Зачем наборы должны стоить обязательно 20 тк? Может агенту еще что-нибудь прикупить приспичит помимо набора. Догонять их до стоимости в 20 всякими безделушками было необязательно, я думаю.
Набор дырявщика выглядит слишком опасным. Такой нюке бы.
В остальном наборы выглядят круто и могут расширить возможности агентов, помочь в выборе новичкам.

2022-07-01 08:09 UTC, simb11 commented
В этом же и фишка наборов, они стоят 20 ТК и в них предостаточно вещей для выполнения заданий, ну и созданы они для того, чтобы игроки выполняли цели в определённом стиле, заданным набором.

2022-07-02 18:56 UTC, volas requested changes
Реквестирую кого нибудь провести ревизию по стоимости содержимого коробок. Можно было бы прям в swith-е откомментировать для каждого предмета и подвести сумму.

Если переделать наборы на датумы, то можно было бы какую-то автоматически генерируемую для дебага табличку в игре сделать.

2022-07-02 18:56 UTC, volas commented on code/game/objects/items/weapons/storage/uplink_kits.dm
> +			new /obj/item/weapon/pen/edagger(src)
Добавленные новые перчатки 7 очков, едаггер 5. Старые предметы 23. Слишком выгодно для коробки за 20.

Вариант может был бы разбить на 2-3 разных stealth набора.

Ну и с другими тоже нужно так же посмотреть.

2022-07-20 07:18 UTC, simb11 commented
сделал, как ты и просил.

2022-07-29 21:33 UTC, necrofill commented
Хороший пр, разве нет?

2022-08-15 20:55 UTC, simb11 commented
Немного поменял бандлы, большинство удешевил.

2022-08-19 04:29 UTC, volas commented
> Немного поменял бандлы, большинство удешевил.

Обновишь таблицу в первом посте?

Я всё еще предлагаю делать это комментариями в коде.

2022-08-19 04:51 UTC, simb11 commented
Да вроде табличка актуальна

2022-09-02 14:38 UTC, simb11 commented
@volas алло ну как там с бандлами обстоит вопрос

2022-09-02 14:40 UTC, volas commented
Если табличка актуальная - то проблемы, о которых я говорил, не были решены.

2022-09-02 15:18 UTC, simb11 commented
терь почти все коробки стоят меньше 30тк

2022-09-16 06:45 UTC, simb11 commented
ладно пох

2022-09-16 06:45 UTC, closed without merging