Небольшие фиксы дион
TauCetiStation/TauCetiClassic pull request #9507
Opened 2022-06-18 12:55 UTC by NinjaPikachuska

## Описание изменений
Добавил дионам `oxy_mod = 0`, чтобы они не получали окси урон, например, от петли.
Добавил проверку на отрицательный урон в реген органов, чтобы в случае нецелого числа урона не продолжалось лечение в минус.
Убрал неработающий механ легких, завязанных на токсинах, т.к. дионы не имеют токс урона из-за флага `NO_BLOOD`.
Убрал лишний реген почек.
## Почему и что этот ПР улучшит
Меньше багов.
## Авторство
Я
## Чеинжлог

2022-06-18 12:55 UTC, TauKitty commented
###### Changelog status: :radio_button: No changelog

2022-06-19 08:03 UTC, BunkyFly commented
Получается теперь диону не задушить?

2022-06-19 11:42 UTC, NinjaPikachuska commented
Их и сейчас нельзя задушить, ибо реген окси слишком быстрый. Но, если реген дионы будет занят органами или переломами, то дионы могут спокойно задохнуться от петли или чьих-то рук.

2022-06-29 08:11 UTC, BunkyFly commented
> Выпил окси регена у дион замержили, а окси мод 0 нет. Теперь петля точно убивает дион.

Дионы по сути деревья и как-бы они не дышат, но теперь их МОЖНО задушить петлей

2022-06-29 18:33 UTC, volas commented on code/modules/mob/living/carbon/species.dm
> +					O.damage = 0
```suggestion
				O.damage = max(0, O.damage - light_amount * regen_mod / 5)
```

2022-06-29 18:38 UTC, volas commented on code/modules/organs/organ_internal.dm
> -			owner.apply_damage(rand(1,15), TOX, BP_CHEST, 0)		//Diona's lungs are used to dispose of toxins, so when lungs are broken, diona gets intoxified.
Мне кажется, то что сломали механ дав NO_BLOOD дионам - не повод его совсем выпиливать.

Можем заменить токсины чем-то другим? Или может нужно рассмотреть NO_BLOOD дион и его работу с токсинами еще раз (может нужен отдельных флаг).

2022-07-02 19:26 UTC, volas commented on code/modules/organs/organ_internal.dm
> -			owner.apply_damage(rand(1,15), TOX, BP_CHEST, 0)		//Diona's lungs are used to dispose of toxins, so when lungs are broken, diona gets intoxified.
@LudwigVonChesterfield интересно твоё мнение тут.

2022-07-03 12:31 UTC, volas requested changes
обсуждение выше, все пропали

2022-07-03 13:59 UTC, BunkyFly commented
> обсуждение выше, все пропали

После тестировки стало больше багов, дионы после петли падают в бесконечный сон из которого из не вывести

2022-07-03 15:31 UTC, LudwigVonChesterfield commented on code/modules/organs/organ_internal.dm
> -			owner.apply_damage(rand(1,15), TOX, BP_CHEST, 0)		//Diona's lungs are used to dispose of toxins, so when lungs are broken, diona gets intoxified.
ничего не сломали, токси и окси урон никогда не работали и то что я их натыкал было моей ошибкой

2022-07-04 18:33 UTC, volas approved these changes

2022-07-04 18:33 UTC, merged