Респрайт некоторых худов.
TauCetiStation/TauCetiClassic pull request #9517
Opened 2022-06-19 20:45 UTC by Tap0r

## Описание изменений
![image](https://user-images.githubusercontent.com/88531962/174499642-dfd5748a-2547-41f0-98d1-2ccabbb8806b.png)
![2](https://user-images.githubusercontent.com/88531962/174499661-b247dd36-b78a-47a4-af4a-3bd0b7f7e9cb.PNG)
![3](https://user-images.githubusercontent.com/88531962/174499664-d2ecde13-3483-42b5-86e4-d8f5f2efc6c3.png)

## Почему и что этот ПР улучшит
красоту
## Авторство
я
## Чеинжлог
:cl: 
 - image: Обновлены спрайты худов.

2022-06-19 20:45 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2022-06-19 22:34 UTC, UsadoSmokk requested changes
Воксам респрайт не завезли

2022-06-20 06:32 UTC, Tap0r commented
Не понял, каким-то там воксам отдельный спрайт надо?

2022-06-20 06:48 UTC, UsadoSmokk commented
Да

2022-07-04 06:31 UTC, UDaV73rus requested changes
Перекрас не очень, спрайт стал меньше, отсутствие толщины и каких-либо аутлайнов делают спрайт по игре не приятным. Даже не превью заметно что чтобы увидеть в куче вещей очки, нужно реально напрячься

Опять же говорю что просто перекрашивать - это бесполезное занятие и нужна новая глобальная красивая идея как рисовать очки, потому что все очки в билде нуждаются в респрайте.

2022-07-21 18:23 UTC, Tap0r commented
> Перекрас не очень, спрайт стал меньше, отсутствие толщины и каких-либо аутлайнов делают спрайт по игре не приятным. Даже на превью заметно, что чтобы увидеть в куче вещей очки, нужно реально напрячься
> 
> Опять же говорю что просто перекрашивать - это бесполезное занятие и нужна новая глобальная красивая идея как рисовать очки, потому что все очки в билде нуждаются в респрайте.

![image](https://user-images.githubusercontent.com/88531962/180286148-eb619fb9-46b2-4082-b042-493653b2b5e3.png)
???????????

2022-07-22 14:24 UTC, UDaV73rus commented
![image](https://user-images.githubusercontent.com/33157992/180459891-37016d1b-55ef-4b66-917d-4073345a20cb.png)

(Плох)

2022-07-22 15:14 UTC, AirBlack commented
писька
![image](https://user-images.githubusercontent.com/5171605/180469925-4949f01a-3f5e-43d2-9a71-b90ea7d7dc73.png)

2022-07-22 19:08 UTC, Tap0r commented
отвалиська

2022-08-06 12:01 UTC, closed without merging