Термит может плавить почти всё
TauCetiStation/TauCetiClassic pull request #9529
Opened 2022-06-23 17:05 UTC by IlinMihail

## Описание изменений
Термит помимо стен теперь может плавить шкафы, двери, консоли, машины и прочее

## Почему и что этот ПР улучшит
+10 к грифу

## Авторство

## Чеинжлог
:cl: M104
add: Термит может плавить больше вещей

2022-06-24 20:48 UTC, IlinMihail commented
там глупенький варн про то что я не юзаю переменную айтема, хотя мне нужно только его заспавнить

2022-06-24 21:06 UTC, kalazus commented
К твоему сожалению варн не глупенький. Можно new использлвать без переменной.

2022-06-25 06:11 UTC, kalazus commented on code/game/atoms.dm
> +		O.layer = 5
Это всё нужно в отдельный тип вынести.

2022-06-25 06:26 UTC, kalazus commented on code/game/atoms.dm
> +		QDEL_IN(O, seconds_to_melt SECONDS)
1) лучше регистрировать сигнал (либо что лучше придумать) чтобы термит убирался при уничтожении предмета.
2) QDEL_IN обязательно произойдёт даже при remove_thermite. Нужен таймер с id.

2022-06-25 06:26 UTC, kalazus commented on code/game/objects/items/weapons/tools.dm
> +			return
Зачем тут return-ы? Дальше есть проверка на поджигание пола под предметом.

2022-06-25 06:26 UTC, kalazus commented on code/game/objects/structures/crates_lockers/closets.dm
> +
Т.е. теперь нельзя положить контейнер в ящик?

2022-06-25 06:26 UTC, kalazus commented on code/game/turfs/simulated/floor.dm
> +	BreakToBase()
Уже точно не помню, но вроде sleep в любых attack_by нежелательны. Да и зачем вообще это делать, есть турф qdel-итится?

2022-06-25 09:14 UTC, IlinMihail commented on code/game/objects/structures/crates_lockers/closets.dm
> +
почему же, можно. просто если ты закрытый шкаф облил термитом он не откроется после этого

2022-06-25 09:33 UTC, IlinMihail commented on code/game/turfs/simulated/floor.dm
> +	BreakToBase()
qdel не работает на полы, а даже если бы работал у меня подозрение что просто снялась плитка, а я хочу до самого космоса

2022-06-25 09:52 UTC, kalazus commented on code/game/objects/structures/crates_lockers/closets.dm
> +
Про второе не знаю, но да, проверка на открытость раньше.

2022-06-25 10:13 UTC, Deahaka commented
Это получается термит будет тупо С4 бесплатным?

2022-06-25 11:43 UTC, IlinMihail commented on code/game/atoms.dm
> +		QDEL_IN(O, seconds_to_melt SECONDS)
так, как красиво сделать чтоб не было два вара под два айди таймера? можно как то в колбек добавить второй прок?

2022-06-25 12:53 UTC, kalazus commented on code/game/atoms.dm
> +		QDEL_IN(O, seconds_to_melt SECONDS)
Как и писал, лучше удалять термит по сигналу, связанному с qdel. И тебе в любом случаи желательно сделать прок для удаления т.к. есть турфы (а удалять лучше только верхний т.к. термит иначе будет всегда разгермы делать).

2022-06-25 12:56 UTC, kalazus commented on code/game/atoms.dm
> +		var/turf/L = src.loc
Хз насколько реально такое, но кажется что термит можно использовать в руках, а тогда тут будет exception. Используй get_turf или проверку.

2022-06-25 13:12 UTC, IlinMihail commented
ну можно время плавки повысить, убрать возможность ломать укреп. стены, полы. ещё возможность тушить чем нибудь

2022-06-25 13:36 UTC, kalazus commented on code/game/atoms.dm
> +		QDEL_IN(O, seconds_to_melt SECONDS)
А вообще, overlay сам не исчезает? Он же находится вроде внутри предмета.

2022-06-25 13:54 UTC, IlinMihail commented on code/game/atoms.dm
> +		QDEL_IN(O, seconds_to_melt SECONDS)
нет, он будет на месте пока не дилитнут

2022-06-25 16:08 UTC, LudwigVonChesterfield commented on code/game/atoms.dm
> +	var/seconds_to_melt = 30 //set to negative/zero if you don't want for your atom to be melted at all
мне кажется по дефолту вещь должна быть несжигаемая термитом, а не наоборот

2022-06-25 16:09 UTC, LudwigVonChesterfield commented on code/game/objects/items.dm
> +		visible_message("<span class='warning'>Thermite instantly melts [src] turning it into molten mess. </span>")
почему это поведение для предметов не указывается параметром seconds_to_melt = 1 у /obj/item?

2022-06-25 16:11 UTC, LudwigVonChesterfield commented on code/game/turfs/simulated/floor.dm
> +	BreakToBase()
слип действительно тут нежелателен

2022-06-25 16:34 UTC, IlinMihail commented on code/game/atoms.dm
> +	var/seconds_to_melt = 30 //set to negative/zero if you don't want for your atom to be melted at all
мне кажется что гораздо геморойнее проставлять потом каждой мелочи что её можно расплавить чем наоборот. хотя надо баланс деп спросить

2022-06-25 16:46 UTC, IlinMihail commented on code/game/objects/items.dm
> +		visible_message("<span class='warning'>Thermite instantly melts [src] turning it into molten mess. </span>")
потому что в данном случае seconds_to_melt работает как бул. (и типо мгновенное плавление мелких предметов ближе к реальности)

2022-06-25 16:47 UTC, IlinMihail commented on code/game/objects/items.dm
> +		visible_message("<span class='warning'>Thermite instantly melts [src] turning it into molten mess. </span>")
хотя налеплю сверху эффект сварки, так же будет

2022-06-27 15:07 UTC, IlinMihail commented
вопрос: стоит ли плавить все/рандомные предметы в шкафу чтоб люди всё таки старались использовать сифор/емаг/ЭМИ

2022-06-30 13:05 UTC, IlinMihail commented on code/game/atoms.dm
> +		QDEL_IN(O, seconds_to_melt SECONDS)
дестрой теперь убирает

2022-07-03 13:25 UTC, volas commented on code/game/atoms.dm
> +	var/obj/effect/overlay/thermite_overlay
Возможно стоило посмотреть компоненту с тг и утащить

2022-07-03 15:11 UTC, IlinMihail commented on code/game/atoms.dm
> +	var/obj/effect/overlay/thermite_overlay
окей, будет компонент

2022-07-04 13:38 UTC, IlinMihail commented on code/game/atoms.dm
> +	var/obj/effect/overlay/thermite_overlay
компонент есть а кучка переменных для минимального количества термита/максимального времени плавки/минимального времени плавки/прочего ещё нужны. может упростить и сделать только один вар типо "thermite_resistance = TR_REGULAR/TR_HIGH/TR_VERYHIGH"?

2022-07-04 13:40 UTC, IlinMihail commented on code/game/atoms.dm
> +	var/obj/effect/overlay/thermite_overlay
и от него уже значения делать вне атома

2022-07-07 18:35 UTC, IlinMihail commented on code/game/atoms_movable.dm
> +	if(freeze_movement)
наверное не очень хорошо это в форсмуве делать, но раз он везде юзается...

2022-07-13 19:59 UTC, IlinMihail commented
ревью может? вроде всё работает

2022-07-21 04:07 UTC, volas commented on code/game/atoms.dm
> +	return FALSE
Хм, я понял, на тг это только компонент тайлов, а тут идея плавить всё, и задача глобальнее. Нужно подумать, как это лучше делать... 
Вообще это тогда больше похоже на то, как уже работает кислота. И кислоту нужно тоже переделывать на компонент в перспективе. И на тг компонент кислоты уже есть, и возможно будет ближе к идее термита для всего тут.

2022-07-24 10:44 UTC, IlinMihail commented on code/game/atoms.dm
> +	return FALSE
в кислоте проки для объектов/мобов/турфов прямо в компоненте находятся. могу перенести, но так вроде красивее и можно уникальные эффекты при плавке сделать для разных объектов.

2022-07-24 11:01 UTC, IlinMihail commented on code/_onclick/item_attack.dm
> -		return TRUE
оверлоады attackby не вызывают ..() поэтому так и было сделано. кроме того это позволяет NO_ATTACKBY легко впихнуть. могу конечно переделать и везде ..() проставить

2022-07-24 11:03 UTC, volas commented on code/_onclick/item_attack.dm
> -		return TRUE
я не про перегруз, многие вещи могут вызывать obj.attackby() на совершенно другие ивенты, отличные от клика

2022-07-24 11:10 UTC, IlinMihail commented on code/_onclick/item_attack.dm
> -		return TRUE
ну так я о том же, если мы вызываем attackby какого то атома у которого он перегружен, то мы не кидаем эти сигналы вообще, и не проверяем фидбек от компонентов, следовательно работает всё не как надо. собственно для многих вещей у которых attackby вызывается напрямую ничего не поменялось.

2022-07-24 11:13 UTC, volas commented on code/_onclick/item_attack.dm
> -		return TRUE
Почему ты считаешь, что если кому-то мы вызываем attackby, то /attackby у этого предмета будет обязательно перегружен и без сигналов. Это не связанные вещи.

2022-07-24 11:16 UTC, volas commented on code/_onclick/item_attack.dm
> -		return TRUE
Например из какого-нибудь ``afterattack_tk``, или при правом клике, или при клике из экшен кнопки, и так далее

2022-07-24 11:16 UTC, IlinMihail commented on code/_onclick/item_attack.dm
> -		return TRUE
я не говорю что он у ВСЕГО перегружен, просто у большого количества барахла родителя не зовут

2022-07-29 15:26 UTC, volas requested changes
Я напишу тут из обсуждения в дискорде.

Отдельный ПР (желательно отдельным, это мелочь что и я могу сделать):
1. Проверить, что везде в fire_act есть вызов родителя, прописать если нету
2. Добавить в fire_act сигнал COMSIG_ATOM_FIRE_ACT

По этому ПР:
1. Сигналы атаки не стоит трогать и новые делать, используя уже существующий fire_act через COMSIG_ATOM_FIRE_ACT компоненте мы добавим нормальную и логичную механику без костылей, которая будет работать не только для горелок
2. Соответственно нужно будет добавить горелке вызов fire_act у предметов при ударе. Странно, что этого не было.
3. (Возможно) стоит оставить методы плавки термитом в самой компоненте термита, и делать это по флагам предметов. Как на тг сделали с компонентой кислоты.

2022-08-08 17:40 UTC, IlinMihail commented on code/_onclick/item_attack.dm
> +//structure of attackby overload:
я всё же ещё раз спрошу, ибо в дискорде четкого 'нет' мне никто не сказал. можно ли так везде сделать, раз враппер с ретурном нельзя?

2022-08-08 18:27 UTC, kalazus commented on code/_onclick/item_attack.dm
> +//structure of attackby overload:
Очень херовое решение и такое почти наверное не замержат.

2022-08-08 18:27 UTC, kalazus commented on code/_onclick/item_attack.dm
> -		return TRUE
Можно сделать новый сигнал, который будет вызываться до attackby (на тг наверное в их attack_chain есть подобное)

2022-08-08 18:27 UTC, kalazus commented on code/_onclick/item_attack.dm
> +	if((bit_map & COMPONENT_NO_AFTERATTACK) || (bit_map & COMPONENT_NO_ATTACK_PROCESSING))
Учи битовые операции (3 & 1) = 1, (3 & 2) = 2

2022-08-08 18:27 UTC, kalazus commented on code/datums/components/clickplace.dm
> +		return COMPONENT_NO_AFTERATTACK
Скорее кликплейс не должен вообще работать при харме. И разве это уже не так?

2022-08-08 18:27 UTC, kalazus commented on code/datums/components/thermite.dm
> +		M.anchored = old_anchor
Почему термит вообще устанавливает админскую заморозку движения? Не понимаю почему вообще добавляется anchored, который может сломать много чего. Это термит или клей-момент?

2022-08-08 18:27 UTC, kalazus commented on code/datums/components/thermite.dm
> +	temp = (env.temperature + I.get_current_temperature()) - T0C
Почему температура предмета складывается с температурой окружающей среды? Температура предмета уже абсолютная, и у нас она почти везде или 0 или 1000+.

2022-08-08 18:27 UTC, kalazus commented on code/datums/spells/spacetime_distrortion.dm
> +		. = f
С этим точно не замержат.

2022-08-08 18:27 UTC, kalazus commented on code/game/atoms_movable.dm
> +		return
freeze_movement это админская кнопка чтобы всех замарозить. Очень странно что она останавливает вообще все атомы, ломая кучу систем.

2022-08-08 18:27 UTC, kalazus commented on code/modules/reagents/reagent_types/Chemistry-Miscellaneous.dm
> +			if(C != null)
for in без  as anything никогда не найдёт null, да и в листе этом не должно их быть.

2022-08-08 18:27 UTC, kalazus commented on code/modules/reagents/reagent_types/Chemistry-Miscellaneous.dm
> +				C.set_amount(C.amount + volume)
Тут же можно просто return сделать. У тебя же термит 1 раз максимум накладывается.

2022-08-08 18:27 UTC, kalazus commented on code/modules/reagents/reagent_types/Chemistry-Miscellaneous.dm
> +				C.set_amount(C.amount + volume)
Да и вроде есть примеры, когда компонента может быть только одна.

2022-08-08 18:27 UTC, kalazus commented on code/datums/components/thermite.dm
> +		M.anchored = old_anchor
Можно сделать что-то подобное Bound компоненте, или просто копировать локацию при Moved (вроде должен быть сигнал).

2022-08-08 18:51 UTC, IlinMihail commented on code/_onclick/item_attack.dm
> +//structure of attackby overload:
ну собсна по этому и вопрос. как заставить оверлоады слушаться, чтоб не было криво?

2022-08-08 18:52 UTC, IlinMihail commented on code/_onclick/item_attack.dm
> +	if((bit_map & COMPONENT_NO_AFTERATTACK) || (bit_map & COMPONENT_NO_ATTACK_PROCESSING))
вплане? COMPONENT_NO_ATTACKBY и прочее, нормальные битовые флаги, а bitmap нормальный ретурн от сигнала

2022-08-08 18:57 UTC, IlinMihail commented on code/datums/components/thermite.dm
> +		M.anchored = old_anchor
ленивый фикс движения мобов и прочего барахла после того как они начали гореть. правильнее конечно оверлей нормально перемещать

2022-08-08 18:58 UTC, IlinMihail commented on code/datums/components/thermite.dm
> +	temp = (env.temperature + I.get_current_temperature()) - T0C
ну это копипаст кода пирометра, поставлю просто предмета тогда

2022-08-08 19:00 UTC, IlinMihail commented on code/modules/reagents/reagent_types/Chemistry-Miscellaneous.dm
> +				C.set_amount(C.amount + volume)
ну так довольно глупо что при повторном поливании термитом общее количество не увеличивается, а вторая попытка просто игнорится

2022-08-08 19:04 UTC, kalazus commented on code/_onclick/item_attack.dm
> +	if((bit_map & COMPONENT_NO_AFTERATTACK) || (bit_map & COMPONENT_NO_ATTACK_PROCESSING))
При COMPONENT_NO_ATTACK_PROCESSING у тебя будет TRUE || TRUE в обоих, да и сам COMPONENT_NO_ATTACK_PROCESSING нужно определять как COMPONENT_NO_ATTACKBY | COMPONENT_NO_AFTERATTACK

2022-08-08 19:06 UTC, kalazus commented on code/datums/components/thermite.dm
> +		M.anchored = old_anchor
Нельзя менять anchored на продолжительно время т.к. к примеру так можно сделать рабочую двигающуюся машинерию.

2022-08-08 19:09 UTC, kalazus commented on code/modules/reagents/reagent_types/Chemistry-Miscellaneous.dm
> +				C.set_amount(C.amount + volume)
Не будет игнорится. 1) у компонент вроде есть какая-то штука для варианта, когда на 1 родителя 2 одинаковые компоненты ставятся. 2) Можно получать 1 компоненту (а не лист), раз у тебя она максимум может быть 1. Если нету, добавлять, если есть, то увеличивать amount.

2022-08-08 19:17 UTC, kalazus commented on code/datums/components/clickplace.dm
> +		return COMPONENT_NO_AFTERATTACK
У тебя этот код просто не вызовется, если ты на харме. Да предмет уже покинул руки, как им ещё можно бить?

2022-08-08 19:20 UTC, kalazus commented on code/_onclick/item_attack.dm
> +//structure of attackby overload:
Как и писал, сделать сигнал до attackby (а не в самом).

2022-08-08 19:25 UTC, kalazus commented on code/_onclick/item_attack.dm
> -		return TRUE
Лучше не смотри на ТГ, я не представляю как из нормального прока сделали там такое говно в attack_chain

2022-08-08 20:01 UTC, IlinMihail commented on code/_onclick/item_attack.dm
> +//structure of attackby overload:
волас сказал что сигналы надо оставить в attackby и не трогать

2022-08-08 20:02 UTC, IlinMihail commented on code/_onclick/item_attack.dm
> +//structure of attackby overload:
ну и опять же, ломаются штуки которые вызывают атак бай напрямую

2022-08-08 20:06 UTC, volas commented on code/_onclick/item_attack.dm
> +//structure of attackby overload:
> волас сказал что сигналы надо оставить в attackby и не трогать

по сравнению с тем, что в мастере, а не что ты в этом ПР-е сделал. Используя fire_act тебе вообще не нужно лезть с какими-то новыми или старыми сигналами в атакбай, и городить странные костыли

2022-08-08 20:12 UTC, volas commented on code/modules/reagents/reagent_types/Chemistry-Miscellaneous.dm
> +				C.set_amount(C.amount + volume)
COMPONENT_DUPE_UNIQUE_PASSARGS, до этого потом дойдем

2022-08-09 10:23 UTC, IlinMihail commented on code/_onclick/item_attack.dm
> +//structure of attackby overload:
нет, новые сигналы всё ещё нужны, для ретурна от компонентов, fire_act лишь триггерит термит, а не контролирует выполнение afterattack/attackby

2022-08-09 10:36 UTC, kalazus commented on code/_onclick/item_attack.dm
> +//structure of attackby overload:
Я так кстати и не понял зачем он тебе нужен.

2022-08-09 10:46 UTC, IlinMihail commented on code/_onclick/item_attack.dm
> +//structure of attackby overload:
дабы блочить логику afterattack и attackby естественно, я не хочу например заваривать дверь если я по ней тыкнул сваркой, и она при этом залита термитом

2022-08-09 10:52 UTC, volas commented on code/_onclick/item_attack.dm
> +//structure of attackby overload:
> а не контролирует выполнение afterattack/attackby

Я понял, сейчас ты это всё еще делаешь глобально для перехватывания клика по *любому* объекту, что бы не проходил обычный удар горелкой.

С fire_act ты можешь локально в самой горелке это делать, если добавишь к сигналу COMSIG_ATOM_FIRE_ACT код возврата (был акт, или нет), и плясать в горелке от него. Что-то типо

```
/atom/proc/fire_act(exposed_temperature, exposed_volume)
	return SEND_SIGNAL(src, COMSIG_ATOM_FIRE_ACT, exposed_temperature, exposed_volume)
```

2022-08-09 11:04 UTC, IlinMihail commented on code/_onclick/item_attack.dm
> +//structure of attackby overload:
но ведь fire_act вызывается не для горелки а только для объекта по которому ударили. да и кроме того, для будущих компонентов тоже может понадобиться NO_AFTERATTACK и NO_ATTACKBY

2022-08-09 11:06 UTC, IlinMihail commented on code/_onclick/item_attack.dm
> +//structure of attackby overload:
ну и кроме того, надо будет в каждый горячий предмет тогда копипастить код реакции на сигнал фаер акта

2022-08-09 11:16 UTC, volas commented on code/_onclick/item_attack.dm
> +//structure of attackby overload:
``fire_act`` прок у того, что поджигается, да. И где-то из горелки ты будешь вызывать этот fire_act

2022-08-09 11:23 UTC, kalazus commented on code/_onclick/item_attack.dm
> +//structure of attackby overload:
Я не понимаю почему волас так цепляется за fire_act, учитывая что это вроде прок самого процесса горения, а не поджигания.

2022-08-09 11:27 UTC, volas commented on code/_onclick/item_attack.dm
> +//structure of attackby overload:
Поджигание, это именно реакция на "объект затронуло огнем". Из той же серии, что и  ``emp_act()``, ``ex_act()``, и другие.

2022-08-09 11:28 UTC, volas commented on code/_onclick/item_attack.dm
> +//structure of attackby overload:
Боюсь тут всё еще может быть какой-то мискомуникейшен, вечером можно в дискорде еще обсудить

2022-08-09 13:11 UTC, IlinMihail commented on code/_onclick/item_attack.dm
> +//structure of attackby overload:
вызывать фаер акт ПРЯМО из кода горелки, как по мне, полнейшая глупость. лучше в коде атаки айтемом, в том же атак бай например, проверять температуру предмет и если она выше какого то порога - звать фаер акт на атаковано атоме.

2022-08-17 16:56 UTC, IlinMihail commented
вооообщем, мне как то лень, и я всё ещё хочу эти сигналы атаки, но не знаю как их хорошо сделать, по этому...

2022-08-17 16:56 UTC, closed without merging