HoS aug shades
TauCetiStation/TauCetiClassic pull request #9556
Opened 2022-06-30 01:00 UTC by Mercurialaste

## Описание изменений
Сделал "очки" хоса переключаймыми.
ПНВ и сангласы – отдельные режимы.
ПНВ имеет янтарный цвет, также ПНВ обладает более приятным худом.
"Очки" хоса постоянно имеют СБ худ.
https://youtu.be/SdloWzdmRMs

P.s.: У меня немного кривая ветка.

P.s.s.: Из-за того, каким образом я реализовал переключение между ПНВ и сангласами, рекалибратор работает на половину, а если точнее, до первого переключения режимов. По-хорошему, я думаю запретить пихать в ПНВ ХоСа рекалибратор, но честно, немного хз как это сделать, если есть мысли как, сделаю.

P.s.s.s.: Пытался ещё добавить на очки оверлей, чтобы ХоС бегал с глазами по типу тех что у тенелинга, но янтарного цвета. Не нашел адекватного примера и забил, также буду благодарен если объясните или дадите пример того как делали.

## Почему и что этот ПР улучшит

ХоС больше не будет выбрасывать выданное им НТ оборудование и воровать у офицеров очки?
Предположу, удобство и геймплей.

## Авторство

Я, помогавшие в дискорде.

## Чеинжлог
- tweak: Изменил худ ПНВ ХоСа на более приятный, добавил ему возможность переключатся между режимом солнцезащитных очков и ПНВ.

2022-06-30 01:01 UTC, TauKitty commented
###### Changelog status: :radio_button: No changelog

2022-06-30 07:57 UTC, notkripton commented on code/modules/clothing/glasses/glasses.dm
> +/obj/item/clothing/glasses//hud/hos_aug/verb/switch_shade()
```suggestion
/obj/item/clothing/glasses/hud/hos_aug/verb/switch_shade()
```

2022-06-30 09:36 UTC, Mercurialaste commented on code/modules/clothing/glasses/glasses.dm
> +/obj/item/clothing/glasses//hud/hos_aug/verb/switch_shade()
Bruh

2022-06-30 11:22 UTC, Mercurialaste commented on code/modules/mob/living/carbon/human/human.dm
> +	if(istype(glasses, /obj/item/clothing/glasses/hud/aug_shades))
Брух, спасибо.

2022-07-12 00:58 UTC, volas requested changes

2022-07-12 00:58 UTC, volas commented on code/modules/clothing/glasses/glasses.dm
> +		lighting_alpha = LIGHTING_PLANE_ALPHA_VISIBLE
Я не вижу у нас каких-то очков с ``LIGHTING_PLANE_ALPHA_VISIBLE``, может просто null?

2022-07-12 00:58 UTC, volas commented on code/modules/clothing/glasses/glasses.dm
> +/obj/item/clothing/glasses/hud/hos_aug/verb/switch_shade()
Не должен ли этот прок вызывать какой-то апдейт зрения у моба в конце?

2022-07-12 00:58 UTC, volas commented on code/modules/clothing/glasses/glasses.dm
> +	else
и не должен ли тут где-то сбрасываться hud_types

2022-07-12 05:59 UTC, Mercurialaste commented on code/modules/clothing/glasses/glasses.dm
> +		lighting_alpha = LIGHTING_PLANE_ALPHA_VISIBLE
Это я по своей сути взял Crimson Eyes, там для найтвижена использовалось отключение теней.

2022-07-12 08:18 UTC, Mercurialaste commented on code/modules/clothing/glasses/glasses.dm
> +/obj/item/clothing/glasses/hud/hos_aug/verb/switch_shade()
H.update_sight()
?

Наверное это, судя по названию. 

Если я правильно понимаю, это прописано здесь и ещё раз это прописывать не нужно?


```
/obj/item/clothing/glasses/attack_self(mob/user)
	if(toggleable)
		if(ishuman(usr))
			var/mob/living/carbon/human/H = usr
			if(active)
				active = 0
				icon_state = off_state
				vision_flags = 0
				lighting_alpha = null
				to_chat(usr, "You deactivate the optical matrix on the [src].")
			else
				active = 1
				icon_state = initial(icon_state)
				vision_flags = initial(vision_flags)
				lighting_alpha = initial(lighting_alpha)
				to_chat(usr, "You activate the optical matrix on the [src].")
			playsound(src, activation_sound, VOL_EFFECTS_MASTER, 10, FALSE)
			H.update_inv_glasses()
			H.update_sight()

```


Ориентир брал на нуарные очки в конце файла.

2022-07-12 08:20 UTC, Mercurialaste commented on code/modules/clothing/glasses/glasses.dm
> +	else
Тк... Сама идея была в том, чтобы сделать ГСБ очки, с постоянным СБ худом, но переключаемыми защитой от ярких вспышек и режимом ночного зрения.

2022-07-17 13:54 UTC, Mercurialaste commented
Когда-нибудь… 

_(Анти-бот коолишен.)_

2022-07-19 15:15 UTC, Mercurialaste commented on code/modules/clothing/glasses/glasses.dm
> +/obj/item/clothing/glasses/hud/hos_aug/verb/switch_shade()
Угу, хорошо, оно вроде и сейчас не багается, по ощущению, работая лишь с небольшой задержкой.

Посмотрю в общем и отпишусь как разберусь.

2022-08-02 18:52 UTC, Mercurialaste commented
Да тихо ты... 
Разберусь я.

2022-08-12 13:21 UTC, Mercurialaste commented on code/modules/clothing/glasses/glasses.dm
> +/obj/item/clothing/glasses/hud/hos_aug/verb/switch_shade()
Если я правильно понимаю работу кода, то упомянутые обновления зрения моба происходят, если toggleable существует.
А по скольку оно создано в
`/obj/item/clothing/glasses/` 

То все предметы дальше 
`/obj/item/clothing/glasses/`

Наследуют это и собственно, все работает корректно.

2022-08-20 22:05 UTC, Mercurialaste commented
wants to merge

2022-08-21 12:03 UTC, KIBORG04 commented on code/modules/clothing/glasses/glasses.dm
> +/obj/item/clothing/glasses/hud/hos_aug/verb/switch_shade()
Может нt надо вербов? Ты и так сделал экшен кнопкой.

2022-08-21 12:06 UTC, KIBORG04 commented
Ты так и не сделал, что тебя просил волас.

 Сделал какой-то свой страшный овверайд, который зачем-то работает. Новые переменные, которые уже были, переопределение аттак_селфа, что убивает всё наследование, о котором ты писал. Неиспользование текущих переменных очков. Оч страшный код, который с диффа 43 строчек схлопывается до ~10

2022-08-21 12:08 UTC, KIBORG04 requested changes
Посмотри еще раз на `/obj/item/clothing/glasses/attack_self(mob/user)` и убери всю копипасту

2022-08-23 20:20 UTC, Mercurialaste commented on code/modules/clothing/glasses/glasses.dm
> +/obj/item/clothing/glasses/hud/hos_aug/verb/switch_shade()
Экшен кнопка может сломаться/улететь куда-то, а верб есть всегда.
*(Хотя я просто как ориентир использовал нуарные очки.)*

2022-09-03 14:45 UTC, Mercurialaste commented
wants to merge

2022-09-06 23:44 UTC, Mercurialaste commented
Мерж конфликт из-за Прометея?

2022-09-08 19:36 UTC, Mercurialaste commented
Review me pls

2022-09-10 18:35 UTC, KIBORG04 commented on code/modules/clothing/glasses/glasses.dm
> +
вроде не нужно

2022-09-10 18:36 UTC, KIBORG04 commented on code/modules/clothing/glasses/glasses.dm
> -		return
а вот здесь нужно. Иначе госты будут рофлить)

2022-09-10 18:39 UTC, KIBORG04 approved these changes
вроде ок, кроме тех инкапаситейдов

2022-09-10 19:34 UTC, Mercurialaste commented on code/modules/clothing/glasses/glasses.dm
> -		return
а, брух, я чет только сейчас вчитался, что это не инкараптед...

2022-09-10 22:13 UTC, merged