Добавление прикольностей для астероида и его производных
TauCetiStation/TauCetiClassic pull request #9557
Opened 2022-06-30 01:19 UTC by BiQndy

Очередное обновление от меня для астероида, добавление некоторого количества контента так сказать. Далее всё будет расписано.

## Описание изменений
Пойдём от наиболее интересного:

~Добавлен **новый модификатор** для монстров: Agility(ловкий). Ускоряет монстра на 10% и позволяет ему уклоняться от снарядов в 21% случаях. Под уклонением подразумевается додж самого снаряда и стрейф(движение) в сторону. Т.е. стреляете в ебаку, а она мало того, что уклоняется, так ещё и чуть ближе к вам становится. Бонусы удваиваются, если монстру повезло и он Very Agility(20% ускорения и 42% уклонений).

~Добавлены **новые улучшения** для **кинетика**. Теперь есть 4 вида улучшений и при установке в кинетик они дают следующие бонусы:
Скорость:  -0.35 секунд к перезарядке.
Урон:  +2 к урону.
Дальность: +1 к дальности стрельбы.
Эффективность добычи ресурсов: +25% к выпадаемым минералам с пород.

У каждой характеристики есть свой лимит, выше которого **нельзя** далее бафать.

~Добавлена механика, позволяющая получать **разное количество ресурсов с породы**, в зависимости от используемого инструмента и не только. Конкретнее: стандартный коэффициент выпадения минералов с породы это единица, т.е. дефолт. Резонатором коэффициент 1.25, на 25% чем обычно. Если в породе было 6 минералов, то с резонатором вы получите с неё 8 минералов(т.к. 6*1.25 = 7.5 да ещё и округление в большую сторону). У кувалды коэффициент ресурсов 0.7 и будете получать с породы меньше. **(А что вы хотели, небрежно разламывая горную породу кувалдой?)**

<details> 
  <summary>~Голдграб стал **несколько умнее.** Теперь он будет меньше тупить при виде руды. Теперь после получения урона он будет убегать около 4-х секунд и, если у него после этого короткого побега у него осталось менее 40% здоровья, он будет закапываться в землю С НОВОЙ красивой анимацией!! (спасибо Удаву за анимацию) **А ЕЩЁ БЕРЕГИТЕ СВОИ ЯЩИКИ С РУДОЙ!!** АХАХАХА, теперь Голдграб будет выискивать ящики с рудой(не пустые) и жрать ресурсы прямо из него, попутно повышая своё максимальное здоровье! Повышает здоровье и обычное пожирание руды с пола. Так же Голдграб при движении станит хумана, поэтому не стойте у него на пути лишний раз. Урон зависит от его макс. хп, так что обожравшийся червяк может и убить случайно..</summary>
  
![borrow](https://user-images.githubusercontent.com/43725089/176568523-e098adf2-de32-4796-af41-85b735ab6fb5.gif)

</details>

~Теперь Голдграбу взрывы делают очень.. И очень.. И очень.. Больно.

<details> 
  <summary>~Теперь с Голдграба выпадает не золото, а его особое.. **Ядро!**
Это ядро можно как использовать в руке, тогда оно разломает ближайшие горные породы с коэффициентом дропа минералов равным аж 3! Или же можно обмазать этим ядром кирку или её производные(буры) и повысить им коэф. дропа на 25%.</summary>

https://user-images.githubusercontent.com/43725089/176568290-f55e5034-f85e-421e-a8b8-fcdfd7b2e8d3.mp4

</details>

<details> 
  <summary>~Обновлена форма отображения руд в ящике, теперь здесь картинки!</summary>
   
![new_orebox](https://user-images.githubusercontent.com/43725089/176567250-a2fb7c01-ef37-42eb-8525-f8ab7694c5ad.png)

</details>

<details> 
  <summary>~Теперь лут с монстров после их смерти лежит ПОВЕРХ самих трупов, а не под ними.</summary>
  
![over](https://user-images.githubusercontent.com/43725089/176570175-50163829-ecd4-4a71-b4e1-201ec3628ff0.png)

</details>

~Теперь при получении урона монстр будет незамедлительно искать новую ближайшую к нему цель. Больше не получится "кайтить" с напарником бедных хостайлов.

~Теперь плиты Голиафа чинят некоторые пробои в риге или костюме от физических повреждений. Так же теперь можно применить плиты Голиафа и починить скафандр своему товарищу, просто кликнув по его кукле плитой Голиафа.

<details> 
  <summary>~Новый звук перезарядки кинетика. Новый звук при попадании снаряда Базилиска. Новый звук при спавне говнолута шахтёрской капсулой.</summary>

https://user-images.githubusercontent.com/43725089/176568004-ccd22739-8dff-4e15-baf6-430ac786f8ad.mp4

</details>

~И вот ещё кучка небольших изменений, под которые мне очень лень делать отдельные пункты: 
Кувалда стала чуть реже в луткомнатах. В луткомнате теперь может появиться заброшенный ящик. У резонатора теперь два заряда заместо одного выстрела. Голиаф стал самую малость быстрее(теперь ход раз в 3.7 секунд, было раз в 4 секунды). Голиаф получил резист к бруту в 10%. Щупальца Голиафа теперь немного быстрее подкапывают цель. Если атаковать Голиафа вблизи предметом, то с шансом в 50% под вами он сделает атаку щупальцем. Сварка стала быстрее чинить майнбота. Золотая кирка стала копать быстрее алмазной(hi Minecraft), но у золотой коэф. дроп лута 0.5, а у алмазной 1.2. У майнбота теперь здоровье 150 вместо 140 а так же майнбот получил резит к брут урону в 20%. Майнбот стал ГОРАЗДО меньше тупить при сборе руды. Сейчас он вообще почти не тупит при руде: при сборке одной кучки руды он немедленно бежит к новой кучке руд на полу. Выкапывание песка теперь даёт не стабильные 5 кучек песочка, а рандомно в количестве от 3 до 6. Теперь у монстров, которые стреляют очередями(несколько выстрелов, как у сбойного дрона) время между выстрелами рандомное в интервале от 0.3 до 0.5 секунд, а не стабильные 0.4. Здоровье сбойных дронов снижено с 300 до 250, но добавлен резист к бруту 20%. Немного ослаблена дальность притягивания у сингулярных мобов. Ангельский модификатор теперь даёт более крепкий щит, но он дольше перезаряжается. Голдграб теперь хранит всю съеденную руду в себе, не преумножает её, а просто дропает при смерти, зато всю. Резист к бруту у Базилиска снижен с 50% До 35%. Теперь снаряд Базилиска двигается немногим медленее, давая этим шанс на уклонение.

## Почему и что этот ПР улучшит
Станет немного интереснее быть шахтёром (возможно)
## Авторство
Спрайт закапывания Голдграба подогнал Удав. Спасибо ему за него.
Остальное - я.

## Чеинжлог
some later..

2022-06-30 01:19 UTC, TauKitty commented
###### Changelog status: :radio_button: No changelog

2022-06-30 01:48 UTC, LudwigVonChesterfield commented
это же можно было на несколько ПР-ов разбить?

2022-06-30 01:49 UTC, LudwigVonChesterfield commented on code/modules/roguelike/mob_modifiers/positive.dm
> +	RegisterSignal(H, list(COMSIG_MOB_HOSTILE_BEEN_SHOOTED), .proc/try_mance, override = TRUE)
возможно тут лучше было бы просто вызвать start_mancing

2022-07-02 01:25 UTC, EnshizhArkoshfol commented
Реквестирую поверх этого чудесного ПР'а возможность автоподбора руды с мешком в руке если пройтись по руде/автоподбор руды в ящик если он взят в пул с мешком в руке/без него.

2022-07-02 17:50 UTC, Follint commented
Крутой ПР, без шуток. Пока ты над этой темой трудишься, может, баффнешь немного кирки и буры? Сейчас, особенно после твоего ПРа, они никому нахрен не будут нужны, кинетики делают всё то же самое, но, лучше, быстрее, действуют как оружие, и не имеют шанса оставить чертовы камешки на месте стенки, которые снова нужно ковырять, но, без лута. Мне кажется это несколько странным, учитывая, что кирки - лут астероида, а буры имеют даже улучшенную, и весьма дорогую версию. Было бы неплохо, если бы был выбор у шахтера между инструментами, а не только "КИНЕТИК ПЛЮС ОГРАБИТЬ АРХЕОЛОГОВ РАДИ КИНЕТИКОВ!11!", оставляя буры и кирки абсолютно неюзабельными.

2022-07-02 20:19 UTC, BiQndy commented
В моих планах выпилить нахер "безопасный" и "обычный" режим у буров, ибо этот механ вообще никудышный и хер пойми как работает. А так же к предложению выше насчёт автосбора руды: я планировал это сделать, но для блуспейс шахтёрской сумочки. Насчёт кирок и буров: убрать остающиеся беспонтовые камешки после копания? Что скажете?

2022-07-03 07:53 UTC, Follint commented
Из тех камешков, пусть и редко, но, иногда выпадают разные вещи. Осколки форонового стекла, материалы, странные камни, иногда даже артефакты, но, эти камни больше бесят, чем помогают. Я бы предложил следующее:
Дать археологам складную кирку, влезающую в рюкзак, с мизерным модификатором добычи руды, но, эта кирка могла бы оставлять такие завалы для раскопок, и повысить шанс нахождения окаменелостей, камней и прочей фигни из этих завалов, при этом, убрать шанс появления этих завалов с шахтерских ручных инструментов.
У всех кирок поднять модификатор выкапываемой руды, плюс, ядро червя как улучшение оставить. Может быть, еще повысить урон, что бы если припечет, можно было бы ей отбиваться от фауны, но, урон ниже, чем у кинетика в вакууме. Обычные шахтерские кирки можно оставить как есть, но, всем остальным нужно точно поднимать скорость копания, что бы был смысл их брать и использовать.
Бурам оставить дефолтный модификатор добычи, но, сильно повысить скорость копания, и слегка понизить расход батареи. Допустим, что бы дефолтная батарея позволяла выкопать 200-300 камней перед заменой. Может, несколько повысить модификатор добычи алмазному буру и дать прямо отличную скорость копания, вроде 0.1-0.2 секунд.
Добавить расход батареи Sonic Jackhammer'у и снизить модификатор добычи, но, не сильно, 0.8 должно быть нормально. 150-200 использований с дефолтной батареей будет нормально, лучше обычного бура получится, ибо это лут и разработка РнД. Батарею стоит ему дать, потому что такой же инструмент стоит в шахтерском риге, и он, очевидно, жрет энергию, а ручной инструмент почему-то нет.

Все описанное выше - просто QoL, по сути, а кое-где даже и нерф, и не дает серьезных преимуществ перед кинетиком, тем более, с теми грейдами, которые твой ПР вводит, он все-еще имба. Возможно, стоит добавить кинетику батарею, как у других инструментов, но, опять же, на доминировании кинетика это никак не скажется. Как вариант, который я вижу - дать киркам и бурам возможность при раскопке археологических точек дропать лут с них, включая статуи, есворды, катласы, мечи, и прочее. Может, еще что-нибудь туда добавить, вроде ретро лазеров, унатховских ригов, едаггеров, или и вовсе что-нибудь уникальное, при этом, полностью лишить возможности делать это остальными инструментами шахтера. Понятное дело, что основной дроп был бы в виде окаменелостей, либо странных камней, но, сама возможность уже заставила бы игорьков думать, какой инструмент взять, особенно учитывая модификаторы добычи. И, я думаю, ядру червяка поднять эффект стоит, при использовании на кирку, ибо подобный модификатор для кинетика добавляешь, а червя еще пойди-найди-убей, так и поставить можно будет на менее эффективный инструмент, либо просто в руке юзануть с кинетиками можно, для stonks с фороном, или алмазами.

Еще, стационарные буры меня несколько в ступор вводят. Их используют либо в самом начале смены для дополнительных ресурсов и очков, либо если шахтеров нет вообще, и копать кому-то нужно. Больше эти буры никому ни для чего не нужны. Честно, я даже не знаю, апгрейдятся ли они лучшими деталями из РнД, или нет. Не уверен, даже, можно ли с ним что-нибудь сделать, и стоит ли.

В целом вот, мои мысли.

2022-07-03 13:40 UTC, volas commented
> это же можно было на несколько ПР-ов разбить?

и я тут с такой же реакцией и пошел дальше

2022-07-04 22:10 UTC, LudwigVonChesterfield requested changes
разбей на отдельные ПР-ы пожалуйста, модификатор никак не зависит от ящичков, а ящички от цен в вендомате, а цены от реворка резонатора.

2022-07-05 07:50 UTC, BiQndy commented
> разбей на отдельные ПР-ы пожалуйста, модификатор никак не зависит от ящичков, а ящички от цен в вендомате, а цены от реворка резонатора.

Окей, я попробую это сделать, но всегда сторонился изменять одни и те же файлы в разных ПРах, потому что я не понимаю, как фиксить конфликты, это сложно. Ну ладно

2022-07-06 22:05 UTC, BiQndy commented
> разбей на отдельные ПР-ы пожалуйста, модификатор никак не зависит от ящичков, а ящички от цен в вендомате, а цены от реворка резонатора.

Не знаю, правда, как разбить. Все названные категории связаны, исключением можно модификатор назвать, да, его можно вынести в отдельный. К примеру в ящичках фигурируют новые апгрейды, обновлённые цены в вендомате так же зависимы от апгрейдов, потому что они туда добавляются, реворк резонатора зависим от новой механики зависимости выпадаемой руды и тд

2022-07-07 14:38 UTC, BiQndy commented on code/modules/mining/mine_items.dm
> +	var/recharge_time_limit = 1.4 SECOND
Мб сделать это дейфайнами?

2022-07-07 14:38 UTC, BiQndy commented on code/modules/mining/minerals.dm
> -	var/ore_loss = 0
result_amount вообще не использовался нигде, а ore_loss теперь не нужен, т.к. теперь кол-во руды можно контролировать

2022-08-02 17:50 UTC, BiQndy commented
В этом ПРе изменения слишком сплетены(за малым исключением), разбить его особо не получится. Я могу удалить какие то изменения, если так можно

2022-08-12 02:43 UTC, volas commented
![Снимок экрана от 2022-08-12 05-42-20](https://user-images.githubusercontent.com/4064061/184275174-9f68a205-081f-4ad3-a29b-4d371979c5b3.png)
каждый из этих пунктов можно залить отдельно, я не вижу как они были бы связанны. Может быть еще объединить небольшие тематические, типо отдельный пр с Голдграбом

2022-08-19 04:32 UTC, volas commented
Я не смогу уделить время и просмотреть и оценить всю сборку сразу. Просьба разбить на отдельные PR-ы.

2022-08-19 04:32 UTC, closed without merging

2022-08-19 04:43 UTC, Deahaka commented
Жесть, этот ПР сделал почти всё, что я придумал сделать вчера, но его погубил дифф...

2022-08-19 04:44 UTC, volas commented
можешь помочь автору с распилом

2022-08-20 19:33 UTC, Deahaka commented
Ладно я посмотрел весь дифф и я совсем не такое хотел. Распил отменяется.

2022-08-21 05:36 UTC, BiQndy commented
Ближе к сентябрю смогу взяться за этот ПР и всё же попробую засплитить его. @Deahaka , а что ты придумал для шахты, ежели не секрет?

2022-08-21 06:02 UTC, Deahaka commented
Улучшить интеллект мобов астероида, разбить инструментам колличество ресурсов добываемых, сделать улучшения более полезными (например алмазный бур в три раза больше ресурсов добывает, чем обычный)