Rcd
TauCetiStation/TauCetiClassic pull request #9562
Opened 2022-06-30 18:44 UTC by Risraivyn

## Описание изменений
Добавил проверку на постройку рсд стен. Фикс #9481
## Почему и что этот ПР улучшит
Теперь нельзя строить стены под себя, на столе, под непроходимые объекты.
## Авторство
Risraivyn
## Чеинжлог
:cl: 
- bugfix: Исправил постройку стен у RCD

2022-07-01 02:59 UTC, kiVts commented on config/example/admins.txt
> +Risraivyn - Host
хихи

2022-07-01 09:10 UTC, Risraivyn commented on config/example/admins.txt
> +Risraivyn - Host
А почему бы и нет?

2022-07-01 11:31 UTC, volas commented on config/example/admins.txt
> +Risraivyn - Host
Лучше убрать, а то окажешься потом хостом на чьей-то локалке, не очень хорошо

2022-07-01 12:53 UTC, Risraivyn commented on code/game/objects/items/weapons/RCD.dm
> +					if(AT.density || istype(AT, /obj/machinery/door) || istype(AT, /obj/structure/mineral_door))
Ошибка логики. Створка та же дверь, какой смысл делать стену в двери?

2022-07-02 08:07 UTC, volas commented on config/example/admins.txt
> -# not_a_user - Admin
ты перестарался. Сделай что-то вроде
``git checkout upstream/master config/example/admins.txt``
и закоммить обратно

2022-07-03 13:44 UTC, volas requested changes
зря удален конфиг

2022-07-08 06:03 UTC, volas commented on code/game/objects/items/weapons/RCD.dm
> +		return 0
тут у тебя какая-то ошибка с отступами

2022-07-08 06:03 UTC, volas commented on code/game/objects/items/weapons/RCD.dm
> +				if(useResource(1, user) || canBuildOnTurf(S))
1. нету сообщения
2. в одном месте у тебя возврат функции True означает, что строить можно. В другом означает, что строить нельзя

2022-07-08 08:09 UTC, Risraivyn commented on code/game/objects/items/weapons/RCD.dm
> +		return 0
![image](https://user-images.githubusercontent.com/44939241/177947392-161fc4cf-e019-4d78-815f-447578497518.png)

2022-07-09 07:41 UTC, volas commented on code/game/objects/items/weapons/RCD.dm
> +					to_chat(user, "<span class='warning'>You can't build Wall here.</span>")
```suggestion
					to_chat(user, "<span class='warning'>You can't build wall here.</span>")
```

2022-07-09 07:46 UTC, volas commented on code/game/objects/items/weapons/RCD.dm
> +			if(isenvironmentturf(target)
```suggestion
			if(isenvironmentturf(target))
```
mergefix

2022-07-09 07:47 UTC, volas commented on code/game/objects/items/weapons/RCD.dm
> +				var/turf/space/S = target
```suggestion
				var/turf/T = target
```

2022-07-09 07:47 UTC, volas approved these changes

2022-07-09 07:49 UTC, volas commented on code/game/objects/items/weapons/RCD.dm
> +				if(!canBuildOnTurf(S))
```suggestion
				if(!canBuildOnTurf(T))
```

2022-07-09 07:52 UTC, merged