Анализатор газов в токсинную и атмос
TauCetiStation/TauCetiClassic pull request #9567
Opened 2022-07-01 18:30 UTC by Tap0r

## Описание изменений
В токсинную и атмос добавлены машинки для анализа газов. На данный момент толку от них немного, но следующими ПРами я намерен добавить:
1. Рандомизацию значения теплоёмкости у горючих газов, чтобы учёным перед сборкой лимиток нужно было сканировать газ (находить теплоёмкость) и расчитывать из полученного значения необходимую температуру нагрева.
2. Получение очков за сканирование определённых газов при определённых температурах.

![1](https://user-images.githubusercontent.com/88531962/176950999-d693fb74-9542-4c38-9f09-f5ed795407cf.png)
![image](https://user-images.githubusercontent.com/88531962/176951288-3907ff30-8b65-4ed0-8896-cfdcb29fe502.png)
https://forum.taucetistation.org/t/mysli-o-peredelke-rnd/34301/90

## Почему и что этот ПР улучшит
Разнообразит геймплей токсинной
## Авторство
я
## Чеинжлог
:cl:
 - add: В токсинную и атмос добавлен анализатор газов.

2022-07-01 18:30 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2022-07-01 18:30 UTC, TauKitty commented
Этот запрос на извлечение был упомянут в **Tau Ceti Station Forum**. Там могут быть соответствующие подробности:

https://forum.taucetistation.org/t/mysli-o-peredelke-rnd/34301/93

2022-07-02 06:01 UTC, WatlerJe commented
Какая-то нездоровая тяга к сферам... ballz

2022-07-02 08:05 UTC, TungstenOctopus commented
![image](https://user-images.githubusercontent.com/6051766/176992272-ea67166e-2f36-45bd-89f9-3854a85af56e.png)
![image](https://user-images.githubusercontent.com/6051766/176992288-938b7377-a85e-4021-814d-39cd6c2907b5.png)

2022-07-02 08:56 UTC, UDaV73rus requested changes
На трубе стремненький блик который ломает глаза и всю перспективу. 
Не стесняйся показывать крутой объем делая освещение под интересным углом, а не просто сверху
![image](https://user-images.githubusercontent.com/33157992/176993323-2a57f2cf-41cc-4934-963f-2a6b8d2347f0.png)

Ещё возможно лишние тени снизу машинки, чисто аутлайна по идее должно хватать. Такое количество переходов из тени в тень очень грязнит спрайты

А мозг реально не понятно почему мозг и игроков будет путать и пугать. Потому что делая как газовые ballz, они вообще не так нарисованы, и дело не в том что места мало.
Но лучше не заморачиваться и сделать просто шаром без разреза.

2022-07-06 13:52 UTC, Tap0r commented
ПР закрывается и уходит на переперделку

2022-07-06 13:52 UTC, closed without merging