Right click on prefs
TauCetiStation/TauCetiClassic pull request #9590
Opened 2022-07-06 09:45 UTC by Chip11-n

Не знаю как вас, но меня это всегда вымораживало просто
## Описание изменений
Вот вас никогда не раздражало, что если вы случайно нажмёте дважды мышкой на префы работы, и выставите вместо high на never, вам нужно жать ещё целых три раза, вместо того, чтоб просто в другую сторону нажать один раз? Исправлено! Теперь, нажав на ПРАВУЮ кнопку мыши, вы УМЕНЬШИТЕ преф на работу
## Почему и что этот ПР улучшит
QoL
## Авторство
Древний код, Carn
## Чеинжлог
:cl: Chip11-n
- tweak: Нажав правой кнопкой мыши на работы, вы уменьшите её приоритет

2022-07-06 11:15 UTC, Zmey25 commented
лучшее что происходило с тау

2022-07-07 06:43 UTC, notkripton commented
Сделайте лучше чтобы оно на кружочках выбиралось как на тг

2022-07-13 14:07 UTC, Sakuya-Izayoi commented on code/modules/client/character menu/occupation.dm
> +		if(1)
магические числа заменить на дефайны

2022-07-27 14:58 UTC, Mercurialaste commented
Кхм… Алло?

2022-07-29 15:44 UTC, volas requested changes
Небольшие комментарии выше. Мне очень не нравится дублирование логики с ID-шниками на самом ивенте клика и при генерации шаблона.

2022-08-07 09:08 UTC, Chip11-n commented
Переделал. Убрал скрипт, переставил уровни в сам момент изменения уровней, но убрал установку уровней точную. Впрочем, это не должно быть важно.

2022-08-09 14:33 UTC, Chip11-n commented
Тут нужно что-то ещё менять?

2022-08-12 02:46 UTC, volas approved these changes

2022-08-12 02:46 UTC, merged