Toolboxhammer
TauCetiStation/TauCetiClassic pull request #9595
Opened 2022-07-07 08:13 UTC by Tap0r

## Описание изменений
Добавляет возможность сделать молот из пустого тулбокса и палочки с проводами.
![1](https://user-images.githubusercontent.com/88531962/177724382-db8bce15-6f47-422b-b042-76a466b1bee1.PNG)
![image](https://user-images.githubusercontent.com/88531962/177724656-b85f104c-4fac-49ef-88b5-4ff172582852.png)

## Почему и что этот ПР улучшит
Больше смешного оружия ассистухам

## Авторство
я

## Чеинжлог
:cl:
 - add: Добавлен тулбоксомолот.

2022-07-07 08:13 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2022-07-12 03:26 UTC, UDaV73rus approved these changes

2022-07-12 05:45 UTC, volas commented on code/game/objects/items/weapons/storage/toolbox.dm
> +	empty = TRUE
Как вариант, раз всё равно создаешь новые классы, можно избавиться от костыля с empty - взять дефолтный ``/obj/item/weapon/storage/toolbox`` и указать ему стейты и имена.

С другой стороны, текущий вариант будет надежнее из-за наследования этих самых имен и стейтов.

2022-07-12 05:45 UTC, volas commented on code/game/objects/items/weapons/makeshift.dm
> +		if(istype(I, /obj/item/weapon/storage/toolbox/mechanical))
Ошибка удалять предмет I, а потом обращаться к его типу

2022-07-12 05:45 UTC, volas commented on code/game/objects/items/weapons/makeshift.dm
> +/obj/item/weapon/wirerod/attackby(obj/item/I, mob/user, params)
У нас есть еще что-то самопальное, что делается кликами а не через крафт меню?

Крафт меню предпочтительнее, где всё систематизировано и в одном месте.

2022-07-12 06:46 UTC, Deahaka commented on code/game/objects/items/weapons/makeshift.dm
> +/obj/item/weapon/wirerod/attackby(obj/item/I, mob/user, params)
Крафт меню отстой, всё что собирается кликами, а лучше радиалкой на клик по себе, намного лучше (пример ТГ должен учить как делать не стоит)

2022-07-12 06:50 UTC, Mercurialaste commented on code/game/objects/items/weapons/makeshift.dm
> +/obj/item/weapon/wirerod/attackby(obj/item/I, mob/user, params)
> У нас есть еще что-то самопальное, что делается кликами а не через крафт меню?
> 
> Крафт меню предпочтительнее, где всё систематизировано и в одном месте.

Огнемет, если память не изменяет.

2022-07-12 07:14 UTC, volas commented on code/game/objects/items/weapons/makeshift.dm
> +/obj/item/weapon/wirerod/attackby(obj/item/I, mob/user, params)
Крафт в одном месте > разбросанный по билду в атакбей. Сам крафт из крафт меню можно переделать как угодно и даже сделать кликами, лишь бы все его использовали.

2022-07-12 07:28 UTC, Deahaka commented on code/game/objects/items/weapons/makeshift.dm
> +/obj/item/weapon/wirerod/attackby(obj/item/I, mob/user, params)
Примеры как есть уже работают против аргумента что должно быть в этом конкретном ПРе иначе. см. инструменты инженеров

2022-07-15 02:54 UTC, volas requested changes
как минимум, ошибка с qdel

2022-07-20 17:23 UTC, Tap0r commented on code/game/objects/items/weapons/makeshift.dm
> +		if(istype(I, /obj/item/weapon/storage/toolbox/mechanical))
Пофиксил?

2022-07-20 18:28 UTC, volas approved these changes
про крайт-меню я когда нибудь отдельное ишью составлю

2022-07-20 19:02 UTC, Sakuya-Izayoi commented on code/game/objects/items/weapons/makeshift.dm
> +			TB.add_fingerprint(user)
унылый копипаст. представь сколько работы нужно сделать, если человек вдруг захочет создать новый тип тулбокса. сделай чтобы оно триггерилось на один /obj/item/weapon/storage/toolbox, а спрайт и название выбиралось исходя из параметров самого тулбокса. бонус поинтс если сделаешь чтобы урон тоже наследовался от тулбокса. ну и удалять себя смысла нет, можно перемещать этот самый тулбокс в молот.

2022-07-28 22:08 UTC, Shootnik01 commented
Каждый ассистент после этого иссуя: https://youtu.be/sQfk5HykiEk?t=118

2022-08-15 06:04 UTC, Tap0r commented
тише-тише-тише

2022-08-19 04:31 UTC, volas commented
просьба переоткрыть, когда будет поправлено и вновь актуально

2022-08-19 04:31 UTC, closed without merging

2022-12-06 19:17 UTC, TauKitty commented
Этот запрос на слияние был упомянут в **Tau Ceti Station Forum**. Там могут быть соответствующие подробности:

https://forum.taucetistation.org/t/hotite-li-vy-dobavlenie-novyh-kraftov/36648/21