Новый дереликт
TauCetiStation/TauCetiClassic pull request #9610
Opened 2022-07-10 18:04 UTC by IlinMihail

## Описание изменений
новый дереликт для любителей телесала

## Почему и что этот ПР улучшит
+гост ролька, +новый дереликт

## Авторство

## Чеинжлог
:cl: M104
- add: Новый дереликт

2022-07-10 18:04 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2022-07-10 18:09 UTC, IlinMihail commented
хуки...

2022-07-10 18:11 UTC, Chip11-n commented
"желательно ссожите после прочтения"

2022-07-10 18:12 UTC, IlinMihail commented
кхм, опечатка

2022-07-10 20:52 UTC, KIBORG04 commented on code/datums/spawners_menu/spawners.dm
> +/datum/spawner/derelict
назови уникальнее

2022-07-11 15:37 UTC, Tap0r commented
Замаплено плохо, даже очень, могло бы быть намного лучше. Если будет желание полностью её переделать, то отпиши в дискорде, могу помочь с этим. 
Но вообще в целом пойдёт, это же не станция, а просто дерелик, который за раунд ну человек 5 максимум посетят.

2022-07-11 15:54 UTC, AndroBetel commented
где тиран спейр

2022-07-11 16:00 UTC, IlinMihail commented
да спеир не нужен, я уже начал переделывать

2022-07-14 15:03 UTC, IlinMihail commented
переделал, вроде чуточку лучше, если что дефор сказал что потом ремапнет

2022-07-14 15:19 UTC, Tap0r commented
Сделай пжпжпж нормальную красивую плитку.
![2](https://user-images.githubusercontent.com/88531962/179017599-8f67a4e9-b92e-48d5-8217-1cadf6cae180.png)
![1](https://user-images.githubusercontent.com/88531962/179017592-b2d02fe6-bf6c-408e-b3d3-8ccdb17272fd.png)

Я не буду просить там изменений отсеков или ещё чего, ну просто плитку красивую, чекни как на боксе, как на фалконе сделано.

2022-07-14 15:20 UTC, Tap0r commented
Токамак на дерелике супер круто.

2022-07-14 15:45 UTC, IlinMihail commented
блин, ну ладно

2022-07-14 16:55 UTC, IlinMihail commented
всё сломалось...

2022-07-21 02:58 UTC, volas requested changes
Это охренеть какой огромный дереликт с кучей процессящейся техники и 38(!!!) мобами. Нужно его здорово облегчать, или перевести в разряд away-миссий за гейтом.

2022-07-21 04:44 UTC, Deahaka commented
Или сломать там всё)

2022-07-21 10:17 UTC, IlinMihail commented
не, ну тогда закрываю. мобы и техника ещё ладно, можно поломать немного, а размеры я уменьшать не хочу, ибо у меня ощущение что так станет ещё кривее и уродливее. в гейт переносить смысла не вижу, ибо его открывают раз в 1000 лет, и в основном только на пляж.

2022-07-21 10:17 UTC, closed without merging

2022-07-21 14:44 UTC, volas commented
Сам по себе размер может быть и не проблема, проблема в наполнении, которое будет несправедливо грузить сервер.

Карты гейта - потому и не запускают, что там либо сломано, либо делать нечего, сделаете какие-нибудь интересные карты - будут запускать.

2022-07-21 14:46 UTC, AndroBetel commented
а лучше сделать возможность игрокам их самостоятельно запускать и экспедиции организовывать, только чтобы хардкорные были обязательно

2022-07-21 15:07 UTC, Deahaka commented
> а лучше сделать возможность игрокам их самостоятельно запускать и экспедиции организовывать, только чтобы хардкорные были обязательно

Вот бы информация на вики была бы правдой...

2022-07-21 16:23 UTC, Tap0r commented
Я когда-то хотел начать ремапить карты гейта. Даже вроде академию магов трогать начал. Но потом посмотрел, подумал. И расхотел. 
А вообще, зря пр закрыл. Тут же действительно всякого поубирать немного и пойдёт.