Рефактор спасательного ломика
TauCetiStation/TauCetiClassic pull request #9614
Opened 2022-07-11 09:40 UTC by notkripton

## Описание изменений
Эмердженси кроубар получил новый спрайт и функционал.

![image](https://user-images.githubusercontent.com/75007994/178230848-708f4633-1e09-4158-adcd-476e7cea022d.png)
(микрочел)

Мини-ломик больше не требует скиллов для использования и помещается в карман. Используется он для открытия обесточенных шлюзов и пожарных створок и делает это теперь в два раза быстрее обычного. Однако разбирать машинки, стены и т.д. с его помощью нельзя.

https://user-images.githubusercontent.com/75007994/178233179-a34288b9-f9be-4688-84bf-12227929833f.mp4

Также на карте их стало больше, добавил их в: 
* Эмердженси тулбоксы. В сумме их теперь три, а не один.
* В сб-вендомат в (6 штук).
* В кабинеты глав с ригами.
* В разные места и в теха (пожарные ящики и т.д.).
## Почему и что этот ПР улучшит
Теперь разным профессиям, которым лом нужен просто как открывашка не будет нужды лутать инженерный ломик. Также гораздо меньше людей будет застревать на шаттле велосити или в своих отсеках если на дверях нет питания.
## Авторство
я
## Чеинжлог
:cl:
 - tweak[link]: Обновлен функционал спасательного ломика.
 - map: На карты добавлено больше спасательных ломиков.

2022-07-12 03:33 UTC, UDaV73rus commented
инхенды будут?

2022-07-12 05:51 UTC, volas commented
Так можно и доступы всем профам дать на эти двери.

2022-07-15 03:58 UTC, volas commented
Насколько понимаю историю вопроса:
Люди бегают по станции и разносят разгермы ->
Добавляем аварийные створки ->
Люди не обращают внимания и всё равно ломятся в них ->
Добавляем открытие на доступы лишь определенным профам, остальным аварийную механику открытия ломом, который еще нужно найти  ->
... ->
добавляем больше ломов на станцию, что бы остальные могли открывать эти двери(???)

Это еще опуская момент, что фаердоры проверяют давление и вроде как пускают и так, если проблем нет.

Единственный хороший аргумент - это про двери без питания на велосити, но я бы предложил сделать это отдельным типом дверей с аварийной ручкой, которая будет работать при отсутствии питания, и разместить их где требуется. Что бы решить конкретную проблему, и не затрагивать остальные механики.

В остальном, не вижу причин просто не добавить доступы тем профам, кому это требуется.

2022-07-15 03:58 UTC, volas requested changes
^

2022-07-15 04:04 UTC, Mercurialaste commented
Из того что мне приходит в голову, так это то, что резиновые двери, способные выдержать любую температуру и давление, сложно таскать. Т.е. ты должен в еве заранее взять себе ящик, если ты парамед, или если ты атмостех, вынести его поближе, а потом, в час X, занимая слот руки бежать на место. 

В теории, если бы ящик с дверьками можно было повесит на ремень или на риг/пожарный костюм, было бы норм. Ну и самих пожарных костюмов по больше, тк, сейчас больше евросов чем их.

2022-07-18 00:40 UTC, kiVts commented
все время пока играл на бее или нсв и смоттрел на крутой механ двух аварийных створок которые работают как шлюз, я уверен вы знаете о чем я

2022-07-20 07:14 UTC, notkripton commented
> добавляем больше ломов на станцию, что бы остальные могли открывать эти двери(???)

@volas Открытие ломом как и было аварийным вариантом так и остается. Одно дело когда болваны открывают двери имея доступ, а другое когда берут для этого специальный предмет и делают это целенаправленно без "а я не заметил что она мигает". Это вариант больше в тг логику, где доступа нету ни у кого и ты либо открываешь ломом либо ждешь пока починят.
Еще открывашки нужны людям во время шлингов и ночнораундо-2-3 серверов, когда станция по кд без электричества и все ломы с карты лутаются просто открывать двери без питания. Вместо этого теперь для людей лежат специальные открывашки.

2022-07-20 07:15 UTC, Deahaka commented
Так вроде на ТГ всё через пожарную тревогу можно снимать, как и у нас

2022-07-20 07:19 UTC, notkripton commented
Вообще этот пр больше про ребаланс именно ломика. Сейчас, если что, это просто лом, но занимающий в 3 раза меньше места в инвентаре. Механом они почти не отличаются, за что его и лутают более проворные игроки. Если вопросы только про изобилие предметов на открытие дверей, то все мапоизменения можно вынести в отдельный пр, допустим.

2022-07-20 07:21 UTC, notkripton commented
> Так вроде на ТГ всё через пожарную тревогу можно снимать, как и у нас

я имел ввиду открытие ручками одной конкретной створки

2022-07-21 02:34 UTC, volas commented
> Еще открывашки нужны людям во время шлингов и ночнораундо-2-3 серверов, когда станция по кд без электричества и все ломы с карты лутаются просто открывать двери без питания

Может стоит просто на фалкон больше обычных ломов добавить.

> Если вопросы только про изобилие предметов на открытие дверей, то все мапоизменения можно вынести в отдельный пр, допустим.

Смысла в пр-е с одним ломом нету, если его не положить куда-то.


Мне не принципиально, но в текущем виде это какое-то корявое решение проблем. Плодить новые сущности, нивелировать суть фаерлоков, ломов... Можешь попробовать подергать других мейнтейнеров, может они увидят больше смысла в этом.

2022-07-31 18:46 UTC, notkripton commented
В общем никто так и не отметился тут, попробую пинг @Maintainer

> Может стоит просто на фалкон больше обычных ломов добавить.

Корявое решение, у нас совсем недавно поднимался вопрос об изобилии общедоступных тулзов, да и стандартные ломы далеко не только для дверей используются.

> Смысла в пр-е с одним ломом нету, если его не положить куда-то.

> Плодить новые сущности

Этот лом не новый айтем, он уже есть в билде и является абузной версией обычного лома, когда имея такой же функционал он занимает в три раза меньше места в сумке.
Этот пр оставляет ему лишь тот функционал, который ему задуман.

2022-07-31 18:51 UTC, volas commented
> Корявое решение, у нас совсем недавно поднимался вопрос об изобилии общедоступных тулзов, да и стандартные ломы далеко не только для дверей используются.

ты поднимаешь вопрос про конкретную проблему фалкона, я и пишу, что можно её только там и решать добавлением инструментов, не зависимо от других карт, где может быть а может и не быть проблема с изобилием инструментов.

2022-08-25 07:27 UTC, closed without merging