Кормушка
TauCetiStation/TauCetiClassic pull request #9615
Opened 2022-07-11 09:43 UTC by FatFatFat1

## Описание изменений
Кормушка для куриц.
## Почему и что этот ПР улучшит
Теперь курицы будут сами кормиться из кормушки, можно не отвлекаться на них
## Авторство
🆑 FatFat , Udav
## Чеинжлог
- rscadd : Кормушка для куриц

2022-07-11 09:43 UTC, TauKitty commented
###### Changelog status: :x: Empty changelog (check markdown correctness)

2022-07-11 11:19 UTC, KIBORG04 commented on code/game/objects/structures/chicken_feeder.dm
> +	..()
Вместо этого у нас есть дефайн ADD_TO_GLOBAL_LIST, заюзай лучше его

2022-07-11 11:45 UTC, FatFatFat1 commented on code/game/objects/structures/chicken_feeder.dm
> +	..()
чек

2022-07-13 14:20 UTC, Sakuya-Izayoi requested changes

2022-07-13 14:20 UTC, Sakuya-Izayoi commented on code/game/objects/structures/chicken_feeder.dm
> +/obj/structure/ch_feeder
совсем не обзательно давать такое короткое название классу. chicken_feeder -- вполне сносно, хоть и длиннее, но намного понятние

2022-07-13 14:20 UTC, Sakuya-Izayoi commented on code/game/objects/structures/chicken_feeder.dm
> +	if(food >=8)
пробелы после оператора, также магические числа

2022-07-19 07:41 UTC, TungstenOctopus commented
А где скрины спрайтов

2022-07-20 10:51 UTC, FatFatFat1 commented
Добавил дефайны и прок кормежки.
По поводу кормежки единым проком и у курицы и у кормушки , расскажи подробнее

2022-07-29 15:52 UTC, volas commented on code/game/objects/structures/chicken_feeder.dm
> +/obj/structure/ch_feeder
"чё фидер" действительно ужасное название, не экономьте на символах

2022-07-29 15:54 UTC, volas commented on code/game/objects/structures/chicken_feeder.dm
> +			update_icon()
Не обязательно, держать лишние объекты в памяти такое себе.

2022-08-17 17:19 UTC, FatFatFat1 commented
[Sakuya-Izayoi](https://github.com/Sakuya-Izayoi) приди

2022-08-19 04:44 UTC, volas commented
пока ты не переименуешь "че финдер", мейнейнеры не позвонят

2022-08-19 10:22 UTC, FatFatFat1 commented
а , не увидел это

2022-08-19 11:07 UTC, FatFatFat1 commented
готово

2022-08-24 10:41 UTC, FatFatFat1 commented
гетап приди гетап приди

2022-08-27 06:33 UTC, volas requested changes

2022-08-27 06:33 UTC, volas commented on code/game/objects/structures/chicken_feeder.dm
> +			food += 1
у reagent_containers есть ведь volume, возможно не нужно тут всю пачку за 1 считать?

2022-08-27 06:33 UTC, volas commented on code/modules/mob/living/simple_animal/friendly/farm_animals.dm
> +	stop_automated_movement = FALSE
в каком-то условии флаг должен возвращаться обратно

2022-08-27 06:33 UTC, volas commented on code/modules/mob/living/simple_animal/friendly/farm_animals.dm
> +						step_to(src, C)
get_dist работает через z-уровни, и при некоторых обстоятельствах курица будет пытаться через пространство дойти до кормушки. Можно сделать еще проверку на z-уровень, или просто иметь в виду и не ставить их на дереликтах и цк, и контролировать, что бы никто другой не ставил.

2022-08-27 07:05 UTC, FatFatFat1 commented on code/game/objects/structures/chicken_feeder.dm
> +			food += 1
Пшено нельзя стакать , значит считать за 1 справедливо (А volume вообще = 50)

2022-08-27 07:22 UTC, FatFatFat1 commented on code/modules/mob/living/simple_animal/friendly/farm_animals.dm
> +						step_to(src, C)
получить как-то другую кормушку невозможно , она изначально одна. Так что только дериликты контролировать (Но кто вообще захочет сделать космо-курятник?)

2022-08-27 07:25 UTC, volas commented on code/modules/mob/living/simple_animal/friendly/farm_animals.dm
> +						step_to(src, C)
> Но кто вообще захочет сделать космо-курятник

кто-то может и захочет

2022-08-27 07:40 UTC, FatFatFat1 commented on code/modules/mob/living/simple_animal/friendly/farm_animals.dm
> +						step_to(src, C)
добавил проверку на z

2022-08-27 11:46 UTC, volas commented on code/modules/mob/living/simple_animal/friendly/farm_animals.dm
> +	if(!stat && !ISDIAGONALDIR(Dir))
человек старался, исправлял, а ты... https://github.com/TauCetiStation/TauCetiClassic/pull/9857

2022-08-27 12:12 UTC, FatFatFat1 commented on code/modules/mob/living/simple_animal/friendly/farm_animals.dm
> +	if(!stat && !ISDIAGONALDIR(Dir))
оно само както после мержа с мастером , щас вроде вернулось

2022-08-27 12:35 UTC, volas commented on code/modules/mob/living/simple_animal/friendly/farm_animals.dm
> +	if(!stat && !ISDIAGONALDIR(Dir))
ты возможно не ту стратегию при мерже выбрал, оно не должно было измениться у тебя. Сейчас это частичный откат 9857

2022-08-27 13:12 UTC, FatFatFat1 commented on code/modules/mob/living/simple_animal/friendly/farm_animals.dm
> +	if(!stat && !ISDIAGONALDIR(Dir))
вернул

2022-08-27 13:16 UTC, volas approved these changes

2022-08-27 13:16 UTC, merged