Runtimes
TauCetiStation/TauCetiClassic pull request #9645
Opened 2022-07-15 14:39 UTC by Chip11-n

## Описание изменений
Фикс нескольких наиболее заметных [рантаймов] (https://cdn.discordapp.com/attachments/818540839005323316/997215919174590494/rtsurvey.txt) (1-й, 2-й, 3-й, 6-й, 7-й)

Напишите, если я где-то накосячил. Вроде оно должно рантаймить чуток меньше.
## Почему и что этот ПР улучшит
Немного раундстартом меньше будет дёргать, надеюсь
## Авторство

## Чеинжлог
Не стоит, думаю?

2022-07-15 14:39 UTC, TauKitty commented
###### Changelog status: :radio_button: No changelog

2022-07-15 14:46 UTC, KIBORG04 commented
Ты накосячил много где.
1. Это 1 пр, а не несколько.
2. Нет тела рантайма, а только его заголовки.
3. Это не фикс проблемы, а сокрытие симптомов проблемы. У тебя так же где-то будет приходить null, но так как ты тыкнул "?" нулла как-бы нет, но он есть.

У нас где-то был гайд по фиксам рантаймов, мб в конвенции, мб в гайде контрибутинга.

2022-07-15 15:00 UTC, KIBORG04 commented on code/modules/religion/altar_types/altar_of_gods.dm
> +	if(!religion && user?.my_religion?.religious_tool_type && istype(I, user.my_religion.religious_tool_type))
Че за фикс, в твоем файле про это ниче нету

2022-07-15 15:01 UTC, Chip11-n commented on code/modules/religion/altar_types/altar_of_gods.dm
> +	if(!religion && user?.my_religion?.religious_tool_type && istype(I, user.my_religion.religious_tool_type))
Про это забыл. Рантайм вылазит, если без религии любой с holy_role ударит нуллродом по алтарю

2022-07-15 15:02 UTC, KIBORG04 commented on code/game/gamemodes/modes_gameplays/abduction/machinery/console.dm
> +	if(!issilicon(user) && !IsAbductor(user) && !isAI(user) && !isobserver(user))
проверка на исАИ не нужна теперь

2022-07-15 15:03 UTC, KIBORG04 commented on code/modules/religion/altar_types/altar_of_gods.dm
> +	if(!religion && user?.my_religion?.religious_tool_type && istype(I, user.my_religion.religious_tool_type))
А эээ. Как holy_role может быть без религии?

2022-07-15 15:03 UTC, Chip11-n commented on code/modules/religion/altar_types/altar_of_gods.dm
> +	if(!religion && user?.my_religion?.religious_tool_type && istype(I, user.my_religion.religious_tool_type))
Да очень просто. Она у разума, а не у религии или алтаря

2022-07-15 15:04 UTC, KIBORG04 commented on code/game/objects/effects/spiders.dm
> +	forceMove(entry_vent?.loc)
Это похоже на ленивый фикс

2022-07-15 15:05 UTC, KIBORG04 commented on code/modules/religion/altar_types/altar_of_gods.dm
> +	if(!religion && user?.my_religion?.religious_tool_type && istype(I, user.my_religion.religious_tool_type))
Ну ты щас описал то, что и приводит к рантайму. По задумке, holy_role и religion не могут существовать друг без друга, холи_роль уже даже легаси скорее.

2022-07-15 16:32 UTC, kalazus commented on code/modules/religion/altar_types/altar_of_gods.dm
> +	if(!religion && user?.my_religion?.religious_tool_type && istype(I, user.my_religion.religious_tool_type))
По задумке могут. Вроде у паранормальщака до сих пор есть самая нижняя holy_role для взаимодействия с некоторыми осквернёнными штукам.

2022-07-15 16:34 UTC, kalazus commented on code/game/objects/effects/spiders.dm
> +	forceMove(entry_vent?.loc)
Это хуже ведь паук похоже может уйти в нуллспейс не удалившись.

2022-07-15 17:14 UTC, Chip11-n commented on code/game/objects/effects/spiders.dm
> +	forceMove(entry_vent?.loc)
А он что делает, если проверка прерывается?

2022-07-15 17:26 UTC, kalazus commented on code/game/objects/effects/spiders.dm
> +	forceMove(entry_vent?.loc)
Ничего, но лучше получить рантайм, чем существо в нуллспейсе.

2022-07-16 11:06 UTC, kalazus commented on code/modules/religion/aspect.dm
> +		return
Это вообще говоря просто скрытие проблемы т.к. почему-то турф пересчитывает фавор, когда с него уже пропал holy датум.

2022-07-17 17:42 UTC, Chip11-n commented on code/modules/mob/living/silicon/robot/robot_modules.dm
> +	if(B?.charges < 10)
Мне его выпилить?

2022-07-17 17:52 UTC, Chip11-n commented on code/modules/religion/aspect.dm
> +		return
Лайтбенд вообще какой-то чумной. Сейчас на локалке тещу, и у меня, откровенно говоря, ебанутая ситуация, когда несуществующий аспект пытается считать свой фавор. Так что да, лучше я туда не буду лезть.
![image](https://user-images.githubusercontent.com/50750952/179418404-3a10c463-0d9c-4703-9002-3d5d1101813d.png)
![image](https://user-images.githubusercontent.com/50750952/179418417-9537c701-71d1-4180-8633-d3417b37103b.png)

2022-07-17 19:46 UTC, kalazus commented on code/modules/mob/living/silicon/robot/robot_modules.dm
> +	if(B?.charges < 10)
Батона уже нету, лучше просто выпилить код его зарядки

2022-07-18 11:29 UTC, Chip11-n commented on code/game/objects/effects/spiders.dm
> +	forceMove(entry_vent?.loc)
Сейчас вроде должно его вытаскивать из трубы

2022-07-18 11:29 UTC, Chip11-n commented on code/game/gamemodes/modes_gameplays/abduction/machinery/console.dm
> +	if(!issilicon(user) && !IsAbductor(user) && !isAI(user) && !isobserver(user))
Забрал в целом у ИИ и боргов возможность интерактить с консолью абдукторов. Они могли напакостить по идее через всякие бейджики СБ, чего наверное не должно происходить в целом.

2022-07-18 11:40 UTC, Mercurialaste commented on code/game/gamemodes/modes_gameplays/abduction/machinery/console.dm
> +	if(!issilicon(user) && !IsAbductor(user) && !isAI(user) && !isobserver(user))
> Забрал в целом у ИИ и боргов возможность интерактить с консолью абдукторов. Они могли напакостить по идее через всякие бейджики СБ, чего не должно происходить в целом по логике вещей.

Не могли, нужно чтобы борг был рядом, иначе у него не получится взаимодействовать с чем-либо через камеры. Мб там могло быть исключение, но на сколько я помню, максимум что можно использовать на любом расстоянии — кнопки аля тех, что закрывают бластдуры.

_(Как пример, попробуй повзаимодействовать с шлюзами через камеры и консоли.)_

Самому даже интересно стало, учитывая что однозначного ответа я дать сейчас не могу.

2022-07-29 16:09 UTC, volas commented on code/game/gamemodes/modes_gameplays/abduction/machinery/console.dm
> +	if(!IsAbductor(user) && !isobserver(user))
Указанный рантайм проблема метода ``IsAbductor``, который должен работать не зависимо от того, что ему передали.

Вообще почему у нас есть нормальный
```
#define isabductor(A) (istype(A, /mob/living/carbon/human/abductor))
```
и этот странный прок ``IsAbductor``.

Есть ли смысл проверять расу у абдуктора? Это у нас дефайн не правильный, или прок?

Стоит оставить дефайн, поправить его по необходимости, и убрать метод консолей в пользу дефайна.

2022-07-29 16:12 UTC, volas commented on code/game/objects/effects/spiders.dm
>  	entry_vent = null
Должно быть две отдельные ветки if/else, или return в первом случае. А то ты то его в турф телепортируешь, то опять пытаешься телепортировать в entry_vent.loc при несуществующем entry_vent - будет опять рантайм

2022-07-29 16:17 UTC, volas requested changes
два небольших комментария выше, почти хорошо

2022-07-30 14:51 UTC, Chip11-n commented on code/game/gamemodes/modes_gameplays/abduction/machinery/console.dm
> +	if(!IsAbductor(user) && !isobserver(user))
ПР конечно слегка раздуется, но я удалил все эти ненужные проверки на расу в пользу дефайна.

2022-07-30 16:02 UTC, volas commented on code/game/gamemodes/modes_gameplays/abduction/machinery/console.dm
> +	if(!IsAbductor(user) && !isobserver(user))
Норм :+1:

2022-07-30 16:02 UTC, volas approved these changes

2022-07-30 20:54 UTC, LudwigVonChesterfield commented
>  кого есть holy_role, но нет религии

почему может быть холи роул но не быть религии...

2022-08-06 18:58 UTC, merged