Чипы для изменения умений
TauCetiStation/TauCetiClassic pull request #9656
Opened 2022-07-17 13:51 UTC by Dushess0

## Описание изменений
# Добавляет чипы что могут изменять умения. 
![image](https://user-images.githubusercontent.com/44201461/179397711-14cbfb0a-3d1b-4fd2-a958-016ca3d6ef72.png)

Работают с помощью имплантов.
Чип вставляется  в консоль, после в консоли настраивается какие навыки выдать человеку что лежит на столе, после чего он вкалывается человеку. 

https://user-images.githubusercontent.com/44201461/179401333-08b4e454-7af2-478d-aadb-dfcf983a98eb.mp4

- Сейчас получить новые никак нельзя, их ограниченое количество на станции.
- Когда человек чипируется то есть шанс 50% шанс что накинется 50 урона мозгу и 10% шанс получить 75 урона мозгу и 50 токсинов. 
- По умолчанию имплантировать можно людей, таяр и унатхов. Для других расс нужны другие катриджи. 
- Нельзя имплантировать людей с лояльностью или защитой разума. Если в человеке есть такой имплант то консоль не даст вставить имплант. Если же майндшилд вставить в уже чипированого умением человека то  имплант скилла сгорит. Это сделал что бы капитаны и СБ не имплантировались максимальными умениями.
- Если попасть под сильное ЭМИ то есть шанс что имплант расплавится.
- Если вынять из человека имплант хирургической операцией то имплант расплавится.

![image](https://user-images.githubusercontent.com/44201461/179396743-3b14d12c-78b0-4abb-b750-4e178e096e04.png)

## Виды чипов
![image](https://user-images.githubusercontent.com/44201461/179397745-0cf328b7-cca5-4016-b902-1c037d827bf1.png)

- ![image](https://user-images.githubusercontent.com/44201461/179397831-1ec9b8c6-1236-4f9f-af5c-dfbfe49a5c5f.png) Зеленый USP - 5:  5 очков, может применятся к к людям, унатхам и таярам. 3 штуки в кабинете ГП

- ![image](https://user-images.githubusercontent.com/44201461/179397828-6d1f4576-2567-4713-81af-a762152b6290.png) Синий USP - 7 : такой же как и зеленый но 7 очков. Две шутки в кабинете ГП
- ![image](https://user-images.githubusercontent.com/44201461/179397825-57b5c2be-2c4e-4b07-bd4e-3e8419efc299.png) Красный USP - 10: лежит один у капитана на столе
- ![image](https://user-images.githubusercontent.com/44201461/179397821-c9306112-9bde-4e68-a876-57cd1497dd90.png) Фиолетовый USP - 15. Не используется, возможно добавлю на дереликт какой-то или как рецепт в РнД или заказ в карго. В зависимости от того нужно ли будет.
- ![image](https://user-images.githubusercontent.com/44201461/179397815-c59bb10c-8e52-49b2-84be-c3bcd10e6bbe.png) Голубой CSP - 15: Может использоватся только к СПУ. Лежит один у ГП

## Изменения карты
Доступ в эту комнату имеют все главы и все главы имеют доступ к тому шкафчику с картриджами. В кабинете для измененния умений находится:

<details>
  <summary>Бумажка с инструкцией</summary>
![image](https://user-images.githubusercontent.com/44201461/179396919-2acc1fe9-ecc1-4992-a4d7-1fc5b16d5a5c.png)
</details>

Консоль
![image](https://user-images.githubusercontent.com/44201461/179396929-37099046-3760-4d7e-820e-b1fb64b9e9c5.png)

Стол на котором должен лежать пациент
![image](https://user-images.githubusercontent.com/44201461/179396949-d09ee775-8bb9-4e86-9685-02e4a0b24671.png)

Шкаф с картриджами
![image](https://user-images.githubusercontent.com/44201461/179397087-98bb510e-d9e9-49a5-9e33-296c8512ae12.png)

Перенес серверную в комнату киборгов

![image](https://user-images.githubusercontent.com/44201461/179396960-b62e26bb-0d93-4dd3-83f7-d3e7a175a447.png)

Капитану в его каюту добавил 1 красный картридж и инструкцию.

![image](https://user-images.githubusercontent.com/44201461/179396967-f3b45b88-9b2d-4950-a3c9-84e46bbd5a50.png)

## Скриншоты и видео
Так выглядит консоль:

## Почему и что этот ПР улучшит
Изменение професии у ГП теперь будет лучше работать.
## Авторство
Dushess
## Чеинжлог
:cl: Dushess
 - rscadd: Добавляет импланты что улучшают умения.

2022-07-17 13:51 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2022-07-17 13:57 UTC, Mercurialaste commented
> Бумажка с инструкцией
> ![image](https://user-images.githubusercontent.com/44201461/179396919-2acc1fe9-ecc1-4992-a4d7-1fc5b16d5a5c.png)

Картинка сломалась? 

> Так выглядит консоль:

А здесь?

2022-07-17 14:05 UTC, KIBORG04 commented on tgui/packages/tgui/interfaces/SkillsConsole.js
> +          <Box>
ааааа почему там нету отступа и две секции слились аа ааа.

(мб заменить бокс на стак?)

![image](https://user-images.githubusercontent.com/26389417/179402020-8705a071-6e68-463b-9f39-b8321852df17.png)

2022-07-17 14:37 UTC, TauKitty commented
Этот запрос на извлечение был упомянут в **Tau Ceti Station Forum**. Там могут быть соответствующие подробности:

https://forum.taucetistation.org/t/skilly-na-tau-opyat-teper-s-itogovym-golosovaniem-ssylka-v-pervom-poste/31475/945

2022-07-17 14:50 UTC, Dushess0 commented on tgui/packages/tgui/interfaces/SkillsConsole.js
> +          <Box>
добавил отступ 
![image](https://user-images.githubusercontent.com/44201461/179403898-18770ca9-68ee-4482-8abe-46c91300a6f0.png)

2022-07-17 16:07 UTC, Dushess0 commented on tgui/packages/tgui/interfaces/SkillsConsole.js
> +          <Box>
![image](https://user-images.githubusercontent.com/44201461/179410621-bb19c5f2-db63-4bbd-ae4f-973cc84970b8.png)

2022-07-17 16:13 UTC, ViDLiathan commented
Почему бумажка на англицком, когда вы занимаетесь локализацией станции?

2022-07-17 21:06 UTC, Dushess0 commented
> Почему бумажка на англицком, когда вы занимаетесь локализацией станции?

Я лично не занимаюсь локализацией билда. Да и ведь у нас все интерфейсы и куча бумажек на английском

2022-07-17 21:10 UTC, KIBORG04 commented on code/modules/paperwork/paper.dm
> +	<li>Place patient on CMF manipulation table</li>
Так как на инглише прочтет 1 чел из 100

2022-07-17 22:11 UTC, Zmey25 commented
Та пощади, киборгам в той комнате и так не пройти, а теперь там еще этот сервер и непонятный блекбокс

2022-07-17 22:15 UTC, Mercurialaste commented
> Та пощади, киборгам в той комнате и так не пройти, а теперь там еще этот сервер и непонятный блекбокс

Хз, я уже предлагал перенести сервера пда и консольку к телекомам на пример. 
Видимо, не вариант.

2022-07-18 00:36 UTC, kiVts commented
вот теперь можно за скилы всеми руками за

2022-07-18 15:15 UTC, Sakuya-Izayoi commented on code/game/objects/items/weapons/implants/mindshield.dm
> +			S.meltdown()
на 90-й строке то же самое, возможно стоит вынести в отдельный прок?

2022-07-18 15:15 UTC, Sakuya-Izayoi commented on code/modules/skills/skill_changer/cartridges.dm
> +	points = 15
странный нейминг. назвал бы с цифрами. а то еще помнить какой цвет сколько поинтов дает.

2022-07-18 15:15 UTC, Sakuya-Izayoi commented on code/modules/skills/skill_changer/cartridges.dm
> +	meltdown()
возможно порядок вызова должен быть другой?
meltdown обрабатывает конкретный случай когда возникает неполадка с имплантом и вызывает removed, который в общем вырубает действие импланта снимая скиллбафф.

2022-07-18 15:15 UTC, Sakuya-Izayoi commented on code/modules/skills/skill_changer/cartridges.dm
> +	if(H.ismindprotect())
забавно что при разном порядке вкалывания имплантов будет разный эффект. если сначала майндшилд, потом скилл -- 125 брейндемеджа, если сначала скилл, потом майндпротект, то 100.

2022-07-18 15:15 UTC, Sakuya-Izayoi commented on code/modules/skills/skill_changer/cartridges.dm
> +	return 1
```suggestion
	return TRUE
```

2022-07-18 15:15 UTC, Sakuya-Izayoi commented on code/modules/skills/skill_changer/skills_console.dm
> +			if(compatible && !same_user && !H.ismindprotect())
а тут вообще чек на майндшилды. типа, чисто механически уколоться скилл имплантом имея майндшилд нельзя, но при этом соответствующий чек в механе скилл импланта есть. зачем?

2022-07-18 16:40 UTC, Dushess0 commented on code/modules/surgery/implant.dm
> +						skill_impant.removed()
я так и задумывал что если из тебя его удаляют то тебе накидывает брейдамаг

2022-07-18 16:43 UTC, Dushess0 commented on code/modules/skills/skill_changer/cartridges.dm
> +	meltdown()
removed используется только в одном месте это когда из тебя его хирургическим путем вынули. Я бы оставил как есть, то есть meltdown это то, что наступает всегда, когда имплант удаляют, или с помощью ЭМИ или с помощью другого импланта.

2022-07-18 18:15 UTC, Sakuya-Izayoi commented
я посмотрел видео и только щас понял что картриджи вставляются в комп а не в стол... почему?

2022-07-18 18:16 UTC, Sakuya-Izayoi commented on code/modules/skills/skill_changer/cartridges.dm
> +	points = 15
да

2022-07-18 18:21 UTC, Dushess0 commented
> я посмотрел видео и только щас понял что картриджи вставляются в комп а не в стол... почему?

Можно и в стол, но в комп как то более логично.

2022-07-18 18:55 UTC, Dushess0 commented on code/modules/skills/skill_changer/cartridges.dm
> +	points = 15
переназвал их всех на
```
/obj/item/weapon/skill_cartridge/usp5
	name = "USP-5 cartridge"
	icon_state = "green"
	points = 5

/obj/item/weapon/skill_cartridge/usp7
	name = "USP-7 cartridge"
	icon_state = "blue"
	points = 7

/obj/item/weapon/skill_cartridge/usp10
	name = "USP-10 cartridge"
	icon_state = "red"
	points = 10

/obj/item/weapon/skill_cartridge/usp15
	name = "USP-15 cartridge"
	item_state = "card-id"
	icon_state = "purple"
	points = 15

/obj/item/weapon/skill_cartridge/csp15
	name = "CSP-15 cartridge"
	desc = "Used together with the CMF apparatus to rapidly alter skills. Specifically, this one can be used with the IPC."
	icon_state = "ipc"
	points = 15
	compatible_species= list(IPC)
```

2022-07-18 18:59 UTC, Dushess0 commented on code/modules/skills/skill_changer/cartridges.dm
> +	if(H.ismindprotect())
Вколоть чип в человека что под защитой разума не выйдет физически. Там кнопка будет серая и в самом `tgui_act `идет проверка на `if(can_inject(usr))`  так что такой ситуации вообще не должно возникнуть, но мало ли может ещё какие то способы имплантирования есть или будут где это не учтено.

2022-07-18 20:32 UTC, Dushess0 commented on code/modules/skills/skill_changer/skills_console.dm
> +			if(compatible && !same_user && !H.ismindprotect())
На случай если я не учел каких-то моментов. Пусть лучше будет такая защита, что бы не возникли абузы неожиданные

2022-07-19 15:00 UTC, Ro2tCrab commented
Если IQ клоуна не будет равен "-1" на GUI, то можно смело закрывать

2022-07-19 21:29 UTC, Sakuya-Izayoi commented
> > > > я посмотрел видео и только щас понял что картриджи вставляются в комп а не в стол... почему?
> > > 
> > > 
> > > Можно и в стол сделать, но в комп как то более логично.
> > 
> > 
> > ну вкалывает же стол а не комп. комп к тому же может быть за н тайлов от стола. что за блюспейс магия.
> 
> Связанно с моментами вроде:
> 
> * Энергию потребляет консоль, а не стол
> * Вообще все манипуляции с картриджем в коде делает консоль, не хочется добавлять кучу проверок на то есть ли подключенный стол при этих манипуляциях.
> * Для игрока логичнее впихнуть картридж в консоль, а не в стол, потому что у нас уже есть довольно много консолей с таким механом, а что бы вставить что-то в стол это очень в новинку будет.
> * Моменты вроде - разобрать стол вовремя операции.

Я не хочу чтобы это выглядело так будто я тираню или что-то такое, но тебе не кажется что это просто отмазки? Типа, ну, как некоторые могли бы подумать "работает и ладно". Но на самом деле не ладно, это же банальная логика. Ты вставляешь имплант в стол, а стол имплантирует, правильно? С чего бы он должен вставлятся в компьютер, если имплантирует стол? В принципе можем обратиться к другому мейнтейнеру для решения этого спорного вопроса, но моя позиция такова, что это просто очень ленивая имплементация и данная фича заслуживает большего.

2022-07-23 12:34 UTC, Dushess0 commented
Изменил что теперь имплант надо вставить в стол а не в консоль

2022-07-23 12:54 UTC, Dushess0 commented
Добавил возможность распечатать платы в рнд
![image](https://user-images.githubusercontent.com/44201461/180605795-ba0bc88b-e018-47c4-aca5-c98f77ec6dd5.png)

![image](https://user-images.githubusercontent.com/44201461/180605788-ad3af7c0-cde9-4aa8-ab0f-5e76d24e539e.png)

2022-07-23 14:30 UTC, Sakuya-Izayoi approved these changes

2022-07-24 17:48 UTC, Shootnik01 commented
Сделать бы шансам на урон мозгу и токсины зависимыми от навыка хирургии и электроники..

2022-07-25 01:06 UTC, Sakuya-Izayoi requested changes
когда кладешь чела на стол, из стола выпадает картридж

![image](https://user-images.githubusercontent.com/30875884/180674517-20c6faac-005d-4a83-98d6-4d3f17cd8246.png)

![image](https://user-images.githubusercontent.com/30875884/180674674-5099aacd-20fd-43b7-afe0-eed2e4222a50.png)

не хватает паддингов, и я бы сделал фиксированного размера блоки.

2022-07-25 16:37 UTC, Dushess0 commented
пофиксил момент с пациентом и картриджем.
Так же сделал постоянного размера секции
![image](https://user-images.githubusercontent.com/44201461/180829413-60cf2b1b-9100-4bf9-9cbe-035ce8c3be53.png)
![image](https://user-images.githubusercontent.com/44201461/180829428-b25b439c-fca2-441d-b635-13e9c54ac88e.png)
![image](https://user-images.githubusercontent.com/44201461/180829469-b2b491c4-c792-4f4f-bd1c-3b443e7b75e7.png)
![image](https://user-images.githubusercontent.com/44201461/180829501-30cba51e-2001-45a7-b9e9-d4f6b1d28d9c.png)

2022-07-25 18:12 UTC, Sakuya-Izayoi approved these changes

2022-07-27 21:09 UTC, simb11 commented
Чипы не работают, после втыкания чипа наносится урон, но навыки не изменяются.

2022-07-27 21:20 UTC, Sakuya-Izayoi commented on code/modules/skills/skill_changer/skills_scanner.dm
> +	cartridge = null
```suggestion
	QDEL_NULL(cartridge)
```

что-то я поспешил с аппрувом, my bad

2022-07-29 09:17 UTC, Dushess0 commented
> Чипы не работают, после втыкания чипа наносится урон, но навыки не изменяются.

игроку и не будут видны изменения в его скилл меню. Попробуй вколоть себе навык инженерии и разобрать стенку или стол.

2022-07-29 10:53 UTC, Shootnik01 commented
> > Чипы не работают, после втыкания чипа наносится урон, но навыки не изменяются.
> 
> игроку и не будут видны изменения в его скилл меню. Попробуй вколоть себе навык инженерии и разобрать стенку или стол.

А почему так? Это очень неудобно. Сделай плиз видимыми изменения, чтобы их можно было также скрывать, притворяясь тупым, или просто знать свой уровень, когда тебе не сказали, что тебе качают

2022-08-04 17:00 UTC, Akellazp commented
забыл камеру в комнату пихнуть а еще консоль сообщений пда отвязана от серверов

2022-08-06 09:25 UTC, Dominig12 commented
Не слишком ли много базового IQ, у нас что, получается люди на станции в среднем имеют минимум 100 IQ?)

2022-08-07 16:38 UTC, Dominig12 commented
@Dushess0 правильно понимаю что возможности создавать такие чипы не будет? Например из членов экипажа или с помощью ИИ, которые могут условно "генерить" навыки из своих вычислительных мощностей

Если не будет, то стоит распихать побольше чипов по делериктам (+ про СПУ не забыть) или дать возможность печатать на СПУ такие штуки, так как этим ребятам как по мне проще подобным заниматься чем людям

2022-08-10 08:37 UTC, Dushess0 commented
Поправил консоль сообщений ПДА и исправил то, что все главы могли войти к ГП через эту дверь. Камеру не добавил в эту комнату что бы ГП через ИИ сам себя не имплантировал

2022-08-12 03:04 UTC, volas approved these changes
По коду вроде ок, в остальное не вникал. Как решишь. что можно мержить - слапни

2022-08-14 12:09 UTC, Dushess0 commented on code/modules/paperwork/paper.dm
> +	name = "CMF manipulation manual"
поправил на русский

2022-08-14 12:09 UTC, Dushess0 commented
@volas, можно мержить. Перевел бумажку и поправил VARSET_IN

2022-08-15 03:45 UTC, merged