Фикс ТЭГов
TauCetiStation/TauCetiClassic pull request #9673
Opened 2022-07-18 13:49 UTC by IlinMihail

## Описание изменений
ТЭГи снова в билде, можно их создать через РнД, разобрать и т.д. Убран мусор из кода рециркуляторов.
## Почему и что этот ПР улучшит
+способ генерации энергии
## Авторство

## Чеинжлог
:cl: M104
- fix: ТЭГи возвращены в билд

2022-07-18 13:49 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2022-07-18 14:52 UTC, KIBORG04 commented
Напиши в чем заключается фикс и что было поломано

2022-07-18 14:56 UTC, Sakuya-Izayoi commented
это сравнительно новая фича, потому что тэги никто не помнит.

2022-07-18 15:01 UTC, IlinMihail commented
> Напиши в чем заключается фикс и что было поломано

не знаю кому это нужно, но написал

2022-07-18 15:21 UTC, Sakuya-Izayoi commented on code/modules/research/research.dm
> +	unlocks_designs = list("mrspacman, circ, teg")
```suggestion
	unlocks_designs = list("mrspacman", "circ", "teg")
```

2022-07-18 18:09 UTC, Refug1 commented
Лучше убрать в карго, дабы заказывать вместе с СМ. Создание через РнД убивает любой источник энергии

2022-07-18 19:08 UTC, IlinMihail commented
ну и кроме того, инженеры врядли его часто делать будут, как и токамак/материю

2022-07-18 19:50 UTC, IlinMihail commented
ладно, будет в атмосе

2022-07-18 21:44 UTC, IlinMihail commented
ну всё вроде

2022-07-19 08:22 UTC, UDaV73rus commented
Возьми прекрасные спрайты отсюда
https://github.com/yogstation13/Yogstation/pull/9195

2022-07-29 16:20 UTC, volas commented
> wip, надо спрайты пофиксить

Актуально?

И я бы еще поискал коммит/пр, по какой причине их вообще отключили и убрали в ящик. Может там еще были какие-то проблемы.

2022-07-29 16:22 UTC, IlinMihail commented
актуально. когда нибудь закончу

2022-08-12 20:41 UTC, IlinMihail commented
пшёл вон бот

2022-08-15 20:50 UTC, IlinMihail commented
вроде всё норм, можно ревью

2022-08-19 05:05 UTC, volas requested changes
в чеинжлоге еще стоит подробнее расписать, в каком именно виде они вернулись (рнд и вот это всё)

2022-08-19 05:05 UTC, volas commented on code/modules/atmospheric/machinery/components/binary_devices/circulator.dm
> +		add_overlay(image("icons/obj/machines/power/thermoelectric.dmi", "circ-panel", dir = fd))
Сначала хотел написать про get_inverse_direction, но вообще можно просто использовать turn

2022-08-19 05:07 UTC, volas commented on code/modules/research/designs.dm
> +/datum/design/smes
еще может дизайны стоит по другому именовать, что бы не было путанницы с обычными SMES-ами

2022-08-19 05:32 UTC, kalazus commented on code/modules/atmospheric/machinery/components/binary_devices/circulator.dm
> +		add_overlay(image("icons/obj/machines/power/thermoelectric.dmi", "circ-panel", dir = fd))
Разве у нас не reverse_dir[dir] для используется для обратных?

2022-08-19 05:37 UTC, volas commented on code/modules/atmospheric/machinery/components/binary_devices/circulator.dm
> +		add_overlay(image("icons/obj/machines/power/thermoelectric.dmi", "circ-panel", dir = fd))
или его, я долго не мог вспомнить название

2022-08-19 10:17 UTC, IlinMihail commented on code/modules/atmospheric/machinery/components/binary_devices/circulator.dm
> +	if(heat < per_kelvin * 173) //-100C
так ведь это просто температура в кельвинах, всё в дефайны чтоль запихнуть?

2022-08-27 06:39 UTC, volas commented on code/modules/power/generator.dm
> +	anchored ? connect_to_network() : disconnect_from_network()
с if эта конструкция будет более читаемой, не критично

2022-08-27 06:39 UTC, volas commented on code/modules/power/generator.dm
> +//note that the circulator"s outlet dir is it"s always facing dir, and it"s inlet is always the reverse
?

2022-08-27 06:39 UTC, volas commented on code/modules/atmospheric/machinery/components/binary_devices/circulator.dm
> +	if(heat > per_kelvin * 4773) //4500C
else-if может? если условия взаимно исключающие

2022-08-27 14:28 UTC, volas commented on code/modules/atmospheric/machinery/components/binary_devices/circulator.dm
> +		if(heat >= per_kelvin * 4773) //4500C
стоило просто сделать
```
If ...
else if ...
else if ...
else if ...
```
на одном уровне, теперь я не понимаю что происходит. В одном месте проверяешь меньше, в другом больше, в каких-то ветках ставишь дважды оверлеи и дважды set_light

2022-08-27 14:53 UTC, IlinMihail commented on code/modules/atmospheric/machinery/components/binary_devices/circulator.dm
> +		if(heat >= per_kelvin * 4773) //4500C
елз иф не подходит, в первом варианте иф-ы специально были друг на друге, так как есть по 2 оверлея как для горячего, так и для холодного газа. в данном случае "если газ холоднее 30 градусов -> (1 холодный оверлей -> если газ холоднее 100 градусов -> второй холодный оверлей и свет ярче) иначе -> проверяем насколько газ горяч

2022-08-27 15:04 UTC, volas commented on code/modules/atmospheric/machinery/components/binary_devices/circulator.dm
> +		if(heat >= per_kelvin * 4773) //4500C
Но set_light то зачем дважды дергать... сходу выглядит как ошибка.

2022-08-27 15:05 UTC, IlinMihail commented on code/modules/atmospheric/machinery/components/binary_devices/circulator.dm
> +		if(heat >= per_kelvin * 4773) //4500C
ну можно поставить промежуточную переменную и после проверок всё задавать, но сет-лайт вроде не тяжёлый метод и нормально работает если его дважды вызвать

2022-08-29 17:22 UTC, IlinMihail commented
смысла держать в ТМ-е не вижу, вроде всё всем нравится, работает как надо, эффективность подправил дабы не было так имбово

2022-08-29 17:30 UTC, kalazus commented
А тэги за время теста вообще использовали?

2022-08-29 17:45 UTC, Chip11-n commented
Дедава в прошлом раунде использовал, но там было всего десяточка на выходе с его билдом

2022-08-29 17:50 UTC, IlinMihail commented
> всего десяточка на выходе

он говорил что 10 мегаватт а не ватт, в сравнении с сингой - дохера. эффективность теперь в два раза меньше по дефолту, должно быть норм

2022-09-03 10:31 UTC, volas requested changes

2022-09-03 10:31 UTC, volas commented on code/modules/atmospheric/machinery/components/binary_devices/circulator.dm
> +			set_light(3, 5, "#ff0000")
```suggestion
	if(heat <= per_kelvin * 243) //-30C
		add_overlay(image("icons/obj/machines/power/thermoelectric.dmi", "circ-cold", dir = fd))

		if(heat <= per_kelvin * 173) //-100C
			add_overlay(image("icons/obj/machines/power/thermoelectric.dmi", "circ-excold", dir = fd))
			set_light(3, 5, "#0044ff")
		else
			set_light(1, 3, "#0044ff")

	else if(heat >= per_kelvin * 1773) //1500C
		add_overlay(image("icons/obj/machines/power/thermoelectric.dmi", "circ-hot", dir = fd))

		if(heat >= per_kelvin * 4773) //4500C
			add_overlay(image("icons/obj/machines/power/thermoelectric.dmi", "circ-exhot", dir = fd))
			set_light(3, 5, "#ff0000")
		else
			set_light(1, 3, "#ff0000")
```

2022-09-03 10:31 UTC, volas commented on code/modules/cargo/packs.dm
> +/datum/supply_pack/teg // teg currently were broken for a long time ago, so no point to have it in-game until fixed.
```suggestion
/datum/supply_pack/teg
```

2022-09-03 10:31 UTC, volas commented on code/modules/atmospheric/machinery/components/binary_devices/circulator.dm
>  /obj/machinery/atmospherics/components/binary/circulator/update_icon()
Мне еще не нравится, что это прок, который каждый раз дергает кучу оверлеев и свет, но при этом безусловно вызывается из нескольких процессингов:

1. ``process_atmos()``, т.е. из контроллера атмоса
2. ``return_transfer_air()`` через ``process()`` генератора, т.е. из контроллера машинерии

Плохо, что оно будет постоянно дергаться отовсюду, и в теории даже возможны гонки, когда будет вызвано несколько апдейтов в один момент и будут конфликтующие оверлеи.

Я бы предложил добавить таймер-кулдаун с последнего обновления, может секунд на 5, и использовать для вызовов из процессинга. Для вызовов конструкта/деконструкта и подобного использовать флаг, который бы игнорировал кулдаун. Так мы решим сразу вопрос и веса прока, и возможные проблемы из-за гонок.

2022-09-03 10:52 UTC, IlinMihail commented on code/modules/atmospheric/machinery/components/binary_devices/circulator.dm
>  /obj/machinery/atmospherics/components/binary/circulator/update_icon()
легче его банально убрать из get_transfer_air, он там не особо то и нужен

2022-09-04 11:33 UTC, volas commented on code/modules/atmospheric/machinery/components/binary_devices/circulator.dm
> +			set_light(3, 5, "#ff0000")
```suggestion
	if(air.temperature <= 243) //-30C
		add_overlay(image("icons/obj/machines/power/thermoelectric.dmi", "circ-cold", dir = fd))

		if(air.temperature <= 173) //-100C
			add_overlay(image("icons/obj/machines/power/thermoelectric.dmi", "circ-excold", dir = fd))
			set_light(3, 5, "#0044ff")
		else
			set_light(1, 3, "#0044ff")			


	else if(air.temperature >= 1773) //1500C
		add_overlay(image("icons/obj/machines/power/thermoelectric.dmi", "circ-hot", dir = fd))

		if(air.temperature >= 4773) //4500C
			add_overlay(image("icons/obj/machines/power/thermoelectric.dmi", "circ-exhot", dir = fd))
			set_light(3, 5, "#ff0000")
		else
			set_light(1, 3, "#ff0000")
```

2022-09-05 19:29 UTC, merged

2022-09-12 02:31 UTC, volas commented
@IlinMihail можешь глянуть #10048?

2022-09-13 01:30 UTC, TauKitty commented
Этот запрос на слияние был упомянут в **Tau Ceti Station Forum**. Там могут быть соответствующие подробности:

https://forum.taucetistation.org/t/guide-teg-put-k-hellburn/35528/2