добавляет маску гая фокса во взломанный автомат с одеждой
TauCetiStation/TauCetiClassic pull request #9681
Opened 2022-07-19 13:47 UTC by AndroBetel

## Описание изменений
нашел какую-то маску в коде прикольную решил добавить в автомат в котором есть очки из гуренн лаганна и прочие прикольные отсылочки
## Почему и что этот ПР улучшит
больше одежды игрокам
## Авторство

## Чеинжлог
:cl:
- rscadd: В автомат с одеждой добавлена маска Гая Фокса

2022-07-19 13:47 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2022-07-19 13:49 UTC, Sakuya-Izayoi commented
очки из гуррен лаганна это отсылка на аниме которое старше 90% аудитории сервера и вполне себе культурная приличная отсылка, в нашем обществе маска гая фокса это в первую очередь отсылка на унылый раковый форс из вконтакта для детей младше 16-и лет. если и добавлять эту маску еще куда-то, то только так, чтобы это был конкретный референс на что-то кроме вышеописанного.

2022-07-19 13:50 UTC, AndroBetel commented
чзх гетап в 2016 году предсказал мем на снюсоеда

2022-07-19 13:51 UTC, KIBORG04 requested changes
Причем мержить это я не вижу

2022-07-19 14:23 UTC, volas commented
лучшеб консоли аплоада пофиксил

2022-07-19 18:42 UTC, Pivo24 commented
лучшеб вирусологию пофиксил

2022-07-19 18:43 UTC, Mercurialaste commented
лучшеб абдукторов пофиксил

2022-07-19 20:01 UTC, Vysserath1 commented
V значит вендетта прекрасный фильм про революцию, а его символ превратили в интернет высер про пряники, ужас

2022-07-21 02:10 UTC, volas commented on code/game/machinery/vending/clothing.dm
> +		/obj/item/clothing/mask/gas/fawkes = 6,
```suggestion
		/obj/item/clothing/mask/gas/fawkes = 1,
```

так будет мой апрув. Маски, тем более газовые, слабо вписываются в контекст ClothesMate. Но контрабанду можно и оставить.

2022-07-31 00:40 UTC, AndroBetel commented
все смержьте уже мне надо позакрывать пры

2022-07-31 14:43 UTC, volas approved these changes

2022-07-31 14:44 UTC, volas commented
Теперь нужен третий мейнтейнер для вынесения финального вердикта

2022-08-11 15:15 UTC, AndroBetel commented
мерж

2022-08-12 03:05 UTC, volas commented
![Снимок экрана от 2022-08-12 06-05-16](https://user-images.githubusercontent.com/4064061/184277446-cc5646f8-6977-46cf-8c97-aa5cfd5d9662.png)
Найди третьего мейнтейнера, который согласится посмотреть

2022-08-14 02:35 UTC, AndroBetel commented
пофиг

2022-08-14 02:35 UTC, closed without merging