Делает бриг более защищённым от космических налётов
TauCetiStation/TauCetiClassic pull request #9687
Opened 2022-07-20 11:24 UTC by simb11

## Описание изменений
Вокруг брига расставлены обычные и шоковые мины.
Обычные стены у недоделанного шаттла и душевой брига заменены на укреплённые.
## Почему и что этот ПР улучшит
Нюкеры будут не так часто нападать на бриг.
Человекам без нормальных умений придётся потратить больше времени на штурм брига со стороны космоса.
## Авторство

## Чеинжлог
пусть это будет сюрпризом для игроков

2022-07-20 11:24 UTC, TauKitty commented
###### Changelog status: :radio_button: No changelog

2022-07-20 11:49 UTC, simb11 commented
![image](https://user-images.githubusercontent.com/84613249/179974863-a1082d73-5934-4350-a5bd-ae63f5887972.png)

2022-07-20 12:15 UTC, Mercurialaste commented
Для сравнения, та же инженерка, в которой самое слабое место — окна у дронной. 

Все остальное в укреп. стенках.

2022-07-20 12:27 UTC, QWxiZX commented
Едешь такой на инженере чинить обшивку брига после метеоритов.
Встречаешь сюрприз для игроков.

2022-07-20 12:57 UTC, simb11 commented
Добавил табличку с предупреждением.

2022-07-20 14:09 UTC, Sakuya-Izayoi commented
симбака дошел до издевательства над игроками через пулл реквесты...

2022-07-20 14:32 UTC, TheLone1y commented
Обычные мины че-то лишнее уже, да и какой тогда смысл шаттла если он стоит столько же сколько и гейт, но не дает тебе три шага до диска? Обезоружить экипаж? Дак там и через гейт вбежать можно.
Еще вопрос, если антаги просто мультитулом мины снимут и подставят под двери брига то это не нерф, а бафф? Какая-то смешнявка с бесплатной раздачей того, что триторы покупают за 3 телекристалла.

2022-07-20 14:32 UTC, kalazus commented
> Накину сверху. закинь туда ещё 4-6 турелей, с настройкой на проверку доступа, они тогда, как я помню, будут стрелять по нюкерам.

Не будут. Кто-то очень умный решил что карта агента даёт угрозу меньше чем карта капитана. Типо, чтобы она по ним стреляла у них должно быть 2+ пушки в руках/карманах вроде.

2022-07-20 14:36 UTC, simb11 commented
> Обычные мины че-то лишнее уже, да и какой тогда смысл шаттла если он стоит столько же сколько и гейт, но не дает тебе три шага до диска? Обезоружить экипаж? Дак там и через гейт вбежать можно.

Я не хочу полностью убрать возможность рейда брига, я хочу его усложнить и замедлить, с минами у ИИ хотя бы будет время сказать про нюкеров вблизи брига, не зря же там камеры с сенсорами стоят.

2022-07-20 16:23 UTC, Tap0r commented
Солидно
![image](https://user-images.githubusercontent.com/88531962/180033372-285ee483-12b6-49de-bc23-9e49f6f78cba.png)

2022-07-20 16:26 UTC, Mercurialaste commented
Главное чтобы там ничего мимо не пролетало…

2022-07-20 17:19 UTC, simb11 commented
уменьшил количество обычных мин.

2022-07-20 19:16 UTC, Sakuya-Izayoi requested changes
> Нюкеры будут не так часто нападать на бриг.
> Человекам без нормальных умений придётся потратить больше времени на штурм брига со стороны космоса.

Очень глупая попытка решить глупую проблему. Насколько я знаю нынче мета идти через гейт, так что логичнее было бы поставить мины там (это все еще плохо). А почему надо "замедлять" штурм брига для "неопытных" игроков непонятно. Какая-то унылая компенсация скилл ишьюсов шитсеков. Не годится.

Еще были использованы ХЕ мины, типа, их на стейшене нигде нет, на кой черт они там?

Ну и помимо этого, ничто не мешает каким-нибудь инженерам или что еще хуже мусорщикам подойти и скрутить эти мины мультитулом и поставить где-то на стейшене. На кой черт это надо?

2022-07-20 20:19 UTC, simb11 commented
> Насколько я знаю нынче мета идти через гейт,

После возвращения анонса гейт перестал быть метой и всё вернулось на свои места.

> А почему надо "замедлять" штурм брига для "неопытных" игроков непонятно. Какая-то унылая компенсация скилл ишьюсов шитсеков. Не годится.

Тут скорее проблема не в опытности игроков, а в том что нюка с шаттлом примерно всегда штурмует бриг, ибо это самое выгодное место для старта, потому что имеет оружие, которое добывается за 1 клик сваркой, 1 клик ключом и несколько кликов емагом. С добавлением мин и укреп стен у нюки появится хоть какой-то смысл не начинать с брига.

2022-07-20 20:47 UTC, Chip11-n commented
Честно говоря, я бы на месте юнкеров всё также продолжил бы штурмовать бриг, но уже со стороны офиса ХоСа, примерно также выйдет и по времени, а в итоге из офицеров не выживет ещё больше, ибо разгерма бьёт по всём путям отхода

2022-07-21 15:42 UTC, Pivo24 commented
Сидишь офицеришь в офисе брига, сидишь в РИГе такой типо эпичный выживатель космосов но тут прилетает метеор

А ты без магбутов

И ты такой нееееееееееееееееееееееееет и в 1000000000 мин подряд влетаешь

2022-07-21 16:21 UTC, simb11 commented
мины не наносят прям супер огромного урона людям в ригах, максимум кость сломает и оглушит на минуту.

2022-07-21 16:47 UTC, Akellazp commented
тупая хуйня

2022-07-21 18:25 UTC, simb11 commented
да реально хуйня какая-то получилась

2022-07-21 18:25 UTC, closed without merging

2022-07-21 18:45 UTC, BiQndy commented
на первое апреля самый сок