Drugs will make you happier!
TauCetiStation/TauCetiClassic pull request #9694
Opened 2022-07-21 20:46 UTC by simb11

## Описание изменений
Наркотики немного повышают настроение.
## Почему и что этот ПР улучшит
наркоту чаще по вене пускать будут
## Авторство

## Чеинжлог
:cl: Simbaka
- add: Наркотики повышают настроение.

2022-07-21 20:46 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2022-07-21 21:04 UTC, Sakuya-Izayoi requested changes

2022-07-21 21:04 UTC, Sakuya-Izayoi commented on code/modules/mob/mob.dm
> +		SEND_SIGNAL(src, COMSIG_ADD_MOOD_EVENT, "drugged", /datum/mood_event/drugged)
муд евенты не должны отправляться из прока обновления оверлеев.

2022-07-21 21:46 UTC, simb11 commented
переделал

2022-07-22 09:07 UTC, BunkyFly commented
Вот бы ещё самокрутки из дион нимф сделали...

2022-07-22 18:15 UTC, Sakuya-Izayoi commented on code/datums/mood_events/generic_positive_events.dm
> +	description = "<span class='nicegreen'>Oh my god! What a thrill!</span>"
![image](https://user-images.githubusercontent.com/30875884/180499408-ae80ea25-cdc8-4f81-9ebe-1d26d624d8f8.png)

thrill не звучит как что-то положительное и приятное

2022-07-22 18:15 UTC, Sakuya-Izayoi commented on code/datums/mood_events/generic_positive_events.dm
> +	timeout = 1 MINUTES
то есть даже если чел пробудет druggy хотя бы 1 тик, ему даст целую минуту муда? может стоит поменьше сделать таймаут мудивента?

2022-07-22 18:27 UTC, AndroBetel commented on code/datums/mood_events/generic_positive_events.dm
> +	description = "<span class='nicegreen'>Oh my god! What a thrill!</span>"
![image](https://user-images.githubusercontent.com/44546836/180501236-8874ae7a-80b8-4043-a8aa-9cced1ff2632.png)
лол

2022-07-22 18:31 UTC, Sakuya-Izayoi commented on code/datums/mood_events/generic_positive_events.dm
> +	description = "<span class='nicegreen'>Oh my god! What a thrill!</span>"
ладно...

2022-07-22 19:58 UTC, simb11 commented on code/datums/mood_events/generic_positive_events.dm
> +	timeout = 1 MINUTES
У нас сейчас такая штука с сигаретами, никто не жалуется и многие считают это фишкой. Минута это не сильно много, я не хочу, чтобы настроение сразу после окончания эффекта снижалось.

2022-07-22 22:53 UTC, LudwigVonChesterfield commented on code/datums/mood_events/generic_positive_events.dm
> +	timeout = 1 MINUTES
а как же отходняк

2022-07-23 01:32 UTC, volas commented on code/datums/mood_events/generic_positive_events.dm
> +	timeout = 1 MINUTES
Нам нужна система последствий, как вариант её можно реализовать через сами же реагенты, как писал в #9573

2022-07-26 17:25 UTC, Sakuya-Izayoi approved these changes

2022-07-29 16:27 UTC, volas requested changes

2022-07-29 16:27 UTC, volas commented on code/modules/mob/mob.dm
> +	MakeHappy()
~~Перед MakeHappy стоит проверять, что у нас вообще druggy стоит.~~ А, оно ниже.

Чуть подумав, мне не нравится вообще странный прок MakeHappy в скоупе моба, можно просто тут сигнал отправлять.

Еще чуть подумав, почему мы вообще это делаем из методов аджуста значения, это должно быть где-то в лайфе или в самих реагентах

2022-07-30 18:46 UTC, simb11 commented on code/modules/mob/mob.dm
> +	MakeHappy()
перенёс в лайф

2022-07-30 20:55 UTC, LudwigVonChesterfield commented on code/modules/mob/mob.dm
> +	MakeHappy()
когда перенос на статус эффекты

2022-07-31 14:39 UTC, volas approved these changes

2022-07-31 14:40 UTC, merged