Swimsuit resprite by WJ
TauCetiStation/TauCetiClassic pull request #9702
Opened 2022-07-24 07:26 UTC by WatlerJe

## Описание изменений
[Респрайт женских купальников.](https://youtu.be/0PpxUAZsJtE)
![image](https://user-images.githubusercontent.com/19796920/180636872-580ddfa9-480b-472d-a810-f93107557885.png)
## Почему и что этот ПР улучшит
В данном ПРе предлагается новое дизайнерское видение женских купальников, благодаря чему они стали более разнообразными и эстетически приятными. Так же были перерисованы спрайты для толстых кукол, добавлен красный купальник для толстых.
## Авторство
Me
## Чеинжлог
🆑 WalterJe
- Респрайт купальников

2022-07-24 07:26 UTC, TauKitty commented
###### Changelog status: :x: Empty changelog (check markdown correctness)

2022-07-24 07:31 UTC, UDaV73rus commented
Не очень себя чувствую на счет пропуска пикселя у груди, потому что женские купальники эммммм.. будут в основном носить мужики. Нужно прост более темным пикселем залить, эффект тот же будет, а у мужиков не будет торчать пиксель

2022-07-24 07:37 UTC, WatlerJe commented
Женские купальники как это не странно предназначены для женщин. Если его будет носить мужчина и он будет смотреться несуразно - так тому и быть.

2022-07-24 07:57 UTC, TungstenOctopus commented
> Не очень себя чувствую на счет пропуска пикселя у груди, потому что женские купальники эммммм.. будут в основном носить мужики. Нужно прост более темным пикселем залить, эффект тот же будет, а у мужиков не будет торчать пиксель

Думаю это ок

![image](https://user-images.githubusercontent.com/6051766/180637873-b00a1889-f5c5-471b-a103-758e52a6894a.png)

2022-07-24 08:25 UTC, Zandwitch23 commented
Ништяк. Самое время для пляжных эпизодов.

2022-07-24 11:21 UTC, volas commented
конфликты... не буду грузить, я потом поправлю сам

2022-07-24 11:29 UTC, UDaV73rus requested changes
Залей пиксели по бокам у фуллбоди костюмов, они не играют такой роли, чтобы трястись за них. Эта фишка с обрезанными боками у женщин только у хуманов

2022-07-24 11:47 UTC, UsadoSmokk commented
За них можно трястись, просто сделайте это кодом, как у фем версии тактикулки

2022-07-29 16:47 UTC, volas commented
> не буду грузить, я потом поправлю сам

Я не могу поправить это автоматически, пр на базе старой ветки и скрипт захлебнулся. Нужно в ручную на новой ветке пересоздать.

2022-07-30 05:27 UTC, closed without merging