Big voice for Harbinger & Shadowling
TauCetiStation/TauCetiClassic pull request #9715
Opened 2022-07-26 13:32 UTC by Chip11-n

## Описание изменений
![image](https://user-images.githubusercontent.com/50750952/181018005-b9793563-8dfd-4c96-a31b-7bc15692bc7c.png)
![image](https://user-images.githubusercontent.com/50750952/181018266-49154a62-a29d-4967-aa3b-10730850b837.png)

## Почему и что этот ПР улучшит
Лидерам командных фракций будет проще координировать действия подопечных. По крайней мере тогда, когда они действительно пытаются это делать
## Авторство

## Чеинжлог
:cl: Chip11-n
- tweak: Голос предвестника культа и шэдоулинга теперь выглядят больше в чате

2022-07-26 13:44 UTC, TungstenOctopus commented
А он не слишком крупный? На скриншоте выглядит так, будто каждое слово будет на отдельной строчке. Может лучше сделать его жирным, поменять оттенок на более заметный и т.д.?

2022-07-26 13:59 UTC, UDaV73rus commented
Это экран у него маленький

2022-07-26 14:57 UTC, Chip11-n commented
У меня экран просто не прямоугольник, а квадрат, потому создаётся такое ощущение. Но могу уменьшить, да

2022-07-26 15:03 UTC, Chip11-n commented
Вот так выглядят шрифты. Можно уменьшить до 3.

На скрине сверху-вниз: 4ка, 3ка, 2ка
![image](https://user-images.githubusercontent.com/50750952/181041440-a3c8d26e-0c98-4f63-87eb-f9c8e743dfbe.png)

2022-07-26 15:05 UTC, Chip11-n commented on code/datums/spells/wizard.dm
> +	if(user.mind.holy_role == CULT_ROLE_MASTER)
Ладно, думал дать ему По крайней мере возможность на чуть больше геймплея.

2022-07-26 15:10 UTC, KIBORG04 commented on code/datums/spells/wizard.dm
> +	if(user.mind.holy_role == CULT_ROLE_MASTER)
Можешь сделать приписку перед "Аколит", думаю этого хватит.

2022-07-26 15:24 UTC, UDaV73rus commented
Размер шрифта лучше тебе самому решать, потому что к большим шрифтам наиболее чувствительны люди с мелким экраном

2022-07-26 15:41 UTC, Chip11-n commented
Даже при большом тексте оно выглядит для меня не слишком огромным. Аналогично с шедоу
![image](https://user-images.githubusercontent.com/50750952/181049940-f9b03919-8ebb-4a4b-9877-fe1ac3fc7d99.png)

2022-07-26 17:16 UTC, Sakuya-Izayoi commented on code/game/gamemodes/modes_gameplays/shadowling/shadowling_abilities.dm
> +			text2speak = "<font size='4'>[text2speak]</font>"
мы больше не юзаем <font>, найди или сделай класс с соотвутсвующим размером.

2022-07-29 16:57 UTC, volas requested changes
Как Гетап выше написал, требуется сделать через span с классом, для универсальности, поддержки, переиспользования в будущем. Ну и font вообще моветон, да. Как и прописывание стилей и свойств инлайн.

2022-07-29 19:56 UTC, Chip11-n commented
![image](https://user-images.githubusercontent.com/50750952/181834075-f21e9202-7e4a-45d9-83b2-2336d70fc88c.png)
Собственно, я победил их. Не без помощи, конечно, но всё же. В ТГУИ пришлось подправить нерабочую троечку на large. Этот класс ранее не использовался, потому было незаметно.

2022-07-29 19:58 UTC, KIBORG04 commented on code/game/gamemodes/modes_gameplays/shadowling/shadowling_abilities.dm
> +			text2speak = "<font size='large'>[text2speak]</font>"
```suggestion
			text2speak = "<span class='large'>[text2speak]</font>"
```

эммммм

2022-07-29 19:58 UTC, KIBORG04 commented on code/game/gamemodes/modes_gameplays/shadowling/shadowling_abilities.dm
> +			text2speak = "<font size='large'>[text2speak]</font>"
Как оно работало вообще

2022-07-29 20:00 UTC, KIBORG04 commented on code/game/gamemodes/modes_gameplays/shadowling/shadowling_abilities.dm
> +			text2speak = "<font size='large'>[text2speak]</font>"
Или даже можно сделать так:
```suggestion
		var/text2speak = "<span class='shadowling [isshadowling(usr) ? "large" : ""]'><b>\[Hive Chat\]</b><i> [usr.real_name]</i>: [text]</span>"
```

2022-07-29 20:00 UTC, Chip11-n commented on code/game/gamemodes/modes_gameplays/shadowling/shadowling_abilities.dm
> +			text2speak = "<font size='large'>[text2speak]</font>"
Это я уже ревертал свои изменения. Починю

2022-07-29 20:00 UTC, Chip11-n commented on code/game/gamemodes/modes_gameplays/shadowling/shadowling_abilities.dm
> +			text2speak = "<font size='large'>[text2speak]</font>"
Спасибо

2022-07-29 20:01 UTC, KIBORG04 commented on code/game/gamemodes/modes_gameplays/shadowling/shadowling_abilities.dm
> +			text2speak = "<font size='large'>[text2speak]</font>"
(я если что это не тестил, мб оно даже не скомпилит)

2022-07-30 05:24 UTC, volas commented on tgui/packages/tgui-panel/styles/goon/chat-base.scss
> +  font-size: large;
ключевые слова тоже плохо, это не контролируемый рандом. Лучше

```suggestion
  font-size: 4em;
```
относительно и понятно

2022-07-30 05:29 UTC, volas commented on tgui/packages/tgui-panel/styles/goon/chat-base.scss
> +  font-size: large;
> Этот класс ранее не использовался, потому было незаметно.

нашел 3 упоминания в ``modules/admin/admin.dm``, не страшно

2022-07-30 05:42 UTC, Chip11-n commented on tgui/packages/tgui-panel/styles/goon/chat-base.scss
> +  font-size: large;
Мне другие классы переделать по подобию? Там `x-large`, `xx-large`

2022-07-30 17:50 UTC, volas commented on code/game/gamemodes/modes_gameplays/shadowling/shadowling_abilities.dm
> +				to_chat(M, "<span class='shadowling [isshadowling(usr) ? "large" : ""]'><b>\[Hive Chat\]</b><i> [usr.real_name]</i>: [text]</span>")
предлагаю сделать небольшую оптимизацию, и сообщение компоновать до цикла. Можно обойтись одним вызовом isshadowling(usr), чем вызвать его каждый раз для каждого из мобов в цикле

2022-07-30 17:55 UTC, volas commented on tgui/packages/tgui-panel/styles/goon/chat-base.scss
> +  font-size: large;
em как раз будет скейлится от текущего размера шрифта, а все эти large рандом и у юзера могут оказаться чем угодно.

Их стоит аннигилировать, это какое-то легаси времен бьенд чата. Но нужно скорее всего смотреть и подгонять новые размеры, просто заменив в классе можно что нибудь сломать. Тема отдельного ПР-а в общем

2022-07-30 18:23 UTC, Chip11-n commented on code/game/gamemodes/modes_gameplays/shadowling/shadowling_abilities.dm
> +				to_chat(M, "<span class='shadowling [isshadowling(usr) ? "large" : ""]'><b>\[Hive Chat\]</b><i> [usr.real_name]</i>: [text]</span>")
Ревертнул

2022-07-30 18:39 UTC, volas approved these changes

2022-07-30 18:40 UTC, merged