Позволяет вылазить из слипера одиссея
TauCetiStation/TauCetiClassic pull request #9718
Opened 2022-07-26 15:46 UTC by simb11

## Описание изменений
Убрал стан и паралайзис от слипера, теперь из него можно спокойно вылазить через нажатие резиста
## Почему и что этот ПР улучшит
fixes #7662
## Авторство

## Чеинжлог
:cl: Simbaka
- tweak: При помощи кнопки "resist" можно покинуть слипер, встроенный в мех.

2022-07-26 15:46 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2022-07-27 06:10 UTC, notkripton commented
НАКОНЕЦ-ТО кто-то это сделал

2022-07-29 17:03 UTC, volas requested changes

2022-07-29 17:03 UTC, volas commented on code/game/mecha/equipment/tools/medical_tools.dm
> -	M.Stun(2)
тут что-то странное на самом деле, почему мы выше уменьшаем счетчики и тут же накидываем половину обратно. Я бы поискал в гит блейме, в чем была идея.

А так, не заглядывая, вероятно adjust-ы выше стоит просто тоже убрать.

2022-07-30 05:48 UTC, simb11 commented on code/game/mecha/equipment/tools/medical_tools.dm
> -	M.Stun(2)
Убрал

2022-07-30 17:47 UTC, volas approved these changes

2022-07-30 17:48 UTC, merged