Фиксы синдиборга
TauCetiStation/TauCetiClassic pull request #9734
Opened 2022-07-29 15:09 UTC by NinjaPikachuska

## Описание изменений
ПНВ синдиборга не видел во тьме. Исправлено.
Если борг переключится с дефолтной частоты, то у него пропадет синди канал. Исправлено.
## Почему и что этот ПР улучшит
Синдиборг станет играбельней.
## Авторство

## Чеинжлог

2022-07-29 15:09 UTC, TauKitty commented
###### Changelog status: :radio_button: No changelog

2022-07-29 15:11 UTC, Mercurialaste commented
В синдиборге же установлен ключ шифрования синди. Даже если переключить частоту, через :t все ещё можно будет говорить в синди канал.

2022-07-29 16:11 UTC, kalazus commented
Калибровка каналов занимает время (где-то есть sleep там), а это запрещено в atom_init.

2022-07-31 14:47 UTC, volas requested changes

2022-07-31 14:47 UTC, volas commented on code/modules/mob/living/silicon/robot/syndi/syndiborg.dm
> +		secure_radio_connections[ch_name] = radio_controller.add_object(src, radiochannels[ch_name],  RADIO_CHAT)
Тебе надо было как в радио сделать
```INVOKE_ASYNC(src, .proc/recalculateChannels)```

2022-07-31 15:12 UTC, volas approved these changes

2022-07-31 15:12 UTC, merged