Апдейт движения
TauCetiStation/TauCetiClassic pull request #9753
Opened 2022-08-02 10:14 UTC by notkripton

## Описание изменений

https://youtu.be/J4COVfevAeU

Список изменений:
1. Игрок двигается на тайл с объектом когда токает его.
2. Диагональное передвижение больше не в 2 раза медленнее обычного, а в 1.4 (корень из 2) и будет выглядеть более натурально.
3. Замедление от пулла мобов теперь зависит от состояния моба. Мобы в сознании и с хелп интентом будут пуллиться быстро, в другом интенте медленнее, мертвым или без сознания еще медленнее.
4. Уменьшено замедление от пуллинга обжектов.
5. Замедление от захвата увеличивается с его уровнем и на первом такое же как у пулла.
6. Контрл+клик по объекту который ты уже пуллишь отменит пулл (хоткей по остановке пулла по кнопке никуда не делся).
## Почему и что этот ПР улучшит
QoL. 
## Авторство

## Чеинжлог
:cl:
 - add: Теперь игрок двигается на тайл с объектом когда токает его.
 - add: Замедление от захвата увеличивается с его уровнем и на первом такое же как у пулла.
 - add: Контрл+клик по объекту который ты уже пуллишь отменит пулл.
 - tweak: Замедление от пулла мобов теперь зависит от интента и здоровья моба.
 - tweak: Пуллинг всего стал чуть быстрее.
 - tweak: Диагональное передвижение стало на 30% быстрее.

2022-08-02 10:14 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2022-08-02 10:23 UTC, Tap0r commented
Кажется что как-то уж слишком быстро объекты таскаются.

2022-08-02 10:27 UTC, WatlerJe commented
Дерганое движение это только на видео? В остальном круто, игра станет динамичнее и на рутину будет уходить меньше времени.
Алсо есть предложение портировать фичу с ТГ по переноске людишек на плече с возможностью метнуть их в кого-нибудь. К сожалению в реалиях билда ТК гораздо эффективнее положить раненного в шкаф и так оттащить в мед, чем тащить вторым грабом, а так можно будет доставить персонажа достаточно быстро.

2022-08-02 10:31 UTC, notkripton commented
> Дерганое движение это только на видео

Да, мой комп ведро и не тянет бандикам вместе с локалкой даже в плохом качестве, такие дела)

2022-08-02 12:46 UTC, KIBORG04 commented
> QoL.

Это нихуя не qol

2022-08-02 12:49 UTC, KIBORG04 commented on code/modules/mob/mob_movement.dm
> +			move_delay += add_delay * 0.4 // in general moving diagonally will be 1.4 (sqrt(2)) times slower
Проведи исследования по скорости бега в диагональном коридоре. Первый должен бежать только по диагонали, а без. Если диагональщик выиграет, ты убираешь это.

2022-08-02 13:05 UTC, notkripton commented on code/modules/mob/mob_movement.dm
> +			move_delay += add_delay * 0.4 // in general moving diagonally will be 1.4 (sqrt(2)) times slower
Результат налицо даже без микрозамеров (смотреть длину видео)

<details>
  <summary>Замеры</summary>

https://user-images.githubusercontent.com/75007994/182380961-699d3847-598f-4ac3-888e-e96ac7125b15.mp4

https://user-images.githubusercontent.com/75007994/182380980-8d965bbd-394b-45f0-87ee-748b1a720296.mp4

</details>

2022-08-02 13:06 UTC, LudwigVonChesterfield commented on code/modules/mob/mob_movement.dm
> +			move_delay += add_delay * 0.4 // in general moving diagonally will be 1.4 (sqrt(2)) times slower
но нижняя кукла то все равно больше расстояния прошла из-за диагоналей...

2022-08-02 13:16 UTC, KIBORG04 commented on code/modules/mob/mob_movement.dm
> +			move_delay += add_delay * 0.4 // in general moving diagonally will be 1.4 (sqrt(2)) times slower
Диагональное движение сейчас абузится чтобы на изи уклониться от ударов и от пуль, теперь же че, это станет почти в 3 раза проще?

2022-08-02 13:26 UTC, notkripton commented on code/modules/mob/mob_movement.dm
> +			move_delay += add_delay * 0.4 // in general moving diagonally will be 1.4 (sqrt(2)) times slower
> 3 раза проще

На 30 процентов?

В тг (и на гунах?) на такой скорости спокойно живут учитывая что у них прожектайлы даже медленнее наших

2022-08-02 13:33 UTC, KIBORG04 commented on code/modules/mob/mob_movement.dm
> +			move_delay += add_delay * 0.4 // in general moving diagonally will be 1.4 (sqrt(2)) times slower
Мы не тг и гуны. Мы не чисто кска билд. У нас мили довольно слабое, в отличие от тг

2022-08-02 13:44 UTC, notkripton commented on code/modules/mob/mob_movement.dm
> +			move_delay += add_delay * 0.4 // in general moving diagonally will be 1.4 (sqrt(2)) times slower
У нас в отличие от кскобилдов по небронированной кукле голоурон от баллистики просто космический, стоит один раз попасть и кукла не сможет нормально мансить, к тому же есть ещё и пульки с хай велосити если боишься мазать, так что не вижу в этом какой-то серьезной баланс-проблемы

2022-08-02 13:48 UTC, KIBORG04 commented on code/modules/mob/mob_movement.dm
> +			move_delay += add_delay * 0.4 // in general moving diagonally will be 1.4 (sqrt(2)) times slower
И зачем это делать? "Qol" и "это будет выглядеть натуральней" не звучит как аргумент. Зачем быстрее бегать? Это высчитано по умной формуле и делает диагональное движение справедливее? Это решает какую-то проблему? Я пока вообще не понимаю

2022-08-02 14:00 UTC, TheLone1y commented
Эм я вроде баланс деп так что к чему я это, зачем ускорять на 30% по диагонали если ты на деле делаешь два шага за один клик? Я бы вообще понизил скорость ибо фичи для шарящих, вот сверху была гонка, но ты сделай пробежку по кругу, а не напрямую, в целом переработка пуллов и толканий убирает много рваностей, но это стелсобафф боевки? Добавляй лейбл баланс если хочешь продолжить тему с +30% или убирай эту херню

2022-08-02 14:50 UTC, kalazus commented on code/modules/mob/mob_movement.dm
> +			move_delay += add_delay * 0.4 // in general moving diagonally will be 1.4 (sqrt(2)) times slower
Не понимаю киборга что так против ускорения. Для мили это даёт плюс т.к. даёт лучше мансить (но при этом догнать убегающего манся все ещё не получится). На кс билде как-то попадают, а на нашем "рп билде" люди на бегу стреляющие с автомата без замедления попасть не могут.

2022-08-02 14:53 UTC, TheLone1y commented on code/modules/mob/mob_movement.dm
> +			move_delay += add_delay * 0.4 // in general moving diagonally will be 1.4 (sqrt(2)) times slower
У нас по диагонали буквально телепорт на два тайла ведь при переходе попасть по чуваку нельзя, да и это баланс тема, а не фьючирхтвикс

2022-08-02 15:01 UTC, kalazus commented on code/modules/mob/mob_movement.dm
> +			move_delay += add_delay * 0.4 // in general moving diagonally will be 1.4 (sqrt(2)) times slower
> при переходе попасть по чуваку нельзя

Ты серьезно? Ахаха.
А про баланс да, нужно твик на баланс заменить.

2022-08-02 15:12 UTC, KIBORG04 commented on code/modules/mob/mob_movement.dm
> +			move_delay += add_delay * 0.4 // in general moving diagonally will be 1.4 (sqrt(2)) times slower
Пифагор.... У нас даже по механу кукла делает два шага, а анимация делает диагональное.

2022-08-02 19:54 UTC, necrofill commented
Не согласен с ходьбой по диагонали в 1.4 медленее
Смысл же в том, что ты сокращаешь расстрояние двух тайлов, типо удобство, но скорость та же, будто ты прошел два тайла, нет?
думаю это надо оставить как есть

2022-08-02 20:13 UTC, notkripton commented
> Не согласен с ходьбой по диагонали в 1.4 медленее
> Смысл же в том, что ты сокращаешь расстрояние двух тайлов, типо удобство, но скорость та же, будто ты прошел два тайла, нет?
> думаю это надо оставить как есть

Ты перепутал, это сейчас диагональками ходят по времени как два тайла, а в пре я ускоряю

2022-08-02 20:18 UTC, necrofill commented
> > Не согласен с ходьбой по диагонали в 1.4 медленее
> > Смысл же в том, что ты сокращаешь расстрояние двух тайлов, типо удобство, но скорость та же, будто ты прошел два тайла, нет?
> > думаю это надо оставить как есть
> 
> Ты все перепутал, это сейчас диагональками ходят по времени как два тайла, а в пре я ускоряю (или это тонкая шутка и я не понял?)

Я написал следующее
Сейчас ходьба 2 в раза медленнее по диагонали
Ты хочешь сделать в 1.4
Я считаю, что диагональная ходьба, не дя сокращения дистанции у нас, а для удобства, что б не тыкать вверх лево например
Твоя фишка ломает концепцию тайл за шаг
Я не путал, скорость должна остаться 0.5 по диагонали, если она такая сейчас, и не должна быть ускоренной

2022-08-17 07:28 UTC, notkripton commented
@volas Можешь сделать заключение по пру? Мейнтейнерам не нравится, но от остальных фидбек положительный. Может сделать какую-нибудь темку на форуме с голосованием?

2022-08-27 15:01 UTC, volas requested changes

2022-08-27 15:01 UTC, volas commented on code/modules/mob/mob_movement.dm
> +			move_delay = max(move_delay, world.time + grab_delay)
с грабом я тут тоже не понимаю, почему move_delay может игнорироваться напрочь. В старом и новом варианте.

2022-08-27 16:18 UTC, notkripton commented on code/modules/mob/living/living.dm
> +			forceMove(M.loc, pulling == M) // so if we pulling this mob we will continue so
Там двойное равно стоит.

2022-08-27 16:34 UTC, notkripton commented on code/modules/mob/mob_movement.dm
> +			move_delay = max(move_delay, world.time + grab_delay)
Что-то совсем не врубаюсь о чем ты, правда

2022-08-27 16:36 UTC, volas commented on code/modules/mob/mob_movement.dm
> +			move_delay = max(move_delay, world.time + grab_delay)
что если world.time + grab_delay > move_delay, то мы старый move_delay не берем, по какой-то логике выбрасываем и берем новый move_delay = world.time + grab_delay

2022-08-27 16:37 UTC, volas commented on code/modules/mob/mob_movement.dm
> +			move_delay = max(move_delay, world.time + grab_delay)
т.е. если задержка с грабом большая, то все остальные игнорируются. Если нет, то игнорируется задержка граба

2022-08-29 08:45 UTC, notkripton commented on code/modules/mob/mob_movement.dm
> +			move_delay = max(move_delay, world.time + grab_delay)
Исправил.

2022-08-29 08:48 UTC, notkripton commented on code/modules/mob/living/living_defines.dm
> -	var/pull_debuff = 0		//Movement debuff when pulling
Дебаф от пулла теперь считается каждый ход, так как может изменяться динамически. За сим этот вар больше не нужен.

2022-09-03 10:46 UTC, volas requested changes
Просьба еще немного переделать чеинжлог, сами по себе записи сложно понять

2022-09-03 10:46 UTC, volas commented on code/modules/mob/living/living.dm
> +		step(src, t)
в некоторых случаях подобное поведение может быть не желательным, но посмотрим

2022-09-03 10:46 UTC, volas commented on code/modules/mob/living/living.dm
> +		tally += 1.5
потерялась проверка на pulling, сейчас это постоянная задержка для обезьян и слаймов

2022-09-03 10:46 UTC, volas commented on code/modules/mob/living/living.dm
> +		tally += M.stat == CONSCIOUS ? ( M.a_intent == INTENT_HELP ? 0 : 0.5 ) : 1
нам давно нужна фича с "советами" в лобби, эти скрытые механики слишком скрытые...

2022-09-03 14:51 UTC, notkripton commented on code/modules/mob/living/living.dm
> +		tally += 1.5
Не, эту проверку я вынес им в мувделей.
```
	if(pulling)
		tally += count_pull_debuff()
```
Своего рода микрооптимизация, потому что у бьенда внутри проблемы с вызовом методов и лучше оно будет проверяться до вызова, чтобы не теребить проки когда это в 90% случаев не нужно. Там была статейка в коде по этому поводу, но я ее потерял...

P.S. Сейчас я еще этот кусок с истайпами на срк убрал и сделал через перегрузки
```
/mob/living/carbon/monkey/count_pull_debuff()
	return ..() + 1
```
Вообще почему оно до меня было не так? Кринж

2022-09-03 15:02 UTC, notkripton commented
> Просьба еще немного переделать чеинжлог, сами по себе записи сложно понять

Добавил больше инфы в описание. Ну и ссылки на пр у изменений, которые лучше показать на видео, а не обьяснять текстом.

2022-09-10 22:24 UTC, volas commented on code/modules/mob/living/carbon/monkey/monkey.dm
> +	return ..() + 1
я думаю, проверка на pulling всё же желательна, что бы прок был независимым от каких-то внешних факторов и возвращал то, что от него ожидаешь

2022-09-10 22:25 UTC, volas commented on code/modules/mob/living/carbon/monkey/monkey.dm
> +	return ..() + 1
просто продублировать будет ок

2022-09-10 22:42 UTC, volas commented on code/modules/mob/mob_movement.dm
> -		move_delay = world.time//set move delay
тут кстати выше add_delay не инициализирован, и ниже у нас null складывается с числами. По мнению бьенда это ок, но можно было тоже поправить

2022-09-11 06:29 UTC, notkripton commented on code/modules/mob/living/carbon/monkey/monkey.dm
> +	return ..() + 1
добавил

2022-09-11 06:29 UTC, notkripton commented on code/modules/mob/mob_movement.dm
> -		move_delay = world.time//set move delay
поправил

2022-09-11 06:38 UTC, notkripton commented
@volas мерж? 🤐

2022-09-11 11:06 UTC, volas commented on code/modules/mob/living/carbon/human/human_movement.dm
> +	tally += count_pull_debuff()
ты мог оставить проверку на пуллинг и тут, и там, экономия на вызове прока хорошо а проверка переменной много не весит. Ну ладно.

2022-09-11 11:06 UTC, volas approved these changes

2022-09-11 13:58 UTC, merged

2023-11-20 20:03 UTC, TauKitty commented
Этот запрос на слияние был упомянут в **Tau Ceti Station Forum**. Там могут быть соответствующие подробности:

https://forum.taucetistation.org/t/podskazki-dnya/41407/1