Две новые фичи аутопсии
TauCetiStation/TauCetiClassic pull request #9809
Opened 2022-08-11 11:31 UTC by DarthSidiousPalpatine

## Описание изменений
Аутопсия показывает откуда нанесён удар, сверху или снизу, позволяет определить разницу роста между атаковавшим и жертвой.
Аутопсия показывает ДНК под ногтями бьющего голой рукой без предмета и перчаток.
![image](https://user-images.githubusercontent.com/21008918/184123765-a9fda42b-d798-4e34-895e-386bbe58d8db.png)

## Почему и что этот ПР улучшит
Два прикола аутопсии, полезнее и легче определить челикса.

## Авторство
Darth_Sidious и все все все, кто помогал в дискорде.

## Чеинжлог
 :cl:
 - rscadd: Аутопсия показывает ДНК под ногтями и разницу роста жертвы и атакующего.

2022-08-11 11:31 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2022-08-11 13:21 UTC, KIBORG04 commented on code/__HELPERS/mobs.dm
> +/proc/compare_heights(mob/living/carbon/human/A, mob/living/carbon/human/B)
Почему это глобальный прок, который находится вообще в code/__HELPERS/mobs.dm? Сделай `/mob/living/carbon/human/proc/compare_heights(mob/living/carbon/human/B)`

2022-08-11 13:22 UTC, KIBORG04 commented on code/__HELPERS/mobs.dm
> +/proc/check_hit_direction(mob/living/carbon/human/Attacker, mob/living/carbon/human/Victim)
Тоже самое

2022-08-11 13:23 UTC, KIBORG04 commented on code/__HELPERS/mobs.dm
> +/proc/check_hit_direction(mob/living/carbon/human/Attacker, mob/living/carbon/human/Victim)
Переименуй название, прок ниче не проверяет, прок связан с визуальным ростом, а не dir'ами

2022-08-11 13:30 UTC, KIBORG04 commented on code/modules/unarmed_combat/living_procs_defines.dm
> +						LARM.DNA_under_fingernail = H.dna.unique_enzymes
Вместо этого сделай где-то прок `get_active_arm()` `get_inactive_arm()`, где и будет такое. (Литтерали скопируй прок get_active_hand и измени 2 строчки)

2022-08-11 13:32 UTC, KIBORG04 commented on code/modules/organs/organ_external.dm
> +	var/DNA_under_fingernail = ""
Не у всех рас есть fingernail, ВРОДЕ

2022-08-11 13:36 UTC, KIBORG04 commented on code/game/objects/structures/watercloset.dm
> +			switch(H.hand)
Тут тоже самое про get_active_arm

2022-08-11 13:37 UTC, KIBORG04 commented on code/modules/detectivework/autopsy.dm
> +		if("left arm")
define юзай плиз

2022-08-11 15:15 UTC, DarthSidiousPalpatine commented on code/modules/detectivework/autopsy.dm
> +				D.more_info += "<tr><th colspan=\"5\"><b>DNA found under nails on left hand: [LARM.DNA_under_fingernail]</b></th></tr>"
резонно

2022-08-11 15:16 UTC, DarthSidiousPalpatine commented on code/game/objects/structures/watercloset.dm
> +			switch(H.hand)
забыл что оно существует. Везде юзается просто вида "H.hand ? BP_L_ARM : BP_R_ARM". надо будет пройтись везде заменить на гетарм

2022-08-11 15:18 UTC, DarthSidiousPalpatine commented on code/modules/organs/organ_external.dm
> +	var/DNA_under_fingernail = ""
Ну, у унатхов, таяр и воксов под когтями, у людей под ногтями, у дион в коре, у ИПЦ в щелях, остаются лишь скреллы, но плевать, в чешуйках?

2022-08-11 23:48 UTC, LudwigVonChesterfield commented on code/__HELPERS/mobs.dm
> +/proc/compare_heights(mob/living/carbon/human/A, mob/living/carbon/human/B)
но тем не менее ты сравнивашь хумана с хуманом

2022-08-11 23:49 UTC, LudwigVonChesterfield commented on code/modules/organs/organ_external.dm
> +	var/DNA_under_fingernail = ""
у ИПЦ и Дион есть NO_FINGEPRINTS флаг

2022-08-12 00:19 UTC, KIBORG04 commented on code/game/objects/structures/watercloset.dm
> +			switch(H.hand)
Но не в этом ПРе проходить и заменяй. Либо можешь той тернаркой обойтись

2022-08-14 03:24 UTC, DarthSidiousPalpatine commented on code/__HELPERS/mobs.dm
> +/proc/compare_heights(mob/living/carbon/human/A, mob/living/carbon/human/B)
Да, кстати, тупо

2022-09-10 20:02 UTC, DarthSidiousPalpatine commented
го я создал

2022-09-10 20:02 UTC, DarthSidiousPalpatine commented on code/modules/detectivework/autopsy.dm
> +				D.more_info += "<tr><th colspan=\"5\"><b>DNA found under nails on left hand: [LARM.DNA_under_fingernail]</b></th></tr>"
не резонно

2022-09-10 20:21 UTC, DarthSidiousPalpatine commented
Открывайте это полиция

2022-09-10 20:56 UTC, DarthSidiousPalpatine commented
ноль конфликтов, когда мерж?

2022-09-11 15:55 UTC, notkripton requested changes

2022-09-11 15:55 UTC, notkripton commented on code/modules/mob/living/carbon/human/human_helpers.dm
> +			message = "The hit has been dealt from a very above"
```suggestion
		if(-9 to -6)
			message = "The hit has been dealt from a very below"
		if(-5 to -2)
			message = "The hit has been dealt from a below"
		if(-1 to 1)
			message = "The hit has been dealt from a same height"
		if(2 to 5)
			message = "The hit has been dealt from an above"
		if(6 to 9)
			message = "The hit has been dealt from a very above"
```

2022-09-11 15:55 UTC, notkripton commented on code/modules/mob/living/carbon/human/human_helpers.dm
> +			second_height = 5
А может эти дефайны сразу числами задать а не строками?

2022-09-11 15:55 UTC, notkripton commented on code/modules/organs/organ_external.dm
> +	var/DNA_under_fingernail = ""
^
до сих пор актуально

2022-09-11 15:55 UTC, notkripton commented on code/modules/unarmed_combat/living_procs_defines.dm
> +						LARM.DNA_under_fingernail = H.dna.unique_enzymes
А если атаккер в перчатках? В риге? В любой другой одежде закрывающей руки? Ты все равно положишь ему днк под ногти будто он голый

2022-09-11 15:55 UTC, notkripton commented on code/game/objects/structures/watercloset.dm
> +				if(BP_R_ARM)
бп_арм никакого отношения к хуман.хенд не имеет, это вообще строка.
по поводу свича написал ниже

2022-09-11 15:55 UTC, notkripton commented on code/modules/unarmed_combat/living_procs_defines.dm
> +			switch(attacker.hand)
свич здесь не нужен. поставь иф елс

2022-09-11 15:56 UTC, notkripton commented on code/game/objects/structures/watercloset.dm
> +				if(BP_R_ARM)
https://github.com/TauCetiStation/TauCetiClassic/pull/9809#discussion_r967850223

2022-09-11 16:41 UTC, cool20141 commented on code/modules/organs/organ_external.dm
> +	var/DNA_under_fingernail = ""
> у ИПЦ и Дион есть NO_FINGEPRINTS флаг

А причем здесь отпечатки пальцев, если речь идет о частичках кожи?

2022-09-11 18:04 UTC, DarthSidiousPalpatine commented on code/modules/detectivework/autopsy.dm
> +				scan_data += "<td>[W.impact_direction]</td>"
кавооо

2022-09-11 18:04 UTC, DarthSidiousPalpatine commented on code/modules/mob/living/carbon/human/human_defense.dm
> +		impact_direction = check_hit_direction(H)
нет

2022-09-11 18:06 UTC, DarthSidiousPalpatine commented on code/modules/mob/living/carbon/human/human_helpers.dm
> +			second_height = 5
нет

2022-09-11 18:07 UTC, DarthSidiousPalpatine commented on code/game/objects/structures/watercloset.dm
> +				if(BP_R_ARM)
нет

2022-09-11 18:07 UTC, DarthSidiousPalpatine commented on code/modules/unarmed_combat/living_procs_defines.dm
> +			switch(attacker.hand)
свич круче

2022-09-11 18:11 UTC, DarthSidiousPalpatine commented on code/modules/unarmed_combat/living_procs_defines.dm
> +						LARM.DNA_under_fingernail = H.dna.unique_enzymes
сделал

2022-09-11 18:11 UTC, DarthSidiousPalpatine commented on code/modules/mob/living/carbon/human/human_helpers.dm
> +			message = "The hit has been dealt from a very above"
круть

2022-09-11 18:27 UTC, notkripton commented on code/modules/unarmed_combat/living_procs_defines.dm
> +		if(H.dna && !H.gloves)
Хуета. Риги и подобное все еще не учитываются. Сделай проверку через body_parts_covered вместо этого кринжа

2022-09-11 18:27 UTC, notkripton commented on code/game/objects/structures/watercloset.dm
> +			if(BP_R_ARM)
Я тебе голову откушу. Этот код НЕ РАБОТАЕТ, убери эти константы и замени нулем на правую руку и единицей на левую

2022-09-11 18:31 UTC, notkripton commented on code/modules/detectivework/autopsy.dm
> +				scan_data += "<td>[W.impact_direction]</td>"
я тебе скинул готовый код просто сделай копипаст к себе и закоммить

2022-09-12 15:45 UTC, notkripton commented on code/modules/mob/living/carbon/human/human_helpers.dm
> +	return message
Ты не учитываешь кравл у мобов. Аттакер или срк могут быть лёжа а ты все равно посчитаешь им удар с 'вери белоу'

2022-09-12 16:16 UTC, KIBORG04 commented on code/game/objects/structures/watercloset.dm
> +			if(BP_R_ARM)
![image](https://user-images.githubusercontent.com/26389417/189704625-6e715552-58a2-42d1-8267-773bb03c3fa5.png)
![image](https://user-images.githubusercontent.com/26389417/189704633-5932fc2b-56b8-47ff-9ae6-8626fd9a3eb8.png)


Капец, гисев все моё зарезолвал и оставил это

2022-09-12 17:09 UTC, DarthSidiousPalpatine commented
Чуваки, вы такие крутые, конечно, но, лучше бы, фотики и сингу замержили :dovolen:

2022-10-02 17:21 UTC, DarthSidiousPalpatine commented
Сначала терпим терпим

2022-10-09 11:54 UTC, KIBORG04 commented
Сорри, мерж конфликты не ревуваем

2022-10-09 12:00 UTC, DarthSidiousPalpatine commented
ай блин. как пропустил-то. Ну ничего, сейчас решу конфликты через три дня.

2022-10-09 12:30 UTC, KIBORG04 requested changes
Гисев, забей что я до этого писал про отдельный прок для рук. У нас есть уже есть крутые дефайны для этого. 

Убирай все свои крингесвитчи и замени на get_bodypart(BP_ACTIVE_ARM), который возвращает активную руку.

2022-10-22 08:36 UTC, DarthSidiousPalpatine commented
Атлант закупил гречи

2022-11-05 15:40 UTC, DarthSidiousPalpatine commented
Отставить!

2022-11-14 19:34 UTC, closed without merging