Возращение оператора меха в подпрофы тестовиков.
TauCetiStation/TauCetiClassic pull request #9810
Opened 2022-08-11 14:21 UTC by maleyvich

## Описание изменений
Оператор мехов возвращен в подпрофы тестовика
## Почему и что этот ПР улучшит
Благодаря скиллам эта профессия может пользоваться спросом у профессий, связанных с управлением мехов.
## Авторство

## Чеинжлог
🆑 
- :rscadd: Возвращение оператора мехов как подпрофессии тестовика

2022-08-11 14:21 UTC, TauKitty commented
###### Changelog status: :x: Empty changelog (check markdown correctness)

2022-08-11 14:28 UTC, Chip11-n commented
- rscadd:

2022-08-11 15:03 UTC, TheLone1y commented
Я не буду это комментировать.

2022-08-11 15:14 UTC, AndroBetel commented
а зачем он нужен-то? если большинство других подпроф тестовика позволяет заниматься своей фигней без оглядки на других космонавтов, то мехоператор пятое колесо в любом отделе, которому нужно ждать пока (если) ему сделают мех, почему-то отдадут мехоператору, а не парамедику (единственное применение мехоператора - это заменять парамедика, да) и потом сидеть-ждать раненых или ещё какой-нибудь фигни. ну или ролькохантить на мехе, да

2022-08-11 15:19 UTC, maleyvich commented
В голове я уже продумал две ситуации, где мех оператор может быть использован
1. Помощь мусорщикам в их работе.
2. Будет на мехе пястись за шахтером и помогать ему добывать ресурсы / отбиваться от существ.

2022-08-11 15:34 UTC, Deahaka commented
Сделайте его каргонцем, пусть помогает там, где он нужен.

2022-08-11 16:20 UTC, RONSI7 commented
Давайте порассуждаем где может пригодится пилот меха.

И так, допустим инженер мехов хорошенько попотел и сделал аж целых три меха за одну смену: Рипли, Одиссей и Гигакс. Рипли отдает шахтёрам, Одиссей получают парамедики, а Гигакса удостоился рядовой офицер. И теперь внимание вопрос - нужен ли работникам этих отделов частное лицо для эксплуатации данных экзоскелетов?

Вопрос риторический, ведь я знаю ответ - нет, не нужен. Ведь у шахтера и парамедика самый высокий навык это как раз таки пилотирование гражданских экзоскелетов, а значит специальный пилот меду и карго не нужен. Единственного кого может заменить пилот меха, так это офицера, но кто разрешит разгуливать по станции, в боевом экзокостюме, не имплантированному левому мужику?

Получается так, что пилот будет не особо востребован, то есть вообще не нужен.

2022-08-11 17:18 UTC, AirBlack commented
Понизить уровень владения мехам всем профам а у пилота оставить на максимальных/оч высоких. И вот теперь он нужен. На кой ляд кто-то будет учить ЧОПовца, который должен знать как стрелять с пистика и держать дубинку, как водить боевой блять мех??? Все равно, что охранников 6 разряда будут учить, как водить БТР и танк. А кто будет учить медика или парамедика как водить большую железную ебалдовину?? ИРЛ водители скорой помощи вроде не обязаны медицину знать, а просто должны хорошо аккуратно и быстро ездить.

2022-08-11 17:52 UTC, KIBORG04 commented
Профа бесполезная, скиллы не особо помогут.

2022-08-11 19:20 UTC, TryXAH commented
> большинство других подпроф тестовика позволяют заниматься своей фигней без оглядки на других космонавтов, то мехоператор пятое колесо в любом отделе, которому нужно ждать пока (если) ему сделают мех, почему-то отдадут мехоператору


То есть когда и где нужно это "великая социалочка и взаимодействие игроков", а где не нужно это "не может страдать хуйней в соло"

2022-08-12 10:10 UTC, Fluffy-510 commented
Все кто выступает против возвращения меха оператора не учитывают 3 вещи:
1 - это единственная профа для обучения вождения мехов, вы скажите: «мол а роботех что? На нём учись на мехах гонять» А я отвечу, что а - роботехов всего 2, б - на роботехе от тебя в первую очередь ждут бесконечное обслуживание картоных боргов, ВТЕК тот же, и они не захотят ждать пока ты будешь изучать для себя новые фичи на мехе.
2 - хоть многие профы и могут водить мехов, не каждый игрок умеет/использует эту фишку, у нас одисеи после робототехники могут весь раунд в меде стоять мёртвым грузом, тоже самое про гигасов в бриге 
3 - Нету профессии для обучения вождения мехам -> нету новых людей умеющих водить и пользоваться мехами -> нету людей, которые умеют пользоваться мехами -> мехи никто не использует -> мехи никто не использует -> «Назовите хоть одну причину существования мехов в билде кроме «большие и сильные»?…»

2022-08-12 10:22 UTC, Lafrien commented
Просто дайте МехВодиле максимальные статы на мехах, Боевых и Гражданских, а всем остальным понизьте до малых, но не минимальных значений. Так мы получим, что будет профессия, что специализируется на мехах, и простых парамедиков/офицеров не обделим.

Да и честно говоря тут мехи не беевские и обучаться ими водить ООС - плевое дело.

2022-08-12 10:32 UTC, Deahaka commented
> Просто дайте МехВодиле максимальные статы на мехах, Боевых и Гражданских, а всем остальным понизьте до малых, но не минимальных значений. Так мы получим, что будет профессия, что специализируется на мехах, и простых парамедиков/офицеров не обделим.

Мехвод не нужен будет никогда, пока у экипажа не нулевые скилы пилотирования мехов. А как только будут нулевые — лишь мехвод будет преградой перед выпилом говномехов.

2022-08-12 10:42 UTC, UsadoSmokk commented
да вы заебали, верните мехвода уже, как сказали, он может пилотировать мехи, плюсом, это техническая профа, что сможет в инженерию и роботику с научкой, а то у нас есть только всякие неудачники как адвокаты, частники и тд

2022-08-12 11:41 UTC, UsadoSmokk commented
> > да вы заебали, верните мехвода уже, как сказали, он может пилотировать мехи, плюсом, это техническая профа, что сможет в инженерию и роботику с научкой, а то у нас есть только всякие неудачники как адвокаты, частники и тд
> 
> мехвод от них ничем не отличается, такой же неудачник.

только почему-то они есть, а его нет

2022-08-12 15:37 UTC, KIBORG04 commented
Покажите мне ебало СБшника, который даст управлять гигаксом какому-то лоху-цивилу из самого низа ПДА.

2022-08-12 15:45 UTC, Mercurialaste commented
> Покажите мне ебало СБшника, который даст управлять гигаксом какому-то лоху-цивилу из самого низа ПДА.

![677DE9A1-C012-42BE-B182-6C332AD2109B](https://user-images.githubusercontent.com/90282587/184392588-584b8b5a-b6b1-427d-a22d-d14a56a884ef.jpeg)

2022-08-12 15:59 UTC, TryXAH commented
> Покажите мне ебало СБшника, который даст управлять гигаксом какому-то лоху-цивилу из самого низа ПДА.

До скиллов я на кадете выпрашивал мехов у офиков, если были, и выдавали нормально, так как сами они больше пешкодрапом бегать любят. Так что если вдруг будет мех, и напросится соответствующий кадр им управлять - чоб и нет. Если что, сразу в сб нанять с имплантом

2022-08-12 16:19 UTC, Mercurialaste commented
> > Покажите мне ебало СБшника, который даст управлять гигаксом какому-то лоху-цивилу из самого низа ПДА.
> 
> До скиллов я на кадете выпрашивал мехов у офиков, если были, и выдавали нормально, так как сами они больше пешкодрапом бегать любят. Так что если вдруг будет мех, и напросится соответствующий кадр им управлять - чоб и нет. Если что, сразу в сб нанять с имплантом

Есть альтернативный способ найма, более надежный. 
Вырезать мозг и пихнуть в ММИ, ММИ в. меха.

2022-08-13 12:05 UTC, AirBlack commented on code/datums/outfits/jobs/assistant.dm
> +    gloves = /obj/item/clothing/gloves/fingerless
новую строку в конец файла

2022-08-15 04:38 UTC, volas commented
линканите кто нибудь пр, когда его удалили

2022-08-15 05:46 UTC, KIBORG04 commented
Мы ещё вроде в дисе че-то обсуждали на его тему, но не помню уже
https://github.com/TauCetiStation/TauCetiClassic/pull/8601

2022-08-19 05:45 UTC, volas commented
выпилили без аргументации в том пр-е, и вот как теперь с ревертами решать

2022-08-19 05:53 UTC, volas requested changes
Я думаю, тут могут быть две проблемы.

* То, что тест сабжект это единственная доступная профа для первого захода от новичков. не прочитавших вики, и набегаторов. И мы не должны давать ей много, а водить мехи это однозначно слишком много.
* То, что используется общий лимит с тест сабжектами. Если какая-то из альт проф будет лучше голого тест сабжекта, по скилам или экипировке - только её и будут пикать.

Возможным решением было бы вынести профы как отдельные, или сделать еще одну какую-то профу-бандл с ограничениями и всеми этими репортерами/операторами/т.д.

2022-08-21 11:11 UTC, KIBORG04 commented
Из аргументов было, что меча оператор не вписывается в концепцию частника. Тест субжект это просто чувак на опыты. Всякие официанты зарабатывают баром, паранормалисты гаданием, адвокаты адвокатством и тд. Меча оператор же должен служить станции и работать со станционным имуществом на благом станции.

Поэтому, я могу согласится с возвращением меча оператора в виде каргонца. Там и чатик с обладателями мехов, там и зарплата, там и повышенный статус, из-за которого дадут порулить, может быть. А в виде ассистента он никому не нужен и никто не доверяет

2022-08-27 07:26 UTC, closed without merging

2022-08-27 07:27 UTC, volas commented
если будет какое-то альтернативное возвращение и исправление старых проблем, можно будет вернуться к вопросу