бафф и багфикс синдиборга
TauCetiStation/TauCetiClassic pull request #9815
Opened 2022-08-12 18:14 UTC by AndroBetel

## Описание изменений
синдиборг в настоящий момент слишком слаб. его арбалет работает только на голожопиков, патроны кончаются слишком быстро, а использовать меч - себе дороже, так как в боевых условиях разряжаешься ты из-за него ооочень стремительно. в этом пре я удаляю использование энергии при ударах мечом, делаю бесконечный* пп роботу и фикшу баг, связанный с оверлеем меча, а ещё по дефолту отключаю отображение робота в пда
пп теперь регенерирует патроны самостоятельно, так как таскать с собой дополнительный боезапас для него сложно как роботу, так и нюкеру. раз в примерно десять секунд пп синдиборга теперь регенерирует один патрончик. 40 патронов с нуля восстанавливаются примерно за 6 минут. 
## Почему и что этот ПР улучшит
удобство игры за синдиборга и фиксит баг
## Авторство
я
## Чеинжлог
:cl:
- balance: Пистолет-пулемет синдиборга самостоятельно восстанавливает патроны.
- rscadd: Синдиборг спавнится с отключенным ПДА.
- bugfix: Меч снова видно на спрайте синдиборга при его активации.

2022-08-12 18:14 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2022-08-12 19:39 UTC, Deahaka commented
Нужно ли синдиборгу вообще думать о батарейке? Есть ли на станции оружие, которое рассчитано снизить боргу заряд? Почему бы не убрать со всего кост за использование или дать батарейку в несколько раз лучше?

2022-08-12 20:53 UTC, Mercurialaste commented
> Есть ли на станции оружие, которое рассчитано снизить боргу заряд?

Ионки, ЭМИ от нюкеров.

Лучше дать батарейку по лучше. Та что сейчас, если не изменяет память, на 25 000. С ВТЭК и активным использованием меча, улетает она довольно быстро, учитывая что борга ещё и свои же бью ЭМИ. А зарядится боргу, скорее всего никто не даст. Может помочь замена батареи, но тогда уже придется искать подходящий вариант, а не 7 500.

2022-08-12 20:53 UTC, Mercurialaste commented
Мб к слову, дать ему перезаряжающийся ЕМАГ? Такой же был бы неплох и для дрона.

2022-08-14 07:13 UTC, RONSI7 commented
> Мб к слову, дать ему перезаряжающийся ЕМАГ? Такой же был бы неплох и для дрона.

Раньше у борга был бесконечный Е-маг, но его почему то посчитали багом, а не фичей и поправили это дело.

2022-08-14 18:10 UTC, Chip11-n commented
Синдиборгу почти бесконечные патроны для СМГ немного лишнее, а вот фулл набор для инструментов и флешка было бы шикарно

2022-08-14 19:36 UTC, AndroBetel commented
>БОЕВОЙ робот
>полный набор инструментов

игроки вы вообще с нашей планеты

2022-08-14 19:42 UTC, Chip11-n commented
> игроки вы вообще с нашей планеты
Так-то это борг отряда по уничтожению станции, отправленный на штурм, так что да, это вполне логично звучит для меня. Там конечно как хочешь, но борг почти везде немощ в плане помощи для команды помимо вырезания небронированных целей. Разве что стену обычную пропилит в начале штурма брига.

2022-08-14 19:46 UTC, kalazus commented
А почему вообще мини-антаг (помощник для антага) должен убивать всех и вся как обычный антага? С внесением хаоса и помощью в инжинерии он и так справляется.

2022-08-14 19:58 UTC, Mercurialaste commented
> > БОЕВОЙ робот
> > полный набор инструментов
> 
> игроки вы вообще с нашей планеты

> > БОЕВОЙ робот
Одно ЭМИ и ты труп.

2022-08-14 20:26 UTC, AndroBetel commented
фейк от лса, если ты не один гоняешь по станции то с помощью друга легко переживешь эми

2022-08-14 22:52 UTC, Mercurialaste commented
> фейк от лса, если ты не один гоняешь по станции то с помощью друга легко переживешь эми

Не фейк и не от лса.

"С помощью друга" ты можешь словить ЭМИ уже от него, можешь словить несколько пуль себе в затылок.
И да, "друг" ака, рандомному человеке на нюкере может быть просто плевать на тебя. 
Не говоря уже о ниличии хотя бы базовом понимании ремонта боргов.

Не знаю Бетель, где ты хоть раз видел, чтобы нюкер шел с синди боргом за ручку, учитывая что синди борг движется медленне чем обычный борг без ВТЭКа.

2022-08-15 03:36 UTC, TheLone1y commented
Аппрув

2022-08-16 08:10 UTC, TungstenOctopus commented
Каждый раз, когда я видел синдиборга, он буквально выпиливал все живое вокруг, и умирая забирал с собой как минимум несколько человек. Абсолютно не понимаю к чему баффать и так сильного (по наблюдениям) антагониста.

2022-08-16 09:54 UTC, AndroBetel commented
та просто пока у него патроны есть - он может убивать, как только кончились - остается только охотиться с арбалетом на голожопых одиночек, рискуя словить лазер или ионку, и это не весело совсем

2022-08-27 11:50 UTC, volas commented
... и теперь они может убивать бесконечно?

Тут бы какие-нибудь нерфы, для баланса

2022-08-27 11:52 UTC, volas commented on code/modules/projectiles/guns/energy/special.dm
> +	power_supply.give(25)
Стоит использовать компоненту, которую Deahaka сделал в https://github.com/TauCetiStation/TauCetiClassic/pull/9812

2022-09-03 10:53 UTC, volas requested changes
^

2022-09-03 12:02 UTC, AndroBetel commented
>Тут бы какие-нибудь нерфы, для баланса

основная мощч робота заключается не в пистолетике, а в отсутствии станов и в арбалете, вон там выше игрок жалуется. что робот умирает с одного эми, так что куда робота нерфить я не знаю

2022-09-14 20:05 UTC, volas requested changes

2022-09-14 20:05 UTC, volas commented on code/modules/mob/living/silicon/robot/syndi/syndiborg.dm
> -	var/hitcost = 500
По поводу нерфа. В моём понимании, раз ему поставили потребление энергии - значит, пытались забалансить сам меч. Ты убераешь потребление, но не меняешь меч, он остаётся всё с тем же дамагом. Сейчас один из самых больших.

Мне будет проще принять ПР, если ты компенсируешь отсутствие hitcost-а меньшим дамагом меча, например. Тем более, раз ты утверждаешь, что это не основное оружие - это не должно быть проблемой.

2022-09-14 20:05 UTC, volas commented on code/modules/projectiles/guns/energy/special.dm
> +	ammo_type = list(/obj/item/ammo_casing/energy/syndiborg)
И с смг аналогично.

2022-10-02 17:54 UTC, AndroBetel commented
йуйцуйцу12увфывфыв

2022-10-02 17:56 UTC, AndroBetel commented on code/modules/projectiles/guns/energy/special.dm
> +	ammo_type = list(/obj/item/ammo_casing/energy/syndiborg)
у смг ОЧЕНЬ долгая перезарядка, а дамаг там и так самый низкий как у пушки, так что с ним все норм

2022-10-02 17:56 UTC, AndroBetel commented on code/modules/mob/living/silicon/robot/syndi/syndiborg.dm
> -	var/hitcost = 500
снижу демедж

2022-10-02 18:04 UTC, AndroBetel commented on code/modules/mob/living/silicon/robot/syndi/syndiborg.dm
> +		sword_overlay.plane = -4
если не ошибаюсь, то layer оверлея был меньше нужного и из-за этого меч под роботом показывался

2022-10-04 05:39 UTC, volas commented on code/modules/mob/living/silicon/robot/syndi/syndiborg.dm
> +		sword_overlay.plane = -4
почему тогда тут используется plane а не layer? Как минимум определенно точно это не должно быть "-4", а какой-то дефайн или относительное значение

2022-10-09 12:06 UTC, KIBORG04 commented on code/modules/mob/living/silicon/robot/syndi/syndiborg.dm
> +	force_active = 200
Норм нёрф.

2022-10-09 12:07 UTC, KIBORG04 commented on code/modules/mob/living/silicon/robot/syndi/syndiborg.dm
> +		sword_overlay.plane = -4
Здесь скорее всего вообще плейн не надо менять, а только леер сделать выше.

2022-10-09 12:30 UTC, AndroBetel commented on code/modules/mob/living/silicon/robot/syndi/syndiborg.dm
> +	force_active = 200
о)

2022-10-23 11:16 UTC, volas commented on code/modules/mob/living/silicon/robot/syndi/syndiborg.dm
> +		sword_overlay.plane = -4
@AndroBetel

2022-11-10 14:31 UTC, closed without merging