baseball bat and its craft
TauCetiStation/TauCetiClassic pull request #9851
Opened 2022-08-16 12:32 UTC by Rahmanio

## Описание изменений
Добавлена бита и её крафт из 8 дерева.
У биты 11 урона. //урон не большой и не маленький, но можно изменить если не нравится, хотя на данный момент бита нормально вписывается.
Для сравнения:  У табуретки 10 урона + с некоторым шансом стан и 20 урона, у культблейда 30, у копья 10, в одной руке и 18 урона в двух. 
Биту можно положить в рюкзак, но она там занимает места, как станбатон. //можно изменить, но в реальной жизни бита в рюкзак помещается.
Под спойлерами картиночки для уточнения.
<details>

![Screenshot_2128](https://user-images.githubusercontent.com/67812445/184875681-ab12b7e8-5fa0-4ddd-9402-93d7c85c1ef4.png)

</details>

<details>

![Baseball_bite_from_Toby_thx_to_Ink_Void](https://user-images.githubusercontent.com/67812445/184875853-0b7fa206-4e3b-40da-ac29-ccc2222d8770.png)

</details>

## Почему и что этот ПР улучшит
Разнообразие оружия, в бандах хотя бы можно будет побегать с битами, как генгстеры, добавит атмосферы.
## Авторство
ToBy_BoN - основная идея, спрайты и желание, Rahmano - техническая часть.
## Чеинжлог
:cl: ToBy_BoN, Rahmano
* rscadd: Добавлена бита в игру и её крафт из дерева.

2022-08-16 12:32 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2022-08-16 13:56 UTC, RONSI7 commented
Маловато урона. Например у рядового петушителя в общей доступности 10 единиц физического урона, в то время как у твоей биты лишь на один пункт выше и с учетом того, что она делается из довольно редкого ресурса на станции(конечно если нет ботаников), а так же беря во внимания, что она будет подпадать в список неправомерных предметов и за нее могут посадить, то крафтить биту будут не очень часто.

Вот что я предлагаю: увеличить урон бите до уровня боевого ножа(13) и добавить маленький шанс кнока при ударе. Крафт усложнить до 15 досок и 3 кусков ткани(для рукояти).

2022-08-16 14:00 UTC, Deahaka commented
>с учетом того, что она делается из довольно редкого ресурса на станции(конечно если нет ботаников)

Дерева на карте дохуище.

>она будет подпадать в список неправомерных предметов и за нее могут посадить, то крафтить биту будут не очень часто.

А должно было быть иначе?

2022-08-16 14:04 UTC, Tobyyyan commented
> Маловато урона. Например у рядового петушителя в общей доступности 10 единиц физического урона, в то время как у твоей биты лишь на один пункт выше и с учетом того, что она делается из довольно редкого ресурса на станции(конечно если нет ботаников), а так же беря во внимания, что она будет подпадать в список неправомерных предметов и за нее могут посадить, то крафтить биту будут не очень часто.
> 
> Вот что я предлагаю: увеличить урон бите до уровня боевого ножа(13) и добавить маленький шанс кнока при ударе. Крафт усложнить до 15 досок и 3 кусков ткани(для рукояти).

Урон можно повысить, а про крафт - дороговато. Как пример, бита на тг стоит 5 дерева за целых 15 единиц урона и откидывание.

2022-08-16 14:10 UTC, Rahmanio commented
> Маловато урона. Например у рядового петушителя в общей доступности 10 единиц физического урона, в то время как у твоей биты лишь на один пункт выше и с учетом того, что она делается из довольно редкого ресурса на станции(конечно если нет ботаников), а так же беря во внимания, что она будет подпадать в список неправомерных предметов и за нее могут посадить, то крафтить биту будут не очень часто.
> 
> Вот что я предлагаю: увеличить урон бите до уровня боевого ножа(13) и добавить маленький шанс кнока при ударе. Крафт усложнить до 15 досок и 3 кусков ткани(для рукояти).

У нас дверь деревянная 10 досок? Твой крафт супер-нереалистичный будет, про ткань фейспалм, урон повышать тоже не реалистично и как-то глупо. Мы либо делаем норм логичное оружие и доступное. Либо имбаланс говно, которое потом удалят. Огнетушитель хорошое оружие и то что бита его аналог это даже лучше, ведь атмосфернее бить кого-то битой, нежели огнетушителем.

2022-08-16 14:19 UTC, BunkyFly commented
Было бы прикольно добавить возможность воткнуть в биту 5 отверток и повысить её урон на 15

2022-08-16 14:20 UTC, Rahmanio commented
> Было бы прикольно добавить возможность воткнуть в биту 5 отверток и повысить её урон на 15

Может быть, в будущем, добавим крафт усиленной биты с колючей проволокой. Но пока только такая будет бита.

2022-08-16 14:22 UTC, TheLone1y commented
Предлагаю сделать механику бекстабов, что бы если стукнули сзади по голове то человек терял сознание, как в боевиках, так урон маленький, я бы добавил двуручность и 17 урона ибо бита не сказать что полностью одноручное оружие

2022-08-16 14:27 UTC, Rahmanio commented
> Предлагаю сделать механику бекстабов, что бы если стукнули сзади по голове то человек терял сознание, как в боевиках, так урон маленький, я бы добавил двуручность и 17 урона ибо бита не сказать что полностью одноручное оружие

Мы хотим пока что просто биту, а потом уже другими прами улучшать и добавлять какие-то другие виды и двуручность.

2022-08-16 14:33 UTC, Rahmanio commented
> > Маловато урона. Например у рядового петушителя в общей доступности 10 единиц физического урона, в то время как у твоей биты лишь на один пункт выше и с учетом того, что она делается из довольно редкого ресурса на станции(конечно если нет ботаников), а так же беря во внимания, что она будет подпадать в список неправомерных предметов и за нее могут посадить, то крафтить биту будут не очень часто.
> > Вот что я предлагаю: увеличить урон бите до уровня боевого ножа(13) и добавить маленький шанс кнока при ударе. Крафт усложнить до 15 досок и 3 кусков ткани(для рукояти).
> 
> У нас дверь деревянная 10 досок? Твой крафт супер-нереалистичный будет, про ткань фейспалм, её не найти просто так, а то что на бите есть ткать, это спрайт такой, урон повышать тоже не реалистично и как-то глупо. Мы либо делаем норм логичное оружие и доступное, либо имбаланс говно, которое потом удалят. Огнетушитель хорошое оружие и то что бита - его лучший аналог, даже лучше, ведь атмосфернее бить кого-то битой, нежели огнетушителем.

2022-08-16 14:50 UTC, RONSI7 commented
> У нас дверь деревянная 10 досок? Твой крафт супер-нереалистичный будет, про ткань фейспалм, урон повышать тоже не реалистично и как-то глупо. Мы либо делаем норм логичное оружие и доступное. Либо имбаланс говно, которое потом удалят. Огнетушитель хорошое оружие и то что бита - его лучший аналог, даже лучше, ведь атмосфернее бить кого-то битой, нежели огнетушителем.

Повторюсь, я не предлагаю делать новую мету в области оружия, моя основная мысль в том, что у биты нет своей киллер-фичи ради которой ее будут крафтить. Смотрите, зачем, например крафтят копье или станпалку? Потому что у первого довольно высокий урон относительно простоты крафта, а у второго хороший стан, тоже относительно простоты крафта.

Что палка, что копье оба оправдывают затраченное время на их создание и риск ношения, потому что если выйти с таким оружие против оппонента с петушителем, то преимущество будет на твоей стороне. У биты такого нет - зачем 
 идти на лишние риски и делать лишние телодвижения добывая доски, когда будет куда проще и безопаснее взять с ближайшей стойки огнетушитель, ничего фактически от этого не потеряв, м?

Ради атмосферы? Да брось... Именно поэтому бите нужно что-то, что будет выделять ее на фоне списка импровизированного оружия доступного гражданским. Например, то что я предложил выше.

2022-08-16 15:12 UTC, UsadoSmokk commented
жду возможность вбить прутья в биту, дабы добавить шипы (и урон)

2022-08-16 15:18 UTC, RONSI7 commented
> Она добавляется ради аутентичности антагам, не для разьёба ролек
Она будет аутентично валятся в списке крафта на ровне с нынешней болой... И речь не о разьебе ролек, а целесообразности крафта.

2022-08-16 15:36 UTC, RONSI7 commented
Хорошо, если по задумке бита - это просто аналог огнетушителю, добавленный ради атмосферы, тогда ладно, понял. Я лишь попрошу, что бы вы увеличили урон хотя бы до 12 и добавили в рецепт крафта один кусок ткани. Ткань достать еще проще чем древесину.

2022-08-16 16:59 UTC, TungstenOctopus commented
Как вверху подметили, с уроном всего на 1 больше чем у огнетушителя, в этом нет смысла. Сделать ближе к цикрулярке - пусть 14 например, и уже norm

2022-08-16 17:09 UTC, Rahmanio commented
> Как вверху подметили, с уроном всего на 1 больше чем у огнетушителя, в этом нет смысла. Сделать ближе к цикрулярке - пусть 14 например, и уже norm

Выше 13 урона я бите не дам, в общем сделаю 13 урона, но не больше. Изначально я планировал 12 урона, как на ТГ, но потом решил сделать 11.

2022-08-16 17:35 UTC, GermanSUS commented
Тогда в будущем надо добавить фитчу бите как отбитие гранат. Вот прикиньте кидает сбшник в тебя флешбенг а ты хоп, и обратно его.

Ну и конечно набор трейтору с металлической битой со своими имба трейторскими приколами.

2022-08-16 20:44 UTC, Tobyyyan commented
> Тогда в будущем надо добавить фитчу бите как отбитие гранат. Вот прикиньте кидает сбшник в тебя флешбенг а ты хоп, и обратно его.
> 
> Ну и конечно набор трейтору с металлической битой со своими имба трейторскими приколами.

Про металлическую биту: Была идея дать дилерам в гэнгах алюминиевую биту в фултон. Чтобы она стоила 1-2тк. Повысить урон, звук удара металлический. Но это будет наверное тогда, когда и бита с прутами. Ибо обычная бита - это оружие самообороны, нежели наоборот атаки. 
Про триторов ничего не обещаем, у них и так полный аплинк добра.

2022-08-16 23:00 UTC, Tobyyyan commented
![image](https://user-images.githubusercontent.com/104164680/184999341-fe812405-139a-4728-831e-954bb289cfc1.png)
![image](https://user-images.githubusercontent.com/104164680/184999370-08bc3f5e-4a11-4e6b-af27-1ca8ee25898d.png)
Что то такое намечается, держу вас в курсе. Если не нравятся спрайты, предлагайте что изменить. (Или рисуйте сами ;D, если не лень)

2022-08-16 23:56 UTC, kiVts commented
Я посмотрел на крафт меню и как то тоошно стало что там такой сендвич и даже пикселя паддинга нет(мало на нтмле писал вроде так) 
короче надо место между кнопками

2022-08-17 00:39 UTC, Mercurialaste commented
> ![image](https://user-images.githubusercontent.com/104164680/184999341-fe812405-139a-4728-831e-954bb289cfc1.png)
> ![image](https://user-images.githubusercontent.com/104164680/184999370-08bc3f5e-4a11-4e6b-af27-1ca8ee25898d.png)
> Что то такое намечается, держу вас в курсе. Если не нравятся спрайты, предлагайте что изменить. (Или рисуйте сами ;D, если не лень)

Попробуй гвозди в разные стороны развернуть, мб, чтобы пару гвоздей как бы выглядывали из-за биты.

Добавь мб немного объема на её верхнюю часть… хз.

2022-08-17 07:20 UTC, Rahmanio commented
> Я посмотрел на крафт меню и как то тоошно стало что там такой сендвич и даже пикселя паддинга нет(мало на нтмле писал вроде так) короче надо место между кнопками

Делай отдельное ишью - пропосал, к этому пру это не относится. Я знаю как сделать место между кнопками, но не в этом пре.

2022-08-19 13:12 UTC, Rahmanio commented
убери мерж конфликт робот и это мерж реди

2022-08-27 17:52 UTC, UDaV73rus requested changes
Спрайты в руке жидкие, короткая палочка не опасненькая

2022-09-14 20:08 UTC, volas commented
Пока закрою, будет вновь актуально - слапни

2022-09-14 20:08 UTC, closed without merging

2022-12-07 04:55 UTC, TauKitty commented
Этот запрос на слияние был упомянут в **Tau Ceti Station Forum**. Там могут быть соответствующие подробности:

https://forum.taucetistation.org/t/hotite-li-vy-dobavlenie-novyh-kraftov/36648/29