Миротворец
TauCetiStation/TauCetiClassic pull request #9865
Opened 2022-08-18 11:20 UTC by Deahaka

## Описание изменений
ПР является альтернативой https://github.com/TauCetiStation/TauCetiClassic/pull/9801, в связи с решением сообщества не удалять Стандартный модуль у боргов:
![00000](https://user-images.githubusercontent.com/96499407/185378919-0c7ff9c8-a3bc-4a01-b90d-040947819d50.png)
Изменения с прошлого ПРа:

- Выбрать Миротворца можно только если есть секюрити плата (боланс);
- HARM ALARM! - [уменьшено время конфузеда до 5/10 при емаге, потребление энергии при емаге увеличилось до 2500, невзломанному крику добавлена проверка на шлем с защитой от флешек];
- Специальный гипоспрей - [добавлен бикаридин. Вместимость увеличена до 15, в три раза увеличено потребление энергии];
- Энерго-меч удалён;
- Добавлен открываемый емагом Гранатомёт - [Потребление: 500 за выстрел. Может быть заряжен: флешками, дымовыми гранатами, слезоточивыми гранатами и мэнхаками. Последние кушают 1/3 максимального заряда борга];

Сопуствующее изменение:
- Резадон перестал быть токсичным в связи с экипированием его боргом. Там всего то 16 токс урона за 10 едениц в теле. Думаю никто не против?
## Почему и что этот ПР улучшит
Геймплей
## Авторство

## Чеинжлог
:cl: Deahaka
- add: Киборгам добавлен модуль Миротворца.
- tweak: Резадон перестал быть токсичным.

2022-08-18 11:20 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2022-08-18 11:29 UTC, AndroBetel commented
охранного борга удалить when

2022-08-18 13:12 UTC, kiVts commented
добавляем еще один модуль который никто не будет брать

2022-08-18 14:49 UTC, Mercurialaste commented
Можешь сделать харм модуля объятий и куки диспенсера переключаемыми в случае емага? *(Мастеру может быть нужна помощь, а его борг бьет электроперчаткой вместо сброса стана. Мастер может захотеть покушать, на покушай печенья с политриником.)*

И да, мб вместо 5 унций политриника в отравленном печенье запихнуть «нейротоксин» и мут токсин? Это будет всяко полезнее, чем урон политриника. *(Учитывая что эту печеньку нужно ещё кому-то пропихнуть в рот, неплохо было бы дать гриппер сервис борга.)* 

Зачем в гипоспрее криптобионалин? 
Почему бы вместо бика, не закинуть иноправолин и анти-токсин? *(Анти-токсин выводит яд, иноправолин, спасает от удушья, если нужно, борг может сварить в человеке трик для лечения ожогов.)*

Я правильно понимаю, что гранаты в гранатомете по сути бесконечные, но при этом, тратят заряд батареи? 

Мало смысла давать огнетушитель, если борг не может его заправить из бака с пеной.
Ещё бы ломик, для передвижения через обесточеные шлюзы. 

Вместо платы модуля СБ, можно сделать отдельную плату миротворца. 
*(Из-за ограниченности количества именно СБ модулей, модулю СБ будет отдаваться большее предпочтение из-за его снаряжения+лазерки.)*

2022-08-18 16:33 UTC, Mercurialaste commented
> Огнетушитель можно сделать заправляемым из зарядки, но мне кажется никто и те 250 пены не будет выпшикивать. У нас нет антагов, которые умирают от огнетушителя.

У нас есть огонь и игроки как факт.
На моей памяти были как минимум 5 случаев, когда кто-то намеренно прятал все быстродоступные огнетушители и начинал обливать всех топливом. Обычно, это всякие клоуны. А так, сама по себе возможность не один раз потушить пожар в приоритете. *(И себя, урон 4х берном не забывай.)*



> Зачем давать метовую штуку в печенье, которая делает игрока беспомощным?

Если положить мут токсина и нейротоксина по 2.5 унции, то чтобы они нормально работали, придется или их выживать и колоть, или заставить жертву съесть их достаточно много. Насколько  я помню, нейротоксин довольно быстро выветривается. *(Реагенты из еды усваиваются не сразу, т.е. действие не моментальное.)*



> Криптобиолин для тех, кого не берёт флешер и харм аларм.

Переход на ходьбу уже делает и крипту бесполезной. 
Хотя мысль я понял, юзать против, тех кто в очках и шлеме. 
:peka:

Сервис гриппер/ломик?

2022-08-18 16:44 UTC, Deahaka commented
> У нас есть огонь и игроки как факт. На моей памяти были как минимум 5 случаев, когда кто-то намеренно прятал все быстродоступные огнетушители и начинал обливать всех топливом. Обычно, это всякие клоуны. А так, сама по себе возможность не один раз потушить пожар в приоритете. _(И себя, урон 4х берном не забывай.)_

Пусть не занимается тушением пожаров и экономит. Это ж не модуль пожарника. Для этого есть другие профессии.


> Если положить мут токсина и нейротоксина по 2.5 унции, то чтобы они нормально работали, придется или их выживать и колоть, или заставить жертву съесть их достаточно много. Насколько я помню, нейротоксин довольно быстро выветривается. _(Реагенты из еды усваиваются не сразу, т.е. действие не моментальное.)_

Это и есть причина почему там политринник, а не какой-нибудь альфтаамин. Нужно слишком много съесть и эффект получается слишком пепежный. Политринник действует немного сначала и потом уже также как другие яды, но только из одного печенья, а не из 3-х и более.

> Сервис гриппер/ломик/антитоксин и иноправолин вместо бика?

А для чего? Ломик можно дать, антитоксин для выпивак в баре?

2022-08-18 16:56 UTC, Mercurialaste commented
> А для чего? Ломик можно дать, антитоксин для выпивак в баре?

Можно для них. Хотя от части, он нужен вкупе с иноправолином. Читай выше или вот ещё раз, но более скомкано — «по мелочи лечение ожогов, физ травм, удушья и токсинов» 

Если будет антитокси+иноправолин, как и упоминал, можно убрать бикардин. *(Плюсом, у борга меньше возможности отравить лекарством, разве что вокса обколоть иноправолином.)*

Сервис гриппер — кормить кого-то. Фича с печеньками я предвижу, загнется как и отравленное пиво у сервис борга. 

*(Ну и сейчас пришло в голову, в гипоспрей можно было бы закинуть парацетомол, самое слабое обезболивающие.)*
 
 
*(Помянем разводной ключ, посмотри мб, что у других боргов с огнетушителями, как я помню, упоминалось где-то, что они восполняются от станции зарядки. Если конечно, возможность открывать огнетушитель настолько имба.)*

2022-08-18 17:00 UTC, Deahaka commented
Печеньки это фансервис, не нужно принудительное кормление. 
Удалю бик, добавлю инапровалин, антитокс и парацетамол в гипоспрей.
Открывать огнетушитель это очень имба, да, ты правильно сказал.

2022-08-18 17:20 UTC, Mercurialaste commented
> Открывать огнетушитель это очень имба, да, ты правильно сказал (см. нерф смазки ТОЛЬКО из-за саенсборга с его смазочным тушителем и сваренный политринник у медборга).

Упускаешь тот факт, что без колбы, он не сможет наполнить огнетушитель чем-то, что не содержится в цистернах. *(У медборга политриник в взломанном модуле.)*

*(Небольшая сноска по поводу мут токсина и нейротоксина у печенек.)*

У боргов мало возможности уйти в стелс. Максимум, вытянуть из малопосещаемого отдела во время ионносферной или при отключении телекомов с помощью ИИ. В случае, когда боргу нужно убить/покалечить кого-то и он при этом, не имеет поддержки ИИ, в большинстве случаев, начинается обычная резня, в которой старые борги мб и могли что-то сделать, сейчас, в худшем случае, умирают за 3 выстрела. Т.е. нужен способ ликвидации, который предотвратит при первом харме крик в рацию о «[борг_нейм] убивает!». Печеньками с политриником, можно убить, если постараться, но для этого, нужно будет скормить унций 20-30, не помню сколько точно наносит 5 унций политриника по урону. *(Хотя даже так, жертва просто кричит о отравленных печеньках и план снова не удается.)* В случае того, что я предлагал, с нейротоксином и мут токсином, у борга есть время стянуть рацию, запереть челика в шкафу, мб, перед всем этим скормив ещё пару печенек и утащить в Бразилию к своему мастеру. *(Ну, или если ты совсем скучный — выкинуть в космос.)*

> Печеньки это фансервис

Ты такие слова не говори, я тут из всего максимум пользы выжму.

2022-08-18 18:09 UTC, Deahaka commented
> Упускаешь тот факт, что без колбы, он не сможет наполнить огнетушитель чем-то, что не содержится в цистернах.

Это буквально причина почему у него не должен быть бесконтрольный способ наполнять тушитель. Медборг может всё сварить без модулей, он может в химию.

> У боргов мало возможности уйти в стелс. 

Дай сервис боргу стелс или стандартному, или кому-нибудь ещё. Этот может за играть успешно не через стелс.

2022-08-19 17:22 UTC, Mercurialaste commented
Крч, киллерфича. Сделай, чтобы обнимашки прокали муд ивент, немного бафающий настроение на минуту и более, а хармобнимашки, наоборот, дебафали настроение.

2022-08-19 19:13 UTC, Deahaka commented
> Крч, киллерфича. Сделай, чтобы обнимашки прокали муд ивент, немного бафающий настроение на минуту и более, а хармобнимашки, наоборот, дебафали настроение.

Я посмотрел на код хелп интента и пришёл к выводу, что если там нет ивента на повышение настроения после того как потрогали за гроин, то и боргу оно не надо.

2022-08-27 13:10 UTC, volas commented
всё ок, но спрайты какие-то смешные и в кривой (особой) проекции, мне не нравится

2022-08-27 13:12 UTC, Deahaka commented
Я искал на нескольких билдах и там все используют этот спрайт. Других или альтернативных, к сожалению, нет.

2022-08-27 13:15 UTC, volas commented
попробуй в #sprites спросить, может кто будет заинтересован. Я не вижу сильной необходимости в борге, что бы мержить не смотря на спрайт

2022-08-27 13:16 UTC, volas commented
Или поискать спрайт от каких-нибудь других боргов, их на разных билдах много рисовали, может что-то подойдет

2022-08-27 15:23 UTC, Deahaka commented
Просмотрел 13 билдов: 
на Скайрате все борги покрашены в белый и названы миротворцами, там есть вот такой подходящий, но не особо выразительный спрайт
![0000000](https://user-images.githubusercontent.com/96499407/187036371-d519edd2-d34a-4688-b414-9e388cb1c067.png)
на ВГ есть ещё спрайты вот такие 
![image](https://user-images.githubusercontent.com/96499407/187036287-65af8d88-8d04-4004-8723-ad74cb29c0db.png)
 на Аврора-стейшен есть вот такой что-то околопохожий, но очень агрессивный вариант
![000](https://user-images.githubusercontent.com/96499407/187036353-56c56769-7e95-44b1-b92e-20d549076631.png)
 у нас есть вот такой робот, но он не всем нравится и это рескин стандартного борга.
![image](https://user-images.githubusercontent.com/96499407/187036449-056a465c-4c06-4481-8ab8-18fe4c9b17c6.png)
Это все варианты что соответствуют инвентарю и геймплею борга. Буду ждать, может появится ещё вариант от [Меркулясте ](https://github.com/Mercurialaste)или кто-то что-то скинет из какого-нибудь закрытого лайфвеба, если этот совсем не нравится.

2022-08-27 17:57 UTC, UDaV73rus approved these changes
Дефолтный спрайт из прошлого, к полубоку притензий нет

2022-08-28 09:41 UTC, Deahaka commented
Убрал резадон, добавил вместо него лекарство от похмелья (которое игроки используют чтобы убирать Confused, оказывается). Дал возможность лечить ним разможжённое лицо.

2022-09-10 22:54 UTC, volas commented
Одобрения удава не существует, я всё еще жду спрайт в привычной у нас проекции. Иначе это какое-то бельмо на глазу будет.

2022-09-11 17:17 UTC, Deahaka commented
Спрайт поменял на Марину + обычный борг. Попытаюсь закончить боковушку оригинального и залить когда-нибудь

2022-09-14 20:37 UTC, volas requested changes

2022-09-14 20:37 UTC, volas commented on code/modules/reagents/grenade_launcher.dm
> +			current_grenade = /obj/item/weapon/grenade/spawnergrenade/manhacks
мне кажется, manhacks гранаты будут слишком. Лучше убрать, или сделать какое-то ограниченное количество

2022-09-14 20:40 UTC, volas commented on code/modules/reagents/grenade_launcher.dm
> +			current_grenade = /obj/item/weapon/grenade/spawnergrenade/manhacks
другие может тоже, при дефолтном заряде 10к - 20 любых гранат пока он не разрядится. Может быть слишком.

2022-09-14 21:27 UTC, Deahaka commented on code/modules/reagents/grenade_launcher.dm
> +			current_grenade = /obj/item/weapon/grenade/spawnergrenade/manhacks
Ну предлагаю тогда 1500 за выстрел, итого 6 раз.
А мэнхак могу до 50% сделать, но 5 штук по 15 хп и 15 урона и при этом от них можно убежать до того момента пока граната откроется + они раздуплятся... разве что какого-нибудь одинокого паренька без топора в ботанике победят, но точно не составят сопротивления кому-то ещё. Разве емагу киборга нельзя быть хотя бы немного хорошим?

2022-09-14 22:08 UTC, volas commented on code/modules/reagents/grenade_launcher.dm
> +			current_grenade = /obj/item/weapon/grenade/spawnergrenade/manhacks
5 штук в каждой, 3-4 - и весь отсек ими забит. А батарейку еще и поменять можно.

2022-09-14 22:12 UTC, volas commented on code/modules/reagents/grenade_launcher.dm
> +			current_grenade = /obj/item/weapon/grenade/spawnergrenade/manhacks
и как бы там ни было, они довольно кусачие. Сейчас может и меньше, но у меня до сих пор давняя травма по их поводу.

2022-09-15 07:07 UTC, Deahaka commented
Убрал манхаки, поставил гранаты с кислотой. Бьют в среднем на 3 клетки. Так как ими невозможно спамить, ведь кислота разъедает другие гранаты под собой, до того как они сдетонируют, убираю 1/3 траты энергии, оставляю общие 1500.

2022-09-15 07:09 UTC, Deahaka commented
Последний вариант, если это тоже не подойдёт, добавить боргу огнемёт. Но надо ещё сделать такой, чтобы не потреблял форон за выстрел.

2022-09-15 10:22 UTC, volas commented on code/modules/reagents/grenade_launcher.dm
> +			current_grenade = /obj/item/weapon/grenade/chem_grenade/acid
кислота может быть еще даже хуже будет, но по крайней мере не спам мобов

2022-09-16 01:10 UTC, volas commented on code/game/objects/items/weapons/grenades/chem_grenade.dm
> +	B2.reagents.add_reagent("phosphorus", 50)
зачем space_drugs в обоих контейнерах

2022-09-16 04:44 UTC, Mercurialaste commented on code/game/objects/items/weapons/grenades/chem_grenade.dm
> +	B2.reagents.add_reagent("phosphorus", 50)
Затем, что для взрыва нужно смешать 50 калия, 50 фосфора и 50 сахара, есть их поместить в один контейнер, то они сразу детонируют. А в этом случае, на дым с мощностью 50 у нас получается 150 унций космонаркотика, а не 100.

2022-09-16 07:48 UTC, volas commented on code/game/objects/items/weapons/grenades/chem_grenade.dm
> +	B2.reagents.add_reagent("phosphorus", 50)
понял, забыл что они ограничены

2022-09-16 07:48 UTC, volas approved these changes

2022-09-17 15:31 UTC, merged

2023-05-29 11:44 UTC, TauKitty commented
Этот запрос на слияние был упомянут в **Tau Ceti Station Forum**. Там могут быть соответствующие подробности:

https://forum.taucetistation.org/t/golosovanie-udalenie-sb-modulya-borgu/39540/12