Ребаланс захвата у хлыста генокрада
TauCetiStation/TauCetiClassic pull request #9872
Opened 2022-08-19 08:05 UTC by Deahaka

## Описание изменений
Хлыст на граб интенте с шансом притягивает предметы, а если это карбон - берёт его в синий захват.
Так как это реализовано как пуля - с расстоянием есть шанс просто попасть сквозь моба, мол уклонился.
Было: 
+ шанс 90 на некарбонов;
+ 60 - (броня торса * 0,4) для карбонов

Стало: 
+ шанс 100 на некарбонов;
+ 100 - броня атакуемой части - 20 штраф за атаку не в конечность или голову - 10 штраф за дальность атаки по конечностям (с шансом прокает).

[Х/Y/Z]:
- Х урон в торс;
- Y урон в голову;
- Z урон в конечность;

ОБОП - проверялся самый сильный эквип, не инспектор. Штраф за дальность не указан в таблице.

| Тесты | Было | Стало |
|:-------------: |:---------------:| :-------------:|
| Голый | 60 |     **80/100/100** |
| Детектив | 40        |        **20/100/40** |
| Офицер | 40 |        **20/50/90**   |
| Булетпруф | 56        |        **60/90/80** |
| Риотка | 28        |        **-10/18/10** |
| ОБОП | 32        |       **10/30/40** |
| ОБР | 36        |        **20/40/40** |
| Дедсквад | 28        |       **0/20/20** |
| ХоС |    24    |       **-10/-10/20** |
| Риг ГСБ |    38    |       **35/55/55** |
| Риг охраны | 38        |       **25/55/45** |

Кратко: 
- голые челы теперь не рандомно притягиваются;
- всё что хорошо защищает от мили уменьшает шансы до 20% и меньше;
- всё что не защищает конечности - фактически делает вас "голым" против граба хлыста.

То есть теперь на граб можно положиться намного увереннее, не делая его оружием завязанном на удаче. ПР является частью #9867 уменьшения популярности армблейда, не нерфая армблейд.
## Почему и что этот ПР улучшит
Баланс и геймплей
## Авторство

## Чеинжлог
:cl: Deahaka
- balance: Переработан шанс на захват у хлыста генокрада.

2022-08-19 08:05 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2022-08-27 13:42 UTC, volas requested changes

2022-08-27 13:42 UTC, volas commented on code/game/gamemodes/modes_gameplays/changeling/powers/Whip.dm
> +/obj/item/projectile/changeling_whip/on_hit(atom/target, blocked = 0)
мне кажется, def_zone тут следовало оставить. На неконсистентность параметров еще линтер должен был бы ругаться, но чего-то молчит

2022-08-28 10:56 UTC, Deahaka commented on code/game/gamemodes/modes_gameplays/changeling/powers/Whip.dm
> +/obj/item/projectile/changeling_whip/on_hit(atom/target, blocked = 0)
Да, не стоило удалять аргумент полностью. Вернул на место.

2022-09-03 11:03 UTC, volas commented on code/game/gamemodes/modes_gameplays/changeling/powers/Whip.dm
> +/obj/item/projectile/changeling_whip/on_hit(atom/target, def_zone, blocked = 0)
а дефолтное значение чего не вернул?

2022-09-04 11:06 UTC, Deahaka commented on code/game/gamemodes/modes_gameplays/changeling/powers/Whip.dm
> +/obj/item/projectile/changeling_whip/on_hit(atom/target, def_zone, blocked = 0)
Посмотрел в коде, поставил дефолт на чест.

2022-09-06 15:54 UTC, volas approved these changes

2022-09-06 15:55 UTC, merged

2022-12-13 23:16 UTC, TauKitty commented
Этот запрос на слияние был упомянут в **Tau Ceti Station Forum**. Там могут быть соответствующие подробности:

https://forum.taucetistation.org/t/obsuzhdenie-golosovanie-apdejt-genokradov/36786/1