Фикс инстастанов и прочих абузов баклов, крио etc.
TauCetiStation/TauCetiClassic pull request #9892
Opened 2022-08-21 09:45 UTC by TungstenOctopus

## Описание изменений

Стулья, кровати, каталки: 

- Маленькая задержка, когда баклишь другого человек 
- Теперь можно баклить(-ся) с соседнего тайла
**То есть драг-н-дроп стал ближе к грабу, у которого все этих механики уже есть.**
![dreamseeker_vwcADjTs9P](https://user-images.githubusercontent.com/6051766/185784472-6d2b0b51-eae8-4d98-a690-1da0aa5ecfc3.gif)

Крио:
- Задержка при помещении человека в крио
![dreamseeker_c1ULcTleGF](https://user-images.githubusercontent.com/6051766/185784508-0bba0ebc-0af1-426e-bfe2-5ab16095e4db.gif)

Ящик:
- Теперь когда человек залезает на ящик, а ящик в это время открывают, стан меньше. 

## Почему и что этот ПР улучшит

Закроет многочисленные абузы медбейной техники, позволявшие инстастанить
<details> 
  <summary>Примеры использования инстастанов (взято из реальной жизни)</summary>
  
![dreamseeker_ehxsKozETb](https://user-images.githubusercontent.com/6051766/185784719-5291245f-8acc-4f1d-873a-471c058e8f64.gif)

![dreamseeker_G6BhvFkpCC](https://user-images.githubusercontent.com/6051766/185785088-8efb9a48-bee1-4ccf-beab-4ee6aa01443f.gif)

</details>

## Авторство

## Чеинжлог

:cl:
 - tweak: Появилась задержка при попытке посадить человека на стул/кровать/каталку.
 - tweak: Появилась задержка при помещении человека в крио.
 - tweak: На стулья и кровати теперь можно сажать с соседнего тайла.
 - tweak: Уменьшен стан при падении с открываемого ящика, когда залезаешь на него.

2022-08-21 09:45 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2022-08-21 09:56 UTC, notkripton commented
Сделай зависимость от интента и состояния куклы (коншус, инконшус, дед), потому что так это полная кринжатина и будет больше мешать.

2022-08-21 09:57 UTC, TungstenOctopus commented
> Сделай зависимость от интента и состояния куклы (коншус, инконшус, дед), потому что так это полная кринжатина и будет больше мешать.

От интента - однозначно нет. Безсознательных - обсуждаемо, но нужны аргументы за

2022-08-21 09:59 UTC, notkripton commented
> > Сделай зависимость от интента и состояния куклы (коншус, инконшус, дед), потому что так это полная кринжатина и будет больше мешать.
> 
> От интента - однозначно нет. Безсознательных - обсуждаемо, но нужны аргументы за

Посмотри как я реализовал увеличение задержки пулла от состояний в своем пре на мувмент и сделай также

2022-08-21 10:01 UTC, notkripton commented
Вообще эту логику надо будет изолировать в отдельный прок, поместить туда где надо и заставить всех его использовать в подобных случаях. Займусь этим в ближайшие дни, когда буду дома

2022-08-21 11:17 UTC, KIBORG04 commented on code/game/objects/buckling.dm
> +			M.forceMove(src.loc)
```suggestion
		if(M.loc != loc)
			if(!do_after(user, 16, target = M))
				return
			M.forceMove(loc)
```

2022-08-21 11:18 UTC, KIBORG04 commented on code/game/objects/buckling.dm
> +		buckle_mob(M)
Надо обернуть buckle_mob в еще одну ифку, там есть свои проверки.

2022-08-21 11:21 UTC, KIBORG04 commented on code/game/objects/buckling.dm
> +				M.forceMove(src.loc)
Не копипасть. У тебя в одном иф-елсе два одинаковых куска кода

2022-08-21 11:21 UTC, KIBORG04 commented on code/game/objects/buckling.dm
> +			buckle_mob(M)
Надо обернуть buckle_mob в еще одну ифку, там есть свои проверки.

2022-08-21 12:26 UTC, KIBORG04 commented on code/game/objects/buckling.dm
> +	 			"<span class='notice'>You hear metal clanking.</span>")
```suggestion
				"<span class='danger'>[M.name] is buckled to [src] by [user.name]!</span>",
				"<span class='danger'>You are buckled to [src] by [user.name]!</span>",
				"<span class='notice'>You hear metal clanking.</span>")
```

2022-08-21 12:35 UTC, KIBORG04 commented on code/game/objects/buckling.dm
> +	if(!istype(M) || (!M.Adjacent(src)))
```suggestion
	if(!istype(M) || !M.Adjacent(src))
```
Не надо везде скобки пихать

2022-08-21 18:08 UTC, Bullethole commented
когда сам будешь куда то нырять будет ли задержка или так же?

2022-08-21 18:44 UTC, TungstenOctopus commented
> когда сам будешь куда то нырять будет ли задержка или так же?

Нет, если стоишь на тайле и хочешь сесть - задержки нет.

2022-08-22 04:48 UTC, kiVts commented
если нюка дала себя забаклить то это скил ишью

2022-08-22 08:03 UTC, TungstenOctopus commented
> если нюка дала себя забаклить то это скил ишью

игра не про скилл и не про абузы

2022-08-22 09:06 UTC, Tap0r commented
Игра про страдания врачей

2022-08-22 13:07 UTC, BunkyFly commented
Вопрос, а как теперь человека после реанимации спасать если он будет умирать мгновенно после оживления?

2022-08-22 20:27 UTC, kiVts commented
> > если нюка дала себя забаклить то это скил ишью
> 
> игра не про скилл и не про абузы

любая игра про скилл, покажи мне игру где скиловый чел не нагнет нуба, лол. 
если кто-то подпустил врага и простоял там достаточно долго что чел смог тебя забаклить, то это жуткий скилл скил ишью. 
Если ты соснул на нюке и дал себя забаклить, это еще не причина делать пр и агитировать это как абуз который нужно срочно чинить. Больше 3 лет так было и вот опять.

2022-08-22 20:56 UTC, TungstenOctopus commented
>Если ты соснул на нюке и дал себя забаклить, это еще не причина делать пр

а я взял и сделал

>агитировать это как абуз

это и есть абуз, как и другие инстастаны

2022-08-26 01:24 UTC, Lexakr commented
А я бы и на самостоятельное залезание в крио/слиперы сделал задержку. Очень маленькую, но чтобы она была

2022-08-26 14:22 UTC, BebraNuhach228 commented
> Вопрос, а как теперь человека после реанимации спасать, если он будет умирать мгновенно после оживления?

Вколоть ему заранее реагенты которые предотвратят моментальную смерть а не абузить универсальное крио?

2022-08-26 14:42 UTC, BebraNuhach228 commented
> если нюка дала себя забаклить то это скил ишью

так в первую очередь должна быть про рп и атмосферу а не про скилл и робаст, если ты такой скилловый робастер 3000 и хочешь показать свой ультра скилл то иди на ТГ или чё то подобное, хз

2022-08-26 14:53 UTC, necrofill commented
![image](https://user-images.githubusercontent.com/95982161/186932861-6a076300-ed0d-4b2b-bd3a-294710695d5a.png)

2022-08-27 08:23 UTC, BunkyFly commented
Имея задержку на использования крио будучи без скиллов, так ещё процесс бар на бакл раздражает и превращает все в афк гейминг.

2022-08-27 12:46 UTC, Kurshan commented
Ужасное решение, добавляющее проблемы и так вечно перегруженным врачам. Лучше добавить возможность выбраться из всего этого на попытку передвижения.

2022-08-27 14:03 UTC, volas commented
уберу лейбл, хочу одну общую задержку с #9892 и для всего подобного.

2022-08-27 16:59 UTC, Tap0r commented
Пиздец

2022-08-27 17:15 UTC, TauKitty commented
Этот запрос на слияние был упомянут в **Tau Ceti Station Forum**. Там могут быть соответствующие подробности:

https://forum.taucetistation.org/t/nasrali-vracham-v-rot-po-samye-glandy-spasibo/35303/1

2022-08-27 20:32 UTC, TungstenOctopus commented
Думаю стоит разделять определенные виды взаимодействия. Все же тут затрагивается несколько разного уровня девайсов, возможно вводить механику, ограничивающую их под одну гребенку, действительно неправильно.

* Задержка на пристегивание к стулу в принципе самая меньшая проблема и действительно может решаться убиранием бакла при движении. То есть тебя пристегнули > ты нажала WASD > ты отстегнулся. Спасибо @Kurshan  за идею. Таким образом из стульев задержку мы можем убрать, сославшись на легкость в освобождении.

* Задержка бакла на каталку оправдана именно тем, что ты падаешь, роняя все вещи. И двигаться после этого ты не можешь. Здесь на мой взгляд оправдана и задержка, и можно, как я и написал выше, действительно сделать анбакл на кнопки перемещения.

* По поводу крио: здесь однозначно есть проблема с тем, что крио тебя станит и уводит в безсознанку, таким образом сделать здесь легкое_высвобождение на WASD уже не получится.

Это конечно ожидаемо, что большая часть что местной публики, что набежавшей, не умеет в конструктив и не предлагает никаких решений, но призываю тех, кто умеет и могёт думать, следовать всем известному "критикуешь - предлагай".

2022-08-28 05:14 UTC, Deahaka commented
Так стулом тоже можно заробастить, но только ещё сильнее чем ящиком или каталкой... Не братан, давай раз убираем всё, то без исключений

2022-09-01 18:31 UTC, TungstenOctopus commented
Пара слов об апдейтах.
Теперь на стулья можно как и раньше баклить мгновенно, но игрок может сразу с него встать, просто пойдя в любую сторону. 
С каталками и кроватями ситуация обстоит так: если человек уже лежит, баклится без задержки, если нет - с задержкой.
Крио не трогал, все еще мизерная задержка

2022-09-04 10:55 UTC, TungstenOctopus commented
@volas сделал общую задержку, посмотри это ли ты имел в виду

2022-09-04 11:26 UTC, volas commented on code/__DEFINES/mob.dm
> +#define HUMAN_FORCED_BUCKLE_DELAY 16 // delay to possibly unwanted interactions like buckling, putting in cryo etc.
я имел в виду общий дефайн HUMAN_INTERACTION_OTHER (более общее название и назначение) который бы и использовался тут, и вместо OPTABLE_PUT_TIME ниже, и там где if(do_after(user, 24, target = target)) еще ниже

2022-09-04 14:07 UTC, TungstenOctopus commented on code/__DEFINES/mob.dm
> +#define HUMAN_FORCED_BUCKLE_DELAY 16 // delay to possibly unwanted interactions like buckling, putting in cryo etc.
> я имел в виду общий дефайн HUMAN_INTERACTION_OTHER (более общее название и назначение) который бы и использовался тут, и вместо OPTABLE_PUT_TIME ниже, и там где if(do_after(user, 24, target = target)) еще ниже

А, еще более общий. HUMAN_INTERACTION_DELAY норм нейминг?

2022-09-07 09:45 UTC, TungstenOctopus commented
@volas сделал общий дефайн

2022-09-10 23:01 UTC, volas requested changes

2022-09-10 23:01 UTC, volas commented on code/modules/atmospheric/machinery/components/unary_devices/cryo.dm
> +	if(do_after(user, 24, target = target))
дефайн?

2022-09-10 23:01 UTC, volas commented on code/game/machinery/OpTable.dm
> +			if(!do_after(user, HUMAN_INTERACTION_DELAY, target = C))
если граб-клики где-то рядом и они тоже с дуафтер, им тоже можно этот же дефайн поставить

2022-09-24 13:50 UTC, TungstenOctopus commented
@volas добавил использование дефайна в граб-бакл и в крио

2022-09-30 02:45 UTC, volas commented
>  То есть драг-н-дроп стал ближе к грабу, у которого все этих механики уже есть.

последний вопрос - если граб механики есть, у них где-то своя задержка прописана? Если да - то нужно посмотреть и возможно туда тоже добавить тот же дефайн, что бы дуафтеры не отличались.

2022-10-06 18:18 UTC, TungstenOctopus commented
> > То есть драг-н-дроп стал ближе к грабу, у которого все этих механики уже есть.
> 
> последний вопрос - если граб механики есть, у них где-то своя задержка прописана? Если да - то нужно посмотреть и возможно туда тоже добавить тот же дефайн, что бы дуафтеры не отличались.

Я не припомню каких-то задержек помимо бакла с грабом. Там в основном немного другие действия из разряда медосмотра (этодругое) и т.д.

2022-10-09 07:02 UTC, Deahaka commented on code/modules/mob/mob_movement.dm
> +		var/add_delay
Зачем это тебе?

2022-10-09 07:03 UTC, Deahaka commented
Или ты уже забросил борьбу против мира?

2022-10-23 11:25 UTC, volas commented
Помимо нерешенных вопросов с тестами,

> Я не припомню каких-то задержек помимо бакла с грабом. Там в основном немного другие действия из разряда медосмотра (этодругое) и т.д.

Ты просто сам же пишешь, что

> То есть драг-н-дроп стал ближе к грабу, у которого все этих механики уже есть.

Я и хочу узнать, где эти задержки и почему ты их не меняешь. Хотя-бы ссылки на код могут помочь понять, что бы я не разбирался сам.

2022-11-06 13:00 UTC, FelixRuin commented
> Ты просто сам же пишешь, что
> 
> > То есть драг-н-дроп стал ближе к грабу, у которого все этих механики уже есть.
> 
> Я и хочу узнать, где эти задержки и почему ты их не меняешь. Хотя-бы ссылки на код могут помочь понять, что бы я не разбирался сам.

Задержка граба в... задержке захвата в граб, тоесть на тот-же стол можно мгновенно положить грабом если предварительно взять в граб, но мгновенно это сделать нельзя.
Кроме этеракции с кровтью, там конкретно прописан момент с грабом и... там есть дифайн, да.

2022-11-27 18:47 UTC, closed without merging