Добавляет бандитам метательные ножи
TauCetiStation/TauCetiClassic pull request #9900
Opened 2022-08-23 13:49 UTC by simb11

## Описание изменений
Добавляет в аплинк контрабандиста тактический пояс с метательными ножами, стоит он 9ТК.
Ножик наносит 18 урона за бросок и гарантированно застревает в теле. 
![image](https://user-images.githubusercontent.com/84613249/186168954-2cecf95e-a99b-4733-9d1b-af3c3eadb20a.png)

## Почему и что этот ПР улучшит
У бандитов будет возможность без особых трудностей убивать офицеров в пуленепробиваемой броне. Сейчас бандиты ничего не могут сделать офицерам в буллетпруфе, ведь у дилера из оружия есть только огнестрел и обычные ножи, от первого защищает броня, от второго любое ренж оружие.
## Авторство
Спрайт ножа взял у фоллаут13.
## Чеинжлог
:cl: Simbaka
- add: В ассортименте контрабандиста появились метательные ножи.

2022-08-23 13:49 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2022-08-23 14:03 UTC, AndroBetel commented
некрасивый

2022-08-27 14:11 UTC, volas approved these changes
по коду ок

2022-09-02 12:32 UTC, UDaV73rus requested changes
спрайт ужас, и инхендов нет

2022-09-02 14:34 UTC, simb11 commented
поменял спрайтт

2022-09-04 07:10 UTC, UDaV73rus approved these changes
Кухонный нож вместо метательного, но пофиг. Женщины..........

2022-09-05 18:32 UTC, merged