point to
TauCetiStation/TauCetiClassic pull request #9917
Opened 2022-08-26 18:02 UTC by notkripton

## Описание изменений
Убран кд для поинт ту. Добавлен поинт ту для гостов с фиолетовой стрелочкой, который виден только им (и тем кто видит гостов). Когда гост указывает на что-то об этом пишется в госточат с ссылкой на указывающего.
## Почему и что этот ПР улучшит
Для плееров хонк, для гостов еще одно удобство для наблюдения за раундами.
## Чеинжлог
:cl:
 - add: Призраки получили свой поинт ту с фиолетовой стрелочкой, который виден только между ними.

2022-08-26 18:02 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2022-08-26 18:07 UTC, notkripton commented on code/modules/mob/emote.dm
> +			to_chat(M, tracker + message)
Тут еще у всех гост-ми эмоутов будет ссылка на автора, но думаю никто не против

2022-08-26 18:11 UTC, KIBORG04 commented on code/modules/mob/mob.dm
> -	next_point_to = world.time + 1.5 SECONDS
Ты не думал зачем этот кд добавляли?

2022-08-26 19:01 UTC, notkripton commented on code/modules/mob/mob.dm
> -	next_point_to = world.time + 1.5 SECONDS
Чтобы игроки не сравнили много объектов?

2022-08-27 11:57 UTC, KIBORG04 commented on code/modules/mob/mob.dm
> -	next_point_to = world.time + 1.5 SECONDS
Чтобы игроки не убили сервер, чтобы не спамили сообщением.

2022-08-27 12:37 UTC, KIBORG04 commented on code/_onclick/click.dm
> +/mob/proc/MiddleShiftClick(atom/A)
Есть же точно такой же `MiddleShiftClickOn()`, не? Зачем менять эту сигнатуру, я не очень понял.

2022-08-27 12:39 UTC, KIBORG04 commented on code/modules/mob/dead/observer/observer.dm
> +/mob/dead/observer/pointed(atom/A as mob|obj|turf in view(client.view, src))
```suggestion
/mob/dead/observer/pointed(atom/A))
```
а зачем? Есть же ..() вызов? Че блин вообще с вербами происходит...

2022-08-27 12:39 UTC, KIBORG04 commented on code/modules/mob/living/living.dm
> +		return
фолсы-тру возвращай, раз уж в других местах возвращаешь

2022-08-27 12:40 UTC, KIBORG04 commented on code/game/objects/effects/decals/misc.dm
> +/obj/effect/decal/point/ghost
Сюда бы прикрутить фичу, чтобы челики с особкой на гостов видели и гостовские поинт-ту.

2022-08-27 12:49 UTC, Kurshan commented on code/modules/mob/mob.dm
> -	next_point_to = world.time + 1.5 SECONDS
Поинт ту мерзкая штука из-за того что относительно дорогая. Спавн объекта+oview+мессага в чат+таймер на удаление. Mozhno ne nado. Какие вообще аргументы за то, чтобы убирать КД?

2022-08-27 13:05 UTC, notkripton commented on code/modules/mob/mob.dm
> -	next_point_to = world.time + 1.5 SECONDS
У нас совсем недавно добавили сообщение при экзамайне которое литералли то же самое просто вместо миддлклика левый. При желании чат ещё сильнее можно засрать, так что это вообще не аргумент.

Ну а как ты собрался убивать сервер стрелками с одним куделом внутри я вообще не ебу. По такой логике сервер можно убить и партиклами от цепи командования, они же тоже без кд спавнятся и ими тоже очень часто срут игроки.

А ещё стрелки без кд годами работают на тэгэ стейшоне, даа.. 🤓 (а у нас они, кстати, ещё и меньше живут)

2022-08-27 13:07 UTC, Kurshan commented on code/modules/mob/mob.dm
> -	next_point_to = world.time + 1.5 SECONDS
>Какие вообще аргументы за то, чтобы убирать КД?

Всё ещё не получил ответ на вопрос. А подход: ну есть тратящее ресурсы говно, так значит можно всё в таком ключе делать, зачем париться. Уже оптимизацию билда до плачевного состояния

2022-08-27 13:12 UTC, KIBORG04 commented on code/modules/mob/mob.dm
> -	next_point_to = world.time + 1.5 SECONDS
На тг не фиксят баги годами, ревью посредственное, кодеры дебилы. А если есть и другие абузы, то и их бы пофиксить, но сначала нужно демки выпилить.

2022-08-27 13:13 UTC, Kurshan commented on code/modules/mob/mob.dm
> -	next_point_to = world.time + 1.5 SECONDS
Оффтопну, хотя бы выключать контроллер реплеев при наличии админов. Пускай работают, хуле

2022-08-27 13:23 UTC, notkripton commented on code/modules/mob/mob.dm
> -	next_point_to = world.time + 1.5 SECONDS
Да на тг если кто-то и соберётся добавлять на это кд то его говном закидают потому что там это любимая фича. По сути через спам поинт ту РЕАЛЬНО заставляет обращать на себя внимание и имхо это в принципе очень забавно смотрится

2022-08-27 13:25 UTC, Kurshan commented on code/modules/mob/mob.dm
> -	next_point_to = world.time + 1.5 SECONDS
Любимая фича спамить. З а б а в н о  с м о т р и т с я 
Как аргумент. класс.

2022-08-27 13:41 UTC, notkripton commented on code/modules/mob/mob.dm
> -	next_point_to = world.time + 1.5 SECONDS
Ты вообще блять о чем? Я не преподносил забавность как аргумент, поэтому и поставил ИМХО. Настоящий аргумент ты вообще в ответе заигнорил, так что отсылаю на мое прошлое сообщение.

2022-08-27 13:54 UTC, notkripton commented on code/modules/mob/dead/observer/observer.dm
> +/mob/dead/observer/pointed(atom/A as mob|obj|turf in view(client.view, src))
По сути у меня были опасения что могут возникнуть проблемы с выбором цели через список или контекстное меню, но сейчас проверил и все норм. Так что исправлю.

2022-08-27 13:55 UTC, notkripton commented on code/modules/mob/living/living.dm
> +		return
Здесь забыл сделать, ты прав.

2022-08-27 13:56 UTC, notkripton commented on code/game/objects/effects/decals/misc.dm
> +/obj/effect/decal/point/ghost
Да, я думал об этом, по идее все уже сейчас должно работать, но я не проверял

2022-08-27 14:01 UTC, notkripton commented on code/_onclick/click.dm
> +/mob/proc/MiddleShiftClick(atom/A)
Я вроде делал но для какой-то великой цели, но уже забыл для какой так что верну как было

2022-08-27 14:08 UTC, KIBORG04 commented on code/game/objects/effects/decals/misc.dm
> +/obj/effect/decal/point/ghost
Не должно, хуман не видит призраков через see_invisibility. Он видит через жопные приколы с альтернейт_аппирансом.

2022-08-27 14:12 UTC, notkripton commented on code/game/objects/effects/decals/misc.dm
> +/obj/effect/decal/point/ghost
Понял, можешь подсказать как мне лучше всего сделать чтобы видел?

2022-08-27 14:19 UTC, KIBORG04 commented on code/game/objects/effects/decals/misc.dm
> +/obj/effect/decal/point/ghost
Нормально я хз как сделать, станет еще более лагучим.

но поидее, через такой прикол, как у гостов с тем же плейном и тем же АА

![image](https://user-images.githubusercontent.com/26389417/187034109-c36d9211-9214-4954-8ff5-62290760452a.png)

<hr>

Либо же, хз лучше ли, создавать еще один объект `/obj/effect/decal/point/ghost/AA` с нужным плейном GHOST_ILLUSION_PLANE, эффектами и своим же удалением. Это быстрее альт_аппиранских приколов, но не будет синхронизации, если вдруг стрелочка научится летать там куда-то.

2022-08-29 09:14 UTC, notkripton commented on code/game/objects/effects/decals/misc.dm
> +/obj/effect/decal/point/ghost
сделал, проверяй


![image](https://user-images.githubusercontent.com/75007994/187167221-9dececde-fbeb-4c7c-91b6-193b71659596.png)

2022-09-02 22:23 UTC, KIBORG04 requested changes
В основном, аппруве, но я все еще не знаю как лучше реализовать гостовский поинт ту для особки, мысли тут https://github.com/TauCetiStation/TauCetiClassic/pull/9917#discussion_r956587356.

Так как щас юзается система АА для поинт_ту госта, то использование КД становится еще актуальнее. Верни кд, всё равно это не особо проблем создаёт игрокам.

2022-09-07 20:23 UTC, notkripton commented
> то использование КД становится еще актуальнее

Добавил

2022-09-24 12:02 UTC, KIBORG04 approved these changes
Жду конфликты

2022-09-25 17:19 UTC, merged