Phoron contagion fix
TauCetiStation/TauCetiClassic pull request #9939
Opened 2022-08-30 00:54 UTC by Elisei24

## Описание изменений
Теперь космические костюмы и биосьюты защищают от воздействия форона, как и должны.
## Почему и что этот ПР улучшит
fixes #9937 
fixes #7058
fixes #3940
## Авторство
Ya
## Чеинжлог
:cl: Elisei
 - bugfix: Форон заражал вещи сквозь риги и биосьюты.

2022-08-30 00:54 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2022-08-30 06:40 UTC, kalazus commented on code/modules/atmospheric/ZAS/Phoron.dm
> +		else if(wear_suit.body_parts_covered & ARMS & LEGS)
Даже если это работает, лучше проверять body_parts_covered & (UPPER_TORSO|LOWER_TORSO|LEGS|ARMS). У нас сейчас ничего кроме костюмов и шлемов не защищает от форона, так что действительно можно убрать перчатки и ботинки.

2022-08-30 08:21 UTC, Elisei24 commented on code/modules/atmospheric/ZAS/Phoron.dm
> +		else if(wear_suit.body_parts_covered & ARMS & LEGS)
Тоже об этом думал, но мало ли, что там наследует/будет наследовать этот флаг, на всякий случай указал.

Поправлю.

2022-08-30 08:41 UTC, Elisei24 commented on code/modules/atmospheric/ZAS/Phoron.dm
> +		else if(wear_suit.body_parts_covered & ARMS & LEGS)
А что вообще BIT_TEST_ALL возвращает?

2022-08-30 08:45 UTC, kalazus commented on code/modules/atmospheric/ZAS/Phoron.dm
> +		else if(wear_suit.body_parts_covered & ARMS & LEGS)
Тру/фолс. Это просто дефайн для правильной проверки что есть все флаги.

2022-09-01 23:16 UTC, LudwigVonChesterfield commented on code/modules/atmospheric/ZAS/Phoron.dm
> +	if(wear_suit)
можно ли переписать чтобы было меньше уровней вложенности? как минимум две ифки снизу объединить в одну `vsc.plc.PHORONGUARD_ONLY && (wear_suit.flags & PHORONGUARD)`

2022-09-02 07:20 UTC, kalazus commented on code/modules/atmospheric/ZAS/Phoron.dm
> +	if(wear_suit)
Вообще, не сказать что проверка правильная даже. Т.к. одежда должна защищать только при PHORONGUARD.

2022-09-07 17:50 UTC, Elisei24 commented on code/modules/atmospheric/ZAS/Phoron.dm
> +	if(wear_suit)
А что в ней не так?
Проблема была какая: автор этой системы задумывал, чтобы не заражалась только одежда с phoronguard, либо закрытая герметичным скафандром

Проверка на скафандр не работала, так что я её переписал и она теперь работает.

2022-09-07 17:52 UTC, Elisei24 commented on code/modules/atmospheric/ZAS/Phoron.dm
> +	if(wear_suit)
> можно ли переписать чтобы было меньше уровней вложенности? как минимум две ифки снизу объединить в одну `vsc.plc.PHORONGUARD_ONLY && (wear_suit.flags & PHORONGUARD)`

Делал так же, как у автора это сделано выше с проверкой на шлем. Если уж менять, то менять всё.

Либо оставить так, работает и слава богу 🤔

2022-09-07 18:24 UTC, kalazus commented on code/modules/atmospheric/ZAS/Phoron.dm
> +	if(wear_suit)
Так ты скопировал неправильно, сейчас любая верхняя одежда, закрывающая все те битфлаги защищает от форона.

2022-09-07 23:25 UTC, Elisei24 commented on code/modules/atmospheric/ZAS/Phoron.dm
> +	if(wear_suit)
> Так ты скопировал неправильно, сейчас любая верхняя одежда, закрывающая все те битфлаги защищает от форона.

А, да, ты прав. В таком случае даже firesuit защищал от форона. Сейчас поправлю.

2022-09-08 13:08 UTC, volas commented
> pl
> vsc
> plc

ппц

2022-09-14 21:06 UTC, volas commented on code/modules/atmospheric/ZAS/Phoron.dm
> +		else if (wear_suit.body_parts_covered & UPPER_TORSO|LOWER_TORSO|LEGS|ARMS)
мне кажется неправильным, что только wear_suit проверяется.

Насколько понимаю, поведение в ветке PHORONGUARD_ONLY выше ок, а здесь нужно проверять не только, покрывает ли костюм части тела - но еще и ботинки/перчатки. Возможно human.coverage, что выше в старом коде, тут подойдет.

~~А вообще механика дебильная, код дебильный, переменные дебильные.~~

2022-09-14 21:06 UTC, volas requested changes
^

2022-09-14 22:04 UTC, kalazus commented on code/modules/atmospheric/ZAS/Phoron.dm
> +		else if (wear_suit.body_parts_covered & UPPER_TORSO|LOWER_TORSO|LEGS|ARMS)
Если говорить честно, то хватило бы в phoronguardonly вместо ретурна поставить continue, и убрать 2-ой phoronguardonly
Но по факту ни перчатки, ни ботинки не могут полностью закрыть ноги от воздействия. Кроме того, нету перчаток или ботинок с PHORONGUARD.

2022-09-14 22:35 UTC, volas commented on code/modules/atmospheric/ZAS/Phoron.dm
> +		else if (wear_suit.body_parts_covered & UPPER_TORSO|LOWER_TORSO|LEGS|ARMS)
> Кроме того, нету перчаток или ботинок с PHORONGUARD.

Да, но насколько я понимаю механику PHORONGUARD_ONLY из
``var/PHORONGUARD_ONLY_DESC = "If this is on, only biosuits and spacesuits protect against contamination and ill effects."``

Если он TRUE - то нам важен именно костюм и именно с флагом PHORONGUARD. Если FALSE - то сойдет обычная одежда без флага, главное что бы был набор (ботинок, костюма и перчаток, почему голова никому не нужна? а хз).

2022-09-15 05:40 UTC, kalazus commented on code/modules/atmospheric/ZAS/Phoron.dm
> +		else if (wear_suit.body_parts_covered & UPPER_TORSO|LOWER_TORSO|LEGS|ARMS)
Эта штука проверяет защищены ли трусы от форона.
Хз, у нас вроде форон это воздух, а обеспечить полную защиту от него может только полноценный костюм, а не набор из рандомных элементов.

2022-09-30 02:54 UTC, volas commented
Фикс хороший и нужный, если автор не вернется - подхватите кто нибудь может.

2023-05-23 13:52 UTC, ViDLiathan commented
Почините. Всё ещё идет заражение

2023-05-23 15:24 UTC, closed without merging