RnD resprite by WalterJe
TauCetiStation/TauCetiClassic pull request #9991
Opened 2022-09-04 15:14 UTC by NinjaPikachuska

## Описание изменений
![image](https://user-images.githubusercontent.com/89906909/188319137-5059db04-2e05-4ad7-a1bd-3d881dba99e5.png)
Изменены спрайты автолата, анализатора, принтера плат, протолата и фабрикатора роботехов (скрин выше немного устарел, смотрите ниже).
Также у них появился стейт без питания.

https://user-images.githubusercontent.com/89906909/188320168-acf20eca-8711-4826-a581-31ca74003274.mp4

Раскрученное состояние:
![image](https://user-images.githubusercontent.com/89906909/188320400-3aea0d2b-e1be-4371-a728-488013606bc9.png)

## Почему и что этот ПР улучшит
Красиво
## Авторство
WalterJe
## Чеинжлог
:cl: WalterJe
 - image: Респрайт РнД машинерии и автолата.

2022-09-04 15:14 UTC, TauKitty commented
###### Changelog status: :heavy_check_mark:

2022-09-04 15:16 UTC, KIBORG04 commented
автолат это не только рнд машинерия

2022-09-04 15:18 UTC, DarthSidiousPalpatine commented
Давайте скорее, я хочу сделать им аниму как они собирают/разбирают внутри предметы, будет афигенно.

2022-09-04 15:22 UTC, KIBORG04 commented on code/game/machinery/autolathe.dm
> +/obj/machinery/autolathe/power_change()
измени это на какой-то update_icon

2022-09-04 15:22 UTC, KIBORG04 commented on code/game/machinery/autolathe.dm
> +		power_change()
измени это на какой-то update_icon

2022-09-04 15:22 UTC, KIBORG04 commented on code/game/mecha/mech_fabricator.dm
> +		power_change()
измени это на какой-то update_icon

2022-09-04 15:22 UTC, KIBORG04 commented on code/game/mecha/mech_fabricator.dm
> +/obj/machinery/mecha_part_fabricator/power_change()
измени это на какой-то update_icon

2022-09-04 15:23 UTC, KIBORG04 commented on code/modules/mining/mining_fabricator/mining_fabricator.dm
> +		power_change()
измени это на какой-то update_icon

2022-09-04 15:23 UTC, KIBORG04 commented on code/modules/research/circuitprinter.dm
> +		power_change()
измени это на какой-то update_icon

2022-09-04 15:23 UTC, KIBORG04 commented on code/modules/research/destructive_analyzer.dm
> +			power_change()
измени это на какой-то update_icon

2022-09-04 15:24 UTC, KIBORG04 commented on code/modules/research/destructive_analyzer.dm
> +			power_change()
а не, вот здесь кажись не надо. Но странный вообще прок и его название, вроде же есть прок, который при деконструкте надо вызывтаь

2022-09-04 19:44 UTC, UDaV73rus approved these changes

2022-09-12 01:44 UTC, volas requested changes

2022-09-12 01:44 UTC, volas commented on code/game/machinery/autolathe.dm
> +		add_overlay("[initial(icon_state)]-open")
10 вызовов update_icon без изменения статуса панели - у нас спрайт с 10 одинаковыми оверлеями. Обычно мы делаем общий cut_overlays в начале, а уже потом накладываем опциональные оверлеи обратно

2022-09-12 01:44 UTC, volas commented on code/game/machinery/autolathe.dm
> +			cut_overlay("[initial(icon_state)]_glass")
есть ли причина менять flick на оверлеи? sleep в attack_by очень сомнителен

2022-09-14 21:56 UTC, volas commented on code/game/mecha/mech_fabricator.dm
> +	if(default_deconstruction_screwdriver(user, "fab", "fab", W))
с default_deconstruction_screwdriver немного коряво получилось, что он не поддерживает оверлеи. Нужно переписывать его, ну ладно, когда нибудь потом.

2022-09-14 21:56 UTC, volas approved these changes

2022-09-14 21:56 UTC, merged

2022-09-15 12:58 UTC, TauKitty commented
Этот запрос на слияние был упомянут в **Tau Ceti Station Forum**. Там могут быть соответствующие подробности:

https://forum.taucetistation.org/t/protest-resprajt-mashinerii-rnd/35578/8